### ISSUE TITLE
opencart 3.0.3.7 facebook ads extension CREATE privilage is added but not creating oc_facebook_products!!!!

### ISSUE THREAD

**Issue by artemraab** [opencart/opencart#10115]
Hi, I downloaded new xampp of older version (7.3) instead of 8.0 I had and now it somehow overwrote the permissions or something with the users that I granted to opencart3 db and somebody explained to me it was cache conflict and it seems like the installation to new c:/xampp2 folder fixed the c:/xampp folder maria db settings with permissions so the user list now shows fine and i can see and edit priviliges/permissions to my opencart3 db. But my main issue is not fixed yet!!! The facebook ads extension was uninistalled in modifications, modifications were refreshed, the extension was disabled and enabled as well, everything was done two times, page was refreshed but it keeps saying that the permission to CREATE table is not granted to my opencart3_admin that I use for the db opencart3 however, it's granted all permission for this database. Also facebook event manager says that opencart version supported by it are ending with 3.0.2.x and my opencart version is 3.0.3.7 which maybe the issue or not? it's simply CREATE table that doesn't happen... it says JSON.parse error happens when I go to facebook business extension. Why the extension doesn't create the table in my opencart3 db after i follow the pictured instruction on facebook business? any idea how to fix issue with creating oc_facebook_proudct table? **Screenshots:**
![image](https://user-images.githubusercontent.com/69615476/128427349-2ac7282b-11e1-4ae5-ab54-d91786c703f6.png)
![image](https://user-images.githubusercontent.com/69615476/128427374-8ea4ef2d-88c1-4961-a1c6-7efd001e094d.png)
![image](https://user-images.githubusercontent.com/69615476/128427413-cf906c48-0277-403b-907c-834b14be6358.png)
![image](https://user-images.githubusercontent.com/69615476/128427506-abb77946-108d-4a59-84d8-cf9d387542aa.png)
Thanks.

**Comment by TheCartpenter** [comment]
This is an extension issue. Please post on the Opencart forum.

**Comment by mhcwebdesign** [comment]
Also, in addition to posting it on the OpenCart forum, please be so kind to break down your problem description in smaller paragraphs, to make it easier to read and understand.
