### ISSUE TITLE
html_entity_decode not performed for passwords in checkout/login, may cause mismatch of hash

### ISSUE THREAD

**Issue by photographer-mememe** [opencart/opencart#10113]
**What version of OpenCart are you reporting this for?**
master branch 

**Describe the bug**
controller/checkout/login does not do html_entity_decode for the password, while controller/account/login does.
library/cart/customer does not do html_entity_decode for the password
model/customer hashes the password with html_entity_decode to the database.

So special characters may cause a mismatch of hash for checkout/login

I did not check admin users.

**Comment by danielkerr** [comment]
page was removed
