### ISSUE TITLE
Totals incorrect in Reports>Products>Purchased

### ISSUE THREAD

**Issue by stokeyblokey** [opencart/opencart#1014]
The sum is incorrectly working out product prices as shown below:

Example Product A is £15.99 including 20% VAT - net price is £13.3250 and VAT is £2.665

The sum in the report is doing this:

SUM(op.total + op.total \* op.tax / 100) AS total where op.total is op.price \* op.quantity

This is calling the op.tax field value and it should not be! This field is a value, not a tax rate, so it varies for every item!

So for the above example it calculates thus:

SUM(13.3250 + ((13.3250*2.665)/100)) = £13.68

It SHOULD be calculating like this:

SUM(13.3250 + ((13.3250*20)/100)) = £15.99

Potential fix:

Open admin\model\report\product.php

Find:

public function getPurchased($data = array()) {
$sql = "SELECT op.name, op.model, SUM(op.quantity) AS quantity, SUM(op.total + op.total \* op.tax / 100) AS total FROM " . DB_PREFIX . "order_product op LEFT JOIN `" . DB_PREFIX . "order` o ON (op.order_id = o.order_id)";

Change to:

public function getPurchased($data = array()) {
$sql = "SELECT op.name, op.model, SUM(op.quantity) AS quantity, SUM(op.total + op.tax) AS total FROM " . DB_PREFIX . "order_product op LEFT JOIN `" . DB_PREFIX . "order` o ON (op.order_id = o.order_id)";

**Comment by LennyLip** [comment]
+1 opencart 2.0.3 Totals incorrect

**Comment by arnisjuraga** [comment]
Huge!
