### ISSUE TITLE
Issue with Guest Checkout/User Registration

### ISSUE THREAD

**Issue by krishna-7** [opencart/opencart#10175]
When I try to do  a Guest check out then it shows an error, same when I try to register a new user. User registration is happening and users are able to login but its giving internal server error just after registration.

OC Version  : 3.0.3.7
Domain : mymunchbox.in
PHP Version : 8.0.8
![image](https://user-images.githubusercontent.com/10972564/130778798-61fa301a-ce79-463b-a9b2-ecc2aa7245ac.png)

After Registration (a blank page is displayed) : 
![image](https://user-images.githubusercontent.com/10972564/130779128-545dfa6c-8553-4f3a-8e72-f37217ced1d0.png)

![image](https://user-images.githubusercontent.com/10972564/130779228-02640e9e-1cb8-4d09-a4f4-d989c0c570a3.png)

Apache error logs : 
[Wed Aug 25 16:14:24.394029 2021] [php:error] [pid 358080] [client 45.115.91.73:42066] PHP Fatal error:  Uncaught Exceptio
n: Error: Could not load template /var/www/html/catalog/view/theme/checkout/guest.twig! in /var/www/html/system/library/te
mplate/twig.php:17\nStack trace:\n#0 /var/www/html/system/library/template.php(51): Template\\Twig->render()\n#1 /var/www/
html/system/engine/loader.php(125): Template->render()\n#2 /var/www/html/catalog/controller/checkout/guest.php(140): Loade
r->view()\n#3 /var/www/html/system/engine/action.php(79): ControllerCheckoutGuest->index()\n#4 /var/www/html/catalog/controller/startup/router.php(25): Action->execute()\n#5 /var/www/html/system/engine/action.php(79): ControllerStartupRouter->index()\n#6 /var/www/html/system/engine/router.php(67): Action->execute()\n#7 /var/www/html/system/engine/router.php(56): Router->execute()\n#8 /var/www/html/system/framework.php(169): Router->dispatch()\n#9 /var/www/html/system/startup.php(104): require_once('...')\n#10 /var/www/html/index.php(19): start()\n#11 {main}\n  thrown in /var/www/html/system/library/template/twig.php on line 17, referer: http://mymunchbox.in/index.php?route=checkout/checkout

[Wed Aug 25 16:29:02.971077 2021] [php:error] [pid 369869] [client 45.115.91.73:15302] PHP Fatal error:  Uncaught Exceptio
n: Error: Could not load template /var/www/html/catalog/view/theme/mail/register.twig! in /var/www/html/system/library/tem
plate/twig.php:17\nStack trace:\n#0 /var/www/html/system/library/template.php(51): Template\\Twig->render()\n#1 /var/www/h
tml/system/engine/loader.php(125): Template->render()\n#2 /var/www/html/catalog/controller/mail/register.php(43): Loader->
view()\n#3 /var/www/html/system/engine/action.php(79): ControllerMailRegister->index()\n#4 /var/www/html/system/engine/eve
nt.php(62): Action->execute()\n#5 /var/www/html/system/engine/loader.php(255): Event->trigger()\n#6 /var/www/html/system/e
ngine/proxy.php(47): Loader->{closure}()\n#7 /var/www/html/catalog/controller/account/register.php(22): Proxy->__call()\n#
8 /var/www/html/system/engine/action.php(79): ControllerAccountRegister->index()\n#9 /var/www/html/catalog/controller/star
tup/router.php(25): Action->execute()\n#10 /var/www/html/system/engine/action.php(79): ControllerStartupRouter->index()\n#
11 /var/www/html/system/engine/router.php(67): Action->execute()\n#12 /var/www/html/system/engine/router.php(56): Router->execute()\n#13 /var/www/html/system/framework.php(169): Router->dispatch()\n#14 /var/www/html/system/startup.php(104): require_once('...')\n#15 /var/www/html/index.php(19): start()\n#16 {main}\n  thrown in /var/www/html/system/library/template/twig.php on line 17, referer: http://mymunchbox.in/index.php?route=account/register

Is this due to a PHP version issue? 
* Using a 3rd party theme

**Comment by mhcwebdesign** [comment]
OpenCart 3.0.3.7 works just fine on PHP 8.

Have you done the obvious and checked for the existence of file  **/var/www/html/catalog/view/theme/mail/register.twig** ?
It could also be an issue with the Twig rendering engine, the latter is extremely slow on our local test server using PHP 8.0.9.

For the time being, you should use the previous PHP 7.4 and wait till OpenCart 4.0.0.0 is ready before switching over to PHP 8.

**Comment by krishna-7** [comment]
I tried replacing the template folder and now its working fine.
