### ISSUE TITLE
Accept payments in non default currency

### ISSUE THREAD

**Issue by go4mbbs** [opencart/opencart#10170]
**What version of OpenCart are you reporting this for?**
3.0.3.7

**Describe the bug**
Even if I change the store currency, on the payment gateway, it takes the Default currency for payment processing. 

**To Reproduce**
1. Leave the default currency set as USD
2. Leave the other currencies like Euro as they are
3. Go to store front, select Euro as the currency from selector
4. The updated prices of items will show correctly in Euro
5. Proceed to payment gateway using any plugin (I used 2checkout)
6. The payment will still be processed in Dollars and not Euros

**Expected behavior**
The converted amount of currency should have been processed instead of the default currency

**Screenshots / Screen recordings**
Not applicable

**Server / Test environment (please complete the following information):**
 - Web server
 - LAMP
 - PHP 7.4
 - Chrome
 - Latest

**Additional context**

**Comment by WebkulOpencart** [comment]
@go4mbbs your payment method should send the currency value as per the payment API. This is not an issue related to OpenCart. 
Please report the same on opencart forum.
