### ISSUE TITLE
Problem changing catalog folder name 

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10174]
// Hard coding css so they can be replaced via the events system.
$data['bootstrap_css'] = 'catalog/view/stylesheet/bootstrap.css';
$data['fonts'] = '//fonts.googleapis.com/css?family=Open+Sans:400,400i,300,700';
$data['icons'] = 'catalog/view/stylesheet/icon/fontawesome/css/all.css';
$data['stylesheet'] = 'catalog/view/stylesheet/stylesheet.css';

to 

config.php 
define('DIR_APPLICATION_NAME', 'frontend/');
define('DIR_APPLICATION', DIR_OPENCART . DIR_APPLICATION_NAME . '/');

// Hard coding css so they can be replaced via the events system.
$data['bootstrap_css'] =  DIR_APPLICATION_NAME . '/view/stylesheet/bootstrap.css';
$data['fonts'] = '//fonts.googleapis.com/css?family=Open+Sans:400,400i,300,700';
$data['icons'] =  DIR_APPLICATION_NAME. '/view/stylesheet/icon/fontawesome/css/all.css';
$data['stylesheet'] =  DIR_APPLICATION_NAME. '/view/stylesheet/stylesheet.css';

https://github.com/opencart/opencart/blob/43fb20cf7b5977aaaebb605548e44b9120e6f399/upload/catalog/controller/common/header.php#L29

**Comment by danielkerr** [comment]
no need to change catalog. could even have a scrtipts folder.
