### ISSUE TITLE
session path double slash error

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10173]
'path'     => !empty($_SERVER['PHP_SELF']) ? dirname($_SERVER['PHP_SELF']) . '/' : '',

to

'path'     => !empty($_SERVER['PHP_SELF']) ? str_replace("//", "/", dirname($_SERVER['PHP_SELF']) . '/') : '',

https://github.com/opencart/opencart/blob/43fb20cf7b5977aaaebb605548e44b9120e6f399/upload/catalog/controller/startup/session.php#L52

**Comment by TheCartpenter** [comment]
```'path' => !empty($_SERVER['PHP_SELF']) ? preg_replace('/(\/+)/', '/', dirname($_SERVER['PHP_SELF']) . '/') : '',```

Source: https://stackoverflow.com/a/6339317

**Comment by danielkerr** [comment]
$_SERVER['PHP_SELF'] will not providee a double slash error

**Comment by eturerer** [comment]
$option = [
			'expires'  => 0,			
			'path' => !empty($_SERVER['PHP_SELF']) ? preg_replace('/(\/+)/', '/', dirname($_SERVER['PHP_SELF']) . '/') : '',
			'secure'   => $this->request->server['HTTPS'],
			'httponly' => false,
			'SameSite' => $this->config->get('session_samesite')
		];

		echo 'opencart orginal : ' .  dirname($_SERVER['PHP_SELF']) . '/' . '<hr>' ;
		echo 'opencart mod : ' .  preg_replace('/(\/+)/', '/', dirname($_SERVER['PHP_SELF']) . '/') . '<hr>' ;

output 

opencart orginal : //
opencart mod : /

**Comment by ADDCreative** [comment]
@danielkerr the problem is dirname. For '/index.php' it will return / (or \ on windows).

@eturerer You need to also check for \\.

See https://www.php.net/manual/en/function.dirname.php#example-2083.
