### ISSUE TITLE
session_start();

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#10185]
Through out the files, there is no reference to session_start(), and session_id(). This gave me following error message when initializing the session:

Error: Typed property Opencart\System\Library\Session::$session_id must not be accessed before initialization in ...\system\library\session.php on line 89

Here is a fix I propose, by appending these two lines in library\session.php constructor:

    session_start();
    $this->session_id = session_id();

After this patch, my scripts got fine tuned. What do you suggest?

**Comment by eturerer** [comment]
if (session_status() == PHP_SESSION_NONE) {
      session_start();
  }

**Comment by ADDCreative** [comment]
OpenCart doesn't us native PHP sessions, so calling session_start is pointless. Looking at the line number of your error is looks like your library\session.php has been modified, which is probably the cause of your error.

**Comment by anytizer** [comment]
@ADDCreative The line numbers got shifted because I had my patch lines commented out in my constructor.

The actual problem was in the following code block:

    public function close(): void {
    	$this->adaptor->write($this->session_id, $this->data);
    }

And, clearly, $this->session_id was never assigned a value. My patch worked for me.
But still there is a potential error at another level; to match session_id() to '/^[a-zA-Z0-9,\-]{22,52}$/' to my solution.

Instead, I later found that the actual solution should include the following call right after initializing the session:

    $session->start($session_id);

That I missed in my custom code. The full solution seems like to be:
```
$session_id = /^[a-zA-Z0-9,\-]{22,52}$/
$session = new Session('db', $registry);
$registry->set('session', $session);

$session->start($session_id);
```
