### ISSUE TITLE
Repeated language variables in forgotten.php

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#10183]
https://github.com/opencart/opencart/blob/master/upload/catalog/language/en-gb/account/forgotten.php

error_password, error_confirm => These blocks are repeated here.

**Comment by anytizer** [comment]
I updated the link.

**Comment by TheCartpenter** [comment]
Ok, PR created: https://github.com/opencart/opencart/pull/10184 .

**Comment by TheCartpenter** [comment]
@WebkulOpencart: Needs master branch tag.

**Comment by danielkerr** [comment]
nothing repeated n current code
