### ISSUE TITLE
Changelog at new version?!

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#10180]
While it is quite nice when a new version is released: https://github.com/opencart/opencart/releases/tag/3.0.3.8
But - sorry, as always .. - where is the changelog?
Missing such badly, currently only that is published:

> RTL related issues resolved
Resolved other Github issues.

And a advertising link.

That is clearly not enough!
**See no reason to use that version and not any previous.**

Also that this latest version is not published at the official OpenCart Download page: https://www.opencart.com/index.php?route=cms/download

It seems that OpenCart needs someone like a "Release Manager" .. ?!

**Comment by danielkerr** [comment]
will do this next release.
