### ISSUE TITLE
Using DB Transactions

### ISSUE THREAD

**Issue by mathiasgrimm** [opencart/opencart#10189]
Are we not using db transactions for operations that involve multiple tables? like edit product for exemple.
What happens if the program crashes in between the first and the last db operation?

**Comment by TheCartpenter** [comment]
OC version. OC forum request.

**Comment by mathiasgrimm** [comment]
Don't have a forum account. Version would be the current version (3).
But as far as I could see there's no database transactions at all. just wanted that confirmed

**Comment by osworx** [comment]
> 
> 
> But as far as I could see there's no database transactions at all. just wanted that confirmed

Correct.

**Comment by mathiasgrimm** [comment]
Should I create a PR to fix it or there's a particular reason for that being like that?

**Comment by TheCartpenter** [comment]
You could always try with a PR.

**Comment by TheCartpenter** [comment]
> What do you mean? Why would it not be accepted? I mean, its not even safe to use it the way it is right now

If that being the case, then show the codes you are referring about on a PR specifically with the changes you're looking to demonstrate to the OC developers.

**Comment by mathiasgrimm** [comment]
Right,
this code bellow is the deletion of a product for example:
- Controller:
https://github.com/opencart/opencart/blob/master/upload/admin/controller/catalog/product.php#L1086

- Model
https://github.com/opencart/opencart/blob/master/upload/admin/model/catalog/product.php#L361

if anything goes wrong between the first delete and the last, the database becomes inconsistent, which is bad for multiple reasons.

a simple solution would be
```
// generic code
try {
    $db->beginTransaction();
    // delete 1 ...
    // delete 2 ...
    // etc...
    $db->commit()
} catch (Exception $e)
    $db->rollback();
    throw $e;
}
```

**Comment by TheCartpenter** [comment]
If that sort of code was needed, it would of simply been in the system/library/db folder to avoid repeated codes throughout the controller and model folders.

**Comment by mathiasgrimm** [comment]
sure, in the laravel world for example, we call something like
```
DB::transaction(function () {
    // (do your stuff here and we handle the transaction)
    // delete 1
    // delete 2
    // delete n...
})
```

but not having transaction is really risky.
All operations should be atomic meaning they all succeed or they all fail. Otherwise the db will eventually get corrupted at the logical level. Reports will break, integrations will 3rd party will break because they expect certain database state and everything else will eventually fall apart. That's why I was surprised this didn't exist in OpenCart. I must be missing the point and it maybe its happening somewhere I didn't check.

**Comment by TheCartpenter** [comment]
Another of those laravel commits. Just use an API, such as GuzzleHttp to handle your database transactions with your API token. This won't break anything.

**Comment by mathiasgrimm** [comment]
how does the api or guzzle resolve that specific problem I pointed out? There is no database transaction on the OpenCart side. I will in fact be using and API and Guzzle to handle the stock however I saw this issue on the OpenCart side of things.

If you don't believe me, just throw an exception in between the first and the last delete query and you'll see what I am trying to explain here.

I am willing to help with it, adding it as I believe the project is a good project but I am not an OpenCart developer.

The laravel snipped was just a referente as to how we could have it in the system/library/db folder.
I am totally open to any suggestion at the details level. 

What I am trying to assess here is whether we already have this handled or not and as far as I can see the project lacks database transactions which im willing to contribute for free.

**Comment by TheCartpenter** [comment]
Then create a true PR request about it regarding all changes you're mentioning about to see if those changes will be considered in the future.

**Comment by mathiasgrimm** [comment]
that's what im trying to assess here.
- 1 I showed a real problem, showed how to simulate it and what impact it can have.
- 2 I Showed a simple solution for the problem
- 3 We need a confirmation from the core developers whether this makes sense
- 4 We can discuss a bit some details on the implementation before I start actually writing any code
- 5 I will create a PR and try to use the standards that OpenCart uses to write code

Are you part of the Team that gives a thumbs up down on PRs? Sorry if I don't know you, as I said before, I am new to the OpenCart world.

How can we move this forward and not backwards? I am not here to blame anything/anybody, I just to fix a real problem as quick as possibly

**Comment by mathiasgrimm** [comment]
Also, if we confirm we want to fix this we need to decide how to approach it in terms of existing releases and possibly also break it down in different PRs as all CRUDs potentially need this fix if they deal with more than one table

**Comment by TheCartpenter** [comment]
Not to worry, I am not part of the team where thumbs down are provided. The way it usually works is if there's an interest from the OC team about your PR request, the PR will be merged and closed automatically. As for the CRUDs, there's no need to break those suggestions within different PRs in this case since the system/library/db folder is the location that handles the main queries on the entire platform. Which means, only these files should be modified without the need to replicate the codes elsewhere. Therefore, this location should suffice to make the modifications you are enquiring about.

**Comment by mathiasgrimm** [comment]
for the library, you still need to start and commit/rollback the transaction on a case-by-case basis. 
Some places you don't want transaction and some places you want. 
You would normally start a transaction on the controller (or a service layer) as they know exactly the flow. You can't make all queries transactional because sometimes you will have other interactions in between, like file upload, 3rd party connection and transactions should be open for the minimal amount of time required otherwise you might run into dead locks and other problems like that, hence, It's always on the controller/service/entry point in every project I've seen so far.

**Comment by mathiasgrimm** [comment]
Given that, I still thing it could be broken down into multiple PRs as it also makes it easier to test, review and everything. More scoped. But I would also be fine having a single PR but im sure chances of it getting merged decreases as line of codes increase

**Comment by mathiasgrimm** [comment]
as for the OC team, can we tag anybody in specific that would make this discussion more productive/relevant?

**Comment by TheCartpenter** [comment]
I don't see where in this discussion it would be less productive/relevant but you have been suggested to create your own PRs to show the changes you are referring about. If there's an interest from the OC team, your PRs could be merged later on.

**Comment by mathiasgrimm** [comment]
well, As I am not a OC developer it would be more productive to know what they think about it. Otherwise I might put a lot of effort on a PR and then it gets rejected.

**Comment by mathiasgrimm** [comment]
hey @WebkulOpencart, would you help us here? I thikn we are making some progress here on this closed ticket and it would be good to re-open it. Also if anybody from the OC team could give their 2 cents to the discussion it would greatly help

**Comment by TheCartpenter** [comment]
This commit does not need to be re-opened.
