### ISSUE TITLE
Why aren't we using Doctrine ORM or something similar?

### ISSUE THREAD

**Issue by emomaliev** [opencart/opencart#10181]
Why not change the architecture of the application in a future version of opencart.

This will solve at least 2 inconvenient problems.
1. It is very inconvenient to keep track of the relevance of the database when we do not have entities
2. Will simplify the writing of many queries, it will also be easier to support them
...

https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/tutorials/getting-started.html

**Comment by victorhramos-dev** [comment]
> This would cause several problems:
> 
>     * Loss in developer productivity whilst they learn to program with ORM.
> 
>     * Developers lose understanding of what the code is actually doing - the developer is more in control using SQL.
> 
>     * ORM has a tendency to be slow.
> 
>     * ORM fail to compete against SQL queries for complex queries.
> 
> 
> Also, the Doctrine ORM implementation suffers from some important restrictions, such as:
> 
>     * Join-Columns with non-primary keys
> 
>     * Mapping Arrays to a Join Table
> 
>     * Custom Persisters
> 
>     * Mapping many tables to one entity
> 
> 
> OpenCart already uses the MVC design philosophy, where the model classes are responsible for the data persistence. Changing the models to using PHP's PDO would be an easier step forward and would only require minor changes in the model classes.

the most non sense thing i ever seen on a php project repository...
