### ISSUE TITLE
event->trigger() speed profile

### ISSUE THREAD

**Issue by zdanozdan** [opencart/opencart#10196]
**What version of OpenCart are you reporting this for?**
3+

**Describe the bug**
event->trigger() speed issue

system/engine
event->trigger() on profiler looks bad. It takes almost 30% of processing time on aggregate. There is foreach loop called zillion times, basically for every 2x model/view/controller/language. I changed this to simple array key access which improved processing times by factor of 2. Worth to take a look at it

**Expected behavior**
Use array access. Wildcard events needs to be redesigned though.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

<img width="839" alt="Zrzut ekranu 2021-09-5 o 22 53 57" src="https://user-images.githubusercontent.com/463276/132141155-482017de-3f5f-4f44-b124-45eb4740f7a3.png">

**Comment by TheCartpenter** [comment]
I covered similar subject long ago on this repository that new instances should not be loaded in a loop since it can normally load up a maximum of 300 classes overall during the loop. Events can get pretty vast, and rapidly, with time.

**Comment by zdanozdan** [comment]
I guess events can be real killer as processing time rise exponential in relation to number of events. The fix is fairly easy but wildcards are real pain to solve.

**Comment by danielkerr** [comment]
closing issue.

will look into later if people report problems once the extensions using events are in full swing.
