### ISSUE TITLE
Language Editor edit key error - Key must be between 3 and 64 characters OC 3.0.3.7

### ISSUE THREAD

**Issue by AlexanderSk** [opencart/opencart#10193]
**What version of OpenCart are you reporting this for?**
Version 3.0.3.7

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Home Language Editor -> edit and save a language string
an error message is displayed
Key must be between 3 and 64 characters!

**To Reproduce**
On a clean installation just installed locally
1. Go to design -> language editor
2. Click on edit a language string (if you dont have one then create and save one first and then press edit)
3. Then press save button on top right.
4. See error "Key must be between 3 and 64 characters!" bellow key

**Expected behavior**
After language edit the language string should have been saved.

**Screenshots / Screen recordings**
---

**Server / Test environment (please complete the following information):**
 - Local development
 - Operating system windows 10
 - PHP version  PHP/7.4.9RC1
 - Apache version Apache/2.4.46 (Win64) 
 - Browser(s) tested with - Chrome  Version 92.0.4515.159 (Official Build) (64-bit)

**Additional context**

**Comment by mhcwebdesign** [comment]
Yes, I can confirm this is a bug. I managed to reproduce it for OC 3.0.3.7 and OC 3.0.3.8.

**Comment by prabhatkumaroc082** [comment]
Please try some valid "key" that must have min 3 characters, it will accept. it's a validation to not add a blank key.

**Comment by AlexanderSk** [comment]
The validation you mention applies when: someone creates a new key on "Add New"
What we reported for the bug is: On Edit, where you can not change the Key but only the value and of course when the value has some data the Save fails with error: Key must be between 3 and 64 characters! (in my test key was: "code").

Request for verification.
