### ISSUE TITLE
Print Order - if multiple orders are printed at once the order numbers are all the same

### ISSUE THREAD

**Issue by Mios-1000** [opencart/opencart#10197]
I have tested this on a fresh install of both 3.0.3.7 and also 3.0.3.8 and if multiple orders are selected in the 'Order' page and then the 'Print Invoice' button is clicked, all of the orders in the resulting window are correct apart from the actual order number on each individual order are all the same.
This only seems to effect the later OC versions as I have tested on earlier versions which work correctly.

**Comment by mathsolutions** [comment]
Hi, I've proposed a fix #10201

**Comment by ADDCreative** [comment]
Also need to remove the following.

https://github.com/opencart/opencart/blob/08832aa1542c594e631f4a91d1e02a98ab2fa6a8/upload/admin/controller/sale/order.php#L1521

**Comment by mathsolutions** [comment]
@ADDCreative , you are right
I've modified the pull request, removing the line in the controller and correcting the language file also

**Comment by prabhatkumaroc082** [comment]
> @ADDCreative , you are right
> I've modified the pull request, removing the line in the controller and correcting the language file also

@mathsolutions 
text_order is also being used on other pages like order info, etc
it's better to keep this key's value the same in the language file and modify only the invoice page

send each "text_order" value in the array and just add order.text_order in the twig. apply changes on the PR #10203

Controller
Line 1521 `$text_order = sprintf($this->language->get('text_order'), $order_id);`
Line 1677 `'text_order'       => $text_order,`

Twig
order.text_order instead of text_order

**Comment by mathsolutions** [comment]
@prabhatkumaroc082,
yes it's better. I've changed PR #10203

**Comment by ActorMike** [comment]
I added this code below to my en-gb.php language files but when I bulk print it does not show any text at the top, just the order number. The order number is correct now, but I cannot get it to add the word "Order" in front of the order number, did I miss something?

`$_['text_order']            = 'Order';`

**Comment by ActorMike** [comment]
``I added this code below to my en-gb.php language files but when I bulk print it does not show any Order # text at the top, just the order number. The order number is correct now, but I cannot get it to add the word "Order" in front of the order number, did I miss something?

$_['text_invoice'] = 'Order';

I guess for now I will change the TWIG file to:
<h1>ORDER #{% if order.invoice_no %}{{ order.invoice_no }}{% else %}{{ order.order_id }}{% endif %}</h1>

**Comment by ADDCreative** [comment]
You don't need to change the language files. Order is already there.

https://github.com/opencart/opencart/blob/58e1d302e465df7215c4464d8e95f47edbc15682/upload/admin/language/en-gb/sale/order.php#L26

Used.
https://github.com/opencart/opencart/blob/58e1d302e465df7215c4464d8e95f47edbc15682/upload/admin/controller/sale/order.php#L1521

Just need to make these changes.
https://github.com/opencart/opencart/pull/10203/files
