### ISSUE TITLE
[Master Branch] - admin/view/template/common/security.twig file

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#10209]
Hardcoded: https://github.com/opencart/opencart/commit/423c10109f4b36f9208092cb72ecda06e5cdf352#diff-d7e2e7cbdce754580859a7dd96d57d09a323490ab464f5a7889ce75c0dc8646bR14 .

Sentence:

```Some security problems have been detected. Click continue to start fixing the issues.```

**Comment by danielkerr** [comment]
fixed ages ago
