### ISSUE TITLE
[Master Branch] - checkout/register.twig

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#10208]
Hardcoded: https://github.com/opencart/opencart/blob/8227ee6fc6af713e40cf5ebac160723b33b1d4b2/upload/catalog/view/template/checkout/register.twig#L3 .

**Comment by cgcmart** [comment]
<p>Already have an account? You can <a href="{{ login }}"><strong>{{ text_login }} here</strong></a>.</p>

**Comment by TheCartpenter** [comment]
The sprintf function needs to be used from the controller for this.

**Comment by danielkerr** [comment]
fixed ages ago
