### ISSUE TITLE
Error in admin/view/template/sale/order_form.twig

### ISSUE THREAD

**Issue by amaco596** [opencart/opencart#10216]
**What version of OpenCart are you reporting this for?**
3.0.3.8

**Describe the bug**
The {% endif %} on line 302 should be inside `<tbody>` tag, not outside. So, it should be on line 301 and `</tbody>` should be on line 302.

As it is now, the `<tbody>` tag on line 247 will not be closed if there are no order_products or order_vouchers.

**Comment by TheCartpenter** [comment]
Confirmed.

@WebkulOpencart: Maintenance branch.

**Comment by TheCartpenter** [comment]
This one is a major incident though.
