### ISSUE TITLE
bc1qt85ftkvey7q08jsn86tezxswgpet7d3tc7c3hl

### ISSUE THREAD

**Issue by ImpregnusEL87ELwagus** [opencart/opencart#10226]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by ImpregnusEL87ELwagus** [comment]
> **What version of OpenCart are you reporting this for?**
> 
> **Describe the bug**
> A clear and concise description of what the bug is
> What section does it affect?
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots / Screen recordings**
> If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
> https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app
> 
> **Server / Test environment (please complete the following information):**
> 
> * Local development? Deployed to a web server?
> * Operating system
> * PHP version
> * Apache version
> * Browser(s) tested with [e.g. chrome, safari - if applicable]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by mhcwebdesign** [comment]
Missing issue description.
