### ISSUE TITLE
php type error 

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10224]
private string $output = ''; -------------> ///// variable string

private function compress(array $data, int $level = 0): string {  ///// function type array

https://github.com/opencart/opencart/blob/d8144d8baa346adeb7163dd39addd2b2e52f84d1/upload/system/library/response.php#L116

**Comment by TheCartpenter** [comment]
Might be a good point here ...

**Comment by danielkerr** [comment]
yep!
