### ISSUE TITLE
Maximum Speed Ajax

### ISSUE THREAD

**Issue by BuslikDrev** [opencart/opencart#10233]
I propose to make it possible to change the standard OpenCart configuration from the module controller in this way:

system/framework.php
after $registry->set('request', $request); OR $registry->set('db'
```
// Pre config
$config->set('config_pre_config', true);
if ($config->get('config_pre_config')) {
	if ($registry->get('request')->get['route']) {
		$pre_config_route = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$registry->get('request')->get['route']);

		if (!is_file(DIR_APPLICATION . 'controller/' . $pre_config_route . '.php')) {
			$pre_config_route = substr($pre_config_route, 0, -strlen('/' . basename($pre_config_route)));
			if (!is_file(DIR_APPLICATION . 'controller/' . $pre_config_route . '.php')) {
				$pre_config_route = false;
			}
		}
	} else {
		$pre_config_route = 'common/home';
	}

	if ($pre_config_route) {
		$pre_config = new Action($pre_config_route . '/preConfig');
		$pre_config = $pre_config->execute($registry, array($registry->get('request')->get['route']));

		if (is_array($pre_config)) {
			foreach ($pre_config as $key => $result) {
				$registry->get('config')->set($key, $result);
				$config->set($key, $result);
			}
		}
	}
}
```

This will allow you to disable unnecessary libraries from your module when sending ajax, etc. I would be glad if this inspires the creators of OpenCart to improve.

catalog/controller/extension/module/mymodule.php
```
	public function preConfig($route) {
		if ($route == 'extension/module/mymodule/ajax') {
			return array(
				'action_pre_action' => array(
					'startup/setting'
				)
			);
		}
		if ($route == 'extension/module/mymodule') {
			return array(
				'action_pre_action' => array(
					'startup/setting',
					'startup/session',
					'startup/startup',
					'startup/error',
					'startup/event',
					'startup/maintenance'
				)
			);
		}
	}

	public function ajax() {
		$this->response->addHeader('Content-Type: application/json');
		$this->response->setOutput(json_encode('Good 40 ms != 80 ms!'));
	}

	public function index() {
```

**Comment by TheCartpenter** [comment]
Not sure why this change would be needed since the admin path also needs to be considered. As for disabling unnecessary libraries, if these changes are suggested to be made in the Maintenance Branch, the installer does use the system/library folder. Therefore, these codes would, in fact, interfere with the installer especially if it would have to be made in the system/framework.php file.

However, if this is for the master branch, take note that recent changes were made by the founder regarding the mass use of jQuery and Ajax for the purpose to target a new: save() method in almost all controllers. Therefore, these changes would still not be advantageous to use since the whole platform is practically focusing on a new evolution to pass and save the data through the browser while using web forms.

**Comment by chulcha** [comment]
@BuslikDrev , ты ожидал другого ответа? 
@BuslikDrev, did you expect a other answer?

Причем здесь  админский путь, можно подумать что в админке аякса нет.
And here is the admin path, you might think that there is no ajax in the admin panel.


Сколько ты не будешь доказывать, что мы делаем быстрый магазин, что для легких запросов не нужно тянуть все либы
You can prove that we are making a fast shop(both front and back), that for light inquiries you don't have to pull everything. But no one will hear you.


Но здесь есть проблема другого рода.
Это подключение библиотек разработчиков
А в них могут использоваться уже подключенная библиотека
But there is a problem here - developer libraries.
And they can use the already connected library.

**Comment by danielkerr** [comment]
there is already a way using the new startup system

**Comment by BuslikDrev** [comment]
> there is already a way using the new startup system
Do you have a usage example?
Through events, I cannot change the config to choose what to load.
addEvent('mymodule_library', '', 'catalog/controller/startup/setting/before', 'extension/mymodule/event/mymodule|start', 1, 0);
