### ISSUE TITLE
$(this).attr('data-lang'); no such data

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10234]
var url = $('base').attr('href') + 'index.php?route=product/search&language=' + document.documentElement.lang;

https://github.com/opencart/opencart/blob/ea5cec5da3c6e63a3a18e6d5f3daf977cc075dcd/upload/catalog/view/javascript/common.js#L67

**Comment by hafhaf10** [comment]
Hi, I would like to try fix the issue.

**Comment by danielkerr** [comment]
Removed allready
