### ISSUE TITLE
TypeError:  Unsupported operand types: int + string in the file line 51

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10240]
https://github.com/opencart/opencart/blob/2b87dc1c6e7b66cb5bdd2c1e0e63a895ec76790e/upload/catalog/controller/startup/session.php#L51

Referring to similar type errors #10164 , #9730

**Comment by cgcmart** [comment]
fixed.

**Comment by iDigLocal** [comment]
So we have been testing OC4 as an upgrade from OC3 (to put in context) and there are numerous instances of this error in controllers for product, attribute,layout whereby pagination (certainly for admin) is getting the config variable which needs to be an int .

e.g in Opencart\Admin\Controller\Catalog\attribute.php 
 'start' => ($page - 1) * $this->config->get('config_pagination_admin'),
which can be rectified by :  'start' => ($page - 1) * (int)$this->config->get('config_pagination_admin'),
or 
$config_pagination_admin =  (int)$this->config->get('config_pagination_admin');
 
 'start' => ($page - 1) * $config_pagination_admin,


tend to be ln 95 and ln 144

then on ln 144 the end of line there is a cannot divide by 0 error.
