### ISSUE TITLE
TypeError: Argument #1 ($cart_id) must be of type int, string given, called in /

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10245]
TypeError: Opencart\System\Library\Cart\Cart::update(): Argument #1 ($cart_id) must be of type int, string given, called in /

	if (isset($this->request->get['key'])) {
			$key = (string)$this->request->get['key'];
		} else {
			$key = '';
		}

		if (isset($this->request->get['quantity'])) {
			$quantity = (int)$this->request->get['quantity'];
		} else {
			$quantity = 1;
		}
solve

$this->request->post['key']  (key is actually card_id)
 
if (isset($this->request->post['key'])) {
	$key = (int)$this->request->post['key'];
} else {
	$key = 0;
}

	if (isset($this->request->post['quantity'])) {
			$quantity = (int)$this->request->post['quantity'];
		} else {
			$quantity = 1;
		}

// Handles single item update
$this->cart->update($key, $quantity);

system/library/cart/cart.php
public function update(int $cart_id, int $quantity): void {

https://github.com/opencart/opencart/blob/1c2659d35ca06b5a120dc3be9fdd91e9ba91d9c3/upload/catalog/controller/checkout/cart.php#L351

**Comment by danielkerr** [comment]
key is now cart_id so its always an int
