### ISSUE TITLE
Opencart.com marketplace is not notifying developers of purchaser e-mail addresses

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#10256]
Hi Daniel-

I know this isn't a bug in the github code, but I think this is the quickest way of reaching you.

I noticed that since yesterday, the developer notification for orders in the marketplace do not contain the "email" parameter any more. I also tested exporting orders from the sales list, and noticed that the CSV file breaks in there, because the email address isn't present.

Is this a temporary issue, or an intentional change? If it's intentional then I'd strongly encourage you to continue providing the email address to the developers --- without it, we have no way of following up with a customer or contacting them after purchase (such as for a license key). It's going to cause huge headaches for both developers and customers, and that won't reflect well on the marketplace as a whole. 

If it's a bug, then no worries --- hopefully you can get it fixed soon. I just thought I'd let you know in case you weren't aware of it. Thanks!

-Johnathan

**Comment by ClearThinking** [comment]
So I just got an email notification of a purchase (not the API/webhook notification) and it *does* still include the email address. I'm assuming the API problem is a bug then (hopefully)

**Comment by danielkerr** [comment]
It will go. Just giving some sellers time to remove

**Comment by eka7a** [comment]
I think this notification has reached everyone. I'm closing the issue.

> ### API callback email field update

> **Update on the API callback email field**
> This is a notification to let all the developers and sellers know that we have taken the necessary steps and removed the API  callback field.
> Therefore, all sellers can use the support system to follow up with buyers. We encourage sellers as well to communicate with buyers through the Opencart forum. This will definitely grow the community and build a strong relationship between developers and clients.
> We thank you so much for your continuous support and we are working very hard to improve the Opencart platform.

**Comment by ClearThinking** [comment]
> It will go. Just giving some sellers time to remove

So Daniel, I'm assuming by your response that this *IS* an intentional change, and that the E-mail Address field will also be removed from the e-mail notification as well?

>Therefore, all sellers can use the support system to follow up with buyers

I'm sorry, but HOW exactly is a seller supposed to use the support system to follow up? A seller has no way to communicate with a buyer after they've made a purchase. The buyer has to reach out first, and if they don't know that, they could be waiting days before they realize they're not getting a license key e-mail.

Even if the normal e-mail notification is still going to include the e-mail, are sellers supposed to *manually* send each buyer a license key after every purchase? How exactly does that help the seller or the buyer? 

Daniel, I'd really appreciate an actual reason why you did this. I'm assuming you just don't want to provide sellers with e-mail addresses so everything has to go through opencart.com, but if that's the case, can you please offer an explanation as to *why*?

**Comment by TheCartpenter** [comment]
@ClearThinking: I already discussed similar matter with him in the past. In order to rectify that situation, to avoid unassociated emails in the support tickets, the emails needs to be regrouped with the sellers' and buyers' automatically right from the start where no other external emails can be regrouped aside from the support team. This way, email notifications will be reduced vs. 3rd party emails on Zendesk as faster notifications could be sent between parties. Right now, I am sure it's still free-for-all which is why it can take an inconsiderable time before buyers / sellers can both receive their response - including follow-ups.

**Comment by ClearThinking** [comment]
Thank you for the info. So it sounds like developers *might* still get e-mail addresses of purchasers in the future, once the new system is in place? Hopefully that's the case, or Daniel will post with a more thorough explanation.
