### ISSUE TITLE
Summernote fails to initiliaze when using multiple locale

### ISSUE THREAD

**Issue by MarvinKlein1508** [opencart/opencart#10259]
**What version of OpenCart are you reporting this for?**
3.0.3.8

**Describe the bug**
Summernote 

**To Reproduce**
1. Go to admin->settings->languages
2. Click on edit
3. Create multiple locale identifiers. E.g. 
4. Try to visit any site which uses summernote within admin
5. See error in console:
```
GEThttps://DOMAIN/admin/view/javascript/summernote/lang/summernote-de,de-de,de-DE,de_DE,german,de_DE.UTF-8,de-de.UTF-8,german.UTF-8-DE,DE-DE,DE-DE,DE_DE,GERMAN,DE_DE.UTF-8,DE-DE.UTF-8,GERMAN.UTF-8.min.js
[HTTP/2 404 Not Found 26ms]

Uncaught SyntaxError: expected expression, got '<'
    jQuery 11
    <anonymous> https://www.nobel-hobel.de/admin/view/javascript/summernote/opencart.js:8
    jQuery 2
    <anonymous> https://www.nobel-hobel.de/admin/view/javascript/summernote/opencart.js:3
    jQuery 8
```

**Expected behavior**
Summernote should not fail initialzing when multiple local identifiers are defined

**Screenshots / Screen recordings**
![grafik](https://user-images.githubusercontent.com/32510006/140055534-8c4987f3-b85b-4e22-b421-6eb0560c23e7.png)

![grafik](https://user-images.githubusercontent.com/32510006/140055603-4fc2ea51-060a-44ce-9338-624db061e344.png)

**Server / Test environment (please complete the following information):**
 - PHP version 8
 - Browser(s) tested with Chrome and Firefox

**Additional context**
only specifying a single locale willl result in working summernote. For example: `de` however when I be more specific it fails again. For example: `de-de`

**Comment by webkul-dilip** [comment]
We need to add language code at admin in ISO 639-1 formate.
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

http://i.prntscr.com/ZSa4WpfoR4C2oqDg9b41Jg.png
http://i.prntscr.com/h7ZFjsBHQIiIasisZouMyA.png
http://i.prntscr.com/5EnzBKmPTBCS4OQ2FoZ25Q.png
http://i.prntscr.com/RCD5tiIMSmCxHYMoux1RaQ.png

**Comment by osworx** [comment]
Well, it's quite stupid doing it this way with **language.locale**:
https://github.com/opencart/opencart/blob/a27b2b9e7f1edd4d95d3f48ebbb0355521e68165/upload/admin/view/template/catalog/product_form.twig#L61

While the language file has already the correct definiton(s) **summernote**:
https://github.com/opencart/opencart/blob/a27b2b9e7f1edd4d95d3f48ebbb0355521e68165/upload/admin/language/en-gb/en-gb.php#L162

And no need to use ISO 639-1 format (which is btw. only a 2-letter code!).

**Comment by osworx** [comment]
> only specifying a single locale willl result in working summernote. For example: `de` however when I be more specific it fails again. For example: `de-de`

It should be **de-DE** (because all OpenCart packages have the summernote languages like xx-YY.js).
Don't know from where you have the de.js, I assume you are using my German translation ..

**Comment by MarvinKlein1508** [comment]
> 
> It should be **de-DE** (because all OpenCart packages have the summernote languages like xx-YY.js). 

Wrong. The default for German language files in Opencart is `de-de`. Even your own langauge pack creates this folder.

**Comment by osworx** [comment]
> 
> 
> > It should be **de-DE** (because all OpenCart packages have the summernote languages like xx-YY.js).
> 
> Wrong. The default for German language files in Opencart is `de-de`. Even your own langauge pack creates this folder.

de-de IS the language code (and folder) - as all langauge translations should use xx-yy (and NOT xx-YY or German as seen at some).
de-DE IS the code for summernote as defined inside the main language file (also in mine).
So please don't tell me stuff ..

**Comment by webkul-dilip** [comment]
As you suggested, we will do it in a better way, we will update you shortly.

**Comment by osworx** [comment]
Beside this "discussion", summernote use xx-YY as language codes, see:
https://github.com/summernote/summernote/tree/develop/src/lang

And what I've added to the German language pack is a reworked summernote de-DE translation because the one provided with the original packages are quite old ..

**Comment by osworx** [comment]
@webkul-dilip 21 days later - and no update or fix??
What do you understand under **shortly** ?

**Comment by webkul-dilip** [comment]
> @webkul-dilip 21 days later - and no update or fix?? What do you understand under **shortly** ?

sorry for the delay, now we have fixed the issue 
https://github.com/opencart/opencart/pull/10275

**Comment by Opencart-Webkul** [comment]
Merged PR https://github.com/opencart/opencart/pull/10275

**Comment by MarvinKlein1508** [comment]
@Opencart-Webkul when will this patch be available in an update for OC?

**Comment by panqilin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by osworx** [comment]
@opencart If all updates would be so fast as deleting comments, more users would be satisfied.
