### ISSUE TITLE
Affiliate - Register - Validate Customer Custom Fields

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#10262]
**What version of OpenCart are you reporting this for?**
v.3.0.3.2

**Describe the bug**
Field validator not working!

**To Reproduce**
1. Go to home
2. Click on Affiliate Program in footer
3. Click Register
4. Fill customer custom required field (add in admin > customer > custom fields > text field as required)
5. Press Continue
6. See error (no error, you cannot register)

**Comment by danielkerr** [comment]
i think u should know by now github is for development of the latest version. not bug fixinjg old ones that are not relevant.

**Comment by dabbmedia** [comment]
@danielkerr  BTW, there is much outdated info and broken links on OpenCart.com, and it gives the impression that the site has been abandoned by its maintainers.
-PHP required version still says 5.4+
-forum password recovery link is broken
-forum cannot be searched, even on first attempt an error is given
-claims Square payment is included, but it doesn't work (users have reported this issue, response was to claim Square support has been removed)

<img width="334" alt="Screen Shot 2021-11-24 at 12 53 44 PM" src="https://user-images.githubusercontent.com/2788552/143305309-2ac2bfb7-0207-4546-a91c-73e8d196422c.png">

<img width="763" alt="Screen Shot 2021-11-24 at 1 13 49 PM" src="https://user-images.githubusercontent.com/2788552/143307346-d656049b-0ba5-4802-98e8-0ec5a700317f.png">


I have seen members of the community report the issues, as well as offer to help fix them. They are often met with ridicule and derision by contributors.

Maybe you didn't realize.
