### ISSUE TITLE
Checkout gets stuck on Payment Method with Warning: Payment method required!

### ISSUE THREAD

**Issue by advancedJw** [opencart/opencart#10260]
I applied fixes in https://github.com/opencart/opencart/issues/7811 but no luck.  I originally added some states to a Geo-zone to start taxing them, then the issue started.  I tried removing them but the problem persists.  In a fresh browser, the first attempt at a checkout works, if you backup in the process and move forward again, you get the error.  After that, if you close the browser and try again, you get the error.  Opencart V 3.0.3.3

**Comment by ADDCreative** [comment]
If not a race condition it could be a caching issue. https://github.com/opencart/opencart/issues/7008

**Comment by danielkerr** [comment]
should be fixed now

**Comment by advancedJw** [comment]
This just mysteriously started happening in my site in the last few days, looking to hire someone to take a look at it.
