### ISSUE TITLE
Mail: message has lines too long for transport

### ISSUE THREAD

**Issue by Syphere** [opencart/opencart#10268]
**What version of OpenCart are you reporting this for?**
3.0.3.8

**Describe the bug**
Order mails are not being sent with the mailserver rejecting them for "message has lines too long for transport" in accordance with RFC5322 and RFC2822.

**To Reproduce**
1. Order anything.
2. Receive no mail.
3. Notice the error in the mail sending log

**Expected behavior**
The order mail being sent normally

**Mail Log**
2021-11-15 15:59:54 1mmdSc-0007cW-Q0 <= xxx@xxx.nl U=user P=local S=13397 T="Shopname - Order 10" from <xxx@xxx.nl> for yyy@yyy.com
2021-11-15 15:59:54 1mmdSc-0007cW-Q0 ** yyy@yyy.com F=<xxx@xxx.nl> R=smart_route T=remote_smtp: message has lines too long for transport
2021-11-15 15:59:54 1mmdSc-0007cW-Q0 Completed

**Server / Test environment:**
 - Deployed and live on a shared hosting.
 - Apache2 2.4.51
 - PHP 7.3.32
 - Exim 4.95

**Additional context**
Nothing was modified in the OC installation to have caused this. This is a standard/default installation when it comes to mail.
The host has recently updated Exim, and according to them and the changelog it enables line length limit by default. Any mail sent through the server that isn't OpenCart is sent without a problem.

**Comment by dabbmedia** [comment]
@Syphere have you tried sending a test email from the server on the command line to verify it's not a server and/or DNS issue?

`echo "Test Message" | mail -s "Test Subject" email@test.com`

And verify the SPF records in your DNS configuration.

**Comment by Syphere** [comment]
@dabbmedia Hi!

I should've specified that in my initial message that any other mail is sent fine.
It is definitely not a DNS related issue (Those do not enforce line length limits)

**Comment by ADDCreative** [comment]
Is your Mail Engine set to Mail or SMTP in the OpenCart Mail settings?

**Comment by Syphere** [comment]
It is set to Mail. SMTP was an option we thought of, but we have no other mail server to use that won't have the same issue.

**Comment by Syphere** [comment]
It's been implemented and we're waiting to see the results :)
Thanks for that!

**Comment by Syphere** [comment]
It's been a while waiting but we've just got reports that it is working just fine now. I've noticed that this issue may also arise when using SMTP, since the is no splitting in that file either.

Either way, thanks much!

**Comment by ADDCreative** [comment]
@Syphere The lines are split in the SMTP class, just in a different way.

https://github.com/opencart/opencart/blob/a27b2b9e7f1edd4d95d3f48ebbb0355521e68165/upload/system/library/mail/smtp.php#L187-L196

**Comment by Syphere** [comment]
@ADDCreative
You're right! Missed that apparently! Thanks for letting me know!
