### ISSUE TITLE
[Master] Add affiliate bug

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#10265]
**What version of OpenCart are you reporting this for?**
Master

**Describe the bug**
When you want to add an affiliate, customer field is disabled.
`<input type="text" name="customer" value="{{ customer }}" placeholder="{{ entry_customer }}" id="input-customer" class="form-control"{% if not customer_id %} disabled{% endif %}/>`

**To Reproduce**
1. Go to Marketing->Affiliate
2.  Click on Add New
3. Required Customer field is disabled even in database are enabled customers.

**Comment by danielkerr** [comment]
yes because u should not be able to switch accounts to different customer accounts

**Comment by condor2** [comment]
So how you can add a new Affiliate from admin if you can't chose the customer?

**Comment by danielkerr** [comment]
the code is % if customer_id %} disabled{% endif %}
