### ISSUE TITLE
Wrong minimum php version at OpenCart page

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#10263]
I know this here belongs to GitHub only, but because it is serious I am writing it here.
On this page here https://www.opencart.com/index.php?route=cms/download the minimum required php version is stated as 5.4 while in real it must be at least 7.3.x (when used 3.0.3.8 which is the latest published version):

> Requirements

> These are minimum requirements needed so that OpenCart can be installed and work properly.

    Web Server (Apache suggested)
    PHP (at least 5.4)
    Curl enabled
    Database (MySQLi suggested)

Could someone please update that page?!

**Comment by Opencart-Webkul** [comment]
@danielkerr kindly look into this

**Comment by osworx** [comment]
Could someone fix that issue!
ASAP!
More and more posts about wrong php-versions (or wrong downloaded versions) because if that.

Here https://github.com/opencart/opencart a minimum of php 8.0 for the 3.0.3.8 version is published.
And here https://www.opencart.com/index.php?route=cms/download php 5.4 is published.
Tired of answering forum posts because of that.

thx.

**Comment by danielkerr** [comment]
please open issue here:

https://github.com/opencart/opencart-3/issues

**Comment by ADDCreative** [comment]
@danielkerr This applies to 4.0, as it's to do the the requirements listed on https://www.opencart.com/index.php?route=cms/download.
