### ISSUE TITLE
Granted full access/Modify permissions to a User-group but still getting a permission error during Order Editing in Admin Panel

### ISSUE THREAD

**Issue by nikonov91-dev** [opencart/opencart#10277]
in Version 3.0.3.8: I created a user-group and granted with all permissions but I'm still receiving an error:

![Screenshot at Nov 28 15-20-49](https://user-images.githubusercontent.com/31586394/143771612-c1b98586-1e31-489a-a26f-715da6cf02e0.png)

I also get such error when the Country is changed. Seems to be there is a bug in permission that doesnt allow to work with some fields (such as country-regions) because only Admin may visit Order Editing with these permission errors.

My goal is to set permission for Manager-user-group to be able to edit orders in Admin panel.

PS. I've checked the logs in Store-settings, in MyPHPAdmin and in storing log oc-store->system->log-> error.log but there is nothing mentions this issue

**Comment by Opencart-Webkul** [comment]
You must have removed the file permissions to the admin. Kindly share it on the Opencart forum.
