### ISSUE TITLE
Sagepay Direct - 3D Secure v2

### ISSUE THREAD

**Issue by SPB105438** [opencart/opencart#10272]
Opencart Verion 3.0.3.7

My site uses the Sagepay Direct payment method as it is not internet accessible.
Sagepay (now Opayo) informs me the Direct method is using 3D Secure v1 and that we must update to using 3D Secure v2.

Im told we must Upgrade our integration to Protocol 4.00 to prevent the risk of higher decline rates in the future, 
Their site details the changes required, "Direct integration – Minimal impact, the 3DSv2 flow will be the same as the current 3DSv1 flow, however, an additional 9 fields will be required."

Can you tell me if / when the Sagepay Direct payment method will be updated or not, please?
or whether or not the changes have been made in 3.3.8

info can be found at https://www.opayo.co.uk/support/16/3d-secure-v2-what-do-customers-need-to-do

Thank you

**Comment by danielkerr** [comment]
what about the extension listed on the marketplace? they should have updated it there. they are the ones that wrote this integration i think.

**Comment by SPB105438** [comment]
Hi Daniel,  I think this is the one you refer to https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=36557&filter_search=opayo&filter_category_id=3

 I did see it but wanted to check first, the extension doesn't list 3.0.3.7 or 3.0.3.8 as supported specifically, and many have asked questions similar to mine which are unanswered.
 
 I'll give the extension a go, can always undo the changes, 
 Thank you

**Comment by SPB105438** [comment]
Downloaded and tested, the extension does work with 3.0.3.7, however, comparing the files side by side using Notepad++ compare addon, almost all the files are unchanged.

The only change i found was to admin\controller\extension\payment\sagepay_direct.php
Opencart 3.0.3.7 - Line 178

$data['order_id'] = $this->request->get['order_id'];				
$data['user_token'] = $this->request->get['user_token'];

Opayo extension - Line 178

$data['order_id'] = (int)$this->request->get['order_id'];
$data['user_token'] = $this->session->data['user_token'];


admin\model\extension\payment\sagepay_direct.php are identical and unchanged, the extension still uses the older Protocol.

		if (!empty($sagepay_direct_order) && $sagepay_direct_order['release_status'] == 0) {

			$void_data = array();

			if ($this->config->get('payment_sagepay_direct_test') == 'live') {
				$url = 'https://live.sagepay.com/gateway/service/void.vsp';
				$void_data['VPSProtocol'] = '3.00';
			} elseif ($this->config->get('payment_sagepay_direct_test') == 'test') {
				$url = 'https://test.sagepay.com/gateway/service/void.vsp';
				$void_data['VPSProtocol'] = '3.00';
			} elseif ($this->config->get('payment_sagepay_direct_test') == 'sim') {
				$url = 'https://test.sagepay.com/Simulator/VSPServerGateway.asp?Service=VendorVoidTx';
				$void_data['VPSProtocol'] = '2.23';

There is nothing to provide the additional 9 fields that will be required

**Comment by danielkerr** [comment]
It should still work. I don't think they updated it.

**Comment by SPB105438** [comment]
Correct it does work currently, but not with the mandated changes coming into effect in March next year, there is still time and i'll speak to Sagepay

**Comment by SPB105438** [comment]
Spoken with sagepay (opayo) they tell me they do not create the sagepay extensions for any eCommerce site.
Just a consideration, but if the extension is not updated, would you remove it from future releases of opencart?

**Comment by SPB105438** [comment]
Thanks Daniel, I have a number of options to test, and if needs be, i'll contact dreamvention for more options
