### ISSUE TITLE
My Opencart Website Showing this Issue Please Suggest any solution (error 1038 )

### ISSUE THREAD

**Issue by taksha17** [opencart/opencart#10285]
OpenCart 3.0.3.7

**Describe the bug**
My Opencart page suddenly stopped rendering the home page.But after that i found a solution to the problem.
But now My Admin->Catalog->Product Page gives the following error.
"Warning: mysqli::query(): (HY001/1038): Out of sort memory, consider increasing server sort buffer size in /home/acmysys1/public_html/system/library/db/mysqli.php on line 19"

I tried to do my best to solve it but still no result.

Also i tried to contact my host server provider and explained him about the problem but he couldn't help too.

![Error 2](https://user-images.githubusercontent.com/49115366/144449483-54d1f019-38e7-41f6-bf06-da6a9839e4c0.PNG)
Also tried to give cpanel ssh access to putty software,inorder to increase the size of server socket memory in my sql, but server not connecting there.
**Expected behavior**
At normal condition it would generally allow me to edit my products through product page

 Deployed to a web server
 - Operating system : win 10
 - PHP version : 7.4.26
 - Apache version : 2.4.51
 - My sql Version : 8.0.27
 - Browser(s) tested with : chrome,edge

**Comment by dabbmedia** [comment]
@taksha17 did you try/were you able to increase the memory_limit parameter in the php.ini file?

**Comment by osworx** [comment]
Maybe read: https://stackoverflow.com/questions/29575835/error-1038-out-of-sort-memory-consider-increasing-sort-buffer-size

**Comment by taksha17** [comment]
> @taksha17 did you try/were you able to increase the memory_limit parameter in the php.ini file?

Yes did so but didnt work

**Comment by taksha17** [comment]
> Maybe read: https://stackoverflow.com/questions/29575835/error-1038-out-of-sort-memory-consider-increasing-sort-buffer-size

not able to find my mysql files because my wesite is deployed on cpanel based host and probably i dont know how to edit them

**Comment by dabbmedia** [comment]
@taksha17 I believe @osworx is leading you in the correct direction. If you have access to PHPMyAdmin, you should be able adjust some settings through the query window, but changes will not persist on service restart or server reboot. Alternatively, you may be able to connect to the database with the command line MySQL client (usually included when installing MySQL on your PC) with the connection details in the OpenCart config.php file.

View current setting:
`SHOW GLOBAL VARIABLES LIKE '%sort_buffer_size%';`
Change setting:
`SET GLOBAL sort_buffer_size = 256000000;`

**Comment by osworx** [comment]
> Also i tried to contact my host server provider and explained him about the problem but he couldn't help too.

Poor provider, you should look for a better one!

**Comment by taksha17** [comment]
> 

I think this shall work

But on firing the query on myphpadmin page i am getting this error
"#1227 - Access denied; you need (at least one of) the SUPER or SYSTEM_VARIABLES_ADMIN privilege(s) for this operation" 

can you suggest next steps

also my current buffers are as :-


innodb_sort_buffer_size | 1048576
myisam_sort_buffer_size | 8388608
sort_buffer_size | 262144

**Comment by eka7a** [comment]
This is not about opencart

**Comment by dabbmedia** [comment]
@taksha17 to make it work now, try changing admin default items per to a lower number:
Admin->System->Store->Option Tab->Products (first section)->Default Items Per Page (Admin).

My settings that work fine for about 35 products:
<img width="406" alt="Screen Shot 2021-12-02 at 12 52 08 PM" src="https://user-images.githubusercontent.com/2788552/144496489-17c37315-81de-4eb3-89fd-9cd171311277.png">


You will not be able to change global settings on most shared hosting setups. You will likely not find cPanel on low cost dedicated/cloud hosting ($5/mth).

Best

**Comment by taksha17** [comment]
I did my best to solve everything still but no result.
My cpanel refuses to connect with ssh-putty also my host is not increasing the server buffer sort size excusing that i am using a shared ip.
Also recently i purchased the annual hosting so cannot transfer to new one and cost me some extra bucks.
Also i have purchased journal theme for this host.So changing the host means purchasing the new journal theme also.
Can anyone suggest a better viable option to me ?

Please need help or my boss would eat up my job!!!

**Comment by osworx** [comment]
@taksha17 
Sorry, but my pity is limited.
If your "boss" has not that few bucks to pay for a qualified provider, it's not your fault.
And why have YOU bought a theme, would't that be the task of your "boss"?
Sounds all a bit strange.

But to close this here: the whole thing is not OpenCart related, so better continue either in the OpenCart Forum https://forum.opencart.com/ or ask at https://stackoverflow.com/

**Comment by dabbmedia** [comment]
@taksha17 try getting a clean install of OpenCart working with your products created/imported, but without the theme installed. If that works, then installing the theme breaks it, get support or a refund on the theme.

Also, try the install on your local machine and you may have more log file access to find the source of the problem. Pay attention to the version of OpenCart you install and what is supported by the theme.

If the theme is the issue and you can't get it fixed or buy another, try building your own theme by copying the OpenCart default theme. Updating the HTML of the theme and adding CSS can take a lot less time than battling things you have no control over.

I agree that "bosses" should always pay for hosting and the theme.

**Comment by mhcwebdesign** [comment]
Please continue this discussion on the OpenCart forum! This is not an OpenCart bug.
