### ISSUE TITLE
Another error causing

### ISSUE THREAD

**Issue by taksha17** [opencart/opencart#10281]
Replacing the code with the one suggested by you just renders up my home page.
But still my catalog-Product page in my opencart admin panel shows the same http 500 error

**Comment by mhcwebdesign** [comment]
What are you talking about? What code replacement?

**Comment by taksha17** [comment]
I replaced the code in mysqli file as suggested and it worked as home page started rendering.
But ironically the admin->catalog->product page has started showing the same http 500 error
Can you suggest what should i do?

**Comment by mhcwebdesign** [comment]
Please re-post on the OpenCart forum, with details on what exact code you replaced, for what OpenCart version.
