### ISSUE TITLE
[Master Branch] - Double &nbsp;

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#10284]
Perhaps something else than double &nbsp; ?

https://github.com/opencart/opencart/commit/00a8fc2283a119a072566715d3aa7474a9f3b38d#diff-6fcd65fa732907c226042c8809376a03c9f7020fffa4cd0321ebcf094602ff58R1336

**Comment by TheCartpenter** [comment]
Might be a good solution here: https://stackoverflow.com/a/67283550 .

**Comment by danielkerr** [comment]
only ur opinion

**Comment by TheCartpenter** [comment]
If it'd be only my opinion, the idea wouldn't be publicized on StackOverFlow originally.

**Comment by TheCartpenter** [comment]
https://stackoverflow.com/a/67283550 is another solution with CSS.
