### ISSUE TITLE
[V3.x] Events for controllers during regular starup do not fire

### ISSUE THREAD

**Issue by roman80k** [opencart/opencart#10294]
**What version of OpenCart are you reporting this for?**
3.0.x

**Describe the bug**
If you hook an event to a controller that is not loaded like `$this->load->controller($yourController)`, but rather is executed normally during startup - your event will not fire.

**To Reproduce**
Create an event for example to 
`admin/controller/localisation/stock_status/getList/before`

that should fire for example your custom module method
`extension/module/your_module/yourMethod`

Trace it down to `admin/controller/startup/router.php`, there is an events call:
`$result = $this->event->trigger('controller/' . $route . '/before', array(&$route, &$data));`

Trace it further to `system/engine/event.php`. 

In function `public function trigger($event, array $args = array())` there is such a fairy-tale magic:
`if (preg_match('/^' . str_replace(array('\*', '\?'), array('.*', '.'), preg_quote($value['trigger'], '/')) . '/', $event)) {`

This makes your event match default `config` events, such as `controller/*/before` that fire `event/language/before` - as you see this is not your wished method.

If you will comment those `config` wildcard events - you will notice, that your event is not satisfying those regex conditions, in other words - it is not fired.

**Expected behavior**
Very simple: such events should fire and there should be no mess with wildcard events.

**Comment by TheCartpenter** [comment]
I thought it was only me but I know what you mean in this scenario. I tried a few Event Triggers on the common folder, either from the catalog or from the admin folder, in the past as they don't seem to fire up either. I haven't tested it on the Master Branch yet.

**Comment by mhcwebdesign** [comment]
The method getList from class ControllerLocalisationStockStatus is protected, not public. It's not meant to trigger an event here.
