### ISSUE TITLE
[Master Branch] - api/sale/order.php file

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#10295]
I am not sure this portion of code would be quite ideal to use: https://github.com/opencart/opencart/commit/8646619e54b6f4e62ca9fa81333a04c2736dea8e#diff-61f6bdd132041861d2a5ea75788a15ac4a5311a4672c6973ad428ee234913571R413 since the sessionized order ID does not provide guarantee that it would originate from the same platform where the order ID needs to pulled which could cause an invalid, or a mixed, order information being retrieved from the database.

Rather, an order token should be used to ensure that the same compared token is matched; similarly to the customer and user login method (if not identical).

**Comment by danielkerr** [comment]
i sorted it
