### ISSUE TITLE
[Master Branch - Suggestion] - custom fields to be used in common folder

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#10291]
Custom field HTML codes can become quite repetitive and also massive in the TWIG files. A great suggestion would be to add a new controller in the common folder (both; admin and catalog) to be used with $this->load->controller and enter the keys and values in an array where parameters can be modified in event triggers to allow developers to address their own parameters from their extensions - including the type of custom fields that needs to be addressed.

In the TWIG files, we could use something like:

{{ payment_custom_fields }}
{{ shipping_custom_fields }}

and so forth (depending on the type) ...

This method could probably help to speed up the process by theme developers. This would also allow to reduce the expansion of codes regarding types of custom fields that needs to be used specifically as only one or two controllers could manage the entire custom fields throughout the platform - including those being used in the API.

**Comment by danielkerr** [comment]
I think setting up a html folder and creating controllers for each field type.

Anyway post suggestions in the discussion not here please.
