### ISSUE TITLE
[Master] - account/register

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#10297]
This lookup also means that all customers that are not requiring approval does not need a token: https://github.com/opencart/opencart/commit/0862b59fd78c7a384f8150d68cb88446b73274b7#diff-e2910d1482c663783acba12e20b3c81156130b8f483e2681197d16ddd8b8a327R217 . 

Which means, since guest checkout can be used by each stores, guests will not require to have guest tokens prior to this point.

**Comment by TheCartpenter** [comment]
A downside with this is that guest tokens would also create 403 error messages on the browser which may also include implicit bots along with valid customers before obtaining their tokens when attempting to login to their account...

**Comment by danielkerr** [comment]
i think already been fixed think already fixed. if not open another ticket.

**Comment by TheCartpenter** [comment]
The only thing that's been modified since your last change is that the same code lookup is located on line 219 instead of line 217: https://github.com/opencart/opencart/blob/master/upload/catalog/controller/account/register.php#L219 .

**Comment by danielkerr** [comment]
U are the oy one complaining about this. I have no idea the issue. Approval is set from customer group and setting
