### ISSUE TITLE
submit order 500 error  send mail

### ISSUE THREAD

**Issue by 283288675** [opencart/opencart#10298]
when i submit  order occur  500 error
![image](https://user-images.githubusercontent.com/15771966/145550152-d6c9e578-eed4-428c-96cc-1b2f9c991c72.png)

: *1565 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Error: EHLO not accepted from server! in /datalocal/server/linruistore/system/library/mail/smtp.php:121

please help me

 - PHP version    7.3
 - nginx   1.20

**Comment by ADDCreative** [comment]
It will be your SMTP settings. Post on https://forum.opencart.com/ for help.

**Comment by mhcwebdesign** [comment]
As ADDCreative said, please re-post on the OpenCart forum. It's not an OpenCart bug.
