### ISSUE TITLE
[Sugestion] Cutom_fields based on shipping address and payment address

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#10290]
**What version of OpenCart are you reporting this for?**
Master Branch

I think will be nice if in 4.0 custom fields will be based on shipping and payment address.

**Comment by TheCartpenter** [comment]
Might be a good idea here due to the new design of the APIs recently developed for the master branch since the new design is more up-to-date and opted to work with other platforms, payment and shipping service providers nowadays.

@WebkulOpencart: Master Branch.
