### ISSUE TITLE
sub folder create problem

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10302]
add id="input-directory" 
 type="hidden" name="directory" id="input-directory" value="{{ directory }}"/>

https://github.com/opencart/opencart/blob/f931c02460112f06cc0b6c8b0d39aa1055c1a773/upload/admin/view/template/common/filemanager_list.twig#L8

**Comment by webymaster** [comment]
Why is **id="input-directory"** needed for?

**Comment by eturerer** [comment]
$('#modal-image').on('click', '#button-create', function() {
        var url = 'index.php?route=common/filemanager|folder&user_token={{ user_token }}';
  
        var directory = $('#input-directory').val();
