### ISSUE TITLE
PHP8+ Required

### ISSUE THREAD

**Issue by pw44** [opencart/opencart#10308]
Hi,  

i got the latest version at github and when trying to install, i get PHP8+ Required message,

ubuntu 20.04 and I have php8.0 installed.

Any clue? 

Thx!

**Comment by ADDCreative** [comment]
Use [phpinfo()](https://www.php.net/manual/en/function.phpinfo.php) to check, You probably don't have PHP 8. You are probably better asking on https://forum.opencart.com/.

**Comment by anytizer** [comment]
You might have 2 different versions of PHP Installed: php8.0 and an older version. And, the older version may be attached to your Apache/httpd. Take a look at [How to Upgrade from PHP 7.x to PHP 8 on Ubuntu (Apache)](https://devanswers.co/how-to-upgrade-from-php-7-x-to-php-8-on-ubuntu-apache/)
