### ISSUE TITLE
PHP 8.1 Error on opencart 4 Dev.

### ISSUE THREAD

**Issue by domaingood** [opencart/opencart#10300]
Warning: Undefined variable $products in /extension/opencart/catalog/controller/module/featured.php on line 23Warning: foreach() argument must be of type array|object, null given in /extension/opencart/catalog/controller/module/featured.php on line 23

**Comment by cgcmart** [comment]
#9300

**Comment by anytizer** [comment]
#9761

**Comment by TheCartpenter** [comment]
The solution was already posted back in February in the #9300 commit ...

**Comment by danielkerr** [comment]
already fixed
