### ISSUE TITLE
OpenCart v4.0.0.0 BETA (TESTED)

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#10307]
Tested:
OpenCart v4.0.0.0 BETA
PHP 8.0.0.
FireFox

Store
1. I have inserted random data in checkout and i got this error:
 
`Warning: Undefined array key "payment_address" in catalog\controller\checkout\payment_method.php on line 61TypeError: Opencart\Catalog\Model\Checkout\PaymentMethod::getMethods(): Argument #1 ($payment_address) must be of type array, null given in catalog\model\checkout\payment_method.php on line 4`

2. Remove button "Continue" from checkout. It must be only 1 button as "Confirm order".

Attachment:
[](https://ibb.co/bKFDtx0)

3. Cart display

Attachment:
[https://ibb.co/Gdmh741]

Administration
1. Catalog >Category > Edit
Press Save
Click on Category Name
Press Save (again) - button doesn't work!

Attachment:
[https://ibb.co/42wtPBw]

2. Catalog > Product >Edit > Option
Text "Required" is out of screen.

Attachment:
[https://ibb.co/brx29Gq]

3. Extensions > Marketplace
I got this error:
```
Warning: Trying to access array offset on value of type null in admin\controller\marketplace\marketplace.php on line 168Warning: Trying to access array offset on value of type null in admin\controller\marketplace\marketplace.php on line 206Warning: Trying to access array offset on value of type null in admin\controller\marketplace\marketplace.php on line 223
OpenCart
```

Attachment:
[https://ibb.co/3hgFbk5]

```
2021-12-15 12:35:22 - PHP Warning: Trying to access array offset on value of type null
File: opencart-4.0.0.0B\admin\controller\marketplace\marketplace.php
Line: 168

2021-12-15 12:35:22 - PHP Warning: Trying to access array offset on value of type null
File: opencart-4.0.0.0B\admin\controller\marketplace\marketplace.php
Line: 206

2021-12-15 12:35:22 - PHP Warning: Trying to access array offset on value of type null
File: opencart-4.0.0.0B\admin\controller\marketplace\marketplace.php
Line: 223
```

4. Sales >Order > New order > Payment address > insert address. Address doesn't appear in order.

Attachment:
[https://ibb.co/s65GQQC]

5. Make more understandable. All lot of users from v2 and v3 do not know that then can click on "Analytics" to get all other extension type.

Attachment:
[https://ibb.co/CQsnW92]

**Comment by danielkerr** [comment]
will be fixing the html issues as they are already listed on the projects todo.

1. fixed.
2. dont know what u are talking about or care.
3. only if ur system can not connect to the oc server
4. only in your mind.
5. same as above
you dont need to report everything .
