### ISSUE TITLE
Products missing from Orders when submitting to Paypal

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#10306]
Related to post:
https://forum.opencart.com/viewtopic.php?f=185&t=203561&p=833876#p720547

OpenCart order don't have all products which has been ordered.
PayPal has full list of ordered products.

Example: Missing 1 of 3 products

**Comment by danielkerr** [comment]
version?

**Comment by danielkerr** [comment]
please open issue here:

https://github.com/opencart/opencart-3/issues
