### ISSUE TITLE
login_token variable names do not match

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10309]
user_token == login_token problem

	// Check to see if user is already logged
		if ($this->user->isLogged() && isset($this->request->get['user_token']) && isset($this->session->data['user_token']) && ($this->request->get['user_token'] == $this->session->data['user_token'])) {
			$this->response->redirect($this->url->link('common/dashboard', 'user_token=' . $this->session->data['user_token']));
		}

https://github.com/opencart/opencart/blob/f67a7ba81b581059a23185014baf4b048ee33820/upload/admin/controller/common/login.php#L53

**Comment by danielkerr** [comment]
user_token != login_token

there not the same. login_token if there to stop some types of brute force attacks. once logged in a user_token is created.
