### ISSUE TITLE
Inconsistent defaults in db query - undefined index error

### ISSUE THREAD

**Issue by reetp** [opencart/opencart#10305]
**What version of OpenCart are you reporting this for?**

Github latest and earlier versions

**Describe the bug**

When injecting via API or additional API methods there should be error checking on mysql values where possible to prevent errors. 

eg admin/model/catalog/category.php

We can see it here for 'top' where it defaults to 0 in the absence of a value, but doesn't for 'sort_order' or 'column' or 'status'

```
$this->db->query("INSERT INTO `" . DB_PREFIX . "category` SET `parent_id` = '" . (int)$data['parent_id'] . "', 
`top` = '" . (isset($data['top']) ? (int)$data['top'] : 0) . "', 
`column` = '" . (int)$data['column'] . "', 
`sort_order` = '" . (int)$data['sort_order'] . "', 
`status` = '" . (bool)$data['status'] . "', 
`date_modified` = NOW(), `date_added` = NOW()");
```

Perhaps better?

```
$this->db->query("INSERT INTO " . DB_PREFIX . "category SET parent_id = '" . (int)$data['parent_id'] . "', 
`top` = '" . (isset($data['top']) ? (int)$data['top'] : 0) . "', 
`column` = '" . (int)$data['column'] ? (int)$data['column'] : 0 . "', 
`sort_order` = '" . (int)$data['sort_order'] ? (int)$data['sort_order'] : 0 . "',
`status` = '" . (int)$data['status']  ? (int)$data['status'] : 1 . "', 
`date_modified` = NOW(), date_added = NOW()");
```

The category is allowed to be added, it is not a complete success with a warning typically like this:

```
<b>Notice</b>: Undefined index: column in <b>admin/model/catalog/category.php</b> on line <b>4</b>
{"data":{"category_id":114,"success":"Success: You have added category!"}}

```
This is made trickier to handle as it only logs to the log and does not return a proper failure code.

**Comment by danielkerr** [comment]
column should be at least 1.

**Comment by reetp** [comment]
> column should be at least 1.

Thanks.

Do you want a PR this? I'm no real coder.... :-)

**Comment by danielkerr** [comment]
no there i no issue with the original code but there is with yours. just posting rubbish with 0 testing.

**Comment by danielkerr** [comment]
`column` = '" . (int)$data['column'] ? (int)$data['column'] : 0 . "', 


needs to be minimum 1

**Comment by reetp** [comment]
> `column` = '" . (int)$data['column'] ? (int)$data['column'] : 0 . "',
> 
> needs to be minimum 1

Yeah I already said thanks.

**Comment by reetp** [comment]
> no there i no issue with the original code but there is with yours. just posting rubbish with 0 testing.

Actually it was your code that failed in the first place by making assumptions about values without testing.

You were the one who set this test:

(int)$data['top'] : 0)

But you did not set tests for other values, which by your own apparently perfect standards is "inconsistent" any time, but particular poor for a DB insertion , at least where I come from.

I mistakenly added a 1 and not 0 in my suggestion. It doesn't make the principle wrong and I'm not sure that is a reason to try and publicly embarrass or humiliate people who are only trying learn and assist, and choosing where to spend their money.

It was merely a suggestion. I'd have happily gone back and done it properly. Hey ho. You clearly know best.

**Comment by danielkerr** [comment]
Top and column are different.

**Comment by danielkerr** [comment]
Top and column are different.

**Comment by danielkerr** [comment]
And locked. I'm not wasting my time arguing with clowns
