### ISSUE TITLE
Unable to add a downloadable product

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#10304]
```
The uploaded file exceeds the 2mb max file size!
```

Admin > Catalog > Download
Try to add a new download. The upload fails instantly with the above message even for a small sized file.

The error index is: $_['error_upload_size'] in Master Branch:, met when below code runs:

```
f (this.files[0].size > 2000) {
    alert('{{ error_upload_size }}');
```

https://github.com/opencart/opencart/blob/2ef6e3d8eadb2d6f44a80d53f4efeace825383d8/upload/admin/view/template/catalog/download_form.twig#L94 and https://github.com/opencart/opencart/blob/2ef6e3d8eadb2d6f44a80d53f4efeace825383d8/upload/admin/controller/catalog/download.php#L164

It probably did not make 2mb. The db value oc_setting > config_file_max_size is 300000.
And php.ini has:

```
upload_max_filesize = 2M
```

**Comment by cgcmart** [comment]
#10337

**Comment by eka7a** [comment]
https://github.com/opencart/opencart/commit/434eab907998acee9fec55cc638e33556fe26cec
