### ISSUE TITLE
round(): Passing null to parameter

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#10312]
May be this line needs a fix/rewrite base don the error message:

    Unknown: round(): Passing null to parameter #1 ($num) of type int|float is deprecated in catalog\model\catalog\product.php on line 17

Here:
https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/product.php#L17

Some info:
I had installed OC with php 8.0 but later updated to PHP Version 8.1.1.
It is just a freshly installed database; no new products have been administered.

The query returned NULL value for rating column.

**Comment by webymaster** [comment]
I see this fixed and merged. Please close the issue

**Comment by anytizer** [comment]
Thanks.
