### ISSUE TITLE
Contact US Captcha does not work.

### ISSUE THREAD

**Issue by LinuxPractice** [opencart/opencart#10316]
**What version of OpenCart are you reporting this for?**

3.0.3.3

**Describe the bug**

With Google Captcha enabled, the code looks for an empty captcha session:

`if (empty($this->session->data['gcapcha'])) {`

After the first failure, the session is no longer empty and returns

`bool(true)`

Which bypasses the captcha check 

**To Reproduce**

1.  Enable Google Captcha
2.  Submit form without solving captcha.
3.  Submit again after first failure.

**Expected behavior**
The form is expected to be rejected and not send email but the form completes submission and send the email.

**Screenshots / Screen recordings**

Result of 
`         var_dump($this->session->data['gcapcha']);
           die();`

in ControllerExtensionCaptchaGoogle->validate()

Removing 

`if (empty($this->session->data['gcapcha'])) {`

and the ending bracket corrects the issue

![image](https://user-images.githubusercontent.com/1408971/146994466-5b33904c-84bf-4e4e-8028-cf67e2abd655.png)

**Server / Test environment (please complete the following information):**

no important

**Additional context**

**Comment by TheCartpenter** [comment]
Forum request.

**Comment by ADDCreative** [comment]
Are you sure? The only place $this->session->data['gcapcha'] is set is on success. Yes, it only has to be passed once per session, but that is by design apparently. 

https://github.com/opencart/opencart/blob/04a547c8d7f135c81fa0a9e791c5082477d6cdd0/upload/catalog/controller/extension/captcha/google.php#L31-L33

**Comment by LinuxPractice** [comment]
I further tested this with:

Brave  V1.33.106 (What I initially tested on)
Firefox 95.0.2 (64-bit
Edge Version 96.0.1054.62

This seems to only happen in Brave and based on the dozens of automated spam I get a day, from bots as well.

Adding
`    
            var_dump($this->session->data['gcapcha']);
            die();`

Directly after `public function validate() {`

Prints NULL on FFOX and EDGE but bool(true) when posted from Brave.

When placed after `if (empty($this->session->data['gcapcha'])) {`  FFOX and EDGE both echo out null and kill the script but in Brave, the form gets posted and sent to the success page and I get the email.

**Comment by mhcwebdesign** [comment]
gCaptcha is not very good at  repelling spambots. On my own and our clients' websites I don't captchas at all, we use the Spambot Buster which doesn't need a captcha. (https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=38244)

Nevertheless, have you got in touch with the authors of Brave?

**Comment by LinuxPractice** [comment]
The browser should not be relevant.  In Brave the `g-recaptcha-response: `  gets submitted empty same as it gets sent via Firefox. 

`------WebKitFormBoundaryNCIKSwRCUz1wXJSl
Content-Disposition: form-data; name="g-recaptcha-response"


------WebKitFormBoundaryNCIKSwRCUz1wXJSl--`


Looking more at the code, 

`            if (!isset($this->request->post['g-recaptcha-response'])) {
                return $this->language->get('error_captcha');
            }` 

does not make sense either because the post variable is set, it is just empty.

**Comment by mhcwebdesign** [comment]
What do you get in your $_POST ?

**Comment by LinuxPractice** [comment]
This is the post received on the server in Brave

`array(4) {
  ["name"]=>
  string(13) "Random Person"
  ["email"]=>
  string(9) "no@no.way"
  ["enquiry"]=>
  string(23) "This is a spam message."
  ["g-recaptcha-response"]=>
  string(0) ""
}`

In Firefox:

`array(4) {
  ["name"]=>
  string(19) "Random Firefox User"
  ["email"]=>
  string(9) "no@no.way"
  ["enquiry"]=>
  string(25) "test this in firefox mkay"
  ["g-recaptcha-response"]=>
  string(0) ""
}`

**Comment by mhcwebdesign** [comment]
Can you show show all of **$_POST** and **$this->request->post** and **$this->session->data** submitted by the different web browsers at the same time, so as to be able to compare then all?

**Comment by eualexey** [comment]
I do confirm the same issue. Spent the whole day trying to understand why form is submitted without captcha. 

This version works
```
public function validate() {
	$this->load->language('extension/captcha/google_captcha');
	$recaptcha = file_get_contents('https://www.google.com/recaptcha/api/siteverify?secret=' . urlencode($this->config->get('google_captcha_secret')) . '&response=' . $this->request->post['g-recaptcha-response'] . '&remoteip=' . $this->request->server['REMOTE_ADDR']);
    $recaptcha = json_decode($recaptcha, true);
	if ($recaptcha['success']) {
		return true;
	} else {
		return false;
	}
}
    
```
So I removed this line 

`if (empty($this->session->data['gcapcha'])) {` 
and changed outcome of the method to true/false result.

**Comment by danielkerr** [comment]
please open an issue here:

https://github.com/opencart/opencart-3/issues
