### ISSUE TITLE
Permission Denied!

### ISSUE THREAD

**Issue by domaingood** [opencart/opencart#10315]
INSERT INTO `oc_user` (`user_id`, `user_group_id`, `username`, `password`, `salt`, `firstname`, `lastname`, `email`, `image`, `code`, `ip`, `status`, `date_added`) VALUES
(1, 1, 'admin', '8e4f839c67937bf029203ab8976b1f605862981f', 'xQjimkNK0', 'John', 'Doe', 'contact@villagedefrance.net', '', '', '::1', 1, '2016-03-07 15:14:57');

 Permission Denied!
You do not have permission to access this page, please refer to your system administrator.

Opencart Version 4.0.0.0_b
PHP 8.1
MYSQL 8.0

**Comment by danielkerr** [comment]
just tested works fine
