### ISSUE TITLE
Smart button error

### ISSUE THREAD

**Issue by matthew1531** [opencart/opencart#10319]
**What version of OpenCart are you reporting this for?**
Version 3.0.3.8

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

shopping cart page 
error from paypal smart button

**To Reproduce**
1. Go to 'Home Extensions PayPal Commerce Platform'
2. Click on 'Smart Button" 
Options do not show on 

Message Align 
Message Size 
Message Layout
Message Text Color 
Message Text Size 
Message Banner Color 
Message Banner Ratio

Cart page shows error 

Notice: Undefined index: message_align in /homepages/24/d891758801/htdocs/clickandbuilds/OpenCart/ShoppersHall/catalog/controller/extension/module/paypal_smart_button.php on line 87Notice: Undefined index: message_size in /homepages/24/d891758801/htdocs/clickandbuilds/OpenCart/ShoppersHall/catalog/controller/extension/module/paypal_smart_button.php on line 88Notice: Undefined index: message_layout in /homepages/24/d891758801/htdocs/clickandbuilds/OpenCart/ShoppersHall/catalog/controller/extension/module/paypal_smart_button.php on line 89Notice: Undefined index: message_text_color in /homepages/24/d891758801/htdocs/clickandbuilds/OpenCart/ShoppersHall/catalog/controller/extension/module/paypal_smart_button.php on line 90Notice: Undefined index: message_text_size in /homepages/24/d891758801/htdocs/clickandbuilds/OpenCart/ShoppersHall/catalog/controller/extension/module/paypal_smart_button.php on line 91Notice: Undefined index: message_flex_color in /homepages/24/d891758801/htdocs/clickandbuilds/OpenCart/ShoppersHall/catalog/controller/extension/module/paypal_smart_button.php on line 92Notice: Undefined index: message_flex_ratio in /homepages/24/d891758801/htdocs/clickandbuilds/OpenCart/ShoppersHall/catalog/controller/extension/module/paypal_smart_button.php on line 93Notice: Undefined index: message_width in /homepages/24/d891758801/htdocs/clickandbuilds/OpenCart/ShoppersHall/catalog/controller/extension/module/paypal_smart_button.php on line 127Notice: Trying to access array offset on value of type null in /homepages/24/d891758801/htdocs/clickandbuilds/OpenCart/ShoppersHall/catalog/controller/extension/module/paypal_smart_button.php on line 127

**Expected behavior**

**Screenshots / Screen recordings**
[If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app]

Screen video 
**https://www.loom.com/share/f40f65b115b04c1ba644d9b7c85c22e7**

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by ADDCreative** [comment]
You need to download the latest version of the extension.

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=38358

Sadly 3.0.3.8 was released without it being updated.
