### ISSUE TITLE
Product Return and Review feature OC Ver 3.0.3.8

### ISSUE THREAD

**Issue by tkerala** [opencart/opencart#10318]
In **Opencart** we can purchase a product and just after that we can **Return** it. How it is possible?
It should be **Cancel** till it **delivered** (Order Complete). Please help me out if there is any option or fix this issue.

I want Return form to work only when that customer received the product and not before. 
And one more thing, the customer can write review without buying the product. Please make it "Can review only after purchase".
Like other shopping apps.

Could you please do the changes in next update??

**Comment by harman-jack** [comment]
> In **Opencart** we can purchase a product and just after that we can **Return** it. How it is possible? It should be **Cancel** till it **delivered** (Order Complete). Please help me out if there is any option or fix this issue.
> 
> I want Return form to work only when that customer received the product and not before. And one more thing, the customer can write review without buying the product. Please make it "Can review only after purchase". Like other shopping apps.
> 
> Could you please do the changes in next update??

Yes, I agree with you that there is no cancellation or return feature available for Buyers, these features are only available for Sellers. I am also requesting to Opencart team to provide these features for Buyers also.

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/projects/6#card-82048028
