### ISSUE TITLE
OC 4.x & 3.0.x > Language Editor not parsing edited/changed HTML-Tags correct

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#10311]
Currently it is set to add/edit text in a textarea field:

https://github.com/opencart/opencart/blob/f67a7ba81b581059a23185014baf4b048ee33820/upload/admin/view/template/design/translation_form.twig#L64

But has the text HTML-Code like here:
https://github.com/opencart/opencart/blob/f67a7ba81b581059a23185014baf4b048ee33820/upload/catalog/language/en-gb/account/success.php#L6

``` $_['text_success']  = '<p>Congratulations! Your new account has been successfully created!</p> <p>You can now take advantage of member privileges to enhance your online shopping experience with us.</p> <p>If you have ANY questions about the operation of this online shop, please e-mail the store owner.</p> <p>A confirmation has been sent to the provided e-mail address. If you have not received it within the hour, please <a href="%s">contact us</a>.</p>';```

the tags are not parsed currectly!

Solution: either assign a **text editor** to the textarea field (admin), or use ```html_entity_decode( $text, ENT_QUOTES, 'UTF-8' )``` to display the edited text correct (catalog).

**Comment by ADDCreative** [comment]
https://github.com/opencart/opencart/issues/8742

**Comment by osworx** [comment]
Sorry, did not see that commit - closing issue.
