### ISSUE TITLE
Paypal payment error

### ISSUE THREAD

**Issue by matthew1531** [opencart/opencart#10320]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect? 
Payment

**To Reproduce**
1. Go to 'View Cart with login'
2. Click on 'Paypal'
3. Scroll down to 'pop up message'
"The value of a field is either too short or too longoogle.com/search?q=The+value+of+a+field+is+either+too+short+or+too+long.+Please+choose+another+payment+method+or+<a+href%3D"http%3A%2F%2Fshoppershall.com%2Findex.php%3Froute%3Dinformation%2Fcontact"+target%3D"_blank">contact+us<%2Fa>.&sxsrf=AOaemvJheumByCfAyv-XResDMKwkoHC-tg%3A1640431376578&ei=EP_GYf2_Ir6QseMP866L6AU&ved=0ahUKEwj9h-qL6_70AhU-SGwGHXPXAl0Q4dUDCA4&uact=5&oq=The+value+of+a+field+is+either+too+short+or+too+long.+Please+choose+another+payment+method+or+<a+href%3D"http%3A%2F%2Fshoppershall.com%2Findex.php%3Froute%3Dinformation%2Fcontact"+target%3D"_blank">contact+us<%2Fa>.&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGAFKBAhGGABQhxZYhxZgkBxoAXAAeACAAQCIAQCSAQCYAQCgAQHAAQE&sclient=gws-wizg. Please choose another payment method or <a href="http://shoppershall.com/index.php?route=information/contact" target="_blank">contact us</a>."

**Expected behavior**

**Screenshots / Screen recordings**
https://www.loom.com/share/98e7633fc4f14b1b9bd2af68cc25ae75

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by harman-jack** [comment]
> **What version of OpenCart are you reporting this for?**
> 
> **Describe the bug** A clear and concise description of what the bug is What section does it affect? Payment
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'View Cart with login'
> 2. Click on 'Paypal'
> 3. Scroll down to 'pop up message'
> 4. See error
>    "The value of a field is either too short or too longoogle.com/search?q=The+value+of+a+field+is+either+too+short+or+too+long.+Please+choose+another+payment+method+or+<a+href%3D"http%3A%2F%2Fshoppershall.com%2Findex.php%3Froute%3Dinformation%2Fcontact"+target%3D"_blank">contact+us<%2Fa>.&sxsrf=AOaemvJheumByCfAyv-XResDMKwkoHC-tg%3A1640431376578&ei=EP_GYf2_Ir6QseMP866L6AU&ved=0ahUKEwj9h-qL6_70AhU-SGwGHXPXAl0Q4dUDCA4&uact=5&oq=The+value+of+a+field+is+either+too+short+or+too+long.+Please+choose+another+payment+method+or+<a+href%3D"http%3A%2F%2Fshoppershall.com%2Findex.php%3Froute%3Dinformation%2Fcontact"+target%3D"_blank">contact+us<%2Fa>.&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGAFKBAhGGABQhxZYhxZgkBxoAXAAeACAAQCIAQCSAQCYAQCgAQHAAQE&sclient=gws-wizg. Please choose another payment method or [contact us](http://shoppershall.com/index.php?route=information/contact)."
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots / Screen recordings** https://www.loom.com/share/98e7633fc4f14b1b9bd2af68cc25ae75
> 
> **Server / Test environment (please complete the following information):**
> 
> * Local development? Deployed to a web server?
> * Operating system
> * PHP version
> * Apache version
> * Browser(s) tested with [e.g. chrome, safari - if applicable]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

Hi, 
I think the issue you have mentioned is from Paypal payment module.

**Comment by ADDCreative** [comment]
If using the PayPal Commerce Platform extension, make sure you are using the latest from the marketplace.
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=38358

The one in 3.0.3.8 was never updated before release.

I suspect the issue is something to do whit the length of the product names. PayPal probably has a limit of 127 that the extension doesn't check for.

**Comment by matthew1531** [comment]
Happy new year there,

Thank you for the comment.

Yes, it is the latest version.

**Comment by danielkerr** [comment]
please open an issue here:

https://github.com/opencart/opencart-3/issues
