### ISSUE TITLE
mail(): Failed to connect to mailserver

### ISSUE THREAD

**Issue by harman-jack** [opencart/opencart#10327]
**What version of OpenCart are you reporting this for?**
in all version

**Describe the bug**
As by default in Store settings, Alert Mail allowed for Orders and mail engine details are not filled it generates an error.
It affects the checkout process, like Cart not empty after an order is placed. It generates issues when implementing core mail files in APIs.

**To Reproduce**
1. Install fresh Opencart
2. and now place an order 

**Expected behavior**
if due to any reason mail engine details are not filled and error reporting is enabled, the system will check the mail details and if they are available then connect to the mail server, otherwise should not show any error.

**Screenshots / Screen recordings**
![oc_git_error_1_1](https://user-images.githubusercontent.com/55911839/147632801-1ab2d75f-74b4-45a7-bf28-4ca142a86399.PNG)
![oc_git_error_1_2](https://user-images.githubusercontent.com/55911839/147632808-bb5fa15e-f0c3-48e9-97bc-b228728d3558.PNG)

**Additional context**
This is not an actual error, it occurs due to the unavailability of mail details and details control is always in our hands.

**Comment by ADDCreative** [comment]
The error you are seeing is due to your server configuration, not to do with OpenCart settings. You just need to make sure displaying of errors is off in your PHP settings, system/config/default.php and in your OpenCart settings.

**Comment by harman-jack** [comment]
Hello @ADDCreative

Yes, you are correct it's due to server configuration, but my concern is if somehow I am not filled Mail engine details and someone enables error reporting, In that case, is it ok to get this error message

**Comment by ADDCreative** [comment]
In reality on a production server with PHP set up correctly you would be unlikely to see that error. There would be a lot more other issues caused by having display errors on. That's why it should always be off on a production server. Have a read of what the default php.ini included with PHP says about the display_errors setting.
