### ISSUE TITLE
Fix class check for "success" and javascript validation 

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10336]
https://github.com/opencart/opencart/blob/5e98122e8562cfb68d8326c6dde7cd1f8aeb2e98/upload/catalog/view/javascript/common.js#L273

`$('#alert').prepend('<div class="alert alert-success"><i class="fas fa-check-circle"></i> ' + json.success + ' <button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>');`

Line 453 Missing semicolon.
Line 458 Missing semicolon.
Line 463 Missing semicolon.
Line 472 Missing semicolon.
Line 517 Missing semicolon.
Line 527 Missing semicolon.

**Comment by cgcmart** [comment]
master branch source file updated, the issue line moved to L245

**Comment by danielkerr** [comment]
all semicolon are where they should be
