### ISSUE TITLE
Re: Fixed file_max_size calculate

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10337]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
@eka7a's commit 87ab3ae
upload/install/opencart.sql Line 2012
`(0, 'config', 'config_file_max_size', '20', 0),`
config_file_max_size 20 is read as 20 mb, according to oc setting tip:
upload/admin/language/en-gb/setting/setting.php Line 211
`$_['help_file_max_size']               = 'The maximum file size you can allow customers to upload. Enter as megabyte.';`

Some users ignore **megabyte** and enter a large number that exceeds php.ini limit setting.
By default, the maximum upload file size for PHP scripts is set to 128 megabytes.
OC set a lower limit:
`upload_max_filesize = 20M`

In upload/admin/controller/common/filemanager.php line 9 and other files somewhere should be coding as follows:
`$data['config_file_max_size'] = ((int)$this->config->get('config_file_max_size') * 1024);`

The result = 20480 bytes

upload/admin/controller/catalog/download.php line 164
upload/admin/controller/catalog/product.php line 305
upload/admin/controller/common/filemanager.php line 9
upload/admin/controller/customer/customer.php line 349
upload/admin/controller/marketing/affiliate.php line 274
upload/admin/controller/marketplace/installer.php line 24
upload/admin/controller/sale/order.php line 414
upload/admin/controller/tool/backup.php line 12

upload/catalog/controller/account/address.php line 136
upload/catalog/controller/account/affiliate.php line 22
upload/catalog/controller/account/edit.php line 39
upload/catalog/controller/account/register.php line 39
upload/catalog/controller/checkout/payment_address.php line 9
upload/catalog/controller/checkout/register.php line 15
upload/catalog/controller/checkout/shipping_address.php line 10
upload/catalog/controller/product/product.php line 238

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by eka7a** [comment]
Your calculation is wrong. config_file_max_size * 1024 * 1024 = 20.971.520 bytes = 20MB or your value
https://github.com/opencart/opencart/blob/b84b0de1f50459e9a88347110f2f519a95a7ef31/upload/admin/controller/common/filemanager.php#L9

file max size is not the same as upload file size. The upload file is the limit of your server. File max size is a setting your specify.

**Comment by eka7a** [comment]
Added upper limit warning.
8456a0ec060990697551c1a7d238cf04c7a7d77a

**Comment by cgcmart** [comment]
> Your calculation is wrong. config_file_max_size * 1024 * 1024 = 20.971.520 bytes = 20MB or your value
> 
> https://github.com/opencart/opencart/blob/b84b0de1f50459e9a88347110f2f519a95a7ef31/upload/admin/controller/common/filemanager.php#L9

It's not! config_file_max_size * 1024 * 1024 = 20.971.520 bytes = **20GB**. 
My calculation: **config_file_max_size * 1024 = 20480byte = 20MB**
