### ISSUE TITLE
OC4 move oc_product.viewed field to a separate table

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#10339]
There is no sense in `viewed` field in `oc_product` table.

Only thing it does - clears MySQL cache for the whole table on every product view. This creates useless server load on every product query.

As this is the most readable table in OC and is used in 99% only in admin area reports it is recommended to move this field to a separate table.

As this field is not needed in 99.9% queries in frontend, this will significantly speed up MySQL cache and will clear it only when product table is really updated with important information, like model, quantity, price, status, etc, which are really used for every product query.

This is kind of silly to keep one most writable field in most readable table. Never could understand this for a decade since OC 1.4.

Also this statistics can be extended by `store_id` and `language_id`. This can be useful for multistore and multilanguage extensions like "Popular products". Because now it is quite wrong, when a popular product in one store_id is displayed as popular on another. It makes this field even more useless and even harmful.

If @danielkerr is ready to change this, he can give a new table name and structure and I can prepare a pull request for OC4.

https://github.com/opencart/opencart/blob/d885fa8caa20f7d740204830410419c9a4a186cd/upload/catalog/model/catalog/product.php#L5

Here is an example of such table:
```
CREATE TABLE `oc_product_statistics` (
	`product_id` INT(11) NOT NULL DEFAULT '0',
	`store_id` INT(11) NOT NULL DEFAULT '0',
	`language_id` INT(11) NOT NULL DEFAULT '0',
	`viewed` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`product_id`, `store_id`, `language_id`) USING BTREE
)
```

**Comment by danielkerr** [comment]
your right. will remove
 change to its own table

**Comment by TheCartpenter** [comment]
The product_id field could still be misleading based on what it says on the first post. Products gets deleted with the stats from the same table is one thing but to keep the same product ID where the same product ID could represent a new unrelated product later on is another. The `model` field should be used rather than the product ID to ensure the uniqueness of the products.

**Comment by danielkerr** [comment]
already done
