### ISSUE TITLE
ParseError: Unclosed '{' on line 723 does not match ')' in ../admin/controller/setting/setting.php on line 726

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10348]
https://github.com/opencart/opencart/blob/bffc4254f395bbae7740e1189b6f9ebec2c7dd54/upload/admin/controller/setting/setting.php#L726

Fix:
`if ($this->request->post['config_file_max_size'] > $upload_max_filesize) {`

**Comment by slicktdog08** [comment]
I just encountered this also. Thanks for fix. Please merge into project source soon

**Comment by slicktdog08** [comment]
Got another error after making your change

`ParseError: syntax error, unexpected token ";" in /[redacted]/html/admin/controller/setting/setting.php on line 581`

**Comment by slicktdog08** [comment]
Sorry I made change in wrong place. Your change did solve the problem for me :)
