### ISSUE TITLE
[Master Branch] Gmail link from language settings is deprecated

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#10346]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
This link from language settings is not valid anymore
`https://security.google.com/settings/security/apppasswords`

https://github.com/opencart/opencart/blob/master/upload/admin/language/en-gb/setting/setting.php#L205

**Comment by webymaster** [comment]
I see it works fine. I just logged in to my GMail account and used the link to generate an app password.

**Comment by condor2** [comment]
ok, then :)
