### ISSUE TITLE
Extension installer should correctly calculate the maximum upload size

### ISSUE THREAD

**Issue by webymaster** [opencart/opencart#10342]
https://github.com/opencart/opencart/blob/d885fa8caa20f7d740204830410419c9a4a186cd/upload/admin/controller/marketplace/installer.php#L21

PHP INI setting for upload_max_filesize can't be simply convertred to integer, as it's sometimes written as a number with a letter (1K, 1M, 1G).

This error is always triggered showing a message "The uploaded file exceeds ..."

**Comment by cgcmart** [comment]
#10337 
upload/admin/controller/marketplace/installer.php 
change line 24 to
`$data['config_file_max_size'] = ((int)preg_filter('/[^0-9]/', '', ini_get('upload_max_filesize')) * 1024);`

**Comment by eka7a** [comment]
https://github.com/opencart/opencart/commit/434eab907998acee9fec55cc638e33556fe26cec
