### ISSUE TITLE
OC Ver 3.0.3.8 broken link to Twig Syntax explanation

### ISSUE THREAD

**Issue by SoftwareOnbekend** [opencart/opencart#10357]
Version OC 3.0.3.8

Broken link when to get info about Twig at the "Theme editor"
![image](https://user-images.githubusercontent.com/40216653/148677565-50900ad2-57d3-4e84-a594-8121843c5139.png)

The website is not available anymore.
Where can we update the link info to https://twig.symfony.com/doc/  ?
I think this is the correct link at this moment.

S.O.

**Comment by danielkerr** [comment]
the link works
