### ISSUE TITLE
OC 3.0.3.8 With PHP 8  Googleshopping warning when to dublicate or remove product in admin panel

### ISSUE THREAD

**Issue by SoftwareOnbekend** [opencart/opencart#10358]
OC 3.0.3.8
PHP 8.0.14

Googleshopping warning when to dublicate or remove products.

Warning when to dublicate a product in admin panel:

Warning: googleshopping\Googleshopping::integer(): Argument #1 ($product_id) must be passed by reference, value given in /customers/a/3/7/XXXXXXXX/httpd.www/original/system/library/googleshopping/googleshopping.php on line 583Warning: Cannot modify header information - headers already sent by (output started at /customers/a/3/7/XXXXXXXX/httpd.www/original/admin/controller/startup/error.php:34) in /customers/a/3/7/XXXXXXXX/httpd.www/original/system/library/response.php on line 36

Warning when to remove a product in admin panel:

Warning: googleshopping\Googleshopping::integer(): Argument #1 ($product_id) must be passed by reference, value given in /customers/a/3/7/XXXXXXXX/httpd.www/original/system/library/googleshopping/googleshopping.php on line 583Warning: googleshopping\Googleshopping::integer(): Argument #1 ($product_id) must be passed by reference, value given in /customers/a/3/7/XXXXXXXX/httpd.www/original/system/library/googleshopping/googleshopping.php on line 583Warning: googleshopping\Googleshopping::integer(): Argument #1 ($product_id) must be passed by reference, value given in /customers/a/3/7/XXXXXXXX/httpd.www/original/system/library/googleshopping/googleshopping.php on line 583Warning: Cannot modify header information - headers already sent by (output started at /customers/a/3/7/XXXXXXXX/httpd.www/original/admin/controller/startup/error.php:34) in /customers/a/3/7/XXXXXXXX/httpd.www/original/system/library/response.php on line 36

This doesn't happen when we use PHP 7.4.

S.O.

**Comment by mundyman1** [comment]
happen to me too did you find out anything I just disabled the products until someone fixes this bug

**Comment by mhcwebdesign** [comment]
OpenCart 3.0.3.8 is not compatible with PHP 8.x. Try the 3.0.x.x_Maintenance branch which already has a number of bugfixes with regards to PHP8.x support.

**Comment by danielkerr** [comment]
please open an issue here:

https://github.com/opencart/opencart-3/issues
