### ISSUE TITLE
Uncaught TypeError: $(...).daterangepicker is not a function

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10369]
https://github.com/opencart/opencart/blob/f2077fef828d78cc952b9365a86e87dd613f144c/upload/catalog/view/javascript/common.js#L41

> Uncaught TypeError: $(...).daterangepicker is not a function
>     at HTMLDocument.datetimepicker (common.js:41:13)
>     at e (jquery-3.6.0.min.js:2:30038)
>     at t (jquery-3.6.0.min.js:2:30340)

Change line 40
`var datetimepicker = function () {`
to:
`var daterangepicker = function() {`

**Comment by Aks8578** [comment]
Just replace that with this
$( document ).ready(function() {
     $('.date').daterangepicker({
        singleDatePicker: true,
        autoApply: true,
        locale: {
            format: 'YYYY-MM-DD'
        }
    });
});

**Comment by cgcmart** [comment]
Change line 40 is containing the whole section `// Daterangepicker` line 40 - line 71.
