### ISSUE TITLE
OC4 daterangepicker

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#10361]
In frontend, if you try to click any button (header cart for example) you get JS error:
`Uncaught TypeError: $(...).daterangepicker is not a function`

daterangepicker.js is not loaded on every page, while is called globally in common.js on document.load and for every button tag.
https://github.com/opencart/opencart/blob/8e06aee094a805c2daf4399f458e0a5d610aeaa5/upload/catalog/view/javascript/common.js#L74

I think it is wrong to assign it to every button

Same with tooltip
https://github.com/opencart/opencart/blob/8e06aee094a805c2daf4399f458e0a5d610aeaa5/upload/catalog/view/javascript/common.js#L37

**Comment by CallMeSag3** [comment]
hey how have you resolved this?
