### ISSUE TITLE
product autocomplete doesn't work

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10360]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
catalog >> products >> links
extensions >> extensions >> modules >> featured >> products
**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by cgcmart** [comment]
This fix does not solve the issue, that look related to javascript autocomplete  function as well. And extension featured product module.

**Comment by danielkerr** [comment]
it was php related

**Comment by stalker780** [comment]
@danielkerr 
Autocomplete is still broken.

Looks like something is wrong with option groups.

![image](https://user-images.githubusercontent.com/6297070/148836737-c0cc47b2-54a9-4e7a-99d8-a179efbcbcc3.png)

![image](https://user-images.githubusercontent.com/6297070/148836769-8eaf6c0e-b10c-40c2-9859-38fbcd24ce16.png)

**Comment by cgcmart** [comment]
@stalker780 
Does autocomplete function work the released version 4?
DanielKerr says, he doesn't use jquery-ui.
