### ISSUE TITLE
Error on Upload Extension "Main Branch" 4.0.0.0_b

### ISSUE THREAD

**Issue by mullernato** [opencart/opencart#10379]
"Main Branch" - 4.0.0.0_b

**Describe the bug**
When uploading an extension, the validation in javascript returns a message saying that the file size exceeds the size configured in php.

But the error is in the calculation of the variable $data['config_file_max_size'], because the javascript takes the size of the file in bytes and the calculation made in the file admin/controller/marketplace/installer.php is multiplying only by 1000 the value set in the php.ini which is done in Megabytes (ex: upload_max_filesize = 10M or post_max_size = 10M
). 

**To Reproduce**
1. go to: Extensions > Installer
2. upload a file

**To Fix Change the line **

$data['config_file_max_size'] = ((int)preg_filter...

**To**

$upload_max_filesize = ini_get('upload_max_filesize');
$type_size = preg_filter('/[^a-zA-Z]/', '', $upload_max_filesize);
$calc = ($type_size === 'M') ? 1024*1024 : 1024;
$data['config_file_max_size'] = ((int)preg_filter('/[^0-9]/', '', $upload_max_filesize) * $calc);

**Server / Test environment (please complete the following information):**
 - Local development (nginx + php8)
 - Ubuntu 20.04
 - PHP 8.0
 - Nginx
 - Firefox
 - Opencart 4.0.0.0_b

**Comment by danielkerr** [comment]
already been fixed
