### ISSUE TITLE
setting store time zone corrupts logins

### ISSUE THREAD

**Issue by swan-1** [opencart/opencart#10372]
**What version of OpenCart are you reporting this for?**
3.0.3.8

**Describe the bug**
In a fresh install, setting up a store (System->Settings) , the first 2 tabs are fine, but if I change time zone tom America/Los_Angeles, login credentials fail.  If I try to load a new page it asks me to login again and all logins (user & admin) fail. I tried a couple of other time zones.  One worked, one failed.

**To Reproduce**
1. Fresh install
2. Goto System->settings
3. Create a store, fill out General and Store tabs
4. Change time zone in Local tab to America/Los_Angeles
5. Save the settings and try to go to a new page, ie. Dashboard

**Comment by ADDCreative** [comment]
Duplicate of https://github.com/opencart/opencart/issues/9237.
