### ISSUE TITLE
PHP Unknown:  round(): Passing null to parameter #2 ($precision) of type int is deprecated

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10380]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
PHP Unknown:  round(): Passing null to parameter #2 ($precision) of type int is deprecated in ../system/storage/vendor/twig/twig/src/Extension/CoreExtension.php on line 547

Logs did not indicate  what commit caused twig thrown out round() issue. But the issue logged after Daniel's commit "more subscripton work" #bfbf402

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
u provided f all information like the page u were on.

**Comment by cgcmart** [comment]
It looks it's related system settings: php 8.0 extension php pd.

**Comment by danielkerr** [comment]
SWITCH TO 8.1

also yes u need the gd extension enbable which i think is default in 8.1
