### ISSUE TITLE
/system/library/cart/tax.php non well formed numeric value encountered PHP Notice

### ISSUE THREAD

**Issue by gegenyrichard** [opencart/opencart#10385]
OC version 3.0.3.2 (affected all 3.x version)

Affected PHP versions over 7.1.x
(Notices and warnings on arithmetic with invalid strings)
https://www.php.net/manual/en/migration71.other-changes.php

admin/controller/extension/shipping/
All shipping controllers what has cost.

It can generate PHP Notice on checkout page 
"... non well formed numeric value encountered /system/library/cart/tax.php ..."
on line 71 and 113

To Reproduce
example flat shipping method, 
set up cost to invalid php data type
like 99,23 (string)

Navigate to checkout on FrontEnd, and PHP warning appear.

Suggested solution:
To expand validate() function 
- validate cost format
- or use intval() for this post value
to aviod this.

Server / Test environment:
 - web server (hosted)
 - Operating system: Linux s34 4.19.0-13-amd64 - Debian 4.19.160-2 (2020-11-28) x86_64
 - PHP version: 7.3.33
 - Apache version - not depend on it, php notice
 - Browser(s) tested with - not depend on it, php notice

**Comment by danielkerr** [comment]
u are using a eu format. instead of , it should be .

**Comment by BeaverUI** [comment]
I occasionally get these same messages in my logs, however all my cost are OK as far as I can see. It's definitely not there for all orders, OpenCart just very rarely reports this message. Any clue where to look?
