### ISSUE TITLE
[master] Backup file upload - file exceeds the 2Mmb max file size!

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#10387]
**What version of OpenCart are you reporting this for?** master

**Describe the bug**
Goto backup / restore
Click upload button and choose a file for upload
Result: Warning: The uploaded file exceeds the 2Mmb max file size!
even if the file has 25kb

**Expected behavior**
Uploading the file 

**Server / Test environment (please complete the following information):**
 - Local development
 - Operating system Linux
 - PHP version 8.0
 - nginx version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22]  96.0.1

**Comment by cgcmart** [comment]
upload/admin/controller/tool/backup.php

try to commit line 11 - line 12:
```
		$data['error_upload_size'] = sprintf($this->language->get('error_upload_size'), ini_get('upload_max_filesize'));

		$data['config_file_max_size'] = ((int)preg_filter('/[^0-9]/', '', ini_get('upload_max_filesize')) * 1000);
```
with:

```
		$upload_max_filesize = (int)preg_filter('/[^0-9]/', '', ini_get('upload_max_filesize'));

		$data['error_upload_size'] = sprintf($this->language->get('error_upload_size'), $upload_max_filesize);

		$data['config_file_max_size'] = ($upload_max_filesize * 1024 * 1024);
```

**Comment by pemaier** [comment]
Thank you I was testing it ... it works.
But more important that the error is not getting into the release)

**Comment by superbobogithub** [comment]
I installed the latest opencart code, and I encountered the same problem. The extension is a few kb in size. According to your modification, it still prompts Warning: The uploaded file exceeds the 2Mmb max file size!

**Comment by superbobogithub** [comment]
I installed the latest opencart code, and I encountered the same problem. The extension is a few kb in size. According to your modification, it still prompts Warning: The uploaded file exceeds the 2Mmb max file size!

**Comment by danielkerr** [comment]
fixed
