### ISSUE TITLE
New theme not working after install

### ISSUE THREAD

**Issue by mullernato** [opencart/opencart#10381]
Master Branch - 4.0.0.0_b

**Describe the bug**
How to create and install a theme in this "Master Branch (4.0.0.0_b)" version? 
I even tried, the installation worked but the theme did not load, even though I configured everything correctly in the admin panel! What is missing?
What would be the correct folder structure for the theme to load?
I am sending the theme attached to this message for structure analysis. 

**To Reproduce**
1. Install the created theme and enable
2. Configure on Store Settings

**Attached Theme**
[glad.ocmod.zip](https://github.com/opencart/opencart/files/7916466/glad.ocmod.zip)

**Comment by danielkerr** [comment]
use thenew startup table to include an event override for the template path
