### ISSUE TITLE
[master] Security process after new installation

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#10391]
**What version of OpenCart are you reporting this for?** master

**Describe the bug**
After installing OpenCart the Important Security Information occurs with the problems
a) It is not possible to change the path/name of the new destination folder
b) Rename the Admin folder is possible to change but it is not working

**Expected behavior**

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Web server
 - Operating system Linux
 - PHP version 8.0
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 96.0.1

**Additional context**

**Comment by mhcwebdesign** [comment]
Installing what Important Security Information? What exactly do you mean by this?

**Comment by pemaier** [comment]
If you login to the adminisration after the install process you'll see a POP-UP with the title Important Security Information.
Within this you get asked where to locate the storage (like in Version 3.x) and new you get asked for a new folder name for the folder admin.
I hope I could answer your question.

**Comment by mhcwebdesign** [comment]
Looks like a server-side folder access rights issue to me.

**Comment by pemaier** [comment]
Result after a new installing on a external standard web host:

a) **it is possible to move the folder in the given folders from the drop-down menu.**
It is not possible to change the path/folder name. So the situation occure that it is possible to install **only one secure OpenCart instance on one host profile** (mabee 2+ what depends how many subfolders are on the host path available)
Solution: make the path/folder name changeable like in Version 3 ( because that should be in the choise of the administrotor)
(my normal customers have minimum 2 opencart instances installed - a test/dev shop and a productive shop)

b) **no change** to the previous message
There is a new folder with the new name created and a file named config.php is getting created in the new folder but no more activity ... even after 10 minutes
