### ISSUE TITLE
[master] Additional store start with error message - Error in variable $products

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#10390]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
After call of the url there is only the following error message

Warning: Undefined variable $products in /home/localhost/public_html/opencart/master/extension/opencart/catalog/controller/module/featured.php on line 23Warning: foreach() argument must be of type array|object, null given in /home/localhost/public_html/opencart/master/extension/opencart/catalog/controller/module/featured.php on line 23TypeError: Opencart\Catalog\Model\Setting\Module::getModule(): Return value must be of type array, null returned in /home/localhost/public_html/opencart/master/catalog/model/setting/module.php on line 8

**To Reproduce**
1. Create an additional store
2. Open the new created store

**Expected behavior**
to see the header of an empty store

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? local
 - Operating system Linux
 - PHP version 8.0
 - Nginx version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 96.0.1

**Additional context**

**Comment by cgcmart** [comment]
Most product related opencart modules do not work, that is related to respectively control file and model/setting/module.php.
module settings mixed up in db oc_setting table and oc_module table.

**Comment by danielkerr** [comment]
alREADY FIX FEATURED PRODUCTS ISSUE
