### ISSUE TITLE
banner  input target not found

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10392]
<img src="{{ banner_image.thumb }}" alt="" title="" id="thumb-image-{{ image_row }}" data-oc-placeholder="{{ placeholder }}" class="card-img-top"/> <input type="hidden" name="banner_image[{{ language.language_id }}][{{ image_row }}][image]" value="{{ banner_image.image }}" id="input-banner-image-{{ language.language_id }}-{{ image_row }}-image"/>
                              <div class="card-body">
                                <button type="button" data-oc-toggle="image" data-oc-target="#input-banner-image-{{ language.language_id }}-{{ image_row }}-image" data-oc-thumb="#thumb-image-{{ image_row }}" class="btn btn-primary btn-sm btn-block"><i class="fas fa-pencil-alt"></i> {{ button_edit }}</button>
                                <button type="button" data-oc-toggle="clear" data-oc-target="#input-banner-image-{{ language.language_id }}-{{ image_row }}-image" data-oc-thumb="#thumb-image-{{ image_row }}" class="btn btn-warning btn-sm btn-block"><i class="fas fa-trash-alt"></i> {{ button_clear }}</button>
                              </div>

https://github.com/opencart/opencart/blob/6ff9d3fae4c676a6d747c3fb4eb1b32296d65400/upload/admin/view/template/design/banner_form.twig#L70

**Comment by danielkerr** [comment]
fixed a few weeks ago
