### ISSUE TITLE
[Master Branch] - default frequency should be added

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#10394]
https://github.com/opencart/opencart/commit/1b966b36ec7d0c4c96a8938f698914cc1134037e#diff-a53fa184b2d3611fba12fbd1b4415b5428091942fb1fdcea88422dbf0fc7fe3fR389

Should have a default language frequency key. Right now, it would be unpredictable to state during troubleshooting if the frequency is used by the core or from an extension. This should then be validated in an IF statement.

**Comment by TheCartpenter** [comment]
This line as well: ```$trial_frequency = $this->language->get('text_' . $result['trial_frequency']);``` .

**Comment by danielkerr** [comment]
i think fixed already
