### ISSUE TITLE
3.0.3.8  PHP 8.1 conversion of false to array in /catalog/controller/startup/startup.php

### ISSUE THREAD

**Issue by infografik** [opencart/opencart#10403]
Automatic conversion of false to array is deprecated in /var/www/clients/client15/web93/web/public/catalog/controller/startup/startup.php on line ~105 (Sorry, this is my line number after a few changes)
 
The error occurs only the first time you access the website (no cookies yet). 
For $this->session->data['language'] and below, $this->session->data['currency']

My solution:
`if(!is_array($this->session->data)){
	$this->session->data = [];
}`
before:
`if (!isset($this->session->data['language']) || $this->session->data['language'] != $code) {
	$this->session->data['language'] = $code;
}`

------------------------
 - Intranet server
 - Debian
 - PHP 8.1
 - Apache 2.4.25
 - Browser Firefox
 - Version 3.0.3.8

**Comment by TheCartpenter** [comment]
Even there with an !is_array could still encounter an error trigger.

```if (empty($this->session->data) || !is_array($this->session->data)) { $this->session->data = []; }```

but I doubt it would be the right location to lookup for the ```$this->session->data``` to avoid the reported error.

**Comment by TheCartpenter** [comment]
Also ensure that your session autostart is enabled.

In system/framework.php file, find:

```$session->start($session_id);```

add below:

```if (empty($session->data) || !is_array($session->data)) { $session->data = [] }```

See if that fixes the issue.

**Comment by infografik** [comment]
Session autostart is enabled.
My solution in startup.php works, and yours in framework.php, unfortunately, does not.

**Comment by TheCartpenter** [comment]
If that being the case, the right location needs to be used.

**Comment by TheCartpenter** [comment]
In this file should also work: https://github.com/opencart/opencart/blob/master/upload/catalog/controller/startup/session.php .

**Comment by infografik** [comment]
but no, sorry
$config->get('session_autostart') == false in //Session
if ($config->get('session_autostart')){
...
}

**Comment by infografik** [comment]
It promises to be very interesting when I see this startup/session.php, but I have v.3.0.3.8 with the ControllerStartupSession class, and unfortunately not the Session class :)

**Comment by ADDCreative** [comment]
https://github.com/opencart/opencart/blob/58e1d302e465df7215c4464d8e95f47edbc15682/upload/system/library/session/db.php#L21
Needs to be.
```php
return array();
````

This will then also match the change made to the master branch and:
https://github.com/opencart/opencart/blob/58e1d302e465df7215c4464d8e95f47edbc15682/upload/system/library/session/file.php#L22

**Comment by TheCartpenter** [comment]
For the master branch, it should be:

```return [];```

**Comment by mhcwebdesign** [comment]
We have fixed a number of issues to make the 3.0.x.x_Maintenance branch compatible with PHP 8.0 or 8.1, it's all on our forked repository at https://github.com/mhcwebdesign/opencart-php8/tree/3.0.x.x_Maintenance

If there are no further issues, and given enough interest, I could do a pull-request and have someone more experienced with github merge it into the maintenance branch here.

**Comment by ADDCreative** [comment]
@mhcwebdesign I think it will need doing otherwise the forums and GitHub issue tracker will just have the same questions posted again and again.

This is what I have so far. I can do pull request for any of them if needed.
https://github.com/ADDCreative/opencart/commits/php8

**Comment by mhcwebdesign** [comment]
@AddCreative: I'll take a look at yours. I can't see any changes on your OpenCart fork for the 3.0.x.x_Maintenance branch, I thought you had done some changes for this branch with regards to the strftime calls?

**Comment by ADDCreative** [comment]
@mhcwebdesign I create separate branches in order to be able to do pull requests. I've committed all the changes so for into the php8 branch.

**Comment by mhcwebdesign** [comment]
@AddCreative: I see. Would your changes work for the 3.0.x.x_Maintenance branch? Or would they be merged into the master branch?

Anyway, I just created a pull-request to make the 3.0.x.x_Maintenance branch compatible with PHP8.0 and PHP8.1. But this doesn't yet include your suggested changes to the strftime calls used by some of the OpenCart payment extensions!

I tested my changes for PHP 8.1, 8.0, and 7.4. I could merge my pull-request to the 3.0.x.x_Maintenance branch, Daniel gave me the necessary access right for doing merges or changes a while ago, but I'd like have some feedback and/or tests first from others before going ahead with this particular create of merge commit.

I assume the 3.0.x.x_Maintenance branch will eventually lead to tagged 3.0.3.9 release?

**Comment by ADDCreative** [comment]
@mhcwebdesign The changes are for the 3.0.x.x_Maintenance. I should've made that clearer. A lot are the same changes you have done, but in a slightly different way. Maybe more similar to the master.

I will have a look at the pull request and give some feedback.

I'm in the dark on how and who manages the 3.0.x.x_Maintenance branch.

**Comment by mhcwebdesign** [comment]
@ADDCreative : 

> I'm in the dark on how and who manages the 3.0.x.x_Maintenance branch.

I don't know either. Maybe Daniel can tell us? It would be good to have a stable 3.0.3.9 OC version as soon as possible because quite a few webhosts have now switched to newer PHP 8.x versions.

**Comment by danielkerr** [comment]
please open issue here:

https://github.com/opencart/opencart-3/issues
