### ISSUE TITLE
[master] Image manager - New folder get added only in image catalog start folder

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#10406]
**What version of OpenCart are you reporting this for?** master

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Create a new product.
goto tab Image and click edit
click on a folder to get in
click to create a new folder and write a name in the new form line then click add
A new folder is created in the previous folder with the name you typed in

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? web host
 - Operating system Linux
 - PHP version 8.0
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 69.0.1

**Additional context**
**Also the delete folder is not working!**

**Comment by eturerer** [comment]
https://github.com/opencart/opencart/issues/10302

**Comment by danielkerr** [comment]
closing because duplicate
