### ISSUE TITLE
Bugs in upload/admin/view/javascript/common.js

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10416]
**What version of OpenCart are you reporting this for?**
Master branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
upload/admin/view/javascript/common.js
(1) Line 84
`$('[data-bs-toggle=\'tooltip\']').each(function(i, element) {`

Error: Bootstrap doesn't allow more than one instance per element. Bound instance: bs.tooltip.

Change to
`$('[data-toggle=\'tooltip\']').each(function(i, element) {`

(2) Line 453
`+function($) {`

Error:  Missing name in function declaration.

Change to:
`(function($) {`

and wrap function declaration line 527 to
`})(window.jQuery);`

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
this as been fixed a while
