### ISSUE TITLE
[master] Filter not working

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#10415]
**What version of OpenCart are you reporting this for?** master

**Describe the bug**
After install and enabeling the filter module
then defining filters, categories, products, layouts 
the filter function is not working.

**Expected behavior**
A filter appears on the frontend.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? web host
 - Operating system Linux
 - PHP version 8.0
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 96.0.1

**Additional context**

**Comment by danielkerr** [comment]
it does work. but u have to enable it in extensions > modules 

u have to add it to categories u want it to appear in and also products. then go to design > layout and add filter module to which ever page u want it on. normally categories.
