### ISSUE TITLE
Products and totals are duplicatet

### ISSUE THREAD

**Issue by Bogs1989** [opencart/opencart#10424]
Hi. I use opencart 3.0.3.2 version  and I have a problem that I can't reproduce and I can't debug. 1 to a few dozen orders come with duplicate products and duplicate subtotals. These orders are placed without a user account, I have not detected so far the order placed as a user to have this problem. Any information can be useful to me ... I have attached a picture of the problem. Thanks in advance for any feedbackhank you

![bug](https://user-images.githubusercontent.com/72352256/153749865-dae8e570-c7b5-48f7-a2d7-9684e6726bb9.png)

**Comment by ADDCreative** [comment]
Ask on https://forum.opencart.com/ and provide a lot more details such as theme and extensions used.

**Comment by Bogs1989** [comment]
Default Theme , none extensions

**Comment by TheCartpenter** [comment]
Regardless. You are addressing an older OC version where the reliable problem might of been fixed on a more recent OC version already.
