### ISSUE TITLE
Uncaught TypeError: $(...).tabs is not a function

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10429]
https://github.com/opencart/opencart/blob/8b5137e9e196b6f5a350248ec31d384206f6714f/upload/extension/opencart/admin/view/template/module/html.twig#L70

**Comment by stalker780** [comment]
@danielkerr 
Daniel, this does not work. All multilanguage tabs in OC4 are broken now for many months.
`{% if languages.index == 0 %}`

it should be
`{% if loop.index == 1 %}`

https://github.com/opencart/opencart/issues/9848
