### ISSUE TITLE
Upgrade, sass.php errors

### ISSUE THREAD

**Issue by novakjosef1** [opencart/opencart#10420]
**What Hello,
I upgraded opencart 1.5.3 to 3.0.3.6. When the administration starts, we list these errors. Wouldn't anyone advise us what? 

Linux version :Debian 9.13
Chmod /var/www/html/admin/view/ to 777

Warning: fopen(/var/www/html/admin/view/stylesheet/bootstrap.css): failed to open stream: Permission denied in /var/www/html/admin/controller/startup/sass.php on line 19Warning: flock() expects parameter 1 to be resource, bool given in /var/www/html/admin/controller/startup/sass.php on line 21Warning: fwrite() expects parameter 1 to be resource, bool given in /var/www/html/admin/controller/startup/sass.php on line 23Warning: fflush() expects parameter 1 to be resource, bool given in /var/www/html/admin/controller/startup/sass.php on line 25Warning: flock() expects parameter 1 to be resource, bool given in /var/www/html/admin/controller/startup/sass.php on line 27Warning: fclose() expects parameter 1 to be resource, bool given in /var/www/html/admin/controller/startup/sass.php on line 29Warning: Use of undefined constant HTTPS_CATALOG - assumed 'HTTPS_CATALOG' (this will throw an Error in a future version of PHP) in /var/www/html/system/library/googleshopping/googleshopping.php on line 56

Website we write: Error: 
A theme has not been assigned to this store!

**Comment by mhcwebdesign** [comment]
Do a fresh install, upgrades in most cases don't work. If you need further help, re-post on the OpenCart forum.

**Comment by novakjosef1** [comment]
I installed a new version. I made a backup of the old version. Uploading to the new version cannot be done, this error is not compatible.
How to transfer data from old version to new one?

**Comment by osworx** [comment]
@novakjosef1 PLease use for such the OpenCart Forum: https://forum.opencart.com/
Just in short: when you have installed the new version (hopefully in a new directory and NOT copied over the old, original files!), you have to adopt the database tables to tnew scheme.
And add those reqorked data manually into the new database tables.
