### ISSUE TITLE
Opencart 3.0.2.0 and Klarna Checkout Confusion

### ISSUE THREAD

**Issue by ultrono** [opencart/opencart#10436]
Hi,

I'm running an Opencart 3.0.2.0 store. After a bit of research I can see the Klarna checkout files are still part of Opencart 3.0.2.0, but are semi disabled as to never display on the frontend.

Ref. issue #7081 I can see a mention that the Klarna extension has been released onto the Opencart marketplace. I can't see any Opencart created extensions (I may be missing something obvious). 

Ref. issue #6014 I can see a download was provided. The link unfortunately no longer works. 

I therefore have two questions.

Are the Klarna files within Opencart 3.0.2.0 valid?

What is the recommended method to integrate Klarna with Opencart 3.0.2.0.

Many Thanks

**Comment by ultrono** [comment]
Can anyone assist?

**Comment by MarvinKlein1508** [comment]
@ultrono there is an extra free extension which enabled Klarna/Sofort payments.
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=25699&filter_search=karley

**Comment by TheCartpenter** [comment]
It's been fixed on the opencarr-3 repository now.

**Comment by MuhamedAuda** [comment]
Hello, for opencart 3 Klarna have changed the API totally and default opencart not work !!
The only opencart extension in work here :
[](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=43318)

And docs and help here 
[](https://tapspeed.com/blog/opencart-klarna-checkout-api-v3.html)

**Comment by ultrono** [comment]
> 

Thank you, so much!
