### ISSUE TITLE
Google Base is deprecated?

### ISSUE THREAD

**Issue by GndZ3r0** [opencart/opencart#10439]
Excerpt from wikipedia:
> Google Base **_was_** a database provided by Google into which any user can add almost any type of content. As of September 2010, the product has been downgraded to Google Merchant Center... it was announced that **_Google Base's API is deprecated_** in favor of a set of new APIs known as Google Shopping APIs.

Is opencart still using google base? because according to opencart website https://www.opencart.com/index.php?route=cms/feature#tab-mobile

![opencart_googlebase](https://user-images.githubusercontent.com/19254282/155696981-ef066c54-020e-40bb-99e9-a330560b57f6.png)

**Comment by mhcwebdesign** [comment]
These are all removed in the upcoming OpenCart 4.
