### ISSUE TITLE
The uploaded file exceeds the 2Mmb max file size

### ISSUE THREAD

**Issue by superbobogithub** [opencart/opencart#10438]
I installed the latest opencart code, I encountered the same problem, the extension is a few kb size prompt Warning: The uploaded file exceeds the 2Mmb max file size!

version 4.0.0

PHP 8.0

**Comment by danielkerr** [comment]
will test before release.

**Comment by danielkerr** [comment]
ok fixed. if not check the upload max on settings page and increase it
