### ISSUE TITLE
SEO not working - TypeError in model seo_url.php

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10444]
https://github.com/opencart/opencart/blob/24273376c71ad8498e0aded785ed386c5dafafd2/upload/catalog/model/design/seo_url.php#L10

TypeError:  Opencart\Catalog\Model\Design\SeoUrl::getSeoUrlByKeyValue(): Argument #2 ($value) must be of type string, null given in

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart/commit/cff71bb0e8f8aa18bfc39746088016135accff68#diff-63ec18d41a843f6c9ed99b8043c976087464dd6c9bd4637a96e6086d74f9519bR38

has been changed to: LIKE but does not use: % .

**Comment by cgcmart** [comment]
I am waiting for authorized seo_url update complete, have not tested the update. Do you mean L126 and L132 `=` need to change to `LIKE`?

**Comment by TheCartpenter** [comment]
R38 in the URL means L38.

**Comment by cgcmart** [comment]
That is already updated. My question is whether it's applicable to L126 andL132

**Comment by TheCartpenter** [comment]
Applicable on L38.

**Comment by TheCartpenter** [comment]
Such as this change: https://github.com/opencart/opencart/commit/dc1e971539ad323269e18420ba4db3ca1cf2d395#diff-6bf9946bb8aefb6bbb29a3ed833261396d8814a3bd38463b43c17500e3e75761R5 . Not sure if the keyword and value both needs to contain a /% with LIKE or only one of them.
