### ISSUE TITLE
Session Not Expire After New Password Reset

### ISSUE THREAD

**Issue by selvarajRaja31082018** [opencart/opencart#10449]
What version of OpenCart are you reporting this for?

3.0.3.8

Describe the bug

Our VAPT Auditing Team found one more issue in Opencart3.0.3.8. Initially the user will login in a browser then the go with another browser and changed the password for his account. Again he come back to his first browser but the application doesn't ask new password.We need to get the new password from the user to login for different browsers. We need to resolve this issue kindly provide your support.

Local development
Operating system - linux
PHP version - 7.3.32
Apache version - 2.4.51 debian
Browser(s) tested with [e.g. chrome, safari - if applicable] - opera, chrome, edge

Thanks 

Selvaraj 
![image_2022_03_02T14_39_14_641Z](https://user-images.githubusercontent.com/46552995/156383466-86482008-0c89-4f1c-8bb4-cd4ce60e0f94.png)
![image_2022_03_02T14_37_22_607Z](https://user-images.githubusercontent.com/46552995/156383482-c9f0b9c5-a943-4925-9223-8d1c88a354ce.png)
![image_2022_03_02T14_38_56_341Z](https://user-images.githubusercontent.com/46552995/156383489-8ea2e880-aa4b-4d68-9e21-530998a77a76.png)

**Comment by mhcwebdesign** [comment]
Again, another wrong report! This not a security issue. After a login with a given web browser, the session lasts until logoff or session timeout. 

You are free to create github pull requests if you want to add improvements, but use some proper tools, not the VAPT.

**Comment by selvarajRaja31082018** [comment]
It is recommended to invalidate the session after the password reset or password
change.
