### ISSUE TITLE
opencart with postgresql

### ISSUE THREAD

**Issue by yozdas** [opencart/opencart#10443]
i am trying to install opencart with postgresql on ubuntu this is the error i get;

`Warning: pg_connect(): Unable to connect to PostgreSQL server: invalid connection option "hostname" in /var/www/html/opencart/upload/system/library/db/pgsql.php on line 12Warning: pg_connect(): Unable to connect to PostgreSQL server: invalid connection option "hostname" in /var/www/html/opencart/upload/system/library/db/pgsql.php on line 12TypeError: pg_query(): Argument #1 ($connection) must be of type resource, null given in /var/www/html/opencart/upload/system/library/db/pgsql.php on line 24`

System:
Ubuntu 20.04
Opencart 3.0.3.8
Nginx
Postgresql-13
php 8

**Comment by mhcwebdesign** [comment]
OC 3.0.3.8 does not support PHP 8. Please repost on the OC forum for support.
