### ISSUE TITLE
[master] Reverting telephone field as required

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#10441]
https://github.com/opencart/opencart/blob/24273376c71ad8498e0aded785ed386c5dafafd2/upload/catalog/view/template/account/register.twig#L46

Bad decision!
Why?
When this field is again required, European webshop owners get in troubles.
Because a telephone number IS private and nothing just to "share" because this value is requried.
The more, if a website intends to collect such data, it has to be very good argumented, e.g. required because of our delivery serice, or because my grandma may wants to call you once ..

This behaviour violates the GDPR!

Instead add a new setting to make it either required or optional.
As with so some other values in the store.

**Comment by TheCartpenter** [comment]
Custom field still won't show the billing / shipping information as private nevertheless.

**Comment by osworx** [comment]
@TheCartpenter telephone field is okay, but only when able to disable or hide or make as required per setting in the system.

I have read all the other comments about Daniels decision disabling the telephone.
As it seems, all of them do not know the current regulations - worldwide.
And having such as a "custom field" is also useless - would produce too many "bug reports" from the noobs!

**Comment by mhcwebdesign** [comment]
Just make it an optional field, that is, not required?

**Comment by osworx** [comment]
@mhcwebdesign Some shops need it (e,g, for depending processes like delivery, call back if custom products).
Some shops want it - for whatver reason ..
And many shops do not need it.

So, we have 3 options finally:

1. required
2. optional (normal or required)
3. required in any case

When we read current regulations, a personal telephone is personal and private.
Therefore, if a shop needs that value, it must be described why and the reasons behind.
If these reasons are not valid, a penalty payment will happen - as seeing currently at many German shops (as it seems their laywer mafia needs money ..)

Currently for all these shop, an additional extension must be installed.
But it should be integrated as standard desicion.

**Comment by mhcwebdesign** [comment]
@osworx: Would you be able to create a pull request for this, for Daniel to look at?

**Comment by TheCartpenter** [comment]
@osworx: While I do agree about the telephone field that should not be a custom field due to regular expression lookups since multiple OC releases had to be reviewed about this, based on the CCPA / CCRA / GDPR regulations, the field should not be optional but rather based on the specific payment / shipping service providers being used since even by enabling / disabling the telephone field in this scenario, store owners would still have to re-enable this field based on the checkout form or while using the APII as a requirement.

**Comment by TheCartpenter** [comment]
With custom themes by editing checkout.twig file, this could be accomplished.

**Comment by osworx** [comment]
> With custom themes by editing checkout.twig file, this could be accomplished.

It's not only the template, think also about the check inside the controllers!

**Comment by osworx** [comment]
> @osworx: Would you be able to create a pull request for this, for Daniel to look at?

As soon as I will have more time, I will do.

**Comment by TheCartpenter** [comment]
> > With custom themes by editing checkout.twig file, this could be accomplished.
> 
> It's not only the template, think also about the check inside the controllers!

Yes, with Events.

**Comment by osworx** [comment]
> > > With custom themes by editing checkout.twig file, this could be accomplished.
> > 
> > 
> > It's not only the template, think also about the check inside the controllers!
> 
> Yes, with Events.

Why with events when it can be done by a simple definiton in the store settings .. ?
1. new value has to added to the settinsg template
2. new value has to be check in several backend and frontend controllers
3. new value state has to be checked in several backend and frontend templates

When all this is in the core, no additional events or hacks are required.

**Comment by TheCartpenter** [comment]
> > > > With custom themes by editing checkout.twig file, this could be accomplished.
> > > 
> > > 
> > > It's not only the template, think also about the check inside the controllers!
> > 
> > 
> > Yes, with Events.
> 
> Why with events when it can be done by a simple definiton in the store settings .. ?
> 
> 1. new value has to added to the settinsg template
> 2. new value has to be check in several backend and frontend controllers
> 3. new value state has to be checked in several backend and frontend templates
> 
> When all this is in the core, no additional events or hacks are required.

That would be another way but simply considering a longer road to get there, since setting a new store value will still only allow a store owner to load a single custom theme at a time as it would be more restrictive to modify several files in the backend and frontend as opposed to the use of Event triggers which the admin orders and checkout page are already linked to when needed whereas the use of Event triggers would simply require a simple if validation with the associative template as per the selected payment / shipping extension that could load the reliable billing and shipping details afterwards regardless if these forms would originate from the admin orders or from the checkout page.

**Comment by osworx** [comment]
> That would be another way but simply considering a longer road to get there, since setting a new store value will still only allow a store owner to load a single custom theme at a time as it would be more restrictive to modify several files in the backend and frontend as opposed to the use of Event ...

Theme/Template developeros have to follow the core - not the opposite.
Same as prices: logged in or not -just a simple setting.

Maybe there are more settings/values which should be defined via the shop configutation.
Like the default order in all list in the frontend.
Just think about that.

**Comment by TheCartpenter** [comment]
It's already been thought. While I do agree that users needs to follow the core, not the other way around. Sources who established regulations regarding data confidentiality, as you addressed, is also where it won't seem to maintain their tracks as long as the core won't deliver the needs as per the providers' needs. As for the prices, customer groups are already defined in each stores which means the admin catalog products can already manage several types of prices based on customer groups fortunately. Therefore, this shouldn't be much of a problem on that side.

In addition, payment extensions like PayPal, and similar, are also redirecting users outside the site where the transactions might already been cancelled prior to return to the checkout page without store owners' realizing those events. By prioritizing by payment / shipping extension options, after selecting the guest or customer's account option, this prioritization could also help to identify which transaction has been cancelled before the orders gets created by guests / customers regardless of prices that's been initiated from the stores.

**Comment by osworx** [comment]
@TheCartpenter I meant the store setting "Display prices incl. VAT" or "Allow Reviews" and so on .. TAB Options in the store settings.

So I see really no reason, why there should be more to "fine tune" instead of letting users "fiddeling" around on the scripts, editing templates or creating events .. 
And finally see them in the forum again and crying for help bevause they did something wrong.

Instead having such values defineable per "mouse click", I am sure everybody will be satisfied - and can tune his store as he need/want it.

**Comment by TheCartpenter** [comment]
While users already can, then it ain't hard to figure that if everybody will be satisfied, then at this point of time there ain't any issues with GDPR on these forms.

**Comment by danielkerr** [comment]
ill add a setting in config to for display and required for telephone field

**Comment by osworx** [comment]
> By doing that, it will affect all payment and shipping details where payment and service providers may either or not require this field since a single change from each stores could affect the entire telephone field.

If (and only then IF) any payment or shipping extension will need the telephone number (and I do not know any), the telephone number can be "collected".
But, this has to be stated public (e.g. in the "Privacy Statement") and clear why this private and personal data is required.

I see no reason for any payment provider to become telephone numbers (and I don't know one).
Shipping couriers may need them, but only "may".

Adding such advices into the help field at this setting, will help store owners to find their right decision.

@danielkerr Thank you.

**Comment by TheCartpenter** [comment]
It's your show but as stated on my previous reply, these restrictions not only needs to be validated with the payment service providers but also with shipping and can become quite competitive on that and not only specifically on the telephone field but can also request other billing and shipping details once connected to their APIs.

**Comment by TheCartpenter** [comment]
That simply requires some travel around, taking the time to look into API documentations once in a while.. There are many modifications that can be opted by payment and shipping services within one year. Some might not be up-to-date unfortunately and even on the OC forum, we're constantly getting posts about extensions where it used to work but may no longer work for multiple reasons but one of them is service change.

**Comment by TheCartpenter** [comment]
An alternative would be to create a compliance group with the information page where the OC admin setting form can validate by group rather than GDPR only.

**Comment by osworx** [comment]
@TheCartpenter sorry, but what is CCRA ?
Whenever possible. post also a link (because in this case this abbreviation can be more than one ..)

**Comment by TheCartpenter** [comment]
By all means: https://pro.bloomberglaw.com/brief/the-far-reaching-implications-of-the-california-consumer-privacy-act-ccpa/#:~:text=The%20California%20Privacy%20Rights%20Act%20(CPRA)%2C%20also%20known%20as,to%20as%20%E2%80%9CCCPA%202.0.%E2%80%9D .

Howeer, it is 'CPRA', not 'CCRA'. Typo.

**Comment by TheCartpenter** [comment]
As it was already addressed on the OC forum: https://forum.opencart.com/viewtopic.php?t=222491 .

**Comment by osworx** [comment]
@TheCartpenter That's why I wrote. post always a link!
CPRA > California Privacy Rights Act, an extension of CCPA 
https://en.wikipedia.org/wiki/California_Privacy_Rights_Act

Covers 
California CCPA | CPRA
Colorado CPA
Virginia VCDPA

A good comparison is: https://pro.bloomberglaw.com/brief/data-privacy-laws-in-the-u-s/

**Comment by TheCartpenter** [comment]
I thought you already knew about the extended law. Take note, however, that since the financial institutions currencies from the US can also be used in Canada, then Canada is also implicit with these laws with E-Commerce since the payment service providers in the country also included these laws over email and from their websites regarding the terms and conditions of these laws.

**Comment by osworx** [comment]
I cannot know all - and read everything ;)
No, I was aware of this "extension" - thanks for informing me (and others).
And links to all are good in case someone else may read these comments.

p.s.: my "main goal" is Europe - and they have laws more than I want or need.

**Comment by TheCartpenter** [comment]
No worries. Politically, Canada has been allied with Europe since almost two months now in the meantime. Which is why, I believe that subsets of political groups should be added in OC in order to better inform customers prior to complete checkout. I thought perhaps on adding thumbnails with each links from the above lists but the problem would be with the site redirection from the payment service providers like PayPal and a few others with their token strings.

May be to move the terms and conditions to the upper location during checkout?

**Comment by TheCartpenter** [comment]
https://stripe.com/docs/payments/checkout/phone-numbers

**Comment by osworx** [comment]
Quote from their website: 

> You can enable phone number collection in Checkout if you need to collect a phone number for shipping or invoicing.

Means, IF it is required, it can be collected (and this has to be stated clearly in the "Privacy Statement" > why and who is receiving it for which purpose).

I have made several plugins for PayPal (and other payment providers).
None of them ever requested (and required) a telephone number.

So Daniels commit goes the correct direction, IF someone needs it, he can enable it via the system settings.
It's with everything, store owners (and operators) have to read prior they are starting their business.
With this commit we give all the option to set it as required - or not.

**Comment by TheCartpenter** [comment]
What will also happen is when other payment service providers will be enlisted during checkout and won't require a phone number, store owners will have to make each adjustments for each customers where a payment service provider will have this option set to enabled by store owners. Therefore, the store owners' services will be affected before customers can complete their checkout transactions unless store owners do like to switch their phone number settings in accordance of the customers' selection (which I seriously doubt in this case).

**Comment by osworx** [comment]
You have hightlighted only Stripe - and they say, it's **optional**.

And I wrote (from my experience the last 12 years) that no payment provider really need it (as required).
Possible that some shipping couriers want it, but this can be only an option - none of them ever had the need to call me (and to be true, they have not the time to make a call).

Daniels commit has all options: enable/disable this field, make it required or not.

But it's the same with the birthdate: this can be a fields some payment providers really need to evaluate the trustness of the customer (in case for example when an option to pay per "Credit" is given and selected).

Those extensions have to offer automatically that field - or they are not worth to use in a webstore!
In such cases the store owners would have the need to create a ** Custom Field** which value has to be submitted with that request - but that requries some extra coding.

So, I would say, whenever an payment or shipping extension may require the telephone field, the extension developer has to add it in his extension.
Basically a simple task ..

**Comment by TheCartpenter** [comment]
Yes, other fields can also be amended as a mandatory field and not only the telephone field which is why restricting one field throughout the entire store versus a payment extension can involve on-demand orders to be created and is not the goal to start a store.

```So, I would say, whenever an payment or shipping extension may require the telephone field, the extension developer has to add it in his extension.
Basically a simple task ..```

That couldn't be more true; it is indeed a simple task. Which is why, any fields that are mandatory by each payment and shipping service providers could already be adjusted by extension developers rather than store owners' having to set a yes or no option from a specific field that could affect his entire service, including extensions being offered from the Marketplace whereas billing / shipping details information are already restricting those fields. From there, it is to reflect on how many extensions a single globalized restriction could affect each extensions at this point.

**Comment by TheCartpenter** [comment]
My latest reply above is beside the point of GDPR. It is by design.

**Comment by osworx** [comment]
@TheCartpenter I really do understand your intention.
But I think we should discuss that not at this place here - it's only for developers finally.

In general: it's a **shame** to have an eye on all regulations, restrictions and laws before opening a Webstore.

Finally the **victim** is always the proper store owner who wants to sell only a few products "over the web".
And is completely concerned, that the letter from a lawyer is arriving with at least a fine minimum of 1.200,- Euro (payable within 7 days!).
That's the daily and current reality in Germany!

`Called the **Abzockermafia** - lawyers only targeting webstores (from small to big and bigger) to get some money!`

**Comment by TheCartpenter** [comment]
This section is the right section to talk about it, since the request you have convinced a creator to do is within this section and must be rectified.

**Comment by osworx** [comment]
Okay, I've said all what to say.

**Comment by TheCartpenter** [comment]
This GDPR form is appliable from Canada (not sure, yet, originating from the US): https://gdpr-info.eu/chapter-3/ .
