### ISSUE TITLE
Application transmitting  admin panel Session Token through URL

### ISSUE THREAD

**Issue by selvarajRaja31082018** [opencart/opencart#10446]
What version of OpenCart are you reporting this for?

3.0.3.8

Describe the bug
During the period of vulnerability cross checking by the VAPT Auditing Team they found a issue in Opencart3.0.3.8. In the current scenario the Token value are passed in the URL from the admin panel. Shared token value in the url is reported as vulnerability in our application .So we should need to find some other methods or techniques to pass the token values. Kindly provide your support to resolve this issue in a safest and better way.

Server / Test environment (please complete the following information):

Local development
Operating system - linux
PHP version - 7.3.32
Apache version - 2.4.51 debian
Browser(s) tested with [e.g. chrome, safari - if applicable] - opera, chrome, edge
![adminurl (1)](https://user-images.githubusercontent.com/46552995/156107680-7a1312a3-90fa-4a5a-baa0-a39406466df1.png)

**Comment by TheCartpenter** [comment]
```Shared token value in the url is reported as vulnerability in our application```

Since it's in your application and that no details are provided about it, please post on the OC forum > security server section of the forum prior knowing if the actual issue you are reporting shall be addressed as a bug in regards of the admin user token.

**Comment by TheCartpenter** [comment]
In addition, you are also using an older PHP version; 7.3.32 release.

**Comment by mhcwebdesign** [comment]
Short of rewriting the whole OpenCart admin backend there is nothing that can be done here. Besides, the audit report is wrong, it's not a security issue. The 'user_token' in the query string is only used during an admin session. If you copied the URL and opened it in another browser, or elsewhere, it would only result in the admin login page. 

Besides, it's always a good practice to limit the admin backend to only certain IP-addreses anyway via the '.htaccess'. 

In summary: There are other more important issues to be addressed, this isn't one of them.

You are welcome to re-post on the OpenCart forum in order for others to help you make your site more secure.

Or do a proper pull-request here on github if you think you have a better solution.
