### ISSUE TITLE
Problem description too vague. Don't use VAPT which is known for reporting false positives.

### ISSUE THREAD

**Issue by selvarajRaja31082018** [opencart/opencart#10454]
Problem description too vague. Don't use VAPT which is known for reporting false positives.

_Originally posted by @mhcwebdesign in https://github.com/opencart/opencart/issues/10451#issuecomment-1057884794_

Please  Provide details description

**Comment by osworx** [comment]
@selvarajRaja31082018 You must have too much time .. ?!
Read the comments given by other users carefully and stop reporting nonsens again and again!
