### ISSUE TITLE
Cookie Path Attribute Set to Root 

### ISSUE THREAD

**Issue by selvarajRaja31082018** [opencart/opencart#10451]
Cookie Path Attribute Set to Root 

What version of OpenCart are you reporting this for?

3.0.3.8

Describe the bug

We need to set the Cookies in the path attribute but in our Opencart Application currently we are getting from the empty source. But we need to get this Cookies from the domain url. We are doing  this action based upon the security auditing purpose so we need to get the better solution as soon as possible.

Local development
Operating system - linux
PHP version - 7.3.32
Apache version - 2.4.51 debian
Browser(s) tested with [e.g. chrome, safari - if applicable] - opera, chrome, edge

Thanks

Selvaraj
![cookies](https://user-images.githubusercontent.com/46552995/156536537-c7e89cf3-1b10-42e8-a02d-5972479b3a2b.png)

**Comment by mhcwebdesign** [comment]
Problem description too vague. Don't use VAPT which is known for reporting false positives.

**Comment by ADDCreative** [comment]
@selvarajRaja31082018 Your screenshot shows that your website is in the root directory. So a path of / is entirely correct.
