### ISSUE TITLE
@selvarajRaja31082018 Your screenshot shows that your website is in the root directory. So a path of / is entirely correct.

### ISSUE THREAD

**Issue by selvarajRaja31082018** [opencart/opencart#10456]
@selvarajRaja31082018 Your screenshot shows that your website is in the root directory. So a path of / is entirely correct.
The Path attribute plays a major role in setting the scope of the cookies in conjunction 
with the domain. In addition to the domain, the URL path that the cookie is valid for can 
be specified. If the domain and path match, then the cookie will be sent in the request. 
Just as with the domain attribute, if the path attribute is set too loosely.
_Originally posted by @ADDCreative in https://github.com/opencart/opencart/issues/10451#issuecomment-1057937826_

**Comment by ADDCreative** [comment]
Please think of other users and stop spamming the issue tracker. Please post on https://forum.opencart.com/ if you need help.

**Comment by osworx** [comment]
Could someone responsible here stop that spammer and ban?

**Comment by mhcwebdesign** [comment]
@osworx: I'll keep closing his issues!

**Comment by osworx** [comment]
As it seems, he is very persistent ..
