### ISSUE TITLE
Corrupted github resporitory for the 3.0.3.x releases

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#10462]
It appears the following folders shouldn't be empty:

system/storage/vendor/braintree/braintree_php
system/storage/vendor/cardinity/cardinity-sdk-php 
system/storage/vendor/divido/divido-php
system/storage/vendor/guzzlehttp/*
system/storage/vendor/klarna/kco_rest
system/storage/vendor/psr/log
system/storage/vendor/react/promise
system/storage/vendor/scssphp/scssphp
system/storage/vendor/symfony/polyfill-mbstring
system/storage/vendor/symfony/translation
system/storage/vendor/symfony/validator
system/storage/vendor/zoujingli/wechat-php-sdk

For example, for OpenCart 3.0.3.8 above folders have missing files and sub-folders from this download:
https://github.com/opencart/opencart/archive/refs/tags/3.0.3.8.zip

But these downloads appear to be OK:
https://github.com/opencart/opencart/releases/tag/3.0.3.8
https://www.opencart.com/index.php?route=cms/download/download&download_id=64

**Comment by ADDCreative** [comment]
I believe the tags are not meant to have the vendor files. They are source code so require `composer install` to be run. The issue may be that the vendor directory has not been added to .gitignore. So GitHub picks them up as submodules.

https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

**Comment by mhcwebdesign** [comment]
@ADDCreative : In that case a cleaner solution would be perhaps to always exclude 'system/storage/vendor' folder via a '.gitignore' and then let the OpenCart installer generate the vendor folder, by calling composer? Better than having a half-finished vendor folder in github.

**Comment by TheCartpenter** [comment]
By adding the vendor folder in the .gtignore, it would also ignore the integrated PayPal Braintree extension payment and module.

**Comment by ADDCreative** [comment]
@mhcwebdesign Actually I don't think the master has the same issue so it may just be a case of removing the vendor folder from Git and then committing again.

**Comment by ADDCreative** [comment]
@mhcwebdesign I think you can also delete the vendor folder, comit. Change twig version in composer.json. `composer install` and commit again.

**Comment by TheCartpenter** [comment]
$GLOBALS?

https://github.com/opencart/opencart/pull/10461/commits/d227aa5c1568bcabcff40613ff2c6611065532ee#diff-be26f62a61bac95439cb44f898590f44e561fa36ad72ae29da31f5163799cedaR15

**Comment by ADDCreative** [comment]
@mhcwebdesign Seems to have sorted the vendors folder issue.

Just a quick question. Which issue required this __isset? I did notice anything in my testing, but I could've missed it.
https://github.com/opencart/opencart/pull/10467/commits/2b2b7581f9af1ea7ec10f75c2d35277095c5c774#diff-84cad895fb31f36198eebbfaf829456e1a16850038b9a4b31fd92e224db82ce0

**Comment by TheCartpenter** [comment]
__isset could also be added into the system/engine/loader.php file so that the registry could auto-initialize this method.

**Comment by TheCartpenter** [comment]
As an alternative, to create a new controller inside the startup folder and add it into the system/config/admin.php and system/config/catalog.php files.
