### ISSUE TITLE
PHP Warning:  Undefined array key 1 in catalog/controller/startup/seo_url.php

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10463]
https://github.com/opencart/opencart/blob/3dbd6c09bd5ee3e68198e234ece42591c174a8c3/upload/catalog/controller/startup/seo_url.php#L60

**Comment by danielkerr** [comment]
what page,  what url? sick of guessing games. dont post unless u provide more information!

**Comment by jojishi404** [comment]
The error was caused by quotation marks contained in Meta-tag Keyword and Product tag fields in products. There is a point in filtering "problematic" symbols. I hope this helps

**Comment by danielkerr** [comment]
Quotation marks should not be possible as there is a regex filter to block quotation marks being used

**Comment by mhcwebdesign** [comment]
Don't use quotation marks in meta tags or meta keywords. The Export/Import tool may not complain about it, but it will have the potential to mess things up later.
