### ISSUE TITLE
[master] typo in extension/opencart/catalog/model/payment/..

### ISSUE THREAD

**Issue by yvonn** [opencart/opencart#10474]
In master in several payment files I see `hasRecuirring` is that correct? Maybe it should be `hasRecurring`

extension/opencart/catalog/model/payment/bank_transfer.php (line 9)
extension/opencart/catalog/model/payment/cheque.php (line 9)
extension/opencart/catalog/model/payment/cod.php (line 9)
extension/opencart/catalog/model/payment/bank_transfer.php (line 19)

**Comment by TheCartpenter** [comment]
Already pulled request.

**Comment by danielkerr** [comment]
all changed to hasSubscription last month
