### ISSUE TITLE
Affiliate Automatic Commission bug

### ISSUE THREAD

**Issue by tktamas** [opencart/opencart#10487]
Affiliate commission also happens when the order status changes to processing, not only when it changes
My recommended solution is:

catalog/model/checkout/order.php

`// If current order status is not processing or complete but new status is processing or complete then commence completing the order
			if (!in_array($order_info['order_status_id'], array_merge($this->config->get('config_processing_status'), $this->config->get('config_complete_status'))) && in_array($order_status_id, array_merge($this->config->get('config_processing_status'), $this->config->get('config_complete_status')))) {
...

// Add commission if sale is linked to affiliate referral.
				/* DISABLED
				if ($order_info['affiliate_id'] && $this->config->get('config_affiliate_auto')) {
					$this->load->model('account/customer');

					if (!$this->model_account_customer->getTotalTransactionsByOrderId($order_id)) {
						$this->model_account_customer->addTransaction($order_info['affiliate_id'], $this->language->get('text_order_id') . ' #' . $order_id, $order_info['commission'], $order_id);
					}
				}*/
			}

			// If current order status is not complete but new status is complete then add commission to the order: New section
			if (!in_array($order_info['order_status_id'], $this->config->get('config_complete_status')) && in_array($order_status_id, $this->config->get('config_complete_status'))) {
				
				// Add commission if sale is linked to affiliate referral.
				if ($order_info['affiliate_id'] && $this->config->get('config_affiliate_auto')) {
					$this->load->model('account/customer');

					if (!$this->model_account_customer->getTotalTransactionsByOrderId($order_id)) {
						$this->model_account_customer->addTransaction($order_info['affiliate_id'], $this->language->get('text_order_id') . ' #' . $order_id, $order_info['commission'], $order_id);
					}
				}
			}				
`

**Comment by TheCartpenter** [comment]
Not sure how this part really shows a solution to this problem ...

**Comment by tktamas** [comment]
I disabled the add commission in this section: // If current order status is not processing or complete but new status is processing or complete then commence completing the order

And add it to a new: 
// If current order status is not complete but new status is complete then add commission to the order

**Comment by tktamas** [comment]
[order_220318.php.txt](https://github.com/opencart/opencart/files/8307069/order_220318.php.txt)
