### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by sansal54** [opencart/opencart#10480]
I installed So Ladaz template. It works. But when I navigate to other pages, I get 
**Notice: A non well formed numeric value encountered in /var/www/html/opencart/system/helper/utf8.php on line 21Notice: A non well formed numeric value encountered in /var/www/html/opencart/system/helper/utf8.php on line 21**
at the top of page.
When I look inside this file , I see

```
	function utf8_substr($string, $offset, $length = null) {
		if ($length === null) {
			return mb_substr($string, $offset, utf8_strlen($string));
		} else {
			return mb_substr($string, $offset, $length);
		}
	}
```
Here, Line 21 is **"return mb_substr($string, $offset, $length);"** 

I dont have PHP knowledge and so I dont know how to fix this.

PHP 7.0.33-0ubuntu0.16.04.16
OpenCart 3.0.2.0

**Comment by mhcwebdesign** [comment]
This is not an OpenCart bug. Please repost on the OpenCart forum, or contact the theme author. Also, might be good to upgrade your PHP to 7.4.
