### ISSUE TITLE
BuG BountY Progam?

### ISSUE THREAD

**Issue by lsdeep** [opencart/opencart#10494]
need to ask is there any bug bounty program?

**Comment by mhcwebdesign** [comment]
No.

**Comment by lsdeep** [comment]
Why I think it's good for you and customers, script become more secure many people will share good experience.! 

Now i have vulnerability how i can contact with support?

**Comment by ADDCreative** [comment]
@lsdeep It's in the readme.
https://github.com/opencart/opencart/blob/1782b111556e3d249d032b31bfaa4a481070c663/README.md?plain=1#L35
