### ISSUE TITLE
Input fields are not sanitized

### ISSUE THREAD

**Issue by Gadalla** [opencart/opencart#10495]
OC Input fields are not sanitized and protected from  SQLi Attacks (SQL Injections), and XSS Vulnerabilities. This is consider a high risk alert.

**Comment by mhcwebdesign** [comment]
Please provide specific details and an example. Otherwise we'll have to close this issue.

**Comment by Gadalla** [comment]
One of the techniques hackers use is called SQL Injection. They enter codes (XSS Vulnerabilities) or special characters in the input fields in OpenCart to retrieve DB sensitive info and tables. I can tell that 90% of OC hacks are done using SQL Injection. "Input Sanitization" is a technique used programmatically to protect against this attack. And the header communications between the server and the browser reveals the table columns even when SEO URLs is checked in the settings. Watch the below.

[https://www.youtube.com/watch?v=oa_aoFPmCNo](url)

OpenCart is a great free e-commerce script that is gaining popularity. A "Security" tab in the left menu is required were various security checks and suggestions are perfumed to protect the store, specially file permissions. This tab must develop from time to time along the OC development since new vulnerabilities in JS, PHP functions, web browsers, etc are found.

The below will explain more. Thanks
[https://www.getastra.com/blog/cms/opencart-security/how-to-prevent-sql-injection-sqli-in-opencart-1-5-x-2-x/](url)
[https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=41490](url)

**Comment by mhcwebdesign** [comment]
You have not provided a single specific example. Just making general assumptions here isn't good enough. OpenCart is well protected against SQL injections, has been for years.

We'll close this issue.
