### ISSUE TITLE
worldmap zoom in/out buttons display issue

### ISSUE THREAD

**Issue by CR1571** [opencart/opencart#10499]
![download](https://user-images.githubusercontent.com/98699792/160129836-aae8b488-9a6f-44d9-bcce-fd834327375f.png)

**Comment by mhcwebdesign** [comment]
Lack of details, please repost on OpenCart forum with sufficient details, incl. OC version used.

**Comment by CR1571** [comment]
Latest OC Version 4.0.0.0_b

**Comment by mhcwebdesign** [comment]
OK, we'll leave that for Daniel to pick up, OC 4 is still work in progress anyway.

**Comment by CR1571** [comment]
I was just trying to help in pointing bugs as I am testing the OC master branch.

**Comment by mhcwebdesign** [comment]
OK, thanks.

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/pull/10893
