### ISSUE TITLE
TypeError: explode(): Argument #2 ($string) must be of type string, array given in 

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10578]
$shipping = explode('.', $this->session->data['shipping_method']['code']);

https://github.com/opencart/opencart/blob/9e235b6501a2f76e4bcee3ba752a200b7429505b/upload/catalog/controller/checkout/payment_method.php#L44

**Comment by danielkerr** [comment]
$shipping = explode('.', $this->session->data['shipping_method'])

is correct
