### ISSUE TITLE
Recurring profiles cause payment options to not load

### ISSUE THREAD

**Issue by johnmanko** [opencart/opencart#1059]
I added a product with two profiles: 4.95/monthly and 48/yearly.  

During checkout, no payments are available, with a message of "Warning: No Payment options are available. Please contact us for assistance!" 

When I remove the profiles from the product, the payments options show.

I'm using the Authorize.net (AIM) and Check modules.  OpenCart v1.5.6.

**Comment by pattyland** [comment]
"More are being added for 2.0"

any news here @jamesallsup?

**Comment by ModchipMan** [comment]
Warning: No Payment options are available. Please contact us for assistance!
as soon as I set up recurring payment on any product, remove recurring payment and checkout process works fine, any help would be great

**Comment by periyasamy25** [comment]
How to make my custom payment gateway to support recurring payment?

**Comment by nikhilchandran** [comment]
How to make my custom payment gateway to support recurring payment?

**Comment by vaguemind** [comment]
How can i enable COD as a payment gateway to support recurring payment in opencart 3 ?? please can someone help me urgently ?
thanks
