### ISSUE TITLE
repeated opencart queries oc_seo_url

### ISSUE THREAD

**Issue by yusufcan321** [opencart/opencart#10616]
https://prnt.sc/BzKdBm9niETY 

here oc_seo_url also throws a lot of duplicate queries and I couldn't find how to fix these queries.

**Comment by TheCartpenter** [comment]
Which branch are you reporting this issue about?

**Comment by yusufcan321** [comment]
what does the branch mean ?

**Comment by TheCartpenter** [comment]
Are you posting regarding the master branch or about the maintenance branch?

**Comment by yusufcan321** [comment]
regarding the main branch , I am using version 3.0.3.6. my php version is 7.3.3

**Comment by TheCartpenter** [comment]
According to your screenshot, each product IDs are not repeated. They are unique. Unless there's already a commit posted about it or an issue you could demonstrate compared to the maintenance or the master branch, please post on the OC forum.

**Comment by mhcwebdesign** [comment]
Your screenshot doesn't show duplicate queries, it show oc_seo_url queries for different products.
If you experience issues, please post on the OC forum, with more details.
