### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by elitecgh** [opencart/opencart#10825]
**What version of OpenCart are you reporting this for?**
  Version 3.0.3.2
**Describe the bug**

Fatal error: Uncaught Exception: Error: Could not load model extension/total/shipping! in /home/ghanrphn/ghana99/storage/modification/system/engine/loader.php:89 Stack trace: #0 /home/ghanrphn/ghana99/storage/modification/catalog/controller/common/cart.php(34): Loader->model('extension/total...') #1 /home/ghanrphn/ghana99/storage/modification/system/engine/action.php(79): ControllerCommonCart->index(Array) #2 /home/ghanrphn/ghana99/storage/modification/system/engine/loader.php(48): Action->execute(Object(Registry), Array) #3 /home/ghanrphn/ghana99/storage/modification/catalog/controller/common/header.php(213): Loader->controller('common/cart') #4 /home/ghanrphn/ghana99/storage/modification/system/engine/action.php(79): ControllerCommonHeader->index(Array) #5 /home/ghanrphn/ghana99/storage/modification/system/engine/loader.php(48): Action->execute(Object(Registry), Array) #6 /home/ghanrphn/ghana99.com/catalog/controller/common/home.php(17): Loader->controller('common/header') #7 /home/ghanrphn/ghana99/storage/modification/ in /home/ghanrphn/ghana99/storage/modification/system/engine/loader.php on line 89
What section does it affect?
Frontend
**To Reproduce**
1. Go to 'https://www.ghana99.com'

**Expected behavior**
I wanted to visit the website

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 web server
 - Operating system
 windows 11
 - PHP version
 PHP version:7.3.33
 - Apache version
 Apache version 2.4.53
 - Browser(s) tested with [e.g. chrome, safari - if applicable]
 Chrome
94.0 (build 23)
**Additional context**

**Comment by ADDCreative** [comment]
Your catalog/model/extension/total/shipping.php is probably missing. Ask on https://forum.opencart.com/ for help.
