### ISSUE TITLE
Too much errors occured in PHP 8.1.4 when installing and after that. 

### ISSUE THREAD

**Issue by richfuns** [opencart/opencart#10826]
**What version of OpenCart are you reporting this for?** 

v3.0.3.8 

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

**To Reproduce**
1. Go to installation page
2. See error
![Snipaste_2022-05-04_21-17-50](https://user-images.githubusercontent.com/1400999/166856100-b925fcdf-ec76-4fd1-a323-63196327f6a0.png)

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.

![Snipaste_2022-05-04_21-21-29](https://user-images.githubusercontent.com/1400999/166856164-7020d8db-8e93-4362-88d0-0f28f0aa91b0.png)

`Unknown: mysqli::real_escape_string(): Passing null to parameter #1 ($string) of type string is deprecated in D:\env\qampp\htdocs\opencart\system\library\db\mysqli.php on line 53Unknown: Return type of Twig\Node\Node::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\env\qampp\storage\vendor\twig\twig\src\Node\Node.php on line 161Unknown: Return type of Twig\Node\Node::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\env\qampp\storage\vendor\twig\twig\src\Node\Node.php on line 166Unknown: round(): Passing null to parameter #1 ($num) of type int|float is deprecated in D:\env\qampp\htdocs\opencart\catalog\model\catalog\product.php on line 45Unknown: round(): Passing null to parameter #1 ($num) of type int|float is deprecated in D:\env\qampp\htdocs\opencart\catalog\model\catalog\product.php on line 45Unknown: round(): Passing null to parameter #1 ($num) of type int|float is deprecated in D:\env\qampp\htdocs\opencart\catalog\model\catalog\product.php on line 45Unknown: round(): Passing null to parameter #1 ($num) of type int|float is deprecated in D:\env\qampp\htdocs\opencart\catalog\model\catalog\product.php on line 45`

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?  local testing
 - Operating system windows11
 - PHP version 8.1.4
 - Apache version Apache/2.4.53
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox 100

**Additional context**

**Comment by chongshengdz** [comment]
v3.0.3.8 does not support php8.0+

**Comment by richfuns** [comment]
> v3.0.3.8 does not support php8.0+

Thank you for your quick reply. 

Would you please let me know which version is ready for PHP 8.0+ ?

**Comment by mhcwebdesign** [comment]
You could try the 3.0.x.x_Maintenance branch which has some bugfixes and changes, and should work with PHP 8.x.

The upcoming OpenCart 4 will support PHP 8, but hasn't yet been released.

**Comment by danielkerr** [comment]
wait for version 4 will be this week.
