### ISSUE TITLE
After installed Chinese language pack, the admin user can not login to the dashboard without any errors in login page. 

### ISSUE THREAD

**Issue by richfuns** [opencart/opencart#10828]
**What version of OpenCart are you reporting this for?**  OpenCart 3.0.3.8

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

1. 
I installed the newest version of OpenCart and the default language is English.  
After I also installed the Chinese language pack , then logout the admin user can never be logined again without any errors occured. 

2.  In front end, 
    The multilanguage can not be changed, nothing work
    The currency can not be changed too, nothing happened and only showing the default.

**To Reproduce**
1. Install OpenCart
2. Installed Chinese pack, which downloaded from https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=15172&filter_category_id=2&filter_license=0&sort=date_modified
4. Applied the Chinese language pack. 
5. Logout
6. Relogin and never logined again. 

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?  Yes, a Production webserver 
 - Operating system Linux
 - PHP version PHP 7.4
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by TheCartpenter** [comment]
OC forum incident request.

**Comment by mhcwebdesign** [comment]
Please re-post on the OpenCart forum, this is not an OpenCart, but more likely an issue with the Simplified Chinese Language extension. You'll probably have to contact the extension author, too.
