### ISSUE TITLE
Control panel design

### ISSUE THREAD

**Issue by donatiss** [opencart/opencart#10829]
![image](https://user-images.githubusercontent.com/6832828/167132266-82ddb4c9-3686-419d-a4a1-ae13f42fb4a2.png) maybe it could be on a new version? :)

**Comment by stalker780** [comment]
What is a difference from current OC admin design except colors?

**Comment by mhcwebdesign** [comment]
This is not an issue or bug report.

**Comment by donatiss** [comment]
It was a suggestion

**Comment by mhcwebdesign** [comment]
You could post it here: https://github.com/opencart/opencart/discussions/categories/ideas
