### ISSUE TITLE
delete column filename from extension_install table in db_schema.php

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10842]
https://github.com/opencart/opencart/blob/cca29725792d886288f5fbf1bbeee0ac49f19aad/upload/system/helper/db_schema.php#L2185

Delete L2185 - L2189

`        	[
				'name' => 'filename',
				'type' => 'varchar(255)',
				'not_null' => true
			],`

**Comment by TheCartpenter** [comment]
Filenate ... ?
