### ISSUE TITLE
search url doesn't show correctly.

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#10850]
/index.php?route=product/search&language=&search=Apple
the correct search url should be
/index.php?route=product/search&language=en-gb&search=Apple

**Comment by mhcwebdesign** [comment]
If you really want some help then you have to provide some more details on how to reproduce this, with some more details, including the OpenCart version used.

**Comment by chongshengdz** [comment]
> If you really want some help then you have to provide some more details on how to reproduce this, with some more details, including the OpenCart version used.

it must be master branch.

**Comment by cgcmart** [comment]
catalog/controller/common/search.php
after line 7
add:
`    	$data['language'] = $this->config->get('config_language');`

will fix this issue, as catalog/view/template/common/search.twig line 3 requested.
