### ISSUE TITLE
SQL syntax errors: line 5372, line 5402 on table subscription in file db_schema.php

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10853]
https://github.com/opencart/opencart/blob/a22c5df186cad5163b3fb456eb8354e284e0190c/upload/system/helper/db_schema.php#L5372

and line 5402:
`'type' => 'varchar(25)',`

Should be changed to:
`'type' => 'enum('day','week','semi_month','month','year')',`

**Comment by danielkerr** [comment]
fixed
