### ISSUE TITLE
Accesssibility: Form elements must have labels: Element has no title attribute Element has no placeholder attribute

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10856]
https://github.com/opencart/opencart/blob/a22c5df186cad5163b3fb456eb8354e284e0190c/upload/admin/view/template/catalog/category_list.twig#L6

Affected:
`<input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', $(this).prop('checked'));" class="form-check-input">`

Line 16:
`<td class="text-center"><input type="checkbox" name="selected[]" value="{{ category.category_id }}" class="form-check-input"/></td>`

**Comment by danielkerr** [comment]
wasting my time

**Comment by danielkerr** [comment]
just tested and works fine

**Comment by cgcmart** [comment]
I tried to add a subcategory test 3 under top category Cameras.
On the Data tab, typing Parent field Cameras, autocomplete did not bring category list to select. When clicked save button, it displayed success button.
Actually, test 3 saved as top category, not Cameras > test 3
![auto_complete_error](https://user-images.githubusercontent.com/14033183/169399821-075b8148-c1c8-4618-a6c8-7675ab78ba4d.jpg)

In addition, alert-success buttons is not dismissed, instead manually close it.

**Comment by TheCartpenter** [comment]
Neither of you described the browser that's been used. @cgcmart: Along with the browser's name, see the Developers Kit > console and network tab for errors.

**Comment by cgcmart** [comment]
no related error log. just autocomplete Data tab Parent doesn't work either add a category or edit a category.
I believe other affected autocomplete functions are the same issue.
![auto_complete_error_edit_1](https://user-images.githubusercontent.com/14033183/169421512-c010d0da-e9f5-46e6-acde-eeaff3d17f55.jpg)
![auto_complete_error_edit_2](https://user-images.githubusercontent.com/14033183/169421528-aca7cf4d-442c-4864-9898-a71fa71c7770.jpg)

**Comment by danijelGombac** [comment]
@cgcmart can you try replece the autocomplet function with:

```
+function ($) {
    $.fn.autocomplete = function (option) {
        return this.each(function () {
            var $this = $(this);
            var $dropdown = $('#' + $this.attr('list'));

            this.timer = null;
            this.items = [];

            $.extend(this, option);

            // Focus
            $this.on('focus', function () {
                this.request();
            });

            // Keydown
            $this.on('input', function () {
                this.request(function() {
                    var value = $this.val();

                    if (value && this.items[value]) {
                        this.select(this.items[value]);
                    }
                });
            });

            // Request
            this.request = function (callback) {
                clearTimeout(this.timer);

                this.timer = setTimeout(function (object) {
                    object.source($(object).val(), $.proxy(object.response, object), callback);
                }, 50, this);
            }

            // Response
            this.response = function (json, callback) {
                var html = '';
                var category = {};
                var name;
                var i = 0, j = 0;

                if (json.length) {
                    for (i = 0; i < json.length; i++) {
                        // update element items
                        this.items[json[i]['label']] = json[i];

                        if (!json[i]['category']) {
                            // ungrouped items
                            html += '<option>' + json[i]['label'] + '</option>';
                        } else {
                            // grouped items
                            name = json[i]['category'];

                            if (!category[name]) {
                                category[name] = [];
                            }

                            category[name].push(json[i]);
                        }
                    }

                    for (name in category) {
                        for (j = 0; j < category[name].length; j++) {
                            html += '<option value="' + category[name][j]['label'] + '">' + name + '</option>';
                        }
                    }
                }

                $dropdown.html(html);

                if (typeof callback === 'function') {
                    callback.apply(this);
                }
            }
        });
    }
}(jQuery);
```
and in category form:

```
$('#input-parent').autocomplete({
    'source': function(request, response, callback) {
        $.ajax({
            url: 'index.php?route=catalog/category|autocomplete&user_token={{ user_token }}&filter_name=' + encodeURIComponent(request),
            dataType: 'json',
            success: function(json) {
                json.unshift({
                    name: '{{ text_none }}',
                    category_id: 0
                });
                response($.map(json, function(item) {
                    return {
                        label: item['name'],
                        value: item['category_id']
                    }
                }), callback);
            }
        });
    },
    'select': function(item) {
        $('#input-parent-id').val(item['value']);
    }
});
```

to see if working.

**Comment by cgcmart** [comment]
@danijelGombac 
I applied your two pieces of codes. The output results are the same as the above clips.

In addition to this, Javascript validator error: Expected an assignment or function call and instead saw an expression in the last line of common.js `}(jQuery);`

**Comment by danielkerr** [comment]
clear ur js cache

**Comment by cgcmart** [comment]
It looks that autocomplete not working is related category_form javascript.
JQuery responds: `data: undefined`

According to JQuery, 

> The .data() method allows us to attach data of any type to DOM elements in a way that is safe from circular references and therefore from memory leaks.


>     Note that this method currently does not provide cross-platform support for setting data on XML documents, as Internet Explorer does not allow data to be attached via expando properties.
>     undefined is not recognized as a data value. Calls such as .data( "name", undefined ) will return the jQuery object that it was called on, allowing for chaining.


`.data()` Example:

```
 $( "div" ).data( "test", { first: 16, last: "pizza!" } );
 $( "span" ).first().text( $( "div" ).data( "test" ).first );
 $( "span" ).last().text( $( "div" ).data( "test" ).last );
```

Edge console log:
![autocomplete_category_form_error](https://user-images.githubusercontent.com/14033183/169569625-7eafbaea-6849-4f67-b2c7-7e9859e43815.jpg)

**Comment by danielkerr** [comment]
this is what i get in the master branch

![image](https://user-images.githubusercontent.com/5079756/169596079-6bbb472e-b8a1-4f10-bb98-d730de927dd5.png)

**Comment by cgcmart** [comment]
Chrome can produce edit category without console log issue. Edge can't.
However with Chrome Edit Feature Module products autocomplete not working with Chrome and has the same console log issue as Edge: `formaction: undefined`, etc. in common.js line 170, line 172.
![autocomplete_featured_module_error](https://user-images.githubusercontent.com/14033183/169604896-0326788c-0324-41a5-ba76-b8a581da639a.jpg)

**Comment by BuslikDrev** [comment]
And in the latest version of Chrome, I have to click on the field 2 times for the window to appear. Also, the window quickly disappears the first time you move the mouse.

**Comment by guymass** [comment]
I am using Firefox on Ubuntu and currently facing the same issue, not being able to add categories to products or create sub categories. I am running OC4, when I try to save my category selection in the product page I see this in console:

![photo_2023-02-26_17-40-34](https://user-images.githubusercontent.com/58882903/221423261-bc1a21bc-224e-420f-a948-0d122177e958.jpg)

I cannot see any error in logs but this 'enctype undefined'

**Comment by danielkerr** [comment]
I already fixed in master branch
