### ISSUE TITLE
Typo errors: line 2 in extension module bestseller.twig, featured.twig, latest.twig, special.twig

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10852]
https://github.com/opencart/opencart/blob/a22c5df186cad5163b3fb456eb8354e284e0190c/upload/extension/opencart/catalog/view/template/module/bestseller.twig#L2

Should be:
`<div class="row{% if axis == 'horizontal' %} row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4{% endif %}">`

**Comment by danielkerr** [comment]
no idea what the issue is.

**Comment by cgcmart** [comment]
Did you skip lg-4  to xl-4?
