### ISSUE TITLE
file manager last directory remembered

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10855]
// Make sure we have the correct directory
		if (isset($this->request->get['directory'])) {
			$directory = $base . html_entity_decode($this->request->get['directory'], ENT_QUOTES, 'UTF-8') . '/';
			$this->session->data['filemanager_directory'] = $directory;
		} else {
			$directory = isset($this->request->get['parent']) ? $base : $this->session->data['filemanager_directory'];
		}

view

    $('#modal-image').on('click', '#button-parent', function(e) {
        e.preventDefault();
  
        $('#modal-image .modal-body').load($(this).attr('href') + '&parent');
    });
  

https://github.com/opencart/opencart/blob/a22c5df186cad5163b3fb456eb8354e284e0190c/upload/admin/controller/common/filemanager.php#L42-L47

**Comment by danielkerr** [comment]
noty required

**Comment by danielkerr** [comment]
ill add this as a feature
