### ISSUE TITLE
Product gets deleted even if I click on Cancel on delete confirm dialog box.

### ISSUE THREAD

**Issue by Aks8578** [opencart/opencart#10865]
**What version of OpenCart are you reporting this for?**
Master Branch (opencart 4)

**Describe the bug**
Any list page (i.e. product list page, category list page), in which there is a delete button. After Selecting the item, when I click on delete button. There is a confirmation dialog box , asking for confirmation. But Even If I click on Cancel button, its get deleted. But it should not.

**To Reproduce**
1. Go to [http://localhost/upload/admin/index.php?route=catalog/product](http://localhost/upload/admin) (you can go any page , in which there is a delete button)
2. Select Any product of your choice and then click on delete button.
3. There will be a confirmation box, in which you have to click on cancel button. And Wait for few second.
4. The Success message will appear and the product will get deleted.
5. See error

**Expected behaviour**
The product should not get deleted when I Click on Cancel button.

Please Look after this serious Bug. 
Thanks

**Comment by danielkerr** [comment]
thats a bit of a pain

**Comment by Aks8578** [comment]
I know @danielkerr  Sir. Now You have to change all the listings pages. But when we develop something, it's our responsibility that it should to be perfect in every aspect.

**Comment by chongshengdz** [comment]
after testing using latest google chrome, delete button does not do anything, neither confirm nor cancel.

**Comment by Aks8578** [comment]
@danielkerr  Sir I created A pull request to solve this issue.
Please Have A look
[https://github.com/opencart/opencart/pull/10870/#issue-1244136375](https://github.com/opencart/opencart/pull/10870/#issue-1244136375)

**Comment by chongshengdz** [comment]
after testing， your pull request works fine.

**Comment by Aks8578** [comment]
Thanks @chongshengdz
