### ISSUE TITLE
OpenCart Default Extensions uninstall more errors

### ISSUE THREAD

**Issue by BuslikDrev** [opencart/opencart#10876]
OpenCart 4.0.0.0
There are many errors when disabling standard extensions, which obliges you to use standard extensions.

**Comment by danielkerr** [comment]
dont uninstall them then. the only other way is go to each extension. uninstall them from the extensio  page then uninstall from installer page.

**Comment by BuslikDrev** [comment]
Taking advantage of the moment.
Make the installation of modules so that you can name the archive whatever you want. Also take the namespace from install.json.
Also, the archive storage in storage\marketplace\ is divided into folders according to the namespaces specified in install.json

What developers will get:
- the ability to name the module archive as they want.
- the ability to assemble an assembly from several modules, then update each module from the assembly separately.

**Comment by stalker780** [comment]
@BuslikDrev 
https://github.com/opencart/opencart/pull/9710

**Comment by stalker780** [comment]
@BuslikDrev 

By the way, in latest release OC support 2 types of ocmod.zip packages. Single and multiple.
Multiple type is very close to what we asked for. Extension code is taken from subfolder name.

ocmod.zip can contain either single package:
| - admin/
| - catalog/
| - install.json
In this example a code is taken from ocmod.zip basename
https://github.com/opencart/opencart/blob/49a130e7f8e10c507f42dd8ac94e3f917001c832/upload/admin/controller/marketplace/installer.php#L201



or multiple packages
my_extension_package.ocmod.zip:
|-my_extension_code1/
|-my_extension_code1/admin/
|-my_extension_code1/catalog/
|-my_extension_code1/system/
|-my_extension_code1/install.json
|-my_extension_code2/
|-my_extension_code2/admin/
|-my_extension_code2/catalog/
|-my_extension_code2/system/
|-my_extension_code2/install.json
Where extension code is taken from subfolder name
https://github.com/opencart/opencart/blob/49a130e7f8e10c507f42dd8ac94e3f917001c832/upload/admin/controller/marketplace/installer.php#L232

**Comment by BuslikDrev** [comment]
https://www.opencart.com/index.php?route=marketplace/extension

When uploading an archive to the store, the underline is removed from the archive. As a result, my module will not install on OpenCart 4.
Upload: my_module.ocmod.zip
DownLoad: mymodule.ocmod.zip

**Comment by BuslikDrev** [comment]
what happens when you install these extensions?
extension\analytics1\admin\controller\analytics\google.php
extension\analytics2\admin\controller\analytics\google.php

Both of them will have one config: analytics_google_status

**Comment by stalker780** [comment]
@BuslikDrev 
I have proposed to use extension code before module code in `oc_setting` table. Daniel rejected it.
https://github.com/opencart/opencart/pull/9655

I also think these possible duplicate codes are a good ground for lots of modules incompatibilities and bugs.
