### ISSUE TITLE
OC4 oc_product.viewed is no longer used

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#10881]
Since `oc_product.viewed` field have moved to `oc_product_report` table, it should be removed from installer and DB structure.

Also getPopular() does not work correctly in catalog/product model. It should not sort by p.`viewed`:
https://github.com/opencart/opencart/blob/90b9f67546df4dd8dfb91ecd66dd7802acf790c9/upload/catalog/model/catalog/product.php#L256

**Comment by TheCartpenter** [comment]
Yes, correct. ```p.viewed``` field should be removed.

**Comment by danielkerr** [comment]
viewed is required is we sort by popularity. same with sales.
