### ISSUE TITLE
Storage path not defineable

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#10880]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**
Because the input field is readable only, there is no way (without editing manual !) to manual define the storage path.
But (especially for me as developer) this is an absolute must, otherwise having multiple installations, all files would be written into the same folder!

**Comment by danielkerr** [comment]
fine~!

**Comment by danielkerr** [comment]
added a fix
