### ISSUE TITLE
[Bug] Shipping estimate and text success language

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#10887]
**What version of OpenCart are you reporting this for?**
Latest from github

**Describe the bug**
If you use other language then english, text_succes is loaded from english file and not from other language.

Also after shipping method is applied, some translation are switched to english
![cart_bugs](https://user-images.githubusercontent.com/14251939/170253786-76ab4732-68f6-48f4-a598-16ea114fa4af.png)

If I remove/delete english from admin, everything is ok.

**Comment by TheCartpenter** [comment]
Yes, this is a persistent issue even from previous OC versions. The part where it's difficult to see is if a language pack is either published accurately or if it contains errors to result this.

**Comment by condor2** [comment]
Language is OK because after I removed english, all variables are read.

**Comment by TheCartpenter** [comment]
But when removing other language packs is when the language text definition is not translated after a refresh and that can also be caused by the extension language pack by its distribution. Have you tried other language packs by other distributions to reproduce the issue?

**Comment by condor2** [comment]
No issue on 3.0.3.8

**Comment by TheCartpenter** [comment]
Might need further testing on this one.

**Comment by BuslikDrev** [comment]
> It is a bug 100%,

https://github.com/opencart/opencart/issues/10922#issuecomment-1140285134

**Comment by nmpetkov** [comment]
I tested in my test OC4 site, and all works fine in my opinion. Everyone can also test there:
https://octest40.cmstory.com/
Just select Bulgarian language and test.

**Comment by mhcwebdesign** [comment]
@nmptekov: It took me only a few seconds to come across a bug in https://octest40.cmstory.com/canon-eos-5d-%D0%BA%D0%B0%D0%BC%D0%B5%D1%80%D0%B0?route=product/product&language=bg , namely the add to cart doesn't work!
Tested in Firefox 101.0

The bottom line is: OpenCart 4.0.0.0 is not yet suitable for live sites!

**Comment by nmpetkov** [comment]
@mhcwebdesign ?? Add to cart works, but this product needs to specify "Select" :-) Just specify the item on the page colored in red -)

**Comment by mhcwebdesign** [comment]
@nmptekov: Sorry, no it doesn't work! And of course I selected the required option.
Tested with Chrome Version 102.0.5005.61 (Official Build) (64-bit) and Firefox 101.0.

OpenCart 4.0.0.0 has so many bugs, when I have some time I'll post them all here on github.

**Comment by nmpetkov** [comment]
@mhcwebdesign It is really funny, you are trying to add to cart product with options, in which no enogth quontity :-) Just for you I changed quontity to this product, and even I managed to place an order. My advice to you is to try again to place order, even to try with other products.
It is not to prove Opencart 4.0.0.0 is without bugs - on the contrary, i also think it should be a beta release.

**Comment by nmpetkov** [comment]
@condor2 After more testing with other browsers (Mozila and Opera), I found the problem really occurs, and for now I think it is when ordering as guest. I suppose in ajax calls somewhere language fails.

**Comment by mhcwebdesign** [comment]
@nmpetkov: Well, I hate to spoil the party, but on your test site none of the products can be added to the cart, unlike a standard OpenCart 4.0.0.0 where at least this bit works, though there are of course other bugs still to be addressed.

**Comment by nmpetkov** [comment]
@mhcwebdesign Ok. I can add products, and place orders. With 4 different browsers. Can sombody ( @condor2 ?) confirm that it is not possible to add products to cart?

**Comment by rsuchovsky** [comment]
@nmpetkov  I have a clean oc4 installation, adding products to cart doesn't work, customer registration doesn't work, there are more things that don't work.

Everything will start working after logging in to the admin panel.
You can test:
1. Log out of the admin panel
2. Delete cookies for the site
3. Refresh the front-end page
4. Try adding a product to the cart or creating a customer registration
5. Adding to cart doesn't work, etc.
6. Log in to the admin panel
7. go to the front-end page, add the product to the cart (starts working)

**Comment by TheCartpenter** [comment]
Looks like the network tab reports the following: 

```success: "Успех: Добавихте <a href=\"https://octest40.cmstory.com/canon-eos-5d-камера?route=product/product&amp;language=bg\">Canon EOS 5D камера</a> към вашата <a href=\"https://octest40.cmstory.com?route=checkout/cart&amp;language=bg\">количка</a>!"```

However, the next row reports this:

```Your shopping cart is empty!```

While there are no error indications in the console tab, see if the items do get added into the oc_cart table on the database. The items on the grid also don't increase the counter whenever I am successfully able to add a product to the cart. The checkout/cart route also indicates that the shopping cart is empty on my end.

**Comment by rsuchovsky** [comment]
@TheCartpenter  yes, product will be added to the database, but the cart is empty on the page :)

**Comment by nmpetkov** [comment]
@

> @nmpetkov I have a clean oc4 installation, adding products to cart doesn't work, customer registration doesn't work, there are more things that don't work.
> 
> Everything will start working after logging in to the admin panel. You can test:
> 
> 1. Log out of the admin panel
> 2. Delete cookies for the site
> 3. Refresh the front-end page
> 4. Try adding a product to the cart or creating a customer registration
> 5. Adding to cart doesn't work, etc.
> 6. Log in to the admin panel
> 7. go to the front-end page, add the product to the cart (starts working)

@rsuchovsky Genius:-) I confirm this behavior

**Comment by nmpetkov** [comment]
@condor2 @TheCartpenter 
About the reason for the incorrect language in the original issue. The problem is probably in this line where there is no language parameter:

https://github.com/opencart/opencart/blob/master/upload/extension/opencart/catalog/view/template/total/shipping.twig#L50

I noticed that unlike previous versions, in Opencart 4 in the frontend there is no information about the language in the sessions and cookies, ie. relies on the submission of non-core language as a parameter.

**Comment by condor2** [comment]
@nmpetkov 
Normally should displayed...because is in controller

https://github.com/opencart/opencart/blob/master/upload/extension/opencart/catalog/controller/total/shipping.php#L41

**Comment by TheCartpenter** [comment]
> @condor2 @TheCartpenter About the reason for the incorrect language in the original issue. The problem is probably in this line where there is no language parameter:
> 
> https://github.com/opencart/opencart/blob/master/upload/extension/opencart/catalog/view/template/total/shipping.twig#L50
> 
> I noticed that unlike previous versions, in Opencart 4 in the frontend there is no information about the language in the sessions and cookies, ie. relies on the submission of non-core language as a parameter.
> 
> In addition, I just searched the frontend code, and found that there are several other similar deficiencies in the submitted language.

You're probably referring to the ```$this->language->load``` method.

**Comment by nmpetkov** [comment]
Mentioned PR above resolves the problem in the front of this issue. Can check in the test site: https://octest40.cmstory.com/.

**Comment by condor2** [comment]
No issue on shipping estimate after I applied you pull request
