### ISSUE TITLE
type error string to array

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10892]
https://github.com/opencart/opencart/blob/0d65ac817362eae9a3d4adc19ab159245ac12325/upload/system/helper/utf8.php#L282

https://github.com/opencart/opencart/blob/0d65ac817362eae9a3d4adc19ab159245ac12325/upload/system/helper/utf8.php#L512 

function unicode_to_utf8(array $unicode) {

https://github.com/opencart/opencart/blob/0d65ac817362eae9a3d4adc19ab159245ac12325/upload/system/helper/utf8.php#L549

----------------

https://github.com/opencart/opencart/blob/0d65ac817362eae9a3d4adc19ab159245ac12325/upload/system/helper/utf8.php#L45-L49

	function utf8_substr(string $string, int $offset, int $length = 0) {
		if ($length == 0) {
			return mb_substr($string, $offset, utf8_strlen($string));
		} else {
			return mb_substr($string, $offset, $length);
		}
	}

**Comment by danielkerr** [comment]
f all information!

**Comment by danielkerr** [comment]
why are u posting the wrong data types via ur admin?
