### ISSUE TITLE
Undefined constant "APPLICATION" when using cli_install.php 

### ISSUE THREAD

**Issue by mr-madjarov** [opencart/opencart#10904]
**What version of OpenCart are you reporting this for?**
4.0.0.0
**Describe the bug**
**_php cli_install.php install_** returns:

		Fatal error: Uncaught Error: Undefined constant "APPLICATION" in /home/username/www/opencart/system/framework.php:4
		Stack trace:
		#0 /home/username/www/opencart/system/startup.php(66): require_once()
		#1 /home/username/www/opencart/install/cli_install.php(45): require_once('/home/username/...')
		#2 {main}
		  thrown in /home/username/www/opencart/system/framework.php on line 4

**To Reproduce**
1. Go to location of cli_install.php
2. Try to run php cli_install.php
3. See error

**Expected behavior**
Expected to start installation if all required arguments are present or show "**_Usage:_**" message if arguments are not present.

**Server / Test environment:**
 - Operating system - Debian GNU/Linux 10
 - PHP version - PHP 8.0.19 (cli) (built: May 19 2022 13:36:26)
 - Apache version - 2.4.46

**Comment by victoralbala** [comment]
Hi! I'm getting the same error, any news about this?

**Comment by dgomezleon** [comment]
Any update about this?

**Comment by dgomezleon** [comment]
Do you plan to launch a new release with the fix?

**Comment by farrukhahmed4220** [comment]
Hello, 
I'm getting the same error for OpenCart 4.0.1.1
OS: Debian 10
php 8.0
nginx version: nginx/1.14.2

`PHP Fatal error:  Uncaught Error: Undefined constant "APPLICATION" in /mnt/user_data/home/master/applications/shit-op/public_html/system/framework.php:4
Stack trace:
#0 /mnt/user_data/home/master/applications/shit-op/public_html/index.php(70): require_once()
#1 {main}
  thrown in /mnt/user_data/home/master/applications/shit-op/public_html/system/framework.php on line 4"`

**Comment by dgomezleon** [comment]
I have to say that since version 4.0.1.1, it is working again for me. I'm using:

OS: Debian 11
php 8.1
Server version: Apache/2.4.54

```
root@2f2d059c211b:/# php "/opt/bitnami/opencart/install/cli_install.php" install --db_hostname mariadb --db_port 3306 --db_username bn_opencart --db_password  --db_database bitnami_opencart --db_driver mysqli --username user --password bitnami --email user@example.com --http_server http://127.0.0.1/
SUCCESS! OpenCart successfully installed on your server
Store link: http://127.0.0.1/
Admin link: http://127.0.0.1/admin/
```
I hope it helps others.

**Comment by danielkerr** [comment]
@farrukhahmed4220  u are not using the correct version. download latest.

**Comment by danielkerr** [comment]
> @danielkerr Checked the fix by downloaded the fixed cli_install.php script from master branch but the error still presents. The file _**startup.php**_ https://github.com/opencart/opencart/blob/master/upload/install/cli_install.php#L45 (where variable APPLICATION is defined) is executed before config file with _APPLICATION_ parameter has been creates. Please check the CLI installation

if u go up a few lines u find 

// APPLICATION
define('APPLICATION', 'Install');

**Comment by farrukhahmed4220** [comment]
Hello,

I'm still getting the same error, I used the cli_install.php method to install. It installed successfully but when I hit the URL it gives an error in the nginx_error_logs

`2022/09/20 11:07:50 [error] 4528#4528: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "APPLICATION" in /mnt/user_data/home/master/applications/shit-op/public_html/system/framework.php:4
Stack trace:
#0 /mnt/user_data/home/master/applications/shit-op/public_html/index.php(70): require_once()
#1 {main}
  thrown in /mnt/user_data/home/master/applications/shit-op/public_html/system/framework.php on line 4" while reading response header from upstream, client: 111.119.183.14, server: shit-op.com, request: "GET /?asd65as1 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "shit-op.com"
`
Using this link (https://github.com/opencart/opencart/archive/refs/tags/4.0.1.1.tar.gz) to download the opencart 4.0.1.1 

OS: Debian 10
OpenCart 4.0.1.1
PHP 8.1
Nginx 1.14.2
MySQL 10.3

**Comment by ADDCreative** [comment]
@farrukhahmed4220 Check your config.php has been written correctly and contains the APPLICATION define.

**Comment by farrukhahmed4220** [comment]
> @farrukhahmed4220 Check your config.php has been written correctly and contains the APPLICATION define.

@ADDCreative 

Here is the config.php file. APPLICATION is defined

 `<?php
// APPLICATION
define('APPLICATION', 'Catalog');

// HTTP
define('HTTP_SERVER', 'http://shit-op.com/');

// DIR
define('DIR_OPENCART', '/mnt/user_data/home/master/applications/shit-op/public_html/');
define('DIR_APPLICATION', DIR_OPENCART . 'catalog/');
define('DIR_SYSTEM', DIR_OPENCART . 'system/');
define('DIR_EXTENSION', DIR_OPENCART . 'extension/');
define('DIR_IMAGE', DIR_OPENCART . 'image/');
define('DIR_STORAGE', DIR_SYSTEM . 'storage/');
define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');
define('DIR_TEMPLATE', DIR_APPLICATION . 'view/template/');
define('DIR_CONFIG', DIR_SYSTEM . 'config/');
define('DIR_CACHE', DIR_STORAGE . 'cache/');
define('DIR_DOWNLOAD', DIR_STORAGE . 'download/');
define('DIR_LOGS', DIR_STORAGE . 'logs/');
define('DIR_SESSION', DIR_STORAGE . 'session/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'farrukh');
define('DB_PASSWORD', 'adminfarrukh');
define('DB_DATABASE', 'shit_op_69_786');
define('DB_PREFIX', 'oc_');
define('DB_PORT', '3306');
`

**Comment by farrukhahmed4220** [comment]
> @farrukhahmed4220 Check your config.php has been written correctly and contains the APPLICATION define.

@ADDCreative , Thanks for pointing this out. Also, there were a number of parameters in the config.php that need to be corrected, as I have moved the storage directory out of my web root.

**Comment by victoralbala** [comment]
Hi guys! any news about this? I'm having the same problem

**Comment by ADDCreative** [comment]
@victoralbala fixed in latest version.

**Comment by coffiner** [comment]
php Module
fileinfo isn't load... 解决问题
