### ISSUE TITLE
return or returns?

### ISSUE THREAD

**Issue by BuslikDrev** [opencart/opencart#10907]
return or returns?

https://github.com/opencart/opencart/commit/3f8309a47eef403e27eb009495197246473b8251
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/account/returns.php
https://github.com/opencart/opencart/blob/master/upload/catalog/language/en-gb/account/return.php
https://github.com/opencart/opencart/blob/master/upload/catalog/view/template/account/return_form.twig
https://github.com/opencart/opencart/blob/master/upload/catalog/view/template/account/return_info.twig
https://github.com/opencart/opencart/blob/master/upload/catalog/view/template/account/return_list.twig

**Comment by cgcmart** [comment]
I prefer controller/account/return.php and model/account/return.php that will consist with other files such as order.php, etc.

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart/pull/10888#issuecomment-1137856250
