### ISSUE TITLE
Event compatibility between OpenCart versions

### ISSUE THREAD

**Issue by BuslikDrev** [opencart/opencart#10909]
OC 2.1
addEvent($code, $trigger, $action)

OC 2.3
addEvent($code, $trigger, $action, $status = 1)

OC 3.0
addEvent($code, $trigger, $action, $status = 1, $sort_order = 0)

OC 4.0
addEvent(string $code, string **$description,** string $trigger, string $action, bool $status = true, int $sort_order = 0)

**Comment by TheCartpenter** [comment]
Yes. The ```description``` field will need to be added to the Event wiki documentation.

**Comment by BuslikDrev** [comment]
> Yes. The `description` field will need to be added to the Event wiki documentation.

And for all developers, an additional condition for checking the version of OpenCart.

**Comment by danielkerr** [comment]
added to wiki
