### ISSUE TITLE
default theme

### ISSUE THREAD

**Issue by Taylory174** [opencart/opencart#10914]
the default theme folder is missing. where to install other themes now, in which folder?

**Comment by BuslikDrev** [comment]
extension\opencart\catalog\view\template

**Comment by Taylory174** [comment]
I moved the template along your path. it did not appear in the settings. Most likely, something went wrong.

**Comment by BuslikDrev** [comment]
> I moved the template along your path. it did not appear in the settings. Most likely, something went wrong.
Are you a developer or user?
Themes from previous versions are not compatible.

**Comment by stalker780** [comment]
You need to reroute your theme using event system
https://github.com/opencart/opencart/issues/8923#issuecomment-734720061

**Comment by danielkerr** [comment]
setup an event overwide. 

	'view/*/before' => [
		-1 => 'extension/{code}/catalog/event/theme',
	],

**Comment by danielkerr** [comment]
I'm writing examples

https://github.com/opencart/examples

**Comment by danielkerr** [comment]
yes they are

**Comment by danielkerr** [comment]
public function install(): void {
		$language_data = [
			'name'       => 'German',
			'code'       => 'de',
			'locale'     => 'de-de',
			'sort_order' => 1
		];

		$this->load->model('localisation/language');

		$this->model_localisation_language->addLanguage($language_data);

		$startup_data = [
			'code'       => 'language_german',
			'action'     => 'catalog/extension/language_example/startup/german',
			'status'     => 1,
			'sort_order' => 2
		];

		$this->load->model('setting/startup');

		$this->model_setting_startup->addStartup($startup_data);

		$startup_data = [
			'code'       => 'language_german',
			'action'     => 'admin/extension/language_example/startup/german',
			'status'     => 1,
			'sort_order' => 2
		];

		$this->model_setting_startup->addStartup($startup_data);
	}

**Comment by BuslikDrev** [comment]
@danielkerr Have you tested the download speed of 142 (number of languages) controllers?

**Comment by danielkerr** [comment]
example here:

https://github.com/opencart/examples

will add it to tutorial later
