### ISSUE TITLE
[Bug] Catalog language not Default from admin settins

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#10910]
**What version of OpenCart are you reporting this for?**
Latest github

**Describe the bug**
If you set from admin another language for admin dashboard and catalog, when you load the store default language is English and not the language set from admin settings.

**Comment by TheCartpenter** [comment]
Multiple OC location commits about the language, so far...

**Comment by BuslikDrev** [comment]
Where does it show by default?

**Comment by condor2** [comment]
From store settings.

If a Default language is set in store settings, then store (catalog) should load in that language first...and not in english.
![catalog_lang](https://user-images.githubusercontent.com/14251939/171197971-f7cbfc70-4f49-4ae7-8628-30ea5c3d3447.png)

**Comment by BuslikDrev** [comment]
> From store settings.
> 
> If a Default language is set in store settings, then store (catalog) should load in that language first...and not in english. !

The browser language will be loaded first if it is not specified in the link. If the site does not have a browser language, it will load the default language.
The browser language will be loaded first if it is not specified in the link. If the site does not have a browser language, it will load the default language.

**Comment by danielkerr** [comment]
also clear cookies

**Comment by danielkerr** [comment]
it could also be stored in session
