### ISSUE TITLE
Warning: is_dir(): open_basedir restriction in effect. 

### ISSUE THREAD

**Issue by Piercerer** [opencart/opencart#10915]
OpenCart 4.0.0

When installing OpenCart 4.0.0 I got an error:

**Warning: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s):** (/home/.composer:/home/web/local.net/public_html:/home/web/local.net/private:/home/web/local.net/public_shtml:/home/local.net/tmp:/tmp:/var/www/html:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt) in /home/web/local.net/public_html/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 91
Twig\Error\LoaderError: The "/" directory does not exist ("/"). in /home/web/local.net/public_html/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 92​

PHP Version 8.0.19
Linux 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64
Build Date May 17 2022 18:48:30
Server API FPM/FastCGI
MariaDB 10.5.16
My open_basedir /home/.composer:/home/web/local.net/public_html:/home/web/local.net/private:/home/web/local.net/public_shtml:/home/tmp:/tmp:/var/www/html:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt

Kindly tell me what extra open_basedir path should I add to my Apache2 so the script will work?
I don't want to use open_basedir = none option for safety reasons.

`https://forum.opencart.com/viewtopic.php?t=170723 can't use because there are no such lines in autoloader 4.0.0 ver.`

**Comment by TheCartpenter** [comment]
You'd need to contact your host to solve this problem.

**Comment by TheCartpenter** [comment]
This solution seem to work: https://forum.opencart.com/viewtopic.php?f=210&t=228527#p843814 .

**Comment by mathsolutions** [comment]
same problem, @TheCartpenter solution works

**Comment by yoncu** [comment]
RESOLV: https://www.yoncu.com/s148/opencard-hata-cozumu-openbasedir-restriction-in-effect

Error: "warning: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s)"
Resolv File: /system/storage<AppID>/vendor/twig/twig/src/Loader/FilesystemLoader.php
Find lines(2 lines):
Old: $checkPath = $this->isAbsolutePath($path) ? $path : $this->rootPath.$path;
Nev: $checkPath = $this->rootPath.$path;
