### ISSUE TITLE
New save method is annoying

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#10928]
**What version of OpenCart are you reporting this for?**
Latest github

**Describe the bug**
In 4.0 when you save everything current window doesn't close/redirect and you need to click on back or click on main link to repeat the action.

Very annoying ....time waisted

**Comment by stalker780** [comment]
Many people found save+redirect annoying.

I think there should be 3 buttons:
Apply, Save, Cancel

This would be a most comfortable solution for everyone.

**Comment by condor2** [comment]
When you add products is annoying...

After you click on save you need to press back...then add again new product because there is no New product on product_form....

**Comment by chulcha** [comment]
ADD product 
"Save" - redirect list of product
"Apply" redirect on edit product
"Save and Add" redirect on add  product
It's not difficult, but it's convenient

EDIT 
"Save" - redirect list of product
"Apply" redirect on edit product

**Comment by TheCartpenter** [comment]
I agree that most platforms these days do have a new product button on their forms page when the action no longer needs to be redirected.

**Comment by TheCartpenter** [comment]
The only problem with a new button is whenever extensions can auto-use this button with jQuery on the same page ... perhaps it may not be suggested to add it.
