### ISSUE TITLE
(&amp;) is in all the links of opencart 4.0

### ISSUE THREAD

**Issue by Aks8578** [opencart/opencart#10921]
**What version of OpenCart are you reporting this for?**
Opencart 4.0 (latest)

**Describe the bug**
because this &amp; is in all the link. I am not able to get the variable through $this->request->get[] ;

**Comment by adelante25** [comment]
I got this error when make opencar 4.0 update

Warning: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/home/vipgiy/:/tmp:/var/tmp:/opt/alt/php74/usr/share/pear/:/dev/urandom:/usr/local/lib/php/:/usr/local/php74/lib/php/) in /home/:/public_html/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 91Twig\Error\LoaderError: The "/" directory does not exist ("/"). in /home/:/public_html/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 92

**Comment by danielkerr** [comment]
should i guess the page?

**Comment by Aks8578** [comment]
when you login in admin side . For Example I am using the following link.
[http://localhost/upload/admin/index.php?route=catalog/product|form&user_token=a8e1d4189800a870af8ddfbc66b870e8&product_id=42](http://localhost/upload/admin/index.php?route=catalog/product|form&user_token=a8e1d4189800a870af8ddfbc66b870e8&product_id=42)

It will ask you the login detail. After you login it should redirect you to the given product_id. But it will not..
Before the product_id there is amp; in the url.

**Comment by danielkerr** [comment]
i already fixed the links.

@[adelante25](https://github.com/adelante25) dont hijack peoples reports!
