### ISSUE TITLE
[4.0.0.0] Checkout > layout of checkboxes & checkbox Terms is prechecked!

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#10932]
**What version of OpenCart are you reporting this for?**
4.0.0.0

Currently, the checkboxes (Privacy, Newsletter, Terms) are splittet (e.g. PC > full screen):
![OC-4000-Checkout-Checkboxes](https://user-images.githubusercontent.com/1905204/170864327-7fe63ecd-b09d-4136-89c0-48f9ddaf58b7.png)

Suggest to position all checkboxes in one section.

Beside this: after calling the checkout, the checkbox for the Terms is prechecked.
**This behaviour is not allowed** (see GDPR), visitor must check by himself.
This is valid for all possible checkboxes during the checkout, visitor must actively click on them (except the one for payment & shipping address).

Finally: the wording **I have read and agree to the {privacy/terms}** is not correct.
That should be: **I have read and take note of {privacy/terms}** 
(see seperate PR for that: https://github.com/opencart/opencart/pull/10933 )

Reason: some legal decisions about such wording ended in high punishments (2021 & 2022), because when you agree, the visitor is accepting everything of them.
Which must not be the case, but taking note of them is enough and more accurate.

And in terms of the GDPR, such acceptence has to be recorded (which I am badly missing).

**Comment by danielkerr** [comment]
"Beside this: after calling the checkout, the checkbox for the Terms is prechecked."

bnot on my version its not.
