### ISSUE TITLE
[4.0.0.0] Checkout > no Privacy Terms when Guest

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#10930]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**
Checkout as **Guest**: no checkout to confirm terms

**To Reproduce**
1. add product to shopping cart
2. go to checkout
3. click **Guest Checkout**
4. checkbox for Privacy Policy **is NOT displayed**

Checkout "Register Account"
same as above 1 & 2
3. choose Register Account
4. checkbox for Privacy Policy **is displayed**

**Comment by TheCartpenter** [comment]
To ensure this is not a coincidence, in your admin > systems > settings > edit settings, did you also added your information page for checkout?

**Comment by osworx** [comment]
> To ensure this is not a coincidence, in your admin > systems > settings > edit settings, did you also added your information page for checkout?

Yes, of course ..

**Comment by danielkerr** [comment]
i think agree to account creation it should not only checkout terms if there are any.
