### ISSUE TITLE
httponly = false 

### ISSUE THREAD

**Issue by BuslikDrev** [opencart/opencart#10941]
Why would OpenCart 4 let js scripts get a session cookie?

**Comment by danielkerr** [comment]
httponly = false got nothing to do with js being able to set cookies. sick of playing guessing games.

**Comment by BuslikDrev** [comment]
> httponly = false got nothing to do with js being able to set cookies. sick of playing guessing games.
<button onclick="console.log(document.cookie);" type="button">Get Session Cookie</button>
![image](https://user-images.githubusercontent.com/32706609/172239245-c633485f-72ca-45aa-a301-06cdd6e0d546.png)
