### ISSUE TITLE
Delete tax class button in admin panel not working

### ISSUE THREAD

**Issue by atomicsp** [opencart/opencart#10948]
Hello!
Opencart 4, newest version from git today (2022-05-30 18:47 UTC)
https://github.com/opencart/opencart/tree/b9e0499caadcd2f2b8c0ddbdc12b551c58e91e16

Delete tax class button in admin panel not working.
Confirmation dialog appears, but no action or error is shown (And no network traffic initiated)

**Comment by cgcmart** [comment]
First delete tax rate, then delete tax class.

**Comment by saosangmo** [comment]
It is the bug.
> First delete tax rate, then delete tax class.
