### ISSUE TITLE
OC4: header.twig script.href does not work

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#10942]
Daniel, you either forgot to modify library/document.php, or made a typo.

`{{ script }}` is a string, not array.

https://github.com/opencart/opencart/blob/54ea597d1f387f1a04bd0d2bdf2ac0bdbbda2a8a/upload/catalog/view/template/common/header.twig#L23

https://github.com/opencart/opencart/blob/ee843768933c299c2175edc0129b6fee4fea3427/upload/admin/view/template/common/header.twig#L32

![image](https://user-images.githubusercontent.com/6297070/170889856-0795ff95-a05c-4f96-8dd4-0e599fb31e40.png)

**Comment by cgcmart** [comment]
It's within
`{% for script in scripts %}`

allow developers to add scripts and styles to extensions?

**Comment by stalker780** [comment]
@cgcmart 
Yes. In one the latest `header.twig` commits Daniel replaced `{{ script }}` with `{{ script.href }}`.

But perhaps he forgot to change this structure here. Because `script` variable is still a string and it cannot have `[href]` key.
https://github.com/opencart/opencart/blob/b9e0499caadcd2f2b8c0ddbdc12b551c58e91e16/upload/system/library/document.php#L131
