### ISSUE TITLE
Cart button doesn't get updated

### ISSUE THREAD

**Issue by amaco596** [opencart/opencart#10943]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**
When I go to shopping cart page after adding some products to cart, and try to update the quantity of any product, the cart button is not updated with the new quantity and price.

**To Reproduce**
1. Add some products to your cart.
2. Go to shopping cart page.
3. Change quantity for any product.
4. The quantity and total price is updated on shopping cart page, but not in cart button.

**Expected behavior**
The quantity and total price should be updated in cart button as well.

**Screenshots / Screen recordings**
![shopping_cart](https://user-images.githubusercontent.com/51860627/170895464-8c9c9ed0-dd74-4e62-a3e0-3857b08a4cdb.jpg)

**Comment by chongshengdz** [comment]
need to refresh the page to have the cart updated.

**Comment by amaco596** [comment]
@chongshengdz, that's the problem. In OC 3, the cart button is updated automatically when you update quantity. It should get updated in OC 4 as well, don't you think so?

**Comment by danielkerr** [comment]
it does do as far as i know. ill fix it.

**Comment by BuslikDrev** [comment]
```
This means that you need to add the ability to ajax script to fulfill several conditions.
Example of future work:
<form method="post" data-oc-toggle="ajax" data-oc-load="http://demo.opencart.com/index.php?route=checkout/cart|list&language=en-gb http: //demo.opencart.com/index.php?route=common/cart|info&language=en-gb" data-oc-target="#shopping-cart #header-cart">
<button type="submit" formaction="http://demo.opencart.com/index.php?route=checkout/cart|edit&language=en-gb" data-bs-toggle="tooltip" title="" class ="btn btn-primary" data-bs-original-title="Update" aria-label="Update"><i class="fas fa-sync-alt"></i></button>
</form>
```

**Comment by danielkerr** [comment]
u do have a big cart page giving the full details. its not required!

**Comment by amaco596** [comment]
@danielkerr, I agree with you that you get the full details on the shopping cart page, but why shouldn't the cart button get updated as well, like in OC 3? It looks weird to me.
