### ISSUE TITLE
CKEditor not loaded anymore

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#10959]
**What version of OpenCart are you reporting this for?**
Latest github

**Describe the bug**
CKEditor with latest github version  doesn't load

Uncaught TypeError: $(...).ckeditor is not a function line 1044, where line 1044 is this

$('textarea[data-oc-toggle=\'ckeditor\']').ckeditor({

**Comment by BuslikDrev** [comment]
https://github.com/opencart/opencart/pull/10955

**Comment by anytizer** [comment]
Also, the description editor's textarea (Admin > Catalog > Products - editor) has too small height.

**Comment by saosangmo** [comment]
> Also, the description editor's textarea (Admin > Catalog > Products - editor) has too small height.

That textarea will auto grow when you fill your description. It is one of better UX things of CKEditor 5.

**Comment by ProjectMyst** [comment]
condor2 what did you change it to and what file to get it to work again?

**Comment by condor2** [comment]
> condor2 what did you change it to and what file to get it to work again?

> #10955
