### ISSUE TITLE
Session expire default.php and store settings

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#10958]
**What version of OpenCart are you reporting this for?**
4.0

If now in 4.0 you can set life time session from store settings then this line should not be removed?

https://github.com/opencart/opencart/blob/master/upload/system/config/default.php#L43

**Comment by BuslikDrev** [comment]
$this->config->set('session_expire', $this->config->get('config_session_expire'));

**Comment by condor2** [comment]
So will be the same for customer?
![session_expire](https://user-images.githubusercontent.com/14251939/171168618-2a9428b0-5919-431a-a6ce-01e8d636fe64.png)

**Comment by condor2** [comment]
And config_session_expire is used to delete data entry from session table right?

**Comment by BuslikDrev** [comment]
> And config_session_expire is used to delete data entry from session table right?
```
$this->db->query("DELETE FROM `" . DB_PREFIX . "session` WHERE `expire` < '" . $this->db->escape(gmdate('Y-m-d H:i:s', time())) . "' or  `expire` > '" . $this->db->escape(gmdate('Y-m-d H:i:s', time() + $this->config->get('session_expire'))) . "'");
```
