### ISSUE TITLE
Populate banner area on default installation.

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#10950]
![image](https://user-images.githubusercontent.com/5563341/171050352-e48ca5cc-a1c0-45e1-bf0a-15409b624cc8.png)

It is not an issue, but better to resolve the following.
When in a fresh installation, the banner bar appears without data, and presents an empty bar like look.

```
<div id="carousel-banner-0" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
          </div>
  </div>
```

**Comment by BuslikDrev** [comment]
Version OpenCart?

**Comment by anytizer** [comment]
4.0
