### ISSUE TITLE
correct twig filename

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#10969]
https://github.com/opencart/opencart/blob/2fc4baa4c901e1e1eb19aac52cf5a733b64e494d/upload/admin/controller/sale/returns.php#L359

Perhaps, it should be "returns_"; or otherwise, template not found.

**Comment by anytizer** [comment]
Admin > Sales > Returns page having a trouble.

**Comment by danielkerr** [comment]
yep

**Comment by danielkerr** [comment]
already fixed in master
