### ISSUE TITLE
search feature broken

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#10966]
When searching something from the homepage's search bar:

Exception: Error: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens Error Code : HY093
SELECT COUNT(DISTINCT p.`product_id`) AS total FROM `oc_product` p LEFT JOIN `oc_product_description` pd ON (p.`product_id` = pd.`product_id`) LEFT JOIN `oc_product_to_store` p2s ON (p.`product_id` = p2s.`product_id`) WHERE pd.`language_id` = '1' AND p.`status` = '1' AND p.`date_available` <= NOW() AND p2s.`store_id` = '0' AND ( pd.`name` LIKE '%:0%' OR pd.`tag` LIKE '%:1%' OR LCASE(p.`model`) = :2 OR LCASE(p.`sku`) = :3 OR LCASE(p.`upc`) = :4 OR LCASE(p.`ean`) = :5 OR LCASE(p.`jan`) = :6 OR LCASE(p.`isbn`) = :7 OR LCASE(p.`mpn`) = :8) in __\opencart\upload\system\library\db\pdo.php on line 55

v4.0.0 master branch

**Comment by danielkerr** [comment]
its a pdo issue.

**Comment by TheCartpenter** [comment]
The issue is with the PDO since the number values are improperly sanitized as per the PDO prepare statement needs to handle. In this context, p.model, p.sku, p.upc, p.ean, p.jan, p.isbn, p.mpn does not use a prepared value with single quotes.
