### ISSUE TITLE
Missing column in customers >> customers in back-end

### ISSUE THREAD

**Issue by amaco596** [opencart/opencart#10977]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**
In customers >> customers in back-end there is a filter for IP. Shouldn't it be an equivalent column in customer list?

**Expected behavior**
Add a column for IP in customer list.

**Screenshots / Screen recordings**
![customer1](https://user-images.githubusercontent.com/51860627/171289887-8855341b-ce13-4cc3-9cc9-74b65fb64c7f.jpg)

**Comment by saosangmo** [comment]
If it exists at list view, we have lack of space to present long IPv6 addresses.
