### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by goshkoy** [opencart/opencart#10979]
**What version of OpenCart are you reporting this for?**
4.0.0.0
**Describe the bug**
Im trying to open the demo site for past couple of days but i get error that php 8 is required

**To Reproduce**
1. Go to [ https://demo.opencast.com/install/index.php](https://demo.opencart.com/install/index.php)

**Expected behavior**
I should see the demo of the opencart

**Screenshots / Screen recordings**
<img width="1440" alt="Screenshot 2022-06-01 at 9 30 53" src="https://user-images.githubusercontent.com/7643990/171341792-2a7465f9-440b-4390-9e09-d71c3f81a267.png">

**Server / Test environment (please complete the following information):**
Not applicable

**Additional context**
This is the demo site

**Comment by BuslikDrev** [comment]
Naxuya takie voprosvl zadatvatb?

**Comment by BuslikDrev** [comment]
> i decided to delete the demo to upgrade then found out no php8.1+ installed.

8.0?

**Comment by chongshengdz** [comment]
> > i decided to delete the demo to upgrade then found out no php8.1+ installed.
> 
> 8.0?

it must be

**Comment by FelipoAntonoff** [comment]
I also noticed this, here is the PHP 8 warning.
On my same thing, I need to update maybe move to a container soon :)

This is now PHP 8, good to avoid having stores using very old version of Opencart.

**Comment by danielkerr** [comment]
its back
