### ISSUE TITLE
cannot delete demo products or newly created products

### ISSUE THREAD

**Issue by MacBadger** [opencart/opencart#10986]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**
Cannot delete products on a new install. Both demo products and newly created ones. Can edit and save changes to prudcts and any other aspect of opencart. But cannot delete products.

**Expected behavior**
products delted

**Screenshots / Screen recordings**
n/a

**Server / Test environment (please complete the following information):**
 - VPS
 - Debian 10
 - PHP version 8.1.6
 - chrome, firefox

**Additional context**
n/a

**Comment by condor2** [comment]
https://github.com/opencart/opencart/commit/17f2d092f5f02ae24b88b8b9aa6cefc9119e3078
