### ISSUE TITLE
Unable to delete options

### ISSUE THREAD

**Issue by amaco596** [opencart/opencart#10981]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**
I am unable to delete options, even when I just added it.

**To Reproduce**
1. Go to Catalog >> Options in back-end
2. Add new option
3. Try to delete it
4. Not any feedback at all, and the option is not deleted

**Expected behavior**
Be able to delete options.

**Comment by condor2** [comment]
With latest github version options can be deleted if are not assigned to products
