### ISSUE TITLE
Rename admin directory is not work

### ISSUE THREAD

**Issue by rtmkrlv** [opencart/opencart#10987]
**What version of OpenCart are you reporting this for?**
OpenCart 4.0.0.0

**Describe the bug**
Unable to change admin directory. Files from the old directory are not copied and an error occurs.

**To Reproduce**
1. Install OpenCart 4.
2. Log in to admin panel.
3. Enter new path to **Rename admin directory** and click **Rename**.
4. See error in browser console.

**Expected behavior**
Files from the old directory are transferred to the new directory and the login page of the admin panel opens at the new address.

**Screen recordings**
https://user-images.githubusercontent.com/8701534/171598006-18d2e071-965f-4f55-8596-c00da0656b34.mp4

**Server:**
 - Shared hosting
 - CentOS 7
 - PHP 8.0

**Comment by danielkerr** [comment]
already been reported and fixed
