### ISSUE TITLE
Opencart 4.0.0.0 - Error on Line 7 - upload\catalog\language\en-gb\tool\upload.php

### ISSUE THREAD

**Issue by MarcoMzes** [opencart/opencart#10990]
Opencart 4.0.0.0 

Found 1 occurrence.
upload\catalog\language\en-gb\tool\upload.php
Line   7 -
Error:
$_['<error_filetype>']

Correct:
$_['<error_file_type>']

**Comment by condor2** [comment]
I think same should be for:

entry_file_name
error_file_name

**Comment by condor2** [comment]
@MarcoMzes close this.

**Comment by MarcoMzes** [comment]
OK
