### ISSUE TITLE
Design/css: Toast message too far in the right

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#11007]
![image](https://user-images.githubusercontent.com/5563341/171877597-b6bbb018-fd24-42d5-8cbd-d8f8f8bcf423.png)
On a wide screen, the toast message is printed too far right.

It would be good if it stays within the parent's display boundaries.

**Comment by BuslikDrev** [comment]
<style>#alert{right: 0px !important;}</style>

**Comment by danielkerr** [comment]
only if u resize after its shown

**Comment by danielkerr** [comment]
already fixed. forgot to reference
