### ISSUE TITLE
Eco Tax (-2.00) => Eco Tax (2.00)

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#11006]
https://github.com/opencart/opencart/blob/b8e07ebd2c463402e09a11b1970d746739365c19/upload/install/opencart.sql#L2282

I guess, the name of Tax should not have a minus sign -2.00 in front.
It should be just 2.00 (positive number), because it is being added.

Or, is there a reason for the minus sign?

**Comment by danielkerr** [comment]
no reason. u can remove it if u want

**Comment by danielkerr** [comment]
the tax does not exist
