### ISSUE TITLE
Add these CMS documents by default

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#11010]
![image](https://user-images.githubusercontent.com/5563341/171968336-267b4d05-7216-4c90-9f04-859938916647.png)

Looks like these documents are almost mandatory. So, wouldn't it better to have their template pre-created for the CMS?

**Comment by TheCartpenter** [comment]
It would. Especially linked with the payment and shipping service providers during checkout.

**Comment by danielkerr** [comment]
they are not mandatory.
