### ISSUE TITLE
Resetting Admin Password using PHP code?

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#11017]
Not sure if it is right to ask here, but how can I reset the admin password, programmatically?

I updated oc_user with:

    "password" => password_hash($info["password"], PASSWORD_DEFAULT),

It does not allow me to login with $info["password"].
But, when I generate a password manually and copy/paste the password output to replace the password field, it works.

**Comment by danielkerr** [comment]
$rehash = password_needs_rehash($user_query->row['password'], PASSWORD_DEFAULT);

**Comment by danielkerr** [comment]
its not a q&a
