### ISSUE TITLE
Renamed language definitions due to reserved terms

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#11018]
I noticed on the master branch that the ```text_order_id``` has been renamed to ```text_orders_id``` . I also noticed that ```text_empty``` has been renamed to ```text_no_results``` . Therefore, since the ```return``` terms have all been conformingly renamed to ```returns```, shouldn't all the ```text_return_id``` be renamed as well to ```text_returns_id``` in the meantime?

**Comment by danielkerr** [comment]
no. i have to call it returns as return is a reserved keyword and can not be used as a name for classes, functions, etc..

**Comment by TheCartpenter** [comment]
Correct. However, at this time, ```text_return_id``` language keys is still present in all relative files as ```return``` is a reserved word.
