### ISSUE TITLE
Add entity for array $data

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#11028]
https://github.com/opencart/opencart/blob/11c4bb6c7c8375a76b7a4919d5f19d0dce940202/upload/admin/model/setting/startup.php#L34

example
```
$sql = "SELECT * FROM `" . DB_PREFIX . "startup`";
		$sql .= " WHERE 1 ";
		if (isset($data['filter_status'])) {
			$sql .= " AND `status` = " . (int)$data['filter_status'];
		}
		
```
When replace
https://github.com/opencart/opencart/blob/11c4bb6c7c8375a76b7a4919d5f19d0dce940202/upload/admin/controller/startup/startup.php#L8

`$results = $this->model_setting_startup->getStartups(['filter_status'=>1]);`

And replace
https://github.com/opencart/opencart/blob/11c4bb6c7c8375a76b7a4919d5f19d0dce940202/upload/admin/controller/startup/startup.php#L11
`if ((substr($result['action'], 0, 6) == 'admin/')) {`

**Comment by danielkerr** [comment]
wasting my time its not required!
