### ISSUE TITLE
Is not possible to select *.ocmod.zip files using the extension installer upload file dialog 

### ISSUE THREAD

**Issue by dharmawebstudio** [opencart/opencart#11026]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**

- Browse to extension installer admin page. 
- Click on upload extension button
- File dialog window does not allow to select .ocmod.zip file.  

**Expected behavior**
- Be able to select ocmod..zip files

**Screenshots / Screen recordings**

Consider the following screenshot. Is not possible to select the *.ocmod.zip file.

![Captura de pantalla 2022-06-05 a las 21 11 26](https://user-images.githubusercontent.com/8374245/172067000-a79206e2-ccde-43bc-845e-0cdcd2ef2ce1.png)

**Server / Test environment (please complete the following information):**
 - Google Chrome in Mac OS. Versión 98.0.4758.109

**Comment by dharmawebstudio** [comment]
Not sure if somebody else is facing this issue, but I propose to change on this line: 

https://github.com/opencart/opencart/blob/4.0.0.0/upload/admin/view/template/marketplace/installer.twig#L54

```
accept="ocmod.zip".
```

Needs to be replaced by:

```
accept=".zip".
```

Then check in JS or server side if the file name also contains ".ocmod.zip".

**Comment by stalker780** [comment]
No problem in Windows 10/11, Firefox 101/Chrome 102
Current `accept=".ocmod.zip"` works correctly.

**Comment by stalker780** [comment]
Looks like MacOS file manager does not recognize extensions in input accept property. Only mime types

https://stackoverflow.com/questions/47386981/input-type-file-attribute-accept-not-working-in-safari-on-macbook

https://stackoverflow.com/questions/37357970/safari-doesnt-respect-input-type-accept-extension

**Comment by danielkerr** [comment]
google chrome is fine. seems to be a safari issue which i cannot install on my windows pc. ffs i dont want to start messing around with vm's

**Comment by padaliyajay** [comment]
I have also same issue in my Mac. this issue is confirmed if you are using macOS. no matter what browser you are using.

**Comment by mhcwebdesign** [comment]
This is not an OpenCart bug, but it's an macOS file manager issue, hence it should be reported to https://developer.apple.com/bug-reporting/

Also, be aware that the Safari web browser has quite a few well-known bugs, better to use a proper web browser like Chrome or FireFox.

**Comment by padaliyajay** [comment]
this issue is also in Chrome if you are using macOS.

**Comment by cartbinder** [comment]
Well. Overall it's a mac issue. Not matter the browser. 
@padaliyajay :
Kindly add the fix above. It should be okay then.

**Comment by mklarsen** [comment]
Just testet with all released 4.0.0.0 and  4.0.1.1
and as @dharmawebstudio mentioned 
The https://github.com/opencart/opencart/blob/4.0.0.0/upload/admin/view/template/marketplace/installer.twig#L54
Need to be fixed or changed?

**My fix/solution was changed  accept=".ocmod.zip" TO accept="*.ocmod.zip".**

_I believe the issues should be revisit, and create a better solution or adaptation proposal from issues,
(it's really old-fashioned to blame the browser)_

**Comment by ndeet** [comment]
Can confirm this issue on MacOS no matter which browser. 

If somebody on Windows or Linux can confirm that the change to `*.ocmod.zip` as mentioned by @mklarsen above would be great to have the fix in next release.

**Comment by danielkerr** [comment]
maybe just let it accept all types

**Comment by stalker780** [comment]
This code should work both for Mac and Windows.

It allows only .zip files in system file manager.
After that it checks file extension and alerts if extension is not ".ocmod.zip"

requires {{ error_filetype }} language variable

```
....
        $('body').prepend('<form enctype="multipart/form-data" id="form-upload" style="display: none;"><input type="file" name="file" accept="zip,application/octet-stream,application/zip,application/x-zip,application/x-zip-compressed"/></form>');

        $('#form-upload input[name=\'file\']').trigger('click');

        $('#form-upload input[name=\'file\']').on('change', function () {
            if ((this.files[0].size / 1024) > {{ config_file_max_size }}) {
                alert('{{ error_upload_size }}');

                $(this).val('');
            }
// start check file extension
            if (!String(this.files[0].name).endsWith(".ocmod.zip")) {
                alert('{{ error_filetype }}');

                $(this).val('');
            }
// end check file extension
        });

        if (typeof timer != 'undefined') {
            clearInterval(timer);
        }
....
```

Works with Windows Firefox and Chrome. Can anyone check with Mac and Safari?

**Comment by ahmedyounes** [comment]
upload button crashing google chrome
