### ISSUE TITLE
oc_customer.wishlist obsolete ?

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#11031]
I can't find any references to the DB field **oc_customer.wishlist** in any of the database queries. Is this an an old obsolete field?

It seems that OpenCart uses the DB table **oc_customer_wishlist** instead of the **oc_customer.wishlist** !

This is true for both OpenCart 3.0.x.x and 4.0.0.0 releases.

**Comment by TheCartpenter** [comment]
Please submit a pull request in the opencart-3 where you have identified these queries.

**Comment by condor2** [comment]
@mhcwebdesign  why to be oc_customer.wishlist ?
Is like other database table.. oc_customer_activity, oc_customer_group ...

**Comment by danielkerr** [comment]
i think i put it to a spertate table so that we can get stats and use the wish list for setting up marketing emails
