### ISSUE TITLE
History error when editing an order in back-end

### ISSUE THREAD

**Issue by amaco596** [opencart/opencart#11035]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**
There is wrong count of histories after editing an order in back-end.

**To Reproduce**
1. Go to sales >> orders
2. Edit an existing order
3. Go back to sales >> orders, and view the previously edited order
4. See error in History, for example 'Showing 1 to 3 of 3' when there are actually only two histories

**Screenshots / Screen recordings**
![orders](https://user-images.githubusercontent.com/51860627/172174880-ff12aa8d-5c12-4e92-9141-e22a493e0ede.jpg)

**Comment by danielkerr** [comment]
this is not a fix. u have messed the db up and not past all the order histories.

**Comment by amaco596** [comment]
@danielkerr, I tested it on two different servers, on my computer and on internett. The error was on both servers. This is a fresh installation of OC 4.0.0.0 with only demo data. I didn't mess up any database.
