### ISSUE TITLE
Javascript alert not working anymore

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#11032]
For OpenCart 4.0.0.0 the Javascript **alert** function doesn't work anymore. The **alert** is used in the following templates:

admin/view/template/catalog/download_form.twig
admin/view/template/common/filemanager.twig
admin/view/template/marketplace/installer.twig
admin/view/template/tool/backup.twig
extension/opencart/admin/view/template/dashboard/chart_info.twig
extension/opencart/admin/view/template/dashboard/map_info.twig
extension/opencart/admin/view/template/fraud/ip.twig
extension/opencart/admin/view/template/report/product_viewed.twig

The problem is caused by the **admin/view/javascript/common.js**:

```
// Alert Fade
var alert = function () {
    window.setTimeout(function() {
        $('.alert-dismissible').fadeTo(1000, 0, function() {
            $(this).remove();
        });
    }, 7000);
}

```

Besides this, fading bootstrap 5 alert boxes are quite irritating anyway, they should stay open on the screen until the user decides to close them!

**Comment by TheCartpenter** [comment]
Or, the alert boxes should be displayed in a modal where users could click from a link due to the mount of extensions that could be installed and eventually extend or break the grid's height.

**Comment by mhcwebdesign** [comment]
While modal boxes are indeed useful in many circumstances there are causes where the standard Javascript is still useful. Standard Javascript functions should not not be disabled!

**Comment by danielkerr** [comment]
what about the alert appearing in the center of the page

**Comment by danielkerr** [comment]
i fixed it a few commits ago
