### ISSUE TITLE
Refresh Opencart 4 requirements page

### ISSUE THREAD

**Issue by FelipoAntonoff** [opencart/opencart#11033]
Hello, it would be interesting to update the requirements page for Opencart 4 and maybe separate the information according to the version of Opencart, informing maybe mainly for Opencart 4, 3 and 2.3.0.2.

The page I saw outdated is https://docs.opencart.com/requirements/, it looks like it's focused on Opencart 1.5 or 2.

It would be interesting to suggest the minimum version indicated for the MySQL database, MariaDB and PostgreSQL, as well as the server, OpenSSL and Curl.

I have been using Opencart with Nginx for more than 10 years and it has an excellent performance with it, I would recommend it be added as a suggestion with Apache.

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart.github.io/commit/713e71c68cb7a9b14f5f61ed69bc70d55dcec2b1
