### ISSUE TITLE
Catalog Affiliate is incomplete

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#11038]
**What version of OpenCart are you reporting this for?**
Latest github

**Describe the bug**
When someone try to register as Affiliate, that person is added in database as Customer.
If you change from store settings to manually approve affiliates, there is nothing on Customer approval list to show you if is customer or affiliate.

When you approve there is nothing on Marketplace -->Affiliates

**Comment by danielkerr** [comment]
they have to register as customers before they can become affiliates.
