### ISSUE TITLE
SEO URL language issue

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#11057]
**What version of OpenCart are you reporting this for?**
Latest github

**Describe the bug**
Because is ugly to have an seo url like this

**site_name/en-gb/catalog/desktops/mac/** when should be **site_name/en/catalog/desktops/mac/**

If you change the keword en-gb to en the url will become

**site_name/catalog/desktops/mac/en/** and on home page **site_name/en?route=common/home**

LE. Only on sitemap SEO url is OK **site_name/en/sitemap/**

LE. To work OK, after language is changed in SEO url you need to resave again all categories, products,, informations...

**Comment by danielkerr** [comment]
make sure u add seo keyword to everything.

**Comment by condor2** [comment]
> u can change this manually. its bug because u say it looks ugly

Tell me what other CMS use en_gb in url, when is more OK to have /en/something

And the bug is someone don't like en_gb in URL and is changed to en then SEO for all categories, products will be like this

**/catalog/laptop-notebook/en** when should be like this **/catalog/en/laptop-notebook/**

Clearing Theme, SASS cache will not solve this issue.
To fix this issue you need to edit category Laptops & Notebooks and just Save. After this, now url will become /catalog/en/laptop-notebook/

**Comment by mavelo-llc** [comment]
For anyone else that stumbles onto this old issue...

Easily changed using language editor.

**Store:** Default
**Language:** English
**Key:** language
**Value:** en-gb
**Keyword:** en
**Sort Order:** -2
