### ISSUE TITLE
SQL syntax error in upgrade_3.php

### ISSUE THREAD

**Issue by rgbworld** [opencart/opencart#11056]
**What version of OpenCart are you reporting this for?**
4.0

**Describe the bug**
When running install script for an upgrade, the installer fails after step 2.

Exception: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order MODIFY order_id int(11) NOT NULL'

What section does it affect?
Upgrade installer from OpenCart 3.0.2.0.  MariaDB

**To Reproduce**
Run installer performing an upgrade

**Expected behavior**
I expect installer to move past Step 2.

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - Operating system: AlmaLinux v8.6.0 
 - PHP version: 8.1
 - Browser: FireFox

**Additional context**
Fix by adding backticks to sql query.

File: upgrade_3.php 
Line 93:

Find:
```
$this->db->query("ALTER TABLE " . DB_PREFIX . $table['name'] . " MODIFY " . $result['Column_name'] . " " . $field_query->row['COLUMN_TYPE'] . " NOT NULL");
```

Replace with:
```
$this->db->query("ALTER TABLE `" . DB_PREFIX . $table['name'] . "` MODIFY `" . $result['Column_name'] . "` " . $field_query->row['COLUMN_TYPE'] . " NOT NULL");
```

**Comment by TheCartpenter** [comment]
Yes, confirmed.

**Comment by cgcmart** [comment]
upgrade progress stopped after
Patch 2 has been applied (2 of 8)
