### ISSUE TITLE
Customer history not inserted in database

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#11060]
**What version of OpenCart are you reporting this for?**
Latest github

**Describe the bug**
When you edit a customer and fill something in History then you click on Add History, history is not added

The button action URL is: **admin/index.php?route=customer/customer|save** when should be **admin/index.php?route=customer/customer|addhistory**

Another weird thing after I added 2 Transactions, now if I try again I am get kick out from admin

**Comment by TheCartpenter** [comment]
Try these pull requests:

- https://github.com/opencart/opencart/pull/11069
- https://github.com/opencart/opencart/pull/11068
- https://github.com/opencart/opencart/pull/11067

Logout from the admin, clear your browsing history, close browser, re-open browser and re-login to your OC admin. Try again with these three route locations noticing if that will fix the issue. Additionally, the subscription route and the order info route seem, both, to be the only routes that were addressed correctly. See if that differs from the three pull requests as a result.

More importantly, use the Developers Kit > Console and Network tab while using the add history button. Also check your server error logs in the meantime.

**Comment by condor2** [comment]
I have already written...

The button action URL is: admin/index.php?route=customer/customer|save when should be admin/index.php?route=customer/customer|addhistory

**Comment by condor2** [comment]
Doesn't matter

**Comment by TheCartpenter** [comment]
It does matter. Lower case routes vs. uc routes can be misleading for web servers.

**Comment by condor2** [comment]
> 
> The button action URL is: customer/customer|**save** when should be customer/customer|**addhistory**

**Comment by TheCartpenter** [comment]
addHistory.

**Comment by condor2** [comment]
lol......you still not understand....

**Comment by TheCartpenter** [comment]
I definitely understand the issue. Even though you're suggesting to rename the URL, which is fine, you're still suggesting to use a lower case term while the controller has a capital 'H' in in this case. Please see other TWIG files where this term is applied and you'll notice that the add'History' is properly used as opposed to the customer_form . Furthermore, I have created the pull requests accordingly already.

**Comment by condor2** [comment]
The **Add History** button action (Networktab) URL is: **customer/customer|save** when should be **customer/customer|addhistory**, **customer/customer|addHistory**.....

**Comment by TheCartpenter** [comment]
There you go.

**Comment by condor2** [comment]
One bug is this

https://github.com/opencart/opencart/blob/master/upload/admin/view/template/customer/customer_form.twig#L996

**Comment by TheCartpenter** [comment]
Yes, already updated on the customer_form commit as per: https://github.com/opencart/opencart/pull/11072#issuecomment-1148534684 .

**Comment by condor2** [comment]
The bug still exist...

And I am kick out from admin when try to add Transaction... (like in the first post)

**Comment by TheCartpenter** [comment]
What about the console and logs?

**Comment by condor2** [comment]
> The **Add History** button action (Network tab) URL is: **customer/customer|save** when should be  **customer/customer|addHistory**.....

**Comment by TheCartpenter** [comment]
Just out of curiosity. If you try a page in the OC admin like ... attribute and add an attribute by using the submit button, in the console > network tab, do you still see the main route ending with |save?

**Comment by condor2** [comment]
Yes.

catalog/attribute_group|save

**Comment by TheCartpenter** [comment]
In your phpmyadmin console, do you see the new history row that was added from customer even though the wrong route is showing?

**Comment by condor2** [comment]
Customer history table is empty
And when Add history is pressed it show on Success: You have modified customers

**Comment by TheCartpenter** [comment]
In the customer_form.twig file, if you change:

```$('#form-history').on('submit', function (e) {```

to:

```$('#button-history').on('submit', function (e) {```

Clear your OC cache. Then, try again. Do you see any difference?

**Comment by condor2** [comment]
Same issue.

**Comment by TheCartpenter** [comment]
In customer_form, replace:

```data: $('#form-history').serialize(),```

with:

```data: $('#input-comment').val(),```

Then, see in your addHistory() method from the controller by finding:

```if (!$json) {```

add below:

```print_r($this->request->post['comment']);```

then, below that line, add:

```exit;```

Try again with the button submit and notice if the print_r result will be shown.

**Comment by TheCartpenter** [comment]
Another one I found from the marketplace_info:

```data: 'comment=' + encodeURIComponent($(this).parents('.reply-input-box').find('textarea[name=\'comment\']').val()),```

**Comment by condor2** [comment]
No print_r result

**Comment by TheCartpenter** [comment]
Now, move the print_r line 'above' the:

```if (!$json) {```

line. Then, try again (don't forget to remove the exit line).

**Comment by condor2** [comment]
Same. no print result

**Comment by TheCartpenter** [comment]
@danielkerr: Issue is with customer_form.twig file. Needs further testing.

**Comment by TheCartpenter** [comment]
@condor2: It is now fine to reverse the changes until resolution.
