### ISSUE TITLE
Dupllicated code for Transaction in customer_form

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#11071]
**What version of OpenCart are you reporting this for?**
Latest github

**Describe the bug**
Why is a duplicated code for Transaction ?

1. https://github.com/opencart/opencart/blob/master/upload/admin/view/template/customer/customer_form.twig#L929-L960
2. https://github.com/opencart/opencart/blob/master/upload/admin/view/template/customer/customer_form.twig#L1014-L1045

**Comment by TheCartpenter** [comment]
One indicates that it's for the payment method and another one for the form.

**Comment by condor2** [comment]
And I think can be combined....

**Comment by danielkerr** [comment]
i think some code got messed up
