### ISSUE TITLE
Two twig file with no code

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#11096]
https://github.com/opencart/opencart/blob/master/upload/admin/view/template/sale/subscription_invoice.twig
https://github.com/opencart/opencart/blob/master/upload/admin/view/template/mail/subscription_canceled.twig

And some functions from controller with no code

https://github.com/opencart/opencart/blob/master/upload/admin/controller/mail/subscription.php#L45-L53

**Comment by danielkerr** [comment]
will be added before next release
