### ISSUE TITLE
while creating customer from admin end. it is creating duplicate entry.

### ISSUE THREAD

**Issue by amitkumarqa** [opencart/opencart#11121]
**version 4.0.0.0**

**Describe the bug**
when creating a customer from the admin end. so it is creating a duplicate entry.

**To Reproduce**
1. Go to 'admin panel'
2. Click on 'customers -> customer -> click on add button '
3. after filling in detail and clicking on the save button.
4. return to customer page

**Expected behavior**
should not create duplicate entries.

**Screenshots**

![image](https://user-images.githubusercontent.com/106804569/172848339-b681e6c7-d992-468b-b8ab-0fcf20eaac6b.png)

**Test environment:**
 - Local development?
 - linux
 - PHP version - 8.0.17
 - Apache version- 2.2.41
 - google chrome
 - Version 99.0.4844.82

**Comment by anytizer** [comment]
It might have been already fixed in master branch.
