### ISSUE TITLE
The variant products are not getting the value of the option.

### ISSUE THREAD

**Issue by amitkumarqa** [opencart/opencart#11122]
**version 4.0.0.0**

**Describe the bug**
the variant products are not getting the value of the option.

**To Reproduce**
1. Go to 'add options in the main product -> and then create variants'
2. Click on 'variant product'
3. Scroll down to 'give value in options'
4. not adding to the cart

**Expected behavior**
should get the product options values.

**Screenshots**

![image](https://user-images.githubusercontent.com/106804569/172869351-2bd5efc3-a235-4eaf-ac6d-18aa1878411f.png)

**Test environment:**

    • Local development?
    • linux
    • PHP version - 8.0.17
    • Apache version- 2.2.41
    • google chrome
    • Version 99.0.4844.82

**Comment by danielkerr** [comment]
ok should be fixed with last commit
