### ISSUE TITLE
SMTP Mail

### ISSUE THREAD

**Issue by ProjectMyst** [opencart/opencart#11137]
If you use SMTP for sending mail, you can't make an order in the admin section. When you try to place an order you get an error.

I'm using tls:\\ with port 587

**Comment by TheCartpenter** [comment]
Regarding email settings issues, please address them on the Opencart forum > << Your OC version >> > General Support section.

**Comment by danielkerr** [comment]
hpow u know its a bug?

looks more like the port is wrong

**Comment by ProjectMyst** [comment]
Because I tried with all ports, and it doesn't work with any of them. For example, using tls:// with port 587 works just fine when placing an order through the customers side but it will not work when putting an order through the admin side.

**Comment by TheCartpenter** [comment]
Then, you'd need to contact your host or to request deeper troubleshooting from the OC forum as a custom job. At this point, it's not an OC issue.

**Comment by ProjectMyst** [comment]
Hi

Sorry to be a pain but I'm not getting it, can you please explane why that is, why would it work on example.com/store and not example.com/store/admin

I mean, if it was the port then it wouldn't work full stop. If I customers makes an order over at example.com/store then the order works just fine and the invoice email gets sent out. But if I make an order over at example.com/store/admin for a customer then it will not work and gives me the error! It's clearly nothing to do with my hosting provider.

Would you be able to help me understand so I can try and fix the problem.

Thanks in advance.

**Comment by ProjectMyst** [comment]
So I've done more test and worked it out what the problem is.

If you using SMTP for sending out mail and have extension Anti-Fraud IP enabled, it will not let you make orders through the admin backend but it will work through the customers front end.

**Comment by danielkerr** [comment]
it will change it to what ever status u add there.

**Comment by ProjectMyst** [comment]
There's nothing on the server logs, but on the console:

jquery-3.6.0.min.js:2

GET https://projectmyst.com/store1/admin/index.php?route=sale/order|call&user_token=c308440ca7697b9d0fc5208bc40e1a53&action=sale/order|confirm 500
send @ jquery-3.6.0.min.js:2
ajax @ jquery-3.6.0.min.js:2
(anonymous) @ index.php?route=sale/order|info&user_token=c308440ca7697b9d0fc5208bc40e1a53:3078
dispatch @ jquery-3.6.0.min.js:2
v.handle @ jquery-3.6.0.min.js:2
index.php?route=sale/order|info&user_token=c308440ca7697b9d0fc5208bc40e1a53:3125 
error

Network:

Request URL: https://projectmyst.com/store1/admin/index.php?route=sale/order|call&user_token=c308440ca7697b9d0fc5208bc40e1a53&action=sale/order|confirm
Request Method: GET
Status Code: 500 
Remote Address: 77.68.14.209:443
Referrer Policy: strict-origin-when-cross-origin
content-type: text/html; charset=UTF-8
date: Fri, 10 Jun 2022 15:21:53 GMT
server: nginx
set-cookie: OCSESSID=dae99985b00ad3646003f40e73; expires=Mon, 09-Jul-2136 07:21:52 GMT; Max-Age=3600000000; path=/store1/admin/; secure; SameSite=Strict
set-cookie: currency=GBP; expires=Sun, 10-Jul-2022 15:21:52 GMT; Max-Age=2592000; path=/; SameSite=Lax
strict-transport-security: max-age=15768000; includeSubDomains
x-powered-by: PHP/8.1.6
:authority: projectmyst.com
:method: GET
:path: /store1/admin/index.php?route=sale/order|call&user_token=c308440ca7697b9d0fc5208bc40e1a53&action=sale/order|confirm
:scheme: https
accept: application/json, text/javascript, */*; q=0.01
accept-encoding: gzip, deflate, br
accept-language: en-GB,en;q=0.9,en-US;q=0.8
cookie: OCSESSID=dae99985b00ad3646003f40e73; OCSESSID=dae99985b00ad3646003f40e73; currency=GBP
referer: https://projectmyst.com/store1/admin/index.php?route=sale/order|info&user_token=c308440ca7697b9d0fc5208bc40e1a53
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Microsoft Edge";v="102"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33
x-requested-with: XMLHttpRequest

If I switch Anti-Fraud IP off then I can make an order on the admin backend fine.

**Comment by ProjectMyst** [comment]
I found the log file, it has this error, dose it help.

projectmyst.com] child 1200420 said into stderr: "PHP message: PHP Fatal error:  Void can only be used as a standalone type in /var/www/vhosts/projectmyst.com/httpdocs/store1/extension/opencart/catalog/model/fraud/ip.php on line 4"

**Comment by ProjectMyst** [comment]
Yeah that worked, I don't get error anymore and I can process the order.

**Comment by TheCartpenter** [comment]
@ProjectMyst: Thank you for your feedback. A pull request has now been created.
