### ISSUE TITLE
Can't delete options

### ISSUE THREAD

**Issue by ProjectMyst** [opencart/opencart#11147]
When you select and option(s) to delete and press the delete button, nothing happens on OpenCart 4

![image](https://user-images.githubusercontent.com/8054786/173145260-0e8e4e7a-6c25-4eec-a69c-8c3b40e6f861.jpeg)

**Comment by TheCartpenter** [comment]
Which OC version are you reporting this? In the meantime, check your developers kit > console and network tab as well as your server error logs for error messages.

**Comment by ProjectMyst** [comment]
Sorry, to add that, it's on OpenCart 4

**Comment by ProjectMyst** [comment]
This problem is also present on the demo.opencart.com site.

**Comment by danielkerr** [comment]
@ProjectMyst how would u knopw!~!! dlete is blocked on the demo site!
