### ISSUE TITLE
Switching languages doesn't work if seo_url ON

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#11142]
If earlier the system language was remembered in the session or cookies
`$code = $this->session->data['language'];`
`$code = $this->request->cookie['language'];`
now it is determined by the parameter GET['language']
`$code = $this->request->get['language'];`

But when seo_url is enabled, the parameter  GET['language'] is missing

And therefore
`config_language_id`
and
`config_language`
not initialized correctly

**Comment by TheCartpenter** [comment]
The language controller has been re-worked by Daniel recently. Has the issue been resolved, since?

**Comment by danielkerr** [comment]
just tested and it works fine
