### ISSUE TITLE
All Categories not showing

### ISSUE THREAD

**Issue by ProjectMyst** [opencart/opencart#11148]
The All Categories in mobile view only shows up in index.php?route=product/search&language=en-gb, it doesn't show up on any other page on OpenCart 4

![image](https://user-images.githubusercontent.com/8054786/173145674-3f53db3b-caae-4108-a402-05e0ee359b48.jpeg)

![image](https://user-images.githubusercontent.com/8054786/173145692-4886ddc8-5fef-437c-bf7c-f29e96a1135e.jpeg)

**Comment by danielkerr** [comment]
no ides what ur talking about. the olast few u posted have just been time wasters

**Comment by ProjectMyst** [comment]
$_['text_category']  = 'Categories'; was missing in menu.php but it's been fixed now.
