### ISSUE TITLE
OC4: Admin, Sales, Ortders, Filter: Date added and Date modified cannot be empty

### ISSUE THREAD

**Issue by nmpetkov** [opencart/opencart#11143]
**Version**: Master with latest changes

**Problem**: The input controls for Date added and Date modified are allways not empty, and for this reason filtering is not possible (or is possible for a concrete date only). It is not possible to make them empty.

I guess, it is because moving to data range picker, and the problem can be resolved (http://www.daterangepicker.com/).

Furthermore, it is a problem that is possible to enter only a date, not a range.

![image](https://user-images.githubusercontent.com/628801/173104442-d25c10d2-321c-4926-99a9-ccfe5f38b11d.png)

**Comment by danielkerr** [comment]
they are empty for me. should i guess the page

**Comment by nmpetkov** [comment]
Page Admin, Sales, Orders:
https://demo.opencart.com/admin/index.php?route=sale/order
Filter section of the page.

**Comment by nmpetkov** [comment]
Easiest and sipliest way to resolve the problem is to make inputs type "date" (HTML5), remove class "date" and groups. Works quite well and looks well.
![image](https://user-images.githubusercontent.com/628801/173172774-b9a59a67-b03a-43b8-9532-edbd6bf20ed4.png)

**Comment by rgbworld** [comment]
I am seeing the same pre-filled and required date input fields on:
- Sales > Subscriptions
- Sales > Returns
- Customers > Customers

Using FireFox 99.0.1 (64-bit)
MacOS: 12.3.1

My installation is an upgrade from 3.0.2.0 -> 4.0

**Comment by condor2** [comment]
> they are empty for me. should i guess the page

All from all reports are empty and doesn't work. No popup to select date

**Comment by danielkerr** [comment]
the date is forced to be there.

**Comment by nmpetkov** [comment]
Now is ok enter empry dates.

For possibility to filter orders by dates from/to I created [P11227](https://github.com/opencart/opencart/pull/11227).
