### ISSUE TITLE
Putting order through admin

### ISSUE THREAD

**Issue by ProjectMyst** [opencart/opencart#11156]
If you put an order through the admin backend, when it sends the email to customer, there's no logo  and the view order link has the admin folder on it. The logo link is as <img src"https://projectmyst.com/store1/admin" /> on OpenCart 4.

![image](https://user-images.githubusercontent.com/8054786/173195270-abfd4c6d-727b-4ae7-8193-01c8035a90e1.jpeg)

**Comment by anytizer** [comment]
May be here https://github.com/opencart/opencart/blob/a06173de17c5f9a5515dac6a1f6a3cae922f8dbb/upload/catalog/controller/mail/order.php#L101-L105

You probably do not have store logo in your server configuration.

**Comment by ProjectMyst** [comment]
I do, if I make an order through the customers front end, the logo shows up on the email.

**Comment by ProjectMyst** [comment]
I've only seen this replay, it's really nice that when the community try's to help with issues they get called a dickhead.

The issue isn't with my provider, it's with when you put an order through the admin backend, it doesn't recognise the image src {{ logo }} so it just comes up as <a href="example.com/admin" title=""> it's the same for view order link, it adds /admin/ to the link.

If you didn't think you were better than everyone else, and automatically dismissed every one,  you would see that maybe you don't know everything..

I am a server engineer, and I guarantee you 1000% that it's not the server blocking the image, it's your code!

And lastly, you are a horrible, horrible person.
