### ISSUE TITLE
Home page banner

### ISSUE THREAD

**Issue by ProjectMyst** [opencart/opencart#11157]
If you have a banner with control settings switched on, it breaks the page making it that you can move from left to right on mobile view on OpenCart 4.

![image](https://user-images.githubusercontent.com/8054786/173195424-00f832a6-df7e-4ebd-8868-9e998f4fd19d.jpeg)

**Comment by danielkerr** [comment]
it works on default

**Comment by ProjectMyst** [comment]
This problem is also on demo.opencart.com, so no, it doesn't work in the default.

I'll try to explane better, if control option is set to "yes"

![image](https://user-images.githubusercontent.com/8054786/173258945-c7a49395-debd-4493-83c6-6d8d8cf93845.jpeg)

What ever page has that banner, it makes the page shift from right to left.

![image](https://user-images.githubusercontent.com/8054786/173259196-5fd3982e-1071-45ba-a694-351433cb5908.gif)
