### ISSUE TITLE
Reports > Reports Page nested inside itself

### ISSUE THREAD

**Issue by rgbworld** [opencart/opencart#11154]
**What version of OpenCart are you reporting this for?**
4.0

**Describe the bug**
In the OC Admin area, when I select "Reports" from left navigation then click the "Reports" sub-menu, the "Reports" page is replicated inside itself, including the left navigation menu.

**To Reproduce**
1. Go to Admin > Navigation sidebar
2. Click on 'Reports'
3. There is a sub-menu also named 'Reports'
4. Click the sub-menu 'Reports' item
5.  Notice that the 'Reports' page appears a 2nd time, nested in the current 'Reports' page.

**Expected behavior**
I expect the 'Reports > Reports' page to not contain a copy of itself

**Screenshots / Screen recordings**

![Screen Shot 2022-06-11 at 2 32 28 AM](https://user-images.githubusercontent.com/1319222/173178629-6b2424e9-817f-4bfa-8273-275910c48675.png)

FireFox browser
MacOS

**Additional context**
The left Navigation menu is also replicated inside the nested page.

**Comment by danielkerr** [comment]
clear the cache

**Comment by danielkerr** [comment]
would nioce to know which report

**Comment by danielkerr** [comment]
sees also u forgot to tell me u removed all extensions

**Comment by danielkerr** [comment]
does not happen to normal install 

![image](https://user-images.githubusercontent.com/5079756/173178951-a85d1c3a-aacc-40be-82fc-6d28340b2a74.png)

**Comment by rgbworld** [comment]
Dude, it's just a default upgrade. There's all sorts of broken shit, like missing extensions. I didn't remove them, I just haven't figured out what else went wrong during the upgrade.

Just trying to help by reporting a possible bug. Take a chill pill.

**Comment by condor2** [comment]
> Dude, it's just a default upgrade.

You should have said that first :)

**Comment by rgbworld** [comment]
I should have.
