### ISSUE TITLE
positioning error in template customer_form.twig

### ISSUE THREAD

**Issue by AcacioDuarte** [opencart/opencart#11214]
in template 
admin / view / template / customer / customer_form.twig
line 606 and 607 

error -------------------
    html = '<fieldset id="address-row-' + address_row + '">';
    html += '  <legend>{{ text_address }} ' + (address_row + 1) + ' <button type="button" onclick="$(\'#address-row-' + address_row + '\').remove();" data-bs-toggle="tooltip" title="{{ button_remove }}" class="btn btn-danger btn-sm float-end"><i class="fas fa-minus-circle"></i></button></legend>';

correct -------------------
    html = '  <legend>{{ text_address }} ' + (address_row + 1) + ' <button type="button" onclick="$(\'#address-row-' + address_row + '\').remove();" data-bs-toggle="tooltip" title="{{ button_remove }}" class="btn btn-danger btn-sm float-end"><i class="fas fa-minus-circle"></i></button></legend>';
    html += '<fieldset id="address-row-' + address_row + '">';

**Comment by danielkerr** [comment]
no such code.

please stop posting u are wastin my time

**Comment by AcacioDuarte** [comment]
Hello,
the error I see is the following:

this is my first time using github.com to report bug
my intention is not to waste time but to help
Thanks.
AcácioDuarte

**Comment by danielkerr** [comment]
maybe ur using version 3
