### ISSUE TITLE
Compatible route vs language

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#11213]
```
SELECT * FROM `oc_translation`
WHERE
   `store_id` = '0' AND `language_id` = '1'
    AND (`route` = 'extension/opencart/module/account' OR `route` = 'en-gb')
```

In the translation, is the config language being used as the route name?

Source:
https://github.com/opencart/opencart/blob/a06173de17c5f9a5515dac6a1f6a3cae922f8dbb/upload/catalog/model/design/translation.php#L5

It feels like an error.

**Comment by danielkerr** [comment]
bad coding by [OpenCartAddons](https://github.com/opencart/opencart/commits?author=OpenCartAddons)

https://github.com/opencart/opencart/commit/acbb749891e3de361c6b62173b1e6f54ae07862a

**Comment by danielkerr** [comment]
dumbest thing i have seen
