### ISSUE TITLE
header is not good in template 

### ISSUE THREAD

**Issue by AcacioDuarte** [opencart/opencart#11215]
in catalog / view / template / commom / header.twig

in line 86  not good     <div class="col-md-3 col-lg-4">
                 good  is      <div class="col-md-4 col-lg-4">

in line 96  not good     <div id="header-cart" class="col-md-4 col-lg-3">{{ cart }}</div>
                 good  is      <div id="header-cart" class="col-md-3 col-lg-3">{{ cart }}</div>

**Comment by danielkerr** [comment]
guessing games
