### ISSUE TITLE
Missing code for Refresh button in online.twig

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#11229]
When you click on Refresh/Sync button from Online Report doesn't display nothing.

I don't see any success function
https://github.com/opencart/opencart/blob/master/upload/admin/view/template/report/online.twig

**Comment by TheCartpenter** [comment]
Developers Kit > Console and Network tab. Also check your server error logs.

**Comment by danielkerr** [comment]
this code:

$('#button-filter, #button-refresh')
