### ISSUE TITLE
 Undefined array key "extension"

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#11225]
catalog\controller\common\language.php on line 32

**Comment by ProjectMyst** [comment]
Also, if you go to settings, localisation, languages and press any language to edit, you get this error:

Warning: Undefined array key "extension" in /controller/localisation/language.php on line 223

**Comment by condor2** [comment]
A new field was added/changed in database

**Comment by Berserkir-Wolf** [comment]
I had a similar issue, but mentioning different lines under `controller/localisation/language.php.
I resolved it by running the below against the database in MySQL.
````mysql
ALTER TABLE `opencart`.`oc_language` 
ADD COLUMN `extension` VARCHAR(12) NULL AFTER `status`;
```
