### ISSUE TITLE
[master-today] Install Error message

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11223]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Start install process and got the following error message.

Exception: Error: Unknown column 'image' in 'field list'
Error No: 1054
INSERT INTO `oc_language` (`language_id`, `name`, `code`, `locale`, `image`, `sort_order`, `status`) VALUES(1, 'English', 'en-gb', 'en-gb,en', 'gb.png', 1, 1); in /home/aqq20848/public_html/opencart/opencart-master.sandbox/system/library/db/mysqli.php on line 48

**To Reproduce**
1. Start a new install

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Server
 - Operating system Linux
 - PHP version 8.1
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 101

**Comment by danielkerr** [comment]
dont know who put that stupid thing in
