### ISSUE TITLE
Price problem on Google Base module

### ISSUE THREAD

**Issue by kastoras** [opencart/opencart#11258]
**What version of OpenCart are you reporting this for?**
3.0.7.3

**Describe the bug**
When products feed submitted to Google's merchant center I had problem on price attribute. 
The attribute on the feed was <g:price>10.20</g:price>. 
But in order to be submited corectly the currency needed <g:price>10.20 EUR</g:price>

**Comment by kastoras** [comment]
Hi Khnaz35, thanks for the reply,

I had euro as a default currency and still the problem exists.
![feed_settings](https://user-images.githubusercontent.com/16106654/173312311-d06cef1b-4261-4be3-b1a0-0d82470ea21a.jpg)

After searching in the documentation I found this [here](https://support.google.com/merchants/answer/6324371?hl=en)
![price](https://user-images.githubusercontent.com/16106654/173312726-b157ac73-796b-446e-a61a-8a1792e47f99.jpg)

The feed parced correctly, after i made the currency change(<g:price>10.20 EUR</g:price>)

**Comment by TheCartpenter** [comment]
Just confirmed that on the above ...

**Comment by TheCartpenter** [comment]
It has been added now: https://github.com/opencart/opencart-3/commit/725448e396d93482b592a72b980c1a81dc47ac1e . Therefore, this commit can now be closed.

**Comment by kastoras** [comment]
Great!
 Thanks @TheCartpenter
