### ISSUE TITLE
filter_ after edit

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#11254]
After editing any entity, the filter fields are not filled.

This is because the filter variables are in getList
Example
```
protected function getList(): string {
if (isset($this->request->get['filter_name'])) {
$filter_name = $this->request->get['filter_name'];
} else {
$filter_name = '';
}
```
This code needs to be added to the index() methods

**Comment by danielkerr** [comment]
should i guess the page?

**Comment by danielkerr** [comment]
ahh ok i see what u mean

**Comment by danielkerr** [comment]
cant believe i made this mistake.
