### ISSUE TITLE
Does the database have `pin` column?

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#11287]
Warning: Undefined array key "pin" in __\system\library\cart\user.php on line 22
TypeError: Cannot assign null to property Opencart\System\Library\Cart\User::$pin of type string
in __\system\library\cart\user.php on line 22

Looks like pin was introduced but we perhaps forgot to patch the database.

**Comment by anytizer** [comment]
Sources:

https://github.com/opencart/opencart/blob/master/upload/system/helper/db_schema.php#L6053
https://github.com/opencart/opencart/blob/master/upload/install/opencart.sql

**Comment by danielkerr** [comment]
work in progress

**Comment by danielkerr** [comment]
i have removed all pin references its security code
