### ISSUE TITLE
Page(s) not found

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#11292]
With the current configuration, admin pages result in page not found.

Probable Reason: using user_token or login_token interchangeably.
May be we should use single name, if they have a similar scope.

![image](https://user-images.githubusercontent.com/5563341/173682498-032b3f0d-06fd-456a-95c7-c3cb1a2aa0cd.png)

**Comment by TheCartpenter** [comment]
system/config/admin.php indicates that the startup/error loads before the startup/login which means that the startup/error, during first loads, might never be aware of the user_token's presence until the startup/login completes its task with the common/login to create the user_token in the login() method.

**Comment by danielkerr** [comment]
dont even know which page or how u caused the error. if u not capable of making proper bug reports. u should quite now.
