### ISSUE TITLE
Missing config_address_format_id by design

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#11294]
admin/controller/localisation/address_format.php file:

```if ($this->config->get('config_address_format_id') == $address_format_id) {```

The error_default will never output since the config_address_format_id does not exist by design. Therefore, the default address will still be deleted from the database.

**Comment by danielkerr** [comment]
u mean the config value is missing in the default sql

not by design

**Comment by TheCartpenter** [comment]
If a variable is missing by concept, it is by design.
