### ISSUE TITLE
Error if exist characters that need to be escaped

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#11307]
https://github.com/opencart/opencart/blob/110675c782eab021e3229e99a1f0f04551933947/upload/admin/view/template/catalog/product_form.twig#L1698

`{{ entry_required|e('html') }}`

`$_['entry_required'] = 'O\'Reilly';`

And maybe all the variables in the js code

**Comment by danielkerr** [comment]
there is no back quotes required for entry fiel

**Comment by chulcha** [comment]
This is required for js code
![Screenshot_29](https://user-images.githubusercontent.com/15030612/173782783-952be306-dbb1-41bf-adbd-8a4f4e094f89.png)


with escaped `{{ entry_required|e('html') }}`
![Screenshot_30](https://user-images.githubusercontent.com/15030612/173783173-b4f6b994-6afa-4388-aba0-bd167de34d00.png)
