### ISSUE TITLE
[4.x] New language strings

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#11309]
While it may be good to add new files, functions and variables.
See e.g. https://github.com/opencart/opencart/blob/master/upload/admin/language/en-gb/common/pin.php
But if they belong to a language, it would be really "nice" to inform translators when doing so.
I do not to want to waste my time in searching each and any commit and/or release if new strings are added!

Is it so hard to install a "release management" which handles such tasks?

**Comment by danielkerr** [comment]
im fucking working on it! im doing mulltiplee tasks at once and u keep posting on the issues about the same fucking thing is getting to be harrasment!

**Comment by danielkerr** [comment]
also why u posting issue o0f stuff im clearly working on!

give me fucking time to finish~!

**Comment by osworx** [comment]
Nobody said that you have to do all by yourself only!
Your decision .. we have spoken about such a few times the last years.
And YOU published a non working new version without giving devs and translators the change to test it and add translations ..
