### ISSUE TITLE
[master - today] Install - Delete install folder after install is not working

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11310]
**What version of OpenCart are you reporting this for?**
master 15.06.2022 ~12:00 MEZ
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Install process is working. After login in Administration the dialog to delete Install folder und Move Storage is comming up.
Klick on Delete to delete the install folder is not working.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/173815895-841e9057-bec3-4c65-bd2f-df89d54aa5ec.png)

If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 101.0

**Comment by danielkerr** [comment]
already fixed in master branch

**Comment by pemaier** [comment]
Then after the next step after closing the dialog the following message occure:

Warning: require_once(/home/aqq20848/opencart-master.sandbox/vendor/aws/aws-sdk-php/src/functions.php): Failed to open stream: No such file or directory in /home/aqq20848/public_html/opencart/opencart-master.sandbox/system/vendor.php on line 11

Fatal error: Uncaught Error: Failed opening required '/home/aqq20848/opencart-master.sandbox/vendor/aws/aws-sdk-php/src/functions.php' (include_path='.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/aqq20848/public_html/opencart/opencart-master.sandbox/system/vendor.php:11 Stack trace: #0 /home/aqq20848/public_html/opencart/opencart-master.sandbox/system/framework.php(8): require_once() #1 /home/aqq20848/public_html/opencart/opencart-master.sandbox/system/startup.php(66): require_once('/home/aqq20848/...') #2 /home/aqq20848/public_html/opencart/opencart-master.sandbox/admin/index.php(17): require_once('/home/aqq20848/...') #3 {main} thrown in /home/aqq20848/public_html/opencart/opencart-master.sandbox/system/vendor.php on line 11

**Comment by pemaier** [comment]
sorry was not fast enough)

**Comment by danielkerr** [comment]
i just tested this and its working/. im not here fr a argumnet! ur path looks like a mess

not a support service
