### ISSUE TITLE
Installer changes

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#11316]
What happened with marketplace/installer?

upload() and install() functions have changed a lot.

Installer functionality which allowed installing several packages inside one ocmod.zip is destroyed completely.

Again there is no way to:
1. use random ocmod.zip filename (like extension_v1.5.7.5.ocmod.zip)
2. install several extensions from one ocmod.zip

Last commit where this worked was this one.
https://github.com/opencart/opencart/commit/9b4061e0a24c2b31a27101dbab92fdf3ff5b2bc1

Damn! Again we are going circles with this installer. It was almost ideal in 4.0.0.0

**Comment by danielkerr** [comment]
It can already do multiple packages

**Comment by stalker780** [comment]
@danielkerr No! Multiple packages do not work now.

Please check this test ocmod.zip. It is not a working extension, I have quickly prepared just a test for installer.
[stalker780_test_package_v1.2.3.4.multi.ocmod.zip](https://github.com/opencart/opencart/files/8917484/stalker780_test_package_v1.2.3.4.multi.ocmod.zip)

v4.0.0.0 had some installer bugs that could be fixed, but still it was much more usable than now.
Also multiple packages/extensions structure inside one zip is much more efficient, functional and promising both for customers and developers.

Please! Don't kill this functionality.

**Comment by danielkerr** [comment]
ur not supposed to combine them like that. u can put them all in one extension folder.

im not going to change this

**Comment by BuslikDrev** [comment]
> sadomasochism
![image](https://www.meme-arsenal.com/create/chose?tag=%D0%BD%D0%B5%D0%B3%D1%80&page=20)

**Comment by mhcwebdesign** [comment]
I am afraid I have to agree with some of the points made here with regards to the extension installer:

In particular, the extension name, used by the installer when it creates a folder at

extension/<my-extension>/*

should not be taken from the from the ocmod.zip base file name. Rather, the extension name should be taken from the 'install.json' file, e.g. a new field named code, like in this example:

{
  "name": "Export Import Tool",
  "version": "4.12",
  "author": "MHCWebDesign",
  "link": "https://www.mhccorp.com",
  **"code": "export_import"**
}

**Comment by cgcmart** [comment]
db table columns are confused in table oc_extension and oc_extension_install from opencart.sql and index.json
For instance, opencart.ocmod.zip is a download and upload package, that contains 8 types and 46 extensions.
oc_extension_install table should have install_id 1, download_id 1, name opencart, author opencart, link www.opencart.com.
oc_extension table should have 46 extension ids, 46 extension names, that match 46 codes.

**Comment by mhcwebdesign** [comment]
I am now thinking about writing up a free separate plugin manager for OpenCart which would solve the following issues:

- don't use ocmod.zip basename for extension code
- allow multiple packages to be installed from one ocmod.zip file
- use proper namespaces reflecting the folder structure for extensions
- perhaps also have a dependency management between different packages

**Comment by stalker780** [comment]
@mhcwebdesign You see, all these Daniel's attempts to restrict developers only lead to more shitty extensions, patches, even custom OC branches with more incompatibilities. Because developers will always find a way out, but this does not make a life of customers easier and does not make OC more popular :(

This could be easily avoided. Daniel just needs to pay more attention to extension developers advises and PRs.

Otherwise OC development looks like a meme: samurai has no goal, only path. Neverending story.

**Comment by stalker780** [comment]
Questions without answers.
- Why not allow OC developers use both tpl and twig? It's just a dozen lines of code in the core.
- Why not allow multiple packages inside ocmod.zip? It's just a dozen lines of code in the core.
- Why not take extension code form install.json? It's just one line of code in the core.
- Why not keep OCMOD in OC4? It's just a hundred lines of code in the core. It is ready and tested for a decade.

**Comment by mhcwebdesign** [comment]
@stalker780: I can understand your frustration. But I think a good plugin manager can easily be written up as a normal OC 4 extension, to be installed and enabled once, and then 3rd party plugins with above mentioned features can be supported.

**Comment by stalker780** [comment]
@mhcwebdesign That's bullshit when you need to recite a dependencies list for your extension.
You can only imagine, every OC agency will release their own OCMod, VQMod, Extensions manager, Events fixer, etc and require it for their extensions. LOL

**Comment by mhcwebdesign** [comment]
@stalker780: 

> Why not allow OC developers use both tpl and twig?

I have already an extension which supports tpl as well. And I wrote up an alternative twig engine which directly translates from twig to the final HTML output at near-native PHP speed, no need for interim files.

No framework is perfect, but I think a few useful extensions can make a difference:
- plugin manager
- better twig engine
- override engine
- maybe OCMOD

**Comment by stalker780** [comment]
@mhcwebdesign Basically, I don't care which way OC4 will go anymore. For me it is enough of VQMod manager. With it I can build any extension and any core fixes I need, even make my own OC4 build with one extension. This is enough for me right now. 
But in the future I plan to move to another platform. I am tired of this. There is no light in this tunnel.
