### ISSUE TITLE
[master - today] Install process - Rename Admin has no function

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11311]
**What version of OpenCart are you reporting this for?**
master today ~ 13:37 MEZ

**Describe the bug**
After the install process works correct I logged in to the Admin.
After Login a window got up to delete the install folder (the delete is not working - may your change was not on the server)

Then I changed the storgae path (sorry fo the path but I thought you want a reliable test also for multiple shops per account installations)
to /public_storage/opencart/opencart-master.sandbox/
(the install process seems to filter / and . so the path is not built. (I changed by hand and it is working)

Then I changed the name for the admin to admin1 and nothing happens....
If I see a the file system then I can see that there is the new folder with an empty file config.php.

**Screenshots / Screen recordings**

![image](https://user-images.githubusercontent.com/10166095/173823672-35c2a3d5-593c-4b53-8c85-e40e872759e3.png)

If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
i dont know where ur getting ur master from but clearly not in the right place

**Comment by Locxion** [comment]
can confirm this aswell...
if you enter a new directory name like admin_folder it creates this folder and places an empty config file in it but the old admin folder still remains

**Comment by pemaier** [comment]
This problem is fixed in master repository and is working as expected.
