### ISSUE TITLE
[master] Guest Checkout - Shipping and Payment Method no reaction

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11324]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
I was doing an order and at the checkout I filled in the required information.
After I tried to choose the shipment and payment method nothing was possible to choose and the refresh was not working.

**Screenshots / Screen recordings**![image](https://user-images.githubusercontent.com/10166095/174153699-b1a677a7-5aa3-4604-890a-2981bce90c39.png)

**Comment by pemaier** [comment]
When alredy logged in then the checkout looks like this:
![image](https://user-images.githubusercontent.com/10166095/174161749-2228cf53-1bd4-4c13-807f-bbcfdbbe4b3c.png)

**Comment by danielkerr** [comment]
maybe u added a product that reuires subscription or download

**Comment by pemaier** [comment]
I don't changed payment and/or shipping settings and I also didn't change any product settings till now.
(In the screenshot you can also see the left side of the form moved to the right.)

**Comment by pemaier** [comment]
After some tests it seems to be a diffrent behavior of Google Chrom and FireFox to display the form fields.
With Firefox the display of the fields is not correct.
Tested on a hosted platform Linux 8.1 with local windows and linux (no relevance) and Chrom and Firefox 101.0.1
Same results on demo.opencart.com

**Comment by mhcwebdesign** [comment]
I can confirm that, just tested the guest checkout on the **demo.opencart.com** with Firefox 101 on a Linux machine, and I am unable to select shipping or payment method.

Even worst, when using Chrome  102.0.5005.115, I am not even able to add a product such as 'Canon EOS 5D' with 'select=red' option to the cart in the first place. The Chrome console log shows this for the checkout/cart|add:

`{"success":"Success: You have added <a href=\"https:\/\/demo.opencart.com\/index.php?route=product\/product&amp;language=en-gb&amp;product_id=28\">HTC Touch HD<\/a> to your <a href=\"https:\/\/demo.opencart.com\/index.php?route=checkout\/cart&amp;language=en-gb\">shopping cart<\/a>!"}
`

Yet the cart stays empty!

It looks like there is still a lot of Ajax calls and jquery triggers to be sorted out here!

**Comment by danielkerr** [comment]
![image](https://user-images.githubusercontent.com/5079756/174390195-9115c86f-9345-4fdd-96f9-6f36b3e8b485.png)

**Comment by danielkerr** [comment]
ok seems to be an issue with firefox. WTF!

**Comment by danielkerr** [comment]
maybe because the demo has been listed as unsafe.

**Comment by danielkerr** [comment]
works fine for local host and normal web sites.

**Comment by danielkerr** [comment]
most of this guysa bugs hes reported are bull shit. hes posting about stuff happing on the demo

**Comment by danielkerr** [comment]
there could nbe othe reraqsons like hes not set the mail smtp sstuff up
