### ISSUE TITLE
[4.0.0.0] Namespaces should reflect the underlying folder structure

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#11326]
In most programming languages, or in most major projects, the namespace closely reflects the underlying folder structure.

However, in OpenCart 4.0.0.0 this is currently only true for core classes, but not for extensions.

For example, given an extension file 'xyz.php' located in folder

'extension/foo/admin/controller/module' 

OpenCart 4 currently expects the class 'xyz' to use the namespace 

'Opencart\Admin\Controller\Extension\Foo\Module'.  

It should really use the following namespace:

'Opencart\Extension\Foo\Admin\Controller\Module'

In summary: The system/engine/action.php should use something like this for translating from a given route to a fully qualified class name:

```
	protected function getClassAndMethodFromRoute($registry) {
		// Translate a route to a class name and method.
		// The namespace used is closely related to the underlying folder path.
		//
		// Examples (where <application is 'Admin' or 'Catalog'):
		//
		// route 'tool/backup|history' translates to
		// class 'Opencart\<application>\Controller\Tool\Backup'
		// method 'history'
		//
		// route 'extension/foo/module/my_module|delete' translates to
		// class 'Opencart\Extension\foo\<application>\Controller\Module\MyModule'
		// method 'delete'
		//
		$route = $this->route;
		$pos = strrpos($route, '|');
		if ($pos===false) {
			$method = 'index';
		} else {
			$method = substr($route, $pos + 1);
			$route = substr($route, 0, $pos);
		}
		$parts = explode('/',$route);
		$application = $registry->get('config')->get('application');
		if ((count($parts) >= 3) && ($parts[0]=='extension')) {
			$parts = array_merge(
				['opencart'],
				array_slice($parts,0,2),
				[$application,'controller'],
				array_slice($parts,2)
			);
			$path = implode('/',$parts);
		} else {
			$parts = array_merge(['opencart',$applicatiion],['controller'],$parts);
		}
		$class = str_replace(['_', '/'], ['', '\\'], ucwords($path, '_/'));
		return [$class,$method];
	}

```

**Comment by danielkerr** [comment]
yes thats the great feature of autoloaders

**Comment by mhcwebdesign** [comment]
Daniel, the current usage of namespaces in your extensions is simply confusing, and does not follow common programming conventions of namespace usage. Just take a look at the system/storage/vendor to see how others, like symfony, scssphp, etc are doing it. OpenCart 4.0.0.0 still isn't suitable for live sites anyway because of many other bugs, hence we still have a chance to get it right with the namespace usage.

**Comment by danielkerr** [comment]
write a guide. they do have structure

**Comment by mhcwebdesign** [comment]
I can see your structure, in fact, I have successfully ported our Export/Import tool to OC 4.0.0.0.


All I am saying is that an extension  class such as

'**extension/foo/admin/controller/module**/bar.php'

should use a namespaced class name reflecting the underlying folder structure:

Opencart\\**Extension\Foo\Admin\Controller\Module**\Bar

instead of the currently used

Opencart\Admin\Controller\Extension\Foo\Module\Bar
