### ISSUE TITLE
Order - No code required

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#11330]
https://github.com/opencart/opencart/blob/2c10247de9af4c97484623f596d759e42704d848/upload/admin/controller/sale/order.php#L1261

see pre_action

```
		$pre_actions = [
			'startup/setting',
			'startup/customer',
			'startup/currency',
			'startup/tax',
			'startup/application',
			'startup/extension',
			'startup/startup',
			'startup/event'
		];
```
The order action is set as in the CATALOG

**Comment by danielkerr** [comment]
until u start explaining issues properly im not wasting my time guessing!
