### ISSUE TITLE
Admin can't login from administration page after fresh installation 

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#11334]
https://github.com/opencart/opencart/blob/13697b4b066aeaba81281ff2a316999e6af14aac/upload/admin/controller/common/authorize.php#L121

Error log:
Exception:  Error: Could not call registry key model_user_user!
File: /system/engine/controller.php
Line: 25

**Comment by TheCartpenter** [comment]
It's still under development for that method.
