### ISSUE TITLE
how to combine duplicate custom_field name with value opencart version 3038?

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#11335]
how to combine duplicate custom_field name with value opencart version 3038?
admin=>order info=>Account Custom Fields
![combine](https://user-images.githubusercontent.com/30888843/174494469-009dd7f6-e6c3-4b09-8606-6703a7336c77.jpg)

before combination:
Account Custom Fields
color yellow
color green
color red
image 3ba9557e23ecb68b0152683e2623dd72907bdfff
image MPX2102AP.jpg
size big
size small
after combination, the chart will show like:
Account Custom Fields
color: yellow,green,red
image: 3ba9557e23ecb68b0152683e2623dd72907bdfff, MPX2102AP.jpg
size: big, small
how to do it?

**Comment by TheCartpenter** [comment]
Please post this request on the OC forum.

**Comment by danielkerr** [comment]
post here 
https://github.com/opencart/opencart-3
