### ISSUE TITLE
[master] Admin Customer address edit

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11345]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
I wanted to edit a customer address in the administration and it seems that there is the same problem with the first name.

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Customers'
3. Scroll down to 'the customer you like to edit'
4. Click edit
5. Goto to tab Address
6. See the error 

**Expected behavior**

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/174844023-d4c0f1a3-51d8-474e-9c66-4001d0591fce.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] **FIREFOX**
 - Version [e.g. 22] 101.0.1

**Comment by danielkerr** [comment]
i think morelike problmx with firefox update

**Comment by danielkerr** [comment]
thjats was already fixed in master

**Comment by danielkerr** [comment]
dont start reporting issues in comments
