### ISSUE TITLE
Administrators can't log into store using customer details

### ISSUE THREAD

**Issue by plotonic-nz** [opencart/opencart#11342]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**
Administrators can not log into the store using customer details.

What section does it affect?
Frontend

**To Reproduce**
1. Login as Admin User in the backend
2. Go to Customers Section
3. Choose any Customer. From the action Column for that customer Log into Store.

**Server / Test environment**
 - Local development
 - Xxamp
 - PHP 8.1.6
 - Apache 2.4.53
 - Browser(s) tested with Firefox, Chrome, Microsoft Edge

**Error Message Produced**
```
Warning: Undefined array key "address_id" in xampp\htdocs\storename\catalog\controller\account\login.php on line 212
TypeError: Opencart\Catalog\Model\Account\Address::getAddress(): Argument #1 ($address_id) must be of type int, null given in xampp\htdocs\storename\catalog\model\account\address.php on line 28
```

**Reason Why**
Line 212 `$address_info = $this->model_account_address->getAddress($customer_info['address_id']);` 
in file catalog\controller\account\login.php

`$customer_info['address_id']` does not exist in the array of customer details looked up.

**Possible Solution**
`$this->customer->getAddressId()`

Adjust line 212 in catalog\controller\account\login.php 
from `$address_info = $this->model_account_address->getAddress($customer_info['address_id']);`
to `$address_info = $this->model_account_address->getAddress($this->customer->getAddressId());`

**Comment by plotonic-nz** [comment]
**Disregard** this, it looks like this was already fixed.

**Comment by pemaier** [comment]
I confirm it it working with the default store BUT not for additional stores (store 1, store 2, ...)

**Comment by danielkerr** [comment]
already tested muti store and works fine. @[pemaier](https://github.com/pemaier) stop posting u are wasting my time.
