### ISSUE TITLE
[master] Report - Sales Report with TypeError

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11347]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
Opening Sales Report show error.
TypeError: Opencart\System\Library\Cart\Currency::format(): Argument #1 ($number) must be of type float, null given, called in /home/aqq20848/public_html/opencart/master/extension/opencart/admin/controller/report/sale_order.php on line 156 in /home/aqq20848/public_html/opencart/master/system/library/cart/currency.php on line 24

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Reports - Reports choose Sales Report'

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/174863392-571685a0-99fd-45af-8169-d592e0926a05.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 101.0.1

**Comment by danielkerr** [comment]
![image](https://user-images.githubusercontent.com/5079756/174880059-d3ecfe33-78f6-4c77-86cc-82937b4e9c7c.png)
works fine for me! im not playing guessing games

**Comment by pemaier** [comment]
Problem is solved. Thank you.
