### ISSUE TITLE
[master] Checkout as logged user

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11344]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
Location of the user data in checkout is to far right an under other fileds like payment and shipping.

**To Reproduce**
1. Go to 'admin and login'
2. Click to 'customers'
3. Scroll down to 'the user you choose and login to the store e,g. default'
4. Click on the menu Camera and buy a Camera
5. Click to see the Shopping Cart
6. Click right on the bottom to Checkout the you get the view on the screenshot

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/174837118-0d06dfde-75b2-4f97-afe5-d52b39d689b1.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] **FIREFOX**
 - Version [e.g. 22] 101.0.1

**Comment by pemaier** [comment]
Additional Information: This is a regitered user without an address in the db.

**Comment by danielkerr** [comment]
![image](https://user-images.githubusercontent.com/5079756/174880479-7dce00bb-bc91-43ba-9a93-f7f93ecffd55.png)

**Comment by danielkerr** [comment]
Additional Information: This is a regitered customer without an address in the db.

thats better
