### ISSUE TITLE
Version 4.0.0 Extension Installer Not working

### ISSUE THREAD

**Issue by serhatkaya** [opencart/opencart#11367]
**What version of OpenCart are you reporting this for?**
4.0.0

**Describe the bug**
Extension installation not working.

**To Reproduce**
1. Go to 'Extensions > Installer'
2. Click on 'Upload button and select extension to upload.'
3. See error

`{"error":"Zip file could not be opened!"}`

You can see that error in the response developer console > network after the upload request.

Nothing happens visually, programmatically as well.

You can find extension zip attached.

**Expected behavior**
Extensions installs successfully.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? web server
 - Operating system Linux Ubuntu (Server) - Mine Windows 10
 - PHP version 8
 - Apache version unknown
 - Browser(s) tested with chrome
 - Version 4.0
[themesetting.ocmod.zip](https://github.com/opencart/opencart/files/8985815/themesetting.ocmod.zip)

**Comment by Dacogetul** [comment]
Its about mysql error when install DB:
Exception: Error: Index column size too large. The maximum column size is 767 bytes.
Error No: 1709
CREATE TABLE `oc_category_description` ( `category_id` int(11) NOT NULL, `language_id` int(11) NOT NULL, `name` varchar(255) NOT NULL, `description` text NOT NULL, `meta_title` varchar(255) NOT NULL, `meta_description` varchar(255) NOT NULL, `meta_keyword` varchar(255) NOT NULL, PRIMARY KEY (`category_id`,`language_id`), KEY `name` (`name`) ) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; in D:\wamp64\www\test\butic\system\library\db\mysqli.php on line 48

**Comment by danielkerr** [comment]
works for me and many others

**Comment by danielkerr** [comment]
the file wont work on the latest version., thats why we changed the to 4

**Comment by mhcwebdesign** [comment]
@serhatkaya

Your extension is an OCmod XML modification file. OCmod isn't supported by OpenCart 4 anymore. You'll have to use event handlers.

**Comment by Dacogetul** [comment]
Try with MySQL 8.0.28 and php 8.1.6....after that most closet issue

dum., 26 iun. 2022, 20:09 Daniel Kerr ***@***.***> a scris:
