### ISSUE TITLE
Api Security issue

### ISSUE THREAD

**Issue by Aks8578** [opencart/opencart#11398]
**What version of OpenCart are you reporting this for?**
Opencart 4

**Describe the bug**
Anyone can add product into cart by just calling route = api/sale/cart|add and sending product_id as post.

**Expected behavior**
It should verify the api key first then do the required action otherwise show error.

**Comment by danielkerr** [comment]
if ($route !== 'api/login' && !isset($this->session->data['api_id'])) {
				$json['error'] = $this->language->get('error_permission');
			}

should stop this

**Comment by danielkerr** [comment]
FFS shot myself in thew foot!
