### ISSUE TITLE
Bug with cart page shipping estimator when multiple shipping options within 1 shipping method

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#11401]
The cart page estimator does not work properly when there is more than 1 shipping rate within a shipping method. To reproduce, you can set up multiple rates for the same geo zone in Weight Based Shipping, add a product to your cart, then use the cart page shipping estimator. You will see that only the first option can be selected. 

I believe this is because all of the options share the same "id" attribute in their label. This fix seems like it works:

```
IN:
/extension/opencart/catalog/view/template/total/shipping.twig

REPLACE (LINE 99):
if (json['shipping_method'][i]['quote'][j]['code'] == '{{ shipping_method }}') {
  html += '<input type="radio" name="shipping_method" value="' + json['shipping_method'][i]['quote'][j]['code'] + '" id="input-shipping-method-' + i + '" checked/>';
} else {
  html += '<input type="radio" name="shipping_method" value="' + json['shipping_method'][i]['quote'][j]['code'] + '" id="input-shipping-method-' + i + '"/>';
}

html += '  <label for="input-shipping-method-' + i + '">' + json['shipping_method'][i]['quote'][j]['title'] + ' - ' + json['shipping_method'][i]['quote'][j]['text'] + '</label>';

WITH:
if (json['shipping_method'][i]['quote'][j]['code'] == '{{ shipping_method }}') {
  html += '<input type="radio" name="shipping_method" value="' + json['shipping_method'][i]['quote'][j]['code'] + '" id="input-shipping-method-' + json['shipping_method'][i]['quote'][j]['code'] + '" checked/>';
} else {
  html += '<input type="radio" name="shipping_method" value="' + json['shipping_method'][i]['quote'][j]['code'] + '" id="input-shipping-method-' + json['shipping_method'][i]['quote'][j]['code'] + '"/>';
}

html += '  <label for="input-shipping-method-' + json['shipping_method'][i]['quote'][j]['code'] + '">' + json['shipping_method'][i]['quote'][j]['title'] + ' - ' + json['shipping_method'][i]['quote'][j]['text'] + '</label>';

```

**Comment by eturerer** [comment]
namespace Opencart\Catalog\Controller\Startup;

class Cart extends \Opencart\System\Engine\Controller {
    public function index(): void {
        if (!isset($this->session->data['shipping_address']['address_id'])) {
            $this->load->model('localisation/common');
            $this->session->data['shipping_address'] =  $this->model_localisation_common->getAddress();
        }

        if (!isset($this->session->data['payment_address']['address_id'])) {
            $this->load->model('localisation/common');
            $this->session->data['payment_address'] = $this->model_localisation_common->getAddress();
        }

        if (!isset($this->session->data['shipping_methods'])) {
            // Shipping methods
            $this->load->model('checkout/shipping_method');
            $data['shipping_methods'] = $this->model_checkout_shipping_method->getMethods($this->session->data['shipping_address']);

            // Store shipping methods in session
            $this->session->data['shipping_methods'] = $data['shipping_methods'];

            if (!isset($this->session->data['shipping_method'])) {
                //  if (count($this->session->data['shipping_methods']) == 1) {
                $this->session->data['shipping_method'] = current(current($this->session->data['shipping_methods'])['quote'])['code'];
                //  }
            }
        }
    }
}

////
config 

// Actions
$_['action_pre_action']  = [
	'startup/setting',
	'startup/session',
	'startup/language',
	'startup/seo_url',
	'startup/customer',
	'startup/language',
	'startup/currency',
	'startup/tax',
	'startup/application',
	'startup/extension',
	'startup/startup',
	'startup/marketing',
	'startup/error',
	'startup/event',
	'startup/cart',	
	//'startup/sass',
	'startup/maintenance',
];

**Comment by danielkerr** [comment]
seems working for me

![image](https://user-images.githubusercontent.com/5079756/183303971-07eb6384-45ed-4605-9630-bdeb7e142d6f.png)

**Comment by danielkerr** [comment]
ok i see what u mean
