### ISSUE TITLE
Variant product unable to override option values

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#11417]
**What version of OpenCart are you reporting this for?**
OpenCart 4 Master branch (as of July 2, 2022 15:25)

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Variant product with missing options

**To Reproduce**
1. Create and edit a variant product off an master product which has a select type option
2. Click on 'Option' tab
3. Enable select option
4. There is no way to override master product option values
5. And the frontend page of the variant product page doesn't show the option at all! 

**Expected behavior**

Expected to be able to override the option values for a variant product

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Apache/2.4.41 (Ubuntu) on a localhost
 - Operating system: Linux Mint 20.3 xfce
 - PHP version:  8.1.7 
 - Apache version: 2.4.41
 - Browser(s) tested with [e.g. chrome, safari - if applicable]: Firefox
 - Version 102.0

**Comment by mhcwebdesign** [comment]
Hi Daniel, does your recent fix (see https://github.com/opencart/opencart/issues/11122) cover this issue, too?

**Comment by danielkerr** [comment]
yes
