### ISSUE TITLE
Admin order page doesn't not show any plugin tabs

### ISSUE THREAD

**Issue by NTsvetkov** [opencart/opencart#11428]
**What version of OpenCart are you reporting this for?**
Version 4.0.0.0

**Describe the bug**
In the Admin -> Order page -> Order history, no plugin tabs are shown.

**To Reproduce**
1. Make an order
2. Open it in the admin side
3. Scroll down to Order history
4. No aditional plugin tabs are shown

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/9739074/177100095-e5fb54da-b648-4ba7-a357-90916ff133cd.png)

**Server / Test environment (please complete the following information):**
N/A

**Additional context**

It seems that the path is incorrectly formed in `adminpath/controller/sale/order.php` controller, row 969:

```php
if ($extension_info && $this->user->hasPermission('access', 'extension/' . $extension_info['extension'] . '/payment/' . $extension_info['code'])) {
    $output = $this->load->controller('extension/payment/' . $order_info['payment_code'] . '|order');
```
It should be:
```php
if ($extension_info && $this->user->hasPermission('access', 'extension/' . $extension_info['extension'] . '/payment/' . $extension_info['code'])) {
    $output = $this->load->controller('extension/' . $extension_info['extension'] . '/payment/' . $order_info['payment_code'] . '|order');
```

Same in `adminpath/controller/sale/subscription.php` row 492

Best regards

**Comment by danielkerr** [comment]
$extension_info = $this->model_setting_extension->getExtensionByCode('payment', $order_info['payment_code']);

all ready gets the info u need

**Comment by NTsvetkov** [comment]
Thank you! 

https://github.com/opencart/opencart/blob/master/upload/admin/controller/sale/subscription.php#L556 Here needs update too.

**Comment by NTsvetkov** [comment]
@TheCartpenter fix this, please.
