### ISSUE TITLE
Javascript alert still not working!

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#11435]
The alert function still doesn't work, please **do not** use this in the common.js:

```
var alert = function () {
	console.log("alert function entered");
    window.setTimeout(function () {
        $('.alert-dismissible').fadeTo(1000, 0, function () {
            $(this).remove();
        });
    }, 7000);
}

$(document).on('click', 'button', alert);

```

I just tested it in the admin backend at _System > Maintenance > Backup/Restore_ for uploading a large file.

Either the alert function has to be fixed, or better, it should be renamed to something else, to leave the standard Javascript alert function alone!

**Comment by eturerer** [comment]
var alertfn = function () {
	console.log("alert function entered");
    window.setTimeout(function () {
        $('.alert-dismissible').fadeTo(1000, 0, function () {
            $(this).remove();
        });
    }, 7000);
}

$(document).on('click', 'button', alertfn);

**Comment by danielkerr** [comment]
ok renamed function. did not realise that was the issue.
