### ISSUE TITLE
Cannot delete products, missing form="form-product" attribute inside delete button

### ISSUE THREAD

**Issue by anthonyaxenov** [opencart/opencart#11432]
Version 4.0.0.0

**To Reproduce**
Just open product list, check some of them and press trash button. After prompt nothing will happen.

**Expected behavior**
Products you checked in table should be removed after positive answer.

Problem is that `form="form-product"` is missed in delete button declaration.

![image](https://user-images.githubusercontent.com/46676248/177163194-2c3cdbd5-0314-48a6-834a-e6e63f3de6a6.png)

Check:
1. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>
2. choose red trash `<button>`
3. RMB -> Edit as HTML
4. insert `form="form-product"` after `<button` 
5. <kbd>Ctrl</kbd>+<kbd>Enter</kbd>
6. select some products, press trash button and OK. They will be removed.

**Comment by mhcwebdesign** [comment]
This already appears to be fixed in the latest master branch.

**Comment by anthonyaxenov** [comment]
Yep, indeed
https://github.com/opencart/opencart/blob/master/upload/admin/view/template/catalog/product.twig#L9

I hope next version will be released soon because master branch seems to be very unstable now.
