### ISSUE TITLE
Cannot get orders from the webshop API

### ISSUE THREAD

**Issue by zeyadAbouShanab** [opencart/opencart#11438]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**
A clear and concise description of what the bug is:
I am trying to use OpenCart 4 API in PHP but I can't figure out how to get a token properly and how to make API calls. The documentation is written in Python, so I'm not even able to get a token for authentication.

What section does it affect?
API

**To Reproduce**

**Expected behavior**
I managed to get a token for earlier versions using the below code:

```
$post = [
    'username' => 'Username',
    'key' => 'key',
];

$ch = curl_init('http://localhost/index.php?route=api/login');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post);

$response = curl_exec($ch);

curl_close($ch);
echo $response;

?>
```
But after I get the token I don't know how to do the actual calls to get the orders and other stuff because there is no documentation for PHP.

In the new version (4.0.0.0) this code gets me an HTML response with a not found page. So does anyone know how to do proper calls in php in the new or old versions. It would be really helpful if there is any documentation in PHP for the new or old versions.

Thanks in advance!

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by TheCartpenter** [comment]
You will also need CURLOPT_POST set to true in your parameters. In the meantime, while the ?> is no longer required at the end of a PHP file since ages, what does print_r states when pulling the response from your API request?

**Comment by danielkerr** [comment]
try CURLOPT_USERPWD

**Comment by danielkerr** [comment]
ok just tested and it does work. ill post some example code.

**Comment by danielkerr** [comment]
`$curl = curl_init();

// Gets the latest information from opencart.com about news, updates and security.
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($curl, CURLOPT_HEADER, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 30);
curl_setopt($curl, CURLOPT_TIMEOUT, 30);
curl_setopt($curl, CURLOPT_POST, 1);
curl_setopt($curl, CURLOPT_POSTFIELDS, $request_data);

$response = curl_exec($curl);

$status = curl_getinfo($curl, CURLINFO_HTTP_CODE);

curl_close($curl);

if ($status == 200) {
	$api_token = json_decode($response, true);

	print_r($api_token);

	if (isset($api_token['api_token'])) {
		$session_id = $api_token['api_token'];

		echo $session_id;
	}
}`

**Comment by danielkerr** [comment]
then

```
$url = 'http://localhost/opencart-master/upload/index.php?route=api/sale/order.load&language=en-gb&store_id=0&order_id=1';

$curl = curl_init();

curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($curl, CURLOPT_HEADER, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 30);
curl_setopt($curl, CURLOPT_TIMEOUT, 30);
curl_setopt($curl, CURLOPT_POST, 1);
curl_setopt($curl, CURLOPT_POSTFIELDS, $request_data);
curl_setopt($curl, CURLOPT_COOKIE, 'OCSESSID=' . $session_id);

$response = curl_exec($curl);

curl_close($curl);

echo $response;
```
