### ISSUE TITLE
Loading libraries from a extension folder

### ISSUE THREAD

**Issue by dmitriyzhuk** [opencart/opencart#11441]
**to reproduce**
here is an example:
[https://github.com/stasdrvn/extension_library](https://github.com/stasdrvn/extension_library)

1. Library is stored in `extension/download_manager/system/library/d_simple_html_dom.php`
2. Library namespace is `Opencart\System\Library`
3. We are trying to load this library in extension controller `extension/download_manager/admin/controller/download_manager.php`

And we are getting 
```
Exception: Error: Could not load library d_simple_html_dom! in `/Applications/MAMP/htdocs/opencart.loc/system/engine/loader.php on line 192`
```
**only solution now**
4. In case we include library file like it works:
```php
if (!class_exists('d_simple_html_dom')) {        
        include_once DIR_OPENCART . 'extension/download_manager/system/library/d_simple_html_dom.php';
}
```
**better solution**
is it possible `not to include` it and still call the library we have in `extension/quick_order/system/library` inside `extension/download_manager controller`

this would make the code much cleaner

**Comment by danielkerr** [comment]
Libraries are shar ed accross both admin and catalog so its just

$this->load->library('extension/download_manager');

**Comment by danielkerr** [comment]
im going too make it so system goes to the main system/library folder. seems silly having it in multiple places. hard too share across multiple extensions.

**Comment by dmitriyzhukcoso** [comment]
But still under  its own extension folder like a third-party extension would,  or you mean move it to the root/system/library folder when extension is installed?

**Comment by mhcwebdesign** [comment]
> im going too make it so system goes to the main system/library folder. seems silly having it in multiple places. hard too share across multiple extensions.

But what if 2 or more extensions contain a library class each which happen to have the same name but are really different in functionality?

**Comment by dmitriyzhukcoso** [comment]
Yeah, having it’s own separate folder protects the system from having conflicts 

Отправлено с iPhone

**Comment by mhcwebdesign** [comment]
Personally, I'd like to have 3rd party extension use this folder structure:

extension/<ext-1>/system/library/foo.php
extension/<ext-2>/system/library/foo.php
....

Even if both ext-1 and ext-2 were to introduce a library class named '**Foo**' (but possibly with different purposes) it won't create any confusion. They should be loaded via

`$this->load->library('extension/<ext-n>/foo')
`

And, of cpurse I'd still like to see the usage of proper namespaces based on the underlying folder structure :)

**Comment by danielkerr** [comment]
it will go into the library folder

**Comment by mhcwebdesign** [comment]
> it will go into the library folder

Why? How will you handle duplicate conflicts? Why can't an extension be completely located in its own separate folder?

**Comment by danielkerr** [comment]
ok fine
going to separate ones after talking with [dmitriyzhukcoso](https://github.com/dmitriyzhukcoso)

**Comment by danielkerr** [comment]
i just need to sort out helpers being loaded

**Comment by danielkerr** [comment]
after speaking with [dmitriyzhukcoso](https://github.com/dmitriyzhukcoso) it seem u guys would like to upload multiple extensions in a single zip. so once this is done will do another release.

**Comment by mhcwebdesign** [comment]
> after speaking with [dmitriyzhukcoso](https://github.com/dmitriyzhukcoso) it seem u guys would like to upload multiple extensions in a single zip. so once this is done will do another release.

That's good news, thank you.

One quick question: Since each extension has its own folder within the 'extension' folder, why are all the extension's files and/or paths also listed in the DB table 'extension_path'? If an extension gets re-installed it just deletes all its old files and then writes its files into its folder again, quite simple as that. Or am I missing something here?

**Comment by danielkerr** [comment]
[mhcwebdesign](https://github.com/mhcwebdesign) yes its just storeing the paths in case uninstall but also can search through the paths using sql.

i;m closing this as there is now a way to uploaded mutiple extensions via stystem/storage/marketplace

**Comment by mhcwebdesign** [comment]
> 
> i;m closing this as there is now a way to uploaded mutiple extensions via stystem/storage/marketplace

Just looked at your code 2 days later, still can't see any way to upload multiple extensions from one zip-file.
Is it still on your to-do list?

**Comment by danielkerr** [comment]
check her under system

https://github.com/opencart/examples/tree/main/oc_theme_example
