### ISSUE TITLE
[master] Post install process security

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11445]
**What version of OpenCart are you reporting this for?**
master - today
**Describe the bug**
The process is working well -thank you- exept the storage folder is not accepting sub-folders.
Subfolder is gettng filtered ot and the last folder name in the string is used as folder name in the defined folder.

home/account/    master/storage
home/account/    version/storage 
is installed in the same folder. home/account/storage 

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 102.0.0

**Comment by danielkerr** [comment]
can not replicate
