### ISSUE TITLE
How to change cart price in cart library by event.

### ISSUE THREAD

**Issue by VikassWebkul214254** [opencart/opencart#11442]
how to apply events in the library. Want to change the subtotal amount and go to checkout with this amount.

**Comment by cartbinder** [comment]
I don't think the event system can work on the system library cart events. It's hard to update extensions to OC4 with just an event-based system.

**Comment by VikassWebkul214254** [comment]
also,  event is not working into opencart subtotal extension. Does it have another solution?

**Comment by mhcwebdesign** [comment]
You could write event handlers for the models which the $this->cart->getSubTotal() calls.

**Comment by stalker780** [comment]
@mhcwebdesign 
> You could write event handlers for the models which the $this->cart->getSubTotal() calls.

Are you serious? Write events for all possible extensions models and controllers which may use `cart->getSubTotal()` ?

**Comment by mhcwebdesign** [comment]
From what I can these are the only classes using the `$this->cart->getSubTotal()` call:

catalog/controller/checkout/confirm.php
catalog/model/marketing/coupon.php
catalog/controller/api/sale.php
extension/opencart/catalog/model/shipping/free.php
extension/opencart/catalog/model/total/coupon.php
extension/opencart/catalog/model/total/handling.php
extension/opencart/catalog/model/total/low_order_fee.php
extension/opencart/catalog/model/total/sub_total.php

Personally, I am going to use the Override Engine (https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=8588) which I am planning to port to OpenCart 4, as part of a new plugin manager (the latter will also sort out the namespace chaos and allow multiple extensions to be installed in a single zip file, amongst other features).
