### ISSUE TITLE
Adding filters to products and categories

### ISSUE THREAD

**Issue by ProjectMyst** [opencart/opencart#11449]
Adding filets to categories or products, it will only look up the first 5. Please see attached.

As you can see, I have a filters named "New", "Used", "PlayStation 5", none of this will show up on when you enter them in the filters input filed.

![image](https://user-images.githubusercontent.com/8054786/177976250-a54aa84c-d6a0-4c9e-aeab-badbea943cd9.gif)

**Comment by danielkerr** [comment]
qwhy don't you just type playstation 4

**Comment by ProjectMyst** [comment]
I did type PlayStation 4, I also typed New and Used but they don't come up. As you can see from the gif image, I'm typing the name but they are not coming up. I know it will only show the first 5, but when you start typing any other ones, it's meant to fetch them but it isn't. Please create 6 filets on your demo site and then try to add the 6th filter that you added to a product and then you'll see the issue.

**Comment by ProjectMyst** [comment]
It sort of works but limites to 5 filets per filter group, anything over that it will not fetch. I believe that the following needs to be changed for it to work correctly, I tested it and it works as it's meant to with the following changes.

From:
`$sql .= " AND fd.`name` LIKE '" . $this->db->escape((string)$data['filter_name'] . '%') . "'";`

To: `$sql .= " AND fd.`name` LIKE '" . $this->db->escape('%' . (string)$data['filter_name'] . '%') . "'";`

**Comment by danielkerr** [comment]
![image](https://user-images.githubusercontent.com/5079756/178012501-cb8ea340-a2d6-466f-b7d0-5b9568935636.png)

**Comment by danielkerr** [comment]
![image](https://user-images.githubusercontent.com/5079756/178012602-38e2e34c-cddd-4b02-861c-2316adbfeae4.png)

wasting my time entering the products to test

**Comment by ProjectMyst** [comment]
I did enter the filter value, I'm not an idea as you seam to think I am. You can say what ever you want but you wrong, and it doesn't work correctly. You only entered 5 filters and the first 5 filters it fetches but anything over that it doesn't work correctly. The code needs to be changed as follows for it to work as it's meant to. If you want I can make a video to show you as send you the link for the video..

From:
$sql .= " AND fd.name LIKE '" . $this->db->escape((string)$data['filter_name'] . '%') . "'";

To: $sql .= " AND fd.name LIKE '" . $this->db->escape('%' . (string)$data['filter_name'] . '%') . "'";
