### ISSUE TITLE
[master] Multistore - Add to cart option based from grid list not working

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11443]
**What version of OpenCart are you reporting this for?**
master - today
**Describe the bug**
Product add to cart in store1 menu grid view list is not working.
Normally as in the store default the user should be guided onto the product page. Here happens nothing.
(default store is working well)

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/177789697-cc564a45-4903-47db-aa79-09abeaba63af.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 102.0.0

**Comment by mhcwebdesign** [comment]
It's not a browser problem, because it works fine with Firefox 102.0.0 on Linux. Just tested it with the latest master branch.

**Comment by mhcwebdesign** [comment]
You got a wrong formaction:
https://store1.nettwork.ru/opencart/master.demo?route=checkout/cart|add&language=en-gb

It should probably be this:
https://store1.nettwork.ru/opencart/master.demo/en-gb?route=checkout/cart|add

Please re-post on the OpenCart forum for support.

**Comment by pemaier** [comment]
Difference from the stores is the link of the button Add to Cart
default store: formaction="https://nettwork.ru/opencart/master.demo/en-gb?route=checkout/cart|add"
store1:           formaction="https://store1.nettwork.ru/opencart/master.demo?route=checkout/cart|add&amp;language=en-gb"

**Comment by pemaier** [comment]
I can finalize the problem descrition in that way 
SEO settings off - it is working
SEO settinge on - it not working
(in the default store it is working in each way)
