### ISSUE TITLE
Currency refresh - ECB bug

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#11453]
**What version of OpenCart are you reporting this for?**
latest github

<b>Warning</b>: DOMDocument::loadXML(): Opening and ending tag mismatch: meta line 1 and head in Entity, line: 1 in <b>\extension\opencart\admin\controller\currency\ecb.php</b> on line <b>76</b>

<b>Warning</b>: DOMDocument::loadXML(): Opening and ending tag mismatch: img line 1 and div in Entity, line: 1 in <b>\extension\opencart\admin\controller\currency\ecb.php</b> on line <b>76</b>

<b>Warning</b>: DOMDocument::loadXML(): Opening and ending tag mismatch: br line 1 and p in Entity, line: 1 in <b>\extension\opencart\admin\controller\currency\ecb.php</b> on line <b>76</b>

<b>Warning</b>: DOMDocument::loadXML(): Opening and ending tag mismatch: p line 1 and div in Entity, line: 1 in <b>\extension\opencart\admin\controller\currency\ecb.php</b> on line <b>76</b>

<b>Warning</b>: DOMDocument::loadXML(): Opening and ending tag mismatch: img line 1 and div in Entity, line: 1 in <b>\extension\opencart\admin\controller\currency\ecb.php</b> on line <b>76</b>

<b>Warning</b>: DOMDocument::loadXML(): Opening and ending tag mismatch: div line 1 and body in Entity, line: 1 in <b>\extension\opencart\admin\controller\currency\ecb.php</b> on line <b>76</b>

<b>Warning</b>: DOMDocument::loadXML(): Premature end of data in tag div line 1 in Entity, line: 2 in <b>\extension\opencart\admin\controller\currency\ecb.php</b> on line <b>76</b>

<b>Error</b>: Call to a member function getElementsByTagName() on null in <b>\extension\opencart\admin\controller\currency\ecb.php</b> on line <b>84</b>

**Comment by mhcwebdesign** [comment]
Yes, we are getting the same error on some of our sites. Instead of returning an XML response after the **curl_exec** call, it returns a security check page (see attached screenshot). Your PHP warnings are caused by this: `$dom->loadXml($response);` in file **extension/opencart/admin/controller/currency/ecb.php**. 

A quick workaround might be something like this:

```
				$dom = new \DOMDocument('1.0', 'UTF-8');
				set_error_handler(
					function($errno, $errstr, $errfile, $errline) {
						throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
					}, 
					E_WARNING 
				);
				$failure = false;
				try {
					$dom->loadXml($response);
				} catch (Exception $e) {
					$msg = "Currency rates refresh failure: '".$e->getMessage()."'";
					$this->log->write( $msg );
					$failure = true;
				}
				restore_error_handler();
				if ($failure) {
					// .... log error and do your your error handling of some sort ...
					return;
				}

```
This could probably be improved.

Anyway, the ECB response was this (instead of the expected XML with the rates):
![Screenshot_2022-07-10_15-32-50](https://user-images.githubusercontent.com/2989557/178149296-68498728-62a7-4928-a5fb-bd7ba3ca3c39.png)

**Comment by condor2** [comment]
I think was something with the ECB website.
Now refresh work just fine without changes

**Comment by mhcwebdesign** [comment]
I am glad to hear yours is working again.

However, I am re-opening the issue, for Daniel to take a look at it, because it can happen again anytime. The ECB obviously has some kind of a WAF or captcha for its API, so we need some error handling on the OpenCart end for it.

**Comment by ADDCreative** [comment]
The simplest would probably be something like

```php
$dom->loadXml($response, LIBXML_NOWARNING | LIBXML_NOERROR);

if ($dom !== false) {
  $cube = $dom->getElementsByTagName('Cube')->item(0);

  if ($cube !== null) {
    ...
  } else {
    // log error
  }
} else {
  // log error
}
```

**Comment by TheCartpenter** [comment]
Will have to find an alternative solution here since either ECB and Fixer both shows header results rather than pulling the array or object in the API response ...

**Comment by danielkerr** [comment]
maybe just ge the header code must == 200
