### ISSUE TITLE
[master branch][Image Manager] image folder cannot be delete.

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#11470]
[master branch][Image Manager] image folder cannot be delete.
all use $base is not good, need to improve the code.

**Comment by pemaier** [comment]
Is it possible that in that folder is a file with the name index.html? 
If so it is not possible to delete the folder and that is good. In that way it is possible to have predefined folders in extensions with referendes to images.

**Comment by chongshengdz** [comment]
yes, there is a html file there.
@touch($directory . '/' . $folder . '/' . 'index.html');
the above line should be deleted, so the folder can be deleted.

**Comment by danielkerr** [comment]
just trested and works fine
