### ISSUE TITLE
System>Settings

### ISSUE THREAD

**Issue by inamkhanworldclass** [opencart/opencart#11474]
**What version of OpenCart are you reporting this for?**
4.0.1.0
**Describe the bug**
When you enter details in the settings section of your store it did not get saved.
What section does it affect?
System>Settings
**To Reproduce**
1. Go to 'System'
2. Click on 'Settings'
3. Scroll down to 'Action'
4. Enter Details and see error

**Expected behavior**
All the details you enter in this section for your store should be save
**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.

![image](https://user-images.githubusercontent.com/109755935/180274625-21d42ca2-77e6-47cc-a148-8aaa479d4758.png)

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - Operating system
 - PHP version 8.1
 - Apache version
 - Browser(s) tested with chrome

**Additional context**

**Comment by mhcwebdesign** [comment]
I am unable to reproduce your error. Please provide some more details, especially, what is your exact error message, after doing what exactly?

**Comment by pemaier** [comment]
I am unable to reproduce your error - not in the default and not in an additional store. Works as expected.

**Comment by mhcwebdesign** [comment]
I am still unable to reproduce your error. It works fine with the current master branch. You really need to provide some more details. Besides, there is version 4.0.1.0 of OpenCart, use the original masterbranch code.

**Comment by inamkhanworldclass** [comment]
actually with version 4.0.0.0 I am not even able to delete dummy product
posts. In version 4.0.1.0 products are getting delete but default currency
is not switching to any other country currency with a default value. as I
am from Pakistan so it's not  changing to PKR. and furthermore i am
providing you the video. kindly see that as well... kindly see the attached
video
 2022-07-22 15-05-15.mkv
<https://drive.google.com/file/d/1SKNTwGU5nVVXL7LRXphgqNwWWgnpurxx/view?usp=drive_web>

**Comment by inamkhanworldclass** [comment]
https://drive.google.com/file/d/1SKNTwGU5nVVXL7LRXphgqNwWWgnpurxx/view?usp=sharing

**Comment by mhcwebdesign** [comment]
We leave that to Daniel to deal with it. As it is, nobody is able to reproduce your errors, so something else is wrong or different with your setup.  And without further details, nobody will be able to help you.
