### ISSUE TITLE
[master] Theme activation always default store

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11479]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
After installing a theme on a shop with several stores it only enable the theme at default store and it doesn't matter which store is getting enabled.

**Expected behavior**
to enable the theme in the store where it is enabled

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/180663594-3913b5ce-ca8e-4926-bf03-cadeeec80f57.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 102.0

**Comment by danielkerr** [comment]
im not responsible got 3rd party themes.
workd fine when i setup a theme

**Comment by pemaier** [comment]
fair enough - It was my mistake to think that the samples are complete)
