### ISSUE TITLE
Upload Button of Extension installer is not work

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#11477]
I have a strange problem with my test.
When I try to install a new ocmod.zip file with the extension on the installation page, the button "upload button" does not appear at all.
I even did this test in file installer.twig:

```
// Upload
$('#button-upload').on('click', function () {
   alert("OK");
    var element = this;
```
This test does not print anything. Jquery is "dumb".
What could be the reason for this?

**Comment by danijelGombac** [comment]
https://github.com/opencart/opencart/blob/3501dbedf5cddea1666b4d7e33b8fc22d95500ba/upload/admin/view/template/marketplace/installer.twig#L51

Should be !$('#button-upload')

**Comment by pemaier** [comment]
for which version are you reporting?

**Comment by pemaier** [comment]
I can confirm that something changed in the last 3-4 days.
The upload button is working well but the install button is not working anymore.
After clicking the install button the button keep green nothing happens. After a refresh it is getting yellow but the extensions are not visible in the Extensions lists.
I tested on the codeline of today.

**Comment by pekka2** [comment]
This is OC 4.0.0.0

**Comment by pekka2** [comment]
In my test, it seems that Javascript doesn't work at all on this installer page.
Even this script doesn't work:
```
<script type="text/javascript"><!--
  alert("OK");
```

**Comment by pekka2** [comment]
This is test page:
https://www.pm-netti.com/oc4000/admin/index.php?route=marketplace/installer&user_token=e66059a7f6960bf9be87986863abbe17

user:open
password:cart

**Comment by pemaier** [comment]
Sorry but it **works as expected!** Only missing permissions for install.
![image](https://user-images.githubusercontent.com/10166095/180648757-360f37cc-e4c7-496c-8a8a-2851bfeabcbc.png)

**Comment by pemaier** [comment]
it seems that something with your installation is wrong.
![image](https://user-images.githubusercontent.com/10166095/180648868-ef2188d9-5909-4b7b-9483-de93496db524.png)

**Comment by pekka2** [comment]
I changed the settings a bit.
I really wonder why it doesn't work for me.
I noticed that the file structure of my extension was slightly different, extension/paytrail/install.json etc. I changed it but the same problem persists. The program saves the zip package to the file system/storage/marketplace, but does not save anything to the database.

**Comment by pekka2** [comment]
Now success!!
Thank you. I had an old zip package, adding a new one did not replace it in the Marketplace directory, but had to be removed manually.
