### ISSUE TITLE
[master] Sales order edit - Quantity calculation

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11472]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A customer orders a product which has stock qty 1
Then a change of the order in the administration is not possible without error of missing stock qty of the item.

**To Reproduce**
1. Go to 'Admin and choose a product and change the qty to 1'
2. go to the frontend and order this product'
3. go back to the admin sales and open the order
4. change the shipping method and make a refresh 
5. then save the order
6. Then you get the error message of missing stock
Also at the product you see the mark of missing stock.

**Expected behavior**
Is is expected that the stock management considers the qty of already ordered items in the present order and also the available items in the stock.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/180197709-14e51d49-7231-4bc0-a31d-59f20ccc772a.png)
**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 102.0

**Comment by danielkerr** [comment]
U HNEED TO VOID THE ORDER FIRST

**Comment by pemaier** [comment]
That is a emergency solution for now but not a permanent solution. 
99% of customers go to the trap that in the ongoing steps he stock management is not correct.

**Comment by danielkerr** [comment]
who fuck do u think u are? u dont have a clue how ecommerce systems work!
