### ISSUE TITLE
4.0.0.0 - extension install

### ISSUE THREAD

**Issue by prodigyrick** [opencart/opencart#11484]
Extensions download, show in the storage, downloads but dont show up in admin panel to install.

**Comment by prodigyrick** [comment]
2022-07-27 5:54:29 - PHP Warning: Undefined array key "package_name"
File: D:\xampp\htdocs\improdigy.com\store\administer\model\setting\extension.php
Line: 38

2022-07-27 5:54:29 - TypeError:  Opencart\System\Library\DB::escape(): Argument #1 ($value) must be of type string, null given, called in D:\xampp\htdocs\improdigy.com\store\administer\model\setting\extension.php on line 38
File: D:\xampp\htdocs\improdigy.com\store\system\library\db.php
Line: 56

**Comment by prodigyrick** [comment]
Everything I download shows in the storage dir inside of htdocs, but never seems to write properly to the db.

**Comment by prodigyrick** [comment]
Its not resolved and no recommendations given?

**Comment by prodigyrick** [comment]
> Everything I download shows in the storage dir inside of htdocs, but never seems to write properly to the db.

[danielkerr](https://github.com/danielkerr) closed this as [completed] What do I do?

**Comment by Khnaz35** [comment]
Try the master branch!
