### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by HostOncilla** [opencart/opencart#11488]
We are unable to sign in as a customer on OpenCart 4.0.1.0

Getting a this error:

Error:  Call to undefined function Opencart\System\Library\Cart\utf8_strtolower() in /var/www/vhosts/yourdomain.com/httpdocs/system/library/cart/customer.php on line 38

The problem seems to be with this part of the code:

$customer_query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "customer` WHERE LOWER(`email`) = '" . $this->db->escape(utf8_strtolower($email)) . "' AND `status` = '1'");

When I change  (utf8_strtolower($email)) to ($email) then it works correctly and I'm able to sign in.

**Comment by mhcwebdesign** [comment]
I think the 
`$this->db->escape(utf8_strtolower($email))` 
should be replaced with this:
`$this->db->escape(\Opencart\System\Helper\Utf8\strtolower($email))`
in your system/library/cart/customer.php on line 38

**Comment by danielkerr** [comment]
yes fixing helpers

**Comment by mhcwebdesign** [comment]
OK, we'll wait until the helper usage has been fixed before reporting any issues on this. 
There might be more files affected by the helper change, other than the system/library/cart/customer.php

**Comment by danielkerr** [comment]
I thought PHP allowed auto loading functions

**Comment by mhcwebdesign** [comment]
> I thought PHP allowed auto loading functions

Not to my knowledge, see e.g. https://stackoverflow.com/questions/4737199/autoloader-for-functions

**Comment by cgcmart** [comment]
Is this issue fixed?
2022-08-14 00:38:42 - Error:  Call to undefined function Opencart\System\Library\Cart\utf8_strtolower() in ../system/library/cart/customer.php on line 39

**Comment by mhcwebdesign** [comment]
> Is this issue fixed? 2022-08-14 00:38:42 - Error: Call to undefined function Opencart\System\Library\Cart\utf8_strtolower() in ../system/library/cart/customer.php on line 39

Yes. Why not look it up for yourself? You'll see that it now uses

$this->db->escape(Helper\Utf8\strtolower($email))

**Comment by cgcmart** [comment]
@mhcwebdesign Did you view /[system](https://github.com/cgcmart/open-repo/tree/master/system)/[helper](https://github.com/cgcmart/open-repo/tree/master/system/helper)/utf8.php Line 25 - 27?
```
function strtolower(string $string) {
	return mb_strtolower($string);
}
```

**Comment by mhcwebdesign** [comment]
> @mhcwebdesign Did you view /[system](https://github.com/cgcmart/open-repo/tree/master/system)/[helper](https://github.com/cgcmart/open-repo/tree/master/system/helper)/utf8.php Line 25 - 27?
> 
> ```
> function strtolower(string $string) {
> 	return mb_strtolower($string);
> }
> ```

Well yes, and as you can see, it has no function named **utf8_strtolower**.
