### ISSUE TITLE
Options in variant products can't be overridden

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#11481]
What version of OpenCart are you reporting this for?
OpenCart 4 Master branch (as of July 25)

What section does it affect?
Variant product with missing options

To Reproduce

    Create and edit a variant product off an master product which has a select type option
    Click on 'Option' tab
    Enable select option
    There is no way to override master product option values
    And the frontend page of the variant product page doesn't show the option at all!

Expected behavior
Expected to be able to override the option values for a variant product

Server / Test environment (please complete the following information):

    Local development? Deployed to a web server? Apache/2.4.41 (Ubuntu) on a localhost
    Operating system: Linux Mint 20.3 xfce
    PHP version: 8.1.8
    Apache version: 2.4.41
    Browser(s) tested with [e.g. chrome, safari - if applicable]: Firefox
    Version 102.0

**Comment by danielkerr** [comment]
yes because variants are pre selected options.
