### ISSUE TITLE
Extension installer/uninstaller issues

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#11487]
There are still a number of outstanding extension installer issues which should be addressed:

1)
The extension installer still uses the extension's basename as the name for extension code, used in the DB table oc_extension_install and as the extension folder name. Instead, it should take the code from the **install.json**, e.g. something like this:

{
  "code": "foo"
  "name": "My Foo",
  "version": "1.2.3",
  "author": "whoever",
  "link": "https://www.foo.org"
}

2)
The extension uninstaller (see admin/controller/marketplace/installer.php function uninstall) should make sure that all references to the extension folder are removed from the database. Simply showing an error message like '**There are nn extensions that need to be uninstalled before this extension can be safely removed!**' isn't good enough. I suggest that at the very least the uninstaller removes all references to its own extension code (folder) from the DB tables oc_extension, oc_extension_install, oc_extension_path, and oc_event. Or even better, allow the extension to provide its own optional **install** and/or **uninstall** function.  

3)
Extension files still have confusing namespaces. For example, an extension file located at **extension/foo/admin/controller/module/bar.php** should use a namespace like **Opencart\Extension\Foo\Admin\Controller\Module** and not **Opencart\Admin\Controller\Extension\Foo\Module**. It is a common practice for namespaces to reflect the underlying folder structure.

**Comment by danielkerr** [comment]
1. only in ur mind!
2. its fine!
3. not possible

**Comment by mhcwebdesign** [comment]
OK, I think I'll write up a separate plugin manager then because quite a few users want a more robust way to handle extensions.
