### ISSUE TITLE
Upgrading to the latest provided master file

### ISSUE THREAD

**Issue by inamkhanworldclass** [opencart/opencart#11486]
**4.0.0.1**

**Describe the bug**
When we upgrade the latest files you've given it gets stuck on patch 2 and it didn't go forward from that point.
What section does it affect?

**To Reproduce**

**Expected behavior**
the upgrade process should be complete.
**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
![image](https://user-images.githubusercontent.com/109755935/181692885-ee477bf5-abac-4903-96a8-364c800f29e9.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
yes im fixing helpers. once done it will work
