### ISSUE TITLE
4.0.0.0 - Marketplace Extension Install

### ISSUE THREAD

**Issue by prodigyrick** [opencart/opencart#11485]
File: "htdocs\xxxx.com\store\admin..\model\setting\extension.php"

Marketplace Extensions download, but never show updated for install. ('package_name' was not ever in $data array)
Resolved by changing:
`package_name` = '" . $this->db->escape($data['package_name'] on line 38 to
`package_name` = '" . $this->db->escape($data['code']

I was able to download multiple packages and install properly as they finally wrote to db and showed up to install.

**Comment by danielkerr** [comment]
its been fixed. try the master branch
