### ISSUE TITLE
[master] New Install - Error: Call to undefined function

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11482]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A new installation
Error: Call to undefined function Opencart\Install\Model\Install\db_schema() in /home/aqq20848/public_html/opencart/master.demo/install/model/install/install.php on line 10

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 102.0

**Comment by Hyperjase74** [comment]
I have exactly the same error.

**Comment by Pur9e** [comment]
comment line 2 (namespace) in general.php, db_schema.php and bbcode.php found in /system/helper/ 
Solved this issue for me. (cfr. i just undid the adjustment in these files after a commit yesterday)

**Comment by Hyperjase74** [comment]
I've had to reinstall files from the latest version, with your changes, I now see:

`Error: Call to undefined function Opencart\Install\Controller\Install\utf8_strlen() in /var/www/html/opencart/upload/install/controller/install/step_3.php on line 318`

**Comment by pemaier** [comment]
After a new install today I got the same error as @Hyperjase74 

But I think we can not concider this now as an error because Daniel is working in that area now. So I'm sure it will be solved soon.

**Comment by Pur9e** [comment]
Indeed, in between my temporary solution comment and @Hyperjase74, several changes were made concerning the utf8.php helper and the namespaces in the other helpers.

**Comment by pemaier** [comment]
I guess it is best to close this now. If the error rise up later I'll make a new one.

**Comment by pemaier** [comment]
Since 3 days no changes in a install error. The current error is as reportrd from @Hyperjase74 
The error from my 1st report is no longer present but is replaced by the following error.
(Reopening as promised)

Error: Call to undefined function Opencart\Install\Controller\Install\utf8_strlen() in /home/..../public_html/opencart/master.demo/install/controller/install/step_3.php on line 318

**Comment by danielkerr** [comment]
i think were ready for a new release.

**Comment by pemaier** [comment]
Sorry to interrupt the step but we are not complete ...

Error: Call to undefined function Opencart\System\Helper\DBSchema\db_schema() in /home/aqq20848/public_html/opencart/master.demo/install/model/install/install.php on line 9

**Comment by Hyperjase74** [comment]
Confirmed @pemaier & @danielkerr  I get the same error:

Error: Call to undefined function Opencart\System\Helper\DBSchema\db_schema() in /var/www/html/opencart/upload/install/model/install/install.php on line 9

For reference I follow the instructions under "Installing OpenCart" from here: https://osnote.com/how-to-install-opencart-on-ubuntu/

The Git URL for the Master Zip file is: https://github.com/opencart/opencart/archive/refs/heads/master.zip
