### ISSUE TITLE
Product Weight and Dimensions Not showing on shipping label Opencart 3.0.2.0

### ISSUE THREAD

**Issue by gunoshah** [opencart/opencart#11491]
Hi Seniors  and @danielkerr,

I was try many way to show product dimension on shipping label page but it's not working. so please help me.

Regards
Guno Shah

**Comment by mhcwebdesign** [comment]
Please use the OpenCart forum for this, it's not an OpenCart bug, see https://forum.opencart.com/viewtopic.php?f=10&t=229273&p=846685#p846685

**Comment by gunoshah** [comment]
not getting a response!
