### ISSUE TITLE
Checkout bugs

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#11496]
**What version of OpenCart are you reporting this for?**
latest github, clean install

**Describe the bug**

After you fill all info on Checkout page as Guest and hit Continue button:

- Bug 1:
A message is displayed:  **Success: Your account has been created!**
But is wrong because is Guest checkout....and not Register checkout

- Bug 2
Confirm Order button is disabled so you need refresh the page and **not to click** again on Continue.

I think Continue button should be removed because for some old customers is not intuitive  to click on Continue then after that Shipping/Payment method will be shown.

**Comment by danielkerr** [comment]
bug 2 is because u did not setup ur mail settings.

**Comment by condor2** [comment]
Before was Mail...now is SMTP and same problem.
Product was Iphone

Tested with Firefox, Chrome

**Comment by danielkerr** [comment]
main smpt all work via google mail.
