### ISSUE TITLE
What strlen . Take back token

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#11493]
https://github.com/opencart/opencart/blob/ebe4f81f2a58e01ee9e1000478444b62d04be14b/upload/extension/opencart/catalog/controller/captcha/basic.php#L10

Take back token

**Comment by HostOncilla** [comment]
captcha doesn't work, captcha code is blank and when you press submit it ignores captcha validation.

![image](https://user-images.githubusercontent.com/8054786/182321345-c644b447-583c-49d7-be45-aa185fec552d.jpeg)
