### ISSUE TITLE
[master] Administration exit error

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11505]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
Install OpenCart 
then go through pre-security steps (not sure if this is required to come to the error)
then click Logout 
after logout this error occur

TypeError: Opencart\System\Library\Session\DB::read(): Return value must be of type array, null returned in /home/aqq20848/public_html/opencart/master.demo/system/library/session/db.php on line 21

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 103.0

**Comment by mhcwebdesign** [comment]
Unable to reproduce. Please provide some details and a clearer description.

**Comment by TheCartpenter** [comment]
See between browsers if the issue persists when logging out with posted screenshots. With the opencart-3 repository, I did encountered deprecated session errors in the past before the issue was fixed with the new startup.

**Comment by pemaier** [comment]
[Here](https://nettwork.ru/opencart/master.demo/admin/) [for the next 6 hours] you can test the behavior:
Login as admin/demo - close  Important Security Notification! - and click logoout
I with the Firefox get this picture.
![image](https://user-images.githubusercontent.com/10166095/183047236-ce90e249-dbbb-4463-a0b9-1d4f621090c0.png)

**Comment by danielkerr** [comment]
can not replicate

**Comment by danielkerr** [comment]
this guy doe snot know how to setup a server properly

**Comment by pemaier** [comment]
Interesting ... what can be done wrong to start the install process enter the data into the install form an click install? I guess not much especially if the shop is working well on one day and on a new install the next day not. Who s to blame the person who is doing always the same install procedure or ... ?

**Comment by pemaier** [comment]
If it helps something has changed within the last week.

**Comment by pemaier** [comment]
In file upload/admin/controller/common/logout.php
in line 7    unset($this->session->data['user_token']); 
is the problem. 
If the line is commented out the error do not occure.

**Comment by TheCartpenter** [comment]
The issue is not with the user token, in this case. Opencart-3 repository still has the unset user_token function as much as the MB in the common/logout controller without showing any errors when people are logging out of their admin sessions and even when refreshing their browser without the need to clear their browsing history since the session libraries were patched on the repository.

**Comment by pemaier** [comment]
I guess it is related to session handling at the new language change in the administration.

**Comment by mhcwebdesign** [comment]
Why is nobody else ever experiencing the same issue?

**Comment by pemaier** [comment]
If it helps here is a screenshot of my db table oc_session
![image](https://user-images.githubusercontent.com/10166095/183308826-91d8f95f-a4b9-4e62-8151-84e48d1956d5.png)

**Comment by mhcwebdesign** [comment]
This screenshot only shows that you are using an extreme long session duration, taken from the system/config/default.php:

`$_['session_expire']       = 999999999;
`
A more reasonable value would be e.g. 1 hour ( = 3600 seconds):
`$_['session_expire']       = 3600;
`
But either way, this is not the reason for your error. You simply must have messed your installation because nobody else can reproduce it.

**Comment by pemaier** [comment]
With the session_expire time you are right for the 2 entries for year 2036 (orginal setting from the opencart.sql)
![image](https://user-images.githubusercontent.com/10166095/183462228-6eec25ef-f5f7-4130-807f-45c62fd5d459.png)

But then there there is a change of the session_expire time during the worktime with exit entries for year 2054 ?

**Comment by pemaier** [comment]
Here is somthing about a similar problem 
[https://stackoverflow.com/questions/10069594/session-handling-in-chrome-and-firefox](https://stackoverflow.com/questions/10069594/session-handling-in-chrome-and-firefox )

**Comment by TheCartpenter** [comment]
@pemaier: I tested the logout action from the opencart-3 repository as I stand corrected from my last input on this commit; since the session engine was fixed, I could not reproduce the issue, either, by deprecation or error message.
