### ISSUE TITLE
Can't upload extensions / ocmod.zip are greyed out 

### ISSUE THREAD

**Issue by DachsbauTV** [opencart/opencart#11503]
**What version of OpenCart are you reporting this for?**
4.0
**Describe the bug**
Upload of extensions

**To Reproduce**
When trying to use the upload in the web interface, I can't choose the ocmod.zip files as they are greyed out (on Mac).
However, even when I force upload them it doesn't work and the error log shows the following:

`2022-08-04 7:00:39 - PHP Warning: Undefined array key "package_name"
File: /customers/0/9/d/dachsbau.club/httpd.www/opencart/admin/model/setting/extension.php
Line: 38

2022-08-04 7:00:39 - TypeError:  Opencart\System\Library\DB::escape(): Argument #1 ($value) must be of type string, null given, called in /customers/0/9/d/dachsbau.club/httpd.www/opencart/admin/model/setting/extension.php on line 38
File: /customers/0/9/d/dachsbau.club/httpd.www/opencart/system/library/db.php
Line: 56

2022-08-04 7:01:26 - PHP Warning: Undefined array key "package_name"
File: /customers/0/9/d/dachsbau.club/httpd.www/opencart/admin/model/setting/extension.php
Line: 38

2022-08-04 7:01:26 - TypeError:  Opencart\System\Library\DB::escape(): Argument #1 ($value) must be of type string, null given, called in /customers/0/9/d/dachsbau.club/httpd.www/opencart/admin/model/setting/extension.php on line 38
File: /customers/0/9/d/dachsbau.club/httpd.www/opencart/system/library/db.php
Line: 56

2022-08-04 10:29:45 - PHP Warning: Undefined array key "package_name"
File: /customers/0/9/d/dachsbau.club/httpd.www/opencart/admin/model/setting/extension.php
Line: 38

2022-08-04 10:29:45 - TypeError:  Opencart\System\Library\DB::escape(): Argument #1 ($value) must be of type string, null given, called in /customers/0/9/d/dachsbau.club/httpd.www/opencart/admin/model/setting/extension.php on line 38
File: /customers/0/9/d/dachsbau.club/httpd.www/opencart/system/library/db.php
Line: 56

2022-08-04 11:34:38 - PHP Warning: unlink(paypal.ocmod.zip): No such file or directory
File: /customers/0/9/d/dachsbau.club/httpd.www/opencart/admin/controller/marketplace/installer.php
Line: 168

2022-08-04 11:46:02 - PHP Warning: unlink(paypal.ocmod.zip): No such file or directory
File: /customers/0/9/d/dachsbau.club/httpd.www/opencart/admin/controller/marketplace/installer.php
Line: 168`

**Server / Test environment (please complete the following information):**
 - web server on one.com
 - Operating system MacOS
 - PHP version 8.1.
 - Apache version (sorry don't know)
 - Browser Opera & Chrome
 - Version 4.0.0.

**Comment by pemaier** [comment]
It is working as expected.
Add in the settings by Server the extension ocmod.zip then it is working.
![image](https://user-images.githubusercontent.com/10166095/182879992-b0693cce-11c7-45c8-9cbf-f924d78aaa4d.png)
![image](https://user-images.githubusercontent.com/10166095/182879470-48e09a42-3768-4412-a73c-7fbf7206b945.png)
after saveing
![image](https://user-images.githubusercontent.com/10166095/182879666-c80e8cc4-64b5-4034-9042-9847d906e5e6.png)

**Comment by cgcmart** [comment]
A question is that "ocmod.zip' is not a robot or user-agent but a file type and transfer format.

**Comment by DachsbauTV** [comment]
It is still not working, after adding the above.

I fi look at the dev-tools in the browser I get this message even with a never before used file:
<b>Warning</b>: unlink(exportimport.ocmod.zip): No such file or directory in <b>/customers/0/9/d/dachsbau.club/httpd.www/opencart/admin/controller/marketplace/installer.php</b> on line <b>168</b>{"error":"File already exist!"}

**Comment by pemaier** [comment]
So now I understand that you like to upload a extension archive - my mistake. For that the settings are not required!
But also in that case I can confirm that this is working in the master. 
It works as expected.
![image](https://user-images.githubusercontent.com/10166095/182899699-dfe5aacf-757e-45fd-aab4-416511962380.png)

**Comment by mhcwebdesign** [comment]
Besides, there is no such file as 'exportimport.ocmod.zip', the extension filename is 'export_import.ocmod.zip'. Have you tested it with the master branch, or did you use OC 4.0.0.0 ?

You may want to open a support ticket with us (we are the author of this extensions) at the OpenCart marketplace. It doesn't appear to be an issue with OpenCart.

**Comment by pemaier** [comment]
I just testet in master branch with the following result:

Twig\Error\LoaderError: Unable to find template "adminxy/view/template/extension/export_import/other/export_import.twig" (looked into: ). in /home/aqq20848/master.demo/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 227

**Comment by DachsbauTV** [comment]
> Besides, there is no such file as 'exportimport.ocmod.zip', the extension filename is 'export_import.ocmod.zip'. Have you tested it with the master branch, or did you use OC 4.0.0.0 ?
> 
> You may want to open a support ticket with us (we are the author of this extensions) at the OpenCart marketplace. It doesn't appear to be an issue with OpenCart.

I did use the 4.0.0. from the website download page. 
It is definitely not a problem with the extension as I have tried 4 different ones now with no success

**Comment by mhcwebdesign** [comment]
> I just testet in master branch with the following result:
> 
> Twig\Error\LoaderError: Unable to find template "adminxy/view/template/extension/export_import/other/export_import.twig" (looked into: ). in /home/aqq20848/master.demo/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 227

Well yeah, there is no 'adminxy' folder anywhere, I am not sure how you got it.

**Comment by DachsbauTV** [comment]
@danielkerr please don't close it. My problem still wasn't solved and @pemaier 's problem has nothing to do with mine

**Comment by mhcwebdesign** [comment]
@DachsbauTV: Please open a proper support ticket on the OpenCart marketplace at
https://www.opencart.com/index.php?route=support/seller&extension_id=17

**Comment by DachsbauTV** [comment]
Again, it is not a problem with the import export extension.
it's a general problem with the way open cart handles ANY extension I am trying to install.

so I don't see a point in opening a support ticket with the realtor of this specific extension.

to be a 100% clear: I've tried the Facebook extension, the paypal extension, the export import extension and a 4th one I can't remember now.and NONE of them would upload.

**Comment by mhcwebdesign** [comment]
@DachsbauTV: Well, nobody else seems to be able to reproduce this issue, so something must have gone wrong with your site. Maybe re-post on the OpenCart forum?

**Comment by danielkerr** [comment]
i recomend using the master version. will be releasing new version soon
