### ISSUE TITLE
method 'review' not exist in product/product

### ISSUE THREAD

**Issue by vkulish04** [opencart/opencart#11501]
to the `$data['pagination']['url']` variable, a method is passed that does not exist in the "product/product" class

https://github.com/opencart/opencart/blob/90b9f67546df4dd8dfb91ecd66dd7802acf790c9/upload/catalog/controller/product/review.php#L34

Should be `'url'   => $this->url->link('product/review|review', 'language=' . $this->config->get('config_language') . '&product_id=' . $this->request->get['product_id'] . `'&page={page}')`

**Comment by danielkerr** [comment]
no idea what ur talking asbout. there is no issue in master branch

**Comment by danijelGombac** [comment]
@danielkerr 

Pagination url in product/review controller

product/product|review

to

product/review|list
