### ISSUE TITLE
How to use event handler to show my extention form in order info page 

### ISSUE THREAD

**Issue by devlearn100** [opencart/opencart#11509]
Hi, 
Opencart 4 removed OCMOD so unable to do file modification, alert way is event handler how to add new form for add tracking information?  

![image](https://user-images.githubusercontent.com/106736666/183103260-332d3fdd-db7b-4c97-8e87-711ac4cf3b0b.png)

**Comment by danielkerr** [comment]
u could do it in the tabs. 

override($route, $args,  $output) {

}

**Comment by nexadomain** [comment]
Hey @danielkerr 
Please make a tutorial for overriding things using the event system.
Also, current developer documentation is too outdated. It is based on OC v2. Please update it.
