### ISSUE TITLE
[master] logs folder permissions

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11508]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
After each new install of OpenCart it is required to change the permissions of the logs folder for the group with additional write permissions. This is required at all of my external hosting providers.
Without this change the error-log is not working.

**Expected behavior**
The error-log is working out of the box because most people will not understand what to do.

**Screenshots / Screen recordings**
This is not working but a standart setting on hosting servers.
![image](https://user-images.githubusercontent.com/10166095/183087523-f8e71491-f764-4bc2-afca-6fcd4d8f7ba8.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 103.0

**Comment by danielkerr** [comment]
i prefer u stop posting stuff. most of the tiume u dont have a clue how to setup a web server

**Comment by pemaier** [comment]
Daniel setup of external servers is not done by me and at different hostings is the same result. 
(I also understand that this annoying)

**Comment by danielkerr** [comment]
Ur full of shit. Wake only u are reporting this rubbish.

**Comment by pemaier** [comment]
... and after your change 30 min. ago it is working. Thank you!
