### ISSUE TITLE
[master] Edit Address - Default Address

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11518]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
This is a minor issue.
It is possible to switch the only one address entry to Default address NO and the entry is get saved.

**Expected behavior**
... I guess it should be not visible if it is not used in that situation or not be switchable to no.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/183940464-061046f6-0102-4382-aa65-bf1e71a90893.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 103.0

**Comment by heron982** [comment]
yeah, i agree

**Comment by heron982** [comment]
i will check it out
