### ISSUE TITLE
checkout/register.twig doesn't look right

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#11513]
Line 16 on the catalog/view/template/checkout/register.twig doesn't look quite right to me:

`<div class="col mb-3{% if customer_groups|length <= 1 %} d-none{% endif %}">
`

Perhaps it's meant to be this:
`<div class="col mb-3{% if customer_groups|length <= 1 %}{{ text_none }}{% endif %}">`
where text_none is to be declared in the catalog/language/en-gb/checkout/register.php:
`$_['text_none'] = 'No customer groups';
`
?

**Comment by danielkerr** [comment]
text_none in class?

**Comment by mhcwebdesign** [comment]
So what exactly do you mean by '**d-none**' ?

**Comment by mhcwebdesign** [comment]
OK, sorry, it's referring to the bootstrap style **d-none** which make sense. 

Never mind, please ignore, it's not an issue.
