### ISSUE TITLE
opencart 3.0.2.0 alipay minssing orders

### ISSUE THREAD

**Issue by luqihangloy** [opencart/opencart#11529]
We have been loyal users of Opencart for many years, but recently, when using opnecart3.0.2.0 Alipay, we found missing orders. We searched for almost all methods to adjust, but we could not change the error of missing orders. Therefore, we sought solutions from the official. We launched use SEO URLs, and the problem still exists!

Hope to get an answer!

Opencart great creative team！

**Comment by nexadomain** [comment]
@luqihangloy Please explain in more detail. It is impossible to understand your issue.

Ps. I am not Opencart Official Team Member.

**Comment by ADDCreative** [comment]
@luqihangloy Best to ask on https://forum.opencart.com/.

**Comment by luqihangloy** [comment]
This bug almost makes Asian Opencart users have some difficulties. Can Opencart official repair it? Or publish a repair method!



Your loyal supporters!

**Comment by mhcwebdesign** [comment]
> This bug almost makes Asian Opencart users have some difficulties. Can Opencart official repair it? Or publish a repair method!
> 
> Your loyal supporters!

Please read the reply at https://github.com/opencart/opencart/issues/11529#issuecomment-1214201872 and re-post it on the forum, providing a clearer description and more details.
