### ISSUE TITLE
Language is not added in localisation

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#11525]
**What version of OpenCart are you reporting this for?**
latest github. clean install

**Describe the bug**
I have made my own language after oc_language_example but after installed from Extensions and Enabled from Extensions->Extensions->Languages, that language is not displayed in Localisation->Languages.

Same problem tested with  oc_language_example  aka German.

**Comment by danielkerr** [comment]
working for me

**Comment by pemaier** [comment]
I get the same result as @condor2 ... no automatic entry in the language list at  System -> Localisation -> Languages.

**Comment by pemaier** [comment]
UPDATE - the automatic entry in the language list at System -> Localisation -> Languages **is working** 
- if the shop is installed 
- once opened System -> Settings -> [Default Store] 
- clicked on SAVE.
