### ISSUE TITLE
Return value must be of type array, null returned in system\library\session\db.php on line 21

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#11524]
**What version of OpenCart are you reporting this for?**
latest github. clean install

**Describe the bug**
After login to admin and you want to logout you will get this error

TypeError: Opencart\System\Library\Session\DB::read(): Return value must be of type array, null returned in system\library\session\db.php on line 21

**Same issue with**: Google Chome, Firefox, Opera

**Comment by condor2** [comment]
https://github.com/opencart/opencart/issues/11505

**Comment by pemaier** [comment]
Problem solved - thank you.
