### ISSUE TITLE
[master] frontend Produkt page - Write a review link without function

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11526]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
On the frontend product page are the links Reviews and Write a review.
Click on the links are without function.

**Expected behavior**
Go to the Review tab

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/184118327-fd561a32-abb6-4e69-b7be-676aa9961b51.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 103.0

**Comment by TheCartpenter** [comment]
What the developers > console and network tab indicates when using those functions on your browser? Since this was also tested with Firefox, can the issue be reproduced with Edge / Chrome? If so, please address those errors from your Developers Kit as well with screenshots.

**Comment by pemaier** [comment]
You can test it with the browswer you like [here](https://nettwork.ru/opencart/master.demo/index.php?route=product/product&language=en-gb&path=33&product_id=31)  and [here](https://demo.opencart.com/index.php?route=product/product&language=en-gb&path=33&product_id=31)

**Comment by mhcwebdesign** [comment]
I can confirm that this error still exists in the newly released OC 4.0.1.0. It should trigger a click event for the element 'a[href=\'#tab-review\']' but it doesn't.
