### ISSUE TITLE
Fixed framework controller events

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#11533]
I think the system/framework.php needs to be fixed and/or improved for properly supporting controller events for its dispatcher. I suggest below dispatcher to be used in **system/framework.php**:

```
...
// Dispatch
while ($action) {
	// Get the route path of the object to be executed.
	$route = $action->getId();

	$args = [];

	// Keep the original trigger.
	$trigger = $action->getId();

	// Trigger the before-events
	$event->trigger('controller/' . $trigger . '/before', [&$route, &$args]);

	// Execute the action
	$result = ($response->getOutput() == '') ? $action->execute($registry, $args) : '';

	$action = '';

	if ($result instanceof \Opencart\System\Engine\Action) {
		$action = $result;
	}

	// If action can not be executed then we return the action error object.
	if ($result instanceof \Exception) {
		$action = $error;

		// In case there is an error we don't want to infinitely keep calling the action error object.
		$error = '';
	}

	// Trigger the after-events, they can further modify the output
	$output = $response->getOutput();
	$event->trigger('controller/' . $trigger . '/after', [&$route, &$args, &$output]);
	$response->setOutput( $output );
}
...
```

This assumes that a controller method, as invoked by the original request, including Ajax calls, always calls
`$this->response->setOutput( .... );
`
which I think is the case here.

**Comment by mhcwebdesign** [comment]
I can't see any commits for this bugfix in the master branch.

The variable **$output** is not being defined or set anywhere in the **system/framework.php** for the trigger
`$event->trigger('controller/' . $trigger . '/after', [&$route, &$args, &$output]);`

**Comment by danielkerr** [comment]
'	public function controller(string $route, mixed ...$args): mixed {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_|\/]/', '', $route);

		// Keep the original trigger
		$trigger = $route;

		// Trigger the pre events
		$result = $this->event->trigger('controller/' . $trigger . '/before', [&$route, &$args]);

		// Make sure its only the last event that returns an output if required.
		if ($result != null && !$result instanceof \Exception) {
			$output = $result;
		} else {
			$action = new \Opencart\System\Engine\Action($route);
			$output = $action->execute($this->registry, $args);
		}

		// Trigger the post events
		$result = $this->event->trigger('controller/' . $trigger . '/after', [&$route, &$args, &$output]);

		if ($result && !$result instanceof \Exception) {
			$output = $result;
		}

		if (!$output instanceof \Exception) {
			return $output;
		}

		return '';
	}'

the code does not need fixing. his above example does

**Comment by mhcwebdesign** [comment]
Daniel, I am talking about the controller events triggered in the **system/framework.php**, not about the ones in the **system/engine/loader.php**, the latter are fine now!

In the **system/framework.php**, the variable **$output** is always undefined, hence passing it as an argument doesn't make sense:
`$event->trigger('controller/' . $trigger . '/after', [&$route, &$args, &$output]);
`
