### ISSUE TITLE
It looks line 39 has not fixed the issue #11488

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#11537]
https://github.com/opencart/opencart/blob/0f2475899188d17f0e9129fa8251de4ca1af9931/upload/system/library/cart/customer.php#L39

2022-08-14 00:38:42 - Error:  Call to undefined function Opencart\System\Library\Cart\utf8_strtolower() in ../system/library/cart/customer.php on line 39

**Comment by mhcwebdesign** [comment]
Please use the latest master branch. It doesn't call **utf8_strtolower** anymore, rather its call **Helper\Uft8\strtolower**

**Comment by cgcmart** [comment]
It is from master branch file.

**Comment by cgcmart** [comment]
> Please use the latest master branch. It doesn't call **utf8_strtolower** anymore, rather its call **Helper\Uft8\strtolower**

Look at line 39, it is clearly refer to the latest.

**Comment by mhcwebdesign** [comment]
No. You aren't using the latest master branch, because the system/library/cart/customer.php now uses **$this->db->escape(Helper\Utf8\strtolower($email))** on line 38, and not **$this->db->escape(urt8_strtolower($email))**.
