### ISSUE TITLE
PHP Warning:  Undefined array key 1 in ../catalog/controller/startup/seo_url.php on line 61

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#11539]
https://github.com/opencart/opencart/blob/0f2475899188d17f0e9129fa8251de4ca1af9931/upload/catalog/controller/startup/seo_url.php#L61

2022-08-14 01:37:30 - PHP Warning:  Undefined array key 1 in ../catalog/controller/startup/seo_url.php on line 61

**Comment by mhcwebdesign** [comment]
What exactly are you doing? Why is nobody having this error?

**Comment by PhamToan** [comment]
i have updated code for those bugs 
https://github.com/opencart/opencart/pull/11609
https://github.com/opencart/opencart/pull/11610

you can copy code and overwrite to files. it will work
