### ISSUE TITLE
TypeError:  Opencart\Catalog\Model\Design\SeoUrl::getSeoUrlByKeyValue(): Argument #2 ($value) must be of type string, null given in ../catalog/model/design/seo_url.php on line 10

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#11538]
https://github.com/opencart/opencart/blob/0f2475899188d17f0e9129fa8251de4ca1af9931/upload/catalog/model/design/seo_url.php#L10

2022-08-14 01:37:30 - TypeError:  Opencart\Catalog\Model\Design\SeoUrl::getSeoUrlByKeyValue(): Argument #2 ($value) must be of type string, null given in ../catalog/model/design/seo_url.php on line 10

**Comment by mhcwebdesign** [comment]
Without further details nobody will be able to reproduce your error. SEO Urls work just fine.

**Comment by danielkerr** [comment]
just make sure

**Comment by PhamToan** [comment]
> Without further details nobody will be able to reproduce your error. SEO Urls work just fine.

try link like you can try link 
youropencart4.com/index.php?route=common/home&sort=pd.name&order=ASC&limit=75&orderreviews[53][text]=anonymous&orderreviews[70][product_id]=70<br/>&orderreviews[70][rating]=5&orderreviews[70][text]=anonymous&orderreviews[167][product_id]=167<br/>&orderreviews[167][rating]=5&orderreviews[167][text]=anonymous&privacy_policy=1
