### ISSUE TITLE
OCSESSID - Session Cookie Value can be modified and hacker can logged to anyone account 

### ISSUE THREAD

**Issue by nexadomain** [opencart/opencart#11532]
**4.0.0**

**Describe the bug**
Opencart stores _Session ID_ in Cookie named `OCSESSID` in plain text.
Users can edit cookie values on the Client Side (Frontend) and change _Session ID._ Thus accessing other accounts by just simply changing cookie value.

**To Reproduce**
1. Open Opencart Website in any _Chromium_ browser(Firefox also works, but the procedure is different),
then start the Developer Tools (in Chrome, `CTRL + Shift + i` )
2. Go to the "Application" Tab -> _Storage_ -> _Cookies_ -> {Website}
3. Find Cookie named `OCSESSID` and change its value (for quick debugging, use any Session ID from DB->Table- 'oc_session')
4. As soon as you change the cookie value, refresh the page, and you logged into another person's account.

**Expected behavior**
Users should not be able to log into other accounts by using this hack.
Hackers can easily access other accounts and steal their data(Order Details, addresses, phone numbers, shopping behavior, etc).
They will use the hacking script to browse through random Session ID, if 'session_id' matches, they will get access to the user's account.

**Screenshots / Screen recordings**
Please refer to [Screen Recording](https://www.youtube.com/watch?v=3ODz-VsPQJw&source=Github)
[Youtube Link: https://www.youtube.com/watch?v=3ODz-VsPQJw](https://www.youtube.com/watch?v=3ODz-VsPQJw&source=Github)

**Server / Test environment (please complete the following information):**
 - Local development & Deployed to a web server
 - Operating system - Windows 11, but can be done with Any
 - PHP version - 8.1 - Browser(s) tested with Chrome 104
 - Opencart Version 4.0.0

**Possible Solution**
Encrypt _Session ID_ before storing it into Cookies and Decrypt Cookie Value before reading _Session ID_ using OC Encryption Library Class. Encrypting Session Cookie value will make it harder for hackers to invade Customer Accounts.

While Storing Session ID
```
$encryption = new \Opencart\System\Library\Encryption;
setcookie($this->config->get('session_name'),  $encryption->encrypt( 'Your ENCRYPTION KEY', $session->getId() ), $option);
```
While Reading Session ID
```
$encryption = new \Opencart\System\Library\Encryption;
if (isset($this->request->cookie[$this->config->get('session_name')])) {
  $session_id = $encryption->encrypt( 'Your ENCRYPTION KEY', $this->request->cookie[$this->config->get('session_name')] );
}
```

Changes required in Files:
1. upload/system/framework.php
2. upload/catalog/controller/startup/session.php
3. upload/catalog/controller/startup/session.php

@danielkerr

**Comment by ADDCreative** [comment]
@nexadomain Encrypting the session ID is pointless and doesn't add any real protection.

**Comment by nexadomain** [comment]
> 

Still, Bare Session ID can be manipulated easily. Every major Framework are encrypting the Session ID and then stores the encrypted data.

It is just my suggestion to encrypt the session id to enhance the security, the final decision will be taken by Opencart's developers only.

**Comment by danielkerr** [comment]
He will be offering his services next. Fuck off. Ur telling smarter people how do their job.

**Comment by mips171** [comment]
How about this situation? A customer of someone running an OpenCart shop gets phished with an HTML+JS email containing a button that sets a known `OCSESSID` to `abcd1234abcd1234abcd1234`. They include a phone number or some other channel to contact. The customer calls the number, believing they are contacting the shop, and the attacker uses social engineering to get the customer to send them the URL they are browsing to, which contains their `user_token`. The attacker is now logged in, and is able to see the user's personal information, and impersonate them on the site. They may place a fraudulent order, having the goods delivered elsewhere to hawk.

Or perhaps imagine a similar scenario where a store employee or admin is the target, rather than a customer, then it is a much larger breach.

These are contrived, but it's easily repeatable, I just tested the flow myself. Yeah you could say "the people who got phished are dumb", but knowing about and yet still refusing to fix this issue is dumber, as it affects both shop owners and customers.

**Comment by ADDCreative** [comment]
@mips171 Regenerating the session ID would stop that. Both when the session ID doesn't match a valid session and on login.

**Comment by danielkerr** [comment]
see its the WHAT IF again! 

how to get the user token on a different domain!

**Comment by mips171** [comment]
> see its the WHAT IF again!
> 
> how to get the user token on a different domain!

That's the thing, you get the user to copy the URL from their browser (containing their token) and send it to you. It's not inconceivable.

**Comment by danielkerr** [comment]
still doesernt work! again im not going into what ifs and wasting my time. i have real bugs to fix

**Comment by mips171** [comment]
This sets the cookie if the target victim's email is hosted on their domain (again not inconceivable, think Exchange server, or something like that, mail.opencart.com). Embed that in an email, then click it
```
<script>
function setCookieAndOpenUrl() {
  // Set the cookie for opencart.com and all its subdomains
  document.cookie = "OCSESSID=abcd1234abcd1234abcd1234; path=/; domain=opencart.com";

  // Open the new URL in a new tab or window
  window.open('https://shop.opencart.com/admin/', '_blank');
}

</script>
</head>
<body>

<button onclick="setCookieAndOpenUrl()">Log In/Reset Password/Sale on Now! -- Sets Cookie and Open URL</button>
```

From there, the user logs in, validating the OCSESSID. Now it's just up to the attacker to use their wits get the user to send them the URL containing their user_token and off you go.

This is trusting the client way too much with a piece of information that is crucial to authenticity, namely `OCSESSID`. 

@ADDCreative regenerating the token upon login should be a good fix for this, is there any plans to action that? I have had a look at session.php, login.php and framework.php, would there need to be any other changes as far as you're aware? I'm still ramping up with the OC code.

**Comment by mips171** [comment]
Has anyone looked at possible denial of service/resource starvation attacks by constantly setting and resetting the cookie? Fuzzing as well? It looks like OCSESSID can be of variable length (minus a few characters from the standard length - for instance deadb33fabcd1234abcd12 was accepted). Not sure yet what else can be done with that.

**Comment by danielkerr** [comment]
> fetched

U don't have a clue and I'm not ur teacher
