### ISSUE TITLE
Mail SMTP Office365 Still not working. 4.0.1.0

### ISSUE THREAD

**Issue by BasicMr** [opencart/opencart#11549]
Hi,

Office365 SMTP is not working. I had this issue also in 3.x
Got it working in 3.x with this code:

```
/system/library/mail/smtp.php

From:
$header .= 'From: =?UTF-8?B?' . base64_encode($this->sender) . '?= <' . $this->from . '>' . PHP_EOL;

To
$header .= 'From: =?UTF-8?B?' . base64\_encode($this->sender) . '?= <' . $this->smtp_username . '>' . PHP_EOL;


From:
$header .= 'Return-Path: ' . $this->from . PHP_EOL;

To:
$header .= 'Return-Path: ' . $this->smtp_username . PHP_EOL;
```

But this is not working in 4.x

**Comment by ADDCreative** [comment]
@BasicMr If your SMTP username is an email address, then Office365 probably has a restriction that you can only send from that address. Change you main email address in the OpenCart settings to match your SMTP username. That what you code effectively does anyway.

Your change would break other email providers that don't use an email address as the SMTP username.

**Comment by danielkerr** [comment]
its not opencarts fault. u need to find what specific special settings or parameters that only Microsoft require.
