### ISSUE TITLE
PHP DateTime class not working at OC 4

### ISSUE THREAD

**Issue by adias** [opencart/opencart#11546]
hi. im trying to use the DateTime class at OC 4 and get the follow error :
---
$datetime = new DateTime();
var_dump($datetime);
---
Error: Class "Opencart\Catalog\Controller\Common\DateTime" not found in /var/www/html/4000/catalog/controller/common/header.php on line 20

tnks [ ]'s

**Comment by PhamToan** [comment]
add 
use \Datetime;

before class xxx line, it will work

**Comment by mhcwebdesign** [comment]
And use event handler, for e.g. trigger **catalog/view/common/header/before** for modifying the header.

**Comment by adias** [comment]
Thanks all !
