### ISSUE TITLE
[OC 4.0.1.0] Misleading success message in guest checkout

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#11544]
Using the guest checkout, filling in the Personal Details and the Shipping Address, and then clicking on **Continue**, and shows a misleading success message: 

**Success: Your account has been created!**

This being a guest checkout, the success message should be something like this:

**Success: Your guest checkout details have been entered!**

**Comment by TheCartpenter** [comment]
```Success: Your guest checkout details has been added!```

**Comment by condor2** [comment]
https://github.com/opencart/opencart/issues/11496
