### ISSUE TITLE
rename alert function in admin/view/javascript/common.js - opencart 4+

### ISSUE THREAD

**Issue by nikto1** [opencart/opencart#11554]
As per title alert function should be renamed.
Actually the  javascript "`alert();`" doesn't work anymore because it has been overwritten in common.js, line 131.

**Comment by mhcwebdesign** [comment]
This issue has been fixed ages ago, use OC 4.0.1.0 or the master branch.

**Comment by danielkerr** [comment]
it was changed

var oc_alert = function () {
