### ISSUE TITLE
$comment variable is not used in alert function

### ISSUE THREAD

**Issue by julioccguimaraes** [opencart/opencart#11551]
- OpenCart 4.0.1.0
- file: catalog/controller/mail/order.php
- function: alert
- variable: $comment
- result: comment is discarded when adding order history

**Comment by mhcwebdesign** [comment]
I think this is related to this issue: https://github.com/opencart/opencart/issues/11519

**Comment by pemaier** [comment]
It is an addition ;) ... but I'm not sure if in the 3.x versions the comment was included in the alert mail.
