### ISSUE TITLE
onclick="return confirm('{{ text_confirm }}');" refer to issue #10865 commit

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#11561]
https://github.com/opencart/opencart/blob/a359105606bfd6816128462ea7e291ba59873b4d/upload/admin/view/template/catalog/product.twig#L9

It looks a typo in all committed files.
Should be:
`onclick="return confirm('{{ text_confirm }}')"`

**Comment by danielkerr** [comment]
thge only difference i seeis the ; at the end. ur taking the piss!
