### ISSUE TITLE
Store access logged in as admin in maintenance mode does not work

### ISSUE THREAD

**Issue by julioccguimaraes** [opencart/opencart#11568]
Store access logged in as admin in maintenance mode does not work

Version: OpenCart 4.0.1.0
PHP: 8.1
Browser: Chrome

**Comment by TheCartpenter** [comment]
Confirmed. Issue reproduced in the opencart-3 repository.

**Comment by mhcwebdesign** [comment]
It works fine for the 3.0.x.x_Maintenance branch.

Might be a more recently introduced issue with newer versions.

**Comment by TheCartpenter** [comment]
I wonder if it's not related with the system/config profiles. I believe this issue is the remaining one on the opencart-3 repository at this time as well.

**Comment by TheCartpenter** [comment]
Found the root cause: https://github.com/opencart/opencart/pull/11871 .

**Comment by danielkerr** [comment]
fixedhttps://github.com/opencart/opencart/commit/b7591852126073c120d0a7a9d7d297121835a6ed
