### ISSUE TITLE
typo: ]; in upload/catalog/model/checkout/order.php line 41

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#11577]
https://github.com/opencart/opencart/blob/7eb34c11b14e075da17fe874bda38f50c41b1032/upload/catalog/model/checkout/order.php#L41

**Comment by danielkerr** [comment]
that code is not int he master branch!
![Untitled-1](https://user-images.githubusercontent.com/5079756/186211390-34b647d2-c6fc-4dea-b93c-4cf88c6121ee.jpg)

**Comment by cgcmart** [comment]
no, line 41 `];` is still in master [opencart/upload/catalog/model/checkout/order.php](https://github.com/opencart/opencart/blob/7eb34c11b14e075da17fe874bda38f50c41b1032/upload/catalog/model/checkout/order.php#L41)

**Comment by danielkerr** [comment]
its appeared now but only after i accepted [TheCartpenter](https://github.com/TheCartpenter) commit

**Comment by cgcmart** [comment]
@danielkerr you are right.
