### ISSUE TITLE
[OC 4.0.1.0] table-responsive don't work at all

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#11576]
table-responsive don't work at all.
please see the photos.
![Screenshot_2022-08-23-02-57-05-035_com android br](https://user-images.githubusercontent.com/30888843/185998364-e0e778a9-27ea-4a62-874c-3a5802ea526f.jpg)
![Screenshot_2022-08-23-02-57-39-417_com android br](https://user-images.githubusercontent.com/30888843/185998376-55dc6114-5004-40b3-8893-3a842cb1ed93.jpg)
![Screenshot_2022-08-23-02-57-14-238_com android br](https://user-images.githubusercontent.com/30888843/185998382-e05eae94-2165-49a6-9c6f-137a841fe1f2.jpg)

**Comment by chongshengdz** [comment]
after testing, all the table-responsive don't work, no matter the catalog (front-end, for example, the product comparison table) or the admin

**Comment by danielkerr** [comment]
ur screen even on a iphone does not go that small

**Comment by chongshengdz** [comment]
> ur screen even on a iphone does not go that small

my phone is android version 12 with 6.67 oled screen.
it is neither too small nor too big in all smartphones.
all tables are not responsive in opencart version 4+, you should test it and fix it.
there won't be any problem in opencart version 3+

**Comment by chongshengdz** [comment]
> ur screen even on a iphone does not go that small

it all about table-responsive, not about how big or small my phone goes.

**Comment by chongshengdz** [comment]
it all about table-responsive, nothing to do with the screen size.

**Comment by mhcwebdesign** [comment]
@chongshengdz: It's working fine on OC 4.0.1.0, see attached screenshot.
![Screenshot_2022-08-23_16-22-02](https://user-images.githubusercontent.com/2989557/186198586-6dbedfc0-b0fe-4dc7-9159-420b8a89d338.png)

**Comment by chongshengdz** [comment]
it does not work, i do test it using different smartphone browsers.

**Comment by chongshengdz** [comment]
firefox, edge, chrome, are all not table responsive.
you can install any one of the above mobile browsers to test.

**Comment by chongshengdz** [comment]
firefox, edge, chrome, are all not table responsive.
you can install any one of the above mobile browsers to test.
my phone is 12 gb ram and 256 gb storage.
much better than an iphone.

**Comment by chongshengdz** [comment]
table-responsive{-sm|-md|-lg|-xl|xxl}
just found out the solution, it must add -sm or -md or -lg or -xl or -xxl to make tables responsive, bootstrap5 is different
for example  <div class="table-responsive-sm">

**Comment by chongshengdz** [comment]
> @chongshengdz: It's working fine on OC 4.0.1.0, see attached screenshot. ![Screenshot_2022-08-23_16-22-02](https://user-images.githubusercontent.com/2989557/186198586-6dbedfc0-b0fe-4dc7-9159-420b8a89d338.png)

table-responsive{-sm|-md|-lg|-xl|xxl}
just found out the solution, it must add -sm or -md or -lg or -xl or -xxl to make tables responsive, bootstrap5 is different
for example  <div class="table-responsive-sm">

**Comment by chongshengdz** [comment]
> ur screen even on a iphone does not go that small

table-responsive{-sm|-md|-lg|-xl|-xxl}
just found out the solution, it must add -sm or -md or -lg or -xl or -xxl to make tables responsive, bootstrap5 is different
for example  <div class="table-responsive-sm">

**Comment by mhcwebdesign** [comment]
Wrong! Bootstrap supports table-responsive, see e.g. https://getbootstrap.com/docs/5.0/content/tables/

And with regards to OC 4.0.1.0: It works fine. See my previous screenshot.

**Comment by chongshengdz** [comment]
> Wrong! Bootstrap supports table-responsive, see e.g. https://getbootstrap.com/docs/5.0/content/tables/
> 
> And with regards to OC 4.0.1.0: It works fine. See my previous screenshot.

you are wrong, because you don't read all.
https://getbootstrap.com/docs/5.0/content/tables/#responsive-tables
please follow the above link to check again.

Responsive tables
Responsive tables allow tables to be scrolled horizontally with ease. Make any table responsive across all viewports by wrapping a .table with .table-responsive. Or, pick a maximum breakpoint with which to have a responsive table up to by using .table-responsive{-sm|-md|-lg|-xl|-xxl}.

**Comment by chongshengdz** [comment]
https://getbootstrap.com/docs/5.0/content/tables/#always-responsive
Always responsive is working in bootstrap 5.0+, but i don't know why it don't work in opencart 4.0+
maybe always responsive has a breakpoint.

**Comment by chongshengdz** [comment]
Always responsive is like the above screen capture.
Responsive tables
Responsive tables allow tables to be scrolled horizontally with ease. Make any table responsive across all viewports by wrapping a .table with .table-responsive. Or, pick a maximum breakpoint with which to have a responsive table up to by using .table-responsive{-sm|-md|-lg|-xl|-xxl}.

**Comment by mhcwebdesign** [comment]
In stylesheet.css comment out line 850:

```
.table-responsive {
    /* overflow: visible; */
}
```
Then it will use bootstrap's default `overflow-x:auto`

**Comment by chongshengdz** [comment]
> table-responsive

that is it, thank you.

**Comment by chongshengdz** [comment]
by the way, product-compare table should add table-responsive too
