### ISSUE TITLE
Module installation error

### ISSUE THREAD

**Issue by edwinhonesty** [opencart/opencart#11589]
**What version of OpenCart are you reporting this for?**
Version 4.0.1.0
**Describe the bug**
Error when uploading a module or installing from marketplace. It gives initial, error when uploading but when you try to upload again, it tells you files already available.
![Screenshot 2022-08-25 07 19 09](https://user-images.githubusercontent.com/106625380/186595912-27d66412-27eb-465a-8d59-dd943f1e1bdb.png)

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
go to opencart.com register for an account then go to my stores and create a api key. i need to add better instructions

**Comment by edwinhonesty** [comment]
Can I have an alternative means for you to check this error

**Comment by danielkerr** [comment]
If ur using localhost it won't work
