### ISSUE TITLE
[master] Frontend & Backend Translation handling errors

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11597]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
With the same translation files I get different behavior when installing a language in an extension and uploading the same files to the language folders
e.g. Frontend:
a) Upload
![image](https://user-images.githubusercontent.com/10166095/187018360-c1f9e581-528d-4c1c-9620-4246de903c95.png)

b) Extension (text_total, text_sub_total missing and the 3 module headlines are different)
![image](https://user-images.githubusercontent.com/10166095/187018390-cb2da1fb-6d17-466e-a536-b99b1979fe16.png)

e.g. Backend:
a) Upload
![image](https://user-images.githubusercontent.com/10166095/187018518-db62a5a4-9cdc-4eb1-85e4-a58307425f21.png)

b) Extension
![image](https://user-images.githubusercontent.com/10166095/187018549-5d81adcd-c00e-4037-83e1-30a7f005db39.png)

The upload version is working well but the extension has unexpected results.
**Expected behavior**
I expect the same behavior if the language files are uploaded or installed.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 103.0

**Comment by danielkerr** [comment]
U understand that I only included the main angauage file and not one for every page.

**Comment by pemaier** [comment]
Yes I understand that for the example file to show how it works.

I was translating the complete shop into German language and tested in 2 ways the translation.
1st Upload into the language folders (admin, catalog, extension)
2nd I used the same translation files in an extension.ocmod for a complete language installation extension 
(2nd should be the prefered version for customers on the marketpalce)

1st - is working without problems
2nd - displays nt all texts and is mixing text in same cases

You can test it by yourself. Pack your english language files into the langauge example and install it.
Then you have english and german (with english text) and the switch between. Then you'll see the missing or wrong parts.
