### ISSUE TITLE
_zone table country_id 170

### ISSUE THREAD

**Issue by DanielMiara** [opencart/opencart#11595]
All zones have wrong a code symbols

**Comment by mhcwebdesign** [comment]
Can you be more specific please?

**Comment by danielkerr** [comment]
i can not see anything wrong! more like ur uisng the wrong mysql encoding

![image](https://user-images.githubusercontent.com/5079756/186896778-1692974f-1c44-41c8-9929-2dd5ff549ab6.png)

**Comment by mhcwebdesign** [comment]
@DanielMiara: First of all, your claim that

> All zones have wrong a code symbols

isn't true. The zone codes in the DB table are only wrong, or different, for country_id=170 in table 'oc_zone', but not for the other countries. 

@danielkerr : Have the zone codes for Poland been changed on purpose, or is it simply a case of some corrupted data?

**Comment by ADDCreative** [comment]
Probably changed by this commit. https://github.com/opencart/opencart/pull/9211

**Comment by mhcwebdesign** [comment]
This change was initiated by @osworx on on 29 Jan 2021, see
https://github.com/opencart/opencart/commit/d50496fa6506423fe63af9adc80db77c0238aa5e

It's based on https://en.wikipedia.org/wiki/ISO_3166-2:PL

**Comment by regdos** [comment]
State/province code changes for Poland is incorrect. They should be in accordance with the current ISO because in other services, e.g. EMV 3D Secure, the state field is validated in accordance with the current ISO 3166-2 of a given country and for old codes they will cause errors.
