### ISSUE TITLE
Pipe | character in the URL 

### ISSUE THREAD

**Issue by DanielMiara** [opencart/opencart#11594]
The pipe | as a separator is not the safe symbol and makes a lot of issues if you share some feed or process a payment, especially a callback. Even if you encode it to RFC 3986 so that was a bad move to replace a / to |

**Comment by danielkerr** [comment]
any specific payment method?

**Comment by danielkerr** [comment]
is there no url encoding u can use?

**Comment by danielkerr** [comment]
i dont think u have!

$this->url->link(urlencode('catalog/attribute|delete'), 'user_token=' . $this->session->data['user_token']);

**Comment by danielkerr** [comment]
u can use a startup to decode the url

**Comment by danielkerr** [comment]
works for me even without decoding the url after

**Comment by ADDCreative** [comment]
HTML validators give a "Illegal character in query: | is not allowed." error. See. https://validator.w3.org/nu/?doc=https%3A%2F%2Fdemo.opencart.com%2F

**Comment by danielkerr** [comment]
Fine

**Comment by mhcwebdesign** [comment]
I think for all the links hardcoded in the twig files, or being generated by $this->url->link(...) calls, the '|' character needs to be replaced with '%7C'. It should then pass the W3 validator.

**Comment by danielkerr** [comment]
I will change the method simbol to "."

**Comment by mhcwebdesign** [comment]
I am not sure whether the usage of '.' instead of '|' is  good idea. Many URLs follow the convention of treating something like '/software/bar.html' as a resource of type 'html', and something like '/software/bar.foo' might therefore be confusing. 

Couldn't we just fix the Opencart code to always using the '/' character only in the query path, as it used to be in OpenCart 3?

**Comment by stalker780** [comment]
In my opinion, it does not matter '|' or '.' or '/'. If you have got any W3C issues just create a seo_url for a link and that's it.

**Comment by danielkerr** [comment]
[mhcwebdesign](https://github.com/mhcwebdesign) . is a better solution because its in the url variable and its not going too see it when seo urls are on. 

route=software/bar.foo

**Comment by mhcwebdesign** [comment]
> [mhcwebdesign](https://github.com/mhcwebdesign) . is a better solution because its in the url variable and its not going too see it when seo urls are on.
> 
> route=software/bar.foo

You are right, it's in the query string only, not the query path. I think the special characters “.”, “-“, “*”, and “_” are allowed without percent-encoding. Might still be a good idea though to run it through the W3C validator.
