### ISSUE TITLE
[4.0.1.1] Admin - Close the message with click thrown out of Admin

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11598]
**What version of OpenCart are you reporting this for?**
4.0.1.1
**Describe the bug**
Goto a category and click edit categry.
Then click save ... the message apears.
Clich on the cross to close.
Then the session get ended and the login page comes up/
![image](https://user-images.githubusercontent.com/10166095/187035821-2ea2da61-5abb-4dcb-9c4b-2cea984f21a3.png)
(It doesn't matter red or green message - same behavior)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 104.0

**Comment by mhcwebdesign** [comment]
I can confirm this bug!
