### ISSUE TITLE
master branch, the default theme should to be optimized to be responsive

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#11591]
![Screenshot_2022-08-25-22-21-29-764_com android browser](https://user-images.githubusercontent.com/30888843/186691821-5583fd76-2829-47ad-a625-cfabd02b7bc4.jpg)
![Screenshot_2022-08-25-22-24-43-191_com android browser](https://user-images.githubusercontent.com/30888843/186691873-48c2da35-4f14-43b5-a0be-241969570965.jpg)

**Comment by mhcwebdesign** [comment]
Yes, I can confirm it. It's an issue for very small screen widths, e.g. less than 300px.

**Comment by chongshengdz** [comment]
> Yes, I can confirm it. It's an issue for very small screen widths, e.g. less than 300px.
yes, some people places orders using a mobile phone.
so this is not quite user-friendly.
