### ISSUE TITLE
I can't Open My Opencart Dashboard after i install the last version opencart-4.0.1.1.zip

### ISSUE THREAD

**Issue by Ahmed-Raed-Siam** [opencart/opencart#11606]
The problem I can't get to the dashboard with my username and password
Uploading مصنع الصيغ مسجل الشاشة٢٠٢٢٠٨٢٩_٢١٤٨٥٣.mp4…

**Comment by Amir-SSDC** [comment]
go to your database, in the open - oc_setting - look for the time zone, and change it to the correct time zone matching your server. let me know if oy works.

**Comment by Ahmed-Raed-Siam** [comment]
Its working now thanks
