### ISSUE TITLE
Multilanguage SEO URLs is not working

### ISSUE THREAD

**Issue by pashast** [opencart/opencart#11600]
4.0.1.1

Multilanguage SEO URLs is not working
German language installed from OpenCart Language Example
server Apache 2.4 PHP 8.0

https://user-images.githubusercontent.com/1617903/187090224-5e57e3f5-3e2b-4ba2-9770-fde192ed0cd9.mp4

**Comment by TheCartpenter** [comment]
The SEO URL option's on but the URL still doesn't show the links as SEO formats.

**Comment by pashast** [comment]
Also
http://opencart411.local/en-gb/information/about-us - works fine, opens information About us page on english
http://opencart411.local/de-de/information-de/about-de - dont work, opens home page on english, instead of About us page on  german
![Знімок екрана 2022-08-29 061200](https://user-images.githubusercontent.com/1617903/187115691-6134a243-2c2e-45ad-8edc-5dbc68476b80.png)

**Comment by chulcha** [comment]
missing get['language']
also
missing session data for languge
https://github.com/opencart/opencart/issues/11142

**Comment by danielkerr** [comment]
make sure every product, category, etc.. has an seo keyword. soime hqave been left out in the demo data

**Comment by danielkerr** [comment]
im fixing the missing images now
