### ISSUE TITLE
Admin rename

### ISSUE THREAD

**Issue by azn1viet** [opencart/opencart#11604]
it's never been working and caused the site inaccessible if I manually rename it. And it's never been fixed and why we have to rename with this warning window every single load? Admin needs a password to log in (and you still think passpword isn't secured enough?), no need to rename.

System
Debian 10
PHP 8.1.9

![Screenshot 2022-08-29 233633](https://user-images.githubusercontent.com/769104/187251466-8377c9cf-05cf-4547-b67c-fdf31f4f6af3.png)

**Comment by cgcmart** [comment]
both admin and storage moves do not work. I manually moved them but got admin dashboard without navigation.
![admin-dashboard-error](https://user-images.githubusercontent.com/14033183/187262566-276a608a-622c-4852-bf52-a32ecafe8889.jpg)

**Comment by danielkerr** [comment]
i just tested it my self and its working fine

**Comment by danielkerr** [comment]
maybe ur execution time for the page is to short. u should also use the console to see if there are any errors in the response.

**Comment by danielkerr** [comment]
any errors?

**Comment by FelipoAntonoff** [comment]
I also tested it on Opencart 4.0.1.1 and it started normally, but it took a few seconds, maybe depending on the Hosting or configuration it may arrive at the timeout, but something simple to solve on the Hosting side.

**Comment by danielkerr** [comment]
its set up to copy all the files to the new directory then it redirects in the AJAX to the new folder and the delete method for the old admin directory.

**Comment by danielkerr** [comment]
i need to change how it works so it copys files in segments
