### ISSUE TITLE
v4.0.1.1 installed extension not showing in modules list 

### ISSUE THREAD

**Issue by nayeemrv** [opencart/opencart#11611]
Opencart version : 4.0.1.1

module packages is installed via installler. but it is not showing in modules list. even if manually placing all files still module does not show in list.

**To Reproduce**
1. Go to 'extension installer'
2. Upload 'xx.ocmod.zip package'
3. click install package.
4. then go to extensions>modules
5. installed module not showing 

**Expected behavior**
Installed module should be available in extensions -> modules list

**Comment by mhcwebdesign** [comment]
Not enough details, unable to reproduce your error.

**Comment by cgcmart** [comment]
I uploaded xxx.ocmod.zip file by extensions installer, message says successfully uploaded.
It's located in storage/marketplace folder.
But not display it in extensions installer list, so can not install it.

**Comment by mhcwebdesign** [comment]
Unable to reproduce it, works fine on our test server.

**Comment by PhamToan** [comment]
post your module code in here. Maybe you wrote wrong structure of module in Opencart 4 ...

**Comment by cgcmart** [comment]
@PhamToan I got screen error message after upload "Could not find install.json!"
open929.ocmod.zip uploaded, including
admin/
catalog/
install.json

```
{
  "name": "Open929 Shipping",
  "version": "1.0",
  "author": "CGCMart",
  "link": "https://www.cgcmart.com"
}
```

comparing with /admin/controller/marketplace/installer.php, could not find what's wrong:
```
		// 5. Validate if the file can be opened and there is install.json that can be read.
		if (!$json) {
			move_uploaded_file($this->request->files['file']['tmp_name'], $file);

			// Unzip the files
			$zip = new \ZipArchive();

			if ($zip->open($file, \ZipArchive::RDONLY)) {
                $install_info = json_decode($zip->getFromName('install.json'), true);

				if ($install_info) {
					if (!$install_info['name']) {
						$json['error'] = $this->language->get('error_name');
					}

					if (!$install_info['version']) {
						$json['error'] = $this->language->get('error_version');
					}

					if (!$install_info['author']) {
						$json['error'] = $this->language->get('error_author');
					}

					if (!$install_info['link']) {
						$json['error'] = $this->language->get('error_link');
					}
				} else {
					$json['error'] = $this->language->get('error_install');
				}

				$zip->close();
			} else {
				$json['error'] = $this->language->get('error_unzip');
			}
		} 
```
