### ISSUE TITLE
[master] Sales Report TypeError

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11612]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
Opening the Sales Report bring up directly an error.

TypeError: Opencart\System\Library\Cart\Currency::format(): Argument #1 ($number) must be of type float, null given, called in /home/aqq20848/public_html/opencart/master.demo/extension/opencart/admin/controller/report/sale_order.php on line 156 in /home/aqq20848/public_html/opencart/master.demo/system/library/cart/currency.php on line 24

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/187417685-d0a5fa98-5fdb-4c69-8245-c4c2a47e330d.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 104.0

**Additional context**
Fresh install with opened and saved settings

**Comment by danielkerr** [comment]
can not replicate but forced float type on the variables in question should work.
