### ISSUE TITLE
[master] Admin Customer edit history not working

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11637]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
Enter data get message that data is saved but the history is empty

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/189092689-a22d2af2-4163-4fe9-8a5c-36f263bcb7b9.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 104.0

**Additional context**

**Comment by FelipoAntonoff** [comment]
In 4.0.1.1 same thing, a success warning appears, but it doesn't save the data.
