### ISSUE TITLE
type field in subscription_transaction table

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#11630]
public function addTransaction(int $subscription_id, string $description = '', float $amount = 0): void {
		$this->db->query("INSERT INTO `" . DB_PREFIX . "subscription_transaction` SET `subscription_id` = '" . (int)$subscription_id . "', `description` = '" . $this->db->escape($description) . "', `amount` = '" . (float)$amount . "', `date_added` = NOW()");
	}

In admin/model/sale/subscription.php file, addTransaction() method misses the ```type``` field as it is mandatory as a NOT NULL field in the ```oc_subscription_transaction``` table, by design.

**Comment by danielkerr** [comment]
clearly being worked on
