### ISSUE TITLE
Installation failure: Error: Class "Opencart\System\Library\Document" not found in

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#11632]
https://github.com/opencart/opencart/blob/f3b07b753addb065f5f7ef93af69d262d66513e0/upload/system/framework.php#L182

install screen message:
`Error: Class "Opencart\System\Library\Document" not found in ../system/framework.php on line 182`

check /system/library there is:
/[system](https://github.com/opencart/opencart/tree/master/upload/system)/[library](https://github.com/opencart/opencart/tree/master/upload/system/library)/document.php

**Comment by danielkerr** [comment]
fucking guessing games ever time with u these days.
