### ISSUE TITLE
Payment and Shipping methods are not populated in other language thang en-gb

### ISSUE THREAD

**Issue by azn1viet** [opencart/opencart#11633]
Perhaps, there are no options to make those translated and they are not populated to the front end.

Note that they''re working fine in en-gb as default.

NOT working in vi:

![Screenshot 2022-09-06 105804](https://user-images.githubusercontent.com/769104/188544289-f28ec740-ae1b-469b-a695-f4207aa3dd5f.png)
Same cart and working in en-gb:

![Screenshot 2022-09-06 110212](https://user-images.githubusercontent.com/769104/188544526-bbb6e8c0-9ac5-49fe-936e-bd2d06b9973e.png)

Also from this screen:

![Screenshot 2022-09-06 110847](https://user-images.githubusercontent.com/769104/188545095-71c838df-f081-412b-affb-dd21777b34b6.png)

**Comment by danielkerr** [comment]
should work
