### ISSUE TITLE
[4.0.1.1] Not listing Orders in My Account

### ISSUE THREAD

**Issue by FelipoAntonoff** [opencart/opencart#11638]
Hello, it is not listing the Orders in My Customer Account.

Even the Order being created with Status and by the account.

Vídeo:
https://drive.google.com/file/d/1v2m0L29_cdygFdmWgPjPhZDwo6JQmE9b/view?usp=sharing

Data:
Opencart 4.0.1.1
Chrome o 104.0.5112.102 (Official version) 64 bit
PHP 8.1

**Comment by danielkerr** [comment]
i think u need to clikc on the name when it drops down after typing oftherwise it goes as a guest order

**Comment by FelipoAntonoff** [comment]
Hello, @danielkerr , if it's the registration, I used the Register Account, I can even log into the test client's account, but it doesn't show the orders, in the Administrator it does.

I made a new registration and the same thing, the Status of the orders starts in Pending in the tests done.
In your tests does it show normal in My Account?

Opencart was just installed as normal, without any changes in the configuration, maybe it could be some configuration detail.

**Comment by danielkerr** [comment]
what is the order status on the payment method. maybe u need to resave. happe43ns if u delete the order status and its the default to the order

**Comment by FelipoAntonoff** [comment]
Hello, the payment used in the test is Cash On Delivery, with initial Status Pending, I also tested manually changing the Status Processed.
Then I'll try to test in the master version to see if it works normally, for now I tested in 4.0.1.1.

**Comment by danielkerr** [comment]
its because when u select customer its not selecting them properly.

**Comment by danielkerr** [comment]
ur selecting data that is in ur autocomplete of ur browser data

fix it with adding autocomplete="new-password"
