### ISSUE TITLE
Links are not clickable in the Toast message after adding product to cart

### ISSUE THREAD

**Issue by Victorq10** [opencart/opencart#11631]
**What version of OpenCart are you reporting this for?**
opencart-4.0.1.1

**Describe the bug**
Links are not clickable in the Popup Toast message after adding a product to the cart.
It effects page toast messages with links.

**To Reproduce**
1. Go to product page
2. Click on add to cart
3. Move mouse over the links in the popped up Toast message.
4. Links are not clickable.

**Expected behavior**
Links in the Toast message box should be clickable.

**Screenshots / Screen recordings**
No

**Server / Test environment (please complete the following information):**
 - Local development? yes
 - Operating system: Ubuntu
 - PHP version 8.1.6
 - Apache version: Apache/2.4.53 (Unix) OpenSSL/1.1.1o PHP/8.1.6 mod_perl/2.0.12 Perl/v5.34.1 
 - Browser(s) tested with [e.g. chrome, safari - if applicable]: Firefox 104.0 (64-bit), Chrome Version 105.0.5195.102 (Official Build) (64-bit), Vivaldi 5.4.2753.47 (Stable channel) stable (64-bit)

**Comment by danielkerr** [comment]
already reported and fixed in master
