### ISSUE TITLE
[4.0.1.1] Allow upgrade using a different admin path

### ISSUE THREAD

**Issue by dgomezleon** [opencart/opencart#11641]
**What version of OpenCart are you reporting this for?**
OpenCart 4.0.1.1

**Describe the bug**
Since version 4.0.0, it is required to move `/admin` path in order to avoid the security warning after accessing the admin panel. However, it is not supported to execute the upgrade steps at that moment (accessing http://YOUR-IP/install/index.php?route=upgrade), having to recreate the `/admin` path to do it.

**To Reproduce**
Steps to reproduce the behavior (in spite not being a logical situtation):
1. Install OpenCart using cli.php
2. Move `/admin` path to another location (e.g. `/newadmin`) and edit administration `config.php`
3. Go to 'http://YOUR-IP/install/index.php?route=upgrade'
4. See error `Error: config file /opt/bitnami/opencart/admin/config.php could not found. Make sure the admin directory is the correct name!`

**Expected behavior**
Ideally, it should work without having to recreate `/admin` folder, since the folder has been renamed and the `admin/config.php` (now in a new path) edited to reflect these changes. 

**Screenshots / Screen recordings**
![upgrade error](https://user-images.githubusercontent.com/11521627/189475528-11a3ebeb-3d8d-42b5-9e85-93ee2578bab4.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system: Debian 11
 - PHP version: 8.1
 - Apache version: Apache/2.4.54
 - Browser(s): Chrome

**Additional context**
It is especially useful to reduce the logic when upgrading containers, where `config.php` and `/newadmin/config.php` have been already persisted and restored.

**Comment by danielkerr** [comment]
it works by being redirected from the admin upgrade button. 

```
if (isset($this->request->get['admin'])) {
	$admin = basename($this->request->get['admin']);
} else {
	$admin = 'admin';
}
```

**Comment by danielkerr** [comment]
it should work now
