### ISSUE TITLE
No way to changes files inside the extension folder with the event system, opencart 4

### ISSUE THREAD

**Issue by nikto1** [opencart/opencart#11646]
**What version of OpenCart are you reporting this for?**
4+

**Describe the bug**
No way to change files in the extension folder. As per docs, only files inside catalog/, system/ and admin) can be modified.

**Expected behavior**
extend the event system also to the extension folder.

**Comment by stalker780** [comment]
Are you sure system folder events work?
https://github.com/opencart/opencart/discussions/11624

**Comment by danielkerr** [comment]
it can be done by extending the class and replacing the cart class in the registry via the startup system

**Comment by danielkerr** [comment]
look at the extension examples i have put in the code
