### ISSUE TITLE
On the payment page when choosing a payment method - gives an error

### ISSUE THREAD

**Issue by KomandirBohdanov** [opencart/opencart#11659]
Two payment methods do not work on the payment page:
1. With a bank card
2. Pay on delivery

![tempsnip](https://user-images.githubusercontent.com/113684933/190621031-f2ed75a4-0ec1-4288-8580-64ed72f3b102.png)

When you select them and click on the "Place an order" button, it gives an error from the browser:

![image](https://user-images.githubusercontent.com/113684933/190619927-238c9154-cb50-4110-94a0-57265674352d.png)

And an error is displayed in the console:

![image](https://user-images.githubusercontent.com/113684933/190620257-80a5adf7-95ee-430a-ad80-c7e2b5569215.png)

Website Link on Checkout page: https://autoprom.in.ua/index.php?route=extension/module/custom
And you may not be able to view the page, because I can not remove the stub.

Thanks in advance for your reply
Dear Sir/Madam

**Comment by pemaier** [comment]
For which OpenCart version is your request?

**Comment by KomandirBohdanov** [comment]
> For which OpenCart version is your request?


Sorry, I forgot to write about it.

OpenCart version 3.0.3.7

**Comment by pemaier** [comment]
Sorry but you are wrong here. Here is the OpenCart development and not the support area.
You should go to the Opencart Forum with your request.

**Comment by KomandirBohdanov** [comment]
> Sorry but you are wrong here. Here is the OpenCart development and not the support area. You should go to the Opencart Forum with your request.

![image](https://user-images.githubusercontent.com/113684933/190643851-3c7f3846-e788-4006-af76-1b13e8005b96.png)
