### ISSUE TITLE
[master] Checkout Payment Methode not working with Geo Zone setting

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11658]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
At checkout in payment methode are only payment methods visible with setting Geo Zone = All Zones

**Expected behavior**
That payment methods for the customer address defined in a Geo Zone is visible and choosable.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/190619717-05bfabce-4a2c-4f9a-acca-9c5a905e061e.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 104.0.2

**Additional context**
Shipping methods are working well.

**Comment by danielkerr** [comment]
it works but u have to enable billing address
