### ISSUE TITLE
Libraries update Jquery / Bootstrap / FontAwesome

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#11652]
Perhaps it is time to update libraries to use latest ones in new OC4.0.2 release

jQuery 3.6.1
https://jquery.com/download/

Bootstrap 5.2.1
https://getbootstrap.com/docs/5.2/getting-started/download/

FontAwesome 6.2.0
https://fontawesome.com/download

**Comment by danielkerr** [comment]
where bootstrap?
search for // u will see all the changes i have done

**Comment by stalker780** [comment]
@danielkerr 
> where bootstrap? search for // u will see all the changes i have done

I am working on it now. I will place all custom variables in view/stylesheet/bootstrap.scss file, so it will be much easier to update BS and apply modifications in the future.
Will be ready in a day or two.
