### ISSUE TITLE
[Forum] producing PHP Warning

### ISSUE THREAD

**Issue by nexadomain** [opencart/opencart#11656]
**What version of OpenCart are you reporting this for?**
**Forum Site**

**Describe the bug**
I visited the Forum to get some help.
_Webpages_ contain **PHP Warnings**.

This is near Header
```
[phpBB Debug] PHP Warning: in file [ROOT]/phpbb/session.php on line 580: sizeof(): Parameter must be an array or an object that implements Countable
[phpBB Debug] PHP Warning: in file [ROOT]/phpbb/session.php on line 636: sizeof(): Parameter must be an array or an object that implements Countable
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3257)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3257)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3257)
```

This is before the first feed
```
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1266: count(): Parameter must be an array or an object that implements Countable
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1266: count(): Parameter must be an array or an object that implements Countable
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1266: count(): Parameter must be an array or an object that implements Countable
```

**To Reproduce**
1. Go to '[(https://forum.opencart.com/viewtopic.php?t=218348)](https://forum.opencart.com/viewtopic.php?t=218348)'
2. See error

**Expected behavior**
This should not happen with the Forum site.

**Screenshots / Screen recordings**
![opencart-forum-error-2022-09-16](https://user-images.githubusercontent.com/77724079/190491766-71a2ccb5-6887-4817-8e12-3ef36051d3f2.jpg)

**Comment by osworx** [comment]
This is since a few days .. and as it seems, nobody is doing something to solve.
Seems someone has updated the php-version to 8.x ..

**Comment by nexadomain** [comment]
No longer PHP warnings are visible.
I guess it is **solved** now.

**Comment by condor2** [comment]
Yep...but Breadcrumbs are missing..

**Comment by osworx** [comment]
It's like the current shop release .. not ready for production ..

**Comment by condor2** [comment]
What shop? Here is related to forum...

**Comment by danielkerr** [comment]
hosting upgraded the php version. im not blind!

**Comment by mhcwebdesign** [comment]
It's working again, but as condor2 says, the breadcrumbs appear to be still missing there.

**Comment by condor2** [comment]
@danielkerr 
![forum_oc](https://user-images.githubusercontent.com/14251939/191236560-2894e2c3-369a-4120-a085-c81727046c1a.png)

**Comment by condor2** [comment]
@danielkerr fix forum breadcrumbs for fast browsing

**Comment by condor2** [comment]
@danielkerr stil not fixed.......

**Comment by osworx** [comment]
> hosting upgraded the php version. im not blind!

Sorry, but nobody else then me personally (as the account owner) can do anything on my server (settings)!
And IF they did, please fix the open issues like the breadcrumb issue.
thx.

**Comment by condor2** [comment]
@danielkerr  fix forum breadcrumbs........
