### ISSUE TITLE
replace override.product_image override.image

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#11668]
https://github.com/opencart/opencart/blob/f5bd792612201f3e1837eecf8d1da5e4ca701412/upload/admin/view/template/catalog/product_form.twig#L1294

**Comment by danielkerr** [comment]
which version as its working on the master branch.

**Comment by eturerer** [comment]
<input type="checkbox" name="override[image]" value="1"
id="input-variant-image" data-oc-toggle="switch" data-oc-target="#image"
class="form-check-input" ------------ {% if override.product_image %}
---------------- checked{% endif %}/>

change

<input type="checkbox" name="override[image]" value="1"
id="input-variant-image" data-oc-toggle="switch" data-oc-target="#image"
class="form-check-input"{% if override.image %} checked{% endif %}/>
