### ISSUE TITLE
Links are pointing to the admin panel. 

### ISSUE THREAD

**Issue by priyorockz** [opencart/opencart#11667]
**What version of OpenCart are you reporting this for?**
OpenCart 4.0.1.1

**Describe the bug**
When an admin updates the order history and notifies customer, the links in the email are pointing to the admin panel.

**Comment by nexadomain** [comment]
Hey @priyorockz 
Are you planning the "OpenCart SMS System" for OC v4?

Eagerly waiting for your extension. For v2, and v3, it was one of the best & must Extensions for Opencart.

**Comment by danielkerr** [comment]
which email?
