### ISSUE TITLE
php Warning:  Undefined array key "status" 

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#11662]
https://github.com/opencart/opencart/blob/ef2e45a654b9f61932669da121cc07475f1641dc/upload/admin/controller/extension/module.php#L64

go to Admin Navigation menu >> Extensions
choose the extension type: Modules

![php_error_module_status](https://user-images.githubusercontent.com/14033183/190876213-b26731dc-7f72-43f8-ada0-abbd4e27b6e2.jpg)

**Comment by TheCartpenter** [comment]
Confirmed. Done: https://github.com/opencart/opencart/pull/11663

**Comment by cgcmart** [comment]
replace [opencart/upload/admin/controller/extension/module.php](https://github.com/opencart/opencart/blob/ef2e45a654b9f61932669da121cc07475f1641dc/upload/admin/controller/extension/module.php#L64) Line 64
`'status' => $setting_info['status'] ? $this->language->get('text_enabled') : $this->language->get('text_disabled'),`

with
`'status' => $this->config->get('module_' . $code . '_status') ? $this->language->get('text_enabled') : $this->language->get('text_disabled'),`

The php Warning is gone!

**Comment by TheCartpenter** [comment]
By doing that, it will also skip the $setting_info from the rest of the setting key where the extensions will also be installed by remaining with one config key.

**Comment by danielkerr** [comment]
they all need status other wise they will not load
