### ISSUE TITLE
config product_category needs to be added

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#11676]
<div class="row mb-3">
                        <label class="col-sm-2 col-form-label">{{ entry_product_category }}</label>
                        <div class="col-sm-10">
                          <div class="form-check form-switch form-switch-lg">
                            <input type="hidden" name="config_product_category" value="0"/>
                            <input type="checkbox" name="config_product_category" value="1" id="input-product_category" class="form-check-input"{% if config_product_category %} checked{% endif %}/>
                          </div>
                          <div class="form-text">{{ help_product_category }}</div>
                        </div>
                      </div>

https://github.com/opencart/opencart/blob/d67d780881074f9ef4814b7d5b4dda37eaa21207/upload/admin/view/template/setting/setting.twig#L307

**Comment by danielkerr** [comment]
no fucking idea what u mean
