### ISSUE TITLE
Opencart 3.0.3.8 config smtp with gmail no longer support less secure app

### ISSUE THREAD

**Issue by paolobiavati** [opencart/opencart#11722]
Is there a way to configure in Opencart the smtp with gmail? 
I usually did it with "less secure app" setting in Gmail, but after 30 may 2022 Gmail no longer support the use of less secure app...

I found this solution in the opencart community forum, someone say it is not safe (and it is right...) https://forum.opencart.com/viewtopic.php?p=844079&hilit=gmail+less+secure+app#p844079

Maybe there will be in the future a way to put a certificate or some other type of safe authentication for gmail?
Thanks

**Comment by danielkerr** [comment]
copy the mail class from 4x

**Comment by ADDCreative** [comment]
@paolobiavati the app password option is more secure than less secure app option (but probably not as good as the access token). That is why Google has retained it and removed the less secure app option.

@mhcwebdesign the SMTP class in the master is really no different to the maintenance and would not solve the issue. It would require using the Google API to create and access token and use that for the SMTP auth.

**Comment by mhcwebdesign** [comment]
@ADDCreative : Thank you for your explanation. Personally, I always use email accounts provided by the webhost, but from my experience with gmail, I haven't managed to get my email client (evolution on linux) to work with the gmail for ages.

**Comment by cartbinder** [comment]
I did this few months ago via the PHPmailer extension available on the opencart. As default SMTP selection is not working.

Then add up the Gmail SMTP details.
And also used app password available in the google. Worked for me.

**Comment by ADDCreative** [comment]
@cartbinder No need to use the PHPmailer extension, the SMTP class in 3.0.3.8 works just fine with Gmail if you configure everything correctly.

Not that any live store should be using Gmail.
