### ISSUE TITLE
[4.0.1.1] Pop Ups Bugs

### ISSUE THREAD

**Issue by frameyourbag** [opencart/opencart#11751]
**What version of OpenCart are you reporting this for?**
Opencart Version: 4.0.1.1
Theme/Template: Original
No additional Extensions installed a part of the ones that come from scratch
No translations installed

**Describe the bug**
This kind of information tab, when add something to the cart, or error information about, not enough quantity etc, don't disappear.

**To Reproduce**
1-a. At any place( home or categories or products pages) just add something to the shopping cart per example.
1-b. Try to add more quantity then the one allowed
Similar errors like this that open the pop up on the right corner, the "x" bottom don't work, neither disappear.

**Expected behavior**
Expected to the "x" bottom work and sometime after it appear to disappear automatically 

**Screenshots / Screen recordings**
Link: https://prnt.sc/uy8-WB__3niB

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - Operating system: Linux
 - PHP version: 8.0
 - Apache version: 2.4.5
 - Browser(s) tested with Chrome
 - Version: 105.0.5195.127

**Comment by Leander96911111** [comment]
What is the solution here? So far I just found "fixed in master branch" and don't understand what to do. For a beginner this kind of answers (as well as a generic reference to "search the forum") are not as helpful.

**Comment by mhcwebdesign** [comment]
@Leander96911111: The master branch, which has a number of bugfixes, can be downloaded from here:
https://github.com/opencart/opencart/tree/master

**Comment by Leander96911111** [comment]
After another search I found a solution (apart from a complete reinstallation).

Just replace

#alert {z-index: 9999;}

with

#alert {z-index: 9999; pointer-events: all;}

in both stylesheet.css files (folders admin/view/stylesheet and catalog/view/stylesheet).

And don't forget to clear your browser cache after updating the stylesheets.

**Comment by Leander96911111** [comment]
> @Leander96911111: The master branch, which has a number of bugfixes, can be downloaded from here: https://github.com/opencart/opencart/tree/master

Thanx for the quick reply!
