### ISSUE TITLE
Errors when confirming an order

### ISSUE THREAD

**Issue by Sionape** [opencart/opencart#11754]
**What version of OpenCart are you reporting this for?**

4.0.0.0

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

**To Reproduce**
Every time I click to confirm an order I'm getting this. Not sure how to get this fixed. All the information it needs are in the correct place

![image](https://user-images.githubusercontent.com/110951325/192374127-46a86342-a571-4cb8-b3d7-1923a081fc61.png)

**Comment by mhcwebdesign** [comment]
This is already fixed, try the latest master branch.

**Comment by danielkerr** [comment]
press the refrsh button for the shipping and payment methods
