### ISSUE TITLE
Upgrading a 3.x shop to 4.x dosnt respect an already out-of-root storage dir

### ISSUE THREAD

**Issue by Mai-Lapyst** [opencart/opencart#11761]
**What version of OpenCart are you reporting this for?**
4.0.1.1

**Describe the bug**
When upgrading a 3.0.3.8 opencart to the latest version (4.0.1.1), that has already it's storage dir moved outside of the root directory of opencart, it does not update the old one but rather creates a new one.

**To Reproduce**
1. Have an 3.0.3.8 opencart installed where the storage dir is already moved out of root, i.e.:
    ```
    - domain.folder/
      - public/          (content of the upload folder from the opencart zip packages)
        - system/
        - index.php
        - ...
      - storage/
    ```
    and `config.php` contains: `define('DIR_STORAGE', '/path/to/your/domain.folder/storage/');`

2. Upgrade your installation as described here: https://docs.opencart.com/upgrading/; which means to download the zip and overwrite your current installation.
3. Open the installer at `https://your.shop.tld/install` and run it until it shows you the `Installation complete` page.
4. Try to access any page besides the installer
5. See following error in your webserver logs:
    ```
    Failed opening required '/path/to/your/domain.folder/storage/vendor/aws/aws-sdk-php/src/functions.php' (include_path='.') in /path/to/your/domain.folder/public/system/vendor.php:11
    ```
6. Find that the whole `/path/to/your/domain.folder/storage/vendor/aws` folder does not exists, but it exists in `/path/to/your/domain.folder/public/system/storage/vendor/aws`.

**Expected behavior**
That upgrading an existing openpath with an out-of-root storage directory updates the storage directory instead of creating a new one at another location.

**Screenshots / Screen recordings**
-

**Server / Test environment (please complete the following information):**
 - Deployed to a web server 
 - Operating system: Linux
 - PHP version: 8.0
 - Apache version: 2.4.38

**Additional context**
-

**Comment by TheCartpenter** [comment]
Before an upgrade is in the need, the storage folder needs to be put back to its original location, either from the file server, and from both config.php files. Once the upgrade has successfully completed, the process needs to be reversed for the storage folder.

**Comment by TheCartpenter** [comment]
This might be a good point here. I have updated the upgrade steps in the opencart-3 repository as followed: https://github.com/opencart/opencart-3/blob/main/upgrade.txt

**Comment by danielkerr** [comment]
storage folder does not need to be put back in original place! i have accounted for this in the code.

**Comment by danielkerr** [comment]
i will test it again.

**Comment by danielkerr** [comment]
its fine. as long as the one in you config is using the one put side ur html directory
