### ISSUE TITLE
PHP8.1+ Required   for 3.x

### ISSUE THREAD

**Issue by Buddyboy-git** [opencart/opencart#11769]
OC 3.0.3.8 
I just downloaded this version into xampp 7.4.3 for windows locally.
But for the life of me I cant get past this error.
I tried modifying the composer.json back to 5.4.0, but it has no effect.

I will try to pull a maintenance version.  I am brand new to all this git versioning and even opencart...  so it could be something i am doing wrong.
But, either way....  Just because 3.X is compatible with PHP 8, does not mean it should be required.  So whoever updated the composer.json file to require PHP 8...  should not have done that.   If 3.X is compatible with PHP 8  we should also be able to run it on the minumum PHP version that it is still compatible with...  But that  is just my Newbie 2 cents. 

That commit should have been a new release 3.0.3.9.

**Comment by mhcwebdesign** [comment]
Opencart versions up to 3.0.3.8 are NOT compatible with PHP 8.0 or 8.1.

For PHP 8.x releases, you have to use the https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance version of OpenCart.
