### ISSUE TITLE
Optional payment address info

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#11765]
I would strongly advise against the use of this lookup: https://github.com/opencart/opencart/commit/f89b29a8e946b8a0de6ad83d88117deca8c97df5 , since it would be against CPRA law in regard to minors using their credit cards. Store owners cannot verify these claims. By skipping this information. and going straight to the payment method, it means that any store owner could collect the information without the use of a payment service provider that not only redirects to the payment party to complete the payment but also to encourage store owners not to collect any information from these classifications whereas a law has been built-in the United States to avoid those kinds of activities to occur.

As a result, Security Management from the financial institutions could intercept these payments without the checkout process to intervene,

**Comment by danielkerr** [comment]
are u fucking nuts!

**Comment by TheCartpenter** [comment]
You want to take chances by letting store owners to take that opportunity, be my guest. While you're at it, why not remove the whole order tables then? !

**Comment by TheCartpenter** [comment]
Furthermore to this issue, since Opayo was suggested and merged on this branch, what's been previously reported on the above was about the 'repeated payments' in regard to token use rather than CVV when relying on the 3D Secure Payments. For more information, please see this PR from Opayo repository: https://github.com/academe/opayo-pi/pull/2#issuecomment-1086580091 .
