### ISSUE TITLE
Invoice PDF preview

### ISSUE THREAD

**Issue by shivankagrawal** [opencart/opencart#11762]
**What version of OpenCart are you reporting this for?**
3011

**Describe the bug**
Admin-> Invoice Printing is showing messy

**To Reproduce**
1. Go to admin->order->order view
2. Click on print invoice button from the top
3. It opens the invoice html
4. Press Control p to See design issue

**Expected behavior**
PDF preview should show like invoice html

**Screenshots / Screen recordings**
https://prnt.sc/CWmIVxwDsxe6

**Comment by ADDCreative** [comment]
For 4.0.1.1 part of the issue could be.
https://github.com/opencart/opencart/blob/f585f66548987c073455e1e20a28d920ba53db47/upload/admin/view/template/sale/order_invoice.twig#L7

**Comment by danielkerr** [comment]
maybe post this sort of thing here:

https://github.com/opencart/opencart-3

**Comment by shivankagrawal** [comment]
> For 4.0.1.1 part of the issue could be.
> 
> https://github.com/opencart/opencart/blob/f585f66548987c073455e1e20a28d920ba53db47/upload/admin/view/template/sale/order_invoice.twig#L7

Yes it was my typo, that issue is for 4011 not for 3011
