### ISSUE TITLE
[master] Missing store icon for multistore usage

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11774]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
In old versions we had the store icon in the settings. So it was possible to give each store an icon for a single CI in a browser link.
Right now we have only the possibillity to use the standard web server funktion for only one icon for all stores within the shop folder.
(So for store A company is the same icon visible as for for store B company with has e.g. a total different name and CI.)

**Expected behavior**
To have the possibillity to show for each store a diffrent icon. Each store has a diffrent CI by logo design and more. This is to be refelcted also in the browser by a different icon.

**Comment by danielkerr** [comment]
any one else want this back?

**Comment by osworx** [comment]
> any one else want this back?

Beside the fact, that I define sometimes icons the way I (or the client) prefer(s) (including several sizes and targets), yes.

Defining different icons in a multi-store environement was good feature - and would be fine to have it back.
But, when it may come back, it should be possible to define several, for example:
```css
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">

**Comment by paulfeakins** [comment]
> any one else want this back?

Yep, seems a good place to have it.
