### ISSUE TITLE
Error PHP 8 comptability on Opencart 4

### ISSUE THREAD

**Issue by victoralbala** [opencart/opencart#11771]
**What version of OpenCart are you reporting this for?** 
Version 4.0.1.1 with PHP 8.1.11

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Composer.

When I run composer I get

root@dc65ae751fc9:/var/www/app.local# composer dumpautoload
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Console/Helper/HelperSet.php on line 104

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Console/Helper/HelperSet.php on line 104
Composer could not find a composer.json file in /var/www/app.local
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

**To Reproduce**
1- Install latest OC version with PHP 8.1.11.
2- Install composer.
3- run composer dump autoload

**Expected behavior**
Not getting any error and doing the autoload.

**Comment by danielkerr** [comment]
i am using the latest php and im not getting these errors

**Comment by danielkerr** [comment]
fixed. u dont use composer from the upload folder u do it from the storage one. i removed the wrong composer.json file
