### ISSUE TITLE
4.0.1.1 Toast Notifications 'un-clickable'

### ISSUE THREAD

**Issue by bdolnik** [opencart/opencart#11794]
**What version of OpenCart are you reporting this for?**
4.0.1.1

**Describe the bug**
Toast Alerts are 'un-clickable'. This seems to only be an issue in 4.0.1.1 as the demo site does not seem to have this issue, and is currently running 4.0.0.0

**To Reproduce**
1. Add item to cart
2. Note that a 'toast' notification with various links and a close 'x' will pop-up
3. The links and the close 'x' are un-clickable
4. The only way to get rid of the notification is to refresh or navigate to another page

**Expected behavior**
The notification needs to be clickable

**Screenshots / Screen recordings**
https://www.loom.com/share/b4579d9b34d64263993435e409293069

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? -Deployed
 - Operating system -Ubuntu
 - PHP version -8.1.2
 - Apache version -Apache/2.4.52 (Ubuntu)
 - Browser(s) tested with [e.g. chrome, safari - if applicable] -chrome, edge, mobile safari

**Comment by mhcwebdesign** [comment]
I think this is already fixed in the current master branch (upcoming V4.0.2.0)

**Comment by TheCartpenter** [comment]
There's also another attempt here: https://github.com/opencart/opencart/pull/11764 . Could be a related issue.

**Comment by danielkerr** [comment]
its working in master

**Comment by stalker780** [comment]
@TheCartpenter 
No, mentioned PR is related to bootstrap tooltips, not toasts.
