### ISSUE TITLE
Home Accessiblity Issues

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#11792]
**What version of OpenCart are you reporting this for?**
Master and branches

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

home page is blank, no source, no error log

![home_access_error](https://user-images.githubusercontent.com/14033183/195177436-b169b73c-3e4e-4581-894d-ee5733fcd9dd.jpg)

I checked  [upload](https://github.com/opencart/opencart/tree/master/upload)/[catalog](https://github.com/opencart/opencart/tree/master/upload/catalog)/[controller](https://github.com/opencart/opencart/tree/master/upload/catalog/controller)/[common](https://github.com/opencart/opencart/tree/master/upload/catalog/controller/common)/header.php

```
		$data['lang'] = $this->language->get('code');
		$data['direction'] = $this->language->get('direction');

		$data['title'] = $this->document->getTitle();
		$data['base'] = $this->config->get('config_url');
		$data['description'] = $this->document->getDescription();
		$data['keywords'] = $this->document->getKeywords();
```

In fact, land and title are set and saved in oc_setting

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
can nt replicate and n idea what u are talking about

**Comment by cgcmart** [comment]
@danielkerr 
What is displayed by your browsers?

**Comment by danielkerr** [comment]
The default store template

**Comment by mhcwebdesign** [comment]
@cgcmart : Getting a blank is usually a sign that there is an Internal Server 500 error. You should check your server's error log (not the same as the OpenCart error.log!)

**Comment by mhcwebdesign** [comment]
@cgcmart : Well, nobody else seems to be able to reproduce your error. You should provide some more details, and your website URL.

**Comment by cgcmart** [comment]
home page: https://cgcmart.com

**Comment by mhcwebdesign** [comment]
@cgcmart: Well, your server is returning zero bytes, most likely it's a wrongly configured server and not an OpenCart issue. You should re-post on the OpenCart forum to find someone to look into it.

**Comment by cgcmart** [comment]
I don't think so. Home had displayed until yesterday after merged files from https://github.com/opencart/opencart/issues/11641 
upload/admin/model/sale/subscription.php
upload/install/controller/upgrade/upgrade.php
upload/install/view/template/upgrade/upgrade.twig
upload/install/controller/upgrade/upgrade_2.php
