### ISSUE TITLE
Opencart default extensions english language file not loaded when using non-english admin language

### ISSUE THREAD

**Issue by bull5-i** [opencart/opencart#11806]
**What version of OpenCart are you reporting this for?**
4.0.1.1

**Describe the bug**
When admin language is changed to something other than English, then the OpenCart Default Extensions do not show properly translated strings.

**To Reproduce**
1. Install the OpenCart Default Extensions
2. Install a non-english language (eg "OpenCart Language Example" would do as well), enable it and set admin language to the newly installed language.
3. Observe the issue

**Expected behavior**
When translation files for given language do not exist, then the extension should revert to the English language or the language that came with the extension.

*How would one go about adding translations for other third party extensions (eg OpenCart Default Extensions)?*

**Screenshots / Screen recordings**
Extensions>Extensions>Modules
<img width="787" alt="Screenshot 2022-10-15 at 23 54 28" src="https://user-images.githubusercontent.com/2567658/196007500-07abaee8-32e8-458c-bf96-2a9c0e3484ed.png">

The Banner module edit page:
<img width="834" alt="Screenshot 2022-10-15 at 23 55 03" src="https://user-images.githubusercontent.com/2567658/196007508-4ee6970e-3a86-4bfa-9f9f-bb73f690d89f.png">

**Server / Test environment (please complete the following information):**
 - Local development
 - Operating system: OSX
 - PHP version: 8.1.6
 - Apache version: nginx/1.21
 - Browser(s) tested with: not applicable

**Comment by condor2** [comment]
https://github.com/opencart/opencart/discussions/11601
