### ISSUE TITLE
A big issue with modules compatibility

### ISSUE THREAD

**Issue by sv2109** [opencart/opencart#11800]
There is a very commonly used rule that is used by many software developers. It says that only the major version of the software can break compatibility but not minor or especially patch or revision versions. And it's a very good rule. Developer can create an extension for, for example, 4.0.0.0 version of a CMS and can be sure that this extension will work on 4.1, 4,2, 4.3, and even on 4.99. It's good for developers, it's also very good for all customers, and as a result for the CMS.
But what do we have in OpenCart right now? 
Recently I've created a free module for OpenCart 4 and what have I discovered?
1. In 4.0.0.0 you can create a module archive with subfolders and it's working, but in 4.0.1.0 it doesn't work anymore
2. In 4.0.0.0 you can add a new Event like this:
addEvent($code,$description,$trigger,$action);
but in 4.0.1.0 it uses event array like this
addEvent($event);
5. 4.0.0.0 uses utf8_strlen() function
but 4.0.1.0 uses \Opencart\System\Helper\Utf8\strlen
4. before 4.0.2.0 routes were with "|" separator: 'marketplace/event|save'
but from 4.0.2.0 it's ".": 'marketplace/event.save'

And this is what I found by myself, there are probably many more similar changes and there is no documentation at all where I can read about all the changes. 

Most of the improvements are definitely better but why not add them in the major version, or at least add them without breaking compatibility? Otherwise, the whole module development process turns into hell. Because the module I've created for 4.0.0.0 won't work on 4.0.1.0, the module I've created for 4.0.1.0 won't work on 4.0.2.0, and so on... And I need either create a different module version for each OpenCart version (and support all of them in the future) or add dozens of
if (version_compare(VERSION... constructions into the code. 
And it isn't even a minor (4.1) version yet! 
This is a very bad development approach. And it's bad for everyone. Developers will hate to create new modules for OpenCart, users will get fewer modules, a lot of conflicts when a module written for 4.0.1.0 won't work on 4.0.2.0 and eventually they will hate the whole OpenCart too. 

So why not use standard software versioning rules where only a major version of the software can break compatibility?

**Comment by osworx** [comment]
This is how OpenCart "operates" since many years.

**Comment by danielkerr** [comment]
u can actually code work arounds for these.
