### ISSUE TITLE
Creation of dynamic property is deprecated

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#11803]
A list of some issue with dynamic properties are in the attached file.

[dynamic-properties.txt](https://github.com/opencart/opencart/files/9788081/dynamic-properties.txt)

Basically, it is for php 8.2.

**Comment by mhcwebdesign** [comment]
PHP 8.2 hasn't even been released yet.

As regards deprecation of dynamic properties: See https://wiki.php.net/rfc/deprecate_dynamic_properties

The quickest solution would be the usage of `#[AllowDynamicProperties]`

**Comment by danielkerr** [comment]
still works with getters and setters i heard

**Comment by danielkerr** [comment]
ok ill look into it.

**Comment by danielkerr** [comment]
php8.2 is not out yet. as soon as it is i will fix what ever needs fixing.

**Comment by TheCartpenter** [comment]
Will have to integrate the namespaces, without addPath, in the opencart-3 repository shortly to avoid deprecation messages to grow on the platform. This way, even though it grows, it will be more manageable to change helper functions when needed like the MB. As an impact, extensions will be affected, regardless of the used Engine, but will be more solvable solution from the core in the future to make modifications where needed.

Right now, without namespaces, we don't have those options on previous versions than OC 4.x.

**Comment by mhcwebdesign** [comment]
I have now updated the 3.0.x.x_Maintenance branch for supporting PHP 8.2.

Of course, some 3rd party extensions might have to be updated, too, in addition to the OpenCart core.

**Comment by anytizer** [comment]
> still works with getters and setters i heard

Looks like it does not. I found this:

```
Unknown: Creation of dynamic property Opencart\System\Engine\Proxy::$database is deprecated in __/system/engine/proxy.php on line 39
```

which looks like the __set() function.
I will collect/send you more information as I try to setup under 8.2 RC4.

**Comment by mhcwebdesign** [comment]
@anytizer : Or you could try our pull request https://github.com/opencart/opencart/pull/11877

**Comment by anytizer** [comment]
@mhcwebdesign I will try. Thanks for the notification.

**Comment by danielkerr** [comment]
i can not get php 8.2 installed properly with mysql on windows. i need to wait until it properly released.

**Comment by TheCartpenter** [comment]
> i can not get php 8.2 installed properly with mysql on windows. i need to wait until it properly released.

On November 24th, the final release has been announced to be released on this date. Therefore, official bugfixes instead of workarounds can be worked on.

**Comment by bloodyKnuckles** [comment]
I used https://github.com/mhcwebdesign/opencart-php8 to install (on almalinux 8, nginx). No warnings nor errors.

**Comment by mhcwebdesign** [comment]
> I used https://github.com/mhcwebdesign/opencart-php8 to install (on almalinux 8, nginx). No warnings nor errors.

That's the same as https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance

**Comment by bloodyKnuckles** [comment]
> > I used https://github.com/mhcwebdesign/opencart-php8 to install (on almalinux 8, nginx). No warnings nor errors.
> That's the same as https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance

I tried https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance — but got PHP "deprecated" warnings, that I didn't get with https://github.com/mhcwebdesign/opencart-php8.

**Comment by mhcwebdesign** [comment]
> > > I used https://github.com/mhcwebdesign/opencart-php8 to install (on almalinux 8, nginx). No warnings nor errors.
> 
> > That's the same as https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
> 
> I tried https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance — but got PHP "deprecated" warnings, that I didn't get with https://github.com/mhcwebdesign/opencart-php8.

That's not possible, the https://github.com/mhcwebdesign/opencart-php8/tree/3.0.x.x_Maintenance is the same as https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance

**Comment by bloodyKnuckles** [comment]
I might be missing something—on this page: https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance I copied the Code > HTTPS link: https://github.com/opencart/opencart.git and "git cloned" it. Installation produced the PHP deprecated warnings.

**Comment by bloodyKnuckles** [comment]
> > > > I used https://github.com/mhcwebdesign/opencart-php8 to install (on almalinux 8, nginx). No warnings nor errors.
> > 
> > 
> > > That's the same as https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
> > 
> > 
> > I tried https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance — but got PHP "deprecated" warnings, that I didn't get with https://github.com/mhcwebdesign/opencart-php8.
> 
> That's not possible, the https://github.com/mhcwebdesign/opencart-php8/tree/3.0.x.x_Maintenance is the same as https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance

I might be missing something—on this page: https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance I copied the Code > HTTPS link: https://github.com/opencart/opencart.git and "git cloned" it. Installation produced the PHP deprecated warnings.

**Comment by TheCartpenter** [comment]
> > > > > I used https://github.com/mhcwebdesign/opencart-php8 to install (on almalinux 8, nginx). No warnings nor errors.
> > > 
> > > 
> > > > That's the same as https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
> > > 
> > > 
> > > I tried https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance — but got PHP "deprecated" warnings, that I didn't get with https://github.com/mhcwebdesign/opencart-php8.
> > 
> > 
> > That's not possible, the https://github.com/mhcwebdesign/opencart-php8/tree/3.0.x.x_Maintenance is the same as https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
> 
> I might be missing something—on this page: https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance I copied the Code > HTTPS link: https://github.com/opencart/opencart.git and "git cloned" it. Installation produced the PHP deprecated warnings.

If you try to clone with: https://www.github.com/opencart/opencart-3 repository, do you still get deprecated messages?

**Comment by bloodyKnuckles** [comment]
> If you try to clone with: https://www.github.com/opencart/opencart-3 repository, do you still get deprecated messages?

Yes.
![Screen Shot 2022-11-25 at 5 03 20 PM](https://user-images.githubusercontent.com/3579179/204061978-ec8d3d23-3ed6-4387-bd71-a79c7f9858fa.png)

**Comment by mhcwebdesign** [comment]
The 3.0.x.x_Maintenance code is here: https://github.com/opencart/opencart/archive/refs/heads/3.0.x.x_Maintenance.zip

**Comment by TheCartpenter** [comment]
> > If you try to clone with: https://www.github.com/opencart/opencart-3 repository, do you still get deprecated messages?
> 
> Yes. ![Screen Shot 2022-11-25 at 5 03 20 PM](https://user-images.githubusercontent.com/3579179/204061978-ec8d3d23-3ed6-4387-bd71-a79c7f9858fa.png)

Yes, the dynamic property errors is in the works for PHP 8.2. This PHP version has been officially released since today and being worked on. OC 4 is also expected to work with this PHP 8.2 but don't know when exactly the solution will be populated.

**Comment by danielkerr** [comment]
is php8.2 released yet?> NO! 

it will take me 3 minutes to fix what ever changes have been made.

**Comment by TheCartpenter** [comment]
> is php8.2 released yet?> NO!
> 
> it will take me 3 minutes to fix what ever changes have been made.

Delayed until Dec. 8.

**Comment by mhcwebdesign** [comment]
It's currently at **PHP 8.2.0~rc7-1** .

It's working fine for the 3.0.x.x_Maintenance, and will be fairly easy to adjust the master branch, too.

**Comment by bloodyKnuckles** [comment]
> The 3.0.x.x_Maintenance code is here: https://github.com/opencart/opencart/archive/refs/heads/3.0.x.x_Maintenance.zip

Using this install, I get a MySQL error on step 3:

```
DROP TABLE IF EXISTS `oc_api`;
ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails
```

**Comment by bloodyKnuckles** [comment]
> > The 3.0.x.x_Maintenance code is here: https://github.com/opencart/opencart/archive/refs/heads/3.0.x.x_Maintenance.zip
> 
> Using this install, I get a MySQL error submitting step 3:

https://github.com/mhcwebdesign/opencart-php8

...installs without error.

**Comment by TheCartpenter** [comment]
> > > The 3.0.x.x_Maintenance code is here: https://github.com/opencart/opencart/archive/refs/heads/3.0.x.x_Maintenance.zip
> > 
> > 
> > Using this install, I get a MySQL error submitting step 3:
> 
> https://github.com/mhcwebdesign/opencart-php8
> 
> ...installs without error.

If you try to install with: https://www.github.com/opencart/opencart-3 repository, do you get any errors?

**Comment by bloodyKnuckles** [comment]
Yes. I posted a screenshot of the errors in a previous post. They were the PHP 8.2 "deprecated" errors.

-------- Original Message --------

**Comment by bloodyKnuckles** [comment]
> > Using this install, I get a MySQL error submitting step 3:
> > ```
> > DROP TABLE IF EXISTS `oc_api`;
> > ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails
> > ```
> 
> @bloodyKnuckles If doing a clean install make sure your database in completely empty with no tables.

That worked!—with an empty database, https://github.com/opencart/opencart/archive/refs/heads/3.0.x.x_Maintenance.zip installed without error or warning.

**Comment by bloodyKnuckles** [comment]
Using https://github.com/opencart/opencart/archive/refs/heads/3.0.x.x_Maintenance.zip , I encountered some "PHP 8.2 deprecation" glitches when making an order.

In file `system/library/mail/mail.php` I inserted, starting at line 4:

    public $to;
    public $from;
    public $sender;
    public $reply_to;
    public $subject;
    public $text;
    public $html;
    public $attachments;
    public $parameter;
    public $adaptor;
    public $smtp_hostname;
    public $smtp_username;
    public $smtp_password;
    public $smtp_port;
    public $smtp_timeout;

**Comment by mhcwebdesign** [comment]
Thanks for pointing it out.

Try these extra lines:

```
	protected $to;
	protected $sender;
	protected $from;
	protected $reply_to;
	protected $html;
	protected $text;
	protected $attachments;
	protected $parameter;
	protected $subject;

```
You shouldn't need the ones for smtp. Also, they should be protected or private. If it works, we'll make a pull request and update.

**Comment by bloodyKnuckles** [comment]
Changing `public` to `protected` produces the `Creation of dynamic property Mail::$to is deprecated` error.

Changing back to `public` and it works.

Then I rem'd these out:

```
//public $adaptor;
//public $smtp_hostname;
//public $smtp_username;
//public $smtp_password;
//public $smtp_port;
//public $smtp_timeout;
```

...and I got the `Creation of dynamic property Mail::$adaptor is deprecated` error, for everyone of them.

I restored the previous list:

```
public $to;
public $from;
public $sender;
public $reply_to;
public $subject;
public $text;
public $html;
public $attachments;
public $parameter;
public $adaptor;
public $smtp_hostname;
public $smtp_username;
public $smtp_password;
public $smtp_port;
public $smtp_timeout;
```
...and all is well.

**Comment by bloodyKnuckles** [comment]
> You shouldn't need the ones for smtp.

I tried removing just those, leaving the rest, including `$adaptor`, and I unexpectedly got a "...deprecated" error for `$adaptor`, (along with all the `$smtp_` properties).

**Comment by mhcwebdesign** [comment]
I think you are right, because, when looking at the system/library/mail.php it copies them all over:

```
		foreach (get_object_vars($this) as $key => $value) {
			$this->adaptor->$key = $value;
		}
		
		$this->adaptor->send();

```

I'll test it. The same problem might exist for the system/library/mail/smtp.php.

Perhaps it might be a good idea to add **__get** and **__set** magic methods to the system/library/mail/mail.php and system/library/mail/smtp.php files and to let them just internally use a 

protected $data;

for storing all these dynamic properties.

**Comment by mhcwebdesign** [comment]
@bloodyKnuckles: OK, try these changes, I just tested it on my local PHP 8.2 server:

File system/library/mail.php:
```
<?php
...
class Mail extends \stdClass {
...
```

File system/library/mail/mail.php:
```
<?php
namespace Mail;
class Mail extends \stdClass {
....
```

File system/library/mail/smtp.php:

```
<?php
namespace Mail;
class Smtp extends \stdClass {
....
```

Let me know what you get. These mail classes are almost being mistreated like a proxy class, so above is a lazy approach, but it should work.

**Comment by TheCartpenter** [comment]
Another set of ```srdclass```.

**Comment by bloodyKnuckles** [comment]
> @bloodyKnuckles: OK, try these changes, I just tested it on my local PHP 8.2 server:

That works. I started with a fresh copy of https://github.com/opencart/opencart/archive/refs/heads/3.0.x.x_Maintenance.zip , added the `exends \stdClass` in those files, and no warnings or errors on install.

**Comment by TheCartpenter** [comment]
I'm awaiting on Dec. 8.

**Comment by mhcwebdesign** [comment]
> > @bloodyKnuckles: OK, try these changes, I just tested it on my local PHP 8.2 server:
> 
> That works. I started with a fresh copy of https://github.com/opencart/opencart/archive/refs/heads/3.0.x.x_Maintenance.zip , added the `exends \stdClass` in those files, and no warnings or errors on install.

That's great. Could also test it with SMTP, if possible? I don't get these errors about the dynamic properties anymore either, however, when using SMTP with PHP8.2 the text portion is completely stripped off.

**Comment by bloodyKnuckles** [comment]
> That's great. Could you also test it with SMTP, if possible? I don't get these errors about the dynamic properties anymore either, however, when using SMTP with PHP8.2 the text portion is completely stripped off.

I get an empty response, and the nginx error log reports a php `fsockopen` error `Error: DATA not accepted from server!`, status code 250. 

It may be my configuration—my mailserver is on `localhost`, and I also tried: `127.0.0.1`, which resulted in that error.

**Comment by mhcwebdesign** [comment]
> I get an empty response, and the nginx error log reports a php `fsockopen` error `Error: DATA not accepted from server!`, status code 250.
> 
> It may be my configuration—my mailserver is on `localhost`, and I also tried: `127.0.0.1`, which resulted in that error.

Do you get the same error when using PHP 8.1 ?

**Comment by bloodyKnuckles** [comment]
> Do you get the same error when using PHP 8.1 ?

I have not used opencart with PHP 8.1—fresh server, fresh install.

**Comment by mhcwebdesign** [comment]
@bloodyKnuckles: Try our pull request https://github.com/opencart/opencart/pull/12071 for your PHP 8.2 OpenCart server's smtp.

**Comment by mhcwebdesign** [comment]
> im trying something new

Your new idea of using an **$option** array for the **system/library/mail.php** makes sense, but still needs some finishing up. At the moment it's not possible to send mails, still getting some errors. I assume it's still work in progress?

**Comment by danielkerr** [comment]
Yes not finished

**Comment by sabetiH** [comment]
> A list of some issue with dynamic properties are in the attached file.
> 
> [dynamic-properties.txt](https://github.com/opencart/opencart/files/9788081/dynamic-properties.txt)
> 
> Basically, it is for php 8.2.

Hi.
the solution is to use the #[AllowDynamicProperties] attribute just above the class definition.

In PHP 8.0 classes marked with #[AllowDynamicProperties] and their children can continue to use dynamic properties without being deprecated or removed.

You must in the file:
system\engine\proxy.php
like this:
```
#[AllowDynamicProperties]
class Proxy {
```
And in the following file:
system\library\template\twig.php
like this:
```
#[\AllowDynamicProperties]
final class Twig {
```

Apply the changes.
