### ISSUE TITLE
Unable to create the cache directory

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#11802]
I am trying to install OC under PHP 8.2.
Due to the various changes and requirements, the installation did not go smoothly.

The installation page showed continue button; and after this, when loading the home page, I see:

```
Warning: mkdir(): Permission denied in __/system/storage/vendor/twig/twig/src/Cache/FilesystemCache.php on line 50
Warning: file_put_contents(__/system/storage/logs/error.log): Failed to open stream: Permission denied in __/system/library/log.php on line 34
RuntimeException: Unable to create the cache directory (__/system/storage/cache/template/80). in __/system/storage/vendor/twig/twig/src/Cache/FilesystemCache.php on line 53
```

When installer continued, the website should open normally.
And the installer page should stop or warn the user when the cache directory is not create-able.

**Comment by danielkerr** [comment]
i think this is u have the security settings to high.
