### ISSUE TITLE
{master branch} filemanager image folder cannot be deleted.

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#11811]
{master branch} filemanager image folder cannot be deleted.

**Comment by mhcwebdesign** [comment]
That's correct, you should not be able to delete the image folder with Opencart's built-in file manager.

**Comment by chongshengdz** [comment]
> That's correct, you should not be able to delete the image folder with Opencart's built-in file manager.

yes, where there are photos in the image folder

**Comment by mhcwebdesign** [comment]
If you are talking about removing a folder located within the image/catalog folder: This can only be done when it is empty. See e.g. https://www.php.net/manual/en/function.rmdir.php
