### ISSUE TITLE
Code sniffing standard link is broken.

### ISSUE THREAD

**Issue by glodov** [opencart/opencart#11825]
I found a link to a code sniffing standard in the official github repository of OpenCart and it is not working anymore, 404 error is thrown.

There is a [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) standard here: https://github.com/opencart/opencart/tree/master/tests/phpcs/OpenCart

**Comment by glodov** [comment]
@danielkerr really? 🤦‍♂️
Don't wanna fix the bug or guide the community?

**Comment by danielkerr** [comment]
not using code sniffer anymore

**Comment by glodov** [comment]
This is why I asked. 🤦‍♂️
Where is code sniff @danielkerr ?
It's missing in current version, need to go back to v3 to find them?
