### ISSUE TITLE
[4.0.1.1] Using a stored address in the checkout breaks the invoice/shipping list

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#11862]
When logged in and using a stored address in the checkout, the "payment_address_format" and "shipping_address_format" columns in the "order" database table will be filled in with the raw HTML, and not the actual address format data. For example, instead of storing this:

```
{firstname} {lastname}
{company}
{address_1}
{address_2}
{city}, {zone} {postcode}
{country}
```

it will store this:

`
Tester Testing<br/>123 Main Street<br/>Beverly Hills, California 90210<br/>United States
`

This causes the invoice view and shipping list for the order to output the HTML tags instead of the proper address. I traced the issue to the following lines:

```
IN:
/catalog/controller/checkout/payment_address.php
/catalog/controller/checkout/shipping_address.php

LINES:
$address_info = $this->model_account_address->getAddress($address_id);
```

To fix it, some code will need to be added after those lines to set the "address_format" properly in the session data.

**Comment by TheCartpenter** [comment]
May have to verify this for OC-3 as well ...

**Comment by TheCartpenter** [comment]
Which repository of Opencart 3.0 are you referring to?

**Comment by ClearThinking** [comment]
All repositories of 3.0. The code for the checkout is different in 3.0 (and consistent with 1.5 and 2.x versions) so this 4.0-specific bug doesn't apply.

**Comment by TheCartpenter** [comment]
One thing I could think of, so far, is the (string) hanging in front in the catalog/model/checkout/order.php file whereas previous releases don't have this enforced cast to insert the data for the payment_address_format and the shipping_address_format fields.

**Comment by ClearThinking** [comment]
The problem is that the this->model_account_address->getAddress() function returns the "address_format" parameter already converted based on the address. It doesn't return the address format itself, but the already-formatted address data.

Changing that to return the address format may break other things, so my proposed solution is to add some code after the lines I mentioned above. You'd need to retrieve the "address_format" for the country from the database, and then put that into the session variables:

$this->session->data['payment_address']['address_format']
and
$this->session->data['shipping_address']['address_format']

**Comment by danielkerr** [comment]
http://localhost/opencart-master/upload/index.php?route=account/address&language=en-gb&customer_token=96d062c85bb5670f621bb3fc77

**Comment by danielkerr** [comment]
i think its fixed now
