### ISSUE TITLE
[master] Module status in list is wrong

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11868]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
Wrong display of current status of modules. Modules are enabled but displayed in the list as disabled.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/197182528-b77c7d1a-ed7d-4372-84ab-900519bce228.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 106.0

**Comment by PhamToan** [comment]
for fixing, i have created pull request ... https://github.com/opencart/opencart/pull/11822

but @danielkerr  didn't merge

**Comment by pemaier** [comment]
Problem is solved.
