### ISSUE TITLE
Can confirm this issue on MacOS no matter which browser.

### ISSUE THREAD

**Issue by mklarsen** [opencart/opencart#11879]
Can confirm this issue on MacOS no matter which browser. 

If somebody on Windows or Linux can confirm that the change to `*.ocmod.zip` as mentioned by @mklarsen above would be great to have the fix in next release.

_Originally posted by @ndeet in https://github.com/opencart/opencart/issues/11026#issuecomment-1271521615_

Just tested the on Linux, and i worked as i described :-)

**Comment by danielkerr** [comment]
dont open double issues
