### ISSUE TITLE
[4.0.1.1]  Uploading folders and files via extensions in Opencart

### ISSUE THREAD

**Issue by Reitier** [opencart/opencart#11883]
I'm working with the latest opencart 4.0.1.1
I need to load the language files in the correct folder. I am working with .ocmod.zip and install.json. 
All the files go up to the extensions folder, I need them to go to the language folder. 

admin/language/
catalog/language/
extension/opencart/admin/language/
extension/opencart/catalog/language/

I have not seen any solution on this issue.
Does anyone know how I should do it? 
Thanks!!!

**Comment by danielkerr** [comment]
check the example language extension i have included. it shjows u hoow to setup ur own language. its no longer a drop in extension system

**Comment by Reitier** [comment]
Thanks @danielkerr Where can I find the example you mentioned?
