### ISSUE TITLE
"phpmailer for 2.x" extension - seen on OC4 installation

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#11888]
When I click into Extensions > Marketplace, I see phpmailer for 2.x as paid extension. My OC is a new installation, and hopefully, it should not list out any paid extensions in my dashboard.

![image](https://user-images.githubusercontent.com/5563341/198859207-0479e1cb-22dc-4473-aedd-489a730952e2.png)

Further, the OC version is 4, not 2.x. And, this is the only extension listed. Other tabs are empty.

**Comment by danielkerr** [comment]
im not sure how hes managed to post his extension in unreleased version.

**Comment by danielkerr** [comment]
i think i added it for testing.
