### ISSUE TITLE
[master] New install error - Error: Call to undefined function in install.php on line 108

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11885]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A new install of OpenCart give the error
Error: Call to undefined function Opencart\System\Helper\General\token() in /home/aqq20848/public_html/opencart/master.demo/install/model/install/install.php on line 108

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 106.0

**Comment by danielkerr** [comment]
being worked on.

**Comment by pemaier** [comment]
Thank you. Just for info... today I got
Error: Call to undefined function Opencart\System\Helper\DbSchema\db_schema() in /home/aqq20848/public_html/opencart/master.demo/install/model/install/install.php on line 11

**Comment by pemaier** [comment]
Thank you - Problem solved.
