### ISSUE TITLE
[master branch] shipping tax and vat don't add to order total.

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#11884]
![tax-vat](https://user-images.githubusercontent.com/30888843/198536745-d9ed40c8-224c-4702-8437-db91064bed78.jpg)

**Comment by danielkerr** [comment]
set correct tax zone

**Comment by chongshengdz** [comment]
> set correct tax zone

I set it correctly.
as you can see the flat shipping rate is different in the above picture.
