### ISSUE TITLE
Tooltips are broken again

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#11900]
This PR broke admin tooltips again.
https://github.com/opencart/opencart/commit/9f50c264796e9c4f6f624880ffd64e0ac0484080#diff-6c896305ca8e127a8e28a98a4bcd589a6f78c6091330c663887cbab9844d0bae

`getOrCreateInstance` does not work the same as `getInstance` when instance exists. I don't know why, I did not dig BS sources that deep, but my experiments showed that we need to use `getInstance` check to make dynamic tooltips work correctly.

Here is a video of a bug. On first hover tooltip is not shown over a button, but is shown on child hover or second hover.
https://user-images.githubusercontent.com/6297070/199306133-a4a11bd2-b178-4721-a396-800e1a09f33f.mp4

**Comment by danielkerr** [comment]
yes because the code was deleting all tooltips intead of using the show hide.
