### ISSUE TITLE
[4.0.1.1] Can't create custom extension/module - always 404

### ISSUE THREAD

**Issue by sapabg** [opencart/opencart#11906]
**What version of OpenCart are you reporting this for?**
4.0.1.1

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Can't create custom extensions! When I try to edin the settings (start the index function in the admin/controller/module/simple.php) it renders the  404 - File not found page.

**To Reproduce**
1. Download Simple Extension zip from https://drive.google.com/file/d/1pFDQ57lTIqLGyc39ru7gR8aM8WJgDqDD
It has only 2 files - install.json and simple.php (admin/controller/module/simple.php);
2. Go to admin -> Extensions -> Installer;
3. Click Upload (top right);
4. Select the simple plugin zip;
5. Click the "+" (Install) button on the Simple Plugin row of the table;
6. Go to Extensions->Extensions
7. Select Modules from filter dropdown;
8. Click the "+" (Install) button on the simple_heading_title row;
9. Click on the "Edit" (pen) button;

**Expected behavior**
Should echo 'AAAAAAAAAAAAAAAAAAAA'

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? - deployed to a server
 - Operating system - linux
 - PHP version - 8
 - Apache version - 2.4.54
 - Browser(s) tested with - crome

**Additional context**

I moved the files inside the catalog/extension/OPENCART folder, added the files manually in the database in extension_path table and it worked but it will NOT work if it is not in the catalog/extension/OPENCART folder. I tried so many things and I could not get it to work.
Any help or at least documentation will be apretiated!

**Comment by mhcwebdesign** [comment]
This is not an OpenCart bug. Use this namespace in your simple.php file:

`namespace Opencart\Admin\Controller\Extension\Simple\Module;`

The OpenCart 4 extension name-spacing is a bit confusing as it doesn't reflect the underlying folder structure.

**Comment by sapabg** [comment]
> This is not an OpenCart bug. Use this namespace in your simple.php file:
> 
> `namespace Opencart\Admin\Controller\Extension\Simple\Module;`
> 
> The OpenCart 4 extension name-spacing is a bit confusing as it doesn't reflect the underlying folder structure.

Thank you!
