### ISSUE TITLE
Admin Currency 

### ISSUE THREAD

**Issue by Vilgar** [opencart/opencart#11901]
**What version of OpenCart are you reporting this for?**
4.0.1.1

**Describe the bug**
when you try to create currency first save click is creating the currency, but after the second click it creates the same data as the new currency,

**To Reproduce**
1. Go to admin > currency > create
2. Click on the save button
3. Click the second time in the save button
4. See error as a second one created

**Expected behavior**
when you try to create currency first save click is creating the currency, but after the second click it creates the same data as the new currency,

**Server / Test environment (please complete the following information):**
 - Development
 - Centos
 - 7.4
 - Chrome
 - Version 106

**Comment by TheCartpenter** [comment]
OC 4.x supports PHP 8.x<2 releases. Your specs states PHP 7.4.

**Comment by pemaier** [comment]
This behavior is when you create a NEW product, category, ... in short at all new created entries.
I use php 8.1 and FF 106.0

**Comment by danielkerr** [comment]
not happening for me
