### ISSUE TITLE
Error: Call to undefined function Opencart\System\Library\imagecreatefromjpeg() 

### ISSUE THREAD

**Issue by chendelin1982** [opencart/opencart#11918]
**What version of OpenCart are you reporting this for?**

Opencart 4.0.1.1
PHP: 8.1
Apache2.4
Linux
chrome

**Describe the bug**

Installed opencart successfully, login to console, open 【Catolog】-【Product】，error below

```
Error: Call to undefined function Opencart\System\Library\imagecreatefromjpeg() in /var/www/html/system/library/image.php on line 49
```

**Additional context**
Other function is ok

**Comment by danielkerr** [comment]
ur linux is not setup correctly. possibly needs to jpg library

**Comment by chendelin1982** [comment]
> ur linux is not setup correctly. possibly needs to jpg library

Daniel, Thank you
