### ISSUE TITLE
  Possible data error - FK constrain fail (or, order of data loading)

### ISSUE THREAD

**Issue by picsouds** [opencart/opencart#11932]
same error reported (https://github.com/opencart/opencart/issues/11878)  - fresh install from master

> Exception: Error: SQLSTATE[23000]: Integrity constraint violation: 1452
>
> Cannot add or update a child row: a foreign key constraint fails
> (`oc`.`oc_attribute`, CONSTRAINT `oc_attribute_ibfk_1` FOREIGN KEY (`attribute_group_id`) REFERENCES `oc_attribute_group` (`attribute_group_id`))
> 
> Error Code : 23000
> 
> INSERT INTO `oc_attribute` (`attribute_id`, `attribute_group_id`, `sort_order`) VALUES(1, 6, 1),(2, 6, 5),(3, 6, 3),(4, 3, 1),(5, 3, 2),(6, 3, 3),(7, 3, 4),(8, 3, 5),(9, 3, 6),(10, 3, 7),(11, 3, 8); in __/system/library/db/pdo.php on line 71

foreign key seems to be always in https://github.com/opencart/opencart/blob/master/upload/system/helper/db_schema.php

**Comment by danielkerr** [comment]
there are no contraints in master or lastest released version

**Comment by picsouds** [comment]
just had $this->connection->query("SET FOREIGN_KEY_CHECKS = 0"); in  [pdo.php](https://github.com/opencart/opencart/blob/master/upload/system/library/db/pdo.php) (ok in [mysqli.php](https://github.com/opencart/opencart/blob/master/upload/system/library/db/mysqli.php#L27))

**Comment by stalker780** [comment]
What the sense in foreign keys with disabled constraints?

A structure with consistency check but with a lifehack for ignoring this check.
This breaks any external connection to OC4 DB.

For example if I try to work with DB from HeidiSQL or PMA, I cannot send "SET FOREIGN_KEY_CHECKS = 0" on every request. I get tons of foreign keys errors. 

This may result in issues during backup and restore OC database process with many tools and hosting scripts.
