### ISSUE TITLE
Unable to choose an "Order Status" at first when creating an order manually by admin

### ISSUE THREAD

**Issue by Miguel-MultiSafepay** [opencart/opencart#11940]
**What version of OpenCart are you reporting this for?**

Latest OpenCart 4.0.1.1

**Describe the bug**

There is no option to choose the order status when an order is created by admin.

It always gets "Pending" by default.

This is only possible to do later, namely using "Add History".

I think that this should be also be possible to do at first, when you create the order first time, as there are circunstancies where is much more useful to have this possibility at this moment, for example: when we want to send an email to a client at the moment of creating an order, so we can send a payment link to her/him at that point inside the email.

What section does it affect?

**To Reproduce**
1. Go to Admin -> Sales -> Orders -> Add New
2. Try to find to choose an "Order Status" in the first form [namely Add Order]

**Comment by danielkerr** [comment]
not really qa bug. u save the orddr by clicking the confirm button then u add the order status
