### ISSUE TITLE
[master] New subscrition plan is limited in input values

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11946]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
A 0 is not possible to enter in the field.

**To Reproduce**
Create a new subscription plan with trial ... set this to 0 if you want payments until they are cancelled.

**Expected behavior**
Error message appear.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/201098237-e44a72f0-7936-486c-a3ca-3ea8b48c6386.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 106.0

**Comment by TheCartpenter** [comment]
There seem to be a valid point here since cron/subscription.php file does validate whether the trial_duration is or isn't the case from this line:

```if ($result['trial_status'] && (!$result['trial_duration'] || $result['trial_remaining'])) {```

Therefore, it should also implicit the use of 0 in the subscription plan rather than restricting 'or' to edit the validation from cron/subscription.

**Comment by TheCartpenter** [comment]
After reviewing this, it is still possible that the trial duration may require a higher value than 0 since the trial remaining could take the lead over the trial duration by extension on anyhow. Therefore, this is not an issue.

**Comment by pemaier** [comment]
Then the description text is not right.

**Comment by TheCartpenter** [comment]
> Then the description text is not right.

More info needed.

**Comment by pemaier** [comment]
Please have a look at pull request #11960 and #11959
