### ISSUE TITLE
Why did commit the line 271 from pull #11947

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#11953]
https://github.com/opencart/opencart/blob/93b86b0f08fe54491d7d7f5c9ee276eeaad09fff/upload/system/library/cart/cart.php#L271

line 270:
`'trial_duration'       	=> $subscription_query->row['trial_duration'],`

line 271: 
`'trial_remaining'       => $subscription_query->row['trial_duration'],`

why did commit this line?

**Comment by TheCartpenter** [comment]
Because it's the way it has to be. The duration field in that library file is the same. This time, it's simply for the trial. The reason why you're wondering now it's because it's been missing since all this time.

**Comment by danielkerr** [comment]
u minus remaining every day starting from the duration
