### ISSUE TITLE
Infinite loop on first save of new module

### ISSUE THREAD

**Issue by redbraz** [opencart/opencart#11966]
**What version of OpenCart are you reporting this for?**
Opencart 4.0.1.1

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
--- I noticed that when creating a new module there is an infinite loop when clicking the save button continuously.
For example: if you go to extension > "Featured" do a simple configuration and click on save several times it will create several modules in the database in the table "oc_module".
I believe that this can generate a series of problems, since an inexperienced user may find that he is not saving the current settings and create many modules without knowing it.

**To Reproduce**
1 - Go to extensions > select a Featured module
2 - Click on create new
3 - Make the settings, such as the module name
4 - click save continuously (about 5 times)
5 - Click on exit module
6 - Note that the amount of modules that you clicked on save in step 4 was created

**Expected behavior**
The correct thing here would be for him to save and return to the list so that this does not happen or not allow this to happen.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Localhost - WampServer
 - Operating system: Windows 10 Pro
 - PHP version: 8.1.4
 - Apache version: 2.4.41
 - Browser(s) tested: Firefox
![error_1](https://user-images.githubusercontent.com/8571832/201502326-f47a5f34-e629-4b79-b862-2b19a05979e1.JPG)
![error_2](https://user-images.githubusercontent.com/8571832/201502327-0270d484-bb25-4d42-85c3-f63aa627b934.JPG)

 - Version: 106.0.5

**Additional context**

**Comment by danielkerr** [comment]
does not happen on master branch. the but is disabled as soon as its clicked and user has to wait until its saved before they can click again. i think this is has already beeen reported and fixed.
