### ISSUE TITLE
opencart 4.0.1.1 design/seo_url

### ISSUE THREAD

**Issue by 007amitgarg** [opencart/opencart#11963]
In admin panel design/seo_url  "Keyword" is having 64 character limit but when you add it via category or product you can add upto 255 characters. So when there is a need to edit a url via design/seo_url you cannot.

Also on the front website the url it is producing is 

Current URL: http://localhost/pd/upload/delhi/new-delhi?route=product/category&language=en-gb
Expected URL: http://localhost/pd/upload/delhi/new-delhi

Why the whole route query string is present in the url when "Use SEO URLs" is already enabled in settings/server

**Comment by danielkerr** [comment]
route=product/category

has to ahave a keyword as well.

**Comment by 007amitgarg** [comment]
> 

Can you please guide me how this can be done please!

**Comment by 007amitgarg** [comment]
> route=product/category
> 
> has to ahave a keyword as well.


Can you please guide me how this can be done please!
