### ISSUE TITLE
after upgrading from 3.0.3.6 to 4.0+

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#11971]
the below problems need to be improved.
(1) all links breaks after upgrading.
(2) seo urls are not reliable, active products from search engines are not found, sometimes the product pages can be visited and something cannot and redirect to error page.
(3) $query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "seo_url` WHERE (`keyword` = '" . $this->db->escape($keyword) . "' OR `keyword` LIKE '" . $this->db->escape('%/' . $keyword) . "') AND `store_id` = '" . (int)$this->config->get('config_store_id') . "' AND `language_id` = '" . (int)$this->config->get('config_language_id') . "'");
the above query consumes too much cpu.

**Comment by chongshengdz** [comment]
> u probably need to clear all ur keywords.

all seo url keywords will recreate automatically?

**Comment by TheCartpenter** [comment]
I'll have to keep an opened eye on this one if previous OC 3 versions could become problematic with the use of the SEOs once upgraded to OC 4.x releases.

**Comment by chongshengdz** [comment]
> I'll have to keep an opened eye on this one if previous OC 3 versions could become problematic with the use of the SEOs once upgraded to OC 4.x releases.

if you don't have enough products to test, i can post the link here.

**Comment by TheCartpenter** [comment]
> > I'll have to keep an opened eye on this one if previous OC 3 versions could become problematic with the use of the SEOs once upgraded to OC 4.x releases.
> 
> if you don't have enough products to test, i can post the link here.

It is more about the ways to handle the queries from OC-3 and OC-4 with the SEOs in-between the upgrades altogether since the URL structures have now changed. However, as per Daniel's question on the above, could you please also confirm this?

**Comment by chongshengdz** [comment]
> > > I'll have to keep an opened eye on this one if previous OC 3 versions could become problematic with the use of the SEOs once upgraded to OC 4.x releases.
> > 
> > 
> > if you don't have enough products to test, i can post the link here.
> 
> It is more about the ways to handle the queries from OC-3 and OC-4 with the SEOs in-between the upgrades altogether since the URL structures have now changed. However, as per Daniel's question on the above, could you please also confirm this?

yes, the URL structures have now changed, and old urls from search engines will lead to page not found.

product pages sometimes redirect to product error pages may be due to one database with multiple store-fronts, anyway, i will test more tomorrow.

**Comment by mhcwebdesign** [comment]
> SEO URLs are NOT RELIABLE, SOMETIMES suddenly Product not found!

To the contrary: SEO Urls, once set up correctly, work just fine in OpenCart 4.

**Comment by TheCartpenter** [comment]
I'll take care of it. There seem to be insufficient steps in the upgrade/upgrade_9 file. Currently, it is not considered for previous OC versions; only for OC 4.

**Comment by TheCartpenter** [comment]
Done: https://github.com/opencart/opencart/pull/11977

**Comment by danielkerr** [comment]
pretty suire they are fine. i think u need to update the so they use | or . in 4.0.2.0

**Comment by Ergotron-Mexico** [comment]
Se ve que opencart  como codigo abierto esta decayendo, cada actualizacion es un mundo de correcciones y andar adivinando y probando correcciones de los foros
