### ISSUE TITLE
seo_url max length 64

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#11972]
Why keyword is limited to 64 chars in controller?
https://github.com/opencart/opencart/blob/13f374f1c05f45226cd905a6c1df73d748262f0c/upload/admin/controller/catalog/product.php#L1075

While DB field has length of 255 chars.
https://github.com/opencart/opencart/blob/13f374f1c05f45226cd905a6c1df73d748262f0c/upload/system/helper/db_schema.php#L7213

64 is too short. Keywords generated by product name over 100 chars are quite common nowadays
example:
apple-watch-hermes-series-4-gps-cellular-40mm-stainless-steel-case-with-bleu-indigo-swift-leather-double-tour-mu6q2-59324

What is the sense of this limit?

**Comment by TheCartpenter** [comment]
It would seem multiple locations needs to be edited, here.

**Comment by TheCartpenter** [comment]
Done:

https://github.com/opencart/opencart/pull/11976
https://github.com/opencart/opencart/pull/11975
https://github.com/opencart/opencart/pull/11974
https://github.com/opencart/opencart/pull/11973

**Comment by TheCartpenter** [comment]
Recently resolved here: https://github.com/opencart/opencart/issues/11963 .
