### ISSUE TITLE
HTTP_HOST can contain the port number and make unreliable the multi-store feature

### ISSUE THREAD

**Issue by Miguel-MultiSafepay** [opencart/opencart#11985]
**What version of OpenCart are you reporting this for?**

4.0.1.1

**Describe the bug**

At .../catalog/controller/startup/setting.php line 7, namely at $hostname =  etcetera, you are using $this->request->server['HTTP_HOST']

I would like to remind that HTTP_HOST can contains the port number like for example localhost:80 and in this case, the validation with the database to find the right 'store_id' won't work if admin/user did not add the 'store_url' including the port too.

This introduces an extra and unnecessary action to take into consideration for the admin/user that most of time won't know what is happening when they add the [sub-domain].domain name for their stores and will see that their multi-store configuration is not working.

This can happen when their configuration for virtualhosts, vitualization (docker, vmware, etc), or apache/nginx conf include the port explicitally in the hostname

**Expected behavior**

To introduce some kind of sanitisation so $hostname sends the right hostname to getStoreByHostname(), and to make a comparison "apple to apple" with what you extract from the database (also sanitised).

I suggest you to extract the raw hostname at both sides cleaning any extra "pollution" with ...

parse_url($entry, PHP_URL_HOST).

The choice to avoid this problem is up to you, obviously.

Thanks!

**Comment by danielkerr** [comment]
"This introduces an extra and unnecessary action to take into consideration for the admin/user that most of time won't know what is happening when they add the [sub-domain].domain name for their stores and will see that their multi-store configuration is not working."

I can get it working on a localhost subdomain no problem. sees like u can not setup multiple localhost properly and reported it as a bug

**Comment by danielkerr** [comment]
"I suggest you to extract the raw hostname at both sides cleaning any extra "pollution" with ...

parse_url($entry, PHP_URL_HOST)."

does not filter anything out just puts it into an array

**Comment by danielkerr** [comment]
u should be setting it up localhost1, localhost2, etc..

**Comment by danielkerr** [comment]
learn to use aliases

**Comment by Miguel-MultiSafepay** [comment]
> parse_url($entry, PHP_URL_HOST).

you use the PHP_URL_HOST component, it will return the host without the port

**Comment by Miguel-MultiSafepay** [comment]
> u should be setting it up localhost1, localhost2, etc..

I just warning you that HTTP_HOST can contain the port and this is not sanitized so this can cause problems.

I see you didn't understand me.
