### ISSUE TITLE
V4 - Product option values revert to zero decimal places on admin reload and save.

### ISSUE THREAD

**Issue by stevehosesolutions1** [opencart/opencart#11991]
All product option values revert to zero decimal places on refresh of the product page in the admin. You can initially save a value which has decimal places, but if you re-save the product at any point, the values will revert to zero decimal places. 

Confirmed from my own installation (4.0.1.1) and the demo store (4.0.0.0):
https://demo.opencart.com/index.php?route=product/product&language=en-gb&product_id=42

The select option prices are:
$6.80
$5.60
$3.20
$4.40

In the admin they revert to zero decimal places. I'm assuming if you save that product (no permissions on demo store), they will save the values as zero decimal places like they do on my own installation.
![image](https://user-images.githubusercontent.com/118457098/202472616-9bbed08a-5dc6-459c-a5c1-3c3617c0fe1e.png)

**Comment by TheCartpenter** [comment]
In the catalog/product controller, the points are rounded. If you check in your PHPMyAdmin console, you should notice the original point values added from your product option table.

**Comment by stevehosesolutions1** [comment]
Yes, the decimals show on the database correctly the first time it’s saved.But, when you reload the product page in admin and resave it (you could be editing anything not just option values), they are saved into the database without decimals.Sent from my iPhoneOn 17 Nov 2022, at 16:35, TheCartpenter ***@***.***> wrote:﻿
In the catalog/product controller, the points are rounded. If you check in your PHPMyAdmin console, you should notice the original point values added from your product option table.

**Comment by TheCartpenter** [comment]
Since you are using a previous of OC, please compare, or replace, the ```admin/controller/catalog/product.php``` and ```admin/model/catalog/product.php``` file to see if the reported issue persists.

**Comment by TheCartpenter** [comment]
As an extra step, ```admin/view/template/catalog/product_form.twig``` file might need to be compared or replaced as well to test this.

**Comment by danielkerr** [comment]
can't believe i made this mistake!
