### ISSUE TITLE
Not able to upload Zip file

### ISSUE THREAD

**Issue by NanheKumar** [opencart/opencart#11990]
I am not able to upload .zip extension

<img width="1435" alt="Screenshot 2022-11-17 at 5 43 28 PM" src="https://user-images.githubusercontent.com/6573683/202443858-341aa9c5-2243-4621-a28c-37df2dc9e6a7.png">

Opencart Version : 4.0.1.1
Operating system : macOS Catalina
PHP version : 8.0
nginx version: nginx/1.23.2

**Solution :** 
Goto File :admin/view/template/marketplace/installer.twig
Line NO : 54
<input type="file" name="file" accept="*.ocmod.zip"/>
add this line  **accept="*.ocmod.zip"**

**Comment by mhcwebdesign** [comment]
This has been solved ages ago: https://github.com/opencart/opencart/issues/11026#issuecomment-1271521615

**Comment by danielkerr** [comment]
will be in a fix in the next release
