### ISSUE TITLE
[master] Install - Language default not found

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11995]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
Due to changes with language there is coming up an error during the install process at the 1st page - default not found. 

**To Reproduce**
1. Start a new install

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/202812408-e902771d-699c-45c1-99f2-0e04488b4ec7.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 106.0

**Additional context**
Only renaming the en-gb.php to default.php is not working.

**Comment by bloodyKnuckles** [comment]
I copied `install/language/en-gb/en-gb.php` to `install/language/en-gb/default.php` and the warning no longer appears. 

The Language class, located at: `/system/library/language.php`, writes the warning. The language URL is constructed there: `$file = $this->directory . $this->default . '/' . $filename . '.php';`.  It's default property value is `en-gb`. And it gets the `$filename` variable from the file that calls this class' `load` method, located at: `/system/framework.php`, line 177, `$language->load('default');`. 

Therefore the URL requested is `/install/language/en-gb/default.php`
