### ISSUE TITLE
[master branch] index.html should be removed from Image Manager

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#12002]
Notice: getimagesize(): Error reading from /image/catalog/index.html! in /admin/model/tool/image.php on line 15
[master branch]index.html should be removed from Image Manager
![Image-Manager(1)](https://user-images.githubusercontent.com/30888843/202905536-1e4c5a50-2342-4fd4-9779-c7639a128fe6.jpg)

**Comment by danielkerr** [comment]
u must have done something because master branch does not doo this
