### ISSUE TITLE
[master] Filemanager (Images) has several problems

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12017]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
a) each image is shown 2x
b) if there is a other file like index.html / *.html then there is an error shown
c) and with other extensions / no extensions then the folder is blocked

**Expected behavior**
Working as it should

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 106.0

**Comment by pemaier** [comment]
just saw now one of the same problems is written in #12013

**Comment by danielkerr** [comment]
cannot replicated. no one else has thios issue only you.

**Comment by danielkerr** [comment]
this line of code blocks anything other than image files and folders shown

	$paths = glob($directory . $filter_name . '*{/,.ico,.jpg,.jpeg,.png,.gif,.webp,.JPG,.JPEG,.PNG,.GIF}', GLOB_BRACE);

**Comment by chongshengdz** [comment]
(1) Rocky, Alma, and RHEL 8 and 9 on x86_64
(2) CentOS and RHEL 7 on x86_64 (This version is extremely old and no longer recommended, please choose one of the above compatible systems instead.)
