### ISSUE TITLE
[master] one image is showing twice in the filemanager

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#12013]
![twice2](https://user-images.githubusercontent.com/30888843/203396830-c4efd640-fa1b-40b5-9d5b-5be80c67a0e0.jpg)
![twice](https://user-images.githubusercontent.com/30888843/203396856-09b9069e-705c-4d89-928f-965c52fd3e34.jpg)

**Comment by danielkerr** [comment]
can noit repicate. maybe u should change os
