### ISSUE TITLE
[master] phpMyAdmin Database backup and restore error

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12011]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
Backup an OpenCart database and restore it again. Then the following error occurs:

Error

SQL query:

--
-- Constraints for table `oc_category_to_store`
--
ALTER TABLE `oc_category_to_store`
  ADD CONSTRAINT `oc_category_to_store_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `oc_category` (`category_id`),
  ADD CONSTRAINT `oc_category_to_store_ibfk_2` FOREIGN KEY (`store_id`) REFERENCES `oc_store` (`store_id`)

MySQL said: Documentation
#1452 - Cannot add or update a child row: a foreign key constraint fails (`aqq20848_0031_silverfast_test`.`#sql-26dd59_48150`, CONSTRAINT `oc_category_to_store_ibfk_2` FOREIGN KEY (`store_id`) REFERENCES `oc_store` (`store_id`))

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/203176551-9903a7b9-ae42-4df3-abc6-48aaef0515af.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 106.0

**Comment by stalker780** [comment]
That's what I was talking about recently

https://github.com/opencart/opencart/issues/11932#issuecomment-1307754038

**Comment by stalker780** [comment]
Daniel must choose use foreign or not. 

"SET FOREIGN_KEY_CHECKS = 0" is just a lifehack which is breaking the law.

**Comment by danielkerr** [comment]
i removed all foreign key constraints. i commented out the code that causes it. whyis it back on ur database

**Comment by stalker780** [comment]
Just installed a clean master and foreign keys are still there.

![image](https://user-images.githubusercontent.com/6297070/203353818-a7ec8c23-75de-49ac-a863-c2208fbcc837.png)

![image](https://user-images.githubusercontent.com/6297070/203353955-48185ac3-fa3f-4e60-9d86-6ad22ecfd510.png)

**Comment by stalker780** [comment]
https://github.com/opencart/opencart/blob/d088237886d28d4a81462ce2e408ff71729a8ebb/upload/install/model/install/install.php#L67

**Comment by pemaier** [comment]
the problem is already present...
![image](https://user-images.githubusercontent.com/10166095/204404865-37de11d2-7ade-42aa-a5e9-1bc955414b94.png)

**Comment by mehov** [comment]
Any plans to fix and bring back the foreign keys?
