### ISSUE TITLE
upgrade to master branch from 4.0.1.1

### ISSUE THREAD

**Issue by itobin** [opencart/opencart#12031]
**What version of OpenCart are you reporting this for?**

4.0.1.1

**Describe the bug**

When attempting to upgrade, the installer says at the very top 'default not found'.  When entering the admin directory location which was renamed during the initial install, the pressing the continue button doesnt do anything.

**What section does it affect?**

the upgrade process at /install

**To Reproduce**
1. Go to /install after uploading 4.0.2 from master branch

**Expected behavior**

The installer should run

**Comment by TheCartpenter** [comment]
What's the output from your Developers Kit in your console or network tab when hitting the continue button?

**Comment by itobin** [comment]
Only thing that appears is in the info window under console.

SyntaxError: Unexpected token 'd', "default no"... is not valid JSON
OK
default not found 
{"text":"Patch 1 has been applied (1 of 9)","next":"https:\/\/www.domain.co.uk\/install\/index.php?route=upgrade\/upgrade_2&admin=sysadmin"}

**Comment by TheCartpenter** [comment]
May need further investigation.

**Comment by danielkerr** [comment]
i think i left in some testing code. 

// For testing
		$data['latest_version'] = 'master';

**Comment by danielkerr** [comment]
just tested it works fine.
