### ISSUE TITLE
Problem with install extension .json version 4.0.1.1

### ISSUE THREAD

**Issue by Frunodev** [opencart/opencart#12034]
**What version of OpenCart are you reporting this for?**
Master

**Describe the bug**
We can't install extension of the marketplace opencart. The error that generate is 
- Invalid JSON
- Can't create documents but the system has the permision 777
- I Think that some URL not exist in the system, but the aplication attach those ones
Example the route admin\controller\module <- This route dont exist 

What section does it affect?
Extension Installer and  Marketplace

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/113132418/204058706-f8e34e26-544e-4229-b156-85910909a061.png)

**Server / Test environment (please complete the following information):**
 - Local development? server
 - Operating system Linux Fedora 36
 - PHP version 8.1.12
 - Apache version Apache/2.4.54
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**
The extension that I install are
   - onWebChat live chat URL: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=26290&filter_search=chat&filter_category_id=5&filter_license=0&filter_download_id=67
   - REVE Chat- Live Chat Software. URL: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=28099&filter_search=chat&filter_category_id=5&filter_license=0&filter_download_id=67

**Comment by TheCartpenter** [comment]
Since you tried multiple extensions, see with the PayPal Commerce Platform extension from the OC Marketplace if it does install correctly. If so, please contact the extension developer of both extension links you submitted on the above to resolve this issue.

**Comment by Frunodev** [comment]
I tried the extension PayPal Commerce Platform but the error is the same, I think the error is in the install. I all ready put all the directorys with permition 777.
I attach the error
![image](https://user-images.githubusercontent.com/113132418/204553770-9ab4213a-c1d9-4fa5-a391-1c41274009e1.png)

How do I solve this problem?

**Comment by TheCartpenter** [comment]
Bunch of permissions denied messages. Ensure that your storage folder is located outside of your public_html folder and that the storage folder gets ```recursively``` assigned with CHMOD 0755 on your folders and that your files are ```recursively``` assigned with 0644 permissions. If these changes still provide a permission denied error message in the logs, I would suggest to contact your host.

**Comment by Frunodev** [comment]
I all ready solve the problem with the mkdir and the directorys, but now my problem is the permision of the website.
--- Extension onWebChat - Live Chat
I install and don't have problem, but in Extension-> Module-> onwebchat_heading_title 
![image](https://user-images.githubusercontent.com/113132418/204818769-5906e7df-a374-40d9-b4e8-55fb78fcc349.png)
I install the module but if I edit "Don't have permision"
![image](https://user-images.githubusercontent.com/113132418/204822964-522c2454-0826-42ae-b577-9e877e7b9e87.png)

I login with the user Administrator and in the permision I have all

How do I solve this problem?

**Comment by gRoberts84** [comment]
Go to `System > Users > User Groups`, edit the Administrator user group and then make sure the permissions for the extension are ticked and save.
