### ISSUE TITLE
[master] Add attribute to product - names

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12033]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
Create several attributes and add this attributes to a product. All attributes are shown but the name is not displayed right. All attributes seem to show the attribute group name.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/203869620-2218d9e9-82a2-4d27-9236-2339f5424b34.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 106.0

**Additional context**

**Comment by chongshengdz** [comment]
(1) Rocky, Alma, and RHEL 8 and 9 on x86_64
(2) CentOS and RHEL 7 on x86_64 (This version is extremely old and no longer recommended, please choose one of the above compatible systems instead.)

**Comment by pemaier** [comment]
Linux 
Kernel version: 3.10.0-962.3.2.lve1.5.73.el7.x86_64 #1 SMP Wed Aug 24 21:31:23 UTC 2022 x86_64
Build Date | Oct 28 2022 14:20:30

**Comment by TheCartpenter** [comment]
Then, it seem not only to be related with server-specifics but also on the OS versions with their libraries installed causing some of this...

**Comment by pemaier** [comment]
@TheCartpenter I don't think that it is related to OS versions. OC is working on a middle-ware (php) what should decouple it from the OS and it's versions. (The middle-ware is relaying on the OS versions.)

**Comment by stalker780** [comment]
I have the same behavior in Windows 10 Firefox 107.

In Chrome 107.0.5304.122 it does not show at all. Just blinking a list of attributes and disappears at once.

This is not related to hosting. This is OC common.js bug.

Firefox:
![image](https://user-images.githubusercontent.com/6297070/203998200-7377e536-d43f-4262-aa2f-1aba285ef9f1.png)

Chrome:
https://user-images.githubusercontent.com/6297070/203999285-4df3a007-905f-4914-a531-f0b4b56c43a6.mp4

**Comment by chongshengdz** [comment]
i install Alma Linux 8, and all problems disappeared.

**Comment by TheCartpenter** [comment]
> i install Alma Linux 8, and all problems disappeared.

Yes, of course. Which is why on the above, it states that the OS and the version release is not related vs. this one for some reason. 

@stalker780: As for the common.js file, however, if the issue persists on Windows 10, it may need to be observed.

**Comment by chongshengdz** [comment]
> > i install Alma Linux 8, and all problems disappeared.
> 
> Yes, of course. Which is why on the above, it states that the OS and the version release is not related vs. this one for some reason.
> 
> @stalker780: As for the common.js file, however, if the issue persists on Windows 10, it may need to be observed.

opencart version 4.0+ works fine on Alma Linux 8.

**Comment by TheCartpenter** [comment]
> > > i install Alma Linux 8, and all problems disappeared.
> > 
> > 
> > Yes, of course. Which is why on the above, it states that the OS and the version release is not related vs. this one for some reason.
> > @stalker780: As for the common.js file, however, if the issue persists on Windows 10, it may need to be observed.
> 
> opencart version 4.0+ works fine on Alma Linux 8.

Yes, I get that. Which is why I was convinced from my first reply that this issue is OS and versions-related.

**Comment by chongshengdz** [comment]
> I have the same behavior in Windows 10 Firefox 107.
> 
> In Chrome 107.0.5304.122 it does not show at all. Just blinking a list of attributes and disappears at once.
> 
> This is not related to hosting. This is OC common.js bug.
> 
> Firefox: ![image](https://user-images.githubusercontent.com/6297070/203998200-7377e536-d43f-4262-aa2f-1aba285ef9f1.png)
> 
> Chrome: https://user-images.githubusercontent.com/6297070/203999285-4df3a007-905f-4914-a531-f0b4b56c43a6.mp4

you can try to install the latest master branch on a sub-folder and see if the problems persist?

**Comment by pemaier** [comment]
I have tested it in a direct and a sub-folder ... same result.

**Comment by stalker780** [comment]
> > I have the same behavior in Windows 10 Firefox 107.
> > In Chrome 107.0.5304.122 it does not show at all. Just blinking a list of attributes and disappears at once.
> > This is not related to hosting. This is OC common.js bug.
> > Firefox: ![image](https://user-images.githubusercontent.com/6297070/203998200-7377e536-d43f-4262-aa2f-1aba285ef9f1.png)
> > Chrome: https://user-images.githubusercontent.com/6297070/203999285-4df3a007-905f-4914-a531-f0b4b56c43a6.mp4
> 
> you can try to install the latest master branch on a sub-folder and see if the problems persist?

This is the latest master on screenshot and video

**Comment by TheCartpenter** [comment]
Whether there are also different OSes installs or different results of one OS that claims to work with different OC v4.x versions.

**Comment by TheCartpenter** [comment]
Any results with different browsers on Windows 10 such as Edge or Chrome? So far, it only seem to be about Firefox.

**Comment by chongshengdz** [comment]
![attribute](https://user-images.githubusercontent.com/30888843/204017866-baf8aba6-1554-4df5-8080-0f22c4ede67e.jpg)
mine works fine, maybe you need to update your operating system.

**Comment by TheCartpenter** [comment]
> ![attribute](https://user-images.githubusercontent.com/30888843/204017866-baf8aba6-1554-4df5-8080-0f22c4ede67e.jpg) mine works fine, maybe you need to update your operating system.

Which OC version?

**Comment by TheCartpenter** [comment]
@chongshengdz: Also, is it on a development / virtual server or on a production server?

**Comment by chongshengdz** [comment]
> > ![attribute](https://user-images.githubusercontent.com/30888843/204017866-baf8aba6-1554-4df5-8080-0f22c4ede67e.jpg) mine works fine, maybe you need to update your operating system.
> 
> Which OC version?

latest master branch

**Comment by chongshengdz** [comment]
> @chongshengdz: Also, is it on a development / virtual server or on a production server?

for testing purpose currently, and if no errors, can put into production server immediately.

**Comment by TheCartpenter** [comment]
> > @chongshengdz: Also, is it on a development / virtual server or on a production server?
> 
> for testing purpose currently, and if no errors, can put into production server immediately.

By uploading the package to a test domain on a web server of a development server that is not a virtual server could also be done in order to test the results and the differences of the virtual server vs. a development location of your production server.

**Comment by TheCartpenter** [comment]
As written before, by following the above suggestion can affect licenses provided by web hosts. Please ensure to contact your host for such considerations before affecting their terms and conditions.

**Comment by TheCartpenter** [comment]
Understandable. These suggestions are mostly known, either, for the people who are eligible to do so from their own fully managed dedicated server or by using their own computers with SSL development certificates to sell their goods.

**Comment by osworx** [comment]
> just tested in different operating systems, and if you are going to using opencart version 4.0+, then (1) Rocky, Alma, and RHEL 8 and 9 on x86_64 (if you are using CentOS7 before, then these operating systems are highly recommended) (2) CentOS and RHEL 7 on x86_64 (This version is extremely old and no longer recommended, and will cause lots of bugs, please choose one of the above compatible systems instead.)

This discussion goes completely in the **wrong direction!**

Not the basic system has to be changed (if something does not work as expected), instead the script itself (here OpenCart) should be able to run on almost all operating systems.
Why?
Because this is a "simple webshop script" and deal not with operating system settings etc.
The moment OpenCart requires a special defined operating system, I would say that many users (especially outside of Europe) will look for alternatives (which are not so "sophisticated" about Operating systems ..).

**Comment by mhcwebdesign** [comment]
Coming back to the original issue here:

I just tested it on with today's master branch (3 Dec 2022), on a Linux Mint 20.3 (with a 5.15.0-56-generic kernel), with PHP 8.2 as well as PHP 8.1. The error comes up when using Firefox 107.0.1, but work fine when using Google Chrome version 108.0.5359.94 .

**Comment by gRoberts84** [comment]
Only partial support for `<datalist>` with Firefox. Likely other browsers on older operating systems may also be affected.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
