### ISSUE TITLE
[master] Add option to product - names

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12032]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
Create several options and add this options to a product. All options are shown but the name is not displayed all options have he name choose except file and date options.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/203869107-3e7844f0-f0d1-4a9c-92e7-09e43ab0c9ae.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 106.0

**Comment by pemaier** [comment]
Additional Information to attributes and options.
for options
- Firefox Browser show one line per entry with -choose-
- Chromium Browser show 2 lines with the option name and 2nd line choose
and attributes
- Firefox Browser show one line per entry with attribute group name
- Chromium Browser show 2 lines with the attribute name and 2nd line attribute group name

**Comment by mhcwebdesign** [comment]
Why is nobody else able to reproduce your error?

**Comment by pemaier** [comment]
... others do. It is likely the same problem as #12033 so it makes no sense to discuss it here again.
I was only pupping additional information here that it is seen directly)

**Comment by TheCartpenter** [comment]
Then why is there another commit opened about the same issue regarding this?
