### ISSUE TITLE
Latest/Bestseller modules caching problem with memcached and Redis 

### ISSUE THREAD

**Issue by kozmoya** [opencart/opencart#12030]
We are using Opencart 3.0.3.8 with default theme on litespeed server.
When the cache option is set to "file", everything works well as it should be.
My case is happening when i set it up to redis or memcached.
Both on redis or memcached, when someone buy a product which is 1 piece in stock, the latest or bestseller extensions is not updated on homepage. The product page is updated and shows no stock, search page, cateogry pages, everything is fine but these two extensions.
I've got the same result on different scenarios like i disable a product which is listing on bestseller. It's still showing up on bestseller but disabled on the other homepage extensions as normal.

Third party extensions works well on homepage, every product updates any changes like enable/disable products, stock status (even when someone buy it) etc.
But on bestseller and latest extensions, they does not update anything till the cache expire time. For example, i disable a product and it still showing on homepage/latest products like enabled.

I hope i can explained it correctly.

**Comment by kozmoya** [comment]
@danielkerr i dont understand why its closed without any answer?

**Comment by ADDCreative** [comment]
@danielkerr This is an issue. None of the Redis, Memcache or Memcached delete methods support wildcards.

So calling delete of `product` does not remove `product.latest. ...`.
https://github.com/opencart/opencart/blob/eb0f24661f3737ed86d5d37da4b290fb064f048d/upload/admin/model/catalog/product.php#L146

**Comment by TheCartpenter** [comment]
Could be the array|string deprecation stuff from the library/cache folder. Sometimes, it does show that error message in opencart-3 as well.

**Comment by danielkerr** [comment]
im not supporting these extensions. i didnt add them some one else did and did a half ass job. they are still useful but not with the opencart app.
