### ISSUE TITLE
Possibility to install extensions inside an author's folder.

### ISSUE THREAD

**Issue by andresjavierpf** [opencart/opencart#12047]
**What version of OpenCart are you reporting this for?**
4.x

**Describe the bug**
Is there any way to install the extensions inside an author folder, inside upload/extensions/? Example: `upload/extensions/devman/extension_folder_1`, `upload/extensions/devman/extension_folder_2`, etc.

devman is the author name.

- extensions
    - devman
        - extension_folder_1
            - admin
            - catalog
            - system
            - install.json
        - extension_folder_2
            - admin
            - catalog
            - system
            - install.json
    - other_extension_folder         

**Expected behavior**
Being able to organize/install extensions by author to avoid conflict with other extensions that may have the same name without the need to prefix extension names.

**Comment by TheCartpenter** [comment]
I had that idea previously but then realized with time that no extension developers would be able to work their ideas together for their clients since each extension would remain separated as impossible to reunite and may also become duplicated on-one-and-another between authors.

**Comment by gerasart** [comment]
But if u use namespace - this is can resolve it

**Comment by TheCartpenter** [comment]
It would also create other conflicts since multiple extensions would also rely on the same namespace among different sub-folders inside the extensions folder similarly as what OCMod and VQMod can already create.

**Comment by danielkerr** [comment]
no. they need to be clean so they can not interfere with each other if one is uninstalled. try using prefix of the file name
