### ISSUE TITLE
[4.0.1.1] Captcha doesn't work on Returns page

### ISSUE THREAD

**Issue by MagDevel** [opencart/opencart#12043]
**What version of OpenCart are you reporting this for?**
4.0.1.1 and the current master

**Describe the bug**
Captcha doesn't work on the Product Returns page

**To Reproduce**
1. Go to 'Extensions -> Extensions -> Captchas -> Basic captcha -> click 'Edit'.
2. Set Status to enabled, click 'Save'
3. Go to 'System -> Settings -> Default store -> click 'Edit'
4. Go to 'Option' tab, scroll down to 'Captcha' section
5. Select Basic Captcha in Captcha field
6. Pick all options in Captcha Pages field, click 'Save'
7. Go Returns page in front-end

See that Captcha does not appear, and captcha verification is not performed

**Expected behavior**
Captcha should appear on the Returns page, captcha validation should work

**Additional context**
The problem is different values used for config_captcha_page setting:

'returns' value is used in admin/controller/setting/setting.php
'return' value is used in catalog/controller/account/returns.php

**Comment by TheCartpenter** [comment]
I replied to your pull request: https://github.com/opencart/opencart/pull/12045

**Comment by danielkerr** [comment]
@TheCartpenter stop fucking around with stuff!

**Comment by TheCartpenter** [comment]
@danielkerr: WTF are you talking about dude?? This fix was meant to be!

**Comment by danielkerr** [comment]
@TheCartpenter yes sorry. i just checked

**Comment by MagDevel** [comment]
@danielkerr Thank you. 
Please fix the same on line 408
