### ISSUE TITLE
[master] File manager - Main product image is not deleteable

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12059]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
1. The main image of a product is not possible to delete. If the product is opened the main image is deleted and the product is saved. The image is still present.
2. Additional i get an error message in the file manager when I click edit 
Notice: getimagesize(): Error reading from /home/.../image/catalog/index.html! in /home/.../adminx/model/tool/image.php on line 15

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/204647509-9bf44203-5a2a-4db2-9989-28307643dc5f.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF & Chrom
 - Version [e.g. 22] 107 / 104

**Comment by TheCartpenter** [comment]
Bunch of server issues lately. It has nothing to do with Opencart; getimagesize() function error.

**Comment by chongshengdz** [comment]
you need to upgrade your operating system

**Comment by danielkerr** [comment]
again this is because hes deleting random stuff to see if it works!

**Comment by TheCartpenter** [comment]
I am also noticing persistent instructions to upgrade the OS. Please take note that doing so on a production server may involve licensing charges by the web hosting service people are hosting their stores in accordance with their terms and conditions.

**Comment by danielkerr** [comment]
i dont know what the fuck hes doing. its like playing guessing games. no information on which page. as far as i can tell if no image is found it shows nothing because its codeed to do that.
