### ISSUE TITLE
[master] Product Variant name is lost after status=off

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12050]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
The product name is lost after the product variant status is switched to off and turn back to the product master name.
(It seams to be only the name other data eg. model is not changed.)

**To Reproduce**
**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/204276808-a51951c5-bdc8-4233-b938-a6faa8beb37d.png)
the switch off ...
![image](https://user-images.githubusercontent.com/10166095/204277030-0621e209-f45e-483e-aebf-bece7d817dfd.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 107.0

**Comment by TheCartpenter** [comment]
@pemaier: Please provide the full steps on how to reproduce the described issue.
