### ISSUE TITLE
[master] Customer groups are empthy - add new is not possible

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12056]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
see subject

**To Reproduce**
New install
goto customer groups

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/204410150-3b8d35cd-9aa0-4da0-b9ba-c9464b14eb5b.png)

**Comment by TheCartpenter** [comment]
In your PHPMyAdmin, do you see your customer group in your ```oc_customer_group_description``` table?

**Comment by danielkerr** [comment]
[screen-capture.webm](https://user-images.githubusercontent.com/5079756/204628630-4b6cb273-f066-4269-8e56-ca0dd5cee8df.webm)
