### ISSUE TITLE
Argument '2' passed to readfile() is expected to be of type bool|null, string givenPHP(PHP0406)

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#12058]
https://www.php.net/manual/tr/function.readfile.php

function readfile(
    string $filename,
    bool $use_include_path = false,
    null|resource $context = null
): bool|int
Outputs a file

Reads a file and writes it to the output buffer.

https://github.com/opencart/opencart/blob/d97f086ed5fba3231c3ea5fe7f5c3173ae8afaa0/upload/admin/controller/tool/upload.php#L281

**Comment by TheCartpenter** [comment]
Which OC and PHP versions are you reporting this issue about?

**Comment by eturerer** [comment]
we don't use fopen. 
https://www.php.net/manual/tr/function.fopen.php

https://www.php.net/manual/tr/function.fopen.php

**Comment by TheCartpenter** [comment]
Neither did previous OC versions. We used readfile for a long time.

**Comment by danielkerr** [comment]
`readfile($file, 'rb');`

there is nothing that can cause the error

[screen-capture (1).webm](https://user-images.githubusercontent.com/5079756/204629986-257eeeac-40d9-4158-bf31-80d2cd95f681.webm)

**Comment by ADDCreative** [comment]
@danielkerr You may not get an error but the line should still be changed to `readfile($file);` as the 'rb' is doing nothing except equating to true for the second parameter.
