### ISSUE TITLE
[master] Settings entries missing - weight class and length class

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12055]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
see headline ... it's impossible to save the settings

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/204403926-58a02247-81b7-41bc-bf40-1696ebdad765.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 107.0

**Additional context**
Situation after a new install

**Comment by TheCartpenter** [comment]
Have you configured your length and weight classes in your OC admin > systems > localisation section?

**Comment by danielkerr** [comment]
very simple add ur weight and length classes back.
