### ISSUE TITLE
{master branch}Warning: Attempt to read property "num_rows" on bool in

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#12051]
Warning: Attempt to read property "num_rows" on bool in /catalog/model/catalog/product.php on line 7
Warning: Trying to access array offset on value of type null in /catalog/model/catalog/product.php on line 457
Warning: foreach() argument must be of type array|object, null given in /catalog/model/catalog/product.php on line 165

**Comment by TheCartpenter** [comment]
@chongshengdz: array|object is not part of the core. This error must be originating from an installed extension.

**Comment by chongshengdz** [comment]
@danielkerr @TheCartpenter please check the install process, some database tables are missing.
