### ISSUE TITLE
[master] Language - Translation is used only partly

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12054]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
Installed a German translation as an extension but is used only partly.

**To Reproduce**
Install the appended extension and then you'll see at the modules and the mini cart and the normal cart the English text. Also some other text as e.g. the buy button is English.

**Expected behavior**
A complete translation.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/204388549-e1a5320a-0e02-488c-886d-35bf7b7e0cca.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 107.0

[language_german.ocmod.zip](https://github.com/opencart/opencart/files/10107821/language_german.ocmod.zip)

**Comment by danielkerr** [comment]
yes the language example is not a full translation and the language is supposed to drop back to the default one.

**Comment by pemaier** [comment]
There is a full translation appended.

**Comment by pemaier** [comment]
[4.0.2.0] Same problem in the current version.
![image](https://user-images.githubusercontent.com/10166095/232718053-4d49501b-3303-4062-a148-ae6b23e8059f.png)

**Comment by pemaier** [comment]
![image](https://user-images.githubusercontent.com/10166095/232718640-693d9f70-b55c-4de9-97ce-05f9fe41d5c3.png)

If you like to check it I have uploaded a complete German translation to the marketplace.
