### ISSUE TITLE
[master] Order history mail - Order date with 3 variants

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12069]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
The order history mail has the time 3x with different variants.

**To Reproduce**
1. Go to an order
2. Send a status change
3. See error in the mail

**Expected behavior**
A clear date 

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/205280983-52dd9fcb-9e2f-46be-9523-758c9fbeffce.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system cloud linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF & Chrome
 - Version [e.g. 22] 107 / 104

**Comment by TheCartpenter** [comment]
What is your set value in your date_format_short language key in catalog/language/your_language/default.php file?

**Comment by TheCartpenter** [comment]
Which master branch version? Any extensions installed?

**Comment by danielkerr** [comment]
im not even looking at his issues u dont get to do this because u delete stuff.

**Comment by pemaier** [comment]
That is an interesting insinuation! What are you smoking ... why should I do this?

**Comment by pemaier** [comment]
@TheCartpenter 
Before each test I do a complete new install. So this is the last version.
