### ISSUE TITLE
Order created on Opencart dashboard without sending data to PayPal

### ISSUE THREAD

**Issue by suganyajai** [opencart/opencart#12061]
**What version of OpenCart are you reporting this for?** 
OpenCart 3.0.3.7

**Describe the bug**
I've configured PayPal Commerce Platform recently in above OpenCart version and facing the following issue for some orders. The order was created in the OpenCart back-end, but I couldn't find any transaction for that in PayPal. Is it possible in OpenCart to create order only in OpenCart back-end without sending order details to PayPal?

And, how will I identify the transaction was completed for the orders created in OpenCart dashboard?

I also face order status issue with PayPal Commerce Platform, the transaction was declined due to wrong cvv entered by customer during payment, but the order status was completed in OpenCart dashboard.

What section does it affect?
Order creation and Payment

**To Reproduce**
1. Go to 'Checkout Page'
2. Click on 'PayPal or Card payment'
3. If transaction completed the order will be created in the OpenCart back-end with the status of Completed. If failed/pending that should be updated with status

**Server / Test environment (please complete the following information):**
 - ecigs-direct.com
 - OpenCart 3.0.3.7
 - PayPal Commerce Platform (in-build) 
 - Chrome

**Additional context**

**Comment by ADDCreative** [comment]
Are you using the latest version of the extension from the marketplace? The one included with OpenCart has a lot of bugs.

Including an issue when the order status could be changed remotely.
https://forum.opencart.com/viewtopic.php?t=222974

You also need to check your order statuses are set correctly in both the extension and the OpenCart settings. Ask on https://forum.opencart.com/ for help with that.
