### ISSUE TITLE
`uses_customer` field at table `[prefix]coupon` should be an integer not a string (varchar)

### ISSUE THREAD

**Issue by Miguel-MultiSafepay** [opencart/opencart#12064]
`uses_customer` field is managed by OpenCart software like an integer, namely is like `uses_total` in terms of programming logic, but is a string (varchar) instead

You can see an example at line 5 of [admin]model/marketing/coupon.php

... where the DB query is written like this ...
`uses_customer` = '" . (int)$data['uses_customer'] . "'

Here is a dump of the DB as it is now, so you can see how `uses_customer` is designed as a string ...

CREATE TABLE `oc_coupon` (
  `coupon_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL,
  `code` varchar(20) NOT NULL,
  `type` char(1) NOT NULL,
  `discount` decimal(15,4) NOT NULL,
  `logged` tinyint(1) NOT NULL,
  `shipping` tinyint(1) NOT NULL,
  `total` decimal(15,4) NOT NULL,
  `date_start` date NOT NULL,
  `date_end` date NOT NULL,
  `uses_total` int(11) NOT NULL,
  `uses_customer` varchar(11) NOT NULL,
  `status` tinyint(1) NOT NULL,
  `date_added` datetime NOT NULL,
  PRIMARY KEY (`coupon_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

Regards

**Comment by TheCartpenter** [comment]
I think I'm gonna start comparing all fields in the database with the models since I found the same issue in opencart-3.

**Comment by TheCartpenter** [comment]
After further investigation. The ```uses_customer``` field uses the same logic as the ```seo_url``` 's ```value``` field. Therefore, the field structure should be fine but it is the ```int``` cast of the model for the ```uses_customer``` that should use: ```$this->db->escape``` instead of ```int``` .

**Comment by TheCartpenter** [comment]
The admin/controller/marketing/coupon should use a string of 1 instead of using an integer as well if the case with the ```$this->db->escape``` .

**Comment by danielkerr** [comment]
of course uses_customer should be an int.

**Comment by Miguel-MultiSafepay** [comment]
Thanks for your great job!!
