### ISSUE TITLE
Error when filling in a customeraddress

### ISSUE THREAD

**Issue by tinnielam** [opencart/opencart#12065]
Hello good people :) 

I tried to create a customer and attempted to fill in it's address I received the following error:

SyntaxError: Unexpected token '<', "<b>Error</"... is not valid JSON
OK
<b>Error</b>: Call to undefined function Opencart\System\oc_strlen() in <b>/home/opencart/htdocs/admin/controller/customer/customer.php</b> on line <b>701</b>

![image](https://user-images.githubusercontent.com/2794232/205092443-1b13c153-bf36-45c6-bf72-5a07ddae0864.png)

I looked in this repository if there was a fix for it, but I saw that the last commit was about 27 days ago.

It worked for me when I removed "Opencart\System\" the rest of the file only uses oc_strlen() instead of "Opencart\System\oc_strlen()"

Just letting you know :)

Kind regards,

**Comment by TheCartpenter** [comment]
Already fixed in OC v4.0.2.0. You don't use the latest changes, that's why.

**Comment by TheCartpenter** [comment]
There seem to be three lines left on the latest release, still...

**Comment by tinnielam** [comment]
> There seem to be three lines left on the latest release, still...

That's what I was trying to say, when I mentioned the last commit on the file. It's still there lol :)
