### ISSUE TITLE
Slow getTotalProducts when filtering is set

### ISSUE THREAD

**Issue by Pluuk** [opencart/opencart#12062]
**What version of OpenCart are you reporting this for?**
OpenCart 4.0.1.1

**Describe the bug**
The function `Opencart\Catalog\Model\Catalog\Product::getTotalProducts()` function can get really slow on large tables when the `$data` parameter is set.

**To Reproduce**
Create a database with large tables oc_product_to_category, oc_product, oc_product_description, oc_product_to_store, oc_category_path. Then use the  `Opencart\Catalog\Model\Catalog\Product::getTotalProducts()` with `$data = ['filter_category_id' => {any_category}, 'filter_sub_category' => true]`. Queries often take more than 1 second.

**Expected behavior**
Should not be that long.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?: Local, but also happens on production servers
 - Operating system: Linux
 - PHP version: -
 - Apache version: -
 - Browser(s) tested with [e.g. chrome, safari - if applicable]: -
 - Version [e.g. 22]: -

**Comment by danielkerr** [comment]
thats why u can disable from admin

**Comment by Pluuk** [comment]
Yes, but it's possible to optimize the query as I did in my PR

**Comment by zoigecyb** [comment]
I have about 50k products in 260 cats total. query uses 200-600ms. 
1. maybe it happens bcause of combined index
2. if you have "large", as you said, tables (large - how much records??), so you need to optimize mysql/mariadb server for: 1 - caching, 2- maybe "SET GLOBAL query_cache_size = 80000;" 3 - use memcached for mysql

**Comment by zoigecyb** [comment]
I found solution. it happens because most of columns in where clause not indexed.
let's say my query is:
`SELECT COUNT(DISTINCT p.`product_id`) AS total
FROM `oc_product` p
    LEFT JOIN `oc_product_description` pd
        ON (p.`product_id` = pd.`product_id`)
    LEFT JOIN `oc_product_to_store` p2s ON (p.`product_id` = p2s.`product_id`)
WHERE pd.`language_id` = '2' AND p.`status` = '1'
  AND p.`date_available` <= NOW() AND p2s.`store_id` = '0'
  AND ( pd.`name` LIKE '%midi%' OR  pd.`tag` LIKE '%midi%' OR 
        LCASE(p.`model`) = 'midi' OR 
        LCASE(p.`sku`) = 'midi' OR 
        LCASE(p.`upc`) = 'midi' OR 
        LCASE(p.`ean`) = 'midi' OR 
        LCASE(p.`jan`) = 'midi' OR 
        LCASE(p.`isbn`) = 'midi' OR 
        LCASE(p.`mpn`) = 'midi')`

1. from all fields in where clause only p2s.`store_id` is indexed.
2. functions like LCASE also add few ms
3. like %% - is the most heavy...

so, LCASE(p.`model`) = 'midi' can be freely replaced with p.`model` LIKE 'midi', because LIKE is case insensitive

also CREATE INDEX `sku` ON oc_product (`sku`) or something like ALTER TABLE oc_product_description ADD FULLTEXT (`name`)
will speedup drastically.
but! you have to know that all of that improvements (the most is fulltext) will load mysql server.

**Comment by zoigecyb** [comment]
maybe you'll review and commit the changes to catalog/model/catalog/product.php
``
public function getProducts(array $data = []): array {
		$sql = "
        select p.`product_id`, AVG(r1.`rating`) as `rating`, pd2.`price` as discount, ps.`price` as `special`, p.`price`,
       ps.`date_end`
FROM `oc_product_to_category` p2c
    LEFT JOIN `oc_product` p ON (p2c.`product_id` = p.`product_id`)
left join oc_review r1 on (r1.`product_id`=p.`product_id` AND r1.`status` = '1')
LEFT JOIN `oc_product_filter` pf ON (p2c.`product_id` = pf.`product_id`)
left join `oc_product_discount` pd2 on (pd2.`product_id` = p.`product_id`
    AND pd2.`customer_group_id` = '" . (int)$this->config->get('config_customer_group_id') . "' 
        AND pd2.`quantity` = '1' AND ((pd2.`date_start` = '0000-00-00' OR pd2.`date_start` < NOW())
    AND (pd2.`date_end` = '0000-00-00' OR pd2.`date_end` > NOW())))
left join `oc_product_special` ps on (ps.`product_id` = p.`product_id`
    AND ps.`customer_group_id` = '" . (int)$this->config->get('config_customer_group_id') . "' 
        AND ((ps.`date_start` = '0000-00-00' OR ps.`date_start` < NOW())
    AND (ps.`date_end` = '0000-00-00' OR ps.`date_end` > NOW())))
    LEFT JOIN `oc_product_description` pd ON (p.`product_id` = pd.`product_id`)
    LEFT JOIN `oc_product_to_store` p2s ON (p.`product_id` = p2s.`product_id`)
    WHERE pd.`language_id` = ".(int)$this->config->get('config_language_id')."
    AND p.`status` = '1' AND p.`date_available` <= NOW()
  AND p2s.`store_id` = '0'";

	/*	if (!empty($data['filter_category_id'])) {
			if (!empty($data['filter_sub_category'])) {
				$sql .= " FROM `" . DB_PREFIX . "category_path` cp LEFT JOIN `" . DB_PREFIX . "product_to_category` p2c ON (cp.`category_id` = p2c.`category_id`)";
			} else {
				$sql .= " FROM `" . DB_PREFIX . "product_to_category` p2c";
			}

			if (!empty($data['filter_filter'])) {
				$sql .= " LEFT JOIN `" . DB_PREFIX . "product_filter` pf ON (p2c.`product_id` = pf.`product_id`) LEFT JOIN `" . DB_PREFIX . "product` p ON (pf.`product_id` = p.`product_id`)";
			} else {
				$sql .= " LEFT JOIN `" . DB_PREFIX . "product` p ON (p2c.`product_id` = p.`product_id`)";
			}
		} else {
			$sql .= " FROM `" . DB_PREFIX . "product` p";
		}

		$sql .= " LEFT JOIN `" . DB_PREFIX . "product_description` pd ON (p.`product_id` = pd.`product_id`) LEFT JOIN `" . DB_PREFIX . "product_to_store` p2s ON (p.`product_id` = p2s.`product_id`) WHERE pd.`language_id` = '" . (int)$this->config->get('config_language_id') . "' AND p.`status` = '1' AND p.`date_available` <= NOW() AND p2s.`store_id` = '" . (int)$this->config->get('config_store_id') . "'";
*/
		if (!empty($data['filter_category_id'])) {
			if (!empty($data['filter_sub_category'])) {
				$sql .= " AND cp.`path_id` = '" . (int)$data['filter_category_id'] . "'";
			} else {
				$sql .= " AND p2c.`category_id` = '" . (int)$data['filter_category_id'] . "'";
			}

			if (!empty($data['filter_filter'])) {
				$implode = [];

				$filters = explode(',', $data['filter_filter']);

				foreach ($filters as $filter_id) {
					$implode[] = (int)$filter_id;
				}

				$sql .= " AND pf.`filter_id` IN (" . implode(',', $implode) . ")";
			}
		}

		if (!empty($data['filter_name']) || !empty($data['filter_tag'])) {
			$sql .= " AND (";

			if (!empty($data['filter_name'])) {
				$implode = [];

				$words = explode(' ', trim(preg_replace('/\s+/', ' ', $data['filter_name'])));

				foreach ($words as $word) {
					$implode[] = "pd.`name` LIKE '" . $this->db->escape('%' . $word . '%') . "'";
				}

				if ($implode) {
					$sql .= " " . implode(" AND ", $implode) . "";
				}

				if (!empty($data['filter_description'])) {
					$sql .= " OR pd.`description` LIKE '" . $this->db->escape('%' . (string)$data['filter_name'] . '%') . "'";
				}
			}

			if (!empty($data['filter_name']) && !empty($data['filter_tag'])) {
				$sql .= " OR ";
			}

			if (!empty($data['filter_tag'])) {
				$implode = [];

				$words = explode(' ', trim(preg_replace('/\s+/', ' ', $data['filter_tag'])));

				foreach ($words as $word) {
					$implode[] = "pd.`tag` LIKE '" . $this->db->escape('%' . $word . '%') . "'";
				}

				if ($implode) {
					$sql .= " " . implode(" AND ", $implode) . "";
				}
			}

			if (!empty($data['filter_name'])) {
				$sql .= " OR LCASE(p.`model`) = '" . $this->db->escape(Helper\Utf8\strtolower($data['filter_name'])) . "'";
				$sql .= " OR LCASE(p.`sku`) = '" . $this->db->escape(Helper\Utf8\strtolower($data['filter_name'])) . "'";
				$sql .= " OR LCASE(p.`upc`) = '" . $this->db->escape(Helper\Utf8\strtolower($data['filter_name'])) . "'";
				$sql .= " OR LCASE(p.`ean`) = '" . $this->db->escape(Helper\Utf8\strtolower($data['filter_name'])) . "'";
				$sql .= " OR LCASE(p.`jan`) = '" . $this->db->escape(Helper\Utf8\strtolower($data['filter_name'])) . "'";
				$sql .= " OR LCASE(p.`isbn`) = '" . $this->db->escape(Helper\Utf8\strtolower($data['filter_name'])) . "'";
				$sql .= " OR LCASE(p.`mpn`) = '" . $this->db->escape(Helper\Utf8\strtolower($data['filter_name'])) . "'";
                $sql .= " OR LCASE(p.`product_id`) = '" . $this->db->escape(Helper\Utf8\strtolower($data['filter_name'])) . "'";
			}

			$sql .= ")";
		}

		if (!empty($data['filter_manufacturer_id'])) {
			$sql .= " AND p.`manufacturer_id` = '" . (int)$data['filter_manufacturer_id'] . "'";
		}

		$sql .= " GROUP BY p.product_id";

		$sort_data = [
            'rating',
            'p.image',
            'pd.name','p.quantity',
			'p.model',

			'p.price',
			'p.sort_order',
			'p.date_added'
		];

		if (isset($data['sort']) && in_array($data['sort'], $sort_data)) {
			if ($data['sort'] == 'pd.name' || $data['sort'] == 'p.model') {
				$sql .= " ORDER BY LCASE(" . $data['sort'] . ")";
			} elseif ($data['sort'] == 'p.price') {
				$sql .= " ORDER BY (CASE WHEN special IS NOT NULL THEN special WHEN discount IS NOT NULL THEN discount ELSE p.`price` END)";
			} else {
				$sql .= " ORDER BY " . $data['sort'];
			}
		} else {
			$sql .= " ORDER BY p.`sort_order` and p.`image`";
		}

		if (isset($data['order']) && ($data['order'] == 'DESC')) {
			$sql .= " DESC, LCASE(pd.`name`) DESC";
		} else {
			$sql .= " ASC, LCASE(pd.`name`) ASC";
		}

		if (isset($data['start']) || isset($data['limit'])) {
			if ($data['start'] < 0) {
				$data['start'] = 0;
			}

			if ($data['limit'] < 1) {
				$data['limit'] = 20;
			}

			$sql .= " LIMIT " . (int)$data['start'] . "," . (int)$data['limit'];
		}

		$product_data = [];
        //var_dump($sql);
		$query = $this->db->query($sql);

		foreach ($query->rows as $result) {
			// for never get one more time with same product id
			if (!isset($product_data[$result['product_id']])) {
				$product_data[$result['product_id']] = $this->model_catalog_product->getProduct($result['product_id']);
			}
		}

		return $product_data;
	}
``

**Comment by danielkerr** [comment]
@zoigecyb we dont use full text as it requires 3 keywords to search with. the current way is fine.

**Comment by danielkerr** [comment]
u are probably getting faster results because u have included status = 1

**Comment by danielkerr** [comment]
please test if any speed changes. i dont think its done anything
