### ISSUE TITLE
Time to address the support for the upcoming PHP 8.2

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#12074]
As per the header, PHP 8.2 support for OpenCart should be implemented soon for the upcoming PHP 8.2 release. We have created a pull request for the master branch for this: https://github.com/opencart/opencart/pull/12071

**Comment by TheCartpenter** [comment]
Integrated into opencart-3 now.

**Comment by mhcwebdesign** [comment]
Still some more fixes needed, see https://github.com/opencart/opencart/pull/12071#issuecomment-1344208950 for details.

**Comment by mhcwebdesign** [comment]
There is still an outstanding issue with PHP8.2, for the system/library/mail/smtp.php, as follows:

Line 237:
```
				$results = str_split($line, 998);
```


needs to be replaced with:
```
				// see https://php.watch/versions/8.2/str_split-empty-string-empty-array
				$results = ($line === '') ? [''] : str_split($line, 998);
```

Otherwise the email text gets completely lost when using PHP8.2 !
