### ISSUE TITLE
Success: You have added (product) to your shopping cart doesn't disappear

### ISSUE THREAD

**Issue by ronvanderzwan** [opencart/opencart#12077]
Hi,

OC 4.0.1.1. 
When adding a product to the cart, the success message goes off-screen on a mobile screen.
The message is unresponsive, the links don't work,  the x to close the message doesn't work.

Only way to close it is to refresh the page.

**Server / Test environment (please complete the following information):**
 - Deployed to a web server.
 - Operating system
 - PHP version 8.1
 - Apache version
 - Browser(s) tested with Chrome
 - Latest Version

**Comment by mhcwebdesign** [comment]
Already fixed in the master branch.

**Comment by mhcwebdesign** [comment]
> What do I need to do to update my install?

First of all, OpenCart 4.0.1.1 is not yet a stable enough release for live websites. If you need a stable release, use OpenCart 3.0.3.8 (for PHP 7.4), or the 3.0.x.x_Maintenance branch (that one also supports PHP 8.x, see at https://github.com/opencart/opencart/archive/refs/heads/3.0.x.x_Maintenance.zip).

If you want to test OpenCart 4, then grab the current master branch from https://github.com/opencart/opencart/archive/refs/heads/master.zip

**Comment by danielkerr** [comment]
fixed in master. 

@mhcwebdesign dont say stupied shit!

**Comment by ronvanderzwan** [comment]
Thanks for your help!

Ron
On Dec 7, 2022 at 9:44 AM -0500, Daniel Kerr ***@***.***>, wrote:

Closed #12077<https://github.com/opencart/opencart/issues/12077> as completed.

**Comment by ronvanderzwan** [comment]
What do you mean with your comment? Not accurate?

Ron
On Dec 7, 2022 at 9:44 AM -0500, Daniel Kerr ***@***.***>, wrote:

fixed in master.

@mhcwebdesign<https://github.com/mhcwebdesign> dont say stupied shit!

**Comment by Leander96911111** [comment]
What does this mean "fixed in master"? What does one have to do to solve this issue? I've installed the latest version of opencart and still have this problem :(

**Comment by danielkerr** [comment]
Look through the issues to the last person reporting the same issue and there should be a link near the bottom with the fix in

**Comment by Leander96911111** [comment]
After another search I found a solution (apart from a complete reinstallation).

Just replace

#alert {z-index: 9999;}

with

#alert {z-index: 9999; pointer-events: all;}

in both stylesheet.css files (folders admin/view/stylesheet and catalog/view/stylesheet).

And don't forget to clear your browser cache after updating the stylesheets.

**Comment by Leander96911111** [comment]
> 

Thanx for your reply

**Comment by Leander96911111** [comment]
> Look through the issues to the last person reporting the same issue and there should be a link near the bottom with the fix in

Thanx for the reply
