### ISSUE TITLE
[master] Backend Sales order - Language problem

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12075]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
New Install add new customer who order 2 products.
In the sales order in the backend is the price is displayed wrong - without dot or comma instead is text...

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/205722533-b3ffed1a-0b14-4825-b63f-d309e1d0f1c1.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system cloud linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 107.0.1

**Additional context**
No other language is installed.

**Comment by Aditya8578** [comment]
Same issue here.

**Comment by mhcwebdesign** [comment]
This issue has already been resolved in the master branch for the upcoming 4.0.2.0 release, just tested it successfully.

**Comment by pemaier** [comment]
... so we are coming to different results - I used the last version in master branch

**Comment by mhcwebdesign** [comment]
> ... so we are coming to different results - I used the last version in master branch

Apologies, my reply (now deleted) was referring to another issue.

**Comment by pemaier** [comment]
no problem. 
I [just installed](https://nettwork.ru/opencart/master.demo/admin0) for you now to test (demo/demo) ... may you get other results)

**Comment by pemaier** [comment]
Just saw if a 2nd language is installed and I refresh shipping or payment then I get also in English and German language setting the following result
![image](https://user-images.githubusercontent.com/10166095/208628407-b7e1a322-8540-479b-90f8-6e3cd353610d.png)

**Comment by pashast** [comment]
Still not working for the second language

https://user-images.githubusercontent.com/1617903/211291098-0110ee36-4bac-448d-b78d-00805bf2b8dc.mp4
