### ISSUE TITLE
[4.0.2.0] Warnings when save store settings

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#12086]
**What version of OpenCart are you reporting this for?**
4.0.2.0 latest github

Warning: Undefined array key "config_meta_title" in admin/controller/setting/setting.php on line 634
Warning: Undefined array key "config_name" in admin/controller/setting/setting.php on line 638
Warning: Undefined array key "config_owner" in admin/controller/setting/setting.php on line 642
TypeError: oc_strlen(): Argument #1 ($string) must be of type string, null given, called in admin/controller/setting/setting.php on line 642 in system/helper/general.php on line 3

**Comment by mhcwebdesign** [comment]
I am unable to reproduce your error, the settings are working just fine.

Line 634 doesn't even contain executable code:
`		// Get a list of installed captchas
`

Please use the latest master branch for testing!

**Comment by condor2** [comment]
See the image....I used latest github....see first post

![save_bug](https://user-images.githubusercontent.com/14251939/206724504-fa1e38cb-6708-42d2-9426-e8ea755ad940.png)

**Comment by mhcwebdesign** [comment]
Sorry, you are wrong. Clicking on that line doesn't make sense:
a) It will do a GET request, not a PUT request
b) It won't use the needed form data in the request
That's not how to test it!
