### ISSUE TITLE
Shipping method and payment method are always empty in order info

### ISSUE THREAD

**Issue by tinnielam** [opencart/opencart#12085]
Hi guys, 

Normally I would have done a pull request for an issue like this, but still unsure what to do.

![image](https://user-images.githubusercontent.com/2794232/206490255-be9376b5-d8ff-42bb-9669-7cd5084894fc.png)

Whenever I go to an order info in the backend, the input fields of my payment method and shipping method almost gets instantly cleared, but during page load I still see a shipping and payment method for like 0,3 seconds before it disappears.  Is this default behavior ? 

I have kind of found out that admin/view/template/sale/order_info.twig has this function: "$('#form-customer').on('submit', function (e) {" which always triggers during pageload and overwriting these fields...

            //$('#input-payment-method').html('<option value="">{{ text_select }}</option>');
            //$('#input-shipping-method').html('<option value="">{{ text_select }}</option>');
            
            
I have outcommented these lines for now and it doesn't overwrite my shipping method or payment anymore in the order info.

So I am wondering, whats the purpose of emptying these two methods? 

Thanks 

Kind regards,

Tin

**Comment by danielkerr** [comment]
What do u think the refresh buttons on the right of the select field do?

**Comment by danielkerr** [comment]
I'll look into it. Php8.2 fixes, then restore backups for the cloud then order editor testing and fixing

**Comment by mhcwebdesign** [comment]
Will your order editor fixing also include the necessary fix for the api/order.load? See https://github.com/opencart/opencart/issues/12057

**Comment by danielkerr** [comment]
fixed

https://github.com/opencart/opencart/issues/12019

**Comment by danielkerr** [comment]
it was customer group triggering change was the issue.
