### ISSUE TITLE
 PHP Warning:  Undefined array key "customer_token"

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#12097]
https://github.com/opencart/opencart/blob/613b29f352a22e8a9ef5c16bae4fe38b7b70d01d/upload/catalog/controller/account/forgotten.php#L8

customer can't login, forgotten function doesn't work.

**Comment by TheCartpenter** [comment]
I think it should be this one:

if (!$this->customer->isLogged() || (!isset($this->request->get['customer_token']) || !isset($this->session->data['customer_token']) || ($this->request->get['customer_token'] != $this->session->data['customer_token']))) {
			$this->session->data['redirect'] = $this->url->link('account/account', 'language=' . $this->config->get('config_language'));

			$this->response->redirect($this->url->link('account/account', 'language=' . $this->config->get('config_language')));
		}

**Comment by TheCartpenter** [comment]
account/account should be the route to redirect to.

**Comment by cgcmart** [comment]
doesn't work

**Comment by cgcmart** [comment]
Undefined array key "customer_token" is involved in several files:
upload/catalog/controller/account/account.php
upload/catalog/controller/account/forgotten.php
upload/catalog/controller/account/login.php
upload/catalog/controller/account/wishlist.php
upload/catalog/controller/account/footer.php
upload/catalog/controller/account/header.php

**Comment by TheCartpenter** [comment]
The ```customer_token``` and the ```login_token``` are two separated tokens.

**Comment by cgcmart** [comment]
solved
