### ISSUE TITLE
return null

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#12096]
public function createInvoiceNo(int $order_id): string {
		$order_info = $this->getOrder($order_id);

		if ($order_info && !$order_info['invoice_no']) {
			$query = $this->db->query("SELECT MAX(invoice_no) AS invoice_no FROM " . DB_PREFIX . "order WHERE invoice_prefix = '" . $this->db->escape($order_info['invoice_prefix']) . "'");

			if ($query->row['invoice_no']) {
				$invoice_no = $query->row['invoice_no'] + 1;
			} else {
				$invoice_no = 1;
			}

			$this->db->query("UPDATE " . DB_PREFIX . "order SET invoice_no = '" . (int)$invoice_no . "', invoice_prefix = '" . $this->db->escape($order_info['invoice_prefix']) . "' WHERE order_id = '" . (int)$order_id . "'");

			return $order_info['invoice_prefix'] . $invoice_no;
		}  
	return "";
	}

https://github.com/opencart/opencart/blob/613b29f352a22e8a9ef5c16bae4fe38b7b70d01d/upload/admin/model/sale/order.php#L466

**Comment by pemaier** [comment]
[master] already solved
