### ISSUE TITLE
[master] Captcha page setting "Guest checkout" is not used anywhere

### ISSUE THREAD

**Issue by MagDevel** [opencart/opencart#12103]
**What version of OpenCart are you reporting this for?**
master, 4.0.1.1

**Describe the bug**
Captcha page setting "Guest checkout" (value="guest") that available in System settings (Captcha section) is not used on Checkout Page.

In previous OpenCart version this value was used to add captcha to guest checkout form.
In OpenCart 4.0 'register' value is used instead, both on the Register page and on the Checkout Page.
This makes this setting unusable and does not allow you to set captcha separately, for example, **only** for the registration page, and **not** for the checkout page.

**To Reproduce**
(use v4.0.1.1 if you have problems saving system settings in the current master branch)

Case 1:
1. Go to Extensions >Extensions > Captcha > Basic Captcha > click 'Install > click 'Edit'
2. Enable the captcha, click 'Save'
3. Go to System > Settings > Default Store -> click 'Edit' -> go to 'Option' tab -> scroll down to Captcha settings
4. Select 'Guest Checkout', unselect all other pages, click 'Save'
6. Go to front-end > add product to cart > go to Checkout
7. See the captcha is missing

Case 2:
1. Go again to System > Settings > Default Store -> click 'Edit' -> go to 'Option' tab -> scroll down to Captcha settings
2. Select 'Register', unselect all other values, click 'Save'
3. Back to front-end > go to Checkout
4. See the captcha is activated (but I don't need it here)

**Expected behavior**
The "Guest checkout" value must activate the captcha on the checkout page (instead of the "Register" value), in order to be able to set captcha separately for the registration page and for the checkout page.

**Screenshots / Screen recordings**

![guest-checkout](https://user-images.githubusercontent.com/47626377/207430523-52f921cf-78e0-47ef-91cd-dbd06cfa28ca.png)

**Comment by pemaier** [comment]
issue solved in the current master branch
![image](https://user-images.githubusercontent.com/10166095/207453918-08ebb948-d388-40db-ad5a-2e80158f5d16.png)

**Comment by MagDevel** [comment]
No, the problem has not been fixed.
It's working for you because you have checked 'Register' value.
The problem is 'Guest Checkout' value not used.
New screenshots are attached to explain more clearly.

'Guest Checkout' is selected:

![no-captcha2](https://user-images.githubusercontent.com/47626377/207480847-0ba14f4f-8311-4fe1-8a5e-97a330ca28a1.png)

But no success:

![no-captcha](https://user-images.githubusercontent.com/47626377/207480951-a22e0f52-2ecf-44b4-98e0-92a8aec7813e.png)

**Comment by pemaier** [comment]
Ok I deselected in Captcha Page (only) the Register item and now i get the same result as you when I try to order something as guest.

**Comment by danielkerr** [comment]
is already fixed in master branch
