### ISSUE TITLE
Demo - Cannot add items to cart

### ISSUE THREAD

**Issue by saulojg** [opencart/opencart#12105]
If we try to add an item to the cart we get a green popup telling that the item was added but the cart remains at $0 and no items. This can be reproduced at the demo website.

![Screenshot from 2022-12-15 13-13-03](https://user-images.githubusercontent.com/689455/207917463-edbfb088-497f-4d6a-a988-ed8f823e8cef.png)

**Comment by JoshuaAGE** [comment]
Works. You have probably disabled cookies or something, problem is on your side.

**Comment by saulojg** [comment]
Hello, thank you for taking a look. I confirm the issue still persists with:

- Firefox 108.0.1 (64-bit) - Linux - Tried with _Enhanced Tracking Protection_ on and off
- Chromium 108.0.5359.124 (Official Build) snap (64-bit) - Linux - No Extensions - Default privacy settings

**Comment by mhcwebdesign** [comment]
Test it again using the master branch, the demo site has a number of known bugs which are now fixed in the master branch.

**Comment by JoshuaAGE** [comment]
Working, Firefox latest: https://vimeo.com/783191237

**Comment by danielkerr** [comment]
i t5hink the session table crashed because of soem one ddosing

**Comment by danielkerr** [comment]
fixed
