### ISSUE TITLE
Admin Maintenence Mode Blocks Admin from Store

### ISSUE THREAD

**Issue by SofaKingRotten** [opencart/opencart#12106]
4.0.1.1

When maintenance mode is set to 'On', admin cannot access the storefront as expected, getting message: "We are currently performing some scheduled maintenance. We will be back as soon as possible. Please check back soon."

1. Go to Admin System --> Settings and Edit the store
2. Click on Server tab
3. Set Maintenance Mode to 'On'
4. Go to the store home page to see the message.
5. Logout and log in again as admin, same issue.

I expect to be able to view the products like normal while in maintenance mode and logged in as admin.

Live server
Apache Version | 2.4.54
PHP Version | 7.3.33 (native) - 8.1 selected in cPanel
MySQL Version | 10.3.37-MariaDB-cll-lve

Using Windows 10 21H2 x64 to administrate
Tested this on Firefox and Chrome with latest updates

**Comment by pemaier** [comment]
With the last version master Maintenance Mode is not working and the shop is open for all - Tested with Firefox 107.0.1

**Comment by danielkerr** [comment]
should be the same as  && !$user->isLogged()

**Comment by danielkerr** [comment]
i think cookie issue

**Comment by TheCartpenter** [comment]
Since the topic presents two different OC 4 versions encountering this issue, the probabilities could be pretty low to be a cookie issue.

**Comment by SofaKingRotten** [comment]
> In catalog/controller/startup/maintenance.php file,
> 
> replace:
> 
> `$this->user->isLogged()`
> 
> with:
> 
> `$this->user->isLogged() !== true`


I made this change and now the cart is open to anyone while in maintenance mode. I then deleted my cookies for my site and the problem persists, anyone can view product while in maintenance mode.

**Comment by TheCartpenter** [comment]
It's where this strange thing on having different results comes in. Replace ```!== true``` with ```!== false``` and notice the difference.

**Comment by danielkerr** [comment]
its gopt nothing to do with $this->user->isLogged() its a cookie issue

**Comment by TheCartpenter** [comment]
From my end, when I try with: ```!== true```, the maintenance page does appear normally once the maintenance setting is on from the OC admin. When I try other lookups with ```$this->user->isLogged()``` , the maintenance page no longer comes up. However, since we seem to have 4 different versions on the topic, it seem to be about more that.

**Comment by pemaier** [comment]
Update: New install today it is working as expected. 
May I forgot to delete all cookies with the test 4 days ago... I don't remember now.

**Comment by danielkerr** [comment]
@TheCartpenter u make the dumbest fucking guesses./

**Comment by SofaKingRotten** [comment]
I noticed today this seems to be working as long as I don't log into front end as customer from same PC. When I log in from another PC  as customer I am not allowed, but Admin can see product from my admin PC. I will keep an eye on this for now.

**Comment by danielkerr** [comment]
i just tested with the masteer and its working

**Comment by pemaier** [comment]
[4.0.2.0] This error is present in the current version.

**Comment by Sergeynaum** [comment]
@danielkerr Problem not resolved. Why you closed this branch? I use Version 4.1.0.3 for example.

When I enable Maintenence Mode I can't work with the site as Admin as it was in previous versions.

It close the site for me also(with logged in as admin).

**Comment by Sergeynaum** [comment]
Steps to reproduce:

1. Open incognito mode
2. Go to admin panel and login.
3. Enable maintance mode
4. Go to the site
5. It will NOT available for Admin user.

Hack to work in maintance mode:
1. Open incognito mode
2. Go to the site
3. Login as customer
4. Change url and go to admin panel
5. Login as admin
6. Enable maintance mode
7. In this case you will have possibility to work as Admin in maintance mode.
