### ISSUE TITLE
Checkout page is confusing to customers - Continue button bad design

### ISSUE THREAD

**Issue by wkkapr** [opencart/opencart#12108]
Opencart 4.0.1.1
The checkout page continues to be confusing to many of our customers, as they don't realize they have to hit Continue before they can get Shipping choices. I think the confusion occurs due to the Continue button being below the "I wish to subscribe to newsletter" checkbox. Somehow people are thinking they have to hit continue to sign up for the newsletter. 

Please redesign this checkout page to be less confusing.

**Comment by mhcwebdesign** [comment]
Agreed, it should be changed to a 2-step sequence, with 2 tabs, with the 2nd tab (shipping details etc) not showing up until the 1st tab (customer details, shipping address) has been filled in.

**Comment by danielkerr** [comment]
only in ur minds

**Comment by Leander96911111** [comment]
"Only in ur mind" might be an answer but it is not a solution. The design of the checkout page is indeed confusing with regard to the continue button. Even experienced online shoppers do not expect this. Why would you need to "continue" when you're remaining on the same page?  Beats me...
