### ISSUE TITLE
[master] Admin language settings change with no rights

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12102]
**What version of OpenCart are you reporting this for?**
master of today
**Describe the bug to Reproduce**
OpenCart (new install and added demo user and 1 time saved settings)
with English language (standard) 
and additional a **complete** German language translation **installed as extension**.
(Front & Back-end including the translation files for the extension/opencart)

Situation in the administration ...
Admin: has the right to change all (standard)
Demo (You): has no right to change settings (Test: go to settings change language click save - error no permission)
But if Demo is **changing language by clicking on the language flag on top menu** then the settings entry Admin language is changed. 
(You can see it in the settings as demo because you have access rights to view settings.)

[Demo system](https://nettwork.ru/opencart/master.de/admin0) 
user/pass is demo/demo

**Expected behavior**
That it is only a temporary change for the user Demo and the admin settings do not change.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server (external hoster)
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 107.0.1

**Additional context**
Also I'm interested if 
- only I with Firefox are not able to see the German translation 
- and Chrome users can see the administration with the German translation?
A screenshot of the back-end will be helpful. Thank you.

The demo system is present in the next days so you can test around if you like...)

**Comment by nmpetkov** [comment]
https://github.com/opencart/opencart/issues/12081
