### ISSUE TITLE
Hackers  complete 500$ commodity payment with 0.1$ ，use pp standard  on opencart 3.0.3.2

### ISSUE THREAD

**Issue by bksy0909** [opencart/opencart#12111]
**What version of OpenCart are you reporting this for?**
opencart 3.0.3.2

A clear and concise description of what the bug is

My store is opencart 3.0.3.2, using pp_ Standard plug-in payment(default).
We found that for several orders, hackers paid 0.1$ and purchased 500$ goods. Paypal and opencart both judged that the transaction was normal. We finally found it in the admin of the paypal account.  

The log from my website ，thank you！
2022-12-09 6:27:56 - PP_STANDARD :: IPN REQUEST: cmd=_notify-validate&mc_gross=0.10&invoice=2274+-+Sofi+Lunno ...

What section does it affect?
payment  

**To Reproduce**
I don't know how hackers do it. 

**Expected behavior**
It should not happen  

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
bullshit. u have ur order statuses messed up. should go to pending or denied if setup correctly. it wi9ll not go to complete unless u set that as the default status.

**Comment by bksy0909** [comment]
> bullshit. u have ur order statuses messed up. should go to pending or denied if setup correctly. it wi9ll not go to complete unless u set that as the default status.
@danielkerr  Could you tell me where the order status is wrong? The screenshot picture is my paypal standard status setting  . [screenshot](https://user-images.githubusercontent.com/48849993/208278749-1c4449e6-cf18-48c4-8d0e-223287a181fa.png)

My website has thousands of orders, of which only the last three orders were cracked by hackers in this way. The hackers actually paid 0.1 $for these three orders, but they are in the order list of opencart, and the status is pending. When we checked the paypal account, we found that the amount was incorrect, but the goods had been delivered to the customer.

Please help me look again, thank you!

**Comment by danielkerr** [comment]
Change the fraud status to denied

**Comment by bksy0909** [comment]
> fraud
How do I identify the fraud status?
Did I see this state in the background 
[screenshot](https://user-images.githubusercontent.com/48849993/208278749-1c4449e6-cf18-48c4-8d0e-223287a181fa.png)  ？

**Comment by mhcwebdesign** [comment]
We had similar issues in the past on one of our client's Opencart-based websites. Perhaps use the newer Paypal Checkout Integration (see https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=38358) to see whether it makes any difference.

You could always modify it for the IPN callback to check the order total against the paid total.

**Comment by bksy0909** [comment]
> We had similar issues in the past on one of our client's Opencart-based websites. Perhaps use the newer Paypal Checkout Integration (see https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=38358) to see whether it makes any difference.
> 
> You could always modify it for the IPN callback to check the order total against the paid total.
> 
> In our case we solved it by simply blacklisting those fraudsters.

Thank you for your answer,
Could you tell me more detail to do "the IPN callback to check the order total against the pay total"?
As for the blacklist method, I noticed that the hackers use different mail, but their IP addresses are the same. Do you mean the IP blacklist?

**Comment by ADDCreative** [comment]
The order total is already checked against the payed total in the IPN.

https://github.com/opencart/opencart/blob/d18e0c13a323ab832ab50e49bb0d18d4c067dc91/upload/catalog/controller/extension/payment/pp_standard.php#L192

If it didn't match then you should see `PP_STANDARD :: TOTAL PAID MISMATCH!` in your error log.
https://github.com/opencart/opencart/blob/d18e0c13a323ab832ab50e49bb0d18d4c067dc91/upload/catalog/controller/extension/payment/pp_standard.php#L202-L204

**Comment by danielkerr** [comment]
It's under settings. Fraud status. U only send goods that are on a complete or confirmed status

**Comment by ADDCreative** [comment]
It's actually the default status in the settings that is used, not the fraud status. The fraud status is only set on an issue with coupon, gift voucher or reward points, not payment total mismatch.

**Comment by danielkerr** [comment]
its set in paypal extension that if payment email or total mismatch it does
jot hit the complete statusw

**Comment by bksy0909** [comment]
> The order total is already checked against the paid total in the IPN.



> The order total is already checked against the paid total in the IPN.
> 
> https://github.com/opencart/opencart/blob/d18e0c13a323ab832ab50e49bb0d18d4c067dc91/upload/catalog/controller/extension/payment/pp_standard.php#L192
> 
> If it didn't match then you should see `PP_STANDARD :: TOTAL PAID MISMATCH!` in your error log.
> 
> https://github.com/opencart/opencart/blob/d18e0c13a323ab832ab50e49bb0d18d4c067dc91/upload/catalog/controller/extension/payment/pp_standard.php#L202-L204

Thank you for your reply
I found the code you said, but I saw that this code was in the "case 'Completed'", but the fraudulent order I actually encountered appeared in the Pending status. I also checked the admin log ，but it did not print "PP_STANDARD:: TOTAL PAID MISMATCH!", So it may not solve the problem.

**Comment by ADDCreative** [comment]
The code is there to detect the mismatch. It's in the competted case as that's the only case for paid orders. If you didn't get the log message, maybe the log was switched off or erased. If could also be that the mismatch wasn't the issue.

A lot will depend on how you payment modules and orders statuses are configured. You would probably be best to post on 
https://forum.opencart.com/ and give a lot more detail of how you have configured things and what exactly happened.

**Comment by bksy0909** [comment]
> The code is there to detect the mismatch. It's in the competted case as that's the only case for paid orders. If you didn't get the log message, maybe the log was switched off or erased. If could also be that the mismatch wasn't the issue.
> 
> A lot will depend on how you payment modules and orders statuses are configured. You would probably be best to post on https://forum.opencart.com/ and give a lot more detail of how you have configured things and what exactly happened.

Thank you for your advice ，I will try it !

**Comment by danielkerr** [comment]
It's the blicd leading the blind again

**Comment by danielkerr** [comment]
Imn not dealing with this. It works u just don't know how to setup the order statuses correctly.  There's no bug.
