### ISSUE TITLE
 Query failed: ERROR: unrecognized configuration parameter "time_zone" 

### ISSUE THREAD

**Issue by Nuruddin999** [opencart/opencart#12117]
**What version of OpenCart are you reporting this for?**
ver 4
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
i have folder of already installed opencart. I want run it on local ubuntu. I move to this folder and run php -S localhost:8000.
Also in config.php i made changes: i wrote psql config
`define('DB_DRIVER', 'pgsql');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'postgres');
define('DB_PASSWORD', 'fillpostgress999');
define('DB_DATABASE', 'magaz');
define('DB_PORT', '5432');
define('DB_PREFIX', 'oc_'); `
Onb my local ubuntu i created databse magaz
So in my browser there is error

Warning: pg_query(): Query failed: ERROR: unrecognized configuration parameter "time_zone" in /home/nuruddin/apps/practise/magaz/system/library/db/pgsql.php on line 24TypeError: pg_result_error(): Argument #1 ($result) must be of type PgSql\Result, PgSql\Connection given in /home/nuruddin/apps/practise/magaz/system/library/db/pgsql.php on line 52

So where is problem can be ?

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by eturerer** [comment]
change to TIMEZONE

**Comment by danielkerr** [comment]
removed access to postgresql via install. unfortunately the mysql and postgresql are too different in the syntax. it would mean i need to remove backticks from every table and field to make them compatible but would still be having issues down the line. after checking around other php open source projects don't use postgresql unless its a specially modified version of the script.
