### ISSUE TITLE
& turns into &amp; in customer and adress table

### ISSUE THREAD

**Issue by Betacarotin** [opencart/opencart#12112]
Having a customer or company name that contains an & will lead to wrong database insert. 
the field in the database contains &amp; instead. 
this will occur on orders and invoices. 
When manually corrected in sql database it stays correct.
3.0.3.8 on php8.1

**Comment by TheCartpenter** [comment]
Why is this posted here?

**Comment by Betacarotin** [comment]
where should it be posted?

**Comment by ADDCreative** [comment]
It's by design. OpenCart has always done a HTML escape on input.

https://github.com/opencart/opencart/blob/613b29f352a22e8a9ef5c16bae4fe38b7b70d01d/upload/system/library/request.php#L46

**Comment by mhcwebdesign** [comment]
I just tested the ampersand in a customer name, company name, and street name, using 3.0.x.x_Maintenance branch, and it all works fine, it's all stored correctly in the database as '&amp', and displayed as '&' on all the frontend and backend pages.

**Comment by pemaier** [comment]
I tested in the latest master branch ...
I tried to add a new address in the administration to a customer account with "&" in first name, last name, company, address 1, address 2 and city. If in one of this fields this character is present then it's not possible to save the address.

 **Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 108.0

**Comment by Betacarotin** [comment]
My version did not trim by default. So I commented out and added the trimmed row you showed,
But still the same problem, is there something else I need to change from the 3.0.3.8 maintenance branch? 

`	//$data = htmlspecialchars($data, ENT_COMPAT, 'UTF-8');
			$data = trim(htmlspecialchars($data, ENT_COMPAT, 'UTF-8'));`

**Comment by Betacarotin** [comment]
![Bildschirmfoto 2022-12-17 um 23 48 38](https://user-images.githubusercontent.com/10900439/208268752-f8ff14eb-a6f8-4588-bdfc-baab6357291d.png)
![Bildschirmfoto 2022-12-17 um 23 47 38](https://user-images.githubusercontent.com/10900439/208268761-113766b3-8558-406c-a1ba-bfd6a227ebec.png)

**Comment by Betacarotin** [comment]
It looks like the company field is treated differently on data insert

**Comment by Betacarotin** [comment]
> It's by design. OpenCart has always done a HTML escape on input.
> 
> https://github.com/opencart/opencart/blob/613b29f352a22e8a9ef5c16bae4fe38b7b70d01d/upload/system/library/request.php#L46

But it can´t be intended to not be able to have & in the company name? Is theer a way to fix this? It works on other fields in the same form. So I consider it a bug, not feature.

**Comment by TheCartpenter** [comment]
If it'd be a bug, this issue would be reproduced for multiple users. Check your php.ini file.

**Comment by ADDCreative** [comment]
@Betacarotin Do not comment out that line, it's required to for security.

The way the data is stored is not a bug, but there is a bug that affects the order editor. I have been able to recreate it in both 3.0.3.8 and 4.0.1.1. When using a sorted address with `&` in, it will display and save as `&amp;`.

It due to the parts of the address not being put through html_entity_decode before being JSON encoded and returned from the address function the order editor calls to fetch the address.

https://github.com/opencart/opencart/blob/d18e0c13a323ab832ab50e49bb0d18d4c067dc91/upload/admin/controller/customer/customer.php#L1527-L1539

**Comment by Betacarotin** [comment]
> @Betacarotin Do not comment out that line, it's required to for security.
> 
> The way the data is stored is not a bug, but there is a bug that affects the order editor. I have been able to recreate it in both 3.0.3.8 and 4.0.1.1. When using a sorted address with `&` in, it will display and save as `&amp;`.
> 
> It due to the parts of the address not being put through html_entity_decode before being JSON encoded and returned from the address function the order editor calls to fetch the address.
> 
> https://github.com/opencart/opencart/blob/d18e0c13a323ab832ab50e49bb0d18d4c067dc91/upload/admin/controller/customer/customer.php#L1527-L1539

@ADDCreative it is two lines! 
- one line does not trim- that is 3.0.3.8 right from maintenance github
- The other has the trim, that is the one from previous posts here. I tried to use the one with trim to see if something changes. It does not. Still, one may wonder which to use

**Comment by Betacarotin** [comment]
@mhcwebdesign can you reopen this issue please, since it is not solved?

**Comment by mhcwebdesign** [comment]
@Betacarotin: I am simply unable to reproduce your error. Hence, using the 3.0.x.x_Maintenance, please provide the exact steps leading to your error, you original problem is too vague for anyone else to reproduce.

**Comment by Betacarotin** [comment]
@mhcwebdesign 
- Insert a customer (frontend or backend) with an & in his company name. Like "Test & Chaos inc."
- Make an order with this customer.
- Look at the company name in the order form
- See attached pictures. If I deactivate all extension it is still the same. 
![Bildschirmfoto 2022-12-18 um 12 25 35](https://user-images.githubusercontent.com/10900439/208295870-260a47cf-66cd-4fc4-be0c-baddd7d81398.png)
![Bildschirmfoto 2022-12-18 um 12 26 08](https://user-images.githubusercontent.com/10900439/208295873-232eb332-ea83-4a4f-82dd-7906246a94f2.png)
![Bildschirmfoto 2022-12-18 um 12 26 39](https://user-images.githubusercontent.com/10900439/208295878-7a2cf092-fa3a-4aef-893b-0dd0860388fe.png)
![Bildschirmfoto 2022-12-18 um 12 27 01](https://user-images.githubusercontent.com/10900439/208295882-482f401a-d553-46dd-b704-701f6599c23d.png)

**Comment by mhcwebdesign** [comment]
I see, now managed to reproduce it. This appears to be an issue with the autocomplete whose data is then filled in automatically into these various other fields. Will look into it tomorrow.

**Comment by danielkerr** [comment]
@Betacarotin if u dont know what html escape is for u shouldnt giving advice and how web sites should work!

dumb!

**Comment by Betacarotin** [comment]
> @Betacarotin if u dont know what html escape is for u shouldnt giving advice and how web sites should work!
> 
> dumb!

Nice tone, thx. 
For someone your experience I would have expected a fast solution instead of calling me names.
My excuse is that I am not anywhere near a programmer, I am a poor user, trying to get his shop right. 
And honestly OC is far from easy in that regards. 

So @danielkerr , if you don´t have a solution, just get out of the way and make room for the professionals if they arrive to the scene here.

**Comment by danielkerr** [comment]
just tested and it works fin in master

**Comment by Betacarotin** [comment]
Come on, thats how you want to have it? Ego over good code? @danielkerr

**Comment by Betacarotin** [comment]
@danielkerr its not about the master branch, I wrote that. Please reopen.

**Comment by mhcwebdesign** [comment]
@Betacarotin : I have updated your issue title to make it clear it's for 3.0.x.x_Maintenance.

Anyway, I just tested a modified order_form.twig successfully, to get rid of this issue. Before a merge into the 3.0.x.x_Maintenance, can you please try it out, with the following changes in the admin/view/template/sale/order_form.twig:

Add this:
```
function htmlDecode(value) {
  return $("<textarea/>").html(value).text();
}
```
before 
```
// Payment Address
$('select[name=\'payment_address\']').on('change', function() {
```

Change the lines containing
```
			$('#tab-payment input[name=\'firstname\']').val(json['firstname']);
			$('#tab-payment input[name=\'lastname\']').val(json['lastname']);
			$('#tab-payment input[name=\'company\']').val(json['company']);
			$('#tab-payment input[name=\'address_1\']').val(json['address_1']);
			$('#tab-payment input[name=\'address_2\']').val(json['address_2']);
			$('#tab-payment input[name=\'city\']').val(json['city']);
```
to these ones:
```
			$('#tab-payment input[name=\'firstname\']').val(htmlDecode(json['firstname']));
			$('#tab-payment input[name=\'lastname\']').val(htmlDecode(json['lastname']));
			$('#tab-payment input[name=\'company\']').val(htmlDecode(json['company']));
			$('#tab-payment input[name=\'address_1\']').val(htmlDecode(json['address_1']));
			$('#tab-payment input[name=\'address_2\']').val(htmlDecode(json['address_2']));
			$('#tab-payment input[name=\'city\']').val(htmlDecode(json['city']));
```

Also, change the lines
```
			$('#tab-shipping input[name=\'firstname\']').val(json['firstname']);
			$('#tab-shipping input[name=\'lastname\']').val(json['lastname']);
			$('#tab-shipping input[name=\'company\']').val(json['company']);
			$('#tab-shipping input[name=\'address_1\']').val(json['address_1']);
			$('#tab-shipping input[name=\'address_2\']').val(json['address_2']);
			$('#tab-shipping input[name=\'city\']').val(json['city']);
```
to the following ones:
```
			$('#tab-shipping input[name=\'firstname\']').val(htmlDecode(json['firstname']));
			$('#tab-shipping input[name=\'lastname\']').val(htmlDecode(json['lastname']));
			$('#tab-shipping input[name=\'company\']').val(htmlDecode(json['company']));
			$('#tab-shipping input[name=\'address_1\']').val(htmlDecode(json['address_1']));
			$('#tab-shipping input[name=\'address_2\']').val(htmlDecode(json['address_2']));
			$('#tab-shipping input[name=\'city\']').val(htmlDecode(json['city']));
```

**Comment by condor2** [comment]
> just tested and it works fin in master

or not.....

![oc4_test](https://user-images.githubusercontent.com/14251939/208632890-a1e880bb-e785-43fd-a97c-6fc83b1e1a5d.png)

**Comment by Betacarotin** [comment]
I also found that there is no input field validation in oc? That a email must contain @ or that a zip code is only numbers. Or did I miss the validation input somewhere in the backend?

**Comment by mhcwebdesign** [comment]
The issue with the doubly escape ampersands or other characters in the admin order editor has now been fixed in the 3.0.x.x_Maintenance branch.

@condor2 : For other issues, or different branches (e.g. master branch) please open separate github issues with a precise description on how to reproduce an issue, otherwise Daniel will just close them.

@Betacarotin : As regards field validation, most of it is done on the frontend, not in the admin order editor. And postcodes can have letters in them, too, as is for e.g. the case in the UK or Canada.

**Comment by danielkerr** [comment]
3.x needs to be reported in a different repository

**Comment by mhcwebdesign** [comment]
> 3.x needs to be reported in a different repository

Which one? [Opencart-3](https://github.com/opencart/opencart-3) ? The latter has become too different from 3.0.3.8 and is more like a 3.1.0.0 in terms of changes and backwards compatibility with 3rd party extensions, unlike the 3.0.x.x_Maintenance branch.
