### ISSUE TITLE
Translation to what's been said here

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#12118]
Without knowing why exactly the opencart-3 has been brought up as also why I can't reply to the topic at this time, it's ok, I'll translate what Daniel explained from this commit: https://github.com/opencart/opencart/issues/12112#issuecomment-1359674436 . So, what it means is that Daniel is in the wonders if the maintenance branch should not be moved into a separated repository from the main repository rather than leaving it inside the opencart project as the same as it is currently with opencart-3 repository.

**Comment by condor2** [comment]
Because reply was restricted for Contributors....

No. Daniel don't want **3.0.x.x_Maintenance** branch issues to be reported in Opencart repo/Branch for the 3.0.x.x_Maintenance branch.

If this is it then should move **3.0.x.x_Maintenance** branch as a separate repository.

**Comment by danielkerr** [comment]
so why the fuck do u need to open an issue!

a non issue! ohh why have done this, i must be told, so im going to open an issue to force Daniel to tell me!

grow up! i dont anwer to u oor any one else1\

**Comment by TheCartpenter** [comment]
> so why the fuck do u need to open an issue!
> 
> a non issue! ohh why have done this, i must be told, so im going to open an issue to force Daniel to tell me!
> 
> grow up! i dont anwer to u oor any one else1\

To clarify this situation, I guess you haven't clicked on the comment link. In case you haven't, or even if you did, the comment post wasn't addressed to you which means I don't know shit clue on why you're posting me this. While the addressed post was closed due to a restrictive message, as I also mentioned on my first post, is the reason why a new commit was created since Github does allow to link commits from one-and-another which, therefore, I haven't broke any regulations about it these restrictions were applied by you or an author that had the cowardness to set it.

Meaning, if that setting wasn't in-place, prior to this post and this commit. none of this would of happened. Therefore, that blame goes on you buddy and only you at the end of the day since you did posted on the addressed commit in the meantime which doesn't put you in a better position than anyone else and even less to let people post against repositories that are located on your own projects. At least, I had the decency to defend it as you should do the same instead of telling people bunch of stuff they may not deserve while your own people would rather want to preserve what they've built for others as for you to consider these contributors for the right cause.

You don't like peoples' replies? Well boohoo pell 'cause if you don't like the way the web works, then build your own since you're still one guy as anyone else who will depend on what we got if you're not able to change those rules!
