### ISSUE TITLE
4.0.1.1 After the installation，Modifications not showing

### ISSUE THREAD

**Issue by xcgsoho** [opencart/opencart#12114]
PHP-8.0.26 ，Apache 2.4.54， MySQL 8.0.24，4.0.1.1 After the installation，No "Modifications" under the Extensions menu，
 
![0221219202850](https://user-images.githubusercontent.com/47844554/208429802-b14bbe5f-cf29-4382-b68f-86a6d968f002.png)

Please help me

**Comment by mhcwebdesign** [comment]
Not a bug, Opencart 4 has no built-in OCmod anymore, it uses event handlers only for modifications.
