### ISSUE TITLE
Master Branche "property_exists" seem to doesn't work anymore

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#12128]
Master Branche

"property_exists" seem to doesn't work anymore. Anyone else have a problem with this?

https://github.com/opencart/opencart/blob/0fba10eade9b4f7f89891ea148b53b1335b4d403/upload/catalog/model/checkout/order.php#L253

https://github.com/opencart/opencart/blob/0fba10eade9b4f7f89891ea148b53b1335b4d403/upload/catalog/model/checkout/order.php#L272

**Comment by danielkerr** [comment]
im testing this with php8.2 and its coming up as working.

**Comment by danijelGombac** [comment]
My website running on php 8.1.13. Is php version 8.2 the minimum for OC to work or does it also work on 8.1?  Thanks for the reply.

**Comment by danielkerr** [comment]
check the latest please

**Comment by danielkerr** [comment]
ok i just tested and it works on both php8.1 and php 8.2 without ur changes

**Comment by danielkerr** [comment]
ok its working with the last commit i did
