### ISSUE TITLE
Cannot assign resource to property Opencart\System\Library\DB\PgSQL::$connection of type object 

### ISSUE THREAD

**Issue by Nwgazzazamwal** [opencart/opencart#12121]
**What version of OpenCart are you reporting this for?**
opencart-4.0.1.1

**Describe the bug**
im getting this error, after filling the db form in install/index.php.
```
TypeError: Cannot assign resource to property Opencart\System\Library\DB\PgSQL::$connection of type object in /Applications/MAMP/htdocs/opencart1/system/library/db/pgsql.php on line 17
```

**Comment by eturerer** [comment]
include './system/helper/db_schema.php';

$tables = db_schema();

//echo '<pre>' . print_r($tables, true) . '<pre>';
$schema = "cbpublic.";
$prefix = "gmx_";

$sql = "";
$BR =  '';
$HR =  '';
$TAB =  '';

$debug = true;

if ($debug) {
    $BR =  '<br>';
    $HR =  '<hr>';
    $TAB =  '&emsp;';
}

foreach ($tables as $table) {

    $sql .= $BR . "DROP TABLE IF EXISTS " . $schema . $prefix  . $table['name'] . "; ";

    $fields = $table['field'];

    foreach ($fields as $field) {
        if (str_starts_with($field["type"], 'enum')) {
            $sql .= "DROP TYPE " . $field["name"] . "_enum_type ;" . $BR;
            $sql .= "CREATE TYPE " . $field["name"] . "_enum_type AS " . $field["type"] . ";" . $BR;
        }
    }

    $sql .=  $BR . "CREATE TABLE " . $schema . $prefix . $table['name'] . " ( " . $BR;

    foreach ($fields as $field) {
        $col_name = $field["name"] == 'column' || $field["name"] == 'default' ? '   "' . $field["name"] . '"' : "\r" . $field["name"];

        $sql .=  $TAB . $col_name . ' ';

        // echo '<pre>' .   print_r($field, true) . '</pre>';

        if (isset($field["auto_increment"])) {
            $sql .= " SERIAL";
        } elseif (str_starts_with($field["type"], 'enum')) {
            $sql .= $field["name"] . "_enum_type";
        } elseif (str_starts_with($field["type"], 'tinyint(1)')) {
            $sql .= "BOOLEAN";
        } elseif (str_starts_with($field["type"], 'bigint')) {
            $sql .= "BIGINT";
        } elseif (str_starts_with($field["type"], 'int') || str_starts_with($field["type"], 'mediumint(')) {
            $sql .= "INTEGER";
        } elseif (str_starts_with($field["type"], 'smallint') || str_starts_with($field["type"], 'tinyint')) {
            $sql .= "SMALLINT";
        } elseif (str_starts_with($field["type"], 'decimal') or str_starts_with($field["type"], 'double')) {
            $sql .= preg_replace('/double|decimal/i', ' NUMERIC', $field["type"]);
        } elseif (str_starts_with($field["type"], 'datetime')) {
            $sql .= "TIMESTAMPTZ";
        } elseif (str_starts_with($field["type"], 'mediumtext')) {
            $sql .= "TEXT";
        } else {
            $sql .=  $field["type"];
        }

        if ((int)$field["not_null"] > 0) {
            $sql .= " NOT NULL";
        }

        if (isset($field["default"])) {
            $sql .= " DEFAULT '" . $field["default"] . "'";
        }

        $sql .=  ",";
        $sql .= $BR;
    }

    if (isset($table['primary'])) {
        $primary_data = [];

        foreach ($table['primary'] as $primary) {
            $primary_data[] = "" . $primary . "";
        }

        $sql .= "PRIMARY KEY (" . implode(",", $primary_data) . ")" . $BR;
    }

    $sql .= ");" . $BR;

    $sql .= $BR;

    // echo '<pre>' . print_r($table['index'], true) . '</pre>';
    if (isset($table['index'])) {
        foreach ($table['index'] as $index) {
            $index_data = [];

            foreach ($index['key'] as $key) {
                $index_data[] = $key;
            }

            $sql .=   "CREATE INDEX idx_" .  $prefix . $table['name'] . "_" . $index['name'] . " ON " .  $schema . $prefix . $table['name'] . "(" . implode(",", $index_data) . ");<br>";
        }
    }

    $sql .= $HR;

    //  echo '<pre>' . print_r($table['field'], true) . '</pre>';
}


//alter table orderlines add foreign key (orderid) REFERENCES Orders(ORDERID);

foreach ($tables as $table) {

    if (isset($table['foreign'])) {
        foreach ($table['foreign'] as $foreign) {
            $sql .= "ALTER TABLE " . $schema . $prefix  . $table['name'] . " ADD CONSTRAINT ". $prefix . $table['name']."_". $foreign['table'] ."_".$foreign['key'] ."_fkey FOREIGN KEY (" . $foreign['key'] . ") REFERENCES " .  $schema . $prefix . $foreign['table']  . " (" . $foreign['field']  . ");" . $BR;
        }
    }
}
echo $sql;

**Comment by danielkerr** [comment]
@eturerer ur just wasting peoples time

**Comment by danielkerr** [comment]
removed access to postgresql via install. unfortunately the mysql and postgresql are too different in the syntax. it would mean i need to remove backticks from every table and field to make them compatible but would still be having issues down the line. after checking around other php open source projects don't use postgresql unless its a specially modified version of the script.
