### ISSUE TITLE
Recent autocomplete changes not working!

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#12129]
**What version of OpenCart are you reporting this for?**
Master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
input product name in filter did not show product name list to choose.
input category name in product link tab category did not display category to select.
**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
[screen-recorder-mon-jan-02-2023-13-33-20.webm](https://user-images.githubusercontent.com/5079756/210197808-57f393d5-fcb9-4a1e-9f2a-be6c36e0f3d4.webm)

it works
