### ISSUE TITLE
Favicon not being set in browser tab

### ISSUE THREAD

**Issue by SofaKingRotten** [opencart/opencart#12127]
v 4.0.1.1

The live demo at opencart.com is not displaying the favicon even though there is a image in place. This was working in a previous version that I tested.

Go to Admin -->System Settings then Edit the Store and go to Store tab

The image shown below on that page should become your favicon in browser tab but it does not appear, even after closing/reopening tabs.

EDIT:  I have also noticed the same image is being used in the contact.php page, but because this image was initially used for the favicon (in version 2?), it has a low resolution and looks terrible on the contact page. Perhaps there should be an additional image for each location on the contact page, as well as a favicon for each location? Either that or perhaps the favicon needs to be added to the db elsewhere. I'm not sure what the original intent was, so I digress...

Live server
Apache Version | 2.4.54
PHP Version | 7.3.33 (native) - 8.1 selected in cPanel
MySQL Version | 10.3.37-MariaDB-cll-lve

Using Windows 10 21H2 x64 to administrate
Tested this on Firefox 108.1 and Chrome 108

**Comment by danielkerr** [comment]
add it viua the template editor manually.
