### ISSUE TITLE
[Master Branch] SEO Keyword validation issue

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#12136]
I think the **admin/controller/design/seo_url.php** needs to be fixed for the **save** function, in the validation part, as follows, for line 493:

old:
`		if ($seo_url_info && ($seo_url_info['key'] != $this->request->post['key']) || ($seo_url_info['value'] != $this->request->post['value'])) {
`

new:
`		if ($seo_url_info && (($seo_url_info['key'] != $this->request->post['key']) || ($seo_url_info['value'] != $this->request->post['value']))) {
`

Otherwise, if it can't find the **$seo_url_info**, it shouldn't use the **$seo_url_info['value']**

**Comment by TheCartpenter** [comment]
That is the point of using the old validation way. ```$seo_url_info``` is supposed to be found. If it's not found, an error would be thrown on screen or in the logs based on the logs settings. By using the new way, it would suppress the fact that ```$seo_url_info``` could not be found based on the above theory.

**Comment by mhcwebdesign** [comment]
The **$seo_url_info** is not always supposed to be found! It may not yet exist in the DB for a certain keyword. 

This is a bug which needs to be fixed.

**Comment by TheCartpenter** [comment]
If it's not always found based on a value that may not yet exist once the feature has been enabled, then that, itself, is not a bug.

**Comment by condor2** [comment]
For example if you edit a SEO url value and you delete the keyword then Save, there is no error message.
But in console is...

Error: Unexpected token '<', "<b>Warning"... is not valid JSON
OK
<b>Warning</b>: Undefined array key "value" in <b>admin\controller\design\seo_url.php</b> on line <b>493</b>{"error":{"keyword":"Keyword is already in use!"}}

**Comment by mhcwebdesign** [comment]
@condor2: Exactly, hence my suggested bugfix.

**Comment by condor2** [comment]
In controller is made required...but not in twig form...

**Comment by TheCartpenter** [comment]
> In controller is made required...but not in twig form...
> 
> Also if keyword should not be suposed to be empty...then when you delete the keyword and save, should display...Keyword can't be empty....
> 
> And added required to div...

The keyword empty part, I conclude the same thing here on this one.

**Comment by condor2** [comment]
With that change you allow to save one SEO URL entry with keyword empty....but you can't do that from Product form...
Also why you are you allowed to save one?....but you can't save more....

**Comment by danielkerr** [comment]
It's working

**Comment by condor2** [comment]
https://user-images.githubusercontent.com/14251939/211261901-bf390016-2507-411f-a839-0bb1741802ca.mp4

**Comment by danielkerr** [comment]
@condor2 having a blank keyword is nothing to do with what hes reporting!

you just high jack the thread!

**Comment by condor2** [comment]
Why you can save with a blank keyword on SEO URL? when this should not be possible.....

> Also **if keyword should not be suposed to be empty**...then when you delete the keyword and save, should display...**Keyword can't be empty**....
.

**Comment by condor2** [comment]
Now if you can't save with blank keyword....this part of text should be removed.

**Leave blank if you just want to remove the perimeter.**
