### ISSUE TITLE
OpenCart  4.0.1.1  Signature hash does not match! 

### ISSUE THREAD

**Issue by Aamirx64** [opencart/opencart#12133]
**What version of OpenCart are you reporting this for?**
   4.0.1.1

**Describe the bug**
Signature hash does not match! tried every solution. I have completed building website. Now i am stuck on Payment Gateway.  Currently on Localhost.

What section does it affect?
Checkout/Gateway

![Screenshot (7)](https://user-images.githubusercontent.com/99568000/211154465-d5aa386e-afc3-48f3-8164-eef40f0f08de.png)

**Comment by danielkerr** [comment]
it does not work on localhost

iot needs a domain then u need to register the store under account > your stores
