### ISSUE TITLE
End-back file renaming shows duplicate directories.

### ISSUE THREAD

**Issue by troylee1990** [opencart/opencart#12130]
Tested on 4.0.2.0, based on php8.1 and 8.2, after installed, tried rename the end-back directory file, Button is not work, but the actual problem is that the root directory shows duplicate directories, one is changed name, another is default admin folder.
![image](https://user-images.githubusercontent.com/121782615/210196548-8ff9631f-7d23-4586-9f64-974145ec3de9.png)

**Comment by danielkerr** [comment]
it should auto delete as soon as u login into the admin
