### ISSUE TITLE
2issues frontend registration button is not compatible etc

### ISSUE THREAD

**Issue by troylee1990** [opencart/opencart#12132]
See photos directly,
Tested master line, php8.1+8.2, Nginx1.22 with latest chrome version 108.0.5359.125
1. Extra language code show top leftside.
2. Frontend sign up button not working. Then reload to see ID Registered successfully.
![image](https://user-images.githubusercontent.com/121782615/210737085-744dc5fd-9284-4feb-9f54-730cb388e62b.png)
![image](https://user-images.githubusercontent.com/121782615/210737121-76f73d65-713d-445b-853a-39caac8b2ab1.png)

**Comment by troylee1990** [comment]
![image](https://user-images.githubusercontent.com/121782615/210737853-8de21b45-53d1-4b90-996a-5092a5b0b651.png)
additional but not is not a bug

**Comment by troylee1990** [comment]
oen more... Product list compatibility issue, icons are missing.
![image](https://user-images.githubusercontent.com/121782615/210738718-d5259b9d-e9a9-4653-9fa1-d2d889c0dd82.png)

**Comment by troylee1990** [comment]
Hummm. Add to cart not work too unless reload page to see changes, checkout page not work too. eh..Seems like a lot of things went wrong with the latest update 30minutes ago.. we are waiting for V 4.0.2.0 for the final launch then start our project.so i tested everyday. thank you.

**Comment by troylee1990** [comment]
2023-01-05 09:09:31 - PHP Notice: getimagesize(): Error reading from /image/catalog/index.html!
File: /model/tool/image.php
Line: 15
![image](https://user-images.githubusercontent.com/121782615/210743185-0e3de083-4057-4a99-af00-4b0ca5f09865.png)

**Comment by chongshengdz** [comment]
> 2023-01-05 09:09:31 - PHP Notice: getimagesize(): Error reading from /image/catalog/index.html! File: /model/tool/image.php Line: 15 ![image](https://user-images.githubusercontent.com/121782615/210743185-0e3de083-4057-4a99-af00-4b0ca5f09865.png)

such problems are due to your operating system is too old.

**Comment by chongshengdz** [comment]
Rocky, Alma, and RHEL 8 and 9 on x86_64
CentOS and RHEL 7 on x86_64 (This version is extremely old and no longer recommended, please choose one of the above compatible systems instead.)

**Comment by danielkerr** [comment]
master only shows these files:

{/,.ico,.jpg,.jpeg,.png,.gif,.webp,.JPG,.JPEG,.PNG,.GIF}

**Comment by danielkerr** [comment]
also removed the language code front end already
