### ISSUE TITLE
OC not see languages after updating files from here

### ISSUE THREAD

**Issue by zoigecyb** [opencart/opencart#12135]
Helo.
I've uploaded almost all files from here to my site. thought some fixes will be good.
after that on site and in admin panel i have all texts like "text_catalog""text_design" etc.
in oc_settings i see config_language uk-ua andconfig_language_admin uk-ua. but OC don't read language files at all.
language files was simply uploaded to server and lang added in panel manually.

now i cannot see what changed and why OC don't read files in admin/language/uk-ua folder.
the same with catalog/language/uk-ua

also i have ru-ru. the same problem. even if i switch language nothing happens.
before "update" i had a problem with seo, language like to be changed but nothing happens. OC read only uk-ua.

p.s. i removed files in storage/cache folder (outside OC). all file permissions is ok, nothing was changed.

edited:
in system/engine/loader.php
public function language(string $route, string $prefix = '', string $code = ''): array {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_\-\/]/', '', $route);

var_dump($route);
...

$route returns string(7) "default" string(16) "common/dashboard" string(15) "common/security" string(13) "common/header" string(18) "common/column_left" string(13) "common/footer"

but few earlier it returned "uk-ua" but not default.

**Comment by danielkerr** [comment]
did u add it to system > localisation > language

**Comment by zoigecyb** [comment]
Of course i added.
