### ISSUE TITLE
Affiliate Reports missing

### ISSUE THREAD

**Issue by JoshuaAGE** [opencart/opencart#12147]
The OpenCart doc describe affiliate reports but at the demo and OpenCart 4.0.2.0 installation the reports cannot be found.

OpenCart 4 Demo: https://demo.opencart.com/admin/index.php?route=report/report

OpenCart doc: http://docs.opencart.com/en-gb/report/marketing/commission/

**Comment by danielkerr** [comment]
its there just not got the permissions

**Comment by JoshuaAGE** [comment]
I tried to fix it manually as this is a part I need for my shopping cart but was totally unable to find the files related to this report, neither on in the opencart-master zip file, before and after installation, and neither in the extensions and the permissions at the user's settings are also all set correctly. 

Would be really good to know, which version this will be included?

**Comment by JoshuaAGE** [comment]
> will be fixed in next release.

I tried to fix it manually as this is a part I need for my shopping cart but was totally unable to find the files related to this report, neither on in the opencart-master zip file, before and after installation, and neither in the extensions and the permissions at the user's settings are also all set correctly.

Would be really good to know, which version this will be included?

**Comment by danielkerr** [comment]
i checked and its missing from master branch

**Comment by JoshuaAGE** [comment]
> i checked and its missing from master branch

Could you please include it in the next update you publish?

**Comment by JoshuaAGE** [comment]
> i checked and its missing from master branch

I don't want to bother you but could you please include it in the master version? It is missing in all 4.x versions.

**Comment by danielkerr** [comment]
i think its now the customer_transaction report

**Comment by danielkerr** [comment]
there is no report. use the customer transaction report instead.
