### ISSUE TITLE
language from seo url is ignored

### ISSUE THREAD

**Issue by zoigecyb** [opencart/opencart#12142]
Hi,
i found that if in oc_seo_url table more that one record with key='language', value='lang code', keyword='somekw' it is ignored.
url like 'uk/category/mycat' etc
in startup/language.php $this->request->get has only _route_ variable.

but if i add ...?language=uk-ua to the url (manually) all works fine. and in startup/language.php (where actually language is set) $this->request->get has two variables _route_ and language.

and i cannot understand what to fix to force OC use language code from seo url.

OC 4.0.1.1

P.S. please, do not close post as completed without answer.
I tested - downloaded all files from here and owerwrite them. DB left old.
With few languages added (in panel of course too) - there is only language from system/config/default works. with any other - it is not loaded at all.

i saw closed posts with this problem. but nothing changed. all posts are silently closed

**Comment by danielkerr** [comment]
already been reported and fixed

**Comment by mstudzitsky** [comment]
HI! I  have same problem! I try upgrading and downgrading - nothing helped. There is no "language" key in the request. Seo processed after. 

I have no idea.
