### ISSUE TITLE
Opencart does not send email. 

### ISSUE THREAD

**Issue by ultimoimperio** [opencart/opencart#12141]
Opencart Version 3.0.3.1 - When customer place order or open an account no e-mail is being sent. But when we use mail function under marketing tool, e-mail function is working

Auto e-mail system is not working. Admin and customers are not getting any e-mails. Does anyone know what is wrong?

Thanks

**Comment by egproo** [comment]
Check events
Especially if you upgraded from an older version

**Comment by mhcwebdesign** [comment]
This is better posted on the OpenCart forum.
