### ISSUE TITLE
Discussion about SEO links in OpenCart 4

### ISSUE THREAD

**Issue by gitrequests** [opencart/opencart#12145]
Hello. The opinion of the Open Cart community regarding SEO links in the project is interesting.
---
In my opinion, such open projects with a community of developers should remain flexible and meet the needs of the maximum number of projects that the engine is designed for.

It can be both large stores - multi-language, multi-currency, **but also support a large number of regional projects**, stores with not so huge ambitions and at the same time provide tools for project development.

I also understand that this kind of open source projects is difficult to implement and you have to sacrifice something, inclining the project in some particular direction ... But was it really worth it to change the logic for building links?

It seems to me that from a project that could cover 90% of the needs of online stores, we suddenly turned into a heavily customized monster that imposes multilingualism and a link structure! I understand that there could be complaints about the speed of the router, some other pitfalls ... But it worked quickly in OpenCart 3 by default and never had problems with routing.

But here are the problems (in my opinion) that we have today (with OpenCart4):

1. Adding a language to links by default (https://github.com/opencart/opencart/commit/85c7ae626d487d250e4a76557b723c3cc7718420)
2. Adding a category or product to the generated links (Due to a change in route parsing).

---

It would seem that this can be experienced. OpenCart4 brought a lot of great changes too! What are the reworked extensions worth! It's just amazing.

But look at the situation from another point of view:

---

**1.** I have no statistics on the use of OpenCart in general, **but not all stores need multilingual**. Until recently, I thought that this was a custom parameter and it could be removed, but I was very surprised when I saw the generation of links with the language parameter in almost all controllers (See this PR: https://github.com/opencart/opencart/commit/85c7ae626d487d250e4a76557b723c3cc7718420)!

As a result, we get all links either with the language parameter directly in the link:
for example: `https://domain.com/en-gb/some/route`

Or remove the language parameter from seo_url in the admin panel and the language parameter is added to all links in query string! You can't turn it off!

For example: `https://domain.com/some/route?language=en-gb`

Owners of regional stores will immediately ask the question - how to remove it? Customers of regional stores also do not understand why this parameter is everywhere (Because it's a regional store)!

It also breaks backward compatibility and the ability to attract the audience that comes from other systems. Now we don't have the option to choose whether or not to place the language parameter in the link.

---

**2.** OpenCart 3 remained one of the few online store engines with really human readable URLs! I recently conducted an audit of the engines of online stores:

- Magento is the same algorithm as in OpenCart3.
- PrestaShop - adds ID to all routes! You cannot change this behavior.
- Sylius - Adds prefixes (category, product) to links.
- Drupal Commerce - Due to taxonomy, it is difficult to generate multiple nested categories in links.

The only problem I've seen with OpenCart3 is that since there's no way to select a main category for a product, it's impossible to generate a SINGLE URL for a product (with categories).

For example:
There is a product1 and it is placed in two categories - category1 and category2. If you go to category1, you will see a link to the product in this form:

`https://domain.com/category1/product1`

If you go to category2, you will see a link to the product in this form:

`https://domain.com/category2/product1`

The search engine will already have 2 duplicates of the page! And everything would be decided by the canonical tag, but from what category should it be built? As a result, there is only one solution for stores - to build a canonical link without categories. For example this one:

`https://domain.com/product1`

---

With the update of OpenCart4 we have a new problem! Substitution in the address of the controller link, which breaks the semantic nesting of links!

For example, a category link now looks like this:

`https://domain.com/en-gb/catalog/category/subcategory/`

When visiting a product from this category, what link do you expect to see? Personally, it seems to me that:

`https://domain.com/en-gb/catalog/category/subcategory/product-slug`

But now it doesn't... In the new OpenCart4 it looks like this:

`https://domain.com/en-gb/product/category/subcategory/product-slug` <- (`product` after language parameter instead of `catalog`)

I have no idea how search engines react to this, but this is not the behavior that a HUMAN expects to see.

---

**3.** And the last, but in my opinion the most important!

What do you, as a business owner or store customer, **expect to see** as a result? **What drives** your business as a business owner?

You could say that in the end it doesn't matter. That SEO is one small tool of all possible promotion channels. And you will find for yourself a bunch of other excuses why the links look that way.

But ultimately, **your business is your face**! The face of the company and all its employees. **Links should look** neat and semantically correct. Not for a programmer, but for clients and business owners.

- **Musicians** - who sell merch on the site and want to see a logical nesting in the link, and not the name of the controller.
- **Owners of a regional business** - who see an extra parameter in the link (language) as useless and incomprehensible for their business.
- And many other users...

What Google thinks about it can be read here: https://developers.google.com/search/docs/crawling-indexing/url-structure

Please correct me if I am wrong somewhere.

---

On the matter. If the community agrees in this belief, I will make a PR with the ability to customize the logic for adding a language to links. I invite to discussion.

**Comment by gitrequests** [comment]
Why is this closed as completed? Or did I miss something?

**Comment by aksthelion** [comment]
I'm using OC 4 version. I want to set a local shop for the UK only. I've removed all countries and zones except for UK. I can still see "en-gb" in the url. It makes no sense, it should be removed if there is only one country and one language. Is there any workaround for it?

**Comment by bluebrad** [comment]
the language should not be in the address bar and use cookies for tracking.
also the browser produces the default language to the website. the default
language should come from the user not the domain.

**Comment by danielkerr** [comment]
It's a feature and not going to kill the seo

**Comment by aksthelion** [comment]
> It's a feature and not going to kill the seo
Yes, you are right but it is pain in the as$$ to keep it when it's not needed. You can never convince SEO guy to keep it no matter what. Can't we do it with .htaccess redirect? Will it break something in OC?

**Comment by bluebrad** [comment]
it sould be a trigger in the url and &= or ?= not a sub directory.
name.domain/name/ is used for sub directories
yes it will break SEO management. and it will break management of the
system and will break analytics.
