### ISSUE TITLE
Lnaguage files are not loaded

### ISSUE THREAD

**Issue by zoigecyb** [opencart/opencart#12148]
Hi.

In common/languages:
en-gb/...
uk-ua/uk-ua.php
uk-ua/common/...
etc
in admin folder structere it the same.

in DB:
code - en-gb, sort_order "-2", name- English, status - 1
code - uk-ua, sort_order "-2", name- Ukrainian, status - 1
(all enabled)

in any case (?language=uk-ua or /uk with seo):
trace $language_info in catalog/controller/startup/language.php:
i added line 15-16:
`
		$language_info = $this->model_localisation_language->getLanguageByCode($code);
var_dump($language_info);`
returns uk-ua

but trace in system/ibrary/language.php:
lines 135-136:
`print_r($file);`
returns .../common/language/en-gb/default.php
.../common/language/en-gb/common/header.php
etc.

all texts that are used from DB (category names, product names etc) - are switched, but all texts that have to be loaded from language files are loaded only from en-gb. (default) but not loaded from language code folder.
in case i set uk-ua as default in system/config/defaults.php - the same, but all is loaded from .../catalog/labguage/uk-ua/default.php (also in this case i have to rename uk-ua.php to default.php)

in my previous posts i wrote about this. all of them was closed as fixed.

all described above tested on clean install from master branch and tried to overwrite files on OC 4.0.1.1 (which i downloaded from here in december 2022)

in admin panel works only default language. frontend shows that language is switched, but nothing happens.
"tracing" from what files texts are loaded - returns the same. (but under admin/language folder)

P.S. i tried next:
gave oc_language_example.ocmod.zip
overwrote there all files to my own. changed german to ukrainian etc.
removed language files from catalog/language, admin/language. removed from DB.

the result - it added 100500 same languages to DB (in my case it is ukrainian with language_id 4,5,6,7....), but nothing works. in this case it doesn't want to switch language at all.
and in case of adding language as extension - all language_id in all tables must be changed what actually is very hard work.
of course i changed. result the same. texts are loaded only from default file.

**Comment by zoigecyb** [comment]
As a quick solution i added to the end of system/library/language.php
``` 
public function setCode ($code='') {
        if ($code) {
            $this->code=$code;
        }
    }
```

and catalog/controller/startup/language.php:

 lines 26-29:
```
$this->config->set('config_language_id', $language_info['language_id']);
	$this->config->set('config_language', $language_info['code']);
            $this->language->setCode($language_info['code']);
            $this->load->language('default');
```

**Comment by mhcwebdesign** [comment]
I am struggling to understand your description. What issue are you trying to resolve?

**Comment by zoigecyb** [comment]
When i have multiple languages and switch between them, texts from language files are not changed.
I showed paths from what languages are loaded - they are not changing.
sorry for my bad english

**Comment by zoigecyb** [comment]
When i have multiple languages and switch between them, texts from language files are not changed.
I showed paths from what languages are loaded - they are not changing.
sorry for my bad english

**Comment by danielkerr** [comment]
So this is latest version and not master branch
