### ISSUE TITLE
No match for Username and/or Password.

### ISSUE THREAD

**Issue by Mahmood-Hussain** [opencart/opencart#12153]
**What version of OpenCart are you reporting this for?**
4.0.1.1
3.0.3.6

**Describe the bug**
A clear and concise description of what the bug is
After Installation by following instruction admin is not able to login

What section does it affect?
admin module (dashboard is not able to accessible) 

**To Reproduce**
1. Install the opencart 
2. go to site.com/admin
3. enter credentials used at the the of installation
4. See error ( you won't be able to login)

**Expected behavior**
Take me to admin dashboard after login

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? 
 Tried on both local and Server 
 - Operating system
 Ubuntu and Mac
 - PHP version 
 8.0
 - Apache version 
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2022-06-14T13:30:55
 - Browser(s) tested with [e.g. chrome, safari - if applicable]
 chrome
 Version 109.0.5414.87 (Official Build) (x86_64)

**Comment by JoshuaAGE** [comment]
I install oc master version at least 10 times in the last couple of weeks and admin works without issues.

Maybe check cookie issues? Different browser?

Also, try latest master version which is 4.0.2.0 including some unmarked changes.

**Comment by Mahmood-Hussain** [comment]
I have tried different browsers, and operating systems I am interested in OC 3.0.3.6 but I can also try installing oc from the master branch to see if it works.

**Comment by mhcwebdesign** [comment]
Please post on the OpenCart forum for support. Nobody else seems to be able to reproduce your bug, so something must have gone wrong with your installation. Use 3.0.3.8, or 3.0.x.x_Maintenance, for live websites, OpenCart 4 is still subject to many bugfixes.
