### ISSUE TITLE
[master] Events:  It cannot be changed the $route for controllers and models

### ISSUE THREAD

**Issue by nmpetkov** [opencart/opencart#12155]
The way classes are loaded and their methods called has changed since version 4.0.1.1 and the current state of master:

https://github.com/opencart/opencart/blob/master/upload/system/engine/loader.php

As a result, specifically for controllers and models, the route can no longer be changed in before event.

Is this a bug, and if not, how can I change the route for controller or model?

**Comment by danielkerr** [comment]
already fixed in master. or at least its doing it a different way
