### ISSUE TITLE
Load API

### ISSUE THREAD

**Issue by ingdjason** [opencart/opencart#12152]
**What version of OpenCart are you reporting this for?** 
oepncart-4.0.1.1

**Describe the bug**
I'm getting an error related to the opencart api, when i try to call many of other endpoint i got in html page with: **The page you requested cannot be found!**

example: `/index.php?route=api/sale/order.load&language=en-gb&store_id=0&order_id=1`

**Comment by mhcwebdesign** [comment]
Try it with the latest master branch, to see whether it has been fixed.

Also, please provide more details on how exactly, in what context, you have used the api.
