### ISSUE TITLE
[master] & [4.0.1.1] Error in catalog/controller/mail/voucher.php when adding order history

### ISSUE THREAD

**Issue by nmpetkov** [opencart/opencart#12154]
When adding history to orders, an error occurs, which is logged in the error log:

`TypeError:  Opencart\Catalog\Model\Checkout\Order::getOrder(): Argument #1 ($order_id) must be of type int, array given
File: .../catalog/model/checkout/order.php
Line: 169`

After not easy debugging, because it turns out in an event, the error occurs in the
`catalog/controller/mail/voucher.php`
on line 7:
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/mail/voucher.php#L7

The error also occurs when there are no vouchers at all.

The trace shows that the argument passed is not $order_id, but an array $order_info.
I offer a solution:

Instead of lines 5-7, to put one line:

`$order_info = isset($args[0]) && is_array($args[0]) && $args[0] ? $args[0] : null;`

**Comment by danielkerr** [comment]
just tested and works on master branch please look fo rthe fix in the code history
