### ISSUE TITLE
Improve system/library/db/mysqli->isConnected

### ISSUE THREAD

**Issue by nikkyandrei** [opencart/opencart#12160]
**What version of OpenCart are you reporting this for?**
4.0.1- i think also older is the same 

**Describe the bug**
In case `$this->connection->ping()` throw an exception the function should return also false 

**To Reproduce**
it is hard because it happens using CLI + PCNTL when an child close 
and to not lost the connection i registered in extension an temporary event  (register before fork and unregister after all childs close ) for `model/*/ before` to run  this:
```
    public function database_protect(...$param) {
        if (!$this->db->isConnected()) {
            $db = new \App\System\Library\DB($this->config->get('db_engine'), $this->config->get('db_hostname'), $this->config->get('db_username'), $this->config->get('db_password'), $this->config->get('db_database'), $this->config->get('db_port'));
            $this->registry->set('db', $db);
            // Sync PHP and DB time zones
            $db->query("SET time_zone = '" . $db->escape(date('P')) . "'");
        }
    }
```
and i get error : 
`<b>mysqli_sql_exception</b>: Malformed packet in <b>xxxxxxxxxxxx/system/library/db/mysqli.php</b> on line <b>66</b><br>`

**Expected behavior**
db->isConnected() shoud retun false 

I fixed the behavior by : 

```
    public function isConnected(): bool {
        if ($this->connection) {
            try {
                $ping = $this->connection->ping();
            } catch (\mysqli_sql_exception $e) {
                return false;
            }

            return $ping;
        } else {
            return false;
        }
    }
```

**Screenshots / Screen recordings**
.........................................

**Server / Test environment (please complete the following information):**
VPS, Cpanel, Centos 7 , PHP 8.1. MariaDB, Litespeed - all with last updates 

**Additional context**
...............................................

**Comment by danielkerr** [comment]
already fixed in master
