### ISSUE TITLE
[Master] TypeError: json_decode(): Argument #1 ($json) must be of type string, array given

### ISSUE THREAD

**Issue by rasulsh** [opencart/opencart#12161]
Version: current files from [master] branch (4.0.2.0)

**Issue**
show this error when open an missing order

TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in C:\laragon\www\oc4\admin\controller\sale\order.php on line 616

To reproduce:
Fresh install with current files from branch [master].
When you register as a customer and add a product to the cart, go to checkout until you reach the payment method, then go to admin and view missing orders, this error will appear when you view an order. 

Because $order_info contains an empty array for custom_field.

**Comment by danielkerr** [comment]
because working on subscriptions
