### ISSUE TITLE
opencart 2.0.2.0 order edit,view 404

### ISSUE THREAD

**Issue by vishaleng** [opencart/opencart#12163]
Opencart 2.0.2.0

**Describe the bug**
When i try to edit, view any order it goes to 404

When i try to debug i found its because of API section in admin/controller/sale/order.php

lets say function edit and here below code

$api_info = $this->model_user_api->getApi($this->config->get('config_api_id'));

			if ($api_info) {
				$curl = curl_init();

				// Set SSL if required
				if (substr(HTTPS_CATALOG, 0, 5) == 'https') {
					curl_setopt($curl, CURLOPT_PORT, 443);
				}

				curl_setopt($curl, CURLOPT_HEADER, false);
				curl_setopt($curl, CURLINFO_HEADER_OUT, true);
				curl_setopt($curl, CURLOPT_USERAGENT, $this->request->server['HTTP_USER_AGENT']);
				curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
				curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
				curl_setopt($curl, CURLOPT_FORBID_REUSE, false);
				curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
				curl_setopt($curl, CURLOPT_URL, HTTPS_CATALOG . 'index.php?route=api/login');
				curl_setopt($curl, CURLOPT_POST, true);
				curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($api_info));

				**$json = curl_exec($curl);**

so as soon as it enters to cur_exit it goes to 404 , if i change my code from

$api_info = $this->model_user_api->getApi($this->config->get('config_api_id'));

to

$api_info = '';

it works because it does not enter if section of validate.

**Comment by vishaleng** [comment]
HI denielkerr,

Can you tell me the solution for this please?

**Comment by ADDCreative** [comment]
Ask on https://forum.opencart.com/.
