### ISSUE TITLE
Bug language seo url

### ISSUE THREAD

**Issue by Y-Kilic** [opencart/opencart#12173]
**What version of OpenCart are you reporting this for?**
4.0.1.1
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
SEO urls

**To Reproduce**
- Add & delete 4x languages.
- enable .htaccess for seo
- enable seo in admin
- delete all category and products
- add category and fill in everything correctly including seo
- visit category seo url
- error??
Exception: Error: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
Error Code : HY093
SELECT * FROM `oc_seo_url` WHERE (`keyword` = :0 OR `keyword` LIKE '%/:1') AND `store_id` = '0' AND `language_id` = '4' in /home/test/public_html/system/library/db/pdo.php on line 55

**Expected behavior**
category page

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?: Cpanel production server
 - Operating system: windows 10
 - PHP version 8
 - Apache version cpanel apache
 - Browser(s) tested with [e.g. chrome, safari - if applicable] edge

I guess I won't be able to use opencart 4.x because of all the bugs?

**Comment by mhcwebdesign** [comment]
Please test it again with the master branch, to see whether this issue still exists or not.
