### ISSUE TITLE
[master] Post and get variables in request.php are trimmed, even if they are not empty

### ISSUE THREAD

**Issue by nmpetkov** [opencart/opencart#12178]
Post and get variables in request.php are trimmed, even if they are not empty. It is now impossible to enter space for example in currency simbol - before the simbol, or after.

I see this is made in this commit:
https://github.com/opencart/opencart/commit/1bc8e69f6e5c936ad08e6eb17e19e40544f74f43
The reason is:
`"This should prevent any form fields being entered with just white space."`

At line:
https://github.com/opencart/opencart/blob/master/upload/system/library/request.php#L46

The adopted solution to this, however, removes spaces not only from empty fields, but also from those in which there is meaningful input.

I suggest changing this and applying trim only to empty post and get variables.

**Comment by ADDCreative** [comment]
@nmpetkov You can work around it by entering another space such as a Non-breaking space.
https://en.wikipedia.org/wiki/Non-breaking_space#Keyboard_entry_methods

**Comment by nmpetkov** [comment]
@ADDCreative Tenk you for the advice, I now this approatch, but we then have to waste time explaining it to our customers too.
At least here is better to use `rtrim`, instead of `trim`.

**Comment by ADDCreative** [comment]
rtrim wouldn't be any better as the symbol could be on the other side. Probably what is needed, if all inputs are to be trimmed, is a checkbox to say to add a space between the symbol and currency.

**Comment by nmpetkov** [comment]
@ADDCreative The currency problem is just one example where the problem is found. In fact, it can appear in many other places, especially in third-party extensions. Finally, a common developer solution may be to hack the code…
Yes, rtrim half solves the problem. In my first post in this issue, I suggested a general solution.

**Comment by nmpetkov** [comment]
In fact, I can't understand why spaces should be removed for texts where there are other characters entered.

**Comment by nmpetkov** [comment]
The problem has another side effect:
When you enter spaces in front or behind and press the Save button, you get a message that it has been saved, but the spaces remain visible on the page. When you refresh, they disappear. This is because the recording uses Ajax technology. But to avoid inconsistency, and the desire to trim on the server is preserved, it is correct to do it in the frontend as well.
