### ISSUE TITLE
Error ocured with the new update 4.0.2.0 on checkout while choosing payment mode

### ISSUE THREAD

**Issue by FrankFontcha** [opencart/opencart#12182]
Error  : Warning: Payment method required!

` "if (isset($this->request->post['payment_method']) && isset($this->session->data['payment_methods'])) {
                $payment = explode('.', $this->request->post['payment_method'])

			if (!isset($payment[0]) || !isset($payment[1]) || !isset($this->session->data['payment_methods'][$payment[0]]['option'][$payment[1]])) {
				$json['error'] = $this->language->get('error_payment_method')
			}
		} else {
			$json['error'] = $this->language->get('error_payment_method')
		}

$payment return an array of size 1 ($payment[0]) but on the previous condition $payment[1] is needed

**Comment by danielkerr** [comment]
still being worked on
