### ISSUE TITLE
Checkout doesn't work!

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#12188]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
shipping method and payment method did not display options to select.

It seems cookie causes the problem because shipping method and payment method need to connect to third parties' domains.

Firefox error message:
Some cookies are misusing the recommended “SameSite“ attribute 3
Cookie “_ga_0M7V7YX6M6” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

However, I checked store setting and mysql table setting config_session_samesite that seemed samesite attribute value was right:
SameSite = None.
![cookie_error](https://user-images.githubusercontent.com/14033183/220815963-cc023a16-faf7-4a3c-a3e5-82a12341bd7d.png)

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by TheBiTTixX** [comment]
https://github.com/opencart/opencart/pull/12213

**Comment by polcape** [comment]
Hi, do you solve?

**Comment by cgcmart** [comment]
It's not working.

**Comment by danielkerr** [comment]
working in latest commit.

**Comment by polcape** [comment]
Hi, now shipping method appear but checkout page not work again.

I get this error 

2023-04-07 10:30:28 - Exception:  <b>Notice</b>:  Undefined property: Proxy::getMethods in <b>/app/sito/catalog/model/checkout/payment_method.php</b> on line <b>15</b> in /app/sito/system/engine/proxy.php on line 83

**Comment by danielkerr** [comment]
I think the method in the payment needs to be renamed from method to methods

**Comment by polcape** [comment]
Hi @danielkerr ,
I try update to the last commit (1 hour ago) now when I click choose on payment method seems load something but dont' load anything and checkout not work.

I get this error

2023-04-07 23:37:12 - Exception:  <b>Notice</b>:  Undefined property: Proxy::getMethods in <b>/app/sito/catalog/model/checkout/payment_method.php</b> on line <b>15</b> in /app/sito/system/engine/proxy.php on line 84

**Comment by danielkerr** [comment]
Yes because u have a 3rd party extension that does not have the required method

**Comment by danielkerr** [comment]
i have changed payment from getMethod to getMethods. payment gateways need to be rewritten. easy fix for all extensions,. unfortunately this needed to be done.

**Comment by polcape** [comment]
Yes @danielkerr , I already change only name of function but it's not enough.
I open ticket to developer of extension and I hope to fix it.

**Comment by danielkerr** [comment]
Yes because u have a 3rd party extension that does not have the required method

**Comment by danielkerr** [comment]
i also changed 

```
$method_data = [];

if ($status) {
	$method_data = [
		'code'       => 'bank_transfer',
		'title'      => $this->language->get('heading_title'),
		'sort_order' => $this->config->get('payment_bank_transfer_sort_order')
	];
}
```
to
```		
$method_data = [];

if ($status) {
	$option_data['bank_transfer'] = [
		'code' => 'bank_transfer.bank_transfer',
		'name' => $this->language->get('heading_title')
	];

	$method_data = [
		'code'       => 'bank_transfer',
		'name'       => $this->language->get('heading_title'),
		'option'     => $option_data,
		'sort_order' => $this->config->get('payment_bank_transfer_sort_order')
	];
}
```

**Comment by polcape** [comment]
Yes, I saw it and I changed but I can't get PayPal working.

I hope in developer fix.

Thanks

**Comment by danielkerr** [comment]
also change name from title

**Comment by polcape** [comment]
Ok, where is this name?

**Comment by danielkerr** [comment]
I mean I renamed title to name

**Comment by cgcmart** [comment]
@danielkerr checkout is still not working!
Object { error: 'No Shipping options are available. Please <a href="https://cgcmart.com/en-gb/contact">contact us</a> for assistance!' }
​
error: 'No Shipping options are available. Please <a href="https://cgcmart.com/en-gb/contact">contact us</a> for assistance!'
​
Object { error: 'No Shipping options are available. Please <a href="https://cgcmart.com/en-gb/contact">contact us</a> for assistance!' }
​
error: 'No Shipping options are available. Please <a href="https://cgcmart.com/en-gb/contact">contact us</a> for assistance!'
​
<prototype>: Object { … }
​​
__defineGetter__: function __defineGetter__()
​​​
length: 2
​​​
name: "__defineGetter__"
​​​
<prototype>: function ()
​​
__defineSetter__: function __defineSetter__()
​​​
length: 2
​​​
name: "__defineSetter__"
​​​
<prototype>: function ()
​​
__lookupGetter__: function __lookupGetter__()
​​​
length: 1
​​​
name: "__lookupGetter__"
​​​
<prototype>: function ()
​​
__lookupSetter__: function __lookupSetter__()
​​
__proto__: 
​​
constructor: function Object()
​​
hasOwnProperty: function hasOwnProperty()
​​
isPrototypeOf: function isPrototypeOf()
​​
propertyIsEnumerable: function propertyIsEnumerable()
​​
toLocaleString: function toLocaleString()
​​
toString: function toString()
​​
valueOf: function valueOf()
​​
<get __proto__()>: function __proto__()
​​
<set __proto__()>: function __proto__()
checkout:837:25
![checkour_error_20230422](https://user-images.githubusercontent.com/14033183/233798437-753edca6-0c31-4e8e-8bb5-6df00e7df11e.jpg)

**Comment by danielkerr** [comment]
> @danielkerr checkout is still not working! Object { error: 'No Shipping options are available. Please [contact us](https://cgcmart.com/en-gb/contact) for assistance!' }​error: 'No Shipping options are available. Please [contact us](https://cgcmart.com/en-gb/contact) for assistance!'​Object { error: 'No Shipping options are available. Please [contact us](https://cgcmart.com/en-gb/contact) for assistance!' }​error: 'No Shipping options are available. Please [contact us](https://cgcmart.com/en-gb/contact) for assistance!'​: Object { … }​​**defineGetter**: function **defineGetter**()​​​length: 2​​​name: "**defineGetter**"​​​: function ()​​**defineSetter**: function **defineSetter**()​​​length: 2​​​name: "**defineSetter**"​​​: function ()​​**lookupGetter**: function **lookupGetter**()​​​length: 1​​​name: "**lookupGetter**"​​​: function ()​​**lookupSetter**: function **lookupSetter**()​​**proto**:​​constructor: function Object()​​hasOwnProperty: function hasOwnProperty()​​isPrototypeOf: function isPrototypeOf()​​propertyIsEnumerable: function propertyIsEnumerable()​​toLocaleString: function toLocaleString()​​toString: function toString()​​valueOf: function valueOf()​​<get **proto**()>: function **proto**()​​<set **proto**()>: function **proto**() checkout:837:25 ![checkour_error_20230422](https://user-images.githubusercontent.com/14033183/233798437-753edca6-0c31-4e8e-8bb5-6df00e7df11e.jpg)

Maybe u need to enable a shipping method

**Comment by cgcmart** [comment]
@danielkerr both flat rate an free shipping are enabled. But the checkout page errors are the same, that looks like session_token issues.
You see the checkout page url does not contain token code.
Everyday there are a lot of error logs all in controller account files, #12209 .
