### ISSUE TITLE
I can't run atocomplete when i edit products in admin mode in opencart, when I type into the autocomplete box nothing happend

### ISSUE THREAD

**Issue by miriutza** [opencart/opencart#12189]
**What version of OpenCart are you reporting this for?** Opencart 3.0.3.8.

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect? editing products (in link tab-> manufacturers, categories, filters, recurring)

**To Reproduce**
1. Login to 'admin' in opencart 3.0.3.8.
2. Click on 'Catalog'->Products->Choose a product->Edit product->try to use autocomplete for fields manufacturers, categories, filters, recurring
4. See error ->
Uncaught SyntaxError: Invalid or unexpected token
jquery-2.1.1.min.js:4 Failed to load resource: the server responded with a status of 404 (Not Found)
send @ jquery-2.1.1.min.js:4
index.php:1 Uncaught SyntaxError: Unexpected token '<'
at eval ()
at Function.globalEval (jquery-2.1.1.min.js:2:2536)
at text script (jquery-2.1.1.min.js:4:15256)
at vc (jquery-2.1.1.min.js:4:7381)
at x (jquery-2.1.1.min.js:4:10802)
at XMLHttpRequest. (jquery-2.1.1.min.js:4:14767)
at Object.send (jquery-2.1.1.min.js:4:14955)
at Function.ajax (jquery-2.1.1.min.js:4:10579)
at n._evalUrl (jquery-2.1.1.min.js:4:11799)
at n.fn.init.domManip (jquery-2.1.1.min.js:3:17145)

**Expected behavior**
-> the autocomplete must show what categories, filter and manufacturer to choose when you type 2 or 3 letters in that field...

**Screenshots / Screen recordings**

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? ->deployed to a webserver with webuzo
 - Operating system - Centos v7.9
 - PHP version -> PHP 7.3. and i try also on PHP 8.0
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] -> Edge and Chrome

**Additional context**

**Comment by mhcwebdesign** [comment]
Try the 3.0.x.x_Maintenance release, where it works fine.

**Comment by miriutza** [comment]
Hello,

I can renounce on actual install, i have found a solution how to fix that opencart bug.
Thank You!

**Comment by miriutza** [comment]
sorry.. i must found a solution for that opencart bug.
