### ISSUE TITLE
Opencart 4.0.1.1 checkout does not complete

### ISSUE THREAD

**Issue by timconsidine** [opencart/opencart#12193]
**What version of OpenCart are you reporting this for?**
4.0.1.1
out of the box installation with demo data
only change was to add mail settings

**Describe the bug**
guest checkout
1 product **without** subscription plan
populate guest details
press continue
chose shipping and payment options (using default settings from installation)
clicking confirm - nothing happens

**To Reproduce**
1. Go to checkout , guest, after adding in stock product
2. Click on confirm
3. nothing happens
browser console shows 
```
<b>Warning</b>: Undefined property: 
Opencart\System\Library\DB::$row in <b>/app/data/public/catalog/model/checkout/subscription.php</b> on line <b>101</b>
<b>TypeError</b>: Opencart\Catalog\Model\Checkout\Subscription::getSubscriptionByOrderProductId(): 
Return value must be of type array, null returned in <b>/app/data/public/catalog/model/checkout/subscription.php</b> on line <b>101</b>
```

**NB : product has no subscription - but console references subscription**

**Expected behavior**
Checkout should complete

**Server / Test environment (please complete the following information):**
 - Deployed to a web server with LAMP stack
 - ubuntu 20.04
 - PHP version 8
 - Apache version
 - Safari firefox brave
 - latest versions

**Comment by danielkerr** [comment]
dont use subscription

**Comment by timconsidine** [comment]
> dont use subscription

because they don't work ?
or you mean don't use a product with a subscription ?
bit more clarity would be helpful 

As per original report, checkout does not work because it believes there is a subscription on a product.
Even when there isn't one.
**This is a bug, plain and simple.**

Tried an installation where I cleaned out all data and used my own.
The problem happened
Tried a clean installation with not changes other than setting the mail server
You would kinda expect that to work, wouldn't you ?
But no.  It doesn't.
**Default install does not work.**

Please take this seriously, just close with some cryptic comment.

**Comment by mhcwebdesign** [comment]
I think Daniel is still working on the subscription issues in the master branch.

Also, try the master branch, not 4.0.1.1, to see whether known bugs have been fixed or not.

**Comment by timconsidine** [comment]
Thank you, that's a lot more helpful 👍 
Given that opencart in 4.0.1.1 is essentially fundamentally broken, I hope it gets sorted soon.
And release page should have some kind of warning about this IMHO.

**Comment by danielkerr** [comment]
the subscription system is broken but should work if the product does not have sucbscrition

**Comment by timconsidine** [comment]
Yeah ... but that is what I am trying to report to you.
**Products without subscription attached generate an error in the checkout.**
Empty array - see message as first reported.

I don't know how I can say it any more clearly.
