### ISSUE TITLE
Cannot add categoeis to product

### ISSUE THREAD

**Issue by guymass** [opencart/opencart#12191]
I have a new opencart installation and while trying to create new sub categories it seems to not want to save and present a sub category. As well when I create a new product and want to add its category it will not save my selection even though the category appears in the list. All other fields are saved just fine, my only issue is with creating sub categories and add them to my products.

I don't see any error in logs. I can only add that  I am trying to use the btcpay server plugin as the main  currency on my site. Other than that everything seems to work just fine, so I don't even know where to start looking.

* Could be something wrong with the autocomplete function, just a thought.

**Comment by danielkerr** [comment]
already fixed in master. will release as soon as i finish the subscription issues
