### ISSUE TITLE
Install step 2 validation don`t recognize `session.auto_start="Off"` option

### ISSUE THREAD

**Issue by SimonLitt** [opencart/opencart#12198]
Install step 2 validation don't recognize 'session.auto_start="Off"' option.
When conducting validation, there should be such a code:
```
if (ini_get('session.auto_start') && ini_get('session.auto_start') != 'Off') {
	$this->error['warning'] = $this->language->get('error_session');
}
```

**Comment by danielkerr** [comment]
version of php?

**Comment by SimonLitt** [comment]
php 7.4.33 for the OC 3.0.3.8 installation
and
php 8.2.3 for the OC 4.0.1.1 installation

**Comment by danielkerr** [comment]
it must be down to ur php configuration on ur host. i have not heard any one else complain of this. n o default configuration would do this.
