### ISSUE TITLE
BTCPAY Extension currency error

### ISSUE THREAD

**Issue by guymass** [opencart/opencart#12192]
I am not sure if this issue goes here, I couldn't fine anywhere else to ask about this issue. I have installed the BTCPAY server extension to my OpenCart 4 site and set the currency to be bitcoin, however when I try to save it I get the following error:

2023-02-26 17:44:37 - DivisionByZeroError:  Division by zero
File: /var/www/html/opencart/extension/opencart/admin/controller/currency/ecb.php
Line: 103

This is how I set my currency for bit coin:

![Screen Shot 5783-06-05 at 19 21 06](https://user-images.githubusercontent.com/58882903/221431513-29f3992a-626c-439e-86a7-97b92d18b73f.jpg)

So not sure where the issue lays, probably with the extension I guess, so maybe someone here can help me understand how to fix that. 

Much thanks for all the hard work!

**Comment by guymass** [comment]
It seems there is not ISO currency code for Bitcoin, maybe that is the problem. How can I overcome this problem so that my opencart will use my BTCPAY server store and display prices on product in bitcoin?

**Comment by danielkerr** [comment]
DivisionByZeroError normally means u need to put something in value

**Comment by guymass** [comment]
would that be for example the value of the exchange rate between USD and BTC?

**Comment by guymass** [comment]
Sorry I didn't notice because I thought it was a repeating error but this is the complete error log:

2023-02-27 01:10:30 - PHP Warning: Undefined array key "btc"
File: /var/www/html/opencart/extension/opencart/admin/controller/currency/ecb.php
Line: 103

2023-02-27 01:10:30 - DivisionByZeroError:  Division by zero
File: /var/www/html/opencart/extension/opencart/admin/controller/currency/ecb.php
Line: 103

**Comment by danielkerr** [comment]
btc can not work with ecb. 
you would need to create an extension to get update exchange rates. 
im closing this because i just tested it with master branch and it works as it should with no errors
