### ISSUE TITLE
PHP MySQLi class don't contain `report_mode` property

### ISSUE THREAD

**Issue by SimonLitt** [opencart/opencart#12200]
It is property of the `mysqli_driver`, not `mysqli`.
https://www.php.net/manual/en/mysqli-driver.report-mode.php

In PHP 8.2, this causes a irremovable warning `Deprecated: Creation of dynamic property`.  Such errors in the OC engine classes can be removed by specifying the necessary properties in the class declaration, or by using the `AllowDynamicProperties` attribute. But here it's about the built-in class.

**Comment by SimonLitt** [comment]
```
index fa39be2f..4df13cf8 100644
@@ -9,10 +9,11 @@ class MySQLi {
 		}
 
 		try {
+			mysqli_report(MYSQLI_REPORT_ERROR);
+
 			$mysqli = @new \MySQLi($hostname, $username, $password, $database, $port);
 
 			$this->connection = $mysqli;
-			$this->connection->report_mode = MYSQLI_REPORT_ERROR;
 			$this->connection->set_charset('utf8mb4');
 			$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION'");
 		} catch (\mysqli_sql_exception $e) {

```

**Comment by mhcwebdesign** [comment]
Try the 3.0.x.x_Maintenance branch where I think it's already fixed.

**Comment by danielkerr** [comment]
already fixed in masster. trying to get a release ready asap
