### ISSUE TITLE
MAIL SMTP ERROR: SMTP Options are not being set

### ISSUE THREAD

**Issue by nexadomain** [opencart/opencart#12206]
**What version of OpenCart are you reporting this for?**
**Master**

**Describe the bug**
After choosing the **SMTP** _Mail Engine_ with desirable parameters, _**mails** are **not sent.**_
Routes responsible for sending mail, throwing an exception in response: `SMTP hostname required!`
While required parameters are correctly configured in `Setting->Mail`

**To Reproduce**
1. Go to **Admin->Setting -> Setting**
Route - `admin/index.php?route=setting/setting`
2. Click the **"Mail"** tab and enter SMTP settings.
I used the following Google SMTP to send mail from my Google Account.
```
Hostname: tls://smtp.gmail.com
Username: abcd...@gmail.com  // my email address
Password: 2ivc0v3e...  // Google Application Password created for this app
Port: 587
```
3. Go to the page URL that is sending emails, like 
```
Catalog->Forgotten Password
Catalog->Register Customer
Admin->Two Factor Security Page
etc
```
4. Keep eye on **Network** Tab
`Inspect (Ctrl+Shift+I) and go to Network Tab` and check responses from URLs for quick Debugging <br>
I have enabled 2-factor security for the admin user. It should have sent the security code to the administrator's email. But it is not sending. <br>
I checked the response from this URL `admin/index.php?route=common/authorize.send `, which is responsible for sending mail after _event_ call.
It is throwing an error.
`Exception: Error: SMTP hostname required! in C:\xampp\htdocs\opencart\system\library\mail\smtp.php on line 37`
5. See error

**Expected behavior**
_It should have sent email using the SMTP server, but it does not!_

**Additional context**
On further debugging, I found that the declared **options** parameters such as `smtp_hostname, smtp_username, smtp_password, smtp_port,` etc. are **not set.** 
It is using **default** array declared in the `SMTP` Class in `System/Library/Mail/SMTP.php`

For quick fix, I added parameters directly in protected  array `$default` in the file: `System/Library/Mail/SMTP.php` and it is **working.**

```
class Smtp {
	protected array $option = [];
	protected array $default = [
		'smtp_port'     => 25,
		'smtp_timeout'  => 5,
		'max_attempts'  => 3,
		'verp'          => false,

                // Parameters hardcoded for testing
		'smtp_hostname' => 'tls://smtp.gmail.com',
		'smtp_username' => 'abcd..yz@gmail.com', // GMAIL Email Address
		'smtp_password' => 'zcas...df', // Password Set for Opencart Application
		'smtp_port' => '587',
		'smtp_timeout' => 5
	];
.....
.....
}
```
_Above-hardcoded changes are sending the emails, but it is not the correct way._

**I hope Daniel and the Opencart Team resolve this issue as soon as possible.**

**Server / Test environment:**
 - Opencart version - **Master**
 - Local development? **Xampp**
 - PHP version - **8.1.6**
 - Apache version - **2.4.53 (Win64)**
 - Browser(s) tested with - Latest Chrome , Firefox

**Comment by danielkerr** [comment]
port should be 465

**Comment by nexadomain** [comment]
Thanks, Daniel, for your suggestion.

The problem is **not** with SSL or TLS parameters.
Both SSL and TLS's respective values are working fine.

The issue is that the **SMTP Engine is not accepting custom parameters**.

The defined _SMTP hostname, username, password,_ and _ports_ are not being used or set!

For Example
```
// upload/admin/controller/mail/customer.php  -> approve() function 
// Line # 81

$mail->parameter = $this->config->get('config_mail_parameter');
$mail->smtp_hostname = $this->config->get('config_mail_smtp_hostname');
$mail->smtp_username = $this->config->get('config_mail_smtp_username');
$mail->smtp_password = html_entity_decode($this->config->get('config_mail_smtp_password'), ENT_QUOTES, 'UTF-8');
$mail->smtp_port = $this->config->get('config_mail_smtp_port');
$mail->smtp_timeout = $this->config->get('config_mail_smtp_timeout');

// here these values are set in the controller class, but they are not being used or available in the SMTP engine class.
// SMTP Mail Engine File - upload/system/librarymail/smtp.php
```

**Comment by danielkerr** [comment]
Have u updated to the latest because I fixed this a few weeks ago
