### ISSUE TITLE
Error installation OC Branch 'Master'

### ISSUE THREAD

**Issue by rsuchovsky** [opencart/opencart#12205]
When installing on the subdomain, this error returns to me:

`Warning: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/nfsmnt/:/data/:/usr/php82/:/usr/bin/:/apachetmp:/tmp/:/var/tmp/:/dev/urandom:/usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/:/usr/local/bin/:/etc/ssl/certs/ca-certificates.crt) in /data/6/4/644308aa-ca42-485d-a59c-72a835797307/domainname/sub/oc4/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 91Twig\Error\LoaderError: The "/" directory does not exist ("/"). in /data/6/4/644308aa-ca42-485d-a59c-72a835797307/domainname/sub/oc4/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 92`

**Server**
 - web server
 - Ubuntu
 - 8.2 PHP version
 - OC branch master

**Comment by danielkerr** [comment]
i think u have not setup the server properly. u need a web user with proper permissions.

**Comment by rsuchovsky** [comment]
> i think u have not setup the server properly. u need a web user with proper permissions.

@danielkerr I use the web server of the largest web provider in Slovakia and Czech Republic.
Many people in Slovakia and the Czech Republic will have this problem.
Opencart version 2.x and 3.x did not have this problem.

**Comment by danielkerr** [comment]
Latest version does not work with 8.2. u need to wait for next release

**Comment by rsuchovsky** [comment]
> Latest version does not work with 8.2. u need to wait for next release

@danielkerr  There is a similar problem with PHP 8.0 and 8.1

**Comment by danielkerr** [comment]
It's not an opencart issue. They hosting has not setup the web server properly

https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths
