### ISSUE TITLE
Image can only be cleared once

### ISSUE THREAD

**Issue by SimonLitt** [opencart/opencart#12201]
Tested on demo server
https://demo.opencart.com/admin/index.php?route=catalog/category|form&user_token=923c9875e89be4f5bced2c98fcf251b1&category_id=33
`Catalog` - `Categories` - `Edit` or `Add new` - `Data` tab
The `Clear` button is pressed once.
After selecting a new image, the `Clear` button is still disabled.

**Comment by chongshengdz** [comment]
the demo is too old.
if you want to test, just install the master branch.

**Comment by danielkerr** [comment]
can not replicate
