### ISSUE TITLE
Cannot Complete Checkout - Subscription PHP Error

### ISSUE THREAD

**Issue by epetey88** [opencart/opencart#12203]
**Opencart Version:**
4.0.2.0 on Local Machine

When clicking "Confirm Order" nothing happens. There is no visible error on the front end. Error log and console show the following:

**Errors:**
PHP Warning:  Undefined property: Opencart\System\Library\DB::$rows in C:\Users\efpet\OneDrive\Desktop\OpenCart\catalog\model\checkout\subscription.php on line 21

TypeError:  Opencart\Catalog\Model\Checkout\Subscription::getSubscriptionByOrderProductId(): Return value must be of type int, null returned in C:\Users\efpet\OneDrive\Desktop\OpenCart\catalog\model\checkout\subscription.php on line 21

**Steps to reproduce the behavior:**
1. Log into an existing account
2. Browse the store
3. Add item to cart
4. Checkout using an existing address
5. Use store pickup shipping method
6. Use COD payment method
7. Click "Confirm Order"
8. Site does not reload or produce an error on front end

![console-error](https://user-images.githubusercontent.com/61068050/223604775-2d6bff30-aa66-4a26-96d6-132698d69afb.png)

**Server / Test environment:**
 - Local development
 - MAMP/Windows 10
 - PHP 8.0.1
 - Apache2.4.33
 - Tested on Chrome and Firefox

**Comment by condor2** [comment]
Because some files still use `model_checkout_subscription`.

**Comment by danielkerr** [comment]
work in progress
