### ISSUE TITLE
Cannot load Length Class and Weight Class

### ISSUE THREAD

**Issue by F03SD** [opencart/opencart#12207]
**Lastes master branch[beb64cd]**

**Describe the bug**
After fresh installation, moving into Settings -> Local and Length Class with Weight Class not displayble. 

On Localization settings its blank, data on DB exist.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/2673447/224235395-7a8c6484-e3cd-4bfd-91a2-8a2acedca1d3.png)

**Server / Test environment (please complete the following information):**
 - ArchLinux 6.2.2-arch1-1
 - PHP version: PHP 8.2.3 (cli) (built: Feb 15 2023 16:48:38) (NTS)
 - Apache version: 
  Server version: Apache/2.4.55 (Unix)
  Server built:   Jan 18 2023 19:03:59
[mariadb]
collation_server = utf8mb4_unicode_ci
character_set_server = utf8mb4
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
i dont know what u have done. maybe its a language issue
