### ISSUE TITLE
Issue while updating cart in frontend

### ISSUE THREAD

**Issue by GautamMKGarg** [opencart/opencart#12216]
**What version of OpenCart are you reporting this for?**
4.0.1.1

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
On Front end, if order is already created for a cart, and customer tries to change the product quantity on cart page. On payment page, it shows correct amount, but in actual, correct amount does not gets updated on existing order. When customer tries to make the payment, customer sees incorrect amount.

**To Reproduce**
1. Add 1 product in cart. (let's say amount is $10)
2. navigate to Checkout page.
3. Choose a payment gateway which supports hosted checkout. (issue occurs on other checkout also, just choose any payment gateway make sure order gets created at pending after clicking confirm button)
4. Click on Confirm button. Customer gets redirected to payment gateway page. Order gets created with $10.
5. At this point customer is not making the payment. He opens store in new tab.
6. Go to cart page and update the quantity. Total amount updated to let's say $20.
7. Now again follow step 2 and 3.
8. Make payment for this new cart.
9. Issue here, old amount is visible on payment gateway page and admin panel for this order. (Either new order should get created or old order should get updated. none of these are happening).

**Expected behavior**
If cart items updated after order is already created. Either create new order, or update exciting order. In version 3 of opencart, it was working fine.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
can not replicate
