### ISSUE TITLE
Issue with Extension installer

### ISSUE THREAD

**Issue by GautamMKGarg** [opencart/opencart#12215]
**What version of OpenCart are you reporting this for?**
4.0.1.1

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
If someone tries to install the extension which is not compatible with v4 of opencart and does not have install.json file, opencart gives the error. But after making the extension compatible with v4 and adding install.json file, if we retry to upload the correct extension, OpenCart gives error that file already exists. OpenCart is neither automatically deleting incorrect version not it's allowing admin to delete from admin panel. We have navigate to filemanager and delete the old version from file manager.

**To Reproduce**
1. Take a plugin which is compatible with v4 of opencart on your pc
2. Create backup of this plugin in different folder, making sure that **name of zip file remains same**.
3. delete install.json from backup extension.
4. try to install backup plugin, you will get error that install.json missing.
5. Now try to install original plugin which has install.json file, make sure name of zip file of original and backup should be same. You will get error that file already exists.
6. Admin gets confused where is the existing file, it's not visible on admin dashbaord. Admin has to delete from filemanager in order to fix the issue.

**Expected behavior**
Alow to install the new plugin even if file already exists (if existing file was not compatible)

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
already reported

**Comment by GautamMKGarg** [comment]
@danielkerr and @nexadomain 

Thanks for looking at this. Description at https://github.com/opencart/opencart/issues/11673 is little different. Kindly double check if same code is causing the issue or not.
