### ISSUE TITLE
Wrong validation on custom_fields when creating new address - payment_address.php

### ISSUE THREAD

**Issue by RicardoCostaTW** [opencart/opencart#12217]
Version: 4.0.1.1 

**Describe the bug**
Wrong validation on custom_fields when creating new address.

**To Reproduce**
1 - create custome field with 'address' location
2 - make required
3 - save
4- start a new order
5- create a new payment address and save
 
 The result is `{"error":{"payment_custom_field_31":"Phone required!","payment_custom_field_32":"Vat required!"}}`

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/1208532/226687289-cfc177c8-460d-457f-a4b8-2991899c1baa.png)

The code is:
`$custom_fields = $this->model_account_custom_field->getCustomFields($this->customer->getGroupId());

			foreach ($custom_fields as $custom_field) {
				if ($custom_field['location'] == 'address') {
					if ($custom_field['required'] && empty($this->request->post['custom_field'][$custom_field['custom_field_id']])) {
						$json['error']['payment_custom_field_' . $custom_field['custom_field_id']] = sprintf($this->language->get('error_custom_field'), $custom_field['name']);
					} elseif (($custom_field['type'] == 'text') && !empty($custom_field['validation']) && !preg_match(html_entity_decode($custom_field['validation'], ENT_QUOTES, 'UTF-8'), $this->request->post['custom_field'][$custom_field['custom_field_id']])) {
						$json['error']['payment_custom_field_' . $custom_field['custom_field_id']] = sprintf($this->language->get('error_regex'), $custom_field['name']);
					}
				}
			}`

**Comment by danielkerr** [comment]
not sure who put that fucking code there. it was working at some point.
