### ISSUE TITLE
Order Failing Due To Error in Order.php File

### ISSUE THREAD

**Issue by epetey88** [opencart/opencart#12222]
**Opencart Version:**
4.0.2.0 on Local Machine

When clicking "Confirm Order" nothing happens. There is no visible error on the front end. Error log and console show the following:

**Errors:**

```
SyntaxError: Unexpected token '<', "<b>Warning"... is not valid JSON
OK
<b>Warning</b>: Attempt to read property "row" on bool in <b>upload\catalog\model\checkout\order.php</b> on line <b>207</b><b>TypeError</b>: Opencart\Catalog\Model\Checkout\Order::getSubscription(): Return value must be of type array, null returned in <b>upload\catalog\model\checkout\order.php</b> on line <b>207</b>
```

**Steps to reproduce the behavior:**

- Log into an existing account
- Browse the store
- Add item to cart
- Checkout using an existing address
- Use store pickup shipping method
- Use COD payment method
- Click "Confirm Order"
- Site does not reload or produce an error on front end

**Server / Test environment:**

Local development
MAMP/Windows 10
PHP 8.0.1
Apache2.4.33
Tested on Chrome and Firefox

**Comment by cgcmart** [comment]
`return $query->rows;`
