### ISSUE TITLE
Error on Fresh Install Opencart 4.0.1.1

### ISSUE THREAD

**Issue by 8ternity** [opencart/opencart#12220]
When i try to install Opencart 4.0.1.1 i get this error message :

`Warning: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/var/www/vhosts/******.com/:/tmp/) in /var/www/vhosts/*****.com/centre.*****.com/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 91Twig\Error\LoaderError: The "/" directory does not exist ("/"). in /var/www/vhosts/*****.com/centre.*****.com/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 92`

I change to 777 for each config.php file, samething. Its a fresh install.

Thanks.

**Comment by danielkerr** [comment]
jesus this is down to ur hosting company. contact them ask them to fix the permissions for the web user
