### ISSUE TITLE
Checkout page does not pass data regarding shipping to payment module

### ISSUE THREAD

**Issue by KiaEsh** [opencart/opencart#12234]
Using OpenCart 3.0.x.x_Maintenance and payment module Bambora. Checkout page does not pass shipping data into that payment module. The payment module gives possibilities to customer to pay via payment card and invoice. Payment via card works, but invoice doesn't work because it requests order line regarding shipping (shipping name and cost). Checkout page passes product price and total amount. Amounts in order lines, which are requesting to capture in the sessionlog, are not the same as the passing total amount. 

It seems like data regarding shipping is not passing. 

Expected behavior:
Shipping data (name, amount) must be passed to the payment module, so you can see shipping name and amount as an order line when the payment module comes up.  

Screenshots:
![checkout-selected-shipping](https://user-images.githubusercontent.com/130162205/230734320-7c5aabbd-9afe-410b-9935-5443627a97b7.jpg)

![checkout-confirm](https://user-images.githubusercontent.com/130162205/230734330-d8a5f1ef-daef-454b-af3b-f4d5f5cf2e75.jpg)

![image](https://user-images.githubusercontent.com/130162205/230734261-be1d2476-c336-40fc-82ba-e28184d545da.png)

**Comment by danielkerr** [comment]
this is a 3rd party extension. i think u need to contact the extension developer.
