### ISSUE TITLE
Extension name containing "after" will cause errors when installing

### ISSUE THREAD

**Issue by yao-tx** [opencart/opencart#12233]
**What version of OpenCart are you reporting this for?**
OpenCart 4.0.1.1

**Describe the bug**
If the extension name contains the word "after", there will be an error when you click on "Install" at Extensions >> Modules. Error returned below:

`ArgumentCountError:  Too few arguments to function Opencart\Admin\Controller\Event\Language::after(), 2 passed and exactly 3 expected`

**To Reproduce**
1. Upload an extension that has the word "after" in the extension name
2. Go to Extensions >> Modules and click on "Install"
3. See error

**Expected behavior**
The word "after" should not cause errors and should not be a reserved keyword as well.

**Screenshots / Screen recordings**
nil

**Server / Test environment:**
 - Deployed to web server
 - CentOS
 - PHP 8

**Additional context**
Renaming the extension to exclude the word "after" is not an option.

**Comment by mhcwebdesign** [comment]
Please test it again with the current master branch, and then let us know whether this issue still exists.
