### ISSUE TITLE
Opencart 4.1 Checkout page Bug

### ISSUE THREAD

**Issue by gjordanra** [opencart/opencart#12247]
Opencart 4.1

Checkout page
After entering your shipping address and shipping method, the payment method dropdowns don't refresh and autofill the paymetn methods.  Have to reload the page before it works correctly, then the payment button activated.

**To Reproduce**
1. Go to checkout after adding a product
2.Follow the normal flow, select your shipping adress and shipping method

**Expected behavior**
paymeth method retrieved and select field autofilled, continue button activated

**Server / Test environment (please complete the following information):**
 - Local development , Wamp server 6.4
 - Windows 10
 - PHP version 8.0.13
 - Apache version 2.4.51
 - Chrome last version

**Comment by danielkerr** [comment]
fixed in latest. will launch asap

**Comment by gjordanra** [comment]
@danielkerr thanks, hope it will work soon
