### ISSUE TITLE
Session data and cart missing after redirect on Opencart 4.1

### ISSUE THREAD

**Issue by gjordanra** [opencart/opencart#12248]
Opencart 4.1

Hi, previously on Opencart 3.8 when a payment extension redirect to another website to process the payment and then redirect back to Opencart, the session data and cart could be accessed from the extension controller, also the user is keeped logged in.
Now in new version 4.1 with the same extension and logic, when the extension redirect to process the payment (processresponse) and then return control to Opencart the session data is missing, also the customer logged out and the cart no longer accessible. I have tried some options like adding the user_token and customer_token but not working as inteded as the customer is logged out, here is the code where the payment processing website is called, so if anyone has idea on how I should call the redirect to keep the user logged in it will help me a lot.

```
$data["RETURN_URL"] = bin2hex($this->url->link('extension/paymentextension/payment/paymentextension|processresponse',
            'user_token=' . $this->session->data['customer_token'] . '&type=payment', true));
$result = $this->model_extension_paymentextension_payment_paymentextension->curl($this->model_extension_paymentextension_payment_paymentextension->getURL(), http_build_query($data, '', '&'));
$this->response->redirect($result['data']['url']);

```

**To Reproduce**

**Expected behavior**
Session not expired after getting control back by Opencart, user not logged out inmediatelly

Server / Test environment (please complete the following information):

    Local development , Wamp server 6.4
    Windows 10
    PHP version 8.0.13
    Apache version 2.4.51
    Chrome last version

**Comment by ADDCreative** [comment]
Could be that SameSite is set to Strict by default.

https://github.com/opencart/opencart/blob/f31535a13a1d973965c669ac2e797efb48f128b1/upload/system/config/default.php#L46

**Comment by danielkerr** [comment]
its updated security.

**Comment by gjordanra** [comment]
Hi. I changed the options in default.php as this, yet the user is still logged out after redirect
![Screenshot_17](https://user-images.githubusercontent.com/4700976/232496618-676f4aa2-d983-4a24-a261-50bc1ffc9fe4.jpg)

**Comment by ADDCreative** [comment]
@gjordanra You need to change it in your settings (under the server tab), Use Lax for a GET and None for a POST.

**Comment by gjordanra** [comment]
Hi, I did that also after reading your reply, no luck yet
