### ISSUE TITLE
Query error: "Foreign key constraint is incorrectly formed"

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#12241]
https://github.com/opencart/opencart/blob/771cfb287caed3dec6d3526e69d5859189da025a/upload/system/helper/db_schema.php#L3941 in the last comment
inconsistent with L6456
`'type' => 'varchar(128)',`

L4016 in the last comment
`'type' => 'text',`
inconsistent with L6471
`'type' => 'varchar(128)',`

**Comment by danielkerr** [comment]
im not sure its fixed or not
