### ISSUE TITLE
[4.0.2.0] Filemanager error because of index.html

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12259]
**What version of OpenCart are you reporting this for?**
4.0.2.0 
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Error message in error log
2023-04-17 20:24:36 - PHP Notice: getimagesize(): Error reading from /home/.../public_html/opencart/master/image/catalog/index.html!
File: /home/.../public_html/opencart/master/admin0/model/tool/image.php
Line: 15

and on the image manager page
![image](https://user-images.githubusercontent.com/10166095/232608527-16c21b39-4ed8-42a7-90d1-e4b708dff6f5.png)

also the images in a folder are 2 times present in the file manager.

**To Reproduce**
Open a category
goto tab data
edit image

**Expected behavior**

**Screenshots / Screen recordings**
present

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Server
 - Operating system Linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22]  112.0

**Additional context**

**Comment by pemaier** [comment]
It's getting a funny customer talk.
- Customer: Can you upgrade my shop
- I tell him OpenCart is so new that your current host is not usable.... it's to old.
- Customer: Ok where I should go for hosting
- You have to find a host with a new OS
- Customer: You can help me?
- I have to say no  because I can't see from outside which OS the hoster is using.
- Customer: And now what can I do.
- ??? Maybe wait till OpenCart is old enough to work on sharing hosting platforms again.

This will be the conversation with 90% of my customers. The other 10% are going to Shopify.

**Comment by ADDCreative** [comment]
See this too on some hosting. Lots of hosts are still using an OS like CloudLinux OS 7, which are not end of life yet.

**Comment by danielkerr** [comment]
so does cloudos not use go0b brace and just returns all results.

**Comment by danielkerr** [comment]
says this on PHP web site:

Note: This function isn't available on some systems (e.g. old Sun OS). i really dont see why i need to fuck around with old functions because of some shit os only a few companies use.

**Comment by pemaier** [comment]
The error is solved but the double presentation of images is not solved.

@Daniel - I like the changes you was doing (subscription, button design ...) the last time. Good job !!!

**Comment by ADDCreative** [comment]
@danielkerr It does support GLOB_BRACE, The issue is ```catalog/*/``` matches files as well as directories. You probably need to use ```/.``` as the first item inside the braces.
```php
$paths = glob($directory . $filter_name . '*{/.,.ico,.jpg,.jpeg,.png,.gif,.webp,.JPG,.JPEG,.PNG,.GIF}', GLOB_BRACE);
```
Should work on all systems.
