### ISSUE TITLE
Extension code and file name

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#12266]
https://github.com/opencart/opencart/pull/9710#issue-920219155

https://github.com/opencart/opencart/issues/11316#issuecomment-1157542884

![image](https://user-images.githubusercontent.com/6297070/232805398-fe29f26f-3acd-4596-859c-43c5f4fa7f0d.png)

WHYYYY????

![image](https://user-images.githubusercontent.com/6297070/232809113-0f8bf656-fb05-4e46-8699-cc2bb5cc640b.png)

**Comment by mhcwebdesign** [comment]
There are indeed a number of flaws with the way OpenCart 4 handles extensions IMHO. I am thinking about releasing a plugin manager for OpenCart which will address those common issues, and which would also correct issues with the way OpenCart 4 doesn't abide by common namespace usage standards.

**Comment by danielkerr** [comment]
its the extension devs fault. under download name they should put version number.  msg the developer.
