### ISSUE TITLE
Error order email

### ISSUE THREAD

**Issue by RicardoCostaTW** [opencart/opencart#12269]
Version: 4.0.2.0

**Describe the bug**
Mail of the purshase dont have the correct information about payment method and shipping method

**To Reproduce**
-> Make any order

File: catalog/controller/mail/order.php

Current Code:
$data['payment_method'] = $order_info['payment_method'];
$data['shipping_method'] = $order_info['shipping_method'];

Maybe:
$data['payment_method'] = $order_info['payment_method']['name'];
$data['shipping_method'] = $order_info['shipping_method']['name'];;

**Server / Test environment (please complete the following information):**
 - Deployed
 - Mac OS
 - PHP 8.1
 - Apache
 
 
![image](https://user-images.githubusercontent.com/1208532/232838321-e620a153-d0ff-4df6-bad2-112a276e710a.png)

**Comment by danielkerr** [comment]
clear ur template cache

**Comment by RicardoCostaTW** [comment]
ok @danielkerr . But it still a bug. Please analyze for yourself.

**Comment by RicardoCostaTW** [comment]
I cleared the cache and other problem appear so i updated the following lines:

$data['payment_method'] = $order_info['payment_method']['name'];
$data['shipping_method'] = $order_info['shipping_method']['name'];

**Comment by mhcwebdesign** [comment]
I can confirm this error, see https://github.com/opencart/opencart/issues/12271 . I'll take a closer look at it tomorrow, should be easy enough to fix.
