### ISSUE TITLE
[OC 4.0.2.0] Bug in order_invoice.twig

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#12271]
**What version of OpenCart are you reporting this for?**
OpenCart 4.0.2.0

**Describe the bug**
Create new order, e.g. for the HTC Touch item, on the frontend. OpenCart then sends an order confirmation mail to the customer, and it uses the catalog/view/template/mail/order_invoice.twig for this.

However, the order_invoice.twig file has bugs in lines 35 to 39:

```
          <b>{{ text_payment_method }}</b> {{ payment_method }}
          <br/>
          {% if shipping_method %} <b>{{ text_shipping_method }}</b> {{ shipping_method }}
          {% endif %}</td>

```

The variables for **{{ payment_method }}** and **{{ shipping_method }}** are json arrays, so Twig would complain about an 'Warning: Array to string conversion' for these variables! I suggest to fix the corresponding controller at catalog/controller/mail/order.php for the method 'add'.

**Server / Test environment (please complete the following information):**
 - Linux Mint 20.3
 - PHP version 8.2
 - Apache version: Apache/2.4.41 (Ubuntu) 
 - Browser(s) tested with: Firefox 112.0 (64-bit)

**Comment by RicardoCostaTW** [comment]
Maybe is related to https://github.com/opencart/opencart/issues/12269

**Comment by RicardoCostaTW** [comment]
I think that payment_method.name and shipping_method.name should solve that bug.

**Comment by mhcwebdesign** [comment]
I think you are right. Though in the database it's stored as a json array, somewhere it converts it into a regular array before rendering the mail/order_invoice.twig template.
