### ISSUE TITLE
[OC 4.0.2.1] Missing variables for account/subscription_info.twig

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#12273]
**What version of OpenCart are you reporting this for?**
OC 4.0.2.1, OC 4.0.2.0, and master branch

**Describe the bug**
I haven't test it yet. But just looking at the code, it looks like the **catalog/template/account/subscription_info.twig** uses various unpopulated variables such as
{{ payment_method }}
{{ product_quantity }}
{{ order_id }}
{{ product }}
{{ order }}
{{ transactions }}
{{ product_name }}
{{ reference }}
etc.

These variables don't appear to be set in the corresponding controller at **catalog/controller/account/subscription.php** in method **info**.

Is this still work in progress? Or is it a bug?

**Comment by danielkerr** [comment]
dont use subscription its still being worked on. i needed to get as release out. as long as checkout works with normal payments its fine.
