### ISSUE TITLE
Undefined property: Proxy::getSubscriptions

### ISSUE THREAD

**Issue by RicardoCostaTW** [opencart/opencart#12279]
Version 4.0.2.1

**Describe the bug**
Exception: <b>Notice</b>: Undefined property: Proxy::getSubscriptions in <b>/catalog/controller/cron/subscription.php</b> on line <b>23</b> in /home/admin/lojakpf.lixovirtual.com/system/engine/proxy.php on line 83

The method getSubscriptions() not exists in model checkout subscription.

**To Reproduce**
- Appear in error.log

**Expected behavior**

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/1208532/233323121-4ddc3fe5-afd0-4f09-a054-198c9d9ba6fc.png)

**Server / Test environment (please complete the following information):**
 - Deployed
 - Mac OS
 - PHP 8.1
 - Apach
 - Chrome

**Comment by mhcwebdesign** [comment]
I think Daniel is still working on the subscription feature, hopefully it will become available again in a future release. See also https://github.com/opencart/opencart/issues/12273#issuecomment-1515378027

**Comment by RicardoCostaTW** [comment]
Ok! I thought the same, but the notices were conflicting with my API.
