### ISSUE TITLE
[OC 4.0.2.1] Admin order editor bug: Lost payment method

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#12275]
**What version of OpenCart are you reporting this for?**
OC 4.0.2.1

**Describe the bug**
Getting this when trying to view an order:
```
Warning: Trying to access array offset on value of type null in /htdocs/opencart-4-0-2-1/admin/controller/sale/order.php on line 999
Warning: Trying to access array offset on value of type null in /htdocs/opencart-4-0-2-1/admin/controller/sale/order.php on line 1005
Warning: Trying to access array offset on value of type null in /htdocs/opencart-4-0-2-1/admin/controller/sale/order.php on line 1135
TypeError: Opencart\Admin\Model\Setting\Extension::getExtensionByCode(): Argument #2 ($code) must be of type string, null given in /htdocs/opencart-4-0-2-1/admin/model/setting/extension.php on line 16

```

**To Reproduce**
Add an order for e.g. the 'HTC Touch' product on the frontend

In the admin backend, view order and click on **Confirm**, without changing anything.

This causes the all of the payment_method and payment info to get lost for the order.

Then exist view order

Then try to go back into view order, we now get above mentioned error because of the missing payment details

**Server / Test environment (please complete the following information):**
 - Operating system Linux Mint 20.3
 - PHP version: 8.2
 - Apache version Apache/2.4.41 (Ubuntu) 
 - Browser(s) tested with: Firefox 112.0 (64-bit)

**Comment by danielkerr** [comment]
did u run through the upgrade script because it should convert to json

**Comment by mhcwebdesign** [comment]
No, it was a fresh install.

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart/issues/12298#issuecomment-1528793143

**Comment by ahmed-fad** [comment]
see this:
[https://github.com/opencart/opencart/issues/12298#issuecomment-1555045721](https://github.com/opencart/opencart/issues/12298#issuecomment-1555045721)

**Comment by danielkerr** [comment]
already fixed in master
