### ISSUE TITLE
[OC 4.0.2.1] Wrong variables for mail/order_invoice.twig

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#12274]
**What version of OpenCart are you reporting this for?**
OC 4.0.2.1

**Describe the bug**
The template at **catalog/view/template/mail/order_invoice.twig** uses the variables

{{ payment_method }} and {{ shipping_method }}

which are passed from the controller catalog/controller/mail/order.php in method **add** as arrays. This causes the Twig rendering engine to come up with the errors

PHP Warning:  Array to string conversion

for the template lines 35 and 37.

There are 2 suggested fixes for this:

Either use {{ payment_method.name }} and {{ shipping_method.name }} in the template.

Or fix the controller, e.g. use something like this in lines 130 and 131:

```
		$data['payment_method'] = isset($order_info['payment_method']['name']) ? $order_info['payment_method']['name'] : '';
		$data['shipping_method'] = isset($order_info['shipping_method']['name']) ? $order_info['shipping_method']['name'] : '';
```

This issue was reported several times before, see e.g. https://github.com/opencart/opencart/issues/12271 or https://github.com/opencart/opencart/issues/12269

**Comment by RicardoCostaTW** [comment]
I honestly prefer the correction in the view... if we have all the information in the controller ...
