### ISSUE TITLE
[4.0.2.1] - config_language_id is discarded when saving store settings

### ISSUE THREAD

**Issue by julioccguimaraes** [opencart/opencart#12285]
**What version of OpenCart are you reporting this for?**
OC 4.0.2.1 - fresh install

**Describe the bug**
config_language_id is not saved in oc_setting table when store settings is saved
The result is that products, categories and other entities that need this variable are not displayed in the admin

**Expected behavior**
config_language_id stored in oc_setting table when store settings is saved

**Server / Test environment (please complete the following information):**
 - Web Server
 - Linux
 - PHP 8.1

**Comment by danielkerr** [comment]
im sure its saved but u might need to to change the language on the other side as the urls have language=en-gb.

**Comment by danielkerr** [comment]
im sure i got rid of cookies for language

**Comment by julioccguimaraes** [comment]
Yes, oc4 does not generate a language cookie, but it reads the value if it exists (generated by the oc3 store installed in the root .com/).
I'm just leaving this testimonial in case anyone else has this problem when trying to test the store on a subfolder of the main domain. The correct thing is to install on a subdomain.

**Comment by danielkerr** [comment]
closing as reported here
https://github.com/opencart/opencart/issues/12290
