### ISSUE TITLE
[master] Frontend Customer order history view - TypeError: Cannot access offset of type string on string

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12298]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
Customer view of sales history has an error.
TypeError: Cannot access offset of type string on string in /home/.../catalog/controller/account/order.php on line 193

**To Reproduce**
1. Login as customer
2. Click on 'View your order history'
3. Open an order

**Expected behavior**
to the the order.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system cloudlinux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 112.0.1

**Additional context**
I logged in over the admin customer login function.

**Comment by danielkerr** [comment]
u didnt run upgrade

**Comment by pemaier** [comment]
it was a new install 
and now I tested once again and here are my detailed steps.
- new install
- in Admin set mail and save settings
- goto customer an create new customer
- goto sales and make an order and confirm
- goto customer and use login to store function
- goto view your order history 
- order # 1 is visible and then click view ... error is visible

I recognized that in that way the customer has no address saved in his profile.

(Is it possible that I'm on a blacklist since ~6 month because I don't get your messages anymore?)

**Comment by TheCartpenter** [comment]
According to this error message, that would be showed for the right reasons with this scenario. catalog/model/account/order.php file pulls the ```payment_method``` field whether is JSON or not from the ```getOrder()``` method while line 193 of catalog/controller/account/order.php file seem to insist on pulling the ```name``` key from the array.

Therefore, if people whether needs to install a fresh version or upgrade their OC versions in the future, thermal operators should not be used in the models but rather insisted to use the array key names as ```payment_method['name']``` altogether with the use of JSON decode without using the thermal operator. The upgrade process should then have the need to convert the strings into an array from the database. 

Granted, the mount of orders will most likely cause these upgrades to fail to due the max post size and the delay servers will allow to complete the process on the browser regardless how increased the php.ini or .user.ini file will handle but using a thermal operator in the models while the controllers uses an insisted way to pull the data from an array won't really help to avoid that kind of error message in this case.

**Comment by pemaier** [comment]
Here is my [oc_order.sql.zip](https://github.com/opencart/opencart/files/11361128/oc_order.sql.zip) table to see the differences in the entries.

**Comment by TheCartpenter** [comment]
What way did you used to copy it?

**Comment by pemaier** [comment]
I copied direct in the sql db

**Comment by TheCartpenter** [comment]
I wonder if it's not related to this case: https://github.com/opencart/opencart-3/issues/162 . Could you confirm these steps to see if it resolves the issue?

**Comment by pemaier** [comment]
oh sorry I answer in the issue you wrote ...

**Comment by pemaier** [comment]
When I try to write the db string (addOrder in checkout/model/order.php) into the log I get the following situation:
1st - in the order I enter the payment address but I do not see it in the saved order
![image](https://user-images.githubusercontent.com/10166095/235431922-f8c64f14-991f-4271-9387-25f87c8adf6f.png)

2. I get the error as following: 
2023-05-01 08:50:24 - PHP Warning: Array to string conversion
File: /home/xxx/master.demo/cache/template/1b/1b651aff57ced7d35c794ff002ab2be3.php
Line: 146

3. In the mail I get:
4. Shipping Method: Warning: Array to string conversion in /home/xxx/master.demo/cache/template/1b/1b651aff57ced7d35c794ff002ab2be3.php on line 146Array

I hope it will help you.

**Comment by TheCartpenter** [comment]
> When I try to write the db string (addOrder in checkout/model/order.php) into the log I get the following situation: 1st - in the order I enter the payment address but I do not see it in the saved order ![image](https://user-images.githubusercontent.com/10166095/235431922-f8c64f14-991f-4271-9387-25f87c8adf6f.png)
> 
> 2. I get the error as following:
>    2023-05-01 08:50:24 - PHP Warning: Array to string conversion
>    File: /home/xxx/master.demo/cache/template/1b/1b651aff57ced7d35c794ff002ab2be3.php
>    Line: 146
> 3. In the mail I get:
> 4. Shipping Method: Warning: Array to string conversion in /home/xxx/master.demo/cache/template/1b/1b651aff57ced7d35c794ff002ab2be3.php on line 146Array
> 
> I hope it will help you.

In catalog/controller/mail/order.php file,

rename all instances of:

```$data['payment_method'] = $order_info['payment_method'];```

to:

```$data['payment_method'] = $order_info['payment_method']['name'];```

Do the same for the ```shipping_method``` lines. This should resolve the issue.

**Comment by pemaier** [comment]
That is the result ...
![image](https://user-images.githubusercontent.com/10166095/235525570-b98b9093-e7f2-46da-b167-ef696f8be061.png)

**Comment by TheCartpenter** [comment]
What's on your line 146 of the provided cache file from your screenshot?

**Comment by TheCartpenter** [comment]
Also, for order ID 7, what does it state in your shipping_method field from your PHPMyAdmin?
