### ISSUE TITLE
Admin order editor error display is incorrect

### ISSUE THREAD

**Issue by faheem5157** [opencart/opencart#12294]
**What version of OpenCart are you reporting this for?**
OpenCart4.0.2.1
**Describe the bug**
Add or edit any order without selecting products, payment address, shipping address, shipping method or payment method gives you 1 character error
What section does it affect?
Admin order editor
**To Reproduce**
1. Go to 'Admin->Sales->Order'
2. Click on 'Plus Button to add order'
3. Scroll down to 'Confirm Button and click it without selecting anything'

**Expected behavior**
It should display 1 line understandable error

**Screenshots / Screen recordings**
![Screenshot from 2023-04-27 11-00-02](https://user-images.githubusercontent.com/49372879/234774233-32bd5779-6029-4bdf-82c5-36935f52d9d8.png)

**Server / Test environment (please complete the following information):**
 - Local development
 - Ubuntu 22.04.2 LTS
 - PHP Version 8.0.25
 - Apache/2.4.54
 - Browser(s) tested with [Chrome, Firefox]
 - Version [111.0.5563.146 (Official Build) (64-bit), 103.0.1 (64-bit)]

**Comment by MarvinKlein1508** [comment]
Seems to be already fixed in master branch.
![image](https://github.com/opencart/opencart/assets/32510006/b1d773db-1ec1-44c3-a902-49b7fec7bfef)

**Comment by danielkerr** [comment]
i 5think fixed already
