### ISSUE TITLE
[4.0.2.1] Administration language doesn't change, always loading the English translation

### ISSUE THREAD

**Issue by AlexandraGkogka** [opencart/opencart#12290]
**What version of OpenCart are you reporting this for?**
4.0.2.1 Fresh install

**Describe the bug**
After installing and enabling a new language extension, the administration always displays the English language translation.

The administration language select dropdown (nav-language) changes the flag and sets the correct language cookie, on each language change, but the OpenCart translation always stays to English.

This issue occurs only in the administration.

**To Reproduce**
1. Install a new language extension.
2. In settings, select the new language as the default Language and Administration Language and save.
3. Logout, clear all cookies and login again to the  Administration.
4. The language translation is still English.
5. From language drop down menu, change the language and select the installed language.
6. The language menu selection changes to the new language, but the language translation is still English.

**Server / Test environment (please complete the following information):**
 - Cloud server
 - Operating system: Ubuntu 20.04
 - PHP version: 8.1, 8.2
 - Apache version: 2.4.55
 - Browser(s) tested with: Chrome, Firefox

**FIX Proposal**
Until a better solution is found, the language issue can be fixed by modifying this file:
admin/controller/startup/language.php

Replace this line:
$this->language->addPath('extension/' . $language_info['extension'], DIR_EXTENSION . $language_info['extension'] . '/admin/language/');

With this:
$language = new \Opencart\System\Library\Language($language_info['code']);
$this->registry->set('language', $language);
$language->addPath(DIR_EXTENSION . $language_info['extension'] . '/admin/language/');

**Comment by pemaier** [comment]
The upper solution is not working at all. Here a sample:
Go to order something as customer and go to sales and view the order.
![image](https://user-images.githubusercontent.com/10166095/234564840-7228c9d7-9167-44cc-ad9f-2ab37288ba12.png)
Till here all is ok BUT if you change the order language 
![image](https://user-images.githubusercontent.com/10166095/234565131-5069abc5-141e-49c3-8445-bd83e8deed76.png)
then you get this price view ...
![image](https://user-images.githubusercontent.com/10166095/234565350-899774ae-9d7e-4bf4-97f7-7c37947b8cf3.png)

**Comment by AlexandraGkogka** [comment]
The solution has been tested and works fine for setting the displayed language in all administration pages. As I said it is a working solution until something more solid comes out.

If it doesn't work for you, make sure you have installed a proper language extension for OC 4.0.2.1 with all language files being in the extension directory. Language extensions for 4.0.1.1 may not work properly, because of a change when calling language save method, from language_name|save to language_name.save in the language controller file.

The problem you mentioned in your example occurs specifically at the order info page when changing the order's language.

To fix the decimal_point issue,  in admin/model/setting/store.php line 141

Change this:
$language = new \Opencart\System\Library\Language($this->config->get('config_language'));

To this:
$language = new \Opencart\System\Library\Language($language_info['code']);

Please note that there may be other issues occurring in the order view / edit process, that are beyond the scope of the admin language change issue mentioned above.

**Comment by batumibiz** [comment]
The problem with the admin/controller/startup/language.php file has wider implications than those described above. Even if the system has only one language (clean Opencart installation), there are the following problems:
- System ->  Localisation -> Stock Statuses list is empty. Can't add anything...
- System ->  Localisation -> Order Statuses list is empty. Can't add anything...
- It is not possible to change and save the main system settings (System -> Settings).

At the same time, if you replace the admin/controller/startup/language.php file with the same one, but from version 4.0.1.1, then the problem with lists and settings (but not with languages ​​in general) is fixed.

**Comment by julioccguimaraes** [comment]
> The problem with the admin/controller/startup/language.php file has wider implications than those described above. Even if the system has only one language (clean Opencart installation), there are the following problems:
> 
> * System ->  Localisation -> Stock Statuses list is empty. Can't add anything...
> * System ->  Localisation -> Order Statuses list is empty. Can't add anything...
> * Also, all return statuses are not visible.
> * It is not possible to change and save the main system settings (System -> Settings).
> 
> At the same time, if you replace the admin/controller/startup/language.php file with the same one, but from version 4.0.1.1, then the problem with lists and settings (but not with languages ​​in general) is fixed.

https://github.com/opencart/opencart/issues/12285

**Comment by AlexandraGkogka** [comment]
> The problem with the admin/controller/startup/language.php file has wider implications than those described above. Even if the system has only one language (clean Opencart installation), there are the following problems:
> 
> * System ->  Localisation -> Stock Statuses list is empty. Can't add anything...
> * System ->  Localisation -> Order Statuses list is empty. Can't add anything...
> * Also, all return statuses are not visible.
> * It is not possible to change and save the main system settings (System -> Settings).

What you describe is not an OpenCart issue. With a proper language extension for OC 4.0.2.1, the tables that use language entries will be populated with the new language entries copied from the default language. 

The language extension, upon installation, calls the install() method witch in turn calls the model/localisation/language/addLanguage() method that creates those entries you're missing. Try using a proper language extension on a clean install.

**Comment by AlexandraGkogka** [comment]
> At the same time, if you replace the admin/controller/startup/language.php file with the same one, but from version 4.0.1.1, then the problem with lists and settings (but not with languages ​​in general) is fixed.

Yes, I've also tried that first, but I think the fix I mention above, has fewer issues than using the startup/language.php from version 4.0.1.1.

**Comment by batumibiz** [comment]
> What you describe is not an OpenCart issue.

You didn't read carefully what I wrote

> Even if the system has only one language (clean Opencart installation), there are the following problems

- To test, download and install clean OpenCart 4.0.2.1
- Do not install any languages, but immediately try to check what I wrote about.

**Comment by AlexandraGkogka** [comment]
> > Even if the system has only one language (clean Opencart installation), there are the following problems
> 
> * To test, download and install clean OpenCart 4.0.2.1, or the master branch on 04/27/2023
> * Do not install any languages, but immediately try to check what I wrote above.

@batumibiz Hello Oleg, I read carefully what you wrote. Works fine for me. 

On a 4.0.2.1 fresh install, right after installation at the administration, at pages System -> Localisation -> Stock Statuses,  System -> Localisation -> Order Statuses, System -> Localisation -> Returns -> Return Statuses db entries are visible and working as expected for me. I've tried it with cleared cookies and with different browser locales and looks good.

**Comment by batumibiz** [comment]
@AlexandraGkogka dear Alexandra, thanks for the answer.
I just did the following:
- i downloaded OpenCart 4.0.2.1 from the official website
- i did a clean installation
- immediately after installation, I checked the problems that I wrote about above, there are
- what am I doing wrong?

![screenshot-isoap-new-2023 04 28-21_01_57](https://user-images.githubusercontent.com/10770779/235212263-4579ce25-5887-451f-98e8-a046dc7ed202.png)
![screenshot-isoap-new-2023 04 28-21_05_26](https://user-images.githubusercontent.com/10770779/235212289-fd35d5ac-ab47-4663-a29b-235c807342e9.png)

**Comment by AlexandraGkogka** [comment]
> @AlexandraGkogka dear Alexandra, thanks for the answer. I just did the following:
> 
> * i downloaded OpenCart 4.0.2.1 from the official website
> * i did a clean installation
> * immediately after installation, I checked the problems that I wrote about above, **there are**
> * what am I doing wrong?

@batumibiz, Hello Oleg. There is no language selection menu in the images you've shown.
This could happen if there's a language cookie in your browser for a language other than English.
Try clearing your cookies and login again.

**Comment by octaviancernat** [comment]
@batumibiz @danielkerr 
Hi there. Got the same problem. 

This 
`        if (isset($this->request->cookie['language'])) {
            $code = (string)$this->request->cookie['language'];
        } else {
            $code = $this->config->get('language_code');
        }`
in /controller/startup/language.php

If the cookie language isn't English  you will get that.
So first install your language, clear cookies and check.

But this code should be changed as opencart doesn't have all the languages installed.

**Comment by gerasart** [comment]
have same problem opencart 4.0.2.1

**Comment by nourhamra** [comment]
> @AlexandraGkogka dear Alexandra, thanks for the answer. I just did the following:
> 
> * i downloaded OpenCart 4.0.2.1 from the official website
> * i did a clean installation
> * immediately after installation, I checked the problems that I wrote about above, **there are**
> * what am I doing wrong?
> 
> P.S. With version 4.0.1.1, these problems (which I wrote about above) do not exist.
> 
> ![screenshot-isoap-new-2023 04 28-21_01_57](https://user-images.githubusercontent.com/10770779/235212263-4579ce25-5887-451f-98e8-a046dc7ed202.png) ![screenshot-isoap-new-2023 04 28-21_05_26](https://user-images.githubusercontent.com/10770779/235212289-fd35d5ac-ab47-4663-a29b-235c807342e9.png)

 i had the same problem even with clean installation then i saw Daniel talked about cookies and yes it worked just clean your cookies properly it will work

**Comment by TugumeDaniel** [comment]
Thanks

**Comment by danielkerr** [comment]
languages need to be added like extensions are. i put an example language extension under system/storage/marketplace/oc_language_example.zip

install it. i have just tested this is working in fine and even added a file in the extension directory and it automatically overrides as default language.
