### ISSUE TITLE
Can't add product options because of quotes in translation

### ISSUE THREAD

**Issue by zkrx** [opencart/opencart#12293]
Basically the same issue as https://github.com/opencart/opencart/issues/6378

**What version of OpenCart are you reporting this for?**
4.0.1.1

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

I'm using a French translation on Opencart 4.0.1.1. Example from `admin/language/fr-fr/catalog/option.php`:

```
// Entrée
$_['entry_name'] = 'Nom de l\'option';
$_['entry_type'] = 'Type';
$_['entry_option_value'] = 'Nom de la valeur de l\'option';
$_['entry_image'] = 'Image';
$_['entry_sort_order'] = 'Trier l\'ordre';                              
```

As you can see, quotes are correctly escaped. Yet it's impossible to add an option:
`Uncaught SyntaxError: unexpected token: identifier`
On this line:
`    html += '      <input type="text" name="option_value[' + option_value_row + '][option_value_description][1][name]" value="" placeholder="Nom de la valeur de l'option" id="input-option-value-' + option_value_row + '-1" class="form-control"/>';`
(from `admin/view/template/catalog/option_form.twig`)

`Uncaught ReferenceError: addOptionValue is not defined`

Removing the quotes from the translation file (entry_option_value and entry_sort_order) and the problem is solved.

I can find the same issue being referenced on this forum nearly 10 years ago:
https://forum.opencart.com/viewtopic.php?t=137214

I wonder what other areas of the site are impacted.

**Comment by TheCartpenter** [comment]
The solution has already been posted in the addressed OC forum topic. Since fr-fr is an extension language pack, simply follow these instructions. It is not originally an issue that's delivered from the core since en-gb cannot originally reproduce those issues out-of-the-box. Therefore, contact the extension language pack developer to resolve this issue.

**Comment by zkrx** [comment]
I don't understand what solution you are referring to. If it is https://forum.opencart.com/viewtopic.php?p=538676#p538676 , then quotes are already escaped in the translation pack as shown in my original message. I can't do more.

> It is not originally an issue that's delivered from the core since en-gb cannot originally reproduce those issues out-of-the-box. 

This is a moot argument. Even English uses quotes every now and then, you're just lucky that it doesn't in the right places.

And how do I catch all the places where translation breaks? This needs a systematic review.

Please provide what solution you are referring to.

**Comment by zkrx** [comment]
I found another place where adding a

**Comment by zkrx** [comment]
I found another place where adding a 2nd product image breaks for the same reason. Using a "triple-escaped quote" in the translation solves it (`\\\'` instead of `\'`), but I cannot blindly do that for all translated sentences (otherwise stray '\' characters will show up in some places).

I don't understand how a translator can guess where triple escaping is needed and where it is not. To me, this is clearly a bug in OC. If it is not, someone can point me to the bit of documentation where this is explained.
