### ISSUE TITLE
[master] GDPR data export error

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12304]
**What version of OpenCart are you reporting this for?**
master branch

**Describe the bug**
GDPR data export request. Mail is delivered ... click on I confirm export my data. ... see error.

TypeError: Opencart\Catalog\Model\Account\Gdpr::getGdpr(): Argument #1 ($gdpr_id) must be of type int, string given in /home/xxx/public_html/opencart/master.demo/catalog/model/account/gdpr.php on line 12

GDPR delete account. Mail is delivered ... I confirm delete my account ... has the same problem.

**Expected behavior**
get data or delete data

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? cloudserver
 - Operating system linux
 - PHP version 8.2.5
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 112.0.1

**Comment by TheCartpenter** [comment]
Yes, confirmed. catalog/controller/mail/gdpr/remove, $args[0], pulls a string code, not an int gdpr id. The ```getGdpr``` should then be changed to: ```getGdprByCode``` method.
