### ISSUE TITLE
An e-Commerce software without any registration protection? Really?

### ISSUE THREAD

**Issue by PeterCodar** [opencart/opencart#12308]
**What version of OpenCart are you reporting this for?**
v4.0.2.1

**Describe the bug**
I don't see how an e-Commerce software can be delivered without the slightest check for registration.
This open the door for all the spammers and bots and many shop admin will recognize this huge problem much too late.

**To Reproduce**
1. Try to register a new account with any wild and not existing information
2. Login and try to order whatever you want

**Expected behavior**
Every new account registration should be protected by simple anti-spam methods like reCaptcha.
Or at least the account activation & login should be possible only after verifying the given mail-adress by checking a one-time verification code sent to this mail-adress and the correct response.

**Comment by pemaier** [comment]
Dear "Guest".
It seems that you know nothing about the OpenCart software and then to write such a stupid issue message.
1. This is not the right place for discussions and questions!!! Please do this in the forum.
2. There are several possibilities to solve the problem what you think to see. Go learn read and listen the people in the forum.
3. If you are not able to config one of the solutions by yourself visit the partner site and ask for help.

I suggest that you respect our rules and close your issue by your self.

Thank you for your respect!
(Sorry but this ignorance is to much....)

**Comment by PeterCodar** [comment]
Maybe there are "several possibilities to solve the problem", just none is working for v4.0.2.1.
All the solutions out there are heavy priced (including the help of "partner sites").

I don't think that the standard answer for Open Source software should be "go and buy 3rd party solutions and buy external help".

And no, I don't close my issue, because its not solved.
If you want that my issue disappears - to hide the huge lack of basic functionality - then feel free to close it.

**Comment by danielkerr** [comment]
U can find captchas on the extension page. 1 comes with opencart. Do research before posting
