### ISSUE TITLE
TypeError:  Opencart\Catalog\Model\Catalog\Product::getProduct(): Argument #1 ($product_id) must be of type int, string given

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#12309]
https://github.com/opencart/opencart/blame/0c3153d1c8eda165b603afa03f6a066324adc070/upload/catalog/model/catalog/product.php#L4

TypeError:  Opencart\Catalog\Model\Catalog\Product::getProduct(): Argument #1 ($product_id) must be of type int, string given in

**Comment by TheCartpenter** [comment]
OC version and route.

**Comment by danielkerr** [comment]
guessing games again!
