### ISSUE TITLE
Error: Could not call registry key model_tool_upload

### ISSUE THREAD

**Issue by ZateLabClients** [opencart/opencart#12303]
**What version of OpenCart are you reporting this for?**
Version 4.0.2.1
**Describe the bug**
opencart 4 error:
Exception: Error: Could not call registry key model_tool_upload! in /Users/D/php/opencart/public/system/engine/controller.php on line 37

**To Reproduce**
1. Goto sale/orders
2. Open an order which contain an customer uploaded image.

**Comment by TheCartpenter** [comment]
From which route?

**Comment by ZateLabClients** [comment]
> From which route?

Admin panel: sale/order/info

**Comment by ZateLabClients** [comment]
> Confirmed. Below line 650, add: `$this->load->model('tool/upload');` . This should resolve the issue.

i added this line, but when the order is "not required shipping", it produce some other errors. I didnt remember the errors. I will post that error soon.
