### ISSUE TITLE
order comment not record.

### ISSUE THREAD

**Issue by ouchqueen** [opencart/opencart#12319]
**What version of OpenCart are you reporting this for?**
Version 4.0.2.1
**Describe the bug**
A clear and concise description of what the bug is  :
  choose shipping method, then payment method, and then  order comment, the comment not record.
What section does it affect?

temp deal with 

catalog\controller\checkout\payment_method.php
174 line add code
```
if (isset($this->session->data['order_id'])) {
				$this->load->model('checkout/order');
				$order_data['comment'] = $this->session->data['comment'];
				$this->model_checkout_order->editOrder($this->session->data['order_id'], $order_data);
			}
```

**Comment by MarvinKlein1508** [comment]
The comment also doesn't get saved from admin.

It looks like the save command is missing within the API.
https://github.com/opencart/opencart/blob/f4bdaaa212ed762a29d05f7623a48ae2f1f5e72b/upload/catalog/controller/api/sale/order.php#L186
