### ISSUE TITLE
OC 4 allows downloads uploaded with & in filename, but not saved to db

### ISSUE THREAD

**Issue by hayden-t** [opencart/opencart#12316]
Will upload the file ok, but save says not found, should likely block filenames with & from the upload widget or fix the backend logic:

![image](https://user-images.githubusercontent.com/1000743/236712770-80370a0e-2895-4dbc-a4d8-3792a524913c.png)

**Comment by danielkerr** [comment]
of course! dont use special characters.

**Comment by hayden-t** [comment]
your loss, im just trying to make it easier for people to use this system.... i already worked it out obviously and took the time to make this ticket

**Comment by danielkerr** [comment]
ur just wasting many time
