### ISSUE TITLE
[master] Theme Template - Search form for middle size needs new css-config

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12318]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

**To Reproduce**
1. Go to any page with search field
2. Change make the browser-window smaller or use a tablet/mobile 
3. See error

**Expected behavior**
A clear and concise position to enter search string

**Screenshots / Screen recordings**
![image](https://github.com/opencart/opencart/assets/10166095/4a35516e-0077-4d57-9ae7-16511fd7118a)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? cludserver
 - Operating system linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 102.01

**Comment by danielkerr** [comment]
![image](https://github.com/opencart/opencart/assets/5079756/e80d5577-cada-4956-a71c-55bdf7cd2b9d)
works fine
