### ISSUE TITLE
Pressing order confirm button deletes its payment_method column record

### ISSUE THREAD

**Issue by MegamindAme** [opencart/opencart#12315]
**What version of OpenCart are you reporting this for?**
I am using opencart version 4.0.2.1

**Describe the bug**
While on the admin's order page, and you click confirm, the page doesn't load when you refresh the page and you get an error.
![image](https://user-images.githubusercontent.com/71287850/236707017-cad4ab38-dd1d-4a06-bee0-511b88e069a8.png)

What section does it affect?
The bug affects the database and as a result, the same page couldn't be opened and gives an error because the method_payment record is missing.

**To Reproduce**
1. Go to Orders
3. Click on Confirm
4. Refresh the page
5. See error 
![image](https://user-images.githubusercontent.com/71287850/236707098-b76bf451-0df6-4326-a9b0-998ad877e1c0.png)

**Expected behavior**
The page is expected to load as normal

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system: Linux Debian “Buster”
 - PHP version: 8.0
 - Apache version 2.4 
 - Browser(s) tested with chrome

**Additional context**

**Comment by danielkerr** [comment]
already fixed in master. u now have to manually refresh the payment methods and shipping methods if u want them changed
