### ISSUE TITLE
Opencart 4.0.2.1 - Table customer_payment doesn't exist when removing customer from BO

### ISSUE THREAD

**Issue by RicardoCostaTW** [opencart/opencart#12317]
**Opencart 4.0.2.1**

**Describe the bug**
Table customer_payment doesn't exist when removing customer from BO, but the credit cart native module write to the table.

**To Reproduce**
Exception:  Error: Table 'xxx_customer_payment' doesn't exist<br/>Error No: 1146<br/>DELETE FROM `xxx_customer_payment` WHERE `customer_id` = '35'

1. Go to BO and try to remove a client.
2. See error

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Deployed
 - Ubuntu
 - PHP 8.1
 - Apache

**Comment by danielkerr** [comment]
already fixed in master
