### ISSUE TITLE
PHP Warning:  Undefined array key "custom_field"

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#12310]
https://github.com/opencart/opencart/blame/0c3153d1c8eda165b603afa03f6a066324adc070/upload/catalog/controller/account/edit.php#L64

PHP Warning:  Undefined array key "customer_token" in ../catalog/controller/account/edit.php on line 24
PHP Warning:  Undefined array key "customer_token" in../catalog/controller/account/edit.php on line 29
PHP Warning:  Undefined array key "customer_token" in ../catalog/controller/account/edit.php on line 38
PHP Warning:  Undefined array key "firstname" in ../catalog/controller/account/edit.php on line 45
PHP Warning:  Undefined array key "lastname" in ../catalog/controller/account/edit.php on line 46
PHP Warning:  Undefined array key "email" in ../catalog/controller/account/edit.php on line 47
PHP Warning:  Undefined array key "telephone" in ../catalog/controller/account/edit.php on line 48
PHP Warning:  Undefined array key "custom_field" in ../catalog/controller/account/edit.php on line 64
PHP Unknown:  json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in ../catalog/controller/account/edit.php on line 64
PHP Warning:  Undefined array key "customer_token" in ../catalog/controller/account/edit.php on line 69

**Comment by danielkerr** [comment]
makes no sense as these ines of code 

```
if (!$this->customer->isLogged() || (!isset($this->request->get['customer_token']) || !isset($this->session->data['customer_token']) || ($this->request->get['customer_token'] != $this->session->data['customer_token']))) {
	$this->session->data['redirect'] = $this->url->link('account/edit', 'language=' . $this->config->get('config_language'));

	$this->response->redirect($this->url->link('account/login', 'language=' . $this->config->get('config_language')));
}

```
