### ISSUE TITLE
Checkout doesn't work, Exception:  Undefined property: Proxy::getMethods

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#12314]
https://github.com/opencart/opencart/blame/0c3153d1c8eda165b603afa03f6a066324adc070/upload/catalog/model/checkout/payment_method.php#L15

Exception:  Undefined property: Proxy::getMethods in ../catalog/model/checkout/payment_method.php on line 15 in ../system/engine/proxy.php on line 83

**Comment by danielkerr** [comment]
yes rename getMethod  to getMethods as it no longer gets one method
