### ISSUE TITLE
Opncart4.x .ocmod doesn't know

### ISSUE THREAD

**Issue by feyzullahdemir** [opencart/opencart#12327]
I am developing plugin for opencart according to new version.We saw that there is ocmod in plugin extensions.You see that you do not recognize the files with the ocmod extension while installing them.
<img width="864" alt="Screen Shot 2023-05-17 at 9 30 51 AM" src="https://github.com/opencart/opencart/assets/101548542/0ef5937a-4663-40b8-953b-2c21b3c65586">
as seen in the image , Although ocmod is selected, it does not perform selection. 
<img width="807" alt="Screen Shot 2023-05-17 at 9 31 13 AM" src="https://github.com/opencart/opencart/assets/101548542/4b56bba4-3971-40f8-8167-74be404aeaec">
but ocmod allows adding file extensions when all file is done.This feature is only valid for chrome. The ocmod extension does not load in other browsers.

**Comment by feyzullahdemir** [comment]
Yes I saw. Opencart has not made any default development for this. they can improve on this with the new version

**Comment by danielkerr** [comment]
we are not supporting ocmod any more. sorry

**Comment by feyzullahdemir** [comment]
what to use instead of .ocmod for future developments.Is there a roadmap?

**Comment by nexadomain** [comment]
@feyzullahdemir 
**Events**

Make extension using events

**Comment by feyzullahdemir** [comment]
Hi ,
@nexadomain  Thanks , I need 4.x Plugin Events Documents. Can you Send documents ?

**Comment by nexadomain** [comment]
@feyzullahdemir 
Search Google - **"Opencart Event"**, you will find plenty of documentation

Some of them are as follows:
1) https://github.com/opencart/opencart/wiki/Events-System
2) https://webkul.com/blog/opencart-event-system/
3) https://opencartbot.com/en/blog/event-system
4) https://www.opencart.com/blog?blog_id=174
5) https://www.opencart.com/blog?blog_id=215
etc

I also made basic extension, which is available for free in Opencart Marketplace. You can check source files of that Extension
[https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=44798](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=44798)
