### ISSUE TITLE
Error when click category edit button

### ISSUE THREAD

**Issue by Pakeydev** [opencart/opencart#12326]
Version 4.0.2.1

**Describe the bug**
When at backend, Catalog-Categories then click edit button. It goes to error page.
2023-05-16 04:14:18 - Error: Call to a member function setSourceContext() on string File: /home/mysite/public_html/INT/CLI/AT/storage/vendor/twig/twig/src/Node/Node.php Line: 171

In the error log it show;
Error: Call to a member function setSourceContext() on string File: /home/mysite/public_html/INT/CLI/AT/storage/vendor/twig/twig/src/Node/Node.php Line: 171

**To Reproduce**
At backend go to Catalog-Categories-Category then click edit button. It goes to error page.

**Expected behavior**

**Server / Test environment (please complete the following information):**

 - linux
 - 10.6.13-MariaDB
 - PHP version 8.2
 - Apache version 2.4.57
 - Browser(s) tested with Chrome

Fresh install of Opencart Version 4.0.2.1

**Comment by mhcwebdesign** [comment]
Unable to reproduce. Are you sure you tested 4.0.2.1, and not the master branch?

**Comment by Pakeydev** [comment]
> Unable to reproduce. Are you sure you tested 4.0.2.1, and not the master branch?

Yes...
![image](https://github.com/opencart/opencart/assets/12601807/b94a6134-3aaf-4eca-a86b-7b6d78276f6d)

I download it from here;
![image](https://github.com/opencart/opencart/assets/12601807/fe7d48bd-8c9f-4d4c-b4f4-3a8c30d3b061)

**Comment by danielkerr** [comment]
i just tested and its working fine
