### ISSUE TITLE
OC 4 potential bug with variant add to cart adding master instead...

### ISSUE THREAD

**Issue by hayden-t** [opencart/opencart#12338]
So the stock behaviour on adding a variant to the cart is for the cart to actually add the master/parent product with the same options to the cart instead...

Im not sure if this is intentional or not, if so, maybe it should be an option in admin ??

For starters here is the code, which switches the variant id with the master id before doing the add action
https://github.com/opencart/opencart/blob/fb89117577968fa4bf11c4f3bd4dec7f7d6255a8/upload/catalog/controller/checkout/cart.php#L243-L247

I found by commenting this out, the add works just fine, and you end up with the variant in your cart instead, which you can buy and re-order successfully.

Some reasons i dont think its intentional is that by having the variant in the cart is that you see the variant name in the cart/checkout/order history which might be specified/overridden, as well as having access to any other variant override fields which might want/need to be displayed else where such as model etc.

I also noticed there is a master_id field in the order_product table, which if variants were never meant to be put in the cart and ordered would not be needed there....

**Comment by danielkerr** [comment]
yes it is how its supposed to behaviour because variant products are products with pre defined options. dont open an issue just to ask a question

**Comment by hayden-t** [comment]
Why then is there a master_id field in the order_product table ??
It was not a question, but potential bug report that I was trying to be polite about and non-accusational...

**Comment by mhadar** [comment]
It is a bug. I created an product A, and product B as variant of product A.
When I add product B into the cart, then I get message 'Product B was added into basket', but when I go to basket, there is product A, with price of product A.

**Comment by hayden-t** [comment]
Glad you can see sense in this issue @mhadar , it seems pretty obvious when all the evidence is seen. It is a much more usefull and powerful feature this way.

**Comment by simonbhchristensen** [comment]
I totally agree. Just started my first oc4 project. It makes sense to fix this bug.

**Comment by danielkerr** [comment]
ill look into it.

**Comment by hayden-t** [comment]
To give you some idea of where this can be extended, for my client they have most combinations of options for a product to have its own price and sku. So I could use variant system for this, and make a custom js front end on the master product for chosing between the different options, and then depending on that it preselects that specific variant, and shows the price and sku to the customer, which if they then click add to cart, it adds that variant to the cart. The customer never sees the variant product page, and inbound links to the variant page (such as search results and cart links) redirect to the master product page. You can see the site here (but you cant see prices or add to cart without login, its trade only) [https://www.cphgroup.com.au/product/substrates/non-combustible-aluminium-panel/procore_a1](https://www.cphgroup.com.au/product/substrates/non-combustible-aluminium-panel/procore_a1) but you can see the model field change.   
  
I also modified the admin product list page to group products into master/variant hierarchy , so that you by default see masters only, but you can expand/collapse display of variants. Also because it suits to not add masters into the cart, i was able to customise the master vs variant product edit form to only show specific inputs that are specific for them. eg masters dont have (show) price or stock, while variants dont have (show) descriptions, or pretty much the whole general tab, as its just inherited from the master.  
  
I also use individual variant photos for the color picker.  
 

![](https://github.com/user-attachments/assets/ff46e008-f471-4b37-ac7a-20b92868ceab)

**Comment by danielkerr** [comment]
it doesernt just set pre defined option. opencart variants can over ride everything. description, price, attributes, etc..

**Comment by hayden-t** [comment]
Yes and i use that, as mentioned, some fields i override on the variant level but others i dont. Also i should mention i dont show the variant products in the category listing pages. That why i can hide some unneeded inputs on the either of the master or variant product forms, as those questions are irrelevant as never seen, or are always fine to be same as master. I even made it that some fields have the product override tick box ticked by default, as it always has to be set, like making it mandatory to be specified.
