### ISSUE TITLE
string data is not coming

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#12339]
https://github.com/opencart/opencart/blob/4f1c694ac703830f4a6e48b9074e374b7d473636/upload/catalog/controller/startup/setting.php#L30,L34

		if (!$result['serialized']) {
				$this->config->set($result['key'], json_decode($result['value'], true));				
			} else {
				$this->config->set($result['key'], $result['value']);				
		}

**Comment by hayden-t** [comment]
heres how you do ranges
https://github.com/opencart/opencart/blob/4f1c694ac703830f4a6e48b9074e374b7d473636/upload/catalog/controller/startup/setting.php#L29-L35

**Comment by hayden-t** [comment]
can you check in the database if those values exist ? maybe try re-saving them in settings

**Comment by eturerer** [comment]
https://i.hizliresim.com/hvdxwch.png

**Comment by hayden-t** [comment]
you mean a link is not loading ? such as 
index.php?route=product/product&language=en-gb&path=46_304&product_id=440
try 
index.php?route=product/product&path=46_304&product_id=440
