### ISSUE TITLE
OC 4 demo does not show variants feature

### ISSUE THREAD

**Issue by hayden-t** [opencart/opencart#12330]
Great big new feature, but no demo products using it ?? and you cant add new products in admin due to security.

**Comment by hayden-t** [comment]
did you add some examples for me to look at ?

**Comment by danielkerr** [comment]
I'm not ur slave. Install a copy.

**Comment by hayden-t** [comment]
Sorry, I didnt mean it like that, just trying to help by making a suggestion, I did end up installing a new copy, but i was just thinking that such a big new feature that has had that time put into it should be featured so people can see it in action. Thank you for your work here !
