### ISSUE TITLE
Error when clicking on System > Maintenance > Upgrade

### ISSUE THREAD

**Issue by mehtaman** [opencart/opencart#12334]
**What version of OpenCart are you reporting this for?**
Current Version
4.0.1.1

**Describe the bug**
Unable to auto upgrade Opencart using Admin page

What section does it affect?
System > Maintenance > Upgrade

**To Reproduce**
1. Go to Admin >  System > Maintenance > Upgrade
2. Click on Upgrade
3. See error logs

**Expected behavior**
Site should upgrade automatically 

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - Operating system - Linux
 - PHP version: 8.1
 - Apache version ?
 - Browser(s) tested: Chrome
 - Version: 113.0.5672.127 

****Additional context**
Error Log
2023-05-23 16:04:36 - TypeError:  dirname(): Argument #2 ($levels) must be of type int, string given
File: /it-me-up.co.uk/public_html/<custom admin folder>/controller/tool/upgrade.php
Line: 171**

**Comment by danielkerr** [comment]
there is no argument #2 in master branch. maybe try a manually upgrade by copy abd pasting the files to overwrite the current ones then just run the upgrade via the installer.

**Comment by danielkerr** [comment]
its fixed in master already
