### ISSUE TITLE
OC 4 product add option autocomplete not working due to category grouping

### ISSUE THREAD

**Issue by hayden-t** [opencart/opencart#12331]
Ive looked through the source code, and it seems your option autocomplete is the only one that uses the category grouping feature, which doesnt seem to be working correctly.

Im just seeing the category name as the option name, so, Choose five times, if i click in the option input with no input

![image](https://github.com/opencart/opencart/assets/1000743/abb18285-ab8b-4e51-a291-4f63b716a5b2)

its also generally breaks the search results not returning anything much., though the json returns are fine.

if i disable the category gorup returned from json it works fine

**Comment by hayden-t** [comment]
![image](https://github.com/opencart/opencart/assets/1000743/e0dd9e4d-4bf7-4e85-8b9c-8c8d82ba6773)

**Comment by danielkerr** [comment]
option name working fine. im  assuming u deleted all options

![image](https://github.com/opencart/opencart/assets/5079756/3bbea1cc-5e4d-4052-8488-7f5758ccc25f)

**Comment by danielkerr** [comment]
after deleteing all options i can not replicate ur made up issue.

just a time waster aren't u!
