### ISSUE TITLE
Autocomplete Bug

### ISSUE THREAD

**Issue by HostOncilla** [opencart/opencart#12344]
I've done a fresh installation of OpenCart 4.0.2.1 and I'm getting a bug where you can't select anything on any of the Autocomplete drop-down fields. When click on the option that you require, it just exits without selecting you choice. Please see the clip for example.

https://github.com/opencart/opencart/assets/8054786/81f55077-3c6e-41a3-8bd9-c7e920aad32d

**Comment by hayden-t** [comment]
I have found inconsistent results from this js popout too....

**Comment by danielkerr** [comment]
does nbot show version. i think what ever issue it is its already fixed on lastest and master

**Comment by mhcwebdesign** [comment]
@ HostOncilla : It looks like you are using a mobile device, in which case it would be useful to more details about that. It's working fine from a desktop browser (Chrome or Firefox).

**Comment by danielkerr** [comment]
I think it was the older version when I was still using dataset tag

**Comment by HostOncilla** [comment]
I'll have a test on with the latest master and update you on the results.

**Comment by mhcwebdesign** [comment]
@HostOncilla : Do you have the same issue when using Chrome or Firefox? Maybe it's an issue because of Safari.

**Comment by HostOncilla** [comment]
Yeah, I've tested it and I get the same issue with Google Chrome.

https://github.com/opencart/opencart/assets/8054786/66d497cf-11c3-48cc-b4a1-bfc871c25e92

**Comment by danielkerr** [comment]
They are time wasters. No information like os, browser etc..

**Comment by danielkerr** [comment]
Guessing it's ios

**Comment by danielkerr** [comment]
Possibly this guy having some setting on his phone blocking html Ajax calls

**Comment by HostOncilla** [comment]
Thank you so much for looking into the problem electroid79. danielkerr you really need to work on your people skills, not everyone is a "genius like you". I don't have any settings switched off on my iPhone, and I also get the same problem on 2 other laptops using Safari so it isn't isolated to a mobile phone or "some settings" that I have switched off on my phone.

**Comment by electroid79** [comment]
window.setTimeout(function () {
            $dropdown.removeClass('show');
        }, 1000);

**Comment by electroid79** [comment]
<img width="737" alt="Screenshot 2024-03-27 at 17 03 14" src="https://github.com/opencart/opencart/assets/137916539/b8e4e7a8-31cd-489b-a70e-d64922a87b22">
