### ISSUE TITLE
seo url not stable, sometimes product error.

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#12349]
opencart 4.0.2.0
seo url not stable, sometimes product error and redirect to product/error page and give PHP Warning:  Undefined array key 1 in catalog/controller/startup/seo_url.php on line 60

**Comment by TheCartpenter** [comment]
How can this issue be reproduced? Please, post the steps.

**Comment by chongshengdz** [comment]
this issue cannot be reproduced, it is only appear randomly.
product page redirect to domain/en-gb/product/error.html and give PHP Warning: Undefined array key 1 in catalog/controller/startup/seo_url.php on line 60 in the error log.

**Comment by chongshengdz** [comment]
> How can this issue be reproduced? Please, post the steps.

It looks like something wrong with MariaDB, after changing to MySQL 8.1 yesterday, I no more see these errors in a day in the error log.

**Comment by chongshengdz** [comment]
> this issue be reproduced

so if you want this issue to be reproduced, you need to install MariaDB and have a test.
pages are randomly not found.
