### ISSUE TITLE
Opencart API Issue

### ISSUE THREAD

**Issue by tktamas** [opencart/opencart#12355]
I would like to send an API request to change the status of my order, unfortunately I get the HTTP/1.1 404 Not Found message for all requests except index.php?route=api/account/login&language=en-gb&store_id=0. I would like to use the index.php?route=api/sale/order.load&language=en-gb&store_id=0 request. 
The api/account/login call is successful, I get session_id.
The version of Opencart I am using is **4.0.1.1** unfortunately the upgrade is not possible for the moment due to incompatibility of some extensions. Please can you help me to change something or how to send the request correctly?
Thanks in advance for your help.
I used this code now: 
`
$url = 'https://***********/index.php?route=api/sale/order.load&language=en-gb&order_id=15';

$curl2 = curl_init();

curl_setopt($curl2, CURLOPT_URL, $url);
curl_setopt($curl2, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($curl2, CURLOPT_HEADER, true);
curl_setopt($curl2, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($curl2, CURLOPT_CONNECTTIMEOUT, 30);
curl_setopt($curl2, CURLOPT_TIMEOUT, 30);
curl_setopt($curl2, CURLOPT_POST, 1);
curl_setopt($curl2, CURLOPT_POSTFIELDS, $request_data);
curl_setopt($curl2, CURLOPT_COOKIE, 'OCSESSID=' . $session_id);

$response = curl_exec($curl2);`

**Comment by hayden-t** [comment]
I have found there are any breaking bugs in 4.0.1.1 as im stuck on it for time being too, though we will upgrade asap once live, unfortunately you wont get any help here from Daniel, and ive found you are best to try comparing code with the latest github for differences in the area you diagnose as being at fault.

**Comment by danielkerr** [comment]
this part does work but u need need to store the session cookie to use again

**Comment by tktamas** [comment]
I'm supposed to do it this way, but it still doesn't work, can you please send me an example code for it?

**Comment by danielkerr** [comment]
Yes will look into it. It can be done. U need to store the session is in another session

**Comment by danielkerr** [comment]
yes i see i did it wrong. should not be making multiple calls to create an order. i will update it so parts can be updated and make it so within one call u can create an order.

**Comment by danielkerr** [comment]
fixed! updated the system so its a proper res api and orders can be creted with a single call. not sure what i was thinking with the past api.
