### ISSUE TITLE
when creating a new language, customer can't be created

### ISSUE THREAD

**Issue by ahmed-fad** [opencart/opencart#12358]
Opencart v4.0.2.1

if you add a language, customer can't be created
error: Customer Group does not appear to be valid

I traced the issue to this line:

`
public function getCustomerGroup(int $customer_group_id): array {
		$query = $this->db->query(.........

		return $query->row;
`
it tries to join with the description of the new language

suggested fix:
* either create a description line once the language is added
* or this query must be tolerant to missing language description

**Comment by pemaier** [comment]
At the moment I can't confirm this. Normal customer registration at the front-end is no problem.
![image](https://github.com/opencart/opencart/assets/10166095/28bd034c-2544-4d5c-913c-e2cb9b9557f6)

**Comment by danielkerr** [comment]
can not replicate
