### ISSUE TITLE
install language fails if there are existing entries in any table

### ISSUE THREAD

**Issue by ahmed-fad** [opencart/opencart#12360]
**Version: OC 4.0.2.1**

**Describe the bug**
when installing a new language, it tries to add new entries for this language in multiple tables.
for example, if you install Arabic, it will try to insert banner images/product description/category description/....etc for Arabic

it will fail if you have any existing entries (e.g. when you uninstalled the language and installed it again)

**suggested fix**
in \admin\model\localisation\language.php
replace:
```php
      // Customer Group
      $query = $this->db->query("SELECT * ..........
       foreach ($query->rows as $customer_group) {
       $this->db->query(
```

with: 
```php
      // Customer Group
      $query = $this->db->query("SELECT * ..........

foreach ($query->rows as $customer_group) {
            try {
                $this->db->query("INSERT INTO .............
            } catch (\Exception $e) {
                if(strpos($e->getMessage(),'Duplicate') != false){
                    ; //do nothing, allow duplicates
                }else{
                    throw $e;
                }
            }
        }
```

**Comment by TheCartpenter** [comment]
It wouldn't make sense to put a try catch into a foreach statement but rather a foreach into a try statement.

**Comment by danielkerr** [comment]
bind leading the blind. MYSQL has a NOT IF EXISTS

**Comment by ahmed-fad** [comment]
why did you feel compelled to say 'blind leading the blind'? You can suggest your solution in a more professional way.

**Comment by ahmed-fad** [comment]
> It wouldn't make sense to put a try catch into a foreach statement but rather a foreach into a try statement.

If you do so, it will exit the whole import process once an exception happened

**Comment by TheCartpenter** [comment]
And the way it should be, since there can't be more than 300 new instances that can be created at once on anyhow.

**Comment by ahmed-fad** [comment]
the idea is the the end use will not want the import to fail just because one row insert threw an exception. (not just duplicate id, but for any other reason)

**Comment by TheCartpenter** [comment]
Then, using an SQL query in a new customer group model with: ```GROUP BY HAVING COUNT``` would be more optimal and best practice rather than using a ```try catch``` with PHP since mysql libraries can already regroup the data whereas PHP would simply need a single IF statement to validate this without the need of a loop.

**Comment by TheCartpenter** [comment]
As for the ```throw $e```, that would be even lease suggested since ```user_token``` is being used as well as API requests. It would create more problematics with thrown exception errors during productions as this was already covered on this repository before. Which is why, the system/startup, admin startup and catalog startup files already use an error_handler to trigger erroneous activities.

**Comment by danielkerr** [comment]
its working fine for me.
