### ISSUE TITLE
Shipping method Sort Order - valid values

### ISSUE THREAD

**Issue by DaveRiba** [opencart/opencart#12369]
Both USPS and UPS shipping methods control the sort order of displayed costs by the variable(s) shipping_XXX_sort_order, where XXX is either UPS or USPS.
The key takes a numeric value
Is there a list of valid values?
I want to sort by ascending price, not descending price.
Any recommendations?

**Comment by danielkerr** [comment]
UPS or USPS are not included by default so no issue. but if urt asking advice on =creating them then u can force the type using (int)$sort_order
