### ISSUE TITLE
Try to change this line in system/library/db/mysqli.php

### ISSUE THREAD

**Issue by whmemon** [opencart/opencart#12364]
The following issue is also present in `system/library/db/pdo.php` I changed same thing in this file as i was facing same issue.
i.e changed

`$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");`

to 

`$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION'");`

              Try to change this line in system/library/db/mysqli.php

Old:
`$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");`

New:
`$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION'");`

See documentation at https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_mode for details.

_Originally posted by @mhcwebdesign in https://github.com/opencart/opencart/issues/9075#issuecomment-774502931_

**Comment by whmemon** [comment]
I am using OC Version 4.0.2.1 with Laragon 6 having
```
PHP Version 8.1.10
mysqlnd 8.1.10
Apache/2.4.54
```
It was creating error
` Incorrect DATE value: '0000-00-00'`
After searching found following issue
https://github.com/opencart/opencart/issues/9236
After going through source code of OC found code was update in 
`system/library/db/mysqli.php`
but not in
`system/library/db/pdo.php`

so i updated it. I think i am not only facing this issue.

Thanks

**Comment by danielkerr** [comment]
ur not even using the latest version!
