### ISSUE TITLE
Checkout - Warning: Undefined array key "address_id"

### ISSUE THREAD

**Issue by GITGOMO** [opencart/opencart#12368]
**What version of OpenCart are you reporting this for?**  OC 4.0.2.1

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

**To Reproduce**
Checkout process

To Reproduce

    Go to register a new user
    Go to products and something
    Go to cart and calculate the destination for shipping costs
    click on checkout
    see error (image below)

**Expected behavior**
The following text shoule NOT appear at the top of the checkout page:

Warning: Undefined array key "address_id" in /home/xxxxxx/xxxxxx/xxxxx_Website_OC4021_Unmodified/upload/catalog/controller/checkout/shipping_address.php on line 18"
**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? localhost
 - Operating system Linux
 - PHP version 8.0.27.1
 - Apache version 2.4.57.1 (running on Mageia linux)
 - Browser(s) tested with: Firefox
 - Version 102.12.0esr (64-bit)
 
**Additional context**
![OpenCartCheckout_address_id_issue](https://github.com/opencart/opencart/assets/99238066/45cf6b21-88da-47ad-a229-bc862df5327f)

**Comment by danielkerr** [comment]
already fixed in master
