### ISSUE TITLE
When the cart clicks on checkout, it sees the products and prices.

### ISSUE THREAD

**Issue by Osman06TR** [opencart/opencart#12370]
Hi,
I am installing opencart for the first time.
I installed it according to the documentation. Visitors can't see prices (I turned it off in settings) But there is a problem.
The visitor cannot see the prices, but adds them to the cart.
When the cart clicks on checkout, it sees the products and prices. (Does not redirect to sign up page)
Version 4.0.2.1
How can I fix this problem.
PS: I am a beginner and want to learn
![odeme_hatasi_ziyaretci](https://github.com/opencart/opencart/assets/136902857/8905d11b-2430-45b1-9f8c-4a8f94961b08)

**Comment by danielkerr** [comment]
turn off guest mode

**Comment by Osman06TR** [comment]
Hi,
![1](https://github.com/opencart/opencart/assets/136902857/e80de6f2-41f4-43a6-b91c-92eb45e9275e)

Thank you for your answer.
Guest mode is turned off.
I can give you the address if you want.

**Comment by Osman06TR** [comment]
The visitor is closed and cannot see the prices.
Adds it to the cart and goes to the payment screen.
It does not redirect to the sign up screen and shows the prices. (It should not show or add to the visitor's basket)

Control : zamanduy.net.tr

**Comment by Osman06TR** [comment]
Thanks.

**Comment by ADDCreative** [comment]
This looks like it wasn't fully fixed in 4.0.2.3. The Sub-Total is still displayed on the checkout page.
