### ISSUE TITLE
in seo_url, when building url, pipe (|) get url_encoded [was working in 4.0.1.1]

### ISSUE THREAD

**Issue by ahmed-fad** [opencart/opencart#12382]
**What version of OpenCart are you reporting this for?**
4.0.2.1

**Describe the bug**
pipe (|) get encoded in url
hence add to wishlist / compare fail

in `catalog/controller/startup/seo_url.php:88`
```php
		if ($query) {
			$url .= '?' . str_replace(['%2F', '%7C'], ['/', '|'], http_build_query($query));
		}

```

got changed to 
```php
		if ($query) {
			$url .= '?' . str_replace(['%2F'], ['/'], http_build_query($query));
		}

```

in this commit:

[79ff4bf](https://github.com/opencart/opencart/commit/79ff4bf9183569c0d853408b3c6804b9d1e04260)

**Comment by ADDCreative** [comment]
The pipe (|) character should be encoded in a URL. The wishlist and compare URLs now use dot (.) in 4.0.2.1. See https://github.com/opencart/opencart/issues/11594 for why it was changed.

**Comment by danielkerr** [comment]
already removed
