### ISSUE TITLE
[master] Frontend Module Latest - Translation not used

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12383]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Using a 2nd Language (German) and using the module Latest on the main page.
English is present any additional language is shown the English text.

**To Reproduce**
1. Go to 'install a 2nd language'
2. Configure and activate the module Latest
3. Open the main page at front end'
4. Choose the new installed language'
5. See error

**Expected behavior**
To see the right language text.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

![image](https://github.com/opencart/opencart/assets/10166095/a1d81e74-e72b-4ce4-bd17-49da1f5545ae)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Localhost
 - Operating system Linux
 - PHP version 8.2
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 114.0

**Comment by batumibiz** [comment]
I agree with the author of the topic, there is a problem with module languages.
You can check on the extension/opencart module included in the distributive. English is always used, translation is ignored.

**Comment by danielkerr** [comment]
ur just reperating issues others have posted
