### ISSUE TITLE
How to create an extension in OpenCart 4.0?

### ISSUE THREAD

**Issue by criskell** [opencart/opencart#12398]
Hello, thank you very much for the project.

I would like to develop a payment gateway extension on OpenCart 4.0, and to do this I downloaded OpenCart and created a directory under `/extension` in the server root `/var/www/html`:

```
.
└── extension
    └── super_payments
        ├── install.json
        ├── admin
        │   ├── controller
        │   │   └── payment
        │   │       └── super_payments.php
        │   ├── view
        │   │   └── template
        │   │       └── payment
        │   │           └── super_payments.twig
        │   └── language
        │       └── en-gb
        │           └── payment
        │               └── super_payments.php
        └── catalog
            ├── controller
            │   └── payment
            │       └── super_payments.php
            ├── language
            │   └── en-gb
            │       └── payment
            │           └── super_payments.php
            ├── view
            │   └── template
            │       └── payment
            │           └── super_payments.php
            └── model
                └── payment
                    └── super_payments.php
```

I followed this example:
<https://github.com/opencart/opencart/tree/master/upload/extension/oc_payment_example>

But the extension doesn't appear on this page (?route=marketplace/installer):
![image](https://github.com/opencart/opencart/assets/96352451/4411033f-07f4-433c-9a1d-4df962c607dc)

Also not on this page (?route=marketplace/extension):
![image](https://github.com/opencart/opencart/assets/96352451/d881aba0-81c9-4fe9-924d-152344b8914d)

Thank you if you can help

**Comment by vinibgoulart** [comment]
do we have an answer? has this issue been closed?

**Comment by robbiebel** [comment]
I'm facing with this issue. My branch is updated already.

**Comment by criskell** [comment]
> [@criskell](https://github.com/criskell) did you find a solution? i mount as volume in docker it doesnt appears, if i zip and upload it appears. but i need to make it work for development purpose.

I believe so, but I don't remember exactly how I did it
you can find the docker setup I did in this github tree
https://github.com/woovibr/opencart3-woovi/tree/64def07477364a64838322fa7d7ee5e3a24b4919/docker

**Comment by criskell** [comment]
> I already have a setup of Opencart 2 and Opencart 3 there is no problem at these versions. Just need my development folder installed in Opencart 4. I will try to add db records manually. Thank you for the answer.

from what I'm seeing what I did was basically invoke the opencart extension installer in an automated way
you can see in this method
https://github.com/woovibr/opencart3-woovi/blob/64def07477364a64838322fa7d7ee5e3a24b4919/scripts/Robo/Plugin/Commands/ExtensionCommands.php#L26-L85

**Comment by daisyklar** [comment]
> > I already have a setup of Opencart 2 and Opencart 3 there is no problem at these versions. Just need my development folder installed in Opencart 4. I will try to add db records manually. Thank you for the answer.
> 
> from what I'm seeing what I did was basically invoke the opencart extension installer in an automated way you can see in this method https://github.com/woovibr/opencart3-woovi/blob/64def07477364a64838322fa7d7ee5e3a24b4919/scripts/Robo/Plugin/Commands/ExtensionCommands.php#L26-L85

Great. This is exactly what Opencart 4 needs. My previous comment because I have success by mounting files directly in Opencart 3 and saw Dockerfile only and the repo name is Opencart 3.

I also already have success by adding db records manually in Opencart 4. But your extensionEnable function what I exactly need. Thank you so much.
