### ISSUE TITLE
Language on front

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#12396]
https://github.com/opencart/opencart/blob/30b9c0d3963aa3600a0d7630c02d67a8cebc80ed/upload/catalog/controller/startup/language.php#L63

Does not match what is stated in the comment
// Use load->language so it's not triggering infinite loops

need
```
		if (oc_substr($route, 0, 10) != 'extension/' && self::$extension) {
			$this->language->load('extension/' . self::$extension . '/' . $route, $prefix, $language);
		} else {
			$this->language->load($route, $prefix, $language);
		}
```

**Comment by danielkerr** [comment]
im guessing its not working for u because u have manually put the language files in and not using an extensions
