### ISSUE TITLE
Add wrapper class in Opencart 4

### ISSUE THREAD

**Issue by padaliyajay** [opencart/opencart#12395]
@daniel

I will recommend to provide a wrapper class with opencart 4 package. it can help to overwrite library function without conflict 

```
<?php
namespace Opencart\System\Library\Extension\Mazaengine;

class Wrapper {
	protected $object;

	public function __construct(object $object) {
		$this->object = $object;
	}

	public function __get($key) {
		return $this->object->{$key};
	}

	public function __set($key, $value) {
		$this->object->{$key} = $value;
	}

	public function __call($method, $args) {
		return $this->object->{$method}(...$args);
	}

	public function restore() {
		return $this->object;
	}
}
```

Your own cart file
```
<?php
namespace Opencart\System\Library\Extension\Mazaengine;

class MyCart extends \Opencart\System\Library\Extension\Mazaengine\Wrapper {
	public function getProducts() {
		$products = $this->object->getProducts();
                 // Do your changes in $products
                 return $products;
	}
}
```

in your startup file
`$this->cart = new Opencart\System\Library\Extension\Mazaengine\MyCart($this->cart);`

at any stage, if you want to remove your wrapper and restore original cart object then just do this
`$this->cart = $this->cart->restore()`

other developer can also create wrapper on your cart object, so there is no chance of conflict
[Someone Wrapper [Your wrapper [Object]]]

@danielkerr

_Originally posted by @padaliyajay in https://github.com/opencart/opencart/discussions/10251#discussioncomment-5715215_

**Comment by danielkerr** [comment]
lookz  the same as the proxy class
