### ISSUE TITLE
Cron command call via url

### ISSUE THREAD

**Issue by imarakhovets** [opencart/opencart#12404]
**Version of OpenCart 4.0.2.1**

**Describe the bug**
I have error during call wget "http://localhost/index.php?route=cron/cron" --read-timeout=5400

**To Reproduce**
1. Install opencart
2. Go to admin Extentions/Cron jobs 
3. Copy **cron url** like http://localhost/index.php?route=cron/cron"
4. Open  **cron url** in brower 

**Screenshots / Screen recordings**
![image](https://github.com/opencart/opencart/assets/16114914/ad9be65d-c655-4154-a3cd-b7c71f1f7954)

**Comment by danielkerr** [comment]
same as https://github.com/opencart/opencart/issues/11458
just disable or delete suibscription from cron in the admin page

**Comment by imarakhovets** [comment]
I understand, but it is stable release !

Where is auto tests ?
