### ISSUE TITLE
Shipping Tax rate is not flowing through to order totals

### ISSUE THREAD

**Issue by hayden-t** [opencart/opencart#12418]
OC 4.0.1.1

**Describe the bug**
You can choose a tax rate for a shipping class such as flat rate shipping. And if you have show prices with taxes setting enabled it will show the shipping price quote with tax added, this seems correct.

But the problem is that same price (or tax component) is not shown in the order totals/summary anywhere.

I extensively debugged the code to track down why, as was not sure if my fault, or bug fixed in later release or what.

The problem starts in the getQuote function for the extension shipping model: the text value has tax added, but not the cost:
```
	$quote_data['flat'] = [
		'code'         => 'flat.flat',
		'title'        => $this->language->get('text_description'),
		'cost'         => $this->config->get('shipping_flat_cost'),
		'tax_class_id' => $this->config->get('shipping_flat_tax_class_id'),
		'text'         => $this->currency->format($this->tax->calculate($this->config->get('shipping_flat_cost'), $this->config->get('shipping_flat_tax_class_id'), $this->config->get('config_tax')), $this->session->data['currency'])
	];
```

this screen shot is taken from a virgin install of oc4 with 10% product tax rate with show product price with tax enabled and same tax rate applied to the shipping method.
![image](https://github.com/opencart/opencart/assets/1000743/0167f7a3-a823-4adf-9a36-2c65b5ffed93)

Really it should add the tax for shipping (if that method has a tax class set) into the tax subtotal (regardless of if show prices with tax is set), but from my investigation it seems to only account for product tax.

If the 'cost' in getQuote is adjusted to have tax, then the shipping subtotal would be accurate and match the shipping quote, but then the tax subtotal wont have that tax amount included, it will be a purely product only tax component.

So Ideally i think the getTaxes function of system->cart needs to take into account other tax components than just product:
[upload/system/library/cart/cart.php](https://github.com/opencart/opencart/blob/ed06d3f4651774dbe68b08c0ef7543abd3ad7694/upload/system/library/cart/cart.php#L455)

**Comment by hayden-t** [comment]
Im not suggesting this is the final fix, thus Im not creating a pull request with it, but its enough for me and my needs, I put it in the end of getTaxes() before the final return.
```
if(isset($this->session->data['shipping_method']) && isset($this->session->data['shipping_methods'])){

	$shippingMethod = explode('.', $this->session->data['shipping_method']);
	$shippingData = $this->session->data['shipping_methods'][$shippingMethod[0]]['quote'][$shippingMethod[1]];
			
	$tax_rates = $this->tax->getRates($shippingData['cost'], $shippingData['tax_class_id']);
	$tax_rate = array_pop($tax_rates);//I only have one tax rate, so can skip the foreach used above for products
	
	$tax_data[$tax_rate['tax_rate_id']] += $tax_rate['amount'];
}
```

**Comment by ADDCreative** [comment]
@hayden-t I think this may of been fixed in 4.0.2.1 as I can't recreate this. For me the shipping tax is added in the shipping total extension.

https://github.com/opencart/opencart/blob/ed06d3f4651774dbe68b08c0ef7543abd3ad7694/upload/extension/opencart/catalog/model/total/shipping.php#L17-L22

**Comment by hayden-t** [comment]
looking a the diff, that bit wasnt changed, but, certainly other bits have been, which could have an effect, thanks for the input, ill have to look at it in more detail to see what effect it might have, or install the latest version as a test to see if i can replicate it.

**Comment by hayden-t** [comment]
If you are going to close it @danielkerr can you at least say why ?

**Comment by hayden-t** [comment]
This is the sort of rude behaviour that does not help here at all and is very immature. I reported a legitimate bug, and am still in the process of working out the reason, and you just close it as completed.

**Comment by hayden-t** [comment]
@TheCartpenter @ADDCreative yes i see now that extension/opencart/catalog/model/total/shipping.php does calculate the tax for shipping and is very similar in code to what hotfix i had to implement. I did actually find this file before and look into it but it was not executing to completion, and kept looking, i should have looked closer and realised that was the problem.

Look at it again now with some time, the problem is this line: https://github.com/opencart/opencart/blob/8a8f42e5992fc9dfaa25d259f80ebd62837201b7/upload/extension/opencart/catalog/model/total/shipping.php#L19 as as far as i have soon, $this->session->data['shipping_method']['tax_class_id'] is never set, that detail (tax_class_id) is only kept in $this->session->data['shipping_methods'] (and this is the line that the execution in the file ends.
I see that latest oc still has the same line, so all i can assume is that that key is being set in later versions, but i will investigate that next and report back.

**Comment by hayden-t** [comment]
Ok so $this->session->data['shipping_method'] is set here:
https://github.com/opencart/opencart/blob/be25c58ad73d61da2028e0a28c6ebab255fe4cdc/upload/catalog/controller/checkout/shipping_method.php#L124C83-L124C83
and it has changed from 4.0.1.1
from
`$this->session->data['shipping_method'] = $this->request->post['shipping_method'];`
to 
`$this->session->data['shipping_method'] = $this->session->data['shipping_methods'][$shipping[0]]['quote'][$shipping[1]];`

so with change it will get the extra shipping_method data, Im not sure i can just change that line though, as i have to check, that $this->session->data['shipping_method'] is likely expected to be just the simple text value code of the method in other places, rather than the array it would become.

**Comment by hayden-t** [comment]
There are 2 places where $this->session->data['shipping_method'] is expected to be an array:
extension\opencart\catalog\model\total\shipping.php  (already mentioned above)
and
extension\opencart\catalog\model\total\coupon.php 

vs all these files that need changing to not expect it to be a string
        modified:   public_html/catalog/controller/checkout/confirm.php
        modified:   public_html/catalog/controller/checkout/payment_method.php
        modified:   public_html/catalog/controller/checkout/shipping_method.php
        modified:   public_html/extension/opencart/catalog/controller/total/shipping.php
        modified:   public_html/extension/opencart/catalog/model/total/shipping.php

(and im not 100% i got them all yet, so even though i have patched them, ass and its working, i think ill revert them to default and patch the 2 total models, as its less vqmod xml to generate.

**Comment by hayden-t** [comment]
ok here is my xml to patch the 2 files
```
		<file name="extension/opencart/catalog/model/total/shipping.php">
			<operation>
				<search position="replace"><![CDATA[if (isset($this->session->data['shipping_method']['tax_class_id'])) {]]></search>
				<add><![CDATA[if (isset($shipping_method_info['tax_class_id']) && isset($shipping_method_info['cost'])) {]]></add>
			</operation>
		</file>
		<file name="extension/opencart/catalog/model/total/coupon.php">
			<operation>
				<search position="replace" offset="12"><![CDATA[if ($coupon_info['shipping'] && isset($this->session->data['shipping_method']['cost']) && isset($this->session->data['shipping_method']['tax_class_id'])) {]]></search>
				<add><![CDATA[				
				if ($this->cart->hasShipping() && isset($this->session->data['shipping_method'])) {
					$shipping = explode('.', $this->session->data['shipping_method']);
						if (isset($shipping[0]) && isset($shipping[1]) && isset($this->session->data['shipping_methods'][$shipping[0]]['quote'][$shipping[1]])) {					
							$shipping_method_info = $this->session->data['shipping_methods'][$shipping[0]]['quote'][$shipping[1]];
								
								if ($coupon_info['shipping'] && isset($shipping_method_info['tax_class_id']) && isset($shipping_method_info['cost'])) {
										$tax_rates = $this->tax->getRates($shipping_method_info['cost'], $shipping_method_info['tax_class_id']);

										foreach ($tax_rates as $tax_rate) {
											if ($tax_rate['type'] == 'P') {
												$taxes[$tax_rate['tax_rate_id']] -= $tax_rate['amount'];
											}
										}

									$discount_total += $shipping_method_info['shipping_method']['cost'];
								}						
						}
				}]]></add>
			</operation>
		</file>
```
