### ISSUE TITLE
[master] Strange behavior when ordering MacBook

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12432]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
When I'm ordering a Nikon camera I get a normal checkout form but if I'm ordering then a MacBook I get a short checkout form [not really working because it throw an error].
**To Reproduce**
1. Go to 'order a camera and then a MacBook'
2. Click on 'checkout'
3. See error

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app
![image](https://github.com/opencart/opencart/assets/10166095/534cfdc5-52fa-4f1e-84c3-9b386a2106ea)
![image](https://github.com/opencart/opencart/assets/10166095/68029aea-6cd0-4ae6-88b5-e56ee5fff69b)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.0

**Additional context**
There is no difference in the behavior of English or German language - I tested both.

**Comment by danielkerr** [comment]
possibly set to no shipping or subscription product

**Comment by pemaier** [comment]
Daniel you are right - Product was set to Shipment required - No
but i think the payment options error should not occur because they are present.
