### ISSUE TITLE
[master] Shopping cart - recalculation removes products 

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12437]
**What version of OpenCart are you reporting this for?**
master / 4.0.2.2
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
When a customer has products in shopping cart and press the button update then Success message appear and the shopping cart lost all products.

**To Reproduce**
1. Go to 'Frontend register a user'
2. Click on 'Cameras and order one or more'
3. Click on 'Shopping Cart'
4. Scroll down to 'a product and click update'
5. See error

**Expected behavior**
To get a updated product list

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app
![image](https://github.com/opencart/opencart/assets/10166095/2c5580bc-41e4-4662-841b-89c5812dd2d1)
![image](https://github.com/opencart/opencart/assets/10166095/3e81e90d-2742-466d-9b14-2707befa9077)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable]  FF
 - Version [e.g. 22] 115.0

**Additional context**
It make no difference it here are one or more products / products with/wo options ... at all the same behavior

**Comment by mhcwebdesign** [comment]
I can confirm this error, just tested it on 4.0.2.2

**Comment by danielkerr** [comment]
@mhcwebdesign the master branch is the beta release. going to start doing more frequent releases anyway. there's no big changes plus the upgrade page should be fully working now.

**Comment by MaxD2** [comment]
> the upgrade page should be fully working now.
How much time does it takes to upgrade 4.0.2.1 to 4.0.2.2?
