### ISSUE TITLE
Installation Failure due to Twig Filesystem loader on DirectAdmin hosted services

### ISSUE THREAD

**Issue by aarauf** [opencart/opencart#12445]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Initial Opencart installation fails due to fatal error in Twig.

**To Reproduce**

Attempt installation on DirectAdmin hosting.

**Expected behavior**

Follow-through of installation wizard

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Web Server
 - Operating system 
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
i just did a test install and it works fine. i have no idea why directadmin would cause opencart not to work
