### ISSUE TITLE
Stock Status Order Status missing/not working

### ISSUE THREAD

**Issue by decorello** [opencart/opencart#12442]
OC4.0.2.2

After new installation its not possible to save the settings, because the status are missing.

New install -> go to Stock Status -> Page is empty. Same for order status.

I saw in the database that there are entries inside. Its also not possible to make new entries - there is a form, but it have no effect when i save any informations there.

First i thought its a namespace problem, but currencies and languages are working....so it must be a other problem...
I also tested with a new admin folder name and without any changes.
Server is a debian11 with ols.

**Comment by pemaier** [comment]
Jfi: That's in my new install:
![image](https://github.com/opencart/opencart/assets/10166095/0faa295d-516d-4104-9e6e-ac713fbf2438)

**Comment by pashast** [comment]
Clear admin language cookie

**Comment by decorello** [comment]
Yeah, that was the way...thanks

**Comment by jfbvm** [comment]
@pashast MAN YOU SAVED MY LIFE!!!!! 👏👏👏👏👏
