### ISSUE TITLE
banners no data will save

### ISSUE THREAD

**Issue by martinbradshaw** [opencart/opencart#12452]
4.0.2.2

extensions / moduals / banner
save button is not updating on pressing and also no changes are saved inside the banner module.

also under design/banner no changes can be made or saved

**To Reproduce**
1. Go to extensions/modual 
2. Click on banner and edit icon
3. make a change and press save
4. see issue

error logs
2023-07-09 00:09:47 - Error:  Call to undefined function Opencart\System\Helper\Utf8\strlen()
File: /home/********/domains/**********.com/public_html/***********/controller/design/banner.php
Line: 269

2023-07-09 00:28:33 - Error:  Call to undefined function Opencart\System\Helper\Utf8\strlen()
File: /home/*******/domains/******.com/public_html/extension/opencart/admin/controller/module/banner.php
Line: 128

**Comment by danielkerr** [comment]
Opencart\System\Helper\Utf8\strlen was removed ages ago. 

can not replicate

**Comment by martinbradshaw** [comment]
any idea how i can fix it

**Comment by mhcwebdesign** [comment]
Do a fresh install, and then try it again.

**Comment by martinbradshaw** [comment]
i  installed 4.0.2.2 over the top of a fresh 4.0.2.1 so its not that old

**Comment by TheCartpenter** [comment]
@martinbradshaw: Was the database also updated since you uploaded the files over OC v4.0.2.1 instead of uploading it fresh or was the database also installed fresh since 4.0.2.2?
