### ISSUE TITLE
[master] Order recalculation - Data in not getting saved

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12459]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect? 
Invoice and order itself

**To Reproduce**
Steps to reproduce the behavior: related to #12431 
1. Then Go to 'click Invoice'
2. See error

Also when reopen the order then you see the unchanged order.

**Expected behavior**
That the changed are saved and changed data will be used in invoice.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Server
 - Operating system Linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.0

**Comment by danielkerr** [comment]
So the invoice has a error not the order. Stop posting issues if u are to dumb to post them properly

**Comment by pemaier** [comment]
...ohhh so dumb it's not my invoice - It's yours!

**Comment by danielkerr** [comment]
u need to confirm the order for it t save

**Comment by danielkerr** [comment]
can not replicarte. or its fixed

**Comment by pemaier** [comment]
@danielkerr
I tested once again and the all 3 following information is not changing.
![image](https://github.com/opencart/opencart/assets/10166095/df2916e8-4691-44c0-858e-5bfd30639fdc)

https://nettwork.ru/opencart/master.demo/admin0
user/pass: demo/demo

Now I have not installed a 2nd language so you can test only store and currency.

**Comment by pemaier** [comment]
Here is a video....

https://github.com/opencart/opencart/assets/10166095/5456712b-fb6e-4f53-8c9c-4630cb7cd567

**Comment by pemaier** [comment]
Here a video ...

[order-data-save.webm](https://github.com/opencart/opencart/assets/10166095/318f3aa1-3351-47d9-8169-6f4997ab3a23)
