### ISSUE TITLE
[master] Checkout - Product without shipping courses payment problem

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12457]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
If a customer order a product without shipping (MacBook) and is going to checkout - enter his data for registering clicks on continue for choosing the payment option show up an error.

**To Reproduce**
Steps to reproduce the behavior: related to #12432 

**Expected behavior**
That customer is able to choose a payment method. 

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app
![image](https://github.com/opencart/opencart/assets/10166095/87720ba8-34cf-4b53-afd7-1ffb081b55a3)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Server
 - Operating system Linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.0

**Additional Info**
If there is an additional product with shipping requirement on the cart then it is working well.

**Comment by danielkerr** [comment]
Install a payment method that's not cash in delivery to a product that does not require delivery. Ffs u are wasting my time
