### ISSUE TITLE
[master] - catalog/model/checkout/order/addOrder() method

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#12474]
The order cannot be created, the ```subscription_id``` field is missing as per helper/db_schema:

https://github.com/opencart/opencart/blob/master/upload/catalog/model/checkout/order.php#L5C4-L5C4 . That's why.

**Comment by danielkerr** [comment]
And where is the order begining created wio

**Comment by TheCartpenter** [comment]
While I do know how to post the errors the way they should be addressed. Let me remind you that not only you're impacting everyone with the orders right now, but also the fact that you're the one who added the subscription_id field in the order table as a mandatory as it is not the only time you're causing this issue especially since OC 4 releases.

If you're not able to keep track of what you're doing, then perhaps you should consider an early retirement buddy because, obviously, based on the mounts of the distributions with the mistakes you have put in whereas other users have also posted to you as you keep posting stuff against your own design, your own defects and decide on your own to close commits and that's on you.

If you don't want to gather solutions from other users, then evidently you're on the wrong site. In here, we work as a team. You don't like it? Then go somewhere else 'cause you clearly have given up the way you're talking to others while I haven't. Just since yesterday, I had to cover other BS from your upgrades and posted them today. You don't like it? Then FIX IT!
