### ISSUE TITLE
Error handlers needs updating for PHP 8

### ISSUE THREAD

**Issue by ADDCreative** [opencart/opencart#12483]
The error handlers need updating for PHP 8 to handle errors suppressed with @ correctly. error_reporting no longer returns 0.

https://php.watch/versions/8.0/fatal-error-suppression#suppress-error-handlers
https://www.php.net/manual/en/function.set-error-handler.php#refsect1-function.set-error-handler-examples

https://github.com/opencart/opencart/blob/04c3ddcecff2029682b3ae4b1fb0489de68d8fff/upload/catalog/controller/startup/error.php#L13
The above and in all other error handlers would need changing to something like the following.

```php
if (!(error_reporting() & $code)) {
```

**Comment by danielkerr** [comment]
fine lets see if works or i get complaints

**Comment by ADDCreative** [comment]
@danielkerr Please read https://php.watch/versions/8.0/fatal-error-suppression#suppress-error-handlers.

error_reporting() will no longer return 0 in normal conditions in PHP 8. It will most likly return ```E_ERROR | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR | E_RECOVERABLE_ERROR | E_PARSE``` which is 4437, so checking ```=== 0``` is pointless.

**Comment by danielkerr** [comment]
then why didnt u post the solution ! wasting my fucking time

**Comment by ADDCreative** [comment]
I've done a pull request https://github.com/opencart/opencart/pull/12660 to show the sort of changes needed to update the error handlers for PHP 8. Not had time to install the latest master and test.

**Comment by hayden-t** [comment]
seems this was abandoned ?
