### ISSUE TITLE
[master]product list view is just a mess

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#12489]
product list view is just a mess
![list-view](https://github.com/opencart/opencart/assets/30888843/ed34a79c-d0cd-4b21-b11d-4d049918dfe9)

**Comment by chongshengdz** [comment]
and the pagination is not mobile responsive.
![Screenshot_2023-07-13-02-44-25-127_com android browser](https://github.com/opencart/opencart/assets/30888843/f363862f-e00e-4eda-acf1-dad1397732e8)

**Comment by ADDCreative** [comment]
Looks like this commit caused the issue. https://github.com/opencart/opencart/pull/12343

Moved the button-group, which has `position: absolute;` into another div which does not have `position: relative;`.

**Comment by danielkerr** [comment]
i should never trust these clowns
