### ISSUE TITLE
[feature request] custom field should add Geo Zone filter

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#12495]
because some countries need buyers to provide tax id (CNPJ) like Brazil, but some are not.
so setting as a required field is not always true for all countries.

**Comment by danielkerr** [comment]
yes so u leave it as an optional field.

 this is not a bug but a feature request.

**Comment by chongshengdz** [comment]
> an optional field
an optional field is not a required filed, they may not enter it.
