### ISSUE TITLE
Best Seller table missing after upgrade

### ISSUE THREAD

**Issue by itobin** [opencart/opencart#12496]
**What version of OpenCart are you reporting this for?**

4.0.2.2

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Run upgrade from 4.0.1.1, when visiting the website after the upgrade the following error appeared

Exception: Error: Table '*****.oc_product_bestseller' doesn't exist
Error No: 1146
SELECT * FROM `oc_product_bestseller` ORDER BY `total` DESC LIMIT 0,10 in /****/****/www/system/library/db/mysqli.php on line 68

**To Reproduce**
1. Go to website or click on best sellers module in admin

**Expected behavior**
Website should load

To work around issue, disabled best sellers module, however when in admin and clicking on best sellers the same issue appears so something happened to the table during the upgrade.

**Comment by TheCartpenter** [comment]
It's not a bug. You just need to reinstall the extension from the OC admin.

**Comment by itobin** [comment]
that has worked thanks, however highlights an upgrade problem?

**Comment by TheCartpenter** [comment]
Users are normally aware that when upgrades are applied that it's being done without guarantee of success, since extensions are not part of the core. While, in this case, it is; it should only require reinstalling the extension to solve the issue.

**Comment by danielkerr** [comment]
there should be a new button that generates the best seller list on the best seller extension page
