### ISSUE TITLE
User cannot place order when guest checkout is disabled

### ISSUE THREAD

**Issue by itobin** [opencart/opencart#12497]
**What version of OpenCart are you reporting this for?**

4.0.2.2

**Describe the bug**
A clear and concise description of what the bug is

When disabling guest checkout, a user places and order and fills out the user info such as addresss etc.  However opencart complains that the user needs to create an account when you click continue and wont allow you to go past the user info section.

The errror is

***Warning: Items in your shopping cart require you to register for an account!****

**To Reproduce**
as above

**Expected behavior**
Opencart should create the account and allow the user to select shipping method.

**Comment by mhcwebdesign** [comment]
Seriously, this is not a bug!

> disabling guest checkout
> ....
> Items in your shopping cart require you to register for an account!
> 

This is exactly what it should do!

**Comment by danielkerr** [comment]
so that means the products are subscription or have downloads linked to them

**Comment by itobin** [comment]
they cant register though, the user types in the user details, after they click continue, the message pops up with no option to register on that screen.

So are you saying that after they type in the user details (some people will be slow at typing) to place the order and the message pops up, they then have to click the register button at the top (under my account) and go through the process again? its seems counter intuitive for them to have to do it twice?

Also no subscription or downloads are linked, they are one of purchases of goods.

**Comment by danielkerr** [comment]
Post a link to the site

**Comment by itobin** [comment]
https://www.marinefarm.co.uk/

**Comment by danielkerr** [comment]
only u having this issue! u have noit configured the products properly.

**Comment by itobin** [comment]
Not entirely sure what you mean by not configured properly?

Guest check is also enabled currently as it was causing issues when disabled.

**Comment by sublok** [comment]
Having the same issue.  Not just OP, as I agree with OP the option to show the user creating fields in a section which does not allow it to be created is frankly silly. Its confusing for the potential customers. Issue still occurs on 4.0.2.3 

I know that was closed a year ago, so don't roast to hard for the necropost.  Just was looking for a solution for this without enabling guest chkout. As this is still an issue, do not have subscription products, no downloads linked on the products.

**Comment by itobin** [comment]
it is still an issue, i gave up as i was i just wasnt being listened to. I dont have downloadable products or subscriptions, it was fresh out of the box install with just products to purchase.

**Comment by sublok** [comment]
Its my guess that in controller/checkout near line 232 `if (!$json) {
			// If not guest checkout disabled, login require price or cart has downloads
			if (!$this->request->post['account'] && (!$this->config->get('config_checkout_guest') || $this->config->get('config_customer_price'))) {
				$json['error']['warning'] = $this->language->get('error_guest');
			}`
The issues is caused or being flagged becuase of the default user group being set. I was able to replicate the issue when i only had  "customer group" discounts set in the products. IE if i had a price set wholesale it caused the same error,

**Comment by mhcwebdesign** [comment]
@danielkerr : I just reopened this issue, because it still hasn't been solved. I just managed to reproduce the same error with today's master branch code. 

With the guest checkout disabled, a new user should be able to do a checkout after having registered his details (Personal Details, Shipping Address) on the checkout page, but the subsequent call to the **checkout/register.save** always results in this error:

Warning: Items in your shopping cart require you to register for an account!

Can you look into this please? Thanks.

**Comment by mhcwebdesign** [comment]
I think the solution is to modify file catalog/controller/checkout/register.php for lines 227 to 230:

old:
```
		// Force account requires subscript or is a downloadable product.
		if ($this->cart->hasDownload() || $this->cart->hasSubscription()) {
			$this->request->post['account'] = 1;
		}
```

new:
```
		// Force account required if cart has downloadable products or if subscription or if guest checkout is disabled.
		if ($this->cart->hasDownload() || $this->cart->hasSubscription() || !$this->config->get('config_checkout_guest')) {
			$this->request->post['account'] = 1;
		}
```
