### ISSUE TITLE
[master] - catalog/model/checkout/subscription/addSubscription()

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#12490]
```subscription_status_id``` is a mandatory field. The addSubscription() method won't be able to add a value as the same goes to the addOrder() method with the ```subscription_id``` field. Since we have the ```order_status_id``` field in the ```order``` table, then the ```subscription_id``` should be removed and replaced with the: ```subscription_status_id``` underneath the ```order_status_id```. The ```subscription_status``` or the ```$this->config``` should use a ```default``` value for subscriptions the ```subscription_id``` won't likely be a considerable option to be set at ```0``` as a default value when no subscriptions are involved.

https://stackoverflow.com/questions/3997966/can-i-add-a-not-null-column-without-default-value .

**Comment by TheCartpenter** [comment]
The ```subscription_status_id``` field should also be removed from the ```subscription``` table.

**Comment by TheCartpenter** [comment]
The admin orders already have a recycle bin when the ```order_status_id``` is set to: ```0```. The same could be applied with the ```subscription_status_id``` whether the ```order_status_id``` is valid or not.

**Comment by danielkerr** [comment]
subscription not finished
