### ISSUE TITLE
[master] Two-factor Security send no automatic mail

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12504]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
When 2-factor security is active the mail after the login (with the code) is only send after click on resend button.

**To Reproduce**
1. Go to 'admin'
2. Then 'login with user/pass'
3. Click Login then the 2-factor security form is visible
4. but no mail is send to the user
5. only after click on button Resend the mail is send to the user

**Expected behavior**
After enter user/pass and press return the 2-factor security form come up and the mail with the code is send automatic to the user.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app
![image](https://github.com/opencart/opencart/assets/10166095/87f2fccd-5266-4481-94e3-561c04428cfe)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.0.2

**Comment by TheCartpenter** [comment]
```admin/model/user/user->editCode()``` is not used in the common/authorize.send method, The route in the admin/controller/mail/authorize/index checks for: ```common/authorize.send``` but the ```editCode()``` is not launched from this method.

**Comment by danielkerr** [comment]
what a dick! playing guessing games again! 

im closing it because no nidea if they  setup the smtp email in setting

**Comment by pemaier** [comment]
No I didn't setup smtp - setting is on mail.

**Comment by pemaier** [comment]
Here a video
[Screencast 2023-08-17 13:43:38.webm](https://github.com/opencart/opencart/assets/10166095/aadde928-abef-424a-9e8c-3d672d0a2c67)

**Comment by ADDCreative** [comment]
@pemaier See https://github.com/opencart/opencart/issues/12615#issuecomment-1680871936 for a fix for the forget password not working.

**Comment by pemaier** [comment]
@ADDCreative Thank you for the information.
I tested and I have the following behavior.

I start with the normal login (user/pass) then the 2FS form comes up ... then I'm waiting... nothing happens/no mail **only after pressing Resend** the mail with the code is sent.
Then the next step to login work well with the code.

**Comment by pemaier** [comment]
@ADDCreative  Update - After some time the 2FS was working again ... in the way before described with the requirement to press Resend to get the email with the code. 
So your solution for the Forget Password mail is working. Thank you.

**Comment by pemaier** [comment]
Perfect :) that solve the problem... I tested and removed the line and it is working well. Thank you.

**Comment by ADDCreative** [comment]
It looks like the #button-send trigger is being called before the button is initialized. Probably need to delay the calling of the trigger.

https://github.com/opencart/opencart/blob/72dae9399e4a5c3bdc9488cfa2e5ec0b912a4e31/upload/admin/view/template/common/authorize.twig#L75
