### ISSUE TITLE
[bug] [marketplace] my extension does not appear in my opencart instance

### ISSUE THREAD

**Issue by criskell** [opencart/opencart#12503]
Hello, I have published a test extension to demonstrate this bug:
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=45255&filter_search=criskell
When searching for this extension in my OpenCart instance, no results appear:
![image](https://github.com/opencart/opencart/assets/96352451/a45f7b36-9903-4417-9e87-f71a346ab5b2)
My OpenCart version is 4.0.1.1.
Thanks

**Comment by danielkerr** [comment]
yes it needs to be approved by my staff

u should upload the extension on the installer page if u need to test the install function

**Comment by criskell** [comment]
> yes it needs to be approved by my staff
> 
> u should upload the extension on the installer page if u need to test the install function

How can I get approval for my real extension?

**Comment by danielkerr** [comment]
use the support tickets. ask for ur extensiuon to be approved.
