### ISSUE TITLE
link() function rewrites core modules like checkout, making APIs fail in other languages

### ISSUE THREAD

**Issue by ahmed-fad** [opencart/opencart#12506]
version
4.0.2

**Describe the bug**
when using other languages, the ->link() function rewrites the URL (seo) removing the index.php
for example: 
http://localhost/oc/index.php?route=checkout/cart.add&language=en
becomes
http://localhost/oc/en-gb?route=checkout/cart.add

which renders api not working.

**Suggested correction**
in this file:
`\system\library\url.php`

replace this:
```php
foreach ($this->rewrite as $rewrite) {
                $url = $rewrite->rewrite($url);
            }
```

with this:
```php
$modulesToBeSkipped = ['checkout/cart', 'product/compare', 'account/wishlist'];
        $skipFound = false;
        
        foreach ($modulesToBeSkipped as $moduleStr) {
            if(strstr($url, $moduleStr)){
                $skipFound = true;
                break;
            }
        }

        if(!$skipFound){
            foreach ($this->rewrite as $rewrite) {
                $url = $rewrite->rewrite($url);
            }
        }
```

**Comment by TheCartpenter** [comment]
This could be done through the controller/startup with an extension.

**Comment by ahmed-fad** [comment]
not sure that I understood, but the issue is that the core modules shouldn't be re-written in SEO engine, or else the api receiver will not be able to process them.

**Comment by danielkerr** [comment]
checkout isrn't a module.

**Comment by ahmed-fad** [comment]
Hi Daniel,

Can you confirm if it is a bug? I'm afraid it is something affected by the theme.

**Comment by danielkerr** [comment]
its a quick fix. ill do it

**Comment by ahmed-fad** [comment]
thanks a lot.

**Comment by danielkerr** [comment]
i don't have a clue what issue u are talking about!
