### ISSUE TITLE
Bug - Return Error Message

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#12508]
**What version of OpenCart are you reporting this for?**
OpenCart 4.0.2.2, latest

**Describe the bug**
Validator for "product" and "model" doesn't match to language file.
Error description ask user to insert at least 3 characters. If you insert only 1 character error vanish.
Validator need to be changed from < 1 to < 3 or language files need to be changed from "than 3" to "than 1".

**To Reproduce**
1. Go to 'Sales > Returns'
2. Click on 'Add New'
3. Press 'Save'
4. Check errors under "Product Name" and "Model".
5. Insert only 1 character in each field
6. Press 'Save'
7. See error

Code
admin/controller/sale/returns.php
```
		if ((oc_strlen($this->request->post['product']) < 1) || (oc_strlen($this->request->post['product']) > 255)) {
			$json['error']['product'] = $this->language->get('error_product');
		}

		if ((oc_strlen($this->request->post['model']) < 1) || (oc_strlen($this->request->post['model']) > 64)) {
			$json['error']['model'] = $this->language->get('error_model');
		}
```

admin/language/en-gb/sale/returns.php
```

$_['error_product']        = 'Product Name must be greater than 3 and less than 255 characters!';
$_['error_model']          = 'Product Model must be greater than 3 and less than 64 characters!';
```

Screenshots:
https://ibb.co/JvrGVW0
https://ibb.co/1qR1yPS

**Comment by TheCartpenter** [comment]
Confirmed. Also identified in the catalog/controller/account/returns.php file.
