### ISSUE TITLE
Fraud tab misalign in order details page

### ISSUE THREAD

**Issue by garychewter** [opencart/opencart#12505]
**What version of OpenCart are you reporting this for?** 4.0.2.2

**Describe the bug**
Fraud tab not align correctly in the order details page

**Additional context**
The line 1184 in https://github.com/opencart/opencart/blob/master/upload/admin/controller/sale/order.php should be `'code'  => $extension['extension'],` instead of `'code' => $output,`.

**Comment by garychewter** [comment]
Hi @danielkerr 

Any update about this issue?

Thank you.

**Comment by danielkerr** [comment]
merged a fix
