### ISSUE TITLE
Add a Favicon feature not available in Opencart v4.0.2.2

### ISSUE THREAD

**Issue by this-git** [opencart/opencart#12517]
**What version of OpenCart are you reporting this for?**
v4.0.2.2
**Describe the bug**
I have not found any kind of feature how to add favicon in a web page like 
<link rel="icon" type="image/x-icon" href="/images/favicon.ico">

**Comment by CreativeArtDesign** [comment]
They have removed it.
But i think there is a other way to do it upload it to the root but i have not tryied it. it should be named o.ico or something. browser for it.
