### ISSUE TITLE
master bug --- Mail Alerts

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#12513]
![Mail-Alerts](https://github.com/opencart/opencart/assets/30888843/a76a7a87-4cf0-46fe-9abd-70cf6a04c17b)
![Mail-Alerts2](https://github.com/opencart/opencart/assets/30888843/6088e80d-574e-4986-a756-b4a0e6c7da24)
I don't tick the "Register", but the mail is still being sent.

**Comment by chongshengdz** [comment]
please fix it ASAP, too many spam registration.

**Comment by bofa26** [comment]
has this been fixed?

**Comment by chongshengdz** [comment]
> has this been fixed?

you can disable it.
NAVIGATION=>Extension=>Event=>mail_customer_add and mail_customer_alert

**Comment by danielkerr** [comment]
not sure there is ebven a bug as u have put fuck all description
