### ISSUE TITLE
Mysql Error: Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by ZateLabClients** [opencart/opencart#12514]
**What version of OpenCart are you reporting this for?**
Version 4.0.2.1

**Describe the bug**
<br/><b>Fatal error</b>:  Uncaught Exception: Error: Deadlock found when trying to get lock; try restarting transaction&lt;br/&gt;Error No: 1213&lt;br/&gt;DELETE FROM `oc_session`WHERE `expire`&lt;'2023-07-20 15:28:07'in /Users/D/php/opencart_aabuy/public/system/library/db/mysqli.php: 64 Stack trace: #0/Users/D/php/opencart_aabuy/public/system/library/db.php(46): Opencart\System\Library\DB\MySQLi-&gt;query('DELETE FROM `oc...')#1/Users/D/php/opencart_aabuy/public/system/library/session/db.php(78): Opencart\System\Library\DB-&gt;query('DELETE FROM `oc...')#2/Users/D/php/opencart_aabuy/public/system/library/session.php(112): Opencart\System\Library\Session\DB-&gt;gc('59b52ac01a31d66...')#3[
    internal function
]: Opencart\System\Library\Session-&gt;gc()#4{
    main
}thrown in<b>/Users/D/php/opencart_aabuy/public/system/library/db/mysqli.php</b> on line <b>64</b><br/>

**Test environment**
 - Local development 
 - Operating system : Mac OS 13.1
 - PHP version: 8.1
 - MYSQL: 10.4.27-MariaDB
 - Apache version: Apache/2.4.54

**Comment by mhcwebdesign** [comment]
OpenCart 4.0.2.1 doesn't use use any of the MySQL spatial functions (https://dev.mysql.com/doc/refman/8.0/en/spatial-convenience-functions.html) . It looks like you are using a 3rd party extension, in which case you should contact its author for help.

**Comment by ZateLabClients** [comment]
@mhcwebdesign 
I just using select statements with some MySQL spatial functions. Why deadlock happens when using SELECT statement.
