### ISSUE TITLE
[master] Affiliate extension type report files missing

### ISSUE THREAD

**Issue by yvonn** [opencart/opencart#12512]
Master version 4.0.2.2

**Describe the bug**
Extensions type: report files are missing

**To Reproduce**
1. Go to 'Extensions/extension type: reports'

These files are missing.
extension/opencart/admin/controller/report/affiliate.php
extension/opencart/admin/language/en-gb/report/affiliate.php
extension/opencart/admin/controller/report/affiliate.php
extension/opencart/admin/view/template/report/affiliate_form.twig

**Comment by danielkerr** [comment]
yes we doont have affliate reports any moroe. they are called customer transactions.
