### ISSUE TITLE
Language File - Mail Order Add

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#12528]
Hello.

Latest version, OpenCart v4.0.2.2.

Text doesn't match payment method Cash on Delivery (COD).

catalog/language/en-gb/mail/order_add.php

Text should be changed from
$_['text_greeting']         = 'Thank you for your interest in %s products. Your order has been received and will be processed **once payment has been confirmed**.';
to
$_['text_greeting']         = 'Thank you for your interest in %s products. Your order has been received and will be processed **as soon as possible**.';

On Cash on Delivery you got money only when customer received the package and payment cannot be confirmed before. Customer will never receive package (OR) misleading text.

**Comment by TheCartpenter** [comment]
I would replace: ```processed``` with: ```reviewed by our staff``` since ```processed``` is also a title that is implicit as an ```order status```.

**Comment by faca5** [comment]
"staff" is never used in language file. Try find better word.

Example: store owner, or just store (or something like that).

Let's wait what other user will suggest.


Or simple version:
Thank you for your interest in %s products. Your order has been received.

Or
Thank you for your interest in %s products. Your order has been received. We will let you know when your order ships


Word "interest" should be replaced - because order has been already placed. This is not esquire.


My suggestion:
Thank you for your **order**. Your order has been received and **will be processed as soon as possible.**


Make as simple as possible. Mail order is very important for each customers. It is confirmation for order.


eBay:
Subject: Order confirmed
Message: Thanks for shopping! Your order is confirmed. 

AliExpress
Subject: Order xxx: order confirmation
Message: Thank you for shopping with us. Your order xxx is confirmed. We'll let you know when your order ships.

Both eBay and AllExpress has mail order as "order is confirmed". It's confirmation of receipt.

**Comment by faca5** [comment]
Text
Thank you for your interest in %s products. Your order has been received and will be processed once payment has been confirmed.

Additional information related to the payment system:
Cash On Delivery - Current text is very confused.
Bank Transfer - Text is Ok.
Instant payment system (PayPal, credit cards, crypto...) - Text is confused because they already received payment.

Simple version:
Thank you for your order. Your order has been received.

**Comment by danielkerr** [comment]
wasting my time
