### ISSUE TITLE
[Master] Able to do a checkout without agreeing to the Privacy Policy

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#12535]
**What version of OpenCart are you reporting this for?**
master branch

**Describe the bug**
You shouldn't be able to do a successful checkout without agreeing to the privacy policy first.

**To Reproduce**
1. Add an item to the shopping cart
2. Do a guest checkout, without having read and agreed to the Privacy Policy

**Expected behavior**
Checkout step 2 (Shipping method, payment method) should only be allowed after having completed checkout step 1 (Personal Details, Shipping Address) including agreeing to the Privacy Policy

**Server / Test environment (please complete the following information):**
 - Local development? yes
 - Operating system: Linux Mint 20.3. (Kernel Linux 6.3.5-060305-generic (x86_64))
 - PHP version: 8.2.8
 - Apache version:  Apache/2.4.41 (Ubuntu) 
 - Browser(s) tested with: Firefox
 - Version: 115.0.2 (64-bit

**Comment by goro-gh** [comment]
Try to change `Checkout Terms` option in:

System > Settings > EditStore > Option > Checkout

**Comment by mhcwebdesign** [comment]
@goro-gh: Thanks for this, enabled it, and it works for the 2nd checkout step (Confirm Order), yet it's still being ignored by the first checkout step (Continue). See attached screenshot.
![Screenshot_2023-08-01_13-58-18](https://github.com/opencart/opencart/assets/2989557/791152be-ef54-4196-8824-c0d991532243)

**Comment by mhcwebdesign** [comment]
Thinking about it: The button at the bottom of the 1st checkout step (labeled **Continue**) should only be enabled once the Privacy Policy has been enabled (depending on the backend setting (ystem > Settings > EditStore > Option > Checkout).

Also, thinks would clearer if the 2nd checkout step (Shipping Method, Payment Method) would be grayed out or invisible until the user has clicked on the **Continue** button. And maybe rename the Continue button to something like **Step 2: Payment and shipping methods**

**Comment by goro-gh** [comment]
The button at the bottom of the 1st checkout step is controlled from 
System > Settings > EditStore > Option > **Account** > Account Terms

You can use NONE there, but it will affect user creation process (page) too.

I personally think that first 2 checkbox
- I wish to subscribe to the it.z0na.bg newsletter.
- I have read and agree to the [Terms & Conditions]

should not be visualized at all for anonymous checkouts.

**Comment by danielkerr** [comment]
yes because u only need to agree to terms if u create an account!

**Comment by danielkerr** [comment]
and i wouldnt use privacy polciy as ur terms for signing up to an account
