### ISSUE TITLE
Case Sensitive URLs

### ISSUE THREAD

**Issue by DaveRiba** [opencart/opencart#12532]
### Discussed in https://github.com/opencart/opencart/discussions/12529

<div type='discussions-op-text'>

<sup>Originally posted by **DaveRiba** July 28, 2023</sup>
I have created a stub HTML page Foo
Created Controller, Language, and Template files all pointing to information/Foo
Somehow it is case sensitive
route=information/Foo fails
route=information/foo works

Problem is I have published information/Foo
Any ideas what OpenCart is doing to require lower case on a URL?
Running 4.0.2.1 in a Windows environment

Thanks
</div>

**Comment by DaveRiba** [comment]
Was there a solution to my question?

Not seeing how to fix the problem

Advise please

 

S. David Riba

ViviLux LED Lights, Magnifiers, Lasers, and more …
Harbor Sales Inc
P O Box 1200
Safety Harbor, FL 34695

727-669-7700

 <http://www.viviluxusa.com/> www.ViviLuxUSA.com   <http://www.harbor-sales.com/> www.Harbor-Sales.com

**Comment by akaunderr** [comment]
While URLs can technically have capital letters, it's generally recommended to use only lowercase letters in URLs. This is because URLs are case sensitive and using uppercase letters in URLs can cause confusion and errors

**Comment by DaveRiba** [comment]
Thanks Andrii

Noted for the future.   However, I have published a mixed case URL which
works everywhere EXCEPT the new 4.0.2.1 version of OpenCart

How can I control it in 4.0.2.x ?

Is there a setting somewhere which defines case requirement?

 

Dave

S. David Riba

ViviLux LED Lights, Magnifiers, Lasers, and more .
Harbor Sales Inc
P O Box 1200
Safety Harbor, FL 34695

727-669-7700

 <http://www.viviluxusa.com/> www.ViviLuxUSA.com
<http://www.harbor-sales.com/> www.Harbor-Sales.com

**Comment by danielkerr** [comment]
its not an issue as lowercase urls are the correct. dont post crap again! and not include advertisments when u post

**Comment by mhcwebdesign** [comment]
URL case sensitive has different aspects to be looked into:

For example, given a URL

```
scheme:[//host[:port]][/]path[?query][#fragment]
 \____________________/\________________________/
        Location                 Data

```
The Location portion is case insensitive, e.g. google.com is the same as Google.Com

The Data portion usually is case sensitive. This has historic reasons. E.g. the path often maps to folders on the server with case-sensitive lookups on Linux/Unix-based webservers (unlike e.g. Windows IIS). The query portion should be case-sensitive, too. However, something like ?route=sale/order/createInvoiceNo refers to the PHP function **createInvoiceNo**, and unusually enough for a programming language, function names are case-insensitive in PHP (unlike e.g. constants or variables). Still, IMHO opinion all of the URL's Data portion should always be treated as case-sensitve!

**Comment by mhcwebdesign** [comment]
@ DaveRiba : Is Foo a class name? 

In PHP, most things are case-insensitive (except for variables and constants), including class names  However, the URL's Data portion should be treated as case-sensitive, and it is a good practice to treat PHP method- and class-names as case-sensitive, too (even though they aren't in PHP).

**Comment by DaveRiba** [comment]
Sorry, was not clear.  Foo is an HTML stub page.  
Defined as an HTML module extension, with associated Controller, Language, and View pages.  Used to work under 3.x
Essentially want to surface an HTML page named Foo (or whatever) which is located in the information subdirectory

**Comment by danielkerr** [comment]
Im following the w3c URL spec not ur Hubble opinion

**Comment by mhcwebdesign** [comment]
@Daniel: According to the W3C standard at https://www.w3.org/TR/WD-html40-970708/htmlweb.html:

```
URLs typically consist of three pieces:

    The name of the protocol used to transfer the resource over the Web.
    The name of the machine hosting the resource.
    The name of the resource itself, given as a path. 

Consider the URL that designates the current HTML specification:

http://www.w3.org/TR/WD-html4/cover.html

This URL may be read as follows: Use the [HTTP](https://www.w3.org/TR/WD-html40-970708/htmlweb.html#htmlhttp) protocol to transfer the data residing on the machine www.w3.org in the file /TR/WD-html4/cover.html

URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive.

```

And according to the docs at https://www.rfc-editor.org/rfc/rfc3986#page-40:

```
   ... the scheme and
   host are case-insensitive and therefore should be normalized to
   lowercase.  For example, the URI <HTTP://www.EXAMPLE.com/> is
   equivalent to <http://www.example.com/>.  The other generic syntax
   components are assumed to be case-sensitive unless specifically
   defined otherwise by the scheme (see Section 6.2.3).
```

So that means that e.g. https://www.example.com/en-gb/Product/Smartphone/hTC-touch-hd should result in a 404 error (Opencart currently wrongly accepts it), whereas only https://www.example.com/en-gb/product/smartphone/htc-touch-hd ought to return the correct page.

**Comment by danielkerr** [comment]
Why don't u teach ur grandma to suck eggs
