### ISSUE TITLE
[4.0.2.2] Wrong SEO Urls

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#12542]
**What version of OpenCart are you reporting this for?**
4.0.2.2

**Describe the bug**
After enabling the SEO urls, the frontend page for Canon EOS 5D product has the wrong SEO URL:

/en-gb/product/canon-eos-5d/cameras

It should have been:

/en-gb/product/cameras/canon-eos-5d

**Server / Test environment (please complete the following information):**
 - Local development? Local host on a Linux Mint 20.3 (Kernel 6.3.15)
 - PHP version: 8.2.8
 - Apache version: Apache/2.4.41 (Ubuntu) 
 - Browser(s) tested with: Firefox 116.0 (64-bit)

**Comment by danielkerr** [comment]
it doesernt matter u are not selling the default products
