### ISSUE TITLE
[master] SEO entries with additional language(s) in general

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12593]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

**This is not a real bug!!!**
only a question of concept.

In the old versions 3.x the shop owner had to enter a SEO entry **only for English** and it was working ... and also saved the data.
In the new version 4 it is **required to enter for each language** (category, product, ....) a SEO word.

I have customers with more than 17.000 products and up to 4 languages. 
Do we have an easier solution to support these customers instead of doing this job manually by hand?

**Expected behavior**
Solution A: It is working like in the old versions.
Solution B: During the upgrade process the SEO entries get created automatically.

I would prefer Solution A

Sorry for disturbing.

**Comment by danielkerr** [comment]
yes will add seo entry created for new languages
