### ISSUE TITLE
No send email for reset admin password

### ISSUE THREAD

**Issue by kliver50** [opencart/opencart#12615]
**What version of OpenCart are you reporting this for?**
OpenCart 4.0.2.2

**Describe the bug**
Not send email for reset admin password

**To Reproduce**
1. Go to /admin
2. Click on 'Forgotten password'
3. Enter email and click 'Reset'
4. Show message "An email with a confirmation link has been sent your admin email address."
5. Email not exist in mailbox and not traffic to mail server
6. For customer reset password work fine and email sent.

**Error in /admin/controller/mail/forgotten.php**
```
@@ -21,7 +21,7 @@
 			$code = '';
 		}
 
-		if ($email && $code && ($route == 'common/forgotten.reset') && filter_var($email, FILTER_VALIDATE_EMAIL)) {
+		if ($email && $code && ($route == 'common/forgotten.confirm') && filter_var($email, FILTER_VALIDATE_EMAIL)) {
 			$this->load->language('mail/forgotten');
 
 			$store_name = html_entity_decode($this->config->get('config_name'), ENT_QUOTES, 'UTF-8');

```

**Comment by bofa26** [comment]
what have you done so far

**Comment by kliver50** [comment]
@danielkerr The problem has not yet been resolved after [https://github.com/opencart/opencart/issues/12615](https://github.com/opencart/opencart/commit/e42ea60631649e0b36aa6c4a38a532ea958d7738)

**Comment by danielkerr** [comment]
It has because forgotten password won't work until there is mail settings added

**Comment by kliver50** [comment]
> It has because forgotten password won't work until there is mail settings added

Mail server settings and account data  in opencart is configured. For admin email address added.
Messages to customers are sent normally, that is, email is configured correctly

Email to admin with link to reset password is not sent. After modification file /admin/controller/mail/forgotten.php email sending work
