### ISSUE TITLE
HTML Content in 4.0.2.2

### ISSUE THREAD

**Issue by DaveRiba** [opencart/opencart#12634]
Is anyone getting the HTML Content module extension in 4.0.2.2 to work?
None of my HTML content from 3.0.6 is surfacing in OC4
The page paints, the header pulls correctly, the content is blank.
No errors in the log.
Multiple pages of HTML content that all worked in 3x  - none of them surface in 4x.
Is this a bug? or something else?

Thanks for any and all constructive assistance

**Comment by DaveRiba** [comment]
Thanks
Did all that.  Still not working in 4.0.2.2
However, do you confirm that HTML Content surfaces correctly in 4.0.2.2 ????
You have tested it and not just assuming?

**Comment by danielkerr** [comment]
it works just tested it. i think the issue is that the left and right columns disappear when in mobile mode

**Comment by DaveRiba** [comment]
Thank you Daniel.

 

Good thing is html module works.  Bad thing is I still can’t get it to serve up a page

It’s a simple page, center section, no side columns.

Had not even thought about trying it on a mobile device.

No joy. Doesn’t serve the page on desktop or mobile.

I have had some good pointers, and still working my way thru configurations.

Appreciate the help

 

Dave

**Comment by DaveRiba** [comment]
Thank you Daniel

**Comment by danielkerr** [comment]
it works

https://github.com/opencart/opencart/assets/5079756/eeb45554-36c5-47eb-851d-66fc7350be1c

**Comment by danielkerr** [comment]
maybe re save ur extension settings
