### ISSUE TITLE
Apple devices lose products placed in the cart

### ISSUE THREAD

**Issue by DaveRiba** [opencart/opencart#12635]
**What version of OpenCart are you reporting this for?**
4.0.2.2
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Customers trying to order using Apple devices (Mac / Safari, iPhones, etc) report they place items into the cart, receive acknowledgement the item was placed in the cart, and the cart is empty.  Multiple users, using different Apple devices all report the same behavior.  Non-Apple devices (Android, Windows, etc) report no problem.  The cart works correctly

**To Reproduce**

Using an Apple browser (Safari, iPhone,etc), place any item in the cart. Cart shows X items in the cart. Go to cart. Nothing there.  NO ERRORS in the error log

**Expected behavior**
Cart should keep the items instead of being empty.  

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app
NA
**Server / Test environment (please complete the following information):*
https://harbor-sales.com
 - Local development? Deployed to a web server? Deployed
 - Operating system Windows NT S05D07R47 10.0 build 17763 (Windows Server 2019) AMD64 
 - PHP version   API20210902,NTS,VS16 
 - Apache version  NA
 - Browser(s) tested with [e.g. chrome, safari - if applicable]
 - Version [e.g. 22] 4.0.2.2

**Additional context**

**Comment by danielkerr** [comment]
u need to allow cookies

**Comment by DaveRiba** [comment]
Cookies are enabled, so that is not the issue

If there is another solution, please advise.

 

Please reopen this case.  If it is a bug it needs to be addressed

We can’t have 50% of OpenCart customers not being able to place orders.

 

Dave

**Comment by danielkerr** [comment]
Anyone else have this issue?

**Comment by danielkerr** [comment]
Maybe because ur hosting on windows

**Comment by DaveRiba** [comment]
Daniel, possibly but I can't be your only customer using a Windows environment. Not as popular as Unix, but better than Apple.  Regardless if it's a bug it needs to be fixed or there needs to be a disclaimer that OpenCart doesn't work on a Windows server.  

I would hazard an uneducated guess -- could it be a misplaced pointer?  Opening the cart itself opens a different cart than the one the user is putting things into ??  User puts things in Bucket A, and tries to retrieve them from Bucket B, which is empty.
I have seen that before in other software.  
Frustrating part about this problem -- the logs are clean, so no error is being reported.
Regardless, at least for my application, this is a critical issue.
Appreciate your help.

**Comment by pemaier** [comment]
If you like you can use my system (yesterday installed) for testing with your Apple browser.
Data is in issue #12459

**Comment by IP-CAM** [comment]
https://20848.aqq.ru/service/tool/php_info.php
Warning: Potential Security Risk Ahead

Mypal detected a potential security threat and did not continue to 20848.aqq.ru. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

**Comment by DaveRiba** [comment]
Thanks for the heads-up IP-CAM

**Comment by danielkerr** [comment]
im not hear to fix ur issues because u dont know how to confugure a web  host. no on e else is reporting this stupidiy. 

ip-cam looks like u are posting spam.

**Comment by danielkerr** [comment]
im nopt playing fucking guessing games either! i dont know if u havbe fucked up cloudflare premissions or what. im not bothered. u problem  solve an issue only happening to u.

**Comment by DaveRiba** [comment]
Thanks Daniel for your support

I don’t know if it is only me – that is why I posted the question. Not asking you to fix my problems, but if there is a bug in YOUR software it should be fixed or a disclaimer that your software only works on Unix operating systems. 

I really am trying to support OpenCart, and have chosen it over several more popular competitors. Maybe I made the wrong choice. 

I know you are too busy to deal with little people like customers, but maybe someone on GitHub might have some constructive ideas on how to solve a very real problem with your software.

As always, constructive suggestions appreciated.

**Comment by pemaier** [comment]
@IP-CAM Very clever ... what kind of information you can steal if you do not need to login? It's only a system info.

But if no one need it I'll close it.

**Comment by danielkerr** [comment]
IP cam gave u the answer. Ur site has security issue. Stop bothering people

**Comment by pemaier** [comment]
@danielkerr 
The site with the test installation I published is with SSL and has NO security issues! 
And the server information page I published (php_info what I normally not publish) is only without SSL certificate. 
If you see this as security issue ...
