### ISSUE TITLE
Missing table

### ISSUE THREAD

**Issue by alixcio** [opencart/opencart#12638]
Hi,
It seems that table "oc_subscription_transaction" doesn't exist, message below :

Exception:  Error: Table 'oc_subscription_transaction' doesn't exist<br/>Error No: 1146<br/>SELECT COUNT(DISTINCT `s`.`customer_id`) AS `total` FROM `oc_subscription_transaction` st LEFT JOIN `oc_subscription` s ON (st.`subscription_id` = `s`.`subscription_id`) LEFT JOIN `oc_customer` c ON (`s`.`customer_id` = c.`customer_id`)

Thanks

**Comment by danielkerr** [comment]
subscription are still being worked on

https://github.com/opencart/opencart/issues/11458
