### ISSUE TITLE
Option value is trimmed while ordering

### ISSUE THREAD

**Issue by ZateLabClients** [opencart/opencart#12639]
Version: Master branch

When ordering a product with option value has a larger text value. When order completes, the value gets trimmed.
In file: upload/catalog/model/checkout/cart.php:
`(oc_strlen($value) > 20 ? oc_substr($value, 0, 20) . '..' : $value)`
This is the line causes the issue.

Another related issue:
When order with file upload, File name is saved instead of file code in "order_option" table.

**Comment by danielkerr** [comment]
it shows fine in the admin

**Comment by ZateLabClients** [comment]
> it shows fine in the admin

Bug exist. I will share the screenshort tommorow. 
In:  **upload/catalog/controller/checkout/confirm.php** 
which calls **$this->model_checkout_cart->getProducts()**; controller.
this controller contain code:
`(oc_strlen($value) > 20 ? oc_substr($value, 0, 20) . '..' : $value)`
This line of code is making the issue that the option value is trimmed


Hope u understand the bug.
