### ISSUE TITLE
Minimum order quantity by product

### ISSUE THREAD

**Issue by alixcio** [opencart/opencart#12641]
**What version of OpenCart are you reporting this for?**
4.0.2.2

**Describe the bug**
When we define a minimum order quantity by product, on the shopping cart page we cannot continue what is normal. However, no message is displayed.

![Image1](https://github.com/opencart/opencart/assets/142814732/08980583-3393-4c12-9673-11a62150f0a0)
![Image2](https://github.com/opencart/opencart/assets/142814732/8f239f73-f5af-4897-a6b5-437d8c08abda)

**Comment by danielkerr** [comment]
it normally diosplays an error message. maytbe u messed it up with thte template

**Comment by batolero** [comment]
I am also having the same problem. Version 4.0.2.3.

I looked at my previous opencart installed locally on my PC, version 3.0.3.2, and the error message is working. But in the latest version, it is not working.
