### ISSUE TITLE
Order Status dont show 

### ISSUE THREAD

**Issue by muhammetfaik** [opencart/opencart#12656]
I have order status in my sql but dont show order status opencart engine.What's the problem.
![Screenshot from 2023-08-29 16-03-52](https://github.com/opencart/opencart/assets/15978174/c295cb52-c37e-4c1a-bab5-7a8d7a3349df)
![Screenshot from 2023-08-29 16-04-07](https://github.com/opencart/opencart/assets/15978174/d3ca68cb-9a45-4593-854d-41dd2f339a23)

**Comment by pashast** [comment]
> where is admin cookies

https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop

**Comment by muhammetfaik** [comment]
No dont work I open server in firefox and chorome but dont work I think Problem is in server.What do you think ?

**Comment by muhammetfaik** [comment]
I use godaddy cpanel server.
