### ISSUE TITLE
Autocomplete fields bug on Safari

### ISSUE THREAD

**Issue by HostOncilla** [opencart/opencart#12652]
I'm using OC 4.0.2.3, fresh installation as of 28th of August 2023. There's a bug where any of the autocomplete fields in the admin section doesn't select any of the choice options on Safari, desktop or mobile. It works on Mozilla and Chrome, but not Safari. 

I found to solve the problem, commenting out the line round 452
![image](https://github.com/opencart/opencart/assets/8054786/bfaa65d8-2d12-4e77-910e-c1226b184d9c)

I noticed problems is only in the Safari browser, everything works in Mozilla.

for some reason in the Safari browser, the class show, it is deleted earlier than the choice is made.

**Comment by danielkerr** [comment]
yes but will not close the drop down now

**Comment by danielkerr** [comment]
can we confirm if my fix worked?

**Comment by twojtyniak** [comment]
Is this going to get a permanent fix? Still present in 4.1.0.3. Very frustrating for a new user, even one with development experience.

**Comment by twojtyniak** [comment]
@stalker780 Thanks! That seems to work. Is there anything I can do to help get the fix into future releases? It's a shame to have people be frustrated and give up on OC for something easily fixed.
