### ISSUE TITLE
How to apply db_schema in existing mysql db

### ISSUE THREAD

**Issue by ZateLabClients** [opencart/opencart#12664]
version of OpenCart: Master branch

I can see the db schema changes in: `upload/system/helper/db_schema.php`.
How can apply the changes in my current mysql.

Do i need to apply each changes manually??
Is there any simpler methods (or build in methods in OC) to do this?

I need my mysql uptodate with  master branch.

Can anyone help me.

**Comment by ZateLabClients** [comment]
After every changes in ` oc_db_schema.php` , if i run `upload/install/controller/upgrade/upgrade_3.php` , will it update the existing mysql **correctly**. 

@danielkerr What is the actuall need of `upgrade_3.php`

**Comment by danielkerr** [comment]
It should run through the dB update it's Delft.if u go to upgrade

**Comment by ZateLabClients** [comment]
@danielkerr 
But i need to work with master branch. Currently `blog` section is included in latest Master OC. But its tables are needed to add to my mysql DB.

Actually i need a solution for all `oc_db_schema` changes that will happen in future. 
If i run `upgrade_3.php` manually, will it alter the database perfectly.?

**Comment by danielkerr** [comment]
go to www.yourdomain.com/install/

**Comment by danielkerr** [comment]
u need to run through all upgrade scripts.
