### ISSUE TITLE
Error displaying bug guest shipping

### ISSUE THREAD

**Issue by SirStepheno** [opencart/opencart#12665]
**What version of OpenCart are you reporting this for?**
3.0.3.8 maintained

**Describe the bug**
Just a small bug
When a error in the guest shipping occurs, only a part of the div turns red, the message shows up etc. When you correct the error, the error message disappears, but the red border (has-error class) doesn't disappear.

**To Reproduce**
Checkout as a guest, fill in a wrong value for one of the inputs in the shipping address section and correct it.

**Expected behavior**
The has-error class should disappear and the red accent around the input field should turn back to black.

**Screenshots / Screen recordings**
Creating errors:
![image](https://github.com/opencart/opencart/assets/62992499/4ed8907a-deeb-4dd3-9383-255f35e13ba8)
Fixing errors:
![image](https://github.com/opencart/opencart/assets/62992499/3d73f030-0a74-4a0f-acb9-df8c3096641c)

**Additional context**
I think I found the problem:

The guest shipping (guest_shipping.twig) has a extra div around the input:
```
  <div class="form-group">
    <label class="col-sm-2 control-label" for="input-shipping-company">{{ entry_company }}</label>
    <div class="col-sm-10">
      <input type="text" name="company" value="{{ company }}" placeholder="{{ entry_company }}" id="input-shipping-company" class="form-control" />
    </div>
  </div>
```

While in checkout.twig the JS function turns the parent red (line 690):
```
// Highlight any found errors
$('.text-danger').parent().addClass('has-error');
```

But this is only the col-sm-10 div, so it explains why the label doesn't turn red.

Later on, while not submitting the wrong information:
```
$('.alert-dismissible, .text-danger').remove();
$('.form-group').removeClass('has-error');
```

So the warning text disappears, but the red color doesn't. Because the div form-group didn't have the class "has-error" but the child div has.

**Simple fix**

Just rewrite the JS line from above to:
```
// Highlight any found errors
$('.text-danger').parent().parent().addClass('has-error');
```

**Comment by danielkerr** [comment]
3.0.3.8 maintained has a different branch.
