### ISSUE TITLE
[master] Order edit - Order data change/not change at refresh/confirm

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12661]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
the order data is changed in part (store) it should not change and it not changes in parts (language, currency) it should change.

**To Reproduce**
1. Go to 'setup an additional store'
2. Prepare the category and product settings
3. Login to new store and order a product
4. Go to back end sales
5. Open the order and change the currency
6. press refresh and confirm
7. close the order and reopen it again
8. see the error

**Expected behavior**
Correct data should be saved

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app
[order-edit-store-language-curreny-change.webm](https://github.com/opencart/opencart/assets/10166095/8f06ad1b-e85a-4241-8347-e8e55e60d6f4)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 116.0

**Comment by danielkerr** [comment]
the issue is people complain when the order totals arte changed after saving

**Comment by pemaier** [comment]
If it is not allowed for the shop owner to change Store Language and Currency then 
a) it should not be possible for editing in the administration area
(what I really not like as shop owner because then I have to delete the order and create a new order ... that response we really don't like)
b) it should be a configuration setting so the shop owner can decide what he need

I guess it only affects automatic payment/refund systems like PayPal... what we already had in the older OpenCart versions. So variant b) is a good compromise and a clear process for all shop owners.

**Comment by danielkerr** [comment]
i think i need to redo how api calls are made to create orders.

**Comment by danielkerr** [comment]
finally got the order editor working correctly

**Comment by danielkerr** [comment]
just finishing up soome minor stuff.

**Comment by pemaier** [comment]
Thank you very very much ... Is it ok to start testing in 2 days (invoice. language, currency) or should I wait a bit longer?

**Comment by pemaier** [comment]
I tested to change the currency of an order from $ to EUR ... that's working as before also. Saving the order with the new currency and printing an invoice with the new currency is **not working** with the version of today.
