### ISSUE TITLE
Categories not listing in Admin Categories Page

### ISSUE THREAD

**Issue by erkinaka** [opencart/opencart#12667]
**What version of OpenCart are you reporting this for?**
Opencart 4.0.2.2

**Describe the bug**
Problem 1
In Admin panel Catalog-Categories
I have installed opencart 4.0.2.2 with sample data but no categories listed in categories page.
I cretaed new categories but they are not listed also. Images are attached. 

Catalog->Categories : Categories list is empty but page count at the bottom is 4

Catalog->Categories->Add Category : After adding new category, it is being created but not listing in categories list. Database's Categories table has the new category and it is also being showed in top menu but not listing in the categories list in admin panel.

Problem 2
When i was creating a new product, categories are not shown in the form field 

**Screenshots / Screen recordings**

![cat1](https://github.com/opencart/opencart/assets/5435855/29667487-ef6b-44eb-900e-5ced14ef4935)
![cat2](https://github.com/opencart/opencart/assets/5435855/20ed418c-7307-4961-93a7-01cd93ed6344)

**Server / Test environment (please complete the following information):**
 - Deployed Web Server
 - Linux Kernel 3.10.0-1160.el7.x86_64
 - PHP version 8.2
 - Apache version 2.4.57
 - Browser(s) Chrome

**Comment by mhcwebdesign** [comment]
Unable to reproduce your error. Besides, please be more specific, there is no version 4.0.2 of OpenCart, are you using 4.0.2.2?

**Comment by pemaier** [comment]
@erkinaka 
Check it the categories are in the database ... if yes clear your cache.
Else make a new install.

**Comment by erkinaka** [comment]
> Unable to reproduce your error. Besides, please be more specific, there is no version 4.0.2 of OpenCart, are you using 4.0.2.2?
Hi @mhcwebdesign, i edited my post. i hope, it is clear now.

**Comment by erkinaka** [comment]
> if yes clear your cache

İ tried several installation but ihave the same problem. But now i tried a new installation and there is no problem. Thanks.
