### ISSUE TITLE
Breaking changes for payment extensions as of 4.0.2.0+

### ISSUE THREAD

**Issue by ndeet** [opencart/opencart#12675]
**What version of OpenCart are you reporting this for?**
4.0.2.2

**Describe the bug**
The mentioned changes to how payment methods work on the release notes of 4.0.2.0 are not the whole story and more changes are needed to make payment method extensions work.

Beside the updated structure of the payment methods array thankfully described in the release notes here https://github.com/opencart/opencart/releases/tag/4.0.2.0 the following also changed.

1. in your extensions /EXT/catalog/model/payment/EXT.php you need to replace `getMethod()` with `getMethods()`. #12314

2. the previously available array keys of `country_id` and `zone_id` are now also gone/undefined, so you need to do a complicated check for them. Not sure if this is unintended or not, should they be available or have they been removed completely? Can anybody confirm?

This costs needlessly a lot of time for extension maintainers and for you OC maintainers when issues hit. Not sure why there has to be a breaking change in a patch release, would appreciate if it would be at least a feature release like 4.1.0.0 and a more complete description of the breaking changes. If you follow SemVer it would be a major release because of a breaking api change.

**Comment by danielkerr** [comment]
he previously available array keys of country_id and zone_id are still there.
