### ISSUE TITLE
Orders - products with options bug

### ISSUE THREAD

**Issue by martinbradshaw** [opencart/opencart#12678]
**What version of OpenCart are you reporting this for?**
4.0.2.2
**Describe the bug**
on an order in admin, any product which has options doubles in price when the confirm button is pressed - products without options unaffected.

What section does it affect?
orders

**To Reproduce**
create an order either in front or back end add a product with options.
goto admin/orders
press confirm
see the product with options double or tripple in price.

**Server / Test environment (please complete the following information):**
 - Local development? webserver
 - Operating system linux
 - PHP version
 - Apache version
 - Browser(s) tested with chrome and edge

**Additional context**

pressing confirm permanantly doubles the price and has to be deleted from the order to resolve, pressing refresh button doubles price on option products but can be resset by pressing f5

**Comment by danielkerr** [comment]
already fixed in master
