### ISSUE TITLE
Blog objects naming

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#12674]
@danielkerr, it's great to see the Blog implementation in OC finally.

But I find naming of classes and entities confusing.

Why article entities are called `blog`? You don't name `product` entity as `shop`, aren't you?
`blog_category` also looks too long and can be confused with product `category`.
Why not name them `article` and `topic` ?

Catalog
- Categories
- Products
- Manufacturers
- Reviews

Blog or CMS
- Topics
- Articles
- Authors
- Comments

A nice and simple implementation of Blog functionality was proposed earlier.
https://github.com/opencart/opencart/pull/12507
It may need some modifications, but it looks quite clear and functional.

**Comment by danielkerr** [comment]
good point
