### ISSUE TITLE
customer order histories, pagination not working

### ISSUE THREAD

**Issue by ZateLabClients** [opencart/opencart#12677]
Version: Master branch

**Describe the bug**
1. Customer can see all order histories including notify-customer=false.
2. Pagination not working when customer see the order histories.

**To Reproduce**
1. create a order
2. add 15 order histories
3. add 1 order history with notify=false
4. login the customer account, so we can see pagination is not working & we can see including notify-customer=false.

**Comment by danielkerr** [comment]
just tested and works fine
