### ISSUE TITLE
Maintenance version of 3038 not working with other themes, or cookie warning plugins

### ISSUE THREAD

**Issue by LIBERTY-UK** [opencart/opencart#12685]
**What version of OpenCart are you reporting this for?**
3038 Maintenance Edition

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

When using themes OTHER than the standard Opencart Theme,  Carousels and sliders become inoperative.  Also ANY cookie warning plugin fails to operate.  This has been tried with a multitude of other themes, with the same result.

This does NOT happen with the regular 3038 version, but ONLY with the maintenance version.  

Have tried this extensively on both pc based localhost and live servers.

The specific skin I wanted to use was zBaby, but NONE of the non standard themes will work with the maintenance version.

I hate Opencart 4, so specifically want to stick with v3.0.3.8 but being able to use PHP 8 (if needed) is a big plus point, so am hoping this is a straightforward fix.

**Comment by mhcwebdesign** [comment]
First of all, the zBaby theme doesn't even support OpenCart versions greater than 3.0.2.0.

The zBaby theme, in its file at **catalog/view/theme/zBaby/template/common/header.twig**, needs this replacement:

old line:
`<script src="catalog/view/javascript/jquery/jquery-2.1.1.min.js" type="text/javascript"></script>`

new line:
`<script src="catalog/view/javascript/jquery/jquery-3.7.0.min.js" type="text/javascript"></script>`
