### ISSUE TITLE
Opencart's password hashing is vulnerable

### ISSUE THREAD

**Issue by Ayrx** [opencart/opencart#1269]
From `admin/model/user/user.php`:

``` php
    public function editPassword($user_id, $password) {
        $this->db->query("UPDATE `" . DB_PREFIX . "user` SET salt = '" . $this->db->escape($salt = substr(md5(uniqid(rand(), true)), 0, 9)) . "', password = '" . $this->db->escape(sha1($salt . sha1($salt . sha1($password)))) . "', code = '' WHERE user_id = '" . (int)$user_id . "'");
    }
```

There are several things wrong with this line of code.
1. `rand()` is not an appropriate way to generate salts. According to [PHP.net](http://php.net/rand), `rand()` **is not** cryptographically secure way to generate random values. Salts _have_ to be globally unique and using a good CSPRNG is the best way to achieve this.
2. Three iterations of `SHA1` is most definitely not a good password hashing algorithm. This will fall _very_ quickly to GPU-wielding attackers.
##### Recommendations:
1. _Please_ read [How to securely hash passwords?](http://security.stackexchange.com/a/31846/10211) for password hashing best practices.
2. Use `bcrypt`. In PHP 5.5 and above, this can easily be done using [`password_hash()`](http://www.php.net/manual/en/function.password-hash.php). For older PHP versions, there is the excellent [phpass](http://www.openwall.com/phpass/) library.
3. `admin/model/user/user.php` is not the only part of the code that suffers from this vulnerability. I noticed the same problem in `system/library/customer.php`.

Does opencart have a way to be contacted privately for security issues? I would prefer not to open an issue publicly in the future especially for more high-risk bugs.

**Comment by kholia** [comment]
Apologies for resurrecting an old topic but here are some hash cracking numbers,

https://github.com/magnumripper/JohnTheRipper/wiki/Cracking-OpenCart-hashes-with-JtR
