### ISSUE TITLE
[4.0.2.3] The "Upgrade" function fails because it looks for the "storage" directory in the /system/ directory

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#12697]
When you try to run the Upgrade function, it fails with this error:

`Warning: require_once(/system/storage/vendor/aws/aws-sdk-php/src/functions.php): Failed to open stream: No such file or directory in /system/vendor.php on line 6
`

Based on my tests, this happens because the installer tries to find the "storage" directory in the /system/ directory. However, since OpenCart asks you to move that directory when you first install it, it no longer exists when an upgrade takes place. 

I'm not exactly sure of the best way to handle this, but it needs to be fixed for the Upgrade function to work. There are a couple of options I can think of:

1. Copy the "storage" directory when moving it, instead of just moving it. However, this may cause issues if a user manually deletes the directory (to avoid confusion over its location) so it's probably not the best option.

2. Avoid loading the vendor directory when running the install process. I'm not sure how hard this would be.

3. Copy the DIR_STORAGE constant from the main /config.php file into the /install/cli_install.php and /install/index.php files.

I haven't tested any of those, so I'm not sure if they're feasible or not. Hopefully you have more insight into how to fix the problem.

**Comment by ClearThinking** [comment]
It turns out there's a free extension by MaxD that fixes this, and he says in the files that you can use his changes:

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=45216

**Comment by danielkerr** [comment]
this code make sure this issue does noot happen

					// We need to store the path differently for vendor folders.
					if (substr($destination, 0, 15) == 'system/storage/') {
						$path = substr($destination, 15);
						$base = DIR_STORAGE;
						$prefix = 'system/storage/';
					}
