### ISSUE TITLE
[4.0.2.3] Statuses missing after clean install

### ISSUE THREAD

**Issue by PaulBogdanCom** [opencart/opencart#12701]
PHP 8.1
Official OC 4.0.2.3
After clear install there are no statuses ( stock, order, categories, etc, nothing ) in the list but in the database are all visible
language_id=1

[https://ibb.co/5rsftKv](list)
[https://ibb.co/qFZm0wn](database)
[https://ibb.co/dcg1BQ1](categories)

**Comment by mhcwebdesign** [comment]
Sorry, but yours is not a clear install, your DB table oc_stock_status has extra entries. Unless you can provide more details of what other extensions you have installed, and exactly what else you have done, nobody will be able to help you, or replicate this issue.

**Comment by PaulBogdanCom** [comment]
It is a clean install, showing more just because i did try to add, it ads to database ehen i save but does not display any of them

**Comment by mhcwebdesign** [comment]
I am unable to reproduce your error, adding more stock statuses works just fine.
Look, you really have to provide more details, because nobody else can reproduce it.

**Comment by pemaier** [comment]
Clean your cache before you start the install process

**Comment by ClearThinking** [comment]
I just installed a refresh 4.0.2.3 installation and this issue did not happen, so it's specific to you. I did install on PHP 8.0 so it's possible 8.1 is the cause, but I doubt it. Maybe try re-installing again?

**Comment by pemaier** [comment]
So I tried to reproduce the error ... and I got it.
The basic install process is working fine and the db-entries (different stati, weight and length, ..) are present.
Then the 1st login as admin starts the security process.
- Delete the install files
- define storage
- move admin files
- then you have to login again. After this the entries are missing in the admin.

Then have a look into the db - **there are the entries present!**

**Comment by ClearThinking** [comment]
I just tested it again using the exact same process you described, and it works fine for me. I'm guessing it's related to PHP 8.2 --- that's not officially supported by OpenCart, so I would recommend trying 8.1 or 8.0. 

However, if refreshing the cache fixed it for you, then it's probably something specific to your browser configuration. I haven't heard of others experiencing this, but sometimes browsers are very aggressive with their caching, so it can happen. This is why the Upgrade page tells you to hard-refresh your cache (but the installation page doesn't --- maybe it should).

**Comment by PaulBogdanCom** [comment]
So it seems if you install on PHP 8.2 and change to PHP 8.1 the cache is saved and you need to clear the entire browser cache to get the data, and that makes no sense.
That information should be rewriten if you just clear the website cache, not needing a full browser wipe

**Comment by mhcwebdesign** [comment]
@ClearThinking: OpenCart 4.0.2.3 supports PHP 8.2 just fine, I use the latter all the time.

**Comment by ClearThinking** [comment]
Good to know --- I thought I remember people reporting issues, but maybe that was on the first 4.0 release. I'll keep it in mind for the future.

**Comment by pemaier** [comment]
To be concrete what causes the problem.
If you delete in the OpenCart session cookie the language entry it is working well.
![image](https://github.com/opencart/opencart/assets/10166095/b9148d50-807b-42cf-b6e9-736e1d020219)

I was working with the German language today so my session cookie was having the value de-de.
If I only work with English language my installation is without any problem and all entries are visible.

**Comment by ADDCreative** [comment]
The issue looks to be that if the language cookie is set to something that doesn't match a language in the database, then config_language_id doesn't get set in admin/controller/startup/language.php.
