### ISSUE TITLE
[4.0.2.3] SEO Urls settings (Product and Category URL's)

### ISSUE THREAD

**Issue by SewesLR** [opencart/opencart#12702]
Having the following issue with Opencart 4:

When enabling seo urls in the admin settings for products and categories, it does not provide the seo url of that specific category or product url.

The apache mod_rewrite has been enabled and the .htaccess file is being used. The apache2 server setup is also correct according to documentation.

For example:

From: https://your-domain.co.za/?route=product/category&path=72
To: https://your-domain.co.za/photographic-printings/?route=product/category

It must be https://your-domain.co.za/photographic-printings/

Anyone else with the same problem that can assist

**Comment by chongshengdz** [comment]
you must have deleted your route product/category in your oc_seo_url table
