### ISSUE TITLE
[4.0.2.2] Upgrade is looking for storage in the wrong place

### ISSUE THREAD

**Issue by PaulBogdanCom** [opencart/opencart#12700]
The upgrade after it downloads the install folder should load the storage from config.php not from its own place.
Once you move storage, the new update looks for **storage/vendor/aws/aws-sdk-php/src/functions.php** but that file is already in a new place because of the "security".

**Comment by ClearThinking** [comment]
This is already reported here:

https://github.com/opencart/opencart/issues/12697
