### ISSUE TITLE
Problem with subcategory name, description and breadcrumb

### ISSUE THREAD

**Issue by batumibiz** [opencart/opencart#12718]
**OC version: master branch on 24.09.2023**

Problem with subcategory name, description and breadcrumb

**To Reproduce**
1. Add some category with any description
2. Add another category with any description and assign the above created category as its parent.
3. On frontend, go to above created category->subcategory.

Look at subcategory name, description and breadcrumb.  
**The information is incorrect** and is displayed **from the parent category instead of the current subcategory**.

The problem is in the file [/catalog/controller/product/category.php](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/product/category.php)
On 05.09.2023 there was some strange commit that disrupted the normal operation of this file.  
If you roll back the changes made by this commit, the problem disappears and the subcategories are displayed normally.

**Comment by maximus15102006** [comment]
Thank you, it helped a lot!
