### ISSUE TITLE
SQL Error No: 1064

### ISSUE THREAD

**Issue by mehtaman** [opencart/opencart#12754]
**What version of OpenCart are you reporting this for?**
4.0.2.3

**Describe the bug**
Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'p.`status` = '1' AND p.quantity > 0 ORDER BY sp.`sort_order` ASC' at line 2

Error No: 1064

SELECT * FROM `jmgu_product_subscription` ps LEFT JOIN `jmgu_subscription_plan` sp ON (ps.`subscription_plan_id` = sp.`subscription_plan_id`) LEFT JOIN `jmgu_subscription_plan_description` spd ON (sp.`subscription_plan_id` = spd.`subscription_plan_id`) WHERE ps.`product_id` = '2092' AND ps.`customer_group_id` = '1' AND spd.`language_id` = '1' AND s p.`status` = '1' AND p.quantity > 0 ORDER BY sp.`sort_order` ASC

**To Reproduce**
1. Go to any product on the website

**Expected behavior**
Load product page

**Server / Test environment (please complete the following information):**
 - Hostinger
 - Linux
 - 8.2
 - ?
 - Chrome / FireFox / Edge
 - Latest

**Additional context**
Please help, site is no good at the moment. 
No changes made recently other than product uploads.

Site:
www.it-me-up.co.uk

**Comment by mehtaman** [comment]
I think a long time ago I added some code to hide items that are out of stock.
I cannot remember where I entered this code but "p.status = '1' AND p.quantity > 0 ORDER BY" looks familiar

**Comment by ADDCreative** [comment]
You would be best posting on https://forum.opencart.com/ for help.

**Comment by danielkerr** [comment]
subscription dooes noot wrk. dont add subscription products. its in progress and should be ready oon next release
