### ISSUE TITLE
Why is there no official docker file for Opencart?

### ISSUE THREAD

**Issue by fmarslan** [opencart/opencart#12759]
Why is there no official docker file for Opencart?

**Comment by danielkerr** [comment]
theres one here

https://hub.docker.com/r/bitnami/opencart/

**Comment by danielkerr** [comment]
where shoould we poost the offical docker package

**Comment by fmarslan** [comment]
@danielkerr,

Bitnami adds an additional layer to the container, which can sometimes cause issues during configuration or maintenance. This is especially true for those working with local Kubernetes clusters, as they typically already have a maintenance or configuration layer in place. 

If Opencart offers a raw container option, they are more likely to choose it. Additionally, anyone looking to create a customized Opencart container would use the raw container as their base or use the Dockerfile from the repository.

The container could be uploaded to Docker Hub under the Opencart account.

I am preparing a container for myself. If you'd like, I can create a pull request (PR) once it's completed.

**Comment by danielkerr** [comment]
I'll ask on of my guts

**Comment by fmarslan** [comment]
You can find our container source, which may have some shortcomings, at the link below. We are currently addressing these shortcomings.

https://github.com/modulairy/opencart-container/tree/main

**Comment by agajdosi** [comment]
I need to host a small ecommerce site and OpenCart come as my first choice from my investigation of all possibilities. But I do not want to deploy it as whole LAMP stack on bare metal or VM. Instead I would like to deploy it in as a docker container.

I've been searching today a lot and there are not any official or update images, there is not any up to date guide, no mention in the official docs. Some sources refer to bitnami container, but that is deprecated. [modulairy/opencart-container](https://github.com/modulairy/opencart-container/tree/main) was last published 3 years ago. As an outsider to PHP I do not feel to write my own docker file. So I am lost now.

 I believe it would help the OpenCart to have an official docker image and some form of guide in the official docs, @danielkerr.
