### ISSUE TITLE
[master] cli_install not longer work as described in usage

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#12765]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
A install via cli_install.php is not working anymore.

**To Reproduce**
1. upload OpenCart files
2. start cli_install
// Usage:
//
//   php cli_install.php install --username    admin
//                               --email       email@example.com
//                               --password    password
//                               --http_server http://localhost/opencart/
//                               --db_driver   mysqli
//                               --db_hostname localhost
//                               --db_username root
//                               --db_password pass
//                               --db_database opencart
//				 --db_port     3306
//                               --db_prefix   oc_

3. a list of errors appear

**Expected behavior**

I expect a working install process as described.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] not relevant

**Additional context**

Problem started after including pull request https://github.com/opencart/opencart/pull/12758

**Comment by fmarslan** [comment]
Hi @pemaier,

the problem fixed  with #12767

**Comment by danielkerr** [comment]
i think people shbould just fucking wait to see me finsih the db changes instead of all jumpingin
