### ISSUE TITLE
[4] Installer. Completing the code from json

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#12762]
Why does the `code` come from the file name, and not from the `code` field in the install.json file?
Can be taken from the file name if the code field is not filled in.
If someone changes the file name, then the module simply does not work after installation.
You can add a file_name field to the oc_extension_install table.

The idea was, of course, to create a structure where the common folder is the author’s folder, and each author’s modules will be in his folder. How to make a folder with opencart modules. This will eliminate the possibility of a conflict in the names of the modules.

How to update the module correctly? Does it need to be removed and reinstalled?

**Comment by danielkerr** [comment]
pretty sure u have suggested this many time. its not happening
