### ISSUE TITLE
A possibility of using built-in returns mechanism for credit slips?

### ISSUE THREAD

**Issue by mehov** [opencart/opencart#12763]
Hi everyone

For accounting we are required to keep credit slips a.k.a. credit notes on every refund we are making.

Because a lot of related functionality is already implemented in both catalog and admin as "Returns", naturally I'm inclined to look there first, before I reinvent the wheel by creating my own tables.

Pros of using Returns:

- Most of the code is already implemented: users can already initiate returns / refunds, and admins can already manage them
- It's a logical place mose of the developers are already familiar with

Cons:

- There can only be one product per return; it is not possible to create a return having multiple products. If a given order has many products and 10 need to be refunded, there are 10 separate returns to manage and account for.
- It is not possible to refund a postage / shipping fee
- It is not possible to refund an arbitrary amount. 

What does the community think of updating the existing Returns with the above functionality? It won't be major changes, but seems like an improvement. Would it be a welcome change?

**Comment by mehov** [comment]
Of course there already are extensions providing credit notes functionality.

But they all are likely to create a separate DB table for pretty much the same thing. That means

- added housekeeping for every extension
- if an extension is deleted, it will likely delete the database table it created, so the store owner loses the credit notes history, which needs to be stored
- if a store owner moves to another extension, it will most likely use it's own format, which also means losing history and starting from scratch

It is clearly beneficial to have a standard "single source of truth" place for this.

Then implementing actual credit notes functionality is easy: someone who's working on credit notes only has to pull the returns/refunds for a given date range and serve them as PDF.

**Comment by danielkerr** [comment]
opencartt already has a credit system

**Comment by mehov** [comment]
That's different.

The current system (Customers → Edit → Transactions) lets you add virtual funds to the customer account, and those funds can be used against a future order. This won't work if the customer wants the money back because:

- the delivery was late (postage fee refund), or 
- some unexpected customs taxes were charged (arbitrary amount refund).

Being able to record the above types as returns means consistently storing *all* refunds in one place. 

This can be used, for example, when generating credit notes required for accounting.
