### ISSUE TITLE
Adding indexes on columns that used to be foreign keys?

### ISSUE THREAD

**Issue by mehov** [opencart/opencart#12774]
Hey everyone

Creating foreign keys during install [was disabled](https://github.com/opencart/opencart/commit/eb0f24661f3737ed86d5d37da4b290fb064f048d) as a hotfix to #12011.

This means all these `*_id` columns no longer got any indexes as well, because creating an index for every foreign key is the default MySQL behaviour ([source](https://stackoverflow.com/questions/836167/does-a-foreign-key-automatically-create-an-index/65888247#65888247)):

> MySQL requires that foreign key columns be indexed; if you create a table with a foreign key constraint but no index on a given column, an index is created.

Until the foreign key problem is fixed and until the foreign keys are back, would it be a good idea to create an index during install for every column involved?

(Affected columns would be the ones having pink diamond icons in [OpenCart - DB Schema.pdf](https://github.com/opencart/opencart/blob/73962c499c770cc1d5a40ae2d4b6b33a6f974183/OpenCart%20-%20DB%20Schema.pdf). So for example, in the `order` table: `store_id`, `customer_id`, `customer_group_id`, `payment_country_id`, `payment_zone_id` etc.)

**Comment by danielkerr** [comment]
i use it to build up the ERD diagrams but no i dont want any fixed referential deletes.

**Comment by danielkerr** [comment]
also payment_zone_id should not be foreign key because payment address might not be requeired

**Comment by danielkerr** [comment]
u can update the schema ifu think im missing something
