### ISSUE TITLE
Subscription Transaction Table Does Not Exists

### ISSUE THREAD

**Issue by punitkumar** [opencart/opencart#12798]
Opencart Version 4.0.2.3

In admin panel when you go to **Reports Page** and select **Customer Subscription Report** there is an error.

**Error: Table 'oc4023.oc_subscription_transaction' doesn't exist**
Error No: 1146
SELECT COUNT(DISTINCT `s`.`customer_id`) AS `total` FROM `oc_subscription_transaction` st LEFT JOIN `oc_subscription` s ON (st.`subscription_id` = `s`.`subscription_id`) LEFT JOIN `oc_customer` c ON (`s`.`customer_id` = c.`customer_id`): in F:\xampp\htdocs\oc_4023\system\library\db\mysqli.php on line 76
![Screenshot_2](https://github.com/opencart/opencart/assets/1077829/487b3c5f-63a0-4fce-80e7-bf594def29e2)

No table structure found in "upload/system/library/db_schema.php" file as well. However, table described in PDF file "OpenCart - DB Schema.pdf" .
![Screenshot_1](https://github.com/opencart/opencart/assets/1077829/5f930856-d617-43e9-b5df-d23ce4fd654c)

Look at fresh install of Opencart 4.0.2.3

https://www.loom.com/share/66f043410459490aa367407a1cf66472?sid=e0d88b5a-ed66-4318-bc91-e1123e9628a1

**Comment by danielkerr** [comment]
there should be no subscription transaction table
