### ISSUE TITLE
Opencart 4 Upgrade feature not work  if "install" directory is deleted.

### ISSUE THREAD

**Issue by ZateLabClients** [opencart/opencart#12797]
When installing Opencart 4, admin panel suggest to delete the "install" folder. Then how Opencart Upgrade funtion works??.
Because we can see that the update controllers are in 'install' folder.

<img width="513" alt="image" src="https://github.com/opencart/opencart/assets/85485041/f6bbf911-a724-43d9-a587-368c79422f85">

**Comment by danielkerr** [comment]
u should read the upgrade instructions 

u upgrade from the system > maintaince > upgrade 

or if ur copy and pasting then go to install/ so u can run through the upgrade script
