### ISSUE TITLE
Add extension for OpenCart Api

### ISSUE THREAD

**Issue by UzairKhalil** [opencart/opencart#12799]
I have installed my extension in OpenCart for getting customized Orders. My extension structure is as:
upload
->extension
-->myapi
---->admin/controller/api/orders.php
---->admin/model/orders.php

I can access controller file on path `route=extension/myapi/api/orders` with user_token. 
But how it should be accessed via openCart API? with api_token? How can I define its route?

**Comment by danielkerr** [comment]
not sure what u mean. maybe post in the form. if u mean using curl then u need to make a few requests and keep the link open.
