### ISSUE TITLE
Discount coupons percentages calculated before tax

### ISSUE THREAD

**Issue by ghost** [opencart/opencart#128]
on 1.531 store, using default template

The discount coupon ignores the vat applied to any product and calculates the discount based on the ex vat setting

so a 20% discount code which should do the following

.product price  £25 (inc vat) - 20% = £20 = £5 discount

actually does this

product price £25(inc vat)  - vat  is removed = £20.83 - 20% code = £4.17 discount

**Comment by mechanoengi** [comment]
I completely aggre with ghost. Buyer know what he/she will pay and does not matter about the vat. Prices are written with tax on the labels and buyer calculates the discount over the label.
