### ISSUE TITLE
Fresh Install, Unable to add products or remove demo products.

### ISSUE THREAD

**Issue by danclarkau** [opencart/opencart#12815]
Fresh installation, no products listed in admin, however they are listed on the shop front.
Can't delete these products, as can't see them listed under products screen.
Can't add additional products as the SEO Keyword box keeps failing saying the URL must be unique.

![image](https://github.com/opencart/opencart/assets/8283936/393436f5-1ef3-4aa7-a28d-d0983c526b66)

**Comment by danielkerr** [comment]
must be a permission issue to use the delete statement in mysql. the thing s nobody else is reporting this issue

**Comment by ADDCreative** [comment]
The issue is caused when the language cookie has a old/invalid value. Clearing cookies should fix it.

It's been reported a few times before.
https://github.com/opencart/opencart/issues/12701
https://github.com/opencart/opencart/issues/12766
