### ISSUE TITLE
There is a language problem

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#12816]
self::$languages = $this->model_localisation_language->getLanguages();

Array
(
    [0] => Array
        (
            [language_id] => 1
            [name] => Türkçe
            [code] => tr.

It returns multi array.

change 

self::$languages = $this->model_localisation_language->getLanguageByCode($code);

if (isset(self::$languages)) {
	$language_info = self::$languages;

https://github.com/opencart/opencart/blob/8cc84e52d0dbb7c8f89819ab09cb937bddae769c/upload/catalog/controller/startup/language.php#L26:L32

**Comment by danielkerr** [comment]
why!!!
