### ISSUE TITLE
Hide language title in URI

### ISSUE THREAD

**Issue by yvgorshkov** [opencart/opencart#12851]
**Version 4.0.2.3**

**Describe the bug**
How to hide the single language label in URI in the opencart system?

**To Reproduce**
After installation, the language appears in the address bar. He is the only one in the system. How to remove it?

There are tips on the Internet for editing the kernel source code. Is it really impossible without this?

**Server / Test environment (please complete the following information):**
 - local development
 - Ubuntu LTS 22.04
 - PHP 8.1
 - Apache 2
 - Browser - Latest Chrome

**Comment by pemaier** [comment]
I can't reproduce this error with a new install.
![image](https://github.com/opencart/opencart/assets/10166095/9fbdba28-34ce-4f37-b34b-eeeb73ce3b56)

**Comment by yvgorshkov** [comment]
> I can't reproduce this error with a new install. ![image](https://user-images.githubusercontent.com/10166095/279303079-9fbdba28-34ce-4f37-b34b-eeeb73ce3b56.png)

![mp3oc](https://github.com/opencart/opencart/assets/294703/da2ea9aa-460e-4d5f-810a-2eaa33e63ceb)

**Comment by pemaier** [comment]
Hello Yuri. Sorry my mistake - in the URL I also get     ../en-gb?route=common/home    with active SEO.
