### ISSUE TITLE
There is duplication in bread crumbs

### ISSUE THREAD

**Issue by yvgorshkov** [opencart/opencart#12852]
**Version 4.0.2.3**

**Describe the bug**
There is duplication in bread crumbs

**To Reproduce**
After installing the system. Go to any mp3 subsection. MP3 will be written twice in the breadcrumbs

**Expected behavior**
Expected display of section and subsection in breadcrumbs

**Server / Test environment (please complete the following information):**
 - local
 - Ubuntu LTS 22.04
 - PHP 8.1
 - Apache 2
 - Latest Chrome

**Comment by yvgorshkov** [comment]
![mp3oc](https://github.com/opencart/opencart/assets/294703/e69b7b73-b997-4703-ae3c-eca007adf652)

**Comment by mhcwebdesign** [comment]
This is already fixed in the master branch for the upcoming 4.0.2.4 version.

**Comment by danielkerr** [comment]
![image](https://github.com/opencart/opencart/assets/5079756/74d0f772-5c36-4ace-ac06-d987a1304977)

**Comment by grahamstoker** [comment]
Hi,

I am a first time user of open cart and have version 4.0.2.3 and cannot update to version 4.0.2.4 as it is not available yet. 

I have this issue of double up and wondered how this was fixed in danielkerr's posts

Thanks
