### ISSUE TITLE
UTF8 domain lookup during startup won't match it's Punycode representation

### ISSUE THREAD

**Issue by mehov** [opencart/opencart#12854]
**What version of OpenCart are you reporting this for?** 2 and 4

**Describe the bug**

Nginx [does not](https://nginx.org/en/docs/http/server_names.html#idn) support UTF8 domains (`æøå.example.com`) in the `server_name` directive and uses ASCII/Punycode (`xn--5cab8c.example.com`) instead. As a result, `$SERVER['HTTP_HOST']` contains ASCII/Punycode.

If I save the UTF8 domain in Opencart settings, [`getStoreByHostname()`](https://github.com/opencart/opencart/blob/365e73a0a26bfb0b2a7dd9c36632eab5b8522b6b/upload/catalog/model/setting/store.php#L25) (called [in `catalog/controller/startup
/setting.php`](https://github.com/opencart/opencart/blob/365e73a0a26bfb0b2a7dd9c36632eab5b8522b6b/upload/catalog/controller/startup/setting.php#L17)) won't pick it up, as it receives the ASCII `$SERVER['HTTP_HOST']`.

Our local workaround is to pass the `$SERVER['HTTP_HOST']` value through `idn_to_utf8` before looking it up in the database.

    $query = $this->db->query("SELECT * FROM " . DB_PREFIX . "store WHERE REPLACE(`ssl`, 'www.', '') = '" . $this->db->escape('https://' . str_replace('www.', '', idn_to_utf8($_SERVER['HTTP_HOST'], 0, INTL_IDNA_VARIANT_UTS46)) . rtrim(dirname($_SERVER['PHP_SELF']), '/.\\') . '/') . "'");

Do you think it could make sense to implement this for everyone?

**To Reproduce**
1. Configure you web server to where `HTTP_HOST` that Opencart receives is in Punycode
2. Configure Opencart store to expect the UTF8 representation

**Expected behavior**
Opencart recognises both UTF8 domains as well as Punycode domains

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - Operating system Debian 11
 - PHP version 8.3
 - Nginx

**Comment by ADDCreative** [comment]
It would need more than that to properly support UTF-8 domain names. The database tables use a general_ci collation. So test.example.com and xn--tst-bma.example.com (tést.example.com) would be a match, even though they are different domains.

**Comment by danielkerr** [comment]
already reported. no solution.
