### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#12869]
**What version of OpenCart are you reporting this for?**
Master branch

**Describe the bug**
It is highly unlikely that the other DB engine PostgrSQL will actually work, especially in view of all the recently added backticks ('`') for table aliases in the various model classes.

In view of this, would it make sense to drop support for PostgrSQL altogether? Or are there plans to fix all the model classes, starting with the many unneeded backticks, and other query fixes?

**Comment by TheCartpenter** [comment]
> **What version of OpenCart are you reporting this for?** Master branch
> 
> **Describe the bug** It is highly unlikely that the other DB engine PostgrSQL will actually work, especially in view of all the recently added backticks ('`') for table aliases in the various model classes.
> 
> In view of this, would it make sense to drop support for PostgrSQL altogether? Or are there plans to fix all the model classes, starting with the many unneeded backticks, and other query fixes?

Sure, go ask the database industry for a 2-minute solution that would also get rid of all the reserved terms they've put into their documentations to inform the public that ```reserved terms```, under their rights I might add, are reserved for the purpose of their libraries development in order to make this work in the mean time while somebody else worries about another and singleton library.

**Comment by mhcwebdesign** [comment]
@TheCartpenter : Do have anything constructive to say here? A decision is needed here as to whether OpenCart should even support other DB engines at all, and if so, many of the model classes need fixes.

**Comment by TheCartpenter** [comment]
> @TheCartpenter : Do have anything constructive to say here? A decision is needed here as to whether OpenCart should even support other DB engines at all, and if so, many of the model classes need fixes.

You damn, I have. The only and definite fixes that really are required is the MySQL Parser from the server libraries which is beyond our control.

Even though there'd be a way to dynamically remove the backticks from the models directly from the SQL string in the DB libraries, that still won't change the fact that those removals would be user-defined as it would create other problems.

**Comment by danielkerr** [comment]
its too much messing around. postgres seems to differ to much from mysql
