### ISSUE TITLE
[4.0.2.3] Header cart doesn't refresh after applying shipping methods.

### ISSUE THREAD

**Issue by Samdz19** [opencart/opencart#12874]
I got the issue using OpenCart v4.0.2.3

I find that the header cart (mini cart) doesn't refresh after applying shipping method to get shipping estimate from shopping cart page.

So, I have edit the shipping method file like this, until opencart fix the issue.

> I edited this file:
> **catalog/view/template/checkout/shipping_method.twig**
> 
> And add this line
> **$('#header-cart').load('index.php?route=common/cart.info&language={{ language }}');**
> 
> After this line (line 131)
> **$('#checkout-confirm').load('index.php?route=checkout/confirm.confirm&language={{ language }}');**

**Comment by danielkerr** [comment]
it' will be fixed with the others
