### ISSUE TITLE
[3.0.3.9] - No custom field on Edit order in admin

### ISSUE THREAD

**Issue by stefancic** [opencart/opencart#12871]
**What version of OpenCart are you reporting this for?**

3.0.3.9

**Describe the bug**

I have created an account custom field and added it to the checkout. The checkout works fine and when you see the order, you can see the custom field and its entered value in the Order history below. But when you edit the order, the input for the custom field isn't anywhere. If you go through all 5 steps and save the order, the custom field value is set to blank and its not visible anymore on the order details page.

**To Reproduce**

1. Create an "account" custom field
2. Submit an order with the custom field value
3. Look at the order in the admin to check if the custom field is there
4. Edit the order and see there is no custom field input

**Expected behavior**

The custom field should exist on the Edit order page in Admin.

**Server / Test environment (please complete the following information):**

PHP 8.0

**Comment by mhcwebdesign** [comment]
Could you provide some more details please? In particular, how exactly did you create the custom field? Was it via the admin backend at **_Customers > Custom Fields >  Add Custom Field_** ? And if so, what are the custom fields details (custom field name,location, type, etc)?

**Comment by stefancic** [comment]
I created in in Customer - Custom Fields - Add Custom Field

Name: Davčna št.
Location: Account
Type: Text
User Group: selected, I have only one
Not required

The custom field is displayed normally on checkout, also it is displayed on order info - but there is no field when you edit the order.

**Comment by mhcwebdesign** [comment]
The account custom field is correctly displayed at **_Customers > Customers > edit_**, but not on **_Sales > Orders > view_**, because custom account fields are not stored in an OpenCart order. It does show up in **_Sales > Orders > edit > tab Customer Details_**, but I think that's wrong, account custom fields shouldn't show up in the latter at all!

**Comment by condor2** [comment]
Work just fine
![cust_field](https://github.com/opencart/opencart/assets/14251939/7f197af7-43e2-48d6-afca-76964980446c)

**Comment by mhcwebdesign** [comment]
> Work just fine !

Except that it won't save the account custom fields after editing an order. The account custom fields are not part of the saved order anyway.

**Comment by mhcwebdesign** [comment]
I was wrong with my previous statement.

Just tested it again, with an account custom text field, and it stores it just fine in the DB field **oc_order.custom_field**
