### ISSUE TITLE
Required field meta_title. Why?

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#12877]
Why meta_title is a required field for categories/products/informations/topics/articles?

- It is very annoying to fill this field. In most cases it contains same text as name
- Most seo extensions fill this field automatically without editing form

Furthermore this breaks seo extensions logics. If you want this field filled automatically in realtime by extension you can leave it empty. If you want to use your custom title for certain product/category/etc, you just fill it with your text.

It would have more sense to take meta_title from name field if it is empty in catalog controllers. This will make life of content managers a lot more easy and save lots of time.

**Comment by danielkerr** [comment]
have we need some system to copy what u write across multiple fields

**Comment by stalker780** [comment]
@danielkerr Sorry, did not get you comment.

I was just trying to find out why it was made required since OC2.
As far as I remember in OC1.5 meta_title was taken from name and this worked fine.

Then I decided to propose a PR with an optional meta_title. This does not break any functionality, but makes it much easier to create new entries.
