### ISSUE TITLE
OCSESSID can be controlled by attacker

### ISSUE THREAD

**Issue by mips171** [opencart/opencart#12913]
This sets the cookie if the target victim's email is hosted on their domain, and assumes they're using the email web client (again not exactly far fetched, think Exchange server, or something like that on a host like mail.opencart.com). Embed that in an email, then click it. (This will also work from any page hosted on their domain.)

<script>
function setCookieAndOpenUrl() {
  // Set the cookie for opencart.com and all its subdomains
  document.cookie = "OCSESSID=deadb33fabcd1234abcd1234; path=/; domain=opencart.com";

  window.open('https://shop.opencart.com/admin/', '_blank');
}
</script>

<button onclick="setCookieAndOpenUrl()">Log In/Reset Password/Sale on Now! -- Sets Cookie and Open URL</button>

From there, the user logs in, validating the OCSESSID. Now it's just up to the attacker to use their wits get the user to send them the URL containing their user_token and off you go.

This is trusting the client way too much with a piece of information that is crucial to authenticity, namely OCSESSID.

@ADDCreative regenerating the token upon login should be a good fix for this, are there any plans to action that? I have had a look at session.php, login.php and framework.php, would there need to be any other changes as far as you're aware? I'm still ramping up with the OC code.

@danielkerr not to asking you to get involved, just let the rest of us talk so we can fix this security issue please. Btw thank you for starting and maintaining this open source project, it's not easy and is a big commitment from you.

**Comment by danielkerr** [comment]
time waster!

**Comment by danielkerr** [comment]
post again u get banned!
