### ISSUE TITLE
Admin URL Change every time we change extension filter

### ISSUE THREAD

**Issue by sahilofficial671** [opencart/opencart#12936]
**What version of OpenCart are you reporting this for?**
3.0.3.9

**Describe the bug**
Every time I change "Admin > Extensions > Extensions" and filter the current admin page url changes to:
`{your domain}/index.php?route=api/promotion&type=module&__cf_chl_rt_tk=wacTbbn7BfqSj2Gf9x8uUK4.23U91C2mknSUUl2S3iU-1699780027-0-gaNycGzNCuU` and URL it changes to is also wrong the domain in the URL is ours instead of Opencart Server which should give us a promotional Opencart Image may be Paypal Promotion of something.

**To Reproduce**
1. Go to 'Admin > Extensions > Extensions'
2. Select any filter entity let say "Module"
3. Click on "Filter"
4. You we can see that current page url has been changed to something from Opencart api/promotion
`{your domain}/index.php?route=api/promotion&type=module&__cf_chl_rt_tk=wacTbbn7BfqSj2Gf9x8uUK4.23U91C2mknSUUl2S3iU-1699780027-0-gaNycGzNCuU` 
5. And If we refresh at this moment it will load that api/promotion page

**Expected behavior**
Current page url should not change after changing any filter value

**Screenshots / Screen recordings**
![image](https://github.com/opencart/opencart/assets/55436684/ea7aaf8f-2bf4-483d-b7c0-eb0c4715768b)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? - Yes, tested on both
 - Operating system - Windows
 - PHP version - 8.0
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Comment by cartbinder** [comment]
Possibly due to Cloudflare active on your server. 

When you pass the captcha test the path gets added to your URL by Cloudflare.

**Comment by danielkerr** [comment]
Ok will cancel. I was being ddos. I need to put the admin on a sperate site

**Comment by crisjff** [comment]
Hello. Same issue here since yesterday in versions 3.0.3.8 and 3.0.3.3, any clue? Thank you.

**Comment by ADDCreative** [comment]
@crisjff Maybe https://github.com/opencart/opencart/issues/13892 (and https://github.com/opencart/opencart/pull/14084 if PHP less then 8).
