### ISSUE TITLE
Error in opencart.sql file - Path Error in Line 3868

### ISSUE THREAD

**Issue by nicomintr** [opencart/opencart#12946]
In the "opencart.sql" file located at the path "upload/install/opencart.sql," there is a path error on line 3868:

`INSERT INTO `oc_user_group` (`user_group_id`, `name`, `permission`) VALUES
(1, 'Administrator', '{"access":[....."extension\\/currceny\\/ecb".....]}'),`

It should be replaced with:

`INSERT INTO `oc_user_group` (`user_group_id`, `name`, `permission`) VALUES
(1, 'Administrator', '{"access":[....."extension\\/currency\\/ecb".....]}'),`

**Comment by danielkerr** [comment]
can not replicate. also u dont put which version

**Comment by mhcwebdesign** [comment]
I think it was for the 3.0.x.x branch. I have now fixed it ('currency' instead of 'currceny').

**Comment by nicomintr** [comment]
Yes, sorry, I forgot to mention the branch version v. 3.0.3.9
> I think it was for the 3.0.x.x branch. I have now fixed it ('currency' instead of 'currceny').
