### ISSUE TITLE
[Master] No error message when regex validation is invalid

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#12978]
**What version of OpenCart are you reporting this for?**
Master

**Describe the bug**
Add a new Text custom field and write some letters in Validation input (fgfgf) then click save.

No error message it shown.

Console log message error

<b>Unknown</b>: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in <b>admin\controller\customer\custom_field.php</b> on line <b>387

<b>Warning</b>: preg_match(): Delimiter must not be alphanumeric, backslash, or NUL in <b>admin\controller\customer\custom_field.php</b> on line <b>387</b>{"error":{"validation":"error_validation"}}`

**Comment by condor2** [comment]
Closed....and Admin warning message where is?

**Comment by danielkerr** [comment]
@AJenbo im getting a bit worried about some of ur commits now.

**Comment by AJenbo** [comment]
https://github.com/opencart/opencart/pull/12994#issuecomment-1823144109

**Comment by danielkerr** [comment]
should be ok now
