### ISSUE TITLE
[3.0.x.x] 0 Special price is still displayed

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#12976]
**What version of OpenCart are you reporting this for?**
3.0.x.x

**Describe the bug**
If special price is 0, on catalog side is still displayed

https://github.com/opencart/opencart/pull/9197/files

**Comment by mhcwebdesign** [comment]
This is not a bug. If special price is zero, it correctly displays the zero price on the frontend page.

Besides, why would you even use zero for the special price in the first place?

**Comment by condor2** [comment]
Entering by mistake.....

https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/product.php#L509

**Comment by TheCartpenter** [comment]
For zero prices, this is the reason why: https://cm-commerce.com/academy/what-science-says-about-discounts-promotions-and-free-offers/#:~:text=The%20price%20of%20free,higher%E2%80%9D%20than%20their%20absolute%20value.

**Comment by condor2** [comment]
lol
