### ISSUE TITLE
[Master] ECB bug currency rate?

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#12977]
**What version of OpenCart are you reporting this for?**
Master branch

**Describe the bug**

I have refreshed ECB currency and EURO vs USD is:

0.84602094 | 1.00000000

On 3.0.x.x is

0.91979397 | 1.00000000

Both oc version has this URL in ecb

`https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml`

**Comment by ADDCreative** [comment]
The calculations are different. Try.
```php
$this->model_localisation_currency->editValueByCode($result['code'], $currencies[$result['code']] / $value);
```

**Comment by condor2** [comment]
With that line changed work.

**Comment by mhcwebdesign** [comment]
Well, the value shown on OC 3.0.x.x is the correct one, the one from the OC 4 master branch appears to be wrong.

**Comment by TheCartpenter** [comment]
So is the correct one from the opencart-3 originally.

**Comment by danielkerr** [comment]
MOST LIKELY SOME NE POSTED A COMMIT TO MESS THINGS UP

**Comment by danielkerr** [comment]
> So is the correct one from the opencart-3 originally.

VERSION 3 DOES NOT HAVE ECB

**Comment by TheCartpenter** [comment]
> > So is the correct one from the opencart-3 originally.
> 
> VERSION 3 DOES NOT HAVE ECB

It's sad to see that you seem to be a bit late in the news on this one since OC v3.0.x.x and opencart-3, both, have the ECB integrated already as you are the one who officially put the version number for it afterwards.

**Comment by danielkerr** [comment]
versoin 3 stilll uses yahoo

**Comment by condor2** [comment]
https://github.com/opencart/opencart/blob/3.0.x.x/upload/admin/controller/extension/currency/ecb.php

**Comment by TheCartpenter** [comment]
> versoin 3 stilll uses yahoo

That's right, @danielkerr. Version 3 still uses Yahoo:



> https://github.com/opencart/opencart/blob/3.0.x.x/upload/admin/controller/extension/currency/ecb.php

admin/controller/extension/currency/ecb.php
admin/model/extension/currency/ecb.php
admin/view/template/extension/currency/ecb.twig
catalog/controller/extension/currency/ecb.php
catalog/model/extension/currency/ecb.php
install/opencart.sql

**Comment by mhcwebdesign** [comment]
3.0.3.9 uses Yahoo, the latter has been defunct for quite a while now.
3.0.x.x uses the ecb, which I backported from OpenCart 4.
And it was also then copied over by @TheCartpenter to opencart-3.

Hope this clarifies it.

**Comment by TheCartpenter** [comment]
The above is not entirely true in regard to 'copied'. It is not a verbatim copy while I did took portion of the MB as well to achieve this on the opencart-3 repository.

**Comment by mhcwebdesign** [comment]
> The above is not entirely true in regard to 'copied'. It is not a verbatim copy while I did took portion of the MB as well to achieve this on the opencart-3 repository.

OK, thanks for the clarification. BTW.: I can't see the **Extensions > Extensions > Currency Rates** in the admin backend of opencart-3, there should be one pointing to available currency engines.

**Comment by danielkerr** [comment]
if anyone wants to maybe move some of the fixes accross

**Comment by danielkerr** [comment]
i need to do another update foor opayo

**Comment by TheCartpenter** [comment]
> > The above is not entirely true in regard to 'copied'. It is not a verbatim copy while I did took portion of the MB as well to achieve this on the opencart-3 repository.
> 
> OK, thanks for the clarification. BTW.: I can't see the **Extensions > Extensions > Currency Rates** in the admin backend of opencart-3, there should be one pointing to available currency engines.

Done.

**Comment by mhcwebdesign** [comment]
> 
> Done.

See also this issue: https://github.com/opencart/opencart-3/issues/206
