### ISSUE TITLE
High CPU Usage Issue: Suspected Cache Problem

### ISSUE THREAD

**Issue by kungfudirect** [opencart/opencart#12988]
I've been experiencing sudden and significant increases in CPU usage on my OpenCart site, and I suspect it might be related to caching. This issue started almost daily, I'm currently using OpenCart version 3.03.8 .
**Symptoms:**
- Sudden spikes in CPU usage, causing site slowdowns.
- No specific error messages displayed.
- CPU usage seems to be intermittent.
Seeking advice and assistance from the OpenCart community in identifying and resolving the high CPU usage issue.
- Particularly interested in insights on common causes and troubleshooting steps.
**Expected Help:**
- Looking for guidance on identifying the root cause of sudden CPU spikes.
- Recommendations for monitoring tools or diagnostics to pinpoint the issue.

**Additional Notes:**
- The high CPU usage seems to coincide with increased site traffic.
- No recent changes made to OpenCart configurations.

Any help or guidance you can provide would be greatly appreciated. Thank you!

**Comment by mhcwebdesign** [comment]
Best to post it on the OpenCart forum: https://forum.opencart.com/
And while there. provide more details, as per the forum rules https://forum.opencart.com/viewtopic.php?t=200480

**Comment by chongshengdz** [comment]
If you are using mysql 5.7 or lower, there should be no problem.
if you are using mysql 8.0 or higher or new version of mariaDB, 
it may due to using too many select * from ... and  select * from ... where ... or ...
you need to find them and replace them one by one.
for example, replace select *  with columns

**Comment by kungfudirect** [comment]
mysql is 8.0

**Comment by kungfudirect** [comment]
over 1000 products

**Comment by chongshengdz** [comment]
> over 1000 products
over 1000 products are not the problem, you need to do what i told you above.

**Comment by danielkerr** [comment]
does not matter having 1000 products as long as u dont show them all at once
