### ISSUE TITLE
[3.0.x.x] Autocomplete (Dropdown) bug when edit Attributes

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#12989]
**What version of OpenCart are you reporting this for?**
3.0.x.x

**Describe the bug**
This bug is somehow related to Bootsrap 3.4.1 and Jquery > 3.2.1.

https://github.com/opencart/opencart/blob/3.0.x.x/upload/admin/view/javascript/common.js#L214-L223

**To Reproduce**
Edit a product which has Attributes then click on the input of that attribute.
Dropdown will show on wrong posittion. Same when you try to add one.

**Screenshots / Screen recordings**
![attribute_bug](https://github.com/opencart/opencart/assets/14251939/a0202bf5-e3da-4713-b66e-98fd6cf91790)

**Comment by mhcwebdesign** [comment]
Thanks, well spotted. Now fixed, see https://github.com/opencart/opencart/pull/12990
