### ISSUE TITLE
Object properties inside models

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#13028]
https://github.com/opencart/opencart/commit/846a5bf016924059a98e73697cdde5a6c8bed7ba#diff-d3c1b486ca583b5faf702ceec3acefd3ee8063edd614cbd450290be77f9984a3L121

After this commit models are reconstructed on every call for example `$this->model_catalog_product->getProduct()`.
You cannot store any variables inside a model class, because they are reset every time a model is called.

Don't know if it was meant to work like that, but this breaks a lot of functionality of PHP objects, also it takes more time to reconstruct every model class. Especially if you want to use own `__construct` method in your extension.

BTW controllers have this issue since OC1.5 or OC2.0 as far as I remember.

IMHO when you code PHP objects and want to use a class properties like `$this->my_var` you must be able to use them and you rely that these properties are saved between calls to an object. Otherwise why are we using PHP objects at all?

I have tried to use previous version of `model` method in loader.php and it works fine. Properties are saved.

**Comment by danielkerr** [comment]
needs to be fixed a different way

**Comment by danielkerr** [comment]
also controllers should not be stored.
