### ISSUE TITLE
PHP 7.4 Settings warnings

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#13026]
**What version of OpenCart are you reporting this for?**
Master

**Describe the bug**
Notice: Trying to get property 'rows' of non-object in admin\model\setting\setting.php on line 17
Return value of Opencart\Admin\Model\Setting\Setting::getSettings() must be of the type array, null returned

Notice: Trying to get property 'row' of non-object in catalog\model\setting\store.php on line 28
Return value of Opencart\Catalog\Model\Setting\Store::getStoreByHostname() must be of the type array, null returned

**Comment by danielkerr** [comment]
can t replicate. i suugest pull the last commits

**Comment by condor2** [comment]
I have downloaded again...and same problem....weird.

Maybe someone else can test with php 7.4
