### ISSUE TITLE
No Login for admin after installation

### ISSUE THREAD

**Issue by decMuc** [opencart/opencart#13024]
**What version of OpenCart are you reporting this for?**
4.0.2.3 - master from git - 15 min ago
**Describe the bug**
After installation when you go to admin page, there come no login form - but you can see part of dashboard and the popup to change storage folder... you can try to click but it have no effect.

What section does it affect?
Warning: Undefined array key "user_token" in .../admin/controller/common/dashboard.php on line 21Warning: Undefined array key "user_token" in .../admin/controller/common/dashboard.php on line 26Warning: Undefined array key "user_token" in .../admin/controller/common/security.php on line 53Warning: Undefined array key "user_token" in .../admin/controller/common/dashboard.php on line 92

**To Reproduce**

Make a new install.
1. Go to 'admin'
2. Click on 'nothing'
3. Scroll down to 'nothing'

**Expected behavior**
The login form for admin page

**Screenshots / Screen recordings**
n/a

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system - debian12
 - PHP version 82
 - Openlitespeed  1.7.18
 - Browser(s) tested Chrome, Safari, Firefox
(firefox was new installed - no old cookies)

**Comment by danielkerr** [comment]
yes i updated events. fixing now

**Comment by danielkerr** [comment]
and startup

**Comment by MaAnShanGuider** [comment]
I encountered the same problem.😂😂😂
