### ISSUE TITLE
[Master] Manufacturer List & Info language bug

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#13031]
**What version of OpenCart are you reporting this for?**
branch

**Describe the bug**
Wrong language is displayed when no brands

If you check Manufacturer_list you will see that the language variable is **text_no_results**
https://github.com/opencart/opencart/blob/master/upload/catalog/view/template/product/manufacturer_list.twig#L30

Manufacturer Info user same variable
https://github.com/opencart/opencart/blob/master/upload/catalog/view/template/product/manufacturer_info.twig#L55

The language file use: 
**$_['text_no_results']  = 'There are no products to list.';**

When are no Brands in the store the correct message is this: **There are no brands to list.**

So better use 2 variables: 

**text_empty** for no products in Manufacturer Info
**text_no_results** for no Brands in Manufacturer List

**Comment by TheCartpenter** [comment]
Already added on the opencart-3 repository.

**Comment by danielkerr** [comment]
u should put this is for the 3.x branch

**Comment by condor2** [comment]
> u should put this is for the 3.x branch

When your brain is fried.....
![manufacturers](https://github.com/opencart/opencart/assets/14251939/c90ec241-3990-4b39-b94e-699178262d6c)
