### ISSUE TITLE
Add new Kazakhstan regions

### ISSUE THREAD

**Issue by yaldasshit** [opencart/opencart#13051]
OpenCart 3.0.3.8
In 2022, new regions appeared in Kazakhstan (Abai, Jetisu, Ulytau), but theese regions do not exist in regions list of localization settings

Localization section

![image](https://github.com/opencart/opencart/assets/61117094/350ee98b-5d1c-4d67-b385-c8ee8176d90a)

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - PHP v. 7.3

https://en.wikipedia.org/wiki/Regions_of_Kazakhstan#:~:text=0.0%20–%209.9%25-,Demographic%20statistics,from%20part%20of%20Karaganda%20Region).

**Comment by pemaier** [comment]
@yaldasshit  also [Shymkent](https://en.wikipedia.org/wiki/Shymkent) is not in the database. This has the reason that the new regions have not an ISO_3166-2 code - I found nothing in the web. May you can provide this so it is possible to enter the regions into the database?

**Comment by danielkerr** [comment]
pull request please

**Comment by pemaier** [comment]
@danielkerr I already started with a pr but I'm missing the ISO_3166-2 code. I can do it temporarily with a dummy code till I get a real one. What you suggest?
