### ISSUE TITLE
SEO URL propositions for improvement

### ISSUE THREAD

**Issue by SDG1212** [opencart/opencart#13110]
**What version of OpenCart are you reporting this for?**
Master

**Describe the bug**
It's great that we have found a fix for 404 error page recognition. I discovered that the index method code in seo_url.php file has some potential vulnerabilities. Somebody who is  responsible for the repository needs to confirm that we need to fix some test cases or to ignore it.

**1. High tolerance to multiple forward slashes**

https://domain/en-gb/product////iphone

**Output result**
Product page

**Expected result**
404 page

**2. High tolerance to keyword sort order positions**

**Correct link**
https://domain/en-gb/product/desktops/mac/imac

**Incorrect link**
https://domain/en-gb/product/imac/desktops/mac

**Output result**
Product page

**Expected result**
404 page

**3. Home page with language code**

https://domain/qwerty404?language=en-gb

**Output result**
Home page

**Expected result**
404 page

**4. Double quotes PHP warning.**

The same issue #10463

https://domain/en-gb/product/desktops/mac/%22imac%22

**An addition**
Check please the security of tool/upload controller in catalog folder. There isn't some kind of CSRF token check to protect against file uploading spam to the storage folder. As a result disk space usage can increase. Is this controller safe enough?

**Comment by danielkerr** [comment]
u dont know what ur talking about!

"seo_url.php file has some potential vulnerabilities"

fucking expert here all of a sudden!  if u were smart enough to be able to read php code u would see there is no vulnerabilities and we already have tokens on upload pages! in fact we have them on all forms.

**Comment by SDG1212** [comment]
@danielkerr Have a nice day!

**Comment by danielkerr** [comment]
ok we dont have tokens on uploads. adding now. thought i did it when i added tokens to all the form.
not a worldending


No vulnerability for seo urls because becauae u are just converting key value pairs into request GET vars. at the most what u have found is a bug. if u have setup your store properly with disabling displaying errors there is also fallback error.html page.
