### ISSUE TITLE
Database Issues while installing

### ISSUE THREAD

**Issue by sarojbaskota** [opencart/opencart#13127]
**Latest master branch code**

**While installing project throw db related key error**

Error: Key column 'article' doesn't exist in table
Error No: 1072
CREATE TABLE `oc_article_rating` ( `article_rating_id` int(11) AUTO_INCREMENT, `article_id` int(11), `article_comment_id` int(11), `store_id` int(11) DEFAULT '0', `customer_id` int(11) DEFAULT '0', `rating` tinyint(11), `ip` varchar(40), `date_added` datetime, PRIMARY KEY (`article_rating_id`), KEY `article_id` (`article`), KEY `article_comment_id` (`article_comment`), KEY `customer_id` (`customer`), KEY `store_id` (`store`) ) ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_general_ci; : in /var/www/html/explore/opencart/upload/system/library/db/mysqli.php on line 122

**Comment by TheCartpenter** [comment]
Seem to be relative: https://github.com/opencart/opencart/pull/13134

**Comment by danielkerr** [comment]
another one. give me chance to finish the blog system, then i go through the installer
