### ISSUE TITLE
SEO Url not working

### ISSUE THREAD

**Issue by abikh** [opencart/opencart#13126]
**What version of OpenCart are you reporting this for?**
4.0.2.2
**Describe the bug**
Seo url not working. It showing page not found . I checked from local host (Macbook Xaamp ) and also AWS AMI 2 Instance. It works fine if we disabled SEO URL Option from admin panel.
What section does it affect?
All Pages

**Comment by danielkerr** [comment]
maybe add the correct path to RewriteBase /
