### ISSUE TITLE
Coupon list page - status column 

### ISSUE THREAD

**Issue by Samdz19** [opencart/opencart#13137]
**Opencart 4.0.2.3**

After opencart remove status column in  version 4.0.2.3 the colum status stay in coupon list page with showing 0 and 1

Need to remove line to fixe

1. Go to 'admin/view/template/marketing/'
2. Open 'coupon_list.twig'
3. Scroll down to line '32'
4. Then remove : `<td class="text-start">{{ coupon.status }}</td>`

**Comment by TheCartpenter** [comment]
Or, to simply re-add the validation of the enabled or disabled ```status```. Disabled should be the default one when the platform removes the ```status```.

**Comment by Samdz19** [comment]
> Or, to simply re-add the validation of the enabled or disabled `status`. Disabled should be the default one when the platform removes the `status`.

The status column and sort order code should be removed from the coupon, voucher, customer and other lists
But I mean the status column in coupons list,

![Uploading coupon_error.png…]()

**Comment by TheCartpenter** [comment]
That's because the ```status``` values shows in the ```action``` field. The ```colspan``` should also be adjusted accordingly.

**Comment by Samdz19** [comment]
> That's because the `status` values shows in the `action` field. The `colspan` should also be adjusted accordingly.

No the colspan not the issue,
Opencart change the place of status on the version 4.0.2.3, they remo this:
`<td class="text-start"><a href="{{ sort_status }}"{% if sort == 'status' %} class="{{ order|lower }}"{% endif %}>{{ column_status }}</a></td>`
but they didn't remove this line:
 `<td class="text-start">{{ coupon.status }}</td>`
also, they should remove the sort order code on controller file (line 135):
`$data['sort_status'] = $this->url->link('marketing/coupon.list', 'user_token=' . $this->session->data['user_token'] . '&sort=status' . $url);`

**Comment by TheCartpenter** [comment]
> > That's because the `status` values shows in the `action` field. The `colspan` should also be adjusted accordingly.
> 
> No the colspan not the issue, Opencart change the place of status on the version 4.0.2.3, they remo this: `<td class="text-start"><a href="{{ sort_status }}"{% if sort == 'status' %} class="{{ order|lower }}"{% endif %}>{{ column_status }}</a></td>` but they didn't remove this line: `<td class="text-start">{{ coupon.status }}</td>` also, they should remove the sort order code on controller file (line 135): `$data['sort_status'] = $this->url->link('marketing/coupon.list', 'user_token=' . $this->session->data['user_token'] . '&sort=status' . $url);`

- https://github.com/opencart/opencart/blob/master/upload/system/helper/db_schema.php#L1429
- https://github.com/opencart/opencart/blob/master/upload/admin/controller/marketing/coupon.php#L125
- https://github.com/opencart/opencart/blob/master/upload/admin/language/en-gb/marketing/coupon.php#L20
- https://github.com/opencart/opencart/blob/master/upload/admin/language/en-gb/marketing/coupon.php#L41
- https://github.com/opencart/opencart/blob/master/upload/admin/model/marketing/coupon.php
- https://github.com/opencart/opencart/blob/master/upload/admin/controller/marketing/coupon.php#L143

All these files contains the ```status``` field except the coupon_list.twig file with the ```sort_order```. It rather looks like it is missing rather than removing the rest of the entries containing the ```status``` field since this field is also located in the ```system/helper/db_schema.php``` file in the ```coupon``` table as it should be.

**Comment by Samdz19** [comment]
> > > That's because the `status` values shows in the `action` field. The `colspan` should also be adjusted accordingly.
> > 
> > 
> > No the colspan not the issue, Opencart change the place of status on the version 4.0.2.3, they remo this: `<td class="text-start"><a href="{{ sort_status }}"{% if sort == 'status' %} class="{{ order|lower }}"{% endif %}>{{ column_status }}</a></td>` but they didn't remove this line: `<td class="text-start">{{ coupon.status }}</td>` also, they should remove the sort order code on controller file (line 135): `$data['sort_status'] = $this->url->link('marketing/coupon.list', 'user_token=' . $this->session->data['user_token'] . '&sort=status' . $url);`
> 
> * https://github.com/opencart/opencart/blob/master/upload/system/helper/db_schema.php#L1429
> * https://github.com/opencart/opencart/blob/master/upload/admin/controller/marketing/coupon.php#L125
> * https://github.com/opencart/opencart/blob/master/upload/admin/language/en-gb/marketing/coupon.php#L20
> * https://github.com/opencart/opencart/blob/master/upload/admin/language/en-gb/marketing/coupon.php#L41
> * https://github.com/opencart/opencart/blob/master/upload/admin/model/marketing/coupon.php
> * https://github.com/opencart/opencart/blob/master/upload/admin/controller/marketing/coupon.php#L143
> 
> All these files contains the `status` field except the coupon_list.twig file with the `sort_order`. It rather looks like it is missing rather than removing the rest of the entries containing the `status` field since this field is also located in the `system/helper/db_schema.php` file in the `coupon` table as it should be.

No, they can't remove it from all these files, because opencart need it to display the status of coupon,
the db_schema.php is for creating db tables during the install.

**Comment by TheCartpenter** [comment]
> > > > That's because the `status` values shows in the `action` field. The `colspan` should also be adjusted accordingly.
> > > 
> > > 
> > > No the colspan not the issue, Opencart change the place of status on the version 4.0.2.3, they remo this: `<td class="text-start"><a href="{{ sort_status }}"{% if sort == 'status' %} class="{{ order|lower }}"{% endif %}>{{ column_status }}</a></td>` but they didn't remove this line: `<td class="text-start">{{ coupon.status }}</td>` also, they should remove the sort order code on controller file (line 135): `$data['sort_status'] = $this->url->link('marketing/coupon.list', 'user_token=' . $this->session->data['user_token'] . '&sort=status' . $url);`
> > 
> > 
> > 
> > * https://github.com/opencart/opencart/blob/master/upload/system/helper/db_schema.php#L1429
> > * https://github.com/opencart/opencart/blob/master/upload/admin/controller/marketing/coupon.php#L125
> > * https://github.com/opencart/opencart/blob/master/upload/admin/language/en-gb/marketing/coupon.php#L20
> > * https://github.com/opencart/opencart/blob/master/upload/admin/language/en-gb/marketing/coupon.php#L41
> > * https://github.com/opencart/opencart/blob/master/upload/admin/model/marketing/coupon.php
> > * https://github.com/opencart/opencart/blob/master/upload/admin/controller/marketing/coupon.php#L143
> > 
> > All these files contains the `status` field except the coupon_list.twig file with the `sort_order`. It rather looks like it is missing rather than removing the rest of the entries containing the `status` field since this field is also located in the `system/helper/db_schema.php` file in the `coupon` table as it should be.
> 
> No, they can't remove it from all these files, because opencart need it to display the status of coupon, the db_schema.php is for creating db tables during the install.

Your initial post is about removing a TD from the coupon_list.twig file. An adjustment is simply needed since the ```status``` field is showing everywhere else from this page and on the DB. Therefore, no need to remove that line.

**Comment by MarvinKlein1508** [comment]
@TheCartpenter is simply retarded. Of course this column needs to be removed. As you can see (I hope you have eyes) the status of the coupon is being displayed underneith the name of the coupon.

**Comment by Samdz19** [comment]
https://github.com/opencart/opencart/pull/13268#issue-2052877306

**Comment by Samdz19** [comment]
https://github.com/opencart/opencart/pull/13270#issue-2052881673
