### ISSUE TITLE
Subscription related bugs

### ISSUE THREAD

**Issue by tktamas** [opencart/opencart#13138]
Following function is not implemented in the model.
`$this->model_sale_order->getProductByOrderProductId($subscription_info['order_id'], $subscription_info['order_product_id'])
`

Based on my research, this may be the function instead:
`$product_info = $this->model_sale_order->getSubscription($subscription_info['order_id'], $subscription_info['order_product_id']);`

In this case, it loads successfully, but for some reason the product_id in the database is empty, maybe it is not stored correctly when the order is placed?

`Array ( [order_subscription_id] => 13 [order_product_id] => 16 [order_id] => 7 [product_id] => 0 [subscription_plan_id] => 1 [trial_price] => 0.0000 [trial_tax] => 0.0000 [trial_frequency] => day [trial_cycle] => 0 [trial_duration] => 0 [trial_remaining] => 0 [trial_status] => 0 [price] => 0.0000 [tax] => 0.0000 [frequency] => day [cycle] => 1 [duration] => 0 ) `

Related discussion: https://github.com/opencart/opencart/pull/12916#discussion_r1425230064_

**Comment by TheCartpenter** [comment]
Which OC version are you addressing this issue about?

This week, the ```not_null: true``` have all been removed from the DB schema on the MB version. Therefore, could you confirm if the ```order``` is still not storing the ```product_id``` ? I already addressed the issue in the past about the ```subscription_id``` and the ```transaction_id``` field in the ```addOrder``` method from checkout/order that needed to be declared as well but that was before the removal of ```not_null: true``` .

**Comment by tktamas** [comment]
It is for public: Version 4.0.2.3, but now I will try from this github verion.

**Comment by tktamas** [comment]
Can't test with the latest it has an other bug:
Error: Key column 'article' doesn't exist in table
Error No: 1072

`CREATE TABLE `oc_article_rating` ( `article_rating_id` int(11) AUTO_INCREMENT, `article_id` int(11), `article_comment_id` int(11), `store_id` int(11) DEFAULT '0', `customer_id` int(11) DEFAULT '0', `rating` tinyint(11), `ip` varchar(40), `date_added` datetime, PRIMARY KEY (`article_rating_id`), KEY `article_id` (`article`), KEY `article_comment_id` (`article_comment`), KEY `customer_id` (`customer`), KEY `store_id` (`store`) ) ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_general_ci`

**Comment by TheCartpenter** [comment]
Then, this is a major incident: https://github.com/opencart/opencart/issues/13127 .

**Comment by TheCartpenter** [comment]
See with the commit solution above if that solves the issue and lets you resume with the subscriptions during checkout.

**Comment by danielkerr** [comment]
FFS u guys are reporting bugs for stuff that was purposely disabled because it was not finished.

**Comment by danielkerr** [comment]
tjhe fact that u have large chunks oof code commented out should give a clue

**Comment by tktamas** [comment]
Indeed, it could be a clue, but it's not commented out, and the released version 4.0.2.3 doesn't have the feature disabled.
However, this bug causes the page to crash.
