### ISSUE TITLE
Modified product.twig to fix cart info language in header

### ISSUE THREAD

**Issue by arabyserv** [opencart/opencart#13136]
**Opencart 4.x.x.x**

**Describe the bug**
When add product from product page while i choose secondary language, cart info in header return to default language, we can fix this by modify next line in product.twig

Change This line:
```twig
$('#header-cart').load('index.php?route=common/cart.info');
``` 
To be 

```twig
$('#header-cart').load('index.php?route=common/cart.info&language={{ language }}');
``` 
What section does it affect?
cart info in header 

**To Fix**
1. Go to 'catalog\view\template'
2. Open on 'product.twig.'
3. Scroll down to 'line 374' 
4. Make change above

**Comment by danielkerr** [comment]
i have no idea why some one has added ad to cart on the install page
