### ISSUE TITLE
Reviews filters loss enter data

### ISSUE THREAD

**Issue by Samdz19** [opencart/opencart#13139]
**OpenCart 4.0.2.3**

Using filters of admin reviews page will be lost from the filters fileds but still in adress bar if reload the page.
This code is in wrong place:
From admin/controller/catalog/review.php - lines 308-3012
```
$data['filter_product'] = $filter_product;
$data['filter_author'] = $filter_author;
$data['filter_status'] = $filter_status;
$data['filter_date_from'] = $filter_date_from;
$data['filter_date_to'] = $filter_date_to;

```

then place it before (line 98)
`$data['user_token'] = $this->session->data['user_token'];`

**Comment by TheCartpenter** [comment]
Furthermore, the following controllers also seem to be missing the corresponding entries before the ```$data['user_token']``` line:

- admin/controller/customer/gdpr.php
- admin/controller/customer/customer.php
- admin/controller/customer/customer_approval.php
- admin/controller/marketing/affiliate.php
- admin/controller/marketing/marketing.php
- admin/controller/sale/returns.php
- admin/controller/sale/subscription.php
- admin/controller/sale/order.php
- admin/controller/tool/upload.php

**Comment by danielkerr** [comment]
is it required in customer aprooval and gdpr. i dont think so
