### ISSUE TITLE
[master] Admin / Customer group after sorting without header/footer

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#13155]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
After sorting Customer Group entries only the customer group entries are visible. Missing header/footer.

**To Reproduce**
1. Go to 'Admin/Customer/Customer Group'
2. Click on 'Sort by Customer Group Name' or Sort Order

**Expected behavior**
Admin page complete

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

![customer_group_sort_2023-12-16_23-37-45](https://github.com/opencart/opencart/assets/10166095/408f6e9d-4626-4ed8-8f5e-ba4826756093)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.0.5

**Comment by Samdz19** [comment]
Yes, it's need to edit this : 

> File : admin/view/template/customer/customer_group.twig

And add before `{{ footer }} `
These lines
```
<script>
$('#customer-group').on('click', 'thead a, .pagination a', function (e) {
    e.preventDefault();

    $('#customer-group').load(this.href);
});
</script>
```

**Comment by pemaier** [comment]
@Samdz19  Thank you for your support. I tested it and it is working. I also created a pr.

**Comment by pemaier** [comment]
solved
