### ISSUE TITLE
Customer Subscription Report error  - database

### ISSUE THREAD

**Issue by Samdz19** [opencart/opencart#13241]
**OpenCart 4.0.2.3** clean install

Get this error on Customer Subscription Report

> Warning: Attempt to read property "row" on bool in C:\wamp64\www\oc4023b\extension\opencart\admin\model\report\customer_subscription.php on line 76Warning: Trying to access array offset on value of type null in C:\wamp64\www\oc4023b\extension\opencart\admin\model\report\customer_subscription.php on line 76Warning: Attempt to read property "rows" on bool in C:\wamp64\www\oc4023b\extension\opencart\admin\model\report\customer_subscription.php on line 45Opencart\Admin\Model\Extension\Opencart\Report\CustomerSubscription::getTransactions(): Return value must be of type array, null returned: in C:\wamp64\www\oc4023b\extension\opencart\admin\model\report\customer_subscription.php on line 45

**Describe the bug**
The problem is no subscription_transaction table on opencart database.

**Comment by TheCartpenter** [comment]
```customer_subscription``` has been removed in OC v4.0.2.4 release. I created a PR to remove the rest of the permissions: https://github.com/opencart/opencart/pull/13240/commits/46f33dd58fe2c28a76403535a0109b1f22669e30 . The ```subscriptions``` report has been recently integrated.

**Comment by danielkerr** [comment]
i think some one added it back
