### ISSUE TITLE
PHP Warning:  Undefined array key 1 in /home/wenbo/public_html/catalog/controller/startup/seo_url.php on line 83

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#13251]
https://github.com/opencart/opencart/blob/b9a0bce0c1551d82ec3d6c506ded457f7a2e8923/upload/catalog/controller/startup/seo_url.php#L83

**Comment by danijelGombac** [comment]
Maybe [$key, $value] = array_pad(explode('=', $part, 2), 2, '');

**Comment by cgcmart** [comment]
This error did not fix either in v4.0.2.3 or master.
However, @PhamToan 's patches (https://github.com/opencart/opencart/pull/11609
https://github.com/opencart/opencart/pull/11610) are still the one solution.
