### ISSUE TITLE
Issue with ocmod for extentions folder

### ISSUE THREAD

**Issue by Samdz19** [opencart/opencart#13260]
**OpenCart 4.0.2.4**

Trying to use OCMOD for make modification on the extentions folder,

I got the files for example:

> extension/ocmod/extension/opencart/admin/controller/report/customer_order.php
> extension/ocmod/extension/opencart/admin/view/template/report/customer_order_list.twig

but I didn't get any changes.

Also, I have tried to replcae this example but in the two ways not working:

> Opencart\Admin\Controller\Extension\Opencart\Report;

to:

> Opencart\Admin\Controller\Extension\Ocmod\Extension\Opencart\Report;

or to :
> Opencart\Admin\Controller\Extension\Ocmod\Opencart\Report;

but I didn't get any changes.

**Comment by pemaier** [comment]
@Samdz19 The modification system is in development. I have also the problem that the ocmod.xml files are not working now with the newest master code. Even not in the development mode (file in system folder). If you build up the modification result in exension/ocmod/.. then you can see simple changes e.g. setting username demo in the admin login.

**Comment by stalker780** [comment]
Modification system is not in development any more. It is ready. Daniel asked to check and report about issues.

**Comment by pemaier** [comment]
@stalker780 Anton thank you for the info.

**Comment by Samdz19** [comment]
> Modification system is not in development any more. It is ready. Daniel asked to check and report about issues.

but why they added in the version 4.0.2.4 ?
I have tested it's working with admin and catalog folder it's working, but with extenstion folder I get files but without result

**Comment by Samdz19** [comment]
> @Samdz19 The modification system is in development. I have also the problem that the ocmod.xml files are not working now with the newest master code. Even not in the development mode (file in system folder). If you build up the modification result in exension/ocmod/.. then you can see simple changes e.g. setting username demo in the admin login.

@pemaier the old way to write the xml file not working, you need to check the ocmod example (working for controller, model, view and library folder), and you nedd to replace the **namespace**
check the file: **oc_ocmod_example.ocmod**

**Comment by pemaier** [comment]
@Samdz19 I have opened a new issue with an extension included. It was working 2 weeks ago. #13261

**Comment by danielkerr** [comment]
this feature should work. there is a test ocmod to test all the different file paths.

**Comment by danielkerr** [comment]
i dont think its a good way to do things using ocmod to add files. its there to modify ones that are there.
