### ISSUE TITLE
Register account error

### ISSUE THREAD

**Issue by Samdz19** [opencart/opencart#13267]
**OpenCart 4.0.2.4**

Got this error on register a customer,

> Cannot assign null to property Opencart\System\Library\Cart\Customer::$safe of type bool: in C:\wamp64\www\oc4024a\system\library\cart\customer.php on line 84

Need to edit this :

> catalog/model/account/customer.php

**Comment by Samdz19** [comment]
https://github.com/opencart/opencart/pull/13269#issue-2052880503

**Comment by danielkerr** [comment]
Should be fixed now
