### ISSUE TITLE
[master] modification system problems

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#13261]
**What version of OpenCart are you reporting this for?**
master from today
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
the modification system

**To Reproduce**
1. Go to 'upload the appended extension'
2. Click on 'install the extension'
3. Goto modification and enable the modification then click refresh 
4. See error - log file get updated only after page refresh
5. Then logout
6. See error - no entries in login form 

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.0.5

**Additional context**
Appended extension:
[occ_demo_login.ocmod.zip](https://github.com/opencart/opencart/files/13732543/occ_demo_login.ocmod.zip)

The modification files (extension/ocmod/...) are not present/generated. ~Two weeks ago it was working.

**Comment by Samdz19** [comment]
@pemaier I got generated files, but the language file not working, generated but didn't got result.
Also, tried to get the modification on the opencart extention folder, not working, I make change on modification and extention files without any fixes.

**Comment by danielkerr** [comment]
u need to mod the file paths.

**Comment by danielkerr** [comment]
o ruse events to override the paths

**Comment by pemaier** [comment]
Do I understand you right, that e.g. admin/... is not usable anymore. It has to be used the "new" changed path?
If so I can only make individual modifications because I don't know then new path name the customers choose?

**Comment by danielkerr** [comment]
WHICH SIDE DID U DO THIS ON? THE FRONT OR THE BACK. I HAVE JUST ADDED TOT HE FRONT SO SHOULD BE OK NOW
