### ISSUE TITLE
[Master] CMS > Comments (list and view) >> double action buttons without functions

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#13275]
OC 4..0.2.4 [Master]

The bug: list comments display top right 3 buttons to: Approve, Spam and Delete (they work as expected).

![grafik](https://github.com/opencart/opencart/assets/1905204/c0826e51-711f-4f7b-8d4a-7e0ff1ed2898)

But same buttons are displayed again when a comment is opened (in modal window) and lead to a json error only because the main function is called and the whole page (list) is returned!
![grafik](https://github.com/opencart/opencart/assets/1905204/0d222a77-10bf-464b-9dfc-a6166ae66343)

See https://github.com/opencart/opencart/blob/2e227cd31466c919722332137f98672ab9bfacb9/upload/admin/view/template/cms/comment.twig#L6
and
https://github.com/opencart/opencart/blob/2e227cd31466c919722332137f98672ab9bfacb9/upload/admin/view/template/cms/comment_list.twig#L63

Either 
(1) delete the first buttons in the overview (list) - not recommended
(2) delete the buttons inside the modal
(3) add correct links to the buttons in the modal view

(3) is basically useless, because the action is already done in list view ..
Same goes for (2)

**Comment by TheCartpenter** [comment]
I think he's still working on the CMS folder.

**Comment by osworx** [comment]
@TheCartpenter Maybe .. or not ..
Better to highlight bugs before they got lost ..

**Comment by TheCartpenter** [comment]
> @TheCartpenter Maybe .. or not .. Better to highlight bugs before they got lost ..

Couldn't agree more. However, there's a difference between development stages and bugs: https://github.com/opencart/opencart/discussions/13071#discussioncomment-7805314

**Comment by danielkerr** [comment]
i need to push the changes ive done in case my HD goes down. maybe i should do my own branch and merge when features are complete

**Comment by osworx** [comment]
> i need to push the changes ive done in case my HD goes down. maybe i should do my own branch and merge when features are complete

Please let us all know when you have done, then we can go forward with testing (because seems useless in the current stage).
