### ISSUE TITLE
Phone number and Postal Code validation

### ISSUE THREAD

**Issue by commandodhruva** [opencart/opencart#133]
Phone number and Postal Code accept alpha numeric characters. Should only accept numbers.
This creates problems while sending info for payment processing.

**Comment by shekharvermaj** [comment]
the developers are rude here. commandodhruva was right same problem i am facing and looking for help but i found here this rudely arguments except any help to existing or new customers i like most opencart and his support but what's wrong with developer i don't know what the hell is going here?
anyway i found the way to switch to woo commerce or drupal
Thanking You!!!

**Comment by anayakart** [comment]
I am looking for an opencart developer who can develop some extensions and do some customizations. I am using webkul marketpalce so all customization will be related to that.

**Comment by anayakart** [comment]
I am looking for an opencart developer who can develop some extensions and do some customizations. I am using webkul marketpalce so all customization will be related to that. Only experienced developer contact me.  anayakart@gmail.com
