### ISSUE TITLE
Stored payment methods

### ISSUE THREAD

**Issue by Samdz19** [opencart/opencart#13329]
**OpenCart v4.0.2.4 clean install**

got this error message when try to access to stored payment method from customer account:

> Notice: Undefined property: Proxy::getStored in C:\wamp64\www\oc4024c\catalog\controller\account\payment_method.php on line 94: in C:\wamp64\www\oc4024c\system\engine\proxy.php on line 87

**Comment by danielkerr** [comment]
its part of the subscription that im working on.

https://github.com/opencart/opencart/issues/11458
