### ISSUE TITLE
Images not visible with image manager

### ISSUE THREAD

**Issue by mewolari** [opencart/opencart#1332]
I used opencart 1.5.6.1. Images were shown as in attachment 1.5.6.1.jpg

After upgrade to opencart 1.5.6.2, the images are not displayed anymore. Also not able to select images anymore. Using a clean install (only with demo shop) without any addons.

After that I completely removed everything and performed a clean install (only with demo shop) with 1.5.6.2, but same problem occurs.

![1 5 6 2](https://cloud.githubusercontent.com/assets/2721621/2686656/b0c553de-c214-11e3-897d-5d7aadaac3d7.jpg)
![1 5 6 1](https://cloud.githubusercontent.com/assets/2721621/2686657/b0c609a0-c214-11e3-8f58-70bc0c2f08a2.jpg)

**Comment by arnisjuraga** [comment]
Are you using 1.5 or 2.x OC?

**Comment by arnisjuraga** [comment]
Which Opencart version are you using? This issue is old one, and comments are done for version 1.5.
If you have downloaded latest Opencart from Git, then you should create a new issue. 
Also include, are you using **Windows** or **Linux**

**Comment by osworx** [comment]
And to both: discuss such in the forum, not here!

**Comment by Dhthakkar** [comment]
@arnisjuraga 
I am using windows and I have downloaded new latest opencart. but leave it..

**Comment by choikinfat** [comment]
Just

chmod 777 -R image/
