### ISSUE TITLE
Looking for Documentation on Modification System!

### ISSUE THREAD

**Issue by DS-Matt** [opencart/opencart#1336]
NOTE - THIS IS NOT AN ISSUE - THIS IS A QUESTION BUT I'M NOT ABLE TO SELECT LABELS FOR ISSUES ON THIS REPO!

Yesterday I set up a local copy V2.0 using mPDO, I then tired to install VQMod to see if my V1.5.X mods would work with V2.0 and what I'd need to make the modules work.  Unfortunately when installing VQmod my whole site broke and I received js notifications and an error message stating: 

"Unable to load mPDO driver".  After removing the VQMod changes to index.php in the root and admin directories everything was working again.

So I'd like to port my modules over to the new modification system to ensure they play nicely with V2.0, when it's released. I know Daniel and James are really busy with managing the code base and adding in new features, so is there anyone who can start to write up some documentation on the Modification system (such as HostJars - who currently does the documentation management or @mhcwebdesign - since you seem to have a good understanding of how the opencart modification system works).  

Thanks!

DS-MATT

**Comment by ankita2015** [comment]
opencart first native app 
</br>
Create branded native storefront opencart apps on iPhone, iPad and Android !
</br>
seamlessly integration of your online store with the opencart-mobile app !
</br>
No core file overwritten. It takes your existing opencart configuration and database and yet is fully customizable as independent APP. 
</br>

See Features and pricing on <a href="http://opencartmobileapp.com/" style="color: rgb(0, 0, 0); text-transform: uppercase; text-decoration: none; text-align: justify;">opencartmobileapp.com </a>

**Comment by ankita2015** [comment]
Our Mobile is a Powerful, Fully Responsive & Multi-Purpose OpenCart Mobile App for any type of store, inspired by the best eCommerce solutions and designed with great attention to details and usability in mind.

Opencart Mobile App is built For Fast Connectivity And Best Performance This Is The Best And First Opencart Native App.

You Dont Need Any Change In App, No core file overwritten. It takes your existing opencart configuration and database and yet is fully customizable as independent APP.  

Our Mobile App is the right solution for your online business. Your store look be amazing and Customer Love And Like Very Much Your Store!

If You Have Any Query Please Contact Our Administrator.

The Opencart Mobile App is a Multipurpose Responsive and multi-language support OpenCart Application. If you want to have a very unique and attractive design and trying to make fast and more reliable your way among numerous store owners, Opencart Mobile App is a great starting point for you.
visit today -: http://opencartmobileapp.com/

**Comment by ankita2015** [comment]
opencart first native app 


Features
Create branded native storefront opencart apps on iPhone, iPad and Android !
seamlessly integration of your online store with the opencart-mobile app !

Mobile App gets ready for your store in 20 minutes and just need few new files uploaded. No core file overwritten. It takes your existing opencart configuration and database and yet is fully customizable as independent APP. You don’t have to do anything extra to make this APP live.

**Comment by ankita2015** [comment]
See Features and pricing on  http://opencartmobileapp.com/
 Opencart-mobile App Feature List! 
1.Multilanguage Support, 2. Multi Currencies Support, 3. All shipping method support, 4. All payment method support, 5. Coupons/ Vouchers/Reward Points Supported, 6. Wishlist Supported, 7. Share To friends Via email, apps, Bluetooth etc., 8. Independent Featured Module, 9. Independent Slideshow, 10. Individual Banner, App Icon and App name, 11. Opencart Login/Register with Local, FB or Goolge+, 12. All Customer Field Validation With Inherited customer profile, 13. Customer Image, 14. Forget password, 15. Multiple shipping address, 16. Support all cart validation, 17. Special/discount support, 18. Checkbox/ radio/ dropdown- product option support, 19. Attributes support, 20. Reviews- add/view support, 21. Product image carousal zoom support, 22. Tags support, 23. Special price end timer support, 24. Category/sub category method support, 25. Category Sort support, 26. View orders support, 27. My downloads support, 28. Push notification support on multi languages, 29. Enhanced filter support, 30. Create easy filter on category by Product options support, 31. Create easy filter on category by Opencart Category Filters, 32. Information pages support, 33. Contact admin page, 34. Logo app color , background, price color Changeable, 35. Related product support, 36. Customer preferred language currency support, remembered by APP, 37. All checkout Method/Process/Rules Totals/ Validations Supported .
