### ISSUE TITLE
DB Advanced accordition is not displayed by first time step3 install

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#13454]
**What version of OpenCart are you reporting this for?**
github

**Describe the bug**
When you try to install Opencart, MySQLi driver is selected by Default, but Advanced accordition is not displayed.
You need to select mPDO driver, then MySQLi driver and finaly Advanced accordition it show.

Is not suposed to be shown for first time?

**Comment by danielkerr** [comment]
mpdo wont work uness u enable the extension in the php.ini

**Comment by danielkerr** [comment]
I can't work out what u mean.

works fine:

![image](https://github.com/opencart/opencart/assets/5079756/d257e634-ea45-4a05-9d3f-d4f7a260d8cc)

**Comment by condor2** [comment]
For MYSQLi you have Advanced accordition where you can enter SSL certificate.....

**Comment by danielkerr** [comment]
i thought they could add it after

**Comment by danielkerr** [comment]
ahh ok
