### ISSUE TITLE
[3.0.x.x] Paypal Checkout & Recurring Orders

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#13485]
Because Payapal Checkout was added to 3.0.x.x a new paypal controller is needed for recurring orders.

https://github.com/opencart/opencart/tree/3.0.x.x/upload/catalog/controller/extension/recurring

**Comment by mhcwebdesign** [comment]
Why? Does the extension/recurring/pp_express.php clash with the extension/payment/paypal.php ?

**Comment by condor2** [comment]
I don't know if pp_express is still working :)

**Comment by TheCartpenter** [comment]
Taking care of that for OC v4.x releases already.

**Comment by mhcwebdesign** [comment]
OK, looking at it, the **catalog/controller/extension/recurring/pp_express.php** uses some settings from the now non-existing **admin/controller/extension/payment/pp_express.php**, such as these:

payment_pp_express_test
payment_pp_express_sandbox_username
payment_pp_express_sandbox_password
payment_pp_express_sandbox_signature
payment_pp_express_username
payment_pp_express_password
payment_pp_express_signature

So we got 2 options:

1. Remove recurring/pp_express
2. Add the missing payment/pp_express

Does anyone know whether pp_express still works on OC 3.0.3.9 , or 3.0.x.x? Especially also for PHP 8.x versions?

**Comment by TheCartpenter** [comment]
3.2 already has option 1 built-in.

**Comment by mhcwebdesign** [comment]
Would this work for OC 3.0.x.x? If not, could you backport it? Also, is it based on the latest al Checkout Integration extension from the OpenCart marketplace?

**Comment by TheCartpenter** [comment]
What I do know is 3.2 has the latest bugfixes on PayPal Checkout since downloaded from the Marketplace and that multiple pp_express files have been removed from 3.0.x.x branch since the PayPal Checkout min. version has been integrated. Therefore, since there were already deleted files involved during the integration, I wouldn't count much on it while reviewing the 3.0.x.x changelogs that shows the details along with this integration already.

**Comment by mhcwebdesign** [comment]
So does the PayPal Checkout Integration from the OC marketplace already include support for recurring payments? Or is it something you added for the opencart-3 repository?

**Comment by TheCartpenter** [comment]
Already supports it with the old recurring payments but does require multiple patching whereas OC 3.2 includes in.

**Comment by TheCartpenter** [comment]
Since this morning, the ```charge``` method has also been included in the OC v3.2x release in order to proceed with OC v4.x releases later on with the customers based on different subscription plans store owners should already be able to handle with the ```cron``` on the same method with their extensions.
