### ISSUE TITLE
Gift certificate monitoring.

### ISSUE THREAD

**Issue by nrno007** [opencart/opencart#13489]
V 4.0.23

There's no possibilities to check credit (rest) balance of th Gift Certificate so the receiver can monitor it to plan future purchase. Big miss !!!
It exist some old not updated extensions for the previous versions but it should be very nice if it should be integrated in the OC.
Thanks. ;)

Nino

**Comment by TheCartpenter** [comment]
If the extension is free, and provided by Opencart, what extension are you referring to?

**Comment by nrno007** [comment]
For examplle this one:
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=37813&filter_search=gift%20certificate&filter_license=0

Is it suitable for 4.0.23 ?

**Comment by TheCartpenter** [comment]
> For example this one: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=37813&filter_search=gift%20certificate&filter_license=0
> 
> Is it suitable for 4.0.23 ?

While this extension is free, it is provided by a contributed user on the OC Marketplace.

**Comment by nrno007** [comment]
It is not the issue - it is not compatible with 4.0.23 !

Ii tried to install it but I couldn't.

**Comment by condor2** [comment]
Of course is not compatible. Compatibility3.0.1.2, 3.0.2.0

**Comment by danielkerr** [comment]
u should be able to see the balance from the customer transactions page
