### ISSUE TITLE
Bug after returning backup

### ISSUE THREAD

**Issue by nrno007** [opencart/opencart#13490]
V 4.0.23

I have made an backup (files and DB)  and removed production site (because I'm building it locally by Wamp-the latest version).
When I returned it online to the server, it was missing the small icons on the top. After changing language everything was returned.

![IMG_20240109_142546](https://github.com/opencart/opencart/assets/156097209/dc8bb255-39ef-42fd-b07a-7242ad31ad13)
![IMG_20240109_142620](https://github.com/opencart/opencart/assets/156097209/c5a8bcce-7269-4212-b540-b8401d8d6239)

**Comment by danielkerr** [comment]
looks like its reading the css and js from the wrong domain. check if all urls are ssl. makje sure the sotre url matches up

**Comment by nrno007** [comment]
Hi there.

Thank you very much for your reply.
Unfotunatelly, I'm not skilled in developing, I'm just making my new online store.
Can you clarify me please how and what I need to do since I just returned what I saved like a backup?
What I did wrong or, how can I prevevnt it to occure next time?
The first address is main (root) address and the second, when I'm mclicking on the language has /index.php?route=common/home&language=en-gb  sufix. Both are ssl  (all are...).

Sorry to be boring and thank you.

**Comment by danielkerr** [comment]
u need to edit the settings in the admin or alter ur config.php too match the domain u are visiting
