### ISSUE TITLE
syntax error, unexpected identifier "SELECT"

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#13494]
https://github.com/opencart/opencart/blob/e9415601b9dc4fbd9e41d330560627c03bc06300/upload/catalog/model/cms/article.php#L28C4-L28C4

Error logged. What's wrong?

**Comment by condor2** [comment]
When you do what?
No error for me

**Comment by danielkerr** [comment]
being worked on

**Comment by cgcmart** [comment]
today.
I viewed it seemed
L17 passed:
		$query = $this->db->query("SELECT DISTINCT * FROM `" . DB_PREFIX . "article` `a` LEFT JOIN `" . DB_PREFIX . "article_description` `ad` ON (`a`.`article_id` = `ad`.`article_id`) LEFT JOIN `" . DB_PREFIX . "article_to_store` `a2s` ON (`a`.`article_id` = `a2s`.`article_id`) WHERE `a`.`article_id` = '" . (int)$article_id . "' AND `ad`.`language_id` = '" . (int)$this->config->get('config_language_id') . "' AND `a2s`.`store_id` = '" . (int)$this->config->get('config_store_id') . "' AND `a`.`status` = '1'");

but L28 logged error:
syntax error, unexpected identifier "SELECT"

**Comment by cgcmart** [comment]
@condor2 I uploaded catalog/model/cms/article.php to sql syntax check and validator on an online tool
That showed INVALID SQL
SyntaxError: Expected "#", "$", "(", "+", "-", "--", "/*", ";", "@", "@@", "ALTER", "CALL", "CREATE", "DELETE", "DESC", "DESCRIBE", "DROP", "GO", "INSERT", "LOCK", "RENAME", "REPLACE", "SELECT", "SET", "SHOW", "TRUNCATE", "UNLOCK", "UPDATE", "USE", "WITH", "return", [ \t\n\r], [0-9], [A-Za-z_], or end of input but "<" found.

**Comment by cgcmart** [comment]
It seems need to rework identifiers,  have to double-quote, consistent with the UI behavior.

**Comment by cgcmart** [comment]
Error: Could not call registry key model_cms_article! ../system/engine/controller.php on line 41

It seems this issue specially from only opencart when search the error on internet.
