### ISSUE TITLE
[3.0.x.x] wechat_pay issues

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#13518]
Is anyone still using the wechat_pay at all? I am thinking about removing wechat_pay from OC 3.0.x.x.

It relies on an abandoned vendor package 'zoujingli/wechat-php-sdk', the composer software always comes up with this warning:

Package zoujingli/wechat-php-sdk is abandoned, you should avoid using it. Use zoujingli/wechat-developer instead.

While OC 3.0.x.x has the recommended 'zoujingli/wechat-developer' vendor package, the wechat_pay doesn't use it yet.

**Comment by danielkerr** [comment]
ill get my staff to contact them

**Comment by mhcwebdesign** [comment]
Any news yet from the wechat_pay developers and/or authors?

**Comment by mhcwebdesign** [comment]
OK, we'll keep the package **zoujingli/wechat-php-sdk** in there till we hear back from the wechat_pay author.
