### ISSUE TITLE
[master] Frontend - Wishlist is loosing entries

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#13527]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
The problem is that products which are not available in all stores are getting lost in the wishlist of a customer if this customer is changing between the stores.

Situation
Product A - Available in Store 0 (Default) and Store 1
Product B - Available only in Store 0
Product C - Available only in Store 1

**To Reproduce**
Customer login to Store 0
customer add Product A and B in Store 0 (Default) to the wishlist
then login to Store 1
customer add Product A and C in Store 1 to the wishlist
then login/go to Store 0 again
then in the wishlist is only Product A
then login/go to Store 1 again
then in the wishlist is only Product A
Product B and C are lost 

**Expected behavior**
All wishlist entries should be present in the related store wishlist

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app
[Screencast 2024-01-12 14:06:14.webm](https://github.com/opencart/opencart/assets/10166095/63863b99-29fa-4a5b-990a-cf2fd5581f19)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.6.0esr

**Comment by danielkerr** [comment]
so i need to add storye id to wish list

**Comment by pemaier** [comment]
I also think that should solve the issue. I'm only not sure if it allowed to add an table column or better what I was thinking about a new table card_to_store to keep the structure?

**Comment by pemaier** [comment]
update ... with Cart we have the same issue.
