### ISSUE TITLE
Reset button not working on all pages, and suggestion for reset button

### ISSUE THREAD

**Issue by Samdz19** [opencart/opencart#13546]
**OpenCart 4.0.24**

The new reset button not working on all pages, the filters fileds clean, but the list didn't reloaded and the link stay the same when use filer button.

Also, as suggestion to change the reset button style. like this picture
![pic1](https://github.com/opencart/opencart/assets/149782656/9f747c62-774c-4512-8e48-ea2f91fb1d8b)

I have edit the code from:

```
  <div class="text-end">
    <button type="button" id="button-filter" class="btn btn-light"><i class="fa-solid fa-filter"></i> {{ button_filter }}</button>
    <button type="reset" data-bs-toggle="tooltip" title="{{ button_reset }}" class="btn btn-outline-secondary"><i class="fa-solid fa-filter-circle-xmark"></i></button>
  </div>
```

to this

```
  <div class="mb-3 hstack gap-2">
    <div class="text-start">
      <button type="reset" id="button-reset" class="btn btn-light"><i class="fa-solid fa-filter-circle-xmark"></i> {{ button_reset }}</button>
    </div>
    <div class="ms-auto">
      <button type="button" id="button-filter" class="btn btn-light"><i class="fa-solid fa-filter"></i> {{ button_filter }}</button>
    </div>
  </div>
```

**Comment by pemaier** [comment]
Hello Samdz19 thank you for your support. I was testing your new code. It is cleaning the filter but a reload doesn't happens at my test shop. May I'm missing something? I simply replaced your code with the present code as described. 
From the button location I specially placed the reset button near the filter button because it is simple and fast to work this way for massive usage.

**Comment by Samdz19** [comment]
@pemaier I didn't change the code, I only change the style and keep the same funtion,
It's not working on all the page, orders, customer, reviews, report, with my style or with the exisiting style, on version 4.0.2.4

**Comment by danielkerr** [comment]
checking the code but  that is dumb

**Comment by danielkerr** [comment]
i found one missing and fixed it
