### ISSUE TITLE
no error message and help text purchase text

### ISSUE THREAD

**Issue by Samdz19** [opencart/opencart#13545]
**OpenCart 4.0.2.4**

In Purchase a Gift Certificate page we can add voucher without check agree button, also the amout help text missing,
i have fix by:

> file: catalog/controller/checkout/voucher.php

edit this
`if (!isset($this->request->post['agree'])) {`
to
`if (!$this->request->post['agree']) {`

> file: catalog/view/template/checkout/voucher.twig

after this:
`<div id="error-amount" class="invalid-feedback"></div>`
add
`<div class="form-text">{{ help_amount }}</div>`

**Comment by rasulsh** [comment]
Hello @Samdz19,

The issue you reported has been addressed in the following pull request: [PR #13779](https://github.com/opencart/opencart/pull/13779).
