### ISSUE TITLE
[master] admin - security process

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#13548]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
The install is working partly. The admin folder is getting copied to admin0 but the admin folder is not getting deleted. At the step to rename the admin folder is shown an error. The config files are writeable and the changes in the config files is done. So it is only a wrong information which stops the process.

**To Reproduce**
- New install
- Login into admin
- go through the steps of the security process
- when changing the admin folder it needs a long time and throw an error.
- see error
 
**Expected behavior**
normal close of the security process

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app
![image](https://github.com/opencart/opencart/assets/10166095/f844bd3b-2f56-42b5-a44c-7e959421d328)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.6.0esr

**Comment by danielkerr** [comment]
pretty sure this is a misconfiguration on ur end. like making sure the php user has p-ermission to write to files

**Comment by pemaier** [comment]
I use an install script in combination with install_cli and and the install process is working well.
The part which is not working is the manual part after the automatic Installation after the 1st. login when the user has to delete the install folder (ok) then to move the storage folder (ok) and then the move of the admin folder (not ok). 
The new admin folder is getting created and the files are copied. The config file in the new folder is not changed and the old admin folder is not deleted. From the environment on the server I changed nothing the last 4 month and on the localhost also no changes in the last time. So I have two different ways with the same result.

**Comment by danielkerr** [comment]
should be fully working now

**Comment by pemaier** [comment]
Thank you. I was doing a screen-cast about the new behavior. 
I don't know if it is a planned separation of deleting the ( installation ) admin folder.
I tested it on the server.
[Screencast 2024-01-27 12:00:40.webm](https://github.com/opencart/opencart/assets/10166095/cd91af33-ed12-453b-9898-4224735b0a87)
