### ISSUE TITLE
Can not receive order confirmation but can receive message which customers left.

### ISSUE THREAD

**Issue by Boheng2013** [opencart/opencart#13575]
**What version of OpenCart are you reporting this for?**
2.3.0.2

I am using 2.3.0.2, and everything is normal until this afteroon, all the orders report this error, and customers and I can not receive order confirmation emails. the error is as below:

### Detected at URL: [index.php?route=extension/payment/paypal/webhook](https://www.***.com/index.php?route=extension/payment/paypal/webhook)
Uncaught Exception: Error: DATA not accepted from server! in system/storage/modification/system/library/mail.php:376
Stack trace:
#0 [system/storage/modification/catalog/model/checkout/order.php(937):](https://www.***.com/index.php?li_source=system/storage/modification/catalog/model/checkout/order.php(937):) Mail->send()
#1 [vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php(196):](https://www.***.com/index.php?li_source=vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php(196):) ModelCheckoutOrder->addOrderHistory('167950', '2', '', true)
#2 [system/engine/proxy.php(25):](https://www.***.com/index.php?li_source=system/engine/proxy.php(25):) Loader->{closure}(Array, Array)
#3 [catalog/controller/extension/payment/paypal.php(766):](https://www.***.com/index.php?li_source=catalog/controller/extension/payment/paypal.php(766):) Proxy->__call('addOrderHistory', Array)
#4 [catalog/controller/extension/lightning/beta.php(262):](https://www.***.com/index.php?li_source=catalog/controller/extension/lightning/beta.php(262):) ControllerExtensionPaymentPayPal->webhook()
#5 [vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(34):](https://www.***.com/index.php?li_source=vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(34):) Wkn(Array, 'extension/payme...', 'webhook')
#6 ca in [system/storage/modification/system/library/mail.php:376](https://www.***.com/index.php?li_source=system/storage/modification/system/library/mail.php:376)

Customers can leave message with no problem, only the problem with order notifications.

**Comment by ADDCreative** [comment]
Could be a timeout issue or your email provider rejecting the mail for some reason, such as detecting it as spam. You would be best to post on the OpenCart forums for help. https://forum.opencart.com/

**Comment by Boheng2013** [comment]
Yes, you are correct. The error last about 2 hours, and now the emails come out gradually./
Seems like the mail provider solved the problem by adding whitelist.
Thank you for the answer.
