### ISSUE TITLE
The store doesn't load correctly

### ISSUE THREAD

**Issue by 4DRIAN0RTIZ** [opencart/opencart#13579]
**What version of OpenCart are you reporting this for?**
3.0.3.9

**Describe the bug**
The main page of my store is not working and the theme is'nt applied.
The main page shows "Unknown: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /path/to/public_html/system/engine/action.php on line 65"

**To Reproduce**
1. Go to 'https://mechanicshop.com.mx'
2. 4. See error

**Expected behavior**
The page should display correctly.

**Screenshots / Screen recordings**
I noticed, that it is not loading correctly the applied theme name when loading the css files.
![imagen](https://github.com/opencart/opencart/assets/105228934/89b9686b-b8a5-427d-ac6d-da44da22c009)
I was update opencart today, using the web install <site.com/install> without any error.

**Comment by mhcwebdesign** [comment]
Please repost on the OpenCart forum to get help. And also provide some more details. In general, don't use the buil-in upgrade feature, do a fresh install, and then re-install  all your extensions and themes, and copy your data using the Export/Import tool which you can get here: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=17
