### ISSUE TITLE
[Master] - admin/controller/marketplace/modification.php

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#13576]
https://github.com/opencart/opencart/blob/master/upload/admin/controller/marketplace/modification.php#L438C17-L438C113

Causing this error message: ```Binary operation "+" between (float|int) and non-empty-string results in an error.```

**Comment by danielkerr** [comment]
i think i9ts already fixed here:

https://github.com/opencart/opencart/commit/b0a9262e9188b178e9a1fa2b979b00b4559f8ced
