### ISSUE TITLE
Pagination controller and template

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#13580]
@danielkerr Do you have any plans to combine pagination into single controller and template?

Now it is separated to pagination and results. Also it has lots of repeated code hardcoded into templates and other controllers.

If a developers needs to modify pagination functionality/design it turns into a nightmare of deleting hardcoded templates and causes lots of issues with 3rd party extensions compatibility both in admin and frontend.

I have proposed a PR https://github.com/opencart/opencart/pull/13287
But it was merged and then reverted https://github.com/opencart/opencart/pull/13291

**Comment by danielkerr** [comment]
no idea what u are talking about

**Comment by danielkerr** [comment]
no m8

**Comment by stalker780** [comment]
@danielkerr I am talking about moving repeated html code from lists to a separate pagination.twig

So we can modify/reroute pagination controller and pagination template instead of modifying with OCMOD over 100 template files.

For example I need to relocate `results`. and change the structure of pagination html. I need to do this with JS. Cause it is not possible to this neither with events nor with OCMOD.

OC already has pagination controller and pagination template. Why not to use them? Pagination is identical on every single list.

This html code hardcoded in every list template:
https://github.com/opencart/opencart/blob/2c9b039c1b416f9257674bb6f797966139dd49ea/upload/admin/view/template/catalog/product_list.twig#L64C3-L67C9
 must be a single variable:
`{{ pagination }}`

While all pagination content should be located in upload/admin/view/template/common/pagination.twig

This is related both to admin and frontend.

Please check my PR https://github.com/opencart/opencart/pull/13287

**Comment by TheCartpenter** [comment]
In other words, to use the ```dataType: html``` from an Ajax request to pull the same pagination content from the ```common/pagination.twig``` file.

**Comment by stalker780** [comment]
@TheCartpenter No. What I propose is not related to ajax calls at all.
I have mentioned a working PR as example.

**Comment by TheCartpenter** [comment]
> @TheCartpenter No. What I propose is not related to ajax calls at all. I have mentioned a working PR as example.

You are rather moving all results into a single location which would still interfere with the remote pagination from APIs. What if there's a modification that needs to be done from an extension in order to pull the data? Would each data be pulled accordingly if it were to load from the same controller?
