### ISSUE TITLE
[4.0.2.3] Product Review Issue

### ISSUE THREAD

**Issue by kazimshawon** [opencart/opencart#13603]
[4.0.2.3]

On catalog->controller->product->review.php page
Line number 88 
there is product model loaded but model folder is wrong it should be :

$this->load->model('catalog/product');
and
$product_info = $this->model_catalog_product->getProduct($product_id);
![Capture](https://github.com/opencart/opencart/assets/54492784/4794f9f9-e228-4a9e-890c-ad7e4db4458a)

**Comment by mhcwebdesign** [comment]
Already fixed in the master branch for the upcoming 4.0.2.4.
