### ISSUE TITLE
[3.0.3.9] Auto UPdate Currency Not Working

### ISSUE THREAD

**Issue by WebSpectrum** [opencart/opencart#13600]
**What version of OpenCart are you reporting this for?**
3.0.3.9
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Currencies, when using mutiple currencies
**To Reproduce**
Use more than multiple currency, rates are never updated

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by mhcwebdesign** [comment]
More details please! Are you using the ECB currency converter?
