### ISSUE TITLE
error on new install

### ISSUE THREAD

**Issue by Samdz19** [opencart/opencart#13635]
**OpenCart 4.0.2.4**

With new install of the last update (31/01/2024), after complete the instalI I can't access to admin, I got this error:

> syntax error, unexpected variable "$address_id", expecting ")": in C:\wamp64\www\oc4024h\admin\model\customer\customer.php on line 84

**Comment by stalker780** [comment]
@Samdz19 
There are numerous bugs now in editing customers, products, articles, etc.
Daniel is working on admin code refactoring. Work still in progress.

**Comment by danielkerr** [comment]
yes and ging through them all

**Comment by Samdz19** [comment]
good,
