### ISSUE TITLE
[3.0.x.x and Master] The administrator can disable himself

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#13647]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
master

**Comment by condor2** [comment]
For my repo I used this solution

https://github.com/condor2/Opencart_23xx/commit/105b7c6792fe3468242153b880be9fac2660d704

**Comment by mhcwebdesign** [comment]
I am not quite sure what you are on here. The password DB field is of type **varchar(40) 	utf8mb3_general_ci**  hence shouldn't it be verified like this:

```
			if ((utf8_strlen(html_entity_decode($this->request->post['password'], ENT_QUOTES, 'UTF-8')) < 4) || (utf8_strlen(html_entity_decode($this->request->post['password'], ENT_QUOTES, 'UTF-8')) > 40)) {
				$this->error['password'] = $this->language->get('error_password');
			}

```
?

**Comment by mhcwebdesign** [comment]
@condor2 : There are no lines 509-514 in admin/controller/user/user.php.

Can you please create a pull request?

**Comment by condor2** [comment]
@mhcwebdesign  lol

On my second comment you see **my repo**....where I have added a solution (my solution.)

The code is on lines 509-514....
Also I have posted only the code for reference because maybe you will have another solution.....

**Comment by mhcwebdesign** [comment]
OK, now fixed, see https://github.com/opencart/opencart/pull/13750
