### ISSUE TITLE
[master & 3.x] SEO-URLs logic unclear if more languages and stores!

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#13651]
Master & all versions of 3.x

Since 3.x OpenCart is asking for SEO URLs for each language (and store).
Well, clear - but not fine.

Why is this logic not easy (to understand)?

Case: you have 2 (or more) languages, and 2 (or more) store(s).

Product = OpenCart
Languages = en, de fr
Stores = 2

Means, you have to define for each language AND store a keyword (= SEO URL).

Result would be:

url 1-3 store 1: 
EN: OpenCart
DE: OpenCart
FR: OpenCart

url 4-6 store 2: 
EN: OpenCart
DE: OpenCart
FR: OpenCart

So, what if the name of the product, category, text and/or manufacturer **IS NOT TRANSLATEABLE**?
As we have it here with OpenCart, because I think **the term/name OpenCart will be always the same in each store and language**!

But now, each SEO-URL has to be different - which is not applicable with every and each term.

Solution: maybe combine the table seo_url with store (id) and language (id).
In such a case, the keyword can be the same for each store and language.
And (as side effect) the keyword has to be defined only once - because OpenCart will always be OpenCart .. in every language and store ..

**Comment by danielkerr** [comment]
as long as the same keyword is used to point to the same key value it works.

think of it from how the urls are going to be

/en-gb/cameras/canon-d5/info

/de-de/cameras/canon-d5/info
wont be found unless the german language var is there.
 its a better way for google indexing. all pages will be unique and have their own path

**Comment by danielkerr** [comment]
also this seems more like a coomplaint than a bug or any issue. it leaves the system open for u to arrange the seo keywords
