### ISSUE TITLE
 Cannot access offset of type string on string File: ../admin/model/catalog/product.php Line: 1532

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#13688]
https://github.com/opencart/opencart/blob/f56c0d8abe9800a97491a41a529e30b29928e9d6/upload/admin/model/catalog/product.php#L1532

**Comment by cgcmart** [comment]
`more refactoring` comments caused a lot of php errors, admin does not work!

**Comment by danielkerr** [comment]
fixed yeasterday
