### ISSUE TITLE
[3.0.x.x] Error Connecting Paypal

### ISSUE THREAD

**Issue by WebSpectrum** [opencart/opencart#13707]
**What version of OpenCart are you reporting this for?**
3.0.x.x
**Describe the bug**
Unable to connect PayPal error ' Authentication failed due to invalid authentication credentials or a missing Authorization header.' 
Error in console ' paypal Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://bm.paypal.com/spd3TxHV/xhr/api/v2/collector. (Reason: CORS request did not succeed). Status code: (null). '

**To Reproduce**
1. Go to PayPal Extension -> Connect
2. Login To PayPal
3. Complete login process
4. Click 'Return to Opencart...' Button

**Expected behavior**
PayPal sbhould be connected

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Live server
 - CloudLinux v8.9.0
 - PHP 8.2
 - Browser(s) tested with Chrome, Edge and FF

**Additional context**

**Comment by mhcwebdesign** [comment]
I just tested it on our mhccorp.com/demo (using the latest 3.0.x.x aka 3.0.4.0), with our paypal.com account, and it works fine. Unable to reproduce your error. Please contact your webhost for further assistance. Or contact the author at https://dreamvention.com/

**Comment by WebSpectrum** [comment]
I have tried on 3 different hosts now, in each case the same error.
  

  

  

  
  
  
  
  
>
