### ISSUE TITLE
Unable to select a dropdown option in admin (Safari Only)

### ISSUE THREAD

**Issue by ppranav164** [opencart/opencart#13705]
**What version of OpenCart are you reporting this for?**
Version: 4.0.2.3

**Describe the bug**
Unable to select a dropdown option in admin using the safari browser, works well in chrome, firefox etc.

**To Reproduce**
1. Go to 'Admin > Catalog > Products and select any product'
2. Click on 'Links (Tab)'
3. Scroll down to 'Categories'
4. Select any option from the dropdown suggestions.

**Expected behavior**
Should be able to see the selected option in the list

**Comment by danielkerr** [comment]
already6 reported
