### ISSUE TITLE
admin can't add product, work not saved and lost

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#13711]
**What version of OpenCart are you reporting this for?**
4.0.2.4
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
as title described.
![opencart-error](https://github.com/opencart/opencart/assets/14033183/64542100-8c87-4ac7-9025-80f41aed3f78)

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
it works now
