### ISSUE TITLE
[Master branch] Don't use proxy when already inside model

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#13735]
I recently noticed that there were plenty of recent modification in the master branch for the various model classes which appear to be unnecessary, such as:

admin/model/catalog/category.php:

now:
```
    public function addCategory(array $data): int {
        ....
        $this->model_catalog_category->addDescription($category_id, $language_id, $category_description);
        ....
    }

```
was:
```
    public function addCategory(array $data): int {
        ....
        $this->addDescription($category_id, $language_id, $category_description);
        ....
    }

```

Can we please rethink this approach? I think all these changes were merely done because some may have event triggers.

Instead of events, an easier approach for modifying a method in a model class would be to simply extend the model class, using overridden methods.

The only complication arises when multiple 3rd party extensions try to extend the same model class, in which case it should be a chain of dynamically extended classes.

OpenCart already has (finally) a factory class. This one should be improved to support above described scenario, see e.g. https://stackoverflow.com/questions/1539530/is-it-possible-to-extend-a-class-dynamically on how this could be done in principle.

**Comment by danielkerr** [comment]
events are well known. extending the class has disadvantages also.
