### ISSUE TITLE
[3.0.x.x] Two different currency database queries writing to the same cache

### ISSUE THREAD

**Issue by ADDCreative** [opencart/opencart#13745]
https://github.com/opencart/opencart/blob/c6748cf1e4ebe9218e73826ee044aa5fed450ebd/upload/admin/model/localisation/currency.php#L85-L101

https://github.com/opencart/opencart/blob/c6748cf1e4ebe9218e73826ee044aa5fed450ebd/upload/catalog/model/localisation/currency.php#L15-L31

Caused by this commit.
https://github.com/opencart/opencart/commit/38946dfe8af8347f9318f2788e61c5ec1cdd518c

**Comment by mhcwebdesign** [comment]
Maybe don't use currency cache in admin backend? Probably won't make much of a difference in performance.

**Comment by ADDCreative** [comment]
It's only used in settings, the order editor and the currency updater, so the difference in performance would be negligible.

The other option is to split the cache as done for languages.
https://github.com/opencart/opencart/blob/f2626af6bcc63dfb1e1954fc1964d55e96d72536/upload/admin/model/localisation/language.php#L6-L7

**Comment by mhcwebdesign** [comment]
I think the only relevant change needed for this is in **admin/model/localisation/currency.php**:

```
	public function getCurrencies($data = array()) {
		if ($data) {
			.....
		} else {
			$currency_data = $this->cache->get('currency');

			if (!$currency_data) {
				$currency_data = array();

				$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "currency ORDER BY title ASC");

				foreach ($query->rows as $result) {
					$currency_data[$result['code']] = array(
						'currency_id'   => $result['currency_id'],
						'title'         => $result['title'],
						'code'          => $result['code'],
						'symbol_left'   => $result['symbol_left'],
						'symbol_right'  => $result['symbol_right'],
						'decimal_place' => $result['decimal_place'],
						'value'         => $result['value'],
						'status'        => $result['status'],
						'date_modified' => $result['date_modified']
					);
				}

				$this->cache->set('currency', $currency_data);
			}

			return $currency_data;
		}
	}

```
which could be replaced with this:

```
	public function getCurrencies($data = array()) {
		if ($data) {
			.....
		} else {
			$currency_data = array();

			$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "currency ORDER BY title ASC");

			foreach ($query->rows as $result) {
				$currency_data[$result['code']] = array(
					'currency_id'   => $result['currency_id'],
					'title'         => $result['title'],
					'code'          => $result['code'],
					'symbol_left'   => $result['symbol_left'],
					'symbol_right'  => $result['symbol_right'],
					'decimal_place' => $result['decimal_place'],
					'value'         => $result['value'],
					'status'        => $result['status'],
					'date_modified' => $result['date_modified']
				);
			}

			return $currency_data;
		}
	}

```
Nowhere else does the admin backend call `$this->cache->get('currency')` ! But the admin backend still has to call `$this->cache->delete('currency')` in places where the currencies are edited or refreshed.

**Comment by ADDCreative** [comment]
I think that is the simplest fix.

**Comment by mhcwebdesign** [comment]
OK, now fixed, see https://github.com/opencart/opencart/pull/13751
