### ISSUE TITLE
[3.0.x.x] PayPal Extenion Missing File: message_configurator.twig

### ISSUE THREAD

**Issue by WebSpectrum** [opencart/opencart#13746]
**What version of OpenCart are you reporting this for?**
3.0.x.x
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
PayPal Extension -> Pay Later Sections
**To Reproduce**
Enable PayPal extensions -> go to pay later sections

**Expected behavior**
Configure pay later error:  PHP Fatal error:  Uncaught Exception: Error: Could not load template /admin/view/template/extension/payment/paypal/message_configurator.twig

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by mhcwebdesign** [comment]
Just added a fix here: https://github.com/opencart/opencart/pull/13747
Try it again.
