### ISSUE TITLE
OC 4.0.2.3 customer view order history error

### ISSUE THREAD

**Issue by Belleson** [opencart/opencart#13749]
**What version of OpenCart are you reporting this for?**
OC 4.0.2.3

**Describe the bug**
In catalog/model/account/order.php lines 81 and 97

‘payment_method’ => $order_query->row['payment_method'] ? json_decode($order_query->row['payment_method'], true) : '',
 
where json_decode returns null for non-JSON strings.

PHP Warning:  Trying to access array offset on value of type null in public_html/oc/catalog/controller/account/order.php

What section does it affect?
Customer view order history from Account page
The error also exists for shipping_method

**To Reproduce**
1. Create an order with payment method that uses JSON, e.g. Square
2. After order is complete, go to My Account->Order History
3. Click View button
4. See Internal Server Error! There has been a problem loading the page you are looking for. 

The same order shows successfully in Admin console with empty payment method field, no server error page

**Expected behavior**
View payment history

**Screenshots / Screen recordings**

**Server environment (please complete the following information):**
 - Linux
 - PHP version 8.1
cPanel Version | 116.0 (build 11)
Apache Version | 2.4.58
MySQL Version | 8.0.36
Architecture | x86_64
Operating System | linux
Shared IP Address | 45.79.178.199
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.26.3
Kernel Version | 4.18.0-477.21.1.lve.1.el8.x86_64

**Additional context**
I have no PHP experience, otherwise would post a PR

**Comment by danielkerr** [comment]
this pull request dopes not fix anything

**Comment by danielkerr** [comment]
orders should have payments methods so not sure what u did. maybe did not upgrade that would have changed all payment methods and shipping methods into json

**Comment by Belleson** [comment]
Will it do anything to run 4.0.2.3 upgrader on site that is already 4.0.2.3?

**Comment by Belleson** [comment]
And does upgrader affect installed modules?

**Comment by Belleson** [comment]
Problem is fixed and you are correct Daniel, about payment_method not upgraded. Data were [migrated from 2.2.0.0 manually with a script](https://github.com/Belleson/opencart) because of two-version upgrade to 4.0.2.3. Thus payment_method was not converted to JSON because I was not aware of the change. Fortunately we only had three distinct payment methods, Paypal, Square and Check, so I wrote the following SQL updates using payment_method data from orders placed in 4.x. I think there may be more JSON converted fields and I will find and update.

-- {"code":"paypal_payment_gateway.paypal_payment_gateway","name":"PayPal"}
update belleson_oc.`order` set payment_method = '{"code":"paypal_payment_gateway.paypal_payment_gateway","name":"PayPal"}'
where payment_method = 'PayPal Express Checkout';

-- {"code":"cheque.cheque","name":"Cheque \/ Money Order"}
update belleson_oc.`order` set payment_method = '{"code":"cheque.cheque","name":"Cheque \/ Money Order"}'
where payment_method = 'Cheque / Money Order';

-- {"code":"squareup.squareup","name":"Square"}
update belleson_oc.`order` set payment_method = '{"code":"squareup.squareup","name":"Square"}'
where payment_method = 'Credit / Debit Card';

-- Find stray entries not converted to JSON
select count(1) from belleson_oc.`order` o
where payment_method not like '{%';
