### ISSUE TITLE
PHPDoc [4.0.2.3]

### ISSUE THREAD

**Issue by aletoropov** [opencart/opencart#13752]
**What version of OpenCart are you reporting this for?**
4.0.2.3

**Not a bug**
Maybe we should add PHPDoc for system/library  classes?

**Server / Test environment (please complete the following information):**
 - Local development
 - PHP version 8.3

**Comment by AJenbo** [comment]
You should probably clarify a bit, at least if I look at a random file in that folder there is lots of PHPDoc in it:
https://github.com/opencart/opencart/blob/master/upload/system/library/cache.php

Are you asking to generate HTML docs from it or something?

**Comment by aletoropov** [comment]
> Are you asking to generate HTML docs from it or something?
Generate HTML documentation for developer

**Comment by mhcwebdesign** [comment]
@AJenbo : He's probably talking about this one: https://github.com/opencart/opencart/wiki

**Comment by danielkerr** [comment]
i need to setup a documention api script that can gnerate html docs from the phpdoc blocks

**Comment by danielkerr** [comment]
I add apigen but looking at other phpdoc generators
