### ISSUE TITLE
Missing oc_modification table

### ISSUE THREAD

**Issue by Shinrai** [opencart/opencart#13772]
**What version of OpenCart are you reporting this for?**
4.1

**Describe the bug**
Going to index.php?route=marketplace/modification in the admin shows the table does not exist.

**To Reproduce**
1. Go to index.php?route=marketplace/modification
2. See error

**Expected behavior**
Admin Modification page to load and have database tables available

**Comment by danielkerr** [comment]
RUN THROUGH THE UPGRADE

**Comment by Shinrai** [comment]
This is a brand new install of 4.1, due to the upgrade path the upgrade page does not work as it detects 4.0.2.3 as the latest version. The only place oc_modification is present in the code is the db_schema helper file. It's not present in the install.sql.

**Comment by danielkerr** [comment]
4.1 version is in development.
