### ISSUE TITLE
Can't unlock account

### ISSUE THREAD

**Issue by uudruid74** [opencart/opencart#13783]
A user mistyped their password and had their account locked.  The button to unlock it just gives an error message

**Comment by danielkerr** [comment]
on opencart.com? or on ur opencart  installation?

**Comment by uudruid74** [comment]
Local install 

On March 15, 2024 5:33:57 AM CDT, Daniel Kerr ***@***.***> wrote:
>on opencart.com? or on ur opencart  installation?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/opencart/opencart/issues/13783#issuecomment-1999373589
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
---
Thank You,
Evan Langlois
Eddon Systems Consulting

**Comment by pemaier** [comment]
@Daniel - Tested on master of today.
[unlock-customer.webm](https://github.com/opencart/opencart/assets/10166095/d5135b22-6670-4c61-aa6f-e9758f4d0616)
