### ISSUE TITLE
after upgrading from OC 3.0.3.9 to 4.0.2.3, admin panel is largely broken

### ISSUE THREAD

**Issue by 0spinboson** [opencart/opencart#13785]
**What version of OpenCart are you reporting this for?**
4.0.2.3
**Describe the bug**
affects the admin panel, after I upgrade from 3.most-recent to OC4, all of the dashboard reports are missing, and cannot be enabled in the extension overview because the extension dropdown menu is mostly empty (only containing 4 payment methods), OC3 extensions are left in an unclear state (loaded? working? broken? disabled by the updater?)
Also, the status reports are all missing/inaccessible from the main menu and that dropdown menu is also empty.

**To Reproduce**
upgrade existing store from OC3 to OC4
1. Go to 'extensions -> extensions
2. Click on dropdown menu
no 'dashboard' visible
same with all sales reports

**Expected behavior**
I expect the upgrade process to work and not break because of UI / app changes, if there are settings or menu changes even simply dropping those parts of the existing OC3 configuration/settings would be vastly preferable to upgrading to then find a broken store.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
deployed on a plesk VPS, most current, using php 8.2.x
 - Operating system
ubuntu 22.04.4 LTS
 - PHP version
8.2.x
 - Apache version
2.2.x or nginx
 - Browser(s) tested with [e.g. chrome, safari - if applicable]
firefox, chrome

**Comment by osworx** [comment]
> .. extension overview because the extension dropdown menu is mostly empty (only containing 4 payment methods), ..

>.. I expect the upgrade process to work ..

To be honest: and we expect that users inform them before they do a update/upgrade.
OC 4 has 4 payment methods only: https://github.com/opencart/opencart/tree/master/upload/extension/opencart/admin/controller/payment

**Comment by 0spinboson** [comment]
> > .. extension overview because the extension dropdown menu is mostly empty (only containing 4 payment methods), ..
> 
> >.. I expect the upgrade process to work ..
> 
> To be honest: and we expect that users inform them before they do a update/upgrade.
> OC 4 has 4 payment methods only: https://github.com/opencart/opencart/tree/master/upload/extension/opencart/admin/controller/payment

Fine, I'll change my report in line with this since the semi broken extension installer post update is of secondary concern to me anyway. My main concern is the nonexistent "dashboard" category.

Anyway, I don't follow what you're trying to say when you say "we expect users to inform them"? Do you mean that I should simply have looked up in the code (given that the oc4 documentation is still basically nonexistent) that the database upgrade process is absent or as yet unfinished?

**Comment by osworx** [comment]
@0spinboson No, but I thought that in the meantime the page at OpenCart was updated: https://www.opencart.com/index.php?route=cms/feature
**Have to apoligize myself, because the infos there are not relevant anmyore for OC 4.x !!**
With OC 4.x only a few extensions (payment-, shippingmethods) are per default on board.
For all further, you have to look at the marketplace: https://www.opencart.com/index.php?route=marketplace/extension

Anyway, seriousely I would never do an update!
Better to install the new version in another folder or subfolder, and migarte then the old database.
Several threads about this - why and how - in the forum: https://forum.opencart.com/

**Comment by 0spinboson** [comment]
yeah migration fails for the same reason -- it seems there are some database entries from OC3 that cause problems for OC4. So there needs to be an import function that can ignore or convert those entries/fields/etc.

**Comment by danielkerr** [comment]
the upgrade does work. i thinkl u have some extensions that need uninstalling and wait until new versions are released for versin 4

**Comment by danielkerr** [comment]
go to user groups and add permissions for all files and etensions

**Comment by 0spinboson** [comment]
so you're saying that if there are 3.x plugins present, the upgrade neither detects nor disables them nor warns that this might cause issues, and that their presence can break the functionality of core features like the dashboard sales etc display? And you consider this acceptable? This may have been normal practice in the mid-2000s, but nowadays?

**Comment by danielkerr** [comment]
also didnt say if he wen through the actually upgrade in install/upgrade
