### ISSUE TITLE
[master] Frontend - Cart is loosing entries

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#13787]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Cart - Loosing entries after logged in to an other store.

**To Reproduce**
1. Go to 'Store 0/default'
2. Add products to cart and log out.
3. Login to Store 1 
4. View cart - see 0
5. Return to Store 0
6. Cart is empthy

**Expected behavior**

a) At the Front-end in the cart I like to see in the cart the products of the store I logged in in that moment. 
and after the order in the order administration in the order I see the ordered products.
b) BUT when it is required to edit the order as admin it is required to add also products of other stores to the order (a new setting is required for product in own store/not own store ... or something else)

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

[Screencast 2024-03-17 12:09:50.webm](https://github.com/opencart/opencart/assets/10166095/a0dcd71d-01d8-4e3c-9252-39e811b1301c)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system cloudlinux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.8.0esr

**Additional context**

In the video is also an additional error visible that the login by action button in the 2nd store is not working.

**Comment by pemaier** [comment]
To switch with the same user between the cards witch have products is working well. 
But in the moment 1 of the cards is going through checkout the 2nd card is loosing entries and is empty at the next login.

**Comment by danielkerr** [comment]
just tested and its working fine.

**Comment by pemaier** [comment]
Confirm it's working now.
