### ISSUE TITLE
Affiliate Emails Sent to Everyone

### ISSUE THREAD

**Issue by uudruid74** [opencart/opencart#13782]
Opencart 4 is sending out affiliate marketing emails to every customer.  It says their order earned them 100% commission.  The checkbox for affiliates is off, every affiliate event is disabled, I have no affiliates, but it sends them out anyway.  I had to go into the language files and make it look like the amounts being reported are what they spent instead of what they earned

**Comment by danielkerr** [comment]
no diea which version! master or last release
