### ISSUE TITLE
HEAD content rendered in BODY area

### ISSUE THREAD

**Issue by itdes** [opencart/opencart#1378]
Hello,
I'm using the latest version of OpenCart v1.5.6.4, I'm creating a new theme by copying the default theme and changing the header links to the new theme's folder instead of default's theme. Without any other changes to the new theme, I'm not getting proper rendering of all the pages, except for the home page. Strangely, this problem isn't visible in Firefox, but it is there in IE and Google Chrome. The content that should be placed in the HEAD area of the document, is places in the BODY area.. This happens after I change the theme, even though it is EXACT copy of the default theme, the problem isn't observed with the default theme. So I'm wondering if this problem is because of some issues in the controllers? How could I change it without changing the core files?
I haven't tested in previous versions of OpenCart.
Thank you.

**Comment by alonshoshani** [comment]
hi , i have the same problem with my opencat 2 can you pease explain how to fix it?

**Comment by reppair** [comment]
as explained above, but I am struggling with finding properly encoded translation files .. I am about to translate them my self ... (oc v1.5)
