### ISSUE TITLE
[master] Admin - New Customer add address - Customer does not exist

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#13786]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Administration - Customer
When adding a new customer and adding a address to this customer the message Customer doesn't exist appears. 

**To Reproduce**
1. Go to 'Administration - Customers - Customers - Add new'
2. Click on 'Button Add new'
3. Enter new customer details and click  'Save'
4. Then goto Tab Addresses and click 'Add Address'
5. Enter the addess data and click 'Save'
6. See error

**Expected behavior**
At this point the address should get saved.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

![new-user-address](https://github.com/opencart/opencart/assets/10166095/4ac53354-f8bb-4ac9-9c77-bf62923450c4)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Server
 - Operating system Cloudlinux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.8.0esr

**Additional context**
When leaving the customer after saveing then enter the customer again and the enter the address then saveing is working.

**Comment by danielkerr** [comment]
ur right its terrible. something i need to fix before next release

**Comment by pemaier** [comment]
Thank you. Add customer address is working but delete customer address is not working now.
