### ISSUE TITLE
Lost Session "[order_id]" before redirect to "checkout/success"

### ISSUE THREAD

**Issue by ppalashturov** [opencart/opencart#13792]
**OpenCart 4.1.0.0**

**Lost Session "[order_id]"**

Hi again,

I'm posting some more details about my issue:
I am currently working on a new extension for a payment platform. I am at the payment stage, where I have a controller:
"\extension\oc_epay\catalog\controller\payment\epay.php".

In this controller, I have the following methods:
index(): This method contains data for sending to an external payment provider and a form that leads to it. One of the variables sent to the external provider is the "success" method and the link:
"https://domain.test/index.php?route=extension/oc_epay/payment/epay.success&language=en-gb"

However, after accessing this address and method, I lose the entire session and I don't have "$this->session->data['order_id']" which I need to complete the order and change the status with "addHistory". 

After that, I redirect to:
"https://domain.test/index.php?route=checkout/success&language=en-gb"
@danielkerr 
Any ideas on what happened?
Best Regards!

**Comment by danijelGombac** [comment]
Check if you have an option to add a variable to the url, which is returned back when redirection. If option exist, add order_id to the url or some token which is related to order_id in some table.

**Comment by ppalashturov** [comment]
Hi,

I have currently implemented it exactly as you said. With the "order_id" GET parameter - here is an example:

"[https://domain.test/index.php?route=extension/oc_epay/payment/epay.success&order_id={$order_id}&language=en-gb](https://domain.test/index.php?route=extension/oc_epay/payment/epay.success&order_id=%7B$order_id%7D&language=en-gb)"

However, I am not personally comfortable with this solution because someone could potentially manipulate the parameters and change the order status to "completed", for example. I have security concerns.

Thanks @danijelGombac!
Best Regards!

**Comment by danijelGombac** [comment]
Create new table and use both unique token and order_id. When customer return get from the table order_id using a token and then compare the returned order_id in the url with the order_id from the table.

**Comment by ppalashturov** [comment]
Hello,
I'm ok with the idea, but most modules for 3.0 work like this with a session "order_id" to complete and change the status to complete. That's why I want to keep it that way if possible or if I'm wrong somewhere to find out what's new in version 4.1.
thanks

**Comment by danijelGombac** [comment]
The problem is with session "samesite". When you leave the site the session is gone. Try change https://github.com/opencart/opencart/blob/a01aec839839dc1101d791a5efbc0385303ace7c/upload/system/config/default.php#L49C13-L49C21 the value of samesite.

**Comment by ppalashturov** [comment]
Hello,
Thanks, I will test it these days and write!
Greetings

**Comment by danielkerr** [comment]
what about passing the order id to via the get request.

**Comment by ppalashturov** [comment]
> The problem is with session "samesite". When you leave the site the session is gone. Try change https://github.com/opencart/opencart/blob/a01aec839839dc1101d791a5efbc0385303ace7c/upload/system/config/default.php#L49C13-L49C21 the value of samesite.

Hello,
By changing the SameSite session from the Administration settings, everything worked correctly. You just have to choose None or Lax.
Thanks a lot for your help.
Best Regards
