### ISSUE TITLE
SEO URLs slow store loading

### ISSUE THREAD

**Issue by lemonadvert** [opencart/opencart#13793]
**OpenCart 4.1.0.0**

**SEO URLs slow store loading**

Hello, 
When I enabled the SEO URLs I found that the store loading speed dropped dramatically... There are 4 sec. delay on each new click.

When I disable the SEO URLs the store loading speed increases dramatically. It's loading almost immediately.
But when I enable the SEO URLs loading speed decreases.

The online store is a multi-store, but currently, it only works with the default store id=0
The categories count is switched OFF.

**Comment by chongshengdz** [comment]
you can remove the "or ... like..." selection from database.
for example, on the below file.
Catalog\Model\Design\SeoUrl.php

**Comment by ppalashturov** [comment]
@chongshengdz not working for me :(

**Comment by chongshengdz** [comment]
> @chongshengdz not working for me :(

how many products do you have in your store?

**Comment by ppalashturov** [comment]
> > @chongshengdz not working for me :(
> 
> how many products do you have in your store?

Hi, 714 products.

**Comment by chongshengdz** [comment]
> > > @chongshengdz not working for me :(
> > 
> > 
> > how many products do you have in your store?
> 
> Hi, 714 products.

it is too few, do what i told you in the above message.

**Comment by ppalashturov** [comment]
> > > > @chongshengdz not working for me :(
> > > 
> > > 
> > > how many products do you have in your store?
> > 
> > 
> > Hi, 714 products.
> 
> it is too few, do what i told you in the above message.

Yes I did and I also have a 4 second lag!
Thanks!

**Comment by lemonadvert** [comment]
The products are not much but we have 7 languages so I think that the SEO URLs slowing down the speed load.  When I disable the SEO URLs the page almost immediately.

Here is the link: [https://inbyo.cz/test/cs-cz/catalog](https://inbyo.cz/test/cs-cz/catalog)

Try to enter any product ... it's loading slowly.

**Comment by ppalashturov** [comment]
@danielkerr @chongshengdz 
Hi, problem is here: `$this->url->addRewrite($this);` in `catalog/controller/startup/seo_url.php`. If enable SEO url  I did and I also have a 4 second lag!

**Comment by chongshengdz** [comment]
> Catalog\Model\Design\SeoUrl.php
> remove OR `keyword` LIKE '" . $this->db->escape('%/' . $keyword) from the file

did you do what I told you?
remove OR keyword LIKE '" . $this->db->escape('%/' . $keyword) from Catalog/Model/Design/SeoUrl.php

**Comment by chongshengdz** [comment]
you can check out our website using opencart and have thousands of products, it works fast.
https://www.ectransistors.com/

**Comment by cgcmart** [comment]
> you can check out our website using opencart and have thousands of products, it works fast. https://www.ectransistors.com/

What product feed extension did you use?

**Comment by chongshengdz** [comment]
> > you can check out our website using opencart and have thousands of products, it works fast. https://www.ectransistors.com/
> 
> What product feed extension did you use?

if MySQL slowly searches your data, you can use elasticsearch or sphinx search.
for less than 100k products, MySQL is ok.

**Comment by danielkerr** [comment]
its fine.  i can imagine it might be down to some missing resource like images or js that is causing finite loops. possibly a template missing stuff. either way no one else is reporting it.

**Comment by stalker780** [comment]
> For some insane reason there are over 1.8 MILLION records in `oc_seo_url` table.

Something is wrong with your store. 
I have about 170000 products, about 1000 categories and about 336000 seo_url rows for 2 languages. 
You should rebuild your seo_urls at least for categories. There was a problem saving seo_urls in earlier OC4 versions. It produced lots of duplicates and orphans.
https://github.com/opencart/opencart/pull/14478

Check how many urls you have for categories with 
```SELECT COUNT(seo_url_id) FROM oc_seo_url WHERE `key` = 'path'```

Mine shows about 1986 rows for 969 categories and 2 languages. Looks like I have some orphans in my table. But not critical.
