### ISSUE TITLE
imagecreatefromwebp function not found

### ISSUE THREAD

**Issue by benycode** [opencart/opencart#13794]
Version: 4.1.0.0
Env: used docker-compose from repo

if file .webp was uplaoded reviewing files via "Image manager" i'm getting error:

Call to undefined function Opencart\System\Library\imagecreatefromwebp(): in /var/www/html/system/library/image.php on line 70

**Comment by danielkerr** [comment]
extension=gd

**Comment by danielkerr** [comment]
GD Support => enabled
GD Version => bundled (2.1.0 compatible)
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.4.11
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.5.13
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled

**Comment by benycode** [comment]
nop, i have made a pull request: https://github.com/opencart/opencart/pull/13795

native dockerfile has not extra lib
