### ISSUE TITLE
[3.0.x.x] Ready for a new release 3.0.4.0

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#13803]
Hi Daniel,

I think we are ready for another tagged release 3.0.4.0 of the 3.0.x.x branch.

We have added a number of security patches, and payment extension updates over the past few months.
See also https://forum.opencart.com/viewtopic.php?t=233153

Can you do please another tagged release please?

Thanks

**Comment by danielkerr** [comment]
sure

**Comment by mhcwebdesign** [comment]
> sure

Thanks. Let us know when you are done with this. 

We have already a number of OpenCart users waiting for this upcoming 3.0.4.0 release.

**Comment by mhcwebdesign** [comment]
Hi Daniel, when will you be able to do a tagged 3.0.4.0 release? It has some important security fixes, and some other bugfixes.

**Comment by rasulsh** [comment]
> Hi Daniel, when will you be able to do a tagged 3.0.4.0 release? It has some important security fixes, and some other bugfixes.

What security issues have been addressed in this version? Could you please mention the related commits?
Thank you.

**Comment by NicNiead** [comment]
is it ready?

**Comment by IP-CAM** [comment]
It looks like it::
https://github.com/opencart/opencart/blob/3.0.x.x/upload/index.php

define('VERSION', '3.0.4.0');

![oc_3040](https://github.com/opencart/opencart/assets/12776547/5934912d-a555-4aea-b7c2-dac76098db68)

**Comment by mhcwebdesign** [comment]
@danielkerr : I know you are busy, but when find a moment, can you please do a tagged release for the 3.0.4.0 ?
Thanks.

**Comment by NicNiead** [comment]
https://github.com/opencart/opencart/tree/3.0.x.x  @mhcwebdesign Hi Bro, is the version downloaded from this address now 3.0.4.0?

**Comment by mhcwebdesign** [comment]
> https://github.com/opencart/opencart/tree/3.0.x.x @mhcwebdesign Hi Bro, is the version downloaded from this address now 3.0.4.0?

Yes

**Comment by NicNiead** [comment]
@mhcwebdesign I'm about to upgrade it from 3.0.3.9, no changes to the database? Just need to overwrite the program. Will it be upgraded to 3.0.4.0?

**Comment by mhcwebdesign** [comment]
> @mhcwebdesign I'm about to upgrade it from 3.0.3.9, no changes to the database? Just need to overwrite the program. Will it be upgraded to 3.0.4.0?

No DB changes.

**Comment by NicNiead** [comment]
@mhcwebdesign Thank you

**Comment by NicNiead** [comment]
When I upgraded from 3.0.3.9 to 3.0.4.0, I opened the website backend page admin/index.php?route=marketplace/marketplace&user_token=8BdVImEaB30ZvmaBy0q7EOrQdyjpDRkR. There was an error message, Warning: Undefined array key "install" in /www/admin/controller /extension/module/ocm.php on line 26.    @mhcwebdesign

**Comment by mhcwebdesign** [comment]
@danielkerr : Will be able to do a tagged release please soon for 3.0.4.0 from the https://github.com/opencart/opencart/tree/3.0.x.x ? Also, I think the https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance (which was released as 3.0.3.9 as while ago, shouldn't be there anymore as a 3.0.x.x_Maintenance, we'd expect any fixes for it to already be in 3.0.4.0.

**Comment by danielkerr** [comment]
ok deleted

**Comment by TheCartpenter** [comment]
OC v3.2.0.0 has been mostly maintained since the beginning. Will there be a release of that version soon, as well?

**Comment by JohnnyVega** [comment]
Hi, guys

It would be logical to call the new version "3.1.0.0" instead of "3.0.4.0." Because PHP 8 support is a big change.

The name "3.0.4.0" is very similar to previous versions where there was no PHP 8 support. If this version name is left, there will be a lot of errors and confusion in the future, especially among buyers. But if you call the version "3.1.0.0" - it will be well visually distinguishable from previous versions and will be well remembered.

As a result, it turns out:

- 3.0. x. x - PHP 7 support,
- 3.1. x. x - PHP 8 support

It looks good, it reads well, it is clear, it is well remembered and buyers will not be confused.


I understand that perhaps not all the conditions are met in order to name version 3.1. But sometimes you need to move away from strict formalism in favor of common sense and better clarity. Because in the end it will be better for everyone.

With respect and hope for common sense.

**Comment by TheCartpenter** [comment]
3.1.0.0 already exists in the OC downloads.

**Comment by mhcwebdesign** [comment]
@JohnnyVega : This was discussed on the OpenCart forum, and the majority decided to go for a 3.0.4.0, see https://forum.opencart.com/viewtopic.php?t=233153#p867162

**Comment by JohnnyVega** [comment]
> 3.1.0.0 already exists in the OC downloads.

You are wrong. In any case, there is no version 3.1 or 3.1.x.x on opencart.com.

**Comment by TheCartpenter** [comment]
Looks like the beta has been removed from the downloads list.

**Comment by JohnnyVega** [comment]
> @JohnnyVega : This was discussed on the OpenCart forum, and the majority decided to go for a 3.0.4.0, see https://forum.opencart.com/viewtopic.php?t=233153#p867162

Thanks for the link. I have read this topic and I am not saying that your arguments are not correct. I just offer a slightly different take on it. As one movie hero said: "Code is more like guidelines than actual rules.." )

As I said earlier, the third and fourth digits in the version are poorly remembered. But the first two digits in the version are remembered perfectly. Let's try to use it.

For example, instead of the memorable 2.4 notation, we use 2.3.0.2. Someone can, using memory and despite the documentation, quickly remember how 2.3.0.0 and 2.3.0.2 differ from each other? )) We, as a thrifty old mistress, save numbers. )

The first branch of opencart in numbering reached 1.6.x. The second version in the numbering reached 2.3.x. The third version in the numbering reached 3.0.x.

We can more often than now use two digits in the version instead of four digits - numbers are enough, there is no shortage of numbers.

**Comment by TheCartpenter** [comment]
> > @JohnnyVega : This was discussed on the OpenCart forum, and the majority decided to go for a 3.0.4.0, see https://forum.opencart.com/viewtopic.php?t=233153#p867162
> 
> Thanks for the link. I have read this topic and I am not saying that your arguments are not correct. I just offer a slightly different take on it. As one movie hero said: "Code is more like guidelines than actual rules.." )
> 
> As I said earlier, the third and fourth digits in the version are poorly remembered. But the first two digits in the version are remembered perfectly. Let's try to use it.
> 
> For example, instead of the memorable 2.4 notation, we use 2.3.0.2. Someone can, using memory and despite the documentation, quickly remember how 2.3.0.0 and 2.3.0.2 differ from each other? )) We, as a thrifty old mistress, save numbers. )
> 
> The first branch of opencart in numbering reached 1.6.x. The second version in the numbering reached 2.3.x. The third version in the numbering reached 3.0.x.
> 
> We can more often than now use two digits in the version instead of four digits - numbers are enough, there is no shortage of numbers.

Except that memorization isn't needed, in this case. Users simply needs to copy and paste the version number from their admin footer or from the index.php file.

**Comment by danielkerr** [comment]
0k fine will do today

**Comment by danielkerr** [comment]
actuaally who wants the job of preapring new releases for the old version
?

**Comment by TheCartpenter** [comment]
> actually who wants the job of preparing new releases for the old version ?

I do.

**Comment by NicNiead** [comment]
I have been using it for a while. I feel that version 3.0.3.8 is the most stable. For online sales systems, the most important thing is stability and plug-in compatibility. Nothing else matters.

**Comment by mhcwebdesign** [comment]
> actually who wants the job of preparing new releases for the old version ?

I am happy to continue the 3.0.x.x maintenance and releases if that helps.

**Comment by mhcwebdesign** [comment]
> I have been using it for a while. I feel that version 3.0.3.8 is the most stable. For online sales systems, the most important thing is stability and plug-in compatibility. Nothing else matters.

This was precisely the reason why we continued the 3.0.x.x line: 3.0.3.9 and 3.0.4.0 are based on 3.0.3.8, with just some more bugfixes and security patches, and added support for PHP 8.x.

**Comment by JohnnyVega** [comment]
> actually who wants the job of preparing new releases for the old version ?

I do.

**Comment by osworx** [comment]
I would recommend @mhcwebdesign - he has done a lot for that in the past, knows the code very well and is also well known in the OC community.

**Comment by JohnnyVega** [comment]
Time passes.
Days turn into weeks, weeks into months, months into years.
But there are no changes here...

_Japanese haiku_

**Comment by Wacky-Mole** [comment]
Please, we need a new version, 3.0.3.9 is not a happy camper with PHP 8.2. Lots of little bug fixes

**Comment by mhcwebdesign** [comment]
OpenCart 3.0.4.0 has now been tagged and released by Daniel.

A big thanks to all the contributors here who helped us with all the needed bugfixes and security patches.

**Comment by NicNiead** [comment]
"Thank you mhcwebdesign and Daniel, now just waiting for all extensions that support version 3.x to update to support 3.0.4.0. This may take some time."
