### ISSUE TITLE
[master] Customer Account  FE - Stored Payment Method /  Undefined property

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#13807]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Frontend Customer Account - Stored Payment Method

**To Reproduce**
1. Go to 'Customer Account'
2. Click on 'click on - Stored Payment Methode'

Notice: Undefined property: Proxy::getStored in /home/localhost/public_html/opencart/opencart-master.demo/catalog/controller/account/payment_method.php on line 98: in /home/localhost/public_html/opencart/opencart-master.demo/system/engine/proxy.php on line 91

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? localhost
 - Operating system Linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.8.0esr

**Comment by danielkerr** [comment]
already reported
