### ISSUE TITLE
Image Upload Dialog is not Showing

### ISSUE THREAD

**Issue by Gadalla** [opencart/opencart#13809]
**What version of OpenCart are you reporting this for?**
3.0.3.9

**Describe the bug**
On the product create/edit page, when clicking the blue OpenCart logo image in the 'Image' tab, the little tooltip that has the edit image button, and delete image button, is not showing. Only empty white tooltip. This is happening on a fresh OpenCart 3.0.3.9 installation. I cleared the cache, tried from the Chrome Incognito window, I tried different browsers; and the problem is still showing.

**To Reproduce**
1. Go to 'Catalog' from the left menu, then click on 'Products'.
2. Click on 'Add New' button in the top right.
3. Go to 'Image' tab.
4. Click the add/edit image OpenCart logo image

**Expected behavior**
The little tooltip that has the edit image button, and delete image button, is to show.

**Screenshots / Screen recordings**
https://www.loom.com/share/e9f36f36f91a4105872f7b3025151e73?sid=d94a6836-6416-4a32-a27a-aa6bf47a21d3

**Server / Test environment (please complete the following information):**
 -  Plesk Obsidian 18.0.58 Update #2, Web server
 - AlmaLinux 8.9
 - PHP version 8.0.30
 - Nginx version
 - Browser(s) tested with Chrome, Edge, Firefox.

**Additional context**

**Comment by mhcwebdesign** [comment]
I ma unable to reproduce your error, it works just fine on OC 3.0.3.9. Yours is probably a heavily modified OC 3.0.3.9 site, causing this error. Make sure your admin/view/javascript/common.js isn't corrupted.
