### ISSUE TITLE
is the logic here good?

### ISSUE THREAD

**Issue by benycode** [opencart/opencart#13802]
Version: 4.1.0.0

module: wishlist
action: add

adding a product to the wishlist when i'm not logged:

![image](https://github.com/opencart/opencart/assets/39025147/fb445c8f-d19f-4fbe-bc15-10264417df97)

getting message: 

![image](https://github.com/opencart/opencart/assets/39025147/acaa3373-22c9-4a2b-ba48-81d069603b57)

but product was added to the wishlist anyway, it was stored to session not DB (i checked a code). Is there the message or logic conflict?

the code fragment:

![image](https://github.com/opencart/opencart/assets/39025147/aecf3a7e-4728-4358-a16f-f7ce0a7633a7)

**Comment by carkcib1** [comment]
Logic is good I believe. Try this to test it. While you are not logged in, click "Add to wish list" button to add a product to your wish list, you will get the message "You must login or create account". Then go ahead and login to your account, navigate to your wish list, you will see that the product is added to your wish list. This feature basically saves you time and doesn't require you to click the "Add to wish list" button again after you logged in.

**Comment by carkcib1** [comment]
I was able to remove the product from wish list when not logged in by clearing the cookies with couple clicks, I know it's a hack :D but let's wait if anyone else have opinion about this topic. Personally, I don't see problem.

**Comment by danielkerr** [comment]
iu dont see a problem also. another clown!

**Comment by benycode** [comment]
nice communication and culture, cool :)

**Comment by rsuchovsky** [comment]
Otherwise, regarding the wishlist function in opencart. I have been confronted with marketing agencies more than once. That it is a bad functionality if the visitor cannot add the product to the wishlist if he is not logged in. Which I agree with them. It is a pity that OpenCart does not have this function in the core.

**Comment by benycode** [comment]
of course, the majority part of buyers buy offline as guests, and if I add a product to my wish list, it does not mean that I will go and log in or create an account, although the example I have shown only talks about such a scenario. But here is the point, when ux software is created by programmers and not ux experts, then nothing is wrong:)
