### ISSUE TITLE
In case of module installation error, the file remains in `system/storage/marketplace` and blocks further installation attempts.

### ISSUE THREAD

**Issue by akaunderr** [opencart/opencart#13801]
OpenCart 4.1.0.0

In case of module installation error, the file remains in `system/storage/marketplace` and blocks further installation attempts. 

For example. If will try to install a module file without `install.json` we will get related error message, and after that it will impossible to install the same but fixed file (with `install.json`), because such file was be already downloaded.

I think if there is an installation error the file should be deleted.

**Comment by danielkerr** [comment]
no idea what ur talking about
