### ISSUE TITLE
Nginx slow SEO URLs

### ISSUE THREAD

**Issue by lemonadvert** [opencart/opencart#13815]
**OpenCart 4.1.0.0 - Dev version**

**Describe the bug**

Hello again,
We tried all the options suggested in the previous post (change of model in SEO). We found that the issue is completely different. 
We are using Nginx. So the Nginx slowed down the loading speed by 3-4 seconds when we enabled the SEO URLs. We have a standard Nginx configuration. Maybe due to some settings, this issue appears. 
After that, we tried to upload the project to Apache2 and we found that the loading speed was much faster, about 600 - 700 ms. 

The project is in 9 languages with many SEO URLs, and that's why we noticed the problem.

Has anyone had a similar problem with Nginx and can provide any idea or solution?

Thanks!

**Comment by danielkerr** [comment]
how many products

**Comment by danielkerr** [comment]
i added index to the db  table

**Comment by lemonadvert** [comment]
> how many products

Now much.. around 1000 with 300 categories, and  9 languages .

**Comment by mhcwebdesign** [comment]
@lemonadvert : Have you managed to trace it down to the exact SQL query which makes it so slow? If so, run it via PHPMyAdmin, try to modify and/or optimize it there, to see what exactly causes the performance issue. Even 700 msec on Apache2 is a bit slow, too.

**Comment by lemonadvert** [comment]
> i added index to the db table

Can you give us an exact MySQL query for the indexes to run on phpmyadmin in our DB and then test if it works?

**Comment by lemonadvert** [comment]
> @lemonadvert : Have you managed to trace it down to the exact SQL query which makes it so slow? If so, run it via PHPMyAdmin, try to modify and/or optimize it there, to see what exactly causes the performance issue. Even 700 msec on Apache2 is a bit slow, too.

No, we don't. You can try to open the product from this link [https://inbyo.cz/cs-cz/catalog/slevy](https://inbyo.cz/cs-cz/catalog/slevy) will see the delay on the Console Network tab.

**Comment by mhcwebdesign** [comment]
Your product page takes about 2172ms to do the initial load for https://inbyo.cz/116-cs/cs-cz/product/slevy 
I can only see 1 language.

**Comment by lemonadvert** [comment]
> Your product page takes about 2172ms to do the initial load for https://inbyo.cz/116-cs/cs-cz/product/slevy I can only see 1 language.

Yes, I know that.
At the moment we disabled the other languages. They will be on separate domains. But the issue is the same with one or 9 languages.

**Comment by mhcwebdesign** [comment]
You could just temporarily add some logging code with time measurements to the system/library/db/mysqli.php, in its query function, to see what exact DB query is so slow. See e.g. https://stackoverflow.com/questions/6245971/accurate-way-to-measure-execution-times-of-php-scripts on how to do that.

**Comment by danielkerr** [comment]
seems quick enough to me

**Comment by lemonadvert** [comment]
We added the logging code.  You can check now: https://inbyo.cz/116-cs/cs-cz/product/slevy

@mhcwebdesign, @danielkerr, @ppalashturov

**Comment by lemonadvert** [comment]
> The SQL query times seem to be OK, no outstanding bottlenecks in there, judging by your logs. Is it on NGinx or Apache2?

It's Nginx only.... with standard configurations...

**Comment by rsuchovsky** [comment]
Amost 1000 sql queries for product detail page?

**Comment by mhcwebdesign** [comment]
Try it on an Apache2 server, just to see whether it makes a difference.

**Comment by lemonadvert** [comment]
> Try it on an Apache2 server, just to see whether it makes a difference.

We tried already, as I described in the first post:

We tried to upload the project to Apache2 and we found that the loading speed was much faster, about 600 - 700 ms.
