### ISSUE TITLE
[4.1.0.0] Customer Custom Fields do not populate

### ISSUE THREAD

**Issue by Dave3009** [opencart/opencart#13818]
In the latest opencart-master the customer custom fields do not populate on admin/view/template/customer_form.twig

Root cause:
In admin/controller/customer/customer.php line: 601
`
$data['account_custom_field'] = $customer_info['custom_field'];
`
Solution:
Change line 601 to
`
$data['account_custom_field'] = json_decode($customer_info['custom_field'],true);
`

This was working in 4.0.2.3 which is listed as the most recent release, downloading the latest master shows version 4.1.0.0, not sure if I'm doing something wrong here!

**Comment by pemaier** [comment]
Activated custom fields:
![image](https://github.com/opencart/opencart/assets/10166095/440c4c28-2e62-4d7c-b227-2c9582ba81dc)

Display at customer frontend: (OK)
![image](https://github.com/opencart/opencart/assets/10166095/a521264d-daa5-4604-b941-0d759ef7267f)

Display at customer frontend address book entries: (not present)
![image](https://github.com/opencart/opencart/assets/10166095/ba372d93-30c0-48aa-a2aa-3b7891a98cdf)

Display at customer frontend address entry: (OK)
![image](https://github.com/opencart/opencart/assets/10166095/c2201a71-48c8-476b-bf9d-6f3fe24b9caa)

Display at backend customer edit: (OK)
![image](https://github.com/opencart/opencart/assets/10166095/d1ff1112-fdfa-4da2-bf8c-8cbb874a5500)

Display at backend address list: (not present)
![image](https://github.com/opencart/opencart/assets/10166095/124646e0-6c7d-4a1b-a9b3-cbbabd239ec0)

Display at backend address edit: (Date is correct displayed but the deactivated custom fields are not filtered)
![image](https://github.com/opencart/opencart/assets/10166095/db3f84ce-3e66-4958-8142-816153243ace)

**Comment by danielkerr** [comment]
already fixed

return $query->row + ['custom_field' => json_decode($query->row['custom_field'], true)];
