### ISSUE TITLE
Upgrade cannot do it

### ISSUE THREAD

**Issue by hermannmisi** [opencart/opencart#13821]
Hello,

I cannot upgrade to the newest version.

**What version of OpenCart are you reporting this for?**
4.0.2.1

**Describe the bug**
"Version is lower than the current version!" to 4.0.2.3

**To Reproduce**
1. Go to 'System'
2. Click on 'Maintenance'
3. Click on 'Upgrage'
4. Click on 'Upgrade' button
6. See error

**Screenshots / Screen recordings**
![image](https://github.com/opencart/opencart/assets/47886318/6b2d6396-dadf-49e4-85da-dee5f549ebbd)

**Server / Test environment (please complete the following information):**
Cpanel, PHP 8.3

**Comment by danielkerr** [comment]
any error messages? if u rick click the browser and go to inspect element then console.

**Comment by hermannmisi** [comment]
No error message.
Which browser? Sorry I don't understand.
I opened the developer function and I can see these elements after click the upgrade button:

- /nv2yokfirncvehfl/index.php?route=tool/upgrade.download&user_token=2bc67916f3001731ff6a8e600bfafa13&version=4.0.2.3:
Data:
 route=tool/upgrade.download&user_token=2bc67916f3001731ff6a8e600bfafa13&version=4.0.2.3
Answer:
 {"error":"Version is lower than the current version!"}

- data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 12 12' width='12' height='12' fill='none' stroke='%23e3503e'%3e%3ccircle cx='6' cy='6' r='4.5'/%3e%3cpath stroke-linejoin='round' d='M5.8 3.6h.4L6 6.5z'/%3e%3ccircle cx='6' cy='8.2' r='.6' fill='%23e3503e' stroke='none'/%3e%3c/svg%3e:
Response:
 < svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 12 12' width='12' height='12' fill='none' stroke='#e3503e'>< circle cx='6' cy='6' r='4.5'/>< path stroke-linejoin='round' d='M5.8 3.6h.4L6 6.5z'/>< circle cx='6' cy='8.2' r='.6' fill='#e3503e' stroke='none'/>< /svg>

**Comment by ADDCreative** [comment]
Could be https://github.com/opencart/opencart/issues/12280.

**Comment by hermannmisi** [comment]
I can see this in the error.log:
[28-Mar-2024 14:30:18 Europe/Budapest] PHP Fatal error:  Uncaught Error: Failed opening required '/home/listazoe/shop/system/storage/vendor/aws/aws-sdk-php/src/functions.php' (include_path='.:/opt/alt/php83/usr/share/pear:/opt/alt/php83/usr/share/php:/usr/share/pear:/usr/share/php') in /home/listazoe/shop/system/vendor.php:6
Stack trace:
#0 /home/listazoe/shop/system/framework.php(8): require_once()
#1 /home/listazoe/shop/install/index.php(42): require_once('/home/listazoe/...')
#2 {main}
  thrown in /home/listazoe/shop/system/vendor.php on line 6

vendor.php on line 6:
require_once(DIR_STORAGE . 'vendor/aws/aws-sdk-php/src/functions.php');
