### ISSUE TITLE
"Applying patches..." for end fo word

### ISSUE THREAD

**Issue by hermannmisi** [opencart/opencart#13832]
I can see this in the error.log:
[28-Mar-2024 14:30:18 Europe/Budapest] PHP Fatal error: Uncaught Error: Failed opening required '/home/listazoe/shop/system/storage/vendor/aws/aws-sdk-php/src/functions.php' (include_path='.:/opt/alt/php83/usr/share/pear:/opt/alt/php83/usr/share/php:/usr/share/pear:/usr/share/php') in /home/listazoe/shop/system/vendor.php:6
Stack trace:
#0 /home/listazoe/shop/system/framework.php(8): require_once()
https://github.com/opencart/opencart/issues/1 /home/listazoe/shop/install/index.php(42): require_once('/home/listazoe/...')
https://github.com/opencart/opencart/pull/2 {main}
thrown in /home/listazoe/shop/system/vendor.php on line 6

vendor.php on line 6:
require_once(DIR_STORAGE . 'vendor/aws/aws-sdk-php/src/functions.php');

**What version of OpenCart are you reporting this for?**
4.0.2.1

**Describe the bug**
I click on the Upgrade button and I can see "coping files..." and then "applying patches" and no changes 

**To Reproduce**
1. Go to 'System'
2. Click on 'Maintenance'
3. Click on 'Upgrage'
4. See neverending upgrade process

**Screenshots / Screen recordings**
![Uploading image.png…]()

**Server / Test environment (please complete the following information):**
 - Operating system: Linux (Cpanel surface)
 - PHP version: 8.3
 - Browser(s) tested with [e.g. chrome, safari - if applicable]: Chrome

**Comment by hermannmisi** [comment]
![image](https://github.com/opencart/opencart/assets/47886318/0291fc23-4587-4e35-9a2a-8638ed5697e0)

**Comment by danielkerr** [comment]
go tot he console so u can see any errors

**Comment by hermannmisi** [comment]
SyntaxError: Unexpected token '<', "<br />
<b>"... is not valid JSON
parsererror
<br />
<b>Warning</b>:  require_once(/home/.../shop/system/storage/vendor/aws/aws-sdk-php/src/functions.php): Failed to open stream: No such file or directory in <b>/home/.../shop/system/vendor.php</b> on line <b>6</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Failed opening required '/home/.../shop/system/storage/vendor/aws/aws-sdk-php/src/functions.php' (include_path='.:/opt/alt/php83/usr/share/pear:/opt/alt/php83/usr/share/php:/usr/share/pear:/usr/share/php') in /home/.../shop/system/vendor.php:6
Stack trace:
#0 /home/.../shop/system/framework.php(8): require_once()
#1 /home/.../shop/install/index.php(42): require_once('/home/.../...')
#2 {main}
  thrown in <b>/home/.../shop/system/vendor.php</b> on line <b>6</b><br />

**Comment by mhcwebdesign** [comment]
You shouldn't use OC 4.0.2.1, at least go with 4.0.2.3, or later (if testing)! Besides, you are using wrong or corrupted files, because line 6 in **system/vendor.php** contains this:

`$autoloader->register('AWS/CRT/IO', DIR_STORAGE . 'vendor/aws/aws-crt-php/src/AWS/CRT/IO/', true);`

and not this:

`require_once(DIR_STORAGE . 'vendor/aws/aws-sdk-php/src/functions.php');`

**Comment by hermannmisi** [comment]
Ok, but I install it this version because it was the newest.
Now on the console have this message:
SyntaxError: Unexpected token '<', "<br />
<b>"... is not valid JSON
parsererror
<br />
<b>Warning</b>:  require_once(/home/listazoe/shop/system/storage/vendor/guzzlehttp/guzzle/src/functions_include.php): Failed to open stream: No such file or directory in <b>/home/listazoe/shop/system/vendor.php</b> on line <b>10</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Failed opening required '/home/.../shop/system/storage/vendor/guzzlehttp/guzzle/src/functions_include.php' (include_path='.:/opt/alt/php83/usr/share/pear:/opt/alt/php83/usr/share/php:/usr/share/pear:/usr/share/php') in /home/.../shop/system/vendor.php:10
Stack trace:
#0 /home/.../shop/system/framework.php(8): require_once()
#1 /home/.../shop/install/index.php(42): require_once('/home/listazoe/...')
#2 {main}
  thrown in <b>/home/.../shop/system/vendor.php</b> on line <b>10</b><br />


vendor.php line 10:
require_once(DIR_STORAGE . 'vendor/guzzlehttp/guzzle/src/functions_include.php');

How can I install the newest version if I have more wrong lines? At the Backup & Restore menu point can I upload the 4.0.2.1.zip file?

**Comment by hermannmisi** [comment]
I downloaded the 4.0.2.3 and upzipped and then uploaded to the folder and Opened the install "file" and I have this question:
![image](https://github.com/opencart/opencart/assets/47886318/157e41eb-6d8e-4570-9d48-44eeccb8e972)

And I checked the file:
![image](https://github.com/opencart/opencart/assets/47886318/99df0715-5d61-4d0e-94e0-cb8aafaeb3da)

I cannot overwrite it because in the zip file doesn't contain the admin/config.php

**Comment by osworx** [comment]
> I cannot overwrite it because in the zip file doesn't contain the admin/config.php

Such questions should be made in the forum > https://forum.opencart.com/
Next: you will never find any config.php because you have to **rename first both config-dist.php** before you start the installation!

**Comment by danielkerr** [comment]
read the INSTALL.md

**Comment by hermannmisi** [comment]
Yeah, I tried the upgrade.md. Now in cpanel I can see the newest version but on the upgrage surface 4.0.2.1.  Must be remember this in the future. 
And everything is deleted but not problem I can write again the SW details. I have just one.

Thanks!

**Comment by danielkerr** [comment]
i think missing some files when it was uploaded
