### ISSUE TITLE
Store- or country-specific shipping prices in a multi-store setup

### ISSUE THREAD

**Issue by mehov** [opencart/opencart#13840]
Hi everyone

When a store is shipping to multiple countries in Europe, the postage cost is likely to differ, but currently there doesn't seem to be a way to reflect that in Opencart.

**The current approach**

From looking at my own Opencart copy, as well as the latest shipping extension templates code, both [free shipping](https://github.com/opencart/opencart/blob/b9e62a05bb76eff3d378d7b14980ea298e1856eb/upload/extension/opencart/admin/view/template/shipping/free.twig#L24) and [flat rate shipping](https://github.com/opencart/opencart/blob/b9e62a05bb76eff3d378d7b14980ea298e1856eb/upload/extension/opencart/admin/view/template/shipping/flat.twig#L24) ask for just one value, which they then optionally convert to another currency.

Flat rate shipping then charges the value directly, and free shipping uses it as a threshold determining whether free shipping is eligible.

**The problem with it**

For a store owner it may be more expensive to send, for example, to Western Europe vs. to Eastern Europe. Our old Deutsche Post prices are ~€3,50/kg vs. ~€8,00/kg respectively. This means with the current one-input approach, we either significantly overcharge the Western Europe customers by using the higher price, or lose money on Eastern Europe customers if using the lower price.

**What could be the solution**

Something similar to how [Weight-Based shipping](https://demo.opencart.com/admin/index.php?route=extension/opencart/shipping/weight) already lets us configure the rate based on weight per Geo Zone. Except here it would be just the cost (flat rate shipping) or total (free shipping) per destination country, or per Geo Zone, or maybe even per store – although I'm not sure if that'll work.

Ideally, the regional prices would be entered in respective currencies. This way, with flat rate shipping, the store owner can charge the round e.g. 19 SEK in Sweden and 2,99 CHF in Switzerland, instead of whatever comes out of automatic currency conversion.

Thank you!

**Comment by danielkerr** [comment]
u can do it using the discount system. set the min order qty to 1 and set the store.

normally for shipping an shipping api is used and u give it the location to and from and it will gvie the price to the customer. i suggest u setup ur own shipping method or check the extension store.
