### ISSUE TITLE
Contact form is not working on opencart 4.0.2.3 with smpt setup

### ISSUE THREAD

**Issue by BartosMihai** [opencart/opencart#13845]
**What version of OpenCart are you reporting this for?**
v4.0.2.3
**Describe the bug**
Contact form is not working on opencart 4.0.2.3 with smpt setup on fresh install. All other system mails are good

**To Reproduce**
1. Install
2. Setup smpt settings
3. go to contact page 
4. I have success on sending but email is not arriving to my imbox

**Expected behavior**
Go to contact end simply send an mail to admin store 

**Server / Test environment (please complete the following information):**
 - A2hosting
 - PHP 8.1
 - Browser(s) tested with chrome, edge latest versions
 

**Additional context**
ssl://
465

**Comment by mhcwebdesign** [comment]
The Contact Us page works just fine for OC 4.0.2.3. Make sure you have set your Mail Engine to SMTP.

For further help use the OpenCart forum.

**Comment by BartosMihai** [comment]
magazin.componente.eu
user: admin
pass: y@3Ye$92iX
I tried on 3 servers configuration.

**Comment by BartosMihai** [comment]
> The Contact Us page works just fine for OC 4.0.2.3. Make sure you have set your Mail Engine to SMTP.
> 
> For further help use the OpenCart forum.

I send you an email  white demo login

**Comment by BartosMihai** [comment]
I got the settings wrong! I apologize. Everything is ok!
