### ISSUE TITLE
Not Method "getStored" in Payment methods (Account)

### ISSUE THREAD

**Issue by ppalashturov** [opencart/opencart#13851]
**4.0.2.3 and 4.1.0.0**

**Describe the bug**
Hello,
@danielkerr 
When listing payment methods from your profile, an error appears that there is no such "getStored" method in the model from the following controller:
upload/catalog/controller/account/payment_method.php?
This is line 97 of the controller.
Thanks!

**Comment by danielkerr** [comment]
yes will fix, its already been reported.
