### ISSUE TITLE
[master - low prio] Different behavior on server and localhost at Security Notification

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#13855]
**What version of OpenCart are you reporting this for?**
master - localhost

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
There is a behavior on localhost which is not on the server installation.
After a new installation at the 1st login the Important Security Information window starts.
Then it is required to enter the storage path and press MOVE
And at this point I get the different behavior.
On the server the path is moved and the question for the new Admin name start autocratically - what is right. 
On localhost the path is moved and the question for the new Admin name DO NOT start autocratically.
I have to click on Dashboard to start it or at the next login it start autocratically and the I have to log in again with the new admin name.

At 0:22 sec. there is a warning message related to the log file. 
Warning: file_put_contents(/home/localhost/public_html/opencart/opencart-master.test/system/storage/logs/error.log): Failed to open stream: No such file or directory in /home/localhost/public_html/opencart/opencart-master.test/system/library/log.php on line 38Class "Twig\Loader\FilesystemLoader" not found: in /home/localhost/public_html/opencart/opencart-master.test/system/library/template/twig.php on line 36

**Expected behavior**

On both platforms the same behavior.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

[OpenCart-Security-manual-Admin.webm](https://github.com/opencart/opencart/assets/10166095/937c520c-d05b-4ee1-a67e-15113cc30984)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? 
   Linux atlas.multihost.cloud 4.18.0-477.27.2.lve.el8.x86_64 #1 SMP Wed Oct 11 12:32:56 UTC 2023 x86_64 
 - Operating system cloudlinux 
 - PHP version    8.2.16
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.9.1esr 

**Localhost / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system linux (debian)
 - PHP version    8.2.12
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.9.1esr

**Comment by danielkerr** [comment]
a not reproduce.

**Comment by pemaier** [comment]
It's solved. Thank you.
