### ISSUE TITLE
OC v4.1.0.0 - no controller calling these models

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#13852]
The following list are not called from any controllers over their models and checking if it's for extensions purposes:

- admin/model/catalog/product: getTotalOptionValuesByOptionValueId
- admin/model/sale/order: getTotalOrdersByOrderStatusId
- admin/model/sale/order: getTotalOrdersByCompleteStatus
- admin/model/setting/store: getTotalStoresByLayoutId
- admin/model/setting/store: getTotalStoresByOrderStatusId
- admin/model/user/user: getTotalUsersByEmail
- admin/model/customer/customer: getTotalAddresses

**Comment by danielkerr** [comment]
leave them in
