### ISSUE TITLE
You haven't configured any AI services yet

### ISSUE THREAD

**Issue by chuck1in** [opencart/opencart#13865]
**What version of OpenCart are you reporting this for?**
2.13.0 (469)

**Describe the bug**
在 appstore 下载本软件以后，选择直接开始对话，提示 You haven't configured any AI services yet

**Screenshots / Screen recordings**
<img width="936" alt="image" src="https://github.com/opencart/opencart/assets/15964712/f01e2ecc-02f3-4ac7-9d9f-e30b77c7ae13">

**Comment by mhcwebdesign** [comment]
There is no such 2.13.0 (469) version of OpenCart.

**Comment by chuck1in** [comment]
> There is no such 2.13.0 (469) version of OpenCart.

<img width="952" alt="image" src="https://github.com/opencart/opencart/assets/15964712/7f8b7e89-6d8d-4b3b-9b20-31ac8f7b3e66">

<img width="1424" alt="image" src="https://github.com/opencart/opencart/assets/15964712/9b704697-66f2-49bf-b6b1-a43db372a41e">

**Comment by IP-CAM** [comment]
Well, OPENCAT has nothing to do with OPENCARD

**Comment by chuck1in** [comment]
My god, I found the problem, I made a mistake between opencat and opencart.

**Comment by hayden-t** [comment]
that is funny shit there ! AI opencart when ???
