### ISSUE TITLE
PHP Warning: Undefined array key "rating"

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#13861]
https://github.com/opencart/opencart/blob/be82726c1c6b04bde8e76632e2422400d0be5dfb/upload/admin/controller/cms/article.php#L128

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/product/review.php#L188

**Comment by TheCartpenter** [comment]
@cgcmart: Which OC version?

**Comment by cgcmart** [comment]
It's obviously master /4.1 admin/controller/cms/article Line 128

**Comment by danielkerr** [comment]
ye but  rating is there. i think the isse is old
