### ISSUE TITLE
Argument #1 ($stock_status_id) must be of type int

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#13883]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
Product not loaded on catalog side.

Opencart\Catalog\Model\Localisation\StockStatus::getStockStatus(): Argument #1 ($stock_status_id) must be of type int, string given, called in /system/engine/loader.php on line 156 in /catalog/model/localisation/stock_status.php on line 16

**Comment by ppalashturov** [comment]
@condor2 @danielkerr 
I fixed here => #13885
