### ISSUE TITLE
Openacart Extension mOdule page showing space 

### ISSUE THREAD

**Issue by kiranmane1992** [opencart/opencart#13892]
version of OpenCart 
3.0.3.2
![Screenshot from 2024-04-25 17-14-30](https://github.com/opencart/opencart/assets/96581758/d16947bb-0b85-48bd-b1da-239e8f470a26)

Issue Description:
In the admin panel, when I go to Extensions and then Modules, there is a space below the select bar and no scroll bar appears.

**Comment by mhcwebdesign** [comment]
@cartbinder: This just bypasses the curl call to the OpenCart api/promotion . Not a real bugfix.

**Comment by osworx** [comment]
To describe this "bug" a bit more: normally OC loads a "promotion banner" above the list.
Fetching the code from OpenCart, which itself is "protected" by CloudFlare.

While we all know that Cloudflare ist not the optimal solution, it is as it is.
The mentioned fix does only bypass this promotion banner (and the call to OpenCart itself in the background).
As @mhcwebdesign telling, it's not really a fix, but will solve the current issue.

**Comment by cartbinder** [comment]
Yes, that is true. Internally the curl is asking for validation, presenting a challenge. Which will not be solved. As its not human. So there must be a temporary fix. 

Users have important things to do in the modules/payment method etc.

**Comment by mhcwebdesign** [comment]
Yeah, I agree, CloudFlare is a nightmare, and also slows things down.

**Comment by cartbinder** [comment]
This is a better way. Advertising will continue to work once the response is okay.

Updating the zip based on the above solution.

[scrollfix.ocmod.zip](https://github.com/opencart/opencart/files/15112534/scrollfix.ocmod.zip)

**Comment by osworx** [comment]
Honestly .. who ever needs that advertisement ??
