### ISSUE TITLE
[3.0.x.x]  PHP Unknown:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in admin/controller/extension/dashboard/map.php on line 102

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#13953]
**What version of OpenCart are you reporting this for?**
3.0.x.x

I used...

$isoCode2 = strtolower($result['iso_code_2'] ?? '');

$json[$isoCode2] = array(

for line 102
https://github.com/opencart/opencart/blob/3.0.x.x/upload/admin/controller/extension/dashboard/map.php#L102

**Comment by TheCartpenter** [comment]
See this solution: https://github.com/opencart/opencart-3/commit/6756f029e6b894e4c18cdd7b83c5c07a3c8a1521 .

**Comment by condor2** [comment]
@TheCartpenter 

With that solution orders/statistics sales are not show on Dashboard map

**Comment by TheCartpenter** [comment]
> @TheCartpenter
> 
> With that solution orders/statistics sales are not show on Dashboard map

Forgot to add ```AS``` alias. Now, it should work with orders already added.

**Comment by mhcwebdesign** [comment]
@condor2 : The only reason why you would get that PHP deprecation error is because you have orders from now non-existing countries. Hence I think a proper solution would be to use an INNER JOIN instead of a LEFT JOIN in the underlying DB query.

**Comment by TheCartpenter** [comment]
Perhaps a ```RIGHT JOIN``` could do it with these scenarios...

```The RIGHT JOIN keyword returns all records from the right table (table2), and the matching records (if any) from the left table (table1).```

**Comment by mhcwebdesign** [comment]
Now fixed, see https://github.com/mhcwebdesign/opencart/commit/87e36312ae8527b84bd2aa0f55c4c64f8331e9e9
