### ISSUE TITLE
[3.0.x.x] Unused currency code

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#13968]
**What version of OpenCart are you reporting this for?**
3.0.x.x github

**Describe the bug**
Still use same old code. It is called refresh method from model

https://github.com/opencart/opencart/blob/3.0.x.x/upload/admin/controller/common/dashboard.php#L93-L98

but model use old yahoo engine
https://github.com/opencart/opencart/blob/3.0.x.x/upload/admin/model/localisation/currency.php#L102-L123

**Comment by mhcwebdesign** [comment]
Thanks for pointing it out. Now fixed, see https://github.com/opencart/opencart/pull/13969
