### ISSUE TITLE
OC Version 4.0.2.3: Is Opencart Store API is realy work?

### ISSUE THREAD

**Issue by WuzenLiz** [opencart/opencart#13965]
**What version of OpenCart are you reporting this for?**
Version 4.0.2.3
**Describe the bug**
I'm trying build a bot for my store that use API for call and get thing. But i got that Opencart Docs was outdated and not working at my side

**To Reproduce**
dO aS oC dOcS sAiD.

**Expected behavior**
Yes, Api work

**Screenshots / Screen recordings**
![image](https://github.com/opencart/opencart/assets/30171626/838612f7-73cb-4c48-9564-94003e731281)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?: Self-deployed to a test server
 - Operating system: CentOS 
 - PHP version: PHP 8.1.28
 - Apache version: Apache/2.4.6
 - Browser(s) tested with [e.g. chrome, safari - if applicable]: Postman, Python requests
 - Version [e.g. 22]: latest all 

**Additional context**

**Comment by danielkerr** [comment]
it does work but not in the most efficient way. im working on a fix now.

**Comment by danielkerr** [comment]
im closing this because its liked to this

https://github.com/opencart/opencart/issues/12355
