### ISSUE TITLE
how to disable pagination and use scroll pages instead?

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#13962]
how to disable pagination and use scroll pages instead?
this means &page=2... won't be able to be visited,
only visitors can scroll the page to visit the next page.

**Comment by hayden-t** [comment]
just make your page size really big :p

**Comment by danielkerr** [comment]
look how i have done comments.

**Comment by hayden-t** [comment]
right, saw the completed link but didnt click it, thought it was just you closing the tickets you normally do with no explanation...
