### ISSUE TITLE
Currencies refresh issue

### ISSUE THREAD

**Issue by lemonadvert** [opencart/opencart#13963]
Hi,

When I try to refresh the currencies from the admin, the following error occurs:

Class 'DOMDocument' not found

I found that PHP XML library is missing:

https://github.com/opencart/opencart/blob/master/upload/extension/opencart/admin/controller/currency/ecb.php#L99

**Comment by danielkerr** [comment]
The DOMDocument class[ ¶]
(https://www.php.net/manual/en/class.domdocument.php#class.domdocument)
(PHP 5, PHP 7, PHP 8)


its built in. unless u are using a old php version
