### ISSUE TITLE
Admin Delivery method translations

### ISSUE THREAD

**Issue by lemonadvert** [opencart/opencart#13979]
**OpenCart 4.1.0.0**

**We have a multi-language store and admin. We found a bug, when we tried to change the Delivery method from the admin panel: Sales>Orders. The translations for the delivery extensions do not appear. I double-checked the translation files for text_description and heading_title and the translations exist. Can someone help with this?
**
![git-oc](https://github.com/opencart/opencart/assets/23619723/cbe8213e-41eb-4856-a734-b7e235a5d5be)

**Comment by stalker780** [comment]
1. There is no OC v 4.1.1.
2. Here is discussed an OC 4.0.2.0 which is not released yet.
3. You can find support for released versions of OC and it's extensions on https://forum.opencart.com/

**Comment by mhcwebdesign** [comment]
Assuming you meant OC 4.0.1.1 : Don't use it, it has too many known issues which were fixed in later releases. Use OC 4.0.2.3, or the master branch.

**Comment by lemonadvert** [comment]
Sorry, my mistake... I mean 4.1.0.0
I used the master branch.

**Comment by danielkerr** [comment]
i think some ne reported this already. wiull look into it but there is a way around it. 

[mhcwebdesign](https://github.com/mhcwebdesign) dont tell people something has to many known issues. 

its works fine
