### ISSUE TITLE
Shipping costs is not shown on the invoice

### ISSUE THREAD

**Issue by MischaOe** [opencart/opencart#14000]
Opencart 4.0.2.3

Hello
I have noticed that in version OC4.0.2.3 the shipping settings can be activated and this is also active, but can then be selected in the order, but is not shown on the invoice.
Is there another setting that I don't know about?
I have created an order with a test customer and was able to adjust the shipping costs on the order but it is not shown on the invoice at the end.
Maybe also a hint to check this in the OC4.1.0.0 version.
Is there a solution, what can be adjusted?
Many thanks for your help.
I look forward to the feedback.

Sorry my english is very bad
Have a nice day...

**Comment by happyxiaomao** [comment]
Hello! Is it possible to consolidate all product adding functionalities for the online store onto a single page? This includes the main product image, SKU images, SKU descriptions, details page images and descriptions, as well as the product pricing setup. Arranging them sequentially from top to bottom would allow us to preview everything at once when uploading products. It would also make it much more convenient to make changes to specific information without the need to navigate between different web pages!

**Comment by tmdashwani** [comment]
@MischaOe can you please share the print screen so we can get the issue 
I checked version 4.1.0.0, Shipping cost displaying  on invoice 
https://prnt.sc/CQHIfoDBh0O3

**Comment by danielkerr** [comment]
shipping costs are listed on the invoice. 
![image](https://github.com/user-attachments/assets/cfd5fcee-381f-479b-a6f2-417cf5fdc2a6)

**Comment by danielkerr** [comment]
![image](https://github.com/user-attachments/assets/837bb328-5a45-4328-b2ad-3287726d7a55)
