### ISSUE TITLE
Isseu in "catalog/controller/product/review.php" file on line no 88 and 90,  

### ISSUE THREAD

**Issue by devkapil8433** [opencart/opencart#14009]
**What version of OpenCart are you reporting this for 4.0

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect "user can't write review on product"

**To Reproduce**
1. Go to "catalog/controller/product/review.php"
2. Click on 'line 88 and 90'

**Expected behavior**

getting error while submit a review on product then i had find what issue causing and fix.
you type by mistake wrong model on line 88 of catalog/controller/product/review.php
you should fix, you need to call model "$this->load->model('catalog/product');"  insted of "$this->load->model('product/product');".
<img width="721" alt="Screenshot 2024-06-22 at 9 33 45 PM" src="https://github.com/opencart/opencart/assets/33986181/a088daa6-273a-4cdf-9846-1cd81bd4ab73">

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by TheCartpenter** [comment]
Already fixed in the MB.
