### ISSUE TITLE
Suggestions for the product adding page

### ISSUE THREAD

**Issue by happyxiaomao** [opencart/opencart#14006]
Hello! Is it possible to consolidate all product adding functionalities for the online store onto a single page? This includes the main product image, SKU images, SKU descriptions, details page images and descriptions, as well as the product pricing setup. Arranging them sequentially from top to bottom would allow us to preview everything at once when uploading products. It would also make it much more convenient to make changes to specific information without the need to navigate between different web pages!

**Comment by TheCartpenter** [comment]
It could also be ideal for the products API integration.
