### ISSUE TITLE
I cannot access the backend in the latest version cloned from the repository

### ISSUE THREAD

**Issue by ADDISON74** [opencart/opencart#14019]
**What version of OpenCart are you reporting this for?**
master branch (cloned today, June 28)

**Describe the bug**
I cannot access the backend. The layout seems to be affected too.

**To Reproduce**
1. Install from scratch
2. When the installer finishes click the [LOGIN TO YOUR ADMINISTRAION] buton
3. Fill in Username and Password
4. The page content is "{"redirect":"https:\/\/opencart.ddev.site\/admin\/index.php?route=common\/login"}"

**Expected behavior**
The form layout should be centered. I should be able to access the backend. 

**Screenshots / Screen recordings**
![screen1](https://github.com/opencart/opencart/assets/8360474/09c3d991-d0aa-4cc9-a2d7-c28cabb8d021)

![screen2](https://github.com/opencart/opencart/assets/8360474/ce3d20a2-1da7-4203-b7ec-51c1a9e6c4c7)

**Server / Test environment (please complete the following information):**
DDEV 1.23.2
Ubuntu 22.04
PHP 8.2.20
Apache version 2.4.59
Chrome 126.0.6478.115

**OFF TOPIC - ANOTHER ISSUE**
When installer finishes with success you will see the screenshot bellow. Just resize the window and what those three image. They are not responsive as the rest of the content.

![responsive](https://github.com/opencart/opencart/assets/8360474/b3b898e7-c516-4929-87d4-76554e1970eb)

**Comment by ADDISON74** [comment]
With the same server configuration this issue is not happening in the latest 3.0.3.9.

**Comment by TheCartpenter** [comment]
This issue should, then, be addressed on each OC Marketplace's extension pages.

**Comment by danielkerr** [comment]
refresh ur browser cache.  its still memorising the old css and javassript
