### ISSUE TITLE
Checkout - Add comments issue

### ISSUE THREAD

**Issue by ADDISON74** [opencart/opencart#14011]
**What version of OpenCart are you reporting this for?**
4.1.0.0 installed from scratch without any changes.

**Describe the bug**
I am not able to place the order if I add a comment in the checkout process.

**To Reproduce**
1. Create a customer account and add an address to speed up the checkout process.
2. Add a product to the cart then go to the cart page.
3. Follow the steps one by one to send the order. Choose the Address, the Shipping Method, and Payment Method.
4. Pay attention to the [Confirm Order] button, it looks the same like the other Choose above.
5. Fill in the "Add Comments About Your Order" and look to the [Confirm Order] button, the color changes to a light blue, it is disabled. Even you delete the comment the button won't come back to the enabled status. 
6. If you reload the page your will get ```Error: Could not call registry key model_checkout_order!: in /var/www/html/system/engine/controller.php on line 43```

**Expected behavior**
I should be able to send the order with a comment.

**Screenshots / Screen recordings**

![screenshot](https://github.com/opencart/opencart/assets/8360474/678a0b80-93ae-4d58-972b-db4e40390f9c)

**Server / Test environment (please complete the following information):**
- DDEV 1.23.2
- Ubuntu 22.04
- PHP 8.2.20
- Apache version 2.4.59
- Chrome 126.0.6478.115

**Additional context**
This issue is not occurring in the latest the 3.0.3.9 version.

**Comment by ADDISON74** [comment]
A small observation, in version 3.0.3.9 in step 5 there is the checkbox related to "Terms & Conditions" which is missing from version 4.

![screenshot](https://github.com/opencart/opencart/assets/8360474/d440f3bf-46c5-4c05-b960-4a55dfd5f198)

**Comment by adamruck2** [comment]
Same error with the same version of opencart, but getting the error while checking out as guest.

**Comment by adamruck2** [comment]
This is the snippit of code that triggers the error, it's in catalog/controller/checkout/confirm.php

`               if (isset($this->session->data['order_id'])) {
                        **$order_info = $this->model_checkout_order->getOrder($this->session->data['order_id']);**
                        if (!$order_info) {
                                unset($this->session->data['order_id']);
                        }
                }
`

**Comment by adamruck2** [comment]
It looks like the model for checkout/order wasn't loaded before attempting to reference it. It's loaded too late in confirm.php

**Comment by condor2** [comment]
> A small observation, in version 3.0.3.9 in step 5 there is the checkbox related to "Terms & Conditions" which is missing from version 4.
> 
> ![screenshot](https://private-user-images.githubusercontent.com/8360474/342106722-d440f3bf-46c5-4c05-b960-4a55dfd5f198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTA0NzksIm5iZiI6MTcyMDY5MDE3OSwicGF0aCI6Ii84MzYwNDc0LzM0MjEwNjcyMi1kNDQwZjNiZi00NmM1LTRjMDUtYjk2MC00YTU1ZGZkNWYxOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMDkyOTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE4ZDg0YjUzMzRmMDIxYzdmYWNmZjdiZmI3NDJjZDBlMDllMDZhOWI4MDQwMzZmMTY1MjQzMDBjYzliM2YyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wwg62upRQZ4g4oFC6qGHOTQ8zob_rY_1GB2YBVLDsEE)

You can add from store settings.

**Comment by retrina** [comment]
Someone added $this->load->model('checkout/order') and it works now.

**Comment by danielkerr** [comment]
its fixed.
