### ISSUE TITLE
The version listed in the backend is wrong

### ISSUE THREAD

**Issue by ADDISON74** [opencart/opencart#14012]
**What version of OpenCart are you reporting this for?**
3.0.3.9

**Describe the bug**
I downloaded from this repository the file named 3.0.3.9.tar.gz. I installed from scratch OpenCart. In Backend the version is listed as 3.0.3.8.

**Expected behavior**
Version listed in the backend should be 3.0.3.9.

**Screenshots / Screen recordings**
![screenshot](https://github.com/opencart/opencart/assets/8360474/2afbaf53-25ba-4cca-9185-bd6afb3d443b)

**Comment by mhcwebdesign** [comment]
Already fixed in the upcoming [3.0.4.0](https://github.com/opencart/opencart/tree/3.0.x.x)
