### ISSUE TITLE
Two issues related to the Image Manager

### ISSUE THREAD

**Issue by ADDISON74** [opencart/opencart#14010]
**What version of OpenCart are you reporting this for?**
4.1.0.0 - cloned from GitHub.

**Describe the bug**
I cannot create new folders using the **Image Manager**.

**To Reproduce**
1. Go to the admin interface then **Catalog** > **Products** > **Image** tab
2. Click on the **Edit** button
3. Click on the folder icon to create a new one

**ERROR 1**: Click on the [+] button without filling in anything. The warning message is not correct, "A file or directory with the same name already exists!". There is no such of thing. It should be "Please fill in a folder name".

**ERROR 2**:  Fill in a folder name with more than 3 characters and click on the [+] button. The warning message is "Folder name must be between 3 and 255!". This is not correct because I used opencart as folder name which has 8 characters. I am not able to create new folders even I follow the rule.

**Expected behavior**
OpenCart should ask for a folder name if nothing is filled in. 
I should be able to create folders having a 3 letters names. 

**Screenshots / Screen recordings**

**FOR ERROR 1**
![folder-name-2](https://github.com/opencart/opencart/assets/8360474/2fe81bcc-794a-4b1e-83ee-8a427a3122a0)

**FOR ERROR 2**
![folder-name](https://github.com/opencart/opencart/assets/8360474/cb25dc4f-d361-42c8-83f7-4143d060da04)

**Server / Test environment (please complete the following information):**
 - DDEV 1.23.2
 - Ubuntu 22.04
 - PHP 8.2.20
 - Apache version 2.4.59
 - Chrome 126.0.6478.115

**Comment by ppalashturov** [comment]
@ADDISON74 related #13999

**Comment by ADDISON74** [comment]
@ppalashturov - actually there are two errors related to the Image Manger in version 4. One when you press the [+] button without filling in the folder name. The other one when you fill in the folder name even the length is gte than 3 characters.

**Comment by ADDISON74** [comment]
It was fixed partially. Please check this comment:

https://github.com/opencart/opencart/commit/ac9c9b36618b5e2d4fcdc07f8f9735dc6b19d5ff#commitcomment-143660924
