### ISSUE TITLE
HTML does not save if it contains relative links

### ISSUE THREAD

**Issue by Belleson** [opencart/opencart#14015]
Not sure if this is a bug or intended behavior

What section does it affect?
HTML links in category, information, etc. pages

    Go to Categories
    Click on '+' for new category
    Scroll to General tab, click "Source" button
    Paste HTML such as
    <p><img alt="Product image" src="../../graphics/some_image.jpg" width="250px" /><br /> Our most amazing product!</p>

    Enter other required fields such as SEO tag, meta tag title
    Press Save button
    NOTHING happens, no save, no error pop-up, no entry in error log

    Expected behavior: Success! message

similar issue: a relative link in a menu module URL (Mega Menu Pro by ModulePoints) causes a 500 server error

Opencart Version | 4.0.2.3
Apache Version | 2.4.59
mySql Database Version | 8.0.37
Architecture | x86_64
Operating System | linux
PHP Version | 8.1
Perl Version | 5.26.3
Kernel Version | 4.18.0-513.18.1.lve.2.el8.x86_64

**Comment by ADDCreative** [comment]
Check you web browser's developer console. For me the issue was caused by hosting web application firewall.

**Comment by danielkerr** [comment]
could u not do /image/catalog/

**Comment by danielkerr** [comment]
i supposed there might be some base url that can be used.

**Comment by Belleson** [comment]
I can gradually migrate to /image/catalog, but the website was transferred from a combined 2.2.0.0 with standard HTML where the folder structure was already in place. I've worked around it for now using the full path URL
