### ISSUE TITLE
[master] Checkout Terms for Store 1+ are not visible

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#14024]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Checkout Terms activated in the store settings Option / Checkout are not visible for the customer at the checkout process. So the checkout button is not getting focus/activated.

**To Reproduce**
1. Go to 'Settings of any additional store'
2. Click on 'Option + Checkout'
3. Scroll down and choose any checkout terms and save
4. Login as customer order something and go to the checkout
5. See error

**Expected behavior**
Terms should appear so that the customer can accept them and the checkout button get active.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 127.0.2

**Comment by danielkerr** [comment]
u need to add the information page to show on said store as well as well as selecting it for checkout terms
