### ISSUE TITLE
Cannot assign string to property Opencart\System\Library\Mail::$adaptor of type object in /system/library/mail.php on line 32

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#14028]
{latest master branch}
Cannot assign string to property Opencart\System\Library\Mail::$adaptor of type object in /system/library/mail.php on line 32
send send out stmp mail

**Comment by TheCartpenter** [comment]
Which route?

**Comment by chongshengdz** [comment]
> Which route?

information/contact
admin/order = >Add History
