### ISSUE TITLE
API customer controller, question, potential issue

### ISSUE THREAD

**Issue by hayden-t** [opencart/opencart#14025]
https://github.com/opencart/opencart/blob/49d68ebfbf49107b542baf18acbf8a111f5a493e/upload/catalog/controller/api/customer.php#L35

Ive started a project that uses the API (via curl), I have logged in ok. 
For the next step want to set the active customer, to then operate the cart with.

The questions:

- This controller function can optionally be passed a customer_id but it only checks if its valid, and doesnt do anything with the loaded data.
- It seems to only operate as a guest checkout form, where any changes to customer details in admin add order customer form are not saved to customer, only order.
- Should I submit a pull request to make a login function that you only submit a customer_id too ?

Thanks

**Comment by hayden-t** [comment]
I realise now I was thinking the api could do something it didnt currently, I thought the api could be used to act as a customer account/cart , but this doesnt seem so,

It appears the API users each have their own cart, separate from each customers cart. I guess what im looking to do is similar to the "login as customer" from admin function but via api.

**Comment by danielkerr** [comment]
im closing this as still working on it

**Comment by hayden-t** [comment]
Great !, ill just give you some of the improvements ive made to meet my needs and might be of inspiration:

**Comment by hayden-t** [comment]
1 - I made all functions return a success value eg ShippingMethod/index returns the methods available, by adding a success along with that, as a user, you can have a universal api call library that always checks for the success/error value to know if the call worked or not. eg
```
$json['shipping_methods'] = $shipping_methods;
$json['success'] = 'Success: Get shipping methods';//new
```
I also did this in payment method and cart.

**Comment by hayden-t** [comment]
2 - I added select functions to customer and shipping address to select the active customer or address by id (or default address in case of address)

```
public function select (): void{
		
		$json = [];
		$this->load->language('api/sale/customer');
		$this->load->model('account/customer');

		if (isset($this->request->post['customer_id'])) {
			$customer_info = $this->model_account_customer->getCustomer($this->request->post['customer_id']);

			if (!$customer_info) {
				$json['error']['warning'] = $this->language->get('error_customer');
			}
			
			if (!$json) {
				$this->session->data['customer_id'] = $customer_info['customer_id'];
				$this->session->data['customer'] = [
					'customer_id'       => $customer_info['customer_id'],
					'customer_group_id' => $customer_info['customer_group_id'],
					'firstname'         => $customer_info['firstname'],
					'lastname'          => $customer_info['lastname'],
					'email'             => $customer_info['email'],
					'telephone'         => $customer_info['telephone'],
					'custom_field'      => $customer_info['custom_field']
				];

				$json['success'] = "Success: Customer selected";//$this->language->get('text_success');

				unset($this->session->data['shipping_methods']);
				unset($this->session->data['payment_methods']);
				unset($this->session->data['reward']);
			}

			$this->response->addHeader('Content-Type: application/json');
			$this->response->setOutput(json_encode($json));
		}
	}
```
```
public function select (): void{
		$this->load->language('checkout/shipping_address');
		
		$json = [];

		if (isset($this->request->post['address_id'])) {
			$address_id = (int)$this->request->post['address_id'];
		} else {
			$address_id = 0;
		}
		
		if($address_id == -1){//get default
			$address_id = $this->customer->getAddressId();
		}

		if (!$json) {
			$this->load->model('account/address');

			$address_info = $this->model_account_address->getAddress($address_id);

			if (!$address_info) {
				$json['error'] = $this->language->get('error_address');
			}
		}

		if (!$json) {
			$this->session->data['shipping_address'] = $address_info;

			$json['success'] = "Success: Address selected";

			unset($this->session->data['shipping_methods']);
		}

		$this->response->addHeader('Content-Type: application/json');
		$this->response->setOutput(json_encode($json));
	}
```

**Comment by hayden-t** [comment]
3 - When selecting the active customer (above) I added setting the session customer_id:
`$this->session->data['customer_id'] = $customer_info['customer_id'];`

From my research I cant see any problem with this, and it means that all the standard system customer library functions work that for example use `$this->customer->getId()`

**Comment by hayden-t** [comment]
another little thing that is neat, and doesnt need changing, but hopefully can be kept the same, is that the result array returned from api cart index function is the same format as the $data vars used in front end controller cart function, so ive been able to just pass the api result to the existing view templates and get a cart list and confirm totals as it would appear in the normal checkout, but elsewhere. :)
