### ISSUE TITLE
[master] Config new store - Design Layout entries ... for default store added

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#14023]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

When a new store is added then in the Design Layouts an entry is generated .. for all layouts.
The entries are getting created but the reference is not the new store it is referenced to the Default store. 

**To Reproduce**
1. Go to 'Settings'
2. Create a store 'Add new'
3. Enter data and save
4. Got Design Layouts open "Account" or any other
5. See error

**Expected behavior**

The reference to the new entries should be the new store

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

![image](https://github.com/opencart/opencart/assets/10166095/f5505577-e26a-4ac0-901f-6c720a7e22c4)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system Linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 127.0.2

**Comment by tmdashwani** [comment]
HI
please apply this fix 
https://github.com/tmdashwani/opencart/commit/05506fc3a6c29e8d882358e1ca4e564996774245
you will get solution 
thank you
