### ISSUE TITLE
The storage directory is moved but a copy of it remains in the system directory

### ISSUE THREAD

**Issue by ADDISON74** [opencart/opencart#14021]
**What version of OpenCart are you reporting this for?**
3.0.3.9

**Describe the bug**
After the installation, accessing the backend, OpenCart asks for moving the storage directory, as an important security notification. Even you move it there is as a copy in the system directory.

**To Reproduce**
1. Install OpenCart then access the backend
2. OpenCart asks for moving the storage directory outside of the web directory
3. Click the [Move] button. A confirmation window appears. **As an observation the part I surrounded by red color should not be there once the action ends with success because it creates confusion, you can repeat the action.**

![screen_2](https://github.com/opencart/opencart/assets/8360474/46f6b0b4-f96c-4e66-905d-b042c6ece784)

4. Open the file manager and check the system directory content. The storage directory should be moved but it is still there.

**Expected behavior**
Moving action means to move something, nothing should be left in the initial position (like mv command in Linux). The storage directory shouldn't be in the system directory. OpenCart actually copies the storage directory in a new location.

**Server / Test environment (please complete the following information):**
DDEV 1.23.2
Ubuntu 22.04
PHP 8.2.20
Apache version 2.4.59
Chrome 126.0.6478.115

**Comment by danielkerr** [comment]
in the latest it should make a request to delete the old directory
