### ISSUE TITLE
[Image Manager] I cannot delete folders

### ISSUE THREAD

**Issue by ADDISON74** [opencart/opencart#14020]
**What version of OpenCart are you reporting this for?**
Latest version 4.1.0.0 cloned today (June 29)

**Describe the bug**
The [Delete] button is not working in the **Image Manager** window.

**To Reproduce**
1. Go to the backend
2. Edit any product then go to the [Image] tab
3. Click on the [Edit] button of any image. Create a folder. 
4. Select the created folder then click the [Delete] button and confirm the action.
5. After it is done the folder is still visible. Please note this is not happening in the latest v3.

**Expected behavior**
After clicking on the [Delete]button the folder should not be listed.

**Server / Test environment (please complete the following information):**
DDEV 1.23.2
Ubuntu 22.04
PHP 8.2.20
Apache version 2.4.59
Chrome 126.0.6478.115

**Additional context**
It seems that for deleting the files it is working as expected. The issue is related only to the folders. I cannot delete the ones that OpenCart installs too.

**Comment by danielkerr** [comment]
can not replicate
