### ISSUE TITLE
Can't delete orders

### ISSUE THREAD

**Issue by lemonadvert** [opencart/opencart#14035]
**OpenCart 4.1.0.0**

**Deleteing orders not wokring. When you click the delete button the confirmation popup does not appear.**

**Comment by ppalashturov** [comment]
@danielkerr 
https://github.com/opencart/opencart/blob/f863f9285c5fa283d5a8771eddedd884b5309113/upload/admin/view/template/sale/order.twig#L187

`url: 'index.php?route=sale/order.call&user_token={{ user_token }}&call=sale/order.delete',`

**Comment by retrina** [comment]
> @danielkerr
> 
> https://github.com/opencart/opencart/blob/f863f9285c5fa283d5a8771eddedd884b5309113/upload/admin/view/template/sale/order.twig#L187
> 
> `url: 'index.php?route=sale/order.call&user_token={{ user_token }}&call=sale/order.delete',`

By changing this code, there is still a problem.

**Comment by danielkerr** [comment]
its fixed.

**Comment by danielkerr** [comment]
order editor and delte should be fully woirkign without isssues
