### ISSUE TITLE
{master branch}need optimization about where LCASE(`email`) when selecting data from database

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#14030]
{master branch}need optimization about where LCASE(`email`) when selecting or deleting data from database
https://github.com/search?q=repo%3Aopencart%2Fopencart%20LCASE(%60email%60)&type=code
using where LCASE(`email`) will not use index condition, these queries will only appear in the slow log, so  you need to change all the  LCASE(`email`) = '" . $this->db->escape(oc_strtolower((string)$email)) . "' to  `email` = '" . $this->db->escape(oc_strtolower((string)$email)) . "' since the oc_strtolower is already in use.

**Comment by chongshengdz** [comment]
oc_customer table, need to change  email index to union index (email, ip, status) according to the database queries.

**Comment by danielkerr** [comment]
`email` = '" . $this->db->escape(oc_strtolower($data['email'])) . "' so it makes no difference!
