### ISSUE TITLE
CKeditor out of date

### ISSUE THREAD

**Issue by castinstyleuk** [opencart/opencart#14034]
**What version of OpenCart are you reporting this for?**
Version 4.0.2.3

**Describe the bug**
Just recently when I go to edit a description in the admin system, I am getting a red popup message saying 
"This CKEditor 4.22.1 version is not secure. Consider upgrading to the latest one, 4.24.0-lts."
It looks like the CK Editor is out of date. Can you look into updating this please. I have tried to upgrade the CK Editor but I think you plugin needs to be made to work with it as well. 

**To Reproduce**
1. Log in to admin. Go to a product or a category in the editor and go to the general  tab. 
A red box will pop up with the error described above.

**Expected behavior**
This box is annoying and also mentions a security risk, so it need upgrading to the latest CKeditor

**Screenshots / Screen recordings**
![Screenshot 2024-07-05 085117](https://github.com/opencart/opencart/assets/86596232/b7c50b5b-fc61-420e-a423-11e6a473febd)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? in Development
 - Operating system Windows Google chrome
 - PHP version 8.2

**Additional context**

**Comment by mhcwebdesign** [comment]
Already answered here: https://github.com/opencart/opencart/issues/14032
