### ISSUE TITLE
Need to Update Opencart Documentation for Opencart 4

### ISSUE THREAD

**Issue by kevalpatel02** [opencart/opencart#14038]
**What version of OpenCart are you reporting this for?**
Opencart 4.x.x.x

**Describe the bug**
I am an OpenCart developer at a web development company. When I started working with OpenCart, I found it difficult to handle client-specific custom features and extension development due to the limited resources available on YouTube and the documentation only covering OpenCart 3. We use OpenCart 4 for our client's projects, so it's crucial to improve the OpenCart 4 documentation and provide comprehensive guides for extension development for both OpenCart 3 and 4.

**Additional context**
We could create a separate documentation project, similar to how frameworks like Laravel have dedicated documentation sites. Additionally, we can use markdown files for maintaining the documentation.

**Comment by danielkerr** [comment]
please do!

**Comment by danielkerr** [comment]
a lot of people offer to help but prefer to just add their own features.

**Comment by danielkerr** [comment]
post  a link to a example and see if the community likes it then we can maybe come up with a price.

**Comment by koriyapankaj** [comment]
Alright, I think this is a fantastic idea; it will take some time to plan and make a basic sample. but I believe I can manage in weekends; after I'm done, I'll post a link to the project's prototype in this thread.

**Comment by danielkerr** [comment]
any one out there whos good at writing documentation with screen shots etc.. and writing examples please msg me. will pay to update documentation.
