### ISSUE TITLE
The demo does not load the icons well

### ISSUE THREAD

**Issue by curiosport** [opencart/opencart#14033]
I have noticed that the icons are not loading in the [demo](https://demo.opencart.com/), please fix it, I can't show that demo to my potential clients.

**Comment by stalker780** [comment]
Looks fine to me.

![image](https://github.com/opencart/opencart/assets/6297070/d24859b2-35e1-4863-859e-df6f24bec289)

**Comment by mhcwebdesign** [comment]
First of all, the demo.opencart.com uses the older 4.0.1.1 which has a number of known bugs.

Also, the opencart.com uses the CloudFlare CDN which frequently causes incomplete page loads, including missing icons.

If you want to show a customer the OpenCart software use a local install on your own computer, using at least 4.0.2.3, or a stable 3.0.3.9 or 3.0.4.0 version.

**Comment by danielkerr** [comment]
bloody cloudflare!

**Comment by mhcwebdesign** [comment]
@danielkerr : Talking about CloudFlare, your forum.opencart.com is virtually unusable because of it, especially when using the Firefox web browser. Most of the times, it won't load images or stylesheets, unless you do multiple refreshs.

CloudFlare is not a professional CDN !

**Comment by danielkerr** [comment]
i updated the forum cloudflare settings. should require one js challange then should be ok.

**Comment by mhcwebdesign** [comment]
> i updated the forum cloudflare settings. should require one js challange then should be ok.

Thanks, works much better now with the FireFox browser, haven't had any missing images nor styles for past 30 minutes.
