### ISSUE TITLE
{master branch}how to get the unique $pair on line 87 in catalog/controller/startup/seo_url.php ?

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#14046]
{master branch}how to get the unique $pair on line 87 in catalog/controller/startup/seo_url.php ?
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/startup/seo_url.php
in order to make sure it won't waste time and lots of CPU usage to query duplicate results from database.

**Comment by danielkerr** [comment]
i thought i did something to optimize this.

**Comment by chongshengdz** [comment]
the optimization is not reliable.
when you are on product page and then click on the drop-down category menu, the category page is not found.
need more optimization
