### ISSUE TITLE
CKEditor not Secure

### ISSUE THREAD

**Issue by mehtaman** [opencart/opencart#14043]
**What version of OpenCart are you reporting this for?**
4.0.2.3

**Describe the bug**
Description box shows a red box with the message below:
`This CKEditor 4.22.1 version is not secure. Consider [upgrading to the latest one](https://ckeditor.com/ckeditor-4-support/), 4.24.0-lts.`

**To Reproduce**
1. Category
2. New
3. Description box has red box in the middle

**Expected behavior**
No error message

**Screenshots / Screen recordings**
<img width="247" alt="image" src="https://github.com/user-attachments/assets/bdd14722-a761-404b-a732-80e98c6714bc">

**Server / Test environment (please complete the following information):**
 - Hostinger Business Plan
 - Operating system: Not sure, Linux based?
 - PHP version: 8.3.1
 - Apache version: Not Sure
 - Browser - Chrome
 - Version - 126.0.6478.127 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by stalker780** [comment]
https://github.com/opencart/opencart/issues/14032

**Comment by mhcwebdesign** [comment]
Already answered here: https://github.com/opencart/opencart/issues/14032
