### ISSUE TITLE
Opencart - Single Page Checkout problem

### ISSUE THREAD

**Issue by Geor4** [opencart/opencart#14049]
I tried to install this extension - https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=15580&filter_search=one%20page%20checkout

But something broke and now there is some error - Unknown: Creation of dynamic property Template\Twig::$registry is deprecated 

How can I fix it?

**Comment by mhcwebdesign** [comment]
Contact the author dreamvention at https://www.opencart.com/index.php?route=support/seller&extension_id=15580

Or post on the OpenCart forum.
