### ISSUE TITLE
[master branch] aws/aws-sdk-php not needed ?

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#14063]
**What version of OpenCart are you reporting this for?**
master branch

**Describe the bug**
Do we really need the vendor library aws-sdk-php in the OpenCart core? From what I can see neither OpenCart itself, nor its standard extensions use this vendor library. The authors of the aws-sdk-php don't seem to be able to publish a stable release of their library, as is evident by their almost daily updates. See also https://github.com/aws/aws-sdk-php/discussions/2965

**Comment by TheCartpenter** [comment]
> **What version of OpenCart are you reporting this for?** master branch
> 
> **Describe the bug** Do we really need the vendor library aws-sdk-php in the OpenCart core? From what I can see neither OpenCart itself, nor its standard extensions use this vendor library. The authors of the aws-sdk-php don't seem to be able to publish a stable release of their library, as is evident by their almost daily updates. See also [aws/aws-sdk-php#2965](https://github.com/aws/aws-sdk-php/discussions/2965)

You've also been answered by the official channels on that topic the reason on why this is happening as the answer has been tagged during the same period of time you created the topic over there in the first place, therefore, I'd say it's pretty good timing. Thank god there's a repository that has what it takes on this site to maintain their projects on a periodic basis.

**Comment by punitkumar** [comment]
Do we really need the vendor library aws-sdk-php in the OpenCart core? From what I can see neither OpenCart itself, nor its standard extensions use this vendor library. 

As far as I can see, above part still unanswered.

**Comment by TheCartpenter** [comment]
Furthermore on the subject, it also doesn't explain the integration of Google Shopping libraries built-in the core without having a vendor since all these years which could cause more issues to the core itself as opposed to OC v3.2x and v4.x releases that do encourage users to rely on vendor packages and parallel integrations based on the publicized extensions on the market. During those times, people were still encourage to use the OC v3.x releases in regard to flexibility vs. OC v4.x releases.

Does it necessarily ease the task of development between OC v3.x releases and OC v4.x releases? Not really. However, OC v4.x releases do provide different approach rather than encouraging users to integrate services straight from the core.

**Comment by mhcwebdesign** [comment]
Still not answering this question. Once OC 4.1.0.0 is released, the aws-sdk-php will likely be not a stable release. It's not the responsibility of OpenCart to maintain 3rd-party extensions. After all, that's why most payment extensions aren't part of the OpenCart core anymore. The same should be true for aws-sdk-php. Most OpenCart stores won't even use any extension with this aws-sdk-php.

**Comment by TheCartpenter** [comment]
Answered here already: https://github.com/opencart/opencart/pull/14064#issuecomment-2265200033 .

**Comment by batumibiz** [comment]
AWS is not used and is not needed in the distribution.
If some extension will use it, then AWS should ship with it, and not with the engine itself.
I already sent a pull request #13624 regarding this matter, but it was not accepted.

**Comment by TheCartpenter** [comment]
> AWS is not used and is not needed in the distribution. If some extension will use it, then AWS should ship with it, and not with the engine itself. I already sent a pull request #13624 regarding this matter, but it was not accepted.

Then, it hasn't been accepted for the right reasons.

**Comment by mhcwebdesign** [comment]
It's obvious that the authors of the aws-sdk-php aren't able to provide a stable API for this at the moment. Perhaps I'll create a free OpenCart extension which allows the user to remove the aws-sdk-php, to make OpenCart 4 more lightweight and robust.

**Comment by TheCartpenter** [comment]
An extension can be created at your complete and total discretion, since a development release of a platform does not expect to have stable features, including vendors, until being stable even though AWS does not describe nor hasn't been tagged as a development release either way.

**Comment by batumibiz** [comment]
@TheCarpenter Stop generating spam!
You write some kind of nonsense.
You spammed the entire history of comits, there is no peace in the comments from you either.
It is better not to write anything, it is calmer without you.

**Comment by eka7a** [comment]
> Still not answering this question. Once OC 4.1.0.0 is released, the aws-sdk-php will likely be not a stable release. It's not the responsibility of OpenCart to maintain 3rd-party extensions. After all, that's why most payment extensions aren't part of the OpenCart core anymore. The same should be true for aws-sdk-php. Most OpenCart stores won't even use any extension with this aws-sdk-php.

@mhcwebdesign @danielkerr answered the question here but i think it is unnecessary if it will only be used for S3 storage.
https://github.com/opencart/opencart/pull/13624#issuecomment-1915347025

**Comment by mhcwebdesign** [comment]
@eka7a : You are right. There are alternatives if all we want is to use the Amazon S3 storage for future 3rd party extensions (OpenCart core doesn't even use it). See for example this one: https://medium.com/@martindrapeau/simple-php-code-to-push-files-to-aws-s3-3396f9b3d02a

**Comment by danielkerr** [comment]
yes in the next version after the current one is released i plan to allow files to be stored on cloud s3.

**Comment by mhcwebdesign** [comment]
> yes in the next version after the current one is released i plan to allow files to be stored on cloud s3.

In that case we need a better alternative library for the cloud S3 storage, the aws-sdk-php hasn't been able to provide one!
