### ISSUE TITLE
Open Redirect

### ISSUE THREAD

**Issue by mateuszismyname** [opencart/opencart#14075]
**Latest**

**Type of bug**
An open redirect vulnerability occurs when an application allows a user to control a redirect or forward to another URL

**To Reproduce**
POST /index.php?route=common/language/language HTTP/2
Host: redacted
Cookie: OCSESSID=<something>; language=en-gb; currency=EUR
Content-Length: 253
Cache-Control: max-age=0
Sec-Ch-Ua: "Not/A)Brand";v="8", "Chromium";v="126"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Accept-Language: en-GB
Upgrade-Insecure-Requests: 1
Origin: https://redacted
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryebLPQ9WBaPYSgRst
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.57 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: https://redacted
Accept-Encoding: gzip, deflate, br
Priority: u=0, i

------WebKitFormBoundaryebLPQ9WBaPYSgRst
Content-Disposition: form-data; name="code"

pl
------WebKitFormBoundaryebLPQ9WBaPYSgRst
Content-Disposition: form-data; name="redirect"

https://evilsite.com
------WebKitFormBoundaryebLPQ9WBaPYSgRst--

**Expected behavior**
User should not be redirect to a different domain for security reasons.

The user will be redirected to https://evilsite.com

**Server**
 - Deployed and online
 - OS: Linux
 - Apache
 - Browser tested on: Brave
 - Version: [Version 1.68.134 Chromium: 127.0.6533.88](https://brave.com/latest/)

**Comment by mhcwebdesign** [comment]
You are going to have to provide a lot more details if you want help here.

How exactly were you instantiating this bug? What exactly did you enter in your web browser, and how?

**Comment by ADDCreative** [comment]
@mateuszismyname At least say what version of OpenCart.

I believe this was fixed with https://github.com/opencart/opencart/pull/13095.

**Comment by mateuszismyname** [comment]
I hope to get this information soon and I will update you asap.
