### ISSUE TITLE
Subscription: Missing Method "getProductByOrderProductId "

### ISSUE THREAD

**Issue by prdpmishra** [opencart/opencart#14086]
Notice: Undefined property: Proxy::getProductByOrderProductId in admin\controller\sale\subscription.php on line 671: in system\engine\proxy.php on line 85

**Comment by mhcwebdesign** [comment]
Try the master branch. The subscription was still work in progress in OC 4.0.2.3.

**Comment by danielkerr** [comment]
shoould be getProductsByOrderProductId

**Comment by danielkerr** [comment]
not sure which branch u mean.
