### ISSUE TITLE
Error  Page not found.

### ISSUE THREAD

**Issue by vingoyf** [opencart/opencart#14097]
**What version of OpenCart are you reporting this for?**
4.0.2.3

i added a new controller,   directly modified the source code.,  the name of controller directory and file, model directory and file, language directory and file, class, view, twig file,   are ALL correct. and added permissions to User Groups, 

but there is still error  'Page not found.'
 is there anything that i should do?

I have experience developing with version 3.0.  but first time for opencart 4.0.  I'm looking forward to your help.

ubuntu0.24.04.1,
mysql  8.0.39
nginx  1.24

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system:   ubuntu 24
 - PHP version  8.
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by mhcwebdesign** [comment]
Better post it on the [OpenCart forum](https://forum.opencart.com/), with some more details, in order for someone to help you.
