### ISSUE TITLE
Still missing subscription table!

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#14103]
After a new install
- save Settings
- when opening Report / Customer Subscription Report an error occur. -
Exception: Error: Table 'aqq20848_opencart_master_demo.oc_subscription_transaction' doesn't exist
Error No: 1146
SELECT COUNT(DISTINCT `s`.`customer_id`) AS `total` FROM `oc_subscription_transaction` st LEFT JOIN `oc_subscription` s ON (st.`subscription_id` = `s`.`subscription_id`) LEFT JOIN `oc_customer` c ON (`s`.`customer_id` = c.`customer_id`) in /home/aqq20848/public_html/opencart/master.demo/system/library/db/mysqli.php on line 68

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] FF
 - Version [e.g. 22] 115.0.2

_Originally posted by @pemaier in https://github.com/opencart/opencart/issues/11458#issuecomment-1633987510_
            

25th August 2024 - published as "stable" version .. issue still open since many month!
When will this be fixed ???

OC 4.0.2.3

Error: Table 'dev_4.oc_subscription_transaction' doesn't exist
Error No: 1146
SELECT COUNT(DISTINCT `s`.`customer_id`) AS `total` FROM `oc_subscription_transaction` st LEFT JOIN `oc_subscription` s ON (st.`subscription_id` = `s`.`subscription_id`) LEFT JOIN `oc_customer` c ON (`s`.`customer_id` = c.`customer_id`): in ..\system\library\db\mysqli.php on line 76

**Comment by TheCartpenter** [comment]
The main issue is still opened: https://github.com/opencart/opencart/issues/11458 . It's still in the works.

**Comment by danielkerr** [comment]
there is no missing tables with the master.

**Comment by osworx** [comment]
Maybe the table is in the master, but in the **4.0.2.3 Version which is published as stable**, it is NOT!
So, either publish a new 4.0.2.4 version, or come to an end with the 4.1.0.0 version ..
