### ISSUE TITLE
[OpenCart Install] Error: Could not make a database link using myshop@localhost!

### ISSUE THREAD

**Issue by Jiiua** [opencart/opencart#14109]
**What version of OpenCart are you reporting this for?**
4.0.2.3 and commit 6fef235 (latest at the time of this issue)

**Describe the bug**
When installing OpenCart and filling the mysql or mariadb credentials with a valid account (with `localhost` and `%` and accessible on the CLI), _the following error occurs_ (with either mysqli or mdpo selected):

>  Error: Could not make a database link using myshop@localhost!
Message: No such file or directory

I have tried with both Apache and Nginx, and `mysql:latest` and `mariadb:latest` in Docker in the port `3307`

**To Reproduce**
1. Move OpenCart files to a http server (either Apache or Nginx) and give permissions as indicated by the OpenCart INSTALL.md
2. Install mysql/mariadb in a Docker container (with a different port from the default, in my case i tried 3307) and run the container
3. Try to install OpenCart and give the database credentials (it can be root or an account just for a single database, same result here)

**Expected behavior**
I expect it to work and install, since i tried a free database from [FreeDB](https://freedb.tech/dashboard/) and it installs, works fine

**Screenshots / Screen recordings**
![Screenshot_20240829_202252](https://github.com/user-attachments/assets/015985ac-ed80-49d9-9b11-74a7b8ab5fb3)

**Server / Test environment (please complete the following information):**
 - Local development
 - Fedora 39
 - PHP 8.2
 - Apache version latest or Nginx latest

**Comment by danielkerr** [comment]
did u setup the database?

**Comment by Jiiua** [comment]
> did u setup the database?

I did with a simple docker compose configuration, i'll post here:
```
services:
  database:
    container_name: "database-mariadb"
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=12345
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  db-data:
```
then i just ran `docker compose up -d` and then i tried to do `docker exec -it database-mariadb /bin/bash ` then `mysql` and that logged in OK.

So after being OK trough the CLI, i created a database called `oc_shop` with a query, it returned OK.

Then i tried giving username `root`, password `12345`, hostname `localhost` and port `3307` and database `oc_shop` to OpenCart, which resulted in the 'could not make a database link' error.

I also thought maybe it was because it being a root account, so i created a new account called `myshop` (with password 12345) without admin privileges, but gave normal privileges (insert, update, delete etc) for `myshop` at database `oc_shop`,
i tried then to enter trough the CLI, and it returned OK

However trying the same details on OpenCart install by giving username `myshop`, password `12345`, hostname `localhost` and port `3307` and database `oc_shop` to OpenCart, and it also returned the same error.

**Comment by Tienam123** [comment]
Your site is on docker , so you don't need 3007 post. I have something and when write in the instalation port mysql on docker 3306 , then it work

**Comment by danielkerr** [comment]
so its ok?
