### ISSUE TITLE
Question about the seo_url for the categories

### ISSUE THREAD

**Issue by MMahach** [opencart/opencart#14107]
Can someone explain me a logic of the seo_url value in the categories?

As far as I understand, the seo_url's value must be unique, which looks natural, ofc. In the same time, a single category's seo_url value contains the full path of this category, which is also pretty unique. But what I didn't understand, why OC shows the error "keyword exists" for a category if it's keyword also used in some other categories branch?

For example:
Let say there is a following categories tree:
_TopCategory -> Category 1 > Subcategory 1_
The seo_url will be: "topcategory/category-1/subcategory-1"
Then, a new category will be added into the top one, and it also will contain the _Subcategory 1_ category, like that:
_TopCategory -> Category 2 > Subcategory 1_
it's seo_url will be: "topcategory/category-2/subcategory-1"
They are different and unique, aren't they? But the keyword for both categories _Subcategory 1_ is the same, and this is also natural, from my point of view. However on the attempt to save 2nd one the OC throws an error. Why?

Thank you in advance!

I'm using the OpenCart 4.0.2.x.

**Comment by danielkerr** [comment]
just a limitation of the seo system

**Comment by MMahach** [comment]
Thank you for the answer! Just few more clarification, if possible, please.

The OC's seo system or what?

Does that mean I will break the seo functionality if I'll change the condition (seo_url duplicate check)?

**Comment by danielkerr** [comment]
u would need to to do some alteration so it would break the seo. 

maybe add a query to detect if the seo url keyword is a category then set something up to detect if one keyword is related to another and with a different value.
