### ISSUE TITLE
I recieve 90-100 missing orders with each order i place for products with "Special prices''. 

### ISSUE THREAD

**Issue by skullerud2280** [opencart/opencart#14117]
Hello Opencart experts, 

I am using:
Opencart V. 3.0.3.9 downloaded here "https://github.com/opencart/opencart/tree/3.0.3.9".
Themes tried: Default and eMarket for Opencart.
Fresh installed without any extra plugins.

Problem:
When i place an order for products with ''special price" i recieve a lot off missing orders (90-100 missing orders).
There is no issue when i place order for products with normal price. I don't know what is wrong with ''special price" section and how to fix it?

Anyone who face same problem?
 
I appriciate all help and tips.

Best regards

**Comment by ADDCreative** [comment]
Could be an issue with a payment extension. Best to ask on https://forum.opencart.com/.

**Comment by mhcwebdesign** [comment]
Just tested it with both OC 3.0.3.9 and 3.0.4.0, and there are no issues with special prices. As AddCreative suggested, please post on the OpenCart forum, with some more details.
