### ISSUE TITLE
Installed extensions status remains at "Disabled"

### ISSUE THREAD

**Issue by eug-L** [opencart/opencart#14111]
**What version of OpenCart are you reporting this for?**
4.0.2.3

**Describe the bug**
Installing extensions does not change status from "Disabled" to "Enabled". 

**To Reproduce**
1. Go to Extensions page
2. Select any extension type
3. Click install for any extension
4. Status for that extension is unchanged ("Disabled")

**Expected behavior**
Status should be changed to "Enabled"

**Screenshots / Screen recordings**
[Screencast from 2024-09-02 10-43-29.webm](https://github.com/user-attachments/assets/65e866fe-67a3-4e8c-8725-af6a9cacc20d)

**Server / Test environment (please complete the following information):**
Tested on docker image bitnami/opencart:latest

**Additional context**

**Comment by tmdashwani** [comment]
HI
when you install any shipping method that is just installed, for enable you need to edit  and set status  { enable }
https://prnt.sc/2e6_Qv8yeuuh

thank you

**Comment by eug-L** [comment]
understood, thanks for clarifying!
