### ISSUE TITLE
Hosting company block my emails because of "Missing Message-ID Email Header" (Solved)

### ISSUE THREAD

**Issue by skullerud2280** [opencart/opencart#14116]
Hello Opencart experts,
This is my first post ever and i am not sure where to post it so please move this post to right place if possible.

I am using:
Opencart V. 3.0.3.9 downloaded here "https://github.com/opencart/opencart/tree/3.0.3.9".
Themes tried: Default and eMarket for Opencart.
Fresh installed without any extra plugins. 

I have an issues with this version. 
Hostinger block my emails to customer, and admin recieve order and new customer emails in spam folder.

I talked to hosting company and recieved this message '' The solution will be to resolve the main source of the issues. And for that, it is necessary to ensure the Opencart mailer will add message IF on the SMTP delivery'' I am not sure what to change and in which file.

I will appriciate all help/tips.

Best regards

**Comment by eka7a** [comment]
system/library/mail/smtp.php

FIND
`$header .= 'Return-Path: ' . $this->from . PHP_EOL;`

ADD BEFORE
`$header .= 'Message-ID: <' . base_convert(str_replace(['.', ' '], '', microtime()), 10, 36) . '.' . base_convert(bin2hex(openssl_random_pseudo_bytes(8)), 16, 36) . substr($this->from, strrpos($this->from, '@')) . '>' . PHP_EOL;`

**Comment by skullerud2280** [comment]
> system/library/mail/smtp.php
> 
> FIND `$header .= 'Return-Path: ' . $this->from . PHP_EOL;`
> 
> ADD BEFORE `$header .= 'Message-ID: <' . base_convert(str_replace(['.', ' '], '', microtime()), 10, 36) . '.' . base_convert(bin2hex(openssl_random_pseudo_bytes(8)), 16, 36) . substr($this->from, strrpos($this->from, '@')) . '>' . PHP_EOL;`

**Comment by skullerud2280** [comment]
Dear [eka7a](https://github.com/eka7a)
Thank you for your reply, i have tested 2-3 times and this issue is solved. Do you have any suggestion for my second issue? 

Best regards

**Comment by parkook** [comment]
Thanks, this has fixed my problem. The system was also sending duplicated of identical emial order receipts and now it has been behaiving correctly so far.

**Comment by imbarazz** [comment]
I'm running OC 4.3.2. I am also experiencing this issue. I reached out to MailChannels and they informed me that my emails are missing message ID. Hope this does the trick. Thanks.

**Comment by mhcwebdesign** [comment]
There is no OpenCart 4.3.2 !

**Comment by imbarazz** [comment]
> There is no OpenCart 4.3.2 !

fixed ;)
