### ISSUE TITLE
Is it possible to display only 2 languages and currencies in multistore setup/frontend?

### ISSUE THREAD

**Issue by skullerud2280** [opencart/opencart#14126]
Hello Opencart Experts,

I am using OC 3.0.4.0

I'm trying to set up multistore, and have some questions/need your help. 

I have set up multistore with subfolders e.g. 
http:// maindomain.com
http:// maindomain.com/dk/ (Danmark)
http:// maindomain.com/de/ (German)
http:// maindomain.com/sp/ (Spain)
and selected default language and currency in admin for these, so when customers use these urls they will land on right site.

I have installed languages such as danish, german, french, spanish, swedish etc. and currencies i need in admin area. All these languags and currencies are also visible in the front end in all multistores. 

I wonder:

1- Is it possible to display only 2 languages ​​and 1-2 currencies in each multistore frontend? Like:
http:// maindomain.com/dk/ (Denmark) shows only danish currency + usd and danish and english languages ​​only?

2- is it possible to hide all other countries in the dropdown and keep only 1 country  like
http:// maindomain.com/dk/ (Denmark) have only Denmark in country dropdown list for new customer registeration form, edit shipping address, guest checkout etc. so no body can choose another country?

If i disable other countries i admin than they will not appear in other multistores. 

If possible, please let me know what to change in which file så i can try. 

I hope to hear from you experts. 

I appriciate all help/tips from comunity.

Best regards.

**Comment by GeekoDev** [comment]
This is not possible in default opencart, you would need extra module for that.

Such questions are better to ask on https://forum.opencart.com/ here it's specifically for reporting bugs to help development.

**Comment by danielkerr** [comment]
it is poossibgle!. u just set a default store language for each store and modifiy the template to remove the language selection

**Comment by skullerud2280** [comment]
Thank you for closing this issue but this was not what i asked for. I know i can set a default language for each store and swith off "language selection" in frontend. But this is not what i need, i want to let customers choose between 2 languges (1 local languge + english). i.e. arabic countries can choose between arabic and english, customers from Denmark can choose danish language + english) and so on.

Best regards

**Comment by skullerud2280** [comment]
> This is not possible in default opencart, you would need extra module for that.
> 
> Such questions are better to ask on https://forum.opencart.com/ here it's specifically for reporting bugs to help development.

Hello dear GeekoDev,
Thank you for your tips, i am new to use Opencart and have registered me newly on Opencart forum. I am not allowed to post anything there yet :(

I will be thankfull to you if you or som one else can do this for me. 

Best regards

**Comment by GeekoDev** [comment]
To set default language you can choose it into System > Settings > Localisation, but it would require to manually edit the template to disable language selection, sorry cannot help you further here, in forum check if you don't have email to validate, else try to contact opencart team so they can validate your forum account.
