### ISSUE TITLE
Opencart demo website not working

### ISSUE THREAD

**Issue by prosenjeet123** [opencart/opencart#14137]
**What version of OpenCart are you reporting this for?**
3.0.3.9

**Describe the bug**
The admin demo is not working. I have attached a video as evidence and have tested it on multiple devices and browsers. Please note that this issue has been present for the past week, and no one has raised any concerns or provided fixes until now. I am bringing this to attention to ensure it is addressed as soon as possible. This leaves a negative impression on OpenCart users, especially new ones.

**To Reproduce**
1. Go to 'https://demo.opencart.com/admin/'
2. Click on 'login'
3. Open debugger to check the 'Javscript Error''

**Expected behavior**
This is supposed to work without any issues

**Screenshots / Screen recordings**
https://jmp.sh/s/0Kyr4g0Pc3NqgL1ENh9u

**Server / Test environment (please complete the following information):**
NA

**Additional context**
NA

**Comment by danielkerr** [comment]
i put cloudflare settings to high.

**Comment by tavronics** [comment]
Opencart demo website not working

![Image](https://github.com/user-attachments/assets/7c83e6d8-a4d6-4f9f-a2d8-0b69b4c41dd0)

**Comment by tavronics** [comment]
Opencart demo website not working

![Image](https://github.com/user-attachments/assets/d139f5b0-dc08-472a-801b-a8512331a4e4)
