### ISSUE TITLE
{master branch} admin order status update getting Error: QUIT not accepted from server!

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#14139]
admin order status update getting the below errors.
2024-09-25 18:57:52 - 0:  Error: QUIT not accepted from server!
File: /system/library/mail/smtp.php
Line: 296

**Comment by Max199068** [comment]
did you get any reason for this problem ? i have a problem same as yours.

**Comment by chongshengdz** [comment]
there is a big bug with the latest smtp commit.
when a customer places an order, the new-order emails will flood to store owner and never send to the customer.

**Comment by chongshengdz** [comment]
> did you get any reason for this problem ? i have a problem same as yours.

install a brand new demo, replace the old oc_event table with the new one.
or install a brand new demo, compare your admin events one by one with your site.

**Comment by chongshengdz** [comment]
admin=>Navigation=>extensions=>Events in the table may have changed since your last updates, so you need to compare one by one. 
if you have only 43 events, then you can simply replace old oc_event with the new one.

**Comment by chongshengdz** [comment]
for master branch, open /system/library/mail/smtp.php
delete the below two lines on line 254 and 256.
			fwrite($handle, 'QUIT' . "\r\n");

			$this->handleReply($handle, 221, 'Error: QUIT not accepted from server!');
for other version, search 'QUIT' and delete the matched similar two lines.
