### ISSUE TITLE
Using several extension modules on a single page causes SeoUrl to not display correct url when using SEO URLs

### ISSUE THREAD

**Issue by great-shop** [opencart/opencart#14146]
**What version of OpenCart are you reporting this for?**
4.1.0.0

**Describe the bug**
Using several extension modules on a single page causes SeoUrl to not display correct url when using SEO URLs.

**To Reproduce**
1. Add Category module and Featured module to a Layout.
2. Visit the layout page

**Expected behavior**
Category links in Category should show up as yourpage.com/catalog/category-name, product links in Featured module should show up as yourpage.com/product/product-name.

**Actual result**
Category links in Category show up as yourpage.com/catalog/category-name, product links in Featured module show up as yourpage.com/cataolog/product-name. I.e. catalog route data persists from Category module to Featured module.

**Comment by danielkerr** [comment]
already fixed
