### ISSUE TITLE
Product filter group not show in admin on categories and products

### ISSUE THREAD

**Issue by great-shop** [opencart/opencart#14165]
**What version of OpenCart are you reporting this for?**
4.1.0.0

**Describe the bug**
Line 897 of admin/controller/catalog/product.php expects $filter_info['group']. $filter_info is set via $this->model_catalog_filter->getFilter($filter_id); This function does not return a 'group' property.

Same is on Line 327 of admin/controller/catalog/category.php

**Comment by prabhat-webkul** [comment]
https://github.com/opencart/opencart/pull/14168 This will fix both product and category
