### ISSUE TITLE
Documentation page says "payment methods are available with an OpenCart installation"; they aren't

### ISSUE THREAD

**Issue by mehov** [opencart/opencart#14167]
The following documentation page is not accurate and needs to be updated:

> The OpenCart package offers a variety of payment methods, from bank transfers to online payment gateways. The following core payment methods are available with an OpenCart installation:

https://docs.opencart.com/en-gb/extension/payment/

**Comment by danielkerr** [comment]
but the ones that are are available on the opencart mareketplace
