### ISSUE TITLE
Customer data not loading into forms

### ISSUE THREAD

**Issue by siteadvice** [opencart/opencart#14185]
**What version of OpenCart are you reporting this for?**
4.1.0.0

**Describe the bug**
When loading the customer edit page in the dashboard (route=customer/customer.form) or on the store (route=account/edit) only the basic required data appears in the form (names, email, telephone, customer group, status) but any custom fields are not populated.

**To Reproduce**
On a site with customer contact form custom fields, go to Customers > Customers and select a customer. 

**Expected behavior**
Custom fields such as "Postcode" should be populated with data input by the customer when registering.
The data is there in the custom_field column of the customer table. And if you re-input it manually into the form, the table is updated successfully. But the form does not populate when refreshing.
No errors in the error_log or in the browser console.
Example from custom_field column:
{"29":"","33":"0000 0000000","4":"10 Downing Street","30":"","31":"London","32":"SW1A 2AA","5":"This is a test now!!!!","2":"4","24":"42"}

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - WHM/cPanel, CentOS v7.9.2009 STANDARD virtuozzo
 - PHP version 8.3
 - Litespeed web server v6.3.1
 - tested in Firefox/Chrome

**Additional context**

**Comment by prabhat-webkul** [comment]
Yes, custom field values are saved into DB but not displayed to UI
 
PR #14196 will fix it

**Comment by siteadvice** [comment]
Thanks! That's now working.
