### ISSUE TITLE
Class "Opencart\System\Library\Url" not found

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#14197]
**What version of OpenCart are you reporting this for?**
4.1
**Describe the bug**
A clear and concise description of what the bug is
Class "Opencart\System\Library\Url" not found: in ../system/framework.php on line 175
What section does it affect?
both admin and catalog access
**To Reproduce**
1. Go to 'https://wenbo.world'

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by chongshengdz** [comment]
which opencart version  are you using?

**Comment by cgcmart** [comment]
4.1.0.0

**Comment by chongshengdz** [comment]
the latest master branch is quite stable.
just check if System\Library\Url.php existed?

**Comment by chongshengdz** [comment]
the latest master branch is quite stable.
just check if your System\Library\Url.php existed?

**Comment by cgcmart** [comment]
Thank your message.

**Comment by chongshengdz** [comment]
there is one big bug with the smtp on opencart 4+ and 3+
you need to comment out two lines if you are using them for production site.
you can take a look at the below pull request.
https://github.com/opencart/opencart/pull/14189

**Comment by cgcmart** [comment]
Thank you for your contribution.
Currently I can work on admin. Front store does not work: Error: Could not load model Opencart\Catalog\Model\Extension\Opencart\Total\Voucher! in ../system/engine/loader.php on line 171

I am waiting for next comment on opencart master, update, release, paypal extension, etc.

**Comment by chongshengdz** [comment]
this error is due to Voucher was removed and you are upgrading from an old version.
just run below query from your database and delete voucher related tables.
delete from oc_extension where code like "%voucher%";
