### ISSUE TITLE
Cannot change language in admin

### ISSUE THREAD

**Issue by zoigecyb** [opencart/opencart#14198]
I have a few languages in OC. but if i change in settings nothing happens. OC admin load only en-gb.

so i added function 
```
    public function setCode ($code='') {
        if ($code) {
            $this->code=$code;
        }

    }
``` to systel/library/language.php

and changed admin/controller/startup/language.php:
```
public function index(): void {
		if (isset($this->request->cookie['language'])) {
			$code = (string)$this->request->cookie['language'];

		} else {
			$code = $this->config->get('language_code');
		}
 
		$this->load->model('localisation/language');
	..........
			// Set the config language_id key
			$this->config->set('config_language_id', $language_info['language_id']);
			$this->config->set('config_language_admin', $language_info['code']);

            $this->language->setCode($language_info['code']); // ----- this line
		

	$this->language->load('default');
		}
	}
```

**Comment by danielkerr** [comment]
works iin the master.
