### ISSUE TITLE
Extension translations are not loaded when installed through the extension installer

### ISSUE THREAD

**Issue by zsoltoroszlany82** [opencart/opencart#14199]
**What version of OpenCart are you reporting this for?**  
OpenCart 4

**Describe the bug**  
Translations for extensions are not loaded if the language file is installed through the extension installer.

**To Reproduce**  
1. Install the language through the extension installer. The language files are installed in the following directories:
   - `/extension/<language_folder_name>/admin`
   - `/extension/<language_folder_name>/catalog`
   - `/extension/<language_folder_name>/extension`
   - `/extension/<language_folder_name>/install`

**Expected behavior**  
Translations should be visible on both the admin and front-end pages.

**Screenshots / Screen recordings**  
Screenshot when the translations **are not directly copied** to the `/extension/opencart/admin/language/` folder:  
![image](https://github.com/user-attachments/assets/ab43c676-421c-4283-816e-bbdee3787987)

Screenshot when the translations **are copied** to the `/extension/opencart/admin/language/` folder:  
![image](https://github.com/user-attachments/assets/209e5a01-4eac-4d33-ae00-22b9ac322f73)

**Server / Test environment (please complete the following information):**  
- Operating system: Linux php83 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64  
- PHP version: 8.3.10  
- Apache version: 20120211  
- Browser(s) tested with: Firefox 131.0.3 (x64)  

**Additional context**  
N/A

**Comment by zsoltoroszlany82** [comment]
I've identified the correct directory structure for automatic installation. Below is an example layout for uploading language files directly:

```
admin\
admin\language\hu-hu\catalog\
...
catalog\
catalog\language\hu-hu\account\
...
extension\
extension\opencart\admin\language\hu-hu\captcha\
extension\opencart\admin\language\hu-hu\payment\
...
extension\opencart\catalog\language\hu-hu\captcha\
extension\opencart\catalog\language\hu-hu\payment\
...
install\
install.json
```

When installing through the extension installer, the structure is slightly different:

```
admin\
admin\language\hu-hu\catalog\
...
admin\language\hu-hu\extension\opencart\captcha\
admin\language\hu-hu\extension\opencart\payment\
...
catalog\
catalog\language\hu-hu\account\
...
catalog\language\hu-hu\extension\opencart\captcha\
catalog\language\hu-hu\extension\opencart\payment\
...
```

First it was a little bit strange why this directory structure was choosen, but it works now properly the extension translations are display properly both frontend and backed.

**Comment by danielkerr** [comment]
ok great. the directories are like virtual directories.
