### ISSUE TITLE
[master branch] Wrong link for login page

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#14202]
**What version of OpenCart are you reporting this for?**
master brach 4.1.0.0

**Describe the bug**
On the checkout page, clicking on the link at 'If you already have an account with us, please login at the **login page**.' always results in a 403 Forbidden response.

**Expected behavior**
Clicking on the **login page** should lead to the account/login page.

**Screenshots / Screen recordings**
![Screenshot_2024-10-30_15-49-57](https://github.com/user-attachments/assets/f0801a8b-3854-4765-93dd-d32d105cf53d)

**Comment by danielkerr** [comment]
works for me. maybe cloudflare.

**Comment by mhcwebdesign** [comment]
This is not a cloudflare issue! In fact, we are not using cloudflare at all. See our test site at https://www.mhccorp.com/oc4100

**Comment by GeekoDev** [comment]
Seems caused by security rule on your server that disallow access when some urls are passed as parameter, check in your apache logs to see if you have more details about the forbidden access.

**Comment by mhcwebdesign** [comment]
@GeekoDev : You are right, the Apache error log has indeed this entry:

`AH: Unsafe URL with %3f URL rewritten without UnsafeAllow3F, referer: https://127.0.0.1/juergen/opencart-4-1-0-0/en-gb?route=checkout/checkout`

So what's the solution? This also happens on a remote server with an Apache 2.4 server on Linux, hosted by webhostinguk.net . I this will happen for a quite a few servers?

**Comment by GeekoDev** [comment]
Try to change in .htaccess:
RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]
by:
RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA,UnsafeAllow3F]

**Comment by mhcwebdesign** [comment]
I think using the UnsafeAllow3F tag in the .htaccess is not a final solution, and probably will only work for certain vesions of the Apache server.

The following solution appears to address this issue:

Change the system/library/url.php, as follows:

```
	public function link(string $route, $args = '', bool $js = false): string {
		$url = $this->url . 'index.php?route=' . $route;

		if ($args) {
			if (is_array($args)) {
				$url .= '&' . http_build_query($args);
			} else {
				$url .= '&' . trim($args, '&');
			}
		}

		foreach ($this->rewrite as $rewrite) {
			$url = $rewrite->rewrite($url);
		}

		// see https://stackoverflow.com/questions/78729429/403-forbidden-when-url-contains-get-with-encoded-question-mark-unsafeallow3f
		$url = str_replace('%3F', '?', $url);

		if (!$js) {
			return str_replace('&', '&amp;', $url);
		} else {
			return $url;
		}
	}

```

For a more detailed discussion on this, see https://stackoverflow.com/questions/78729429/403-forbidden-when-url-contains-get-with-encoded-question-mark-unsafeallow3f

**Comment by mhcwebdesign** [comment]
@danielkerr : I reopened this issue, because it needs to be addressed, there are many websites out there running newer Apache 2.4.x where it's relevant!

**Comment by osworx** [comment]
Quite good described here: https://launix.de/launix/broken-websites-after-apache-update-unsafeallow3f-a-game-you-cannot-win/

**Comment by mhcwebdesign** [comment]
> @mhcwebdesign Will there be other minor issues with %3F in URLs? For example a search containing a question mark?
> 
> https://github.com/opencart/opencart/blob/815476c448894becbfb03b5a81dce1cec85b11e6/upload/catalog/view/template/product/search.twig#L115

Good question. I just ran a quick test, and it seems to be fine for the product search, tried it with these search expressions:
`Apple?limit=10`
`Apple%3Flimit=10`

**Comment by ADDCreative** [comment]
@mhcwebdesign Thanks. I understand why now. Apache will only block rewritten URls with %3F in. Since the first part of the search URLs are hard coded with index.php in the JavaScript they will never be rewritten.

**Comment by mavelo-llc** [comment]
> Change the system/library/url.php, as follows:
> ```
> 		$url = str_replace('%3F', '?', $url);
> 
> 		if (!$js) {
> ```

Solved the problem for us in latest release. Was unaware of the %3F problem before today. Nice catch!
