### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#14205]
**What version of OpenCart are you reporting this for?**
Master
**Describe the bug**
A clear and concise description of what the bug is
no error log or display error
What section does it affect?
header search bar not response after input words
**To Reproduce**
1. Go to 'https://wenbo.world/en-gb/home'

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by chongshengdz** [comment]
this was fixed  on the latest master branch
https://github.com/opencart/opencart/commit/b6a73bd73ae3ae42107e75bf66a35c1e0da5be9f

**Comment by cgcmart** [comment]
I checked my files that were updated to the latest.

**Comment by mhcwebdesign** [comment]
Could have caused by the recent changes to the common.js
