### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by ZateLabClients** [opencart/opencart#14208]
**version of OpenCart**
Latest Master branch

**Describe the bug**
Search bar on opencart header is not working

**Screenshots / Screen recordings**
![image](https://github.com/user-attachments/assets/16d8a0ba-084b-4617-813e-dd02e463c5e0)

**Comment by mhcwebdesign** [comment]
Already reported here: https://github.com/opencart/opencart/issues/14205
