### ISSUE TITLE
[master branch] Use only enabled custom fields for customer address editing

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#14204]
**What version of OpenCart are you reporting this for?**
master branch (upcoming 4.1.0.0)

**Describe the bug**
In the admin backend, when editing a customer's address, it currently show all the disabled custom fields, which is wrong!

**Suggested fix**
In file admin/controller/customer/address.php, replace lines 154 to 158 as follows:

old:
```
		$filter_data = [
			'filter_location' => 'address',
			'sort'            => 'cf.sort_order',
			'order'           => 'ASC'
		];
```
new:
```
		$filter_data = [
			'filter_location' => 'address',
			'filter_status'   => '1',
			'sort'            => 'cf.sort_order',
			'order'           => 'ASC'
		];
```

**Server / Test environment (please complete the following information):**
 - Operating system: Linux
 - PHP version: 8.3
 - Apache version: 2.4
 - Browser(s) tested with: Firefox
 - Version: 132.0 (64-bit)

**Comment by danielkerr** [comment]
fine
