### ISSUE TITLE
Exception: Error: Could not call controller catalog/product! in ../system/engine/loader.php:333

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#14207]
https://github.com/opencart/opencart/blame/8c813137b0f3e118cde48bdbe064b51a815c4693/upload/system/engine/loader.php#L333

Exception: Error: Could not call controller catalog/product! in ../system/engine/loader.php:333
Stack trace: 
#0 ../system/engine/loader.php(78): Opencart\System\Engine\Loader->execute() 
#1 ../admin/controller/catalog/product.php(151): Opencart\System\Engine\Loader->controller()
#2 ../system/engine/loader.php(331): Opencart\Admin\Controller\Catalog\Product->index() 
#3 ../system/engine/action.php(56): Opencart\System\Engine\Loader->execute() 
#4 ../system/framework.php(240): Opencart\System\Engine\Action->execute() 
#5 ../admin/index.php(20): require_once('...') 
#6 {main}

**Comment by cgcmart** [comment]
OC master version, latest comments: "framework changes issue fixes", "update system/engine/loader.php
The error impacts: admin -> catalog -> categories -> category list
admin -> catalog -> products -> product list
admin -> catalog -> filters
admin -> catalog -> attributes
admin -> catalog -> options
admin -> catalog -> manufacturers
admin -> catalog -> downloads
admin -> catalog -> information

**Comment by mhcwebdesign** [comment]
Try this solution: https://github.com/opencart/opencart/issues/14209#issuecomment-2462655029

**Comment by cgcmart** [comment]
as completed.
