### ISSUE TITLE
Build and test for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [opencart/opencart#14220]
## Description  

For aarch64 platform, I have built "OpenCart " from source.  

## Steps   

Following "STEPS (https://docs.opencart.com/en-gb/installation/)" were used for building and installing OpenCart 
 
```
wget https://github.com/opencart/opencart/archive/refs/tags/3.0.3.8.tar.gz 
tar xvf 3.0.4.0.tar.gz 
sudo mv opencart-3.0.3.8/upload /var/www/html/opencart  
sudo chown -R www-data:www-data /var/www/html/opencart 
sudo chmod -R 755 /var/www/html/opencart 
```

## Outcome  

To validate the OpenCart: 

Create a Database and user by Log into MySQL. 

Access OpenCart in your web browser: Open your browser and go to http://your_server_ip/opencart. 
 
All this information was also added to Software Ecosystem Dashboard for Arm (https://www.arm.com/developer-hub/ecosystem-dashboard/).

**Comment by danielkerr** [comment]
Cheers. Not sure what u want me to do with this information

**Comment by danielkerr** [comment]
u can do a pull request to updater the documentation here 

https://github.com/opencart/opencart.github.io
