### ISSUE TITLE
Request for Consistent Commenting Guidelines

### ISSUE THREAD

**Issue by MDorn03** [opencart/opencart#14229]
Currently there are no guidelines or standards for code comments in the Coding Standards page for this project. This can make it difficult for a new user or developer to understand the code, as well as leading to inconsistent documentation across files. 

In some files, such as upload/cron.php and upload/system/framework.php, there are many comments which are only a single word, which don’t really impart information beyond which variable is being changed or accessed. Other files, like upload/system/library/response.php are very thoroughly commented. 

Introducing a standardization for comments could improve communication and understanding of the code. It could also help future contributors by giving them a guideline so they don’t have to come up with their own. Would it be possible to implement commenting guidelines? This could mean an original standard, or an existing one like Javadoc or docstrings.
Thank you for your consideration!

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/wiki/Coding-Standards
