### ISSUE TITLE
Extensions >Installer, Undefined array key "link"

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#14235]
**What version of OpenCart are you reporting this for?**
4.0.2.3

**Describe the bug**
Warning: Undefined array key "link" in /var/www/opencart.com/web/admin/controller/marketplace/installer.php on line 117Opencart\System\Library\DB::escape(): Argument #1 ($value) must be of type string, null given, called in /var/www/opencart.com/web/admin/model/setting/extension.php on line 86: in /var/www/opencart.com/web/system/library/db.php on line 58

**To Reproduce**
1. Go to https://demo.opencart.com/admin/
2. Login demo/demo
3. Extensions >Installer

**Comment by danielkerr** [comment]
i noticed it

**Comment by mhcwebdesign** [comment]
This is most likely caused by a faulty .ocmod.zip extension located in the DIR_STORAGE.'/marketplace'.

**Comment by danielkerr** [comment]
not sure how this nonse code got in there
