### ISSUE TITLE
This CKEditor 4.22.1 version is not secure. Consider upgrading to the latest one, 4.25.0-lts.

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#14234]
**What version of OpenCart are you reporting this for?**
4.0.2.3

**Describe the bug**
This CKEditor 4.22.1 version is not secure. Consider [upgrading to the latest one](https://ckeditor.com/ckeditor-4-support/), 4.25.0-lts.

**To Reproduce**
1. Go to Catalog >Product > Edit

![1](https://github.com/user-attachments/assets/99b5e05c-2b3f-4dbe-a0fb-d35720bffc84)

**Comment by mhcwebdesign** [comment]
Already been dealt with: https://github.com/opencart/opencart/issues/14032

**Comment by cgcmart** [comment]
`	config.versionCheck = false;`

It's not work anymore.
