### ISSUE TITLE
[4.1.x / 5.x] utf8mb4_unicode_ci vs utf8mb4_general_ci

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#14231]
According the discussion here: https://stackoverflow.com/a/766996/3450837
leads to my question if it would be not better to use **utf8mb4_unicode_ci** rather then the currently used **utf8mb4_general_ci**

As reference one entry:
https://github.com/opencart/opencart/blob/be2b786542dd6d8893ad35ddde3420c7281813c0/upload/system/helper/db_schema.php#L160

A quote from there (belongs here especially to German language):

> For example, the Unicode collation sorts "ß" like "ss", and "Œ" like "OE" as people using those characters would normally want, whereas utf8mb4_general_ci sorts them as single characters (presumably like "s" and "e" respectively).

And such makes a big difference when sorting is a matter ..

**Comment by nickpapoutsis** [comment]
I have always been using utf8mb4_unicode_ci because it's the only logical choice for not-exclusively-english stores.
There's a tiny performance penalty, afaik, but the compatibility and future-proofness of utf8mb4_unicode_ci more than make up for it.

**Comment by kanenas** [comment]
I wonder why **WordPress** is using `utf8mb4_unicode_520_ci`.

**Comment by stalker780** [comment]
`utf8mb4_unicode_520_ci` is the newer version of `utf8mb4_unicode_ci`.
It fixes polish Ł sorting.

**Comment by osworx** [comment]
> `utf8mb4_unicode_520_ci` is the newer version of `utf8mb4_unicode_ci`. It fixes polish Ł sorting.

Correct, but to use that, you need at least **MySQL 5.6** - lower versions do not support utf8mb4_unicode_520_ci.
@kanenas this is also the reason why some WP users do have troubles and need to convert back to utf8mb4_unicode_ci

In general, should be OpenCart support also 'older" MySQL version or not ?

**Comment by nickpapoutsis** [comment]
> In general, should be OpenCart support also 'older" MySQL version or not ?

In general, it shouldn't. New Opencart versions should be drawing lines and dictating minimum versions for PHP, SQL, etc.

But, in this case, `utf8mb4_unicode_520_ci` doesn't make any real difference and not even Polish sites will notice anything so `utf8mb4_unicode_ci` should be chosen as the default.

**Comment by danielkerr** [comment]
ok

**Comment by osworx** [comment]
thx Daniel
