### ISSUE TITLE
Call to a member function get() on a non-object in /home/.../public_html/.../admin/index.php on line 84

### ISSUE THREAD

**Issue by sairaj21** [opencart/opencart#1424]
Hi,

 i am trying to fix error my one of my website. So that i am using dump in another my server but when i config it shows Fatal error: Call to a member function get() on a non-object in /home/.../public_html/../admin/index.php on line 84

in admin index.php file i have this code

if ($config->get('config_error_display')) {
        echo '<b>' . $error . '</b>: ' . $errstr . ' in <b>' . $errfile . '</b> on line <b>' . $errline . '</b>';
    }

**Comment by NewLifeMan** [comment]
Problem with permissions to log file     /system/logs/error.log
