### ISSUE TITLE
Session Order_id is not updating

### ISSUE THREAD

**Issue by plisdeveloper** [opencart/opencart#14251]
**What version of OpenCart are you reporting this for?**

All version of Opencart are affected

**Describe the bug**
I am developing a third party payment extension, after the Pay button, the customer is taken to our gateway payment page. The problem is that if the user closes the page or clicks the Back button in the browser, he will be returned to the cart and no matter what he does with the cart (add items to it or click pay again) - his Order_id will not change, although it is actually another order. As a temporary solution, I update the order_id manually with `unset($this->session->data['order_id']);` before redirecting to the payment system page, but this hack will not work with whitelabel solution because in this case when the page is refreshed the client will see a white box as it takes the order_id from the session to show the invoice to the client. As a solution - we can update the order_id every time the customer clicks on the Checkout button, then we will know for sure that the customer wants to place a new order.

**To Reproduce**
1. Add the items to the cart
2. Go to the checkout page
3. Choose 3rd party payment provider
4. Click Pay button
5. Redirect to the payment provider page
6. Leave the invoice page without doing anything
7. Return to shop and proceed to checkout again

**Expected behavior**
A new order_id is given everytime user goes to the checkout page

**Server / Test environment (please complete the following information):**
 - Web server
 - Linux
 - PHP 8.3
 - Nginx
 - Chrome
 - Latest

**Comment by danielkerr** [comment]
its designed so the order id does not change until after an order status has been assigned.
