### ISSUE TITLE
The promotion style of the Step 4 page is broken.

### ISSUE THREAD

**Issue by retrina** [opencart/opencart#14260]
**What version of OpenCart are you reporting this for?**
4.1.0.0

When you open console on install/step_4 page, there are several errors:

GET http://localhost/opencart-website/public_html/application/view/stylesheet/install.css net::ERR_ABORTED 404 
GET http://localhost/opencart-website/public_html/application/view/javascript/fontawesome/css/font-awesome.min.css net::ERR_ABORTED 404 
GET http://localhost/cdn-cgi/challenge-platform/scripts/jsd/main.js net::ERR_ABORTED 404

These files are called via the following URL in install/promotion.php:
curl_setopt($curl, CURLOPT_URL, 'https://www.opencart.com/index.php?route=api/install');

"http://localhost/opencart-website/public_html/application/view/stylesheet/install.css" must changed to 
"https://www.opencart.com/application/view/stylesheet/install.css" and other links too

@danielkerr

**Comment by danielkerr** [comment]
https://community.cloudflare.com/t/report-of-deprecated-api-usage-in-cloudflares-auto-generated-script/578200/4

no issue because its the installer that will be deleted. its just cloudflare protecting the opencart.com.
