### ISSUE TITLE
    public function getTotalCategoriesByCategoryId(int $product_id, int $category_id): int  $product_id, not use

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#14266]
https://github.com/opencart/opencart/blob/af2e9d7d8bb974daf631fbecf6c673a2e57bcb66/upload/catalog/model/catalog/product.php#L389C49-L389C65

**Comment by danielkerr** [comment]
iots used by coupons

**Comment by eturerer** [comment]
public function getTotalCategoriesByCategoryId(int $product_id, int $category_id): int {
		$query = $this->db->query("SELECT COUNT(*) AS `total` FROM `" . DB_PREFIX . "product_to_category` WHERE `category_id` = '" . (int)$category_id . "'");

		return $query->row['total'];
}
 
$product_id not use

**Comment by danielkerr** [comment]
if ($coupon_product_data || $coupon_category_data) {
				$this->load->model('catalog/product');

				foreach ($this->cart->getProducts() as $product) {
					if (in_array($product['product_id'], $coupon_product_data)) {
						$product_data[] = $product['product_id'];

						continue;
					}

					foreach ($coupon_category_data as $category_id) {
						$product_total = $this->model_catalog_product->getTotalCategoriesByCategoryId($product['product_id'], $category_id);

						if ($product_total) {
							$product_data[] = $product['product_id'];

							continue;
						}
					}
				}

**Comment by TheCartpenter** [comment]
> return $query->row['total'];

That line also originates from a previous OC 4 version.
