### ISSUE TITLE
Product review: Could not load product model

### ISSUE THREAD

**Issue by zsoltoroszlany82** [opencart/opencart#14264]
**What version of OpenCart are you reporting this for?**
OpenCart 4.0.2.3

**Describe the bug**
In the catalog/controller/product/review.php file:

```
$this->load->model('product/product');
$product_info = $this->model_product_product->getProduct($product_id);
```

should be:

```
$this->load->model('catalog/product');
$product_info = $this->model_catalog_product->getProduct($product_id);
```

**To Reproduce**
1. Go to any product page
2. Click on 'Reviews' then 'Continue'
4. Server response is `Error: Could not load model Opencart\Catalog\Model\Product\Product!: in xxxxxxxx\opencart4\system\engine\loader.php on line 177`

**Expected behavior**
The server should return JSON e.g.: `{"error":{"warning":"Warning: Review token invalid!","text":"Review Text must be between 25 and 1000 characters!"}}`

**Screenshots / Screen recordings**
n/a

**Server / Test environment (please complete the following information):**
 - Local development
 - Operating system: Windows 10
 - PHP version: 8.2.12
 - Apache version: 2.0
 - Browser(s) tested with Firefox
 - Version 133.0.3

**Additional context**
n/a

**Comment by danielkerr** [comment]
this code is already fixed on master
