### ISSUE TITLE
Continue Button does not appear on CheckOut page when address is loaded from stored addres

### ISSUE THREAD

**Issue by DaveRiba** [opencart/opencart#14261]
**What version of OpenCart are you reporting this for?**
4.0.2.2

**Describe the bug**
Customers with a saved address do not see the Continue button

What section does it affect?
checkout/checkout

**To Reproduce**
Enter an order into the Shopping Cart
Go to checkout
Continue Button is there.
Change to I want to use an existing address
Continue button is gone
Change to I want to use a new address
Continue button is there.
Change to I want to use an existing address
No checkout button

**Expected behavior**
Continue button should always be there

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?  Deployed harbor-sales.com
 - Operating system  hosted
 - PHP version  hosted
 - Apache version  unknown
 - Browser(s) tested with [e.g. chrome, safari - if applicable]  Firefox / Chrome

**Additional context**

**Comment by mhcwebdesign** [comment]
Use OC 4.0.2.3 or later. Also, not a bug, it's how it is designed.
