### ISSUE TITLE
admin order edit does not save comment

### ISSUE THREAD

**Issue by vsadoug** [opencart/opencart#14277]
**What version of OpenCart are you reporting this for?**
4.0.2.3

**Describe the bug**
In admin side, viewing an order, adding a comment and saving it, it confirms it modified the order but does not save the comment. 

**To Reproduce**
1. Edit any order
2. click comment button to add comment, save. 
3. exit order.
4. view order again. 

**Expected behavior**
The comment should appear. 

**Server / Test environment (please complete the following information):**
 - alma linux, latest.
 - PHP version 8.2
 - Apache version latest
 - Firefox - latest

**Additional context**

**Comment by chongshengdz** [comment]
https://github.com/opencart/opencart/pull/14189/commits/e703e595c3b111dc671aa1f0da1c832e7e32a95f
it may be the QUIT's problem, check the above pull request and comment out these two lines and try again.

**Comment by ADDCreative** [comment]
@vsadoug You have to them click Confirm.

**Comment by vsadoug** [comment]
correction to this, confirm does work but it will NOT work if the items are now out of stock It will give an error about the items and not save the comment.

**Comment by ADDCreative** [comment]
@vsadoug That's a different issue. See https://github.com/opencart/opencart/issues/8997.
