### ISSUE TITLE
 catalog/model/product/product.php issue: error in sql syntax on line 591

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#14283]
https://github.com/opencart/opencart/blob/2dfd602d3c0201176f725f7a41eae93471bcbb96/upload/catalog/model/catalog/product.php#L591

**Comment by danielkerr** [comment]
needs to highlight exactly which character

**Comment by cgcmart** [comment]
it looks single quote, at line 16 but can't figure out what line 16 refers to.
[error-1064-syntax.txt](https://github.com/user-attachments/files/18223154/error-1064-syntax.txt)

**Comment by retrina** [comment]
The query in your text file is different from the master code.
"DISTINCT" is not exist on line 591.

**Comment by cgcmart** [comment]
The same issue and error.
