### ISSUE TITLE
Default Fedex Module ERROR

### ISSUE THREAD

**Issue by yajuvendra1990** [opencart/opencart#1469]
Hi,
Opencart team
I'm using Opencart vs 1.5.6.1 and the Default Fedex module of opencart doesn't display any shipping options during checkout, it simply displays ERROR.
e.g.
Please select the preferred shipping method to use on this order.

Flat Rate
Flat Shipping Rate  $50.00
Fedex
ERROR

I have verified that my key, password, account and meter number are correct. I am using a production account, not a testing account. please help me for resolve this issue

thanks & regards
yajuvendra

**Comment by jalalm07** [comment]
Hi yajuvendra,

i am also have the same issue. can u please tell me if found the fix for this issue?

**Comment by yajuvendra1990** [comment]
I am sorry, I had this issue 3 years ago and I do not remember how to fix
this, I think you have to cross check your detail that you enter in FedEx
module like meter no. Account ID etc.
