### ISSUE TITLE
Opencart 1.5.4 SEO keywords for categories not working properly.

### ISSUE THREAD

**Issue by shadyyx** [opencart/opencart#155]
If I want to use SEO features in OpenCart and set SEO keyword for products, categories, information etc., I am facing this problem with categories SEO keywords:

Imagine You have a big category tree where more main categories could have sub-categories of the same name as in another main category. This could be like Fruit  -> Yellow with products like  Bananas, Lemon, ... and Vegetable -> Yellow with products like Peppers, Tomatos, Sweet melon, ... Here we would normally set the SEO keyword for both Yellow sub-categories the same - "yellow".

This leads to two entries in "url_alias" table - both having "keyword" column containing "yellow" but "query" column containing (logically) two entries, e.g. "category_id=2" and "category_id=4".

Now if I want to display the products of the category Fruit -> Yellow - it worsk fine. But if I want to display the products of category Vegetable -> Yellow - wth - the products of Fruit -> Yellow are displayed...

The only now working workaround for this is to name the SEO keyword differently, like "yellow-vegetable" and "yellow-fruit", but this will lead to not very nice URL like "/vegetable/yellow-vegetable".

I think better solution could be implemented right within OpenCart core and store the queries like "category_id=1_2" for the keyword "yellow" that is under the category "fruit" and "category_id=3_4" for category "yellow" under "vegetable". Since the OpenCart knows what category is just displayed and hence know it's ID after requesting the "/vegetable/yellow" keyword the query for "category_id=3_4" could be identified therefore the products of correct category ID 4 would be displayed.

Or do You have better solution for SEO features?

**Comment by hayden-t** [comment]
this doesnt have to be a problem there is no need for categories of different paths to not have unique keyword !!
