### ISSUE TITLE
Modification does not work (as used with vqmod)

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#1561]
For example, I want to have 2 modifications in 1 file.
The orginal code:

``` php
foreach ($extensions as $extension) {
    $modules = $this->config->get($extension['code'] . '_module');

    if ($modules) {
        foreach ($modules as $module) {
            if ($module['layout_id'] == $layout_id && $module['position'] == 'column_right' && $module['status']) {
                $module_data[] = array(
                    'code'       => $extension['code'],
                    'setting'    => $module,
                    'sort_order' => $module['sort_order']
                );
            }
        }
    }
}
```

And I want just 2 simple lines added:

``` php
foreach ($extensions as $extension) {
    if( $a == $b ) { // HERE THE FIRST LINE
    $modules = $this->config->get($extension['code'] . '_module');

    if ($modules) {
        foreach ($modules as $module) {
            if ($module['layout_id'] == $layout_id && $module['position'] == 'column_right' && $module['status']) {
                $module_data[] = array(
                    'code'       => $extension['code'],
                    'setting'    => $module,
                    'sort_order' => $module['sort_order']
                );
            }
        }
    }
    } // HERE THE SECOND
}
```

A simple task, the xml should like this:

``` xml
<file path="PATH/TO/FILE">
    <operation>
        <search>
            <![CDATA[
                foreach ($extensions as $extension) {
            ]]>
        </search>
        <add position="after">
            <![CDATA[
        if( $a == $b ) { // HERE THE FIRST LINE
            ]]>
        </add>
    </operation>
    <operation>
        <search offset="3"> 
            <![CDATA[
                $sort_order = array();
            ]]>
        </search>
        <add position="before">
            <![CDATA[
        } // HERE THE SECOND
            ]]>
        </add>
    </operation>
</file>
```

The first line is added, the second not - no matter what I try, which offset I use, etc.
Could it be that only 1 (one) operation per file is allowed or what else is wrong?

**Comment by ricardo-gamboa** [comment]
How can i search multiple lines? im being trying to search without success:

<?xml version="1.0" encoding="utf-8"?>
<modification>
    <name>another email</name>
    <version>1.0</version>
    <author>me</author>
    <link>http://www.opencart.com</link>
    <code>another_email</code>
    <file path="catalog/model/checkout/order.php">
        <operation>
            <search trim="true"><![CDATA[
					foreach ($emails as $email) {
						if ($email && preg_match('/^[^\@]+@.*.[a-z]{2,15}$/i', $email)) {
							$mail->setTo($email);
							$mail->send();
						}
					}
				}
            ]]></search>
            <add position="replace"><![CDATA[
					foreach ($emails as $email) {
						if ($email && preg_match('/^[^\@]+@.*.[a-z]{2,15}$/i', $email)) {
							$mail->setTo($email);
							$mail->send();
						}
					}
				}
				// Send another email
            ]]></add>
        </operation>
    </file>
</modification>

**Comment by aldavara** [comment]
how can i use after in vqmode???!!!

**Comment by ricardo-gamboa** [comment]
@aldavara [here](https://github.com/vqmod/vqmod/wiki/Examples) are examples
