### ISSUE TITLE
SQL_MODE = 'MYSQL40'

### ISSUE THREAD

**Issue by PrivateAlpha** [opencart/opencart#1611]
/install/model/install.php contains a query

> $db->query("SET @@session.sql_mode = 'MYSQL40'");

that makes new installations hang on installation step 3.

Someone get rid of it please?

**Comment by miklcct** [comment]
This line causes error on MySQL 8.0. Please remove it.

**Comment by faizon101** [comment]
For those who are noobs (like me), what miklcct is saying (and it works) is:
navigate to your install.php file in the following directory
/install/model/install.php
 edit the file and delete exactly this text: 
> $db->query("SET @@session.sql_mode = 'MYSQL40'");

Thank you miklcct!!!

**Comment by hisatnam** [comment]
> 
> 
> This line causes error on MySQL 8.0. Please remove it.

Bro... Your suggestion saved me.... Thanks a Ton!
