### ISSUE TITLE
Captcha verification does not match the image with writing a review

### ISSUE THREAD

**Issue by webfryslan** [opencart/opencart#1713]
This happens when you make an error the first time (less then 25 chars in Your Review) The captcha picture is not refreshed, so you enter the old captcha code again which results in a " Warning: Verification code does not match the image!" Even when the code matches the picture

**Comment by Dekari** [comment]
Hello i experiencing the same issue

**Comment by milimar** [comment]
Mr @jamesallsup ready to help as always, but he made a simple question that need to be answered - he asked which version?

OK then, I just tested on my OC v. 2.0.3.1 and it works like expected. 

Now it is allowed to insert more that 10 characters and less that 300, so even if you insert less than 10, after the warning message you just insert more characters and the reCaptcha will refresh correctly.

**Comment by Dekari** [comment]
the issue is that never accepts the code,. even if i add correctly.

**Comment by milimar** [comment]
@Dekari , what is your OC version? 
As @jamesallsup said, this issue has been corrected. I use v. 2.0.3.1 and reCaptcha works as expected, even after the warning message for minimum characters.

**Comment by deepakcodeace** [comment]
@Dekari I saw the link posted by you in above conversation. But the link is working fine. So, how did you rectify it.?
