### ISSUE TITLE
url alias problem 

### ISSUE THREAD

**Issue by ghost** [opencart/opencart#1915]
in url alias every url saved with id , what will be problem if 2 category has same name? and 2 product has same name ?  which product or category will be shown ? 
for example top categorys can be `women` and `men`  and under men and women category can be as a sub category `shoe`  and `t-shirts`  it can be inserterd many times same name sub category for different top level categorys.  
how url alias will work ?

**Comment by hayden-t** [comment]
this doesnt have to be a problem there is no need for categories of different paths to not have unique keyword !!
