### ISSUE TITLE
Error on upgrade to 2.0.0.0

### ISSUE THREAD

**Issue by shiv0307** [opencart/opencart#1932]
I'm getting following error on upgrade. can you please help?

Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/goshoppeuk/public_html/system/startup.php on line 53

Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/goshoppeuk/public_html/system/startup.php on line 57

Fatal error: Class 'DB\stdClass' not found in /home/goshoppeuk/public_html/system/library/db/mysql.php on line 39

**Comment by awrelll** [comment]
what about the next step? after logging into admin interface i get this 

admin/controller/common/header.php on line 58Warning: implode(): Invalid arguments passed

**Comment by CoverUp** [comment]
This is not the place for this kind of issues, thus you will NOT find an answer here, please go to the support forum instead.

**Comment by nukepoof** [comment]
If DIR_MODIFICATION isn't getting added by the upgrade script then it should be included in the upgrade.txt
