### ISSUE TITLE
Log In with PayPal module not working

### ISSUE THREAD

**Issue by jorgansymes** [opencart/opencart#1952]
New / clean install of Opencart 2.0.0.0 (official release)
Configured Log In with PayPal module as described in this post: https://github.com/opencart/opencart/wiki/Log-In-with-PayPal
but can't get the module to function.
Added the Log In with PayPal to account and home pages and the button appears. When select the PayPal subpage briefly loads and then disappears and the users is then redirected to the "index.php?route=account/login" page.
The following error is displayed in the Error Log:
Log In with PayPal debug (ControllerModulePPLogin::login) - No code returned. Error: invalid_scope, Error Description: Client Validation Error: Invalid scope.
Have tired creating several PayPal REST apps under several Accounts in both Sandbox and Live but always get the same result. Have tried almost every option in Log In with PayPal section of REST app.
Have contacted PayPay but they said that the apps look good from their end.

**Comment by demarco** [comment]
I'm still experiencing this error on the latest version 2.0.2.0.

The PayPal window briefly shows up, closes, then redirects to the login page.

It doesn't seem to occur when I set everything up in Sandbox mode, using Sandbox Client ID and Secret. Are we supposed to be using the "Live" credentials though?

**Comment by david-wm** [comment]
Hi demarco.

Sandbox and Live use completely different Client ID and Secret. On developer.paypay.com when you're editing an app, there is a toggle in the top right corner.

Please note that Live credentials are only available for Premier or Business accounts.

Kind regards.

**Comment by Billchopher** [comment]
david-wm, did you find the solution to this problem?
I am having the same problems as you seem to have had. 
Did it start working for you after waiting a few hours?

**Comment by david-wm** [comment]
Hi Billchopher.

Are you still having problems with this? If you haven't already, please follow the instructions here: https://github.com/opencart/opencart/wiki/Log-In-with-PayPal

Kind regards.

**Comment by Billchopher** [comment]
Thanks for following up with me about this. When I posted my question, I 
had already followed the instructions you pointed me to, and triple 
checked everything.

I eventually got it to work as soon as I selected in PayPal, to request 
all the Account details in addition to the "personal Information" and 
"Address information".
So it is working beautifully now in sandbox mode on xampp local server.

**Comment by syslogic** [comment]
have set this up just recently and wanted to tell, that it might be useful if there would be separate fields for both, the sandbox and the live client_id/secret (just like at PayPal). there error which I keep getting is invalid_scope; guess the scopes need to be enabled/disabled within the application settings - for reference: https://developer.paypal.com/docs/integration/direct/identity/attributes/
