### ISSUE TITLE
Extension Installer Error

### ISSUE THREAD

**Issue by OpenCartAddons** [opencart/opencart#1961]
Still receiving this error when attempting to install an extension using the extension installer.

2014-10-09 19:29:34 - PHP Warning:  ftp_mkdir(): Can't create directory: File exists in /.../admin/controller/extension/installer.php on line 312

**Comment by sureshkumarks1** [comment]
hi, i am using opencart 2.0.3.x. i am facing this problem while uploading extensions.
SyntaxError : Unexpected token <
OK
<b> Warning </b>:ftp_chdir(): End in <b> [file location]\controller\extension\installer.php</b> on line 299

{"error":"Could not set root directory as"}

thanks in advance

**Comment by prabinshakya** [comment]
Hi, 
I am using opencart-2.0.3.1 and i am having problem on extension installer. Following error occurs : 
Directory containing files to be uploaded could not be found!. Can anyone help me ?? Thanx in advance

**Comment by zoqui** [comment]
Since this thread is quite old, I´m not sure if prabinshakya is still facing extension installation issues. But tip below might be useful for other users.
In a customer Godaddy shared hosted shop, I noticed that upload directory was not present under system directory, failing all extension installation I´ve tried. After manually creating the '/system/upload' directory i got no error anymore. I´ve installed the regular cPanel opencart 2.1.0.1 package.

**Comment by oooooh-button** [comment]
@zoqui 

Spot on! :+1: 

Thank you very much, problem solved.

**Comment by mariospast** [comment]
@zoqui i cant thank you enough.. i spent over 7 hours looking for the error and i just found your post.. 
problem solved... i only had to create an "upload" folder and voila...
thanks again :)

**Comment by zoqui** [comment]
glad to hear that @mariospast
success!

**Comment by dmz9** [comment]
maybe someone would find it useful.
i had incorrectly packed zip. extension zip should contain "upload" directory exactly in the root of archive, instead, i had one directory, named by module name, wrapping all the installation files (upload, mod file, xml etc).
repacking and reuploading with correct folder structure helped.
'wrong' > mod.zip => mod (folder) => upload (folder) + files
'correct' > mod.zip => upload (folder) + files

**Comment by yasir-lateef** [comment]
@dmz9 Absolutely Love it! Had the same issue and your solution worked like charm! Thanks a lot!
