### ISSUE TITLE
Cheque/Money Order and Bank Transfer payment options not being displayed on Checkout Page.

### ISSUE THREAD

**Issue by ghost** [opencart/opencart#1986]
I had enabled Free Checkout, Cash on Delivery, Cheque/Money Order and Bank Transfer payment options for checkout, however I could only see the Cash On Delivery option being displayed on the checkout page. 
When I disabled the COD option, I got the following message - " Warning: No Payment options are available. Please contact us for assistance!" 

Faced this issue with v2.0.0.0. 
This issue doesn't not exist with earlier v1.5.6.4.

Checked this on Aurora, Firefox, IE and Chrome.

**Comment by mhjn** [comment]
Hello sir , 
Even i am facing the same problme and i am checking out as a registered user .
