### ISSUE TITLE
Total calculation - excess cent(s)

### ISSUE THREAD

**Issue by meare** [opencart/opencart#1990]
The store have a lot of cheap accessories. VAT is set to 21%, so to get final product price of 4$ we should set product price to ~3.305785123967, which gets automatically rounded to 4 decimals — 3.3058. While in store front product price + tax is shown as 4.00$, it’s calculated as 4.000018$. When quantity is big enough (usually 100+ items) this gap (0.000018) could add excess cent(s) to total.
![screen shot 2014-10-12 at 15 21 16](https://cloud.githubusercontent.com/assets/3748248/4606266/e0bd9df2-5216-11e4-8c78-2c782f8241af.png)
![screen shot 2014-10-12 at 16 41 38](https://cloud.githubusercontent.com/assets/3748248/4606268/ee809eb2-5216-11e4-8a5f-6a4d84d07be2.png)
I think price + tax should be strictly rounded to currency decimal point before doing '\* quantity'.

**Comment by micrdy** [comment]
The total calculation should be done with with the price shown to the user, not the price within the system. This is a huge down for OC.
