### ISSUE TITLE
When copying existing product, both products are deleted from OpenCart and database

### ISSUE THREAD

**Issue by kimmetje** [opencart/opencart#1991]
Hello, I have uploaded the latest version of the master, am using a clean install of OpenCart 2.0 but when I try to copy a product, it simply erases the product I am trying to copy and doesn't copy. 

I have tried this on a Windows 8.1 machine in both IE11 and the latest version of Firefox as well...

**Comment by dknight0** [comment]
I can confirm this is indeed happening on ie 11..0.x on Win 8.1
firefox 34.0.5 is ok
chrome 39.0.x is ok
safari 5.1.x is ok

**Comment by BrianMcEyes** [comment]
that's right. there is a fault in the source text.

<button type="submit" form="form-product" formaction="http://t1.caribri.com/admin/index.php?route=catalog/product/copy&amp;token=6dc5475e0dfa93b57bbedbebdab3feae" data-toggle="tooltip" title="Copy" class="btn btn-default"><i class="fa fa-copy"></i></button>

the form Name 
form="form-product"  
of the copy button activates the $('#form-product').submit on delete button.

<button type="button" data-toggle="tooltip" title="Delete"  onclick="confirm('Are you sure?') ? $('#form-product').submit() : false;"><i class="fa fa-trash-o"></i></button>

**Comment by LiamMcArthur** [comment]
I'm experiencing the same issue in IE11. Brian, did you find a working fix?

**Comment by munirasim** [comment]
This issue exists as I tested with IE 11 and Opencart 2.0.1.1 and its not an issue in Chrome. I guess the issue is with underlying JavaScript of browsers and/or how they render the buttons. I'll look into it in detail. Apparently it has nothing to do with the logic of Opencart.

**Comment by nuke123** [comment]
It happens because the default action for the form is delete and IE11 does not support ```formaction```

```php
<form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-product">

<button type="submit" form="form-product" formaction="<?php echo $copy; ?>" data-toggle="tooltip" title="<?php echo $button_copy; ?>" class="btn btn-default"><i class="fa fa-copy"></i></button>
```

To fix change this to onclick
```php
<button type="button" onclick="$('#form-product').attr('action', '<?php echo $copy; ?>').submit()" data-toggle="tooltip" title="<?php echo $button_copy; ?>" class="btn btn-default"><i class="fa fa-copy"></i></button>
```

**Comment by munirasim** [comment]
@nuke123 You're right that issue is with Document Object Model (DOM) of IE 11. However, when I tested 'formaction' in the same browser using W3School example http://www.w3schools.com/tags/att_button_formaction.asp, it works perfectly to my surprise. May be a more investigation is needed here than making Jquery fix to this view. Could you please test the mentioned example in your browser?

**Comment by nuke123** [comment]
Maybe its the form="form-product" attribute with the button being outside of the form. Too busy to find another solution and its already using jquery for the delete.

**Comment by LiamMcArthur** [comment]
@nuke123 I've just applied your fix and it worked perfectly. Thanks! IE is always such a pain.

**Comment by munirasim** [comment]
So here is the real reason that why this issue exists in IE. The html 'button' does not support 'form' attribute. See http://www.w3schools.com/tags/att_button_form.asp
@danielkerr Please modify this view as well as Orders' admin view as suggested by @nuke123 using Jquery for the compatibility of Opencart with Internet Explorer. Thanks!

**Comment by jamesallsup** [comment]
Patch has now been applied for this as it was breaking in IE.

@nuke123 Thanks for the patch suggestion and others for confirming.

**Comment by smartey** [comment]
Well, I just downloaded latest version and it seems in Edge the issue is here as well. Select product -> click Copy and product simply disappears.... will similar fix like earlier mentioned fix this or is this a new issue tied to Edge??

**Comment by xvisual** [comment]
I too can confirm this issue is back, Right in the middle of copying the perfect product I had setup it wiped it out completely, thank god for constant backups. The code snippet above is still the same but the fix no longer works and the product will still get deleted when using edge/explorer.

**Comment by danielkerr** [comment]
@xvisual congratulations! now 3 people have said when i only needed 1

**Comment by danielkerr** [comment]
yes seems edges modern web standards are the same bull shit game that has cost me lots of time and money over the years because they do not fully implement the standards that every one else does! feels like 2006 again

**Comment by smartey** [comment]
Despite your feelings, I can see your frustration, thank you for reopening the issue! :)

**Comment by manisoft** [comment]
Please fix this issue on next version. Edge on Creators update is great browser I have to use FF just for this issue.

**Comment by danielkerr** [comment]
fix https://github.com/opencart/opencart/issues/1991

**Comment by sandaezreal** [comment]
Same issue encounter
