### ISSUE TITLE
Cannot delete or edit an Order

### ISSUE THREAD

**Issue by vahrheit** [opencart/opencart#1993]
Clean install of OC 2.0.0, without vQmod, out-of-the-box.
I reinstalled at least 6 times and always get the same error.
I try to create a new order in the administration, click on "continue":
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
I can create an order through the frontend, but impossible to delete or edit it. Same error message.

Also , the order in status "Pending" doesn't appear in the administration dropdown-toggle

Following files have access rights 777:
 /www/htdocs/.../shop-devel/config.php
/www/htdocs/.../shop-devel/admin/config.php
/www/htdocs/.../shop-devel/system/cache/
/www/htdocs/.../shop-devel/system/logs/
/www/htdocs/.../shop-devel/system/download/
/www/htdocs/.../shop-devel/system/upload/
/www/htdocs/.../shop-devel/image/
/www/htdocs/.../shop-devel/image/cache/
/www/htdocs/.../shop-devel/image/catalog/

.htaccess hast the new base /shop-devel/

Thanks fo your help!

**Comment by test34interactive** [comment]
Thanks a lot you saved my time.

**Comment by salmanindia** [comment]
finally got the right answer

**Comment by cornernote** [comment]
If anyone else is here with no solution to this, ask your host if they have mod_security.  If so, ask them to turn it off.

**Comment by Murmur** [comment]
OpenCart is using curl shellexec(from PHP) for various APIUser privileged tasks. This makes API calls run in a separate http request context, it's not using the same remoteIP as your web browser. Previous OpenCart did not have such double-context issues.
* You may have `.htaccess` to limit /admin access to intranet IP range, make sure 127.0.0.1 is enabled
* You may have a public hostname which does not resolve properly in an intranet, try `$ ping mycart.com and ping www.mycart.com` to see if it works in a localhost
* If hostname does not work locally then edit `/etc/hosts` configuration to add a custom dns name mapping

We had problems with the internal test environment, it is using a custom Apache virtual hostname and remote Windows machines use `c:/windows/system32/drivers/etc/hosts` to hostname mapping. **OpenCart is using that hostname used by the remote client for APIUser interface calls** and this may produce unexpected problems. 

OpenCart probably should use or give Settings config to make use 127.0.0.1 hostname for all API calls. Virtual hostnames, test environment hostnames or weird remote client proxy pipelines did not produce side effects.

**Comment by niyak2** [comment]
please copy admin folder once again

**Comment by Prozexis** [comment]
Problem still continue. I'm using OC 2.0.3.1,
I have tried all advice included above here and fallowing adresses:
https://forum.opencart.com/viewtopic.php?f=181&t=132699&start=60
https://github.com/opencart/opencart/issues/1993
https://github.com/opencart/opencart/issues/2587
http://stackoverflow.com/questions/28053063/opencart-2-0-syntaxerror-json-parse-unexpected-end-of-data-at-line-1-column-1
http://stackoverflow.com/questions/27732677/opencart-2-0-0-syntaxerror-json-parse-unexpected-end-of-data-at-line-1-colu
https://forum.opencart.com/viewtopic.php?f=181&t=133490
http://www.viethemes.com/how-to-fix-error-syntaxerror-unexpected-end-of-input-ok-when-editing-order-in-opencart-2/

But not working any solution. Still I'm getting error.... 

Also I'm getting this error: 
<b>Notice</b>: Undefined variable: order_id in <b>/home/dossenamilano/public_html/catalog/model/fraud/maxmind.php</b> on line <b>8</b>

This line content is:
$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "maxmind` WHERE order_id = '" . (int)$order_id . "'");

In line number 7 content is commentted line (fixed issue) :
//$fraud_info = $this->getFraud($data['order_id']);

So I changed it to 
$order_id = $this->getFraud($data['order_id']);

But nothing change... problem still contniue...

So sorry for my bad english....

**Comment by sfaragy** [comment]
Here is the real solution. If please visit this link below where you can see the live demo and you can figure it out by yourself. Video documentation and screenshot also available.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=24725

**Comment by sfaragy** [comment]
Here is the real solution. Please visit this link below where you can see the live demo and you can figure it out by yourself. Screenshots also available.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=24725

**Comment by Opencartprogrammer** [comment]
Hi all,
Finally we get the solution for the order edit error "SyntaxError: 

JSON ... ok" in OpenCart 2.0.1.0, 2.0.1.1, 2.0.2.0, 2.0.3.1, 2.1.0.1, 

2.1.0.2, 2.2.0.0, 2.3.0.0, 2.3.0.1, 2.3.0.2 If you really want to get 

the solution for the order edit error in your OpenCart store then 

visit us and contact through GET A QUOTE message or place a support 

ticket by the links below respectively.

http://opencartprogrammer.com/

http://opencartprogrammer.com/helpdesk/

Our support team will get back to you soon.

thanks
Opencartprogrammer team

**Comment by patricmutwiri** [comment]
This is a working Solution. 
I had this particular issue. Once an order is created, I, the Admin, couldn't edit the order. It's not a bug or anything. It's a security update which opencart implemented via user/api, and is called during several operations on site, ie Order Additions, Deletions or Modifications. 

For it to work for you, ask your host to disable mod_security for urls with "admin", or urls containing your IP Address, or check if your htaccess can overide and disable it from there. 

You can also exclude per request/method type 'POST' or 'GET'.

Please note, Latest mod_sec is mod_security2

Guess am happy after I found out the real issue. 
![opencart_order_edit](https://user-images.githubusercontent.com/7590159/27328180-e1a22dd8-55b9-11e7-8028-eafcf1ee5ef6.png)
