### ISSUE TITLE
Royal Mail Shipping Module Services incorrect

### ISSUE THREAD

**Issue by Upuaut** [opencart/opencart#2020]
Royal Mail amended the services and prices back in March 2014. The prices you can amend within UI but the service descriptions you cannot.

http://www.royalmail.com/sites/default/files/RM_OurPrices_Mar2014a.pdf

Airsure has sort of been retired (Its now called International Tracked) and replaced with International Tracked and Signed, International Tracked and International Signed. Quite a few destinations that used to be Signed only are now covered under International Tracked and Signed.

Amended destinations :
http://www.royalmail.com/sites/default/files/RoyalMail_International_TrackedCoverage_Jan2014.pdf

**Comment by danielkerr** [comment]
http://www.royalmail.com/sites/default/files/docs/pdf/despatch_express_interfacing_guide.pdf
