### ISSUE TITLE
top category menu not clickable ,  need to fix it.

### ISSUE THREAD

**Issue by ghost** [opencart/opencart#2024]
if category hasnt any sub category then top category menu category name is clickable , but if category has subcategorys, drop down show subcategory names but we cant click mainly parent category name. for example in demo mode Laptops & Notebooks  category has products mapped but on the top menu we can click only Macs and Windows subcategory name, we cant click Laptops & Notebooks to see products because of subcats  but whe we click on Phones & PDAs and Tablets then it is working.

**Comment by rajeshroy86** [comment]
You can make a category  clickable by removing **data-toggle="dropdown"** class from header .tpl at line no  116.
