### ISSUE TITLE
Paypal Express Checkout not sending address to Paypal

### ISSUE THREAD

**Issue by snakesss** [opencart/opencart#2027]
Hi

When i use Paypal Express Checkout, payments are received by paypal, but paypal does not receive an address from the customer, and therefore the order is not covered by the protection program.

What needs to be done so that Paypal receives the shipping information from open cart?

Everything else is sent to paypal fine, product titles, prices, shipping, ... just not the address.

Thank you

**Comment by bonny3** [comment]
Hi,
I have a problem to send the customer's address in PayPal Express.
I use Opencart 2.0.3.1, 
I have edited the file
catalog / controller / payment / pp_express.php
I followed the instructions
https://github.com/opencart/opencart/pull/2404/commits/465244e04111490cd172daff7ff10ab9ca4466d7
but does not work the transmit shipping address in PayPal...
Hope you can help me...
Thank you

**Comment by webcorvo** [comment]
Hi,
I am from Portugal and i am working in localhost.
I have OC version 2.3.2 and i am working in localhost.
When i try to pay with PayPal Express Checkout i have this erros.

Thanks  you help me?

I am using sendox to test ...
In attach go my error logs
[log_error.txt](https://github.com/opencart/opencart/files/994061/log_error.txt)

Webcorvo
