### ISSUE TITLE
Products ->Special on Chrome

### ISSUE THREAD

**Issue by lindsmcw** [opencart/opencart#2057]
When trying to put a Special for one of the products under products ->  special using Chrome, I was unable to enter a special price as the box was too small to see what I was typing.
I was able to enter the price using Internet Explorer, not sure about other browsers.
Another minor issue is that if you put a dollar sign '$' in the price section with any price it will show as 0.00. It could possibly show an error message saying only numbers and full stops allowed.

**Comment by svayamalhotra** [comment]
there is some problem with every product's special price as it auto disappear many times from all the products and I have to clear cache from my browser to display that again. I'll bound my buyers.
