### ISSUE TITLE
Adding new payment - Amazon Payments

### ISSUE THREAD

**Issue by lindsmcw** [opencart/opencart#2059]
From the page with the list of payments, when adding Amazon Payments (in Chrome) I clicked on Install and it came up with the following error: (I deleted the full dir for privacy)
Warning: Invalid argument supplied for foreach() in ...public_html/market/admin/model/setting/setting.php on line 22Warning: Cannot modify header information - headers already sent by (output started at .../public_html/market/admin/index.php:80) in .../public_html/market/system/library/response.php on line 12

**Comment by artras** [comment]
I have same problem, how you resolved it?

**Comment by lindsmcw** [comment]
It wasn't resolved. Try asking them again, support is a bit temperamental.
