### ISSUE TITLE
Unlimited coupon use when "use per customer" and "uses per coupon" set to 1

### ISSUE THREAD

**Issue by mewolari** [opencart/opencart#2068]
I've made a coupon code, set the "uses per coupon" to 1 and "uses per customer" to 1.

Customers are however able to use the coupon every single order, so not only the first time they use the order.

**Comment by sahildeliwala** [comment]
Please help me, I'm Getting the same problem.

Thank you.

**Comment by IBBoard** [comment]
For anyone else suffering from this (as it still appears to be a problem when using PayPal and other callback-based methods) then try the patch in https://forum.opencart.com/viewtopic.php?t=65018 (also referenced from the Bugs Thread)
