### ISSUE TITLE
Bug in admin product listing

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#2085]
I think this bug affects all 1.5.x and 2.x OpenCart versions.

Scenario: A shop owner has 2 languages, 'English' (disabled) and 'Greek' (enabled). His products are in the Greek language only, and are shown as such on the frontend as the only active language. And in the backend he can list all products in Catalog > Product as long as he uses the Greek admin language. However, as soon as he switches to to english admin language, none of the products are shown on the admin backend. 

The reason for this is a bug in file 'admin/model/catalog/product.php', which uses this condition in the DB queries to retrieve the products:

```
pd.language_id = '" . (int)$this->config->get('config_language_id') . "'"
```

This is wrong because 'config_language_id' in the admin backend always refers to the admin language, not the default language. It is safe to assume that the product names and/or descriptions always exist in the configured default language which is always available in the 'config_language' setting. Hence my proposed bugfix for this:

Use this to get the default language id:

```
    protected function getDefaultLanguageId() {
        $code = $this->config->get('config_language');
        $sql = "SELECT language_id FROM `".DB_PREFIX."language` WHERE code = '$code'";
        $result = $this->db->query( $sql );
        $language_id = 1;  // fallback to English if all else fails
        if ($result->rows) {
            foreach ($result->rows as $row) {
                $language_id = $row['language_id']; // the configured default language
                break;
            }
        }
        return $language_id;
    }
```

Then replace all instances of

```
(int)$this->config->get('config_language_id')
```

with

```
(int)$this->getDefaultLanguageId()
```

Also, while we are at it: When editing a product in the admin backend, it should perhaps show only language tabs for languages which are not disabled.

**Comment by hoseinBL** [comment]
@mhcwebdesign hi
I have same problem with the filters. How can I find your VQmod/OCmod XML file to fix this bug?
