### ISSUE TITLE
Extension installation error

### ISSUE THREAD

**Issue by samirkumardas** [opencart/opencart#2118]
Hi
I tried to install an extension from following OS and got same error "PHP Warning:  ftp_mkdir(): admin: Permission denied in ... installer.php on line 318 "
1. Mac - 
2. Windows
3. Linux

In Mac, ftp_nlist() is returning file names with relative path where windows/linux returns only file name. Also following lines affect original path with respect to FTP root so ftp_mkdir() shows error.

$position = strpos($destination, '/');
if ($position !== false) {
  $destination = substr($destination, $position + 1);
 }

For example, 

if $destination is  "catalog/controller/product", after applying strpos(),  $destination   becomes "controller/product" and 
$files=array("controller/account","controller/product","controller/payment","affiliate" ...);  // For windows/Linix
$files=array("controller/account","controller/product","controller/payment","controller/affiliate" ...);  //For Max

As a result,  if (!in_array($destination, $list))  condition will be always false and it tries to create ftp_mkdir("controller/product") which directory is already existed and return a php warning

I have created a patch for the fixing but did not send pull request. Just wanted to share what I found. Here is the patch

https://github.com/samirkumardas/opencart/commit/efaa5b4334cf96bb9b57405860967fd159c5a28c?diff=unified

Thanks
samir

**Comment by CodeSpanish** [comment]
Is this issue back in 2.2.0.0? I have the same permission errors with an extension based on OCMOD?

**Comment by samirkumardas** [comment]
Seems ftp information mostly ftp root is wrong under store setting. Please recheck

**Comment by danielkerr** [comment]
works fne for me and many others!

@samirkumardas also the fix you did broke a load of peoples stores. wasting my time! with imaginay fixes for issues caused by your selfs!

**Comment by samirkumardas** [comment]
@danielkerr  are you referring to correct person?   You have commented same `time wasting thing` in this issue https://github.com/opencart/opencart/pull/2400 as well

Also I did not send any pull request for this issue.

**Comment by danielkerr** [comment]
yeah sorry wrong person. some one added some code to mkdir and not ftp_mkdir and caused a load of issues.

**Comment by danielkerr** [comment]
from what i have been told about twig extensions they do all some php code to be executed if required.

so if user installs an extension that requires php to be executed in a theme and its available in the theme editor then is a security problem. i need to do more research. im still busy with the theme editor.
