### ISSUE TITLE
Customer custom field error in registration

### ISSUE THREAD

**Issue by faern** [opencart/opencart#2147]
When having custom fields for customer registration (Sales -> Customers -> Custom fields) for either location account OR address, but not for both. Then this error appears upon clicking "Continue" in the register user form:

**Notice: Undefined index: address in /home/gardsbut/public_html/shop/catalog/controller/account/register.php on line 281
Fatal error: Unsupported operand types in /home/gardsbut/public_html/shop/catalog/controller/account/register.php on line 281**

This is because register.php is only checking for _isset($this->request->post['custom_field'])_, if that is true it concatenate the values ['account'] and ['address'] under that post data but one of them is empty since we only have custom fields for one.

**Comment by qahmad81** [comment]
replace line 
		if (isset($this->request->post['custom_field'])) {
with this
		if (isset($this->request->post['custom_field'])&&is_array($data['custom_field'])) {
