### ISSUE TITLE
Contact form does not send mail

### ISSUE THREAD

**Issue by lazarus477** [opencart/opencart#2198]
Version 2.0.0.1b

Hello

I have setup OC 2 from git and gotten mail out through news letter but the contact form does not send any mail. The in app error log does not give any output either.

Any suggestions?

**Comment by ynagarjuna1995** [comment]
I was unable to recieve mails sent from the Contactus from 

I am using Opencart 2.1.0.2 Bitnami VM Image hosted on Azure.

I have checked spam too there is no mail._

**Comment by vigneshmuthukrishnan** [comment]
open cart mail is not working but alert (Your enquiry has been successfully sent to the store owner!)  is working mail not received

**Comment by KeepCreatingOnline** [comment]
> open cart mail is not working but alert (Your enquiry has been successfully sent to the store owner!) is working mail not received

Im having this same issue. Contact form not working. Test emails are working to client emails. How to fix?

**Comment by mhcwebdesign** [comment]
@KeepCreatingOnline: This is a 5 years old report, long fixed since then in OpenCart 3.0.x.x releases.
If you really want help, you have to provide some more details on how reproduce your error, for what OpenCart version.

**Comment by lazarus477** [comment]
Like @mhcwebdesign states, this is an old bug report, now **7 years old**. I have since moved on but in conclusion. I ended up writing my own tests using **sendmail** and mail was sent as expected. But the contact form in OpenCart simply did not work. I can only assume that this has since been fixed, in some later **update**.

**Comment by danielkerr** [comment]
@lazarus477 bullshit. it works fine for me. maybe u should setup ur php conf or php.ini properly.

**Comment by lazarus477** [comment]
@danielkerr to clarify. **7 years ago** this was an issue, for me, on a now way outdated version of OpenCart. Back then, as I recall, all mail features in OC worked as expected, except for the contact link in the page footer. **Not casting blame** so do not take it personally. My comment was ment as **constructive feedback** for those who stumble on this now **ancient** issue.

In all respect. Thank you for providing us with OpenCart and thank you for the free BS, I have use for it in another realm...
