### ISSUE TITLE
Any chances to get a PostgreSQL support?

### ISSUE THREAD

**Issue by msva** [opencart/opencart#22]
HI there! I've writen a PostgreSQL driver for opencart, but it seems to be useless a bit: many parts of OpenCart executes SQL queries directly in model/ instead of using drivers code.
So, is it any chances to rewrite OpenCart a bit to not to do that, but use drivers instead? :)

**Comment by it-all** [comment]
Any progress on this?

**Comment by fbobraga** [comment]
I'm stucked on install/index.php?route=install/step_3 trying to use an existing pgsql database...
