### ISSUE TITLE
Bug in installing the specials module

### ISSUE THREAD

**Issue by basanta123** [opencart/opencart#2212]
When i  installed the specials module and added the module to my home layout with limit, width and height of image it displays the error and could not load the image as well.It displays the error like:

Notice: Undefined index: limit in C:\xampp\htdocs\opencart-2.0\upload\catalog\controller\module\special.php on line 24Notice: Undefined index: width in C:\xampp\htdocs\opencart-2.0\upload\catalog\controller\module\special.php on line 32Notice: Undefined index: height in C:\xampp\htdocs\opencart-2.0\upload\catalog\controller\module\special.php on line 32Warning: imagecreatetruecolor(): Invalid image dimensions in C:\xampp\htdocs\opencart-2.0\upload\system\library\image.php on line 86Warning: imagecolorallocate() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\opencart-2.0\upload\system\library\image.php on line 94Warning: imagefilledrectangle() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\opencart-2.0\upload\system\library\image.php on line 97Warning: imagecopyresampled() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\opencart-2.0\upload\system\library\image.php on line 99Notice: Undefined index: width in C:\xampp\htdocs\opencart-2.0\upload\catalog\controller\module\special.php on line 32Notice: Undefined index: height in C:\xampp\htdocs\opencart-2.0\upload\catalog\controller\module\special.php on line 32Warning: imagecreatetruecolor(): Invalid image dimensions in C:\xampp\htdocs\opencart-2.0\upload\system\library\image.php on line 86Warning: imagecolorallocate() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\opencart-2.0\upload\system\library\image.php on line 94Warning: imagefilledrectangle() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\opencart-2.0\upload\system\library\image.php on line 97Warning: imagecopyresampled() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\opencart-2.0\upload\system\library\image.php on line 99

**Comment by umarfarukm** [comment]
i am still receiving this error now after upgrade to 2.xx version.

**Comment by Ergotron-Mexico** [comment]
i update and not problems from 1.5.6
