### ISSUE TITLE
<b>Fatal error</b>:  Cannot use string offset as an array in <b>/admin/view/template/sale/customer_form.tpl on line 489

### ISSUE THREAD

**Issue by shrimantech** [opencart/opencart#2234]
Customer Page tabs are not working in admin side. Since it is throuing the error message at line 487, when there is a custom field is added and mapped to the address section.
Failed to load the error message parts, because of the array index issue.

To replicate this issue, add a custom field (like telephone number) in admin side and map that custom field to the address section for customers.

The impact is, It will through error message in html  page and stop loading the further sections.

Correction in array index is required to fix up this issuehttp://stackoverflow.com/questions/2058635/cannot-use-string-offset-as-an-array-error

**Comment by rtbfreitas** [comment]
Hi,

Is this fixed? I still got this issue on 2.0.1.1.

Thanks.

**Comment by qahmad81** [comment]
hi

use this until (يفرجها الله) fix 

https://drive.google.com/file/d/0B2-nzvg31rU7d3NhbkhHU2IwNFk/view

**Comment by rtbfreitas** [comment]
Hi,

Thanks @qahmad81 , its working.
