### ISSUE TITLE
Syntax Error when adding order history

### ISSUE THREAD

**Issue by lab1750** [opencart/opencart#2251]
OpenCart 2.0
When attempting to add history to an order, an error pops up:

Syntax Error: Unexpected end of input

**Comment by psitsolution** [comment]
official demo site of opencart 2.0.1.1 have the same problem "sintax error"!!!!
![captura de pantalla 2015-03-21 a la s 13 05 09](https://cloud.githubusercontent.com/assets/6780838/6765153/91a8789e-cfcb-11e4-9529-93cee86b9000.png)
