### ISSUE TITLE
Featured and latest modules left and right display issue

### ISSUE THREAD

**Issue by dazzyweb** [opencart/opencart#2297]
The featured and latest modules don't display correctly in position column left and column right. width only set to 25% -  col-lg-3
![capture](https://cloud.githubusercontent.com/assets/5357457/5117179/35f8751c-7049-11e4-98a5-35a84390783e.JPG)

**Comment by kishorejangid** [comment]
I also see the same issue when displaying special product in left column. Will there be a fix.

**Comment by xannonmedia** [comment]
Will there be a fix to this issue?  I realize "its not designed to go in to the columns" but it should be.  Previous OC versions did, and most other OC e-commerce competitors do.
