### ISSUE TITLE
Admin Category list displays wrong sort order

### ISSUE THREAD

**Issue by jusurb** [opencart/opencart#2329]
In Admin-side Category list displays always the top most parent's sort order not the actual category.

if i have category "Parent" with sort order 0
and "Parent > Child 1" with sort order 1
in the list there will be:
"Parent" 0
"Parent > Child 1" 0

if you open and edit form sort order is displayed correctly, but not in the list. It's confusing and you can't see what sort order is set for other then top most categories.

**Comment by Gamesh** [comment]
appears to have been fixed by 3cd7970b864737c9431622ead3af0276872fa34e
