### ISSUE TITLE
opencart 2.0.0.0 template issue

### ISSUE THREAD

**Issue by srinivas714** [opencart/opencart#2403]
Hello,
i am installing opencart2.0.0.0 and i have installed 1.5.6.X template it shows error like shown below.
Notice: Undefined property: Loader::$config in C:\xampp\htdocs\upload\catalog\view\theme\lexus_superstore\template\module\featured.tpl on line 2
Fatal error: Call to a member function get() on a non-object in C:\xampp\htdocs\upload\catalog\view\theme\lexus_superstore\template\module\featured.tpl on line 2

**Comment by Devpriy** [comment]
Hello 
i am try to update my menu module 1.5.6.x to 2.x so display this error

    Notice: Undefined property: Loader::$config in C:\wamp\www\opencart-theme\catalog\view\theme\ndsoft21001\files\menu.tpl on line 159
    Fatal error: Call to a member function get() on a non-object in C:\wamp\www\opencart-theme\catalog\view\theme\ndsoft21001\files\menu.tpl on line 159

please help me 

Thanks
Devpriy
