### ISSUE TITLE
Recurring Profiles Checkout Step #6 Errors

### ISSUE THREAD

**Issue by mallone** [opencart/opencart#2435]
There are undefined index & variable when using recurring profiles during checkout step #6 

Notice: Undefined index: recurring_trial in C:\xampp\htdocs\200\catalog\controller\checkout\confirm.php on line 362
Notice: Undefined index: recurring_duration in C:\xampp\htdocs\200\catalog\controller\checkout\confirm.php on line 366
Notice: Undefined variable: text_recurring in C:\xampp\htdocs\200\catalog\view\theme\default\template\checkout\confirm.tpl on line 23

![recurring-profiles-errors](https://cloud.githubusercontent.com/assets/2141568/5308636/f582feae-7bcd-11e4-812d-7172af6dd12e.png)

**Comment by rmullaney77** [comment]
Came here to see if the model issue was reported since I just had to add an ugly hack of my own code to fix it. The 2.x model is looking for 1.5.x array keys. Assuming comments go unread after these are closed, will create a new issue with details.
