### ISSUE TITLE
Latest Module - Showing Twice (image)

### ISSUE THREAD

**Issue by southbendmedia** [opencart/opencart#2450]
![untitled](https://cloud.githubusercontent.com/assets/5648120/5327924/1d5494a8-7d34-11e4-8a95-ff4b6f376b94.jpg)

I installed 2.0, then upgraded to 2.0.10 after it was just released from the website copy. Then I pulled the master file and still experienced the same issue.

**Comment by umarfarukm** [comment]
i am having the same issue. tried re-installing, but didn't help!
