### ISSUE TITLE
ZIP Extension While Installing 

### ISSUE THREAD

**Issue by localkingcharan** [opencart/opencart#2454]
I am Getting an issue with ZIP Extension while  installing  opencart  , i have already enabled my ZIP Extension in Easyapache  but  I Am getting The ZIP Extension  as  "off" . This  is  the  only one  extension i am getting  problem  !  
![zip](https://cloud.githubusercontent.com/assets/8296640/5330046/c86cadaa-7dfa-11e4-94b6-bbf940e06a28.JPG)

**Comment by lcfigo** [comment]
i have the same problem. Hope it can help other people.
If you also use Cpanel and Linux hosting
![Uploading WechatIMG5112.jpeg…]()
, you can going to "Linux hosting with cPanel" - "Software" - "Select PHP version" - Select "zip" - Save. Then reflash, done.

**Comment by Siunlite** [comment]
next time try restarting the php-fpm service, it work for me!! :+1:

**Comment by trmylinh** [comment]
I use Windows, I have a same error and I can not fix it, please help me 
![image](https://github.com/opencart/opencart/assets/89790450/5fbe270b-4e82-4769-a5c2-b5dd4d0418de)

**Comment by danielkerr** [comment]
edit to conf or php.ini

**Comment by danielkerr** [comment]
extension=curl
;extension=ffi
;extension=ftp
extension=fileinfo
extension=gd
extension=gettext
;extension=gmp
;extension=intl
;extension=imap
extension=mbstring
extension=exif      ; Must be after mbstring as it depends on it
extension=mysqli
;extension=oci8_12c  ; Use with Oracle Database 12c Instant Client
;extension=oci8_19  ; Use with Oracle Database 19 Instant Client
;extension=odbc
;extension=openssl
;extension=pdo_firebird
extension=pdo_mysql
;extension=pdo_oci
;extension=pdo_odbc
;extension=pdo_pgsql
extension=pdo_sqlite
;extension=pgsql
;extension=shmop

; The MIBS data available in the PHP distribution must be installed.
; See https://www.php.net/manual/en/snmp.installation.php
;extension=snmp

;extension=soap
;extension=sockets
;extension=sodium
;extension=sqlite3
;extension=tidy
extension=xsl
extension=zip
