### ISSUE TITLE
Unable to copy a Recurring Profile

### ISSUE THREAD

**Issue by Hell-Raiser** [opencart/opencart#2458]
Add a Recurring Profile. Select it and click on Copy. Instead of getting copied it gets deleted.

**Comment by Lidorc145** [comment]
I have version 2.0.2.0... 

I fix it:
you need to change line in this file:
 upload/admin/view/template/catalog/recurring_list.tpl 

I doesn't know how to put code here so its on image... 
![default](https://cloud.githubusercontent.com/assets/12116215/7334897/2d935ffe-ebaa-11e4-9012-9ff9936d7678.png)

good luck :)
