### ISSUE TITLE
Authorize.net AIM module not submitting product information

### ISSUE THREAD

**Issue by usefulz** [opencart/opencart#2475]
http://community.developer.authorize.net/t5/Integration-and-Testing/Itemized-order-info-with-AIM/td-p/2797
http://www.authorize.net/support/AIM_guide_XML.pdf

The authorize.net AIM gateway included with opencart does not submit product information.  Here's the code that I think will work, but I would like to see this fixed if at all possible.

```
$products   = $this->model_checkout_order->getOrderProducts($this->session->data['order_id']);
foreach($products as $product)
{
  $line_items[] = sprintf("%d<|>%s<|>%s<|>%d<|>%s<|>Y", $product['id'], $product['name'], $product['name'], $product['quantity'], $product['price']);
}
$data['x_line_item'] = urlencode($line_items);
```

in

catalog/controller/payment/authorizenet_aim.php

**Comment by cryptokevin** [comment]
usefulz probably is an agent of the IRS
