### ISSUE TITLE
oc2 modules are not display properly on category page

### ISSUE THREAD

**Issue by adnan00733** [opencart/opencart#2499]
I found some display errors in opencart version 2.0
opencart version 2.0 modules are not displaying properly on category page. especially featured , latest etc 
Modules that have images  are not display properly in left column and right column. 

here is the solution.
go to "catalog/view/javascript"  and open file "common.js"
Go to line number 88 
find 
$('#content .product-layout').attr('class', 'product-layout product-list col-xs-12');"
replace 
$('#content .row > .product-layout').attr('class', 'product-layout product-list col-xs-12');

Go to line number 101
find 
$('#content .product-layout').attr('class', 'product-layout product-grid col-lg-6 col-md-6 col-sm-12 col-xs-12');
replace
$('#content .row > .product-layout').attr('class', 'product-layout product-grid col-lg-6 col-md-6 col-sm-12 col-xs-12');

Go to line number 105
find 
$('#content .product-layout').attr('class', 'product-layout product-grid col-lg-4 col-md-4 col-sm-6 col-xs-12');
replace
$('#content .row > .product-layout').attr('class', 'product-layout product-grid col-lg-4 col-md-4 col-sm-6 col-xs-12');

Go tjo line number 109
find
$('#content .product-layout').attr('class', 'product-layout product-grid col-lg-3 col-md-3 col-sm-6 col-xs-12');
replace
$('#content .row > .product-layout').attr('class', 'product-layout product-grid col-lg-3 col-md-3 col-sm-6 col-xs-12');

Go to line number 125
add following line here 
$("#column-left .product-layout > div , #column-right .product-layout > div").removeClass("col-lg-3 col-md-3 col-sm-6 col-xs-12").addClass("col-lg-12");

Thank you .

**Comment by Dentan80** [comment]
I have the same problem with the content_bottom and top module appears small, how can I change the size?

**Comment by danielkerr** [comment]
your so called fix does nothing to the columns. 

you have not even product any evidence there is an issue!

"I found some display errors in opencart version 2.0"

this could mean a million things!

DO NOT POST HERE AGAIN UNLESS YOU ARE GOING TO PROVIDE SOME ACTUAL INFORMATION INSTEAD OF WASTING MY TIME!
