### ISSUE TITLE
404 Error in store when Use SEO URLs in the store settings

### ISSUE THREAD

**Issue by latutioti** [opencart/opencart#2500]
The store breaks all the links when you change the Use SEO URLs to yes in the store settings under the server tabs in the 2.0.1 version.

**Comment by ahmadneyaj** [comment]
I have also same problem. please help me to short out this problem. Thanks in advanced

**Comment by TLEwebdevs** [comment]
I had the same problem too - there is insufficient instruction in the documentation to assist either.

For any website this is a critical area and seems to get swept aside in OC - why?
