### ISSUE TITLE
Review Cannot be posted 2.0.0.0

### ISSUE THREAD

**Issue by guidea1** [opencart/opencart#2519]
I am using Opencart 2.0.0.0, and has vmod installed with SEO enabled.  Other parts of the application seems to be working fine, but when review is posted, the message "Warning: Verification code does not match the image!" is displayed all the time and users cannot post reviews.  Please help.

**Comment by danielkerr** [comment]
works fine for me!

**Comment by guidea1** [comment]
It is still not working. Please help!
