### ISSUE TITLE
Summernote bold bug

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#2521]
When you write the word and change to bold appears this:

`<p><span style="font-weight: normal;">test</span><br></p>` 

Then click again "B" and appears:

`<p><span style="font-weight: bold;"><span style="font-weight: normal;">test</span></span><br></p>` 

OC Version 2.0.1.2_rc

**Comment by mario-inventum** [comment]
This bug not exist in in Chrome (v.39), but only in FF (tested v.34) and IE (tested IE11).

Problem is in default admin stylesheet (/admin/view/stylesheet/stylesheet.css) on line 9:
```css
font-weight: 500;
```

Comment that line:
```css
/* font-weight: 500; */
```
and bug will disappear :-)
