### ISSUE TITLE
upgrade success page has broken images

### ISSUE THREAD

**Issue by tvanbeek** [opencart/opencart#2524]
The images in install/view/template/success.tpl refer to view/image/screenshot_1.png and view/image/screenshot_2.png but are non existent
![image](https://cloud.githubusercontent.com/assets/3518980/5580191/3a5f8faa-9047-11e4-87e2-df78cbce0a15.png)

**Comment by nosite** [comment]
reported on 25 sept... still no fix for it.
https://opencart.atlassian.net/browse/OC-1855

**Comment by danielkerr** [comment]
I dont use the isue tracker on opencart.atlassian.net

this is github! why post to another tracker!
