### ISSUE TITLE
Upgrade Error: 1.5.6 to 2.0.1.1

### ISSUE THREAD

**Issue by gpearson** [opencart/opencart#2526]
Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /var/www/virtuals/ww2.thunderkingfireworks.com/www/system/startup.php on line 53

Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /var/www/virtuals/ww2.thunderkingfireworks.com/www/system/startup.php on line 57

Uninstalled all modules on version 1.5.6, backed up database, copied 2.0.1.1 files over installation and ran the install script. Upon clearing cache received error on accessing admin page.

**Comment by mLawrenci** [comment]
New to OC. Getting same error. Any help?
