### ISSUE TITLE
Missing array()

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#2533]
In 

public function getLatestProducts($limit)

 missing:

$product_data = array();

OC Version 2.0.1.2_rc

**Comment by danielkerr** [comment]
$product_data = $this->cache->get('product.latest.' . (int)$this->config->get('config_language_id') . '.' . (int)$this->config->get('config_store_id') . '.' . $this->config->get('config_customer_group_id') . '.' . (int)$limit);

		if (!$product_data) {
			$query = $this->db->query("SELECT p.product_id FROM " . DB_PREFIX . "product p LEFT JOIN " . DB_PREFIX . "product_to_store p2s ON (p.product_id = p2s.product_id) WHERE p.status = '1' AND p.date_available <= NOW() AND p2s.store_id = '" . (int)$this->config->get('config_store_id') . "' ORDER BY p.date_added DESC LIMIT " . (int)$limit);

			foreach ($query->rows as $result) {
				$product_data[$result['product_id']] = $this->getProduct($result['product_id']);
			}

			$this->cache->set('product.latest.' . (int)$this->config->get('config_language_id') . '.' . (int)$this->config->get('config_store_id') . '.' . $this->config->get('config_customer_group_id') . '.' . (int)$limit, $product_data);
		}

		return $product_data;

**Comment by danielkerr** [comment]
you have explained nothing!

any error messages?

**Comment by GomDani** [comment]
You are right, no errors. Maybe because this function is not used anywhere.
