### ISSUE TITLE
Amazon payments not working

### ISSUE THREAD

**Issue by maan82** [opencart/opencart#2534]
When I install Amazon payments I get blank page with warnings "Warning: Invalid argument supplied for foreach() in /home4/addonsca/public_html/admin/model/setting/setting.php on line 22Warning: Cannot modify header information - headers already sent by (output started at /home4/addonsca/public_html/admin/index.php:80) in /home4/addonsca/public_html/system/library/response.php on line 12"

If I go back to the admin->payments->Amazon Payments it is installed. But when I enable the module after filling all the details for UK Amazon payment button or checkout doesn't show up.

**Comment by artras** [comment]
I have same problem, how you resolved it?
