### ISSUE TITLE
css for slider still small 20px  issue after applying fix

### ISSUE THREAD

**Issue by pinkslink** [opencart/opencart#2535]
i have already applied the fix for slider css
and now have pagination displayed (which was not present before)

however, there is a 20px space at bottom of slider images (homepage and manufacturer sliders)
.owl-controls.clickable

i have tried adding this with .owl-controls (116, 120, 128) in the css file
and it does remove the 20px gap but in the process i keep losing pagination again

**Comment by danielkerr** [comment]
no idea what the you are talk about!

just wasting my time!

do you many 20px on banners
