### ISSUE TITLE
add/edit order from admin > Sales > Orders not working

### ISSUE THREAD

**Issue by hydrowire** [opencart/opencart#2537]
When trying to add a new order or edit existing orders from the admin > Sales > Orders, an error "Payment method required!" will popup even though a payment method has been correctly selected in the form, preventing the form from submitting.

The issue seems to be the session data "$this->session->data['payment_method']" is empty when /catalog/controller/api/order.php > add()/edit() did a check on it. But in fact, the correct variable is "$this->session->data['payment_methods']". However, simply changing the variable name doesn't fix the error.

It seems the core problem is coming from /catalog/controller/api/payment.php where variable name with & without "s" is being use interchangeably, thus, causing the confusion.

**Comment by danielkerr** [comment]
you need to hit the refresh button on the order editor > confim page

**Comment by sfaragy** [comment]
Here is the real solution. Please visit this link below where you can see the live demo and you can figure it out by yourself. Screenshots also available.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=24725

**Comment by larsbo** [comment]
same problem here.
hitting the refresh button next to the save button does nothing. ok, it fires an ajax request with parameters
```
api: api/cart/products
route: sale/order/api
store_id: 0
```
which returns ```products``` , ```vouchers``` and ```totals```. But that doesn't change the missing payment method error.

**Comment by larsbo** [comment]
@danielkerr any news on this bug? Maybe it has been fixed in a newer version than my current one (2.0.1.1)?
