### ISSUE TITLE
common.js popover (solution)

### ISSUE THREAD

**Issue by dtjones** [opencart/opencart#2544]
![screenshot 2015-01-06 17 48 14](https://cloud.githubusercontent.com/assets/1758785/5633132/4581975e-95cc-11e4-8c1e-bb63b41a3acc.png)

multiple popovers can be shown but only the first popover element shown has clickable buttons which change all the images instead of just the corresponding one. 

The correct element must be targeted rather that using $('#button-image')

		var popover = $(element).siblings('.popover');	
		popover.on('click', '#button-image', function() {

			var button = this;

			$('#modal-image').remove();	
			$.ajax({
				url: 'index.php?route=common/filemanager&token=' + getURLVar('token') + '&target=' + $(element).parent().find('input').attr('id') + '&thumb=' + $(element).attr('id'),
				dataType: 'html',
				beforeSend: function() {
					$(button).find('i').replaceWith('<i class="fa fa-circle-o-notch fa-spin"></i>');
					$(button).prop('disabled', true);
				},
				complete: function() {
					$(button).find('i').replaceWith('<i class="fa fa-upload"></i>');
					$(button).prop('disabled', false);
				},

This should work as it is but if there are multiple "#button-image" in the DOM then I would use a class instead of an id.

**Comment by danielkerr** [comment]
not sure this will work with ajax

**Comment by dtjones** [comment]
I made the change to my common.js file a while ago and its been working fine ever since. 

I haven't tried to change <strong><b>#</b></strong>button-image to <b>.</b>button-image as its working fine without it

**Comment by dtjones** [comment]
Sorry forgot to mention that 

    $('#button-clear').on('click', function() { . . . .

will clear all images if multiple popovers exist, although only the first clear button will work so that will also need to be changed to 

    popover.on('click', #button-clear', function() {

**Comment by dtjones** [comment]
@danielkerr, The id names DO need changing to classnames to work 100%. Although this code does work as it is. If you were interested in adding a direct upload icon to the popover or to allow drag and drop on the a[data-toggle=\'image\'] elements then the popover button ids will need removing.

**Comment by danielkerr** [comment]
if you click add image your solution will not work
also i prefer just having one popover showing at a time

**Comment by danielkerr** [comment]
thx for the code though
