### ISSUE TITLE
Add History: email notification is sent regardless of Notify checkbox value

### ISSUE THREAD

**Issue by jorimvanhove** [opencart/opencart#2546]
OC v2.0.1.1
When changing the order status on the order_info.tpl form, an notification email is sent to the customer regardless of the 'Notify' checkbox value, so an email is sent even when the checkbox is NOT checked. 

Solution Suggestion: 
file: catalog/model/checkout/order.php
line: 785
old value: if ($order_info['order_status_id'] && $order_status_id) {
suggested value: if ($order_info['order_status_id'] && $order_status_id && $notify) {

**Comment by Sokonomi** [comment]
I just spent a month tweaking 2.0.1.1 just the way I like it,
only to find out the history mail was borked.
You saved me hours of work, thanks!
