### ISSUE TITLE
I am getting error when i am creating clone of carousel module 

### ISSUE THREAD

**Issue by anupait** [opencart/opencart#2551]
Notice: Error: Could not load template /home/content/51/10396551/html/sesame/admin/view/template/module/Carouselone.tpl! in /home/content/51/10396551/html/sesame/system/engine/loader.php on line 45

How to get rid of this error ..

thanks

**Comment by CoverUp** [comment]
please close and use community forum instead (http://forum.opencart.com), this is an issue tracker used for the development of opencart core, not a support system. Regards.

**Comment by danielkerr** [comment]
uninstall the extension and reinstall
