### ISSUE TITLE
Compare doeas not cross original price when special price available

### ISSUE THREAD

**Issue by Schwannn** [opencart/opencart#2555]
Opencart 2.0.1.1, when adding products with special price to compare, it will show original price and special price both next to each other, it should either show both and cross the original price or just show special price.

**Comment by Schwannn** [comment]
I fixed it by adding a style to the span as follow:

Line 52 in compare.tpl
Change:
<span class="price-old"><?php echo $products[$product['product_id']]['price']; ?> </span><span class="price-new"> <?php echo $products[$product['product_id']]['special']; ?> </span>

to:
<span class="price-old", style="text-decoration: line-through;"><?php echo $products[$product['product_id']]['price']; ?> </span><span class="price-new"> <?php echo $products[$product['product_id']]['special']; ?> </span>

**Comment by mrg123** [comment]
<span class="price-old", style="text-decoration: line-through;"> 
you more , in here
