### ISSUE TITLE
cant use multi xml file in ocmod (xml over 64kb error)

### ISSUE THREAD

**Issue by qahmad81** [opencart/opencart#2559]
when xml file go over 64kb its show this error

Warning: DOMDocument::loadXML(): CData section not finished ...

i wish to could dividing xml file to move like admin modifications to admin.xml and more because large file is difficult to update, but when i look in admin/controller/extension/installer.php its seem it not possible :(

so currently i see to explode my ocmod in two ocmod, until someone give us solution her or opencart make update to this problem.

more information
http://stackoverflow.com/questions/27906799/ocmod-use-multi-xml-file-xml-over-64kb-error

thanks

**Comment by danielkerr** [comment]
there is also a install.php and install.sql function that will read when installing from an upload

**Comment by qahmad81** [comment]
ok but there is a error when xml file go over 64KB!!

so we should fix it by remove the limit on file size ((or)) divide the xml file.

**Comment by qahmad81** [comment]
ok i find the bug!! you store xml file in database and in field type (text) the size of this type is 64KB so when xml file go bigger than 64KB its cut and then you have the error above!!

read more about mysql text field type in this link
http://stackoverflow.com/questions/6766781/maximum-length-for-mysql-type-text

the type should be MEDIUMTEXT with 16MB size, please fix this in next ver

and for the public you can run this query in opencart database
ALTER TABLE  `oc_modification` CHANGE  `xml`  `xml` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ;

or use it via this ocmod
https://drive.google.com/file/d/0B2-nzvg31rU7QVAtZnVGN2lYRzA/view?usp=sharing

if have error in ftp use this ocmod
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=18892

now this issues closed. thanks.

**Comment by gob33** [comment]
I totally agree.
xml field in oc_modification is limited to 65535 chars (2^16 - 1) and my code of 100.000+ chars is cut.
It was a bad idea wanting to put a file inside the DB. Should have stay with vqmods.
You need to change to MEDIUMTEXT as complex extensions require more than 65535.
