### ISSUE TITLE
Missing tpl file in admin (common/buttons.tpl)

### ISSUE THREAD

**Issue by makbulut** [opencart/opencart#2564]
Paypal Express payment method controller(admin) calls "common/buttons.tpl" file in following line, but there is no buttons.tpl file in "admin\view\template\common" folder.

file           :  admin\controller\payment\pp_express.php
function   :  recurringButtons
line 1231 :  return $this->load->view('common/buttons.tpl', $data);

**Comment by danielkerr** [comment]
reupload the file is there

**Comment by spsaravananct** [comment]
Hi Danielkerr Still admin/view/template/common/button.tpl not found

**Comment by chris-willows** [comment]
Linked to:
https://github.com/opencart/opencart/issues/3602
