### ISSUE TITLE
Updating order history bug or error :(

### ISSUE THREAD

**Issue by franz2007** [opencart/opencart#2565]
hi

every time i edit the order history to any status, it always show 'canceled'. the problem is it doesnt show any bug error in the site. i look the error log at the cpanel of the hosting but it doesnt show any errors for it :( we use opencart 2.0. i also try to update it using other status like processed, refund etc. but once it save the message post as "canceled". im a bit worry since it might be affected even our online payments once we update the order history. we just need to fix the order history since it look like it has a bug on it.

our site is: http://www.curvyclothing.com.au
![1](https://cloud.githubusercontent.com/assets/10559307/5774108/7c18f4a2-9da5-11e4-831c-ee9703aa89e9.jpg)
![2](https://cloud.githubusercontent.com/assets/10559307/5774107/7c16d140-9da5-11e4-9149-4a2ea9ddf851.jpg)

**Comment by danielkerr** [comment]
works for me

**Comment by grazcata** [comment]
hi franz2007, i had the same issue , to fix it check the Fraud Setting that keep the order history canceled.
