### ISSUE TITLE
Edit Order

### ISSUE THREAD

**Issue by LokeshFating26** [opencart/opencart#2567]
Error Description is : SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

Is there any solution?

**Comment by rmullaney77** [comment]
A screen shot would help indicate which ajax request this is referring to.

**Comment by Tangol** [comment]
Seems the same issue as https://github.com/opencart/opencart/issues/2569

**Comment by rmullaney77** [comment]
Gotcha. Let me know if admin permissions were the cause.

**Comment by shamanime** [comment]
I am also having the same problem, it happens when I click on the "continue" button while editing an order.

Works fine locally. After googling some people said it could be curl, or mod_security, no solutions have worked so far.

![screenshot 2015-01-20 11 42 23](https://cloud.githubusercontent.com/assets/332276/5818089/78f5599a-a099-11e4-88c5-1413972a9b7d.png)

**Comment by shamanime** [comment]
As a follow up, I managed to fix this issue by removing the `https` protocol in the following config files:

##### config.php
Find:
```php
// HTTPS
define('HTTPS_SERVER', 'https://example.com/');
```
And change https to http:
```php
// HTTPS
define('HTTPS_SERVER', 'http://example.com/');
```
##### admin/config.php
Find:
```php
// HTTPS
define('HTTPS_SERVER', 'https://example.com/admin/');
define('HTTPS_CATALOG', 'https://example.com/');
```
And change https to http:
```php
// HTTPS
define('HTTPS_SERVER', 'http://example.com/admin/');
define('HTTPS_CATALOG', 'http://example.com/');
```

**Comment by danielkerr** [comment]
make sure maintenance mode is off!
make sure you have not password protected your site
make sure your host allows CURL calls to the same domain name you are sending from

**Comment by psitsolution** [comment]
official demo site of opencart 2.0.1.1 have the same problem "sintax error"!!!!can you explain????!
![captura de pantalla 2015-03-21 a la s 13 05 09](https://cloud.githubusercontent.com/assets/6780838/6765156/0087217a-cfcc-11e4-9952-e15c13f0466b.png)

**Comment by munirasim** [comment]
The issue is with PHP settings of the server. Opencart provides its own php.ini which may conflict with your server settings. Simply rename your 'php.ini' in root as well as admin folder to see if the problem is fixed. DON'T DELETE them unless issue is resolved.

**Comment by psitsolution** [comment]
why php.ini in my server? the problem is with your demo on your server 
(see attached screenshot)
maybe I'm missing something?
thanks

2015-03-21 13:25 Asim Munir:
> The issue is with PHP settings of the server. Opencart provides its
> own php.ini which may conflict with your server settings. Simply
> rename your 'php.ini' in root as well as admin folder to see if the
> problem is fixed. DON'T DELETE them unless issue is resolved.
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] 
> https://github.com/opencart/opencart/issues/2567#issuecomment-84333656

-- 
Pierluigi Spaziani
info@psitsoution.com / pierluigispaziani@gmail.com
http://www.psitsolution.com

**Comment by munirasim** [comment]
@psitsolution  I had the same issue on a client's installation. Deleting php.ini resolved the issue for that host. Now that installation is working fine. The issue does not exist in production environment. As far as demo is concerned, it is restricted to delete orders.

**Comment by alanrburns** [comment]
Wow this issue keeps on coming up and devs keep on closing them without any real investigation or solution. 
We might need to fork before big egos kill the project

**Comment by eatonmunoz** [comment]
I think I found the solution for this issue, since in OpenCart 2 it uses API you need to do these steps:
1. Make sure you have created user API in menu System / Users / API
2. Then in System / Settings, choose your store, select Options tab
3. In Checkout section, choose API User you just created
4. Save your settings
5. Try to add or edit an order again, it should be working.

**Comment by psitsolution** [comment]
don't work for me!

**Comment by milimar** [comment]
If this means something to you.....I have tested editing orders and it works fine for me on OC 2.0.1.2rc.

**Comment by dancarp** [comment]
Everyone keeps referring to PHP etc and configuration. If you are sure your config is correct, it isn't your fault.  

 2.0.1.1 is missing an option that was in 1.5x
See below:
![order-edit-fix](https://cloud.githubusercontent.com/assets/11760563/6950250/9376b568-d887-11e4-99e4-0e0cd6b26150.png)

**Comment by balanscs** [comment]
Hello,

My Version: 2.0.0.0 My php Version: ea-php55

When I choose Sales >> Orders >> Any Order >> Edit
The following errors are displayed at the top of the page:

Notice: unserialize(): Error at offset 0 of 2 bytes in /home/opencartorg/public_html/admin/model/sale/order.php on line 98
Notice: unserialize(): Error at offset 0 of 2 bytes in /home/opencartorg/public_html/admin/model/sale/order.php on line 114
Notice: unserialize(): Error at offset 0 of 2 bytes in /home/opencartorg/public_html/admin/model/sale/order.php on line 132

Someone could help me solve that problem?

Regards
