### ISSUE TITLE
Email Spam

### ISSUE THREAD

**Issue by xceptional** [opencart/opencart#2568]
Whenever I send an email using OpenCart> Mail option to all customers my account is blocked for email spamming and website is turned down.  Could you please make sure the emails are not sent instantly but with a gap of few seconds each to that it is not considered spamming.

**Comment by danielkerr** [comment]
I added a mass mail system because the community wanted it.

In reality it will probably get your domain name blacklisted for spamming. you can not just mass email these days. you need to use a service like mail chimp.
