### ISSUE TITLE
Error when logging in as a user

### ISSUE THREAD

**Issue by Tangol** [opencart/opencart#2569]
Hello,
I've just installed OC on WampServer 2.5, created a User Group and assigned a few Access Permissions to it (only the catalog ones).
Then i created a new user, but each time i log in the admin interface with it, i receive the following error:
![error](https://cloud.githubusercontent.com/assets/3336728/5781260/ee0aa3d0-9db9-11e4-861a-138c7c4cdd26.png)
This error appears only in the Admin Dashboard and i have to click OK twice to get rid of it.
`Tested on both versions of OC 2.0.1.1 and 2.0.1.2_rc rev` https://github.com/opencart/opencart/commit/6ad153d6ba3d11f301703089a44244557a808e46

**Comment by rmullaney77** [comment]
Can you provide the request that generated that response? Most desktop browsers have developer  tools that can show everything to/from the server during page load.

**Comment by JAY6390** [comment]
This is most likely due to your user not having permissions to access. Ensure they have access to `dashboard/map` and `dashboard/chart`

**Comment by rmullaney77** [comment]
That would do it. I just assumed those would be automatic since they would always generate such an error on log in.

**Comment by JAY6390** [comment]
@rmullaney77 One can never assume with opencart :smiling_imp:

**Comment by Tangol** [comment]
Thank you @JAY6390 
Checking `dashboard/map` and `dashboard/chart` fixes the issue.

Now we should have them checked by default i guess, so others don't experience the same issue in the future.

**Comment by rmullaney77** [comment]
Can we think of any reason why that would ever be turned off for an admin? If not, maybe just hide those selections to prevent assignment errors and always enable them during admin insert?

**Comment by Tangol** [comment]
Having complete control of the User/Admin access is a good thing, but we either have to find a way to manage these errors better, or as @rmullaney77 said, filter out the few standard selections that generate errors.

Many store owners will create a support department that has access to the Admin area and will assign special access roles to those users, so it's kinda hard to go thru all selections to find out which one generates an error, as seen here https://github.com/opencart/opencart/issues/2567 .

**Comment by rmullaney77** [comment]
I realize this was closed without a solution, but why not just check the first character of the data for "<" and bypass it? You're expecting data in a particular format, yet another is possible. Just add a conditional to avoid the error if nothing will be done to user creation to remove the possibility.

**Comment by Tangol** [comment]
Why did this issue get closed?
Is this the intended behavior, huge error without any reference to what caused it?

**Comment by JAY6390** [comment]
I'm guessing because it's not actually a bug, though it should be handled gracefully if they're not set

**Comment by danielkerr** [comment]
"Is this the intended behavior, huge error without any reference to what caused it"

because its been explained many times now!

**Comment by TLEwebdevs** [comment]
If it has to be expla times, then the logic behind it is flawed - strong/good logic needs no explanation.
