### ISSUE TITLE
Notice in \admin\controller\tool\backup.php on line 13

### ISSUE THREAD

**Issue by Tangol** [opencart/opencart#2571]
Installed `OC 2.0.1.2_rc rev` https://github.com/opencart/opencart/commit/6ad153d6ba3d11f301703089a44244557a808e46 and did a test backup of a database.
When i checked the Error Log i got the following notice:
`2015-01-16 21:13:13 - PHP Notice:  Undefined index: import in C:\wamp\www\admin\controller\tool\backup.php on line 13`

**Comment by danielkerr** [comment]
can not replicate this. I think the problem may have been the post request did not get fully through

**Comment by kikito94i** [comment]
I have a problem to backup or export the file 
C:\xampp\htdocs\xampp\multivendor\admin\model\tool\backup.php
