### ISSUE TITLE
Error when changing the Order Status

### ISSUE THREAD

**Issue by Tangol** [opencart/opencart#2572]
When i try to change the status of an order i'm getting the following error even if i have unchecked the Notify Customer box:
![error3](https://cloud.githubusercontent.com/assets/3336728/5783921/298144bc-9dd0-11e4-95e3-24c89e656e29.png)
`2015-01-16 21:27:19 - PHP Warning:  mail(): Failed to connect to mailserver at "localhost" port 25, verify your "SMTP" and "smtp_port" setting in php.ini or use ini_set() in C:\wamp\www\system\library\mail.php on line 162`

**Why does the script try to email the customer if the notify box is unchecked?**

*The same issue reported here:* http://forum.opencart.com/viewtopic.php?f=191&t=137285

`Using OC 2.0.1.2_rc rev` https://github.com/opencart/opencart/commit/6ad153d6ba3d11f301703089a44244557a808e46

**Comment by JAY6390** [comment]
It appears in OpenCart 2.0 that a customer gets notified of an order history update regardless of the notify setting. The $notify in `catalog/model/checkout/order.php` appears to simply suppress the comment if there is one. Pretty sure this is a bug as it didn't work like that in 1.5.X

**Comment by milimar** [comment]
![test](https://cloud.githubusercontent.com/assets/9386798/5990168/6989287e-a9a4-11e4-86b0-f9269707810b.jpg)

Yesterday I installed OC 2.0.1.2_rc and I tried to replicate your error, but It seems everything to be OK. 
 I haven't made any configurations or modifications to OC yet, I made a fresh installation for testing purposes only.

**Comment by danielkerr** [comment]
yes the notify will s only if you leave a message.

if a customers order goes reversed he should know about it

**Comment by danielkerr** [comment]
@Tangol as for your mail issue its because you have not setup your mail server.

**Comment by JAY6390** [comment]
@danielkerr What if you just want to add a note to the order? The customer still gets a notification even if the status doesn't change, which will lead to confusion. This should work the same as it always has where the email doesn't go unless you click the notify - otherwise the notify is mislabelled and irrelevant.

**Comment by danielkerr** [comment]
ok fine will change it

**Comment by Tangol** [comment]
@jay6390 Finally a person that understood my bug report.
I know i didn't setup a mail server, because i just wanted to test Opencart locally and see if it's the right thing for me.
That's the big bolded question:
"Why does the script try to email the customer if the notify box is unchecked?"

This is a bug because sometimes you just want to add notes to orders. ;)

But as Daniel said, i will stop commenting and posting bugs.
Have a good one!

**Comment by sfaragy** [comment]
Here is the real solution. Please visit this link below where you can see the live demo and you can figure it out by yourself. Screenshots also available.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=24725
