### ISSUE TITLE
Checkout - Address

### ISSUE THREAD

**Issue by Tangol** [opencart/opencart#2573]
During logged in Checkout you have `Step 2: Billing Details` and it should be `Step 2: Shipping Details`, as it creates confusion regarding the address where the package will be sent.
![shipping](https://cloud.githubusercontent.com/assets/3336728/5784314/d138c484-9dd3-11e4-81e0-bb85d685f5ba.png)

`Using OC 2.0.1.2_rc rev` https://github.com/opencart/opencart/commit/6ad153d6ba3d11f301703089a44244557a808e46

**Comment by danielkerr** [comment]
you have not picked an item which requires shippin in your screenshot!
