### ISSUE TITLE
My Account Changes

### ISSUE THREAD

**Issue by Tangol** [opencart/opencart#2574]
In the user account section, on the right menu `Address Books` should be `Address Book` (this is the correct wording), and `Newsletter` must go down one row as it should be located after `Recurring Payments` (the same as on the left menu).
![account](https://cloud.githubusercontent.com/assets/3336728/5784690/3bfead80-9dd7-11e4-94da-fa24465c6fe2.png)

`Using OC 2.0.1.2_rc rev` https://github.com/opencart/opencart/commit/6ad153d6ba3d11f301703089a44244557a808e46

**Comment by pinkslink** [comment]
in
catalog/view/theme/default/template/module/account.tpl
change:
<a href="<?php echo $newsletter; ?>" class="list-group-item"><?php echo $text_newsletter; ?></a><a href="<?php echo $recurring; ?>" class="list-group-item"><?php echo $text_recurring; ?></a>

to:
<a href="<?php echo $recurring; ?>" class="list-group-item"><?php echo $text_recurring; ?></a><a href="<?php echo $newsletter; ?>" class="list-group-item"><?php echo $text_newsletter; ?></a>

that will rearrange the list in right colum

in
catalog/language/english/module/account.php
change:
address books
to:
address book
