### ISSUE TITLE
'append' key for order history issue/irrelevant?

### ISSUE THREAD

**Issue by JAY6390** [opencart/opencart#2575]
I've been reviewing the latest code while doing some upgrades for my extensions. One of these involves adding a message to the customers order history. I notice that the admin interface on the order view sends an `append` parameter to the API - which in turn calls the API on the catalog side and also passes the `append`. It's referenced [here](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/api/order.php#L668) but I can't see that it has any purpose whatsoever in any files. In fact the only place I can find that's using it is the OpenBay code in the admin which also passes the `append` to the catalog API. Is this just an error, or is there a reason behind it? Or is this for code that will follow at some point and if so, can you explain what the reason for it is so the code I'm implementing can be forward compatible?

**Comment by danielkerr** [comment]
i removed the append functionality

**Comment by JAY6390** [comment]
@danielkerr OK so it's safe to ignore it and not use it in my code?

**Comment by danielkerr** [comment]
yep

**Comment by JAY6390** [comment]
OK great stuff
