### ISSUE TITLE
Column size change of logo and search through header.tpl

### ISSUE THREAD

**Issue by logivity** [opencart/opencart#2577]
Hi I was trying to increase the width of search bar and decrease width of logo column in opencart 2.0.1.1 by changing col-sm-4 to col-sm-3 for logo and col-sm-5 to col-sm-6. But I do not see any changes when I visit my website. Can you please help me with that.

<header>
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div id="logo">
          <?php if ($logo) { ?>
          <a href="<?php echo $home; ?>"><img src="<?php echo $logo; ?>" title="<?php echo $name; ?>" alt="<?php echo $name; ?>" class="img-responsive" /></a>
          <?php } else { ?>
          <h1><a href="<?php echo $home; ?>"><?php echo $name; ?></a></h1>
          <?php } ?>
        </div>
      </div>
      <div class="col-sm-5"><?php echo $search; ?>
      </div>
      <div class="col-sm-3"><?php echo $cart; ?></div>
    </div>
  </div>
</header>

**Comment by pinkslink** [comment]
you may find better help posting in Opencart community forums, as this is not an issue with OC.

post here:
http://forum.opencart.com/
