### ISSUE TITLE
Coupon code  bug!

### ISSUE THREAD

**Issue by amertad** [opencart/opencart#2578]
A voucher code can be used multiple times and do not expire whne limited 1 !!!
pls check this

-----------------------------------
میتوان چندین بار از یک کد تخفیف استفاده نمود در صورتی که هر کاربر فقط میتواند یکبار از آن استفاده نماید
و هر بار در هر سفارش میتواند آنرا استفاده کرده و بصورت خودکار منقضی نمیشود

**Comment by pinkslink** [comment]
for coupon code (not gift voucher) set use per customer to 1, coupon codes are working as they should, what version you using what extensions do you have ?
