### ISSUE TITLE
special price cancels out multiple quantity discount

### ISSUE THREAD

**Issue by pinkslink** [opencart/opencart#2580]
when i give an item a special price, customers no longer receive the multiple quantity discount, items are added to cart at special price regardless of quantity and discount for higher quantity

**Comment by beifloyd** [comment]
This has been discussed other times and is the same for OC 1.5.x. 
Discounts are intentionally handled this way. 
If you want to change it  you need to apply this Vqmod by uksb

<modification>
	<id>Fix Discounts wtih Specials</id>
	<version>1.0</version>
	<vqmver>1.2.3</vqmver>
	<author>uksb</author>
	<file name="system/library/cart.php">
		<operation>
			<search position="replace" offset="2"><![CDATA[				if ($product_special_query->num_rows) {]]></search>
			<add><![CDATA[if ($product_special_query->num_rows) {
					if($product_discount_query->num_rows&&$product_discount_query->row['price']<=$product_special_query->row['price']){
						$price = $product_discount_query->row['price'];
					}else{
						$price = $product_special_query->row['price'];
					}
				}]]></add>
		</operation>
	</file>
	
        <file name="catalog/controller/product/product.php">
		<operation>
			<search position="replace" offset="5"><![CDATA[foreach ($discounts as $discount) {]]></search>
			<add><![CDATA[			foreach ($discounts as $discount) {
				if((float)$product_info['special']){
					if($product_info['special']>$discount['price']){
						$data['discounts'][] = array(
							'quantity' => $discount['quantity'],
							'price'    => $this->currency->format($this->tax->calculate($discount['price'], $product_info['tax_class_id'], $this->config->get('config_tax')))
						);
					}
				}else{
					$data['discounts'][] = array(
						'quantity' => $discount['quantity'],
						'price'    => $this->currency->format($this->tax->calculate($discount['price'], $product_info['tax_class_id'], $this->config->get('config_tax')))
					);
				}
			}]]></add>
		</operation>
	</file>
        
        
</modification>

**Comment by pinkslink** [comment]
cheers, i only recently made switch from CC to OC, and use 2.0 so not really looked at anything for 1.5
