### ISSUE TITLE
Gift Vouchers, email sent to all even when only one is selected

### ISSUE THREAD

**Issue by Tea56** [opencart/opencart#2581]
In version 2.0.1.1, emails are sent to recipients of all issued vouchers, even if only one is selected.

**Comment by Tangol** [comment]
Seems to be a general issue with the mailing system. https://github.com/opencart/opencart/issues/2572

**Comment by GomDani** [comment]
Gfgvv ZztU ikk gg ln i gh hb hn.,cvghnggggggggggtgvv














guhv gg ft gg vfhuhui ih gbmv
Dne 2015 1 21 06:17 je "Tea56" <notifications@github.com>
,,,kllRlRrlRnapisal/-a:
>
> In version 2.0.1.1, emails are sent to recipients of all issued vouchers,
even if only one is selected.

**Comment by danielkerr** [comment]
@Tangol stop commenting! you didn't setup your mail server!
