### ISSUE TITLE
OC 2.0.1.1 Reports>Products>Purchased - Inflated amounts in Totals column

### ISSUE THREAD

**Issue by shalom-cohen** [opencart/opencart#2588]
When running reports to view Purchased Products, the Totals column duplicates the amounts charged.

The file responsible for this calculation is located in:
webroot / admin / model / report / product.php

The original line of code (line 34), sums up the model count, but then also multiplies the total + tax  and multiplies it with the quantity once again, inflating the results as shown below:

$sql = "SELECT op.name, op.model, SUM(op.quantity) AS quantity, SUM((op.total + op.tax) * op.quantity) AS total FROM " . DB_PREFIX . "order_product op LEFT JOIN `" . DB_PREFIX . "order` o ON (op.order_id = o.order_id)";

To correct this issue, you need to remove the second instance of multiplying by quantity as follows:

$sql = "SELECT op.name, op.model, SUM(op.quantity) AS quantity, SUM(op.total + op.tax) AS total FROM " . DB_PREFIX . "order_product op LEFT JOIN `" . DB_PREFIX . "order` o ON (op.order_id = o.order_id)";

**Comment by Tea56** [comment]
I am seeing the total inflation when editing same order. (quantity is going up and sometimes a second instance of the product gets added.) 
As i'm new to opencart and have some modifications, i'm not really sure if it's a bug, but it sounds exactly like what you're describing.

Any help would be appreciated.

**Comment by shalom-cohen** [comment]
The problem you are describing seems to be with another module of the OC system, you may want to create a completely new ticket for this one.

**Comment by Tea56** [comment]
Yeah, i already did :) Thank you!

**Comment by danielkerr** [comment]
@shalom-cohen this is not the case. I think you have your prices and tax setup wrong maybe.

**Comment by shalom-cohen** [comment]
I've reviewed the results of my findings before posting them online. I stand behind my original post. If you feel I am incorrect then I recommend you substantiate your claims.

**Comment by milimar** [comment]
I tried to check this issue myself, so I found out that shalom-cohen has right, the totals in the total column are calculated incorrectly. The issue appears only if more then one product is bought at a time. I used opencart 2.0.1.2_rc from about one week ago. I hope this helps.

**Comment by ADDCreative** [comment]
This is an issue. It was cause by https://github.com/opencart/opencart/commit/b22942a149fba290e1379b8ce2e653717320beb1, which was tying to fix another issue.

The calculation should be using op.price not op.total, assuming op.tax is the same as in 1.5.x.
```php
SUM((op.price + op.tax) * op.quantity) AS total
```
See https://github.com/opencart-ce/opencart-ce/commit/d287961327d38cb049f15cc591c3811fcc650a6d.

**Comment by LennyLip** [comment]
+1 @danielkerr , please reopen issue, 2.0.3 still  Inflated amounts
