### ISSUE TITLE
Message Error Template + Review Success Message not showing

### ISSUE THREAD

**Issue by franz2007** [opencart/opencart#2590]
hi

we just need some help. everytime a customer login to our customer login page and if they type their password incorrect, the template of our login page disappeared :( we dont know what is wrong on it. is there someone experience it? im using opencart 2.0 (i attached the image for the errors)

Another Issue: If a customer submits a product review it wont show a success message like "Thank you for your review. It has been submitted to the webmaster for approval." It does get submitted to the admin and I can see it come through but the customer cannot see any kind of success message.

hope you could help us on this error
![login](https://cloud.githubusercontent.com/assets/10559307/5853448/b1da67ca-a25e-11e4-8a4e-35ce1a871709.jpg)
![login-1](https://cloud.githubusercontent.com/assets/10559307/5853450/b1e46766-a25e-11e4-87c0-db86fa014cf5.jpg)
![changing-pass](https://cloud.githubusercontent.com/assets/10559307/5853449/b1df320a-a25e-11e4-9592-cb8a5cee7ab6.jpg)

**Comment by CoverUp** [comment]
This is a issue related to your theme, contact the theme's developer or ask in support forums. This issue tracker is only for OC's core system. So please close this issue.

**Comment by franz2007** [comment]
im not sure if its from the template that we use since i try to put back the default theme and its till show this error: https://cloud.githubusercontent.com/assets/10559307/5853450/b1e46766-a25e-11e4-87c0-db86fa014cf5.jpg

**Comment by JAY6390** [comment]
This is most likely due to you enabling HTTPS in your admin, but not updating your config.php files properly to use the new https values

**Comment by franz2007** [comment]
is it possible to get help for the steps how to fix it? i really appreciate the help :)
