### ISSUE TITLE
Error: Subquery returns more than 1 row

### ISSUE THREAD

**Issue by dtjones** [opencart/opencart#2591]
I receive the following error.

Error: Subquery returns more than 1 row
Error No: 1242
SELECT DISTINCT *, (SELECT keyword FROM oc_url_alias WHERE query = '

The error occurs if a duplicate query was added to the keyword table.
  
I think this will fix the problem.
admin\model\catalog\information.php

		$query = $this->db->query("SELECT DISTINCT *, (SELECT keyword FROM " . DB_PREFIX . "url_alias WHERE query = 'information_id=" . (int)$information_id . "' LIMIT 1) AS keyword FROM " . 
admin\model\catalog\manufacturer.php

		$query = $this->db->query("SELECT DISTINCT *, (SELECT keyword FROM " . DB_PREFIX . "url_alias WHERE query = 'manufacturer_id=" . (int)$manufacturer_id . "' LIMIT 1) AS keyword FROM " . 

admin\model\catalog\product.php

		$query = $this->db->query("SELECT DISTINCT *, (SELECT keyword FROM " . DB_PREFIX . "url_alias WHERE query = 'product_id=" . (int)$product_id . "' LIMIT 1) AS keyword FROM " .

Shouldn't all subqueries used as a column alias be limited to 1 ? 

     (SELECT column FROM " . DB_PREFIX . "table WHERE column='" . $value ."' ) AS alias
     //should be
     (SELECT column FROM " . DB_PREFIX . "table WHERE column='" . $value ."'  LIMIT 1) AS alias

please note the reason for the duplicate keyword was a modification and not opencart.

**Comment by Steinweber** [comment]
The values should be unique? Or how should one can distinguish between the first and the second value?

**Comment by dtjones** [comment]
Yea they <b><i>should</i></b> be unique and opencart does a good job preventing duplicates so you shouldn't really need to distinguish between the first and second because a duplicate <b><i>should'nt</i></b> ever exist.
<br>
I wouldn't say it was hugely important on how duplicated are handled, just that if they do exist the script can cope with it rather than throwing an error.  You could order by url_alias_id, to return either the newest or oldest matching entry. 
but the point is it should ALWAYS return 1 row.

**Comment by danielkerr** [comment]
there should be no duplicates as opencart is deleting all keywords linked to a specific product before adding just 1 back.

i think you have been playing around with the data manually.

**Comment by dtjones** [comment]
@danielkerr 
Yes you're correct it was a modification and not opencarts fault for the duplicate.
I'm aware extensions are not your concern as they are out of your control but 
Adding " LIMIT 1 " seems like a good practice.

**Comment by dvlprs** [comment]
> there should be no duplicates as opencart is deleting all keywords linked to a specific product before adding just 1 back.

Opencart might be deleting all keywords, but there's a chance some plugin will still mess this up. What do you think about making the keyword column `UNIQUE`?

It will be throwing errors for empty values though: 

> Duplicate entry '' for key 'keyword'

However, it's not obvious to me why would one keep an empty keyword in there anyway. We can, technically, write a copy of the `query` value there which can act as a placeholder, but it will still throw a duplicate entry error if that table ever starts keeping the multilingual entries, so it still seems like a bad idea. So again, the empty values shouldn't probably be there. 

What do you think about making the `url_alias.keyword` `UNIQUE`?
