### ISSUE TITLE
Opencart 2.0.1.1 problems with moving

### ISSUE THREAD

**Issue by meco2by4** [opencart/opencart#2600]
Hi,

I moved my Opencart Store from public_html/a to public_html_b and done all the correct steps, like editing config.php and so on...but when I access the new store and change things to it, it seems that it is making changes to the old one. I can'd understand why...

For example, in the new store, I access to change the theme and when I check, it changes it on the old website...

Can someone please help me with this?

**Comment by nosite** [comment]
Use the forum for support.
