### ISSUE TITLE
Add a Modification OCMOD 

### ISSUE THREAD

**Issue by danelsan** [opencart/opencart#2604]
When add a modification xml,
there aren't record into modification menu (name, author, version, ecc..)
But the modification is active and give result.

Thanks

**Comment by TLEwebdevs** [comment]
I have posted about this in OpenCart forums with quick and dirty workarounds and a list of problems and some of the causes -

http://forum.opencart.com/viewtopic.php?f=191&t=142296

I certainly hope that Daniel and the rest of the core devs will take a serious look at this as it's a deal breaker when choosing between different carts with a click-and-go extensions installation system.  Even with the OC fanbase, it could be the deal breaker when deciding between versions 1.x and 2.x
