### ISSUE TITLE
Product edit after upgrade

### ISSUE THREAD

**Issue by danelsan** [opencart/opencart#2605]
I do an upgrade from oc 1.5.6.4 to 2.0.1.1 and all run well.
When I go to edit e product I see this errors:
- model not visible and give error
- Tax not visible
- Quantity is 1 for all products
- Price not visible

I don't see also into Link the related products, but into frontend there are.

All this data is correct into database but incorrect at first edit.

**Comment by beifloyd** [comment]
I don't think this is a bug of OC2.0 for the below reasons:
Fresh install works.
An  official script to upgrade from 1.5 to 2.0 has not been released.
On top of that, I have migrated from 1.5 to OC 2.0 and everything works for me.

I would suggest to make sure the upgrade process is correct.

**Comment by danelsan** [comment]
The upgrade that i done it's into the release 2.0.1.1.
No other scripts i ran
