### ISSUE TITLE
Google Analytics code not updating from admin settings config

### ISSUE THREAD

**Issue by Wetronic** [opencart/opencart#2611]
Login to your Google Analytics account and after creating your web site profile copy and paste the analytics code into this field." id="input-google-analytics" class="form-control">

This message is appearing on my webshop, when I fill in the script code of the google analytics. It won't save it in the configuration. (it stores it in the database, but seems it's not picking it up at the shop local.

Also noticed that a lot of other shops has this error on top of their sites.

Link: www.wetronic.nl/
Shop originally 1.5 updated to 1.5.6.4 and then to 2.0 with 2.0.1.1 as final step.

**Comment by danielkerr** [comment]
your issue is related to the extension you installed. contact the extension developer, my staff or the forums
