### ISSUE TITLE
HTML module Uninitialized string offset: 1

### ISSUE THREAD

**Issue by opencart-russia** [opencart/opencart#2614]
https://github.com/opencart/opencart/blob/master/upload/admin/controller/module/html.php#L99
Notice: Uninitialized string offset: 1

--- template --- isset($module_description[$language['language_id']]['description'])
--- controller --- $data['module_description'] = '';   ISSET = TRUE !!!!!!!! string(0)

**Comment by Steinweber** [comment]
Unfortunately, I can not see any errors or bugs

**Comment by opencart-russia** [comment]
to see the warning, it is not enough just to check. 
https://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting

**Comment by danielkerr** [comment]
i can not relicate. i think you may have odl data still in the system. the module system was updated recently. try resaving.

**Comment by danielkerr** [comment]
error reporting is on full by default in opencart.
