### ISSUE TITLE
Mail password is HTML encoded

### ISSUE THREAD

**Issue by pcfreak30** [opencart/opencart#2616]
Recently had a client who had & symbols in their password. Debugging showed SMTP getting passed &amp;. Mail passwords should not be html encoded.

This is OC 2.

**Comment by Steinweber** [comment]
The problem is the request class. 
https://github.com/opencart/opencart/blob/master/upload/system/library/request.php#L26

**Comment by pcfreak30** [comment]
Ok, then the mail class needs to decode htmlspecialchars before sending the password.

**Comment by danielkerr** [comment]
@Steinweber the request class is fine. if it did not convert the html into its code equivalent sites would be hackable!
