### ISSUE TITLE
openbay (PHP Notice:  Undefined index: category_id)

### ISSUE THREAD

**Issue by dtjones** [opencart/opencart#2618]
<h6>?route=openbay/ebay/create</h6>
The ajax request to search the ebay catalog (admin/index.php?route=openbay/ebay/searchEbayCatalog) posts 'categoryId' 

    data: { categoryId: cat, page: 1,  search: qry },    
but the model tries to use 'category_id'

		$response = $this->model_openbay_ebay_product->searchEbayCatalog($this->request->post['search'], $this->request->post['category_id']);

@jamesallsup

**Comment by dtjones** [comment]
Could not load mode .../admin/model/tool/event.php!

**Comment by jamesallsup** [comment]
This has now been patched on OpenBay Pro repo.

https://github.com/openbaypro/OpenBay-Pro/commit/b66ecac2a7083f67a9ad27c9cc714bc69a69beec

Thanks.
