### ISSUE TITLE
Opencart Problem

### ISSUE THREAD

**Issue by randiprosl** [opencart/opencart#2619]
Hi there,
i have few problems about opencart.

1. if i am using a theme, can you tell me, can we sort orders by the ordered CITY of the buyer?

2. what will happen if a sold product is money back, and where will be gone the product ? like think, what i delivered item is broken and customer re-sending it to me.. then i am going to refund money...
then that item? do we have some category call damaged items or something?

3.in  a related product listing in product details page, can we put our desired category? , like., Free Delivery Items or something...

Please send me a answers to these problems asap
thank you.

**Comment by milimar** [comment]
Hello randiprosl. As I can see, you have just registered at github, so I would like to inform you that this is a place for bug reports only related to the core of opencart. You can find a lot of tutorials about opencart on internet, or / and use the community forum to ask questions. I hope this information is helpful to you. Regards

http://forum.opencart.com/
