### ISSUE TITLE
friends Goods does not see the table , please help

### ISSUE THREAD

**Issue by costanza20** [opencart/opencart#2621]
Fatal error: Uncaught exception 'ErrorException' with message 'Error: Table 'oc_bicak.oc_product_tab' doesn't exist<br />Error No: 1146<br />DELETE FROM oc_product_tab WHERE product_id = '30'' in /home/yatagankesicielaletleri.com/httpdocs/system/database/mysqli.php:41 Stack trace: #0 /home/yatagankesicielaletleri.com/httpdocs/vqmod/vqcache/vq2-system_library_db.php(20): DBMySQLi->query('DELETE FROM oc_...') #1 /home/yatagankesicielaletleri.com/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php(332): DB->query('DELETE FROM oc_...') #2 /home/yatagankesicielaletleri.com/httpdocs/vqmod/vqcache/vq2-admin_controller_catalog_product.php(130): ModelCatalogProduct->deleteProduct('30') #3 [internal function]: ControllerCatalogProduct->delete() #4 /home/yatagankesicielaletleri.com/httpdocs/vqmod/vqcache/vq2-system_engine_front.php(42): call_user_func_array(Array, Array) #5 /home/yatagankesicielaletleri.com/httpdocs/vqmod/vqcache/vq2-system_engine_front.php(29): Front->execute(Object(Action)) #6 /home/yatagankesicielaletleri. in /home/yatagankesicielaletleri.com/httpdocs/system/database/mysqli.php on line 41

friends Goods does not see the table , please help

**Comment by milimar** [comment]
Hello costanza20. As I can see, you have just registered at github, so I would like to inform you that this is a place for bug reports only related to the core of opencart. You can find a lot of tutorials about opencart on internet, or / and use the community forum to ask questions and obtain help. I hope this information is helpful to you. Regards

http://forum.opencart.com/
