### ISSUE TITLE
Email regex

### ISSUE THREAD

**Issue by Golling** [opencart/opencart#2627]
Hello,

The current regex email validation allow monstrosity like :
- abc;def@domain.com
- abc@def@domain.com
- abc/def@domain.com

My regex knowledge is very limited. I can't suggest a better one.

Thanks !

**Comment by danelsan** [comment]
Where is the problem,
into registration of customers?

**Comment by Golling** [comment]
account/edit
account/forgotten
account/login
account/register
affiliate/edit
affiliate/forgotten
affiliate/login
affiliate/register
checkout/login
checkout/register

Every page where the email is required in a form.

Yesterday, a payment failed because of the email format. :(

**Comment by danelsan** [comment]
I tested into last commit.
The problem is for email

abc/def@domain.com

The other is not valid.
What version you have?

**Comment by Golling** [comment]
V1.5.5.1
```
/^[^\@]+@.*\.[a-z]{2,6}$/i
```
V2.0+
```
/^[^\@]+@.*.[a-z]{2,15}$/i
```

Both allowed the same email validation monstrosity.
