### ISSUE TITLE
Reports>Sales>Orders bug 

### ISSUE THREAD

**Issue by Lyp8801** [opencart/opencart#2630]
The No.Products and Tax value is wrong since the there have 34 order but only 2 product and 1 taxed, it always show the result of first data, only correct when i filter the result Group by days. Is that anyone met and solved this problem? Please help, thanks for anyone who trying to solve this problem.

![capture](https://cloud.githubusercontent.com/assets/10704739/5972655/35f3f078-a898-11e4-8196-285664a4b426.JPG)

**Comment by tvanbeek** [comment]
Fix: in admin/model/report/sale.php change:

```sql
SELECT MIN(o.date_added) AS date_start,
MAX(o.date_added) AS date_end,
COUNT(*) AS `orders`,
(SELECT SUM(op.quantity) FROM `order_product` op WHERE op.order_id = o.order_id GROUP BY op.order_id) AS products,
(SELECT SUM(ot.value) FROM `order_total` ot WHERE ot.order_id = o.order_id AND ot.code = 'tax' GROUP BY ot.order_id) AS tax,
SUM(o.total) AS `total`
FROM `order` o
WHERE o.order_status_id > '0'
AND DATE(o.date_added) >= '2015-01-29'
AND DATE(o.date_added) <= '2015-01-30'
GROUP BY YEAR(o.date_added)
ORDER BY o.date_added DESC
LIMIT 0,100
```

to:

```sql
SELECT MIN(o.date_added) AS date_start,
MAX(o.date_added) AS date_end,
COUNT(*) AS `orders`,
SUM((SELECT SUM(op.quantity) FROM `order_product` op WHERE op.order_id = o.order_id GROUP BY op.order_id)) AS products,
SUM((SELECT SUM(ot.value) FROM `order_total` ot WHERE ot.order_id = o.order_id AND ot.code = 'tax' GROUP BY ot.order_id)) AS tax,
SUM(o.total) AS `total`
FROM `order` o
WHERE o.order_status_id > '0'
AND DATE(o.date_added) >= '2015-01-29'
AND DATE(o.date_added) <= '2015-01-30'
GROUP BY YEAR(o.date_added)
ORDER BY o.date_added DESC
LIMIT 0,100
```

so basically the two subqueries need to be surrounded by SUM

**Comment by Lyp8801** [comment]
It's work, thanks.

**Comment by tvanbeek** [comment]
Made a free OCMOD so you don't have to change the core files
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=20715

**Comment by JAY6390** [comment]
Why not submit a pull request instead so this is fixed for everyone by default?
