### ISSUE TITLE
Opencart Order Issue in back end.

### ISSUE THREAD

**Issue by Saikat29** [opencart/opencart#2636]
Hi I have been completed confused and scared. I have been trying to solve this issues for a long time.

1. When i try to process an order (Chrome browser) it says syntax error. unexpected end of inout
2. When i try to process an order (Firefox) it says SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data.

I have tried the following
1. Changing the API user
2. Disabling the mod_security
3. .htpasswords - file is empty
4. .htaccess  have setup some changes
5. Data base AIP config i made some changes as well,

But no luck. 

i have crossed y go live date for my store. any help to revolve this issue would be greatly appreciated.

thanks,
Saikat

**Comment by danielkerr** [comment]
check your host allows for loopback using curl

if so change the curl url to ip or a different domain

**Comment by Saikat29** [comment]
I would really appreciate if you can explain me how to make this change? and where to make this change?

thanks in advance.
Smit

**Comment by Saikat29** [comment]
Daniel, i would appreciate if you can help me with more information on this.

Regards,
Saikat

**Comment by Saikat29** [comment]
Daniel, they do loopback useinf curl.

where to change the CURL to IP/ different domain.

Why different? why not my storedomain name?

**Comment by Saikat29** [comment]
I found the same issues the opencart demo portal. Can someone help me to resolve this issue?

Login to OpenCart demo portal and try to edit any of the pending orders from back end. (Tested in chrome)
http://demo.opencart.com/admin/index.php?route=sale/order/edit&token=daf6996203721d2f8a3cfeb16fb3759e&order_id=1117

**Comment by danielkerr** [comment]
@Saikat29 the demo has its function disabled to stop people hacking it! 

many people manage their orders no problem! so this means its server specific!

**Comment by Saikat29** [comment]
Daniel,

my hosting service provider failed to extend their support for this. So i
would like to know if i can update the latest release. Because i have
2.0.0.0 can i update to 2.0.1.1?

thanks,
Saikat
