### ISSUE TITLE
 filter module opencart not working

### ISSUE THREAD

**Issue by udhayavanan** [opencart/opencart#2638]
Hi developers,
   I am troubling to fix the following issue, I installed Megapro filter extension in my Website Opencartv1.5.6.3. But it not works as when i select any filter it load ajax for few seconds and redirect to my sql error as : 
            Fatal error: Uncaught exception 'ErrorException' with message 'Error: Query execution was interrupted<br />Error No: 1317 Connection Lost or mysql_server gone away command cannot run out. 

   So I turned to get way there for filter module in opencart I add filter group and filters. also add filters in products. But still i cannot get result. Need a guide asap. 
TIA
Regards,
Udhayavanan.S

**Comment by danielkerr** [comment]
congratulations

**Comment by garudacrafts** [comment]
Be sure to set the Filters on Categories, as well as Products. This is commonly missed. 

Please direct such questions to http://forum.opencart.com/ going forward. GitHub is for bug reports, not general support questions.

**Comment by udhayavanan** [comment]
thank you  danielkerr and garudcrafts.
