### ISSUE TITLE
Maintenance mode should be triggered when important modifications are missing

### ISSUE THREAD

**Issue by dtjones** [opencart/opencart#2647]
During modification refresh It is likeley on a high traffic site that a request or two will slip through before the refresh has completed.
I would prefer my users to see a custom maintenance page or a custom 404 rather than a distorted or less than functioning page.

    //just before files are deleted, if config settings say maintenance mode is off then turn it on 

    if(!$this->config->get('config_maintenance')){
        $this->load->model('setting/setting');
        $this->model_setting_setting->editSettingValue($code = 'config', $key = 'config_maintenance', $value = 1) ;
    }

    // Clear all modification files
    ....
    
    ....
        // Log
        $log[] = '----------------------------------------------------------------';				
    }

    //just after modifications are complete, if config settings say maintenance mode is off then turn it back off.

    if(!$this->config->get('config_maintenance')){
        $this->model_setting_setting->editSettingValue($code = 'config', $key = 'config_maintenance', $value = 0) ;
    }
    // Log
    $ocmod = new Log('ocmod.log'); 

     foreach ($xml as $xml) {

**Comment by danielkerr** [comment]
very good point

**Comment by danielkerr** [comment]
i'm assuming this was an issue for a site you have setup

**Comment by dtjones** [comment]
I believe it might be an issue when put into production.
The majority of the time when people click refresh will be to activate their newest uploaded modification. 
Could we have a third action button in the modification list that allows the refresh of individual modifications?
