### ISSUE TITLE
Errors in customer admin not working well

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#2649]
In admin customer form must change:

`$('#tab-general .tab-content').prepend(html);`

to

`$('#tab-general .tab-content').append(html);`

If is an existing address and you add one new and errors appear, it applies to the wrong address.

and missing:

`<?php if (isset($error_address[$address_row]['postcode'])) { ?>`
`<div class="text-danger"><?php echo $error_address[$address_row]['postcode']; ?></div>`
`<?php } ?>`

and

`<option value=""><?php echo $text_none; ?></option>`

in zone_id.

**Comment by danielkerr** [comment]
serious don't know how some of this stuff got missed out
