### ISSUE TITLE
Voucher can be used more than its value

### ISSUE THREAD

**Issue by petestewartnz** [opencart/opencart#2653]
Vouchers can be used to pay for an order more than its vouchers value amount if the order status hasn't been changed to processing or complete.

Example:
I have a $100 voucher. I place an order for $90 and use the voucher, the order costs me nothing. 
I place another order immediately for $90 and use the same voucher, again the order costs me nothing as the voucher hasn't been applied to the first order...

**Comment by danielkerr** [comment]
so make sure the order status are setup properly.
