### ISSUE TITLE
Reports product viewed. wrong method used, corrected method was deleted.

### ISSUE THREAD

**Issue by dtjones** [opencart/opencart#2656]
The percentage is really wrong on the products viewed reports because it uses the total amount of products that have been viewed. rather than the sum of all product viewed. 
The wrong method had been used resulting in the unused(correct) method being deleted. 

Admin ControllerReportProductViewed index()

     //this is the wrong method, this is used for pagination 
    $product_viewed_total = $this->model_report_product->getTotalProductsViewed();

    //correct method (this has been deleted)
    $product_views_total = $this->model_report_product->getTotalProductViews();

		$results = $this->model_report_product->getProductsViewed($filter_data);

		foreach ($results as $result) {
			if ($result['viewed']) {
                                //wrong variable used. should be $product_views_total
				$percent = round($result['viewed'] / $product_viewed_total * 100, 2);
			} else {
				$percent = 0;
			}
		}

Admin ModelReportProduct 

//this method needs adding back. 

    	public function getTotalProductViews() {
		$query = $this->db->query("SELECT SUM(viewed) AS total FROM " . DB_PREFIX . "product");

		return $query->row['total'];
	}

**Comment by danielkerr** [comment]
cheers
