### ISSUE TITLE
Review Does not give proper message

### ISSUE THREAD

**Issue by guidea1** [opencart/opencart#2657]
I am using Opencart 2.0.0.0, and has vmod installed with SEO enabled. Other parts of the application seems to be working fine, but when review is posted, no success message shows up and Captcha image just refreshes.  

The review is being saved in database for review, but from the user's stand point, it doesn't look like the review is being saved completely. 

Please help.

Thanks,

**Comment by danielkerr** [comment]
i think the issue has been fixed on github already

**Comment by guidea1** [comment]
Could you please point to where the change is and how I can update?  Thanks

**Comment by guidea1** [comment]
Which commit has the change?
