### ISSUE TITLE
Confirm #2636

### ISSUE THREAD

**Issue by Steinweber** [opencart/opencart#2659]
I can confirm the Problem from #2636
The Problem isn´t the loopback. The session data "cookie" isn´t set in the check on Line 2443
```php 
if (isset($this->session->data['cookie']) && isset($this->request->get['api'])) {
```
The next problem is the missing else on this if
```php
            $json = curl_exec($curl);
            curl_close($curl);
}
//$json is now just an empty array. Set
else{
            $json = json_encode(array('error' => 'WTF is $session->data[cookie]??'));
        }
//will remove the problem
$this->response->addHeader('Content-Type: application/json');
$this->response->setOutput($json);
```
I could not found any usage of $session->data['cookie'] in opencart. Just in [openbay](https://github.com/opencart/opencart/blob/c04c68ac623d0de79aa1733b4f7eb40b3e81c7bd/upload/admin/model/openbay/openbay.php)

What should be the content of cookie?

**Comment by danielkerr** [comment]
i donmt need you to confirm anything! this is not a support tracker!

use the forum.
