### ISSUE TITLE
Undefined index: recurring_id

### ISSUE THREAD

**Issue by sud0074** [opencart/opencart#2662]
Notice: Undefined index: recurring_id in /home/xyz.com/public_html/abc/admin/model/catalog/product.php on line 272.
Code-
if (isset($data['product_recurrings'])) {
			foreach ($data['product_recurrings'] as $recurring) {
				$this->db->query("INSERT INTO `" . DB_PREFIX . "product_recurring` SET `product_id` = " . (int)$product_id . ", customer_group_id = " . (int)$recurring['customer_group_id'] . ", `recurring_id` = " . (int)$recurring['recurring_id']);
			}
		}
how do i solve this problem plz help me

**Comment by danielkerr** [comment]
can not replicate!
