### ISSUE TITLE
g-recaptcha error on submission (review, contact, return)  

### ISSUE THREAD

**Issue by markoRs** [opencart/opencart#2663]
On product pages - when posting reviews and omitting name, or rating, or review, in all cases only error for captcha is shown. I guess it has something to do with: 
 
data: 'name=' + encodeURIComponent($('input[name=\'name\']').val()) + '&text=' + encodeURIComponent($('textarea[name=\'text\']').val()) + '&rating=' + encodeURIComponent($('input[name=\'rating\']:checked').val() ? $('input[name=\'rating\']:checked').val() : '') + '&captcha=' + encodeURIComponent($('input[name=\'captcha\']').val()),

**Comment by markoRs** [comment]
Just to add, new captcha doesn't allow to post a review, return, or enquiry (contact page). It always report error, verify again. Tested on 2.0.1.1 and 2.0.1.2 on local server. Google says this should work on localhost.

**Comment by danielkerr** [comment]
i think this is because you are on localhost, php can not get your real IP. only enable captcha when you have a domain

**Comment by markoRs** [comment]
Hi Daniel,

Tested live and it's not working. I don't know if the code below helps (contact.php). But captcha always reports error, cannot verify. 
if (!$json['success']) {
				$this->error['captcha'] = $this->language->get('error_captcha');
