### ISSUE TITLE
Watermark error

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#2678]
I install OC 2.0.1.2_rc and add watermark to images:
`
$image = new Image(DIR_IMAGE . $old_image);
`
`
$image->watermark(DIR_IMAGE . 'no_image.png');
`
`
$image->resize($width, $height);
`
`
$image->save(DIR_IMAGE . $new_image);
`
in tool/image.php. And error occurs. Is this problem in OC or in server / PHP.

Apache 2.4.9
PHP 5.5.12

![watermark_error](https://cloud.githubusercontent.com/assets/3872726/6200469/0c4e854c-b47a-11e4-8564-cd0f5e0653a8.jpg)

**Comment by icoco** [comment]
seem I face the same problem ... after install the version site and try to login to admin panel, but failed....   I trace into the code, it locate the code  'class ModelToolImage' , accurate line 29...  I  try to remove the no image "/image/no_image.png", then I can login the admin panel, but failed to use the image upload dialog box ....

**Comment by danielkerr** [comment]
watermarks are not in the default opencart code

**Comment by GomDani** [comment]
No problem, I solve this by myself.
