### ISSUE TITLE
Cannot use string offset as an array

### ISSUE THREAD

**Issue by hexagonn** [opencart/opencart#2681]
Hello,

I got an issue with open cart and custom fields added to addresses.

I add a (one ore more) custom fields to the address, a a new adress to the user, add a product to the cart, checkout with it and the new address. So far so good.

I can go and see details about the order, and i can see the custom fields added to both the payment & the shipping address.

When i go and look at that customer's details, o the addresses div ( the ones you select from the left links on the general tab ) i get the following error:

```
Fatal error: Cannot use string offset as an array in /home/raul/Development/fresh_opencart/admin/view/template/sale/customer_form.tpl on line 501
```

I tried this with two open cart installs. One modified, and one fresh. The version i am using is 2.0.1.1

**Comment by danielkerr** [comment]
this has already been fixed on the master branch.
