### ISSUE TITLE
.htaccess "download" wrong rule

### ISSUE THREAD

**Issue by Steinweber** [opencart/opencart#2684]
RewriteRule ^download/(.*) /index.php?route=error/not_found [L]
should be
RewriteRule ^system/download/(.*) /index.php?route=error/not_found [L]

**Comment by ADDCreative** [comment]
Also need to remove the / in front of index.php. See https://github.com/opencart-ce/opencart-ce/commit/855f6ea678c3217834bbab862baeaab4fa0305c0.
