### ISSUE TITLE
Two installations under the same domain has huge security issue

### ISSUE THREAD

**Issue by eugeniopacheco** [opencart/opencart#2686]
Hi,

I noticed that if I have two installations of Opencart under the same domain using two different subdirectories and two different databases, if I login as admin to one of the installations, I can login to the other simply by changing the subdirectory under the URL and keep the same token.

I changed the database user table to add a Token field which then is matched against the session token. This way it works fine. Shouldn't it be already a default method as it's safer?

In order to accomplish this, I added the field token to the oc_user table in the database and changed  both admin/controller/common/login.php (methods index and check) and system/library/user.php (method login)

Best regards,

Eugenio Pacheco

**Comment by danielkerr** [comment]
read the instruction dummy!

**Comment by danielkerr** [comment]
you can not have more than one installation under the same domain name unless its a sub domain!
