### ISSUE TITLE
Module - HTML Content Module

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#2688]
Hello.

I got this error in v2.0.1.1.

<b>Notice</b>: Uninitialized string offset: 1 in <b>admin\view\template\module\html.tpl</b> on line <b>49</b>
Notice: Uninitialized string offset: 1 in admin\view\template\module\html.tpl on line 55

**Comment by munirasim** [comment]
What you did that may caused this error? I am using the same version and the module is working fine.

**Comment by faca5** [comment]
Hello.

Nothing! I just install fresh version.

**Comment by munirasim** [comment]
Are you using one language or more than one in Opencart? And what language it is?

**Comment by faca5** [comment]
Hello.

I add one language.

Error appear on English.

Please check:
http://postimg.org/image/vtffdx65j/

**Comment by munirasim** [comment]
You may remove the English language and try re-installing it. If it solves your issue, may try re-installing Opencart
