### ISSUE TITLE
Order History showing other customers' information

### ISSUE THREAD

**Issue by jessicamidland** [opencart/opencart#2689]
Hi, we have an order history security issue.  When a customer signs into their account on our website and views their order history, it is showing previous customers' information including name, address, phone number and order history.  This is a HUGE problem.  Please advise.  

Thank you, 
Jessica

**Comment by munirasim** [comment]
What version of Opencart it is? Do you have custom theme installed? Did you install some new extention? Please share more information.

**Comment by jessicamidland** [comment]
It is OpenCart 5.6.  We do have a custom theme, the Themeforest Journal 2 theme and none of our extensions are new.


Jessica Gilbreath
Midland Information Systems. Inc.
Office: (407) 571 3136
Cell: (954) 871 9278
midlandinfosys.com<http://midlandinfosys.com>



On Feb 20, 2015, at 10:10 AM, munirasim <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of Opencart it is? Do you have custom theme installed? Did you install some new extention? Please share more information.

**Comment by munirasim** [comment]
Customers' own order history is included in the record or not? Secondly, is it the history of all the previous customers or a few ones?

**Comment by jessicamidland** [comment]
Yes, the customers' own order history is included, but the history of other customers varies.  For example, the customer on my test account is different from another employee's test account.

**Comment by munirasim** [comment]
I just checked that there is no such know issue with Opencart 1.5.X. It is most likely that problem resides with your theme Journal 2. You may revert to default theme for a while and test again (You can do so in your testing environment) .

**Comment by jessicamidland** [comment]
Thank you

**Comment by munirasim** [comment]
Further tested in my development environment Opencart 1.5.6.4 with default theme and there is no such issue.

**Comment by kanenas** [comment]
Tested in my development environment Opencart 1.5.6.5_rc with default theme & Journal v.2.4.6 with no such issue.
@jessicamidland you need to tell us which version of Journal 2 do you use and which extensions (make a list).

**Comment by jessicamidland** [comment]
Hi, we are using the Journal v.2.4.6 as well.  

Here is the list of our current extensions:

VQMod
Ultimate Shipping Pro 
Smart Search 
Redirect Manager
Multi-Product RFQ
Form Builder
Extra Tabs
Ask a question about product - advanced
Admin Quick Edit Pro
Zoho Live Desk

**Comment by danielkerr** [comment]
because you have been deleting stuff directly using sql or phpmyadmin

**Comment by jessicamidland** [comment]
I have not be using either of those. That does not help me solve my issue, Daniel.

**Comment by jessicamidland** [comment]
I understand what you are saying, but there’s no reason for me to delete anything manually ….and since it takes some effort and purpose to edit the database via phpadmin, then I’d say they are trying to blame everything except the obvious. The mod doesn’t work well with the RFQ. The only thing PHPAdmin is used for is to make backup copies of the database. Nothing is overwritten or changed.

**Comment by jessicamidland** [comment]
Could there be any other factors contributing to this error?
