### ISSUE TITLE
Unable to install Opencart on ISS8

### ISSUE THREAD

**Issue by darkwood-studios** [opencart/opencart#2690]
The installation of Opencart failed on ISS8 because of writing permissions

if (!is_writable(DIR_OPENCART . 'image/catalog'))  fails because the constant DIR_OPENCART  contains an incorrect slash at the end

example:
real path to opencart: D:\inetpub\server.com\
DIR_OPENCART constant: D:\inetpub\server.com/

so is_writeable returns false because of the wrong slash

**Comment by munirasim** [comment]
For Windows make sure the following folders and files permissions allow Read and Write. 
image/ 
image/cache/ 
cache/ 
download/ 
config.php 
admin/config.php

Right click the folder with the web files in it, and select Security Tab to modify the permissions.

**Comment by darkwood-studios** [comment]
thanks for the fast reply. i checked the premissions and the user has all permissions to read and write.

i made some test.

the actual code does this:
is_writable(DIR_OPENCART . 'image/catalog') in my example its qual to is_writable('D:\inetpub\server.com/image/catalog') // FALSE

here you can see the wrong slashes

if I correct the slashes in the code to is_writable('D:\inetpub\server.com\image\catalog') I get TRUE

so the folder is writeable, but the code is wrong

**Comment by danielkerr** [comment]
slash on windows does not matter.
