### ISSUE TITLE
"E-Mail Message required!" when I try to email newsletter

### ISSUE THREAD

**Issue by greghouston** [opencart/opencart#2693]
I am getting the following error when I try to email a newsletter. "E-Mail Message required!"

Note that the contact form is sending emails properly, and I am receiving emails notifications for new customers and sales. It seems to be an issue specifically with the newsletter.

**Comment by danielkerr** [comment]
this has already been fixed. check the repository of ask on the forums for the fix.

**Comment by greghouston** [comment]
What does the "// Summer not fix" comment mean?
