### ISSUE TITLE
 Error when attempting to create new customer from admin

### ISSUE THREAD

**Issue by greghouston** [opencart/opencart#2694]
I get this error when attempting to create a new customer from the admin interface:

Notice: Undefined index: custom_field in [...]/html/admin/model/sale/customer.php on line 4Warning: Cannot modify header information - headers already sent by (output started at [...]/html/admin/index.php:80) in [...]/html/system/library/response.php on line 12

**Comment by rafaelfranco** [comment]
I cannot simulate this error
