### ISSUE TITLE
Had to add column to table for PayPal Express Checkout

### ISSUE THREAD

**Issue by greghouston** [opencart/opencart#2695]
Using phpMyAdmin, I had to add a column in the database with the name, "modified" to "paypal order" in order for PayPal Express Checkout to work properly.

**Comment by jamesallsup** [comment]
modified was renamed to date_modified a while back, all usages of the modified variable should have been changed too. 

I cannot find any usages of it and doesn't seem to be a global issue..

If you do have any further issues with it please post your version number, any errors you get and also where the errors occur.

Thanks.
