### ISSUE TITLE
Quantity is multiplied in admin order form

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#2703]
Fresh install 2.0.1.2_rc

In admin order form when add new order or correct one, when move from Customer Details to Products and back every n-times products quantity is multiplied.

But when move out from `$('#button-customer').on('click', function() {});` ajax the second ajax and put it in separate function and then if no error calling the function, the multiplication is stopped and work OK.

**Comment by danielkerr** [comment]
not for me it doesn't!
