### ISSUE TITLE
Cart in multistore mode

### ISSUE THREAD

**Issue by helgvor-stoll** [opencart/opencart#2704]
Hello,

I have 2 stores store_1 & store_2 on the same installation (V 2.0.1.1) and each store is opened on a new tab of Chrome.
In store_1, I put product_1 (quantity_1) in the cart and in store_2 I put product_2 (quantity_2) in the other cart.

When I want to checkout one cart (for example the cart_2), I login and I find the product_2 with quantity_2 in the cart (that is correct). But when I want to checkout the first cart (I consider that I didn't pay the cart_2 yet), I login and then I find product_1 (quantity_1) and product_2 (quantity_2) in cart_1. That is not good.

Could you please fix this.

Thanks in advance,

Best regards.

Helgvor STOLL

**Comment by helgvor-stoll** [comment]
Hi,

In fact, I think it comes from the file: /system/library/customer.php (line 33):
$this->db->query("UPDATE " . DB_PREFIX . "customer SET cart = '" . $this->db->escape(isset($this->session->data['cart']) ? serialize($this->session->data['cart']) : '') . "', wishlist = '" . $this->db->escape(isset($this->session->data['wishlist']) ? serialize($this->session->data['wishlist']) : '') . "', ip = '" . $this->db->escape($this->request->server['REMOTE_ADDR']) . "' WHERE customer_id = '" . (int)$this->customer_id . "'");

The cart is registered in the database when a customer log in but in multistore configuration, when a customer have 2 cart, they are cumulated in the second login.

Best regards,

Helgvor.

**Comment by sculptex** [comment]
I second this. It defeats the object of having multicart with selected products as it allows products to transfer into carts of other stores where that product is not even enabled! This is a huge problem and of course should not be possible!
Its debatable whether it should be allowed to transfer products which are enabled on both stores, as I guess this ability could be useful but I think should be an option selected in admin.

**Comment by JeffroDH** [comment]
I vote Aye. Transferring products between carts in a multi-store configuration should be a deliberate choice at the product level (i.e., you want product A and B to transfer between stores 1 and 2, but not store 3), and not default behavior.

**Comment by kimhoo** [comment]
Luckily I've been busy with a client's case for this and preparing to release a mod that fully integrates carts from shop A into shop B and vice versa. It also allows "Single Sign-On": once logged into shop A, one is also logged into shop B. If some product is put into cart at shop A, it pops up into the cart at shop B as well, but when it isn't found in shop B, it links back to shop A when clicked. Carts can be checked out in any shop configured. I'm thinking of releasing this mod and adding the possibility to configure in the backend whether carts and logins should be fully integrated or be fully seperated over stores configured.

**Comment by danielkerr** [comment]
im closing this as i have updated the cart system to use the db. now if you complete one order the cart will be deleted on both stores.

if you find other issues open another issue.
