### ISSUE TITLE
Newsletter success AJAX stopped prematurely

### ISSUE THREAD

**Issue by greghouston** [opencart/opencart#2707]
After sending a newsletter, the success message first said:

Your message has been successfully sent to 0 of 38 recipients!

It updated to:

Your message has been successfully sent to 10 of 38 recipients!

And then:

Your message has been successfully sent to 20 of 38 recipients!

It stopped there. Does that mean 18 recipients didn't get a newsletter or did the AJAX just fail to continue updating the success message? What would cause it to stop at 20?

**Comment by greghouston** [comment]
I got 15 instances of the following error in the error log:

2015-02-22 13:46:19 - PHP Warning:  mail() [<a href='function.mail'>function.mail</a>]: Could not execute mail delivery program '/usr/sbin/sendmail -t -i ' in [...]/html/system/library/mail.php on line 162

**Comment by danielkerr** [comment]
thats an issue with your server
