### ISSUE TITLE
Class for modules in column-left and -right

### ISSUE THREAD

**Issue by PprMkr** [opencart/opencart#2710]
When adding module to column-left or -right class remains:
class="col-lg-3 col-md-3 col-sm-6 col-xs-12"
Actually it should be col-xs-12, making it 100% width.

Solution could be:
Add position to controllers column-left, column-right, content-top and content-bottom after getting setting_info :
$setting_info['position'] = 'content_top';

In module controllers set variable 'position':
$data['position'] = $setting['position'];

In templates:
($position == 'content_top' || $position == 'content_bottom' )?'col-lg-3 col-md-4 col-sm-6 col-xs-12':'col-xs-12'

Try ocmod: http://forum.opencart.com/viewtopic.php?f=107&t=139471&p=545466#p545466

**Comment by veksen** [comment]
CSS knows the position, you don't need to pass it through the controller.

**Comment by danielkerr** [comment]
im closing this as it seems to work fine for me when i put featured products in a column
