### ISSUE TITLE
Order History showing other customers' information

### ISSUE THREAD

**Issue by jessicamidland** [opencart/opencart#2714]
Hi, we have an order history security issue. When a customer signs into their account on our website and views their order history, it is showing previous customers' information including name, address, phone number and order history.  I am using  OpenCart 5.6, the Themeforest theme Journal v.2.4.6 (which has been ruled out as the cause) and these extensions: 

VQMod
Ultimate Shipping Pro 
Smart Search 
Redirect Manager
Multi-Product RFQ
Form Builder
Extra Tabs
Ask a question about product - advanced
Admin Quick Edit Pro
Zoho Live Desk

We are NOT deleting items directly using sql or phpmyadmin and cannot seem to find the culprit for this issue.  

Please advise. 

Thank you, 
Jessica

**Comment by garudacrafts** [comment]
This is a problem with your installation, not OpenCart. No one else has reported such an issue and it cannot be reproduced (https://github.com/opencart/opencart/issues/2689). I suggest you close this issue and hire a developer to investigate. GitHub is for bug tracking, not personal support.

**Comment by danielkerr** [comment]
because you have been deleting stuff directly using sql or phpmyadmin
