### ISSUE TITLE
Wrong folder permissions after extension (ftp) install

### ISSUE THREAD

**Issue by stefanhuber** [opencart/opencart#2715]
After using the extension installer for an extension zip, the files inside the upload folder are moved to the expected location. However (on my virtual hosting) the ftp upload sets the permissons only for the owner fully (drwx------).

The controller is not visible inside the the system/user/user groups permissions listing. The glob function on line 354 doesn't recognize the files. The issue can only be solved by manually updating the file permissions.

I would recommend to check the permissions of the files after ftp upload and set something like 0755 if necessary! If appreciated I can create a pull request for that...

**Comment by danielkerr** [comment]
checjkking permissions or not, this is down to your host to set the default permissions for uploaded files.

**Comment by danielkerr** [comment]
please do a push request so i can atleast see if what you are doing is going to help.

chmod would need to be done via ftp.
