### ISSUE TITLE
Warning: array_key_exists():

### ISSUE THREAD

**Issue by chambasi** [opencart/opencart#2716]
Hello, my domain intale opencart www.macanudoshop.com and all was well until I did the modification of the logo and accompanying me this error.

Warning: array_key_exists(): The first argument should be either a string or an integer in /hermes/bosnaweb05a/b2614/ipg.macanudoshopcom/macanudo/index.php on line 158

when I open the index.php what I find is that.
if (isset($session->data['language']) && array_key_exists($session->data['language'], $languages) && $languages[$session->data['language']]['status']) {

can you help me please, my email is cchambasi@systemsthn.com

**Comment by munirasim** [comment]
It has nothing to do with Open cart and it is concerned to hosting. You may go to "Web Cache Control Tool" inside ipage hosting and enable cache to get it resolved.

**Comment by chambasi** [comment]
Munirasim Hi, thanks for replying.
Active cache like you said and still got the same error,
I enter the web not have any any mistake but if I enter the administrator launches the error.

**Comment by munirasim** [comment]
The problem is that you 'session' expires either very quickly or randomly. Please contact ipage support to fix it for you. Again I confirm that it is not Opencart issue.
