### ISSUE TITLE
product count showing value wrong

### ISSUE THREAD

**Issue by bethelinfoserv** [opencart/opencart#2717]
Please visit my store
http://www.wholesalebazaar.clothing/index.php?route=product/category&path=20
The total count in Category "Salwar Suits" showing count as 42 which is wrong.
The product count is coming wrong.

My store is made live and I want an immediate solution.  Can you please let me know what went wrong.... An early action would be really really appreciated......

**Comment by danielkerr** [comment]
then go to a local web developer and pay for it to be fixed!

do jnot post here again this issue tracker is purely for new versions of opencart!
