### ISSUE TITLE
Not accepting email ID with .clothing tld

### ISSUE THREAD

**Issue by bethelinfoserv** [opencart/opencart#2718]
I am trying to register with email id i.e. info@wholesalebazaar.clothing but it says email id is not valid.
Why?

This is my valid email id.

**Comment by danielkerr** [comment]
this is development tracker for 2.0

i have just tested the email and it works correctly!

**Comment by bethelinfoserv** [comment]
Thanks for your reply.  Here I am using 1.5.6.4 and am trying to register with "info@wholesaleclothing.com" and also trying to put the same id in Settings > General tab of my store but at both places it says email id is not valid.  It is taking any junk email id but not with ".clothing" (dotClothing) extension. Not able to understand.  Is there something wrong with .Clothing TLD

Please help I am in great pain....
