### ISSUE TITLE
Hide english tab if language is disabled

### ISSUE THREAD

**Issue by hassi2k7** [opencart/opencart#2721]
English Headline, Text, Meta is required even if the Shop is complete in another language and the english language is disabled.

It would be more comfortable if the complete english tab is hidden if the language is disabled.

**Comment by mymzheka** [comment]
Issue closed, but there is no solution. Problem still exists and I came here from google. You can remove English from localisation/language for resolve this, but it may generate other problems in some situations, like you still need english in admin interface.

**Comment by 5brothers** [comment]
OMG. 2018. But this problem still unsolved
