### ISSUE TITLE
settings not accepting email id with .clothing TLD

### ISSUE THREAD

**Issue by bethelinfoserv** [opencart/opencart#2727]
I have a domain with .clothing TLD lets say http://www.market.clothing and I created an email Id i.e. info@market.clothing. This email id is valid and working absolutely fine.

But when I try to put this email ( info@market.clothing) in Admin of my Store under System > Settings > General Tab; it says email ID is not valid.

Here I am using 1.5.6.4 and not even able to register with this email as on registration page as well it says email is invalid. It is taking any junk email id but not with ".clothing" (dotClothing) extension. Not able to understand. Is there something wrong with .Clothing TLD

Please help I am in great pain....

**Comment by ADDCreative** [comment]
This has been fixed in the master branch. See https://github.com/opencart/opencart/commit/d3954cb021da0041144f5a80e591112fbe9e95e7

Looks like replacing ```'/^[^\@]+@.*\.[a-z]{2,6}$/i'``` with ```'/^[^\@]+@.*.[a-z]{2,15}$/i'``` in all files it appears should do the trick (the 6 changed to 15).
