### ISSUE TITLE
Error with 2.0 mail.php rolled back to 1.5.6 mail.php and works fine

### ISSUE THREAD

**Issue by MeisterWebzr** [opencart/opencart#2729]
Over the weekend, a few clients notified me of an error message while attempting to send request password reset email. I tested it out on OC 2.0.0.0 and sure enough this is the  error that triggered: 

Warning: fsockopen() expects parameter 2 to be long, string given in /home/twpfam/public_html/system/library/mail.php on line 168Notice: Error: () in /home/twpfam/public_html/system/library/mail.php on line 172

I simply rolled back to the mail.php from 1.5.6's  release and everything works fine. This might be something on my side, however, I chekced the repo mail.php from latest update on libraby directory and its identical to my error file. 

Should anyone have any feedback, errors or suggestions please update.

**Comment by danielkerr** [comment]
maybe you never resaved your settings for the new method of sending mails.

**Comment by MeisterWebzr** [comment]
Thanks, I've updated and all is working correctly.
