### ISSUE TITLE
Core SEO Clean URLs suck. Lets end the madness

### ISSUE THREAD

**Issue by manakill** [opencart/opencart#2733]
I'm so damn sick of SEO mods that go out of date every core update. If you use a different mod most time the URL generation technique will vary and the output URL will vary causing lots of 404 errors on google.

If I outsource the work to have the *core fixed* (not a crappy mod) to include:

Product SEO URL format: Category-name/sub-category-name/product-name 
Category SEO URL format: Parent-Category/Category/ 
Page SEO URL format: domain.com/page/ 
Other SEO URL format custom strings: /item 
Use single URL for all languages: checkbox

Can it be submitted for inclusion to core so there is a SEO standard followed well into the future?? I would like to hear from some Opencart Contributors on if this would be considered and how difficult a process would it be?

**Comment by yckart** [comment]
:+1: Sadly, this isn't already done. Sadly, issues get closed, without a comment. This disappoints me :'(

**Comment by stockmaster** [comment]
welcome to OpenCart ;)
