### ISSUE TITLE
opencart Hide Empty Categories

### ISSUE THREAD

**Issue by buluma** [opencart/opencart#2734]
Hello All

I need help to hide opencart empty categories from getCategories function in catalog/model/catalog/category.php

SELECT * FROM " . DB_PREFIX . "category c LEFT JOIN " . DB_PREFIX . "category_description cd ON (c.category_id = cd.category_id) LEFT JOIN " . DB_PREFIX ."uchumionlineproduct_to_category cp ON (c.category_id = cp.category_id) LEFT JOIN " . DB_PREFIX . "category_to_store c2s ON (c.category_id = c2s.category_id) WHERE c.parent_id = '" . (int)$parent_id . "' AND cd.language_id = '" . (int)$this->config->get('config_language_id') . "' AND c2s.store_id = '" . (int)$this->config->get('config_store_id') . "'  AND c.status = '1' ORDER BY c.sort_order, LCASE(cd.name)

Anyone has a solution for this?

**Comment by milimar** [comment]
Here you can report bugs related to the core of opencart, and here http://forum.opencart.com you can try to find a solution for your problem.

Greetings

**Comment by nosite** [comment]
To bad this is not a basic function in OC. Same for manufactures.

**Comment by TLEwebdevs** [comment]
I'll second the request for this to be a core function ... switchable in admin under System - Settings - Site.

Ideally I'd want the option to choose at which category level the "hiding" becomes active - e.g. hide 2nd and lower level categories that are empty, but leave visible top level categories that are empty (for page-formatting purposes).

**Comment by buluma** [comment]
Very good input TLEwebdevs
