### ISSUE TITLE
Bug on category template

### ISSUE THREAD

**Issue by Uzenmi** [opencart/opencart#2741]
I just found 2 bugs on category template as  picture below. I was add new currency and new language, then I change that options on front end and its price bug.

https://lh3.googleusercontent.com/-Fte8kZt6dYM/VPx-T83JMUI/AAAAAAAAB5k/AoMQRQYlo1Y/w909-h573-no/opc.png

(Safe image from Picasa)

**Comment by eatonmunoz** [comment]
What is the solution for this issue?
