### ISSUE TITLE
Open Cart Contact Form Fails

### ISSUE THREAD

**Issue by jdkarns** [opencart/opencart#2742]
My Opencart contact page will not go to "information/contact/success" and send the email from a customer.  It has no validation errors.  It only clears the form and presents it again to be filled out.  The website is here:
https://www.cosmicbutterflyclothing.com/shopping/index.php?route=information/contact

Has anybody heard of a bug in Opencart 2.0.1.1 like this?  I do believe it may have something to do with the "catalog/controller/information/contact.php".  I am not a pro at PHP so it is not totally coming to me yet?  I keep trying to figure it out though.  Thanks for any help.

**Comment by munirasim** [comment]
Could you please tell us who is your hosting provider and are you using Mail protocol in 'Mail'  tab in store settings? Does your 'mail parameters' field looks like '-fyouremailaddress@example.com'?
It's an issue with your settings not with Opencart.

**Comment by jdkarns** [comment]
It is fixed now.  It was a line of code.  Since I am using SSL I needed to
change a line of code in the (catalog/controller/information/contact.php)
file as follows:

Was like this:
$this->response->redirect($this->url->link('information/contact/success'));

Needed to be changed to this:
$this->response->redirect($this->url->link('information/contact/success',
'', 'SSL'));

All the other mail related features have always worked such as order
confirmation, newsletter and others.  The only thing that was broken was
the contact page.

Thank you very much for your response

**Comment by munirasim** [comment]
Great you solved it yourself and posted it to help others.

**Comment by jdkarns** [comment]
Something like that.  I actually stumbled on to the fix in a forum
somewhere.  But I hope my post/re-post will help others.  :)
