### ISSUE TITLE
FYI - Royal mail prices changes

### ISSUE THREAD

**Issue by dtjones** [opencart/opencart#2743]
I know someone put in a lot of hard work updating the royal mail shipping extension recently so I am hoping the changes are minimal but starting 30/03/15 royal mail prices are changing. 

http://www.royalmail.com/sites/default/files/Royal-Mail-UK-and-international-parcel-and-letter-prices-30-March-2015.pdf

**Comment by jamesallsup** [comment]
Merchants can update the prices / rates / services they offer through the admin. We will update the base prices though once the changes have taken effect but that will only be for new installs - sadly Royal Mail don't offer a live API for price checking yet (despite many, many people begging for it!!).

Thanks.
