### ISSUE TITLE
New G-recaptcha not working 

### ISSUE THREAD

**Issue by markoRs** [opencart/opencart#2744]
New captcha always reports error on product, contact, and return pages. After filling the forms ans submitting it reports error. Tested on custom and default theme localhost and live. 
![captcha](https://cloud.githubusercontent.com/assets/10956731/6552489/46e67202-c63e-11e4-8eca-3a00e207f140.jpg)

**Comment by milimar** [comment]
On my OC 2.0.1.2rc it does not work neither. I tried to verify several times, but I always get this error message:
{ "success": false, "error-codes": [ "invalid-input-response" ] }

My test website is on a life server.

**Comment by danielkerr** [comment]
try it on a domain and not localhost

**Comment by markoRs** [comment]
It is on a domain. Not working.

**Comment by mesutk** [comment]
Yep, tried on both localhost and several domains using Apache and IIS (7, 7.5, 8.5) 

Even if you tick the box, it gives you an error

Default 

![ekran alintisi](https://cloud.githubusercontent.com/assets/11406577/6574163/8803ce78-c72a-11e4-8235-3e5c7bd4f389.PNG)

Custom

![testcustom](https://cloud.githubusercontent.com/assets/11406577/6574165/8fc3e63e-c72a-11e4-9e3d-af8b5cd4053a.PNG)

**Comment by k2tec** [comment]
And if you set status to disabled you get a error:
PHP Notice:  Undefined variable: site_key in /*/catalog/view/theme/default/template/information/contact.tpl on line 135
2015-03-17 14:51:44 - PHP Notice:  Undefined variable: site_key in /*/catalog/view/theme/default/template/account/return_form.tpl on line 155
2015-03-17 18:04:33 - PHP Notice:  Undefined variable: site_key in /*/catalog/view/theme/default/template/product/product.tpl on line 106

**Comment by k2tec** [comment]
Still a issue.
When you don't make your captcha enabled you still get this error.
PHP Notice:  Undefined variable: site_key in C:\xampp\htdocs\oc2_goedkoop\catalog\view\theme\default\template\product\product.tpl on line 106

I think the controller is not correct and have to be changed in.
find :
if ($this->config->get('config_google_captcha_status')) {
			$this->document->addScript('https://www.google.com/recaptcha/api.js');
			
			$data['site_key'] = $this->config->get('config_google_captcha_public');
		} 

and change to:

if ($this->config->get('config_google_captcha_status')) {
			$this->document->addScript('https://www.google.com/recaptcha/api.js');
			
			$data['site_key'] = $this->config->get('config_google_captcha_public');
		} else {
			$data['site_key'] = '';
		}

**Comment by jamesallsup** [comment]
https://github.com/opencart/opencart/commit/220cc5f2a04eb02c27b5bb10a0b570f6f74e2dbf

**Comment by markoRs** [comment]
But g-recaptcha is still not working. As shown on the images above.

**Comment by k2tec** [comment]
In the controller->product.php change 
$json['error'] = $this->language->get('error_captcha');
to
$this->error['captcha'] = $this->language->get('error_captcha');

**Comment by markoRs** [comment]
For me is still not working - returns, contact, and product. Ask to verify again.

**Comment by k2tec** [comment]
Here its working, the only thing is that when I write a review, there is no text that the revieuw is sended, it stays on the same review page.but in the admin you can see that the review is placed.

**Comment by markoRs** [comment]
Have you tried on contact page?

**Comment by k2tec** [comment]
Contact, review and return page check and working

**Comment by markoRs** [comment]
Tnx. I checked my php and tpl files and everything is like aligned with the files on github,  but not working. Will check it again

**Comment by markoRs** [comment]
No idea. I copied the files from the github both php and tpl and tested and not working. If you have time could you quickly check if your files are matching those in the github?

Tnx

**Comment by k2tec** [comment]
Hi markoRs, I compared them and they are matching.

**Comment by milimar** [comment]
Soon I want to start building my online shop based on OC, and I am interested in helping in everything I can, so today I made  a fresh installation on live server and I tested the new recaptcha that for sure was not working before, and now It is working fine (att), but can someone tell me where I can find the message that an unregistered clients send from the contact form? I just want so test if the messages are really sent, but unfortunately I cannot find the message in my admin panel.
![recaptcha](https://cloud.githubusercontent.com/assets/9386798/6788888/cf2dae46-d19c-11e4-8c96-981ae72cadba.jpg)

**Comment by k2tec** [comment]
This is not a forum and if your making a shop with 2.0.1.2rc don't do that

**Comment by milimar** [comment]
@k2tec  I am trying to help resolving the issue with the recaptcha, and I just confirmed that it is working fine at my end, messages are sent with no problems, but I do not know if the admin of the site receives that messages, maybe someone with better knowledge can check it. 

I will not make my shop with 2.0.1.2rc, but with the new official release which I hope will come soon, but if we all don't help as much as we can, that release will not come so soon, so I am trying to help, and not to obtain help, which I know that is done on the official forum.

**Comment by k2tec** [comment]
If you setup a account with a live e-mail box than you can see it works. and look for review in your admin controle under the bell. Top right corner.
Sorry for my English

**Comment by markoRs** [comment]
Tnx K2tec! Solved. The problem was in modification file. I needed to hit refresh button in admin.

**Comment by milimar** [comment]
1. Yes, thanks to k2tec I managed the review to work, but as he already said, there is no a confirmation message,and that would be very confusing for clients.

2. I tested and I can confirm that a review will not be sent if it has less than 25 characters in the text, so if a clients writes "very good product", that message will not be send to the store admin. 

There has to be an alert message if text less that 25 characters!

**Comment by Irfah5555** [comment]
Hey!

**Comment by Irfah5555** [comment]
Hey guys!we are student of MBA(ITM), We are working on project, our project is to find solution of this bug now we have solution of this problem, anyone who is interested to get this solution.
so comment here.

**Comment by osworx** [comment]
@Irfah5555 this here is no puzzle.
If you have to say something, say it.
Otherwise let it.

**Comment by Irfah5555** [comment]
actually its our project and through this project need to earn money ,its requirement of our project and we want to pledge this project, if you want that bug solution,you must pay for it.

**Comment by Samiooo** [comment]
Irfah5555 give me complete detail of project?

**Comment by mesutk** [comment]
That is not a correct place for you to sell your solutions for fixed stuff.

**Comment by Irfah5555** [comment]
please tell me right place where i can sell it

**Comment by mesutk** [comment]
If you have a something new rather than a fixing bug such as adding new feature, ability, or increasing the efficiency etc. you should write the module in ocmod and upload it on Opencart's extension store.

http://www.opencart.com/index.php?route=extension/extension

But it's not ethical to sell a fixed-bug or core-issue with money for this project, atleast for me. If you have a solution, as osworx said, say it, otherwise let it go.

**Comment by osworx** [comment]
@Irfah5555 on the other side of the moon.

**Comment by Irfah5555** [comment]
@osworx i have not much information about it i am working on project so give solution other its not a joke you go on other side of moon you need it

**Comment by Irfah5555** [comment]
thanks @mesutk

**Comment by milimar** [comment]
What are you talking about people? I think that this issue has already been fixed, or not? What was this about: https://github.com/opencart/opencart/issues/2843

**Comment by mihonik** [comment]
Does anyone know how to change recaptcha language for opencart 2.0.3.1?
