### ISSUE TITLE
umask prevents mkdir 0777 after image upload in backend

### ISSUE THREAD

**Issue by stefanhuber** [opencart/opencart#2745]
Inside the admin/controller/common/filemanager.php on line 322, the following is stated:

        mkdir($directory . '/' . $folder, 0777);

Unfortunately, umask may prevent the setting of mode 0777 for mkdir. Setting via chmod directly will not be affected by umask. The following would do the trick:

       mkdir($directory . '/' . $folder);
       chmod($directory . '/' . $folder, 0777);

I often encounter a umask of 0022 in shared hosting environments, which would set the mode to 0755 after using php's mkdir. This infact wouldn't allow for image uploads via ftp inside the directories, created via the filemanager.

**Comment by danielkerr** [comment]
some how i think this is not a very good solution. I image most hosts have security to protect the directories from being modified from creating chmod folders already setup.

**Comment by stefanhuber** [comment]
In the phpdoc there is a comment with a different solution. Which would be an alternative (http://php.net/manual/en/function.mkdir.php#1207). The above stated solution is better in my opinion.

Anyhow, i cannot think of another way to allow different users (ftp and php) to upload images, than setting chmod o+w to the folders inside the image directory. Otherwise only the user who created the folder has the right to upload images into it.

As the php user is the creator (and owner) of the folder with mkdir, i cannot think of any protection, which could disallow a chmod...

**Comment by stefanhuber** [comment]
This is still an issue! Could be fixed so easy with the approaches I mentioned...
