### ISSUE TITLE
Need to understand how we can change / modify opencart 2.0 code base.

### ISSUE THREAD

**Issue by omps** [opencart/opencart#2763]
I was going through the opencart system and was tinkering around of removing the comment box block, but I am getting JSON.parse error, any clue? Also, it seems a lot of things got changed in opencart 2.0 version, like button shipping method and all. Can you suggest what needs to be done to remove the shipping method and the delivery method during the checkout.

**Comment by jamesallsup** [comment]
Please use the forums for help.

https://github.com/opencart/opencart/blob/master/README.md
