### ISSUE TITLE
Opencart 2.0.1.1. admin/controller/extention/modification.php issue

### ISSUE THREAD

**Issue by imartin1983** [opencart/opencart#2764]
Hi, 
I'm running OC 2.0.1.1. and after installing any Ocmod with the installer (it shows it's istalled OK) and I go to Modifications and Refresh, I get an error and basically I can't install any ocmod with the installer:

"Warning: DOMDocument::loadXML(): Empty string supplied as input in /hosting/www/domain.cz/www/admin/controller/extension/modification.php on line 132Notice: Trying to get property of non-object in /hosting/www/domain.cz/www/admin/controller/extension/modification.php on line 143"

I replaced the modification.php file with the theme default file (I'm using pavothemes, where it works fine) and still nothing happens. Any idea what this can be? I also noticed that in /system/modification there is no "admin" and "system" folders (as in the preview pavotheme I have).

Thanks for reply. Cheers.

**Comment by mhcwebdesign** [comment]
Unable to reproduce your error, it is working fine. Please post on the OpenCart forum as a support request!

**Comment by ankitbisht227** [comment]
Warning: DOMDocument::loadXML(): Empty string supplied as input in /home/wwwmotherglance/public_html/admin/controller/extension/modification.php on line 132Notice: Trying to get property of non-object in /home/wwwmotherglance/public_html/admin/controller/extension/modification.php on line 143
Fatal error: Call to a member function getElementsByTagName() on null in /home/wwwmotherglance/public_html/admin/controller/extension/modification.php on line 145Warning: DOMDocument::loadXML(): Empty string supplied as input in /home/wwwmotherglance/public_html/admin/controller/extension/modification.php on line 132Notice: Trying to get property of non-object in /home/wwwmotherglance/public_html/admin/controller/extension/modification.php on line 143
Fatal error: Call to a member function getElementsByTagName() on null in /home/wwwmotherglance/public_html/admin/controller/extension/modification.php on line 145Warning: DOMDocument::loadXML(): Empty string supplied as input in /home/wwwmotherglance/public_html/admin/controller/extension/modification.php on line 132Notice: Trying to get property of non-object in /home/wwwmotherglance/public_html/admin/controller/extension/modification.php on line 143
Fatal error: Call to a member function getElementsByTagName() on null in /home/wwwmotherglance/public_html/admin/controller/extension/modification.php on line 145

**Comment by ankitbisht227** [comment]
Warning: DOMDocument::loadXML(): Empty string supplied as input in/public_html/admin/controller/extension/modification.php on line 132Notice: Trying to get property of non-object in /public_html/admin/controller/extension/modification.php on line 143
Fatal error: Call to a member function getElementsByTagName() on null in /public_html/admin/controller/extension/modification.php on line 145

**Comment by osworx** [comment]
@ankitbisht227 And?
What should that say to us?
Seems that you have a invalid XML-file - post it here to check.

**Comment by mhcwebdesign** [comment]
It should really be posted on the OpenCart forum, as it is not a bug report.

**Comment by unknownAnkur** [comment]
When i installed an extension, it shows installation successfull, and it is also displayed in modification section in admin panel, but it's changes are not seen in live screen.
