### ISSUE TITLE
Payment Methods sould refresh when a Shipping Method is selected in an Order from the Admin Panel

### ISSUE THREAD

**Issue by GKASIOS** [opencart/opencart#2765]
I have an Extension that relies on the selected Shipping Method and because the Payment Model doesn't get as an argument the shipping method code I get that information from the session. So my extension will work from the store front but will fail from the admin panel. To better understand what I’m talking about you can download my extension here http://www.opencart.com/index.php?route=extension/extension/info&extension_id=11301

**Comment by jamesallsup** [comment]
You need to use the forum for help like this, please use Github for OpenCart related bugs only and not 3rd party modules.

Thanks.
