### ISSUE TITLE
multistore currency conversions issues in catalog/controller/payment/pp_express.php?

### ISSUE THREAD

**Issue by pine3ree** [opencart/opencart#2768]
#2601 

to put it simply

$this->currency->convert($value1, 'GBP', 'USD');
$this->currency->convert($value2, 'EUR', 'USD');

$value1 must be provided in GBP
$value2 must be provided in EUR

for the conversions to make any sense.

But $this->cart->getTotal() is always in the same currency, i.e. the config_currency of store id=0,
while config_currency can be different for different stores, so we can have situations when we will try to convert a value in EUR from GBP to USD.

the longer comments in #2601 maybe explain it better.

**Comment by jamesallsup** [comment]
https://github.com/opencart/opencart/commit/29f6c323d3d2e48e9929823b0f5b234285191208
