### ISSUE TITLE
bad sitemap.xml

### ISSUE THREAD

**Issue by opencart-russia** [opencart/opencart#2770]
SEO enabled

look sitemap.xml

<loc>http://test/sony?amp%3Bproduct_id=46</loc>

**Comment by jamesallsup** [comment]
Works fine for me on several test sites we run.

**Comment by opencart-russia** [comment]
Works fine if the SEO URL off, and work, when to enable, but there is an incorrect reference. 
Blame 
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/feed/google_sitemap.php#L47
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/feed/google_sitemap.php#L95


test 2.0.1.2 rc
http://easycaptures.com/fs/uploaded/778/0295789378.png
http://easycaptures.com/fs/uploaded/778/6078195601.png
