### ISSUE TITLE
Editing orders / deleting orders

### ISSUE THREAD

**Issue by alanrburns** [opencart/opencart#2775]
So I have tested this over and over.
with a fresh install on aws
I used bitnami nginx stack
https://bitnami.com/stack/nginx

Creating and editing orders and deleting orders is impossible.

http://forum.opencart.com/viewtopic.php?f=190&t=141690
http://forum.opencart.com/viewtopic.php?f=191&t=136386
http://forum.opencart.com/viewtopic.php?f=191&t=138987

Process followed..
wget https://bitnami.com/redirect/to/44301/bitnami-nginxstack-1.6.2-1-linux-x64-installer.run
chmod +x ./bitnami-nginxstack-1.6.2-1-linux-x64-installer.run
sudo ./bitnami-nginxstack-1.6.2-1-linux-x64-installer.run

#create db via phpmyadmin

git clone https://github.com/opencart/opencart.git
cd opencart/upload/
mv config-dist.php config.php 
cd admin/
mv config-dist.php config.php 
cd ..
chmod 0777 system/cache/
chmod 0777 system/logs/
chmod 0777 system/download/
chmod 0777 system/upload/
chmod 0777 image/
chmod 0777 image/cache/
chmod 0777 image/catalog/
chmod 0777 config.php
chmod 0777 admin/config.php
sudo mv ./* /opt/nginxstack-1.6.2-1/nginx/html/
sudo vi /opt/nginxstack-1.6.2-1/nginx/conf/bitnami/bitnami.conf

#Change index.html to index.php

/opt/nginxstack-1.6.2-1/nginx/ctlscript.sh restart

Go through the web installer
Log into admin interface

When I try to add an order via route=sale/order/add it is very slow and I get an "unexpected end of input" error when trying to submit..

When I submit an order as a customer and then try to delete it I get the error message bellow.. >
Warning: CURL error couldn't connect to host(7)!

**Comment by jamesallsup** [comment]
Please use the forums for support. http://forum.opencart.com

**Comment by alanrburns** [comment]
So the fact that there are multiple reports of this doesn't indicate that there might be an issue?

**Comment by alanrburns** [comment]
http://forum.opencart.com/viewtopic.php?f=191&t=138987&p=550770

**Comment by psitsolution** [comment]
![captura de pantalla 2015-03-21 a la s 13 05 09](https://cloud.githubusercontent.com/assets/6780838/6765723/405d42f8-cfe4-11e4-84d5-1e4e0bb3ade5.png)
official demo site of opencart 2.0.1.1 / mod-edit order have a bug?

**Comment by arbelaezjm** [comment]
this is the same problem ...  https://github.com/opencart/opencart/issues/3124

**Comment by sfaragy** [comment]
Hello friends,
I have a great fix for this issue. Please visit my extension and purchase it. You should get the issue fixed.
We have few customers already getting the issue fixed. 

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=24725
![opc1](https://cloud.githubusercontent.com/assets/6167254/11949043/26668ad6-a8a5-11e5-8ca3-93ae25d0f92b.jpg)
![opc2](https://cloud.githubusercontent.com/assets/6167254/11949044/26719bba-a8a5-11e5-94aa-4fcc10b175af.jpg)

**Comment by Smartappies** [comment]
Hello,

i have fix it simply :)

In file admin/controller/sale/order.php

in api function 

replace 

$this->response->setOutput($json);

with this

$this->response->setOutput(json_encode($json));

And thats all :)

**Comment by osworx** [comment]
Wrong approach, because if the api call was not successful you are now encoding the $json array twice (the error message is already encoded).
Beside this, with 2.1.x this function does not exist anymore in this controller.

**Comment by Smartappies** [comment]
public function api() {
		$json = array();

		// Store
		if (isset($this->request->get['store_id'])) {
			$store_id = $this->request->get['store_id'];
		} else {
			$store_id = 0;
		}

		$this->load->model('setting/store');

		$store_info = $this->model_setting_store->getStore($store_id);

		if ($store_info) {
			$url = $store_info['ssl'];
		} else {
			$url = HTTP_CATALOG;
		}

		if (isset($this->request->get['api'])) {
			// Include any URL perameters
			$url_data = array();

			foreach ($this->request->get as $key => $value) {
				if ($key != 'route' && $key != 'token' && $key != 'store_id') {
					$url_data[$key] = $value;
				}
			}

			
			$curl = curl_init();

			// Set SSL if required
			if (substr($url, 0, 5) == 'https') {
				curl_setopt($curl, CURLOPT_PORT, 443);
			}

			curl_setopt($curl, CURLOPT_HEADER, false);
			curl_setopt($curl, CURLINFO_HEADER_OUT, true);
			curl_setopt($curl, CURLOPT_USERAGENT, $this->request->server['HTTP_USER_AGENT']);
			curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
			curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
			curl_setopt($curl, CURLOPT_FORBID_REUSE, false);
			curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
			curl_setopt($curl, CURLOPT_URL, $url . 'index.php?route=' . $this->request->get['api'] . ($url_data ? '&' . http_build_query($url_data) : ''));

			if ($this->request->post) {
				curl_setopt($curl, CURLOPT_POST, true);
				curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($this->request->post));
			}

			curl_setopt($curl, CURLOPT_COOKIE, session_name() . '=' . $this->session->data['cookie'] . ';');

			$json = json_decode(curl_exec($curl));
			
			curl_close($curl);
			
		
	    }
		
		
		$this->response->addHeader('Content-Type: application/json');
		$this->response->setOutput(json_encode($json));
	}

And everything working great !

**Comment by angboontiong79** [comment]
Smartappies, where to put in this ?

**Comment by Smartappies** [comment]
angboontiong79,

open the file admin/controller/sale/order.php

Find the public function api()

And change 

$this->response->setOutput($json);

to

$this->response->setOutput(json_encode($json));

Ok ?

**Comment by angboontiong79** [comment]
Hi, by default, it's already $this->response->setOutput(json_encode($json));

**Comment by SwissMrs** [comment]
Fantastic! I've been searching how to fix this for weeks now. I have tried EVERY suggestion I could find and the fix above worked for me. THANK YOU @Smartappies!!!

**Comment by tombu93** [comment]
Hi,

We're using MijoShop, which runs off OpenCart and after endless searches trying to resolve this, we finally managed to solve this by adding a **https** domain to "admin/config.php"
(Using MijoShop this directory is located in: "/components/com_mijoshop/opencart/admin/config.php").

So it should look as follows...

`define('HTTP_CATALOG', $main_full_url);
define('HTTP_CATALOG', 'https://www.yourdomain.co.uk');`

I hope this helps.
