### ISSUE TITLE
Different Checkout prices when purchasing the same items

### ISSUE THREAD

**Issue by micb11** [opencart/opencart#2776]
I have never reported a bug before so I hope this is the place to do it. 

Please follow these exact steps to reproduce the bug

1. Go to www.doorsdirect2u.co.uk
2. In the search box enter 201236 the result will show one door available. Click into the door product
3. Enter any size in the size box and pre-finish in the finish box.
4. Then select qty 5 and add to basket
5. Your cart should be showing 699.95
6 Now go to the search box and add 201419 the result will show one doors available. Click into the doors product
7. Enter pre finished in the finish box and any size in the size box.
8. Then select qty 2
9. Your shopping cart should be showing 979.93

No if you clear all the item out of your shopping cart. 

This time add 201419  product first to your shopping cart then find the product 201236 and add that to your shopping cart.

My shopping cart now is showing £1144.15

I have ordered exactly the same products but different ways round and it is giving me 2 different checkout prices

The below images are exactly the same items but different checkout prices

![doors1](https://cloud.githubusercontent.com/assets/11523497/6690968/7c843ab0-ccbb-11e4-9478-895fd9f2e7b9.jpg)
![doors2](https://cloud.githubusercontent.com/assets/11523497/6690969/80373f72-ccbb-11e4-8ce5-ce97e5e2b698.jpg)

**Comment by higagan** [comment]
I am able to reproduce in www.doorsdirect2u.co.uk . But also, I cloned the opencart,installed and tried to reproduce the bug with Apple Cinema 30" and iPhone. Used different ways to add to cart. But I am unable to reproduce in my local cloned copy.

**Comment by jamesallsup** [comment]
Please use the forums for support. http://forum.opencart.com

**Comment by micb11** [comment]
Sorry about that. Is this not a bug then?



On 18/03/2015 14:27, James Allsup wrote:
>
> Please use the forums for support. http://forum.opencart.com
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/opencart/opencart/issues/2776#issuecomment-82995633>.
>

-- 
thanks

Mike Boulton

Wey2creative
Nicholson House
41 Thames Street
Weybridge
Surrey
KT13 8JG

T: 01932506226
