### ISSUE TITLE
Paypal refund in OpenCart 2.0.1.1 (rs.6)

### ISSUE THREAD

**Issue by avia07** [opencart/opencart#2778]
Hi when i issue refund from Order>>Action page, refund woks fine, but when i go to error log, i am faceing with this error:

2015-03-17 22:28:30 - PHP Notice: Undefined variable: text_edit in /home/XXXX/public_html/admin/view/template/payment/pp_express_refund.tpl on line 27

Does any one have any idea why this error happenes?

**Comment by osworx** [comment]
simply missing the var $text_edit in the language fille.

**Comment by opencart-russia** [comment]
@avia07 в скобках rs6, а это значит Русская сборка.
Посему, если что, просто пишите на форум сборки.

**Comment by avia07** [comment]
Проблема присутствует и в других локализациях.
