### ISSUE TITLE
Dirty URL

### ISSUE THREAD

**Issue by jofftornea** [opencart/opencart#2779]
Does anyone here knows how to fix Opencart URL? I tried .htaccess but its not enough.

RewriteRule ^home/$ index.php?route=common/home [L] #Home Page
RewriteRule ^contact/?$ index.php?route=information/contact [L] #Contact Page
ReWriteRule ^login/?$ index.php?route=account/login [L] #Login Page
ReWriteRule ^logout/?$ index.php?route=account/logout [L] #Logout Link
ReWriteRule ^cart/$ index.php?route=checkout/cart [L] #Cart Page
ReWriteRule ^manufacturers/$  index.php?route=product/manufacturer  [L] #Manufacturer Page
ReWriteRule ^specials/$ index.php?route=product/special [L] #Specials Page
ReWriteRule ^vouchers/$ index.php?route=account/voucher [L] #Voucher Page
RewriteRule ^account/?$ index.php?route=account/account [L] #Account Page
RewriteRule ^wishlist/?$ index.php?route=account/wishlist [L] #Wishlist Page
ReWriteRule ^my-orders/$ index.php?route=account/orders [L] #Past Orders Page

**Comment by mhcwebdesign** [comment]
This is not a bug report, please post it on the OpenCart forum.
