### ISSUE TITLE
Sending Emails to Customers with non-active member too

### ISSUE THREAD

**Issue by ilovechinahk** [opencart/opencart#2780]
my version is 1.5.6.1

problem: Sending Emails to Customers with non-active member too

I tested and found a big problem.

When i using the opencart built-in mail function (under =sale/contact) ,

and  i choose send to "All Member"  , the system will send out to the non-active member  too (i means it will send to all the non-approved member , how to fixed it ? how to set only sent to approved member (under=sale/customer, admin click "Approve") ?

**Comment by jamesallsup** [comment]
Please use the forums for support or queries on how to change functionality. http://forum.opencart.com
