### ISSUE TITLE
Administration - Menu layout - 3rd level 

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#2791]
Version 2.0.1.2_rc (and before)
In the OC administration menu layout (Icon variant/short menu) there is the problem that if the user is opening a menu entry of the 3rd level the dividing lings of the 3rd menu level stay present after the menu closed.
e.g. open Catalog - Attributes > 3 lines stay (after leaving the menu with the mouse)

**Comment by nuke123** [comment]
Fixed by overwriting the collapse class 
https://github.com/nuke123/opencart/commit/868c46b7b36983196b8ee1a54588032104ca9069

**Comment by jamesallsup** [comment]
This was fixed in the latest release.

**Comment by jamesallsup** [comment]
Sorry I meant latest version.
