### ISSUE TITLE
No able to register on forum|  PlayThru game not getting displayed

### ISSUE THREAD

**Issue by higagan** [opencart/opencart#2792]
Hi,
 I am not able to register on forum. After clicking it says "Sorry, please complete the PlayThru game." I dont see any such games at the end of form .. its just blank spaces. I have tried in all the browsers.

Thanks,
Gagan

**Comment by jamesallsup** [comment]
Contact the support team for issues like this. GitHub is for OpenCart code bugs only.

http://www.opencart.com/index.php?route=support/contact
