### ISSUE TITLE
Klarna Invoice - Not showing Thank you/Order compleate page

### ISSUE THREAD

**Issue by exsatio** [opencart/opencart#2794]
Like topic said, after completing a order with klarna invoice the customers don't get any "thank you page" confirming the purchase. I have read some 3 year cases with same problem but cant find any solution. 

I have tried updating all the klarna files from the list below and found out that \catalog\view\theme\YOURTHEME\template\payment\klarna_invoice.tpl  was completely missing.

\admin\controller\payment\klarna_invoice.php
\admin\view\template\payment\klarna_invoice.tpl
\catalog\controller\payment\klarna_invoice.php
\catalog\model\payment\klarna_invoice.php
\catalog\view\theme\YOURTHEME\template\payment\klarna_invoice.tpl 

Any ideas?

**Comment by danielkerr** [comment]
im closing this because klarna has paid for us to up date the api to their latest one. shoudl be ready soon.

**Comment by syntaxerror** [comment]
@exsatio in \catalog\controller\payment\klarna_invoice.php find this line (385 in 2.0.3.1):

curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 1);

change it into:

curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 2);

- Support for value 1 removed in cURL 7.28.1

PS! Same for \catalog\controller\payment\klarna_account.php
