### ISSUE TITLE
Class 'Image' not found in admin/model/tool/image.php

### ISSUE THREAD

**Issue by mhd-matheen** [opencart/opencart#2795]
I tried to install OpenCart 2.0.1.1 a local server. Everything went fine until, admin login page showed up. It said "Fatal error: Class 'Image' not found in /admin/model/tool/image.php on line 29".

This is my first time installation in a PHP framework and am sure no problem in server and database.

**Comment by jamesallsup** [comment]
Please use the forum for support: http://forum.opencart.com

**Comment by mhd-matheen** [comment]
Thank you James Allsup


Thanks,
Mohamed *Matheen*
