### ISSUE TITLE
need to change MyIsam to InnoDB

### ISSUE THREAD

**Issue by tmccaff** [opencart/opencart#2800]
I have made a test to prove my point. I setup opencart on 2 different hosts. We made a total of 170 transactions and out of those 5 where lost and 6 of them where messed up due to MyIsam. As a developer I know MyIsam has no business in ecommerce script it doesnt do well with transactions as you can see.

**Comment by side-by-side** [comment]
Agree. MyISAM must die in eCommerce. So, so many talks about that but no action.
