### ISSUE TITLE
It's a Bug(?) Multistore can't find images and Stylesheets (404 Error)

### ISSUE THREAD

**Issue by uponity** [opencart/opencart#2802]
Version: 1.5.6.3
Issue: a new Multistore have no access to the images and stylesheets. If i call e.g. the stylesheet directly in the browser i get an 404 Error.

http://totalverplant.flockstar.de/

Regards,
Danny

**Comment by jamesallsup** [comment]
Use the forum please: http://forum.opencart.com/
