### ISSUE TITLE
BUG!!  Editing orders / deleting orders

### ISSUE THREAD

**Issue by alanrburns** [opencart/opencart#2803]
READ BEFORE CLOSING!!!!

So I have tested this over and over.
with a fresh install on aws
I used bitnami nginx stack
https://bitnami.com/stack/nginx

Creating and editing orders and deleting orders is impossible.

http://forum.opencart.com/viewtopic.php?f=190&t=141690
http://forum.opencart.com/viewtopic.php?f=191&t=136386
http://forum.opencart.com/viewtopic.php?f=191&t=138987

Process followed..
wget https://bitnami.com/redirect/to/44301/bitnami-nginxstack-1.6.2-1-linux-x64-installer.run
chmod +x ./bitnami-nginxstack-1.6.2-1-linux-x64-installer.run
sudo ./bitnami-nginxstack-1.6.2-1-linux-x64-installer.run

#create db via phpmyadmin

git clone https://github.com/opencart/opencart.git
cd opencart/upload/
mv config-dist.php config.php 
cd admin/
mv config-dist.php config.php 
cd ..
chmod 0777 system/cache/
chmod 0777 system/logs/
chmod 0777 system/download/
chmod 0777 system/upload/
chmod 0777 image/
chmod 0777 image/cache/
chmod 0777 image/catalog/
chmod 0777 config.php
chmod 0777 admin/config.php
sudo mv ./* /opt/nginxstack-1.6.2-1/nginx/html/
sudo vi /opt/nginxstack-1.6.2-1/nginx/conf/bitnami/bitnami.conf

#Change index.html to index.php

/opt/nginxstack-1.6.2-1/nginx/ctlscript.sh restart

Go through the web installer
Log into admin interface

When I try to add an order via route=sale/order/add it is very slow and I get an "unexpected end of input" error when trying to submit..

When I submit an order as a customer and then try to delete it I get the error message bellow.. >
Warning: CURL error couldn't connect to host(7)!

**Comment by jamesallsup** [comment]
Re-opening issues again does not mean that there is a bug in OpenCart. If Daniel or myself closes a report it means that we have tested or investigated and could not replicate your problem. If the solution works for 99.9% of users then the issue is not a bug and we move on to the next bug report to save valuable little time we have to help everyone. It is nothing personal, it is just what we have to do to get through as many reports as possible.

Putting comments on the forum like: "So I logged this as a bug because is seems to be easy to recreate but it looks like James Allsup decided it is not worth investigating..Looks like this project is falling apart.." - it does not help anyone and is an insult to people to spend time working on a FREE solution that you use.

I will again investigate the report just like last time and if it works across all of my test installations then the report will be closed. If any issues are found then they will be posted here.

**Comment by stefanhuber** [comment]
I had a similar problem, but only with apache http authentication in place. Without this, everything worked fine.

https://github.com/opencart/opencart/issues/2251

**Comment by alanrburns** [comment]
@jamesallsup thank you for responding.
I have replicated this 5 times now and I always get the same result with 2.0.1.1 but I do not see this issue with 1.5.6.4

Send me your public key and I will give you access to an AWS server running Ubuntu Server 14.04 LTS (HVM), SSD Volume Type

I will even provide you with an auto deployment script.

**Comment by psitsolution** [comment]
official demo site of opencart 2.0.1.1 have the same problem "sintax error"!!!!
![captura de pantalla 2015-03-21 a la s 13 05 09](https://cloud.githubusercontent.com/assets/6780838/6765144/5046a3a8-cfcb-11e4-8e27-24e2b3715dee.png)

**Comment by danielkerr** [comment]
the official demo is stripped down and set to block people editing orders!!

**Comment by psitsolution** [comment]
if you say so!....

**Comment by psitsolution** [comment]
if you say so!....

2015-03-21 15:43 Daniel Kerr:
> the official demo is stripped down and set to block people editing
> orders!!
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] 
> https://github.com/opencart/opencart/issues/2803#issuecomment-84374756

-- 
Pierluigi Spaziani
info@psitsoution.com / pierluigispaziani@gmail.com
http://www.psitsolution.com

**Comment by psitsolution** [comment]
...if really is as you say why not just remove the permission to the demo user giving a message of warnig. "Warning: You do not have permission to modify orders!"???
the answer seems to me an excuse.

**Comment by alanrburns** [comment]
Looks like the devs are to arrogant to need help..

**Comment by Lowerland** [comment]
i agree

**Comment by Lowerland** [comment]
https://github.com/opencart/opencart/commit/5ef4e03c41bcd64fad136a5418a3830a5c282920?diff=split

lololol

**Comment by pezastic** [comment]
I, too, am having this problem, and wonder how many others are having it who don't comment.

**Comment by pezastic** [comment]
I tried the steps here and it works now for me:
http://www.viethemes.com/how-to-fix-error-syntaxerror-unexpected-end-of-input-ok-when-editing-order-in-opencart-2/

**Comment by Lowerland** [comment]
Nope i tried that also.

Not working for me

**Comment by Lowerland** [comment]
It is weird...

**Comment by pezastic** [comment]
According to that link you could try sending your site URL, an admin account, and an FTP account to viethemes@gmail.com and see if he can help. At least he's willing to try.
