### ISSUE TITLE
Multi-currency issue in order_info (currency_code & amount not matched)

### ISSUE THREAD

**Issue by nvphuc1989** [opencart/opencart#2807]
Hi All,

I'm getting currency code & amount from order info by the code below:
> $order_info = $this->model_checkout_order->getOrder($this->session->data['order_id']);
> $data['amount'] = $this->currency->format($order_info['total'], $order_info['currency_code'], 1.00000, false);
> $data['currency_code'] = $this->currency->getCode();

The result:
- currency_code is same selected currency which is displayed in front-store
- but amount is always the amount for Default Currency

For example:
- Select USD currency in front-store (this is default currency), the output is USD - 602.00
- Select EURO currency in front-store, the output is EUR - 602.00 (instead of 556.85 ad per the rate config)

Please help to resolve this issue as it impacts payment processing. Thanks.

**Comment by danielkerr** [comment]
yes this is how its supposed to work!

**Comment by danielkerr** [comment]
make sure the default currency value is always set to 1.00000

**Comment by nvphuc1989** [comment]
Hi Daniel,
I used the default setting of OpenCart 2.x to check this issue (the same happens in OpenCart 1.5.x). The default currency (e.g USD) value is always set to 1.00000.
Can you please check the amount & currency passed to payment gateway in the authorized.net AIM module when a buyer select non-default currency in front-store? How can we can pass the amount in default currency but with different  the currency code? I'm develop a payment gateway for OpenCart so I'm very desire to understand this behavior. I'm expecting I wrong so please help to explain. Thanks.

**Comment by aspokes** [comment]
hello,
i am facing the same issue with reference to @nvphuc1989 . @danielkerr Is there a way to go about it?

**Comment by sachinmngla** [comment]
Hi,
Can anyone please update about mentioned issue.  I'm facing this issue on opencart 2.3.0.2.

**Comment by abdulwad7869** [comment]
I can try to solve this currency change issue. contact on skype: bc090402913 or email abdulwad7869@gmail.com

**Comment by abdulwad7869** [comment]
No fee will be charged. I will solve your issue via teamviewer.
