### ISSUE TITLE
Issue at the Extension Installer

### ISSUE THREAD

**Issue by thomeyone** [opencart/opencart#2809]
We get always the following issue by usin the extension installer. We tried different modules.
Seems to be a stores problem(?).
![capture](https://cloud.githubusercontent.com/assets/6048525/6780478/029fc2f0-d166-11e4-934d-35487e5caccb.PNG)

**Comment by danielkerr** [comment]
seems to be your hosts problem since no one else using opencart has ever reported this!

i suggest you reupload first
