### ISSUE TITLE
Html.tpl - Html Module. 

### ISSUE THREAD

**Issue by aWeirdo** [opencart/opencart#2811]
Hi,
First off, I'm sorry, 
but i have no clue how all that pull request and stuff works.. 
Minor bug, but annoying to look at.

When adding custom HTML code to your webstore via the HTML module, 
if you don't need a heading title for your code, the module still adds a empty ```<h2></h2> ```, which leaves very a ugly space.

File: upload/catalog/view/theme/default/template/module/html.tpl

Current code:
```
<div>
<h2><?php echo $heading_title; ?></h2>
<?php echo $html; ?></div>
```

Fix:
```
<div>
<?php if(!$heading_title){} else { ?>
<h2><?php echo $heading_title; ?></h2>
<?php } echo $html; ?></div>
```

123 and that ugly space is gone.

Keep up the good work!, just started using opencart, loving it  :) :+1:

**Comment by beifloyd** [comment]
I don't think they accept code from here.
pull request created for you here https://github.com/opencart/opencart/pull/2813
