### ISSUE TITLE
Langauge Option Not Working Properly In My Server.

### ISSUE THREAD

**Issue by suvamchikun** [opencart/opencart#2812]
Hi

I have a website esouqatar.com .the language option i have is not working.
its in Arabic and english .when am selecting arabic its working but when am moving it from arabic to english it is not working.

Can any resolve the issue.

**Comment by beifloyd** [comment]
The correct place to ask is the forum not here.

**Comment by danielkerr** [comment]
most likely you have the language cookie set the language for you.
