### ISSUE TITLE
Order model : language filename 

### ISSUE THREAD

**Issue by Golling** [opencart/opencart#2818]
Hello,

In the file :
``opencart/upload/catalog/model/checkout/order.php``

The files ``default.php`` on line 402 and 803 are loaded whereas they don't exist.

The files name of each language are the languages themselves (as english.php or french.php for example).

PS : I noticed that since the V2.0, the column ``filename`` in the ``language`` table has been deleted.

Have a nice day !

**Comment by osworx** [comment]
Because since 2.x the language filenames are **NOT the language name** (as it was before), changed to **default.php**

**Comment by GomDani** [comment]
So why this difference?

Index file

`$language = new Language($languages[$code]['directory']);`
`$language->load($languages[$code]['directory']);`

Order file

`$language = new Language($order_info['language_directory']);`
`$language->load('default');`
