### ISSUE TITLE
Feature request: Persian/Arabic Language and RTL Layout

### ISSUE THREAD

**Issue by AliMD** [opencart/opencart#2819]
Hi
We are plannig to build an official Persian language package for Opencart 2.
Do you accept our pull request for RTL theme structure and official Persian language support ?
And do you have any contributing/code guide line ?
Unfortunately some unofficial web sites like opencart.ir have translated the opencart but have made many changes and perhaps many bugs.
They have changed the licence and made all rights reserved for own!
We're so sorry about this situation and want to solve it as an official way.
Would you please accept our pull request?
Thank you in advance.

**Comment by jamesallsup** [comment]
Use the suggestion site please: http://opencart.uservoice.com

**Comment by AliMD** [comment]
It's mean you don't accept any pull request at all ?!
