### ISSUE TITLE
Undefined index in pp_express 2.0.1.1

### ISSUE THREAD

**Issue by markoRs** [opencart/opencart#2830]
PHP Notice: Undefined index: pp_express in controller/payment/pp_express.php. 

The line of code below:
$this->session->data['payment_method'] = $this->session->data['payment_methods']['pp_express'];

**Comment by VeeeneX** [comment]
Session data doesn't have any key pp_express, so when the problem occurs?

**Comment by markoRs** [comment]
When you reach the confirm pp_express page, it fill the error log with Undefined index: pp_express

**Comment by VeeeneX** [comment]
Can you turn debugging for pp_express; in your config set pp_express_test to 1

**Comment by markoRs** [comment]
Yup. It looks like no errors there and you can successfully make payments. Only thing reported is 

PHP Notice:  Undefined index: pp_express in 
/catalog/controller/payment/pp_express.php on line 695

**Comment by pekka2** [comment]
Is pp_express status Enabled? You see payments > pp_express > tab general

**Comment by danielkerr** [comment]
actually posting theline of the error is al;ways helpful!

**Comment by danielkerr** [comment]
try as a might i can not replicate this.

maybe your missing a file or modified something.
