### ISSUE TITLE
Paypal Express in 2.0.1.1 forces all currencies to USD, incorrectly converts value.

### ISSUE THREAD

**Issue by qphoria** [opencart/opencart#2836]
There are hardcoded references in catalog/controller/payment/pp_express.php for 'USD' but paypal supports other currencies besides that. It also doesn't seem to be converting correctly so you'll get 

12 CAD (which is like 9.46 USD)
When it gets to Paypal it shows as 12 USD

https://developer.paypal.com/docs/classic/api/currency_codes/#paypal

**Comment by manakill** [comment]
I have also noticed this.

**Comment by pine3ree** [comment]
I also reported this ... twice  
#2601 
#2768
