### ISSUE TITLE
Mail error

### ISSUE THREAD

**Issue by devtsit** [opencart/opencart#2840]
OpenCart 2.0.2.0

At the settings the key for the mail hostname is "config_mail_smtp_hostname".

Multiple files contains the line:
$this->config->get('config_mail_smtp_host')

I think it must be replaced with:
$this->config->get('config_mail_smtp_hostname')

e.g. admin/controller/common/forgotten.php
Line 37: $mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

**Comment by gsc1ugs** [comment]
Its not fixed for me, is there another file somewhere?
