### ISSUE TITLE
Category Bug (OpenCart 1.5.6.2)

### ISSUE THREAD

**Issue by mark4785** [opencart/opencart#2849]
Hello,

I am using Opencart version 1.5.6.2 and recently added a product to the category of 'accessories > Candles'. When I browse to the Candles subcategory on the frontend of the store the 'Accessories' page displays and the said product does not display.

When clicking on the Candles hyperlink it is evident that OpenCart is wrongly hyperlinking to the Accessories page.

**Comment by jamesallsup** [comment]
Please use the forum for 1.5.x issues. Only 2.x bug reports belong on GitHub. Thanks.

http://forum.opencart.com/
