### ISSUE TITLE
World Pay - on Module - gives 404 error if clicked - OC 2.0.2.1

### ISSUE THREAD

**Issue by stockmaster** [opencart/opencart#2850]
OC 2.0.2.1
on Extension -> Paying -> Clicking World Pay icon gives:

Not Found

The requested URL /support/apply/default.aspx was not found on this server.

URL:
http://support.worldpay.com/support/apply/default.aspx?PartnerID=E511AF91-E4A0-42DE-80B0-09C981A3FB61

**Comment by jamesallsup** [comment]
The URL was changed on a recent commit following request from Worldpay to https://online.worldpay.com/signup/ee48b6e6-d3e3-42aa-a80e-cbee3f4f8b09

**Comment by stockmaster** [comment]
James, was this commit you mention merged to master? I just took the latest RC from github and the link persists being wrong.

**Comment by jamesallsup** [comment]
https://github.com/opencart/opencart/blob/master/upload/admin/language/english/payment/worldpay.php

**Comment by stockmaster** [comment]
Found it yes, thank you! 
While on the topic of payments, commited a small fix there maybe you wana take a looksy
https://github.com/opencart/opencart/pull/2917
