### ISSUE TITLE
OcMod on OC 2.0.1.1 not correct search code

### ISSUE THREAD

**Issue by pro100Hub** [opencart/opencart#2855]
For example, I want to replace a piece of this code: 

     <h2><?php echo $heading_title; ?></h2>
      <?php if ($thumb || $description) { ?>
      <div class="row">
        <?php if ($thumb) { ?>
        <div class="col-sm-2"><img src="<?php echo $thumb; ?>" alt="<?php echo $heading_title; ?>" title="<?php echo $heading_title; ?>" class="img-thumbnail" /></div>
        <?php } ?>
        <?php if ($description) { ?>
        <div class="col-sm-10"><?php echo $description; ?></div>
        <?php } ?>
      </div>
      <hr>

How to do it through a modifier (ocmod)? OcMod after replacing writes: "Not Found"
How to add an additional .css style through modifier (ocmod)?

**Comment by jamesallsup** [comment]
Use the forum for generic questions, GitHub is for BUG REPORTING only.

http://forum.opencart.com/
