### ISSUE TITLE
undefined variable json when updating order history

### ISSUE THREAD

**Issue by gsc1ugs** [opencart/opencart#2857]
undefined variable json line 2490 order.php when updating order history, so the history cannot be changed, MAJOR bug

**Comment by gsc1ugs** [comment]
Ok I set json=array()

and then this thread sorted ok box out

http://forum.opencart.com/viewtopic.php?f=190&t=137498

**Comment by albertojmv** [comment]
Undefined variable: json in on line 2221

**Comment by pkhadka56** [comment]
@albertojmv https://github.com/opencart/opencart/issues/3436
