### ISSUE TITLE
openbay/ebay_new.tpl small errors

### ISSUE THREAD

**Issue by gob33** [opencart/opencart#2860]
File: opencart/upload/admin/view/template/openbay/ebay_new.tpl
There are many .prop('checked', 'checked'); left in this file.
Incorrect, this should be only .prop('checked', true); or .prop('checked', false);

**Comment by jamesallsup** [comment]
Thanks, OpenBay Pro files are handled on a separate fork - I'll update them there and will be merged before the next update too.
