### ISSUE TITLE
\system\library\mail.php ENT_QUOTES

### ISSUE THREAD

**Issue by opencart-russia** [opencart/opencart#2861]
Please return ENT_QUOTES to mail library

my mail
```
From: 	MyShop &quot;Elegans&quot; <shop@mail.ru>
```

**Comment by danielkerr** [comment]
dont add any nonoe normal characters that get converted in the store name, use the store title for

**Comment by opencart-russia** [comment]
Daniel, store name MyShop "Shop" this is not normal ??
Many people in different countries use a similar name store.
