### ISSUE TITLE
output date in mails

### ISSUE THREAD

**Issue by zoulou101** [opencart/opencart#2863]
Datum: 05am30UTC_f2015Sun, 05 Apr 2015 09:23:28 +000004am30_28092015Sun, 05 Apr 2015 09:23:28 +000030

ordermail, update mail

how to fix please ?

**Comment by GomDani** [comment]
Change

`$language->load('default');`

to

`$language->load($order_info['language_directory']);`

**Comment by flamx** [comment]
I have the same issue

"Date Ordered: 12pm30UTC_f2015Sun, 12 Apr 2015 19:15:10 +000004pm30_10072015Sun, 12 Apr 2015 19:15:10 +000030"

Which file to change?

**Comment by osworx** [comment]
See https://github.com/opencart/opencart/pull/2897
While Daniel closed this thread, I hope that he wakes up someday and fix all occurrencies of that!
He was the one who changed that.

**Comment by flamx** [comment]
Thanks, #2897 sorted the problem
