### ISSUE TITLE
[admin] V.2020 product options don't show

### ISSUE THREAD

**Issue by pvl11** [opencart/opencart#2865]
Hi all,
After fresh install, just opened "Canon EOS 5D" to look and try possibilities.
When I am trying to add an option to the product the autocomplete function on that field does not show all the default options installed.

**Comment by stockmaster** [comment]
Can confirm this. They will populate if you start to type options (ex: Si... for size). but if you only click in the empty box, only Color; date, Delivery Time, Date Time, File, show.

I think this might be related to the max 5 Query i reported in a dif commit sugestion.

admin\controller\catalog/options.php

Line 471 - 475

			$filter_data = array(
				'filter_name' => $this->request->get['filter_name'],
				'start'       => 0,
				'limit'       => 5
			);

Shouldnt "filter" be dynamic?

**Comment by danielkerr** [comment]
imagine if you have 1 million product options which some stores do! should it show all 1 million options!

no because your bandwidth and connection time out will be used up.

why is this so hard for you to work out????

@stockmaster

please advise you understand, so you don't keep posting the same bug messages over and over!

**Comment by stockmaster** [comment]
@danielkerr advise you to have a different attitude towards the people that actually bother to report. (i posted this once btw and only to reflect the concerns in the forum).
Regardless, i do understand the problem on unlimited, which doesn't mean your decision of limiting to 5 is the wiser. Is just Your decision. For everyone else having 10 options, and 15 categorys ONLY, it is not the best. But i guess they can manually change it.
