### ISSUE TITLE
language > name of main file

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#2866]
Just saw that with 2.0.2.0 the main language file is renamed back to LANGUAGE_NAME.php instead default.php

What is the reason for this and how will that be in the future??
Have we to assume with every x release a change - or did this happen because someone forgot to name it default.php?
If not, it would be nice to highlight such changes also in the changelog.
thx!

**Comment by danielkerr** [comment]
it was a mistake to have defualt.php it should have been the name of the language.
