### ISSUE TITLE
Code mixture ..

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#2870]
e.g. payment/worldpay.php:
``$_['entry_card'] = 'Store Cards';``
``$_['entry_secret_token'] = "Secret Token";``
``$_['entry_webhook_url'] = "Webhook URL:";``

1. '
2. "
3. : 

Using single and double quotes, colons and no colons ..
Maybe the creator of this file take a rest and check first other files.

**Comment by danielkerr** [comment]
yep this is a shootable offence
