### ISSUE TITLE
OC 2.0.2.0 OCMOD path wildcard with braces 

### ISSUE THREAD

**Issue by jorimvanhove** [opencart/opencart#2872]
It appears the OCMOD path wildcard functionality has changed.

Using `<file path="catalog/view/theme/*/template/{account,checkout}/{register,guest}.tpl">` works in OC 2.0.1.1 but not in OC 2.0.2.0

No error message is generated in the OCMOD log file, the expected modifications do not show up in the log.

**Comment by danielkerr** [comment]
the functionality has changed and is updated int he documentation, but it has never had error reporting for files that don't exist!

**Comment by jorimvanhove** [comment]
Thanks for clearing that up.

The documentation in the github wiki still mentions this example:

> Example:
>
>Direct file path.
>
>`<file path="catalog/controller/common/home.php">`
>Using braces allows for selecting multiple files and not having to repeat the code operation multiple times.
>
>`<file path="system/{engine,library}/{action,loader,config,language}*.php">`

From the 'modification.xml' file that ships with OC 2.0.2.0 I am deducing that it is still possible to modify multiple files at once, using this syntax: 

`<file path="system/engine/action.php,system/engine/loader.php,system/library/config.php,system/library/language.php">`
