### ISSUE TITLE
SEO URLs ampersands in product tags/keywords

### ISSUE THREAD

**Issue by tylerwatt12** [opencart/opencart#2873]
If there are ampersands in product tags/keywords, loading a product when SEO URLs are enabled gives this error
The page you requested cannot be found!
Appears in ver 2.0.1.1
If this was fixed past 2.0.1.1 please close

**Comment by danielkerr** [comment]
this will never be fixed because & are part of the html url standard!

http://www.htmlhelp.com/tools/validator/problems.html#amp

do some research before posting!

**Comment by tylerwatt12** [comment]
I'm well aware of HTML URL standard
The problem is tags with ampersands (e.g. B&W for Black and white) should not break loading a product page
SEO URL generation should be escaped with &amp; or %26, and the SEO URL decoder should process that properly.

Or at the very least striping ampersands when a user tries entering an ampersand into tags when editing the product.
