### ISSUE TITLE
Wrong query in admin/model/report/product

### ISSUE THREAD

**Issue by znvPredatoR** [opencart/opencart#2874]
In function getPurchased total sum is calculated as (**total** + tax) * quantity, when it should really be (**price** + tax) * quantity. 

```
public function getPurchased($data = array()) {
		$sql = "SELECT op.name, op.model, SUM(op.quantity) AS quantity, SUM((op.total+ op.tax) * op.quantity) AS total FROM " . DB_PREFIX . "order_product op LEFT JOIN `" . DB_PREFIX . "order` o ON (op.order_id = o.order_id)";
```

**Comment by danielkerr** [comment]
which version??

the latest version does not have this code! also i suggest you look for a fix on the current branch

**Comment by znvPredatoR** [comment]
Got it, will look next time.

**Comment by iLevye** [comment]
v2.0.1.0
