### ISSUE TITLE
Shared SSL broken

### ISSUE THREAD

**Issue by cese** [opencart/opencart#2875]
In commits 561f3452bce68edcb3afd8a65df82a8405069b15 and ccddcedcf19d209a952b82832d567b8af9778397, a setting was added to allow different domains to be used for the HTTP and HTTPS servers, which provides support for servers with shared SSL certificates.  However, in commit 5d161cd148f0c23a1a7c5431a197d131faa9832d, it was converted to a cookie-based solution, and it was removed entirely in b4773efaf83071da56cf5be2ccb3c40c26567400.

The setting for shared SSL, "config_shared," is still present, but searching through the code, it no longer has any function.  Could you please restore this functionality?

**Comment by cese** [comment]
If I restore the last working version of `catalog/controller/common/shared.php` (from commit 1cd9bceb217785013a500ffb1339ea8a04080533) and add the relevant line to `index.php`, the session IDs are appended to the HTTPS URLs again.  However, those session IDs are not accepted when moving from HTTP to HTTPS.  I've tried modifying `system/library/session.php`, but I haven't gotten it working yet...

**Comment by danielkerr** [comment]
dont waste my time posting crap like this. never use shared ssl as its not secure!

**Comment by Merc4Hire** [comment]
I believe that his topic need to be re-opened and not just closed with a snarky reply  "dont waste my time posting crap like this. never use shared ssl as its not secure! " is not a valid or helpful reply.

I am facing the exact same issue.  My company uses a wild card SSL on our server as we host over 200 websites, many of which are sub-domains.   It does not make business sense to incur the cost of additional IP addresses and SSL's.

Like Cese if I restore the last working version of catalog/controller/common/shared.php and add the relevant line to index.php, the session IDs are appended to the HTTPS but they accepted.

This is a serious issue for us that use product driven sub-domains for our carts.
