### ISSUE TITLE
Emails not working in 2.0.2.0

### ISSUE THREAD

**Issue by gsc1ugs** [opencart/opencart#2879]
Ok, I cannot get emails out of this version, I've just done a simple php to test my hosts mail and it works fine

$mail = new Mail();
$mail->protocol = "smtp";
$mail->smtp_hostname = "mail.mysite.com";
$mail->smtp_username = "admin@mysite.com";
$mail->smtp_password = "mypass";
$mail->smtp_port = "25";
$mail->smtp_timeout = "5";
$mail->setTo("admin@mysite.com");
$mail->setFrom("admin@mysite.com");
$mail->setSender("mysite");
$mail->setSubject("test from g");
$mail->setHtml("test from g");
$mail->send();
echo "mail sent";

Can someone point me into another direction to check please?

**Comment by stockmaster** [comment]
https://github.com/opencart/opencart/commit/56ef27d82e4f08c6de709ed75e0eafabe6d3cfa0

read that

**Comment by gsc1ugs** [comment]
Its not that... JUST FIXED IT

if ($this->protocol == 'mail') { LINE 156 in 
.......................\system\library\mail.php

before its was 

if ($this->protocol == 'Mail') {

... case senstive

**Comment by stockmaster** [comment]
Funny! :D well done!

**Comment by gsc1ugs** [comment]
Why have these been taken out pls?

html_entity_decode($subject, ENT_QUOTES, 'UTF-8');

**Comment by stockmaster** [comment]
https://github.com/opencart/opencart/commit/bd5696bc68ee60b819d712c8bfbe7b4812b5383e
"html_entity_decode should not be used inside the mail class as mail class should not know about what the request class is doing."

**Comment by gsc1ugs** [comment]
How come no errors? will it still send html mail?

**Comment by stockmaster** [comment]
you are asking things i know not how to answer. All i am saying is, IF you want to debug your code, be SURE you using the latest php files from here. So you not reporting or fixing something already fixed. GET github for windows.
