### ISSUE TITLE
Duplicate URL After SEO Enabled

### ISSUE THREAD

**Issue by pushpikasj** [opencart/opencart#2882]
Most of the URL s Works fine But for the homepage and a few other links Duplicate after SEO Enabled

Open Cart Version 2.0.2.1_rc
Linux hosting

1.
www.[DOMAIN NAME].com/index.php?route=common/home (When Click on the Web Main "Logo" image)
www.[DOMAIN NAME].com
2.
www.[DOMAIN NAME].com/index.php?route=information/information...id=4
www.[DOMAIN NAME].com/about_us
3.
atsmore.com/index.php?route=information/contact (No SEO URL)
4
http://atsmore.com/index.php?route=information/information&information_id=3 (No SEO URL)
5 etc...
-------------------------------
some research but fed up and frustrated

http://itechtuts.com/seo-friendly-urls-opencart-pages/

http://stackoverflow.com/questions/10813809/remove-index-phproute-common-home-from-opencart

http://stackoverflow.com/questions/16890265/how-can-i-remove-index-phproute-common-home-from-opencart-version-1-5-1

etc...

**Comment by danielkerr** [comment]
i know the issue. you have not put the correct path in htaccess.

here is not the place to post though!

**Comment by pushpikasj** [comment]
Only allows the use of search engine optimized URLs for product, category, manufacturer and information pages. SEO keywords are defined per product, category, manufacturer and information page, stored in a database table (url_alias) But Customer Service, Extra, My Accounts pages are Not SEO Enable.

SEO Enabled URL

Information

    About Us - [DOMAIN NAME]/about_us
    Delivery Information - [DOMAIN NAME]/delivery
    Privacy Policy - [DOMAIN NAME]/Privacy
    Terms & Conditions -  [DOMAIN NAME]/Terms

Not SEO URL

Customer Service

    Contact Us - [DOMAIN NAME]/index.php?route=information/contact
    Returns - [DOMAIN NAME]/index.php?route=information/contact
    Site Map - [DOMAIN NAME]/index.php?route=account/return/add

Extras

    Brands - [DOMAIN NAME]/index.php?route=product/manufacturer
    Gift Vouchers - [DOMAIN NAME]/index.php?route=account/voucher
    Affiliates - [DOMAIN NAME]/index.php?route=affiliate/login
    Specials - [DOMAIN NAME]/index.php?route=product/special

My Account

    My Account - [DOMAIN NAME]/index.php?route=account/login
    Order History - [DOMAIN NAME]/index.php?route=account/login
    Wish List - [DOMAIN NAME]/index.php?route=account/login
    Newsletter - [DOMAIN NAME]/index.php?route=account/login
