### ISSUE TITLE
Getting error on front end and back end " start up error " please resolve it.

### ISSUE THREAD

**Issue by hnugrv** [opencart/opencart#2883]
Hello sir
            Please help me. i am getting such a error on front end and also on back-end. 
error is "Warning: require_once(/home/oppssin/public_html/system/startup.php): failed to open stream: No such file or directory in /home7/oppssin/public_html/admin/index.php on line 17

Fatal error: require_once(): Failed opening required '/home/oppssin/public_html/system/startup.php' (include_path='.:/usr/local/lib/php') in /home7/oppssin/public_html/admin/index.php on line 17 "

i dont understnd too much, what it is. i have no idea why i am getting this error, its second time when this error has heppened. fist it happened on default open cart template, then i resolved it by just reinstalling the store, after that i changed theme, now again, i m getting this error, its stuck all the time , should i have to reset..
please help me in this regard.. I am giving you my ftp details access and domain name,,and please resolve this issue and suggest me what to do next time, if this thing happens again in future.

website url - www.oppss.in
      
Thanks and regards
         Gaurav

**Comment by milimar** [comment]
Your message is very kind, but unfortunately this is a place for bug reporting connected to OC v.2x. Still, you can try to obtain help  at the official forum of OC http://forum.opencart.com . I am telling you this because probably this ticket of yours will be closed without any explanation. 
Greetings

**Comment by danielkerr** [comment]
@milimar  thank you!
