### ISSUE TITLE
Mail: SMTP "getaddrinfo failed" error in OpenCart 2.0.2.0

### ISSUE THREAD

**Issue by neonapple** [opencart/opencart#2887]
This occurs only with OpenCart 2.0.2.0. All previous versions work fine with identical settings.
Reproduced on two separate installation instances both with and without vQmod. Local development (darwin) and on a commercial web host. 

This occurs when sending mail, such as order confirmation, forgotten password, etc when using smtp mail method.

"Mail" (phpmail) setting works fine. "SMTP" both with populated fields and unpopulated fields causes the same result below.

In my particular instance, I had used the following fields:
Mail Parameters: Blank
SMTP Hostname: ssl://smtp.gmail.com
port: 465
(I also tested other mail servers known to be working in previous versions including TLS on 587)

Warning: fsockopen(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /Users/default/Sites/local.oc/2020v/system/library/mail.php on line 168Warning: fsockopen(): unable to connect to :465 (php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known) in /Users/default/Sites/local.oc/2020v/system/library/mail.php on line 168Notice: Error: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known (0) in /Users/default/Sites/local.oc/2020v/system/library/mail.php on line 171

Line 168 ~ 171: (system/library/mail.php & vqcache/vq2-system_library_mail.php)
```php
			$handle = fsockopen($hostname, $this->smtp_port, $errno, $errstr, $this->smtp_timeout);

			if (!$handle) {
				trigger_error('Error: ' . $errstr . ' (' . $errno . ')');
```

**Comment by neonapple** [comment]
Other people having the same issue here:
http://forum.opencart.com/viewtopic.php?f=37&p=554379#p554379

**Comment by osworx** [comment]
Looking in the current mail class (and fixed that bug 5 minutes ago at a customers shop), it is always the same stupid bug Daniel does.
This is since OC 1.5.x .. do not know why he does not fix that!

**Comment by stockmaster** [comment]
James and Daniel did a lot of commits in the mail class in the last days.
Can you confirm the bug is still present on 2.0.2.1rc? and if so what is this bug? :D

**Comment by osworx** [comment]
Yes, they did a lot .. if good we will see.
Regarding the 'everlasting' bug: just check that line 
``$header .= 'Content-Type: multipart/related; boundary="' . $boundary . '"' . $this->newline . $this->newline;``
and you will see what is wrong.

**Comment by stockmaster** [comment]
Outside my scope of knowledge - but i am sure they will look at this and fix it?  
Fingers crossed! That Mail class been a pain in the .... for a while now!

**Comment by danielkerr** [comment]
the isse was that was the problem was smtp_hostname was left as smtp_host on some vars.

@osworxyou are wrong!

also because you are not the developer of opencart you only have a limited view of the issue. 

the issue is your mail server. its a setting that adds extra \n or converts \r. while this might be a problem with your server its not with the majority of other users.

**Comment by mihaiachim** [comment]
@danielkerr  so I need to do a mass search for smtp_host and replace with smtp_hostname 
or smtp_hostname replaced with smtp_host ?

**Comment by danielkerr** [comment]
olr exactly search for 

'config_mail_smtp_host'

replace with

'config_mail_smtp_hostname'

**Comment by mihaiachim** [comment]
Thanks a lot I have done and is working OK.
I have find an  other issue I do not had a Compare product button.
I did add it in there, and defice text_compare for this button.

**Comment by haxcop** [comment]
Hi, i am facing the same errors, could i know which files exactly do i have to look for and replace ? Thanks @danielkerr @mihaiachim 
Best Regards

**Comment by kombi747** [comment]
Here you go....

https://github.com/opencart/opencart/commit/b03149e4802cc4ac7e9f9ec59c7be4759840c98f

**Comment by haxcop** [comment]
Thanks @kombi747 long night changing this docs...

**Comment by kombi747** [comment]
If you have cpanel use file manager and do a search and replace or load the code manager extension into your site.  It has a nice search feature in it much like the locate command in linux....Happy changing..

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=17423&filter_search=CodeManager

**Comment by haxcop** [comment]
Thanks! for the Tip!, sort that out already with Coda2 anyway :dancer:, but somehow i still facing the issue that the SMTP Hostname don't keep saved the url path :-1:   anychance this happened to you too?.@kombi747
Regards

**Comment by kombi747** [comment]
I had to re-enter all my SMTP setting via the GUI system-> setting -> Mail... Once I did that everything worked after I edited the 18 pages... Which path are you losing?

**Comment by haxcop** [comment]
Hi, the system works fine sending the emails over phpmail trough the server and always leaving on system>Mail-Tab and selecting MAIL, but, if i want to configure oc to send over smtp and fill all the details for example = ssl://smtp.mandrillapp.com or tls://smtp.mandrillapp.com and click "Save", then when i get back to the system and check the credentials, the smtp field is empty again... and also if i let the smtp selected on the Mail Tab, the registration form on success is returned in blank page again, eventhogh that i've made all the correct modifications described above... 
here's the erro shown on Error.log
Undefined variable: config_mail_smtp_hostname in /home/haxcop/public_html/admin/view/template/setting/setting.tpl on line 1285

Any Clue or Help will be much Appreciate
Thanks @kombi747 @danielkerr

**Comment by haxcop** [comment]
i forgot to say i use the correct ports over ssl and without it. 465 / 587 and any possible combination so far.
Host smtp.mandrillapp.com
Port 587 
SMTP Username admin@mydomain.com 
SMTP Password any valid API key

**Comment by kombi747** [comment]
did you check the permissions?

**Comment by haxcop** [comment]
Hi, sorry for the delay, no i did not, if is not much to ask can you tell or show me steps to check it?. Cheers! @kombi747

**Comment by osworx** [comment]
@danielkerr 
>@osworx you are wrong!

>also because you are not the developer of opencart you only have a limited view of the issue.

>the issue is your mail server. its a setting that adds extra \n or converts \r. while this might be a >problem with your server its not with the majority of other users.

Correct, I am not THE developer, only 'one' of many .. and basically a user like thousands other.

And we both are correct - and wrong.

Basically adding 2 newlines at the last line of the header is wrong!
``$header .= 'Content-Type: multipart/related; boundary="' . $boundary . '"' . $this->newline . $this->newline;``
One (1) is enough and solved many of my customers headaches - fact.
While none at the last line would be the best.

Another issue (since 1.5) is, that you have 'only' ``\n`` as newline.
But in WIN* servers (which nobody should honestly use for webservices!), it should be ``\r\n``
Using ``PHP_EOL`` could solve that.

And an additional check for `\n \n\r` and `\r` would be not bad to use finally the correct newline.

Daniel, if you thank back a few years, we have troubles with that mail.class since a long time.
But this class (or better the mail function) is one of the main features of each store and essential (also in the meaning of being legal).
So this has to work `out-of-the-box` - no dicsussion.

**Comment by haxcop** [comment]
So nobody will fix the SMTP Function at all?. :8ball:  :/

**Comment by blacksoft38** [comment]
List of needs to change, all must be:
$mail->smtp_hostname = $this->config->get('config_mail_smtp_hostname');

\opencart-2.0.2.0\upload\catalog\controller\account\forgotten.php (1 hit)
	Line 32: $mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

 \opencart-2.0.2.0\upload\catalog\controller\affiliate\forgotten.php (1 hit)
	Line 32: $mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

 \opencart-2.0.2.0\upload\catalog\controller\information\contact.php (1 hit)
	Line 14: $mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

 \opencart-2.0.2.0\upload\catalog\model\account\customer.php (2 hits)
	Line 46: $mail->smtp_hostname = $this->config->get('config_mail_smtp_host');
	Line 72: 	$mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

 opencart-2.0.2.0\upload\catalog\model\affiliate\affiliate.php (2 hits)
	Line 31: $mail->smtp_hostname = $this->config->get('config_mail_smtp_host');
	Line 155:	$mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

\opencart-2.0.2.0\upload\catalog\model\catalog\review.php (1 hit)
	Line 27: $mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

\opencart-2.0.2.0\upload\catalog\model\checkout\order.php (3 hits)
	Line 679: 	$mail->smtp_hostname = $this->config->get('config_mail_smtp_host');
	Line 773: 	$mail->smtp_hostname = $this->config->get('config_mail_smtp_host');
	Line 833: 	$mail->smtp_hostname = $this->config->get('config_mail_smtp_host');
  \opencart-2.0.2.0\upload\catalog\model\checkout\voucher.php (1 hit)
	Line 118: 	$mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

 \opencart-2.0.2.0\upload\catalog\model\openbay\ebay_order.php (2 hits)
	Line 237: 	$mail->smtp_hostname = $this->config->get('config_mail_smtp_host');
	Line 512: 	$mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

  \opencart-2.0.2.0\upload\system\library\ebay.php (1 hit)
	Line 352: 	$mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

opencart-2.0.2.0\upload\system\library\openbay.php (1 hit)
	Line 303: 	$mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

**Comment by LoveWithOC** [comment]
I have changed and tried all, still I am not getting email notification. Surprisingly, I am not getting any error though.  My project is still pending because of this email notification error.

Opencart version 2.0.2.0. can any one help pls.

**Comment by blacksoft38** [comment]
LoveWithOC, mail adress at the store settings and the email settings mail adress must be same, pls check this and also system/library/mail.php try to make this changing, 
```
if ($this->verp) {
                         fputs($handle, 'MAIL FROM: <' . $this->from. '>XVERP' . "\r\n");
                    } else {
                         fputs($handle, 'MAIL FROM: <' . $this->from. '>' . "\r\n");
                    } 
if ($this->verp) {
                         fputs($handle, 'MAIL FROM: <' . $this->smtp_username . '>XVERP' . "\r\n");
                    } else {
                         fputs($handle, 'MAIL FROM: <' . $this->smtp_username . '>' . "\r\n");
                    }
```
This worked on mine. i hope it works for you too. 
good luck.

**Comment by LoveWithOC** [comment]
Lovely!  blacksoft38 works perfectly well.. Hurrayyyyyyy!!!! Thank You Very Muuuuuuuuuch....

**Comment by henrydc** [comment]
If you want to send email via marketing in the back-end, change the following as well

opencart-2.0.2.0\upload\admin\controller\marketing\contact.php (1 hit)
Line 239: $mail->smtp_hostname = $this->config->get('config_mail_smtp_host');

**Comment by Dobratr** [comment]
I have the same problem and I can't solve it.

2015-05-03 17:30:58 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/xgogecom/public_html/system/library/mail.php on line 166
2015-05-03 17:30:58 - PHP Warning:  fsockopen(): unable to connect to :25 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/xgogecom/public_html/system/library/mail.php on line 166

I did all renaming host -> hostname that mentioned above and I correct mail.php as mentioned but I can't see ant mail in my Inbox. I test this mail with contact function and I doublecheck contact.php that I made the correction.

**Comment by LoveWithOC** [comment]
Yes, for me Contact Mail is not working, rest all is fine.

**Comment by Dobratr** [comment]
At my site I get this error after sign in
Warning: fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/xgogecom/public_html/system/library/mail.php on line 166Warning: fsockopen(): unable to connect to :25 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/xgogecom/public_html/system/library/mail.php on line 166Error: E-Mail to required!
I'm out of solution. Pls somebody help me.

**Comment by blacksoft38** [comment]
Dobratr, can you try to change mail host port number ;) And you need to learn the smtp port of your mail host. For example mine is 587. I guess your error is this.

**Comment by Dobratr** [comment]
My had changed it as my hosting provider showed.

![1](https://cloud.githubusercontent.com/assets/12221478/7446441/3688dc78-f1e1-11e4-8a6c-48456f40e7d4.JPG)

It's odd because in error code it says can't connect to :25. Wasn't it suppose to say "can't connect to :587"?

Warning: fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/xgogecom/public_html/system/library/mail.php on line 166
Warning: fsockopen(): unable to connect to :25 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/xgogecom/public_html/system/library/mail.php on line 166Error: E-Mail to required!

> Dobratr, can you try to change mail host port number ;) And you need to learn the smtp port of your mail host. For example mine is 587. I guess your error is this.

**Comment by Dobratr** [comment]
~~this~~

**Comment by blacksoft38** [comment]
yes I guess, error supposed to be 587. did you tried to use google's captcha? Mine was giving error before  I use it too. And also i use mail.blabla.com for hostname. store mail adress and email settings username must be same too.  All these are what I did. And my mails are all working fine, admin side and site front too.

**Comment by blacksoft38** [comment]
166Error: E-Mail to required! - this error message made me think about mail adress in store settings and email settings might be different.

**Comment by LoveWithOC** [comment]
To get error free first you add your email address in gmail > setting > account and Import > Add a POP3 mail account you own.  Mine All working all fine..  Good Luck.

**Comment by Middleman77** [comment]
If you have still problems esp. with SMTP, remember to use localhost or 127.0.0.1 as the hostname.
This includes if you use SSL.

Anyways I've done the full config_mail_smtp_hostname changes. They are included in the file here: http://we.tl/rRVSxcaNiZ

This also includes the catalog/model/account/customer.php changes regarding Email to required.

**Comment by juggalox2008** [comment]
hey middleman77 ive uploaded your fix and i still having trouble

2015-05-10 19:16:42 - PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/user/public_html/system/library/mail.php on line 168
2015-05-10 19:16:42 - PHP Warning:  fsockopen(): unable to connect to :587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/user/public_html/system/library/mail.php on line 168
2015-05-10 19:16:42 - PHP Notice:  Error: php_network_getaddresses: getaddrinfo failed: Name or service not known (0) in /home/user/public_html/system/library/mail.php on line 171

my settings are

Mail Protocol: smtp
Mail Parameters: blank
SMTP Hostname: smtp.gmail.com
SMTP Username: user@gmail.com
SMTP Password: pass
SMTP Port: 587
SMTP Timeout: 5

ive even try my localhost email settings and still the same thing and i even used the mail protocol mail. and when i use the mail protocol and says it sent emails but doesnt

**Comment by Middleman77** [comment]
Juggalox2008,

In addition to this, you need to make the following adjustments:

1) Update 2.0.2.0 fix via Extension Installer with this file:

https://raw.githubusercontent.com/pekka2/OpenCart-Migration-Upgrade-Tool/master/bugs_2.0.2.0-fix.ocmod.xml

2) Add these columns to your database to prevent the SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data OK error' as well as the registration account creation error.

http://forum.opencart.com/viewtopic.php?f=181&t=135170#p530983

3) If you are sending mail direct from your server, there's no need to fill in all the details even using SSL. Just set the Mail protocol to Mail, and hostname to either localhost or 127.0.0.1 using port 25 (as it is sending it internally which folks forget sometimes). This is what I use:

Mail Protocol: Mail
Mail Parameters: -femail@mydomain.com
SMTP Hostname: blank
SMTP Username: blank
SMTP Password: blank
SMTP Port: 25
SMTP Timeout: 5

4) Make sure that your store email setting is the same email used above.

5) If you still want to use smtp, after you've made the above changes maybe you also need to do this:

Mail Protocol: smtp
Mail Parameters: -fuser@gmail.com
SMTP Hostname: tls://smtp.gmail.com
SMTP Username: user@gmail.com
SMTP Password: pass
SMTP Port: 587
SMTP Timeout: 5

Check the SMTP port is the correct one given by your webhost, as some providers use others.
For Gmail you may have to change the port to 465 if 587 doesn't work.

Also if using the SMTP+SSL setting make sure you've added your https:// to your HTTPS server settings under the root /config.php and admin/config.php files.

**Comment by rsmck** [comment]
Another simple fix for this for those not wanting to edit code is to insert the 'missing' key into MySQL;

```INSERT INTO `oc_setting` (`setting_id`, `store_id`, `code`, `key`, `value`, `serialized`)
VALUES
	(NULL, 0, 'config', 'config_mail_smtp_host', 'smtp.example.com', 0);```

**Comment by msieprawski** [comment]
For all who are experiencing this issue: there are three ways to fix this.

#### Global fix 1
Do like @rsmck wrote - I'll work.

#### Global fix 2
1. Open file `system/library/mail.php`
2. Under line 166 `} elseif ($this->protocol == 'smtp') {` add:
```php
if (empty($this->smtp_hostname)) {
    $this->smtp_hostname = 'mysmtp.host.name';
}
```

#### Better approach
If you are not able to pull/update your opencart code (whatever your reason is) you have to manually search for `config_mail_smtp_host` and change to `config_mail_smtp_hostname` in all files.

The issue is bigger than changing just 1 line. For example I started from register action. My customers were able to register but they didn't recieve any emails. So I went to `catalog/model/account/customer.php` file where I found this line:
```php
$mail->smtp_hostname = $this->config->get('config_mail_smtp_host');
```
This is wrong because there is `config_mail_smtp_hostname` in configuration. Now this bug has been  fixed (commit 7d42e75d256bd8ee0f6ffa5ad794486b91b5b3b5) and there is:
```php
$mail->smtp_hostname = $this->config->get('config_mail_smtp_hostname');
```

**Comment by haxcop** [comment]
This error is already fixed on the last version 2.0.3 it work. 


Yours faithfully 
Carlos Lozada

**Comment by DaisyOne** [comment]
Thanks all.

**Comment by DaisyOne** [comment]
Thanks all of you.I have done as @blacksoft38 's solutions.Now it reminders "SyntaxErroe:Unexpected token<OK      <b>Notice</b>:Error:EHLO not accepted from server! in <b>D:\......\system\library\mail.php</b>on line<b>197</b>".
And I don't know why ?

**Comment by gsaadi** [comment]
I'm using 2.0.2.0 and I've changed all instances of 'config_mail_smtp_host' to 'config_mail_smtp_hostname'
All e-mail features work (marketing, e-mail order confirmation to customer, contact form...etc) except I don't receive an e-mail notification when new order is placed on website although I have the "send notification e-mail" checked. Any help with this would be appreciated. Thanks

**Comment by neeraj10786** [comment]
Hi,

Thanks for the solution now i m getting email notification now perfectly.. but i have one more question
in admin i am not getting any of Notification message in NOTIFICATION BAR ( Right Top )
what can i do for it ??

**Comment by videfrancisco** [comment]
Hi guys, im using 2.0.3.1 and i get this error in multistore/multilangue, in default store i can use forgot password, but in another store i get this error.

Notice: Error: DATA not accepted from server! in /var/www/html/system/library/mail.php on line 418

**Comment by dominick01234** [comment]
Hi - I read through most of this stream, but I am not exactly clear.  I am using Opencart Version 2.0.3.1.  My php emails are working, but my smtp email from the contact form is not sending anything.  Has this issue regarding:

'config_mail_smtp_host'

replace with

'config_mail_smtp_hostname'


been fixed?  

My site is working great.  Just need to address this issue.  Thanks for your help.  Here are the log errors:

2015-11-12 22:47:37 - PHP Warning:  fsockopen(): unable to connect to smtp.1and1.com:587 (Connection timed out) in /homepages/22/d535240346/htdocs/openCart/system/library/mail.php on line 170
2015-11-12 22:47:37 - PHP Notice:  Error: Connection timed out (110) in /homepages/22/d535240346/htdocs/openCart/system/library/mail.php on line 173

**Comment by dominick01234** [comment]
Okay I just tried this and it doesn't appear to have solved it:
Global fix 2

Open file system/library/mail.php

@msieprawski commented on May 27
Under line 166 } elseif ($this->protocol == 'smtp') { add:
if (empty($this->smtp_hostname)) {
    $this->smtp_hostname = 'mysmtp.host.name';
}

**Comment by dominick01234** [comment]
However, there are no longer errors in my log after using the contact form ... so not sure

**Comment by dominick01234** [comment]
All is working.  Initial issue with contact form was that I was forwarding all http to https with .htaccess.  That broke the form.  Secondly, I didn't realize the form didn't send to the contacts in the alert list under store->settings.  It only sends to store owner.  

Cheers

**Comment by sundarrajan360** [comment]
Hi,
In Opencart 2.2 after configuired SMTP in admin panel, I am getting below error while registering user,
Warning: fsockopen(): unable to connect to ssl://smtp.gmail.com:465 (Connection refused) in /mypath /system/library/mail.php on line 167
Fatal error: Uncaught exception 'Exception' with message 'Error: Connection refused (111)' in /mypath /system/library/mail.php:170 Stack trace: #0 /mypath/catalog/model/account/customer.php(55): Mail->send() #1 [internal function]: ModelAccountCustomer->addCustomer(Array) #2 /mypath /system/storage/modification/system/engine/loader.php(150): call_user_func_array(Array, Array) #3 [internal function]: Loader->{closure}(Array) #4 /mypath /system/engine/proxy.php(13): call_user_func(Object(Closure), Array) #5 /mypath /catalog/controller/account/register.php(21): Proxy->__call('addCustomer', Array) #6 /mypath /catalog/controller/account/register.php(21): Proxy->addCustomer(Array) #7 [internal function]: ControllerAccountRegister->index() #8 /mypath /system/storage/modification/system/engine/action.php(44): call_user_fun in /mypath /system/library/mail.php on line 170

I have found a solution online from below link, **but in opencart 2.2 already these changes are done still I am getting the above error.** 
https://github.com/opencart/opencart/issues/2887
Please help me to resolve this issue.
**SMTP Configuiration:**
Hi,
In Opencart 2.2 after configuired SMTP in admin panel, I am getting below error while registering user,
Warning: fsockopen(): unable to connect to ssl://smtp.gmail.com:465 (Connection refused) in /mypath /system/library/mail.php on line 167
Fatal error: Uncaught exception 'Exception' with message 'Error: Connection refused (111)' in /mypath /system/library/mail.php:170 Stack trace: #0 /mypath/catalog/model/account/customer.php(55): Mail->send() #1 [internal function]: ModelAccountCustomer->addCustomer(Array) #2 /mypath /system/storage/modification/system/engine/loader.php(150): call_user_func_array(Array, Array) #3 [internal function]: Loader->{closure}(Array) #4 /mypath /system/engine/proxy.php(13): call_user_func(Object(Closure), Array) #5 /mypath /catalog/controller/account/register.php(21): Proxy->__call('addCustomer', Array) #6 /mypath /catalog/controller/account/register.php(21): Proxy->addCustomer(Array) #7 [internal function]: ControllerAccountRegister->index() #8 /mypath /system/storage/modification/system/engine/action.php(44): call_user_fun in /mypath /system/library/mail.php on line 170

I have found a solution online from below link, but in opencart 2.2 already these changes are done still I am getting the above error. 
https://github.com/opencart/opencart/issues/2887
Please help me to resolve this issue.
![untitled](https://cloud.githubusercontent.com/assets/17548427/16170035/e0454fac-3561-11e6-91e9-8b5421c6892e.jpg)

**Comment by glstrade** [comment]
blacksoft38's answer really solved my problem! I have tried almost everything online, and can't believe I accidentally find the final answer here, which was posted 3 years ago... Feel so lucky!

![image](https://user-images.githubusercontent.com/43131089/45282927-ff2b5680-b50e-11e8-8155-8631228f547d.png)
