### ISSUE TITLE
Bootstrap still contains some dubble stylesheets on container

### ISSUE THREAD

**Issue by tverheijen** [opencart/opencart#2891]
Bootstrap still contains some dubble stylesheets on container

../catalog/view/javascript/bootstrap/css/bootstrap.min.css

@media (min-width:1200px){
	.container{
		width:1135px
	}
}
@media (min-width:1200px){
	.container{
		width:1135px
	}

**Comment by danielkerr** [comment]
your telling me why? because i run the bootstrap project?

**Comment by tverheijen** [comment]
wats the meaning of  haveing it twice ?

@media (min-width:1200px){
 .container{
 width:1135px
 }

------

@media (min-width:768px){
	.container{
		width:750px
	}

}

@media (min-width:992px){
	.container{
		width:970px
	}

}

@media (min-width:1200px){
	.container{
		width:1135px
	}

}

@media (min-width:1200px){
	.container{
		width:1135px
	}

}
