### ISSUE TITLE
On order update, Click notify Customer they dont get notified OC 2.0.2.0

### ISSUE THREAD

**Issue by gsc1ugs** [opencart/opencart#2892]
If someone can tell me in  \admin\controller\sale\order.php where abouts this happens pls

**Comment by stockmaster** [comment]
This is NOT the support forum. 
But. are you using phpmail or SMTP?
Did you upgrade your install with the latest MAIL fixes from github? if not little point on reporting here.

Can you PLEASE elaborate more your reports?

....

**Comment by gsc1ugs** [comment]
Initial order mail comes through, when you edit and order in admin and click notify customer, no emails are sent, yes i have all the MAIL changes I'm using the "MAIL" protocol

**Comment by danielkerr** [comment]
i think this has been anwsered all ready. try search the mail issues
