### ISSUE TITLE
re-Captcha does not work on reviews

### ISSUE THREAD

**Issue by karlpers** [opencart/opencart#2894]
When Google re-Captcha is used, nothing happens on product pages/review form. In Firebux, I get:

Undefined index: g-recaptcha-response

I have configured an account, and set it up correctly I think. It looks normal, but nothing happens after I push the Continue button. The re-Captcha works just fine the contact page.

**Comment by milimar** [comment]
This issue has already been resolved.

**Comment by karlpers** [comment]
Oh! Sorry. I didnt see it among the closed issues. Case closed
