### ISSUE TITLE
error after buy gift voucher and some problem

### ISSUE THREAD

**Issue by Hamid0311** [opencart/opencart#2896]
Hi i have some problems on opencart 2.0.2.0

when my customer buy gift voucher in admin i get this error

Notice: Undefined variable: order_products in /public_html/oc2/admin/view/template/sale/order_form.tpl on line 240Notice: Undefined variable: order_products in /public_html/oc2/admin/view/template/sale/order_form.tpl on line 242Warning: Invalid argument supplied for foreach() in /public_html/oc2/admin/view/template/sale/order_form.tpl on line 242

on email the logo or image of gift voucher not show

on google hangouts module i get this error

<b>Notice</b>: Undefined variable: code in <b>admin\view\template\module\google_hangouts.tpl</b> on line <b>31</b>

and a big problem from older version of opencart until now is problem of www and non www 
add to cart not work and the font-awesome not work and font icon miss because of this problem 
if the url on config be with www on non www this problem happen and if url on config be without www on www this problem happen 
always i should fix it by htaccess and redirect i want to know why you dont fix this problem?
Thanks

**Comment by Hamid0311** [comment]
any help for this problems?

**Comment by stockmaster** [comment]
@Hamid0311  test this for your voucher issue
http://forum.opencart.com/viewtopic.php?f=190&t=143366&p=555907#p555907
