### ISSUE TITLE
Customer Service, Extra, My Accounts pages are Not

### ISSUE THREAD

**Issue by pushpikasj** [opencart/opencart#2898]
Only allows the use of search engine optimized URLs for product, category, manufacturer and information pages. SEO keywords are defined per product, category, manufacturer and information page, stored in a database table (url_alias) But the the Issue Customer Service, Extra, My Accounts pages are Not SEO Enable.

SEO Enabled URL

Information

About Us - [DOMAIN NAME]/about_us
Delivery Information - [DOMAIN NAME]/delivery
Privacy Policy - [DOMAIN NAME]/Privacy
Terms & Conditions -  [DOMAIN NAME]/Terms

Not SEO URL

Customer Service

Contact Us - [DOMAIN NAME]/index.php?route=information/contact
Returns - [DOMAIN NAME]/index.php?route=information/contact
Site Map - [DOMAIN NAME]/index.php?route=account/return/add

Extras

Brands - [DOMAIN NAME]/index.php?route=product/manufacturer
Gift Vouchers - [DOMAIN NAME]/index.php?route=account/voucher
Affiliates - [DOMAIN NAME]/index.php?route=affiliate/login
Specials - [DOMAIN NAME]/index.php?route=product/special

My Account

My Account - [DOMAIN NAME]/index.php?route=account/login
Order History - [DOMAIN NAME]/index.php?route=account/login
Wish List - [DOMAIN NAME]/index.php?route=account/login
Newsletter - [DOMAIN NAME]/index.php?route=account/login

![sam](https://cloud.githubusercontent.com/assets/9498899/7105006/ff7875a2-e120-11e4-91c7-cc90d80faa8d.png)

**Comment by danielkerr** [comment]
donmt report feature requests. the seo urls are on the pages that matter!

**Comment by pushpikasj** [comment]
@danielkerr  I apologize for the inconvenience.  can you please clarify this for me. i did not get any clear answer for this issue form Community Forums - OpenCart. Some Are SEO Some are Non SEO. is there are any advantage getting from Non SEO Urls like. or is that some thing wrong with my configuration. 

Customer Service

Contact Us - [DOMAIN NAME]/index.php?route=information/contact
Returns - [DOMAIN NAME]/index.php?route=information/contact
Site Map - [DOMAIN NAME]/index.php?route=account/return/add

**Comment by vipinks** [comment]
It is really awkward that some of URLs are not SEO URLs!!
