### ISSUE TITLE
No canonical url on special pages

### ISSUE THREAD

**Issue by jeroencusters** [opencart/opencart#2900]
On special pages (catalog/controller/product/special.php) the canonical url (rel="canonical") is not available. This leads to duplicate title errors in Google Webmaster Tools for the special pages. Category and manufacturer pages are working fine.

**Comment by tiborbesze86** [comment]
I've implemented rel="prev/next" pagination on my website as a vQmod, and here's a code snippet you could use for the special pages, by inserting it into your `catalog/controller/product/special.php` file, just after the line `$data['pagination'] = $pagination->render();`, or by creating a vQmod/OCMod xml file for it.

```
if ($pagination->page == 1) {
	$this->document->addLink($this->url->link('product/special', '', 'SSL'), 'canonical');
} elseif ($pagination->page == 2) {
	$this->document->addLink($this->url->link('product/special', '', 'SSL'), 'prev');
} else {
	$this->document->addLink($this->url->link('product/special', $url . '&page='. ($pagination->page - 1), 'SSL'), 'prev');
}
if ($pagination->limit && ceil($pagination->total / $pagination->limit) > $pagination->page) {
	$this->document->addLink($this->url->link('product/special', $url . '&page='. ($pagination->page + 1), 'SSL'), 'next');
}
```

**Comment by dtjones** [comment]
@tiborbesze86 should all pages have the 'canonical' link or just page one

**Comment by danielkerr** [comment]
done. forgot which commit though
