### ISSUE TITLE
Opencart 1.5.6.4 : COD orders jumps to missing orders

### ISSUE THREAD

**Issue by Aaina0292** [opencart/opencart#2901]
I've read all the other threads about missing orders, but what makes this different is that I'm using "Free Checkout" and "Cash on Delivery" as my payment methods, which don't need to make an external call to a payment processor. I've checked everything that I could think of and can't seem to figure it out. I've been using OpenCart 1.5x for a while with no issues.

**Comment by danielkerr** [comment]
re save cash on delivery. maybe you deleted the order status that was set to
