### ISSUE TITLE
Opencart is not loading english.php defined text variables

### ISSUE THREAD

**Issue by waqasghouri89** [opencart/opencart#2903]
I have uploaded my code on my host and install Opencart 2.0.2.0. After installation my front-end website is not loading all the variables defined in english.php file under catalog/language/english/english.php.

Due to this all the variables are not showing actual text on my front-end website. 

when I add 
"$this->load->language('english.php');"
in each file inside catalog/Controller/ 
then it load all the variable from english.php, I don't know what is this happen?

Can anyone help me to fix this issue ASAP?

**Comment by danielkerr** [comment]
should bhe english/english

**Comment by waqasghouri89** [comment]
Thank DanielKerr, 

My problem is, by default in my opencart variables in catalog/language/english/english.php are not reading, 

So I had tried to test my english,php  in register controller, I have added "$this->load->language('english');" this line and all the variable in "english.php" loaded.. 

I want to know why in my opencart all the variables are not loading by default? Why should I add this line in each controller..

**Comment by osworx** [comment]
Because Mr. Superbrain changed the behaviour with the lastest (2.0.2.0) version without any further notice!
Changed from default.php to LANGUAGE_NAME.php
Unfortunetaly he did not changed all occurences of default.php and introduced a new bug.
