### ISSUE TITLE
Manual Order status change triggers email to customer regardless of notification flag

### ISSUE THREAD

**Issue by ainelena** [opencart/opencart#2904]
Reference issue # 2576 - this was close prematurely without the fix -  it is a bug,
the system has a "Notify Customer" check box - we should be able to use it to control whether or not notify user on a particular status change.
However this flag is currently disabled or something, the system somehow decides by itself when to send notifications, and this is cumbersome and confusing.
If changes cannot be made to software at this point, please suggest how to fix the bug manually to override the system behavior.

Thanks
Elena

**Comment by ainelena** [comment]
For those who struggles with same issue as me ("Notify customer" flag in order history makes no difference and system still sends out emails to customer on every status update), the manual fix is pretty easy:
file /catalog/model/checkout/order.php is doing that (even though you are changing status in Admin, change comes from catalog anyways).
in that file there is a function addOrderHistory, where close to the very end - around line 773 - there is a code that is commented like this:
// If order status is not 0 then send update text email
within this piece of code find a line that actually sends the email, it looks like this:
$mail->send();
and surround this line with an IF condition, so it now looks like this:
if ($notify) {
    $mail->send();
}

After this change the status (or any other history) update will be send out as email to customer ONLY when flag "Notify Customer" is set.

**Comment by aWeirdo** [comment]
I would suggest something like this instead:
    			// If order status is not 0 then send update text email
			if ($order_info['order_status_id'] && $order_status_id && $notify) {

**Comment by danielkerr** [comment]
it will always send the order status changes out but wont send the comments. thats what notify means. notify the comments. there rally is not reason to not let the customer know his order status has changed!

juts how you think something should work.
