### ISSUE TITLE
Main store always using "home" layout, despite of selection in "Settings"

### ISSUE THREAD

**Issue by msva** [opencart/opencart#2905]
Hi there! I've found that store, that is selected as "default" always render "Home" layout, despite of you select in it's settings (for example, I trying to set it up to render "default" layout, which I also use for "secondary" stores, and I also tried to select any other layout, and it always render "Home").

In the same time, "secondary" stores obey the layout setting and renders specified layout.

**Comment by msva** [comment]
Although, if I remove "path" settings from "Home" layout, Main store starts to render selected layout instead of home.

It looks very strange and probably somehow related to upgrade from 1.5.x...

**Comment by danielkerr** [comment]
i just tested this on the default opencart install and it works howit should. 

if its an upgrade issue you might need to ask a developer to help you. maybe use the contact us form on the opencart.com web site.

**Comment by danielkerr** [comment]
you might need to delete the Home layout or change the route.
