### ISSUE TITLE
ADMIN  LOGIN NOT WORKING

### ISSUE THREAD

**Issue by manojkatta143** [opencart/opencart#2906]
WWW.CHARVICRAFTS.IN/ADMIN

Fatal error: Uncaught exception 'ErrorException' with message 'Error: MySQL server has gone away<br />Error No: 2006<br />UPDATE oc_currency SET value = '1.00000', date_modified = '2015-04-13 15:37:28' WHERE code = 'INR'' in /home/ussinuxm/public_html/charvicrafts.in/system/database/mysqli.php:41 Stack trace: #0 /home/ussinuxm/public_html/charvicrafts.in/system/library/db.php(20): DBMySQLi->query('UPDATE oc_curre...') #1 /home/ussinuxm/public_html/charvicrafts.in/admin/model/localisation/currency.php(141): DB->query('UPDATE oc_curre...') #2 /home/ussinuxm/public_html/charvicrafts.in/admin/controller/common/home.php(193): ModelLocalisationCurrency->updateCurrencies() #3 [internal function]: ControllerCommonHome->index() #4 /home/ussinuxm/public_html/charvicrafts.in/system/engine/front.php(42): call_user_func_array(Array, Array) #5 /home/ussinuxm/public_html/charvicrafts.in/system/engine/front.php(29): Front->execute(Object(Action)) #6 /home/ussinuxm/public_html/charvicrafts.in/admin/index.php(162): Front->dispatch(Object(A in /home/ussinuxm/public_html/charvicrafts.in/system/database/mysqli.php on line 41

**Comment by stockmaster** [comment]
all URLS are case sensitive
http://www.charvicrafts.in/admin/

**Comment by manojkatta143** [comment]
still not working

**Comment by stockmaster** [comment]
yes it does
![image](https://cloud.githubusercontent.com/assets/4859025/7119410/6123f51a-e1fd-11e4-8cdb-642f9dfcbef4.png)

**Comment by manojkatta143** [comment]
after entering username and password i am geting this error

Fatal error: Uncaught exception 'ErrorException' with message 'Error: MySQL server has gone away
Error No: 2006
UPDATE oc_currency SET value = '1.00000', date_modified = '2015-04-13 15:37:28' WHERE code = 'INR'' in /home/ussinuxm/public_html/charvicrafts.in/system/database/mysqli.php:41 Stack trace: #0 /home/ussinuxm/public_html/charvicrafts.in/system/library/db.php(20): DBMySQLi->query('UPDATE oc_curre...') #1 /home/ussinuxm/public_html/charvicrafts.in/admin/model/localisation/currency.php(141): DB->query('UPDATE oc_curre...') #2 /home/ussinuxm/public_html/charvicrafts.in/admin/controller/common/home.php(193): ModelLocalisationCurrency->updateCurrencies() #3 [internal function]: ControllerCommonHome->index() #4 /home/ussinuxm/public_html/charvicrafts.in/system/engine/front.php(42): call_user_func_array(Array, Array) #5 /home/ussinuxm/public_html/charvicrafts.in/system/engine/front.php(29): Front->execute(Object(Action)) #6 /home/ussinuxm/public_html/charvicrafts.in/admin/index.php(162): Front->dispatch(Object(A in /home/ussinuxm/public_html/charvicrafts.in/system/database/mysqli.php on line 41

**Comment by osworx** [comment]
But you know what that means: `Error: MySQL server has gone away
Error No: 2006`
See: https://dev.mysql.com/doc/refman/5.0/en/gone-away.html
Has basically nothing todo with the shop.

**Comment by jamesallsup** [comment]
Use the forum for this type of support.
