### ISSUE TITLE
Custom customer field sort order not working

### ISSUE THREAD

**Issue by leslieblakewood** [opencart/opencart#2907]
In the administration panel:

After adding new custom fields in Sales > Customers > Custom Fields and setting their sort order, if you then edit a customer (also in the admin panel), the custom fields are always sorted by name instead of the sort order stored in the database.

**Comment by filip-mustatea** [comment]
Where I cand found the answer?

**Comment by leslieblakewood** [comment]
It was fixed in commit 6e95c48
<https://github.com/opencart/opencart/commit/6e95c487cbb109ce7e9925d8d9a8073ea244c9a4>
.

**Comment by filip-mustatea** [comment]
Thanks. 


     În Luni, 26 Octombrie 2015 15:01:45, Leslie Wood <notifications@github.com> a scris:
   

 It was fixed in commit 6e95c48
<https://github.com/opencart/opencart/commit/6e95c487cbb109ce7e9925d8d9a8073ea244c9a4>
.
