### ISSUE TITLE
language files

### ISSUE THREAD

**Issue by atnaples** [opencart/opencart#2908]
order.php/voucher.php have:

	$language = new Language($order_info['language_directory']);
	$language->load('default');

is it supposed to be:

	$language = new Language($order_info['language_directory']);
	$language->load($order_info['language_directory']);

**Comment by pine3ree** [comment]
opencart 2.0 $language->load('default'); will load the default.php file in the current language directory.
```php
english/default.php
```
opencart 1.5 used to name the main language file according same as the dicrectory.
```php
english/english.php
```

**Comment by atnaples** [comment]
yes, i know 2.0.1 uses different name for main language file
-------------------------
sorry, i might say not correct: 2..0.2... (same as 1.5.6 english/english)

**Comment by pine3ree** [comment]
oh, yeah, you are right, i was checking 2.0.1....

**Comment by atnaples** [comment]
It's a mess, and becomes annoying: -(

**Comment by osworx** [comment]
It IS a mess, and this bug as already discussed - several times (here & in the forum)!
Because not only ``voucher.php`` is affected.

**Comment by pine3ree** [comment]
As a quick fix, until what naming convention will be definitevely used has been decided, you could symlink default.php to the main language file, or viceversa....depending on the version. Since library/language checks using file_exists() and not is_file(), it will work.

**Comment by danielkerr** [comment]
fixed
