### ISSUE TITLE
Customer Registration, blank screen, Error: E-Mail to required!

### ISSUE THREAD

**Issue by flamx** [opencart/opencart#2910]
OC 2.0.2.0
using SMTP

After new customer registration - blank screen.

Error Log: PHP Notice:  Error: E-Mail to required! in /system/library/mail.php on line 61

Confirmation email was sent to customer but no email was sent to store owner.

Before I had this issue #2887 which was succesfully sorted (thanks Daniel) by mass replace 'config_mail_smtp_host' to 'config_mail_smtp_hostname'

But now I getting "Error: E-Mail to required!"

Yes, I have seen issue #2852 but it did not helped

**Comment by opencart-russia** [comment]
https://github.com/opencart/opencart/pull/2888

**Comment by dskonline** [comment]
#2847

**Comment by flamx** [comment]
Thank you opencart-russia and dskonline. This fixed a problem.

**Comment by gsc1ugs** [comment]
How to I find the conclusion to this thread please? I have same problem, cant find answer
