### ISSUE TITLE
Opencart 2 filter module not work

### ISSUE THREAD

**Issue by borisov87** [opencart/opencart#2912]
1.I install filter module
2.Create filters
3.assign filters to category and products
4.assign module to home and product layout

but filters not displayed . I use opencart with default theme

**Comment by GomDani** [comment]
Is filter module enabled or only installed?

**Comment by borisov87** [comment]
Installed and enabled , this is demo shop, where i test
http://boyarsoft.com/tiptop/admin/
user: admin
pass: admin@
Please try and see problem.

**Comment by GomDani** [comment]
Lool at http://boyarsoft.com/tiptop/desktops filters working.

**Comment by borisov87** [comment]
Hm, but on home and all product page filter missing, i assign filter module to this pages - home, products, but filter missing

**Comment by GomDani** [comment]
Filters works only in category page.
