### ISSUE TITLE
Cash on Delivery payment lacks loading "data-loading-text" attribute

### ISSUE THREAD

**Issue by thekrotek** [opencart/opencart#2918]
Well, subject says it all. Here's a confirm button code:

```html
<input type="button" value="<?php echo $button_confirm; ?>" id="button-confirm" class="btn btn-primary" />
```

Missing line in TPL:

```html
data-loading-text="<?php echo $text_loading; ?>"
```

Missing line in controller:

```php
$data['text_loading'] = $this->language->get('text_loading');
```

**Comment by jamesallsup** [comment]
Just tested and works ok.

Looks like it is handled in the ajax, not the form element.

		beforeSend: function() {
			$('#button-confirm').button('loading');
		},

**Comment by thekrotek** [comment]
@jamesallsup, no, it does NOT work! More specifically, it shows "Loading" only in English. "data-loading-text" attribute is what allows you to make in you site's language.

So, in short, lack of this attribute shows default 'loading...' value from JS. Open ANY other payment method and see for yourself. Then switch your site to some other language and look, how "Loading" changes everywhere except CoD.

Please, next time, look into the issue more closely, before closing the ticket.

**Comment by jamesallsup** [comment]
I'll reopen and investigate again.
