### ISSUE TITLE
Language load issues

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#2919]
Now that OpenCart 2.0.2.0 doesn't use the 

catalog/language/\*/default.php
admin/language/\*/default.php

files anymore, the following files need to be fixed:

catalog/model/checkout/order.php,
catalog/model/checkout/voucher.php,
catalog/model/openbay/ebay_order.php
admin/model/sale/voucher.php
system/library/openbay.php

They should use:

````
$language->load($order_info['language_directory']);
````

instead of the old

````
$language->load('default');
````

Having said that, it would have been better to continue using 'default.php' files in the main language folders rather than changing them to 'english.php' etc, then it wouldn't have broken above listed files, nor any of the 3rd party language packs or extensions!

**Comment by evx** [comment]
Hi! 
I had the same problem. I fixed it with a solution suggested by "opencartjazz.com":
http://www.opencartjazz.com/en/opencart-module/oc2011/oc2011-bugfix-default-language-fallback

The solution will make Open Cart to look in the language default.php.

Replace .../system/library/language.php with the following code:
```
<?php
class Language {
        private $default = 'english';
        private $directory;
        private $data = array();

        public function __construct($directory = '') {
                $this->directory = $directory;
        }

        public function get($key) {
                return (isset($this->data[$key]) ? $this->data[$key] : $key);
        }

        public function load($filename) {
                $_ = array();

                $files = array(
           DIR_LANGUAGE . $this->default   . '/' . $filename . '.php',
           DIR_LANGUAGE . $this->directory . '/' . 'default.php',
           DIR_LANGUAGE . $this->directory . '/' . $filename . '.php'
           );

       foreach($files as $file)
       {
           if (file_exists($file)) {
               require($file);
           }
        }

                $this->data = array_merge($this->data, $_);

                return $this->data;
        }
}
```

I hope the developers will implement or fix this as soon as possible.

Best Regards

**Comment by osworx** [comment]
it is a pitty that Daniel does not fix that nonsens asap!
Publishing a new version = introducing new bugs!
Always the same shit.

**Comment by stockmaster** [comment]
osworx, Daniel and James seem to pull your commits quite fast. 
Cant you add this in to try to streamline the situation? same as https://github.com/opencart/opencart/issues/2920?

**Comment by osworx** [comment]
I am tired of such things ..
Because with NO time for testing a PRErelease, instead publishing fast(er) then you can look, new bugs are out and we should make pull requests all the time.
Not our job.
Daniel has paid stuff - should they do their job!

**Comment by stockmaster** [comment]
Cant argue with that for sure! Thanks for explaining

**Comment by danielkerr** [comment]
@evx  tis would not fix the issue.

@osworx  currently i have been working on another opencart related project and soon will start rewriting the main oc web site. I don't have a lot of spare time at the moment to fix the bigs that have been popping up.

i'm open to making you a opencart project admin on github. you will be able to commit the fixes yourself. i just need to confirm with james also i need to make sure you wont start adding loads of features. 

things are not always so simple. the mail issue you replied to last week would have caused more issues. your fix would have stopped mails being sent for a lot of users while it might have fixed your own issues.

**Comment by atnaples** [comment]
nobody needs to load lots of features, but review what is good, was good, and what must be moved from ocmods to the core without really changing the core functionality...
that's simple, clean what really needs to be cleaned... and keep moving

- multi-stores;
- big data;
- order processing/payment from admin;
- using more % instead of absolute values;
- a few extra modules: last viewed, also bought, etc.
- payment/shipping for ex: FedEx is terrible implementation

... it will very nice cart, i personally struggle with myself to drop it, but I like it...

**Comment by osworx** [comment]
@danielkerr please see PM.

**Comment by atnaples** [comment]
so far nothing...

**Comment by mhcwebdesign** [comment]
@atnaples: This place here is only for specific bug reports, please post your general suggestions on the OpenCart forum!

**Comment by atnaples** [comment]
. wow, thanks for reminder, if i am not mistaken i reported this bug 5 days ago, other people talked about this in forum and... it's not fixed. am i wrong? do not think so, but e-mail confirmations, customers receive, are mess.

**Comment by stockmaster** [comment]
2.0.2 was released on march 31st, lots of bugs been reported since. nearly non been fixed.
Get in qeue! lol

**Comment by atnaples** [comment]
you know what some people do, after got tired staying in the line... i see just a few guys who are on github and forum all the time. may be it's time to join?

**Comment by stockmaster** [comment]
is weekend, i expect no one to be here. i am just a caveman with too much invested in this to have weekends! ;)

**Comment by atnaples** [comment]
me too... i still like to write some code, but i would like the to have web sites those are functional and wasting my weekend on line-by-line cleaning the mess

**Comment by stockmaster** [comment]
want something to get entertained?
help me figure out why handling fee is acting as a low order fee
http://forum.opencart.com/viewtopic.php?f=191&t=143588 
"order must reach > x for it to kick in"
however its acting the other way around, it will add handling fee if order is UNDER specified x value.

**Comment by atnaples** [comment]
never tried, but why not...

**Comment by stockmaster** [comment]
Yup that was it!
One more for pull request lol

**Comment by evx** [comment]
I think Open Cart has big potential, but right now, I'm out... I wish you all good luck with all the bugs.

**Comment by stockmaster** [comment]
Lot of this seem to be a bit of rushed, non verified copy/pasting of code, which one cant blame anyone.
But they are so Simple bug fixes i am unsure why they take so long to be commited :(

on the bright side, is sharpening my coding skills! lol

**Comment by atnaples** [comment]
to @ stockmaster

what about replacing

$this->cart->getSubTotal() < $this->config->get('handling_total')
with
$this->cart->getSubTotal() > $this->config->get('handling_total')

unfortunately, you should like in my ocmod "free shipping is really free", because the problem with special/discounted products.

did i fix or not?

**Comment by atnaples** [comment]
don't leave us evx :-)

**Comment by nuke123** [comment]
Simple fix just copy 'catalog/language/english/english.php' to 'catalog/language/english/default.php' and same for admin

**Comment by import35** [comment]
oke guys, got the solution for second language packs for opencart.

bugissue: * not showing icons (like: myaccount, language etc etc..) * not putting your default language really to default on live webshops!

solution: .htaccess.TXT (save this document as .htaccess (no TXT! save with *all documents selected)

then add the following text after line 31 (install Notepad++ to see line numbers:

```
RewriteEngine On
RewriteCond %{HTTP_HOST} ^[^.]+\.[^.]+$
RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [L,R=301]
```

**Comment by danielkerr** [comment]
If u setup ur config.php properly u won't have this issue.
