### ISSUE TITLE
Multiple orders on checkout

### ISSUE THREAD

**Issue by thekrotek** [opencart/opencart#2920]
During checkout process, when you're on the latest stage and new order with zero status already created, if you decide to go back and change something, a new order will be created again. And again, and again for each time you go back to update payment, shipping or address. Such strange behavior existed in OC 1.0 as well and I was surprised, that it still exists.

in catalog/controller/checkout/confirm there's a line:

```php
$this->session->data['order_id'] = $this->model_checkout_order->addOrder($order_data);
```
It definitely needs a check for existing order ID in current session:

```php
if (!isset($this->session->data['order_id'])) {
	$this->session->data['order_id'] = $this->model_checkout_order->addOrder($order_data);
} else {
	$this->model_checkout_order->editOrder($this->session->data['order_id'], $order_data);
}
```

I've tested in on my store and it works perfectly. Can't find any issues with it, but my database doesn't have a bunch of empty orders anymore.

Not sure, why it hasn't been implemented. Is there any reason for this?

**Comment by stockmaster** [comment]
Please DO make Pull requests on your suggestions. Seem necessary.

**Comment by thekrotek** [comment]
@stockmaster I'm trying to right now. This is probably one of the most confusing and overcomplicated things I saw for the years. And documentation is plain awful. Might take some time.

**Comment by dskonline** [comment]
I just want to say thanks to thekrotek, stockmaster and others for contributing to help stabilize opencart. I updated my shop to 2.0.2.1 thinking it would be a little more stabilized than it was with a RC version being pushed but it pretty much broke everything. What version do you recommend as a stable version for a production environment?

**Comment by stockmaster** [comment]
Yes is not the most straight forward bit for sure. 
but basicly you got to fork the repository -> edit in yours and create a commit, then pull request into master of Opencart. 
Myself i do it by trial and error :D

**Comment by stockmaster** [comment]
@dskonline, at the moment? None! 2.0.1 is broken in some ways - 2.0.2.x is broken in anothers. Trying to see if i can figure that question myself, i stoped deployement untill further notice.

**Comment by dskonline** [comment]
Well keep up the good work people like me who have no coding skills and payed for allot of opencart modules over time trying to start a business not to mention the $500+ a year server, who can't afford to start all over,  gives us small people hope that something may work in the future. been sitting here with a dead site since I converted in October 2014.. I just wanted to say thank you again for giving us a fighting chance...

**Comment by stockmaster** [comment]
@dskonline i Hear you on the costs, and the dead store front... thank god in my case i have a secundary domain up and working

**Comment by creativelogic** [comment]
It seems Opencart v2 is still a long way of before its advisable for the
production environment, I will stick to Opencart 1.5.6.4 for the live shops

**Comment by thekrotek** [comment]
@creativelogic if you can code, you can use it :-)

**Comment by danielkerr** [comment]
THIS IS NOT A BUG!

this is the blind leading the blind again!

"I've tested in on my store and it works perfectly. Can't find any issues with it, but my database doesn't have a bunch of empty orders anymore."

the order details would be over written if the customer returns to the checkout confirm. 

they could pay for a low priced item then click back until they reached the cart page and adds lots of items to their cart then go back to the checkout confirmation page without paying!

it works how its supposed to work and how many other carts work.

**Comment by danielkerr** [comment]
if i included a pull with your code in it would thousands of shops open to this type of hack. it woudl cost me a lot of business and would be posted across all the vulnerability databases.

**Comment by thekrotek** [comment]
@danielkerr so you mean it is normal to leave tens, hundreds or even thousands of orders with zero status in database, right?

I do not insist on my fix. The point was to clean the multiple "lost" orders to keep database smaller. Right now, if I go back and checkout again 10 times, then confirm, I'll have 9 bogus entries in database. Imagine, I have 1000 orders per day and each customer goes back and forth 10 times before confirming checkout. It's 9000 of additional entries in order table, which will never be used!

I'm very much OK, if you suggest your own solution to this issue.

By the way, my pull request also contains a fix for mail object on registration process. This one can be safely merged.

**Comment by danielkerr** [comment]
last time i will repeat my self. this is not an issue! its a issue in your head. its how you think sonething should work but in reality it does not.
your soultion will lead to people being able to get products for free.

the only thing that needs to be concurrent is the invoice. not order id.

**Comment by danielkerr** [comment]
you should never delete any order data or customer data. 

but if u insist then set the system to depete orders with order status of 0 that are over 1 month old.

**Comment by thekrotek** [comment]
I already told you, that I do NOT insist on my solution and you are free to provide our own. My point was to keep database clean. I think, it's a pretty good reason.

> the only thing that needs to be concurrent is the invoice. not order id. 

Sure. All my orders have invoce_no set to zero. Very concurrent.

> you should never delete any order data or customer data. 

Why not? I delete them all the time and NEVER had a single issue. I absolutely fail to understand, why are you zealous about UNCONFIRMED orders.

> but if u insist then set the system to depete orders with order status of 0 that are over 1 month old.

Yes, I even have an extension for that. I just wondered, why this couldn't be implemented in core OC.

**Comment by danielkerr** [comment]
because paypal and many other payment gateways require an order id before the order informtion is sent to them. 

also there is no guarantee the payment gateway will reach the store. many times has paypals callback system has stopped working due to some network issue on their end.

**Comment by hayden-t** [comment]
hey i just arrived here after noting this seemingly odd behavior. my client actually had me track it does as a bug as the order numbers in admin where not sequential and wondered what was happening to the orders. 
tracked it down in 1.5 and 2.0 and then wound up here... i think i can see the points in both sides, but why not just make an order not remove/update able by client cart process once payment successful ? then you get the best of both worlds no ?
