### ISSUE TITLE
owl-carousel issue on Safari browser

### ISSUE THREAD

**Issue by Dvir-Julius** [opencart/opencart#2921]
Hello Daniel,

I have noticed an issue with the owl-carousel when using Safari browser.
When the owl-carousel slides an image, the top nav links color are getting brighter, and as soon the owl-carousel finished the sliding of the image, the color returns to normal.
The same issue occurs with the featured products name on the main page.

On Chrome and Firefox it is working without any problem,  the issue is on Safari only.

Thanks,
Dvir

**Comment by Dvir-Julius** [comment]
I forgot to say that I am using Macintosh, so I don't know if this issue occurs with Safari for Windows.

**Comment by Firestorm-Graphics** [comment]
add z-index: 1 or higher to .owl-carousel

**Comment by jamesallsup** [comment]
Is this issue still present on your install? Just tested on Safari with Yosemite 10.10.3 but could not replicate

@Dvir-Julius Can you supply some screen shots and also a link that has the problem.

**Comment by Dvir-Julius** [comment]
@jamesallsup 

Yes, it is still present.
I am using Macintosh with Yosemite 10.10.3, and latest Safari.

You will need a very good eyes to see the differences between the images, but when actually working with the Safari, you will not miss it.
 
Attached are 2 images:
The first image represents a static slider  - product name is shown correctly.
the second image was taken while the slider is moving, the product name becomes lighter.
![1](https://cloud.githubusercontent.com/assets/9422670/7738776/ea1ad764-ff60-11e4-88ab-678cd7b84e41.png)
![2](https://cloud.githubusercontent.com/assets/9422670/7738779/ee2f609a-ff60-11e4-87a0-6715c61d9851.png)

**Comment by Dvir-Julius** [comment]
@jamesallsup 

While investigating my images, A good example is Canon EOS 5D.  Take a very good look at the 5D.
You will see the difference between the 2 images. The letter D is much lighter at image 2 than image 1

**Comment by iSaulius** [comment]
I have same problem.

**Comment by jamesallsup** [comment]
@Dvir-Julius Thanks for the extra info, I'll take a look into this. Did you try the suggestion by @Firestorm-Graphics? I'm not convinced a z-index will cause this but I'll check it out anyway..

**Comment by Dvir-Julius** [comment]
@jamesallsup 
The z-index 1 solved the issue on Safari. Adding z-index 1 to the owl-carousel while using the Safari's debugger did the trick. I also enabled and disabled the z-index in the debugger to see it very carefully before reporting again, and it is working like a charm. 
You can close the ticket by applying the z-index.

@Firestorm-Graphics Thank for the tip

**Comment by Dvir-Julius** [comment]
@jamesallsup 
I am closing this issue as I already send a PR #3033.
