### ISSUE TITLE
ocMod regex operations are never trimmed

### ISSUE THREAD

**Issue by opencarthelp** [opencart/opencart#2925]
The trim attribute is ignored for regex search operations. Code similar to the regular search operation should be added for regex:

```php
$trim = $operation->getElementsByTagName('search')->item(0)->getAttribute('trim');

if (!$trim || $trim == 'true') {
	$search = trim($search);
}
````

Otherwise a regex with whitespace is very likely to fail.

**Comment by danielkerr** [comment]
so u add soem regex to account for white space

s+ i think

**Comment by opencarthelp** [comment]
Not the code.  The XML file.
