### ISSUE TITLE
Unable to Edit Orders 

### ISSUE THREAD

**Issue by rajivdr** [opencart/opencart#2926]
Keep getting  the following error on Edit order, Version of OC is 2.0.2.0
Have check both maintenance mode as well as the oc_setting table for ap_id key and value which match to the api user

SyntaxError: JSON Parse error: Unexpected EOF
OK

**Comment by beifloyd** [comment]
Error Confirmed -
 Edit order from Back-end  won't go pass the message - Payment method required! - 
OC 2.0.2 PHP5.4

**Comment by stockmaster** [comment]
Two different issues. @beifloyd click the "update" little button in front of payment method, it shall sort your problem. 
@rajivdr  yes the same issues in many of my builds, cant figure it out. Done all the steps ppl have in forum, nothing sorts mine.

**Comment by iSaulius** [comment]
order editing is terrible in OC2, Is it suitable for everyone?

**Comment by stockmaster** [comment]
This "SyntaxError: JSON Parse error: Unexpected EOF" is a bit of a unexplainable plage
Some ppl find easy fixes, be it by API, or by htaccess file, of by simple screw ups during install.
The biggest problem is when you do the WHOLE list of possible fixes and the problem persists. Surelly its a very sensible system and a smallest change in envoriment breaks your install. I am for sure reconsidering if opencart is a solution for any serious live shop atm.

**Comment by gsc1ugs** [comment]
PUT THIS ON LINE 2425 ADMIN/CONTROLLER/SALE/ORDER.PHP

$json = array();

**Comment by stockmaster** [comment]
wont work, like i said i tried all the sugestions in forum.

**Comment by danielkerr** [comment]
link to your web site helps.

**Comment by stockmaster** [comment]
https://www.lojadofolclore.pt
can give you full admin previleges, just wont post those in public. Advise how to send them please?

**Comment by stockmaster** [comment]
in fact never mind, i created a user just for you full admin 
user & pass danielkerr
if anyone can figure it out i am all ears!

**Comment by GomDani** [comment]
I think the problem is in one of config file or in htaccess.

**Comment by stockmaster** [comment]
Root Config File:
<?php
// HTTP
define('HTTP_SERVER', 'https://www.lojadofolclore.pt/');

// HTTPS
define('HTTPS_SERVER', 'https://www.lojadofolclore.pt/');

// DIR
define('DIR_APPLICATION', '/home/gsadesig/public_html/lojadofolclore.pt/catalog/');
define('DIR_SYSTEM', '/home/gsadesig/public_html/lojadofolclore.pt/system/');
define('DIR_LANGUAGE', '/home/gsadesig/public_html/lojadofolclore.pt/catalog/language/');
define('DIR_TEMPLATE', '/home/gsadesig/public_html/lojadofolclore.pt/catalog/view/theme/');
define('DIR_CONFIG', '/home/gsadesig/public_html/lojadofolclore.pt/system/config/');
define('DIR_IMAGE', '/home/gsadesig/public_html/lojadofolclore.pt/image/');
define('DIR_CACHE', '/home/gsadesig/public_html/lojadofolclore.pt/system/cache/');
define('DIR_DOWNLOAD', '/home/gsadesig/public_html/lojadofolclore.pt/system/download/');
define('DIR_UPLOAD', '/home/gsadesig/public_html/lojadofolclore.pt/system/upload/');
define('DIR_MODIFICATION', '/home/gsadesig/public_html/lojadofolclore.pt/system/modification/');
define('DIR_LOGS', '/home/gsadesig/public_html/lojadofolclore.pt/system/logs/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'gsadesig_ldf2015');
define('DB_PASSWORD', 'ldf2015ldf');
define('DB_DATABASE', 'gsadesig_ldf2015');
define('DB_PREFIX', 'oc_');


Admin config file
<?php
// HTTP
define('HTTP_SERVER', 'https://www.lojadofolclore.pt/admin/');
define('HTTP_CATALOG', 'https://www.lojadofolclore.pt/');

// HTTPS
define('HTTPS_SERVER', 'https://www.lojadofolclore.pt/admin/');
define('HTTPS_CATALOG', 'https://www.lojadofolclore.pt/');

// DIR
define('DIR_APPLICATION', '/home/gsadesig/public_html/lojadofolclore.pt/admin/');
define('DIR_SYSTEM', '/home/gsadesig/public_html/lojadofolclore.pt/system/');
define('DIR_LANGUAGE', '/home/gsadesig/public_html/lojadofolclore.pt/admin/language/');
define('DIR_TEMPLATE', '/home/gsadesig/public_html/lojadofolclore.pt/admin/view/template/');
define('DIR_CONFIG', '/home/gsadesig/public_html/lojadofolclore.pt/system/config/');
define('DIR_IMAGE', '/home/gsadesig/public_html/lojadofolclore.pt/image/');
define('DIR_CACHE', '/home/gsadesig/public_html/lojadofolclore.pt/system/cache/');
define('DIR_DOWNLOAD', '/home/gsadesig/public_html/lojadofolclore.pt/system/download/');
define('DIR_UPLOAD', '/home/gsadesig/public_html/lojadofolclore.pt/system/upload/');
define('DIR_LOGS', '/home/gsadesig/public_html/lojadofolclore.pt/system/logs/');
define('DIR_MODIFICATION', '/home/gsadesig/public_html/lojadofolclore.pt/system/modification/');
define('DIR_CATALOG', '/home/gsadesig/public_html/lojadofolclore.pt/catalog/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'gsadesig_ldf2015');
define('DB_PASSWORD', 'ldf2015ldf');
define('DB_DATABASE', 'gsadesig_ldf2015');
define('DB_PREFIX', 'oc_');


I did notice theres no closing ?> but i didnt changed for the sake of not touching anything

**Comment by GomDani** [comment]
define('HTTP_SERVER', 'https://www.lojadofolclore.pt/'); must be

define('HTTP_SERVER', 'http://www.lojadofolclore.pt/');

**Comment by stockmaster** [comment]
Well thats the thing though, all forum posts sugest as a "fix" to define http to https as well.

**Comment by GomDani** [comment]
This is mine and works:

// HTTP
define('HTTP_SERVER', 'http://www.gombac.si/');
define('HTTP_IMAGE', 'http://www.gombac.si/image/');

// HTTPS
define('HTTPS_SERVER', 'https://www.gombac.si/');
define('HTTPS_IMAGE',  'https://www.gombac.si/image/');

**Comment by stockmaster** [comment]
i can change it for sure, mind you the installer itself does those changes on clean install (i checked) it installs itself as http = https if you do a install based on a ssl install domain. so not sure, honestly, whats going on. Maybe daniel might give us a clue, a final one!

**Comment by GomDani** [comment]
I had a similar problem and the problem was in the config.php. Try change where: 

HTTPS_SERVER -> https://

and where is

HTTP_SERVER -> http://

**Comment by stockmaster** [comment]
I will let Daniel look into it before doing changes, or he will be looking at a moving target.
However if it is as you say, the install script must be revised.

**Comment by rajivdr** [comment]
It is working for me now, i used the .htaccess file within the apache config to lockdown the website which caused the issue, removing it seems to solve the problem for me, Also did create a separate api user/key

**Comment by stockmaster** [comment]
@GomDani
"I had a similar problem and the problem was in the config.php. Try change where:

HTTPS_SERVER -> https://

and where is

HTTP_SERVER -> http:/"
no change
