### ISSUE TITLE
Handling Total Operator Typo - Greater Than instead of less than

### ISSUE THREAD

**Issue by stockmaster** [opencart/opencart#2929]
upload/catalog/model/total/handling.php

Fixed Handling fee typo on operator
"The checkout total the order must reach before this order total becomes
active."

Order total must be GREATER than instead of Less than

if (($this->cart->getSubTotal() > $this->config->get('handling_total'))
&& ($this->cart->getSubTotal() > 0)) {
$this->load->language('total/handling');

https://github.com/stockmaster/opencart/commit/68dba1bbbc9f2fbeccbeac57ee7753b6e527a991

**Comment by danielkerr** [comment]
added your pull request

**Comment by stockmaster** [comment]
Thank you!
Skrill referal link URL still needs you to fix, to know which is which as current is 404
