### ISSUE TITLE
SMTP host config setting is wrong

### ISSUE THREAD

**Issue by jcdarwin** [opencart/opencart#2930]
In `admin/controller/setting/setting.php` and `admin/view/template/setting/setting.tpl` we have `config_mail_smtp_hostname`, however everywhere else (including, importantly, `admin/controller/marketing/contact.php`) we have `config_mail_smtp_host`.

Because of this, if we set the SMTP host in the admin settings screen, SMTP will not work, instead throwing an error on line 171 in `system/library/mail.php`.

It seems that `admin/controller/setting/setting.php` and `admin/view/template/setting/setting.tpl` should be amended to refer instead to `config_mail_smtp_host`

**Comment by kombi747** [comment]
Already reported see below...

https://github.com/opencart/opencart/issues/2887#issuecomment-94155983

https://github.com/opencart/opencart/commit/b03149e4802cc4ac7e9f9ec59c7be4759840c98f
