### ISSUE TITLE
Modification refresh results maintenance mode on

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#2931]
After pushing button refresh in the modification list the 
maintenance mode in the settings default store is switched on.
As logged in admin the default store is working the others are in maintenance mode.
oc version 10 min. old

**Comment by danielkerr** [comment]
try the main branch

**Comment by agatha65** [comment]
Same issue with the very latest code from here and clean install.
My quick fix:
lines 63 - 68
```
$org_maintenance = $this->config->get('config_maintenance');
			//if (!$this->config->get('config_maintenance')) {
				$this->load->model('setting/setting');

				$this->model_setting_setting->editSettingValue('config', 'config_maintenance', '1');
			//}
```
and lines 418 - 420:
```
//if ($org_maintenance != $this->config->get('config_maintenance')) {
				$this->model_setting_setting->editSettingValue('config', 'config_maintenance', $org_maintenance);
			//}
```
Than go to admin and change your store settings if the store is wrongly on maintenance mode.

I think there is a problem with this all, because it is not handling the multistore feature. Only the store id 0 is temporarily put in maintenance mode during the modification refreshing.

**Comment by bijak8** [comment]
I have the same issue with my website for opencart 2.0.3.1. It goes on maintenance mode for other people but not for admin.

**Comment by buzzdev** [comment]
Hi,
i don't know, why this was closed.
I have the same issue with official 2.0.3.1 version.

**Comment by xguntis** [comment]
The same is here https://github.com/opencart/opencart/pull/3077, but this change is still not implemented in the main branch for some reason.

**Comment by bijak8** [comment]
From what I understand, it was done on purpose.

To fix it, you will need to install a mod (it's free):-
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=22694&filter_license=0&filter_download_id=41&page=8

**Comment by buzzdev** [comment]
Thanxs... i've fixed it myself already.
