### ISSUE TITLE
PayPal currencies list lack RUB

### ISSUE THREAD

**Issue by thekrotek** [opencart/opencart#2932]
There's no RUB in PayPal currencies list. Russian rouble is available at least for 1.5 years and should be added. Pull request is not needed here, just add a RUB to the list, that's it.

**Comment by danielkerr** [comment]
in your mind

**Comment by thekrotek** [comment]
What did you just say? Why did you close this issue? Did you fix it or what?

```php
		$currencies = array(
			'AUD',
			'CAD',
			'EUR',
			'GBP',
			'JPY',
			'USD',
			'NZD',
			'CHF',
			'HKD',
			'SGD',
			'SEK',
			'DKK',
			'PLN',
			'NOK',
			'HUF',
			'CZK',
			'ILS',
			'MXN',
			'MYR',
			'BRL',
			'PHP',
			'TWD',
			'THB',
			'TRY'
		);
```

See, no RUB? It doesn't show on payments list during checkout, if current currency is RUB.

**Comment by thekrotek** [comment]
Please, stop acting like a 15 y.o. teenager. I've reported you and existing issue and you again answered "in you mind". This time IT IS an issue, which should be fixed. I don't see any reason not to do so.
