### ISSUE TITLE
Gift Vourcher recepient never recieved Email

### ISSUE THREAD

**Issue by stockmaster** [opencart/opencart#2937]
OC 2.0.2 with latest patches

When a customer buys a Gift Voucher, and this order becomes complete in the back end an confirmation email is sent to buyer.
Everyone receives an email. admin - customer (so mail is working!)
However the gift voucher recipient never receives the email for this gift voucher, not on purchase, not on any Order state.

The admin\controller\sale\voucher.php has the correct mail functions, i just think it is never triggered.

In other words. 

Customer buys voucher > checks out -> order containing voucher is pending/processing status
          At this point voucher is added but wont WORK on checkout yet. No email should be sent to voucher recipient at this point. That's good and expected.

However...
Customer order that contains voucher payment is confirmed -> order status becomes Complete
         At this point voucher becomes usable and validated. However no notification email is sent to voucher recipient. 

Cant seem to find in the code where the complete status of the order updates the voucher AND triggers the notification email for the voucher recipient.

I will try to investigate further why. 
If anyone one knows please help?

**Comment by stockmaster** [comment]
see a few closed issues about this
https://github.com/opencart/opencart/issues/2295

**Comment by stockmaster** [comment]
Hi Daniel
Was you able to replicate this as well?
Or it doesn't work as stated above and the recipient needs to be notified by hand?

**Comment by domenikniemietz** [comment]
I can replicate this issue!!

Opencart 2.0.3.1! Voucher mail is not sent until i do it manually or delete the corresponding order!

Please fix it.
