### ISSUE TITLE
encoding of log modifactions is not utf-8

### ISSUE THREAD

**Issue by Hamid0311** [opencart/opencart#2951]
Hi
when the name of xml file on tag name is arabic on log of modification the name not show correctly how should i fix that?

**Comment by danielkerr** [comment]
Check for UTF-8 content in fread after fopen:
For checking the UTF-8 content I use the function 'htmlentities();'
Example:
<?php
$filename = "CONTENT.htm";
$handle = fopen($filename, "r");
$contents = fread($handle, filesize($filename));
// Check for UTF-8 content
if(htmlentities(utf8_decode($contents))){
    $contents = htmlentities(utf8_decode($contents));
}else{
    $contents = htmlentities($contents);
}
?>

**Comment by danielkerr** [comment]
i'm closing this down. all the entities are converted because its more secure.
