### ISSUE TITLE
Errors after update and same error on fresh install with old DB 

### ISSUE THREAD

**Issue by vaizbunas** [opencart/opencart#2952]
This error I have got after update. 

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

OK

<b>Warning</b>: Invalid argument supplied for foreach() in <b>C:\xampp\htdocs\opencart\admin\model\report\sale.php</b> on line <b>87</b><b>Notice</b>: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND DATE(date_added) >= '2015-04-1' GROUP BY DATE(date_added)' at line 1<br />Error No: 1064<br />SELECT COUNT(*) AS total, date_added FROM `oc_order` WHERE order_status_id IN() AND DATE(date_added) >= '2015-04-1' GROUP BY DATE(date_added) in <b>C:\xampp\htdocs\opencart\system\library\db\mysqli.php</b> on line <b>41</b><b>Notice</b>: Trying to get property of non-object in <b>C:\xampp\htdocs\opencart\admin\model\report\sale.php</b> on line <b>104</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>C:\xampp\htdocs\opencart\admin\model\report\sale.php</b> on line <b>104</b>{"order":{"label":"Orders","data":[[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],[10,0],[11,0],[12,0],[13,0],[14,0],[15,0],[16,0],[17,0],[18,0],[19,0],[20,0],[21,0],[22,0],[23,0],[24,0],[25,0],[26,0],[27,0],[28,0],[29,0],[30,0]]},"customer":{"label":"Customers","data":[[1,0],[2,"1"],[3,0],[4,0],[5,0],[6,0],[7,"1"],[8,"2"],[9,0],[10,"2"],[11,0],[12,0],[13,0],[14,"1"],[15,"1"],[16,"1"],[17,0],[18,0],[19,0],[20,0],[21,0],[22,0],[23,0],[24,0],[25,0],[26,0],[27,0],[28,0],[29,0],[30,0]]},"xaxis":[["1","01"],["2","02"],["3","03"],["4","04"],["5","05"],["6","06"],["7","07"],["8","08"],["9","09"],["10","10"],["11","11"],["12","12"],["13","13"],["14","14"],["15","15"],["16","16"],["17","17"],["18","18"],["19","19"],["20","20"],["21","21"],["22","22"],["23","23"],["24","24"],["25","25"],["26","26"],["27","27"],["28","28"],["29","29"],["30","30"]]}

and here is what I see on the back end.

Warning: implode(): Invalid arguments passed in C:\xampp\htdocs\ks\admin\controller\common\header.php on line 58Warning: implode(): Invalid arguments passed in C:\xampp\htdocs\ks\admin\controller\common\header.php on line 59Warning: implode(): Invalid arguments passed in C:\xampp\htdocs\ks\admin\controller\common\header.php on line 62Warning: implode(): Invalid arguments passed in C:\xampp\htdocs\ks\admin\controller\common\header.php on line 63Warning: implode(): Invalid arguments passed in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 14Warning: implode(): Invalid arguments passed in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 22Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\ks\admin\controller\common\stats.php on line 37

**Comment by CoverUp** [comment]
thus, old db is not compatible, on my side I have upgraded from 2.0.1.1 to 2.0.2.0 and I only get errors with featured, slider and carrusel modules, but nothing that an uninstall followed by a install module can't fix it

**Comment by vaizbunas** [comment]
I have tried to update from 1.5.6.4 to 2.0.2.0 got same error. DB seems to work, as its pulling sales and customers data and other information. From what I have read so far, some variables have name change or I might be wrong, therefore some information is not being pulled from the DB. Still trying to understand the code and what could be causing it. 

Did you updated to 2.0.1.1  from 1.5.x ? If so, how did you do it ?

**Comment by CoverUp** [comment]
First I install the 2.0.0.0 version, then I populate the db table by table, changing the fields with different names (as i remember only 1 field change the name), modules got to be unistalled and installed again becasuse data is saved in a different way, the best is only migrate customers, categories and products, all the rest is better to omit. About extension most of them are fixed changing $this->data[ to $data[, notepadd++ is your friend on this

**Comment by GomDani** [comment]
If your customers have their address with company_id and tax id you must create two custom fields and fill it with old address data. If you have 1000 customers is a lot of work. Or let to the customer to fill again tax_id and company_id. And orders also lose this two fields. So if you have new open orders and need customers company_id or tax_id copy them.

**Comment by danielkerr** [comment]
resave the settings for each module after upgrading./
