### ISSUE TITLE
move theme preview image from root image folder to theme image folder

### ISSUE THREAD

**Issue by Firestorm-Graphics** [opencart/opencart#2955]
Theme modifications should be kept in the theme folder, i.e template preview image in system > settings > store is currently in the root image folder, perhaps opencart can look for this image in theme folders first.

**Comment by Firestorm-Graphics** [comment]
reason for closure ?

**Comment by milimar** [comment]
@Firestorm-Graphics , sometimes there is a lot to explain, sometimes the reason for not explaining is other...
I do not tell you that I do not agree with you, just telling you how Daniel do the things here, but however, he has explained many times why he closes some issues without a comment. 

Greetings

**Comment by Firestorm-Graphics** [comment]
:-1:

**Comment by GizMecano** [comment]
@Firestorm-Graphics As mention in the [readme](https://github.com/opencart/opencart#making-a-suggestion), I supposed that you have to post your proposition on [Uservoice](http://opencart.uservoice.com/).
