### ISSUE TITLE
Error code on the top of web admin

### ISSUE THREAD

**Issue by Progresweb** [opencart/opencart#2956]
I am trying to install the white label branding for opencart with vqmod. But after putting to the XML area of the vqmod, I am seeing the error codes on the top of the admin that goes like this

Notice: Indirect modification of overloaded property ControllerSettingSetting::$data has no effect in /home2/webhostn/public_html/vqmod/vqcache/vq2-admin_controller_setting_setting.php on line 944

I am not even seeing the custom admin which is suppose to be in the setting. 
![error_codes_on_opencart_admin](https://cloud.githubusercontent.com/assets/12114436/7333969/10e264da-ebb5-11e4-86bb-be584c970dc7.png)

**Comment by haxcop** [comment]
Hi @Progresweb ,i think you may refer this to Jay creator or vqmod... @JAY6390 may give you a better answer

**Comment by JAY6390** [comment]
That has nothing to do with VQMod

**Comment by Progresweb** [comment]
Can you tell me how I can possibly rectify this?
