### ISSUE TITLE
Region/State Issue

### ISSUE THREAD

**Issue by shahankitb** [opencart/opencart#2959]
http://demo.opencart.com/index.php?route=account/register
![1](https://cloud.githubusercontent.com/assets/12130260/7341100/11a69584-ecce-11e4-8dd7-7c093e9f9e02.png)

When we select Country as Singapore in Region/State it should display as "None" & Selected.

In AJAX call of country instead of
if (json['zone']) {

Need to change
if (json['zone'] != '') {

Need to change on 10-12 file places. It works on older version. But newer version it's not working.

**Comment by danielkerr** [comment]
can not find this code

**Comment by shahankitb** [comment]
There is an issue. Please check on live URL.
