### ISSUE TITLE
Coupon,Gift  can't limit use,and database no record ,please help!!!

### ISSUE THREAD

**Issue by infoall** [opencart/opencart#2960]
優惠券,Gift,不能控制使用次數，以及沒有優惠券訂單使用記錄。

請幫檢查跟進謝謝。

Coupon,Gift cannot be used to control The Times, and the lack of record use coupons orders. 
Please help to check follow up. Thanks. 

Notes:
1,database , oc_coupon_history & oc_coupon_products no data.
2,use opencart 2.* test .
3,use cash payment 
4,order change status to complete  , As well as no data .

thanks!!!!

**Comment by samirdesign** [comment]
I have the same problem in OC 2.0.3.1.
No history, no data in database.
Can anyone help?

Thank you

**Comment by paptom** [comment]
Why is this closed?
