### ISSUE TITLE
admin/catalog/../autocomplete array_multisort unneeded. 

### ISSUE THREAD

**Issue by dtjones** [opencart/opencart#2963]
Firstly by adding the sort and order filters to the filter_data you remove the need for the "for loop" and array_multisort. 

replace 

    $sort_order = array();
    foreach ($json as $key => $value) {
		$sort_order[$key] = $value['name'];
    }
    array_multisort($sort_order, SORT_ASC, $json);

with 

    'sort'         => isset($this->request->get['sort'] ? $this->request->get['sort'] : 'name',
    'order'        => isset($this->request->get['order'] ? $this->request->get['order'] : 'ASC',

or  just

    'sort'         => 'name',
    'order'        => 'ASC',

**Comment by dtjones** [comment]
And secondly I would allow all methods to make use of all available filters. it would give front end developers more flexibility with .tpl files without the need of modifying controllers.  

e.g.

    	$filter_data = array(
			'filter_name'  => isset($this->request->get['filter_name'] ? $this->request->get['filter_name'] : '',
			'filter_model' => isset($this->request->get['filter_model'] ? $this->request->get['filter_model'] : '',
			'sort'         => isset($this->request->get['sort'] ? $this->request->get['sort'] : 'name',
			'order'        => isset($this->request->get['order'] ? $this->request->get['order'] : 'ASC',
			'start'        => isset($this->request->get['start'] ? $this->request->get['start'] : 0,
			'limit'        => isset($this->request->get['limit'] ? $this->request->get['limit'] : 5
		);
Please consider the above code.  I am not suggesting any front-end/.tpl changes. 

Just to make it clear, the following  example is of what a developer could achieve/do with the above modification.
e.g 
This would allow you to do just the one ajax request to retrieve all manufacturers and save that in local storage rather than doing ajax requests via $.fn.autocomplete;

    if(window.localStorage !== 'undefined' && ( out-of-date || doesnt-exist )){
		$.ajax({
			url: 'index.php?route=catalog/manufacturer/autocomplete&token=<?php echo $token; ?>&limit=0&filter_name=',
			dataType: 'json',			
			success: function(json) {
				if(json){
    window.localStorage.setItem('manufacturers',JSON.stringify({'date': new Date(),'manufacturers': json}));
					} 
				}				
			}
		});
From there you can populate a `<select>` element with all results, use things like fuse.js(fuzzy search), select2.js or selectize.js.

I'm just saying that by making that small controller change would open up a lot of opportunities.

**Comment by danielkerr** [comment]
i prefer the current way. also if you hadn't noticed but the filter vars need to be passed back intot he template. your solution would not do this.

**Comment by saamalam** [comment]
is that possible to pass two parameters filter_name and filter_model on ajax call:
url: 'index.php?route=catalog/product/autocomplete&token=<?php echo $token; ?>&filter_name=' +  encodeURIComponent(request) + '&filter_model=' + encodeURIComponent(request),
but doesn't seems to working. Basically trying to search for Related product by their name or model.
