### ISSUE TITLE
Virtual Merchant Converge Issue

### ISSUE THREAD

**Issue by Viswanath-Ravi** [opencart/opencart#2964]
Hi, 

   We just purchased a virtual merchant converge payment gateway for opencart site. We are facing a issue like "invalid credentials". 

We set the payment gateway as test in the admin area and use the test credit card account only. I attach the image of the issue we are facing. 

Please find the attachment and give me a solution for this issue asap.
![virtual_payment_error](https://cloud.githubusercontent.com/assets/12151527/7367595/23a10c06-edbe-11e4-91e8-401e6a28a61e.PNG)

**Comment by osworx** [comment]
Completely wrong forum!
Ask the developer of this extension, this here is only for OpenCart core.
