### ISSUE TITLE
Filters not getting displayed

### ISSUE THREAD

**Issue by thiagupct** [opencart/opencart#2966]
Opencart 2.0.1.1 Enabled filter in module then created new filter group and filters then added the same in categories and products tabs. While opening the category page, filter option is not displayed.

What am I doing wrong?

Please advice, Any help is most appreciated.

**Comment by GomDani** [comment]
In Layouts page add filter module to Category Layout.

**Comment by thiagupct** [comment]
@GomDani Thanks a lot

**Comment by farheenr** [comment]
Hi, i installed filters added filters 
in frontend it is visible on category page but not on home page.
will you please help me in this

**Comment by milimar** [comment]
I think that filters can be used only on category pages.
