### ISSUE TITLE
OCMOD <operation error="skip"> ABORTING

### ISSUE THREAD

**Issue by AlexDWZ** [opencart/opencart#2972]
Hi!
I have problem with OCMOD modifications - if used < operation error="skip" > and into < search > some code < /search > not found - all code after (until < /file >) are IGNORED

for fix -  in file admin\controller\extension\modification.php

find code:
                                        // Skip current operation
                                        if ($error == 'skip') {
                                            break;
                                        }

and replace:
                                        // Skip current operation
                                        if ($error == 'skip') {
                                            // break;
                                            $log[] = 'SKIP!';
                                        }

**Comment by AlexDWZ** [comment]
UPD: tested with Opencart 2.0.2.0 and 2.0.1.1

**Comment by danielkerr** [comment]
its does not need a skip log in there because you might use a wild card on the files in which case every file that is accessed would log a skip!

also the current way is correct! you want to skip the operation if the code is not found, not continue it!

**Comment by AlexDWZ** [comment]
Maybe skip this if not found, and continue code after, but not abort all code (another < operations >) after (until< /file >) ?
(as it is done in VQMOD - I normally use < skip > in VQMOD for compatibility between different Opencart versions)

PS: sorry for my English, is not my native language
