### ISSUE TITLE
Affiliate links broken / not tracking sales / non working buttons

### ISSUE THREAD

**Issue by manakill** [opencart/opencart#2973]
An affiliate of ours is having ongoing issues with the affiliate links.
His traffic creates broken buttons on our site. Traffic cannot make a purchase or add items to cart.

Affiliate site: http://www.johnnyclevelandshirts.com/
Our links are the two bottom "Johnny Cleveland" shirts - the Brown and Orange ones.
His links are:
http://explicitshirtstore.com/johnny-manziel-cleveland-browns-t-shirt-orange-white-print?tracking=5377c6514416e

Clicking through should show you the break. Can select options, but when you add to cart, nothing happens.. All product item pages seem to be broken for that session

**Comment by manakill** [comment]
I see Daniel is still acting a foo

**Comment by valdeir2000** [comment]
@manakill the problem is that your store does not work with WWW.
Here is a fix for your problem: http://forum.opencart.com/viewtopic.php?t=35924

Test: https://explicitshirtstore.com/johnny-manziel-cleveland-browns-t-shirt-orange-white-print?tracking=5377c6514416e

**Comment by danielkerr** [comment]
@valdeir2000, don't help this dumbass.
