### ISSUE TITLE
Affiliate links broken / not tracking sales / non working buttons

### ISSUE THREAD

**Issue by manakill** [opencart/opencart#2974]
An affiliate of ours is having ongoing issues with the affiliate links.
Was working fine until upgraded to new version OC.
His traffic creates broken buttons on our site. Traffic cannot make a purchase or add items to cart.

Affiliate site: http://www.johnnyclevelandshirts.com/
Our links are the two bottom "Johnny Cleveland" shirts - the Brown and Orange ones.
His links are:
http://explicitshirtstore.com/johnny-manziel-cleveland-browns-t-shirt-orange-white-print?tracking=5377c6514416e

Clicking through should show you the break. Can select options, but when you add to cart, nothing happens.. All product item pages seem to be broken for that session

**Comment by manakill** [comment]
You'd think a framework issue wouldn't get immediately closed.

You are a tool DANIEL KERR
Maybe I'll have to come visit you personally. Call it a business meeting LOL

**Comment by valdeir2000** [comment]
https://github.com/opencart/opencart/issues/2973

Search www to no-www

**Comment by danielkerr** [comment]
the issue is caused by you not opencart! your account is also banned on opencart.com! i don't know why you are posting here! i'm not going to help you with your problems.

**Comment by manakill** [comment]
It's been banned from your SCAM
https://github.com/opencart/opencart/issues/2915

You are such a douchebag Daniel and you're proving it for everyone to see.

I will continue to post here because this is an OPEN SOURCE PROJECT
YOU DON'T OWN OPENCART DANIEL, EVEN THOUGH YOU MAKE EVERYONE BELIEVE IT


If it were up to you I'm sure you'd Ban me here for exposing you!!!!!!!!!  HAHAHAHA!!

**Comment by manakill** [comment]
@valdeir2000 Thanks for actually helping :)

**Comment by creativelogic** [comment]
Daniel is no scam, and you are supposed to post your needs on the Opencart
forum, github is more for the advanced users to post bugs

**Comment by manakill** [comment]
We have some cases in which he did steal money for no reason. That is a "scam"
It's all heavily documented and we have ongoing communication with
PayPal Management and other official connections.

I am "an advanced user" and have posted many things code related. I
betcha if I post there, 'ol Daniel will try and ban me for no reason
too.

I also pay a lot for coders to fix issues that have not been
addressed, or prematurely closed without explanation.

Thanks for your help with this issue. If any code we make, or fix, can
help, I'll submit it :)

**Comment by danielkerr** [comment]
you have been refunded on your past purchases


Rich Comiskey Dec 10, 2013 22:36
No, I'm not thank you LOL


Daniel Kerr Dec 10, 2013 13:06
your banned!


Rich Comiskey Dec 10, 2013 11:15
See my account. Paypal didn't go thru but charged me, cc payment did go 
thru.


Beth Dec 10, 2013 11:04
Hi Rich, 
sorry but could you please clarify your message, you want to claimed for refund and you want to access the download ASAP also?

Best regards 
Beth 
Opencart support team


Rich Comiskey Dec 10, 2013 10:25
Contact Details

Username: manakill 
Name: Rich Comiskey 
E-Mail: manakill@gmail.com 
IP: 96.25.246.88

Enquiry:

I want a refund for the recent purchase paid for with PayPal. You didn't deliver instantly and this is unacceptable for a digital download supplier. The credit card payment, keep, and process please so I can access the download ASAP
