### ISSUE TITLE
do I not need rewritebase file htaccess

### ISSUE THREAD

**Issue by bhraqnet** [opencart/opencart#2975]
Seems to be working, , do I not need rewritebase
Delete  RewriteBase /

        # Prevent Direct Access to files
          <FilesMatch "(?i)((\.tpl|\.ini|\.log|(?<!robots)\.txt))">
         Order deny,allow
         Deny from all
        </FilesMatch>

          # SEO URL Settings
          RewriteEngine On
          # If your opencart installation does not run on the main web folder make sure you folder it  does run in ie. / becomes /shop/ 

          RewriteRule ^sitemap.xml$ index.php?route=feed/google_sitemap [L]
          RewriteRule ^googlebase.xml$ index.php?route=feed/google_base [L]
          RewriteRule ^system/download/(.*) /index.php?route=error/not_found [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteCond %{REQUEST_URI} !.*\.(ico|gif|jpg|jpeg|png|js|css)
          RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]

**Comment by osworx** [comment]
Why do so many people think they know everything better??
I would suggest, first inform yourself (search engines do a good job in this), and then - and only if you are sure that you have to say something, post it in the correct forum.
