### ISSUE TITLE
Impeach Daniel Kerr

### ISSUE THREAD

**Issue by manakill** [opencart/opencart#2976]
This framework has gotten polluted with bad mods with bad business ethics and laughable bug handling of issues. I see other mods are just fine. There is one bad apple for sure though, suspect another..

There are currently ongoing SCAMS at Opencart.com with "Daniel Kerr" at the head of that operation.
https://github.com/opencart/opencart/issues/2915

Don't expect your issue will ever be addressed if Daniel is around... if you're lucky you might get a nice insult to your intelligence and character! How exciting! =D

https://github.com/opencart/opencart/issues/2973
https://github.com/opencart/opencart/issues/2974
and that's just the last few

If it was up to Daniel, he'd ban me for exposing him! 
LOL THIS AIN'T CHINA BUDDY 

I've been here for years, I've contributed, I'm not going anywhere.
I don't want to be a mod, I'm not claiming to be that good at coding :) I am claiming to be a better businessman who doesn't alienate his customers. My clients are reading this. My coders and partners. 

I speak for all of us when I say "It is we who do not want to do business with you, Daniel Kerr"

**Comment by danielkerr** [comment]
and banned from github!!
