### ISSUE TITLE
Error in admin/model/catalog/product.php

### ISSUE THREAD

**Issue by dfgonzalez** [opencart/opencart#2977]
Just installed the main version and had these errors in the file, easy to fix them:

$data['product_attribute'] = $this->getProductAttributes($product_id)));
$data['product_description'] = $this->getProductDescriptions($product_id)));
$data['product_discount'] = $this->getProductDiscounts($product_id)));
$data['product_filter'] = $this->getProductFilters($product_id)));
$data['product_image'] = $this->getProductImages($product_id)));
$data['product_option'] = $this->getProductOptions($product_id)));
$data['product_related'] = $this->getProductRelated($product_id)));
$data['product_reward'] = $this->getProductRewards($product_id)));
$data['product_special'] = $this->getProductSpecials($product_id)));
$data['product_category'] = $this->getProductCategories($product_id)));
$data['product_download'] = $this->getProductDownloads($product_id)));
$data['product_layout'] = $this->getProductLayouts($product_id)));
$data['product_store'] = $this->getProductStores($product_id)));
$data['product_recurrings'] => $this->getRecurrings($product_id)));

2 extra ) in every line, and removed the > in the last line.

Best,

**Comment by milimar** [comment]
This bug has been reported many times and it has been solved, so please do not report this issue again.
