### ISSUE TITLE
Update quantity from cart not (always) working

### ISSUE THREAD

**Issue by QualityWorks** [opencart/opencart#2980]
Both 2.0.1.1 and 2.0.2.0 have this error:
When you add a product with a lot of options (like the demo Apple 30" screen) you can't edit the quantity in the cart, it just shows []
Products with less options work fine.
It probably has to do with the length of the key that is being generated but I haven't been able to find a solution to this yet. Unfortunately, I really need to be able to update from the cart for a big project I'm working on.

I have checked on a fresh install. demo.opencart.com doesn't accept the file upload but you can test it here:
http://oc2.qualityworks.eu/index.php?route=product/product&product_id=42

**Comment by QualityWorks** [comment]
hmmm my theory for the longer keys just went up in flames, the demo Canon EOS 5D has the same issue. this one also has options, but not as many.
I have just reinstalled OC again to make 100% sure it is not any mod or any trace code... same problems still (strange though that on demo.opencart.com this one seems to be working: http://oc2.qualityworks.eu/index.php?route=product/product&manufacturer_id=7&product_id=47 and on my page, it doesn't)

**Comment by milimar** [comment]
Sorry to disappoint you, but on my installation of OC2.0.2.0 it is working well. Please check my installation: 

http://milimar.info/oc2020/index.php?route=common/home

Greetings!

**Comment by QualityWorks** [comment]
hmmm that's so strange... I seriously checked on 2 different installs, and I reinstalled them completely from scratch...
might it be a hosting issue?

**Comment by milimar** [comment]
You will lose nothing if you ask your hosting provider for help , and I suggest you transfer your issue to the official forum of OC, there might be people who can help you more than I can.

**Comment by danielkerr** [comment]
maybe a template issue.  if your using an old template with a new version of OC

**Comment by QualityWorks** [comment]
yeah lets close this one... and no Daniel, it doesn't seem to be a template issue, the "option-less" products ARE working and I did a clean install.

**Comment by milimar** [comment]
Please note that in my OC installation I have SEO enabled....I am not sure if this information could be important, but you can test it :)

**Comment by QualityWorks** [comment]
just to let you guys know... I tested on another host and it works fine there... no explanation for it.
I am now moving all my domains to the other host because this is just nuts... cost me half a day  :(
