### ISSUE TITLE
Proposition regarding template use

### ISSUE THREAD

**Issue by QualityWorks** [opencart/opencart#2991]
the templates for latest.tpl, bestseller.tpl, special.tpl are identical, why not create only 1 tpl that is being called from all 3 controllers (common/module.tpl)? 

and from that, how a product is shown within these templates, aswell as others could be put in common/product.tpl and include that in the different templates like category, bestseller, etc. 

the plus side is that for customization you only have to update the 1 common template that filters through to all the different spots where this is used instead of having to change every template file. Also ofcourse for bugfixing (if any)

I actually have a shop made that uses the common/product.tpl if anyone's interested in seeing how that could work.

**Comment by milimar** [comment]
There is a special place where you can send prepositions. This is a place for bug reporting.

Greetings

**Comment by valdeir2000** [comment]
In three models (latest.tpl, bestseller.tpl, special.tpl) gives the designer more freedom to customize each. Being able to do the equal or customize them all differently.
