### ISSUE TITLE
www and non-www add to cart

### ISSUE THREAD

**Issue by QualityWorks** [opencart/opencart#2992]
I noticed that if you install the shop either with or without www in the url and then visit the shop with the method you didn't install, the add to cart button doesn't work.
The issue is solved as soon as you click 1 link, as it will go to the installed method for the next page, but on the initial load the buy buttons will not work.
This is the error:

XMLHttpRequest cannot load http://www.domain.com/index.php?route=checkout/cart/add. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://domain.com' is therefore not allowed access.

So the fix would be a rewrite in the .htaccess (but google doesn't like that) or some other way to initially force the vistor to the installed access. Or mark the resource as  'Access-Control-Allow-Origin', if that doesn't cause other issues

**Comment by aWeirdo** [comment]
If you just need a quick fix, 
Lets say you installed it without www, redirect people who access with www in the url to a url without the www, e.g: Redirect on load http://www.yourdomain.com/x/x/x -> http://yourdomain.com/x/x/x

If you add the following to the top of your upload\catalog\controller\common\header.php
```
/* Redirect - Check for www in Url.. */
$url = 'http://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
if (strpos($url,'www') !== false) {
	if ($this->request->server['HTPS']) {
		header('Location: https://yourdomain.com/'. $_SERVER['REQUEST_URI']);
	} else {
		header('Location: http://yourdomain.com/'. $_SERVER['REQUEST_URI']);
	}
exit;
}
```

Note, i haven't tested this, i dont have a live domain and you cant really use www.localhost :) 
Use at your own risk and dont expect official support from opencart for this quickfix, hopefully they will fix the issue soon without something like this.

**Comment by QualityWorks** [comment]
yes, that is one option, but keep in mind that google does not like redirects like those. Also, I think this should be solved in the code.
For my current customers I have solved it in the htaccess.

**Comment by ManaKill2** [comment]
@QualityWorks how did you solve it?

**Comment by QualityWorks** [comment]
I solved it by adding into the htaccess manually to check for www or non-www manually and rewrite the url accordingly, but again, this is not a real core fix for the standard install for 3 reasons:

1) forces use of htaccess
2) rewrites the url which Google really doesn't like
3) manual change because you cannot automatically say it's always www -> non-www or the other way around.

I haven't come up with a good structural fix (yet)....

**Comment by ManaKill2** [comment]
Got it. I'm having a similar issue but it only seems to apply to affiliate links from www site to my non-www site.

**Comment by osworx** [comment]
Basically Google does not like if a website is accessable by both: www and non-www
Adjust first this ad Google webmaster tools.
Second adjust the .htaccess to have only one: either with or without www

Do now know what you have against the .htaccess ?

**Comment by QualityWorks** [comment]
actually, google doesn't mind to have both accessible, it actually tells you to add both www and non-www in webmastertools.
What I was saying is that google doesn't like redirects in general. On all the stores where I fixed this problem, google gives notices on the redirect (through the htaccess).
What I have against fixing this in the htaccess I explained before:

1) forces use of htaccess
2) rewrites the url which Google really doesn't like
3) manual change because you cannot automatically say it's always www -> non-www or the other way around. (since this depends on how the user installs the shop)

**Comment by kanenas** [comment]
@QualityWorks, google <strong>does mind</strong> to have both <strong>www</strong> and <strong>non-www</strong> accessible, because she doesn't like duplicate content! Adding both www and non-www in "Webmaster Tools" is another thing.

Anyways, can someone please close this (not) issue?

**Comment by QualityWorks** [comment]
you're not getting the point... it's not about google liking or not liking www AND non-www
it's about the button not working on non-www if the store is installed on www.

So now, if the solution is the htaccess file as I have done manually, then this is something we cannot code into the core of opencart because a user can install the shop either on www, making the rewrite from non-www to www. or install on non-www making the rewrite www to non-www.

Also, and this is where google comes in, google doesn't like redirects! now, again, the problem is only on initial landing on the site, as any next clicked link in the page solves the issue as it will resolve to the installed www or non-www respectively.

you can focus on google wanting duplicate content or not, but that's really not what this issue is about!

**Comment by osworx** [comment]
@QualityWorks I got all points ...
Installed nearly 650 OC shops for customers the last 2 years, had not one with such problems.
So I guess I know what about I am talking.
And using the .htaccess is not only to avoid duplicate URLs.
Finally adopting the config.php could be also a solution (additionally).

**Comment by QualityWorks** [comment]
I understand that using the htaccess is not only to avoid duplicates, I never said anything about duplicates!
I said that htaccess is not being used by default by all customers and therefore not the best solution. that's it.
I also said that a redirect in general is not being liked by Google.
And just test it, I have tested it on several shops now and they all have this issue, all on different hosts, both 2.0.1.1 and 2.0.2.0. I must admit I have only had 1 customer actually complain about it and it was hard to find, but I am not making this stuff up. I think most customers who land on a page, hit add to cart and it doesnt work actually click on the product and try again there, so by then the problem is gone and it works, so you wouldn't get a lot of complaints.

And yes, I think changing the config.php would be the best solution

**Comment by valdeir2000** [comment]
Just redirect to the status code 301. Google recommended.

https://moz.com/learn/seo/redirection
https://support.google.com/webmasters/answer/93633

**Comment by QualityWorks** [comment]
fine, then please suggest how to do that if the htaccess is not used by default and when we don't know if a shop will be installed on www or non-www.

**Comment by valdeir2000** [comment]
http://php.net/manual/pt_BR/function.header.php
http://www.agenciamestre.com/seo/redirecionamento-301-em-php-asp-htaccess-coldfusion-e-ruby-on-rails/

Just use the code base @aWeirdo  and operate.
If you implement this in core of OpenCart you can give problem with that install on localhost.
