### ISSUE TITLE
Cannot Update Order Status in 2.0.1.1

### ISSUE THREAD

**Issue by indclassictrophy** [opencart/opencart#2993]
I cannot update order history in 2.0.1.1 due to a syntax error: unexpected end of input. I have contacted support and have tried creating a new api and changed the settings in the php files from 0 to 1 and I've also contacted my hosting company to enable http loopback. Neither of which have worked. My hosting company said I should contact a web developer to debug the problem. However, with this being a simple order status I thought I would try contacting you first. Here is my login info:
www.indclassictrophy.com/admin
UN: admin
PW: wer098WER
FTP:
109.73.236.137
indclass
Ct4890!900

Any help would be greatly appreciated!
Thanks!
Zac

**Comment by danielkerr** [comment]
take your stupid ftp details down!!

**Comment by indclassictrophy** [comment]
WOW - THAT IS ONE PROFESSIONAL WAY TO ANSWER A SUPPORT QUESTION. 

BEST REGARDS, 

 		Zac Weidler | Marketing Director

 		T: 260.483.1161

 		E: zac@indclassictrophy.com

 		W: www.www.indclassictrophy.com [2]

 		 [3]
 		 [4]
 		 [5]

 		The company accepts no liability for the content of this email, or
for the consequences of any actions taken on the basis of the
information provided, unless that information is subsequently confirmed
in writing. If you are not the intended recipient you are notified that
disclosing, copying, distributing or taking any action in reliance on
the contents of this information is strictly prohibited.

On 11/05/2015 03:26 AM, Daniel Kerr wrote: 

> take your stupid ftp details down!! 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/opencart/opencart/issues/2993#issuecomment-100796579
[2] http://www.www.indclassictrophy.com
[3] http://www.twitter.com/indclassic
[4] http://www.facebook.com/classictrophyinc
[5] http://plus.google.com/115142875484619087974

**Comment by manakill** [comment]
@indclassictrophy  He does it to a lot of people, don't let him discourage you. There are a lot of helpful people here. If he offends you, flag him for abuse, it's what GitHub told me to do. They are getting sick of him I think.

I will say, posting FTP, admin or other login info, you are setting yourself to get hacked or rooted with no effort at all - Don't do it in a public place like this.

**Comment by danielkerr** [comment]
@indclassictrophy you have given the world access to your server.

**Comment by indclassictrophy** [comment]
I thought this was a professional site for OpenCart - and thought it
would be safe as it says on opencart report a bug - not a forum. In my
post I dont see my site details listed. So, not sure how I can remove
them. 

---

BEST REGARDS, 

 		Zac Weidler | Marketing Director

 		T: 260.483.1161

 		E: zac@indclassictrophy.com

 		W: www.www.indclassictrophy.com [3]

 		 [4]
 		 [5]
 		 [6]

 		The company accepts no liability for the content of this email, or
for the consequences of any actions taken on the basis of the
information provided, unless that information is subsequently confirmed
in writing. If you are not the intended recipient you are notified that
disclosing, copying, distributing or taking any action in reliance on
the contents of this information is strictly prohibited.

On 17/05/2015 01:07 PM, manakill wrote: 

> @indclassictrophy [1] He does it to a lot of people, don't let him discourage you. There are a lot of helpful people here. If he offends you, flag him for abuse, it's what GitHub told me to do. They are getting sick of him I think. 
> 
> I will say, posting FTP, admin or other login info, you are setting yourself to get hacked or rooted with no effort at all - Don't do it in a public place like this. 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/indclassictrophy
[2]
https://github.com/opencart/opencart/issues/2993#issuecomment-102823467
[3] http://www.www.indclassictrophy.com
[4] http://www.twitter.com/indclassic
[5] http://www.facebook.com/classictrophyinc
[6] http://plus.google.com/115142875484619087974
