### ISSUE TITLE
error on admin login after first install

### ISSUE THREAD

**Issue by webxpro** [opencart/opencart#2996]
Parse error: syntax error, unexpected ')' in C:\xampp\htdocs\opencart\upload\admin\model\catalog\product.php on line 293

**Comment by valdeir2000** [comment]
Solution

https://github.com/opencart/opencart/pull/2982

**Comment by webxpro** [comment]
the problem still not fixed in main code i just downloaded and tryed and still same problem please can you submit the fix ?
