### ISSUE TITLE
Price presentation fault

### ISSUE THREAD

**Issue by rutan65** [opencart/opencart#2999]
Display prices with Tax does the opposite!
![screenshot from 2015-05-09 19 45 46](https://cloud.githubusercontent.com/assets/11318409/7551292/3d8002d4-f684-11e4-82a3-81899c34b30b.png)
![screenshot from 2015-05-09 19 46 18](https://cloud.githubusercontent.com/assets/11318409/7551295/45553f10-f684-11e4-8a50-9583ab0c162d.png)

**Comment by milimar** [comment]
Hi, it is very strange to find so obvious error like this and no one else to notice it so far.
I have made an installation of OC 2.0.2.0 for testing purposes and this error does not exist in my installation. All prices that use tax classes are well calculated. Please check my installation and check again yours to confirm the existence of eventual error. 

http://milimar.info/oc2020/index.php?route=common/home

Gretings

**Comment by osworx** [comment]
@rutan65 And where is an error?
If you have not defined a taxclass and have set the definitions wrong, this is the normal output.

**Comment by rutan65** [comment]
Hi,
Added some screenshots of my settings.
One difference is that I have removed $ as choice of currency.

Regards,

Goran

2015-05-09 22:09 GMT+02:00 milimar <notifications@github.com>:

> Hi, it is very strange to find so obvious error like this and no one else
> to notice it so far.
> I have made an installation of OC 2.0.2.0 for testing purposes and this
> error does not exist in my installation. All prices that use tax classes
> are well calculated. Please check my installation and check again yours to
> confirm the existence of eventual error.
>
> http://milimar.info/oc2020/index.php?route=common/home
>
> Gretings
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/2999#issuecomment-100539735>.
>



-- 
Göran Edlund

LinkedIn <http://se.linkedin.com/in/goranedlund>

**Comment by opencarthelp** [comment]
As was previously stated, you don't have your taxes set up correctly.

**Comment by rutan65** [comment]
Thanks!
I finally got the product price correct. Usage of the terms Geo
Zone/Geocode  was not crystal clear to me but I it is now, the hard way.



2015-05-10 17:37 GMT+02:00 rph <notifications@github.com>:

> As was previously stated, you don't have your taxes set up correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/2999#issuecomment-100657258>.
>



-- 
Göran Edlund

LinkedIn <http://se.linkedin.com/in/goranedlund>
