### ISSUE TITLE
language problem during install steps

### ISSUE THREAD

**Issue by webxpro** [opencart/opencart#3000]
there is a language isue during install steps and install script dont see language files.

**Comment by webxpro** [comment]
![1](https://cloud.githubusercontent.com/assets/9664085/7563205/76b2cbd0-f7e3-11e4-8c76-4c9e31047508.png)
![2](https://cloud.githubusercontent.com/assets/9664085/7563204/762db4fe-f7e3-11e4-8386-1215f14576e8.png)

**Comment by osworx** [comment]
1. if that would be a bug, it would be already fixed (beause until yet, you are the only)
2. the images are shown that you simply not loading the language files
3. which language are you using
4. tell us more about your server environement

**Comment by hadijouma** [comment]
I had the same issue with fresh install few days ago. I am in the US and use English installation. I have been on the same server with many OC installations in the past but this was the first time I encounter this.

What would be the correct link at Github to download the most updated version of opencart?

Thank you

**Comment by Milow** [comment]
I can confirm this issue with a fresh install from master.

**Comment by osworx** [comment]
Bug confirmed.
Is because either the language name is incorrect (corrent default.php > should be english.php) or loading the wrong language file in the index.php of the installer.
One of them has to be changed!
