### ISSUE TITLE
login with paypal 2.0.2

### ISSUE THREAD

**Issue by Mewporg** [opencart/opencart#3002]
There is a problem on login with paypal extention

after going to paypal and back to website it's give blank page without any data.

so it's not complete the login 

https://www.domain.com/?route=module/pp_login/login&scope=address+profile+email+https%3A%2F%2Furi.paypal.com%2Fservices%2Fexpresscheckout+phone&code=Sm-SrsNCByw8j_zC3Y00MKQFFmeXoPooGY2q4WTOFaef7aU3g1n5PZLC-jvfG5_WZrc79IAeUTPg6mnrN-jfaWEUFAddveV_UuAMrfezh7gLuuNWRoB0CamguEgLjRLNxsu5cHFgACd0EBGq9hEYbY623Sjd3M_HC9DNKybMn54JhPlCwfrY35DamH5l0OD4qyzMbJwqKjUnnd1j

error log show that:

2015-05-11 16:08:16 - Log In with PayPal debug (ModelModulePPLogin::getTokens) - cURL Response: stdClass Object
(
    [error] => invalid_client
    [error_description] => Redirect uri does not match for this client
)

**Comment by david-wm** [comment]
Hi Mewporg.

Did you follow the instructions on here?:
https://github.com/opencart/opencart/wiki/Log-In-with-PayPal

Make sure the return URL from the OpenCart LIPP admin settings have been added to your PayPal app.

Kind regards,

**Comment by Mewporg** [comment]
Hi David,

Everything looking as the instructions and return url as on LIPP settings.

The problem after login with paypal account it's redirect again to my website to appear blank page without any data on this page, i was check CURL on the server it's installed!

**Comment by Mewporg** [comment]
Please confirm when you can access the website!

**Comment by david-wm** [comment]
Hi Mewporg.

On the PayPal Developer site when you edit the app, make sure the return URL is set correctly for both the Sandbox and Live settings.

**Comment by Mewporg** [comment]
Hi David,

i look on my paypal developer site found return url as you told me.

i was contact Chirs about the problem of login and pay with amazon he was told me


Hi,
the problem was because of a bug in the Amazon OpenCart integration, ironically created by a system that is supposed to minimise bugs on deployment.  My colleague Dave is currently looking at the Paypal issue you mentioned, I have already advised him of the cause of the Amazon and bug and to check whether something similar may have happened to the Paypal integration.  Glad to have helped and hope everything else goes smoothly with your installation.

Kind regards
Chris Dixon
Technical Project Manager

please can you check the problem carefully for this ?

**Comment by jamesallsup** [comment]
@Mewporg I confirmed with @david-wm that there is no issue here and is likely due to your setup.

The Amazon issue was unrelated.

If you still have a problem please create a support ticket at http://help.welfordmedia.co.uk/ where David may require more information (GitHub is public). Please ensure that you have setup your account correctly before creating an issue, if you do the WM team will be happy to help.
