### ISSUE TITLE
Edit order fails

### ISSUE THREAD

**Issue by rutan65** [opencart/opencart#3003]
I get a JSON error on the last row of order.php when I click Continue
See attached screenshots.
![screenshot from 2015-05-12 10 09 37](https://cloud.githubusercontent.com/assets/11318409/7582582/593bdb12-f88f-11e4-879a-01ac035b9995.png)
![screenshot from 2015-05-12 10 13 19](https://cloud.githubusercontent.com/assets/11318409/7582593/8d9a4600-f88f-11e4-8e59-3f6558d30fbe.png)
![screenshot from 2015-05-12 10 16 01](https://cloud.githubusercontent.com/assets/11318409/7582626/ee073232-f88f-11e4-9e16-c2ada5bab6c0.png)

OpenCart 2.0.2.0

**Comment by veksen** [comment]
Did you create an API? if I recall, $json is initiated and returned only if an API is present.

**Comment by rutan65** [comment]
Opencart out of the box with two extensions, one language and a new module
for payment.
No API created.


2015-05-12 17:03 GMT+02:00 veksen <notifications@github.com>:

> Did you create an API? if I recall, $json is initiated and returned only
> if an API is present.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/3003#issuecomment-101310857>.
>



-- 
Göran Edlund

LinkedIn <http://se.linkedin.com/in/goranedlund>

**Comment by danielkerr** [comment]
you have a space at the beginning of one of the files

**Comment by rutan65** [comment]
Can you clarify?
Do mean a space in the file content or in the file name?
Can also give me a hint of where to find the file (directory ...)?
Since I installed the SW out-of-the box I don't have a clue of how "the space" got there!

**Comment by danielkerr** [comment]
if you opened it and saved the file using a Microsoft product they can add invisible spaces in files. copy the contents of the file and create a new one in dreamweaver or another ide.

**Comment by pekka2** [comment]
@rutan65 
You create APi user and update System > Setting > Edit > Tab Option > select API user
and install this extension:
https://raw.githubusercontent.com/pekka2/OpenCart-Migration-Upgrade-Tool/master/bugs_2.0.2.0-fix.ocmod.xml

**Comment by rutan65** [comment]
Hi,
I am using a Linux based web host service.
The installation of Opencart was based on a tool called "Installatron
Application Installer".
When l look at the file structure I can not see any time stamps that have
changed other than those added, an additional payment module and an
additional language.
Is it possible to raise the debug level somehow so you can get a more
precise printout of the error causing the problem?
The file referenced in the error log, admin/controller/sale/order.php, has
not been touched so where shall I look???

2015-05-20 16:23 GMT+02:00 Daniel Kerr <notifications@github.com>:

> if you opened it and saved the file using a Microsoft product they can add
> invisible spaces in files. copy the contents of the file and create a new
> one in dreamweaver or another ide.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/3003#issuecomment-103904074>.
>



-- 
Göran Edlund

LinkedIn <http://se.linkedin.com/in/goranedlund>

**Comment by pekka2** [comment]
@rutan65 
https://github.com/opencart/opencart/issues/3028

**Comment by rutan65** [comment]
It did it!
Thank you.

Göran


2015-05-20 16:31 GMT+02:00 Pekka Mansikka <notifications@github.com>:

> @rutan65 <https://github.com/rutan65>
> You create APi user and update System > Setting > Edit > Tab Option >
> select API user
> and install this extension:
>
> https://raw.githubusercontent.com/pekka2/OpenCart-Migration-Upgrade-Tool/master/bugs_2.0.2.0-fix.ocmod.xml
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/3003#issuecomment-103906030>.
>



-- 
Göran Edlund

LinkedIn <http://se.linkedin.com/in/goranedlund>
