### ISSUE TITLE
Unable to modify admin views using OCMOD

### ISSUE THREAD

**Issue by gRoberts84** [opencart/opencart#3004]
Hi,

Unless I've missed any part of the OCMOD documentation, it appears that there isn't any support for modifying admin views.

The assumption that we shouldn't be modifying Catalog views using OCMOD because we have themes is fine however admin views, we don't have the support for themes.

Loader::view simply uses DIR_TEMPLATE without checking to see if a modified view exists.

If I look at creating a pull request, is it likely that this will be included or will I need to modify the loader (if I can) to handle this my self?

Thanks

**Comment by gRoberts84** [comment]
Hmmm, seems it's not just views, but language files too.

Just to clarify, is it expected that instead of modifying existing files, i.e. adding keys to an existing language file or modifying an existing admin view, is it assumed we should be using a new one and simply replacing the code in the controller to reference the new files?

**Comment by danielkerr** [comment]
public function view($template, $data = array()) {
		$file = DIR_TEMPLATE . $template;

		if (file_exists($file)) {
			extract($data);

			ob_start();

			require(modification($file));

			$output = ob_get_contents();

			ob_end_clean();

			return $output;
		} else {
			trigger_error('Error: Could not load template ' . $file . '!');
			exit();
		}
	}

**Comment by gRoberts84** [comment]
Why has this been closed without any explanation?

**Comment by opencarthelp** [comment]
Anything loaded through the modification() function can be modified with ocMod so you can edit templates and language files.  I personally don't think there's any clean/safe way to modify a template file but that's another issue.
