### ISSUE TITLE
Bug to update the quantity of a product when you have an option

### ISSUE THREAD

**Issue by Skramewell** [opencart/opencart#3005]
When a product has a mandatory minimum quantity and it has an option after going to the checkout and update the amount deparome with a blank screen with [] - You can see the image is easier to realize.

![1](https://cloud.githubusercontent.com/assets/12413684/7590838/5813d2a2-f8c2-11e4-9c9b-3d3d1d519cc3.png)

![2](https://cloud.githubusercontent.com/assets/12413684/7590843/5be35ace-f8c2-11e4-83a8-252c211ba448.png)

![3](https://cloud.githubusercontent.com/assets/12413684/7590846/5f55de8e-f8c2-11e4-904e-bd376fd291b3.png)

![4](https://cloud.githubusercontent.com/assets/12413684/7590853/62869ef4-f8c2-11e4-8897-572a52fd6075.png)

**Comment by milimar** [comment]
What version of OC do you talking about. I have installed OC 2.0.2.0 for testing purposes and I cannot recreate this error. Please try to recreate this error on my installation. Please note that I have already set min. order quantity to 2 in admin panel for Canon EOS 5D. 

http://milimar.info/oc2020/index.php?route=common/home

Greetings!

**Comment by Skramewell** [comment]
It worked properly!
But why I did encounter this error on my? Will the translation?
I use the OC 2.0.2.0

**Comment by Skramewell** [comment]
I have already installed and not changed anything or translation error persists, which will be able to be?

**Comment by Skramewell** [comment]
After a few hours around the problem, I discovered it was my alojamneto, but do not know why...
