### ISSUE TITLE
API Issue / Permissions

### ISSUE THREAD

**Issue by akzogibbs** [opencart/opencart#3006]
Can you advise if you have resloved the API issue / permissions preventing you from editing orders?

**Comment by danielkerr** [comment]
do some research!

**Comment by akzogibbs** [comment]
Your professionalism and manners astound me.

**Comment by osworx** [comment]
@akzogibbs Why?
Basically he is right, this issue is discussed and solved at unlimited threads/discussions. 
Here and in the forum.

**Comment by akzogibbs** [comment]
Because his response was rude as are his responses in most other threads. I have reviewed numerous threads on here and the issue has not been resolved as far as I can see?

There is a mention of something similar in the release notes for 2.0.2.1 but I can’t find confirmation of this.

**Comment by manakill** [comment]
@akzogibbs  get used to it, he treats most people like crap. He tried to ban me last week, and was calling me names LOL!!

**Comment by akzogibbs** [comment]
It’s unbelievable behaviour…never mind terrible marketing for Opencart.

**Comment by danielkerr** [comment]
did not try, you were banned and will be again soon. 

for what ever reason you managed to get back on github you are just going to be removed again when they see your comments. just wasting peoples time.

**Comment by christoph1981** [comment]
@danielkerr Show some professionalism you jumped up little shit!
