### ISSUE TITLE
Account -> register -> emailing to admin

### ISSUE THREAD

**Issue by lohe** [opencart/opencart#3009]
Hi,

Found bug in file [opencart_install_dir]/catalog/model/account/customer.php line 79.
Bug appears, when user registers on page and email must be sent to admin (uses MAIL method, not SMTP). $mail->send(); is before when $mail -> sendTo is set and therefore you get blank page. User gets mail, user gets registered, just blank page and no error. Fix is to "comment out" or remove that extra line (cause after that first line there is foreach that sends out mail).

Seams to me also, that this bug is not appearing always, but still at least in some server configs it appears.

**Comment by jamesallsup** [comment]
Looks like this was fixed on this commit:

https://github.com/opencart/opencart/commit/7974e4674258bfe3688c7b54c5c984ddc98d6cf9
