### ISSUE TITLE
Cannot update quantity when using SSL

### ISSUE THREAD

**Issue by stofolus** [opencart/opencart#3013]
I'm using opencart 2.0.0.0

When using SSL the form that gets posted to update the cart quantities posts to an http url instead of an https url. This results in a warning in most browsers and in my case the POST parameters got dropped somewhere and the PHP code got an empty $_POST object.

This results in a new page being rendered only printing an empty JSON object because `catalog/controller/checkout/cart.php:edit()` only redirects to the correct page if there is at least one quantity parameter in the post request. 

I did a workaround in `catalog/controller/checkout/cart.php:edit()` where I changed 
`$data['action'] = $this->url->link('checkout/cart/edit');`
to
`$data['action'] = $this->url->link('checkout/cart/edit', '', true);`

**Comment by danielkerr** [comment]
it will post  to what ever the base tag is set to.
