### ISSUE TITLE
Installing opencart theme on localhost

### ISSUE THREAD

**Issue by w-fa** [opencart/opencart#3014]
Hi,
I'm trying to install Journal - Advanced Opencart theme on localhost.This is the documentation of installing this theme : http://docs.digital-atelier.com/opencart/journal/#/home
After coping the four folders when I install the journal 2 module it shows this error:
Fatal error: Access to undeclared static property: Front::$IS_OC2 in C:\xampp\htdocs\opencart-2.0.1.1\admin\controller\module\journal2.php on line 35
And when I access the store front page It shows a blank page only written : Featured.
What should i do??

**Comment by kanenas** [comment]
You should ask for help here http://support.digital-atelier.com/. This is Journal's official support.

**Comment by w-fa** [comment]
I see but this is a free version of this theme and i only want to install it on localhost

**Comment by kanenas** [comment]
@w-fa this is a <strong>bug tracker</strong> for opencart. You could ask for help here http://forum.opencart.com/.

**Comment by w-fa** [comment]
Thanks :)
