### ISSUE TITLE
Possible bug with order status.

### ISSUE THREAD

**Issue by znvPredatoR** [opencart/opencart#3018]
There is next line in `catalog/model/checkout/order.php` in edit order function:
```php
// Void the order first
$this->addOrderHistory($order_id, 0);
```
now, I'm not sure why it is there but it messes with things that are triggered in addOrderHistory method, when we actually update order_status to new status. That causes bugs like sending 'You received a new order' mail when we actually just updated order, here is an example from `catalog/controller/api/order.php` (line 603-612):
```php
$this->model_checkout_order->editOrder($order_id, $order_data);
// Set the order history
if (isset($this->request->post['order_status_id'])) {
  $order_status_id = $this->request->post['order_status_id'];
} else {
  $order_status_id = $this->config->get('config_order_status_id');
}
$this->model_checkout_order->addOrderHistory($order_id, $order_status_id);
```
Here `editOrder` will set order status as 0, and when `addOrderHistory` set order status to new status inside that method wrong if clauses would be triggered because of that 0 status.

**Comment by danielkerr** [comment]
really you should never edit an order. only void it and create a new one. accounts dont like invoices being changed.

i only added the order edit because people wanted it.

you edit an order its basically a new order. and a new email with all the infroamtion about the order needs to go out. not an order status has changed.

the system works as it should!

**Comment by danielkerr** [comment]
are u sure its not the admin email you are receiving.

**Comment by znvPredatoR** [comment]
How do I change order status then?

On Wednesday, May 20, 2015, Daniel Kerr <notifications@github.com> wrote:

> really you should never edit an order. only void it and create a new one.
> accounts dont like invoices being changed.
>
> i only added the order edit because people wanted it.
>
> you edit an order its basically a new order. and a new email with all the
> infroamtion about the order needs to go out. not an order status has
> changed.
>
> the system works as it should!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/3018#issuecomment-103777178>.
>


-- 
With best regards, Dmitry Solomadin

**Comment by znvPredatoR** [comment]
Does it matter who receives an email? When I edit order in cms nobody
should receive an email that there was new order!

On Wednesday, May 20, 2015, Daniel Kerr <notifications@github.com> wrote:

> are u sure its not the admin email you are receiving.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/3018#issuecomment-103777314>.
>


-- 
With best regards, Dmitry Solomadin

**Comment by danielkerr** [comment]
"When I edit order in cms nobody
should receive an email that there was new order!"

yes they should because the order has been changed.

**Comment by znvPredatoR** [comment]
But that's not a new order, that's a changed order, that confuses everyone.
Also there is a special email in opencart that literally says: "the order
status was updated", when you remove that void method call, everything
works correct.

On Sat, May 23, 2015 at 3:24 PM, Daniel Kerr <notifications@github.com>
wrote:

> "When I edit order in cms nobody
> should receive an email that there was new order!"
>
> yes they should because the order has been changed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/3018#issuecomment-104888361>.
>



-- 
With best regards, Dmitry Solomadin
