### ISSUE TITLE
FedEx shipping module improvements

### ISSUE THREAD

**Issue by opencarthelp** [opencart/opencart#3019]
There are a few modifications to the FedEx shipping module that I think will improve implementation for store owners.

1. The help section for Weight Class states `Set to kilograms or pounds.`  FedEx is strict about this and will only allow for kilogram and pound, singular.  Some store owners add `kgs` and `lbs` units for readability so specifying a more stringent `Set to kilogram (kg) or pound (lb).` and validating it's one of those units on module update can prevent problems.
2. While the FedEx module catches for failures and errors, it can't handle faults.  Modifying /catalog/model/shipping/fedex.php from:

```php
if ($dom->getElementsByTagName('HighestSeverity')->item(0)->nodeValue == 'FAILURE' || $dom->getElementsByTagName('HighestSeverity')->item(0)->nodeValue == 'ERROR') {
	$error = $dom->getElementsByTagName('HighestSeverity')->item(0)->nodeValue;

	$this->log->write('FEDEX :: ' . $response);
} else ...
```

to something like:

```php
if ($dom->getElementsByTagName('faultcode')->length > 0) {
	$error = $dom->getElementsByTagName('cause')->item(0)->nodeValue;

	$this->log->write('FEDEX :: ' . $response);
} elseif ($dom->getElementsByTagName('HighestSeverity')->item(0)->nodeValue == 'FAILURE' || $dom->getElementsByTagName('HighestSeverity')->item(0)->nodeValue == 'ERROR') {
	$error = $dom->getElementsByTagName('HighestSeverity')->item(0)->nodeValue;

	$this->log->write('FEDEX :: ' . $response);
} else ...
```

would allow for faults to be captured and handled.

**Comment by danielkerr** [comment]
for some reason can not test. but have added your code.
