### ISSUE TITLE
$this->config->get('config_mail_protocol') returns NULL

### ISSUE THREAD

**Issue by CLG-Brainstorm** [opencart/opencart#3026]
Mail settings are stored in the db as a serialized array but are not being retrieved by information/contact controller:

var_dump($this->config->get('config_mail_protocol'));
var_dump($this->config->get('config_mail_parameter'));
var_dump($this->config->get('config_mail_smtp_hostname'));
var_dump($this->config->get('config_mail_smtp_username'));
var_dump(html_entity_decode($this->config->get('config_mail_smtp_password'), ENT_QUOTES, 'UTF-8'));
var_dump($this->config->get('config_mail_smtp_port'));
var_dump($this->config->get('config_mail_smtp_timeout'));

outputs NULL NULL NULL NULL string(0) "" NULL NULL

**Comment by CLG-Brainstorm** [comment]
Wouldn't it have made more sense to perform the
html_entity_decode($this->smtp_password, ENT_QUOTES, 'UTF-8')
inside the Mail class, rather than repeating it over a dozen times across admin and catalog folders!?

**Comment by danielkerr** [comment]
yes but its about separating the classes. make sure one does not rely on the other. i looked at other php maill scripts and none have html_entity_decode used for passwords or usernames.

**Comment by danielkerr** [comment]
i think you need to resave settings

**Comment by jamesallsup** [comment]
Yeah please resave your setting if you upgraded to the latest version as the names of these configs have changed. The previous release had a documented bug with using SMTP.

**Comment by gurpreet2501** [comment]
![nirvana](https://cloud.githubusercontent.com/assets/7167688/10301683/597ba128-6c22-11e5-8c37-3d59d4639b59.jpg)
