### ISSUE TITLE
Few bugs fix

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#3028]
File admin/controller/sale/order.php after line 2152:

public function api() {

this line:
$json = array();

catalog/controller/payment/pp_express lines 1573-1577 this edit:

			if (file_exists(DIR_TEMPLATE . $this->config->get('config_template') . '/template/error/not_found.tpl')) {
				$this->response->setOutput($this->load->view($this->config->get('config_template') . '/template/error/not_found.tpl'));
			} else {
				$this->response->setOutput($this->load->view('default/template/error/not_found.tpl'));
			}

admin/view/template/module/google_hangouts.tpl in line 31 this edit:
<?php echo $google_hangouts_code; ?>

**Comment by yvonn** [comment]
Google hangout module:
admin/view/template/module/google_hangouts.tpl in line 31
              <textarea name="code" rows="5" id="input-code" class="form-control"><?php echo $code; ?></textarea>
change this to
              <textarea name="google_hangouts_code" rows="5" id="input-code" class="form-control"><?php echo $google_hangouts_code; ?></textarea>

and line 40/41
              <select name="status" id="input-status" class="form-control">
                <?php if ($status) { ?>
change this to
              <select name="google_hangouts_status" id="input-status" class="form-control">
                <?php if ($google_hangouts_status) { ?>
