### ISSUE TITLE
Image manager issue: Warning: File could not be uploaded for an unknown reason

### ISSUE THREAD

**Issue by garychong** [opencart/opencart#3030]
I can't upload any image by image manager, use ftp no problem.
Opencart version 2.0.1.1
The image directory setting access:755
image no bigger than 300K and file name without any symbol,
When I click upload in image manager and choose file, popup message showme
Warning: File could not be uploaded for an unknown reason!

**Comment by danielkerr** [comment]
server issue

**Comment by garychong** [comment]
Thx daniel,
problem slove
some config wrong in php.ini

**Comment by itsmesai** [comment]
Hi GaryChong !!! I too had same problem. Can you pls tell me what's that config wrong in php.ini ??

**Comment by niyak2** [comment]
ping me on whatsapp 9047262141

**Comment by niyak2** [comment]
@itsmesai  please open that page in firefox and open console and check please ....its because opencart core file issue
code may blocked somewhere, i too had image loading problem in file manager,but i fixed by making some modification in core files

**Comment by garychong** [comment]
Hi itsmesai, in my case I modify
upload_tmp_dir = "/var/www/virtual/YOURNAME/session"
session.save_path = "/var/www/virtual/YOURNAME/session"
done! The file php.ini which NOT inside the www root folder, inside the parent directory.

**Comment by koetsuji** [comment]
@garychong hey man, I didn't find the codes in php.ini, could you help a little bir further?

**Comment by highacid** [comment]
I got the same issue, and upload is enabled in php.ini, any idea what could be a specific .ini option for not allowing file uploads? Here using Safari 9

**Comment by garychong** [comment]
You can try the troubleshooting step:
1.Download your opencart version again from opencart.com and upload filemanager.php and filemanager.tpl to your server.
2.Find out the error log, maybe one of the theme or extension xml file re-generate the wrong command file.
3.The image directory setting access:755
4.Image no bigger than 300K and file name without any symbol
5.Ask your hosting provider for help.

**Comment by furynguyen** [comment]
I have this issue for version 2.3.0 I don't know where I can set values of upload-max-file-size
please help me. it don't work on local and release env

**Comment by danielkerr** [comment]
php.ini u can set max file upload size.

**Comment by luckybhumkar** [comment]
Right..! most time this error belongs to **php.ini** file. Sometime link to **image directory permission level**.
Here is solution [Warning: File could not be uploaded for an unknown reason!](https://doubtsolver.com/ask/332/opencart-warning-file-could-not-uploaded-for-unknown-reason)

**Comment by mscacan** [comment]
**just change cPanel to php version 5.6**
