### ISSUE TITLE
button currency error v2.0.3.0

### ISSUE THREAD

**Issue by yvonn** [opencart/opencart#3035]
v2.0.3.0
Sales => Orders -> Edit 
Continue to Totals and try to change the currency (select another and try to hit refresh)
Undefined variable: button_currency in ...\admin\view\template\sale\order_form.tpl on line 846

**Comment by keramist** [comment]
v2.0.3.0
2015-05-22 16:27:25 - PHP Warning:  Invalid argument supplied for foreach() 
in //system/library/mail.php on line 22

when send email by admin on admin panel it shows error above
use admin/marketing/mail function
but the smtp email system works ok,no error found.all email sent.
how to fix it?

**Comment by yvonn** [comment]
@danielkerr I made some Pull Requests but I guess they are only in my forked OpenCart ( I don't know how to add it in pulls).
https://github.com/yvonn/opencart/pulls
