### ISSUE TITLE
Menu bar buttons not clickable big problem in mobile version

### ISSUE THREAD

**Issue by TheGiftOfMagic** [opencart/opencart#3036]
Hello!

I've recently started with opencart, and am really content with it, exept for the fact that the buttons in the menu bar arent clickable anymore when you add subcategories. (A menu drops down, but if you click the main button nothing happens) In the normal version this is just annoying, but you can still get to the page. In the mobile version there are no drop down menu's, so there it is a VERY BIG PROBLEM since you can't get into the category pages...

Does anyone know what the problem is and how to fix it? I would be very gratefull!

It is not due to any themes or extensions, I've turned them all of to try.
for reference my website is http://www.thegiftofmagic.nl 

Hope anyone can help me.
regards Inge

**Comment by TheGiftOfMagic** [comment]
ehm? why is this closed whe I got no answers yet?

**Comment by milimar** [comment]
It is closed because Daniel does not consider it is a bug. You cannot ask for help here. This is a place for bugs reporting only. You can ask for help at the official forum of OC http://forum.opencart.com . 

Greetings
