### ISSUE TITLE
OC2.0.3 Maintenance Mode switch On automatically  

### ISSUE THREAD

**Issue by haxcop** [opencart/opencart#3042]
Hi i'm trying the new version but after a few minutes the system turns on maintenance mode ON?...
is this an issue or can someone explain to me what's happening?. my apologies if this is closed case already
thanks!

**Comment by danielkerr** [comment]
if you refreshed the modification system then this might cause it

**Comment by haxcop** [comment]
Thanks yes that's what was happening, but this is a new mode because in the previous wasn't like that. 
Thanks you!
