### ISSUE TITLE
OC 2.0.3.0 - admin/model/openbay/amazonus.php

### ISSUE THREAD

**Issue by yvonn** [opencart/opencart#3053]
admin/model/openbay/amazonus.php
line 27
`
			) DEFAULT COLLATE=utf8_general_ci;;");
`
should be
`
			) DEFAULT COLLATE=utf8_general_ci;");
`

**Comment by yvonn** [comment]
same on admin/model/openbay/amazon.php
line 27
`
			) DEFAULT COLLATE=utf8_general_ci;;");
`
should be
`
			) DEFAULT COLLATE=utf8_general_ci;");
`

**Comment by stockmaster** [comment]
Hey Yvonn, you seem to be spotting a lot of those little ones!
Maybe do a PR?

**Comment by yvonn** [comment]
uhh... PR?

**Comment by stockmaster** [comment]
Pull Request here in github

**Comment by yvonn** [comment]
And how do I do that?

**Comment by haxcop** [comment]
> It shouldn't be?
> 
> ) DEFAULT COLLATE=utf8_general_ci;;");
> 


Yours faithfully 
Carlos Lozada

**Comment by yvonn** [comment]
I just added PR

**Comment by jamesallsup** [comment]
I've fixed this on the OBP fork now - will be updated at the next merge. Thanks.

**Comment by yvonn** [comment]
Hi,

Can you take a look at https://github.com/yvonn/opencart/pulls 

I put some more fixes there.

 

Regards

Yvonne

 

Van: James Allsup [mailto:notifications@github.com] 
Verzonden: woensdag 27 mei 2015 11:15
Aan: opencart/opencart
CC: Yvonne
Onderwerp: Re: [opencart] OC 2.0.3.0 - admin/model/openbay/amazonus.php (#3053)

 

I've fixed this on the OBP fork now - will be updated at the next merge. Thanks.

**Comment by jamesallsup** [comment]
Any issues need to be added to the OpenCart tracker so we can prioritise and assign them please.
