### ISSUE TITLE
image manager backdrop lost

### ISSUE THREAD

**Issue by zzxworld** [opencart/opencart#3054]
in admin, any page just has the image manager to open it, when you do select folder or refresh, the black backdrop will be lost.

**Comment by GomDani** [comment]
Change in common.js

```$('body').append('<div id="modal-image" class="modal">' + html + '</div>');```

to

```$('body').append('<div id="modal-image" class="modal"><div class="modal-dialog modal-lg">' + html + '</div></div>');```

and remove from 

filemanager.tpl

`<div class="modal-dialog modal-lg"></div>.`

Bootstrap now attach backdrop on modal, and not on body. And when add html on modal remove the backdrop.

**Comment by zzxworld** [comment]
thanks, @GomDani, now is working.
