### ISSUE TITLE
Opencart 2.0.1.0 add order in admin

### ISSUE THREAD

**Issue by Darylt** [opencart/opencart#3055]
When I try to add an order in admin it tells me that a payment method is required.  Paypal express checkout is installed and shows as the selection.

![image](https://cloud.githubusercontent.com/assets/12604460/7805023/9dead7c0-03ae-11e5-9c68-a3a1fec2588f.png)

**Comment by yvonn** [comment]
Did you hit the refresh button (next to payment)?

**Comment by Darylt** [comment]
Hi

Thank you that worked!

**Comment by yvonn** [comment]
You can close this issue :-)
