### ISSUE TITLE
Filemanager image will not open if anyone image has filename empty

### ISSUE THREAD

**Issue by niyak2** [opencart/opencart#3056]
Hi ,
Our company client has one opencart website that is in opencart v 1.5.6.1 , in that one issue is arised it is because of opencart core functional issue, in admin side the image isnt loaded , they added lot of images but nothing shown in the filemanager.

it is with the error "TypeError: json[i].filename is null", like this it shown, because of one image without name the whole image loader got blocked,

so i added this code in filemanager.tpl

if (json) {
for (i = 0; i < json.length; i++) {
if(json[i]['filename'] != null)
{
html += '<a><img src="<?php echo $no_image; ?>" alt="" title="" /><br />' + ((json[i]['filename'].length > 15) ? (json[i]['filename'].substr(0, 15) + '..') : json[i]['filename']) + '<br />' + json[i]['size'] + '<input type="hidden" name="image" value="' + json[i]['file'] + '" /></a>';
}
}
}

please review this core error and please avoid this in next versions

**Comment by kanenas** [comment]
Have you checked the master branch?

**Comment by niyak2** [comment]
Master Branch?

**Comment by pekka2** [comment]
@niyak2 
Is images added to directory `image/catalog`  or `image/data`?

**Comment by niyak2** [comment]
yes

**Comment by niyak2** [comment]
wait i will upload images

**Comment by niyak2** [comment]
@kanenas  hi please refer the screenshots, that issue i fixed

**Comment by kanenas** [comment]
@niyak2 Go here https://github.com/opencart/opencart/tree/v1.5.6.x download the latest v.1.5.6.5_rc and test it.

**Comment by niyak2** [comment]
Thank you @kanenas  .
