### ISSUE TITLE
Google Sitemap error Oc 2.0.0-2.0.3.0

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#3057]
catalog/controller/feed/google_sitemap.php line 47:

$output .= '&lt;loc&gt;' . $this->url->link('product/product', 'manufacturer_id=' . $manufacturer['manufacturer_id'] . '&amp;amp;product_id=' . $product['product_id']) . '&lt;/loc&gt;';

change to:

$output .= '&lt;loc&gt;' . $this->url->link('product/product', 'manufacturer_id=' . $manufacturer['manufacturer_id'] . '&product_id=' . $product['product_id']) . '&lt;/loc&gt;';

**Comment by mhcwebdesign** [comment]
I think the same is true for line 95:

Replace
```
				$output .= '<loc>' . $this->url->link('product/product', 'path=' . $new_path . '&amp;product_id=' . $product['product_id']) . '</loc>';
```
with
```
				$output .= '<loc>' . $this->url->link('product/product', 'path=' . $new_path . '&product_id=' . $product['product_id']) . '</loc>';
```

**Comment by opencart-russia** [comment]
see http://www.sitemaps.org/protocol.html#escaping
need replace  & to &amp;

example 
```
$link = $this->url->link('product/product', 'path=' . $new_path . '&product_id=' . $product['product_id']);
$output .= '<url>';
$output .= '<loc>' . str_replace('&', '&amp;', $link) . '</loc>';
```
similar changes to make in 6 locations

And I already reported the error, but @jamesallsup said that there are no errors ((
https://github.com/opencart/opencart/issues/2770

**Comment by pekka2** [comment]
@opencart-russia 
Method "link" from class "Url" does that (system/library/url)

**Comment by niyak2** [comment]
Thank u

**Comment by opencart-russia** [comment]
@pekka2 I wrote without thinking. My fault.,

**Comment by exit15** [comment]
have v 2.0.3.1 and i get this error:
XML Parsing Error: not well-formed
Location: http://www.mysite.com/index.php?route=feed/google_sitemap
Line Number 3, Column 57008:

**Comment by mhcwebdesign** [comment]
@exit15: Nobody can reproduce your error, let alone do something about, unless you provide some more details. Also, you should post it on the OpenCart forum.
