### ISSUE TITLE
we are not  getting any email  while making new registration in 2.0.3.0 opencart

### ISSUE THREAD

**Issue by sbglobal** [opencart/opencart#3060]
Hello !

we are not  getting any email  while making new registration in 2.0.3.0 open cart.
![mail issue]. we  are using mail function . we  already enabled  new account  email alert from store setting !  

(https://cloud.githubusercontent.com/assets/8528070/7835899/5abab36c-04d0-11e5-8c80-c60fa8ab051c.png)

**Comment by jamesallsup** [comment]
You need to use the forums for help, it is either a hosting issue or it is being spammed.

Github is for bugs relating to the core.

**Comment by niyak2** [comment]
hosting issue so please consult your hosting provider
