### ISSUE TITLE
Gift Voucher can be used more than once in OpenCart 2.0.2 Ver. problem

### ISSUE THREAD

**Issue by AshrafSello** [opencart/opencart#3067]
I tried to apply the same gift voucher code to more than one order it pays all the order, i.e.: the problem that you can use the same gift voucher code more than once so the seller will lose these amount of occurrence.
Please fix and notify.

**Comment by danielkerr** [comment]
you need to set up the correct order statuses

**Comment by AshrafSello** [comment]
I know that the status should be set to " Disabled " but this must be done automatically once the gift voucher applied to any order instantly to prevent multi use of the voucher in another orders, if the status of the voucher left active till it set manually to disabled mode many other order can be place by the same gift voucher code which is a big loss problem to the seller.
This Fix should be: Auto. Disable the gift voucher code once applied in any order, re enable it could be done manually with no problem.

**Comment by sparkcom** [comment]
I agree this is a big problem for the shop owner and it needs to be fixed. I will try to look into this myself in one of our sites and see if i can come up with a quick fix.

**Comment by stockmaster** [comment]
@AshrafSello  please see this issue maybe it can help. 
https://github.com/opencart/opencart/issues/3093
