### ISSUE TITLE
Maxmind Error !

### ISSUE THREAD

**Issue by haxcop** [opencart/opencart#3069]
HI, i just create an order with paypal express and with the maxmind service active on oc2.0.3.1 and i just got this error message after the paypal process , but  when i click back it shows me the successful page of paypal. any ideas? 
![6ee1a90d40cf66db1a6ad5993e86a836 copy](https://cloud.githubusercontent.com/assets/7826906/7904590/188a5646-07fa-11e5-832c-acc91f486e41.png)

**Comment by pekka2** [comment]
Is this old code? You try line 6 in file catalog/model/fraud/maxmind.php:
`$fraud_info = $this->getFraud($data['order_id']);`
change to:
`//$fraud_info = $this->getFraud($data['order_id']);`

**Comment by haxcop** [comment]
Sorry for the delay @pekka2  what do you mean "is this old code?". and also that error that i get i think will be for everyone here using oc.2.0.3.1 , have you make the pull request yet?

**Comment by pekka2** [comment]
The variable "$fraud_info" does not refer anywhere else in the whole file. It gives the impression that this line 6 is unnecessary.

**Comment by haxcop** [comment]
Hi, thanks for your comments. @danielkerr  Hi, can you please check this error and let us know if you are agree with or there's other Reason>? Thanks @pekka2

**Comment by mrnfrancesco** [comment]
The `getFraud` method was deleted in commit https://github.com/opencart/opencart/commit/a0f3a115fce8dd9b55e121af2e4a464316b540a2

I'll make a pull request fixing it in minutes.

**Comment by haxcop** [comment]
Hi @mrnfrancesco & @pekka2 Thanks for your Support! Now let's see if Daniel think is right or not.
Best Regards

**Comment by jamesallsup** [comment]
Merged.

**Comment by 44kaine** [comment]
Did we get some kind of solution for this issue, encountering exactly the same using OC 2.0.3.1 just recently downloaded and installed. Weird that a default module doesnt work
