### ISSUE TITLE
seo url problem on other functions like domain.com/contact/success

### ISSUE THREAD

**Issue by hemanjosko** [opencart/opencart#3070]
Hello  I am using opencart 2.0.1
My problem is that like url

I already enabled seo urls and htaccess.

domain.com/contact/success is not working its calling only same contact page not showing the message that contact us successfully something.

and my other custom pages also not working like my blog and all.  with the seo keyword of blog its not opening the particular post.

**Comment by danielkerr** [comment]
opencart is not wordpress. wordpress is a simple blog system where you can get away with keywords in the url. opencart is a lot more complex. it does not support keywords for contact us pages also its completely unneeded.

**Comment by hemanjosko** [comment]
Thank for Answering me daniel, But i think url rewriting is needed everywhere for better seo and cool representation of urls.

In the setting why is there seo keyword enable thing. This thing I dont understand. it enables keywords for information pages products pages and all. i think that than this function is also not needed on the settings page..

Overall Thankyou

**Comment by milimar** [comment]
@hemanjosko the real place for asking help is the forum of opencart http://forum.opencart.com . You should be happy that Daniel answered you once, I think he will not continue answering your questions, because this is a place for reporting bugs. 

Greetings.
