### ISSUE TITLE
Wrong event name for new address and login trigger not working

### ISSUE THREAD

**Issue by vinyl919** [opencart/opencart#3071]
Hi, 
Event name for add new address should be post.customer.add.address (catalog/model/account/address.php, line 4), not like given post.customer.address.add.
Also it seems that post.customer.login  to not working properly. I've added trigger code in catalog/controller/account/login.php, line 55. Now it seems to work correctly. Before that it was not triggering any action.

**Comment by niyak2** [comment]
good work

**Comment by milimar** [comment]
@vinyl919 why don't you share with us the trigger code? I might help us...

**Comment by jamesallsup** [comment]
catalog/model/account/address.php, line 4 is the PRE event, line 14 is the POST event, working ok on my tests.

Pre events happen before data is modified / action is taken, post events happen after.

**Comment by vinyl919** [comment]
Yes, the address trigger working fine. What I mean was that it is a mistake in documentation. Event name in file is "post.customer.add.address" and "pre.customer.add.address", but in documentation it is "post.customer.address.add" and "pre.customer.address.add". It is just a wrong order of words:)

@madhurjain It is just code from line 10 of catalog/controller/account/login.php - "$this->event->trigger('pre.customer.login');"

**Comment by jamesallsup** [comment]
OK great, that's updated now in the docs.

Thanks.

**Comment by vinyl919** [comment]
I'm going to use a lot of triggers now, so maybe if I find any issues I will post them here.
Another one mistake in docs is twice "pre.customer.newsletter.edit", one of them should be "post.customer.newsletter.edit" :)
