### ISSUE TITLE
i got this issue when i try to change status order

### ISSUE THREAD

**Issue by r1ant** [opencart/opencart#3072]
http://i.imgur.com/8eLnKA2.png

when i try to change the status order give me this error

Error here:
$this->response->addHeader('Content-Type: application/json');
		$this->response->setOutput($json);

**Comment by valdeir2000** [comment]
Add
`$json = array();`

after
`public function api() {`

**Comment by gilas1959** [comment]
Hi, i got the same error (under Chrome) commenting the history of the order.
Under Mozilla I can see this popup:
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
OK

I have modified the file as suggest, nothing goes right.

O.C. version: 2.0.2.0

configuration:
* API loaded string created

* user related to API is OK

* permission to change status from system > settings > myshop > options is OK, all configure:
Processing Order Status > all checked
Complete Order Status > all checked

* shop is not under maintenance mode

DNS configuration:
* I have not bought a DNS
* the shop is hosted within my VPS (Linux CentoOS)
* /etc/hosts on my VPS is configured with the IP of the server and the name, ie:
MY.IP.ADD.RESS myshop.com
* my PC is configured (linux), as follows
file: /etc/hosts
MY.IP.ADD.RESS myshop.com
(same address above)

I do login into my VPS then give:
ping MY.IP.ADD.RESS
but I have no answer.

I suspect that O.C. cannot work until there is a DNS available and bought from a provider.

But I have no docs about this.
Forgive me but the forum cannot help and I can't solve this issue, please help.

I su

**Comment by gilas1959** [comment]
HI you closed this issue 3 days ago; I have not received any answer.
Moreover you closed it without a solution, why?!?
