### ISSUE TITLE
The page you requested cannot be found error

### ISSUE THREAD

**Issue by querious** [opencart/opencart#3078]
Hi,

I've recently been seeing this issue when trying to access my website. I'm using Opencart 1.5.6.4.
"The page you requested cannot be found". (Please see attachment)

Unfortunately, this issue is intermittent and it seems to happen for no apparent reason.

When checking the error logs, I see this error message:-

PHP Warning: array_key_exists(): The first argument should be either a string or an integer in /hermes/bosnaweb05a/b327/username/public_html/website.com/index.php on line 171

Upon opening up index.php, I see this code on line 171:

if (isset($session->data['language']) && array_key_exists($session->data['language'], $languages) && $languages[$session->data['language']]['status']) {
$code = $session->data['language'];
} elseif (isset($request->cookie['language']) && array_key_exists($request->cookie['language'], $languages) && $languages[$request->cookie['language']]['status']) {
$code = $request->cookie['language'];
} elseif ($detect) {
$code = $detect;
} else {
$code = $config->get('config_language');

I have read that it could be a session issue and have reported this to iPage (our hosting provider) but they have no idea what is wrong or how to fix the issue.

I'm stuck and have no idea what else to do. It looks really bad on us as new customers are thinking that our website is intermittently down, when it actually isn't.

Could someone help please? Thanks so much in advance.
![img_2151](https://cloud.githubusercontent.com/assets/10379344/7976824/a05c751e-0ac4-11e5-884b-6eb2ed6347fd.PNG)

**Comment by querious** [comment]
Hi,

May I know why was this issue closed? There is no update at all?

**Comment by milimar** [comment]
It is because it is not a bug. Why don't you try to post to the official forum of OC http://forum.opencart.com , there might be someone who will be able to help you.

Greetings

**Comment by querious** [comment]
Hi milimar,

Thanks for your reply. I have tried to post the issue at the forum but it doesn't seem like anyone knows what is wrong. The issue is really affecting us badly as customers are thinking our website is intermittently down (and dodgy), which it actually isn't. 

Do you have any ideas as to why this could be happening? Have you seen issues like this before? It would be great if you could provide some guidelines on how to go about this.

Thanks so much for your help in advance.

**Comment by milimar** [comment]
I understand your problem and I would help if I could, but I cannot help you directly because I do not know the solution, but at least I have an idea, you can try to obtain a commercial help, check this http://www.opencart.com/index.php?route=support/support . That is all I can do for you, good luck!
