### ISSUE TITLE
Missing SSL

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#3081]
In account order reorder function missing SSL in redirect url.

**Comment by tiborbesze86** [comment]
SSL link generation seems to be quite inconsistent. Possible workaround is to use an https URL for the HTTP_SERVER variable in your config.php files.

**Comment by danielkerr** [comment]
does not require a SSL url because there is no personal information on it. you only need ssl when secure information is being posted.

**Comment by GomDani** [comment]
OK, but why is used SSL in the order list? Is not the same?
