### ISSUE TITLE
FTP fails to upload Extensions 

### ISSUE THREAD

**Issue by geopayme** [opencart/opencart#3085]
I have setup my FTP correctly but I noticed one feature, it requires TLS but I cant find it anywhere as an option in OpenCart. So How does someone install extensions if the FTP is not working because it lacks the security features.

**Comment by geopayme** [comment]
In log files I get this error recorded:

2015-06-06 3:06:44 - PHP Warning:  ftp_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/content/28/11098828/html/cookingstore/admin/controller/extension/installer.php on line 292

I use ftp from a GoDaddy Reseller

this is my ftp URL -->253.340.myftpupload.com it works fine in filezilla!

**Comment by geopayme** [comment]
I tested it directly with the IP --> 184.168.205.158, and I still get the same error

**Comment by geopayme** [comment]
The extension installer seems to be out of wake... anything I try to upload, either it fails to connect or this message --> Invalid file type!

**Comment by mhcwebdesign** [comment]
This is not a bug report. For support questions, please use the OpenCart forum. 

BTW.: You could use the extension installer workaround from iSense Labs: http://www.opencart.com/index.php?route=extension/extension/info&extension_id=18892

**Comment by geopayme** [comment]
The "fix" from iSense does not work... so I consider it a serious bug for the open cart platform. Some should offer alternative choices to the bug.

**Comment by milimar** [comment]
@geopayme , what version of OC do you have? I just tested the extension installer and in 2.0.3.1 and it works fine. For testing I installed this extension 

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=19862&filter_license=0&filter_download_id=41&page=1

It might be helpful to you as it is a free extension to upload without a FTP.  Here you can see how it looks like after the installation. As @mhcwebdesign said, better use the Forum.

![screen1](https://cloud.githubusercontent.com/assets/9386798/8026316/46ff151c-0d71-11e5-99fb-ab9c437cc088.jpg)

**Comment by geopayme** [comment]
Maybe after 35 years of development I am loosing my touch... since we are
sharing pictures here are mine!

a shot with the plug/extension fix installed and my after shot of the
Extension Installer

No doubt we are all correct.... your thoughts?



​

**Comment by geopayme** [comment]
Thanks for the heads up the link you posted has a different version of the
fix not from iSense, worked it out for now!

Cheers
