### ISSUE TITLE
browser format is all messed up after upgrade

### ISSUE THREAD

**Issue by rebeccastanke** [opencart/opencart#3088]
![opencart](https://cloud.githubusercontent.com/assets/11907916/8022040/9910d5d8-0c6e-11e5-9b9c-89db348d26d8.JPG)
I can no longer view all customer information, this is not usable, can I go back to the last version

**Comment by milimar** [comment]
@rebeccastanke , I just installed OC2.0.3.1 for testing purposes and I am trying to check your issue. I suppose you refer on upgrade to 2.0.3.1. I am trying to recreate your error but I am not sure if you refer on clicking the bell icon at the right upper corner of admin? If so, my installation shows the information correctly, here is the screenshot: 

![screen](https://cloud.githubusercontent.com/assets/9386798/8023607/3fa98c10-0d13-11e5-9d9c-c724a34d88b7.jpg)

If not, please explain better and I will check it.

Greetings.

**Comment by mrnfrancesco** [comment]
Cannot reproduce the issue. Could you write a step-by-step instructions and OC version informations?

**Comment by milimar** [comment]
@mrnfrancesco , at first I wanted to answer the same you answered, but then I realized that @rebeccastanke updated her version of opencart and after that she has problems. So, as I understand, we are not talking about errors in OC 2.0.3.1 , but in the updated version of @rebeccastanke .

**Comment by rebeccastanke** [comment]
yes, since I updated, when I login I no longer have access to all my
customers information, I have to click on each customer and view their
information.
http://minecraftschooloflearning.com/ocart2/admin/index.php?route=common/dashboard&token=277103eb9674ce74643eb89abd998cdf
the formatting looks like this.
when I click on total customers, I see this

**Comment by milimar** [comment]
@rebeccastanke , before updating your OC version you should make a full backup and thus later you can reverse the changes. This is not a bug and this a a place for bug reporting. In the future you should post and try to obtain help here http://forum.opencart.com .

**Comment by rebeccastanke** [comment]
So I tried it in Firefox and it formats correctly - Must be an IE thing
