### ISSUE TITLE
At Least add correct info - Event Wiki

### ISSUE THREAD

**Issue by Nikhil-7** [opencart/opencart#3090]
https://github.com/opencart/opencart/wiki/Events-(script-notifications)

If you are loading 
$this->load->model('tool/event');
then use this
$this->model_tool_event->addEvent($args);

or if you are using 
$this->load->model('extension/event')
then update code to
$this->model_extension_event->addEvent($args);

Yeah it's baby issue and you are noob :-1:

**Comment by mhcwebdesign** [comment]
It should be:
```
$this->load->model('extension/event');
$this->model_extension_event->addEvent($args);
```

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/wiki/Events-(script-notifications)/47a244e8cde4fc40b629df729fd0f36b3ba8e31e
