### ISSUE TITLE
Admin permissions problem?

### ISSUE THREAD

**Issue by r1ant** [opencart/opencart#3091]
[img]http://i.imgur.com/N3NPFr1.png[/img]

any solutions i think was admin permissions 

i have version 2.0.2.0 clean install

**Comment by haxcop** [comment]
Hi, 1st you must verify the permission of the files. For reference you can ask or search in oc documents at the main site Opencart.com and forums this site is for bugs and improvements only. 
2nd I strongly recommend you to use always the last version 2.03.1 current 


Yours faithfully 
Carlos Lozada
