### ISSUE TITLE
Paypal Express Payment Module - exclude totals - hard-corded

### ISSUE THREAD

**Issue by traedamatic** [opencart/opencart#3094]
Hello everyone,

I've created two new custom total modules for a custom shop. Everything worked fine. The totals were displayed completely correct in all view. But then we added the Paypal Express payment module. After the redirect to the Paypal Server we saw a wrong total amount. A reason for that was that the two new custom totals were added to the PayPal cart. 

I started to wonder, because the sub_total and the total total modules were not added to the PayPal cart. So i looked at the catalog/model/payment/pp_express.php and found this line:

```php

   if (!in_array($total_row['code'], array('total', 'sub_total'))) {

```
(https://github.com/opencart/opencart/blob/master/upload/catalog/model/payment/pp_express.php#L264)

I think this makes the it really difficult to use the PayPal Express payment module with custom total modules. Or do I miss there something?

In my opinion a better solution is to create a new config field for the Paypal express module were the admin a add totals that should be displayed within the PayPal cart.

Nicolas

**Comment by haxcop** [comment]
Hi, which version of oc are you using?

Yours faithfully 
Carlos Lozada

**Comment by traedamatic** [comment]
I use the version 2.0.1.1.
Nicolas

**Comment by haxcop** [comment]
HI, i am not sure if you have an issue or it’s a simple misconfiguration of your Paypal Account. 
Please try this and let us know if this worked for you.

Log on to your PayPal account, it's under "Profile → My selling tools → Shipping my items", then the "Update" link, the checkbox at the very bottom of the Shipping calculations page. you need to check that box.

Best Regards
Carlos Lozada

**Comment by traedamatic** [comment]
No, that does not solve the problem.  Our custom shipping module works fine. The problem are the new totals we created. But I get the point of your code. You think that all totals do affect the payment amount, which is probably correct in most cases.  But in our case the approach causes some strange amounts.  Don't have a good solution for that right now.

Nicolas
