### ISSUE TITLE
Duble Encode in search url

### ISSUE THREAD

**Issue by NeoCsatornaja** [opencart/opencart#3099]
Hy!
I have a Big problem.
After I Installed this extension:
www.opencart.com/index.php?route=extension/extension/info&extension_id=6204
My search url get some issu:
https://www.eherbaria.hu/index.php?route=product%252Fsearch&search=valami
The problem is this character:
<b>%252F</b>
Becuse this means /, but some how the broweser can't understand this character.
I tryed remove this extension but the problem is not solved.
Any help would be greatfull!

**Comment by haxcop** [comment]
HI, Please contact the Developer of the Extension, this is not the place for your queries. 
Have a good day

**Comment by NeoCsatornaja** [comment]
Okey, I know, just a little tips need where I can find this bug.
Which fils could be touched?
