### ISSUE TITLE
IoS HTML format error

### ISSUE THREAD

**Issue by digit69** [opencart/opencart#3100]
Order confirmation email to admin on iphone is malformed - all other html emails work fine on the iphone.

Subject comes through fine with Order ID.

Opencart
Version 2.0.2.1_rc

body

This message cannot be displayed because of the way it is formatted. Ask the sender to send it again using a different format or email program. multipart/related

![screen shot 2015-06-10 at 14 48 56](https://cloud.githubusercontent.com/assets/12830625/8083954/10563520-0f80-11e5-8b3e-9681d73929ab.png)
![img_3074](https://cloud.githubusercontent.com/assets/12830625/8084004/48605072-0f80-11e5-8aa5-3221ab5007fb.PNG)

**Comment by scrollup** [comment]
See opencart/upload/system/library/mail.php

The HEADER is set as Content-Type: multipart/related;.

Emails received by the iOS mail app are showing just "This is a HTML email and your email client software does not support HTML email!" or a message like you're receiving, and not the HTML part at all.

From googling it seems to be a known issue with Apple.

I suggest changing the structure to have the HEADER set to Content-Type: multipart/alternative; which in my tests correctly displayed the html section. You'll also need to modify the boundaries and other parts of the structure. Perhaps someone has a better solution?

**Comment by danielkerr** [comment]
@scrollup thx for that! i could not test because I dont own an iphone and never will

**Comment by chrisice** [comment]
I was able to resolve the issue on iOS on one of my sites by changing this line in case it helps someone later.  

# diff mail.php mail.php-org
105,106c105
< //		$header .= 'Content-Type: multipart/related; boundary="' . $boundary . '"' . PHP_EOL . PHP_EOL;
<                 $header .= 'Content-Type: multipart/alternative; boundary="' . $boundary . '_alt"' . PHP_EOL . PHP_EOL;
---
> 		$header .= 'Content-Type: multipart/related; boundary="' . $boundary . '"' . PHP_EOL . PHP_EOL;

**Comment by danielkerr** [comment]
i think the above code you posted will cause more issues. the boundry is not the issue.

**Comment by chrisice** [comment]
I changed both the Content-Type and the boundary, which I copied from a little further down in the mail.php file.  Everything looked like it was working correctly when I tested it after making that change.  What are you thinking that it will cause issues with?  I'll test it out and make sure
