### ISSUE TITLE
Customers orders report wrong information

### ISSUE THREAD

**Issue by MKuzma** [opencart/opencart#3101]
There is a bug showing in customers orders report wrong number of orders and total amount. The SQL query is wrong and multiplies the number of orders and total amount by the previous result from a LEFT JOIN  ... op ON (o.order_id = op.order_id) clause. See attached images where a registered customer and an unregistered customer have each one order. The registered customers order has 3 products and unregistered 2 products. In customers orders report for registered customers I see 3 times multiplied total and the number of orders. Correct should be one order and total $505.

![ocbug2](https://cloud.githubusercontent.com/assets/12835446/8092989/351b2242-0fbe-11e5-9ea9-9673ed6e839e.png)
![ocbug1](https://cloud.githubusercontent.com/assets/12835446/8092992/36f09cbe-0fbe-11e5-906e-3bb0deb519d3.png)

**Comment by mrnfrancesco** [comment]
Issue fixed with pull request #3105. Waiting for merge.

**Comment by danielkerr** [comment]
the fix you have added is completely wrong! all you have done is block the system from being able to show another order total of the same amount!
