### ISSUE TITLE
Historical Fraud data is missing after 2.0.3.1

### ISSUE THREAD

**Issue by tiborbesze86** [opencart/opencart#3102]
Hello,

I've just noticed, after I've upgraded my dev server from 2.0.2.0 to 2.0.3.1, that historical fraud data is no longer shown on the order details page. I've checked, and the oc_order_fraud table is still in place, so I was just wondering, if it's something you guys missed during the process of making Opencart to support multiple fraud detection services.

All the best.

**Comment by danielkerr** [comment]
not missing the table got renamed
