### ISSUE TITLE
Mail alert Not working in Opencart 2.02

### ISSUE THREAD

**Issue by neeraj10786** [opencart/opencart#3104]
Hi,

i am using opencart: Version 2.0.2.0
i am not able to receive any of mail from website ( new account creation, order, newsletter etc. )
Please let me know how to solve this issue

**Comment by niyak2** [comment]
please consult your hosting provider

**Comment by neeraj10786** [comment]
Hi, this is not hosting issue.. this is opencart issue.
when user create account.. i didn't receive any Alert.. when i active alert from admin.. register button shows blank page ( after filling/creating account n click on submit/create account button)... but i didn't receive any of mail for this account creation

**Comment by niyak2** [comment]
oh okok i will check and update u soon

**Comment by mrnfrancesco** [comment]
From @neeraj10786 first comment
> i am using opencart: Version 2.0.2.0

**Comment by mhcwebdesign** [comment]
Unable to reproduce this error, not an Opencart bug, it's either a hosting issue, or else should be posted on the Opencart forum.
