### ISSUE TITLE
API-login.php 

### ISSUE THREAD

**Issue by r1ant** [opencart/opencart#3106]
Hi, im new to opencart and when i try to change order status this happen and dont change order status

http://i.imgur.com/XcieABl.png

and the register log show this after i try to change any order status

2015-06-12 7:32:12 - PHP Warning:  json_encode(): Invalid UTF-8 sequence in argument in /var/www/vhosts/96/243934/webspace/httpdocs/electrotecnia.com/loja/catalog/controller/api/login.php on line 37

line 37 is :
http://i.imgur.com/FMqG7TH.png

any solutions? i really need to change order status for customers see and just dnt know what to do

i already create other api user but same error ocurred

**Comment by milimar** [comment]
Hi, you don't say which version of OC you use. I have installed 2.0.3.1 and no problems with changing order statuses. 

Greetings

**Comment by mhcwebdesign** [comment]
This is for reporting Opencart bugs, support requests should be posted on the Opencart forum.

**Comment by danielkerr** [comment]
Closing this as its related to tge curl loopvack issue
