### ISSUE TITLE
Historical Fraud data is missing after 2.0.3.1

### ISSUE THREAD

**Issue by tiborbesze86** [opencart/opencart#3108]
Hello,

I've opened an issue on this, but it has been ignored and closed (not even mentioned what's the new name of the table).
https://github.com/opencart/opencart/issues/3102

Even if you ignore the issue, it's still an issue. I had v2.0.2.0, and upgraded to v2.0.3.1 using the official upgrade script, and fraud data doesn't show anywhere on the admin side.

**Comment by danielkerr** [comment]
it was not ignored, I replied. its an issue you have and post on the forums not here. this is for the development only. not problem solver for you.

**Comment by danielkerr** [comment]
the new table name is maxmind and it only appears when you install the anti fraud maxmind plugin. 

you need to import the data into the new table or do some table renaming.
