### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by thebergamo** [opencart/opencart#3110]
I dowload the opencart 2.0 for testing in a new project.
But when I upload my files to my server, rename the files correctly and set the permissions (755 or 777) when I try access the url of my store simply the index.php are dowloaded.

Months ago, I use the version 1.6 and this behavior not occurrs, the new version have an new way to install or something like that? I'm really lost to next steps.

I currently use the PHP 5.3.

**Comment by beifloyd** [comment]
this is clearly nothing to do with OC and it should not be posted here.

the file is downloaded because the PHP parser is not not working properly. try to restart apache see if that fixes your problem.

**Comment by thebergamo** [comment]
Thanks for your reply @beifloyd trying reload my apache this issue still!

Sorry, for posting this here. I'll close this issue.
