### ISSUE TITLE
OpenCart 2.0.2.0 error: SyntaxError Unexpected end of input OK

### ISSUE THREAD

**Issue by ofersb** [opencart/opencart#3111]
hello

When updating order history, getting the error Unexpected token in chrome
i follow the issue https://github.com/opencart/opencart/issues/1825
and follow the guide:
https://www.fastcomet.com/community/opencart-2-error-syntaxerror-unexpected-end-of-input-ok/

I did all needed like new api user, disable maintenance mode, set my config.php not use https
all this did not fix my problem
I can't update or delete my orders.
no 3rd party modules installed, hosting on ipage.com

any suggestions?
thanks

**Comment by webwaveCH** [comment]
We have the same problem. Everthing checked. 
Is there no fix/workaround for loopback connection problem?

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/issues/3062
