### ISSUE TITLE
[2.0.3.1]  \upload\catalog\model\openbay\ebay_product.php

### ISSUE THREAD

**Issue by gob33** [opencart/opencart#3115]
Line 273: utf8_decode() has only 1 parameter possible not 3.
Confusion with html_entity_decode()
Error since 1.5.6.4 at least.

**Comment by mrnfrancesco** [comment]
Line 273 in `upload/catalog/model/openbay/ebay_product.php` in OC 2.0.3.1 is:

```
$this->db->query(
"INSERT INTO `" . DB_PREFIX . "product_description` SET
`product_id` = '" . (int)$product_id . "',
`language_id` = '" . (int)$this->config->get('config_language_id') . "',
`name` = '" . $this->db->escape(htmlspecialchars(base64_decode($item['Title']), ENT_COMPAT, 'UTF-8')) . "',
`description` = '" . $this->db->escape(htmlspecialchars(utf8_encode($item['Description']), ENT_COMPAT, 'UTF-8')) . "'");
```
There is no `utf_decode()`, but `utf_encode()`; by the way, it has just one parameter which is `$item['Description']`.

So, what's the problem? I really don't understand this issue.

**Comment by gob33** [comment]
You are right, I missed the closing )
