### ISSUE TITLE
library-image->watermark not work

### ISSUE THREAD

**Issue by opencart-russia** [opencart/opencart#3119]
Hi. In image library function watermak not work.
\system\library\image.php

1. See line:
private function create($image) {
$mime = $this->info['mime'];

2. See line:
imagecopy($this->image, $watermark, $watermark_pos_x, $watermark_pos_y, 0, 0, 120, 40);

**Comment by CoverUp** [comment]
Works for me, idk what r u pointing here, lines r correct.
BTW i use this instead for customization purposes 
imagecopy($this->image, $watermark, $watermark_pos_x, $watermark_pos_y, 0, 0, $watermark_width, $watermark_height);//CoverUp

**Comment by idcorp** [comment]
How I can insert watermark on all images in the OP 2.2, I can not solve .
Thanks!!
