### ISSUE TITLE
Wiki OCMOD

### ISSUE THREAD

**Issue by periscuelo** [opencart/opencart#3123]
In first place, congratulations about that excelent work in opencart.

The Ocmod braces not work in O.C. 2.0.3.1. Why the wiki not updated with this information and a new method to use something similar at braces?

Thanks.

**Comment by mhcwebdesign** [comment]
Wildcard paths were silently broken in OpenCart 2.0.2.0. The new method is comma separated full paths, for example:

```
    <file path="system/engine/action.php,system/engine/loader.php,system/library/config.php,system/library/language.php">
```

**Comment by danielkerr** [comment]
you can still do system/engine/*.php

**Comment by danielkerr** [comment]
also it was changed to cover a previous issue.

**Comment by danielkerr** [comment]
updated

https://github.com/opencart/opencart/wiki/Modification-System
