### ISSUE TITLE
Warning: ini_set(): A session is active

### ISSUE THREAD

**Issue by haipham** [opencart/opencart#3131]
When install Revolution Slider module, I getting error:

Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /.../system/library/session.php on line 8Notice: A session had already been started - ignoring session_start() in /.../system/library/session.php on line 16.

Disabled sessions auto start with session.auto_start = Off and register_globals = Off settings in php.ini and restart MAMP web server, but don't work.

I fresh install opencart 2.0.3.2_rc version.

(session.php file in v2.0.3.1 work fine for 2.0.3.2_rc). Please help me fix this problem.

Thank you.

**Comment by milimar** [comment]
I think you should contact the creator of the RS.

**Comment by danielkerr** [comment]
no this is an issue with the master branch. i can fix it

**Comment by haipham** [comment]
@danielkerr, problem solved. Work like a charm. Thank you.
