### ISSUE TITLE
Product count very slow on large store

### ISSUE THREAD

**Issue by drenda** [opencart/opencart#3138]
Hi,
I'm trying to import ~68.000 products and ~1320(category+subcategories) in my opencart store. I'm using the 2.0.3.1 release.
In product count in categories is enabled, then the store is unusable!! It's very very very slow.
I think there is some problem in queries that make the count of products.

Can you check please?

Thanks

**Comment by beifloyd** [comment]
It's reported in the documentation that product count in the category slows down the system and is suggested to have it off for large stores. 68.000 products and ~1320(category+subcategories) is indeed a very large store. Ask in the forum and probably someone with more experience can assist you to optimise it for speed. Not really a bug
