### ISSUE TITLE
categories and products do not appear or link

### ISSUE THREAD

**Issue by harutokawasaki** [opencart/opencart#3145]
when you create a category, and you can not create a link with the product, new products can not be bound by that link does not appear in the catergory, example:
1. Create  5 category
2. create a product and link 
3. cant make a link, because dont exist the link in the product edit.
![linked](https://cloud.githubusercontent.com/assets/13092444/8399665/4523b028-1dd8-11e5-80b2-9a43a719c775.png)

**Comment by danielkerr** [comment]
use the forum not the developer github as this is not a Q&A
