### ISSUE TITLE
4 products after the system is broken

### ISSUE THREAD

**Issue by harutokawasaki** [opencart/opencart#3146]
the problem occurs when you create more than 4 products, the link to the category appears, but when you look at the page, the product was not linked, it appears 0 eventhough it is all like other products.

![linked2](https://cloud.githubusercontent.com/assets/13092444/8399702/f5920a90-1dd8-11e5-9877-2f138369ba44.png)

**Comment by danielkerr** [comment]
check product status, make sure you have added the product to the store.
