### ISSUE TITLE
New Template Engine for Opencart 3

### ISSUE THREAD

**Issue by vanderson139** [opencart/opencart#3151]
Hello everyone!
I've made an OCMOD that implements Twig Template Engine on Opencart 2 with exclusive functions and filters. It made the workflow of template development so much easier that I hope you think about using something like it on Opencart 3 version as a core template engine. It's safer and faster.

**Comment by mhcwebdesign** [comment]
This is for reporting OpenCart bugs only, use the OpenCart forum for your announcements!

**Comment by vanderson139** [comment]
Ok
