### ISSUE TITLE
Error in comment of Product

### ISSUE THREAD

**Issue by eullercristian** [opencart/opencart#3152]
By posting a comment on the product page , the form does not display the confirmation, only displays if a field is not filled .

**Comment by mhcwebdesign** [comment]
Please be more specific, otherwise nobody can reproduce your error.

**Comment by eullercristian** [comment]
This error was solved?

**Comment by mhcwebdesign** [comment]
Not necessarily, your problem description was so vague, my guess is Daniel just closed it.
