### ISSUE TITLE
Unable to modify orders in latest Version 2.0.3.2_rc

### ISSUE THREAD

**Issue by ravdeepsingh22** [opencart/opencart#3153]
ERROR 
 Warning: No match for Username and/or Password. (Only When Editing Orders)
 Warning: You do not have permission to access the API! 
Please Note I have added api 
created new user and tried
Same problem always 

 Warning: You do not have permission to access the API!

**Comment by niyak2** [comment]
Your server issue

**Comment by iSaulius** [comment]
niyak2,  what's server issue?
i have same problems after update or just with new fresh install...
