### ISSUE TITLE
Category -> Data -> Filters autofill show just some filters, not all

### ISSUE THREAD

**Issue by alkulsv** [opencart/opencart#3154]
Hello!

  I use OpenCart Version 2.0.3.1 (rs.1).

  Have the problem in Category -> Data -> Filters. Then I choice autofil they show just some filters (really it much more). So need to enter filters manually. How to show all filters then I press autofil button?

print screen: http://i.imgur.com/wy0HzWD.png

   Thank you

**Comment by niyak2** [comment]
Enter the filter value ,it will show most used fiters all the time
