### ISSUE TITLE
"Notify Customer" box in History tab on Order screen not working properly

### ISSUE THREAD

**Issue by DSTAngieB** [opencart/opencart#3158]
When you go to the History tab in a customer's order and change the STATUS of the order, it automatically sends an e-mail notifying the customer even though the "Notify Customer" button is NOT checked! 

THIS IS A BUG!!

There are INTERNAL statuses that I have within my company that my customer needs to know nothing about (e.g. when an order moves from pre-production to production or packaging to shipped). It is not always necessary to notify the customer about when their order has moved from one department to the next internally and thus why we always leave the "NOTIFY CUSTOMER" box unchecked. But unfortunately, this 2.0.3) version of OpenCart will send an e-mail to the customer regardless of what you say. 

What is the purpose of having a notify customer button if it always is going to default to being ON??

Please fix this in the next release!

**Comment by danielkerr** [comment]
it was done so the customer can always see the progress of their order. the notify just notifys when comments have been added. 

It can be changed.

**Comment by iSaulius** [comment]
Daniel, I agree with DSTAngieB 100%, my clients asking do not send too many messages like a spam! Please, add additional check field.

**Comment by DSTAngieB** [comment]
If that is the case, Daniel, I ask again what is the purpose of the NOTIFY CUSTOMER button??
Nope!

This is a bug. The code is broken.

**Comment by stockmaster** [comment]
This changed from 2.0.1 to 2.0.2 if i recall correctly. On 2.0.2 the customer would recieve an update ONLY if the check box was actually checked. Not sure if it was reverted back to 2.0.3.

I tested this extensivly.

**Comment by beifloyd** [comment]
it's quite invasive to send out emails on every single change in the status order. 
I can think of  at least 2 points that leave me with doubt about this:
1. Responsibility on how the store is run must be ultimately with the store owner. He has to have the authority to decide on the behavior of the script and take responsibility if customers are not updated etc etc. 
2-  I suppose all store owners want to offer the best service possible to their customers and that OFTEN means slightly different procedures for some customers. What works for one (send out emails on every update of the order) does not work for everyone.

Finally, would it be possible to add a switch (yes/no) in the settings options screen for emails to be sent out automatically every time order is updated and edited.
Yes = current behavior
No = as it was in 1.5.x 
A  Final note about editing orders. While It's not a good habit do edit orders especially if you have been paid and editing the order means changing the total of the invoice. The feature is very handy to add a note/comment or to change/amend  the delivery address after a quick chat with your customer. Sending out an new email every time the order has been edited has resulted only in more confusion so far.

**Comment by danielkerr** [comment]
I will change it before the next release. need to get the order editor working again

**Comment by micrdy** [comment]
Quick fix for now: 
catalog/model/checkout/order.php

Change line 127 to:
if($notify){
    $mail->send();
}

**Comment by peszo** [comment]
@micrdy simple but perfect! Thanks

**Comment by beifloyd** [comment]
line 827.  is not correct for OC2.0.3.1 
maybe line 850? 
https://github.com/opencart/opencart/blob/master/upload/catalog/model/checkout/order.php#L850

**Comment by micrdy** [comment]
Yeah. In OC2.0.3.1 it´s line 850

**Comment by gob33** [comment]
I totally agree: notification shouldnt be done for internal notes of the merchant.
Furthermore, you are breaking behaviour of some extensions using this checkbox for sending emails.

**Comment by danielkerr** [comment]
@DSTAngieB  its not a bug dip shit its how you think some thing should work!

**Comment by DSTAngieB** [comment]
WHAAAAAAAAT??? What's with all the name calling?? WTH?!! 
RUDE!

**Comment by DSTAngieB** [comment]
THANK YOU @micrdy!! I appreciate your fix.
