### ISSUE TITLE
OC 2.0.3.1 does not diminishing stock at all

### ISSUE THREAD

**Issue by alexfarias** [opencart/opencart#3159]
When the client makes a purchase, the item does not come out of the stock. All the settings are correct. Automatic write-off of inventory and not allow purchases without stock. The only thing that works is returns, which ends up being odd because for example; if the customer buys an item that has 6 units in stock, this stock should reduce to 5 units, but it does not happen. Even the customer confirming the purchase the stock remains at 6, and if by chance he returns the item inventory increases to 7 units.
So I went in the admin panel I configured all available options to order situations to see if the stock diminished, but nothing happened, on the contrary, some items increase the stock. Are they; Reversal Canceled and Refunded.
Anyone know what can be done to fix this, because this is a very serious problem!
thanks

**Comment by mhcwebdesign** [comment]
CURL loopback issue here which was discussed elsewhere, and for which Daniel was working on a solution?

**Comment by danielkerr** [comment]
did you set product > stock deduct

**Comment by alexfarias** [comment]
yep, i did!

**Comment by danielkerr** [comment]
no one else is having this issue. ask in the forums for help.

**Comment by danielkerr** [comment]
i think you are not using the order info to update the order status.
