### ISSUE TITLE
How to new field at oc_order table in admin

### ISSUE THREAD

**Issue by minhquan4080** [opencart/opencart#3160]
I add new field tracking_id at oc_order table. And i click button save look : 
form data :
shipping_method:
payment_method:cod
order_status_id:3
comment:
affiliate_id:0
tracking_id:0366633918

But, i don't know how to save tracking_id . What is controller processing save it ?

**Comment by mhcwebdesign** [comment]
This is only for reporting bugs, use the OpenCart forum for support queries.
