### ISSUE TITLE
Order editing

### ISSUE THREAD

**Issue by stlntdot** [opencart/opencart#3163]
If I am in order view or edit mode and try to change anything I get this error:

![error](https://cloud.githubusercontent.com/assets/13181858/8509964/2595908e-2295-11e5-8f13-62f07d4a7e6e.jpg)

**Comment by stlntdot** [comment]
How do you close  ticket with ZERO explanation? ?

**Comment by milimar** [comment]
@stlntdot , there is a known bug - loopback issue, Daniel is being trying to resolve it for a while. 

I think that your issue is about that.
