### ISSUE TITLE
MaxMaind error HTTP 500 and Opder crash OC 2.03.1, 2.0.3.2_rc

### ISSUE THREAD

**Issue by Virik1** [opencart/opencart#3166]
Hello!
Orders do not register in the system, when I turn on MaxMaind. Adding to this, when I make a payment via PayPal  Express Checkout I get the error HTTP 500.
When I make a payment via PayPal Payments Standard, system sends me to the page /index.php?route=checkout%2fsuccess, but the order is not registered in the system.
I checked on clear settings OpenCart 2.03.1, 2.0.3.2_rc.
The error appeared after redirect from OC 2.0.2.1 to 2.03.1.
Screenshots are added.
I can give an access to  an expert for testing this problem

 
![screenshot](https://cloud.githubusercontent.com/assets/13176979/8528427/a232909c-241b-11e5-8e85-e6212602bdba.png)
![screenshot2](https://cloud.githubusercontent.com/assets/13176979/8528435/a7b089b6-241b-11e5-9bbe-26fcb96d9e38.png)

**Comment by danielkerr** [comment]
email my staff

**Comment by Virik1** [comment]
Where to write? Here?
http://www.opencart.com/index.php?route=support/contact

2015-07-06 21:16 GMT+03:00 Daniel Kerr <notifications@github.com>:

> email my staff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/3166#issuecomment-118943633>.
>



-- 
Best regards,Vereschagin Vitaliy
