### ISSUE TITLE
Pay with Amazon tax not being calculated

### ISSUE THREAD

**Issue by dbrent-amazon** [opencart/opencart#3167]
When using Pay with Amazon tax is not displayed/calculated on the confirmation page.

Repro: Add a taxable item to your cart, checkout, click Pay with Amazon. You will see on the confirmation page that it does not include tax.

**Comment by chris-wm** [comment]
@dbrent-amazon Hi, I believe this is the same as an issue raised by the Amazon testing team, can you try replacing this file catalog\controller\payment\amazon_login_pay.php with the the following https://drive.google.com/file/d/0B0thHgBjXmj_OGZhUklKMHBoaFU/view?usp=sharing,  and let me know if it resolves the problem for you,
regards
