### ISSUE TITLE
Product option selection gets erased from time to time

### ISSUE THREAD

**Issue by Markovnin** [opencart/opencart#3168]
I have a weird problem: for some products, required option selection don't save from time to time. In one order, some products have selection, others don't. I can't find any way to reproduce the bug, and there's no specific browsers. It just happens accidentally. 

Opencart version: 1.5.4.1

**Comment by danielkerr** [comment]
this is an old issue. if you have many options on a product. i think its fixed in after your current version.

**Comment by Markovnin** [comment]
@danielkerr I have one option per product. What version is it fixed in? Can you link to pull request please?
