### ISSUE TITLE
Modification refresh causes maintenance mode off with no on

### ISSUE THREAD

**Issue by nageshshetty** [opencart/opencart#3170]
it seems when you refresh the modification settings, it goes to maintenance mode but never changes it back. on further checking, it seems the org_maintenance variable gets the value of config setting and then again below checks the same setting savd in the memory instead of the changed one.. this is causing the issue. also the setting values are not boolean so setting value as false wont  put 0 . this is again a bug..

Hope open cart looks into this

**Comment by danielkerr** [comment]
this is fixed in the master branch
