### ISSUE TITLE
Integrate Multimerch by default in opencart

### ISSUE THREAD

**Issue by ravdeepsingh22** [opencart/opencart#3172]
Multimerch is a great extension that makes opencart a heaven 
I suggest to make multimerch a default module in opencart with some additional features
I also suggest to make a community forum for opencart using http://www.discourse.org/
This is an awesome forum opensource script 
Lets Make opencart number one in market 
I also suggest to create a Restful api for opencart that will allow to create various apps 
Thanks 
Ravdeep

**Comment by milimar** [comment]
Suggestions should be welcomed, but you shouldn't suggest things at the place for bug reporting. 

@ravdeepsingh22 , I suggest you close this ticket, and post your suggestion here: 

http://opencart.uservoice.com/forums/52387-general
