### ISSUE TITLE
install file looking for "storeage"

### ISSUE THREAD

**Issue by welov3** [opencart/opencart#3175]
hello, i find that the install file is looking for right permissions on 
~/system//storeage/cache/
~/system/storeage/logs/
~/system/storeage/download/
~/system/storeage/upload/
~/system/storeage/modification/
how i can do a manual fix?
if i do a manual fix, will not mess up the system later?
thanks

**Comment by welov3** [comment]
![installationstep2](https://cloud.githubusercontent.com/assets/13299559/8637838/c961cb9a-28a5-11e5-9098-21f0cbff1239.jpg)

**Comment by welov3** [comment]
![installationstep2](https://cloud.githubusercontent.com/assets/13299559/8637841/f0b3d95e-28a5-11e5-9fac-cb64ebf08d1f.jpg)

**Comment by welov3** [comment]
i submit fix, #3176 but it still doesnt let me move forward as it gives error messages.
the "storeage" misspell might be somewhere else too

**Comment by danielkerr** [comment]
credit card scammers are not welcome here!

**Comment by welov3** [comment]
???

**Comment by danielkerr** [comment]
i did not post that. maybe some one is in my account
