### ISSUE TITLE
Opencart Smtp Mail not Sending To hotmail Account

### ISSUE THREAD

**Issue by savoo** [opencart/opencart#3177]
Opencart 1.5.6

Smtp mail Sending to other emails like gmail.

But not sending to Hotmail account.

Please can you figure out this problem.

**Comment by savoo** [comment]
I found this topics on http://forum.opencart.com/viewtopic.php?f=20&t=117816

**Comment by milimar** [comment]
I think this is a place for OC 2.x only, not sure if you will receive any answer here about older versions of OC.

**Comment by danielkerr** [comment]
replacing the mail class with the latest version should work.
