### ISSUE TITLE
Product options weight wrong on shipping list - only shows base product weight

### ISSUE THREAD

**Issue by sculptex** [opencart/opencart#3178]
When products with options that have weights are bought, the shipping list only shows the base product weight and ignores the options.
![selection_002](https://cloud.githubusercontent.com/assets/12629448/8640775/552027a2-28fc-11e5-87f6-85761831ae05.png)
^ (base) product weight
![selection_003](https://cloud.githubusercontent.com/assets/12629448/8640776/5aa1845a-28fc-11e5-8555-a66393165e3e.png)
^ option weight
![selection_004](https://cloud.githubusercontent.com/assets/12629448/8640777/5e7aa2fa-28fc-11e5-9a8e-5b34c402faf7.png)
^ shows correct in cart
![selection_005](https://cloud.githubusercontent.com/assets/12629448/8640778/6390fdb6-28fc-11e5-86ec-f69696e90050.png)
^ only shows product weight not option in shipping list

**Comment by danielkerr** [comment]
reported 2x
