### ISSUE TITLE
ORDER STATUS ERRORS SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data 

### ISSUE THREAD

**Issue by iamtechjunkie1** [opencart/opencart#3182]
when i change my order status to denied or completed or any 1 of ther other.
the error occurs.

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data  OK  <b>Notice</b>: Undefined variable: json in <b>/home/shopi17/public_html/admin/controller/sale/order.php</b> on line <b>2221</b>

Plz guide me

**Comment by milimar** [comment]
Firstly, here it is difficult that someone will guide you to resolve your problems because here we only report bugs.
Secondly, no one can help you if you don't leave sufficient information, like for ex. which version of OC you are talking about?
