### ISSUE TITLE
column_left.tpl+column_right.tpl

### ISSUE THREAD

**Issue by dtjones** [opencart/opencart#3183]
`<column id="column-right" class="col-sm-3 hidden-xs"></column> `
`<column id="column-left" class="col-sm-3 hidden-xs"></column>` 

Did you mean `<aside>`  ??

**Comment by danielkerr** [comment]
or section

**Comment by dtjones** [comment]
have you thought about having just the one controller for all positions ? 


		$data['column_left'] = $this->load->controller('common/position','column_left');
		$data['column_right'] = $this->load->controller('common/position','column_right');
		$data['content_top'] = $this->load->controller('common/position','content_top');
		$data['content_bottom'] = $this->load->controller('common/position','content_bottom');


//common/position.php 

	<?php
	class ControllerCommonPosition extends Controller {

		public function index($position = 'content_top') {
			$this->load->model('design/layout');

			if (isset($this->request->get['route'])) {
				$route = (string)$this->request->get['route'];
			} else {
				$route = 'common/home';
			}

			$layout_id = 0;

			if ($route == 'product/category' && isset($this->request->get['path'])) {
				$this->load->model('catalog/category');
				
				$path = explode('_', (string)$this->request->get['path']);

				$layout_id = $this->model_catalog_category->getCategoryLayoutId(end($path));
			}

			if ($route == 'product/product' && isset($this->request->get['product_id'])) {
				$this->load->model('catalog/product');
				
				$layout_id = $this->model_catalog_product->getProductLayoutId($this->request->get['product_id']);
			}

			if ($route == 'information/information' && isset($this->request->get['information_id'])) {
				$this->load->model('catalog/information');
				
				$layout_id = $this->model_catalog_information->getInformationLayoutId($this->request->get['information_id']);
			}

			if (!$layout_id) {
				$layout_id = $this->model_design_layout->getLayout($route);
			}

			if (!$layout_id) {
				$layout_id = $this->config->get('config_layout_id');
			}
			
			$this->load->model('extension/module');
			
			$data['modules'] = array();

			$modules = $this->model_design_layout->getLayoutModules($layout_id, $position);

			foreach ($modules as $module) {
				$part = explode('.', $module['code']);
				
				if (isset($part[0]) && $this->config->get($part[0] . '_status')) {
					$data['modules'][] = $this->load->controller('module/' . $part[0]);
				}
							
				if (isset($part[1])) {
					$setting_info = $this->model_extension_module->getModule($part[1]);
					
					if ($setting_info && $setting_info['status']) {
						$data['modules'][] = $this->load->controller('module/' . $part[0], $setting_info);
					}
				}
			}

			if (file_exists(DIR_TEMPLATE . $this->config->get('config_template') . '/template/common/' . $position . '.tpl')) {
				return $this->load->view($this->config->get('config_template') . '/template/common/' . $position . '.tpl', $data);
			} else {
				return $this->load->view('default/template/common/' . $position . '.tpl', $data);
			}
		}
	}

simple, that's the full controller now the other four can be deleted
