### ISSUE TITLE
Order admin page error

### ISSUE THREAD

**Issue by haipham** [opencart/opencart#3186]
Fresh install Opencart from Github, access Admin > Sales > Order, show blank page. 
And in Dashboard, click view action "Latest Orders",  show below popup error:

SyntaxError: JSON Parse error: Unrecognized token '<'
OK
<b>1024</b>: Notice in <b>/.../www/opencart/upload/system/library/db/mysqli.php</b> on line <b>41</b><b>8</b>: Notice in <b>/.../www/opencart/upload/index.php</b> on line <b>134</b>{"success":"Success: API session successfully started!","token":"EHrg5DFIuyopClTOAs3WSF4wDmo4rjuMs7XnL6GeIKInJyUguZPtWgOfpl9GxuFi"}

Please fix this.

**Comment by danielkerr** [comment]
maybe you just read the commit comments
