### ISSUE TITLE
SyntaxError: JSON Parse error: Unrecognized token

### ISSUE THREAD

**Issue by haipham** [opencart/opencart#3189]
With latest commit, Admin > Sales > Order, getting below error:

>SyntaxError: JSON Parse error: Unrecognized token '<'
>OK
><br />
><b>Fatal error</b>:  Call to undefined method Session::getName() in ><b>/.../www/opencart/upload/catalog/controller/api/login.php</b> on line <b>41</b><br />

Thanks.

**Comment by stockmaster** [comment]
What version of OC?
SSL?

**Comment by haipham** [comment]
Opencart v2.0.3.2_rc, none SSL.

**Comment by werim** [comment]
got the same issue 
"SyntaxError: JSON Parse error: Unrecognized token '<'
OK
<br />
<b>Fatal error</b>:  Call to a member function check() on a non-object in <b>/home/public_html/catalog/model/checkout/order.php</b> on line <b>267</b><br />
" 
version 2.3.0.2. Any help would be appreciated
