### ISSUE TITLE
Improving getTotalProducts() and maybe other queries

### ISSUE THREAD

**Issue by JeramyNS** [opencart/opencart#3198]
Hey,

We have found from the 2000+ OpenCart sites we manage that the getTotalProducts function can sometimes cause mysql to freeze up on sites with a large amount of traffic.

After playing around a bit, we think that it's actually better to cache the results of the query.
As it's such a busy function and the query chances a lot depending on what data is passed, choosing a cache name was the first obstacle, but we decided to use md5() on the $sql to create a unique name.

Anyway, here is example of the solution we are currently using...

File: /catalog/model/catalog/product.php
Function: getTotalProducts
At the end of the function replace:
```
$query = $this->db->query($sql);
return $query->row['total'];
```
With:
```
$sql_name = md5($sql);

$final_total = $this->cache->get('product.count.' . $sql_name);
if(!$final_total){
    $query = $this->db->query($sql);
    $final_total = $query->row['total'];
    $this->cache->set('product.count.' . $sql_name, $final_total);
}

return $final_total;
```

Now the problem with this solution is that all of the php code that creates the query has to be run before you load the cached file.
One possible solution may be to convert the $data array into a string (eg. json_encode) and then do an md5 on the json_encode to get a unique name we can use in the cache file.

This idea of using md5() to create a unique cache name also opens up the opportunity to cache other functions that can cause a bit of strain on MySql.

Anyway, I'm keen to hear other people's thoughts and if you can think of anywhere else this may be useful; as it has been a huge problem for some of our bigger clients in the past.

Jeramy Simpson - from MyWork

**Comment by GomDani** [comment]
I  cached results in the controller depending on the variable passed to the function.

    $total = $this->cache->get('product.count.' . (int)$child['category_id'] . '.filter_sub_category.' . 1);

    if (!$total) {
        $filter_data = array('filter_category_id' => $child['category_id'], 'filter_sub_category' => true);

        $total = $this->model_catalog_product->getTotalProducts($filter_data);

        $this->cache->set('product.count.' . (int)$child['category_id'] . '.filter_sub_category.' . 1, $total );
    }

**Comment by veksen** [comment]
Yes, you're caching the query, but when do you invalidate it? Did I miss something?

**Comment by garudacrafts** [comment]
Yeah, the cache should be cleared whenever the data set changes. So $this->cache->delete('product'); needs to be included in addProduct, editProduct, etc.

**Comment by bmett** [comment]
```
$this->cache->delete('product');
```
is already part of the addProduct, editProduct, deleteProduct, etc. functions.

Therefore the caching should work fine.

**Comment by danielkerr** [comment]
what about switching the product table to inodb?

Im closing this because using file caching is not that great for high end sites.
