### ISSUE TITLE
All fields Blank caused by json_decode?

### ISSUE THREAD

**Issue by dtjones** [opencart/opencart#3199]
https://github.com/opencart/opencart/commit/b445fa87a4d260e46bee83e286811862e53a1e1e and https://github.com/opencart/opencart/commit/141de8ac42ee10851d9d8736462e5e1418569be5

what happends when people upgrade and try to json_decode serialised data ??? all forms that are loaded are going to be blank. 

i think all json_decode/unserialize should happen within the model, it would be a lot cleaner. 

 setting/setting.php

editSetting()

    .e.g  `value` = '" . $this->db->escape(json_encode($value)) . "', serialized = '2'");

getSetting()

    foreach ($query->rows as $result) {

        if (!$result['serialized']) {

            $setting_data[$result['key']] = $result['value'];

        } else if($result['serialized'] == 2) {

            $setting_data[$result['key']] = json_decode($result['value'], true);

        } else {
            // old saved data 
            $setting_data[$result['key']] = unserialize($result['value']);
        }
    }

and in some cases  json_decodes need so be checked like so . 

    $permissions = json_decode($user_group_query->row['permission'], true);
    if(json_last_error() !== JSON_ERROR_NONE){
        $permissions = unserialize($user_group_query->row['permission']); 
    }

**Comment by GomDani** [comment]
Or make an upgrade script, which get serialized data and convert it in json_encode and then save it in db.

**Comment by dtjones** [comment]
I feel I should have checked the upgrade script before writing this. .

**Comment by danielkerr** [comment]
yes going to add a conversion system in the upgrade script

**Comment by danielkerr** [comment]
your suggest is good though

**Comment by danielkerr** [comment]
ok last commit shoud have fixed this

**Comment by danielkerr** [comment]
forogt user permissions. will fix tomrrow

**Comment by GomDani** [comment]
Customer cart have two serialize. Missing something like:

    $json_encode_cart = array();

    $cart = unserialize($customer['cart']);

    foreach ($cart as $key => $quantity) {
	    $product = unserialize(base64_decode($key));
				
	    $key = base64_encode(json_encode($product));
				
	    $json_encode_cart[$key] = $quantity;
    }

    $cart = json_encode($json_encode_cart);
