### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Dwebtron** [opencart/opencart#3200]
I have a brand-new install of the latest version of opencart, and I can't log in. My symptoms are identical (from what I can tell) to this issue: 

https://github.com/opencart/opencart/issues/729

Is there something I can do? I've looked for the session_start(); code in the system/library/session.php file and it wasn't there... I'm brand new to open cart and don't know where to start.

**Comment by danielkerr** [comment]
yes, im working on it. install the stable release from opncart.com.

**Comment by danielkerr** [comment]
closing this as i any session problems should be fixed now

**Comment by Dwebtron** [comment]
I know it's been a little while, but thanks for fixing and addressing this so quickly. :)
