### ISSUE TITLE
Catalog > Options : Page Not Found

### ISSUE THREAD

**Issue by saiddrouri** [opencart/opencart#3203]
Hi, 

I just installed Open cart Version 2.0.3.1 and I coulnd't access the options, I get Page Not Found error...

Thanks for your help.

**Comment by milimar** [comment]
Hi, I don't think this is a bug, I have been using OC 2.0.3.1 for a while and no problems with the options at all.

**Comment by mhcwebdesign** [comment]
Please use the OpenCart forum for support requests, this is only for bug reports.

**Comment by saiddrouri** [comment]
I continued the customization of the app and surprisingly it got fixed "by itself" I think it might be because of text differences between win and Unix ?

Anyways, glad to have access to the options and moving on with the project 

It might come back in the future as a bug as it's not a confit/deployment issue...

Kind regards,
Saïd.
