### ISSUE TITLE
Order Editing Stock Quantity Issue.

### ISSUE THREAD

**Issue by ubifWebNinja** [opencart/opencart#3204]
When you edit an existing order in admin for items that have already been removed from inventory but does not have quantities on hand greater than the items in the order you cannot save the order again after adding new items. This is a huge issue for stores that have huge volumes of orders where inventory levels fluctuate a lot but items need to be added after the user checks out. If the items in my order have already been removed from inventory these items should not flag the stock level warning, only new items being added to the order should do that. 

Let me explain it like this:
Currently if someone submits an order for 5 items then later calls in and needs to add a 6th, if the first 5 items have sold out but the 6th hasn't by the time I have to add the 6th item I cannot do it until the other 5 items are back in stock.

What is the thought process behind this?

The entire edit order process needs to be re-done now because it doesn't logically make sense or work  the way it should. I could always turn off the stock check at checkout in settings but that wouldn't be smart would it ;)

**Comment by danielkerr** [comment]
what about the allow checkout if products not instock setting?

**Comment by ubifWebNinja** [comment]
Unless you had a very extensive back ordering system it doesn't make sense to do that and would cause a huge headache with keeping up with our current inventory that is in stock. Our company uses open cart for our distribution center so when something is out it needs to be at 0 and not a negative number other wise we would have a difficult time assessing our inventory properly.

Here is another simple example. Lets say product 1203 has 50 in stock, someone orders 45 of that product then when editing an order they need to add 3 more of the same product when checking if its in stock since 45 have already been remove the system should only check if 3 is in stock from the remaining 5 left and should be checking 48 against 5 because 45 have already been ordered and removed from inventory.

Since submitting this issue I've completely re-wrote the process for editing orders so that orders are no longer voided but instead quantities are updated instead and for each item the quantity that has already been removed is taken into account when adding or removing or adjusting items in the order that way when trying to save it doesn't always check whats in your cart against whats in stock it only checks the new difference. I would have rather not had to change so much of the core system to do this but it was necessary based on our needs. Given the way it currently works I feel that you should look into possibly re-doing your editing process that same way as it just makes more sense for businesses such as ours but I think overall everyone that uses opencart would benefit as well. i've also adding better quantity adjustment tracking and its now a tab under the products form and also in the order history so we can actually see every adjustment that was made, from where and by who.

Its just logical that it should work the way i'm describing and not how it currently does. I've been using opencart since version 1.2 and 2.3.1 is a huge improvement over the years but I just couldn't use it without re-doing the editing process because there was no way it could have worked for us that way. It might be ok for smaller companies that don't rely on having accurate inventory but for us we do around 20 million a year in sales so it's vital our inventory is accurately reflected.

**Comment by danielkerr** [comment]
ok just tested this.there is one way of by passing this which would be to remove the item in the cart and re add it problem with this is if there are any uploads.

going to try to add a quantity field.
