### ISSUE TITLE
Reset google recaptcha after submit product review

### ISSUE THREAD

**Issue by nuke123** [opencart/opencart#3205]
After submitting a review the form resets everything apart from the captcha. 

Simple fix by adding to product.tpl:
```javascript
if (json['success']) {
	$('#review').after('<div class="alert alert-success"><i class="fa fa-check-circle"></i> ' + json['success'] + '</div>');

	$('input[name=\'name\']').val('');
	$('textarea[name=\'text\']').val('');
	$('input[name=\'rating\']:checked').prop('checked', false);
	
	if (typeof grecaptcha != "undefined") {
		grecaptcha.reset();
	}
```

It works ok for me but apparently your supposed to pass the key
https://developers.google.com/recaptcha/docs/display#js_api

**Comment by danielkerr** [comment]
closing because going to change the google captcha back to the default one
