### ISSUE TITLE
OC 2.0.3.1 modification extension - brace expansion of pathnames does not work

### ISSUE THREAD

**Issue by TomekWW** [opencart/opencart#3206]
Modifications with paths containing braces such as `<file path="catalog/language/english/account/{register,password}.php">...</file>` are not recognized in OC 2.0.3.1.
It worked in OC 2.0.1.1.

**Comment by elcopdoo** [comment]
Poštovani,

trenutno sam van ureda.
Vraćam se 10.08.

I am currently out of the office.
I'll be back 10.08.

Za sve hitne upite molim vas da kontaktirate
kolege u uredu:
Renato Novak: (040)804-083
Milivoj Balić: (040)804-087
Spomenka Patafta: (040)804-082

Lijep pozdrav,
Denis Dobranić
Elcop d.o.o.

**Comment by danielkerr** [comment]
ok braces are back. multple paths now use | to spit them up.

**Comment by nuke123** [comment]
Why change to a pipe when it currently works with commar? This just creates extra work for extension developers with another change to ocmod syntax
