### ISSUE TITLE
Wordlpay Business Gateway Module replaced with Worldpay Online module

### ISSUE THREAD

**Issue by ajfwebdesign** [opencart/opencart#3207]
Hi,

In the latest version of Opencart you have replaced the original Worldpay payment module with the WORLDPAY ONLIE payments module.

This means that anyone with a Worldpay Business Gateway account won't be able to upgrade to the latest version of opencart and still use the Worldpay option as I have found out when trying to upgrade multiple sites.

Can you please please please please please re-integrate the original Worldpay module even if it is along side the new one?

Thanks in advance 
Andrew

**Comment by Bodge-IT** [comment]
@ajfwebdesign I pointed this out to them on the actual pull request, seemed they ignored it and released anyway!

Just in case Andrew's point isn't clear: You no longer offer the commonly accepted Worldpay offsite payment process as a payment gateway in Opencart.

**Comment by ajfwebdesign** [comment]
@Bodge-IT Hi Gary, thanks for adding that comment, and adding a much clearer explanation for me, much appreciated.

I am coming across more and more people that are having the exact same issues as I am, I can't see clients willing to switch out a Business Gateway account that charges around 1.2% +15p per transaction for an account that charges 2.75% +20p per transaction.

**Comment by Bodge-IT** [comment]
@ajfwebdesign The original pull request was to make Worldpay gateway work with the 'Recurring Payments' feauture and was something I was desperate for.  @chris-wm must have got somewhat confused but @jamesallsup committed it. See here: https://github.com/opencart/opencart/pull/2755
AFAIK only massive corporates use the Worldpay Clearwater/Corporate accounts and I doubt they're using OpenCart.

**Comment by jamesallsup** [comment]
We are currently working with WP to have the old module added back for the next release

**Comment by Bodge-IT** [comment]
Thanks @jamesallsup , will this new module work with recurring payments? And will I be apply it as backportable patch to 2.0.1.1?  I'm unable to move forward with OC versions until Mijosoft guys decide to upgrade.

**Comment by jamesallsup** [comment]
There won't be any updates to the module, it will just be re-added to it's original state but probably renamed so it doesn't conflict with the recent addition.

**Comment by Bodge-IT** [comment]
@jamesallsup weren't @chris-wm 's changes intended to bring WP PG inline with recurring payments?  Can't this be done to old module?

**Comment by ajfwebdesign** [comment]
That is great news @jamesallsup thanks for replying, do you have any idea when the next release will be happening?

Thanks
Andrew

**Comment by jamesallsup** [comment]
@Bodge-IT I will confirm with Chris, but believe that it was part of the whole update to the new platform.

@ajfwebdesign Daniel has been working on some bigger updates with the order editing and fraud system so these need to go through some testing first. It is likely a beta release of the next version will be done which takes some time to gather feedback and update any issues. I don't have a solid ETA on the next release but expect the beta in the coming weeks.

**Comment by Bodge-IT** [comment]
@jamesallsup thanks James.

**Comment by ajfwebdesign** [comment]
@jamesallsup Thanks for the update, I'll keep an eye out for the beta

**Comment by ajfwebdesign** [comment]
Hi @jamesallsup sorry to bother you, but just wanted to check that this is where I should keep an eye out for the beta release https://github.com/opencart/opencart/releases ?

**Comment by paulterry** [comment]
@jamesallsup any news on when the next release will be? I have a site waiting to go live and this is the only thing holding it back.
Does version 2.0.1.1 have the old WorldPay Extension? I may need to consider downgrading.

**Comment by ajfwebdesign** [comment]
@paulterry Versions 2.0.0.0 - 2.0.1.0 - 2.0.1.1 have the original Worldpay Business Gateway it's from version 2.0.2.0 that it change to the Worldpay ONLINE gateway. I've got 2 shops waiting to go live but need the original WP Gateway, @jamesallsup has said there should be a beta out shortly

**Comment by paulterry** [comment]
@ajfwebdesign Thanks.
If the new beta/release is due soon I may hold on, otherwise I'm downgrading. If anyone does know when this release will be then please share.

**Comment by ajfwebdesign** [comment]
hi @jamesallsup I understand you're busy, but just wondering is there any word on the new beta being released? Thanks

**Comment by paulterry** [comment]
For those that still need to use the old WorldPay gateway (like me), you may be interested to know you can take the code files for the WorldPay extension from an older version of opencart and implement them into a newer version without issue.
I have done this and it works, test and production payments are working absolutely fine.

**Comment by ajfwebdesign** [comment]
Hi @paulterry that sounds promising, so by using the old files does this replace the new WorldPay gateway completely? Will I need to replace the files with future upgrades? And if you have time....which files need to be used/swapped/replaced?

Thanks in advance
Andrew

**Comment by paulterry** [comment]
Hi @ajfwebdesign
It does replace the new WorldPay gateway, but that was fine for me. I'm sure with a bit of poking around I could have renamed the new/old one and have them both running, but that wasn't necessary for me.

I moved up all the 'new' code files into a folder within their respective directory i.e.
`catalog/controller/payment/worldpay.php > catalog/controller/payment/`**backup**`/worldpay.php `
`catalog/model/payment/worldpay.php > catalog/model/payment/`**backup**`/worldpay.php`
...etc.

And then copied the files from the 2.0.1.1 version of OpenCart to their respective directories.

Full file list:
`catalog/controller/payment/worldpay.php`
`catalog/model/payment/worldpay.php`
`catalog/language/english/payment/worldpay.php`
`catalog/view/theme/default/payment/worldpay.tpl`
`catalog/view/theme/default/payment/worldpay_failure.tpl`
`catalog/view/theme/default/payment/worldpay_success.tpl`
and if you want your own themed worldpay pages, copy from the default them to your theme
`catalog/view/theme/`*THEMENAME*`/payment/worldpay.tpl`
`catalog/view/theme/`*THEMENAME*`/payment/worldpay_failure.tpl`
`catalog/view/theme/`*THEMENAME*`/payment/worldpay_success.tpl`

`admin/controller/payment/worldpay.php`
`admin/language/english/payment/worldpay.php`
`admin\view\template\payment\worldpay.tpl`

NOTE: there is **not** a `admin/`**model**`/payment/worldpay.php` file in the old version, so make sure you move the 'new' version's files out of that directory

I hope this helps

Thanks

**Comment by ajfwebdesign** [comment]
Hi @paulterry Thanks for taking the time to put all the info together, much appreciated. Unfortunately doesn't seem to be working for me. I've moved/replaced the files but just getting an error when trying to go through the checkout. I'm going to try it out on another of the shops waiting to go live and see if there's any luck there.

Any word on the new release @jamesallsup ? Thanks in advance

**Comment by ajfwebdesign** [comment]
Hi again @paulterry so I tried this method with another shop and it appears to work perfectly! I'll try and re-replace the files in the other shop and see how it goes. Thanks again for your help

**Comment by danielkerr** [comment]
IM closing this. I have been to the worldpay web site and it looks like they have removed documentation for the old way of integrating worldpay.
