### ISSUE TITLE
cart.php All the option quantities are zero and are required.

### ISSUE THREAD

**Issue by Richione** [opencart/opencart#3211]
Hi, sorry for english.
If all the option quantities are zero and are required and checkout settings is yes, there is no way to make an order, but that make no sense, because: My stock checkout settings is  - Yes (It should allow people make an order while products are out of stock anyway)
Due to required setting are all the options invisible and there is nothing to select. So, there is now way how add something to cart.

Something wrong is with that code I guess:

$product_options = $this->model_catalog_product->getProductOptions($this->request->post['product_id']);

         foreach ($product_options as $product_option) {
            if ($product_option['required'] && empty($option[$product_option['product_option_id']])) {
               $json['error']['option'][$product_option['product_option_id']] = sprintf($this->language->get('error_required'), $product_option['name']);
            }
         }

**Comment by danielkerr** [comment]
how is this a bug? set the option quantity to 1 and subtract stock to no.

**Comment by Richione** [comment]
O.K. That's possible of course, but you need constantly control option quantities manually. Back and forth switch subtract to no and yes whether your goods is out of stock or not. That is not comfortable and doesn't make sense to me either. In this case checkout setting option - Yes is good for nothing.

**Comment by Richione** [comment]
The logic should be simple or I'm wrong?
If all the option quantities are 0, there is nothing to be required. That's what I'm trying to say. I'm talking about better logic of cart.php. that's all. Checkout setting is yes, just continue or something...
Of course, you can say, make your option of goods not required, but that is not way either, because If is merchandise in the stock, you simply need people to select.
Anyway.
Maybe it is not a bug, it all about comfort and user friendliness.
Thanks.
