### ISSUE TITLE
Notice: unserialize(): Error at offset

### ISSUE THREAD

**Issue by WTree** [opencart/opencart#3212]
I had a problem.In 2.0.3.1 for linux :
Notice: unserialize(): Error at offset 0 of 78 bytes in    public_html/catalog/model/extension/module.php on line 10

**Comment by naimbic** [comment]
Hello i had similar probleme, may it will help, and i hope opencart team will look to it...

anyway after miss up with ssl urls i got the same error but into index.php and admin/index.php
Solution:
i add this line before the VARIABLE that unserialize

$VARIABLE_MUST_CHANGE['value'] = preg_replace('!s:(\d+):"(.*?)";!e', "'s:'.strlen('$2').':\"$2\";'", $VARIABLE_MUST_CHANGE['value']);
$config->set($setting['key'], unserialize($setting['value']));

change VARIABLE_MUST_CHANGE to setting in my case

**Comment by danielkerr** [comment]
i ont know what you did to cause this but its unlikely it happens as default

**Comment by WTree** [comment]
he is  just that first install happen this problem

**Comment by eugeniots** [comment]
Estou com o mesmo erro e ainda sem solução. 

Add a $ VARIABLE_MUST_CHANGE ['valor'] = preg_replace ('! S: (\ d +): "(. *?)";! E', "'s:'. Strlen ('$ 2'). ':" $ 2 "; '", $ VARIABLE_MUST_CHANGE [' valor ']);  , mas o erro mudou para Parse error: syntax error, unexpected '$'
