### ISSUE TITLE
fopen problem can\t acces admin or website

### ISSUE THREAD

**Issue by Mewporg** [opencart/opencart#3217]
Hello,

afrer upgrade to 2.3.1 my website give this error on the website

 Warning: fopen(/home/******/public_html/system/logs/): failed to open stream: Is a directory in /home/*****/public_html/system/library/log.php on line 6
 Fatal error: Call to a member function get() on a non-object in /home/*****/public_html/index.php on line 97

and i can't access my admin panel

 Warning: fopen(/home/nasey/public_html/system/logs/): failed to open stream: Is a directory in /home/*****/public_html/system/library/log.php on line 6

I try to change per to 0777  755 to logs directory and not working too.

**Comment by danielkerr** [comment]
please dont post here. use the forums
