### ISSUE TITLE
Suggestion for change to config.php

### ISSUE THREAD

**Issue by billynoah** [opencart/opencart#3220]
I've been using the following structure for `config.php` and would like to submit the idea as a suggestion to be incorporated into the next release:

	// GLOBAL
	define('DOCROOT', '/path/to/docroot/');
	define('URL', '//example.com/');

	// HTTP
	define('HTTP_SERVER', 'http:' . URL);

	// HTTPS
	define('HTTPS_SERVER', 'http:' . URL);

	// DIR
	define('DIR_APPLICATION', DOCROOT . 'catalog/');
	define('DIR_SYSTEM', DOCROOT . 'system/');
	define('DIR_LANGUAGE', DOCROOT . 'catalog/language/');
	define('DIR_TEMPLATE', DOCROOT . 'catalog/view/theme/');
	define('DIR_CONFIG', DOCROOT . 'system/config/');
	define('DIR_IMAGE', DOCROOT . 'image/');
	define('DIR_CACHE', DOCROOT . 'system/cache/');
	define('DIR_DOWNLOAD', DOCROOT . 'system/download/');
	define('DIR_UPLOAD', DOCROOT . 'system/upload/');
	define('DIR_MODIFICATION', DOCROOT . 'system/modification/');
	define('DIR_LOGS', DOCROOT . 'system/logs/');

**BENEFITS:**
- Allows end user to update website document root path and url in only one place
- Allows programmatic access to the website docroot if needed.  For instance, if a developer uses a new directory called "resources" in their extension, they could simply refer to it as `DOCROOT . 'resources'` instead of needing to define a new global.
- The `URL` global allows programmatic ability to create protocol relative links where needed.

Thanks for your consideration.

**Comment by danielkerr** [comment]
sometimes the system and admin folders need to be moved out of the web folder.
