### ISSUE TITLE
missing class .product-layout in tpl modules

### ISSUE THREAD

**Issue by opencart-russia** [opencart/opencart#3224]
Hi. Why delete class product-layout ?? Now the modules are wrong again visible.
see https://github.com/opencart/opencart/commit/25498b58810ce8d1dfc2793d0a7c3e3cc9d2927a#diff-0ff8eccb3c6d4398ddc051f7f7cef247

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/issues/2886
