### ISSUE TITLE
opencart cart update problem 

### ISSUE THREAD

**Issue by satyphp** [opencart/opencart#3225]
Both 2.0.1.1 and 2.0.2.0 have this error:
When you add a product with a lot of options (like the demo Apple 30" screen) you can't edit the quantity in the cart, it just shows [] i am not understanding what is issue .its working on local system fine but when upload on live server it just shows []

**Comment by ypn** [comment]
i think this problem can be the string contain special character like double quote.OP not check any issues like that.
