### ISSUE TITLE
error on checkout

### ISSUE THREAD

**Issue by tangara** [opencart/opencart#3236]
when too many items are selected then in stock from a product that has options
in checkout get
 Products marked with *** are not available in the desired quantity or not in stock!

when you reduce amount of items and hit update button I get blank white screen with [] in top left corner
![screen1](https://cloud.githubusercontent.com/assets/6454781/9184386/5a87a0fe-3ff8-11e5-966c-bc3a3912d835.jpg)
![screen2](https://cloud.githubusercontent.com/assets/6454781/9184392/64ed7ac8-3ff8-11e5-9893-a63187247998.jpg)

**Comment by milimar** [comment]
What verison of OC you are talking about?

**Comment by tangara** [comment]
Version 2.0.3.1

**Comment by tangara** [comment]
Not sure what closed means..does that mean it is being looked at or not...have I posted this in right place?

**Comment by milimar** [comment]
@tangara , your issue is closed because it is not a bug. It might be a misconfiguration or maybe you should install your software again and try if it will work well.

**Comment by tangara** [comment]
I did a fresh install of version 2.0.3.1
without editing anything choose product Canon EOS 5D  chose option red added 6 quantity to cart
tried to checkout and get screen attached with...Products marked with *** are not available in the desired quantity or not in stock!

so then reduced quantity to 1 and hit update button..I get same error blank white screen with [] in top left corner

**Comment by tangara** [comment]
sorry this is screenshot ![screen5](https://cloud.githubusercontent.com/assets/6454781/9219584/3fb40970-411f-11e5-837c-089b725fc019.jpg)

**Comment by milimar** [comment]
You should try to obtain help at the forum: http://forum.opencart.com , because as I said it is not a bug. 
If you need a proof, go to my test website (OC 2.0.3.1) and try to buy this boots http://test.milimarshoes.com/index.php?route=product/product&product_id=61 . There are only 3 pairs left, so try to buy 4 and then reduce the number, and you will see that it works like it should.

Please, don't post again here, unless you find a bug.

**Comment by tangara** [comment]
Ok thanks..yes that makes it clearer
