### ISSUE TITLE
should Url Link self-manage SSL config?

### ISSUE THREAD

**Issue by veksen** [opencart/opencart#3241]
Just throwing this out here, should the [link method](https://github.com/opencart/opencart/blob/master/upload/system/library/url.php#L16) deal with SSL config by itself? I think it's unnecessary, redundant, and prone to error to have to define the SSL config everywhere in the code. Of course it could be overwritten if explicitely defined.

If you give me a go on this, I'll prepare a pull request. There are over 2800 references to $this->url->link() in the code right now, sooo... :)

Let me know.

**Comment by danielkerr** [comment]
no because you don t need ssl on every page

**Comment by veksen** [comment]
that's why you pass false only to those exceptions..





-------- Original message --------

**Comment by veksen** [comment]
even then it makes no sense, if you enable SSL, it should be used everywhere

**Comment by danielkerr** [comment]
are u arguing with me again. do some research! web site used to take ages to load using ssl.

it makes sites load slower. i know google changed its policy of ssl every where but its down to the user. you want ssl every where make the default HTTP_SERVER in the config to ssl url
