### ISSUE TITLE
It's possible to order out-of-stock products when "Stock Checkout" is set to "No"

### ISSUE THREAD

**Issue by JoshuaLuckers** [opencart/opencart#3248]
Steps to reproduce:
1. Set "Stock Checkout" to "No".
2. Change the quantity of a product to 1.
3. Open 2 browsers (eg. Safari and Chrome).
4. Add the product of which there is only 1 in stock in both browsers to your cart.
5. Go trough the checkout procedure in 1 browser (browser A) till the last step.
6. Go trough the checkout procedure in the other browser (browser B) and finish it.
7. Finish the checkout procedure in browser A.

Now it turns out that the product is ordered 2 times, the quantity of the product is also now -1 rather than 0.
Browser A in this case would have to get an out-of-stock message when trying to finish the order but this doesn't happen.
I tried to fix this issue myself by adding a out-of-stock check in the checkout/success controller but this didn't work and gave an out-of-stock message for both browsers thus unable to order the product.

**Comment by danielkerr** [comment]
stop wasting my time.

**Comment by JoshuaLuckers** [comment]
@danielkerr why is this wasting your time? It took me some time to figure out why two people where able to order the same product while the quantity of the product was 1.

**Comment by mksystem** [comment]
@JoshuaLuckers danielkerr is known to be unpleasant for others (gently speaking) and this is sad, btw. I checked this and I think I know what the problem is. The order does not reserve amounts of product, amounts is changed only then, when you change the status of a particular order to "complete"

**Comment by JoshuaLuckers** [comment]
@mksystem thanks for your comment. Maybe I should have included the fact that the order done via browser B was set to complete before the order done via browser A was finished. If I understand it correctly this particular case is not by design (unless the order done via browser B was not set to complete before the order via browser A was finished)?

**Comment by mksystem** [comment]
@JoshuaLuckers So it's a bug :) And I may confirm it but only in case when user B came to step number 6 ("Confirm Order"). In every previous step the amount of product it was verified.

**Comment by garudacrafts** [comment]
It's not a bug. Quantity is not reduced unless order status is processing or complete (https://github.com/opencart/opencart/blob/master/upload/catalog/model/checkout/order.php#L300). This stop sales loss from abandoned carts. Think about it: if stock were to be held in the cart (and reduced before order confirmation), then any product quantity added by a indecisive customer to their cart would be unavailable indefinitely to actual paying customers when the customer logs out and his/her cart is saved! That is a bad idea.

If one did want to implement a stock hold on the cart, then the store should have expiration dates on carts. Sounds like a good idea for an extension, but not necessary for the core.

**Comment by JoshuaLuckers** [comment]
@mksystem @garudacrafts user B did complete the order (order status was set to complete, order was also paid for). User A left the order open in step 6 (Confirm order) and finished and paid the order after the order by user B was completed.

**Comment by garudacrafts** [comment]
@JoshuaLuckers I hear you. It's absolutely possible for both to purchase, as you describe. But this can only happen when the 2 users are going through the cart process at the exact same time. A page refresh of the cart is all that is needed to correctly trigger the out of stock warning for user A. This narrows down the probability of it happening from unlikely to very unlikely. It boils down to a "timing issue" that is the lesser of two evils (the alternative being the aforementioned holding/locking stock in carts).

**Comment by JoshuaLuckers** [comment]
@garudacrafts It doesn't have to be at the same time. User A started the checkout process around 15:00 and kept his browser open in the last step (Step 6: Confirm Order). A hour later user B placed his order and finished the checkout proces (order was set to complete, user also paid for it). A few hours after that user A pressed "Confirm order" and was able to buy a product that was not in stock.

**Comment by mksystem** [comment]
In my opinion validation quantity of the order should take place before (just like is now) and just after our confirmation (before payment - like now isn't).

**Comment by OpenCartAddons** [comment]
There would still be a small chance of customers completing the payment for out of stock items if the shop owner is using a hosted payment page.

Both Customer A and Customer B are transferred to the hosted payment page (e.g. PayPal Standard) and therefore pass the out of stock check. The stock is not adjusted until Customer A completes the payment and the payment sends the callback to OpenCart.  Unfortunately Customer B can also complete his payment.

Adding an additional check before the customer confirms the order would be a step in the right direction, but won't completely eliminate the issue.

**Comment by garudacrafts** [comment]
The only to add a quantity check after the confirmation step has rendered (confirm.tpl) and before payment is processed is to bind an ajax call to the payment submission button to a new function (in confirm.php) that performs the quantity check ($this->cart->hasStock()).

But, *every payment template*  would need to be updated. The code for the payment submission buttons do not share a unique identifier. Even if a unique class name, like "button-payment-submit", were added to all of them, some payment templates that already bind an ajax call to complete payment would still need to be updated to prioritize the triggering events.

As an addition measure, an expiration date field could be added to the order table and a verification check on it could be added to the same new function called by the ajax request. The value could be made configurable so the admin can set it to +15min or +5min or whatever.

I'm not against such an approach; it adds value. But it's not a bug - more like an improvement request. Because it closes such a small "loophole" (how many customers keep pause at the confirmation step for hours??), I don't see @danielkerr adding it to the core. But I bet an ambitious developer could sell a few as extensions! :)

**Comment by garudacrafts** [comment]
As @OpenCartAddons mentioned, even using the approaches I suggested, the "loophole" will remain open for as long as the customer is transferred to a hosted payment page. The hosted payment provider should have a timeout, but the window of opportunity will remain open for that time period.

Again, this boils down to a "timing issue". The chances of it happening are small and can be made evern smaller by implementing my suggestions above, but not eliminated. This is an issue with all e-commerce. Every business should be aware of it and have the proper procedures in place to handle it (i.e. refunds).

**Comment by JoshuaLuckers** [comment]
In my opinion a loophole is a bug. I will try to implement a bug fix myself with a check like @garudacrafts suggested. Thanks all for your input on this issue.
