### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by bezdna** [opencart/opencart#3251]
Notice: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '4231, 99, 'Telangana', 'TS', 1)' at line 1
Error No: 1064
(4231, 99, 'Telangana', 'TS', 1); in /home/anton/projects/vdgrande/upload/system/library/db/mysqli.php on line 41

Fatal error: Call to undefined function token() in /home/anton/projects/vdgrande/upload/install/model/install.php on line 39

**Comment by danielkerr** [comment]
seems like you have not uploaded all the files and some are missing.

also i can not produce your sql error

im assuming this is an upgrade

**Comment by danielkerr** [comment]
ok just spotted the issue
