### ISSUE TITLE
The extension/modification refresh bug

### ISSUE THREAD

**Issue by chunguangblog** [opencart/opencart#3252]
operator:admin/index.php?route=extension/modification/refresh
bug code:line admin/controller/extension/modification.php 417 

// Just after modifications are complete, if config settings say maintenance mode is on AND is different org state, then turn it back on
if ($org_maintenance != $this->config->get('config_maintenance')) {

The code can lead to change the system configuration 
That is my local repair: if ($org_maintenance != $this->model_setting_setting->getSetting('config_maintenance')) {
from model get new setting

**Comment by chunguangblog** [comment]
version:2.0.3.1

**Comment by danielkerr** [comment]
Already fixed on the master branch
