### ISSUE TITLE
Document selection "lost" in filemanager when a filter is applied

### ISSUE THREAD

**Issue by robertogerola** [opencart/opencart#3253]
Scenario :
WYSIWYG text area, click the image button, click in the input filter
At this point the original document selection is gone and the filemanager doesn't know where to insert the image.

Solution :
Add this code in admin/view/common.js file

```javascript
var document_selection;

function saveSelection() {
    if (window.getSelection) {
        sel = window.getSelection();
        if (sel.getRangeAt && sel.rangeCount) {
            return sel.getRangeAt(0);
        }
    } else if (document.selection && document.selection.createRange) {
        return document.selection.createRange();
    }
    return null;
}

function restoreSelection(range) {
    if (range) {
        if (window.getSelection) {
            sel = window.getSelection();
            sel.removeAllRanges();
            sel.addRange(range);
        } else if (document.selection && range.select) {
            range.select();
        }
    }
}
```

In the same file at the beginning of the function
```javascript
$(document).delegate('button[data-toggle=\'image\']', 'click', function() {
```
add

```javascript
document_selection = saveSelection();
```
In file admin/view/filemanager.tpl
in function
```javascript
$('a.thumbnail').on('click', function(e) {
```
before

```javascript
var range, sel = document.getSelection(); 
```
add
```javascript
restoreSelection(document_selection);
```

**Comment by danielkerr** [comment]
great possible fix for something i can not replicate.

maybe if you gave a better description and details of browser used. possibly even a video.

**Comment by danielkerr** [comment]
ok i see. you mean the image manager search text field

**Comment by GomDani** [comment]
Confirm this in OC demo page wtih Firefox 40.0.2. If click in search input field in filemaneger then you can't add image to summernote editor.

**Comment by danielkerr** [comment]
@GomDani 

did you read where i said 

"ok i see. you mean the image manager search text field"

no need for confirmation

**Comment by GomDani** [comment]
I didn't see your second message when i started writing.

**Comment by danielkerr** [comment]
sorry.

this fix does not seem to work

**Comment by GomDani** [comment]
I replace in common.js:
    $(this).parents('.note-editor').find('.note-editable').focus();
with
    summernote_editor = $(this).parents('.note-editor').find('.note-editable');

And in filemanager.tpl before 
    var range, sel = document.getSelection(); 
add 
    summernote_editor.focus();

It seems to work.

**Comment by aymouna** [comment]
Scenario :
WYSIWYG text area, click the image button, click in the input filter
At this point the original document selection is gone and the filemanager doesn't know where to insert the image. Version(2.0.2.0)
Solution :
Change this code in admin/view/template/commen/filemanager.tpl  to :
 $('a.thumbnail').on('click', function(e) {
var htmlimage='<img src="'+$(this).attr('href')+'" >';
$('.note-editable').append(htmlimage);
$('#modal-image').modal('hide');
	});
