### ISSUE TITLE
Unable to change order status from pending to complete through add history option 

### ISSUE THREAD

**Issue by punnu16** [opencart/opencart#3256]
hi, i am  setting up my own store in localhost.. previously ADD HISTORY option worked correctly in admin panel but latter i don't know whats going wrong i unable to change the status from pending to complete or any other given status. i already checked settings so many time  for payment, shipping and order but still i am facing the same problem.please help me how to resolve this issue

**Comment by milimar** [comment]
Telling what version of OC you are talking about, will give you more chances someone to answer your question.

**Comment by punnu16** [comment]
i am using latest version OC 2.0.3.1

**Comment by danielkerr** [comment]
already fixed on the master branch
