### ISSUE TITLE
Native iOS/Android m-commerce app with opencart backend

### ISSUE THREAD

**Issue by edmundcwm** [opencart/opencart#3257]
Hi there,

Are there any extensions/examples out there for opencart v2 that allows seamless integration and development of a native iOS/Android mobile app with opencart CMS?

**Comment by milimar** [comment]
Here is not the right place for asking questions. Here we report, test and try to resolve bugs. If you need help you could try to obtain it on the official forum of OC http://forum.opencart.com .
