### ISSUE TITLE
Make tooltips work on new elements

### ISSUE THREAD

**Issue by Deji69** [opencart/opencart#3258]
Instead of using ajaxStop to add tooltips to new elements (which will also initiate the tooltip plugin multiple times every time ajax runs), why not just trigger this when the tooltip is needed?

My suggestion is to replace

    // Makes tooltips work on ajax generated content
    $(document).ajaxStop(function() {
    	$('[data-toggle=\'tooltip\']').tooltip({container: 'body'});
    });

With

    // Makes tooltips work on generated content
    $('body').on('mouseover.tooltip', '[data-toggle="tooltip"]', function() {
    	if ($(this).data('bs.tooltip') == undefined)
    		$(this).tooltip({container: 'body'}).tooltip('show');
    });

Much better, works without ajax.

**Comment by danielkerr** [comment]
i will look of a better solution later. thx though
