### ISSUE TITLE
If two categories have same sub category name then website does not show correct products

### ISSUE THREAD

**Issue by suvaiba** [opencart/opencart#3259]
HI,
i have a category: Samsung and sub category E-Series to divide mobiles as per models...
Another main category is NOkia and sub category E-Series...
Each main category have sub-category Accessories

Now if i click on Samsung>E-Series nokia mobiles are displayed
Similarly clicking on Accessories dont display correct results...

**Comment by suvaiba** [comment]
Well
i dig the issue more deeply and what i found was.... the SEO-keyword perhaps required to be unique across all the items..categories etc because they are supposed to call from home home.....
so that is why it was causing the issue....
Let me know if i am correct..... if there is some other issue....then kindly update...
similarly issue came when i use same SEO-keywords...for Brand and Category ... actually i have categorized items on Brand and then model style .......... so i have to set same SEO Keyword.... and it start showing URLs based on subcategory rather than the original
For example: when i click Apple/iPhone/iphone-4
the browser takes me to iPHone/iphone-4
this is because i used Same SEO-Keyword for  Category <Apple> and <BRAND> Apple  

It think it is bug... Brand and Main category can be same...as it is logical to make a Apple category as it will further categorized the products....In brand we cant have sub- categories

**Comment by danielkerr** [comment]
you shoudl only use unique seo keywords.

**Comment by garudacrafts** [comment]
This has been brought up so many times:
https://github.com/opencart/opencart/issues/2384
https://github.com/opencart/opencart/issues/2223
https://github.com/opencart/opencart/issues/1915
https://github.com/opencart/opencart/issues/155

It's simply how OpenCart is designed to work, not a bug. 

There are extensions available to allow duplicate category names (e.g. http://www.opencart.com/index.php?route=extension/extension/info&extension_id=6210) and many other seo extensions (http://www.opencart.com/index.php?route=extension/extension&filter_search=seo).

**Comment by hayden-t** [comment]
this doesnt have to be a problem there is no need for categories of different paths to not have unique keyword !!
