### ISSUE TITLE
Problem round discount (double round)

### ISSUE THREAD

**Issue by hermans** [opencart/opencart#3260]
It's get problem in grand total when get discount $1.995 
example:

sub total: $ 3.99
discount: $2  --> from $1.995 
grand total be: $ 2

should be grand total $1.99 

my solution fix in library currency:
$string .= number_format(round($value, (int)$decimal_place), (int)$decimal_place, $decimal_point, $thousand_point);

change to be:
 $string .= number_format( floor(( $value *100))/100 , (int)$decimal_place, $decimal_point, $thousand_point);

**Comment by ADDCreative** [comment]
Rounding 1.995 to 2 is correct for most countries.
http://www.hmrc.gov.uk/manuals/vatrecmanual/vatrec12030.htm

**Comment by hermans** [comment]
thanks
FYI in my case the site always use 2 decimal.

**Comment by danielkerr** [comment]
so the community should guess your country

**Comment by danielkerr** [comment]
tthe only other option would be to set an option to use floor or ceil to decide if to round up or down.
