### ISSUE TITLE
Hidden currency problem

### ISSUE THREAD

**Issue by Knoxvillekm** [opencart/opencart#3268]
Opencart 2.0.3.1

I have 2 currency:
- USD - default for store(main) and hidden
- UAH - visible

In Chrome no problem (all price in UAH), but IE and Mozilla show USD.

**Comment by danielkerr** [comment]
clear your cookies from the browser!

**Comment by Knoxvillekm** [comment]
Clear cookies not help me.

**Comment by milimar** [comment]
I think it would be a good idea if you test this on another computer.

**Comment by Knoxvillekm** [comment]
This checked on 5 PC. In Chrome - fine, IE and Mozilla - showed hidden currency.
I'll check this on new oc without extensions.

**Comment by Knoxvillekm** [comment]
currency.php
```js
public function __construct($registry) {
  ...
  $this->set($this->config->get('config_currency'));
  ...
}
```
This line always set defualt currency. But my defult currency hidden.
