### ISSUE TITLE
loader.php is problem for modules and templates

### ISSUE THREAD

**Issue by webxpro** [opencart/opencart#3269]
loader.php has changed some class and all modules and templates will need to update and change all files , i tested master with 3.0.1.0 version templates and not working.

**Comment by danielkerr** [comment]
some code has changed but still acts the same.

**Comment by webxpro** [comment]
i used 8  3,0,1,1 template for github  master and all i got this error

Fatal error: Class 'Controllermodule' not found in C:\xampp\htdocs\test\system\engine\loader.php on line 28

but when i change the load file with old then all works fine.

**Comment by danielkerr** [comment]
im not hear to answer your personal problems. this is a development tracker for the main opencart master.

**Comment by webxpro** [comment]
:)
