### ISSUE TITLE
Double quotes breaks product name on edit form

### ISSUE THREAD

**Issue by sarrala** [opencart/opencart#3270]
Version 2.0.3.1

Product editor name field will be empty if product db field `product_description.name` contains double quotes `"`.

However, product listings still displays name correctly (with quotes) in both customer and admin sides.

---
Another thing about escaping html, which **could well be problem in API module** that I'm using, is when product data contains escaped quotes (&quot;) they will be unescaped (") before written to db. But as I already said, this one could possibly be more related to custom API module.

**Comment by jamesallsup** [comment]
Using double quotes works fine when adding through the admin edit area, if you are adding data from a custom module or directly to the db then it isn't being formatted properly

To get more help on your issue please use the forum http://forum.opencart.com
