### ISSUE TITLE
Coupon/Voucher should be available during checkout

### ISSUE THREAD

**Issue by hassi2k7** [opencart/opencart#3271]
Hi there,

to improve the usablility of the shop it should be possible to include the field for coupons during the checkout process.

Many of our customer didn't find the input in the cart and cancel the checkout or buy without the coupon.

**Comment by sp-apertus** [comment]
+1 

same problem with lots of customers here

**Comment by danielkerr** [comment]
except that services like google checkout and paypal express have the onclick checkout buttons on the cart page.

**Comment by sp-apertus** [comment]
so why not let the admin choose at which place the coupon code field should be?

**Comment by hassi2k7** [comment]
Why is that suggestion closed without a solution?
