### ISSUE TITLE
Fatal Error: Memory Exhausted

### ISSUE THREAD

**Issue by taydey** [opencart/opencart#3272]
I understand that many people have seen this issue before.  But all of the fixes that have been suggested have not worked thus far.  Here is the error that I get:

"Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 60000 bytes) in /home/davidluman/webapps/opencart_php54/system/library/image.php on line 32"
![fatal error](https://cloud.githubusercontent.com/assets/13984321/9498974/d55fb324-4bd9-11e5-941c-58eeb7d9e5cc.jpg)

I have tried the suggested increase in memory size allowed as such:
"memory_limit = 512M;
max_execution_time = 300;
post_max_size = 999M;
upload_max_filesize = 998M;"

but this does not fix the issue.  My webhosting service does allot me 512M of memory.  So that isn't the issue either.

I am running OpenCart v2.0.3.1 and have tried using PHP v5.6, v5.5, and v5.4 as a suggestion from my hosting company Webfaction.

This error occurs immediately after install.  As you can tell in the screenshot below, I have not even changed one thing from the core code directly after install.  The first thing that I tried to do was change the image that is shown below.  THE WEIRD PART of the whole issue is that the error occurs before I even get the option to upload a image file.  So we know that it isn't a corrupt image file, or too big, or anything like that.  As indicated by the arrow in the image below, the error comes up immediately after pressing the edit button before I even get the dialog box to have the option of changing out the image.

![point to edit](https://cloud.githubusercontent.com/assets/13984321/9499219/4fe2f4e8-4bdb-11e5-8942-b7a5b1f23ab8.jpg)

Any help is greatly appreciated.  If needed I can show the different php files if that will help.  But like I said, the version of opencart I have installed is fresh from the opencart website and has had no adjustments made to it at all yet.  This is a straight out of the box error that I get.  

Am I missing something very simple or is there a larger issue to this?

Thank you!

**Comment by georgipetrov** [comment]
Have you tried on other host? Something else may have eaten your allocated memory and in fact to have bits of available memory.

Regards,
Georgi Petrov - iSense Team

**Comment by taydey** [comment]
That is a valid point...  I didn't even think of this.  We currently have another website (wordpress WooCommerce site) that is being ran under that same host setup.  This other site is live right now and we will eventually be killing this site once our new one is built.  Is this likely a cause for this?

If this is likely the cause, is there a chance of being able to build the site locally on my PC and then upload the full thing right before we go live?  (I've been searching for some documentation on this but haven't had luck yet, if you know of a good source on how to do this that would be great!)

I appreciate the help!

**Comment by taydey** [comment]
I can also upgrade the memory allotment for applications on my host.  Would another 512M work or would I likely need more...

**Comment by georgipetrov** [comment]
You can ask on the forum or any OpenCart partner if you need this to be investigated, since this place is for issues and features related to OpenCart. Generally OpenCart has a small footprint on memory. I think in your case you either have a local restriction for memory limit less than the max you have set, or as previously mentioned you just have less available due to other processes. You may contact the host or a sysadmin to look deeper.

Regards,
Georgi Petrov - iSense Team

**Comment by tiborbesze86** [comment]
Have you set both php.ini files (in the root folder, and in the admin folder as well) up to an increased memory limit? I had problems with 700+ products, where I had to increase my memory limit from 64M to 128M, but never had issues ever since that. Also, can you ask your service provider, if they allow you to change those values on a folder level? The error message on your screenshot is basically saying, that 64M was not enough for that script to execute, so I don't think your increased memory limit actually is in place.

**Comment by davidjuanesb** [comment]
exactly same problem. Any solution?

**Comment by patelchirag122** [comment]
Hi friends you will solve this error ,
1) Go throw ftp open image folder and Like root directory image/catalog and find image more then 1MB and delete this image.
2) then login through admin penal and check.
3)error will be remove from control penal .

**Comment by patombugua** [comment]
Changing the php.ini in admin folder worked for me

**Comment by sakilimran** [comment]
@patelchirag122  Thanks for the solution.

**Comment by malikfaizanbabar** [comment]
agree admin php.ini file changes worked

**Comment by kitkit85** [comment]
@patelchirag122 
temporary solution and later dont upload something more than 1mb .

@patombugua 
works forever , i believe .

**Comment by lxgiang90** [comment]
Thank you,
I have also overcome this,
I fixed it in admin/php.ini and it worked.
Earlier I also updated the php.ini file in addition to the root directory.

memory_limit = 1G;
max_execution_time = 180000;
upload_max_filesize = 999M;
