### ISSUE TITLE
When you add an attribute without group

### ISSUE THREAD

**Issue by roma-fe** [opencart/opencart#3274]
When you add an attribute without group
Notice: Undefined index: attribute_group_id in localhost\admin\model\catalog\attribute.php on line 6
Warning: Cannot modify header information - headers already sent by (output started at localhost\admin\index.php:80) in localhost\system\library\response.php on line 12

and 

When you delete an error Notice: Undefined index: total in localhost\admin\model\sale\return.php on line 234

**Comment by hotwer** [comment]
Should it be possible to create attributes without a group? I don't think so...
