### ISSUE TITLE
Missing config_language_id

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#3275]
![no_desc](https://cloud.githubusercontent.com/assets/3872726/9520217/7b6d97c2-4cc5-11e5-82c6-ce2a9751d096.jpg)

In catalog model product in all functions get * Products is used config_store_id but missing where config_language_id. Is this on purpose.

**Comment by danielkerr** [comment]
can not replicate. i think you did a bad upgrade.

**Comment by GomDani** [comment]
Fresh install from master. If product doesn't have description in config_language_I'd, the getSpecials function get product from db, but getProduct function return empty array.
