### ISSUE TITLE
Can not remove options from products

### ISSUE THREAD

**Issue by Kengun** [opencart/opencart#3277]
Version 2.0.3.1. I can not remove "options" from products. I can click the - to remove it, but after I click save and go back the options are back too. Clicking on the red - do not work at all.

**Comment by tiborbesze86** [comment]
It must be something related to a module or modification you've installed. My shop runs on Opencart 2.0.3.1, and I have no problem adding, saving, then removing them. After I've removed and saved, it will remain removed.

**Comment by Kengun** [comment]
Thanks. Added vqmod and Product Price By Size extension. Could be one or both of them.

**Comment by tiborbesze86** [comment]
Try disabling your third party modules and vqmod xml files one by one, and it might help you track down the issue. I'm afraid your problem is not related to the core Opencart code, so your issue will be closed by one of the developers shortly.
