### ISSUE TITLE
Opencart admin shows white screen

### ISSUE THREAD

**Issue by dayour4** [opencart/opencart#3280]
I uploaded my site to a web server and tried logging in into the admin backend but i get a white background all thorugh. need help

**Comment by dayour4** [comment]
Sorry why is my comment closed

**Comment by milimar** [comment]
@danielkerr has been making mayor changes lately so it is normal new bugs to appear, and we all do our best to report that bugs so he and the coders of the community could resolve them, but in your case I think It cannot be bug. 
Why don't you delete everything from your server and try to do all again? Ask your server provider for help too.
The good thing is that you could still ask for help on the right place for it http://forum.opencart.com .
