### ISSUE TITLE
Color profile not correct

### ISSUE THREAD

**Issue by Thomaxo** [opencart/opencart#3286]
The (resized) images are overly vibrant in chrome/firefox, presumably because of the original color profile information lost. How to fix this?
Exporting all the images to an opencart-accepted colorprofile doesn't seem handy.

Thanks!

**Comment by danielkerr** [comment]
what are you talking about "opencart color profile"

oipencart does not have one. it uses the build in php GD functions.

you are the only one ever to complain about this!
