### ISSUE TITLE
Changing order status in history tab increases stock quantity

### ISSUE THREAD

**Issue by Tenida** [opencart/opencart#3292]
I am using OC 2.0.2.0 and having  an stange issue. Whenever I change the status of an order to 'shipped', stock of that product gets incremented by the ordered quantity value.

Lets say  product X has 5 quantity and someone orders 2 piece of it. The order is placed, with order status 'processing' and the quantity is showing 3 as it should. Then I pack the product and despatch it and update the status 'shipped' notifying the customer in history tab. Here at this point my stock quantity must not get affected by the order status 'shipped' but when I check the quantity on product page, it shows 5. Then again I change the status to 'complete' and the stock becomes 3 again. 

The practical problem is, between the time of an order attains status 'shipped' to 'complete', if I get order of that product, I need to cancel them as I mostly sell unique product (mine is a jewellery boutique, so each item is one of a kind).  In my case, mostly product quantity is set to 1 or 2, so after a product is sold, it becomes 'out-of-stock', so if changing the status to 'shipped' increases quantity, the product is no more 'out-of-stock' and due to this issue I am having trouble servine my customer. 

I have searched forum and both open& closed bugs but didnt find exact match, few were similer though but didnt helped.

Please fix this and help me. Or please redirect me to forum post/closed bug where this issue has been addressed before closing it.

**Comment by tiborbesze86** [comment]
I don't think this is a bug. Just set the 'Complete Order Status' to both Complete and Shipped in the Store Settings on the admin panel.

**Comment by Tenida** [comment]
Thank you very much for correcting me, but it worked only when I checked 'shipped' on Processing Order Status and not Complete order status. 
Anyways it helped me solve my problem. Thanks again.
