### ISSUE TITLE
Image manager not working in Mozzila and Chrome

### ISSUE THREAD

**Issue by milimar** [opencart/opencart#3296]
OC 2.1.0.0 master from 01-09-15, just try to add a new product and to upload an image in the data tab, or even images at images tab.

![scr1](https://cloud.githubusercontent.com/assets/9386798/9641152/71213d38-51b5-11e5-8771-43dc52368e6b.jpg)

 It is not possible to create a new folder, to upload image and even the refresh button doesn't work like it should. If you click on the folder "demo" you obtain this:

![scr2](https://cloud.githubusercontent.com/assets/9386798/9641135/60854ff0-51b5-11e5-8c2a-128529c228ad.jpg)

 It is not possible in Mozilla and Chrome, but in Internet Explorer it works like expected.

I tested this on several computers, I cannot be wrong, it is a bug for sure!

**Comment by danielkerr** [comment]
im using chrome and its fine.

**Comment by milimar** [comment]
About this issue, I contacted my web hosting provider company and they investigated the issue and they agree that the issue exists, but they don't think it is caused by them, so I am sending you their reply on this issue.

It is however very strange that no one else has reported this and I personally believe that this is not an OC bug, and the problem is with my server....however if you want you can check it better. 

Here is the reply from my web hosting provider.....

Hello,

Thank you for your reply.

I have investigated the issue you have experienced in details and the only thing I can say is what it has been said already by my colleagues:

• The issue is related to the browser compatibility of the Release Candidate OC version. With Google Chrome and Mozilla Firefox the issue is presented while checking the issue with Internet Explorer shows that the same does persist.

I tried changing the version of the php service to php 5.5, 5.6 and even I tried the php 7 version which is the most recent. With all these versions the situation is quite the same - the upload image button does not work.

Now since this is a release candidate type of version we cannot provide any support of the same as we support and investigate issues only with the official Stable releases of Opencart. I am not sure why exactly you are demanding for using that version precisely when the 2.0.31 version is relatively stable and can be utilized at full. Anyway, no further investigation on the matter can be provided by our technical team until the Release candidate is not a Stable Version.

Please let me know if we can assist you further on that matter.

Looking forward to your reply.

Kind Regards,

**Comment by emperorerror** [comment]
encountered the same issue today
