### ISSUE TITLE
Edit Order Fetches Current Product Price, Not Sold At Price

### ISSUE THREAD

**Issue by paulbwd** [opencart/opencart#3298]
Forgive me if this has already been mentioned, but ive not seen any mention of it anywhere else.
Here's the scenario

Sell Product 1 at $100
Price of product 1 goes up to $200
Goto edit order, and instead of seeing the product on the order at $100 as it was sold, you see it at $200 and worse still if you dont happen to see this and carry on editing the order, it will save the order with the new price, Which can lead to all kinds of things like , incorrect Refund Amounts etc..

The price really needs pulling from the sale record, not the current product price.

Paul
Opencart V2.0.3.1

**Comment by danielkerr** [comment]
then void the order and start a new one!

**Comment by paulbwd** [comment]
Hi Daniel, I think you've not really understood the issue, you cant do this every time a product changes price in your catalog. lets imagine i have 1000 orders, and then i get a price increase at the suppliers,I may still need to manage those orders through the edit order screen, every one of those will now show the incorrect price and whats more without checking the original order details, I have no way of knowing if that price is right or not.

**Comment by hotwer** [comment]
#danielkerr this is a very problematic issue and voiding the order won't help either.

**Comment by paulbwd** [comment]
Exactly when I came across this early today I had to resort to editing the order values in phpmyadmin to put it back to the correct price,  I've built stock control systems and in way should we be pulling prices out of a product table for an order that already exits at x price,  Opencart saves this data in the order product table so why are we not pulling in this data?

**Comment by paulbwd** [comment]
This needs re-opening so it can be fixed, whats the point in reporting 'Real' bugs if were just going to be ignored, Opencart v2 can not be taken seriously if you cant even change the price of your products without it causing implications elsewhere in the ordering system. After editing an order yesterday and issuing a part refund to the customer, my customer was sent a copy of his invoice from opencart showing an incorrect product price (£50 More than he had paid) , which made us look most unprofessional, and dare i say it a bit dodgy, I had to convince him it was just an error on our part and that he had not been charged the extra £50 that was showing on his invoice.

**Comment by hermans** [comment]
Daniel, please check the issue before you decided to close the issue, this is really issue i think.

I just checked and i think this big issue, i have order $3 then i try to change product price $4 and the order total be $4.

**Comment by guiltar** [comment]
So many people confirm that it's an issue but every time it gets ignored and closed with an absurd excuse. Agree with @paulbwd that Opencart can not be taken seriously with such an approach to developing. 

https://github.com/opencart/opencart/issues/3792
