### ISSUE TITLE
Extension Installer Not Work in Version 2.0

### ISSUE THREAD

**Issue by naveen786** [opencart/opencart#3299]
Dear Sir,

i tried so many trick and your help forum but no one provide correct solution to Install Extension in opencart v2.0

Please Rectify this bug and also describe the procedure how i Install Extension 

Please help i need it urgent

**Comment by OpenCartAddons** [comment]
@naveen786 Unfortunately the error messages for the extension installer are pretty vague.  It's likely one of your FTP settings are incorrect.  I still get confused by some of the settings at times.

Here's a little more information on the FTP settings

FTP Host: This is usually your domain name (e.g. opencart.com).
FTP Port: Most hosting services use port 21, but double check with your hosting provider.
FTP Username: Again, this usually corresponds with your domain (e.g. user@opencart.com).
FTP Password: The password for the FTP user account.
FTP Root: If OpenCart is installed at the base directory, simply enter "/" into the field. If it's installed in a subdirectory, enter the directory name (e.g. /subdirectory/)
Enable FTP: Set this to Yes.

If you're still having issues with the extension installer and need to install an extension, I have a tutorial on how to manually install OpenCart extensions which you can follow here:
http://opencartaddons.com/extension-installation-tutorial

Regards,
Joel.

**Comment by GizMecano** [comment]
By the way, maybe it would be helpful to provide the [complete version number](https://github.com/opencart/opencart/releases) of the release you use and the name of the extension you have tried to install.

**Comment by clorne** [comment]
OCMOD an introduction and installation guide for OpenCart users at

http://ocextensions.co.uk/ocmod/ocmod

**Comment by danielkerr** [comment]
use the contact us form or the forum!
