### ISSUE TITLE
Installation Issue - DB Prefix

### ISSUE THREAD

**Issue by OpenCartAddons** [opencart/opencart#3307]
The current release for 2.1.0.0 has an issue with replacing the DB Prefix that is assigned during the Step 3 in the installation.

This is due to the script looking for "CREATE TABLE IF NOT EXIST `oc_", whereas the opencart.sql file uses "CREATE TABLE `oc_".

I've created pull request #3308 which corrects the issue during the installation by replacing CREATE TABLE with CREATE TABLE IF NOT EXISTS as I believe it was intended to be.

Cheers,
Joel.

**Comment by danielkerr** [comment]
this is not a fix.

if yuou want to fix it fix the upgrade code.

**Comment by OpenCartAddons** [comment]
@danielkerr my apologies, you used the wrong call in both the install and upgrade script so I assumed the opencart.sql file was the issue. 


Joel.
