### ISSUE TITLE
error in upgrade 2.1.0.0

### ISSUE THREAD

**Issue by mrteray** [opencart/opencart#3317]
error in updgare stable 2.0.3.1 - testing 2.1.0.0

[code]PHP Warning:  preg_match(): Empty regular expression in /home//test/install/model/upgrade.php on line 375[/code]
line 381

[code] preg_match(): Empty regular expression in /home//test/install/model/upgrade.php on line 392[/code]

[code]preg_match(): Delimiter must not be alphanumeric or backslash in /home/cigarelka/test/install/model/upgrade.php on line 403[/code] line 409, 415, 426

bottom Continue -1sec adn show "Don't forget to delete your installation directory!"
not upgrade version 
my server bad? or code?

**Comment by danielkerr** [comment]
try now

**Comment by danielkerr** [comment]
i just added a fix tot he master branch

**Comment by mrteray** [comment]
PHP Notice:  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `code` = 'config', `store_id` = '0'' at line 1<br />Error No: 1064<br />UPDATE `1_setting` SET `value` = '[\\"5\\"]' WHERE `key` = 'config_complete_status', `code` = 'config', `store_id` = '0' in /home/1/test/system/library/db/mysqli.php on line 41, referer: http://test.1.com.ua/install/

PHP Notice:  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `code` = 'config', `store_id` = '0'' at line 1<br />Error No: 1064<br />UPDATE `1_setting` SET `value` = '[\\"2\\",\\"13\\",\\"9\\",\\"3\\"]' WHERE `key` = 'config_processing_status', `code` = 'config', `store_id` = '0' in /home/1/test/system/library/db/mysqli.php on line 41, referer: http://test.1.com.ua/install/

 PHP Notice:  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `code` = 'config', `store_id` = '0'' at line 1<br />Error No: 1064<br />UPDATE `1_setting` SET `value` = '[\\"1\\"]' WHERE `key` = 'config_customer_group_display', `code` = 'config', `store_id` = '0' in /home/1/test/system/library/db/mysqli.php on line 41, referer: http://test.1.com.ua/install/
