### ISSUE TITLE
Voucher send query is strange

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#3320]
I think that this

`AND vtd.language_id = '" . (int)$order_info['language_id'] . "' WHERE v.order_id = '" . (int)$order_info['order_id'] . "'`

must be 

`WHERE v.order_id = '" . (int)$order_info['order_id'] . "' AND vtd.language_id = '" . (int)$order_info['language_id'] . "'`

**Comment by danielkerr** [comment]
wow you are really good at testing
