### ISSUE TITLE
Error successful registration

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#3321]
File catalog/controller/account/success.php line 32:

$data['text_message'] = sprintf($this->language->get('text_message'), $this->url->link('information/contact'));

This did errors:
PHP Warning:  sprintf(): Too few arguments in /home/epromiro/domains/epromirok.hu/public_html/catalog/controller/account/success.php on line 32

This fix remove error:
$data['text_message'] = sprintf($this->language->get('text_message'), $this->url->link('information/contact'), '');

**Comment by danielkerr** [comment]
the issue is with your language transalation
