### ISSUE TITLE
Issues Related version 2.1 

### ISSUE THREAD

**Issue by rahulpathania61** [opencart/opencart#3324]
Default captcha not working in the specified pages.

**Comment by danielkerr** [comment]
a

**Comment by rahulpathania61** [comment]
Daniel is this issue resolved?

**Comment by danielkerr** [comment]
its working for everybody else. 

FYI this is a developer bug tracker and not your personal problem solver!

**Comment by rahulpathania61** [comment]
this is not my personal problem i was testing this version and found the that its not working so i informed you....and i don't need a personal problem solver for myself i can solve it myself. This is opencart issue thats why i informed you.

**Comment by rahulpathania61** [comment]
this is not my personal problem i was testing this version and found the that its not working so i informed you....and i don't need a personal problem solver for myself i can solve it myself. This is opencart issue thats why i informed you. RAHUL PATHANIA 


     On Friday, 11 September 2015 5:55 PM, Daniel Kerr <notifications@github.com> wrote:
   

 its working for everybody else. FYI this is a developer bug tracker and not your personal problem solver!—

**Comment by danielkerr** [comment]
sorry about the response. I did not realize that a a post was in the forums requesting peoples to test the pre release.

you need to save which captcha to use in the settings.

**Comment by OpenCartAddons** [comment]
The issue with captcha not appearing was resolved in PR #3313 

It was due to some coding issues in the template file.


Regards,
Joel.
