### ISSUE TITLE
Issues in notification admin panel

### ISSUE THREAD

**Issue by rahulpathania61** [opencart/opencart#3327]
Notification is not working properly... I have attached the snapshot of the problem...
 kindly have a look

![screenshot](https://cloud.githubusercontent.com/assets/14231701/9814228/f753c8c6-58a9-11e5-81dc-e4f39163b87d.jpg)

**Comment by danielkerr** [comment]
another problem you caused your self and wasting my 5 minutes looking into it.

**Comment by rahulpathania61** [comment]
Daniel this is not my problem ok. I am an opencart developer and i was told to look issues in the latest version of opencart 2.1.... this problem is not created by me i was testing the opencart and i found problems so i highlighted those issues for proof i have also attached the snapshot of the problem. if you don't want to solve it is not my headache my duty was to highlight the issue i have highligted it.

**Comment by rahulpathania61** [comment]
Daniel this is not my problem ok. I am an opencart developer and i was told to look issues in the latest version of opencart 2.1.... this problem is not created by me i was testing the opencart and i found problems so i highlighted those issues for proof i have also attached the snapshot of the problem. if you don't want to solve it is not my headache my duty was to highlight the issue i have highligted it. RAHUL PATHANIA 


     On Friday, 11 September 2015 5:57 PM, Daniel Kerr <notifications@github.com> wrote:
   

 Closed #3327.—

**Comment by OpenCartAddons** [comment]
@rahulpathania61 This may be caused because the "Complete" status is also selected as a Processing Order Status within the system settings.

**Comment by rahulpathania61** [comment]
I have resolved this issue thanks for your concern
