### ISSUE TITLE
error in upgrade 2.1.0.0 part 3 and other error 

### ISSUE THREAD

**Issue by mrteray** [opencart/opencart#3329]
not updated, there is no error in the logs, the database(sql) has not changed 
3317+3325

and error in admin panel common/dashboard

2015-09-11 12:34:55 - PHP Warning:  vsprintf(): Too few arguments in /home/1/test/admin/controller/dashboard/activity.php on line 19

**Comment by danielkerr** [comment]
if you keep posting part 1 part 2 you get  a ban!

**Comment by danielkerr** [comment]
your just wasting my time!

DO NOT POST HERE AGAIN. YOU HAVE PROVIDED NO USEFUL INFORMATION ABOUT THE ISSUE.

**Comment by danielkerr** [comment]
wasting my time again going over every method to produce a new activity to find one with the issue!! thats even if there is one and its not you adding a different language!

**Comment by danielkerr** [comment]
ok been through every activity and can not find any issue!

DO NOT POST HERE AGAIN.

**Comment by mrteray** [comment]
ok, sorry for the it is, I just shiny new
