### ISSUE TITLE
MaxMind Fraud module is broken

### ISSUE THREAD

**Issue by shibinv** [opencart/opencart#3331]
**Needs the following fixes in:**
```
catalog/model/fraud/maxmind.php
```

**Line 6:**
*replace*
```php
$fraud_info = $this->getFraud($data['order_id']);
```
*with*
```php
$order_id = $data['order_id'];
```

**Line 28:**
*replace*
```php
$request .= '&license_key=' . urlencode($this->config->get('config_fraud_key'));
```
*with*
```php
$request .= '&license_key=' . urlencode($this->config->get('maxmind_key'));
```

**Lines 112-116 are duplicate with lines 106-110**
*remove*
```php
if (isset($data['ip_city'])) {
    $ip_city = $data['ip_city'];
} else {
    $ip_city = '';
}
```

**Comment by shibinv** [comment]
**Line 63 is not needed, it would just be duplicate from line 6**
*remove*
```php
$order_id = $data['order_id'];
```

**Comment by OpenCartAddons** [comment]
@shibinv Other than the duplicate ip_city, the issues you brought up appear to already be corrected.  Double check that you have the latest version of the master branch downloaded.


Joel.

**Comment by shibinv** [comment]
@OpenCartAddons Thanks, I was going by release 2.0.3.1
