### ISSUE TITLE
Bluepay Redirect payment getting wrong totals

### ISSUE THREAD

**Issue by beechyrb** [opencart/opencart#3338]
Bluepay Redirect payment method getting wrong totals from transactions table for (total released)
There is no need to get (auth) type transactions for the total amount released as this shows as it was released when it really wasn't and prevents from (release) function from actually working.

File: admin/model/payment/bluepay_redirect.php - line 182

**CHANGE**
public function getTotalReleased($bluepay_redirect_order_id) {
		$query = $this->db->query("SELECT SUM(`amount`) AS `total` FROM `" . DB_PREFIX . "bluepay_redirect_order_transaction` WHERE `bluepay_redirect_order_id` = '" . (int)$bluepay_redirect_order_id . "' AND (`type` = 'sale' OR `type` = 'rebate' OR `type` = 'auth')");

		return (float)$query->row['total'];
	}

**TO:**
public function getTotalReleased($bluepay_redirect_order_id) {
		$query = $this->db->query("SELECT SUM(`amount`) AS `total` FROM `" . DB_PREFIX . "bluepay_redirect_order_transaction` WHERE `bluepay_redirect_order_id` = '" . (int)$bluepay_redirect_order_id . "' AND (`type` = 'sale' OR `type` = 'rebate')");

		return (float)$query->row['total'];
	}

**Comment by beechyrb** [comment]
File: admin/model/payment/bluepay_redirect.php - line 182

**Comment by jamesallsup** [comment]
Fixed on commit: https://github.com/opencart/opencart/commit/56361d47bfc85eb233eba16ffee3c39c8d659a65
