### ISSUE TITLE
Adding reward points in admin (2.0.3.1)

### ISSUE THREAD

**Issue by vitak** [opencart/opencart#3341]
If user use reward points i order. In administration can`t add reward points for this order.
There is only button for remove.
Problem is in SQL query in file admin/model/sale/customer.php.
Fix is:
<modification>
	<id>Reward points fix</id>
	<version>OC 2.x</version>
	<vqmver>1.0.0</vqmver>
	<author>Netlion.cz</author>

	
	<file name="admin/model/sale/customer.php">
		<operation>
			<search position="replace" index="1"><![CDATA[
				$query = $this->db->query("SELECT COUNT(*) AS total FROM " . DB_PREFIX . "customer_reward WHERE order_id = '" . (int)$order_id . "'");
			]]></search>
			<add><![CDATA[
				$query = $this->db->query("SELECT COUNT(*) AS total FROM " . DB_PREFIX . "customer_reward WHERE order_id = '" . (int)$order_id . "' AND `points` > 0");
			]]></add>
		</operation>
	</file>
</modification>
Can anybody verifi it and merge to branche?

**Comment by danielkerr** [comment]
you need to check the master branch before posting
