### ISSUE TITLE
Add wishlist table

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#3347]
Can you please add wishlist table to opencart.sql. Thanks.

**Comment by Gustav1114** [comment]
Gom's description needs more explaining.

the issue with fresh install
```
Notice: Error: Table 'open_cart.oc_wishlist' doesn't exist
Error No: 1146
DELETE FROM oc_wishlist WHERE customer_id = '0' AND HOUR(date_modified) + 1 < NOW() in /srv/shop/system/library/db/mysqli.php on line 41Notice: Error: Table 'open_cart.oc_wishlist' doesn't exist
Error No: 1146
SELECT COUNT(*) AS total FROM oc_wishlist WHERE customer_id = '0' AND session_id = 'hna9l44ngtd4up0dfjpo2m5pv7' in /srv/shop/system/library/db/mysqli.php on line 41Notice: Trying to get property of non-object in /srv/shop/catalog/model/account/wishlist.php on line 55
```
and install/opencart.sql is missing oc_wishlist table
that's what I guess what he wants to say.

Is making the table from wishlist.php to opencart.sql good enough?

**Comment by danielkerr** [comment]
Im doing some research into how other carts handle wishlists. i would prefer if it forced the customer to register or login to add tot he wishlist

**Comment by GomDani** [comment]
One shop here in our country have multiple wishlist. You can add name and description to it, but you must be logged in. You have a button "Create wishlist" and then you choose in which wishlist to add product. Make wishlist in the way that can be extended like that.

**Comment by OpenCartAddons** [comment]
If the wishlist items are stored in the database than the system can be modified to make that information shareable across customers.  This would be perfect for a Gift Registry system.

**Comment by danielkerr** [comment]
was added in the last commit
