### ISSUE TITLE
Missing setTitle

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#3348]
In admin ControllerExtensionPayment in function install() missing $this->document->setTitle.

In admin ControllerExtensionModule in function getList() you use isset($this->request->post['selected']) but there are no input selected in .tpl.

In template extension analytics.tpl and fraud.tpl wrong colspan, change 8 to 3.

**Comment by danielkerr** [comment]
@GomDani 

are you a seller if so what is your username?

**Comment by GomDani** [comment]
No I am not the seller. At least not yet. I used OC to build my online store. Now it's my hobby. When I finish my multiseller I may be sell it on your site.

**Comment by danielkerr** [comment]
let me know i will set your account as premium seller.
