### ISSUE TITLE
Mysql error `cart` table option column remove index

### ISSUE THREAD

**Issue by nuke123** [opencart/opencart#3349]
Mysql Error: BLOB/TEXT column 'option' used in key specification without a key length. 

**Fixed below by removing the `option` from key.**

```sql
CREATE TABLE `oc_cart` (
  `cart_id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_id` int(11) NOT NULL,
  `session_id` varchar(32) NOT NULL,
  `product_id` int(11) NOT NULL,
  `recurring_id` int(11) NOT NULL,
  `option` text NOT NULL,
  `quantity` int(5) NOT NULL,
  `date_added` datetime NOT NULL,
  PRIMARY KEY (`cart_id`),
  KEY `cart_id` (`customer_id`,`session_id`,`product_id`,`recurring_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
```
Testing on Windows WAMP:
PHP 5.5.12
Mysqli 5.0.11

Also there was no error when installing I had to run the query manully to find what the problem was after install noticing the the cart table hadn't been created.

**Comment by danielkerr** [comment]
you dont need a key length for text fields
