### ISSUE TITLE
PayPal IPN - special characters

### ISSUE THREAD

**Issue by synweap15** [opencart/opencart#3351]
With the current approach, if the first name, last name, address or any other field contains any special character (like spanish á, é etc.), the request sent to PayPal that should mark the transaction as "Completed" will return "Invalid". I'll post a proposed solution to this problem shortly.

**Comment by synweap15** [comment]
It's not a clean MVC approach, but it seems suitable here as a special method of handling PayPal transactions only. It can be refactored and placed somewhere else.

**Comment by ADDCreative** [comment]
I don't think this is needed. You just need to set PayPal to use UTF-8.

In the sandbox click on "Profile", then "Language Encoding", then "More Options". Select UTF-8 and save.

In a live account click on "Profile", then "Profile and Settings", then "Language Encoding", then "More Options". Select UTF-8 and save.

**Comment by danielkerr** [comment]
this is completely untrue! I use this on the opencart.com web site and never had this issue.
