### ISSUE TITLE
mail issue

### ISSUE THREAD

**Issue by molly8023** [opencart/opencart#3352]
MY website http://shiyotex.com/ has a big problem.
when the customer add to cart.The mail system doesn't work,The customer can't receive the mail.
Please check it.

Thank you!!

**Comment by danielkerr** [comment]
its working for other people. idif you need support you need to use the contact us form on the opencart.com web site

**Comment by OpenCartAddons** [comment]
@molly8023 I highly recommend that you change your admin password immediately as everyone who is subscribed to OpenCart on Github has received an email with your login details.

Regards,
Joel.
