### ISSUE TITLE
Coupon per category does not work

### ISSUE THREAD

**Issue by samirdesign** [opencart/opencart#3354]
Hi,

Create a coupon that would be used only in one category. In the category chosen it works. But if I select a product from another category, you can buy as well. 

1 - The correct he would not restrict the purchase of this product that is not in the selected category in the coupon configuration?

2 - Why does not appear the coupon used in your history even though he already standing as the status "complete"?

3 - He does not respect the configuration Uses per Customer: first, because I was able to buy again with the same coupon with the same user.

My OC Version: 2.0.3.1
My coupon configuration:

- Coupon name: Test 20%
- Code: Test20
- Type:%
- Discount: 20
- Total Amount: 50
- Customer Login: yes
- Free Shipping: No
- Products: empty
- Category: Apple
- Start Date: 09/15/2015
- End Date: 09/30/2015
- Uses per Coupon: 1000000
- Uses per Customer: 1
- Status: Enable

**Comment by danielkerr** [comment]
the coupon discount only applies to the products in the selected category. the other products will not be discounted.

**Comment by danielkerr** [comment]
anyway added a fix

**Comment by ankitjn227** [comment]
getting similar error

coupon setup for 1 category, but it was getting applied to complete store..

how to resolve
