### ISSUE TITLE
Shoiwing error "We are currently performing some scheduled maintenance....." when not logged in as admin

### ISSUE THREAD

**Issue by avorob** [opencart/opencart#3360]
The site is showing error
"We are currently performing some scheduled maintenance. 
We will be back as soon as possible" when not logged in as admin in a separate browser tab.
It goes away once logged in.
http://www.aerialliftequipment.com/av

**Comment by danielkerr** [comment]
disable maintenance mode under settings

**Comment by Sameerkashmirbox** [comment]
any other way

**Comment by danielkerr** [comment]
it works:
https://www.aerialliftequipment.com/equipment-for-sale/scissor-lifts-for-sale

the av maybe needs saving again. seems like the keyword is not set to a category.
