### ISSUE TITLE
multiple file locations issue

### ISSUE THREAD

**Issue by harnishdesign** [opencart/opencart#3362]
I have Read Ocmod documentation here - https://github.com/opencart/opencart/wiki/Modification-System.

I am read there. Following code use for multiple file. but, this code is not working.
`<file path="system/engine/action.php|system/engine/loader.php|system/library/config.php|system/library/language.php">`

**this code is working Fine. (with commas)**
`<file path="system/engine/action.php,system/engine/loader.php,system/library/config.php,system/library/language.php">`

**So, actually my question is, Documentation information is wrong.**

**Comment by danielkerr** [comment]
this will be in the next version. look at the history for what it was before.
