### ISSUE TITLE
Admin Permission Denied after upgrade to latest master

### ISSUE THREAD

**Issue by btafoya** [opencart/opencart#3364]
I am unable to set the group permission, store, or access anything after the latest update from the master. Any suggestions? Did all of the basic stuff, cleared the cache, etc. Even restored the db backup and tried again a couple of times.

![image](https://cloud.githubusercontent.com/assets/4192106/9976407/29490f64-5eb1-11e5-8de5-b876e4a187fd.png)

**Comment by btafoya** [comment]
FYI - The front end is fully functional including the user account.

**Comment by danielkerr** [comment]
yes going to remove the testign code
