### ISSUE TITLE
Question about difference

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#3366]
In common/seo_url.php you firstly use:

```
$this->request->get['route'] = 'product.manufacturer/info';
```

and next:

```
$data['route'] == 'product.manufacturer.info'
```

is this OK or it must be

```
$this->request->get['route'] = 'product.manufacturer.info';
```

**Comment by danielkerr** [comment]
i was just testing these changes.

I'm going to put it back so we can move forward.

the reason for the change is becuase we have found some web hosting using a security policy blocking / int he urls. if this becomes more common we need to change. joomla also uses . to split up directories as its a safe html character.
