### ISSUE TITLE
Add to cart with string quantity

### ISSUE THREAD

**Issue by thanhhungtn1** [opencart/opencart#3372]
It is a funny bug. 
When I enter the quantity in string just like "asdasdad" system still showing success message but nothing in the cart. 
I think it should validate the quantity form that must be number.

**Comment by danielkerr** [comment]
it is validating by remove the item

**Comment by thanhhungtn1** [comment]
I meant, it should said "not valid quantity number" instead of auto removing the items and said it's success to add the item into the cart?
