### ISSUE TITLE
Modification Refresh makes site go into maintenance mode

### ISSUE THREAD

**Issue by TrickMyIdea** [opencart/opencart#3373]
( Trying to improve OC with my 2cents )

Version: 2.0.3.1

If you try to refresh the modification, it pushes site to maintenance mode even if it is active. 

Basically, issue is with this code (Line 63-68):
`
$org_maintenance = $this->config->get('config_maintenance');
			if (!$this->config->get('config_maintenance')) {
				$this->load->model('setting/setting');
				$this->model_setting_setting->editSettingValue('config', 'config_maintenance', true);
			}
`

Settings are updated to the database but not in the object. Hence the code below is NOT executed:
(Line 418-420)

`	if ($org_maintenance != $this->config->get('config_maintenance')) {
				$this->model_setting_setting->editSettingValue('config', 'config_maintenance', false);
			}
`

**Resolution:**
1. Update the object.
2. Reload the Config

For performance reasons 1. is recommended.

Below is the OCMOD that we created to resolve the issue:

`	<file path="admin/controller/extension/modification.php">
		<operation>
			<search><![CDATA[$this->model_setting_setting->editSettingValue('config', 'config_maintenance', true);]]></search>
			<add position="before"><![CDATA[
			 $this->config->set('config_maintenance',true);
			]]></add>
		</operation>
	</file>	
`

**Comment by danielkerr** [comment]
alreayd changed ont he master branch
