### ISSUE TITLE
OC 2.1.0.0_rc1 Edit Order not working

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#3374]
The Sales > Orders > Edit is still not working, I can only edit **Customer Details**, not however **Products**, **Payment Details**, **Shipping Details**, nor **Totals**. Is this still work in progress?

**Comment by danielkerr** [comment]
no finished. did you click the red add ip button?

**Comment by danielkerr** [comment]
any error messages? what about js errors?

**Comment by mhcwebdesign** [comment]
It only has View, Edit, and Delete buttons for each order in sale/order, no Add IP button in order/sale nor in order/sale/edit. 

However, I just noticed that I can use the Continue and Back buttons at the bottom of the sale/order/edit page to jump to the different tabs. No error messages, it's just confusing when the other tabs are disabled, I would have expected to be able to directly click on the tabs, instead of using the Continue/Back buttons.

**Comment by danielkerr** [comment]
it has to be this way. other wise it will mess peoples orders up if they are being edited. the pointer icon shows a disabled sign when you hover over it

**Comment by mhcwebdesign** [comment]
It does indeed show the disabled sign when hovering over the other tabs. 

Still, it's a bit confusing, maybe the template could be changed to use it in a way like the frontend multi-step checkout sequence?
