### ISSUE TITLE
Still problems with custom database port.

### ISSUE THREAD

**Issue by urbels** [opencart/opencart#3379]
Hello!

Trying to setup latest opencart on custom Mysql port with mysqli and got this:
Warning: mysqli::mysqli(): (HY000/2003): Can't connect to MySQL server on 'some.server' (111) in /system/library/db/mysqli.php on line 7

Notice: Error: Could not make a database link (2003) Can't connect to MySQL server on 'some.server' (111) in /system/library/db/mysqli.php on line 10

Warning: mysqli::close(): Couldn't fetch mysqli in /system/library/db/mysqli.php on line 58

Server have mysqli support and I can connect to that database throught phpmyadmin without problem.

**Comment by danielkerr** [comment]
so contact your host and find out which mysql port they use

**Comment by urbels** [comment]
I know exactly what port they use I wrote in it but the problem is not ir port and not in connection. It`s ins install script.
