### ISSUE TITLE
on the checkout page, step number does not re calculate when disable required shipping

### ISSUE THREAD

**Issue by soulge** [opencart/opencart#3397]
because all of my products does not require shipping option, after I disable them, I found the step number dose not re-calculate on the checkout page.
The step number is 
Step 1,
Step 2,
Step 5,
Step 6,

**Comment by OpenCartAddons** [comment]
This has been going on since the intitial launch of OpenCart v1.5.

Personally, I think the step numbers should be just completely removed as they're not necessary.  Steps only make sense when the customer must go through multiple pages for a checkout.

**Comment by OpenCartAddons** [comment]
I've created a pull request that will reassign the checkout step numbers based on whether or not shipping is required. #3435

**Comment by danielkerr** [comment]
fixed with opencartaddons pull
