### ISSUE TITLE
SQL injection BUG 

### ISSUE THREAD

**Issue by mrg123** [opencart/opencart#3398]
it's unhappy for me,
in morning, i found my site attach form hacker.and it's too later when i found it, and hacker succeed.
funck

i can't fix it ,help ...
i put all i found evidence

ex:
index.php?route=tool/captcha' OR (SELECT 1 FROM (SELECT 1) A WHERE SLEEP(0.000)=0)#'

and it will error in mysql ,i feel hacker succeed it in my sql.

error report:

Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''' at line 1<br />Error No: 1064<br />SELECT * FROM my_url_alias WHERE `query` = 'tool/captcha' OR (SELECT 1 FROM (SELECT 1) A WHERE SLEEP(0.000)=0)' in /www/web/default/public_html/system/library/db/mysqli.php on line 41

**Comment by danielkerr** [comment]
"and it will error in mysql ,i feel hacker succeed it in my sql."

YOU ARE AN IDIOT!!! THERE IS NO HACK!

DO NOT POST HERE AGAIN!!!
