### ISSUE TITLE
Banner Sort Order Issue

### ISSUE THREAD

**Issue by ocjohncarter** [opencart/opencart#3399]
Banner Sort Order related textbox not showing in add banner scheme.

please check the following snapshot.
![banners](https://cloud.githubusercontent.com/assets/14884678/10156462/ea2a37e0-669e-11e5-92ea-3ef77ecf0554.png)

**Comment by angboontiong79** [comment]
how can i solve this issue ?
which file i need to amend ?

**Comment by ocjohncarter** [comment]
Hello,

Please open design/banner controller & you can find that when new banner
image add then it will not display the text box for short order.

So please replace following line

html += '  <td class="text-right" *style="width: 10%;*><input type="text"
name="banner_image[' + image_row + '][sort_order]" value=""
placeholder="<?php echo $entry_sort_order; ?>" class="form-control"
/></td>';

- Above is old code which show currently opencart 2.0.1.x version, please
check below code.

html += '  <td class="text-right" *style="width: 10%;"*><input type="text"
name="banner_image[' + image_row + '][sort_order]" value=""
placeholder="<?php echo $entry_sort_order; ?>" class="form-control"
/></td>';

*In above both code please compare highlighted portion & once below code is
replace with old one then issue will be solved.*

Thanks & Regards,

John Carter.


On Sun, Feb 14, 2016 at 8:04 AM, angboontiong79 <notifications@github.com>
wrote:

> how can i solve this issue ?
> which file i need to amend ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/3399#issuecomment-183801874>.
>



-- 
Thank You,
John Carter

**Comment by ocjohncarter** [comment]
Hello,

- Sorry please by forget previous mail.

Please open design/banner View or tpl file & you can find that when new
banner image add then it will not display the text box for short order.

So please replace following line

html += '  <td class="text-right" *style="width: 10%;*><input type="text"
name="banner_image[' + image_row + '][sort_order]" value=""
placeholder="<?php echo $entry_sort_order; ?>" class="form-control"
/></td>';

- Above is old code which show currently opencart 2.0.1.x version, please
check below code.

html += '  <td class="text-right" *style="width: 10%;"*><input type="text"
name="banner_image[' + image_row + '][sort_order]" value=""
placeholder="<?php echo $entry_sort_order; ?>" class="form-control"
/></td>';

*In above both code please compare highlighted portion & once below code is
replace with old one then issue will be solved.*

Thanks & Regards,

John Carter.

On Sun, Feb 14, 2016 at 11:11 AM, John Carter <ocjohncarter@gmail.com>
wrote:

> Hello,
>
> Please open design/banner controller & you can find that when new banner
> image add then it will not display the text box for short order.
>
> So please replace following line
>
> html += '  <td class="text-right" *style="width: 10%;*><input type="text"
> name="banner_image[' + image_row + '][sort_order]" value=""
> placeholder="<?php echo $entry_sort_order; ?>" class="form-control"
> /></td>';
>
> - Above is old code which show currently opencart 2.0.1.x version, please
> check below code.
>
> html += '  <td class="text-right" *style="width: 10%;"*><input
> type="text" name="banner_image[' + image_row + '][sort_order]" value=""
> placeholder="<?php echo $entry_sort_order; ?>" class="form-control"
> /></td>';
>
> *In above both code please compare highlighted portion & once below code
> is replace with old one then issue will be solved.*
>
> Thanks & Regards,
>
> John Carter.
>
>
> On Sun, Feb 14, 2016 at 8:04 AM, angboontiong79 <notifications@github.com>
> wrote:
>
>> how can i solve this issue ?
>> which file i need to amend ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/opencart/opencart/issues/3399#issuecomment-183801874>
>> .
>>
>
>
>
> --
> Thank You,
> John Carter
>



-- 
Thank You,
John Carter

**Comment by annia316** [comment]
In case someone else is wondering:
The right file that needs to be changed is admin/view/template/design/banner_form.tpl
