### ISSUE TITLE
Upgrade script column modidy

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#3406]
install/model/upgrade.php line 281:
$sql = "ALTER TABLE `" . $table['name'] . "` CHANGE `" . $field['name'] . "` `" . $field['name'] . "` " . strtoupper($field['type']);

Can this do also this way:
$sql = "ALTER TABLE `" . $table['name'] . "` MODIFY `" . $field['name'] . "` "  . strtoupper($field['type']);

**Comment by danielkerr** [comment]
if it works don't change.
