### ISSUE TITLE
Admin customer edit form IP not displayed correctly

### ISSUE THREAD

**Issue by mallone** [opencart/opencart#3407]
OC 2.1.0.0_rc1 
In customer edit under the IP tab below the IP header there is a clickable link that is suppose to send you to www.geoiptool.com. This section does not display the IP correctly and when clicked throws an error: 

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

![cust-edit-ip-issue](https://cloud.githubusercontent.com/assets/2141568/10195270/b33efc7c-6741-11e5-995b-fabafd76935f.png)

**Comment by danielkerr** [comment]
because its localhost
