### ISSUE TITLE
Payment Method "terms" error code fix $payment_method['terms']

### ISSUE THREAD

**Issue by agtt** [opencart/opencart#3408]
catalog\view\theme\default\template\checkout\payment_method.tpl line 16:

 <?php if ($payment_method['terms']) { ?>
    (<?php echo $payment_method['terms']; ?>)
    <?php } ?>

Can this do also this way:

 <?php if(array_key_exists('terms',$payment_method)){?>
    (<?php echo $payment_method['terms']; ?>)
    <?php } ?>

**Comment by danielkerr** [comment]
not required as terms is on every payment gateway.

also !empty is a better choice.

**Comment by dinumarathe** [comment]
@danielkerr !empty means..like this or something......
<?php if(array_key_exists('!empty',$payment_method)){?>
(<?php echo $payment_method['!empty']; ?>)
<?php } ?>

I was tried @agtt  above code it works but it still showing error after ccavenue payment 
Error like that  - Notice :undefine index : encResp in home/myproject/public_html/catalog/controller/ccavenuepay.php on line 165 
warnings: mdecript_generic() An empty script was passed in /home/myproject/public_html/admin/controller/common/cbdom_main.php on line 117
