### ISSUE TITLE
the upgrade script is not working (2.0.3.1 to 2.1.0.0)

### ISSUE THREAD

**Issue by opencart-russia** [opencart/opencart#3411]
May be https://github.com/opencart-russia/opencart/commit/1862532aad1dd370e36e70b3b0162412107ecc51#diff-2127205952db0f9814229ffe6873e588

And please, test repeat upgrade (2.1.0.0 to 2.1.0.0). I see notice
```
Notice: Error: Can't DROP 'cart_id'; check that column/key exists<br />Error No: 1091<br />ALTER TABLE `oc_cart` DROP INDEX `cart_id` 
```

**Comment by Newman101** [comment]
The index cart_id has AUTO_INCREMENT property. I think the relationship needs to be removed in the upgrade script before dropping the index?

**Comment by danielkerr** [comment]
should be fixed in latest commit

the table should always be created if you have gone through the upgrade process even if it fails.
