### ISSUE TITLE
when i install import/export tool in opencart 2.3.0.1 diplay this error..so suggest me the best solution

### ISSUE THREAD

**Issue by luv777** [opencart/opencart#3418]
![photo_2015-10-05_14-24-59](https://cloud.githubusercontent.com/assets/14974550/10276435/01d318a8-6b6d-11e5-9818-60d30977f1fe.jpg)

**Comment by danielkerr** [comment]
i think you dont have the correct permissions on the server. please post this in the forums as it seems to be extension specific.

**Comment by luv777** [comment]
Hello Mr. Danielkeer,

I had checked and make the correct permissions on the server and post as well in forums but nobody solve this.

Thank You.
