### ISSUE TITLE
Inconsistent zone data for zones in Austria

### ISSUE THREAD

**Issue by hoermannklaus** [opencart/opencart#3420]
When I look at the install sql file in "upload/install/opencart.sql" I see the zone entries for the country Austria (id = 14).
They are written in German and have Umlauts (ä,ö,ü). The Umlauts in the zones "Niederösterreich" and "Oberösterreich" where converted in html entities, the Umlaut in "Kärnten" was not.

I suggest to stay with one of the 2 options. And not using both.

I dont see any reason not to use the Umlauts, so I would change the existing html entities back to Umlauts.

Thanks

**Comment by osworx** [comment]
Basically you are correct (use either the one or the other method), but finally the result is counting and that does it since 5 years.
So - who cares really about that?

**Comment by hoermannklaus** [comment]
If you dont care, why bothering?

I made a pull request.

**Comment by danielkerr** [comment]
ok changed
