### ISSUE TITLE
opencart-2.1.0.1 Upgrade is broken

### ISSUE THREAD

**Issue by ebmarques** [opencart/opencart#3424]
Upgraded from opencart-2.0.3.1 to opencart-2.1.0.1 and noticed:
- table oc_api keep firstname and lastname (column name is not created)
- table oc_cart is not created
Also having an error from admin/controller/dashboard/activity.php line 19.

Saw no errors with a clean install.

**Comment by stevebassi** [comment]
I noticed these differences on a fresh install compared to an upgraded installation. which produces the following error

Notice: Error: Table 'ourshop.oc_cart' doesn't exist
Error No: 1146
DELETE FROM oc_cart WHERE customer_id = '0' AND date_added < DATE_SUB(NOW(), INTERVAL 1 HOUR) in system/library/db/mysqli.php on line 41
Fatal error: Call to undefined method Loader::library() in catalog/controller/journal2/settings.php on line 20

oc_api changes from username and password to key and is not updated.
oc_api_ip not created
oc_api_session not created
oc_cart not created
oc_customer_wishlist not created
oc_customer change `token` varchar(255) NOT NULL, to `token` text NOT NULL,
oc_customer_ban_ip should be removed

**Comment by pnair39** [comment]
Upgrade does not work at all receiving multiple errors, confirmed same as above.

**Comment by matrunchyk** [comment]
The same for me

**Comment by xguntis** [comment]
same here - tried to upgrade from 2.0.3.1 and 2.0.2.0. There are mysql errors after upgrade.

**Comment by matrunchyk** [comment]
To quick fix it, run this SQL:
`CREATE TABLE `oc_cart` (
  `cart_id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_id` int(11) NOT NULL,
  `session_id` varchar(32) NOT NULL,
  `product_id` int(11) NOT NULL,
  `recurring_id` int(11) NOT NULL,
  `option` text NOT NULL,
  `quantity` int(5) NOT NULL,
  `date_added` datetime NOT NULL,
  PRIMARY KEY (`cart_id`),
  KEY `cart_id` (`customer_id`,`session_id`,`product_id`,`recurring_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;`

**Comment by pnair39** [comment]
Attempting to load page:
===========================
Notice: Use of undefined constant DB_PORT - assumed 'DB_PORT' in /home/amillio8/public_html/Demo/index.php on line 31

Warning: mysqli::mysqli() expects parameter 5 to be long, string given in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 7

Warning: mysqli::set_charset(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 14

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 15

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 46

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Notice: Trying to get property of non-object in /home/amillio8/public_html/Demo/index.php on line 41

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Notice: Trying to get property of non-object in /home/amillio8/public_html/Demo/index.php on line 50

Warning: Invalid argument supplied for foreach() in /home/amillio8/public_html/Demo/index.php on line 50

Notice: Trying to get property of non-object in /home/amillio8/public_html/Demo/index.php on line 58

Warning: fopen(/home/amillio8/public_html/Demo/system/logs/): failed to open stream: Is a directory in /home/amillio8/public_html/Demo/system/library/log.php on line 6

===========================================================================
Immediately after install:
============================================================================
Notice: Use of undefined constant DB_PORT - assumed 'DB_PORT' in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 139

Warning: mysqli::mysqli() expects parameter 5 to be long, string given in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 7

Warning: mysqli::set_charset(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 14

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 15

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Notice: Trying to get property of non-object in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 146

Warning: Invalid argument supplied for foreach() in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 146

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Notice: Trying to get property of non-object in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 314

Warning: Invalid argument supplied for foreach() in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 314

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Notice: Undefined index: oc_customer_group in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 332

Warning: in_array() expects parameter 2 to be array, null given in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 332

Notice: Undefined index: oc_product_option in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 348

Warning: in_array() expects parameter 2 to be array, null given in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 348

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Notice: Trying to get property of non-object in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 357

Warning: Invalid argument supplied for foreach() in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 357

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Notice: Trying to get property of non-object in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 368

Warning: Invalid argument supplied for foreach() in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 368

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Notice: Trying to get property of non-object in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 391

Warning: Invalid argument supplied for foreach() in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 391

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Notice: Trying to get property of non-object in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 402

Warning: Invalid argument supplied for foreach() in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 402

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Notice: Trying to get property of non-object in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 425

Warning: Invalid argument supplied for foreach() in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 425

Warning: mysqli::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 19

Warning: DB\MySQLi::query(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 21

Notice: Trying to get property of non-object in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 441

Warning: Invalid argument supplied for foreach() in /home/amillio8/public_html/Demo/install/model/upgrade.php on line 441

Warning: Cannot modify header information - headers already sent by (output started at /home/amillio8/public_html/Demo/install/model/upgrade.php:139) in /home/amillio8/public_html/Demo/system/library/response.php on line 12

Warning: mysqli::close(): Couldn't fetch mysqli in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 58

**Comment by pnair39** [comment]
Applied the following to config.php files: 

simple fix for upgrade to 2.1.0.1
THERES only 2 THINGS WRONG THAT NEEDS CHANGING
add " define('DB_PORT', '3306'); " to config.php and admin/config.php on the last line of each file
then go to your-site/install (upgrade should be in darker color to finished)
click continue and it will upgrade perfectly and you will get upgrade successful

Also had to run:
=============
CREATE TABLE `oc_cart` (
`cart_id` int(11) NOT NULL AUTO_INCREMENT,
`customer_id` int(11) NOT NULL,
`session_id` varchar(32) NOT NULL,
`product_id` int(11) NOT NULL,
`recurring_id` int(11) NOT NULL,
`option` text NOT NULL,
`quantity` int(5) NOT NULL,
`date_added` datetime NOT NULL,
PRIMARY KEY (`cart_id`),
KEY `cart_id` (`customer_id`,`session_id`,`product_id`,`recurring_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


However I am receiving the following error:
==================================
Fatal error: Call to undefined method ModelToolOnline::whosonline() in /home/amillio8/public_html/Demo/system/modification/catalog/controller/common/footer.php on line 80

**Comment by zang** [comment]
Same as stevebassi  that I got same Fatal error: Call to undefined method Loader::library(). 

Wasted 3 hours to go through the process and manually fix all the known issues. Just wondering if the upgrade process has been tested at all?

**Comment by pnair39** [comment]
Disabled System>Settings>Account: Customers Online to No 
================================================
To get home page to partial show up except for the content home page every other pages are click able except for home page content. 


Logging into Admin: 
==================
Warning: vsprintf(): Too few arguments in /home/amillio8/public_html/Demo/admin/controller/dashboard/activity.php on line 19Warning: vsprintf(): Too few arguments in /home/amillio8/public_html/Demo/admin/controller/dashboard/activity.php on line 19Warning: vsprintf(): Too few arguments in /home/amillio8/public_html/Demo/admin/controller/dashboard/activity.php on line 19Warning: vsprintf(): Too few arguments in /home/amillio8/public_html/Demo/admin/controller/dashboard/activity.php on line 19Warning: vsprintf(): Too few arguments in /home/amillio8/public_html/Demo/admin/controller/dashboard/activity.php on line 19

**Comment by pnair39** [comment]
According to Daniel Kerr: need to empty the activity table and let the system add new ones. i have already added a fix in the master branch but you would have to update again. 

This worked for me.

**Comment by pnair39** [comment]
Anyone fix the upgrade process or know anyone that has?

**Comment by elorac** [comment]
I would like to know if there's an upgrade fix too.  I'm getting all those same errors on the upgrade attempt. I had to revert back to 2.0.3.1 since the 2.1.0.1 left me with a broken system.  Notably these types of errors that pnair39 got above:
Notice: Use of undefined constant DB_PORT - assumed 'DB_PORT' in /home/xxxx/public_html/yyyy/install/model/upgrade.php on line 139

Warning: mysqli::mysqli() expects parameter 5 to be long, string given in /home/xxxx/public_html/yyyy/system/library/db/mysqli.php on line 7 .....

**Comment by merqlove** [comment]
Lol, how can you release such upgrade? Same bugs with DB.
Maybe we can have some patches for every release, if so?

**Comment by merqlove** [comment]
Short fix for SQL hackers.

```sql
SET sql_mode = '';

--
-- Table structure for table `oc_api`
--

DROP TABLE IF EXISTS `oc_api`;
CREATE TABLE `oc_api` (
  `api_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `key` text NOT NULL,
  `status` tinyint(1) NOT NULL,
  `date_added` datetime NOT NULL,
  `date_modified` datetime NOT NULL,
  PRIMARY KEY (`api_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `oc_api_ip`
--

DROP TABLE IF EXISTS `oc_api_ip`;
CREATE TABLE `oc_api_ip` (
  `api_ip_id` int(11) NOT NULL AUTO_INCREMENT,
  `api_id` int(11) NOT NULL,
  `ip` varchar(40) NOT NULL,
  PRIMARY KEY (`api_ip_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `oc_api_session`
--

DROP TABLE IF EXISTS `oc_api_session`;
CREATE TABLE `oc_api_session` (
  `api_session_id` int(11) NOT NULL AUTO_INCREMENT,
  `api_id` int(11) NOT NULL,
  `token` varchar(32) NOT NULL,
  `session_id` varchar(32) NOT NULL,
  `session_name` varchar(32) NOT NULL,
  `ip` varchar(40) NOT NULL,
  `date_added` datetime NOT NULL,
  `date_modified` datetime NOT NULL,
  PRIMARY KEY (`api_session_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Table structure for table `oc_cart`
--

DROP TABLE IF EXISTS `oc_cart`;
CREATE TABLE `oc_cart` (
  `cart_id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_id` int(11) NOT NULL,
  `session_id` varchar(32) NOT NULL,
  `product_id` int(11) NOT NULL,
  `recurring_id` int(11) NOT NULL,
  `option` text NOT NULL,
  `quantity` int(5) NOT NULL,
  `date_added` datetime NOT NULL,
  PRIMARY KEY (`cart_id`),
  KEY `cart_id` (`customer_id`,`session_id`,`product_id`,`recurring_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Table structure for table `oc_customer_wishlist`
--

DROP TABLE IF EXISTS `oc_customer_wishlist`;
CREATE TABLE `oc_customer_wishlist` (
  `customer_id` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `date_added` datetime NOT NULL,
  PRIMARY KEY (`customer_id`,`product_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

ALTER TABLE `oc_customer` CHANGE COLUMN `token` `token` text NOT NULL;

DROP TABLE IF EXISTS `oc_customer_ban_ip`;
```

**Comment by merqlove** [comment]
http://www.opencart.com/index.php?route=extension/extension/info&token=f77e468ab047c531640b890c3aa25f2c&extension_id=24454

**Comment by akamri300** [comment]
Now I learn the opencart, and the update failed. I read the description of the installation, but I do not understand. Could you describe a little more detail on what to do

thank you!

**Comment by merqlove** [comment]
@akamri300 This is OCMOD extension.

So, your steps:

1. Download
2. Go to admin/modules, extensions installer
3. Upload current extension.
4. Refresh modificators cache (maybe redundant).

**Comment by akamri300** [comment]
error message
Directory containing files to be uploaded could not be found!

**Comment by merqlove** [comment]
Ok, This is OC storage bug(wrong ZIP encoding)., have no time to play with it.
Try this., here ZIP file with right encoding.
https://www.dropbox.com/s/dehkqbr7d17adk1/opencart_2_1_0_1_upgrade_fix.ocmod.zip?dl=0

**Comment by RobinEd** [comment]
The modules on the front page are disabled and don't have names after the upgrade. It also seems to have deleted all the content in my HTML modules. This upgrade is dangerous: not only does it NOT work, it deletes stuff! BEWARE! You may have to rebuild your entire site!

**Comment by glpunk** [comment]
Any clue how to fix home modules error?  In the admin banners are enabled with the same data, but not showed in home.

Thank you

**Comment by glpunk** [comment]
Sorry I figured out, should be reconfigured in the admin -> modules

**Comment by haxcop** [comment]
do not upgrage for 2.1 it's to buggy... wait for the next one...

**Comment by blmg911** [comment]
@haxcop A fresh install seems to be fine, maybe try this if possible

**Comment by danielkerr** [comment]
ok i have updated the upgrade scrip and should fix all mentioned above.

**Comment by alancheongkl** [comment]
Hi @danielkerr , I'm still facing the error 
"Fatal error: Call to undefined function token() " at /admin/model/user/user.php on line 12

and also some other place, example : 
catalog/model/account/customer.php on line 114

I need to replace the token() with = substr(md5(uniqid(rand(), true)), 0, 9) to fix the error.

Would appreciate if you could advise the solution for this.

**Comment by saboorulhassan** [comment]
Plzz help me 
Fatal error: Call to undefined method Loader::library() in /home/-/public_html/catalog/controller/journal2/settings.php on line 20 ?

**Comment by alancheongkl** [comment]
How to solve the following error after upgrade ?

oc_google_base_category_to_category' doesn't exist
