### ISSUE TITLE
Does title instead Page URL display of in Category Page.

### ISSUE THREAD

**Issue by harnishdesign** [opencart/opencart#3430]
Does title instead Page URL display of in Category Page.
I am not sure. but, I think, Should be Current Category name in title. but, Here, does display category page url.
is this any issue here? please see following screenshot. 

Thanks.

![screenshote](https://cloud.githubusercontent.com/assets/2634085/10339139/7bfd9ad4-6d27-11e5-97a7-3c708eb66118.jpg)

**Comment by OpenCartAddons** [comment]
This is due to missing meta titles in the installation script.  I've added them here #3432

**Comment by Tangol** [comment]
Closed by https://github.com/opencart/opencart/commit/6ea12cb5d4f974fc97ba2e5c433e7d52695d051b ?

**Comment by OpenCartAddons** [comment]
Yes

**Comment by Ergotron-Mexico** [comment]
thanks
