### ISSUE TITLE
Notice: Undefined variable json in \opencart\admin\controller\sale\order.php on line 2221

### ISSUE THREAD

**Issue by srayner** [opencart/opencart#3436]
I've seen posts on forums indicating others have hit this issue, but I cannot find a solution that works for me.

Regardless I would say this is a bug. If it is a config issue there should be a better error message.

example forum post; http://forum.opencart.com/viewtopic.php?t=145923&p=564670

**Comment by OpenCartAddons** [comment]
This controller file has been rewritten for the latest release.  Try updating to OpenCart v2.1.0.1 as the issue should be resolved.

Cheers,
Joel.
