### ISSUE TITLE
OC 2.0.3.1 - Editing order history throws "syntaxerror: Unexpected end of input"

### ISSUE THREAD

**Issue by rckani** [opencart/opencart#3438]
Opencart Version : 2.0.3.1

I'm getting an error while trying to process the order. Basically, Editing order history throws "syntaxerror: Unexpected end of input".

I have hosted my service with a shared host service provider.

**Comment by OpenCartAddons** [comment]
I believe this issue has already been resolved in the v2.1.0.1 release.
