### ISSUE TITLE
Permissions on the directories list below

### ISSUE THREAD

**Issue by Sm00dE** [opencart/opencart#3439]
/home/*****/domains/*******/public_html/system//storage/cache/

double // on link directory

**Comment by danielkerr** [comment]
these are the 2 parts where cache directory path is added to the config

$output .= 'define(\'DIR_CACHE\', \'' . DIR_OPENCART . 'system/storage/cache/\');' . "\n";

$output .= 'define(\'DIR_CACHE\', \'' . DIR_OPENCART . 'system/storage/cache/\');' . "\n";

I can not see how its possbile to have //

**Comment by Sm00dE** [comment]
danielkerr when i download .tar file of opencart 2.1.0.1 it works for me perfect without 2 other problems.
