### ISSUE TITLE
After installation fresh store problem

### ISSUE THREAD

**Issue by Sm00dE** [opencart/opencart#3440]
After i install new one Opencart 2.1.0.1 version adminsitration panel work fine but store /index.php is just blank.

**Comment by Sm00dE** [comment]
Found on Adminsitration > Settings > General  > Template (no template)

**Comment by Stoffel79** [comment]
I have just the same problem, after upgrade from 2.0.3.1
Blank store, can't login in admin ... wrong name/pasword
No brands found, no products, no catefories found ...

**Comment by danielkerr** [comment]
works fine for me. I can not replicate. also you have not provided enough information.

the blank index.php could be a bad upload.
