### ISSUE TITLE
2.1.0.1 Undefined variable: entry_export

### ISSUE THREAD

**Issue by maxgioie** [opencart/opencart#3459]
admin/controller/tool/backup.php
$data['entry_export'] = $this->language->get('entry_export');

admin/language/english/tool/backup.php
$_['entry_export']     = 'Tables:';

**Comment by OpenCartAddons** [comment]
Already submitted a bug fix for this https://github.com/opencart/opencart/pull/3433

The wrong variable was used in the template file.

Cheers,
Joel.
