### ISSUE TITLE
Google reCAPTCHA checkout register error

### ISSUE THREAD

**Issue by eintnohick** [opencart/opencart#3462]
Google reCAPTCHA when registering on checkout is buggy. Getting this error...

```PHP Notice:  Undefined index: g-recaptcha-response in C:\xampp\htdocs\demo-oc2.1\catalog\controller\captcha\google_captcha.php on line 32```

The recaptcha doesn't display and this error occurs...

![capture](https://cloud.githubusercontent.com/assets/1884871/10412962/0485655e-6f66-11e5-972a-f6652c6e3b6e.PNG)

**Comment by danielkerr** [comment]
just spotted this. im 100% i dfid not upload the google captcha with a telephone field
