### ISSUE TITLE
Shopping Cart  and Check outError

### ISSUE THREAD

**Issue by depler2** [opencart/opencart#3463]
When you go to view shopping cart or checkout I get this message
Notice: Error: Could not load template /home/original/public_html/catalog/view/theme/default/template/module/pp_layout.tpl! in /home/original/public_html/vqmod/vqcache/vq2-system_engine_controller.php on line 9

**Comment by danielkerr** [comment]
I think pp_layout was changed to pp_login

maybe the extension you are using needs updating.

i woudl need to know the exact name of file calling the controller.
