### ISSUE TITLE
Where $this->load->library in system/engine/loader.php

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#3469]
These methods exist :

 $this->load->view
 $this->load->helper
 $this->load->view
 $this->load->model

$this->load->library - is absent.

But, for example
catalog/model/openbay/amazon_order.php
		$this->load->library('log'); - What is it?

**Comment by danielkerr** [comment]
its been removed.

james is responsible of openbay pro. i have removed the $this->load->library as the log is already pre loaded.

**Comment by boristhebulletdodger** [comment]
What about $this->load->library('encryption'); ?

Since what version did opencart dropped the load->library()?

thanks

**Comment by jamesallsup** [comment]
// Autoloader
function library($class) {
	$file = DIR_SYSTEM . 'library/' . str_replace('\\', '/', strtolower($class)) . '.php';
	if (is_file($file)) {
		include_once(modification($file));
		return true;
	} else {
		return false;
	}
}

Library files are autoloaded, please review the code before posting bugs. Just use new LibraryClassName();

**Comment by boloindia** [comment]
@jamesallsup In that case shall I remove the code $this->load->library('encryption') from ccavenuepayment controller?
