### ISSUE TITLE
PayPal not comminucating with my site. 

### ISSUE THREAD

**Issue by ThumbRC** [opencart/opencart#3473]
I am receiving orders and payments through my website. However, PayPal is not communicating with the site. All of the orders are in the missing orders section. The cart never gets the status changed even though the payments go through successfully. I do not receive any email notifications that I have orders as they are "missing". 

casterracingmi.com is my site.

**Comment by botonakis** [comment]
You will need to set up IPN response url inside Paypal to url : http://www.casterracingmi.com/?route=payment/pp_standard/callback

or fixe your php error notices that you probably have.

**Comment by danielkerr** [comment]
it works for many people. the ipnj repsonse is already setup in the data thats sent to paypal
