### ISSUE TITLE
admin/controller/common/filemanager: variable '$filename' might have not been defined

### ISSUE THREAD

**Issue by matrunchyk** [opencart/opencart#3476]
Hello, guys.

I've noticed that `$filename` variable [might have not been defined](https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/filemanager.php#L275) within a `upload` method.
Could you please make a small refactoring here?

Also, [there are](https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/filemanager.php#L223) two [the same](https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/filemanager.php#L274) `if (!$json) {` cases goes in a row. Wouldn't it be more clear to join it?

Thank you very much!

**Comment by danielkerr** [comment]
Also, there are two the same if (!$json) { cases goes in a row. Wouldn't it be more clear to join it?

no because the first one needs to check if there are any errors

**Comment by danielkerr** [comment]
im closing this.

if there is an error create a new issue and post the exact error code.
