### ISSUE TITLE
Why not default lowercase URL

### ISSUE THREAD

**Issue by fourroses666** [opencart/opencart#3478]
http://forum.opencart.com/viewtopic.php?f=112&t=146486

**Comment by danielkerr** [comment]
not required. and the issue is only happening because tyou are using a 3rd party script to genrate the keywords for you.

**Comment by fourroses666** [comment]
Your rite, my bad.

I did not install anything yet, but was looking for a good solution to get nice (SEO) URLs.
OC1 didn't had an out of the box solution. Seems OC2 has an setting (usage .htaccess) for the clean category / product pages URLs.
