### ISSUE TITLE
Email issue -  email not sent 1.5.3 to 1.5.4.1

### ISSUE THREAD

**Issue by capte** [opencart/opencart#348]
Had to remove $this->newline in the system\library\mail.php to get it working again !

Before : 
$header .= 'Content-Type: multipart/related; boundary="' . $boundary . '"' . $this->newline . $this->newline;

After : 
$header .= 'Content-Type: multipart/related; boundary="' . $boundary . '"' . $this->newline;

Works fine now on our side.

**Comment by magentodevelop** [comment]
Hello There

mail function not working opencart 1.5.2 we have set setting of mail function from admin panel but not got mail to customer please suggest how we can do it

**Comment by munirasim** [comment]
It not necessarily be the fault of Opencart. Many email servers have now implemented SPF, DKIM and DMARC policies and to comply them you must use an email address which is created on the domain name of your store i.e. if your domain name is 'example.com', you should create a domain name 'anyName@example.com' 

When setting email under MAIL tab, you may use MAIL protocol and in email field put -f OR -F before email address.

If it is not working for other reason, please check error log and share email related entry.

**Comment by magentodevelop** [comment]
Hello munirasim

Thanks for quick response

We have used this mail setting please check following link
http://imgur.com/a/m8B2f

Please let me know how we can do it

**Comment by munirasim** [comment]
- You may try -f (note lower case)
- Make sure under STORE tab you use the same email address
- When you choose MAIL protocol only first two entries matter under MAIL tab and you may remove entries from fields that start with word SMTP

**Comment by magentodevelop** [comment]
Yes, We are using same email on general tab and we have setup smtp mail function but not got any mail.we have try all way but i am not sure issue which side.

**Comment by munirasim** [comment]
Forget SMTP and use MAIL protocol only i.e. under MAIL tab choose MAIL in first field and then in the next field enter your email address like "-fanyname@example.com" and clear all other fields

I assume that you have created your email address at your web host and you are not using third party email server

After doing this go to CONTACT form and send an email to see if you receive it. I tell you the next step after seeing results of this action.

**Comment by magentodevelop** [comment]
Hello 

We have already created same email on cpanel and we have clear all the fields please check following link
http://imgur.com/a/7P1Ax

**Comment by munirasim** [comment]
It' not a general issue, you may check my profile to contact me privately and I can fix it.

**Comment by munirasim** [comment]
It turned out that the issue was with email server (inbox full) and not the Opencart. Please close this thread.
