### ISSUE TITLE
pp_payflow.php variable typo

### ISSUE THREAD

**Issue by xenez** [opencart/opencart#3484]
I am using OC 2.0.3.1 and on line 38 of admin/view/template/payment/pp_payflow.php a variable is named $help_usere instead of $help_user

**Comment by OpenCartAddons** [comment]
Submitted fix.  Thanks for reporting it.

Cheers,
Joel.

**Comment by ahuvainc** [comment]
This isn't the only issue rendering payflow not functional. Please check it. 
Does anyone have a working version ?
