### ISSUE TITLE
Edit order

### ISSUE THREAD

**Issue by wtfmrpresident** [opencart/opencart#3487]
Hi
Editing order I cannot save it if the total quantity of product in stock before order was 1.
Why programm tries subtract quantity again after confirm order?

When customer confirms order programm must subtract confirmed quantity from stock. When manager editing order he cannot save it because product already not available in stock. ( ? ) it's mistake, because product must be available for specified customer in ordered quantity

**Comment by danielkerr** [comment]
version? should i guess?

i think, the issue you are talking about is down to your settings or you need to update to the latest.
