### ISSUE TITLE
Forget email admin

### ISSUE THREAD

**Issue by interspiresource** [opencart/opencart#3488]
$message .= $this->url->link('common/reset', 'code=' . $code, 'SSL') . "\n\n";

This will be broken link
admin/index.php?route=common/reset&amp;code=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
So cannot reset password
Because the Characters "&amp" also broken in opencart v2.0.3.1

**Comment by danielkerr** [comment]
@interspiresource

dont post here again! you are vietnamese scammer! who hasd bought from opencart using stolen card information as well as piracy! you want me to post all the fino i have about you? no problem!

**Comment by interspiresource** [comment]
Hi Kerr.
I also have all the info about you.
All info your father,your mother and your grand father
Do you want me post?
No problem!

**Comment by danielkerr** [comment]
Nguyen Thanh Son
interspire.vn@gmail.com

**Comment by danielkerr** [comment]
expect a DMCA take down for interspiresource

**Comment by danielkerr** [comment]
more information about this sumbag here:

Scumbags details

Nguyen Thanh Son
interspire.vn@gmail.com 

also works with

Hoang Dung
233 Bac Kinh
Ha Noi 17000

contact: Hoang Dung
address: 5 Pham Hung - Cau Giay
address: 17000 Ha Noi
address: HN
country: VN
phone: +84 1213219925
e-mail: vietzippo.com@gmail.com 

Mail: opencart.com@gmail.com 
Yahoo: opcvn_mod
Mobile: 0943-405-833

01/12/2014 07:37 Sent Hoang Trung Dung Processed -7.43 -743.35 
Transaction ID: 1316028631
Recipient's email: mastercart.net@gmail.com 
More details:

amaze admin@opencartz.net 
interspire.com info@opencartdev.com 
kangoc luuminhkhanh@hotmail.com 
maslo maslo@maslo.com 
matamko matamko.leo@gmail.com 
max opencart info@bonsai.az 
newbag sales@newbag.pro 
novapro novathemepro@gmail.com 
opencart2x admin@opencartx.net 
opencart77 opencart77@gmail.com 
opencartips admin@opencartips.com 
opencartpm admin@opencart.pm 
opencartznet info@opencartclub.net 
openxcart admin@openxcart.com 
opz cheryl.angelo@hotmail.com 
vdc haihuyenpham@yahoo.com 

some of the above emails are fake.

hes also listed here:

http://opencartvn.com/forum/Thread-modu ... -%E1%BA%A1 

I actually have much more details
OpenCart®

**Comment by danielkerr** [comment]
http://opencartvn.com/forum/User-makalot
