### ISSUE TITLE
Guest Checkout

### ISSUE THREAD

**Issue by Tangol** [opencart/opencart#3490]
During `Guest Checkout`, nothing happens when you click on `Confirm Order`.
You don't get any confirmation message and the cart doesn't update (product remains in the cart even after page refresh).
![guest1](https://cloud.githubusercontent.com/assets/3336728/10481978/163b686a-727d-11e5-815b-05bfec62dae7.png)

The order registers fine in the admin, with Pending status.

v2.1.0.2_rc - rev https://github.com/opencart/opencart/commit/fbc6396bd269389b1da097fe7fb50c1cc646aa1a
Using `Guest Checkout` `Basic Captcha`

**Comment by danielkerr** [comment]
works fine for me.

**Comment by danielkerr** [comment]
its possible your email settings are incorrect. check your error log

**Comment by Tangol** [comment]
True, i was testing in localhost. Thanks!
