### ISSUE TITLE
The side navigation isn't opening in Firefox

### ISSUE THREAD

**Issue by fourroses666** [opencart/opencart#3491]
The side navigation isn't opening.
Seems it doesn't work for Firefox and does for other browsers.

Firebug tracker says:
```NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached```

When looking further for this issue it seems this is the reason:
https://bugzilla.mozilla.org/show_bug.cgi?id=1090567

Maybe there is a workarround, else wait till the bug is fixed in Firefox?

**Comment by danielkerr** [comment]
ok just tested int he desktop firefox and its working well.

so wasted 5 mins checking while i'm gusessing your using mobile

**Comment by fourroses666** [comment]
no, I installed a clean opencart 2.1.0.1 (and also updated to 2.1.0.2_rc) on desktop Win 7.
I use FF 41.0.1

![error](https://cloud.githubusercontent.com/assets/523389/10487757/dd7bf3c8-7295-11e5-9e26-e1d534e8069b.jpg)

**Comment by fourroses666** [comment]
I gave the wrong link:
http://stackoverflow.com/questions/17460437/firefox-localstorage-reach-maximum-size-while-there-are-only-800-kb-data-in-it

**Comment by OpenCartAddons** [comment]
@fourroses666 I just tried the issue using FireFox 41.0.1 and I'm not able to replicate it either.

Did you try it before applying the 2.1.0.2_rc changes?

**Comment by fourroses666** [comment]
hmm, weird. yes I did check 2.1.0.1. it works on Chrome thow.

**Comment by fourroses666** [comment]
The weird thing is, it works on: http://demo.opencart.com/admin

**Comment by stockmaster** [comment]
@fourroses666 demo site is not updated to 2.1.0.x i dont think

**Comment by fourroses666** [comment]
correct, thats: Version 2.0.0.1b

**Comment by fourroses666** [comment]
I made a testaccount for if someone doesn't beleive me.

**Comment by OpenCartAddons** [comment]
@fourroses666 Sure, send them to me at joel @ opencartaddons . com and I'll take a look.

Regards,
Joel.

**Comment by fourroses666** [comment]
ok!

**Comment by OpenCartAddons** [comment]
@fourroses666 I still wasn't able to replicate the issue.  Have you tried clearing your browser cache?

**Comment by danielkerr** [comment]
do you have multiple sites running on the same domain name? because its saying the local storage for that domain name is full. 

its also possibly a security settings.

**Comment by fourroses666** [comment]
could be the issue. have only 1 oc install but multiple other cms sites on the testdomain. opencartaddons didnt had the issue thow when logging in the site with FF. I think i shall close this issue tomorrow.
