### ISSUE TITLE
Class 'Controllerpayment' not found

### ISSUE THREAD

**Issue by iamdevice** [opencart/opencart#3492]
after update from 2.0.3.1 to 2.1.0.1 i got error

PHP Fatal error:  Class 'Controllerpayment' not found in /***/system/modification/system/engine/loader.php on line 39

Line 39 has code
$controller = new $class($this->registry);

**Comment by iamdevice** [comment]
this error gets when i try view order

**Comment by danielkerr** [comment]
reupload probably a missing the code in the payment file
