### ISSUE TITLE
Paypal standard - opencart 2.0.3.1 - not passing vat or shipping to fields

### ISSUE THREAD

**Issue by Philtrum** [opencart/opencart#3496]
Hi

Im using opencart 2.0.3.1 (although this issue also occurred in 1.5.6)

when a sale is made using paypal standard, opencart feeds paypal with the products and cost, it also passes vat/shippping/packing as as single line, and does not populate paypal's own fields for shipping and vat

see example image
![image](https://cloud.githubusercontent.com/assets/6342899/10511042/88d28276-732e-11e5-9ead-c22d2ee6f5e1.png)

**Comment by Philtrum** [comment]
does anyone else have this issue / can it be reproduced ?

**Comment by danielkerr** [comment]
what disacoutns did you use

**Comment by Philtrum** [comment]
Hi, no discounts were applied
this is a straight purchase from opencart using paypal standard

If you need me to test again/provide more images, please let me know
Thanks
Phil

**Comment by rozhawk** [comment]
Hi. I'm having the same issue.  Did you discover the solution? Can anyone help me out?

**Comment by Philtrum** [comment]
Hi, I've not had a resolution or found a solution for this yet im afraid
Kind Regards
Phil

**Comment by rozhawk** [comment]
Thanks for letting me know.

Regards

Rory

**Comment by haxcop** [comment]
Same issue on my store. 
![screen shot 2015-12-02 at 10 49 27 p m](https://cloud.githubusercontent.com/assets/7826906/11546793/3f0a3c80-9947-11e5-93e5-37f4cc6adcb5.png)

**Comment by danielkerr** [comment]
ok there is no bug here. buyer can see the exact costs on his opencart email.

**Comment by Philtrum** [comment]
This IS a problem or a fix is needed

yes the buyer has on their email what the vat is
problem is that in paypal the VAT and shipping have been passed as one field

if the correct VAT and shipping fields are not filled in by opencart when it passes the information to paypal, any vat accountancy cannot be done correctly

example

£100 product cost
VAT = £20
shipping = £10
total order £130

customer pays by paypal

opencart passes order information into paypal

product  = £100
vat and shipping = £30
vat field = blank
shipping field = blank

so the customer pays £130

when I do a report from paypal on what VAT has been payed on order, it cant tell me as the details have not been passed to paypal from opencart.

this is a big issue for anyone vat registered and using paypal with opencart, as you cannot calculate the correct vat charged to customers for your VAT return etc.

looking at https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/

in the Payment Details Type Fields section, there are separate fields you can pass to paypal from opencart to put the VAT and shipping in their own separate fields

I hope that helps and you can still consider this as something that needs to be resolved.

Many thanks in advance
Phil
