### ISSUE TITLE
Upgrade from 2.0.3.1 to 2.1.0.0 - Specific issues

### ISSUE THREAD

**Issue by blueworldmedia** [opencart/opencart#3497]
There are other tickets, but here are some specific upgrade issues with a couple of solutions. I gave up after the first few...

# Missing definition in config.php
define('DB_PORT', '3306')

# None of the SQL upgrade commands are being executed. 
I tracked this down to the follow regexp. There is no 'IF NOT EXISTS' line in the SQL

upgrade.php Line 124

// Get Table Name
preg_match_all('#create\s*table\s*if\s*not\s*exists\s*`(\w[\w\d]*)`#i', $sql, $table);

to 

// Get Table Name
preg_match_all('#create\s*table\s*`(\w[\w\d]*)`#i', $sql, $table);

# DB field migration
Fields do not get migrated. For example, 'api' table has two new fields for key and value, and does not migrate the old values

# Modules have lost content
'Featured' is a good example. The content does not appear on the main website, and if you try and edit it in the admin system, it create a new blank record. I suspect this is related to the DB migration issue.

# unserialize() error on page load
This can be fixed by reloading the modifications in the admin system

**Comment by pnair39** [comment]
Does this mean there no way to Upgrade from 2.0.3.1 to 2.1.0.0?

**Comment by xguntis** [comment]
you can try this:
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=19572


On Tue, Oct 20, 2015 at 2:13 AM pnair39 <notifications@github.com> wrote:

> Does this mean there no way to Upgrade from 2.0.3.1 to 2.1.0.0?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/3497#issuecomment-149373186>.
>
-- 
Regards/Ar cieņu
Guntis Endzelis

**Comment by pnair39** [comment]
Error msg received using migration tool: upgrading from 2.0.3.1 to 2.1.0.0.


Fatal error: Uncaught exception 'ErrorException' with message 'Error: Incorrect table definition; there can be only one auto column and it must be defined as a key<br />Error No: 1075<br />ALTER TABLE `oc_address` DROP PRIMARY KEY' in /home/amillio8/public_html/Demo/converter/system/database/mysqli.php:40 Stack trace: #0 /home/amillio8/public_html/Demo/converter/vqmod/vqcache/vq2-system_library_db.php(20): DBMySQLi->query('ALTER TABLE `oc...') #1 /home/amillio8/public_html/Demo/converter/model/upgrade/database.php(273): DB->query('ALTER TABLE `oc...') #2 /home/amillio8/public_html/Demo/converter/controller/upgrade/column.php(138): ModelUpgradeDatabase->addColumns(Array) #3 [internal function]: ControllerUpgradeColumn->new_data() #4 /home/amillio8/public_html/Demo/converter/vqmod/vqcache/vq2-system_engine_front.php(46): call_user_func_array(Array, Array) #5 /home/amillio8/public_html/Demo/converter/vqmod/vqcache/vq2-system_engine_front.php(32): Front->execute(Object(Action)) #6 /home/amillio8/public_html/Demo/converter/ind in /home/amillio8/public_html/Demo/converter/system/database/mysqli.php on line 40

**Comment by danielkerr** [comment]
Missing definition in config.php

FIXED IN LATEST COMMIT

None of the SQL upgrade commands are being executed.

FIXED IN LATEST COMMIT

**Comment by danielkerr** [comment]
unserialize() error on page load

SHOULD BE FIXED ALSO

**Comment by danielkerr** [comment]
DB field migration

added the api stuff
