### ISSUE TITLE
Dashboard Activity PHP errors

### ISSUE THREAD

**Issue by pnair39** [opencart/opencart#3498]
Disabled System>Settings>Account: Customers Online to No

To get home page to partial show up except for the content home page every other pages are click able except for home page content.
Logging into Admin:

Warning: vsprintf(): Too few arguments in /home/amillio8/public_html/Demo/admin/controller/dashboard/activity.php on line 19Warning: vsprintf(): Too few arguments in /home/amillio8/public_html/Demo/admin/controller/dashboard/activity.php on line 19Warning: vsprintf(): Too few arguments in /home/amillio8/public_html/Demo/admin/controller/dashboard/activity.php on line 19Warning: vsprintf(): Too few arguments in /home/amillio8/public_html/Demo/admin/controller/dashboard/activity.php on line 19Warning: vsprintf(): Too few arguments in /home/amillio8/public_html/Demo/admin/controller/dashboard/activity.php on line 19

**Comment by danielkerr** [comment]
you need to empty the activity table and let the system add new ones. i have already added a fix in the master branch but you would have to update again.

**Comment by alancheongkl** [comment]
Hi @danielkerr , which file need to update for this error ?
