### ISSUE TITLE
Missing Order tabs Version 2.1.0.1

### ISSUE THREAD

**Issue by myln8** [opencart/opencart#3502]
<img width="1257" alt="screen shot 2015-10-16 at 4 57 04 am" src="https://cloud.githubusercontent.com/assets/15151137/10532344/e1fb92b0-73c5-11e5-8d53-96d93336a05e.png">

**Comment by danielkerr** [comment]
Anyone else have this issue?

**Comment by GomDani** [comment]
This is not ver 2.1.0.1. The order info page in 2.1.0.1 is diferent. I don't know how modification works i never use that, maybe is old copy of html and need refresh.

**Comment by OpenCartAddons** [comment]
As @GomDani mentioned, this does not appear to be the default order information page in OC v2.1.0.1.


Regards,
Joel.
