### ISSUE TITLE
 Fatal error: Call to undefined method ModelToolOnline::whosonline() in /home/amillio8/public_html/Demo/system/modification/catalog/controller/common/footer.php on line 80

### ISSUE THREAD

**Issue by pnair39** [opencart/opencart#3506]
completed steps(Systems>Settings>Account>Customers Online (Set to off) to disable error msg but this is just a work around any ideas?

**Comment by GomDani** [comment]
I think you have same old footer.php in system/storage/modification/ or same extension that call old whosonline() function, now is addOnline().

**Comment by pnair39** [comment]
I disabled an extension and re-enabled it resolved issue and received the following msg:

Notice: Undefined variable: icon in /home/amillio8/public_html/Demo/vqmod/vqcache/vq2-system_modification_catalog_view_theme_red nav_template_common_header.tpl on line 20
