### ISSUE TITLE
DISCUSSION: tax_rules and geo_zones

### ISSUE THREAD

**Issue by pine3ree** [opencart/opencart#3508]
Hello Daniel,

i am not sure this is the right place. With the current features of OC, the need to sell both shippable and digital products made me duplicate the standard tax rate for the shop country.

Let me explain with an example:

1) shippable products
tax class "standard vat" 
     - rule (rate: VAT-22 (22% defined for the entire EU VAT zone) based on shipping addr)

2) digital products / electronic services
tax class "digital products"
    - rule for AT (rate: VAT-DE-19 (19% defined for a zone including Germany only) based on billing addr)
    - rule for UK (rate: VAT-UK-20 (20% defined for a zone including Great Britain only) based on billing addr)
    ...
    ... (1 rule for each member state with a single zone defined for it)
    ...
    - rule for IT (rate: VAT-IT-22 (22% defined for a zone including Italy only) based on billing addr)

in  this case, i had to redefine the italian vat 22% rate becausein this case  it needs to be linked only to Italy, i cannot use the already defined rate. If i use the previously define rate, this will be always inlcuded in the tax calculation along with single states vat rates when i sell a digital product to other eu contry customers.

Wouldn't it be better to move the relation to the geo_zone into the tax_rule table?
It would also be clearer to read. In the same place you see almost all the conditions (customer_group excluded) in which a rule apply for the current tax_class being edited/created.

I understand that this would be a major change for upgrades, even if coding it would be quite simple (only tax-class tax-rate administration related code + tax calculator class would be affected)

kind regards,
maks

**Comment by danielkerr** [comment]
I will look into this later. im still moving servers. 

I think the current method is correct thouh. maybe your not using the tax system correctly.

**Comment by pine3ree** [comment]
Hello Daniel, sure.

But i am not saying it's not correct or that it's not possible to make it work. I was just saying that to sell both shippable and electronic products to the shop country and other eu countries, since a tax rate is linked to a zone, i have to define the same tax rate twice, one linked to the shop country for digital products) and one linked to an EU geo-zone for shippable products. 
btw, in magento, you have to define the same rate for each country....which is much less comfortable.
The one thing i find more useful in magento is having all the components of a tax rule in the same place, while in opencart rule definitions are spread among the tax_rate table (link to geo-zone), tax_rate_to_customer_group table, and the tax_rule table. Having the geo-zone relation moved to the tax_rule table would make it possible to avoid even that single redefinition of the same rate.

If you have time and are interested i can setup an example site ang give you admin access in the next days.

best regards,
maks

**Comment by danielkerr** [comment]
]your actually giving me really bad advice that if i follow what you say would cause major issues.

say with the last commit you did on taxes. i dont think you know what you are doing.

**Comment by pine3ree** [comment]
No problem, i have already implemented what I was suggesting for a customer and it's working perfectly....

kind regards

**Comment by arnisjuraga** [comment]
@pine3ree how did you manage this to work?
