### ISSUE TITLE
Notice: Undefined variable: icon in /home/amillio8/public_html/Demo/vqmod/vqcache/vq2-system_modification_catalog_view_theme_red nav_template_common_header.tpl on line 20

### ISSUE THREAD

**Issue by pnair39** [opencart/opencart#3509]
Notice: Undefined variable: icon in /home/amillio8/public_html/Demo/vqmod/vqcache/vq2-system_modification_catalog_view_theme_red nav_template_common_header.tpl on line 20

**Comment by Newman101** [comment]
Related to vQmod, specifically vqcache folder.  Initial troubleshooting steps: 

1. Disable the vQmods one by one. To eliminate the possible buggy mod. 
2. Once found, investigate where exactly the bug is.
3. Once bug is eliminated, clear vqcache folder and re-instate the mod. 

Thanks.

**Comment by pnair39** [comment]
disabled all mods and deleted vqcache folder and before did not enable mods the problem still exists, what's the next?

**Comment by GomDani** [comment]
Open header.tpl in your template and remove 
```
<?php if ($icon) { ?>
<link href="<?php echo $icon; ?>" rel="icon" />
<?php } ?>
```

**Comment by pnair39** [comment]
That fixed the issue, thank you. One more issue the home page content is missing it shows all the banner and menu. I am able to view all the pages except for the home page content portion any idea?

**Comment by danielkerr** [comment]
stop posting support questions here!
