### ISSUE TITLE
New banner image sort order not displaying. 

### ISSUE THREAD

**Issue by bhavin30** [opencart/opencart#3510]
Notice: Undefined index: sort_order in \opencart-2.1.0.1\upload\admin\controller\design\banner.php on line 386
Save with out adding banner title and get notice.
![fresh_opencart_issue](https://cloud.githubusercontent.com/assets/15160716/10546998/2dd1365c-744f-11e5-81ff-f08c4b5f15e2.png)

**Comment by Newman101** [comment]
This is yet to be reproduced, but my main suspicion is that the code causing this to happen is this piece in admin/controller/design/banner.php:

```PHP
			foreach ($banner_image_description_query->rows as $banner_image_description) {
				$banner_image_description_data[$banner_image_description['language_id']] = array('title' => $banner_image_description['title']);
			}
```

Basically, the foreach loop in question saves the title to array by default. If there is no title, the notice appears. I need to dig deeper and reproduce the bug later on.

**Comment by OpenCartAddons** [comment]
This was caused due to a missing double quote in the banner_form.tpl.  The fix is here https://github.com/opencart/opencart/issues/3399


Regards,
Joel.

**Comment by bhavin30** [comment]
thank you :)
