### ISSUE TITLE
Undefined variable error in Backup & Restore page from admin

### ISSUE THREAD

**Issue by harnishdesign** [opencart/opencart#3519]
`Notice: Undefined variable: entry_export in C:\Harnish Design\xampplite\htdocs\opencart_2.1.0.1\admin\view\template\tool\backup.tpl on line 43`

![screenshote](https://cloud.githubusercontent.com/assets/2634085/10570509/642d24cc-7652-11e5-9104-fb8b6a6ea46e.jpg)

**Comment by danielkerr** [comment]
was already reported and been fixed int he mast branch.

**Comment by harnishdesign** [comment]
Great. Thanks.
