### ISSUE TITLE
"Other states" display in admin wrong when only 2 order states

### ISSUE THREAD

**Issue by hoermannklaus** [opencart/opencart#3520]
My shop only has 2 order states: A "Processing" and a "Finished" state. They are configured in the shop instance as the 2 necessary states, when a new order is made, and when a order is completed.

Because there are only 2 states, the quick display in the bottom of the left column of the admin view says that there are 100% other statuses, although there are no other states.

I think the problem is in the function "getTotalOrders" of the class "ModelSaleOrder". 

Thanks

**Comment by danielkerr** [comment]
you need to re save the settings and make sure you tick the correct order statuses
