### ISSUE TITLE
Session class error

### ISSUE THREAD

**Issue by matrunchyk** [opencart/opencart#3524]
Hi guys, 

I stumbled with some weird issue.
When I try to remove any order it shows me the error `Warning: You do not have permission to access the API!`.

(I have Admin rights, all permissions are selected and API user is selected in store config as well)

Let's dig deeper.
To delete an order the api is used:
`https://example.com/index.php?route=api/order/delete&token=XXX&order_id=1`

`Delete` method checks a session variable [like this](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/api/order.php#L701):
```
if (!isset($this->session->data['api_id'])) {
   $json['error'] = $this->language->get('error_permission');
}
```

`$this->session` comes from `Registry` system and [is declared](https://github.com/opencart/opencart/blob/master/upload/index.php#L127) in `index.php` file.

[Let's take a look](https://github.com/opencart/opencart/blob/master/upload/system/library/session.php) inside a `Session` class. And have some questions..

1. [Where](https://github.com/opencart/opencart/blob/master/upload/system/library/session.php#L16) `$session` var is being declared before? It's always undefined.
2. [The same](https://github.com/opencart/opencart/blob/master/upload/system/library/session.php#L13) for `$registry` variable. Undeclared.

But anyway code within [this if case](https://github.com/opencart/opencart/blob/master/upload/system/library/session.php#L12) is never to be run while Session's $driver is empty. (I suppose this piece of code is still under design).

But main question - Where `api_id` is being set here?
I've found only one entry point - [api login method](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/api/login.php#L36). Should it be used somehow before I need to remove orders?

Or should API user be logged in automatically for me to use it within admin panel?

Thank you!

**Comment by GomDani** [comment]
Look issue  #3482.

**Comment by matrunchyk** [comment]
Oh your reply is so fast! :+1: 
Thank you for the reference, @GomDani!
