### ISSUE TITLE
Secure password with symbols - 2.1.0.1

### ISSUE THREAD

**Issue by nuke123** [opencart/opencart#3528]
1. Login is checking utf8 password but there is no conversion for this when eidting a user. 

2. Password length calculated incorrectly 21 characters instead of 16. 

Testing with password:
"t7!T^.?=RNDVwwh

**Comment by danielkerr** [comment]
i think more to do with the html char conversion

**Comment by nuke123** [comment]
It used to work ok until you added html_entity_decode to the login

```php
if (!isset($this->request->post['username']) || !isset($this->request->post['password']) || !$this->user->login($this->request->post['username'], html_entity_decode($this->request->post['password'], ENT_QUOTES, 'UTF-8'))) {
```

**Comment by danielkerr** [comment]
closing as it would disrupt users upgrading. also this is pointless. whats stored in the db matches when i user tries to login.

**Comment by nuke123** [comment]
Test with the password and try logging in.
