### ISSUE TITLE
Sort Order Field Missing In Added 'Banner' Rows [2.1.0.1]

### ISSUE THREAD

**Issue by Deji69** [opencart/opencart#3529]
![untitled](https://cloud.githubusercontent.com/assets/6594342/10610731/0ade65c6-7741-11e5-910a-858fc49c3681.png)

It has a simple 1-character (missing quote) fix at line 107 of admin\view\template\design\banner_form.tpl...

Change

    html += '  <td class="text-right" style="width: 10%;><input type="text" name="banner_image[' + image_row + '][sort_order]" value="" placeholder="<?php echo $entry_sort_order; ?>" class="form-control" /></td>';

To

    html += '  <td class="text-right" style="width: 10%;"><input type="text" name="banner_image[' + image_row + '][sort_order]" value="" placeholder="<?php echo $entry_sort_order; ?>" class="form-control" /></td>';

**Comment by IP-CAM** [comment]
has already been fixed in:
('VERSION', '2.1.0.2_rc'); 
html += '  <td class="text-right" style="width: 10%;">

**Comment by Gengjun-VVU** [comment]
Yup, missing one quote, took me 5 mins to find it. All fixed.
