### ISSUE TITLE
delete return status bug

### ISSUE THREAD

**Issue by opencart-russia** [opencart/opencart#3531]
When delete return status and table return_history the empty
I see: Undefined index: total in \admin\model\sale\return.php on line 234

**Comment by OpenCartAddons** [comment]
You shouldn't be manually dropping tables via phpMyAdmin.  Dumping just return_history is only half of the data.  

Here's the delete function for returns:

    public function deleteReturn($return_id) {
		$this->db->query("DELETE FROM `" . DB_PREFIX . "return` WHERE return_id = '" . (int)$return_id . "'");
		$this->db->query("DELETE FROM " . DB_PREFIX . "return_history WHERE return_id = '" . (int)$return_id . "'");
	}

Regards,
Joel.

**Comment by opencart-russia** [comment]
I did not dropping tables
see https://github.com/opencart/opencart/blob/master/upload/install/opencart.sql#L2996
table empty

**Comment by opencart-russia** [comment]
I delete return status from admin dashboard

**Comment by OpenCartAddons** [comment]
Sorry, I thought you meant to deleted data directly from the return_history table.

I just tried it and was also able to recreate the issue.  I think I might know what is causing the issue.

Regards,
Joel.

**Comment by OpenCartAddons** [comment]
Submitted a patch https://github.com/opencart/opencart/pull/3533

**Comment by danielkerr** [comment]
ok the patch was merged
