### ISSUE TITLE
Modifications error=skip bug

### ISSUE THREAD

**Issue by nuke123** [opencart/opencart#3532]
```php
if (!$status) {
	// Log
	$log[] = 'NOT FOUND!';

	// Skip current operation
	if ($error == 'skip') {
		break;
	}

	// Abort applying this modification completely.
	if ($error == 'abort') {
		$modification = $recovery;

		// Log
		$log[] = 'ABORTING!';

		break 5;
	}
}
```

I think the $error == 'skip' should be continue instead of break. 

It should continue to the next operation if there is a error, at the moment it is skipping to the next file and missing out any operations below. 

E.g the third operation wil not get modified due to the error="skip" above it. 
```xml
<file path="catalog/view/theme/*/template/product/product.tpl">
    <operation>
	  <search><![CDATA[<?php echo $price; ?>]]></search>
	  <add position="replace"></add>
	</operation>
	<operation error="skip">
	  <search><![CDATA[<?php echo $reward1234; ?>]]></search>
	  <add position="replace"></add>
	</operation>
	<operation>
	  <search><![CDATA[<?php echo $footer; ?>]]></search>
	  <add position="replace"></add>
```

**Comment by danielkerr** [comment]
thats what you think and you also did a pull request for it.

after i closed the pull request you now think its acceptable to open an issue!

stop wasting my time!

**Comment by nuke123** [comment]
Even the comment says how it should work 'Skip current operation'

No pull request from me, must be somebody else who thinks the same.
