### ISSUE TITLE
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data  OK

### ISSUE THREAD

**Issue by ranjeetOstech** [opencart/opencart#3543]
I have upgrade opencart  to 2.0.3.1  from 2.0.1.1
When i edit or add new order from admin then i have getting  "SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data  OK"
Pls help me to resolve this error

**Comment by danielkerr** [comment]
I need to guess the page your having this issue on

**Comment by ranjeetOstech** [comment]
Thanks danielkerr
This page working correctly on local or other server.

**Comment by matrunchyk** [comment]
What the page are you seeing this error?

**Comment by ranjeetOstech** [comment]
http://healthdentalproducts.com/admin/sale/order/add
http://healthdentalproducts.com/admin/sale/order/edit
/admin/controller/sale/order.php

**Comment by Opencartprogrammer** [comment]
Hi all,
Finally we get the solution for the order edit error "SyntaxError: 

JSON ... ok" in OpenCart 2.0.1.0, 2.0.1.1, 2.0.2.0, 2.0.3.1, 2.1.0.1, 

2.1.0.2, 2.2.0.0, 2.3.0.0, 2.3.0.1, 2.3.0.2 If you really want to get 

the solution for the order edit error in your OpenCart store then 

visit us and contact through GET A QUOTE message or place a support 

ticket by the links below respectively.

http://opencartprogrammer.com/

http://opencartprogrammer.com/helpdesk/

Our support team will get back to you soon.

thanks
Opencartprogrammer team

**Comment by Opencartprogrammer** [comment]
Hi all,
Finally we get the solution for the order edit error "SyntaxError: 

JSON ... ok" in OpenCart 2.0.1.0, 2.0.1.1, 2.0.2.0, 2.0.3.1, 2.1.0.1, 

2.1.0.2, 2.2.0.0, 2.3.0.0, 2.3.0.1, 2.3.0.2 If you really want to get 

the solution for the order edit error in your OpenCart store then 

visit us and contact through GET A QUOTE message or place a support 

ticket by the links below respectively.

http://opencartprogrammer.com/

http://opencartprogrammer.com/helpdesk/

Our support team will get back to you soon.

thanks
Opencartprogrammer team

**Comment by danielkerr** [comment]
get a ban!
