### ISSUE TITLE
Missspaced From: Header in E-Mails sent

### ISSUE THREAD

**Issue by mnaef** [opencart/opencart#3544]
Mails being sent lack a space between the human readable "name" and the &lt;emailaddress&gt;:

     From: =?UTF-8?B?UGxxxeg==?=<xxx@xxx.tld>

This leads to Spamassassin penalizing such mails with quite some points:

        4.3 FROM_MISSP_REPLYTO     From misspaced, has Reply-To

<pre>

Fix:

diff -u   ./system/library/mail.php ./system/library/mail.php.new
--- ./system/library/mail.php   2013-05-30 11:08:01.679256000 +0200
+++ ./system/library/mail.php.new       2015-10-23 16:31:01.480474000 +0200
@@ -90,8 +90,8 @@
                }
 
                $header .= 'Date: ' . date('D, d M Y H:i:s O') . $this->newline;
-               $header .= 'From: ' . '=?UTF-8?B?' . base64_encode($this->sender) . '?=' . '<' . $this->from . '>' . $this->newline;
-               $header .= 'Reply-To: ' . '=?UTF-8?B?' . base64_encode($this->sender) . '?=' . '<' . $this->from . '>' . $this->newline;
+               $header .= 'From: ' . '=?UTF-8?B?' . base64_encode($this->sender) . '?= ' . '<' . $this->from . '>' . $this->newline;
+               $header .= 'Reply-To: ' . '=?UTF-8?B?' . base64_encode($this->sender) . '?= ' . '<' . $this->from . '>' . $this->newline;
                $header .= 'Return-Path: ' . $this->from . $this->newline;
                $header .= 'X-Mailer: PHP/' . phpversion() . $this->newline;
                $header .= 'Content-Type: multipart/related; boundary="' . $boundary . '"' . $this->newline . $this->newline;
@@ -403,4 +403,4 @@
                }
        }
 }
-?>
\ No newline at end of file
+?>
</pre>

And while you're at it, it also helps to safe spampoints if you enclose the To: E-Mail address in pointy brackets:

        2.5 TO_NO_BRKTS_FROM_MSSP  Multiple header formatting problems

**Comment by danielkerr** [comment]
not sure which version you are using but its been over a year since spaces where added.
