### ISSUE TITLE
Google Analytics Multi-Store

### ISSUE THREAD

**Issue by mgraph** [opencart/opencart#3547]
in OC 2 when I go to analytics/google_analytics I can insert a single Analytics Code which mean the code is displayed in all multi-stores (I think the old Google Analytics OC 1.5.6 was perfect)

**Comment by pnair39** [comment]
Receiving Error on New Installed tracking code is installed however it's not working. 

Missing Tracking Code:
Make sure your pages are tagged with a supported version of the tracking code.

**Comment by jamesallsup** [comment]
Add suggestions to changes here: http://opencart.uservoice.com
