### ISSUE TITLE
Opencart 2 android/paypal error

### ISSUE THREAD

**Issue by Philtrum** [opencart/opencart#3549]
Hi

I have replicated this on at least 3 devices

opencart 2.0.3.1
various versions of android

if the paypal app is installed, when you come to checkout, it opens the app and asks you to login to the paypal app, a that point it looses its connection with opencart and the user cannot complete the sale.

not sure if its a problem with the data passed to the app, or the paypal app itself

Many thanks
Phil

**Comment by danielkerr** [comment]
I have not had time to look at the issue yet.

do not make multiple uissues fo the same thing
