### ISSUE TITLE
Extension installer issue

### ISSUE THREAD

**Issue by richardcopestake** [opencart/opencart#3556]
SyntaxError: JSON Parse error: Unrecognized token '<'
OK
<br />
<b>Fatal error</b>:  Call to undefined function zip_open() in <b>/home/cherryde/public_html/customers/innerpeace/admin/controller/extension/installer.php</b> on line <b>120</b><br />

When trying to upload a new installation. Version 2.0.2.0

**Comment by danielkerr** [comment]
what version of php are you using?

**Comment by danielkerr** [comment]
i think you dont have the php zip extension installed. contact your host. please let me know if they fix it.

**Comment by danielkerr** [comment]
the function exists
http://php.net/manual/en/function.zip-open.php

**Comment by richardcopestake** [comment]
Thank you for the rapid response. 

I've asked my tech to install this and see where we are at.

**Comment by richardcopestake** [comment]
This is rebuilding with the required module

**Comment by richardcopestake** [comment]
The next issue 

"Directory containing files to be uploaded could not be found!

**Comment by valdeir2000** [comment]
This means that within the file "*.ocmod.zip" does not contain the upload folder.

**Comment by matrunchyk** [comment]
What are the file contents?

**Comment by richardcopestake** [comment]
So should there be a folder called "upload" in the zip?

**Comment by richardcopestake** [comment]
Right, so theres an upload folder in the file, with all the contents in BUT nothing still..

**Comment by richardcopestake** [comment]
Related to the same issue 

"SyntaxError: JSON Parse error: Unrecognized token '<'
OK
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
<meta charset="UTF-8" />
<title>Administration</title>
<base href="http://cherry-designs.net/customers/innerpeace/admin/" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
<script type="text/javascript" src="view/javascript/jquery/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="view/javasc"

**Comment by matrunchyk** [comment]
Perhaps there's something wrong with file names. Could you please post here a list of the all files  packed within the archive?

**Comment by richardcopestake** [comment]
I've tried multiple extensions.

**Comment by danielkerr** [comment]
yeah i think this is a problem just with your site. you should contact my staff or try the forums. this si a developer issue tracker.

**Comment by richardcopestake** [comment]
I'm aware, but who do we contact for support? The forums you never get an answer. I'm not sure whats going on

**Comment by matrunchyk** [comment]
Just try [there](https://forum.opencart.com/viewforum.php?f=184). There many guys who does support each one.
