### ISSUE TITLE
API session error

### ISSUE THREAD

**Issue by matrunchyk** [opencart/opencart#3557]
Hi guys,

I stumbled with some weird issue.
When I try to remove any order it shows me the error Warning: You do not have permission to access the API!.

**My OpenCart is in sync with master (latest update was today!)**

(I have Admin rights, all permissions are selected and API user is selected in store config as well)

Let's dig deeper.
To delete an order the api is used:
https://example.com/index.php?route=api/order/delete&token=XXX&order_id=1

Delete method checks a session variable like this:

if (!isset($this->session->data['api_id'])) {
   $json['error'] = $this->language->get('error_permission');
}
$this->session comes from Registry system and is declared in index.php file.

Let's take a look inside a Session class. And have some questions..

Where $session var is being declared before? It's always undefined.
The same for $registry variable. Undeclared.
But anyway code within this if case is never to be run while Session's $driver is empty. (I suppose this piece of code is still under design).

But main question - Where api_id is being set here?
I've found only one entry point - api login method. Should it be used somehow before I need to remove orders?

Or should API user be logged in automatically for me to use it within admin panel?

P. S. @danielkerr, it's a dup of #3524, still haven't solved.

Thank you!

**Comment by danielkerr** [comment]
its fixed. just trying to sort the events system. i want it to work like the front controller.

**Comment by danielkerr** [comment]
pm me your skype via the forums

**Comment by matrunchyk** [comment]
@danielkerr Great, thanks! I wrote you by PM
