### ISSUE TITLE
New installation, /admin/, got fatal error calculate() in featured.php 

### ISSUE THREAD

**Issue by maxim-486** [opencart/opencart#3562]
After successful installation new instance of opencart 2.1.0.1 when trying to open http://opencart/admin folder, got error
"Fatal error: Call to a member function calculate() on null in site-folder/www/catalog/controller/module/featured.php on line 38"

Overwriting with master.zip files from Github did not solved this problem :(

Debian GNU/Linux 8
PHP 5.6.13-0+deb8u1 (cli) (built: Sep  7 2015 13:38:37)
Apache/2.4.10 (Debian)
mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.3

BTW, Thanks for your work!

**Comment by matrunchyk** [comment]
Why just not to remove all the files and unzip ones from the master? Just notice to keep config.php files.

**Comment by maxim-486** [comment]
I`ve removed all but config.php and admin/config.php
and unzipped upload folder from master.zip (github repository).
Problem still exist.

**Comment by maxim-486** [comment]
the problem solved while apache config changed
virtual host
removed
"php_admin_value include_path /folder2site/www"

**Comment by matrunchyk** [comment]
Could you please close the issue?

**Comment by deadlance** [comment]
I am having this same error. I do not have anything in my apache config that has php_admin_value at all.

**Comment by deadlance** [comment]
[Thu May 19 12:32:51.393064 2016] [:error] [pid 7009] [client 70.167.25.24:56677] PHP Fatal error:  Uncaught Error: Call to a member function calculate() on null in /var/www/AMS-Opencart2/catalog/controller/module/featured.php:38\nStack trace:\n#0 /var/www/AMS-Opencart2/system/storage/modification/system/engine/loader.php(42): ControllerModuleFeatured->index(Array)\n#1 /var/www/AMS-Opencart2/catalog/controller/common/content_top.php(59): Loader->controller('module/featured', Array)\n#2 /var/www/AMS-Opencart2/system/storage/modification/system/engine/loader.php(42): ControllerCommonContentTop->index(Array)\n#3 /var/www/AMS-Opencart2/catalog/controller/error/not_found.php(50): Loader->controller('common/content_...')\n#4 /var/www/AMS-Opencart2/system/storage/modification/system/engine/action.php(46): ControllerErrorNotFound->index(Array)\n#5 /var/www/AMS-Opencart2/system/engine/front.php(34): Action->execute(Object(Registry))\n#6 /var/www/AMS-Opencart2/system/engine/front.php(29): Front->execute(Object(Action))\n#7 /var/www/AMS-Opencart2/admin/index.php(174): Front->dispatch(Object(Action), Object(Action))\n#8 {main}\n  in /var/www/AMS-Opencart2/catalog/controller/module/featured.php on line 38
