### ISSUE TITLE
double cleaning super globals

### ISSUE THREAD

**Issue by dtjones** [opencart/opencart#3572]
The $_GET, $_POST and $_COOKIE superglobals are now cleaned in  startup.php which is great, but they are also cleaned again in library/request.php. I think $_REQUEST, $_FILES and $_SERVER should be cleaned in startup.php and then all cleaning removed from request.php. 

// like so 

    // Magic Quotes Fix
	if (ini_get('magic_quotes_gpc')) {
		function clean($data) {
	   		if (is_array($data)) {
	  			foreach ($data as $key => $value) {
	    			$data[clean($key)] = clean($value);
	  			}
			} else {
	  			$data = stripslashes($data);
			}
			return $data;
		}
		$_GET = clean($_GET);
		$_POST = clean($_POST);
		$_COOKIE = clean($_COOKIE);
		$_REQUEST = clean($_REQUEST);
		$_FILES = clean($_FILES);
		$_SERVER = clean($_SERVER);
	}

and request.php 

	class Request {

		public $get; // = array(); needed ? 
		public $post;
		public $cookie;
		public $files;
		public $server;

		public function __construct() {
			$this->get = $_GET;
			$this->post = $_POST;
			$this->request = $_REQUEST;
			$this->cookie = $_COOKIE;
			$this->files = $_FILES;
			$this->server = $_SERVER;
		}
	}

**Comment by danielkerr** [comment]
the top is removing the lashes the bottom is stopping any html from being added via the request vars.

**Comment by dtjones** [comment]
Sorry, my mistake. Nevertheless, I think a single cleaning method would be better.

    function clean($data, $strip = false) {

		if (is_array($data)) {
			foreach ($data as $key => $value) {
				$data[clean($key, $strip)] = clean($value, $strip);
			}
		} else {

			$data = htmlspecialchars($data, ENT_COMPAT, 'UTF-8');
			if($strip){
				$data = stripslashes($data);
			}
		}
		return $data;
	}
	$_GET = clean($_GET, ini_get('magic_quotes_gpc'));
	$_POST = clean($_POST, ini_get('magic_quotes_gpc'));
	$_COOKIE = clean($_COOKIE, ini_get('magic_quotes_gpc'));
	$_REQUEST = clean($_REQUEST);
	$_FILES = clean($_FILES);
	$_SERVER = clean($_SERVER);
