### ISSUE TITLE
Rounding issue again

### ISSUE THREAD

**Issue by micrdy** [opencart/opencart#3578]
Hi Daniel

So firstly: great job in developing OpenCart. I love your system. But there is a huge problem, making the shop not usable in all EU countries: The well known rounding issue.

I understand that opencart is doing rounding with 8 decimals. That´s great but simply not usable for countries with just 2 decimals (whole EU). 

I have used several other shop systems like Magento and Shopware. None of them got this issue. 
There should be an option to turn off the 8 decimal calculation and switch to 2 decimals. Again: This issue makes OpenCart NOT usable in EU countries. The laws are quite strict. 

So please, Daniel, give us your opinion to this issue (and don´t just close it). Will this be developed in the future? Or is there any quick fix for that?

Greetings from Germany
Lukas

**Comment by danielkerr** [comment]
people have been using opencart and selling int he EU for a long time! i dont know what exactly your issue is as your only talking about decimals not example of which part the calculation is not correct!

**Comment by GomDani** [comment]
I use OpenCart for two year and see a lot of OpenCart shops in our country and the only problem about laws that i see is gift voucher with no tax in totals. In our country all tax values must be displayed.

**Comment by micrdy** [comment]
See the discussion here: http://forum.opencart.com/viewtopic.php?f=161&t=96706&p=511826&hilit=rounding#p511826

**Comment by osworx** [comment]
Unfortunetaly I have to agree what Daniel says (and GomDani commented).

Our own customers are mainly located inside the EU (many of them in Germany) and none of them have troubles with the calculations and/or decimals.
Set the NET price correct, and the GROSS price will be calculated correct.

The posting of froschgift maybe a nice posting, but he is wrong (beauce his net prices are not set correct).

**Comment by micrdy** [comment]
And what is correct? NET Price with 4-8 decimals? I'm Importing products from excel lists with only 2 decimals. 

Von meinem iPhone gesendet

**Comment by osworx** [comment]
At least 4 - you have to check by yourself how many are the best solutiion.
And only because you have only 2 decimals, the whole system is wrong??

**Comment by micrdy** [comment]
I know quite many ecommerce Systems, and noone forces the user to fill in prices with 4 decimals to get correct prices. This is simply not possible if you get prices from suppliers with 2 decimals and you have to use more than one VAT classes.

**Comment by EdersonTS** [comment]
Here in Brazil is 2 decimals and I'm getting trouble with rounding values, totals and **coupon**.
Take a look the cart below:
![Issued cart](https://cloud.githubusercontent.com/assets/3809579/12181324/afa965a0-b568-11e5-9d66-450c7e0d14a9.png)
The total should be 292,09 but I'm getting 292,10 just because there is no round at https://github.com/opencart/opencart/blob/master/upload/catalog/model/total/coupon.php

To fix my problem I just add:
```php
$this->load->model('localisation/currency');
$currency = $this->model_localisation_currency->getCurrencyByCode($this->session->data['currency']);
$discount_total = round($discount_total, $currency['decimal_place']);
```
at https://github.com/opencart/opencart/blob/master/upload/catalog/model/total/coupon.php#L166

I didn't do more tests with taxes or other thinks, but I guess won't be a problem this fix.

**Comment by EdersonTS** [comment]
I did more tests with my modification and all of them worked as expected .. 
@danielkerr may you take look ?
