### ISSUE TITLE
Installer doesn't work

### ISSUE THREAD

**Issue by Tangol** [opencart/opencart#3590]
The installer doesn't work on the latest OC 2.1.0.2_rc https://github.com/opencart/opencart/commit/76a772f9a11f37d3ceb37866b45cd2beee42fc7a
All i get is a blank page.

It must be one of the recent commits that broke it, as it was working 2 weeks ago when i tried it on https://github.com/opencart/opencart/commit/fbc6396bd269389b1da097fe7fb50c1cc646aa1a

**Comment by pnair39** [comment]
They are not going to fix it, they are just going to close your ticket.

**Comment by danielkerr** [comment]
@pnair39  installer works fine! are u talkign about the upgrade?

because its been posted as an issue many times now and i dont need another ticket opening explaining the same thing!!!!!!!
