### ISSUE TITLE
Feature: Weight based shipping choose source currency

### ISSUE THREAD

**Issue by micrdy** [opencart/opencart#3591]
I got two currencies. € (geozone germany) and CHF (geozone switzerland). Both currencies should have weight base shipping applied.

Important is, that both currencies should have FIXED shipping costs. E.G:
Shipping costs for € - 5.00 €
Shipping costs for CHF – 8.00 CHF

The exchange rate of CHF to € is changing every day. Because it is only possible to add the shipping rates in the default currency (€), the shipping costs of CHF changes every day.

It should be possible to say: 
Shipping costs for geozone Germany (€) should be 5 € fixed.
Shipping costs for geozone Switzerland (CHF) should be 8 CHF fixed. 

So that the shipping costs of the foreign currency (with value 1.232323...) is not depending (and gets calculated) from the default currency (with value 1.00000).

**Comment by osworx** [comment]
Simply to apply with a small module.

**Comment by micrdy** [comment]
Is there any? Can't find one in store

**Comment by OpenCartAddons** [comment]
Advanced Shipping PRO can do this.

http://www.opencartaddons.com/shipping/advanced-shipping-pro
