### ISSUE TITLE
button Upload dont work in Safari etc

### ISSUE THREAD

**Issue by opencart-russia** [opencart/opencart#3592]
Hi Daniel. You test click button upload file  http://demo.opencart.com/index.php?route=product/product&product_id=42 (use browser Safari) ?
There will need to be otherwise, html5 does not support ' event triger click' on the element "display:none" and dont upload file in form if insert and remove from DOM.

may be add
```
<?php if ($option['type'] == 'file') { ?>
<form enctype="multipart/form-data" id="form-upload"><input type="file" name="file" /></form>
```
and style
```
#form-upload {height: 0; overflow: hidden;}
```

**Comment by danielkerr** [comment]
why are u using the demo! it the first version of 2.0!

**Comment by opencart-russia** [comment]
bug 2.0.0.0 - 2.1.0.1

**Comment by nosite** [comment]
demo should be fully working and updated!

**Comment by danielkerr** [comment]
just tested on my daughters mac os and works fine.

are u talking about safari on windows? the last release for windows is from 2012 

https://en.wikipedia.org/wiki/Safari_version_history

**Comment by danielkerr** [comment]
ok closing this. 

there is an issue on the demo which was fixed in later versions but the demo was never updated.
