### ISSUE TITLE
Can't view orders in admin

### ISSUE THREAD

**Issue by bowevents** [opencart/opencart#3595]
Hello,
If i wan't to view an order from the dashboard or in sale->orders
I always come to a blank page 
The link says 'server error' with the link :
http://excaliburcrossbows.be/admin/index.php?route=sale/order/info&token=yiubpeZkGY1HJLn8wOLXTq4HcAmkDUqH&order_id=2

Order 2 i made as a test.

The website is :
www.excaliburcrossbows.be

**Comment by bowevents** [comment]
The admin language was in dutch. I put it back to english and i can view them.....

**Comment by GomDani** [comment]
Check if you have order status in both languages.

**Comment by bowevents** [comment]
How can I check that?

**Comment by GomDani** [comment]
I try to delete order status and i still see orders. So the order status is not the problem. Open this in the forum and there maybe someone will help you. I think is something in your code.

**Comment by danielkerr** [comment]
its rather your host having some weird security setting blocking words with admin and order or there is an error on the page your host has error reporting turned off completely  causing the blank page.
