### ISSUE TITLE
information pages

### ISSUE THREAD

**Issue by bowevents** [opencart/opencart#3596]
Hello,
In the information pages i can only put a limited number of words, i think max100
In opencart version 1.5x it wasn't limited.
How can i fix this?

**Comment by GomDani** [comment]
The validation is the same:

```
if (utf8_strlen($value['description']) < 3) {
	$this->error['description'][$language_id] = $this->language->get('error_description');
}
```

This error is in your code not default OC.

**Comment by OpenCartAddons** [comment]
The only limitation to the number of characters allowed in the information page description is what the database structure can handle.

Because the description column is set to TEXT I believe that puts the limitation to around 60,000 characters.

Cheers,
Joel.

**Comment by bowevents** [comment]
I just installed 2.1.0.1. I didn't made any changes to the script.
Only added language dutch and german.  
The problem is when i enter all the text in the text field, when i press then save, and open it again, half is missing... only at dutch and englisch, german is ok.

**Comment by osworx** [comment]
Have you added the text manually or copy & paste (from e.g. MS-Word)?

**Comment by bowevents** [comment]
copy past....   but also with the german part and that is ok...

**Comment by danielkerr** [comment]
another issue that nobody else in the world has

**Comment by bowevents** [comment]
i don't think i just have that problem...
