### ISSUE TITLE
Installer doesn't work

### ISSUE THREAD

**Issue by Tangol** [opencart/opencart#3597]
To be on the same tone with @danielkerr (https://github.com/opencart/opencart/issues/3590#issuecomment-153578398), the installer doesn't work!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Rev: https://github.com/opencart/opencart/commit/76a772f9a11f37d3ceb37866b45cd2beee42fc7a

-Steps V1:
1. Select the master branch - https://github.com/opencart/opencart/tree/master
2. Click on Download ZIP.
3. Unzip the master archive.
4. Rename the config.php files.
5. Copy the contents of the upload folder to the htdocs folder.
6. Access localhost.
7. Result:
![bug](https://cloud.githubusercontent.com/assets/3336728/10946453/0c15cbdc-832b-11e5-8109-5150990fe1b9.png)

-Steps V2:
1. Access http://www.opencart.com/index.php?route=download/download/success&download_id=42
2. Download OC 2.1.0.1
3. Repeat the steps at V1.
4. IT WORKS!

-Steps V3:
1. Download OC at this commit: https://github.com/opencart/opencart/commit/fbc6396bd269389b1da097fe7fb50c1cc646aa1a
2. Repeat the steps at V1.
3. IT WORKS!

**Comment by stockmaster** [comment]
@Tangol lol, just lol!

**Comment by Masterwebsite** [comment]
in the master the problem is in \upload\system\engine\loader.php  comment line 71 and 90 with // and work

**Comment by danielkerr** [comment]
its still being worked on! stop posting crap!

**Comment by Tangol** [comment]
How are we supposed to know its being worked on? Where does it say?
What should we do if we want to test the master branch?
Shouldn't this bug report remain open until the issue is fixed by a pull request?
For example, I have no interest in testing v2.1.0.1, as i want to see if the latest and "greatest" is ok to become the next release.

No offence @danielkerr , but you should support the community feedback a little bit more...
Right now you closed a valid bug report, just because YOU (the only person) have an information that somewhere the issue is being worked on, and one day we will have a fix for it.
OpenCart never ceases to amaze me...

**Comment by danielkerr** [comment]
@Tangol I don't have to explain my self to you! i will just have you blocked from posting on the opencart github!

if an issue gets closed and i dont explain why thats down to me!

**Comment by danielkerr** [comment]
"No offence @danielkerr , but you should support the community feedback a little bit more..."

I do take offence!! I have been working at home for the last 4 weeks weeks on opencart just for you to criticize me because i have deiced to work on something other than fixing bugs!

the issue was closed 3 times! my installer works fine for me! when i go back to testing the installer and it doesn't work I will fix it! at the moment i have better things to do!

in the mean time stop wasting my time!!
