### ISSUE TITLE
Running list of outstanding issues with 2.1.0.1 not upgrade.

### ISSUE THREAD

**Issue by pnair39** [opencart/opencart#3598]
I am trying to get a list of open issues with 2.1.0.1 that is not related to the upgrade. Where can I get that info? Thanks.

**Comment by Tangol** [comment]
@pnair39 :
Pull Requests and Bug Reports here: https://github.com/opencart/opencart
Any other questions/suggestions here: http://forum.opencart.com/

**Comment by danielkerr** [comment]
@pnair39 your issues are your own! i have looked at your public activity. the issues you are having should not be posted here but in the forum or hire a developer to fix for you!
