### ISSUE TITLE
Share on Facebook

### ISSUE THREAD

**Issue by Tangol** [opencart/opencart#3599]
There seems to be a problem with the Facebook Sharing system, as it doesn't take the product image, only its link and description.
Rev: https://github.com/opencart/opencart/commit/76a772f9a11f37d3ceb37866b45cd2beee42fc7a

In the OC Demo (Version 2.0.0.1b) it works fine.

**Comment by nuke123** [comment]
Test with the facebook debugger: https://developers.facebook.com/tools/debug/

Facebook will craw the URL you are sharing and read data from the head. 
Check you have this: ```<meta property="og:image" content="http://mystore.com/image.jpg"/>```

Also check image url doesn't contain spaces or any special characters.
