### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by chris-willows** [opencart/opencart#3602]
In file:
admin/controller/payment/pp_express.php

this line:
return $this->load->view('common/buttons.tpl', $data)

should be changed to:
return $this->load->view('payment/buttons.tpl', $data);

This was already reported here but closed incorrectly:
https://github.com/opencart/opencart/issues/2564

11 months after it is finally resolved! :-)

**Comment by danielkerr** [comment]
why'??\
