### ISSUE TITLE
Quoted shipping is incorrect

### ISSUE THREAD

**Issue by chris-willows** [opencart/opencart#3604]
Problem: the estimated shipping quote gives 2 different values, 1st being incorrect, 2nd being correct.

This happens when:
* the store's address is set to a country A ;
* default shipping is set to be payment address ;
* a shipping quote is requested @ checkout (cart screen) for a country B ;
* different shipping rates are set for country A & B.

To resolve:
in file: system/library/cart/tax.php
before every line:
foreach ($tax_query->rows as $result) {

this line should be added:
$this->tax_rates = array();

If this is not done, $this->tax_rates will contain too much tax zones (from the previous session), of which a second hit will fix.

**Comment by danielkerr** [comment]
You are incorrect.

in the US some states charge taxes based on where the digital goods where sold from and other states tax where the goods are shipped to. you are not configuring your taxes correctly!

**Comment by chris-willows** [comment]
I have set-up a bug area for you to double check please.

How to test:
* use an Incognito window of Chrome (to make sure you are starting fresh with sessions)
* add something in the cart, like this: http://bugoc.willowdigital.com/index.php?route=product/product&product_id=43
* go to the cart
* and ask for a shipping quote for the cart for the UK, pick a region/state, and "get quotes". You get an amount: €574. Ok, click again for a quote, and you get: €482.


Admin area:
http://bugoc.willowdigital.com/admin/
admin / pass

Please confirm when I can delete that DEV area.

**Comment by chris-willows** [comment]
#3612 created.

**Comment by danielkerr** [comment]
DO NOT POST YOUR LOGIN DETAILS TO THE WORLD!!!!!!!!

**Comment by danielkerr** [comment]
THIS IS WHY I DONT THINK ITS A BUG BUT NOT BEING ABLE TO USE THE SOFTWARE PROPERLY!

YOUR LAST ISSUE WAS CAUSED BY YOUR SELF.

DO NOT POST HERE! USE THE FORUM!

**Comment by chris-willows** [comment]
Thank you. The DEV area has been removed. Have a nice day.
