### ISSUE TITLE
Incorrect Tax with guest checkout [2.1.0.1]

### ISSUE THREAD

**Issue by prateekshah** [opencart/opencart#3608]
when there are two (or more) zones defined in store; Say for e.g.
Zone 1: 5% (This is default store address)
Zone 2: 2%

Now if a customer uses guest checkout and enters billing details and selects state that is other than default store state, the same tax 5% is applied where as it should actually be 2%.

If customer is logged in, than the correct tax is added in checkout.

**Comment by danielkerr** [comment]
change the settings tax to be based off the shipping address or billing address.

once the address is set then you will see the taxes change.

**Comment by prateekshah** [comment]
Hello,

My tax setting is shipping address already. It still doesn't work;

![tax-setting](https://cloud.githubusercontent.com/assets/15713635/11021731/7a79cf58-8671-11e5-93c5-6c6b28274776.png)

**Comment by prateekshah** [comment]
Okay, I got it. Payment address is same as billing address. Seems to be working fine now. Thanks.
