### ISSUE TITLE
HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by cikoleko** [opencart/opencart#3609]
Hello,

Please fix this issue, I don't know what is causing it but I get it when I try to install (downloaded opencart from 'master' branch). And yes I did download it couple of days and everything was working fine. I wanted to re-download it because I saw new commits merged so I thought why not?

I know something is broken because I just downloaded a fresh 2.1.0.1 install from the site and install does open.

**Comment by danielkerr** [comment]
download from the main site! the mester version is for developers

**Comment by cikoleko** [comment]
But I saw several fixes that might be important, for example the captcha one that is causing the bug, or I'm wrong. Please let me know if there nothing important in the master branch, thanks.
