### ISSUE TITLE
ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/vhosts/bubblesdeluxe.co.uk/httpdocs/system/library/session.php on line 7

### ISSUE THREAD

**Issue by Saweeney** [opencart/opencart#361]
iam getting two errors! I have just installed open cart on my server and i need help with them!

ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/vhosts/bubblesdeluxe.co.uk/httpdocs/system/library/session.php on line 7

and 

 A session had already been started - ignoring session_start() in /var/www/vhosts/bubblesdeluxe.co.uk/httpdocs/system/library/session.php on line 11 

thank you

**Comment by haipham** [comment]
Disabled sessions auto start with session.auto_start = Off and register_globals = Off settings in php.ini and restart MAMP web server, I still getting error:
Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /.../system/library/session.php on line 8Notice: A session had already been started - ignoring session_start() in /.../system/library/session.php on line 16.

(session.php file in v2.0.3.1 work fine for 2.0.3.2_rc). Please fix this problem. 

Thank you.
