### ISSUE TITLE
The Date and Time Picker with Print v1.1

### ISSUE THREAD

**Issue by vijaya-settipalli** [opencart/opencart#3610]
Hi,

I installed  The Date and Time Picker with Print v1.1 extension in opencart 1.5.6 version.
It shows in admin->users->users group, modules->shipping.
At Front side it shows at shipping Method.once i click on delivery or pick time it shows below error.

Notice: Undefined index: specificdate in C:\Program Files\wamp\www\rationmall\catalog\model\total\shipping.php on line 8

Please any one help.I am working since 10 days.still it not rectifying.

Thanks in advance
![1](https://cloud.githubusercontent.com/assets/15718326/11021853/f638e4b4-8674-11e5-9b03-e77b3e1619e1.png)
ce.

**Comment by vijaya-settipalli** [comment]
Please help me anyone about  bug.

**Comment by GomDani** [comment]
Open this in the forum.
