### ISSUE TITLE
Quoted shipping is incorrect

### ISSUE THREAD

**Issue by chris-willows** [opencart/opencart#3612]
==> Previous issue #3604 was closed & I cannot reopen. I have added a comment there. See below.

I have set-up a bug area for you to double check please.

How to test:

* use an Incognito window of Chrome (to make sure you are starting fresh with sessions)
* add something in the cart, like this: http://bugoc.willowdigital.com/index.php?route=product/product&product_id=43
* go to the cart
* and ask for a shipping quote in the cart for the UK, pick a region/state, and "get quotes". You get an amount: €574. Ok, click again for a quote, and you get: €482.

Admin area:
http://bugoc.willowdigital.com/admin/
admin / pass

Please confirm when I can delete that DEV area

**Comment by danielkerr** [comment]
DO NOT POST YOUR LOGIN DETAILS TO THE WORLD!!!!!!!!

**Comment by chris-willows** [comment]
Thank you. The DEV area has been removed. Have a nice day.
