### ISSUE TITLE
OpenCart Installation - extra forward-slash in directory listing

### ISSUE THREAD

**Issue by Newman101** [opencart/opencart#3614]
Hi. 

After updating OpenCart repository locally (fresh working copy, no changes made), I noticed this on the installation screen, in permissions section:

/var/www/html/opencart/upload/system//storage/cache/.

I do suspect that there's an extra forward-slash somewhere in installation/setup file. 

No further changes made, so I do suspect this is in default settings somewhere. 

Screenshot attached.
![opencart_installation](https://cloud.githubusercontent.com/assets/4118513/11031403/257c82ce-86cc-11e5-8cd8-2c4a4db183a4.png)

**Comment by danielkerr** [comment]
wasting my time!

server software being used?
permissions on the directories!

can the web user even read the folder!

i should guess everything!

**Comment by stockmaster** [comment]
I think daniel

**Comment by stockmaster** [comment]
@Newman101  Daniel merged the fix. Thank you

**Comment by Newman101** [comment]
You're welcome. My installation works fine, it was just the extra forward slash which actually had my attention.

**Comment by stockmaster** [comment]
@Newman101 no clue the implications of that extra slash in the long term, but its fixed now
Cheers
