### ISSUE TITLE
Subdirectory 'catalog' in 'image' directory is hard coded

### ISSUE THREAD

**Issue by nmpetkov** [opencart/opencart#3618]
In order to be able to make multi-site installation, we need to specify different directory for uploaded images (I mean not multi store in one database, but multi-sites with one code base and different databases and image directories). Currently it is not possible with constant DIR_IMAGE (if changed, then images are not visible from http). Proper directory to be configurable is "catalog"  subdirectory, but it is currently hard coded in:
https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/filemanager.php
with several statements like:
```DIR_IMAGE . 'catalog/'```
and
```DIR_IMAGE . 'catalog'```

One possible solution could be to add a constant next to  DIR_IMAGE in config.php, for example:
```define('IMAGESUBDIR_CATALOG', 'catalog');```

If this is acceptable solution, I can make PR for this, otherwise please advice how to proceed.

**Comment by danielkerr** [comment]
so your building a multi vendor mod where clients have their own login in the admin. ask int he forums not here~! this is for development of opencart script and not help you build a site for clients!
