### ISSUE TITLE
Buttons not working on image uploader

### ISSUE THREAD

**Issue by EBDriff** [opencart/opencart#3619]
Just downloaded and started using the newest version of Opencart, but there seems to be a bug in the image loader in that the next page buttons don't work for me. So I can upload (one by one) as many images as I like, but can only see and use the first page. Also the refresh button isnt working so I have to upload the image, then close the uploader, then re-open and use.

Currently using Chrome, but also tried Mozilla and IE incase it was a browser problem.

Have searched the forums and can't find this problem.

**Comment by danielkerr** [comment]
newest version of Opencart,? from where the mnaster branch or the download page! i should guess

**Comment by EBDriff** [comment]
From here http://www.opencart.com/index.php?route=download/download

Version	Release Date	Action
2.1.0.1	October 6, 2015	[ Download ]

Also looked around for patches / updates, but couldnt find any.

Is there somewhere else I should be looking?

Thanks
