### ISSUE TITLE
regular expression to validate email address for IDN

### ISSUE THREAD

**Issue by opencart-russia** [opencart/opencart#3620]
Hi Daniel. May be create helper for validate email? Or add to settings tabs mail, field "regular expression to validate email" ??

Now expression not correct validate emails for Internationalized Domain Names!
```
preg_match('/^[^\@]+@.*.[a-z]{2,15}$/i'
```

Example. иван@почта.рф (for Russia)  and امارات@امارات.اما.امارات (for Egipt) etc ...

This email fine work in gmail, but not work in opencart.

What do you think about this?

**Comment by danielkerr** [comment]
If u can come up with a soultion then please post a better regx

**Comment by opencart-russia** [comment]
Universal regx solution is a very big.

In addition to the variants that I suggested, you can try to use punycode converter for correct validate https://github.com/true/php-punycode

And see  look at how others have solved https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/string/punycode.php#L195

**Comment by danielkerr** [comment]
check latest commit

**Comment by ADDCreative** [comment]
I don't think filter_var with FILTER_VALIDATE_EMAIL supports IDNs. See https://bugs.php.net/bug.php?id=39469. Wouldn't an email with an IDN would still need converting first?
