### ISSUE TITLE
When i whant delete order button not working.

### ISSUE THREAD

**Issue by Salman19933** [opencart/opencart#3621]
And when i whant edit order type error:
Notice: Use of undefined constant HTTPS_CATALOG - assumed 'HTTPS_CATALOG' in /home/dsstore/domains/digitalstore.az/public_html/admin/controller/sale/order.php on line 87Notice: Use of undefined constant HTTPS_CATALOG - assumed 'HTTPS_CATALOG' in /home/dsstore/domains/digitalstore.az/public_html/admin/controller/sale/order.php on line 98

**Comment by matrunchyk** [comment]
It seems you have wrong settings in your `config.php` files. Works for me.

**Comment by Salman19933** [comment]
In config.php file all is ok.
