### ISSUE TITLE
Cannot change status of order with last item avaliable

### ISSUE THREAD

**Issue by guiltar** [opencart/opencart#3623]
When any user orders the last avaliable item the corresponding order becomes uneditable.
It shows "Products marked with *** are not available in the desired quantity or not in stock!" when you try to edit the order status.

For example, you may order all avaliable "Canon EOS 5D" (5 Blue + 2 Red) in demo version and try to edit status of this order.

Tried on opencart 2.1.0.1  and 2.1.0.2_rc (today master from github).

It seems that script "thinks" I'm going to make new order with reserved items.
It doesn't consider that edited order **already** contains these items.

![2015-11-13 12 07 02](https://cloud.githubusercontent.com/assets/1562290/11142629/e16fb74a-89ff-11e5-9c19-e5883b5ef863.png)

![2015-11-13 12 06 05](https://cloud.githubusercontent.com/assets/1562290/11142628/e156ce1a-89ff-11e5-9006-660abf438aef.png)

![2015-11-13 12 09 52](https://cloud.githubusercontent.com/assets/1562290/11142630/e19c98f0-89ff-11e5-974a-0b49d666bbc0.png)

**Comment by danielkerr** [comment]
demo is not the latest version!

the issue is fixed but there are number of ways to fix the issue your having by just adding more stock!

**Comment by guiltar** [comment]
Thanks! Great to hear that!

**Comment by guiltar** [comment]
This bug still isn't fixed in 2.1.0.2. Same as other reported bugs.

**Comment by jamesallsup** [comment]
2.1.0.2 was not a release containing a lot of bug fixes. It was only to address 1 issue - please read the changelog.

The bugfixes will be part of the 2.2 release due soon.

**Comment by guiltar** [comment]
Ok, thanks!

**Comment by caiorg** [comment]
I know this issue was closed, but I'm using 2.2 version and facing this exact same issue.

I've created a product, set quantity to 1, minimum quantity to 1, subtract stock to Yes and yet I get the message "Products marked with *** are not available in the desired quantity or not in stock!" when I try to create an order through administration.

**Comment by guiltar** [comment]
@caiorg it's useless to ask @danielkerr to fix any bug.
The only things he can do is to to say it's not a bug, close the issue with some idiotic excuse.
Just check some examples and discussions to understand how stupid he is.
If you use opencart you should fix bugs yourself :)

https://github.com/opencart/opencart/issues/3792
https://github.com/opencart/opencart/issues/3298
https://github.com/opencart/opencart/issues/3797
https://github.com/opencart/opencart/issues/1373
https://github.com/opencart/opencart/issues/3298
https://github.com/opencart/opencart/issues/62
https://github.com/opencart/opencart/issues/1300
https://github.com/opencart/opencart/issues/1269
https://github.com/opencart/opencart/issues/1279
https://github.com/opencart/opencart/issues/1534
https://github.com/opencart/opencart/pull/1594
https://github.com/opencart/opencart/issues/3721

https://www.reddit.com/r/PHP/comments/41st43/opencart_users_switch_to_opencartce_immediately/

**Comment by caiorg** [comment]
@guiltar I'm kinda new to the community but also noticed what you said about @danielkerr 

Anyway... thx for your help and I'll definitely look through your links.

**Comment by guiltar** [comment]
@caiorg I've solved the problem by coding complete syncronisation with ERP (SAP-like). All the admin actions (edit catalog/products/prices/discounds/rests, handle orders and customers) in our system manager makes in ERP then data gets synchronised to opencart. And vice versa, any order or customer created in opencart gets synchronised to ERP.

So our managers have no need to login in admin panel, they work only in ERP. We use opencart just as frontend for customers.

**Comment by caiorg** [comment]
@guiltar That's my ultimate goal.
As I'm not part of my client's ERP's dev team, I can't go very deep. Luckily they're (the ERP team) very helpful and willingly to hear from us.

Thx again!

**Comment by guiltar** [comment]
@caiorg of course I've done that not only to solve this problem, but to solve many-many others.

To solve only this issue you may virtually add all the current order's products to stock. I.e. if you edit order consisting from 5 Canons and 2 Iphones you may virtually (not in DB) increase number of canons by 5 and increase number of iphones by 2. This may be done by some hook through globals, which is of course a poor way to code, but nothing else to do when the main dev is such...

**Comment by caiorg** [comment]
@guiltar Totally agree!

One thing I've noticed is that even if I click on **Cancel**, when I get back to Orders page, that order I've just "canceled" is there and I can work with it. Pretty weird. lol
