### ISSUE TITLE
Can't Use AWS SES 

### ISSUE THREAD

**Issue by haxcop** [opencart/opencart#3625]
Hi i have tried every way to connect with AWS SES SMTP but there's no available way to do it only with the credentials without modifying the code of OC. at least on the V2.0.3.1 
Is any solution to this issue?

**Comment by garbinmarcelo** [comment]
> Hi i have tried every way to connect with AWS SES SMTP but there's no available way to do it only with the credentials without modifying the code of OC. at least on the V2.0.3.1
> Is any solution to this issue?

Hi, sorry to answer this issue, but were you able to solve this problem? Did OpenCart work with AWS SES? If so, how to do it? Thanks

**Comment by haxcop** [comment]
> > Hi i have tried every way to connect with AWS SES SMTP but there's no available way to do it only with the credentials without modifying the code of OC. at least on the V2.0.3.1
> > Is any solution to this issue?
> 
> Hi, sorry to answer this issue, but were you able to solve this problem? Did OpenCart work with AWS SES? If so, how to do it? Thanks

I did at the time but I don't recall how unfortunately, I think it had something to do with using tls:// instead of SSL:// - looking into the forum of opencart for better support of someone who is actually using AWS SES - I'm using Google now
