### ISSUE TITLE
opencart-2.1.0.1 - PayPal Express Checkout Fatal Error

### ISSUE THREAD

**Issue by vimalnath53** [opencart/opencart#3626]
When using Paypal Express Checkout module, in the process of completing the checkout results in fatal error "Fatal error: Class 'Controllermodule' not found in C:\xampp\htdocs\training\opencart-2.1.0.1\opencart-2.1.0.1\upload\system\engine\loader.php on line 28"

Steps to Reproduce:
- Enable Express Checkout Module
- Buy some item, proceed with checkout.
- Takes you to PayPal checkout page(https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-0GG645720L489752C#/checkout/review)
- After loggging into PayPal account, the page redirects back to "/upload/index.php?route=payment/pp_express/expressConfirm" this page produces the fatal error "
Fatal error: Class 'Controllermodule' not found in C:\xampp\htdocs\training\opencart-2.1.0.1\opencart-2.1.0.1\upload\system\engine\loader.php on line 28"

Please someone look into this as this affects the PayPal merchants substantially. 
P.S This error only happens in new version 2.1.0.1
It was working fine in "opencart-2.0.3.1"

**Comment by dude2511** [comment]
Coupon/Reward/Voucher have been moved. Just edit the file `controller/payment/pp_express`, method `expressConfirm()`:
Find the line `$data['coupon'] = $this->load->controller('module/coupon');` 
and change it to `$data['coupon'] = $this->load->controller('total/coupon');`
Same for the the 2 lines below (voucher + reward):
`$data['voucher'] = $this->load->controller('total/voucher');`
`$data['reward'] = $this->load->controller('total/reward');`

**Comment by vimalnath53** [comment]
@dude2511 
Thanks for that. It works. But, is there any plan to update the opencart express checkout module on the same?
There are few merchants who use this plugin and I cannot ask all of them to update their code on their end.
Is opencart planning to fix this?

**Comment by dude2511** [comment]
I think only the module developer can answer to that.

**Comment by vimalnath53** [comment]
@dude2511
Ah okay. I am not sure how to contact the developer. Is there any way? Sorry I'm novice here.

**Comment by vimalnath53** [comment]
@dude2511 Ah okay. I am not sure how to contact the developer. Is there any way? Sorry I'm novice here.

**Comment by danielkerr** [comment]
im working on this now.

**Comment by danielkerr** [comment]
i think fixed now
