### ISSUE TITLE
Three issues that affect live store

### ISSUE THREAD

**Issue by Elitza85** [opencart/opencart#3628]
Hi,
I`ve read a lot in opencart forum about one of my three errors, I tried a few things but still cannot fix it:
1. I`m unable to change the order status: I have the following message: 
SyntaxError: Unexpected token
OK
<b>Notice<b/>:Undefined variable:json in <b>/home/..........admin/controller/sale/order.php <b/> on line<b>2490<b/>
2. My second error: When I try to buy voucher in language which is different from English, I get the following error message:
Warning:Cannot modify header information-headers already sent by(output.......
3. Third issue: The Estimate Shipping and Taxes calculator in the shopping cart during Checkout does not calculates correctly for currencies which are different from the default currency (it shows the price of the default currency and only changes the sign of the currency for different currencies). But when you continue to checkout in STEP 4 Delivery Method- then the correct shipping price appears- so the issue is only with the Estimate Shipping and Taxes calculator.

My online store is live and these issues are really annoying.
Any help please?
Thansk,
Elitsa

**Comment by danielkerr** [comment]
this has already been fixed. use the latest version or pay some one to add the updated code.
