### ISSUE TITLE
Sale - Order - add IP

### ISSUE THREAD

**Issue by opencart-russia** [opencart/opencart#3629]
What to do if  a ip dinamic ? Click click click, 10 ip per one day! 300 ip in month etc.

**Comment by danielkerr** [comment]
you have to add it every time.

**Comment by danielkerr** [comment]
do post crap like this again!

its petty! there is no issue!

all u do is click a button and it adds your IP!

its like complaining you have to enter a password everytime you login!

think before posting an issue!

**Comment by opencart-russia** [comment]
Daniel, don't swear. In Russia, there are many users with dynamic ip.
I just think and write complaints from users that it is convenient and what is not. And you decide to fix it or not.

**Comment by opencart-russia** [comment]
If you do not want to get complaints from users who tell me I'm not going to write any more. No problem.
