### ISSUE TITLE
cart->getTotal()

### ISSUE THREAD

**Issue by pine3ree** [opencart/opencart#3632]
Hello Daniel, 
please verify...

This method Cart::getTotal() is used by amazon_pay (module and payment controllers) and pp_express payment controller.
In my opinion the value returned by it is not very reliable for usage in comparisons (as in amazon_pay) since it depends on config_tax settings, so it can be the cart total with or without taxes.

...unless the desired effect for amazon_login_pay_minimum_total limit is to match exactly what the customer "sees" in the shop...but all other payment methods are using Cart::getSubTotal() method for the same purpose.

kind regards

**Comment by danielkerr** [comment]
i need to pass this onto james.

**Comment by pine3ree** [comment]
Sure Daniel,

as a side note: in my implementation i added a parameter $force_calculate_tax (default false), so when i need the cart product gross total i just pass true to the method.
```php
$calculate = $force_calculate_tax ?: $this->config->get('config_tax');
```
then i pass the $calculate var into the Tax::calculate(...) method inside getTotal()

kind regards
