### ISSUE TITLE
Login With Paypal OpenCart Version 2.1.0.1

### ISSUE THREAD

**Issue by rossual** [opencart/opencart#3640]
Hi, 
I'm having an issue with the login with paypal module

#In Error Log:
Log In with PayPal debug (ModelModulePPLogin::getTokens) - cURL Response: stdClass Object
(
    [error] => invalid_authz_code
    [error_description] => Authorization Code is invalid
)

#Pop Up window hangs on a white page
https://www.DomainNameReplaced.com/index.php?route=module/pp_login/login&scope=address+profile+email+phone&code=3qchtUYsheH9FIw3HzL6V-dvc2fbWRF0SHPg5d2WvLPShC9JoO0PytiNoVyXdw1KO7cS2qDD8iQU4cxDkKNBAVMpAfNL-61AfNcuiH_NPOWdLti0c3L2ah84lOnpqSFlrRkt49ozesWhnW9lzY9le4JFMCeLDDUWbGi1MuxyBaI8JuE8dzYv8sCcirZcdTIGRxtmWUW333eZ-HWd

**Comment by rossual** [comment]
I managed to fix with the following changes in /catalog/model/module/pp_login.php:

Change the API URLs
			//$endpoint = 'https://api.sandbox.paypal.com/v1/oauth2/token';
			$endpoint = 'https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice';
		
			//$endpoint = 'https://api.paypal.com/v1/oauth2/token';
			$endpoint = 'https://api.paypal.com/v1/identity/openidconnect/tokenservice';
				

Comment/remove line:
//CURLOPT_USERPWD    => $this->config->get('pp_login_client_id') . ':' . $this->config->get('pp_login_secret'),

**Comment by rossual** [comment]
Leaving open in case this needs changing in build, if not please close. :)

**Comment by stockmaster** [comment]
You got the new oauth link from Paypal documentation @rossual ?

**Comment by rossual** [comment]
Sure, I found the example code with URIs in "Step 3" here:

https://devtools-paypal.com/guide/openid/curl?interactive=OFF&env=sandbox

I'm new to OpenCart but very impressed so far! Apologies if I'm using GitHub incorrectly, my first time.

**Comment by stockmaster** [comment]
great ty, that way is documented so Daniel can look into it.

**Comment by davidteal** [comment]
Fixed in #3732
