### ISSUE TITLE
Recurring Profile Issues

### ISSUE THREAD

**Issue by jjpz** [opencart/opencart#3641]
I have recurring profiles set up for a product subscription and the product price set at $0. Whenever a recurring option is added to the cart, the price in the cart and throughout the checkout process shows as $0, and the only thing that gets charged is the shipping as a one time payment (I am using PayPal Express Checkout).

The reason why I have the product price set at $0 is because I noticed that when I did have a product price set (to something other than $0) it would also just go through as a one time payment (product price + shipping).

A recurring payment never seems to get charged and the recurring price never seems to correctly reflect in the cart.

Please help!

**Comment by mitymarcus** [comment]
I have the same issue!

**Comment by danielkerr** [comment]
ok i did some changes before and have just tested with the master branch and the recurring payment is working fine.

**Comment by danielkerr** [comment]
im closing this but will be testing the recurring payments when i test paypal express
