### ISSUE TITLE
Order edition error

### ISSUE THREAD

**Issue by alexascj** [opencart/opencart#3643]
hi,

I have an opencart 2.0.2 and for 1-2 month I can edit my orders I recive this two error and don`t know what to do.
I have an extension that uses API witch I need to be installed if it relevant.

The errors

Notice: CURL erro(0)!
Error You do not have permision to acces API

I tried several methods found online but still no luck

Thank you

**Comment by danielkerr** [comment]
ask your host to enable curl loopback

apart from that upgrade.

**Comment by alexascj** [comment]
Hei,

 

The curl is enabled and cURL Information => 7.38.0

 

Any thoughts?

 

 

Mersi,

Alexandra Dimitriu 

Mobile: +4 0736 644 074 <tel:%2B4%200736%20644%20074>

**Comment by stockmaster** [comment]
@alexascj the curl issue on pre 2.1 builds is common, and what causes it wasnt ever clear. If possible you should try to upgrade to the latest build of OC which has a new order management system. Details of this changes are above my skill set.
However upgrading this comes with a new set of challanges, so you should try it on a sandbox install, be sure all your themes, and extentions work propperlly. Also theres not a easy way to just Upgrade or migrate. 
I sugest you browse the forums for more info
