### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by gabrielsomoza** [opencart/opencart#3647]
Getting the following on master when trying to install using the web installer. Am I missing something?

```
( ! ) Fatal error: Call to a member function trigger() on null in [truncated]/opencart/upload/system/engine/loader.php on line 19
Call Stack
#	Time	Memory	Function	Location
1	0.0069	267416	{main}( )	.../index.php:0
2	13.2582	647888	Front->dispatch( ???, ??? )	.../index.php:85
3	13.2582	647976	Front->execute( ??? )	.../front.php:33
4	13.2582	648120	Action->execute( ???, ??? )	.../front.php:38
5	13.2585	663240	call_user_func_array:{[truncated]/opencart/upload/system/engine/action.php:43} ( ???, ??? )	.../action.php:43
6	13.2585	664000	ControllerStep1->index( )	.../action.php:43
7	21.8497	666488	Loader->controller( ??? )	.../step_1.php:23
```

**Comment by danielkerr** [comment]
your ,missing that its being worked on!

**Comment by gabrielsomoza** [comment]
Ok, glad to hear that! Would you be so kind to point me to *where* its being worked on? ;) A branch / another ticket I didn't see? 

Another question: why close this ticket? If the status of this is "its being worked on" then wouldn't it make sense to keep it open until the issue is resolved? Doing that would also help other in the future *see* that its something that's being worked on - instead of forcing them to report the issue all over again in order to find that out.

Also: did you notice I [made a PR](https://github.com/gabrielsomoza/opencart/commit/5c34bc00e4a4a3bdf2e390766ae60ae9b1c801ac) that fixes this particular issue? Not saying its THE solution cause its probably not, but at least it worked like a charm for me and it might at least help others as a temporal workaround.

I have to say its one of the most disappointing responses I got from an open source project. Some more info would be great: as someone who is evaluating OpenCart I need to get at least a sense of either what I'm doing wrong or when to expect I'll be able to properly evaluate the framework. Even something *as little as* acknowledging the PR would have gone a long way. What follows is what I learned about what I'm doing wrong:

For other people stumbling into this: "master" is not the correct branch to test this product on, because its not kept on a stable state. Go to the "releases" section, choose the latest release, and install from there. That's probably what we should all be doing with ANY project that we want to test, I learned my lesson with this one.

**Comment by BetaScripts** [comment]
https://github.com/opencart/opencart/issues/3597
As you can see, you got off easy...
User got banned for posting a bug report in the dev/bug tracker. :))

**Comment by gabrielsomoza** [comment]
Thanks for the reference. Just to be clear: I appreciate the hard work everyone is putting on this open-source project! (or any other one of course). 

Being a library author and maintainer myself, if several people kept complaining about the same issue, I'd make my own life easier by just leaving the ticket open until its fixed.

As far as banning people goes: I understand banning people who are outright disrespectful. I didn't mean any of that, I hope that's clear: all I did was find an issue an think "hey, maybe they don't know about it so I'll report it". So I don't think I should feel thankful that I "got off easy", as if I'm guilty of anything for just reporting an issue and being assertive about it. All I did was try to help.

A great talk with suggestions on how to deal with situations like these, from the creator of Composer: https://youtu.be/n42HhJln4Ag?t=16m56s

Anyway, that was it. I'm glad we could exchange some ideas and I appreciate the time you took off your busy schedules to address and issue you already knew existed!

**Comment by BetaScripts** [comment]
**Leaving a bug ticket open when people are complaining about it over and over again, means having common sense and logic.**

@gabrielsomoza Why are you even apologizing? For pointing out a bug and trying to help?
There are companies out there that PAY people to test their stuff, and hold in high value any kind of feedback they receive.
 We're all here to improve on a project, by pointing out bugs and fixing them.
``- @OpenCart you just get bashed and insulted for trying to help.``

I've been watching this repository for a while now, and there's only one person insulting everybody else, guess who:
https://github.com/opencart/opencart/pull/578#issuecomment-15529076
https://github.com/opencart/opencart/pull/142#issuecomment-8605092
https://github.com/opencart/opencart/issues/128#issuecomment-8302175
https://github.com/opencart/opencart/issues/2399#issuecomment-65173655
https://github.com/opencart/opencart/issues/2299#issuecomment-63839521

Have a good one!

**Comment by Mewporg** [comment]
I can't install the opencart it give me 

Error: Could not load template driver basic cache!

I speak with Cpanel Tech guys they told me 


The bug report links to a pull request with a new versions of the index.php for the installer script at https://github.com/gabrielsomoza/opencart/commit/5c34bc00e4a4a3bdf2e390766ae60ae9b1c801ac , which I've gone ahead and placed on your server. The error is no longer showing, but now it is showing

"Error: Could not load template driver basic cache!"

You will want to work the developers of OpenCart to get this issue resolved, as the issue is with their script which has an open bug report regarding this exact issue. I apologize for the inconvenience.

**Comment by gabrielsomoza** [comment]
@Mewporg my pull request was for a different issue. It won't fix yours. Additionally, it was rejected by OpenCart so neither them nor I will endorse it as a good solution for anything.

I suggest you contact a PHP developer to help you out with this.
