### ISSUE TITLE
 Moving Customers from one group to another: Warning: Please check the form carefully for errors!

### ISSUE THREAD

**Issue by pnair39** [opencart/opencart#3650]
Unable to move customers to different groups

<img width="1055" alt="screen shot 2015-11-21 at 2 27 37 pm" src="https://cloud.githubusercontent.com/assets/15057957/11320075/5360f690-905c-11e5-831a-d8a12172c49f.png">

**Comment by stockmaster** [comment]
OC version please?

**Comment by pnair39** [comment]
2.1.0.1 	October 6, 2015

**Comment by pnair39** [comment]
I am new to this? What I am doing wrong this is a legit bug tracking issue.

**Comment by aram-klonect** [comment]
also I have a same issue. I can't change the customer group. it's occurred same problem. How can I do?
