### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by sivi29y** [opencart/opencart#3655]
It is good that there is an API. But API is not really productive and useful - until there is documentation. 

Need to add example uses to api to source code and explain the architecture.

**Comment by stockmaster** [comment]
you mean this?
https://github.com/opencart/opencart/wiki/Modification-System

**Comment by xguntis** [comment]
no, it is not for API

**Comment by danielkerr** [comment]
api is not finished

**Comment by danielkerr** [comment]
also post this sort of stuff in the forums! this is for bug tracking not suggestions.

**Comment by sivi29y** [comment]
Ok. Thanks
