### ISSUE TITLE
Wrong option value displaying on edit product page after values being deleted.

### ISSUE THREAD

**Issue by MstrAnton** [opencart/opencart#3658]
Preconditions. Option with few selectable values.
Steps.
1. Go to any product and add few option values.
2. Go to option and delete some value.
3. Go back to product.
As we can see, deleted value was replaced by other value (in our case: we had Blue, and got Orange instead). Not sure is this right? See screens below.
![screen_before](https://cloud.githubusercontent.com/assets/16001655/11371647/38701d70-92d2-11e5-825b-5382d0ceec9c.png)
![screen_after](https://cloud.githubusercontent.com/assets/16001655/11371648/3874e404-92d2-11e5-92c8-54fd17e92972.png)

**Comment by danielkerr** [comment]
yes because you deleted the options! can you add a product after its been deleted!

don't edit orders if you know some options are no longer available.
