### ISSUE TITLE
Mail class sends SMTP 'EHLO' twice

### ISSUE THREAD

**Issue by kevstev01** [opencart/opencart#3659]
I'm using the /system/library/mail.php class in opencart 2 and it's sending the EHLO welcome handshake twice. For my requirements I've just commented out the first instance (lines 186 to 200) as I'm not using authentication to the local server and so only need the HELO handshake, which is working fine for me.
My knowledge of SMTP isn't great, but I think the EHLO command is needed before the STARTTLS is sent, hence it might have worked in some instances.

**Comment by danielkerr** [comment]
ok just test on gmail and works fine.

going to check a server setup locally.

**Comment by danielkerr** [comment]
ok spent all day testing this. installed mercury web server and con not replicate your issue. also you have provided no information such as mail server being used.

**Comment by kevstev01** [comment]
Sorry it's taken so long for you to debug Daniel.
Line 187 sends the EHLO command to the SMTP server and then line 225 sends
it again, so I commented out the first instance to remove the issue.
I'm using the hosting service at 1and1.co.uk (Linux) to host my shop, so
I'm not sure what SMTP mail server is in use.
