### ISSUE TITLE
Order status can't be updated, can't add a comment -v 2.1.01

### ISSUE THREAD

**Issue by myln8** [opencart/opencart#3663]
Hi

I have upgraded my OC from 2.0 to the last version (2.1.0.1)

All was ok, but now I see a problem (It is a big problem for me): The order status can't be updated, and I can't add any comment in the order history ...

The button is stuck to "loading" ...

Any ideea what could be?
![image](https://cloud.githubusercontent.com/assets/15151137/11380769/28c5e602-9309-11e5-8da9-87220200a44a.png)

**Comment by danielkerr** [comment]
delete and re add the api stuff

**Comment by PhamToan** [comment]
some time it cause by HTTPS. You can try with OCMOD file 
[fix_https_process_order_unzip.zip](https://github.com/opencart/opencart/files/230049/fix_https_process_order_unzip.zip)

you can contact to me for fixing if you can't do it!!
