### ISSUE TITLE
Opencart Coupon is not working properly

### ISSUE THREAD

**Issue by amitbala** [opencart/opencart#3664]
I am Using opencart 2.0, Beamstore theme, When i am assigning a coupon code for 1 user one 1 time use, But user can using The code Unlimited time,
Please sove my Problem.

**Comment by jimbob71** [comment]
I am having a similar issue that whatever information I put into Coupon, and then try to purchase - adding coupon code is doing nothing to the figures ?? anyone please help me. I am running OC 1.5.6.4

**Comment by amitbala** [comment]
check your order complete status, mark it all , then it will work

**Comment by danielkerr** [comment]
im closing this as im using 2.0 doe snot help.

will test the coupon system related to another issue opened
