### ISSUE TITLE
If product has min quantity, adding 1 of that item to cart changes to min amount

### ISSUE THREAD

**Issue by ChangePlaces** [opencart/opencart#3666]
2.1.0.1

If I have a product where min order is 5, and the user enters 1 into the quantity, 5 get added to the shopping cart without any sort of message. Either the adding to the cart should be refused with a message stating that 5 is the minimum (preferable), or a message stating that the 1 has been magically changed to 5 should be displayed to the user.

This is serious enough to warrant as a bug because buyers could order 1, unknowingly end up paying for 2 and charge back / return the whole lot, and see the seller as scammy!

**Comment by danielkerr** [comment]
its states minimum order on the product page. 

also if the product has options the buyer needs to be able to select a quantity for the different option types without the quantity changing to the minimum order.

**Comment by ChangePlaces** [comment]
My point is that the buyer may not see the minimum quantity and will complain wanting a chargeback, return, and unhappy customer. OC changes the quantity in the cart without warning the user.
