### ISSUE TITLE
OPEN CART COUPON NOT DOING WHAT IT IS SUPPOSED TO BE DOING !

### ISSUE THREAD

**Issue by jimbob71** [opencart/opencart#3672]
Whatever information I put into Coupon set up, and then try to purchase - adding coupon code is doing nothing to the figures ?? anyone please help me. I am running OC 1.5.6.4
 it used to work fine, only change is adding SSL certificate to site  although could be coincidence.

**Comment by jamesallsup** [comment]
Please use the forum for support or contact OpenCart support via website, this is for bug reports online.

**Comment by i-am-chris** [comment]
hello did you solve this?
