### ISSUE TITLE
Error: Could not load template /var/www/html/catalog/view/theme/common/column_left.tpl!

### ISSUE THREAD

**Issue by w4ilun** [opencart/opencart#3676]
Template directory is not correct:

```Notice: Error: Could not load template /var/www/html/catalog/view/theme/common/column_left.tpl! in /var/www/html/system/library/template/basic.php on line 26```

Should be ```view/theme/default/template/common/```

**Comment by danielkerr** [comment]
stop trying to fix things! 

im working on changing a lot off code! 

all your doing is just undoing the changes and going to cause issues if i try to commit.

**Comment by danielkerr** [comment]
wasting your time and mine!

**Comment by w4ilun** [comment]
Sorry about that, I was getting these errors on master branch, did not realize it was under development.
