### ISSUE TITLE
how to check whether ocmod is working properly or not

### ISSUE THREAD

**Issue by kalpeshdesai20** [opencart/opencart#3683]
I am using opencart 2.1.0.1 with vqmod 2.5.1 and non of extensions of ocmod working. It installing correctly but can't see on front side without any error. I don't why it happens I doubt on ocmod but how to check whether it is working properly or not.
I can share FTP if you guys can check the issues.

**Comment by kalpeshdesai20** [comment]
Hi
Why my issue has been closed?

**Comment by ADDCreative** [comment]
Because this is not a support forum. You need http://forum.opencart.com/ or http://www.opencart.com/index.php?route=support/support.
