### ISSUE TITLE
$shipping_method in orders

### ISSUE THREAD

**Issue by Red-Lolik** [opencart/opencart#3685]
I don't understand for what to save description of shipping method in oc_order table in DB?
When i add in description of one shipping method some HTML tags, i see that this field have limit for 128 symbols. This mean that in DB goes not full string of description. Only 128 symbols. And when i open order to edit something, i can't save it because shipping_method selector shows description that broke next selector (payment_method).
I think selectors must generates by another way. By shipping code, for examle.

**Comment by danielkerr** [comment]
it does not save the text in the select box but a hidden field.

try the order history table
