### ISSUE TITLE
Empty <title> at static information pages 2.1.0.1

### ISSUE THREAD

**Issue by dtinside** [opencart/opencart#3687]
Hi. On every static information page "title" tag is empty. But in control panel this field is not empty.
![notitle](https://cloud.githubusercontent.com/assets/4015892/11464437/da73e996-973f-11e5-8164-1a535962ad46.png)

**Comment by dangtienngoc** [comment]
You need set Meta tag title

**Comment by indragop** [comment]
Нашел решение?

**Comment by dtinside** [comment]
![sql_fill](https://cloud.githubusercontent.com/assets/4015892/11647549/4add5ee8-9d7a-11e5-9038-f8e4a0689c93.png)
As you can see  Meta tag title has been filled. But I cant see it on the pages of front-end.
