### ISSUE TITLE
OC 2.1.0.1 modification.xml bugs

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#3691]
The 'system/modification.xml' contains amongst others this line:
```
  <file path="system/{engine,library}/{action,loader,config,language}*.php">
```

This line is wrongly processed in admin/controller/extension/modification.php at line 158, as follows:
```
					$files = explode(',', $file->getAttribute('path'));
```
It gets the wrong files:
'system/{engine', 'library}/{action', 'loader', 'config' and 'language}*.php'

Suggested fix in 'system/modification.xml':
```
  <file path="system/engine/action.php,system/engine/loader.php,system/library/config.php,system/library/language.php">
```

**Comment by opencart-russia** [comment]
see https://github.com/opencart/opencart/blob/master/upload/admin/controller/extension/modification.php#L157

```
$files = explode('|', $file->getAttribute('path'));

**Comment by mhcwebdesign** [comment]
Sorry, my mistake, it's not a bug, I had the wrong file from a previous version.

This issue can be closed!

**Comment by danielkerr** [comment]
im hoping people will move over to the events system when that is done
