### ISSUE TITLE
How to install and configure OpenCart on NGINX

### ISSUE THREAD

**Issue by vivekkiran** [opencart/opencart#3692]
How to install and configure OpenCart on NGINX instead of Apache Server.

**Comment by apsega** [comment]
Install Nginx and PHP-FPM. You also need to install these additional PHP extensions:

    php-mysql
    php-gd
    php-mcrypt

Then, edit ``nginx.conf`` so that PHP scripts are being handled by ``FastCGI``, i.e.:

    location ~ \.php$ {
                fastcgi_pass   127.0.0.1:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                fastcgi_max_temp_file_size 0;
                include        fastcgi_params;
                fastcgi_param REMOTE_ADDR $http_x_real_ip;
    }
