### ISSUE TITLE
Permission issues while installing (Step 2)

### ISSUE THREAD

**Issue by apsega** [opencart/opencart#3693]
Getting ``images/cache/`` and ``images/catalog`` unwritable even if I'm chmod'ing to 0666 or 0777:

    mode of „config.php“ changed from 0755 (rwxr-xr-x) to 0666 (rw-rw-rw-)
    mode of „admin/config.php“ changed from 0755 (rwxr-xr-x) to 0666 (rw-rw-rw-)
    mode of „image/“ changed from 0755 (rwxr-xr-x) to 0666 (rw-rw-rw-)
    mode of „image/cache“ changed from 0755 (rwxr-xr-x) to 0666 (rw-rw-rw-)
    mode of „image/catalog“ changed from 0755 (rwxr-xr-x) to 0666 (rw-rw-rw-)
    mode of „system/storage/cache/“ changed from 0755 (rwxr-xr-x) to 0666 (rw-rw-rw-)
    mode of „system/storage/logs/“ changed from 0755 (rwxr-xr-x) to 0666 (rw-rw-rw-)
    mode of „system/storage/download/“ changed from 0755 (rwxr-xr-x) to 0666 (rw-rw-rw-)
    mode of „system/storage/upload/“ changed from 0755 (rwxr-xr-x) to 0666 (rw-rw-rw-)
    mode of „system/storage/modification/“ changed from 0755 (rwxr-xr-x) to 0666 (rw-rw-rw-)
    mode of „image/cache“ changed from 0666 (rw-rw-rw-) to 0777 (rwxrwxrwx)
    mode of „image/catalog“ changed from 0666 (rw-rw-rw-) to 0777 (rwxrwxrwx)

![pre-installation](https://cloud.githubusercontent.com/assets/15917655/11529115/89e7a494-98f3-11e5-97b7-cbf93ffbdbc8.png)

Does anyone have any ideas how to fix this?

**Comment by osworx** [comment]
Ask your provider!
Beside this, 0777 should be never used!
I guess - depends on server settings, that is why ask your provider - that it should be 0700, 0750 or (as it should be always) 0755

**Comment by apsega** [comment]
It's on my home server. Anyway, looks like a bug, as other directories are getting writable.

**Comment by apsega** [comment]
Looks like when I firstly chmod ``images/cache`` and ``images/catalog`` to 0666 and then ``images/`` to 0777 everything works fine.
