### ISSUE TITLE
Admin => System => Settings => Edit => Google tab is removed.

### ISSUE THREAD

**Issue by devenpateldp** [opencart/opencart#3694]
I had done upgrade from 2.0.3.1 to 2.1.0.1.

I see lot of difference in settings file and main thing my site analytic is down.

Notice: Undefined variable: icon in /var/www/projects/xxxxx/catalog/view/theme/handletrade/template/common/header.tpl on line 20 Notice: Undefined variable: google_analytics in /var/www/projects/xxxxx/catalog/view/theme/handletrade/template/common/header.tpl on line 39

I see in admin 
Admin => System => Settings => Edit => Google tab is removed.
Google tab is removed.

**Comment by drkskwlkr** [comment]
@devenpateldp: I don't remember how it was done before, but Google Analytics in 2.1.0.1 is handled via a module. Go to Extensions => Analytics, enable Google Analytics (via green button) and add your tracking code (via red 'edit' button).

Does that work for you?
