### ISSUE TITLE
ModelModulePPLogin::getTokens() has an outdated TokenService endpoint.

### ISSUE THREAD

**Issue by syslogic** [opencart/opencart#3695]
"Login with PayPal" only returns the user_id unless changing the endpoint of the TokenService:
``` $endpoint = 'https://api.paypal.com/v1/identity/openidconnect/tokenservice'; ```
scope ```https://uri.paypal.com/services/paypalattributes``` seems to be missing, too.

**Comment by syslogic** [comment]
like this the option can be switched on/off - the additional account fields should get returned (while they are not yet used on account creation nor updated on user login). not sure if there are some kind of account attributes which PayPal/Amazon/etc all share, that would allow the extension of customer table columns.

**Comment by syslogic** [comment]
important: the configured scopes always need to match those configured for the application: 
https://developer.paypal.com/developer/applications/ -> "Log In with PayPal" -> "Advanced options".

**Comment by syslogic** [comment]
also noticed that Sandbox and Live credentials have two fully-independent configurations for the accessible scopes. the form should have two columns - one side for Sandbox, the other side for Live - in order to represent a PayPal Application - incl. both credentials, all at a glance.

**Comment by davidteal** [comment]
Hi syslogic.

As the extra fields aren't used in OpenCart, we don't need the additional scope to bring the data through. 

The wiki explains the scopes you need to enter whilst setting up the module: https://github.com/opencart/opencart/wiki/Log-In-with-PayPal

Modules/Payment Gateways in OpenCart don't usually have separate fields for Sandbox/Live environments so I don't think this is necessary.

Thanks.

**Comment by syslogic** [comment]
@davidteal other's don't - while this one has two individual endpoints. just thought it would make sense to have the account status availble - eg. to only allow login for verified accounts or even only of type `BUSINESS` for B2B.  have got an alternate version, which blends better into themes.
