### ISSUE TITLE
opencart meta description meta tag closing tags

### ISSUE THREAD

**Issue by shadowcurtains** [opencart/opencart#3697]
i have realized there is a problem with the meta data tags on each page such as the meta description and key words etc. 
the coding is as follows <meta name="description" content="text_here" />
however i need to change the ending tag on this from " /> to just ">
how can i achieve this thank you

**Comment by osworx** [comment]
Just to be curious: and why?

**Comment by shadowcurtains** [comment]
because google is having diffculties finding the tags the usual format google looks for is 
<head>
	<meta name="description" content="type_here_your_description">
</head>

but on opencart its 

<head>
	<meta name="description" content="type_here_your_description " />
</head>

**Comment by osworx** [comment]
Guess you do not know what about you are talking ..
Beside this, here is not the right place to ask such - use the OpenCart Forum.

**Comment by stockmaster** [comment]
Is this a type of "fill in the blank" game issue? i am confused

**Comment by jamesallsup** [comment]
@shadowcurtains , @osworx is correct, use the forum for questions please - this is not a bug.

@stockmaster - I think he forgot to quote the tags in code blocks
