### ISSUE TITLE
Column ordering of Related Products was wrong

### ISSUE THREAD

**Issue by Hasonk** [opencart/opencart#3698]
The column ordering is okey when display on the maximize of browser window.
But when the Bookmark Window of FireFox is opened or the browser window is draged to minimize, the ordering of columns always go bad.
![column-ordering](https://cloud.githubusercontent.com/assets/16137250/11564727/3aaed0da-9a0d-11e5-8cc4-6722f18c05d5.jpg)

**Comment by dodiaraculus17** [comment]
I'm building a shop system and I hope you can try it, I have fixed this on my system and I would like you to try it, please tell me what you think. https://github.com/Tecflare-Corporation/Easy-Large-Websites

**Comment by jamesallsup** [comment]
Cannot replicate the issue. Tested on FF & Chrome at the latest build.

http://jenkinsbuild.ecommercehq.co.uk/oc_74/upload/index.php?route=product/category&path=18
