### ISSUE TITLE
Google captcha with telephone

### ISSUE THREAD

**Issue by nuke123** [opencart/opencart#3700]
Google captch still contains telephone field: 
catalog/view/theme/default/template/captcha/google_captcha.tpl

https://github.com/opencart/opencart/issues/3462

**Comment by jamesallsup** [comment]
Please DO NOT open new tickets about the same problem, post an update on the existing thread (even if closed) with proof of the bug. Daniel referenced a commit after your report:

https://github.com/opencart/opencart/commit/577754ad9af63cb3ad81160c8abee185fb45ba01

Ensure you have a clean install of the latest MASTER to verify.
