### ISSUE TITLE
cannot login to api 2.1.0.1 

### ISSUE THREAD

**Issue by sivi29y** [opencart/opencart#3701]
Not sure if it ia  a bug however 
cannot log into the api with current api  for few days.

"error":{"key":"Warning: Incorrect API Key!"}}" 

Did not see anyone mention it in the forum. I suspect it is the authenticion key I am missing 
.. BASE  ..... 
However I do not know where should I state this key in the cms interface httaccess database or somwhere else?   

http://forum.opencart.com/viewtopic.php?f=10&t=137250

**Comment by jamesallsup** [comment]
Please use the forum for community support or contact OpenCart support via the website.
