### ISSUE TITLE
Security possible bug 2.1.0.1  mysql_real_escape_string deprecated

### ISSUE THREAD

**Issue by sivi29y** [opencart/opencart#3702]
escape() uses mysql_real_escape_string,mysql  -- which is deprecated possible sql injections.

**Comment by jamesallsup** [comment]
Don't use mysql, it is legacy and remains for people on older servers who require/want it. MySQLi is the correct one to use and should be the default during install.

http://php.net/manual/en/mysqli.real-escape-string.php
https://github.com/opencart/opencart/blob/master/upload/system/library/db/mysqli.php#L46

vs (old one)

http://php.net/manual/en/function.mysql-real-escape-string.php
https://github.com/opencart/opencart/blob/master/upload/system/library/db/mysql.php#L62
