### ISSUE TITLE
Cannot completely "disable" OCMOD extension

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#3703]
Using OCMOD with Opencart 2.1.0.1 - if I go to 

`Extensions > Modifications > Modification List`
and click on `disable` icon for any extension in the list, 

then click
- `Clear`
- `Refresh`

it still works and modifies files!

After this issue, I did install VQMod Manager 3.0, was able to 'Uninstall' modification.

Is this 'by the design' or there is problem somewhere?

**Comment by nuke123** [comment]
Check the modification is disabled in the database. Then debug this file to see what is going on where is manually checks the status:
admin/controller/extension/modification.php

```php
// Get the default modification file
$results = $this->model_extension_modification->getModifications();

foreach ($results as $result) {
	if ($result['status']) {
		$xml[] = $result['xml'];
	}
}

**Comment by danielkerr** [comment]
maybe a file system issue with the server. login via ftp and delete all the files manually.

**Comment by danielkerr** [comment]
im closing this as i think you are the only one having these issues.

**Comment by arnisjuraga** [comment]
Ok, I will debug and report it again if I face it.
