### ISSUE TITLE
A match of the Shipping Address City, State, and Postal Code failed

### ISSUE THREAD

**Issue by vapebe** [opencart/opencart#3704]
hi,guys,i use the opencart v1.5.6

When i use Paypal Express Checkout, payments are received by paypal, but paypal does not receive an address from the customer, and therefore the order is not covered by the protection program.

I found the following relevant threat:

https://github.com/opencart/opencart/issues/2027 

which recommends the following fix:

https://gist.github.com/thiscreative/66 ... 8062a36779 

But this fix does not work as I get the following error when I try to checkout:

A match of the Shipping Address City, State, and Postal Code failed.

I would greatly appreciate your help in solving this mystery.

Thanks in advance!

**Comment by vapebe** [comment]
I double-checked my address and everything is correct, just as shown below. I have also checked the address in my Paypal account and it matches.not know where the error is,you guys can help me please?

thanks

John

**Comment by danielkerr** [comment]
this is anot a Q&A
