### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by pine3ree** [opencart/opencart#3707]
I believe it would be useful to have a 'both' (meaning both shipping and payment) value for

config_tax_customer
config_tax_default

When a customer logs in I want his/her default address to be used both as shipping (for shippable product tax calculation) and payment address (for downloadable/electronic/digital product  tax calculation) for tax calculation, if not already set in the user session.

Same (but less important) for the store address when customer is not logged in.

REASON:
if i, from England, log in a German shop and  config_tax_customer is set to 'shipping', shippable products will have tax calculated for England as destination, while downloadable products (based on payment address) will not be calculated or calculated for the store address (Germany) if config_tax_default is set to 'payment'.

It would mean just a few small changes to the tax class (just one more "||"ed check with === 'both') and the admin setting area.

kind regards

**Comment by jamesallsup** [comment]
http://opencart.uservoice.com/
