### ISSUE TITLE
HTTPS ajax errors

### ISSUE THREAD

**Issue by RamonSmit** [opencart/opencart#3714]
Hello, 

We're using https for our store, but we ran into an problem. In this file: https://github.com/opencart/opencart/blob/master/upload/admin/view/template/sale/order_info.tpl#L506

the ```$store_url``` didn't change to https url. We did a little work around for now by replacing ```$store_url``` with the ```HTTPS_CATALOG``` constant. 

Is someone willing to check if you can reproduce this problem? 

Cheerios

**Comment by GomDani** [comment]
I made these changes, 

https://github.com/opencart/opencart/issues/3536

**Comment by RamonSmit** [comment]
@GomDani :+1:

**Comment by billynoah** [comment]
Just ran in to this same issue.  Looks like it's new in 2.1.0.1.  Not sure if  the API is multistore sensitive.  If so then using HTTPS_CATALOG might break if order does not belong to main store.

Here's a vqmod workaround:

<?xml version="1.0" encoding="UTF-8"?>
	<modification>

		<id>Load API Over SSL</id>
		<version>1.0</version>
		<vqmver>2.4</vqmver>
		<author>zuma design and print • billynoah@zuma-design.com</author>

		<file name="admin/controller/sale/order.php">
			<operation>
				<search position="after"><![CDATA[$data['store_url'] = $order_info['store_url'];]]></search>
				<add><![CDATA[
				$data['api_url'] = ($this->request->server['HTTPS'] ? 'https://' : 'http://') . basename($order_info['store_url']) . '/';
				]]></add>
			</operation>
		</file>
		<file name="admin/view/template/sale/order_info.tpl">
			<operation>
				<search position="replace"><![CDATA[<?php echo $store_url; ?>index.php?route=api]]></search>
				<add><![CDATA[<?php echo $api_url; ?>index.php?route=api]]></add>
			</operation>
		</file>

	</modification>

**Comment by danielkerr** [comment]
ok should be fixed with the latest commit. if not open another issue.
