### ISSUE TITLE
Affiliate Change

### ISSUE THREAD

**Issue by djeby** [opencart/opencart#3719]
Hello,
I am interested in modifying the affiliate section.

I want to remove the check and bank transfer options, and set the primary payout option to paypal.
My OC version is 2.0.3.1

How can i do that?

I want check and bank transfer removed.

**Comment by djeby** [comment]
Why did you close it?

**Comment by ADDCreative** [comment]
This is a bug tracker, not a support forum. You want http://www.opencart.com/index.php?route=support/support.
