### ISSUE TITLE
EHLO and RCPT errors on mail.php

### ISSUE THREAD

**Issue by gsc1ugs** [opencart/opencart#3720]
Hi mails have stopped for orders, getting errors when i want to notify customer or order status

first it was
2015-11-19 18:37:55 - PHP Notice:  Error: RCPT TO not accepted from server! in /home/garyjacobjack/public_html/system/library/mail.php on line 344

now

2015-12-07 10:39:35 - PHP Notice:  Error: EHLO not accepted from server! in /home/garyjacobjack/public_html/system/library/mail.php on line 197

I notice a view event changes to this file mail.php where do I download please and try events?

**Comment by prhost** [comment]
+1

**Comment by gsc1ugs** [comment]
What does +1 mean please?

**Comment by gsc1ugs** [comment]
Ok got emails working changing SERVER_NAME TO SERVER_ADDR but still getting errors in error log and dialogs

**Comment by gsc1ugs** [comment]
The problem still persists, the order emails are not coming through, could this be my server updated? I have made no changes

**Comment by gsc1ugs** [comment]
Anybody on this please? spoke to my servers, their end is fine

**Comment by gsc1ugs** [comment]
231 					while ($line = fgets($handle, 515)) { 
232 						$reply .= $line; 
233  
234 						if (substr($line, 3, 1) == ' ') { 
235 							break; 
236 						} 
237 					} 
238  
239 					if (substr($reply, 0, 3) != 250) { 
240 						trigger_error('Error: EHLO not accepted from server!'); 
241 						exit(); 
242 					}

**Comment by adrianuf22** [comment]
This error occurs when the email server configuration is wrong or incomplete or the server is down.

First, check the SMTP Hostname, if your server use TLS or SSL, you will should type the hostname like this:

tls://[your SMTP Hostname] or ssl://[yout SMTP hostname]

Before, I used a SMTP hostname without tls:// or ssl:// at begin of the address, but now, my server dont accept no connection without the protocol at hostname.

To resolve the server connection down trouble I created an isolated controller to set order status, so, the order never will be lost.

If you call the "addOrderHistory" method twice, at the second time the error will not appear and the order will be writing, and so, you can create a log file reporting the error or notify the store admin by another way.

**Comment by gsc1ugs** [comment]
Should this be added to the file mail.php? Its strange because nothing has been modified, it just started happening all of a sudden

**Comment by adrianuf22** [comment]
No, the protocol should be added in the SMTP hostname at e-mail server configuration page (Admin panel > System > Settings > Store > E-mail

![image](https://cloud.githubusercontent.com/assets/721525/11671874/671197be-9df2-11e5-9194-36edc8399326.png)

**Comment by gsc1ugs** [comment]
So if mine now is admin@mysite.com

I now use

Tls://mysite.com
?

**Comment by gsc1ugs** [comment]
Ok, some update, CHANGED to tls://mysite.com errors are still being recorded and the initial order confirmation email fails to come, still shows

PHP Notice:  Error: EHLO not accepted from server! in /public_html/system/library/mail.php on line 201

**Comment by gsc1ugs** [comment]
Hi danielkerr , have you any ideas on this please?

**Comment by adrianuf22** [comment]
Oh, really? That shame...

What's the port number that you use to connect to the server mail?

25: No security protocol (AUTH)
465: SSL protocol
587: TLS protocol / AUTH too

This can appear idiot, but, after I used server 1&1 I don't ignore this check.

**Comment by gsc1ugs** [comment]
OK, ok, ok, we are getting somewhere, I got an order confirmation email, and it updates, im still getting the PHP Notice:  Error: EHLO not accepted from server! though, on first click comes up, second click doesn't, thanks you so far though..

**Comment by gsc1ugs** [comment]
Still got this problem, im baffled, what is goin on

**Comment by gsc1ugs** [comment]
Have protocols chnaged?

**Comment by jamesallsup** [comment]
Please use the forum to discuss your issue, this is the bug tracker and every comment is filling up peoples inbox which is not related to the core code.

http://forum.opencart.com/
