### ISSUE TITLE
svg file resize issue

### ISSUE THREAD

**Issue by baisoo** [opencart/opencart#3724]
when upload svg file, this will create a cache file with setting file size, the image.php resize function has issue

**Comment by danielkerr** [comment]
svg is jot supported its also not an image

**Comment by danielkerr** [comment]
also dont waste my time! svg dont need resizing!

**Comment by baisoo** [comment]
when open the upload dialog to upload svg file, when uploaded success, the image will show as a thumbnails, the thumbnails on the cache directory, but the thumbnails does not exist

**Comment by danielkerr** [comment]
Svg us not supported! Its not an image file. Its a vectory graphic. Srop wasting my time
