### ISSUE TITLE
error in Xtensions-Best Checkout and Customer Solution extension

### ISSUE THREAD

**Issue by shrutishah14** [opencart/opencart#3725]
I have purchased this extension but when i goint to edit from admin site i am getting error like below .Please provide us better solution to resolve this issue.
Fatal error: Call to a member function getData() on a non-object in /home/u2ushop/public_html/admin/controller/module/signup.php on line 8

**Comment by saifwebberoo** [comment]
which extension purchased?


*Thanks, Looking Forward*

* <http://webberoo.in/images/webberoo-logo.png>Saif Sulaiman*
*Technical lead*
www.webberoo.In <http://webberoo.in/>

*Mobile *         : *+91 9633555007, +91 4922 222810*
*Official Emails* : *saif@webberoo.com.au <saif@webberoo.com.au>,
saif@webberoo.in <saif@webberoo.in>*
*Skype *          : *saif.silver*

**Comment by shrutishah14** [comment]
I have purchased  this Xtensions-Best Checkout and Customer Solution extension.

**Comment by shrutishah14** [comment]
Hello sir,

I have purchased  Xtensions-Best Checkout and Customer Solution.



Regards,
[cid:image001.jpg@01D0A204.4AE8BD00]

Shruti Shah
Web developer

808B | AA1 Tower | Al Mazaya Business Avenue
JLT | Dubai | United Arab Emirates
D: +971 4 4419202| M: +971 552948248
E: shruti.shah@cloudrangers.com<mailto:shruti.shah@cloudrangers.com>
URL: www.cloudrangers.com<http://www.cloudrangers.com/>

**Comment by saifwebberoo** [comment]
hi,

please share the extension url please. which you purchased/


*Thanks, Looking Forward*

* <http://webberoo.in/images/webberoo-logo.png>Saif Sulaiman*
*Technical lead*
www.webberoo.In <http://webberoo.in/>

*Mobile *         : *+91 9633555007, +91 4922 222810*
*Official Emails* : *saif@webberoo.com.au <saif@webberoo.com.au>,
saif@webberoo.in <saif@webberoo.in>*
*Skype *          : *saif.silver*

**Comment by shrutishah14** [comment]
Hi ,

This is the url from where I purchased.
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=20736

[cid:image001.jpg@01D0A204.4AE8BD00]

Shruti Shah
Web developer

808B | AA1 Tower | Al Mazaya Business Avenue
JLT | Dubai | United Arab Emirates
D: +971 4 4419202| M: +971 552948248
E: shruti.shah@cloudrangers.com<mailto:shruti.shah@cloudrangers.com>
URL: www.cloudrangers.com<http://www.cloudrangers.com/>

**Comment by saifwebberoo** [comment]
sorry this is not ours.

http://xtensions.in/support/

its not working their support.


we are another service provider.
if you want  we can provide paid support.

contact on skype: saif.silver


*Thanks, Looking Forward*

* <http://webberoo.in/images/webberoo-logo.png>Saif Sulaiman*
*Technical lead*
www.webberoo.In <http://webberoo.in/>

*Mobile *         : *+91 9633555007, +91 4922 222810*
*Official Emails* : *saif@webberoo.com.au <saif@webberoo.com.au>,
saif@webberoo.in <saif@webberoo.in>*
*Skype *          : *saif.silver*

**Comment by jamesallsup** [comment]
Read the readme on GitHub, This has got nothing to do with OpenCart core! Use the forum or support form here: http://www.opencart.com/index.php?route=support/contact

**Comment by shrutishah14** [comment]
Hi,

So why is it showing in opencart.com . Can you please briefly explain me what I need to do.

[cid:image001.jpg@01D0A204.4AE8BD00]

Shruti Shah
Web developer

808B | AA1 Tower | Al Mazaya Business Avenue
JLT | Dubai | United Arab Emirates
D: +971 4 4419202| M: +971 552948248
E: shruti.shah@cloudrangers.com<mailto:shruti.shah@cloudrangers.com>
URL: www.cloudrangers.com<http://www.cloudrangers.com/>
