### ISSUE TITLE
Admin Menu Controller - Broken Customer links

### ISSUE THREAD

**Issue by redasakhi** [opencart/opencart#3733]
Hi,
I've installed a fresh 2.1.0.1 on my server, then i have noticed that when i access Customers section(and sub sections) form the admin control panel it throws an Access Denied error message.
So i looked for the reason why.
The Menu links point on "sale/customer", "sale/..." instead of "customer/customer" and "customer/..." in the controller at "admin/".
Edit : Also customer_ban_ip.php file is missing among the controllers! but still used in the menu controller.

**Comment by danielkerr** [comment]
does not have this issue on the master branch
