### ISSUE TITLE
Image resize tool on white background, create gray lines or gray pixels

### ISSUE THREAD

**Issue by abiani** [opencart/opencart#3734]
Image resize tool, after resizing creates gray lines or gray pixels on white background of images.

<b>Original image before resize 1300x1950</b>
![gi7521756_1](https://cloud.githubusercontent.com/assets/15847718/11740588/266b16ac-9ffc-11e5-9642-3cedb145e38c.jpg)
<b>After resize 1200x1800</b>
![gi7521756_1-1200x1800](https://cloud.githubusercontent.com/assets/15847718/11740592/2add1f00-9ffc-11e5-8cd2-c44d3154e7ed.jpg)
<b>After resize 370x555</b>
![gi7521756_1-370x555](https://cloud.githubusercontent.com/assets/15847718/11740593/2dcd7390-9ffc-11e5-8c1d-2c1f826a2012.jpg)

**Comment by danielkerr** [comment]
Then resize it manually and reupload

**Comment by abiani** [comment]
Thankyou for reply. Thankyou for Opencart.
You mean after manual resize upload images to image cache folder? (in all config image sizes)
(that issue have in all 2.x.x.x versions)

**Comment by Troxya** [comment]
Still using oc 2.0.1.1 and tried everything to remove it as well. Resizing images doesn't help. Neither formats (jpg, png, transparent or not). Neither changing web browser. It just stay. It must be due to some OC custom compression

**Comment by danielkerr** [comment]
no oc custom compression!

opencart uses the default php gd library for resizing.

i also believe the issue is based on the background not being completely white.
