### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by ChangePlaces** [opencart/opencart#3736]
When automatically creating resized images, white borders are added either above or below the image. This is undesirable most of the time, so can the image width and height be calculated as close to the max size for images that's set in the admin, and then when the image is created, instead of the image being set to the actual max size, the calculated size is used.

**Comment by danielkerr** [comment]
yoiu need to edit the images manually to stop this. opencart uses the gd library built into php.

**Comment by ChangePlaces** [comment]
uhm, gd is capable to creating transparent images. you're doing it wrong.
