### ISSUE TITLE
When using new theme, it still uses the default css file

### ISSUE THREAD

**Issue by ChangePlaces** [opencart/opencart#3737]
I have a new theme set up and switched to use it, but the default theme css file is being pulled in the header. It's using the template files of the new theme.

I realise it has to be changed in the header, but shouldn't it pull the directory of the actual theme and use that automatically?

**Comment by ChangePlaces** [comment]
i'll take that as "i disapprove" then

**Comment by drkskwlkr** [comment]
@ChangePlaces You should take that as "This is a bug tracker for OpenCart and not a support forum for vague problems with unnamed 3rd party themes". Neither is this a place to complain about the way OpenCart works as in [#3673](https://github.com/opencart/opencart/issues/3673) where you wrote about a non-issue with URLs that would be trivial to fix via .htaccess rules.

Peace.

**Comment by ChangePlaces** [comment]
@drkskwlkr Oh hello. This is a bug tracker. It's for reporting bugs. Not for getting to know each other, nor is it highschool. A bug tracker is for suggestions and bugs. You may not like reading something, so don't comment in it. As for the "non-issue" of #3673, then I wish you well in your online commercial endeavours.

**Comment by jamesallsup** [comment]
NO, this is not the place to make suggestions. It is also not the place to vent your unwanted opinions like you did on the other thread. 

Read the readme! https://github.com/opencart/opencart
