### ISSUE TITLE
image resizing and transparency

### ISSUE THREAD

**Issue by ChangePlaces** [opencart/opencart#3741]
When automatically creating resized images, white borders are added either above or below the image. This is undesirable most of the time, so can the image width and height be calculated as close to the max size for images that's set in the admin, and then when the image is created, instead of the image being set to the actual max size, the calculated size is used.

GD is capable of creating transparent images, so should not leave such a border. If the correct dimensions were passed to GD in the first place, there would be no white border

**Comment by danielkerr** [comment]
stop posting issues! your wasting my time!
