### ISSUE TITLE
Admin Dashboard is all jumbled up

### ISSUE THREAD

**Issue by caliberfitness** [opencart/opencart#3746]
Did a clean install of Opencart 2.1.01 and when I log into the Admin dashboard, it is all jumbled up and unreadable.  Last time I saw this, it had something to do with the stylesheet in admin but not sure if its the same thing or is the config has a wrong path.  Cannot tell
![screenhunter_43 dec 17 22 35](https://cloud.githubusercontent.com/assets/4172595/11888705/ba8323c2-a50e-11e5-8d1c-1ad7c6b5d5ae.jpg)

**Comment by danielkerr** [comment]
reupload or download thge one from the opencart download page
