### ISSUE TITLE
Worldpay Stored Cards Functionality

### ISSUE THREAD

**Issue by virtualLast** [opencart/opencart#3748]
This is not working, i have been on the phone to Worldpay who can see the token generation taking place, but nothing happens from Opencart once that has been sent. I assume OC is supposed to then send more info back over to Worldpay. I have attached some screen shots of the curl requests. This is all the debug data I have as there are no records being saved to the DB and nothing reaching Worldpay. I am using OC 2.0.1.3
![screen shot 2015-12-17 at 12 26 07](https://cloud.githubusercontent.com/assets/2872439/11899585/c76a368c-a597-11e5-8dbb-8209ddca7487.png)
![screen shot 2015-12-17 at 12 26 47](https://cloud.githubusercontent.com/assets/2872439/11899584/c7643c3c-a597-11e5-8c45-962e7d5105d0.png)

**Comment by virtualLast** [comment]
before people mention it...I have blanked out the clientKey and the web address

**Comment by chris-wm** [comment]
@virtualLast Hi, I believe this is because of a change made to Worldpay's js library and I am in contact with them at the moment. I will implement any required fix in to the next release of OC and update this ticket.
