### ISSUE TITLE
Config.php bad setup

### ISSUE THREAD

**Issue by Bertuzb** [opencart/opencart#3749]
Why are the 2 config.php files (root-dir and /admin) set-up so badly? We should have a single definition for the `ROOT_PATH` or whatever the name should be, which is then used for the other definitions.

We dont have to edit every single line in the config.php this way, when we are changing server setup.

In other words: an opencart installation should have less references to the actual installation directory.

**Comment by jamesallsup** [comment]
This is a big tracker, not a suggestion or opinion place. Read the readme located in the root of the project.
