### ISSUE TITLE
images with symbol # in name not show, OC 2.1.0.1

### ISSUE THREAD

**Issue by maxinfosoft** [opencart/opencart#3751]
Images with symbol # in name not show, OC 2.1.0.1

**Comment by drkskwlkr** [comment]
@maxinfosoft : This is *not* a problem of OpenCart you should not be using ambiguous characters when naming your files and folders for the web.

Use of the # sign inside URLs without encoding violates the rules of URL syntax:
> The character "#" is unsafe and should always be encoded because it is used in World Wide Web and in other systems to delimit a URL from a fragment/anchor identifier that might follow it.

Taken verbatim from [RFC1738](https://www.ietf.org/rfc/rfc1738.txt)

Please be kind and close your own thread.
