### ISSUE TITLE
Discussion: Links and Labels for the View generated in Controller

### ISSUE THREAD

**Issue by acheshko** [opencart/opencart#3752]
I decided to open this issue here, since didn't know the best place to start such discussion. I just wanted to understand why URL and labels (text) strings are generated in the controller and passed to the template view?

Currently, if I want to modify the link on my page, I am forced to modify the controller. This sorta defeats the purpose of MVC design pattern, where controller should be responsible for the business logic and not the static data in the view.

What if we pass some context object to the template from the controller. In this context, we could pass stuff like url generator and language object. By doing so, when we need to modify the view (i.e. link or add extra text), we won't have to change the controller.

**Comment by danielkerr** [comment]
"Currently, if I want to modify the link on my page, I am forced to modify the controller. This sorta defeats the purpose of MVC design pattern, where controller should be responsible for the business logic and not the static data in the view."

im open to just dumping all the language data into the view. would save a lot of lines of code.

"What if we pass some context object to the template from the controller. In this context, we could pass stuff like url generator and language object. By doing so, when we need to modify the view (i.e. link or add extra text), we won't have to change the controller."

objects should not go into the view as it makes a real mess of the code and also i plan to add the ability to use other template languages. this will not work if objects are in the view. 

also the desktop MVC and web MVC are different.
