### ISSUE TITLE
opencart v2.1.0.1 SMTP sender issue

### ISSUE THREAD

**Issue by sheikhmunawar** [opencart/opencart#3756]
Hi,

I have configured SMTP and receiving the following error.

Notice: Error: DATA not accepted from server! in /var/www/mydomain.com/system/library/mail.php on line 418

I've confirmed that if i put the "E-mail Address" on the "Contac Us" form same as I have used while setting the smtp user then the email goes without error.

**Comment by haxcop** [comment]
I've seen that issue and it happens with smtp providers that needs a verifiable sender - particularly with Aws SES. 
Try with mandrill it works greater and have a couple of advantages 


Yours faithfully 
Carlos Lozada

**Comment by sheikhmunawar** [comment]
Thanx @halfhope, but SES is client's choice so we don't have other option. There is a free extension though recommended for earlier release, but I am reluctant to try that.

Regards,
Munawar

**Comment by brandfoundry** [comment]
dont use the extension it breaks the smtp mail function.

i am also receiving the same error.
Notice: Error: DATA not accepted from server! in /var/www/domain.com/system/library/mail.php on line 418

**Comment by haxcop** [comment]
Exactly - the only way that may should work for the customer is to modify the code and add the field from your_vrified_email and remove the field from the customers eye and request the customer details on the comments field. otherwise it has to be a custom code to change the whole mail contact us form

**Comment by danielkerr** [comment]
its not an opencart issue if sender requires to be verified.

**Comment by haxcop** [comment]
Hello Daniel, Merry Christmass. 

With all the respect that you deserve. I think it’s an Opencart Issue because the smtp sender works fine when the System send a notification for new = order/customer/ also  the Marketing tool to send emails. if you have setup the verified sender in the SYSTEM>SETTINGS>EDIT>GENERAL>E-MAIL
But it does not work for the Contact_page and the reason is because it sends the email on name of the ‘sender’ and not of the system settings… 
In this case the sender on the contact page should be assigned as ‘requester’  or whatever you wanna called.

This also avoid send emails from unauthorised senders as you may know a lot about this. 

I will request again please have a better look to this ‘Issue’, because this will be a requirement in a near future for the major companies of Email senders. . . 

and more for the Opencart Users that cannot use AWS SES that offer More benefits 50k free emails to send a month against 12k that offer other provider like Mandrill for free. 
If you can also check the email providers regarding who finish as spam between them AWS SES have the better reputation against any other. 

Once again, Thanks for your time and consideration. 
\\
Carlos

**Comment by haxcop** [comment]
@danielkerr

**Comment by EdersonTS** [comment]
@danielkerr I have the same issue with my servers, 
I agree with @haxcop that Opencart should have a better look to this _issue_.

I just changed the headers `From` and `Return-Path` from `$this->from` to `$this->user_name` (because _from_ must be the same as _smtp_username_)

**Comment by lucarobo** [comment]
hi guys.
The problem is not solved.
If I changed the headers From and Return-Path from $this->from to $this->user_name
anyway don't works.

how can you solve?

Thanks

**Comment by lucarobo** [comment]
ok guys, I've solved adding ssl://smtps.xxx .it in SMTP Hostname.

**Comment by nkeYy** [comment]
I change mail.php in $header

$this->from to $this->smtp_username

It's works on Zohomail.

**Comment by zidnuss** [comment]
Thanks @nkeYy sat with this problem for two days. And changing $this->from to $this->smtp_username works in 2.2

**Comment by gowthamdandu** [comment]
Can you guys please let me know which line and how many places we need to change in mail.php

**Comment by edtsz** [comment]
@gowthamdandu probably at `107`:
Original code is:  `$header .= 'From: =?UTF-8?B?' . base64_encode($this->sender) . '?=' . ' <' . $this->from . '>' . $this->newline;`

**Comment by gowthamdandu** [comment]
Still, I am getting the same error 
**Notice: Error: MAIL FROM not accepted from server! in /var/www/html/order-online/system/library/mail.php on line 328**
My OC-Version - **2.1.0.1**

**My Mail Settings are** 
Mail Protocol : SMTP
Mail Parameters : -fadmin@restroappz.xyz
SMTP Hostname : ssl://smtp.yandex.com
SMTP Username : admin@restroappz.xyz
SMTP Password : ******
SMTP Port : 465
SMTP Timeout : 5

**Comment by edtsz** [comment]
@gowthamdandu hmmm.. I also changed the `Return-Path` to `$this->smtp_username`
look at below:
![captura de tela de 2016-08-09 11-28-44](https://cloud.githubusercontent.com/assets/3809579/17520029/9347a952-5e24-11e6-9c15-34a51a0f939b.png)

**Comment by nkeYy** [comment]
@gowthamdandu this is the complete code.
$header .= 'From: =?UTF-8?B?' . base64_encode($this->sender) . '?=' . ' <' . $this->smtp_username . '>' . $this->newline;

                if (!$this->reply_to) {
                        $header .= 'Reply-To: =?UTF-8?B?' . base64_encode($this->sender) . '?=' . ' <' . $this->smtp_username . '>' . $this->newline;
                } else {
                        $header .= 'Reply-To: =?UTF-8?B?' . base64_encode($this->reply_to) . '?=' . ' <' . $this->reply_to . '>' . $this->newline;
                }

**Comment by danielkerr** [comment]
No need to mess with the mail class you can set the send from the code in the contact us page

**Comment by gowthamdandu** [comment]
After changing the above lines in mail.php still i get the same error 

Someone please help me ... !

**Comment by gowthamdandu** [comment]
@danielkerr  not only contact us I have the same issue in all places **Order, Register, Forget Password, and contact ... etc**

**Comment by gowthamdandu** [comment]
I tried Zoho, Bitrix24, and Amazon SES nothing worked for me.

**Comment by gowthamdandu** [comment]
@nkeYy I configured back my Zohomail as it worked for you and made the change but still it's the same error with a change in line number 

**Notice: Error: DATA not accepted from server! in /var/www/html/order-online/system/library/mail.php on line 418**

**My Mail Settings are** 
Mail Protocol : SMTP
Mail Parameters : -fadmin@restroappz.xyz
SMTP Hostname : ssl://smtp.zoho.com
SMTP Username : admin@restroappz.xyz
SMTP Password : ******
SMTP Port : 465
SMTP Timeout : 5

**Comment by andrei-bogdan** [comment]
Hi, the issue might be related to the SMTP server itself.

Please try to connect and use those SMTP details with a 3rd party email sending library, such as:

https://github.com/PHPMailer/PHPMailer

**Comment by danielkerr** [comment]
On the contact page you need to change the sender as the stores email and not the person sending the contact request.

**Comment by danielkerr** [comment]
I will do a commit tommorrow

**Comment by gowthamdandu** [comment]
@andrei-bogdan i have normal emailer and its working fine 

http://restroappz.xyz/mail/examples/gmail.php

**Comment by danielkerr** [comment]
@gowthamdandu so must be fixed for every one then!!

**Comment by danielkerr** [comment]
some host dont allow you to send emails if the sender email is not set to the stores.

**Comment by gowthamdandu** [comment]
@danielkerr  I have just replaced my contact.php with this commitId - 1ab4332 and I had the below error

Notice: Error: Could not load template /var/www/html/order-online/catalog/view/theme/information/contact! in /var/www/html/order-online/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php on line 86

Does any upgrade required from 2.1.0.1 to 2.3.0.2 before using this commit

**Comment by gowthamdandu** [comment]
I have the below Amazon SES teste with **PHPMailer** and working fine but with OpenCart Still had an issue 

**Notice: Error: EHLO not accepted from server! in /var/www/html/order-online/system/library/mail.php on line 199**

Mail Protocol : SMTP
Mail Parameters : 
SMTP Hostname : email-smtp.eu-west-1.amazonaws.com
SMTP Username : ******
SMTP Password : ******
SMTP Port : 465
SMTP Timeout : 5

I tried all what we have above and can some one suggest me any solution please

**Comment by tonytcb** [comment]
@gowthamdandu You solve it with the ZohoMail and OpenCart ?

**Comment by Wingie** [comment]
yup having the same issue myself.

**Comment by bgdz** [comment]
I had this problem when tryint to send out receipts in Opencart 2.1.0.2 
In /system/library/mail.php around line 31, I changed: 
`public function setFrom($from) {
       //line was: $this->from = $from;
        $smtp_username = $this->smtp_username;
	$this->from =  $smtp_username;
    }`
I'm no expert programmer, but it worked for me.

**Comment by fennellgb23** [comment]
To fix this issue I just added tls:// to the front of the SMTP server information and used port 587, hope this helps people.

**Comment by arnisjuraga** [comment]
Isn't  the time to change to phpmailer?

https://github.com/opencart/opencart/pull/5072
https://github.com/opencart/opencart/pull/1329

**Comment by lapint** [comment]
By changing SMTP Timeout to 60 seconds, I was able to resolve this issue. Obviously that's too long, but your server's negotiation with Gmail is taking longer than expected.

When you encounter that issue, it is because the server hasn't received a reply before the timeout period.

**Comment by khalj** [comment]
I have OC2.0.1.1 and my hosting company and I have been trying to configure SMTP on my site, but I keep getting the same error: EHLO not accepted from server! 

My hosting company say it is a development issue with the OC code, so is there now a solution to this? And how can I implement the fix on my OC site?

Thank you

**Comment by lapint** [comment]
Increase the SMTP Timeout setting in Settings->Mail to something higher. I use 60 seconds now.

If you're on shared hosting, they likely run a series of spam filtering checks and what not that slow the sending of emails down.

**Comment by khalj** [comment]
I have, I set it to 240. The emails using PHP Mail take around 2 hours to be received, but on SMTP settings they are not sent/received at all, I just get the errors above, when sending out any sort of email, update an order status , contact form etc.

**Comment by lapint** [comment]
What are the settings you have on that page?

Do you have mail parameters set and are you using localhost as the hostname?

**Comment by khalj** [comment]
The settings I had for SMTP as given by my hosting company:

Mail Protocol: SMTP
Mail Parameters: -f admin@mywebstore.com
SMTP Hostname: ssl://10.168.1.70
SMTP Username: admin@mywebstore.com
SMTP Password: xxxxxx
SMTP Port: 465
SMTP Timeout: 240

**Comment by lapint** [comment]
You could try removing the space between "-f" and admin@mywebstore.com

Possibly could change SMTP Hostname to localhost but other than that I'd just be guessing.

SMTP Port 25 is also a typical choice so you could try that.

I have SSL configured for my site but I just use "localhost" as the hostname.

**Comment by khalj** [comment]
Thanks for the suggestions. I have tried all combinations of those settings and still not working. Using localhost as the Hostmane I get the error: Error: Connection refused (111)

 I have also tried many of the fixes to the mail.php file given on here, and have spent hours searching the OC forum for a solution but nothing works :( My hosting company thinks it's a a development issue with the code of OC, so more people must be having this issue?

**Comment by arnisjuraga** [comment]
One more thing - check the "from:" and "to:" field values. 
are they just an e-mail address, or they contains something more, like:

`'Some Name<example2@example.com>'` ? 

On some servers/configuration this can raise an issue. For the compatibility - from and to fields should contain ONLY an email address. I can't find it my history, where and when I have dealt it with. 

Just check and test it, does it helps?

**Comment by khalj** [comment]
Where can I check the "from" and "to" fields? I have looked at my emails received from my website email inbox and the "from" field does contain the `name` value.

Do you know how to resolve this? 

Thank you for your help

**Comment by arnisjuraga** [comment]
Needs more research in your case, contact me if I can help.

**Comment by khalj** [comment]
I would appreaciate any help I can get! I have sent you an email, thank you

**Comment by lapint** [comment]
Are you able to view any error logs on the server. With Shared hosting you likely won't be able to. But that could give more explanation into what's going wrong.

As arnisjuraga mentioned, you can edit system/library/mail.php to make the message content different, specifically the to, from, and sender information to only supply the email address.

**Comment by danielkerr** [comment]
you can view errors with shared hosting as well!

**Comment by khalj** [comment]
> Are you able to view any error logs on the server.

I can ask my hosting company for the error logs on the server, but I don't know what to look for.

`As arnisjuraga mentioned, you can edit system/library/mail.php to make the message content different, specifically the to, from, and sender information to only supply the email address.`

Here are the header lines of my mail.php at the  moment. How do I change it to supply only the email address:

`if ($this->protocol != 'mail') {
			$header .= 'To: ' . $to . $this->newline;
			$header .= 'Subject: ' . '=?UTF-8?B?' . base64_encode($this->subject) . '?=' . $this->newline;
		}

		$header .= 'Date: ' . date('D, d M Y H:i:s O') . $this->newline;
		$header .= 'From: =?UTF-8?B?' . base64_encode($this->sender) . '?=' . ' <' . $this->from . '>' . $this->newline;
		$header .= 'Reply-To: =?UTF-8?B?' . base64_encode($this->replyto) . '?=' . ' <' . $this->from . '>' . $this->newline;
		$header .= 'Return-Path: ' . $this->from . $this->newline;
		$header .= 'X-Mailer: PHP/' . phpversion() . $this->newline;
		$header .= 'Content-Type: multipart/related; boundary="' . $boundary . '"' . $this->newline . $this->newline;`

Thank you guys so much, for your help. I seem to be going around in circles with my hosting company, they just keep giving me the same settings to try, which we already know are not working.

**Comment by arnisjuraga** [comment]
Try to change 
~~~php
$header .= 'From: =?UTF-8?B?' . base64_encode($this->sender) . '?=' . ' <' . $this->from . '>' . $this->newline;
~~~

to

~~~php
$header .= 'From: ' . $this->from . $this->newline;
~~~

**Comment by khalj** [comment]
I think the extension  installed already changes this line: http://redmarlin.net/blog/post/opencart-fixing-notice-error-rcpt-not-accepted-server-tutorial

@arnisjuraga  I have sent you an email

**Comment by arnisjuraga** [comment]
Fixes:

1. `$this->crlf` must be replaced with `$this->newline`. there was one line in a file.
2. Double check server port/IP address. If the site catches a timeout (more than ~5 seconds), then, most probably, you are not connected to SMTP server, so - double check settings.

Both those fixes seem to help!

**Comment by khalj** [comment]
@arnisjuraga thank you so much for finding these issues on my site and fixing them. My SMTP mail is working now! I really appreciate your time and help :)

**Comment by arnisjuraga** [comment]
I hope, that can help someone else, who faces the same issue and searches it in github e.g.
Have a nice day!

**Comment by namangarg88** [comment]
Hi,

I have been recently migrated to zoho email server. Whenever We try to change the order status of the we receive the following error. We have cross check with the hosting team for any network issue but they run simple test script for email and showed that emails network is working fine. 

This is issue is temporary. That means in some hours of the day email sending is successful but for some part it stops. Following are the set of errors received every time we change the order status. 

2017-07-29 22:07:31 - PHP Warning:  fsockopen(): SSL: crypto enabling timeout in /var/www/giftjaipur/system/storage/modification/system/library/mail.php on line 186
2017-07-29 22:07:31 - PHP Warning:  fsockopen(): Failed to enable crypto in /var/www/giftjaipur/system/storage/modification/system/library/mail.php on line 186
2017-07-29 22:07:31 - PHP Warning:  fsockopen(): unable to connect to ssl://smtp.zoho.com:465 (Unknown error) in /var/www/giftjaipur/system/storage/modification/system/library/mail.php on line 186
2017-07-29 22:07:31 - PHP Notice:  Error:  (0) in /var/www/giftjaipur/system/storage/modification/system/library/mail.php on line 189


It will be great help if anyone can share some solution. 


Thanks,
Naman

**Comment by zemguru** [comment]
If it's sometimes works, sometimes - not - sounds as a server or mail system problem.
These errors indicate, that you are using SSL connection, and your shop web server must validate SSL certificate, received from Mail server.

**Comment by NimKulia** [comment]
in this file catalog/controller/information/contact.php
Find:
$mail->setFrom($this->request->post['email']);

Replace with:
$mail->setFrom($this->config->get('config_email'));
$mail->setReplyTo($this->request->post['email']);

**Comment by myothein** [comment]
<?php
class Mail {
	protected $to;
	protected $from;
	protected $sender;
	protected $replyto;
	protected $subject;
	protected $text;
	protected $html;
	protected $attachments = array();
	public $protocol = 'mail';
	public $smtp_hostname;
	public $smtp_username;
	public $smtp_password;
	public $smtp_port = 25;
	public $smtp_timeout = 5;
	public $newline = "\n";
	public $verp = false;
	public $parameter = '';

	public function __construct($config = array()) {
		foreach ($config as $key => $value) {
			if ($value) {
				$this->$key = $value;
			}
		}
	}

	public function setTo($to) {
		$this->to = html_entity_decode($to, ENT_QUOTES, 'UTF-8');
	}

	public function setFrom($from) {
		$this->smtp_username = html_entity_decode($from, ENT_QUOTES, 'UTF-8');
	}

	public function setSender($sender) {
		$this->sender = html_entity_decode($sender, ENT_QUOTES, 'UTF-8');
	}

	public function setReplyTo($reply_to) {
		$this->replyto = html_entity_decode($reply_to, ENT_QUOTES, 'UTF-8');
	}

	public function setSubject($subject) {
		$this->subject = html_entity_decode($subject, ENT_QUOTES, 'UTF-8');
	}

	public function setText($text) {
		$this->text = html_entity_decode($text, ENT_QUOTES, 'UTF-8');
	}

	public function setHtml($html) {
		$this->html = html_entity_decode($html, ENT_QUOTES, 'UTF-8');
	}

	public function addAttachment($filename) {
		$this->attachments[] = $filename;
	}

	public function send() {
		if (!$this->to) {
			trigger_error('Error: E-Mail to required!');
			exit();
		}

		if (!$this->smtp_username) {
			trigger_error('Error: E-Mail from required!');
			exit();
		}

		if (!$this->sender) {
			trigger_error('Error: E-Mail sender required!');
			exit();
		}

		if (!$this->subject) {
			trigger_error('Error: E-Mail subject required!');
			exit();
		}

		if ((!$this->text) && (!$this->html)) {
			trigger_error('Error: E-Mail message required!');
			exit();
		}

		if (!$this->replyto) {
			$this->setReplyTo($this->sender);
		}

		if (is_array($this->to)) {
			$to = implode(',', $this->to);
		} else {
			$to = $this->to;
		}

		$boundary = '----=_NextPart_' . md5(time());

		$header = 'MIME-Version: 1.0' . $this->newline;


		if ($this->protocol != 'mail') {
			$header .= 'To: ' . $to . $this->newline;
			$header .= 'Subject: ' . '=?UTF-8?B?' . base64_encode($this->subject) . '?=' . $this->newline;
		}

		$header .= 'Date: ' . date('D, d M Y H:i:s O') . $this->newline;
		$header .= 'From: =?UTF-8?B?' . base64_encode($this->sender) . '?=' . ' <' . $this->smtp_username . '>' . $this->newline;
		//$header .= 'Reply-To: =?UTF-8?B?' . base64_encode($this->replyto) . '?=' . ' <' . $this->smtp_username . '>' . $this->newline;
		if (!$this->replyto) {
            $header .= 'Reply-To: =?UTF-8?B?' . base64_encode($this->sender) . '?=' . ' <' . $this->smtp_username . '>' . $this->newline;
        } else {
                    $header .= 'Reply-To: =?UTF-8?B?' . base64_encode($this->replyto) . '?=' . ' <' . $this->replyto . '>' . $this->newline;
        }
		$header .= 'Return-Path: ' . $this->smtp_username . $this->newline;
		$header .= 'X-Mailer: PHP/' . phpversion() . $this->newline;
		$header .= 'Content-Type: multipart/related; boundary="' . $boundary . '"' . $this->newline . $this->newline;

		if (!$this->html) {
			$message  = '--' . $boundary . $this->newline;
			$message .= 'Content-Type: text/plain; charset="utf-8"' . $this->newline;
			$message .= 'Content-Transfer-Encoding: 8bit' . $this->newline . $this->newline;
			$message .= $this->text . $this->newline;
		} else {
			$message  = '--' . $boundary . $this->newline;
			$message .= 'Content-Type: multipart/alternative; boundary="' . $boundary . '_alt"' . $this->newline . $this->newline;
			$message .= '--' . $boundary . '_alt' . $this->newline;
			$message .= 'Content-Type: text/plain; charset="utf-8"' . $this->newline;
			$message .= 'Content-Transfer-Encoding: 8bit' . $this->newline . $this->newline;

			if ($this->text) {
				$message .= $this->text . $this->newline;
			} else {
				$message .= 'This is a HTML email and your email client software does not support HTML email!' . $this->newline;
			}

			$message .= '--' . $boundary . '_alt' . $this->newline;
			$message .= 'Content-Type: text/html; charset="utf-8"' . $this->newline;
			$message .= 'Content-Transfer-Encoding: 8bit' . $this->newline . $this->newline;
			$message .= $this->html . $this->newline;
			$message .= '--' . $boundary . '_alt--' . $this->newline;
		}

		foreach ($this->attachments as $attachment) {
			if (file_exists($attachment)) {
				$handle = fopen($attachment, 'r');

				$content = fread($handle, filesize($attachment));

				fclose($handle);

				$message .= '--' . $boundary . $this->newline;
				$message .= 'Content-Type: application/octet-stream; name="' . basename($attachment) . '"' . $this->newline;
				$message .= 'Content-Transfer-Encoding: base64' . $this->newline;
				$message .= 'Content-Disposition: attachment; filename="' . basename($attachment) . '"' . $this->newline;
				$message .= 'Content-ID: <' . basename(urlencode($attachment)) . '>' . $this->newline;
				$message .= 'X-Attachment-Id: ' . basename(urlencode($attachment)) . $this->newline . $this->newline;
				$message .= chunk_split(base64_encode($content));
			}
		}

		$message .= '--' . $boundary . '--' . $this->newline;

		if ($this->protocol == 'mail') {
			ini_set('sendmail_from', $this->smtp_username);

			if ($this->parameter) {
				mail($to, '=?UTF-8?B?' . base64_encode($this->subject) . '?=', $message, $header, $this->parameter);
			} else {
				mail($to, '=?UTF-8?B?' . base64_encode($this->subject) . '?=', $message, $header);
			}
		} elseif ($this->protocol == 'smtp') {
			$is_tls = substr($this->smtp_hostname, 0, 3) == 'tls';
			$hostname = $is_tls ? substr($this->smtp_hostname, 6) : $this->smtp_hostname;
			$handle = fsockopen($hostname, $this->smtp_port, $errno, $errstr, $this->smtp_timeout);

			if (!$handle) {
				trigger_error('Error: ' . $errstr . ' (' . $errno . ')');
				exit();
			} else {
				if (substr(PHP_OS, 0, 3) != 'WIN') {
					socket_set_timeout($handle, $this->smtp_timeout, 0);
				}

				while ($line = fgets($handle, 515)) {
					if (substr($line, 3, 1) == ' ') {
						break;
					}
				}

				fputs($handle, 'EHLO ' . getenv('SERVER_NAME') . "\r\n");

				$reply = '';

				while ($line = fgets($handle, 515)) {
					$reply .= $line;

					if (substr($line, 3, 1) == ' ') {
						break;
					}
				}

				if (substr($reply, 0, 3) != 250) {
					trigger_error('Error: EHLO not accepted from server!');
					exit();
				}

				if ($is_tls) {
					fputs($handle, 'STARTTLS' . "\r\n");

					$reply = '';

					while ($line = fgets($handle, 515)) {
						$reply .= $line;

						if (substr($line, 3, 1) == ' ') {
							break;
						}
					}

					if (substr($reply, 0, 3) != 220) {
						trigger_error('Error: STARTTLS not accepted from server!');
						exit();
					}

					stream_socket_enable_crypto($handle, true, STREAM_CRYPTO_METHOD_TLS_CLIENT);
				}

				if (!empty($this->smtp_username)  && !empty($this->smtp_password)) {
					fputs($handle, 'EHLO ' . getenv('SERVER_NAME') . "\r\n");

					$reply = '';

					while ($line = fgets($handle, 515)) {
						$reply .= $line;

						if (substr($line, 3, 1) == ' ') {
							break;
						}
					}

					if (substr($reply, 0, 3) != 250) {
						trigger_error('Error: EHLO not accepted from server!');
						exit();
					}

					fputs($handle, 'AUTH LOGIN' . "\r\n");

					$reply = '';

					while ($line = fgets($handle, 515)) {
						$reply .= $line;

						if (substr($line, 3, 1) == ' ') {
							break;
						}
					}

					if (substr($reply, 0, 3) != 334) {
						trigger_error('Error: AUTH LOGIN not accepted from server!');
						exit();
					}

					fputs($handle, base64_encode($this->smtp_username) . "\r\n");

					$reply = '';

					while ($line = fgets($handle, 515)) {
						$reply .= $line;

						if (substr($line, 3, 1) == ' ') {
							break;
						}
					}

					if (substr($reply, 0, 3) != 334) {
						trigger_error('Error: Username not accepted from server!');
						exit();
					}

					fputs($handle, base64_encode($this->smtp_password) . "\r\n");

					$reply = '';

					while ($line = fgets($handle, 515)) {
						$reply .= $line;

						if (substr($line, 3, 1) == ' ') {
							break;
						}
					}

					if (substr($reply, 0, 3) != 235) {
						trigger_error('Error: Password not accepted from server!');
						exit();
					}
				} else {
					fputs($handle, 'HELO ' . getenv('SERVER_NAME') . "\r\n");

					$reply = '';

					while ($line = fgets($handle, 515)) {
						$reply .= $line;

						if (substr($line, 3, 1) == ' ') {
							break;
						}
					}

					if (substr($reply, 0, 3) != 250) {
						trigger_error('Error: HELO not accepted from server!');
						exit();
					}
				}

				if ($this->verp) {
					fputs($handle, 'MAIL FROM: <' . $this->smtp_username . '>XVERP' . "\r\n");
				} else {
					fputs($handle, 'MAIL FROM: <' . $this->smtp_username . '>' . "\r\n");
				}

				$reply = '';

				while ($line = fgets($handle, 515)) {
					$reply .= $line;

					if (substr($line, 3, 1) == ' ') {
						break;
					}
				}

				if (substr($reply, 0, 3) != 250) {
					trigger_error('Error: MAIL FROM not accepted from server!');
					exit();
				}

				if (!is_array($this->to)) {
					fputs($handle, 'RCPT TO: <' . $this->to . '>' . "\r\n");

					$reply = '';

					while ($line = fgets($handle, 515)) {
						$reply .= $line;

						if (substr($line, 3, 1) == ' ') {
							break;
						}
					}

					if ((substr($reply, 0, 3) != 250) && (substr($reply, 0, 3) != 251)) {
						trigger_error('Error: RCPT TO not accepted from server!');
						exit();
					}
				} else {
					foreach ($this->to as $recipient) {
						fputs($handle, 'RCPT TO: <' . $recipient . '>' . "\r\n");

						$reply = '';

						while ($line = fgets($handle, 515)) {
							$reply .= $line;

							if (substr($line, 3, 1) == ' ') {
								break;
							}
						}

						if ((substr($reply, 0, 3) != 250) && (substr($reply, 0, 3) != 251)) {
							trigger_error('Error: RCPT TO not accepted from server!');
							exit();
						}
					}
				}

				fputs($handle, 'DATA' . "\r\n");

				$reply = '';

				while ($line = fgets($handle, 515)) {
					$reply .= $line;

					if (substr($line, 3, 1) == ' ') {
						break;
					}
				}

				if (substr($reply, 0, 3) != 354) {
					trigger_error('Error: DATA not accepted from server!');
					exit();
				}

				// According to rfc 821 we should not send more than 1000 including the CRLF
				$message = str_replace("\r\n", "\n", $header . $message);
				$message = str_replace("\r", "\n", $message);

				$lines = explode("\n", $message);

				foreach ($lines as $line) {
					$results = str_split($line, 998);

					foreach ($results as $result) {
						if (substr(PHP_OS, 0, 3) != 'WIN') {
							fputs($handle, $result . "\r\n");
						} else {
							fputs($handle, str_replace("\n", "\r\n", $result) . "\r\n");
						}
					}
				}

				fputs($handle, '.' . "\r\n");

				$reply = '';

				while ($line = fgets($handle, 515)) {
					$reply .= $line;

					if (substr($line, 3, 1) == ' ') {
						break;
					}
				}

				if (substr($reply, 0, 3) != 250) {
					trigger_error('Error: DATA not accepted from server!');
					exit();
				}

				fputs($handle, 'QUIT' . "\r\n");

				$reply = '';

				while ($line = fgets($handle, 515)) {
					$reply .= $line;

					if (substr($line, 3, 1) == ' ') {
						break;
					}
				}

				if (substr($reply, 0, 3) != 221) {
					trigger_error('Error: QUIT not accepted from server!');
					exit();
				}

				fclose($handle);
			}
		}
	}
}

**Comment by sdancer75** [comment]
I really did not understand the root of the problem and the solution. In my OpenCart installation version 3.0.3.6  I get the same error. What should I fix?

Fatal error: Uncaught Exception: Error: MAIL FROM not accepted from server! in /var/www/vhosts/oxxxxs.gr/httpdocs/system/library/mail/smtp.php:242 Stack trace: #0 /var/www/vhosts/oxxxxs.gr/httpdocs/system/library/mail.php(142): Mail\Smtp->send() #1 /var/www/vhosts/oxxxxs.gr/httpdocs/catalog/controller/information/contact.php(25): Mail->send() #2 /var/www/vhosts/oxxxxs.gr/httpdocs/system/engine/action.php(79): ControllerInformationContact->index() #3 /var/www/vhosts/oxxxxs.gr/httpdocs/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #4 /var/www/vhosts/oxxxxs.gr/httpdocs/system/engine/action.php(79): ControllerStartupRouter->index() #5 /var/www/vhosts/oxxxxs.gr/httpdocs/system/engine/router.php(67): Action->execute(Object(Registry)) #6 /var/www/vhosts/oxxxxs.gr/httpdocs/system/engine/router.php(56): Router->execute(Object(Action)) #7 /var/www/vhosts/oxxxxs.gr/httpdocs/system/framework.php(165): Router->dispatch(Object(Action), Object(Action)) #8 /var/www/vhosts/oxxxxs.gr/httpd in /var/www/vhosts/osubkids.gr/httpdocs/system/library/mail/smtp.php on line 242


My mail settings are :

Protocol: SMTP
Server : tls://smtp.titan.email
Username : info@oxxxxs.gr
Password : *************
SMTP port : 465
SMTP timeout : 60

**Comment by sdancer75** [comment]
> I really did not understand the root of the problem and the solution. In my OpenCart installation version 3.0.3.6 I get the same error in the contact form. What should I fix?
> 
> Fatal error: Uncaught Exception: Error: MAIL FROM not accepted from server! in /var/www/vhosts/oxxxxs.gr/httpdocs/system/library/mail/smtp.php:242 Stack trace: #0 /var/www/vhosts/oxxxxs.gr/httpdocs/system/library/mail.php(142): Mail\Smtp->send() #1 /var/www/vhosts/oxxxxs.gr/httpdocs/catalog/controller/information/contact.php(25): Mail->send() #2 /var/www/vhosts/oxxxxs.gr/httpdocs/system/engine/action.php(79): ControllerInformationContact->index() #3 /var/www/vhosts/oxxxxs.gr/httpdocs/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #4 /var/www/vhosts/oxxxxs.gr/httpdocs/system/engine/action.php(79): ControllerStartupRouter->index() #5 /var/www/vhosts/oxxxxs.gr/httpdocs/system/engine/router.php(67): Action->execute(Object(Registry)) #6 /var/www/vhosts/oxxxxs.gr/httpdocs/system/engine/router.php(56): Router->execute(Object(Action)) #7 /var/www/vhosts/oxxxxs.gr/httpdocs/system/framework.php(165): Router->dispatch(Object(Action), Object(Action)) #8 /var/www/vhosts/oxxxxs.gr/httpd in /var/www/vhosts/osubkids.gr/httpdocs/system/library/mail/smtp.php on line 242
> 
> My mail settings are :
> 
> Protocol: SMTP
> Server : tls://smtp.titan.email
> Username : [info@oxxxxs.gr](mailto:info@oxxxxs.gr)
> Password : *************
> SMTP port : 465
> SMTP timeout : 60

Ok Solved.

1. In the store settings, I had to change the email to something that had the website domain. Ie. if your domain is www.xyz.com your email in this field should be info@xyz.com and not info@yahoo.gr (you have to create it 1st ofcourse)
2. Under mail settings the ssl:// in the server field is obligated. ie
Protocol: SMTP
Server : ssl://smtp.titan.email
Username : info@oxxxxs.gr
Password : *************
SMTP port : 465
SMTP timeout : 60

**Comment by distvan** [comment]
> Isn't the time to change to phpmailer?
> 
> #5072
> #1329

Yes, you are right.
I can't understand while to reinvert the wheel when perfectly fine third-party solutions are available and work great....

**Comment by garbinmarcelo** [comment]
> Ok Solved.
> 
> 1. In the store settings, I had to change the email to something that had the website domain. Ie. if your domain is [www.xyz.com](http://www.xyz.com) your email in this field should be [info@xyz.com](mailto:info@xyz.com) and not [info@yahoo.gr](mailto:info@yahoo.gr) (you have to create it 1st ofcourse)
> 2. Under mail settings the ssl:// in the server field is obligated. ie
>    Protocol: SMTP
>    Server : ssl://smtp.titan.email
>    Username : [info@oxxxxs.gr](mailto:info@oxxxxs.gr)
>    Password : *************
>    SMTP port : 465
>    SMTP timeout : 60

I tried to use the same settings for AWS SES(of course changing the settings according to the service), but without success. In the panel the alert is that "Email was sent successfully", but in the mail.log is returned "Error: The SMTP server refused the sender's email!"

The main email is configured with the domain that has been validated on AWS, it is also possible to send email normally via the AWS panel as a test.

I've seen several topics, including one that an extension should be installed, I don't know which one because it doesn't show the same on the Marketplace on the panel. Others said that it is AWS 'problem that the OC is all right, but several reports seem to show the opposite.

P.s. With the configuration of email on a shared server it works well, but it involves the issue of SPAM, that's why I want to use AWS SES.

**Comment by pacersoft** [comment]
I solved the issue by setting SMTP login and Store E-Mail in settings to the same e-mail address. Before I did this, Server replied "relay-prohibited".
