### ISSUE TITLE
opencart v2 Fatal error: Call to undefined method Closure::bindTo() on PHP 5.3.29

### ISSUE THREAD

**Issue by ericcire** [opencart/opencart#3761]
Running opencart v2 master branch,  Fatal error: Call to undefined method Closure::bindTo() in system/engine/proxy.php on line 10

from this docs, http://docs.opencart.com/requirements/
PHP 5.3+(1.5.x at least 5.2+) should be ok for running it, but Closure::bindTo() exists start from php 5.4

**Comment by AlexanderKovalchuk** [comment]
Perhaps this is due to the fact that the master branch is used as a dev. :)
The master branch always faulty. You need to use latest release.

**Comment by danielkerr** [comment]
yes. we do plan to split the dev an master after the next release.

**Comment by danielkerr** [comment]
just remvoed the bindto. please test it again and open a new issue if not fixed.
