### ISSUE TITLE
Issues with Product Quantities

### ISSUE THREAD

**Issue by cf1224** [opencart/opencart#3768]
Hi,

(I am using Opencart 2)

I have noticed some issues regarding product quantities. For example:

Sometimes when I sell an item, the quantity isn't subtracted. Even though Product: Subtract quantity is set to yes (for all products), and the Settings: Subtract stock when status is Processing. However, sometimes the stock quantity is subtracted, and sometimes it isn't.

Also, sometimes the products quantities just randomly change. For example, a product may have quantity 5, then the next time I login it has changed to 6, or a product may have quantity 3, then the next time I login it has changed to 2, or a product may have quantity 0, then the next time I login it has changed to 2, and so on.

I am the only one who has the login password, and it is a 15+ character password with uppercase, lowercase, numbers, and special characters. So, I am the only person who can login.

Therefore, there is a definite bug with the Opencart automatic quantity updates.

Regards

**Comment by danielkerr** [comment]
good for you, but no one else is reporting it. use the forums!

Im pretty sure this is down to you.
