### ISSUE TITLE
Bug in Model/Total/Reward->confirm

### ISSUE THREAD

**Issue by mexykanu** [opencart/opencart#3774]
Hello,

Although this works, I consider this to be a bug instead of an improvement. This should not exist.

Location: Catalog - Model - Total - Reward -> *confirm*
The following code exists in the *confirm* function
```
$start = strpos($order_total['title'], '(') + 1;
$end = strrpos($order_total['title'], ')');

if ($start && $end) {  
	$points = substr($order_total['title'], $start, $end - $start);
}	
```
A new column should be created in **" . DB_PREFIX . "customer_reward**, named *points_int* or something like that. Reward points data should be saved and also read from this column. This is not too difficult, i've made this fix in about 5 minutes. I should mention that it took me more than 5 minutes to find out what was wrong.

**A function should not be dependent on language files, which are supposed to be modified ! This i found out the hard way and no one else should !**

**Comment by danielkerr** [comment]
the issue is your language files not having the () in them.

 it would require a text field would be required since its not just points in totals there are also coupon codes and currencies. 

the current solution is fine. its worth changing.

**Comment by mexykanu** [comment]
If you mean that it's not worth changing, then I'm disappointed. So many great things have been beautifully implemented in OpenCart and code like this is just not up to par.
