### ISSUE TITLE
Double subtotal & total at Invoice and Order Opencart-Urgent

### ISSUE THREAD

**Issue by ssskumar** [opencart/opencart#3775]
Hi,
My customer complain.. we receive invoice and order email with double subtotal & total.. why?
Please resolve and guide me for solution.
This is very urgent....

I guess that When i'm deleting order from admin section then oc_order deleting but previous order not deleting.. and also not deleting from oc_order_total table. may be this is main problem? When i'm creating new order then oc_order->order_id (36) but in oc_order_total -> order_id (64). Order_id is going different.

Thanks,
![order](https://cloud.githubusercontent.com/assets/6593851/12104533/78e10e9e-b372-11e5-937d-c613905ffec7.png)

**Comment by danielkerr** [comment]
use the forums or contact my staff.
