### ISSUE TITLE
Unable to sign in to admin

### ISSUE THREAD

**Issue by BlackSkorpio** [opencart/opencart#3776]
Scenario:
Fresh download v2.1.0.1
All requirements for installing OC is fulfilled
Latest FF & Chrome running on Win7
Cleared the cache
Restarted both browsers

No mather what I do I dont get to login to the ACP
I have reset the PW several times via the "forgot password mail"
I have used oc2_pwreset.php
Checked that the PW is recognized by using a fake PW: OC tells me the PW doesn't match the user

There is no clue what so ever to why OC let me in, I have gone through the forums and it looks as I'm not the only one experiencing this issue.

**Comment by droninn** [comment]
Same here. Tried 2.1.0.1 and 2.1.0.1 and still nothing.

**Comment by droninn** [comment]
The issue might be I'm using Mariadb instead of Mysql. The database install reports success but the database appears to be empty post install.

**Comment by danielkerr** [comment]
pm me via the forums your login info.

**Comment by droninn** [comment]
I figured out what was going on. I had limited the DB account used for the installation to max 300 update per hour. This caused the DB setup to fail silently except in the server logs.
```
Wed Jan 06 22:36:54.030706 2016] [:error] [pid 6982] [client ] PHP Notice:  Error: User 'user' has exceeded the 'max_updates_per_hour' resource (current value: 300)<br />Error No: 1226<br />DELETE FROM `oc_user` WHERE user_id = '1' in /var/www/html/store/system/library/db/mysqli.php on line 41, referer: http://mystore/store/install/index.php?route=step_3
```

**Comment by droninn** [comment]
Works now :)

**Comment by BlackSkorpio** [comment]
No change on my part :(

**Comment by danielkerr** [comment]
ok will look at it tomorrow

**Comment by BlackSkorpio** [comment]
I updated to the latest pre-release: and sorry to say, it still acts the same

**Comment by danielkerr** [comment]
im closing this but will look into why you can not login to your admin.
