### ISSUE TITLE
Session class in OC

### ISSUE THREAD

**Issue by johnqiuwan** [opencart/opencart#3777]
I found the following code in system/library/session.php, as follow:

ini_set('session.use_only_cookies', 'Off');
ini_set('session.use_cookies', 'On');
ini_set('session.use_trans_sid', 'Off');
ini_set('session.cookie_httponly', 'On');

However, I am kind of confuse because the "session.use_only_cookies" is set to 'Off' but the 'session.use_trans_sid' is also set to 'Off'.

Then, I have looked at the PHP manual, and also found:

session.use_only_cookies boolean

session.use_only_cookies specifies whether the module will only use cookies to store the session id on the client side. Enabling this setting prevents attacks involved passing session ids in URLs. This setting was added in PHP 4.3.0. Defaults to 1 (enabled) since PHP 5.3.0.

I think set both the 'session.use_only_cookies'  and the 'session.use_trans_sid' to 'Off' is kind of conflict. 

Should the 'session.use_only_cookies' be set to 'On' ?

**Comment by danielkerr** [comment]
no becaus cookie ID's for the API are stored in the db.
