### ISSUE TITLE
To create google base table

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#3786]
To file admin/controller/feed/google_base.php in line 20:

$data['heading_title'] = $this->language->get('heading_title');

change to:

$this->install();
$data['heading_title'] = $this->language->get('heading_title');

**Comment by danielkerr** [comment]
its already done here:

	public function install() {
		$this->load->model('feed/google_base');

		$this->model_feed_google_base->install();
	}

i think the table was not there because you had done an upgrade maybe.

**Comment by pekka2** [comment]
Hi Daniel

public function install() {
    $this->load->model('feed/google_base');
  /* Do something */
}
This method ControllerModuleGoogleBase->install need call somewhere .... :)
