### ISSUE TITLE
Price makes updated when admin edits order

### ISSUE THREAD

**Issue by guiltar** [opencart/opencart#3792]
When admin edits any order a new price shows up.

It's wrong behaviour. Some shops change prices very often.

For example, admin cannot just change the Last name or Adress without editing price.
There should be a button "Reset price to current price".
And even better to have ability of manual changing Price.

**Comment by danielkerr** [comment]
then do what 100% of other businesses do which is void the order and create a new one!

**Comment by guiltar** [comment]
New order will also be with new price.
Don't understand why too argue with obvious bugs and mistakes.

**Comment by danielkerr** [comment]
do you want a ban!!!

this is only how think something should work!

I suggest you hire a developer and pay them to add this in.

**Comment by guiltar** [comment]
Don't suggest me anything. Better keep watching your poor code. Ban me, there is no hope for this poorly coded full of bugs and empty out-of-box engine which you don't want to improve

**Comment by OpenCartAddons** [comment]
@guiltar You shouldn't be using the order editing system to update the order status.  Updating the order status is done by adding an order history under view order. 


Joel.

**Comment by guiltar** [comment]
@OpenCartAddons, thanks, I will check. But, anyway, if you want to change ONLY last name or email or address in order, the price gets updated. You cannot change even one letter in last name without changing price.

BTW, personally I easily fixed it for my site. It's not a problem for me since I'm a developer.

I reported here to contribute, to help improve engine. But with such reaction on obvious bugs there are no chance..

**Comment by moodleboy** [comment]
@guiltar 
Can you share what you did to fix this bug? Thanks.

**Comment by guiltar** [comment]
Hi, @moodleboy 
Sorry for long delay. First time I've done quick fix, but later decided the problem by complete move back-office to ERP and sync ERP<->Opencart. So all back-office including order edition goes in ERP then results sync to Opencart.

About quick fix. Couldn't found the exact code, it's removed due to above reason, sorry for that. But I'll explain why that happens and how to fix. When you go to 2nd step of order edit OC creates "cart" for you from order-products. Same way as you would be a customer. The problem is that "cart" always operates with actual prices. Then OC updates order from this cart.

Actually solution depends on when you want to change price and when don't want. The simplest would be to change when some stuff in the cart has changed.

**Updating of the cart by new products is here**
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/api/order.php#L567

You need to add a method `isCartModified()` which compares product_id/quantity/options from object $this->cart with product_id/quantity/options of existing data from `oc_order_product/oc_order_option`. You may compare them by hash-function: 
`product_1_id:quantity_1{option_11_id:option_11_value_id,option_12_id:option_12_value_id}+product_2..`
or more simple but not so universal
`product_1_id:quantity_1+product_2_id:quantity_2+...`

For example you will have such string values `'132:2+434:1+345:4'` (keep them ordered by id) for your cart and for existing data.

So if the cart is modified everything should go as before, if not you have to replace `$this->cart->getProducts()` in foreach by result of sql query with existing data from `oc_order_product/oc_order_option`.

Doing only this you will have correct saving but in order edit page you will see wrong data (as before). You may just ignore them going through the step and check actual data in order-history. If you want to fix this too, you need to fix products in 2nd and 5th steps of order-page.

**Products for view got quered by AJAX from here**
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/api/cart.php#L148

You have to check if the cart is modified as before. If yes everything goes as before. If not again replace `$this->cart->getProducts()` by result of sql query with existing data from `oc_order_product/oc_order_option` in similar way.

**Comment by guiltar** [comment]
@danielkerr, lots of people in many topics confirm it's a bug. It's a shame and looks very stupid to ignore evident bug.
https://github.com/opencart/opencart/issues/3298
https://github.com/opencart/opencart/issues/3797
https://github.com/opencart/opencart/issues/1373
https://github.com/opencart/opencart/issues/3298

**Comment by moodleboy** [comment]
@guiltar Thank you for your help.  I ended up taking a slightly different approach, in which I set a session variable in catalog/controller/api/order.php in the edit() function to hold the order_id.  Since this function can only be called by the admin when editing an order, the session variable will only be set during an order edit.

Then, in system/library/cart.php, I wrapped the product_special_query in an if() statement that basically checks to see if the session variable is set.  if it is, it graps the date_added date from the order and compares the special price to that instead of NOW(), thus preserving the special price of the order.  I have to do some more testing to make sure it works will all the order totals as well, but so far it looks like it does.

I am offering this ocmod to the general opencart community for free in my forum post here:

[http://forum.opencart.com/viewtopic.php?f=190&t=158405&p=604989#p604989](http://forum.opencart.com/viewtopic.php?f=190&t=158405&p=604989#p604989)

Or, if you want to get the code directly, grab it here:

[https://drive.google.com/file/d/0B-eMK_lc_jlyaGhyb3R5b01MeGc/view?usp=sharing](
https://drive.google.com/file/d/0B-eMK_lc_jlyaGhyb3R5b01MeGc/view?usp=sharing)

**Comment by guiltar** [comment]
@moodleboy Great solution, thanks! It will help many people! 

Actually you've solved slight another bug **"Respect outdated specials"**. Fortunately, `product_special` has `date_start` and `date_end` which you may compare with order's `date_added`.

But there is also another bug **"Respect outdated prices"**: respect old outdated prices if order is not changed. Standart (not special) price may change every day, for example oil prices, lol :) So you have to just freeze prices if the order-cart is not modified. For example, you want to edit First name and Address for a very-very old order. In such case you also have to freeze everything related to cart (old outdated prices, vouchers, discounts, etc).

**Comment by guiltar** [comment]
@danielkerr horrible job, the bug still exists in 2.3.0.2.
You don't have any aim to improve the product, lazyness and stupid excuses instead.

**Comment by schiggi** [comment]
Is there an updated version for OC 2.3?
