### ISSUE TITLE
Delete button on admin order page doesnt refresh the page. So the order is still there until i refresh it manually 

### ISSUE THREAD

**Issue by looney81** [opencart/opencart#3794]
When deleting an order, clicking the delete button temporarily shows the loading button, then shows success message, but order still shows in list. Admin must refresh page for the order to disappear.
Tested on Firefox & Chrome

**Comment by danielkerr** [comment]
already fixed

**Comment by looney81** [comment]
Ok, Thanks

**Comment by abiani** [comment]
I tried, not working well on 2.1.0.1 and on master 2.2.0.0_rc

**Comment by YU-WEI-LIN** [comment]
I have same problem,can you teach me again,thanks!!

**Comment by looney81** [comment]
Open admin/view/template/sale/order_list.tpl and after this:

if (json['success']) {
$('#content > .container-fluid').prepend('<div class="alert alert-success"><i class="fa fa-check-circle"></i> ' + json['success'] + ' <button type="button" class="close" data-dismiss="alert">&times;</button></div>');

add this one:


location.reload();

so the final will be like this:

if (json['success']) {
$('#content > .container-fluid').prepend('<div class="alert alert-success"><i class="fa fa-check-circle"></i> ' + json['success'] + ' <button type="button" class="close" data-dismiss="alert">&times;</button></div>');

location.reload();

**Comment by YU-WEI-LIN** [comment]
Thanks you,I understand,and thanks for your answer again.

Have a nice day!!



2016-08-29 14:41 GMT+08:00 looney81 <notifications@github.com>:
