### ISSUE TITLE
Images Bug! Please don´t close before answer...

### ISSUE THREAD

**Issue by greicebr** [opencart/opencart#3796]
Please help!!
I recently uploaded to the latest OC version. Issue is I cant seem to edit or add any images anywhere. When I select an image to change or when I try to add an image and click on the pencil (edit button). I see the circle goes around but nothing happens, no box pops up or anything for me to upload/change or select a new image. Can someone advise how to fix. Thanks

**Comment by danielkerr** [comment]
you have 4 options:

1. use the contact us on the opencart.com web site and my staff will help you monday.
2. post in the forums.
3. go to the partner page and contact some of the developers to fix your web site for a small fee. should be small as its only a bug fix.
4. find a developer online via services like odesk.
