### ISSUE TITLE
Allow db->query to return associative array when required

### ISSUE THREAD

**Issue by dtjones** [opencart/opencart#3804]
As you know the `$this->db->query` method  generates and returns  a `new \stdClass()` with the `rows` property populated with a sequential array of the query results. 
Something like this. 

				while ($row = $this->...fetch()) {
					$data[] = $row;
				}

But there are many instances in opencart where the returned results are immediately then looped to create an associative array.
 
        $query = $this->db->query($sql);
		foreach ($query->rows as $result) {
			$data[$result['column_name']  ] = array(
				// 
            );
		}

wouldn't it be more efficient in these instances to have a second parameter ($column_name) for the query method which when present returns an associative array using that column.

	public function query($sql, $column_name = false){

		if($column_name){
			while ($result = fetch_assoc()) {
				$data[$result[$column_name]] = $result;
			}
		} else {
			while ($result = fetch_assoc()) {
				$data[] = $result;
			}
		}

For the mysqli database adapter, `$result->fetch_all(MYSQLI_ASSOC);` could be used instead of the `while` loop and then use `array_column` to return an associative array.

        $data = $query->fetch_all(MYSQLI_ASSOC);
	if($column_name && $data){
		$data = array_column($data, null, $column_name);
	}

**Comment by pine3ree** [comment]
@dtjones 

Hello,
in my opinion the `query($sql)` method should not have parameters appliable to only one type of statement (SELECT statements in this case).`query(sql)` is used for INSERT, DELET, UPDATE and in those cases the 2nd parameter is not usable or ambiguous. 

You can add a layer of optimization by using php mysqli, pdo_mysql extensions compiled against mysqlnd instead of libmysqlclient. This will save the memory needed to import data from libmysqlclient to php.

kind regards

**Comment by dtjones** [comment]
@pine3ree I totally agree, I did not consider the other query types. Thanks
@danielkerr `$data = $query->fetch_all(MYSQLI_ASSOC);` might be faster than the while loop and its certainly neater.

**Comment by dtjones** [comment]
Alternatively another method could be used 

	public function select($sql, $column_key = null, $index_key = null) {

		$query = $this->link->query($sql);

		if (!$this->link->errno){

			if($query instanceof \mysqli_result) {

				$data = $query->fetch_all(MYSQLI_ASSOC);

				if($column_key || $index_key){
				    return $data ? array_column($data, $column_key, $index_key) : array();
				}
				return $data;
			
			} else {
				return array();
			}
		} else {
			trigger_error('Error: ' . $this->link->error  . '<br />Error No: ' . $this->link->errno . '<br />' . $sql);
		}
	}


getProductDescriptions using `$this-> db->select` Example (neater+faster)

	public function getProductDescriptions($product_id) {
		return  $this->db->select("SELECT * FROM " . DB_PREFIX . "product_description WHERE product_id = '" . (int)$product_id . "'", null, 'language_id');
	}

Current  getProductDescriptions method

	public function getProductDescriptions($product_id) {

		$product_description_data = array();

		return  $this->db->select("SELECT * FROM " . DB_PREFIX . "product_description WHERE product_id = '" . (int)$product_id . "'");

		foreach ($query->rows as $result) {
			$product_description_data[$result['language_id']] = array(
				'name'             => $result['name'],
				'description'      => $result['description'],
				'meta_title'       => $result['meta_title'],
				'meta_description' => $result['meta_description'],
				'meta_keyword'     => $result['meta_keyword'],
				'tag'              => $result['tag']
			);
		}

		return $product_description_data;
	}

**Comment by pine3ree** [comment]
Hello @dtjones,

over the year i build a separate DbSqlBuilder class and based on it a series of crud (select, insert, delete, update) methods with column/values normalization and some helper methods for the db class.

Maybe the opencart team will move to something like this in the future.

You can make suggestions here: http://opencart.uservoice.com/

best regards
