### ISSUE TITLE
Permission denied to view customers page

### ISSUE THREAD

**Issue by fiza1** [opencart/opencart#3812]
Hello,

I cannot access customers page (customers/customers page/custom fields) in opencart 2.1.0.1.

I don't have any problem before but after the installation of webkul extension, i cannot access customers page anymore. My site is going to launch soon, I don't know coding :(

I'm the only administrator and I already checked all permission access :(

**Comment by danielkerr** [comment]
admin > system > users > user group > edit

**Comment by fiza1** [comment]
done earlier before posting to github. all permission has been selected but no result
