### ISSUE TITLE
Access denied to view customer page

### ISSUE THREAD

**Issue by fiza1** [opencart/opencart#3815]
Refer to this issue #3812. I selected all permission but still cannot access customer page.

I look at user_groups/administration and phpmyadmin i only have this item:
"analytics\/customer\/custom_field","analytics\/customer\/customer","analytics\/customer\/customer_group"

However, "customer\/custom_field","customer\/customer","customer\/customer_group" does not exist.

Is this the reason why I cannot access customer page?

I tried to edit permission on phpmyadmin by adding extra list on user_group this item --> "customer\/custom_field","customer\/customer","customer\/customer_group".

But then an error occurred when I refresh opencart. I cannot access System page, permission denied!

So I delete back this fields "customer\/custom_field","customer\/customer","customer\/customer_group" I entered earlier.

Is there any possibilities of missing files?

I don't know coding hope you can provide me clear information.

![permissiondenied](https://cloud.githubusercontent.com/assets/16628154/12331688/924547c8-bb25-11e5-99a6-aaa832669712.PNG)

**Comment by danielkerr** [comment]
make sure your host compiles the server with json on.

**Comment by danielkerr** [comment]
i have already added a fix. you just need to replace the helper json with the one from the master branch.

**Comment by fiza1** [comment]
how to replace json? Should i refer to this url
https://github.com/opencart/opencart/blob/master/upload/system/helper/json.php

sorry i'm not a web developer i don't how to do it :(

On Fri, Jan 15, 2016 at 1:58 PM, Daniel Kerr <notifications@github.com>
wrote:

> i have already added a fix. you just need to replace the helper json with
> the one from the master branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencart/opencart/issues/3815#issuecomment-171879097>.
>



-- 
Thank you.
Regards
Faezah


-------------------------------------

Disclaimer:

Confidential Information contained in this message.  If you are not the
intended addressee indicated in this message, you may not copy or deliver
this message to anyone without the permission of the sender.  In such case,
you should destroy this message, and notify sender immediately.



Thank You
-------------------------------------

**Comment by fiza1** [comment]
how to replace helper json and master branch? how to find the files?

**Comment by danijelGombac** [comment]
The file is here upload/system/helper/json.php

**Comment by fiza1** [comment]
i only have this in my oc system/helper/json.php. i dont have upload folder.

I tried replace json.php with below script but still unable to access:

<?php
if (!function_exists('json_encode')) {
	function json_encode($data) {
		switch (gettype($data)) {
			case 'boolean':
				return $data ? 'true' : 'false';
			case 'integer':
			case 'double':
				return $data;
			case 'resource':
			case 'string':
				# Escape non-printable or Non-ASCII characters.
				# I also put the \\ character first, as suggested in comments on the 'addclashes' page.
				$json = '';
				$string = '"' . addcslashes($data, "\\\"\n\r\t/" . chr(8) . chr(12)) . '"';
				# Convert UTF-8 to Hexadecimal Codepoints.
				for ($i = 0; $i < strlen($string); $i++) {
					$char = $string[$i];
					$c1 = ord($char);
					# Single byte;
					if ($c1 < 128) {
						$json .= ($c1 > 31) ? $char : sprintf("\\u%04x", $c1);
						continue;
					}
					# Double byte
					$c2 = ord($string[++$i]);
					if (($c1 & 32) === 0) {
						$json .= sprintf("\\u%04x", ($c1 - 192) * 64 + $c2 - 128);
						continue;
					}
					# Triple
					$c3 = ord($string[++$i]);
					if (($c1 & 16) === 0) {
						$json .= sprintf("\\u%04x", (($c1 - 224) <<12) + (($c2 - 128) << 6) + ($c3 - 128));
						continue;
					}
					# Quadruple
					$c4 = ord($string[++$i]);
					if (($c1 & 8 ) === 0) {
						$u = (($c1 & 15) << 2) + (($c2 >> 4) & 3) - 1;
						$w1 = (54 << 10) + ($u << 6) + (($c2 & 15) << 2) + (($c3 >> 4) & 3);
						$w2 = (55 << 10) + (($c3 & 15) << 6) + ($c4 - 128);
						$json .= sprintf("\\u%04x\\u%04x", $w1, $w2);
					}
				}
				return $json;
			case 'array':
				if (empty($data) || array_keys($data) === range(0, sizeof($data) - 1)) {
					$output = array();
					foreach ($data as $value) {
						$output[] = json_encode($value);
					}
					return '[' . implode(',', $output) . ']';
				}
			case 'object':
				$output = array();
				foreach ($data as $key => $value) {
					$output[] = json_encode(strval($key)) . ':' . json_encode($value);
				}
				return '{' . implode(',', $output) . '}';
			default:
				return 'null';
		}
	}
}
if (!function_exists('json_decode')) {
	function json_decode($json, $assoc = false) {
		$match = '/".*?(?<!\\\\)"/';
		$string = preg_replace($match, '', $json);
		$string = preg_replace('/[,:{}\[\]0-9.\-+Eaeflnr-u \n\r\t]/', '', $string);
		if ($string != '') {
			return null;
		}
		$s2m = array();
		$m2s = array();
		preg_match_all($match, $json, $m);
		foreach ($m[0] as $s) {
			$hash = '"' . md5($s) . '"';
			$s2m[$s] = $hash;
			$m2s[$hash] = str_replace('$', '\$', $s);
		}
		$json = strtr($json, $s2m);
		$a = ($assoc) ? '' : '(object) ';
		$data = array(
			':' => '=>',
			'[' => 'array(',
			'{' => "{$a}array(",
			']' => ')',
			'}' => ')'
		);
		$json = strtr($json, $data);
		$json = preg_replace('~([\s\(,>])(-?)0~', '$1$2', $json);
		$json = strtr($json, array_map('stripcslashes', $m2s));
		$function = @create_function('', "return {$json};");
		$return = ($function) ? $function() : null;
		unset($s2m);
		unset($m2s);
		unset($function);
		return $return;
	}
}
