### ISSUE TITLE
images not loaded on the site and does not open the download window

### ISSUE THREAD

**Issue by Anastasy-ya** [opencart/opencart#3824]
Three warnings and images not loaded on the site. Previously it worked fine.
1)PHP Warning:  unlink(.../system/storage/cache/cache.product.1.0.1.a69d2050bdd72adc3a5dd6688f994865.1453122084): No such file or directory in .../system/library/cache/file.php on line 17
2)PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at .../index.php:98) in .../system/library/session.php on line 21
3)PHP Warning:  Cannot modify header information - headers already sent by (output started at ...index.php:98) in ...system/storage/modification/catalog/view/theme/sstore/template/common/header.tpl on line 449
Help me please.
V 2.1.0.1

**Comment by danielkerr** [comment]
great! but here is a not a support ticket system!

use the contact us for or the forums.
