### ISSUE TITLE
Url and multisore

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#3833]
Hi,Daniel

I search how the system set url for multi store, but i can't find where is set. In old way is set in index like

```
$url = new Url($config->get('config_url'), $config->get('config_secure') ? $config->get('config_ssl') : $config->get('config_url'));
$registry->set('url', $url);
```
now is 

```
$registry->set('url', new Url($config->get('site_base'), $config->get('site_ssl')));
```

Is somewhere else set store url?

**Comment by danielkerr** [comment]
i dont see the point of having 2 urls. one for ssl other for normal. opencart wont run properly if the ssl is on another domain name or sub domain. 

might as well have a setting to say has ssl or not.

**Comment by danijelGombac** [comment]
I don't mean ssl url, but normal store url. Now all the stores url are defined like default store. At least I can't find where is set new store url.

**Comment by danijelGombac** [comment]
If is available only default store settings <base href="" /> is empty because no config_ssl is set.

**Comment by danielkerr** [comment]
still working on this
