### ISSUE TITLE
"OpenCart users, switch to OpenCart-CE immediately"

### ISSUE THREAD

**Issue by SecurityProblemFinder17** [opencart/opencart#3834]
Somebody has send this mail to http://www.openwall.com/lists/oss-security/2016/01/19/16:

>This commit was made against the Community Edition of OpenCart on April 2,
2014.
>
>https://github.com/opencart-ce/opencart-ce/commit/5bc5f7a816aab17f1718e0c09323c74cd7167f35#diff-d0709af23c0fbe35295ee9a1ceb9fd79
>
>As you can see from the commit message, it was intended to prevent file
inclusion attacks.
>
>It's January 19, 2016 and OpenCart proper is still doing it wrong.
>
>https://github.com/opencart/opencart/blob/0b8ff2ef74309dd2e1797af762364dab2eef761b/upload/system/engine/action.php#L7
>
>What this line tries to do is prevent directory traversal attacks by
stripping out ../, but unfortunately it's quite dumb.
>
>https://3v4l.org/tMmNK
>
>This also doesn't defend against NUL byte injections.
>
>This is a 0day, because Daniel Kerr usually just flames security
researchers and I didn't feel like subjecting myself to that ever again. To
wit:
>
>* https://github.com/opencart/opencart/issues/1269
>* https://github.com/opencart/opencart/issues/1279
>* https://github.com/opencart/opencart/issues/1534
>* https://github.com/opencart/opencart/issues/1594
>* https://github.com/opencart/opencart/issues/3721
>
>I'm sure I missed quite a few instances of him flaming people trying to
help him secure his project for free. He doesn't seem to ever learn, either.
>
>The OpenCart-CE maintainer, in contrast, is more hospitable towards
security researchers. So in addition to already having a fix in place,
their rapport with the community means using the community edition is
likely to make your system more secure than running OpenCart proper.
>
>In closing, I recommend everyone who runs OpenCart to switch to OpenCart-CE
today and anyone who does penetration testing read this excellent article
by Keith Makan about Ordering an RFI via Email:
http://blog.k3170makan.com/2012/01/ordering-remote-file-inclusion-via-e.html

Does mean this that OpenCart insecure?

**Comment by danielkerr** [comment]
Idiot!

**Comment by soatok** [comment]
> Idiot!

Come on now, aren't you just proving the point that the author of the email was trying to make by getting angry and closing the issue?

Have you ever considered not being angry and hostile towards everyone? Just my $0.02

**Comment by danielkerr** [comment]
I closed the issue because hes promoting another project. All thats happening is my time being wasted. Im sure this guy has been banned in the past. I will look into this but the fix thats offered here is the same regex that i used a long time ago in my front controller.

Some of the above mentioned issues were not security issues but bugs or just opions.

**Comment by danielkerr** [comment]
congratulations you have now gotten opencart-ce project banned from being mentioned in the opencart forums!

so rph and addcreative should thank you! 

I told you that your account was banned get the message!
