### ISSUE TITLE
Very bizarre issue when editing orders

### ISSUE THREAD

**Issue by wscull** [opencart/opencart#3838]
Opencart version 2.1.0.1
Tested on live site and also two local WAMP setups.
Also tested latest Opencart version 2.1.0.2 on local WAMP setup.

This issue occurs when an admin user edits an order. Specifically on step 2. Products. When the admin goes to that page, all the products on that order are immediately put back in the customers cart. It does not matter if the customer cart was empty or had products in it. Either way it replaces all the cart contents with the products from the old order.
The admin does not need to save or modify the order in any way for this to happen. Just loading step 2 on the page /admin/index.php?route=sale/order/edit causes this to occur.

There are other issues with order editing, but this is worst by far.

**Comment by wscull** [comment]
Note that the WAMP installs are fresh copies of opencart. No changes were made.

**Comment by danijelGombac** [comment]
This is the way it works.

**Comment by wscull** [comment]
How is this useful for the customer or admin?

**Comment by wscull** [comment]
Would be nice to have some input before just closing the thread

**Comment by wscull** [comment]
Seriously how can you expect customer to shop at your store when the items in their logged in shopping cart suddenly disappears and gets replaced with their old order???

**Comment by danielkerr** [comment]
this is a not a support thread! its a bug tracker for development of opencart script.

use the forum or email my staff!

**Comment by DanielRuf** [comment]
@danielkerr Well, this is clearly a bug in your software.

**Comment by agatha65** [comment]
@danielkerr This is not a bug but the logic is wrong.
When you open the order to editing the cart is replaced by the old order. If the customer has in it something stored it is lost.
Maybe you have to check the cart and keep someway the records before to edit and then restore it.

**Comment by wscull** [comment]
@danielkerr I have posted this issue on the Opencart forum, and emailed your support staff. Outside of a response asking for login information for our site (which I supplied), I have not had any reply from your staff. I have seen no response on the forum either. 

Does this mean no one wants to discuss this?

**Comment by acheshko** [comment]
welcome to opencart community!
Daniel, just doesn't know how to build open source projects. He alienates pretty much anyone who would want to contribute to this project.
