### ISSUE TITLE
Ocmod error 500 in admin

### ISSUE THREAD

**Issue by pepsinclar** [opencart/opencart#3850]
OpenCart version 2.1.0.2

I can not access the back office because it gives me error 500.

I'll explain what I did:
1. I created a file .ocmod
2. I did upload from Installer in the backoffice
3. file .comod there was a syntax error
4. I deleted the record from the database "modification"
5. I can not remove the files from "System> Storage> modification> [FILES]

Now I'm stuck and I can not turn on the backoffice for error 500.
Have you any suggestions?

**Comment by pepsinclar** [comment]
OpenCart version 2.1.0.2

**Comment by danielkerr** [comment]
Login via ftp to delete thd fules. Also contact ur host. Maybe its not ocmod

**Comment by pepsinclar** [comment]
Ok thanks but the problem remains the number 5, that is, that I can not remove the files from the "modification" ftp.
I have a server cloud and I can not delete them.

Have you any suggestions?
