### ISSUE TITLE
Getting undefined error pop up on category editing/creating(bug report)

### ISSUE THREAD

**Issue by ocextension** [opencart/opencart#3854]
here is what i did:

1. installed the 2.2.0.0_a1 alpha
2. edit any form that having a summernote
3. the error pop up saying undefined

i believe it has something to do with the summernote since when i remove the summernote class from
category_description textarea, the error do not comes up. but then there are no special editing mode anymore.
![clipboard01](https://cloud.githubusercontent.com/assets/15631453/12532134/13f88e7e-c247-11e5-8f6b-723606945d27.jpg)

**Comment by BetaScripts** [comment]
Confirmed.

https://github.com/opencart/opencart/issues/3831
The guy said that v0.6.16 was the last compatible version.

OC was updated to v0.7.3
![summ](https://cloud.githubusercontent.com/assets/8970524/12535482/aa46e038-c28d-11e5-8031-059f60e09b5f.jpg)

**Comment by ocextension** [comment]
yeah, its seem like it occur to all form that having a summernote

**Comment by villagedefrance** [comment]
Yup, confirmed, I got this too.

**Comment by danielkerr** [comment]
dont worry will fix. left a bit of testing code in there

**Comment by ocextension** [comment]
https://github.com/opencart/opencart/pull/3856 <- cant we use this fix?

**Comment by danielkerr** [comment]
its not a ful fix i think
if you have multiple text editors
problem is i think there are some bus in summernote

**Comment by danielkerr** [comment]
and fixed! i hate spending a day trying to get something simple that should work.
