### ISSUE TITLE
OC 1.5.5 Admin controller/catalog/product -> autocomplete ignores filter_category_id

### ISSUE THREAD

**Issue by shadyyx** [opencart/opencart#386]
From unknown reason some parts of code are missing now in the method "autocomplete" of the class ControllerCatalogProduct within the admin part:

```
        if (isset($this->request->get['filter_category_id'])) {
            $filter_category_id = $this->request->get['filter_category_id'];
        } else {
            $filter_category_id = '';
        }

        if (isset($this->request->get['filter_sub_category'])) {
            $filter_sub_category = $this->request->get['filter_sub_category'];
        } else {
            $filter_sub_category = '';
        }
```

And this code:

```
        $data = array(
            'filter_name'  => $filter_name,
            'filter_model' => $filter_model,
            'start'        => 0,
            'limit'        => $limit
        );
```

Should be replaced with this one:

```
        $data = array(
            'filter_name'         => $filter_name,
            'filter_model'        => $filter_model,
            'filter_category_id'  => $filter_category_id,
            'filter_sub_category' => $filter_sub_category,
            'start'               => 0,
            'limit'               => $limit
        );
```

 The `$data` then is pushed to `$results = $this->model_catalog_product->getProducts($data);` while the model is handling `$data['filter_category_id']` correctly...

Check with the previous OC 1.5.4 version to see what I am talking about...

Or should the autocomplete() method be missing the mentioned parts for some reason?

**Comment by sud0074** [comment]
in also opencart-1.5.6.4 autocomplete is not working anymore. 
wat is wrong with it ... 
please tell .. how can i fix it .. even google cant give me ri8 path
