### ISSUE TITLE
[2.2.0.0_a1] $this->load->language() doesn't return data any more

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#3864]
$this->load->language() can no longer be used to get the language variables, which breaks compatibility with any extension that uses that. This is easily fixed by making this edit, which shouldn't affect any language functionality, I believe:

IN:
/system/engine/loader.php

REPLACE:
$this->registry->get('language')->load($route);
$this->registry->get('event')->trigger('language/' . $route . '/after', $route);

WITH:
$data = $this->registry->get('language')->load($route);
$this->registry->get('event')->trigger('language/' . $route . '/after', $route);
return $data;

**Comment by OpenCartAddons** [comment]
v1.5.5 all over again.

At least now they've added $this->language->all().

**Comment by danielkerr** [comment]
FIXED!

**Comment by danielkerr** [comment]
i was thinking it might be better to do:

$this->language->load('whatever', $data);

**Comment by OpenCartAddons** [comment]
@danielkerr Thanks
