### ISSUE TITLE
[2.2.0.0_a1] Consider falling back to the "english" language files if the "en-gb" files do not exist

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#3865]
While this won't be an issue once an extension is updated, my guess is that it's going to cause a LOT of confusion for store owners when they update and suddenly none of their extensions will load any language text. This can be fixed by first attempting to load any "english" language files, before the new "en-gb" files are loaded. It should maintain backwards compatibility while still preferring the new "en-gb" files:

IN:
/system/library/language.php

BEFORE:
$file = DIR_LANGUAGE . $this->default . '/' . $filename . '.php';

ADD:
$file = DIR_LANGUAGE . 'english/' . $filename . '.php';
if (file_exists($file)) {
	require($file);
}

**Comment by OpenCartAddons** [comment]
I agree.  This would be ideal so we don't have to include 2 identical language files to keep extensions backwards compatible.

**Comment by ocextension** [comment]
this is good, btw i would rather prefer the language directory name remain the same which is 'english'

**Comment by danielkerr** [comment]
yes will do

**Comment by danielkerr** [comment]
added

**Comment by OpenCartAddons** [comment]
@danielkerr Thanks
