### ISSUE TITLE
Recurring order problem

### ISSUE THREAD

**Issue by danielkerr** [opencart/opencart#3872]
1. customer account recurring order page showing errors.
2. admin recurring order needs redesign

**Comment by JigneshMistry** [comment]
Hello Danielkerr,
I have the issue on the opencart verison 2.1.0.2 i have created sample profile and added to one sample product while on the checkout page its giving me  Warning: No Payment options are available. Please contact us for assistance!
While i have three payment method enabled on the admin side. is there any bug or just causing some miss configuration.  
I have searched on the opencart fouram and on google as well. i cont find anything. can you able to help me out.
Regards,
Jignesh

**Comment by bzark** [comment]
The payment methods you have enabled need to support recurring payments.  Currently the only payment module installed with OpenCart that supports recurring payments is PayPal Express.
