### ISSUE TITLE
Image upload syntax error

### ISSUE THREAD

**Issue by zacchaeusluke** [opencart/opencart#3873]
Using version 2.1.0.2. I'm getting a syntax error as follows when uploading an image:
![image](https://cloud.githubusercontent.com/assets/7443010/12591527/13a2511a-c460-11e5-9254-12af2fccd340.png)

The error log shows: 2016-01-26 14:09:01 - PHP Warning:  move_uploaded_file(): UPLOADED FILE:'/tmp/phpM7aZTJ' to '/home/vol14_8/byethost7.com/b7_17232751/htdocs/image/catalog/logo2.png' in /home/vol14_8/byethost7.com/b7_17232751/htdocs/admin/controller/common/filemanager.php on line 275

The images are uploaded correctly when I refresh though.

**Comment by danielkerr** [comment]
i think contact your host. this is at the php level. so maybe hd is full or permissions on folders are not correct.
