### ISSUE TITLE
[2.1.0.1] Incorrect password reset link

### ISSUE THREAD

**Issue by lexand** [opencart/opencart#3874]
Got
```
http://some.domain.com/admin/index.php?route=common/reset&amp;code=7719a49859d4f75c76bd2fabbe3ae17e4847faf8
```
Should be
```
http://some.domain.com/admin/index.php?route=common/reset&code=7719a49859d4f75c76bd2fabbe3ae17e4847faf8
```

**Comment by ingilerdaite** [comment]
Steps to reproduce:

1. Go to url: http://[hostname]/admin

2. Click on forgotten password

3. Enter email and press reset button

4. Go to email and open received reset password link

5. Open received link

Actual:

Login page is opened

Expected:

Reset password page is opened

**Comment by ocextension** [comment]
same goes to oc2.1.0.2
edit admin/controller/common/forgotten.php

find :
$mail->setText($message);

replace with:
$mail->setText(html_entity_decode($message, ENT_QUOTES, 'UTF-8'));
