### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by lexand** [opencart/opencart#3876]
Sorry but dont know hot to contact with main contributors else.

1. Are there right tests for OpenCart v2.1+ ?
Because the tests in https://github.com/openbaypro/opencart-test-suite.git not correspond to version 2.1+.

2. You are not using type hinting, even @property declaration in class header. Why ? That much improve code understanding and navigation.

thank a lot

**Comment by jamesallsup** [comment]
No, the tests are not up to date and will be revisited soon to update them.

Please use the forum to ask questions or use the suggestion site to make improvement suggestions

https://github.com/opencart/opencart/blob/master/README.md
