### ISSUE TITLE
Fatal error when click on register, login and forgotten pssword

### ISSUE THREAD

**Issue by fiz1** [opencart/opencart#3880]
Hello,

Below error occurred when I click on 'Register', 'Login' and 'Forgotten Password'

Fatal error: Class 'Controllermodule' not found in /home/wiwitzco/public_html/ocart2/system/storage/modification/system/engine/loader.php on line 28

I check on loader.php line 28 but found nothing. Not sure how to fix them. Appreciate your advice.

**Comment by ocextension** [comment]
seems like it was because some mod you were using since its pointing it to /system/storage/modification/
