### ISSUE TITLE
country cache issue.

### ISSUE THREAD

**Issue by shadowtsai** [opencart/opencart#3881]
hi all,
When cache.country.status is already exit, cause cache.country judgement error.
[Fix]
 modify   /catalog/model/localisation/country.php  on ine 10,17
cache.country.status -> cache.country_status

thank a lot

**Comment by danielkerr** [comment]
there is no issue! dont post unless you know what you are doing.

**Comment by shadowtsai** [comment]
dear danielkerr,
                           when /system/storage/cache/cache.country.status is already exit, cache.country  does not exit. At background management  edit Customer address country not show all. /admin/model/localisation/country.php on line 65 cache get will 'country'. but get 'country.status'. 
thanks
