### ISSUE TITLE
Special price is not workng properly

### ISSUE THREAD

**Issue by svayamalhotra** [opencart/opencart#3882]
Hello Opencart,
In my website, there is some problem with every product's special price as it auto disappear many times from all the products and I have to clear cache from my browser to display that again. I'll bound my buyers.
Please reply !

**Comment by svayamalhotra** [comment]
@Danielkerr why are you closing my issue,
please to that !

**Comment by danielkerr** [comment]
because its an issue only you are having and this is not a support ticket system!

**Comment by svayamalhotra** [comment]
Hadd hai mtlb !
Seedha bol na ata nahi,
I'll do it >:(
