### ISSUE TITLE
Incorrect email validation in guest checkout

### ISSUE THREAD

**Issue by ingilerdaite** [opencart/opencart#3883]
Environment:
opencart version 2.1.0.2

Preconditions:
User is not signed-in in application

Steps to reproduce:

Add some items to your cart

Go to checkout 

Select Guest checkout

Enter Billing information with wrong email address (for example: aaa@.bbb):

![l_16ad tmp](https://cloud.githubusercontent.com/assets/16939221/12649455/48ec7ebc-c5e7-11e5-9295-fd75ea7a98c6.PNG)

Click continue

Actual:
User is navigated to another section

Expected:
User is alerted that email address is incorrect and stays in the same section

**Comment by ADDCreative** [comment]
The email validation has already been changed for the next version. https://github.com/opencart/opencart/commit/bc1bd168913e928e10993c1a6d47bb116f1bbcbc
