### ISSUE TITLE
[Minor] Misleading text when adding item to wishlist

### ISSUE THREAD

**Issue by ingilerdaite** [opencart/opencart#3884]
Environment:
opencart version 2.1.0.2

Preconditions:
User is not signed in to application

Steps to reproduce:

Go to any item
Add it to wish list

![l_7cf2 tmp](https://cloud.githubusercontent.com/assets/16939221/12649880/28ec5680-c5e9-11e5-8070-569929955a94.PNG)

Actual:
Item is added to wishlist, but text says, that in order to add this item to wishlist I need to login or register

Expected:
Item is added to wishlist and text should say, "item is added to your wish list and in order to see your list you should register or login"

**Comment by danielkerr** [comment]
not required
