### ISSUE TITLE
Checkout process. Step 5 broken continue button

### ISSUE THREAD

**Issue by ingilerdaite** [opencart/opencart#3885]
Environment:
opencart version 2.1.0.2; browser: Chrome 47.0.2526.106 m (64-bit)

Preconditions:
User is signed in to application

Steps to reproduce:

Go to any item
Click add to cart
Go to checkout
Click continue until you get to the step 5 (Payment Method)
Leave Terms and conditions checkbox empty and click continue

![l_27c8 tmp](https://cloud.githubusercontent.com/assets/16939221/12650402/5e0f29c6-c5eb-11e5-8022-ff5d68698d77.PNG)

Actual:
Warning is visible, continue button is changed to loading. I click the Terms and conditions checkbox - nothing happens.

Expected:
Warning is visible. Continue button is disabled. I click the Terms and conditions checkbox - continue button is enabled and I can continue with my order.

**Comment by danielkerr** [comment]
i can not replicate. do u have a llink to your site?

**Comment by danijelGombac** [comment]
I think it already corrected

```
} else if (json['error']) {
                $('#button-payment-method').button('reset');
```

**Comment by danijelGombac** [comment]
Yes, there is already reset, but twice. You need to remove one.
