### ISSUE TITLE
Incorrect stock out behavior with options

### ISSUE THREAD

**Issue by jaiume** [opencart/opencart#3890]
Opencart will allow an order of more than is available in stock of an item, even if 'stock checkout' is set to No under the following conditions 

1. The product has options that do not subtract stock (My situation is drop down options)
2. The main product is set to subtract stock
3. The customer chooses multiple options of the same product, where each option is less than available stock, but combine options are more than available stock

This results in a negative stock level, even though stock check out is set to no.

This is with version 2.1.0.1

Thanks
Jamie

**Comment by danielkerr** [comment]
simple solution. refund buyers order and tell him you were out of stock. 

also thje store owner is supposed to check the option stock levels match the products stock level!
