### ISSUE TITLE
admin/controller/catalog/category.php  issue

### ISSUE THREAD

**Issue by johnqiuwan** [opencart/opencart#3896]
I saw the following code in the file admin/controller/catalog/category.php around line 53:

if (($this->request->server['REQUEST_METHOD'] == 'POST') && $this->validateForm()) {
			$this->model_catalog_category->editCategory($this->request->get['category_id'], $this->request->post);

Should we change it 

from:
$this->request->get['category_id']

to:
$this->request->post['category_id']

**Comment by danielkerr** [comment]
No.
