### ISSUE TITLE
helper 'genera'l load

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#3897]
Eg. file catalog/controller/api/order.php is find function 'token' (this in line 229)

`'code'             => token(10),`

is missing function loader? Can you add To after  line 4:

`$this->load->helper('general');`

same issue is also in file admin/model/user/user.php

**Comment by danielkerr** [comment]
thats done in the startup.

// Helper
require_once(DIR_SYSTEM . 'helper/general.php');
