### ISSUE TITLE
Website problem Checkout 

### ISSUE THREAD

**Issue by sivi29y** [opencart/opencart#3901]
In the testing mode of a website when forgetting to select the terms and conditions rubric, the site seems to be crashing (version 2.X 1 )

![screen shot 2016-02-01 at 14 14 31](https://cloud.githubusercontent.com/assets/535881/12717095/2e1598da-c8ee-11e5-93ac-17aef0494825.png)

**Comment by danielkerr** [comment]
all ready fixed on the master branch.
