### ISSUE TITLE
API

### ISSUE THREAD

**Issue by trajedy** [opencart/opencart#3908]
Why does the opencart backend use the API methods? From what I can tell the API only acts on data stored in the session, so when editing an order in the backend, is that order loaded into the current session and then the API acts on it. After editing an order, if I then go to the frontend, that order is now in my cart....... If this is confusing, it's probably because the code organisation of Opencart is an absolute nightmare.

After using Opencart 1.* and then moving to 2.* I can see that things haven't improved at all, and will no longer use Opencart.

Good luck

**Comment by danielkerr** [comment]
only if your logged in.
