### ISSUE TITLE
Paypal standard doesn't show on Opencart 2.1.0.1

### ISSUE THREAD

**Issue by Faddel** [opencart/opencart#3909]
I have OpenCart 2.1.0.1, everything works fine, I have enabled Paypal standard but it doesn't show, i put a valid email used on another website, it is direct payment,

where I could start from to solve it?

**Comment by danielkerr** [comment]
reupload the files

**Comment by Faddel** [comment]
well it was my partner's mistake, he entered the code of the currency wrongly, I will add a request to put the name of currency from a combo box so there will be no chance for mistakes
