### ISSUE TITLE
version is not consistent in admin panel

### ISSUE THREAD

**Issue by sivi29y** [opencart/opencart#3912]
after overiding the files with 2.1.0.2 release.
I still see the older version in admin panel: 

> OpenCart © 2009-2016 All Rights Reserved.
> Version 2.1.0.1

**Comment by ocextension** [comment]
not really sure if you did replace the file or not but here it is

installation_directory/admin/index.php Line: 3

change to
define('VERSION', '2.1.0.2');

**Comment by sivi29y** [comment]
sorry the install was not in the root folder. So a reinstall in the right directory should resolve this issue.
