### ISSUE TITLE
same photo 

### ISSUE THREAD

**Issue by RamyaKrishna1** [opencart/opencart#3913]
when user is clicking any category for ex: rice, if his requirement is for 5kg rice if  he clicks rice category it is showing same 1 kg photo for both 1kg & 5kg.
[problem (1).PDF](https://github.com/opencart/opencart/files/118713/problem.1.PDF)

**Comment by RamyaKrishna1** [comment]
Hai i'm ramya my problem is when user is clicking any category for ex: rice, if his requirement is for 5kg rice.. if he clicks rice category it is showing same 1 kg photo for both 1kg & 5kg. so any one answer me please leave a comment .

Thank you,
Ramya krishna.

[problem (1).PDF](https://github.com/opencart/opencart/files/118719/problem.1.PDF)

**Comment by ocextension** [comment]
i guest you're saying that when the customer go buy same product but different option, the image on the cart looks the same where it take the original image of the product and not image from an option of the product. if that it then you need to contact the developer of your extension to include this feature
