### ISSUE TITLE
2.2 fiture request Extensions > Events page

### ISSUE THREAD

**Issue by qahar** [opencart/opencart#3915]
During my test, it's not possible to view Events action path, where it trigerred or enable/disable them.
The only way to see what Events action path and triggered is through database. And the only way to disable is by renaming the method.

My request is to add _status_ column at database Events table. And create new Events managing just like Modification or Themes page.

Another column like _group_ at Events table would be usefull to identify the author or what exetension the event belong, but it's optional.

**Comment by tiborbesze86** [comment]
I don't think it's necessary. Opencart doesn't use events for its core code base. It's an option for module developers to hook into specific methods, when something is about to happen, or has already happened. Events are usually registered in the install() method of a module and de-registered in the uninstall() method (but this is just the convention... you can register and de-register events anywhere in your code). Manually removing an event binding from the database will most likely break the module using it, so it's not recommended at all. If you are having problem with a third party module's events, then contact its developer, and in most of the cases they'll be happy to help you.

**Comment by qahar** [comment]
> It's an option for module developers to hook into specific methods

That is the reason why we need to see the list of database table "Event". My request is simply to make it easy for everyone to see what event is triggered for what action. So we can locate which file on what method the code run.

Events is not conflict free, no priority order and cannot enable/disable.
The most hard part is that Events not outputing final code; compared to Ocmod or vQmod. It's make Events harder to troubleshoot.

**Comment by tiborbesze86** [comment]
Your approach is wrong. Events are not meant to be tampered with, unless you are developing a module. In my opinion it should be hidden from your average admin user, or they might be able to break third party modules.

By the way, Opencart executes events in the order they've been added to the database. Also, if you are a developer, then you can just go and check the oc_event table to see what's going on. If you aren't, then you have nothing to do there, you'll most likely break stuff.

**Comment by qahar** [comment]
You overthinking my request.
Just like you said, I could simply ask client database access to troubleshoot
