### ISSUE TITLE
Validate order id upon product return

### ISSUE THREAD

**Issue by Tenida** [opencart/opencart#3916]
I found, any one can submit a product return request using the returns form where there is no validation of whether the order at all exists or not. There must be a validation of the supplied order id exists in database and is valid in respect to the status of the order, before the form gets submitted. There must be another validation of email id with the given order id. the email id given in the returns form must be same as email id used purchasing/placing that order. This should be a default property, if not, there should be an option in setting panel to enable/disable this.

**Comment by danielkerr** [comment]
does not matter!

I suggest if you have customers no putting in the correct information that you email them and ask them for the correct information.
