### ISSUE TITLE
Google Recaptcha Guest Checkout

### ISSUE THREAD

**Issue by ordonezgs** [opencart/opencart#3919]
when you try to checkout as guest with Google Recaptcha active doesn't appears and when you try to continue display an error with something like google Rechapta doesn't match but google isnt visible , the machine usderstand that google Re captcha is active and you have to put the code

**Comment by danielkerr** [comment]
version?

**Comment by santy2001** [comment]
The latest 2.1.0.2 (Open Cart)

**Comment by nuke123** [comment]
Update: /catalog/view/theme/default/template/captcha/google_captcha.tpl

```html
<div class="form-group required">
  <?php if (substr($route, 0, 9) == 'checkout/') { ?>
    <label class="control-label" for="input-captcha"><?php echo $entry_captcha; ?></label>
    <div id="input-captcha" class="g-recaptcha" data-sitekey="<?php echo $site_key; ?>"></div>
  <?php } else { ?>
    <div class="col-sm-offset-2 col-sm-10">
      <div id="input-payment-captcha" class="g-recaptcha" data-sitekey="<?php echo $site_key; ?>"></div>
      <?php if ($error_captcha) { ?>
      <div class="text-danger"><?php echo $error_captcha; ?></div>
      <?php } ?>
    </div>
  <?php } ?>
</div>

<script src="https://www.google.com/recaptcha/api.js"></script>
<script type="text/javascript">
if (typeof grecaptcha != "undefined") {
  $(document).ready(function() {
    $('.g-recaptcha').each(function(){
      $(this).html('');     
      var widgetId = grecaptcha.render($(this)[0], {sitekey : $(this).data('sitekey')});
    });
  });
}
</script>
```

**Comment by danielkerr** [comment]
because your country is blocking google services.

**Comment by pnair39** [comment]
2016-02-17 15:18:00 - PHP Notice:  Undefined index: g-recaptcha-response in /home/amillio8/public_html/catalog/controller/captcha/google_captcha.php on line 32


The latest 2.1.0.2 (Open Cart)

**Comment by bruiseviolet** [comment]
Thanks @nuke123  it worked.  @pnair39 make sure you are updating the right file- make sure if you are using a theme other than the default theme, that you are changing the file under that theme and not default.

**Comment by shyandsy** [comment]
@danielkerr  
I have same problem and I live in Canada

**Comment by shyandsy** [comment]
@howdu 
it works. Thanks you!

**Comment by lib088** [comment]
@howdu , thank you very much, your code is still working.

**Comment by daritehnologies** [comment]
it works for me! thank you

**Comment by serdaraltan** [comment]
@howdu thank you worked for me too
But if you dont check the "i am not robot" and press REGISTER button on checkout page, it doesnt warn you, just button turns LOADING and nothing...

**Comment by cheglok-ok** [comment]
@howdu Thanks you! It fixed my problem!

**Comment by danielkerr** [comment]
Google Recaptcha has been moved out of the opencart core. report any issues via the extension page  comments section there.  will add the page soon.

**Comment by calexil** [comment]
this is still broken in 2023, version 2.0.1.2, @howdu 's solution results in the following:

![Screenshot at 2023-03-24 18-05-26](https://user-images.githubusercontent.com/3487071/227652238-1b62a9d1-6446-409e-9a1f-a07c231afd82.png)

**Comment by danielkerr** [comment]
And u post this on a closed issue
