### ISSUE TITLE
Voucher send currency error without order

### ISSUE THREAD

**Issue by nuke123** [opencart/opencart#3921]
If voucher does not belong to an order throws error. 

Replace:
````
$data['text_greeting'] = sprintf($this->language->get('text_greeting'), $this->currency->format($voucher_info['amount'], $order_info['currency_code'], $order_info['currency_value']));
```

With:
````
$data['text_greeting'] = sprintf($this->language->get('text_greeting'), $this->currency->format($voucher_info['amount'], $this->config->get('config_currency')));
```

**Comment by p0v1n0m** [comment]
#4486
