### ISSUE TITLE
Image manager issue: Warning: File could not be uploaded for an unknown reason

### ISSUE THREAD

**Issue by highacid** [opencart/opencart#3923]
Unable to upload on fresh install, running on Cpanel, with php56. I have all these ini options loaded:

```
magic_quotes_gpc = Off;
register_globals = Off;
default_charset	= UTF-8;
memory_limit = 256M
max_execution_time = 30
upload_max_filesize = 8M
safe_mode = Off;
mysql.connect_timeout = 20;
session.auto_start = Off;
session.use_only_cookies = On;
session.use_cookies = On;
session.use_trans_sid = Off;
session.cookie_httponly = On;
session.gc_maxlifetime = 3600;
allow_url_fopen = On
display_errors = On
;error_reporting = E_ALL;allow_url_include = Off
asp_tags = Off
enable_dl = On
file_uploads = On
include_path = ".;/path/to/php/pear"
max_input_time = 60
max_input_vars = 1000
session.save_path = ""
```

**Comment by danielkerr** [comment]
file permissons?

**Comment by danielkerr** [comment]
i mean folder

**Comment by highacid** [comment]
It seems this was a issue with some php modules. Now it works as designed.

**Comment by luckybhumkar** [comment]
Right..! most time this error belongs to **php.ini** file. Sometime link to **image directory permission level**.
Here is the solution [Warning: File could not be uploaded for an unknown reason!](https://doubtsolver.com/ask/332/opencart-warning-file-could-not-uploaded-for-unknown-reason)
