### ISSUE TITLE
Mixed content error while editing orders

### ISSUE THREAD

**Issue by studiopersona** [opencart/opencart#3941]
Chrome Error:
Mixed Content: The page at 'https://www.sencorediamondtools.com/admin/index.php?route=sale/order/edit&token=cAtmeEOcdFX8QHlhmbMwn1lc68oEPOHo&order_id=1050' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.sencorediamondtools.com/index.php?route=api/currency&token='. This request has been blocked; the content must be served over HTTPS.

Use SSL is set to yes under Security in Server settings

**Comment by danielkerr** [comment]
alreadfy fixed. check the commits

**Comment by BlueKore** [comment]
This is not fixed. I have the same issue with 2.2
