### ISSUE TITLE
module template loading isue

### ISSUE THREAD

**Issue by PXLTCH** [opencart/opencart#3943]
i try to load module from version 2.1.0.1 on master but i have module template loading isue , templates loading core code system changed on new master version ?
`Notice: Error: Could not load template C:/xampp/htdocs/opencart/upload/admin/view/template/module/adv_ajaxfilter.tpl.tpl! in C:\xampp\htdocs\opencart\upload\system\library\template\basic.php on line 26`

**Comment by PXLTCH** [comment]
page show error message and also end of file format try to check 2 times .tpl  `adv_ajaxfilter.tpl.tpl! in `

**Comment by danielkerr** [comment]
try using the master

**Comment by PXLTCH** [comment]
i used master but oc 2.1.0.1 modules not working on master, some template loading isue, i tryed 3 modules .
