### ISSUE TITLE
opencart

### ISSUE THREAD

**Issue by saboorulhassan** [opencart/opencart#3944]
Fatal error: Call to undefined method Loader::library() in /home/-/public_html/catalog/controller/journal2/settings.php on line 20 ?

Plz help me

**Comment by prhost** [comment]
what's on line 20?

**Comment by nuke123** [comment]
It was removed in 2.1.0.1 for some reason. Broke a lot of extensions that used it. 

Easier to just modify core library file and add it back in.

```
<?xml version="1.0" encoding="utf-8"?>
<modification>
  <file path="system/engine/loader.php">
	<operation>
      <search index="0">
        <![CDATA[final class Loader {]]>
      </search>
      <ignoreif>
        <![CDATA[function library(]]>
      </ignoreif>
      <add position="after">
        <![CDATA[	public function library($library) {
		$file = DIR_SYSTEM . 'library/' . $library . '.php';

		if (file_exists($file)) {
			include_once($file);
		} else {
			trigger_error('Error: Could not load library ' . $file . '!');
			exit();
		}
	}]]>
      </add>
    </operation>
  </file>
</modification>
```

**Comment by prhost** [comment]
They made a autoload for libraries https://github.com/opencart/opencart/blob/2.1.0.1/upload/system/startup.php#L87 I think we now need only load the Class library for namespace.

**Comment by nuke123** [comment]
Your error is missing method. 

Github is different to download from opencart 2.1.0.1 site:
http://www.opencart.com/index.php?route=download/download/success&download_id=42

**Comment by prhost** [comment]
@nuke123 I do not get it, download the official website is different from Github? I downloaded and checked the 'upload/file system/startup.php` the autoload I mentioned.

**Comment by danielkerr** [comment]
its different there is a drop down on github for different versions.

**Comment by danielkerr** [comment]
im closing this as its related to an extension. the loader->library was removed because we had autoload so no need to add library->load.

**Comment by saboorulhassan** [comment]
but i use different  opencart vr.. not work  just lastest v. work opencart

**Comment by prhost** [comment]
@danielkerr Remove the method library not optimize load, since the load class is instantiated and the method is not used, there is no overload. And the autoload is the same as the method library was the only difference is that it uses namespace. Eventually causing many lost compatibility with the new version for nothing.
