### ISSUE TITLE
OC2.2 $this->load->view(<TEMPLATE>) without .tpl extension

### ISSUE THREAD

**Issue by torcu** [opencart/opencart#3951]
Hi

I noticed that from OC2.2 it is required to remove the extension .tpl from `$this->load->view()` this will force developers to update "all" modules that call a template.

Also this change is not backwards compatible with OC2.1 so either two separate module versions or a conditional variable with the ".tpl" extension will be needed from OC2.2

Is there a reason for this change?

Many thanks!

**Comment by danielkerr** [comment]
Its backwards compatible.

**Comment by danielkerr** [comment]
The change was for the events wystem which i will finish thd docs for today

**Comment by danielkerr** [comment]
also we plan to introduce a template language. its the only way for customer to be able to edit the template without being able to execute php code.

**Comment by torcu** [comment]
Hi Daniel

Thanks for your answer. Yes, I see, that for the templates:

`if (substr($view, -4) == '.tpl') {
			$view = substr($view, 0, -4);
		}`

But this is not implemented in the Loader Class that gets called from the admin modules and it is always adding the `.tpl` bit to the template. In /system/engine/loader.php

`$output = $template->render($route . '.tpl');`

Many thanks
Keep up the good work!

**Comment by danielkerr** [comment]
ok will do some more testing

**Comment by qahar** [comment]
It's valid that use $this->load->view('module/information.tpl', $data) from admin will produce an error.

I think it's necessary to make event/theme at admin for backward compability. Since there is no theme in admin, use the Events to remove .tpl if exist
