### ISSUE TITLE
missing openbay table: oc_product_option_variant

### ISSUE THREAD

**Issue by screamingjungle** [opencart/opencart#3952]
Missing Openbay table:
`CREATE TABLE IF NOT EXISTS " . DB_PREFIX . "product_option_variant"`

error log:
`PHP Notice:  Error: Table 'oc_product_option_variant' doesn't exist`

@jamesallsup

**Comment by jamesallsup** [comment]
You need the OpenStock module, this table is created on the install of it to handle product variants. Not required for standard OC/OBP install.

**Comment by screamingjungle** [comment]
Thanks James,

This was found in the v2.1.x betas (OpenBayPro_v2993_OC_2_1_BETA).

Checking the stable OpenBayProv2980OC21, it's not there.

@jamesallsup
