### ISSUE TITLE
Coupon is not calculated in checkout cart and not added to total amout

### ISSUE THREAD

**Issue by Daivule** [opencart/opencart#3959]
Hi,

I created a coupon for some products in our e-shop with unlimited use (but situation not chanes if I put any number in fields "Uses per Coupon" or "Uses per Customer":
http://www.screencast.com/t/JDHE4X9rnhMA

And tested how it works. As you can see from Checkout window, Coupon is recognized but not calculated:
http://www.screencast.com/t/OCPCHhPPaaR

Please, help to solve this issue. Thank you, Daiva

**Comment by danielkerr** [comment]
its working for everyonbe else. this is not a personal support issue tracker. i think you have messed the settings up as totals are messed up.

"Uses per Customer":

you need to set that the customer must be logged in to use.

might be a good idea i add a message to let the customer know this.

**Comment by Daivule** [comment]
Sorry for disturbing. I was redirected here by OC support I asked first. I absolutely agree that it would be reported earlier if it is a common bug.

**Comment by Daivule** [comment]
Sorry for disturbing. I was redirected here by OC support I asked first. I absolutely agree that it would be reported earlier if it is a common bug.  Why customer should be logged if I let him use unlimited amount of coupons?
