### ISSUE TITLE
Opencart-2.1.0.2 custom field sort order issue with registration page

### ISSUE THREAD

**Issue by anamikamca** [opencart/opencart#3965]
I have installed open cart version 2.1.0.2.

I have added one custom field named phone number from administrator section and assigned the sort-order 6 to this field.

When I check the registration page I am unable to see this field, but when I change the sort order to 5 or 7 then this field is visible . I am not sure why for sort order 6, this field does not show on registration page.

**Comment by anamikamca** [comment]
![screenshot-opencart local 2016-02-19 18-57-50 copy](https://cloud.githubusercontent.com/assets/12440597/13176786/bde84f3e-d73a-11e5-84b5-244aa0dbb6d9.png)
![screenshot-opencart local 2016-02-19 18-57-20 copy](https://cloud.githubusercontent.com/assets/12440597/13176785/bde66656-d73a-11e5-8a3e-959a190b17f4.png)

**Comment by danielkerr** [comment]
there is a help tooltip on the customer field page. please read it.
