### ISSUE TITLE
Has anyone Experienced disabled payment step button?

### ISSUE THREAD

**Issue by Boxedsolutions** [opencart/opencart#3967]
Steps to reproduce. 

Choose a payment method, uncheck terms and condition checkbox. Then click continue button. 

Then error message for You have to confirm Terms and conditions. But the button is still disabled.
<img width="1174" alt="skarmavbild 2016-02-19 kl 15 12 18" src="https://cloud.githubusercontent.com/assets/8977650/13177747/6fca4c2c-d71b-11e5-9665-f594a8c85c8d.png">

**Comment by pnair39** [comment]
What version of opencart are you running?

**Comment by pnair39** [comment]
Please see this fix: https://github.com/opencart/opencart/issues/3885

**Comment by Boxedsolutions** [comment]
I have 2.1.0.1 Which version is the solution released in? 

I work for Billmate in their Payment gateway development and came across this. So that we know what to tell our clients?

**Comment by UK-Tiger** [comment]
Will this fix be included in the next release ?
Thanks for the code snippet, but would it be possible to get more information as to where it should be applied... Thanks
