### ISSUE TITLE
Coupons Not working , Opencart 2.1.0.1

### ISSUE THREAD

**Issue by pranaymoluguri** [opencart/opencart#3971]
I have done a lot googling, but did not get any proper solution for that. ??? 
When we apply a valid coupon, it shows "Success: Your coupon discount has been applied!", but nothing changes in the subtotal or total.
Whereas the gift voucher works perfectly.

Kindly check the same and help me.

url : freshneeds.in

Can use details for login 
username : aa@bb.com 
password : 123456
I am in urgent need of it..

Thanks a lott in advance :)
pranaymoluguri

**Comment by danielkerr** [comment]
i hope thats not your admin login info!!!

**Comment by ssyberg** [comment]
I'm having this exact same issue on the same version, why was this closed without comment?

**Comment by pranaymoluguri** [comment]
The problem was solved. That's why

**Comment by ssyberg** [comment]
Generally if a problem is solved there's some explanation added to Github. Where/how was the problem solved? It still appears to exist in my code...

**Comment by ssyberg** [comment]
Looks like someone else found it to: https://forum.opencart.com/viewtopic.php?f=191&t=165198

**Comment by ssyberg** [comment]
I've confirmed this is a bug, manually setting setting.coupon_sort_order to 1 in the database seems to fix it.
