### ISSUE TITLE
Stock is not check when confirm order

### ISSUE THREAD

**Issue by cool20061988** [opencart/opencart#3973]
I'm using open cart version 2.1.0.2.

I'm trying to buy the same product using 2 browser.
The product stock is 10. Buyer A is trying to buy 10 and buyer B is 10.
Then I checked out both of them.
I finished the order of buyer A and then I tried to continue (click "continue" button) with buyer B but I was redirected to "view cart" (opencart is working properly).

Then I tried with the condition where both buyers only need to click "confirm order" button (I reset the stock).

I clicked the button for buyer A and the order succeed.
Then I clicked the button for buyer B and the order succedd too (opencart not check stock when confirm order). The stock is minus.

Can anyone tell me how to fix it?
I think I only need to copy the query when button "continue" clicked (check stock part) and copy it to "confirm order"  but I can't find the file.

Thank you.

**Comment by danielkerr** [comment]
would it be better that competitors add as many products as they can with max quantities and go to the payment page and never pay or return to the store.

**Comment by UK-Tiger** [comment]
Maybe work something like safety stock into the system, that should take care of the issue.
