### ISSUE TITLE
OC 2.1.0.2, 2.2.0.0_b1: Make Openbay more secure

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#3980]
In file **admin/model/openbay/openbay.php**, in method **call**, it always uses the HTTP only in this code:
```
		if (defined("HTTP_CATALOG")) {
			$domain = HTTP_CATALOG;
		} else {
			$domain = HTTP_SERVER;
		}
```

Could we change it to this please:

```
		if (defined("HTTP_CATALOG")) {
			$domain = ($this->request->server['HTTPS']) ? HTTPS_CATALOG : HTTP_CATALOG;
		} else {
			$domain = ($this->request->server['HTTPS']) ? HTTPS_SERVER : HTTP_SERVER;
		}
```

Remember, Google will soon favour HTTPS-only websites in its SEO ranking!

**Comment by jamesallsup** [comment]
This has got nothing to do with OpenBay Pro security! Curl is not using that variable to make a connection, look at the code it is just part of the request body.

**Comment by mhcwebdesign** [comment]
So why then does the **account.openbaypro.com** API then need the insecure domain in the CURLOPT_POSTFIELDS?

**Comment by jamesallsup** [comment]
For internal debugging, if a client is having problems connecting to the server, how the website serves its own pages is irrelevant.

Is there a reason why you want this information?

**Comment by mhcwebdesign** [comment]
I wasn't sure whether openbaypro would use the domain url for other purposes, such as callbacks to the Opencart server, or not.
