### ISSUE TITLE
OC 2.1.0.2, 2.2.0.0_b1: Wrong link canonical for home page

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#3982]
I think, by the looks of the code used, when using a second etc Opencart store as part of a multi-store scenario, it creates a wrong link canonical for the homepage.

This code in the **catalog/controller/common/home.php** 

```
		if (isset($this->request->get['route'])) {
			$this->document->addLink(HTTP_SERVER, 'canonical');
		}
```

should be replaced with something like this:

```
		if (isset($this->request->get['route'])) {
			$this->document->addLink($this->config->get('config_url'), 'canonical');
		}
```

**Comment by danielkerr** [comment]
pull requests please.

**Comment by mhcwebdesign** [comment]
OK, will do.

**Comment by waqasjawed** [comment]
Here is the pull request #4072
