### ISSUE TITLE
indirect modification of overloaded property ControllerApiCustomer::$session

### ISSUE THREAD

**Issue by Namanyahillary** [opencart/opencart#3983]
I receive warning **indirect modification of overloaded property ControllerApiCustomer::$session** when i try to update a placed order in Opencart 2.1.0.2

I upgraded from 1.5 to 2.1.0.2.

Any help regarding this matter will be appreciated. 

Thanks in-advance.

**Comment by jamesallsup** [comment]
Please use the forum. Read the readme for info.

https://github.com/opencart/opencart/blob/master/README.md

**Comment by Namanyahillary** [comment]
Greetings, i managed to figure it out after a long while.

The issue was caused by not creating an API record under **System** > **Users** > **API** 

and attaching it to the store under **System** > **[Edit Store]** > **Option** > **API User**

The API record did not exist in the DB since i had manually upgraded from 1.5.X to latest 2.1.X. A fresh install will automatically add the API while such an upgrade will not, thus causing session errors and unable to add your IP address correctly.

Thanks.
