### ISSUE TITLE
order email not receive by admin

### ISSUE THREAD

**Issue by melfort237** [opencart/opencart#4002]
i have subscription in three hosting services. one is cloud hosting and 2 ordinary hosting. i installed opencart version 2.0 and up in 2 ordinary hosting services, whenever an order placed only the client would received the confirmation but the admin did not. I tried using cloud hosting e.g. site5.com hosting service the client and the admin received both the email confirmation of the order. is the problem causes by the hosting services or the opencart script is compatible only to selected hosting server especially cloud? 

hope to hear some enlightenment from you guys... thanks!

**Comment by danielkerr** [comment]
contact the hosting company thats not working. they should check they have the php mail function configured properly.
