### ISSUE TITLE
Main Website - Many Cannot Download/Purchase Extensions or use Contact Form

### ISSUE THREAD

**Issue by uksitebuilder** [opencart/opencart#4003]
Sorry for posting this here, tryign to grab your attention quickly

A few people have raised this issue on the forums and I have posted in the Internal Discussion support forum and can also confirm this issue.

If you are aware of it already, cool.  If not, read on....

There is a problem with the Extensions store in that many people cannot access any previous or recent downloads

Upon clicking download for any extension that have been previously purchased, a Page Not Found is displayed and then you get kicked to the login screen.

Please advise soonest as this has been down for at least 10 hours now

I have also had customers contact me who cannot purchase because of this, so losing sales for everyone concerned.

**Comment by danielkerr** [comment]
its fixed now sorry!

james changed the session cookie to be ssl only by mistake. do when people were redirected back tot he extension they wanted to buy it logged them out.

lost  about 100 orders. should pick up again over the next few days. implementing some new features
