### ISSUE TITLE
Timing attack leading to XXE

### ISSUE THREAD

**Issue by abdogdn** [opencart/opencart#4009]
Hi,
There are areas where you're comparing "tokens" to user inputs using "==" which is not timing-safe and can lead to timing attacks and leak the token, for example that can lead to a further attack:

[amazon_login_pay.php#L848](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/payment/amazon_login_pay.php#L848
)

If an attacker made a tool that calculates the time it takes for every character then he can get amazon_login_pay_ipn_token used to validate this request => calling "parseRawMessage" which is:

[amazon_login_pay.php#L393,L435](https://github.com/opencart/opencart/blob/master/upload/catalog/model/payment/amazon_login_pay.php#L393,L435
)

It calls "simplexml_load_string" on "file_get_contents('php://input')" which is an exception of the sanitization using "htmlspecialchars", so this might lead to an XXE after amazon_login_pay_ipn_token is leaked. Not-timing-safe comparison is used in other places as well.
To avoid this, it's better to use "hash_equals" which is timing-safe.
More about timing attacks:

```
https://codeseekah.com/2012/04/29/timing-attacks-in-web-applications/
http://blog.ircmaxell.com/2014/11/its-all-about-time.html
```

Regards.

**Comment by danielkerr** [comment]
ok this is one of james. will let him know.

**Comment by abdogdn** [comment]
OK.

**Comment by jamesallsup** [comment]
Nice find. I have added hash_equals helper function for backwards support and updated some of the statements using hash checking.

https://github.com/opencart/opencart/commit/033dad1ea556fc980f155ce3b2534b7a45938ce1
