### ISSUE TITLE
I want an Automated Payment System in Opencart

### ISSUE THREAD

**Issue by gabaparas** [opencart/opencart#4023]
Hello Guys, 

I m working on ecommerce Website where i need an module for automated Payment Tranfer..
In this Project, Seller means Owner wants to provide Men & Women Dress on Rent with some Security Amounts...
Owner want thats when Users/Customers return the dress to him then Secuirity amount should be Tranfer in Customers Account automatically...
Can anyone help me for same..

**Comment by jamesallsup** [comment]
https://github.com/opencart/opencart/blob/master/README.md
