### ISSUE TITLE
minor changes to composer

### ISSUE THREAD

**Issue by stefanhuber** [opencart/opencart#4029]
Great that you added composer!

 - Why placing the vendor directory outside of the upload folder?
Since years I use opencart, now I need another folder outside of the opencart root directory, this seems to be not a good solution in my opinion. Composer allows to configure where the vendor folder should be places, my suggestion would be to add the folder under the system folder inside the upload directory (https://getcomposer.org/doc/06-config.md#vendor-dir).

 - Why not adding opencart to packagist?
In order to be able to create a new opencart project one could use composer's create-project command (e.g. composer create-project "opencart/opencart:2.2.0"). Providing opencart to packagist is very simple and would be done automatically in the background...

- Providing composer.json also for old versions?
It would be nice to have composer also for older opencart versions. Currently, this is possible with a great project: https://github.com/etki/opencart-core-installer. But, it would be much easier if this would be available from opencart natively...

**Comment by AlexanderKovalchuk** [comment]
**stefanhuber**, You're absolutely right.

**Comment by victorwbuzz** [comment]
Why not a constant defined in config.php like DIR_VENDOR ? It would allow you to place vendor folder somewhere you judge more convenient.

**Comment by sorcix** [comment]
The current vendor location also breaks Opencart on hardened PHP installations, because it's outside the document root. The only way to get it to work as of now is to modify the startup.php file.

**Comment by danielkerr** [comment]
will get james to change this,

**Comment by danielkerr** [comment]
ok just spoke to james. this can not be done as the vendor folder is insecure. it would be fine if all opencart users knew how to lock down the vendor folder but they don't!

**Comment by stefanhuber** [comment]
ok, this sounds reasonable, thx for your response! However, what about adding OpenCart to packagist (https://packagist.org/)?

**Comment by victorwbuzz** [comment]
@stefanhuber wait for james answer

**Comment by stefanhuber** [comment]
Just follow the link: https://packagist.org/packages/submit
add the url: https://github.com/opencart/opencart
and click submit!

Additionally, one can add a webhook via github settings!

Maximum 5 Minutes work! This would allow anyone proficient with composer (most php developers nowadays) install opencart more easily...

As an example look at our project template for opencart projects: https://github.com/beyondit/opencart-project-template. One could add opencart as a requirement without specifying the repository explicitly and reduce waiting time dramatically!

**Comment by danielkerr** [comment]
going to register on packagist.org after the current person who registered the name there removes it.

**Comment by stefanhuber** [comment]
cool ;)
https://packagist.org/packages/opencart/opencart
