### ISSUE TITLE
 syntax error on line 1105 in \admin\controller\customer\customer.php

### ISSUE THREAD

**Issue by nikto1** [opencart/opencart#4030]
Opencart 2.2.0.0. See title.

Solution:

```php
} elseif (($custom_field['type'] == 'text' &&
 !empty($custom_field['validation']) && 
$custom_field['location'] == 'address') && 
!filter_var($value['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {
```

instead of 

```php
} elseif (($custom_field['type'] == 'text' && 
!empty($custom_field['validation'] && 
$custom_field['location'] == 'address')) 
&& !filter_var($value['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {
```

**Comment by jhon-stone** [comment]
Hello, can you please let me know what i am doing wrong? i followed your instructions:

I delete the original lines and i am now using this:

} elseif (($custom_field['type'] == 'text' &&
 !empty($custom_field['validation']) && 
$custom_field['location'] == 'address') && 
!filter_var($value['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {

but i am still getting the error. can you please let me know what else i am missing here. thanks

**Comment by jhon-stone** [comment]
Thanks a lot !!!! your fix worked perfect !!!!

**Comment by oneakroller** [comment]
Same error appear in here too "catalog/controller/account/address.php on line 522"

**Comment by jhon-stone** [comment]
didnt see that one coming. and how do we fix thay one now? anyone knows?

**Comment by waqasjawed** [comment]
**File:** "catalog/controller/account/address.php"
**Line No:** "522"

**Replace this line:**
    } elseif (($custom_field['type'] == 'text' && !empty($custom_field['validation'] && $custom_field['location'] == 'address')) && !filter_var($value['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {

**With this line:**
    } elseif (($custom_field['type'] == 'text' && !empty($custom_field['validation']) && $custom_field['location'] == 'address') && !filter_var($value['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {

**Comment by waqasjawed** [comment]
Sorry about the mess!
Here are the pull Requests.

#4070 #4071

**Comment by Sufisa** [comment]
@nikto1 Great! worked perfectly! thanks!

**Comment by opencarteli** [comment]
The pull request have merged #4070 #4071

**Comment by grela** [comment]
Great! worked perfectly! 
thanks!

**Comment by dnshvra** [comment]
@nikto1 	thank you soooooooo much

**Comment by niltonfelipe** [comment]
Obrigado pela correção.

**Comment by mehdilh423** [comment]
you are angle!

**Comment by danielkerr** [comment]
@junaid381 make sure u have error reporting turned on at php level.

**Comment by nikto1** [comment]
@junaid381 To increase the speed of your shop just use a bit of htaccess, browser caching, compressing files, use only necessary modules, ecc. The above code is working, i don't think the 500 error has anything to do with the code.

**Comment by iammadhujadhav** [comment]
This page isn’t working
allegradubai.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by nortecweb** [comment]
Parse error: syntax error, unexpected 'ControllerBlogArticle' (T_STRING) in /home/sultanbeylipet/public_html/admin/controller/blog/article.php on line 1


böyle sorunum var acaba nasıl duzeltirim opencart 30.20

**Comment by Mehdi574** [comment]
This isn't working !

**Comment by danielkerr** [comment]
He's talking about 2.2.2.0
