### ISSUE TITLE
subcategory recursion makes things weird

### ISSUE THREAD

**Issue by cypa** [opencart/opencart#4031]
If a subcategory has itself as parent category then it shown somethat weird ... I guess recursion should be forbidden here.

**Comment by danielkerr** [comment]
i think there is validation to stop this

**Comment by opencarteli** [comment]
@cypa any update for this issue? if not , it will close this issue

**Comment by cypa** [comment]
I'm not a opencart developer, I have no plan to fix this bug, but it is bold fat bug and is should be fixed, do not close this issue if you are sensible

**Comment by danielkerr** [comment]
this does not actually cause any major issue with infinite recursion as I used the path method rather than basic parent_Id sub categories trees. i will fix though
