### ISSUE TITLE
SSL doesnt work

### ISSUE THREAD

**Issue by fakhricker** [opencart/opencart#4034]
I have 2.1.0.2 version i have no problem with my SSL
but when i upgrade to 2.2.0.a1 and i  open my site my broswer (google chrome) show "Lock icon with yellow warning triangle". 
i had config the settings and the config.php in public_html and admin
still doesnt work

sry if my english bad

**Comment by danijelGombac** [comment]
Are you set in

 opencart/upload/system/config/admin.php
 opencart/upload/system/config/catalog.php

$_['site_ssl']         = true;
