### ISSUE TITLE
Proxy creates new model class instance on each method call

### ISSUE THREAD

**Issue by kopitoshka** [opencart/opencart#4040]
In opencart 2.2.0.0 why does proxy create a new class instance every time when a class method is called? It is getting hard to share property data between class instances. For example, if the first method call is set some property, it is unavailable for other calls. 

```php

class ModelTest extends Model {
	protected $somevar = 1;
	
	public function methodA() {
		$this->somevar = 123;
	}
	
	public function methodB() {
		echo $this->somevar;
	}
}

$this->load->model('model/test');
$this->model_test->methodA();
$this->model_test->methodB();
```

Output will be "1" instead of "123".

In my opinion, just one class instance should exist in "registry" and it should never be overwritten.

**Comment by skyosev** [comment]
You can test my commit regarding this issue.

**Comment by qahar** [comment]
@skyosev do you check your code with Events? Looking at the code, the Events for model will not triggered once it's available at registry.

**Comment by skyosev** [comment]
@qahar the Events will actually trigger. Look again :)

**Comment by kopitoshka** [comment]
the issue is resolved, thank you.

**Comment by vanvisor** [comment]
Code in first message will not work. To make it correct you shouldn't declare property $somevar.
```
class ModelTest extends Model {
    protected $somevar = 1;

    public function methodA() {
        $this->somevar = 123;
    }

    public function methodB() {
        echo $this->somevar;
    }
}

$this->load->model('model/test');
$this->model_test->methodA();
$this->model_test->methodB(); //will return 1

```
Without declaration:
```
class ModelTest extends Model {
    //protected $somevar = 1;

    public function methodA() {
        $this->somevar = 123;
    }

    public function methodB() {
        echo $this->somevar;
    }
}

$this->load->model('model/test');
$this->model_test->methodA();
$this->model_test->methodB(); //will return 123, as expected
```

After uninstalling override engine (uses ModelDecorator instead of Proxy) my module stoped working. Wasted much time to resolve it (((
