### ISSUE TITLE
All link not change

### ISSUE THREAD

**Issue by fakhricker** [opencart/opencart#4048]
im was set SSL configuration in:

config.php in public_html and admin folder

system/config/admin.php
system/config/catalog.php
$_['site_ssl'] = true;

and system/library/url.php

everything was ok
but when i opened sub category
this happened
http://s17.postimg.org/iexhiuq27/https_page.png

when i tried http
http://s8.postimg.org/hmia8g4md/non_https.png

did i miss some configuration
._.

Updated:
when i unable seo the page run complete as https
but when i activated back the page cant run complete
._.

**Comment by danielkerr** [comment]
post your web site link!!! messing around!

**Comment by fakhricker** [comment]
gamio.web.id
