### ISSUE TITLE
[2.2.0.0] Language locale is not saved

### ISSUE THREAD

**Issue by gob33** [opencart/opencart#4050]
When creating a new language, there is no more locale (in the form and DB).
So that it is no more possible to use PHP setlocale() for formatting dates, time, etc...in extensions.

![langages](https://cloud.githubusercontent.com/assets/4837882/13530515/0376db78-e222-11e5-9f2c-8fff6f819468.png)
Ex:
```
setlocale(LC_TIME, explode(',', $language['locale']));
```
$language['code'] could be used instead but not sure it displays accents correctly (like with fr-FR.UTF-8).
Rather annoying.

**Comment by gob33** [comment]
$language['code'] should be the ISO 3166-1 code 'gb' with 2 letters (no change) like in zones.
$language['directory'] should be the new directory 'en-gb'.
$language['image'] should be 'en-gb.png' .

**Comment by b-and-p** [comment]
I find this to be an issue as well, this will require updating and releasing another version of any 3rd party modules that use language in some way, just tested one of my modules on a fresh install of 2.2.0.0 and find it broken in both  - admin and store front because of this.

Language in catalog has code set to **'en'**, in admin it is set to **'en-gb'**, this breaks my module setting array, as the language code is used as key.
Also, the key `image` is missing from language object in admin, so this breaks the flag icons.

**Catalog language object**

     object(Language)[37]
      private 'default' => string 'en-gb' (length=5)
      private 'directory' => string 'en-gb' (length=5)
      private 'data' => 
      array (size=76)
      'code' => string 'en' (length=2)
      'direction' => string 'ltr' (length=3)
      'date_format_short' => string 'd/m/Y' (length=5)
      'date_format_long' => string 'l dS F Y' (length=8)
      'time_format' => string 'h:i:s A' (length=7)
       ...

**Admin language object**

     array (size=5)
     'language_id' => string '1' (length=1)
     'name' => string 'English' (length=7)
     'code' => string 'en-gb' (length=5)
     'sort_order' => string '1' (length=1)
     'status' => string '1' (length=1)

Are these and other core changes documented anywhere?

**Comment by mhcwebdesign** [comment]
There are indeed some changes to the way languages are handled.

To start with: OpenCart 2.2.0.0 doesn't use the DB fields 'directory', 'image' and 'locale'. The name of the language folder always has to be same one as the language code, e.g. something like 'en-gb' or 'de-de'. The language folder also ought to have the image file, e.g. 'catalog/language/en-g/en-gb.png' or 'catalog/language/de-de/de-de.png' etc.

It looks like the only reason why the database still has the 'image', 'locale' and 'directory' fields in there is for backward compatibility with previous Opencart versions and their language packs.

Having said that, I agree with the previous comments that the 'locale' field should be suppported again for the reasons mentioned by above posters, e.g. the need to use 'locale' in 3rd party extensions.

**Comment by gob33** [comment]
Over 2.1.0.2, there was nothing to change here, just adopting the convention that image and directory new names will be typed like 'language_country'.

**Comment by gob33** [comment]
I have tried a workaround, building a locale with the code:
```
if (!empty($language['locale'])) {
  $locale = $language['locale'];
} elseif (!empty($language['code'])) {
  $data = explode('-', $language['code']);
  $locale = $data[0].'_'.strtoupper($data[1]).'.UTF-8,'.$data[0].'_'.strtoupper($data[1]).','.$data[0].'-'.$data[1];
} else {
  $locale = null;
}
```
which gives "fr_FR.UTF-8,fr_FR,fr-fr".
But doesnt works on Windows which expects "french" (used in previous OC version) to get French_France.1252
So that it is absolutely necessary to revert back changes here as it was before 2.2.0.0.

**Comment by danielkerr** [comment]
ok will add local but the folder names remain the same. its useful for the opencart installer and if the site has no DB connection to still be able to work without the DB.

**Comment by Ergotron-Mexico** [comment]
I have problems...!
