### ISSUE TITLE
[2.2.0.0] language in common.js

### ISSUE THREAD

**Issue by yvonn** [opencart/opencart#4051]
Semicolon forgotten in catalog/view/lavascript/common.js
at line 51 
replace
`	})`
add
`	});`

**Comment by McBochi** [comment]
File a pull request! ;)

**Comment by yvonn** [comment]
hmm.. I did try that before but maybe I am doing it wrong.

**Comment by McBochi** [comment]
Oh, looks like you created that pull request against your own fork: https://github.com/yvonn/opencart/pull/6
Create one against the official repository and it should be fine!

**Comment by danielkerr** [comment]
I can not find anything missing

**Comment by yvonn** [comment]
I see it is fixed in 2.2.0.0_a1
