### ISSUE TITLE
Unknown column customer_activity in 2.2.0.0 upgrade

### ISSUE THREAD

**Issue by timint** [opencart/opencart#4052]
I have a clean Softaculous install of OpenCart 2.1.something. I recceived a notice of upgrading to 2.2.0.0 but the final step takes me to an error. See attached image.

![clipboard01](https://cloud.githubusercontent.com/assets/359192/13536749/d33d0c50-e241-11e5-829c-c9fe209cff8e.png)

After the javascriprt alert the upgrade halts.

**Comment by opencarteli** [comment]
Please make sure you empty your database already

**Comment by litecart** [comment]
@opencarteli

What is the point of upgrading if you empty your database???

Accoarding to Softaculous this was a known problem with your installer and they had been waiting for a fix.

I solved it with a fresh install but I wanted to notify you know there were an issue with the upgrade script who concerned all Softaculous users.

**Comment by timint** [comment]
@opencarteli

What is the point of upgrading if you empty your database???

Accoarding to Softaculous this was a known problem with your installer and they had been waiting for a fix.

I solved it with a fresh install but I wanted to notify you know there were an issue with the upgrade script who concerned all Softaculous users.

**Comment by danielkerr** [comment]
you need to run through the upgrade installer correctly. the upgrade script will create any missing tables.

not sure what happened here.

**Comment by timint** [comment]
Punit@Softaculous said on dec 4th:

> We do not provide upgrade of OpenCart from 2.1.0.1 from 2.0.3.1. There are errors in upgrade. Also many tables of 2.1.0.1 are not generating after upgrade.
> I have notified this to the developer. We will provide upgrade once we get patch or any solution.
