### ISSUE TITLE
Mixed content problems

### ISSUE THREAD

**Issue by BlueKore** [opencart/opencart#4053]
If i am access the website in HTTPS, i have some mixed content problems in the index page (for instance). There are some content that is served via HTTP. Furthermore, if i want to use HTTPS in all pages, that is not possible.

**Comment by danielkerr** [comment]
should i guess if its a default install or some template you downloaded!

**Comment by BlueKore** [comment]
I didn't download any template. Don't kick the problem. It's not the way to make a better product. What do you mean by 'default install' ? I started my website in ssl, but the form action url's are not served correctly.
