### ISSUE TITLE
Manual install errors

### ISSUE THREAD

**Issue by donaceli** [opencart/opencart#4056]
Warning: session_start(): open(/tmp/sess_0d7b1f49088ec786d4adefe51f537574, O_RDWR) failed: No such file or directory (2) in /home/user/public_html/subdomain/system/library/session.php on line 38

This is the error that keeps popping up after upload of files via ftp for manual install. Any suggestions?

**Comment by danielkerr** [comment]
that is a directory permission issue in your php. its not opencart related. contact you host.
