### ISSUE TITLE
Proxy vs variables by reference in models

### ISSUE THREAD

**Issue by kopitoshka** [opencart/opencart#4057]
Proxy does not allow to pass variables by reference to model methods.

```php

class ModelTest extends Model {
	public function methodA(&$var) {
		$var = 123;
	}
}

$var = 1;
$this->model_test->methodA($var);
echo $var;

```
This code generates an error like this:
Warning: Parameter 1 to ModelTest::methodA() expected to be a reference, value given.

Can you fix this or provide an alternative way to load a model bypassing the proxy mechanism?

**Comment by skyosev** [comment]
I think this case is unfixable with the current model loading implementation, unless some advanced techniques (such as Reflection) are used or the Proxy is removed at all. 

Workaround: 

```php
class ModelTest extends Model {
    public function methodA(array $args) {
        $args[0] = 123;
        $args[1] = 'changed';
    }
}

$var   = 1;
$var2 = 'changeMe';

$this->model_test->methodA([&$var, &$var2]);

echo $var, $var2;
```

**Comment by danielkerr** [comment]
which version of php are u using?

actually the fix is put the reference object in an array and pass it through. i did this with the totals. if you have a extension that requires this you need to use this type of work around code.

blame PHP!

**Comment by danielkerr** [comment]
also i dont believe reflect can be used for references. if you could post some example code of it workign though.

**Comment by kopitoshka** [comment]
Thank you for the clarifications.
