### ISSUE TITLE
To open the filemanager in a specific folder using Opencart?

### ISSUE THREAD

**Issue by kodomoyeh** [opencart/opencart#4059]
I try to manager images of product as 
./image/catalog/product/sku1
./image/catalog/product/sku2
./image/catalog/product/sku3

every time when I upload image under product1, the filemanager would popup and open folder 
./image/catalog/product/sku1
which sku1 is the sku of product1

how should I implement this feature ?

**Comment by danielkerr** [comment]
maybe using sessions.

just set the last loaded directory.
