### ISSUE TITLE
2.2.0.0 Errors showing even if 'display errors' is set to No

### ISSUE THREAD

**Issue by QualityWorks** [opencart/opencart#4062]
The title is pretty self-explanatory, the errors on the front pages are showing, even if the 'display errors' option is set to 'no' in the settings. 

I have tested with this error:
http://test.qualityworks.eu/2200/index.php?route=product/product&path[]=1
as another test I have checked this in 1564 and there the setting is working fine
http://test.qualityworks.eu/1564/index.php?route=product/product&path[]=1

both these shops are set to not display errors

**Comment by danijelGombac** [comment]
Are you set display errors in opencart/upload/system/config/default.php?

**Comment by QualityWorks** [comment]
I'm talking about the setting in  the admin login 'system' > 'settings' > 'Your Store' > [server]

**Comment by danijelGombac** [comment]
I think that this setting is now moved in system/config/default.php

**Comment by QualityWorks** [comment]
the setting is still there, it's just not working

**Comment by danijelGombac** [comment]
I don't know why is still there.

**Comment by QualityWorks** [comment]
it's there because it belongs there I assume? It's always been there and it makes sense to keep it there and not hardcoded in the php. So if the php moved, that's probably where the issue lies.

**Comment by readconsult** [comment]
Yes, this would seem to be a bug - the choice in 'system' > 'settings' > 'Your Store' > [server] is not toggling in opencart/upload/system/config/default.php

Very annoying - and probably the only change in 2.2.0.0 - as the changelog doesn't seem to show any changes in 2.2.0.0 ;)

This needs to be fixed as a priority - most users aren't going digging in the code.

**Comment by danijelGombac** [comment]
There is another problem with config_secure, site_ssl and config_ssl which is set only in multistore.
