### ISSUE TITLE
OC 2.2.0.0 Wrong event unregister

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#4074]
This code in system/engine/event.php looks strange:

```
	public function unregister($trigger, $action) {
		if (isset($this->data[$trigger])) {
			unset($this->data[$trigger]);
		}
	}
```

This would remove all actions for a given trigger. I think it should only remove it for a certain action.

**Comment by danielkerr** [comment]
already fixed not sure why the issue is still open
