### ISSUE TITLE
Module Page not Font

### ISSUE THREAD

**Issue by manojb05** [opencart/opencart#4077]
I am download a opencart version 2.2.0.0, some strange reason Extension>Modules page is not open some error is comes up 
"Server error
The website encountered an error while retrieving http://in.domain.com/admin/index.php?route=extension/module&token=E9a15TyrHXZCLcJlz8u65m0WsU3Q65EL. It may be down for maintenance or configured incorrectly."

**Comment by danielkerr** [comment]
maybe reupload or ask your host if they are blockign urls with the words extension/module in
