### ISSUE TITLE
SEO on SSL cant load page

### ISSUE THREAD

**Issue by fakhricker** [opencart/opencart#4078]
i thought that was bug for seo but when i installed on the other hosting and domain thats totaly not seo bug
look http://www.blimurah.com/desktops/pc
http://s10.postimg.org/5djueg6s9/without_ssl_its_works.png

but when im installed ssl on my hosting it cant load compelete. Its like .css wont load in ssl mode
https://www.gamio.web.id/desktops/pc
http://s22.postimg.org/gomoisxlt/seo_ssl_not_work.png

but thats became strange when in category i click **Show All Desktop** in Desktop menu
https://www.gamio.web.id/desktops
http://s27.postimg.org/eldvcuhqb/132.png

and the page will load complete in ssl if i disable SEO mode
https://www.gamio.web.id/index.php?route=product/category&path=20_26
http://s8.postimg.org/gy67xsfvp/disable_seo.png

Sry for my bad language
:)

**Comment by danielkerr** [comment]
ok its fixed in the master branch.

**Comment by bau720123** [comment]
hi @danielkerr 
I have the same problem in version 2.2.0
but because some reason，I can't upgrade to the latest 2.3.0.2
could you tell me how to fix the problem in 2.2.0 or which file should I upgrade
