### ISSUE TITLE
Change of theme

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#4081]
Theme change is not work

http://forum.opencart.com/viewtopic.php?f=190&t=159122&p=607799#p607799

Loader response to default theme.

**Comment by dracon80** [comment]
I'm unable to set a custom theme on either a local development system or my host. Both fresh installs.

**Comment by pekka2** [comment]
@dracon80 Custom theme need be theme setting files in admin/*/theme. Then this is temporary solution: http://forum.opencart.com/viewtopic.php?f=190&t=159122&p=607799#p607833

**Comment by danielkerr** [comment]
what about when you go to admin > extension > theme > Default Store Theme

then set the field Theme Directory to the name of the custom theme?

**Comment by danielkerr** [comment]
I just tested this and the images work!

maybe after upgraded the user should go to admin > extension > theme > Default Store Theme

then set the field Theme Directory to the name of the custom theme?
