### ISSUE TITLE
.css and js wont work in https

### ISSUE THREAD

**Issue by fakhricker** [opencart/opencart#4083]
i just install fresh patch from master and configuration ssl in: 
config.php in admin and public_html folder
admin.php and catalog.php in system/config
but
.css and js wont work if i changed link became https
without https://
www.gamio.web.id/desktops/mac/imac
http://s15.postimg.org/5pocsu123/work.png

with https
https://www.gamio.web.id/desktops/mac/imac
http://s7.postimg.org/7dqv3wfwb/wont_work.png

thx before
:)

**Comment by danielkerr** [comment]
look at view source

<base href="" />

<base href="http://www.gamio.web.id/" />

did u enter both url and ssl in the admin settings page?

**Comment by danielkerr** [comment]
ok found the issue. will fix tomorrow

**Comment by fakhricker** [comment]
ok its working now thx
:)

**Comment by guidone65** [comment]
Hi, where can i find the fixed file? Regards!

**Comment by fakhricker** [comment]
this patch
https://github.com/opencart/opencart/commit/7d653c60578573aefcb477b1c183567928dde23c
i hope this help u
:)

**Comment by danielkerr** [comment]
it was already added to the master branch! next time check before asking for something that has already been fixed!!
