### ISSUE TITLE
[OC 2.2.0.0] admin contact.tpl summernote error

### ISSUE THREAD

**Issue by b-and-p** [opencart/opencart#4089]
File: `opencart\admin\view\template\marketing\contact.tpl` line 194:

      	// Summer not fix
	 $('textarea[name=\'message\']').val($('#input-message').code());

cause JS error:
    
        Uncaught TypeError: $(...).code is not a function

Cause summernote API has changed.

Proposed solution: comment out or delete offending code
     
       // Summer not fix
	// $('textarea[name=\'message\']').val($('#input-message').code());

**Comment by bau720123** [comment]
I have the same problem just like @b-and-p said
after comment it， seem work perfect
hope it will fix in the new version

**Comment by lives-in-th** [comment]
FIX Marketing Mail in OPC2.2.0.0

Replace Line194 to end with this code

function send(url) {
	$.ajax({
		url: url,
		type: 'post',
		data: $('#content select, #content input, #content textarea'),
		dataType: 'json',
		beforeSend: function() {
			$('#button-send').button('loading');
		},
		complete: function() {
			$('#button-send').button('reset');
		},
		success: function(json) {
			$('.alert, .text-danger').remove();

			if (json['error']) {
				if (json['error']['warning']) {
					$('#content > .container-fluid').prepend('<div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> ' + json['error']['warning'] + '</div>');
				}

				if (json['error']['email']) {
					$('#content > .container-fluid').prepend('<div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> ' + json['error']['email'] + '</div>');
				}

				if (json['error']['subject']) {
					$('input[name=\'subject\']').after('<div class="text-danger">' + json['error']['subject'] + '</div>');
				}

				if (json['error']['message']) {
					$('textarea[name=\'message\']').parent().append('<div class="text-danger">' + json['error']['message'] + '</div>');
				}
			}

			if (json['success']) {
				$('#content > .container-fluid').prepend('<div class="alert alert-success"><i class="fa fa-check-circle"></i>  ' + json['success'] + '</div>');
			}
				
			if (json['next']) {
				send(json['next']);
			}
		},
		error: function(xhr, ajaxOptions, thrownError) {
			alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
		}
	});
}
//--></script></div>
<?php echo $footer; ?>
