### ISSUE TITLE
Edit Cart Blank Page Issue

### ISSUE THREAD

**Issue by xannonmedia** [opencart/opencart#4093]
When updating quantity on the cart page, once you press the refresh button it takes you to a blank page with only [ ] on it.

Using Opencart v 2.0.3.1

**Comment by danielkerr** [comment]
sounds like you have error reporting turned off and the system is showing nothing because there is an error blocking the page loading.

**Comment by xannonmedia** [comment]
It only happens with products that have options.  Fresh install (demo products) OCv 2.0.3.1

**Comment by jorimvanhove** [comment]
Same issue here, clicking the Update button redirects to index.php?route=checkout/cart/edit showing only an empty array.
[]

Setup is OC2.0.1.1 with SSL enabled. Console reports 
```
Resource interpreted as Document but transferred with MIME type application/json: "https://{website}/index.php?route=checkout/cart/edit".
Navigated to https://{website}/index.php?route=checkout/cart/edit
content.js:200 JSON Formatter: Type "json" to inspect.
```
