### ISSUE TITLE
Add module button is not working in admin Layouts page [OC 2.2.0.0]

### ISSUE THREAD

**Issue by harnishdesign** [opencart/opencart#4094]
I have realized. Add module button is not working in Layout page admin OC 2.2.0.0.
Go to admin > Design > Layouts > Edit Layouts > & then, I cannot add new module.

is it really this type issue there?

![screenshot](https://cloud.githubusercontent.com/assets/2634085/13694723/3dabb5c8-e77e-11e5-8770-b91c7825697a.jpg)

**Comment by waqasjawed** [comment]
Which browser are you using?

**Comment by harnishdesign** [comment]
I have tested in all major browser. Same issue create in all major browser.

Get following error.

![screenshot](https://cloud.githubusercontent.com/assets/2634085/13699202/f60b8222-e79e-11e5-9193-11bb2c5a7f4d.jpg)

**Comment by waqasjawed** [comment]
Default Opencart doesn't has this issue, I have tested in all major browsers. It must be any of your Opencart extension, or it can be the theme you are using.

**Comment by waqasjawed** [comment]
Make sure you are only using Opencart extensions or theme which are compatible with OC 2.2.0.0 version. Its a new version so not so many extensions and themes support this version for now.

**Comment by harnishdesign** [comment]
You are right. It was third party customization issue. I have fixed.
Thanks.
