### ISSUE TITLE
config.php HTTP_SERVER not working

### ISSUE THREAD

**Issue by Krosik** [opencart/opencart#4107]
**2.1.0.2**
clean install and in config.php
define('HTTP_SERVER', 'http://www.domain1.com/domains/domain1.com/');
link on logo on main site is (and all menu links accordingly)
http://www.domain1.com/domains/domain1.com/index.php?route=common/home

after this change
define('HTTP_SERVER', 'http://www.domain1.com/');
link on logo
http://www.domain1.com/index.php?route=common/home

**2.2.0.0**
clean install and in config.php
define('HTTP_SERVER', 'http://www.domain1.com/domains/domain1.com/');
link on logo on main site is
http://www.domain1.com/domains/domain1.com/index.php?route=common/home

after this change
define('HTTP_SERVER', 'http://www.domain1.com/');
link on logo
http://www.domain1.com/domains/domain1.com/index.php?route=common/home

So looks like **config.php -> HTTP_SERVER is not working in 2.2.0.0**

**Comment by danielkerr** [comment]
stop posting!

**Comment by Sebastian-Wallace** [comment]
Why? its a legitimate issue?
