### ISSUE TITLE
Attribute groups and attributes not displayed in Admin product tab Attributes

### ISSUE THREAD

**Issue by Urs-Bruelhart** [opencart/opencart#4110]
Clean install locally, deleted demo products, categories, attributes, attribute groups, options.
Setup 4 attribute groups, setup attributes for this 4 groups. 
Create a new product assign attributs and there are only the first 2 groups in the popup to assign.

There should be Gruppe 3 and Gruppe 4 with Attributes -> see attachement.

Opencart 2.2.0.0, faced on a server and locally reproduced.
![bildschirmfoto 2016-03-13 um 13 47 45](https://cloud.githubusercontent.com/assets/837404/13728745/373cdce4-e922-11e5-86b4-6e259bdee8d0.png)

Atributes / Groups setup:

![bildschirmfoto 2016-03-13 um 14 01 35](https://cloud.githubusercontent.com/assets/837404/13728810/319178ac-e924-11e5-9b40-c3ba3d977d95.png)

Thank you very much.

**Comment by steven0liu** [comment]
Hi

This is normal behavior as coded in source file.
please refer to "opencart\admin\controller\catalog\attribute.php" line 414-418, especially line 417, there is a limited for the result that can be displayed in check list.
what you need to do is write attribute name manually and it will filtered with which you typed.
maybe designer think there is no need and can not display all attribute in the list, so he set a limited to display only 5 items

the same situation apply to category etc.

hope this can help you.

**Comment by Urs-Bruelhart** [comment]
Ah yes, thank you for the tip.
