### ISSUE TITLE
site_base and site_ssl in multistore

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#4113]
I have one question, how is handled site_base and site_ssl in multistore. I don't unederstend how is working. Now we have site_base and site_ssl with HTTP and HTTPS and config_url and config_ssl from DB or HTTP and HTTPS. Why use config_url and config_ssl, if all urls was created with site_base and site_ssl.

**Comment by danielkerr** [comment]
the url class need re intalizing with the new base url
