### ISSUE TITLE
Add Language Code is not possible from Admin

### ISSUE THREAD

**Issue by hendrachristian** [opencart/opencart#4120]
In Admin > System > Localisation > Language, there's no way to add Locale, Code, Directory, Image to a Language. All that's available on the Code dropdown is "en-gb" and "english". The old screen have them as text box. The Locale, Directory, and Image field is also missing from this screen.

Furthermore, adding to the confusion, the Opencart documentation is also not updated with the current display: http://docs.opencart.com/system/localisation/language/

**Comment by gob33** [comment]
See #4050

**Comment by hendrachristian** [comment]
@gob33 sorry for the double post. you're right, it's being raised on the other issue ticket. feel free to close this issue. thanks for the pointer.

**Comment by gojdic** [comment]
after 2.2.0.0 has been released, whole "add language" process has changed. you can use lang pack from 2.1.0.2, but you have to edit lang folder names in both /admin and /catalog, use ISO 639-1 standard language codes, to add image, create "lang_iso_code.png" file in both admin and catalog, also you can change code in "lang_iso_code.php" in both admin and catalog
