### ISSUE TITLE
how to upgrade theme

### ISSUE THREAD

**Issue by rasheedhamdawi** [opencart/opencart#4121]
Hi there,

after I've upgraded to 2.2.0.0 the theme doesn't work and I get some errors on the template files

> Notice: Undefined property: Template\Basic::$registry in /catalog/view/theme/pav_minimo/template/module/featured.tpl on line 2

	<?php
	$load = $this->registry->get("load");
	$language = $load->language("module/themecontrol");
	$text_sale = $language['text_sale'];
	$quick_view = $language['quick_view'];
	?>

thanks

**Comment by danielkerr** [comment]
i have no idea what your talking about. look at the default them in the admin. look at the fields it uses.
