### ISSUE TITLE
cannot edit or delete order in opencart version 2.0.2.0.

### ISSUE THREAD

**Issue by Mariam522** [opencart/opencart#4127]
hi. 

i have 2 sites running in opencart version 2.0.2.0 on the same server in different folders with almost same setting. in one site it is running perfectly. i can edit orders and delete them. but in other main site i cannot do that. i have tried many solutions that says create new user api. replace admin files with other site that is working perfeclty but cannot mae it work. its been 2 days and yet no solution. anyone please help me out.

your help is greatly appreciated
![error2](https://cloud.githubusercontent.com/assets/17698476/13777386/a98bcba6-ead1-11e5-843a-dc461bd2321c.PNG)

**Comment by Antquel** [comment]
Same problem here.

**Comment by opencarteli** [comment]
Maybe update your ver to settle the problem
