### ISSUE TITLE
url use "www" missing icons 

### ISSUE THREAD

**Issue by d3csaba** [opencart/opencart#4130]
example missing icons:
http://www.digx.hu

without www okay:
http://digx.hu

**Comment by Rpent001** [comment]
@d3csaba Can you access the icon using "www" manually on the same server?  That sounds like more of an Apache issue to me, not an OpenCart issue.  You would need to setup a server alias in your Apache directives if your config is for digx.hu

Ex:
ServerAlias www.digx.hu

**Comment by d3csaba** [comment]
2016. 03. 22. 12:26 keltezéssel, Rick írta:
>
> @d3csaba <https://github.com/d3csaba> Can you access the icon using 
> "www" manually on the same server? That sounds like more of an Apache 
> issue to me, not an OpenCart issue. You would need to setup a server 
> alias in your Apache directives if your config is for digx.hu
>
> Ex:
> ServerAlias www.digx.hu <http://www.digx.hu>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/opencart/opencart/issues/4130#issuecomment-199769149>
>
The service using nginx. Unfortunately, I do not understand this part, 
it was just an observation on my part. All I know is that the original 
opencart 2.2 .htacces converted ngnix file format. Sorry for the poor 
English.

-- 
Üdvözlettel, Demeter Csaba
