### ISSUE TITLE
Opencart 2.2.0 Voucher notification event issue!

### ISSUE THREAD

**Issue by jimmyphong** [opencart/opencart#4133]
In install.sql 
line 1418
```
INSERT INTO `oc_event` (`event_id`, `code`, `trigger`, `action`) VALUES
(1, 'voucher', 'catalog/model/checkout/order/addHistory/after', 'total/voucher/send');
```
Wrong function
Need change to 
```
INSERT INTO `oc_event` (`event_id`, `code`, `trigger`, `action`) VALUES
(1, 'voucher', 'catalog/model/checkout/order/addOrderHistory/after', 'total/voucher/send');
```

Because the addHistory changed to addOrderHistory !

**Comment by hehb** [comment]
in addition, according to the document, The trigger is made up of many parts: application / type / folder / file / method / before or after

it seems that opencart trigger does not include application

`$result = $registry->get('event')->trigger('model/' . $route . '/before', array_merge(array(&$route), $args));
`
