### ISSUE TITLE
Coupon and Voucher History Empty

### ISSUE THREAD

**Issue by svayamalhotra** [opencart/opencart#4134]
I just downloaded and installed 2.0.3.1. I have been testing the coupon and voucher features and have run into some issues. When using coupons and vouchers to check out, they work fine. However, coupon and voucher history never get recorded upon checkout. I tried invoicing the order and marking it shipped, but this didn't do anything either. I tried COD and bank transfer payment methods.

This means that a customer can keep using the same coupon (even if it is marked 1 use only) and the same voucher over and over again. That will certainly be bad for business. I searched the forums and found several reports of coupon history not working in 1.5.*. No results yet in the 2.0 board.

Please make some suggestions. Reply ASAP !

Thanks,
Svayam

**Comment by danielkerr** [comment]
work for me!

**Comment by svayamalhotra** [comment]
Sory Daniel Sir, but you have a very bad service.
I am not questioning you, I'm just asking you.
Your don't answer anything like all time but Qphoria told me the answer for same problem.
Anyways, it's all your, What could I do in this.
