### ISSUE TITLE
Order edit gives the json error message

### ISSUE THREAD

**Issue by faizconcept** [opencart/opencart#4135]
When ever I open the order to edit mode then click on continue button then below error message display.

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

OK

<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 8157454891696494493</body></html>

I am using the opencart 2.0.3.1 version

I have debug by firebug and find out that below message display from http://www.domain.com/admin/index.php?route=sale/order/api&token=59529e8d3950c2b0ecebc486c3423edd&api=api/voucher/add&store_id=0

<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult
 with your administrator.<br><br>Your support ID is: 8157454891696503049</body></html>

Please help me. How to solve this issue. It is a core file bug.

Thanks !
Faiz

**Comment by faizconcept** [comment]
Hi Danielkerr,

Can you let me know how to solve the issue.?

Without replay you have closed this thread ? why you have closed ?

Please let me know.

Thanks !

**Comment by Rpent001** [comment]
Welcome to OpenCart @faizconcept .  LOL
