### ISSUE TITLE
Multiple clicks on install module generate multiple database instances

### ISSUE THREAD

**Issue by LucasKauz** [opencart/opencart#4140]
This should be a front-end issue, but if a user clicks multiple times on the "Install" in the model list it create multiple entries in the database and also creates multiple instances in the selection list (while it does not create multiple instances on the module list).

The button I'm talking about

![image](https://cloud.githubusercontent.com/assets/1552681/13834016/42252b3e-ebca-11e5-9eae-878b88d8ce25.png)

It happens on native modules or not, like affiliates. Example of the problem in the database:

![image](https://cloud.githubusercontent.com/assets/1552681/13834030/69b38704-ebca-11e5-83b5-660e182db9c6.png)

And in the list

![image](https://cloud.githubusercontent.com/assets/1552681/13834048/99bb620a-ebca-11e5-8e38-8642d27d1cc4.png)

It could be fixed with an unbind, for example. About the database itself, it does not seem a problem the "module namespace" conflict.

I can't fix it right now and send the pull request, that's why the issue opening. Thank you.

**Comment by RadhikaMayani** [comment]
In which version you are facing this problem?

**Comment by LucasKauz** [comment]
Version 2.2, downloaded this week on the site.

**Comment by RadhikaMayani** [comment]
In my case, it works fine.

**Comment by LucasKauz** [comment]
It works as expected, the problem is when you click multiple times before the redirect is completed.

1. Go to extension/module
2. Click install
3. Before the redirect is complete click install again, or multiple time

Note that it does become a problem when the user has slow connection or for some reason the reload take too much time to happen and he starts clicking it again.

**Comment by RadhikaMayani** [comment]
yes, now I am facing the same issue.

**Comment by danijelGombac** [comment]
Added pull request https://github.com/opencart/opencart/pull/4143 to prevent this.

**Comment by LucasKauz** [comment]
The request #4143 will fix the issue.
