### ISSUE TITLE
Customers can't reset their password

### ISSUE THREAD

**Issue by druscila** [opencart/opencart#4146]
Reset password is not working, password success message is shown but password isn't changed. Old password remain. Only for customer password reset, the admin password reset works properly.

**Comment by FunkyUserName** [comment]
yes i can confirm this. i even have a fix for it:
in reset.php replace : 		$this->model_account_customer->editPassword($customer_info['customer_id'], $this->request->post['password']);
with
$this->model_account_customer->editPassword($customer_info['email'], $this->request->post['password']);

and in customer.php replace:
$query = $this->db->query("SELECT customer_id, firstname, lastname FROM `" . DB_PREFIX . "customer` WHERE code = '" . $this->db->escape($code) . "' AND code != ''");
with
$query = $this->db->query("SELECT customer_id, firstname, lastname, email FROM `" . DB_PREFIX . "customer` WHERE code = '" . $this->db->escape($code) . "' AND code != ''");

**Comment by druscila** [comment]
It Worked!

Thank You!!!
