### ISSUE TITLE
Fatal Error image.php

### ISSUE THREAD

**Issue by mudzify** [opencart/opencart#4153]
Hi, I am getting the following error when I open new product added in the products category. 

Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 2000 bytes) in /home/electrosolz/public_html/store/system/library/image.php on line 105

The admin dashboard also highlights the quantity column in red for this particular item.

**Comment by VadymVolos** [comment]
OpenCart 2.2.0.0
My Error:
```
Warning: imagecreatetruecolor(): Invalid image dimensions in /shop/system/library/image.php on line 105
Warning: imagecolorallocate() expects parameter 1 to be resource, boolean given in /shop/system/library/image.php on line 113
Warning: imagefilledrectangle() expects parameter 1 to be resource, boolean given in /shop/system/library/image.php on line 116
Warning: imagecopyresampled() expects parameter 1 to be resource, boolean given in /shop/system/library/image.php on line118
```

**Comment by VadymVolos** [comment]
My problem, I decided!
The theme settings, do not touch anything, just click Save.
The error is gone, Images are displayed correctly.

http://forum.opencart.com/viewtopic.php?t=159122&p=607893
