### ISSUE TITLE
Default English language direcroity is wrong

### ISSUE THREAD

**Issue by thekrotek** [opencart/opencart#4156]
I see, that you've changed directory and code name for English, but directory still has old name inserted by default:

```php
INSERT INTO `oc_language` (`language_id`, `name`, `code`, `locale`, `image`, `directory`, `sort_order`, `status`) VALUES
(1, 'English', 'en-gb', 'en_US.UTF-8,en_US,en-gb,english', 'gb.png', 'english', 1, 1);
```

Not also sure about locale (also the old one):

```php
$_['code']                          = 'en';
```

Basically, we now have 2 directories (en-gb, english) and 2 codes (en-gb, en) for English, which can break any extension, which depend on current customer/user language.

**Comment by danielkerr** [comment]
the upgrade script fixed this
