### ISSUE TITLE
SSL / HTTPS configuration issues

### ISSUE THREAD

**Issue by alexonciu** [opencart/opencart#4158]
I really don't understand what happened in v. 2.2.0 with the SSL / HTTPS config. It used to be so straightforward.
Following the normal steps doesn't work anymore.
By normal steps I mean:
1. Enable SSL in Settings > Edit Store > Server > Use SSL > on

2. Edit config.php 
HTTPS_SERVER - correct (https) address
HTTP_SERVER define to the https address to force https on all pages

3. Edit /admin/config.php 
HTTPS_SERVER - correct https address / admin
HTTPS_CATALOG - correct https address
HTTP_SERVER define to the https address to force https on all admin pages
HTTP_CATALOG define to the https address to force https on all storefront pages

4. (I dont know if it's really requeired - I don't think so - I only did it to play it safe)
Extensions > Modifications > refresh

Doing this steps gets you lots of mixed content warning -> there is a mixture of http and https content

Moving forward going to the file system/config/ 
Edit admin.php and catalog.php and define **manually**:
$_['site_ssl']          = true;
By default it is
$_['site_ssl']          = false;
(in my opinion it should change to true when SSL is enabled in the admin interface - but it doesn't)

Doing this gets rid of the mixed content warning but the internal links are still http.
This is puzzling since the config in system/config/admin.php and /system/config/catalog.php are like this:
$_['site_base']         = substr(HTTP_SERVER, 7);
Since the HTTP_SERVER was defined as force **HTTPS** (step 2) I have absolutely no idea why the engine insists to link **HTTP** internal pages.
This is very very very bad for SEO if you transition to a pure https site and I have absolutely no idea where the site_base gets the HTTP_SERVER config from.

Can you pretty please look into this?

**Comment by danielkerr** [comment]
already changed in master

**Comment by alexonciu** [comment]
Does this mean that it is already fixed if I download the zip from opencart.com or I need to wait for the next release / clone the git repository?
Sorry for the rookie question - not really used to git.
Thanks!

**Comment by komirad** [comment]
The zip on opencart.com is not updated yet.

**Comment by Lepraz** [comment]
I have Opencart 2.1.0.2, 
there no admin.php file in
system/config/

HTTPS working fine in front end, but get error of mixed - secure and unsecured contain when open order in admin panel. Any idea how to fix it?

**Comment by calderwood** [comment]
I  also noticed that there is an error in the system/config/install.php file - changing it forces ssl. It has:
`$_['site_ssl']          = HTTP_SERVER;`
I'm assuming this should be:
`$_['site_ssl']          = HTTPS_SERVER;`
