### ISSUE TITLE
Insert image in folder is not working on OpenCart 2.2.0.0

### ISSUE THREAD

**Issue by ducntq** [opencart/opencart#4162]
In Product Description box, I click on Picture button, then move to a folder, and select an image to insert into product description, but I got redirect to the image itself, instead of inserting an image into product description.

But if I choose a image in the root folder, everything works just fine.

I'm using OpenCart 2.2.0.0 on nginx, php-fpm 5.6. Also tested locally on Apache + php-fpm 5.6, and problem still happens.

**Comment by ducntq** [comment]
Seems like it was fixed in this commit: https://github.com/opencart/opencart/commit/d962e9100f19f918d1c02e43e6db8fb7e4e9142a but was not released just yet

**Comment by Rpent001** [comment]
I had the same problem.  Along with quite a few others.  It also happens when you are simply choosing an image for the product itself.

**Comment by bau720123** [comment]
thanks @ducntq 
solves by https://github.com/opencart/opencart/commit/d962e9100f19f918d1c02e43e6db8fb7e4e9142a

**Comment by gearza** [comment]
i'm download OC2.2.0.0 from opencart.com on 01aug16. 
it had the same problem. can insert picture in root image only. sub image can't.
it can solved by https://github.com/opencart/opencart/commit/d962e9100f19f918d1c02e43e6db8fb7e4e9142a
thanks.

**Comment by andreab79** [comment]
hi, i tested this
https://github.com/opencart/opencart/commit/d962e9100f19f918d1c02e43e6db8fb7e4e9142a
but not works for opencart 2.2.0.0.

the true is that for opencart 2.2.0.0 you have to apply this modify to is common_oncopy.js not to common_oncopy.js

**Comment by gearza** [comment]
thank you

2016-11-18 21:15 GMT+07:00 andreab79 <notifications@github.com>:
