### ISSUE TITLE
Paypal Payflow Error

### ISSUE THREAD

**Issue by ahuvainc** [opencart/opencart#4163]
The specific file located here needs to be corrected.
opencart/upload/admin/view/template/payment/pp_payflow.tpl 

On the storefront, it renders error when you click the submit button showing a user undefined variable and apparently even after fixing misspelling of 'user' in the code, the variable data is not being passed onto paypal for processing. Paypal tech stated it seems the "Test mode" does not turn off although I have it switched off in admin, hence throwing a credentials error. 

This is an out of box payment option that should work. Please fix.

**Comment by opencarteli** [comment]
Maybe try to update your opencart ver. since i found ur path is not match with latest ver.

**Comment by jamesallsup** [comment]
Booked in for review.

It is also using `return $this->forward('error/not_found');`

**Comment by davidteal** [comment]
Hi @ahuvainc 

Can you give more details on this please. Where is the misspelling of "user" in the code? Which file?

Can you also confirm that you are using PayPal Payflow Pro not PayPal Payflow Pro iFrame

I have fixed the undefined help_start_date and help_issue in the above commit.

Thanks.

**Comment by jamesallsup** [comment]
Unable to find an issue on the current branch (v3 dev).

If the issue happens again on the latest version please provide some more information on the issue with screen shots and error logs to help narrow down.
