### ISSUE TITLE
Catalog > Category > Edit > Parent

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#4165]
Hello.

Disallow set parent "Main Category".

How to reproduce:
1. Login in admin
2. Select "Catalog" > "Category"
3. Click exp. "Components" "Edit"
4. Click "Data" tab
5. Select "Parent" category exp. Components > Monitors > test 1
6. Save.

Results:
All categories exp. "Components" and subcategories exp. "Components > Monitors" disappear.

![category_1](https://cloud.githubusercontent.com/assets/11090866/14053227/073fc54e-f2d0-11e5-83ab-b20ff44ce99b.png)
![category_2](https://cloud.githubusercontent.com/assets/11090866/14053229/074066ca-f2d0-11e5-8d0f-8d8612fe0834.png)
![category_3](https://cloud.githubusercontent.com/assets/11090866/14053228/07400df6-f2d0-11e5-96ec-068f4be2c769.png)

**Comment by opencarteli** [comment]
If your parent category set into sub-category, the whole of the category and subcategories will be set under the subcategory which you have chose.
For the above example, you will find the "Components" and subcategories under the "test 1 > Components". But "Components > Monitors > test 1" would not have any change.

**Comment by faca5** [comment]
Hello.

Please check again above bug.

Categories disappear.

**Comment by danielkerr** [comment]
yes categories disappear from the front end but this is correct behavior. you can make them appear again by just removing the parent category. 

if your talking about sub category recursion that has been fixed in my last commit.
