### ISSUE TITLE
Wrong Success Message on Compare Page OC 2.2.0.0

### ISSUE THREAD

**Issue by quma** [opencart/opencart#4170]
go on the online demo to frontpage and add 2 separate products in the shopping cart.
than delete one of them by using the drop-down cart (header section).
than add a product to compare and go to compare page.

than you get the message: 
Success: You have modified your shopping cart! 

I think this message must displayed on the cart page and not on the compare page

**Comment by stockmaster** [comment]
Note: The demo is not 2.2 yet

**Comment by quma** [comment]
yes but I use 2.2.0.0 and this is the same bug

**Comment by danielkerr** [comment]
yep!
