### ISSUE TITLE
cart weight multiplies when add a product to cart

### ISSUE THREAD

**Issue by cyberformed** [opencart/opencart#4175]
cart weight multiplies when add a product to cart. how to resolve this issue? can somebody help me.

**Comment by cyberformed** [comment]
Weight calculation problem.

**Comment by cyberformed** [comment]
I have resolved this issue by simple removing product quantity from weight after lots of searching. Go to `system/library/cart.php` and looking for  `'weight' => ($product_query->row['weight'] + $option_weight) * $cart['quantity']`. after that replace with `'weight' => ($product_query->row['weight'] + $option_weight) `

**Comment by cyberformed** [comment]
fdvfdv

**Comment by Rpent001** [comment]
@cyberformed call me crazy, but wouldn't you WANT to multiply the weight by the quantities to get the whole cart weight?  If I put a 5 lb item in a cart and then put a second of the same item in the cart it doesn't still weight 5 lbs.  It weighs 10 lbs.

**Comment by cyberformed** [comment]
No according to my requirement, I find out a way.
