### ISSUE TITLE
Complete orders appear under missing order status

### ISSUE THREAD

**Issue by truescope** [opencart/opencart#4181]
I have a few completed orders but for some reasons they all appear under Missing Orders status. But when click to edit the order, i am getting error undefined and unable to edit.

Please help!

**Comment by danielkerr** [comment]
first you dont change order statuses using edit order!!! always use the order history one!

**Comment by danielkerr** [comment]
resave which ever payment gateway settign you are using

as you have deleted the order status that was assigned to that payment gateway
