### ISSUE TITLE
Redirect 403 to 404 error

### ISSUE THREAD

**Issue by deepentim** [opencart/opencart#4194]
How can I return 'The page you requested cannot be found!' when visitor goes to my backend folders like /catalog, /system.
How to redirect user to default Page Not Found page instead of 403 error?

**Comment by Rpent001** [comment]
I would start by looking at the various .htaccess files in the directories.  Just make sure you know what you're changing before you make any adjustments or you could compromise the security of your site.

A 404 Forbidden error is better than a 404 Not Found though.  Why do you want to change that?

**Comment by deepentim** [comment]
I would like to just return graphical error interface instead default server error. I like to transform

![selection_013](https://cloud.githubusercontent.com/assets/14071397/14230559/4c3d0a72-f97d-11e5-9eaa-bf07f230b5e1.jpg)
 to
![selection_014](https://cloud.githubusercontent.com/assets/14071397/14230560/6ac182d4-f97d-11e5-9167-1b863d6b6489.jpg)

**Comment by Rpent001** [comment]
You would need to use the .htaccess file to redirect each error to the specific page that you want.

**Comment by deepentim** [comment]
Yes, I know what to do. But I am stuck how to do.

**Comment by jamesallsup** [comment]
@deepentim This is not where you get support for issues or ask questions. Read the README!

Post on the forum http://forum.opencart.com/
