### ISSUE TITLE
Problem with cardinity

### ISSUE THREAD

**Issue by fido-x** [opencart/opencart#4196]
Insecure link at line 17 in admin/controller/payment/cardinity.php
$this->response->redirect($this->url->link('extension/payment', 'token=' . $this->session->data['token']));

This should be:
$this->response->redirect($this->url->link('extension/payment', 'token=' . $this->session->data['token'], true));

On further investigation, all links in this payment method (breadcrumbs, action and cancel) are insecure.

**Comment by danielkerr** [comment]
wow ur pretty focused to check all this

**Comment by danielkerr** [comment]
already fixed, some one did a commit without linking to this issue.
