### ISSUE TITLE
Menu Controller admin

### ISSUE THREAD

**Issue by jenyaukraine** [opencart/opencart#4200]
https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/menu.php

Please fix this omg. and its really need for unprivate $this->user->permission['access']

ill try, but dont find optimal way to pack data.

**Comment by jenyaukraine** [comment]
for menu build we can use pattern data array

**Comment by jenyaukraine** [comment]
`<?php
class ControllerCommonMenu extends Controller {
	private $menu = array(
		'catalog' => array(
									'sort'=>'0',
									'icon'=>'fa-tags',
									'name'=> '',
									'menus'=> array(
																'category',
																'product',
																// parse name & url if no array
																'attribute' => array(
																								'attribute',
																								'attribute_group'
																							)
																)

									)

	);

/*
Array ( [0] => Array ( [category] => Array ( [name] => 1 [url] => 1 ) )
				[1] => Array ( [product] => Array ( [name] => 1 [url] => 1 ) )
[attribute] => Array ( [attribute] => Array ( [name] => 1 [url] => 1 )
												[attribute_group] => Array ( [name] => 1 [url] => 1 ) ) )
*/
	private $menus = array();

	protected function menus($pattern, $cas = '',$main = '') {
		foreach ($pattern as $case => $children)
		{
			if(is_array($children))
			{
				$this->menus($children, $case, $main);
			}
			else
			{
				/*
				category->
				product->
				attribute->attribute
				attribute->attribute_group
				*/
				if($cas != '')
				{
					$this->menus[$cas][$children]['name'] = $this->language->get('text_'.$children);
					$this->menus[$cas][$children]['url'] = $this->url->link($main.'/'.$children, 'token=' . $this->session->data['token'], 'SSL');
					//print_r($cas."->".$children."<br>");
				}
				else
				{
					$this->menus[$children]['name'] = $this->language->get('text_'.$children);
					$this->menus[$children]['url'] = $this->url->link($main.'/'.$children, 'token=' . $this->session->data['token'], 'SSL');
					//print_r($cas."->".$children."<br>");
				}
			}
		}
	}

	protected function build_menu() {
		//load language
		$this->load->language('common/menu');
		// Get all main root
		foreach ($this->menu as $menu => $pattern)
		{
			//$menu - catalog
			// Send main var menu for url;
			$this->menus($pattern['menus'], null, $menu);

			//Forse set category name^^
			$this->menu[$menu]['name'] = $this->language->get('text_'.$menu);

			//relocate
			$this->menu[$menu]['menus'] = $this->menus;
		}
	}

	public function index()
	{
 		$this->build_menu();
/*
		$data['text_octeam_toolset'] = $this->language->get('text_octeam_toolset');
		$data['analytics'] = $this->url->link('extension/analytics', 'token=' . $this->session->data['token'], 'SSL');
		$data['access'] = isset($this->user->permission['access'])?:"";
		$data['openbay_markets'] = array(
			'ebay' => $this->config->get('ebay_status'),
			'amazon' => $this->config->get('openbay_amazon_status'),
			'amazonus' => $this->config->get('openbay_amazonus_status'),
			'etsy' => $this->config->get('etsy_status'),
		);
*/
			$menu = $this->menu;

		return $this->load->view('common/menu.tpl', compact('menu'));
	}
}
`

`<ul id="menu">
<?php
function singer($arr)
{
  $res = '';
  foreach($arr as $parentName => $menu)
  {
    if(!isset($menu['name']))
    {
      $res .= '<li><a class="parent">'.$menu[$parentName]['name'].'</a><ul>';
      $res .= singer($menu);
      $res .= "</ul></li>";
    }
    else
    {
      $res .= '<li><a href="'.$menu['url'].'">'.$menu['name'].'</a></li>';
    }
  }
  return $res;
}
// Extract category: [sort], [icon], [name], [menus]
foreach($menu as $me)
{
?>
<li id="catalog"><a class="parent"><i class="fa <?php echo $me['icon']; ?> fa-fw"></i> <span><?php echo $me['name']; ?></span></a>
  <ul>
    <?php
      echo singer($me['menus']);
    ?>
  </ul>
</li>
<?php
}
?>
</ul>
`

**Comment by danielkerr** [comment]
yes this is planned!

**Comment by c0b41** [comment]
@danielkerr any status?

**Comment by danielkerr** [comment]
already done in the dev branch
