### ISSUE TITLE
squares coming up on site

### ISSUE THREAD

**Issue by jalasljr** [opencart/opencart#4204]
hi there i have uploaded the 2.2.0.0 and its giving me a error and showing squares please check image  and then please update me on what to do please thanks

![12935334_10207443393975490_2004077835_n](https://cloud.githubusercontent.com/assets/18267994/14256117/653d3818-fa8f-11e5-910c-1400df423b3b.jpg)

please email me jalasljr@yahoo.co.uk thanks

**Comment by trinkaljuneja** [comment]
font-awesome script not loaded properly, check forum for answer

this may help 
http://forum.opencart.com/viewtopic.php?t=143946&p=557707
https://forum.opencart.com/viewtopic.php?f=190&t=135810

**Comment by danielkerr** [comment]
normally ssl issue or the files are not on the same domain

**Comment by danielkerr** [comment]
like www and non www urls. pick one and force a redirect.

**Comment by jalasljr** [comment]
The ssl is not truned on and all files are on same domain name if not then the site would not work also the site works without www url

**Comment by jalasljr** [comment]
Why is this saying its been closed the problem has not been fixed

**Comment by OpenCartAddons** [comment]
@jalasljr This isn't an issue with OpenCart.  You need to force your site to load without www.  You do this using the .htaccess file.

Here's a tutorial on how to force both www and non-www.
http://www.inmotionhosting.com/support/website/htaccess/force-www-htaccess


Regards,
Joel.
