### ISSUE TITLE
OC 2.0.1.1 if special product price is ON, quantity product prices does not work.

### ISSUE THREAD

**Issue by supak111** [opencart/opencart#4205]
Hey I've noticed that anytime you have special product price set (example special price $100), and if I also set 5pcs price is $90each, and 10pcs price is $80each, the quantity price never works.  OC always uses the special price of $100 even if someone tries to buy 10pcs.

**Comment by Rpent001** [comment]
I proposed a fix to this a few weeks ago but it was shot down.  

https://github.com/opencart/opencart/pull/4105

**Comment by Rpent001** [comment]
Since the code is executed in sequence the variable for the price gets overwritten and doesn't take in to consideration that both pricing options might exist in a real world situation.

**Comment by supak111** [comment]
I found a vqmod to fix this but the vqmod isn't working, causing a unexpected T_DOUBLE_ARROW

`<modification>
	<id>Fix Discounts wtih Specials</id>
	<version>1.0</version>
	<vqmver>1.2.3</vqmver>
	<author>uksb</author>
	<file name="system/library/cart.php">
		<operation>
			<search position="replace" offset="2"><![CDATA[if ($product_special_query->num_rows) {]]></search>
			<add><![CDATA[if ($product_special_query->num_rows) {
					if($product_discount_query->num_rows&&$product_discount_query->row['price']<=$product_special_query->row['price']){
						$price = $product_discount_query->row['price'];
					}else{
						$price = $product_special_query->row['price'];
					}
				}]]></add>
		</operation>
	</file>

    <file name="catalog/controller/product/product.php">
		<operation>
			<search position="replace" offset="5"><![CDATA[foreach ($discounts as $discount) {]]></search>
			<add><![CDATA[foreach ($discounts as $discount) {
				if((float)$product_info['special']){
					if($product_info['special']>$discount['price']){
						$data['discounts'][] = array(
							'quantity' => $discount['quantity'],
							'price'    => $this->currency->format($this->tax->calculate($discount['price'], $product_info['tax_class_id'], $this->config->get('config_tax')))
						);
					}
				}else{
					$data['discounts'][] = array(
						'quantity' => $discount['quantity'],
						'price'    => $this->currency->format($this->tax->calculate($discount['price'], $product_info['tax_class_id'], $this->config->get('config_tax')))
					);
				        }
			}]]></add>
		</operation>
	</file>
</modification>`

**Comment by Rpent001** [comment]
It shouldn't require a mod.  It should be part of the package.  It's just the result of poor coding and tunnel vision.  Everything works fine in the OpenCart testing bubble though.

**Comment by supak111** [comment]
I understand but because there was a problem in coding, couldn't someone just fix the bug with a add on code like vqmod?

**Comment by danijelGombac** [comment]
Try this ocmod https://forum.opencart.com/viewtopic.php?f=161&t=35730&start=40

**Comment by Rpent001** [comment]
@supak111 of course, but why should you have to?  My pull request fixes the issue just fine but it was closed without a merge.

**Comment by supak111** [comment]
Correct me if I'm wrong, but were you not suggesting they fix this in the newer versions of OC?  I'm still on 2.0.1.1.  Not everyone likes upgrading to the newest as its a major PITA to get all your extension to work.

**Comment by Rpent001** [comment]
I could take a look at the code for your version, but I'd imagine the fix would be exactly the same.  I highly doubt 2.2.x is a complete code rewrite of 2.0.x.  That's what major revisions are for.

**Comment by supak111** [comment]
Got it working on OC 2.0.1.1 here is the .xml file

<?xml version="1.0" encoding="utf-8"?>
<modification>
    <name>Discounts wtih Specials</name>
    <version>1.0</version>
    <author>danijelGombac</author>
    <code>Discounts wtih Specials</code>
    <link>http://www.gombac.si</link>
    <file path="system/library/cart.php">
        <operation>
            <search><![CDATA[if ($product_discount_query->num_rows) {]]></search>
            <add position="replace"><![CDATA[if ($product_discount_query->num_rows && ($product_discount_query->row['price'] < $price)) {]]></add>
        </operation>
        <operation>
            <search><![CDATA[if ($product_special_query->num_rows) {]]></search>
            <add position="replace"><![CDATA[if ($product_special_query->num_rows && ($product_special_query->row['price'] < $price)) {]]></add>
        </operation>
    </file>  
</modification>
