### ISSUE TITLE
Issue when upload image with specific name.

### ISSUE THREAD

**Issue by hermans** [opencart/opencart#4207]
when i try to  upload image with name: AQUA-5-Dry-70g-mini.jpg, the cache image not work properly.
please see attached image for detail 
![screenshot from 2016-04-05 17 20 19](https://cloud.githubusercontent.com/assets/938767/14278664/0b74cae8-fb53-11e5-8828-05d05bbdb1f7.png)

i tried to fix in model/tool/image.php
$new_image = 'cache/' . utf8_substr($filename, 0, utf8_strrpos($filename, '.')) . '-' . $width . 'x' . $height . '.' . $extension;

change to be:

$new_image = 'cache/' . md5(basename($filename, "." . $extension)) . '-' . $width . 'x' . $height . '.' . $extension;

**Comment by danielkerr** [comment]
but then you lose the seo ranking because the image names are not related. dont use - in the file name maybe

**Comment by hermans** [comment]
yes, correct. do you have solution about missing image ? i tried in fresh installation and get same issue, this just in server not in localhost.
