### ISSUE TITLE
Can't insert picture on information description in version 2.2

### ISSUE THREAD

**Issue by cybersupport** [opencart/opencart#4209]
I need to create a paragraph with some picture illustrations on it, but instead selecting the picture I have uploaded earlier it opens the picture with a grey background when clicking on it instead inserting it in the description paragraph I'm trying to create with that image.  Please help!!!

**Comment by cybersupport** [comment]
My server PHP version is 5.6 and the OC version is 2.2

**Comment by danielkerr** [comment]
i can not replicate this.

**Comment by danielkerr** [comment]
browser?

in your browser click view source and look for the colnsol tab. look for any js errors. maybe you didnt upload all the files.

**Comment by qahar** [comment]
This is happen on OpenCart at v2.2.0.0 for images inside folders.
But this is fixed on latest master branch
