### ISSUE TITLE
Analytics not working for multistore in OC 2.2

### ISSUE THREAD

**Issue by xseon** [opencart/opencart#4211]
In Extensions > Analytics when there are several stores, no matter which one you choose to edit, the same settings are saved for all of them.

**Comment by danielkerr** [comment]
did u iuninstall before the upgrade?

**Comment by xseon** [comment]
It was a clean 2.2 install. The error message is:
PHP Notice:  Undefined index: store_id in admin/controller/analytics/google_analytics.php on line 13

**Comment by xseon** [comment]
Here is a fix I got to work:

`		$data['breadcrumbs'][] = array(
			'text' => $this->language->get('heading_title'),
			'href' => $this->url->link('analytics/google_analytics', 'token=' . $this->session->data['token']** . '&store_id=' . $this->request->get['store_id']**, true)
		);

		$data['action'] = $this->url->link('analytics/google_analytics', 'token=' . $this->session->data['token']** . '&store_id=' . $this->request->get['store_id']**, true);

		$data['cancel'] = $this->url->link('extension/analytics', 'token=' . $this->session->data['token'], true);
		
		$data['token'] = $this->session->data['token'];
		
		**if (isset($this->request->get['store_id']) && ($this->request->server['REQUEST_METHOD'] != 'POST')) {
			$setting_info = $this->model_setting_setting->getSetting('google_analytics', $this->request->get['store_id']);**
		}`

**Comment by danielkerr** [comment]
the code has already been fixed. i can not replicate your issue. i did find though that the analitcs status was not setup correctly when viewed from the list page.

**Comment by danielkerr** [comment]
anyway included a fix
