### ISSUE TITLE
https image resize bug default store

### ISSUE THREAD

**Issue by nuke123** [opencart/opencart#4214]
config.php set HTTPS_SERVER
catalog.php has site_ssl = true
store settings in database ssl set true 

But `$this->config->get('config_ssl')` is always NULL.

Probem is for image resize if request HTTPS this code doesn't work correctly
```php
if ($this->request->server['HTTPS']) {
	return $this->config->get('config_ssl') . 'image/' . $new_image;
} else {
	return $this->config->get('config_url') . 'image/' . $new_image;
}
```

**Comment by danielkerr** [comment]
i think already fixed in master branch

**Comment by robinflyhigh** [comment]
Can someone help me find the fix? I am not able to trace it in GIT history.

**Comment by robinflyhigh** [comment]
I found the commit which fix this issue

URL: https://github.com/opencart/opencart/commit/057f12e63aba20e3259234db322ad128afc9b91c
