### ISSUE TITLE
Bug in Currency List

### ISSUE THREAD

**Issue by pro2847** [opencart/opencart#4216]
it says is
![2016-04-07 19 26 18](https://cloud.githubusercontent.com/assets/3256096/14350989/e0a3e8b2-fcf6-11e5-9038-58fe1445ff91.png)

Change ZMK for 1.0, and USD not 1.0. but ultimately ZMK is not Default. (first bug)
![2016-04-07 19 26 05](https://cloud.githubusercontent.com/assets/3256096/14350977/d3d040a4-fcf6-11e5-8383-ed6b6459eb46.png)

Updating curencies
![2016-04-07 19 26 24](https://cloud.githubusercontent.com/assets/3256096/14350987/e09dbe10-fcf6-11e5-8114-f5087a834a65.png)

All discharges. And again, the dollar is 1.0 and default (second bug)
![2016-04-07 19 26 30](https://cloud.githubusercontent.com/assets/3256096/14350988/e0a1a7b4-fcf6-11e5-8264-d478cbbeb486.png)

**Comment by pro2847** [comment]
And.

Change code for USD to NON (example).

**Comment by pro2847** [comment]
jamesallsup why have you closed issue?

**Comment by OpenCartAddons** [comment]
@pro2847 You need to set your default currency under:

Admin CP > System > Settings > YourStore [edit] > Local > Currency

Restore your US Dollar currency code back to USD, and go back into your currency settings and change your new default currency to a value of 1.


Regards,
Joel.

**Comment by pro2847** [comment]
Thanks, that helped. It was not an obvious way.
