### ISSUE TITLE
account activation email language issue

### ISSUE THREAD

**Issue by derekvotresite** [opencart/opencart#4217]
when setting opencart to allow only approved users to login the system sends two emails, the first being the account registration confirmation email and the second being the account approval email after the webmester approves it. The issue is with the account approval email because it sends the email in the language of the backend and **not in the users language. **

**Comment by opencarteli** [comment]
You can find the language in
`admin->language->en-gb->mail->customer.php`
make sure your files is it exist

**Comment by nuke123** [comment]
You have to edit opencart and add language_id to customer table.
