### ISSUE TITLE
OpenCart json_decode function Remote PHP Code Execution

### ISSUE THREAD

**Issue by n4s3r** [opencart/opencart#4220]
Removed comment for breach of our guidelines. - James

**Comment by kanenas** [comment]
@n4s3r, shouldn't you PM an OpenCart moderator/administrator on the forum before disclosing security issues?

> If you would like to report a serious security bug please PM an OpenCart moderator/administrator on the forum. Please do not report concept/ideas/unproven security flaws - all security reports are taken seriously but you must include the EXACT details steps to reproduce it. Please DO NOT post security flaws in a public location.

**Comment by jamesallsup** [comment]
Thank you for your effort of finding this bug, but considering you posted it without concern for others on a public place it shows that you didn't read our very clear instructions.

Your report has been copied to our internal tracker and will be investigated so do not re-post it.
