### ISSUE TITLE
Common section

### ISSUE THREAD

**Issue by dimon4ik062** [opencart/opencart#4222]
I want to load some admin models from catalog section for my module.
I can make patch for opencart core and create opportunity like this:
`$this->load->model($modelName = 'someModel', $section = 'ADMIN');`
But this path is not good for true Knight of Jedi, and bad solution for module :)

Maybee u want to think about the common section? When we call $this->load we can firstly try to load model/controller/language/view from current section(admin or catalog), then if not finded this on current section we will try to load from common section.

**Comment by danielkerr** [comment]
admin and catalog should be separate. also i dont like non application specific classes to know if there is a catalog or admin

**Comment by dimon4ik062** [comment]
Edit order function was excluded from admin section. I think its bad move, when edit function doesnt exsists on admin section. What pattern are u using for opencart?
