### ISSUE TITLE
confirm order 500 internal server error 

### ISSUE THREAD

**Issue by cyberformed** [opencart/opencart#4230]
confirm order button submit throws 500 internal server error

PHP Fatal error:  Call to a member function getOrder() on null in /catalog/model/openbay/ebay_order.php on line 587

**Comment by jamesallsup** [comment]
You have possibly removed the Openbay loader in the index.php

This isn't related to OpenCart though, create a ticket at http://help.welfordmedia.co.uk for support with this issue.

**Comment by cyberformed** [comment]
Thanks, James. You saved my day.
