### ISSUE TITLE
Opencart Order edit from admin shows product in cart in front end.

### ISSUE THREAD

**Issue by sureshmg23** [opencart/opencart#4233]
Facing a weird issue, Opencart 2.1.0.1 (fresh setup),when i try to edit order from admin after clicking the continue button from first step, makes the product in customer cart in front end. How to resolve this issue? If its not an issue, why it works so?

**Comment by Rpent001** [comment]
Functionality like this has its advantages from a Customer Service perspective.  Say someone calls in, or is on a chat, looking for an item but may not purchase right away.  At lest you can add it to their cart for a checkout at a later time.  I wouldn't consider it a bug at all.  If the order goes through right away then the item should only be in their cart briefly.

**Comment by sureshmg23** [comment]
Thanks for the reply. But, What if the customer has already made the purchase? and if they want to edit the phone number alone of that order? Customers are calling me, and asking me to stop this, what should i do to stop this activity to the customer cart?

**Comment by nklatt** [comment]
You can comment out line 19 of system/library/cart/cart.php, preferably using ocmod or vqmod so your fix doesn't get lost when you update OC.

https://github.com/opencart/opencart/blob/master/upload/system/library/cart/cart.php

The downside is carts do not persist across sessions / browsers. A more robust fix might be to add a column to the cart table that flags whether the row is catalog (front-end) or admin, and only update the front-end rows.
