### ISSUE TITLE
Export/Import problem

### ISSUE THREAD

**Issue by Orlangyr** [opencart/opencart#4240]
i have taken so big damage of thisfight so many people which wroks in hosting companies but the issue is that after ia import/export default product and categoies, categories become invisble http://prntscr.com/aruql1 , i just install fesh 2.2. and export/import tool , help me please

**Comment by danielkerr** [comment]
thyis is not the place for support. use the forum. or hire one of the partners.

**Comment by Orlangyr** [comment]
where is the place for support , can you link ?  also why nobody knows how to resolve this ?

**Comment by iMateo** [comment]
http://opencart.com
