### ISSUE TITLE
OC2.2.0.0 account/account Address Book error

### ISSUE THREAD

**Issue by leomb** [opencart/opencart#4251]
In the sidebar list on the Account page all links work except the one for Address Book. The error log on my server has the following error description:
PHP Parse error:  syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /home/color4/public_html/red/catalog/controller/account/address.php on line 522

This is where the custom fields are being validated.
What could be the error and how can it be fixed?

**Comment by danielkerr** [comment]
i think this is already fixed on the master branch
