### ISSUE TITLE
When update from old version to new version in OpenCart with old database error occurs. 

### ISSUE THREAD

**Issue by mfozdarprojects** [opencart/opencart#4257]
When update from old version to new version in OpenCart with old database error occurs. 

I backup all htdocs folders and old database, still error occurs. 

With update new version with old database OpenCart must display proper old data. 

Error occurs in front end 

After login errors occurs when update from old version to new version in OpenCart with old database error occurs. 

How to solved problem please guide me.

**Comment by danielkerr** [comment]
i should guess the errors messages!!!!

read the upgrade instructions.
