### ISSUE TITLE
Page isnt working HTTP ERROR 500

### ISSUE THREAD

**Issue by systeminflow** [opencart/opencart#4259]
I cleaned installed OC2.2.0.0

Everything seems fine but when I click on Customer in the admin panel under Customer - **Page isnt working** comes up with the error http error 500.

Please help

Deepak

**Comment by danielkerr** [comment]
reupload

**Comment by systeminflow** [comment]
which files? I reuploaded customer.php but same issue

**Comment by pekka2** [comment]
**@systeminflow **

You download fixed file:
https://github.com/opencart/opencart/blob/master/upload/admin/controller/customer/customer.php

**Comment by systeminflow** [comment]
thank you.

Problem fixed.

but in customer area, the address link is giving same error.

Please  let know the fix?

Deepak

--------------------------------------------
On Thu, 4/21/16, Pekka Mansikka <notifications@github.com> wrote:

 Subject: Re: [opencart/opencart] Page isnt working HTTP ERROR 500 (#4259)
 To: "opencart/opencart" <opencart@noreply.github.com>
 Cc: "systeminflow" <systeminflow@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Thursday, April 21, 2016, 8:34 PM
 
 *@systeminflow
 *
 
 You download fixed file:
 
 https://github.com/opencart/opencart/blob/master/upload/admin/controller/customer/customer.php
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly or view
 it on GitHub

**Comment by pekka2** [comment]
Your need update also file catalog/controller/account/address.php
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/account/address.php
