### ISSUE TITLE
customer page in Admin not opening. Error 500

### ISSUE THREAD

**Issue by systeminflow** [opencart/opencart#4261]
I made cleaned installation of OC2.2.0.0 and also done Reupload of all files of OC2.2.0.0

Everything seems fine but when I click on Customer in the admin panel under Customer - Page isnt working comes up with the error http error 500.

I reuploaded again but the problem remains.

Please help

Deepak

**Comment by mhcwebdesign** [comment]
This is not a bug report, please post on the OpenCart forum.
