### ISSUE TITLE
Admin > Edit Orders always show Internal Server Error popup

### ISSUE THREAD

**Issue by amarin-boonkirt** [opencart/opencart#4265]
I 'v verify in error_log and found issue

[Tue Apr 19 00:48:59 2016] [error] [client ....] PHP Parse error:  syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /home/....../public_html/admin/controller/customer/customer.php on line 1105, referer: http://...../admin/index.php?

And I 've fixed by patched code in admin/controller/customer/customer.php: 1105

BY Change

} elseif (($custom_field['type'] == 'text' && !**empty($custom_field['validation']** && $custom_field['location'] == 'address')**)** && !filter_var($value['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {

TO THIS CODE

} elseif (($custom_field['type'] == 'text' && !empty($custom_field['validation']) && $custom_field['location'] == 'address') && !filter_var($value['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {

FYI

**Comment by pekka2** [comment]
**@amarin-boonkirt**
https://github.com/opencart/opencart/blob/master/upload/admin/controller/customer/customer.php
