### ISSUE TITLE
Warning: mysqli::mysqli(): (HY000/1203): User ppp already has more than 'max_user_connections' active connections in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/system/library/db/mysqli.php on line 7 Notice: Error: Could not make a database link (1203) User ppp already has more than 'max_user_connections' active connections in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/system/library/db/mysqli.php on line 10 Warning: mysqli::close(): Couldn't fetch mysqli in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/system/library/db/mysqli.php on line 58

### ISSUE THREAD

**Issue by shabirbhat** [opencart/opencart#4271]
Warning: mysqli::mysqli(): (HY000/1203): User ppp already has more than 'max_user_connections' active connections in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/system/library/db/mysqli.php on line 7 Notice: Error: Could not make a database link (1203) User ppp already has more than 'max_user_connections' active connections in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/system/library/db/mysqli.php on line 10 Warning: mysqli::close(): Couldn't fetch mysqli in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/system/library/db/mysqli.php on line 58

Hi every one, I am facing the problem with opencart when ever i clicked on view order on dashboard on latest order  site getting slow at the end it through the error as i have mentioned above please help

**Comment by shabirbhat** [comment]
i am using the version 2.0.3.1 I have also contact host ipage they said this is problem with my store as server connection limit is only 10...
i have also noticed this problem occurs when i click on view order on dashboard in the section of latest orders

**Comment by pine3ree** [comment]
Hello @shabirbhat ,
if you are in a shared hosting server ask you admin to allow more db connections to your server account.
Opencart shut down connections when the script has done running. maybe your service provider is keeping persistent connections so you run out of allowed slots very in a very few requests

**Comment by pine3ree** [comment]
opencart does not open new connections, it always uses the connection opened when the script started.
is it a busy website? some bad guy is DOS probing your site?

**Comment by shabirbhat** [comment]
I have asked them to allow more connections but they denied ....but i am confuse as rest of the site is working fine whenever i do click on latest order or view order only then it comes..I think this is something related to script what you suggest..

**Comment by pine3ree** [comment]
which OC version?

**Comment by shabirbhat** [comment]
this is not so busy website....its in admin site problem...front is okay but when this problem happens on front its also effecting 

i am using 2.0.3.1

**Comment by pine3ree** [comment]
any extension involving admin/order/info area?

**Comment by shabirbhat** [comment]
not at all there is no extension related to orders

**Comment by pine3ree** [comment]
mm strange i just checked the template order_info.tpl for ajax calls.
ajax calls will trigger requests on the server (1 request === 1 db connection), but i only see 1 request called with rendering `$('#history').load(...)`. All other ajax `$.ajax({})` `load(...)`  requests appear to be triggered on events such as adding history entries....

**Comment by shabirbhat** [comment]
so what i should do now....my site is down now

**Comment by pine3ree** [comment]
can you access your apache-webserver logs to see if some search-engine/spider/bot is making many requests to your site. I had  problems in the past (not with connections I have 30 db connections allowed, but with site slowness)

**Comment by shabirbhat** [comment]
where i need to check this

**Comment by pine3ree** [comment]
It depends on the hosting provider. some have dedicated panels to search inside access logs. maybe your panel also show you active visitors. anyway 10 db active connections can be risky when the site gets busy.

**Comment by shabirbhat** [comment]
i have ipage and there is nothing like server logs

**Comment by shabirbhat** [comment]
https://perfectsigns.ipage.com/stats/

**Comment by shabirbhat** [comment]
i have more than 4 websites running there rest of the sites are working fine

**Comment by pine3ree** [comment]
in the same account???

**Comment by shabirbhat** [comment]
yes

**Comment by pine3ree** [comment]
so all the websites are sharing max 10 active db connections? or is it 10 per website?

**Comment by shabirbhat** [comment]
i dont know that

**Comment by shabirbhat** [comment]
but my friend was having the same problem with this opencart on ipage he was having only one website then he moved to vps server

**Comment by pine3ree** [comment]
if you run your VPS you won't have db connection limits, so your problem will probably go away.
I've gone through the db adapters of your opencart version and they all close the db connection, so my opinion is that you have many concurrent requests that make you reach the limit. Most of the times bad spiders (or very busy website or even seo-scanning-tools) are responsible for these kind of issues. Some times if the script terminate badly (with errors) connection are left open and their number can add up. Anyway I believe you need an hosting account with more resources....and keep just 1 website per account if the limits imposed by the hosting company are meant to be per-account.

kind regards

**Comment by shabirbhat** [comment]
i received this error before

Warning: mysqli::set_charset(): Error executing query in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/system/library/db/mysqli.php on line 14 Notice: Error: User 'ps' has exceeded the 'max_questions' resource (current value: 300000)
Error No: 1226
SELECT * FROM oc_store WHERE REPLACE(`url`, 'www.', '') = 'http://perfectsigns.co.uk/' in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/system/library/db/mysqli.php on line 41 Notice: Trying to get property of non-object in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/index.php on line 41 Notice: Error: User 'ps' has exceeded the 'max_questions' resource (current value: 300000)
Error No: 1226
SELECT * FROM `oc_setting` WHERE store_id = '0' OR store_id = '0' ORDER BY store_id ASC in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/system/library/db/mysqli.php on line 41 Notice: Trying to get property of non-object in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/index.php on line 50 Warning: Invalid argument supplied for foreach() in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/index.php on line 50 Notice: Trying to get property of non-object in /hermes/bosweb25b/b957/ipg.perfectsigns/ps/index.php on line 58 Warning: fope

**Comment by pine3ree** [comment]
It is still an hosting provder limit setting on mysql server:

max_questions = max number of database queries per hour

you definitely need a bigger hosting account or vps, it is not a problem related to opencart code.
1 opencart request can trigger 20-100 or in some cases (long product lists) more database queries
considering 100 you have 3000 allowed requests per hour. but some pages can trigger more requests....
so let's say you can have in a worst case scenarion 1000 requests per hour, including admin requests, search engine, spiders, etc etc....

a website, and especially an ecommerce website, can run out of resources very quickly

BTW you should disable error output in the website, you are giving away information to hackers, you can still user error_log to examine errors.

**Comment by pine3ree** [comment]
I also think that the repo owner will close this issue at once when he sees it since is not related to coding bugs :-)

**Comment by shabirbhat** [comment]
Thank you so much :)

**Comment by pine3ree** [comment]
@shabirbhat you are welcome! I believe you should close the issue... :-)
