### ISSUE TITLE
Please fix or revert changes by pull request "Correct wrong variable index #3503"!

### ISSUE THREAD

**Issue by AlexanderKovalchuk** [opencart/opencart#4273]
In my project all .png images type idenfified via getimagesize() as "3" but the constant IMG_PNG contains "4", and to the front puts value with DIR_IMAGE instead $this->config->get('config_ssl') . 'image/;

Commit: https://github.com/opencart/opencart/commit/038646f38569e51008c65d4284d308a5333d3b39

_upload/catalog/model/tool/image.php:_

```
list($width_orig, $height_orig, $image_type) = getimagesize(DIR_IMAGE . $old_image);

if (!in_array($image_type, array(IMG_PNG, IMG_JPEG, IMG_GIF))) { 
    return DIR_IMAGE . $old_image;
}
```

My PHP version is 5.5.

Please check this.

**Comment by pine3ree** [comment]
i found the bug i'm opening a PR
