### ISSUE TITLE
js issue , inserting images from subfolder in summernote editor

### ISSUE THREAD

**Issue by nasserman** [opencart/opencart#4283]
I think this is a bug in inserting images using summernote (default editor) for opencart version 2.2.0,
i checked demo version (2.0.0.1b) currently installed on demo.opencart.com, but there is no such issue, but in version 2.2.0.0 if i want to inserting image from subfolder into the editor, it redirect me to that image (open it in browser) instead of inserting image into editor, if i select an image from root, it works but if i want to select image from subdirectory or navigate into subolder and return up to the root, clicking on image cause to navigate to that image (javascript event not fired or not attached to the images)

install version 2.2.0.0 and got to product edit page ad try to insert image from subfolder to the editor, you will see this issue.

**Comment by danielkerr** [comment]
have u tried the master branch. im sure this has been fixed.

**Comment by 2valenki** [comment]
just had to download the newest admin common.js file to fix this!

**Comment by nasserman** [comment]
there is no such thing in 2.2.0.1b version (latest version of master branch),  i replaced common.js with newer version, but this time summernote did not loaded ( after page load, there is just a normal textarea instead of summernote editor)

**Comment by nasserman** [comment]
i replaced some older files with newest copies (tagged 2.2.0.b1 master) and it seems issue has gone! 
i think this bug solved in **2a6d6e4ea5d27b08d2a84ee57018cf42a5742b8e** commit, in files that changed in this commit (this files using summernote editor).

i think the problem is solved, i you think same, close this issue,

sorry for may bad English!

**Comment by guidone65** [comment]
Hi @nasserman i'm going crazy with your same issue, i'm on Opencart 2.2 and the problem for me is still there, can you tell me exactly how to fix it? Thanx in advance
