### ISSUE TITLE
Paypal upgrading their website system

### ISSUE THREAD

**Issue by melvin16** [opencart/opencart#4284]
Hello Github & all of Opencart programers,

I recently saw my email and Paypal website that they will upgrading their software/programs that could be affecting opencart program in Paypal payment method. 
Their information is so highly technical that I can't understand at this link below

https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1913&viewlocale=en_US

I hope this information may benefit to all users of Opencart.

Best regards,
Melvin

**Comment by danielkerr** [comment]
Yes i got it aswell
