### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by badsyntaxx** [opencart/opencart#4285]
It would be nice if the changelog link from the opencart site that points here actually pointed to a changelog instead of a page with more opencart dl links. So I downloaded ver 2.2.0.0 and viewed the changelog in the zip and there are no changes under ver2.2.0.0. Did opencart just release the same version again for the heck of it with a new ver number? Why is opencart now 2.2.0.0 if nothing has changed since 2.1.0.1?

**Comment by danielkerr** [comment]
i think there was one in the readme.
