### ISSUE TITLE
Create new order from admin panel always show the last created order products list

### ISSUE THREAD

**Issue by AmrAbdelrahman** [opencart/opencart#4286]
Opencart 2.2
I'm using the admin order form to create new order, if i created order with some products and submitted it, then tried to create another new order i see that the products list of the last order appeared and added to the new order, i have to remove them manually before start adding the new order prodects.. this is so annoying issue, ANY HELP

**Comment by AmrAbdelrahman** [comment]
any help please

**Comment by yuriygr** [comment]
It started with 2.1.0.2, and as I know, the developers do not like to bring it up.
