### ISSUE TITLE
display product weight on return section

### ISSUE THREAD

**Issue by cyberformed** [opencart/opencart#4289]
I want to display product weight on return section, I have changed the code, but nothing works.

**Comment by cyberformed** [comment]
I have changed the return model file, but nothing changes in query. what's the problem. someone find out.

**Comment by opencarteli** [comment]
you should add 1 more field called "weight" in order_info page, controller, model and langauage

**Comment by cyberformed** [comment]
I have already added the weight filed in order_info function in controller , model and language, but nothing works as well as I have added weight field in return table.

**Comment by danielkerr** [comment]
heres not the correct place to ask. use the forum
