### ISSUE TITLE
To file design/translation.php

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#4290]
To file admin/controller/design/translation.php

about after line 112:

```
$data['button_add'] = $this->language->get('button_add');
$data['button_delete'] = $this->language->get('button_delete');
```

**Comment by opencarteli** [comment]
I cannot find this path admin/controller/design/translation.php in 2.2.0.0 ver

**Comment by danielkerr** [comment]
This feautre is still being worked on and due to time constraint will not be in the next version.
