### ISSUE TITLE
Google reCaptcha - Need Reset During Checkout Registration on Field Errors

### ISSUE THREAD

**Issue by codesticle** [opencart/opencart#4293]
Scenario: Google reCaptcha is enabled for registration, and a user chooses to register for an account during checkout. 

User enters their account information into the fields in step 2 and checks the Google reCaptcha checkbox (I'm not a robot). 

They click continue and there is a validation error on one of the fields (a non-matching password or too short of a last name, for example).

The user fixes the issue in the applicable field(s) and clicks continue again. Now they get a validation error from the Google reCaptcha field as it needs to be revalidated, but this is impossible since you cannot re-check the box.

Possible solution: use grecaptcha.reset(); to reset the captcha field to allow re-checking.

**Comment by myblankspaces** [comment]
I would love to see this error get fixed. it has had this or similar errors for at least the last two versions.
![opencart errir](https://cloud.githubusercontent.com/assets/19110078/14944445/de27e67e-0fa7-11e6-901e-175c0f1c03b4.jpg)

**Comment by opencarteli** [comment]
Please make sure your country is it available to use google function
