### ISSUE TITLE
Disabled products disappear while editing orders

### ISSUE THREAD

**Issue by woodfashion** [opencart/opencart#4294]
I have a website selling clothing and always disable some products regularly due to fast turnover.
I just found a problem that...
if I edit an order which includes a disabled product, even I do not edit the product list,
the disabled product will automatically disappear without any alert!
This issue also happens in a new, clean Opencart without any extension.

![opencart_disable](https://cloud.githubusercontent.com/assets/18673861/14809113/7455d582-0bbd-11e6-8fe8-f2d879dcb59c.jpg)
![opencart_enable](https://cloud.githubusercontent.com/assets/18673861/14809114/7455fbf2-0bbd-11e6-8c3c-11fd07a4fe09.jpg)

**Comment by danielkerr** [comment]
then enable them duhhhh!~

**Comment by woodfashion** [comment]
That's non-sense!
What if my customers buy the items when I enable them temporarily?
Then I have to tell them that those are disabled items actually?
And do I have to enable the items one by one just because I have to edit order details?
What I mean is, the ordered items should not be affected by their status after ordering.
I don't know if you have tried other shopping cart system but this situation is really disturbing
And your answer disappoint me. :(

**Comment by rmullaney77** [comment]
Agree with **woodfashion**. Product status should not affect what admins can do when manually editing/creating orders.

WF: Get used to those types of responses fro OC :/

**Comment by zemguru** [comment]
Agree with @woodfashion @rmullaney77 - it's not acceptable.
When you edit an order, you can't now, that products are disabled
1) You could at least add some visual notification, that you are editing order with disabled products
2) or add alert, if there are disabled products, which will be "deleted" from an order.
3) or - just allow to *edit* ready orders from admin, event they contains disabled products.

![image](https://user-images.githubusercontent.com/30476178/31413144-9a5799c6-ae20-11e7-8f50-34648dbb55e5.png)

**Comment by rmullaney77** [comment]
That's not a bad idea.

Even better: Make it an ajax toggle so you can enable/disable while on that page ... though I doubt this idea would ever make it to a commit :P

**Comment by danijelGombac** [comment]
You can try replace this in upload/system/library/cart/cart.php

line 41

`$product_query = $this->db->query("SELECT * FROM " . DB_PREFIX . "product_to_store p2s LEFT JOIN " . DB_PREFIX . "product p ON (p2s.product_id = p.product_id) LEFT JOIN " . DB_PREFIX . "product_description pd ON (p.product_id = pd.product_id) WHERE p2s.store_id = '" . (int)$this->config->get('config_store_id') . "' AND p2s.product_id = '" . (int)$cart['product_id'] . "' AND pd.language_id = '" . (int)$this->config->get('config_language_id') . "' AND p.date_available <= NOW() AND p.status = '1'");`

with

```
if ($cart['api_id']) {
    $product_query = $this->db->query("SELECT * FROM " . DB_PREFIX . "product_to_store p2s LEFT JOIN " . DB_PREFIX . "product p ON (p2s.product_id = p.product_id) LEFT JOIN " . DB_PREFIX . "product_description pd ON (p.product_id = pd.product_id) WHERE p2s.store_id = '" . (int)$this->config->get('config_store_id') . "' AND p2s.product_id = '" . (int)$cart['product_id'] . "' AND pd.language_id = '" . (int)$this->config->get('config_language_id') . "'");
} else {
    $product_query = $this->db->query("SELECT * FROM " . DB_PREFIX . "product_to_store p2s LEFT JOIN " . DB_PREFIX . "product p ON (p2s.product_id = p.product_id) LEFT JOIN " . DB_PREFIX . "product_description pd ON (p.product_id = pd.product_id) WHERE p2s.store_id = '" . (int)$this->config->get('config_store_id') . "' AND p2s.product_id = '" . (int)$cart['product_id'] . "' AND pd.language_id = '" . (int)$this->config->get('config_language_id') . "' AND p.date_available <= NOW() AND p.status = '1'");
}
```

**Comment by rmullaney77** [comment]
@danijelGombac Avoid notices `isset($cart['api_id'])` or `!empty($cart['api_id'])`
