### ISSUE TITLE
New Theme not detected

### ISSUE THREAD

**Issue by ajprok** [opencart/opencart#4296]
I'm using Opencart 2.2. I duplicated the default theme folder in catalog, and renamed it in the same folder. However, in the backend, I do not see the new theme in the Store settings. Only the defalut theme store shows.
![backendthemeselection](https://cloud.githubusercontent.com/assets/18692797/14841543/5bab5724-0c5c-11e6-9d27-2553e71c11bc.png)
![themefolder](https://cloud.githubusercontent.com/assets/18692797/14841542/5ba5a414-0c5c-11e6-9086-83ca76273fba.png)

**Comment by trinkaljuneja** [comment]
![screen shot 2016-04-27 at 11 46 58 am](https://cloud.githubusercontent.com/assets/13024052/14843495/4d4c4aaa-0c6e-11e6-8052-5f01397a60ad.png)

How to activate theme in new opencart version

**Comment by danielkerr** [comment]
go to these default then look at the bottom field. this allows backwards compatibility.

**Comment by ajprok** [comment]
Thank you all.
