### ISSUE TITLE
Change log issues

### ISSUE THREAD

**Issue by badsyntaxx** [opencart/opencart#4297]
This is a 2 part issue.
First: The tab labeled “Changelog” on the opencart download page does not contain a change log. It only contains a link that leads to a github page that also does not contain a change log. That is 2 total links the user must follow just to find out they are both false. This misleads the user and wastes everyone’s time. Perhaps just a sentence on the changelog page that says you must download a version of OC and find the actual change log inside the zip file.

Second: Recently OC was update to version 2.2.0.0, however the change log shows nothing under that version. 
The readme shows
`The version is broken down into 4 points e.g 1.2.3.4 We use MAJOR.MINOR.FEATURE.PATCH to describe the version numbers.`
`A MINOR is when there are significant changes that affect core structures. This increment would likely break some 3rd party modules.`

So if there were significant changes to OC from 2.1 to 2.2 why are they not shown in the change log?

The change log shows the following
`OpenCart 2.0 change log`
`v2.2.0.0 (02.03.2016) `
`v2.1.0.1 (06.10.2015)
Bugs fixed
Use the ip address from data in Fraudlanbs module and update language strings
Changes
Allow download of the error log`

Why are there no changes shown under v2.2.0.0? 
What has changed since 2.1? 
If nothing has changed why did the devs feel the need to change the version number for OC?
If something has changed why did they not show the changes in the change log?

**Comment by danielkerr** [comment]
sorry! we are planning to do this better just very busy.
