### ISSUE TITLE
Syntax error in customer module

### ISSUE THREAD

**Issue by Ooze** [opencart/opencart#4300]
opencart Version 2.2.0.0 (trs-2.2.0.0)
/admin/index.php?route=customer/customer

Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /srv/www/opencart/upload/admin/controller/customer/customer.php on line 1105

**Comment by mhcwebdesign** [comment]
I think line 1105 should be this:

````
					} elseif (($custom_field['type'] == 'text' && !empty($custom_field['validation']) && $custom_field['location'] == 'address') && !filter_var($value['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {
````

**Comment by CoverUp** [comment]
your proposed code has a mistake

**Comment by Ooze** [comment]
This code has been downloaded from http://www.opencart.com/index.php?route=download/download
2.2.0.0 (Latest version). Please upload the fixed version on http://www.opencart.com/index.php?route=download/download.
