### ISSUE TITLE
jQuery NS_ERROR_UNKNOWN_PROTOCOL Exception on Order View

### ISSUE THREAD

**Issue by rsmck** [opencart/opencart#4303]
Viewing an order in the admin panel when SSL is enabled causes the following error

```[Exception... "The URI scheme corresponds to an unknown protocol handler"  nsresult: "0x804b0012 (NS_ERROR_UNKNOWN_PROTOCOL)"```

This appears to be due to the URLs in the $.ajax calls being prepared with an httpss:// prefix, rather than https://

**Comment by rsmck** [comment]
As a workaround;

Changing line 850 of controller/sale/order.php from
`$data['store_url'] = $this->request->server['HTTPS'] ? str_replace("http", "https", $order_info['store_url']) : $order_info['store_url'];`
to
`$data['store_url'] = $order_info['store_url']; `

Resolved this in my case.

**Comment by pine3ree** [comment]
@rsmck 
Hello, i see it fixed in master:
```php
$data['store_url'] = $this->request->server['HTTPS'] ? preg_replace("/^http:\/\//", "https://", $order_info['store_url']) : $order_info['store_url'];
```
kind regards
