### ISSUE TITLE
2.2 Theme issue

### ISSUE THREAD

**Issue by edbeeny** [opencart/opencart#4304]
I have copied the default_theme.php from 
admin/controller/theme
admin/language/en-gb/theme
admin/view/template/theme 

and renamed them theme_test.php

I have opened up the admin/controller/theme/theme_test.php and renamed all references to deafult_theme to theme_test

I have gone into Extension->Themes and installed and activated.
I have then copied stylesheet and common->header from the default theme and changed the location of the stylesheet in the header.tpl

However every time I browse the site the theme always references the default_theme location.
I have tried adding the theme location in extensions->theme to the new location, but it seems that makes no difference.

A bug or missing something. No documentation to help.

**Comment by pekka2** [comment]
@edbeeny 
cataloag/controller/event/event/theme.php lines 13-17:
		
		```
if ($this->config->get('config_theme') == 'theme_default') {
			$directory = $this->config->get('theme_default_directory');
		} else {
			$directory = $this->config->get('config_theme');
		}
```
Your need rename folder catalog/view/theme/test to theme_test.
