### ISSUE TITLE
More Openbay Issues

### ISSUE THREAD

**Issue by fido-x** [opencart/opencart#4305]
In "admin/controller/openbay/amazon.php", line 1000:

	$data['link_do_listings'] = $this->url->link('openbay/amazonus/doBulkLinking', 'token=' . $this->session->data['token'], true);

Should link to "openbay/amazon" not "openbay/amazonus", like so:

	$data['link_do_listings'] = $this->url->link('openbay/amazon/doBulkLinking', 'token=' . $this->session->data['token'], true);

In "admin/controller/openbay/amazonus.php", line 459:

	$data['delete_saved'] = $this->url->link('openbay/amazon_product/deleteSaved', 'token=' . $this->session->data['token'], true);

Should link to "openbay/amazonus_product/deleteSaved" not "openbay/amazon_product/deleteSaved", like so:

	$data['delete_saved'] = $this->url->link('openbay/amazonus_product/deleteSaved', 'token=' . $this->session->data['token'], true);

Same file, at lines 773 to 777:

	$data['start'] = ($page - 1) * $this->config->get('config_limit_admin');
	$data['limit'] = $this->config->get('config_limit_admin');

	$results = $this->model_openbay_amazonus->getProductSearch($data);
	$product_total = $this->model_openbay_amazonus->getProductSearchTotal($data);

Should be changed to:

	$filter['start'] = ($page - 1) * $this->config->get('config_limit_admin');
	$filter['limit'] = $this->config->get('config_limit_admin');

	$results = $this->model_openbay_amazonus->getProductSearch($filter);
	$product_total = $this->model_openbay_amazonus->getProductSearchTotal($filter);

In "admin/controller/openbay/ebay.php", insecure link at line 93:

	$this->response->redirect($this->url->link('openbay/ebay&token=' . $this->session->data['token']));

Should be:

	$this->response->redirect($this->url->link('openbay/ebay', 'token=' . $this->session->data['token'], true));

Same file, insecure link at line 1492:

	$this->response->redirect($this->url->link('extension/openbay/items&token=' . $this->session->data['token']));

Should be:

	$this->response->redirect($this->url->link('extension/openbay/items&token=' . $this->session->data['token'], true));

In "admin/controller/openbay/ebay_profile.php", insecure link at line 72:

	$data['cancel'] = $this->url->link('openbay/ebay_profile/profileall', 'token=' . $this->session->data['token'], true);

Should be a capital "A" in "profileAll", like so:

	$data['cancel'] = $this->url->link('openbay/ebay_profile/profileAll', 'token=' . $this->session->data['token'], true);

Same file, line 80:

	$this->response->redirect($this->url->link('openbay/ebay_profile/ProfileAll&token=' . $this->session->data['token'], true));

Should be a lower case "p" in "profileAll" and the token should be separated so the correct number of arguments is passed through, like so:

	$this->response->redirect($this->url->link('openbay/ebay_profile/profileAll', 'token=' . $this->session->data['token'], true));

Same file, lines 98 and 113:

	$this->response->redirect($this->url->link('openbay/ebay_profile/profileAll&token=' . $this->session->data['token'], true));

Should have the token separated so the correct number of arguments is passed through, like so:

	$this->response->redirect($this->url->link('openbay/ebay_profile/profileAll', 'token=' . $this->session->data['token'], true));

Same file, line 137:

	$this->response->redirect($this->url->link('openbay/ebay/syncronise&token=' . $this->session->data['token'], true));

Should have the token separated so the correct number of arguments is passed through, like so:

	$this->response->redirect($this->url->link('openbay/ebay/syncronise', 'token=' . $this->session->data['token'], true));

Same file, line 174:

	$this->response->redirect($this->url->link('openbay/ebay_profile/profileall&token=' . $this->session->data['token']));

Should be a capital "A" in "profileAll", separate the token and fix SSL, like so:

	$this->response->redirect($this->url->link('openbay/ebay_profile/profileAll', 'token=' . $this->session->data['token'], true));

In "admin/controller/openbay/ebay_template.php", insecure link at lines 80, 99 and 119:

	$this->response->redirect($this->url->link('openbay/ebay_template/listAll&token=' . $this->session->data['token'], true));

Should have the token separated so the correct number of arguments is passed through, like so:

	$this->response->redirect($this->url->link('openbay/ebay_template/listAll', 'token=' . $this->session->data['token'], true));

Breadcrumb at line 166:

	'href' => $this->url->link('openbay/ebay/listAll', 'token=' . $this->session->data['token'], true),

Should be:

	'href' => $this->url->link('openbay/ebay_template/listAll', 'token=' . $this->session->data['token'], true),

In "admin/controller/openbay/etsy.php", breadcrumb at line 50:

	'href' => $this->url->link('openbay/ebay', 'token=' . $this->session->data['token'], true),

Should be:

	'href' => $this->url->link('openbay/etsy', 'token=' . $this->session->data['token'], true),

Badly formatted and insecure link at line 86:

	$this->response->redirect($this->url->link('openbay/etsy/index&token=' . $this->session->data['token']));

This should be:

	$this->response->redirect($this->url->link('openbay/etsy', 'token=' . $this->session->data['token'], true));

In "admin/controller/openbay/fba.php", badly formatted and insecure link at line 86:

	$this->response->redirect($this->url->link('openbay/fba/index&token=' . $this->session->data['token']));

This should be:

	$this->response->redirect($this->url->link('openbay/fba', 'token=' . $this->session->data['token'], true));

Same file, badly formatted and insecure link at line 298:

	$this->response->redirect($this->url->link('openbay/fba/fulfillmentlist&token=' . $this->session->data['token']));

This should be:

	$this->response->redirect($this->url->link('openbay/fba/fulfillmentlist', 'token=' . $this->session->data['token'], true));

And last, but certainly not least, the "install" function in the following files:
	admin/controller/openbay/amazon.php
	admin/controller/openbay/amazonus.php
	admin/controller/openbay/ebay.php
	admin/controller/openbay/etsy.php
	admin/controller/openbay/fba.php

make a call to:

	$this->model_user_user_group->addPermission()

without loading the model. Suggest inserting:

	$this->load->model('user/user_group');

at the beginning of the "install" function (at around line 7) in each of the above files.

**Comment by jamesallsup** [comment]
thanks @fido-x - I will look into these and update the obp repo for the next update.

**Comment by jamesallsup** [comment]
Thanks again @fido-x
