### ISSUE TITLE
Bug counting arguments when executing an action in action.php

### ISSUE THREAD

**Issue by chrisrollins65** [opencart/opencart#4307]
### Problem
When executing an action in `system/engine/action.php`, the number of arguments are counted to ensure the correct number for the the relevant method are present.
The problem occurs when you try to pass more than one argument for a controller method. In **`/system/engine/loader.php`** on **line 21**:
```php
$output = $action->execute($this->registry, array(&$data));
```
When this array of data is counted in **`/system/engine/action.php`** on **line 43**:
```php
if ($reflection->hasMethod($this->method) && $reflection->getMethod($this->method)->getNumberOfRequiredParameters() <= count($args)) {
```
the value of `count($args)` is always 1 instead of the number of elements in `$data`.

### Solution
Change the above line in **`/system/engine/loader.php`** to:
```php
$output = $action->execute($this->registry, $data);
```

Add a line to **`/system/engine/action.php`** to ensure the value passed is an array (since you need to pass an array to `call_user_func_array` later):

```php
if ( !is_array($args) ) { $args = array($args); }
if ($reflection->hasMethod($this->method) && $reflection->getMethod($this->method)->getNumberOfRequiredParameters() <= count($args)) {
```

**Comment by pine3ree** [comment]
@chrisrollins65 
I see your point (and i had some doubts about it when the code was changed from 1.5 to 2.x).
But there are case where `count($args)` is 2 or 3.
in Loader::controller(...) method you have pre/post event triggering. calling Event::trigger(...) will pass to all the actions related to that event 2 (`array(&$route, &$data)`) and 3 (`array(&$route, &$data, &$output)`) arguments respectively.

The Action class is used in the event manager, here its instances are receiving more than 1 argument

**Comment by pine3ree** [comment]
@chrisrollins65 

- normal controller methods will not have arguments
- module controller public methods will receive `array(&settings_info)` as argument
- event handler action will recevie more arguments (see `catalog/controller/total/voucher::send($route, $output, $order_id, $order_status_id)`)

kind regards

**Comment by chrisrollins65** [comment]
Thank you for the information, @pine3ree. The change I propose shouldn't affect the functionality of any model or event methods. It'd just allow controller methods to be called via the loader with more than one argument. I'll give an example of the problem that led me to investigate this:

I'm working on an extension that modifies the error handler a bit for a specific function. It utilizes PHP's `set_error_handler()` for the custom functionality but then calls OpenCart's error handler to handle the log and so forth.

Calling the handler function the way I've seen done with other controller methods doesn't work because of the problem I outlined in my original post:

```$this->load->controller('startup/error/handler', array($errno, $errstr, $errfile, $errline));```

I've tested the solution I proposed, and it solves this. But maybe I'm going about it the wrong way. Is there a better way to call this method with the needed arguments?

**Comment by pine3ree** [comment]
Hello @chrisrollins65 ,

I don't believe that `ControllerStartupError::handler(...)` is supposed to be called like other controller actions. It's an utility method. In my own fork the error/exception handler belongs to a library class and the handlers are registered the old way during startup. I believe the only reason Daniel put it in a controller is to have a unified way to automatically run things. In this case the 'startup/error(/index)' controller action. The purpose of `ControllerStartupError` class is to register the error handler method via the standard action `index()` (this is a standard controller action). Furthermore `$this->load->controller` is used to get a string representing the rendering of a child controller (header, footer, modules). This method replaced the old oc 1.5 getChild() controller mehod. But out of curiosity i will try to load the error method like you did and i will get back to you with my results. 
kind regards

**Comment by pine3ree** [comment]
@chrisrollins65 
I confirm it cannot be called with Loader::controller() because it gets 1 arrray argument:
You can call it like this:
```php
$action = new Action('startup/error/handler');
$output = $action->execute($this->registry, $your_error_handler_args);
```
inside any class having this->registry property.

It basically creates a new ControllerStartupError instance and run the handler method.

I agree that having `Loader::controller` `$data` argument translated directly into `Action::execute` `$data` argument would be clearer. To achieve that some other changes would be needed, for instance inside the module holder controllers

```php
$module_data = $this->load->controller('module/' . $part[0], $setting_info);
```

should be rewrittend to:

```php
$module_data = $this->load->controller('module/' . $part[0], array($setting_info));
```
because some module controller methods (module/feature/index for instance) expect 1 array ($setting) parameter. Right now `$setting_info` is transformed into `array($setting_info)` inside the Loader:controller() method.

**Comment by chrisrollins65** [comment]
Thank you for you suggestion of using an Action instance. That will work for what I'm trying to do.

I see your point that there are sections of the application that expect the code to work the way it is currently written, and I agree with you that it should be rewritten to make more sense.

Perhaps it can be done in a future release of OpenCart. If I find the time, I'll see if I can hunt down everything that would need to be changed and create a pull request for it.

In the meantime, I guess this issue is resolved. Thanks for your help!
