### ISSUE TITLE
bug on ebay installation 

### ISSUE THREAD

**Issue by PradeepManagave** [opencart/opencart#4309]
when i install ebay i got message "Parse error: syntax error, unexpected 'public' (T_PUBLIC) in /home/pmanagave/public_html/system/library/openbay/ebay.php on line 30"
i don't get home page and admin page
any body pls resolve this issue

**Comment by jamesallsup** [comment]
Usually caused when you or a module modifies the startup or index files.

You can get help from the OpenBay Pro support team at https://help.welfordmedia.co.uk/contact - they will be able to check and advise for you as this isn't OpenCart related (it is a 3rd party plugin)
