### ISSUE TITLE
Store credit does not decrease on confirming order - OC 2.2

### ISSUE THREAD

**Issue by ajprok** [opencart/opencart#4314]
![screenshot from 2016-05-02 15-47-52](https://cloud.githubusercontent.com/assets/18692797/14952462/11884f50-107e-11e6-869b-af5941dd7b2d.png)
![screenshot from 2016-05-02 15-47-13](https://cloud.githubusercontent.com/assets/18692797/14952463/118b9da4-107e-11e6-8860-67460f163c5a.png)
![screenshot from 2016-05-02 15-46-36](https://cloud.githubusercontent.com/assets/18692797/14952464/119066e0-107e-11e6-96de-fef4ebfdd2be.png)

For testing I gave a customer 10 store credits through _Transaction_. However, when that Customer purchases a product, although the store credit is decreased from total, the store credit of the customer is not deducted. Because of this the customer can buy multiple times with the same store credit.

**Comment by danielkerr** [comment]
order status needs to reach the complete order status

**Comment by danielkerr** [comment]
do some research instead of posting here!

**Comment by hrm143** [comment]
it is not deducting in my case too..changed to order status complete

**Comment by turhanserkan** [comment]
> order status needs to reach the complete order status

This comment not in logic :) When the order is received, it goes through some processes (payment confirmation, inventory control, etc.) and then when the customer receives the package, the order status marked as "completed" and customer will be able to order again and again with her existing credit in this process, right?!
