### ISSUE TITLE
Amazon Login and Pay - VAT based on shipping address

### ISSUE THREAD

**Issue by lifis** [opencart/opencart#4316]
If the customer creates a new Amazon account and adds the address manually in the Amazon login and pay frame - Opencart does not recognise whether the shipping address needs VAT or not.

if the customer already has a registered account with the store and Amazon then Opencart will recognise the address and apply the VAT.

> > I don't think the address created in the Amazon frame is getting passed back to Opencart properly in order to apply the VAT.

**Comment by lifis** [comment]
If I login with Amazon it shows like the below screenshot. 
hence why opencart can not apply VAT based on shipping address

![screen shot 2016-06-19 at 15 27 55](https://cloud.githubusercontent.com/assets/19150256/16178029/e7235ed4-3635-11e6-990d-11cba78fa808.png)

**Comment by chris-wm** [comment]
@lifis Hi, thank you for raising the issue, Amazon also brought this to our attention and it has been resolved in the upcoming release of OpenCart. It will also be applied to the backwards compatible modules available on the extensions store, this should be implemented in the next few weeks and I will update the ticket when they have been released,
regards

**Comment by wennbley** [comment]
Hi... Any news on the fix?

**Comment by chris-wm** [comment]
@wennbley The patch files have been provided to Amazon who are testing at the moment, once they have signed off on the updates we will release them on the extension store. 
Regards

**Comment by wennbley** [comment]
Just spoken Amazon and its now back with you guys to fix some issues. How long until a release?

**Comment by chris-wm** [comment]
@wennbley Hi, the current issues are more a question of implementation rather than of bugs so we are currently discussing with Amazon how best they would like the system to work. Once this has been decided upon we will then have to implement any further changes so it could still be a while before it is released,
regards

**Comment by wennbley** [comment]
Just wondering if this fix will sort out the VAT being taken off my site when anyone uses Login with Amazon?

**Comment by chris-wm** [comment]
@wennbley Hi, yes I believe you are referring to one of the issues that has been resolved,
regards

**Comment by wennbley** [comment]
Hi guys.... Any news on the fix?

**Comment by chris-wm** [comment]
@wennbley Hi, Amazon have got back with the results of their testing, there are a few issues that remain to be resolved but I expect that the modules will be released next week,
regards

**Comment by wennbley** [comment]
Any news on this fix?

**Comment by lifis** [comment]
Its fixed in 2.3.0.2, but the automatic capture status doesn't work anymore.

**Comment by wennbley** [comment]
This has been going on for ages now! probably worth removing from my shop as it does not work properly (its pissing my customers off as I have to get the missing VAT off of them after they have made payment). Will it ever work? Let us know developers so we don't waste our time and lose customers.

**Comment by chris-wm** [comment]
@wennbley Hi, the backwards compatible modules have now been updated on the extensions store and can be downloaded from [here](http://www.opencart.com/index.php?route=extension/extension/info&extension_id=25006). @lifis I will look at this issue on the latest OC and update this ticket as soon as I have more information,
regard

**Comment by chris-wm** [comment]
@lifis Hi, can you overwrite the file found in this directory with the attached and this will resolve the issue catalog/controller/extension/payment/. I will also apply this fix to the OpenCart repo,
regards
[amazon_login_pay.php.zip](https://github.com/opencart/opencart/files/487720/amazon_login_pay.php.zip)

**Comment by chris-wm** [comment]
@lifis Hi,
sorry can you actually use this file instead and also delete the event with code 'amazon_edit_capture' from your event table in the database,
regards
[amazon_login_pay.php.zip](https://github.com/opencart/opencart/files/489490/amazon_login_pay.php.zip)

**Comment by lifis** [comment]
@chris-wm Hi Chris - Thanks for getting back to me, I replaced the file you sent yesterday on my dev system and it didn't work. So I try these new updates and let you know how I get on.

its like the only bug I have on my system.. so fingers crossed :)

**Comment by wennbley** [comment]
Another issue which I cannot resolve. I have a few customers that are having issues when trying to checkout. They are getting this message:

"login failed: SHOP NAME account email address did not match Amazon account email address."

When double checking with our customers that they are using the same email address with our shop (when they registered) with their Amazon account. They said yes!

Any ideas?

**Comment by lifis** [comment]
@chris-wm Hi Chris, I've tried both the versions you added recently with no luck - my automatic capture status is 'shipped' so when I mark it as shipped it is still not capturing the payment.

I deleted the amazon_edit_capture from the event table also. my event table looks like this:
![screen shot 2016-09-25 at 13 18 23](https://cloud.githubusercontent.com/assets/19150256/18815290/8ea2d1aa-8323-11e6-8bbf-0066f1af7903.png)

I also went back to the original version of code from 2302 and made sure the triggers and action paths were the same as a fresh install.. still no luck.

**Comment by chris-wm** [comment]
@wennbley Hi,
yes the email address would need to be identical, did they have different capitalisation for the emails?
Regards

**Comment by chris-wm** [comment]
@lifis Hi,
would you be able to raise a ticket on our [support site](https://help.welfordmedia.co.uk/) so that I can have a look at your install?
Regards

**Comment by wennbley** [comment]
@chris-wm Yes the customer had a lower case letter (for the start of the email address) on their Amazon account, and on my shop account they had a upper case letter.

When the customer tries to edit their email address on my shop, it will stay as a capital for some reason? I will have to delete their account and they will have to sign up again, making sure their email is all lower case.

Any way around this?

**Comment by chris-wm** [comment]
@wennbley what OC version are you using?

**Comment by wennbley** [comment]
@chris-wm it's 2.1.0.1

**Comment by chris-wm** [comment]
@wennbley emails with different capitalisation can be considered different so the correct way to resolve this would be to fix the email address in your customer account, if you are having problems doing this via the admin the you could feasibly do this straight in the database,
regards

**Comment by wennbley** [comment]
So I have updated to the latest from the OC site. I am still having issues with the VAT being taken off all of my products when logging in with Amazon (not tried to see if the vat is being added to the invoice). 

I don't hold up much hope if this being fixed.

**Comment by lifis** [comment]
@chris-wm am I expected to pay for this to be looked at? I am happy for you to look at my installation..

**Comment by chris-wm** [comment]
@lifis Hi,
for this particular issue we would not charge for the investigation, assuming that it is in fact a bug in the payment gateway. If however if it turns out to be an issue with the set-up/code of your store then we would require payment if you wished for us to resolve it for you, you would be under no obligation to proceed with this. Please tell the support team that I referred you to them and ask them to speak to me about the issue,
regards

**Comment by chris-wm** [comment]
@wennbley Hi,
do you mean you updated your store or updated the gateway? If you are prepared to raise a ticket on our [support site](https://help.welfordmedia.co.uk/) and provide details then I can investigate the problem on your specific store,
regards

**Comment by lifis** [comment]
@chris-wm Chris just out a curiosity - in the latest code you supplied.. you also said "delete 'amazon_edit_capture' from event table" - does this actually have to be deleted for good? because if I was to uninstall and reinstall the extension this event would just come back?
