### ISSUE TITLE
[BUG] catalog/controller/api/order.php

### ISSUE THREAD

**Issue by helgvor-stoll** [opencart/opencart#4318]
Hello,

It seems that a mistake appeared in the file: catalog/controller/api/order.php (line 766).
$json = $this->model_checkout_order->getOrder($order_id);
should be:
$order_info = $this->model_checkout_order->getOrder($order_id);

Best regards

**Comment by mrbarletta** [comment]
Looks like you are right.

 Proposed PR #4331
