### ISSUE TITLE
Show Subcategory Items in Filter Module

### ISSUE THREAD

**Issue by bizzynate** [opencart/opencart#432]
This is related to https://github.com/opencart/opencart/issues/431 and applies a similar edit to the filter module. This proposed solution is based on the 1.5.5.1 release.

Change lines 57-58 in /catalog/controller/module/filter.php from

```
 'filter_category_id' => $category_id,
 'filter_filter'      => $filter['filter_id']
```

to

```
 'filter_category_id' => $category_id,
 'filter_sub_category' => true,
 'filter_filter'      => $filter['filter_id']
```

This results in the inclusion of subcategory products in the count placed next to each filter (e.g. "laptops (5)").

**Comment by tostercx** [comment]
Nonsense, this should be the default behavior. Why would I even try using the filter, if it shows 0 products there. If it searches for products in subcategories, it should show their count as well, no?
