### ISSUE TITLE
Affiliate Program Registeration Agree to about not to terms

### ISSUE THREAD

**Issue by doronshe** [opencart/opencart#4320]
When registering a new affiliate, one is asked to agree to:
"I have read and agree to the **About Us**"
[http://demo.opencart.com/index.php?route=affiliate/register](url)

**Comment by danielkerr** [comment]
and??? you know how to change it? then change it!

dont post stupid things like this! your just wasting developers time!

**Comment by doronshe** [comment]
The stupidity is of the defect in your program you are so proud of.
Just fix your damn defect that all are downloading 
Be responsible and responsive to your creation
Don't be an ass
