### ISSUE TITLE
Product options lost in saved carts

### ISSUE THREAD

**Issue by diatodan** [opencart/opencart#4321]
1. A customer adds a product with an option to the cart.
2. Admin changes the option causing the id to be deleted and and recreated.
3. The customer logs in (the product in the cart loses the option) and places the order without the option

As discussed here : https://forum.opencart.com/viewtopic.php?f=20&t=85193&start=20

Is it possible to keep the option id on update or force the cart to update ?
This issue is really a problem when the product price is set to 0 and the options set the price.
Thanks

**Comment by danielkerr** [comment]
the post you have linked to is from Sep 05, 2013!!!

no one else has compliance!
