### ISSUE TITLE
google_sitemap generating too long

### ISSUE THREAD

**Issue by vitaly-zdanevich** [opencart/opencart#4327]
For ~4000 products it takes nearly 20 seconds on Amazon mini instance with 1gb of ram. I see bottleneck at the `htop` - cpu of the mysql.

As I see at Google Webmaster - no problem with such delay, but popular Russian search engine - Yandex - can not wait too long - I see this at [webmaster.yandex.ru](webmaster.yandex.ru)
![3ckpkawti0m](https://cloud.githubusercontent.com/assets/3514015/15009850/9479d2ac-11f1-11e6-9e56-bfdf702a0ad8.jpg)

Maybe you can add some caching mechanism?

**Comment by pine3ree** [comment]
@vitaly-zdanevich 
I use caching to save the generate xml. You could also save the page result to an actual sitemap.xml file in the server, but you will need to replace it when products change. Nevertheless this could be a temporary solution for feeding yandex.
kind regards
