### ISSUE TITLE
google_sitemap: inaccessible images 404

### ISSUE THREAD

**Issue by vitaly-zdanevich** [opencart/opencart#4328]
In exported xml I see

```
<image:loc>
  http://zvukovik.by/image/cache/data/1a/EdnetGrizzlyBear831351-x.jpg
</image:loc>
```
But this image is inaccessible by direct link.

I need to edit something at `.htaccess` or something else?

**Comment by opencarteli** [comment]
Maybe this link can help u
http://forum.opencart.com/viewtopic.php?t=139979&p=547110

**Comment by vitaly-zdanevich** [comment]
problem was with folder permission on server
