### ISSUE TITLE
php-xml library is being used by OpenCart, but not listed in documentation!

### ISSUE THREAD

**Issue by XxXxXprogrammerXxXxX** [opencart/opencart#4330]
**Hello!**

OpenCart uses **[php-xml](http://php.net/manual/en/book.dom.php)** library that provides classes for DOM manipulation and OpenCart can't perform some operations without it. 

Please add it to required PHP extension list in **[documentation](http://docs.opencart.com/requirements/ )**.

My PHP of version 7.0.3 is downloaded from official ubuntu repository and it doesn't ship php-xml by default. I had to install it by typing `$ sudo apt-get install php7.0-xml`

Don't make people waste their time, provide documentation for that :smiley:

**Comment by CoverUp** [comment]
a check list during install would be better.. 
[Ok][passed] etc

**Comment by danielkerr** [comment]
domdocument is built into php! not such what idiot hosting would not include it.

**Comment by XxXxXprogrammerXxXxX** [comment]
If you don't trust me, you can just install any debian-like linux distro and install php v7 on it and try to use DOMDocument
