### ISSUE TITLE
Method Resize not find images on Windows

### ISSUE THREAD

**Issue by victorwbuzz** [opencart/opencart#4332]
Method resize returning NULL

O.S: Windows 10
PHP 5.4
Apache 2.4

Root Path: C:\laragon\www\rexpeita-elearning/

Image tried to load: C:\laragon\www\rexpeita-elearning/image/no_image.png

```
if (!is_file(DIR_IMAGE . $filename) || substr(str_replace('\\', '/', realpath(DIR_IMAGE . $filename)), 0, strlen(DIR_IMAGE)) != DIR_IMAGE) {
    return;
}
```

Old validation running ok:

```
if (!is_file(DIR_IMAGE . $filename)) {
	return;
}
```

https://github.com/opencart/opencart/commit/efe6534b6f535de30e07bbae8183be706db57fc2

**Comment by danielkerr** [comment]
and yet thuis part protects your system from being heacked!

|| substr(str_replace('\\', '/', realpath(DIR_IMAGE . $filename)), 0, strlen(DIR_IMAGE)) != DIR_IMAGE)

**Comment by danielkerr** [comment]
i suggest you check your server

**Comment by victorwbuzz** [comment]
I don't know why i need to check my server. 

small dump with your code:

realpath: C:\laragon\www\rexpeita-elearning\image\no_image.png
substr: C:/laragon/www/rexpeita-elearning/image/
dir_image: C:\laragon\www\rexpeita-elearning/image/

See the result of **substr(str_replace('\\', '/', realpath(DIR_IMAGE . $filename)), 0, strlen(DIR_IMAGE))** never will be the same of **DIR_IMAGE** on windows servers

**Comment by aldoanizio** [comment]
Same problem here.

O.S: Windows 8
PHP 5.6
Apache 2.4

Root Path: E:\web-server\public\cipreste/

Image tried to load: E:\web-server\public\cipreste/image/no_image.png

The problem looks like related to Windows paths. Older versions and Linux OS's seems fine.

Why not keep the validation as simple as possible ? 

Since DIR_IMAGE is a static config and all the image paths is built on top of it, any changes on config files will break the rest of paths.

**Comment by victorwbuzz** [comment]
@aldoanizio try this code:

changing '/' to constant DIRECTORY_SEPARATOR i was fixed problem here
 
```
if (!is_file(DIR_IMAGE . $filename) || substr(str_replace('\\', DIRECTORY_SEPARATOR , realpath(DIR_IMAGE . $filename)), 0, strlen(DIR_IMAGE)) != DIR_IMAGE) {
    return;
}
```

**Comment by victorwbuzz** [comment]
@aldoanizio i guess unix users dont care too much about directory separator on windows system so them dont know about single backslash in paths

**Comment by victorwbuzz** [comment]
Fixed it providing same standard only to pass conditional:

```
if (!is_file(DIR_IMAGE . $filename) || substr(str_replace('\\', '/', realpath(DIR_IMAGE . $filename)), 0, strlen(DIR_IMAGE)) != str_replace('\\', '/', realpath(DIR_IMAGE))) {
    return;
}
```

**Comment by victorwbuzz** [comment]
@aldoanizio  fixed it providing same standard on the right side. Try it:

```
if (!is_file(DIR_IMAGE . $filename) || substr(str_replace('\\', '/', realpath(DIR_IMAGE . $filename)), 0, strlen(DIR_IMAGE)) != str_replace('\\', '/', DIR_IMAGE)) {
    return;
}
```
