### ISSUE TITLE
Sagepay server opencart 2.2

### ISSUE THREAD

**Issue by edbeeny** [opencart/opencart#4336]
It seems that version 2.2 when paying with sagepay server isn't sending the RedirectionURL

Server error 5006: Unable to redirect to Vendor's web site. The Vendor failed to provide a RedirectionURL.

**Comment by edbeeny** [comment]
Also Logs are not been generated for Sagepay Server.

**Comment by gob33** [comment]
Normal, the code of SagePay is unfinished. Do not use it.

**Comment by edbeeny** [comment]
So why would you release version 2.2 when code is not complete on extensions that have been in since 1.*
No documentation indicating that.
Daniel you moan when people waste your time, Thanks 4 days wasted on getting a project ready and now have to revert it back to 2.1 WTF.

**Comment by gob33** [comment]
It is WelfordMedia work.
See http://www.opencart.com/index.php?route=extension/extension/info&extension_id=16868 the sagepay v3 integration.
.

**Comment by edbeeny** [comment]
So if's it not compatible with the current core, remove it. Simple.

**Comment by chris-wm** [comment]
@edbeeny @gob33 Hi, I will have a look at the gateway in question and update the ticket when I have some answers,
regards

**Comment by edbeeny** [comment]
@chris-wm you can ignore this, I eventually found a small server issue that was preventing the callback function to be called.
The Sagepay Server extension works fine.

**Comment by chris-wm** [comment]
@edbeeny Hi, I'm glad that you were able to resolve the issue. I had tested the gateway and wasn't able to find the problem and was just in the middle of a writing a response suggesting that there might be a server or redirect issue causing the problem,
regards

**Comment by duller999** [comment]
@edbeeny any idea what the issue was here, I am experiencing this 1 year on.
