### ISSUE TITLE
Event system do not work on friendly/seo urls

### ISSUE THREAD

**Issue by LucasKauz** [opencart/opencart#4339]
Hi, I'm using heavily the event system and realized this bug. The controller before and controller after aren't triggered when you are using SEO URLs.

The main controller, like product/category/before, will not trigger. So you can't rely on the event system with specific URLs (the same don't happen on modules, etc) seems to be a problem with the ROUTER.PHP since it's not called when we use SEO URLs.

We (me and @victorwbuzz) could not solve the problem yet, but it seems to be vitally important to notice the developers and/or fix the bug (for example people using it without the use of SEO in development and them break the production).

Thank you, and I'm here for any further questions.

**Comment by pine3ree** [comment]
@LucasKauz 
I can confirm that.
ControllerStartupSeoUrl return a new Action instance (on successful uri match) used as a pre-action in the front controller, so the original $action called by dispatch() is never executed. The original action is `$config->get('action_router') === 'startup/router'` => ControllerStartupRouter::index() is not executed anymore. At least is what I believe it happens at first sight.

kind regards

**Comment by pine3ree** [comment]
@LucasKauz @danielkerr 
as a suggestion: event triggering code could perhaps be moved inside Front::execute(Action $action) and applied to pre-actions as well.

**Comment by pekka2** [comment]
@LucasKauz
Is this issue:
https://github.com/opencart/opencart/issues/4244

**Comment by danielkerr** [comment]
i have removed

			if (isset($this->request->get['route'])) {
				//return new Action($this->request->get['route']);
			}

it should work now.

**Comment by bindashsandeep** [comment]
Hi @danielkerr ,
I used your seo_url.php code but my store url remain same. No changes happened. What to do now? I am using 2.3.0.2

Thanks!!
