### ISSUE TITLE
error in file  customer.php

### ISSUE THREAD

**Issue by nik2020** [opencart/opencart#4340]
when i click to check a new customer in my admin panel , i get the following error.

Parse error: syntax error, unexpected 'ControllerCustomerCustomer' (T_STRING) in /home/aaryapcv/public_html/admin/controller/customer/customer.php on line 1.

can anyone help me fix this ?
i am using opencart2.2.

**Comment by pine3ree** [comment]
@nik2020 

something changed your file!

i checked my 2.2.0 download and current master. There is nothing wrong in the first 2 lines, that should read:
```php
<?php
class ControllerCustomerCustomer extends Controller {
```

but I am curious about this repo:
https://github.com/nik2020/customer-line-error/blob/master/README.md

:-)

**Comment by nik2020** [comment]
<?phpclass ControllerCustomerCustomer extends Controller {	private $error = array();	public function index() {		$this->load->language('customer/customer');		$this->document->setTitle($this->language->get('heading_title'));		$this->load->model('customer/customer');		$this->getList();	}	public function add() {		$this->load->language('customer/customer');		$this->document->setTitle($this->language->get('heading_title'));		$this->load->model

**Comment by nik2020** [comment]
do u see any prob in the code ?

**Comment by pine3ree** [comment]
@nik2020 
Did you remove all new lines?

this is not valid php code:
```php
<?phpclass ControllerCustomerCustomer

**Comment by nik2020** [comment]
@pine3ree 
i have pasted the customer.php file in my root from the download copy of 2.2.
now i get this error which i got earlier before trying to fix the source code .


Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /home/aaryapcv/public_html/admin/controller/customer/customer.php on line 1105



do u know a

**Comment by nik2020** [comment]
@pine3ree 

i found out the error. thanx for your response.
got it fixed.

**Comment by cpltown** [comment]
I still have the same issue. The code you wrote @nik2020 I cant get past the error.
