### ISSUE TITLE
PHP Fatal error when going to Customers->Customers in Admin Area

### ISSUE THREAD

**Issue by hasMobi** [opencart/opencart#4342]
The following PHP syntax error is present when I go to this URL:
`/admin/index.php?route=customer/customer&token=HpQZTz7UOxpgeeTIui6xIQwcKzbtCELw`

`Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /public_html/mystoreurl.com/admin/controller/customer/customer.php on line 1105`

Using OpenCart version 2.2.0.0.

**Comment by nik2020** [comment]
http://forum.opencart.com/viewtopic.php?f=191&t=159399#p608658

**Comment by hasMobi** [comment]
Thank you for the link, Nik. I have fixed the issue already, using the method described on that thread (many other people complained of the same issue online).

I can't believe an official, public release of OpenCart is out there with such a serious hole in a such widely used area of the backend. This definitely deserves a hotfix release in my opinion, due to the block it poses on managing a regular ecommerce website.

**Comment by nik2020** [comment]
There are other lots of bugs too.... Do u have any problem sending marketing mail ?

**Comment by hasMobi** [comment]
Haven't tested that part.

**Comment by danielkerr** [comment]
can not replicate!
