### ISSUE TITLE
marketing>> mail issue

### ISSUE THREAD

**Issue by nik2020** [opencart/opencart#4343]
i am using open cart 2.2 and when i goto marketing >> mail , after typing the mail and when i click send mail icon,nothing happens.i am unable to send any mail or newsletter to any customers.
is anybody else facing this prob ?
please help

**Comment by CoverUp** [comment]
if the issue is not confirmed or is not reproducible please use the forums first

**Comment by nik2020** [comment]
Why have you closed the issue ?

Sent from Yahoo Mail on Android 
 
  On Mon, 9 May, 2016 at 3:59 p.m., Daniel Kerr<notifications@github.com> wrote:   
Closed #4343.

**Comment by DanJFletcher** [comment]
I'm having the same issue too. I also don't understand why it's closed without reference to the fix.

The only error I see is this in the JS console: `index.php?route=marketing/contact&token=Xp2rsBFccztuT2b1TtK3mDXIpts1QIXq:511 Uncaught TypeError: $(...).code is not a function`

All of the other jQuery is working and I can confirm that by typing `$` in the console. 

Clicking the "send" gives me no success or fail feedback.

If I write a custom mail script and place it on my server, I can visit that URL and I will receive an email, so it's not my server settings, it's OpenCart.

I got here after searching the forums and finding this helpful post:
>Re: Newsletters not sending
Postby i2Paq » Thu Jul 07, 2016 1:17 am

>Known issue with OC2.2.

>Please use our FREE search of visit our GitHub for a solution.

Of course, no link to the solution that apparently exists.

Here's the link to the thread: http://forum.opencart.com/viewtopic.php?t=164859&p=627649

**Comment by DanJFletcher** [comment]
@nik2020 
Try this: https://github.com/opencart/opencart/issues/4089
