### ISSUE TITLE
error in file address.php

### ISSUE THREAD

**Issue by nik2020** [opencart/opencart#4344]
when i log in as a customer and then click the address tab to add/change address , i get the following error.
Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /home/aaryapcv/public_html/catalog/controller/account/address.php on line 522

can somebody help
.

**Comment by CoverUp** [comment]
Already fixed on master, download a new copy
regards
https://github.com/opencart/opencart/commit/a8b6823b223aa4fedd325e4782c18f9079dd2ab7

**Comment by nik2020** [comment]
Thank....
