### ISSUE TITLE
2.2.0.0 - SSL Issue, cannot edit orders

### ISSUE THREAD

**Issue by xcentriq** [opencart/opencart#4347]
Fresh installation of OC 2.2.0.0 and I get an SSL error when viewing orders.

> [Exception... "<no message>"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: https://www.MYWEBSITE.com/shop/admin/view/javascript/jquery/jquery-2.1.1.min.js :: .send :: line 4"  data: no]
> 
> [Exception... "<no message>"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: https://www.MYWEBSITE.com/shop/admin/view/javascript/jquery/jquery-2.1.1.min.js :: .send :: line 4"  data: no]
> 
> undefined

What I've done:
- Installed fresh OC 2.2.0.0 - No mods, no updates, just pure download from the website and install.
- Edited "config.php" and "admin/config.php"
- Enabled SSL in store settings/server
- Create new order on front end and using guest check out
- Go into Admin panel, Sales -> Orders -> View Orders - At this point a popup with the error above comes up.

I've tried the following:
- Using Softaculous installer in Cpanel
- Installing manually from downloading from OC website
- Enabled SSL in store settings/server
- Disabled SSL in store settings/server
- Disable ALL SSL https protocols from settings, config.php and admin/config.php (no error above but I get this API error: ** Warning: You do not have permission to access the API!**)

What I think it is:
- While all is SSL enabled and in HTTPS protocol, on the order details page, when viewing source code, I found 3 instances of HTTPSS, rather than HTTPS.
- While all SSL and HTTPS is disabled, on the same order detail page, now with the API issue, source code shows "HTTPS" in the same instances where "HTTPSS" was.

Something is causing the extra "S" when SSL is not enabled, and when it is, enabling SSL mode adds another "S", resulting in HTTPSS.

Please address this issue ASAP. My store is on hold from being released to do business.

**Comment by pekka2** [comment]
Hi, how is your config.php HTTP_SERVER, http:// or https:// ?

**Comment by xcentriq** [comment]
Admin/config.php

```
// HTTP
define('HTTP_SERVER', 'https://www.mysite.com/shop/admin/');
define('HTTP_CATALOG', 'https://www.mysite.com/shop/');

// HTTPS
define('HTTPS_SERVER', 'https://www.mysite.com/shop/admin/');
define('HTTPS_CATALOG', 'https://www.mysite.com/shop/');
```

config.php
`// HTTP
define('HTTP_SERVER', 'https://www.mysite.com/shop/');

// HTTPS
define('HTTPS_SERVER', 'https://www.mysite.com/shop/');`

**Comment by pekka2** [comment]
Can you change to:
// HTTP
define('HTTP_SERVER', 'http://www.mysite.com/shop/');

// HTTPS
define('HTTPS_SERVER', 'http://www.mysite.com/shop/');

**Comment by xcentriq** [comment]
Tried that, issue still persists.

**Comment by pekka2** [comment]
@xcentriq 
You mean, that it yet add connect 'httpss://' ??

**Comment by xcentriq** [comment]
Yes, with HTTP, the page source code still shows HTTPS.

Line 274:
`<td><a href="**httpss**://www.mysite.com/shop/" target="_blank">Your Store</a></td>`

Line 669-671:
```
// Login to the API
$.ajax({
url: '**httpss**://www.mysite.com/shop/index.php?route=api/login',
```

Line 718:
`url: 'httpss://www.mysite.com/shop/index.php?route=api/order/history&token=' + token + '&order_id=1',`

**Comment by pekka2** [comment]
Can you test, how this mod to file admin/controller/sale/order.php to line 851-853 is work:

```
if( $this->server['HTTPS'] && substr($order_info['store_url'],0,5) !='https' ){
			   $data['store_url'] = $this->request->server['HTTPS'] ? str_replace("http", "https", $order_info['store_url']) : $order_info['store_url'];
 }
```

**Comment by pekka2** [comment]
https://github.com/opencart/opencart/pull/4353

**Comment by demartini** [comment]
This solved my problem: [#3536](https://github.com/opencart/opencart/issues/3536#issuecomment-155882241)

**Comment by coder480** [comment]
Mike222, I have the OC 2.2 and I have the same problem did you ever solve anyone can help please

**Comment by danielkerr** [comment]
this is an old issue that has already been fixed for 2.2.0 try 2.2.3

**Comment by coder480** [comment]
On Fri, Nov 4, 2016 at 8:52 PM, Daniel Kerr <notifications@github.com>
wrote:

> 2.2.3


​my OC is 2.2... I can't really update as my theme is on 2.2​



Thanks and regards,

Adam Nguyen

**Comment by danielkerr** [comment]
you should only need to rep[lace parts of  the code with the latest vewrsion
i dont think there were any big changes in between files

**Comment by coder480** [comment]
Do you know if there was a database change can I just overwrite all the
file to update to 2.3 from 2.2
thank you


Thanks and regards,

Adam Nguyen

**Comment by coder480** [comment]
I am getting this error. even after I have update my cs to 2.3 I can't
figure out why. Please help me


Thanks and regards,

Adam Nguyen

**Comment by mike222taylor** [comment]
Hello Deniel Kerr,

Make sure that this admin can change order edit from admin panel in live
site when i will use opencart version 2.2.3

**Comment by sfaragy** [comment]
Please visit http://opencartprogrammer.com/
And then contact us. We have real solution. We have ready module that will help you to edit your order.

**Comment by Fus3** [comment]
I solve this by modifying line 850 in admin/controller/sale/order.php file.

I just removed **s** from https in the following line:

$data['store_url'] = $this->request->server['HTTPS'] ? str_replace("http", "http**s**", $order_info['store_url']) : $order_info['store_url'];
