### ISSUE TITLE
More on Openbay

### ISSUE THREAD

**Issue by fido-x** [opencart/opencart#4350]
The "<?php echo $token ?>" in the ajax urls in the following template files has not been closed properly (no semi-colon):

    admin/view/template/openbay/amazon_bulk_listing.tpl (lines 156, 184 and 217)
    admin/view/template/openbay/amazonus_bulk_listing.tpl (lines 163 and 196)

Should be "<?php echo $token; ?>" (with the semi-colon).

**Comment by jamesallsup** [comment]
Thanks @fido-x - fixed on the openbay repo which will be merged before release. I did find others as well both openbay and not so I'll update those and see if I can add in a code scanning rule for this in tpl files.
