### ISSUE TITLE
Heap of useless sql-requests in category pages

### ISSUE THREAD

**Issue by guiltar** [opencart/opencart#4354]
There are tons of not optimized sql-requests in category pages and in other product-list pages.
When you need list of products **you use getProduct($product_id) for each single product in the page**.
It terribly slows down the script. For example, if category shows 40 (or 60 or 100) products per page you will have at least 40 (or 60 or 100) sql-requests in this page. To say it is very poor would be would be an understatement.

You may discover getProductsByIds method that will get all these 40 (or 60 or 100) products in one sql-request by given ids. All normal scripts do it in such a way.

See getProduct() in foreach cycle:
https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/product.php#L193
https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/product.php#L243
https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/product.php#L256
https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/product.php#L290
https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/product.php#L384
And other places all over the script. These are just examples

**Comment by danielkerr** [comment]
thats what caching is for. even with the so called 40 sql requests its still a lot less that all the other carts!

**Comment by guiltar** [comment]
No more comments. Everything is clear with your approach.
![xcfg_upldmmf 878x0 z-z96kyq](https://cloud.githubusercontent.com/assets/1562290/15181388/012fbac8-1798-11e6-9a71-e45bf8b84b24.jpg)
