### ISSUE TITLE
Category check-box is not saved for Coupon under OC store Admin

### ISSUE THREAD

**Issue by irinaOnesaas** [opencart/opencart#4355]
Opencart version 1.5.4

[steps]
1. Login to Opencart store admin
2.  Go to Sales->Coupons
3. Create new Coupon in Opencart or open an existing one
4. In the Category section select one Category to apply coupon to all products within that category
5. save changes
6. Open coupon once again and make sure category selection is saved

Expected; Category selection is saved

Actual: Category selection is not saved and coupon cannot be applied for products within selected category

**Comment by danielkerr** [comment]
well we are now version 2.2 so i suggest you look for a fix from commits!
