### ISSUE TITLE
oc_menu table is missing

### ISSUE THREAD

**Issue by robinflyhigh** [opencart/opencart#4357]

**Comment by anuj1987kr** [comment]
I also faced this issue.

When we click on Menu Manager we get below error:
***
Fatal error: Uncaught exception 'Exception' with message 'Error: Table 'open1.oc_menu' doesn't exist<br />Error No: 1146<br />SELECT COUNT(*) AS total FROM oc_menu' in C:\xampp\htdocs\open1\u\system\library\db\mysqli.php:40 Stack trace: #0 C:\xampp\htdocs\open1\u\system\library\db.php(16): DB\MySQLi->query('SELECT COUNT(*)...', Array) #1 C:\xampp\htdocs\open1\u\admin\model\design\menu.php(99): DB->query('SELECT COUNT(*)...') #2 [internal function]: ModelDesignMenu->getTotalMenus() #3 C:\xampp\htdocs\open1\u\system\engine\loader.php(160): call_user_func_array(Array, Array) #4 [internal function]: Loader->{closure}(Array) #5 C:\xampp\htdocs\open1\u\system\engine\proxy.php(13): call_user_func(Object(Closure), Array) #6 C:\xampp\htdocs\open1\u\admin\controller\design\menu.php(170): Proxy->__call('getTotalMenus', Array) #7 C:\xampp\htdocs\open1\u\admin\controller\design\menu.php(170): Proxy->getTotalMenus() #8 C:\xampp\htdocs\open1\u\admin\controller\design\menu.php(12): ControllerDesignMenu->getList() #9 [internal function]: in C:\xampp\htdocs\open1\u\system\library\db\mysqli.php on line 40
***

Url points to 
http://localhost:8080/open1/u/admin/index.php?route=design/menu&token=T3MtoDlAr3ReeWnvfLSr59SKBq5uneWW

It seems to be some bug.

-Anuj

**Comment by robinflyhigh** [comment]
@anuj1987kr fetch/merge master and run update. It will fix the issue.
