### ISSUE TITLE
No SKU, UPC, ISBN, MPN Coming on the OpenCart Product Page?

### ISSUE THREAD

**Issue by tarun454** [opencart/opencart#4361]
I am using the OpenCart Version 1.5.6.4 for this website and I noticed that on the backen product having much fields like UPC, SKU, ISBN,MPN and I tried to fill out on admin but they are not visible on the front.

Can anybody help me because I need to provide UPC, SKU, ISBN and MPN for each of the product. I tried to do some customization and able to display the SKU but the other information is not coming. 

Review the site here http://wheelchaironsale.com/newsite/index.php?route=product/product&product_id=52 and help me asap.

Thanks,

**Comment by CoverUp** [comment]
This is not a issue, is a personal requirement, you must use the forums instead. You can get an extension (free/paid) or hire a developer. Regards.

**Comment by tarun454** [comment]
Why should I hire developer when this feature is already coming in the back
end but not coming on frontend. So I this is issue and I have never seen
any shopping cart which has the field in the back end but don't display the
data on frontend.

Is there any fix or hack code? Need Core help?

**Comment by CoverUp** [comment]
Those fields are for backend only, most of them are there for updating purposes (batch) as identifiers.
There are a lot of fields in the admin area that never will be shown on the frontend, at least not as default.
Also you state you need a solution asap, thus you need a developer.
Also my comment is probably the only one that you will ever see here, that btw I had the courtesy to answer you, this kind of publish are just closed with no answer 99.9% of the time. (as stated in the rules)

**Comment by tarun454** [comment]
Strange... First time I use OpenCart and not happy with that...

**Comment by danielkerr** [comment]
yopu can add these types of details in the product description or attributes

**Comment by tarun454** [comment]
Hello Daniel,

But My client wanted to display like the other fields are coming Product Code, Brand etc.. And he will import the sheet with around 300 products and he is also right when the field is coming on backend then why it is not coming on front-end. He has used XCART for couple of site and there is no issue there, Unfortunately on my call he thinks to start on OpenCart also for small shop but we got the serious issue. Can you help to find the hack code and issue?

**Comment by tarun454** [comment]
Hello Daniel,

Even I try to add via Attributes it is saved but it does not display on front also. So when I checked it again then I noticed the attribute I added, is not available.. Strange?
