### ISSUE TITLE
Display notice even after I set display error NO

### ISSUE THREAD

**Issue by pranavpari** [opencart/opencart#4366]
I am creating a API for register and in response I am getting notice for some filed. I tried to set error_reporting(E_ALL & ~E_NOTICE); 
but not working. this API is working in older version.

**Comment by Jermim** [comment]
`error_reporting` won't effect because notice errors are displayed in `catalog/controller/startup/error.php`
http://php.net/manual/en/function.error-reporting.php

i think this need to be fixed

**Comment by danielkerr** [comment]
you have error reporting in php as well as in the oc.

**Comment by pranavpari** [comment]
Ok got it. I changed it from php file. Thanks for the help
