### ISSUE TITLE
Country names not localized

### ISSUE THREAD

**Issue by LaconicTranslator** [opencart/opencart#4369]
Table oc_country should have language_id column. Names of countries should be processed the same way as other language specific strings.

**Comment by danielkerr** [comment]
only in your opinion

**Comment by LaconicTranslator** [comment]
Of course it's up you to decide what is right for your project.
Yet, the problem of Country names localisation exists no only in my opinion.
[https://forum.opencart.com/viewtopic.php?f=20&t=125402](url)
and
[http://forum.opencart.com/viewtopic.php?f=20&t=26471](url)
For example English speaking users might not recognize Deutschland as Germany.
