### ISSUE TITLE
customer php error

### ISSUE THREAD

**Issue by aliscomputer** [opencart/opencart#4371]
parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /home/te/public_html/admin/controller/customer/customer.php on line 1105

how can i fix this error i have tried what people have shared. does any one have a good customer php that i can upload

**Comment by pekka2** [comment]
@aliscomputer 
You download here:
https://github.com/opencart/opencart/blob/master/upload/admin/controller/customer/customer.php
