### ISSUE TITLE
opencart 2.2.0.0

### ISSUE THREAD

**Issue by carl1957** [opencart/opencart#4372]
would anyone be able to help me please, and please bear in mind I'm not a programmer. I'm having a number of issues with the above, namely; I get an error message if I try to access the customer totals, I cannot seem to be able to activate international shipping and I keep having messages from potential customers that when they try to pay by paypal they get the message 'invalid client key'. the error message I get with the customer totals is Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /data01/c7641554/public_html/admin/controller/customer/customer.php on line 1103

**Comment by carl1957** [comment]
was I wrong to ask this on here, I've tried the contact but didn't receive a reply?

**Comment by pekka2** [comment]
@carl1957 
You download here:
https://github.com/opencart/opencart/blob/master/upload/admin/controller/customer/customer.php

**Comment by carl1957** [comment]
Brilliant, thank you. Any thoughts on the other two issues?

**Comment by pekka2** [comment]
@carl1957 
Your need update also these:
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/account/address.php
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/account/voucher.php
Is your incorrect extensions?

**Comment by carl1957** [comment]
Thank you very much Pekka, I think I'm using the correct extensions, they
are the ones that came with the 2.2.0.0.
