### ISSUE TITLE
Order can't be edited if product is not in stock

### ISSUE THREAD

**Issue by eka7a** [opencart/opencart#4374]
Even if there is no change in order products, order can't be edited if product is not in stock

**Comment by bluekable** [comment]
I recently found the same bug!

**Comment by danielkerr** [comment]
then set the order status to canceled so it adds the stock and deletes the coupon.

then try editing the order! then set the add a new order history and set the status to complete.

**Comment by bluekable** [comment]
Hi Danielkerr,

Thanks for your response, I haven't tried your workaround as I have not needed to edit any other orders yet however I must ask - Are there not potential problems with your workaround.

My concern is that while client no 1's order is in the "cancelled" state client no 2, on the catolog side, will see the stock as available and if they order it while you are busy with the process of editing the client no 1's order then you have to go back to client no 1 and apologise for having no stock of a product that they originally ordered. I know that chances of this happening are slim but I thought that it might still be a valid concern.

Also, the problem doesn't just affect adding and removing products from the order but in fact it doesn't allow any editing to be done on the order, so if a client chooses the wrong shipping method or something like that and then asks you to change it, you have to now cancel the whole order, edit the shipping method and then re-open the order.

Would it not be better to try and make it possible for an admin to edit an order regardless of stock status? 

My current workaround is to remove the code in catalog/controller/api/order.php - Line 448 that requires positive stock, then edit the order, then replace the code. This also is not a good workaround.

Regards
Bluekable
