### ISSUE TITLE
open cart: w/o success hint at doing marketing->mail->products

### ISSUE THREAD

**Issue by xieming1** [opencart/opencart#4375]
Hi,
My OC is v2.2.0.0 on Win7 with XAMPP. When I send email in Marketing->Mail. If "To" is products, mail indeed is sent correctly but no any hint like "To" is other options. I tested "All newsletter", "All customers" and "customer" that all of them have a success hint.

Regards,
Michael

**Comment by danielkerr** [comment]
it works!
