### ISSUE TITLE
Adding of new product option

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#4378]
Can do large(?) migration to option add to admin product page?
Current activities:
1. Something product is complete 150 option lines.
2. Admin want add yet 1 option, then product is 151 option.
3. Edit script `delete` at first `all options` and add` insert 151 options` to database.
Questions:
- Can this database script do different way?
- Can do different options `insert page` and options `edit page`? And in use sql UPDATE and INSERT in query?

**Comment by thephpx** [comment]
I also think this approach is wrong and should implement UPDATE query instead of DELETE and INSERT query.

**Comment by opencarteli** [comment]
The performance is not possible for update each options, Delete all and insert once can make sure your options data integrity.
