### ISSUE TITLE
addRoute is not defined and addModule is not defined

### ISSUE THREAD

**Issue by naujasdizainas** [opencart/opencart#4379]
OPC 2.2
Timestamp: 2016.05.17 13:51:06
Error: ReferenceError: addModule is not defined
Source File: /admin/index.php?route=design/layout/edit&token=PZoZyQiePHvqqVG8my4qKlMxRmgL42ko&layout_id=16
Line: 1

Timestamp: 2016.05.17 13:47:14
Error: ReferenceError: #addRoute is not defined
Source File: /admin/index.php?route=design/layout/edit&token=PZoZyQiePHvqqVG8my4qKlMxRmgL42ko&layout_id=14
Line: 1

**Comment by danielkerr** [comment]
your reporting old errors from the development version of oc!
