### ISSUE TITLE
Undefined in Form Data Admin New and Edit Order

### ISSUE THREAD

**Issue by eka7a** [opencart/opencart#4380]
![untitled](https://cloud.githubusercontent.com/assets/5789807/15322740/2cb51964-1c47-11e6-991d-168a9a5ed536.png)

**Comment by Jermim** [comment]
replaced this line (located in in `admin/view/template/sale/order_form.tpl`)
`data: $('select[name=\'payment_method\'] option:selected,  select[name=\'shipping_method\'] option:selected,  #tab-total select[name=\'order_status_id\'], #tab-total select, #tab-total textarea[name=\'comment\'], #tab-total input[name=\'affiliate_id\']'),
`
with
`data: $('#tab-total :input').serialize(),`

makes it work for me
