### ISSUE TITLE
OC 2.1.x: config_file_max_size is ignored for Uploads

### ISSUE THREAD

**Issue by sorinpohontu** [opencart/opencart#4385]
`System -> Settings -> Server`: `Max File Size` is setup to 300000, but it's possible to upload files of any sizes (eg, 10 MB).
Doing a search on entire project files, there is no reference to `file_max_size` beside Settings area.
`admin/controller/common/filemanager.php`: No reference
`admin/controller/catalog/download.php`: No reference

Is this setting ignored by OpenCart ? :)

**Comment by opencarteli** [comment]
It will fix on 2.2.0.0 ver. Thanks

**Comment by sorinpohontu** [comment]
* Same check should be performed on `public function upload()` from `admin/controller/catalog/download.php`, `admin/controller/tool/download.php`) and maybe in `admin/controller/extension/installer.php`
* Also, I think it's should be better to use the same code formatting as in other files (`if(` => `if (`, `} else {`)
