### ISSUE TITLE
Documentation error (requirements for 2.2.0.0 )

### ISSUE THREAD

**Issue by 4044ever** [opencart/opencart#4390]
from:
http://docs.opencart.com/requirements/

Error:
PHP 5.3+

Correct:
PHP 5.4 or better

Reason:
File:  2.2.0.0-compiled/vendor/react/promise/src/functions.php
It uses shorthand PHP, which is only supported from 5.4 onwards.

Error:
2.2.0.0 can't be installed

You can change "[]" to "array()", it will install then, but there might be more shorthand on other pages. Better change the minimum requirement to PHP 5.4

**Comment by danielkerr** [comment]
not required! 

File: 2.2.0.0-compiled/vendor/react/promise/src/functions.php

not even used!
