### ISSUE TITLE
some popup error coming with opencart order in opencart 2.2.0.0 

### ISSUE THREAD

**Issue by prabhatmech** [opencart/opencart#4392]
I have  problem , invoice is working with http . but wait its not working properly with https . 

it might be i have done something wrong with configuration file . 
I am also providing your config/.htaccess file .
please have a look and try to find the solutions .

//config.php ( inside admin) 

<?php
// HTTP
define('HTTP_SERVER', 'https://www.mysite.com/admin/');
define('HTTP_CATALOG', 'https://www.mysite.com/');

// HTTPS
define('HTTPS_SERVER', 'https://www.mysite.com/admin/');
define('HTTPS_CATALOG', 'https://www.mysite.com/');

// DIR
define('DIR_APPLICATION', '/home/mysite/public_html/admin/');
define('DIR_SYSTEM', '/home/mysite/public_html/system/');
define('DIR_IMAGE', '/home/mysite/public_html/image/');
define('DIR_LANGUAGE', '/home/mysite/public_html/admin/language/');
define('DIR_TEMPLATE', '/home/mysite/public_html/admin/view/template/');
define('DIR_CONFIG', '/home/mysite/public_html/system/config/');
define('DIR_CACHE', '/home/mysite/public_html/system/storage/cache/');
define('DIR_DOWNLOAD', '/home/mysite/public_html/system/storage/download/');
define('DIR_LOGS', '/home/mysite/public_html/system/storage/logs/');
define('DIR_MODIFICATION', '/home/mysite/public_html/system/storage/modification/');
define('DIR_UPLOAD', '/home/mysite/public_html/system/storage/upload/');
define('DIR_CATALOG', '/home/mysite/public_html/catalog/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'username');
define('DB_PASSWORD', 'password');
define('DB_DATABASE', 'database');
define('DB_PORT', '3306');
define('DB_PREFIX', 'oc_');

// Redirect users to the OpenCart installation url preventing cross-origin resource sharing policy errors.
if (strtolower($_SERVER['REQUEST_METHOD']) === 'get') {
$https = false;
if (isset($_SERVER['HTTPS']) && (($_SERVER['HTTPS'] == 'on') || ($_SERVER['HTTPS'] == '1'))) {
$https = true;
} elseif (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' || !empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] == 'on') {
$https = true;
}

$current_url = parse_url(($https ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . rtrim(dirname($_SERVER['PHP_SELF']), '/.\\') . '/');
$correct_url = parse_url($https ? HTTPS_SERVER : HTTP_SERVER);

if ($current_url !== $correct_url) {
if (dirname($_SERVER['PHP_SELF']) !== '/') {
$url = str_replace(dirname($_SERVER['PHP_SELF']), '', $_SERVER['REQUEST_URI']);
} else {
$url = $_SERVER['REQUEST_URI'];
}

$url = ($https ? HTTPS_SERVER : HTTP_SERVER) . ltrim($url, '/');

if (!headers_sent()) {
header('Location: ' . $url);
} else {
echo '<script>location = "' . $url . '";</script>';
}

exit;
}
}

// config.php inside public 

<?php
// HTTP
define('HTTP_SERVER', 'https://www.mysite.com/');

// HTTPS
define('HTTPS_SERVER', 'https://www.mysite.com/');

// DIR
define('DIR_APPLICATION', '/home/mysite/public_html/catalog/');
define('DIR_SYSTEM', '/home/mysite/public_html/system/');
define('DIR_IMAGE', '/home/mysite/public_html/image/');
define('DIR_LANGUAGE', '/home/mysite/public_html/catalog/language/');
define('DIR_TEMPLATE', '/home/mysite/public_html/catalog/view/theme/');
define('DIR_CONFIG', '/home/mysite/public_html/system/config/');
define('DIR_CACHE', '/home/mysite/public_html/system/storage/cache/');
define('DIR_DOWNLOAD', '/home/mysite/public_html/system/storage/download/');
define('DIR_LOGS', '/home/mysite/public_html/system/storage/logs/');
define('DIR_MODIFICATION', '/home/mysite/public_html/system/storage/modification/');
define('DIR_UPLOAD', '/home/mysite/public_html/system/storage/upload/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'username');
define('DB_PASSWORD', 'password');
define('DB_DATABASE', 'database');
define('DB_PORT', '3306');
define('DB_PREFIX', 'oc_');

// Redirect users to the OpenCart installation url preventing cross-origin resource sharing policy errors.
if (strtolower($_SERVER['REQUEST_METHOD']) === 'get') {
$https = false;
if (isset($_SERVER['HTTPS']) && (($_SERVER['HTTPS'] == 'on') || ($_SERVER['HTTPS'] == '1'))) {
$https = true;
} elseif (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' || !empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] == 'on') {
$https = true;
}

$current_url = parse_url(($https ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . rtrim(dirname($_SERVER['PHP_SELF']), '/.\\') . '/');
$correct_url = parse_url($https ? HTTPS_SERVER : HTTP_SERVER);

if ($current_url !== $correct_url) {
if (dirname($_SERVER['PHP_SELF']) !== '/') {
$url = str_replace(dirname($_SERVER['PHP_SELF']), '', $_SERVER['REQUEST_URI']);
} else {
$url = $_SERVER['REQUEST_URI'];
}

$url = ($https ? HTTPS_SERVER : HTTP_SERVER) . ltrim($url, '/');

if (!headers_sent()) {
header('Location: ' . $url);
} else {
echo '<script>location = "' . $url . '";</script>';
}

exit;
}
}

// .htaccess file 

# 1.To use URL Alias you need to be running apache with mod_rewrite enabled.

# 2. In your opencart directory rename htaccess.txt to .htaccess.

# For any support issues please visit: http://www.opencart.com

Options +FollowSymlinks

# Prevent Directoy listing
Options -Indexes

# Prevent Direct Access to files
<FilesMatch "(?i)((\.tpl|\.ini|\.log|(?<!robots)\.txt))">
 Order deny,allow
 Deny from all
</FilesMatch>

# SEO URL Settings
#Force https redirect

RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
# If your opencart installation does not run on the main web folder make sure you folder it does run in ie. / becomes /shop/

RewriteBase /
RewriteRule ^sitemap.xml$ index.php?route=feed/google_sitemap [L]
RewriteRule ^googlebase.xml$ index.php?route=feed/google_base [L]
RewriteRule ^system/download/(.*) index.php?route=error/not_found [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !.*\.(ico|gif|jpg|jpeg|png|js|css)
RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]

### If you get an "Internal Server Error 500" after enabling any of the following settings, restore the # as this means your host doesn't allow that.

# 1. If your cart only allows you to add one item at a time, it is possible register_globals is on. This may work to disable it:
# php_flag register_globals off

# 2. If your cart has magic quotes enabled, This may work to disable it:
# php_flag magic_quotes_gpc Off

# 3. Set max upload file size. Most hosts will limit this and not allow it to be overridden but you can try
# php_value upload_max_filesize 999M

# 4. set max post size. uncomment this line if you have a lot of product options or are getting errors where forms are not saving all fields
# php_value post_max_size 999M

# 5. set max time script can take. uncomment this line if you have a lot of product options or are getting errors where forms are not saving all fields
# php_value max_execution_time 200

# 6. set max time for input to be recieved. Uncomment this line if you have a lot of product options or are getting errors where forms are not saving all fields
# php_value max_input_time 200

# 7. disable open_basedir limitations
# php_admin_value open_basedir none

**Comment by opencarteli** [comment]
Can you list what your problem of not working properly with https

**Comment by danielkerr** [comment]
this issue has been fixed. he needs to use the url class from the master branch
