### ISSUE TITLE
Customer.php syntax error at admin/customer.php

### ISSUE THREAD

**Issue by amrigo** [opencart/opencart#4400]
Hi 

I am using version 2.2 and when trying to access admin/customer.phpi see the error

Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /public_html/opencart/admin/controller/customer/customer.php on line 1107

is there a fix

**Comment by CoverUp** [comment]
get the last version, this is already fixed on master.

**Comment by amrigo** [comment]
Thank You.
