### ISSUE TITLE
Hit error when login to admin

### ISSUE THREAD

**Issue by lawrence5199** [opencart/opencart#4403]
Currently I am using opencart 2.2.0.0 version, then I have installed the SSL and enforce the link to https:// in htacess file. After that I hit error below when login to admin panel

XMLHttpRequest cannot load : Response for preflight is invalid (redirect)

**Comment by opencarteli** [comment]
Please try to follow below setting if you are using https
http://www.fastcomet.com/tutorials/opencart2/enable-ssl

**Comment by danielkerr** [comment]
you also need to change the config.php for the catalog and admin.
