### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Kgombelian** [opencart/opencart#4404]
If I'm correct I found a little bug while trying to reset the password using  the "forgot password" method:

In the file controller/account/reset.php on line 26:
$this->model_account_customer->editPassword($customer_info['customer_id'], $this->request->post['password']);

The method editPassword in model/account/customer.php expects an email instead of customer_id.

public function editPassword($email, $password) {
   .....
}

So also change the query in the function getCustomerByCode(in model/account/customer.php) to SELECT the email instead of the customer_id

Instead of using email you could also fix this bug by using customer_id instead but the method editPassword is also used in the controller/account/password.php and in this file it passes email address

**Comment by dinumarathe** [comment]
Thank You so much bro...
