### ISSUE TITLE
image manager within information page issue

### ISSUE THREAD

**Issue by basboekema** [opencart/opencart#4410]
Hi there,

I have some issues with image manager......
It only adds the pictures that are direct /image folder.
When i try to add a picture from the.. lets say /image/mypicures folder it doesnt add the picture but i opens the picture in te browser.
Please give me some advise to fix this

Kind regards Bas

**Comment by 1309637127** [comment]
I have the same problem can anyone help to fix this? otherwise we can not upload products

**Comment by opencarteli** [comment]
Maybe download the new ver again. If you are using old ver.
Please change the code
`$('#modal-image').on('click', 'a.thumbnail',  function(e) {`
instead of
`$('#modal-image a.thumbnail').on('click', function(e) {`
