### ISSUE TITLE
Quantity into product and order float

### ISSUE THREAD

**Issue by danelsan** [opencart/opencart#4411]
Can the quantity of product and ordera are float mumbers.
In some case it's more usable

**Comment by Dotrox** [comment]
It would be nice!
I often hear such requests from OpenCart users. I mean, that quantity of product may be 1.5, 2.3 etc (not only float type instead of integer, but fractional number).

**Comment by danielkerr** [comment]
we had this before but hard to stop people buying for 0.5 and reducing the price by 50% for normal products. can you not just do 150mil. this would need to be a mod.

**Comment by danielkerr** [comment]
can you post this as a feature request. https://opencart.uservoice.com/forums/52387-general
