### ISSUE TITLE
catalog option is not showing in admin panel

### ISSUE THREAD

**Issue by priskyl** [opencart/opencart#4418]
Hello friends,

In my admin panel catalog option is not showing . And i am unable to edit all category. i have googled so many hour but not finding the solution.
Please help me to resolve this issue

**Comment by opencarteli** [comment]
Maybe you try to reinstall the opencart
`http://docs.opencart.com/installation/`

**Comment by danielkerr** [comment]
use the contact us form on the opencart.com web site. your issues are not dev related.
