### ISSUE TITLE
No Seo URLs when ssl is enabled?

### ISSUE THREAD

**Issue by kvailas** [opencart/opencart#4422]
Opencart version 2.0.1.1

SSL is enabled on admin & ssl is working OK navigating at https://
vhost is OK (same works for another installation on same server)
htaccess is the opencart default for that version uncommented as .htaccess

we got a 403 error when trying to reach a seo url of any kind either product,information etc. 
Could it be server related or opencart related?

config.php
```
define('DS',DIRECTORY_SEPARATOR);

$subDirFolder = '';
$ssl = TRUE;
$https = 'http://';
if($ssl)
    $https = 'https://';

define('HOST',$_SERVER['HTTP_HOST']);
define('SUB_DIR_FOLDER',$subDirFolder);
define('SITE_PATH',$_SERVER['DOCUMENT_ROOT'] . DS . SUB_DIR_FOLDER);

// HTTP
define('HTTP_SERVER', 'http://'. HOST . '/' . SUB_DIR_FOLDER);
define('HTTP_IMAGE', HTTP_SERVER . 'image/');
define('HTTP_ADMIN', HTTP_SERVER . 'admin/');

// HTTPS -
define('HTTPS_SERVER',$https. HOST . '/' . SUB_DIR_FOLDER );
define('HTTPS_IMAGE', HTTPS_SERVER . 'image/');
```

**Comment by stamster** [comment]
Do you run on Apache or Nginx?
OS?
Do you use load balancer?

**Comment by danielkerr** [comment]
did you set RewriteBase / in htacess files?
