### ISSUE TITLE
Can´t access Customer menu from admin panel

### ISSUE THREAD

**Issue by sistemasazulana** [opencart/opencart#4428]
Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /home/azucuenta2/public_html/intranet/admin/controller/customer/customer.php on line 1105

pretty much the same in the address book in the storefront

**Comment by danielkerr** [comment]
this has been fixed many times! do some searching before posting an issue!

**Comment by sistemasazulana** [comment]
sorry man, i´m new at this, and i just feel the need to post something, jeje, actually it was first post ever on github, thanks , and by the way , i just foud the solution here https://github.com/opencart/opencart/issues/4106
