### ISSUE TITLE
Coupon is not working as expected when coupon offers free shipping

### ISSUE THREAD

**Issue by samirkumardas** [opencart/opencart#4429]
In OC 2.x, a coupon with free shipping enabled, can not be applied before selecting shipping method. If I did not choose shipping method during checkout, the applied coupon got lost whenever I refresh the page.

In OC 1.5.x, it would work as expected. I could apply coupon (with free shipping - yes) anytime whatever I chosen shipping method or not.

Actually following line is reseting applied coupon every time if discount amount is zero. But it should not because discount amount will not available in  the cart page unless I choose a shipping method during checkout page.

> File:  catalog/model/total/coupon.php 
> Line: 182
> Code: unset($this->session->data['coupon']);

I think it should not reset when coupon type is free shipping. Something like:

```
if(!$coupon_info['shipping'])  {
    unset($this->session->data['coupon']);
 }
```

**Comment by iSaulius** [comment]
Thank You!

**Comment by opencarteli** [comment]
Please look at master ver line 153, if have a checking there already

**Comment by samirkumardas** [comment]
Yes I saw that line. But I am talking about line 182.  Okay, I did followings:

1. First I added a product to my cart. 
2. Then I applied a coupon which offer free shipping.
3. Now I tried to checkout but during checkout my coupon got lost. I did not get free shipping at all and it showed that there was no coupon applied.

Shouldn't it remain valid during checkout when I apply coupon before choosing delivery method?

Noted that I saw `catalog/model/total` has been move in `catalog/extension/total`

**Comment by danielkerr** [comment]
you mean is not working how you expect it!

im not sure a free shipping coupon should work until a product that requires shipping is added to the cart.

**Comment by samirkumardas** [comment]
:) It is not my expectation.  Well, it would work in OC 1.5.x

Yes I have added product to the cart that requires shipping first, then I applied coupon. But it does not sustain my coupon during checkout

**Comment by danielkerr** [comment]
ok added
