### ISSUE TITLE
text_ appearing on header and footer

### ISSUE THREAD

**Issue by cpltown** [opencart/opencart#4430]
Using OpenCart 2.2.0, after uploading from localhost to server. All my links on the header and footer are displayed as such "Text_***"

Admin page cannot load config default.

the default config files on the main and admin are edited as per the server requirements.

Site works perfectly on localhost, but after ftp to server. its not working.,
Any help?
![image](https://cloud.githubusercontent.com/assets/19731039/15779869/8cc1490a-29a7-11e6-8c76-171ca0a5ddfe.png)

**Comment by munirasim** [comment]
The issue is with LANGUAGE FILES.

text_**** are defined inside language files and either those files are corrupt or not loaded properly. You may try uploading just LANGUAGE folders (catalog+admin) again.

**Comment by cpltown** [comment]
Tried, but it didn't work. Had to do a fresh installation.

**Comment by opencarteli** [comment]
I have visit this website http://www.computerplanet.co.ke/
is it solved already?

**Comment by cpltown** [comment]
Fresh installation on server did the trick. Uploading language files did not work.
