### ISSUE TITLE
Marketing - Mail not sending

### ISSUE THREAD

**Issue by i2Paq** [opencart/opencart#4432]
I have a clean 2.2.0.0 install and cannot find a solution here on GitHub.

I am not able to send a mail through the website using the marketing-mail feature, the send mail button does nothing, please check this if only my site is affected or not.

@danielkerr Please, if you close this then point me towards te solution as I cannot find it on GitHub.

**Comment by i2Paq** [comment]
By accident I've found the solution:

[quote="florinsith"]If you mean the admin mail page, then edit the file admin/view/template/marketing/contact.tpl, and in the file, find and delete the line:
[code]$('textarea[name=\'message\']').val($('#input-message').code());[/code][/quote]

**Comment by osworx** [comment]
There is also another bug in the current code (sending emails by pruchased products):
https://github.com/opencart/opencart/pull/4434

**Comment by i2Paq** [comment]
@osworx Thanks!

**Comment by othink13** [comment]
hai there... i got the same problem, i can not send email from, have you get resolved another bug#4434 ?

**Comment by danielkerr** [comment]
i just tested using gmail and it works fine. you need to set app password maybe.
Version 2.2.0.1b
