### ISSUE TITLE
in multistore shared session internet explorer not works

### ISSUE THREAD

**Issue by sandeep-pateriya** [opencart/opencart#4433]
Hello,
I have develop a multistore in opencart with different domain names.
I have active shared session in it. 
In all other browser when user add a product on a store it also display in cart in other store.
But this not work in internet explorer , i am checking in IE 11.

**Comment by CoverUp** [comment]
Thus is it an OC issue or a IE issue?

**Comment by danielkerr** [comment]
im closing the ticket because you have provided no useful information to go from such as OC version.

the latest version has the cart in the db so should work across multiple stores provided the session ID is the same or the customer logs into one of the stores.
