### ISSUE TITLE
2.2.0.1b breaks whilst installing 3rd party Theme - Journal Theme 2

### ISSUE THREAD

**Issue by stockmaster** [opencart/opencart#4435]
While Attempting to install the latest Master build from GitHub on a sandbox i noticed that installing any theme will break the installation.

In this case Journal Theme 2

Breaks with error:
Fatal error: Call to a member function get() on a non-object in /home/gsadesig/public_html/system/engine/front.php on line 45

Granted this is a Theme creator issue, just keeping a Log of the situation.
Wonder what kind of other extensions might suffer from the same or similar issue

Regards

**Comment by danielkerr** [comment]
it depends what version your Journal Theme was made for. I did some texting with the new theme sytem and did set it up so it was compatible with older 2.x themes

**Comment by stockmaster** [comment]
Agreed, i notified the theme creator awaiting for their answer.
However wanted to let you know that in fact the latest build - of one of which is the most sold theme for Opencart, breacks on 2.0.0.1.b

I think is relevant information for you to keep aware of ? maybe :)

**Comment by davidfranks** [comment]
@stockmaster Journal only supports stable releases not beta releases.

**Comment by stockmaster** [comment]
@davidfranks Granted, that's not the point though. 
The point is, 2.0.0.1 will break a lot of things, so my question was... what ELSE will it break.
This means or might mean, upgrading will be a nightmare. again....

**Comment by davidfranks** [comment]
@stockmaster not if you use @qphoria new upgrade script which is now built into the core. All upgrades should be pretty smooth now.

**Comment by stockmaster** [comment]
@davidfranks Time will tell.... i waited 1 year, wont wait anylonger. swapping
