### ISSUE TITLE
SMTP-Settings cleaned

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#4450]
Because customers are sometimes very stupid, some of them do not know what they are doing.
Because of that, a customer of mine set the SMTP settings - but wrong.
Because the port number was saved with an extra space - therefore no email were sent!

Therefore I recommend either to store these settings cleaned (withount any space) or clean them in the mail.php script (whatever you prefer).
Otherwise with such stupid entries, **mail.php** will always trigger an error like: 
`PHP Notice:  A non well formed numeric value encountered in /var/www/not_public/system/library/mail.php on line 168`

The fatal on that 'bug' is, the store tells the customer that the mail is sent!

**Comment by opencarteli** [comment]
In your refer file, it showed throw exception already
`throw new \Exception('Error: ' . $errstr . ' (' . $errno . ')'); on line 169`
