### ISSUE TITLE
page does not refresh after deleting product on checkout/cart

### ISSUE THREAD

**Issue by rippersvk** [opencart/opencart#4453]
When you delete product on page  checkout/cart minicart updates itself, but page does not.

Can be fixed by updating cart.delete in catalog/view/js/common.js

**Comment by opencarteli** [comment]
I have tried delete products on minicart, the cart page have update at the same time.

**Comment by danielkerr** [comment]
the page woudl nt refresh if you are using SEO mod that alters the cart page url.
