### ISSUE TITLE
fixed voucher in order edit admin 

### ISSUE THREAD

**Issue by spacedog4** [opencart/opencart#4455]
in opencart 2.1.0.2

When editing the order and you gonna apply a voucher it returns an error, Internal server error.

catalog\controller\api\voucher.php
`$this->load->model('total/coupon');`

becomes
`$this->load->model('total/voucher');`

**Comment by opencarteli** [comment]
It should be
$this->load->model('total/voucher');

**Comment by spacedog4** [comment]
Yeah, and if you download the 2.1.0.2 version from the site, you gonna see that it's wrong

**Comment by opencarteli** [comment]
Please update to new version or change your code to solved this problem, since 2.1.0.2 version will not have any update process.
