### ISSUE TITLE
Errors on "common/home - index.php"

### ISSUE THREAD

**Issue by Hyp3rionM4x** [opencart/opencart#4458]
Hello, just installed a fresh set of OpenCart today from GitHub here.

Errors given on index.php file:

Warning: Invalid argument supplied for foreach() in C:\Winginx\home\foodbox\public_html\system\engine\loader.php on line 50

Notice: Undefined property: Proxy::getTotal in C:\Winginx\home\foodbox\public_html\catalog\controller\common\cart.php on line 37

ideas? Please note customer URL in admin menu-link is broken also, it was on my version for some reason, even tho i got told it was fixed by now?

Hoping some support soon :)
Thanks! :)

**Comment by danielkerr** [comment]
yes because dev version use the one from opencart.com
