### ISSUE TITLE
admin -> Events -> Edit the events "voucher" -> i dont have permission

### ISSUE THREAD

**Issue by Hyp3rionM4x** [opencart/opencart#4459]
Hello, found another error that is something else, so i decided to make a new "issue" instead of typing in the already one i made earlier today.

Not sure if this is a part of the code, but when i try to hit the edit button of an Event... i get this error:

 Warning: You do not have permission to modify extensions!

Is this a part of the code for some reason? Thanks again! :)

**Comment by danielkerr** [comment]
there is no edit button on the events page

**Comment by danielkerr** [comment]
if not permission then added it via user goups
