### ISSUE TITLE
Theme structure proposal

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#4460]
I recommed this change to theme structure:

1. Copy folder catalog/view/theme/default to folder 'view' and rename to 'theme_default'.
2. Then remove folder catalog/view/theme.
3. Change DIR_TEMPLATE path:
  define('DIR_TEMPLATE', 'http://www.yourstore.com/catalog/view/');
4. Change file catalog/controller/event/theme.php script:
```
		if ($this->config->get('config_theme') == 'theme_default') {
			$directory = $this->config->get('theme_default_directory');
		} else {
			$directory = $this->config->get('config_theme');
		}
```
to:
`			$directory = $this->config->get('config_theme');`

and this line
`			$view = 'default/template/' . $view;`
change to:
`			$view = 'theme_default/template/' . $view;`

Ps. Setting `theme_default_diectory` can remove form admin > theme, or edit script to file admin/controller/theme/theme_default.php:
```
	     $directories = glob(DIR_CATALOG . 'view/theme/*', GLOB_ONLYDIR);

		foreach ($directories as $directory) {
			$data['directories'][] = basename($directory);
		} 
```
change to:
```
		$directories = glob(DIR_CATALOG . 'view/*', GLOB_ONLYDIR);

		foreach ($directories as $directory) {
		     if(strpos($directory,'theme_')){
			  $data['directories'][] = basename($directory);
			 }
		
		}
```

**Comment by CoverUp** [comment]
so in short, get rid of theme folder?
thus, theme names will be in the same level as javascript?

**Comment by danielkerr** [comment]
ive just done soem massive changes with the extensions so that they are all under one sub folder.

**Comment by danielkerr** [comment]
yiour systerm wont work. i already tried it

**Comment by warriorjackets** [comment]
Hey I need your suggestions guys. This is my website: https://www.warriorjackets.com/. I just need your help on how can I improve it. As lots of visitors are facing some issues. The most common is the speed of the page.

**Comment by pekka2** [comment]
@danielkerr 
I am tested this in version 2.2.0.0, there me worked.
