### ISSUE TITLE
Shipping method name can not contain a dot

### ISSUE THREAD

**Issue by kuusekas** [opencart/opencart#4461]
Through all OC 2.x there is a problem with shipping_method handling in checkout process.
If my shipping method name does contain a dot, it will not be handled as valid option.
That's due to the data exploding procedure in class **_ControllerCheckoutShippingMethod_** function **_save()_**, located in _/catalog/controller/checkout/shipping_method.php_.

Currently it's done like this (version 2.2.0.0, row 117):
```php
$shipping = explode('.', $this->request->post['shipping_method']);
```

But in my opinion it should be handled something like this:
```php
$dividerPosition = strpos($this->request->post['shipping_method'], '.');
$shipping = array(
	substr($this->request->post['shipping_method'], 0, $dividerPosition),
	substr($this->request->post['shipping_method'], $dividerPosition + 1)
);
```

**Comment by CoverUp** [comment]
true, but why u want a dot in the name?
it worth add 4 lines of code instead 1 just for this?

**Comment by kuusekas** [comment]
but why are you trying to restrict me to not have a dot in the name of the shipping method?
this is absolutely not the correct way to approach this issue.

the code was written on the fly to give just an example, that is why it is 3 additional lines.
It is easily done in one additional line of code with something like this:
```php
$shippingPostDataArray = explode('.', $this->request->post['shipping_method']);
$shipping = array($shippingPostDataArray[0], implode('.', array_slice($shippingPostDataArray, 1)));
```

**Comment by kuusekas** [comment]
or even better like this:
```php
$shipping = explode('.', $this->request->post['shipping_method']);
$shipping[1] = implode('.', array_slice($shipping, 1));
```

**Comment by danielkerr** [comment]
any type of setting code should be lowercase a-z and 0-9
