### ISSUE TITLE
Error Undefined In Version 2.2.0.0

### ISSUE THREAD

**Issue by DARKVALE** [opencart/opencart#4463]
When i log into admin i get 

Error Undefined  

When using www

when i use without the www i don't get the error.

Please can anyone help?

**Comment by moosen2012** [comment]
The same question with u

**Comment by danielkerr** [comment]
only use one url structure. you should have a redirect on your htaccess

**Comment by txyaaj** [comment]
I encountered the same error while accessing the orders module.  It loads after I clicked OK, but thrown the same error when I tried to view/edit the order.   It also loaded ok for viewing, but I can't update the order to shipped - got the same error.
