### ISSUE TITLE
Parse Error on Line 1

### ISSUE THREAD

**Issue by cpltown** [opencart/opencart#4468]
Parse error: syntax error, unexpected 'ControllerCustomerCustomer' (T_STRING) in /home/xxx/public_html/admin/controller/customer/customer.php on line 1

The code is
<?php

class ControllerCustomerCustomer extends Controller 
	{ private $error = array(); public function index() 
	{ $this->load->language('customer/customer'); 
	$this->document->setTitle($this->language->get('heading_title'));
	$this->load->model('customer/customer'); $this->getList(); } public function add() 
	{ $this->load->language('customer/customer'); $this->document->setTitle($this->language->get('heading_title')); 
	$this->load->model('customer/customer');

**Comment by danielkerr** [comment]
dont save these files using notepad or any other made micorsoft product. delete the file and reupload one from the opencart download.

**Comment by cpltown** [comment]
I did that, IT gives me Parse error: syntax error, unexpected "&&" (T_BOOLEAN_AND), expecting ")" in /home/xxx/public_html/admin/controller/customer/customer.php on line 1105.

**Comment by cpltown** [comment]
@danielkerr 
I did that, IT gives me Parse error: syntax error, unexpected "&&" (T_BOOLEAN_AND), expecting ")" in /home/xxx/public_html/admin/controller/customer/customer.php on line 1105 #

**Comment by cpltown** [comment]
@danielkerr 
I did that, IT gives me Parse error: syntax error, unexpected "&&" (T_BOOLEAN_AND), expecting ")" in /home/xxx/public_html/admin/controller/customer/customer.php on line 1105 #4468
