### ISSUE TITLE
State JHARKHAND  is missing when selecting Country as India

### ISSUE THREAD

**Issue by SANTANU51** [opencart/opencart#4472]
Hi,
I am not able to find the state jharkhand for country India.
How to add this state?

**Comment by thephpx** [comment]
Hi Santanu51,

I am not sure if jharkhand is a state of India or not but if you want to add it as an state you will need to add an entry into oc_zone table. Be sure to give proper country_id for india, while adding the new zone. 

In my case India's country_id is 99 so add new entry on oc_zone with country_id = 99, Name = "Jharkhand", Code = {2 Character long - Whatever Applicable}, Status = 1

Hope it helps,

**Faisal Ahmed**
