### ISSUE TITLE
Issue with multiple languages when using SSL OpenCart 2.2.0

### ISSUE THREAD

**Issue by FoZo** [opencart/opencart#4488]
Hello,

for version 2.2.0 when you are using SSL for the website, the URL to switch between languages is not pointing ssl (https) and it should:

`<input type="hidden" value="http://testdomain.com/index.php?route=common/home" name="redirect">`

I test it with new installation.

**Comment by danielkerr** [comment]
all the issues you have reported are user error ones. this is a issue tracker for developers!

**Comment by FoZo** [comment]
Hi,

sorry for that, but where should I report them?
In the forum I saw that "BUGs should be posted at the OpenCart GitHub Issue tracker."
I test it with base installation with no extra addons or anything ( I tried with nginx and apache2 ).
The only difference is that I use SSL connection.
Those issues looks like bugs for me.
