### ISSUE TITLE
When adding addtional addresses for logged in user I'm getting following error which also get logged in the backend.

### ISSUE THREAD

**Issue by Thorny-Twig** [opencart/opencart#4498]
Opencart v 2.2.0.0 - As a logged in user, when adding addtional addresses to profile, I'm getting following error shown below on a white page with no further content. The error message also gets logged in the backend. When I click the _"Continue"_ button, the new delivery/billing address gets added but I do not get returned to the address page showing list of previous and updated addresses with bootstrap header message in green informing of a _" Your address has been successfully inserted"_  Error message is popping up when running off a live hosted web server. Odd thing is it's working in my Cloud9 enviroment, so I'm a bit lost on this.

_Warning: Cannot modify header information - headers already sent by (output started at /usr/local/pem/vhosts/159856/webspace/httpdocs/upload/catalog/controller/account/address.php:1) in /usr/local/pem/vhosts/159856/webspace/httpdocs/upload/system/library/response.php on line 12_

**Comment by danielkerr** [comment]
the white page means you dont have php errors set to display in your php settings.

address.php:1

means you have edited the code with a Microsoft product and its put its own non standard header in the file.

delete the file and re upload. 

/upload/catalog/controller/account/address.php
