### ISSUE TITLE
Suggestion - Logging out a user

### ISSUE THREAD

**Issue by Thorny-Twig** [opencart/opencart#4500]
This is only a suggestion for OCv2.2.0.0, would it be helpful to have a more visually prominent **Logout** button popup/appear on the same bar as "Telephone Numer | My Account | Wish List (0) | Shopping Cart | Checkout" nav bar when registered user is logged in. Now I know the option to logout is shown under "My Account" dropdown but it's a bit hidden and inconvenient for the not so regular registered users. 

Just imagine you had a large promotional event and a few Internet Kiosks setup where customers new and registered (outside the comfort of their own homes) wanted to log in and purchase special items on sale for instance. It's a bit of a job to get a registered logged in user logged out quickly while confidently indicating to that same customer who placed the order that the next customer won't be able to see all their personal details. Now, I know what your going to say, tell them to do it on their smart phones but Murphy's Law - "Anything that can go wrong, will go wrong."

While on that scenario another suggestion would be to have a logout button along side the continue button in the "example-shop.com/upload/index.php?route=checkout/success" page when your order is successfully placed. Maybe a information message indicating "Do you wish toLog Out of this shopping visit"

Anyway it's just a suggestion. Critic away.

**Comment by opencarteli** [comment]
Thanks for your suggestion.
