### ISSUE TITLE
Captcha Code

### ISSUE THREAD

**Issue by kazcoclothing** [opencart/opencart#4501]
When using capture, the code needs to be positioned differently, as browser autofill boxes cover the captcha code and customer cannot read it. As soon as customer enters the first letter or number of the code and the customer has typed that digit as the first digit in a previous form, the browser 'autofill box' blocks the captcha code and it cannot be read. Many people use the form auto fill option in their browser.
Can we please have the code positioned above the entry box or lower than it is now?

**Comment by danielkerr** [comment]
nothing to do with position. most capchas are at the end of the form. set autocoplete attribute to false.
