### ISSUE TITLE
Error undefined (OC 2.2.0 New Install)

### ISSUE THREAD

**Issue by txyaaj** [opencart/opencart#4502]
I posted this on an old issue (#4463) with the same error, but realized it was closed.  Hopefully this won't cause any problems by reposting it as a new issue.

I encountered the error  "error undefined" while accessing the orders module. It loads after I clicked OK, but thrown the same error when I tried to view/edit the order. It also loaded ok for viewing, but I can't update the order to shipped - got the same error.  It appears to be throwing the same error whenever I click on any function.

**Comment by danielkerr** [comment]
do some reseach. im sure this is related to ssl.

**Comment by pekka2** [comment]
@txyaaj 
In version 2.2.0.0 id few issue. 
file admin/controller/sale/order.php.
line 318, 481 and 570:
`$data['store_url'] = $this->request->server['HTTPS'] ? HTTPS_CATALOG : HTTP_CATALOG;`
this start issue, when constant HTTPS_CATALOG start: http:// 

lines 851-853:
```
if( $this->server['HTTPS'] && substr($order_info['store_url'],0,5) !='https' ){
			   $data['store_url'] = $this->request->server['HTTPS'] ? str_replace("http", "https", $order_info['store_url']) : $order_info['store_url'];
}
```
This start issue, when SSL is disabled or SSL is enabled and store url start 'https'. These is fixed to github.

**Comment by danielkerr** [comment]
issue  (#4463) has nothing to do with this problem!

**Comment by danielkerr** [comment]
@pekka2 so your fix is rather than putting the correct url in the config.php just do a replace.

**Comment by danielkerr** [comment]
also its a stupied fix! how is it going to work if the store url is on a different domain name!

**Comment by danielkerr** [comment]
actually your right. if the store is set by the order table.

**Comment by danielkerr** [comment]
another issue is if the domain name gets moved.

**Comment by txyaaj** [comment]
I have tied to set the config files to what's been suggested on various posts on the forum, but as long as I have SSL on, it will throw the error.  When it does, all product images are missing.

**Comment by muthukumar005** [comment]
I'm facing the same problem. anyone pls solve my issue?

**Comment by danielkerr** [comment]
the issue is already fixed on the master branch

**Comment by muthukumar005** [comment]
I'm new to opencart. Could you please tell where I can find this master branch?

**Comment by meckdnb** [comment]
@danielkerr  How did you solve it?

**Comment by arnisjuraga** [comment]
@meckdnb - can you try to upgrade to latest master branch?

**Comment by meckdnb** [comment]
@arnisjuraga  what is master branch?

**Comment by arnisjuraga** [comment]
@meckdnb this source code: https://github.com/opencart/opencart/tree/master/upload

**Comment by DeCezar** [comment]
Hi Guys had a similar issue maybe this helps, firstly go into the file directory of your website once there you will see .htaccess.txt or .htaccess (if you have .htaccess.txt change to .htaccess) in this edit the file in the file you should see 

RewriteBase /
RewriteRule ^sitemap.xml$ index.php?route=feed/google_sitemap [L]
RewriteRule ^googlebase.xml$ index.php?route=feed/google_base [L]
RewriteRule ^system/download/(.*) index.php?route=error/not_found [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !.*\.(ico|gif|jpg|jpeg|png|js|css)
RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]


simply add the following at the bottom:
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]

So it should like this 

RewriteBase /
RewriteRule ^sitemap.xml$ index.php?route=feed/google_sitemap [L]
RewriteRule ^googlebase.xml$ index.php?route=feed/google_base [L]
RewriteRule ^system/download/(.*) index.php?route=error/not_found [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !.*\.(ico|gif|jpg|jpeg|png|js|css)
RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]


save the file.

Hope this solves your problem as myn was abit different
