### ISSUE TITLE
in Admin > Localisation > Currencies in Edit Currency popup of Code is not displayed

### ISSUE THREAD

**Issue by evgenekorolev** [opencart/opencart#4511]

**Comment by opencarteli** [comment]
What mean of popup of Code is not displayed.
There will not have any popup in edit page

**Comment by evgenekorolev** [comment]
in Admin the version of OS 2.2 does not display pop-up window with text: "Do not change if this is your default currency. Must be valid xe.com ISO code" when you hover.
<img width="456" alt="screen" src="https://cloud.githubusercontent.com/assets/18613768/16108965/fecb27b2-33ae-11e6-84fb-ee80a3617963.png">
