### ISSUE TITLE
2.2.0.0 buggy work of the new model loading system

### ISSUE THREAD

**Issue by igorokb** [opencart/opencart#4514]
In some conditions the following exception is thrown:

> Exception: Error: Could not load model ! in /var/www/devhost.sergey/html/system/storage/modification/system/engine/loader.php on line 146

This one was received in particular when trying to delete several products at a time (via admin panel of course). Although the issue was not reproducible in another environment on the same opencart version (both were clean opencart copies).

While going through the code the following magic was noticed. Here are a couple of screenshots made during debugging step by step with Xdebug:

![one step before the $route variable will be broken](https://cloud.githubusercontent.com/assets/6459930/16082600/ada4f186-331a-11e6-957a-9a0f10aba5aa.png)

As you can see the $route variable is fine and contains correct route string

![this step broke the $route variable](https://cloud.githubusercontent.com/assets/6459930/16082688/02db9da8-331b-11e6-9102-9150b69fce7f.png)

On the step some unexpected happens.
Obviously when another product from selection is getting deleted the $route is incorrect, which causes the error.

Most likely the "magic" happens due to usage of variable references (purpose of using of them there is not clear frankly speaking. Besides a reference defined for the input parameter).

Removing of those references resolves the issue.

**Comment by danielkerr** [comment]
you have not explained this issue properly at all.

> Obviously when another product from selection is getting deleted the $route is incorrect, which causes the error.

deleting a product does not effect the route!

**Comment by igorokb** [comment]
By saying about purpose I was referring to the ampersand sign in the code:

`$result = $registry->get('event')->trigger('model/' . $route . '/after', array_merge(array(&$route, &$output), $args));
`

Sorry if my explanation wasn't enough clear for you. We've investigated the issue further and came up with the following:

The issue appears on PHP 5.3, meanwhile on PHP 5.4+ it is ok.
Please see the code snippet which is a short reflection of the event system process (you can try it in sandbox http://sandbox.onlinephpfunctions.com/code/19beca3ff08d457b5ef4df82c1fa424bb088a936):

```
$route = 'route';
$c = array(&$route);

function eventHandler($param) {
    $param = 'new value';
}

var_dump($c);
call_user_func_array('eventHandler', $c);
var_dump($c);

```

This will give you different results in PHP 5.3 and PHP 5.4

For PHP 5.3 it will be:

```
array(1) {
  [0]=>
  &string(5) "route"
}
array(1) {
  [0]=>
  &string(9) "new value"
}
```

For PHP 5.4 it will be:

```
array(1) {
  [0]=>
  &string(5) "route"
}
array(1) {
  [0]=>
  &string(5) "route"
}

```

Hope it is enough to see the problem
