### ISSUE TITLE
Permissions for extensions not working well

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#4516]
When you moved all extensions in extenison folder, the route for extensions changed in three parts route, but in startup permission file the system checks only for two parts route. Are you will change this file for checking three parts route or you planning different way for checking for extensions permission.

**Comment by opencarteli** [comment]
I don't what you mean, you dont need move everything as well
http://docs.opencart.com/installation/

**Comment by danijelGombac** [comment]
Daniel move all extensions. now route change from 

analytics/google_analytics

to 

extension/analytics/google_analytics

If you look in admin/controller/startup/permission.php there is only two part:

```
if (isset($part[0])) {
		$route .= $part[0];
}

if (isset($part[1])) {
	$route .= '/' . $part[1];
}

```

**Comment by danielkerr** [comment]
should be ok now

**Comment by danijelGombac** [comment]
Permissions still not working well. Now it checks if **extension/** is in array, but is always false.

```
// If a 3rd part is found we need to check if its under one of the extension folders.
			$routes = array(
				'extension/analytics',
				'extension/captcha',
				'extension/feed',
				'extension/fraud',
				'extension/module',
				'extension/payment',
				'extension/shipping',
				'extension/theme',
				'extension/total'
			);
			
			if (isset($part[2]) && (in_array(substr($this->request->get['route'], 0, 10), $routes))) {
				$route .= '/' . $part[2];
			}
```
