### ISSUE TITLE
Add multilingual summernote and calendar (datetimepicker)

### ISSUE THREAD

**Issue by evgenekorolev** [opencart/opencart#4520]
Could you make a calendar (datetimepicker) and summernote editor multilingual in OC? So that when you change the language from EN, such as RU changed the calendar language (in Admin and Catalog) and summernote language (in Admin)?
On screenshot i use alternate OC 
![screen](https://cloud.githubusercontent.com/assets/18613768/16118433/bdd5c394-33df-11e6-9019-c53d5601cc60.jpg)

**Comment by MohsenKoohi** [comment]
Yes it is possible. You need just read the language variable in the session  in your controller, and specify which language should be selected for calender. For SummerNote, I don't think it support multi lingual, thus it is better to use TinyMCE instead.

**Comment by danielkerr** [comment]
done the datepicker still need to finish summernote

**Comment by slva2000** [comment]
For ru include language
in **opencart.js** (admin view)
add:
`lang:'ru-RU',`
before:
`fontSizes: ['8', '9', '10', '11', '12', '14', '16', '18', '20', '24', '30', '36', '48' , '64'],`

and be sure that file:
admin\view\javascript\summernote\lang\summernote-ru_RU.UTF-8,ru_RU,russian-RU_RU.UTF-8,RU_RU,RUSSIAN.min.js
exist
