### ISSUE TITLE
OC 2.2.0.0 Admin products listing hanging on 100,000 products - fine in Front end

### ISSUE THREAD

**Issue by xmanflash** [opencart/opencart#4521]
Not sure how to report this, except that we have imported via CSV over 100,000 products in about 50 categories and clicking on the products in admin hangs the MySql server.

I have run this on 2 very powerful servers (8G ram, 16 processors etc) and same result.

We had seen this issue in an older oscommerce shop and discovered that the query was filling/killing the MySql cache, and we just needed to turn off mySql caching for the products listing query.

I will provide any information necessary to help inquiries, but from my POV (and I run a few happily working OC2 stores) this looks very much like a bug - mainly because it all works really well (quickly)  on the Front end, including product search.. which I assume means its not an indexing issue.

Cheers,
Pete

**Comment by danielkerr** [comment]
pm me your admin login details on the opencart forum. i suspect theres somethign thats causing that your not telling me. maybe 1050 options on each product.

**Comment by xmanflash** [comment]
Hi Daniel, thanks ..  There are no options yet, but there may be something else..  When I work out how to PM you I will.. (new to GitHub)

**Comment by danielkerr** [comment]
opencart forum

**Comment by danielkerr** [comment]
if you can add this commit to your site i have put some debug code to get the execution time for each controller thats loaded.

**Comment by danielkerr** [comment]
i think this is more of 3rd party estension problem but will still take a look at your site.

**Comment by xmanflash** [comment]
Hi Daniel,  OK - not sure how to add the commit - I cant see any code form you to me here?  Sorry -
