### ISSUE TITLE
Newbie spotted two issues for fixing customers.php and address.php

### ISSUE THREAD

**Issue by charlotteki** [opencart/opencart#4522]
Love opencart so far but there were two bugs I spotted on a new install of 2.2.0.0. so I am just wanted to let you know.

Parse error in the customers.php file

i experienced a syntax error when I was trying to look at the customers list in the backend

`Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in .../admin/controller/customer/customer.php on line 1105`
I found a solution here http://stackoverflow.com/questions/35939201/syntax-error-unexpected-t-boolean-and-expecting-in-opencart-when-cl

It was that the parentheses were in the wrong place… so I changed

`!empty($custom_field['validation'] && $custom_field['location'] == 'address'))`
to

`!empty($custom_field['validation']) && $custom_field['location'] == 'address')`

Parse error in the address.php file

On clicking address book in the my account page there is an error:

`Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in .../catalog/controller/account/address.php on line 522`

I found a fix in the forum http://forum.opencart.com/viewtopic.php?f=181&t=159242

to change line 522 from:

`} elseif (($custom_field['type'] == 'text' && !empty($custom_field['validation'] && $custom_field['location'] == 'address')) && !filter_var($this->request->post['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {`
change to:

`} elseif (($custom_field['type'] == 'text' && !empty($custom_field['validation']) && $custom_field['location'] == 'address') && !filter_var($this->request->post['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {`
I confirm that this works.

**Comment by danielkerr** [comment]
And u never bothered to check the master to see a fix already added weeks a go
