### ISSUE TITLE
Opencart 2.2 SMTP Error

### ISSUE THREAD

**Issue by sundarrajan360** [opencart/opencart#4525]
Hi,
In Opencart 2.2 after configuired SMTP in admin panel, I am getting below error while registering user,

Warning: fsockopen(): unable to connect to ssl://smtp.gmail.com:465 (Connection refused) in /mypath /system/library/mail.php on line 167
Fatal error: Uncaught exception 'Exception' with message 'Error: Connection refused (111)' in /mypath /system/library/mail.php:170 Stack trace: #0 /mypath/catalog/model/account/customer.php(55): Mail->send() #1 [internal function]: ModelAccountCustomer->addCustomer(Array) #2 /mypath /system/storage/modification/system/engine/loader.php(150): call_user_func_array(Array, Array) #3 [internal function]: Loader->{closure}(Array) #4 /mypath /system/engine/proxy.php(13): call_user_func(Object(Closure), Array) #5 /mypath /catalog/controller/account/register.php(21): Proxy->__call('addCustomer', Array) #6 /mypath /catalog/controller/account/register.php(21): Proxy->addCustomer(Array) #7 [internal function]: ControllerAccountRegister->index() #8 /mypath /system/storage/modification/system/engine/action.php(44): call_user_fun in /mypath /system/library/mail.php on line 170

I have found a solution online from below link, but in opencart 2.2 already these changes are done still I am getting the above error. 
https://github.com/opencart/opencart/issues/2887
Please help me to resolve this issue.

SMTP Config:
![untitled](https://cloud.githubusercontent.com/assets/17548427/16170064/ef872a16-3562-11e6-8340-e3edab565f7c.jpg)

**Comment by danielkerr** [comment]
did you set 2 factor auth up and an app password?

**Comment by sundarrajan360** [comment]
Yeah i have tried  it by referring #4496 but i am getting the same error.
Kindly help me on this.

**Comment by metalbox** [comment]
same error

**Comment by webcorvo** [comment]
Try to use
SMTP Hostname: tls://smtp.gmail.com
SMTP Port : 587

That woks for me ;o)

**Comment by alokgoenka** [comment]
> 
> 
> Try to use
> SMTP Hostname: tls://smtp.gmail.com
> SMTP Port : 587
> 
> That works for me ;o)

Thanx for support , It worked for me .
