### ISSUE TITLE
"ajax call" broken when there is a lot of "option elements" in the page 

### ISSUE THREAD

**Issue by bau720123** [opencart/opencart#4531]
all detail in my screenshot (I am using 2.2 version)
![01](https://cloud.githubusercontent.com/assets/5110085/16198542/d95a9d86-3738-11e6-8dec-a2b40f824773.png)
![02](https://cloud.githubusercontent.com/assets/5110085/16198541/d9396210-3738-11e6-8cd8-853c6368e848.png)

**Comment by danielkerr** [comment]
I think the issue is because you in china and the connection is slow there.

**Comment by danielkerr** [comment]
if you use the latest master it has the ablity to use all zones

**Comment by bau720123** [comment]
hi @danielkerr 
thanks your reply
but I am still confuse and maybe you misunderstood what I mean
you said because I am in China (although I am in Taiwan)，and...I have a low network connection...so I will encounter this problem
but this problem if I use "private mode"，it won't happen

My steps︰

=====
use latest chrome browser (none private mode)

first，link this address and type the "admin" to be the account and password (2.2 version)
http://www.littlebau.com/OpenCart_o/admin/

second，click...System＞Localization＞Geo Zones
click the Edit bottom (UK VAT Zone)...and it will show this screenshot like this
![01](https://cloud.githubusercontent.com/assets/5110085/16198542/d95a9d86-3738-11e6-8dec-a2b40f824773.png)
=====

=====
use latest chrome browser (in private mode)

follow the above step，and you will find there is no problem at all，why？
![02](https://cloud.githubusercontent.com/assets/5110085/16198541/d9396210-3738-11e6-8cd8-853c6368e848.png)
=====

**Comment by CoverUp** [comment]
Different result using FF 47.0

![taiwan](https://cloud.githubusercontent.com/assets/9145868/16274886/93d0a286-3875-11e6-868c-13516ed8f2a0.png)

**Comment by bau720123** [comment]
yes
just like @CoverUp said (it's what I mean)
everytime you refresh the page，every different result

**Comment by CoverUp** [comment]
It is possible that your server got some kind of anti hammering security? I mean some kind of firewall against too many request per second from same IP. Yes it sound weird but I have seen this before.
http://greenbytes.de/tech/webdav/rfc5842.html#status.508.loop.detected

**Comment by bau720123** [comment]
thanks @CoverUp 
thanks your reply
maybe I should consider to upgrade my server
but I am just wonder，why in "private mode"，the problem won't appear

**Comment by bau720123** [comment]
hi @danielkerr 
is there any possible that you can give me some suggestion
because just like above said，this problem won't appear if I use "private mode" in my browser

**Comment by CoverUp** [comment]
@bau720123 I get the same result in "private mode", thus the issue is the "Loop" of calls, not the private or normal mode, thats is just to get rid of session and cookie information after use.

**Comment by bau720123** [comment]
hi @CoverUp 
thanks your reply again
are you using latest Chrome version "private mode"
if not，can you help me to use Chrome and test again
because in my Chrome，it really no problem at all
anyway...tks...

**Comment by danielkerr** [comment]
Ok I can fix

**Comment by danielkerr** [comment]
ok just done a commit where it will ajax load each zone one at a time

**Comment by bau720123** [comment]
hi @danielkerr 
thanks for your solution
is it possible to do a php version fix before opencart 3.0.0 beta
because before opencart 3.0.0 (for example 2.3.0.2)，it is a file that called geo_zone_form.tpl
and...a lot of syntax different from your geo_zone_form.twig
