### ISSUE TITLE
summernote "click" problem

### ISSUE THREAD

**Issue by bau720123** [opencart/opencart#4532]
all detail in my screenshot (I am using 2.2 version)
![3](https://cloud.githubusercontent.com/assets/5110085/16199063/bcf5a468-373a-11e6-9aae-3dd79a9356f0.png)
![04](https://cloud.githubusercontent.com/assets/5110085/16199064/bcfcb3de-373a-11e6-8fef-45bea9d79d03.png)
![05](https://cloud.githubusercontent.com/assets/5110085/16199065/bd015736-373a-11e6-861b-51ab893ebfc8.png)

**Comment by kieranmccarthy** [comment]
I am having the same issue. Insert an image from root works fine, insert an image within a sub-folder of root opens the image in a browser window and doesn't insert into the Summernote WYSIWYG edit area. I'm using Version 2.2.0.0

**Comment by bau720123** [comment]
hi @kieranmccarthy 
try this
https://github.com/opencart/opencart/commit/d962e9100f19f918d1c02e43e6db8fb7e4e9142a
problem solved

**Comment by ivanssa** [comment]
I also found the same solution here https://github.com/opencart/opencart/issues/4726
