### ISSUE TITLE
[OPENBAY]'s related issue at sale/order/info

### ISSUE THREAD

**Issue by giovannipds** [opencart/opencart#4535]
Hello guys! As I've seen here: http://forum.opencart.com/viewtopic.php?f=20&t=113666 - and in this file: [order_info.tpl](https://github.com/opencart/opencart/blob/master/upload/admin/view/template/sale/order_info.tpl) - in the master branch, this problem seems to be still happening, in the 2.0.3.1 version that I've tested and in should be the same in the latest version, as well.

In the sales/order history tab, it's showing a "permission denied" when the user doesn't have permission nor openbay installed.

It seems that the function `changeStatus` should just run when the user has openbay installed.

```
function changeStatus(){
  var status_id = $('select[name="order_status_id"]').val();

  $('#openbay-info').remove();

  $.ajax({
    url: 'index.php?route=extension/openbay/getorderinfo&token=<?php echo $token; ?>&order_id=<?php echo $order_id; ?>&status_id='+status_id,
    dataType: 'html',
    success: function(html) {
      $('#history').after(html);
    }
  });
}

function addOrderInfo(){
  var status_id = $('select[name="order_status_id"]').val();

  $.ajax({
    url: 'index.php?route=extension/openbay/addorderinfo&token=<?php echo $token; ?>&order_id=<?php echo $order_id; ?>&status_id='+status_id,
    type: 'post',
    dataType: 'html',
    data: $(".openbay-data").serialize()
  });
}

$(document).ready(function() {
  changeStatus();
});

$('select[name="order_status_id"]').change(function(){ changeStatus(); });
```

Can someone give an attention to this? If I can try to contribute to the code, please just inform and I can provide a PR for that.

Regards, Gio.

**Comment by danielkerr** [comment]
james you should be using the event system instead of putting js code in core files.

**Comment by giovannipds** [comment]
This is something that beats me. There's js code everywhere in the opencart's core files. It would be better if they were all separated, specially the default theme views...

**Comment by danielkerr** [comment]
sales/order history tab is fine in the latest version.

**Comment by giovannipds** [comment]
@danielkerr I'm not with a project using OpenCart right now anymore, so I can't test it, but glad you guys have taken care anyway. =) Cheers.
