### ISSUE TITLE
Opencart 2.2 SMTP Error

### ISSUE THREAD

**Issue by sundarrajan360** [opencart/opencart#4536]
Hi,
In Opencart 2.2 after configuired SMTP in admin panel, I am getting below error while registering user,

Warning: fsockopen(): unable to connect to ssl://smtp.gmail.com:465 (Connection refused) in /mypath /system/library/mail.php on line 167
Fatal error: Uncaught exception 'Exception' with message 'Error: Connection refused (111)' in /mypath /system/library/mail.php:170 Stack trace: #0 /mypath/catalog/model/account/customer.php(55): Mail->send() #1 [internal function]: ModelAccountCustomer->addCustomer(Array) #2 /mypath /system/storage/modification/system/engine/loader.php(150): call_user_func_array(Array, Array) #3 [internal function]: Loader->{closure}(Array) #4 /mypath /system/engine/proxy.php(13): call_user_func(Object(Closure), Array) #5 /mypath /catalog/controller/account/register.php(21): Proxy->__call('addCustomer', Array) #6 /mypath /catalog/controller/account/register.php(21): Proxy->addCustomer(Array) #7 [internal function]: ControllerAccountRegister->index() #8 /mypath /system/storage/modification/system/engine/action.php(44): call_user_fun in /mypath /system/library/mail.php on line 170

I have found a solution online from below link, but in opencart 2.2 already these changes are done still I am getting the above error.
https://github.com/opencart/opencart/issues/2887 & also tried this but it not help me https://github.com/opencart/opencart/issues/4496

Please help me to resolve this issue.
SMTP Config:
![ef872a16-3562-11e6-8340-e3edab565f7c](https://cloud.githubusercontent.com/assets/17548427/16218351/5d46e6b6-379a-11e6-9081-e7c4747eff00.jpg)

**Comment by danielkerr** [comment]
this is a issue tracker for the development of opencart not your personal support ticket system!

post again i block your account from being able to open issue and comment on the opencart github page!

**Comment by sundarrajan360** [comment]
Thank You !!!

**Comment by eviquez** [comment]
Is it was fixed?, can you help me?

Thank you in advance!!!
