### ISSUE TITLE
About config_ssl issue

### ISSUE THREAD

**Issue by seglavi** [opencart/opencart#4541]
Hi,

config_ssl is not working properly good for me if ssl is active. And it some times images are broken in 3rd party modules which uses tool image resize. And i looked into master files and i see there is difference with admin and catalog model files. And if i change the catalog model file like admin model file every thing is good. Is it an issue?

In admin>model>tool>image.php

		if ($this->request->server['HTTPS']) {
			return HTTPS_CATALOG . 'image/' . $new_image;
		} else {
			return HTTP_CATALOG . 'image/' . $new_image;
		}

In catalog>model>tool>image.php

		if ($this->request->server['HTTPS']) {
			return $this->config->get('config_ssl') . 'image/' . $new_image;
		} else {
			return $this->config->get('config_url') . 'image/' . $new_image;
		}

**Comment by danielkerr** [comment]
@seglavi never post here again!

if i accept your fix it would break a lot of opencart stores.

**Comment by seglavi** [comment]
@danielkerr ever will see a polite again!

first: i did not say this is a bug and this is a fix. just ask if it is global or my! whatever.

i will ever never wrote any thing just your kindly ask from me. of course.

**Comment by robinflyhigh** [comment]
I found the commit which fix this issue

URL: https://github.com/opencart/opencart/commit/057f12e63aba20e3259234db322ad128afc9b91c
