### ISSUE TITLE
Admin Dashboard->Customers->Parse Error

### ISSUE THREAD

**Issue by bando1de** [opencart/opencart#4544]
When I try to access Customers from the Admin Dashboard, I get this error message:

**Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /xxxx/xxxx/public_html/shop/admin/controller/customer/customer.php on line 1105**

Open Cart version is 2.2.0.0, fresh install, no mods.

**Comment by CoverUp** [comment]
get the last version from here not from opencart.com, this issue is already fixed. Please always get the last version before posting issue to avoid replication, regards.

**Comment by bando1de** [comment]
Sorry, I'm new to Github. Where do I find the latest version to update my current one?
Thanks.

**Comment by CoverUp** [comment]
https://github.com/opencart/opencart
Button Clone or download
Download ZIP
Regards
