### ISSUE TITLE
Reset password not working

### ISSUE THREAD

**Issue by amirulahmad** [opencart/opencart#4555]
As normal reset the password flow, email sent to mailbox. Click the link to reset it and put a new password. Got notification saying password successfully changed. Try to login again with new password with no luck. Try login again with old password and it worked.

**Comment by danielkerr** [comment]
just tested works fine for me. i think your issue is browser related,. try it on a browser that has not saved your username and password.

**Comment by amirulahmad** [comment]
I have re-installed it again just now to make sure I haven't missed anything on the installation process. However, I have tested again and it is the same problem. After changing the password, i's still working with the old one.  Just want to confirm, I have downloaded version 2.2.0.0 and the link is http://www.opencart.com/index.php?route=download/download/success&download_id=44.

**Comment by amirulahmad** [comment]
The response after I reset the password is this:

Request URL:http://xxx.xxxxxx.xxx/index.php?route=account/reset&code=zNKXAIteuQfvniq6UrlypCnlrBfTKmN4DjxCfGtQ
Request Method:POST
Status Code:302 Found

**Comment by danielkerr** [comment]
maybe security configuration on your server. does not like account/reset in the url
