### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by fakhricker** [opencart/opencart#4558]
I found security issue about admin page. They can  reset and login password from admin page
http://blog.indoxploit.or.id/2016/06/deface-dengan-opencart-bruteforce-and.html
http://spyhackerz.com/forum/threads/thewayend-opencart-twe-gif-video.1392/

my site was hacked with thats way in 2.1.0.2 i dont know about 2.2.x

**Comment by danielkerr** [comment]
@fakhricker hey idiot! these sites got hacked because they used the default login with weak passwords!

dont post security issues on a public tracker again!!! use email!

**Comment by danielkerr** [comment]
you dont even know what you are taking about! the video is 1.5.x! and its still not vunribule if you dont use the default login info!

your site got hacked! i suggest you check your pc for Trojans!
