### ISSUE TITLE
summernote should not execute script-tags

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#4571]
When entering this in Codeview:

```
<script type="text/javascript">
alert("I am malicious");
</script>
```

and then switching back to WYSIWYG the scripts are executed. This used to be different in CKEditor which simply preserved script-tags, but never executed them! Can this be sorted out as soon as possible?

**Comment by danielkerr** [comment]
https://github.com/summernote/summernote/issues/1462

**Comment by alansong** [comment]
Any updates on this issue? Or is there a work around?

**Comment by danielkerr** [comment]
im closing this as its out of our control. also this sort of thing can not happen if the are correct permissions made in the admin.

**Comment by RaidoDev** [comment]
This is bad.
There are many indications, that Summernote is having too many problems, should switch to different one. :(

**Comment by danielkerr** [comment]
suggest one

**Comment by mhcwebdesign** [comment]
CKEditor?

**Comment by OpenCartAddons** [comment]
There's also TinyMCE
https://www.tinymce.com/
