### ISSUE TITLE
about the "Pagination" page 1 problem

### ISSUE THREAD

**Issue by bau720123** [opencart/opencart#4574]
hi all，I am using 2.2.0 version
when I use "Use SEO URLs" and set to No
![2016-06-28_194601](https://cloud.githubusercontent.com/assets/5110085/16414206/fe34d3ca-3d68-11e6-8583-37d6ddf6a155.png)
when in page 1 and 2，it will show (please click the below Pagination)
http://www.littlebau.com/OpenCart_o/index.php?route=product/category&path=20
http://www.littlebau.com/OpenCart_o/index.php?route=product/category&path=20&page=2

but 
when I use "Use SEO URLs" and set to Yes
when in page 1 and 2，it will show (please click the below Pagination)
http://www.littlebau.com/OpenCart/desktops?page={page}
http://www.littlebau.com/OpenCart/desktops?page=2

the issue is about the "{page}"
although it seem won't occur any problem，but if in page 1，it can just show 
http://www.littlebau.com/OpenCart/desktops
I think it is more better

**Comment by bau720123** [comment]
hi @danielkerr 
any unclear ?

**Comment by pekka2** [comment]
There is your language file error.

**Comment by bau720123** [comment]
hi @pekka2 
I can't understand what your true meaning
main language file ?
can you give me some hint ?

**Comment by eka7a** [comment]
Fixed
https://github.com/opencart/opencart/commit/f0a53f36821839cf035e6e654e33adfb499c02d4#diff-adcbd94d10692a3c7cd49ac1cc48955b
https://github.com/opencart/opencart/commit/8406e222ec0f63193630ae72e9660d93eba75138#diff-adcbd94d10692a3c7cd49ac1cc48955b

**Comment by bygantar** [comment]
thanks @eka7a

**Comment by webcreativity** [comment]
Thanks @eka7a
