### ISSUE TITLE
Opencart 2.2   admin->Customer 

### ISSUE THREAD

**Issue by jigneshdavara** [opencart/opencart#4575]
admin/controller/customer/customer.php

Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ') in line 1104

**Comment by jigneshdavara** [comment]
solution  replace
else condition with 

elseif(($custom_field['type'] == 'text' && !empty($custom_field['validation']) && $custom_field['location'] == 'address') && !filter_var($value['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation']))))

**Comment by mariavilaro** [comment]
This is not a solution. The solution is fixing the broken code in the zip file that people is downloading from Opencart.com. 6 months later, Opencart users are still losing their time because a stupid missing )
