### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#4578]
After last changes to API, $this->session->data['api _id'] is not set right. The system every time alerting Warning: You do not have permission to access the API!

**Comment by haxcop** [comment]
@danijelGombac  I got the same issue and tried to find a solution over the past closed reports and none works.

**Comment by danielkerr** [comment]
ok

**Comment by danielkerr** [comment]
back on with this. strange it was working in my office then when i get home not working.

**Comment by danielkerr** [comment]
the issue is when creating a new session its not creating a file.

**Comment by danielkerr** [comment]
maybe if we try setting a cookie manually.

**Comment by danielkerr** [comment]
i think its not possible to set a cookie via ajax

**Comment by danielkerr** [comment]
ok this php session_write_close must not work. no way to tell since it does not return anything.

so if i manually create the session file and store the api_id in it that should work.

**Comment by danielkerr** [comment]
only issue is if soem hosts dont use the php file system for sessions.

**Comment by danielkerr** [comment]
php 5.6 at home and php 7 in the office.

**Comment by haxcop** [comment]
Hi @danielkerr is this solved?. if so, what should I do?.

**Comment by thekrotek** [comment]
Just want to confirm, that on 2.3.0.2 API still not working properly. I can easily login to API using cURL, but any further request fails with "Warning: You do not have permission to access the API!". Reason is the same: api_id session variable is not present at all.

Here's a code I use to make requests:

```php
		
		$curl = curl_init();

		if ((substr($this->getStoreURL(), 0, 5) == 'https') && !$this->config->get($this->extension.'_disable_ssl')) {
			curl_setopt($curl, CURLOPT_PORT, 443);
		}

		if ($this->config->get($this->extension.'_debug')) {
			$verbose = fopen('php://temp', 'w+');
		
			curl_setopt($curl, CURLOPT_VERBOSE, true);
			curl_setopt($curl, CURLOPT_STDERR, $verbose);
		}
		
		curl_setopt($curl, CURLOPT_HEADER, false);
		curl_setopt($curl, CURLOPT_USERAGENT, $this->request->server['HTTP_USER_AGENT']);
		curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
		curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($curl, CURLOPT_FORBID_REUSE, false);
		curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($curl, CURLOPT_URL, $url);
			
		if (!empty($this->session->data[$this->extension.'_session'])) {
			curl_setopt($curl, CURLOPT_COOKIE, session_name().'='.$this->session->data[$this->extension.'_session'].';');
		}
	
		if ($data) {
			curl_setopt($curl, CURLOPT_POST, true);
			curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($data));
		}

		$result = curl_exec($curl);
```

I triple checked session and token - they both are present in database for current API.

It works perfectly on OpenCart up to version 2.1. Don't have 2.2 installation right now, but on 2.3 it stopped working.
