### ISSUE TITLE
Permissions for extensions and dashboard not working

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#4582]
If user doesn't have permission to access extension/dashboard/ ... pages, dashboard elements are blocked.

And in admin/controller/startup/permission.php missing 'extension/dashboard' and checking for in array not working, because "substr($this->request->get['route'], 0, 10)" return "extension/" which is never in array:

```
$routes = array(
				'extension/analytics',
				'extension/captcha',
				'extension/feed',
				'extension/fraud',
				'extension/module',
				'extension/payment',
				'extension/shipping',
				'extension/theme',
				'extension/total'
			);
```

But there is another problem, if is in array and add part 3 to route, install, unistall, add and delete extension is blocked, because you can add extension/total/install to premission. There should be ignore for this routes or change the names of main extension pages .I don't know, if my explanation is clear enough.

**Comment by danielkerr** [comment]
it works from fresh install fine are u upgrading?

**Comment by danielkerr** [comment]
i just did a commit to fix the issue. open a new issue if still having issue after my fix.

**Comment by danijelGombac** [comment]
Try create new user without permission for extensions and open dashboard page.
