### ISSUE TITLE
Image upload Error in Opencart

### ISSUE THREAD

**Issue by shopyfly** [opencart/opencart#4591]
Hi,

I am getting the below Error while i try to upload images to product.

Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 33326667 bytes) in /home/xledugat/public_html/shopyfly.com/shopyfly_host/system/library/image.php on line 24

Any Solution for this ??

**Comment by bau720123** [comment]
hi @shopyfly 
I suggest you search from google first
http://stackoverflow.com/questions/561066/fatal-error-allowed-memory-size-of-134217728-bytes-exhausted-codeigniter-xml

**Comment by osworx** [comment]
A better qualified suggestion than the one before is:
1. check the size if the image(s) (have seen customer uploading images bigger 30MB each which is nonsens!)
2. upload less images at once (additionally to #1 if that does not help)
3. last change: increase the server memory limit (really last option!)

 - How do to #3? 
Well here again, learn to understand your server, php and use your preferred search engine.
