### ISSUE TITLE
Internal Server Error v2.2 on New Customer Registration Page

### ISSUE THREAD

**Issue by Si-Richards** [opencart/opencart#4593]
- Opencart v2.2
- PHP 5.6.22
- Apache 2.4.6
- SSL

> PHP Fatal error:  Uncaught exception 'Exception' with message 'Error: Unknown column 'language_id' in 'field list'<br />Error No: 1054<br />INSERT INTO oc_customer SET customer_group_id = '1', store_id = '0', language_id = '1'........................
> 
> vho...')\n#2 [internal function]: ModelAccountCustomer->addCustomer(Array)\n#3 /var/www/html/system/storage/modification/system/engine/loader.php(150): call_user_func_array(Array, Array)\n#4 [internal function]: Loader->{closure}(Array)\n in /var/www/html/system/library/db/mysqli.php on line 40, referer: https://store.mystore.co.uk

Language ID does'nt exist in the schema so removed this and registration was a success.

**catalog/model/account/customer.php** 
line 14
`$this->db->query("INSERT INTO " . DB_PREFIX . "customer SET customer_group_id = '" . (int)$customer_group_id . "', store_id = '" . (int)$this->config->get('config_store_id') . "', firstname = '" . $this->db->escape($data['firstname']) . "', lastname = '" . $this->db->escape($data['lastname']) . "', email = '" . $this->db->escape($data['email']) . "', telephone = '" . $this->db->escape($data['telephone']) . "', fax = '" . $this->db->escape($data['fax']) . "', custom_field = '" . $this->db->escape(isset($data['custom_field']['account']) ? json_encode($data['custom_field']['account']) : '') . "', salt = '" . $this->db->escape($salt = token(9)) . "', password = '" . $this->db->escape(sha1($salt . sha1($salt . sha1($data['password'])))) . "', newsletter = '" . (isset($data['newsletter']) ? (int)$data['newsletter'] : 0) . "', ip = '" . $this->db->escape($this->request->server['REMOTE_ADDR']) . "', status = '1', approved = '" . (int)!$customer_group_info['approval'] . "', date_added = NOW()");`

**Comment by danielkerr** [comment]
did u run through upgrade? because if you had it would have added the missing field

**Comment by Si-Richards** [comment]
Hi Daniel, It was a clean install which didnt appear to throw any visible errors so who knows.
It also didn't create the 'code' column in customer which meant the password reset page throws an internal 500 error.
It must be down to a corrupt database install so feel free to close off the ticket.
