### ISSUE TITLE
SMTP Error (Opencart 2.2.0.0)

### ISSUE THREAD

**Issue by andrei336** [opencart/opencart#4594]
Hi,

I have installed opencart 2.2 and after the configuration of SMTP when i wanted to send an email from the contact page the following error appeard:

**1. Contact page:**
Warning: fsockopen(): unable to connect to ssl://smtp.gmail.com:465 (Connection refused) in /mypath /system/library/mail.php on line 167
Fatal error: Uncaught exception 'Exception' with message 'Error: Connection refused (111)' in /mypath /system/library/mail.php:170 Stack trace: #0 /mypath/catalog/model/account/customer.php(55): Mail->send() #1 [internal function]: ModelAccountCustomer->addCustomer(Array) #2 /mypath /system/storage/modification/system/engine/loader.php(150): call_user_func_array(Array, Array) #3 [internal function]: Loader->{closure}(Array) #4 /mypath /system/engine/proxy.php(13): call_user_func(Object(Closure), Array) #5 /mypath /catalog/controller/account/register.php(21): Proxy->__call('addCustomer', Array) #6 /mypath /catalog/controller/account/register.php(21): Proxy->addCustomer(Array) #7 [internal function]: ControllerAccountRegister->index() #8 /mypath /system/storage/modification/system/engine/action.php(44): call_user_fun in /mypath /system/library/mail.php on line 170

**2. Admin error.log:**
Warning: fsockopen(): unable to connect to ssl://smtp.gmail.com:465 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/greencit/public_html/system/library/mail.php on line 167
166: 
167: 	$handle = fsockopen($hostname, $this->smtp_port, $errno, $errstr, $this->smtp_timeout);
168:

 

**This are my SMTP configurations:**

![setting-smtp](https://cloud.githubusercontent.com/assets/3365019/16488947/bb40d7e8-3edb-11e6-8000-1ac2d0643c3d.jpg)

How can i solve this issue.

**Comment by osworx** [comment]
Have you ever tried port **587** and **smtp.gmail.com** only?

**Comment by danielkerr** [comment]
also did you set 2-factor auth on your google account and then set an app specific password on google for smtp to be accessed?

**Comment by danielkerr** [comment]
also if this is localhost does your ISP allow this port to be used?

**Comment by danielkerr** [comment]
it works fine on my gmail account

**Comment by andrei336** [comment]
@osworx yes. Not work.

@danielkerr 
1. yes. username and password
2.yes ISP allow

**Comment by danielkerr** [comment]
It's not an Opencart issue with errors like

php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by danielkerr** [comment]
Contact ur host

**Comment by andrei336** [comment]
Thanks, worked with the following setup:

![setting-smtp-](https://cloud.githubusercontent.com/assets/3365019/16516245/a4c5ff44-3f7f-11e6-97a7-696cc6a515ff.jpg)

**Comment by KalaiarasanSeetharaman** [comment]
I am facing issue in opencart 3.0.2
Please help me mail is not going using smtp 
I am using wamp server 
smtp i have used gmail 
Host : tls://smtp.gmail.com
Port: 587
Gmail username and password given but mail is not going 

Same thing i have used in laravel project .. There mail going fine .  But in opencart i can't 
![issue](https://user-images.githubusercontent.com/16400150/38558969-64583f70-3cef-11e8-9a08-141057d30d99.png)

**Comment by danielkerr** [comment]
you need to setup an app password on your google account and use that with
gmail.

On 10 April 2018 at 21:16, Kalaiarasan Seetharaman <notifications@github.com

**Comment by KalaiarasanSeetharaman** [comment]
In my team they said they set everything correctly in gmail for smtp ... I need some help ...

**Comment by KalaiarasanSeetharaman** [comment]
Where i can see the proper smtp settings in gmail ..

**Comment by KalaiarasanSeetharaman** [comment]
Yes i have created google separate  app password . Did i need to disable two step verification

**Comment by danielkerr** [comment]
no.

https://medium.com/@BENJITHREESTACK/how-to-use-googles-smtp-service-with-opencart-944b9c5c76ea

ssl://smtp.gmail.com

**Comment by KalaiarasanSeetharaman** [comment]
Friend I am using wamp server
I have created app password also for my mail id..  Disabled 2 step
verification also..  Unlocked cap also, ... Even though it not going
