### ISSUE TITLE
Error in datetime function when another form is on the page. 

### ISSUE THREAD

**Issue by goberflunk** [opencart/opencart#4595]
If there is a form embedded on the page (from another plugin such as a live chat plugin) then there is a fatal error on the checkout page on these lines

m = function() {
var a;
a = i.element.is("input") ? i.element.data() : i.element.find("input").data(),
void 0 !== a.dateFormat && (i.options.format = a.dateFormat),

a is set to undefined and the a.dateFormat fails out. 

This can be reproduced by going to an open cart site such as https://www.xenonshop.co.uk/index.php?route=checkout/checkout with something in your cart. Trying to put the following code in the console (loading the live chat widget) and clicking "guest checkout" 

window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '8b151242-3c24-495e-b396-342e2a94b799', f: true }); done = true; } }; })();

**Comment by danielkerr** [comment]
im closing this issue because your talking gibberish.

there is no live purechat wiglet in opencart only hangouts.

**Comment by goberflunk** [comment]
It's not a widget. It's a code snippet that is placed on the website. Lots of different companies load software onto a website by doing this. There are many lead capture forms and live chat software products that load a form onto the page and will break this.

**Comment by vigneshwaran-kannan** [comment]
I am facing a issue that i have added purechat script in my website and trying to make popup of the widget inside my website. but it's getting popout of the portal and getting displayed in new window.
Can someone help me on this.

<script type='text/javascript' data-cfasync='false'> window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '4a0f94ec-92f6-45d0-a687-76c66ee5af8e', f: true }); done = true; } }; })(); </script>
