### ISSUE TITLE
After changing theme from admin settings theme view files are not loading

### ISSUE THREAD

**Issue by RadhikaMayani** [opencart/opencart#4601]
opencart 2.2
I have changed theme from **default** to **demo1**.After this while calling a page controller is not loading the file from **demo1**.It still giving the file path of **default** theme.

I want like this : 
**2.2.0.0-compiled/upload/catalog/view/theme/demo1/template/folder/file.tpl**
 instead of 

**2.2.0.0-compiled/upload/catalog/view/theme/default/template/folder/file.tpl**

**Comment by pekka2** [comment]
Your need edit eg. this file:
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/event/theme.php

**Comment by RadhikaMayani** [comment]
It is not working for me. :(

**Comment by danielkerr** [comment]
try changing the 

	if (substr($view, -3) == 'tpl') {
			$view = substr($view, 0, -3);
		}

to 

	if (substr($view, -4) == 'tpl') {
			$view = substr($view, 0, -4);
		}

**Comment by danielkerr** [comment]
i mean 

if (substr($view, -4) == '.tpl') {
        $view = substr($view, 0, -4);
    }

**Comment by danielkerr** [comment]
i know!!!

go to the default theme and you see where it says directory. its which theme to choose.

**Comment by RadhikaMayani** [comment]
ok. Now it I have created custom folder in catalog eg. Folder1
while **catalog/controller/customfolder/customfile** executes it calls **view/theme/customtheme/template/customfolder/customfile**.

It displays blank page in front store.
