### ISSUE TITLE
custom folder in opencart 2.2

### ISSUE THREAD

**Issue by RadhikaMayani** [opencart/opencart#4602]
Now I have created custom folder in catalog eg. Folder1
while catalog/controller/customfolder/customfile executes it calls view/theme/customtheme/template/customfolder/customfile.

It displays blank page in front store.

**Comment by danielkerr** [comment]
github is not a support service! its a development tool for the development for opencart and not a personal FAQ!

**Comment by danielkerr** [comment]
use the contact us page or forums or even contact one of our partners,
