### ISSUE TITLE
pay with amazon not woking in 2.2.0.0

### ISSUE THREAD

**Issue by bapparabi** [opencart/opencart#4603]
hi 

gusy there some iisue in version 2.2.0.0 ad when try to active the pay with amazon payment gateway it si not showing in checkout page ..i have tested in default theme as well a as custom theme ..do you guys know why this happening what is issue and how to solve it ..

this test by in 2 website same issue

**Comment by danielkerr** [comment]
have u tried the latest version?

**Comment by bapparabi** [comment]
yes 2.2.0.0 is latest version sir same problem

**Comment by danielkerr** [comment]
what about the master branch on github?

**Comment by bapparabi** [comment]
what do you menaa by that sir

**Comment by danielkerr** [comment]
go here and download the master branch version here:

https://github.com/opencart/opencart

click the button on the top right.

it shoudl be fixed in this verion as its the master branch it has all the fixes.

**Comment by danielkerr** [comment]
let me know if it works

**Comment by chris-wm** [comment]
@bapparabi Hi, can you also check that you have an SSL installed for your site, Amazon requires this for  security and the payment system will not display without it,
regards

**Comment by bapparabi** [comment]
yes it has ssl already installed

**Comment by chris-wm** [comment]
@bapparabi Hi, would you be able to raise a support ticket at https://help.welfordmedia.co.uk/ so that we can have a look at your site to investigate the problem?
Regards

**Comment by bapparabi** [comment]
hi you can test it in defualy 2.2 version store ist not working in there alos

**Comment by chris-wm** [comment]
@bapparabi Hi, the Amazon payment system was tested and functional on a default OpenCart store, it might be something to do with your store or server set-up. If you can raise a ticket then one of the team should be able to help. Also the next version of OpenCart is due to be released soon with an updated version of Login and Pay with Amazon so you might want to consider waiting for this as well,
regards

**Comment by jamesallsup** [comment]
Closing issue as it is isolated and support offered.
