### ISSUE TITLE
Undefined Error: New User Registration during Checkout

### ISSUE THREAD

**Issue by srivatsats** [opencart/opencart#4604]
Hi,

I have been struggling to solve the the below undefined error issue on our shop front. We get Undefined error when user is trying to register a new account during the checkout process. Account gets created, but the pages shows an error as in the enclosed screenshot. The page stays there until and unless user refreshes the page. This is causing a lot of drop outs on our shop. Please help.
Please note, this happens only on new account creation during checkout. If the account is being created via the regular Login/Register, this is not an issue.

Opencart version: 2.0.3.1

Thanks,
Sri
![oc_error](https://cloud.githubusercontent.com/assets/7007300/16543820/381d53b6-4109-11e6-9d08-9429566ef647.png)

**Comment by danielkerr** [comment]
use the forums.
