### ISSUE TITLE
Deleting extension GUI issue;

### ISSUE THREAD

**Issue by elcopdoo** [opencart/opencart#4606]
In Firefox 47.0.1(don't know for other browsers) after deleting extension module GUI is incomplete,
this issue is present some time now in github master version.
This time i tried with OC 2.2.2 master.
See screenshot.
![oc_222_deleting_module](https://cloud.githubusercontent.com/assets/9281666/16544536/bfe8589e-410a-11e6-834f-a6f68f632667.jpg)

**Comment by danielkerr** [comment]
"this issue is present some time now in github master version."

so why didnt you report it it sooner!

**Comment by danielkerr** [comment]
ok not fixed

**Comment by danielkerr** [comment]
fixed
