### ISSUE TITLE
Paypal standard no shipping staus

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#4608]
https://github.com/pekka2/opencart/commit/5ba0b5c3d8bde659bdb76c1f1458e92bfebe9dd2
https://github.com/pekka2/opencart/commit/f1d41e76c4b7379537c4b845c25a38f6a8689ca6
https://github.com/pekka2/opencart/commit/4b31fee6f478841771e238686637397e767cc901
https://github.com/pekka2/opencart/commit/eb5f88dc16a677cc5dde1a9bea9bae721539ce7d
https://github.com/pekka2/opencart/commit/998ce010ef0a1b3ac8f7217260f0920665bfdd18

**Comment by davidteal** [comment]
Hi @pekka2 

Can you submit a Pull Request for this? Also, make sure you use the correct indentation:

https://github.com/opencart/opencart/wiki/Coding-standards#indentation

**Comment by pekka2** [comment]
@davidteal 
Sorry, I do not know how to use this Github

**Comment by danielkerr** [comment]
closing this as i have no idea what the issue is
