### ISSUE TITLE
Call to undefined method ModelMarketingAffiliate::getvTransactionsByOrderId()

### ISSUE THREAD

**Issue by Fanster** [opencart/opencart#4612]
Hello.
Not sure if anybody else had this problem on their hands, but I searched and found no results. Our company is currently using opencart as a platform for the online store. And everything was fine last week. But something happened during the weekend, and now we are facing this unexpected error:

Fatal error: Call to undefined method ModelMarketingAffiliate::getvTransactionsByOrderId() in /home/cqyiu7ta/public_html/system/storage/modification/admin/controller/sale/order.php on line 1085

This occurs when we try to view an order through the Admin Panel. We click on "view" and this pops up, we can't see the order, we can't print the invoice, we can't do anything. I've dug myself in the php of the order.php code, but I don't see any problem there. It is peculiar enough that this happened by itself.

Thank you for your time!

**Comment by danielkerr** [comment]
clear your modifcation directory. if your issue is related to a mod use the forum, contact the developer, contact my staff, use the support ticket system
