### ISSUE TITLE
Marketing > Mail

### ISSUE THREAD

**Issue by jfjewels** [opencart/opencart#4617]
I'm using version 2.2.0.0
This issue has been raised before but was closed before a solution was found.

When I go to Marketing > Mail and try to send a newsletter to any recipient in the drop down menu, nothing happens at all. The page does not even try to load anything.

All my mail settings are set up correctly to the best of my knowledge.

**Comment by bau720123** [comment]
hi @jfjewels 
try this
https://github.com/opencart/opencart/issues/4089
