### ISSUE TITLE
Beta Test 2.3.0.0_b1 Error

### ISSUE THREAD

**Issue by pnair39** [opencart/opencart#4618]
Fatal error: Call to undefined function start() in /home/amillio8/public_html/Demo/index.php on line 31

**Comment by florinsith** [comment]
Index.php doesnt seem to have that many lines

**Comment by pnair39** [comment]
should I take the index.php and replace it again for the https://github.com/opencart/opencart/releases/tag/2.3.0.0_b1 ???

**Comment by pnair39** [comment]
<?php
// Error Reporting
error_reporting(E_ALL);

// Check if SSL
if ((isset($_SERVER['HTTPS']) && (($_SERVER['HTTPS'] == 'on') || ($_SERVER['HTTPS'] == '1'))) || $_SERVER['SERVER_PORT'] == 443) {
	$protocol = 'https://';
} elseif (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' || !empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] == 'on') {
	$protocol = 'https://';
} else {
	$protocol = 'http://';
}

define('HTTP_SERVER', $protocol . $_SERVER['HTTP_HOST'] . rtrim(dirname($_SERVER['SCRIPT_NAME']), '/.\\') . '/');
define('HTTP_OPENCART', $protocol . $_SERVER['HTTP_HOST'] . rtrim(rtrim(dirname($_SERVER['SCRIPT_NAME']), 'install'), '/.\\') . '/');

// DIR
define('DIR_APPLICATION', str_replace('\\', '/', realpath(dirname(__FILE__))) . '/');
define('DIR_SYSTEM', str_replace('\\', '/', realpath(dirname(__FILE__) . '/../')) . '/system/');
define('DIR_OPENCART', str_replace('\\', '/', realpath(DIR_APPLICATION . '../')) . '/');
define('DIR_MODIFICATION', DIR_SYSTEM . 'storage/modification/');
define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');
define('DIR_TEMPLATE', DIR_APPLICATION . 'view/template/');
define('DIR_CONFIG', DIR_SYSTEM . 'config/');
define('DIR_IMAGE', str_replace('\\', '/', realpath(DIR_SYSTEM . '../image')) . '/');
define('DIR_CACHE', DIR_SYSTEM . 'storage/cache/');

// Startup
require_once(DIR_SYSTEM . 'startup.php');

start('install');

**Comment by pnair39** [comment]
During install: 

Notice: Error: Could not load template /home/amillio8/public_html/Demo/install/view/template/common/header! in /home/amillio8/public_html/Demo/system/storage/modification/system/engine/loader.php on line 86

**Comment by florinsith** [comment]
Why would it be /home/amillio8/public_html/Demo/index.php when that is the content of install/index.php
Did you rename the install folder?
And how do you allready have modifications cache?
Im confused, seems to be working fine for me.

**Comment by pnair39** [comment]
Demo/install/index.php is present ...This is an upgrade any suggestions?

**Comment by pnair39** [comment]
renamed modifications folder and ran upgrade: 

Error Code(0): Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`store_id` = '0', `code` = 'dashboard_activity', `key` = 'dashboard_activity_sta' at line 1
Error No: 1064
INSERT INTO `oc_setting` `store_id` = '0', `code` = 'dashboard_activity', `key` = 'dashboard_activity_status', `value` = '1', `serialized` = '0' in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 40

**Comment by pnair39** [comment]
Fatal error: Call to undefined function start() in /home/amillio8/public_html/Demo/index.php on line 31
