### ISSUE TITLE
  renamed modifications folder and ran upgrade:Beta Test 2.3.0.0_b1 Error (#4618)

### ISSUE THREAD

**Issue by pnair39** [opencart/opencart#4620]
@florinsith 
renamed modifications folder and ran upgrade:

During upgrade process received this and hit continue went thru as successful, **

> after upgrade
> error:
> Fatal error: Call to undefined function start() in /home/amillio8/public_html/Demo/index.php on line 31

**

Error Code(0): Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'store_id = '0', code = 'dashboard_activity', key = 'dashboard_activity_sta' at line 1
Error No: 1064
INSERT INTO oc_setting store_id = '0', code = 'dashboard_activity', key = 'dashboard_activity_status', value = '1', serialized = '0' in /home/amillio8/public_html/Demo/system/library/db/mysqli.php on line 40

**Comment by pnair39** [comment]
Some Progress: I am able to login to admin account on the webpage however the home page does not load:Fatal error: Call to undefined function start() in /home/amillio8/public_html/Demo/index.php on line 31

**Comment by pnair39** [comment]
<img width="1258" alt="screen shot 2016-07-05 at 2 30 34 pm" src="https://cloud.githubusercontent.com/assets/15057957/16595441/1b0e9338-42bd-11e6-80b8-21c0e1aa04bd.png">

**Comment by danielkerr** [comment]
replace your system/startup file i dont think you did it correctly.

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/blob/master/upload/system/startup.php

is at the bottom

function start($application_config) {
	require_once(DIR_SYSTEM . 'framework.php');	
}

**Comment by danielkerr** [comment]
let mw know if it works.

**Comment by pnair39** [comment]
Re-confirmed all files in the upload folder was uploaded via FTP to overwrite: (see below).

// Helper
require_once(DIR_SYSTEM . 'helper/general.php');
require_once(DIR_SYSTEM . 'helper/utf8.php');
require_once(DIR_SYSTEM . 'helper/json.php');

function start($application_config) {
	require_once(DIR_SYSTEM . 'framework.php');	
}

**Comment by danielkerr** [comment]
come on your a programmer!

im not wasting my time playing guessin games!

100% this is related to mod files!

post links to the site or pm me the login detaisl!

this is not happening when i upgrade or install! this is an issue you have caused your self and you want me to fix it with giving 0 information!

hurry up!

**Comment by danielkerr** [comment]
i know the db table prefix was missing

**Comment by danielkerr** [comment]
> Re-confirmed all files in the upload folder was uploaded via FTP to overwrite: (see below).

// Helper
require_once(DIR_SYSTEM . 'helper/general.php');
require_once(DIR_SYSTEM . 'helper/utf8.php');
require_once(DIR_SYSTEM . 'helper/json.php');

function start($application_config) {
require_once(DIR_SYSTEM . 'framework.php'); 
}

confirmed you the function is there and its your issue!

**Comment by pnair39** [comment]
@danielkerr I added the db table prefix that was missing and re-ran the upgrade, receiving same error, one question should I delete the database and re-run the upgrade? How do I send you a private message you since I don't see that option under my account. Thank You.

**Comment by danielkerr** [comment]
try cealring your cookies.

**Comment by danielkerr** [comment]
send me a pm via the opencart forum

username Daniel

**Comment by danielkerr** [comment]
also are u doign command line installs?

because i havernt checked that in ages.

**Comment by pnair39** [comment]
just sent the login with the corrections.

**Comment by danielkerr** [comment]
you do know you have many files int he worng directories. its a mess!

**Comment by danielkerr** [comment]
could it be that you have the install index.php as you main index.php!!!!

**Comment by danielkerr** [comment]
well ur paths are wrong for a start!

if i do 

echo __FILE__;

it says

/public_html/Demo/index.php

but when loading the path used is:

/public_html/system/startup.php

you have caused this issue your self!! instead of complaining maybe you shoudnt have been messijgn with the index.php code int he first place! wasting my time! you should not even be rportign crap liek this!

only developers who are upgrading the default versoin should post issues here! because its for devs!

**Comment by pnair39** [comment]
I am looking into the path used /public_html/system/startup.php. Since when I put the old files and old systems back in it work without issues. I am looking at the index. php to see if it has to do with the following: define('DIR_SYSTEM', str_replace('\\', '/', realpath(dirname(__FILE__) . '/../')) . '/system/');

**Comment by danielkerr** [comment]
ethier way dont post here. ask my staff, use the forums, pay a dev

**Comment by pnair39** [comment]
Corrected Path issue, also ran on a fresh install upgrade, same error

Sent: Wed Jul 06, 2016 8:55 am
From: pnair39
To: Daniel 
define('DIR_SYSTEM', str_replace('\', '/', realpath(dirname(FILE) . '/../')) . '/system/');

corrected:

define('DIR_SYSTEM', str_replace('\', '/', realpath(dirname(FILE) . '/../')) . '/Demo/system/');

Only thing that I can assume the upgrades won't work in Sub-Directories, due to path and changes in scripts.I also created another sub folder installed fresh copy of opencart 2.1.x.x and ran upgrade it created the same error so it's the path in the scripts.

**Comment by danielkerr** [comment]
you need to create folders in your public html for each site then move each sites files into those folders. then edit htaccess to redirect depending on which domain they are coming from to the corresponding folder.  you shoudl nto have multiple instances of opencart running in each others directories

**Comment by pnair39** [comment]
here's the outcome:

/home/amillio8/public_html/Demo/
/home/amillio8/public_html/Demo/system/
/home/amillio8/public_html/Demo/index.php
Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/amillio8/public_html/Demo/index.php:29) in /home/amillio8/public_html/Demo/system/library/session.php on line 30

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/amillio8/public_html/Demo/index.php:29) in /home/amillio8/public_html/Demo/system/library/session.php on line 30

Warning: Cannot modify header information - headers already sent by (output started at /home/amillio8/public_html/Demo/index.php:29) in /home/amillio8/public_html/Demo/system/library/session.php on line 50

Warning: Cannot modify header information - headers already sent by (output started at /home/amillio8/public_html/Demo/index.php:29) in /home/amillio8/public_html/Demo/system/library/response.php on line 12
