### ISSUE TITLE
OpenCart 2.3.0.0 Beta Checkout issue

### ISSUE THREAD

**Issue by mallone** [opencart/opencart#4621]
Fresh new install with standard settings getting these errors during checkout. Cannot checkout at all.

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

OK

<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Error: Password not accepted from server!' in C:\xampp\htdocs\2300\system\library\mail.php:286
Stack trace:
#0 C:\xampp\htdocs\2300\catalog\model\account\customer.php(55): Mail-&gt;send()
#1 [internal function]: ModelAccountCustomer-&gt;addCustomer(Array)
#2 C:\xampp\htdocs\2300\system\engine\loader.php(178): call_user_func_array(Array, Array)
#3 [internal function]: Loader-&gt;{closure}(Array, Array)
#4 C:\xampp\htdocs\2300\system\engine\proxy.php(25): call_user_func_array(Object(Closure), Array)
#5 C:\xampp\htdocs\2300\catalog\controller\checkout\register.php(234): Proxy-&gt;__call('addCustomer', Array)
#6 C:\xampp\htdocs\2300\catalog\controller\checkout\register.php(234): Proxy-&gt;addCustomer(Array)
#7 [internal function]: ControllerCheckoutRegister-&gt;save()
#8 C:\xampp\htdocs\2300\system\engine\action.php(51): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\2300\catalog\controller\startup\router.php(25): Action-&gt;execute(Object(Registry))
#10 [internal function]: Control in <b>C:\xampp\htdocs\2300\system\library\mail.php</b> on line <b>286</b><br />

**Comment by LucasKauz** [comment]
Seems like a problem in the e-mail configuration. Have you configured setting/setting > Email?

I don't think it's right to show the error (many ajax fails because of this), but it's the error that you are getting.

**Comment by mallone** [comment]
Yes Email has been configured like on all our test boxes so nothing different there.

**Comment by mallone** [comment]
Disregard this. This is not an issue.
