### ISSUE TITLE
Missing design links on the admin menu

### ISSUE THREAD

**Issue by LucasKauz** [opencart/opencart#4622]
The beta 2.3b is missing  some links that exist in the folder like Design/Theme

The Folder
https://github.com/opencart/opencart/tree/master/upload/admin/controller/design

Part where it's hidden
https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/column_left.php#L219

Sorry if I missed something, but as a theme developer this release would be used to adapt to the new version.

**Comment by danielkerr** [comment]
do not uyse those files. they are unfinished. left them in there.
