### ISSUE TITLE
2.2.x dont send any email

### ISSUE THREAD

**Issue by vonhellsing** [opencart/opencart#4624]
I lost 4 hours in fone with my host, and nothing
don't send any email:
Register, Buy, nothing

:(

**Comment by CoverUp** [comment]
did you test the mail function alone? Try community forum regarding this. regards

**Comment by danielkerr** [comment]
nothing has been changed on the mails accept alert mails.

**Comment by jamesallsup** [comment]
Send fine for me on local and smtp on dev machine and test build servers.

**Comment by danielkerr** [comment]
use the contact us form on the oc web site.
