### ISSUE TITLE
Edit product / General – Description area - "Picture" Button Bug

### ISSUE THREAD

**Issue by Jakursmu** [opencart/opencart#4625]
Found a edit product / general / desctiption / "Pictuer" button issue, OC2.2. 

Path
Edit product / General – Description area.

When using the insert "picture" button in the "description" box, only images that are located on page 1 of the default Image Manager page, will insert into the Description box. Any images located elsewhere are not inserted into the description box, but when attempted to insert into description box,  are displayed in new browser tab.

A found work around is using the </> button, and manually entering the code for the desired images, then view, then save.

Any suggestions? 

Alex

**Comment by danielkerr** [comment]
check your config.php and make sure you have http image path is correct,

**Comment by danielkerr** [comment]
also try using the latest master branch
