### ISSUE TITLE
Customer password reset bug

### ISSUE THREAD

**Issue by andrejuseu** [opencart/opencart#4630]
Hi,

In [customer.php] (https://github.com/opencart/opencart/blob/master/upload/catalog/model/account/customer.php#L103-105) L103-105 should be:
```php
public function editPassword($customer_id, $password) {
		$this->db->query("UPDATE " . DB_PREFIX . "customer SET salt = '" . $this->db->escape($salt = token(9)) . "', password = '" . $this->db->escape(sha1($salt . sha1($salt . sha1($password)))) . "', code = '' WHERE customer_id = '" . $this->db->escape($customer_id) . "'");
	}

**Comment by higagan** [comment]
why?

**Comment by andrejuseu** [comment]
Client can't change his password in password reset page.

**Comment by danielkerr** [comment]
dont post imaginary fixes!

from the password change page:

$this->model_account_customer->editPassword($this->customer->getEmail(), $this->request->post['password']);

	public function editPassword($email, $password) {
		$this->db->query("UPDATE " . DB_PREFIX . "customer SET salt = '" . $this->db->escape($salt = token(9)) . "', password = '" . $this->db->escape(sha1($salt . sha1($salt . sha1($password)))) . "', code = '' WHERE LOWER(email) = '" . $this->db->escape(utf8_strtolower($email)) . "'");
	}

**Comment by andrejuseu** [comment]
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/account/reset.php#L26

There's no $this->customer->getEmail() function in use.

**Comment by danielkerr** [comment]
1st off you never specified the page!

2nd 

$customer_info = $this->model_account_customer->getCustomerByCode($code);

has 

$this->model_account_customer->editPassword($customer_info['email'], $this->request->post['password']);

it does not need customer_id and would only break a load of stores.

**Comment by xmanflash** [comment]
While andrejuseu fix works, the problem is that the variable $customer_info['email'] being passed to editPassword() is actually the customer_id. 

Which is why reset password in OC2.2 doesn't work.

 $customer_info = $this->model_account_customer->getCustomerByCode($code);

It has been fixed in GitHub.. 

catalog/model/account/customer.php

	public function getCustomerByCode($code) {
		$query = $this->db->query("SELECT customer_id, firstname, lastname, email FROM `" . DB_PREFIX . "customer` WHERE code = '" . $this->db->escape($code) . "' AND code != ''");
		return $query->row;
	}

**Comment by qahmad81** [comment]
hi everyone

you can use this ocmod to fix this issue, by upload it vie admin -> Extension Installer
https://drive.google.com/file/d/0B2-nzvg31rU7WVZnLWhmM3kzeUE/view

am add another function is resetPassword use $customer_id, and change it in controller to use this function
