### ISSUE TITLE
Admin adding order - customer group selection ignored

### ISSUE THREAD

**Issue by RichardThomas1** [opencart/opencart#4633]
Testing 2.3.0.0-b1

Two related issues:
1. If the customer is not registered and you select a group with different prices, it is ignored. It works as expected if the group is also available in the storefront settings but if not, then admin can still select the group but it is not applied.
2. If admin add an order for a registered customer belonging to one group and you change the group for this order, the new selection is ignored and prices follow the customer's account settings only (although the new group selection is now saved with the order it does not use this to calculate the prices).

**Comment by andrei-bogdan** [comment]
Hi,

I have also tested this on OpenCart v2.3.0.2 and I can confirm the customer group is ignored (price also) http://take.ms/gTtsQ no matter what you select from the dropdown, when you place an order from admin http://take.ms/JgOsN

**Comment by danielkerr** [comment]
ok closing this as andrei-bogdan  seems to have solved the problem without any changes

**Comment by danielkerr** [comment]
ok reopened

**Comment by danijelGombac** [comment]
This issue is related to the code from  opencart/upload/catalog/controller/api/customer.php

```
// Customer Group
			if (is_array($this->config->get('config_customer_group_display')) && in_array($this->request->post['customer_group_id'], $this->config->get('config_customer_group_display'))) {
				$customer_group_id = $this->request->post['customer_group_id'];
			} else {
				$customer_group_id = $this->config->get('config_customer_group_id');
			}
```

This should be removed, so the admin can choose internal customer groups, which are not available in store.

**Comment by RichardThomas1** [comment]
Made that change to 2.3.0.2 and now prices neither follow the selected group or the nor an existing customer's group - can only create order with default prices ???

**Comment by RichardThomas1** [comment]
My comment relates to the commit - not tried removing code suggested by danijelGombac

**Comment by danijelGombac** [comment]
Try remove this and replace:

`'customer_group_id' => $customer_group_id,`

with

`'customer_group_id' => $this->request->post['customer_group_id'],`

**Comment by RichardThomas1** [comment]
It appears to require both the commit by Daniel and the change proposed by danijelGombac  👍
With both changes made it appears to work.

**Comment by RichardThomas1** [comment]
The VQmod to make it easy for others:	

`<file path="catalog/controller/startup/startup.php">
		<operation error="log">
            <search><![CDATA[	
			if ($this->customer->isLogged()) {
			]]></search>
            <add position="replace" offset="4"><![CDATA[
			if (isset($this->session->data['customer']) && isset($this->session->data['customer']['customer_group_id'])) {
 				// For API calls
 				$this->config->set('config_customer_group_id', $this->session->data['customer']['customer_group_id']);
			} elseif ($this->customer->isLogged()) {
				// Logged in customers
				$this->config->set('config_customer_group_id', $this->customer->getGroupId());
			]]></add>
        </operation>
    </file>		

	<file path="catalog/controller/api/customer.php">
		<operation error="log">
            <search><![CDATA[		
			'customer_group_id' => $customer_group_id,		
	     ]]></search>
            <add position="replace"><![CDATA[
			'customer_group_id' => $this->request->post['customer_group_id'],
	     ]]></add>
        </operation>	
    </file>`
