### ISSUE TITLE
OPENCART 1.5.4.1 - POP UP Spam at checkout index.php file

### ISSUE THREAD

**Issue by DONNYBRASCO9** [opencart/opencart#4635]
Hello,

I recently had a customer contact us because at the checkout a pop up appeared with showing countries missing and some websites spam at the bottom.

Forunately template monster advised to look in the index.php file and when i did i saw the spam websites from the popup in there. I deleted this and the issue was resolved.

**My question is how do i stop this from  happening again, and how did this happen in the first place?**

Best regards,
Donny

**Comment by danielkerr** [comment]
github is not the correct place to report this. the spam maybe an extension you installed. or freehosting spam.
