### ISSUE TITLE
Version 2.3.0.0_b1 Error framework.php on line 86

### ISSUE THREAD

**Issue by pnair39** [opencart/opencart#4641]
Fatal error: Call to undefined method Loader::library() in /home/amillio8/public_html/Demo/system/framework.php on line 86

**Comment by danielkerr** [comment]
stop posting here! 

your version of opencart is highly modified!

this is not a FAQ!

**Comment by pnair39** [comment]
actually I did a test on the stock opencart version upgrade and received the error,

**Comment by danielkerr** [comment]
no one else is having this issue!
