### ISSUE TITLE
Shipping_pincode error

### ISSUE THREAD

**Issue by chitreshgoyal1** [opencart/opencart#4643]
OC 2.1.0.1 
Login in customer account
on checkout page I got this error
shipping_pincode in /home/juniperf643/public_html/system/storage/modification/catalog/controller/checkout/shipping_address.php on line 53

**Comment by CoverUp** [comment]
check the path and look
/modification/

Thats mean an issue with an extension, not with the core.

Use the forum instead or ask for extension's support, please dont use github for this kind of issues.
