### ISSUE TITLE
Old extensions are still broken on 2.3 (+ fixes)

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#4645]
Old extensions installed on 2.3 need a few more updates to get them working properly. I've tested out the following three edits, and they're working fine in all my tests. This allows older extensions to be installed and used on 2.3, with the exception of any code loading OpenCart model files, like this:

$this->load->model('total/sub_total');

If using those, developers will need to update their code since I don't see an easy way to fix that. The edits I used to fix this are as follows:

```
IN:
/system/engine/loader.php

AFTER:
$output = $action->execute($this->registry, array(&$data));

ADD:
if ($output instanceof Exception) {
	$action = new Action(str_replace('extension/', '', $route));
	$output = $action->execute($this->registry, array(&$data));
}
```
```
IN:
/admin/model/user/user_group.php

AFTER:
$data[$type][] = $route;

ADD:
if (strpos($route, 'extension/') === 0) {
	$data[$type][] = str_replace('extension/', '', $route);
}
```
```
IN:
/system/library/language.php

REPLACE THE load() FUNCTION WITH:
public function load($filename, &$data = array()) {
	$_ = array();
	
	$language_directories = array(
		'english',
		$this->default,
		$this->directory,
	);
	
	foreach ($language_directories as $language_directory) {
		$file = DIR_LANGUAGE . $language_directory . '/' . $filename . '.php';
		$old_file = DIR_LANGUAGE . $language_directory . '/' . str_replace('extension/', '', $filename) . '.php';
		
		if (is_file($file)) {
			require($file);
		} elseif (is_file($old_file)) {
			require($old_file);
		}	
	}
	
	$this->data = array_merge($this->data, $_);

	return $this->data;
}
```

In that last edit I added a loop because it results in less code, but you could also manually run the three "if(is_file($file))" statements separately, like OpenCart currently does. 

Please include these fixes, to minimize the work developers will need to do to get their extensions working in OpenCart 2.3! Thanks!

**Comment by OpenCartAddons** [comment]
+1

Maintaining a separate download package for v2.3 because extension files were moved will be a pain.

Thanks @ClearThinking

**Comment by danielkerr** [comment]
I dont think extension chages i did can ever really be made compatible but if we can make the more simple ones work it should be ok.

**Comment by danielkerr** [comment]
as dfor the fixes above, you should be able to provide the fixes using events without altering core code.

**Comment by ClearThinking** [comment]
I agree that you can't always make backwards-compatibility possible, but in this case, if you don't add these fixes *every* single extension is going to be broken on 2.3. If you do add them, *many many* extensions will work on 2.3, without needing any changes at all.

Isn't that a better thing to offer people who download the new version? Instead of waiting weeks or months to get 2.3-compatible versions of extensions (depending on the speed of the developer), they'd be able to use most of them immediately. I haven't experienced any issues when testing out the changes, so I don't see any downside to adding them, unless there is something I've missed.

**Comment by danielkerr** [comment]
Yes ok will add

**Comment by OpenCartAddons** [comment]
@danielkerr Thanks!  This will save a lot of headaches

**Comment by ClearThinking** [comment]
Thank you! I'm sure everyone will appreciate it.

I haven't seen any issues in my testing, but if you see any issues with any of the edits let me know and I'll see if I can come up with a different way to accomplish the task.

**Comment by DAKSWANG** [comment]
Very good!
