### ISSUE TITLE
doubt template engine

### ISSUE THREAD

**Issue by prhost** [opencart/opencart#4647]
I'm fixing the part of engine and especially the twig, had to take a doubt, hesitate one way to access configs within the template engine? Twig has some important settings and it would be interesting to let the config OpenCart. I needed to spend `$registry` into the Template Class:

`$template = new Template($this->registry->get('config')->get('template_type'), $this->registry); `

it is good practice?

**Comment by danielkerr** [comment]
i like to keep thing sperate. maybe beeter feeding a an array o config settings.
