### ISSUE TITLE
Issue in installation

### ISSUE THREAD

**Issue by robingupta2008** [opencart/opencart#4649]
Hi, I was trying to install newer version i.e. opencart 2.2.0.0 but could not install it successfully. Its giving me 500 server error in database credentials step. I also tried to install older versions and its working fine. Any guess for this issue in newer version?

**Comment by danielkerr** [comment]
php version? server? 

why do people think that other people have these abiltites: 

mind reading
clairvoyant
guessing 
magic powers

**Comment by robingupta2008** [comment]
HI,
Details are as below:

Php version : 5.4.45
Server: Apache/2.2.15 (Red Hat)

Thanks

**Comment by danielkerr** [comment]
switch to 5.5 maybe

**Comment by gnovaro** [comment]
check apache logs
