### ISSUE TITLE
CHECKOUT CONFIRM BUTTON KEEPS LOADING WITHOUT SUCCESS PAGE ON VERSION Version 2.1.0.2

### ISSUE THREAD

**Issue by kenny99** [opencart/opencart#4650]
PLEASE HELP ME FIX A BUG ON MY COMPANY WEBSITE WHICH HAS DRIVEN MOST OF MY CUSTOMERS AWAY BECAUSE MY CHECKOUT CONFIRM BUTTON KEEPS LOADING WITHOUT SUCCESS PAGE ON VERSION Version 2.1.0.2

**Comment by CoverUp** [comment]
this behavior happen when you don't get a properly answer on the ajax call, go to the forums for help

**Comment by kenny99** [comment]
thanks Daniel, I have posted that on forums and no one could help me out, Please I really need this to work because my company is going down everyday due to that error

**Comment by kenny99** [comment]
Thank so much @CoverUp, I have posted that on forums and no one could help me out, Please I really need this to work because my company is going down everyday due to that error

**Comment by anhchienhoang** [comment]
Do you have any logs of that issue?

**Comment by kenny99** [comment]
please how do I get the logs , Although I believe my issue is from (openbay/ebay_order.php) I have error logs enabled so should I copy all the error logs and share ?

**Comment by anhchienhoang** [comment]
Yup, in order to debug the issue, we need the logs.

**Comment by kenny99** [comment]
ok Thanks let me share you the error log, I clicked on the button myself and this is the error  { PHP Notice:  Trying to get property of non-object in /hsphere/local/home/c333861/kenexpress.com/catalog/model/openbay/ebay_order.php on line 586 }

**Comment by anhchienhoang** [comment]
hmm, it's Notice and doesn't break the application. Did ebay_order work before?

**Comment by danielkerr** [comment]
you should have said it was openbay!

james will fix it. you can call openbay directly if you like.

**Comment by jamesallsup** [comment]
@kenny99 Create a ticket at https://help.welfordmedia.co.uk - supply your store info and the OpenBay Pro support team will look into your issue.

**Comment by kenny99** [comment]
thanks so much Guys, I really appreciate, I will create a ticket immediately.
