### ISSUE TITLE
Question - Twig design considerations

### ISSUE THREAD

**Issue by sergei-maertens** [opencart/opencart#4652]
Pardon me if this is not the correct place for this question, and I also want to mention beforehand that I did not check the current Twig implementation in depth, however I have a few questions:

1. Will it be possible to modify the Twig environment that's used? For example, I want to be able to register custom extensions to the Twig environment that's used. I feel this should be possible and supported in core without any OCMode/VQMod shenanigans.

2. The templates I saw that are being redone in Twig don't seem to use the inheritance system (`{% extends 'foo.html' %}`), but other blobs of HTML rendered via different templates. The `{% block <blockname> %}` system is one of the most powerfull features in decent template engines, will this be supported? And did you consider replacing the `{{ header }}` stuff with includes, e.g. `{% include 'header.html' %}`?

**Comment by danielkerr** [comment]
its not finished yet. we can have an array of config settings maybe fed through thr constructor. which features do you want to use?

maybe not though because i dont want any executable code in the templates.

**Comment by sergei-maertens** [comment]
I do realize this is in development, which is why I am asking if it will be
supported or not.

The features I would need are the ability to register my custom Twig
extension and/or add TokenParsers:

    $twig = new Twig_Environment($loader);
    $twig->addExtension(new Project_Twig_Extension());

    $twig = new Twig_Environment($loader);
    $twig->addTokenParser(new Project_Set_TokenParser());

Other features would be to use different loaders, but that's probably less
important.

I don't see how this has anything to do with executable code in the
template, care to elaborate?

Also, could you comment on point 2. with regards to the inheritance system?

**Comment by danielkerr** [comment]
because if you look at the dev branch i have built a template editor. i dont want people being able to save php code and it being executable because its insecure which would not be good for opencart cloud.

**Comment by danielkerr** [comment]
i can maybe add this.

**Comment by sergei-maertens** [comment]
It's clear that being able to execute arbitrary PHP code is a bad thing and
should be avoided, but I fail to see how this relates to the ability to
register custom extensions. Mind explaining that link?
