### ISSUE TITLE
Feature request: option to use different password hashers

### ISSUE THREAD

**Issue by sergei-maertens** [opencart/opencart#4653]
At the moment, it looks like account and customer passwords are only `sha1` hashed - with a salt and the sha1 hash is applied twice. However, `sha1` is definitely not the best/most secure way to hash passwords - it's easily parallelized to bruteforce on GPUs for example.

I'd like to be able to use `bcrypt` or `pbkdf2` with a work-factor that can be specified to increate the password hash strength and make the hash computation slow by design to avoid brute-forcing.

Thoughts?

**Comment by RichardThomas1** [comment]
This is only useful if someone already has a copy of the passwords (i.e. accessed the database), in which case they have all the time to brute-force (and access to other sensitive data).

An improvement I would suggest however is re-encrypting the password using the latest method (whatever method is decided upon) when the customer loggs-in using a password that is less secure, i.e. if password = $this->db->escape(md5($password)) then I suggest it should be re-encrypted with a salt.

**Comment by sergei-maertens** [comment]
+1 on the suggestion to re-encrypt.

And yes, it's obvious that when they have access to the hashes, there is a larger problem at stake, but things like that can happen if there are any undiscovered SQL Injection attacks or other vectors. You cannot 100% guarantee that OpenCart has no vulnerabilities, so you should assume the worst from a security point of view. I don't see any reason NOT to use or at least offer the latest and greatest password hashing mechanisms. In fact, PHP has it built in since 5.5 and for older versions (5.3.7 and up, but who is running on that without feeling ashamed?) there is a third party implementation, see http://php.net/manual/en/faq.passwords.php

**Comment by danielkerr** [comment]
its actually sha1 3 times.

I agree but there are not really that many solutions that wont be cracked with more powerful machines. like amazon cloud services.

go to hash cat and you will see they dont have an oc brute force attack. because when you hash multiple times. the 1st hash is like setting a 32 char password. most people use 6 - 15 chars. it would be quicker buteforcing some ones password rather than trying to use rainbow tables.

**Comment by sergei-maertens** [comment]
The point isn't that it's uncrackable, if you throw enough time and money at it, every password can be bruteforced in the end. The point of stronger hashing algorithms is to buy yourself time and delay the cracking as long as possible.

I am talking about bruteforcing and not using rainbow tables - sha1 is relatively easy to bruteforce since it can be parallelized on the GPU. 2 times, 3 times hashing doesn't really matter that much, it's an arbitrary number. If in two years triple sha1 hashes turn out to be easily cracked, you cannot just update the hashing algorithm that's used in OC without running the extra hash call again on all existing passwords.

Support for different hashers and strong hashers in core would make it easy to increment the work factor of pbkdf2 for example, and could allow hashes to be upgraded to the strongest hasher automatically on login of a user. This is a proven pattern in the Django framework and probably in others as well.

**Comment by danielkerr** [comment]
ok what i can do is add the option so users can choose the hash algo they want to use.

**Comment by sergei-maertens** [comment]
That seems reasonable

**Comment by CoverUp** [comment]
I think that the hability to choose the hash and the times that you apply it, will customize the installation enough in order to stronger the security, after all in an opensource project, what you don't know is what protects you.

**Comment by danielkerr** [comment]
So my plan after doing some research is have a customer_password table.

So the fields would be

Customer_id
Salt
Password
Type

The have in settings have a list of php installed hashing algorithms.

**Comment by sergei-maertens** [comment]
Can I suggest taking a peek at how Django does it?
https://docs.djangoproject.com/en/1.9/topics/auth/passwords/ this is a
solid and battle tested implementation

**Comment by prhost** [comment]
Instead of customer_password be a table called customer_login supporting types of login, continues with the aforementioned fields put some options, and some extra field, each type can be an instantiated class that handles the login as you want, supports any type of login and password, also for example login by social network.

**Comment by NachoAbril** [comment]
In this context, although it is old it is worth to read: https://blog.mozilla.org/webdev/2012/06/08/lets-talk-about-password-storage/

**Comment by ecsiron** [comment]
As an option to connect this module in OC. If you collect money, he will hold the customization. design we are able to change. https://github.com/ulogin/ulogin-OpenCart

**Comment by danielkerr** [comment]
big thx to @goofygoblin

https://github.com/opencart/opencart/pull/5798
