### ISSUE TITLE
PayPal Express payment total

### ISSUE THREAD

**Issue by beechyrb** [opencart/opencart#4656]
We are currently using discounts tab for some products, the discounted price we use 3 numbers after the decimal (23.9920). 

The issue is that PayPal Express payment totals seems to be getting calculated differently than the order totals do and therefore PayPal payment amount is almost always different than the actual order totals.

**Comment by Felix-Ho** [comment]
The reason is from paypal express API, you can see the total only counting 2 decimal places.
https://developer.paypal.com/docs/api/payments/#payment_create
