### ISSUE TITLE
Login credentials aren't sent thru SSL

### ISSUE THREAD

**Issue by physicalit** [opencart/opencart#4659]
I've just installed opencart, latest version, i set up the ssl, and blocked all http requests in order to use ssl and i was surprise to find out that the login credentials aren't sent thru ssl, the i confirmed it with wireshark, just to make sure i'm not mistaking. Is this a bug or is it intentional?

**Comment by danielkerr** [comment]
which login? customer, affiliate, admin?

**Comment by danielkerr** [comment]
are u sure you not using an extension?

**Comment by danielkerr** [comment]
this code

$data['action'] = $this->url->link('common/login', '', true);

public function link($route, $args = '', $secure = false) {

also did you set the SSL url up in the config.php's?

**Comment by danielkerr** [comment]
also which version are u using?

**Comment by danielkerr** [comment]
i dont believe this. I think user error
