### ISSUE TITLE
special chars for database password during installation

### ISSUE THREAD

**Issue by stijn1989** [opencart/opencart#4661]
I was at step 3 of the installation. I entered my database password (mPDO) but got an access denied error for the database user. I have a '<' char in the password. For quick fix, I opened /system/library/db/mpdo.php and added follow line before the connection was made:

`$password = html_entity_decode($password);`

Then the installation was complete.

**Comment by prhost** [comment]
There really is this problem has been fixed in Mysqli connection but not in mPDO, I believe you have to change the controller and not the driver.

https://github.com/opencart/opencart/blob/master/upload/install/controller/install/step_3.php#L275

**Comment by danielkerr** [comment]
it already had it here. 

			$mysql = @new MySQLi($this->request->post['db_hostname'], $this->request->post['db_username'], html_entity_decode($this->request->post['db_password'], ENT_QUOTES, 'UTF-8'), $this->request->post['db_database'], $this->request->post['db_port']);


will add for PDO

**Comment by drakanor** [comment]
I just encountered the very same issue after changing the admin password in the profile settings.

I set the admin password to "VS#t[]X<^Y4E" but had to login with "VS#t[]X&lt;^Y4E".

**Comment by ADDCreative** [comment]
@drakanor This issue is for the database password. For user passwords see issue https://github.com/opencart/opencart/issues/7009.
