### ISSUE TITLE
Gift Vouchers Sending Problem

### ISSUE THREAD

**Issue by bau720123** [opencart/opencart#4664]
I am using 2.2.0 version

when I send Gift Vouchers to somebody，it will show this message
![02](https://cloud.githubusercontent.com/assets/5110085/16866192/cab53170-4a9c-11e6-9c9e-dcc073c2631b.jpg)
but in fact，the sending function is work，because I can receive that email
![03](https://cloud.githubusercontent.com/assets/5110085/16866214/f2a64246-4a9c-11e6-927b-ff193a6bf179.jpg)

**Comment by bau720123** [comment]
fixed
[before]
`
$symbol_left = $this->currencies[$currency]['symbol_left'];
$symbol_right = $this->currencies[$currency]['symbol_right'];
$decimal_place = $this->currencies[$currency]['decimal_place'];
$value = $this->currencies[$currency]['value'];
`

[after]
`
$symbol_left = isset($this->currencies[$currency]['symbol_left']);
$symbol_right = isset($this->currencies[$currency]['symbol_right']);
$decimal_place = isset($this->currencies[$currency]['decimal_place']);
$value = isset($this->currencies[$currency]['value']);
`

**Comment by CoverUp** [comment]
you are overwriting info with true/false values!! you will break the formatting process with this, that's not a fix.

**Comment by bau720123** [comment]
hi @CoverUp 
oh???really???
but after I did that，the email can receive correctly too
and the warning message will never appear again
well...do you have a better way to solve it ?

**Comment by CoverUp** [comment]
The problem is solved here, revert your changes and apply this one instead
https://github.com/opencart/opencart/pull/4671

**Comment by bau720123** [comment]
tested...
OKOK
thanks @CoverUp
