### ISSUE TITLE
How to create New page module in opencart 2.2 ?

### ISSUE THREAD

**Issue by dinumarathe** [opencart/opencart#4666]
I want to create custom dynamic page in opencart  and i want to access it from my dashboard/admin panel.

**Comment by mhcwebdesign** [comment]
Please post it on the OpenCart forum. This is for bug reports only.

**Comment by danielkerr** [comment]
I think in the extension soon store

**Comment by cartbinder** [comment]
Had created an extension for this on opencart :
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=23821&filter_search=extra%20pages&filter_username=cartbinder

@danielkerr  planning this for 2.3 so i can help and make a commit..
