### ISSUE TITLE
Options Error

### ISSUE THREAD

**Issue by sully210** [opencart/opencart#4667]
I have a restaurant site that has 4 options for a meat choice. I have no problems when I add 3 meat choices to a product. When I add the 4th meat option, everything goes awry. For some reason, different meat options that I have already entered are discarded and/or are missing choices that I have entered. I have tried renaming options, using different sort order values and everything else I can think of and nothing is working. The error I get varies from undefined index option_value_id to option_value_weight, etc.. I need to know how to fix this so m sites work correctly. Any help is greatly appreciated. Here is the latest error message that I got:

> Notice: Undefined index: points in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 131Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: option_value_id in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: weight in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Notice: Undefined index: weight_prefix in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Warning: Cannot modify header information - headers already sent by (output started at /home/chesters/public_html/clinton/admin/index.php:84) in /home/chesters/public_html/clinton/system/library/response.php on line 12

>

**Comment by sully210** [comment]
I have increase the maz_input_vars to 75000 from 50000 in the php.ini file and I am now getting this error:

> Notice: Undefined index: points in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 131Notice: Undefined index: weight in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Warning: Cannot modify header information - headers already sent by (output started at /home/chesters/public_html/clinton/admin/index.php:84) in /home/chesters/public_html/clinton/system/library/response.php on line 12Notice: Undefined index: points in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 131Notice: Undefined index: weight in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Warning: Cannot modify header information - headers already sent by (output started at /home/chesters/public_html/clinton/admin/index.php:84) in /home/chesters/public_html/clinton/system/library/response.php on line 12

> 

The first three options are correct and the fourth is missing option values. I entered 16 and there are only 6 showing.

**Comment by sully210** [comment]
Here is a video of one problem: [http://screencast-o-matic.com/watch/cDioXGizUo](url)

**Comment by sully210** [comment]
This is the error I get after completing the steps in the video:

> Notice: Undefined index: points in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 131Notice: Undefined index: weight in /home/chesters/public_html/clinton/admin/model/catalog/product.php on line 175Warning: Cannot modify header information - headers already sent by (output started at /home/chesters/public_html/clinton/admin/index.php:84) in /home/chesters/public_html/clinton/system/library/response.php on line 12``

**Comment by danielkerr** [comment]
This is not the place to post ur issues. I can not replicate this issue. Use the forums
