### ISSUE TITLE
how to remove whitespaces from resized images and not to further resized image with whitespcaes

### ISSUE THREAD

**Issue by Hashhu** [opencart/opencart#4669]

**Comment by Hashhu** [comment]
whitespace character *, actuallly my images are being resized with the new name having whitespace characters and it causes me problem while sharing on fb

**Comment by MrPeach** [comment]
Turn them into PNG files - when they scale the "whitespace" gets turned into transparent.
You will have to do some other monkeying around with config.php so the former "whitespace" will have the content you desire.

I can give you further help with config.php, just let me know what you are seeing and what you want instead.

**Comment by Felix-Ho** [comment]
Please use A-Z, a-z, number, - , _ for the file name.
Try don't use / ; ' * or those special characters on the name since it might cause issue from the system while loading the image path.
