### ISSUE TITLE
Unable to View Customers in Admin - Parse Error

### ISSUE THREAD

**Issue by cf1224** [opencart/opencart#4689]
Hi,

I just installed Opencart 2.2.0.0, placed an order on my store to test it. Then, I deleted the order in Admin, and clicked on Customers in order to delete the customer I just created. But, I was unable to do this because when I clicked on 'Customers' a blank white page appeared with the error message:

Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /home/xxxxxx/public_html/storedomain.com/admin/controller/customer/customer.php on line 1105

Regards

**Comment by danielkerr** [comment]
this was fixed in the master ages ago

**Comment by cf1224** [comment]
As the error is still occurring, then it doesn't look like it was fixed completely?
