### ISSUE TITLE
Passive FTP mode

### ISSUE THREAD

**Issue by samirkumardas** [opencart/opencart#4690]
Hi,

I often get a very common issue related with server's firewall configuration which is causing extension installer malfunction. For example, following error:

> <b>Warning</b>: Invalid argument supplied for foreach() in <b>public_html/admin/controller/extension/installer.php</b> on line <b>338</b>

When I added `ftp_pasv($connection, true);` , it fixed the issue.

So I believe it would be great if you add a new option `FTP Connection Mode` in store setting.

Thanks
Samir

**Comment by PlumbPal** [comment]
This worked a treat when my extension installer was failing on FTP.

Thanks

**Comment by danielkerr** [comment]
im closing this as i will remove ftp install int he next release.
