### ISSUE TITLE
Problem with Reward

### ISSUE THREAD

**Issue by ishwaindustries** [opencart/opencart#4695]
Can any one please tell us how can we change reward point value because we give any  costomer to 10 Point with Every product
1. customer buy 10 product then they have 100 Point (Like USD 500 total)
2. next Customer give order 2000USD and they rendome point of 100 so discount is applied 100% and they order free

can you please how can we solve 1point to 1USD

**Comment by danielkerr** [comment]
there is no correlation of 1 usd to 1 reward point. dont use decimals with reward points!



.
