### ISSUE TITLE
Cart API removed automatically from cart table

### ISSUE THREAD

**Issue by onusgit** [opencart/opencart#4696]
hello

I am preparing API for the add product in cart table, I success to insert in cart table, but there is strange.
When I POST data from REST client POSTMAN with specific session id, its insert in table but after 2-3 min its auto remove from cart table.

its working fine when i insert product in cart from website..

My function only insert data in cart table, is there other associate table too which i have to manage with cart table?

please guide me to fix it, I am new on opencart. I am preparing API using cakephp.

thanks,
jaysukh

**Comment by danielkerr** [comment]
did you setup the cross site policys?

**Comment by danielkerr** [comment]
also ask in the forums on how to do stuff not here.

**Comment by onusgit** [comment]
I don't know "cross site policys"

**Comment by danielkerr** [comment]
look at the api code in opencart. its already been done.

**Comment by harmis-tech** [comment]
Hello,

same issue i am getting now When I POST data from REST client POSTMAN with specific session id, its insert in table but after 2-3 min its auto remove from cart table.

So can you please help me and my API in codeignitor.

Thank you,
HarmisTechnology
