### ISSUE TITLE
Force HTTPS/SSL

### ISSUE THREAD

**Issue by nasirkhan** [opencart/opencart#4699]
Recently i developed a website using Opencart. I need to set HTTPS for all the pages. I found several posts on several forums and made the following changes. 

1. Updated htaccess and added the following lines, 
```
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R,L]
```

2. Updated the site and admin config
3. Modified the `link` function at `system/library/url`

But the HTTPS issues is not fully resolved, i can still browse the HTTP URL of the home page http://DOMAIN.COM. I need a solution for this. 

As i modified the core library function new version update will overwrite these change. Is this the only to force HTTPS or there are other better approaches?

**Comment by CoverUp** [comment]
you got to properly configure your server, that's all. OC by default only activate the https on "secure" pages, if you want to use https in the entire site you got to make that changes on your server, not in OC. Anyway, this is not the place to discuss this, go to OC forum instead or hire someone. regards.

**Comment by elcopdoo** [comment]
Poštovani,

trenutno sam van ureda.
Vraćam se 08.08.

I am currently out of the office.
I'll be back on 08.08.
Your email will not be forwarded.

Za sve hitne upite molim vas da kontaktirate
kolege u uredu:
Renato Novak: (040)804-083
Milivoj Balić: (040)804-087
Spomenka Patafta: (040)804-082

Lijep pozdrav,
Denis Dobranić
Elcop d.o.o.
