### ISSUE TITLE
Stupid Firefox password autocomplete causes admin issues

### ISSUE THREAD

**Issue by MrPeach** [opencart/opencart#4700]
See Mozilla release 38 [release note](https://www.mozilla.org/en-US/firefox/38.0/releasenotes/) - "autocomplete=off is no longer supported for username/password fields". This is not an end user user issue, solely a problem for admins using Firefox v38+ and saving their admin logins.

Because of this, any form that contains a field with (input type="password") will be filled with the saved admin password and in some other preceding text field the saved admin user name. 

A hackish fix for this is to place the following at the top of all non-admin forms with a password type:

```
    <input type="text" style="display: none;" />
    <input type="password" style="display: none;" />
```

This seems to absorb both the username and the password autofill without affecting the rest of the form. It would be nice if this could be patched in the distribution code.

It should be noted that there was some talk of adding this "feature" to other browsers in the future.

**Comment by RaidoDev** [comment]
This solution will not work anymore. The right way to do it would be to use ```autocomplete="new-password"```. 
http://stackoverflow.com/a/30976223/1720476
This still does not help for LastPass plugin, but I have contacted LastPass support

**Comment by danielkerr** [comment]
great! post a solution once i have closed the issue.

**Comment by danielkerr** [comment]
i can not replicate this issue. if i want to login to the admin the username and password are in the browser
