### ISSUE TITLE
Can I access theme path from .tpl template?

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#4702]
In OC1, when `$this->config->get` was available from templates, we could use template folder path in `header.tpl` or `footer.tpl`.

Now, in OC2 - global class is not available in .tpl files.

Shouldn't be any variable to get rid of theme directory name dependency? 

https://github.com/opencart/opencart/blob/master/upload/catalog/view/theme/default/template/common/header.tpl#L25

**Comment by danielkerr** [comment]
global class ?

**Comment by arnisjuraga** [comment]
I mean "direct" way to access template name? 

Now I am using this in `header.tpl`: 
~~~php
$config = $this->registry->get('config');
$theme = $config->get('config_template');
~~~

**Comment by danielkerr** [comment]
__FILE__

dont asked questions here!
