### ISSUE TITLE
Summernote 8.1 - Cannot add links to images

### ISSUE THREAD

**Issue by trueliarx** [opencart/opencart#4703]
Adding links on images is not working from the first rel of summernote in OC, including 2.3beta.

Reference on summernote issues.
https://github.com/summernote/summernote/issues/226
https://github.com/summernote/summernote/pull/1854

**Comment by danielkerr** [comment]
please have a go at summer note about this. i can not find another good online WYSIWYG editor.

**Comment by danielkerr** [comment]
ok found a solution

**Comment by RaidoDev** [comment]
https://www.bersling.com/2016/05/12/best-wysiwyg-for-web-content/
