### ISSUE TITLE
2 bugs in release 2.3.0.0

### ISSUE THREAD

**Issue by evgenekorolev** [opencart/opencart#4709]
1) Please add the missing text "$_['entry_width']      = 'Width';)" in all Dashboard extensions.
<img width="472" alt="screen" src="https://cloud.githubusercontent.com/assets/18613768/17272973/fe001d98-56ad-11e6-92b5-397c40030b31.png">

2) Please remove the duplicate Anti-Fraud in Extensions.
<img width="270" alt="screen_2" src="https://cloud.githubusercontent.com/assets/18613768/17272993/b52f97e6-56ae-11e6-8f13-8dd7f2fe02d9.png">

**Comment by evgenekorolev** [comment]
fixed in 2.3.0.3
thank you!

**Comment by businessera** [comment]
Евгений подскажите как избавиться от дублей? https://yadi.sk/i/Qpu48yR0vMLx3

**Comment by evgenekorolev** [comment]
Вам лучше обратиться к разработчикам или на соответствующий форум. я на таком уровне кодом не владею
