### ISSUE TITLE
MySQLi error handling fails 

### ISSUE THREAD

**Issue by mdutra555** [opencart/opencart#4724]
I have consistently reproduced this issue in WAMP development and LAMP PHP7 production environments. When mysqli executes a query with sql syntax error it returns the errno, error and error_list values; but immediately after executing another line of code (any code at all) these values are cleared making it impossible to return the error number and description. I've tried several alternatives to retrieve these error values to no use. It is most likely a PHP 7 MySQLi driver issue; I don't believe it to be an OpenCart issue. Nevertheless, if the OpenCart team can solve this issue I greatly appreciate. 

`//*** calling mysqli query will a obvious sql syntax error`
`$db->query("DROP TABLE IF EXISTS fff oc_rwd_category");`

`//*** Altered DB::MySQLi query() method to test issue.`

`public function query($sql) {
        $query = $this->connection->query($sql);

```
    //*** This line of test code proves that any code after the query above wipes off the error values.
    $error = mysqli_error($this->connection);

    if ($query) {
        if ($query instanceof \mysqli_result) {
            $data = array();

            while ($row = $query->fetch_assoc()) {
                $data[] = $row;
            }

            $result = new \stdClass();
            $result->num_rows = $query->num_rows;
            $result->row = isset($data[0]) ? $data[0] : array();
            $result->rows = $data;

            $query->close();

            return $result;
        } else {
            return true;
        }
    } else {          
        throw new \Exception('Error: ' . mysqli_error($this->connection) . '<br />Error No: ' . mysqli_errno($this->connection) . '<br />' . $sql);
        //throw new \Exception('Error: ' . $this->connection->error . '<br />Error No: ' . $this->connection->errno . '<br />' . $sql);
    }
}
```

`

**Comment by johnwongoc** [comment]
OpenCart doesn't support PHP7 yet. Please reconfigure your environment.

**Comment by osworx** [comment]
@johnwongoc  That is not true!
I am running 8 clients with OC 2.3.0.2 and php 7.1 without any problem.
