### ISSUE TITLE
Image Manager redirects to image

### ISSUE THREAD

**Issue by tabarjack** [opencart/opencart#4729]
When clicking an image within a folder, instead of putting the image in the summernote box, the Image Manager redirects to the image itself. 

I've tried with and without htaccess
Setting 777 on everything
Tried locally.
Tried removing conditions in the file

Problem occurs in version 2.2

After reading through the 2.3 code, it shouldn't happen anymore as the offending code has been rewritten and moved to another file.

For anyone else finding this issue:
in Admin's common.js find `$('#modal-image a.thumbnail').on('click', function(e) {`
replace it with `$('#modal-image').on('click', " a.thumbnail", function(e) {`

**Comment by ivanssa** [comment]
@tabarjack Hello thank you for sharing this solution was searching for weeks and have no hope you saved my job ... thank you

**Comment by ivanssa** [comment]
I also found the same solution here https://github.com/opencart/opencart/issues/4532
