### ISSUE TITLE
oc 2302 extension list added anti-fraud twice

### ISSUE THREAD

**Issue by yvonn** [opencart/opencart#4734]
anti-fraud is added twice in extension list, choose: 
anti-fraud (3) 
anti-fraud (0)

**Comment by OpenCartAddons** [comment]
Delete the file admin/controller/extension/extension/menu.php

This file was accidentally left in during the beta but has since been removed from the official release.

**Comment by Eliottiosdevs** [comment]
@yvonn delete admin/controller/extension/extension/menuphp this fixed for me i got this too

**Comment by yvonn** [comment]
yes thanks :-)
