### ISSUE TITLE
Possible security flaws: Cross Site Scripting

### ISSUE THREAD

**Issue by arocha01** [opencart/opencart#4735]
I'm working for a university project related to information security, i do test in a local machine to the opencart software with open source tools, the results were the following:

*Tool: OWASP ZAP 2.5.0
Cross Site Scripting (Reflected)

URL: http://192.168.179.139/index.php?route=javascript%3Aalert%281%29%3B
Parameter: route
Attack: javascript:alert(1);

URL: http://192.168.179.139/index.php?information_id=4&route=javascript%3Aalert%281%29%3B
Parameter: route
Attack: javascript:alert(1);

*Tool: Subgraph Vega 1.0
Cross Site Script Include

Resource: /catalog/view/theme/default/template/module/pp_login.tpl
Classification: Environment
Script Source: https://www.paypalobjects.com/js/external/api.js

Resource: /catalog/view/theme/default/template/payment/eway_iframe.tpl
Classification: Environment
Script Source: https://secure.ewaypayments.com/scripts/ecrypt.js

*Tool: XSSer 1.7b

[I] Target: http://192.168.179.141/index.php?path=57&route=product%2Fproduct&product_id=VECTOR
[+] Injection: http://192.168.179.141/index.php?path=57&route=product%2Fproduct&product_id=<STYLE>.X{background-image:url("9863229884ff8e3b9e28350504681e55");}</STYLE><A CLASS=X></A>
[-] Method: xss
[-] Browsers: [IE6.0|NS8.1-IE]

[I] Target: http://192.168.179.141/index.php?path=57&route=product%2Fproduct&product_id=VECTOR
[+] Injection: http://192.168.179.141/index.php?path=57&route=product%2Fproduct&product_id=VECTOR/ [ None ]
[!] Special: This injection looks like a Cross Site Referer Scripting
[-] Method: xsr

I would like to give me your opinion.

Thanks

Antonio Teixeira

**Comment by danielkerr** [comment]
i think your wasting my time
