### ISSUE TITLE
Opencart Minor Security Issue

### ISSUE THREAD

**Issue by cf1224** [opencart/opencart#4736]
If you give someone Admin access to your website (e.g. web developer etc), they can also see your FTP username and password by going to Settings > FTP, as it is displayed as text, rather than black dots.

It would be better if the FTP Username and Password are displayed as black dots, rather than the actual text.

Thanks

**Comment by danielkerr** [comment]
That's what permissions are for

**Comment by cf1224** [comment]
Yes, but if you forget to block access to the Settings, or make a mistake and think the box was checked, when it actually wasn't. This is when the security issue can occur. Better to be safe, rather than sorry. This is why it would be better if the FTP Username and Password are displayed as black dots, rather than the actual text.

Thanks

**Comment by trinkaljuneja** [comment]
Still you can check what behind black dots by changing input type password to input type text in inspect element

**Comment by danielkerr** [comment]
the issues closed because the dev version already had the ftp settings removed.
