### ISSUE TITLE
Opencart Admin Access Permissions Issue

### ISSUE THREAD

**Issue by cf1224** [opencart/opencart#4737]
When assigning access permissions for a user, it is not possible to block access to the Dashboard. The dashboard contains some information which you may not want certain users to view. For example, Total Orders, Total Sales, World Map, Sales Analytics etc.

It would be better if 'Dashboard' was added to the Access Permission section of the User Groups.

Thanks

**Comment by Felix-Ho** [comment]
We already have it on the system.
You can change the permission from
admin > users > user group
edit the user group permission (make sure you are not modifying  the Administrator user group)
find out the permission name like
    extension/dashboard/
and change it.

**Comment by cf1224** [comment]
There is no Dashboard option in the User Groups.

**Comment by Felix-Ho** [comment]
It's under
Dashboard > system > user > user group.
If you still have issue, please send us support request from
https://www.opencart.com/index.php?route=support/support

**Comment by derekvotresite** [comment]
Yeah.. that option "extension/dashboard/" doesn't exist un the permission list.
