### ISSUE TITLE
Publishing OpenCart (2.3.0.2) to Packagist

### ISSUE THREAD

**Issue by stefanhuber** [opencart/opencart#4738]
Many developers work extensively with composer in their projects. It would be critical to have opencart's latest releases also available via packagist (as soon as the github tag is available). There is an easy to setup github hook, configurable via github project settings.

Currently 2.3.0.2 is missing at packagist!

**Comment by danielkerr** [comment]
you already posted once here:

https://github.com/opencart/opencart/issues/4717#issuecomment-236681223

dont repeat the same ****ing posts! im busy and will do it when i have time!
