### ISSUE TITLE
Iphone/Safari admin menu button not working

### ISSUE THREAD

**Issue by ivanssa** [opencart/opencart#4739]
Hi All, 

I tried searching for a solution for this problem but haven't found anything at all anywhere.
If you try to log into any opencart 2.x admin area on an iPhone with safari, it appears you can't click the menu button to make the vertical menu slide out from the left. Nothing happens, I've tried it on opencarts demo site, same problem.

I am using an iPhone 5s with safari, but when i downloaded chrome it work fine.
I have also tried on an iPhone 6 with safari and get the same issue.

Does anybody have any bright ideas on how to fix this problem? It's like it just isn't recognizing the click event in the javascript.

Any help would be much appreciated!

**Comment by andrei-bogdan** [comment]
Hi, just tested out demo.opencart.com/admin on iPhone SE with Safari, iOS v.9.3.3 and it works just fine.

It might be a local problem, try to update the OS and browser and test again.

![iphone-safari-oc-admin](https://cloud.githubusercontent.com/assets/6366895/17481205/773c26de-5d84-11e6-8874-a73a065d2b0c.jpg)

**Comment by ivanssa** [comment]
@andrei-bogdan Thanks for the feedback, the day looking for a solution after his test I decided to do some more checks and found that the problem occurs only when the safari is in private mode, I think it's something in the related Common.js to sessionStorage that does not load the data in private mode, but I believe that the responsive menu could also work in the private mode without the need to load the sessionStorage, any solution to this bug?

**Comment by andrei-bogdan** [comment]
Hi,

I have been investigating this further and it seems it is a general issue on Safari, when browsing in Private mode: http://take.ms/Bu17g

Found a solution for this here: http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

This issue can be fixed in OpenCart by editing `admin/view/javascript/common.js` and replacing this:
```
localStorage.setItem('column-left', 'active');
```
with this:
```
if (typeof localStorage === 'object') {
    try {
        localStorage.setItem('column-left', 'active');
    } catch (e) {
        Storage.prototype._setItem = Storage.prototype.setItem;
        Storage.prototype.setItem = function() {};
        alert('Your web browser does not support storing settings locally. In Safari, the most common cause of this is using "Private Browsing Mode". Some settings may not save or some features may not work properly for you.');
    }
}
```
This will also send a message to inform the user, you can remove that if it's not needed necessarily.

**Comment by ivanssa** [comment]
Hello @andrei-bogdan  I would like to thank you very much, this fix worked perfectly thank you.
