### ISSUE TITLE
Opencart 2.3 -Change the image sizes in product and in catalog

### ISSUE THREAD

**Issue by bonvilleorganic** [opencart/opencart#4745]
Early version of opencart 2.0, 2.2 has option of changing the image size in setting>Image or in Extension>Theme

please if any means of changing the image size can be done in  Opencart 2.3 let me know.

Advance Thanks

**Comment by andrei-bogdan** [comment]
Hi, in OpenCart 2.3 you can go to Extensions > Extensions > choose Themes from the 'Choose the extension' type selector and then click > Edit on your theme, to view the Images section and change your image sizes. 

This is not an OpenCart issue, you should address this kind of requests on OpenCart Forum at http://forum.opencart.com/ as stated here https://github.com/opencart/opencart#reporting-a-bug

**Comment by bonvilleorganic** [comment]
Thank you for your quick Response..... Once again Thanks for saving my time ...
Have a Great Day .. :+1:

**Comment by andrei-bogdan** [comment]
Hi, you're welcome, please close this issue if it's solved.
