### ISSUE TITLE
Sale Order Access Permission don't Work

### ISSUE THREAD

**Issue by Hiei78** [opencart/opencart#4754]
I happen to create a group only able to access sale order in opencart 2.1.0.2, 
But the group still able to delete the sale orders even I only give them access permission and not modify permission...

**Comment by danielkerr** [comment]
because it uses the api.

**Comment by Hiei78** [comment]
So you mean that if we turn off the API it will work? , And is there any
way to turn off API in opencart? Thanks

**Comment by danielkerr** [comment]
block them from having permission to view the page maybe.
