### ISSUE TITLE
Unable to save layout in 2.3.0.2

### ISSUE THREAD

**Issue by b-and-p** [opencart/opencart#4763]
Hi, I just downloaded v2.3.0.2 today to test and update some of my modules.
I am unable to add any module to a layout and save it.

**Details**
I am able to add a module to each section `Column Left`, `Column Right`, `Content Top`, `Content Bottom`, these do save. However, the actual module, selected for each slot is not retained - all fields are set to `Account`.

After saving, success message is displayed and there are no errors in the log either.

![screen shot 2016-08-15 at 08 30 pm](https://cloud.githubusercontent.com/assets/8944029/17664516/3c64ffb0-6327-11e6-9056-d372897b5dfc.PNG)

![screen shot 2016-08-15 at 08 31 pm](https://cloud.githubusercontent.com/assets/8944029/17664519/4147d5e8-6327-11e6-82c4-310a7b7a6d72.PNG)

![screen shot 2016-08-15 at 08 28 pm](https://cloud.githubusercontent.com/assets/8944029/17664486/f8947dc4-6326-11e6-9e07-b4a6359d7495.PNG)

**Comment by andrei-bogdan** [comment]
Hi, just tested it and I can confirm the same issue is happening on my end:

http://take.ms/sfFBJ

The modules are not displayed in the front-end either.

**Comment by florinsith** [comment]
Are you clicking the + button after selecting a module?

**Comment by andrei-bogdan** [comment]
That did the trick in my case :) sorry for the misunderstanding. 
If @b-and-p can confirm it, then the issue should be closed.

**Comment by b-and-p** [comment]
Ok, I see that it works when I click the plus button to add a new module. I don't understand the interface though. Below is the what you see with fresh install:

![screen shot 08-17-16 at 02 49 pm](https://cloud.githubusercontent.com/assets/8944029/17727178/2dae2488-648a-11e6-93d1-f3607c5e73c6.PNG)

![screen shot 08-17-16 at 02 55 pm](https://cloud.githubusercontent.com/assets/8944029/17727285/e441c9ca-648a-11e6-8229-1bdf1510b38b.PNG)


What are these default `Account` items in each layout panel? You can't delete nor change them and they do nothing (it appears). Could someone explain? Thanks.

**Comment by danielkerr** [comment]
ok so putting please select on each one would be better.
