### ISSUE TITLE
OpenCart v2.3.0.2 - Extension Installer

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#4771]
Hello.

OpenCart v2.3.0.2 - Extension Installer

Windows platform:
I always got "Invalid file type!"

Linux platform with Mod Security:
I always got "Not Acceptable". One of the rule of Mod Security block uploading files.

Please can you improve Extension Installear as have WordPress platform. There is not that kind of problems. Thank you!

**Comment by danielkerr** [comment]
It also depends on the minute type of the zip file. Try WinZip or 7z or what ever it's called

**Comment by danielkerr** [comment]
Mine type

**Comment by danielkerr** [comment]
Mime type

**Comment by faca5** [comment]
Hello.

I tried with random extension, AJAX Quick Checkout which have "install.xml".

Uploading it doesn't work **smooth** on different platform.

On WordPress platform I don't have that kind of problem (still uploading zip file).

I think that part of platform can be improved.

It should work on different platform and settings.

**Comment by shyandsy** [comment]
@danielkerr 
Is that extension must be installed by extension installer from 2.x?

**Comment by Felix-Ho** [comment]
There are two different type of extension OCMOD and VQMOD.

OCMOD extension can using the backend built-in extension installer to upload and install it(make sure you enable FTP configuration from your backend)

VQMOD have to install vqmod on your opencart system before you install the extension.
And VQMOD extension require you to using server FTP or cpanel to upload the extension file directly to your opencart system folder.
https://github.com/vqmod/vqmod/wiki/Installing-vQmod-on-OpenCart

If you got the error Invalid file type!
Double check if you using the wrong way to install it.
