### ISSUE TITLE
Login and Pay with Amazon Refund status stuck on 'Pending'

### ISSUE THREAD

**Issue by onaqc** [opencart/opencart#4772]
The status of a refunded order using Amazon does not update past 'Pending'. The refund works from within the Opencart admin and shows correctly in the Amazon Sellers Dashboard. I am running 'Login and Pay with Amazon' in sandbox mode on Opencart v2102. Everything else works and there are no errors. I do note that the refund status in the Amazon seller's dashboard takes a short time to update from 'pending' to 'complete'.

The 'pending' status is returned to Opencart, from Amazon, when a refund is triggered. Without an additional call from Opencart, or a status update sent from Amazon, there is no way the status to be updated. Does the Amazon module ping amazon for a update status? Or is this a problem with running in Sandbox mode?

**Comment by onaqc** [comment]
Amazon informed me that they do update the status with the IPN but in my case there system was showing a 'Authorization Error'. Looking at the Amazon_Log_Pay.log I see:

2016-08-17 15:53:23 - ControllerPaymentAmazonLoginPay::ipn Data:  IPN received
2016-08-17 15:53:23 - ControllerPaymentAmazonLoginPay::ipn Data:  Incorrect security token
2016-08-17 15:59:16 - Origin

Is this a problem with working in Sandbox mode? Or is this a problem with my setup? As I have already said all other functions are working, just the refund status is not updated in Opencart.

**Comment by jamesallsup** [comment]
Added some improvements on the latest OC version but they can be easily updated on an old store ina  few minutes using the commit as a guide:
https://github.com/opencart/opencart/commit/ff697bba1c3c9143c00818e725f69e592a233c62
