### ISSUE TITLE
[LAYBUY] Opencart 2.2.0.0  checkout not working in Microsoft Edge

### ISSUE THREAD

**Issue by OrogDTS** [opencart/opencart#4773]
Greetings!
when customers are going through the checkout process in google chrome and choosing the Lay-Buy payment option everything works fine. the page redirects to paypal with no issues.
If they are using Edge browser when you click confirm order it just gets stuck on "loading" and never sends them to paypal.....

**Comment by Felix-Ho** [comment]
@OrogDTS I have run a test on opencart 2.2.0.0 fresh installation and checkout with Laybuy.
Checkout redirect successfully to paypal
![checkout2200](https://user-images.githubusercontent.com/6228720/35268163-568ba01c-0063-11e8-8ac4-fe1e4f5ce419.png)

![login2200](https://user-images.githubusercontent.com/6228720/35268172-58f21610-0063-11e8-9f3c-398201a80d07.png)

I am not sure what's the issue and would you mind try it again to see if that work for you now?
If you still have the issue, please let us know.
