### ISSUE TITLE
Session and Cookie based query

### ISSUE THREAD

**Issue by pkanetkar** [opencart/opencart#4775]
Recently I am facing a problem with opencart. I have deployed opencart project on my server. If I do not clear my cookies, I get the same pair of **PHPSESSID** and **default** values for every user in same browser.

Suppose I login with user1, I get following pair of values.
PHPSESSID=b3cq8ggm2rfn11f3nh0c49ohq7
default=e46f98b3417f41b6e6fd38da78

Now if I do not clear my cookies and login with user2 in same browser, I get same pair of values again.
PHPSESSID=b3cq8ggm2rfn11f3nh0c49ohq7
default=e46f98b3417f41b6e6fd38da78

Even I logout, I get this values in same browser everytime until I clear cookies.
Logout should expire the current cookies.

I am facing some security issues because of this behavior. Is this the standard way or should I modify it?
Please comment.

**Comment by danielkerr** [comment]
maybe you have multiple instances of oc on the same domain name
