### ISSUE TITLE
about assigning the order to customer

### ISSUE THREAD

**Issue by mortisrigor** [opencart/opencart#4777]
hi, i looked the forum and someone discussing about order editing and someone also on this project page. and i am having a problem and having a suggestion if accept from developers. also if there is an option or setting to make this work well. here is the scenario;

-customer making an order as guest
-after he/she is registering as customer
-mail/call "where is my order?"
-we are describing the point "you made as guest and after you register. so you are not able to see the order"
-trying to edit the order to assign the order to his/her account
-but everything is updating to recent "stock, price, total costs, fees etc."
-askiing from him/her to make a new order but he/she not will to do this

now i want to ask as the beginning of the issue; is there a way to change customer, address without changing any thing on order? if there is someone can please explain to do it. if not can be plan a feature to make this available? or is there any reason to working of editing like this?

because when something wrong on order name, surname, address, telephone or guest/customer issue; only way is ask from customer make a new order. but most of them are not willing to this due to lots of item on his/her cart and not willing to fill all of the fields again (for guest customers). and some of them cancelling their orders.

hope to here is the correct place and hope to hear a solution to this. because i search the forum and extension store but i can not find any solution or extension. if there is no way to make this available i will look someone to hire.

greetings.

**Comment by andrei-bogdan** [comment]
Hi,

I am not sure if I understand this right, but here's is my solution to this:

1. edit the order made as guest: http://take.ms/jvZJUV
2. use autocomplete to assign it to a different registered customer (in this case to the customer's newly created account): http://take.ms/WrYjR and you will see all the fields updated with the registered account details.
3. move on and you should see the same, previous cart and order data: http://take.ms/YF3x0 with nothing lost.

This worked fine for me on OpenCart 2.3.0.2. Is this a suitable solution for you?

**Comment by munirasim** [comment]
The one simple solution is to make customer registration compulsory at checkout and disable guest checkout so that you don't get into this situation again.

And for the orders already placed you may have to do as explained by @andrei-bogdan

**Comment by mortisrigor** [comment]
@andrei-bogdan @munirasim 
thank you for your answers.

@andrei-bogdan ; yes. you are right. you can apply a customer the order which was made by guest and there is nothing lost. but the problem is this; if you change a product price, stock status, close the product or completely delete the product; it is updated to recent time while you are editing the order.

customer buy "A" product with a price 15 $. you guess the price is wrong and you must make it 20 $. but you can not offer it from customer because it is your fault. than you update the price after the order. and if you want to change any thing on order the price is update to 20 $. OR you delete the product. or close. or change the stock status to out of stock. than when you try to edit the order you are not able to save the order like the first one which was not edited. i mean when you try to edit the order everything updating to recent store settings; price, stock, enable/disable, deleted... etc. hope i can tell.

@munirasim ; yes. you are right. i can disable the guess checkout. but customers are asking why i am must to be a register. so it must be a guess checkout.

thanks again. hope i can tell the issue. sorry for bad english.

greetings.

**Comment by munirasim** [comment]
@mortisrigor 

I just tested and found your issue valid. The solution then is to make changes in database and this is how:

1. Open PhpMyAdmin

2. Browse OC_CUSTOMER and OC_ADDRESS tables to find details of customer to whom you want to assign order X

3. Edit OC_ORDER table and update customer_id, customer_group_id and other shipping and payment details found in step 2

Save and exit. 

It's not a very good solution but it works.

**Comment by danielkerr** [comment]
cancel the order before changing the customer.

**Comment by mortisrigor** [comment]
@danielkerr 
hi,
thank you for your kind answer. but,
(sorry if it is a stupid question)

which is the correct CANCEL order status? for example i have two Cancel which was is DEFAULT one?
because i looked at store settings and localization>order status area; i can not see a select status for a default Cancel Status.

hope i can tell.
because i try canceling order and edit order but nothing change.

greetings.

**Comment by danielkerr** [comment]
any that is not in your complete or proccessing list

**Comment by danielkerr** [comment]
looking ito the customer issue

**Comment by mortisrigor** [comment]
hello, is there any new on this issue?
thanks.

**Comment by danielkerr** [comment]
this is fixed in the dev branch.

**Comment by danielkerr** [comment]
ok i see what u mean about addresses.

**Comment by danielkerr** [comment]
a temporary solution though would be to void the previous order and just add a new one. when voiding it should re add stock.

**Comment by danielkerr** [comment]
easy fix
