### ISSUE TITLE
module issues in v2.3

### ISSUE THREAD

**Issue by siriusdev** [opencart/opencart#4782]
In 2.3 modules in controller/module/ and controller/extension/module are displayed, but for controller/module it does not work correctly : 
- install() uninstall() methods are not called
- access/write rights are assigned to extension/module/[module] instead of module/[module]
- edit button link is extension/module/[module], which is working, but if user edit the rights it won't work anymore because the rights displayed in user groups are for module/[module]

My suggestion is to completely remove the backward compatibility for modules in controller/module, so we could easily adapt the modules to be compatible with all OC 2.x versions by putting the files in both directories (actually it creates a duplicate entry in module listing).

**Comment by OpenCartAddons** [comment]
A PR was submitted before the v2.3.0.2 which would correct these issues but it still has yet to be accepted.

https://github.com/opencart/opencart/pull/4712

Regards,
Joel.

**Comment by siriusdev** [comment]
Thanks Joel, didn't see it.
