### ISSUE TITLE
Option Image missing

### ISSUE THREAD

**Issue by NerQuiLes** [opencart/opencart#4785]
Hi,

I made an installation of Opencart 2.3.0.2 from scratch (without installing third-party extensions) and I can not add image options. 

![error-option-image-2302](https://cloud.githubusercontent.com/assets/17621360/17853231/781c4c68-686b-11e6-8ea0-0bb57b26ea06.jpg)

Does anyone else have this problem? Help? 

Thank you.

**Comment by florinsith** [comment]
Checkbox and Radio support image, the image option type is not needed anymore.

**Comment by NerQuiLes** [comment]
Hi,

Ok, thanks.

**Comment by mattloon** [comment]
What if the thumbnail image is still not appearing on the product page if the checkbox or radio type is selected?

**Comment by arnisjuraga** [comment]
Then it could be your theme problem, not Opencrt :(.
Try to switch to stock theme, if everything works then - look fot your themes support.

**Comment by PAVANKUSHVAHA** [comment]
@mattloon add this in your theme, product radio button option.
`<img src="<?php echo $option_value['image']; ?>" alt="<?php echo $option_value['name'] . ($option_value['price'] ? ' ' . $option_value['price_prefix'] . $option_value['price'] : ''); ?>" class="img-thumbnail" />`

**Comment by mazlie** [comment]
where should i paste di code? what file?path?

**Comment by webcorvo** [comment]
catalog\view\theme\default\template\product\product.tpl
Line 192

**Comment by Getinbuy** [comment]
I have the same problem. I see the above code in my theme, but still the images are not appearing :(
