### ISSUE TITLE
Doesnt work in UC browser 

### ISSUE THREAD

**Issue by Tauseefsaudagar** [opencart/opencart#4790]
Hi
we have installed the basic Openacart Version 2.2.0.0

The Site Doesn't works in UC Browser, Site opens well but the Product doesn't gets added into Cart, though in some Mobile it works but for most it doesn't work, we using android & Symbian mobile Phones.

Pls Guide

**Comment by Tauseefsaudagar** [comment]
Hi,
Reason for Closing this Issue ??
_________________________________________________________________________________________________________

Hi
we have installed the basic Openacart Version 2.2.0.0

The Site Doesn't works in UC Browser, Site opens well but the Product doesn't gets added into Cart, though in some Mobile it works but for most it doesn't work, we using android & Symbian mobile Phones.

Pls Guide

**Comment by danielkerr** [comment]
spam
