### ISSUE TITLE
Invalid directive in bootstrap.css at line 205

### ISSUE THREAD

**Issue by butsds** [opencart/opencart#4791]
Invalid directive in bootstrap.css at line 205 and missing fonts folder

**Comment by danielkerr** [comment]
do u mean your using a different domain name then the one you used to setup your oc store there by your browser blocking fonts beign loaded from different domain name

**Comment by butsds** [comment]
what is directive @at-root in css bootstrap? Where the bootstrap fonts folder in opencart 
assembly? bootstrap-datetimepicker used full bootstarap without bugs,
