### ISSUE TITLE
I Cannot edit order status when order reduces stock level to zero in opencart

### ISSUE THREAD

**Issue by anupjrwe** [opencart/opencart#4792]
If i try to change product status in opencart it is showing error Products marked with *** are not available in the desired quantity or not in stock!'. If product quantity is less than the order quantity which you are editing It shows this message that  Products marked with *** are not available in the desired quantity or not in stock!' or sometimes it shows json error. It is a big issue in Opencart. I want to know that how Opencart is getting on so high in the term of ecommerce websites dealing with these kind of serious issues. 

Please help if any one knows about its solutions

**Comment by danielkerr** [comment]
you have already been provided with an anwser here:

https://github.com/opencart/opencart/issues/3811#issuecomment-241953225
