### ISSUE TITLE
edit order product price change after offer expire (special or discount)

### ISSUE THREAD

**Issue by prof-jagpreet** [opencart/opencart#4798]
Dear Sir

We are developing a big marketplace using opencart in pakistan.
https://www.mygerrys.com

we choose opencart because of its flexibility and good performance .

But now we are getting a strange issue.

Suppose a customer order a product at time of sale at $100 and now the price is $200

The customer mistakenly right House NO 200 in address in place of House No 20

but when we try to edit order the price automatically changes to $200 for order.

Then we tried on other orders and same thing happens.

Then we tried on fresh install of opencart and same this repeated.

When ever order is edited the current price is taken by opencart.

Please guide us in this matter

**Comment by munirasim** [comment]
Hi!

First this isn't an issue but a situation. The code must work like this to keep ordered items' price updated. 

To deal with this situation, you may need to first CANCEL the order (without notifying customer), make changes to the order/address and then may change the order status to COMPLETE and this will keep prices unchanged.

**Comment by prof-jagpreet** [comment]
No sir
Its a very serious finance related bug
When i place new order i have follwing situations:

1. Prices of product are updated so when i place new order the prices are changed and customer will not pay me $200 for product he purchased at $100 one day ago.

2. If a coupon is used in that order then i am unable to use that coupon in new order because opencart says it is already used.

3. Same in case of voucher.

4. if shippig price is updated then it also changes in new order.

5. we are large company getting 800 to 1000 orders per day. And our prices change within hours or minutes because we have more than 10000 products. aslo prices are in hands of vendors which sell on our website.

so in all when i found this issue and place new order everything will change.

so i was looking for 1 bug and found more.
this is a serious bug sir opencart team should accept this becuse other solutions like magento, shopify, woocommerce give proper order editing module.
then why not opencart doing it?

**Comment by seglavi** [comment]
#4777 i think it is a similar issue with my issue. @prof-jagpreet ; did you try to CANCEL order? hope you can take a look to my issue too.

greetings.

**Comment by danielkerr** [comment]
dumb ass!

if your talking about laws then editing an order that has already been issued is illegal! your supposed to cancel or void the order and create a new invoice!

your also banned for being rude!!
