### ISSUE TITLE
Incorrect logic works with cycles

### ISSUE THREAD

**Issue by volodyahome** [opencart/opencart#4799]
Hello!
The upload / system / library / cart / cart.php file a lot of wrong designs `foreach ($this-> getProducts() as $product)`.
This greatly affects the DB load!
Incorrect use functions provided in cycles.
It is necessary to make `$this->getProducts()` of the loop, `$products = $this->getProducts(); foreach ($products as $product)`

**Comment by danielkerr** [comment]
go bother magento about their coding issues!

**Comment by arnisjuraga** [comment]
@volodyahome what do you mean with "reatly affects the DB load!"? 

`$products = $this->getProducts(); foreach ($products as $product)`

is completely equal to

`foreach ($this->getProducts() as $product)`

What you can do to improve performance - create public property, e.g. `$this->cartproducts` in Cart class, set this property in Cart `__construct` method with `$this->cartproducts = $this->getProducts()` and change all `$this->getProducts()`  to `$this->cartproducts`.

This would really exclude unnecessary DB queries.

**Comment by volodyahome** [comment]
@arnisjuraga at each iteration cycle, the method $ this-> getProducts (), which queries the database.

**Comment by arnisjuraga** [comment]
@volodyahome you are wrong about this this.

Based on the docs:

> The first form loops over the array given by array_expression. On each iteration, the value of the current element is assigned to $value and **the internal array pointer is advanced by one** (so on the next iteration, you'll be looking at the next element).

So, `$this->getProducts()` is returning an array, and every iteration is just advancing to the next array item. By working "kind a" with array copy.

If you want to read more:  http://stackoverflow.com/questions/1891917/does-using-a-function-in-foreach-loop-caches-the-result-or-calls-the-function-e 
or even, if you want more specific cases http://stackoverflow.com/questions/10057671/how-does-foreach-actually-work
