### ISSUE TITLE
If You create a language directory with more then 5char, it will breake OC settings (OC 2.3.0.2)

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#4802]
"code" limit is 5 chars.
"directory" limit is 32 chars.

So, if You create (without knowing, that language directory name MUST be not longer then 5 chars)
a directory "english", then:

- in db `code` will be set to "engli"
- `directory` will be set to "english"
- in Settings table `config_language` and `config_admin_language` values will be set to "english".

And - admin theme breaks - You cannot change default admin language, because it asks for Order statuses etc.etc. and so on.

You cannot change these settings from admin after this! 
Because the reference to "code" field, which has been truncated!

**Comment by osworx** [comment]
It was in 1.5. where languages has been written like `english` or `french`
The 2.x branch (and here from 2.1.x) introduced the xx-yy convention.
Read this: https://msdn.microsoft.com/de-de/library/ee825488(v=cs.20).aspx

So no one will (and should) use further `english` for example.

I am only curious what OC will do with languages like `zh-CHT` (traditional Chinese) and some other 6-letter codes .. ?

**Comment by arnisjuraga** [comment]
There is nothing bad for using language code. But this is a "bug", because currently You CAN add folder with longer name, it will appear in admin and even allow to save it (without error) .... but will truncate the data in table because of table `oc_language` schema:

![image](https://cloud.githubusercontent.com/assets/2185289/17964799/8d465246-6ac3-11e6-9487-f1cccb5a74c1.png)

**Comment by arnisjuraga** [comment]
or `Cy-az-AZ` :)

**Comment by danielkerr** [comment]
do nto posty here again! this is for developers! any one with a brain should know they can rename the language folder!
