### ISSUE TITLE
Opencart Dont work in UC browser 

### ISSUE THREAD

**Issue by Tauseefsaudagar** [opencart/opencart#4803]
Hi
we have installed the basic Openacart Version 2.2.0.0

The Site Doesn't works in UC Browser, Site opens well but the Product doesn't gets added into Cart, though in some Mobile it works but for most it doesn't work, we using android & Symbian mobile Phones.

Pls Suggest the Solution & Dont close the the issue as its important for us...
Thanks

**Comment by danielkerr** [comment]
now banning you from being able to open new issues!

stop spamming!
