### ISSUE TITLE
Too short language code field in DB

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#4807]
Sorry, @danielkerr 
but this is a bug, and Your reply #4802 is not constructive. 

- You cannot create language codes longer then 5 chars (and sorry, they exists). Be The developer and accept it.
- If language folder name MUST be the same, as language code, then there is no need for longer field in db
- this case breaks Opencart settings, if language folder name is longer. If You need, I can send or post much longer proof of that

![image](https://cloud.githubusercontent.com/assets/2185289/17997205/cf0bd2a2-6b75-11e6-9b07-4ae7bd045e59.png)

**Comment by danielkerr** [comment]
directory is no longer used! shoud be the language code used by the browser
