### ISSUE TITLE
OpenCart 2.2.0.0 Sendmail problem

### ISSUE THREAD

**Issue by jwang22** [opencart/opencart#4810]
Hi, 

I installed OpenCart 2.2.0.0 on Ubuntu 14.04. I also installed sendmail and the path to sendmail is right.

But I really don't know why the sendmail when notifying the users and changing the order history doesn't work. I googled a lot and tried to find a feasible solution. However, no existing methods can solve the problem.

I used the smtp. The email can be sent correctly with the "sendEmail" tool in Ubuntu. So the smtp configuration should be correct. I also tried the mail but still didn't work.

**Comment by danielkerr** [comment]
ask for help in the fourms.
