### ISSUE TITLE
Vouchers can be reused under concurrent access

### ISSUE THREAD

**Issue by TWarszawski** [opencart/opencart#4812]
### Description
When two customers check out concurrently using the same voucher, the voucher can be used twice.

### Steps to reproduce
1. Start site, create two customers, create/pick test product, create test voucher.
2. Both customers add the item to their carts, apply the voucher, and perform the  checkout concurrently, making sure both customers finish checkout (click the ‘Confirm Order’ button) as close to the same time as possible.

We have reproduced this behavior on a single machine, by performing the above steps with one customer in one browser window and another customer in a second browser window with a short communication delay (200 ms) between the database and application. If connecting to the database using unix sockets, the following script can act as a proxy that delays packets:
https://gist.github.com/TWarszawski/a0d8dd8aea9eb5b774d64c9f826de6db

### Expected Result:
Only one order completes using the voucher, the other order ends in the fraud status.

### Actual Result:
Both orders successfully complete using the voucher.

**Comment by danielkerr** [comment]
and blocked!
