### ISSUE TITLE
Removed obsolete Total files when upgrading

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#4815]
install/model/upgrade/1006.php:
https://github.com/pekka2/opencart/commit/66dede9dceada148f2d8d056f50127f5d6b878f5

AND change column type for table user_group to 1001.php:
https://github.com/pekka2/opencart/commit/f60eb1c76702d8a6d77a1bcdce92d38f3bc45a7e

**Comment by hkrware** [comment]
Mine weren't erased for some reason during upgrade and I had an error that it 'Could not load model total!' Why is the model removed, anyway? I can't seem to find a changelog for the 2.3.0.2?

**Comment by pekka2** [comment]
@hkrware 
You can remove folder model/total on manual.

**Comment by danielkerr** [comment]
can not find user_group in the 1001 file
