### ISSUE TITLE
Permission Denied extensions 

### ISSUE THREAD

**Issue by tekland** [opencart/opencart#4821]
Completely new install of V 2.3.0.2. Install went great and easily installed and setup a few of the onboard extensions like Paypal, and USPS. Then added Swipe payment extension. Extension install went O.K. but when clicked on install in extension list got, "You do not have permission to access this page, please refer to your system administrator."
This issue is unaddressed on many community forums ie...http://forum.opencart.com/viewtopic.php?f=191&t=166012&p=633892&hilit=permission+denied#p633892
The fixes listed like rechecking the permissions in admin user group do not solve problem.
Downloaded this fix: 
Dreamvention wrote:
"Hi everyone
made a vqmod file for the compatibilty issue based on OpenCartAddons and my pull requests

https://gist.github.com/Dreamvention/77 ... 6457c8f189 

feel free to use it untill opencart adds it to core ;)"

Does nothing as far as I can tell.

**Comment by danielkerr** [comment]
contact the extension developer!

**Comment by tekland** [comment]
Well that was a waste of time. Did you even read the report? The problem has nothing to do with the extension because it affects all extensions installed after the version 2.3.0.2 install or upgrade. Look at the fix for sale for 12.99 by guru and clearly he thinks its core.

**Comment by OpenCartAddons** [comment]
@tekland It's a known issue.  The fix can be found here https://github.com/opencart/opencart/pull/4712

Dreamvention's mod applies these changes through VQMod.  Make sure you have the latest version of VQMod installed on your site and it should work.

Regards,
Joel.
