### ISSUE TITLE
Last quantity order Edit issue!

### ISSUE THREAD

**Issue by SabirScepia** [opencart/opencart#4824]
I'm facing an issue with the product which has 1 or more and the buyer ordered whole quantity.  As I have 1 in stock the buyer ordered that or 5 quantity in stock buyer ordered total 5 of 5.  
I need to edit that order for address / name change or for other reason. Now the problem come.. " Warning: Products marked with **\* are not available in the desired quantity or not in stock! " 
So in the last step of editing you can't update / save the edited order. 

I've faced this issue on the previous version of opencart and still on the last version too! 
Screenshot: 
![screen-shot](https://cloud.githubusercontent.com/assets/21293626/18034877/55045050-6d6a-11e6-8140-d4031e7cc46a.jpg)

**Comment by webkul-dilip** [comment]
This issue resolve now please close this issue 
Version 3.0.3.6
