### ISSUE TITLE
Same cache key in admin folder and catalog for languages

### ISSUE THREAD

**Issue by trgtrg** [opencart/opencart#4825]
Here **admin/model/localisation/language.php** languages are cached with the key "language" for query 

> $query = $this->db->query("SELECT \* FROM " . DB_PREFIX . "language ORDER BY sort_order, name");

And here **catalog/model/localisation/language.php** with the same key for query

> $query = $this->db->query("SELECT \* FROM " . DB_PREFIX . "language WHERE status = '1' ORDER BY sort_order, name");

so the second query selects only active languages  and the first - all languages. This affects editing products. Here **admin/controller/catalog/product.php** there is no filter for status=1 

> $data['languages'] = $this->model_localisation_language->getLanguages();

If you're lucky and languages cached in the second case - all will be alright, but if you clean cache you won't be able to save product until you fill all necessary values for switched off languages ;-(

**Comment by NikolayEZ** [comment]
Hello trgtrg,
I have same problem like you. Have you found how to be fixed?

**Comment by trgtrg** [comment]
Hi @NikolayEZ,

You can try diff like this:
```diff
diff --git a/catalog/model/localisation/language.php b/catalog/model/localisation/language.php
index e1e15e0..2c02b20 100755
--- a/catalog/model/localisation/language.php
+++ b/catalog/model/localisation/language.php
@@ -7,7 +7,7 @@ class ModelLocalisationLanguage extends Model {
        }
 
        public function getLanguages() {
-               $language_data = $this->cache->get('language');
+               $language_data = $this->cache->get('catalog_language');
 
                if (!$language_data) {
                        $language_data = array();
@@ -27,7 +27,7 @@ class ModelLocalisationLanguage extends Model {
                                );
                        }
 
-                       $this->cache->set('language', $language_data);
+                       $this->cache->set('catalog_language', $language_data);
                }
 
                return $language_data;

```

**Comment by NikolayEZ** [comment]
Hello @trgtrg ,
Thank you for your help! This code really works.

Thank you very much again!
Nikolay
