### ISSUE TITLE
Problem with VAT calculation right after customer registration.

### ISSUE THREAD

**Issue by jeffz2012** [opencart/opencart#4827]
Hello,

Potential bug description:
If customer registers and goes shopping outright, system would use country, where store is located to calculate VAT.

Why is it bad?
Lets say store is located in Germany, where VAT is 19%.
Since last VAT Harmonization, that store has to collect different VAT for customers from different EU countries (once over minimum amount).

Lets say that customer from Poland registers and goes shopping. OC based store calculates VAT at 19%, instead of at 23% which is a proper VAT for Polish customer. This 4% difference will go out of store owner pocket.
Not something store owner is going to be wild about.

Where in code is the problem:
It is in Session Object, which is missing payment_address array, or shipping_address array - depend on backend settings in /system/settings manager.

How to fix it:
Take this code from:   catalog\controller\account\login.php

<pre>
$this->load->model('account/address');

if ($this->config->get('config_tax_customer') == 'payment')
{
   $this->session->data['payment_address'] = $this->model_account_address->getAddress($this->customer->getAddressId());
}

if ($this->config->get('config_tax_customer') == 'shipping')
{
   $this->session->data['shipping_address'] = $this->model_account_address->getAddress($this->customer->getAddressId());
}
</pre>

... and paste it into:   catalog\controller\account\register.php
somewhere inside of this conditional: 

<pre>
if (($this->request->server['REQUEST_METHOD'] == 'POST') && $this->validate())
{
}
</pre>

I put this right after:
<pre>
unset($this->session->data['guest']);
</pre>

Once you do that, all starts to work as it should.

**Comment by osworx** [comment]
Applying different VAT rates is only valid for digital goods.
Or am I wrong?

**Comment by danielkerr** [comment]
there is nothing to fix! your dont know how to setup the taxes properly!
