### ISSUE TITLE
information description cant hold more than 64KB and trim the extra text

### ISSUE THREAD

**Issue by qahmad81** [opencart/opencart#4831]
hi

when you save information that length more than 65536 char its trim the text that more than this number.

please note that field type (text) on mysql size = 64KB, so please use mediumtext that can hold 16MB of text or html code. as mysql referal there
http://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html

to fix this problem run this
`ALTER TABLE`oc_information_description`CHANGE`description`  `description` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ; `

**Comment by lz1nud** [comment]
If it's possible for the next update this proposal to be added in opencart. I have been stuggling before with longer descriptions that can't use them in the system.

**Comment by danielkerr** [comment]
ok just did a search and think its trimmed

**Comment by danielkerr** [comment]
ok its been merged so closing
