### ISSUE TITLE
$this->response->output will return "garbadge", if compression is used and ANY output has been already sent

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#4832]
I faced this problem with a custom theme, having Display errors set to "Yes". Because of this, PHP notice output was sent before response output compression and headers.
### How to reproduce:

Got to System > Settings > Edit > Server
- set "Output Compression Level" greater than 0
- Now, create any output, e.g. in `controller/common/home.php` 

```
echo "test";
```

Now, refresh home page of site. 

The site will return "garbage" data:
![image](https://cloud.githubusercontent.com/assets/2185289/18069065/5e43589e-6e4d-11e6-8a64-5fff71eb04b0.png)

This is because of the `system/library/response.php` code:
- it compresses the output (because compression is set in admin).
- then sets additional headers, because `headers_sent()` still returns "false".

as noted here: http://es1.php.net/manual/en/function.headers-sent.php#75835

> headers_sent() will return false, even if you sent something to the ouptut using print() or header() , if output_buffering is different from Off in you php.ini

It looks, running `ob_end_flush()` before output compression, send output to browser together with Headers, and not `!headers_sent()` works as expected:

```
public function output() {
  ob_end_flush();
  [..] 
```

**Comment by danielkerr** [comment]
so it should send garbage if out put is already sent.

**Comment by danielkerr** [comment]
thi sis the reason i banned you. you cant work this stuff out your self and post it as an issue.
