### ISSUE TITLE
Bug report, fatal bug in delete language function

### ISSUE THREAD

**Issue by minhvb** [opencart/opencart#4848]
You have a bug in the file admin/model/localisation/language.php , function deleteLanguage();

you use query to delete record from table oc_banner_description but you have remove it in version 2.3 so please fix that bug soon.

Best regard

**Comment by Neto-Queiroz** [comment]
Just a correction on @minhvb comment: The table name is "oc_banner_image_description"... 

When trying to exclude a language, the full error message is:
`Fatal error: Uncaught Exception: Error: Table 'oc_banner_image_description' doesn't exist<br />Error No: 1146<br />DELETE FROM oc_banner_image_description WHERE language_id = '1' in /public_html/system/library/db/mysqli.php:40 Stack trace: #0 /public_html/system/library/db.php(16): DB\MySQLi->query('DELETE FROM oc_...', Array) #1 /public_html/admin/model/localisation/language.php(222): DB->query('DELETE FROM oc_...') #2 /public_html/system/engine/loader.php(178): ModelLocalisationLanguage->deleteLanguage('1') #3 /public_html/system/engine/proxy.php(25): Loader->{closure}(Array, Array) #4 /public_html/admin/controller/localisation/language.php(88): Proxy->__call('deleteLanguage', Array) #5 /public_html/system/engine/action.php(51): ControllerLocalisationLanguage->delete() #6 /public_html/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array) #7 /public_html/system/engine/action.php(51): ControllerStartupRouter->index() #8 /v in /public_html/system/library/db/mysqli.php on line 40`

**Comment by danielkerr** [comment]
did u run through the upgrade script?

**Comment by danielkerr** [comment]
this does not happen in the dev branch.
