### ISSUE TITLE
Config alert email wrong  name

### ISSUE THREAD

**Issue by zebratratata** [opencart/opencart#4850]
In setting form field  additional emails has name config_mail_alert_email instead config_alert_email
And field "additional emails" are not saved. 
This bug in version 2.3.0.2

**Comment by priyorockz** [comment]
I have fixed this bug by updating admin's setting.php controller file and template setiing.tpl

**Comment by zebratratata** [comment]
Thanks.

**Comment by priyorockz** [comment]
It still needs to be updated in other places as well. Just noted there are confusion between $this->config->get('config_mail_alert') , $this->config->get('config_alert_email'), $this->config->get('config_mail_alert_email')

Not sure which standard is better.

The simplest way now is replace the field name from  config_mail_alert_email to config_alert_email in setting.tpl

**Comment by zebratratata** [comment]
i think will be better return name from oldest version config_alert_emails

**Comment by Greenerok** [comment]
The value, entered to textfieild, is saved to database with key config_mail_alert_email, but not displayed on settings page

**Comment by andrei-bogdan** [comment]
Hi,

I've noticed that in the latest `admin/view/template/setting/setting.tpl` file version the value `config_alert_email` is used for the textarea field name.
Does this solve the above issue?

**Comment by ClaudePlouffe** [comment]
Is there a patch for bug #4850? 
I'm running opencart 2.3.0.2
Thanks

**Comment by ClaudePlouffe** [comment]
I was able to fix in 2.3.0.2 : 
1) In setting.php controller replace config_alter_email with config_mail_alert_email on the if statement (line 1047) 

2) In setting.tpl template replace $config_alert_email with $config_mail_alert_email 
    in textarea="config_mail_alert_email" section (line 1166)

Hope it helps.

**Comment by danielkerr** [comment]
fixed in dev branch
