### ISSUE TITLE
opencart 2.3.2 bestsell dontest show on extension->module page

### ISSUE THREAD

**Issue by shyandsy** [opencart/opencart#4857]
opencart 2.3.2 bestsell dontest show on extension->module page

page: admin/index.php?route=extension/module&token=oI1StA8IDDR4fqiWOJRSqdkDWAstBQpW

why there is no bestsells module in this page?

**Comment by pekka2** [comment]
It is expired page, you look new filesystem.

**Comment by shyandsy** [comment]
dont understand you. 
Could you give some detail info?

发自我的 iPad

**Comment by pekka2** [comment]
File extension/module.php is not:
https://github.com/opencart/opencart/tree/master/upload/admin/controller/extension
Raight path is admin/index.php?route=extension/extension and you select option 'Modules'

**Comment by shyandsy** [comment]
yes，but the bestsell does not exist


发自我的 iPad

**Comment by pekka2** [comment]
What is 'bestsells'? Bestseller?

**Comment by shyandsy** [comment]
yeah.

there is a module named ControllerExtensionModuleBestSeller under catalog/controller/extension/module. I havent found this in admin extension module page

**Comment by shyandsy** [comment]
@pekka2 
why dont keep the functionality which automatically identify the module from filesystem like previous version?   Is its now must install by xml to use a module ?

**Comment by pekka2** [comment]
@shyandsy 
You is not found module list? You look here:
http://forum.opencart.com/viewtopic.php?f=190&t=167371

**Comment by shyandsy** [comment]
there are 26 modules in extension page, but there is no bestseller module

发自我的 iPad

**Comment by pekka2** [comment]
@shyandsy 
Bestsellers module is my in module list, in versions 2.3.0.3_rc and 3.0.0.0_rc

**Comment by osworx** [comment]
@shyandsy : and what do you think is this here (2.3.0.2 since 1.5.x):

![module_bestseller](https://cloud.githubusercontent.com/assets/1905204/18226825/6ae57a64-7212-11e6-8989-1bf3625399e7.png)

**Comment by shyandsy** [comment]
ok.
 I haven't saw the new version github,2.3.3 and 3.0

发自我的 iPad

**Comment by shyandsy** [comment]
I saw this file infilesystem, but does not show up in admin extension page

发自我的 iPad

**Comment by pekka2** [comment]
@shyandsy 
You is not open module list from extension list to this way?
http://forum.opencart.com/viewtopic.php?f=190&t=167371#p636859

**Comment by shyandsy** [comment]
I will show you the screenshot after I go back home

发自我的 iPad

**Comment by shyandsy** [comment]
@pekka2 
![list](https://cloud.githubusercontent.com/assets/5271457/18229057/9c45da9c-722e-11e6-81f4-ef28a6868f12.png)

no bestseller module here
