### ISSUE TITLE
opencart 2.3: Are there anyway to setup theme manually

### ISSUE THREAD

**Issue by shyandsy** [opencart/opencart#4858]
Hi,

I have old theme write by myself which works fine under opencart 2.2.

I just wanna copy the theme folder and made some change by hand in the controllers.

Looks I must use the extension installer to add theme now.

 Are there anyway to do that manually?

**Comment by shyandsy** [comment]
I did little research for this. I hope it helps for other developer who meet this problem.

My first language is not English, so, ask me if you have any problem on read this

link:
https://github.com/shyandsy/Blogs/blob/master/Opencart%202.3%20theme%20install%20analysis.md

**Comment by danielkerr** [comment]
there is afield under the defaulty theme extension that lets you choose your directory
