### ISSUE TITLE
Custom Fields Created Not Shown on Backend

### ISSUE THREAD

**Issue by robertda** [opencart/opencart#4862]
OC 2.3.0.2 (issue was not there on OC 2.2.0)
As a Admin with create / edit rights (_customer/custom_field_), i create 2 input text, required, custom fields (VAT code and another one) on **Home/Custom Fields**. 

On frontend (new customer - register form), custom fields appears (i check with _phpMyAdmin_ and everything is there), but on backend (**Home / Custom Fields**), there is no custom field.

After creating each custom fields, there is a confirmation success alert ( _Success: You have modified custom fields!_).

Best wishes.

**Comment by robertda** [comment]
My fault. Language pack was not updated accordingly (menu.php -> column_left.php)
False issue.

**Comment by helocy** [comment]
I have the same issue. How did you fix it?

**Comment by helocy** [comment]
I fixed this issue by change back-end language pack to English.
