### ISSUE TITLE
（2.3.0.2）design/layout position problem

### ISSUE THREAD

**Issue by bau720123** [opencart/opencart#4865]
in opencart 2.2.0，we can set the position value in order to show the position level
![01](https://cloud.githubusercontent.com/assets/5110085/18249339/38459de2-73b0-11e6-816e-45dcef6cd700.jpg)

but in opencart 2.3.2，seem disappear
![02](https://cloud.githubusercontent.com/assets/5110085/18249350/484e9784-73b0-11e6-83f2-b48eb2af85bc.jpg)

**Comment by danielkerr** [comment]
is it so hard for you to work out how to order the modules?? use your brain instead of wasting peoples time to reading your "duhh what do i do!!!"

**Comment by bau720123** [comment]
Hi @danielkerr
Could you please more polite
I don't know why are you so angry
I just want you to know and just want to ask you
Why in 2.2.0 have this function (the Sequence)
but in 2.3.2 disappear，that's all
