### ISSUE TITLE
SKU should be UNIQUE

### ISSUE THREAD

**Issue by 3zzy** [opencart/opencart#4868]
SKU is a reference code for an individual item, therefore it must be unique. Magento follows it and almost every other ecommerce solution. 

So it would be a good idea to make the `sku` field UNIQUE in the DB.

**Comment by tylerbenzing** [comment]
Kind of. You run in to issues with this when you think about the same item being listed multiple times but with a different quantity being sold. I'm not saying I disagree there are just arguments for both sides. As an example eBay doesn't require your SKUs to be unique
