### ISSUE TITLE
Order Number can be edited in Return Submission Page of User Module

### ISSUE THREAD

**Issue by linson007** [opencart/opencart#4879]
In User module, once the user select return some products, on that submission page, there is field for order id, it is automatically filled by corresponding order id, but user can able to edit the same with any value.
I dont know am doing wrong or not. i feel so. 
am using opencart 2.3.0.2

**Comment by andrei-bogdan** [comment]
Hi, are you suggesting it should be contained in a field which is not editable?
If you are using the default theme, you should be able to achieve that if you open file:
`catalog/view/theme/default/template/account/return_form.tpl`
and replace this:
`<input type="text" name="order_id" value="<?php echo $order_id; ?>" placeholder="<?php echo $entry_order_id; ?>" id="input-order-id" class="form-control" />`
with this:
`<input type="text" name="order_id" value="<?php echo $order_id; ?>" placeholder="<?php echo $entry_order_id; ?>" id="input-order-id" class="form-control" disabled />`

**Comment by linson007** [comment]
Hi,
Yes , am suggesting it. At the same time , i feel it as a bug since if any user choose return and user change the order id (Which is automatically filled based on order return) and the admin get confused about the order.

**Comment by labrg** [comment]
I think this can be called a bug since admin will see a different order number when viewing the return. This  shouldn't be possible!

**Comment by ADDCreative** [comment]
I believe the order ID is editable as a customer can click on the returns link in the footer without having an account. This way the customer needs to be able to supply the order ID.

**Comment by danielkerr** [comment]
this is not an issue! if customers can not learn to put the correct order id thats there fault and you have to deal with it. its just like people posting issues here with out providing any information

**Comment by dhaupin** [comment]
@danielkerr ROFL dude, seriously -- head out of the sand brother. I will explain why its an issue:

Who makes a return process with required fields that don't validate against anything? Not even an email? You can spam all order IDs for returns, that doesn't make any sense. If post email doesn't match order email, reject. Simple stuff for a cart of this age, amiright?
