### ISSUE TITLE
PHP Notice: Undefined variable: username in

### ISSUE THREAD

**Issue by GuruElmer** [opencart/opencart#4880]
I am using Opencart Version 2.3.0.2 and I am getting an error log with:

PHP Notice: Undefined variable: username in
2016-09-08 12:53:35 - PHP Notice: Undefined variable: username in /home/mysitename/public_html/mystorename/admin/view/template/common/column_left.tpl on line 5;
Can I assume the following statement is correct;

The reason why it's undefined is because it hasn't been set in the controller file first.
I used 
if (isset($username)) 
    $this->data['username'] = $this->config->get('username');
In the admin/controller/common/column_left.php and it didn't work.

I also went to https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/column_left.php dowloaded the php filie and installed it and still doesn't work.

Any idea on what else should I do?

![error_log_-_undefine_variable_username](https://cloud.githubusercontent.com/assets/1123086/18449845/c241e7f0-78fe-11e6-95e1-85d73924c310.png)

**Comment by danielkerr** [comment]
already fixed i think

**Comment by danielkerr** [comment]
int he masterbranch

**Comment by GuruElmer** [comment]
Thanks Daniel.  I went ahead and uploaded https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/column_left.php then clear up all my cache and still get the same error.

I went back to masterbranch and notice that the file says that it was updated (fb8f63e  on Aug 4
@Felix-Ho Felix-Ho Update column_left.php)

So I must be missing something.  Could you point me in the right direction?

**Comment by GuruElmer** [comment]
Well I don't know what happened.  I was having cache issue with the VQMod and installed a new version from the OC extension - Integrated VQmod for OpenCart 2 and seems that it overwrote the controller and the bug got fixed.
