### ISSUE TITLE
Composer install required

### ISSUE THREAD

**Issue by prhost** [opencart/opencart#4882]
For wearing composer package, `install composer` becomes necessary in the store installation step. Ideally, trigger an exception when not found autoload the composer and also versioning the composer.lock

See commit https://github.com/opencart/opencart/commit/0bf6f31ce7dae753c6ed38026529c4bff6593010

Take advantage and put the library of the twig also the composer.

**Comment by jamesallsup** [comment]
No.

Some hosts WILL NOT support users to use the command line so you cannot force people to run composer install - this would kill the number of people using OpenCart on lower cost hosting which is the majority of users. It is why there are 2 packages available, 1 with the packages already included and another without them.

OpenCart will work perfectly fine if you do not need the modules that use a composer dependancy, if you do then you can download the larger package or install with composer.
