### ISSUE TITLE
Orders not getting placed with Fraudlabs or Maxmind enabled

### ISSUE THREAD

**Issue by moneycarlo** [opencart/opencart#4883]
Using 2.3.0.2, orders are not going through when either Maxmind or Fraudlabs is enabled.
There's no error in the error logs or on the screen, and the payment even goes to processor.  Checking to see if the database recorded the order, I found that the order was partially recorded in the order_history table.  In the Comments field, there was an error:

`The order could not be completed normally due to the following error:<br /><br /><em>&lt;br /&gt;
&lt;b&gt;Fatal error&lt;/b&gt;:  Call to a member function check() on a non-object in &lt;b&gt;/public_html/system/storage/modification/catalog/model/checkout/order.php&lt;/b&gt; on line &lt;b&gt;267&lt;/b&gt;&lt;br /&gt;
</em><br /><br />Double-check your SMTP settings in System > Settings > Mail, and then try disabling or uninstalling any modifications that affect customer orders (i.e. the /catalog/model/checkout/order.php file). One of those is usually the cause of errors like this.`

I know SMTP works fine because if I disable the fraud mods, the order goes through fine and emails are sent out.

**Comment by danielkerr** [comment]
maybe you deleted one of your order statuses that you set maxmind or fraudlabs to use

**Comment by moneycarlo** [comment]
Nope, it's because you didnt update the extensions folder.
In catalog/model/checkout/order.php at line 268:
$fraud_status_id = $this->{'model_fraud_' . $extension['code']}->check($order_info);
should be:
$fraud_status_id = $this->{'model_extension_fraud_' . $extension['code']}->check($order_info);
