### ISSUE TITLE
Can I extend the checkout without using vQmod/OCmod?

### ISSUE THREAD

**Issue by dvlprs** [opencart/opencart#4884]
Hi everyone, 

I have a quick question. Is there any way to modify/extend the checkout process without using vQmods and OCmods? I'm talking about redoing the checkout completely, e.g. moving inputs, showing them all at once, etc. It will probably require creating a new template and probably even a controller.

I checked [the list of the event types available](https://github.com/opencart/opencart/wiki/Events-(script-notifications)-2.0.x.x-&-2.1.x.x#products-attributes-categories-options-downloads) but couldn't find anything relevant. I'm not sure this should be handled through the events either. Modules perhaps? I checked the [Developing Modules](http://docs.opencart.com/developer/module/) page and it confirms I can use modules for frontend, but I still don't understand how do I forward users from the default checkout to our custom one, and if it's possible at all.

Please just point me to the right direction. Thanks

**Comment by dvlprs** [comment]
For example, say I wanted to add a few custom links to the footer. I can edit my template and create a custom language file no problem. However, I still have to somehow map the translations to the `footer.tpl`. Normally that's done through a controller (or a vQmod modifying that controller), but is there any way to avoid doing that? It's a multilingual site so I can't just hardcode the translation into the `footer.tpl` file

**Comment by munirasim** [comment]
If event system, vqmod and ocmod are not your options, you may backup original files and re-write them using chunks of code from originals where necessary.

**Comment by dvlprs** [comment]
@munirasim, thank you for your reply.

I won't be able to upgrade easily then.

**Comment by jamesallsup** [comment]
Please use the forum, not the bug tracker for questions.

https://forum.opencart.com/
