### ISSUE TITLE
Controller event arguments not passed (catalog-side)

### ISSUE THREAD

**Issue by side-by-side** [opencart/opencart#4889]
Hello.
I'm using last Opencart 2.3.0.2 and trying to use events to modify frontend product page.
The problem: no any data are passed to event handler, except of the first argument that is route.
It is not working with /before and /after events (for example `catalog/controller/product/product/after`)

Arguments passed to event handler looks like this:
```
array (size=3)
  0 => string 'product/product' (length=15)
  1 => null
  2 => null
```
With this bug events are totally useless.

**Comment by danielkerr** [comment]
theres no data to pass!

**Comment by side-by-side** [comment]
Ok, thank you for the answer.
