### ISSUE TITLE
_route_ bugfix: SEO in multilanguage sites

### ISSUE THREAD

**Issue by yuriysamarin** [opencart/opencart#4892]
Hi,
You have a bug in the file ../catalog/controller/common/language.php
Insert Line32#  `unset($url_data['_route_']);`

so, please fix that bug in new version release.

Best regards, Yuriy.

**Comment by tylerbenzing** [comment]
What? Can you please elaborate rather than just declaring there is a bug? What happens that causes you to say it is a bug?

**Comment by yuriysamarin** [comment]
Look carefully attached my file with fixes.
Step-by-step:
1. Install OpenCart v2.3.0.2
2. Add Language ru-RU,ru_RU.UTF-8,ru_RU,ru-ru,russian
3. General Settings Use SEO
4. Rename .htaccess.txt->.htaccess
5. Go to any category, ex. http://mysite/desktops/mac (category_id=46, i.e. index.php?route=product/category&path=20_27), ok
6. And so well, change the language and see you in the browser address line: http://mysite/desktops/mac?_route_=desktops%2Fmac

i think about is not correctly string, ok?

p.s.  Sorry for my bad English, but I hope understand me... ;)

**Comment by Kolpikov** [comment]
Yuriy, thanks for your report. I had exactly the same bug with OpenCart v. 2.2.0.0 and your code fixed the problem

**Comment by thekrotek** [comment]
I just want to confirm, that the issue indeed exists in 2.3. In 2.1 everything was good and later unset($url_data['_route_']); was removed. I assume, accidentally, because it till exists in currency.php.

**Comment by amyobaid** [comment]
Hi, i have the same issue on OC 2.3.0.2.
Could you please attach your fix file as i could not find it here.

**Comment by thekrotek** [comment]
@amyobaid it is given right in the first message of this issue.

**Comment by amyobaid** [comment]
I did insert it but the issue still remain is there a cache or something to clear after?

Here what my code look like now
if (!isset($this->request->get['route'])) {
			$data['redirect'] = $this->url->link('common/home');
		} else {
		unset($url_data['_route_']);
			$url_data = $this->request->get;
			unset($url_data['_route_']);	
			$route = $url_data['route'];
			unset($url_data['route']);
			$url = '';
			if ($url_data) {
				$url = '&' . urldecode(http_build_query($url_data, '', '&'));
			}
			$data['redirect'] = $this->url->link($route, $url, $this->request->server['HTTPS']);
		}
		return $this->load->view('common/language', $data);
	}

**Comment by amyobaid** [comment]
I did insert it but the issue still remain is there a cache or something to clear after?

Here what my code look like now

if (!isset($this->request->get['route'])) {
			$data['redirect'] = $this->url->link('common/home');
		} else {
		
			$url_data = $this->request->get;
			unset($url_data['_route_']);	
			$route = $url_data['route'];
			unset($url_data['route']);
			$url = '';
			if ($url_data) {
				$url = '&' . urldecode(http_build_query($url_data, '', '&'));
			}
			$data['redirect'] = $this->url->link($route, $url, $this->request->server['HTTPS']);
		}
		return $this->load->view('common/language', $data);
	}

**Comment by amyobaid** [comment]
@thekrotek @yuriysamarin  Please check my reply above and advise if i did something wrong.

**Comment by arnisjuraga** [comment]
Depends on your deployment. try to "refresh" in admin Extensions > Modifications.
?

**Comment by amyobaid** [comment]
tried that did not change anything @arnisjuraga

**Comment by thekrotek** [comment]
@amyobaid works perfectly for me and everyone else. Might be some caching issue or 3rda party extension.
