### ISSUE TITLE
Improvement: use SQL_CALC_FOUND_ROWS for pagination

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#4894]
Hi!

Have You considered to use SQL_CALC_FOUND_ROWS and FOUND_ROWS() for pagination?

It's a pain for modules and modifications, if you modify some filters for `getProducts()`, to make the same changes into `getTotalProducts()`.

I have not tested yet the performance, but considering current SQL scheme for Opencart selects - I suppose, one select for Total and Filtered products in current code situation could be more efficient, than select all the same results twice?

http://dev.mysql.com/doc/refman/5.7/en/information-functions.html#function_found-rows

**Comment by danielkerr** [comment]
Don't post unless u know what ur doing

**Comment by arnisjuraga** [comment]
What? Sory, can You explain - what's wrong with my proposal??!?

https://github.com/search?q=SQL_CALC_FOUND_ROWS&type=Code&utf8=%E2%9C%93
