### ISSUE TITLE
replacing GLOB_BRACE 

### ISSUE THREAD

**Issue by xming** [opencart/opencart#4897]
Hi,

GLOB_BRACE is not supported some non glibc (Solaris, non GNU Linux,  etc), I have made replaced all GLOB_BRACE occurrences except in the upgrade scripts, please review this commit https://github.com/xming/opencart/commit/cdeed6ef3f1065ef6ba36630554a9568bb3af59d
Thanks

**Comment by sappelt** [comment]
I replaced all files with your versions and it caused my modifications to crash. When hitting the refresh button under modifications the following files were deleted and not newly created.

`system\storage\modification\system\engine\action.php`
system\storage\modification\system\engine\loader.php
system\storage\modification\system\library\config.php
system\storage\modification\system\library\language.php
system\storage\modification\system\library\template\php.php
`system\storage\modification\system\library\template\tiwg.php`

**Comment by xming** [comment]
Judging from the backslashes you are probably on Windows, GLOB_BRACE should be supported so there is probably no need for the patch.

That aside can you show me the error? Are you saying the files get deleted after an error and refresh?

**Comment by osworx** [comment]
@xming : interesting, is an old bug, but comes always up.
Would you recommend to read this:
[http://nl1.php.net/manual/en/function.glob.php](url)

And this:

> Note: This function isn't available on some systems (e.g. old Sun OS). 
> Note: The GLOB_BRACE flag is not available on some non GNU systems, like Solaris.

**Comment by xming** [comment]
@osworx the php manual states that it isn't supported everywhere. I run Linux VMs on which GLOB_BRACE isn't available (Alpine Linux, which Docker is migrating to too).

So I really hope this gets resolved, and I don't even know why this was closed without even any comments.

**Comment by sappelt** [comment]
You are right, that my development system is windows with xampp. Therefore I don't need this patch on my development system. My client has a strato hosting (guess we will switch) and they are running on Solaris and don't support GLOB_BRACE. 

There is no error code, simply the mod isn't running anymore after clicking the refresh button under modifications. The mod is the manufacturer description (http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26587&filter_search=manufacturer&filter_license=0). 

As I did some research was causes the error starting again with a clean system, I found out with the Git version history that the files I listed above are deleted after hitting the refresh button. If I checkout the version without the glob_brace changes, the error doesn't occur and I can refresh.

**Comment by xming** [comment]
@sappelt how are you applying the patch? Were you trying to merge/rebase with git? As you can see here https://github.com/xming/opencart/commit/cdeed6ef3f1065ef6ba36630554a9568bb3af59d there are no files deleted.

Can you try the following?
- apply it as patch (not using git) https://github.com/xming/opencart/commit/cdeed6ef3f1065ef6ba36630554a9568bb3af59d.patch on either master or 2.3.0.x and paste the output there, there should be no files being deleted
- using git: checkout my fork https://github.com/xming/opencart

And can you provide the output of `git status` and `git log stat` of the git repo where the files are deleted?

I fully

**Comment by sappelt** [comment]
Hey I think there is a misunderstanding and I am sorry for that. I will try to describe more clearly what I did: 

1) OpenCart clean install
2) Install a mod like manufacturer description (link above) 
2a) Everything runs fine, hitting the refresh button under Extensions->Modifications works fine
3) Apply the modifications of the GLOB_BRACE commit manually or using git (I changed the system files manually, copying the changes from the commit into these files)
4) Hit the refresh button under  Extensions->Modifications in the admin panel.
5) The files I listed above are deleted, after hitting the refresh button.

It is not a problem of the modification as it perfectly works without modifying the system files like in the commit.

**Comment by xming** [comment]
So the files are not deleted after the patch nor with git. It's got deleted by the php (with GLOB_BRACE replacement) am I correct? Are they deleted from the filesystem or just disappear in the Admin->Extensions->Modifications

If this is the case it's more plausible, I need to check the extensions.

**Comment by sappelt** [comment]
Yes exactly like this. The files are deleted from the file system after hitting refresh. When I revert the files manually, the modification works fine again. 

At all the mod has nothing special. That is why I had the idea, that this error is caused by the commit. Maybe it is a strange cohesion.

**Comment by xming** [comment]
Ah deleted from the filesystem, which shouldn't happen :( Can you try to modify the file permission so that apache doesn't have write access any more to those files, then it should give a php error.

I will try to find the time to test this myself.

**Comment by raffraffraff** [comment]
I'm testing your fork @xming - I'm in the early build phase so it's not a big deal switching. However, I don't expect that you'll maintain a fork going forward so it's not really a proper solution unless your code gets merged. Any update on the 'files getting deleted after hitting refresh' issue ?

@danielkerr I know this issue has been pretty quiet an' all. I just finished an alpine-based docker build and ran blind into this. With more people using docker for dev and prod, I'm sure many others will repeat the blunder, since Alpine has become somewhat of a standard (whatever about those poor bastards stuck on Solaris). So I wouldn't exactly call this a 'non issue'. If OpenCart could check for the presence of this non-portable function (or maybe avoid using it?) that would be great. It's only used in a handful of places.

**Comment by cartbinder** [comment]
I have a client who is on solaris server and same issue. If i remove GLOB_BRACE as per this commit from modification.php

**There is no error on refresh which was coming because of GLOB_BRACE**

But the modification is not picked up from system/storage/modification folder.
Any ideas @xming ?

I tried vqmod which works fine. But ocmod not working.
So shall ask the client to change to apache, linux.

**Comment by xming** [comment]
hi all, sorry that I haven't got time working on this, I was just testing opencart and never got to use it, so I did a quick replace w/o investigating if all functionalities work and w/o getting deep into the opencart's code.

@cartbinder if you want to have GLOB_BRACE you will have to use a Linux with GNU (some BSD has GOB_BRACE too)

@raffraffraff best way might be to create a php function with mimics the GLOB_BRACE, as this can be used for all php projects depending on it.

**Comment by qroft** [comment]
Thanks to this commit i was able to have most dropdowns work in the backend.
The only one not working is shippign. The dropdown select says "shipping (12)" but though i select it, the shipping methods / modules do not pop up.
