### ISSUE TITLE
Not working "Recent Activity" 2.3.0.2

### ISSUE THREAD

**Issue by danfahl** [opencart/opencart#4898]
This isnt working in new version 2.3.0.2.

**Comment by tylerbenzing** [comment]
Yes it is. Please be sure that you have it enabled by going to the Admin Panel > Settings > Stores > Edit > Option Tab > Account Section > Change 'Customers Activity' from No to Yes and Save

**Comment by danfahl** [comment]
Oww.. It's true. Thank you!
I looked everything and can't see it

<http://www.essj.com.br/>

2016-09-21 22:23 GMT-03:00 Tyler Benzing <notifications@github.com>:
