### ISSUE TITLE
Theme Issue With Multi Store 

### ISSUE THREAD

**Issue by dhaval03** [opencart/opencart#4910]
With multi store when from admin if we apply different theme for 2 different stores 

it save all theme configuration parameter properly but after configuration if we edit the configuration again it always shows default store's setting

i debug the code and found the issue that

file : admin/controller/extension/theme/theme_default.php
line : 199
$data['theme_default_image_category_width'] = $this->config->get('theme_default_image_category_width');

this should be like below

$data['theme_default_image_category_width'] = $setting_info['theme_default_image_category_width'];

and all other parameter which takes the value from config variable should be from $setting_info

file : admin/language/en-gb/extension/theme/theme_default.php
issue : 
$_['text_extension']   = 'Extensions';
is not defined

correct me if i am wrong

Thanks

**Comment by R-G-B** [comment]
@dhaval03  You're absolutely right! Opencart bugs... I can't help wondering. This major bug (guys, @danielkerr and company, it's really MAJOR bug) exists even in v.2.2 and for 6 months NOBODY fixed that, but this bug negates the whole idea of multistore themes settings conception!

**Comment by R-G-B** [comment]
Just look at this, "List description limit" is set to **111** (it is _theme_default_product_description_length_ value in db) for the **store_id = 1**
![6b2e5580df6d9b0cdd9b3e763e55fbf2](https://cloud.githubusercontent.com/assets/6608080/18892295/b3558f48-8511-11e6-9794-be35f8c87c40.png)
Now let's look at db and compare _theme_default_product_description_length_ for our **store_id=1**:
![4476ebc668911cb11a1b9460434f7c3a](https://cloud.githubusercontent.com/assets/6608080/18892276/a22e45d4-8511-11e6-881d-5f9d45fda9d7.png)
It should be equal to 222, but it is shown as 111 (as  _theme_default_product_description_length_ for our **store_id=0**)

**Comment by danielkerr** [comment]
and just banned some idiot who signed up to cause trouble!

**Comment by danielkerr** [comment]
you see this

$this->model_setting_setting->editSetting('theme_default', $this->request->post, $this->request->get['store_id']);

this piece of code separates out the different store settings based on store ID!

$this->request->get['store_id']

**Comment by danielkerr** [comment]
im quite busy at the moment. i suggest the community stands up and posts some fixes to github.

**Comment by dhaval03** [comment]
Here i have attach those 2 files with bug fixed Just in case if anybody need it

thanks
[upload.zip](https://github.com/opencart/opencart/files/497306/upload.zip)

**Comment by danielkerr** [comment]
A fix has already been issued

**Comment by R-G-B** [comment]
@dhaval03 many thanks
