### ISSUE TITLE
URL aliases of the same product for each of the languages in a multi-store setup

### ISSUE THREAD

**Issue by dvlprs** [opencart/opencart#4915]
Hello, 

I want both `example.COM/cellphone-nokia-3310-red` and `example.FR/telephone-mobile-nokia-3310-rouge` to point to the same product within a multistore. It'd load different language files, have different url_alias keywords, but it will essentially be the same product id.

I did a quick search and I can see this was kind of [mentioned](http://forum.opencart.com/viewtopic.php?t=405) all the way back in 2007, and this forum post from 2012 [language_id colum in url_alias table mutilingual routes](https://forum.opencart.com/viewtopic.php?t=88286) explains the issue as well. That means I'm not the only one who needed that. I can also see a bunch of extensions claiming to enable this feature (although my problem with the extensions is that they rely on vQmod which I'd prefer to avoid at any cost). 

So my question is this: seeing that there's some demand for the feature, why is this not implemented in the core yet? _Are there known problems with this idea that stop the community from implementing it?_ Or is it just lack of time? Or is this on the roadmap and somebody is already working on it? I was thinking about implementing and contributing this myself and wanted to make sure this'd be a good idea and there's nothing wrong with it.

**Comment by OpenCartAddons** [comment]
Submitted a pull request adding SEO URL support.

Cheers,
Joel.

**Comment by danielkerr** [comment]
and done!
