### ISSUE TITLE
Loading views with a single "." is broken - 2.3.0.2

### ISSUE THREAD

**Issue by bull5-i** [opencart/opencart#4917]
In all OpenCart versions prior to 2.3.0.x you can load views named like "mail/notification.html" and "mail/notification.txt" where the corresponding template files would be named "mail/notification.html.tpl" and "mail/notification.txt.tpl".

Since OpenCart 2.3.0.0 the system/engine/loader.php view method breaks this behaviour by stripping out all dots, even perfectly unharmful ones as described above. In previous versions only potentially harmful dots "../" were removed.

**Comment by danielkerr** [comment]
yes correct and your point?

**Comment by bull5-i** [comment]
The point is, that it should be fixed, so it would be possible to use perfectly legal file names.
