### ISSUE TITLE
Can not update an order in admin interface

### ISSUE THREAD

**Issue by ionutz89** [opencart/opencart#4918]
Hello,

I have OpenCart 2.2.

I moved my store from an old domain to a new one in the same hosting ( moved from an old directory to a new one).  When I tried to edit a order, it give me "error undefined".
I deleted old API and create a new one and I update in settings store. I also added my IP plus IP's site.

Output from inspect element from Chrome:

jquery-2.1.1.min.js:4 POST https://store.com/index.php?route=api/login send @ jquery-2.1.1.min.js:4ajax @ jquery-2.1.1.min.js:4(anonymous function) @ index.php?

route=sale/order/info&token=99j9001whxTKflRkvRfkxTWP9MZKm4fn&order_id=21:734
index.php?route=sale/order/info&token=99j9001whxTKflRkvRfkxTWP9MZKm4fn&order_id=21:1 XMLHttpRequest cannot load https://store.com/index.php?route=api/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://superfoods-wholesale.co.uk' is therefore not allowed access. The response had HTTP status code 404.

The problem from above is that it redirected to the old domain not the new one. I updated config.php from root directory + admin directory. I do not from where it gets the old domain because I need to replace with new one.
Could you please help me how to fix this issue.

Thanks !

**Comment by trinkaljuneja** [comment]
Did you check .htaccess ,

**Comment by ionutz89** [comment]
Yes, I did. No redirect rule to the old one.

**Comment by ionutz89** [comment]
I fixed myself.  You have to check on mysql and replace with new URL.
Thanks !
