### ISSUE TITLE
Cannot send enquiry in opencart 2.3.0.2

### ISSUE THREAD

**Issue by melvin16** [opencart/opencart#4928]
Hello everyone,

I tested sending enquiry but it cannot receive although there is a statement that enquiry has been sended. I just want to know that if I miss configure in mail setting or it's a bug in opencart 2.3.0.2? Any body have an opinion and I'm very appreciate for it.

**Comment by Felix-Ho** [comment]
It should due to email configuration only.
If you need help to check the setting, please submit a ticket to support @opencart.com and provide the admin login detail from there.

**Comment by melvin16** [comment]
Thank you so much Felix-Ho, I'm very appreciate for it.
