### ISSUE TITLE
Menu model typping error

### ISSUE THREAD

**Issue by lukaspijak** [opencart/opencart#4929]
Hello, 

in https://github.com/opencart/opencart/blob/master/upload/admin/model/design/menu.php#L89

you have typping error in SQL "menu**t**_id".

**Comment by lukaspijak** [comment]
Pull request https://github.com/opencart/opencart/pull/4930

**Comment by danielkerr** [comment]
its fixed in the dev branch. cheers

**Comment by danielkerr** [comment]
i dont think the menu table is used in older versions

**Comment by lukaspijak** [comment]
I noticed the table, so I wanted to try, but unfortunately it was not yet finished. But pull request I sent ;-)
