### ISSUE TITLE
$this->config->get('any_key') should be decoded automatically

### ISSUE THREAD

**Issue by phuctma** [opencart/opencart#4932]
Hi OpenCart team,

I found that most OpenCart payment modules get API password from their setting without decoding. This will pose issue in case passwords have special characters and OpenCart automatically encodes (when submitting setting form) before saving them to the database.
I think the method `$this->config->get('any_key')` should should be decoded automatically when getting the value.

**Comment by danielkerr** [comment]
no it should not, as it can lead to js and htl security issues
