### ISSUE TITLE
Select caching method

### ISSUE THREAD

**Issue by thekrotek** [opencart/opencart#4933]
I recently found out, that there're at least 3 different caching methods available in OpenCart. Unfortunately you can't select the desired method or even add such functionality with VQMod - file method is hard-coded in index.php.

Is it a bug or somehow was made deliberately?

**Comment by danielkerr** [comment]
there are also some config files that you can alter to change which engine to use!

**Comment by thekrotek** [comment]
@danielkerr Which config files? config.php? And how they will affect this, if caching method is HARD-CODED in index.php? Before posting here I googled for the solution and found none. Each and every solution suggested you to edit index.php.
