### ISSUE TITLE
 "Email to required" Opencart 2.0.2.0 Register.php

### ISSUE THREAD

**Issue by gsc1ugs** [opencart/opencart#4934]
Error - "Email to required" system/library/mail.php line 60
I cannot figure out this error, I changed to new version of register.php and mail.php but still get this error on registeration, I cannot find any solution on github?

**Comment by thekrotek** [comment]
It means, that there's no receiver's email. Relative to registration, email address is not passed to mailer thus email can not be sent. Might be related to customer's email or to administrative email, if admin notification about new registrations is turned on.

**Comment by osworx** [comment]
The user found the bug and fixed it (see forum).
This case can be closed therefore.

**Comment by danielkerr** [comment]
@gsc1ugs why are you postying here! this is not your personal support system! gthsi is the for development of opencart! not 3rd party issues!

do not post again!
