### ISSUE TITLE
Discount Coupons issue :: Calculated Without VAT

### ISSUE THREAD

**Issue by gags88** [opencart/opencart#4936]
Consider below scenarios:

**Category A :: VAT 1%
Category B :: VAT 5%**

_Scenario 1: (When only category A is added)_

- Item 1:  2454 (With VAT) [Without VAT: 2430] -  Category A
- Subtotal : 2454 (With VAT) [Without VAT: 2430]
- Discount (10%) : 243  -- But it shall be "**245**"
  
so, is it possible to apply on subtotal.. not product wise.

_Scenario 2: (When category A&B is added)_

- Item 1:  2454 (With VAT) [Without VAT: 2430] -  Category A
- Item 2:  624 (With VAT) [Without VAT: 594] -  Category B
- Subtotal : 3,078 (With VAT) [Without VAT: 3024]
- Discount (10%) : 302 -- But it shall be "**307**"

So, in both cases, Discounted applied is wrong as we are showing prices with VAT inclusion on store

**Comment by danielkerr** [comment]
Do some reasearch

**Comment by danielkerr** [comment]
Discounts don't include tax
