### ISSUE TITLE
getTotalEmailsByProductsOrdered

### ISSUE THREAD

**Issue by ghost** [opencart/opencart#4938]
Sql request in /admin/model/sale/order.php is probably wrong.
Should be:

$query = $this->db->query("SELECT COUNT(DISTINCT `email`) AS total FROM `"
return $query->row['total'];

as per use made in /admin/controller/marketing/contact.php function send()

**Comment by yushine** [comment]
Good point.

@danielkerr

**Comment by danielkerr** [comment]
fixed

**Comment by webcorvo** [comment]
in witch version?

**Comment by webcorvo** [comment]
tks
