### ISSUE TITLE
default paypal express checkout is unable to use in Opencart 2.2.0.0 

### ISSUE THREAD

**Issue by gtescreen** [opencart/opencart#4942]
if I click the button check out with paypal express.  

the page will turn to 404 pages.

I try to find every information I can find. But there's not same issue as me.

I'm researching on catalog\view\theme\default\template\payment\pp_express.tpl and pp_express_confirm.tpl

catalog\controller\payment\pp_express.php   . 

I'm compare with original opencart 2.2.0.0 by np++ . the files are exactly same.

someone give a tips let me know the way to fix it.

**Comment by danielkerr** [comment]
its fixed in 3.0
