### ISSUE TITLE
opencart 2.1.0.1 extension installer Syntax Error 

### ISSUE THREAD

**Issue by Remmy2017** [opencart/opencart#4947]
Hey guys. I hope you  can help me because I have worked for hours(google and looking in opencart forum) trying to fix the issue with no luck. The issue is when Iam trying to upload any extension using the extension installer in opencart 2.I.0.1 I get the following error

![image](https://cloud.githubusercontent.com/assets/22851629/19408387/fa639fb2-92bb-11e6-95d4-350c0daebfa4.png)

**Comment by munirasim** [comment]
Without going into details of cause and effects, you may repeat following steps:

1. Install this extension and DISABLE your FTP settings
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=18892

2. Go to USER GROUPS and edit ADMINISTRATOR (Be sure you're user of this group) and choose SELECT ALL and SAVE

Now you can upload extension and if problem still persists, please make sure you have assigned required permissions to files/folders as described in extension's documentation.

**Comment by Remmy2017** [comment]
Hey munirasim. 

Thanks for replying. I have tried following the steps you suggested but when I try to upload the extension(i have tried different extension) i get the error "FTP needs to be enabled in the settings"

Which means that to disable ftp is not solving the problem. Do you have any other suggestion??

![image](https://cloud.githubusercontent.com/assets/22851629/19411315/b653bd5e-92ff-11e6-9fcc-ab1351fbee3e.png)

best regards
Remmy

**Comment by munirasim** [comment]
You need to REFRESH MODIFICATIONS first before installing your extension since http://www.opencart.com/index.php?route=extension/extension/info&extension_id=18892 is also an OCMOD and needs refresh to work.
