### ISSUE TITLE
Product Discount not working 

### ISSUE THREAD

**Issue by abdallahmaali** [opencart/opencart#4948]
i have problem with discount  by quantity  the total take the price for 1 items 
and multiplication with the original  price   you can see the problem in the following screen shoots

<img width="323" alt="screen shot 2016-10-16 at 10 14 07 pm" src="https://cloud.githubusercontent.com/assets/5798651/19420135/ee4d9470-93ed-11e6-9c52-94ef1699f0f6.png">
<img width="479" alt="screen shot 2016-10-16 at 10 13 50 pm" src="https://cloud.githubusercontent.com/assets/5798651/19420136/f32b9320-93ed-11e6-857d-66217524a556.png">
<img width="1140" alt="screen shot 2016-10-16 at 10 14 16 pm" src="https://cloud.githubusercontent.com/assets/5798651/19420137/fb1427c8-93ed-11e6-9b4e-775942b76c2d.png">

**Comment by ADDCreative** [comment]
You need to enter the price for each product. So for 6 enter 33.1666 (199 / 6).

**Comment by abdallahmaali** [comment]
aha okay thank you
