### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by sshelzi** [opencart/opencart#4950]
On the [Demo](https://www.opencart.com/index.php?route=demonstration/demonstration) page, both the Demo [store front](https://demo.opencart.com/) button and the demo [admin area](https://demo.opencart.com/admin/) are  broken. The store front button links you back to the sites homepage while the demo admin button displays a "page not found" error.

**Comment by jamesallsup** [comment]
Thank you, this is now fixed.
