### ISSUE TITLE
opencart syntaxError in public_html/op/catalog/model/account/customer.php

### ISSUE THREAD

**Issue by maldossary2** [opencart/opencart#4953]
Dear 
hope you all are doing well. 

when i tried to register new a customers  i am facing the below exception. we need your support in this matter 

see attached 

![bug1](https://cloud.githubusercontent.com/assets/22897289/19455284/40878f0c-94c5-11e6-8404-ee36573bb108.png)

**Comment by jamesallsup** [comment]
Known issue on older version, please use the forums. https://forum.opencart.com
