### ISSUE TITLE
[AUTHORIZE.NET SIM] transaction key error

### ISSUE THREAD

**Issue by sajicodea** [opencart/opencart#4954]
Authorize.net SIM Payment is not working. Showing "Error 99: This transaction cannot be accepted."

Need to update code : \opencart\upload\catalog\controller\extension\payment\authorizenet_sim.php

Replace :
        $data['x_fp_hash'] = hash_hmac('md5', $data['x_login'] . '^' . $data['x_fp_sequence'] . '^' . $data['x_fp_timestamp'] . '^' . $data['x_amount'] . '^' . $data['x_currency_code'], $this->config->get('authorizenet_sim_transaction_key'));

with : 

```
    $data['x_fp_hash'] = hash_hmac('md5', $data['x_login'] . '^' . $data['x_fp_sequence'] . '^' . $data['x_fp_timestamp'] . '^' . $data['x_amount'] . '^' . $data['x_currency_code'], $this->config->get('authorizenet_sim_key'));
```

**Comment by JesseOC** [comment]
Checked and fixed already.
This issue will be closed.
