### ISSUE TITLE
model/catalog/option.php unavailable in catalog

### ISSUE THREAD

**Issue by dvlprs** [opencart/opencart#4956]
I [searched](https://github.com/opencart/opencart/issues?q=is%3Aissue+catalog+option+model) but couldn't find anyone else reporting and willing to fix this. I did see people needing this feature though.

In my case, I need to show a list of options in a custom module on store front. The problem is, to get those while in catalog, I have to either run a `$this->db->query` directly from within that controller file, or get all products and find their options one by one, neither of those sounds like a good idea.

I suggest creating a `/catalog/model/catalog/option.php` file with a few option-specific functions. I'm willing to do that myself and contribute. Of course I'll adhere to the coding standards and refer to the existing implementations in the admin area or other models. I wanted to ask @danielkerr if you're okay with all this, because it'd feel bad if I spend time on this and submit a pull request and you reject it because you don't want the feature :) I mean, is there a specific reason why it's not implemented and why shouldn't I do this?

Please let me know! Thanks

**Comment by danielkerr** [comment]
model/catalog/option.php unavailable?

use better titles in the future instead of missleading people!

**Comment by dvlprs** [comment]
Dear @danielkerr,

I used the title *model/catalog/option.php unavailable in catalog* because that's what it is: the option.php model isn't available in catalog (because it doesn't exist). However, I tried to rephrase the title after seeing your comment. Let me know if you can think of a better title and I'll change it, I'm not here to argue. I don't think in this case the title is that important either.

You didn't respond to the actual issue I've tried to report. I wanted to run this by you to see if you want the feature. Please share your opinion.

**Comment by danielkerr** [comment]
its not called or needed any where else. if its not there add your own code.
