### ISSUE TITLE
Compatibility Error

### ISSUE THREAD

**Issue by pcha** [opencart/opencart#4957]
The version 2.3 trie to be compatible with previous versions plugins, and for these reason list the plugins in "admin/controller/extension/payment" and "admin/controller/payment" but then try to call the install in "admin/controller/extension/payment", and the file doesn't exist here in a module to previous versions.
When I want to access to the index method I neither can.
OpenCart 2.3 isn't retrocompatible.

**Comment by OpenCartAddons** [comment]
It's a known issue in the latest release.  I created a PR a while back to address the issue.

https://github.com/opencart/opencart/pull/4712

Regards,
Joel.
