### ISSUE TITLE
googlebase.php $product_data array

### ISSUE THREAD

**Issue by billynoah** [opencart/opencart#4958]
The `$product_data` array in `catalog/controller/extension/feed/google_base.php` appears to be intended to prevent duplicate products.  However, it is never populated with anything.  I submitted a pull request to correct this issue here but it was rejected:

https://github.com/opencart/opencart/pull/4805

The array should either be removed or put to use.  As it stands, it serves no purpose.  It is initialized, compared against but never populated.

**Comment by jamesallsup** [comment]
Re-opened and merged.

Thanks.

**Comment by billynoah** [comment]
Thanks James
