### ISSUE TITLE
[Wiki] PHP Codesniffer link to rule set is outdated

### ISSUE THREAD

**Issue by gunjanpatel** [opencart/opencart#4961]
I found here that https://github.com/opencart/opencart/wiki/Coding-standards#php-codesniffer link https://github.com/opencart/opencart/blob/master/tests/phpcs.xml is outdated. 

Correct link should be https://github.com/opencart/opencart/tree/master/tests/phpcs/OpenCart

I would love to help improve wiki but I didn't know how can I do that. So, I have tried to create an issue for that. Hope this is a correct way to report.

Thanks.

**Comment by jamesallsup** [comment]
Thanks, that's been updated now.
