### ISSUE TITLE
Order Comments do not appear in Order Confirmation emails

### ISSUE THREAD

**Issue by danielmoore123** [opencart/opencart#4963]
Hi,
I am stuck.
When a customer leaves a note with their order at checkout, it writes to the database table "order" under row "comment" - Perfect.
The comment appears in the administration area of OpenCart - Perfect.
The comment refuses point blank to echo in the order confirmation email!!!
I have tried to install the VQMod fixes for this, none of them work.
I have tried to edit the code as per the OpenCart forums, again, no joy!
As a test, to make sure the template was calling the right table, I got it to echo the $ip instead in the email, this worked perfectly, it is just $comment that is hates.
Are either of the following possible, if so, how:
1) Creating a new row in the Order table and echo that instead, how would I then go about doing this?
2) Create a whole new text box to serve this purpose
3) Somehow fix this, I am willing to try anything!

Many Thanks in Advance.

(P.S: My Opencart version is 2.1.0.1)

**Comment by danielkerr** [comment]
this is for the admin to see, no need to present on invoice

**Comment by RichardThomas1** [comment]
The comments entered by the customer are on the printed invoice (i.e. for the customer) but not their E-Mail of the order. Comments are often used for the customer's order number for their own reference to identify the order and I always thought it was strange that it was not on the E-Mail to confirm the notes they made. In some cases it is delivery instructions which again would have expected to be in the confirmation so the customer has a record of what they wrote (purpose of the confirmation E-Mail).

@danielmoore123 The comments will appear on the customer's E-Mail if the status is first changed in admin (from "missing orders" to any status) - just not if the status is changed by the customer / payment method - perhaps this will help you work out the difference and how to implement it for all new orders. I think like you do that the comments entered by the customer should be in the customer's confirmation E-Mail and hope someone helps you figure it out and report back......

**Comment by danielmoore123** [comment]
The customer comments are in neither! For some reason, as admin, we get the exact same email as the customer! This isn't a problem, but I know as a customer, I would prefer the comments I entered to come back on a confirmation so I know it has gone through, especially on guest checkout! If I can echo the IP address then surely echoing the comment can't be too hard. I appreciate Opencart is not designed to show this by default, but that does not mean that I want it there less! Can anyone help to get it on there? In the tpl this works: 
`<?php echo $ip; ?>`
and this does not:
`<?php echo $comment; ?>`
Many Thanks for your help in advance.
