### ISSUE TITLE
Main admin frame also in Inside of Order Info Page

### ISSUE THREAD

**Issue by guddurahul** [opencart/opencart#4966]
I create a login for employee with the single permission of **Sales/Order** > **View**. And I though he can add order history comments. But found this bug attached screenshot. Have any idea/guide how to solve this issue...? 
![access-denied-problem](https://cloud.githubusercontent.com/assets/22999397/19620079/75f5467c-9892-11e6-8044-ea1ae28ab4ec.jpg)

**Comment by guddurahul** [comment]
Okey...guys found solution.
Under:   /admin/view/template/sale/order_info.tpl

I disabled following code

**Comment by guddurahul** [comment]
Okey guys i found solution..
Under: /admin/view/template/sale/order_info.tpl
Need to delete/disabled following line of code.

![ss151](https://cloud.githubusercontent.com/assets/22999397/19620427/d5439b9e-989a-11e6-960b-ad3f6f42dfa9.jpg)

**Comment by guddurahul** [comment]
Have any idea...please this is very urgent...

**Comment by danielkerr** [comment]
1st this is not Q&A!

ask in the fourms!

or do some research!
