### ISSUE TITLE
v2.3.0.2 Paypal Express Refund error

### ISSUE THREAD

**Issue by tyler-x** [opencart/opencart#4971]
CORRECTION: opencart version used is 2.3.0.2.

While using the paypal refund (tested on a full refund case), the system generates an error:

Notice: Undefined index: parent_id in /home/domain/public_html/domain.com/admin/model/extension/payment/pp_express.php on line 64Warning: Cannot modify header information - headers already sent by (output started at /home/domain/public_html/domain.com/admin/controller/startup/error.php:34) in /home/domain/public_html/domain.com/system/library/response.php on line 12

The refund transaction went through and was logged in the order payment history. I have to manually change the order status to Refunded.

the line 64 is a sql insert query, which has the `parent_id` = '" . $this->db->escape($transaction_data['parent_id']) in it, and it looks like the error was from here.

I checked the paypal_order_transaction database and there is a parent_id filed but it's empty for all the payment records, and this refund record.

No modification was made on the paypal extension, thought this might be a bug.

**Comment by looney81** [comment]
maybe it has something to do with this ->
https://github.com/opencart/opencart/pull/5022/commits/44e54ccdea05c7e3e6466d2752ee794080b334e2

check it out!!!

**Comment by craigbaines** [comment]
I'm having the same issue, also 

Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model account/recurring!' 

when i try to use the cancel recurring payment button's.

Paypal express ipn seems totally broken in 2.3.0.2.

artcore says here: https://forum.opencart.com/viewtopic.php?f=191&t=171424&p=650225#p650225

> file:catalog/controller/extension/payment/pp_express.php - ipn method
> 'recurring_payment_recurring_cancel'
> 
> should be:
> 'recurring_payment_profile_cancel'
> 
> The same for all other txn_types

That did seem to partially fix it but im not too sure what else needs fixing in regards to "all other txn-types" and what else beyond thats broken. 

If anyone who's a bit more clued up on this (my first time using recurring so i'm not too failure with default behaviour) could provide there fix, or if they already have already done so send me some updated files to get this all working as expected i would be very grateful! Thanks

**Comment by craigbaines** [comment]
Also, 

>kostasmoure commented 27 days ago • edited
maybe it has something to do with this ->
https://github.com/opencart/opencart/pull/5022/commits/44e54ccdea05c7e3e6466d2752ee794080b334e2
check it out!!! 

This link doesn't seem to work, im curious to see what you linked / if its of any help!? Thanks

**Comment by craigbaines** [comment]
Ahh, kostasmoure . That link owuldnt open for me when i clicked it.

Just copy/ pasted it an found the fix. 

One question specifically for the refund issue, when i refund via paypal express, my order status doesn't update automatically, is that the default behaviour or do i still have a problem there?

**Comment by webcorvo** [comment]
Hi i am using OC 2.3.2 and i must have API Username and API Sendbox Username ?!

**Comment by webcorvo** [comment]
I have OC version 2.3.2 and i am working in localhost.
When i try to pay with PayPal Express Checkout i have this erros.

Can some one help?

[log_error.txt](https://github.com/opencart/opencart/files/993736/log_error.txt)

**Comment by ADDCreative** [comment]
"Security header is not valid" is probably down to your settings. You should ask this sort to thing in the forums.

**Comment by webcorvo** [comment]
hi, i already solved that issue :o)
I can finish the order i am using sandox api to test in localhost.
mail like shop-buyer@gmail.com.
The problem is that the popup of paypal login dosen´t appear :o(

**Comment by webcorvo** [comment]
Ok the problem is solved,
Tks

**Comment by lifis** [comment]
@craigbaines did you ever get the order status to update when refunding a PP express order?
