### ISSUE TITLE
when front language and admin language are different - bug

### ISSUE THREAD

**Issue by lz1nud** [opencart/opencart#4972]
oc 2.3.0.2 - when I choose for language - Bulgarian (for example) and admin language stays English, in Extension -> Payments, Modules, Order Totals, Feeds you can see repeted modules like Divido Product Page Calculator - show 7 times, Klarna Checkout - twice and so on. If admin and front languages are the same, no problem.

Anyone else can confirm this?

**Comment by osworx** [comment]
Yes, but that indicates that some translations do not exist.
The missing is using the text from the former.
