### ISSUE TITLE
Pagination bug when SEO URLs are enabled

### ISSUE THREAD

**Issue by alexonciu** [opencart/opencart#4976]
Looks like OC 2.3.0.2 has a bug with pagination (at least on the category & brand page I can see it).

Steps to reproduce:
1.make sure you have more than 15 products (16 would do) on a category page
2.go to page 2 and look at the pagination links to go to page 1 or "<" "|<"

You can see this with a fresh install on my test site (clean, fresh OC 2.3.0.2):
http://www.kiotex.com/smartphone

So when you are on page 2 the link to page one (and the "<" & "|<" links) look like this:
http://www.kiotex.com/smartphone?page={page}
instad of the normal:
http://www.kiotex.com/smartphone

What's interesting further is that it know where to go properly on page 1:
`<link href="http://www.kiotex.com/smartphone" rel="prev" />
`

Going to page 1 with the weird link the prev / next looks like this: :)

```
<link href="http://www.kiotex.com/smartphone?page=-1" rel="prev" />
<link href="http://www.kiotex.com/smartphone?page=1" rel="next" />
```

(notice **page=-1** and **page=1**)

Digging deeper I can see that this only happens where SEO URLs are involved. It works just fine when these are disabled and it works just fine on the search page where there are no SEO URL.

At first you might think this is a small issue because page 1 is rendered just fine regardless of this bug however this is not the case because it hurts SEO pretty badly - both with duplicate content and with bad prev / next linking.

**Comment by ravilrrr** [comment]
@danielkerr  why closed ?

**Comment by danielkerr** [comment]
@ravilrrr because duplicate!

dont ask me questions again like this unless you want a ban!

**Comment by ravilrrr** [comment]
@danielkerr , I'm not asking for justification. This bug exists in versions 2.2x, 2.3x, and is still not fixed. For what ban me if the question is normal? Have I done something bad to you?
