### ISSUE TITLE
Invalid CSS in opencart/upload/admin/view/stylesheet/stylesheet.css: lines: 394-405

### ISSUE THREAD

**Issue by vamshikr** [opencart/opencart#4978]
opencart/upload/admin/view/stylesheet/stylesheet.css: lines: 394-405

input[type="radio"], .radio input[type="radio"], .radio-inline input[type="radio"], input[type="checkbox"], .checkbox input[type="checkbox"], .checkbox-inline input[type="checkbox"] {
    position: relative;
    width: 13px;
    width: 16px \0;
    height: 13px;
    height: 16px \0;
    -webkit-appearance: none;
    background: white;
    border: 1px solid #dcdcdc;
    border: 1px solid transparent \0;
    border-radius: 1px;
}

I am not sure if the trailing '\0' are intentional but CSSLint (http://csslint.net/) produces invalid XML because of those '\0' in the above piece of code. 

Here is the output from running xmllint --noout on the output of css for this file.
/home/stylesheet-redacted.xml:4: parser error : Char 0x0 out of allowed range
/home/stylesheet-redacted.xml:4: parser error : AttValue: ' expected
/home/stylesheet-redacted.xml:4: parser error : attributes construct error
/home/stylesheet-redacted.xml:4: parser error : Couldn't find end of Start Tag error line 4
/home/stylesheet-redacted.xml:4: parser error : Premature end of data in tag file line 2
/home/stylesheet-redacted.xml:4: parser error : Premature end of data in tag checkstyle line 1

**Comment by danielkerr** [comment]
i dont give a crap if the css is valid or not!

**Comment by danielkerr** [comment]
go and report some issue to Microsoft!
