### ISSUE TITLE
Klarna Checkout and payment method list

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#4981]
In file catalog/model/extension/payment/klarna_checkout.php:

```
      public function getMethod($address, $total) {
        // Not shown in the payment method list
        return array();
    }
```

Why is this so?

Ps. Why is not display button in file catalog/view/theme/default/template/extension/payment/klarna_checkout.tpl?

Ps2: Also checkout display again header and 2 footer

Our test this is not work, new klarna library is installed. Anyone suggestion?

**Comment by pekka2** [comment]
Klarna.com recommed this package:
https://github.com/klarna/kco_php

**Comment by danielkerr** [comment]
i dont give a rats ass what klarna recommends. they couldnt build a decent payment gateway to save gtheir lives!

im not including a 3rd party package that is a couple of MB!

**Comment by danielkerr** [comment]
also did i not close a post with the similar title

**Comment by pekka2** [comment]
@danielkerr 
This built-in Klarna Checkout is good remove, until it works.

**Comment by danielkerr** [comment]
@pekka2  i suggest you stop giving me orders and stop reposting closed issues!!
