### ISSUE TITLE
Search image bugs

### ISSUE THREAD

**Issue by ghxter** [opencart/opencart#4982]
can't search image bug, this is fixed code in admin/filemanager.php 40 ~ 54 line:
`if (substr(str_replace('\', '/', realpath($directory . '/')), 0, strlen(DIR_IMAGE . 'catalog')) == DIR_IMAGE . 'catalog') {
            // Get directories
            $directories = glob($directory . '/_' . $filter_name . '_', GLOB_ONLYDIR);

```
        if (!$directories) {
            $directories = array();
        }

        // Get files
        $files = glob($directory . '/*' . $filter_name . '*.{jpg,jpeg,png,gif,JPG,JPEG,PNG,GIF}', GLOB_BRACE);

        if (!$files) {
            $files = array();
        }
    }`
```

**Comment by Felix-Ho** [comment]
It's already fix from
https://github.com/opencart/opencart/commit/06b9a4d4a7fe7e2bbd50180f88713e1c11918b0e
you can update the file.
