### ISSUE TITLE
Store Credit Error

### ISSUE THREAD

**Issue by kamalkpaleti** [opencart/opencart#4983]
This issue is found in version 2.3.02

When using the store credit to purchase an item, the total balance is deducting and showing balance zero even though the product price is less than the store credit we have. 
Example : I have store credit $3000 and purchased a product for $500.

In real, $500 must be deducted from store credit and the balance should be $2500

But, it is deducting all the store credit and showing a balance Zero.

I have attached screen shots below. Please check.  Thanks for looking into this.

![error1](https://cloud.githubusercontent.com/assets/23154893/19839111/665316ba-9f02-11e6-9acf-c64530ffb2a7.JPG)

![error2](https://cloud.githubusercontent.com/assets/23154893/19839112/6a5c60a4-9f02-11e6-85b5-84534947fdca.JPG)

**Comment by fido-x** [comment]
Confirmed. Problem results from invalid comparison between a float value ($balance) and an array ($total) at line 9 in catalog/model/extension/total/credit.php.
`$credit = min($balance, $total);`
Should be changed to:
`$credit = min($balance, $total['total']);`

**Comment by Felix-Ho** [comment]
Thanks for let us know.
It's already been fixed on the master branch from previous issue.
https://github.com/opencart/opencart/issues/4776

and master branch file path
https://github.com/opencart/opencart/blob/master/upload/catalog/model/extension/total/credit.php
