### ISSUE TITLE
SMTP E-Mail - Contact Us - Server Error 500 if invalid E-Mail address

### ISSUE THREAD

**Issue by RichardThomas1** [opencart/opencart#4985]
With Mail settings SMTP, if the customer enters the E-Mail domain name incorrectly into the Contact Us form, such as myemail@yyyyyoop.com this presents the customer with a Server Error 500. 

Logs:
Uncaught Exception: Error: MAIL FROM not accepted from server! in /var/www/vhosts/*****/system/library/mail.php:323\nStack trace:\n#0 /var/www/vhosts/****/catalog/controller/information/contact.php(25): Mail->send()\n#1 /var/www/vhosts/****/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(51): ControllerInformationContact->index()\n#2 /var/www/vhosts/****/catalog/controller/startup/router.php(25): Action->execute(Object(Registry))\n#3 /var/www/vhosts/****/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(51): ControllerStartupRouter->index()\n#4 /var/www/vhosts/****/system/engine/front.php(34): Action->execute(Object(Registry))\n#5 /var/www/vhosts/****/system/engine/front.php(29): Front->execu...\n', referer: http://****/index.php?route=information/contact

OC V 2.3.0.2 and no VQMods related to E-Mail.

**Comment by Felix-Ho** [comment]
Please try the advice from 
https://github.com/opencart/opencart/issues/3756
