### ISSUE TITLE
Unparsable PHP file extension/sf_express.php

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#4986]
Look here:

https://github.com/opencart/opencart/blob/master/upload/catalog/model/extension/shipping/sf_express.php#L99

![image](https://cloud.githubusercontent.com/assets/2185289/19873808/c897d0a0-9fc9-11e6-8fc5-e9f8e4f9e0c8.png)

*And* - extr closing bracket at the end of file:
![image](https://cloud.githubusercontent.com/assets/2185289/19873859/12744be0-9fca-11e6-9aab-84ad3a85bffc.png)

**Comment by Felix-Ho** [comment]
From Daniel : seems sf express can not be bothered to provide a api key!so will be pulling it out.
https://github.com/opencart/opencart/issues/4644

Since SF Express did not provide an API KEY to us at the moment, so the project has been hold.

**Comment by arnisjuraga** [comment]
Will you fix the source too?
