### ISSUE TITLE
Demo site has been down

### ISSUE THREAD

**Issue by Uzenmi** [opencart/opencart#4987]
It seams that [demo site](https://www.opencart.com/index.php?route=demonstration/demonstration) has been down :)

**Comment by Felix-Ho** [comment]
It's working fine now.
Please check it.
https://www.opencart.com/index.php?route=demonstration/demonstration

**Comment by osworx** [comment]
It may working, but with that old version 2.0.0.1b it is everything else than good!
For example order edit:
![order_edit](https://cloud.githubusercontent.com/assets/1905204/19883447/afbab462-a014-11e6-9cae-9487c7a6dd50.png)
