### ISSUE TITLE
OpenCart Main Website Token Issue

### ISSUE THREAD

**Issue by uksitebuilder** [opencart/opencart#4995]
There are two issues on the main OpenCart.com website

After logging in, the 'My Account' link in the header does not work as expected and redirects to a login page (I'm assuming no token is passed in the link and/or session is not detected)

Export CSV from Sales List for extension sellers does not work - Again seems to be a token issue as it redirects to the login screen

**Comment by jamesallsup** [comment]
Thanks for letting us know Simon, I have identified the issue and working on a fix now.

**Comment by jamesallsup** [comment]
Issues should now be resolved for the links and also export.

Please advise if you still have any issues, thanks again!

**Comment by OpenCartAddons** [comment]
@jamesallsup Thanks
