### ISSUE TITLE
Bug Vouchers-Coupons inexplicably disappearing from orders

### ISSUE THREAD

**Issue by rkrkonline** [opencart/opencart#4998]
Hi,

On the back end (ie: admin side), if an order is payed with a voucher-coupon and you click view, the voucher-coupon shows fine, if instead of view you click on edit the voucher-coupon disappears without a trace.

Thanks,

**Comment by andrei-bogdan** [comment]
Hi, please send more information, what OpenCart version are you using?

**Comment by rkrkonline** [comment]
Hi Andrei-bogdan,
I first detected this on version 2.1.0.1 and I just replicated it on version 2.3.0.2
To replicate the problem:
- Log into the back end (ie: admin area)
- Add an order with any voucher and a coupon (You can do that from the front end too if you want to)
- View the order and you will be able to see the voucher and coupon fine as expected
- Edit the order and you will see that the voucher-coupon is not there which is the problem
- Click continue until you get to the last page and click save
- View the order again and the voucher-coupon is gone and the amount is changed
Hopefully this gives you enough to replicate the problem and take it from there?

**Comment by danielkerr** [comment]
try voiding the order before reediting the order

**Comment by danielkerr** [comment]
fixed in 3.,0 anyway,
