### ISSUE TITLE
Extensions breadcrums are missing text for text_extension

### ISSUE THREAD

**Issue by SelfMan** [opencart/opencart#5002]
The following files are missing the text_extension text entry: $_['text_extension']   = 'Extensions';

admin\language\en-gb\extension\captcha\google_captcha.php
admin\language\en-gb\extension\feed\openbaypro.php
admin\language\en-gb\extension\payment\pp_express_refund.php
admin\language\en-gb\extension\payment\pp_express_search.php
admin\language\en-gb\extension\payment\pp_express_view.php
admin\language\en-gb\extension\payment\pp_payflow.php
admin\language\en-gb\extension\payment\pp_pro.php
admin\language\en-gb\extension\payment\pp_pro_iframe.php
admin\language\en-gb\extension\shipping\auspost.php
admin\language\en-gb\extension\shipping\citylink.php
admin\language\en-gb\extension\shipping\fedex.php
admin\language\en-gb\extension\shipping\flat.php
admin\language\en-gb\extension\shipping\free.php
admin\language\en-gb\extension\shipping\item.php
admin\language\en-gb\extension\shipping\parcelforce_48.php
admin\language\en-gb\extension\shipping\pickup.php
admin\language\en-gb\extension\shipping\royal_mail.php
admin\language\en-gb\extension\shipping\ups.php
admin\language\en-gb\extension\shipping\usps.php
admin\language\en-gb\extension\shipping\weight.php
admin\language\en-gb\extension\theme\theme_default.php
admin\language\en-gb\extension\total\coupon.php
admin\language\en-gb\extension\total\credit.php
admin\language\en-gb\extension\total\custom_order_total.php
admin\language\en-gb\extension\total\handling.php
admin\language\en-gb\extension\total\klarna_fee.php
admin\language\en-gb\extension\total\low_order_fee.php
admin\language\en-gb\extension\total\reward.php
admin\language\en-gb\extension\total\shipping.php
admin\language\en-gb\extension\total\sub_total.php
admin\language\en-gb\extension\total\tax.php
admin\language\en-gb\extension\total\total.php
admin\language\en-gb\extension\total\voucher.php

Also all files within:
admin\language\en-gb\extension\extension
admin\language\en-gb\extension\openbay
are missing the text but I am not sure if they are used here.

The problem is visible when you adit the extension's properties and check the breadcrumbs.
i.e. "**Handling Fee** Home / text_extension / Handling Fee"

**Comment by SelfMan** [comment]
![breadcrumb-missing-text](https://cloud.githubusercontent.com/assets/2239036/20034604/c442b21a-a3c3-11e6-8e0a-f11ca5571ae6.png)
A screenshot for the visually oriented...

**Comment by dav-entry** [comment]
You can just add it globally to _admin/language/en-gb/en-gb.php_

**Comment by jamesallsup** [comment]
Tested on current dev branch and issue is resolved.
