### ISSUE TITLE
Main Website Update is a disaster

### ISSUE THREAD

**Issue by uksitebuilder** [opencart/opencart#5004]
Many problems with the latest update to OpenCart.com

Forums missing images

Extension Store errors, typos and seems unfinished

Clicking an extension gives you:

Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model marketplace/category!'

Why on earth was this not tested locally before uploading?  What a disaster

Suggest you rollback and sort this shit out properly before making it live to the public.

See this forum post on reported bugs:

https://forum.opencart.com/viewtopic.php?f=10&t=170219

**Comment by ffctcc** [comment]
Did the forum post got nuked? Can't see it anymore :D

**Comment by uksitebuilder** [comment]
It seems the post id changed for some reason.

I have updated the link above

**Comment by pekka2** [comment]
Confuso:
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=19083

There missing this:
`$description_data = str_replace("\r\n","<br>",$description_data);`

**Comment by pekka2** [comment]
There in new Opencart missing export purhase csv file. Why?
And extension sale is only '0'.
And how anyone can purchase extension? There missing 'Download' button

**Comment by nikto1** [comment]
For sellers there's no #orderId, nor any information who purchased the extension

**Comment by danielkerr** [comment]
most of the issues are fixed. the remaining ones will be fixed as we add new features to the master branch
