### ISSUE TITLE
What You have done with www.opencart.com?

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#5008]
## Is this correct place, where to post? Or you have other issue tracker for web page?

- comments are not visible in Extensions section
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=23098
![image](https://cloud.githubusercontent.com/assets/2185289/20080357/0063dc8a-a552-11e6-81d8-fd9eaf44a1e4.png)

- Problem with images:
![image](https://cloud.githubusercontent.com/assets/2185289/20080367/0b8ba520-a552-11e6-8d9b-292423effcfd.png)

https://www.opencart.com/index.php?route=marketplace/extension&filter_member=chrisrollins65
![image](https://cloud.githubusercontent.com/assets/2185289/20080388/1fd13356-a552-11e6-9487-be4dfb5295a9.png)

- Support request form for Extensions is filled with Opencart contact phone:
![image](https://cloud.githubusercontent.com/assets/2185289/20080422/4fad2d0a-a552-11e6-91d5-25e929bac2cc.png)

- after posting support request form, I receive 404:
![image](https://cloud.githubusercontent.com/assets/2185289/20080468/8339cb42-a552-11e6-9fc0-8c1a44e985f6.png)

- Date, near extension download, seems to be not correct:
![image](https://cloud.githubusercontent.com/assets/2185289/20081547/ed118d56-a558-11e6-8cd0-a4ca9f96658b.png)

**Comment by danielkerr** [comment]
im not blind!
