### ISSUE TITLE
Vietnam currency (not dollars)

### ISSUE THREAD

**Issue by tuananh88c25** [opencart/opencart#5015]
When Vietnam currency as main currency, sync feature is not implemented correctly
currency ratio USD/VND is 1:1
exact USD/VND is 1:22300

**Comment by osworx** [comment]
Was never a issue/bug!
Guess you forgot to adjust the standard currency value (= 1).

**Comment by tuananh88c25** [comment]
have 1 standard and 2 value (= 1).

![2016-11-11_210653](https://cloud.githubusercontent.com/assets/20010645/20217551/e0c43a2e-a852-11e6-9fd3-bd949dc49c37.png)

**Comment by osworx** [comment]
From the dates I can see that you have made no update till yet.
You should and you will see the result.

**Comment by tuananh88c25** [comment]
I clicked the refresh button. and the result is that.
no changes.
When USD currency as main currency. result is ok.

**Comment by tuananh88c25** [comment]
Wait danielkerr. the pic is bug
