### ISSUE TITLE
Rant: not using a `foreach` loop in language controller

### ISSUE THREAD

**Issue by DRSDavidSoft** [opencart/opencart#5019]
I'm really curious, please one of the devs answer to this issue.

The controller files use the following logic to include language content:
```
$data['text_designer'] = $this->language->get('text_designer');
$data['text_order'] = $this->language->get('text_order');
$data['text_order_status'] = $this->language->get('text_order_status');
$data['text_complete_status'] = $this->language->get('text_complete_status');
$data['text_return'] = $this->language->get('text_return');
$data['text_customer'] = $this->language->get('text_customer');
$data['text_online'] = $this->language->get('text_online');
$data['text_approval'] = $this->language->get('text_approval');
$data['text_product'] = $this->language->get('text_product');
$data['text_stock'] = $this->language->get('text_stock');
$data['text_review'] = $this->language->get('text_review');
$data['text_affiliate'] = $this->language->get('text_affiliate');
$data['text_store'] = $this->language->get('text_store');
$data['text_front'] = $this->language->get('text_front');
$data['text_help'] = $this->language->get('text_help');
$data['text_homepage'] = $this->language->get('text_homepage');
$data['text_documentation'] = $this->language->get('text_documentation');
$data['text_support'] = $this->language->get('text_support');
```

However, this method has a really bad side problem: If we want to add a new language field, we have to duplicate (i.e. copy and paste) a line, and change the variable **two** times.

Why OpenCart doesn't use the following format:
```
$lang_list = array( 
	'text_designer',
	'text_order',
	'text_order_status',
	'text_complete_status',
	'text_return',
	'text_customer',
	'text_online',
	'text_approval',
	'text_product',
	'text_stock',
	'text_review',
	'text_affiliate',
	'text_store',
	'text_front',
	'text_help',
	'text_homepage',
	'text_documentation',
	'text_support'
);

foreach ( $lang_list as $node )
	$data[$node] = $this->language->get($node);
```

Which is easier to maintain and understand, easier to add, remove or modify, and overall neater to do so.

Please, any of the original devs who wrote the controller code, answer to this issue. I really want to know!

**Comment by DRSDavidSoft** [comment]
Please someone explain this to me! 😰 

<?php if ($layout_module['position'] == 'content_top') { ?>
<option value="content_top" selected="selected"><?php echo $text_content_top; ?></option>
<?php } else { ?>
<option value="content_top"><?php echo $text_content_top; ?></option>
<?php } ?>
<?php if ($layout_module['position'] == 'content_bottom') { ?>
<option value="content_bottom" selected="selected"><?php echo $text_content_bottom; ?></option>
<?php } else { ?>
<option value="content_bottom"><?php echo $text_content_bottom; ?></option>
<?php } ?>
<?php if ($layout_module['position'] == 'column_left') { ?>
<option value="column_left" selected="selected"><?php echo $text_column_left; ?></option>
<?php } else { ?>
<option value="column_left"><?php echo $text_column_left; ?></option>
<?php } ?>
<?php if ($layout_module['position'] == 'column_right') { ?>
<option value="column_right" selected="selected"><?php echo $text_column_right; ?></option>
<?php } else { ?>
<option value="column_right"><?php echo $text_column_right; ?></option>
<?php } ?>

**Comment by kagan94** [comment]
Because it's invented wheel :)

**Comment by pekka2** [comment]
How eg. this:
`$data = array_merge($data,$this->language('ctalog/product));`

**Comment by osworx** [comment]
Easier: `$data += $this->language->get( 'TYPE/NAME' );`
But many times bespoken the last 5 years, never changed - so finally useless to post here everything about.

**Comment by danielkerr** [comment]
ill change it when i have a better solution.

what about $this->load->language('account/account', &$data);

**Comment by danielkerr** [comment]
ok we can use that method

**Comment by danielkerr** [comment]
im still fixing issues on the main site
as soon as im finished will start working on changing thew dev stuff

**Comment by DRSDavidSoft** [comment]
I really agree to the last one!
But truth be told, I though Open Cart wrote like this for a reason, e.g. loading only a portion of language data, which is then simply false.
Why should we define language names in three files and many sections, when it can be simply defined in one, and fetched from the other one?! :D

**Comment by osworx** [comment]
When changing that method, I propose also to change the language files (a bit).
Move all redundant variables into one file, this will reduce the workload for translating massive.

**Comment by DRSDavidSoft** [comment]
I second that! No redundant language files!

**Comment by danielkerr** [comment]
It's because we were using php in the top files if there's a missing car it throws an error

**Comment by danielkerr** [comment]
I mean var

**Comment by CoverUp** [comment]
we can load a global language definition $this->load->language('common/global') and then a specific language file for that controller $this->load->language('section/module'), thus in global we can have common definitions, like yes, no, continue, etc. and in the specific file all related to the module being loaded, also this way we can overwrite the global definion if is required, but if isn't defined there will use the global definition

**Comment by danielkerr** [comment]
Sure.

**Comment by osworx** [comment]
@CoverUp I suggested such already 2 years ago, but was not ecxepted ..
But loading a 'global' language definition is already done by the 'master' language file (e.g. en-gb, de-DE, etc.).
So you mean an additonal?

**Comment by arnisjuraga** [comment]
It would be great, if you could change this! 
Main drawback, of course - there areOCMOD and VQMOD modules, which uses .php code in controllers for "search/replace" strings. 

But better now then ever - @opencart must improve this.

I would vote for outputing strings with some kind of function. Like Wordpress and others does it. 
It allows then to improve it, change, log, hook or whatever, if you use any simple functions - one with echo another with return (Wordpress style: `__('Home')` `_('Home')`)

Functions can take more arguments (scope, e.g.). And even more - you can really use more human readable keys for that and always be sure - you are outputing translated string in a view, not a variable.

**Comment by danielkerr** [comment]
ikf you check the dev branch the template system has switch to twig. as soon as the dev is released we can change the language files.

**Comment by arnisjuraga** [comment]
Great!

**Comment by hauso** [comment]
my 2 cents:
in language files:
$_['text']['browse'] = 'Browse';
$_['text']['clear'] = 'Clear';
$_['text']['yes'] = 'Yes';
$_['text']['no'] = 'No';

in contoller:
$this->load->language('module/file');
$this->texts = $this->language->get('text');

in template:
{{ text.browse }}

**Comment by OpenCartAddons** [comment]
I use a similar method when loading text in my extensions.  

`$data['language']					= $this->load->language('extension/shipping/file');`

Unfortunately changing the core system would be a lot of work to do.

One huge benefit I can think of is compatibility with the new language editor.  You can add additional text with custom keys, but there's no way to load this text without writing an OCMod to modify the controller to push the text to the template files.  Auto loading the master text file and page specific text would avoid this issue.

**Comment by danielkerr** [comment]
ok i have a solution using autoloading!

so after many years of nagging and complaints language auto insert into the template its happening!

**Comment by danielkerr** [comment]
maybe this way?

$this->response->setOutput($this->load->view('design/seo_url_form', $this->load->language('module/file', $data)));

**Comment by RaidoDev** [comment]
What if you need multiple language files?
What if y want to override some translation?
What if you need `sprintf` aggregation?

**Comment by danielkerr** [comment]
it will still work

**Comment by OpenCartAddons** [comment]
I think @RaidoDev is right about overriding text and using sprintf as these would have to be passed through the controller individually

`$data['text_example'] = sprintf($this->language->get('text_example'), 'sometext');`

but would be overwritten if the entire language file is passed afterwards during the response.

**Comment by danielkerr** [comment]
ok going to remove language vars and test at the same time. seems to be working on the few pages i have tried.

**Comment by danielkerr** [comment]
ok closing this, it should be working now

**Comment by marekkijo** [comment]
I'm afraid this change cause a lot of issues and should be reverted or at least it requires in deep review.
Example problems noticed:
- wrong heading in Cart view "Use Gift Certificate" instead "Shopping Cart"
- wrong headings in every subpage in Account eg. "Account" instead "My Wish List" at Wish List subpage
- wrong links labels at My Acount page eg. "Address Book" instead of "Modify your address book entries" or "Wish List (%s)" instead of "Modify your wish list"

**Comment by woutd** [comment]
- Also breaks product page: wrong `text_manufacturer` is used and you get: "Brands XXX" instead of "Brand: XXX"
- I think this is also related with issue report #5699, in master all `text_empty` have been replaced with `text_no_result`, but it should have remained `text_empty` as long as the right `text_empty` value is used.
