### ISSUE TITLE
Filemanager - Cannot upload a file in a folder with special characters

### ISSUE THREAD

**Issue by trueliarx** [opencart/opencart#5023]
2.3.0.2 (and before)
I cannot upload a file in a folder with special characters. And the same folder cannot be deleted.
The problem appears with folders like "johnson & johnson".

admin/controller/common/filemanager.php

**Comment by osworx** [comment]
Sometimes it is interesting how people try to name folders, files and images!
What a stupid world today.

Simply DO NOT USE space, umlauts, special chars.

**Comment by trueliarx** [comment]
Sometimes it is interesting how people are commenting without thinking about REALITY and how the REAL world works.
1) My customers (admin users) are not aware of the technical parts and best practices. They just add what they feel is correct (real life ...).
2) If some characters are NOT allowed or cannot be managed correctly the error message must be different.
3) It's an error, even in logic, since There's an error dialog related to folders and the folder that the user adds cannot be deleted via backend.
4) The administrators/programmers/whatever are going to waste time to find out what is the problem.
5) If you feel that some characters are not allowed they MUST be sanitized and reported in the correct way and the scripts must not proceed into adding folders that cannot be deleted by the users.
6) I don't need to "not use space, etc". I fixed the problem by myself disallowing non-alphanum.
7) I'm not here to attend a possible "flame" but to report what is clearly an ISSUE.

Thank you for your reply.
Cheers.

**Comment by johnwongoc** [comment]
It is a good practice to name the folder name without using any special characters.

**Comment by osworx** [comment]
@trueliarx I have to endorse, too many customers are in these days very stupid.
And nobody can require basic knowledge what can be done and what not.
We are living in a 'App' and 'Windows' world where some is possible, but not on Linux servers.
And yes, this is an issue since the beginning of OpenCart - and no one seems to be willing to add a fix which will automatically sanitize incorrect entries.
