### ISSUE TITLE
Clean file catalog/controller/product/category.php and Opencart works.

### ISSUE THREAD

**Issue by GoldenScrew** [opencart/opencart#5024]
I am new in OpenCart, but I have the question:
When I delete file:
> catalog/controller/product/category.php

I have an error, when I try use list of product in category.
But when I **clean file or comment** all strings, I haven't error.

Why need this file?
I want to change controller for category, but I can't find where I should change.
Waiting for a reply, thanks.

**Comment by tylerbenzing** [comment]
This isn't the place to ask this
