### ISSUE TITLE
Upstream Problem with Nginx+Fastcgi

### ISSUE THREAD

**Issue by Insax** [opencart/opencart#5029]
Hey guys, I'm trying to set up Opencart on my Mac and I get some weird 502 Errors and I have no clue how to fix that.

At first I also want to say that I run many Web Applications with nearly the same config and they all work, so it must be something specific for opencart.

If I try to visit the page the first time I get a 502 Bad Gateway, nginx log gives me this:

`2016/11/17 01:56:10 [error] 1474#0: *30 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: zerry.codefactory.dev, request: "GET /install/index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "zerry.codefactory.dev", referrer: "http://zerry.codefactory.dev/install/index.php"`

PHP-FPM isnt even writing logs (or I'm too stupid to find them...) and Permissions are all set so I have no clue what causes this error, here some information for you:

Here is my Site Configuration:

https://gist.github.com/Insax/b8fc2a6f86d588a092059e8a80a3daa9

PHP-FPM Config:

https://gist.github.com/Insax/1c903d2e87ba3246611e59e987459fc3

And my FastCGI Params:

https://gist.github.com/Insax/ad997dc62e9cf3418b9f7e7676d0b10f

Any clues what maybe could cause these errors?

**Comment by jamesallsup** [comment]
Please post this on the forum as it isn't a bug on the core - its a setup issue. https://forum.opencart.com

If it helps I'd change from using php-fpm on tcp to a socket - if your on a local dev it is better (tcp is better for multi fpm servers / scaling). Second, check php-fpm is running and finally (most important) check that your php-fpm config is valid and you have set your pool config correctly. Those config files are not in json-style like nginx is so the one you posted seems incorrect.

Hope that helped.

J
