### ISSUE TITLE
/payment/pilibaba.php oc -v 2.3.02 malware issue

### ISSUE THREAD

**Issue by Charlie1404** [opencart/opencart#5030]
My hosting is telling that '/home/app2wo7i/public_html/voidkart.com/catalog/controller/extension/payment/pilibaba.php' this file contains malicious content and may be infected with malware. Please check it out and remove this payment extension if required.

**Comment by trueliarx** [comment]
I cannot see any particular *malicious* code.
Virustotal doesn't report any possible virus and other people tested the file before us (there's a previous analysis of about a month ago)
https://www.virustotal.com/it/file/02f8e67766bb7b9fa402a45497b5bb2523899e7e9afbef9e61b000f2d818e18b/analysis/

If you can please show what is the problematic/malicious content.

**Comment by Charlie1404** [comment]
Actually i also tried virustotal and even in my case it showed me that no virus is found but on hostgator's hosting my ports were blocked just because there scanners found this pilibaba's controller file contains malicious code. I don't what is malicious in it. When i removed the extensio,hosting provider opened my ports.

**Comment by trueliarx** [comment]
It could be a false positive. More informations are needed.
Meanwhile, if unused, it can be safely deleted.

**Comment by jamesallsup** [comment]
There is no malware in the extension so must be a false positive coming from your hosting provider - they will probably use an external service that looks for signatures and maybe matches something else. The service may also be used by other hosts too.

Without the actual information from your provider as to the exact lines of code that cause the error - there is nothing anyone can do, if you can get the information from them then please post here and I can re-open the ticket if it is valid.
