### ISSUE TITLE
Coupon History did't record Customer

### ISSUE THREAD

**Issue by rcc03461** [opencart/opencart#5032]
I change the order status to processing. Coupon History is recorded but only the field of Customer is empty . I view it on database and show 0 ( customer_id ) . Which file can I check?

**Comment by Felix-Ho** [comment]
We have to check deeper on the situation so that we can find out the reason.
Would you mind go to
https://www.opencart.com/index.php?route=support/support
and send us a support request including your store admin and temp FTP for us to check it?
