### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by kelunik** [opencart/opencart#5042]
Please publish information on how to contact you for security issues _outside_ of your forum, e.g. an email address.

**Comment by jamesallsup** [comment]
You can contact our support at opencart@zendesk.com who will forward on any information. This is the only email we will publish on public sites, otherwise they just end up on spam lists.

There is also our contact form here: https://www.opencart.com/index.php?route=support/contact

J

**Comment by kelunik** [comment]
I sent a mail 6 days ago, no response yet.

**Comment by kelunik** [comment]
Sure, it starts with `[Security]` and contains `Token`. I don't have any ticket ID.

**Comment by jamesallsup** [comment]
@kelunik very sorry but cannot find any support issue with your name and subject keywords.  

Can you forward the email again to support@opencart.com - this has been configured instead of the zendesk one, ive just tested and works too.

Thanks.

**Comment by kelunik** [comment]
@jamesallsup Done.

**Comment by kelunik** [comment]
@jamesallsup 8 days later now and still no response. Ticket 93065.

**Comment by samtarling** [comment]
@kelunik are you really expecting this to be taken seriously, given the history this project has?

**Comment by arnisjuraga** [comment]
Sure, it takes time to dig into and evaluate it. Keep in mind, your ticket is available for small amount of team. 

But me also is looking forward to see the response.

**Comment by kelunik** [comment]
@samtarling Can't say that. I'm surprised by the rather quick responses here.

@arnisjuraga If you take security seriously, you usually have a look at new issues in under a week and send an initial response. My ticket in this case is available to the whole support team, as no other e-mail has been provided that's security specific.

**Comment by danielkerr** [comment]
James hasrn't replied because its a none issue i think

**Comment by arnisjuraga** [comment]
@kelunik please, can You share the issue to me? Look for my email in profile.

**Comment by kelunik** [comment]
@arnisjuraga I won't share it privately, either publicly or not at all.

> Please do not report concept/ideas/unproven security flaws - all security reports are taken seriously

@danielkerr Should I provide a PR instead fixing that statement in the README? Because it's obviously not the case.

1. If it's spam, feel free to ignore it, but this isn't.
2. If you think it's a non-issue, respond and state the reasons why you think it's a non-issue. If someone takes the effort to find a security contact and write an e-mail, it's probably worth responding.

**Comment by danielkerr** [comment]
@kelunik I dont need your advice on what I need to do!

**Comment by danielkerr** [comment]
spoke with james he said its a non issue and you were wasting peoples time.

**Comment by danielkerr** [comment]
post it if you like

**Comment by danielkerr** [comment]
as long as its not going to stop me from working because you can't other people say!

**Comment by kelunik** [comment]
@danielkerr Would you accept a PR fixing the issue?

**Comment by danielkerr** [comment]
no

**Comment by danielkerr** [comment]
there is no issue, its in your mind!

**Comment by ryan-copperleaf** [comment]
@kelunik Is this still a potential issue? Was it ever posted publicly?

**Comment by kelunik** [comment]
@ryan-copperleaf Yes, it is. No, I think it hasn't been publicly posted.
