### ISSUE TITLE
About OC Store

### ISSUE THREAD

**Issue by seglavi** [opencart/opencart#5044]
Hi,

I know you will say it is not the right place to ask this but i also tried to get support from OC Support. I looked at the new "comments" on new system and also to the forum.

**I can not download extensions which i bought.**

You may say talk to developer. I have nearly 30 extensions which i bought. Will i talk with all of them? Because if there is an update on extension i can not download it. And i need some extensions to buy but i am afraiding to buy. So, will be a solution to this?

Regards.

**Comment by jamesallsup** [comment]
hi @seglavi - I have been looking into various issues like this for days, with customers being unable to download certain extensions and updates. But all have been working for me.

What is your support case id #? I can get your info from there and look at your issue. (please dont put your email on here, just your case ID)

J

**Comment by seglavi** [comment]
Hi @jamesallsup ,

Yesterday when i wrote this issue i can not download my extensions. And now i try them to download. And also i get reply from your Support Agent an email.

Thanks. This issue seems solved.

Regards.
