### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by JustMaffie** [opencart/opencart#5047]
Fatal error: Class 'SessionHandler' not found in /home/******/www/system/library/session/native.php on line 3

**Comment by JustMaffie** [comment]
That is what I get when trying to install it in the /install/ directory.

**Comment by danielkerr** [comment]
reupload you are missing files.

**Comment by danielkerr** [comment]
http://php.net/manual/en/class.sessionhandler.php

**Comment by danielkerr** [comment]
make sure you r php is above 5.4
