### ISSUE TITLE
Suggestion to change Float to Double on oc_currency

### ISSUE THREAD

**Issue by hendrachristian** [opencart/opencart#5048]
Since I live in Indonesia and the currency here is (at the time of writing):
USD 1 = IDR 13.600 or IDR 1 = USD 0.00007352941
and the db definition for "value" in "oc_currency" is float(15,8), this cause the input to be rounded up to 0.00007353. This cause the conversion to be slightly off. (Indonesian Rupiah being the Default value)

I have 2 suggestions:

1. I suggest to change this to "double" to cater for extra decimal places.
2. Since pulling up data from Yahoo Finance (http://download.finance.yahoo.com/d/quotes.csv?s=IDRUSD=X&f=sl1&e=.csv) directly cause an even worse rounding (it became 0.0001). I suggest for the code to decide if the value retrieved from Yahoo Finance is below 0, it would be better to get a value from the other way around, ie. $tempvalue = http://download.finance.yahoo.com/d/quotes.csv?s=USDIDR=X&f=sl1&e=.csv and then $value = 1/$tempvalue. That way the decimal number would be retained and a correct currency exchange value would be saved to db.

PS: I've done a vqmod for this, let me know if this change is approved, then I can submit a pull request.

**Comment by johnwongoc** [comment]
Thank you for your opinion. If you make a Vqmod, please upload it to our marketplace.

**Comment by danielkerr** [comment]
i see the issue.

**Comment by danielkerr** [comment]
its quite hard to fix without switching from yahoo to a paid service.

**Comment by hendrachristian** [comment]
Since this has been a while, I know I've fixed this in my vqmod last time. I'll copy my vqmod here, hope it can go through to the official release.
``<?xml version="1.0" encoding="UTF-8"?>
<modification>
    <id>Currency</id>
    <version>1.0</version>
    <opencart>2.3.0.2</opencart>
    <journal>2.8.0</journal>
    <vqmver>2.6.1</vqmver>
    <author>Hendra Christian</author>
    <date>25 Nov 2016</date>

    
    <file name="admin/model/localisation/currency.php">
        <operation>
            <search position="after"><![CDATA[
                $data = array();
            ]]></search>
            <add><![CDATA[
                $data_swap = array();
            ]]></add>
        </operation>
        <operation>
            <search position="after"><![CDATA[
                $data[] = $this->config->get('config_currency') . $result['code'] . '=X';
            ]]></search>
            <add><![CDATA[
                $data_swap[] = $result['code'] . $this->config->get('config_currency') . '=X';
            ]]></add>
        </operation>
        <operation>
            <search position="before"><![CDATA[
                $curl = curl_init();
            ]]></search>
            <add><![CDATA[
                $curl_swap = curl_init();

                curl_setopt($curl_swap, CURLOPT_URL, 'http://download.finance.yahoo.com/d/quotes.csv?s=' . implode(',', $data_swap) . '&f=sl1&e=.csv');
                curl_setopt($curl_swap, CURLOPT_RETURNTRANSFER, 1);
                curl_setopt($curl_swap, CURLOPT_HEADER, false);
                curl_setopt($curl_swap, CURLOPT_CONNECTTIMEOUT, 30);
                curl_setopt($curl_swap, CURLOPT_TIMEOUT, 30);

                $content_swap = curl_exec($curl_swap);

                curl_close($curl_swap);

                $lines_swap = explode("\n", trim($content_swap));

                $swap = array();

                foreach ($lines_swap as $line_swap) {
                    $currency_swap = utf8_substr($line_swap, 1, 3);
                    $value_swap = utf8_substr($line_swap, 11);

			        $swap[$this->db->escape($currency_swap)] = (float)$value_swap;
                }
            ]]></add>
        </operation>
        <operation>
            <search position="replace"><![CDATA[
                $value = utf8_substr($line, 11, 6);
            ]]></search>
            <add><![CDATA[
                $value = utf8_substr($line, 11);

                if ((float)$value < 1 && $swap[$currency] != 0) { //need to get currency exchange the other way
                    $value = 1/$swap[$currency];
                }
            ]]></add>
        </operation>
    </file>

    
    <file name="catalog/controller/product/product.php">
        <operation>
            <search position="before" index="1"><![CDATA[
                if ($this->customer->isLogged() || !$this->config->get('config_customer_price')) {
            ]]></search>
            <add><![CDATA[
                $data['meta_description'] = $this->db->escape($this->document->getDescription());

                $decimal_place = $this->currency->getDecimalPlace($this->session->data['currency']);
                $decimal_point = $this->language->get('decimal_point');
                $thousand_point = $this->language->get('thousand_point');
                $currency_symbol_left = $this->currency->getSymbolLeft($this->session->data['currency']);
                $currency_symbol_right = $this->currency->getSymbolRight($this->session->data['currency']);
            ]]></add>
        </operation>
        <operation>
            <search position="replace"><![CDATA[
                $data['price'] = $this->currency->format($this->tax->calculate($product_info['price'], $product_info['tax_class_id'], $this->config->get('config_tax')), $this->session->data['currency']);
            ]]></search>
            <add><![CDATA[
                $price_taxed = $this->tax->calculate($product_info['price'], $product_info['tax_class_id'], $this->config->get('config_tax'));

                $data['price'] = $this->currency->format($price_taxed, $this->session->data['currency']);

                $data['price_number'] = $this->currency->format($price_taxed, $this->session->data['currency'], "", false);

                $data['price_value'] = number_format(round($this->currency->format($price_taxed, $this->session->data['currency'], "", false), $decimal_place), $decimal_place, $decimal_point, $thousand_point);

                $data['currency_symbol_left'] = $currency_symbol_left;
                $data['currency_symbol_right'] = $currency_symbol_right;
            ]]></add>
        </operation>
        <operation>
            <search position="replace"><![CDATA[
                $data['special'] = $this->currency->format($this->tax->calculate($product_info['special'], $product_info['tax_class_id'], $this->config->get('config_tax')), $this->session->data['currency']);
            ]]></search>
            <add><![CDATA[
                $special_taxed = $this->tax->calculate($product_info['special'], $product_info['tax_class_id'], $this->config->get('config_tax'));

                $data['special'] = $this->currency->format($special_taxed, $this->session->data['currency']);

                $data['special_number'] = $this->currency->format($special_taxed, $this->session->data['currency'], "", false);

                $data['special_value'] = number_format(round($this->currency->format($special_taxed, $this->session->data['currency'], "", false), $decimal_place), $decimal_place, $decimal_point, $thousand_point);

                $data['currency_symbol_left'] = $currency_symbol_left;
                $data['currency_symbol_right'] = $currency_symbol_right;
            ]]></add>
        </operation>
    </file>

    <file name="catalog/view/theme/journal2/template/product/product.tpl">
        
        <operation>
            <search position="replace"><![CDATA[
                <li class="product-price"><?php echo $price; ?></li>
            ]]></search>
            <add><![CDATA[
                <li class="product-price"><?php echo $currency_symbol_left; ?><span><?php echo $price_value; ?></span><?php echo $currency_symbol_right; ?><span itemprop="price" style="display:none"><?php echo $price_number; ?></span></li>
            ]]></add>
        </operation>
        <operation>
            <search position="replace"><![CDATA[
                <li class="price-new"><?php echo $special; ?></li>
            ]]></search>
            <add><![CDATA[
                <li class="price-new"><?php echo $currency_symbol_left; ?><span><?php echo $special_value; ?></span><?php echo $currency_symbol_right; ?><span itemprop="price" style="display:none"><?php echo $special_number; ?></span></li>
            ]]></add>
        </operation>
    </file>
</modification>

**Comment by hendrachristian** [comment]
This way you'll get accurate exchange rates either way still using free Yahoo feed.

**Comment by danielkerr** [comment]
It's ok I sorted it

**Comment by danielkerr** [comment]
I'll commit ltr

**Comment by hendrachristian** [comment]
Nice. You did it more elegant than I did 👍 
Finally another vqmod to retire, one less to maintain with each releases :)
I still got a bunch of mini tweaks and fixes, maybe I should do a pull request or open a new issue :D
