### ISSUE TITLE
 Warning: CURL extension needs to be loaded for OpenCart to work! 

### ISSUE THREAD

**Issue by sopheakreth** [opencart/opencart#5049]
![aaa](https://cloud.githubusercontent.com/assets/19568260/20641682/dfbdc0da-b42f-11e6-861c-a692fc15c300.PNG)

**Comment by jamesallsup** [comment]
This is not a bug! It means your php is not installed with curl support

**Comment by sopheakreth** [comment]
I got it, it has been worked. Thanks
