### ISSUE TITLE
unit tests do not apear to be working for me.  I followed the steps on the the tests readme and im proper stuck, is there something wrong or is it just the way im invoking the tests. 

### ISSUE THREAD

**Issue by nslocomotives** [opencart/opencart#5050]
i have a database in place, and the config files where they should be in upload and in upload/admin, ive also copied and populated the bootstrap.php into the tests/phpunit folder using the template bootstrap-dist.php as i saw this was required. 

I then tried running this on the command line rather than using jenkins command interface.. but i get the same errors. 

iMac:phpunit jenkins$ pwd 
/Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit
iMac:phpunit jenkins$ vendor/bin/phpunit --bootstrap /Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/bootstrap.php opencart/admin
PHP Notice:  Undefined index: SERVER_PORT in /Users/Shared/Jenkins/Home/jobs/opencart/workspace/upload/system/startup.php on line 40

Notice: Undefined index: SERVER_PORT in /Users/Shared/Jenkins/Home/jobs/opencart/workspace/upload/system/startup.php on line 40
PHP Warning:  require_once(/Users/Shared/Jenkins/Home/jobs/opencart/workspace/upload/system/library/customer.php): failed to open stream: No such file or directory in /Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/openbaypro/opencart-test-suite/src/OpenCartTest.php on line 54

Warning: require_once(/Users/Shared/Jenkins/Home/jobs/opencart/workspace/upload/system/library/customer.php): failed to open stream: No such file or directory in /Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/openbaypro/opencart-test-suite/src/OpenCartTest.php on line 54
PHP Fatal error:  require_once(): Failed opening required '/Users/Shared/Jenkins/Home/jobs/opencart/workspace/upload/system/library/customer.php' (include_path='/Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/phpunit/php-file-iterator:/Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/phpunit/phpunit-mock-objects:/Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/phpunit/phpunit:/Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/symfony/yaml:/Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/phpunit/phpunit-selenium:/usr/local/Cellar/php54/5.4.45_6/lib/php/pear') in /Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/openbaypro/opencart-test-suite/src/OpenCartTest.php on line 54

Fatal error: require_once(): Failed opening required '/Users/Shared/Jenkins/Home/jobs/opencart/workspace/upload/system/library/customer.php' (include_path='/Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/phpunit/php-file-iterator:/Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/phpunit/phpunit-mock-objects:/Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/phpunit/phpunit:/Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/symfony/yaml:/Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/phpunit/phpunit-selenium:/usr/local/Cellar/php54/5.4.45_6/lib/php/pear') in /Users/Shared/Jenkins/Home/jobs/opencart/workspace/tests/phpunit/vendor/openbaypro/opencart-test-suite/src/OpenCartTest.php on line 54

**Comment by jamesallsup** [comment]
The tests are not currently working for v2  - it is on my list of jobs but there are a lot of other more important tasks we are working on.

**Comment by nslocomotives** [comment]
sure understand completely I've been playing with them but i don't understand them enough yet to be of any help to you.  If I get some time i may see if i can do something to help contribute, just glad it wasn't just me 👍

**Comment by stefanhuber** [comment]
I have updated this opencart-testing-suite: https://github.com/beyondit/opencart-test-suite which was  simplified and works with OC > 2.2. I use it exensively in my projects... If you need any help with the unit tests I could definitely help.

**Comment by ruilorenzetti** [comment]
@jamesallsup the current tests can run without problems against the project, or there is modifications to do  ?

**Comment by ruilorenzetti** [comment]
I ran the current tests and there is a problem in opencart/tests/phpunit/opencart/system/engine/EventTest.php on line 3

The problem is because  don't exists the base class.

The output is: 
Fatal error: Class 'OpenCartTest' not found in /opt/lampp/htdocs/opencart/tests/phpunit/opencart/system/engine/EventTest.php on line 3

I don't found the OpenCartTest, by the way.

**Comment by danielkerr** [comment]
removing the tests. its not required.
