### ISSUE TITLE
Issue in image manager

### ISSUE THREAD

**Issue by ihorsl** [opencart/opencart#5051]
There is a file 1.jpg in folder at server
If I upload the other file with name 1.jpg opencart shows message, that file was uploaded to server.
But actually previous file 1.jpg is not replacing with new file 1.jpg

**Comment by johnwongoc** [comment]
Yes. It doesn't work like that. The system will keep both images. You have to remove the previous one first then upload the new one.

**Comment by ihorsl** [comment]
In that case it should give an information about that to user

I made such changes in my opencart shop :

`. . . 

			} else {
				$json['error'] = $this->language->get('error_upload');
			}
		}




//--------------------------------------------------------
// BUGFIX: Raise error if file with same already exists
//--------------------------------------------------------
if ( is_file($directory . '/' . $filename)) {  $json['error'] = "File with same name already exists in this folder !"; }
//--------------------------------------------------------
//	End of ISLModification
//--------------------------------------------------------		



		if (!$json) {
			move_uploaded_file($this->request->files['file']['tmp_name'], $directory . '/' . $filename);

			$json['success'] = $this->language->get('text_uploaded');
		}

		$this->response->addHeader('Content-Type: application/json');
		$this->response->setOutput(json_encode($json));
	}
`

**Comment by ihorsl** [comment]
Please unclose this issue  !!!!
it is NOT fixed !
Users will get troubles trying to upload images, if images with such names already exists.
No error message will be shown
