### ISSUE TITLE
Help me with a basic OCMOD question

### ISSUE THREAD

**Issue by donguillermo** [opencart/opencart#5053]
Hello,

I could not find detailed documentation regarding the use of search and add attributes.

I would like to modify some files, including stylesheet.css and some .tpl files.
In some cases I need to <search> and <add position="replace"> at different location in the same files.

How do you use index and offset attributes in order to change the right line ?

For instance if you have in original file :
____________________________
```
some code
Line 10 : The_line_I_want_to_change
some code
Line 20 : The_line_I_want_to_change
some code
```
_______________________________________

To change line 10 :
```
<search index="0"><![CDATA[
      The_line_I_want_to_change
      ]]>
</search>
<add position="replace" offset="0"><![CDATA[
      My_new_line
      ]]>
</add>

```
To  change line 20 :
what index and offset do i need to use ?

Thank you in advance,

**Comment by tylerbenzing** [comment]
Please close this as this is NOT where you should ask such questions. Head over to stackoverflow. Also, you don't need OCMOD to change templates. Just clone the default template and make your changes.
