### ISSUE TITLE
Opencart 2.3.0.2 problems with shipping address details, cart session data 

### ISSUE THREAD

**Issue by krshnkrishna** [opencart/opencart#5054]
I am using opencart 2.3.0.2 , i m testing with some orders where i have few issues below mentioned list 1)shipping address not into database and also i have seen in invoice also shipping address not displaying
2) once i have done check out process if i do again its not clearing existing data in getting order sometimes, even i am getting success message , not getting any mail and also orders in admin section as well.
3) if i enable cash on delivery also its not displaying while check out , some times its getting display and some times not , even if i set minimum cash on delivery is 0.

**Comment by jamesallsup** [comment]
@krshnkrishna 
Sorry to hear you have an issue, the GiHub bug tracker is not the place to post issues relating to setup, 3rd party modules or general types of questions.

Please read the [project information page](https://github.com/opencart/opencart/blob/master/README.md#reporting-a-bug-and-security-issues) which should guide you in the right direction for support.

Kind regards, J
