### ISSUE TITLE
OpenCart 2.3.0.2 - Warning: No Payment options are available

### ISSUE THREAD

**Issue by linux4everagain** [opencart/opencart#5055]
I have a store with items loaded. I have a single GEO-Zone as Romania (all zones), a single tax rate as 20% assigned to taxable goods and all the items are in the taxable goods list. As well, I have 2 currencies - EUR as default and RON, therefore the rpices are in EUR. The price conversion works too.

However, when a user wants to do the checkout, he's getting the Warning: No Payment options are available. The OpenCart address is http://www.blackpenguin.org/opencart - the store is not in "production". But I cannot get past this and it looks like a bug to me since everything is setup correctly.

**Comment by jamesallsup** [comment]
@linux4everagain 
Sorry to hear you have an issue, our GiHub bug tracker is not the place to post issues relating to setup, 3rd party modules or general types of questions.

Please read the [project information page](https://github.com/opencart/opencart/blob/master/README.md#reporting-a-bug-and-security-issues) which should guide you in the right direction for support.

Kind regards, J
