### ISSUE TITLE
Bug on 2.2, not sure how to report/fix

### ISSUE THREAD

**Issue by mariavilaro** [opencart/opencart#5059]
I found a bug in the 2.2 version, it's fixed on the last version but it breaks the 2.2.0.0 that is currently downloadable.

The error:

PHP Parse error:  syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /home/bugabebe/public_html/nueva/admin/controller/customer/customer.php on line 1105

This is the faulty code:

    } elseif (($custom_field['type'] == 'text' && !empty($custom_field['validation'] && $custom_field['location'] == 'address')) && !filter_var($value['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {

And this is the fix:

    } elseif (($custom_field['type'] == 'text' && !empty($custom_field['validation']) && $custom_field['location'] == 'address') && !filter_var($value['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {

**Comment by jamesallsup** [comment]
This has been reported many times already, please check closed issues before posting.

Thanks.

**Comment by mariavilaro** [comment]
But... it's happening in a published version on the Opencart.com website. Maybe it should be fixed on that release also?

**Comment by CoverUp** [comment]
a new release candidate is a must, dont wait the new year version
