### ISSUE TITLE
Deactivating language definitely.

### ISSUE THREAD

**Issue by newerton** [opencart/opencart#5061]
Because when the language is disabled, the "getLanguages" function does not have 'status = 1'?

https://github.com/opencart/opencart/blob/master/upload/admin/model/localisation/language.php#L333

If the language was deactivated, it should not be used in opencart.

**Comment by arnisjuraga** [comment]
"should not", but right now - if you just deactivate language - all models will still select product and all the other language information in admin forms. 

And there - it could be a huge change. But I agree with you. Disabled language `should` be disabled language.

**Comment by danielkerr** [comment]
i disagree as u need to time to setup new languages. why not just delete the language and re added when ready.
