### ISSUE TITLE
google recaptcha for multishop

### ISSUE THREAD

**Issue by weusthofm** [opencart/opencart#5063]
I would like to add the recaptcha to a second webshop, the socalled multishop. However the current google recaptcha is only feasible for main shop. How do I implement the recaptcha for the second webshop.
My idea is that you add the option for the webshop and that you add a second key from google .
Another option could be that the secret key is picked up and transferred to the concerning page like contact, login etc.

**Comment by weusthofm** [comment]
Hello,

Why is this topic closed. Till now I have no answer or suggestions. So topic should remain open.

Marcel

Verzonden vanaf mijn Huawei mobiele telefoon

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [opencart/opencart] google recaptcha for multishop (#5063)
Van: Daniel Kerr
Aan: opencart/opencart
Cc: "Weusthof, M.H.H. (EWI)" ,Author


Closed #5063<https://github.com/opencart/opencart/issues/5063>.

-

**Comment by danielkerr** [comment]
Your under the wrong impression, that the github is not for providing support
