### ISSUE TITLE
Admin View Product SKU Filters

### ISSUE THREAD

**Issue by jimmypinto** [opencart/opencart#5064]
Working to show SKU column and SKU filter option in admin view of Opencart 2.0.2.0 Version. I am updating `/admin/controller/catalog/product.php` but its not showing any updates. The product list comes even after commenting total code of `/admin/controller/catalog/product.php` file. It shows nothing when I comment getProducts($data = array()) function of `admin/model/catalog/product.php` file. So, I am guessing `/admin/controller/catalog/product.php` file is not right controller file which sends data to view. Please help me in finding the right controller product file.

**Comment by arnisjuraga** [comment]
You are modifying correct controller. It's `admin/controller/catalog/product.php` un for product list you must change method `getList()` (~line 225, in original OC2020).

But - if it's seems, does not change anything - be aware - *check Modifications* 

1. is there any files in `system/modification` ? If so, it means OCMOD is taking original source files and modifies them, then puts in `system/modification`. For dev - you can try to change these files directly, but they WILL be overwritten on modifications refresh.

2. try to refresh modifications - in admin go to `Extensions > Modifications`  and click refresh and clear.

**Comment by jimmypinto** [comment]
Hi rnisjuraga, you are awesome. Yes, its storing files in `system/modificaion`. I refreshed modifications in the front end and it gave me the expected results. Thanks a ton :)
