### ISSUE TITLE
Opencart admin only refreshes

### ISSUE THREAD

**Issue by Xneaky** [opencart/opencart#5066]
I've been trying to log in into my opencart admin but whenever I try to log in, it only refreshes the page and never goes into the dashboard, I've been reading about this problem and some fixes however none has worked for me.

**Comment by arnisjuraga** [comment]
There is some problem with your installation or technical problems.
You should try to ask for a support in https://forum.opencart.com/ or look for any developer or administrator of the server.

If you need help, let me know pm. 

But this is not an issue for github anyway.
