### ISSUE TITLE
Refresh modification. Clear log

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#5070]
If you do not clean the log modifier, then after a while it becomes very large. But inforomatsiya in such a large file will be useless.
You must log changes overwrite every time you update.

/system/library/log.php
	public function __construct($filename, $clear=false) {
$mode = $clear?'w':'a';
		$this->handle = fopen(DIR_LOGS . $filename, $mode);
	}

admin/controller/extension/modification.php
// Log
			$ocmod = new Log('ocmod.log', true);
			$ocmod->write(implode("\n", $log));

**Comment by arnisjuraga** [comment]
I think this is great idea. 
Either refresh, or with timeout, but log file should be truncated time to time definitely.

**Comment by danielkerr** [comment]
there is already a clear button

**Comment by arnisjuraga** [comment]
The problem is, that if you don't clear it manually, then eventually it can become huge and keep space or impact performance.
E.g. - VQMOD log files are rotated by week day, I think - this is great example of the reason WHY it must be done.
