### ISSUE TITLE
Voucher e-mails are not automatically sent

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#5071]
Voucher e-mails are not automatically sent when an order is placed, nor when its order status is changed to the "Complete" status set in System > Settings. It looks like the only code to send the voucher e-mail is in /admin/model/sale/voucher.php, which is only triggered when manually clicking the "Send" button in Sales > Gift Vouchers > Gift Vouchers. 

This seems to be the case since at least 2.1. Previous versions (like 2.0.3) triggered it in the /catalog/model/checkout/voucher.php file. Am I missing something in 2.1+ for where it's automatically sent?

**Comment by danielkerr** [comment]
Fixed in Dev branch
