### ISSUE TITLE
WARNING - Error in logic that validates the product stock

### ISSUE THREAD

**Issue by prhost** [opencart/opencart#5073]
I think there is an error in the logic of this if this code is in several controllers like `upload/catalog/controller/api/order.php` `upload/catalog/controller/checkout/confirm.php`, etc ...

You need to search all controllers for this logic and fix it.

```
// Cart
if ((!$this->cart->hasProducts() && empty($this->session->data['vouchers'])) || (!$this->cart->hasStock() && !$this->config->get('config_stock_checkout'))) {
    $json['error'] = $this->language->get('error_stock');
}
```

**Comment by danielkerr** [comment]
WARNING why WARNING?
did you put that to get every ones attention or just mine!!!!

you have not even pointed out the issue!

**Comment by arnisjuraga** [comment]
@prhost please, if you really have something serious or important, then give more information. Otherwise it completely useless :(

**Comment by prhost** [comment]
The way I wrote the issue is not the case, I thought it was a serious problem, it mattered more with how I wrote than with the error in your code. I just reported the logic error and what part of the code this is, I think it's programmer enough to identify the problem files and fix it. I did not send MR because my fork is in conflict.

**Comment by arnisjuraga** [comment]
Can you post it here or send it to email?

**Comment by prhost** [comment]
@arnisjuraga Just remove the `!` From the `$this-> config->get('config_stock_checkout')` problem is that there are several files.

**Comment by arnisjuraga** [comment]
@danielkerr is it relevant?

**Comment by danielkerr** [comment]
!$this->config->get('config_stock_checkout')

is correct

allow check out if no stock: yes / no

so if no then compare if has stock.

so

!$this->cart->hasStock() 
in stock = NO

!$this->config->get('config_stock_checkout')

allow checkout if no stock display error!

**Comment by danielkerr** [comment]
@prhost the code has not been changed for a copule of years and your the 1st one to claim there is an issue!

next time explain in fully or get a ban as i dont have time to waste on non issues!.

**Comment by prhost** [comment]
The `$this->config->get('config_stock_checkout')` function (which checks inventory at checkout) returns 1 for enabled and 0 for disabled. If I want to check inventory at checkout I enable it, right? Then to enter in the if it would need this enabled along with the negation if it has stock.

The current logic is like this:
`(!$this->cart->hasStock() && !$this->config->get('config_stock_checkout'))`

Which is more readable like this:
`($this->cart->hasStock() == false && $this->config->get('config_stock_checkout') == false)`

This way I need to keep the configuration disabled so that it stays = true and validates.
1 with negation gets 0, it will never get into `if` if the stock is false which negates becomes true.

Another example

```
$hasStock = false; //out of stock
$config_stock_checkout = 1; //enable

(!$hasStock && !$config_stock_checkout) 
```

$hasStock becomes true and $config_stock_checkout becomes false, it will never get into `if`.

**Comment by danielkerr** [comment]
so your argument is your way is more readable rather than their being an issue!

**Comment by danielkerr** [comment]
stop wasting my time!

**Comment by danielkerr** [comment]
nrext post gets you a banned! this is not he 1st time you have reported non issues that has cost me a lot of time to investigate
