### ISSUE TITLE
Fatal error: SessionHandler::create_sid(): Cannot call default session handler in Unknown on line 0

### ISSUE THREAD

**Issue by GasparSukk** [opencart/opencart#5074]
OC: 2.3.0.2

Front-end crashes (blank page):
Fatal error: SessionHandler::create_sid(): Cannot call default session handler in Unknown on line 0

After i login in admin the error is gone and site operates again.

**Comment by danielkerr** [comment]
are u using different version of php one for the admin one for the rest of the site.

**Comment by GasparSukk** [comment]
Same version of PHP. Well, now it displays this error in both area.
