### ISSUE TITLE
Fatal error: Class 'Controllercommon' 

### ISSUE THREAD

**Issue by Aniapl** [opencart/opencart#5075]
Please help!
Everything was fine, then I installed module (cookie) and suddenly when you want to log in to the administrative panel appears:
Fatal error: Class 'Controllercommon' not found in /home/imaginac/domains/imaginacyjna.pl/public_html/upload/system/engine/loader.php on line 28

I do not have the original file from loader.php before installation module.

28 line is:
$ Controller = new $ class ($ this-> registry);

If someone finds a moment to please help, I will be very grateful!

**Comment by kostasmoure** [comment]
Aniapl please this is not the right place to write your problem.... go to forum and make a new post with your details and dont forget to write also the opencart version you use.
