### ISSUE TITLE
UI - Mouse on "Select All / Unselect All" does not have "pointer" style

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#5079]
OC 2.3.0.2

go to `System > Users > User Groups`
Click on `Edit` any group, 
check the mouse cursor on links. Should be "pointer":

![image](https://cloud.githubusercontent.com/assets/2185289/21082193/63636592-bfdf-11e6-9b49-dcd2f4cabc37.png)

**Comment by stefanhuber** [comment]
Could be solved in two ways:
 - button with classes 'btn btn-link`
 - a tag with empty href attribute

According to accessiblity principles a button should be used, as this is not a link.

**Comment by arnisjuraga** [comment]
The same must then be done in all places: https://github.com/opencart/opencart/search?utf8=%E2%9C%93&q=text_select_all
