### ISSUE TITLE
 I want to change the default sort order in my opencart store to decreasing by stock_status_id but i cant

### ISSUE THREAD

**Issue by mahsash5** [opencart/opencart#5080]
i did these:

catalog/controller/product/category.php

i changed:

if (isset($this->request->get['sort'])) {
            $sort = $this->request->get['sort'];
        } else {
            $sort = 'p.stock_status_id';
        }

in default when i refresh the page no action work just when i selected default choice i see this code "?sort=p.stock_status_id&order=DESC&limit=100" but not sort by stock_status_id yet!! plz help me!

**Comment by arnisjuraga** [comment]
`catalog/model/catalog/product.php` has "limit" of allowed sort order columns.

Add additional key here, this could help:

~~~php
$sort_data = array(
	'pd.name',
	'p.model',
	'p.quantity',
        'p.stock_status_id', // << something like this. Add this line.
	'p.price',
	'rating',
	'p.sort_order',
	'p.date_added'
);
~~~

This could help.

But please - do not post support questions here in Github. Please, use community forum!

**Comment by mahsash5** [comment]
thanks alot ,but in which file i can define this?
im new in open cart

**Comment by arnisjuraga** [comment]
Please, close the issue and you can post it in forum. This is support question, so not for Github.
Or send me pm.
