### ISSUE TITLE
opencart 2.3.0.2 version problem with customer login

### ISSUE THREAD

**Issue by krshnkrishna** [opencart/opencart#5081]
I am using opencart 2.3.0.2 ,i have installed it, when i see page products cost is saying with including taxes and with excluding taxes, in front end pages, if i add products to cart it is working fine.. Now i register any customer , and login with that customer , the products price showing without taxes, even if i add products to cart also its is not displaying taxes which is enabled..

I am facing this problem i m unable to move forward with this problem

**Comment by arnisjuraga** [comment]
When customers register, they choose Country and Zone. 
So, the tax is calculated based on customer Geo Zone. You must check whether tac slass are correctly defined.

If customer is registered to Geo Zone, to which tax is not defined, then prices will be displayed without tax.

Check those settings.

**Comment by danielkerr** [comment]
some coutnries you need to pay tax if your online store is based there and others where your shipping the goods to. this is down to usa state taxes.
