### ISSUE TITLE
When using Store Credit and Rewards points together - If cart total is zero, Free Checkout does not show as a payment option and therefore does not allow a user to checkout.

### ISSUE THREAD

**Issue by uksitebuilder** [opencart/opencart#5082]
Example

User has store credit of $10
User has 10 reward points (equates to $10)

Free checkout is enabled in the admin

Products in cart total $20

Balance of cart correctly reduces to $10 after using store credit

User enters Rewards points to be used which effectively reduces cart total to zero

User cannot checkout even though Free Checkout is enabled and gets error message stating No payment methods are available, contact store owner.

**Comment by danielkerr** [comment]
you mean they can not be used together when they make the price go to zero!

otherwise if not zero can still proceed!

uses better titles in future because its misleading!

**Comment by uksitebuilder** [comment]
Sorry, Daniel, yes, when the balance is zero after using both together, free checkout is not available.
