### ISSUE TITLE
[PAYPAL EXPRESS] with version 3.2.0.2 

### ISSUE THREAD

**Issue by craigbaines** [opencart/opencart#5084]
There seems to be a whole bunch of issues with this. Iv'e been trying to set up recurring payments, ive had issues with the cancel button admin side not being able to load the accounts/ model, which obviously doesn't exist admin side.

Im having problems customer side cancelling a recurring profile, it just doesn't work. 

the ipn isnt updating the order status at all. 

Iv'e changed the line that was merged here a few days ago, regards it breaking when you issue a refund. That works now but again doesn't the update order status after it. 

Im honestly loosing the will to live with it, im only after the default features that it offers but nothing seems to work, at this point im really just considering downgrading my opencart version, i would have thought this should all be working?

Does anyone have a working set of files for paypal express/ recurring payments? Im trying to fix them but iv'e never used it before so i'm not sure on what it should be doing by default so its making is quite tricky.

**Comment by danielkerr** [comment]
has been removed in latest version and is replaced with a new intergration.
