### ISSUE TITLE
Error when Product name contains  quotation mark;  eg: 2016 Hot "vat" hoodies 

### ISSUE THREAD

**Issue by tianzhidao28** [opencart/opencart#5087]
Error Picture : 
![qq20161218-0](https://cloud.githubusercontent.com/assets/2037847/21293578/0cca2196-c564-11e6-9fed-9bea42a86e1c.png)

sql when product name contains " "  "

```
 $query = $this->db->query("SELECT m.name from " . DB_PREFIX . "manufacturer m left join " . DB_PREFIX . "product p on m.manufacturer_id = p.manufacturer_id  WHERE 1     AND p.product_id = ".$product_id);
 17                 return ($query->row['name']) ? $query->row['name'] : '';


```

**Comment by arnisjuraga** [comment]
I cant reproduce it on OC 2.3.0.2
From the path, I see you are using some modification, some modele. 
Can You try to change to default theme or disable all modules?

Are the problem still exists then?

**Comment by kostasmoure** [comment]
You are using journal theme with system performance enabled. Try disable and then try again. I think it has something to do with minify html + js
