### ISSUE TITLE
Image manager search field

### ISSUE THREAD

**Issue by dudman** [opencart/opencart#5092]
It dosn't seem that this works, unless I don't understand the purpose of it. 

Even typing the name of a displayed image, hitting return key shows not a single image.

Is this image manager just broken ? or does everyone buy a seperate module for simple functionality ?

Without any search its very differcult to find files, i'd prefer just to remember the names of files and not have any selection dialog.

**Comment by arnisjuraga** [comment]
Yes, you are right. 2.3.0.2 version has this bug it seems.

You can try to replace this filw with the latest one (create a backup before!!!) 

https://raw.githubusercontent.com/opencart/opencart/master/upload/admin/controller/common/filemanager.php

But even with this version - search works only by "start of string", e.g. `log` will find `logo.png` but `ogo` will not find `logo.png`.

@danielkerr - do you have the issue registered alrady for this?

**Comment by danielkerr** [comment]
This is working in the e v branch so fixed

**Comment by webcorvo** [comment]
Hi Daniel, could you please send the link of file?
Thanks ;o)

**Comment by webcorvo** [comment]
Sorry but is not working :o(

**Comment by webcorvo** [comment]
Sorry but is not working :o(

**Comment by danielkerr** [comment]
dev branch

**Comment by webcorvo** [comment]
sorry :o( where is that ?!

**Comment by webcorvo** [comment]
Sorry Daniel, but i just tested is not working :(

**Comment by webcorvo** [comment]
https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/filemanager.php

**Comment by RaidoDev** [comment]
? 
https://github.com/copona/copona/commit/c0c039b5896a23fd29739e3008d7afb328bdebc9

**Comment by webcorvo** [comment]
Hi RadioDev i am trying to use de new filemanager.php but i no´t found a version that works :(

**Comment by webcorvo** [comment]
https://github.com/opencart/opencart/blob/dev/upload/admin/controller/common/filemanager.php

Don´t work :(
