### ISSUE TITLE
$this->config->get('config_language') has no priority over HTTP_ACCEPT_LANGUAGE

### ISSUE THREAD

**Issue by dvlprs** [opencart/opencart#5093]
Right now the language detection looks like this:

```
// Language Detection
if (!empty($this->request->server['HTTP_ACCEPT_LANGUAGE']) && !array_key_exists($code, $languages)) {
	$browser_languages = explode(',', $this->request->server['HTTP_ACCEPT_LANGUAGE']);
	// ... further detection
}
if (!array_key_exists($code, $languages)) {
	$code = $this->config->get('config_language');
}
```
Taken from [startup.php:54](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/startup/startup.php#L54).

The code checks the browser language in `HTTP_ACCEPT_LANGUAGE` first, and if it's installed, it then doesn't even look at the configured value. 

In a multilingual store that has a bunch of languages installed, there seems to be no way to force the sites to use a config language, because the `HTTP_ACCEPT_LANGUAGE` condition executes first, and it just never gets to `$this->config->get('config_language')`.

**Comment by rodrigomanara** [comment]
just look into the code and the language set up received the variable $code.

check line 40, it will start from there. [look](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/startup/startup.php#L40)

**Comment by dvlprs** [comment]
@rodrigomanara thank you for your reply. Sorry, I'm not sure I'm following what you're trying to say. 

You're right, the `$code` variable is declared on line 39. However, my point is: the store configuration language has no preference over the browser language.

**Comment by rodrigomanara** [comment]
i see!, I think you need to patch a suggestion

**Comment by danielkerr** [comment]
yes its supposed to try to detect the correct language to use rather than being assigned one.
