### ISSUE TITLE
Admin order editor API documentation

### ISSUE THREAD

**Issue by JaggedJax** [opencart/opencart#5095]
Is there documentation on the Opencart API anywhere?

The main website says there's an API, but if you click for more info it just takes you to the opencart homepage. The documentation has an API page under Users but it is completely blank.

Does opencart have an API for things like getting new orders from the system? The `controller/api/order.php` file is the closest thing I can find but it appears you need to already know the order number to get it. Is there a search by date or status feature or are 3rd party extensions required for this feature to work?

**Comment by ruilorenzetti** [comment]
I am new here, but I think that I contribute with this @danielkerr  Can you guide me in this first work ?    The solution is change the build.xml to construct the documentation, verify the code beginning of the rest api and others borders like mentioned one.

**Comment by arnisjuraga** [comment]
+1

**Comment by JaggedJax** [comment]
The main functionality we needed in an API was the ability to download a list of new orders and then upload tracking information.

We found the following extension as a starting point: https://github.com/gosweetspot/OpenCartRestApiV2

We forked it and added the following functionality via new API endpoints: https://github.com/CartRover/CartRover-OpenCart-RestAPI

- List orders by date and status
- List of possible order statuses (for use in above call)
- List products and their inventory levels
- Update inventory levels for specific product

The existing api/order/history endpoint allows us to add a note with the tracking info.

**Comment by Felix-Ho** [comment]
@JaggedJax If you would like to take a look the API documentation.
Please have a look from
http://docs.opencart.com/en-gb/system/users/api/

Hope this help!

**Comment by danielkerr** [comment]
ask jesse to make it look niucer please
