### ISSUE TITLE
Unnecessary things in catalog/model/catalog/product.php

### ISSUE THREAD

**Issue by kagan94** [opencart/opencart#5097]
Hi.

In the method "getProductSpecials"(**catalog/model/catalog/product.php**) you shouldn't use additional select for rating because in the end you only get product info by "product_id". There no need to use extra select by rating:
```
DISTINCT ps.product_id, (SELECT AVG(rating) FROM " . DB_PREFIX . "review r1 WHERE r1.product_id = ps.product_id AND r1.status = '1' GROUP BY r1.product_id) AS rating FROM " . DB_PREFIX .
```
And as I wrote before, in the end, you request all info about product by its product_id
```
foreach ($query->rows as $result) {
     $product_data[$result['product_id']] = $this->getProduct($result['product_id']);
}
```

**Comment by danielkerr** [comment]
rating is used for sorting in this context not for the information!

**Comment by kagan94** [comment]
Daniel, to be honest, it's not logical because you rewrite the data of each product in the loop later.

**Comment by danielkerr** [comment]
It's used for sorting

**Comment by kagan94** [comment]
Sorry. Now I see.
