### ISSUE TITLE
Problems with CatalogModelAccountCustomerTest::customerLogin() 

### ISSUE THREAD

**Issue by ruilorenzetti** [opencart/opencart#5099]
This method doesn't exists. (customerLogin() )
Whats this method must call ?? I searched the entire project (v 2.2.3 candidate release) without success.
I changed the class inheritance to became more clear the tests, I have some tests that works but this one is tricky. 

Thanks in advanced.

<?php

class CatalogModelAccountCustomerTest extends PHPUnit_Framework_TestCase{

        //The rest was omitted for sake of clarity 

	public function testEditNewsletter() {

		$this->customerLogin('customer@localhost', '', true);

		$this->model_account_customer->editNewsletter(1);

		$row = $this->db->query("SELECT * FROM " . DB_PREFIX . "customer WHERE customer_id = 1")->row;

		$this->assertEquals(1, $row['newsletter']);
	}

	.....................

**Comment by danielkerr** [comment]
I'm closing this as it's duplicate the tests not working
