### ISSUE TITLE
Error: Invalid session ID!

### ISSUE THREAD

**Issue by drsect0r** [opencart/opencart#5100]
OpenCart has a session ID length limitation between 22 and 52 characters. Is there any reason why this is the case? https://github.com/opencart/opencart/blob/master/upload/system/library/session.php#L25

We have sha512 configured as the hash algorithm used to generate the session IDs. Can I create a merge request to change this or perhaps remove this limitation? 

Poke @danielkerr as he seems to have done previous work on sessions.

**Comment by danielkerr** [comment]
yes

**Comment by drsect0r** [comment]
Could this be merged?

**Comment by danielkerr** [comment]
Yes, will merge just do the ppull request

**Comment by drsect0r** [comment]
Great, merge request already exists: https://github.com/opencart/opencart/pull/5101

**Comment by drsect0r** [comment]
...

**Comment by danielkerr** [comment]
ok done but not sure it should be unlimited
