### ISSUE TITLE
Please revert TWIG system

### ISSUE THREAD

**Issue by Shinrai** [opencart/opencart#5102]
Beyond the fact that a MVC model template system should be doing little to no logic. The TWIG system is simply bloat ware upon opencart.
I just did a fresh install of OC 2.3 and OC 3.0 (dev). Here are the results:

**OC2.3:**
- 140-180ms load time
- Shows slider
- Shows featured products (4)
- Shows brands

**OC3.0**
- 280-340ms load time
- Shows featured products (4)

So OC3.0 is showing 2 less modules and is taking twice the load time? What could possibly be the benefit of using TWIG over native PHP, considering View should have little to no logical code?

**Comment by arnisjuraga** [comment]
Needs more tests.

**Comment by Shinrai** [comment]
In Microseconds with 3.0 and PHP as the template engine:
- Template-Time:0.00014877319335938
- Template-Time:0.00015497207641602
- Template-Time:0.00016927719116211
- Template-Time:0.0001370906829834
- Template-Time:0.00014615058898926

In Microseconds with 3.0 and TWIG as the template engine:
- Template-Time:0.0063667297363281
- Template-Time:0.0060136318206787
- Template-Time:0.0070564746856689
- Template-Time:0.0074975490570068
- Template-Time:0.0066244602203369

TWIG in it's BEST time is still 72% slower compared to PHP's worst time.

Twig adds 6 ms, at it's best, to the page load just for the home page (which presents that there may be other significant performance issues coming in 3.0). Compared to PHP which adds less than 2 ms at it's worse.

Same server, same code. Simple flag to tell the system if to use TWIG or PHP for template. Ran them against Pagespeed Insights. The one running PHP comes up with the usual issues of OC. However the report for the TWIG version comes up with:
- Reduce server response time

Obviously from my own tests recording the micro seconds of the template system there is more degrading the performance of CO 3.0 compared to OC 2.3. However a single system literally tripling it's usage for minimal improvement if any?

**Comment by prhost** [comment]
That's obvious, template parser will always be slower than native php, but it also needs to compare benefits, Twig's idea is to bring agility and organization into development.

**Comment by dmitriyzhuk** [comment]
I think that the time spend to generate a twig layout is relatively nothing to the time it sometimes takes to fulfill a MYSQL request. Of course plain php is faster - no doubt about that. But this can be easily optimized with caching which is usually the case for high traffic sites.

the advantages of Twig among many are the ability to separate the logic and help keep sustainable code. Unlike you, people have no clue that the view should be close to no logic. people add outrages php code, looping and formating texts, adding php validation and more. not to metion this all goes bonkers with a nifty vqmod script.  

if we want opencart to move to a more professional state, we need a tempting engine that can block crazy stuff thus reducing conflicts. 

We actually used Handlebars before twig in our modules. we added support for partials and much more. twig is also a good option so we really don't care - as long as its a robust templating engine that can filter our malicious php.

**Comment by arnisjuraga** [comment]
@dmitriyzhuk Agree!

**Comment by dmitriyzhuk** [comment]
https://github.com/Dreamvention/2_d_event_manager Added Events to old opencart versions

**Comment by danielkerr** [comment]
i will add caching in 3.1 which should fix these issue outright. for now its fine.

**Comment by danielkerr** [comment]
opencart is the fastest on the market so 6ms is not to bad

**Comment by Shinrai** [comment]
> On average with PHP as the template engine
> - the response time is approx 100ms
> 
> On average with TWIG (with caching) as the template engine
> - the response time is approx 130ms
> 
> On average with TWIG (with out caching) as the template engine
> - the response time is approx 250ms-300ms

Google want's a response time of 200ms or less. The above numbers were done with modifying OC 3.0 (back at the time of that post) to allow a file system template or the twig template. Even while enabling the cache the processing time was 23% slower. While the calls into the template system tracked 6-7ms, With only changing the template engine (I presume it's due to the loading of the TWIG system). The actual ms increase is much more.

Beyond that as TWIG's cache is file based which can lead to issues on cloud based platforms where the files do not update properly across the cloud system. Leading to errors.  I've already come across this issue with ocmod and vqmod with clients on cloud systems.

**Comment by danielkerr** [comment]
im going to use my own cache system not twigs. it will be more efficient.

**Comment by smolinari** [comment]
Out of curiosity, and I couldn't find it in the code, but does OC use Twigs compiler?

Scott
