### ISSUE TITLE
admin/model/catalog/product.php isset() is missing

### ISSUE THREAD

**Issue by yszty** [opencart/opencart#5105]
line 114 is: `if ($data['keyword']) {`

should be: `if (isset($data['keyword'])) {`

**Comment by ADDCreative** [comment]
Changing the line back to what you suggest, causes blank entries in the url_alias table. See https://github.com/opencart/opencart/pull/4559

**Comment by yszty** [comment]
Right, so: 
change: line 114
`if ($data['keyword']) {
			$this->db->query("INSERT INTO " . DB_PREFIX . "url_alias SET query = 'product_id=" . (int)$product_id . "', keyword = '" . $this->db->escape($data['keyword']) . "'");
		}`
to:
`		if (isset($data['keyword'])) {
			if ($data['keyword']) {
				$this->db->query("INSERT INTO " . DB_PREFIX . "url_alias SET query = 'product_id=" . (int)$product_id . "', keyword = '" . $this->db->escape($data['keyword']) . "'");
			}
		}`

**Comment by arnisjuraga** [comment]
Make it shorter!
~~~php
if (isset($data['keyword']) && $data['keyword'] ) {
    $this->db->query("INSERT INTO " . DB_PREFIX . "url_alias SET query = 'product_id=" . (int)$product_id . "', keyword = '" . $this->db->escape($data['keyword']) . "'");
}
~~~

**Comment by yszty** [comment]
@arnisjuraga dont agree. Its less readable, but also working. Code should be easily for human reading.

**Comment by arnisjuraga** [comment]
I am just saying...

But nesting IF statements can be more "human reading", but definitely - not "developers reading".

Nesting two IF statements inside one another is completely useless. Think about "closing brackets" - you have two of them, it's easy to make some mistake there too. It's just "more code".

It's every developer decision, which approach to use and which coding style to follow. But take a look here: https://github.com/opencart/opencart/blob/master/upload/admin/controller/catalog/product.php Opencart uses boolean pairs for IF statements, not nested `if`s. I wouldn't even consider using unnecessary duplicate code for:

~~~php
if ($a) {
  if ($b) {
    if ($c) {
      if ($d) {
          echo "Hello world!";
      }
    }
  }
}
~~~

If you can do it in one line:

~~~php
if ($a && $b && $c && $d) {
  echo "Hello world!";
}
~~~

Just learn simple boolean algebra for `&&`, `||` and so on: http://php.net/manual/en/language.operators.logical.php

**Comment by yszty** [comment]
Probably u are right. Its enough for me: "Opencart uses boolean pairs for IF statements". I just wanted keep OC style ;)

**Comment by arnisjuraga** [comment]
:)
or even:

~~~php
if (!empty($data['keyword'])) {
~~~

**Comment by yszty** [comment]
Funny xD! Its exactly what we wanted :D 

> empty() - No warning is generated if the variable does not exist. That means empty() is essentially the concise equivalent to !isset($var) || $var == false.

**Comment by arnisjuraga** [comment]
@yszty can you, please, make a pull request?

**Comment by yszty** [comment]
I dont know how to do it. What a shame..

**Comment by arnisjuraga** [comment]
The simplest way
- navigate to the correct file in opencart/opencart
- open it, and click on "edit"
![image](https://cloud.githubusercontent.com/assets/2185289/21782592/9a42a3f4-d6bc-11e6-86f9-cf4f079480cf.png)

- edit the file, and "prospose  changes", this will create new branch in your account yszty/opencart
- then you will be able from there to submit pull request.

Try it, it's fun!

:)

**Comment by yszty** [comment]
What I should do now? admin/model/catalog/category,information,manufacturer need be edited also.

**Comment by arnisjuraga** [comment]
With Github Web interface by editing files, you will create one pull request for every edited file (http://stackoverflow.com/questions/17815895/can-i-edit-two-files-then-make-one-commit-using-github-web-based-editor). 
It will take a lot of pull requests, if there are multiple files.

So the right way to do:
1) create Opencart forkto your account
2) Clone this repo locally
3) edit all files
4) push back to your fork
5) Go to Pull requests in your repo and make new request. It will take all edits you have done and make as one request.

**Comment by danielkerr** [comment]
it causes blank entires

**Comment by RaidoDev** [comment]
~~~php
if (!empty($data['keyword'])) {
~~~
is exactly what you need. This assures, not only value is set, but it "has value" larger then "empty" e.g.:

 ```"" (an empty string)```is "empty", 
so it will not generate blanks.
