### ISSUE TITLE
2.3.0.3_rc install throw undefined constant DIR_LOGS

### ISSUE THREAD

**Issue by qahar** [opencart/opencart#5106]
DIR_LOGS defined in config.php, thus installation will get error for any requirement to DIR_* constant.

**Comment by arnisjuraga** [comment]
Hi, please, can you give more info on this? When/what errors do you receive? I did a test installation but had no errors, may be I missed something.

**Comment by maddog986** [comment]
error:

Notice: Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in D:\vhosts\rcbros.com\opencart.gitsummotorsports.com\upload\system\library\log.php on line 6

**Comment by Icebox-Studio** [comment]
I decided to test this out locally using xampp. I took screenshots, too, while doing a fresh install. Please see the attached images. This error appeared on all 4 parts of the installation pages as you can see. 
![proof1](https://cloud.githubusercontent.com/assets/24770786/21561135/a10dafe6-ce36-11e6-88c3-c3b05e7d093d.PNG)
![proof2](https://cloud.githubusercontent.com/assets/24770786/21561137/a38fbfac-ce36-11e6-9d93-15843600023a.PNG)
![proof3](https://cloud.githubusercontent.com/assets/24770786/21561138/a52b9296-ce36-11e6-8628-1f902a6a82f4.PNG)
![proof4](https://cloud.githubusercontent.com/assets/24770786/21561139/a67d6bd8-ce36-11e6-9742-0423d168cd3d.PNG)

**Comment by arnisjuraga** [comment]
OK, @danielkerr 
https://github.com/opencart/opencart/blob/master/upload/install/index.php should include `DIR_LOGS`  constant as well.

**Comment by arnisjuraga** [comment]
@qahar please, can you test:

1. After line 
`define('DIR_OPENCART', str_replace('\\', '/', realpath(DIR_APPLICATION . '../')) . '/');`
in `install\index.php` add this line:
~~~php
define('DIR_LOGS', DIR_OPENCART . 'system/storage/logs/');
~~~

2. Run installation tasks. No, error should no appear, but **post errors from log file** 
`system/storage/logs/error.log` - you should have some.

**Comment by arnisjuraga** [comment]
Yep, web server error log contains the error. Latest OC.

~~~
FastCGI: server "/home/www/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/www/public_html/upload/system/library/log.php on line 6, referer: http://example.com/upload/install/index.php?route=install/step_3
FastCGI: server "/home/www/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/www/public_html/upload/system/library/log.php on line 6, referer: http://example.com/upload/install/index.php?route=install/step_3
FastCGI: server "/home/www/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/www/public_html/upload/system/library/log.php on line 6, referer: http://example.com/upload/install/index.php?route=install/step_3
FastCGI: server "/home/www/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/www/public_html/upload/system/library/log.php on line 6, referer: http://example.com/upload/install/index.php?route=install/step_3
FastCGI: server "/home/www/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/www/public_html/upload/system/library/log.php on line 6, referer: http://example.com/upload/install/index.php?route=install/step_3

~~~

**Comment by Icebox-Studio** [comment]
I didn't get any errors in my error log after adding the extra line of code. Worked like a charm for me.

**Comment by arnisjuraga** [comment]
@qahar can you try latest fix from here https://github.com/opencart/opencart/commit/edb33c4241733d67195ba756afda5dbddecb2f1c and give a feedback?

**Comment by danielkerr** [comment]
ok c;losing this as DIR_LOGS has been in the system for a long time. if you are missing a contant just add it. i think only your having this issue

**Comment by danielkerr** [comment]
its there anyway
