### ISSUE TITLE
If you have ONLY "Missing orders", then admin generates "division by zero"

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#5113]
`Warning: Division by zero in /public_html/admin/controller/common/column_left.php on line 879`

Debugging gives:
~~~
$other_total == 1 (I have 1 "Missing orders" order.
$order_total == 0 (I have no other orders).
~~~

**Comment by arnisjuraga** [comment]
Please, review: https://github.com/opencart/opencart/pull/5115/commits/28113478fc6d2fbf6a8e53ecb07b71a5b0be5885

**Comment by danielkerr** [comment]
fixed a while ago
