### ISSUE TITLE
Minimum quantity applies to the 'add to cart' function, not the 'total ordered quantity'

### ISSUE THREAD

**Issue by raffraffraff** [opencart/opencart#5117]
OpenCart Version: 2.3.0.2

## To reproduce:
1. In the Admin, edit a product and set a minimum quantity to 5
2. In the Shop, browse to the product. It displays the quantity '5'. Click 'Add to cart. At this point you have satisfied a minimum _order_ quantity.
3. While still on the product page, change the quantity field to '1' to click 'Add to cart' .

## Result:
The '1' quantity value is silently ignored, and total quantity in the cart is 10. Two things are non-intuitive for the user here:
1. The entered quantity is ignored. An error would be preferable.
2. The minimum quantity applies to the 'add to cart' operation. It should apply to the ordered quantity.

**Comment by danielkerr** [comment]
ur right. i think there was a massive conversation about this and i told people its not the correct way but seems one one sunk in a the commit!

**Comment by RaidoDev** [comment]
It's still incorrect.
Validation should check the Cart for existing added products! 
validation should be true then and only if: 

```(already_in_cart.quantity + new_addition.quantity) >= minimum.quantity```
