### ISSUE TITLE
opencart purchase on online is not asking login to customer 

### ISSUE THREAD

**Issue by vinothjdx** [opencart/opencart#5123]
http://marakadai.com/

everthing is ok but .. while i'm ordering a product online as a customer i'm checking out without any login or address confirmation.

go to above website link and try to login without login. session is not starting please someone solve this

**Comment by arnisjuraga** [comment]
`try to login without login. ` ? I just registered my account, I can login and cart is working. You can see my email address in latest account registration, give me a message.

**Comment by vinothjdx** [comment]
u can login ... but please logout and purchase a product . 
i mean checkout is done without login itself .. u don't need to login just please checkout and proceed for next step u will understand..

**Comment by vinothjdx** [comment]
i changed the theme but the problem exist

**Comment by REJack** [comment]
Try to disable `Guest Checkout` in the `Option`-Tab at `Home / Stores / Settings`

**Comment by vinothjdx** [comment]
@REJack  i tried it .. its not working

**Comment by REJack** [comment]
Did you tried it with the Original Theme, its look like its your Theme prevents it?

**Comment by vinothjdx** [comment]
ya i tried it @REJack  its not working

**Comment by REJack** [comment]
thats wierd i can not reproduce this, if i disable `Guest Checkout` any customer need to create a account or login even on my custom Theme.

**Comment by vinothjdx** [comment]
i've done everything ... i didn't get any changes . its something beyond that

**Comment by REJack** [comment]
> ... its something beyond that

It seems so.

I had in the last days some errors with opencart, mods & my theme, caused by the file encodings from Windows (my Sys) to Linux Webroot. 
I installed it finally without any errors trough the Filemanger from my Server Control Panel

**Comment by vinothjdx** [comment]
thanks for helping to solve my issue  @arnisjuraga

**Comment by vinothjdx** [comment]
and also to @REJack

**Comment by arnisjuraga** [comment]
The "problem" was because of custom Quickcheckout module. 

When you install themes, sometimes they comes with custom controllers files and vqmod modules. Thus - only changing theme in admin will not have impact on custom modules.

**Comment by vinothjdx** [comment]
The issue is in guest checkout only as u said..thanks Raphael
