### ISSUE TITLE
Notice: Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /Library/WebServer/Documents/opencart/system/library/log.php on line 6  Warning: fopen(DIR_LOGSerror.log): failed to open stream: Permission denied in /Library/WebServer/Documents/opencart/system/library/log.php on line 6  Warning: fwrite() expects parameter 1 to be resource, boolean given in /Library/WebServer/Documents/opencart/system/library/log.php on line 10  Warning: fwrite() expects parameter 1 to be resource, boolean given in /Library/WebServer/Documents/opencart/system/library/log.php on line 10

### ISSUE THREAD

**Issue by kastihama** [opencart/opencart#5125]
Notice: Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /Library/WebServer/Documents/opencart/system/library/log.php on line 6

Warning: fopen(DIR_LOGSerror.log): failed to open stream: Permission denied in /Library/WebServer/Documents/opencart/system/library/log.php on line 6

Warning: fwrite() expects parameter 1 to be resource, boolean given in /Library/WebServer/Documents/opencart/system/library/log.php on line 10

Warning: fwrite() expects parameter 1 to be resource, boolean given in /Library/WebServer/Documents/opencart/system/library/log.php on line 10

even though i have tried as per the installation guide
why is this not working in my mac localhost?

**Comment by lucasjkr** [comment]
Can you check you /config.php file and verify this line exists (it's line 17 of my install):

define('DIR_LOGS', '/home/ecotrimmings/public_html/system/storage/logs/');

**Comment by arnisjuraga** [comment]
@lucasjkr /config.php cannot exist in fresh Opencart installation. It exists, if you make upgrade/update. But foo the fresh installation - it's not!

**Comment by danielkerr** [comment]
just done a fix with the commit in

**Comment by kastihama** [comment]
It's a fresh installation and in config file its empty

**Comment by arnisjuraga** [comment]
Have you tested @danielkerr fix?
