### ISSUE TITLE
PHP Unknown:  Function mcrypt_decrypt() is deprecated

### ISSUE THREAD

**Issue by eka7a** [opencart/opencart#5126]
Mcrypt extension has been deprecated in PHP 7.1
http://php.net/manual/en/migration71.deprecated.php

Instead of Mcrypt,  can be used openssl or a different method.
http://php.net/manual/en/function.openssl-encrypt.php

**Comment by arnisjuraga** [comment]
Hmm.... openssl-encrypt is available from 5.3 (which is minimal OC requirements too), so - for compatibility, you are right - could be replaced with openssl. Can you provide a pull request?

**Comment by danielkerr** [comment]
please

**Comment by eka7a** [comment]
@arnisjuraga 
At least PHP 5.4 is now required for OpenCart.
https://github.com/opencart/opencart/blob/master/upload/install/controller/install/step_2.php#L107

@danielkerr ok. I will send a pull request.

**Comment by arnisjuraga** [comment]
Sorry, you are right. I was referencing to the documentation. So, @danielkerr please update this #5132

**Comment by ADDCreative** [comment]
Don't forget to update the installers and OpenBay.
https://github.com/opencart/opencart/search?utf8=%E2%9C%93&q=mcrypt

**Comment by arnisjuraga** [comment]
#5132

**Comment by danielkerr** [comment]
already fixed yesterday to use openssl
