### ISSUE TITLE
Because you're removing all compatibility code in 2.3, please make the next update 2.4

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#5127]
Please do not make the next update 2.3.0.3. There are significant changes to many files for removing the compatibility code for older extensions, and it will cause many users to be confused why 2.3.0.2 works differently than 2.3.0.3. Any extensions that used the compatibility code to make their older extensions compatible will have them broken on 2.3.0.3, and that's not how a small incremental version number change should happen.

Please please please make the next version 2.4.0.0!

**Comment by dmitriyzhuk** [comment]
So true! You simply do not expect to a minor fix to be a compatibility brake. so yeah, please change to 2.4.0.0 

Thanks to CLearThinking for noticing this!
