### ISSUE TITLE
Error when installing via CLI: Undefined index: SERVER_PORT

### ISSUE THREAD

**Issue by sofyansitorus** [opencart/opencart#5128]
PHP Notice:  Undefined index: SERVER_PORT in /var/www/opencart.dev/public/upload/system/startup.php on line 40

**Comment by arnisjuraga** [comment]
Duplicates: https://github.com/opencart/opencart/pull/5107
But in your commit there is double spaces, and this one, I think, is more correct: https://github.com/opencart/opencart/pull/5107

**Comment by danielkerr** [comment]
Server port is not required, just set a define for it to false

**Comment by arnisjuraga** [comment]
@danielkerr Can you add this to installation script to ensure no notices appears on install?
