### ISSUE TITLE
Problem when moving server and upgrading

### ISSUE THREAD

**Issue by narektigranyan** [opencart/opencart#5133]
Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model extension/total/payment_costs!' in /var/www/example.com/public_html/system/storage/modification/system/engine/loader.php:59 Stack trace: #0 /var/www/example.com/public_html/catalog/controller/checkout/cart.php(209): Loader->model('extension/total...') #1 [internal function]: ControllerCheckoutCart->index() #2 /var/www/example.com/public_html/system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array) #3 /var/www/example.com/public_html/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #4 [internal function]: ControllerStartupRouter->index() #5 /var/www/example.com/public_html/system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array) #6 /var/www/example.com/public_html/system/engine/front.php(34): Action->execute(Object(Registry)) #7 /var/www/example.com/public_html/system/engine/front.php(29): Front->execute(Object(Action)) #8 /va in /var/www/example.com/public_html/system/storage/modification/system/engine/loader.php on line 59

I cannot figure out why it prints those errors, admin dashboard does not print any error.
Please help!

**Comment by arnisjuraga** [comment]
You have meesed something with config or modules I think.
Try to Clear all Modification in admin, And what do you mean by  "Problem when moving server and upgrading"

You should try to contact any developer for support or post in Community forum,
this is not related to Opencart source :(

**Comment by narektigranyan** [comment]
The website was on a shared hosting, now it is on VPS. I had exported MySQL and saved website on my local machine. I installed newly Opencart on my VPS and then imported the DB also uploaded the rest of files to the VPS.

**Comment by arnisjuraga** [comment]
Did You changed opencart version too? I mean - Shared hosting had older version as the new one?

**Comment by narektigranyan** [comment]
Yes, it had older version, for VPS I downloaded the most recent version

**Comment by narektigranyan** [comment]
Also I deleted the whole modifications in Extension in admin panel

**Comment by arnisjuraga** [comment]
I see - at first, you _must_ have the same version on VPS, if you are using any custom code\modules\extensions\theme! Latest Opencart could bet not be compatible with your site at all. 

So
1. Try to find and install the same Opencart version
2. contact any Dev support, if you still have issues :(

**Comment by narektigranyan** [comment]
In Modifications it dumped some error log. can it be usefull?

**Comment by narektigranyan** [comment]
Thank you very much! I will try to install the same version

**Comment by danielkerr** [comment]
personal issues are not to be posted here!
