### ISSUE TITLE
Opencart 2.1.0.2 Not Sending Out Confirmation E-Mails

### ISSUE THREAD

**Issue by Deadwood83** [opencart/opencart#5141]
I am able to recieve email notifications when registering a new customer, placing orders using cash on delivery but i never get confirmation emails after making payments using card.

In the backend, Under sales, orders placed using the card payment option appear as missing orders, instead of processing and appearing in the order list.

How can i fix this? What exactly is the issue?

**Comment by arnisjuraga** [comment]
This means, card payments extension does not work correctly.
Successful payment should change the order to setup order process and the mail should be delivered at that moment.

So this must be an issue for used cards payments extension.

**Comment by Deadwood83** [comment]
So how do I fix the extension?

**Comment by arnisjuraga** [comment]
Depends from an extension. Which cards processor do you use.
If its not core extension used from Opencart source, then it's not an issue of Opencart :(

**Comment by Deadwood83** [comment]
@arnisjuraga i got the extension from opencart, and its from a developer. GTPay is the name of the extension. Is there anyway i can fix this, also having in mind that my coding skills are beginner level.

**Comment by arnisjuraga** [comment]
GTPay is not included in Opencart source. If you have downloaded/bought it from opencart.com, you should contact the developer or ask this question in Community forum, please.
