### ISSUE TITLE
install.sql how to uninstall.sql

### ISSUE THREAD

**Issue by zastil** [opencart/opencart#5147]
If you say add column via alter table how to you remove it on uninstall.

Running this 

ALTER TABLE oc_product_option
ADD hide_option_price tinyint(1) default 0;

But if you already had it installed and go to install again you will get error and module won't install.

**Comment by trinkaljuneja** [comment]
hope this helps 

http://stackoverflow.com/questions/3395798/mysql-check-if-a-column-exists-in-a-table-with-sql

**Comment by zastil** [comment]
Thx I used 

SET @s = (SELECT IF(
    (SELECT COUNT(*)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE table_name = 'oc_product_option'
        AND table_schema = DATABASE()
        AND column_name = 'hide_option_price'
    ) > 0,
    "SELECT 1",
    "ALTER TABLE oc_product_option ADD hide_option_price TINYINT(1) NOT NULL DEFAULT '0'"
));

PREPARE stmt FROM @s;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
