### ISSUE TITLE
Install controller method not getting called in version 2.3.0.2

### ISSUE THREAD

**Issue by peterchaula** [opencart/opencart#5149]
I have a module with the controller class in `upload/admin/controller/module/my_module.php`
```

class ControllerModuleMyModule extends Controller{
     public function index(){
              die('My module index');
     }
     
    public function install(){
         //install logic here
         //create tables
    }
}

```
This works in earlier version of OC. However in 2.3.0.2  it's not the case. The method never gets called

**Comment by osworx** [comment]
Guess you are missing some.
With 2.3.x modules for example are located in
`..admin/controller/extension/module/my_module.php`

**Comment by peterchaula** [comment]
Yeah. I was missing something because of the old example I was following
