### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by CCOC-Rick** [opencart/opencart#5150]
I am using OpenCart 2.3.0.2 and I am getting this error when trying to upload an extension through the Extension Installer.  From what I can gather, the system is uploading to a temp directory with the user:group of the web server and then trying to FTP in with a different user who is not part of the web server group to that directory so the permission is denied.

This only happens when I upload an extension that is a zip file where it needs to extract an archive to then be processed.  Just an XML file works fine.

It seems like the files should either be set to a permission of 777 or the user:group needs to be the same as the user from the FTP settings.

-----------------------
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

OK

<b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin: Permission denied in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog: Permission denied in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/controller: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/language: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/model: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/view: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/controller: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/language: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/model: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/view: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/controller/blog: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/language/en-gb: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/language/ru-ru: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/language/tr-tr: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/model/blog: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/view/template: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/controller/blog: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/language/en-gb: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/language/ru-ru: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/language/tr-tr: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/model/blog: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/view/theme: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: ftp_put(): Illegal PORT command in <b>/admin/controller/extension/installer.php</b> on line <b>344</b><b>Warning</b>: ftp_put(): Illegal PORT command in <b>/admin/controller/extension/installer.php</b> on line <b>344</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/language/en-gb/blog: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/language/ru-ru/blog: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/language/tr-tr/blog: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: ftp_put(): Illegal PORT command in <b>/admin/controller/extension/installer.php</b> on line <b>344</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): admin/view/template/blog: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: ftp_put(): Illegal PORT command in <b>/admin/controller/extension/installer.php</b> on line <b>344</b><b>Warning</b>: ftp_put(): Illegal PORT command in <b>/admin/controller/extension/installer.php</b> on line <b>344</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/language/en-gb/blog: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/language/ru-ru/blog: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/language/tr-tr/blog: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: ftp_put(): Illegal PORT command in <b>/admin/controller/extension/installer.php</b> on line <b>344</b><b>Warning</b>: Invalid argument supplied for foreach() in <b>/admin/controller/extension/installer.php</b> on line <b>332</b><b>Warning</b>: ftp_mkdir(): catalog/view/theme/default: No such file or directory in <b>/admin/controller/extension/installer.php</b> on line <b>337</b><b>Warning</b>: ftp_put(): Illegal PORT command in <b>/ad

**Comment by osworx** [comment]
Looks to me more than a permission problem.
Or did you forgot to define your FTP credentials?
Check the extension store for FTP replacements and use such - they need no FTP data.

**Comment by danielkerr** [comment]
FTP stuff has been removed in latest
