### ISSUE TITLE
Call to undefined method Language::all

### ISSUE THREAD

**Issue by trueliarx** [opencart/opencart#5153]
On a freshly installed opencart 2.3.0.3rc when I view a new order I get this error message:

Fatal error: Call to undefined method Language::all() in \admin\controller\extension\openbay.php on line 477

The "function all()" doesn't exists anymore and I don't know why it loads openbay even if I didn't activate it (I never use openbay).

Maybe I can be wrong but It would be better to exclude openbay on default installation.
I added the old "all" function as a workaround for testing.

	public function all() {
		return $this->data;
	}

**Comment by hrm143** [comment]
i have the same issues with me...any solution?

**Comment by trueliarx** [comment]
just add the function as showed before 
in system/library/language.php

> public function all() {
> 	return $this->data;
> }

**Comment by jamesallsup** [comment]
Added back all() and merge() methods for this branch. 3.x will be the next release but they have been added back to 2.3 to allow people to use the rc branch if needed (it contains quite a few fixes).
