### ISSUE TITLE
Multilanguage support for urls

### ISSUE THREAD

**Issue by ktaranov** [opencart/opencart#5157]
Hi, guys.

How can I get different urls for dual language store? For example:
 - /ru/product1
 - /en/product1

**Comment by arnisjuraga** [comment]
This is not supported by Opencart. You must look up for some modules to do it. 
I have used one and modified it for OC2 too. So, let me know, or search in Community forum.

**Comment by ktaranov** [comment]
Could you provide links for this modules, I try some free but they didn't properly works

**Comment by dmitriyzhuk** [comment]
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=29764&filter_search=dsm

**Comment by ktaranov** [comment]
Thanks for answers, closed.
