### ISSUE TITLE
Document the API for god's sake!

### ISSUE THREAD

**Issue by dmitriyzhuk** [opencart/opencart#5159]
Hi guys, the name is to drive more attention. The main goal - we need to stop changing the api of the framework.

look, after so many new versions, we end up with new file structures, missing model methods, models moved to other folders, even system libraries end up having different names of methods. 
I don't want to create a new repo just for the version 2.3.0.2 because it changed so dramatically that i can't create a compatibility fix. Keeping two basically same repos in sync is time and cost consuming. If you have 100 modules, you end up having 200 modules. Changing one repo means changing 2 repos and so on. I am ok with having two repos for opencart 1.5x and 2.x but not in the same major version. its not a good sign. 

I know that there is nothing ideal, and change is inevitable. But isn't thats the point of a strict API - change the code, don't change the endpoints. 

I don't like wordpress core, but I like wordpress API documentation. I like that if I develop a new extension, it will most likely work with the next update. That I don't need to duplicate core methods simply to avoid getting them removed in the next version or for compatibility through the major versions. 

And I am not talking about keeping all the old shit just to have a backwards compatibility like wordpress. I am simply saying - lets all sit and write it down. 

Make a simple GITHUB repository where we go through all our model methods,  system methods, even controllers. Where we define their attributes and returning values. And we say - thats it. thats the API - please take it into consideration when  changing something. I understand this is pointless for the 2.x but we can still help it in version 3.x 

So for now, please write your thoughts and lets see if we are on the same page.

**Comment by danielkerr** [comment]
your going to have to have 2 separate downloads because the files have changed position. we are heading towards a framework that will not be altered in the future.

**Comment by danielkerr** [comment]
ok got ones of my guys working on it now.

**Comment by dmitriyzhuk** [comment]
Sounds good. Count me in. We be glad to help with the process.

**Comment by danielkerr** [comment]
u can start if u like.

**Comment by danielkerr** [comment]
working on the cloud will add this when i have freer time maybe over the next 2 months.

**Comment by Quacky2200** [comment]
@dmitriyzhuk I couldn't agree more. 

I have to develop an extension for this web application and it's a huge pain having to track the differences throughout different versions without any proper documentation to tell you otherwise. The fact that I have to release around 2-3 different versions due to anyone using either v1, v2.2 and v2.3 is rather shocking. These should all be compatible or at least easy to update within the system itself rather than having to waste time developing for each version. I haven't had much of a problem with the version differences in most shopping web applications. 

**If your web application changes this much, DO NOT pass v1 until you have a stable environment available for extending to developers or at least; push the huge changes between major releases (i.e. v2 and v3)**

**Comment by danielkerr** [comment]
And banned.

**Comment by danielkerr** [comment]
And banned.

**Comment by Quacky2200** [comment]
Why are you banning people just because they disagree?

**Comment by kallef110** [comment]
Just put the repository as private, why not do it? Because you know you need the community to collaborate, the problem that not everyone accepts being treated poorly by you @danielkerr.
Change your arrogant way because your project is already getting behind.

**Comment by danielkerr** [comment]
2 more bans

**Comment by OCalternative** [comment]
Just to anyone!

Everyone is invited to brainstorming, support requests and everything else - no bullying here:

https://github.com/OCalternative/opencart-alternative

It seems Opencart is doing everything it can, to shut the project down and move away from open-source.

To remind You some of them:

https://github.com/opencart/opencart/issues/5411#issuecomment-299179658
https://github.com/opencart/opencart/issues/5177#issuecomment-300104240
https://github.com/opencart/opencart/issues/1534#issuecomment-45237879
https://github.com/opencart/opencart/issues/4832#issuecomment-299625788

And these are just only very few of them :(
More can be found by keywords: "wasting time", "dick" or "prick" and "banned", e.g.: 
https://github.com/opencart/opencart/search?q=wasting+time&type=Issues&utf8=%E2%9C%93 

Choose and try out different platforms, which are based on Opencart!

These are my favourites:

* https://github.com/copona/copona
* https://arastta.org
* http://www.abantecart.com

Some older projects, still active:

* https://github.com/opencart-ce/opencart-ce

Or just, another system: 
* http://alternativeto.net/software/opencart/

**Comment by danielkerr** [comment]
@kallef110  you have never helped nor have i ever heard of you!

I know why the people are who help with the project. 

Quacky2200 i have my own reasons for banning people i dont need to explain them to you.

**Comment by kallef110** [comment]
I've helped a lot, and I still help, obviously I have a fake account so I do not risk being banned by you. I like to contribute with opencart, I work with it for over 5 years, unfortunately you do not value your taxpayers. At the end of the day, all the people who complain are trying to help you, hoping that someday you will change your attitude and make Opencart go further. Why not put someone in your place to manage the repository while doing other things? There must be plenty of developers you trust.

**Comment by danielkerr** [comment]
your full of of crap!

why come on here and lie.

**Comment by RaidoDev** [comment]
Guys, please, spend time for developing not arguing....

**Comment by danielkerr** [comment]
i plan to document the library classes using phpdocs and that should be enough. all methods is not required.

**Comment by willfaulds** [comment]
If 1 method was documented to the standard, and desired conventions, I would document other over the next month. I need to familiarise myself with them anyway.

**Comment by danielkerr** [comment]
started here:

https://github.com/opencart/opencart/wiki

im going to close this issue as i will finish the wiki over the next few days.

**Comment by willfaulds** [comment]
Just a note; still no API documentation (literally nothing I can find anyway) which means there's nothing for me to add to. Unfortunately, that makes me nervous to invest time learning/writing so OC won't be the solution this time round for me.
