### ISSUE TITLE
Controller Module not found in vq2-system_storage_modification_system_engine_loader.php

### ISSUE THREAD

**Issue by vipulmadhani** [opencart/opencart#5167]
HI, I just installed d_social_loginlite. After installing that i faced this error.

Fatal error: Class 'Controllermodule' not found in /hermes/bosnaweb26a/b436/ipg.vipulma/exclusivebay.com-redirect/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php on line 28

I am using Opencart 2.1.0.2

Can Anyone help me in this?

**Comment by arnisjuraga** [comment]
Hi!

What is "d_social_loginlite" ?

**Comment by vipulmadhani** [comment]
Its a plugin for introducing social login on site.


https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=18171&filter_search=d%20social


Thanks & regards

Vipul Madhani

Mob: +91 845 185 7474


P.S :- Donate your books at https://goo.gl/CJVd5N


________________________________

**Comment by arnisjuraga** [comment]
Then you should contact plugin develepor and ask for a support. Start with commenting into plugin site. 
As it looks, it's not an Opencat issue :(

**Comment by vipulmadhani** [comment]
It seems this is not a plugin issue. i spoke with the developer and they said that its page is broken. 

Kindly help.

**Comment by danielkerr** [comment]
it ant a issue with the default opencart. post in the forums. not here
