### ISSUE TITLE
[PAYPAL EXPRESS] Error: after clicking on Paypal Express Checkout, system is redirecting to cart page. 

### ISSUE THREAD

**Issue by vipulmadhani** [opencart/opencart#5168]
When I click on paypal express checkout button, system is redirecting me to checkout page itself. Its not navigating to Paypal site. 

Kindly help.

**Comment by jamesallsup** [comment]
Enable "Debug logging" in the settings for PayPal Express, go through the checkout and then check your logs folder. 

If you cannot resolve the error please contact support or use the forum - please do not use GitHub for user related issues.

https://support.opencart.com/hc/en-us/requests/new
https://forum.opencart.com
