### ISSUE TITLE
[GOOGLE SITEMAP] issue. 

### ISSUE THREAD

**Issue by vipulmadhani** [opencart/opencart#5171]
I am trying to access sitemap for my site through this URL.
https://www.pustakmandi.com/index.php?route=feed/google_sitemap

But whenever i try, it says - Page not found.

Kindly help on priority.

**Comment by arnisjuraga** [comment]
Have you installed/enabled and double-checked the path for sitemap? 
It seems to be loading so slow, maybe you have more than 1K products? In that case, it can take too much time to generate for the first time?

**Comment by vipulmadhani** [comment]
I have done that as well. Yes products are a lot and they are increasing daily.


What can be done. Everytime it says page not found.


Thanks & regards

Vipul Madhani

Mob: +91 845 185 7474


P.S :- Donate your books at https://goo.gl/CJVd5N


________________________________

**Comment by arnisjuraga** [comment]
You should request some Opencart dev support, look for a developer. Goole sitemap for large sites is a bit challenge.

**Comment by uksitebuilder** [comment]
Our sitemap extension can handle large sites

It does this by splitting the sitemap into smaller sitemaps

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=2881

**Comment by danielkerr** [comment]
I'll put this on my to-do list.

**Comment by danielkerr** [comment]
your not using the latest version. the url should have extension/feed/google_sitemap as the route.
