### ISSUE TITLE
Create class Product, Client, Address, etc.

### ISSUE THREAD

**Issue by valdeirpsr** [opencart/opencart#5175]
Why not create a class for these options?

It would not be better to work as follows:

```php
/* Register */
$product = new Product();
$product->setName( 'Product Name' );

$description = new ProductDescription();
$description->setTitle( `language_id`, "Title" );
$description->setDescription( `language_id`, "Descrição" );
$product->setDescription( $description );

/* Get */
$product = new Product( `id` );
echo $product->getName() . PHP_EOL;
echo $product->getDescription( `language_id` )
             ->getTitle();

/* ArrayIterator */
$products = new ArrayIterator( $query->rows );
$products->next();
$products->next();
$products->next();

/* Customer */
$customer = new Customer();
$customer->setAddress( new Address() );
$customer->setCustomFields( new CustomFields() );
```

That would be much better than working with arrays.

**Comment by danielkerr** [comment]
Because I don't want to fill OpenCart up with garbage code that will have performance issues. Also that is not the correct to use an objects for inputting data into a db.

**Comment by valdeirpsr** [comment]
Garbage should be work with you.

Another, you might as well use the "model" to take care of the data. (Save, retrieve, delete, update).

The object would only serve for the controllers to work.

It was my mistake to use [ $product = new Product (`id`); ]. But to say that this is losing performance is very stupid.
