### ISSUE TITLE
custom theme template path

### ISSUE THREAD

**Issue by studioenot** [opencart/opencart#5176]
My custom theme did not work (v 2.3.0.2) because due to the wrong path.
Changed /catalog/controller/event/theme.php row 16:

$theme = $this->config->get('config_theme');

Replaced with:
$theme = $this->config->get($this->config->get('config_theme') . "_directory");

now everything is ok

**Comment by danielkerr** [comment]
You set the directory path using the default theme only for compatibility with the old templates. If it's a new one u created then u messed up.
