### ISSUE TITLE
OpenCart orders history tab notification issues

### ISSUE THREAD

**Issue by iwp-nishant** [opencart/opencart#5178]
I am having an issue with my Open Cart, when I want to send a notification to clients from the History tab, I get this message error:

Syntax Error: Unexpected end of JSON input.

**Comment by arnisjuraga** [comment]
Which OC version? Can you give us HTTP response from server (if you can trace it using Chrome Web Developer console .e.g.)?

**Comment by iwp-nishant** [comment]
I am using OpenCart Version 2.0.3.1

**Comment by arnisjuraga** [comment]
Check out this, does it helps? 
https://github.com/opencart/opencart/issues/3124
