### ISSUE TITLE
Newly installed extension is not showing in the modules list

### ISSUE THREAD

**Issue by jimmypinto** [opencart/opencart#5180]
I am a top administrator and the user group has all the permissions checked. I installed Mailchimp Pro but its not showing in the list. When I used the Mailchimp demo's relative path of the module on my store, it says-
"Permission Denied! You do not have permission to access this page, please refer to your system administrator."

**Comment by arnisjuraga** [comment]
Sounds like something wrong with Mailchimp Pro installer or module itself :(
You should contact developer of module. Or any PHP devs for the help.

**Comment by jimmypinto** [comment]
Hi arnisjuraga, Thanks for your response. I contact the module development team.
