### ISSUE TITLE
Default payment gateway stripe?

### ISSUE THREAD

**Issue by zaqueoae** [opencart/opencart#5182]
Hello,
I have used Opencart for years. All this paypal time has always been installed by default. I have discovered stripe and I found it far superior to paypal. I wanted to poponer that the opencart team would support a payment gateway with stripe. I think it would be a very strong competitive advantage over other e-commerce cms.

Greetings and thank you.

**Comment by jamesallsup** [comment]
No.

I have contacted Stripe several times and get the same generic response. Stripe is an excellent gateway but if they are not prepared to have a mutually beneficial relationship with OpenCart then they will not be included. PayPal have a similar product to Stripe and much more products too - something to fit almost any need. In addition, they work with partners closely.

If you prefer Stripe as many others do too, there are several modules for it on the extension store.

Regardless, this is a bug tracker and is not for feedback. If you would like to discuss Stripe with people please use the forum https://forum.opencart.com/
