### ISSUE TITLE
Opencart 2.3.0.2 Not Instaslling

### ISSUE THREAD

**Issue by mrrohanverma** [opencart/opencart#5183]
Dear sir i have just download oc latest version 2.3.0.2 and upload all
files on my server but when i launch my website it is not installing
and only a white page(Blank) page appears. Tell me please what can i
do

**Comment by arnisjuraga** [comment]
Check PHP log files, there can be many reasons for this :( 
Ask log files from hosting company, 
also, check these log files:

`system/storage/logs/error.log`

**Comment by danielkerr** [comment]
your server is miss confgured
