### ISSUE TITLE
error

### ISSUE THREAD

**Issue by waierty** [opencart/opencart#5184]
i have just upgrade to 2.3.0.2
but the wedsite is occurring http error 500
and "Indirect modification of overloaded property ControllerPaymentCod::$data has no effect in /admin/controller/payment/cod.php on line 20" from line 20 to line 100 
please help

**Comment by mrrohanverma** [comment]
this version of open cart is useless in my way you should use oc 2.2.0.0

**Comment by trinkaljuneja** [comment]
this link might help 

[https://forum.opencart.com/viewtopic.php?f=191&t=166012](url)

**Comment by arnisjuraga** [comment]
@trinkaljuneja - link ir "broken", when clicked. Try this: https://forum.opencart.com/viewtopic.php?f=191&t=166012 

but anyway - there are no direct notes for that problem. Can you specify, which fix exaclty to use?

**Comment by pnair39** [comment]
First make a backup of the site your working on:

1) rename the Admin and Catalog folder to oldxxxx.
2) rename the vqmod folder to vqmodold
3) upload 2.3.x.x new Admin and Catalog Folder.

If you are using VQMOD you will have to reinstall and  re-download the compatible 2.3.x.x Extension

Let me know if this works for you. Thanks.

**Comment by arnisjuraga** [comment]
@pnair39 supposed drastic, but a way to go. By renaming folders, you will not loose anything, but the site, of course, will be reverted to the default theme, without modules and so on.
First of all - create backup, 
if you are able - setup temp server and try everything on test. Fire up some CPS, (on Digitalocean.com e.g.) and so on.

**Comment by danielkerr** [comment]
this is very easy to fix just add 	private $error = array(); after class ControllerExtensionPaymentCod extends Controller {
