### ISSUE TITLE
Coupon Issue!

### ISSUE THREAD

**Issue by davodavodavo3** [opencart/opencart#5186]
Add the coupon with parameters Uses Per Coupon = 1 and Uses Per Customer = 1 in the admin paneli.In front-end when two users at same time introduce the same code the process is successful.When order is confirmed by first customer , coupon functionality works fine( row added to cupon_history with customer ID who first confirm the order). And when  the second suctomer confirm his order he erroneously indicates that it has received a discount in his profile orders page.
Opencart Version 2.3.0.2

**Comment by arnisjuraga** [comment]
You mean - if I receive a coupon as a customer, then I can, let's say - register 10 new users, open 1 order for each and leave them on the confirmation page.

Then, one by one, confirm orders - all 10 will get a discount?
Even though, the coupon can be used only once?

**Comment by davodavodavo3** [comment]
Yes! Let's say you have registered 10 members, all of them have added 1 product to cart and confirm  the coupon which is valid only once. After that, they go to confirmation page and confirm order. In the real, only one receives a coupon discount (the one who confirm the order first ). And the other 9 did not receive a discount on their orders but the page Profile->Orders shows that they have received a discount with this coupon.

**Comment by davodavodavo3** [comment]
You understand so that the program leads to customer confusion. He would think that he had received a discount << Here I have on the page, I see that I have a discount >>, but we have seen in the admin panel that he has no discount.

**Comment by danielkerr** [comment]
this should not happen!if coupon has already been used it will return a fraud status!

if not there is a fix pom the master branch

**Comment by davodavodavo3** [comment]
danielkerr I download the master branch of opencart and there is no fix for that issue.
