### ISSUE TITLE
Upgrade from 2.0.0.0 to 2.2.0.0

### ISSUE THREAD

**Issue by pedrodevoto** [opencart/opencart#5187]
I developed a shop in 2.0.0.0 and now, due to a plugin requirement, I have to upgrade to 2.2.0.0. What is the safest way? I tried going directly to 2.2.0.0 but the upgrade script fails. I tried going _"step by step"_ but it also fails. I have some modules configured which I noticed get invalidated/lost and need reinstallation (slideshow, banner, etc). I also use Override Engine, although I don't think it is a problem really. 

Anyone?

**Comment by arnisjuraga** [comment]
oh, bugga ..
IMHO, there is no "safest way". Depends on how much customization/modules you have.

I would try:

Manual hard way with DB migration (have done some. Requires OC DB tables knowledge)
1) Setup fresh 2.2.0.0 (or 2.3.0.2, but depends on modules you use)
2) export DB with categories/products/attributes/orders/customers/ 
3) try to import them (there could be table differences)
4) copy and install modules one by one. See what happens.

Manual, most often used for me:
1) create test site
2) copy DB, Files, enable error/debug log files
3) configure OC, debug all log files (web log, system log, vqmod log, ocmod log) and fix code errors, differences manually.
This, usually, works for me. But requires to read log files, and then fix problems. 

One way or another - it's "hands on" job to do manually.
(you can contact me by mail, may be we can share experience)

**Comment by danielkerr** [comment]
dont for get backup and upgrade on a test site first.

**Comment by pedrodevoto** [comment]
Thank you very much @arnisjuraga for your fast response and your willingness. Luckily for me (maybe not for someone who needs to upgrade and came here to find a solution), I found a way to make the plugin that I needed to use compatible with 2.0.0.0, so I'm sticking with that version for now.
