### ISSUE TITLE
opencart 2.0.1.1 modification refresh error

### ISSUE THREAD

**Issue by AhmedMaherPro** [opencart/opencart#5188]
when click on refresh button i get this errors
Notice: Undefined variable: megamenu in /home/alsulwana/public_html/catalog/view/theme/justcakes/template/common/header.tpl on line 106

Notice: Undefined variable: header_top in /home/alsulwana/public_html/catalog/view/theme/justcakes/template/common/home.tpl on line 2

Notice: Undefined variable: about_shop_description in /home/alsulwana/public_html/catalog/view/theme/justcakes/template/common/home.tpl on line 8

Notice: Undefined variable: footers in /home/alsulwana/public_html/catalog/view/theme/justcakes/template/common/footer.tpl on line 4

Notice: Undefined variable: footers in /home/alsulwana/public_html/catalog/view/theme/justcakes/template/common/footer.tpl on line 138

**Comment by arnisjuraga** [comment]
This looks like a problem in your theme `theme/*justcakes*/template`. Contact Theme developer.
