### ISSUE TITLE
Development recomendations

### ISSUE THREAD

**Issue by wazzzar** [opencart/opencart#5191]
**1** write "**breadcrumbs**" object with **__constructor** wich push home link in private field **$path** as example.
and it contains method "**push**" wich accept 2 parametrs, obviosly that. also **url->link** and **language->get** already in "**breadcrumbs**" object.
and method "**render**" to get html.

**2** copy all language entries into **$data["lang"]**. it save many code lines and no more need to add new line into controller then new line was appended into language file. you just add new entry into language file and use it in template. worries about memory is senselessly - max language file size not length **17kb**

**3** extend "**customer**" object with fields:
	**sex** :int 0-undefined,1-male,2-female
	**country**, **region**(state), **city**, **addres**, **post code** :string
	and methods to get it
	
**4** write method "**generate**" in controller **account/password** and http:get or code:call parameter "**length**"

**5** remove inline **javascript** from templates and takes needed data from **DOM** using **jQuery**.
nobody can forbid to visitor copy **javascript** from **DOM** and replaced data and redefine event handler.

Sorry for my english. I do as I can

**Comment by clearshot** [comment]
Thank you wazzzar.
