### ISSUE TITLE
Coupon issue not fixed!

### ISSUE THREAD

**Issue by davodavodavo3** [opencart/opencart#5197]
for the last opened issue dankier recomend to check out master branch, there was a fix for that issue, but there is not((((
Error still exists, when two different people at the same time in the basket will add a coupon with same code (Uses Per Coupon =1 AND Uses Per Customer = 1) and confirm the order.on their profile it shows that they have received discount for that coupon(((((
Opencart Version 2.3.0.3_rc

**Comment by danielkerr** [comment]
no error is fixed! i suggest you do some searching!
