### ISSUE TITLE
Vulnerability report

### ISSUE THREAD

**Issue by MaorShwartz** [opencart/opencart#5198]
Hi,

We would like to report a vulnerability in OpenCart latest.

Because the information is sensitive - please contact me at maors@beyondsecurity.com

**Comment by jamesallsup** [comment]
Information on how to report a vulnerability can be found in the [README](https://github.com/opencart/opencart/blob/master/README.md#reporting-a-bug-and-security-issues)

**Comment by danielkerr** [comment]
@MaorShwartz another clown acting like james bond with a nonsense Vulnerability

**Comment by MaorShwartz** [comment]
Hi Daniel,

We will go ahead with the disclosure

**Comment by danielkerr** [comment]
james already told me it was bullshit so go ahead!
