### ISSUE TITLE
oc_customer_login table too large

### ISSUE THREAD

**Issue by hardjob** [opencart/opencart#5202]
I was wondering why not delete old records from this table , as it takes too much size ,
i made a backup and try to import it but i got memory and time out error , so i explored the database and found that customer_login table has a lot of records most of them are useless ... i'm i wrong ?

**Comment by danielkerr** [comment]
yes delete the entries

but that table reports when hacker bots are trying to login

**Comment by saeed1000** [comment]
phpmyadmin -->select opencart database --> query tab

`
TRUNCATE TABLE oc_customer_login;

`
press go and then all is done
