### ISSUE TITLE
customer group default error

### ISSUE THREAD

**Issue by falconeri** [opencart/opencart#5203]
when i have multiple customer group, the function `$this->config->get('config_customer_group_id')` did not show corect value. ex: i have customer groups: **default, staff**; i set **default** as customer groups default, then i write `$this->config->get('config_customer_group_id')` in header to check. it is shows **staff** as customer groups.
![screenshot 80](https://cloud.githubusercontent.com/assets/9047407/23012030/c3830a4e-f456-11e6-9688-3e0217ba660d.png)
![screenshot 81 - copy](https://cloud.githubusercontent.com/assets/9047407/23012083/0ae6182c-f457-11e6-870b-92708b65f758.png)
![screenshot 81](https://cloud.githubusercontent.com/assets/9047407/23012085/0dfb3696-f457-11e6-8dbf-44cd150f6d05.png)

"2" is a **staff**

**Comment by JJKalnins** [comment]
Can you explain this in greater detail?

**Comment by arnisjuraga** [comment]
From your printscreen - "2" is not an ID, but `sort_order`, so can it be, your "Default" customer group has ID:2? And that means - `$this->config->get('config_customer_group_id')` - returns "2", and if `Default` group `ID == 2`, then it works fine?

I just tested this on OC master and OC 2.3.0.2 - it works as expected - `$this->config->get('config_customer_group_id')` returns surrent `customer_group_id`
