### ISSUE TITLE
Compatibility issues. One payment plugin from 1 to 2.3

### ISSUE THREAD

**Issue by Boxedsolutions** [opencart/opencart#5204]
It would be great if https://github.com/opencart/opencart/blob/master/upload/admin/controller/extension/extension/payment.php#L100

Someone added a array outside the file loop and saved the extension to the array in the loop. That way its possible to check if the extension is already in the array and continue. 

As I did the compatibility by adding classes to extension/payment and extend the base. 

As a payment plugin developer its a must have to make it possible to achieve compatibility in one single plugin as long as it is possible. 

It works as it is today the only issue is that the payment methods is shown to times.

**Comment by danielkerr** [comment]
this has been changed. the marketplace and extension files are in sperate folders now.

**Comment by Boxedsolutions** [comment]
Marketplace and extension files. 

Can you point me to the commit so I can review the solution. 

If you look att Billmate/Opencart on github so you can see how we have solved all versions in one plugin.
