### ISSUE TITLE
admin username

### ISSUE THREAD

**Issue by skythemes** [opencart/opencart#5205]
opencart 2.3.0.2 error
Undefined variable: username in /admin/view/template/common/column_left.tpl on line 5
Fix
admin/controller/common/column_left.php
Find:

			if ($user_info) {
				$data['firstname'] = $user_info['firstname'];
				$data['lastname'] = $user_info['lastname'];
	
				$data['user_group'] = $user_info['user_group'];
	
				if (is_file(DIR_IMAGE . $user_info['image'])) {
					$data['image'] = $this->model_tool_image->resize($user_info['image'], 45, 45);
				} else {
					$data['image'] = '';
				}
			} else {
				$data['firstname'] = '';
				$data['lastname'] = '';
				$data['user_group'] = '';
				$data['image'] = '';
			}	

Replace

		if ($user_info) {
			$data['firstname'] = $user_info['firstname'];
			$data['lastname'] = $user_info['lastname'];
			$data['username'] = $user_info['username'];

			$data['user_group'] = $user_info['user_group'] ;

			if (is_file(DIR_IMAGE . $user_info['image'])) {
				$data['image'] = $this->model_tool_image->resize($user_info['image'], 45, 45);
			} else {
				$data['image'] = $this->model_tool_image->resize('no_image.png', 45, 45);
			}
		} else {
			        $data['username'] = '';
				$data['firstname'] = '';
				$data['lastname'] = '';
				$data['user_group'] = '';
				$data['image'] = '';
		}

**Comment by lucasjkr** [comment]
https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/column_left.php

Is it me or does the original already have the changes you're suggesting?
