### ISSUE TITLE
store credit bug, used balance to deduct instead of order total

### ISSUE THREAD

**Issue by wuhuw** [opencart/opencart#5207]
catalog/model/extension/total/credit.php

line 9: $credit = min($balance, $total);  => $credit = min($balance, $total['total']);

**Comment by danielkerr** [comment]
the function min it goes for what ever is the lowest amount. the system works!

maybe a better description of the issue!

instead im guessing you dont want to auto deduct total from peoples balance is that correct?

**Comment by danielkerr** [comment]
can not find the code.
