### ISSUE TITLE
typo locallisation

### ISSUE THREAD

**Issue by hauso** [opencart/opencart#5211]
Typo in menu System > Locallisation should be "Localization"

**Comment by Icebox-Studio** [comment]
British English uses "s" whereas American English uses "z". So it's technically not a typo.

**Comment by hauso** [comment]
and double ll ? locaLLisation

**Comment by arnisjuraga** [comment]
Where do you see left `LocaLLisation`? I have searched repo, `text_localisation` has correct translations at the moment everywhere.

**Comment by hauso** [comment]
My fault sorry, probably some eyestrain, I need to stop working overnight ...
