### ISSUE TITLE
shopping cart lost links

### ISSUE THREAD

**Issue by Sillky01** [opencart/opencart#5212]
I am new to shopping cart/ websites although in I am an It engineer so I hope I can with a little assistance work things out  - my web site has the following error - can any one guide me ?

Notice: Error: Could not connect to database domestic in /home/jul1e/public_html/domestic-furniture/system/database/mysql.php on line 11

Notice: Error: No database selected
Error No: 1046
SELECT * FROM dw_store WHERE REPLACE(`url`, 'www.', '') = 'http://david-way.com/domestic-furniture/' in /home/jul1e/public_html/domestic-furniture/system/database/mysql.php on line 50

**Comment by ADDCreative** [comment]
Could be a problem with your config or hosting. Best to ask in the forums.

**Comment by danielkerr** [comment]
Notice: Error: No database selected

is the issue. check the config.php

**Comment by Sillky01** [comment]
Thank you 🙂

On 19 Feb 2017 3:52 am, Daniel Kerr <notifications@github.com> wrote:

Notice: Error: No database selected

is the issue. check the config.php

**Comment by Sillky01** [comment]
Great thank you

On 18 Feb 2017 10:13 pm, ADDCreative <notifications@github.com> wrote:

Could be a problem with your config or hosting. Best to ask in the forums.
