### ISSUE TITLE
OpenCart mail error on mail.php line 170

### ISSUE THREAD

**Issue by Balakrishnakr** [opencart/opencart#5215]
I'm getting this error on my OpenCart site while I trying to register with an email.

Warning: fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/gulfbuyzar/public_html/demo/system/library/mail.php on line 167Warning: fsockopen(): unable to connect to :25 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /home/gulfbuyzar/public_html/demo/system/library/mail.php on line 167
Fatal error: Uncaught exception 'Exception' with message 'Error: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)' in /home/gulfbuyzar/public_html/demo/system/library/mail.php:170 Stack trace: #0 /home/gulfbuyzar/public_html/demo/admin/model/sale/seller.php(429): Mail->send() #1 [internal function]: ModelSaleSeller->approve('179') #2 /home/gulfbuyzar/public_html/demo/system/storage/modification/system/engine/loader.php(150): call_user_func_array(Array, Array) #3 [internal function]: Loader->{closure}(Array) #4 /home/gulfbuyzar/public_html/demo/system/engine/proxy.php(13): call_user_func(Object(Closure), Array) #5 /home/gulfbuyzar/public_html/demo/admin/controller/sale/seller.php(276): Proxy->__call('approve', Array) #6 /home/gulfbuyzar/public_html/demo/admin/controller/sale/seller.php(276): Proxy->approve('179') #7 [internal function]: ControllerSaleSeller->approve() #8 /home/gulfbuyzar/public_html/demo/system/storage/modification/system/engine/action.php(44): call_user_func_array(Array, Array) in /home/gulfbuyzar/public_html/demo/system/library/mail.php on line 170

**Comment by arnisjuraga** [comment]
Double check the server address. Best of all -change it to the IP address. There can be issues on the server with name resolution, 
so change the server name to IP address.

Second - double check the settings again - destination port (is it 25? Or 465)?

**Comment by talledge** [comment]
BEST SOLUTION:

simple go to you setting >>> Mail>> 

In you mail protocol, make sure you select mail rather than smtp
and fill the rest accordingly
