### ISSUE TITLE
opencart is not sending email to customer  Opencart 2.3.02

### ISSUE THREAD

**Issue by okmela** [opencart/opencart#5224]
. Notify to customer > sending to admin.
.Orders sends to admin only. not customer who buys the products.
Anyone wanna help me to get done, Im struggling since a long time.
regards

**Comment by suman0359** [comment]
same problem facing me too from 4 hours

**Comment by pnair39** [comment]
@okmela Is this an upgraded opencart or new fresh install. And is this on a server or xampp or mamp?

**Comment by arnisjuraga** [comment]
@okmela please, contact me. I believe, there is some simple explanation
