### ISSUE TITLE
The new EVENT system needs sorting!

### ISSUE THREAD

**Issue by dmitriyzhuk** [opencart/opencart#5225]
Hi

**CASE 1 - the first event in VIEW "BEFORE" stage.**
Here is the case. We have implemented an Event that adds twig support. A simple method that looks for the twig file and compiles it instead of the tpl. 

obviously it has to run before the default tpl template is loaded - otherwise the view method will throw an error saying there is no TPL file, because there is a .twig file instead. 

If we run it before the default template compiler, thats fine. it generates an output.The output is not empty and so the default is not running. 

but then we noticed that some of the events that add more to the $data are missing. simply because the next event is added after our. So we can't generate $output on the step "BEFORE", because we might not have all the $data.

**CASE 2 - the last event in the VIEW "AFTER" stage.**
so we thought ok - we will move this event to AFTER and let all the events add what they need to the $data on the BEFORE stage.

AND AGAIN we added the compiler after third-party event that was altering the $output. But since our event was the last event - there was NO $output to alter - and the third-party event displayed an error again. 

**SOLUTION**
Obviously to avoid this situation we are forced to run the method in between by adding it via OCMOD. but what we really want is to have SORTING in events. What if we could set the sorting for our event to run the last in the BEFORE stage or the first in the AFTER Stage. 

-1 - runs fist
0 - no sorting (middle)
+1 - runs last

It may not be the best solution - but it could reduce the rick of future conflicts - thus making it more reliable. We truly believe in events and would love to see them become a standard for any extension.

**Comment by danielkerr** [comment]
seems to be ok for me. i can get the output to work no problem.

**Comment by danielkerr** [comment]
so how should events work?

should output be there?

is it better to override the default method being called if there is already out put?

what about a continue argument?

so it will become 

&$route, &$args, &$output, &$continue

**Comment by mhcwebdesign** [comment]
I am not sure why the view before needs the output argument. The 'view before' events should act more like a series of preRender calls, for modifying or adding the variables, and for modifying the template file. These 'view before' events should not rely on a particular order. Any 3rd party extension using events is not aware of other possibly installed 3rd party extensions using their own events. All 3rd party extensions should have a chance for their events to be executed, none of the 'view before' events should render the template, the latter has to be done by the template engine.

**Comment by dmitriyzhuk** [comment]
to danielkerr  and  mhcwebdesign -  I agree that before - is preRender - edit DATA, after - is postRender - edit OUTPUT. And in most cases this is enough. But what if we want to change the template engine just for several files, like twig and not run tpl... OCMOD again?

Personally I enjoy events and want them to become a standard. 

First lets list the causes of issues and conflicts up till now:
1. If one event prevents another from running, like returning an output - conflict. 
2. If one event relies on another event - and the order is changing from the way events are added to the database - conflict. 


Solution
1. The first VIEW before can alter an output. Like i said, we may have a need for that and their is nothing bad in creating your own output to skip the tpl render.  But it must not RETURN an output since this will stop the function - so altering output is fine, returning $return is not good. It should continue, skipping the render of tpl step and going directly to the VIEW after events, and running those events.

2. at the moment we have basically 2 sorting orders: BEFORE and AFTER, which gives us 100% confidence that one will be before the other. in many cases (90%) this is enough. but for those 9% of the cases we can add sort_order. of course there will be 1% chance that someone will brake this. but at least it allows a developer to have a 99% confidence that his event will run in before  (sort_order: -1) most of events run in the VIEW after for example. 

3. and if we have sorting, it allows us to check for an existing event and be sure that our event takes place before or after it by altering the sort value. 

In most cases this will not be necessary - right now the event system is a great tool. What I am proposing is to make it a standard by focusing on those missing pieces. If we can come up with a more simpler solution - I am for it.

Thanks!
The Dreamvention team

**Comment by danielkerr** [comment]
do 
function (&$route) {

$route = 'override/theme';

**Comment by mhcwebdesign** [comment]
To  dmitriyzhuk:

Daniel is right. I have done it that way in several Opencart-based projects using the view-before event: 

- Copy the template into a cache
- Modify the cached template file
- Change the route to point that new template location

It's pretty similar to what I'd do when using the preRender in the Override Engine.

You need to rethink your strategy. No event should rely on another one. Nor should an event change a core OpenCart template type (e.g. from '.twig' to '.php').

To Daniel:

A view-before event should not be allowed to create a rendered output. It would prevent the template engine from doing its job, and it would prevent view-after events from being executed.

However, we may need a proper mechanism to have individual non-core template files from 3rd party extensions for rendering them in e.g. the php instead of twig template engine.

**Comment by dmitriyzhuk** [comment]
1. Guys, as far as I understand you can not touch the $route at all on the VIEW-BEFORE - or you will kill all the VIEW AFTER EVENTS that are connected to that $route, unless you want to switch to other $route events

2. Plus, as you know - this event 
'view/*/before'                         => 'event/theme',
which is set in the config file, alters the $route from this

product/product

to

default/template/product/product

so you will have to do that too or again - conflict.

they rely  on the exact $route - altering it to avoid tpl rendering will cause new level of conflicts.

**Comment by mhcwebdesign** [comment]
@dmitriyzhuk: Good point about the view/*/after events not being triggered because of a changed route. The Loader::view method should really be something like this:

```
	public function view($route, $data = array()) {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route);
		
		// save the original route, we need it later for the view/*/after events
		$original_route = $route;
		
		// Trigger the pre events
		$result = $this->registry->get('event')->trigger('view/' . $route . '/before', array(&$route, &$data));
		
		if ($result) {
			return $result;
		}
		
		$template = new Template($this->registry->get('config')->get('template_engine'));
		
		foreach ($data as $key => $value) {
			$template->set($key, $value);
		}
	
		$output = $template->render($route);
		
		// Trigger the post events (using the original route, to make sure the intended events get triggered)
		$result = $this->registry->get('event')->trigger('view/' . $original_route . '/after', array(&$route, &$data, &$output));
		
		if ($result) {
			return $result;
		}
		
		return $output;
	}
```

**Comment by danielkerr** [comment]
original_route maybe should be done in event maybe

**Comment by dmitriyzhuk** [comment]
ok, i had this idea, and to be frank - its more logical to me at first.

the only thing is what if you actually need to see the specific theme? what if you create an event that needs to run only for one of the themes and not the other. 

if you have multistore with different themes, and you have this wildcard that runs the event for all the themes ... well conflicts will come. having a specific route and the ability to add or remove wildcards is a more stable approach.

so having an original_route is a good option, but with the modified path that holds information about the theme folder.

**Comment by mhcwebdesign** [comment]
@Daniel: It is important, as pointed out by dmitriyzhuk, that the **view/*/after** events are triggered as expected. E.g. if the original route was 'product/product' then it should trigger the **view/product/product/after** events, and not something like **view/default/template/product/product/after**.

**Comment by danielkerr** [comment]
what about instead of &$route, &$args, &$output, &$continue

change to just

&$event

then could do 

event->getRoute()

event->setRoute()

or event->route = 

event->continue()

event->skip()

**Comment by danielkerr** [comment]
what about if there is a return we could set it to the new route.

return 'account/override/register'

if ($new_route) {
  changes the default call

  $route = $new_route;
} 
	
			$template = new Template($this->registry->get('config')->get('template_engine'));
			
			foreach ($data as $key => $value) {
				$template->set($key, $value);
			}
		
			$output = $template->render($route);

**Comment by danielkerr** [comment]
ok any one know the chain of command pattern?

if we could 

$events = array_merge($events_before, $default, $events_after);

foreach ($events as $event) {
			$event->execute();
		}

**Comment by danielkerr** [comment]
ok i see the issue with the template calling view/default/template/product/product/after

**Comment by dmitriyzhuk** [comment]
Sounds good. In this case the template call, if unsuccessful, should be ignored and a next event can continue till the end of the cycle.

also it would be a good option to be able to not only set before and after but also the middle (default) stage for an event 

before - modifies data
default - creates output
after - modifies output

then basically we have a solution to all the cases i can think of.

**Comment by mhcwebdesign** [comment]
@dmitriyzhuk: 

The view/*/before event needs to be able to do:
- modify the data
- modify the template file using a cached copy
- it should not create a rendered output

The view/*/after event needs to be able to do this:
- further modify the rendered output

Also, we need a mechanism to use a different template rendering engine (e.g. PHP instead if TWIG) for individual templates from 3rd party extensions. Perhaps the rendering logic should first check the template file type ('.tpl', '.twig', '.smarty' etc) and then select the rendering engine adapter accordingly.

**Comment by dmitriyzhuk** [comment]
i would advise you to remove as much logic as possible and shift it to events. if someone wants to use smarty, let them implement an event that renders smarty - etc. the less logic the core system has, the easier it is for you guys to maintain it and for us to extend it.

**Comment by danielkerr** [comment]
What about if out put needs to be put out before to override the the
default action? Such as caching

**Comment by dmitriyzhuk** [comment]
That is a good point. if you put the caching as an event on before, we end up missing some of the data, from the events that go after your caching event... again back to sorting...

**Comment by mhcwebdesign** [comment]
That's why I think the view/*/event/before should NOT be allowed to generate an output in the first place! It should only be allowed to:
- modify the data
- modify the template file
Therefore, the triggering of the view/*/event/before events should look like this only:
```
		// Trigger the pre events
		$result = $this->registry->get('event')->trigger('view/' . $route . '/before', array(&$route, &$data));
```
and not like this:
```
		// Trigger the pre events
		$result = $this->registry->get('event')->trigger('view/' . $route . '/before', array(&$route, &$data, &$output));
```

**Comment by danielkerr** [comment]
yes i will add. just updating the order editor. ok think i have solved a big issue loads of people complaining about.

**Comment by danielkerr** [comment]
ok added sorting

**Comment by danielkerr** [comment]
ok reopened because i need some opinions.

**Comment by mhcwebdesign** [comment]
As I said before, the **view/*/before** events need a way to modify the template, in addition to modifying or adding variables. But they should not do the rendering, the latter should only be done in the subsequent **$template->render($route)** call. Hence, there is no need for the view/*/before events to have the **output** argument. See https://github.com/opencart/opencart/issues/5225#issuecomment-286877707 for more details.

**Comment by danielkerr** [comment]
i think there is no need for the checking if the file is php or twig because in the future we will just be using twig. there are many advantages of twig of php.

**Comment by danielkerr** [comment]
ok so what about doing this for the controller

`	
	public function controller($route, $data = array()) {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route);
		
		$action = new Action($route);
		
		// Trigger the pre events
		$result = $this->registry->get('event')->trigger('controller/' . $route . '/before', array($route, &$data));
		
		if ($result instanceof Action) {
			$action = $result;
		}
		
		$output = $action->execute($this->registry, array(&$data));
			
		// Trigger the post events
		$result = $this->registry->get('event')->trigger('controller/' . $route . '/after', array($route, &$data, &$output));
		
		if ($result instanceof Action) {
			$action = $result;
		}

		return $output;
	}`

**Comment by mhcwebdesign** [comment]
@Daniel, I am not sure what this will accomplish. 

The important bit is that the **view/*/before** events can:
- modify or add to the $data
- modify the template (route gets changed to point to a modified cached template file)

And that the **view/*/after** events can be triggered via the original route.

For example, this should perfectly do it:

```
	public function view($route, $data = array()) {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route);
		
		// save the original route, we need it later for triggering the view/*/after events
		$original_route = $route;
		
		// Trigger the pre events
		$result = $this->registry->get('event')->trigger('view/' . $route . '/before', array(&$route, &$data));
		
		if ($result) {
			return $result;
		}
		
		// render the template
		$template = new Template($this->registry->get('config')->get('template_engine'));
		foreach ($data as $key => $value) {
			$template->set($key, $value);
		}
		$output = $template->render($route);
		
		// Trigger the post events (using the original route, to make sure the intended events get triggered)
		$result = $this->registry->get('event')->trigger('view/' . $original_route . '/after', array(&$route, &$data, &$output));
		
		if ($result) {
			return $result;
		}
		
		return $output;
	}
```

**Comment by danielkerr** [comment]
looks liek i need to add some sort of dependency container for for the load for model and views

**Comment by danielkerr** [comment]
we still need to stop the default call if needed. 

i dont like using if (!$output) {

**Comment by danielkerr** [comment]
maybe

if ($route) {

**Comment by danielkerr** [comment]
also how to do page caching to send out the output without calling the default action.

**Comment by danielkerr** [comment]
ok forget it. i will put it back and use the new method.

**Comment by danielkerr** [comment]
ok what about 

```
	public function controller($route, $data = array()) {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route);
		
		$trigger = $route;
		
		// Trigger the pre events
		$result = $this->registry->get('event')->trigger('controller/' . $trigger . '/before', array(&$route, &$data));
		
		if (!$result) {
			$action = new Action($route);
			$output = $action->execute($this->registry, array(&$data));
		}
		
		// Trigger the post events
		$result = $this->registry->get('event')->trigger('controller/' . $trigger . '/after', array(&$route, &$data, &$output));
		
		if ($result) {
			$output = $result;
		}

		return $output;
	}
```

**Comment by mhcwebdesign** [comment]
I think your suggested **Loader::controller** method makes sense, and makes sure that the **controller/*/after**  events always have a chance to be triggered, too, now.

The same should be true with the **view/*/after** events. Perhaps change the **Loader::view** method in a similar way?

```
	public function view($route, $data = array()) {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route);
		
		$trigger = $route;
		
		// Trigger the pre events
		$result = $this->registry->get('event')->trigger('view/' . $trigger . '/before', array(&$route, &$data));
		
		if ($result) {
			$output = $result;
		} else {
			// render the template
			$template = new Template($this->registry->get('config')->get('template_engine'));
			foreach ($data as $key => $value) {
				$template->set($key, $value);
			}
			$output = $template->render($route);
		}
		
		// Trigger the post events
		$result = $this->registry->get('event')->trigger('view/' . $trigger . '/after', array(&$route, &$data, &$output));
		
		if ($result) {
			return $result;
		}
		
		return $output;
	}
```

That just leaves one issue: If any of the **controller/*/before** and **view/*/before** event handlers returns a result, then the remaining **controller/*/before** and **view/*/before** events won't get processed. That means, if there a multiple 3rd party extensions using the before-events for modifying OpenCart core behaviour then some may miss out because a previous before-handler returned a non-null result.

To prevent this problem, I always return null in my **view/*/before** event handlers. And if a **view/*/before** event needs to change the template, it can do that in a cached file and change the route accordingly to point to it. For example:

- product/product   
(original route)

- default/template/product/product 
(route after the catalog/controller/event/theme.php was called)

- ../../../system/cache/view/default/template/product/product
(route after another 3rd party event handler changed the template and wrote it to the system/cache/view/default/default/template/product/product.twig file)

**Comment by danielkerr** [comment]
im adding a priority to the event system. i have solved the load class part.

maybe i just need some minor changes to the model callback

```
<?php
final class Loader {
	protected $registry;

	public function __construct($registry) {
		$this->registry = $registry;
	}
	
	public function controller($route, $data = array()) {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route);
		
		$trigger = $route;
		
		// Trigger the pre events
		$result = $this->registry->get('event')->trigger('controller/' . $trigger . '/before', array($route, &$data));
		
		// Make sure its only the last event that returns an output if required.
		if ($result) {
			$output = $result;
		} else {
			$action = new Action($route);
			$output = $action->execute($this->registry, array(&$data));			
		}
		
		// Trigger the post events
		$result = $this->registry->get('event')->trigger('controller/' . $trigger . '/after', array($route, &$data, &$output));
		
		if ($result) {
			$output = $result;
		}

		return $output;
	}
	
	public function model($route) {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route);
		
		if (!$this->registry->has('model_' . str_replace('/', '_', $route))) {
			$file  = DIR_APPLICATION . 'model/' . $route . '.php';
			$class = 'Model' . preg_replace('/[^a-zA-Z0-9]/', '', $route);
			
			if (is_file($file)) {
				include_once($file);
	
				$proxy = new Proxy();
				
				// Overriding models is a little harder so we have to use PHP's magic methods
				// In future version we can use runkit
				foreach (get_class_methods($class) as $method) {
					$proxy->{$method} = $this->callback($this->registry, $route . '/' . $method);
				}
				
				$this->registry->set('model_' . str_replace('/', '_', (string)$route), $proxy);
			} else {
				throw new \Exception('Error: Could not load model ' . $route . '!');
			}
		}
	}

	public function view($route, $data = array()) {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route);
		
		$trigger = $route;
		
		// Trigger the pre events
		$result = $this->registry->get('event')->trigger('view/' . $trigger . '/before', array(&$route, &$data));
		
	//	echo $route;
		
		// Make sure its only the last event that returns an output if required.
		if ($result) {
			$output = $result;
		} else {
			$template = new Template($this->registry->get('config')->get('template_engine'));
			
			foreach ($data as $key => $value) {
				$template->set($key, $value);
			}
		
			$output = $template->render($route);		
		}
		
		// Trigger the post events
		$result = $this->registry->get('event')->trigger('view/' . $trigger . '/after', array(&$route, &$data, &$output));
		
		if ($result) {
			$output = $result;
		}
		
		return $output;
	}

	public function library($route) {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route);
			
		$file = DIR_SYSTEM . 'library/' . $route . '.php';
		$class = str_replace('/', '\\', $route);

		if (is_file($file)) {
			include_once($file);

			$this->registry->set(basename($route), new $class($this->registry));
		} else {
			throw new \Exception('Error: Could not load library ' . $route . '!');
		}
	}
	
	public function helper($route) {
		$file = DIR_SYSTEM . 'helper/' . preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route) . '.php';

		if (is_file($file)) {
			include_once($file);
		} else {
			throw new \Exception('Error: Could not load helper ' . $route . '!');
		}
	}
	
	public function config($route) {
		$this->registry->get('event')->trigger('config/' . $route . '/before', array(&$route));
		
		$this->registry->get('config')->load($route);
		
		$this->registry->get('event')->trigger('config/' . $route . '/after', array(&$route));
	}

	public function language($route) {
		$result = $this->registry->get('event')->trigger('language/' . $route . '/before', array(&$route, &$output));
		
		if ($result) {
			$output = $result;
		}
		
		$output = $this->registry->get('language')->load($route);
		
		$this->registry->get('event')->trigger('language/' . $route . '/after', array(&$route, &$output));
		
		return $output;
	}
	
	protected function callback($registry, $route) {
		return function($args) use($registry, $route) {
			static $model;
			
			$route = preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route);
			
			$trigger = $route;
			
			// Trigger the pre events
			$result = $registry->get('event')->trigger('model/' . $trigger . '/before', array($route, &$args));
			
			if ($result) {
				$output = $result;
			} else {
				$file = DIR_APPLICATION . 'model/' .  substr($route, 0, strrpos($route, '/')) . '.php';
				$class = 'Model' . preg_replace('/[^a-zA-Z0-9]/', '', substr($route, 0, strrpos($route, '/')));
				
				// Store the model object
				if (!isset($model[substr($route, 0, strrpos($route, '/'))]) && is_file($file)) {
					include_once($file);
				
					$model[$route] = new $class($registry);
				} else {
					throw new \Exception('Error: Could not load model ' . substr($route, 0, strrpos($route, '/')) . '!');
				}
				
				$method = substr($route, strrpos($route, '/') + 1);
				
				$callable = array($model[$route], $method);
	
				if (is_callable($callable)) {
					$output = call_user_func_array($callable, $args);
				} else {
					throw new \Exception('Error: Could not call model/' . $route . '!');
				}					
			}
			
			// Trigger the post events
			$result = $registry->get('event')->trigger('model/' . $trigger . '/after', array($route, &$args, &$output));
			
			if ($result) {
				$output = $result;
			}
						
			return $output;
		};
	}	
}
```

**Comment by mhcwebdesign** [comment]
I think that looks quite good now. 

As regards Proxy versus runkit: Have you considered using a decorator design pattern instead? You could easily wrap up any Model instance into a decorator class and then implement the triggering of before and after events, like in this example:

```
<?php
class ModelDecorator {

	protected $object;
	protected $route;


	public function __construct( $object, $route ) {
		$this->object = $object; // model instance
		$this->route = $route;   // route of the class, e.g. 'catalog/product'
	}


	public function __get( $key ) {
		return $this->object->__get( $key );
	}


	public function __set( $key, $val ) {
		$this->object->__set( $key, $val );
	}


	public function __call( $method, $args ) {
	
		// make sure it's a callable method
		if (!is_callable(array($this->object, $method))) {
			throw new \Exception("Error: Unable to call public method '$method' in class '" . get_class($this->object) . "'");
			exit;
		}

		$trigger = $this->route.'/'.$method;

		// trigger the pre-events
		$result = $this->event->trigger('model/'.$trigger.'/before', array(&$route, &$args));

		if ($result) {
			$output = $result;
		} else {
			// call the method
			$output = call_user_func_array(array($this->object, $method), $args);
		}

		// trigger the post-events
		$result = $this->event->trigger('model/'.$trigger.'/after', array(&$route, &$args, &$output));
		if ($result) {
			$output = $result;
		}
		
		return $output;
	}
}
```
