### ISSUE TITLE
installer needs to make sure php-xml module is installed

### ISSUE THREAD

**Issue by miracleman** [opencart/opencart#5226]
I installed a fresh opencart 2.3.0.2 everything wents fine until I clicked on extensions > modification > refresh then I got an error. solution I installed php7.0-xml

php 7
ubuntu 16.04

**Comment by miracleman** [comment]
don't know if this is a module since php7 but it seems more people have this issue so it would be nice if the installer could check this prerequisite.

https://www.google.de/search?client=ubuntu&channel=fs&q=Fatal+error%3A+Class+%27DOMDocument%27+not+found+opencart&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=BUyzWMSSEO6A8QeItoKwDg

**Comment by miracleman** [comment]
don't know if this is a module since php7 but it seems more people have this issue so it would be nice if the installer could check this prerequisite.

https://www.google.de/search?client=ubuntu&channel=fs&q=Fatal+error%3A+Class+%27DOMDocument%27+not+found+opencart&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=BUyzWMSSEO6A8QeItoKwDg

**Comment by danielkerr** [comment]
domdocument is pretty much default on any ost. if its not iinstalled contact ur host or change them
