### ISSUE TITLE
Additional Alert Mail opencart 2.3.0.2 does not send email (Setting.php and Setting.tpl) ??? 

### ISSUE THREAD

**Issue by pnair39** [opencart/opencart#5228]
https://www.quora.com/How-do-I-fix-additional-alert-email-field-issue-in-Opencart-2-3-0-2
https://www.knowband.com/blog/opencart-tutorials/additional-alert-email-field-issue-opencart-v2-3-0-2/?utm_source=quora&utm_medium=opencart&utm_term=blog-post&utm_campaign=participation

There are two links above that shows fixing part of the issue, however the alert email does not go thru to my "**Additional Alert Mail**". If I send an email from Marketing>Mail to my test customer account the primary email will always go thru. The above fixes do not resolve this issue, anyone point me to the fix/updated file,

 I see a closed #4850, however does not fix this issue.  Thanks

**Comment by pnair39** [comment]
@arnisjuraga

any suggestions?

**Comment by arnisjuraga** [comment]
I will review this in few days, ok.

**Comment by pnair39** [comment]
@danielkerr not sure why this was closed without explanation.

**Comment by danielkerr** [comment]
works for many other people. also recently updated the the dev bracnh code and tested it. so i know its working

**Comment by pnair39** [comment]
@danielkerr , Correction I made an error, the additional email alerts were for reviews and orders and does not work for Marketing, can you point me at the files that affect the sending of alert mails. Maybe all the files did not copy over during ftp upload. Thanks.

**Comment by elalemanyo** [comment]
I am using the last release (2.3.0.2) and opencart is sending emails just to the shop email. I add an extra email but no email is being sent. What files did dev branch changed?
I am already using a patch to make possible to even save the extra email mail alert:

```
<file path="admin/view/template/setting/setting.tpl">
    <operation>
        <search position="replace"><![CDATA[config_mail_alert_email]]></search>
        <add><![CDATA[config_alert_email]]></add>
    </operation>
</file>
```

I have to say that my opencart was before 1.5.5.1 and I did an upgrade, maybe have something to do?
