### ISSUE TITLE
Function Request on Registeration

### ISSUE THREAD

**Issue by CokkocZateki** [opencart/opencart#5231]
Hello.

Is it possible to have a person register without having to add telephone numbers and addresses.

My site is intended to work with everything happening virtually and no items need to be delivered except an email address.

Thanks

**Comment by pnair39** [comment]
Try this extension below.

https://www.opencart.com/index.php?route=marketplace/extension/info&member_token=mXOJu14TMLRZZkllw9uP8BeKbhsKysyw&extension_id=20225&filter_license=free&filter_download_id=47

**Comment by danielkerr** [comment]
Thinking of this as well

**Comment by cartbinder** [comment]
one more free extension added by us:

**Comment by CokkocZateki** [comment]
thanks for the info. i tried @cartbinder and when i try to upload i get `Could not upload file /var/www/opencart/upload/system/storage/upload/temp-xzS2CFTgCVeSg3VSuDekfNmywZ1vA5Qj/upload/catalog/language/en-gb/module/registerfree.php

any ideas`

**Comment by CokkocZateki** [comment]
and since then my register function is spitting out error 500 script `'/var/www/opencart/index.php' not found or unable to stat`

**Comment by CokkocZateki** [comment]
perfect this worked well :)

**Comment by CokkocZateki** [comment]
for some reason this has become paidware
now i cant remove the address and phone number.
Anyone able to help me

**Comment by webcorvo** [comment]
First Uninstall the extension.

If you want register without having to add telephone numbers and addresses  Address 1 and Address 2

you must go to :

 **catalog\view\theme\default\template\account** 

First make a bakup of the folder **account** 

Then open the folder **account** and repalce with this new files that i send you Register.zip.
account.tpl
edit.tpl
register.tpl

After register in the admin backoffice the Customer will have on Telephone field the value 123.
The address filed will be in blank.

I hide the link **Modify your address book entries** from my account in the store.

I will work ;o)
If you need more help just say ;o)

[Register.zip](https://github.com/opencart/opencart/files/974398/Register.zip)

**Comment by danielkerr** [comment]
i already removed the requirement for address details. i think telephone is required

**Comment by webcorvo** [comment]
i @danielkerr i agree with you

**Comment by osworx** [comment]
> i think telephone is required
Not within the EC/EU (because falls under privacy).
And if, it must be defined/written in the imprint (if for example the order process may need it or depends on it).
