### ISSUE TITLE
Replacement for OwlSlider

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#5236]
It seems, that OWLslider is 'dead' 

http://owlgraphic.com/owlcarousel/
http://divetv.ops.labs.vu.nl/css/demos/one.html

so it should be replaced in the default theme to something, Just choose one.

**Comment by danijelGombac** [comment]
I like 

https://github.com/bqworks/slider-pro

is modular and has lot of option.

**Comment by stefanhuber** [comment]
Please do us all a favour and go with swiper, if anything is changed: http://idangero.us/swiper

**Comment by samchen945** [comment]
owlcarousel v1.x is dead. but it has v2.0, https://github.com/OwlCarousel2/OwlCarousel2

**Comment by arnisjuraga** [comment]
You are right! 
I have checked out, but it seems OWL still has more unresolved bugs, if compared with alternatives :(

**Comment by uchsarath** [comment]
I think Slick Carousel could replace OwlCarousel, http://kenwheeler.github.io/slick/
I also like Swiper, that's nice for main slider

**Comment by nasserman** [comment]
http://idangero.us/swiper is very very handy and nice, i will use it to create new slider for my store ( hope publish it on the market for free)
