### ISSUE TITLE
Please improve the marketplace for buyers (bugs/ideas for improvement)

### ISSUE THREAD

**Issue by VistaXP** [opencart/opencart#5237]
Not sure if Daniel will read this, but here goes. I love the new filters, but there's a few things that make it difficult for buyers to search.

1. Please put back the # of comments and sales each extension has in the marketplace page. This gives me a better idea of popularity. Showing just the # of reviews doesn't help me much when most only show just 1 or 0 reviews.

2. Star ratings on main search page are white and should be blue. Also, why does the white star rating say 4 stars, but when you visit the extension page, it 5 stars?

3.  How do I even rate an extension? I don't have an option to rate.

4. Feature request: Wishlist or Favorite an extension!

Thank you! I hope this gets looked in to.

**Comment by iSaulius** [comment]
I agree!

**Comment by danielkerr** [comment]
yes will do but no time until the cloud is launched.

**Comment by danielkerr** [comment]
Most of the code is done and ready i just need time for testing.

**Comment by VistaXP** [comment]
Great! Can't wait to try it out. Thank you Daniel

**Comment by danielkerr** [comment]
ok done
