### ISSUE TITLE
SSL and the Admin-Page not showing design

### ISSUE THREAD

**Issue by Loggan08** [opencart/opencart#5240]
Everything is formatted without design, store looks OK, but defaults to the Install directory even after deleting the Install folder.

Getting Mixed Content errors with the admin page, my page is served over SSL,

**Comment by lucasjkr** [comment]
You're accessing your admin console through SSL, but your servers admin/config.php file has the wrong values in it.

Login with ssh, backup your admin/config.php file, and then and edit the original.

You'll see two lines that start as follows (should be lines 7 and 8):

define('HTTPS_SERVER', 'http://yourserver/admin/');
define('HTTPS_CATALOG', 'http://yourserver/');

Change the method for each to http**s**://



That is if I'm understanding your problem correctly and your admin page looks like this:

<img width="328" alt="screen shot 2017-03-04 at 11 57 10 am" src="https://cloud.githubusercontent.com/assets/4703516/23580606/d6d11054-00d2-11e7-8df1-376cb8d4e9c3.png">

**Comment by Loggan08** [comment]
That's right, thx

**Comment by lucasjkr** [comment]
Happy to help. Please close this issue if its been solved.  :)
