### ISSUE TITLE
Checkout Problem 2.0.2 JSON Error

### ISSUE THREAD

**Issue by Ashiku67** [opencart/opencart#5241]
When checkout, showing json error.

**Comment by arnisjuraga** [comment]
Please, give more information on it - error, used payment method, used shipping method,
 "when" exactly in checkout method?

**Comment by Ashiku67** [comment]
http://forum.opencart.com/download/file.php?id=31564&sid=353d36db20692d2bc52e408ac2bf3f03 
please see this screenshot.

**Comment by arnisjuraga** [comment]
You don't have "to:" email address for that customer/order?

![image](https://cloud.githubusercontent.com/assets/2185289/23609069/ee9fa012-0274-11e7-82fb-58fe84e845c5.png)

**Comment by Ashiku67** [comment]
have, http://obakshop.com/ this is the site link. please can you try.

**Comment by arnisjuraga** [comment]
Ok, this looks like Your theme specific problem, because Error comes from OC source code `mail.php`  - it does not receive Email-TO address, but that IS posted to OC in your theme, but this definitely is a problem with your Theme. Please, close this issue. Pm me if you need more help.

**Comment by Ashiku67** [comment]
but theme developer told me it's opencart problem.

**Comment by Ashiku67** [comment]
when i checkout as a new register, then show this problem.

**Comment by arnisjuraga** [comment]
Can you switch to Default theme and try then?

**Comment by Ashiku67** [comment]
I had try opencart default theme, same problem. So I need your help and sorry for late reply because I was sick.

**Comment by Ashiku67** [comment]
It's not a theme problem, It's opencart bug.

**Comment by arnisjuraga** [comment]
You can't know. Me neither. :)

See, when you try to register an account, data from Checkout cart is posted to your themes route. 
Have you really tried to enable default theme? In that case, is this route the same, or then data is posted to "checkout/" controller?

![image](https://cloud.githubusercontent.com/assets/2185289/23800210/1896c7f0-05b4-11e7-96bf-33cdd2c88338.png)

You should seek for some OC developer support, or make a test site with 1:1 code with a default theme. Otherwise nobody can help :(

**Comment by Ashiku67** [comment]
okay, thanks a lot and last I've a question. If I share this problem with journal support, will be they support me?

**Comment by Ashiku67** [comment]
and this is the default theme problem.
![2017-03-10](https://cloud.githubusercontent.com/assets/26180938/23800656/6f4e3362-05d7-11e7-9f4b-4ee407fe831d.png)

**Comment by arnisjuraga** [comment]
ok, fine, just one last thing - can you check system settings for an Admin e-mail addresses?
Anyway - for some reason `/system/library/mail.php` receives an EMPTY e-mail address. This must be debugged on your server :(

**Comment by danielkerr** [comment]
It's an email incorrect settiings

**Comment by Ashiku67** [comment]
#arnisjuraga yes admin email is correct. and if is it server problem, then they maybe help me for solving. right?

**Comment by Ashiku67** [comment]
#danielkerr yes, email setting problem. but i'm not able solve this problem. :( 

** if anyone have need dashboard access or mail.php file i'll upload here or give access on dashboard for solving my problem.

**Comment by danielkerr** [comment]
so its not a issue that should be posted here as this is for development of opencart not your ask a support question!
