### ISSUE TITLE
Fatal Error After Payment Authorization From PayPal Express

### ISSUE THREAD

**Issue by EggcellentMessages** [opencart/opencart#5242]
I have researched this fatal error and also shared with hosting company.  I also posted on OpenCart forum and they recommended I come here because they believe it's a coding error.  After authorizing payment for item with PayPal Express, it is set up to come back to my site to hit a button to commit to purchase.  Once you do that, a white screen shows up with this code:

Fatal error: Uncaught Error: Call to a member function check() on null in /home/eggcelle/public_html/catalog/model/checkout/order.php:267 Stack trace: #0 /home/eggcelle/public_html/system/storage/modification/system/engine/loader.php(178): ModelCheckoutOrder->addOrderHistory(15, '5') #1 /home/eggcelle/public_html/system/engine/proxy.php(25): Loader->{closure}(Array, Array) #2 /home/eggcelle/public_html/catalog/controller/extension/payment/pp_express.php(1430): Proxy->__call('addOrderHistory', Array) #3 /home/eggcelle/public_html/system/storage/modification/system/engine/action.php(51): ControllerExtensionPaymentPPExpress->checkoutReturn() #4 /home/eggcelle/public_html/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #5 /home/eggcelle/public_html/system/storage/modification/system/engine/action.php(51): ControllerStartupRouter->index() #6 /home/eggcelle/public_html/system/engine/front.php(34): Action->execute(Object(Registry)) #7 /home/eggcelle/public_html/system/engine/front.php(29): Front->exe in /home/eggcelle/public_html/catalog/model/checkout/order.php on line 267

Can anyone please tell me what is going on?  I am not a programmer so I need help fast.  Thank you so much!!!  Heidi

**Comment by arnisjuraga** [comment]
@EggcellentMessages It seems, this would require more information from you, - OC version at least.
At first, you could check module version itself, compare source code of Paypal Express module, 
if it's newer on Github, make a backup and (the best - on test site) make the tests. 
Anyway, You would need to find some Opencart developer to support it.

**Comment by pnair39** [comment]
@EggcellentMessages if this is an existing store that has never done this and no modules were installed as of late. I would do a restore on a test site and run the purchase again to see if is happening. Than you will need to do a full restore of your site if this solves your problems. Good Luck!

**Comment by pelagise** [comment]
_I had a similar problem couple of months ago, and I had to do a restore on  2.1, never figured out what caused the issue.__

**Comment by ChrisLancs** [comment]
The error is telling you that there is nothing to call the check method of the class.

Im not sure what that means specifically as ive not upgraded to 2.3 yet im here today investigating to see whether its stable enough to upgrade a live store to.

Anyway that aside: Check the paypal payment actually occurred at paypal. If it did, try resending the IPN to your system it could have corrupted and so opencart cant handle it. if it did not then you have a customer attempting to circumvent your payments to get a free order.

**Comment by EggcellentMessages** [comment]
@arnisjuraga   I have 2.3.0.2
@pnair39   Does a full restore mean I lose all my info I already input?
@ChrisLancs    It wasn't a customer who made payment, it was me.  So no trying to circumvent.  And yes, all three times the payment actually went thru PayPal but no order on my end.

Thank everyone for your help.  I think I will just change my payment to 2checkout and forget PayPal.  Everyone is pointing the finger at each other on this one.  PayPal says that I need to talk to OpenCart to fix this issue and OpenCart says I need to speak with PayPal.  I've been working on this for days and no closer to fixing the issue.  And I already put in about 10 hours setting up my website so if restoring it means I have to set it up again, then it's just easier to use another payment source.

**Comment by EggcellentMessages** [comment]
By the way, I also tried using PayPal Standard and everything goes thru fine on PayPal end, but PayPal does not communicate with my site to tell it that payment was made, so my orders disappear on my site and become cancelled.  I've been trying to get help from OpenCart and PayPal on that one too and no one can tell me how I can get a Third Party Permission Username so that it will work correctly.  Ugh!

**Comment by ChrisLancs** [comment]
https://www.paypal.com/cgi-bin/webscr?cmd=_profile-api-list-auths

You want option 2 to grant/obtain the required credentials, If you have not put that info into the module thats why you are not getting the IPN back. although im confused as to why its working at all if thats the case

**Comment by ChrisLancs** [comment]
Thats all in **business setup** if you need to find it again in the future.

**Comment by pnair39** [comment]
@EggcellentMessages 1st Step: did you restore to a backup test site and confirm if it is working and does not have the same issue?

**Comment by EggcellentMessages** [comment]
@pnair39   Ummm, I'm a photographer not a computer programmer.  Although I'm very good at working with computers, I have no idea how to run a file & folder compare or how to do a backup test site.  **sigh**

Again, I think the simplest solution is to just go with 2checkout and hope all my issues get resolved this way.  Thanks though!!

**Comment by EggcellentMessages** [comment]
@ChrisLancs   I followed PayPal directions to a tee.  I've spent about 10 or more hours on trying to solve this issue and I think I'm just going to give up.  2checkout is my best solution.  But thank you!!  :-(

**Comment by jamesallsup** [comment]
I have been working on the PayPal module and this feature for the last few weeks and haven't had any errors like this. The PayPal module is working fine based on your errors above, it makes it into the addOrderHistory method of the checkout/order model.

The code below:

```
// Anti-Fraud
$this->load->model('extension/extension');

$extensions = $this->model_extension_extension->getExtensions('fraud');

foreach ($extensions as $extension) {
	if ($this->config->get($extension['code'] . '_status')) {
		$this->load->model('extension/fraud/' . $extension['code']);

		$fraud_status_id = $this->{'model_extension_fraud_' . $extension['code']}->check($order_info);

		if ($fraud_status_id) {
			$order_status_id = $fraud_status_id;
		}
	}
}

```

Specifically the line 267:
```
$fraud_status_id = $this->{'model_extension_fraud_' . $extension['code']}->check($order_info);
```

Is the one causing the error. Most likely a bad config for one of the fraud modules which is failing to create the model object, causing the check() method to fail because the expected model is null.

**Comment by collm109** [comment]
i found a work arround, if you dissable the anit fraud modules.
