### ISSUE TITLE
access to admin in opencart lost

### ISSUE THREAD

**Issue by Sillky01** [opencart/opencart#5243]
Hi  our developers have disappeared. we have a nice running web site but I cant log into admin to add and change products.

**Comment by Sillky01** [comment]
I don't know open cart - I know a little wordpress. I wonder if there is a config setting somewhere that gives me the admin url and user name and password. I am able to access php and sql databases. I need help is this something someone or a support company can assist with ?

**Comment by lucasjkr** [comment]
If you have access to the database, look for the users table (probably called oc_users but it could have a different prefix). I would look at the first user in the table - clear the value in the salt field, and change the password to `5f4dcc3b5aa765d61d8327deb882cf99`. Then you can login to the admin panel with that username and the password `password`.

I would close this issue though, it's not exactly an issue with opencart as far as its developers go.

**Comment by Sillky01** [comment]
Star ! Thank you I will xx

On 4 Mar 2017 6:32 pm, Lucas Krupinski <notifications@github.com> wrote:

If you have access to the database, look for the users table (probably called oc_users but it could have a different prefix). I would look at the first user in the table - clear the value in the salt field, and change the password to 5f4dcc3b5aa765d61d8327deb882cf99. Then you can login to the admin panel with that username and the password password.

I would close this issue though, it's not exactly an issue with opencart as far as its developers go.
