### ISSUE TITLE
opencart 2.0.1.1 make field only accept english numbers

### ISSUE THREAD

**Issue by AhmedMaherPro** [opencart/opencart#5244]
hello ,
my site working with arabic language and fields show arabic numbers how i can make fields show english numbers ????

**Comment by arnisjuraga** [comment]
Numbers in OC is formatted, using PHP function `number_format()`, which is based on server `Locale` settings, 
try to check this one:

http://stackoverflow.com/questions/437371/php-locale-aware-number-format

If you want only numbers formatted in En-Gb, you could modify `system/library/cart/currency.php`

**Comment by AhmedMaherPro** [comment]
my all site show numbers in arabic language i want show all numbers in site in english language 
give my steps to do that 
thanks

**Comment by pnair39** [comment]
@AhmedMaherPro  send email to support@opencart.com, they will send the email to Marketplace partner/member who may able to assist to create a quote to see if this can be written into an extension of some sort.
