### ISSUE TITLE
Bug issue on 2.3 Register, Orders and Reviews.

### ISSUE THREAD

**Issue by pelagise** [opencart/opencart#5249]
_I am having a review issue on 2.3 the emails are not going to my second email, I have selected register, orders and reviews. I don't see any error messages under tools and error logs_

**Comment by ADDCreative** [comment]
Could be this issue. https://github.com/opencart/opencart/pull/4757

**Comment by pelagise** [comment]
_#5228 in think this is more like the issue._

**Comment by ADDCreative** [comment]
They are both the same issue with the same solution..

**Comment by pelagise** [comment]
@pnair39 Thanks
