### ISSUE TITLE
what is clean controller (report/customer_login) ?

### ISSUE THREAD

**Issue by 4pxs** [opencart/opencart#5260]
https://github.com/opencart/opencart/blob/master/upload/admin/controller/report/customer_login.php

**Comment by roballport** [comment]
Odd, the controller isn't referenced in the admin menu controller either. Not a huge issue, assume it's some additional report that never got implemented.

**Comment by ADDCreative** [comment]
Also https://github.com/opencart/opencart/blob/master/upload/admin/controller/report/affiliate_login.php

**Comment by danielkerr** [comment]
yep. its in the dev branch but now removed
