### ISSUE TITLE
product is not added to cart from home page at 1st...after visiting other links or description of product then only it is able to add product to the cart

### ISSUE THREAD

**Issue by allzwell** [opencart/opencart#5262]

**Comment by ADDCreative** [comment]
Works for me in 2.3.0.2.

**Comment by arnisjuraga** [comment]
@allzwell you should at first check, if it's working with a default theme?
If you are using custom theme, that can be a reason for an issue.

**Comment by danielkerr** [comment]
theme issue

**Comment by danielkerr** [comment]
sick of people using this for support for their own issues!

**Comment by allzwell** [comment]
Thanx for your reply..I am completely new to opencart so i dont know much about it
