### ISSUE TITLE
2.3.0.2 Checkout page getting "Internal Server Error"

### ISSUE THREAD

**Issue by shopcouch** [opencart/opencart#5263]
Getting "internal server error" which registering a new account on Checkout page in Opencart 2.3.0.2

**Comment by tractcom** [comment]
Internal (500) server errors are normally caused by **incorrect file/folder ownership or permissions**. Check your Apache error logs for the cause, this is not an OpenCart issue.

With services providing virtualised servers, such as DigitalOcean, you will most likely want to set **www-data** as the owner/group and for permissions **755 on folders, 644 on files**. This can vary so please consult your sysadmin or hosting provider if these variables do not work for you.

**Comment by arnisjuraga** [comment]
@tractcom I doubt, that this is a permission error, but can be of course.
@shopcouch - Server error 500 "always" is logged in server error log files. This would not appear in OC log file `system/storage/logs/error.log` but most probably - in a server (Apache e.g.) log files.

Look up for hosting log files and this will give you much more explanation and directions to resolve.

**Comment by Chandraveer** [comment]
Increase your **memory limit** by editing php.in in root folder... this server issue not opencart one.

**Comment by amaranter** [comment]
I have this same issue, i used a EC2 instance with Ubuntu 16.04 and OpenCart 2.3.0.2 w/ PHP 7.0.18.  
In my Apache error log, has the issue: PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found.  
  
*Solution*:  
`sudo apt-get install php-dom`  
`sudo systemctl restart apache2`

**Comment by suryamunjal** [comment]
even i  am getting an "internal server error" on my checkout page before making payments.. i m using oc 2.3.0.2..any solutions?

**Comment by intorka** [comment]
Hi I am also using oc 2.3.0.2 in admin panal I take this error When I click the order view button to see order detail.
please help!

**Comment by sanjeevjaitly** [comment]
i am getting an "internal server error" on my checkout page before making payments.. i m using oc 2.3.0.2..any solutions?

**Comment by osworx** [comment]
Wrong site here to ask such questions!
You should visit https://forum.opencart.com/viewforum.php?f=191 and seach for similiar posts (there are a few ..).
If you cannot find a solution, create a new post there and ask.
