### ISSUE TITLE
Notice: Undefined property: Proxy::getTemplate in posakaworld.com/vqmod/vqcache/vq2-catalog_model_checkout_order.php on line 660

### ISSUE THREAD

**Issue by bindashsandeep** [opencart/opencart#5264]
I am tried hard and finally hope less. After successful transaction its showing the bellow error.

**Notice: Undefined property: Proxy::getTemplate in posakaworld.com/vqmod/vqcache/vq2-catalog_model_checkout_order.php on line 660** 

Please guide me to fix this.

**Comment by arnisjuraga** [comment]
@bindashsandeep - this seems to be your custom theme issue. Please, contact the developers of Theme. They should be able to help.
