### ISSUE TITLE
Issue: site blank

### ISSUE THREAD

**Issue by CokkocZateki** [opencart/opencart#5265]
Hi

I installed the cosmos theme and suddenly.my site is blank.  The banners are missing as well aso the layout. In my administration page it all.appears there. 

Any idea what the issue is

**Comment by danielkerr** [comment]
dont post support problems here!

**Comment by CokkocZateki** [comment]
Hi @daniel

Where should I post it?

Thanks for the speedy reply

**Comment by lucasjkr** [comment]
Contact the theme developer.
