### ISSUE TITLE
Twig modification with ocmod doesn't work

### ISSUE THREAD

**Issue by helgvor-stoll** [opencart/opencart#5268]
When using OCMOD, the new modification doesn't work and the non modified template is loaded. Whe must modifiy the constructor of the system/library/template/twig.php as following:
	public function __construct() {
		// include and register Twig auto-loader
		include_once DIR_SYSTEM . 'library/template/Twig/Autoloader.php';
		
		\Twig_Autoloader::register();	
		
		// specify where to look for templates
		$loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);	
		if (defined('DIR_CATALOG')) {
			$loader->prependPath(DIR_MODIFICATION . 'admin/' . substr(DIR_TEMPLATE, strlen(DIR_APPLICATION)));
		} else {
			$loader->prependPath(DIR_MODIFICATION . 'catalog/' . substr(DIR_TEMPLATE, strlen(DIR_APPLICATION)));
		}
		// initialize Twig environment
		$this->twig = new \Twig_Environment($loader, array('autoescape' => false));			
	}

Best regards,

Helgvor STOLL

**Comment by danielkerr** [comment]
Yes I'm fixing the installer and marketplace I'm adding

**Comment by helgvor-stoll** [comment]
It's better to embrace the constructor as below:
*******************************************************************
	public function __construct() {
		// include and register Twig auto-loader
		include_once DIR_SYSTEM . 'library/template/Twig/Autoloader.php';
		
		\Twig_Autoloader::register();	
		
		// specify where to look for templates
		$loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);	
		if (defined('DIR_CATALOG')) {
			if (is_dir(DIR_MODIFICATION . 'admin/' . substr(DIR_TEMPLATE, strlen(DIR_APPLICATION)))) {
				$loader->prependPath(DIR_MODIFICATION . 'admin/' . substr(DIR_TEMPLATE, strlen(DIR_APPLICATION)));
			}
		} else {
			if (is_dir(DIR_MODIFICATION . 'catalog/' . substr(DIR_TEMPLATE, strlen(DIR_APPLICATION)))) {
				$loader->prependPath(DIR_MODIFICATION . 'catalog/' . substr(DIR_TEMPLATE, strlen(DIR_APPLICATION)));
			}
		}
		// initialize Twig environment
		$this->twig = new \Twig_Environment($loader, array('autoescape' => false));			
	}
***************************************************************************
Best regards,
Helgvor STOLL

**Comment by danielkerr** [comment]
should work now i have put the view event in the db as the last one to be called

**Comment by uksitebuilder** [comment]
Still requires @helgvor-stoll fix to make twig templates work that have been modified by OCMoD

**Comment by danielkerr** [comment]
Why not just use the event system
