### ISSUE TITLE
Image uploading is not working in Windows environment

### ISSUE THREAD

**Issue by desuex** [opencart/opencart#5269]
This condition is always true on my windows machine even though configuration is correct.
`upload\admin\controller\common\filemanager.php:223`
```php
		// Check its a directory
		if (!is_dir($directory) || substr(str_replace('\\', '/', realpath($directory)), 0, strlen(DIR_IMAGE . 'catalog')) != DIR_IMAGE . 'catalog') {
			$json['error'] = $this->language->get('error_directory');
		}
```

**Comment by danielkerr** [comment]
str_replace('\\', '/', 

nedds also to be one on the 

!= DIR_IMAGE . 'catalog'

**Comment by danielkerr** [comment]
i need to fix it

**Comment by ADDCreative** [comment]
Line also 14 need changing to the following in master and dev branches. Stops directory traversal on Windows problem added by this commit https://github.com/opencart/opencart/commit/06b9a4d4a7fe7e2bbd50180f88713e1c11918b0e.
```php
$filter_name = rtrim(str_replace(array('*', '/', '\\'), '', $this->request->get['filter_name']), '/');
```

And line 39 as similar to line 223 should be something like.
```php
if (substr(str_replace('\\', '/', realpath($directory) . '/' . $filter_name), 0, strlen(DIR_IMAGE . 'catalog')) == str_replace('\\', '/', DIR_IMAGE . 'catalog')) {
```

**Comment by NejiMehrez** [comment]
is there a fix for this? i have a problem uploading images. Thank you

**Comment by ADDCreative** [comment]
Try https://github.com/opencart/opencart/pull/5421.

**Comment by danielkerr** [comment]
fixed this in a commit yesterday
