### ISSUE TITLE
Opencart 2.3.0.2 version Backup page Import button not work

### ISSUE THREAD

**Issue by mtjhost** [opencart/opencart#5270]
Opencart 2.3.0.2 version Backup page Import button not working. It is same as the Export button. How to correct it.

**Comment by ADDCreative** [comment]
It seems to work for me. Check your files against the originals.

**Comment by mtjhost** [comment]
Ok, its working now.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=mtjcart@gmail.com&idSignature=22>


------------------------------
------------------------------

TEAM

*Support and Technical Services*

For help with Seller Services, Customer Support,

Technical or other please contact:

Email : care@mtjcart.com

Store link : https://www.mtjcart.com

Contact No. : +91-9033300553 (Whatsapp)

Seller Dashboard : https://www.mtjcart.com/login
<https://www.mtjcart.com/index.php?route=account/login/>

Company Website : https://www.mtjcart.com/company

Social Channels :    <http://www.twitter.com/mtjcart>
<http://www.facebook.com/mtjcart/>  <http://www.googleplus.com/+mtjcart>

<https://play.google.com/store/apps/details?id=com.wMtjcartShopping>
<https://play.google.com/store/apps/details?id=com.wMtjcartShopping/>

----------------------------------------------------
ADDRESS  *Mtjcart India*

Near Vadodara Design Academy Bill Road,

Jambusar Highway, Vadodara, 390012, India

----------------------------------------------------

Disclaimer: This e-mail message and any attachment thereto contains
confidential, proprietary and legally privileged information. It is for the
exclusive use of the addressee. If you are not the addressee please note
that any distribution, copying or use of this communication or the
information in it is prohibited. If you are not the intended recipient,
please notify us, preferably by e-mail, and do not read, copy or disclose
the contents of this message to anyone. The recipient must note and
understand that any views expressed in this message are those of the
individual sender and no binding nature of the message shall be implied or
assumed unless the sender does so expressly with due authority of
Mtjcart.com and associated companies.
