### ISSUE TITLE
Missing translation for 'text_extension' in the breadcrumb for all shipping methods in the backend.

### ISSUE THREAD

**Issue by siven76** [opencart/opencart#5271]
On all the shipping methods in the backend, the breabcrumb shows 'text_extension' instead of the appropriate translation.

<img width="451" alt="screen shot 2017-03-14 at 4 43 20 am" src="https://cloud.githubusercontent.com/assets/2442605/23867696/d60178e4-0870-11e7-99ed-75addab46399.png">

**Comment by siven76** [comment]
**Solution**:

Add the following line in all the language files of shipping methods (to all files under /admin/language/*/extension/shipping/*.php)

`$_['text_extension']	           = 'Extensions';`

**Comment by ChrisLancs** [comment]
Not sure that text_extension**s** is required unless ive missed it somewhere else, last item on breadcrumb comes from the heading_title. simple fix though rather than modifying all shipping files to add the missing line, thanks.

**Comment by OpenCartAddons** [comment]
Breadcrumbs call for text_extension.  Ideally this would be in the general language file `en-gb.php` to avoid repetition.

`$data['breadcrumbs'][] = array(
			'text' => $this->language->get('text_extension'),
			'href' => $this->url->link('extension/extension', 'token=' . $this->session->data['token'] . '&type=shipping', true)
		);`

**Comment by danielkerr** [comment]
can some one add it to the master? i did it on the dev branch already, i should have done it the other way and pulled the fix accross.

**Comment by OpenCartAddons** [comment]
@danielkerr https://github.com/opencart/opencart/pull/5272
