### ISSUE TITLE
Orders not Assigned a valid status - PayPal Standard

### ISSUE THREAD

**Issue by jasonc310771** [opencart/opencart#5275]
I am using Version 2.3.0.2, and orders that I have done via paypal standard are not showing up in admin. I thought I register an account and try again and still the second order that the payment went through ok this also did not show up in admin. They show in phpmyadmin, I am using OC out of the box.

**Comment by arnisjuraga** [comment]
Do you have those orders under "Missing Orders" status?
![image](https://cloud.githubusercontent.com/assets/2185289/23893462/333511b6-08a7-11e7-8955-54eba5f39704.png)

**Comment by jesusdlg** [comment]
Hi,

I've exact this problem, any solutions for this? My clients are being charged on paypal but some of those orders are under Missing Orders status.

Thanks for your help!

**Comment by danielkerr** [comment]
then resave the paypal settings! 

or settings. 

some peope delete an order status that is assigned to their payment gateway

**Comment by fishtankmike** [comment]
I'm having this same issue is there a fix?
