### ISSUE TITLE
custome page permission denied

### ISSUE THREAD

**Issue by allzwell** [opencart/opencart#5276]
I am completely new to opencart. Please give suggestion if possible. I have added custome page into default version of opencart 3.2.0.2. It works fine but when i enabling the status and save changes it gives me Warning: You do not have permission to modify Recent Products module!.. 
For that I have followed the steps also. But still getting same Error:
1. Login to admin, go to System > User Group.
2.  Edit your admin usergroup
3. Add permission to your new extension modules (both Access Permission and Modify Permission).

My question is for this should i need to install ocmod or vqmod?? if yes please guide something..
thank you!!

**Comment by arnisjuraga** [comment]
You want to ocmod or vqmod for what? To fix this error? Or you need som additional modules? 
Ocmod and Vqmod are engines, for plugins installation and usage. Ocmod is includeed in Opencart by default. Vqmod has to be installed manually. 

But they are not the reason for the error.

Can you give a link to the module you are using?

**Comment by allzwell** [comment]
Thank you 
We have requirement to show the "coming soon" or "New" label on product in product list
For this I am trying to develop new functionality
The Page is added in Admin->Controller->Extension->Module->My CustomPage
For this to develop is there need to install vqmod?
I am doing the development on localhost...
In case of giving module link how can we proceed?

**Comment by arnisjuraga** [comment]
No,
vqmod is not required.

But this sounds more like a Forum post in Forums, as this is not an issue.

**Comment by allzwell** [comment]
okk thank you!!
