### ISSUE TITLE
2.3.0.2 Incorrect file name

### ISSUE THREAD

**Issue by ChrisLancs** [opencart/opencart#5278]
Found incorrect filename in compiled 2.3.0.2 downloaded from opencart website last week.

system/library/template/**tiwg**.php

**Comment by danielkerr** [comment]
2.3.0.2 does not use twig it uses php. if u checkled the dev baranch u would see its been changedl. wasting my time

**Comment by RaidoDev** [comment]
@ChrisLancs can you give your contacts, I have similar issue and want to look up for it.

**Comment by osworx** [comment]
@danielkerr 2.3.x does not use, but the wrong named file is there.
