### ISSUE TITLE
stylesheet from custom template folder not loading properly when using PHP7?

### ISSUE THREAD

**Issue by Icebox-Studio** [opencart/opencart#5279]
I decided to test php 7.0 out in a local testing environment. I did a fresh local install of OC (the same release candidate version) using php 7 and just simply copied over my "custom" template folder from my previous php 5.6 installation. My custom template folder is relatively simple as it only has a modified stylesheet (namely, just changing the color scheme in the top header components and nothing else) along with a custom TPL header file to move some links around. 

The custom TPL file appeared loaded where I changed some links around , but the custom stylesheet did not. For example, I changed the grey top bar to black in the custom stylesheet and instead no color registered at all, so it became white/no color.

Next, I decided to toss out the custom tpl file and just be left with my custom stylesheet in my custom folder to see what happens. The default stylesheet style color schemed appeared. I did an inspect on the page, and I saw that the default stylesheet was called all over. So my custom stylesheet definitely is not getting called properly when changing to a "custom" template in the backend.

There are no plugins installed by the way.

Has anyone else experienced this with php 7? I figure I would  bring this subject up before doing any heavy stylesheet modifications.

I did some research on php 7.0 and stylesheet issues in general, and they appear to exist in other capacities. I just can't pinpoint/translate to where or why they are occuring in opencart using php 7.0  though.

**Comment by Icebox-Studio** [comment]
I already had thought about that after my post. I cleared the browser cache and even the opencart cache in the system folder (which I knew would not anything anyhow - but just in case).

It still doesn't explain why the stylesheet colors did not even register at all with the custom tpl file and why it showed as default with it immediately removed even though the store template settings are set to to the custom folder.

**Comment by ChrisLancs** [comment]
Are you seeing the link to the new stylesheet in the head block?

**Comment by danielkerr** [comment]
its not a development issue thats stopping people from using opencart!

its a problem you causerd and should be able to fix using the correct paths
