### ISSUE TITLE
Looking for New Path and references for statements in  2.3.0.2 that are in 2.1.0.2

### ISSUE THREAD

**Issue by pnair39** [opencart/opencart#5283]
`<![CDATA[<li><a href="<?php echo $backup; ?>"><?php echo $text_backup; ?></a></li>]]>`

`<![CDATA[$data['zone'] = $this->url->link('localisation/zone', 'token=' . $this->session->data['token'], 'SSL');]]>`

**Comment by arnisjuraga** [comment]
Please, be more specific

**Comment by pnair39** [comment]
Originally these paths existed in 2.1.0.2.

admin/controller/common/menu.php
`<![CDATA[$data['zone'] = $this->url->link('localisation/zone', 'token=' . $this->session->data['token'], 'SSL');]]>
`
admin/language/english/common/menu.php
`<![CDATA[$_['text_backup']]]>`

admin/view/template/common/menu.tpl
`<![CDATA[<li><a href="<?php echo $backup; ?>"><?php echo $text_backup; ?></a></li>]]>`

**Comment by pnair39** [comment]
I was able to resolve it.
