### ISSUE TITLE
Added support for Twig partials 3.0.0.0

### ISSUE THREAD

**Issue by dmitriyzhuk** [opencart/opencart#5284]
Hi guys. Since we are moving to twig, I think it would be also a great deal to implement partials with Include.

We have dynamic theme folders, so we would need a  twig function to return the correct path to the twig file, checking if it is not available in the current theme folder and falling back to the default folder or if its missing there - returning an empty.twig to avoid errors. 

Twig allows us to create TwigExtensions, so with this we can add a custom function 

Ex. without twig function)
{% for product in products %}
   {% include 'default/template/product/product_thumb.twig' with product %}
{% endfor %}

Ex. (with twig function)
{% for product in products %}
   {% include template('product/product_thumb.twig') with product %}
{% endfor %}

the theme is dynamic, as it should be in case the current theme has no product_thumb.twig

Implementing this is really a question - do we want to have DRY templates or do we want to continue copy/pasting. 

What do you think?

**Comment by danielkerr** [comment]
not a chance
