### ISSUE TITLE
[suggestion] Add login attempt blocker to admin area

### ISSUE THREAD

**Issue by smolinari** [opencart/opencart#5286]
In reference to #5285 and since the issue was locked.... 

Not sure if OC has it, but a timing system for false login attempts could also be a good deterrent for hackers trying to break into the admin area. It looks like the hacker brute-forced the easy passwords in the referenced video. So adding a "you've attempted to log in incorrectly 5 times. You can try again after 15 minutes" login attempt delay would deter that kind of brute force attack. 

Scott

**Comment by kangjoni76** [comment]
You could also defending by using embedded hidden unique random token in login form and save it in sessions data, then compare it using posted hidden token.

**Comment by danielkerr** [comment]
@smolinari was removed foir a reason read my comments!

**Comment by danielkerr** [comment]
open an issiue again like this get a ban!

**Comment by smolinari** [comment]
I don't understand your comment. I am only making a suggestion to try and help OC be better.

Scott

**Comment by danielkerr** [comment]
I already posted in my last comment my plan for the admin. I don't need
another issue opened on the same subject

**Comment by smolinari** [comment]
Do as you will. I've now decided I will not support this software in any way past this issue other than if someone pays me. I already regret making this suggestion. 

Scott
