### ISSUE TITLE
Using too much CPU resources

### ISSUE THREAD

**Issue by webzstore-sahel** [opencart/opencart#5287]
Hi,
I have opencart site version is 2.1.0.1. Overall 15000 products. 253 categories.
Currently the site is not public to visitor but it is live. But due the over resource usage it is down now.

My server administrator sent some message to me. Hope this will help you to find the issue. 

-----------------------------------------------------------------------------------------------------------
Looking at your account's PHP script execution statistics, I can see that the issue is caused by the fact that your PHP scripts run for too long. According to the statistics the average time your PHP scripts execute for is over 8 seconds. Keep in mind that in general PHP scripts should not take more than 1 second to complete their execution. To resolve this issue you should try to optimize your website's PHP scripts so that they execute faster.

The issue is very slow PHP scripts (average execution over 8 seconds). Your PHP scripts also generate a lots of MySQL queries which stack up:

`+----------+------------------+-----------+-------------------------+---------+------+------------------------------+------------------------------------------------------------------------------------------------------+-----------+---------------+
| Id | User | Host | db | Command | Time | State | Info | Rows_sent | Rows_examined |
+----------+------------------+-----------+-------------------------+---------+------+------------------------------+------------------------------------------------------------------------------------------------------+-----------+---------------+
| 71492181 | myorga8_mofs | localhost | myorga8_mofs | Query | 82 | Waiting for table level lock | UPDATE oc_product SET viewed = (viewed + 1) WHERE product_id = '36232' | 0 | 0 |
| 71492688 | myorga8_mofs | localhost | myorga8_mofs | Query | 59 | Waiting for table level lock | UPDATE oc_product SET viewed = (viewed + 1) WHERE product_id = '25065' | 0 | 0 |
| 71492756 | myorga8_mofs | localhost | myorga8_mofs | Query | 1 | Sending data | SELECT COUNT(DISTINCT p.product_id) AS total FROM oc_category_path cp LEFT JOIN oc_product_to_catego | 0 | 0 |
| 71492784 | myorga8_mofs | localhost | myorga8_mofs | Query | 0 | Sending data | SELECT COUNT(DISTINCT p.product_id) AS total FROM oc_category_path cp LEFT JOIN oc_product_to_catego | 0 | 0 |
| 71492806 | viajesyc_wo6144 | localhost | viajesyc_wo6144 | Sleep | 2 | | | 0 | 1 |
| 71492813 | myorga8_mofs | localhost | myorga8_mofs | Query | 1 | Sending data | SELECT COUNT(DISTINCT p.product_id) AS total FROM oc_category_path cp LEFT JOIN oc_product_to_catego | 0 | 0 |
| 71492848 | intelliv_E69N6 | localhost | intelliv_865Tu | Sleep | 0 | | | 0 | 0 |
| 71492944 | myorga8_mofs | localhost | myorga8_mofs | Query | 1 | Sending data | SELECT COUNT(DISTINCT p.product_id) AS total FROM oc_category_path cp LEFT JOIN oc_product_to_catego | 0 | 0 |`

One more thing I want to share with you. When I logged in to the site it always shows me more than 300 users are online. Although hardly 10 users usually online in real.

**Comment by arnisjuraga** [comment]
1. Switch off Product counts for category (if you have not done it already)
2. use som performance modules, e.g. - the ones, whcih replaces `NOW()` with `" . date("Y-m-d") . "` in product and category models.
3. use some CACHE modules. 
4. search for some additional INDEXES for OC database, e.g. for `url_alias` table etc.

you should hire some developer to make a OC work faster. It depends on a scale and products, categories, theme you are using.

**Comment by danielkerr** [comment]
maybe need to move the view counter to a separate table. i will add some teaks when i have time.

**Comment by arnisjuraga** [comment]
`with over a million` - that should be some custom development, as there is no way it can be done without performance problems on stock OC :(

**Comment by webzstore-sahel** [comment]
Although I'm using shared server. Is it okay?

**Comment by CoverUp** [comment]
Just my comment: I work with several sites that handle between 15000 and 20000 products (mainly tech resellers). Without optimization these sites are shown in an average of 8 to 10 sec, wich of course is an awful UX. But after optimization, you can get 2 to 3 sec in average. Main key is indexing DB, disable the product count per category and also limit the max product per page, and then load with ajax the rest of the products.
The two first option can be done in any OC installation, but the third one require a custom development.
I suggest to index DB as default, make a new table for product view and product count per category and optimize db querys with prepare and binding (prepare() and bind_param() functions)
The result is stunning at least on mysql side, for example we have made a module for update stock and price of those 15000 products in a hourly basis, without this implementation using individual querys this took over 30 minutes, but using this technic we have shortened this elapsed time to just a couple of secs. Final thoughts: using a VPS for this kind of stores is a must BTW. Regards.

**Comment by ChrisLancs** [comment]
You are going to find that most shared hosting providers will not be happy with hosting a heavily used website such as a busy online retailer even with all of the above being implemented. A VPS will go some way to mitigate this as you will not be sharing the resources with so many other users but sooner or later you will probably come back to the same situation.

Nonetheless if you get these sorts of reports it suggests that your website may be pulling enough income to justify the costs involved in purchasing your own servers and having them collocated at a suitable datacentre. This is beyond the scope here so il leave it at that but its something for you to consider.

**Comment by webzstore-sahel** [comment]
Although I'm using shared server. Is it okay?

**Comment by eatshitdone** [comment]
Hi, webzstore-sahel

Problem is doing INSANE queries in loops. It's somehow opencart way. 

Solution is to make one big query before loop and use lookup table for product count. 

I use heavily modificated 2.1.0.1 (incompatible with vanilla both DB and API) with about 150 categories and about 2500 products. Page gen time is below 500ms on category.


Use something like this where categories are counted:
```
        $categories = $this->model_catalog_category->getCategories(0);

        $map = $this->model_catalog_category->getTotalProductsData();

        foreach ($categories as $category) {
            if ($category['top']) {
                // Level 2
                $children_data = array();

                $children = $this->model_catalog_category->getCategories($category['category_id']);

                foreach ($children as $child) {
                    $name = $child['name'];
                    if (!empty($map) && isset($map[$child['category_id']])) {
                        $count = $map[$child['category_id']];
                        if ($count == 0) {
                            continue;
                        }
                        $name .= ' (' . $count . ')';
                    }
                    $children_data[] = array(
                        'name' => $name,
                        'href' => $this->url->link('product/category', 'path=' . $category['category_id'] . '_' . $child['category_id'])
                    );
                }

                // Level 1
                $data['categories'][] = array(
                    'name' => $category['name'],
                    'children' => $children_data,
                    'column' => $category['column'] ? $category['column'] : 1,
                    'href' => $this->url->link('product/category', 'path=' . $category['category_id'])
                );
            }
        }

```

Category model method 
```
    public function getTotalProductsData() {

        $DB = DB_PREFIX;
        $store_id = (int) $this->config->get('config_store_id');

        $cache_key = 'total_products_table_' . $store_id;

        if ($this->registry->has($cache_key)) {
            return $this->registry->get($cache_key);
        }

        $sql = <<<SQL
    SELECT p2c.category_id, count(*) as total
        FROM        {$DB}product_to_category p2c 
        LEFT JOIN   {$DB}product             p       ON ( p2c.product_id = p.product_id )
        LEFT JOIN   {$DB}category            c       ON ( p2c.category_id = c.category_id )
        LEFT JOIN   {$DB}product_to_store    p2s     ON ( p2c.product_id = p2s.product_id )
        WHERE   p.status = 1 
            AND c.status = 1 
            AND p2s.store_id = $store_id
        GROUP BY p2c.category_id
        ORDER BY p2c.category_id
                
SQL;
        $q = $this->db->query($sql);

        $map = array();
        foreach ($q->rows as $n => $row) {
            $map[$row['category_id']] = $row['total'];
        }

        $this->registry->set($cache_key, $map);

        return $map;
    }
```

It works same as vanilla code, but faster.
Setting to registry is memoization. You can use caching instead.

Feel free to ask questions.

**Comment by ChrisLancs** [comment]
Do you have the page load times without this modification? Could you become a contributor? The dev branch looks like its going to be version 3.0 so it might be better to get these speed improvements into the dev core instead?

**Comment by eatshitdone** [comment]
Page generation time without patch was about 500ms on 1G RAM VPS and raised to 1000-2000ms on 512M RAM VPS. Disable count wasn't an option. 

With patch it's about 50ms on 512RAM VPS.

Reviewed code and found that my solution doesn't count subcategories prods as does vanilla. 

```
    public function getTotalProductsSubCategory(){
        
        $DB = DB_PREFIX;
        $store_id = (int) $this->config->get('config_store_id');

        $cache_key = 'total_products_sub_table_' . $store_id;

        if ($this->registry->has($cache_key)) {
            return $this->registry->get($cache_key);
        }

        $sql = <<<SQL
    SELECT cp.path_id AS category_id, COUNT(p2c.product_id) AS total 
        FROM {$DB}category_path cp 
        LEFT JOIN {$DB}product_to_category p2c  ON(p2c.category_id = cp.category_id ) 
        JOIN {$DB}category c                    ON(c.category_id = p2c.category_id AND c.status = 1 ) 
        JOIN {$DB}product p                     ON(p.product_id = p2c.product_id and p.status = 1) 
        LEFT JOIN {$DB}product_to_store p2s     ON( p2s.product_id = p.product_id) 
    WHERE p2s.store_id = {$store_id} 
    GROUP BY cp.path_id ORDER BY cp.path_id 
SQL;
        $q = $this->db->query($sql);

        $map = array();
        foreach ($q->rows as $n => $row) {
            $map[$row['category_id']] = $row['total'];
        }

        $this->registry->set($cache_key, $map);

        return $map;
    }
```
Now it counts exactly as vanilla - only with one level of subcategories. 

> Could you become a contributor?

Maybe in future.

**Comment by syslogic** [comment]
the record count probably should be cached in a column, not generated by SQL domain aggregate function - hence the value only changes when adding/removing products.

**Comment by arnisjuraga** [comment]
@syslogic record count changes also when:
- product availability date starts/ends `date_available > NOW()`; this can be processed by some cron job?
- product sales out; can be processed in order checkout)

**Comment by eatshitdone** [comment]
@syslogic, it's very inefficient, especially for counting with subcategories. When you add product to category or change its quantity or avail status (or maybe something that I missed), you must check all ancestors and update their counters => code complexity, I/O, storage. 

My approach stands on fact that each request needs counter for all categories at least 1 time in main menu.  It solves the problem, works fast as hell and requires just simple code changes.

**Comment by syslogic** [comment]
@arnisjuraga doing it by cronjob would reduce the portability of the script... while PHP itself doesn't really have a timer. most simple might be, to create kind of pseudo cron, eg. which runs on the first page request of the day, updates availability & category count.

**Comment by ChrisLancs** [comment]
Then another table that gets updated at product save.

cat_ic | prod_count

I know its yet another table but it would mean the count is done once only at product edit time and not every time on category load.

**Comment by eatshitdone** [comment]
Guys, seriously. I shared with you simple and efficient solution. Stop creating monsters.

DB updates by cron => data are inconsistent most of time, load spikes.

**Comment by smolinari** [comment]
> DB updates by cron => data are inconsistent most of time, load spikes.

This is though a compromise for running aggregate queries, which are costly (and not necessarily poorly programmed). Such cron jobs are created specifically for that reason and ran at a time, when the server is running with a lower load (usually early morning). It is also clear that such aggregates are not 100% accurate. If a 100% accurate aggregate query is needed, other measures must be taken (if the aggregation is already as well programmed as possible.)

Scott

**Comment by eatshitdone** [comment]
@smolinari. see code and graphs above. Works perfectly. Query isn't that big to make it separately. It's indexed and simple from mysql view.
Result data are only two 32 bit ints per row, less than 1KB per 200 rows. Less than one product description.
It makes no sense to cron it.

**Comment by smolinari** [comment]
I was just saying.....:smile: I am not sure what the needed solution is here.

Scott

**Comment by volomike** [comment]
Note on some hosting plans (hostgator has been notorious for me in the past), they put an incredibly ridiculous resource usage allocation on PHP scripts. If you prefer shared hosting, then try another hosting plan. (Personally, I use A2hosting, but there are others.) If that doesn't help, then consider a cloud hosting account such as with DigitalOcean or other company.

**Comment by webzstore-sahel** [comment]
After enabling database cache, it stated working fine for now.
