### ISSUE TITLE
purchased ssl certificate do I need to redirect http to https ? 

### ISSUE THREAD

**Issue by Sillky01** [opencart/opencart#5289]
Hi I am new to open cart  and loving it. I recently purchased an ssl certificate an applied it to my site but it is not being seen by seo. Now  do I need to redirect http to https or does shopping cart do this automatically ? 

If notanu ideas how I do this and preserve backlinks ? I have had a look at my .htaccess file to see if it is obvious what to edit  but it is empty :0(. I am stumped. 

My site has 3 stores/ databases  you land on the front page and are redirected when clicking on your interest. Does anyone have an example 

thank you

**Comment by beipink** [comment]
the forum is the right place for this type of questions.
OC does it automatically for pages that contains private information. search the forum if you want to have the entire site in https. 
.htaccess  is not empty. download it again and rename it

**Comment by Sillky01** [comment]
Thank you

On 19 Mar 2017 1:44 am, beipink <notifications@github.com> wrote:

the forum is the right place for this type of questions.
OC does it automatically for pages that contains private information. search the forum if you want to have the entire site in https.
.htaccess is not empty. download it again and rename it
