### ISSUE TITLE
OC 3.0.0.0 (dev) view events still broken

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#5290]
The view events are still broken.

For example, suppose the Loader::view method is called for the frontend template route 'product/product':

After having triggered the '**view/product/product/before**' events, the route is changed to 'default/template/product/product'.  It therefore won't trigger any subsequent '**view/product/product/after**' events.

Also, if any of the '**view/product/product/before**' events creates a rendered '**output**'
then no subsequent '**view/product/product/after**' events are triggered.

Suggested fix for this:
- don't use an 'output' argument for the view-before events
- always trigger the view-before and view-after events with the original route value

**Comment by danielkerr** [comment]
its on my tgo do list!

**Comment by danielkerr** [comment]
last commit should fix this
