### ISSUE TITLE
Opencart.com Marketplace-Popup Image of Extension Screenshots are too small/unclear

### ISSUE THREAD

**Issue by mike652638** [opencart/opencart#5291]
Dear Authors,

My great appreciations for your great work on this open source platform :)

I have a suggestion regarding the plugins marketplace of opencart.com, in fact it's a feedback put forward years ago in opencart forum, see https://forum.opencart.com/viewtopic.php?t=131739

Improvements might be applied to make the screenshots of plugins with larger size and clear resolution (even better if you can advice the plugins developer to show screenshots of both back-end and front-end interface), I think this can further populate the plugins marketplace :)

(I am sorry if this suggestion is inappropriate here since it's not directly relative with opencart product itself)

Best Regards,
Mike
mike652638@gmail.com 

For example, hard to recognize even zoomed:
![suggestion-for-opencart-marketplace-2](https://cloud.githubusercontent.com/assets/21060980/24088850/8e677b92-0d6a-11e7-8281-5322c504cb36.png)

**Comment by kostasmoure** [comment]
its better to make them larger with high resolution and the option to be resized.

**Comment by samchen945** [comment]
I think developer should upload better image rather than simple screenshot if they want t0 promote their modules better.

**Comment by arnisjuraga** [comment]
@samchen945 isn't it? Checkout, e.g. this one: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=10848 
- they have uploaded a bunch of images. It's impossible to create a fullscreen snapshot if the maximum resolution available is 500x500px. That's the problem  @mike652638 proposing, I think.

**Comment by danielkerr** [comment]
you shopudl make images that are 500px x 500px

**Comment by arnisjuraga** [comment]
@danielkerr It's not a problem to make images 500x500, but this size is historical! It's much too small, to put fullscreen pictures. That's it.
