### ISSUE TITLE
FTP

### ISSUE THREAD

**Issue by scouse12** [opencart/opencart#5292]
Hi, ive added all my log in details to the ftp section but it still says it cant connect, i cant install any extensions because of it, my log in details are definitely correct because i can log in with filezilla using the same details without any problem so....?
im using oc 2.3.0.2 and my hosting is with easyspace.com
thanks for any help/info

**Comment by mike652638** [comment]
Hi,

Have you tried the following plugin ? It has helped many people out :)

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=18892&filter_search=fix

**Comment by scouse12** [comment]
Hi, I've literally just done this 2 min before you emailed and it's working, thanks for getting back to me tho, all the best

Sent from my iPhone

On 20 Mar 2017, at 17:37, Mike Zheng <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Have you tried the following plugin ? It has helped many people out :)

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=18892&filter_search=fix
