### ISSUE TITLE
load->controller() with multiple parameters

### ISSUE THREAD

**Issue by lswamy** [opencart/opencart#5300]
I am trying to call a method in another controller with multiple parameters.
For example:

class ControllerModuleFoo extends Controller {
  public function bar($param1, $param2) {
    //do something
  }
}

In another controller I call this:
$this->load->controller("module/foo/bar", array($param1, $param2));

This fails since bar is expecting 2 args, but only 1 is passed to it, which I traced to Loader::controller() which calls action execute with a single array param.

Is this a bug or is it done this way  on purpose ?

**Comment by 4pxs** [comment]
example with array data and two arguments https://github.com/admincart/opencart-admincart/blob/master/public/system/engine/loader.php  (load controller method).

**Comment by lswamy** [comment]
Thanks for the example, but I prefer a solution that does not require modifying a core system library like loader.php
FYI I am currently on version 2.2

**Comment by 4pxs** [comment]
it is example. you can create modification file.

**Comment by lswamy** [comment]
My original question was intended to find out if the current system is working correctly.
The code in action.php is comparing the number of args passed to the number of args required by the controller method, which will always fail if the controller method requires more than 1 arg.
Why do this if it only ever supports calling a method with 1 parameter?

**Comment by 4pxs** [comment]
Is the best solution in the current system for data array with many arguments. In another case it would be necessary to write a handler strictly for each argument, and use call_user_func_array vs call_user_func. 
http://php.net/manual/en/function.call-user-func-array.php

**Comment by danielkerr** [comment]
going to add this.

**Comment by danielkerr** [comment]
actually no i can not add this. 

other wise data will be sent as 

$arg[1]['setting']

**Comment by lswamy** [comment]
I did not think this was going to be an easy fix. Any update will likely break functionality.
It should at least be documented that only 1 array arg is supported.

**Comment by danielkerr** [comment]
i dont think it will break much. its just a pain to deal with var references and func_get_args

the next version is 3.0. so a lot will break.

why do u explain the what you are building and why you want this feature?

**Comment by lswamy** [comment]
I'm trying to keep my code modular and would like to call methods from other controllers.
I prefer using multiple parameters with type hinting in function definitions rather than a single array.
It helps other developers know exactly how to call the method and what parameters are required.

**Comment by danielkerr** [comment]
ok ill add it now

**Comment by lswamy** [comment]
Is this being added for version 3.0 ?

**Comment by danielkerr** [comment]
no it can't be done because can not reference. need to wait for php to fix loads of stuff
