### ISSUE TITLE
Error when add new product

### ISSUE THREAD

**Issue by Karim988** [opencart/opencart#5307]
when add new product it's shows that error 

Notice: Undefined index: stock_status_id in /home/eltamimi/public_html/system/storage/modification/admin/model/catalog/product.php on line 4Notice:
 Undefined index: weight_class_id in /home/eltamimi/public_html/system/storage/modification/admin/model/catalog/product.php on line 4Notice:
 Undefined index: length_class_id in /home/eltamimi/public_html/system/storage/modification/admin/model/catalog/product.php on line 4Warning:
 Cannot modify header information - headers already sent by (output started at /home/eltamimi/public_html/admin/controller/startup/error.php:34) in /home/eltamimi/public_html/system/library/response.php on line 12

the weird thing that it's working on the localhost.

**Comment by danielkerr** [comment]
inim closing this because its an issue with a modifcation
