### ISSUE TITLE
Coupon title with parenthesis

### ISSUE THREAD

**Issue by iBet7o** [opencart/opencart#5308]
Hello,

Today I had a problem with the title of a coupon, which contained parenthesis, and the method "confirm" that it marked the order as fraudulent.

I think the function "strpos" should be replaced by "strrpos" and thus avoid problems with title that contain parentheses.

https://github.com/opencart/opencart/blob/master/upload/catalog/model/extension/total/coupon.php#L189

**Comment by danielkerr** [comment]
it will be a language file issue! it works fine for me and exactly how strpos should work!
