### ISSUE TITLE
SSO URL not working 

### ISSUE THREAD

**Issue by psramkumar** [opencart/opencart#5310]
SSO URL is not working when i turn on the option. 
i provided the a valid SSO Key as well in Each product and Category.
in latest Opencart Code base

**Comment by psramkumar** [comment]
closed because this is not a valid issue ?
i'm i doing something wrong?

**Comment by danielkerr** [comment]
i have no idea what SSO  and its working for many other people. github is not your personal Q&A tghat is what the forum  and contact us form is for so my staff can deal with it.
