### ISSUE TITLE
issue while enabling cart sms in opencart website

### ISSUE THREAD

**Issue by balachander1205** [opencart/opencart#5311]
![2017-03-28_11-31-07](https://cloud.githubusercontent.com/assets/13295349/24391111/b40c4a94-13aa-11e7-952e-db523331dae6.jpg)

facing this error in my opencart website while trying to enable cart sms module. Any help and solution in really appreciated. Thanks in advance.

Bala Chander D
author & admin 
giftgalleries.in

**Comment by botonakis** [comment]
Cart SMS is not OpenCart's module.

**Comment by danielkerr** [comment]
not to post here.  use the contact us form
