### ISSUE TITLE
Notice: Undefined variable: _SERVER in system/startup.php on line 70

### ISSUE THREAD

**Issue by webzstore-sahel** [opencart/opencart#5314]
Hi,
Suddenly we are getting notice in our admin side like
Notice: Undefined variable: _SERVER in /home/myorga8/public_html/vqmod/vqcache/vq2-system_startup.php on line 70
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/myorga8/public_html/vqmod/vqcache/vq2-system_startup.php:70) in /home/myorga8/public_html/system/library/session.php on line 21Notice: Undefined index: HTTPS in /home/myorga8/public_html/BanglADM19s5/controller/common/header.php on line 6

Can you please help us why it is happening?
Thanks.

**Comment by webzstore-sahel** [comment]
Hello to all contributors,
Is there anyone who can relate with the issue. Please let me know.
Thanks.

**Comment by webzstore-sahel** [comment]
Is this not belongs to opencart or what? Please clarify me.

**Comment by AMDS** [comment]
What PHP version are you using for this site?

Try 5.6

**Comment by cartbinder** [comment]
The answer is this:
https://forum.opencart.com/viewtopic.php?f=202&t=202269#p714709
