### ISSUE TITLE
Opencart “Confirm order” button not clickable, for COD as payment method

### ISSUE THREAD

**Issue by sresenthil** [opencart/opencart#5316]
I have an opencart application working fine with no major issues. Right now I have enabled two payments including COD. Here is the issue..

During the checkout process, select the payment method (anything other than cod) and check the terms and condition checkbox and click the Continue button, and after this we can see the confirm order details (accordion tab for confirm order). Now here, do not press the "Confirm order" button and instead go back to same Payment Method tab (accordion tab for payment method) and change the Payment method to COD and click on continue. After this we can see the order details in "confirm order accordion tab", and now click on "Confirm order" button to place the order.

And now the issue is The button is not clickable or no event occurs when we press the button.

Need help in fixing this issue. TIA

**Comment by ADDCreative** [comment]
Works OK for me. Try on the forums https://forum.opencart.com/ or support https://www.opencart.com/index.php?route=support/support.

**Comment by sresenthil** [comment]
Thanks for the reply.  Can you please enable COD and check., because I am getting the error when i select COD as payment method. If it still works, can you share the code which is in cod.tpl file ?

**Comment by sresenthil** [comment]
FYI, I am using opencart 2.3

**Comment by ADDCreative** [comment]
Yes, it worked. cod.tpl should be. https://github.com/opencart/opencart/blob/2.3.0.2/upload/catalog/view/theme/default/template/extension/payment/cod.tpl

If could be that there is some JavaScript in your theme or other payment module that is causing the problem.
