### ISSUE TITLE
Order and Editing an Order Failure

### ISSUE THREAD

**Issue by premudeshi** [opencart/opencart#5319]
Hi,

Everytime I use a test account to order something, after I successfully checkout and go to the orders  in the admin panel, the order shows in the "Missing Order" Filter. When I attempt to change the status, and save it gives me this error:

`SyntaxError: Unexpected token < in JSON at position 0
OK
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function check() on null in /Applications/XAMPP/xamppfiles/htdocs/educraft/catalog/model/checkout/order.php:267
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/educraft/system/engine/loader.php(178): ModelCheckoutOrder-&gt;addOrderHistory('7', '2')
#1 /Applications/XAMPP/xamppfiles/htdocs/educraft/system/engine/proxy.php(25): Loader-&gt;{closure}(Array, Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/educraft/catalog/controller/api/order.php(697): Proxy-&gt;__call('addOrderHistory', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/educraft/system/engine/action.php(51): ControllerApiOrder-&gt;edit()
#4 /Applications/XAMPP/xamppfiles/htdocs/educraft/catalog/controller/startup/router.php(25): Action-&gt;execute(Object(Registry))
#5 /Applications/XAMPP/xamppfiles/htdocs/educraft/system/engine/action.php(51): ControllerStartupRouter-&gt;index()
#6 /Applications/XAMPP/xamppfiles/htdocs/educraft/system/engine/front.php(34): Action-&gt;execute(Object(Registry))
#7 /Applications/XAMPP/xamppfiles/htdoc in <b>/Applications/XAMPP/xamppfiles/htdocs/educraft/catalog/model/checkout/order.php</b> on line <b>267</b><br />
`

**Comment by ManoelVidal** [comment]
What version of your OpenCart?

**Comment by premudeshi** [comment]
2.3.0.2

**Comment by danielkerr** [comment]
not ur personal q&A
