### ISSUE TITLE
OC 3.0.0.0-alpha: config_language bug

### ISSUE THREAD

**Issue by hauso** [opencart/opencart#5331]
Catalog value of config_langue is not properly set
$this->registry->get('config')->get('config_language') contain incorrect value
$this->registry->get('config')->get('config_language_id') is OK
$this->registry->get('session')->data['language'] is OK

**Comment by danielkerr** [comment]
$this->config->get('config_language')

is only used on one page in the admin to make sure it snot deleted.

its not required!! 

do post stupid fixes for non issues ! u are wasting my time with your stupid commits!

$this->session->data['language'] is used for language config!

**Comment by hauso** [comment]
probably because i tried to fixed stupid logic ...
