### ISSUE TITLE
Maintenace mode issue

### ISSUE THREAD

**Issue by akzogibbs** [opencart/opencart#5334]
I can't seem to find this issue on any other threads on here...
I have installed two separate clean versions of OC Version 2.3.0.2 and on both installations i am unable to see the site even when logged in as admin. It's as if the site isn't logging that an admin has logged in?

Could this be an issue with my hosting provider or could this potentially be a bug? 
This is the only place i can find a mention of the issue on the OC forum http://forum.opencart.com/viewtopic.php?f=181&t=173152

Thanks

Stephen

**Comment by danielkerr** [comment]
dont use subfolders use sub domains

**Comment by barkeyo** [comment]
Hi Daniel,

Appreciate the recommendation not to use subfolders, and although I initially did, my OC 2.3.0.2 site was transferred to the public_html root to complete the upgrade process (from 1.5.6.4). Both of the config.php files (root and admin) and the .htaccess file were edited to ensure the correct paths were present. The /test subfolder was then deleted in its entirety. I now have just the main site resident in the root, and I still cannot view the site normally when logged in as admin with maintenance mode on. Everything else works just fine.

The issue still persists even after performing a completely fresh install of OC directly into the web root, as I originally indicated in the forum post that the OP (akzogibbs) links to above.

Any ideas why?
