### ISSUE TITLE
OC 3 session.php registry variable  Undefined variable

### ISSUE THREAD

**Issue by agtt** [opencart/opencart#5335]
Bug : 
Notice: Undefined variable: registry in C:\xampp\htdocs\oc3\catalog\controller\startup\session.php on line 29

File :   catalog/controller/startup/session.php

Error code  : 		if ($this->config->get('session_engine') == 'db') {
				$handler = new $class($registry);
			} else {
				$handler = new $class($registry);
			}
			

Fix : 

		if ($this->config->get('session_engine') == 'db') {
				$handler = new $class($this->registry);
			} else {
				$handler = new $class($this->registry);
			}

**Comment by danielkerr** [comment]
Duplicate

**Comment by RaidoDev** [comment]
Which # does this duplicates?

**Comment by danielkerr** [comment]
API bug

**Comment by danielkerr** [comment]
It's already fixed, I just haven't committed.
