### ISSUE TITLE
Api bug

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#5341]
If not added ip to api_ip table the error appear:

> PHP Notice:  Indirect modification of overloaded property ControllerStartupStartup::$session has no effect

In startup session, if api_query return nothing, the session missing. There should be an error for ip or remove api_ip table and look only in api_session table for ip.

**Comment by danielkerr** [comment]
good point i fogot i added it manually

**Comment by danielkerr** [comment]
added ur fix manually thx!

**Comment by danijelGombac** [comment]
I have still problem with session startup in catalog. If i open order edit page and left it open for a while and then try to continue i got the error. Look at my open PR. This fix the error. You used just a part of PR.

**Comment by danielkerr** [comment]
should be ok now
