### ISSUE TITLE
Request feature: track searched keyword of item, customer information(browser, devices and minute)

### ISSUE THREAD

**Issue by uchsarath** [opencart/opencart#5350]
Hi,
I think it might not be the right place to request the feature. There are a few benefits that I think the shop owner prefer to understand from customer, those should be **what kind of item** that customer searched on website and **how many times that keyword were searched** (those will give the admin to know which item are on demand), information of devices and browser. I believe everyone prefer to build someone that match to what customer want to use.

I don't know whether those are available in 3.0 or you guy are planning to do it?

Thanks,

**Comment by hauso** [comment]
Hi uchsarath, 
you can buy module with this (or similarly) functionality.
search in marketplace: 
https://www.opencart.com/index.php?route=marketplace/extension

for feature request is better to use forum
https://forum.opencart.com/viewforum.php?f=32

Kind regards,
HausO
