### ISSUE TITLE
OC3.0.0.0_a1 Extension installer is broken

### ISSUE THREAD

**Issue by hauso** [opencart/opencart#5351]
Extension installer is broken (probably know)

And newly is missing support for install.php and install.sql files?
I'll update my comment later...

**Comment by danielkerr** [comment]
for SQL u need to first create a extension files under one of the extension categories and add a install method. include the sql in their.

im going o write a user guide

**Comment by uksitebuilder** [comment]
Not sure if it is my localhost, but I am unable to reupload an extension with the same filenames that were previously uploaded (e.g. an extension update), I get an error/warning stating such and such a file already exists.

Obviously this will prevent extensions being able to upgrade in the future

Correct me if it purely a problem my end

**Comment by danielkerr** [comment]
try uninstalling before installing a new version

**Comment by hauso** [comment]
Now is it less user friendly.
In OC2.x I have logic which install and configure module right out the box.
Now in OC3 user must do install action by them self, 
what will higher load on user support for more sophisticated extensions.

**Comment by uksitebuilder** [comment]
Not sure you understood my post.

I was talking about the files from the upload directory in the ocmod zip

Once installed, at least for me, it is not possible to install an ocmod.zip containing those same files.

As this will be on the cloud, there will be no way delete the files from the previous upload directory by ftp.

Do we have to add a test @unlink for every file when a user installs/uninstalls
