### ISSUE TITLE
Order delete no stock added

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#5353]
Now we can delete order from admin order model, but i can not find where product stock is added back, before the order was deleted.

**Comment by danielkerr** [comment]
if the order is voided first it will

**Comment by danijelGombac** [comment]
Ok, but what is the point of delete multiple order, if we needed to voided it first. Is quickest delete it with the button in the order list, like before.

**Comment by danielkerr** [comment]
yes i will come up with a solution

will have to be done via the api though
