### ISSUE TITLE
OC 3.0.0.0-alpha upload_tmp_dir issue on many webhosts

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#5354]
In file admin/controller/marketplace/installer.php (and others) it uses the expression

ini_get('upload_tmp_dir')

e.g.

```
$file = ini_get('upload_tmp_dir') . '/install.tmp';
```

On many webhosts, the **upload_tmp_dir** is not set, and it won't be possible to set this value in the 'php.ini' nor in the '.htaccess'.

Please go back to the solution you had in OpenCart 2.3.0.2, e.g. something like

```
			// If no temp directory exists create it
			$path = 'temp-' . token(32);

			if (!is_dir(DIR_UPLOAD . $path)) {
				mkdir(DIR_UPLOAD . $path, 0777);
			}
```

**Comment by uksitebuilder** [comment]
I second this.  Was also getting the same error, but managed to set upload_tmp_dir via httpd conf directive.

Now getting a new error:

PHP Fatal error:  Call to a member function getModificationByCode() on a non-object in admin/controller/marketplace/install.php on line 315

**Comment by mhcwebdesign** [comment]
@uksitebuilder: Looking at the 'adminb/controller/marketplace/install.php' on line 315 I can confirm your issue, it needs to be preceeded by a

```
$this->load->model('setting/modifcation');
```

However, this is another issue and has nothing to do with the one I reported here, namely the one with the lack of a properly **upload_tmp_dir** setting on many webhosts.

**Comment by uksitebuilder** [comment]
Yes, I confirmed your issue and after manually fixing it by setting upload_tmp_dir via http conf, the next issue to follow after fixing the upload_tmp_dir is  what I posted

**Comment by danielkerr** [comment]
Ok will change

**Comment by danielkerr** [comment]
Annoying though as any uploads should be in a folder outside of the web directory

**Comment by danielkerr** [comment]
so where do uploaded files got to?

move_uploaded_file

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/commit/c2b7342c3ca84ad5488b9653709f836266e86de9
