### ISSUE TITLE
Worldpay Duplicate Orders/Payments

### ISSUE THREAD

**Issue by nturne** [opencart/opencart#5355]
We have an issue where customer payments are being duplicated in the Worldpay account. The store is built on OpenCart version 2.1.0.2 and so I have experimented on a fresh installation of that version using the default theme. I have enabled the standard 'Worldpay Online Payments' extension and configured it to the Worldpay test account, but have made no further modifications or customisations (ocmod/vqmod/extensions). What I have found is that if the order confirmation button is double-clicked then the payment appears twice in Worldpay (with the same OpenCart order number), but only the once in the OpenCart back office (but with two entries in that order's 'Order History'). I have also repeated the experiment on an OpenCart version 2.3.0.2 store with the same outcome. I have attached a shot of the Worldpay account.
![worldpay](https://cloud.githubusercontent.com/assets/16684507/24870146/472b4c3c-1e0d-11e7-8e6c-2aff7292abf7.png)

**Comment by danielkerr** [comment]
ask in the forum, this is for the dev branch
