### ISSUE TITLE
2.3.0.3_rc Undefined index & variable

### ISSUE THREAD

**Issue by mallone** [opencart/opencart#5362]
On OC 2.3.0.3_rc

Undefined index & variable in Extensions/Menu
Notice: Undefined index: user_token in C:\xampp\htdocs\3000\admin\controller\extension\extension\menu.php on line 55Notice: Undefined index: user_token in C:\xampp\htdocs\3000\admin\controller\extension\extension\menu.php on line 109Notice: Undefined index: user_token in C:\xampp\htdocs\3000\admin\controller\extension\extension\menu.php on line 110Notice: Undefined index: user_token in C:\xampp\htdocs\3000\admin\controller\extension\extension\menu.php on line 112

and

Notice: Undefined variable: menus in C:\xampp\htdocs\3000\admin\view\template\extension\extension\menu.tpl on line 23

**Comment by danielkerr** [comment]
already been fixed on the dev branch
