### ISSUE TITLE
Order mail

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#5363]
I don't have time to check, but from what can i see from the code. 

The order add and edit mail are sended before the status is changed in addOrderHistory function.

But the mail functions use the order status name from order_info. 

`$data['order_status'] = $order_info['order_status'];`

I think this are old statuses, the mail should use $order_status_id.

```
$order_status_query = $this->db->query("SELECT * FROM " . DB_PREFIX . "order_status WHERE order_status_id = '" . (int)$order_status_id . "' AND language_id = '" . (int)$order_info['language_id'] . "'");
	
if ($order_status_query->num_rows) {
	$order_status = $order_status_query->row['name'];
} else {
	$order_status = '';
}
```

**Comment by danijelGombac** [comment]
There is another problem with order_status_id.

Inside addOrderHistory order_status_id can change in:

`$order_status_id = $fraud_status_id;`

And the wrong status in sended out.

**Comment by danijelGombac** [comment]
There should be after event.

**Comment by danijelGombac** [comment]
I try the addOrderHistory after even and is working. In the and of fuction addOrderHistory i try 

`return $order_info['order_status'];`

and in the after event

```
if ($output) {
	$last_status_id = $output;
} else {
	$last_status_id = 0;
}
```

What do you think?

**Comment by danielkerr** [comment]
ok i just tested this after some changes i did previous in onbe of the other commits it seems to be working now.

**Comment by danielkerr** [comment]
I think the complete order status would get set out regardless. 

maybe need a 2nd email to go out if the order does appear to be fraud. or putting the fraud code in a before event for addOrderHistory

**Comment by danijelGombac** [comment]
Maybe add after email to alert admin that order status change to fraud.
