### ISSUE TITLE
Sale price is not shown for Logged-in users

### ISSUE THREAD

**Issue by jimmypinto** [opencart/opencart#5367]
I have few products in 'Hot buys' and 'Recommended' section which are on sale. I've added discount price on discount tab and added user group. The offers(regular price and sale price) are visible only to visitors and they login, the offers are not showing up.
Any help would be appreciated.

**Comment by RaidoDev** [comment]
@jimmypinto  Please, ask for the support here: https://forum.opencart.com/viewforum.php?f=190
