### ISSUE TITLE
featured/latest product module with (select)option

### ISSUE THREAD

**Issue by zmrfzn** [opencart/opencart#5369]
add to cart option in featured/latest product module with (select/radio)options does not work. 
it trips and rewrites the URL with product name and resets the page location to top of page.

opencart version- 2.1.0.1

is there any simple fix for this issue ?

**Comment by mhcwebdesign** [comment]
Works fine on my OpenCart test server, unable to reproduce your error without further details.

**Comment by zmrfzn** [comment]
@mhcwebdesign add drop down options on a product and add that in a featured products module on home page and try adding to cart directly from featured module on home.

**Comment by mhcwebdesign** [comment]
If a featured product has options, then the 'Add toCart' won't add it immediately to the cart, rather, it redirects to the product page where the use then has to choose the options before he can add the product to the cart. This is how it's designed.

**Comment by zmrfzn** [comment]
werid. 
i just installed a freshcopy in my local box and its working as you described. 
how ever i made the same fix for my site by changing the code.
