### ISSUE TITLE
upload ocmod.xml file not working 3.0.0.0

### ISSUE THREAD

**Issue by scf8127** [opencart/opencart#5374]
Hi

we try to upload abcd.ocmod.xml file to upload but it send Error

http://prntscr.com/ex34lh

thanks

**Comment by mhcwebdesign** [comment]
Unless you can provide some more details on how to reproduce this error nobody will fix it, and Daniel will just close this issue.

**Comment by danielkerr** [comment]
What u have uploaded is not a zip file I think
