### ISSUE TITLE
What is the purpose of `oc_order_custom_field` table?

### ISSUE THREAD

**Issue by iwat** [opencart/opencart#5378]
I saw this table being created but there is no code using this table. So:

- What's its purpose?
- Can I use this table to store order's custom fields for extension usage?
- What is the value of `custom_field_id` and `custom_field_value_id` (they are NOT NULL)? _I saw that the table `order_field` was been dropped from `upgrade/1004.php`._

**Comment by danielkerr** [comment]
I need to check but should store the field names custom fields

**Comment by iwat** [comment]
Wow, that commit explains everything. 👍
