### ISSUE TITLE
$_['text_extension'] OC2.3.0.3_rc few more missing

### ISSUE THREAD

**Issue by waxedperfection** [opencart/opencart#5388]
Hello,

I see you added a few $_['text_extension']   = 'Extensions'; but noticed a few more are missing from the language files:

Default Admin, 2.3.0.3_rc 

$_['text_extension']   = 'Extensions';

AREAS: 

/admin/language/en-gb/extension/total/ ALL WITHIN HERE
/admin/language/en-gb/extension/theme / ONE WITHIN HERE

hope this helps.

**Comment by danielkerr** [comment]
this is fixed on the dev branch if u want to use the language files from the extensions on there

**Comment by waxedperfection** [comment]
@danielkerr Thank you for getting back to me, im still very new to Github and just finding me feet11, i have look in the following location

https://github.com/opencart/opencart/blob/master/upload/admin/language/en-gb/extension/total/total.php

and i didnt see $_['text_extension'] = 'Extensions'; listed i take it im looking in the wrong place?

Thank you for your help.

Ste

**Comment by waxedperfection** [comment]
@danielkerr forget that, a little more looking around and i found the drop down box that allow you to see the Dev Branch. thank you for your advice once again.

https://github.com/opencart/opencart/blob/dev/upload/admin/language/en-gb/extension/total/total.php

Ste
