### ISSUE TITLE
Facebook share is not working  OpenCart 2.3.0.2

### ISSUE THREAD

**Issue by webcorvo** [opencart/opencart#5389]
The share of Facebook is not working ..
The message is ... Sorry, this feature is not available at this time: There was an error processing this request. Please try again later.

![fb_error](https://cloud.githubusercontent.com/assets/13003770/25292379/c33ad2a2-26cd-11e7-921c-6b8e5c16cba3.png)

**Comment by magicbit** [comment]
check your app_id

**Comment by webcorvo** [comment]
Where i can find that :o(, sorry i am new in opencart

**Comment by webcorvo** [comment]
Tks i allreday done!
