### ISSUE TITLE
Order confirmation send on checkout Step 5 instead of Step 6

### ISSUE THREAD

**Issue by tom1989** [opencart/opencart#5398]
When I'm on **Step 5: Payment Method** and click 'Continue' button, the store sends me order confirmation email. That's wrong behaviour, because it should send this email on **Step 6: Order Confirmation**, when I click 'Confirmation' button. Can anyone explain me how the checkout process works in Opencart and what can cause the problem?
http://www.flower-garden.pl

**Comment by danielkerr** [comment]
i think this is an iossue with what ewver code you have changed because this is not functionality of opencart.com

**Comment by danielkerr** [comment]
i dont even know which gatreway
