### ISSUE TITLE
update order issue

### ISSUE THREAD

**Issue by elvessisante** [opencart/opencart#5407]
Dear sir i would like to ask i have error in admin panel this error show if i have new order or if press the order and make some update this error come form order_info.tpl

https://scontent-mxp1-1.xx.fbcdn.net/v/t1.0-9/18199267_2310607725831048_847711056492907018_n.jpg?oh=d8ca09514b25f939d997014326f84149&oe=59B9F8F3

**Comment by danielkerr** [comment]
please use the forum
