### ISSUE TITLE
two title in the image

### ISSUE THREAD

**Issue by kagan94** [opencart/opencart#5409]
Hi, here is a duplication (two "**title**"):
File "catalog/view/theme/default/template/product/product.tpl":
`<li><a class="thumbnail" href="<?php echo $popup; ?>" title="<?php echo $heading_title; ?>"><img src="<?php echo $thumb; ?>" title="<?php echo $heading_title; ?>" alt="<?php echo $heading_title; ?>" /></a></li>`

And also here "catalog/controller/product/product.php":
` if ($product_info['image']) { 
	$data['popup'] = $this->model_tool_image->resize($product_info['image'], $this->config->get($this->config->get('config_theme') . '_image_popup_width'), $this->config->get($this->config->get('config_theme') . '_image_popup_height'));
} else {
	$data['popup'] = '';
}
if ($product_info['image']) {
	$data['thumb'] = $this->model_tool_image->resize($product_info['image'], $this->config->get($this->config->get('config_theme') . '_image_thumb_width'), $this->config->get($this->config->get('config_theme') . '_image_thumb_height'));
} else {
	$data['thumb'] = '';
}`

Can be rewritten in such way:
`if ($product_info['image']) {
	$data['popup'] = $this->model_tool_image->resize($product_info['image'], $this->config->get($this->config->get('config_theme') . '_image_popup_width'), $this->config->get($this->config->get('config_theme') . '_image_popup_height'));
	$data['thumb'] = $this->model_tool_image->resize($product_info['image'], $this->config->get($this->config->get('config_theme') . '_image_thumb_width'), $this->config->get($this->config->get('config_theme') . '_image_thumb_height'));
} else {
	$data['popup'] = '';
	$data['thumb'] = '';
}`

**Comment by danielkerr** [comment]
one is the title for light box
