### ISSUE TITLE
Incorrect file type when uploading SVG image

### ISSUE THREAD

**Issue by LauraPa88** [opencart/opencart#5411]
Hi all,

I'm using opencart 2.1.0.2 and I am trying to upload a svg logo image. I have checked in system-> Settings and my Allowed File Extensions: has svg. My Allowed File Mime Types: has image/svg and image/svg+xml. Every time i go to upload the image i get warning incorrect file type. Does anyone know how to get this working?

Thanks in advance

**Comment by LauraPa88** [comment]
why did you closed it ????

**Comment by LauraPa88** [comment]
because OPENCART sucks or what?

**Comment by webcorvo** [comment]
Hi Laura,
Don't be rude :o(
The solution is simple, just convert .svg file to .jpg ;o)

**Comment by danielkerr** [comment]
@LauraPa88 you are a moron! svg is not an image format!

**Comment by webcorvo** [comment]
@danielkerr  you have total rigth! as all we know is one XML-based vector.
That's the reason i said to @LauraPa88 for convert!

**Comment by LauraPa88** [comment]
ohhhh really you so fucking smart :D:D:D there are people that are learning and the moron are you @danielkerr because you cant explain what is wrong, you are simple minded and just close the issue !!! You are definitely not corresponding with attitude for you age!

**Comment by LauraPa88** [comment]
I really think that your position here have to be re-evaluated

**Comment by webcorvo** [comment]
@LauraPa88 you have reason ... SVG is a type of image

**Comment by LauraPa88** [comment]
i think that is normal to ask and to be answered not to be aggressive and curst at for something that you don't know

**Comment by LauraPa88** [comment]
thank you @webcorvo 
 and ?

**Comment by webcorvo** [comment]
You realy nedd to use .svg files?
Is for becouse when the client use mobile?

**Comment by LauraPa88** [comment]
No i just want visual quality.

**Comment by webcorvo** [comment]
I will install your version and try to see the error.
Give me 15 min ;o)

**Comment by LauraPa88** [comment]
you are wonderful :) the world needs to have more people like you

**Comment by LauraPa88** [comment]
![screen shot 2017-05-04 at 17 02 18 copy](https://cloud.githubusercontent.com/assets/28390648/25707351/ef06edf8-30eb-11e7-9dcf-8fdd297e965c.jpg)

**Comment by webcorvo** [comment]
You have reason should be work :o(
I' trying to check the source code ... 
Maybe will take a longer more :o( sorry

**Comment by webcorvo** [comment]
I have change the code and already can upload the image.
Can you send me one original .svg file?
I convert one on-line but i think is not ok :o(

**Comment by webcorvo** [comment]
@LauraPa88 I already saw the problem ...

OC don´t suport svg files. The reason is because is a xml base and OC can´t show the .svg file.

That´s the reason why @danielkerr close the issue and sad that is not a image ...

Try to upload the images with full resolotion ;o)

**Comment by LauraPa88** [comment]
@webcorvo Thank you :) i have read at many places that OC do not support SVG but the thing that confused me is that in the Allowed File Extensions there are SVG and SVGZ included

**Comment by webcorvo** [comment]
I agree with you ... 
Maybe is only for create templates check this ... https://forum.opencart.com/viewtopic.php?f=21&t=85583
But you must upload the file  via FTP ( /image/ folder ) :o(

**Comment by OpenCartAddons** [comment]
@LauraPa88 The allowed file extensions field is related to the product option type "File".  It controls what file types customers can upload.

Cheers,
Joel.

**Comment by danielkerr** [comment]
@OpenCartAddons don't reply to this guy hes a scumbag
