### ISSUE TITLE
[3.0.0.0] ocMod modifications don't work on admin-side .twig files

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#5414]
The catalog-side .twig files seem to work fine, but the admin-side ones don't. This fix seems to work:

------------------------------------------------------------------------------
IN:
/system/modification.xml

REPLACE BOTH INSTANCES OF:
DIR_MODIFICATION . 'admin/view/'

WITH:
DIR_MODIFICATION . 'admin/view/template/'
------------------------------------------------------------------------------

**Comment by kumar-Sachin** [comment]
i wnat to add a field in product data tab but i am not gettig add ,delete and replace any field. i am doing this by xml file..
