### ISSUE TITLE
Opencart 3.0.0.0 - Modification upload error

### ISSUE THREAD

**Issue by ocdevops** [opencart/opencart#5415]
Hi,
I tried to upload my extension with Extension Installer, but I got this error:
The directory catalog/controller/myfolder is not allowed to be written to!
and
The directory system/engine/ is not allowed to be written to!

How can I upload my controllers and my custom base controller?
Which folders are allowed to add files?

Opencart version: 3.0.0.0.

Thanks for your help

**Comment by danielkerr** [comment]
U should use events to override the controller calls to use the extension folders

**Comment by danielkerr** [comment]
I'm going to write a guide

**Comment by ocdevops** [comment]
Thanks for your fast response.

**Comment by selotoprak** [comment]
i have the same error - 
The directory system/engine is not allowed to be written to!

**Comment by farhadniaz** [comment]
I have that error too

**Comment by osworx** [comment]
Simple: admin/controller/marketplace/install.php:

>// A list of allowed directories to be written to
				$allowed = array(
					'admin/controller/extension/',
					'admin/language/',
					'admin/model/extension/',
					'admin/view/image/',
					'admin/view/javascript/',
					'admin/view/stylesheet/',
					'admin/view/template/extension/',
					'catalog/controller/extension/',
					'catalog/language/',
					'catalog/model/extension/',
					'catalog/view/javascript/',
					'catalog/view/theme/',
					'system/config/',
					'system/library/',
					'image/catalog/'
				);

But what I do really not understand: you all are developing.
What?
For OpenCart .. ?

Then you should read the code before posting such stupid questions.

**Comment by Lavkushwaha** [comment]
it worked . thank you osworx

**Comment by danielkerr** [comment]
u also need to use events to call override the calls to files or folders that are not there.

**Comment by klesun** [comment]
Relevant link I guess: https://github.com/opencart/opencart/wiki/Extension-System

> In version 3.0 we have added some additional path restrictions so extensions being installed will not cause issues when uninstalling.
