### ISSUE TITLE
User password length is restricted to 20 characters

### ISSUE THREAD

**Issue by bmwalters** [opencart/opencart#5416]
![](https://i.imgur.com/2hY0vy5.png)

## Steps to Reproduce:
1. Visit https://demo.opencart.com/index.php?route=account/register
1. Fill in the form fields. When you get to the password fields, use some string longer than 20 characters such as `abcdefghijklmnopqrstuvwxyz`
1. You will receive an error stating that the "Password must be between 4 and 20 characters!"

## Why this is a Problem
Users should be encouraged to use strong passwords, and those who do use strong, lengthy passwords should not be prevented from doing so on sites using OpenCart.

According to my limited understanding of the OpenCart project, this maximum length restriction seems arbitrary. The project appears to use the SHA-1 hashing algorithm which seems to allow inputs much larger than 20 characters + whatever length salt you are using.

**Comment by webcorvo** [comment]
hi @bmwalters i think if you have a 20 characters password is already strong enofe , why more ?!

**Comment by bmwalters** [comment]
@webcorvo Sure, a 20 character password may be very strong. However security isn't something you should put a cap on. If a user wants to be more secure than you or I deem acceptable, let them.

Let's say a user follows a password scheme where they do something like use the name of the site inside of some template (this is fairly insecure, but there is a significant number of users who do something similar to this). Let's say their template is a string such as `<sitename>-bookshelf-parabola`. They happily use this for services like gmail (`gmail-bookshelf-parabola`) and GitHub (`github-bookshelf-parabola`). When they encounter a site running OpenCart, they attempt to use `foo-bookshelf-parabola` only to discover that they must deviate from their existing pattern and remember this deviation. It's simply an inconvenience to users.

But here's a different counter: Why 20 characters? There is no reason for the limit to be 20. It's arbitrary. Why can't it be raised? It would make more sense if the limit was 71 or 72 characters as that is the maximum allowed by the bcrypt algorithm (even though OpenCart isn't using bcrypt), but sha1's upper limit is something like 2^60 which makes 20 characters very unreasonable.

**Comment by jamesallsup** [comment]
I quite agree with the fact 20 chars is too short - so I will look at this and discuss with Daniel. It has become a common understanding that the randomness of password will only carry the strength so far - it is better to have a far longer (still randomised) password. Some sites I either dislike the look of or not 100% sure on I will use the [LastPass](https://lastpass.com/f?17068812 ) tool and assign a LONG, RANDOM and SINGLE time password for it that I don't use on any other site. And I usually set it to the max unless the site complains. It pisses me off when sites enforce "it must be 8 characters, with a capital and 2 numbers" - that's not security, its giving the bots a head start!

**Comment by webcorvo** [comment]
ok @bmwalters you have reason, but is easy to change the code and give no limit to put password, i will tell you soon how you can do that

**Comment by webcorvo** [comment]
You just change the **protected function validate()**

**FROM:**
protected function validate() {
if ((utf8_strlen($this->request->post['password']) < 4) || (utf8_strlen($this->request->post['password']) > **20))** 
{
$this->error['password'] = $this->language->get('error_password');
}

**TO**

protected function validate() {
if ((utf8_strlen($this->request->post['password']) < 4) || (utf8_strlen($this->request->post['password']) > **40))** 
{
$this->error['password'] = $this->language->get('error_password');
}

**ATENCION** - the database table **oc_customer**  field as one **varchar(40)**
If you want more just change ;o)

In this flies: 

- catalog\controller\account\password.php:
- catalog\controller\account\register.php
- catalog\controller\account\reset.php
- catalog\controller\affiliate\password.php
- catalog\controller\affiliate\register.php
- catalog\controller\checkout\register.php

I hope this help :)

**Comment by danielkerr** [comment]
ok updated

**Comment by sputnik-1** [comment]
Following on from this could we have the username field updated to 40 characters as well please.

```
CREATE TABLE `oc_user` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_group_id` int(11) NOT NULL,
  `username` varchar(20) NOT NULL,
  `password` varchar(40) NOT NULL,
...
```
TIA

Keith

**Comment by zemguru** [comment]
@danielkerr `error_password` also must be updated. 
https://github.com/opencart/opencart/search?utf8=%E2%9C%93&q=Password+must+be+between+4+and+20+characters&type=

**Comment by danielkerr** [comment]
I will decide what needs updating. U don't run the project

**Comment by zemguru** [comment]
I was just noting the issue, as language strings haven't been changed....
