### ISSUE TITLE
API List orders (filtered by date and/or status)

### ISSUE THREAD

**Issue by RichardMarchant** [opencart/opencart#5423]
It appears the API is very limited in functionality. Being able to list orders (ideally filtered by date and/or status) would be extremely useful.

Currently the only way to get the orders via the API is to request one order at a time by ID (route api/order/info) starting with ID 1 and incrementing until you hit a 404 and hope no IDs have been skipped or deleted. And to keep doing that every time you poll the API, not a good solution.

**Comment by webcorvo** [comment]
I have delete de api!!! as conflict is paypal checkou

**Comment by roballport** [comment]
Can't you filter the API response from within your app? I've just used a small amount of the Opencart API in a small Laravel project without issue - I used Laravel's collection class to do all my filtering.

**Comment by webcorvo** [comment]
I will try do create a new one after i configure paypal

**Comment by danielkerr** [comment]
a feature request

**Comment by mehov** [comment]
To anyone looking into this, coming from a search engine.

@RichardMarchant submitted a pull request #5429 back in 2017, which had been rejected by @straightlight (who no longer seems to be active here) saying *the code introduces automated scripts automated scripts to capture specific information from the users without their consent, which is against GDPR, therefore denied*. More info on the linked pull request.

**Comment by mhcwebdesign** [comment]
It should be easy enough to port one of the existing RESTful API extensions from OpenCart 3 to OpenCart 4 and then publish it as an extension.
