### ISSUE TITLE
it wont let me join sever it says failed to create a dump file

### ISSUE THREAD

**Issue by cool1906** [opencart/opencart#5427]
but i dont have the lastest save file

**Comment by cool1906** [comment]
why is it closed

**Comment by RaidoDev** [comment]
there is no way someone can understand your issue description ....

**Comment by cool1906** [comment]
it means failed to create dump please file an issue with open rct2 on githb that what it says when i try to join

**Comment by prhost** [comment]
?

**Comment by Gymnasiast** [comment]
@RaidoDev @prhost This user intended to file an issue against OpenRCT2/OpenRCT2...

**Comment by cool1906** [comment]
?

**Comment by RaidoDev** [comment]
@cool1906 it seems, You have posted in INCORRECT project. Did you mean: https://github.com/OpenRCT2/OpenRCT2
Double check the project address!
