### ISSUE TITLE
Paypal Express dont´t work if i have API OC

### ISSUE THREAD

**Issue by webcorvo** [opencart/opencart#5430]
Hi,
In OC Version 2.3.0.2, the paypal Express only works if i delete de OC API

The problem is when i want to update orders status, i can´t,  because i don´t have OC API

How can i fix this?
Tks

**Comment by danielkerr** [comment]
no idea.

**Comment by danielkerr** [comment]
i know paypal have just updated their extension in the dev branch and its all been retested.
