### ISSUE TITLE
In delivery method the system show "UnrecoverableClientError".

### ISSUE THREAD

**Issue by Ivanlee1234** [opencart/opencart#5431]
I received this message in error log:
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Server</faultcode><faultstring xml:lang="en">Fault</faultstring><detail><cause>UnrecoverableClientError</cause><code>SchemaError</code><desc>validation failure for RateRequest Error:cvc-enumeration-valid: Value 'G' is not facet-valid with respect to enumeration</desc></detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
Anyone can help me to solved it?

**Comment by DanielOizumi** [comment]
I'm on version 2.2.0.0 and in my case I fixed making sure that the weight class was in Kilogram on all 3 places (System>Settings>Local, Extensions>Shipping>Fedex and Catalog>Products>Data) .
