### ISSUE TITLE
Can change from non standard Insert into Set queries to Insert Values?

### ISSUE THREAD

**Issue by maplewang** [opencart/opencart#5435]
I have checked on code, there are lots of Insert into Set queries, those are non standard query, should use Insert into values pair, that will help other database support on Opencart,.
http://stackoverflow.com/questions/6973846/insert-into-set-syntax-in-sql-server

I have changed a lot of them, if you like I will submitted, I have left the original query at the above line, so you can compare one by one.

**Comment by danielkerr** [comment]
thats only your op ion! i stop posting your suggestions! post some where on the opencart forum when i will never read it..

**Comment by RaidoDev** [comment]
@maplewang give me a message to my mail on this one, please, I need a solution also.
