### ISSUE TITLE
Suggest Use PHP date() to write back sql query instead of NOW() in mysql

### ISSUE THREAD

**Issue by maplewang** [opencart/opencart#5438]
I noticed some queries included more Now(), for example one query has 4 Now() in query, if use one date() in php may save more server time.
other database server function LCASE/SHA1 also included, if change those to PHP implementation will help support more database servers.

**Comment by RaidoDev** [comment]
@maplewang Check out these suggestions:

https://github.com/opencart/opencart/issues/5287

especially about  ```now()``` https://github.com/opencart/opencart/issues/5287#issuecomment-287351269
