### ISSUE TITLE
Rating Total On Extension Info Page

### ISSUE THREAD

**Issue by OpenCartAddons** [opencart/opencart#5440]
The total number of ratings should be displayed next to the stars on the extension information page, similar to the extension list page.  

The rating_total parameter is not currently passed through the API.

**Comment by danielkerr** [comment]
will do

**Comment by Troxya** [comment]
suggestion: replace # reviews by # comments (like it was previously). Ratings are 100% meaningless on OC marketplace. Module changelogs were 100% useful, but disappeared too. My 1 ct feedback that you can happily delete.

**Comment by uksitebuilder** [comment]
I disagree @Troxya number of comments are meaningless - Number of ratings/reviews along with the rating stars is a must

If many people rate an extension and it comes back with 5 stars - this indicates that the extension is popular and the buyers like it

**Comment by OpenCartAddons** [comment]
Both have their place but I would agree that ratings are a bigger deciding factor for customers than comments.

The # of comments is already available and currently displays on the Comment tab.

Regards,
Joel.

**Comment by osworx** [comment]
@uksitebuilder And how many fake votes many extensions have?!
Rating stars are that useless, can never follow comments.
But, comments can be deleted by the author at any time (see always such whenever a 'bad' comment was made) - that should be controlled.

**Comment by OpenCartAddons** [comment]
@osworx This really would only be an issue for free extensions, as commercial extensions require the customer to purchase the extension prior to rating it.

**Comment by danielkerr** [comment]
ok fixed.

**Comment by uksitebuilder** [comment]
I had a free extension that had ~19k downloads now showing only 672

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=4267
