### ISSUE TITLE
Extension Store Notice: Undefined index: review_total

### ISSUE THREAD

**Issue by waxedperfection** [opencart/opencart#5445]
Opencart Version 2.3.0.3_rc

admin/controller/extension/store.php on line 185Notice: Undefined index: review_total

Had a good look around the forum and github with no real clues to find the reason. On line 185 its as follows:

store.php
'review_total' => $result['review_total'],

first time i have seen the error, but could have been there a little time as its not a section i use, only clicked into by mistake today.

Ste

**Comment by danielkerr** [comment]
not sure how this is possiblwee sibnce no marketplace is added to 2.x

**Comment by waxedperfection** [comment]
@danielkerr Thank you for getting back to me, 100% im using Opencart Version 2.3.0.3_rc, with no added admin mods etc, i can drop you a link or screen shot if it would help. 

Admin >> Home >> Extension >> Extension Store

Downloaded from Github around March time 2017

> OpenCart © 2009-2017 All Rights Reserved.
Version 2.3.0.3_rc

**Comment by danielkerr** [comment]
RC means unreleased. So test with the Dev branch for updtodate oc

**Comment by waxedperfection** [comment]
Thank you @danielkerr , like you say not sure how its possible as its OC 2.x  but its defiantly there. :)

Have a good day. 

Ste

**Comment by OpenCartAddons** [comment]
@waxedperfection This error will also display in the dev branch while Daniel updates the API to pass the rating_total to the extension info page.

Cheers,
Joel.

**Comment by waxedperfection** [comment]
@OpenCartAddons Joel, thank you I'm very new to whole github different branches (master / dev) , i was thinking i was best to get the very most upto date version from here. while this seems to be the only part of Opencart Version 2.3.0.3_rc that give me an error, but i can live with it if needs be.

**Comment by danielkerr** [comment]
U should not be using an RC version , so don't post here if it has issues

**Comment by waxedperfection** [comment]
I understand the RC version is not the final release, what i dont understand and i hope you can take a few minutes to explain, is from the main OC download page you can down load the latest release, or it offers you the option of downloading from github, as previous im very new to github and dont really understand whats the most upto date patched version, if i download the master from here its 2.3.0.3_rc , so if its not the best version to use, what would be the best version please?

**Comment by osworx** [comment]
alpha, beta and rc (release candidate) are mainly for developers and those who want to play with it.
For production and real shops, always use the latest (stable) version:
https://github.com/opencart/opencart/releases - marked: **Latest Release**

**Comment by RaidoDev** [comment]
@waxedperfection please, post that kind of question in the forum, or give your contacts so someone can help you in private.
