### ISSUE TITLE
CVE 2017-9089 - Sesion Fixation in Opencart - 2.3.0.2

### ISSUE THREAD

**Issue by 0xd0m7** [opencart/opencart#5446]
Description
It has been detected that it is possible to set the value of the "default" cookie, so an attacker could construct a link specifically designed with a malicious cookie, in order for a legitimate user to open that link and escalate privileges with "the malicious cookie," aka Session fixation.

Additional Information:

#REQUEST
GET /opencart/upload/admin/index.php?default=di5l02rkaskhofh4jt0xd0m7 HTTP/1.1
Cookie: has_js=1;
SESS29af1facda0a866a687d5055f2fade2c=66MQjiREfLOFxzHWZda1pMEXftxSszf1lf_7Hi6s6Nc;
PHPSESSID=k1pemhltuo79jmas6cg7bi64a7;
default=di5l02rkaskhofh4jt0xd0m7;
language=en-gb;
currency=USD

#RESPONSE:
HTTP/1.1 200 OK
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: default=di5l02rkaskhofh4jt0xd0m7; path=/; httponly
Content-Type: text/html; charset=utf-8

Vulnerability Type:
Incorrect Access Control

Affected Product Code Base:
Opencart - 2.3.0.2

Affected Component:
File: /var/www/html/opencart/upload/system/library/session.php
Line 38: session_id $this->session_id = $_COOKIE[$key]
             Requires:
             Line 37: elseif(isset($_COOKIE[$key]))
             Line 34: function start($key = 'default', $value = '')

Reference:
https://www.owasp.org/index.php/Session_fixation

I have already reported to Mitre this vulnerability assigned to the CVE ID 2017-9089, I will wait the patch of this vulnerability. Any additional information requested from me or Mitre.

**Comment by danielkerr** [comment]
accept that there is no used GET perimeter to set the session key so the below would not work.

default=di5l02rkaskhofh4jt0xd0m7;

i dont believe this has been even tested.

**Comment by 0xd0m7** [comment]
Good Morning,
According to the definition of session fixation, it is not necessary to
send the token (default value) to a user through a URL.

• Session token in a hidden form field: In this method, the victim must be
tricked to authenticate in the Target Web Server, using a login form
developed for the attacker. The form could be hosted in the evil web server
or directly in html formatted e-mail.

References:https://www.owasp.org/index.php/Session_fixation

The application does not regenerate the default cookie value once the user
is authenticated in the application, allowing session hijack, and session
fixation.

2017-05-24 12:35 GMT+02:00 Daniel Kerr <notifications@github.com>:

**Comment by danielkerr** [comment]
It does not work with opencart. Did u do any actual testing?
