### ISSUE TITLE
Opencart Old Version not able to download

### ISSUE THREAD

**Issue by shiroamada** [opencart/opencart#5448]
I would like to download version 1.5.1.2
https://www.opencart.com/index.php?route=cms/download/download&download_id=22

but it show a blank page. Can you please help to check.

and 1.5.6 (Latest version) and below all cannot download. Maybe can add into github release as well.

**Comment by trueliarx** [comment]
That version is quite old and probably with bugs (you already know it for sure).

If you really need that older version you can check this (unofficial) mirror:
https://www.bnit.it/opencart-download-releases.php

**Comment by shiroamada** [comment]
thanks! I need the old version for upgrade purpose.
