### ISSUE TITLE
[3.0.0.0] session_save_path() optional arguments cause errors

### ISSUE THREAD

**Issue by ADDCreative** [opencart/opencart#5451]
The session.save_path return by session_save_path() has optional arguments before the actual path on some PHP configurations..

See http://php.net/manual/en/session.configuration.php#ini.session.save-path.

According to the PHP document above session_save_path() could return in the format N;MODE;/path not just the path.

If any of the optional arguments are set in a PHP configuration errors are generated on install such as
```fopen(5;600;/tmp/sessions/sess_0f13dc62ece3df03a519f21438): failed to open stream: Invalid argument in /opencart3/system/library/session/file.php on line 27```

**Comment by danielkerr** [comment]
session_save_path is different from ini_set
