### ISSUE TITLE
Product filter autocomplete does not match on filter group

### ISSUE THREAD

**Issue by raffraffraff** [opencart/opencart#5452]
OpenCart v2.3.0.2. 

#### Issue:
I've added multiple filter groups, each with multiple filters. When I add/edit a product and try to add filters to it, the filter autocomplete only shows 5 items, and the autocomplete does not show items based on the filter group. When there is a large number of products, filter groups and filters, the autocomplete feature pointless at best, a hindrance at worst.

### Example:
**Filter group: filter names:**
Colour:  orange, blue, green, purple, red
Size: XS, S, M, L, XL
Shape: square, circle, triangle, oval

When I add/edit a product and use the filter autocomplete, there is a hard limit of 5 autocompleted filters:
Colour > orange
Colour > blue
Colour > green
Colour > purple
Colour > red

I cannot get the autocomplete to list sizes or shapes by typing 'size' or 'shape'. I have to _know_ that there is a shape called 'square', and actually start typing 's' 'q' before the autocomplete kicks in and completes 'Shape > square' for me. In other words: it's completely pointless to autocomplete what I already had to know.

### Suggestion 1: start to autocomplete based on filter group
I should be able to type 'colour' and have the autocomplete suggest a list of colours, or type 'shape' and have it autocomplete a list of shapes.

### Suggestion 3: only suggest the filter group _until the filter group is typed_, and then suggest _filter names in that group_

**Comment by danielkerr** [comment]
its fine how it is
