### ISSUE TITLE
Opencart 3.0 cannot access extension marketplace while in staging

### ISSUE THREAD

**Issue by lucasjkr** [opencart/opencart#5456]
I develop locally (in VirtualBox), using a .app TLD (i.e. 'opencart.app'). I just installed OC 3.0 to take a look at it, and while I can view extensions in the marketplace, I cannot download or install them in my testing setup - it requires i have an Opencart Marketplace API key, and when I attempt to register my staging domain ('opencart.app') on the opencart site, it says that it's an invalid domain.

Is there a workaround available for this situation (for people who test and develop locally), but want/need access to the marketplace while doing development?

**Comment by lucasjkr** [comment]
Additionally, it might just be that I'm using a build from a few days ago, but i get an undefined index 'rating_total' when accessing same, AND the Admin account created during install didn't have permission to add Marketplace API credentials by default (I had to go to Admin->System->Users->User Groups and add permission to access & modify `marketplace/api`, which isn't checked by default for the admininstrator user group

**Comment by danielkerr** [comment]
yes reworking this now. its still a dev branch.
