### ISSUE TITLE
config.php creation does not escape file path 2.3.0.2 & master

### ISSUE THREAD

**Issue by jbsaige** [opencart/opencart#5459]
When installing v2.3.0.2, if the path contains a single quote this is not escaped when writing the config.php files, resulting in a php error when trying to load the site.

I have confirmed that this is still an issue in the current master.

**Comment by webcorvo** [comment]
Can you tell wath is the error?

**Comment by jbsaige** [comment]
`
Parse error: syntax error, unexpected 's' (T_STRING), expecting ',' or ')' in C:\inetpub\KAL's\opencart\upload\config.php on line 9
`

Line 9 is this:
`
define('DIR_APPLICATION', 'C:/inetpub/KAL's/opencart/upload/catalog/');
`

And should be:
`
define('DIR_APPLICATION', 'C:/inetpub/KAL\'s/opencart/upload/catalog/');
`

**Comment by CoverUp** [comment]
You are right, But who use an apostrophe in the install path for god sake. I would keep just as is, as a way for identify bad paths names, because this probably will cause other kinds of errors.

**Comment by webcorvo** [comment]
This is one more

admin/controller/common/filemanager.php

**Search - line 39**
` if (substr(str_replace('\\', '/', realpath($directory . '/' . $filter_name)), 0, strlen(DIR_IMAGE . 'catalog')) == DIR_IMAGE . 'catalog') {`

**Replace** 
`if (substr(str_replace('\\', '/', realpath($directory . '/')), 0, strlen(DIR_IMAGE . 'catalog')) == DIR_IMAGE . 'catalog') {
`


**Search* -  line 80 and 88**
`implode('  ', $name)`

**Replace**
`implode(' ', $name)  // remove withe space between '' `
