### ISSUE TITLE
Opencart - Customer orders report is working improperly.

### ISSUE THREAD

**Issue by prakannino** [opencart/opencart#5461]
Dear Opencart Team, 

At the moment, I'm using Opencart VERSION : 2.0.1.1 and I am experiencing a problem with **Customer orders report.** 

I've tried to fix this issue but seems it still has a bug that I've found was when I reached 20 orders, the customer orders report doesn't work anymore. 

Could you please take a look on to this matter, please?  

Refer to the link below : 
https://github.com/opencart/opencart/pull/3105
https://github.com/opencart/opencart/commit/e30de743e09537ffdb03455f8a0768dc6342d89f

_Noted: I've tried to fix the file at path : upload/admin/model/report/customer.php by these solution above. But it doesn't work._ 

![customer orders report 1](https://cloud.githubusercontent.com/assets/29037308/26555865/5a0476b4-44c1-11e7-95b8-6c672f60e5fc.png)

![customer orders report 2](https://cloud.githubusercontent.com/assets/29037308/26555868/5fd51eb8-44c1-11e7-9c1c-da2c4af46a95.png)

Thank you for your help in advance.

**Comment by mrnfrancesco** [comment]
The two values showed in your images come from different model and different queries.

The **TOTAL ORDERS** value in the dashboard comes from the `getTotalOrders` function in `upload/admin/model/sale/order.php`, which do the following query:

`SELECT COUNT(*) AS total FROM order`

The **No. Orders** value comes from `getOrders` function in `upload/admin/model/report/customer.php` with the following query which is a bit more complex:

```
SELECT
    t.customer_id,
    t.customer,
    t.email,
    t.customer_group,
    t.status,
    COUNT(DISTINCT t.order_id) AS orders,    <== THIS IS THE PRINTED VALUE
    SUM(t.products) AS products,
    SUM(t.total) AS total
FROM (

    SELECT
        c.customer_id,
        CONCAT(c.firstname, ' ', c.lastname) AS customer,
        c.email,
        cgd.name AS customer_group,
        c.status,
        o.order_id,
        SUM(op.quantity) as products,
        SUM(o.total) AS total
    FROM order o
    LEFT JOIN order_product op ON (o.order_id = op.order_id)
    LEFT JOIN customer c ON (o.customer_id = c.customer_id)
    LEFT JOIN customer_group_description cgd ON (c.customer_group_id = cgd.customer_group_id)
    WHERE o.customer_id > 0 AND cgd.language_id = '<your language id>'

) AS t
GROUP BY t.customer_id
ORDER BY total DESC
```

Now, somewhere a few values get lost; the question is *where*.

* the inner query do a `LEFT JOIN` and the *left table* is **order**, so no row can be lost in this step
* the *where* condition could lost some values only if `o.customer_id` is `<= 0` (it shouldn't I suppose)
* the outer query do a `COUNT DISTINCT` which could let some value behind if it has the same `order_id` of another one during the `GROUP BY`

Now, I can't do any tests by now, but if I could guess what's going wrong I would bet on the `DISTINCT` keyword.

@prakannino you could just try to query your database with `SELECT order_id FROM <your_db_prefix>order` and look for duplicates. If your problem is issued by the `DISTINCT` keyword you should have at least 3 rows with the same `order_id`.

**In that case** try to just remove the `DISTINCT` keyword from the `getOrders` function in `upload/admin/model/report/customer.php`.

Otherwise wait for someone who can test OC code or do the above queries manually and check where the values get lost. The more info you give us the more quickly we can fix the issue.

**Comment by prakannino** [comment]
Hi Francesco Marano, 

Firstly, thank you so much for your comments.

I've tried to remove **_DISTINCT_** keyword from the _**getOrders**_ function in _upload/admin/model/report/customer.php._

But it doesn't work. So, I've just removed all _**DISTINCT**_ keyword from 
- getTotalCredit
- getTotalRewardPoints
- getTotalOrders
- getOrders

And now it seems better, but still not exactly correct. 

It would be great if you could look onto this matter. 

I've attached the file that I am using for getting a customer orders report, 

please see attached : [customer.zip](https://github.com/opencart/opencart/files/1039534/customer.zip)

![customer orders report 3](https://cloud.githubusercontent.com/assets/29037308/26602024/488e49f0-45ac-11e7-967a-7ba378598860.png)

![customer orders report 4](https://cloud.githubusercontent.com/assets/29037308/26602025/48936642-45ac-11e7-92e7-0ee3f5a355b5.png)

Thank you so much in advance.

**Comment by prakannino** [comment]
Just for your information. 

I've just tried the function above that I just told you earlier. 

It seems like, if I had 50 orders. It will be 3 pages.

And will have only 20 (No. orders) in each page. 

Hmm... and the information in **Total** is incorrect as well.

**Comment by mrnfrancesco** [comment]
As I said previously, I cannot do any kind of test by now other than just looking at the code.
By the way, this seems to be a serious bug to me.

@danielkerr what do you think about that?

**Comment by danielkerr** [comment]
I don't consider any report issue to be serious one. The site still take orders correct!

**Comment by prakannino** [comment]
Thank you for your kindness and your effort to fix this bug. @mrnfrancesco 

As far as we know, OpenCart is a very good ones of open source e-commerce system.

If we could solve this bug, it would be working perfectly. 

I've searched more information about this issue and I've found the solution from his commented 

"BrettMW » Thu Feb 26, 2015 3:05 am" 

https://forum.opencart.com/viewtopic.php?f=190&t=135582

It's quite work as good, but the **total** won't include shipping/tax with this fix. 

If anyone could just look onto the calculation. I think we could close this issue though.

**Comment by webcorvo** [comment]
Upgrade to OC Version 2.3.0.2, that work´s fine there ;o)

**Comment by prakannino** [comment]
Hi @webcorvo , 

Thank you for your suggestion. 

I've tried to apply the file customer.php from OC Version 2.3.0.2. 

It seems working but the **total** goes wrong. 

As the picture below, the **total** on _3rd row_ should be just only ฿300.00 

Are there any solution to fix this issue ? 

![image](https://cloud.githubusercontent.com/assets/29037308/26710083/cb0f4984-4781-11e7-8d4b-8b3a45fc81c5.png)

**Comment by webcorvo** [comment]
you have reason!!! i have made a test and is a bug.
I will try to find a solution even for my clientes as well!!
Today i must find that bug! Tks

**Comment by webcorvo** [comment]
hi find the bug! this only happens when the records are multiple of 3!
And the value duplicate ! 
Please @prakannino test if this happen to you too!
Create more 3 clientes and in total stay with 7!

**Comment by prakannino** [comment]
Hi @webcorvo, 

I think the calculation in **Total** it's all wrong.

Please see image below, this information from my client's website. 

Let's take a look onto **2nd** and **3rd** row. those **No. Orders.** and **No. Products.** are still the same as previously image. 

But the values in **Total**  looks very different, right ? 

That why I told you, it's all goes wrong. 

![image](https://cloud.githubusercontent.com/assets/29037308/26719377/7ad9dcd6-47ae-11e7-855f-ca2fd8462594.png)

_Please note : the **total** on image above calculated from product's price. (excluded shipping fee and coupon discount.)_ 

_It would be better if it's include (tax, shipping fee and any discount)_

**Comment by prakannino** [comment]
Just for your information, 

my client's website is running file customer.php from OC Version : 2.0.1.1

**Comment by RaidoDev** [comment]
Isn't this also the problem of  #5467 ?

**Comment by webcorvo** [comment]
7 orders - check the orders total

![order_list](https://cloud.githubusercontent.com/assets/13003770/26722756/4a623ad2-4789-11e7-8d1b-0a866779d1fb.png)

Check the report- when the order is multiple of 3 the total is *2 

![report_orderes](https://cloud.githubusercontent.com/assets/13003770/26722761/51a217e0-4789-11e7-9827-8e260e3ffd6a.png)

**Comment by webcorvo** [comment]
That is for older versions :o(

**Comment by danielkerr** [comment]
ok seem this issue is for old installs.
