### ISSUE TITLE
Uncaught TypeError: $(...).summernote is not a function at index.php:894

### ISSUE THREAD

**Issue by xauth000** [opencart/opencart#5466]
Hello
i am using opencart 2.3.0.2 and pavo style shop theme i customized it .i made mega menu and vertical menu with plugins included in this theme.Every thing was fine. yesterday i wanted to edit my vertical menu .but it is not letting me to add any catoregory in vertical menu.when i edit previous category added in vertical menu.it changes in back end but it doesnt show changes in front end,
then i click on inspect element and found this error.

Uncaught TypeError: $(...).summernote is not a function
    at index.php:894
with url 
index.php?route=/extension/module/pavverticalmenu&token=blablablaaaaaa
![summernote](https://cloud.githubusercontent.com/assets/29099435/26636630/0f073208-4626-11e7-861f-3288aff38d65.png)

i will be very thankful if any body helps me in this regard,Every thing was perfect .
www.sharishari.com is my web name
best regards

**Comment by webcorvo** [comment]
Summernote is a javascript file! - summernote.min.js
Do you have add this file?

**Comment by xauth000** [comment]
Thank you for responding me.@webcorvo

i searched for this file.dont have this file in my project.where can i find this file and how to add it in my web.
best regards

**Comment by webcorvo** [comment]
I think you must have the folder summernote in catalog/view/javascript.
If you don´t have download here https://github.com/summernote/summernote/releases/download/v0.8.4/summernote-0.8.4-dist.zip

**Comment by xauth000** [comment]
@webcorvo mate .i have this folder . summernote in this path which you told me . do i need to update the file?? if it has this folder then why i am having this error

**Comment by webcorvo** [comment]
It was some thing you change :o(

**Comment by danielkerr** [comment]
dont post ur own issues here use the forum!

**Comment by xauth000** [comment]
where is the forum???

**Comment by osworx** [comment]
Cool down mate!
[https://forum.opencart.com/](url)

**Comment by xauth000** [comment]
man @osworx invalid url.

**Comment by osworx** [comment]
Updated.
But when you are able to edit files (see your template), you should also know where OpenCart sits.
And his forum - you have found also this address here ..
Or do you live on the moon?

**Comment by webcorvo** [comment]
@osworx  is not necessary to be rude :o(
@xauth000  just scroll down the page and click search ;o)
