### ISSUE TITLE
  Getting "internal server error" which registering a new account on Checkout page in Opencart 2.3.0.2

### ISSUE THREAD

**Issue by richieseeu** [opencart/opencart#5468]

**Comment by richieseeu** [comment]
please i need he lp on this. i have tried all i could but not working for me

**Comment by richieseeu** [comment]
Getting "internal server error" which registering a new account on Checkout page in Opencart 2.3.0.2. it was working before now until i apply ssl to the domain. can any one tell me what is happening and how to resolve it.

**Comment by RaidoDev** [comment]
Pls, ask in the forum or post some contacts of you.

**Comment by richieseeu** [comment]
my email address is richtechnologies@yahoo.com

**Comment by richieseeu** [comment]
my email address is richtechnologies@yahoo.com please i need help on this internal server error, it started when i implement ssl on it
