### ISSUE TITLE
Paging missing from Affiliate Transaction tab

### ISSUE THREAD

**Issue by beechyrb** [opencart/opencart#5470]
Paging buttons are missing from the Transaction tab on the edit marketing affiliate route.

Route: admin/index.php?route=marketing/affiliate/edit

Screenshot: https://pasteboard.co/dJ9xbgxSd.png

Rich

**Comment by webcorvo** [comment]
Hi, edit file admin/language/en-gb/en-gb.php

line 24: `$_['text_pagination']               = 'Showing %d to %d of %d (%d Pages)';`

change to:

line 24: `$_['text_pagination']               = '%d - %d of %d results';`

I do that in admin and store and stay amazing!!!!!

**Comment by beechyrb** [comment]
@webcorvo Okay but that doesn't solve the issue. That just hides how many pages of results there are.

The issue here is that you can't view all the results because it limits it to 10 results per page and there are 25 with no next and previous buttons to view more. I then have to open the database to find each one.

Rich

**Comment by danielkerr** [comment]
this is already solved in 3.0
