### ISSUE TITLE
Products not showing on local XAMPP installation

### ISSUE THREAD

**Issue by ziodex** [opencart/opencart#5473]
OpenCart version: 2.3.0.2

Products not showing on local XAMPP installation due to fault in security check in _model\tool\image.php_ file on both catalog and admin.

Problem: Windows path to image url is **C:\xampp\www\opencart\image/** with backslash.

Solution: Change code in **catalog\model\tool\image.php** and **admin\model\tool\image.php** on line 4 from:

`if (!is_file(DIR_IMAGE . $filename) || substr(str_replace('\\', '/', realpath(DIR_IMAGE . $filename)), 0, strlen(DIR_IMAGE)) != DIR_IMAGE) {`

to

`if (!is_file(DIR_IMAGE . $filename) || substr(str_replace('\\', '/', realpath(DIR_IMAGE . $filename)), 0, strlen(DIR_IMAGE)) != str_replace('\\', '/',DIR_IMAGE)) {`

**Comment by danielkerr** [comment]
i use XAMPP  and opencart works flawlessly on it!!

due to fault in security check in model\tool\image.php

the fault was security????? is this armature hour with the description! its got nothing to do with security!

**Comment by danielkerr** [comment]
my installation says:

**Comment by danielkerr** [comment]
duplicate post! there is already an issue openc with same fix for the file manager

**Comment by ziodex** [comment]
Dear Sir. I believe it's spelled amateur if you are going to insult me.

1. The code checks if submitted directory is the same as defined. This is a security measurement.

2. It doesn't handle backslashes, so there is a fault in it.

No, I'm not the only one with the problem. "if it works on my computer there is nothing wrong with it" - that's the true programming spirit Daniel.
