### ISSUE TITLE
Search only for category on store

### ISSUE THREAD

**Issue by webcorvo** [opencart/opencart#5477]
Hi,
For search only for a category on store you must change the page
/catalog/controller/product/product.php

line 199:
search for:
 `if (isset($this->request->get['search']) || isset($this->request->get['tag']))`

replace for:
`if (isset($this->request->get['search']) || isset($this->request->get['tag']) || isset($this->request->get['category_id']) || isset($this->request->get['sub_category'])) `

OC Version 2.3.0.2

**Comment by danielkerr** [comment]
unneeded

**Comment by webcorvo** [comment]
unneeded why not?
I think that you don´t know other stores!!!
I made other thing, when the keyword don´t exist, show all products!!!!!

**Comment by danielkerr** [comment]
im not here to argue with you! i have better experiance than you!

**Comment by webcorvo** [comment]
ok
