### ISSUE TITLE
In opencart 2.3.0.2, Unable to save User Groups.

### ISSUE THREAD

**Issue by vipulmadhani** [opencart/opencart#5487]
Hello, Facing Permission Issues. Whenever try to add IP, modify user groups, Unable to save the,. It says, you dont have permision to modify groups.

Kindly help asap.

**Comment by webcorvo** [comment]
Try to generate a new API Key

**Comment by vipulmadhani** [comment]
I did. But after creating its not getting saved.

**Comment by vipulmadhani** [comment]
Its showing you dont have permission to modify API
