### ISSUE TITLE
Customers Online Report - Solved

### ISSUE THREAD

**Issue by webcorvo** [opencart/opencart#5490]
For Customers Online Report works  we must **INSERT**  not  **REPLACE** fields

Go to **database**  and you must add a new filed on table **`oc_customer_online`** with **AUTO_INCREMENT**

in catalog/model/tool/online.php

$this->db->query("REPLACE INTO `" . DB_PREFIX . "customer_online` SET `ip` = '" . $this->db->escape($ip) . "', `customer_id` = '" . (int)$customer_id . "', `url` = '" . $this->db->escape($url) . "', `referer` = '" . $this->db->escape($referer) . "', `date_added` = '" . $this->db->escape(date('Y-m-d H:i:s')) . "'");
	}

**change to** 

$this->db->query("**INSERT** INTO `" . DB_PREFIX . "customer_online` SET `ip` = '" . $this->db->escape($ip) . "', `customer_id` = '" . (int)$customer_id . "', `url` = '" . $this->db->escape($url) . "', `referer` = '" . $this->db->escape($referer) . "', `date_added` = '" . $this->db->escape(date('Y-m-d H:i:s')) . "'");

**Comment by RaidoDev** [comment]
There is already "REPLACE" syntax, not "UPDATE"

**Comment by webcorvo** [comment]
OK, but if you do replace you stay always with one record!!!!!
