### ISSUE TITLE
Indirect modification of overloaded property ControllerStartupStartup::$session has no effect

### ISSUE THREAD

**Issue by JethvaVipul** [opencart/opencart#5491]
Kindly find the attached file here.

There is problem while I add order from admin side.

![sales-order](https://user-images.githubusercontent.com/3961333/26920384-85f46850-4c56-11e7-8923-8d046a91b5e7.png)

**Comment by webcorvo** [comment]
witch version are you using.
in Version 2.3.0.2 works fine

**Comment by JethvaVipul** [comment]
I am using Version 3.0.0.0_a1(beta)

**Comment by webcorvo** [comment]
Is in beta version ;o)
Use 2.3.0.2

**Comment by JethvaVipul** [comment]
Yes, I know its in beta version. I just sent for fix this issue on beta version.

**Comment by webcorvo** [comment]
ok ;o)

**Comment by danielkerr** [comment]
use the dev branch its the latest.

**Comment by danielkerr** [comment]
Version 3.0.0.0 (Beta)
