### ISSUE TITLE
Split "extensions" from the core in 3.x?

### ISSUE THREAD

**Issue by landsman** [opencart/opencart#5494]
Is possible separate extensions files from the core files by vendors, composer?

I would like have a clean repository, just composer-based stack like at Drupal 8's world. 
What do you think about this?

**Comment by danielkerr** [comment]
I plan to do this

**Comment by danielkerr** [comment]
i need to built a script to split out the extensions and zip them up

**Comment by landsman** [comment]
@danielkerr do you know about this https://github.com/copona/copona? There are few good ideas.
