### ISSUE TITLE
3.0.0.0 beta Backup & Restore

### ISSUE THREAD

**Issue by PeterAR** [opencart/opencart#5495]
In file admin/controller/tool/backup.php are some errors, so the import doesn't work.

Instead of: ini_get('upload_tmp_dir') . '/' . $filename
Better: $filename
Sample replace:
move_uploaded_file($this->request->files['import']['tmp_name'], ini_get('upload_tmp_dir') . '/' . $filename);
with:
move_uploaded_file($this->request->files['import']['tmp_name'], $filename);

By 31% import i became the error-message:
<b>Warning</b>: fopen(C:/xampp/htdocs/opencart/system/storage/logs/): failed to open stream: No such file or directory in <b>C:\xampp\htdocs\opencart\system\library\log.php</b> on line <b>6</b>{"success":"Success: You have successfully imported 33&#37; of your database!","next":"http:\/\/127.0.0.1\/admin\/index.php?route=tool\/backup\/import&user_token=A9dpEyoiAy9YfxTgXe1LbRnwk9Hth4CH&import=C:\\xampp\\tmp\\bacF5E5.tmp&position=280703"}

Thanks for your help!

**Comment by danijelGombac** [comment]
Try replace in admin/controller/startup/error.php

`$this->registry->set('log', new Log($this->config->get('config_error_filename')));`

with 

`$this->registry->set('log', new Log($this->config->get('config_error_filename') ? $this->config->get('config_error_filename') : $this->config->get('error_filename')));`

**Comment by PeterAR** [comment]
Great - import works now :-)
Many thanks and have a nice weekend!
