### ISSUE TITLE
[3.0.0.0] Fax is missing from the front-end getOrder() function

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#5496]
It looks like this was intentionally removed, but since it's still part of the data in the "order" table, it should probably be included in the getOrder() function. The edit needed is this:

```
IN:
/catalog/model/checkout/order.php

AFTER:
'telephone'               => $order_query->row['telephone'],

ADD:
'fax'                     => $order_query->row['fax'],

```

**Comment by danielkerr** [comment]
fax is being removed from customer data. if u require it use custom fields.
