### ISSUE TITLE
Undefined index: order_id in catalog/controller/payment/bank_transfer.php on line 34

### ISSUE THREAD

**Issue by prof-web-coding** [opencart/opencart#550]
This PHP Notice shows up every now and than, but not for all bank transfers:

Undefined index: order_id in catalog/controller/payment/bank_transfer.php on line 34

I'm not sure, can it be that the session times out and then the order_id is not available any more? If you google for this error you will find that many shops have this problem.

**Comment by akadirabus** [comment]
My payment plugin fails. Although many of them are successful, some of them fail. 
**Notice: Undefined index: order_id**

The value of **OCSESID** is changing. I do not know why.

Can you help me??

**Comment by ADDCreative** [comment]
Post details on https://forum.opencart.com/.

**Comment by akadirabus** [comment]
I posted but there is no reply yet
