### ISSUE TITLE
Charset into search result problem 

### ISSUE THREAD

**Issue by edichome** [opencart/opencart#5506]
Hello, please help solve problem.
in search result of website when have more then one page, first page is everything correct until you click next page.
After click next page will not correct show in address keyword (symbols) and result of search also error (Nothing found)
Website in Russian language except this , other functions all work well.
I have check one by one and finally found, if change domain, problem solved.
current domain is .TK, but if change to .COM, .RU problem disappear.

**Comment by danielkerr** [comment]
Maybe the config.php http server issue. Make sure ur using the correct domain that's in the config and the correct t protocol https or not

**Comment by edichome** [comment]
Files config.php both is correct, all settings correct, I spent last two days check one by one and even reinstall again from clean system. Doesn't help.

**Comment by edichome** [comment]
Daniel, sorry, I have ready not carefully your massage.
You are right, I've change all to https and get solution!
Thank you very much!
Problem solved

**Comment by danielkerr** [comment]
hat word should i type to search?

**Comment by danielkerr** [comment]
its working for me wen i search and go to other pages

**Comment by danielkerr** [comment]
yis your issue when you copy the url?

https://autotools.tk/search?search=%D0%9D%D0%B0%D0%B1%D0%BE%D1%80&page=4

thasts doewn to your brwoser

**Comment by edichome** [comment]
before, I use all https, but in the config.php files was http-server > http, https-server>https.
After you sent me first answer, I've change all https and all beginning to work well.
So problem solved, you exactly show place for make right solution. 
Thank you so much again.
