### ISSUE TITLE
3.0.0.0 beta Error with twig-loader

### ISSUE THREAD

**Issue by PeterAR** [opencart/opencart#5508]
Hi,

only in the frontend i became a "fatal error"-Message:

Fatal error: Uncaught Twig_Error_Loader: Unable to find template "common/column_left.twig" (looked into: C:/xampp/htdocs/opencart/catalog/view/theme). in C:\xampp\htdocs\opencart\system\library\template\Twig\Loader\Filesystem.php:215 Stack trace: #0 C:\xampp\htdocs\opencart\system\library\template\Twig\Loader\Filesystem.php(139): Twig_Loader_Filesystem->findTemplate('common/column_l...') #1 C:\xampp\htdocs\opencart\system\library\template\Twig\Environment.php(312): Twig_Loader_Filesystem->getCacheKey('common/column_l...') #2 C:\xampp\htdocs\opencart\system\library\template\Twig\Environment.php(378): Twig_Environment->getTemplateClass('common/column_l...', NULL) #3 C:\xampp\htdocs\opencart\system\storage\modification\system\library\template\twig.php(36): Twig_Environment->loadTemplate('common/column_l...') #4 C:\xampp\htdocs\opencart\system\library\template.php(20): Template\Twig->render('common/column_l...') #5 C:\xampp\htdocs\opencart\system\storage\modification\system\engine\loader.php(85): Template->render('common/colu in C:\xampp\htdocs\opencart\system\library\template\Twig\Loader\Filesystem.php on line 215

For me, it looks the path of the default template "default/template" is missing in the file path.

Thanks for your help!

**Comment by danielkerr** [comment]
fixing

**Comment by jpshdev** [comment]
Can you tell me what the fix was for this? I don't see a PR associated with this issue.

**Comment by danielkerr** [comment]
an incorrect path was not setup int he config.php

**Comment by saptimal** [comment]
@danielkerr Hi there,  I am having exactly the same error message, could tell more on how you  solved the issue ? Did you change a line in config.php ? Which one ? 
I've been struggling for 2 days with this,:( Thanks much for your help.

**Comment by staz17** [comment]
Решается следующим способом. В админке заходим Дизайн->редактор шаблона, с права "История" Находим и удаляем common/column_left. Левая колонка откатиться "по умолчанию" Если нужно внести в неё изменения сделайте это в файле column_left.twig и залейте на сервер, обновите кэш.
Solved in the following way. In the admin panel, go to Design-> template editor, on the right "History" Find and delete common/column_left. The left column will be rolled back "by default" If you need to make changes to it, do it in the column_left.twig file and upload it to the server, update the cache.

**Comment by idem84** [comment]
> Решается следующим способом. В админке заходим Дизайн->редактор шаблона, с права "История" Находим и удаляем common/column_left. Левая колонка откатиться "по умолчанию" Если нужно внести в неё изменения сделайте это в файле column_left.twig и залейте на сервер, обновите кэш. Solved in the following way. In the admin panel, go to Design-> template editor, on the right "History" Find and delete common/column_left. The left column will be rolled back "by default" If you need to make changes to it, do it in the column_left.twig file and upload it to the server, update the cache.

А кого эта ошибка появляется в самой админке и админка не работает?
