### ISSUE TITLE
Order mail store data

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#5509]
Why in the order mail function the store data was taken from three different location?

From config

`$data['logo'] = $this->config->get('config_url') . 'image/' . $this->config->get('config_logo');`

From order DB

`$data['link'] = $order_info['store_url'] . 'index.php?route=account/order/info&order_id=' . $order_info['order_id']`

And then

```
$this->load->model('setting/setting');
		
$from = $this->model_setting_setting->getSettingValue('config_email', $order_info['store_id']);
		
if (!$from) {
	$from = $this->config->get('config_email');
}
```

**Comment by danielkerr** [comment]
because this is required to get the current store email

$from = $this->config->get('config_email');

**Comment by danijelGombac** [comment]
But why we pass store_id to the api if we don't get the store email from the config?

**Comment by danielkerr** [comment]
Because the call back from one of the gateways could be set to the default site
