### ISSUE TITLE
3.0.0.0 beta Error with add category

### ISSUE THREAD

**Issue by PeterAR** [opencart/opencart#5514]
Hi,
i tried to add a new category. After click to the save-Button i became a "fatal error"-Message:

Notice: Undefined index: keyword in C:\xampp\htdocs\opencart\admin\controller\catalog\category.php on line 590
Fatal error: Uncaught Exception: Error: Duplicate entry '31-1' for key 'PRIMARY'<br />Error No: 1062<br />INSERT INTO oc_category_description SET category_id = '31', language_id = '1', name = 'Sandalen', description = '', meta_title = 'Sandalen', meta_description = '', meta_keyword = '' in C:\xampp\htdocs\opencart\system\library\db\mysqli.php:40 Stack trace: #0 C:\xampp\htdocs\opencart\system\library\db.php(16): DB\MySQLi->query('INSERT INTO oc_...', Array) #1 C:\xampp\htdocs\opencart\admin\model\catalog\category.php(13): DB->query('INSERT INTO oc_...') #2 C:\xampp\htdocs\opencart\system\engine\loader.php(185): ModelCatalogCategory->addCategory(Array) #3 C:\xampp\htdocs\opencart\system\engine\proxy.php(25): Loader->{closure}(Array, Array) #4 C:\xampp\htdocs\opencart\admin\controller\catalog\category.php(23): Proxy->__call('addCategory', Array) #5 C:\xampp\htdocs\opencart\system\engine\action.php(51): ControllerCatalogCategory->add() #6 C:\xampp\htdocs\opencart\admin\controller\startup\router.php(26): Action->execute(Objec in C:\xampp\htdocs\opencart\system\library\db\mysqli.php on line 40

Thanks for your help!

**Comment by danielkerr** [comment]
im not here to fix stuff im still working for you

**Comment by PeterAR** [comment]
Excuse me if I have angered you!

Now I have opencart again completely new installed and thus folds again the creation of the categories. It was probably my database.

And apology for my not so good english and the partial translation with Google. Normally, I speak better hessian = dialect of my home town ;-)
