### ISSUE TITLE
About API

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#5530]
Just a suggestion,

now the api controller folder is full of files, which belong to different purpose(localisation, extension, checkout).

Why not move files to appropriate folder:

localisation/api/currency,

extension/total/api/voucher

checkout/api/order

And maybe add customer/api and product/api.

Mixed all in one folder in the future will be a mess.

**Comment by RaidoDev** [comment]
Dividing API into different routes, creates more mess, I think.
API should be available under one path, and logically divided.

E.g. 

`api/{controller}/{action}/{id}`
