### ISSUE TITLE
Call to undefined method Language::load()

### ISSUE THREAD

**Issue by deliogit** [opencart/opencart#5531]
Hi, I just installed a fresh 2.3.0.2, but I am getting this message "Fatal error: Call to undefined method Language::load() ... /system/framework.php on line 58" when I try to run it for the first time.
Could anybody help me out?

Thank you

**Comment by danielkerr** [comment]
reupload

**Comment by deliogit** [comment]
Hello Daniel,
I do not understand why you close this. There is this "reupload" but I am not uploading anything.
Could you please give any solution to this?
Thank you
