### ISSUE TITLE
PHP Fatal error:  SUHOSIN - Use of eval is forbidden by configuration

### ISSUE THREAD

**Issue by bau720123** [opencart/opencart#5553]
hi @danielkerr 
when I install opencart 3.0
in my localhost is OK (XAMPP)
but when in my remote server，it will appear an error message in the folder "install/error_log"
`
PHP Fatal error:  SUHOSIN - Use of eval is forbidden by configuration in /the_opencart_folder/system/library/template/Twig/Environment.php(403) : eval()'d code on line 5
is my server have something wrong ?
`

**Comment by andrejuseu** [comment]
Your hosting provider is blocking "eval()" from using in code, contact them to remove it from blacklist.

**Comment by danielkerr** [comment]
didn't realize eval was in twig.

**Comment by bau720123** [comment]
thanks @andrejuseu and @danielkerr 
I will contact my server provider to solve this problem

well...the PHP Official said that
http://php.net/manual/en/function.eval.php
`
The eval() language construct is very dangerous because it allows execution of arbitrary PHP code. Its use thus is discouraged. If you have carefully verified that there is no other option than to use this construct, pay special attention not to pass any user provided data into it without properly validating it beforehand.
`
so...just recommand，if one day can use other way to realize the twig，I think it will be a more better choice

**Comment by danielkerr** [comment]
I KNOW WHAT THE ISSUES ARE WITH EVAL!!!

I just didnt know twig used it!~

**Comment by andrejuseu** [comment]
> eval is only used when you don't use a Cached template, when you use the cache eval is not used.

Source: https://github.com/twigphp/Twig/issues/2428

**Comment by danielkerr** [comment]
and locked conversation so we dont get any more dumb assun wanted replies
