### ISSUE TITLE
Coupons: choose whether to include or exclude categories/products?

### ISSUE THREAD

**Issue by twistedpixel** [opencart/opencart#5558]
Is this planned? Currently the only way I can see to write an extension for this functionality requires modifying the structure of the database which isn't really a good idea.

**Comment by danielkerr** [comment]
already has this feature

**Comment by twistedpixel** [comment]
No, I think you've misunderstood me. There's no way to choose whether the products/categories selected are inclusions or exclusions. For example, no way to exclude a particular category from a coupon discount. The only way to achieve this is to add every single category except one or if you need to do this with products, add every single product except one.
