### ISSUE TITLE
Opencart 3.0 Filters

### ISSUE THREAD

**Issue by webcorvo** [opencart/opencart#5560]
**Filters on the right side ?????????????????????????
Does not make sense and is not functional!!!!**

**Comment by OpenCartAddons** [comment]
Filters on the side are not really an issue.  They collapse on smaller screens which is nice.

**Comment by webcorvo** [comment]
I don´t agree!! sorry

**Comment by OpenCartAddons** [comment]
Correct, it's your opinion.  The issue tracker isn't meant for tracking opinions.

**Comment by webcorvo** [comment]
ok, you have reason sorry. Where i can put this in the forum?

**Comment by OpenCartAddons** [comment]
You can post it here:

**Comment by danielkerr** [comment]
Ur option only
