### ISSUE TITLE
Documentation for extension developers - OC. 3.0.0.0

### ISSUE THREAD

**Issue by ocdevops** [opencart/opencart#5563]
Please send me some description about how can I run sql during the extension installation (install.sql)
Thanks for your help.

**Comment by osworx** [comment]
Everything written here: https://github.com/opencart/opencart/wiki/Modification-System#file-structure

**Comment by ocdevops** [comment]
Thanks for your fast response, but I try to install an extension on OC. 3.0.0.0, and install.sql did not run for me. It worked fine on Opencart 2.x versions.

**Comment by osworx** [comment]
Sorry, my fault.
Seems that this functions are ... deleted!
Or better - removed. 
Installer in 3.x can handle only extensions from marketplace - and no .sql anymore.

**Comment by danielkerr** [comment]
Do it from a install method

**Comment by CoverUp** [comment]
btw, the install method works great for a module, but your extension must be a module, otherwise you don't have the method. And make a module for your "not module" extension means extra work. Thats why install.sql used to be very useful. Anyway, there is always a workaround.
