### ISSUE TITLE
opencart 3.0 do not route  when login 

### ISSUE THREAD

**Issue by longtaoge** [opencart/opencart#5564]
logined in admin  
the password and user is right 
but can't route to dashboard

[phpinfo](https://github.com/longtaoge/DevelopmentNotes/blob/master/image/opencart.png)
![](https://github.com/longtaoge/DevelopmentNotes/blob/master/image/opencart.png)

**Comment by kostasmoure** [comment]
same here

**Comment by danielkerr** [comment]
closing as u have provided no information
