### ISSUE TITLE
Fresh Installation Errors - Opencart version 3.0

### ISSUE THREAD

**Issue by kostasmoure** [opencart/opencart#5571]
Hi i have the following errors when trying to install the new version of opencart(3.x),
Those errors appears at 1st step and continue to the last step.

Warning: fopen(/var/lib/php/session/sess_ffee82816dfcd6bb1065a22955): failed to open stream: Permission denied in /chroot/home/*/*/html/system/library/session/file.php on line 39Warning: flock() expects parameter 1 to be resource, boolean given in /chroot/home/*/*/html/system/library/session/file.php on line 41Warning: fwrite() expects parameter 1 to be resource, boolean given in /chroot/home/*/*/html/system/library/session/file.php on line 43Warning: fflush() expects parameter 1 to be resource, boolean given in /chroot/home/*/*/html/system/library/session/file.php on line 45Warning: flock() expects parameter 1 to be resource, boolean given in /chroot/home/*/*/html/system/library/session/file.php on line 47Warning: fclose() expects parameter 1 to be resource, boolean given in /chroot/home/*/*/html/system/library/session/file.php on line 49

is it a bug or something else?
What are the minimum requirements for installation? Couldn't find any info on this.

**Comment by danielkerr** [comment]
yes working on a fix now

**Comment by deliogit** [comment]
Fresh Installation Errors OpenCart v3.0.0.1
Notice: Use of undefined constant DIR_SESSION - assumed 'DIR_SESSION' in /home/public_html/system/library/session/file.php on line 7
Fatal error: Call to undefined method Language::load() in /home/public_html/system/engine/loader.php on line 144
Notice: Use of undefined constant DIR_SESSION - assumed 'DIR_SESSION' in /home/public_html/system/library/session/file.php on line 27Warning: fopen(DIR_SESSION/sess_b371ed16069f93a23b957a7324): failed to open stream: No such file or directory in /home/delio210/public_html/system/library/session/file.php on line 29Warning: flock() expects parameter 1 to be resource, boolean given in /home/public_html/system/library/session/file.php on line 31Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/delio210/public_html/system/library/session/file.php on line 33Warning: fflush() expects parameter 1 to be resource, boolean given in /home/public_html/system/library/session/file.php on line 35Warning: flock() expects parameter 1 to be resource, boolean given in /home/public_html/system/library/session/file.php on line 37Warning: fclose() expects parameter 1 to be resource, boolean given in /home/public_html/system/library/session/file.php on line 39

**Comment by danielkerr** [comment]
its there

$output .= 'define(\'DIR_SESSION\', DIR_STORAGE . \'session/\');' . "\n";

unless u did an upgrade

**Comment by kostasmoure** [comment]
Hi Danniel,

deliogit posted an error different than mine as long as i can understand. The solution you provided i think that it has nothing to do with my error. Can you please confirm?

$output .= 'define('DIR_SESSION', DIR_STORAGE . 'session/');' . "\n";

where do i need to insert?

**Comment by deliogit** [comment]
Hi Kostasmoure,

My apologies I will open a new issue.

Kind Regards,

Delio
