### ISSUE TITLE
The directory admin/controller/module is not allowed to be written to!

### ISSUE THREAD

**Issue by satanand7** [opencart/opencart#5572]
There is no module directory but when upload any extension it gives given error. I have created module directory manually but got same error. I am using opencart3.0

![image](https://user-images.githubusercontent.com/22170723/27391602-f6a3a80c-56c1-11e7-993c-df0434856b9b.png)

**Comment by OpenCartAddons** [comment]
Should be `admin/controller/extension/module/`

**Comment by satanand7** [comment]
this is already there but getting error.

**Comment by OpenCartAddons** [comment]
The extension installer limits which folders extensions can be uploaded to:

`admin/controller/extension/`
`admin/language/`
`admin/model/extension/`
`admin/view/image/`
`admin/view/javascript/`
`admin/view/stylesheet/`
`admin/view/template/extension/`
`catalog/controller/extension/`
`catalog/language/`
`catalog/model/extension/`
`catalog/view/javascript/`
`catalog/view/theme/`
`system/config/`
`system/library/`
`image/catalog/`

_I have not reviewed the latest version of the dev branch to confirm if the allowed directories have been changed_

**Comment by osworx** [comment]
@satanand7 

> this is already there but getting error.

But what about the path(s) inside your module you want to install?

**Comment by danielkerr** [comment]
chmod them

**Comment by MohitPrakashSharma** [comment]
I Thinks there have some permission error is extension contact support team of extension.
