### ISSUE TITLE
New install, sass.php errors

### ISSUE THREAD

**Issue by clearshot** [opencart/opencart#5573]
- CentOS 6.9 VPS
- OpenCart 3.0.0.1 (but shows 3.0.0.0 in copyright area)
- The following error displays along the top of admin/index.php after login and on the login page.
- Storefront displays correctly
- No mods installed, no settings changed

`Warning: fopen(/var/www/html/admin/view/stylesheet/bootstrap.css): failed to open stream: Permission denied in /var/www/html/admin/controller/startup/sass.php on line 14Warning: flock() expects parameter 1 to be resource, boolean given in /var/www/html/admin/controller/startup/sass.php on line 16Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/admin/controller/startup/sass.php on line 18Warning: fflush() expects parameter 1 to be resource, boolean given in /var/www/html/admin/controller/startup/sass.php on line 20Warning: flock() expects parameter 1 to be resource, boolean given in /var/www/html/admin/controller/startup/sass.php on line 22Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/html/admin/controller/startup/sass.php on line 24`

**Comment by clearshot** [comment]
Attached error occurs when uploading a picture to the user profile. Image file uploads successfully and shows upon refresh.

![capture](https://user-images.githubusercontent.com/19211913/27394066-e2517544-5678-11e7-97dc-8b26e732fce5.PNG)

**Comment by danielkerr** [comment]
u need to chmod the file to maybe 644 or 777

**Comment by clearshot** [comment]
I chmod'd /var/www/html/admin/view/ to 777 and it all resolved.

**Comment by clearshot** [comment]
Sorry for my rudeness, didn’t read my emails and see your reply notification.

 

Regards,

Conor Cleary

613-246-2492 | conor@clearydale.ca

**Comment by naren27** [comment]
> u need to chmod the file to maybe 644 or 777

Hi Denile,
I  am using capistranio versioning system then how it can possible to use this permission.  File over write in every deployment. 

Kind regards,
Naren
