### ISSUE TITLE
Paypal Express Refund Error 

### ISSUE THREAD

**Issue by SimplyNextGen** [opencart/opencart#5578]
ok so when i make payment it works fine on paypal and site side but when i go to the orders and click on issue refund i get this error 

http://prntscr.com/fm14fk

Update when i refresh when im on the error page i get a message saying the the refund has been already issued and i check paypal and it has refund but its not instant it was a echeck and says pending

**Comment by danielkerr** [comment]
eCheck status is PayPal's bug and should reduce its self in a few days.

**Comment by danielkerr** [comment]
ok this is a duplicate issue
