### ISSUE TITLE
Unable to choose custom theme 3.0

### ISSUE THREAD

**Issue by sajansharmanz** [opencart/opencart#5579]
When i am trying to set a theme I have designed/developed as the store theme; I am unable to do so.

If I visit Extensions > Themes(1) > Default Store Theme and click edit and make any changes I get the following error message:  
> Warning: You do not have permission to modify the default store theme!

If I visit System > Settings > Your Store (Default) > Theme - there is no option for my custom theme in the Dropdown

I have copied and pasted the default theme folder (entirely) and renamed it to something else and it still does not display as an option. Am i missing something?

**Comment by danielkerr** [comment]
u also need to create the corresponding files in the extension directories

**Comment by sajansharmanz** [comment]
What do you mean by this? I have tried google but all forums keep mentioning that you essentially duplicate the default theme folder, rename it to your theme name, visit the theme extension from admin menu and change the theme thats being applied and then make changes to templates. Is there some documentation on what you are mentioning?

**Comment by danielkerr** [comment]
Check under admin/controller/extension/theme
