### ISSUE TITLE
Dashboard extension can not be installed/Uninstalled [3.0.0.0 & 2.3.0.x]

### ISSUE THREAD

**Issue by dmitriyzhuk** [opencart/opencart#5581]
Hi

in Admin / Extensions / Dashboard you can not install or uninstalled Extentions 

http://joxi.ru/L21zk7Mu8yvEVA

This is because the oc_extension table which is responsible for keeping trek of models is storing them like this

 "dasboard" | "analytics"

While the settings are appended with 'dashoard_' prefix

so when you call MODAL uninstall with the prefix - you won't clear the OC_EXTENSION table - thus no uninstall or install

but if you call without the prefix - you will clear OC_EXTENSION, but the OC_SETTING table will not be cleared.

I guess you have done this to avoid collition between similar "code" keys. 

here is my fix for version 2.3.0.x

<?xml version="1.0" encoding="utf-8"?>
<modification>
    <name>d_shopunity_oc230_patch</name>
    <code>d_shopunity_oc230_patch</code>
    <description>Adds copmatibility fixes for old extensions on Opencarts 2.x</description>
    <version>1.0.0</version>
    <author>Dreamvention</author>
    <link>http://dreamvention.com</link>

    <file path="admin/controller/extension/extension/dashboard.php">
        <operation error="skip" info="fix for install and uninstall of dashboard extensions">
            <search ><![CDATA['dashboard_' . $this->request->get['extension']]]></search>
            <ignoreif><![CDATA[//d_shopunity_oc230_patch.xml 1]]></ignoreif>
            <add position="replace"><![CDATA[$this->request->get['extension']]]></add>
        </operation>
        <operation error="skip" info="fix for install and uninstall of dashboard extensions">
            <search ><![CDATA[$this->load->controller('extension/dashboard/' . $this->request->get['extension'] . '/uninstall');]]></search>
            <ignoreif><![CDATA[//d_shopunity_oc230_patch.xml 2]]></ignoreif>
            <add position="before"><![CDATA[
                //d_shopunity_oc230_patch.xml 2
                $this->load->model('setting/setting');
                $this->model_setting_setting->deleteSetting('dashboard_'.$this->request->get['extension']);
            ]]></add>
        </operation>
        <operation error="skip" info="fix for install and uninstall of dashboard extensions">
            <search ><![CDATA[$this->model_extension_extension->uninstall('dashboard', $value);]]></search>
            <ignoreif><![CDATA[//d_shopunity_oc230_patch.xml 3]]></ignoreif>
            <add position="after"><![CDATA[
                //d_shopunity_oc230_patch.xml 3
                $this->load->model('setting/setting');
                $this->model_setting_setting->deleteSetting('dashboard_'.$value);
            ]]></add>
        </operation>
    </file>
 

I made a pull request here for version 3.0.0.0 https://github.com/opencart/opencart/pull/5580

**Comment by dmitriyzhuk** [comment]
just to be clear - the latest version 3.0.0.0 - dev already addressed this issue but there was one prefix still left out in Uninstall

https://github.com/opencart/opencart/pull/5580

**Comment by opencartmasterbr** [comment]
NOT UPGRADE  VERSION  2.3.0.2  FOR  3.0.x,  install  clear  version  3.0.X  abouve  transfer  products, departaments
