### ISSUE TITLE
ERROR  CUSTOM FIELDS REQUIRED 

### ISSUE THREAD

**Issue by opencartmasterbr** [opencart/opencart#5584]
When creating a custom field in the account and put it as mandatory fill even informing data in the field it informs that there is no typed data

**Comment by Samindu** [comment]
Hello Danielkerr,

Is this issue resolved? I also having this issue, Please kindly help me to fix this issue.

![image](https://user-images.githubusercontent.com/1914312/34428573-45e54b26-ec74-11e7-90d6-05669f1adc16.png)

Thank You
Samindu Gunasekara
