### ISSUE TITLE
IE checkout issue 

### ISSUE THREAD

**Issue by onoriotorti** [opencart/opencart#5585]
hi, I've been having the issue of not being able to checkout on IE or Edge trough my opencart website I've already put all the information on the opencart forum and they advised me to write here .
here is the link to check it out []https://forum.opencart.com/viewtopic.php?f=190&t=185159
thanks in advance 

Onorio

**Comment by danijelGombac** [comment]
I think this is not related to opencart, but or some extension or setting. I try my site on Edge and is working fine.

**Comment by onoriotorti** [comment]
i know it is not theme related because even on the default opencart theme it does not work i have no clue on what it could possibly be.

**Comment by webcorvo** [comment]
@onoriotorti  have reason, i have install his version and dosen´t work, with the default theme

**Comment by danijelGombac** [comment]
@onoriotorti i send you private message on forum

**Comment by onoriotorti** [comment]
i have answered you my friend :)
