### ISSUE TITLE
Marketplace - Documetation text

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#5590]
Currently the documentation text is displayed like this:
![admin_marketplace_docu_text](https://user-images.githubusercontent.com/1905204/27453314-48d16590-5796-11e7-90cc-1cd50ef54da2.png)

What if the text could be parsed?
The output could be like that:
![admin_marketplace_docu_text_parsed](https://user-images.githubusercontent.com/1905204/27453339-5c5f4604-5796-11e7-8b0f-a8b6c4b7dcb4.png)

If you interested, I can make a pull request.
Used sw is licensed under MIT.

**Comment by danielkerr** [comment]
i need to fix this from the main opencart.com web site

**Comment by danielkerr** [comment]
ok should be fixed now.
