### ISSUE TITLE
[3.0.0.0] No order_status in emails

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#5593]
Something goes wrong with the new method how orders are handled.
No matter what I try, the order_status is **NOT** included in the emails (wether customer nor admin).
Status is set correct in the backend.

**Comment by danijelGombac** [comment]
The order status is set correctly only in in mail/order/edit function. The other two function get the order status from $order_info which have wrong status, because the event is before and the order status is not saved in DB.

**Comment by osworx** [comment]
And this makes sense?
Customer recieve an email with text Orderstatus but NO order status is displayed?

Case: placing an order with instant payment (status = 5 > Ready/Complete).
So far, so fine.
Before OC 3.x the status was sent with the email, with 3.x only the text is in the email, but status is missing (empty).
Now what shall the customer think when he reads that?

**Comment by danijelGombac** [comment]
I report this issue #5363, but was partially fixed.

**Comment by osworx** [comment]
@danijelGombac sorry, did not see that entry (title is too common ..)

**Comment by osworx** [comment]
@danijelGombac if your fix https://github.com/opencart/opencart/commit/3ae9708 would be added also at the function add
it would work.

**Comment by danijelGombac** [comment]
I added i both functions.
