### ISSUE TITLE
[PAYPAL EXPRESS] Error on refund 

### ISSUE THREAD

**Issue by SimplyNextGen** [opencart/opencart#5600]
Getting error when i issue refund in cpanel, however the action does work and give them a refund but does not change the status 

Notice: Undefined index: parent_id in /home1/k0y4e1v2/public_html/admin/model/extension/payment/pp_express.php on line 64Warning: Cannot modify header information - headers already sent by (output started at /home1/k0y4e1v2/public_html/admin/controller/startup/error.php:34) in /home1/k0y4e1v2/public_html/system/storage/modification/system/library/response.php on line 12

**Comment by danielkerr** [comment]
can not replicate also i have no idea which version u are using.
