### ISSUE TITLE
[3.0.0.0] Bug: sessions code *** up

### ISSUE THREAD

**Issue by max-dreamsoft** [opencart/opencart#5604]
Just explain me, how this code intended to work?

Beautiful SQL query:
https://github.com/opencart/opencart/blob/3.0.0.0/upload/system/library/session/db.php#L34

Magnificent typos:
https://github.com/opencart/opencart/blob/3.0.0.0/upload/system/library/session.php#L54
https://github.com/opencart/opencart/blob/3.0.0.0/upload/system/library/session.php#L55

3.0.0.0 release? Really?

**Comment by danielkerr** [comment]
try 3.0.01

**Comment by max-dreamsoft** [comment]
There is no such release yet.

**Comment by danielkerr** [comment]
Dev
