### ISSUE TITLE
[3.0.0.0] Customer approved column missing

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#5606]
The 'approved' column looks to have been removed from customers table but still referenced in the code. Forgotten password does not validate and throws an error 'Undefined index: approved '

```php
protected function validate() {
	if (!isset($this->request->post['email'])) {
		$this->error['warning'] = $this->language->get('error_email');
	} elseif (!$this->model_account_customer->getTotalCustomersByEmail($this->request->post['email'])) {
		$this->error['warning'] = $this->language->get('error_email');
	}

	$customer_info = $this->model_account_customer->getCustomerByEmail($this->request->post['email']);

	if ($customer_info && !$customer_info['approved']) {
		$this->error['warning'] = $this->language->get('error_approved');
	}

	return !$this->error;
}
```

Maybe this to check group has approval and status but better how it worked before with separate column for approval. 
```php
protected function validate() {
	if (!isset($this->request->post['email'])) {
		$this->error['warning'] = $this->language->get('error_email');
	}

	$customer_info = $this->model_account_customer->getCustomerByEmail($this->request->post['email']);

	if (!$customer_info) {
		$this->error['warning'] = $this->language->get('error_email');
	}

	$this->load->model('account/customer_group');

	$customer_group_info = $this->model_account_customer_group->getCustomerGroup($customer_info['customer_group_id']);

	if (!$customer_group_info || ($customer_group_info['approval'] && !$customer_info['status'])) {
		$this->error['warning'] = $this->language->get('error_approved');
	}

	return !$this->error;
}
```

**Comment by Elios007** [comment]
HI, 

We are not able to approve the customers, where we should do it in the 3.0?

**Comment by howdu** [comment]
There's a new page called Customer Approvals and a new database table customer_approval. 

Also looks like approval column has been replaced with status.

**Comment by Elios007** [comment]
![customer approval](https://user-images.githubusercontent.com/8313659/27731750-05369e20-5d97-11e7-84ac-657946154371.png)
![customer](https://user-images.githubusercontent.com/8313659/27731751-05393770-5d97-11e7-957c-c6d2b12f93e7.png)
![group](https://user-images.githubusercontent.com/8313659/27731752-054027d8-5d97-11e7-8b68-7d850a1f323f.png)

**Comment by Elios007** [comment]
It is not even working

**Comment by howdu** [comment]
Needs to be set 'yes' to approve new customer

**Comment by Elios007** [comment]
We tried both options, and we want to eliminate the approval option. We want the customer to start buying without the need of approval.

**Comment by Elios007** [comment]
![login needs approval](https://user-images.githubusercontent.com/8313659/27732264-1eb4e526-5d99-11e7-8f68-d2da633a3d11.png)

**Comment by Elios007** [comment]
![custom field approval](https://user-images.githubusercontent.com/8313659/27732458-11c6aa60-5d9a-11e7-94a2-097c84daa38c.png)
![Uploading customer approval new.png…]()

**Comment by Elios007** [comment]
I have created a new field ... and still not working....


![custom field approval](https://user-images.githubusercontent.com/8313659/27732482-2b3f794a-5d9a-11e7-925c-55bc74e30b1e.png)
![customer approval new](https://user-images.githubusercontent.com/8313659/27732483-2b4cbbaa-5d9a-11e7-9708-e372b99fac2f.png)

**Comment by danielkerr** [comment]
did u apply the fix i referenced?

https://github.com/opencart/opencart/commit/edb81bd6be720734b8f24d27daa65a66ecd68d90
