### ISSUE TITLE
 Could not load model design/banner!

### ISSUE THREAD

**Issue by Pavel1986** [opencart/opencart#5608]
After installing clean version 3.0.0.0 and 3.0.0.1 (Beta) I have found PHP error:
Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model design/banner!' in system/engine/loader.php on line 60

**Comment by danielkerr** [comment]
can not replicate.

**Comment by Pavel1986** [comment]
and that's it? :D just close the ticket?

**Comment by danielkerr** [comment]
can not replicate.

**Comment by danielkerr** [comment]
there is no missing controller. im not hear to play guessing games. post as much info as you can or stop wasting my time
