### ISSUE TITLE
Duplicate Totals, Missing From Featured List, Cart Change Qty

### ISSUE THREAD

**Issue by nsbz1** [opencart/opencart#5610]
I did a fresh install of OC 3.0.0.0 (not the Beta) and then brought over some data from a 1.5 OC store using temp tables and INSERT SELECT statements via the command line, so these might be bugs or it might be data corruption, or a little of both. :) 

Subtotals & Totals:

When I add an item to the cart, the item subtotal is correct. However, when you look at the cart either from the top pop out or the cart page, it shows two subtotals and two totals and the totals are both showing twice the subtotals.

Example: (The actual subtotal and total should be the $238)

Sub-Total $238.00
Sub-Total $238.00
Total $476.00
Total $476.00

I tried both disabling and removing the subtotal Extension just to see what happens and it removed both and the 2 totals shown went to zero as shown below. I was hoping restoring the subtotal Extension after my test would correct it, but it remains as above.

Total $0.00
Total $0.00

Cart Quantity Change

When you change the qty of items in the cart it throws the 3 asterisk warning below...
Products marked with *** are not available in the desired quantity or not in stock!

I verified the product has a massive quantity number - 999999, set it to not subtract stock, and set Out Of Stock Status to In Stock.

This behavior occurs on every product, except for a test product I created outside of the imported products to see if it was a data corruption issue. So on this issue, I'm trying to look at the DB data to see what the difference is, but nothing jumps out at me so far.

Featured

The Featured Module is only showing 5 of the 9 actual products in the list available to be added to the featured module when you mouse over the Products Autocomplete question mark. If I try to manually add the exact product name of a product missing from that Autocomplete list and save it, it just ignores my attempt and shows the confirmation that the changes were saved to that module.

I am having this issue with both the original products and the new test product added after the fact. In fact one of the 5 it is showing at the end of the list is actually a disabled product. I don't see anything obvious in terms of it only grabbing X number of records from the product table. The items it is showing are not sequential in the MYSQL table either.

Thank you in advance!

**Comment by danielkerr** [comment]
sorry i can not help u with moving your site over. i need to concentrate on fixing bugs for the bulk of users. please try the forum or one of the opencart extensions. or the partners page.

**Comment by nsbz1** [comment]
Daniel, I wasn't asking for help on moving the site over.  I want to know if these are bugs with OC 3 or should I be looking at the data.  The only response I got from the forums was that I'm using a Beta version, which according to the downloads page, I am not.  A simple response of look at your data, or it's a known bug, would have been helpful.  I know you're extremely busy, but in the time you told me you couldn't help with this, you could have answered that for me.   For the record, I appreciate what you've created and eventually would have liked to discuss implementing it in a commercial project we're developing too.
