### ISSUE TITLE
Publish Opencart 3 to packagist

### ISSUE THREAD

**Issue by stefanhuber** [opencart/opencart#5611]
Please publish the new opencart release to packagist, so that the rest of us could work with it! There is an automatic hook on github, which would do the job for you.

https://packagist.org/packages/opencart/opencart

**Comment by jamesallsup** [comment]
Can you add me as an admin on there please stefan: jamesallsup

**Comment by stefanhuber** [comment]
@jamesallsup Unfortunately I have no rights to do that. User `opencart`is the admin (https://packagist.org/users/opencart/)

**Comment by jamesallsup** [comment]
@stefanhuber- all done and also added the auto update for everyone too!
