### ISSUE TITLE
Opencart 3.0 Fresh installation error #5605

### ISSUE THREAD

**Issue by deliogit** [opencart/opencart#5612]
Hi the issue "Opencart 3.0 Fresh installation error #5605" has been closed without a fix,

Also  naturecr had the same problem.
Could someone help to solve this please?

Kind regards,

Delio

After a new installing I am receiving this error when I try to access the site address.
Thank you for the help,

Delio

Notice: Use of undefined constant DIR_SESSION - assumed 'DIR_SESSION' in /home/public_html/system/library/session/file.php on line 7
Fatal error: Call to undefined method Language::load() in /home/public_html/system/engine/loader.php on line 144
Notice: Use of undefined constant DIR_SESSION - assumed 'DIR_SESSION' in /home/public_html/system/library/session/file.php on line 27Warning: fopen(DIR_SESSION/sess_b371ed16069f93a23b957a7324): failed to open stream: No such file or directory in /home/delio210/public_html/system/library/session/file.php on line 29Warning: flock() expects parameter 1 to be resource, boolean given in /home/public_html/system/library/session/file.php on line 31Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/delio210/public_html/system/library/session/file.php on line 33Warning: fflush() expects parameter 1 to be resource, boolean given in /home/public_html/system/library/session/file.php on line 35Warning: flock() expects parameter 1 to be resource, boolean given in /home/public_html/system/library/session/file.php on line 37Warning: fclose() expects parameter 1 to be resource, boolean given in /home/public_html/system/library/session/file.php on line 39

**Comment by danielkerr** [comment]
try 3.0.01

**Comment by danielkerr** [comment]
it has been fixed! reead the comments

**Comment by RaidoDev** [comment]
3.0.0.1 not 3.0.01 and there is no such version release yet, please, be more specific or create release tag!
