### ISSUE TITLE
Could not open screen Design/Layout/Home

### ISSUE THREAD

**Issue by nhatnghe** [opencart/opencart#5613]
Error when open edit layout Home Page 
Link localhost: http://localhost/KBShop/admin/index.php?route=design/layout/edit&user_token=DmouuOIb02vlo5ZiP8pdsOWHC6ujVR4S&layout_id=1

Notice: Undefined variable: language in C:\xampp\htdocs\KBShop\admin\controller\design\layout.php on line 369
Fatal error: Uncaught Error: Call to a member function load() on null in C:\xampp\htdocs\KBShop\admin\controller\design\layout.php:369 Stack trace: #0 C:\xampp\htdocs\KBShop\admin\controller\design\layout.php(76): ControllerDesignLayout->getForm() #1 C:\xampp\htdocs\KBShop\system\engine\action.php(51): ControllerDesignLayout->edit() #2 C:\xampp\htdocs\KBShop\admin\controller\startup\router.php(26): Action->execute(Object(Registry), Array) #3 C:\xampp\htdocs\KBShop\system\engine\action.php(51): ControllerStartupRouter->index() #4 C:\xampp\htdocs\KBShop\system\engine\router.php(34): Action->execute(Object(Registry)) #5 C:\xampp\htdocs\KBShop\system\engine\router.php(29): Router->execute(Object(Action)) #6 C:\xampp\htdocs\KBShop\system\framework.php(168): Router->dispatch(Object(Action), Object(Action)) #7 C:\xampp\htdocs\KBShop\system\startup.php(104): require_once('C:\\xampp\\htdocs...') #8 C:\xampp\htdocs\KBShop\admin\index.php(19): start('admin') #9 {main} thrown in C:\xampp\htdocs\KBShop\admin\controller\design\layout.php on line 369

**Comment by danielkerr** [comment]
duplicate, try 3.0.0.1
