### ISSUE TITLE
No class on body element

### ISSUE THREAD

**Issue by sirego** [opencart/opencart#5616]
Previous versions of opencart were used to target a page with a specific class on the body element.

Designers will sooner or later want to apply different style to the same element rendered accross various pages.

Default OpenCart theme doesn't provide means to do this because header.twig outputs <body> tag wihout any classes, making the previous task impossible to accomplish.  Is that going to come back ?

**Comment by danielkerr** [comment]
dont care. added it needs to be hardcoded and not generated from the route to body.
