### ISSUE TITLE
 Unable to activate default theme

### ISSUE THREAD

**Issue by sirego** [opencart/opencart#5617]
Default theme is disabled when i visit Extensions > Themes(1) > Default Store Theme. Warning: You do not have permission to modify the default store theme.

When I want to activate it and save the new status, i get this error message: "Warning: You do not have permission to modify the default store theme!"

There is the same problem when you duplicate a theme and you want to activate it.

**Comment by danielkerr** [comment]
its fixed in the dev branch (3.0.0.1)
