### ISSUE TITLE
is opencart 3.0.0.0 Marketplace Works on localhost for free extension? says Signature hash does not match! error

### ISSUE THREAD

**Issue by karthickeyang** [opencart/opencart#5620]
when i install free opencart 3.0.0.0 extension in Extension marketplace section, i get 
"Signature hash does not match! error" 
or do i should have a live site?

**Comment by danielkerr** [comment]
try entering the domain again. needs to be www.yourhost.com

localhost i need to update the system to account for this.

**Comment by MrTobyP3** [comment]
I am still getting the same error. Has this issue ever been fixed?

**Comment by danielkerr** [comment]
whats ur username?

**Comment by danielkerr** [comment]
should be working now. silly redirect issue. it redirected to soon and did not load the currency class causing a 404.
