### ISSUE TITLE
Opencart 3 - Not allowed to change the default theme to a custom one

### ISSUE THREAD

**Issue by chainboost** [opencart/opencart#5626]
If I try to change my theme via **Extensions > Themes > Default Store Theme** I get the following message: _Warning: You do not have permission to modify the default store theme!_

**Comment by lz1nud** [comment]
also if try to change any settings on default theme, shows the same message.

**Comment by waxedperfection** [comment]
is that the same issue as reported here:-
https://github.com/opencart/opencart/issues/5617

its seems to have been fixed on 3.0.0.1
