### ISSUE TITLE
Extensions not installing on 3

### ISSUE THREAD

**Issue by amplogik** [opencart/opencart#5627]
With a fresh install, I can't get any extensions to install either via the installer or by uploading to my directory. 

Has the extension architecture changed substantially since 2?

Where can I find documentation on it, if it has?

**Comment by danielkerr** [comment]
yes unfortunately to many users just tick 3.0 without even testing. 

I have enabled an approval system to approve extension before they appear on the cloud

im having my staff go through them to make sure they actually work. 

we will start approving extension on monday.

**Comment by Pierneefie** [comment]
May be related ?
I get Fatal error when attempting to activate payment extensions in /admin.

Fatal error: Can't use method return value in write context in /home/progoco/public_html/ocart2/admin/controller/extension/payment/pp_express.php on line 1282

**Comment by danielkerr** [comment]
this is a different issue

**Comment by Pierneefie** [comment]
Dear danielkerr is there something obvious I can try to fix my problem?

**Comment by danielkerr** [comment]
if its not the same issue as these then create a new issue

https://github.com/opencart/opencart/issues/5600
https://github.com/opencart/opencart/issues/5507
https://github.com/opencart/opencart/issues/5084

**Comment by Pierneefie** [comment]
Thank you

**Comment by danielkerr** [comment]
also if ur still stuck u can contact my staff via the contact us form on opencart.com
