### ISSUE TITLE
Install 3.0.0.1 (Beta) PHP Fatal error

### ISSUE THREAD

**Issue by businessera** [opencart/opencart#5645]
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/0a).' 
in /system/library/template/Twig/Cache/Filesystem.php:62\nStack trace:\n#0 /system/library/template/Twig/Environment.php(400): Twig_Cache_Filesystem->write('/0a/0a5c1845863...', '<?php\\n\\n/* commo...')\n#1 /system/library/template/twig.php(30): Twig_Environment->loadTemplate('common/footer.t...')\n#2 /system/library/template.php(20): Template\\Twig->render('common/footer', false)\n#3 /system/engine/loader.php(85): Template->render('common/footer', false)\n#4 /install/controller/common/footer.php(11): Loader->view('common/footer', Array)\n#5 [internal function]: ControllerCommonFooter->index(Array)\n#6 /system/library/template/Twig/Cache/Filesystem.php on line 62

**Comment by Aranarius** [comment]
the same stuff
