### ISSUE TITLE
Translation install

### ISSUE THREAD

**Issue by ManoelVidal** [opencart/opencart#5654]
Can I make a pull request from the Portuguese translation of the installation?
Or is it not appropriate?

In Brazil, OpenCart is one of the most used platforms.

**Comment by danielkerr** [comment]
Are u going to maintain the translation for life?

**Comment by RaidoDev** [comment]
@danielkerr maybe you should fire up some centralized translation tool or repo?

**Comment by danielkerr** [comment]
We use cwodin

**Comment by danielkerr** [comment]
Needs some one to manage it properly

**Comment by ManoelVidal** [comment]
You're right @danielkerr 👍  

I maintain the translation to Brazil (not official) since 2010, in Marketplace and GitHub since 2014:
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=19865
https://github.com/opencartbrasil/traducao

Are there plans to load the translation of the crowdin installation?
https://crowdin.com/project/opencart

I would like to manage if possible a translation into Brazil in crowdin

**Comment by danielkerr** [comment]
the plan is to let people use crowdin then when the translation is 100%
complete release as a few extension
