### ISSUE TITLE
Incorrect price with Tax calculations (rounding or priorities?) !

### ISSUE THREAD

**Issue by RaidoDev** [opencart/opencart#5657]
Version: master branch
Reproduce:
- set Tax to 21%
- set product price (without tax) to **$1.83** (will be calculated as **$2.22** with tax)
- add to cart 100pcs of the product.

The total SUM will be calculated as **$221.79** !!!

There is kinda huge (0.21 €) price difference.

![image](https://user-images.githubusercontent.com/26715484/27789218-4c798950-5ff4-11e7-9545-caa40f9f0872.png)

**Comment by danielkerr** [comment]
master is not the latest version use the dev one.

**Comment by RaidoDev** [comment]
Sorry, my bad - The problem is with more than 2 decimal places (updated the issue). 
The same appears on DEV branch too. This is NOT a correct way, as there can be many cases, when product price must have more than 2 decimal places. The most common: 
(on DEV branch tested)
- set price to **$1.83** without tax (again: this is with **two decimals, so the "correct" way**
- set tax to 21%
- go to web shop. Change currency to GBP
- add 100 products to cart. The same problem.
![image](https://user-images.githubusercontent.com/26715484/27790917-4cb94098-5ffb-11e7-8961-7edc965facb7.png)

**Comment by RaidoDev** [comment]
@danielkerr you will reopen this or should I create a new issue?

**Comment by danielkerr** [comment]
im not reopening and if u open an issue i will close it

**Comment by RaidoDev** [comment]
Can you, please, at least write your opinion on this? Is it bug, wont fix, by design, planned?
