### ISSUE TITLE
Twig cache

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#5660]
You can also add the auto_reload option to common/developer.

> auto_reload boolean
> 
> When developing with Twig, it's useful to recompile the template whenever the source code changes. If you don't provide a value for the auto_reload option, it will be determined automatically based on the debug value.
>

**Comment by danielkerr** [comment]
i have under admin / dashboard / settings icon

**Comment by danijelGombac** [comment]
What is under admin / dashboard / settings icon? I do not understand.

**Comment by RaidoDev** [comment]
![image](https://user-images.githubusercontent.com/26715484/27793951-c15a8bb6-6008-11e7-8538-6d97ec91d466.png)

Although - CLOSING this window, generates JSON error, because json response loads: ``` Page Not Found!
The page you are looking for could not be found! Please contact your administrator if the problem persists.```

**Comment by fbens** [comment]
Thank you.its ok now.
