### ISSUE TITLE
Fresh Installation Errors - Opencart version 3.0

### ISSUE THREAD

**Issue by kostasmoure** [opencart/opencart#5661]
Hi i have the following errors when trying to install the new version of opencart(3.x),
Those errors appears at 1st step and continue to the last step.

Warning: fopen(/var/lib/php/session/sess_ffee82816dfcd6bb1065a22955): failed to open stream: Permission denied in /chroot/home///html/system/library/session/file.php on line 39Warning: flock() expects parameter 1 to be resource, boolean given in /chroot/home///html/system/library/session/file.php on line 41Warning: fwrite() expects parameter 1 to be resource, boolean given in /chroot/home///html/system/library/session/file.php on line 43Warning: fflush() expects parameter 1 to be resource, boolean given in /chroot/home///html/system/library/session/file.php on line 45Warning: flock() expects parameter 1 to be resource, boolean given in /chroot/home///html/system/library/session/file.php on line 47Warning: fclose() expects parameter 1 to be resource, boolean given in /chroot/home///html/system/library/session/file.php on line 49

The post was labeled as "in progress" but its closed why?

post #5571

**Comment by danielkerr** [comment]
fixed in dev

**Comment by kostasmoure** [comment]
ok Daniel i didn't new cause nobody replied...

thank you
