### ISSUE TITLE
cart.php at opencart ver. 3.0.0.0

### ISSUE THREAD

**Issue by melvin16** [opencart/opencart#5665]
Hello,
I found on folder catalog>language>en-gb>checkout>cart.php on line 21,

$_['text_length'] = ' for %s payments'

It seems like uncompleted program, is any body having suggestions about it?
I'm so grateful for your kindly suggestions about it and thank you in advance for your kindly response.
Best regards,
melvin16

**Comment by danielkerr** [comment]
i think needs deleting its not used anywhere

**Comment by melvin16** [comment]
This similar matter is also found at folder catalog>en-gb>extension>payment>pp_express.php at line 12

$_['text_length']             = ' for %s payments';

It is also needs deleting, isn't it?
Best regards.
melvin16

**Comment by ADDCreative** [comment]
@melvin16 ```$_['text_length'] = ' for %s payments';``` is used here: https://github.com/opencart/opencart/blob/97fde2b479cc8972408b36447e9c0a62223ed8f3/upload/catalog/model/extension/payment/pp_express.php#L226

So needs to be kept in pp_express.php.

```$_['text_until_cancelled']     = 'until cancelled';``` in cart.php dosen't look to be used.

Cancelled is spelt wrongly in ```$_['text_payment_cancel']      = '%s every %d %s(s) until canceled';```

**Comment by ADDCreative** [comment]
Actually cancelled can be spelt both ways depending on whether it's American or British spelling.

Canceled with one l appears 55 times in the code.
https://github.com/opencart/opencart/search?utf8=%E2%9C%93&q=canceled&type=

Canceled with two ls appears 41 times.
https://github.com/opencart/opencart/search?utf8=%E2%9C%93&q=cancelled&type=

**Comment by danielkerr** [comment]
sort this later,ikt will cause an issue if changed
