### ISSUE TITLE
bug for 3.0.0.0

### ISSUE THREAD

**Issue by tofizhou** [opencart/opencart#5666]
Extensions Home Extensions
 Extension List
Choose the extension type-----payments

Fatal error: Can't use method return value in write context in /home/public_html/admin/controller/extension/payment/pp_express.php on line 1282

**Comment by danielkerr** [comment]
i can not replicate

**Comment by danielkerr** [comment]
line 1288 is

		if ($this->config->get('payment_pp_express_username') != 0 || !empty($this->config->get('payment_pp_express_username')) || !empty($this->config->get('payment_pp_express_sandbox_username'))) {
