### ISSUE TITLE
I am using opencart 2.3.0.3 & I want to add contact us page in topmenu. Is there any way?When I clicked on top menu it must redirect to contact us page? How to that?

### ISSUE THREAD

**Issue by ritesh4716** [opencart/opencart#5678]

**Comment by danielkerr** [comment]
ask int he forum but its just a matter of adding an an entry into the category array in the header

**Comment by ritesh4716** [comment]
You aren't understand I want to header menu link in opencart that redirect to my footer page elements(contact us)

**Comment by osworx** [comment]
As Daniel said: ask in the Forum.
Or look at the Extensions.

**Comment by webcorvo** [comment]
@ritesh4716  https://forum.opencart.com/
post there that i help you ;o)
