### ISSUE TITLE
Custom Theme doesn't create in Opencart 3.0.1.1 version.

### ISSUE THREAD

**Issue by Nikhil-kotadiya** [opencart/opencart#5679]
Go to > Extension > Extension >Themes > select Custom theme Also, rename the config-dist.php file.

**Comment by danielkerr** [comment]
Also, rename the config-dist.php file.?

the 1st one is already fixed in admin

**Comment by scf8127** [comment]
i found issue when add new theme then not work	
admin/controller/extension/theme/default.php
	
Line No 120
 $setting_info = $this->model_setting_setting->getSetting('default', $this->request->get['store_id']);

replace with 

$setting_info = $this->model_setting_setting->getSetting('theme_default', $this->request->get['store_id']);

Thanks
