### ISSUE TITLE
upgrade from 3.0.0.0 to 3.0.1.1 error

### ISSUE THREAD

**Issue by tana2017** [opencart/opencart#5682]
When I try to upgrade, I am getting this error:

Error Code(0): Error: Table 'allograf_ocar159.oc8h_url_alias' doesn't exist
Error No: 1146
SHOW INDEX FROM `oc8h_url_alias` WHERE Key_name != 'PRIMARY' in /system/library/db/mysqli.php on line 40

**Comment by naturecr** [comment]
Leave I have the same error when I try to upgrade from 3.0.0.0 to a higher number:

Error Code(0): Error: Table 'allograf_ocar159.oc8h_url_alias' doesn't exist
 Error No: 1146
 SHOW INDEX FROM  oc8h_url_alias  WHERE Key_name != 'PRIMARY' in /system/library/db/mysqli.php on line 40

I see a closure to the issue, but cannot find out what I need to do.
Thank you
