### ISSUE TITLE
Attempt to install upgrade from ver 3.0.0.0 to higher ver returns error

### ISSUE THREAD

**Issue by naturecr** [opencart/opencart#5684]
I noticed some more recent versions were out, so I tried to upgrade by using install. The message below appeared in red. I saw that another user had the error but then closed the issue, but no explanation was given , so I am stuck. Thank you

Error Code(0): Error: Table 'naturecr_opencart33test.oc_url_alias' doesn't exist
Error No: 1146
SHOW INDEX FROM `oc_url_alias` WHERE Key_name != 'PRIMARY' in /home/naturecr/public_html/opencart33test/system/library/db/mysqli.php on line 40

**Comment by danielkerr** [comment]
yes trhis has been fied in the latest release

**Comment by danielkerr** [comment]
any major issue we do quick release fixes until stable. unless any one reports anything big in the next few days. easy to upgrade though

**Comment by naturecr** [comment]
Thank you, 
Does this mean settings I have made in the admin folder will be overwritten, if I ftp all of the files and folders to the 3.0.0.0 installation?

**Comment by naturecr** [comment]
I always fail to read the instructions, Thank you for spelling it out step by step.
I with draw my question and thank you for your patients.

**Comment by danielkerr** [comment]
@naturecr there are no db changes. u can literately just upload the files to override whats there.
