### ISSUE TITLE
After upgrade from OC 3.0.0.0 to OC 3.0.1.1; admin login attempt returns this series of errors.

### ISSUE THREAD

**Issue by naturecr** [opencart/opencart#5688]
I had just downloaded the opencart-master-zip version 3.0.1.1. I followed the instructions as best I could for upgrade. I used the old config.php and admin/config.php files. I uploaded all folders to website and over-wrote previous ones. All permissions were set 777. The upgrade progress line made it all the way across this time. Yea!  The issues started when I tried to see the admin page and the store page. The error shown below is from the admin page. I don’t know where the startup.php file is in the folder collection.

Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Warning: Cannot modify header information - headers already sent by (output started at /home/naturecr/public_html/opencart33test/system/framework.php:42) in /home/naturecr/public_html/opencart33test/system/framework.php on line 108Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_CACHE - assumed 'DIR_CACHE' in /home/naturecr/public_html/opencart33test/system/library/cache/file.php on line 9Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/naturecr/public_html/opencart33test/system/library/log.php on line 6Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Notice: Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/naturecr/public_html/opencart33test/system/library/log.php on line 6Notice: Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/naturecr/public_html/opencart33test/system/library/log.php on line 6Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/naturecr/public_html/opencart33test/system/startup.php on line 59Warning: Cannot modify header information - headers already sent by (output started at /home/naturecr/public_html/opencart33test/system/framework.php:42) in /home/naturecr/public_html/opencart33test/system/library/response.php on line 12

**Comment by danielkerr** [comment]
go to config.php

user this code and replace the http and db info with your own 

```
<?php
// HTTP
define('HTTP_SERVER', 'http://yourhost/opencart-master/upload/');

// HTTPS
define('HTTPS_SERVER', 'http://yourhost/opencart-master/upload/');

// DIR
define('DIR_APPLICATION', str_replace('\\', '/', realpath(dirname(__FILE__))) . '/catalog/');
define('DIR_SYSTEM', str_replace('\\', '/', realpath(dirname(__FILE__))) . '/system/');
define('DIR_IMAGE', str_replace('\\', '/', realpath(dirname(__FILE__))) . '/image/');
define('DIR_STORAGE', DIR_SYSTEM . 'storage/');
define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');
define('DIR_TEMPLATE', DIR_APPLICATION . 'view/theme/');
define('DIR_CONFIG', DIR_SYSTEM . 'config/');
define('DIR_CACHE', DIR_STORAGE . 'cache/');
define('DIR_DOWNLOAD', DIR_STORAGE . 'download/');
define('DIR_LOGS', DIR_STORAGE . 'logs/');
define('DIR_MODIFICATION', DIR_STORAGE . 'modification/');
define('DIR_SESSION', DIR_STORAGE . 'session/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'root');
define('DB_PASSWORD', '');
define('DB_DATABASE', 'opencart-master');
define('DB_PORT', '3306');
define('DB_PREFIX', 'oc_');
```

**Comment by danielkerr** [comment]
go to admin/config.php

<?php
// HTTP
define('HTTP_SERVER', 'http://yourhost.com/admin/');
define('HTTP_CATALOG', 'http://yourhost.com/');

// HTTPS
define('HTTPS_SERVER', 'http://yourhost.com/admin/');
define('HTTPS_CATALOG', 'http://yourhost.com/');

// DIR
define('DIR_APPLICATION', str_replace('\\', '/', realpath(dirname(__FILE__))) . '/');
define('DIR_SYSTEM', str_replace('\\', '/', realpath(dirname(__FILE__) . '../')) . '/system/');
define('DIR_IMAGE', str_replace('\\', '/', realpath(dirname(__FILE__) . '../')) . '/image/');
define('DIR_STORAGE', DIR_SYSTEM . 'storage/');
define('DIR_CATALOG', 'C:/xampp/htdocs/opencart-master/upload/catalog/');
define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');
define('DIR_TEMPLATE', DIR_APPLICATION . 'view/template/');
define('DIR_CONFIG', DIR_SYSTEM . 'config/');
define('DIR_CACHE', DIR_STORAGE . 'cache/');
define('DIR_DOWNLOAD', DIR_STORAGE . 'download/');
define('DIR_LOGS', DIR_STORAGE . 'logs/');
define('DIR_MODIFICATION', DIR_STORAGE . 'modification/');
define('DIR_SESSION', DIR_STORAGE . 'session/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'root');
define('DB_PASSWORD', '');
define('DB_DATABASE', '');
define('DB_PORT', '3306');
define('DB_PREFIX', 'oc_');

// OpenCart API
define('OPENCART_SERVER', 'https://www.opencart.com/');

**Comment by danielkerr** [comment]
go to admin/config.php

```
<?php
// HTTP
define('HTTP_SERVER', 'http://yourhost.com/admin/');
define('HTTP_CATALOG', 'http://yourhost.com/');

// HTTPS
define('HTTPS_SERVER', 'http://yourhost.com/admin/');
define('HTTPS_CATALOG', 'http://yourhost.com/');

// DIR
define('DIR_APPLICATION', str_replace('\\', '/', realpath(dirname(__FILE__))) . '/');
define('DIR_SYSTEM', str_replace('\\', '/', realpath(dirname(__FILE__) . '../')) . '/system/');
define('DIR_IMAGE', str_replace('\\', '/', realpath(dirname(__FILE__) . '../')) . '/image/');
define('DIR_STORAGE', DIR_SYSTEM . 'storage/');
define('DIR_CATALOG', 'C:/xampp/htdocs/opencart-master/upload/catalog/');
define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');
define('DIR_TEMPLATE', DIR_APPLICATION . 'view/template/');
define('DIR_CONFIG', DIR_SYSTEM . 'config/');
define('DIR_CACHE', DIR_STORAGE . 'cache/');
define('DIR_DOWNLOAD', DIR_STORAGE . 'download/');
define('DIR_LOGS', DIR_STORAGE . 'logs/');
define('DIR_MODIFICATION', DIR_STORAGE . 'modification/');
define('DIR_SESSION', DIR_STORAGE . 'session/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'root');
define('DB_PASSWORD', '');
define('DB_DATABASE', '');
define('DB_PORT', '3306');
define('DB_PREFIX', 'oc_');

// OpenCart API
define('OPENCART_SERVER', 'https://www.opencart.com/');

```

**Comment by danielkerr** [comment]
i will do a new release in the next few hours im just waiting for james to wake up.

**Comment by danielkerr** [comment]
Ok fixed in latest release

**Comment by ohmashoes** [comment]
Help Pls.
I followed the steps above but now I am getting this error message when I try to go to admin folder:

Warning: require_once(/system/startup.php): failed to open stream: No such file or directory in /homepages/0/d417133930/htdocs/admin060313/index.php on line 21

Fatal error: require_once(): Failed opening required '/system/startup.php' (include_path='.:/usr/lib/php7.1') in /homepages/0/d417133930/htdocs/admin060313/index.php on line 21

I upgraded from 1.5.6.4 to 3.0.2

Thanks in advance

**Comment by danielkerr** [comment]
ask in the forum. this is not a support system.

**Comment by ohmashoes** [comment]
How do you mean? I thought we can report issues on here.

**Comment by xdjxdaveyx** [comment]
I think ..

> define('DIR_CATALOG', 'C:/xampp/htdocs/opencart-master/upload/catalog/');

should be 

define('DIR_CATALOG',  DIR_APPLICATION . 'catalogue/');

.. in admin/config.php

**Comment by naturecr** [comment]
I wish to mute this closed thread

**Comment by xdjxdaveyx** [comment]
You should go to github and unstar it then my friend.
Dave.
________________________________
