### ISSUE TITLE
Get Current URL

### ISSUE THREAD

**Issue by member999** [opencart/opencart#5690]
How can I get the current URL in OC 3.0.1.1 ?
Here is my code in OC 2.3.0.2 :
if(!empty($_SERVER['HTTPS'])){
	 $url = "https://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'];
 }else{
	 $url = "http://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']; 
 }
Thanks for reading !

**Comment by OpenCartAddons** [comment]
Please post your question in the forums and someone can help you there.   This is not the place to request support.

Regards,
Joel.

**Comment by member999** [comment]
Thank you ! My bad
