### ISSUE TITLE
Opencart 3.0.1.1: Fatal errors in Extensions >> Payments

### ISSUE THREAD

**Issue by andreab79** [opencart/opencart#5694]
In control panel, going to Extensions >> Payments shows this error

Fatal error: Can't use method return value in write context in admin/controller/extension/payment/pp_express.php on line 1282

and if i disable pp_express.php file, shows me this error

Fatal error: Can't use method return value in write context in admin/controller/extension/payment/pp_braintree.php on line 1032

if i disable also pp_braintree.php file, shows me payments list correctly

**Comment by danielkerr** [comment]
i can notr replicdate!

give me more info! version! php version, etc.. guessing games guessing games magic psychic wasting my time guessing games

**Comment by andreab79** [comment]
hi, you can read opencart version on title, about php is 5.4.45

about guessing games?

**Comment by danielkerr** [comment]
ok i have released another version but does not have ur fix in. can u change php versions? i will fix in maybe monday.

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/issues/5694

**Comment by nikto1** [comment]
i got exactly the same error, php version 5.4.+

**Comment by danielkerr** [comment]
U tried the fix?

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/commit/1060fb74d00a33262c029d7b2a5bbf8661e90c6c

**Comment by nikto1** [comment]
@danielkerr working now.

**Comment by greenhalse** [comment]
Thanks for this thread guys.
I had exactly the same issue with a fresh install of 3.0.0.0 and Braintree Payment Gateway Pro (v300.1)
Applied the patch and all was good.
GB.
