### ISSUE TITLE
datetime  type field db

### ISSUE THREAD

**Issue by webcorvo** [opencart/opencart#5698]
Hi,
Can any one explain to me why all the data fields of db is **datetime** type?

I think that the should be **timestamp** type

And on **language/en-gb/en-gb.php**
By default the variable **date_format_short** should be - **$_['date_format_short'] = 'Y/m/d H:i:s';**

**Comment by osworx** [comment]
Explain no, but a good explaination of both:
http://www.tech-recipes.com/rx/22599/mysql-datetime-vs-timestamp-data-type/

And **$_['date_format_short']** as it says: date and not date AND time .. so at least Y.m.d or Y/m/d or d.m.Y or d/m/Y or whatever you prefer ..

**Comment by danielkerr** [comment]
It's easier to read and generate. Also don't waste my time with crap like this. I just released 3.x. U extecpt me to change things that will break everything for what ur personal preference.

**Comment by webcorvo** [comment]
@osworx  but as you know, the datetime data type values are **unchanged** in relation to time zone.
In all cases you must change **date_default_timezone_set**(''); to your own country.

**Comment by danielkerr** [comment]
ok how much of an issue will this be if i switched?

**Comment by danielkerr** [comment]
peoples stores going down?
