### ISSUE TITLE
OC 3.0.1.2 - Theme Editor only works for default theme?

### ISSUE THREAD

**Issue by Pelham81** [opencart/opencart#5700]
I am playing around with OC 3.01.2 on a fresh local install.

1. I duplicated the default theme into a custom folder and made two lines of hard-coded edits to the theme twig files to see how they view in the theme editor out of curiosity.

2. I set the theme to point to the custom theme folder.

3. I cleared the cache folder since some of the changes did not take effect on the front end / store view. After the cache clear, my custom template took effect and the changes I made showed up.

4. I opened the theme editor, but it still shows only the default theme folder files to edit.

So... the problem I am seeing is that I cannot use the theme editor for my custom theme folder. Is this intentional? Or did I somehow miss something? I figure I would post it here in case it might be a potential issue.

**Comment by danielkerr** [comment]
for default yes. the directory section thats in the admin / extension / theme / default was only put there really for backwards compatibility with the old version.

if u want to duplicate a theme u also need to make your own extension to go under admin / extension / theme /
