### ISSUE TITLE
Opencart 3.0.1.1(2) extension->payment error

### ISSUE THREAD

**Issue by kostasmoure** [opencart/opencart#5703]
When i am trying to access the payment methods in admin i get "Internal server error". This happens only in payments and all other works

check the image 

http://i65.tinypic.com/2emphmb.jpg

**Comment by danielkerr** [comment]
what version of php are u using?

**Comment by kostasmoure** [comment]
5.4.45

**Comment by danielkerr** [comment]
it says in the page capthca

**Comment by kostasmoure** [comment]
sorry but i didn't understood what you are saying...
what it says in screenshot captcha? which screenshot?
Inside the screenshot you see the extension->Captchas and tried to move to payments and this error came

**Comment by danielkerr** [comment]
its ok im going to install 5.4 when i have time.

**Comment by danielkerr** [comment]
ok just installed PHP 5.4.31 and i still can not replicate your issue.

can u pm me your web site details via the opencart forum?

admin access

**Comment by kostasmoure** [comment]
yes

**Comment by danielkerr** [comment]
have u tried this fix?

https://github.com/opencart/opencart/commit/1060fb74d00a33262c029d7b2a5bbf8661e90c6c

**Comment by kostasmoure** [comment]
Just did and its working fine.

Thank you Daniel

**Comment by danielkerr** [comment]
great!

**Comment by Sachin1112** [comment]
i have the same issue how you resolve it.

**Comment by kostasmoure** [comment]
have you read the fix Daniel proposed?

[https://github.com/opencart/opencart/commit/1060fb74d00a33262c029d7b2a5bbf8661e90c6c](url)

**Comment by kostasmoure** [comment]
Read this:

https://github.com/opencart/opencart/commit/1060fb74d00a33262c029d7b2a5bbf8661e90c6c

**Comment by danielkerr** [comment]
IM just working on the main site. i will come fixing issues soon.
