### ISSUE TITLE
Error got after edited common/footer.twig in Theme Editor

### ISSUE THREAD

**Issue by jdotchai** [opencart/opencart#5704]
OpenCart 3.0.1.1

[error] 6032#0: *323 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Unable to create the cache directory (/00). in /system/library/template/Twig/Cache/Filesystem.php:62
Stack trace:
#0 /system/library/template/Twig/Environment.php(400): Twig_Cache_Filesystem->write('/00/004ee21b333...', '<?php\n\n/* __str...')
#1 /system/library/template/Twig/Environment.php(437): Twig_Environment->loadTemplate('__string_templa...')
#2 /catalog/controller/event/theme.php(35): Twig_Environment->createTemplate('<footer>\n  <div...')
#3 /system/engine/action.php(51): ControllerEventTheme->index('common/footer', Array)
#4 /system/engine/event.php(37): Action->execute(Object(Registry), Array)
#5 /system/engine/loader.php(73): Event->trigger('view/common/foo...', Array)
#6 /catalog/controller/common/footer.php(61): Loader->view('common/footer', Array)
#7 /system/engine/action.ph" while reading response header from upstream

**Comment by jdotchai** [comment]
Similar issue with [https://github.com/opencart/opencart/issues/5645](https://github.com/opencart/opencart/issues/5645), have checked the upload/system/config/install.php and the "$_['template_cache']    = true;" is exists.

**Comment by danielkerr** [comment]
its in the admin where u choose the cache. i set the system to disable the cache buttons if eval was unavailable on your server. best thing is to clear the cache directory manually via FTP.

**Comment by jdotchai** [comment]
Are you mean clearing everything inside the "storage/cache" ?

**Comment by jdotchai** [comment]
I clear everything inside "storage/cache" except index.html but error still exists. Admin area is fine but store homepage return 500 with the error.

**Comment by danielkerr** [comment]
is ur cache directory defined?

**Comment by jdotchai** [comment]
Yes below are my config.php & admin/config.php . Have tried for hours including reinstall but still the same error.

My storage directory in /www/domain.com/system/storage

config.php

// HTTP
define('HTTP_SERVER', 'https://domain.com/');

// HTTPS
define('HTTPS_SERVER', 'https://domain.com/');

// DIR
define('DIR_APPLICATION', '/www/domain.com/catalog/');
define('DIR_SYSTEM', '/www/domain.com/system/');
define('DIR_IMAGE', '/www/domain.com/image/');


define('DIR_STORAGE', DIR_SYSTEM . 'storage/');
//define('DIR_STORAGE', '/www/storage/');
define('DIR_LANGUAGE', '/www/domain.com/catalog/language/');
define('DIR_TEMPLATE', '/www/domain.com/catalog/view/theme/');
define('DIR_CONFIG', '/www/domain.com/system/config/');
define('DIR_CACHE', DIR_STORAGE.'cache/');
define('DIR_DOWNLOAD', DIR_STORAGE.'download/');
define('DIR_LOGS', DIR_STORAGE.'logs/');
define('DIR_MODIFICATION', DIR_STORAGE.'modification/');
define('DIR_UPLOAD', DIR_STORAGE.'upload/');


——

admin/config.php

// HTTP
define('HTTP_SERVER', 'https://domain.com/admin/');
define('HTTP_CATALOG', 'https://domain.com/');

// HTTPS
define('HTTPS_SERVER', 'https://domain.com/admin/');
define('HTTPS_CATALOG', 'https://domain.com/');

// DIR
define('DIR_APPLICATION', '/www/domain.com/admin/');
define('DIR_SYSTEM', '/www/domain.com/system/');
define('DIR_IMAGE', '/www/domain.com/image/');


define('DIR_STORAGE', DIR_SYSTEM . 'storage/');
//define('DIR_STORAGE', '/www/storage/');
define('DIR_LANGUAGE', '/www/domain.com/admin/language/');
define('DIR_TEMPLATE', '/www/domain.com/admin/view/template/');
define('DIR_CONFIG', '/www/domain.com/system/config/');
define('DIR_CACHE', DIR_STORAGE.'cache/');
define('DIR_DOWNLOAD', DIR_STORAGE.'download/');
define('DIR_LOGS', DIR_STORAGE.'logs/');
define('DIR_MODIFICATION', DIR_STORAGE.'modification/');
define('DIR_UPLOAD', DIR_STORAGE.'upload/');
define('DIR_CATALOG', '/www/domain.com/catalog/');

**Comment by danielkerr** [comment]
ok change install the latest master or try this fix

https://github.com/opencart/opencart/commit/8615d9f684fe5ddb1e9d01a40bc8b9bca2d22a5c

**Comment by jdotchai** [comment]
Fixed! Thank you!!
