### ISSUE TITLE
Create class Product, Client, Address, etc.

### ISSUE THREAD

**Issue by valdeirpsr** [opencart/opencart#5710]
Why not create a class for these options?

It would not be better to work as follows:

```php
/* Product */
$product = new Product();
$product->setName( 'Product Name' );

$description = new ProductDescription();
$description->setTitle( `language_id`, "Title" );
$description->setDescription( `language_id`, "Descrição" );
$product->setDescription( $description );

/* Save */
$this->model_catalog_product->save( $product )

/* Get */
public function getProduct()
{
    /* code Here */
    return $product; /* Object Product */
}

/* ArrayIterator */
public function getProducts()
{
    $products = new ArrayIterator( $query->rows );
    return $products; /* ArrayIterator[Object Product] */
}

$products = $this->model_catalog_product->getProducts();
$products->next();
$products->next();
$products->next();

/* Customer */
$customer = new Customer();
$customer->setAddress( new Address() );
$customer->setCustomFields( new CustomFields() );
```

That would be much better than working with arrays.

**Comment by danielkerr** [comment]
So I'll n the real world products can set their own names?

**Comment by valdeirpsr** [comment]
This leaves the code more organized, easy to scale and much easier to maintain in code, validation, etc.

His course of PHP was fake? Have not you learned about objects?

You're a good admin, but I hope you learn to be a good developer.

Https://softwareengineering.stackexchange.com/a/297109
Https://stackoverflow.com/a/3863520
Https://stackoverflow.com/a/23999743
Https://stackoverflow.com/a/3709721
