### ISSUE TITLE
OC 3.0.1.2: twig templates cannot be modified via view/*/before events

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#5716]
It is not possible to modify a twig-template via a **view/*/before** event trigger. The event would be triggered, but the subsequent twig rendering engine would only allow paths from the **DIR_TEMPLATE** path, or, if OCmod is enabled, from the  **DIR_MODIFICATION.'catalog/view/theme/'** path. 

You wouldn't be able to store a modified twig-template anywhere else, such as in the **DIR_CACHE**. You might as well forget about **view/*/before** events altogether and use OCmod XML files for modifying twig-templates. 

Suggested fix:
In file **system/template/twig.php**, always have this in method **render**:
```
	public function render($template, $cache = false) {
		// specify where to look for templates
		$loader = new \Twig_Loader_Filesystem();
		if (defined('DIR_CATALOG') && is_dir(DIR_MODIFICATION . 'admin/view/template/')) {	
			$loader->addPath(DIR_CACHE . 'admin/view/template/');
			$loader->addPath(DIR_MODIFICATION . 'admin/view/template/');
		} elseif (is_dir(DIR_MODIFICATION . 'catalog/view/theme/')) {
			$loader->addPath(DIR_CACHE . 'catalog/view/theme/');
			$loader->addPath(DIR_MODIFICATION . 'catalog/view/theme/');
		}
		$loader->addPath(DIR_TEMPLATE);	
		......
	}
```

**Comment by danielkerr** [comment]
try the latest commit

**Comment by mhcwebdesign** [comment]
Still not working! Basically, a **view/*/before** event can grab the twig-template file and modify it in a memory buffer. But where is the result to be stored? It shouldn't be written to the DIR_TEMPLATE, nor to the DIR_MODIFICATION. The twig engine at **system/template/twig.php** needs to check for modified templates in the following folders, in the following order, for frontend templates:

DIR_CACHE . 'catalog/view/theme/'
DIR_MODIFICATION . 'catalog/view/theme/
DIR_TEMPLATE

**Comment by danielkerr** [comment]
well this is the issue i was when i was building the system. u can only output once. wring the output to a file in the mod directory might be the best choice.

**Comment by mhcwebdesign** [comment]
Writing to the **DIR_MODIFICATION . 'catalog/view/theme/** will be fine, too. However, in that case the **system/template/twig.php** should always have this code by default:
```
	public function render($template, $cache = false) {
		// specify where to look for templates
		$loader = new \Twig_Loader_Filesystem();
		if (defined('DIR_CATALOG') && is_dir(DIR_MODIFICATION . 'admin/view/template/')) {	
			$loader->addPath(DIR_MODIFICATION . 'admin/view/template/');
		} elseif (is_dir(DIR_MODIFICATION . 'catalog/view/theme/')) {
			$loader->addPath(DIR_MODIFICATION . 'catalog/view/theme/');
		}
		$loader->addPath(DIR_TEMPLATE);	
		......
````
At the moment this code is only there when OCmod has generated a file at DIR_MODIFICATION.'system/library/template/twig.php'. But it should be there regardless of whether OCmod has been run or not!

**Comment by danielkerr** [comment]
I think we need event added before the last call to create a cache file. if cache exists use that.

**Comment by danielkerr** [comment]
try my latest commit. im still testing it but seems to be solid enough.

**Comment by mhcwebdesign** [comment]
Thanks Daniel, I am going to test it now.

**Comment by danielkerr** [comment]
im closing this as it seems to work really well

**Comment by mhcwebdesign** [comment]
Your latest change works to a degree. However, if there is a OCmod xml attempting to do some modifications, too, to the same twig-template, it gets ignored! We need a way for both OCmod and event handlers to be able to do modifications to the same twig-template!

**Comment by danielkerr** [comment]
its a bit hard to apply mods on a template held in a the db.

**Comment by mhcwebdesign** [comment]
Admittedly, yes, it would be hard for templates held in the DB.
But modifications done via OCmod should not be lost when there are also modifications via **view/*/before** events to the same template.

**Comment by mhcwebdesign** [comment]
I took a closer look at: Your theme editor definitely bypasses any modifications introduced by OCmod. 
However, OCmod modifications should be loaded first, if there, and then the **view/*/before** events are to be triggered. Hence, I think this would need some changes to the file '**system/loader.php**' where the line

```
		// Template contents. Not the output!
		$template = '';
```
should be changed so that if there is a modification done by OCmod, it should be loaded into the $template, before triggering the before events!

**Comment by mhcwebdesign** [comment]
Could we please sort out the issues with the **view/*/before** events also for the admin side?

The file
