### ISSUE TITLE
OpenBay ProModule error (OC 3.0.1.0)

### ISSUE THREAD

**Issue by evpadallas** [opencart/opencart#5717]
If clicking on "Items", "Orders" or "Manage" I have error like:

Warning: Illegal offset type in storage/modification/system/library/language.php on line 42Warning: Illegal offset type in storage/modification/system/library/language.php on line 43
Fatal error: Call to a member function load() on null in storage/modification/system/library/language.php on line 43

$this->data[$key]->load($filename);

P.S. Warning of module (Unknown or missing OpenCart version supplied. (3.0.1.0))

**Comment by jamesallsup** [comment]
This has been resolved on an update - if you contact the support team for OpenBay at https://help.openbaypro.com/ they will be able to provide you will the latest version with this patch in.

It will also be merged shortly for the next OpenCart release too.

J
