### ISSUE TITLE
Download Opencart link from docs.opencart 404

### ISSUE THREAD

**Issue by StyxOfDynamite** [opencart/opencart#5719]
Not sure if there's a separate documentation repo but the following link

OpenCart website (recommended)

on http://docs.opencart.com/installation/

Takes you to a 404 page.

**Comment by webcorvo** [comment]
@StyxOfDynamite sorry but the link is working

**Comment by StyxOfDynamite** [comment]
To confirm then.

http://www.opencart.com/index.php?route=download/download/

This link works for you. The link I've provided is the page in question with the link on it, you know so you can identify the bug and fix it, obviously if I just told you the link above was broken you'd have a hard time finding all the links to it and updating them.

**Comment by danielkerr** [comment]
Yes should be CMS/download but there should be a redirect link

**Comment by StyxOfDynamite** [comment]
@danielkerr - I'm taking it 'Yes' isn't a response to me asking whether the http://www.opencart.com/index.php?route=download/download/ link works as your response suggests it _would_ work if a redirect was jn place  (which it isn't)

If you link me to the docs repo I can resolve it, either by fixing the link to be 'CMS/download' - which seems what you're suggesting, although a redirect fix would ensure any off-site resources linking to the download would also work so maybe a code fix and a server redirect fix is the solution to preserve off-site links. ?

**Comment by StyxOfDynamite** [comment]
Oh hang on, the redirect will work if you remove trailing /

I'll just submit a PR for that for the time being.

**Comment by StyxOfDynamite** [comment]
https://github.com/opencart/opencart.github.io/pull/62
