### ISSUE TITLE
OCmod doesn't overwrite files (version 3.0.1.2 and 3.0.1.1)

### ISSUE THREAD

**Issue by theJoff** [opencart/opencart#5722]
I am testing OCmod for OpenCart 3.0.1.2 (I had the exact same issue in 3.0.1.1).

I am testing a simple script:

`<?xml version="1.0" encoding="utf-8"?>
<modification>
    <name>Test</name>
    <code>Test</code>
    <version>1.0</version>
    <author>Test</author>
    <link>http://web.com</link>
    <file path="admin/view/template/catalog/product_form.twig">
        <operation>
            <search><![CDATA[
            <div id="content">
            ]]></search>
            <add position="replace"><![CDATA[
            <div id="content" class="yeah">
            ]]></add>
        </operation>
    </file>
</modification>`

Because of a [separate issue meaning I can't upload xml files directly](https://github.com/opencart/opencart/issues/5721), I saved this file as _install.xml_ and put it inside a directory named _mod_ along with an empty _upload_ directory.  I zipped up _mod_ and saved it as _mod.ocmod.zip_.

I uploaded _mod.ocmod.zip_ using the **Extensions installer**.  It uploaded/installed successfully and appears in the **Install history** list.

But when I view the **Modification List**, there is nothing there and there is no reference in the Log either.  Predictably, the modification hasn't worked when I view _product_form.twig_'s source.

**Comment by danielkerr** [comment]
needs to be called 

install.xml

**Comment by theJoff** [comment]
I _did_ save the file as install.xml...

**Comment by theJoff** [comment]
Hang on - schoolboy error - folder structure was wrong.  Apologies.  Loving your work...

**Comment by danielkerr** [comment]
im testign as will.

**Comment by theJoff** [comment]
Now the mod appears in the Modification List and the Log, but the modification still doesn't work, i.e. product_form.twig is still outputting 
`<div id="content">`
and not
`<div id="content" class="yeah">`

**Comment by danielkerr** [comment]
cheers. at least i tested iot again. i was getting worried.

**Comment by theJoff** [comment]
Thanks - seem to work fine now.
