### ISSUE TITLE
PayPal (Powered by Braintree) Extension returns 500 error (3.0.1.2)

### ISSUE THREAD

**Issue by theJoff** [opencart/opencart#5723]
After setting up PayPal (Powered by Braintree) on opencart 3.0.1.2 the edit page of the extension (/admin/index.php?route=extension/payment/pp_braintree&user_token=xxx) returns a 500 error, meaning it can't be enabled or configured.

**Comment by danielkerr** [comment]
any errors in the error log?

**Comment by danielkerr** [comment]
have u tried this fix?

https://github.com/opencart/opencart/commit/1060fb74d00a33262c029d7b2a5bbf8661e90c6c

**Comment by theJoff** [comment]
[10-Jul-2017 18:10:29 UTC] PHP Fatal error:  Class 'Braintree_Gateway' not found in ~admin/model/extension/payment/pp_braintree.php on line 158

**Comment by danielkerr** [comment]
cheers

**Comment by theJoff** [comment]
Tried the 1060fb7 fix and no difference... still get 500 error

**Comment by danielkerr** [comment]
if u downloaded from the master branch i think its missing some files that compose should autoload. checking into this.

**Comment by theJoff** [comment]
I installed 3.0.1.1 through softaculous but then upgraded to 3.0.1.2.  I downloaded it from opencart.com.

After the successful upgrade the version number is still saying 3.0.1.1...

**Comment by theJoff** [comment]
Where is the Braintree_Gateway class meant to be located?

**Comment by danielkerr** [comment]
it should be autoloaded. its in the main release. under the storage/vendor

**Comment by theJoff** [comment]
OK, I've located the class Braintree_Gateway in 

\system\storage\vendor\braintree\braintree_php\lib\Braintree\Gateway.php

It's there and was definitely uploaded.

Why is the system not loading it?  Is there a way I can force it to load?

Ta,

Joe

**Comment by danielkerr** [comment]
ok getting james to deal with this as its he built it and should be fully
working!

**Comment by theJoff** [comment]
Nice one thanks!

**Comment by theJoff** [comment]
Some more info:

If I uninstall/reinstall I can temporarily access the Braintree settings.  The 500 error happens after I select the _Connect with Braintree_ button and go through the process i.e. it takes me through the authorisation process on the Braintree site seemingly without error but when it redirects back to my site it then returns the 500 error.  From then on I get the 500 error when I try to edit it the settings.

So, I uninstall/reinstall to see if I can add the settings manually...

When I do this, I get the 500 error when I hit Save, and, if I go back to the settings they have not saved: all blank and disabled.

I have tried this multiple times.

When I configure the settings manually, I get the following error in the log:
`PHP Fatal error:  Class 'Braintree_Configuration' not found in ~/admin/controller/extension/payment/pp_braintree.php on line 1127`

And, as mentioned before, when I configure using the Connect button, I get the following error:
`PHP Fatal error:  Class 'Braintree_Gateway' not found in ~/admin/model/extension/payment/pp_braintree.php on line 158`

PHP version is 5.6.31 if that helps.

Thanks

**Comment by danielkerr** [comment]
i think its a path issue. autoloading is not setup properly. james is going to test it today.

**Comment by jamesallsup** [comment]
I have just run an automated build on the latest master and also installed a manual local one too.

Both worked without any issues - I also tested moving the vendor folder in and out of the web root, again no problems there.

Personally I would start over with a clean install of the latest from here : https://github.com/opencart/opencart/releases/download/3.0.1.2/3.0.1.2-opencart.zip

It just sounds like your autoloader.php isn't being picked up properly so a clean install should solve it for you.

Give that a try and let us know if you still have an issue after a clean install. FYI don't use 3rd party installers - a manual install is simple and also gets you used to where things should be in directories, configs etc

J

**Comment by danielkerr** [comment]
ok closing. i will monitor this ticket.

**Comment by theJoff** [comment]
Thanks.  Reinstalled and seems to work now.
