### ISSUE TITLE
Theme Editor is not functionnal

### ISSUE THREAD

**Issue by lemmel** [opencart/opencart#5727]
Hi.
I'm currently benchmarking opencart and I stumbled on a the weird behaviour of the Theme Editor : it may able to save template alteration, but it can't load them later.

I does happen with a fresh installation.

I explain myself:
- I go to Design -> theme Editor
- I select "common", then "header.twig"
- I alter the code by putting a simple "TOTO" string
- I save my change and get a " Success: You have modified themes! "
- i check my change on the front site: it did appear
- I log out from admin panel
- I log in 
- I go to Design -> theme Editor
- there is a line added in the "Theme History" table
- I select "common", then "header.twig"

My template change is gone: the "TOTO" string I added disappeared but the front site is ok.

There is no error message whatsoever in the logs.

Is there some cache to update ? Am I missing something ?

P.S. : I had further problems with the Theme Editor when I use several stores but it may be related to this one, so I prefer to stick to this simple and straight problem.

### How to reproduce
Just make a fresh installation
Alter the "header.twig" template

### Technical informations:
- opencart: 3.0.1.2
- nginx: 1.10
- PHP/FPM: 7.0, with modules: bcmath, cache-lite, curl, fxsl, http-request2, igbinary, intl, json, mbstring, mcrypt, memcached, msgpack, net-url2, pear, soap, xml, xml-htmlsax3, xml-rpc2, xml-svg, yac, yaml, zip, gd, mysql, readline, zip
- MariaDB: 10.1.23
- OS: debian stable

**Comment by danielkerr** [comment]
delete theme template cache via the settings icon on the dashboard or turn off template caching.

**Comment by danielkerr** [comment]
i just tested this and its working for me.

**Comment by lemmel** [comment]
Well maybe I do not undestand what you advise me to do because it doesn't solve my problem.
As I'm not precise enough because I'm not an english native speaker, I made a small video that illustrates my problem and my attempts to clear the caches.

As a reminder it is a vanilla installation of opencart.

Here is the video: 
[![Alt text](https://i.ytimg.com/vi/W91Mwiq4qRA/hqdefault.jpg)](https://youtu.be/W91Mwiq4qRA)

**Comment by danielkerr** [comment]
ok. a easy fix is to just use the edit button on the already modified entry. im not sure i can call this a bug.

**Comment by lemmel** [comment]
Thanks I have now a way to go around the problem :-)

Clearly if I modify a lot of templates (as I plan to do), being forced to scroll down, to find the template I want, is not the natural way to do; one do this only if he changes only a few template.

Furthermore it is quite natural to look for a template by using "Choose a template" list (as nothing alert you that the list contains only original template).

If it isn't a bug, then it may be a bad UX design.

**Comment by BrahmaputraChakraborty** [comment]
hey Lemmel, are you using softaculas to install opencart? i faced this problem also with softaculas.

**Comment by lemmel** [comment]
Sorry, I didn't use anything.

**Comment by ajumalp** [comment]
I also had similar issue. 
I once installed modificationmanager-3.0.0.3.ocmod.zip, then I remember the issue start after removing this extension. So I reinstalled it and now working fine.
