### ISSUE TITLE
OpenCart performs over 8000 SQL queries when accessing disabled category (DoS)

### ISSUE THREAD

**Issue by thesamarkand** [opencart/opencart#5731]
I have disabled some category, e. g. https://site.com/my-disabled-category.
There is a lot of products in this category, all products are still enabled.
Now go to https://site.com/my-disabled-category
OpenCart 2.3.2 will perform over 8000 SQL queries like this:

`SELECT DISTINCT *, pd.name AS name, p.image, m.name AS manufacturer, (SELECT price FROM _product_discount pd2 WHERE pd2.product_id = p.product_id AND pd2.customer_group_id = '1' AND pd2.quantity = '1' AND ((pd2.date_start = '0000-00-00' OR pd2.date_start < NOW()) AND (pd2.date_end = '0000-00-00' OR pd2.date_end > NOW())) ORDER BY pd2.priority ASC, pd2.price ASC LIMIT 1) AS discount, (SELECT price FROM _product_special ps WHERE ps.product_id = p.product_id AND ps.customer_group_id = '1' AND ((ps.date_start = '0000-00-00' OR ps.date_start < NOW()) AND (ps.date_end = '0000-00-00' OR ps.date_end > NOW())) ORDER BY ps.priority ASC, ps.price ASC LIMIT 1) AS special, (SELECT points FROM _product_reward pr WHERE pr.product_id = p.product_id AND pr.customer_group_id = '1') AS reward, (SELECT ss.name FROM _stock_status ss WHERE ss.stock_status_id = p.stock_status_id AND ss.language_id = '2') AS stock_status, (SELECT wcd.unit FROM _weight_class_description wcd WHERE p.weight_class_id = wcd.weight_class_id AND wcd.language_id = '2') AS weight_class, (SELECT lcd.unit FROM _length_class_description lcd WHERE p.length_class_id = lcd.length_class_id AND lcd.language_id = '2') AS length_class, (SELECT AVG(rating) AS total FROM _review r1 WHERE r1.product_id = p.product_id AND r1.status = '1' GROUP BY r1.product_id) AS rating, (SELECT COUNT(*) AS total FROM _review r2 WHERE r2.product_id = p.product_id AND r2.status = '1' GROUP BY r2.product_id) AS reviews, p.sort_order FROM _product p LEFT JOIN _product_description pd ON (p.product_id = pd.product_id) LEFT JOIN _product_to_store p2s ON (p.product_id = p2s.product_id) LEFT JOIN _manufacturer m ON (p.manufacturer_id = m.manufacturer_id) WHERE p.product_id = 'PRODUCT_ID' AND pd.language_id = '2' AND p.status = '1' AND p.date_available <= NOW() AND p2s.store_id = '0'`

`SELECT r.review_id, r.author, r.rating, r.text, p.product_id, pd.name, p.price, p.image, r.date_added FROM _review r LEFT JOIN _product p ON (r.product_id = p.product_id) LEFT JOIN _product_description pd ON (p.product_id = pd.product_id) WHERE p.product_id = 'PRODUCT_ID' AND p.date_available <= NOW() AND p.status = '1' AND r.status = '1' AND pd.language_id = '2' ORDER BY r.date_added DESC LIMIT 0,20`

OpenCart executes < 300 queries per page in normal operation, so executing 8000 queries per page in this case is a bug.

I think this is a security hole, because performing >8k queries introduces high load to server and can lead to denial of service (DoS) attack.

**Comment by danielkerr** [comment]
i don't believe this!

**Comment by thesamarkand** [comment]
How can I proove this?

**Comment by danielkerr** [comment]
do u have 8000 products listed?

also LIMIT 0,20

**Comment by danielkerr** [comment]
SHOW GLOBAL STATUS

**Comment by danielkerr** [comment]
i think u mean the amount of records the system has to go through not quires.

**Comment by RaidoDev** [comment]
The least effective queries in any situation are:
- if you have enabled product count in the category and you have many categories - there will be a bunch of "count" per category on every page you open. You can disable this in settings although I don't remember - does 2.3.2 version only "hides" the count or doesn't exec queries.
- SEO link generations, if you have many categories with a deep structure, then every product and category link is generated in a loop and takes a huge amount of queries.

But what you are writing is about "disabled" category. Can you provide more info, which queries are executed so much?

**Comment by thesamarkand** [comment]
What means "disabled"?
Go to Catalog, Categories, select category, press Edit, go to Data tab, set Status to Disabled.

When category is enabled, OpenCart performs 221 SQL queries, when category is disabled, it performs 8729 queries. So, I think, this is a bug.

 I have 210 products and 7 subcategories in this category.

I will try to reproduce bug on fresh installation, where can I get version 2.3.2?

**Comment by danielkerr** [comment]
Try this with other shopping carts and see what happens before u post this
crap.

**Comment by thesamarkand** [comment]
Fixed. This was a third-party extension bug, not OpenCart itself. Sorry.

**Comment by danielkerr** [comment]
well thank you for letting me know!
