### ISSUE TITLE
when I  upload opencart from localhost to server It gives 500 - Internal server error on godaddy.

### ISSUE THREAD

**Issue by ritesh4716** [opencart/opencart#5732]

**Comment by osworx** [comment]
Have you adopted the 2 config.php files?
Beside this, questions like that have to asked in the forum.

**Comment by danielkerr** [comment]
i think its related to php 5.4 but can not replicate. 

pm me your login info in the forum please. i want to test this myself.

**Comment by ritesh4716** [comment]
yes, I have adoptd 2 config.php

**Comment by ritesh4716** [comment]
sorry, but I can't send you my login info you can help me hear

**Comment by danielkerr** [comment]
ok going to test in a bit.

**Comment by danielkerr** [comment]
had to buy some godaddy hosting for testing.

**Comment by howdu** [comment]
Try edit: /system/startup.php
Add: ini_set('display_errors', true);

This should show you a bit more info about the error.

**Comment by ritesh4716** [comment]
I have contacted to my hosting provider(go daddy) & it will solve the error. Thanks for the help.

**Comment by danielkerr** [comment]
How did u manage to install. I just checked and go daddy does not support
zip

**Comment by danielkerr** [comment]
ok testing this today

**Comment by danielkerr** [comment]
this is 100% your fault for not moving your site from localhost to godaddy.

i have just tested and it works fine!

this area is not for personal issue support. its of problems with opencart the script to get rid of bugs for everyone.
