### ISSUE TITLE
The quote is passed in \admin\view\template\extension\total\sub_total.twig (OC 3.0.1.2)

### ISSUE THREAD

**Issue by PeterStudioWeb** [opencart/opencart#5734]
In file \admin\view\template\extension\total\sub_total.twig quote is passed on line 27 form action="{{ action }}" method="post" enctype="multipart/form-data" id="form-total class="form-horizontal"
after id="form-total
Version 3.0.1.2

**Comment by danielkerr** [comment]
this has been fixed int he master
