### ISSUE TITLE
Better Invoice Management - Update Invoices

### ISSUE THREAD

**Issue by allanespinoza** [opencart/opencart#5739]
Hi,

I think its necessary an Updated Invoices Template, for example the Invoices needs to say "Paid or Unpaid", and manage the Transaction ID if some one makes a successful payment with the transaction ID of that payment "Automatic Payments via PayPal, Creditcard, etc."

This can help to all the admins and customers if they need search a paid product with their transaction ID in the invoices and in the panel.

Additional the option to change the payment method for example "Credit Card to Bank Transfer or Bank Transfer to Credit Card" and activate the option for that payment module (Multiple Options if There are Multiple Payment Modules configured, like PayPal, Paypoint, Nochex, etc).

So the customer can buy some products and make the payment later from the invoice sections.

**Comment by osworx** [comment]
Sorry, but an Invoice is a official and legal binding document.
Once created it is not allowed to change anything on it!

If you want to create an Invoice where it says (e.g.) 'Unpaid' (because of a payment term later - 'Pay within 14 days'), there is nothing to change.
So what for an update??
