### ISSUE TITLE
UPS/FEDEX not working Requires testing 

### ISSUE THREAD

**Issue by nawid** [opencart/opencart#5742]
I have made all localization changes, applied all access keys and account info. No data are returned(such as shipping quotes costs and so).

Please test and fix the issue.

Note: same account info was used on opencart 2.0.0.0 and everything works properly.

**Comment by danielkerr** [comment]
ur wasting my time!

so i have to tell u which information might be useful!

its not hard to work out!!!!

any one else want to give this guy a clue! im to busy to be throwing questions back and forth!

**Comment by nawid** [comment]
I am not trying to waste your time. I am trying to point out that there is a problem in the new version (3.0.1.2). Even if I fix the issue for my self it may exist for others. Therefore, a fix in the package is needed.

**Comment by danielkerr** [comment]
Well what is the location u are shipping from to where the package is being shipped to. Weight? Etc..

**Comment by danielkerr** [comment]
Guessing games

**Comment by nawid** [comment]
I going to make a video and exactly point out the issue. Will send you the
video link.
