### ISSUE TITLE
The operation is insecure

### ISSUE THREAD

**Issue by landsman** [opencart/opencart#5744]
Hi,
my Sentry JS error handler catch this error:

![snimek obrazovky 2017-07-14 v 14 55 45](https://user-images.githubusercontent.com/3184228/28213027-922ccaa8-68a4-11e7-8d68-58c7ee3c0247.png)

**Comment by danielkerr** [comment]
false positive. i dont know why you would use something like sentry js but not have a clue about the results

**Comment by is3kk** [comment]
Hello,
I have same problem with it, can you check it please?
Here was probably same issue (are closed too) before 3 years: https://github.com/opencart/opencart/issues/1979.

![local_storage](https://user-images.githubusercontent.com/22054960/28513770-b3108e34-7057-11e7-8279-8235e4e58fa4.png)
