### ISSUE TITLE
cli-install doesn't validate http address 

### ISSUE THREAD

**Issue by qq7** [opencart/opencart#5745]
when performing cli install and typing, say, http://192.168.1.10 into --http_address, it breaks the app.

examples:
`src="http://192.168.1.10image/cache/catalog/demo/macbook_1-200x200.jpg"` 
` href="http://www.example.comadmin/index.php?route=common/dashboard"`

if option's value is http://192.168.1.10/ (with /), everything works as it's supposed to

OS: Debian 8 Jessie
OpenCart version: 3.0.1.3

**Comment by Felix-Ho** [comment]
@qq7 I test the latest cli install script from opencart is working fine. (also I test the http_server without enter / still work)
Please try it now.
