### ISSUE TITLE
Forgot Password Fail

### ISSUE THREAD

**Issue by reflexweb** [opencart/opencart#5746]
Version 3.0.1.1
PHP 5.4.X

When asking for password reminder (test customer) i get the following error.
*********************************************
Fatal error: Uncaught exception 'Exception' with message 'Error: EHLO not accepted from server!' in /var/sites/p/foobar/public_html/system/library/mail/smtp.php:120 Stack trace: #0 /var/sites/p/foobar/public_html/system/library/mail.php(81): Mail\Smtp->send() #1 /var/sites/p/foobar/public_html/catalog/controller/mail/forgotten.php(26): Mail->send() #2 [internal function]: ControllerMailForgotten->index('account/custome...', Array, NULL) #3 /var/sites/p/foobar/public_html/system/engine/action.php(51): call_user_func_array(Array, Array) #4 /var/sites/p/foobar/public_html/system/engine/event.php(37): Action->execute(Object(Registry), Array) #5 /var/sites/p/foobar/public_html/system/engine/loader.php(192): Event->trigger('model/account/c...', Array) #6 [internal function]: Loader->{closure}(Array, Array) #7 /var/sites/p/foobar/public_html/system/engine/proxy.php(25): call_user_func_array(Object(Closure), Array) #8 /var/sites/p/foobar/public_html/c in /var/sites/p/foobar/public_html/system/library/mail/smtp.php on line 120
***********************************************

this only happens when a valid user email is used, otherwise i get an email not found message

Many Thanks

**Comment by danielkerr** [comment]
works for me. use the forum to ask there.

**Comment by danielkerr** [comment]
A new password was requested for Your Store customer account.

To reset your password click on the link below:

http://localhost/opencart-master/upload/index.php?route=account/reset&code=bWFVKmIci3UFIryjXeUbNATFzYe3qgaHLrip1L7q

The IP used to make this request was:

::1

1.
