### ISSUE TITLE
Problem after upgrading to latest version of opencart

### ISSUE THREAD

**Issue by leeloo2014** [opencart/opencart#5752]
Hello all

After spending 3 days, sleepless, trying to find a solution, I decided to bother you.
I did the upgrade process exactly as per manual. It got me thousands of errors. So I decided to roll back to the previous version 3.0. And I can't get through the below errors. Front page and admin page, not accessible. I have tried anything you can imagine. Nothing is working. 
I have only now access from FTP and cPanel. 
I have restored old databases from php, in case something was wrong there. Nop, nada, zip, zero: I get the same messages.
Can anyone please help me step by step with that? It's my eshop and my physical store is 100% depended from it. Thank you

![screen shot 2017-07-17 at 11 54 23 am](https://user-images.githubusercontent.com/8432455/28261151-ba227906-6ae6-11e7-9287-20aa73ce2358.jpg)
![screen shot 2017-07-17 at 11 54 30 am](https://user-images.githubusercontent.com/8432455/28261150-ba1f816a-6ae6-11e7-8d7b-f60d3e4f56db.jpg)

**Comment by leeloo2014** [comment]
I can also give total access, if someone want to give a shot and try. Please any help will be very very greatful.

**Comment by danielkerr** [comment]
i think your version of php is to old.

**Comment by danielkerr** [comment]
there is no class front in opencart 3.0

**Comment by RaidoDev** [comment]
@leeloo2014 if it's still on the table, I can take a look, but I need your contacts.
or better - post in Forum.

**Comment by leeloo2014** [comment]
@RaidoDev Can you please yes help me? Where do you need me to send you all my details?

**Comment by leeloo2014** [comment]
@danielkerr @RaidoDev Hello again. The php is been updated to 5.6, but the errors are still there! in my admin page : https://www.petheartshop.gr/admin/  Fatal error: Cannot pass parameter 2 by reference in /home3/m1v2a9o8/public_html/system/modification/system/engine/loader.php on line 212

and to the front page: Fatal error: Call to undefined method Exception::getClass() in /home3/m1v2a9o8/public_html/system/engine/front.php on line 80

**Comment by kanenas** [comment]
@leeloo2014 which version of Opencart and what theme are you using?

**Comment by leeloo2014** [comment]
@kanenas hello kanenas. We use journal2 as theme and I have ('VERSION', '2.0.1.0'). All the problems occured when I updated to 3.0 :-( and although I reversed it to 2.0.1.0 i get these errors.

**Comment by kanenas** [comment]
When you say reversed you mean restore from a backup? Did you restore the database also?

I suggest you use this https://docs.journal-theme.com/#/settings/update if you haven't already:
### Journal Theme Update for Opencart 2.x
1. Download the latest version from Themeforest and locate the **Opencart_2.0.x folder**.
2. Upload the 4 folders (admin, catalog, image, system) to your OpenCart installation replacing all existing Journal files.
3. Go to Extensions > Modifications and click on the blue Refresh button (top right corner)

**Comment by leeloo2014** [comment]
@kanenas All good. I have uploaded the 4 folders. BUT I cannot access the admin area, to proceed to step 3!

And yes I did a restore to the database too.

**Comment by kanenas** [comment]
Use **FTP** and delete the files in `/system/modification/` (except `index.html`).
Does this make any difference?
If not, I suggest you restore again files and database in a subdomain (e.g **dev.yourdomain.com**) to see what happens.

**Comment by leeloo2014** [comment]
@kanenas Thank you. Lifesaver for the admin area. 

The main page, I get now the following errors:
Notice: Undefined index: token in /home3/m1v2a9o8/public_html/admin/controller/error/not_found.php on line 16Notice: Undefined index: token in /home3/m1v2a9o8/public_html/admin/controller/error/not_found.php on line 21
Fatal error: Call to a member function getUserName() on null in /home3/m1v2a9o8/public_html/admin/controller/common/header.php on line 41


I have done this step, to a new subdomain, but I had the same issues.! I've done this step, with old apache and the latest database.

Now that I'm writing you I have restored a database from 05/07, which 100% had no errors at all. And I got the errors in my main page as I copied you above.

**Comment by kanenas** [comment]
Use **FTP**:

1. Delete the files in `/vqmod/vqcache/` folder.
2. In `/vqmod/xml/` folder you will have to delete all **.xml** files **except** `vqmod_opencart.xml`. Then add back one by one the .xml files to see which one is causing the problem.

**Comment by leeloo2014** [comment]
@kanenas ..you know... the file vqmod_opencart.xml is not in that folder - actually I have no such file! and the vqcache was empty already. Plus in the admin area, I get an error I cannot see the modules!
![screen shot 2017-07-18 at 1 26 44 am](https://user-images.githubusercontent.com/8432455/28292561-31ee8c4c-6b58-11e7-89a6-dcd8894275e4.jpg)

I tried to install it again, but once I got the success message, again the file vqmod_opencart.xml wasn't there!!!

**Comment by leeloo2014** [comment]
@kanenas and now after the theme update, I get this message in the main page:  Fatal error: Call to a member function getUserName() on null in /home3/m1v2a9o8/public_html/admin/controller/common/header.php on line 41

pfffffffff....

**Comment by leeloo2014** [comment]
@kanenas and in the admin area, I get the message "the page you requested not found", when I click to see the modules.

**Comment by kanenas** [comment]
1. Disable all .xml files ( for example rename `addthis.xml` > `addthis.xml_` ).
2. Download the latest **vQmod** for **Opencart** (v2.6.3-opencart) from here https://github.com/vqmod/vqmod/releases and upload the files.
3. Run www.example.com/vqmod/install/
4. Check that `/vqmod/vqcache/` folder has files in it.

**Comment by leeloo2014** [comment]
@kanenas did it. Still the same issues....no modules page, no main page.

**Comment by kanenas** [comment]
Check `/config.php` and `/admin/config.php` files. I there a chance that you have mixed them up?

**Comment by leeloo2014** [comment]
mixed them up? meaning? no haven't moved, or replaced or anything.

**Comment by leeloo2014** [comment]
@kanenas maybe I can send you somehow, the credentials to log-in and see for yourself, anything?

**Comment by leeloo2014** [comment]
@kanenas listen. The upgrade from 2.0.1.0 to 3.0 created extra folders, due to the new structure. I deleted every dublicate folder and now the admin area is working like a charm. My only issue now is the main page. that f...ng error, still there:  Fatal error: Call to a member function getUserName() on null in /home3/m1v2a9o8/public_html/admin/controller/common/header.php on line 41

I assume that has something to do, with other duplicate files, but please in the meantime if you have any idea, please advise.

**Comment by kanenas** [comment]
@leeloo2014, if you had restored the files & database from a backup before the upgrade you shouldn't have extra folders or files!

**Comment by leeloo2014** [comment]
@kanenas I know but they were there. And by luck I found them, while I was waiting for any of your answers, browsed through ftp and voila!  Do you have any idea what can I do with that error? Fatal error: Call to a member function getUserName() on null in /home3/m1v2a9o8/public_html/admin/controller/common/header.php on line 41
petheartshop.gr is the main page

**Comment by kanenas** [comment]
Are you sure you uploaded the files into the correct folder and with the right structure? Also, make sure the config files are set up correctly with the paths to folders.

**Comment by leeloo2014** [comment]
@kanenas the config files are set, as per the instructions:  didn't replace them with the new ones. And yes the paths are all correct.
So... I must check each folder, each structure? :-(

**Comment by kanenas** [comment]
OK, this is my last suggestion and **you must use it at your own risk**!

1. I will assume that your database is **OK**.
2. Remove all files (everything) -except the `/config.php` & `/admin/config.php`- (I will also assume these are OK).
3. Upload a fresh install of **Opencart v.2.0.1.0** (same version as you had before the upgrade). DO NOT INSTALL just upload the files with the correct structure.
4. Install the latest **vQmod** for **Opencart** (v2.6.3-opencart)
5. Upload the latest version of **Journal Theme Update for Opencart 2.x**.

:pray:

**Comment by leeloo2014** [comment]
@kanenas thank you so much. I will try it. Nothing else left to do. I will advise once I finish. thank you once more for all your time and effort.

**Comment by leeloo2014** [comment]
@kanenas Can I ask you a question? maybe it's stupid, but I have to ask. You are telling me not to install. At this moment I'm uploading all the files of opencart. The folder install, should I left it outside? Not upload it with everything else I found in the zip?

**Comment by kanenas** [comment]
Yes, **do not** upload the `install` folder. What you need is a clean structure of folders & files.

**Comment by leeloo2014** [comment]
@kanenas same sh..it. Just finished everything. PLUS I get now and these errors in my admin area, after I login, at the top of all pages I see the below:


 Warning: fopen(/home3/m1v2a9o8/public_html/system/storage/cache/cache.store.1500412855): failed to open stream: No such file or directory in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 49Warning: flock() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 51Warning: fwrite() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 53Warning: fflush() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 55Warning: flock() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 57Warning: fclose() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 59Warning: fopen(/home3/m1v2a9o8/public_html/system/storage/cache/cache.order_status.2.1500412855): failed to open stream: No such file or directory in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 49Warning: flock() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 51Warning: fwrite() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 53Warning: fflush() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 55Warning: flock() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 57Warning: fclose() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/cache/file.php on line 59

And still front page, Fatal error: Call to a member function getUserName() on null in /home3/m1v2a9o8/public_html/admin/controller/common/header.php on line 41

**Comment by kanenas** [comment]
So, you have followed **all** the instructions from https://github.com/opencart/opencart/issues/5752#issuecomment-315918580 and you are getting the errors above?

Post here the files `/config.php` & `/admin/config.php` **without** the database credentials. I mean **DO NOT** post these:
```
// DB
define('DB_DRIVER', '');
define('DB_HOSTNAME', '');
define('DB_USERNAME', '');
define('DB_PASSWORD', '');
define('DB_DATABASE', '');
define('DB_PREFIX', '');
```

**Comment by leeloo2014** [comment]
@kanenas 
**config.php**
<?php
// HTTP
define('HTTP_SERVER', 'http://www.petheartshop.gr/admin/');
define('HTTP_CATALOG', 'http://www.petheartshop.gr/');

// HTTPS
define('HTTPS_SERVER', 'https://www.petheartshop.gr/admin/');
define('HTTPS_CATALOG', 'https://www.petheartshop.gr/');
define('HTTPS_IMAGE', 'https://www.petheartshop.gr/image/');

// DIR
define('DIR_APPLICATION', '/home3/m1v2a9o8/public_html/admin/');
define('DIR_SYSTEM', '/home3/m1v2a9o8/public_html/system/');
define('DIR_LANGUAGE', '/home3/m1v2a9o8/public_html/admin/language/');
define('DIR_TEMPLATE', '/home3/m1v2a9o8/public_html/admin/view/template/');
define('DIR_CONFIG', '/home3/m1v2a9o8/public_html/system/config/');
define('DIR_IMAGE', '/home3/m1v2a9o8/public_html/image/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_MODIFICATION', '/home3/m1v2a9o8/public_html/system/modification/');
define('DIR_LOGS', '/home3/m1v2a9o8/public_html/system/logs/'); 
define('DIR_CACHE', DIR_SYSTEM . 'storage/cache/');


define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_STORAGE', DIR_SYSTEM . 'storage/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');


define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_CATALOG', '/home3/m1v2a9o8/public_html/catalog/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'xxxxxxxxxxxxxx');
define('DB_PASSWORD', 'xxxxxxxxxxxx');
define('DB_DATABASE', 'xxxxxxxxxxxxxx');
define('DB_PORT', 'xxxxx');
define('DB_PREFIX', 'xxx_');


define('OPENCART_SERVER', 'http://www.opencart.com/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');


define('DIR_UPLOAD', DIR_STORAGE . 'upload/');

**Comment by leeloo2014** [comment]
@kanenas 
admin config


// HTTP
define('HTTP_SERVER', 'http://www.petheartshop.gr/admin/');
define('HTTP_CATALOG', 'http://www.petheartshop.gr/');

// HTTPS
define('HTTPS_SERVER', 'https://www.petheartshop.gr/admin/');
define('HTTPS_CATALOG', 'https://www.petheartshop.gr/');
define('HTTPS_IMAGE', 'https://www.petheartshop.gr/image/');

// DIR
define('DIR_APPLICATION', '/home3/m1v2a9o8/public_html/admin/');
define('DIR_SYSTEM', '/home3/m1v2a9o8/public_html/system/');
define('DIR_LANGUAGE', '/home3/m1v2a9o8/public_html/admin/language/');
define('DIR_TEMPLATE', '/home3/m1v2a9o8/public_html/admin/view/template/');
define('DIR_CONFIG', '/home3/m1v2a9o8/public_html/system/config/');
define('DIR_IMAGE', '/home3/m1v2a9o8/public_html/image/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_MODIFICATION', '/home3/m1v2a9o8/public_html/system/modification/'); 
define('DIR_LOGS', '/home3/m1v2a9o8/public_html/system/logs/');
define('DIR_CACHE', DIR_SYSTEM . 'storage/cache/');


define('DIR_UPLOAD', DIR_STORAGE . 'upload/');

define('DIR_STORAGE', DIR_SYSTEM . 'storage/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');


define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DIR_CATALOG', '/home3/m1v2a9o8/public_html/catalog/');

// DB
define('DB_DRIVER', 'xxxx');
define('DB_HOSTNAME', 'xxxxxxxxxx');
define('DB_USERNAME', 'xxxxxxxxxxx');
define('DB_PASSWORD', 'xxxxxxxxxxxx');
define('DB_DATABASE', 'xxxxxxxxxx');
define('DB_PORT', 'xxxx');
define('DB_PREFIX', 'xxxx_');


define('OPENCART_SERVER', 'http://www.opencart.com/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');


define('DIR_UPLOAD', DIR_STORAGE . 'upload/');

**Comment by leeloo2014** [comment]
@kanenas to the above comments, I just removed the <?php etc at the beginning.

and yes I followed exactly your instructions, I literally wiped out every file from the server and I uploaded a clean structure of 2.0.1.0 and I get the errors I'm writing you. And in the admin area and at the main page. :-(

**Comment by kanenas** [comment]
Use these for `/config.php`:
```
// HTTP
define('HTTP_SERVER', 'https://www.petheartshop.gr/');

// HTTPS
define('HTTPS_SERVER', 'https://www.petheartshop.gr/');

// DIR
define('DIR_APPLICATION', '/home3/m1v2a9o8/public_html/catalog/');
define('DIR_SYSTEM', '/home3/m1v2a9o8/public_html/system/');
define('DIR_LANGUAGE', '/home3/m1v2a9o8/public_html/catalog/language/');
define('DIR_TEMPLATE', '/home3/m1v2a9o8/public_html/catalog/view/theme/');
define('DIR_CONFIG', '/home3/m1v2a9o8/public_html/system/config/');
define('DIR_IMAGE', '/home3/m1v2a9o8/public_html/image/');
define('DIR_CACHE', '/home3/m1v2a9o8/public_html/system/storage/cache/');
define('DIR_DOWNLOAD', '/home3/m1v2a9o8/public_html/system/storage/download/');
define('DIR_LOGS', '/home3/m1v2a9o8/public_html/system/storage/logs/');
define('DIR_MODIFICATION', '/home3/m1v2a9o8/public_html/system/storage/modification/');
define('DIR_UPLOAD', '/home3/m1v2a9o8/public_html/system/storage/upload/');

// DB
define('DB_DRIVER', 'xxxx');
define('DB_HOSTNAME', 'xxxxxxxxxx');
define('DB_USERNAME', 'xxxxxxxxxxx');
define('DB_PASSWORD', 'xxxxxxxxxxxx');
define('DB_DATABASE', 'xxxxxxxxxx');
define('DB_PORT', 'xxxx');
define('DB_PREFIX', 'xxxx_');
```

and these for `/admin/config.php`:
```
// HTTP
define('HTTP_SERVER', 'https://www.petheartshop.gr/admin/');
define('HTTP_CATALOG', 'https://www.petheartshop.gr/');

// HTTPS
define('HTTPS_SERVER', 'https://www.petheartshop.gr/admin/');
define('HTTPS_CATALOG', 'https://www.petheartshop.gr/');

// DIR
define('DIR_APPLICATION', '/home3/m1v2a9o8/public_html/admin/');
define('DIR_SYSTEM', '/home3/m1v2a9o8/public_html/system/');
define('DIR_LANGUAGE', '/home3/m1v2a9o8/public_html/admin/language/');
define('DIR_TEMPLATE', '/home3/m1v2a9o8/public_html/admin/view/template/');
define('DIR_CONFIG', '/home3/m1v2a9o8/public_html/system/config/');
define('DIR_IMAGE', '/home3/m1v2a9o8/public_html/image/');
define('DIR_CACHE', '/home3/m1v2a9o8/public_html/system/storage/cache/');
define('DIR_DOWNLOAD', '/home3/m1v2a9o8/public_html/system/storage/download/');
define('DIR_LOGS', '/home3/m1v2a9o8/public_html/system/storage/logs/');
define('DIR_MODIFICATION', '/home3/m1v2a9o8/public_html/system/storage/modification/');
define('DIR_UPLOAD', '/home3/m1v2a9o8/public_html/system/storage/upload/');
define('DIR_CATALOG', '/home3/m1v2a9o8/public_html/catalog/');

// DB
define('DB_DRIVER', 'xxxx');
define('DB_HOSTNAME', 'xxxxxxxxxx');
define('DB_USERNAME', 'xxxxxxxxxxx');
define('DB_PASSWORD', 'xxxxxxxxxxxx');
define('DB_DATABASE', 'xxxxxxxxxx');
define('DB_PORT', 'xxxx');
define('DB_PREFIX', 'xxxx_');

```
Also use FTP, go to folder `/system/cache/` delete all files except `index.html`. Go to folder `/vqmod/vqcache/` and delete all files.

Let's see how it goes now!

**Comment by leeloo2014** [comment]
@kanenas now I get these errors in main page
Warning: fopen(/home3/m1v2a9o8/public_html/system/storage/logs/error.log): failed to open stream: No such file or directory in /home3/m1v2a9o8/public_html/system/library/log.php on line 6
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home3/m1v2a9o8/public_html/system/library/log.php:6) in /home3/m1v2a9o8/public_html/system/library/session.php on line 12
Warning: fwrite() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/log.php on line 10
Warning: fopen(/home3/m1v2a9o8/public_html/system/storage/logs/openbay.log): failed to open stream: No such file or directory in /home3/m1v2a9o8/public_html/system/library/log.php on line 6
Warning: fwrite() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/log.php on line 10
Opencart OCMod config.php error detected.

Your config.php file creates a conflict with OCMod, probably caused by 1-click Opencart installers.

Solution: Edit config.php from your Opencart root installation and replace all lines of code found after:

//DIR

and before:

//DB

with the following:

// DIR
define('DIR_ROOT'           , '/home3/m1v2a9o8/public_html/');
define('DIR_APPLICATION'    , DIR_ROOT . 'catalog/');
define('DIR_SYSTEM'         , DIR_ROOT . 'system/');
define('DIR_LANGUAGE'       , DIR_ROOT . 'catalog/language/');
define('DIR_TEMPLATE'       , DIR_ROOT . 'catalog/view/theme/');
define('DIR_CONFIG'         , DIR_ROOT . 'system/config/');
define('DIR_IMAGE'          , DIR_ROOT . 'image/');
define('DIR_CACHE'          , DIR_ROOT . 'system/cache/');
define('DIR_DOWNLOAD'       , DIR_ROOT . 'system/download/');
define('DIR_UPLOAD'         , DIR_ROOT . 'system/upload/');
define('DIR_LOGS'           , DIR_ROOT . 'system/logs/');
define('DIR_MODIFICATION'   , DIR_ROOT . 'system/modification/');
                

Warning: fclose() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/log.php on line 14
Fatal error: Call to a member function write() on null in /home3/m1v2a9o8/public_html/index.php on line 106

and admin 
Warning: fopen(/home3/m1v2a9o8/public_html/system/storage/logs/error.log): failed to open stream: No such file or directory in /home3/m1v2a9o8/public_html/system/library/log.php on line 6
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home3/m1v2a9o8/public_html/system/library/log.php:6) in /home3/m1v2a9o8/public_html/system/library/session.php on line 12
Warning: fwrite() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/log.php on line 10
Warning: fopen(/home3/m1v2a9o8/public_html/system/storage/logs/openbay.log): failed to open stream: No such file or directory in /home3/m1v2a9o8/public_html/system/library/log.php on line 6
Warning: fwrite() expects parameter 1 to be resource, boolean given in /home3/m1v2a9o8/public_html/system/library/log.php on line 10

**Comment by leeloo2014** [comment]
@kanenas hello again. Well I had no other choice, after 4 days sleepless and in front of the mac, to: create a new complete shop. Created a new folder in the domain, installed opencart 3.0, installed vqmod the latest release. 
And I have one question only: During the installation, I connected the new one with the old database. Although no errors appear, in the admin area and of course and the main page, seems like it's connected to a blank database! not even one customer, not even one product, although I see every detail to myphpadmin DB. Any clue, idea?

**Comment by kanenas** [comment]
@leeloo2014, if you want, use the email in my profile https://github.com/kanenas to contact me.

**Comment by mhcwebdesign** [comment]
Could you please continue this on the OpenCart forum and leave this github section for bug reports only please?

BTW.: I have yet to see a functioning upgrade system for OpenCart, it usually is bound to fail. Especially with the Journal 2 theme!
