### ISSUE TITLE
Missing language string

### ISSUE THREAD

**Issue by evpadallas** [opencart/opencart#5759]
In admin\language\en-gb\mail\voucher.php missing language constant using in admin\controller\sale\voucher.php
$_['text_sent']         = 'Success: Gift Voucher e-mail has been sent!';

**Comment by ADDCreative** [comment]
It's in admin/language/en-gb/sale/voucher.php where is should be. What is missing is the ```$this->load->language('sale/voucher');```

**Comment by evpadallas** [comment]
Maybe you're right
