### ISSUE TITLE
Call function currency->format with wrong arguments order at product/product.php [line ~320]

### ISSUE THREAD

**Issue by atvorch** [opencart/opencart#5765]
**Signature of function is next [system/library/cart/currency.php]:**
public function format($number, $currency, $value = '', $format = true) 

**Wrong call at product/product.php [line ~320] :**
$data['price'] = $this->currency->format($this->tax->calculate($product_info['price'], $product_info['tax_class_id'], $this->config->get('config_tax')), $this->session->data['currency']);

At product/product.php everywhere you pass **$this->tax->calculate($product_info['price'], $product_info['tax_class_id'], $this->config->get('config_tax'))** as first argument, it's wrong cause function takes the first argument as number not as price value.

As i understand number it's a count of items selected, and you pass calculated price as number, and you don't pass number of items at all. and if someone will try to pass format with false value at the end it will not work, cause it'l be third parameter as value!

**The call of function should be modified like this:**
$data['price'] = $this->currency->format("blank or number", $this->session->data['currency'],
$this->tax->calculate($product_info['price'], $product_info['tax_class_id'], $this->config->get('config_tax')), false - "optional");

If i'm wrong somewhere please tell me!

**Comment by ADDCreative** [comment]
Sorry, you are wrong. If you look at the code for the format function you will see. $number is the value you want to convert into the currency, for example the price of a product. $value is the currency exchange rate.

**Comment by atvorch** [comment]
Thanks!
