### ISSUE TITLE
Editing template .twig files in outside editor doesn't work

### ISSUE THREAD

**Issue by MarcPinnell** [opencart/opencart#5766]
If I edit a file like footer.twig (OC 3.02) in my preferred editor and refresh the page, nothing changes. Tried deleting the cache files in vqmod. Tried turning off caching via the admin>>dashboard>>gear>>cache panel. Cleared browser cache. Nothing. 
If I open the footer.twig file via the admin>>template editor, I can see the changes I made outside of OC. If I just hit save there and reload the front end page, the change appears.
What gives?

**Comment by leandroruel** [comment]
i changed my template .twig and then cleared the cache clicking at gear at admin panel and then it worked to me, check if maybe the permission to cache is writable, if not then i think he will not clear the cache...

**Comment by danielkerr** [comment]
i will add a clear cache button on the template page.

**Comment by leandroruel** [comment]
Marc, you can use a taskrunner to clear the cache too

**Comment by MarcPinnell** [comment]
Under the gear icon I have cache turned off. Why would it still be caching templates then?

**Comment by MarcPinnell** [comment]
Per instructions, I moved root\system\storage\cache to the directory above root. I double checked and caching is turned off. However, files are still being cached. Tested by simply deleting all the files in the cache directory and reloading the page. Two files popped up (cache.catalog.language.1500476673 & cache.store.1500476690). 
Oddly enough CSS files are not effected by this. I can change the CSS and have it show immediately.
![screen shot 2017-07-19 at 7 07 07 am](https://user-images.githubusercontent.com/4871176/28371210-328926f4-6c51-11e7-99ca-ab05368afc93.png)

**Comment by MarcPinnell** [comment]
Also I just tried clicking the clear/refresh button under the gear icon and it did not remove any files from the cache directory.

**Comment by danielkerr** [comment]
is related to this:

https://github.com/opencart/opencart/issues/5716

i will come up with a solution but in the middle of writing an upgrade script

**Comment by danielkerr** [comment]
maybe a fix is here

https://github.com/opencart/opencart/issues/5790

**Comment by danielkerr** [comment]
i have closed this as its a reported issue already

**Comment by jabir303** [comment]
@MarcPinnell have you got solution for this ?

**Comment by danielkerr** [comment]
make sure u have eval enabled on your server. it only caches when eval not used. the refresh buttonsa do work but its creating new cache files every page load.

**Comment by Jaras79** [comment]
Delete rows from oc_theme table in database. Works for me.

**Comment by alexltvnv** [comment]
> Delete rows from oc_theme table in database. Works for me.

Thank you very much!!!!!!!!

**Comment by npandu** [comment]
> Delete rows from oc_theme table in database. Works for me.

Great, It works perfectly, Then, There is no need to store twig in DB always.
