### ISSUE TITLE
Error when installing new language 

### ISSUE THREAD

**Issue by DMX003** [opencart/opencart#5768]
On page:  http://storebih.net/ocart2/   I have added new language HRVATSKI now when I switch to HRVATSKI I have an error in the upper part .

/home2/storebih/public_html/ocart2/catalog/controller/extension/module/octabproductslider.php on line 19

In which file it should change and what if anyone had this problem.

thanks

**Comment by DMX003** [comment]
If anyone has a solution it would be good

**Comment by RaidoDev** [comment]
Please, post full error text.

**Comment by webcorvo** [comment]
send us  the file : /module/octabproductslider.tpl
and extension/module/octabproductslider.php/octabproductslider.php

**Comment by DMX003** [comment]
These are the files you looking for . If he finds what what is the problem can you tell me where you are and what has changed.

 

Thank you


Sent: Monday, July 24, 2017 at 6:06 PM

**Comment by DMX003** [comment]
Notice: Undefined index: hr-hr in /home2/storebih/public_html/ocart2/catalog/controller/extension/module/octabproductslider.php on line 19

 

At the top of the page in Croatian language.

 

http://storebih.net/ocart2/ 

 

 

thank you

 

 

Sent: Monday, July 24, 2017 at 5:44 PM

**Comment by webcorvo** [comment]
send me send us the file : /module/octabproductslider.tpl
and extension/module/octabproductslider.php/octabproductslider.php
webcorvo@gmail.com
