### ISSUE TITLE
Error: A theme has not been assigned to this store! V. OpenCart 3.0.2.0

### ISSUE THREAD

**Issue by vega360** [opencart/opencart#5769]
This is what has came up on my main link to my store since I upgraded. I tried downgrading to an older 3 version and it just got worse.

Error: A theme has not been assigned to this store!

**Comment by danielkerr** [comment]
Added it in case config setting when some on installs it

**Comment by danielkerr** [comment]
Goto ur admin n and re-save the settings and theme

**Comment by vega360** [comment]
I went in and re saved the settings, I just opned up the settings tab in admin and clicked the save option.

I have no idea where you go to save the theme.

Issue is still not resolved

**Comment by danielkerr** [comment]
re save the default theme and the rsave ur settings. it works for everyone else.

this is not ur personal faq. use the forums

**Comment by vega360** [comment]
You are very rude, 

1. if they actually answered on the forums I wouldn't have to come here.
2. When you help someone, you need to actually take the time to make sure the issue is fully resolved before closing it. 

Even after taking a week just to get everything back, I still found numerous bugs with postage calculation and payment processing with the upgrade, so I have decided to move my online shop of about 700 plus products to a new client. Your product is not obviously ready for use, and I have to now have about 2 to 3 months of decreased/tepid sales, just to get my mail order back online.

**Comment by danielkerr** [comment]
i was rude because 

1. if u searched for this you would have found solution as it has been documented how to fix this issue.
2. because this is not the correct place to ask for help!

now u have told me ur paid by a client to upgrade there web site but u dont know enough about php to fix this issue. you made it worse by downgrading. you should always make a backup up of the site first and try doing  test upgrade rather then on a live site.

**Comment by zom-b-food** [comment]
FYI: The Theme dropdown only shows "Settings". There are no other options so I save with "Settings" theme. Weird that that's a theme. I'll just use the old version that works on my other machine.

**Comment by danielkerr** [comment]
Again this is solvable. Go to extensions themes

**Comment by strayasux** [comment]
this little fucker seems that he is begging me for a money with uneducated manner. look at his stupid sunglass on that head. what a joke!
