### ISSUE TITLE
SyntaxError: Unexpected Token

### ISSUE THREAD

**Issue by intervisionlord** [opencart/opencart#577]
![errrrr](https://f.cloud.github.com/assets/3979683/305899/4ddc1cd2-9667-11e2-9377-293cbee76107.jpg)
SyntaxError: Unexpected Token
SUBJ

Fresh install
Demo data
and first that we can see when try to chekout - ERROR!

**Comment by NeoCsatornaja** [comment]
I have a simular issu with registration link:
<img src="http://i60.tinypic.com/23uezk4.png">

**Comment by barthunia** [comment]
@intervisionlord  sry its not working im using 1.5.6 
dose anybody have a proper solution for it??
