### ISSUE TITLE
Shortcodes

### ISSUE THREAD

**Issue by landsman** [opencart/opencart#5771]
Hi,

I want place some my dynamic content only to the one information page (I have multisite etc). 
How can I do it without iframe? I think that great thing in this case are shortcodes.

Can you, please, look on this solution: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=15550 and think about something like this to official install?

**Comment by landsman** [comment]
Hi @danielkerr,
why are you closed this without reply?
You seems little bit arrogant, hm?

**Comment by danielkerr** [comment]
I don't work fo u!
