### ISSUE TITLE
Possible Code Redudancy 

### ISSUE THREAD

**Issue by HFR1994** [opencart/opencart#5773]
Hello,

I was just checking the catalog/products model (catalog side). I found a code redudancy, OpenCart is asking for the values: product_id, rating, discount and special in getProducts($data = array()) function which later execute the getProduct($product_id) function to ask the database again for discount and special. Rating, Discount and Special values on getProducts($data = array()) are not used.

**Comment by danielkerr** [comment]
that is only for sorting. the problem is the product quires have to take a lot into account such as price, discount, special price etc.. and has to come up with the lowest price if sorted that way. its not worth changing.
