### ISSUE TITLE
WorldPay - Keeps going into Disabled Status

### ISSUE THREAD

**Issue by mehtaman** [opencart/opencart#5778]
Hi,

I cant get the WorldPay extension to enable.
I enter all my API details, change the status to enable, OpenCart show the green successful bar.

When I refresh the page, the status is back to disabled.

I've tried uninstalling and reinstalling the plugin

OC Ver: 3.0.2.0

**Comment by danielkerr** [comment]
ok should have fixed it. the code is a little messed up. let me know if this fixes the issues. otherwise i need to contact worldpay to see if they want to update there extension.

**Comment by bobdonkey** [comment]
I tried the fix and it worked in one of my dev environments, but not in 2 others. So it is now enabled in one environment (and working) but I cannot enable in 2 others, including my live site.

**Comment by danielkerr** [comment]
can u pm your worldpay details so i can do some testing?

use the opencart forums. its something i need to test as well.

**Comment by bobdonkey** [comment]
Done

**Comment by bobdonkey** [comment]
OK I think I figured it out, if you use the new files on having never installed the extension before then it works. If you already installed it without the fix, then the Cron Job URL and the Secret are missing, and you then can't enable it. Removing and re-adding the extension does not fix it.

**Comment by bobdonkey** [comment]
Dan did you get anywhere with this? It is causing me production issues. I tried restoring the database from a working instance and it did not help. Thanks

**Comment by danielkerr** [comment]
yes, i fixed the config values were not setup properly. 

if u look at the master branch. maybe try to replace the files from the master branch with your web sites should work

**Comment by danielkerr** [comment]
sorry i forgot you ssnt me the login details

**Comment by danielkerr** [comment]
give me more time. trying to improve the backup restore system in the latest version.

**Comment by bobdonkey** [comment]
Thanks, yes I already replaced both worldpay.php and worldpay.twig and works for new installs but not for existing.
There is cron URL or secret in the config and cannot enable.

**Comment by straightlight** [comment]
The following steps are for Opencart v3.0.2.0 release. If your site is running in production, put your site under maintenance.

1 - Take a screenshot of your admin worldpay payment module configurations.
2 - Uninstall the worldpay payment module.
3 - Follow these steps below.

In admin/controller/extension/payment/worldpay.php file,

replace all instances of:

['worldpay_

with:

['payment_worldpay_

In admin/view/template/extension/payment/worldpay.twig and worldpay_order.twig file,

replace all instances BEGINNING with:

worldpay_

with:

payment_worldpay_

In admin/model/extension/payment/worldpay.php file,

find all BEGINNING instances of:

worldpay_

change each with:

payment_worldpay (EXCLUDING: the database table names and fields and: worldpay_recurring_orders.log)

4 - Reinstall the worldpay payment module.
5 - Reconfigure the worldpay payment module.

This should overall resolve the status issues along with other variables.

**Comment by straightlight** [comment]
I have updated the steps above due to more complex steps to complete. Replacing the files from step 3 should resolve the problem along the other steps that needs to be followed.

**Comment by bobdonkey** [comment]
Hi, I tried this and unfortunately did not work. In the worldpay config no secret key is generated, no URLs are populated, and none of the settings apart from the API keys are saved. Any other ideas? Thanks

**Comment by danielkerr** [comment]
what version are u using?

**Comment by bobdonkey** [comment]
3.0.2.0 with Journal
I tried on a dev site and live site and same issue on both.

**Comment by straightlight** [comment]
When saving the form, what does the error logs indicates?

**Comment by bobdonkey** [comment]
Absolutely nothing!

**Comment by bobdonkey** [comment]
PS I can give you access to the site if you like?

**Comment by straightlight** [comment]
Send me a PM on the Opencart forum, I will take a look.

**Comment by straightlight** [comment]
I sent you a reply on the forum. Please, check your messages.

**Comment by straightlight** [comment]
User is using Journal2. Unsupported since the Journal2 cache takes the lead instead of the Opencart cache.

**Comment by straightlight** [comment]
Received confirmation from the user. Instructions works as intended with fresh installation of Opencart or without additional 3rd party cache libraries.

**Comment by danielkerr** [comment]
this has already been fixed.

**Comment by paul-godfrey** [comment]
Hi, i've got the plugin to work well enough to provide webhooks and integrate with worldpay using the updated files as mentioned above, but the commit button remains greyed out and orders unable to be placed unless the user hits return. Any thoughts?

**Comment by straightlight** [comment]
From your browser, before hitting the commit button, press the F12 function key on your keyboard which will open the Developers Kit. On the console tab, when hitting the commit button, do you notice new lines appearing?

**Comment by paul-godfrey** [comment]
Is that something I can do on my Mac?

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/blob/master/upload/admin/view/template/extension/payment/worldpay.twig

go to

`admin/view/template/extension/payment/worldpay.twig`

search for 

id="input-status"

replace the select tag code with

```
       <select name="payment_worldpay_status" id="input-status" class="form-control">

                    {% if payment_worldpay_status %}

                      <option value="1" selected="selected">{{ text_enabled }}</option>
                      <option value="0">{{ text_disabled }}</option>

                    {% else %}

                      <option value="1">{{ text_enabled }}</option>
                      <option value="0" selected="selected">{{ text_disabled }}</option>

                    {% endif %}

                  </select>
```

**Comment by danielkerr** [comment]
also the issue tracker is not a support system! its for development of opencart. the issue reported was fixed a while ago. use the opencart forum, ask my staff via the contact us form, or pay a developer.

**Comment by paul-godfrey** [comment]
Ok thanks. Which contact us form are you suggesting I use?

Paul

**Comment by danielkerr** [comment]
stop being lazy you are wasting my valuable time. use your brain!

**Comment by danielkerr** [comment]
ridiculous u asking me this question.
