### ISSUE TITLE
Original issue not resolved

### ISSUE THREAD

**Issue by vega360** [opencart/opencart#5779]
https://github.com/opencart/opencart/issues/5769

This ticket was closed with a one sentence explanation of this issue. I was never explained how to actually fix the issue, nor was I allowed to confirm if it was fixed which it was not.

After upgrading to 3.20 it still says a theme has not been assigned to the store

Error: A theme has not been assigned to this store!

**Comment by howdu** [comment]
If upgrading you need to manually install a theme. It's under Extensions -> Themes

Install and save the theme with correct directory. 

![127 0 0 1-opencart_advanced-opencart_advanced_3000-upload-admin-index php-route marketplace-extension user_token uj4xli4zddheveicopjvt6fbhhcfbqah](https://user-images.githubusercontent.com/533658/28464945-0d2be07a-6e1f-11e7-8e0d-7d6294ff9185.png)

**Comment by vega360** [comment]
The new version of opencart I downloaded directly from the Opencart webstire does not have an extensions tab.

![untitledopencart](https://user-images.githubusercontent.com/30290268/28465233-9dd64066-6ded-11e7-86d1-9373e3a38372.png)

**Comment by howdu** [comment]
> 1. Post any upgrade script errors problems in the forums
> 2. After upgrade, clear any cookies in your browser to avoid getting token errors.
> 3. Load the admin page & press Ctrl+F5 twice to force the browser to update the css changes.
> 4. Goto Admin -> Users -> User Groups and Edit the Top Adminstrator group. Check All boxes.
> 5. Goto Admin and Edit the main System Settings. Update all fields and click save, even if nothing changed.
> 6. Load the store front & press Ctrl+F5 twice to force the browser to update the css changes.

More than likely haven't done 4.

**Comment by vega360** [comment]
okay I went and did all of that stuff, I got the extensions tab to come back I went in and enabled the theme, but my store still has not come back

**Comment by vega360** [comment]
Yeah you can close this, this is now resolved
