### ISSUE TITLE
[3.0.2.0] UPS doesn't work

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#5783]
The issue is the same as the USPS issue, which is the wrong code when retrieving a config variable. The fix is this:

```
IN:
/catalog/model/extension/shipping/ups.php

REPLACE:
$this->config->get('ups_

WITH:
$this->config->get('shipping_ups_
```

**Comment by syedfaisalraza** [comment]
Thank you so much for help. Its working fine.

**Comment by kashifmahmood86** [comment]
IN 3.0.3.1 the same issue still exist , i d'nt know why you close the issues if they come in the next release

**Comment by Nodws** [comment]
Well was looking for this for the longest time, OC never again :no_entry_sign:

**Comment by danielkerr** [comment]
I just did a mass search for $this->config->get('ups_ and there is non on the master branch.

**Comment by jolguin87** [comment]
@danielkerr The file /catalog/model/extension/shipping/ups.php in the 3.0.3.1 and 3.0.3.2 download bundles differ from the master branch GitHub repo.

**Comment by ClaudePlouffe** [comment]
Is there a reason why ups shipping extension are not included in master branch and does it mean it will not be part of the next release ?  
Thx

**Comment by D-whitten** [comment]
May of 2020 and this is still a problem with the stock OC UPS and FedEx shipping modules..

this is just sloppy coding at best...   did anyone even test this at all before releasing this?

This fix works..

same issue on line 104 admin/view/template/extension/shipping/fedex.twig 




> The issue is the same as the USPS issue, which is the wrong code when retrieving a config variable. The fix is this:
> 
> ```
> IN:
> /catalog/model/extension/shipping/ups.php
> 
> REPLACE:
> $this->config->get('ups_
> 
> WITH:
> $this->config->get('shipping_ups_
> ```
