### ISSUE TITLE
[3.0.2.0] OCmod is not working with PHP 5.6

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#5784]
OCmod is working with PHP 7.1 but not working with PHP 5.6
The import is working well but after a modification refresh nothing happens. 
It seems the changes in the .php files or OK but the changes in the .twig files are not ok.

**Comment by howdu** [comment]
Sounds like twig has cached the template and not reading the ocmod changes.

Try clearing the cache and also temporarly disabling template cache in: system/config/catalog.php
```php
$_['template_cache'] = false;
```

**Comment by pemaier** [comment]
It helped to clear the cache /storage/cache except index.html
Thank you. 

But there is a clear handling difference between PHP 5.6 and PHP 7.1
because at the PHP 7.1 this step is not required.
