### ISSUE TITLE
"storage" folder continues in system after automatic move

### ISSUE THREAD

**Issue by allanespinoza** [opencart/opencart#5785]
Hi,

I think is necessary remove the "Storage Folder" from "System Folder", after the automatic move it to a root directory.

At config.php the updated Storage folder is:

/var/www/vhosts/xxx.xxx/storage/

But the "old storage folder" continues in:

/var/www/vhosts/xxx.xxx/httpdocs/system/storage/

Thanks.

**Comment by danielkerr** [comment]
only config.php needs updating not the storage folder moving. as any upgades would add it back
