### ISSUE TITLE
Database - problem with set variable

### ISSUE THREAD

**Issue by smety** [opencart/opencart#5786]
Hi opencart team,

I have a problem with my custom SQL command in my custom module. If I was try use query in opencart It throw exception :-( but If I was try copy this sql command and execute in adminer / phpmyadmin it works good (screenshots). Can you look on it please? Problem is about set variable. Thank you.

![image](https://user-images.githubusercontent.com/22744053/28515811-486299c6-705f-11e7-8f91-8fc6ef52b49b.png)

![image](https://user-images.githubusercontent.com/22744053/28515815-4be6d6a2-705f-11e7-8666-f16a66435bc2.png)

**Comment by stalker780** [comment]
You must run one request per query.
You are tying to do multiple requests at once.

explode by ;

**Comment by danielkerr** [comment]
is that maxmind geoip? i have some code on the main site that integrates with this.
