### ISSUE TITLE
error on main front-end [Version 3.0.2.0]

### ISSUE THREAD

**Issue by Hyp3rionM4x** [opencart/opencart#5788]
I have the following errors showing on the OpenCart [Version 3.0.2.0]

Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "common/language.twig" (looked into: /home/thaionli/public_html/catalog/view/theme).' in /home/thaionli/public_html/system/library/template/Twig/Loader/Filesystem.php:215

Stack trace:

#0 /home/thaionli/public_html/system/library/template/Twig/Loader/Filesystem.php(139): Twig_Loader_Filesystem->findTemplate('common/language...')

#1 /home/thaionli/public_html/system/library/template/Twig/Environment.php(312): Twig_Loader_Filesystem->getCacheKey('common/language...')

#2 /home/thaionli/public_html/system/library/template/Twig/Environment.php(378): Twig_Environment->getTemplateClass('common/language...', NULL)

#3 /home/thaionli/opencart_storage/modification/system/library/template/twig.php(45): Twig_Environment->loadTemplate('common/language...')

#4 /home/thaionli/public_html/system/library/template.php(51): Template\Twig->render('common/language', '1')

#5 /home/thaionli/opencart_storage/modification/system/engine/loader.php(85): Template in /home/thaionli/public_html/system/library/template/Twig/Loader/Filesystem.php on line 215

Website URL: http://thai-chinese.dk/

**Comment by mhcwebdesign** [comment]
Please post technical support issues on the OpenCart forum, this is for bug reports only. I am unable to reproduce your issue, you are proving precious little details.

**Comment by danielkerr** [comment]
i think your missing a few files. try reuploading

**Comment by danielkerr** [comment]
also int he admin resave the default template

**Comment by Miindaugas** [comment]
Have same issue on my website after making 2 languages into single one. In my page i try load header controller  $this->load->controller('common/header'); and for some reason header controller trys load languages.php with trys to load language.twig from common/language.twig instead of theme/default/language.twig

**Comment by qayoombhat** [comment]
/public_html/system/library/template/Twig/Loader/Filesystem.php on line 215
