### ISSUE TITLE
Undefined index 'recurring_id' and headers already sent in v3.0.2

### ISSUE THREAD

**Issue by jeesus** [opencart/opencart#5789]
Hi

I've recently updated Opencart from 3.0.0 to 3.0.2 and since then I receive a blank page with error everytime I try to save product.

`Notice: Undefined index: recurring_id in /var/www/admin/model/catalog/product.php on line 198Warning: Cannot modify header information - headers already sent by (output started at /var/www/admin/controller/startup/error.php:34) in /var/www/system/library/response.php on line 36`

Is anyone else experiencing it or is it my problem only? I checked the files for unnecessary whitespaces, but there wasn't any.

**Comment by straightlight** [comment]
Solution posted on the forum: http://forum.opencart.com/viewtopic.php?f=201&p=690776&sid=7285bb1524fd00fe1ad97e03195c7488#p690776
