### ISSUE TITLE
OC 3.0.1.2 and 3.0.2.0: admin/view/*/before events unusable

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#5790]
This is related to this issue: https://github.com/opencart/opencart/issues/5716

It is not possible for templates from the admin backend to be modified via view/*/before events because of some bugs. I suggest the following fixes:

File **system/config/admin.php** should contain this fix:
```
....
// Action Events
$_['action_event'] = array(
	'controller/*/before' => array(
		'event/language/before'
	),
	'controller/*/after' => array(
		'event/language/after'
	),
	'view/*/before' => array(
		999  => 'event/language',
		1000 => 'event/theme'
	),
//	'view/*/before' => array(
//		'event/language'
//	)
);
....
````

File **admin/controller/event/theme.php** should use this:
```
<?php
class ControllerEventTheme extends Controller {
	public function index(&$route, &$args, &$template) {

		// This is only here for compatibility with old templates
		if (substr($route, -4) == '.tpl') {
			$route = substr($route, 0, -4);
		}
		
		if (is_file(DIR_TEMPLATE . $route . '.twig')) {
			$this->config->set('template_engine', 'twig');
		} elseif (is_file(DIR_TEMPLATE . $route . '.tpl')) {
			$this->config->set('template_engine', 'template');
		}

		// If there is a template file we render
		if ($template) {
			$template_engine = $this->config->get('template_engine');

			if ($template_engine=='twig') {
				// include and register Twig auto-loader
				include_once(DIR_SYSTEM . 'library/template/Twig/Autoloader.php');

				Twig_Autoloader::register();

				// specify where to look for templates
				$loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);

				$config = array('autoescape' => false);

				if ($this->config->get('template_cache')) {
					$config['cache'] = DIR_CACHE;
				}

				// initialize Twig environment
				$twig = new \Twig_Environment($loader, $config);

				$output = $twig->createTemplate($template)->render($args);
				return $output;
			} else {
				// render from a 'tpl' buffer
				$file = tempnam( DIR_CACHE, 'tmp' );
				extract($this->data);
				ob_start();
				require($file);
				$output = ob_get_clean();
				unlink( $file );
				return $output;
			}
		}
	}
}
```

**Comment by danielkerr** [comment]
Why the f** do u think I put output there before. Then got people complaining about it

**Comment by mhcwebdesign** [comment]
Daniel, we had this discussion before. In the **system/engine/load.php** you got this:

```
		// Template contents. Not the output!
		$template = '';
		
		// Trigger the pre events
		$result = $this->registry->get('event')->trigger('view/' . $trigger . '/before', array(&$route, &$data, &$template));
```

Hence., in the **admin/controller/event/theme.php** should have 3 arguments:

```
<?php
class ControllerEventTheme extends Controller {
	public function index(&$route, &$args, &$template) {
		.....
	}
```

The same as you did for frontend's view/*before events.

And the **system/config/admin.php** needs fixing because we want the **admin/controller/event/language.php** for view/*/before with priority 999, e.g. like this:

```
	'view/*/before' => array(
		999  => 'event/language',
		1000 => 'event/theme'
	)
``` 

Finally, the **admin/controller/event/language.php** , in method index, should have the missing template argument added, too.

**Comment by danielkerr** [comment]
yews but what exactly are u trying to achieve here? 

because as far as i can work out everything that needs to can be done.

should i guess what u are doing?

if ur trying to modify a theme that can be done after the template has been generated then cached.

**Comment by mhcwebdesign** [comment]
Daniel, at the moment it doesn't appear to be possible to modify admin backend template files via event handlers. We solved this problem for the frontend by adding a 3rd argument, namely the **&$template**, for the view/*/before event handlers.  The same should be done for the admin backend event handlers.

For example, if I wanted to modify the **admin/view/template/common/header.twig** I don't see a way for doing so (unless I go back to using VQmod or OCmod and don't use event handlers at all).

**Comment by mhcwebdesign** [comment]
Also, 2 other minor bugs to be fixed:

The lines in admin/controller/event/theme.php
```
		// This is only here for compatibility with old templates
		if (substr($route, -3) == 'tpl') {
			$view = substr($route, 0, -3);
		}
```
should look like this:
```
		// This is only here for compatibility with old templates
		if (substr($route, -4) == '.tpl') {
			$route = substr($route, 0, -4);
		}
```

And the lines in system/config/admin.php
```
// Action Events
$_['action_event'] = array(
	'controller/*/before' => array(
		'event/language/before'
	),
	'controller/*/after' => array(
		'event/language/after'
	),
	'view/*/before' => array(
		999  => 'event/language',
		1000 => 'event/theme'
	),
	'view/*/before' => array(
		'event/language'
	)
);
```
should look like this:
```
// Action Events
$_['action_event'] = array(
	'controller/*/before' => array(
		'event/language/before'
	),
	'controller/*/after' => array(
		'event/language/after'
	),
	'view/*/before' => array(
		999  => 'event/language',
		1000 => 'event/theme'
	),
);
```
Otherwise the event/language won't keep the priority of 999.

**Comment by danielkerr** [comment]
you need to use ocmod to modify the templates.

**Comment by mhcwebdesign** [comment]
Daniel, the **admin/controller/event/theme.php** and **system/config/admin.php** should be fixed, as shown above.

As regards modifying templates: If you insist on using an XML-dirven modification system like OCmod for modifying templates, then why have view/*/before event handlers at all? The whole idea about using event handlers was to move away from XML-driven modification systems like OCmod or VQmod, the latter are the main reasons for so many poor quality 3rd party extensions and clashes between them.

**Comment by danielkerr** [comment]
so whats the plan load the template file then use regular expression to modify parts of the template?

**Comment by mhcwebdesign** [comment]
I think part of the confusion comes from the fact that a 3rd argument named $**template** was added to the 

_public function index(&$route, &$args, &$template)_

in the **catalog/controller/event/theme.php** but not in the **admin/controller/event/theme.php**. This is fine when we only want the theme editor allow to change a frontend template and store it the 'oc_theme' DB table for later usage. 

However, since we already allow **view/*/before** event handlers we might as well use them for modifying both frontend and backend templates, by using handlers with a priority less than 1000 which make use of the $template argument.

**Comment by danielkerr** [comment]
events are not really good for modifying templates. just the template data. its not php your messing. you have to parse a html template file. it will be expensive to do this with multiple events.

**Comment by mhcwebdesign** [comment]
Your suggested alternative of using OCmod (or possibly VQmod) for modifying templates is even worse. We need to move away from XML-based modification systems and really come up with a better way of doing it. Personally I have been using the Override Engine, as well as on occasion event handlers, 

As regards parsing HTML templates and it being expensive: In most cases no parsing is required, just simple search and replace.

**Comment by danielkerr** [comment]
fine iw will try to put a method in the middle that will get the template

**Comment by coldwellr** [comment]
I so wish I could simply edit twig files outside of OpenCart 3.0.2.0 and have the changes take effect immediately. Storing template changes in the database means GIT version control on those twig files is not possible. Editing them in the 'design' editor is not a useable option. Also, I have written deployment scripts that use rsync to deploy the entire site in seconds, but the twig changes don't take effect! It's so frustrating - please can we edit twig outside of OpenCart?

**Comment by LJK-opencartmods** [comment]
As part of your deployment script, just delete the contents of  `DIR_STORAGE/cache` after a successful rsync.

For your dev site, here are instructions for disabling the caching:

https://webocreation.com/blog/opencart-twig-cache-removing-developing-theme-module-developer-tips <https://webocreation.com/blog/opencart-twig-cache-removing-developing-theme-module-developer-tips>

I haven’t tried them myself, but they look like what you’re looking for.

**Comment by coldwellr** [comment]
Ah, that does indeed look like what I'm after! I can delete the contents of `DIR_STORAGE/cache` with my deployment script. I have found that disabling the cache from the admin 'gear' button doesn't work for me. However I'll try these suggestions for disabling when I'm in development - this could be the answer! Many thanks, will let you know.

**Comment by danielkerr** [comment]
it works for every one else!

u can also turn the caching off.

**Comment by danielkerr** [comment]
ok added what you want. required a bit of thinking about.
its not fully finished. i needd to do a bit more testing and research to confirm this is the best solution.
