### ISSUE TITLE
Opencart 3.0.0.0 Paypal Express issue

### ISSUE THREAD

**Issue by bond1126** [opencart/opencart#5791]
The login dialog box pops up and immediately disappears in Safari, Chrome, Firefox and Edge.
It is working in IE10 but entering the password requires hitting the keyboard multiple times. 

Everything works perfectly in Sandbox mode.

**Comment by howdu** [comment]
https://github.com/opencart/opencart/blob/master/upload/catalog/view/theme/default/template/extension/payment/pp_express.twig#L11

Change to: 
 environment: '{{ environment }}'

**Comment by howdu** [comment]
This was the error  in browser console:
Unexpected init message from domain https://www.paypal.com -- expected message from https://www.sandbox.paypal.com

**Comment by jamesallsup** [comment]
@howdu kindly did the PR for the fix

Ref: https://github.com/opencart/opencart/pull/5983

**Comment by cinder92** [comment]
The variable `environment` does not exist on pp_express.php controller

**Comment by cinder92** [comment]
@howdu  i just tried your pp_express solution from your link, and its not working

**Comment by howdu** [comment]
@cinder92 which opencart version? Check the html source contains environment variable.

**Comment by cinder92** [comment]
version 3

**Comment by cinder92** [comment]
another one is that i put MXN currency code, and paypal is taking always as USD

**Comment by cinder92** [comment]
i put it working but i have to deactivate the use of javascript, in other case is not working
