### ISSUE TITLE
Opencart 2.3 - Default language selection not working for front

### ISSUE THREAD

**Issue by pjd91** [opencart/opencart#5795]
Opencart 2.3 - Default language selected  spanish from admin but not working for front. i mean it always stay by default English  we need to select from drop down 

as i already did 
admin - default language as spanish  also sort order for spanish is 1 but still it will load  by default a english language

**Comment by jigneshdavara** [comment]
hi Opencart 2.3+   versions  use browser language detection algorithm so it will find default language from your browser  ,  please remove detection for set default lanaguage

**Comment by webcorvo** [comment]
You must put the position

**Comment by allanespinoza** [comment]
Hi.. i use opencart in spanish. If you have a full translated opencart, delete the english language from Opencart from your control panel! If you dont use it. But if you use it both go to the Config of the site and verify "Spanish" is selected for "Front Page and Admin".

**Comment by RaidoDev** [comment]
This is known problem, but @danielkerr does not accept this as an issue
#5301
#2909

**Comment by danielkerr** [comment]
@RaidoDev banned!

his issue is he does not know there is language auto detection! he probably has a language cookie saying en-gb.

your posting stuff from 2015 that has nothing to do with this guys issue!

U dont even look into the problem! instead trying to cause issues with me!

**Comment by danielkerr** [comment]
another point #5301 and #2909 are both feature requests!

the current system works and always has!  the system you want me to change to has issues. i can;t reember what they were but i dont want to waste my time researching something  again.
