### ISSUE TITLE
Sidebar - Menu

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#5796]
Please Daniel bring back the possibility to hide/show the left menu (admin).

With 3.0.2.0 you have removed this option - for experienced users no reason why to show always the text (Icons are fully enough).
Beside users may have a bit more space (e.g. at Products list etc.).
Thx.

**Comment by mhcwebdesign** [comment]
Agreed, we need the possibility ti hide or show the left menu, as was the case in previous OC versions.

**Comment by stalker780** [comment]
Actually it's fine now as it is. 
But if you really decide to restore this functionality, please don't make it jump on page load a it was in OC2.x. 
I broke a dozen mice buttons while clicking the wrong link during page load and window jumping 230px left-right.

**Comment by danielkerr** [comment]
I like it how it is. we should need to create 3 view ports. 2 is enough.
