### ISSUE TITLE
OCSESSID cookie expiration is invalid

### ISSUE THREAD

**Issue by gabosom** [opencart/opencart#5801]
For more info on how I found the problem:
https://forum.opencart.com/viewtopic.php?f=199&t=186163&p=680870#p680870

I had issues logging into the Admin panel and it was an issue with the OCSESSID cookie getting expired immediately. The problem is on this line of code: https://github.com/opencart/opencart/blob/master/upload/system/framework.php#L108

ini_get('session.cookie_lifetime') wasn't setting an appropriate expiration value. As a workaround, I used the same values you used for setting the other cookies (language, etc.). Not sure what the right fix should be, but thought I'd let you know.

**Comment by danielkerr** [comment]
you can set your cookie time in php.ini also this should be pre configured n your php installation not opencart.

**Comment by danielkerr** [comment]
maybe because u have hidden html loading in every page request. dont use free crappy hosting!


```<iframe src='http://ifastnet.com/pop.html' name='frame1' scrolling='no' frameborder='no' align='center' MARGINWIDTH='0' MARGINHEIGHT='0' height = '10px' width = '10px'>  </iframe>```

**Comment by ADDCreative** [comment]
The problem is that the third parameter (expire) in setcookie requires a timestamp (e.g. time() + 3600), but 'session.cookie_lifetime' is just the lifetime in seconds.

For the vast majority of servers 'session.cookie_lifetime' will be set to the default of 0, which will work correctly. However there will be a few valid configurations where it will be set to a non-zero value.

So on this line https://github.com/opencart/opencart/blob/3.0.2.0/upload/system/framework.php#L108, the third parameter passed to setcookie could made to be somthing like this:
```php
(ini_get('session.cookie_lifetime') ? (time() + ini_get('session.cookie_lifetime')) : 0)
```

**Comment by danielkerr** [comment]
@ADDCreative cheers. i have added ur changes. this guys iss though is cookies can not be set if any output has html injected in.

**Comment by JamesAntropy** [comment]
@danielkerr I've come across the same issue in catalog/controller/startup/session.php

`setcookie($this->config->get('session_name'), $this->session->getId(), ini_get('session.cookie_lifetime'), ini_get('session.cookie_path'), ini_get('session.cookie_domain'));`

should be:

`setcookie($this->config->get('session_name'), $this->session->getId(), (ini_get('session.cookie_lifetime') ? (time() + ini_get('session.cookie_lifetime')) : 0), ini_get('session.cookie_path'), ini_get('session.cookie_domain'));`

**Comment by JamesAntropy** [comment]
Sorry if I'm looking in the wrong place but while it has been fixed in system/framework.php it still looks wrong in the catalog startup session controller (on master).

https://github.com/opencart/opencart/blob/master/upload/catalog/controller/startup/session.php

**Comment by underr-ua** [comment]
@danielkerr I've come across the same issue with OC 3.0.2.0 on profreehost.com. 
1. Without changes described [here](https://github.com/opencart/opencart/issues/5801#issuecomment-337606176) by @ADDCreative i can't login to admin
2. Without changes described [here](https://github.com/opencart/opencart/issues/5801#issuecomment-385639587) by @JamesAntropy admin session expires after refresh frontend page

**Comment by kristos80** [comment]
I can, also, confirm that the problem still exists

**Comment by danielkerr** [comment]
i have found the issue. fixing it now. 

https://github.com/opencart/opencart/issues/7259
