### ISSUE TITLE
Secure Urls in footer and header

### ISSUE THREAD

**Issue by rajatjain4061** [opencart/opencart#5802]
I am having problem with many links in footer and header which have ssl enabled. Even if I am not running my application on ssl.

When I looked in "C:\xampp\htdocs\opencart\catalog\controller\common\footer.php" I found that some urls have ssl enabled like below

```
		$data['voucher'] = $this->url->link('account/voucher', '', true);
		$data['affiliate'] = $this->url->link('affiliate/login', '', true);
		$data['special'] = $this->url->link('product/special');
		$data['account'] = $this->url->link('account/account', '', true);
		$data['order'] = $this->url->link('account/order', '', true);
		$data['wishlist'] = $this->url->link('account/wishlist', '', true);
		$data['newsletter'] = $this->url->link('account/newsletter', '', true);
```

Why these url's are secure?

**Comment by danielkerr** [comment]
asp check ur config.php

**Comment by danielkerr** [comment]
Because there related to customer account areas

**Comment by rajatjain4061** [comment]
@danielkerr If I would have SSL installed on my site, then my whole website would run over ssl as like demo.opencart.com. why would I selectively enable the SSL on few links?

**Comment by danielkerr** [comment]
Do ur own research. U want full SSL that's easy aswell

**Comment by danielkerr** [comment]
I'm not here to answer question to noobies. Don't open issues unless u are
a developer who has some experience

**Comment by danielkerr** [comment]
use the forums! its not rocket science!
