### ISSUE TITLE
OC Version 3.0.2.1b Contact Form / Permission denied

### ISSUE THREAD

**Issue by waxedperfection** [opencart/opencart#5803]
Hello,
Brand new install out the box fresh and have the following error when using the contact form. 

Warning: mail(/var/log/php_maillog): failed to open stream: Permission denied in /home/evoke/public_html/system/library/mail/mail.php on line 77Warning: Cannot modify header information - headers already sent by (output started at /home/evoke/public_html/catalog/controller/startup/error.php:34) in /home/evoke/public_html/system/library/response.php on line 36

Did try searching the forum and google before posting here.

**Comment by waxedperfection** [comment]
also on STMP for the mail setting im not getting the "Your enquiry has been successfully sent to the store owner!" message

**Comment by zemguru** [comment]
Email messages works, you must check the problem with SMTP server, or post more debug. 

But for success message, @danielkerr please, add:
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/information/contact.php?ts=2#L185
```$data['text_message'] = $this->language->get('text_success');```

**Comment by waxedperfection** [comment]
Thank you sorry my post first post is when selected as mail, if on STMP works fine.

**Comment by danielkerr** [comment]
if thats the case ur host did not configrue the mail settings properly.

 mail(/var/log/php_maillog):

error does not make sense. sme one set it up wrong

**Comment by waxedperfection** [comment]
@danielkerr Thank you for your help.
