### ISSUE TITLE
Opencart 3.0.2.0  Contact us page Bug

### ISSUE THREAD

**Issue by SibylZ** [opencart/opencart#5806]
Fatal error: Uncaught exception 'Exception' with message 'Error: E-Mail subject required!' in /home/gocherrg/public_html/system/library/mail.php:131 Stack trace: #0 /home/gocherrg/public_html/catalog/controller/information/contact.php(25): Mail->send() #1 [internal function]: ControllerInformationContact->index() #2 /home/gocherrg/public_html/system/engine/action.php(79): call_user_func_array(Array, Array) #3 /home/gocherrg/public_html/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #4 [internal function]: ControllerStartupRouter->index() #5 /home/gocherrg/public_html/system/engine/action.php(79): call_user_func_array(Array, Array) #6 /home/gocherrg/public_html/system/engine/router.php(67): Action->execute(Object(Registry)) #7 /home/gocherrg/public_html/system/engine/router.php(56): Router->execute(Object(Action)) #8 /home/gocherrg/public_html/system/framework.php(168): Router->dispatch(Object(Action), Object(Action)) #9 /home/gocherrg/public_html/system/startup.php(104): require_once('/home/g in /home/gocherrg/public_html/system/library/mail.php on line 131

How to solve it?Waitting online!

**Comment by allanespinoza** [comment]
That is not a bug, because i have the same version and works. I think you need ask on forum.

**Comment by SibylZ** [comment]
If your version works, could you send me your documents?
public_html/system/library/mail.php
I can replace mine.

**Comment by SibylZ** [comment]
This is Chinese version bug not english version

**Comment by danielkerr** [comment]
contact my staff they can speak chinese.
