### ISSUE TITLE
twig - how to write good 

### ISSUE THREAD

**Issue by magicbit** [opencart/opencart#5807]
hi
where i can find info about how write twig code?
i think need realese some guid or info about code

i have some extension and i start to learn and change but
i have some isuss
with some convert php
<?php if($direction=='rtl'){ ?>
<link href="view/stylesheet/bootstrap2css" type="text/css" rel="stylesheet" />
<link type="text/css" href="view/stylesheet/stylesheet2" rel="stylesheet" media="screen" />
<?php } ?>

**Comment by prhost** [comment]
https://twig.symfony.com/doc/1.x/

**Comment by magicbit** [comment]
Thanks ....
