### ISSUE TITLE
SEO activation: Fatal errors in OC2.3

### ISSUE THREAD

**Issue by leeloo2014** [opencart/opencart#5810]
Hello all

After a total new clean install of OC 2.3 with journal2 theme installed, I'm facing the below issue:
When I activate SEO from admin panel, everything sc...s up! I get fatal errors.

Notice: Undefined index: token in /home3/m1v2a9o8/public_html/admin/controller/error/not_found.php on line 16Notice: Undefined index: token in /home3/m1v2a9o8/public_html/admin/controller/error/not_found.php on line 21
Fatal error: Call to a member function getUserName() on null in /home3/m1v2a9o8/public_html/admin/controller/common/header.php on line 41

NOTE: The database is brand new, the set up is clean, nothing weird been installed. From the 1st day of installing 2.3 (approx 10 days ago), once I activate SEO I get these errors.
Any help?

**Comment by danielkerr** [comment]
forum please. this area is for the future releases.

**Comment by danielkerr** [comment]
journal2 theme is the issue though

**Comment by leeloo2014** [comment]
@danielkerr nop. Just tested it to the default theme and I get the same errors. So it's not journal issue.
