### ISSUE TITLE
Opencart 3.0.2.0  page Bug

### ISSUE THREAD

**Issue by sanatolij** [opencart/opencart#5813]
Bug  in Payment  "Free checkout". 
  Admin panel-> Extensions-> Free Checkout ->Edit Free Checkout->Order Status  Do not work

See admin/model/setting/setting.php-> public function editSetting:
line :  if (substr($key, 0, strlen($code)) == $code) {... 
 do not work if  "$key"=free_checkout_order_status_id
"$code"=payment_free_checkout
"substr($key"=free_checkout_order_s
"substr($key"=payment_free_checkout
"substr($key"=payment_free_checkout
See:
\admin\view\template\extension\payment\free_checkout.twig
line 31:<select name="free_checkout_order_status_id"
Should be changed to: <select name="payment_free_checkout_order_status_id
Also change to:
admin\controller\extension\payment\free_checkout.php

**Comment by danielkerr** [comment]
its fixed in master branch

**Comment by bluebrad** [comment]
im having the same problem! 
do i just update the files?
