### ISSUE TITLE
Error: A theme has not been assigned to this store!

### ISSUE THREAD

**Issue by tranbinhcse** [opencart/opencart#5814]
Hello!
I created a Theme option in the extension/theme with the name newtheme
This option creates a theme_newtheme_directory in database setting table
But in the override function of ControllerEventTheme is again
if ($this->config->get('config_theme') == 'default') {
			$theme = $this->config->get('theme_default_directory');
		} else {
			$theme = $this->config->get('config_theme');
		}
In function, it names newtheme as the directory name of theme, not the name configured in theme_newtheme_directory.

I suggest modifying it to 
$theme = $this->config->get('theme_'.$this->config->get('config_theme').'_directory');

![override](https://user-images.githubusercontent.com/8472733/28743737-d6a1b4ae-747b-11e7-8873-39814c347b25.png)

**Comment by waxedperfection** [comment]
could these help?

https://github.com/opencart/opencart/issues/5769

https://github.com/opencart/opencart/issues/5779

**Comment by tranbinhcse** [comment]
Not. I do not think so,
This is my configuration.

System => Setting => Store
http://prntscr.com/g2kdyb
Databse =>http://prntscr.com/g2kfs8
=>config_theme = xolomo

Extension=>Theme
http://prntscr.com/g2kdgc
http://prntscr.com/g2kefm
=> theme_xolomo_directory = > gecko

Function override Theme.php
http://prntscr.com/g2khta

// If the default theme is selected we need to know which directory its pointing to			
		if ($this->config->get('config_theme') == 'default') { // FALSE config_theme in database is xolomo
			$theme = $this->config->get('theme_default_directory');
		} else {
			$theme = $this->config->get('config_theme'); // get directory is xolomo not gecko folder theme.
		}

The theme store does not have theme_xolomo_directory , but the config theme is the folder name.

**Comment by danielkerr** [comment]
so this is a feature request! as no issue
 and is only ur chocie

**Comment by tranbinhcse** [comment]
Yes, this is a feature, but i has create a module theme and issue is opencart only using default module theme setting.

**Comment by danielkerr** [comment]
create a theme module. copy the default theme module

**Comment by tranbinhcse** [comment]
Yes. I copy default theme module, but I rename module theme to my project name.

**Comment by danielkerr** [comment]
Prefix the theme name. myext_themename

**Comment by tranbinhcse** [comment]
MY theme module

**Comment by tranbinhcse** [comment]
[xolomo.php.zip](https://github.com/opencart/opencart/files/1208685/xolomo.php.zip)
My theme module.

**Comment by beinoriusju** [comment]
@tranbinhcse if you have a shoe store and need simple design customization you don't create a new theme extension, but simply create a directory inside (e.g. `catalog/view/theme/gecko`) and point to that directory by modifying `theme_default_directory` (you can modify this parameter from within `default` themes configuration).

It's an additional degree of freedom built into Opencart for `default` theme. Other themes if hey need this additional degree of freedom should implement it themselves. I hope that makes things clear.

This code can be safely removed:

```
if (isset($this->request->post['theme_xolomo_directory'])) {
	$data['theme_xolomo_directory'] = $this->request->post['theme_xolomo_directory'];
} elseif (isset($setting_info['theme_xolomo_directory'])) {
	$data['theme_xolomo_directory'] = $setting_info['theme_xolomo_directory'];
} else {
	$data['theme_xolomo_directory'] = 'xolomo';
}
```
