### ISSUE TITLE
Mail can't be received Opencart 3.0.2.0

### ISSUE THREAD

**Issue by SibylZ** [opencart/opencart#5815]
Contact us page

**Comment by zemguru** [comment]
Can you receive an email from any other page? Success order, New customer registration, Forgotten password page?

**Comment by SibylZ** [comment]
$mail->setSender(html_entity_decode($this->request->post['name'].'<'.$this->request->post['email'].'>', ENT_QUOTES, 'UTF-8'));

**Comment by SibylZ** [comment]
code should change setSender

**Comment by danielkerr** [comment]
works fine. i think u did not configure properly. try testing using smtp and gmail
