### ISSUE TITLE
Incorrect error variable and permissions check order on install step_2

### ISSUE THREAD

**Issue by zemguru** [opencart/opencart#5817]
When you run install on 3.0.2.1.b, without created `config.php` files, you receive an incorrect message:

![image](https://user-images.githubusercontent.com/30476178/28753026-6a3093d4-7535-11e7-814e-da67ef88b2a1.png)

Even though - both files `config.php` and `admin/config.php` does not exists!

I will create PR for this, please, review.

**Comment by danielkerr** [comment]
to late

**Comment by zemguru** [comment]
Glad you fixed it!
