### ISSUE TITLE
Don't save order 'Sub-Total'

### ISSUE THREAD

**Issue by PeterStudioWeb** [opencart/opencart#5820]
Don't save sort order 'Sub-Total' in Extensions -> Extensions -> Order Totals
Test on last version from git - master 3.0.2.1b on 2017-07-30

**Comment by PeterStudioWeb** [comment]
In file 'opencart.sql'
on line 3348 (0, 'total_sub_total', 'sub_total_sort_order', '1', 0),
replace on (0, 'total_sub_total', 'total_sub_total_sort_order', '1', 0),

**Comment by amanaloaie** [comment]
The same problem in OC 3.0.3.2. Is it so difficult to fix it in newer versions, when you know what's the problem?

**Comment by danielkerr** [comment]
there was an issue with the last release.

the fix is here:

https://github.com/opencart/opencart/commit/bde4e64882df2a5bf59709c724000e704aa7aeba
