### ISSUE TITLE
passing arguments and data from trigger to action in events

### ISSUE THREAD

**Issue by hamid80386** [opencart/opencart#5825]
HI, what way to passing data and arguments from trigger to action?, in another say i want to use Trigger's arguments and variables into action method.
my question is about opencart 2.3.0.2

**Comment by danielkerr** [comment]
please ask in the forums

**Comment by danielkerr** [comment]
or here

https://github.com/opencart/opencart/wiki/Events-System

its unfinshed but i plan to finish it after i finish the upgrade system

**Comment by hamid80386** [comment]
thanks @danielkerr 
I asked in forum before asked this here, but didn't get any answer, and since i know you read questions here, asked here...

We wait you complete Opencart's wiki for get more developing information about opencarts...
