### ISSUE TITLE
Opencart Events, trigger in catalog, but action in admin

### ISSUE THREAD

**Issue by hamid80386** [opencart/opencart#5826]
I'm trying to add an event in opencart 2.3.0.2, my event trigger is in catalog (Front End) and my action is in admin. But event does not work.
This is my code:

`$this->model_extension_event->addEvent('repository_Output', 'api/order/history/after', 
      'admin/controller/extension/repository/output/exitAfterSell');`
I have a question, is this naturally impossible in opencart, or I have mistake in my code?

this code doesn't work too:

`$this->model_extension_event->addEvent('repository_Output', 'api/order/history/after', 
      'admin/extension/repository/output/exitAfterSell');`

**Comment by mhcwebdesign** [comment]
You cannot trigger events from the frontend for the admin backend.

It has to be:
```
$this->model_extension_event->addEvent('repository_Output', 'catalog/api/order/history/after', 'catalog/controller/extension/repository/output/exitAfterSell');
```
