### ISSUE TITLE
OC 3.0.2.0 Extension Installer bug

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#5830]
The OpenCart extension installer has this following subtle issue:

Assuming I install 3 different module extensions via the admin backend at

_Extensions > Installer > Upload_

where each module extension creates the same folder (highlighted in bold):

1. admin/model/extension/**module**/my-module-1.php
2. admin/model/extension/**module**/my-module-2.php
3. admin/model/extension/**module**/my-module-3.php

If I then uninstall the first extension module via

_Extensions > Installer > Uninstall_

it will then remove the folder **module**

1. admin/model/extension/**module**

leaving the 2nd and 3rd extension with a missing folder and its file.

In general, the OpenCart extension installer should keep a count of newly introduced folders and only remove them in the uninstaller when all extensions using them have been uninstalled.

**Comment by danielkerr** [comment]
this should not happen since it only adds a this to a directory if it does not exists.

ok i will ad something to check if the directory is empty.
