### ISSUE TITLE
OC 3.0.2.0 All Information Page update error

### ISSUE THREAD

**Issue by itechsolution84** [opencart/opencart#5832]
When I am trying to update Information like Privacy / Terms and condition I get error : V3.0.2.0 fresh Installation

Notice: Undefined index: custom_imgtitle in storage/modification/admin/model/catalog/information.php on line 106Notice: Undefined index: custom_alt in /storage/modification/admin/model/catalog/information.php on line 106Warning: Cannot modify header information - headers already sent by (output started at /admin/controller/startup/error.php:34) in /storage/modification/system/library/response.php on line 36

**Comment by danielkerr** [comment]
This is from an extension u installed
