### ISSUE TITLE
Is there a chinese language package for opencart?

### ISSUE THREAD

**Issue by salamander-mh** [opencart/opencart#5835]
Opencart is a wonderful project, but it seems there is no chinese laguage package for it.

**Comment by gizmecano** [comment]
Depending of the version you use, you can consider these translation projects:
-  [OpenCart (Chinese Simplified translation)](https://crowdin.com/project/opencart/zh-CN)
-  [OpenCart Translation v.2 (Chinese Simplified translation)](https://crowdin.com/project/opencart-translation-v2/zh-CN)

**Comment by danielkerr** [comment]
there is  free one on crowdin
