### ISSUE TITLE
Unstable delete order link?

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#5837]
admin > sale/order_list.twig line 140:
`<li><a href="{{ order.order_id }}"><i class="fa fa-trash-o"></i> {{ button_delete }}</a></li>`

This do eg. to link:  yourstore.com/admin/2573

This is not work after upgrade 1.5.2 to 3.0.x, it redirect to admin login page

**Comment by danielkerr** [comment]
try the master

**Comment by danielkerr** [comment]
im sure i fixed this.

**Comment by ratwasher** [comment]
I was wonderng who will ask this question.
Unfortunately I'm having the same issue, any comments on this?

**Comment by pekka2** [comment]
@ratwasher can you download latest files from admin/view/template/sale and defaul/template/api from Github and upload to your store.
