### ISSUE TITLE
Call to undefined function openssl_random_pseudo_bytes() in C:\wamp\www\online_shop\system\library\session.php on line 62

### ISSUE THREAD

**Issue by satyamagni999** [opencart/opencart#5839]
Call to undefined function openssl_random_pseudo_bytes() in C:\wamp\www\online_shop\system\library\session.php on line 62

**Comment by satyamagni999** [comment]
![image](https://user-images.githubusercontent.com/25228602/28890145-c9dac1b4-77e3-11e7-969b-1347ff2a5d8b.png)

**Comment by howdu** [comment]
http://lmgtfy.com/?q=Call+to+undefined+function+openssl_random_pseudo_bytes

**Comment by danielkerr** [comment]
strange as it is checking if the function exists or not.

**Comment by danielkerr** [comment]
im assuming u did an upgrade as opensll is a requirement to install

$data['openssl'] = function_exists('openssl_encrypt');

**Comment by danielkerr** [comment]
ask ur host to enable this extension as it pretty ocmmon and installed in the core of php in later versions.
