### ISSUE TITLE
Version: 3.0.2.0 No Payment option available when Requires Shipping = No

### ISSUE THREAD

**Issue by LightsOnHudson** [opencart/opencart#5840]
when a product has Requires Shipping set to NO, there is no option for payment method when checking out. 
Yes I understand that ' free shipping ' could be an option, however if it is the ONLY thing in the list and it is a downloadable product, or just a Custom Inquiry type product where there is no shipping and potentially no COST for professional services you cannot check out and place an order.

**Comment by danielkerr** [comment]
only one payment method which is set to on by default with is cash on delivery that obviously will not work with product that do require shipping.

just choose one of the other 48 built in payment gateways!
