### ISSUE TITLE
Free Checkout Order Automatically Cancelled, Order is sent to Missing

### ISSUE THREAD

**Issue by Selezen** [opencart/opencart#5841]
Fresh install of OC 3.0.2.0. When any products at zero price are ordered/purchased, the order is completed in the UI and the user is told the order is successful.

However, when the account's order history is checked, the order is not visible. In addition, the admin tool does not show the order in the site's order history. The "Missing Orders" screen shows the orders and shows them as cancelled.

The Free Checkout extension by default shows the status as "Pending". If this is changed to anything, including leaving the option at "Pending" and clicking Save, when reloaded the status always shows as "Cancelled". In the database the status code for this item is always 1, no matter what has been selected - interestingly the "Cancelled" status is 5, so I have doubts that the status is being written to the database.

I've experimented with other methods of free checkout, and the "Cheque / Money order" option allows free checkout to occur.

**Comment by danielkerr** [comment]
I think this is fixed in the master

**Comment by danielkerr** [comment]
Will test ltr

**Comment by howdu** [comment]
Try with the latest master I had the same issue and it was due to the free checkout status missing payment prefix. Order was being added with order_status_id=0.

Apply these fixes and then re-save the payment. 
https://github.com/opencart/opencart/pull/5787

**Comment by Selezen** [comment]
I've installed the latest master and the problems stated above have indeed been resolved.

Thank you for your help :-)

**Comment by ProfessorLinebeck** [comment]
Didnt work for me for some reason. Is still still a bug at the newest version?

**Comment by anderson916** [comment]
same problem here with the latest master.

**Comment by ar27111994** [comment]
same here with 3.0.2.0

**Comment by loginetsolutions** [comment]
Same 3.0.2.0

**Comment by danielkerr** [comment]
Make sure u have not deleted the order status that is assigned to freeze
checkout

**Comment by cartbinder** [comment]
If you are not using latest master and are On 3.0.2.0 version. You can check this forum topic for the fix:
https://forum.opencart.com/viewtopic.php?f=201&t=192113
