### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by evpadallas** [opencart/opencart#5847]
I try update my shop, but in last step get this error.

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data OK Warning: Invalid argument supplied for foreach() in /www/orig/system/engine/loader.php on line 83Notice: Undefined property: Proxy::upgrade in /www/orig/install/controller/upgrade/upgrade.php on line 54

**Comment by danielkerr** [comment]
i think u might be missing a file or the model file is blnk. i can not replicate this. please try the forum
