### ISSUE TITLE
Image manager not functioning correctly 2.3.0.2

### ISSUE THREAD

**Issue by kadlevent** [opencart/opencart#5848]
I see there has been an issue raised before but in my case i do not have Cloudflare setup.

https://github.com/opencart/opencart/issues/5644

Does anyone have any ideas how i can solve this? At the moment, i can not select or upload any images using the image manager.

**Comment by kadlevent** [comment]
@danielkerr why was this closed?

**Comment by zemguru** [comment]
can you send some Chrome dev console logs ? Any errors in console, networking tab?
