### ISSUE TITLE
Brand Page list product but not display correct page number

### ISSUE THREAD

**Issue by itechsolution84** [opencart/opencart#5854]
Hi Team,

there is a bug on brand page where we list products but at bottom it shows as "Showing 0 to 0 of 0 (0 Pages)"
![manufacture page shows product as showing 0 to 0 of 0 0 pages](https://user-images.githubusercontent.com/30600622/28997750-f3590ef8-7a39-11e7-86a0-c6f9987f3c91.png)

**Comment by danielkerr** [comment]
can not replicate. 

u can check the oc demo to see it does work
