### ISSUE TITLE
Impossible to login into admin on fresh installation (current master)

### ISSUE THREAD

**Issue by zemguru** [opencart/opencart#5856]
Fresh installation of master branch.
Password _still_ is passed to cart->user->login method unhashed, but hash created during installation, does not validate. It's impossible to login into system, cause check is done here:

https://github.com/opencart/opencart/commit/4e093a73a1b743fb551ad63fa60a3dab3452460d#diff-5cf9361d599bbfd2e625497510bd16edR44

**Comment by danielkerr** [comment]
yes just fixed in master

**Comment by zemguru** [comment]
Great, thanks! again :)
