### ISSUE TITLE
MySQLi warnings and notices during installation (latest master), if incorrect values entered

### ISSUE THREAD

**Issue by zemguru** [opencart/opencart#5857]
if you specify incorrect mysql connect parameters, you will receive PHP notice and warnings during fresh installation together with validation errors:

~~~
Warning: mysqli::mysqli(): (HY000/2002): No such file or directory in /public_html/upload/system/library/db/mysqli.php on line 7
Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /public_html/upload/system/library/db/mysqli.php on line 10
Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /public_html/upload/system/library/db/mysqli.php on line 10
Notice: Undefined variable: mysql in /public_html/upload/install/controller/install/step_3.php on line 280
Notice: Trying to get property of non-object in /public_html/upload/install/controller/install/step_3.php on line 280
~~~

![image](https://user-images.githubusercontent.com/30476178/29003882-b1f6ab08-7ac7-11e7-91b0-eeed8119454d.png)

**Comment by zemguru** [comment]
Great, thanks!

**Comment by rhiumi1992** [comment]
how did you solve this?

**Comment by dcolley** [comment]
I solved this for myself by switching to mPDO and adding the port to the localhost - e.g. localhost:3306

**Comment by rajatmohan02** [comment]
Hi,
This error comes because you are using the wrong Database, Username or Password.
If you are the Database Administrator, you can go to your cPanel and check the Database, Username, and Password and mention correct information. 
One more thing to remember that the user should be connected to the same database and also have All Privileges.

**Comment by danielkerr** [comment]
Go to config default.php and turn error reporting off false
