### ISSUE TITLE
Token length incorrect

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#5860]
The forgotten password link and other areas that use token function don't work on php 7. `random_bytes` returns twice the length for some reason.

`var_dump(token(40))); // string(80)`

Maybe token needs a substr?

```php
function token($length = 32) {
	if (function_exists('random_bytes')) {
		$token = bin2hex(random_bytes($length));
	} else {
		$token = bin2hex(openssl_random_pseudo_bytes($length));
	}

	return substr($token, 0, $length);
}
```

**Comment by danielkerr** [comment]
it just been fixed here 

https://github.com/opencart/opencart/pull/5863
