### ISSUE TITLE
OpenCart 2.3.x & 3.x PayPal Payments Standard doesn't pass state code

### ISSUE THREAD

**Issue by morgant** [opencart/opencart#5861]
The PayPal Payments Standard payment extension does not pass the state code at all in the PayPal cart upload form for the confirm stage of the checkout process. If the user logs into a PayPal account, this has no ill effect as it'll use the state associated with the address used within PayPal, however, if the user instead selects "Pay with Debit or Credit Card" (so using PayPal's Guest Checkout), the address will be incomplete, silently causing the PayPal checkout process to fail without error (unless the user selects the state and re-enters their Zip Code).

I have confirmed this in OpenCart 2.3.0.2 as well as 3.0.2.0.

This can be fixed by including the region code as the state in `catalog/controller/extension/payment/pp_standard.php` and `catalog/view/theme/default/template/extension/payment/pp_standard.*` (I'll submit a PR for 3.0.2.0, not sure if there's any point in back porting).

**Comment by paulsvang** [comment]
are there instructions to fix this issue manually?

**Comment by ADDCreative** [comment]
Add the lines to the files highlighted at the link below.
https://github.com/opencart/opencart/pull/5862/files

However this will probably only work for US and Canada.
https://developer.paypal.com/docs/classic/api/state_codes/

Other countries PayPal gives an example of using the zone name and not the code.
https://www.paypal.com/uk/cgi-bin/webscr?cmd=_pdn_xclick_prepopulate_outside

**Comment by paulsvang** [comment]
Thanks



Paul



-------- Original message --------
