### ISSUE TITLE
Install step 3 mysqli connect issue

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#5866]
Step 3 validation is failing without error. When debugging I see that $this->error is return.

> array(1) { ["warning"]=> NULL }

Fixed by 
```php
if ($db->connect_errno) {
	$this->error['warning'] = $db->connect_error;
}
```
https://github.com/opencart/opencart/blob/master/upload/install/controller/install/step_3.php#L280

$mysql should be $db. Also check for connect_errno same as example: http://php.net/manual/en/mysqli.error.php

**Comment by howdu** [comment]
https://github.com/opencart/opencart/pull/5867

**Comment by allanespinoza** [comment]
Same error here!
