### ISSUE TITLE
[header.twig] <base href="{{ base }}" /> not including subfolders like /install

### ISSUE THREAD

**Issue by ChazyTheBest** [opencart/opencart#5868]
I was going to install opencart for the first time and the install page doesn't load external files like css or js... Looking at the source I see:

```html
<base href="http://www.domain.com/" />
```

This means that the base url for this page would be root / thus not including the current folder /install (same for /admin) where all the files are.

I'm not sure, could this be some server configuration problem? Because I don't see any issue about this... And this tells me that no one has had this problem before me?

I have checked the php configs in the php.ini file included and they are already in my master php.ini. I have moved the .htaccess configs to the apache virtualhost block for the virtualdomain.

```apache
<VirtualHost *:80>
    ServerName www.domain.com
    #Redirect permanent / https://www.domain.com/

    DocumentRoot "/srv/http/domain.com/www"
    <Directory "/srv/http/domain.com/www">
        <FilesMatch "(?i)((\.tpl|.twig|\.ini|\.log|(?<!robots)\.txt))">
            Require all denied
        </FilesMatch>

        <Files "index.php">
            SetHandler "proxy:unix:/run/php-fpm/www.elsabordemitierra.sock|fcgi://localhost/"
        </Files>

        <IfModule dir_module>
            DirectoryIndex index.php
        </IfModule>

        <IfModule mod_rewrite.c>
            # SEO URL Settings
            RewriteEngine On
            RewriteBase /
            RewriteRule ^sitemap.xml$ index.php?route=extension/feed/google_sitemap [L]
            RewriteRule ^googlebase.xml$ index.php?route=extension/feed/google_base [L]
            RewriteRule ^system/storage/(.*) index.php?route=error/not_found [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_URI} !.*\.(ico|gif|jpg|jpeg|png|js|css)
            RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]
        </IfModule>

        # Enable gzip compression
        <IfModule mod_deflate.c>
            AddOutputFilterByType DEFLATE text/html text/xml text/plain text/css text/javascript application/javascript application/json
        </IfModule>
    </Directory>

</VirtualHost>
```

I'm using the latest version for everything (arch linux).

The temporal solution I'm using is delete that tag or add /install at the end (and /admin for the header.twig inside the admin/view/template/common/ folder)

Any idea why is this happening? Thanks.

**Comment by danielkerr** [comment]
it works for evey one else. please ask in the forum
