### ISSUE TITLE
Very slow after adding product options

### ISSUE THREAD

**Issue by AyhanerMedya** [opencart/opencart#5871]
After adding Opencart product options.
You have to wait a long time to sort out the product. Between 1 and 5 minutes.

Opencart V. 2.1.0.1
Use VQMOD

**Comment by danielkerr** [comment]
do u have any site map generators installed?

remove it.

also post this in the forums.  not here this is for 3.+

**Comment by danielkerr** [comment]
Also I have not said how many product options u have

**Comment by AyhanerMedya** [comment]
There are 10 options in the variable parts and 50 options in some.
I think it's a site map builder.
Non-option products are opening fast.
But the alternative products are unfortunately too cumbersome.
I'm looking for a way to speed it up.

**Comment by AyhanerMedya** [comment]
I clicked on the product edit. It opens in about 1-2 minutes.
Option is turned on in a matter of seconds.
