### ISSUE TITLE
3.0.2.0 Admin menu bug

### ISSUE THREAD

**Issue by unclego** [opencart/opencart#5873]
Steps to reproduce.
Create a new user group with only permission to tool/log.

System menu first child ul got id collapse1,  but next level menu Maintenance child ul also got same id.

Screenshot attached:

![oc_menu_bug](https://user-images.githubusercontent.com/5900577/29250798-9c052de4-8051-11e7-95a3-d670297e253d.jpg)

moving increment statements immediate after for instead before endfor fix it

```
    {% for menu in menus %}
    {% set i = i + 1 %}
...
        {% for children_1 in menu.children %}
        {% set i = i + 1 %}
...
            {% for children_2 in children_1.children %}
            {% set i = i + 1 %}

```

Also reports menu should be checked and don't display if empty
```
if( $report ) {
    			$data['menus'][] = array(
    				'id'       => 'menu-report',
    				'icon'	   => 'fa-bar-chart-o', 
    				'name'	   => $this->language->get('text_reports'),
    				'href'     => '',
    				'children' => $report
    			);
}
```

**Comment by gRoberts84** [comment]
@danielkerr - Do you know when your commit (#861c275) will be released, as it wasn't included in 3.0.3.0?
