### ISSUE TITLE
OC 3.0.1.1 / 3.0.2.0 - Different star rating - minor bug

### ISSUE THREAD

**Issue by WhatNot911** [opencart/opencart#5874]
Wanted to check out **Extensions Marketplace in the Dashboard** and realized that when listed an extension can have a rating of **5 stars**, but when you click on it it shows **4 stars** on the right side of the page (Right above "Date Modified" field). 

It seems to be random - (ExcelPort seems to have 4 stars when listed and 3 stars on its page with both showing 57 reviews while some other don't seem to have this problem)

**Comment by OpenCartAddons** [comment]
Each page uses a different calculation to determine the rating.  The extension list uses a weighted rating, while the extension page takes the average and PHP floors it.

This is derived from the OpenCart API and not the marketplace in the dashboard.  Daniel will have to patch the API.

Regards,
Joel.

**Comment by AlexChanHK** [comment]
Thanks for reporting, I had find the issue and going to commit a update to fix this issue.
