### ISSUE TITLE
Rating stars didn't display on Featured products 3.0.2.1b

### ISSUE THREAD

**Issue by Manitoou** [opencart/opencart#5876]
catalog/view/theme/default/template/extension/module/featured.twig
Change this line:  {% for i in 5 %} 
to:  {% for i in 1..5 %}

**Comment by AlexChanHK** [comment]
Just commit a edition for fixing this mistake.
And **this issue can be closed.**

**Comment by Gotolr** [comment]
Problem is still there on all default product modules (latest, featured, bestsellers..) ocStore 3.0.2.0b1 and default template.
