### ISSUE TITLE
3.0.2.1b don't work backup

### ISSUE THREAD

**Issue by businessera** [opencart/opencart#5878]
System\Maintenance\Backup / Restore - don't work
HTTP ERROR 500
logs:
PHP Parse error:  syntax error, unexpected ')' in .../admin/controller/tool/backup.php on line 326, referer: .../admin/index.php?route=tool/log&user_token=f573a99da974ce3346783f454e9e4e8f

**Comment by allanespinoza** [comment]
Same problem here, only on 3.0.2.1b. On PHP 7.0 in my case.

**Comment by danielkerr** [comment]
yes its being changed to to include the upgrade system.
