### ISSUE TITLE
Add wiki documentation on updating themes/modifications/extensions to support OC 3.0.x

### ISSUE THREAD

**Issue by morgant** [opencart/opencart#5882]
All themes, modifications, and other extensions need to be updated to support 3.0.x and will not function otherwise, so we should document what all those changes are (probably in the wiki for this repository, or in the OpenCart documentation if that's more appropriate). The changes I've found necessary are:

* Updating from `.tpl` to `.twig` format (not required, but preferable)
* Renaming all extension settings (in Controllers & Views) to be prefixed with the appropriate type (esp. `_status` & `_sort_order`; e.g. `mytheme` to `theme_mytheme`, `mytheme_status` to `theme_mytheme_status`, `mytotal_sort_order` to `total_mytotal_sort_order`, etc.)
* Renaming Admin Controller URL paths that contain `extension/extension` to `marketplace/extension`
* Updating any call to views/templates to not specify the `.tpl` extension (as it'll be auto determined)

Anything else major I missed? I started documenting this in an [OpenCart forum thread](https://forum.opencart.com/viewtopic.php?f=199&t=186712) as well.

**Comment by danielkerr** [comment]
Checkout the opencart wiki for regex search and replace template variables

**Comment by danielkerr** [comment]
If u want to add any of this info then please add it there.
