### ISSUE TITLE
Admin Order Delete function doesn't work.

### ISSUE THREAD

**Issue by ratwasher** [opencart/opencart#5885]
admin > sale/order_list.twig line 140:
`<li><a href="{{ order.order_id }}"><i class="fa fa-trash-o"></i> {{ button_delete }}</a></li>`
Link to: yourstore.com/admin/855

You can edit the order, but can't delete.
It directly forwards to the store homepage, as there isn't a page at yourstore.com/admin/855
Normally it'd open the confirmation message about deleting, but it doesn't.

Also, official demo at Opencart's website has the same error.
Version 3.0.1.1

**Comment by danielkerr** [comment]
its fixed in the master branch

**Comment by ratwasher** [comment]
Your order_list.twig file doesn't work for me.

**Comment by danielkerr** [comment]
`Your order_list.twig file doesn't work for me.`

i dont care if it doesn't work for you

**Comment by ratwasher** [comment]
I don't want -you- to care my problem either.

I was trying to find a solution, and as it is a "develepment" forum, I tought it was the right place to write.


________________________________
