### ISSUE TITLE
Admin Order Delete function doesn't work.

### ISSUE THREAD

**Issue by ratwasher** [opencart/opencart#5886]
Reference to the issue #5885
The file danielkerr has edited (order_list.twig) doesn't work for me.
At the order list page, when you click on the arrow just near the order, DELETE function has the link
store.com/admin/order_number  > and doesn't work.

admin > sale/order_list.twig line 140:
`<li><a href="{{ order.order_id }}"><i class="fa fa-trash-o"></i> {{ button_delete }}</a></li>`
Link to: yourstore.com/admin/855

You can edit the order, but can't delete.
It directly forwards to the store homepage, as there isn't a page at yourstore.com/admin/855
Normally it'd open the confirmation message about deleting, but it doesn't.

Also, official demo at Opencart's website has the same error.
Version 3.0.1.1

**Comment by danielkerr** [comment]
github is for the development of opencart and not your support ticket system! use the forum or hire a developer.
