### ISSUE TITLE
Admin product list has empty rows

### ISSUE THREAD

**Issue by Hackej** [opencart/opencart#5892]
Hi!

Not a bug really - but admin\view\template\catalog\product_list.twig has a mix of code and empty rows starting at 56 and ending at 126.

/Hackej

**Comment by Hackej** [comment]
Update!
Same goes for Review list in Admin (admin\view\template\catalog\review_list.twig) - it's the new code for Filter on the left side.

BR
/Hackej

**Comment by ghs619** [comment]
sss

**Comment by danielkerr** [comment]
its just the source formatting. i fixed by switching to phpstorm
