### ISSUE TITLE
Canceling checkout issue

### ISSUE THREAD

**Issue by itechsolution84** [opencart/opencart#5896]
it looks like there are couple of bug at checkout in OC 3.0.2.0.
1: existing customer login don't work at checkout until I refresh the checkout by pressing f5
2: once payment method selected and order confirmed if I cancel payment and come back to website and select again method it is not recognized and always get message "Warning Payment method is required"

**Comment by danielkerr** [comment]
1. Because Ur email is not setup.
2. No idea but works fine for me and many others

Try updating
