### ISSUE TITLE
Uninstalling/Removing an extension issue

### ISSUE THREAD

**Issue by raxbg** [opencart/opencart#5898]
There is an issue with the new uninstall functionality (`marketplace/install/uninstall`) which deletes extension files. It should run the extension's uninstall method (for all controllers if more than one are provided by the extension) as well as refresh the modifications after it deletes the extension's modification.

Otherwise this operation can brick a store and leave the admin with no option to fix it, unless he knows how to delete the extension's events (if any) from the database and clear the modifications directory manually.

**Comment by danielkerr** [comment]
this is already fixed. as for the refresh mods myabe can add a button.

**Comment by danijelGombac** [comment]
I think is not fixed. There is not checking if the extension is still active. If the extension add some tables in the db and the unisnstall function removes the files before the extension was removed in the extensions page, how you remove the tables from the db.
