### ISSUE TITLE
Display the dimensions and weight on product list and product page

### ISSUE THREAD

**Issue by evgenekorolev** [opencart/opencart#5900]
Hi,
Please add in OpenCart 3 the ability to display the dimensions and weight on product list (category, manufacturer, search and special page) and product page, as well as weight should be calculate dynamically and display with change of option. This would be a great advantage of OpenCart.
Third-party plug-ins do not solve this completely, because not all Themes are supported.
Sorry for my bad english.
Thanks.

**Comment by evgenekorolev** [comment]
Why not?

**Comment by danielkerr** [comment]
Because it can be added as a product attribute.

**Comment by evgenekorolev** [comment]
Thank you, but I was talking a little about something else. For an example, see the attached images.
<img width="648" alt="0" src="https://user-images.githubusercontent.com/18613768/29687032-b79a464a-8923-11e7-856f-268312f65881.png">
<img width="484" alt="1" src="https://user-images.githubusercontent.com/18613768/29686711-b8a32b2a-8922-11e7-869a-f71bac1fd3ca.png">
<img width="203" alt="2" src="https://user-images.githubusercontent.com/18613768/29686712-b8a69d50-8922-11e7-9c60-854876efa959.png">
<img width="1160" alt="3" src="https://user-images.githubusercontent.com/18613768/29686713-b8a9a0a4-8922-11e7-92f3-cb8f0e781174.png">
<img width="384" alt="4" src="https://user-images.githubusercontent.com/18613768/29686714-b8c2dfd8-8922-11e7-8910-0ccf94f7b6b3.png">
<img width="379" alt="5" src="https://user-images.githubusercontent.com/18613768/29686715-b8c581c0-8922-11e7-9055-8d02c9ae178e.png">
