### ISSUE TITLE
no comment in customer order history

### ISSUE THREAD

**Issue by dzsamy** [opencart/opencart#5901]
Hi,

when update the order status with comment in admin, I don't get this comment in customer orders history section.
So, the problem is in this file: 
> catalog/controller/account/order.php
in this line ():
`'comment'    => $result['notify'] ? nl2br($result['comment']) : ''`
I have fixed by chang ethe line to:
`'comment'    => nl2br($result['comment'])`

Tested on oc2.x and oc3.x

**Comment by AvestaSaba** [comment]
There isn't any problem. You should check notify customer checkbox otherwise customer doesn't get the comment.
