### ISSUE TITLE
[Opencart 3.0.2.0] Related products / Filter fuzzy search suggestion

### ISSUE THREAD

**Issue by shkabo** [opencart/opencart#5905]
How to reproduce bug:
Create two products, while creating second, when you click on related product try to type some part of that product, it won't find it. By default it suggests products sorted by alphabet. Same thing is for search filter in product list. 
This option does work when creating product and for option to select categories.

**Comment by danielkerr** [comment]
just tested search and works fine. also able to filter by sub category

**Comment by zemguru** [comment]
Isn't the problem, that you tried to search "part" of project name, not by start of name?
Opencart uses wildcard `%` only at search string end:
`iMac`  will find `iMac 9000 professional` and not `Apple iMac 9000`

https://github.com/opencart/opencart/pull/4108#issuecomment-196493703

**Comment by shkabo** [comment]
@zemguru that's correct. 
That type of search works when you're trying to select category of a new product, but when you want to add related product, you need to start typing from the beginning of a product name, you just can't type `iMac` and get `Apple iMac 9000` but instead you need to type `Apple iMac` so that you'd get `Apple iMac 9000` as suggested/searched related product.

@danielkerr reopen this issue as this fuzzy search it's not working as it should. Either change product category search to work same as related product search or other way around as I reported. I got no idea what you tested but in my installation of 3.0.2.0 of OpenCart that search is not working as it should.

Again, to reproduce bug, create 10+ products (in initial post I said only two but you obviously need more than 5 as you have `limit 5` in your search query) with same prefix e.g. `Fruit` and then add 10+ random suffixes of fruits e.g. `Fruit Apple`, `Fruit Apricot`, `Fruit Avocado`, `Fruit Banana`, `Fruit Blackberry`, `Fruit Mango`, etc.  Now create next product and try to add e.g. `Mango` to the related product list. You'd need to type `Fruit Mango` in that search box before you get it displayed as suggested instead of just typing `Mango` in that search box.

Thanks
