### ISSUE TITLE
Paypal Express checkout working but there is a bug

### ISSUE THREAD

**Issue by itechsolution84** [opencart/opencart#5906]
Hi I have seen these errors in admin when I view order and at bottom there is Order history in that there is paypal express checkout tab if I click on that in Transaction I get these errors.

Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unexpected token "string" of value "Completed" ("name" expected) in "extension/payment/pp_express_transaction.twig" at line 25.' in /home/Domain/public_html/system/library/template/Twig/TokenStream.php:87 Stack trace: #0 /home/Domain/public_html/system/library/template/Twig/Extension/Core.php(304): Twig_TokenStream->expect(5) #1 /home/Domain/public_html/system/library/template/Twig/Extension/Core.php(277): Twig_Extension_Core->getTest(Object(Twig_Parser), 25) #2 [internal function]: Twig_Extension_Core->parseTestExpression(Object(Twig_Parser), Object(Twig_Node_Expression_GetAttr)) #3 /home/Domain/public_html/system/library/template/Twig/ExpressionParser.php(48): call_user_func(Array, Object(Twig_Parser), Object(Twig_Node_Expression_GetAttr)) #4 /home/Domain/public_html/system/library/template/Twig/ExpressionParser.php(78): Twig_ExpressionParser->parseExpression() #5 /home/Domain/public_html/system/library/template/Twig/ExpressionParser.php(41): in /home/Domain/public_html/system/library/template/Twig/TokenStream.php on line 87

**Comment by teamlouish** [comment]
Did you ever find a solution? I have the same error. Brand new install April 2018
