### ISSUE TITLE
Potential issue: Use of Yahoo Finance API for currency updates

### ISSUE THREAD

**Issue by lucasjkr** [opencart/opencart#5911]
Not sure if this has been discussed, but Yahoo has been removing access to some of its old API's as a result of its purchase by Yahoo. OC is getting currency prices from Yahoo, so I wondered if we should implement an alternate feed (either in addition to, or instead of, Yahoo), just as a safety measure. 

I'm happy to work on this if it's something that @danielkerr would want.

**Comment by danielkerr** [comment]
Any suggestions?

**Comment by schiggi** [comment]
Maybe these answers help?

https://stackoverflow.com/questions/3139879/how-do-i-get-currency-exchange-rates-via-an-api-such-as-google-finance

**Comment by lucasjkr** [comment]
Yes, here's Google something that's just as easy to scrape from Google:

https://www.google.com/finance/converter?a=1&from=EUR&to=USD

Don't need to drop Yahoo, could just have Google as a fall back SHOULD verizon decided to ditch this service.

**Comment by danielkerr** [comment]
im going to add in the next version the options to choose which api store owners want to use.

**Comment by lucasjkr** [comment]
That's what I've been thinking about - plugins for currencies, and let each exchange rate be provided by a different provider. Suggest also increasing the price fields to 8 decimal places to accommodate cryptocurrencies.

**Comment by CoverUp** [comment]
Hi guys, Finally Yahoo finance is out.
If you try to update you get the following message:

> It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.

Thus we need to implement google as a patch for the moment until the api selection be ready.

**Comment by lucasjkr** [comment]
Hi everyone.

I have a experimental fork of OC I'm working on, and created a method to pick up currency prices from what the ECB publishes rather than from yahoo finance. I also convert the values stored based on the base currency of the store.

https://github.com/lucasjkr/opencommerce/blob/cron-jobs/scheduler/jobs/RefreshCurrencies.php

Still in pretty rough shape, but it shouldn't be too difficult to convert that logic to become a replacement for currency->refresh(), at least until @danielkerr establishes the format for currency plug-ins.

If you'd like, I can probably submit a pull request tomorrow, just so that current OC users that have multi-currency stores can resume getting updates. Someone else could probably look at what I've done and do it in a few hours, I'm just too tired to work on it tonight. Please let me know your thoughts.

**Comment by lucasjkr** [comment]
FYI: The European Central Bank offers once a day updates for the following currencies:

EUR
USD
JPY
BGN
CZK
DKK
GBP
HUF
PLN
RON
SEK
CHF
NOK
HRK
RUB
TRY
AUD
BRL
CAD
CNY
HKD
IDR
INR
KRW
MXN
MYR
NZD
PHP
SGD
THB
ZAR
ILS

**Comment by ray-moncada** [comment]
Hi, I am looking for an alternative to yahoo finance. Is there any progress on this front? I look at several other providers that are free or relatively cheap: http://fixer.io/ and https://free.currencyconverterapi.com/.

**Comment by lucasjkr** [comment]
AFAIK It's being worked on. If you update your store to the latest code, it lets you manually set the exchange rate in the admin interface.

If you're in a pinch, you could probably use the code I offered:
https://github.com/opencart/opencart/blob/94e636989ef1872b0bc2f58a435c61a9c6af79d4/upload/admin/model/localisation/currency.php

But that could turn into a mess when code gets officially rolled out. I'd recommend against running a store with any of the core files modified, wherever possible.

**Comment by baldurg** [comment]
It's now been a year since the Yahoo Finance API shut down and Opencart still contains code that refers to Yahoo Finance API.

**Comment by danielkerr** [comment]
the master branch does not.
