### ISSUE TITLE
Voucher amount format when edit order

### ISSUE THREAD

**Issue by dzsamy** [opencart/opencart#5913]
When edit or add new order from admin I get the voucher amout without any currency format,
this in oc2.x & oc3.x:
> admin/view/template/sale/order_form.twig / .tpl
the 2 lines : 
`html += '  <td class="text-right">' + voucher['amount'] + '</td>';`
to:
`html += '  <td class="text-right">' + voucher['price'] + '</td>';`

**Comment by danielkerr** [comment]
works fine on 3.0!

**Comment by ADDCreative** [comment]
@danielkerr To recreate the issue in version 3.0.2.0.

Edit an order made in a currency other than the default.
On the 2. Products tab. Click the Voucher tab and add a voucher (note the voucher is displayed correctly here).
Continue to the 5. Totals tab where the voucher will be in the wrong currency with no formatting.
