### ISSUE TITLE
V3.x image manager

### ISSUE THREAD

**Issue by kalyannarra** [opencart/opencart#5914]
Opencart image manager doesn't show new folders or pictures immediately. Have to logout and login again to see new folders or pictures uploaded. I noticed that new folders and images are not getting created in image/cache/catalogue or data folders.  Anybody have an idea why this is happening?

**Comment by danielkerr** [comment]
Permission isdue

**Comment by kalyannarra** [comment]
well I think it's not a permission issue, I installed 2.3.x and it perfectly works on the same host. Same issue happening in any theme objects creation as well. New CMS blocks created by objects are not showing up either immediately. Something wrong with caching in new version.
