### ISSUE TITLE
Error/problem with header shopping cart (3021b) - not showing all products

### ISSUE THREAD

**Issue by Hackej** [opencart/opencart#5916]
Hi!

There is a problem with the header shopping cart, it doesn't show products correctly.

How to replicate (in clean install):
- Open Opencart
- From Featured add one MacBook and one iPhone - header SC says two products
- Click on header shopping cart - it only shows the iPhone
- Click Remove to remove product - it doesn't work
- Open Shopping Cart page
- Both products are visible and are possible to remove.

From clean install of 3021b taken from Github yesterday.

BR
/Hackej

**Comment by SCMES** [comment]
I have the same problem.

**Comment by danielkerr** [comment]
can not replicate plus no information like browser or php version

**Comment by Hackej** [comment]
Hi!

Update:
Local host/XAMPP - PHP version 5.6.20.

Problem in IE 11 - Chrome, Firefox and Safari is OK!

BR
/Hackej
