### ISSUE TITLE
HTTP Error 500 on website homepage after upgrade from OpenCart 1.5.6 to 2.3.0.2

### ISSUE THREAD

**Issue by macson12003** [opencart/opencart#5917]
Hi All, 

Just performed an upgrade on my opencart site from 1.5.6.4 to 2.3.0.2 but having issues with accessing the homepage of the site. The admin section works just fine. Below is a screenshot. 

Please help!

![error](https://user-images.githubusercontent.com/31445840/29828094-b3919b08-8cd3-11e7-8f1c-e999aeb52d6d.jpg)

**Comment by lucasjkr** [comment]
What does your apache error log say?
