### ISSUE TITLE
OC 3.0.2.0: Wrong heading_title in checkout/cart

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#5922]
If the checkout/cart has a non-empty left column, e.g. for module extension/module/account, then the heading_title for checkout/cart is wrong, e.g. it uses 'Account' instead of 'Shopping Cart'. Suggested bugfix for **catalog/controller/checkout/cart.php**:

```
		.....
		$this->document->setTitle($this->language->get('heading_title'));
		$data['heading_title'] = $this->language->get('heading_title');
		.....
```
See this OpenCart forum thread for more details: https://forum.opencart.com/viewtopic.php?f=190&t=187098&p=683906#p683906

**Comment by danielkerr** [comment]
can not replicate or its fixed in master branch

**Comment by mhcwebdesign** [comment]
No, it's NOT yet fixed in the master branch!

The controller/checkout/cart.php needs this missing line:
```
		$data['heading_title'] = $this->language->get('heading_title');
```

**Comment by danielkerr** [comment]
can not replicate

![untitled-1](https://user-images.githubusercontent.com/5079756/30198167-df37aa54-949e-11e7-842c-87b9e4efc301.jpg)

**Comment by mhcwebdesign** [comment]
I can still replicate this error using OC 3.0.2.0, so do other users, see above forum link!
I'll test it again with your latest master branch code and let you know what I get.

**Comment by mhcwebdesign** [comment]
Just tested it with OC 3.0.2.1b (master branch), and in that one it is indeed fixed, not sure what you changed, but it is working there.
