### ISSUE TITLE
Make more variables available in Theme Editor

### ISSUE THREAD

**Issue by architech99** [opencart/opencart#5925]
The way pages are built, it's limits the flexibility of the Theme Editor. The controller only adds variables for exactly what is needed in the stock version and doesn't include any additional variables/fields from product records. That's disappointing and very limiting. Any chance the devs can add more fields to the template (at very least, everything under the Data tab would be useful in addition to what's already there).

The way this is set up, you can display the Model, but you can't access the SKU, UPC, MPN, ISBN, etc. Could also be useful to have access to the Location field (some people might want to display something like "Ships from: {{ location }}").

I know this is a first version, but access to more of the fields inside the Theme Editor is going to be important to make it really useful.

**Comment by mhcwebdesign** [comment]
You could always write a view/*/before event handler which adds the missing variables to the $data array.

**Comment by OpenCartAddons** [comment]
While adding an even is possible, wouldn't it make more sense to dump all of the product data to the product page template?

A simple variable such as `$data['product_info'] = $product_info;` so that theme designers could utilize misc fields such as Location, JAN, ISBN, etc.

**Comment by architech99** [comment]
@mhcwebdesign I'm trying to avoid code-based customizations. My thinking is more along what @OpenCartAddons mentions - allow theme designers (who are anything but developers). I'm fine writing code, but the vast majority of individuals creating themes are not and it would be a very common use case where someone might want to include information from other fields if it's filled in by a site admin.

**Comment by architech99** [comment]
@danielkerr Was this closed because it was completed in a code branch or for some other reason?
