### ISSUE TITLE
OC 3.0.2.0: conflicting admin/controller/*/after event arguments

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#5926]
In file **admin/controller/startup/router.php** a post event is triggered like this:

```
		// Trigger the post events
		$result = $this->event->trigger('controller/' . $route . '/after', array(&$route, &$output));
```

whereas in file **system/engine/loader.php** a post event is triggered as follows:
```
		// Trigger the post events
		$result = $this->registry->get('event')->trigger('controller/' . $trigger . '/after', array(&$route, &$data, &$output));
```
The post controller events should always be triggered with  the **array(&$route, &$data, &$output)** and not the  **array(&$route, &$output)**

**Comment by danielkerr** [comment]
does not matter. there is no data to pass

**Comment by mhcwebdesign** [comment]
Yes, it does matter! Either the **&$output** has to be 2nd or the 3rd argument, but not both!
