### ISSUE TITLE
Custom ocmod modification not working in version 3.0.2.0

### ISSUE THREAD

**Issue by jkpatel291289** [opencart/opencart#5930]
whenever I upload myfile.ocmod.zip file from installer it uploaded successfully. but after that it neither appear in modification tab nor works on frontend. 

I think that only extension downloaded from marketplace is working.

For testing I downloaded "OpencartCatalogMenuHomebutton.v3-1.0.ocmod" extension and it works perfectly . So I have created  custom ocmod using this  working extension  (i.e. rename the folder to test and ziped it as test.ocmod.zip)  but it stops working. i had tried this two other working extension but it does not work.

**Comment by Manitoou** [comment]
Check this : https://github.com/opencart/opencart/issues/5852

**Comment by jkpatel291289** [comment]
@Manitoou  yes, I had read that issue before and followed the step correctly.

**Comment by jkpatel291289** [comment]
I have created repository for the extension.
[https://github.com/jkpatel291289/occustommod](url)

**Comment by amshehzad** [comment]
@jaynarayan89 same problem and i have tried everything but still got nothing... does your problem solved ?

**Comment by jaynarayan89** [comment]
@amshehzad nope.

**Comment by letscms** [comment]
Issue is creating ocmod.zip file

I am explaining by example

Suppose we have an extension that have following files as
**upload**
**install.xml**

then we need to zip both files as **extension_name.ocmod.zip**
But if we extract this zip file then files should not be extracted in **extension_name** directory
The .ocmod.zip file should be extracted with **extension_name** directory

as 
**upload**
**install.xml**

Hope it will solve your issue

**Comment by letscms** [comment]
The code is written in admin/controller/marketplace/install.php in line number 104

**Comment by efusionsoft** [comment]
@letscms is right above.

Structure of the your module or modification should be as below:

Zip file that needs to be installed: **module.ocmod.zip**

This zip should container: 
upload
install.xml

And a very **important** thing, your install.xml file must contain a **code** tag as below:
```
<?xml version="1.0" encoding="utf-8"?>
<modification>
    <code>230320181645</code>
	<name>SortOrder Change</name>
    <version>1.2</version>
    <author>Team E-Fusionsoft</author>
    <link>http://www.efusionsoft.com</link>
    <file path="catalog/controller/product/category.php">
        <operation>
            <search><![CDATA[
            $sort = 'p.sort_order';
            ]]></search>
            <add position="Replace"><![CDATA[
            $sort = 'pd.name';
            ]]></add>
        </operation>
    </file>  
</modification>
```
I've attached a sample zip file.
[sortorder.ocmod.zip](https://github.com/opencart/opencart/files/1841346/sortorder.ocmod.zip)

**Comment by rlasmar** [comment]
Someone can help me.

Every ocmod to modifiy the admin side is not working. I dont see changes. And there's no error.
But in the front-end ocmod modifications work.

I think is something with cache from opencart.
I already set to off in dashboard the mode developer and update. Also refresh modifications, but nothing to see changes.
