### ISSUE TITLE
Bug [ModelAccountApi]

### ISSUE THREAD

**Issue by darrisb** [opencart/opencart#5932]
3.0.2.0
Line 4:
		$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "api` WHERE `username` = '" . $this->db->escape($username) . "' `key` = '" . $this->db->escape($key) . "' AND status = '1'");

sql query needs to be:

		$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "api` WHERE `username` = '" . $this->db->escape($username) . "' AND `key` = '" . $this->db->escape($key) . "' AND status = '1'");

**Comment by zemguru** [comment]
Yet not fixed dev branch":
https://github.com/opencart/opencart/blob/dev/upload/catalog/model/account/api.php#L4
