### ISSUE TITLE
Cant use dump() function in twig files [oc3.0.2.0]

### ISSUE THREAD

**Issue by jkpatel291289** [opencart/opencart#5933]
I am trying to find which variables are available to use in the template using dump() function of twig but it gives error of undefined function. 

Then I search twig documentation and find out that it is disabled by default and we have to enable it but I think there is not any config option to turned on twig template debug in opencart 3.0.2.0.

when i dig the source code ,I found that twig is being initiated in catalog\controller\event\theme.php controller. I changed index  method (just for testing)to activate debug mode but it didn't  work.

```
if ($template) {
			// include and register Twig auto-loader
			include_once(DIR_SYSTEM . 'library/template/Twig/Autoloader.php');
			
			Twig_Autoloader::register();
					
			// specify where to look for templates
			$loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);		
			
			$config = array('autoescape' => false);
			
			if ($this->config->get('template_cache')) {
				$config['cache'] = DIR_CACHE;
			}

			**// create template_debug seting in config file
                       if ($this->config->get('template_debug')) {
				$config['cache'] = true;
			}**
			// initialize Twig environment
			$twig = new \Twig_Environment($loader, $config);
			**$twig->addExtension(new Twig_Extension_Debug());**	
			return $twig->createTemplate($template)->render($args);
		}
```

I think there should be a option to enable or disable twig debuging.

**Comment by lipedeitos** [comment]
Hi @jaynarayan89 i got this working changing the main file in `/system/library/template/twig.php`.
Add the `'debug' => true` to the `$config` array.
And finally add the `$this->twig->addExtension(new \Twig_Extension_Debug());` right after the `$this->twig = new \Twig_Environment($loader, $config);`.

```
public function render($template, $cache = false) {
    // specify where to look for templates
    $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);
    // initialize Twig environment
    $config = array('autoescape' => false, 'debug' => true);
    if ($cache) {
        $config['cache'] = DIR_CACHE;
    }
    $this->twig = new \Twig_Environment($loader, $config);
    $this->twig->addExtension(new \Twig_Extension_Debug());
	
    try {
        // load template
        $template = $this->twig->loadTemplate($template . '.twig');

        return $template->render($this->data);
    } catch (Exception $e) {
        trigger_error('Error: Could not load template ' . $template . '!');
        exit();	
    }	
}	
```

Cheers!

**Comment by jaynarayan89** [comment]
@lipedeitos  Thanks.
But this should be builtin feature. It would be inappropriate to change the core files.

**Comment by cyberfountain** [comment]
OpenCart bullshit man what did you expect :/

**Comment by danielkerr** [comment]
And another childish comment.

**Comment by RajeshThakur** [comment]
You can activate dump() function for twig environment by following these steps in opencart 3.0 :
1) Go to system/library/template/Twig/Environment.php
2) Here in constructor function you can find $options array. Set 'debug' option to 'true'.
3) Now we need to include debug extension, so
add $this->addExtension(new Twig_Extension_Debug());   below.
4) That's all we need to do. Now test if its working for you and update here.

**Comment by lSanik** [comment]
RajeshThakur: - Thank you MAN!)
danielkerr: - Bad! Fail - "-F". Sitdown pleas! XD

**Comment by stom66** [comment]
Sadly neither of these methods appear to work in OpenCart 3.0.2.0 under PHP 5.6.33, 7.0.27 or 7.1.18.

Is there an alternative way to dump template variables for debugging?

**Comment by hemantramphul** [comment]
Thanks @RajeshThakur

**Comment by jpasosa** [comment]
Thanks @RajeshThakur !! I test in OC 3.0.2 and perfect!

after use {{ dump()}} i use the next code, to know all keys in the view:
<ol>
    {% for key, value in _context  %}
      <li>{{ key }}</li>
    {% endfor %}
</ol>
{# and then #}
<pre>
    {{ dump() }}
</pre>
