### ISSUE TITLE
Theme edit - Feels broken

### ISSUE THREAD

**Issue by rbwilkinson** [opencart/opencart#5934]
I am trying to edit default theme using my favourite IDE. 

I am forced to use the built in Theme editor which although useful leaves me underwhelmed.
I had to figure out after a few hours to turn off cache although there are times the file reverts to older saves.

Is there a way I can just use my IDE to edit the .twig files?

**Comment by rbwilkinson** [comment]
Unbelievable. I am struggling to use this. And there was no attempt to help!!!

**Comment by danielkerr** [comment]
not the right question to be asked here. i use phpstorm.
