### ISSUE TITLE
bug in confirm password

### ISSUE THREAD

**Issue by vahidmotamen** [opencart/opencart#5936]
https://github.com/opencart/opencart/blob/f8ccc340b1a08caee7437ce2199f41105d6aef83/upload/catalog/controller/account/register.php#L267

hello
I think
"!=" should be converted to "!=="
Thank you for the lovely opencart script  :)

**Comment by danielkerr** [comment]
not really important

**Comment by vahidmotamen** [comment]
Confirm error does not work in your demo site!
If not important
so
Delete the password Confirm field.. 
thanks

**Comment by danielkerr** [comment]
what error dumbass!

you really think load of people wojnt bon here posting t issue over and over is the passsword confrim does not work!

its fine! stop wasting my time!
