### ISSUE TITLE
Product total price in checkout

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#5938]
checkout/confirm.php line 384:
`'total'      => $this->currency->format($this->tax->calculate($product['price'], $product['tax_class_id'], $this->config->get('config_tax')) * $product['quantity'], $this->session->data['currency']),`

is this better change to:

`'total'      => $this->currency->format($this->tax->calculate($product['total'], $product['tax_class_id'], $this->config->get('config_tax')), $this->session->data['currency']),`

**Comment by danielkerr** [comment]
should i guess the reason!!!!!

**Comment by pekka2** [comment]
Yes, I think, that this is easy puzzle :)

File library/cart/cart.php:
Line 247:
`'quantity'        => $cart['quantity'],`
Line 251.
`'price'           => ($price + $option_price),`
Line 252:
`'total'           => ($price + $option_price) * $cart['quantity'],`
Total sum is alreday calculated, why rebuild the wheel in file confirm.php?
