### ISSUE TITLE
Security issues found in opencart (#5923)

### ISSUE THREAD

**Issue by yzy9951** [opencart/opencart#5942]
Hi,
I didn't get my answer from issue #5923 , it has been closed before I reply to you.
1. "it will be a bullshit one that requires admin access"
-->It won't need any permission to trigger the issues.
2.  "please PM an OpenCart moderator/administrator on the forum"
-->There has no respond from my PM in the forum. (My forum ID is yzy9952.)

Please provide me a way to report them, it's better to provide me an email address to report them.
You can reach me at zyyang@fortinet.com

**Comment by jamesallsup** [comment]
Contact the support desk here:
https://www.opencart.com/index.php?route=support/contact

Ask for it to be forwarded to James and Daniel, include detail steps on how to product the issue please.

Putting an email address on a public location is an invitation to spam, I'd suggest you remove it from your comment.

J

**Comment by yzy9951** [comment]
@jamesallsup hi, I have tried to contacted the support desk (ticket 135078, support@opencart.com), they told me to post here for help, so here has 2 issue tickets #5923 and #5942. But I still can't find a way to report the security issue.

**Comment by jamesallsup** [comment]
OK I have asked the support team to forward your ticket over to me directly.
