### ISSUE TITLE
Bug of affiliate ( 2017-09-05 )

### ISSUE THREAD

**Issue by AlexChanHK** [opencart/opencart#5943]
Bug of affiliate of master version

1. Even the status of affiliate is disabled, 
once there is linked affiliate data to the customer,
the user can still able to use the function like Custom Affiliate Tracking Code.

2. Not able to edit the affiliate setting of the customer account.
The system will get form database, but it will not update.

For detail of the reason, need some time for checking.

**Comment by danielkerr** [comment]
works as it should. does not mean the affiliate is approved nor will he receive money
