### ISSUE TITLE
$pagination->url SSL

### ISSUE THREAD

**Issue by robinflyhigh** [opencart/opencart#5945]
We need to set the $secure to true for all $pagination->url

Eg:

Filename: upload/catalog/controller/product/category.php

Change
$pagination->url = $this->url->link('product/category', 'path=' . $this->request->get['path'] . $url . '&page={page}');

To

$pagination->url = $this->url->link('product/category', 'path=' . $this->request->get['path'] . $url . '&page={page}', true);

Defination: public function link($route, $args = '', $secure = false) {}

If agreed I can share a pull request.

**Comment by zemguru** [comment]
Wouldn't it be better, to take these settings automatically in `url->link` Class, if not already? 
If site has SSL settings and SSL is enabled, then use if and only SSL "secure" links?

**Comment by danielkerr** [comment]
not required all urls
