### ISSUE TITLE
Cannot set default language in OpenCart 3.0.2.0

### ISSUE THREAD

**Issue by donhuvy** [opencart/opencart#5952]
Update: In administration page, I go to menu ```System \ Settings```. Edit the preferences of store. In tab local. I change Country to ```Viet Nam```, ```Region / State``` to ```Ha Noi```, ```Language``` to ```Vietnamese```, ```Currency``` to ```VND```. Then I delete cache directory. In web browser, I clear all browsing data, go to: http://localhost:my_port , but It still choose ```English``` as default language.

<img width="1440" alt="screen shot 2017-09-08 at 20 38 38" src="https://user-images.githubusercontent.com/1328316/30214205-c0c630a4-94d5-11e7-8c14-480cae35e827.png">

In source code, File ```/upload/system/library/language.php```, I also changed
```
class Language {
	//private $default = 'en-gb';
    private $default = 'vi-vn';
```

In initialized status, it can't choose ```Vietnamese``` as default language.
<img width="1440" alt="screen shot 2017-09-08 at 20 39 35" src="https://user-images.githubusercontent.com/1328316/30214275-fdf2339c-94d5-11e7-9132-d7d96998ed89.png">

https://stackoverflow.com/questions/46117169/how-to-set-default-currency-in-opencart-3

**Comment by danielkerr** [comment]
because the 1st choice is stored in a cookie. u need to clear your cookies to start from stratch.

**Comment by donhuvy** [comment]
As I written: " I clear all browsing data". I have been cleared cookies to start from scratch.

**Comment by xsaito** [comment]
same here, by default it always opens up in english, while my default is russian.
cache is clear and also i can see squares instead icons.

**Comment by donhuvy** [comment]
@xsaito , I resolved, I (maybe temporary) re-open my answer: https://stackoverflow.com/a/46131714/3728901

**Comment by danielkerr** [comment]
check your site base and urls that they are on the same host and both use ssl or http

**Comment by kazanakius** [comment]
@donhuvy hello, can i know how you fixed it? I am having the same problem in my 3.0.2.0 installation. Please.

**Comment by Vermond125** [comment]
Still relevant for me. Done everything. 
- Browser's cache (cockies...) cleared,
- Opencart's cache cleared,
- Settings are all right (in admin section added language, changed store language).
Back office (admin) works, language changed. But front office (catalog) works in english, and same for currency.
Opencart 3.0.2.0

**Comment by Vermond125** [comment]
@kazanakius , Aha! I suspected this kind of behavior, but my browser is on russian language, but IP is not, anyway...
It is quite strange behavior. I mean, if you selected language as default you want your website to use this one. If you have autodetection, perhaps, it's a good idea to disable this feature (even to have an opportunity to do so).
Hm. If changing core (vqmod) or hardcode is the best option right now. It is sad.
Thanx for your advice. I have only one word to describe the whole situation: "Opencart"...

**Comment by aleksandrnikitenko** [comment]
At /catalog/controller/startup/startup.php 

Comment this block. 

`		// Language Detection
/*		if (!empty($this->request->server['HTTP_ACCEPT_LANGUAGE']) && !array_key_exists($code, $languages)) {
			$detect = '';
			
			$browser_languages = explode(',', $this->request->server['HTTP_ACCEPT_LANGUAGE']);
			
			// Try using local to detect the language
			foreach ($browser_languages as $browser_language) {
				foreach ($languages as $key => $value) {
					if ($value['status']) {
						$locale = explode(',', $value['locale']);
						
						if (in_array($browser_language, $locale)) {
							$detect = $key;
							break 2;
						}
					}
				}	
			}			
			
			if (!$detect) { 
				// Try using language folder to detect the language
				foreach ($browser_languages as $browser_language) {
					if (array_key_exists(strtolower($browser_language), $languages)) {
						$detect = strtolower($browser_language);
						
						break;
					}
				}
			}
			
			$code = $detect ? $detect : '';
		}*/`

Opencart intends to detect users preferable language, so we have those issues.
