### ISSUE TITLE
array_key_exists(): The first argument should be either a string or an integer 

### ISSUE THREAD

**Issue by lachiquilla** [opencart/opencart#5953]
Hello!

After importing some tables from another database I have this prestashop error:

Warning: array_key_exists (): The first argument should be either a string or an integer in /htdocs/public/www/tienda/modules/blocklayered/blocklayered.php on line 2835

That line is as follows:

if (array_key_exists ($ filter_link_rewrite, $ option_checked_array))

and this is the expanded fraction in which this line is inserted:

foreach ($ filter_blocks as & $ type_filter)
{
$ filter_name = (! empty ($ type_filter ['url_name'])? $ type_filter ['url_name']: $ type_filter ['name']);
$ filter_link_rewrite = Tools :: link_rewrite ($ filter_name);

if (count ($ type_filter)> 0 &&! isset ($ type_filter ['slider']))
{
foreach ($ type_filter ['values'] as $ key => $ values)
{
$ nofollow = false;
if (! empty ($ values ​​['checked']) && in_array ($ type_filter ['type'], $ blacklist))
$ global_nofollow = true;

$ option_checked_clone_array = $ option_checked_array;

// If not filters checked, add parameter
$ value_name =! empty ($ values ​​['url_name'])? $ values ​​['url_name']: $ values ​​['name'];

if (! in_array (Tools :: link_rewrite ($ value_name), $ param_group_selected_array [$ filter_link_rewrite]))
{
// Update parameter filter checked before
if (array_key_exists ($ filter_link_rewrite, $ option_checked_array))
{
$ option_checked_clone_array [$ filter_link_rewrite] = $ option_checked_clone_array [$ filter_link_rewrite] $ this-> getAnchor (). str_replace ($ this-> getAnchor (), '_', Tools :: link_rewrite ($ value_name));

if (in_array ($ type_filter ['type'], $ blacklist))
$ nofollow = true;
}
else
$ option_checked_clone_array [$ filter_link_rewrite] = $ this-> getAnchor (). str_replace ($ this-> getAnchor (), '_', Tools :: link_rewrite ($ value_name));
}
else
{
// Remove selected parameters
$ option_checked_clone_array [$ filter_link_rewrite] = str_replace ($ this-> getAnchor (). str_replace ($ this-> getAnchor (), '_', Tools :: link_rewrite ($ value_name)), '', $ option_checked_clone_array [$ filter_link_rewrite] );
if (empty ($ option_checked_clone_array [$ filter_link_rewrite]))
unset ($ option_checked_clone_array [$ filter_link_rewrite]);
}
$ parameters = '';
ksort ($ option_checked_clone_array); // Order parameters
foreach ($ option_checked_clone_array as $ key_group => $ value_group)
$ parameters. = '/'. str_replace ($ this-> getAnchor (), '_', $ key_group) $ value_group;

I have no idea what it means or what to modify ... I spend my life trying, searching for google, or asking for help in blogs, .. and that way I solve problems and learn something :)

My shop with the error: https://vivirahora.es/tienda/es/3-alimentacion
(the filter also does not display the category name, only the number of matches)

Thanks in advance and please be patient that I am new to this!

Ana

Ps. I enclose blocklayered.php 

[blocklayered.txt](https://github.com/opencart/opencart/files/1288307/blocklayered.txt)

**Comment by PeterStudioWeb** [comment]
And at what here PrestaShop???
This branch about OpenCart.

**Comment by lachiquilla** [comment]
Ok, sorry!
