### ISSUE TITLE
OC 3.0.2.1b: marketplace/installer/upload bug

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#5954]
In file admin/controller/marketplace/installer.php, in function upload, the call at

```
$extension_install_id = $this->model_setting_extension->addExtensionInstall($this->request->files['file']['name']);
```
causes an error. It expects a 2nd argument, namely the **$extension_id**, which isn't known at this stage. I am not sure how this could be fixed. This issue reflects the fact that you added the extension_id column to the DB table 'oc_extension_install'.

**Comment by stalker780** [comment]
#5949

**Comment by mhcwebdesign** [comment]
So does the mean that the oc_extension_install.extension_id does not point to the 'oc_extension' table then? Rather, that it refers to the Opencart marketplace extension_id? If so, your suggested fix should work.

**Comment by danielkerr** [comment]
already fixed

**Comment by waqasbaberpk** [comment]
is there is any difference in 3.0.2.1b vs 3.0.2.1?
