### ISSUE TITLE
PayPal Express checkout working but there is a bug

### ISSUE THREAD

**Issue by venta7** [opencart/opencart#5955]
Hi, I see errors in Order History - PayPal Express checkout tab:

Fatal error: Uncaught Twig_Error_Syntax: Unexpected "endfor" tag (expecting closing tag for the "if" tag defined near line 24) in "extension/payment/pp_express_transaction.twig" at line 31. in /home/folder/mysite.com/system/library/template/Twig/Parser.php:172 Stack trace: #0 /home/folder/mysite.com/system/library/template/Twig/TokenParser/If.php(34): Twig_Parser->subparse(Array) #1 /home/folder/mysite.com/system/library/template/Twig/Parser.php(187): Twig_TokenParser_If->parse(Object(Twig_Token)) #2 /home/folder/mysite.com/system/library/template/Twig/TokenParser/For.php(40): Twig_Parser->subparse(Array) #3 /home/folder/mysite.com/system/library/template/Twig/Parser.php(187): Twig_TokenParser_For->parse(Object(Twig_Token)) #4 /home/folder/mysite.com/system/library/template/Twig/TokenParser/If.php(34): Twig_Parser->subparse(Array) #5 /home/folder/mysite.com/system/library/template/Twig/Parser.php(187): Twig_TokenParser_If->parse(Object(Twig_Token)) #6 /home/folder/mysite.com/system/library/ in /home/folder/mysite.com/system/library/template/Twig/Parser.php on line 172

**Comment by itechsolution84** [comment]
Hi 
https://github.com/opencart/opencart/commit/e452fe01dd9e04a0e05ccc1b710d3005de1f4807
here is the fix
