### ISSUE TITLE
Problem with Custtomer form (Transactions & Rewards) in IE11

### ISSUE THREAD

**Issue by Hackej** [opencart/opencart#5957]
Hi!

When editing Transactions or Reward in admin Customer Form the new values is not displayed directly in IE 11. You get a confirmation of successfully updated customer, but the new entry is not  shown in the history, either directly or after Save and going back to the customer form. 
If you Log out and go back to the customer the correct entries are displayed. 
Works in Chrome as intended with entry presented in history list with slight delay!

Seems to be a problem with IE 11 only, similar to my other post #5916 where cart content isn't updated/refreshed/presented correctly!

Tested on local host/XAMPP - PHP version 5.6.20.
Just compared IE 11 and Chrome - no other browser at this stage.

BR
/Hackej

**Comment by danielkerr** [comment]
works for me.

its not working for you maybe because u have not setup the mail system and also the php display_errors is not setup.

**Comment by danielkerr** [comment]
check your error log. opencarts and php
