### ISSUE TITLE
Mail alert not working for Register and Orders

### ISSUE THREAD

**Issue by jdotchai** [opencart/opencart#5962]
My OpenCart version is 3.0.2. I've problem with Mail notification, it not sending email to admin and also customer for new register and new order. The contact form and review are fine. I've checked with hosting, tested and they report the SMTP (currently using) is working correctly. So I doubt there's problem with database as I have this issue since upgrade from version 2 to 3. I've this problem when I was with previous hosting, I blamed it and switch to other hosting now and the problem still exists, tried replace all files with current version 3.0.2 but still its' not working, the only data Inherited is database. Possible that some data are missing during the upgrade? Here my Mail settings:

Mail Engine: SMTP
Mail Parameters: -finfo@domain.com
SMTP Hostname: ssl://my.hostname.com
SMTP Username: info@domain.com
SMTP Port: 465
SMTP Timeout: 15

Alert Mail: All checked

Please help!

**Comment by danielkerr** [comment]
works for me and tested this many times

**Comment by danielkerr** [comment]
SMTP Port: 465 means u are using gmail.

check if u setup app password and u should not need parameters

**Comment by zemguru** [comment]
Also, check SSL connection - does the server can connect to SSL SMTP server?
Sometime hostings have problem with certificates (rare, but has happen)

**Comment by jdotchai** [comment]
I've finally fixed it. I think is because the incomplete upgrade last time that caused database oc_event empty, which make those scripts fail being triggered. I've fixed it after re-insert data copying from the install folder. Btw, is it safe to run the upgrade file again, even my OC is 3.0.2? Will it reset and erase my database?

**Comment by Tsulaeman** [comment]
@jdotchai this was helpful, thank you very much

**Comment by Tollermine** [comment]
This helped me: https://forum.opencart.com/viewtopic.php?t=186236&start=20

I just installed Opencard locally and exported the oc_event. Then I renamed the oc_event in my shop and imported the oc_event from my fresh install.
