### ISSUE TITLE
Cart Total always showing $0.00

### ISSUE THREAD

**Issue by architech99** [opencart/opencart#5964]
I've been trying to figure this one out for several days and so far, it's pointing to a logic error in the shopping cart subtotal calculation. Initially, I was always seeing $0.00 as the subtotal for the shopping cart displayed on the "View Cart" button (i.e. "1 items - $0.00"). I thought it was related to the Journal theme at first, but couldn't find it doing anything different and the issue persisted when I reverted my site to use the default Opencart theme.

After dumping some debugging data to my screen, I found that it was correctly totaling up a single item to be "$34.00". However, when trying to output that total into the text_items template variable, it was attempting to apply the currency formatting to the variable again, which is what was resulting in the zero total value (because the "$" isn't numeric and when casting the value to a float - which was happening in the currency formatter method).

I believe the solution is to change instances where the product's total is being formatted with this line of code:
```
$total = $this->currency->format($unit_price * $product['quantity'], $this->session->data['currency']);
```
to calculate the raw numeric value as so:
```
$total = $unit_price * $product['quantity'];
```
In some cases, it also appears that the value of the text_items template variable is being set before the total is calculated, which may result in erroneous information being displayed. This may also be impacting other parts of Opencart processes, but I can't confirm that right now. If the calculation is coming up zero in other components and/or controllers, it could be passing incorrect data further down the stack (i.e. to extensions) and causing unexpected behaviors there.

I believe the solution for this is to move the assignment of the text_items template variable to the data array that gets passed to the template engine to the end of the method which generates the shopping cart.

**Comment by danielkerr** [comment]
this is not a suport area.,

**Comment by architech99** [comment]
@danielkerr And this isn't a support question. It's pointing out an issue in the Opencart application code that needs to be fixed.
