### ISSUE TITLE
file exist but unable to load in opencart

### ISSUE THREAD

**Issue by tansukhcodoffer** [opencart/opencart#5966]
The file column_left.twig exist but the browser shows following error

`Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "common/column_left.twig" (looked into: C:/xampp/htdocs/default/catalog/view/theme).' in C:\xampp\htdocs\default\system\library\template\Twig\Loader\Filesystem.php:215 Stack trace: #0 C:\xampp\htdocs\default\system\library\template\Twig\Loader\Filesystem.php(139): Twig_Loader_Filesystem->findTemplate('common/column_l...') #1 C:\xampp\htdocs\default\system\library\template\Twig\Environment.php(312): Twig_Loader_Filesystem->getCacheKey('common/column_l...') #2 C:\xampp\htdocs\default\system\library\template\Twig\Environment.php(378): Twig_Environment->getTemplateClass('common/column_l...', NULL) #3 C:\xampp\htdocs\default\system\library\template\twig.php(33): Twig_Environment->loadTemplate('common/column_l...') #4 C:\xampp\htdocs\default\system\library\template.php(51): Template\Twig->render('common/column_l...', '1') #5 C:\xampp\htdocs\default\system\engine\loader.php(125): Template->render('common/column_l...', '1') #6 C:\xam in C:\xampp\htdocs\default\system\library\template\Twig\Loader\Filesystem.php on line 215`

How to solve it?

**Comment by futurelab3d** [comment]
How was this problem solved? I have the same problem when using a new theme.

**Comment by tansukhcodoffer** [comment]
its still a problem with my Opencart. I have removed common templates from controller which is still generate this errors.

You can reply if you resolved this problem.

**Comment by futurelab3d** [comment]
No it is still a problem.

**Comment by howdu** [comment]
I'm not able to reproduce this myself but from looking at the code I think the problem is from the theme/override method. The first IF statement prevents template_directory from being set and likely cause this error. 

https://github.com/opencart/opencart/blob/master/upload/catalog/controller/event/theme.php#L47

```php
public function override(&$route, &$args, &$template) {
	if (!$this->config->get('theme_' . $this->config->get('config_theme') . '_status')) {
		exit('Error: A theme has not been assigned to this store!');
	}

	// If the default theme is selected we need to know which directory its pointing to
	if ($this->config->get('config_theme') == 'default') {
		$theme = $this->config->get('theme_default_directory');
	} else {
		$theme = $this->config->get('config_theme');
	}

	// If there is a theme override we should get it
	$this->load->model('design/theme');

	$theme_info = $this->model_design_theme->getTheme($route, $theme);

	if ($theme_info) {
		$template = html_entity_decode($theme_info['code'], ENT_QUOTES, 'UTF-8');
	} elseif (is_file(DIR_TEMPLATE . $theme . '/template/' . $route . '.twig')) {
		$this->config->set('template_directory', $theme . '/template/');
	} elseif (is_file(DIR_TEMPLATE . 'default/template/' . $route . '.twig')) {
		$this->config->set('template_directory', 'default/template/');
	}
}
```

Maybe it needs to be:
```
	if ($theme_info) {
		$template_directory = html_entity_decode($theme_info['code'], ENT_QUOTES, 'UTF-8');
	} elseif (is_file(DIR_TEMPLATE . $theme . '/template/' . $route . '.twig')) {
		$template_directory = $theme . '/template/';
	} elseif (is_file(DIR_TEMPLATE . 'default/template/' . $route . '.twig')) {
		$template_directory = 'default/template/';
	}

	$this->config->set('template_directory', $theme . '/template/');
```

**Comment by jpshdev** [comment]
I am running into this currently as well. I am not finding where the override function is being called, and any code changes I make in the function are not executed. Any suggestions would be appreciated as to where this function is called from during execution.
