### ISSUE TITLE
Unable to Upload Large FIles Through Downloads Section

### ISSUE THREAD

**Issue by DrewGamble** [opencart/opencart#5967]
I've been trying for days to upload a large PDF 150mb to my Downloads to sell as a product but every single time i just get this error with nothing else. I've tried altering my php.ini but nothing works.

I'd rather just upload through FTP like it says I can but I can't find out where to upload it to or how to properly write the filepath in the section and anything i do just gets me a "file doesn't exist" error

![145901f52d48d3b4d5d4026aef54f010 1](https://user-images.githubusercontent.com/19988233/30409958-8aad21b0-994b-11e7-8056-5f4e98787465.png)

**Comment by danielkerr** [comment]
upload via ftp to the downloads folder then  enter the name manually.
