### ISSUE TITLE
why the user can able to change email id ? why the basic functionality of email verification you have not included? 

### ISSUE THREAD

**Issue by rsmmukesh** [opencart/opencart#5970]
why the user can able to change email id ? why the basic functionality of email verification you have not included? email verification is a basic functionality for all websites why don't you include it. according to a programmer is it a good way that user able to change email id after sign up with another email id?

don't close the issue before clarify my doubt

**Comment by danielkerr** [comment]
its not the norm for shopping web sites. im sure theres and extension for it.  should not be hard to code.

**Comment by lucasjkr** [comment]
@rsmmukesh End of the day, you don't want to disrupt your user from making a purchase. 

Why should you make them wait to validate their email before being allowed to make a purchase? You don't want them leaving that screen.

And after they've made the purchase, its too late, why try to make them validate their email then?

**Comment by rsmmukesh** [comment]
let see,  consider your emailid is "lucasjkr@gmail.com" . but im going to create an account with your email id and going to purchase a product, it will be successful. after some days you are going to signup (original owner of email id) what will happen? site will give a message "Email id already exist" . original owner of the email id user will not be able to signup.  is it the right way?

**Comment by danielkerr** [comment]
use the forum fro this type of conversation! also dont call me out again to get an answer to a question. this stuff is very easily reseached.

**Comment by rsmmukesh** [comment]
im talking about functional bug in the application. It is not a time pass conversation . now you are not understanding the problem. you are thinking only in developer view , In future you will know about it.  im a software engineer and i have 6 year of experience in web development , im not a child to have time pass conversations here.

**Comment by danielkerr** [comment]
im a software engineer as well with many more years of experience! do ur own research in future!
