### ISSUE TITLE
OC 3.0.2.1 twig.php Fatal Error

### ISSUE THREAD

**Issue by eplanetdesign** [opencart/opencart#5971]
Updated to v3.0.2.1 from v3.0.2.0 and when I cleared Modifications I got:
Fatal error: Uncaught Error: Class 'Twig_Loader_Filesystem' not found in /home/username/services.mywebsite.com/system/library/template/twig.php:13

Looked at the v3.0.2.0 /system/library/template/twig.php and added back:

```
	public function __construct() {
		// include and register Twig auto-loader
		include_once(DIR_SYSTEM . 'library/template/Twig/Autoloader.php');
		
		\Twig_Autoloader::register();
	}
```
...no more error.

**Comment by danielkerr** [comment]
replace this file with the one from the latest version. i dont think all the files were transferred properly.
