### ISSUE TITLE
Mismatching language key in contact form

### ISSUE THREAD

**Issue by yodapt** [opencart/opencart#5974]
version 3.0.2.0

Success message doesnt appear after contact form is submitted due to mismatching keys.

**catalog\view\theme\default\template\common\success.twig**

`{{ text_message }}`

**catalog\language\en-gb\information\contact.php**

`$_['text_success']   = '<p>Your enquiry has been successfully sent to the store owner!</p>';`

**Comment by danielkerr** [comment]
its fixed in the masterbranch
