### ISSUE TITLE
i have some error during opencart installation. i entered correct values in all field. pls help  me

### ISSUE THREAD

**Issue by yasiyasi** [opencart/opencart#5978]
Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /home/vol13_5/capnix.com/cnix_20712152/htdocs/system/library/db/mysqli.php on line 7Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /home/vol13_5/capnix.com/cnix_20712152/htdocs/system/library/db/mysqli.php on line 10Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /home/vol13_5/capnix.com/cnix_20712152/htdocs/system/library/db/mysqli.php on line 10Notice: Undefined variable: mysql in /home/vol13_5/capnix.com/cnix_20712152/htdocs/install/controller/install/step_3.php on line 280Notice: Trying to get property of non-object in /home/vol13_5/capnix.com/cnix_20712152/htdocs/install/controller/install/step_3.php on line 280

**Comment by danielkerr** [comment]
what ever info u used its wrong!

**Comment by yasiyasi** [comment]
Thank you for ur reply

**Comment by gautamidslab** [comment]
Warning: mysqli::__construct(): (42000/1044): Access denied for user 'honorabase'@'localhost' to database 'honorabase' in /home/global5005/public_html/upload/system/library/db/mysqli.php on line 7Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /home/global5005/public_html/upload/system/library/db/mysqli.php on line 10Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /home/global5005/public_html/upload/system/library/db/mysqli.php on line 10Notice: Undefined variable: mysql in /home/global5005/public_html/upload/install/controller/install/step_3.php on line 280Notice: Trying to get property of non-object in /home/global5005/public_html/upload/install/controller/install/step_3.php on line 280

**Comment by gautamidslab** [comment]
please help me

**Comment by zemguru** [comment]
Please, check your user name and password, also the permissions on the database. Try to connect to the database from command line mysql, or phpmyadmin. The error is self explaining:

```Access denied for user 'honorabase'@'localhost' to database 'honorabase' ``` - it usually means incorrect username/password/database permissions.

**Comment by danielkerr** [comment]
Mysql php extension driver is not installed. Change the config.php to a
different mysql driver.

**Comment by sanakamadhuchandini** [comment]
can you please check once.Are you connected in team viewer. whats is the
problem.

**Comment by gautamidslab** [comment]
thanks its solved by by on line installation of opencart
