### ISSUE TITLE
Admin login not working

### ISSUE THREAD

**Issue by shreenate** [opencart/opencart#5979]
Hello,
After giving credentials of admin it generates token in url but admin dashboard is not visible, it shows login screen all the time with no errors.
If admin credentials is correct then only it generates token in url but if admin credentials is wrong then it will show Incorrect User name.

My issue is admin can not access dashboard.

Url- jioplant.com/admin
user - admin
password - imvikrant
PLEASE CHECK ASAP

**Comment by danielkerr** [comment]
this is not for support also u have just given away your username and password on a public developer board!

use the opencart.com forum or the contact us for support form.
