### ISSUE TITLE
changes to .twig not showing? 

### ISSUE THREAD

**Issue by alex067** [opencart/opencart#5980]
I've been attempting to remove some buttons on the store page, such as wishlist and compare product, which aren't really necessary for my store. 

I attempted to remove those buttons on the product/cateogory.twig and replace them with something else, however the store keeps showing the wishlist and compare product buttons. I've disabled caching from the developer settings, cleared it, removed cache from storage, tried a different browser, yet the store still loads those buttons which should have been removed.

**Comment by danielkerr** [comment]
try removing oc mod files.
