### ISSUE TITLE
OCMOD Is not showing up in Modifications

### ISSUE THREAD

**Issue by amshehzad** [opencart/opencart#5984]
Hi friends, 
i am creating a ocmod file.
i created a file name install.xml and place the following code in it : 
```
<?xml version="1.0" encoding="utf-8"?>
<modification>
    <name>Modify PowerBy Text</name>
    <version>1.0</version>
    <author>Shehzad</author>
    
    <file path="catalog/language/en-gb/common/footer.php">
        <operation>
            <search>
            <![CDATA[
            $_['text_powered']      = 'Powered By <a href="http://www.opencart.com">OpenCart</a><br /> %s &copy; %s';
            ]]></search>
            <add position="replace"><![CDATA[
            $_['text_powered']      = 'Powered By <a href="http://www.facebook.com/shehzad47">Shehzad</a><br /> %s &copy; %s';
            ]]></add>
        </operation>
    </file>  
</modification>

```
then i created an empty folder called upload and zipped _intall.xml_ and _upoad_ folder into mod.ocmod.zip when i upload it , It uploads and installs okay, at least I get a successful installation message. However, when I go to the Modifications page, I do not see it even after clicking the Refresh button. In addition, when I refresh my site, the modification is not seen.
i have already checked [#5852](https://github.com/opencart/opencart/issues/5852) and follow the steps mentioned their but that doesn't help me.

**Comment by osworx** [comment]
Your xml need additionally this line:
`<code>your_name_code</code>`
in the header (beside name, version, etc.)

And why replacing the whole line and not anly the URL-part?

**Comment by amshehzad** [comment]
i had that line added but i removed that to check if that was creating issue or not as the code tag is not included in the official documentation.

**Comment by osworx** [comment]
What for do you think is this here:
https://github.com/opencart/opencart/blob/9d085aec78b7f92e21a1e075371366e178f005c7/upload/admin/controller/marketplace/install.php#L282

Does no matter if in official docuemtation, it is requried.
And why should that line make troubles??

**Comment by amshehzad** [comment]
@osworx i give it a try and include that line too but still no result :(

**Comment by osworx** [comment]
Just tested your code above (with the line <code>..</code>) and it works as it should - OC 3.0.2.0
Which version do you have?
And - because the installer works perfectly - you should look for help in the forum, not here.

**Comment by danielkerr** [comment]
i will add the documentation as soon as i have finished the cloud stuff. the cloud is priority.

**Comment by danielkerr** [comment]
some is alreayd done here:

https://github.com/opencart/opencart/wiki

any one want to add let me know
