### ISSUE TITLE
Funny bug $this->session 

### ISSUE THREAD

**Issue by 123fork** [opencart/opencart#5985]
Hi folks!

Today I was surprised by funny bug.

My **controller**

```
public function update{
	$this->session->data['test'] = 'new_value';
	var_dump($this->session);
}
```

My **view**
```
$.ajax({
    url: 'index.php?route=module/module/update',
    dataType: 'html',
    cache: false,
    type: 'post',
    success: function(html) {
        alert(html);
    }
});
```

Alert message contain $test variable and new value. 
But "oc_session" contain $test previous value.
Only by 5-10 ajax reloading oc_session get new value.
When I open page index.php?route=module/module/update by browser (not ajax), $this→session work as if nothing had happened and I see new value in DB.

**Comment by danijelGombac** [comment]
I have similar problem in checkout page with payment and shipping methods. Randomly the session is not set and the error occur. I fix that by adding in function save another foreach getMethod and creat again

`$this->session->data['payment_methods']`

**Comment by danielkerr** [comment]
can u give me more examples?

**Comment by 123fork** [comment]
I have tried to change $_['session_engine'] value (db/file) and DB_DRIVER (mysqli/mpdo) in config. 

The result was the same. In ajax response I was receiving new value of $this→session→data[foo]. 

But really (in db/file) session_id’s $foo wasn’t changing.  And randomly (5-10 ajax reloadings) $foo was getting new_value. 

Another example:

**Controller_1**
```
public function updateValue{
        $this->session->data['foo'] = 'new_value';
        var_dump($this->session);
}
```
**Controller_2**
```
public function getValue{
        var_dump($this->session);
}
```
**View**
```
$.ajax({
    url: 'index.php?route=module/module/updatevalue',
    success: function(html1) {
        alert(html1);

        $.ajax({
            url: 'index.php?route=module/module/getvalue',
            success: function(html2) {
                alert(html2);
            }
        });

    }
});
```
First alert: $foo has "new_value"
Second alert: $foo has "previous_value" ($foo wasn't changed)

**Comment by danielkerr** [comment]
why not var dump the session->data

**Comment by danielkerr** [comment]
oh ok i get it. because the session is not writing to the file until after the main page has loaded or  vice visa. 

look into jquery functions .then and .done

i have used these functions on the order editing page.

**Comment by 123fork** [comment]
> because the session is not writing to the file until after the main page has loaded

```
//OK I declare two variables in Controller
$this->session->data[foo] = 1;
$this->session->data[bar] = 2;

//Get sum
$this->session->data[result] = $this->session->data[foo] + $this->session->data[bar];

//Return value
echo $this->session->data[result];

//Get value in view
$( document ).ready(function(){
    $.ajax({
        url: 'index.php?route=module/module/updatevalue',
    }).done(function(html){
        alert(html);
    });
});
```

Alert message return sum. How can I really know that the session was written or not? :)
I think if the session was not written, alert message should be return notice: "undefined variable" or something like this.

**Comment by danielkerr** [comment]
Because if there are multiple Ajax connections open it does not close the
connection until the first one is complete. I'm not sure this is a opencart
issue but jQuery

**Comment by danielkerr** [comment]
There is no issue. Just how Ajax works
