### ISSUE TITLE
Newsletter - Spam

### ISSUE THREAD

**Issue by webcorvo** [opencart/opencart#5986]
With Gmail mail smtp configuration on OC,
The newsletter goes to **SPAM** folder.

**ONLY** the first email of the DB, goes to the inbox folder, the rest goes to **SPAM** folder

**Comment by CoverUp** [comment]
I have just solved this for an store, is not a OC issue, is related to your server configuration and mail settings. You will see this problem with google and hotmail also. Regards

**Comment by danielkerr** [comment]
if ur sending out a lot of mails really u need to be using services like mail chimp.

theres a lot into it. you need to use filter services to filter out spam email addresses.

**Comment by webcorvo** [comment]
ok tks @CoverUp and @danielkerr
