### ISSUE TITLE
Seo Url Dont't work in alll Url

### ISSUE THREAD

**Issue by eduardohenriquesousasilva** [opencart/opencart#5988]
Hello, somebody helps me about de Seo Url, it doesn't work in all url, example in home, in cart and other

index.php?route=

I want to remove this.. to friendly url

**Comment by CoverUp** [comment]
Is not a issue, use forum instead.
BTW you didn't mention what OC version you are using and my crystal ball is out of service right now. In OC 3.0.3 you got SEO Url config tab to do it. Any way go to forums for this. You can also get help in spanish or portugues. Y asi te ahorra estar traduciendo :P
