### ISSUE TITLE
Error 500 - Install Step 3 - 3.0.2.1b

### ISSUE THREAD

**Issue by allanespinoza** [opencart/opencart#5993]
Hi,

Please i have downloaded the last version of OC, from Master. But when i try make a new install, i receive an 500 error.

Can you check it. I have test the install on 3 different servers.

Thanks.

**Comment by zijege** [comment]
Try set full access (777) to directory
system/storage/cache

**Comment by osworx** [comment]
First: never ever (!!!) set any directory to 0777
The most stupid idea and a bad advice.
Why: afterwards you forget to set it back to the correct value of 0755 - everybody can everything in this dir.

Second: you tried the install with the files from master.
Did you also try to install an official version: https://github.com/opencart/opencart/releases/tag/3.0.2.0
And if, same error?

**Comment by zemguru** [comment]
Agree with @osworx - `0777` is bad. Unfortunately, there is multiple places in OC with that setup, but that's a different question: https://github.com/opencart/opencart/search?utf8=%E2%9C%93&q=0777&type=

**Comment by osworx** [comment]
@zemguru Would be better if they change it to umask() and work with that!

**Comment by nita-au** [comment]
I have the same issue:

`PHP Fatal error:  Uncaught Exception: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DROP TABLE IF EXISTS `oc_event`' at line 13<br />Error No: 1064<br />CREATE TABLE `oc_download_report` (\n  `download_report_id` int(11) NOT NULL AUTO_INCREMENT,\n  `download_id` int(11) NOT NULL,\n  `store_id` int(11) NOT NULL,\n  `ip` varchar(40) NOT NULL,\n  `country` varchar(2) NOT NULL,\n  `date_added` datetime NOT NULL,\n  PRIMARY KEY (`download_report_id`)\n) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci\n\n\n\nDROP TABLE IF EXISTS `oc_event`;\n in /var/www/html/3.0.2.1b/system/library/db/mysqli.php:40\nStack trace:\n#0 /var/www/html/3.0.2.1b/system/library/db.php(45): DB\\MySQLi->query('CREATE TABLE `o...')\n#1 /var/www/html/3.0.2.1b/install/model/install/install.php(26): DB->query('CREATE TABLE `o...')\n#2 /var/www/html/3.0.2.1b/system/engine/loader.php(248): ModelInstallInstall->database(Array)\n#3 /var/www/html/3.0.2.1b/system/engine/proxy.php(4 in /var/www/html/3.0.2.1b/system/library/db/mysqli.php on line 40, referer: http://localhost/3.0.2.1b/install/index.php?route=install/step_3`

**Comment by zemguru** [comment]
can You, please, add this error between `~~~` like:

~~~
    ~~~
    PHP Fatal error: Uncaught Exception: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQ...
    ~~~
~~~

**Comment by waxedperfection** [comment]
upload/install/opencart.sql

LINE 1387 ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

**Comment by danielkerr** [comment]
this has been fixed in previous commit. the ;  was missing from oc_download_report
