### ISSUE TITLE
Klarna Checkout not working in OC 3.0.2.0

### ISSUE THREAD

**Issue by mrschumi** [opencart/opencart#5996]
The Klarna Checkout payment extension included with OC 3.0.2.0 does not seem to work. Has anyone actually tested this? It appears to have been written for an earlier version of OC and not updated for 3.x.

When I try to activate the extension, the following error message pops up:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
OK
Notice: Undefined index: api_token in /catalog/controller/startup/session.php on line 8

And when I click on the save icon, it says "Success: You have modified Klarna Checkout account details!", but none of the changes I make are actually saved.

**Comment by mrschumi** [comment]
In addition, the settings need to be prefixed with 'payment_' (e.g. 'klarna_checkout_status' -> 'payment_klarna_checkout_status') so that other OC components will recognize it as a valid payment module.

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/issues/6014
 
adding the fix now
