### ISSUE TITLE
In Dashboard recent activity always shows no result? 

### ISSUE THREAD

**Issue by patil-akshay** [opencart/opencart#5998]
Even if user is doing some activity on website the recent activity shows no results why is it so and can we identify somehow failed login attempts by user?

**Comment by danielkerr** [comment]
U need to activate it

**Comment by danielkerr** [comment]
Settings

**Comment by patil-akshay** [comment]
can you explain in detail?

**Comment by danielkerr** [comment]
no! dont be lazy!
