### ISSUE TITLE
How can we integrate google analytics in it?

### ISSUE THREAD

**Issue by patil-akshay** [opencart/opencart#5999]
how can I integrate the google analytics API in the website

**Comment by zemguru** [comment]
You mean, Google Analytics tracking code?

1. Go to:
*Extensions > Extensions*

2. choose `Analytics` from drop-down
3. click `Install` green button
4. click `Edit` and paste Analytics code, 
5. set it to `Enabled`.

should do the trick. Depends from your version a bit.

**Comment by patil-akshay** [comment]
This part I know but what exactly do we need to write in code that is my point?

**Comment by zemguru** [comment]
Go to https://analytics.google.com, create a free account and follow the instructions.
Anyway - that is not an Opencart question and you can use Google to find the code and instructions, how to get one!
