### ISSUE TITLE
How can we track failed login attempts

### ISSUE THREAD

**Issue by patil-akshay** [opencart/opencart#6001]
I want to track the failed login attempts of a user

**Comment by zijege** [comment]
Look in `validate` method in `catalog/controller/account/login.php`

**Comment by danielkerr** [comment]
oc_customer_login

i need to create a report for them. but u can unlick accounts in the admin

**Comment by osworx** [comment]
But as of OC 3.0.2.x inside this controller (validate) only attempts are logged if the email & password check fails.
Would'nt it be handy, to have an option to log also other tries?
