### ISSUE TITLE
PHP 0: Error: No such file or directory Error No: 2002 in OC 3.0.2.0

### ISSUE THREAD

**Issue by chalermporn** [opencart/opencart#6004]
PHP 0: Error: No such file or directory
Error No: 2002 in /Users/bird/PROJECT/opencart/upload/system/library/db/mysqli.php on line 10

MAMP PHP7.1.6

**Comment by zijege** [comment]
Error No: 2002 = "Can't connect to MySQL"
Check MySQL server status, maybe he not started or blocked by firewall.
And check mysql configuration settings in config.php file

**Comment by pekka2** [comment]
@chalermporn Can you use _mysqli?

**Comment by danielkerr** [comment]
closing this issue as it sounds like file not properly uploaded. i have not seen that error before.
