### ISSUE TITLE
Editing existing records at Design > Language Editor

### ISSUE THREAD

**Issue by rmullaney77** [opencart/opencart#6009]
After creating a language file override, then trying to edit the same entry, when saving we encounter...

**Notice: Undefined index: key in /[...]/admin/controller/design/translation.php on line 412**

Also, the validation error "Key must be between 3 and 64 characters!" is displayed.

Re-selecting the desired Route and Key allows us to save changes.

Error occurs because "key" field is disabled when editing and there is no hidden field with the same name holding the previous value. EG: Disabled inputs are not included in POST data.

PS (Just my 2¢)...

1. Language Editor should be under "System > Settings > Localisation"
2. SEO URLs should be under "System > Settings"

Neither have anything to do with "Design" where they are currently located ;)

**Comment by straightlight** [comment]
For odd reasons, the admin/view/template/design/translation_form.twig file seem to have a selectable name and an input name containing the same 'key' name in Opencart v3.0.2.0 ... looks like these two form categories may need to contain different names.

**Comment by rmullaney77** [comment]
The names do not need to be changed for my reported issue, just add a
hidden field named "key" to preserve the value since the dropdown is
disabled ehen editing an existing record. No idea if that solution would
also apply to your reported problem as I have not looked at that form in
depth

**Comment by straightlight** [comment]
One problem by setting hidden fields is the validateForm method that still validates those identical inputs from the HTML form once being passed over PHP while renaming those two fields to their separate names only requires to add an additional field name into the validateForm method.

**Comment by rmullaney77** [comment]
Validation would be fine without changes. The error I am referring to is triggered by the field being omitted from the request completely (result of being disabled for display purposes) with not supporting hidden field to pass the value

**Comment by straightlight** [comment]
That could be done from jQuery but still would be a great feature added by
the team if considered in the future.

**Comment by rmullaney77** [comment]
Why even bother with jquery, especially when validation still needs to be done server-side anyhow. Maybe you are not familiar with that of which I am referring.

This is a simple issue and easy to fix. It is not the first time a similar solution would have been applied. I could dig into 2.x and point out instances that were properly handled as suggested. Just an oversight in a new controller and its associated view ;)

**Comment by straightlight** [comment]
jQuery was mentioned so that it would validate the keys being passed
through the HTML form from the header. This can also be easily implemented
but also another side of view.

**Comment by rmullaney77** [comment]
Doesn't make sense to add jquery into a form that can easily be fixed by the addition of a hidden field in a conditional statement. Not going to try convincing someone why jquery is completely unnecessary for this situation ;)

Note: unsubscribing since this is becoming less constructive :P

**Comment by rmullaney77** [comment]
whoops... did not mean to close the issue (doh)

**Comment by straightlight** [comment]
Again, that is only one side of view since it would totally make sense to
parameter each hidden fields that either needs to be enabled or disabled
rathed than playing with the render library.

**Comment by xguntis** [comment]
Here is a fix if someone needs [Language Editor FIX OC3](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=38690&filter_member=1.partneris)

**Comment by Kippykip** [comment]
Still seems to be an issue even today, a workaround is to open "/admin/view/template/design/translation_form.twig"

Scroll to about line 99 and just comment ALL of this out:

`$('select[name="store_id"]').prop('disabled', true);
$('select[name="language_id"]').prop('disabled', true);
$('select[name="route"]').prop('disabled', true);
$('select[name="key"]').prop('disabled', true);
$('input[name="key"]').prop('disabled', true);`

Seems to fix it, albiet it also lets you type in a box where you shouldn't. Just be sorta careful I guess.
