### ISSUE TITLE
Deleting languages

### ISSUE THREAD

**Issue by rmullaney77** [opencart/opencart#6010]
Existing SEO URLs are not removed when corresponding language is deleted at System > Localisation > Languages

**Comment by straightlight** [comment]
In admin/model/localisation/language.php file,

find:

$this->db->query("DELETE FROM " . DB_PREFIX . "language WHERE language_id = '" . (int)$language_id . "'");

add below:

$this->db->query("DELETE FROM " . DB_PREFIX . "seo_url WHERE language_id = '" . (int)$language_id . "'");

This should resolved the problem.

**Comment by rmullaney77** [comment]
Know how to fix, reported so it doesnt persist in the next release ;)

**Comment by straightlight** [comment]
The instructions above were not posted as instructions ... it was posted for everyone to see this fix in the future before the next release. Apologize for the confusion ...
