### ISSUE TITLE
PayPal not accepting long characters

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6011]
An issue has been addressed with PayPal regarding long characters vs shorten characters. A maximum limit would need to be set from the PayPal payments modules. The Opencart version was not specified during troubleshooting: https://forum.opencart.com/viewtopic.php?f=198&t=190403

**Comment by AlexChanHK** [comment]
I had tested with PayPal standard and seen the PayPal not accepting product option over about 60 chars,
however it is the limit set in PayPal site and over chars in the option of the product is not comment.

If you want to prevent this case you can refer this [line](https://github.com/opencart/opencart/blob/30a364314e43ed3cb5526639e036e27b0774f821/upload/catalog/controller/extension/payment/pp_standard.php#L45) and apply the check method to the [option name](https://github.com/opencart/opencart/blob/30a364314e43ed3cb5526639e036e27b0774f821/upload/catalog/controller/extension/payment/pp_standard.php#L44) make it shorter.
But it is the issue of Opencart system, therefore I think this issue **can be closed**.
