### ISSUE TITLE
[v3.0.2.0 - Fix] - Firstdata remote payment services

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6013]
The following steps are for Opencart v3.0.2.0 release. If your site is running in production, put your site under maintenance.

1 - Take a screenshot of your admin firstdata remote payment module configurations.
 2 - Uninstall the firstdata remote payment module.
 3 - Download the ZIP file from this location: https://github.com/straightlight/opencart_contributions/blob/master/extension/payment/firstdata_remote/3.0.2.0/upload.zip

4 - Reinstall the firstdata remote payment module.
 5 - Reconfigure the firstdata remote payment module.
 6 - Test a transaction during checkout.
 7 - When successful, disable the site maintenance (if running in production).

This should overall resolve the status issues along with other variables.

**Comment by danielkerr** [comment]
can't believe i missed this stuff out.

**Comment by danielkerr** [comment]
also dont do 

$this->request->get['user_token']; 

it should be 

$this->request->get['user_token'];

also thx for the help. although doing a commit would have been better.

**Comment by zemguru** [comment]
Where is the difference?

![image](https://user-images.githubusercontent.com/30476178/31047287-86bd760a-a610-11e7-9247-52d6b0c05f6c.png)

**Comment by straightlight** [comment]
Just to indicate, the $this->request->get['user_token'] was already part of the code when I found it. However, that is correct, this is an invalid statement with the user_token. It should rather be replaced with:

$this->session->data['user_token'];
