### ISSUE TITLE
[v3.0.2.0 - Fix] - Klarna Checkout Payment Services

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6014]
The following steps are for Opencart v3.0.2.0 release. If your site is running in production, put your site under maintenance.

1 - Take a screenshot of your admin klarna checkout payment module configurations.
 2 - Uninstall the klarna checkout payment module.
 3 - Download the ZIP file from this location: https://github.com/straightlight/opencart_contributions/blob/master/extension/payment/klarna_checkout/3.0.2.0/upload.zip

4 - Reinstall the klarna checkout payment module.
 5 - Reconfigure the klarna checkout payment module.
 6 - Test a transaction during checkout.
 7 - When successful, disable the site maintenance (if running in production).

This should overall resolve the status issues along with other variables.

**Comment by Erikas013** [comment]
How I can download it?

**Comment by chrisriss** [comment]
Hi there, how/where can i download that fix? The link above in "3 - Download the ZIP file from this location: ..." gives me a 404 
Cheers

**Comment by qprod74** [comment]
Any update on this issue ? I have been struggling for weeks but I cannot get it to work , about that download ZIP , does anybody have it ? 
Thanks

**Comment by vyasdeep** [comment]
> Any update on this issue ? I have been struggling for weeks but I cannot get it to work , about that download ZIP , does anybody have it ?
> Thanks

Recently Klarna API version has been upgraded from old V2 to latest V3. So I had implemented the same for Klarna Checkout and Klarna Payment 

Please let me know, If any looking for same

**Comment by craigbaines** [comment]
> > Any update on this issue ? I have been struggling for weeks but I cannot get it to work , about that download ZIP , does anybody have it ?
> > Thanks
> 
> Recently Klarna API version has been upgraded from old V2 to latest V3. So I had implemented the same for Klarna Checkout and Klarna Payment
> 
> Please let me know, If any looking for same

I could do with this if you have it? not sure how i contact you directly on here...
