### ISSUE TITLE
[v3.0.2.0 - Fix] - Pilibaba Payment Modules

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6016]
The following steps are for Opencart v3.0.2.0 release. If your site is running in production, put your site under maintenance.

1 - Take a screenshot of your admin pilibaba payment module configurations.
 2 - Uninstall the pilibaba payment module.
 3 - Download the ZIP file from this location: https://github.com/straightlight/opencart_contributions/blob/master/extension/payment/pilibaba/3.0.2.0/upload.zip

4 - Reinstall the pilibaba payment module.
 5 - Reconfigure the pilibaba payment module.
 6 - Test a transaction during checkout.
 7 - When successful, disable the site maintenance (if running in production).

This should overall resolve the status issues along with other variables.

**Comment by danielkerr** [comment]
straightlight, where do u work?

**Comment by straightlight** [comment]
I am located in Canada.
