### ISSUE TITLE
Problem accessing the user group

### ISSUE THREAD

**Issue by ovicko** [opencart/opencart#6017]
On click the **user group menu** below errors are show
Notice: Undefined property: ModelUserUserGroup::$db in C:\xampp\htdocs\projects\opencart\opencart3020\upload\admin\model\user\user_group.php on line 57
Fatal error: Call to a member function query() on null in C:\xampp\htdocs\projects\opencart\opencart3020\upload\admin\model\user\user_group.php on line 57

**Comment by danielkerr** [comment]
remove any extension u have installed. i havernt had anyone report problems with the user group page. maybe try the forums.
