### ISSUE TITLE
[v3.0.2.0 - Fix] - Amazon Pay Payment Module and PayPal Login Module

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6018]
A bug fix has now been posted regarding the encountered and passed issues of the Amazon Pay Payment Module and the PayPal Login Module: https://forum.opencart.com/viewtopic.php?f=201&t=191657&p=690718#p690718

**Comment by danielkerr** [comment]
this would cause big issues:

In catalog/controller/extension/module/amazon_pay.php file,

find all instances of:
Code: Select all

config->get('payment_
replace each with:
Code: Select all

config->get('module_payment_

**Comment by straightlight** [comment]
Steps removed.
