### ISSUE TITLE
[v3.0.2.0 - Admin Google Base Extension]

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6020]
There are many input names not matching the settings on that extension. The reason a patch cannot be posted is for the following form fields:

By changing these two fields, it would create a conflict:

google_base_category
and
category

would become:

feed_google_base_category
feed_google_base_category

Less generic field names would need to be used in order to resolve this issue definitely.

**Comment by danielkerr** [comment]
this is not required because we dont want the data stored in the config table. its stored in its own table. 

if you notyice only values that have the extension prefix and the code of the file get stored.

**Comment by straightlight** [comment]
This part should be documented since, even I, had to dig a little in order to get that answer as it should also be practical for others.
