### ISSUE TITLE
[v3.0.2.0 - Tweak] - Admin Fraud Extension IP module

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6021]
A bug fix has been posted on this topic since users in the past were reporting issues adding IP addresses from the Admin Fraud Extension IP module: https://forum.opencart.com/viewtopic.php?f=201&t=191671#p690737

**Comment by straightlight** [comment]
The title should rather display: 'Tweak', not 'Fix'. Although, I can't seem to edit it.

**Comment by danielkerr** [comment]
again not required as it saves the data into its own table. u need to test this stuff before reporting!
