### ISSUE TITLE
[v3.0.2.0 - Fix] - Admin Bestseller Extension Module

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6024]
Bug fixes solutions have been posted on the forum: https://forum.opencart.com/viewtopic.php?f=201&t=191674#p690741

**Comment by danielkerr** [comment]
not sure this is correct.  some modules dont work the same as other extensions.

**Comment by straightlight** [comment]
Correct. All this time, I thought it was the 'editSetting' method since I had to do so many of them. This one was about 'addModule' and 'editModule'. The steps on the topic have now been removed.
