### ISSUE TITLE
[v3.0.2.0 - Fix] - API session engine and registry parameters fixed

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6034]
A bug-fix solution has been posted for a line correction in the catalog/controller/api/login.php file: http://forum.opencart.com/viewtopic.php?f=201&t=191608&sid=bacf7df4f5709d0ad1e1e5fddfe65d7a#p690510

**Comment by danielkerr** [comment]
im kicking my self

**Comment by danielkerr** [comment]
can not find this issue in the master branch

**Comment by straightlight** [comment]
Perhaps not but this is where it was found from the Opencart downloads page originally. Otherwise, I wouldn't need to replace the line.
