### ISSUE TITLE
The 'text_empty' localized text error of 'product/category' if it is empty

### ISSUE THREAD

**Issue by aszucs74** [opencart/opencart#6035]
Hi,
the 'text_empty' key exists both the 'product/cart.php' and 'product/category.php' language files.
The language file of cart loaded also before the product category page rendered in the index() method of ControllerProductCategory class. So the 'text_empty' of cart displayed instead of empty category message.
Regards,
Arpad Szucs

**Comment by straightlight** [comment]
It is indeed quite of odd that the catalog/controller/checkout/cart.php file contains an if statement with 'or' by validating the vouchers but also having an additional if statement to see if this voucher is set. The 2nd if statement should suffice as to avoid going to the 'else' statement with the text_empty key.

**Comment by rmullaney77** [comment]
'text_empty' being used instead of 'text_no_results' is occurring in many places as of 3.0.2.0.

We think it is due to recent language class and/or loader changes.

Hoping this will not be present in the next release. We are now treating 3.0.2.0 as not being production-ready :/

**Comment by straightlight** [comment]
I understand. Indeed, it doesn't seem to be production ready after the
mount of bugfixes I had to post on github.

**Comment by danielkerr** [comment]
@stalight!

'it doesn't seem to be production ready'

post stupid comments like this again u will be banned!

there is no issue here and most of the issue with fixes have been non issues! wasted a lot f time checking them! i appreciate the 1st few you did but you don't have the years of experiance with open source cms's to make that sort of opinion! 

opencart is the most popular shopping cart system out! look at other github php repositories that have 1000's of unfixed issues months old!

**Comment by danielkerr** [comment]
text_empty mean the cart is empty. also its no using a table its using the error template.

there is no issue here! its you 2 being picky! wasting my time because u think it should work a different way when it doesn't matter!

**Comment by rmullaney77** [comment]
@danielkerr Please reopen or create a new issue based on this information...

Example of 'text_empty' being used in the wrong place...

https://github.com/opencart/opencart/blob/master/upload/catalog/view/theme/default/template/product/category.twig

```
      {% if not categories and not products %}
      <p>{{ text_empty }}</p>
```

Should be...

```
      {% if not categories and not products %}
      <p>{{ text_no_results }}</p>
```
As far as we can tell, this is the case in **every** front-end twig that displays multiple results.

Your team coded the twigs with the wrong language variable is all. Shit happens.

**Comment by rmullaney77** [comment]
Started new issue https://github.com/opencart/opencart/issues/6070
