### ISSUE TITLE
unlink cache language error message appears on top

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6037]
An issue I was able to reproduce with OC v3.0.2.0 when entering the store on first sight with empty cache folder. Another user has also reported the same issue on the forum: https://forum.opencart.com/viewtopic.php?f=201&t=186797&p=690815#p690815

system/cache/file.php file contains the file exists function. Another solution would need to be used to see if files can also be written along with its existence or not.

**Comment by danielkerr** [comment]
Should be fixed now. I removed a check if file exsits
