### ISSUE TITLE
[v3.0.2.0 - Concept] - jQuery console logs still active. Not suggested on production network

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6038]
On the forum, I posted all the files that may require to disable the console.log for Opencart users running on a production network since there's nowhere to be mentioned that only an admin can see the outputted values on the browser's console. In this case, better to comment out this command if they don't need to be removed.

https://forum.opencart.com/viewtopic.php?f=24&t=191726&p=690894#p690894

**Comment by JesseOC** [comment]
Double check the new version, already been removed.
