### ISSUE TITLE
[v3.0.2.0 - Concept] - Throw new exception errors

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6040]
On the forum, I have posted all the PHP file locations where the throw new exception errors are being used: https://forum.opencart.com/viewtopic.php?f=24&t=191730#p690901

**Comment by straightlight** [comment]
Forum post updated. Found additional files with \Exception rather than just the use of Exception.

**Comment by lucasjkr** [comment]
Most of these are 3rd party libraries from the Vendor directory. Let's not touch them, unless you want to be responsible for them in the codebase. But it's much easier to use these libraries and let their own developers maintain them, than make the code a part of OC

**Comment by jamesallsup** [comment]
You don't modify vendor package files regardless of the code, ever - the files should not technically be pushed into the repository as a build system would normally get the latest version when packaging a release.
