### ISSUE TITLE
[v3.0.2.0 - Bug / Concept] - All concerned files using the exit command function

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6042]
All concerned files using the exit command function: https://forum.opencart.com/viewtopic.php?f=24&t=191733 . 

They should be replaced with alternative solutions so not to interrupt the administrator / customer / affiliate.

**Comment by danielkerr** [comment]
i disagree with this. as long as mysql config is setup properly the db should automatically drop connections.
