### ISSUE TITLE
[v3.0.2.0 - Limited Func / Concept]

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6047]
At this time, merchants cannot transmit their order ID upon successful checkout transactions to their providers other than the payment gateway that has been used during checkout. It would be great to add the order ID within the data variable from the success.php file so that merchants could add the provided JS code into the success.twig file. Granted, the order ID is about to be unset in the controller from that location but at least it will provide the merchants one time per transaction to transmit the information towards their providers before that actual transaction officially ends on the browser.

While this analogy may not be about a bug specifically, it is still, however, a limited functionality which merchants cannot officially complete at the end of their checkout or without using the API from the admin orders.

A solution has been posted on the forum: https://forum.opencart.com/viewtopic.php?f=24&t=191768 . However, in this post, the idea is mainly to add the order ID into the data array from the controller in order to be able to use it from the success.twig file.

**Comment by straightlight** [comment]
In addition, this controller should particularly handle SSL and not being used as a public page on the browser since the customer needs to be redirected at this point.

**Comment by straightlight** [comment]
The topic on the forum has been updated in compliance of the order invoice prefix and the order invoice number.

**Comment by danielkerr** [comment]
if its an extension they are building they can do it via events system and feed it into the twig template

**Comment by danielkerr** [comment]
dont ask for things that only helping you. this sort of stuff is wasting my time. to do a js api request you require the order id. im assuming this is for some 3rd party tracking for sales. analytics. if so do it as an extension using the event system.
