### ISSUE TITLE
[v3.0.2.0 - Fix] - SSL parameters

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6048]
Wrong SSL parameters have been found on this version of Opencart. Instructions have been posted on the forum: https://forum.opencart.com/viewtopic.php?f=202&t=191778#p691036

**Comment by stalker780** [comment]
You are making a good job, but why don't you post fixes as pull requests?

It will be faster than creating a forum topic, creating an issue and wait till Daniel reads a forum post, checks it, find described lines in sources and creates a pull request.

**Comment by straightlight** [comment]
While half of the people are aware of the Github pull requests, the other half of people on Opencart forum is where to would rather remain. By posting in both places, both parties are being notified.

**Comment by danielkerr** [comment]
some of his fixes are will causes more issues so its better i got through them first.

**Comment by danielkerr** [comment]
this is not true!

`if ((isset($_SERVER['HTTPS']) && (($_SERVER['HTTPS'] == 'on') || ($_SERVER['HTTPS'] == '1'))) || (isset($_SERVER['HTTPS']) && (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443))) {
	$_SERVER['HTTPS'] = true;
} elseif (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' || !empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] == 'on') {
	$_SERVER['HTTPS'] = true;
} else {
	$_SERVER['HTTPS'] = false;
}`

**Comment by straightlight** [comment]
I am not sure I understand your last post. What do you mean by not true? The last parameter that needs to be used is either and indeed true or false ... which is exactly what I mentioned on the topic. The list of files I posted on the topic does not provide a true or false boolean with the URL method while they should as the same along the rest of the controllers already does ...

**Comment by danielkerr** [comment]
Where u say 

Otherwise, an 'off' / 'on' statement would be passed.

Is incorrect. The system/startup.php changes it to true or false not on or off.

**Comment by straightlight** [comment]
Ok, I understand. The super global already enforces to a true or false statement throughout the platform.
