### ISSUE TITLE
[v3.0.2.0 - Concept / Tracked] - Die command

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6050]
A new forum post has been created based on the die command that has been tracked on several files that would prevent an action or event to be completed by a user or a customer: https://forum.opencart.com/viewtopic.php?f=24&t=191782#p691051

**Comment by straightlight** [comment]
Concept extended on this post with Paypal PP payment module: https://forum.opencart.com/viewtopic.php?f=24&t=191782&p=691173#p691173

**Comment by danielkerr** [comment]
not really anything required to fix
