### ISSUE TITLE
[v3.0.2.0 - Restrictions with templates] - Restrictions for editing templates

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6052]
Some may say it's a bug, others may see it as an imprisonment. It seem that when using a third party tool to edit template files, the changes won't take effect unless clearing the cache each times 'unless' using the admin theme editor.

There is one input I'd like to add to this concept. I have been using Opencart for a long time now and if there's one thing I like to use when editing any type of files is obviously with my own tools without having to clear cache all the time. TPL files did not required to do so nor should the TWIG files. This is definitely an issue that should be addressed as it must be resolved.

Programmers do have their own materials that they feel comfortable to work with and the theme editor may definitely not be one of them. The theme editor tool itself may work great. Although, if this is the only tool that will not involve any manual operations afterwards for 'each' file savings, then I call for 'limitations of use'. The internet is not about limitations of tools but rather limitations of account access or groups access, not limiting access to the tools we're using that reflects unchanged results to the files without clearing cache.

Topic: https://forum.opencart.com/viewtopic.php?t=186075#p681311

**Comment by lucasjkr** [comment]
Production systems shouldn't be rebuilding templates every time a page loads.

I suggest a dev setting disable the cache, rather than attempting to get rid of the cache mechanism all together.

**Comment by mhcwebdesign** [comment]
IMHO this is indeed a caching bug in the Twig engine.
If I have my own web theme, with caching enabled for Twig, and I do some changes to a twig-template file, e.g. let's say **catalog/view/theme/my-theme/common/header.twig** , using my own text editor tool and FTP, the Twig engine won't pick it up. Any decent caching system should always compare the original file with it's cached version and automatically refresh the cache when there are differences.

**Comment by danijelGombac** [comment]
I use auto_reload 

When developing with Twig, it's useful to recompile the template whenever the source code changes. If you don't provide a value for the auto_reload option, it will be determined automatically based on the debug value.

```
public function render($template, $reload = false) {
        $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);

        $config = array(
            'autoescape'  => false,
            'auto_reload' => $reload,
            'cache'       => DIR_CACHE
        );

        $this->twig = new \Twig_Environment($loader, $config);

        try {
            $template = $this->twig->loadTemplate($template . '.twig');

            return $template->render($this->data);
        } catch (Exception $e) {
            trigger_error('Error: Could not load template ' . $template . '.twig!');
            exit();
        }
    }
```

**Comment by straightlight** [comment]
@mhcwebdesign: Couldn't agree more.

**Comment by mhcwebdesign** [comment]
@danijelGombac : You are right, **auto_reload** should be used for the Twig_Environment.

**Comment by straightlight** [comment]
Those activities should also be added in the logs for troubleshooting purposes in order to monitor those events when needed. Either that or to implement the solution with the before or after events.

**Comment by AlexChanHK** [comment]
Hi guys, just spend some time to read the message above.
I had same case when I tried to edit the system when 3000 just release.
However there is a developer setting in the dashboard of admin panel around version 3012,
what is the different between @danijelGombac suggested code?

**Comment by danijelGombac** [comment]
@AlexChanHK 

The difference is that you don't need to clear the entire cache. You can change the code, refresh the page and changes applied. Then if you disable the auto_reload option, twig load the template from the cashe.

**Comment by danijelGombac** [comment]
The best option is to have both option. Clear entire cache and auto_reload option for single page reload.

**Comment by danielkerr** [comment]
if there is no cache then hosts without eval function installed will not be able to run opencart.

**Comment by straightlight** [comment]
That analogy may not be entirely correct. Since the TWIG engine also allows the use of custom functions, it may be possible to provide alternative solutions than the eval function: https://stackoverflow.com/questions/10671602/whats-alternative-of-eval-function . Besides, OC v3.1.0.0a already provides an event file calling lambda with similar ways as the OC engine already uses the call_user_func_array function which could help users to either use or not use the cache in this case.

**Comment by danielkerr** [comment]
there is no alternative expect caching. 

personally i would manage to make twig system work without caching but dont have time to rewrite twig from scratch.

**Comment by danielkerr** [comment]
im closing this because u can turn caching off on a devlopment server and put it on for the live server. all done on the admin dashboard.
