### ISSUE TITLE
[v3.0.2.0 - Fix] - addGeoZone method

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6054]
A clue has been discovered on that method when users add a new geo zones. Later, they come back and they can no longer find their geo zones. The obvious solution has been posted on the forum: https://forum.opencart.com/viewtopic.php?f=201&t=191792&p=691157#p691157

**Comment by danielkerr** [comment]
problem with this is it allows people to now duplicate the same countries on the same geo zone. this is not how its supposed to work nor does it explain countries being removed from this guys store. 

there is no issue here accept the one this guy probably caused himself. try not to create fixes for imaginary issues.

**Comment by danielkerr** [comment]
he probably is using an old version of opencart where the geo zones took a while to load because to many ajax requests. i altered the system so it does it one by one and can not be saved untill all zones are reloaded.

**Comment by straightlight** [comment]
I was going to suggest an addition in the validate / validateForm method so that users would be more aware of their doing and less ... 'imagining things' while the database ... deletes duplicates entries without administrators consent.

**Comment by straightlight** [comment]
User confirmed it's not a bug on his last post.
