### ISSUE TITLE
[v3.0.2.0 - Fix] - Captcha Extension - Header function

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6059]
Header function being used without the addHeader method. Topic created: https://forum.opencart.com/viewtopic.php?f=201&t=191817#p691176

**Comment by danielkerr** [comment]
im not sure this is a bug. imagejpeg is outputting the image. if it was put into a var then fed into the response output then this would work but the addHeader is not going to output anything as exit is used.

**Comment by straightlight** [comment]
The exit is used with the redirect method from the response library, however. Not from the output method.
