### ISSUE TITLE
[v3.0.2.0 - Fix] - Ebay Extension - Header function without headers_sent

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6060]
Header being used without headers_sent. Topic created: https://forum.opencart.com/viewtopic.php?f=201&t=191818&p=691177#p691177

**Comment by straightlight** [comment]
Just so to add, system/storage/vendor/scss.inc.php and system/storage/vendor/leafo/scssphp/scss.inc.php file may also need the headers_sent() function. Although, I have no idea why these files even exists among Opencart.

**Comment by danielkerr** [comment]
not needed
