### ISSUE TITLE
Extension Modification  missing

### ISSUE THREAD

**Issue by vingoyuan** [opencart/opencart#6064]
i have wrote 2 xml files for some modification of code.   I installed the first one, it was working. but  after i have installed  the second one,   the first modification  in Menu " Modification "  is gone. and didn't work. 

it is

**Comment by vingoyuan** [comment]
in table "modification", the record of first modification is also gone.   i have to copy the record of first modification in table "modification", and insert copy again  after the 2nd modification is installed.

**Comment by danielkerr** [comment]
click the refresh button

**Comment by vingoyuan** [comment]
that's the problem,  i have refreshed,  and still missing.    why the recorde of modification is also deleted. ?   i can only  manually copy the record back to database , then click refresh button ,   then , it works.
