### ISSUE TITLE
Template changes not visible on front-end

### ISSUE THREAD

**Issue by chainboost** [opencart/opencart#6066]
Tried this on both OC 3.0.2.0 and 3.0.2.1b. 

When selecting my custom theme on the back end OC informs me that it has updated succesfully however upon inspecting this on the front end nothing has changed at all. Even when I look into the database at OC_SETTING it stil says that it uses the default template.

**Comment by danielkerr** [comment]
you must have an extension installed thats overriding the setting. works for me and many others
