### ISSUE TITLE
Problems with language files in childs

### ISSUE THREAD

**Issue by stanislavdavid** [opencart/opencart#6068]
Hi, I have found one bug
example - If I have some module in columns which are loaded in controller and when this modules have the same language identifiers, they are not separated and will overwrite existing language definitions.
Example in information/contact.php

         $data['column_left'] = $this->load->controller('common/column_left');
         $data['column_right'] = $this->load->controller('common/column_right');
         $data['content_top'] = $this->load->controller('common/content_top');
         $data['content_bottom'] = $this->load->controller('common/content_bottom');
         $data['footer'] = $this->load->controller('common/footer');
         $data['header'] = $this->load->controller('common/header');

         $this->response->setOutput($this->load->view('information/contact', $data));

Each $this->load->controller will overwrite previously defined language informations.
So I must add again

        $this->load->language('information/contact');

before

        $this->response->setOutput($this->load->view('information/contact', $data));

To get correct language definitions

**Comment by Wolferring** [comment]
Same question

**Comment by danielkerr** [comment]
it uses the event system to backup and then restore the previous controller language definitions.
