### ISSUE TITLE
Twig Templates (catalog): {{ text_empty }} where {{ text_no_results }} belongs

### ISSUE THREAD

**Issue by rmullaney77** [opencart/opencart#6070]
One example (but many instances) of 'text_empty' being used in the wrong place...

https://github.com/opencart/opencart/blob/master/upload/catalog/view/theme/default/template/product/category.twig

```
      {% if not categories and not products %}
      <p>{{ text_empty }}</p>
```

Should be...

```
      {% if not categories and not products %}
      <p>{{ text_no_results }}</p>
```
As far as we can tell, this is the case in **every** front-end twig that displays multiple results.

Note: This is the only issue preventing us from deploying 3.0.2.x stores at this time.

**Comment by rmullaney77** [comment]
This is the only issue keeping us from deploying 3.x stores at this time.

**Comment by straightlight** [comment]
Confirmed. A new topic has been created with all included files that needs to be edited with those statements: https://forum.opencart.com/viewtopic.php?f=201&t=192018

**Comment by danielkerr** [comment]
fine i will sort it tomorrow.

**Comment by danielkerr** [comment]
what are u guys talking about!

if i use text_emapty is says:

You have not made any previous returns!

if i use text_no_results:

No results!

which is better? obversely the first one. are u just complaining about constancy?

**Comment by danielkerr** [comment]
so far only u 2 are complaining about this!

**Comment by rmullaney77** [comment]
Don't know why I even bother reporting valid issues any more. Biggest
problem with OC is the captain...

**Comment by danielkerr** [comment]
its not valid! its not stopping anything from not working!

its your own preference to have a var with a ceritan name even though the pages where i have used no result are different from than page in the catalog.

**Comment by rmullaney77** [comment]
The issue was pointed out, verified, and solution provided. Not wasting my
time continuing this discussion any further. If it's fixed in the master
AFTER I posted it, so be it. If not, I honestly don't care anymore.

**Comment by danielkerr** [comment]
and banned!

no issue! morron~!

**Comment by dmgroom** [comment]
I'm sorry, but this is an issue!  Using opencart 3.0.2.0
The language file /category/language/en-gb/product/category.php file contains the following line:
$_['text_empty']        = 'There are no products to list in this category.';

This text is clearly meant to be displayed on a category page where there are no products.

However the text which gets displayed is "Your shopping cart is empty!" 
![opecartwording](https://user-images.githubusercontent.com/9418815/38504309-43406328-3c0c-11e8-8250-e1c23b08e54a.png)


 This is not the right text to display.

**Comment by PlusA2M** [comment]
Hi, same issues here, everywhere used {{ text_empty }} would become 'Your shopping cart is empty!' rather than the suitable text from the language file from that page. Until I delete `$this->load->language('common/cart');` in catalog/controller/common/cart.php, the problem won't resolve.

**Comment by danielkerr** [comment]
iits already been fixed in the master. uit requires an event adding. 

	'view/*/before' => array(
		500  => 'event/theme/override',
		998  => 'event/language',
		1000 => 'event/theme'
	),

check the latest file and ask int he forums.

**Comment by PlusA2M** [comment]
I got this fixed! Just comment out the following at system/config/catalog.php
```
	'view/*/before' => array(
		1000  => 'event/debug/before'
	),
	'controller/*/after'  => array(
		'event/debug/after'
	)
```
