### ISSUE TITLE
Marketplace API won't save credentials, marketplace won't load anything

### ISSUE THREAD

**Issue by TBFdirect** [opencart/opencart#6071]
Can't see anyone else having this issue?
tried installing 3.0.0.0 and 3.0.2.0 fresh, tried IE and chrome
entered the API username and API secret key, it says saved. if i go back in both fields are blank
the marketplace page won't show any extensions either, just doesn't seem to be communicating

**Comment by straightlight** [comment]
Hi, a solution has been posted on the Opencart forum: https://forum.opencart.com/viewtopic.php?f=201&t=191942#p691670

**Comment by danielkerr** [comment]
"it says saved. if i go back in both fields are blank"

of course it does not show your api key! do u want some one to steal it!

**Comment by TBFdirect** [comment]
thanks, will give the fix a try

**Comment by straightlight** [comment]
@TBFdirect: No problem.
