### ISSUE TITLE
[v3.0.2.0 - Concept] - All files containing manual width and height settings

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6072]
A new topic has been created regarding the manual width and height settings defined with the resize function: https://forum.opencart.com/viewtopic.php?f=24&t=192021&p=691783#p691783

**Comment by danielkerr** [comment]
any new theme that is created should have this functionality already.

**Comment by straightlight** [comment]
Although, under the admin-end to view the thumbnails and images, the width and height are still defined manually through the controllers. Users are looking for to use the same width and height as the ones from the product's store-front end which is already possible.
