### ISSUE TITLE
V 3.0.2.0 install or upload OCMOD error 

### ISSUE THREAD

**Issue by laszkris** [opencart/opencart#6075]
Hello guys!
I"m used the  2.3 version and older but now i installed same server he 3.0.2.0 version of OC,
Is I try install or just upload any OCMOD zip or xml I got an error message like this:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
OK
<b>Warning</b>: Invalid argument supplied for foreach() in <b>/var/www/data1/S5-053/piac/parna/xxxxxxx.hu/admin/controller/marketplace/installer.php</b> on line <b>95</b>{"text":"Installing","next":"http:\/\/xxxxxxx.hu\/admin\/index.php?route=marketplace\/install\/install&user_token=yswS6xQqwkGPGY611mUiVEql5p8NMnUZ&extension_install_id=2"}

The hosting provider say the curl or other server module workinhg fine.
I"m looking any solution  but i nothing fount until this time :(
The folders permission is ok.
I hope anybody can help me here.
Thanks
Laszkris

**Comment by danielkerr** [comment]
u n3eed to ask in the forums. this is for the master branch.
