### ISSUE TITLE
Problem with Alert Email

### ISSUE THREAD

**Issue by sheldmandu** [opencart/opencart#6079]
Using 2.3.0.2. Settings > Store > Mail > Additional Alert Mail values don't persist.  Looking at the code where this is used the key in the setting table in the DB is config_mail_alert_email, but in code config_alert_email is used throughout and hence doesn't work.

**Comment by danielkerr** [comment]
so thats why it was fixed int he latest version

**Comment by zemguru** [comment]
Dublicated here: #4850 
Check solution there, please.
