### ISSUE TITLE
field `date_modified` missing in table `oc_customer`

### ISSUE THREAD

**Issue by bingzheyuan** [opencart/opencart#6083]
Please check table `oc_customer` https://github.com/opencart/opencart/blob/master/upload/install/opencart.sql#L984
There's no field `date_modified`, however in upgrade script 1010, you are trying to modify data type of this field. https://github.com/opencart/opencart/blob/master/upload/install/model/upgrade/1010.php#L268
I think you miss the field in sql file.

**Comment by bingzheyuan** [comment]
- same issue for table `oc_customer_activity`
- same issue but due to table `oc_fraud_ip` doesn't exist
- table `oc_return` has no `date_end`

**Comment by danielkerr** [comment]
its not missing! you need to request it!

also its not needed for the other tables!

**Comment by danielkerr** [comment]
ahh ok i see what u mean.

cheers for checking
