### ISSUE TITLE
[v3.0.2.0 - Concept] - Frequencies array from checkout cart controller

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6084]
A new topic on the forum has been created in order to move the frequencies array: https://forum.opencart.com/viewtopic.php?f=24&t=194053#p694041

**Comment by AlexChanHK** [comment]
Nice suggestion, maybe you can compare the time different and commit the edition to the master version,
then the manager to take  a look to see if they agree to merge to the system.
Since it is not bug or issue, I think **this issue can be closed.**

**Comment by Felix-Ho** [comment]
@straightlight Thanks for your great suggestion.
I have commit the update to the master branch.
https://github.com/opencart/opencart/commit/900b77c0db2e5d7b0e68f39cb9d12e1fe6afcbf4

let's close this issue topic
