### ISSUE TITLE
install/model/upgrade/1010.php

### ISSUE THREAD

**Issue by AcacioDuarte** [opencart/opencart#6088]
line 242 to 245  is =  line 246 to 249 ( $tables['api'] )
line 276 to 279  is =  line 280 to 283 ( $tables['customer_login'] )

in $tables['customer'] line 268 'date_modified' does not exist in the database
in $tables['customer_activity'] line 272 'date_modified' does not exist in the database

database marketing_report in line 2012  `date_added`
database order_recurring  in line 2351  `date_added`
database  order_recurring_transaction in line 2368  `date_added`

in  $tables['return'] line 324 'date_end' does not exist in the database but `date_modified`

I hope I have helped
for a good job
Acácio Duarte

**Comment by danielkerr** [comment]
its been removed already
