### ISSUE TITLE
[v3.0.2.0 - Concept] - All date_added without date_modified field

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6090]
A new topic has been created on the forum regarding the date_modified missing on most (if not all) models along with the date_added field: https://forum.opencart.com/viewtopic.php?f=24&t=194405 . This issue has already been addressed on Github earlier this week, However, the list of files regarding this issue may greatly help for the future version of Opencart.

**Comment by danielkerr** [comment]
not required for most of them. revise the list!
