### ISSUE TITLE
Error with latest/beta build (SQL Syntax Errors in install/model/upgrade/1010.php) when upgrading

### ISSUE THREAD

**Issue by Pelham81** [opencart/opencart#6091]
I downloaded the latest build this morning (10/14/2017 EST time) to test changes (over the last build from ten days ago). During the install upgrade process I received the following error:

```
Error Code(0): Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'VARCHAR(60) NOT NULL' at line 1
Error No: 1064
ALTER TABLE `oc_address` CHANGE `payment_company` VARCHAR(60) NOT NULL in C:\xampp\htdocs\main\system\library\db\mysqli.php on line 40
```
See attached screenshot.

![screenshot 2017-10-14 11 36 49](https://user-images.githubusercontent.com/30006048/31577076-151d900e-b0d6-11e7-8e56-60414219267a.png)

**Comment by Pelham81** [comment]
Actually, now that I am looking at this more closely, somehow there is a conflict with "payment_company" trying to be added in the table perhaps when meanwhile the table uses "company"? Could this be it?

**Comment by danielkerr** [comment]
already been fixed

**Comment by danielkerr** [comment]
thx for testing
