### ISSUE TITLE
[v3.0.2.0 - Fix] - admin/model/extension/openbay/ebay.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6095]
A new topic has been created regarding this issue: https://forum.opencart.com/viewtopic.php?f=201&t=194419

**Comment by straightlight** [comment]
This portion as well would need to be fixed: http://forum.opencart.com/viewtopic.php?f=201&t=194419&sid=06b6ad9d5369ac0d72bfd7917441bcd2

**Comment by danielkerr** [comment]
'" .(int)$id . "'

i think this might not be an integer

**Comment by straightlight** [comment]
If not then why is the product_id field an integer?
