### ISSUE TITLE
[v3.0.2.0 - Fix] - [v3.0.2.0 - Fix] - INSERT / REPLACE INTO with WHERE Clause 

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6100]
A new topic has been created on the forum regarding this issue: https://forum.opencart.com/viewtopic.php?f=201&t=194425&p=694581#p694581

**Comment by danielkerr** [comment]
i have fixed the maxmind one but can not find any other instances using mass search

**Comment by straightlight** [comment]
I don't know the type of search you're using but it sure ain't the same one that I use. Look again for the amazon_login_pay payment module to the indicated path on the forum since I just look from your github files and I can already see it there without re-using the search on this one.
