### ISSUE TITLE
[v3.0.2.0 - Fix] - code SQL field 

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6101]
A new topic on the forum has been created regarding this issue: http://forum.opencart.com/viewtopic.php?f=201&t=194424

**Comment by danielkerr** [comment]
good one!

**Comment by danielkerr** [comment]
ok just checked. they all have `code`.  there is no missing `

**Comment by stalker780** [comment]
@straightlight 
I will ask again. Why don't you use pull request with changed files? You are wasting a lot of people time to read and check those changes on forum then comparing master branch with your comment.

That's what github was designed for.

And making a commit you will see yourself if this bug really exist in master branch.

You post too many false bugs! And over 3000 subscribed people have to read this. Is it a sort of trolling? :)

**Comment by zemguru** [comment]
The question is not about missing ``` ` ```, but about [MySQL `keywords` and `reserved words` ](https://dev.mysql.com/doc/refman/5.7/en/keywords.html).

`code` is a keyword, not a reserved word @straightlight 
So, it's not forbidden to use it un-quoted.

**Comment by straightlight** [comment]
It appears I looked at the wrong row which (R) was right underneath the code row. However, followed are the reserved words list provided by StackOverFlow that we need to be aware of: https://stackoverflow.com/questions/23446377/syntax-error-due-to-using-a-reserved-word-as-a-table-or-column-name-in-mysql , including the official mySQLi chart when querying the database.

Thanks for the information.

The most generated errors being found on Opencart forum originates from contributed programming.

**Comment by danielkerr** [comment]
@stalker780 i donmt mind. some of his issues are not issues so i prefer to check myself.
