### ISSUE TITLE
Errors when adding or editing product options on latest beta build (lots of undefined indexes)

### ISSUE THREAD

**Issue by Pelham81** [opencart/opencart#6105]
I had this problem after upgrading the test install this morning and I also the same problems on a fresh install (decided to test out both due to all the new tables and changes to existing ones) to check out the new product option changes to the build. The tables being used are missing the components being called.

I'm attaching sceenshots

This one is what happens after trying to add a new option for a product
![screenshot 2017-10-15 14 08 37](https://user-images.githubusercontent.com/30006048/31587664-836b7eee-b1b3-11e7-881c-724d15edf4c3.png)

This one is what happens when trying to edit one of the existing options
![screenshot 2017-10-15 14 11 06](https://user-images.githubusercontent.com/30006048/31587673-9599cb0c-b1b3-11e7-88d9-489e2f666aa8.png)

**Comment by danielkerr** [comment]
thx for testing!

**Comment by danielkerr** [comment]
i have updated product options and moved it to its own page. just fix any issues for having to many product options.
