### ISSUE TITLE
Fresh Install of Opencart 3.0.2.0 - Have Glitches With Mail

### ISSUE THREAD

**Issue by Davey81** [opencart/opencart#6106]
Hello all, I have a fresh install of Opencart 3.0.2.0

I have tested it and the store mostly appears to work fine, I have started to collect customer orders already but I'm having a problem that mail sent through the Contact Us page doesn't get received by myself. After the customer (or myself when I tested it) clicks submit, they are redirected to a blank page with with no confirmation the message was sent. No message will be received in my inbox.

The next issue is that when a customer purchases an item through the website, neither the customer or myself receives an email notification of the order. The only mail received is a PayPal receipt to the customer and an email to myself from PayPal for money received into my PayPal account.

I checked the Newsletter function and that appears to work okay.

I have double checked the settings found at system > settings > mail and all appears to be correct.

Apart from the above issues the store works perfect. I have no theme installed (just the default one for now) and only have two extensions which I deleted (but re-added) to check if they may cause a mail error.

There is nothing registered in the error log and the error log is enabled.

Any help or advice would be greatly appreciated.

**Comment by danielkerr** [comment]
please dont post support questions here.

1. display errors is not switched on on your server. most likley there is an eror because the mails not going out.

try using smtp and a gmail account.
