### ISSUE TITLE
Opencart www state lose some icon

### ISSUE THREAD

**Issue by SibylZ** [opencart/opencart#6107]
How to solve this problem?

**Comment by CoverUp** [comment]
Not an issue, your server need to be well config.
match your URL with the URL in config.php
if you set example.com, then your CSS will fail if you visit www.example.com (hence you lose some icons)
and viceversa.
Best aproach is use www.yourdomain.tld and make a redirect if someone put yourdomain.tld
You can find this info in the forums, this is not the place for this.
but im in good mod today and I answer you before this will be closed with no reason. (as stated in rules)
