### ISSUE TITLE
upload problems "Directory does not Exist" localhost

### ISSUE THREAD

**Issue by Sebaortiz** [opencart/opencart#6108]
I have installed opencart on localhost with xampp to try but when upload an image appear this error **"Warning: Directory does not exist"**. I checked the 2 files "config.php" and "admin/config.php" and everything is in order "define('DIR_STORAGE', 'C:/xampp/htdocs/storage/');" and "define('DIR_IMAGE', 'C:/xampp/htdocs/opencart/image/');"  What can be the solution?

**Comment by Pelham81** [comment]
Just to be clear, you created a folder in htdocs of xampp (let's say "test") and then put all the files in there? Then when you went to localhost/test/install you had this issue? See attached screenshot
![screenshot 2017-10-17 01 13 45](https://user-images.githubusercontent.com/30006048/31647870-b965e072-b2d8-11e7-8989-9aab027a2b56.png)

For example, my folder is named "main" and then all the opencart folders/files are in there.

I suspect you simply didn't include your folders properly in all honesty, and this is not an actual OC issue.

**Comment by straightlight** [comment]
I had similar experience when first installed OC v3.x . In the admin dashboard, when prompted to move the storage folder, simply don't move it. I noticed then that the issues were resolved regarding the storage folder.

**Comment by Sebaortiz** [comment]
I understand, and there is no solution without having to reinstall Open Cart?

**Comment by straightlight** [comment]
There is no need to reinstall Opencart for this issue. Simply edit your config.php and admin/config.php file and set the DIR_STORAGE to its previous path. This should resolved the problem other than seeing this annoying modal when entering the Opencart admin section. Just close the modal each times until this issue gets resolved definitely.

**Comment by Sebaortiz** [comment]
the previous path does not remember, try adding another path , but it did not work

**Comment by martvent** [comment]
it is due to a custom storage location, first, edit config.php correct the dir location, go to file manager system/storage copy all file to a custom location, for more info. developer@martvent.com
