### ISSUE TITLE
Format price without currency conversion

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#6109]
Currently, there's no way to format a number without currency conversion taking place. 

Suggested change below that would still be backwards compatible. This way you can pass null as the third param for only number formatting.
`$price = $this->currency->format($order_total['total'], $order_total['currency_code'], null);`

```php
public function format($number, $currency, $value = '', $format = true) {
	$symbol_left = $this->currencies[$currency]['symbol_left'];
	$symbol_right = $this->currencies[$currency]['symbol_right'];
	$decimal_place = $this->currencies[$currency]['decimal_place'];

	if (!$value && $value !== null) {
		$value = $this->currencies[$currency]['value'];
	}

	$amount = $value ? (float)$number * $value : (float)$number;
```

**Comment by zemguru** [comment]
Isn't that already?

https://github.com/opencart/opencart/blob/master/upload/system/library/cart/currency.php#L24

**Comment by OpenCartAddons** [comment]
Correct.  Simply set the last variable `$format` to false.

Example:
`$this->currency->format($value, $currency_code, '', false);`
