### ISSUE TITLE
[v3.0.2.0 - Bug] - admin/controller/tool/upload.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6111]
In this file, from the upload() method, the language library is loading sale/order from the uploads ... already a bit odd as I cannot find other relative key names than the error_permission key which should rather be captured from the tool/upload language ... since I cannot find error_filename in either of files unless the error_filetype was rather need to be referred. It may not be an invalid import for the sale/order language but I presume the tool/upload language would need to be loaded as well but the error_permission must be properly handled so that both imported languages does not confront one-another. The error_upload key could not be found in either of those 'may be' needed languages ...

**Comment by AlexChanHK** [comment]
Yes, there are no language object to correspond the upload  controller in the admin panel.
However, seem there are not function directly related to it and user can't upload any file in that page.
(the page only used to check if user upload some thing for the option of the product.)
Therefore it should exist any issue.

This issue can be closed.
