### ISSUE TITLE
[v3.0.2.0 - Fix] - Email events

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6115]
A working solution has been posted on the forum by another user regarding the email events issues encountered by several users: https://forum.opencart.com/viewtopic.php?f=199&t=186236&hilit=gmail+tls&start=20#p681739 . Of course, the `event` table would need to be changed to the `oc_event` name in the SQL file.

**Comment by danielkerr** [comment]
it already is oc)event in the oc install.

**Comment by straightlight** [comment]
Yes. Although, the rest of the instructions on that post still needs to be implemented in case slight changes may have been applied. People seem to confirm, since this posted solution, that it is working as intended.

**Comment by danielkerr** [comment]
im not sure how this fixes anything:

"PRIMARY KEY (`event_id`)" to "PRIMARY KEY (`oc_event_id`)"

all its doing is trying to add a non existint primary key.

**Comment by danielkerr** [comment]
i see. EVENT is a reserved word i think.

https://dev.mysql.com/doc/refman/5.7/en/create-event.html

needs 'event' maybe

**Comment by straightlight** [comment]
Exactly and along with the rest of the SQL paragraph to be replaced in case.

**Comment by straightlight** [comment]
As for the sensitive case of EVENT and event, this methodology would not be considered with Windows servers. Both cases would be reserved terms in this case.

**Comment by straightlight** [comment]
User beerlim has confirmed that the correction of the event query has fixed the issue with GoDaddy hosting inclusively. There has been cumulative reports regarding partial email sending but other pages that would not actually send those emails.

**Comment by hollisterca** [comment]
Whoever found this. super.
Yes I upgraded from 2.x to 3.x
My table names do not have a prefix (so its events) and the table structure was correct and there but no records.

**Comment by danielkerr** [comment]
oc_event_id will do nothing! its key not a table name.

**Comment by hollisterca** [comment]
Here the event table structure after upgrading from 2.x to 3.x
see attachment. I see also "The column name 'trigger' is a MySQL reserved keyword."
![event-table-db](https://user-images.githubusercontent.com/23412806/31735337-e712b012-b441-11e7-8c9b-a14ef9d8211d.jpeg)
All I did is do the insert statements, I did not drop the event table and recreate it.
Emails do work at this point.

**Comment by straightlight** [comment]
hollisterca's analysis is correct. I have helped another user today regarding this issue. I had to manually re-insert the values into the database. The issue was, then, rectified. It is a confirmed bug.

**Comment by danielkerr** [comment]
should be fixed now. it was just a matter of missing quotes.

**Comment by danielkerr** [comment]
let me know if its not fixed int he master.
