### ISSUE TITLE
[v3.0.2.0 - Bug] admin/controller/common/filemanager.php

### ISSUE THREAD

**Issue by seitbekir** [opencart/opencart#6121]
I've tried to upload file from Image manager, but got `Warning: Directory does not exist!` alert on the page. It was strange, because all right set correct, user and group has all privileges. I've investigates issue.

There is issue on line 200.
Actually, when checking it cut last slash (`/`) from folder name, because following [this page](http://php.net/manual/ru/function.realpath.php) the folder names returns clear, without slash in the end, so the substr need string wider then it is possible. That's why you can just remove slash from right side of the expression:
```php
// Check its a directory
if (!is_dir($directory) || substr(str_replace('\\', '/', realpath($directory)), 0, strlen(DIR_IMAGE . 'catalog')) != str_replace('\\', '/', DIR_IMAGE . 'catalog')) {
    $json['error'] = $this->language->get('error_directory');
}
```

PS: also, I recommend, check if this code repeating somewhere to avoid same situation. I found that many people has this issue in

**Comment by charlzzf** [comment]
I had the same issue in Version 3.0.2.0 and seitbekir's fix resolved it.

**Comment by AlexChanHK** [comment]
Hi seitbekir, charlzzf
Can I have some example to see how and when the error will happened?
as I had tried to update some image will new installation 3.0.2.0,
but not Warning: Directory does not exist! existed.

Also, the Daniel had update that controller in 6 Oct, seem include the row also.
https://github.com/opencart/opencart/commit/60e47c0e5e99236dd334cfd02dad92f5a192b3b7#diff-c70c23de40e6a855caf38dc256c169c8
