### ISSUE TITLE
[v3.0.2.0 - Concept] - Most unsanitized files

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6123]
A topic has been created to demonstrate how many files uses unsanitized values: https://forum.opencart.com/viewtopic.php?f=24&t=198854&p=699729#p699728

**Comment by lucasjkr** [comment]
What do you mean? I didn't look at all the files you referenced, but $result is coming from the database - and was likely sanitized when it was being written into the DB. Show examples of that not occurring, and that would be issues to jump on.

**Comment by straightlight** [comment]
That theory may be correct. Although, it still does not explain on the rest of the files I just posted regarding the use of sanitizing (which is fine on these ones) compared to those that have not been sanitized even though, both and most of the comparison, originates from the database.

**Comment by lucasjkr** [comment]
Can you be more specific what you're seeing? Rather than "the rest of the files"?

**Comment by straightlight** [comment]
I added another post on the forum topic indicated on the first post.

**Comment by AlexChanHK** [comment]
Agree with @lucasjkr, not sure what issue is @straightlight talking about,
can we have some example and detail to know what is the issue when using $result?
