### ISSUE TITLE
Twig caching issue

### ISSUE THREAD

**Issue by advertikon** [opencart/opencart#6126]
Code at line 18 of /system/libraty/tempalte/twig.php need to be changed from:
if ($cache) {
     $config['cache'] = DIR_CACHE;
}
to:
if ($cache) {
     $config['cache'] = DIR_CACHE;
      $config['auto_reload'] = true;
}
in this case Twig will re-render the template each time it modifies, otherwise Twig will constantly use cached version. Since $cache option precoded in config.php and there is no UI to change it will be a problem to support modules

**Comment by straightlight** [comment]
The path is: system/library/template/twig.php

**Comment by advertikon** [comment]
Yes, file is system/library/template/twig.php but line is 25 (sorry, my bad
![selection_018](https://user-images.githubusercontent.com/14218158/31874298-2d4bcf9a-b7d1-11e7-9820-9e431d38ed0d.png)
)

**Comment by howdu** [comment]
You can clear the cache from the dashboard. 

Might be worth doing some benchmark tests see how much it affects performance but the [docs](https://twig.symfony.com/doc/2.x/api.html) say `auto_reload` should only be used when developing.

> When developing with Twig, it's useful to recompile the template whenever the source code changes. If you don't provide a value for the auto_reload option, it will be determined automatically based on the debug value.

**Comment by advertikon** [comment]
My bad, I did not notice this new feature. Sure it's better to flush (enable/disable) the cache manually.

**Comment by stalker780** [comment]
Actually I've pushed a commit that will refresh twig/sass cache on modifications refresh. 
 #6124
It is a solution for modules installation. But seems Daniel have not reached it yet.

**Comment by advertikon** [comment]
This commit will greatly reduce support requests :)
