### ISSUE TITLE
error admin panel

### ISSUE THREAD

**Issue by Derewith** [opencart/opencart#6130]
Since i moved from www/sito to www i tried to edit the same admin/config.php and config.php but now the admin/config.php is not working anymore and gave me this error 

`
Fatal error: require_once(): Failed opening required '/system/startup.php' (include_path='.:/usr/local/php70/pear') in /home/highsoc1/public_html/admin/index.php on line 17`

What can i do ?

**Comment by straightlight** [comment]
Either your config.php and admin/config.php file contains improperly configured relative paths or you are missing uploaded files from your last transfer. Not a bug with Opencart.
