### ISSUE TITLE
Switching Language Problem!!

### ISSUE THREAD

**Issue by Mona-Abdelkader** [opencart/opencart#6132]
Hi,

Please I'm working on OpenCart Version 2.3.0.2, and I've two languages installed in my website, English (the default one) and Arabic. When I try to switch the language from Mozilla nothing happens, but when using the guest browser it's working properly. On chrome I can switch the language for only one time and after that nothing happens even in the private browser!!

How could I solve this problem?
Thanks in advance

Mona Abdelkader

**Comment by straightlight** [comment]
Opencart v2.x are older releases which OC v3.x releases already contains the bug fixes about. Simply look in the code tab of this page and you will see most recent bug fixes. In the catalog/controller/common of this page, you will notice the language.php file date that is more recent than the OC v2.x's date releases.

**Comment by danielkerr** [comment]
because its saving as a cookie. no bug!
