### ISSUE TITLE
[v3.0.2.0 - Fix] - Catalog Extension Payment modules

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6135]
Followed are the list of files using callback() methods but also using the echo command:

catalog/controller/extension/payment/alipay.php
catalog/controller/extension/payment/alipay_cross.php
catalog/controller/extension/payment/pilibaba.php
catalog/controller/extension/payment/sagepay_server.php
catalog/controller/extension/payment/twocheckout.php

While the customer is shopping and might see a failed payment, it would rather be suggested to use templates or JSON response.

**Comment by jamesallsup** [comment]
As these are the callback urls for the gateway into OpenCart, you can't just use json if the gateway is expecting plain text like "OK" (or any other string). Its a rancid / cringing way of doing it I know, its just a dated way of how it was done using a simple string check and header code (usually)
