### ISSUE TITLE
[v3.0.2.0 - Fix] - admin/model/extension/report/activity.php file 

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6136]
A new topic on the forum has been created on this issue: https://forum.opencart.com/viewtopic.php?f=201&t=199004#p700443

**Comment by AlexChanHK** [comment]
Yes, the table is not exist any more, 
but seem also the no controller a using this model anymore,
therefore it should not exist any error due to the problem.

This can be closed.
