### ISSUE TITLE
opencart3.0.2.0 Tax bug

### ISSUE THREAD

**Issue by mengwb** [opencart/opencart#6137]
Admin setting
Display Prices With Tax: Yes;
Taxes module of order total: install and enable;
Product Tax Class: Taxable Goods;

On the settings as over, checkout with the address UK VAT Zone. 
And then, the checkout page as follow:(product price show with tax, and total show without tax )

Product Name | Model | Quantity | Unit Price | Total
-- | -- | -- | -- | --
Canon EOS 5D   - Select: Red | Product 3 | 2 | $98.00 | $196.00
iPhone | product 11 | 2 | $123.20 | $246.40
 |  |  |  | Sub-Total: | $362.00
 |  |  |  | Flat Shipping Rate: | $5.00
 |  |  |  | Total: | $367.00

**Comment by zemguru** [comment]
go to System > Localization > Geo Zones,
Edit "UK VAT Zone", and remove all zones by regioin,
Select Country "United Kingdom" and set Zone to "All Zones"

tax in cart appeared. 

Is it bug @danielkerr  ?

**Comment by straightlight** [comment]
Have you cleared all caches to reflect the changes?

**Comment by zemguru** [comment]
what changes exactly?
On the default OC master installation, there is NO TAX displayed, 

but if you make this:

~~~
go to System > Localization > Geo Zones,
Edit "UK VAT Zone", and remove all zones by regioin,
Select Country "United Kingdom" and set Zone to "All Zones"
~~~

then tax appears.
