### ISSUE TITLE
[v3.0.2.0 - Fix] - Gift Certificate total module

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6138]
A fix has been posted on the forum to rectify the problem: https://forum.opencart.com/viewtopic.php?f=202&t=198804#p700549

**Comment by lucasjkr** [comment]
If these are really bugs and you're really finding fixes, why aren't you making pull requests?

**Comment by osworx** [comment]
It becomes a waste of times to follow straightlight's posts.
Only filling my mailbox with nonsens!
While it maybe nice what you are doing @straightlight , but either make pull requests or post in the forum.
But **NOT** both.

**Comment by straightlight** [comment]
No problem. Since I have been encouraged to post back on the forum based on most official bugs, this is what I'll do. Thanks! :)

**Comment by AlexChanHK** [comment]
Seem it was fixed in the latest version already. Can be close.
![issue1](https://user-images.githubusercontent.com/26454451/33260313-67e01b9a-d39a-11e7-9bc5-c221ca0abaa1.jpg)
