### ISSUE TITLE
Opencart 3.0.2.0 (rs. 1) emails not sending

### ISSUE THREAD

**Issue by opv88** [opencart/opencart#6150]
All email messages not sending (register, forgot password, new order etc.). I cant find code for sending mail on calling this methods in controller.
Opencart version: 3.0.2.0 (rs. 1)
Email settings is correct, because sending mail manually worked correctly. For example, I put code for send mail in checkout/order model (using mail settings from admin panel)
`$mail = new Mail();`
`$mail->protocol = $this->config->get('config_mail_engine');`
`$mail->parameter = $this->config->get('config_mail_parameter');`
`$mail->hostname = $this->config->get('config_smtp_host');`
`$mail->username = $this->config->get('config_smtp_username');`
`$mail->password = $this->config->get('config_smtp_password');`
`$mail->port = $this->config->get('config_smtp_port');`
`$mail->timeout = $this->config->get('config_smtp_timeout');`
`$mail->setTo($this->config->get('config_email'));`
`$mail->setFrom($this->config->get('config_email'));`
`$mail->setSender($order_info['store_name']);`
`$mail->setSubject(html_entity_decode($subject, ENT_QUOTES, 'UTF-8'));`
`$mail->setText(html_entity_decode($text, ENT_QUOTES, 'UTF-8'));`
`$mail->send();`
And I get email message correctly.

Email settings below.
<img src="https://monosnap.com/file/xUKQZBmBobsQ8xm1MrT57PkdaW2RPY.png"></img>

**Comment by ravilrrr** [comment]
Закройте issue.  Все работает по умолчанию. Проблема у вас, тут никто не будет разбираться с вашей проблемой. Есть форумы, есть инструкции по вычислению ошибки, итд. Не нужно засорять гит не подтвержденными ошибками.
