### ISSUE TITLE
Table `oc_shipping_courier`

### ISSUE THREAD

**Issue by DariyGRAY** [opencart/opencart#6151]
What is the `oc_shipping_courier` table for?

![table](https://user-images.githubusercontent.com/9871980/32167540-d353f7b4-bd71-11e7-88d1-a08db72514ea.jpg)

**Comment by Felix-Ho** [comment]
@DariyGRAY Thanks for the commented.
The shipping_courier table is not using at the latest version of opencart system yet but it will using it later.
