### ISSUE TITLE
Is there an accurate list of which payment methods ACTUALLY work?

### ISSUE THREAD

**Issue by lucasjkr** [opencart/opencart#6152]
I've been going through the models recently, and seeing a lot of things that make me think that at least SOME of the methods in them are broken. Makes me think that either:

1 -  people aren't using them at all

2 - they're just not using some methods within those models

3 - they've devised workarounds and haven't shared them back upstream.

For instance, on the admin side, most of the models in `/upload/admin/model/extension/payment/` have methods like `getTotalRebated` or `getTotalRefunded` with queries like:

    `SELECT SUM(`amount`) AS `total` FROM `" . DB_PREFIX . "bluepay_hosted_order_transaction` WHERE `bluepay_hosted_order_id` = '" . (int)$bluepay_hosted_order_id . "' AND 'rebate'`

Where i think the query should be:

    SELECT SUM(`amount`) AS `total` FROM `" . DB_PREFIX . "bluepay_hosted_order_transaction` WHERE `bluepay_hosted_order_id` = '" . (int)$bluepay_hosted_order_id . "' AND type = 'rebate'

In `/upload/admin/model/extension/payment/pp_express.php`, in the `addTransaction()` method, it looks like the queries are occurring in the wrong order - you're trying to update the the `calldata` column before you've gotten the ID of the row you want to update. At the very least, the insert query should occur first, then the Update. Or if could be refactored into a single query.

On the catalog side, you've got one payment method stored in `catalog/model/extension/credit_card`, and the rest are are in `payment`.

Unfortunately, for me it's difficult to actually test most of these, as I don't have API Keys for most of the methods, but i do have time to do the fixes at least as it appears they should be done. But before doing anything, I thought I would ask @danielkerr to make sure everyones time wouldn't be wasted

**Comment by danielkerr** [comment]
we are contacting the gateways one by one to setup a yearly maintenance contract.
