### ISSUE TITLE
[OC 3.0.2.x] Reward points - Option points not considered

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6154]
**Situation**: Product has reward points e.g. 200
Option 1: +10
Option 2: ... (screenshot appended)
![product-reward-option-points](https://user-images.githubusercontent.com/10166095/32223175-620ed920-be4d-11e7-9922-d6dd895a31cf.png)

**Problem**: The reward points of the options are not getting calculated with the product reward points. All options have the basic reward points 200 (see screenshot)
![shopping-cart-reward-option-points](https://user-images.githubusercontent.com/10166095/32223192-73e68d50-be4d-11e7-8add-1c10bed94a05.png)

**Comment by danielkerr** [comment]
its for purchasing the product with reward points!

**Comment by pemaier** [comment]
That's what I understood. Here the sample description: 

Status: Customer has 1000 points on his account
The product has a amount of points(-price) (in this sample 200) 
additional the option has a point(-price) (in this sample for each colour a different - green +30 points)
So the sum to purchase the product and the option it is necessary to calculate the point(-price) like product points + option points (option points can be plus or minus)

Canon EOS 5G cost 200 points + Option Green +30 points = 230 points (to pay)
On the cart view customer can decide to pay with points. In this sample the calculation say he has to pay 200 instead of 230

Or do I misunderstand the situation?

**Comment by hemantkumar469** [comment]
I have got the same issue
please resolve this issue...
![untitled](https://user-images.githubusercontent.com/40543018/41820495-5bc11fe4-77f0-11e8-900f-754dd0f3b4d5.jpg)

**Comment by vivek-webkul** [comment]
Pulled for reward points added on cart page. #6845
