### ISSUE TITLE
Checkout Issue

### ISSUE THREAD

**Issue by CokkocZateki** [opencart/opencart#6155]
Hi

Having an issue with the checkout of my store.

PHP Version: PHP 7.0.25-1
OS: Ubuntu 14.04
Apache
Opencart Version: 2.3.0.3_rc

```css
PHP Fatal error:  Uncaught exception 'Exception' with message 'Error: Password not accepted from server!' in /var/www/opencart/upload/system/library/mail.php:286\nStack trace:\n#0 /var/www/opencart/upload/catalog/model/account/customer.php(55): Mail->send()\n#1 [internal function]: ModelAccountCustomer->addCustomer(Array)\n#2 /var/www/opencart/upload/system/storage/modification/system/engine/loader.php(178): call_user_func_array(Array, Array)\n#3 [internal function]: Loader->{closure}(Array, Array)\n#4 /var/www/opencart/upload/system/engine/proxy.php(25): call_user_func_array(Object(Closure), Array)\n#5 /var/www/opencart/upload/catalog/controller/checkout/register.php(234): Proxy->__call('addCustomer', Array)\n#6 /var/www/opencart/upload/catalog/controller/checkout/register.php(234): Proxy->addCustomer(Array)\n#7 [internal function]: ControllerCheckoutRegister->save()\n#8 /var/www/opencart/upload/system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array)\n#9 /var/www/opencart/upload/catalog/controller/st in /var/www/opencart/upload/system/library/mail.php on line 286, 
```

I also have the below mods to hide address and contact number etc which doesnt seem to work when i guest checks out and creates and account. It will work when a client registers first and then purchases the items. But do it backwards and it asks for contact number, address etc. Nothing in the logs show that there is an issue

![image](https://user-images.githubusercontent.com/16074209/32232797-26fe06b0-be59-11e7-82f0-ff72a36b14fc.png)

**Comment by ADDCreative** [comment]
`Error: Password not accepted from server!` tells you your email server is not accepting the SMTP password you have set in the settings.

Since 2.3.0.3_rc has never been release there is no guarantee the modifications will work. You are best to ask the authors of the modifications of in the forums.

**Comment by CokkocZateki** [comment]
Hi @ADDCreative 

thank you for the feedback. Just noticing a couple more things that seem to have issues. a sale gets finalised and error 500 and nothing in the log. :(

the mods worked perfectly last week and out of the blue it just went sideways fast
