### ISSUE TITLE
Paypal Express Checkout

### ISSUE THREAD

**Issue by stefanleenheer** [opencart/opencart#6157]
This is OC 2.1.0.1
I needed to switch from normal Paypal to Express Checkout because of legal issues.
I use the integrated Paypal Express from OC.
All other payment options work well.

When giving a discount on a purchase if someone has applied for the newsletter following is happening:

Up until the order and checkout page all is calculated correctly.
When submitting to Paypal, instead of giving the order total from store checkout, it suddenly adds the discount to the total, disregarding the previous amount.

example:
order product X of 100 Usd gives 5% discount if subscribed to newsletter..
this is stated in checkout and total sum on checkout is **100-5=95 Usd**
When using all other payments this is correctly parsed to the payment provider.
If paying with Paypal express total shown (to pay in Paypal acount): **100+5=105 Usd**

This is a big issue, ass most of my customers pay with Paypal.

**Comment by PhamToan** [comment]
@stefanleenheer  you can contact to my team Sales@mmosolution.com

We will fix for you with some fee

**Comment by Felix-Ho** [comment]
@stefanleenheer the default opencart system did not built-in this subscribe discount feature.
Have you install any extension to adding it?

**Comment by stefanleenheer** [comment]
Hi Felix,

i solved the issue by using default Paypal and adjust it so it will send the address.

the discount is clearly in the the default OC system btw. no Mod needed for that.
but as i understand, it is more a problem of the way the Paypal api is working and not related to OC.

thanks for your reply!

Stefan

**Comment by AlexChanHK** [comment]
@stefanleenheer, as my understanding, the Opencart default have 2 function for the product discount.
1.Discount: to change the unit price when customer buy specify quantity.
2.Special: directly provide discount to the provide in the specify time.
But both two of them should not related to provide discount for subscriber.

For the default PayPal express issue(price is different between PayPal and Opencart system.)
Did you solved the issue?
If not, can we some example link or screen to understand?
