### ISSUE TITLE
Session mechanism

### ISSUE THREAD

**Issue by studioenot** [opencart/opencart#6160]
version 3.0.2.0

file: system/library/session/db.php
In the method write() we have:
expire = '" . $this->db->escape(date('Y-m-d H:i:s', time() + $this->expire)) . "'"

But in the methods read() we have:
expire > " . (int)time() 
and in the method and gc():
expire < " . ((int)time() + $expire)

It would not be correct to:
expire > " . date('Y-m-d H:i:s', (int)time())
and 
expire < " . date('Y-m-d H:i:s', ((int)time() + $expire))
?

Thanks

**Comment by danielkerr** [comment]
already altered in the master

**Comment by ADDCreative** [comment]
@danielkerr Dosen't look like it's been changed in the master. Still couple of places where time() (integer of milliseconds) needs formatting for the datetime type in the SQL queries.

https://github.com/opencart/opencart/blob/master/upload/system/library/session/db.php#L21
https://github.com/opencart/opencart/blob/master/upload/system/library/session/db.php#L45
