### ISSUE TITLE
create database when install

### ISSUE THREAD

**Issue by repair77** [opencart/opencart#6165]
Hi,
First,I'm not good at English,I'm a Chinese.
when I was using opencart 3.x, I found a problem.
when I install Opencart, why do you create databases manually?

**Comment by zemguru** [comment]
You mean, why the database is not created by installation script?
Because, usually You don't use privileged SQL user for security. Also, shared hostings gives You a user and a password for SQL with a limited permissions - not granted to create databases.

**Comment by repair77** [comment]
As developers, you're not sure your users have permission to create databases,
You should try to create a database, and if you can't create a database,
 throw a warning, and let the user create the database manually

**Comment by stalker780** [comment]
@repair77 You fill in a name of existing DB. And DB itself must be created by you via CPanel or other way.

**Comment by repair77** [comment]
There is no database selection method in the database adapter
I think it should be added
If the user does not fill or fill in the wrong database name, the database connection object will be wrong
