### ISSUE TITLE
Why while saving Billing Datails in ControllerCheckoutPaymentAddress > Save, products in cart should be loaded again!?

### ISSUE THREAD

**Issue by mynameismosa** [opencart/opencart#6170]
Hello,
It seems in the following pages all products in the cart are getting load for nothing, because saving while 'Payment Address' they are not used at all, in a case Validating minimum quantity requirements are already done in ControllerCheckoutCheckout:

ControllerCheckoutPaymentAddress
ControllerCheckoutPaymentMethod
ControllerCheckoutShippingAddress
...

`
	public function save() {
		$this->load->language('checkout/checkout');

		$json = array();

		// Validate if customer is logged in.
		if (!$this->customer->isLogged()) {
			$json['redirect'] = $this->url->link('checkout/checkout', '', true);
		}

		// Validate cart has products and has stock.
		if ((!$this->cart->hasProducts() && empty($this->session->data['vouchers'])) || (!$this->cart->hasStock() && !$this->config->get('config_stock_checkout'))) {
			$json['redirect'] = $this->url->link('checkout/cart');
		}

		// Validate minimum quantity requirements.
		$products = $this->cart->getProducts();

		foreach ($products as $product) {
			$product_total = 0;

			foreach ($products as $product_2) {
				if ($product_2['product_id'] == $product['product_id']) {
					$product_total += $product_2['quantity'];
				}
			}

			if ($product['minimum'] > $product_total) {
				$json['redirect'] = $this->url->link('checkout/cart');

				break;
			}
		}

		if (!$json) {
			$this->load->model('account/address');`

I'd highly appreciate if you help me about the issue or explain.

Regards,
Mo Sa

**Comment by repair77** [comment]
也许你的支付方式里面不需要支付地址吧，如果是别的支付方式，例如:信用卡，可能需要账单地址
Maybe you don't have to pay your address in the way you pay, and if there are other payments, such as credit cards, you may need a billing address

**Comment by danielkerr** [comment]
Ur complaining about validation even though there is no issue. Don't post non issues here. The validation is also required
