### ISSUE TITLE
There are a lot of mistakes related to language

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#6175]
ex
attribute_form
value="{{ attribute_description[language.language_id] ?
need
value="{{ attribute_description[language.language_id] is defined ?

{% if error_name[language.language_id] %}
need
{% if error_name[language.language_id] is defined %}

Similar errors in category_form, product_form, manufacurer_form, information_form
need
{% if error_name[language.language_id] is defined %}
{% if error_meta_title[language.language_id] is defined %}
{% if error_keyword[store.store_id][language.language_id] is defined %}

product_form,
{% if product_layout[store.store_id] is defined

category_form,
{% if category_layout[store.store_id] is defined

manufacturer_form,
{% if manufacurer_layout[store.store_id] is defined

information_form,
{% if information_layout[store.store_id] is defined

**Comment by chulcha** [comment]
also
design/banner_form
{% if error_banner_image[language.language_id][image_row] is defined %}

**Comment by chulcha** [comment]
also
sale/voucher_theme_form.twig
`{% if error_name[language.language_id] is defined %}`

also

customer/customer_group_form.twig
`                <input type="text" name="customer_group_description[{{ language.language_id }}][name]" value="{{ customer_group_description[language.language_id] is defined ? customer_group_description[language.language_id].name }}" placeholder="{{ entry_name }}" class="form-control" />
`
`{% if error_name[language.language_id] is defined %}`

`                <textarea name="customer_group_description[{{ language.language_id }}][description]" rows="5" placeholder="{{ entry_description }}" id="input-description{{ language.language_id }}" class="form-control">{{ customer_group_description[language.language_id] is defined ? customer_group_description[language.language_id].description }}</textarea>`

also
customer/customer_approval.twig

**Comment by chulcha** [comment]
also
customer/customer_approval.twig
<div class="container-fluid">{% if error_warning is defined %}

{% if success is defined %}

customer/custom_field_form.twig
`                <input type="text" name="custom_field_description[{{ language.language_id }}][name]" value="{{ custom_field_description[language.language_id] is defined ? custom_field_description[language.language_id].name }}" placeholder="{{ entry_name }}" class="form-control" />
`
{% if error_name[language.language_id] is defined %}

**Comment by straightlight** [comment]
Followed are all the files listed with 'is defined' in case:

- admin/view/template/extension/payment/eway.twig
- admin/view/template/extension/payment/globalpay.twig
- admin/view/template/extension/payment/klarna_checkout.twig
- admin/view/template/extension/payment/klarna_invoice.twig
- admin/view/template/extension/payment/realex.twig
- admin/view/template/extension/payment/realex_remote.twig

**Comment by danielkerr** [comment]
twig is a parsing template system it does not show errors for missing vars! 

what imaginary errors are u talking about?

**Comment by chulcha** [comment]
system/library/template/Twig/Environment.php
$options 
'strict_variables' => true,

Or

system/library/template/twig.php

$config['strict_variables'] = true;


The code must be clean, and not contain maskable errors

**Comment by danielkerr** [comment]
we dont need strict. its more load than necessary.

**Comment by ravilrrr** [comment]
What about those who are in need ?? Those who want to see all the mistakes and have full control over this??

**Comment by danielkerr** [comment]
than fix the errors your self!
