### ISSUE TITLE
do not updating currency

### ISSUE THREAD

**Issue by darkvladislav** [opencart/opencart#6179]
do not updating currency
yahoo closed service "http://download.finance.yahoo.com/"

**Comment by zemguru** [comment]
#5911

**Comment by lucasjkr** [comment]
Ive put forward a change that should resolve the issue. Got a new source for the needed data.

Longer term, there should be a better solution, but this'll work for now.

See opencart/opencart#6187

**Comment by darkvladislav** [comment]
thx
