### ISSUE TITLE
Hide prices - shop

### ISSUE THREAD

**Issue by Anthrasite-creation** [opencart/opencart#6181]
Hello,
I want to erase the price of all my product in this website.
How can I do?
The website : http://www.europrotex.fr/v2/index.php/tablier-de-travail

Thanks

**Comment by zemguru** [comment]
This is more like a support question, not meant to be in github issue tracker.

You can "hide" prices, by editing catalog/view theme/default/template/catalog/category/category.tpl or .twig templates,
the same with all extensions/modules/latest bestseller featured and so on.

You can't "switch" of prices. But You can do that in code. Or contact me pm.

**Comment by danielkerr** [comment]
login display price settings

**Comment by Anthrasite-creation** [comment]
I didn't find it.
Can you help me?
Is it the right way? 
components/com_mijoshop/opencart/catalog/view/theme/default/template/product
I can't find the way that you mentionned in your message.

When I erase "price" nothing happened in my website.

Thanks.

**Comment by CoverUp** [comment]
You are using mijoshop for joomla!! not opencart. This is not the place for that.
