### ISSUE TITLE
Multi language site OC3

### ISSUE THREAD

**Issue by Manitoou** [opencart/opencart#6189]
Suggestion about multi-language website, for ex. Eng/Fr;
In OC3 we have 2 Urls to the same content : when we click  DOMAIN.COM/FR or DOMAIN.COM/Eng they both take you to the same page (with default language);
In a normal way it must be: DOMAIN.COM/FR to Fr content and DOMAIN.COM/Eng to Eng content.
Thx

**Comment by danielkerr** [comment]
this would have to be a feature to be added. for now use sub domains.

en.yourdomain.com
fr.yourdomain.com

**Comment by danielkerr** [comment]
also here is not for requesting this sort of thing. its the forums.

**Comment by Manitoou** [comment]
Thank you for your reply.
Right it just was a suggestion but, when you see, OC3 create duplicate content for multi-language website, so it's a problem and I think that this is the right place for an issue not the forum. Thx

**Comment by danielkerr** [comment]
it doesn't create duplicate content! language is based on cookies. this is how you thin k something should work an d npot thew correct way! dont post here unless u know what u are talking about
