### ISSUE TITLE
OC 3.0.2.0 doesn't notice changes made to the DB by loading a backup

### ISSUE THREAD

**Issue by Shifterovich** [opencart/opencart#6190]
I have loaded an `.sql` backup. I can see that it's in the DB, but OC doesn't notice it. When I write to the DB, by i.e. creating a new product, I can see a new row in `oc_product`, with an ID following the previous one, but OC doesn't notice the preceding rows.

This issue is similar to #5716. The caching mechanism seems to be somewhat broken, but that's a separate, although superordinate, issue.

Is there something I can do apart from waiting for a fix, like deleting the cache somehow?

**Comment by danielkerr** [comment]
noyt sure what u area talking about but u can clear the tempolate cache via the dashboard

**Comment by Shifterovich** [comment]
Loading a backup loads the data into the DB, but OC doesn't see it.

**Comment by Shifterovich** [comment]
Also, deleting `cache/` (and creating it again, with `index.html` in it) didn't work.
