### ISSUE TITLE
OC 3.0.2.1b - Few little things on a new install

### ISSUE THREAD

**Issue by waxedperfection** [opencart/opencart#6197]
1,The admin footer is showing as "OpenCart © 2009-2017 All Rights Reserved. Version 3.0.2.0" on the OC 3.0.2.1b version.

2,When adding an item to the cart, it tells me "Success: You have added PRODUCT NAME to your shopping cart!" click the cart button to check out and get "Your shopping cart is empty!"

and last, brand new install, 14/11/2017

3. every time i press the dashboard button or opencart logo in the admin panel i get a "syntaxerror" 
https://image.ibb.co/mAeFQ6/error.jpg

i hope this helps.

**Comment by Pelham81** [comment]
I confirm that I get the syntax error too (JSON unexpected token). It's only for when being on the dashboard page upon loggin into admin - using same install. I actually ran the install on a test web server this morning.

**Comment by Pelham81** [comment]
I actually suspect it has to do with the addition of the newly added ajax code for currency on the dashboard.twig file.

**Comment by waxedperfection** [comment]
@pelham81 was you able to duplicate the shopping basket error also? 

adding an item to the cart and the clicking the cart to be told the basket is empty?

**Comment by Pelham81** [comment]
I finally got around to bothering with the front end. Yes - that happens, too. But I can't even login in. After registering an account on the front end (or even doing it on the back end and attempting to login with account), it keeps looping back to the login screen. I am also getting repeatedly logged out on the admin/back end. This current beta install simply is not functional for me.

**Comment by waxedperfection** [comment]
Yes, i have the same issue, I keep getting logged out too.

i also have the following in my database repair -
 
[couk_store.oc_cart] note: The storage engine for the table doesn't support repair
[couk_store.oc_session] note: The storage engine for the table doesn't support repair

**Comment by Pelham81** [comment]
The issue (for the login looping back) lies in the install files (not the upgrade files). I tested this again doing an upgrade now over my Nov 12th install on another test site and the looping / logging out did not occur.

**Comment by danielkerr** [comment]
3.0.2.1b has never been released. it was the cloud version!

are u talking about the master?

The system works fine for me! i think your server session storeage is not setup correctly.

**Comment by waxedperfection** [comment]
@danielkerr Thank you for getting back to me - https://github.com/opencart/opencart then i clicked the clone or download and the downloaded the Zip, please forgive me for not knowing the version.

**Comment by Pelham81** [comment]
This was for the master version DL'ed this morning.
