### ISSUE TITLE
cli_install.php fails with Error: Table 'opencart.oc_attribute' doesn't exist

### ISSUE THREAD

**Issue by breisig** [opencart/opencart#6200]
Downloading the latest code from git [master] and running cli_install.php from the command line to install it,

php install/cli_install.php install --db_hostname 127.0.0.1 --db_username root --db_password myrootpassword --db_database opencart --username admin --password admin2 --email somebody@somewhere.com --http_server http://www.example.com/

I get the following error message,

PHP Fatal error:  Uncaught Exception: Error: Table 'opencart.oc_attribute' doesn't exist<br />Error No: 1146<br />

INSERT INTO `oc_attribute` (`attribute_id`, `attribute_group_id`, `sort_order`) VALUES
(1, 6, 1),
(2, 6, 5),
(3, 6, 3),
(4, 3, 1),
(5, 3, 2),
(6, 3, 3),
(7, 3, 4),
(8, 3, 5),
(9, 3, 6),
(10, 3, 7),
(11, 3, 8);
 in /var/www/html/www.example.com/system/library/db/mysqli.php:40
Stack trace:
#0 /var/www/html/www.example.com/system/library/db.php(45): DB\MySQLi->query('\n\n\nINSERT INTO ...')
#1 /var/www/html/www.example.com/install/cli_install.php(205): DB->query('\n\n\nINSERT INTO ...')
#2 /var/www/html/www.example.com/install/cli_install.php(134): setup_db(Array)
#3 /var/www/html/www.example.com/install/cli_install.php(353): install(Array)
#4 {main}
  thrown in /var/www/html/www.example.com/system/library/db/mysqli.php on line 40

If I download the latest 3.0.2.0 release version tar, it works. It looks like when running the latest version from git[master] is broken.

**Comment by danielkerr** [comment]
this is working in the master branch
