### ISSUE TITLE
$this->session->data['api_id'] empty outside catalog/api/login.php

### ISSUE THREAD

**Issue by ar27111994** [opencart/opencart#6202]
Hi, the Opencart API Session doesn't seem to work outside its originating file i.e. `catalog/api/login.php`. I've fixed the code in the API login file with the latest fixes but the session doesn't propagate to the rest of the API folder. Please help. (I'm developing an Opencart Mobile Application for a client, therefore, need the API working on the client side). This is the entry point of the mobile application:

https://ocapp.ar27111994.com/index.php?route=api/curl (Currently halted with `die session` statement to inspect `session object` after API Login and as you can see, there is no `data['api_id']` item in the Session object, whereas the `$session->data['api_id']` is not empty inside `catalog/api/login.php` when inspected)

My web server is Apache and PHP Version is 7.1.

**Comment by danielkerr** [comment]
is this the master u are talking about?

**Comment by ar27111994** [comment]
the fix is from the current master but opencart version is 3.0.2.0.

**Comment by danielkerr** [comment]
ok the system is a little different compared to editing orders on the same server. you have to login then get a session id or token returned. you need to include that in each request.

**Comment by danielkerr** [comment]
github is for development not a support system!

im not here to fix old issues!
