### ISSUE TITLE
Russian translation registration is broken

### ISSUE THREAD

**Issue by stas730** [opencart/opencart#6203]
Russian translation is broken:

1. It breaks wish list ('Wish List (%s)') [wrong]
2. Registration success page is broken
I don't know about other issues.

**Comment by ravilrrr** [comment]
Стас, это не ошибка связанная с переводом. Если не уверены в ошибке, пишите сначала на форуме. Не засоряйте гит. И так Даниель злой на такого рода сообщения.
Ну и конечно пользуйтесь поиском. Вот тут описывается проблема https://github.com/opencart/opencart/issues/5019

**Comment by stas730** [comment]
Регистрация не работает только на русском языке (на украинском работает).
Wish List не связан с переводом.

**Comment by stas730** [comment]
Не выходит зарегистрировать учётную запись на форуме (временный адрес электронной почты Guerrilla Mail запрещают).
Попробуйте зайти на страницу http://example.com/index.php?route=account/success с русским переводом.
