### ISSUE TITLE
Fresh install issue

### ISSUE THREAD

**Issue by PMMRanger** [opencart/opencart#6209]
The following error was encountered after completely deleting OC and installing again. Once I click the "OK" on the pop-up, everything appears to work fine until I return to the dashboard (or refresh it). Thank you in advance for any and all help. --Cheers.

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
OK
<br />
<b>Fatal error</b>:  Uncaught Exception: Error: Could not load model extension/dashboard/chart! in /home/seaportx/productstorage/modification/system/engine/loader.php:89
Stack trace:
#0 /home/seaportx/public_html/corvette/productmgr/admin/controller/extension/dashboard/chart.php(99): Loader-&gt;model('extension/dashb...')
#1 /home/seaportx/productstorage/modification/system/engine/action.php(79): ControllerExtensionDashboardChart-&gt;chart()
#2 /home/seaportx/public_html/corvette/productmgr/admin/controller/startup/router.php(26): Action-&gt;execute(Object(Registry), Array)
#3 /home/seaportx/productstorage/modification/system/engine/action.php(79): ControllerStartupRouter-&gt;index()
#4 /home/seaportx/public_html/corvette/productmgr/system/engine/router.php(67): Action-&gt;execute(Object(Registry))
#5 /home/seaportx/public_html/corvette/productmgr/system/engine/router.php(56): Router-&gt;execute(Object(Action))
#6 /home/seaportx/public_html/corvette/productmgr/system/framework.php(168): Router-&gt;dispatch(Object(Action), Object(Action))
#7 /home/sea in <b>/home/seaportx/productstorage/modification/system/engine/loader.php</b> on line <b>89</b><br />

**Comment by ChrisLancs** [comment]
It looks like a problem with the move of your storage outside of the webroot. You can try to manually move it.
copy/move the contents of system/storage into /home/seaportx/productstorage/

I assume product storage is the path you chose outside of the webroot

**Comment by ChrisLancs** [comment]
@danielkerr Ive tagged you because I also came across this when i installed a couple of days ago.

Looking over security.php it appears that its doing as it should except the following.

Neither mkdir or copy are being checked for completion, If either of these fail there should be no write to the config file.

**Comment by PMMRanger** [comment]
Thank you for the help. I think I remember being advised to move the storage directory out of the root (must have misunderstood). I moved the produtstorage directory back within the main directory where admin, catalog, image and system directories are found... still get same  error. Is there a registry somewhere that needs to be changed as well?

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

OK

<br />
<b>Fatal error</b>:  Uncaught Exception: Error: Could not load model extension/dashboard/chart! in /home/seaportx/productstorage/modification/system/engine/loader.php:89
Stack trace:
#0 /home/seaportx/public_html/corvette/productmgr/admin/controller/extension/dashboard/chart.php(99): Loader-&gt;model('extension/dashb...')
#1 /home/seaportx/productstorage/modification/system/engine/action.php(79): ControllerExtensionDashboardChart-&gt;chart()
#2 /home/seaportx/public_html/corvette/productmgr/admin/controller/startup/router.php(26): Action-&gt;execute(Object(Registry), Array)
#3 /home/seaportx/productstorage/modification/system/engine/action.php(79): ControllerStartupRouter-&gt;index()
#4 /home/seaportx/public_html/corvette/productmgr/system/engine/router.php(67): Action-&gt;execute(Object(Registry))
#5 /home/seaportx/public_html/corvette/productmgr/system/engine/router.php(56): Router-&gt;execute(Object(Action))
#6 /home/seaportx/public_html/corvette/productmgr/system/framework.php(168): Router-&gt;dispatch(Object(Action), Object(Action))
#7 /home/sea in <b>/home/seaportx/productstorage/modification/system/engine/loader.php</b> on line <b>89</b><br />

**Comment by ChrisLancs** [comment]
yes you need to open up the two config files and change the storage paths back the original if you move them back.

in your store root: config.php and in the admin config.php revert the definition.
define('DIR_STORAGE', '/home/seaportx/public_html/corvette/system/storage/');

I assume the store is located in corvette and not in public_html is thats wrong then remove the corvette part

However, moving them outside of the webroot is advised for security but its only going to work if php is allowed to access them, you will need to add the path /home/seaportx/productstorage/ to the permitted paths in php.ini

I think you are using cpanel so there should be a place in the control panel to add it.

**Comment by PMMRanger** [comment]
I tried a changing both definitions in the config files to the default at install which was: /home/seaportx/public_html/corvette/productmgr/system/storage/ however, not only did I get the same error but also the popup directing me to change the location of storage (see attached). I then moved the storage (using the utility) to /home/seaportx/ (gave me a green checkmark that it was OK). but got the same error.
![image9](https://user-images.githubusercontent.com/17152113/32994660-ade697b4-cd27-11e7-833a-7c1b7c2aa955.png)

**Comment by PMMRanger** [comment]
OK, wait... I think I see the problem. home/seaportx is outside the public_html root (duh). stay tuned.

**Comment by PMMRanger** [comment]
still no good... error still persists

**Comment by PMMRanger** [comment]
Whatever it was, reinstalling fixed it...

**Comment by ChrisLancs** [comment]
@PMMRanger being outside of public_html (webroot/doc_root) but still within your user directory is the preferred location for that directory. 

Your issue seems to be that the new storage path is not permitted to php, the previously mentioned php.ini setting allows you to use it.
