### ISSUE TITLE
The directory system/custom.ocmod.xml is not allowed to be written to 

### ISSUE THREAD

**Issue by Atul1413** [opencart/opencart#6211]
Dear Team,
i installed opencart on linux hosting .i am getting an error while uploading theme using extension.

kindly help us to resolve the issue.

Warm Regards,
Atul S
![custom ocmod](https://user-images.githubusercontent.com/11453397/33059663-5084344c-cebb-11e7-8d2b-3143b924a279.PNG)

**Comment by danielkerr** [comment]
there is a list of allowed directories.

**Comment by Atul1413** [comment]
Hello sir,
thanks for the prompt reply ..
i am getting an permission error while installing opencart.

Files | Status
-- | --
/home/phoen1212/public_html/new/config.php | Missing
/home/phoen1212/public_html/new/admin/config.php | Unwritable


Warm Regards,
Atul S

**Comment by Atul1413** [comment]
now i have given 0755 for both files.

please help

Warm Regards,
Atul S

**Comment by danielkerr** [comment]
use the forum! this is for development!
