### ISSUE TITLE
Amazon Login Pay - Controller > catalog >>error array to string conversion

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#6214]
This line here makes no sense, 
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/extension/payment/amazon_login_pay.php#L556

instead producing an error:
Array to string conversion in ../catalog/controller/extension/payment/amazon_login_pay.php on line 565

Should be removed .. ?

**Comment by danielkerr** [comment]
just post your PayPal email or id in the commit comments.

**Comment by lucasjkr** [comment]
I wish i had an Amazon Pay API key
