### ISSUE TITLE
Tabs in PHP and spaces in TWIG. Why? :)

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#6218]
I have been tormented for years by the question - why spaces in templates and tabs in controllers/models/libraries?

I always have to fight with this in editors. They usually have one setting what to use - spaces or tabs. But whatever I choose it breaks either template or php files. Or I have to use different editors for for templates and php files.

So why? :)

https://youtu.be/SsoOG6ZeyUI

Actually I stopped paying attention to this years ago. But I always meet a lot of indentation garbage in files where other developers worked.

**Comment by danielkerr** [comment]
Because Twig is within the HTML.

It's what ever coding standard is set out by the developer of the language. Also HTML is not really a programming language more like a text presentation language.

**Comment by DariyGRAY** [comment]
So can lead all to one kind? For example, leave points everywhere:)
