### ISSUE TITLE
PayPal Express Checkout

### ISSUE THREAD

**Issue by Heteroculturalism** [opencart/opencart#6221]
I am using OpenCart 3.0.2.0 with a PayPal sandbox account and when I check out I get 

Notice: Undefined index: L_LONGMESSAGE0 in /home/freecamp/public_html/opencart/catalog/controller/extension/payment/pp_express.php on line 1334Warning: Cannot modify header information - headers already sent by (output started at /home/freecamp/public_html/opencart/catalog/controller/startup/error.php:34) in /home/freecamp/public_html/opencart/system/library/response.php on line 36

You can try yourself @ jeromebell.com/opencart.  It's a test site.  Any help is appreciated.

**Comment by straightlight** [comment]
In catalog/controller/extension/payment/pp_express.php file, below line 1328, add:

$this->log->write('PAYPAL EXPRESS_CHECKOUT :: ' . print_r($result, true));

Test another order until reaching that error message again. See in your admin - > system - > maintenance - > error logs for a sentence beginning with: PAYPAL EXPRESS_CHECKOUT :: near the end of your logs. Post the results here afterwards by removing confidential information from the array before you post.

**Comment by Felix-Ho** [comment]
@Heteroculturalism 
Would you mind share your store admin login also with FTP detail to us?
So that we can investigate the issue for you?

Email :  felix@opencart.com

Please note that don't share through here since this is public.

**Comment by jamesallsup** [comment]
Commit note reads:

Added checks around each error part that could be passed from PayPal if it is post curl request. If no error is found then a generic error is displayed to the user to advise contacting the store owner. Without any php notice being thrown.

The system was made originally with an EXTREMELY accurate log collection around almost every PayPal call and action. Simple solution is to check the logs - enable them in the PayPal module then look at them AFTER you can replicate the problem.

Blindly creating a bug report over a PHP notice is not helpful, logs are helpful so please next time provide the actual error that PayPal says which will be found in your log. Worst case scenario is that PayPal sandbox is having problems - I have created many issues before only to find out it was a 5 minute window causing problems on the sandbox and even live checkout systems too.

https://developer.paypal.com/support/ - They can advise what error message PayPal gave and why.

As Express checkout is now ageing there is also the chance of legacy code being phased out - we usually get informed prior to it happening but if that is reported by PayPal tech support please create another issue for it.
