### ISSUE TITLE
SQL Syntax error during upgrade from 3.0.2.0 to latest repository

### ISSUE THREAD

**Issue by Pelham81** [opencart/opencart#6225]
![screenshot 2017-11-26 12 10 45](https://user-images.githubusercontent.com/30006048/33243291-41c46f04-d2b1-11e7-878b-20d0e6412957.png)
Using a test webserver here. I installed the last stable release (fresh). I then downloaded the current repository (Nov 26th) and attempted an upgrade. I get the following error:

`Error Code(0): Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF EXISTS `PRIMARY`' at line 1
Error No: 1064
ALTER TABLE `oc_address` DROP INDEX IF EXISTS `PRIMARY` in /home/username/public_html/test/system/library/db/mysqli.php on line 40`

**Comment by straightlight** [comment]
Confirmed. Since the Key_name key from the database cannot be guaranteed on every created array during the loop, in install/model/upgrade/1000.php file, find:

`foreach ($query->rows as $result) {
					$this->db->query("ALTER TABLE `" . DB_PREFIX . $table['name'] . "` DROP INDEX IF EXISTS `" . $result['Key_name'] . "`");
				}`

replace with:

`foreach ($query->rows as $result) {
                    if (!empty($result['Key_name'])) {
						$this->db->query("ALTER TABLE `" . DB_PREFIX . $table['name'] . "` DROP INDEX IF EXISTS `" . $result['Key_name'] . "`");
					}
				}`

**Comment by straightlight** [comment]
Hi, I created a forum topic here to solve this issue: https://forum.opencart.com/viewtopic.php?f=201&t=199981 . Thank you for posting this.

**Comment by Pelham81** [comment]
Did you  replicate this issue and test that code? That post of yours does not solve the issue at all.

It still spits out the same error code. 

I am not a MySQL expert at all, and I just post here bugs I find along the way. If I had to make some sort of educated guess (and anyone can correct me if I am wrong), but this syntax is referring to code trying to look at "Primary" somehow. instead of "Primary Key"?  I have already looked throughout the 1000.php file immediately upon seeing this error the first time, but that's at most all I can speculate on this issue.

**Comment by straightlight** [comment]
I did indeed do the research on PHP.net regarding the Key_name field. It looks for the PRIMARY key but may not guarantee to track that value during specific rows while running the loop. Which is why, the Key_name must only be indicated whenever it can be found while the loop is running.

**Comment by danielkerr** [comment]
no idea which version you are talkign about

**Comment by straightlight** [comment]
The version was not indicated but the path of the issue from where it is originating from has been. This is also included from the github code tab on the indicated path and file.

**Comment by Pelham81** [comment]
The very last stable version: 3.0.2.0

I mentioned it in my original post.

**Comment by straightlight** [comment]
You did? I don't see it other than now even by doing a query search from the browser ...

**Comment by Pelham81** [comment]
I'm sorry I didn't spell it out word for word in the title, but I stated in my first posted:

"Using a test webserver here. I installed the last stable release (fresh). I then downloaded the current repository (Nov 26th) and attempted an upgrade. I get the following error"

**Comment by straightlight** [comment]
Still, the version number was not indicated in order to help others to understand the source of the issue for future use other than the indicated date for this time period. Which is why, it is best to always mention the OC version that anyone needs to report about - especially if it can be avoided to say: 'latest release'. v3.0.2.1b and v3.0.2.0 are both considered the latest release in a sense. One is with the cloud and showing on the top of the downloads list from the Opencart.com website, the other one is without the cloud and still considered to be the latest version ('stable' with questionmark) release of its kind.

**Comment by Pelham81** [comment]
My apologies. I normally have been more specific in the subject line. Now, you know what version I am talking about :)

**Comment by danielkerr** [comment]
mater is working now

**Comment by straightlight** [comment]
I was able to reproduce this issue by also downloading the master files during an upgrade attempt as a custom job for a client yesterday. DROP INDEX "IF EXISTS" does not seem to be a known reference from mySQL v5.7 website. I did found alternative solutions on StackOverFlow website to pull out the indexes from the information.schema database. There are, for sure, alternative solutions that can be used other than this line.

**Comment by Pelham81** [comment]
I am using mySQL 5.6.38

And FYI - the issue does continue to persist. I just tried the last master repository yet again (from today 12/2) attempting to do an upgrade.

Hope that helps.

**Comment by danielkerr** [comment]
ok try now

**Comment by danielkerr** [comment]
actually i need to ad something so it does not delete the primary key

**Comment by Pelham81** [comment]
i'll give it a try once you make that addition. I have another fresh 3.0.2.0 prepared

**Comment by danielkerr** [comment]
try now

**Comment by LJK-opencartmods** [comment]
Reading this from my phone, not sure if it’s been fixed or not but on here it looks like the issue is just lack of spaces before and after DB_PREFIX

($query->rows as $result) { $this->db->query("ALTER TABLE" . DB_PREFIX . $table['name'] . "DROP INDEX IF EXISTS" . $result['Key_name'] . "");

Although not sure why the upgrade should delete existing indexes, but that’s something else altogether.

**Comment by danielkerr** [comment]
its been fixed

**Comment by Pelham81** [comment]
Well.. it looked the upgrade worked fine on a fresh 3.0.2.0. But then, when I tried to access the size, I got the following:

[05-Dec-2017 02:22:23 UTC] PHP Fatal error:  Uncaught Error: Class 'Twig_Loader_Filesystem' not found in /home/***private***/public_html/test/main/system/library/template/twig.php:13
Stack trace:
#0 /home/***private***/public_html/test/main/system/library/template.php(51): Template\Twig->render('common/header', '1')
#1 /home/***private***/public_html/test/main/system/engine/loader.php(129): Template->render('common/header', '1')
#2 /home/***private***/public_html/test/main/admin/controller/common/header.php(72): Loader->view('common/header', Array)
#3 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonHeader->index()
#4 /home/***private***/public_html/test/main/system/engine/loader.php(52): Action->execute(Object(Registry), Array)
#5 /home/***private***/public_html/test/main/admin/controller/common/login.php(81): Loader->controller('common/header')
#6 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonLogin->index()
#7 /home/***private***/public_html/test/main/system/engine/router.php(67): Action->execute(Object(Registry))
# in /home/***private***/public_html/test/main/system/library/template/twig.php on line 13
[05-Dec-2017 02:22:25 UTC] PHP Fatal error:  Uncaught Error: Class 'Twig_Loader_Filesystem' not found in /home/***private***/public_html/test/main/system/library/template/twig.php:13
Stack trace:
#0 /home/***private***/public_html/test/main/system/library/template.php(51): Template\Twig->render('common/header', '1')
#1 /home/***private***/public_html/test/main/system/engine/loader.php(129): Template->render('common/header', '1')
#2 /home/***private***/public_html/test/main/admin/controller/common/header.php(72): Loader->view('common/header', Array)
#3 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonHeader->index()
#4 /home/***private***/public_html/test/main/system/engine/loader.php(52): Action->execute(Object(Registry), Array)
#5 /home/***private***/public_html/test/main/admin/controller/common/login.php(81): Loader->controller('common/header')
#6 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonLogin->index()
#7 /home/***private***/public_html/test/main/system/engine/router.php(67): Action->execute(Object(Registry))
# in /home/***private***/public_html/test/main/system/library/template/twig.php on line 13
[05-Dec-2017 02:22:26 UTC] PHP Fatal error:  Uncaught Error: Class 'Twig_Loader_Filesystem' not found in /home/***private***/public_html/test/main/system/library/template/twig.php:13
Stack trace:
#0 /home/***private***/public_html/test/main/system/library/template.php(51): Template\Twig->render('common/header', '1')
#1 /home/***private***/public_html/test/main/system/engine/loader.php(129): Template->render('common/header', '1')
#2 /home/***private***/public_html/test/main/admin/controller/common/header.php(72): Loader->view('common/header', Array)
#3 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonHeader->index()
#4 /home/***private***/public_html/test/main/system/engine/loader.php(52): Action->execute(Object(Registry), Array)
#5 /home/***private***/public_html/test/main/admin/controller/common/login.php(81): Loader->controller('common/header')
#6 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonLogin->index()
#7 /home/***private***/public_html/test/main/system/engine/router.php(67): Action->execute(Object(Registry))
# in /home/***private***/public_html/test/main/system/library/template/twig.php on line 13
[05-Dec-2017 02:22:46 UTC] PHP Fatal error:  Uncaught Error: Class 'Twig_Loader_Filesystem' not found in /home/***private***/public_html/test/main/system/library/template/twig.php:13
Stack trace:
#0 /home/***private***/public_html/test/main/system/library/template.php(51): Template\Twig->render('common/header', '1')
#1 /home/***private***/public_html/test/main/system/engine/loader.php(129): Template->render('common/header', '1')
#2 /home/***private***/public_html/test/main/admin/controller/common/header.php(72): Loader->view('common/header', Array)
#3 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonHeader->index()
#4 /home/***private***/public_html/test/main/system/engine/loader.php(52): Action->execute(Object(Registry), Array)
#5 /home/***private***/public_html/test/main/admin/controller/common/login.php(81): Loader->controller('common/header')
#6 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonLogin->index()
#7 /home/***private***/public_html/test/main/system/engine/router.php(67): Action->execute(Object(Registry))
# in /home/***private***/public_html/test/main/system/library/template/twig.php on line 13
[05-Dec-2017 02:22:48 UTC] PHP Fatal error:  Uncaught Error: Class 'Twig_Loader_Filesystem' not found in /home/***private***/public_html/test/main/system/library/template/twig.php:13
Stack trace:
#0 /home/***private***/public_html/test/main/system/library/template.php(51): Template\Twig->render('common/header', '1')
#1 /home/***private***/public_html/test/main/system/engine/loader.php(129): Template->render('common/header', '1')
#2 /home/***private***/public_html/test/main/admin/controller/common/header.php(72): Loader->view('common/header', Array)
#3 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonHeader->index()
#4 /home/***private***/public_html/test/main/system/engine/loader.php(52): Action->execute(Object(Registry), Array)
#5 /home/***private***/public_html/test/main/admin/controller/common/login.php(81): Loader->controller('common/header')
#6 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonLogin->index()
#7 /home/***private***/public_html/test/main/system/engine/router.php(67): Action->execute(Object(Registry))
# in /home/***private***/public_html/test/main/system/library/template/twig.php on line 13
[05-Dec-2017 02:22:49 UTC] PHP Fatal error:  Uncaught Error: Class 'Twig_Loader_Filesystem' not found in /home/***private***/public_html/test/main/system/library/template/twig.php:13
Stack trace:
#0 /home/***private***/public_html/test/main/system/library/template.php(51): Template\Twig->render('common/header', '1')
#1 /home/***private***/public_html/test/main/system/engine/loader.php(129): Template->render('common/header', '1')
#2 /home/***private***/public_html/test/main/admin/controller/common/header.php(72): Loader->view('common/header', Array)
#3 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonHeader->index()
#4 /home/***private***/public_html/test/main/system/engine/loader.php(52): Action->execute(Object(Registry), Array)
#5 /home/***private***/public_html/test/main/admin/controller/common/login.php(81): Loader->controller('common/header')
#6 /home/***private***/public_html/test/main/system/engine/action.php(79): ControllerCommonLogin->index()
#7 /home/***private***/public_html/test/main/system/engine/router.php(67): Action->execute(Object(Registry))
# in /home/***private***/public_html/test/main/system/library/template/twig.php on line 13

**Comment by danielkerr** [comment]
i dont know what you have donme to your site but the errors you are having are caused by your server not setup correctly. nobody else is getting these errors!

make sure the server has the correct paths setup. 

stop posting here! you dont know what you are talking about and this area is for development not for fixing your web site!

uise the contact us form on opencart.com and ask for alex. he will login and fix your site oir at least find your issue.

biut as i said you are posting issues becuase your server has not been setup properly. so stop wasting my time!
