### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lucasjkr** [opencart/opencart#6230]
Looks like the installer was changed and an error was introduced.

Table Prefix has `oc_` entered by default, but the (new) validation refuses that entry (says the prefix can only contain a-z, 0-9, and no symbols, meaning no underscore. 

Maybe it was meant to hardcode in the underscore after the prefix was chosen, and that step was forgotten?

<img width="1030" alt="screen shot 2017-11-27 at 12 43 02 pm" src="https://user-images.githubusercontent.com/4703516/33280630-b29ac38a-d370-11e7-8a18-1ba2ed60d24e.png">

**Comment by straightlight** [comment]
In install/controller/install/step3.php file,

preg_match('/[^a-z0-9_]/'

should probably be:

!preg_match('/[a-z0-9_]/'
