### ISSUE TITLE
If call to ControllerEventTheme->override() fails, a twig error fires. 

### ISSUE THREAD

**Issue by jpshdev** [opencart/opencart#6235]
In attempting to update to 3.0.2.0 from 3.0.1.1 I ran into a twig error that my template files could not be found. I installed a vanilla 3.0.2.0 for testing and changed the name of the override function hoping to trigger an error that would tell me where the call to the function was being made and was able to re-create the Twig error. I am still not sure when that override function is being called, nor from where.

**Comment by danielkerr** [comment]
event/theme
