### ISSUE TITLE
Your shopping cart is empty 

### ISSUE THREAD

**Issue by Sebaortiz** [opencart/opencart#6236]
I'm using OC 3.0.2.0, when I add 1 item to the shopping cart, I got the notice: Success: You have added xxxxxx to your shopping cart!, but when I go to shopping cart page, there is nothing. (Your shopping cart is empty!) 

ps: I didn't install other extensions.

Image:

![Image of Cart](https://i.imgur.com/hVfHTgy.png)

**Comment by danielkerr** [comment]
can not replicate

**Comment by straightlight** [comment]
The reason why the product may have failed to be added to the cart even though there's a success message on the cart page is due to the storage folder not being stored outside the public_html / www / htdocs folder as a writable folder then also having the DIR_STORAGE reconfigured in the config.php and admin/config.php file so for the session ID to be able to create its file with sess_<<id>> when using session files.

**Comment by nishadhra** [comment]
Storage folder outside public_html but still problem persists.

**Comment by danielkerr** [comment]
@straightlight has already given you the anwser!

think
!
 its a permission issue!

it not an opencart bug!!!! payh some one to fix it. very easy to fix.

**Comment by nishadhra** [comment]
@danielkerr Already followed what has been mentioned by @straightlight but the problem persists. I even checked the config.php and admin.config.php files but no respite. For your reference, please find below the file contents (the store name and credentials have been masked):

config.php
<?php
// HTTP
define('HTTP_SERVER', 'http://mysamplestore.com/');

// HTTPS
define('HTTPS_SERVER', 'http://mysamplestore.com/');

// DIR
define('DIR_APPLICATION', '/home/kabeerb15/public_html/catalog/');
define('DIR_SYSTEM', '/home/kabeerb15/public_html/system/');
define('DIR_IMAGE', '/home/kabeerb15/public_html/image/');
define('DIR_STORAGE', '/home/kabeerb15/storage/');
define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');
define('DIR_TEMPLATE', DIR_APPLICATION . 'view/theme/');
define('DIR_CONFIG', DIR_SYSTEM . 'config/');
define('DIR_CACHE', DIR_STORAGE . 'cache/');
define('DIR_DOWNLOAD', DIR_STORAGE . 'download/');
define('DIR_LOGS', DIR_STORAGE . 'logs/');
define('DIR_MODIFICATION', DIR_STORAGE . 'modification/');
define('DIR_SESSION', DIR_STORAGE . 'session/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'username');
define('DB_PASSWORD', 'password');
define('DB_DATABASE', 'database');
define('DB_PORT', '3306');
define('DB_PREFIX', 'oc_');


admin.config.php
<?php
// HTTP
define('HTTP_SERVER', 'http://mysamplestore.com/admin/');
define('HTTP_CATALOG', 'http://mysamplestore.com/');

// HTTPS
define('HTTPS_SERVER', 'http://mysamplestore.com/admin/');
define('HTTPS_CATALOG', 'http://mysamplestore.com/');

// DIR
define('DIR_APPLICATION', '/home/kabeerb15/public_html/admin/');
define('DIR_SYSTEM', '/home/kabeerb15/public_html/system/');
define('DIR_IMAGE', '/home/kabeerb15/public_html/image/');
define('DIR_STORAGE', '/home/kabeerb15/storage/');
define('DIR_CATALOG', '/home/kabeerb15/public_html/catalog/');
define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');
define('DIR_TEMPLATE', DIR_APPLICATION . 'view/template/');
define('DIR_CONFIG', DIR_SYSTEM . 'config/');
define('DIR_CACHE', DIR_STORAGE . 'cache/');
define('DIR_DOWNLOAD', DIR_STORAGE . 'download/');
define('DIR_LOGS', DIR_STORAGE . 'logs/');
define('DIR_MODIFICATION', DIR_STORAGE . 'modification/');
define('DIR_SESSION', DIR_STORAGE . 'session/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'username');
define('DB_PASSWORD', 'password');
define('DB_DATABASE', 'database');
define('DB_PORT', '3306');
define('DB_PREFIX', 'oc_');

// OpenCart API
define('OPENCART_SERVER', 'https://www.opencart.com/');

**Comment by danielkerr** [comment]
I don't care. Stop posting here. It's ur idsue
