### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by TBFdirect** [opencart/opencart#6237]
Error Code(0): Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF EXISTS `PRIMARY`' at line 1
Error No: 1064
ALTER TABLE `oc_address` DROP INDEX IF EXISTS `PRIMARY` in /home/tbfdirect/public_html/system/library/db/mysqli.php on line 40

**Comment by straightlight** [comment]
This issue has already been addressed and resolved: https://github.com/lucasjkr/opencart/commit/75dace1aed1a1d465ac09ffab73fe9a5925d3315
