### ISSUE TITLE
Currency not autoupdating

### ISSUE THREAD

**Issue by xseon** [opencart/opencart#6241]
The autoupdate currency function is not working. If thats the address where the rates are coming from
http://download.finance.yahoo.com/d/quotes.csv
here is the message: Error 403: Forbidden
It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.

**Comment by danielkerr** [comment]
I added a fix in 3.0 l. There is a whole new system for choosing which currency engine you want to use

**Comment by danielkerr** [comment]
I mean master branch

**Comment by danielkerr** [comment]
I think I need to add some code for legacy users

**Comment by danielkerr** [comment]
In the forums
