### ISSUE TITLE
Curious case of 302 redirect/loops on front-end login (master repository)

### ISSUE THREAD

**Issue by Pelham81** [opencart/opencart#6243]
I briefly mentioned this as a side-note before on an unrelated issue page with the installer, but Daniel stated it was "permissions issues." I am not fully convinced of such.

I've been testing a lot of the master updates through XAMPP on my PC directly. But in the last two weeks, I decided to test ALL master repositories as fresh installs on my Bluehost VPS server which also happens to contain a perfectly working, clean/unmodified 3.0.2.0 stable version as well as modified versions of 3.0.2.0 to test out some mods. I've also upgraded from 3.0.2.0 to these masters which also amassed to the same issue here after the upgrade. I cannot for the life in me understand why the master is still currently yielding redirects on the front-end login page. I create an account just fine on the front-end, but logging in simply loops me over and over with each login attempt afterwards without any visible error messages on the login page.

**Comment by Pelham81** [comment]
Also, I want to add, that on the admin side I get logged out unusually often combined with the issue for the login on the front-end.

**Comment by straightlight** [comment]
`without any visible error messages on the login page.`

There were also recent posted topics on the forum reporting this issue as well regarding intermittent logged out sessions but none of them were, yet, able to provide their recent error / access logs. Since no error messages are indicated on the login screen, can you provide the most recent access logs regarding the index 302 from your webserver?

**Comment by straightlight** [comment]
When I think of it, the intermittent issue for the login and logout might be related to this issue as well" https://github.com/opencart/opencart/issues/6236#issuecomment-348637910 . When the session ID needs to be written, it might be possible due to storage access limitation by its location and its set of permissions that the session ID might not be able to update.

**Comment by Pelham81** [comment]
Here, is the log part that is pertaining to creating/registering an account and then logging in with it. I changed the domain for my privacy.

24.188.166.239 - - [30/Nov/2017:17:48:51 -0700] "POST /main/index.php?route=account/register HTTP/1.1" 302 - "http://private.com/main/index.php?route=account/register" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
24.188.166.239 - - [30/Nov/2017:17:48:52 -0700] "GET /main/index.php?route=account/success HTTP/1.1" 200 17685 "http://private.com/main/index.php?route=account/register" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
24.188.166.239 - - [30/Nov/2017:17:48:55 -0700] "GET /main/index.php?route=account/account HTTP/1.1" 302 - "http://private.com/main/index.php?route=account/success" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
24.188.166.239 - - [30/Nov/2017:17:48:55 -0700] "GET /main/index.php?route=account/login HTTP/1.1" 200 18645 "http://private.com/main/index.php?route=account/success" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
24.188.166.239 - - [30/Nov/2017:17:49:07 -0700] "POST /main/index.php?route=account/login HTTP/1.1" 302 - "http://private.com/main/index.php?route=account/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
24.188.166.239 - - [30/Nov/2017:17:49:07 -0700] "GET /main/index.php?route=account/account HTTP/1.1" 302 - "http://private.com/main/index.php?route=account/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
24.188.166.239 - - [30/Nov/2017:17:49:07 -0700] "GET /main/index.php?route=account/login HTTP/1.1" 200 18645 "http://private.com/main/index.php?route=account/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"

**Comment by straightlight** [comment]
No problem for the domain name privacy. Although, there are no account/logout listed in those logs but I do see two constant 302 indexes as a temporary redirect. Can you confirm if your storage folder is outside of your public_html / www / htdocs folder from your FTP and with recursive permission setting writable over the storage folder and also configured in your config.php and admin/config.php file or the storage folder is the storage folder still inside the store within the system folder?

**Comment by Pelham81** [comment]
I can't login. When you enter the username and password it simply refreshes the login in page again (hence, the loop/redirect back to same page). It doesn't log me in to begin with, so that's why there is no logout.

I will look at the storage folder, but I always kept it in the root directory (not in the public_html)

**Comment by straightlight** [comment]
I see. Are you using any extensions that also amended modifications to be made to the .htaccess file? If not, is your site using SSL? If yes and without proper configuration from .htaccess as well as in the config.php and admin/config.php along with the storage folder outside public_html folder, they all need to work together in order to avoid loop redirections.

**Comment by Pelham81** [comment]
Again, all this works in 3.0.2.0 - it's not working correctly on installs of master updates that I've recently tested though. Storage folder permissions are fine - yes. My config and admin config files have the proper https - yes. I have never needed to do anything to the .htaccess file though except change the base directory from "/" to "/foldername" since I install opencart in it's own folder usually and remove the .txt extension from it of course.

Thank you for pointing out SSL things though here. My site uses SSL but it doesn't show as trusted anymore so it's not picking up the SSL correctly I guess. It could be a culprit perhaps of the recent SSL changes?

**Comment by straightlight** [comment]
`It could be a culprit perhaps of the recent SSL changes?`

If there were recent changes to the SSL and your site does not show as trusted anymore even with properly configured settings in your config.php and admin/config.php file and manually query the HTTPS on the browser, then it could be an issue with SSL. If you revert the SSL parameters in your config.php and admin/config.php files and then try to login again after clearing the cache, are you then able to login?

**Comment by Pelham81** [comment]
I am *not* talking about my SSL changing. I was referring to OpenCart's code changes pertaining to SSL. Those are the recent changes.

**Comment by straightlight** [comment]
There has been recent changes to the SSL parameters on the master files.  Download a fresh copy on the opencart.com website of the latest release (v3.0.2.0) and see on another folder with a fresh database if the redirection login issue persists.

**Comment by Pelham81** [comment]
C'mon man.... I just told you several times that IT WORKS IN 3.0.2.0 - LOL?!

I am posting here thinking there is some sort of a bug that it's NOT working in the latest master updates!!

**Comment by straightlight** [comment]
I see. Well, since you provided a bad input by trying to help you here, you're on your own.

**Comment by danielkerr** [comment]
ur not supoposed to post in here. its for developmentr of opencart not your own Q&A. your issue is with your server not opencart the script.

**Comment by Pelham81** [comment]
If it matters to you at all, the issue was with this line that got added in the php.ini file on the master updates after 3.0.2.0:

session.cookie_lifetime = 3600;

I've read on numerous forums that on many browsers (this includes recent-upgraded browsers), there is a known misconfiguration with this setting that can exist, and it's implemented usually with heavier coding. Hope this thread helps: https://github.com/expressjs/session/issues/360

I feel like you maybe should commented out at least and give the user the option for it (or they can set it themselves in their cpanel) as a friendly suggestion.

**Comment by ADDCreative** [comment]
@Pelham81 If you are using the latest php.ini from the master branch. Make sure you also have this commit https://github.com/opencart/opencart/commit/daaa9b6113d51fcaf53fd2c11ede32abb51021b0 (and this which just removes the testing code https://github.com/opencart/opencart/commit/10b48f64e2b64ac843df8a26a7ef9b195d0c23e2#diff-d1ba578f44c95086346f44768a443dba). Otherwise the cookie could have the wrong lifetime.
