### ISSUE TITLE
opencart upgrade gives theme error

### ISSUE THREAD

**Issue by hazasaad** [opencart/opencart#6244]
my website shows --->Error: A theme has not been assigned to this store!
admin page was working but extension option missed and settings are permission denied

**Comment by danielkerr** [comment]
its telling you what tro do! not an eror! when u can fix it with saving the settings

**Comment by hazasaad** [comment]
i cant  save the settings..permission denied..

**Comment by danielkerr** [comment]
Then add this user groups

**Comment by hazasaad** [comment]
i cant add anything  in user group....i tried to select all option in permission but that was denied..

**Comment by danielkerr** [comment]
thats got nothing to do with the upgrade system!

empty your user group table via phpmyadmin then copy and paste the permissions text from the installer

**Comment by danielkerr** [comment]
FYI this is not the area for support!

**Comment by danielkerr** [comment]
dont post here again. use the forums.
