### ISSUE TITLE
rounding error

### ISSUE THREAD

**Issue by alexparker70** [opencart/opencart#6245]
all my products do not show decimals in the prices, it is only rounded up or down to the nearest whole number. for instance 5.5000 is rounded up to 6, 0.25 rounded down to 0. 

Have I forgotten to do something with the setup of the shop or do I need to do something with the code? Has anyone else had this problem?

**Comment by alexparker70** [comment]
Thanks for the help

**Comment by danielkerr** [comment]
This us not a support area! Use the forum or contact my stafg
