### ISSUE TITLE
Is this an issue?

### ISSUE THREAD

**Issue by manishbathla** [opencart/opencart#6248]
I can apply for return of a product without even buying it.

1. First, I log in to my account purchase a product.
2. I goto my account > order history > order information and then I apply for a return.
3. The URL in the address bar is this "http://localhost/opencart/index.php?rou ... duct_id=41"
4. I replace the product_id=41 with product_id=33, and select reason for return as "Received Wrong Item" and hit submit.
5. I then am taken to "http://localhost/opencart/index.php?rou ... rn/success" with the message "Thank you for submitting your return request. Your request has been sent to the relevant department for processing."
6. I open the admin panel and the request for return is sitting on the product return list.

Product 41 was an iMac that I bought and returned a Samsung SyncMaster 941BW which I never purchased. Look into it and let me know.

**Comment by straightlight** [comment]
It is quite harden being amended to look into 'it' while no OC version has been submitted with the request.

**Comment by straightlight** [comment]
A topic has now been created on the forum in order to force redirection to the account/return/info page whenever a user attempts to change a value on the URL as you described: https://forum.opencart.com/viewtopic.php?f=201&t=200184&p=705802#p705802

**Comment by danielkerr** [comment]
use your brain!

**Comment by manishbathla** [comment]
@straightlight, thank you, buddy 👍 ... I'll look into it.
@danielkerr, I'll do.
