### ISSUE TITLE
3.0.2.0 displays incorrect language strings 

### ISSUE THREAD

**Issue by NikosTsil** [opencart/opencart#6250]
```
'controller/*/after'  => array(
   'event/debug/after'
)
```
in
`system/config/catalog.php` (lines 62-64)
causes incorrect language strings to appear in the wrong places. eg:
"Gift certificates" instead of "Shopping cart" in checkout/cart,
"Your shopping cart is empty" instead of "There are no products to list in this category" in product/category,
"Account" instead of "Order history" in account/order

and lots of other places. Can be fixed by commenting out the aforementioned code.

**Comment by AlexChanHK** [comment]
Fixed in the latest developing version already,
therefore **this issue can be closed.**
