### ISSUE TITLE
Update currency have small issue in localhost

### ISSUE THREAD

**Issue by AlexChanHK** [opencart/opencart#6252]
Daniel
I had read the commit of updating currency some days before.
However, I found that the system is not able to update the currency in localhost, it should due to SSL issue.

I had tried to fix in two way.
I think we should add this curl setting in fixer as currency data is not sensitive data
[\admin\controller\extension\currency\fixer.php](https://github.com/opencart/opencart/blob/master/upload/admin/controller/extension/currency/fixer.php#L85)
`curl_setopt($curl, CURLOPT_SSL_VERIFYPEER,0);`
or should we edit the url with http only.
`curl_setopt($curl, CURLOPT_URL, 'http://api.fixer.io/latest?base=' . $default);`

As I am not sure which one is more suitable for us, I did not commit any push request.

**Comment by danielkerr** [comment]
added in last comit
