### ISSUE TITLE
Can't view in maintenance mode with different session name

### ISSUE THREAD

**Issue by g-rodigy** [opencart/opencart#6256]
If set a different session name for admin and customer and on maintenance mode, we can't see the site  logged as admin. There will always be a page of maintenance.

**Comment by danielkerr** [comment]
i think th esession is the same. so only if you chnage it doe the issue happen. not opencarts fault@

**Comment by g-rodigy** [comment]
You left the opportunity to change the name of the session in the config file, but don't take care of working together different sessions for the admin and customer (this happen only in maintenance mode)

**Comment by danielkerr** [comment]
Don't change it . The config files are there for using open cart as a framework.

**Comment by danielkerr** [comment]
Don't post this stupid crap,!! What do u expect will happen when u change code!
