### ISSUE TITLE
Order recurring status mismatch

### ISSUE THREAD

**Issue by yodapt** [opencart/opencart#6260]
**admin/model/sale/recurring.php**

> 
	switch ($status) {
		case 1:
			$result = $this->language->get('text_status_inactive');
			break;
		case 2:
			$result = $this->language->get('text_status_active');
			break;

**admin/language/en-gb/sale/recurring.php**

`$_['text_status_1']                        = 'Active';`
`$_['text_status_2']                        = 'Inactive';`

**Comment by JesseOC** [comment]
Thanks for reporting, we will confirm it is mismatch or not.

**Comment by Felix-Ho** [comment]
@yodapt The status not using model file to retrieve.

File : admin/controller/sale/recurring.php  Line:137
$results = $this->model_sale_recurring->getRecurrings($filter_data);
		foreach ($results as $result) {
			if ($result['status']) {
				$status	= $this->language->get('text_status_' . $result['status']);
			} else {
				$status = '';
			}
.........

First we get recurring detail as $result array and one column call status inside the $result.
Then language is loading by foreach loop of $result['status']

Also, I search through the system and did not find any file using the method
$this->model_sale_recurring->getStatus();

I will try contact James to confirm if the method is not using anymore.
