### ISSUE TITLE
3.0.2.1b install -  Class 'Controllerinstallstep3' not found

### ISSUE THREAD

**Issue by szyryanov** [opencart/opencart#6261]
File upload/install/controller/install/step_3.php is empty.

Install produces the following error:

Fatal error: Class 'Controllerinstallstep3' not found in C:\OpenServer\domains\oc3021b\www\system\engine\action.php on line 71

**Comment by danielkerr** [comment]
working on it now.

**Comment by szyryanov** [comment]
The file still be empty: https://github.com/opencart/opencart/blob/master/upload/install/controller/install/step_3.php

The same error occurs.
