### ISSUE TITLE
[v3.0.2.0 - Fix] - install/model/upgrade/1006.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6265]
User confirms the provided fix is working for foreach loop issues from 1006.php file: https://forum.opencart.com/viewtopic.php?f=199&t=200455&p=707070#p707045

**Comment by Felix-Ho** [comment]
@straightlight Thanks for reporting the upgrade issue. We have tested fresh OC 1.5.6.4 to perform upgrade and it's working fine. So, we will contact the forum issue reporter to get more detail and investigate the issue. Let's close this issue first.

**Comment by straightlight** [comment]
I don't know why this post has been closed. Although, what the facts demonstrates from the first post is regarding the error messages that has been posted by the OP on the Opencart forum during the upgrade.

May be, on your end, the upgrade process went fine. Although, it does not mean that the issue could not be recreated in this case since an error message has been posted on the forum by the poster which my corrections did avoid the user on seeing the same error message afterwards.
