### ISSUE TITLE
v. 3.0.2.0 Modify address book - ERROR 500

### ISSUE THREAD

**Issue by sifisk** [opencart/opencart#6273]
Hello,
i am using opencart v.3.0.2.0 and when i am logged in like a customer and i am trying to modify address i get "ERROR 500".

Could you help me?
Thank you.

**Comment by pemaier** [comment]
Hello sifisk.
I was testing this under php 5.6 and 7.1 and I do not get this error.
You can test this by yourself at [http://demo.opencart.center/demo/shop-302](http://demo.opencart.center/demo/shop-302)

**Comment by straightlight** [comment]
Error 500 is not caused by a platform. It is a server restriction issue. These issues should rather be posted on the opencart.com 's forum to rectify the issue.
