### ISSUE TITLE
[master] Language is not changing

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6275]
I have the current master version installed and have 3 languages configured.
If I like to change from English to a other language it is not working. (May you are working on it.)
The link has appended e.g. '&language=de-de'.
![language-screenshot](https://user-images.githubusercontent.com/10166095/34234479-6aa9b70e-e5fc-11e7-9b48-c2a892119c04.png)

**Comment by Felix-Ho** [comment]
@pemaier bug confirm. Thanks for reporting it to us and we will check the core file and fix it asap.

**Comment by straightlight** [comment]
By using the currency change from the common folder, since it uses the same type of coding, perhaps this issue could be reproduced on the currencies as well.

**Comment by danielkerr** [comment]
im in the process of updating it. thats why its broken.
