### ISSUE TITLE
Admin sale order stock notifications missed sometime

### ISSUE THREAD

**Issue by rupi8803** [opencart/opencart#6277]
Dear Friends,
I am noticing an issue with Opencart admin sale order section.
When I edit sale order, some products that exceed stock, show a warning (Products marked with *** are not available in the desired quantity or not in stock! ). 
Surprise to see, stock notification sometime disappears even no change in quantity. With refresh button again notification appear.
Will wait for your quick response.

Thank You,
Rupinder Singh

**Comment by straightlight** [comment]
No OC version posted with declared issue.

**Comment by rupi8803** [comment]
@straightlight 
Opencart 2.2.0.0

**Comment by rupi8803** [comment]
Can you please help me to get out of it
