### ISSUE TITLE
PayPal IPN notice

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6278]
It seem there is a PayPal IPN notice that requires changes by June 2018. Forum: https://forum.opencart.com/viewtopic.php?f=185&t=200622

**Comment by Felix-Ho** [comment]
All paypal module built-in from opencart are support using SSL/TLS1.2 on the store.
It's a notice for store merchant to know they have to start using SSL/TLS1.2 if they would like to use paypal.
