### ISSUE TITLE
[master] Administration Customer - Login-into-store  - Stores has always store_id=0

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6280]
This issue returned as described in #5941

**Comment by straightlight** [comment]
I do notice something odd in the admin/controller/customer/customer.php file - > login() method. Obviously, there are two causes being found, in this case:

1 - The store database table that should exist in the install/opencart.sql file from the master files cannot contain a store ID of 0 since, by default, there are no definition during the installation that this table 'should' contain a store ID of 0 (which is normal). However, the following code in the admin/controller/customer/customer.php file:

`if ($store_info) {
				$this->response->redirect($store_info['url'] . 'index.php?route=account/login/token&email=' . urlencode($customer_info['email']). '&login_token=' . $token);
			} else {
				$this->response->redirect(HTTP_CATALOG . 'index.php?route=account/login/token&email=' . urlencode($customer_info['email']) . '&login_token=' . $token);
			}`

indicates that if the matched store ID cannot be found, the store ID will be discarded and instead being replaced with a login token (which is fine). Although, in catalog/controller/startup/startup.php file has this query:

`if (isset($this->request->get['store_id'])) {
			$this->config->set('config_store_id', (int)$this->request->get['store_id']);
		} else if ($query->num_rows) {
			$this->config->set('config_store_id', $query->row['store_id']);
		} else {
			$this->config->set('config_store_id', 0);
		}`

which means if all fails for store detections, the store_id is ... "zero" ( 0 ). The logic used in this case is not invalid but simply lacks regarding the customer's login when needed as something seem to have been overthought or not enough since, again - obviously - the store ID will likely be set to the default store ID value.

**Comment by pemaier** [comment]
In my case the database table oc_store is present with the following entry.
![6280-db-table-store](https://user-images.githubusercontent.com/10166095/34328357-2147c728-e8ee-11e7-9afe-c14955db3bab.png)

If I open Store II from the admin top menu it is working fine. Link is correct.
If I open Store II from Customer list with a profile it is always opening the default store (0). Also the link with the different domain is wrong. Instead of ..//demo1.opencart.center/... for Store II is ..//demo.opencart.center/... in the link for the default store.

Also the function 'Use Shared Sessions' in Settings/Server is not working. If I open a user profile in the default store and change the link to Store II I get forwarded to the login page.

I hope the additional information helps you.

**Comment by straightlight** [comment]
I did noticed a store URL format issues on two twig files you are currently using. See if this solution will rectify the issue: https://github.com/opencart/opencart/issues/6287

**Comment by vivek-webkul** [comment]
#6989 Customer login in multiple store issue resolved from the admin end.

**Comment by pemaier** [comment]
I was testing today and it is not working with more than 2 stores -
only store0 and store1.
Also there is a 2nd point. The following user (table entry) is not
working at all.

INSERT INTO `oc_customer` (`customer_id`, `customer_group_id`,
`store_id`, `language_id`, `firstname`, `lastname`, `email`,
`telephone`, `fax`, `password`, `salt`, `cart`, `wishlist`,
`newsletter`, `address_id`, `custom_field`, `ip`, `status`, `safe`,
`token`, `code`, `date_added`) VALUES ('2', '1', '0', '2', 'Demo',
'User', 'demo@user.host', '+1-234-5678901', '',
'$2y$10$ccmeQnp6rbBz4xxxFTKsqelfxxx6DJQDbTpokTSz7kJFyo.oA9K1K', '', '',
'', '0', '5', '[]', '37.144.89.61', '1', '0', '', '', '2018-08-14
14:22:56');


-----Original Message-----

Date: Tue, 30 Oct 2018 06:38:42 -0700
Subject: {Disarmed} Re: [opencart/opencart] [master] Administration
Customer - Login-into-store  - Stores has always store_id=0 (#6280)
Cc: pemaier <peter.maier@level4.de>, Author <author@noreply.github.com>
To: opencart/opencart <opencart@noreply.github.com>
Reply-to: opencart/opencart <reply+009b1f4ff5e173dbe16e8cfedcd28855a824
a86313e81d8392cf0000000117f020e292a169ce10f26948@reply.github.com>
From: Vivek Sharma <notifications@github.com>
#6989 Customer login in multiple store issue resolved from the admin
end.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c554
93e4bb","name":"GitHub"},"entity":{"external_key":"github/opencart/open
cart","title":"opencart/opencart","subtitle":"GitHub
repository","main_image_url":"https://assets-cdn.github.com/images/emai
l/message_cards/header.png","avatar_image_url":"https://assets-
cdn.github.com/images/email/message_cards/avatar.png","action":{"name":
"Open in
GitHub","url":"https://github.com/opencart/opencart"}},"updates":{"snip
pets":[{"icon":"PERSON","message":"@vivek-webkul in #6280: #6989
Customer login in multiple store issue resolved from the admin
end."}],"action":{"name":"View
Issue","url":"https://github.com/opencart/opencart/issues/6280#issuecom
ment-434303377"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/opencart/opencart/issues/6280#issuecommen
t-434303377",
"url": "https://github.com/opencart/opencart/issues/6280#issuecomment-4
34303377",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [opencart/opencart] [master] Administration Customer -
Login-into-store  - Stores has always store_id=0 (#6280)",
"sections": [
{
"text": "",
"activityTitle": "**Vivek Sharma**",
"activityImage": "https://assets-cdn.github.com/images/email/message_ca
rds/avatar.png",
"activitySubtitle": "@vivek-webkul",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\":
\"opencart/opencart\",\n\"issueId\": 6280,\n\"IssueComment\":
\"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/opencart/opencart/issues/6280#issuecomment-4
34303377"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\":
288290346\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by vivek-webkul** [comment]
@pemaier - I already fixed the issue related to customer login in the multiple store. Please wait till PR acceptance.
