### ISSUE TITLE
Edit sale order stock notifications missed sometime in opencart

### ISSUE THREAD

**Issue by rupi8803** [opencart/opencart#6291]
I am noticing an issue with Opencart admin sale order section.
When I edit sale order, some products that exceed stock, show a warning (Products marked with *** are not available in the desired quantity or not in stock! ).
Surprise to see, stock notification sometime disappears even no change in quantity. With refresh button again notification appear.
Will wait for your quick response.

Opencart Version : 2.2.0.0

**Comment by straightlight** [comment]
Old version of Opencart.
