### ISSUE TITLE
ERROR CUSTOM FIELDS REQUIRED

### ISSUE THREAD

**Issue by Samindu** [opencart/opencart#6293]
When creating a custom field in the account and put it as mandatory fill even informing data in the field it informs that there is no typed data.

**Comment by JesseOC** [comment]
If you have any question about using the OpenCart system, you can send a ticket to the Support team for help.
https://www.opencart.com/index.php?route=support/contact

**Comment by Samindu** [comment]
Thank You Very Much.

**Comment by straightlight** [comment]
`If you have any question about using the OpenCart system, you can send a ticket to the Support team for help.
https://www.opencart.com/index.php?route=support/contact`

Then, I presume the Opencart forum has been created for decoration purposes. It would seem in some countries that Christmas and / or new years eve can be celebrated more than once in a year.
