### ISSUE TITLE
[v3.0.2.0 - Possible Fix] - admin/model/extension/openbay/openbay.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6295]
Recently, the SSL links on the Code tab have been restructured by using the $this->url->link . Although, in admin/model/extension/openbay/openbay.php file, the following code still checks for SSL links when initiating a CURL connection:

`
		if (substr(HTTP_CATALOG, 0, 5) == 'https') {

			$defaults[CURLOPT_PORT] = 443;

		}
`

**Comment by jamesallsup** [comment]
Yep this can just be dropped completely, no need to force 443 for SSL as the user may not even be running on that port. CURLOPT_URL is fine to handle the protocol it wants and by the sounds of it should handle custom ports on it fine too. Our build server doesn't use 80/443 so I'll verify on that now. Fraudlabs module had the same too.

The payment gateways can be left as-is as they are all external connections to a remote service which is safe to assume they will be running 443 - if not then that would have been picked up at initial development.
