### ISSUE TITLE
Worldpay checkout 'Confirm Order' button not working

### ISSUE THREAD

**Issue by fletchersplace** [opencart/opencart#6297]
Just installed opencart 3 and enabled worldpay online in test mode. After filling credit card details the button displays no entry on hover.
If I leave cursor in CVC box and press return I get the order complete page and details are stored on worldpay online dashboard.
Is this something I am doing wrong or is it a bug?
Thanks for your help.

**Comment by paul-godfrey** [comment]
I have this same issue. The v3.020 WorldPay plugin didn't work at all and didn't generate any webhooks. I used the updated files from here: https://github.com/opencart/opencart/issues/5778

webhooks are then generated, but i get the same issue with an inactive submit button.

I know my worldpay account is OK as it's running an OpenCart v2 store perfectly well.

**Comment by straightlight** [comment]
When the webhooks are generatd and when the submit button is inactive, use the Developers Kit on your browser by hitting the function key: F12. Go to the console tab and see if there are error messages appearing at this particular time.

**Comment by paul-godfrey** [comment]
Hi 
Just tried this.
The worldpay extension isn’t giving any errors in the console. I’ve checked worldpay.twig and it already has the select tag code as highlighted by Daniel. 
The commit button is persistently inactive.

**Comment by miklcct** [comment]
I debugged the Javascript and found out that the button is disabled in worldpay.twig:88 

        // disable new card form if existing cards
    {% if not existing_cards %}
    	        $('#payment-new-form :input').prop('disabled', true);
    {% endif %}

I suspect that the condition is inversed.
