### ISSUE TITLE
[v3.0.2.0 - Issue] - Master files since removal of SSL triggers

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6300]
A forum user has provided feedback regarding the testing and the removal of the SSL triggers from the $this->url->link . User confirms that from opencart.com 's download, compared to the master files, the SSL is properly working: https://forum.opencart.com/viewtopic.php?f=202&t=200789&p=709071#p709067

**Comment by JesseOC** [comment]
Master files in Github are the developing version, it should not be included the latest (launch) version of OpenCart.
We are trying to upgrade the system in GitHub but not launch it here. Thank you.
