### ISSUE TITLE
Urgent opencart 2200 autoupdate currency yahoo not working

### ISSUE THREAD

**Issue by karthickeyang** [opencart/opencart#6305]
showing below message when i print ,
It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.

Is there any Solutions?

**Comment by karthickeyang** [comment]
Got Solutions from a opencart forum.
https://forum.opencart.com/viewtopic.php?f=10&t=200765&p=708722&hilit=yahoo#p708722

**Comment by akilawickramasekara** [comment]
Try Using google currency converter. You have to change the refresh method in localisation model
Refer : [http://allhtaccess.info/opencart-currency-refresh-not-working/](http://allhtaccess.info/opencart-currency-refresh-not-working/)
