### ISSUE TITLE
No documentation on API

### ISSUE THREAD

**Issue by OuTopos** [opencart/opencart#6308]
Correct me if I'm wrong but there is some sort of API implemented in OpenCart as of version 3.0.2.0.
At least there is something here Admin -> System -> Users -> API.

I can not find anything about it in the documentation except for an empty page (http://docs.opencart.com/system/users/api/)

What is this API?
Shouldn't there be documentation on it?

**Comment by danielkerr** [comment]
already added the issue here

https://github.com/opencart/opencart/issues/5095
