### ISSUE TITLE
worldpay extension issue on 1.9

### ISSUE THREAD

**Issue by danceleisure** [opencart/opencart#6310]
Hello
we have recently updated our site to 1.9 on magento the worldpay extension was working perfectly on 1,7 but now at checkout the payment page will not open or do anything after the shipping method has been chosen.
Any ideas for solution?
Thank you

**Comment by danceleisure** [comment]
Hi

Why was this closed ?

Thank you 
Lisa

**Comment by danielkerr** [comment]
Use ur brain. This is the opencart project not fucking magento!  Idiot

**Comment by danceleisure** [comment]
Don’t think there is any need to be so rude
Hope you don’t need help one day or make a mistake as karma is a bitch 
Idiot
