### ISSUE TITLE
 Division by zero in currency.php on line 141

### ISSUE THREAD

**Issue by zoulou101** [opencart/opencart#6314]
hello, sind this morning I suddenly have this error when I log into the admin panel, even when I even restore backups from older dates, is suddenly this error, any idea how to solve this?

opencart 3.0.2.0
![error](https://user-images.githubusercontent.com/10242412/34639177-e5601264-f2da-11e7-91c4-52fabf9e7de1.jpg)

Warning: Division by zero in /home/cyanda/OP3020.cyanda.be/admin/model/localisation/currency.php on line 141Warning: Division by zero in /home/cyanda/OP3020.cyanda.be/admin/model/localisation/currency.php on line 141

**Comment by danielkerr** [comment]
there is a fix int he forums. u need to update the currency system as yahoo has now blocked it.
