### ISSUE TITLE
Opencart 3.0.2.0

### ISSUE THREAD

**Issue by lehaxe** [opencart/opencart#6317]
Fatal error: Class 'Twig_Extension_DTwigManager' not found in /home/gutdbdpd/ocartdata/storage/modification/system/library/template/twig.php on line 52

**Comment by straightlight** [comment]
Can you provide the detailed steps you did in order to obtain this error message?

**Comment by lehaxe** [comment]
i install that "Lazy-Load-Images" plugin, and after that I click that "reload cache" button.

site https://swiftboard.ru, I can give to your ftp access. my facebook/lehaxe1

**Comment by JesseOC** [comment]
@lehaxe Is it the extension download from OpenCart Marketplace?
If yes, would you please send the ticket to our support team, so we can try to help you check this problem.

**Comment by mohammedenaya** [comment]
Im facing the same problem , I installed an extension from the marketplace and all of a sudden it shows

Fatal error: Class 'Twig_Extension_DTwigManager' not found in /home1/hamza/storage_1/modification/system/library/template/twig.php on line 52
