### ISSUE TITLE
3.0.2.0 In multi language Store, e-mails sent to customers are just possible in default language

### ISSUE THREAD

**Issue by sazpurua** [opencart/opencart#6318]
This is a multilanguage store. The Admin panel's language is set as English, but store has 2 language options (english and spanish).
But all the emails regarding credit and rewards sent by the system to all customers, regardless of their default address, is always in english.
Is this a feature lack of OpenCart? Just able to send those emails in only the default language?

**Comment by JesseOC** [comment]
Hi @sazpurua 
As default system, it can only able to send emails on default language.
If you need to match with different clients, you could contact your developer or our partners to build-up this function for you.

**Comment by danielkerr** [comment]
jesse!

this is not corerect! it has language ID in tghe customer table so it sends in the language set by the customer.

**Comment by danielkerr** [comment]
i will fix

**Comment by Felix-Ho** [comment]
@sazpurua : thanks for us know the issue.

We using a new way to load language from the system since last year.
Firstly, we get the language that customer using on the store and use it to create a language object from the language class.
After that content base on language code will load to the system and send it to customer.

I check transaction and reward system file which is not applying the new loading language feature yet.
We will update it asap.

Thanks again for the report.

Best Regards,
Felix

**Comment by Felix-Ho** [comment]
@sazpurua : Thanks again for your reporting.
I have fix the issue and commit it on the system.
Here is the file changes.
https://github.com/opencart/opencart/commit/bae502cd0d0004e8f91cf7ef732b2c12275c286b

if you would like to fix your store issue, you can download those file and replace it with yours.
Then it will work.

Best Regards,
Felix

**Comment by sazpurua** [comment]
Thanks Felix,

In the tree bae502cd0d I see many other files that have been updated. Are this files for versión 3.0.2.0?

Thanks

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Felix <notifications@github.com>
Enviado: Friday, January 19, 2018 5:41:26 AM
Para: opencart/opencart
Cc: sazpurua; Mention
Asunto: Re: [opencart/opencart] 3.0.2.0 In multi language Store, e-mails sent to customers are just possible in default language (#6318)


@sazpurua<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsazpurua&data=02%7C01%7C%7C7464add275df49ac9f0108d55f20d25b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636519516922026201&sdata=CyeArGpQ8KXBtV8X4cHiVlwUY6CMGHqUVL%2BqFY7vq%2Fs%3D&reserved=0> : Thanks again for your reporting.
I have fix the issue and commit it on the system.
Here is the file changes.
bae502c<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopencart%2Fopencart%2Fcommit%2Fbae502cd0d0004e8f91cf7ef732b2c12275c286b&data=02%7C01%7C%7C7464add275df49ac9f0108d55f20d25b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636519516922026201&sdata=K2Dk2ycqp1y2ji1EFYGndvNElYi6%2Bvkc5q3uswqw%2BG4%3D&reserved=0>

if you would like to fix your store issue, you can download those file and replace it with yours.
Then it will work.

Best Regards,
Felix
