### ISSUE TITLE
3.0.2.0 Gift Certificates email shows amount of gift only in default currency

### ISSUE THREAD

**Issue by sazpurua** [opencart/opencart#6319]
In a multi currency store (i.e. default USD and Euros as option), if a customer buys a gift certificate in Euros, the reciptient gets an email showing the amount in USD.

**Comment by JesseOC** [comment]
Hi @sazpurua 
Would you please send a ticket to our support team and we could help you check the problem.
https://www.opencart.com/index.php?route=support/contact

**Comment by ADDCreative** [comment]
Could be the same as issue https://github.com/opencart/opencart/pull/5298.

**Comment by Felix-Ho** [comment]
@sazpurua : Thanks for reporting to us. Issue confirmed.

![voucher](https://user-images.githubusercontent.com/6228720/35080957-eaed6c48-fc4b-11e7-92ce-f7cda8948353.png)
Voucher description price is not match with cart total.

@ADDCreative : Thanks for the fix, it's solve the issue and I will commit the fix on the master version.
