### ISSUE TITLE
[v3.0.2.0 - Issue] - library cache file.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6321]
It seem the PHP error cache library file.php is still creating error messages. The last solution provided by Daniel did not resolved the issue as a user mentions that the error message still persist after replacing the system/library/cache/file.php : https://forum.opencart.com/viewtopic.php?f=202&t=200896#p709630

**Comment by ADDCreative** [comment]
Maybe something along the lines of this may help to suppress the error if another process has deleted the file, but still detect if the file could not be deleted.

```php
if (is_file($file)) {
    if (!@unlink($file)) {
        clearstatcache();

        if (is_file($file)) {
           // Generate error here.
        }
    }
}
```
