### ISSUE TITLE
opencart 3.0.2 - SEO URL

### ISSUE THREAD

**Issue by ndecaris** [opencart/opencart#6327]
hello dev team,

i have an issue with seo URL : for product_id, it doesn't work. i'm still redirecting to home page.
i use the default htaccess file with opencart 3.0.2
please, any idea ?

nicolas

**Comment by mhcwebdesign** [comment]
SEO Urls, including for products, work just fine for OpenCart 3.0.2.0. Please post on the OpenCart forum for support, hopefully someone should be able to sort out your OC configuration for this.

**Comment by danielkerr** [comment]
I am still making changes

**Comment by ndecaris** [comment]
@mhcwebdesign : i did it, but no answers.
@danielkerr : what kind of changes about seo are you dealing with ?

**Comment by danielkerr** [comment]
because the old system only worked for certain pages. info, prods, cats
