### ISSUE TITLE
PCI DSS Vulnerability - The remote web application discloses path information - OpenCart 3.0.2.0

### ISSUE THREAD

**Issue by tmleafs** [opencart/opencart#6330]
Hi I need to pass a PCI DSS Vulnerability or my payment vendor will start charging fines. OpenCart 3.0.2.0 Fails on 4 things this is number three - Filter error messages containing path information.

**Threat:**
The remote web application discloses path information.
**Impact:**
At least one web application hosted on the remote web server discloses the physical path to its directories when a malformed request is sent to it.

Leaking this kind of information may help an attacker fine-tune attacks against the application and its backend.
**Solution:**
Filter error messages containing path information.
**Result:**

```
The request GET /index.php?to_email=&voucher_theme_id=6&to_name=&quantity=1&product_id=143&path=129&password=&information_id=4&from_name=&from_email=&firstname=&email=&date_ordered=&agree=1&amount=1&comment=&confirm=&customer_group_id=1&lastname=&message=&model=&newsletter=1&opened=1&order_id=&redirect=https%3a%2f%2fshop.wgmotorworks.co.uk%2findex.php%3froute%3daccount%2faccount&return_reason_id=4&route=information%2fcontact&telephone=&product=+and+1=0) HTTP/1.1
Host: shop.wgmotorworks.co.uk
Accept-Charset: iso-8859-1,utf-8;q=0.9,*;q=0.1
Accept-Language: en
Connection: Keep-Alive
Cookie: language=en-gb; currency=GBP; OCSESSID=4f79af550a4752742a1f230319
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)
Pragma: no-cache
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*
```

produces the following path information :

```
<b>Warning</b>: unlink(/var/www/html/storage/cache/cache.catalog.languag
e.1510326721): No such file or directory in <b>/var/www/html/shop/system
/library/cache/file.php</b> on line <b>68</b><!DOCTYPE html>
<!--[if IE]><![endif]-->
<!--[if IE 8 ]><html dir="ltr" lang="en" class="ie8"><![endif]-->
```

**Comment by ADDCreative** [comment]
It seems that version 3 has an seperate default error handler which is used before catalog/controller/startup/error.php is loaded. So as well as switching off Display Errors in the settings you need do one of the following for a production environment.

Change ```$_['error_display']``` to false in system/config/default.php.

Or add ```$_['error_display']        = false;``` to system/config/catalog.php and system/config/admin.php

**Comment by danielkerr** [comment]
and banned!
