### ISSUE TITLE
Error in Admin - Opencart 2.2

### ISSUE THREAD

**Issue by SrCosmic** [opencart/opencart#6337]
Hello,

(sorry my bad english)
I have a opencart 2.2 installed in my store... after install two extensions appear me this error in 
- 'Admin ->modules'

Notice: Undefined index: status in /home/feirados/public_html/system/storage/modification/admin/view/template/extension/module.tpl on line 79

How can I solve this problem, anyone know?

I try to unistall the extensions that you thought caused the error, but the problem remains

Best Regards
Fábio Ramalho

**Comment by ADDCreative** [comment]
You need to ask in https://forum.opencart.com/ as the error is caused by an extension. But try refreshing your modifications by going to Extension > Modifications and click the refresh button at the upper right corner.

**Comment by SrCosmic** [comment]
I try this, but error remains =(

**Comment by danielkerr** [comment]
he is not for old version of opencart. you can use our partner page for support.

**Comment by danielkerr** [comment]
resave layouts, settings, modules etc..
