### ISSUE TITLE
[3.0.2.0] Store Module not working

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6338]
I tried to use the -Store Module- but it is not working well.
I can open only open the the already active store again. Click on a other store is calling -i guess- the root domain. Here is a [sample](http://demo.opencart.center/demo/shop-303/)

**Comment by Felix-Ho** [comment]
I setup a demo multi store on my own test site with the latest version of opencart.
http://liezfh.com/
The store module work perfect on it.
So, it should not be a bug in the system which probably you have sub domain/multi store setting incorrect.
If you still have issue, please feel free to send us support request via opencart.com

**Comment by pemaier** [comment]
Thank you for the suggestion of a support request.
Additional information to the problem:
The problem is this '&session_id=' . $this->session->getId()'
If I cut the session_id out of the link it is working.
