### ISSUE TITLE
Error Modification MODULES Opencart 2.2

### ISSUE THREAD

**Issue by SrCosmic** [opencart/opencart#6343]
Hello,

I've opencart 2.2 and appear me this error:
- PHP Notice: Undefined index: status in /home/feirados/public_html/system/storage/modification/admin/view/template/extension/module.tpl on line 79

Line 79 is this:
- <td class="text-left status"><?php echo $extension['module'] ? '' : $extension['status']; ?></td>

Can Someone help me to solve this problem?

Best Regards
Fábio Ramalho

**Comment by mhcwebdesign** [comment]
This is not a bug. Please post on the OpenCart forum.
