### ISSUE TITLE
Limit Options

### ISSUE THREAD

**Issue by SrCosmic** [opencart/opencart#6344]
Hello,

I've products with option 'Medidas (em metros)' and I need add more options, but apparently I got to the end of the options...

I  asked in my hosting to change the values and restart APACHE
- php_value max_input_vars 9999
- php_value suhosin.post.max_vars 9999
- php_value suhosin.request.max_vars 9999

and add this in .htacess root

php_value max_input_vars 9999
#php_value suhosin.post.max_vars 9999
#php_value suhosin.request.max_vars 9999

but the problema remains =(

Can someone help to solve this problem?

Best Regards
Fábio Ramalho

**Comment by mhcwebdesign** [comment]
This is not an OpenCart bug. Rather something to be sorted out by your webhost.

**Comment by jamesallsup** [comment]
Yes, speak with your host.
