### ISSUE TITLE
[v3.0.2.0 - Fix] - admin/model/localisation/country.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6345]
In admin/model/localisation/country.php file,

find:

`public function deleteCountry($country_id) {
		$this->db->query("DELETE FROM " . DB_PREFIX . "country WHERE country_id = '" . (int)$country_id . "'");

		$this->cache->delete('country');
	}`

replace with:

`
public function deleteCountry($country_id) {
		$this->db->query("DELETE FROM " . DB_PREFIX . "country WHERE country_id = '" . (int)$country_id . "'");

$this->db->query("DELETE FROM " . DB_PREFIX . "zone WHERE country_id = '" . (int)$country_id . "'");

$this->db->query("DELETE FROM " . DB_PREFIX . "zone_to_geo_zone WHERE country_id = '" . (int)$country_id . "'");

		$this->cache->delete('country');
	}`

Otherwise, people will still be able to use shipping modules for unauthorized zones with previous country ID and zone ID when the geo zone ID is not defined from the SQL query or when it's not implied to it.

**Comment by Felix-Ho** [comment]
Before run the delete country method, validateDelete will check any store, address, zone, geo zone is applying to this country_id. So, user have to remove/update the links  from store, address, zone, geo zone before they delete the country.

**Comment by straightlight** [comment]
If so, then the deleteCountry method doesn't explain on why each country ID can be deleted despite the store ID associated with.

**Comment by Felix-Ho** [comment]
Sorry, I am not sure what do you mean.

I have set Aaland Islands as default country from store setting.
Then trying delete it from the system > localisation > country
and it showing the warning.
![country](https://user-images.githubusercontent.com/6228720/35078331-bb9ecb08-fc3c-11e7-8399-f3ce12909c63.png)
So, it's been checking before the country delete.

**Comment by danielkerr** [comment]
dont add this. i know its quicker but can mess things up
