### ISSUE TITLE
Changing languages on Store are not Working - V3.0.2.1b

### ISSUE THREAD

**Issue by webcorvo** [opencart/opencart#6347]
Hi,

On the Store are not changing the languages, on the BO works fine.
 V3.0.2.1b

Tks

**Comment by webcorvo** [comment]
Daniel why did you close this issue ??

**Comment by danielkerr** [comment]
Because it's being worked on.  I've been working on the SEO URLs and languages for the last 2 weeks

**Comment by webcorvo** [comment]
Ok,  sorry i did not know that.
Have a nice work
