### ISSUE TITLE
PayPal Payments Standard + Multiple large Option descriptions

### ISSUE THREAD

**Issue by SEFreeman** [opencart/opencart#6353]
PayPal Payments Standard does not work if you use multiple options with large descriptions and large answers. Paypal reports a problem with destination address and looses all order items and totals, customer can then add what they like and pay what they like. Not sure why options are going across to Paypal as it does not need them. Using Opencart v3.02, but I think this was happening on V2 as well. www.bmsgh-shop.org.uk, Midland Ancestors Membership Renewal item on homepage is an example, I have shortened option descriptions to make it work in short term.

**Comment by danielkerr** [comment]
Felix this should not happen because I'm.sure substr is used

**Comment by AlexChanHK** [comment]
Hi @SEFreeman,
Can we have an example (testing product also okay) to understand what case cause the issue exist?
If it is due to the option name is over the limit, we can teach to you edit the code to prevent it.

**Comment by ADDCreative** [comment]
There is no substr on the option name only the value. Changing the line here. https://github.com/opencart/opencart/blob/3.0.2.0/upload/catalog/controller/extension/payment/pp_standard.php#L44

To the following should work as the PayPal documentation says 64 is the maximum.
```php
'name'  => (utf8_strlen($option['name']) > 64 ? utf8_substr($option['name'], 0, 62) . '..' : $value),
```

Did a quick test with the sandbox and it seemed to fix the issue.

**Comment by danielkerr** [comment]
@AlexChanHK very easy to test. ask felix to help u set up a sandbox account. then add long product option names

**Comment by danielkerr** [comment]
maybe james alrteady fixed it. needs testing./

**Comment by Felix-Ho** [comment]
@SEFreeman I have test paypal standard which confirm the issue.

![checkout](https://user-images.githubusercontent.com/6228720/35211241-a33d97b8-ff90-11e7-820a-0cfc2e6d1682.png)

When I enter massive characters from product option name, it's get to a page allow buyer to enter product and price.
![login](https://user-images.githubusercontent.com/6228720/35211277-c6368c34-ff90-11e7-8abd-8d84cd2d0b0a.png)

I also try others such as product name, product option value which does not have the same issue.

Thanks ADDCreative for the suggestion and I have commit it to the master branch.
https://github.com/opencart/opencart/commit/74beb5aaddd468b8ea469f83162e70cda0b9e5c6

The issue can be close now.

**Comment by SEFreeman** [comment]
Hi, thanks for getting back to me, I have been sent a fix which my techie will install this week, regards, Steve
