### ISSUE TITLE
Free checkout not completing

### ISSUE THREAD

**Issue by SEFreeman** [opencart/opencart#6354]
Opencart v3. If customer orders item, then uses a coupon to pay for it and order total then becomes zero, the customer uses free checkout option, but order does not complete, goes into missing orders. Worked in V2.

**Comment by Felix-Ho** [comment]
![freecheckout](https://user-images.githubusercontent.com/6228720/35078687-5dcefc80-fc3e-11e7-8f94-7e145648acf1.png)

I run a test with 100% discount coupon and checkout with free checkout module. (Latest version of opencart)
Everything works fine and order can be placed and order status as pending which I set it on the system setting.
So, it should not be a bug from the system.

if you still have issue, would you mind please send us a support ticket on 
https://www.opencart.com/index.php?route=support/contact
and our support team will help you check if that's your setting/extension issue.

Hope this help!
