### ISSUE TITLE
Update 3.0.2.0 to 3.0.2.1

### ISSUE THREAD

**Issue by stas730** [opencart/opencart#6355]
I want to install OpenCart website but there are some issues in 3.0.2.0, fixed here. 3.0.2.0 release must be updated ASAP.

**Comment by Felix-Ho** [comment]
If you would like to use opencart as your store shopping cart system.
Please try download the system from
https://www.opencart.com/index.php?route=cms/download
Which is the stable and recommended version.
The github one is a development version for next version.

If you still have issue from using opencart, please send us support ticket on 
https://www.opencart.com/index.php?route=support/contact
This report section mainly focus on system bug reporting hope you understand :-)
