### ISSUE TITLE
eWay OpenCart 3.0.2

### ISSUE THREAD

**Issue by struddysit** [opencart/opencart#6358]
I have a fresh install of OpenCart 3.0.2, and we use eWay as our payment gateway.
Once configured, I tried to put a test payment through, which was met with:

"This payment gateway is currently being tested. Your credit card will not be charged. If this is a real order, please use an alternate method of payment at this time."
( text string for $_['text_testing']	 in catalog/language/en-gb/extension/payment/eway.php )

No Credit Card details input fields were shown either. I thought that perhaps the payment module was being set to Testing mode, even though it was set to off. Debugging these files found that that was not the case.

I believe I have found the issue in the catalog/view/theme/default/template/extension/payment/eway.twig file. Now I'm not that familiar with Twig, but I suspect there are the following issues with this file:

Issue 1 - No Credit Card input fields:

Line 42:
    {% if payment_type.visa == 1 and payment_type.mastercard == 1 and payment_type.diners == 1 or payment_type.jcb == 1 or payment_type.amex == 1 %}
Should be:
    {% if payment_type.visa == 1 or payment_type.mastercard == 1 or payment_type.diners == 1 or payment_type.jcb == 1 or payment_type.amex == 1 %}

I had Visa and Mastercard enabled, but not Diners, so the bug was caused by using "and" instead of "or" in the if statement, causing no credit card inputs to show up for me.

Issue 2 - Testing mode always enabled:
Now, as mentioned, I debugged the controllers and could not find any instance of $data["text_testing"] actually being set. I suspect this if statement is hitting the "text_testing" field in the language file, rather than looking for it in $data. To this end, In catalog/controller/extension/payment/eway.php I changed Line 34 from: 
   $data['text_testing'] 
to 
    $data['text_testing_mode']
And in the TWIG file I changed Line 8 from:
    {% if text_testing %}
to 
    {% if text_testing_mode is defined %}

The error_log also stated :
"PHP Fatal error:  Uncaught exception 'Twig_Error_Syntax' with message 'Unexpected "endfor" tag (expecting closing tag for the "if" tag defined near line 43) in "default/template/extension/payment/eway.twig" at line 68.'" 

So I believe that 

Line 62: 
	% for month in months %} 
Should be:
	{% for month in months %}

Line 77:
	% for year in year_expire %}
Should be:
	{% for year in year_expire %}

I also changed Line 1 from:
{% if error %}
to:
{% if error is defined %}

**Comment by Felix-Ho** [comment]
@struddysit Thanks for reporting the issue and I had fixed it last year.

Twig fix
https://github.com/opencart/opencart/commit/30a05db720d8998a660c48b23930c0b930fb2722#diff-ef6cf707d822b5a778fecd53f3badb1e

https://github.com/opencart/opencart/commit/30a05db720d8998a660c48b23930c0b930fb2722#diff-d9a041a232cb5ef0ba6f160830498b3f

Test mode fix.
https://github.com/opencart/opencart/commit/40c8288d473aa248713fa7dff12cee9f0e9bfcd0#diff-d9a041a232cb5ef0ba6f160830498b3f

Also, I had developed an extension which being tested by us and eWay for existing merchant to use ocmod so that they don't need to fix the code themselves through FTP
Extension URL:
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32505&filter_license=0&page=4

Best Regards,
Felix

**Comment by struddysit** [comment]
Felix-Ho, thanks for the confirmation. Your changes were made after the latest release, so it's good to see my conclusions were the same as yours, and that they're queued for the next version. However, your fixes still don't address the issue of no credit card inputs when only Visa & Mastercard are selected. 

This line:
 {% if payment_type.visa == 1 and payment_type.mastercard == 1 and payment_type.diners == 1 or payment_type.jcb == 1 or payment_type.amex == 1 %}

Means that the credit card inputs will only show up if JCB, or AMEX or all of Visa, Mastercard and Diners are selected in the eWay module. If only one or two of Visa, Mastercard and Diners are selected, as in this instance (Visa and Mastercard), no credit card input fields will show up.

In your changes, was assigning $data['text testing'] to a blank field due to the Twig loader searching data first, followed by the actual text translations?
