### ISSUE TITLE
eWAY OpenCart 3.0.2

### ISSUE THREAD

**Issue by struddysit** [opencart/opencart#6362]
I have a fresh install of OpenCart 3.0.2, and we use eWay as our payment gateway.
Once configured, for Visa and MasterCard, I tried to put a test order through, but no Credit Card details input fields were shown. I

The issue is in the catalog/view/theme/default/template/extension/payment/eway.twig file. 

Line 42:
{% if payment_type.visa == 1 and payment_type.mastercard == 1 and payment_type.diners == 1 or payment_type.jcb == 1 or payment_type.amex == 1 %}
Should be:
{% if payment_type.visa == 1 or payment_type.mastercard == 1 or payment_type.diners == 1 or payment_type.jcb == 1 or payment_type.amex == 1 %}

I had Visa and Mastercard enabled, but not Diners, so the bug was caused by using "and" instead of "or" in the if statement, causing no credit card inputs to show up for me.

**Comment by Felix-Ho** [comment]
@struddysit : Thanks for reporting the issue.
I test and bug confirmed.

I have already fixed the issue on the master branch of opencart.
https://github.com/opencart/opencart/commit/7181f17eede1b92b9e88ecba1d9aeca669448d42

If you already using opencart as your web store.
You can install this extension to fix it.
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32505
