### ISSUE TITLE
[v3.0.2.0] Store Location missing after 2nd saving

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6364]
Situation: 
Multistore installation. Configured a 2nd Store and a Store Location. 

Problem: 
1st step - Activate in (2nd) Store the Store Location (1st time save it is activated and present in the FE )
2nd step - Change Store settings and save it. Then the Store Location is deactivated and missing in FE.
In the default store the problem is not present.

**Comment by Felix-Ho** [comment]
@pemaier Do you mean the Geocode is missing from system setting when you preform second time on saving information? I test on my testing environment which is working fine.
Would you mind send us ticket to provide your store login information so that we can check it for you?
You can send it from
https://www.opencart.com/index.php?route=support/contact

**Comment by pemaier** [comment]
Hello Felix.

I do not mean the Geocode. 
I mean the Store Location which is configured under System-
Localization-Store Location. 
This is activated in the Settings-Store(s) under the Tab Store - Store
Location(s) (end of the page) 

-----Original Message-----

Date: Tue, 23 Jan 2018 10:10:48 +0000 (UTC)
Subject: {Disarmed} Re: [opencart/opencart] [v3.0.2.0] Store Location
missing after 2nd saving (#6364)
Cc: pemaier <peter.maier@level4.de>, Mention <mention@noreply.github.co
m>
To: opencart/opencart <opencart@noreply.github.com>
Reply-to: opencart/opencart <reply+009b1f4f8337445e84482c521fc0777ba938
606242b2b2a392cf00000001167ecc2892a169ce11547e04@reply.github.com>
From: Felix <notifications@github.com>
@pemaier Do you mean the Geocode is missing from system setting when
you preform second time on saving information? I test on my testing
environment which is working fine.

Would you mind send us ticket to provide your store login information
so that we can check it for you?

You can send it from

https://www.opencart.com/index.php?route=support/contact


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



  
  





{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c554
93e4bb","name":"GitHub"},"entity":{"external_key":"github/opencart/open
cart","title":"opencart/opencart","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/asset
s/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.c
om/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/opencart/opencart"}},"updates":{"snip
pets":[{"icon":"PERSON","message":"@Felix-Ho in #6364: @pemaier Do you
mean the Geocode is missing from system setting when you preform second
time on saving information? I test on my testing environment which is
working fine.\r\nWould you mind send us ticket to provide your store
login information so that we can check it for you?\r\nYou can send it
from\r\nhttps://www.opencart.com/index.php?route=support/contact\r\n
"}],"action":{"name":"View
Issue","url":"https://github.com/opencart/opencart/issues/6364#issuecom
ment-359742531"}}}
-- 
With best regards / Mit freundlichen Grüßen / С уважением

Peter Maier
