### ISSUE TITLE
unable to instal language in2.3.0,2

### ISSUE THREAD

**Issue by Gewaagemstones** [opencart/opencart#6366]
I downloaded a trusted pack of Hungarian language , FTP it to the appropriate folder. went to localisation - languages -add language. I can not write the language code respectively hu-HU because there is a dropdown menu that contains only the eanglish language code. Please help me.
![image](https://user-images.githubusercontent.com/35723493/35276193-e15c60da-0042-11e8-8049-d73f5e4b9145.png)
![opencartkep](https://user-images.githubusercontent.com/35723493/35276285-32a26bb0-0043-11e8-81ce-9a69ac223fbc.jpg)

**Comment by Gewaagemstones** [comment]
![image](https://user-images.githubusercontent.com/35723493/35276344-6122a144-0043-11e8-936e-ca30061f3380.png)

**Comment by osworx** [comment]
Clearly wrong done!
You coipied the whole package, but you should first UNZIP ist locally and copy then the content as seen.
For example you may have folllowing structure after unzipping:
upload
|- admin
|- catalog

Now, admin should go to admin, catalog to catalog.
And again, no bug in core, more the user trying to install the language package.
