### ISSUE TITLE
url class link function error (system/library/url.php)

### ISSUE THREAD

**Issue by ozkankonay** [opencart/opencart#6367]
Hi,

The http_build_query function used in the link function is incorrectly configured.

Correction should be as follows:

**Original code block:**
```
....
....
if (is_array($args)) {
    $url .= '&amp;' . http_build_query($args);
} else {
    $url .= str_replace('&', '&amp;', '&' . ltrim($args, '&'));
}
...
...
```
!this usage is wrong!
because http_build_query uses the default '&' character for parameter joining

**Solution:**
```
...
...
if (is_array($args)) {
     $url .= '&amp;' . http_build_query($args, '', '&amp;');
} else {
    $url .= str_replace('&', '&amp;', '&' . ltrim($args, '&'));
}
...
...
```

**PS: this fix is required for all versions above 2.1.0.0.**

**Comment by danielkerr** [comment]
there is no issue!
