### ISSUE TITLE
opencart v3.2 problem in stylesheet 

### ISSUE THREAD

**Issue by mohammadgholeh** [opencart/opencart#6368]
when add custom style sheet on stylesheet.css and return after 5 min add more custom style the old custom style its remove without change from anther people what the problem for that i am say the problem  from 2 days

**Comment by danielkerr** [comment]
you are not adding it in the correct place.

**Comment by ARH-Digital** [comment]
@danielkerr Where is the correct place? 
I am currently trying to see how the scss compiler is functioning, I assume that is the cause of his file been overwritten. From what I can see, you should edit /sass/_bootstrap.scss but I cannot find anything in the docs about it.
