### ISSUE TITLE
Property annotations to classes

### ISSUE THREAD

**Issue by alexey-okhorzin** [opencart/opencart#6369]
I can't go to model classes, when I developing my project. For example I want to go to class ModelCatalogCategory by click on $this->model_catalog_category property, but I can't do this, because this property don't described in the class annotation:
`/**
 * @property ModelCatalogCategory $model_catalog_category
 */
class ControllerCommonMenu extends Controller`

Please add such annotation in all classes.

**Comment by Felix-Ho** [comment]
Did you load model file in the your controller before you call it?
$this->model->load('catelog/catalog');
