### ISSUE TITLE
User enumeration possible using forgotten password feature

### ISSUE THREAD

**Issue by Shifterovich** [opencart/opencart#6373]
You can check if there's an account for an email address using the forgotten password feature. While this is not a big security issue, it's unwanted for some stores. Should always return the "email sent" message, just like login returns the same error independently on the existence of the account.

This is useful for brute force attacks -- when you're not sure *which* email the user might use, or are looking for common/leaked user:password combinations -- and a privacy issue (again, on some stores people may want to keep the existence of their account secret).

[\[1\]][1] [\[2\]][2]

[1]: https://blog.rapid7.com/2017/06/15/about-user-enumeration/
[2]: https://www.owasp.org/index.php/Testing_for_User_Enumeration_and_Guessable_User_Account_(OWASP-AT-002)

---

**Solution: Return the "email sent" message regardless of the account existing.**

Stop using this:

https://github.com/opencart/opencart/blob/92d22ee8f76afbaa50486f754bf20da9b3c24102/upload/catalog/controller/account/forgotten.php#L67-L82

Called on line:

https://github.com/opencart/opencart/blob/92d22ee8f76afbaa50486f754bf20da9b3c24102/upload/catalog/controller/account/forgotten.php#L16

**Comment by shifterovich2** [comment]
**My fix might result in an email being sent to a nonexistent email address.** I didn't want to make any significant changes apart from deleting code. Feel free to use your own fix or change my code in a PR.

**Comment by danielkerr** [comment]
no issue here! use your brain before posting this crap!

**Comment by shifterovich2** [comment]
Right, maybe consider reading the second paragraph of the issue as well.

**Comment by danielkerr** [comment]
fine

**Comment by danielkerr** [comment]
@Felix-Ho please test

**Comment by Felix-Ho** [comment]
@Shifterovich Thanks for the suggestion but in my opinion, removing the whole form validation should not be a good idea.

I have change the way of validation to the forgotten password so that same response message will show no matter user account is exist or not.
But in fact, only existing email address will trigger event and sending email.

Hope this is a better way.
https://github.com/opencart/opencart/commit/8d628a5ec7e0c3a22b4905e7ea322500efa25881

**Comment by shifterovich2** [comment]
I made a branch with a quick fix, but it only removed the validation and may result in emails being sent to nonexistent email addresses. Indeed, validating and returning the same error is the ideal solution.
