### ISSUE TITLE
Templates variables need to be escaped 

### ISSUE THREAD

**Issue by DontShootMe** [opencart/opencart#6378]
First of all, I want to thank all the members for the work they have done!
Thank you very much, it's really a great job you did!

I am a beginner with this software but, I had problems on many functionality with opencart ( version 1.5.* and 3.0.2.1b ), that was annoying.

One reproducible example in version 3.0.2.1b :

- add a translation ( i used a French translation ) where we encounter many escaped apostrophe character  '  : 
> admin/language/fr-Fr/catalog/product_option.php
```php
 $_['entry_option_value']		= 'Valeur de l\'option:' ;
```

In the template file :
> /admin/view/template/catalog/product_option_form.twig

in the Javascript section we have this part ( and many others) 
```javascript
...
html = '';

if (item['type'] == 'text') {
	html += '	<div class="form-group">';
	html += '	  <label class="col-sm-2 control-label" for="input-value">{{ entry_option_value }}</label>';
	html += '	  <div class="col-sm-10"><input type="text" name="value" value="" placeholder="{{ entry_option_value }}" id="input-value" class="form-control" /></div>';
	html += '	</div>';
}
...
```
***
As you can see, we use unescaped  `{{ entry_option_value }}` from twig, producing errors on the resulting HTML / Javascript files.

```javascript
html += '	  <label class="col-sm-2 control-label" for="input-value">{{ entry_option_value }}</label>';
```
become in the browser : 
```javascript
html += '	  <label class="col-sm-2 control-label" for="input-value">Valeur de l'option:</label>';
```

***

These errors cause the mute of every auto-complete functionality breaking down many pages.
In this precise case,  it is just impossible to use Options on products ! 

There are many cases / files where we can find this problem, and the need to carefully escape all template variables is the solution. 

Perhaps the simplest way is to use Twig escape : `{{ entry_option_value | e }}`

**Comment by Felix-Ho** [comment]
@DontShootMe Thanks for reporting to us.
I will test it today.

**Comment by LJK-opencartmods** [comment]
On my phone or id look, but would using double quotes instead of single quotes in the affected language files fix this?

In other words is it php or JavaScript that’s encountering the issue?

**Comment by Felix-Ho** [comment]
@DontShootMe I have setup test with French language option and the auto complete working fine from product option page.

![language_option](https://user-images.githubusercontent.com/6228720/35660503-50020430-0747-11e8-9430-ae717c2df1c4.png)

In the option system(admin/view/template/catalog/product_option.twig)
On the first click action on the option value field, it will fire a ajax request to 
admin/controller/catalog/option.php  -> autocomplete() method
Fetch option data from your database and passing it back to the field.
So, the language should not be the reason causing your autocomplete not working.

If you have issue from using it, please send us ticket via 
https://www.opencart.com/index.php?route=support/contact
and we will check it for you.

**Comment by DontShootMe** [comment]
Thank you for taking the time to react so quickly.
Unfortunately, you took the problem of the wrong side.

You have set up your options with text containing single quotation marks off the problem is not in what we add but directly from the templates.

to be sure to see the problem here is what, please, I ask you to do:

Modify source code of the file:
> admin / controller / catalog / product_option.php

go to the next function to edit it:
```php
protected function getForm () {...
```
go to the end of the function and paste the following code :
```php
...
     $ data ['entry_option_value'] = 'Felix-Ho\'s test ';
     $ this-> response-> setOutput ($ this-> load-> view ('catalog / product_option_form', $ data));
}
...
```
and try again, please.
In my case there is no auto-compete on the option.


![screenshot-2018-2-1 options de produit](https://user-images.githubusercontent.com/651865/35669821-a63019b6-0736-11e8-88b1-56abad851541.png)

**Comment by DontShootMe** [comment]
@ LJK-opencartmods

The problem is in the javascript part, but this javascript is written dynamically by PHP!

So, Javascript suffers from the problem made by PHP

**Comment by danijelGombac** [comment]
@DontShootMe you can try

`$_['entry_option_value']		= 'Valeur de l&apos;option:' ;`

**Comment by DontShootMe** [comment]
@danijelGombac 

Yes sure, now that i am aware of this problem i could do that, for ***this*** use case.
But in fact the problem still there because in my languages files ( translation or not ) everything are well escaped by a slash just like many files in en-gb language from source !

***
Each of this following ***en-gb admin language*** source file have a "slash escaping" :
```php 

./extension/openbay/amazon_bulk_linking.php:    $_['text_load_listings']
./extension/openbay/amazon_listing.php:         $_['help_sku']
./extension/openbay/fba_fulfillment.php:        $_['text_no_results']
./extension/openbay/amazonus_settings.php:      $_['entry_tax_percentage']
./extension/openbay/amazonus_subscription.php:  $_['text_register_invite']
./extension/openbay/fba_fulfillment_list.php:   $_['text_no_results']
./extension/openbay/amazon_subscription.php:    $_['text_register_invite']
./extension/fraud/maxmind.php:                  $_['text_signup']
./extension/payment/amazon_login_pay.php:       $_['text_ipn_url']
./extension/payment/amazon_login_pay.php:       $_['entry_ipn_url']
./extension/payment/authorizenet_sim.php:       $_['text_authorizenet_sim']
./extension/payment/cardconnect.php:            $_['help_transaction']
./extension/payment/sagepay_direct.php:         $_['entry_cron_job_url']
./extension/payment/sagepay_direct.php:         $_['entry_last_cron_job_run']
./extension/payment/laybuy.php:                 $_['help_order_status_pending']
./extension/payment/laybuy.php:                 $_['help_order_status_canceled']
./extension/payment/laybuy.php:                 $_['help_order_status_processing']
./extension/payment/sagepay_server.php:         $_['entry_cron_job_url']
./extension/payment/sagepay_server.php:         $_['entry_last_cron_job_run']
./extension/payment/klarna_checkout.php:        $_['help_api']
./extension/payment/authorizenet_aim.php:       $_['text_authorizenet_aim']
./extension/payment/pilibaba.php:               $_['error_weight']
./extension/payment/worldpay.php:               $_['entry_last_cron_job_run']
./user/api.php:                                 $_['text_ip']
./setting/store.php:                            $_['help_url']
./setting/store.php:                            $_['help_tax_default']
./setting/store.php:                            $_['help_tax_customer']
./setting/setting.php:                          $_['help_open']
./setting/setting.php:                          $_['help_tax_default']
./setting/setting.php:                          $_['help_tax_customer']
./setting/setting.php:                          $_['help_processing_status']
./setting/setting.php:                          $_['help_complete_status']
./setting/setting.php:                          $_['help_mail_engine']
./setting/setting.php:                          $_['help_mail_parameter']
./setting/setting.php:                          $_['help_mail_smtp_hostname']
./catalog/product.php:                          $_['help_points']
./marketplace/cron.php:                         $_['text_cron_1']
./marketplace/installer.php:                    $_['help_upload']
./common/column_left.php:                       $_['text_online']
./sale/voucher.php:                             $_['error_to_name']
./sale/order.php:                               $_['entry_to_name']
./sale/order.php:                               $_['entry_to_email']
./sale/order.php:                               $_['entry_from_name']
./sale/order.php:                               $_['entry_from_email']
./sale/recurring.php:                           $_['text_cancel_confirm']
./sale/recurring.php:                           $_['entry_description']
```
***

I'm sorry, but I think your proposal is not robust enough! 

This does not affect only French or a specific language, it does affect all the languages ​​in which we can meet a "slash escaping"!

***
even more if you write something like that in javascript,  it will not be converted !
```php
...
// Twig template content ...

<span>{{ entry_option_value }}</span>
// here you will have a correct value ---> Valeur de l'option:

...

<script>
    let myValue = '{{ entry_option_value }}';
    console.log(myValue); // here you will have an incorrect value ---> Valeur de l&apos;option:
<script>
```

**Comment by DontShootMe** [comment]
@Felix-Ho 

So what about this ?
Did you tried it ?
it is a real bug, but it is closed now !
What do you think about it ?

**Comment by Felix-Ho** [comment]
@DontShootMe Thanks for the update.
I have made a quick fix to the product option commit
https://github.com/opencart/opencart/commit/3b45520d2ac1f6e6067642bc3764d472c5decf58
and will check others twig which require to escape and fix them.

Thanks again for the reporting.

**Comment by zkrx** [comment]
This is still an issue. I'm using (the same?) French translation on Opencart 4.0.1.1. Example from `admin/language/fr-fr/catalog/option.php`:

```
// Entrée
$_['entry_name'] = 'Nom de l\'option';
$_['entry_type'] = 'Type';
$_['entry_option_value'] = 'Nom de la valeur de l\'option';
$_['entry_image'] = 'Image';
$_['entry_sort_order'] = 'Trier l\'ordre';                              
```

As you can see, quotes are correctly escaped. Yet it's impossible to add an option:
`Uncaught SyntaxError: unexpected token: identifier`
On this line:
`    html += '      <input type="text" name="option_value[' + option_value_row + '][option_value_description][1][name]" value="" placeholder="Nom de la valeur de l'option" id="input-option-value-' + option_value_row + '-1" class="form-control"/>';`

`Uncaught ReferenceError: addOptionValue is not defined`

Removing the quotes from the translation file and the problem is solved.

I can find the same issue being referenced on this forum nearly 10 years ago:
https://forum.opencart.com/viewtopic.php?t=137214

I wonder what other areas of the site are impacted. This is a show-stopper for non-english countries IMO.
