### ISSUE TITLE
Submission guide for Translations

### ISSUE THREAD

**Issue by azarus** [opencart/opencart#6383]
Hey,

I have used crowd in to submit translations for open cart project. Large ammount words for thai translations are missing. We would like to know how and where should we submit the translations so they can be fixed.
Thank you :)

**Comment by azarus** [comment]
Could you please make a seperate repo for opencart to submit all the language packs and translations to be maintained in one place?

**Comment by Felix-Ho** [comment]
@azarus You can contribute the translation content via
http://translate.opencart.com/project/opencart/th#
click on the file and you can enter the translate text.

If you still have question about that, please feel free to send us email via
https://www.opencart.com/index.php?route=support/contact
