### ISSUE TITLE
Multiply model creation (opencart 2.3, 3.x)

### ISSUE THREAD

**Issue by butsds** [opencart/opencart#6387]
Forexample:

model
class ModelCatalogTest extends Model {
    public function __construct($registry) {
        parent::__construct($registry);
        echo "instance created <br>";
    }
    
    public function test1() {}
    public function test2() {}
    public function test3() {}
}
controller
class ControllerCommonTest extends Controller {
    
    public function index() {
        $this->load->model('catalog/test');
        
        $this->model_catalog_test->test1();
        $this->model_catalog_test->test2();
        $this->model_catalog_test->test3();
    }
}
output:
instance created
instance created
instance created

problem code system/engine/loader.php in callback method

solution:
protected function callback($registry, $route) {
		return function($args) use($registry, &$route) {
			//-static $model = array(); 			
			
			$output = null;
			
			// Trigger the pre events
			$result = $registry->get('event')->trigger('model/' . $route . '/before', array(&$route, &$args, &$output));
			
			if ($result) {
				return $result;
			}
			
            $model_route = substr($route, 0, strrpos($route, '/'));
            
			// Store the model object
			//-if (!isset($model[$route])) {
			if (!$registry->get($model_route)) {
                
				$file = DIR_APPLICATION . 'model/' .  $model_route . '.php';
				$class = 'Model' . preg_replace('/[^a-zA-Z0-9]/', '', $model_route);

				if (is_file($file)) {
					include_once($file);
                    
					//-$model[$route] = new $class($registry);
                    $registry->set($model_route, new $class($registry));
                
				} else {
					throw new \Exception('Error: Could not load model ' . $model_route . '!');
				}
			}

			$method = substr($route, strrpos($route, '/') + 1);
			
			//-$callable = array($model[$route], $method);
			$callable = array($registry->get($model_route), $method);

			if (is_callable($callable)) {
				$output = call_user_func_array($callable, $args);
			} else {
				throw new \Exception('Error: Could not call model/' . $route . '!');
			}
			
			// Trigger the post events
			$result = $registry->get('event')->trigger('model/' . $route . '/after', array(&$route, &$args, &$output));
			
			if ($result) {
				return $result;
			}
						
			return $output;
		};
	}

**Comment by stalker780** [comment]
This is really a problem, cause you cannot use variables inside custom models. 

Once you set:
`$this->model_catalog_test->myvar1 = 'value';`

You cannot ever access it.

**Comment by butsds** [comment]
Мy solution fix this problem? May be. 

$this->model_catalog_test->newvar = 'hello';        
var_dump($this->model_catalog_test->newvar);

this code is working

output:
string(5) "hello"

**Comment by danijelGombac** [comment]
This code system/engine/loader.php in callback method was changed:

https://github.com/opencart/opencart/commit/9e6bf71367c74b21e79277870046821c8dde8cbd#diff-0c5765e97948951f14975634256f02f2

**Comment by danijelGombac** [comment]
@butsds 

I made your test. The code was changed, but the result is the same.

**Comment by butsds** [comment]
Please, test it http://sandbox.onlinephpfunctions.com/code/209f76d609631a6ce9a5738bec9e08f2f9025666 . Static variable in closure is senselessly.

**Comment by butsds** [comment]
or http://sandbox.onlinephpfunctions.com/code/f02e0fdac4f73391eaff586adbe384054d558707

**Comment by danielkerr** [comment]
it will be fixed once the minimum vewrsion of php allows us to use classkit.

**Comment by danielkerr** [comment]
not required. also u can do __get __set toi add stuff.
