### ISSUE TITLE
Banners sometimes appear and sometimes not!!

### ISSUE THREAD

**Issue by Mona-Abdelkader** [opencart/opencart#6388]
Hi,
Please I'm using OpenCart Version 2.3.0.2, and my banners were working properly, now I can't find them even they are still enabled and sometimes I found them working in the Arabic edition of my website and when turns into English they keep appearing and when refresh the page they disappear, and sometimes they don't show up, I don't know what is the problem exactly.

The latest change to my website is securing its content to be displayed in HTTPS instead of HTTP, anyone has idea about this issue??

Thanks in advance

**Comment by Felix-Ho** [comment]
@Mona-Abdelkader Sorry this is not a opencart system bug and I recommend you using contact us form from
https://www.opencart.com/index.php?route=support/contact
Then our support team will check it for you.

**Comment by Mona-Abdelkader** [comment]
Thanks a lot
