### ISSUE TITLE
OpenCart v2.x - Internet Explorer v11 (Button "Copy" remove product)

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#6389]
Hello.

How to reproduce:
1. Login in OpenCart v2.0.3.0
2. Select Catalog> Product
3. Select one or more product
4. Click on button "Copy"

Selected product has been removed in Internet Explorer.
In other browser like FireFox work fine.

Screenshot:
https://ibb.co/nnqZQc

**Comment by Felix-Ho** [comment]
@faca5 Issue confirmed. I will try find out what's the reason cause this issue since the issue only happening on IE.

**Comment by Felix-Ho** [comment]
@faca5 It's a bug from IE which is not an opencart system issue.
https://stackoverflow.com/questions/20149751/ie11-only-submit-bug

If you getting this issue from your opencart store.
I recommend you apply this fix

Using FTP or file manager from your hosting cpanel to access opencart system core file.
Goto root directory/admin/view/theme/catalog/product_form.tpl
Goto line 169 and find <script type="text/javascript"><!--
Adding the following code after this line.

$('button[form=\'form-product\']').on('click', function(e) {
	$('#form-product').attr('action', $(this).attr('formaction'));
});

Hope this help!

**Comment by faca5** [comment]
Hello.

Thank you!
