### ISSUE TITLE
Still OCMOD problems

### ISSUE THREAD

**Issue by LorisIT** [opencart/opencart#6392]
I installed OC 3.0.2.0 with JOURNAL theme but trying to install extensions with OCMOD the message "invalid file" or "file not found" appears. I tried various solutions, renaming the file xxx.ocmod.zip correctly, and trying with the directory STORAGE both inside the OC folders and on www /. I tried all the various strange solutions proposed on the net but without result. The FTP entry does not appear in the control panel, even in the clean OC installation. I also tried with VQMOD installed and without VQMOD. What should I do ?

**Comment by Felix-Ho** [comment]
@LorisIT That's not an issue from the extension install.
If you facing any issue from installing Journal template, you should refer to their installation guideline first.
Different extension/template might have different way to install.

Also github page is using for report bug not reporting system usage issue.
Please make use of the contact us form next time.
https://www.opencart.com/index.php?route=support/contact

**Comment by LorisIT** [comment]
I have the same problem with a new and clean installation. From what I read on the net is a fairly common problem, so we can assume that it is a bug of opencart
