### ISSUE TITLE
Image changes color when uploading

### ISSUE THREAD

**Issue by claudineireal** [opencart/opencart#6393]
I'm having a problem in certain photos, when I send the product photo and I visit the product the image is darker than the original, has anyone had this problem?

Should be like this
https://image.ibb.co/k5xeAc/werrrtwtw.jpg
But stay that way
https://image.ibb.co/iN5ubH/165_600x900.jpg

**Comment by stalker780** [comment]
Perhaps you have to save your original photos without color profiles first.

**Comment by claudineireal** [comment]
I've tried it in many ways and it always happens.
