### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#6400]
Tried upgrading one of my websites to latest master.

Current version has broken SEO and cannot be used.

It creates very strange links for products and info pages
http://test.loc/my-product-seo-url?route=product%2Fproduct&language=en-gb
http://test.loc/about-us?route=information%2Finformation&language=en-gb

Category link does not have seo at all
http://test.loc/index.php?route=product/category&language=en-gb&path=20

I thought it's because of empty push field in oc_seo_url. Saving a product fills this field, but nothing changes.

.htaccess is missing

Also it always builds http links, even if ssl is set in settings and I'm opening page by entering https://test.com

**Comment by Felix-Ho** [comment]
@stalker780 Would you mind using the contact us form
https://www.opencart.com/index.php?route=support/contact
and send it a support request also provide your store admin and ftp detail (Please don't provide from here).
Then we will check it for you.

**Comment by stalker780** [comment]
I have reverted online website to previous version.

Testing it now on localhost. I will prepare a test website on my hosting and let you know.
