### ISSUE TITLE
[v3.0.2.0 - Fix] - Custom Fields from catalog/controller/api/customer.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6401]
A forum topic has been created about this issue. Admins were unable to validate a required custom field from the admin - > sales - > add new order - > customers tab.

Fix: https://forum.opencart.com/viewtopic.php?f=201&t=202036#p713641

**Comment by danielkerr** [comment]
you have not described the issue only added a fix!

can not replicate any issue!

wortks fine for me!

**Comment by danielkerr** [comment]
> Another event that could happen is when OC administrators are logged in at the same time and one could simply delete a custom field while another could create an OC order and be prevented to proceed to the next step without realizing why.

start using your brain! dont try to fix issues for a massive what if outcome! it will be rare for a store owner to be deleting new custom fields as the customer is ordering! and even if they are its a one time thing!

**Comment by straightlight** [comment]
`can not replicate any issue!

wortks fine for me!`

Is that so? Then, perhaps you could explain on why exactly this topic says otherwise by demonstrating a PHP error rather than a user error? https://forum.opencart.com/viewtopic.php?f=201&t=201860#p713353

As I am sure you'd rather and not surprisingly believe it may be for decoration purposes, the brainless part I have distinguished is where you haven't tested the code before actually publishing the customer API file. One thing is for sure, once my fix has been implemented from the 2nd post of the forum, this error message is no longer showing as users are ... suddenly ... able to proceed to the 2nd tab after hitting continue from the admin - > orders - > add. As far as I am concerned, these issues has been reported on the forum for a long time now and, until that day, no definite solution were posted other than noticing the mistake you've made by affecting other users with the admin order_form.twig file and / or with the catalog/controller/api/customer.php file.

At this point, I'd say my brain works pretty well!

**Comment by danielkerr** [comment]
@straightlight


i only ment the part i quoted. its unnecessary.
