### ISSUE TITLE
PP Standard option type file

### ISSUE THREAD

**Issue by agatha65** [opencart/opencart#6402]
In catalog/controller/extension/payment/pp_standard.php
At line 34
$upload_info = $this->model_tool_upload->getUploadByCode($option['value']);
model/tool/upload is not initialized.
Just add before
$this->load->model('tool/upload');

**Comment by Felix-Ho** [comment]
@agatha65 : Thanks for reporting it.
I have committed the fix.
https://github.com/opencart/opencart/commit/9ed34ba8f6f7b66ef206e61b60b4998ed27967ec
