### ISSUE TITLE
Sitemap lastmod error

### ISSUE THREAD

**Issue by agatha65** [opencart/opencart#6403]
When the date_modified is empty - the product is not edited or updated with import extension directly in the database the lastmod is wrong (<lastmod>-0001-11-30</lastmod>) and Google reports an error in webmaster tools.
It can be fixed with a condition if the date_modified is empty - use date_added or by filling the date_modified when the product is added(it is the best solution but will conflict with a lot of extensions).

**Comment by rmullaney77** [comment]
Why not update your importer to include the dates as needed ;)

**Comment by Felix-Ho** [comment]
@agatha65 : When using the backend to add product, addProduct method in model/catalog/product will insert date_modified as now. So it's not a bug from opencart system.

You need to update the import extension to insert a date_modified from the import action so that it's not empty.
Hope this help!

**Comment by agatha65** [comment]
@Felix-Ho My mistake it is for version 3 up to 3.0.1.2
The last release  is OK.
As developer I have some time clients with this problem.
