### ISSUE TITLE
Error 500 across whole site when caching is turned off

### ISSUE THREAD

**Issue by theJoff** [opencart/opencart#6404]
Hi,

In Opencart 3.0.1.1 it get a 500 error across the whole site if I turn the theme caching off.  If I turn it back on and it's fine again. 

I'm just using the default theme.

Any ideas?

**Comment by danielkerr** [comment]
u need to contact ur host to allow eval function to enabled.

**Comment by theJoff** [comment]
Thanks Daniel.  Will sort.

Joe
