### ISSUE TITLE
Twig file not read

### ISSUE THREAD

**Issue by theJoff** [opencart/opencart#6405]
HI,

In Opencart 3 I'm trying to create a custom page.  I've tried all of the tutorials out there and they simply don't work.  All I'm trying to do is create a custom information page that includes some script.

Here's what I did:

Created a **custom.twig** file in \catalog\view\theme\default\template\information
I used the code from information.twig but added my script (and `<p>Hello World</p>` for good measure) 

Created a custom.php controller (I copied the code from information and set the view to information/custom).

Added a new layout in the admin and called it Custom and set its route to information/custom.

Added a new information page and set the design to Custom.

Result:

Nothing happens, it just behaves like an information page; no hello world.  I even added a custom.php language file, loaded it in the controller, set a variable and tried to get the twig to call that up. Again, nothing.

What am I missing?

Thanks,

Joe

**Comment by Felix-Ho** [comment]
@theJoff : I recommend you try double check your controller file.
Try find out and check if you set the outpout correctly.
$this->response->setOutput($this->load->view('information/custom', $data));

**Comment by bitlineweb** [comment]
Have you found a solution for this issue, I'm having the same problem!
thanks
