### ISSUE TITLE
[v3.0.2.0 - Problem] - admin/view/template/extension/payment/pp_express_refund.twig file

### ISSUE THREAD

**Issue by Ashon95** [opencart/opencart#6406]
i am getting this error when i issue a refund in opencart cpanel i have followed the fix here but still give's me error on refund - [https://github.com/opencart/opencart/commit/e452fe01dd9e04a0e05ccc1b710d3005de1f4807]

`Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unexpected token "string" of value "" ("name" expected) in "extension/payment/pp_express_refund.twig" at line 15.' in /home1/<Removed>/public_html/system/library/template/Twig/TokenStream.php:87 Stack trace: #0 /home1/<Removed>/public_html/system/library/template/Twig/Extension/Core.php(304): Twig_TokenStream->expect(5) #1 /home1/<Removed>/public_html/system/library/template/Twig/Extension/Core.php(277): Twig_Extension_Core->getTest(Object(Twig_Parser), 15) #2 /home1/<Removed>/public_html/system/library/template/Twig/Extension/Core.php(271): Twig_Extension_Core->parseTestExpression(Object(Twig_Parser), Object(Twig_Node_Expression_Name)) #3 [internal function]: Twig_Extension_Core->parseNotTestExpression(Object(Twig_Parser), Object(Twig_Node_Expression_Name)) #4 /home1/<Removed>/public_html/system/library/template/Twig/ExpressionParser.php(48): call_user_func(Array, Object(Twig_Parser), Object(Twig_Node_Expression_Name)) #5 /home1/<Removed>/public_html/system/libr in /home1/<Removed>/public_html/system/library/template/Twig/TokenStream.php on line 87
`
This is my pp_transaction file

```
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <td class="text-left">{{ column_transaction }}</td>
      <td class="text-left">{{ column_amount }}</td>
      <td class="text-left">{{ column_type }}</td>
      <td class="text-left">{{ column_status }}</td>
      <td class="text-left">{{ column_pending_reason }}</td>
      <td class="text-left">{{ column_date_added }}</td>
      <td class="text-left">{{ column_action }}</td>
    </tr>
  </thead>
  <tbody>

  {% if transactions %}
  {% for transaction in transactions %}
  <tr>
    <td class="text-left">{{ transaction.transaction_id }}</td>
    <td class="text-left">{{ transaction.amount }}</td>
    <td class="text-left">{{ transaction.payment_type }}</td>
    <td class="text-left">{{ transaction.payment_status }}</td>
    <td class="text-left">{{ transaction.pending_reason }}</td>
    <td class="text-left">{{ transaction.date_added }}</td>
    <td class="text-left"> {% if transaction.transaction_id %} <a href="{{ transaction.view }}" data-toggle="tooltip" title="{{ button_view }}" class="btn btn-info"><i class="fa fa-eye"></i></a>
      {% if transaction.payment_type == 'instant' and (transaction.payment_status == 'Completed' or transaction.payment_status == 'Partially-Refunded') %}
      <a href="{{ transaction.refund }}" data-toggle="tooltip" title="{{ button_refund }}" class="btn btn-danger"><i class="fa fa-reply"></i></a>&nbsp;
      {% else %}
      <button type="button" value="{{ transaction.resend }}" data-toggle="tooltip" title="{{ button_resend }}" class="btn btn-info"><i class="fa fa-refresh"></i></button>
      {% endif %} </td>
  </tr>
  {% endfor %}
  {% else %}
  <tr>
    <td class="text-center" colspan="7">{{ text_no_results }}</td>
  </tr>
  {% endif %}
  </tbody>

</table>
```

PP_express Refund File 

```
{{ header }}{{ column_left }}
<div id="content">
  <div class="page-header">
    <div class="container-fluid">
      <div class="pull-right"> <a href="{{ cancel }}" class="btn btn-primary"><i class="fa fa-reply"></i> {{ button_cancel }}</a> </div>
      <h1>{{ heading_title }}</h1>
      <ul class="breadcrumb">
        {% for breadcrumb in breadcrumbs %}
        <li><a href="{{ breadcrumb.href }}">{{ breadcrumb.text }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="container-fluid">
    {% if error is not '' %}
    <div class="alert alert-danger alert-dismissible"><i class="fa fa-exclamation-circle"></i> {{ error }}
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    {% endif %}
    {% if attention is not '' %}
    <div class="alert alert-danger alert-dismissible"><i class="fa fa-exclamation-circle"></i> {{ attention }}
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    {% endif %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> {{ text_refund }}</h3>
      </div>
      <div class="panel-body">
        <form action="{{ action }}" method="post" enctype="multipart/form-data" id="form" class="form-horizontal">
          <input type="hidden" name="amount_original" value="{{ amount_original }}"/>
          <input type="hidden" name="currency_code" value="{{ currency_code }}"/>
          <div class="form-group">
            <label class="col-sm-2 control-label" for="input-transaction-id">{{ entry_transaction_id }}</label>
            <div class="col-sm-10">
              <input type="text" name="transaction_id" value="{{ transaction_id }}" placeholder="{{ entry_transaction_id }}" id="input-transaction-id" class="form-control"/>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">{{ entry_full_refund }}</label>
            <div class="col-sm-10">
              <input type="hidden" name="refund_full" value="0"/>
              <input type="checkbox" name="refund_full" id="refund_full" value="1" {{  refund_available == '' ? 'checked="checked"' : '' }} onchange="refundAmount();"/>
            </div>
          </div>
          <div class="form-group" {{ refund_available == '' ? 'style="display:none;" ' : ''}} id="partial_amount_row">
            <label class="col-sm-2 control-label">{{ entry_amount }}</label>
            <div class="col-sm-10">
              <input type="text" name="amount" value="{{ refund_available is not '' ? refund_available : '' }}" placeholder="{{ entry_amount }}" class="form-control"/>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">{{ entry_message }}</label>
            <div class="col-sm-10">
              <textarea name="refund_message" id="paypal_refund_message" cols="40" rows="5"></textarea>
            </div>
          </div>
          <div class="pull-right"> <a onclick="$('#form').submit();" class="btn btn-primary">{{ button_refund }}</a> </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript"><!--
function refundAmount() {
  var valChecked = $('#refund_full').prop('checked');

  if (valChecked == true) {
    $('#partial_amount_row').hide();
  } else {
    $('#partial_amount_row').show();
  }
}
//--></script>
{{ footer }}
```

**Comment by Felix-Ho** [comment]
@Ashon95 : Yes, it was a small bug and we had fix it on last year.
https://github.com/opencart/opencart/commit/52a3614a253ab93b2c8ede2afb8493b44b40cc37#diff-ed16b6e231782b45373ada99e0ae4ba3

You can follow the fix on the above link to update your pp_express_refund.twig file and it will fix your issue.

**Comment by Ashon95** [comment]
I have looked in to this and the files still does not work on line 46 this code needs to be changed to 
<div class="form-group" {{ refund_available == '' ? 'style="display:none;" ' : ''}} id="partial_amount_row">
To 
<div class="form-group" {{ refund_available is not null ? 'style="display:none;" ' : ''}} id="partial_amount_row">

But I’m not sure if this will brake anything else if i do not edite line 49 i get this error 

Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unexpected token "string" of value "" ("name" expected) in "extension/payment/pp_express_refund.twig" at line 49.' in /home1/k0y4e1v2/public_html/system/library/template/Twig/TokenStream.php:87 Stack trace: #0 /home1/k0y4e1v2/public_html/system/library/template/Twig/Extension/Core.php(304): Twig_TokenStream->expect(5) #1 /home1/k0y4e1v2/public_html/system/library/template/Twig/Extension/Core.php(277): Twig_Extension_Core->getTest(Object(Twig_Parser), 49) #2 /home1/k0y4e1v2/public_html/system/library/template/Twig/Extension/Core.php(271): Twig_Extension_Core->parseTestExpression(Object(Twig_Parser), Object(Twig_Node_Expression_Name)) #3 [internal function]: Twig_Extension_Core->parseNotTestExpression(Object(Twig_Parser), Object(Twig_Node_Expression_Name)) #4 /home1/k0y4e1v2/public_html/system/library/template/Twig/ExpressionParser.php(48): call_user_func(Array, Object(Twig_Parser), Object(Twig_Node_Expression_Name)) #5 /home1/k0y4e1v2/public_html/system/libr in /home1/k0y4e1v2/public_html/system/library/template/Twig/TokenStream.php on line 87
