### ISSUE TITLE
Contact Us Language problem 3.0.2.0

### ISSUE THREAD

**Issue by Ashon95** [opencart/opencart#6409]
When i Use Contact us it will work fine and i will get email but on submit it will give me this message, Think its a Language Problem 

"You have successfully unsubscribe %s from our newsletter."

**Comment by Ashon95** [comment]
Fixed 👍 

find:
`$this->response->redirect($this->url->link('information/contact/success'));`

add above:
`$this->session->data['success'] = true;`

Then, find:
`$data['continue'] = $this->url->link('common/home');`

add below:
```
if (!empty($this->session->data['success'])) {
			$data['text_success'] = $this->language->get('text_success');
			
			unset ($this->session->data['success']);
		}
```


In catalog/view/theme/<your_theme>/template/common/success.twig file,

find:

`</ul>`

add below:

```
{% if text_success %}
  <div class="alert alert-success alert-dismissible"><i class="fa fa-check-circle"></i> {{ text_success }}</div>
  {% endif %}
```

**Comment by Ashon95** [comment]
ok i have done that as above and realised that the susses message is still there but the  other message is to - **You have successfully unsubscribe %s from our newsletter.**

**Comment by straightlight** [comment]
This message cannot be found from the core nor from the code tab of Github Opencart development: https://github.com/opencart/opencart/blob/master/upload/catalog/language/en-gb/information/contact.php

**Comment by Felix-Ho** [comment]
@Ashon95 I check the message
**You have successfully unsubscribe %s from our newsletter.**
Which is not exist from any file from our core system file.

Would you mind send us a support request from
https://www.opencart.com/index.php?route=support/contact
Then we will check if that's an extension issue.
