### ISSUE TITLE
Opencart 2.1.0.2 google_captcha Issue

### ISSUE THREAD

**Issue by musiaczek** [opencart/opencart#6413]
I turned on the google captcha in my store, and i have some error on Register, Contact etc, sites:
I generated the google key, add in admin panel and in
`SyntaxError: Unexpected token < in JSON at position 0

OK

<b>Notice</b>: Undefined index: g-recaptcha-response in <b> /var/www/clients/client2/web137/web/catalog/controller/captcha/google_captcha.php</b> on line <b>32</b>{"error":{"captcha":"Angegebener Code stimmt nicht mit angezeigtem \u00fcberein!"}}`

Line 32 in google_captcha.php:
`$recaptcha = file_get_contents('https://www.google.com/recaptcha/api/siteverify?secret=' . urlencode($this->config->get('google_captcha_secret')) . '&response=' . $this->request->post['g-recaptcha-response'] . '&remoteip=' . $this->request->server['REMOTE_ADDR']);`

Can you help?

**Comment by ADDCreative** [comment]
https://github.com/opencart/opencart/pull/5609

**Comment by Felix-Ho** [comment]
@musiaczek You can follow ADDCreative's advice to fix your google captcha issue from your store.
Here is the file changes log
https://github.com/opencart/opencart/pull/5609/commits/d37113e652d1a4386728959d8558f8aeca710e22
