### ISSUE TITLE
3.0.2.0 Paypal refund Error in logs 

### ISSUE THREAD

**Issue by Ashon95** [opencart/opencart#6415]
i get this error in logs when i refund a person - 
PHP Notice:  Undefined index: parent_id in /home1/removed/public_html/admin/model/extension/payment/pp_express.php on line 86

**Comment by AlexChanHK** [comment]
Please go to \admin\controller\extension\payment\pp_express.php and edit row 706
from 
`'parent_transaction_id' => $this->request->post['transaction_id'],`
to
`'parent_id' => $this->request->post['transaction_id'],`
It should help to fix the error.

**Comment by Ashon95** [comment]
now i get this on front side on page on payment success -
 Parse error: syntax error, unexpected '$this' (T_VARIABLE), expecting function (T_FUNCTION) in /home1/Removed/storage/modification/catalog/controller/checkout/success.php on line 42

**Comment by straightlight** [comment]
parent_id already resolved here: https://forum.opencart.com/viewtopic.php?f=202&t=202172&p=714401#p714401

As for the T_FUNCTION error, more information is needed, what is on line 42 of that file?

**Comment by AlexChanHK** [comment]
If the error exist modification, mostly it is related to the extension of other function.
You may need to send a support ticket in Opencart.com, then we can check further for your case.
