### ISSUE TITLE
[v3.0.3.0b - Fix] - catalog/controller/extension/payment/cod.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6424]
Line 4:

https://forum.opencart.com/viewtopic.php?f=201&t=202494#p715639

opencart.com downloads and on the code tab of Github, same line of code that needs to be fixed.

**Comment by Felix-Ho** [comment]
@straightlight Thanks for reporting the issue.
I initialize the $data array from this commit
https://github.com/opencart/opencart/commit/61a913d60fe589b2d2033c13d0cf20d84bbce96a
which should fix the issue.
