### ISSUE TITLE
Removing an option leaves a dangling product-option pointing to the removed one

### ISSUE THREAD

**Issue by gbmaster** [opencart/opencart#6426]
Hello,
I noticed a weird behaviour when removing an option value from the admin panel (in OC 2.x, but the issue seems to be present in OC 3.x as well). If the option value itself is included in one product, the latter will still have the product-option-value related to the removed one, but showing an invalid value in the combobox (my case was a select option).

The issue is easily reproducible:
* Create a select option
* Create one or more option value in the option
* Associate one or more of the previously created values to a product
* Remove one of the previously associated option values from the option section
* Check the product options

By checking the code in https://github.com/opencart/opencart/blob/master/upload/admin/model/catalog/option.php, I noticed that in the edit and in the delete methods, there's no mention of the product_option and product_option_value tables.

I would like to know if this is the expected behaviour or if it deserves a fix.

**Comment by Felix-Ho** [comment]
@gbmaster Thanks for reporting the issue also with clear reproducible steps.
I have run a test following these steps and issue confirm.

So, I update and fix it on the master branch.
https://github.com/opencart/opencart/commit/9f9e2c3597ed46cf238cc76c7fafdf3928faa85c

If you using opencart system, you can apply the changes from the above link which should fix your issue.

**Comment by gbmaster** [comment]
Thanks for the fix @Felix-Ho.
Just a question: this new code prevents also to change the sort order or rename already existing (and used) option values, which was possible before, am I right?

Shouldn't the fix just prevent the deletion of already used option values?
