### ISSUE TITLE
opencart 3.0.3.0b HTTP ERROR 500 after rest cache

### ISSUE THREAD

**Issue by kurdi999** [opencart/opencart#6428]
hi 
im testing opencart 3.0.3.0b 
after rest cache in dashboard in admin page 
now no admin page keep this error
 is currently unable to handle this request.
HTTP ERROR 500

**Comment by stalker780** [comment]
+1
Installed Opencart 3.0.3.0. Cleared Template & SASS cache in admin dashboard and it stopped working.

Fatal error: Uncaught Error: Class 'scssc' not found in \localhost\oc3030\admin\controller\startup\sass.php on line 7

**Comment by danielkerr** [comment]
should be working on my last commit.

**Comment by danielkerr** [comment]
admin wont look pretty. trying to update to bootstrap 4 as quick as i can.

**Comment by ttibrhm** [comment]
> hi
> im testing opencart 3.0.3.0b
> after rest cache in dashboard in admin page
> now no admin page keep this error
> is currently unable to handle this request.
> HTTP ERROR 500

I have the same problem and I can't log in anywhere?please help me
