### ISSUE TITLE
admin/model/sale/order.php::getOrders() can't search by customer e-mail

### ISSUE THREAD

**Issue by mehov** [opencart/opencart#6429]
Hello, 

There are a bunch of conditions applied to the SQL query built inside the [`getOrders()` function located in `admin/model/sale/order.php`](https://github.com/opencart/opencart/blob/master/upload/admin/model/sale/order.php#L150), but none of them filter orders by the `email` value.

Having `filter_customer` there means that looking customers up is a needed feature. I'm willing to contribute the code.

**Comment by mhcwebdesign** [comment]
This is not a bug! The only filters for this are:

order_id, customer, order_status, total, date_added, date_modified

If you want to add more filters, the controller, model, language, and template files are all to be modifed.

**Comment by mehov** [comment]
@mhcwebdesign 

1. I never said it was a bug
2. No, the files you mentioned do not necessarily need to be modified. 

For example: we need a custom extension retrieving the refunded orders placed from a given e-mail. Currently I have to do a direct `$this->db->query()`. I'd much rather reuse a core model function.

**Comment by mhcwebdesign** [comment]
You could easily write up a little VQmod or OCmod XML script for this, or override the **getOrders** in an extended model class. The standard OpoenCart only uses the **getOrders** function for the Customer Orders Report and the Sales Orders listings.

**Comment by mehov** [comment]
@mhcwebdesign why would I want to use vQmod if this can be painlessly added to the core? We specifically want to avoid using vQmod at all cost.

**Comment by danielkerr** [comment]
@mehov 

i dont work for you.
