### ISSUE TITLE
Cannot Open Modification Page in Opencart 3.x Version

### ISSUE THREAD

**Issue by reeuwebsolution** [opencart/opencart#6431]
Fatal error: Uncaught Error: Call to a member function getElementsByTagName() on null in /home/shopp/data/storage/modification/admin/controller/marketplace/modification.php:1377 Stack trace: #0 /home/shopp/data/storage/modification/admin/controller/marketplace/modification.php(758): ControllerMarketplaceModification->getModificationXmlFiles() #1 /home/shopp/data/storage/modification/admin/controller/marketplace/modification.php(21): ControllerMarketplaceModification->getList() #2 /home/shopp/data/storage/modification/system/engine/action.php(79): ControllerMarketplaceModification->index() #3 /home/shopp/public_html/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array) #4 /home/shopp/data/storage/modification/system/engine/action.php(79): ControllerStartupRouter->index() #5 /home/shopp/data/storage/modification/system/engine/router.php(72): Action->execute(Object(Registry)) #6 /home/shopp/data/storage/modification/system/engine/ro in /home/shopp/data/storage/modification/admin/controller/marketplace/modification.php on line 1377

**Comment by mhcwebdesign** [comment]
Without further details no one is able to reproduce your error.

**Comment by Felix-Ho** [comment]
@reeuwebsolution Please tell us more information about your issue because we can not reproduce your error on a fresh install of opencart.

**Comment by straightlight** [comment]
Null values are not caused by platforms. These results are caused by an extension, by a server library limitation when pulling the results, or by schema changes from the related provider.

**Comment by lucasjkr** [comment]
@straightlight what in the world does that even mean? Beside, issue closed, they didn't provide info on how to recreate.

**Comment by straightlight** [comment]
While the issue was already closed, the explanation of the closure was not explained. The explanation has now been provided to the OP. If you do not understand the meaning of these technical analysis, simply Google them.

**Comment by danielkerr** [comment]
modification/admin/controller/marketplace/modification

means the modification system its self was modified.

**Comment by isolonwest03** [comment]
I have the same errors when trying to update modifiers. I tried disabling them all, it didn't help. When I overwrite the files from the backup and click update modifiers again, the error repeats (I can give access to the developers so they can check. Version 3.0.3.7
So far, the only option is not to click update at all, as something breaks after this action. It's a shame it's not clear which module is causing the problem...
main page errors Notice: Undefined property: Proxy::getOCTCategories in /home/isolonwe/public_html/system/engine/action.php on line 79
refresh Fatal error: Uncaught Error: Call to a member function getElementsByTagName() on null in /home/isolon/public_html/admin/controller/marketplace/modification.php:488 Stack trace: #0 /home/isolon/public_html/system/engine/action.php(79): ControllerMarketplaceModification->refresh() #1 /home/isolon/public_html/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array) #2 /home/isolon/public_html/system/engine/action.php(79): ControllerStartupRouter->index() #3 /home/isolon/public_html/system/engine/router.php(67): Action->execute(Object(Registry)) #4 /home/isolon/public_html/system/engine/router.php(56): Router->execute(Object(Action)) #5 /home/isolon/public_html/system/framework.php(169): Router->dispatch(Object(Action), Object(Action)) #6 /home/isolon/public_html/system/startup.php(104): require_once('/home/isolonwe/...') #7 /home/isolon/public_html/admin/index.php(21): start('admin') #8 {main} thrown in /home/isolon/public_html/admin/controller/marketplace/modification.php on line 488

**Comment by andr11b** [comment]
@isolonwest03, Obviously the issue is not related to the OpenCart itself, but to the theme by the OCTemplates you are using. You (or someone you will hire) just need to look at what's going on, check the paths, etc.

**Comment by isolonwest03** [comment]
Backup helped, completely deleted and overwrote 3 folders: catalog, storage, system
