### ISSUE TITLE
Rounding issue with Paypal (again)

### ISSUE THREAD

**Issue by NoobSkywalker** [opencart/opencart#6433]
Hey i know that this has been discussed several times and its also an issue in general with paypal. 
But i was wondering if there is any solution to this when net prices are set to 4 decimal roundings (e.g. german shop). Is it somehow possible that these cent differences to paypal can be fixed in any way ? someone has some new advice on this. (Opencart 3.0.2.0)

**Comment by Felix-Ho** [comment]
@NoobSkywalker Have you try set the decimal place from the currency you using to checkout?
It's from your store backend
admin > system > localisation > currencies > edit > Decimal Places

**Comment by NoobSkywalker** [comment]
well it currently is set to 2 decimal places. However some prices are still defined on 4 decimals or more.

**Comment by ADDCreative** [comment]
@NoobSkywalker If you are referring to the PayPal total not matching the OpenCart total, maybe this will help. https://github.com/ADDCreative/opencart/commit/c34c867efd9ee659ccfe596d40a50f6ecba8ccc4

**Comment by Felix-Ho** [comment]
@NoobSkywalker Yes, please double check your currencies setting to make sure they are using 4 decimal places if you would like to process that through paypal.

I have created a test order and echo posting information which will sending to paypal.
As you can see, 4 decimal places is applying

![paypal](https://user-images.githubusercontent.com/6228720/36965103-9a025be2-2093-11e8-9830-46458c5987d2.png)

**Comment by NoobSkywalker** [comment]
@Felix-Ho but i dont what to see 4 decimal places in the shop, so how is this handled ?

**Comment by cstudiocc** [comment]
Hi, I have the same issue in PP Express. Is there a solution? (OC 2.3.0.2, euro, 2 decimal in frontend e 4 decimals in admin)... Thank you
