### ISSUE TITLE
opencart 3.0.3.0b datepicker bug

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#6436]
`$('.date').datetimepicker();`

Does not always work. For example for dynamically created inputs with JS.

Open a product page, open discounts tab. If there are discounts already created, their datepickers work ok. But if you add a new row, datepicker doesn't work in it.

Same problem with several extensions for OC3.0.2.0. Everything works fine except datepickers. Because inputs are created dynamically.

**Comment by danielkerr** [comment]
u mean the master branch! not the production version which works. 

its been worked on. im updating bootstrap to 4
