### ISSUE TITLE
php 7.2 support

### ISSUE THREAD

**Issue by breisig** [opencart/opencart#6437]
Has anyone tried testing the latest opencart [even from git] to see if its compatible with php 7.2?

**Comment by davidfranks** [comment]
I'm also interested to find out the answer to this?

When I asked OpenCart Support they said:

Normally, we prefer the Opencart system to run in PHP 5.6.
There may be some bug or error with you run in PHP 7.X.

If you have any question, please feel free to let us know.
Thanks and regards,

Alex
Opencart Team

**Comment by stalker780** [comment]
3.0.2-3.0.3 runs quite fine in php 7.0-7.1 on production server.

I'm developing and testing on localhost in php 7.2 now. See no problems with it at the moment.

Perhaps some extensions or modules may have problems with it, but core is working without any problems.

**Comment by davidfranks** [comment]
@stalker780 Did you notice any performance increase with PHP 7.X.

See this article - [https://kinsta.com/blog/php-7-hhvm-benchmarks/](url)

On other platforms there are HUGE increases in performance.

**Comment by stalker780** [comment]
Even OC 1.5.4 runs quite fine on php 7.1 with minor code changes to remove notices and encryption.php deprecated warning :)

**Comment by davidfranks** [comment]
@stalker780 like you said it's more 3rd party extension and modules we need to worry about.

**Comment by davidfranks** [comment]
See how much Magento increased from 5.6 > 7.1

![Image of Magento](https://kinsta.com/wp-content/uploads/2018/02/magento-2-benchmarks-1.png)

**Comment by stalker780** [comment]
OC core is fast on any PHP version.
You will not get any noticable improvement.

Test says it works a little faster. And requires less memory on php 7.

But usually, all freezes in OC are related to MySQL and bad coded/optimized/tested extensions.

If you are using Journal, no PHP 7 can help you :)

**Comment by davidfranks** [comment]
@stalker780 Why, because Journal is badly written & optimised?

**Comment by stalker780** [comment]
Just a joke. It's up to you what extension to use.

**Comment by shifterovich2** [comment]
When weight is empty, newer PHP versions show a warning in the delivery list. Non-numeric value occurred. admin/controller/sale/order.php, 1799.

**Comment by lucasjkr** [comment]
@stalker780 I've never seen MySQL causing any freezes. I have seen lousy extensions try to make MySQL execute 500+ queries each time a page is loaded though, but that's not MySQL's fault in the slightest.

**Comment by stalker780** [comment]
@lucasjkr of course that's what I ment.
It cannot be a server's fault it is used wrong way.

Thousands of requests, or an attempt to query whole db in one http request. This is a problem.

**Comment by danielkerr** [comment]
HI,

I dont know which idiot staff said this but they are wrong! i run and test on php 7.1. i have not checked php7.2 but unless there is some massive change i can not see why it would not work.

**Comment by kseniia-s** [comment]
PHP 7.2 removed mcrypt extension. Since OC3, mcrypt was replaced, so I guess, it will work fine as well. The functions changed in the newest PHP versions don't affect OC. However, some extensions might be not up to date but from my experience with professional, large extension developers, that should not be a problem.

Source: https://forum.opencart.com/viewtopic.php?t=202581
