### ISSUE TITLE
Affiliate setting and Affiliate with order complete status

### ISSUE THREAD

**Issue by MuhamedAuda** [opencart/opencart#6438]
Hi, Affiliate **Automatic Commission** at setting->option tab never saved to database.
and we skip setting at code no Commission add to affiliate account when order reach compete status 
Any suggests ?

**Comment by Felix-Ho** [comment]
@MuhamedAuda I run a test on the latest version of opencart.

1) setting->option tab never saved to database.
All fields
config_affiliate_id
config_affiliate_commission
config_affiliate_group_id
config_affiliate_auto
config_affiliate_approval
under setting table can be update successfully.

2) no Commission add to affiliate account when order reach compete status
I place an order with the affiliate link.
![affiliate](https://user-images.githubusercontent.com/6228720/36882319-1029d134-1e0e-11e8-9edf-ad54fd28549d.png)
Affiliate detail also save successfully on the order.

So, it should not be a bug from the latest version.
If you using latest version, probably there is a setting configuration issue and I recommend you contact us via
https://www.opencart.com/index.php?route=support/contact
