### ISSUE TITLE
[v3.0.2.0] - Error when affiliate form is sent

### ISSUE THREAD

**Issue by DiV666** [opencart/opencart#6444]
Hi,

I get this error when the affiliate form is sent:
```
Notice: Undefined index: firstname in .../catalog/controller/event/activity.php on line 125
Notice: Undefined index: lastname in .../catalog/controller/event/activity.php on line 125
Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unexpected token "end of print statement" of value "" in "default/template/mail/affiliate.twig" at line 1.' in .../system/library/template/Twig/ExpressionParser.php:190 Stack trace: #0 .../system/library/template/Twig/ExpressionParser.php(84): Twig_ExpressionParser->parsePrimaryExpression() #1 .../system/library/template/Twig/ExpressionParser.php(41): Twig_ExpressionParser->getPrimary() #2 .../system/library/template/Twig/Parser.php(144): Twig_ExpressionParser->parseExpression() #3 .../system/library/template/Twig/Parser.php(100): Twig_Parser->subparse(NULL, false) #4 .../system/library/template/Twig/Environment.php(619): Twig_Parser->parse(Object(Twig_TokenStream)) #5 .../system/library/template/Twig/Environment.php(671): Twig_Environment->parse(Object(Twig_TokenStream)) #6 .../system/library/template/Twig/Environment.php( in .../system/library/template/Twig/ExpressionParser.php on line 190
```

**Comment by Felix-Ho** [comment]
@DiV666 I try to reproduce the error by submitting affiliate registration on the store front.
I test on opencart-maseter (which is the development version) also with stable 3.0.2.0 version.
Both working find and affiliate account can be successfully created. 

![affiliate](https://user-images.githubusercontent.com/6228720/37011107-920811b6-2129-11e8-8b78-a7d07ab029b5.png)


May I know more detail about your web store so that us can investigate the issue.
Please using the contact us form to send the detail to us.
https://www.opencart.com/index.php?route=support/contact
Then we will check it for you.

**Comment by AbdelReheem** [comment]
@Felix-Ho hello I have same issue OC 3.0.3 and submit the contact us forum could you please support

**Comment by aj1322001** [comment]
has anyone fixed this issue yet? i am getting the same.. opencart 3.0.3.1

Notice: Undefined index: firstname in /home4//mywebsite.com/catalog/controller/event/activity.php on line 125Notice: Undefined index: lastname in /home4//mywebsite.com/catalog/controller/event/activity.php on line 125Warning: Cannot modify header information - headers already sent by (output started at /home4//mywebsite.com/catalog/controller/startup/error.php:34) in /home4//storage/modification/system/library/response.php on line 36

**Comment by danielkerr** [comment]
you can disable the event being called when the forum is submitted in the admin. under admin > extension > events look for code mail_affliate_add maybe

**Comment by danielkerr** [comment]
sorry wrong one

i think activity_affiliate

**Comment by aj1322001** [comment]
nice one danielkerr it was activity_affiliate_add thanks

**Comment by Khnaz35** [comment]
Above provided solution turning off the event  activity_affiliate_add doesn’t work on OC 3.0.3.5
![image](https://user-images.githubusercontent.com/43812103/108811248-dff1e800-75e7-11eb-9163-1a826369ece3.png)
