### ISSUE TITLE
admin Panel URL->Link Error

### ISSUE THREAD

**Issue by HuseyinYucel** [opencart/opencart#6445]
Hello,

PHP Fatal error:  Call to a member function link() on a non-object in /public_html/admin/controller/error/not_found.php on line 12

I get the error.
This error is present in the latest version.
Can you help with the subject?

**Comment by HuseyinYucel** [comment]
I get this error on the admin panel login page. the page is blank.

**Comment by straightlight** [comment]
Which OC version is this issue reported for?

**Comment by HuseyinYucel** [comment]
Githup Beta version...

**Comment by AlexChanHK** [comment]
The Beta version of Opencart always exist different bug or issue as it is developing environment,
For example now should be updating the bootstrap version, and layout was crush by this,
but the admin login page and function should be fixed already.
If you are non a developer, don't using beta version!

**Comment by HuseyinYucel** [comment]
after the last updates I made.
Thank you for your support.
Good work,
