### ISSUE TITLE
Problems with city information not updating and updating in customer address form

### ISSUE THREAD

**Issue by HuseyinYucel** [opencart/opencart#6446]
The latest version of Opencart GitHub is not updating the address because the cities are not listed on the form. new customers can not update their addresses for this reason. Can you help with the subject?

**Comment by Felix-Ho** [comment]
@HuseyinYucel I try update city field under customer address setting form.

![before](https://user-images.githubusercontent.com/6228720/37021574-02dbc596-215b-11e8-9495-0c08aaa1e9fe.png)
Before update is HKG

I adding few 1 after HKG for clearing state the update.
![after](https://user-images.githubusercontent.com/6228720/37021583-09308c24-215b-11e8-8f01-d0420d855a13.png)
Clearly it's working fine.

**Comment by danielkerr** [comment]
This should be related to the adressformat under country

**Comment by HuseyinYucel** [comment]
https working system on the new record and update the current registration unfortunately does not come out of the city list of the country. He works in zero setup. But after updating the current 3.0.1 version system, it started not to work. Can you help me with this?

**Comment by HuseyinYucel** [comment]
Hello Daniel
I've done a lot of experiments today. I think the problem is in the js code below.
On this screen I changed the en-gb and tr-tr dlls and got the same error in both.
What should we do to make this mistake? Can you help me?

![getcooki-error](https://user-images.githubusercontent.com/17760101/37092520-458c5c08-221d-11e8-8dce-68b27a5313bb.png)
