### ISSUE TITLE
OC1.5.5.1 admin(manual) order edit

### ISSUE THREAD

**Issue by pine3ree** [opencart/opencart#645]
i found out this:
1. place order on frontend with default currency(EUR)
2. change frontend currency to other currency($)
3. update (edit, add product, update totals, save) order in backend

=> totals are now displayed in other currency($), while product unit price and product total price in order currency(EUR)

does this happen to anyone else?
# doubts and questions
1. maybe ajax requests to catalog/checkout/manual.php should include order currency information and setting frontend currency to order currency after customer->logout and unset(s);
2. even so currency rates change : should we keep order currency rate or update the order currency rate to the current (editing time) exchange rate?

kind regards

**Comment by micrdy** [comment]
I got the same issue in OC 2.0.1.1. Is there any fix?

**Comment by ADDCreative** [comment]
The fix should already be in the 2.x branch, unless something else has changed since then.

**Comment by micrdy** [comment]
I got 2 currencies at my site. The right one is selected with IP of the user. But if I´m editing an order in backend, the prices are only shown in my standard backend currency. I thought that this could be related to this issue.

**Comment by pine3ree** [comment]
@micrdy 
that should be the correct behaviour.
You edit orders in your default currency (the one You use to set prices).
The values should be converted back to the order currency (using the order currency conversion value) when saving.

**Comment by micrdy** [comment]
@pine3ree Thanks for your answer. Okay.
But If I add a new order through backend there is no possibility to specify the currency. And the prices / currency are not recalculated depending on customers shipping adress

**Comment by pine3ree** [comment]
@micrdy 
I believe You.
I used a very customized version of opencart so I have had that option since 2013 and so i didn't pay much attention if oc has it.
Maybe you should open a feature request issue asking to add this option, it doesn't take too much effort to add this feature to opencart admin/order(add|edit).
