### ISSUE TITLE
Add product 

### ISSUE THREAD

**Issue by Hackej** [opencart/opencart#6450]
Clean install 3100b this morning, no adjustments or OCMods or anything.

Adding products from Featured in home page is not working correctly:

- IE11 - Click “Add to cart” in featured products in Home-page do not add to cart or link to product page – nothing happens.

- Chrome – click on “Add to cart” in featured in home page works but confirmation is presented to the right (see picture).

BR
/Hackej

![opc3100 home](https://user-images.githubusercontent.com/29421668/37207166-adf577ee-2393-11e8-80fb-654edd46c3e5.png)

**Comment by straightlight** [comment]
Please use the Developers Kit and follow the Console tab when reporting front-end issues with different browsers so that your reported inquiry can be reproduced.

**Comment by danielkerr** [comment]
Make sure u have cleared the browser cache.
