### ISSUE TITLE
https does not work in seo_url

### ISSUE THREAD

**Issue by HuseyinYucel** [opencart/opencart#6454]
https structure seo_url active category and subcategories of js and css files in the url section of the category names can not find the corresponding file. and the page breaks up. I am using the current version of Github.

The seo_url system works if you do not activate https. But this structure does not work in https.
Can you help me?

if the normal css path is so;
Could not load <script> from "https://www.domain.com/catalog/view/javascript/jquery/jquery-2.1.1.min.js".

If https seo_url is enabled, the directory paths change as follows.
Could not load <script> from "https://www.domain.com/category/catalog/view/javascript/jquery/jquery-2.1.1.min.js".

**Comment by danielkerr** [comment]
Set the base / to the correct  directory in htaccess

**Comment by HuseyinYucel** [comment]
He Daniel,
In this case my .htaccess file is set as you said
The content is as follows.
Can you help me figure out what kind of setting I should make? 

.htaccess
Options +FollowSymlinks

# Prevent Directoy listing
Options -Indexes

# Prevent Direct Access to files
<FilesMatch "(?i)((\.tpl|.twig|\.ini|\.log|(?<!robots)\.txt))">
 Require all denied
## For apache 2.2 and older, replace "Require all denied" with these two lines :
# Order deny,allow
# Deny from all
</FilesMatch>

# SEO URL Settings
RewriteEngine On

RewriteCond %{HTTP_HOST} !^www.domain.com$ [NC]
RewriteRule ^(.*)$ https://www.domain.com/$1 [L,R=301]

RewriteCond %{SERVER_PORT} !=443
RewriteRule ^ https://wwww.domain.com%{REQUEST_URI} [NS,R,L]

# If your opencart installation does not run on the main web folder make sure you folder it does run in ie. / becomes /shop/

RewriteBase /

RewriteRule ^sitemap.xml$ index.php?route=extension/feed/google_sitemap [L]
RewriteRule ^googlebase.xml$ index.php?route=extension/feed/google_base [L]
RewriteRule ^system/storage/(.*) index.php?route=error/not_found [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !.*\.(ico|gif|jpg|jpeg|png|js|css)
RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]

RewriteCond %{HTTP_USER_AGENT} libwww-perl.* 
RewriteRule .* ? [F,L]

<IfModule mod_deflate.c>
  # Compress HTML, CSS, JavaScript, Text, XML and fonts
  AddOutputFilterByType DEFLATE application/javascript
  AddOutputFilterByType DEFLATE application/rss+xml
  AddOutputFilterByType DEFLATE application/vnd.ms-fontobject
  AddOutputFilterByType DEFLATE application/x-font
  AddOutputFilterByType DEFLATE application/x-font-opentype
  AddOutputFilterByType DEFLATE application/x-font-otf
  AddOutputFilterByType DEFLATE application/x-font-truetype
  AddOutputFilterByType DEFLATE application/x-font-ttf
  AddOutputFilterByType DEFLATE application/x-javascript
  AddOutputFilterByType DEFLATE application/xhtml+xml
  AddOutputFilterByType DEFLATE application/xml
  AddOutputFilterByType DEFLATE font/opentype
  AddOutputFilterByType DEFLATE font/otf
  AddOutputFilterByType DEFLATE font/ttf
  AddOutputFilterByType DEFLATE image/svg+xml
  AddOutputFilterByType DEFLATE image/x-icon
  AddOutputFilterByType DEFLATE text/css
  AddOutputFilterByType DEFLATE text/html
  AddOutputFilterByType DEFLATE text/javascript
  AddOutputFilterByType DEFLATE text/plain
  AddOutputFilterByType DEFLATE text/xml

php_value allow_url_fopen On

**Comment by danielkerr** [comment]
RewriteBase /

do some google searching. im not here to fix your issues but fix real bugs. im sure this is alareayddocumented.
