### ISSUE TITLE
Voucher e-mails are not automatically sent to Recipient. Opencart 2.3.0.2

### ISSUE THREAD

**Issue by ocdevgo** [opencart/opencart#6456]
Voucher e-mails are not automatically sent after purchase. Order status is Complete (in extension setup and shop settings), all other e-mails work (admin and customers get confirmation e-mails), everything is set up properly, but still no e-mails for recipient!

I've found many reports of this issue and even read somewhere it was fixed already, but it's not!!! I'm using opencart 2.3.0.2, downloaded from the official site, no mods installed, clean setup. What and where do I need to fix to get reed of this error????

**Comment by straightlight** [comment]
Issue posted about an older version of OC.
