### ISSUE TITLE
Git branch issue

### ISSUE THREAD

**Issue by ocdevops** [opencart/opencart#6457]
Hi,
maybe it would be better if you change the Github url on the official site (pointing to the stable tag or push the dev version of the Opencart to another branch instead of master), because there were many users who downloaded a beta version from Github instead of the stable release.
If someone clicks on the Github link on https://www.opencart.com/index.php?route=cms/download, he will download the Opencart 3.1.0.0b version as the master branch.

**Comment by danielkerr** [comment]
it does say this on the relase note side 


3.0.3.0b | 3.0.3.0 (Beta) Non production Beta Do not use on a live web site.
-- | --
