### ISSUE TITLE
[v3.0.2.0 BUG] - ReferenceError: getCookie is not defined (Default Template | Product/Product)

### ISSUE THREAD

**Issue by beatcode** [opencart/opencart#6458]
**File:**
catalog/view/theme/default/template/product/product.twig

**Problem:** 
click on the shopping cart (#button-cart) force the console error. Shopping Cart doesn't work.

> ReferenceError: getCookie is not defined

**Solution:**
https://stackoverflow.com/questions/5216631/javascript-does-not-recognize-function

Funkction append end to Javascript:

`function getCookie(cname) {
     var name = cname + "=";
     var ca = document.cookie.split(';');
     for(var i=0; i<ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1);
        if(c.indexOf(name) == 0)
           return c.substring(name.length,c.length);
     }
     return "";
}`

**Comment by AlexChanHK** [comment]
This case did not exist in most installation of OpenCart system version 3020,
could it be possible if it is due to some edition or hosting issue only?
I suggest you can install a new installation in sub-folder in confirm again.

**Comment by Vibrat** [comment]
Where would you add the function getCookie() ? This could happen because some scripts that are only included based on specific Controller path.

**Comment by beatcode** [comment]
hmm. The function getCookie () is already in the file. there.https://github.com/opencart/opencart/blob/master/upload/catalog/view/javascript/common.js
Probably I configured something wrong
