### ISSUE TITLE
[v3.0.2.0 - Bug] - TWIG engine with 'matches' term in for loop

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6465]
An interesting error message appears when using a for loop in TWIG file defined with keys and values. When using the word: 'matches' on the value side to extract a multi-dimensional array,

For instance: 

`{% for code,matches in array %}
... codes here ...
{% endfor %}`

returns:

`Fatal error: Uncaught Twig_Error_Syntax: Only variables can be assigned to. Unexpected token "operator" of value "matches" ("name" expected) in ...`

Avoid using that term with multi-dimensional array in the value position of the extraction until this issue can be resolved.

**Comment by AlexChanHK** [comment]
Where did you found that code in OpenCart system version 3.0.2.0.
Well, the error message only mean that you used some invalid variable name with using twig template.
If it is code customized by you, it is completely not related to any bug of OpenCart system.

**Comment by straightlight** [comment]
Forgot to indicate that this line of code is part of one of my contribution with v3.0.2.0 . Although, the point is not about a contribution since I am using the exact TWIG engine as the original. When typing the 'matches' term on the value position of the for loop, this error message then appears. Since the TWIG engine is centralized through Opencart, in this case, I beg to differ but it is definitely an issue that needs to be fixed as it is already a bug throughout Opencart.

Granted, it may not be Opencart's direct issue to resolve but rather the TWIG developers. Although, my inquiry still stands indicating that the 'matches' term should not be used in the value position of for the loop until this issue gets actually resolved rather this could be used from the core files or from a contribution.

That being said, my line of codes have been provided on the first post. Developers normally test provided codes before indicating the results. If you are already convinced at this point that it is not related to any bug of Opencart system, then clearly you haven't tested anything.

Please let the developers test this observation and they will notice the difference.

**Comment by danijelGombac** [comment]
For complex string comparisons, the matches operator allows you to use regular expressions:

```
{% if phone matches '/^[\\d\\.]+$/' %}
{% endif %}
```

**Comment by danijelGombac** [comment]
The same error with 'is'

` Uncaught exception 'Twig_Error_Syntax' with message 'Only variables can be assigned to. Unexpected token "operator" of value "is" ("name" expected).`

**Comment by straightlight** [comment]
Thanks for the info. It seem the matches term is related to a reserved term in this case. Although, this term being used in the for loop should not be conflicted with the regular expressions validation since, in this case, from the for loop - it would be a defined user variable.

For instance, using a foreach statement in PHP:

`foreach ($array as $key => $matches) {`

Normally, we would see the $matches scalar into a preg_match or preg_match_all statement but can also be used elsewhere as the programmer likes as long as the defined variable has not been instantiated elsewhere in the file.

In this case, this issue seem to be a propagated matter from the TWIG engine where the matches term does not make the comparison between a defined statement and a reserved term statement when using the term: 'matches'.

**Comment by straightlight** [comment]
Then, it is settled. This issue is definitely about the reserved terms not being considered when defined variables are being set by the user.

**Comment by AlexChanHK** [comment]
The issue report in OpenCart project should related to the code of the system itself. 
If this related to the error of the your customized code, I do not suggest that you report in here.

**Comment by straightlight** [comment]
As mentioned on the above, the issue has already been discovered. Compared to PHP, the TWIG engine does not distinguish the reserved terms when using those terms inside functions which brings further confusions whether the code can originate from the core as well as developing contributions and may still encounter this issue.

Let the developers handle this from there.
