### ISSUE TITLE
[v3.0.2.0] cli_install.php does not download vendor/[dirs/files] or build composer's autoload.php file.

### ISSUE THREAD

**Issue by panreach** [opencart/opencart#6466]
After having in issue with something similar in #5723, I noticed that the cli_install.php file doesn't download the vendor directory files.  I'm guessing it's installed via composer, but that's merely a guess at this point.  Does anyone else notice this problem?

**Comment by danielkerr** [comment]
It's not supposed to.

**Comment by danielkerr** [comment]
I'm sure that's what composer being installed is for

**Comment by panreach** [comment]
Okay, thank you.  It's just that I noticed the web installer installs these files.  I'll look for another way to install the composer dependencies with a separate command line script.

**Comment by panreach** [comment]
Alright, I figured out what I was doing wrong.  My build script would simply `git checkout [whichever release]` (instead of the downloading the zip file).  Therefore, I copy a `composer.phar` executable into the root directory (so the build is portable with machines that aren't composer friendly) and issued a `php composer.phar install` prior to running `php cli_install.php`.

I'm not sure if there's anything else that needs to be done for the build, but if I notice anything I'll add it to this ticket.  And also, I'm sorry if I've posted in the wrong forum for this type of discussion.

Leaving this comment here in case it helps anybody else.

Thanks

**Comment by lucasjkr** [comment]
If you're installing using composer, you can just do:

`composer create-project opencart/opencart {your directory}`

That downloads opencart and pulls in the vendor directory.

Dowside is the application is put inside a directory called "upload", so you either need to set your web server to serve files from there, or rename it to your servers preferred directory name.

After that, you can run the command line installer... That'll create your two config.php files and create your initial database...
