### ISSUE TITLE
[v3.0.2.0 - Fix] - catalog/controller/extension/payment/pp_pro.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6468]
Replace:

`$request .= '&BUTTONSOURCE=' . urlencode('OpenCart_2.0_WPP');`

with:

`$request .= '&BUTTONSOURCE=' . urlencode('OpenCart_3.0_WPP');`

**Comment by jamesallsup** [comment]
The PayPal button codes or BN codes are not for reference as you expect so cannot be changed to match the version. PayPal needs to supply these to us.
