### ISSUE TITLE
Opencart.com Marketplace Many Icon not display

### ISSUE THREAD

**Issue by sainent** [opencart/opencart#6470]
https://www.opencart.com/index.php?route=marketplace/extension

in opencart.com market place if you see there are lot of icon are not display proper.
check with below image link 
https://image.opencart.com/original/5aadfad767165.jpg
https://image.opencart.com/original/5aadfae1f1de2.jpg
https://image.opencart.com/original/5aadfaea9368e.jpg
https://image.opencart.com/original/5aadfaf3322d8.jpg

i had find out the issue that may be font of fontawesome file "fontawesome-webfont.ttf" is not loaded well, it can be two kind of reason "fontawesome-webfont.ttf" file not found in fonts directory or file will corrupted. 

in this file "https://www.opencart.com/application/view/javascript/fontawesome/css/font-awesome.min.css" 
at this css code : url('../fonts/fontawesome-webfont.ttf?v=4.7.0')
can't load font file or corrupted file.

so check the font directory in path "application/view/javascript/fontawesome/fonts/"
all fonts files are working and get correct path.

Thank You

**Comment by AlexChanHK** [comment]
Thanks for reporting, the designer was fixing it already.
Sorry for the trouble.
