### ISSUE TITLE
install.sql don't work in ocmod with opencart3

### ISSUE THREAD

**Issue by emamheba** [opencart/opencart#6477]
I write my extention to opencart3 using ocmod 
it work correctly and xml file make all changes in file but sql file not work and not make any change in databae
install.sql::
LTER TABLE oc_order_history
ADD (user_group text  , user_name text ); 

ALTER TABLE oc_order
ADD (user_id int  );

**Comment by kurosus** [comment]
Hi, what kind of your extension is?
I have tested to build with my testing extension with install function in admin controller and model file.
It can be installed my sql successfully.
Maybe you can try!

**Comment by xtensions** [comment]
opencart 3 doesn't allow install.sql and install.php. You need to write the sql code in one of controller. Best case would be in install method of the controller.

Second table ALTER is not allow, so instead create two tables, each for oc_order_history and oc_order and use joins else your extension will not be approved in opencart cloud.

**Comment by emamheba** [comment]
thanks for your reply @kurosus 
can you send to me your extention to test it

**Comment by emamheba** [comment]
thanks @even if i write Alter table in controller will not be allowed??

**Comment by danielkerr** [comment]
@emamheba this is not a support area.
