### ISSUE TITLE
Open Cart 3.0 SQL Server Support?

### ISSUE THREAD

**Issue by bhglove** [opencart/opencart#6479]
Hi, I used opencart a few years ago and I'm pretty sure I was able to use MSSQL with Open Cart 2.0. I'm hitting a block with the installer on step 3 and getting a "Driver not found" exception. 

Here is a screenshot of my phpinfo. 
[phpinfo().pdf](https://github.com/opencart/opencart/files/1833344/phpinfo.pdf)

Are there any resources for installing Open Cart 3.0 with SQL Server? 

Thanks

**Comment by straightlight** [comment]
Not a bug. Simply switch to mssql from your config.php and admin/config.php files with the DB_DRIVER defined constant once the installation completed.

**Comment by bhglove** [comment]
The config files are not defined yet because I can't get past the installation.

**Comment by bhglove** [comment]
I modified line 9 of \opencart\app\system\library\db\mpdo.php 
from: 
`$this->connection = new \PDO("mysql:host=" . $hostname . ";port=" . $port . ";dbname=" . $database, $username, $password, array(\PDO::ATTR_PERSISTENT => true));
`
to :
`$this->connection = new \PDO("sqlsrv:Server=" . $hostname . ";Database=" . $database, $username, $password, array(\PDO::SQLSRV_ATTR_DIRECT_QUERY => true));`
