### ISSUE TITLE
Cron jobs require admin login

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#6480]
The cron job url displays the admin login - admin/index.php?route=common/cron
Is it missing from the first `$ignore` admin/controller/startup/login.php

Also it could do with some form of security to prevent the cron from being easily run by anybody. Maybe a token check you pass as a parameter.

**Comment by AlexChanHK** [comment]
I also can't find a way to ignore the login or auto login with the cron job function.
The only solution I can think is placing it to somewhere that don't need to login and adding a secret key for that.
For example:
wget "http://localhost/opencartlatest/upload/index.php?route=common/cron&secret=???" --read-timeout=5400
Don't know much knowledge about server, if there is possible solution, please suggest.

**Comment by danijelGombac** [comment]
@AlexChanHK 

I use cron jobs without problems.

I change $ignore array:

upload/admin/controller/startup/login.php
upload/admin/controller/startup/permission.php

and added cron_token in config settings. The only problem with cron jobs is date_modified.

**Comment by miklcct** [comment]
@howdu `common/route` is present in `$ignore` in the master branch in both `login.php` and `permission.php`

**Comment by AlexChanHK** [comment]
@danijelGombac
Thanks, as I did not notice that we can ignore the login and permission protect in this way.><
I checked the code in the related to the date_modified of corn job,
seem Daniel had added a protection for the all the corn job,
`if ($result['status'] && (strtotime('+1 ' . $result['cycle'], strtotime($result['date_modified'])) < time())) {`
therefore if last update of corn object is less than 1 cycle(default of currency corn is day), it will not run.
If I manually edit the date in database and run Corn URL, then the day will update.

Also, did you created a filed for user to create the cron_token, or you directly added in DB for testing?
___
On the other hand, refer the current  master version(29/3/2018)
The 'common/cron' only exist in the 2nd $ignore in ControllerStartupLogin,
Therefore it will still exist login page as the access was rejected in the
`if (!$this->user->isLogged() && !in_array($route, $ignore)) {`
Should we add 'common/cron' in the first $ignore also?

**Comment by danijelGombac** [comment]
I use cron for daily backup. But with current code it work every two days.

In admin/controller/startup/login.php add 'common/cron' to the first $ignore array

and i change admin/controller/common/cron.php

```
<?php
class ControllerCommonCron extends Controller {
    public function index() {
        $timestamp = time();

        if (isset($this->request->get['cron_token']) && ((string)$this->request->get['cron_token'] == $this->config->get('config_cron_token'))) {
            $this->load->model('setting/cron');

            $results = $this->model_setting_cron->getCrons();

            foreach ($results as $result) {
                if ($result['status'] && (strtotime('+1 ' . $result['cycle'], strtotime($result['date_modified'])) < ($timestamp + 10))) {
                    $this->load->controller($result['action'], $result['cron_id'], $result['code'], $result['cycle'], $result['date_added'], $result['date_modified']);

                    $this->model_setting_cron->editCron($result['cron_id'], $timestamp);
                }
            }
        }
    }
}
```
and in admin/model/setting/cron.php

```
public function editCron($cron_id, $timestamp) {
    $this->db->query("UPDATE `" . DB_PREFIX . "cron` SET `date_modified` = '" . $this->db->escape(date('Y-m-d H:i:s', (int)$timestamp)) . "' WHERE cron_id = '" . (int)$cron_id . "'");
}
```

I added cron_token to config settings like config_encryption.

**Comment by AlexChanHK** [comment]
All in all, there are three small cases with cron job need to be fixed.
(for 29/3/2018 master version)
1. The 1st $ignore array list in admin/controller/startup/login need to add 'common/cron' also.
https://github.com/opencart/opencart/blob/master/upload/admin/controller/startup/login.php#L6
2. Add buffer of update cycle of the cron object, for example
https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/cron.php#L9
`if ($result['status'] && (strtotime('+1 ' . $result['cycle'], strtotime($result['date_modified'])) < time()+buffer time )) {`
3. As it is able to access with cron URL without login and permission,
cron_token need to be added to protect the system.

**Comment by danielkerr** [comment]
im suire u dont need cron token. the cron tasks will only run every 24 hours.
