### ISSUE TITLE
[v3.0.2.0 - Fix] - catalog/model/account/download.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6482]
A topic has been created regarding this small fix: https://forum.opencart.com/viewtopic.php?f=201&t=203106#p718310

**Comment by AlexChanHK** [comment]
As my understanding, the purpose of this edition is try to prevent the customer order the download object in store A and download from store B. (It should work as least I change the store id for checking.)
Also, preventing download in different language, but it is not reasonable as the customer should able to change the store language by themselves.

In addition, you suggest other user to submit the edition in issue #6481,
then why don't you submit this if you think it is correct?

**Comment by straightlight** [comment]
`Also, preventing download in different language, but it is not reasonable as the customer should able to change the store language by themselves.`

Is that so? While I should agree to this statement, then why is the config_language_id already being instantiated in the query since this condition is already part of the core from the getDownloads() method?

`In addition, you suggest other user to submit the edition in issue #6481,
then why don't you submit this if you think it is correct?`

Well, according to my understanding, the statement I posted is a bug and not a pull request. Here's my version of the story.

The getDownloads() method pulls all stores while each generated orders already adds the store ID based on the relative store the customer has selected or being forced to use. The current language ID is being pulled from the getDownloads() but the customer can also switch the language ID from the site header. The right question tp ask yourself, rather to link to an off-topic post by another user, would be the following:

- The customer can switch languages but the order language ID cannot be switched by the user and not being parametered into the getDownloads() method along with the downloads

- The getDownloads() method does not contain any associated language IDs while multiple tables uses that specific database field.

- The store IDs are being pulled altogether while only one store can be linked to the order at a time but only the merchant can make the adjustment from the admin and via the API.

- The getDownload() method, oh wait for it - USES THE CURRENT STORE SETTINGS TO PULL THE ORDER STATUSES COMPARED TO THE getDownloads() METHOD !!!

This has already been reported in the past on the forum and STILL hasn't been fixed!

Forum users has been reporting data duplication for those downloads and none did found an accurate solution to these problems and I am not even wondering why but one thing is for sure - it ain't due to an Opencart issue but the one who did coded that model file in the first place!

Why use all these SQL resources from the getDownloads() method while the current store ID should rather be pulled before reaching the getDownload() method since the order is already restricted to one specific store ID unless the merchant changes it since the customer is still stuck with it?

You know, I am sure Daniel will appreciate the fact that you linked an unrelated topic to another user's post based on these facts above rather than specifically asking those questions. One thing is for sure, probing doesn't seem to be one of your virtues, so far.

**Comment by miklcct** [comment]
@straightlight Could you please edit the opening post clearly where the bug is, and steps to reproduce? It is not clear for our developers to fix the issue promptly.

**Comment by straightlight** [comment]
The aspects on the above post are well detailed enough to understand the source of the issue.

**Comment by JesseOC** [comment]
Tested, this issue is fixed already.
