### ISSUE TITLE
No method named "destroy" when editing or deleting images

### ISSUE THREAD

**Issue by DrPowerSlam** [opencart/opencart#6485]
This is for version 3.0.2.0.
Fresh install on an Ubuntu 16.04 LAMP VPS.
The error is:

> bootstrap.min.js:6 Uncaught TypeError: No method named "destroy"
>     at HTMLAnchorElement.<anonymous> (bootstrap.min.js:6)
>     at Function.each (jquery-3.3.1.min.js:2)
>     at w.fn.init.each (jquery-3.3.1.min.js:2)
>     at w.fn.init.p._jQueryInterface [as popover] (bootstrap.min.js:6)
>     at HTMLButtonElement.<anonymous> (common.js:153)
>     at HTMLButtonElement.dispatch (jquery-3.3.1.min.js:2)
>     at HTMLButtonElement.y.handle (jquery-3.3.1.min.js:2)

Sometimes the error is on popover.js:

> popover.js:164 Uncaught TypeError: No method named "destroy"
>     at HTMLAnchorElement.<anonymous> (popover.js:164)
>     at Function.each (jquery-3.3.1.min.js:2)
>     at w.fn.init.each (jquery-3.3.1.min.js:2)
>     at w.fn.init.p._jQueryInterface [as popover] (popover.js:149)
>     at HTMLButtonElement.<anonymous> (common.js:153)
>     at HTMLButtonElement.dispatch (jquery-3.3.1.min.js:2)
>     at HTMLButtonElement.y.handle (jquery-3.3.1.min.js:2)

To replicate:
Go to System -> Settings -> Edit Store -> Image -> Click on either Store Logo or Icon -> Click on either Edit or Delete.
Curiously, clicking on edit multiple times, while make the overlay stack, making the screen darker for each click.

**Comment by danielkerr** [comment]
U updated jquery? If so downgrade it. I have updated it in the master branch .

**Comment by DrPowerSlam** [comment]
That did not help. I downgraded to 2.2.1, the version that was used before 3.3.1.

The error is still this:

>  popover.js:164 Uncaught TypeError: No method named "destroy"
>     at HTMLAnchorElement.<anonymous> (popover.js:164)
>     at Function.each (jquery.min.js:2)
>     at n.fn.init.each (jquery.min.js:2)
>     at n.fn.init.p._jQueryInterface [as popover] (popover.js:149)
>     at HTMLButtonElement.<anonymous> (common.js:153)
>     at HTMLButtonElement.dispatch (jquery.min.js:3)
>     at HTMLButtonElement.r.handle (jquery.min.js:3)

You can see on my image that the correct version of jQuery is loaded, so it doesn't seem to be a cache issue either.

![jquery-loaded](https://user-images.githubusercontent.com/9006304/37874203-1afcc790-302b-11e8-9f1e-04a91bf74be1.PNG)

**Comment by DrPowerSlam** [comment]
I'm documenting what I'm doing as I try to fix this.

The "the method destroy does not exist" problem is because Bootstrap4 renamed destroy to dispose. Calling that method in common.js instead of destroy, fixes that problem. Now the problem is that the pop-up doesn't come. The screen goes darker, but I'm missing the modal, as far as I can see. I'll write again if I find a fix.

**Comment by danielkerr** [comment]
it was working with the default version of jquery. this is an error with the latest version of jquery.

**Comment by danielkerr** [comment]
jquery-2.1.1.min is the version for 3.0.2.0
