### ISSUE TITLE
[v3.0.2.0 - Fix] - system/library/cart/cart.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6493]
Replace:

`$this->db->query("INSERT "`

with:

`$this->db->query("INSERT INTO "`

This has been reported a long time ago on the forum as this issue still hasn't been fixed.

**Comment by danielkerr** [comment]
It's not been reported here before

**Comment by straightlight** [comment]
While it may never had been reported here before, it's still ironic how long it's been for that correction not being made: https://forum.opencart.com/viewtopic.php?f=191&t=161904&p=616894#p616894 . The bug reports on the forum took place long this Github page ever existed in anyhow.

**Comment by danielkerr** [comment]
please post any other known issues that are in the forum and not here. i dont have time to go over the forums.

**Comment by straightlight** [comment]
I see so after almost 2 years on having posted this bug fix already and no solution was applied on Github regarding this fix yet, people still needs to post on the forum. WTG!
