### ISSUE TITLE
[v3.0.2.0] Search orders filter bug

### ISSUE THREAD

**Issue by toonetcreation** [opencart/opencart#6495]
Hi,

I don't know if this bug has already been reported but here it is.
On SALES -> ORDERS page when I use filter I don't get the same results if I type only last name or last name + first name on CUSTOMER field.
See attached files.

![good](https://user-images.githubusercontent.com/20813754/38033045-8d190e50-328e-11e8-9490-52dba558c3e4.jpg)
![bad](https://user-images.githubusercontent.com/20813754/38033046-8d333c4e-328e-11e8-96e6-56f7efd9a7a5.jpg)

Do you know if this issue will be fixed ?

Many thanks

**Comment by toonetcreation** [comment]
problem is the same with date filter fields.
see attached file.

[filter-date.zip](https://github.com/opencart/opencart/files/1856491/filter-date.zip)

**Comment by toonetcreation** [comment]
latest release : OpenCart 3.0.2.0

**Comment by toonetcreation** [comment]
any info/news about that?

**Comment by miklcct** [comment]
Cannot reproduce your name filter problem

**Comment by toonetcreation** [comment]
the bug is not located on DATE filter.... but on CUSTOMER filter.

try to type different spelling as my screen shot and click on FILTER.

with **Hambridge** you will get  all the results = OK

with **Hambridge Richard** you will get only 1 result = NOT OK

**Comment by toonetcreation** [comment]
I mean when you click on name suggested by auto completion filter ..see below :
![capture d ecran de 2018-04-06 09-38-19](https://user-images.githubusercontent.com/20813754/38408540-7ffdbeba-396d-11e8-88ca-9d6bea8e5920.png)

**Comment by miklcct** [comment]
Not a bug.

The names you have given are different. One has a space at the end and the other three do not have.

**Comment by toonetcreation** [comment]
ok thanks for your help.
you can close this issue.
