### ISSUE TITLE
[v3.0.2.0] Langugage editor pagination not working

### ISSUE THREAD

**Issue by toonetcreation** [opencart/opencart#6496]
Hello, 

When I go to DESIGN -> LANGUAGE EDITOR, I have correctly added some translations override for english. Now I have 2 pages but I cannot use pagination system to see my other pages, I get an error message. 
See attached file.

![language-editor](https://user-images.githubusercontent.com/20813754/38037503-89df3d2c-3298-11e8-9d26-5a3aeaf0b1e7.jpg)

Thanks

**Comment by straightlight** [comment]
For which OC version?

**Comment by JesseOC** [comment]
Hi @toonetcreation
For this case, would you please send the ticket to OpenCart Support in OpenCart website for checking?
https://www.opencart.com/index.php?route=support/contact

**Comment by toonetcreation** [comment]
@straightlight : latest release : OpenCart 3.0.2.0

@JesseOC : ok I will do this right now.

**Comment by straightlight** [comment]
See if this fixes the issue: https://github.com/opencart/opencart/pull/6443

**Comment by toonetcreation** [comment]
I don't think so because #6443 is talking about the following file : upload/catalog/controller/account/download.php (for **catalog**) and my problem is located on **admin** side.

**Comment by straightlight** [comment]
Could you provide the URL of the route included with the page query without the user_token value?

**Comment by straightlight** [comment]
One replacement so far in the admin/controller/design/translation.php file that may need to be changed from:

`$pagination->limit = 10;`

to:

`$pagination->limit = (int)$this->config->get('config_limit_admin');`

**Comment by toonetcreation** [comment]
this ? https://www.xxxxxx.com/xxxxx/index.php?option=com_opencart&route=design/translation/history&user_token=xxxx

**Comment by straightlight** [comment]
Bug confirmed. The history() method does not exist in the admin/controller/design/translation.php file which is why you are noticing a page not found error message from the pagination class.

**Comment by toonetcreation** [comment]
If I add this **$pagination->limit = (int)$this->config->get('config_limit_admin');** where is the config_limit_admin variable to adjust in admin back-end ?

**Comment by straightlight** [comment]
The config_limit_admin is the store's configuration global limit for the admin-end from your admin - > systems - > settings - > edit settings page. As for the pagination URL, the github code already addresses the issue has already been fixed.

Replace the $pagination->url with this one instead:

`$pagination->url = $this->url->link('design/translation', 'user_token=' . $this->session->data['user_token'] . '&page={page}');`

This should resolved the issue in the mean time.

**Comment by toonetcreation** [comment]
Yes I'm using opencart inside Joomla component but this is not the origin of the bug.
Ok for config_limit_admin variable I have found it.

Ok for the temporary solution., I suppose this bug will be fixed for next release?

**Comment by straightlight** [comment]
It has already been fixed in the github files.

**Comment by toonetcreation** [comment]
ok thanks I will download it so.

**Comment by egemenozkan** [comment]
.../admin/index.php?route=design/translation**/history**&user_token=BUIWNGkRWaOLsPrY0JQoMSC7m8OuC5nS&page=2  -- **/history** should remove from controller admin/controller/design/translation.php
