### ISSUE TITLE
[v3.0.3.0b] Return link in order info user

### ISSUE THREAD

**Issue by newerton** [opencart/opencart#6497]
Code:
```php
$this->url->link('account/return/add', 'language=' . $this->config->get('config_language') . '&order_id=' . $order_info['order_id'] . '&product_id=' . $product['product_id'])
```
Return:
```html
http://localhost/iphone?route=account%2Freturn%2Fadd&language=pt-br&order_id=1258
```

The rewrite() function of seo_url.php is changing the URL.

Seo URL info:
![image](https://user-images.githubusercontent.com/4175945/38053061-7c969942-32a9-11e8-9297-464b934aeee4.png)

**Comment by JesseOC** [comment]
Hi @newerton Do you mean v3.1.0.0b?

**Comment by newerton** [comment]
I was using the version from weeks ago.
I've updated now, and the error continues.

**Comment by JesseOC** [comment]
It should be 3.1.0.0b.
The file is tested, and already committed to #6499
Thanks for reporting!

**Comment by newerton** [comment]
Change '%2F' to /. It will not work!

If you do the actual test, product_id is not added to the URL.
Because in the settings the Friendly URL is enabled.

**Comment by danielkerr** [comment]
ok i can fi

**Comment by danielkerr** [comment]
this should be fixed with the seo regex stuff i added to the master branch
