### ISSUE TITLE
Image resizer issue

### ISSUE THREAD

**Issue by inwustore** [opencart/opencart#6498]
Does anyone know a solution for this issue

Warning: imagecreatetruecolor(): Invalid image dimensions in /web/htdocs/domain/home/system/library/image.php on line 105Warning: imagecolorallocate() expects parameter 1 to be resource, boolean given in /web/htdocs/domain/home/system/library/image.php on line 113Warning: imagefilledrectangle() expects parameter 1 to be resource, boolean given in /web/htdocs/domain/home/system/library/image.php on line 116Warning: imagecopyresampled() expects parameter 1 to be resource, boolean given in /web/htdocs/domain/home/system/library/image.php on line 118Warning: imagecreatetruecolor(): Invalid image dimensions in /web/htdocs/domain/home/system/library/image.php on line 105Warning: imagecolorallocate() expects parameter 1 to be resource, boolean given in /web/htdocs/domain/home/system/library/image.php on line 113Warning: imagefilledrectangle() expects parameter 1 to be resource, boolean given in /web/htdocs/domain/home/system/library/image.php on line 116Warning: imagecopyresampled() expects parameter 1 to be resource, boolean given in /web/htdocs/domain/home/system/library/image.php on line 118

**Comment by miklcct** [comment]
Where in the opencart system can you get this issue, and what image are you using for that?

**Comment by danielkerr** [comment]
what ever file is there its not an image

**Comment by inwustore** [comment]
@danielkerr @miklcct sorry I did not see you response/reply. The issue happens when I add multi colour of product for and item in my colour options/ When I proceed to to the cart to check the item i get the error

**Comment by inwustore** [comment]
I have 2.3.02
