### ISSUE TITLE
Nochex Module / Extension - Test Mode Issue and Additional Features

### ISSUE THREAD

**Issue by NochexDevTeam** [opencart/opencart#6500]
Good Morning,

I have recently downloaded a recent version of Opencart, and enabled Nochex which I have placed in Testmode but came accross an issue.

![image](https://user-images.githubusercontent.com/36759878/38080650-f821ce3e-3339-11e8-9947-aedbaf22a5f3.png)

When I go through the checkout and go to the payment page, the merchant_id that is set on the payment form is not the merchant_id that is set in the open cart settings; which I have provided a print screen of below;

![image](https://user-images.githubusercontent.com/36759878/38080731-283d0da4-333a-11e8-8557-8a1f90179140.png)

The merchant id that is passed through to the payment page should be the one set in the open cart settings. Other than this issue the module is working as intended to.

We have also added extra features to the Nochex module, such as; 

- Notes added onto orders in relation to APC and whether the transaction was live / test, 
- Display products in a table structure \ separate postage on the payment page

which can be seen on our own github here: https://github.com/NochexDevTeam/OpenCart_3 

Kind Regards
James Lugton - Nochex Technical

**Comment by straightlight** [comment]
`I have recently downloaded a recent version of Opencart`

What is that recent version?

**Comment by NochexDevTeam** [comment]
Hello @straightlight 

The version that I have downloaded from the Open Cart website is 3.0.2.0-OpenCart.zip

Kind Regards
James Lugton - Nochex Technical Support

**Comment by straightlight** [comment]
You may also want to take a look at these fixes: https://forum.opencart.com/viewtopic.php?f=201&t=199195&p=701193#p701193

**Comment by NochexDevTeam** [comment]
Thank you for informing us of those fixes, I will take a look at including them in our module.

Kind Regards
James

**Comment by danielkerr** [comment]
Nochex has been removed from the core.
