### ISSUE TITLE
[v3.0.2.0] search engine results depending spelling

### ISSUE THREAD

**Issue by toonetcreation** [opencart/opencart#6502]
Hi,

I don't know if this a bug or a default restriction but :

- on default search engine at the top of the screen I type this for example : **Pathologic basis of veterinary disease** and I launch search
- I find 1 result
- then I type Pathologic basis of veterinary disease**s**
- I find 0 results

 this is a normal behavior ?

Thanks

**Comment by danielkerr** [comment]
added the different words u want the products to be found with to the tags.

**Comment by toonetcreation** [comment]
ok thank you

**Comment by toonetcreation** [comment]
so will be available for next release?

**Comment by toonetcreation** [comment]
ok but we cannot type systematically in tags all the words?

I mean, it is tedious to enter all the possible spellings.
