### ISSUE TITLE
extension, Permission Denied!

### ISSUE THREAD

**Issue by vingoyuan** [opencart/opencart#6504]
as a test, i made a new folder of extension, 'customs',  and new customs.php in extension/extension/ 

 and copy a extension in to this folder,  change class name to    ControllerExtensionCustomsClearance.    so   basically  i create a new extension 'Clearance' with new extension folder  'Customs'.  of course new language file and template file are created. 

after give all rights to adminstrator group. 
![1](https://user-images.githubusercontent.com/32472296/38162192-634066f4-34dd-11e8-81d2-3e6e71c444bd.png)
![2](https://user-images.githubusercontent.com/32472296/38162193-635823c0-34dd-11e8-91ce-5a534d462867.png)
[admin.zip](https://github.com/opencart/opencart/files/1865371/admin.zip)

     i can see, install and unstall new extension 'Clearance' .   but i can not  edit.   because

Permission Denied!  You do not have permission to access this page, please refer to your system administrator.

but  if i move all files of new extension 'clearance' to other folder, e.g. extension/payment,   and i can edit this new extension 'clearance'..   

same problem , if i move exited extension 'extension/payment/cheque' to new extension folder 'extension/customs',    'cheque' can not be edited. 

is there some problem with new folder of extension ?  or something els.

**Comment by vingoyuan** [comment]
![20180330185120](https://user-images.githubusercontent.com/32472296/38146059-958f4c24-344c-11e8-8735-fc471eb9b9f2.png)
![20180330190032](https://user-images.githubusercontent.com/32472296/38146105-c7a52850-344c-11e8-89f1-7426afd43bdc.png)

**Comment by straightlight** [comment]
Which OC version? More information is needed.

**Comment by vingoyuan** [comment]
oc3.03  and oc 2.5 both.

**Comment by straightlight** [comment]
Not an OC bug since the extension folder have specific ways to function so to also appear and load in the OC admin. Variables must be appropriately created in the controller files, also in the admin/controller/extension/extension folder. For more information, I would suggest to post in the forum about this.

**Comment by vingoyuan** [comment]
i believe that it is no bug. but where i am wrong?

**Comment by vingoyuan** [comment]
attachment is updated.

**Comment by danijelGombac** [comment]
Here is a list of allowed folders admin/controller/startup/permission.php

```
$extension = array(
	'extension/dashboard',
	'extension/analytics',
	'extension/captcha',
	'extension/currency',
	'extension/extension',
	'extension/feed',
	'extension/menu',
	'extension/fraud',
	'extension/module',
	'extension/payment',
	'extension/shipping',
	'extension/theme',
	'extension/total',
	'extension/report',
        'extension/openbay'
);
```

If you added new directory, then you must add it to the list (extension/customs).

**Comment by vingoyuan** [comment]
that is point. 

thank you very very much.    i should check all code more carefully.

**Comment by danielkerr** [comment]
i will trry to fix it so other folers can be added in other places. but i would use module or other folder for extensions that dont fit into other categories.

**Comment by vingoyuan** [comment]
thanks,
