### ISSUE TITLE
[v3.0.3.0b - Bug] - admin/controller/startup/router.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6505]
$this->config->get('action_default') cannot be found anywhere either in other files nor on the database in the codes except in this file which apparently should be the default routed action when the route on the browser fails.

**Comment by danijelGombac** [comment]
@straightlight action_default is set in this files:

system/config/default.php
system/config/admin.php

**Comment by straightlight** [comment]
The issue is not about inexistent files. It is about the $this->config->get('action_default') not being defined from anywhere in the files nor from the database as explained above.

**Comment by danijelGombac** [comment]
system/config/admin.php

// Actions
$_['action_default'] = 'common/dashboard';

system/config/default.php

// Actions
$_['action_default']       = 'common/home';

**Comment by straightlight** [comment]
Yes, the keys are being defined there with the help of system/framework.php file. I have edited the post above.
