### ISSUE TITLE
[v3.0.3.0b - Bug] - admin/controller/marketing/contact.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6510]
The filter_var function is verified but there are no else statement with the related if statement to notify the user of an error compared to most other cases in the platform where the if statement with the filter_var rather provides both alternatives.

**Comment by gerardadamczewski** [comment]
Invalid emails are simply ignored. Is it a bug?

**Comment by straightlight** [comment]
If the email has been stored on the database, it is not because Opencart ignores those emails. It might rather be due to the email server filtering you are using. However, if you take a look in the database, notice via a query if spaced emails are being found.

**Comment by danielkerr** [comment]
filter_var is used on all registration pages so there should be no invalid emails. if there is then obviously its better to have the 2nd check so the mail server is not going to throw errors.
