### ISSUE TITLE
[v3.0.3.0b - bug] - catalog/controller/extension/payment/klarna_checkout.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6512]
Should be showing a JSON error message along with the checkout/checkout route rather than the checkout/failure since we're not reporting a fraud or an inconclusive case:

`http_response_code(303);
			$this->response->addHeader('Location: ' . $this->url->link('checkout/failure', 'language=' . $this->config->get('config_language')));`

Otherwise, troubleshooting steps may be quite hard to distinguish when this issue occurs for those who will use this payment provider API solution.

**Comment by danielkerr** [comment]
im closing this as all 3rd party extensions are being removed and added int he extension secion. you will be able to report isasues there.
