### ISSUE TITLE
[v3.0.3.0b - bug] - admin/controller/error/permission.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6513]
The $this->request->get['route'] is not validated which means even though there would be a permission error page involved, the variable needs to be validated.

Above:

`$this->load->language('error/permission');`

add:

`if (!isset($this->request->get['route'])) {
    $this->response->redirect($this->url->link('error/not_found'));
} else {`

Then, after:

`$this->response->setOutput($this->load->view('error/permission', $data));`

add:

`}`

**Comment by danielkerr** [comment]
can not make this system not have a route in the admin! your fix is not required.
