### ISSUE TITLE
[v3.0.3.0b - bug] - admin/controller/marketplace/modification.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6514]
I am not sure how useful is the $data['redirect'] array for this line since there are no previous indication of this variable:

`$this->response->redirect($this->url->link(!empty($data['redirect']) ? $data['redirect'] : 'marketplace/modification', 'user_token=' . $this->session->data['user_token'] . $url));`

**Comment by danielkerr** [comment]
modification has been removed
