### ISSUE TITLE
[v3.0.3.0b - fix] - admin/controller/tool/upgrade.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6517]
Find:

`if (!$this->user->hasPermission('modify', 'tool/backup')) {`

replace with:

`if (!$this->user->hasPermission('modify', 'tool/upgrade')) {`

**Comment by gerardadamczewski** [comment]
https://github.com/opencart/opencart/pull/6847

**Comment by jamesallsup** [comment]
Labeled incorrectly, v3.1 issue but already patched.
