### ISSUE TITLE
[v3.0.3.0b - fix] - admin/controller/extension/payment/securetrading_ws.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6518]
Find:

`if (!$this->user->hasPermission('modify', 'extension/payment/securetrading_pp')) {`

replace with:

`if (!$this->user->hasPermission('modify', 'extension/payment/securetrading_ws')) {`

**Comment by gerardadamczewski** [comment]
https://github.com/opencart/opencart/pull/6847
