### ISSUE TITLE
[v3.0.3.0b - fix] - admin/controller/customer/customer.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6521]
Replace all instances of:

`$pagination->limit = 10;`

with:

`$pagination->limit = $this->config->get('config_limit_admin');`

**Comment by gerardadamczewski** [comment]
https://github.com/opencart/opencart/pull/6847

**Comment by danielkerr** [comment]
no required. only for number of products to display!

**Comment by straightlight** [comment]
The reason why the product limit has been used is because this is the only option the OC admins can edit from their settings or with config admin limit regarding pagination values.
