### ISSUE TITLE
[v3.0.3.0b - fix] - admin/controller/marketing/coupon.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6523]
Replace:

`$pagination->limit = 10;`

with:

`$pagination->limit = $this->config->get('config_limit_admin');`

**Comment by gerardadamczewski** [comment]
https://github.com/opencart/opencart/pull/6847

**Comment by danielkerr** [comment]
not needed

**Comment by straightlight** [comment]
Since the pagination now uses a controller file, those fixes for the pagination limit under the no longer existing page class file is no longer needed.
