### ISSUE TITLE
[v3.0.3.0b - fix] - catalog/controller/account/order.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6528]
In no way a customer should only have a limit of 10 orders from his account. It is rather compliant to set the time period yearly (rather the revenue date of the income or from the first purchased period of the current year). For now,

Replace:

`$pagination->limit = 10;`

with:

`$pagination->limit = $this->config->get('theme_' . $this->config->get('config_theme') . '_product_limit');`

**Comment by danielkerr** [comment]
its not required to have product limit for all listed items on a page! just wasting time posting this crap.

**Comment by danielkerr** [comment]
its not required to have product limit for all listed items on a page! just wasting time posting this crap.

**Comment by straightlight** [comment]
The reason why the product limit has been used is because this is the only option the OC admins can edit from their settings regarding pagination values.
