### ISSUE TITLE
[v3.0.3.0b - fix] - catalog/controller/account/recurring.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6529]
Replace:

`$pagination->limit = 10;`

with:

`$pagination->limit = $this->config->get('theme_' . $this->config->get('config_theme') . '_product_limit');`

**Comment by danielkerr** [comment]
its not required to have product limit for all listed items on a page! just wasting time posting this crap.

**Comment by straightlight** [comment]
The reason why the product limit has been used is because this is the only option the OC admins can edit from their settings regarding pagination values.
