### ISSUE TITLE
[v3.0.3.0b - fix] - admin/controller/extension/fraud/ip.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6530]
Replace:

`$pagination->limit = 10;`

with:

`$pagination->limit = $this->config->get('config_limit_admin');`

**Comment by lucasjkr** [comment]
I'll just comment once.

pagination.php has the default limit set to 20 as a property currently. Why not just set it to 10 there?

Then it only needs to be overridden in the specific controllers that it's needed.

**Bonus points:**

Load it into the registry in `framework.php` with the correct limit setting (catalog vs admin), and then it doesn't need to be set in 20 pages and have 20 different issues opened.

**Comment by straightlight** [comment]
Using the config_limit_admin and a hard-coded value on the same controller files does not make any sense. Non-technical people expects to use the admin interface to configure their stores, not having to play with core files. Opencart has the same policy in-place for all users regarding the upgrades; no core files should be edited. Otherwise, they will affect their stores.

With that being said, despite the mount of topics created about it, the only reason why there are so many separate topics is to ease the troubleshooting based on a mixed-concept coding that has been done for those page limits and OC users may want to know all the locations case-by-case due to their lack of knowledge and lack of speed of processes and those who are even afraid to apply those processes period.

Using the default pagination class is great when no hard-coded values have been defined. Although, this time, most of them have been already defined manually in the core which still takes priority over the default value set in the pagination class. Otherwise, should we use a defined value if one value could take control overall across the platform. Then the question would remain to why would OC admin users need to define a page limit in the store settings.

**Comment by hajjiamjad** [comment]
Its very simple first go into System > User > API
1 Give Name To Your API Example : " Main IP "
2 Click on Generate API
3 Make it Enable

Click on API Addressees
Click on ADD IP
Copy paste your IP

Click on Save

Then Go to System > Setting > Edit Your main Store > Click on Option tab
See here : API User
Select Your API USER Which was created in last Stage
For Example Select " main IP "

**Comment by hajjiamjad** [comment]
my mining pool not withdraw

**Comment by hajjiamjad** [comment]
Access not allowed for 192.64.116.47. Please use the Dashboard to add this IP to allow API access.

**Comment by straightlight** [comment]
@hajjiamjad: The goal of this topic is the fact the pagination limit has been set manually rather than using the store admin configuration value; not about how to create an API from the admin.

**Comment by hajjiamjad** [comment]
Access not allowed for 192.64.116.47. Please use the Dashboard to add this IP to allow API access.

**Comment by hajjiamjad** [comment]
my mining pool not withdraw
