### ISSUE TITLE
Invalid XML in Google Sitemaps if `&` is in then product name 

### ISSUE THREAD

**Issue by squarepegsys** [opencart/opencart#6532]
I have a lot of products with & in the name and was surprised to get an invalid Google Sitemap from the extension because it didn't escape it or many other characters. This is a quick and dirty fix to make it work.

see my pull request https://github.com/opencart/opencart/pull/6531

**Comment by ADDCreative** [comment]
@danielkerr I don't think that the htmlspecialchars added by @miklcct are needed. They seemed to cause double encoding like &amp;amp; and &amp;quot; when I quickly tested.

$this->url->link already converts & to $amp;. https://github.com/opencart/opencart/blob/3.1.0.0_a1/upload/system/library/url.php#L56

$product['name'] should already be be converted in the database by the request class when first entered.

For the images changing the line below do a full encoded would probabbly have worked
https://github.com/opencart/opencart/blob/3.1.0.0_a1/upload/catalog/model/tool/image.php#L41 to .

By changing.
```php
$image_new = str_replace(' ', '%20', $image_new);
```
To something like.
```php
$new_image = implode('/', array_map('rawurlencode', explode('/', $new_image)));
```

**Comment by danielkerr** [comment]
Google Sitemaps has been moved out of the opencart core. report any issues via the extension page  comments section there.  will add the page soon.
