### ISSUE TITLE
[v3.0.3.0b - Fix] - admin/controller/catalog/category.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6535]
Find:

`if (($seo_url['store_id'] == $store_id) && ($seo_url['language_id'] == $language_id) && (!isset($this->request->get['category_id']) || ($seo_url['query'] != 'path=' . $this->model_catalog_category->getPath($this->request->get['category_id'])))) {`

replace with:

`if (($seo_url['store_id'] == $store_id) && ($seo_url['language_id'] == $language_id) && (!isset($this->request->get['category_id']) || ((isset($this->request->get['category_id']) && $seo_url['query'] != 'path=' . $this->model_catalog_category->getPath($this->request->get['category_id']))))) {`

**Comment by danielkerr** [comment]
not sure of the issue here.

it does not seem to throw an error.
