### ISSUE TITLE
[v3.0.3.0b - Fix] - admin/controller/catalog/manufacturer.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6537]
find:

`if (($seo_url['store_id'] == $store_id) && ($seo_url['language_id'] == $language_id) && (!isset($this->request->get['manufacturer_id']) || (($seo_url['query'] != 'manufacturer_id=' . $this->request->get['manufacturer_id'])))) {`

replace with:

`if (($seo_url['store_id'] == $store_id) && ($seo_url['language_id'] == $language_id) && (!isset($this->request->get['manufacturer_id']) || ((isset($this->request->get['manufacturer_id']) && $seo_url['query'] != 'manufacturer_id=' . $this->request->get['manufacturer_id'])))) {`

**Comment by danielkerr** [comment]
not sure of the issue here.

it does not seem to throw an error.
