### ISSUE TITLE
[v3.0.3.0b - Fix] - admin/controller/design/seo_url.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6538]
Find all instances of:

`if (($seo_url['store_id'] == $this->request->post['store_id'] && $seo_url['language_id'] == $this->request->post['language_id']) && (!isset($this->request->get['seo_url_id']) || (($seo_url['query'] != 'seo_url_id=' . $this->request->get['seo_url_id'])))) {`

replace all with:

`if (($seo_url['store_id'] == $this->request->post['store_id'] && $seo_url['language_id'] == $this->request->post['language_id']) && (!isset($this->request->get['seo_url_id']) || ((isset($this->request->get['seo_url_id']) && $seo_url['query'] != 'seo_url_id=' . $this->request->get['seo_url_id'])))) {`

**Comment by nickadm** [comment]
Hi, will this fix the problem with mulitple languare? and Seo url?

**Comment by danielkerr** [comment]
not sure of the issue here.

it does not seem to throw an error.

**Comment by vivek-webkul** [comment]
@danielkerr - there is an issue while editing the seo_url.php on admin/controller/design/seo_url.php

https://github.com/opencart/opencart/pull/6908/commits/91325b294777022807e3d2018fea50497955b579
