### ISSUE TITLE
[v3.0.3.0b - Bug] - Die command

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6539]
All files using the die command:

system/library/squareup/cron_functions.php
catalog/controller/extension/payment/globalpay_remote.php
catalog/controller/extension/payment/realex_remote.php
catalog/model/extension/payment/alipay.php

**Comment by JesseOC** [comment]
@straightlight Would you please show us what is the screen return when you get the Die command message?

And after checking, cannot find the die command in these file, and please show the line
```
catalog/controller/extension/payment/globalpay_remote.php
catalog/controller/extension/payment/realex_remote.php
catalog/model/extension/payment/alipay.php
```

**Comment by lucasjkr** [comment]
he's probably referring to line 165

**Comment by simo-vt** [comment]
Why is the die() command an issue in `system/library/squareup/cron_functions.php`?

It is meant to kill the script in case it is not executed in the command line.

**Comment by danielkerr** [comment]
all above mentioned extensions have been removed from the core.
