### ISSUE TITLE
[v3.0.3.0b - Fix] - controller/extension/payment/amazon_login_pay.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6541]
find:

`$json['selected'] = $this->session->data['lpa']['shipping_method']['code'];`

replace with:

`$json['selected'] = strip_tags(html_entity_decode($this->session->data['lpa']['shipping_method']['code'], ENT_QUOTES, 'UTF-8'));`

**Comment by simo-vt** [comment]
Is this not something which should be fixed in the shipment extension providing this data?

Please refer to:

```$this->session->data['lpa']['shipping_methods'] = $quotes;```

... in `ControllerPaymentAmazonLoginPay::shippingQuotes`

**Comment by danielkerr** [comment]
amazon_login_pay has been moved out of the opencart core. report any issues via the extension page  comments section there.  will add the page soon.
