### ISSUE TITLE
[v3.0.3.0b - Bug] - catalog/controller/extension/payment/klarna_checkout.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6543]
`session_destroy();
			session_id($klarna_checkout_order_data['session_id']);
			session_start();
			$this->session->start('default', $klarna_checkout_order_data['session_key']);`

does not really make sense since OC v3.x releases uses its own session table or file sessions which could create problematics with other sessions by destroying its session locally. I fail to see why we would destroy the session for klarna_checkout . In addition, the $this->session->start method has one switch case from the system/library/session.php file. Two are being addressed in the code.

**Comment by danielkerr** [comment]
externsion removed out of the core and will be in the opencart marketplace soon.
