### ISSUE TITLE
[v3.0.3.0b - Fix] - catalog/model/extension/total/klarna_fee.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6549]
Find:

`$address = $this->session->data['guest']['payment'];`

replace with:

`$address = strip_tags(html_entity_decode($this->session->data['guest']['payment'], ENT_QUOTES, 'UTF-8'));`

Useful for the admin APIs.

**Comment by ADDCreative** [comment]
@straightlight $this->session->data['guest']['payment'] is an array of the address fields. Doesn't want decoding anyway.

**Comment by danielkerr** [comment]
not required
