### ISSUE TITLE
[v3.0.3.0b - Fix] - catalog/model/extension/total/voucher.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6550]
Find:

`if (isset($this->session->data['voucher'])) {`

add below:

`$this->session->data['voucher'] = strip_tags(html_entity_decode($this->session->data['voucher'], ENT_QUOTES, 'UTF-8'));`

Useful for the admin APIs.

**Comment by danielkerr** [comment]
not required.
