### ISSUE TITLE
[v3.0.3.0b - Fix] - catalog/controller/startup/seo_url.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6554]
Find:

`if (preg_match('/' . $result['regex'] . '/', $url_info['query'], $matches)) {`

replace with:

`if (preg_match('/' . $result_regex_quoted . '/', $url_info['query'], $matches)) {`

Then, right above, add:

`$result_regex_quoted = preg_quote($result['regex'], '/');`

Then, find:

`if ($seo['keyword']) {`

replace with:

`if (!empty($seo['keyword'])) {`

**Comment by straightlight** [comment]
Another way would be by using the filter_var with the FILTER_VALIDATE_REGEXP case over the $result['regex'] variable.

**Comment by JesseOC** [comment]
fixed in #6604
