### ISSUE TITLE
[All OC versions] - __get and __set methods

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6559]
An interesting topic created here about the __get and __set instantiation. It seem the current way Opencart initializes them can create problems. StackOverFlow suggest to use the: & at the front of them: https://forum.opencart.com/viewtopic.php?f=190&t=203403#p719763

**Comment by danielkerr** [comment]
It's a long running issue with php that can not be fixed unless on version 7. References can not be used with magic methods. Only in php 7 can u use class kit and add methods.
