### ISSUE TITLE
I can not trigger the event for language or config..!

### ISSUE THREAD

**Issue by bhavhirani** [opencart/opencart#6562]
I'm using opencart version **2.2.0.0** and When I trigger an event for the controller, it runs fine but when I trigger for langauge and config, it gives me the arguments error as follows.

`Catchable fatal error: Argument 2 passed to Action::execute() must be of the type array, string given, called in ...\system\engine\event.php on line 29 and defined in ...\system\engine\action.php on line 29`

i just put code in `...\system\config\catalog.php` file append in `$_['action_event']` array as follow:

`'language/*/before' => 'event/language',`

Is this a bug of opencart?
If there are no bugs, tell me how to trigger the event of langauge and config, and if this is an opencart bug then tell me how to fix this bug.

**Comment by straightlight** [comment]
Using old version of OC.

**Comment by bhavhirani** [comment]
But now I use a lot of modules in my website, so now I can not upgrade to new opencart, so now I am using old version.
But do you have any solution?
