### ISSUE TITLE
currency.php bug at line 141

### ISSUE THREAD

**Issue by andrew4alive** [opencart/opencart#6565]
for open cart 3.0 , the auto currrency converter (yahoo) is broken, that function doesnt work any more.

any update?

**Comment by Pelham81** [comment]
The yahoo currency converter no longer works, and it has been updated to something else. You can look at the master repository to examine the changes for the files associated with currency by doing a search for them. However, there is still no official OC release yet post 3.0.2.0 nor is there a "fix" branch for 3.0.2.0 on github. As a result, I'd hold off unless you know very well what you're doing to update it on a live 3.0.2.0 site.

**Comment by danielkerr** [comment]
there is an extension that fixes this that we provide for free on the extension store.

**Comment by ClaudePlouffe** [comment]
I have updated currency refresh function for v3.0.3.2 using https://api.exchangeratesapi.io/latest.
Hope this helps.

[currency_refresh.txt](https://github.com/opencart/opencart/files/4471518/currency_refresh.txt)
