### ISSUE TITLE
[v3.0.3.0b - Fix] - getOrderRecurrings method - catalog/model/checkout/order.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6567]
In that file,

find:

`public function getOrderVouchers($order_id) {`

add above:

`public function getOrderRecurring($order_id, $product_id) {
		$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "order_recurring WHERE order_id = '" . (int)$order_id . "' AND product_id = '" . (int)$product_id . "'");		
		return $query->row;
	}`

**Comment by prabhatkumaroc082** [comment]
methods getOrderRecurrings and getOrderRecurring are added to Model catalog/model/account/recurring.php in v3.0.3.6
