### ISSUE TITLE
[v3.0.3.0 - Clue] - admin/controller/customer/custom_field.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6568]
This validation:

`if (@preg_match('/' . html_entity_decode($this->request->post['validation'], ENT_QUOTES, 'UTF-8') . '/', null) === false) {
			$this->error['validation'] = $this->language->get('error_validation');
		}`

should rather be used with the filter_var with the REGEXP switch case as per the customer, payment and shipping API already validates with and also use the preg_quote function since the validation process needs to validate an input data from a user.

**Comment by straightlight** [comment]
In addition, the error_validation language definition seem to be missing from the admin/language/en-gb/customer/custom_field.php file nor is it located in the en-gb.php file.

**Comment by danielkerr** [comment]
the code above is for validating that the regex typed by the user is valid. if we used filter_var it will check the regex against something.

**Comment by danielkerr** [comment]
i researched it before and this is the only answer i found.
