### ISSUE TITLE
[v3.0.3.0b - HTML Entity Decode] - All files needing HTML Entity Decode

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6572]
// Referenced by 'name' (also involving other variables and array keys)

admin/controller/catalog/attribute.php
admin/controller/catalog/attribute_group.php
admin/controller/catalog/category.php
admin/controller/catalog/download.php
admin/controller/catalog/filter.php
admin/controller/catalog/manufacturer.php
admin/controller/catalog/option.php
admin/controller/catalog/product.php
admin/controller/catalog/recurring.php
admin/controller/catalog/review.php
admin/controller/common/header.php
admin/controller/customer/customer.php
admin/controller/customer/customer_approval.php
admin/controller/customer/custom_field.php
admin/controller/design/banner.php
admin/controller/design/layout.php
admin/controller/design/seo_regex.php
admin/controller/localisation/country.php
admin/controller/localisation/geo_zone.php
admin/controller/localisation/location.php
admin/controller/localisation/return_action.php
admin/controller/localisation/return_reason.php
admin/controller/localisation/stock_status.php
admin/controller/localisation/tax_rate.php
admin/controller/marketing/affiliate.php
admin/controller/marketing/coupon.php
admin/controller/marketing/marketing.php
admin/controller/marketplace/marketplace.php
admin/controller/marketplace/modification.php
admin/controller/sale/order.php
admin/controller/sale/voucher_theme.php
admin/controller/setting/store.php
admin/controller/tool/upgrade.php
admin/controller/tool/upload.php
admin/controller/user/user_permission.php
admin/model/catalog/category.php
admin/model/catalog/option.php
admin/model/catalog/product.php
admin/model/catalog/product_option.php
admin/model/customer/customer_group.php
admin/model/localisation/language.php
admin/model/user/user_group.php
catalog/controller/account/account.php
catalog/controller/account/download.php
catalog/controller/account/order.php
catalog/controller/account/wishlist.php
catalog/controller/api/cart.php
catalog/controller/api/order.php
catalog/controller/checkout/cart.php
catalog/controller/checkout/checkout.php
catalog/controller/checkout/confirm.php
catalog/controller/common/cart.php
catalog/controller/common/language.php
catalog/controller/common/menu.php
catalog/controller/information/contact.php
catalog/controller/information/sitemap.php
catalog/controller/mail/order.php
catalog/controller/product/category.php
catalog/controller/product/compare.php
catalog/controller/product/manufacturer.php
catalog/controller/product/product.php
catalog/controller/product/search.php
catalog/controller/product/special.php
catalog/model/account/custom_field.php
catalog/model/catalog/category.php
catalog/model/catalog/product.php
catalog/model/localisation/language.php
system/library/cart/cart.php
system/library/cart/tax.php
admin/controller/extension/extension/analytics.php
admin/controller/extension/extension/module.php
admin/controller/extension/extension/theme.php
admin/controller/extension/payment/klarna_checkout.php
admin/controller/extension/report/product_purchased.php
admin/controller/extension/report/product_viewed.php
admin/controller/extension/report/sale_coupon.php
admin/model/extension/payment/cardconnect.php
catalog/controller/extension/module/bestseller.php
catalog/controller/extension/module/featured.php
catalog/controller/extension/module/filter.php
catalog/controller/extension/module/klarna_checkout_module.php
catalog/controller/extension/module/latest.php
catalog/controller/extension/module/special.php
catalog/controller/extension/module/store.php
catalog/controller/extension/payment/amazon_login_pay.php
catalog/controller/extension/payment/divido.php
catalog/controller/extension/payment/eway.php
catalog/controller/extension/payment/klarna_account.php
catalog/controller/extension/payment/klarna_checkout.php
catalog/controller/extension/payment/klarna_invoice.php
catalog/controller/extension/payment/pilibaba.php
catalog/controller/extension/payment/pp_braintree.php
catalog/controller/extension/payment/pp_express.php
catalog/controller/extension/payment/pp_standard.php
catalog/controller/extension/payment/twocheckout.php
catalog/controller/extension/total/shipping.php
catalog/model/extension/payment/pp_express.php
catalog/model/extension/shipping/auspost.php
catalog/model/extension/total/coupon.php

// Referenced by 'title' (also involving other variables and array keys)

admin/controller/catalog/information.php
admin/controller/design/banner.php
admin/controller/localisation/tax_class.php
admin/controller/sale/order.php
admin/model/catalog/information.php
admin/model/design/banner.php
admin/model/localisation/currency.php
admin/model/localisation/length_class.php
admin/model/localisation/weight_class.php
catalog/controller/account/affiliate.php
catalog/controller/account/order.php
catalog/controller/account/register.php
catalog/controller/account/return.php
catalog/controller/affiliate/register.php
catalog/controller/api/cart.php
catalog/controller/api/shipping.php
catalog/controller/checkout/cart.php
catalog/controller/checkout/confirm.php
catalog/controller/checkout/payment_method.php
catalog/controller/checkout/register.php
catalog/controller/checkout/shipping_method.php
catalog/controller/common/cart.php
catalog/controller/common/currency.php
catalog/controller/common/footer.php
catalog/controller/information/information.php
catalog/controller/information/sitemap.php
catalog/controller/mail/order.php
catalog/model/localisation/currency.php
system/library/cart/currency.php
system/library/cart/length.php
system/library/cart/weight.php
admin/controller/extension/payment/klarna_checkout.php
admin/controller/extension/report/sale_shipping.php
admin/controller/extension/report/sale_tax.php
catalog/controller/extension/module/banner.php
catalog/controller/extension/module/carousel.php
catalog/controller/extension/module/html.php
catalog/controller/extension/module/information.php
catalog/controller/extension/module/klarna_checkout_module.php
catalog/controller/extension/module/slideshow.php
catalog/controller/extension/payment/amazon_login_pay.php
catalog/controller/extension/payment/klarna_account.php
catalog/controller/extension/payment/klarna_checkout.php
catalog/controller/extension/payment/klarna_invoice.php
catalog/controller/extension/payment/pp_braintree.php
catalog/controller/extension/payment/pp_express.php
catalog/controller/extension/total/shipping.php
catalog/model/extension/payment/pp_express.php
catalog/model/extension/total/coupon.php
catalog/model/extension/total/reward.php
catalog/model/extension/total/shipping.php
catalog/model/extension/total/voucher.php

**Comment by straightlight** [comment]
With json encoding case, strip_tags also needs to be added along with the html_entity_decode function.

**Comment by danielkerr** [comment]
it does not unless u want cross site scripting attacks.

**Comment by straightlight** [comment]
I understand the point of remote sanitizing but without strip_tags when using the API, users have been reporting alert message window errors on the forum until adding this function. If strip_tags is not a solution, due to security purposes, then an alternate solution needs to be added. Otherwise, these errors won't stop showing persistently.
