### ISSUE TITLE
[v3.0.3.0b - Bug] - No validation with session data during payment and order totals

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6576]
Followed are all files that do not validate the session data with either not empty or isset function nor mentioning to users when these session data fails:

catalog/controller/checkout/guest.php
catalog/controller/extension/payment/alipay_cross.php
catalog/controller/extension/payment/bank_transfer.php
catalog/controller/extension/payment/cheque.php
catalog/controller/extension/payment/cod.php
catalog/controller/extension/payment/free_checkout.php
catalog/controller/extension/payment/klarna_checkout.php
catalog/controller/extension/payment/pp_express.php
catalog/controller/extension/total/shipping.php
catalog/model/extension/payment/divido.php
catalog/model/extension/total/reward.php
catalog/model/extension/total/shipping.php

**Comment by prabhatkumaroc082** [comment]
fix #8984
