### ISSUE TITLE
Incorrect refund amount on eWAY payment module

### ISSUE THREAD

**Issue by NathanDorey** [opencart/opencart#6579]
I'm using Opencart 2.3.0.2, and have found a problem with the native eWay payment module - when refunding orders, the system seems to be only refunding part of the entered amount. 

For example: I entered "6.95" into the refund amount field, and it only refunded $6.00. When I entered "2.60", it only refunded $2.00. In both cases, the "captured amount" was the same as what I entered. Even weirder, when I tried to refund the rest of the captured amount (95c and 60c, respectively), the system suddenly refunded the full amount again - meaning that all up I had refunded nearly double the order amount!

**Comment by NathanDorey** [comment]
P.S. - I went to eWAY themselves, and they confirmed that the amount they were being passed was indeed "600" and "200", respectively. 

The file that I think could hold the issue is "/admin/view/template/extension/payment/eway_order.tpl" (or perhaps the model or controller files).

Thanks in advance for any help anyone can offer!

**Comment by miklcct** [comment]
bug found, rounding error in the model (admin/model/extension/payment/eway.php:145 in master branch) .

Pull request available soon

**Comment by NathanDorey** [comment]
Awesome - that seems to have fixed it nicely! Thanks miklcct!

**Comment by JesseOC** [comment]
Pending to merge to master.
