### ISSUE TITLE
Paypal Express module - no status update after an eCheck clears

### ISSUE THREAD

**Issue by NathanDorey** [opencart/opencart#6582]
I'm using Opencart 2.3.0.2, and have found a problem with the Paypal Express Checkout module. I don't believe that IPNs after the first one (when an order is first made) are being received and acted on by Opencart. This seems to affect eChecks (which are not paid right away), as well as disputes by the customer. Both of these events could occur a number of days after an order has been originally made, and - I would think - update an order's status in Opencart.

For eChecks, I have checked the IPN log in Paypal, and it has shown that two IPNs are sent to "/index.php?route=extension/payment/pp_express/ipn" (one when the eCheck is registered, and one when it is cleared), and that they both get a "200" response. However, it doesn't seem to lead to any kind of update on the order itself (I would expect it to be set to "Complete", if we're dealing with a cleared eCheck).

**Comment by miklcct** [comment]
What is the detail in the IPN?

**Comment by NathanDorey** [comment]
Thanks for jumping in, miklcct!

There was obviously a lot of information, but it all looked right to me. Both the initial IPN (which I'm pretty sure was processed properly by Opencart, since the order came through in the first place) and the second one were nearly identical, except "payment_status" was "Pending" in the first and "Completed" in the second. 

Other important fields were "payer_status=verified", "payment_type=echeck" and "address_status=confirmed". I'm not sure how much to put up, since a lot of it is sensitive information or not really relevant.

**Comment by miklcct** [comment]
Can you please enable debug mode in your PayPal extension, and look for the line "Transaction exists" when the cheque is cleared? Also, can you please check your database table "paypal_order_transaction" and tell us what payment_status is in your relevant transaction?

Refer to source code upload/controller/extension/payment/pp_express.php:1653 in master .

**Comment by NathanDorey** [comment]
Hi miklcct - the payment status in "paypal_order_transaction" is indeed "Completed". I've turned debug mode on, too, but I'm guessing I'll need to wait for another eCheck to clear before getting my hands on the debug information. I'll let you know as soon as another one clears.

In the meantime - it couldn't be an issue with the Complete SEO Package extension, could it? I wouldn't think so, because of the "200" response, but I'm scraping the bottom of the barrel.

**Comment by NathanDorey** [comment]
Update - we've had an eCheck clear, and there definitely was a line in the debug file that read "PayPal Express debug (IPN data): "Transaction exists". 

The line before that contained all the expected transaction information, including:

- "request":"cmd=_notify-validate"
- payment_status=Completed
- an "ipn_track_id" value

Then, the next line simply read "PayPal Express debug (IPN data): "cart"". Is that to be expected?

**Comment by miklcct** [comment]
It seems that ControllerExtensionPaymentPPExpress::ipn() doesn't even touch the order history when it receives IPN from PayPal.

The order history is only touched in expressComplete() and checkoutReturn() methods, which is a design issue.

**Comment by NathanDorey** [comment]
Thanks for the explanation, miklcct. If you _could_ add that handling, that would be incredible!

**Comment by danielkerr** [comment]
has been removed in latest version and is replaced with a new intergration.
