### ISSUE TITLE
left_column.twig Fatal error from internal editor in admin panel

### ISSUE THREAD

**Issue by jun-dev** [opencart/opencart#6584]
Greetings.
When saving the left_column.twig page via the built-in template editor, the Twig Fatal error appears. Specifically, he can not find the page, but in fact it is! In modified it is not present.

To resolve the issue, you need to clear the history of this page.
I ask to correct a bug.
Thank you for attention.

**Comment by JesseOC** [comment]
Hi @jun-dev, which version of OpenCart are you using now?

**Comment by jun-dev** [comment]
https://github.com/opencart/opencart/issues/5966 - similar issue

**Comment by RagingGummyBear** [comment]
Has anyone actually solved this? For me this error happened after i tried to change the common/column_left.twig , i was simply change it to support bootstrap 4. And now I cant load any of the pages without left column, but if I add column they work fine. Even restoring the twig to it's normal state doesn't fix this issue. HALP!

**Comment by JesseOC** [comment]
Hi @RagingGummyBear  I think it is not a solution...
You can also delete the history in admin panel > Design > Theme Editor.

**Comment by RagingGummyBear** [comment]
@JesseOC that restores it to the basic (unchanged). To keep your changes you have to delete it manually from the database. And yes its not a solution but it is a quick fix just to keep working on your theme.

**Comment by JesseOC** [comment]
@RagingGummyBear we have already found a way can fix this issue.
I will commit it later, and you can try to do this in your localhost:

> catalog\controller\event\theme.php

Go to line 46
`} elseif (is_file(DIR_TEMPLATE . $theme . '/template/' . $route . '.twig')) {`
Change to 
`} if (is_file(DIR_TEMPLATE . $theme . '/template/' . $route . '.twig')) {`
