### ISSUE TITLE
Installed extension succesfully on Open Cart 3, but does not working. PLEASE HELP 

### ISSUE THREAD

**Issue by abdulaziz0808** [opencart/opencart#6586]
Hi, 
If anyone could help me please ,  I have installed one extension on Open Cart 3 succesfully, but it does not responding. I make sure that I have installed extension that applicable for version 3. 
it does not show on Modules. but it shows only in Modifications. ANy hellp or support would be much appreciate it. Thanks in advance.

**Comment by osworx** [comment]
1. wrong place to post support requests > goto forum
2. which extension
3. maybe the extension has no module

**Comment by abdulaziz0808** [comment]
No extension had a module, before in open cart 2.3 version but in open cart 3 version does not appear. 
I am sorry where is the forum. Could you please give me an link. I am just desparetely need a help.

**Comment by osworx** [comment]
https://forum.opencart.com/
And - in general - ask/contact before the developer of this extension, this might help most.
And - if bought over the marketplace, ask there - if developer is not responding - for help: https://dedicated.opencart.com/
