### ISSUE TITLE
[v3.0.3.0b - Fix] - admin/controller/marketing/affiliate.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6587]
Find:

`if ($affiliate_info && (!isset($this->request->get['customer_id']) || ($this->request->get['customer_id'] != $affiliate_info['customer_id']))) {`

replace with:

`if ($affiliate_info && (!isset($this->request->get['customer_id']) || (isset($this->request->get['customer_id']) && $this->request->get['customer_id'] != $affiliate_info['customer_id']))) {`

**Comment by danielkerr** [comment]
There is no issue here!~ no idea why you need a isset then !isset was already set.
