### ISSUE TITLE
Opencart 2.3.0.2 after update no image

### ISSUE THREAD

**Issue by nazakar** [opencart/opencart#6589]
Opencart 2.3.0.2 after update no images  . I use shared hosting and same DIR_IMAGE

**Comment by straightlight** [comment]
Using an old version. Please post on the forum for those inquiries.

**Comment by JesseOC** [comment]
Hi @nazakar , for your case, maybe you can send the support ticket to us for checking.
https://www.opencart.com/index.php?route=support/contact
