### ISSUE TITLE
[Bug& Fix] Contact form read store email not customer email -OC 3.0.2.0

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#6593]
`catalog/controller/information/contact.php`

 "From:" is sett to read store settings email

`$mail->setFrom($this->config->get('config_email'));`

And will show customer email in "From:" if you change in this:
`$mail->setFrom($this->request->post['email']);`

https://forum.opencart.com/viewtopic.php?f=202&t=203601

**Comment by JesseOC** [comment]
Hi @condor2 , thanks for the report!
Fixed already on #6594
