### ISSUE TITLE
How to set different theme for one store in opencart ?

### ISSUE THREAD

**Issue by monparaashvin** [opencart/opencart#6596]
I want to set different theme for my one stores. I have copied the /catalog/view/theme/default folder and renamed it to mytheme. But still this mytheme is not added to store theme drop down option.How to add multiple theme in one store.

**Comment by JesseOC** [comment]
Hi @monparaashvin , sorry that it is the not the OpenCart issue of the developing.
We suggest you can send a ticket to OpenCart Support or go to the forum for asking the method.
Thank you!
https://www.opencart.com/index.php?route=support/contact

**Forum**
https://forum.opencart.com

**Comment by monparaashvin** [comment]
Thanks For Anwer..?
