### ISSUE TITLE
issue heading_title overridden

### ISSUE THREAD

**Issue by mgraph** [opencart/opencart#6601]
when adding module to account left side all Account pages shows the module heading_title instead of current page heading_title

ex. when changing "Account Menu module" from right to left position, all account heading_title shows "Account" instead of "Register, Change Password..."

**Comment by mgraph** [comment]
I'm using OC 3.0.2.0 too

![issue](https://user-images.githubusercontent.com/670956/39044529-50facefc-4488-11e8-9daa-f1703164c99b.PNG)

**Comment by straightlight** [comment]
There's a solution posted regarding the left column alignment: https://github.com/opencart/opencart/issues/6584 . See if that fixes the issue.

**Comment by mgraph** [comment]
@straightlight that's not the case here, even if you add a right column the issue appears, so this is a var language related issue

**Comment by AlexChanHK** [comment]
Finally, I know what Daniel did in the master version to solve this case......
Please go to system\config\catalog.php and comment these line
```
'controller/*/after'  => array(
	'event/debug/after'
)
```
and you will see the answer.

**Comment by AlexChanHK** [comment]
Also, if the solution can work, (well, I believe it  99% work)
please close this issue as Daniel don't like too many issue exist.

**Comment by mgraph** [comment]
Thanks @AlexChanHK, that fixed the issue
