### ISSUE TITLE
[v3.0.2] - Large numbers of items in cart slows entire site down

### ISSUE THREAD

**Issue by muskyaaron** [opencart/opencart#6605]
The more products that you add to your cart, the slower the site gets. Around 15 to 20 items is where it really starts to get noticeable. Once you get up around 25 it gets extremely slow. And per one customer's experience, it will eventually bog down so much that it locks up the site and you can't access your account anymore. This only effects the site in this way for that particular user. Others are still able to navigate the site as normal. Has any experienced this and is there a known fix? We are using the base shopping cart that comes with 3.0.2.

Thanks,
Aaron

**Comment by JesseOC** [comment]
We have tested your case but everything runs normally.
Would you please send a ticket to OpenCart Support and give us more details in there?
https://www.opencart.com/index.php?route=support/contact

Thank you!

This ticket will be closed
