### ISSUE TITLE
Admin | Maintenance | Backup produces messages

### ISSUE THREAD

**Issue by keith20mm** [opencart/opencart#6610]
I select Admin | Maintenance | Backup.

A stream of messages "Notice: Undefined index: Tables_in_storeO in C:\WAMP\www\O\admin\model\tool\backup.php on line 9" are produced.

Inspecting admin/model/tool/backup.php I find at line 9:

if (utf8_substr($result['Tables_in_' . DB_DATABASE], 0, strlen(DB_PREFIX)) == DB_PREFIX) {

This line appears to be a substring comparison for the DB_PREFIX. My DB_PREFIX is the default string "oc_"

$result is a pick from the sql store table query "$query = $this->db->query("SHOW TABLES FROM `" . DB_DATABASE . "`");"

I am using OpenCart 3.0.2.0-OpenCart.zip, with 3.0.2.0.

I alter the following:
    foreach ($query->rows as $result) {
        if (utf8_substr($result['Tables_in_' . DB_DATABASE], 0, strlen(DB_PREFIX)) == DB_PREFIX) {
            if (isset($result['Tables_in_' . DB_DATABASE])) {
                $table_data[] = $result['Tables_in_' . DB_DATABASE];
            }
        }
    }

to this code:

    foreach ($query->rows as $result) {
        foreach($result as $key => $field) {
            if (isset($field)) {
                if (utf8_substr($field, 0, strlen(DB_PREFIX)) == DB_PREFIX) {
                    $table_data[] = $field;
                }
            }
     }

This presumes that every result row from the table query contains 1 and only 1 row, and I am sure there are other ways to handle this non-loop expressed as a loop.

The result is that backup now produces no error messages, and the export table list is now populated with all table names.

**Comment by danielkerr** [comment]
dont use capitals in db table names!

**Comment by keith20mm** [comment]
I have no capitals in any db table name.  What are you writing about?  My db name is storeo

I see no capitals in storeo,  Do you?

With that said, do you have a different fix for the error?

Any original code shown is straight from the named distro.

**Comment by danielkerr** [comment]
You put storeO

**Comment by keith20mm** [comment]
Meanwhile, the mysql database name is storeo, hence the index fails.  Changing the config.php define('DB_DATABASE',...   corrects problem.

Side note: Installation instruction (online and videos) contain no name case restriction notation.  Install php script has no uppercase validation, but probably should.

Thank you for your assistance.
