### ISSUE TITLE
HTTP ERROR 500 (In HomePage - WWW.YANZOYA.COM)

### ISSUE THREAD

**Issue by yanzoya** [opencart/opencart#6614]
Please Help Me If Anyone Can Do It.
When I try to open my website www.yanzoya.com it shows me an error HTTP ERROR 500.
I Don't know how it happens because I didn't change anything, please give me a solution.

All Answers Will Be Appreciated

**Comment by florinsith** [comment]
Hello,

Use the forums for support http://forum.opencart.com/

**Comment by munirasim** [comment]
@yanzoya This is file permissions and server issue and isn't related to Opencart in anyway. You may contact someone better at understanding server and file permissions.

**Comment by danielkerr** [comment]
set php to enable error reporting or contact ur host as they might have updated the server.
