### ISSUE TITLE
Issue with order history update using opencart version 2.0.1.1

### ISSUE THREAD

**Issue by nitzsha** [opencart/opencart#6615]
I have a issue with updating the  order history of my customers. i can't do the update when i change the order from pending  to shipping or any other,  it automatically go back to pending. I facing this error since 3 month and i am using the opencart store since 2015 this is the first time a error occur please help me out what i need to do. Please do a reply asap as store is live

**Comment by danielkerr** [comment]
please use the forum. this area is for development not support. there is a support ticket system on the opencart.com site.
