### ISSUE TITLE
Missing style and many other visual bugs after updated OC to ver. 3.1.0.0b

### ISSUE THREAD

**Issue by jun-dev** [opencart/opencart#6616]
Hello.
After updating the store from version 3.0.2.0 to 3.1.0.0b, there were problems with the cache, errors in PHP and problems with the layout of items in the admin panel. In addition, 3d-party modules, stopped working correctly, although they were fully working on version 3.0.2.0.

First I went into the admin area and cleared the cache of themes and sass, updated the page and saw "Fatal error: Class 'Twig_Loader_Filesystem' not found in ...". This error was corrected thanks to this instruction:
 https://forum.opencart.com/viewtopic.php?f=202&t=202985&p=717777#p717777 Thanks to @straightlight for the help.
After the done steps, the working capacity was restored, however the settings of 2 3d-party modules flew. One part of the functional has ceased to work in one of the modules.

After reconfiguring the Matherialize Framework module, I found that CSS styles from a third-party theme are not loaded, which causes the page to display incorrectly.
(Before / After pictures)
![Before](https://i.imgur.com/eotSsso.png)
![After](https://i.imgur.com/QqLkBwD.png)

After that, in the admin panel, I saw some bugs, so, they stopped correctly working with the bootstrap:
(Before / After pictures)
![Before](https://i.imgur.com/kl6a966.png)
![After](https://i.imgur.com/5NOAdNI.png)

![Before](https://i.imgur.com/v7KcJFC.png)
![After](https://i.imgur.com/Ktj7LV4.png)

If something else is found, the post will be updated.

Questions for developers and the community:
1. How to fix the output of CSS styles in head.twig?
2. Why and what did you change in the work of the engine, because of what it partially lost compatibility with 3.0.2.0?

**Comment by danielkerr** [comment]
3rd party modules need to be altered to work with the beta version of opencart.

i suggest u use the stable release.
