### ISSUE TITLE
opencart 3.02 password not working

### ISSUE THREAD

**Issue by howdev** [opencart/opencart#6617]
when you use any passwords containing symbol & from the admin panel. It fails by can't login with error "no match username password" 
When you put the password along with the salt using password generator in the database then can login. So there is something wrong with the change password or the login code. version 2.x does not have this problem

**Comment by danielkerr** [comment]
as far as i can tell there is nothing stopping & being used nor any html conversion before it touches the db.

**Comment by howdev** [comment]
I don't understand. I tried again installing fresh. Every time when I changed the password with & in it I can't log back in. I still trying to find where the problem is.

**Comment by howdev** [comment]
the hash changed somehow when stored in the database. I run the same hash code as in admin/model/user.php outside of opencart and produced different hash using same salt and password containing & symbol. I tested @, #, $ and they all produce same hash

**Comment by howdev** [comment]
also in the admin/model/user/user.php needs add html_entity_decode to addUser function

**Comment by solidus-in** [comment]
@howdev  You are right, I also tried tested and confirm this
