### ISSUE TITLE
when is version (3.0.3.0B) 3.1.0.0 going to be live?

### ISSUE THREAD

**Issue by ThaFridge** [opencart/opencart#6622]
Any idea when you guys are ready to fine tune 3.0.3.0b(current master 3.1.0.0) for live release?

**Comment by lz1nud** [comment]
Daniel will close this thread, but I'm curious too....it's been a long time since last release. Also most of the extensions that work on 3.0,x don't work on the beta here on master branch source.

**Comment by ThaFridge** [comment]
hope we can get a timeframe or a roadmap, because i'm working on 2 big opencart webshop for a client
