### ISSUE TITLE
Ajax Session Issue (checkout)

### ISSUE THREAD

**Issue by mgraph** [opencart/opencart#6633]
Hi,

I notice an issue with OpenCart 3 **checkout session** when trying to move faster through checkout process :
![session_issue](https://user-images.githubusercontent.com/670956/39880599-28b1b822-5476-11e8-9be3-1e4935a609b3.PNG)

I read that this can be fixed using `session_write_close();` to avoid session issue when doing parallel Ajax requests :

https://ma.ttias.be/php-session-locking-prevent-sessions-blocking-in-requests/
http://konrness.com/php5/how-to-prevent-blocking-php-requests/

PS: the screenshot is from the opencart demo website (demo.opencart.com)
 I tested this using "db" and "file" session_engine same result

any idea ?

Thanks

**Comment by danielkerr** [comment]
already fixed in the master and other versions. not sure exactly which version you are using.
