### ISSUE TITLE
update error 2.3.0.2 -> latest

### ISSUE THREAD

**Issue by csgerg** [opencart/opencart#6634]
https://github.com/opencart/opencart/blob/a1d7bc1e6434b8741e8a819238a2bf4e428194fb/upload/install/model/upgrade/1009.php#L23

The problem is in the 1009.php file. Search for 'affiliatee' and correct the spelling to 'affiliate'. Then it will work. http://opencart.com/forum/viewtopic.php?f=199&t=201445#p712546

**Comment by JesseOC** [comment]
Hi @c0b41, you mean the install file in version 3.0.2.0, it was fixed in Master version already.
Thanks for the report
