### ISSUE TITLE
Admin autocomplete select event not getting called

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#6638]
Testing with latest version 

```javascript
$dropdown.on('click', '> a', $.proxy(this.click, this));
```

**Comment by yashbeer** [comment]
Facing the same issue

**Comment by danielkerr** [comment]
master version?

go directly to the js file via your browser and refresh. its a pain. 

its working from my side.

**Comment by howdu** [comment]
Working now cheers. Think I missed one of your last commits to fix it
