### ISSUE TITLE
Custom Theme "Error: A theme has not been assigned to this store!" after activation

### ISSUE THREAD

**Issue by BNEP** [opencart/opencart#6640]
Hello,
i can't find any information about this issue, so my last hope is to drop an issue here.
I have a fresh install of OC Version 3.0.2.0. i followed the instructions which one can find on some websites, how to create a custom theme. For a first try i want to duplicate the default theme, which runs without errors. 

**Following Steps where done:**
* Copy the folder catalog/view/theme/default to catalog/view/theme/MyTheme
* Copy the default files to:
*  /admin/language/en-gb/extension/theme/MyTheme.php
*  /admin/language/de-E/extension/theme/MyTheme.php
* /admin/view/template/extension/theme/MyTheme.twig
* /admin/controller/extension/theme/MyTheme.php
* Modify these files s/theme_default/theme_mytheme/g and s/theme\/default/theme\/MyTheme/g and make language changes.
* Change the controller class name in "ControllerExtensionThemeMyTheme"
* Change stylesheet URL in header template /catalog/view/theme/MyTheme/template/common/header.twig
* BE Extensions/Extensions/Themes activate the new theme "MyTheme"
 -- Here is a little Bug, in list view, the Theme is "Disabled", but in form view if one clicks on edit, it is enabled. Also in database, the theme status is 1
* BE System/Settings edit the default store and set the new theme "MyTheme"

After deleting all cache-files in storagedir/cache and refreshing both caches in BE/dashboard/cog-button pointing the browser to the store FE. Get back an Error "Error: A theme has not been assigned to this store!".

Nothing to see in Log File, neither in Apache Log.
Tested with php5.6 and 7.2 on a absolutely fresh OC installation

Do you have any hint for me? Did i oversee anything?

**Comment by danielkerr** [comment]
save the settings. there ius instructions in the upgrade.txt

**Comment by BNEP** [comment]
Thank you for your comment, 
but if you would read my question, you would see, that i had done that (100 times so far)
You can bet that i have read ALL instructions that i could find, before i write an issue here.
That issue is not solved, but you closed it.

**Comment by traubisoda** [comment]
What fixed for me was to insert the theme status in db by hand:
```
insert into setting (code, `key`, value, serialized) values ('setting', 'theme_THEMENAME_status', 1, 0);
```

**Comment by zdanozdan** [comment]
Can confirm that fix by traubisoda works. Also need to go to settings and modify/save something so oc_setting for all required params could be created for new theme

**Comment by zdanozdan** [comment]
`INSERT INTO `oc_setting` (`store_id`, `code`, `key`, `value`, `serialized`) VALUES (0,'theme_MYTHEME','theme_MYTHEME_status','1',0);`

Probably want to use store_id and proper settings table name = oc_setting

**Comment by traubisoda** [comment]
I did not see this in any guide/tutorial, but I think the correct way to get started with your own template, is to copy the related rows from the settings table (the status at least). 
If you think about it, "normally" your template would have a controller with an install method, which will run if someone installs your template, and inserts your theme settings in the setting table (and do any other stuff ofc), so OC recognizes that your theme is set up and active.
It would be nice to see this mentioned in guides,
