### ISSUE TITLE
Fresh installation - just echoes 'hi' on homepage

### ISSUE THREAD

**Issue by mario-smoljanec** [opencart/opencart#6645]
https://github.com/opencart/opencart/blob/7f2c2609d0d50e23e90f43d4d1fab2d489fdf4ff/upload/catalog/controller/event/theme.php#L33

**Comment by OnixDF** [comment]
I had this same problem, installed another theme and did nothing.

I decided to reinstall the store and it worked well for me.

**Comment by pcmanik** [comment]
Install latest tagged version - 3.0.2.0 and not latest code from master branch.
