### ISSUE TITLE
two serious security bug

### ISSUE THREAD

**Issue by NelionZh** [opencart/opencart#6646]
I have found two serious security bugs, and I wrote a document to explain the two serious security bugs I discovered.But I don’t know how to contact you. If you have checked this message, you can contact me via email(924095871@qq.com).

**Comment by danielkerr** [comment]
pretty easy to contact me or my staff! 

1. web site forum pm system
2. opencart.com contact us page!

seems to be a lot of geniuses that claim to have discovered some undiscovered hacks but don't know how to use a contact us form!
