### ISSUE TITLE
Serious Safety Failure

### ISSUE THREAD

**Issue by OnixDF** [opencart/opencart#6647]
I put my bank offline and went to the store.
Look at the error, the password for the Bank appears.

`Warning: mysqli::mysqli(): (HY000/2002): No route to host in /home/ecoauto-detail/www/loja/system/library/db/mysqli.php on line 7Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /home/ecoauto-detail/www/loja/system/library/db/mysqli.php on line 10Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /home/ecoauto-detail/www/loja/system/library/db/mysqli.php on line 10
Fatal error: Uncaught exception 'Exception' with message 'Error: <br />Error No: ' in /home/ecoauto-detail/www/loja/system/library/db/mysqli.php:10 Stack trace: #0 /home/ecoauto-detail/www/loja/system/library/db.php(31): DB\MySQLi->__construct('mysql.ecoauto-d...', 'db_user', 'PASSWORDHERE', 'db_loja', '3306') #1 /home/ecoauto-detail/www/loja/system/framework.php(80): DB->__construct('mysqli', 'mysql.ecoauto-d...', 'db_user', 'PASSWORDHERE', 'db_loja', '3306') #2 /home/ecoauto-detail/www/loja/system/startup.php(104): require_once('/home/ecoauto-d...') #3 /home/ecoauto-detail/www/loja/index.php(19): start('catalog') #4 {main} thrown in /home/ecoauto-detail/www/loja/system/library/db/mysqli.php on line 10`

**Comment by OnixDF** [comment]
failure of the server that does not let the errors be disabled.
Apologies

**Comment by danielkerr** [comment]
turn error reporting off your site and have it logged.

**Comment by danielkerr** [comment]
its a good point though

**Comment by jamesallsup** [comment]
This has ALREADY been an issue multiple times, so unless the codebase has reverted back again then an old version may be in use?

https://github.com/opencart/opencart/issues/5027

It's been handled multiple times and yes the fix can be made application level - but a production server under no reason EVER should output ANYTHING if an error happens (except a relevant http code page). Logging database passwords however is not exactly the correct approach either as there is still a security issue if the htaccess is not enabled restricting .log / .txt files from being shown.

Dan just check on the last fix and revert to throw the error and not the exception data (I  assume that was it so worth checking again)
J

**Comment by danielkerr** [comment]
ill switch to exit commmand.

**Comment by danielkerr** [comment]
edit the system/config/default.php

change the value 

$_['error_display']        = true;

to

$_['error_display']        = false;

**Comment by OnixDF** [comment]
I'll do it later, Thanks Dan.

**Comment by danielkerr** [comment]
im closing this as nothingb can be done unless error reporting is turned off. I'm sire there is some info some were telling uses to do this. its only set the way it is is so that people can see what errors are happenign duing installation and not for production.
