### ISSUE TITLE
Opencart reward points and points in the options of a product

### ISSUE THREAD

**Issue by cvdpol01** [opencart/opencart#6648]
Situation: Product has reward points e.g. 200
Option 1:  have 10 point.

Problem: The reward points of the options are not getting calculated with the product reward points. All options have the basic reward points 200.

I think, this should be 210 reward points. The 200 of reward points and the 10 reward points whats given in the options table of the product.

**Comment by straightlight** [comment]
Please post in the OC forum for inquiry requests.

**Comment by danielkerr** [comment]
i think its the points to buy not points made.
