### ISSUE TITLE
contact.php controller missing language line

### ISSUE THREAD

**Issue by bluekable** [opencart/opencart#6652]
The success method in "catalog/controllers/information/contact.php" is missing the line:

`$data['text_message'] = $this->language->get('text_success');`

I think that it should use this to set the message that will be output on the common/success view when someone has successfully sent through a message.

Super easy fix but I do not yet know how to use Github to contribute to a project so this bug will have to do for now.

Regards
Bluekable

**Comment by schiggi** [comment]
It has already been fixed in this [commit](https://github.com/opencart/opencart/commit/abaaf8942b3d9d4b50c0b7869e0347ee8534452f).

**Comment by bluekable** [comment]
Thanks schiggi,

I recently downloaded OpenCart and installed and the line was not there. I had to add it manually.

Regards
