### ISSUE TITLE
Error in API Query

### ISSUE THREAD

**Issue by tshragarwal** [opencart/opencart#6654]
I try to use opencart api. But it is no working. After dig, found error in query.
SELECT * FROM `" . DB_PREFIX . "api` WHERE `username` = '" . $this->db->escape($username) . "' `key` = '" . $this->db->escape($key) . "' AND status = '1'"

its should be

SELECT * FROM `" . DB_PREFIX . "api` WHERE `username` = '" . $this->db->escape($username) . "' AND `key` = '" . $this->db->escape($key) . "' AND status = '1'"

find file in model / api

Please fix this in upcoming release.

**Comment by straightlight** [comment]
Cannot be tracked in v3.0.2.0 or v3.0.3.0b release either. Reported issue is probably about an older OC release.

**Comment by permalytics** [comment]
Hi, I can confirm the same bug w/ version 3.0.2.0. Additionally I found an uninitialized $config variable here: (shop/catalog/controller/api/login.php)

@line 30:
// $session = new Session($config->get('session_engine'), $registry);
//	tried, but does not work either: 
//	$session = new Session($this->config->get('session_engine'), $registry);
//				$session->start();
// using $this->session instead solved the problem: 
				$session=$this->session;

**Comment by florinsith** [comment]
$session = new Session($this->config->get('session_engine'), $this->registry);

should work.
