### ISSUE TITLE
Unnecessary LEFT JOIN in getTotalReviewsByProductId and getReviewsByProductId

### ISSUE THREAD

**Issue by optimlab** [opencart/opencart#6656]
[catalog/model/catalog/review.php](https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/review.php)

Why do we need these LEFT JOIN if we can make them shorter?

In 2 methods, the modification example query:
1. **getTotalReviewsByProductId**
`$query = $this->db->query("SELECT COUNT(*) AS total FROM " . DB_PREFIX . "review WHERE product_id = '" . (int)$product_id . "' AND status = '1'");`

2. **getReviewsByProductId**
`$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "review WHERE product_id = '" . (int)$product_id . "' AND status = '1' ORDER BY date_added DESC LIMIT " . (int)$start . "," . (int)$limit);`

**Comment by schiggi** [comment]
For `getReviewsByProductId` you will need the product name, price and image.
For `getTotalReviewsByProductId`, indeed it does not look relevant.

**Comment by optimlab** [comment]
What are they for if the product name, price and image are not used?

**Comment by straightlight** [comment]
To pull the product description language ID and to know if the product status is still active along with the review status in order to pull the reviews statistical results.

**Comment by optimlab** [comment]
What's the point? Reviews are downloaded after loading the product page. We a priori know all the data about the product.

**Comment by straightlight** [comment]
The reviews table does not contain the details of the product. It only contains their references. By just keeping the reviews table, how would merchants know the details of those products once being rated would be in question if the JOINs were removed without importing the full details into the reviews table itself which would be considered redundancy of data (except for the orders).

**Comment by WebkulOpencart** [comment]
There is no any such reason to remove the left Join as I checked the above comments so closing this issue

**Comment by optimlab** [comment]
> 
> 
> There is no any such reason to remove the left Join as I checked the above comments so closing this issue

It's a shame that you can't see. You disappointed me.
