### ISSUE TITLE
Fatal Installation Bug 3.0.2.0

### ISSUE THREAD

**Issue by russellbrewer** [opencart/opencart#6660]
Fresh installation OC 3.0.2.0

https://github.com/opencart/opencart/blob/master/upload/system/startup.php

Line #98 looks for system/engine/reference.php which does not exist. Since this is a required call, installation halts. 

Removing line #98 will allow installation to proceed.

**Comment by straightlight** [comment]
This issue seem to have been fixed very recently: https://github.com/opencart/opencart/commit/fe0b6910c5a2fd2ab1f2980faf3196b56f7cb853 . :)

**Comment by danielkerr** [comment]
not 3.0.2.0! 3.1.0.0 alpha
