### ISSUE TITLE
Opencart admin page 500 error

### ISSUE THREAD

**Issue by vdkict** [opencart/opencart#6662]
Hello,

I am new on OpenCart en a friend of my have a old version (I think old version) of opencart webshop.

The normal site is working, buth the admin page i get a ERROR 500 page en cannot find the wrong setting.

Can anybody help me?
Many thanks!

**Comment by vdkict** [comment]
Hallo,

why doe you direcly closed my ticket?

**Comment by danielkerr** [comment]
this is a not a ticket nor a support system! forum or contact us form are for support.

**Comment by MrPlow254** [comment]
Also, read the readme, That explains your steps of how to react to an error. 
https://github.com/opencart/opencart/blob/master/README.md
