### ISSUE TITLE
Why does catalog/controller/common/home.php add a canonical $this->config->get('config_url') link?

### ISSUE THREAD

**Issue by mehov** [opencart/opencart#6665]
Hi everyone,

[catalog/controller/common/home.php#L9](https://github.com/opencart/opencart/blob/3e3feaa3ac6905a91f605cb61cc288d61013ca41/upload/catalog/controller/common/home.php#L9) adds a canonical link to `$this->config->get('config_url')` only if `isset($this->request->get['route'])`. Why?

	if (isset($this->request->get['route'])) {
		$this->document->addLink($this->config->get('config_url'), 'canonical');
	}

**Comment by danielkerr** [comment]
check the history of the file. i think some one pushed it. not sure its necessary aswell. i think some dispshit decided it was required for www and non www urls

**Comment by mehov** [comment]
Removed in https://github.com/opencart/opencart/commit/0fa9d2ff70ae539302b3e4d86ef5fdceffa75a18#diff-a81d85fe9eb0c0a1137142cef77a6065, in case anyone's wondering

Thanks Daniel
