### ISSUE TITLE
Some `$this->url->link()` calls don't respect store's config_secure setting

### ISSUE THREAD

**Issue by mehov** [opencart/opencart#6666]
Hi everyone, 

For example, [catalog/controller/common/footer.php#L14](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/common/footer.php#L14) *always* produces a plain HTTP link.

Currently websites are encouraged to switch to HTTPs. Potential problems in this case: 

- a website may not have HTTP->HTTPs server redirect configured, resulting in duplicate content
- according to [Moz](https://moz.com/blog/301-redirection-rules-for-seo), "*All redirects carry a degree of SEO risk*"
- each redirect takes time and introduces delays

Ultimately, the fewer moving parts, the better. I believe the solution would be choosing protocol according to the corresponding store's *Use SSL* setting. Here's the way I'd solve this:

	'href'  => $this->url->link('information/information', 'information_id=' . $result['information_id'], $this->config->get('config_secure'))

Is this safe? Will the contributions on this be welcomed?

**Comment by straightlight** [comment]
Not really, since extension developers would still have the choice to either add or not add the config_secure key as a switch case.

**Comment by mehov** [comment]
The extension developers can do anything they want. I'm talking about the core here.

Specifically, [catalog/controller/product/product.php#L557](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/product/product.php#L557) which is breaking on an HTTPs site as the browser won't allow loading non-secure content by default

**Comment by danielkerr** [comment]
$this->config->get('config_secure')

has been removed! set https or http in the config.php

these are not redirects! 

you need to learn more about opencart before posting issues or giving advice!
