### ISSUE TITLE
[v3.1.0.0alpha] - "Extension -> Marketplace" is not showing any purchased extensions

### ISSUE THREAD

**Issue by Kiu78** [opencart/opencart#6675]
Entering the OpenCart Marketplace API-Infos worked (no red alert button, but gear-icon is shown)...
But clicking on "Purchased" is not showing any extensions (we have bought about 30 extensions).
This bug also exists in OC3.0.2.0.

As this function is the most comfortable way to install extensions, this should be fixed (the interest of extension-developer should be really high, as this is the interface, where they earn money).

**Comment by danielkerr** [comment]
will be fixed in the next version. use the upload system for now.
