### ISSUE TITLE
FedEx shipping extension does't save services selections

### ISSUE THREAD

**Issue by TheRealDJ** [opencart/opencart#6682]
OpenCart Versions: 3.0.2.0, 3.0.1.1
PHP Version: 5.4.40

After selecting services on the FedEx shipping extension and clicking save, the message "Success: You have modified Fedex shipping!" is displayed. Then click the edit button on the FedEx extension, no services are selected.

**Comment by danielkerr** [comment]
externsion removed out of the core and will be in the opencart marketplace soon.
