### ISSUE TITLE
FedEx shipping extension has old FedEx web services URL

### ISSUE THREAD

**Issue by TheRealDJ** [opencart/opencart#6683]
OpenCart Versions: 3.0.2.0, 3.0.1.1
PHP Version: 5.4.40

Extension uses production URL 'https://gateway.fedex.com/web-services/' and testing URL 'https://gatewaybeta.fedex.com/web-services/'.

FedEx documentation lists production URL 'https://ws.fedex.com:443/web-services/' and testing URL 'https://wsbeta.fedex.com:443/web-services/'.

**Comment by danielkerr** [comment]
removed from core. will have extension page on opencart.com soon.
