### ISSUE TITLE
Strange variable in  catalog/language/[...]/extension/payment/eway.php 

### ISSUE THREAD

**Issue by gizmecano** [opencart/opencart#6685]
I wonder if this variable is correct (as is, it seems only be used in the language pack):

https://github.com/opencart/opencart/blob/1a1655ae9225bff366e5ef686ea07dcfc07066f5/upload/catalog/language/en-gb/extension/payment/eway.php#L39

Should it be something like `text_card_message_check_api` for example?

**Comment by straightlight** [comment]
Intended from catalog/controller/extension/payment/eway.php file:

`140   				$error = $this->language->get('text_card_message_' . $error);
    183   					$error = $this->language->get('text_card_message_' . $error);
    198   							$lbl_error .= $this->language->get('text_card_message_' . $error);
    202   						$log_error .= $this->language->get('text_card_message_' . $error) . ", ";
    237   						$log_error .= $this->language->get('text_card_message_' . $error) . ", ";
`

**Comment by gizmecano** [comment]
I'm not sure, unless `Please check the API Key and Password` is an valid error code (as those intended in lines 41-235, such as `V6000` for example).

Moreover, the use of whitespaces isn't common among OpenCart variables (which generally uses underscores).

It is for these reasons that I wonder about the actual use of the variable named in this way.

**Comment by straightlight** [comment]
One way of solving this would be by using a replaced statement from the provided codes above:

`$error = preg_replace('/[[:blank:]]/', '_', html_entity_decode(strtolower($error), ENT_QUOTES, 'UTF-8'));`

Then, on the language file:

`$_['text_card_message_please_check_the_api_key_and_password'] = 'Please check the API Key and Password';`

**Comment by danielkerr** [comment]
removed from the default. any fixes required for extension needs to be handled by the payment gateway. this extension is moved to the extension store.
