### ISSUE TITLE
https://github.com/opencart/opencart/wiki/Modification-System

### ISSUE THREAD

**Issue by MrPlow254** [opencart/opencart#6686]
Please change the attributes to be lowercase. I spent a few hours wondering why my code was being repalced when I had < add position="After" >. It was ignoring the "After" switched it to lowercase < add position="after" > and now works. Also make a note that it is case sensitive.

**Comment by straightlight** [comment]
I am not sure I understand this inquiry. Using the utf8-general-ci from the database should not involve doing any of this ...

**Comment by osworx** [comment]
@straightlight as it seems.
He is talking about that here:
https://github.com/opencart/opencart/wiki/Modification-System
and
`Allowed Attributes

       position="(Replace|Before|After)"
    `
The names of the attributes is simply wrong, they should be all lowercase!

**Comment by jamesallsup** [comment]
Updated.
