### ISSUE TITLE
MINOR - "Localization" spelled incorrectly

### ISSUE THREAD

**Issue by TheRealDJ** [opencart/opencart#6687]
THIS DOES NOT EFFECT OPENCART FUNCTIONALITY!!!

Correct spelling is "Localization"

"grep -r 'Localisation' *" shows 40 references on version 3.0.1.2

**Comment by stalker780** [comment]
It's not a bug. It's an OpenCart feature since v1.4 :) Maybe even earlier.

All OC VQMod and OCMod extensions search for "localisation". 

This change will break whole infrastructure of OC :)

**Comment by stalker780** [comment]
https://en.wikipedia.org/wiki/Oxford_spelling

**Comment by jamesallsup** [comment]
It is the English spelling, since the default language code is en-gb then it is correct.

You can create a language pack en-us and change to all US type spelling if required.

**Comment by TheRealDJ** [comment]
I was unaware of the multiple correct spellings. Sorry to open an unnecessary issue.
