### ISSUE TITLE
[v3.0.3.0b] - Clean double and above white spaces and hard coded lines in TWIG files

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6691]
317 (double white spaces): view/theme/default/template/checkout/checkout.twig
16 and 19 (hard coded): view/theme/default/template/extension/module/amazon_pay.twig
6 and 9 (hard coded): view/theme/default/template/extension/payment/amazon_login_pay_address.twig
7, 10, 16, 19 (hard coded): view/theme/default/template/extension/payment/amazon_login_pay_confirm.twig
6 and 9 (hard coded): view/theme/default/template/extension/payment/amazon_login_pay_payment.twig
385, 387 and 389 (multiple white spaces): view/theme/default/template/extension/payment/divido.twig

**Comment by danielkerr** [comment]
will start fixing stuff soon. really stuck on twig. its implementation is ridiculous. you can not extend classes as they use private properties.

**Comment by straightlight** [comment]
Couldn't agree more. Other than creating our own functions with TWIGs, it is unlikely possible to propagate classes from the main constructors; only the modulated ones.

**Comment by jamesallsup** [comment]
All of the trash whitespace, incorrect indents, code formats etc will get picked up when I get round to sorting out the Jenkins server again - more priorities than whitespace to fix for now.
