### ISSUE TITLE
[v3.0.3.0b - Fix] - All controller files not validating config array keys compared to others

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6694]
Should be validating with the 'is_array' function like other controller files since these arrays provides no guarantee on being configured on first sight since new users may (and probably will) not know on the spot how to configure these without assistance on anyhow.

- catalog/controller/event/statistics.php (config_complete_status)
- catalog/controller/mail/affiliate.php (config_mail_alert)
- catalog/controller/mail/register.php file (config_mail_alert)
- catalog/model/catalog/review.php (config_mail_alert)
- catalog/model/checkout/order.php (config_complete_status - line 351)

- install/controller/startup/language.php

replace:

`if (isset($this->request->server['HTTP_ACCEPT_LANGUAGE'])) {`

with:

`if (isset($this->request->server['HTTP_ACCEPT_LANGUAGE']) && is_resource($languages)) {`

- catalog/controller/extension/total/voucher.php (config_complete_status)
- catalog/model/extension/payment/amazon_login_pay.php (config_mail_alert)

**Comment by danielkerr** [comment]
this is why the type cast (array) is used

**Comment by danielkerr** [comment]
also these settings are pre confirgured

**Comment by danielkerr** [comment]
is_resource($languages) !!!!! why is_resource

its a glob! so it returns false, null or an empty array!

**Comment by danielkerr** [comment]
fixed in lats commit

**Comment by straightlight** [comment]
I take it back for the is_resource. This suggestion was provided on the forum before and thought it would of fixed the issue. Today, it took a bit of research to find out that Stackoverflow confirms it's an OS issue while using the GLOB_BRACE switch case. Granted, the type cast uses an array. However, it has been known that even with an empty array, in this case, an error message could be returned as it is also being discussed on the forum occasionally.

Followed is a GitHub link containing a fix that should also be considered as an helper file in OC which despites the OS being used while using GLOB_BRACE: https://github.com/jeedom/core/commit/4955bbd84d52525251802894512121269e87ab92
