### ISSUE TITLE
[Github file - Fix] - upload/admin/controller/extension/fraud/fraudlabspro.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6695]
`$this->db->query("TRUNCATE `" . DB_PREFIX . "fraudlabspro`");`

for:

`$this->db->query("TRUNCATE TABLE `" . DB_PREFIX . "fraudlabspro`");`

private function fix_case($s) {
 		$s = ucwords(strtolower($s));
		$s = preg_replace_callback("/( [ a-zA-Z]{1}')([a-zA-Z0-9]{1})/s", create_function('$matches', 'return $matches[1].strtoupper($matches[2]);'), $s);
		$s = preg_replace_callback("/( [ a-zA-Z]{1}')([a-zA-Z0-9]{1})/s", function($matches){ return $matches[1].strtoupper($matches[2]); }, $s);
 		return $s;
 	}

uses fix_case (underscore) with private function rather than protected function. However, shouldn't this also be added as an helper file instead?

**Comment by LJK-opencartmods** [comment]
On my phone, but shouldn’t there be a space between TABLE and the close quote?

**Comment by danielkerr** [comment]
has been removed from the core. will have an extension page added soon.
