### ISSUE TITLE
templates hijacking

### ISSUE THREAD

**Issue by martin-angelov1992** [opencart/opencart#67]
http://demo.opencart.com/catalog/view/theme/default/template/common/home.tpl
Since opne source this I guess is not a big problem but usually tpl files should be outside public folder, in case user might want to change somehting in template and keep code in private.

**Comment by arnisjuraga** [comment]
Still, this IS a quite an issue ...

**Comment by arnisjuraga** [comment]
> also anyone can copy anothers template by just clicking view source.

WHAAT?! :)

View source `does not` have PHP code,  HTML is already compiled.

**Comment by CoverUp** [comment]
this exists years ago
<FilesMatch "(?i)((\.tpl|\.ini|\.log|(?<!robots)\.txt))">
 Order deny,allow
 Deny from all
</FilesMatch>

you can always get a template, the fact that is compiled, just make it a little harder, but you can get it anyway. People that believe that a template cannot be copied just don't understand how internet works.
