### ISSUE TITLE
[v3.0.3.0b - Fix] - PHP Throwables compatible with PHP 7

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6700]
Since Opencart now focuses on PHP 7, it would be important to consider the catch errors: http://php.net/manual/en/language.errors.php7.php . Exception and ErrorException are rather being suggested to be used with: Throwable catches. Some vendor files in Opencart already uses them in anyhow but this solution is not part of the core.

An alternative solution could also be used with the combination of: ArithmeticError | Exception in the catch statement.

**Comment by straightlight** [comment]
All files using Exception case:

- install/cli_install.php (line 300)
- system/library/template/twig.php (line 29)
- admin/controller/extension/payment/divide.php (line 155)
- admin/model/extension/payment/cardinity.php (line 27, 41, 55, 69)
- admin/model/extension/payment/klarna_checkout.php (line 16, 28, 40, 52, 64, 76, 88, 100, 112, 125, 138, 151)

- admin/model/extension/payment/pp_braintree.php (line 12, 32, 52, 72, 92, 112, 129, 150)
- catalog/controller/extension/payment/cardinity.php (line 79)
- catalog/model/extension/payment/amazon_login_pay.php (line 512)
- catalog/model/extension/payment/cardinity.php (line 29, 48)
- catalog/model/extension/payment/klarna_checkout.php (line 13, 25, 38, 50, 239)
- catalog/model/extension/payment/pp_braintree.php (line 12, 28, 44, 62, 78, 94, 110, 126)

**Comment by danielkerr** [comment]
can u post some examples of how this should be implemented?

its great it has this feature and you want to implemented but what is it actually solving.

you have posted no solution to a no problem.

**Comment by danielkerr** [comment]
should we catch the error and pass the exemption to the error page.

**Comment by straightlight** [comment]
Absolutely not. Since we're talking about explicit error details, showing them on the error page may affect the store's reputation while on the other way around to rely on user permissions may also limit top administrators to view the details of that reported error.

To keep focusing on the error logs or display errors while showing explicit details would be the right path as best practices and security purposes.
