### ISSUE TITLE
PHP7.1+ required

### ISSUE THREAD

**Issue by yogesh-kamble** [opencart/opencart#6702]
I setup apache2, mysql locally.
Once I hit the site in Browser I get "PHP7.1+ required" I installed php7.2 on ubuntu but still get same issue. Any Idea What am I missing ?

**Comment by danielkerr** [comment]
must be the masterbranch. ill fix it.

**Comment by MrPlow254** [comment]
i'm running off of the masterbranch and don't get this issue. I'm using apache on windows however.

**Comment by maxigsilva** [comment]
I've the same issue. Why this happend?

**Comment by danielkerr** [comment]
ok should be fixed now.
