### ISSUE TITLE
Opencart 3.0.2.0 filemanager add and delete buttons missing

### ISSUE THREAD

**Issue by m3lvm** [opencart/opencart#6705]
I have an issue wher the filemanager buttons add and delete have completely disappeared from the site.

**Comment by jamesallsup** [comment]
Sorry to hear you have an issue, the GiHub bug tracker is not the place to post issues relating to setup, 3rd party modules or general types of questions.

Please read the [project information page](https://github.com/opencart/opencart/blob/master/README.md#reporting-a-bug-and-security-issues) which should guide you in the right direction for support.

Kind regards, J
