### ISSUE TITLE
[v3.0.3.0b - Hardcoded] - All hardcoded texts

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6706]
All hardcoded texts.

Admin files: 

- admin/view/template/marketplace/marketplace_reply.twig
- admin/view/template/marketplace/marketplace_comment.twig
- admin/view/template/marketplace/marketplace_list.twig
- admin/view/template/tool/upgrade.twig
- admin/view/template/extension/fraud/fraudlabspro.twig
- admin/view/template/extension/payment/amazon_login_pay.twig
- admin/view/template/extension/payment/bluepay_hosted_order.twig
- admin/view/template/extension/payment/bluepay_redirect_order.twig
- admin/view/template/extension/payment/cardconnect_order.twig
- admin/view/template/extension/payment/cardinity_order_ajax.twig
- admin/view/template/extension/payment/eway_order.twig
- admin/view/template/extension/payment/firstdata_remote_order.twig
- admin/view/template/extension/payment/g2pay_order.twig
- admin/view/template/extension/payment/globalpay_order.twig
- admin/view/template/extension/payment/globalpay_remote_order.twig
- admin/view/template/extension/payment/pilibaba.twig
- admin/view/template/extension/payment/pp_braintree.twig
- admin/view/template/extension/payment/realex_order.twig
- admin/view/template/extension/payment/realex_remote_order.twig
- admin/view/template/extension/payment/sagepay_direct_order.twig
- admin/view/template/extension/payment/sagepay_server_order.twig
- admin/view/template/extension/payment/securetrading_pp_order.twig
- admin/view/template/extension/payment/securetrading_ws_order.twig
- admin/view/template/extension/payment/worldpay_order.twig

Catalog files:

- caralog/view/theme/default/template/common/cart.twig
- catalog/view/theme/default/template/information/tracking.twig
- catalog/view/theme/default/template/extension/module/amazon_login.twig
- catalog/view/theme/default/template/extension/module/amazon_pay.twig
- catalog/view/theme/default/template/extension/module/divido_calculator.twig
- catalog/view/theme/default/template/extension/module/pilibaba_button.twig
- catalog/view/theme/default/template/extension/payment/amazon_login_pay_address.twig
- catalog/view/theme/default/template/extension/payment/amazon_login_pay_confirm.twig
- catalog/view/theme/default/template/extension/payment/amazon_login_pay_payment.twig
- catalog/view/theme/default/template/extension/payment/divido.twig
- catalog/view/theme/default/template/extension/payment/divido_calculator.twig
- catalog/view/theme/default/template/extension/payment/eway.twig
- catalog/view/theme/default/template/extension/payment/eway_iframe.twig
- catalog/view/theme/default/template/extension/payment/firstdata_remote.twig
- catalog/view/theme/default/template/extension/payment/klarna_account.twig
- catalog/view/theme/default/template/extension/payment/klarna_checkout_sidebar.twig
- catalog/view/theme/default/template/extension/payment/klarna_invoice.twig

**Comment by jamesallsup** [comment]
Could you explain on these a bit more? Do you mean there is hard coded language strings? If so can you link a few line examples

Thanks J

**Comment by osworx** [comment]
@jamesallsup e.g.: https://github.com/opencart/opencart/blob/0d1fc8bbd0635329ce59f50eebb4d80f24253647/upload/admin/view/template/marketplace/marketplace_reply.twig#L13

For translations it would be 'very' helpfully to replace such 'hardcoded' text parts with strings asap

**Comment by vivek-webkul** [comment]
[Fixed some undefined index issues on Marketplace comment section and language index missing issues.]
![extension marketplace](https://user-images.githubusercontent.com/28401696/45915173-37ffef80-be6e-11e8-940d-6f0bccbeaabd.jpg)

**Comment by vivek-webkul** [comment]
Added the translations in the language files for all the mentioned file's path.

**Comment by straightlight** [comment]
Cheers !

**Comment by WebkulOpencart** [comment]
fixed hardcoded text for all the files.
