### ISSUE TITLE
Fresh Installation of the latest master-branch-version not working as expected

### ISSUE THREAD

**Issue by Kiu78** [opencart/opencart#6707]
Hello,

I installed a complete new version. Something seems not to work as expected. This is a screenshot of the "/admin"

![grafik](https://user-images.githubusercontent.com/40320980/42174997-5dc97f7c-7e24-11e8-825b-e291b2322693.png)

and this is a screenshot, after loggin into the admin
![grafik](https://user-images.githubusercontent.com/40320980/42175101-b510e5ae-7e24-11e8-8696-4b0aa4487ac7.png)

I didn't get any errors at the installation.

**Comment by straightlight** [comment]
Without knowing if you did captured your screenshot with or without the left menu, did you installed the extensions from your admin - > extensions - > extensions - > reports page?

Also, if you hit the F12 function key on your keyboard then go to the Console tab, do you see error messages on that tab once viewing the total orders, total sales, total customers and people online?

**Comment by straightlight** [comment]
Also, did you read the install.txt file from the downloaded ZIP file to configure the folder permissions recursively?

**Comment by MrPlow254** [comment]
This happened to me as well, but I didn't do a fresh install. I did a pull. The fix was deleting the storage folder and running the install script again. This happened when @danielkerr did the twig update. I expected that to break cached files.

**Comment by Kiu78** [comment]
Hello Straightlight,

thanks for your reply. Here are my answers to your questions:
- the screenshot shows the whole brower-area
- there is no left-menu
- there are no other extensions installed. The screenshots are taken right after the installation
- config.php and /admin/config.php are set to 777
- these are the errors, if I go to "orders"
![grafik](https://user-images.githubusercontent.com/40320980/42205628-4faa2488-7ea5-11e8-8946-2e17eb3af558.png)

**Comment by Kiu78** [comment]
@MrPlow254: I deleted the "system/storage" folder without success. Now, I have a lot of other error-messages. Maybe, I did something wrong here?

**Comment by MrPlow254** [comment]
@kiu78 you need to re run the installer. You might need to clear your config files for it to run. All your MySQL data will stay, but make a backup anyway if there are things you want to keep.

I think it has to do with twig. I had the exact same issue. All your style sheets are loading or it would look even more of a mess.

**Comment by PhamToan** [comment]
@Kiu78 
I have same error and i deleted all files and folders in system/storage/cache (excluded index.html)
now it is working fine!

**Comment by Kiu78** [comment]
Hello,

I completely reinstalled OC for testing purposes again and had the same issues.
Then, I also deleted all files and folders in system/storage/cache (excluded index.html)

This also solved the problems.

I hope, this helps the dev-team to find the basic issue.

**Comment by Kiu78** [comment]
@straightlight @danielkerr 
The above described issue can be fixed with the workaround:
Deleting all files and folders in system/storage/cache (excluded index.html)

As I'm not a developer, I don't know, what causes the issue...also I'm not sure, if I can close this issue?!
Or do you close the issue, after fixing it?

Kind regards
Kiu
