### ISSUE TITLE
Unnecessary load model in catalog/controller/information/sitemap.php

### ISSUE THREAD

**Issue by optimlab** [opencart/opencart#6712]
[catalog/controller/information/sitemap.php](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/information/sitemap.php)
$this->load->model('catalog/product');

**Comment by straightlight** [comment]
Confirmed. Also found in v3.0.3.0b release.

**Comment by ilcomp** [comment]
Сut out sitemap. Now this system is considered obsolete. (translated with google)
