### ISSUE TITLE
[3.0.2.0] Order status set to 0 through all payment modules

### ISSUE THREAD

**Issue by LybaNL** [opencart/opencart#6714]
Orders are saved with order_status 0
![image](https://user-images.githubusercontent.com/18228102/42261765-848a58e8-7f69-11e8-9d2b-40d64de9cac3.png)

The customer is redirected to the confirmation page but due to the 0 status the order is not visible to the administrator in Opencart and no e-mail notifications are sent.

Similar to the issue reported on the [forum](https://forum.opencart.com/viewtopic.php?t=200655)

**Comment by straightlight** [comment]
Did you configured your order processing and complete statuses from your admin - > systems - > settings - > edit settings page?

**Comment by danielkerr** [comment]
resave you payment gateway settings. this issue is caused a lot of time after you delete a order status being used by the payment gateway then you readd it again.
