### ISSUE TITLE
Comments and the ability to answer them in product page

### ISSUE THREAD

**Issue by mfadel85** [opencart/opencart#6715]
Hello everyone, I don't know if my issue is repeated but I didn't found it in any old issue,
I believe that adding comment tab in product page with the ability of the admin to answer that comment would be very useful. 

You might say that there are modules for that, but there are not compatible with every theme and it may cause some problems, I guess the best thing is to be included in the system.
Right now the users are only able to write reviews, but no ability to answer these reviews, if a visitor asks writes something in the product page there is no way to answer it directly.

**Comment by straightlight** [comment]
The issues tab on Github is NOT about posting suggestions without root cause. Please post in the Pull Requests section to suggest new features.

**Comment by mfadel85** [comment]
okay I am closing this
