### ISSUE TITLE
Affiliate custom datetimepicker fields issue?  3.0.2.0 (not saved)

### ISSUE THREAD

**Issue by monolithforge** [opencart/opencart#6716]
I noticed, while trying to convert everything to bootstrap4 datetimepicker with tempusdominus/bootstrap-4 that the affiliates aren't listening/recording custom field dates (or maybe not even custom fields in general?).

Is this something that needs looked into for upcoming versions?

see: https://github.com/monolithforge/opencart-bootstrap4-theme-basic.ocmod/commit/cc3730ca6bf3388792356528bd0e876a0be2bd0e

There were also a few instances where date was listed twice (instead of datetime) in the TWIG loops.  Is this a bug I'm not aware of?

-MF

P.S. KEEP UP THE GOOD WORK!!

**Comment by monolithforge** [comment]
Testing:

Create a Customer/Custom Field for each of the three: (date, datetime, time) and set with the option of affiliate.

Then set all three to affiliate.

These custom fields to not record into the db- that I've noticed.

Confirm this?

-MF

**Comment by danielkerr** [comment]
fixed in latest commit.
