### ISSUE TITLE
[v3.1.0.0b - Fix] - Most files containing string IDs instead of 0s.

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6717]
List of the most files that needs to be changed from: 

`''`

to:

`0`

admin/controller/catalog/option.php
admin/controller/catalog/product_option.php
admin/controller/customer/customer.php
admin/controller/customer/customer_approval.php
admin/controller/design/seo_url.php
admin/controller/extension/payment/klarna_checkout.php
admin/controller/extension/payment/laybuy.php
admin/controller/mail/return.php
admin/controller/mail/reward.php
admin/controller/mail/transaction.php
admin/controller/sale/order.php
admin/controller/sale/recurring.php
admin/controller/sale/return.php
catalog/controller/extension/credit_card/sagepay_server.php
catalog/controller/extension/payment/g2apay.php
catalog/controller/extension/payment/sagepay_direct.php
catalog/controller/extension/payment/sagepay_server.php
catalog/controller/startup/session.php
catalog/model/extension/fraud/maxmind.php
system/framework.php
system/library/session.php
system/library/cart/customer.php
system/library/cart/user.php
system/storage/vendor/zoujingli/wechat-php-sdk/Wechat/WechatCard.php

**Comment by straightlight** [comment]
As for the last file on the list (vendor), I don't even know where the $data['cart_id'] comes from since the $data array is not being parametered but only queried inside the method.

**Comment by straightlight** [comment]
Other list of files with the status fields having ELSE of empty strings instead of zeros (0s):

admin/controller/catalog/product.php
admin/controller/catalog/review.php
admin/controller/customer/customer.php
admin/controller/marketing/affiliate.php
admin/controller/sale/order.php
admin/controller/sale/recurring.php
catalog/controller/account/recurring.php
admin/controller/extension/payment/amazon_login_pay.php
admin/controller/extension/payment/laybuy.php
catalog/controller/extension/credit_card/sagepay_server.php
catalog/controller/extension/payment/sagepay_server.php
catalog/controller/extension/payment/squareup.php

**Comment by MrPlow254** [comment]
why don't you just push the updates?

**Comment by danielkerr** [comment]
@MrPlow254 becuase a some of the things he posts are not actually bugs.

**Comment by danielkerr** [comment]
its not required. '' is equal to null
