### ISSUE TITLE
Default language problem at 3.0.2.0

### ISSUE THREAD

**Issue by kazanakius** [opencart/opencart#6718]
Hello,
I am having an opencart at Greek and English. Default language is set to Greek. When I access the website from a clean from any cookies browser, the English version comes first instead of the Greek.

Also, I noticed that I might be looking at the Greek SEO url and the content be in English!

I searched and found similar threads in the internet, and in github, with people having the same problem, but no solution anywhere. Any ideas?

**Comment by osworx** [comment]
It is simply how OpenCat tries to 'detect' users language.
In this order:

1. is ssession set
2. is cookie set
3. which language(s) are enabled and set in your browser

If not #1 and/or #2 then #3

Guess, you you will have English as 1. language defined in your browser.
Then English is used.

But, why post you that here and not in the forum??

**Comment by kazanakius** [comment]
Thank you very much for your answer,

So, what happens is normal..? Doesn't seem like a very correct way to function. When someone sets a default language, it means that he wants the website to always open at this default language, except someone changes language from the drop down language menu.

I am sorry if this is the wrong place to open a thread. It is the first Opencart related thread that I ever open, so I didn;t know the correct place to do so. I just found a similar thread here, and I thought this was the place.

**Comment by osworx** [comment]
> So, what happens is normal..? Doesn't seem like a very correct way to function. When someone sets a default language, it means that he wants the website to always open at this default language, except someone changes language from the drop down language menu.

Yes - that is the way it (and many other systems) work.
How else would you detect the users language?
So, if you want to have your language - Greek fpr example - to be the first, define it in your browser.
If Greek is installed - and confirgured correct - in OpenCart, it should display your store in Greek at first visit and if no session and/or cookie is set.

**Comment by kazanakius** [comment]
Maybe I am used to an other way of thinking about language detection. In Joomla for example, the website always open at the default language. The other languages have a /de or /it etc after the domain. if you visit http://www.mywebsite.gr/de for example, you will see the German version, no matter what settings you have made.
http://www.mywebsite.gr/it will always be Italian, http://www.mywebsite.gr/en will always be English and http://www.mywebsite.gr will always be Greek (if you have set it as default language)

**Comment by osworx** [comment]
In Joomla you define a 'default' language - has no language detection like OpenCart.
And as you write, you have added the langaueg flag to the URL.
This can be done with the new OpenCart 3.1.x

**Comment by kazanakius** [comment]
Thank you, so I might need to wait for Opencart 3.1.x until I activate a second language (english). Yesterday I sent my xml product feed to a price comparison site, and they only saw the english version, which is not correct for them. The url for english version and Greek version is the same. So I dont know if there is a solution there. 

I also just opened a more analytical thread to the forums as you suggested. It is waiting approval.

**Comment by abzo02** [comment]
pls guys help me to now is 2020 and i have same problem

**Comment by danielkerr** [comment]
clear your cookies.

**Comment by danielkerr** [comment]
i added this feature in the master branch. i need to fix the seo urls first.
