### ISSUE TITLE
Cannot install success on windows with MySQL 8

### ISSUE THREAD

**Issue by phinq1910** [opencart/opencart#6722]
Hi, I cannot install opencart on Windows with MySQL 8. There an error on step 3:
`Fatal error: Uncaught exception 'Exception' with message 'Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'<br />Error No: 1231<br />SET @@session.sql_mode = 'MYSQL40'' in D:\Web\htdocs\opencart\3020\system\library\db\mysqli.php:40 Stack trace: #0 D:\Web\htdocs\opencart\3020\system\library\db.php(45): DB\MySQLi->query('SET @@session.s...') #1 D:\Web\htdocs\opencart\3020\install\model\install\install.php(35): DB->query('SET @@session.s...') #2 [internal function]: ModelInstallInstall->database(Array) #3 D:\Web\htdocs\opencart\3020\system\engine\loader.php(248): call_user_func_array(Array, Array) #4 [internal function]: Loader->{closure}(Array, Array) #5 D:\Web\htdocs\opencart\3020\system\engine\proxy.php(47): call_user_func_array(Object(Closure), Array) #6 D:\Web\htdocs\opencart\3020\install\controller\install\step_3.php(11): Proxy->__call('database', Array) #7 D:\Web\htdocs\opencart\3020\install\controller\install\step_3.php(11): Proxy->database(Array) #8 [internal function]: ControllerInstallStep3->index( in D:\Web\htdocs\opencart\3020\system\library\db\mysqli.php on line 40`
Can you check it?
Thanks

**Comment by straightlight** [comment]
Also noticed in OC v3.1.0.0b release probably due to the use of Laravel with mySQL 8. See this solution: https://github.com/weprovide/valet-plus/issues/197
