### ISSUE TITLE
[v3.x - Fix] - catalog/controller/extension/payment/pp_braintree.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6723]
A forum user had an issue with PayPal Braintree regarding the amount being lower than a dollar which would cause an error 2000 in the API response: https://articles.braintreepayments.com/control-panel/transactions/declines#code-2000 . To avoid the wasted time for the customer to contact the bank in the future, in catalog/controller/extension/payment/pp_braintree.php file, find the second instance of:

`$order_info = $this->model_checkout_order->getOrder($this->session->data['order_id']);`

add below:

if ((float)$order_info['total'] < 1) {
				$this->model_extension_payment_pp_braintree->log('Post data: The order total amount is lower than 1.00');
				
				$success = false;
			}

This should rectify the issue on avoiding the error 2000.

**Comment by straightlight** [comment]
Other issues have been discovered and fixed with PayPal Braintree when using PHP v7.2: https://forum.opencart.com/viewtopic.php?f=201&t=205558

**Comment by danielkerr** [comment]
externsion removed out of the core and will be in the opencart marketplace soon.
