### ISSUE TITLE
[v3.1.0.0b - Fix] - admin/language/en-gb/extension/report/sale_order.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6726]
Two entry_status field being used: https://github.com/opencart/opencart/blob/master/upload/admin/language/en-gb/extension/report/sale_order.php

**Comment by vivek-webkul** [comment]
Performed changes for Order Status language index:
=> Changed **entry_status** to **entry_order_status** https://github.com/opencart/opencart/blob/master/upload/admin/view/template/extension/report/sale_order_info.twig#L36

=> Changed **$_['entry_status']** to **$_['entry_order_status']**
https://github.com/opencart/opencart/blob/master/upload/admin/language/en-gb/extension/report/sale_order.php#L28

![reports](https://user-images.githubusercontent.com/28401696/46062051-3728cf80-c186-11e8-9f98-a13ae60ea7d6.jpg)

**Comment by danielkerr** [comment]
its already renamed
