### ISSUE TITLE
cannot add 中文 as language

### ISSUE THREAD

**Issue by miklcct** [opencart/opencart#6736]
When I install a Chinese language pack and try to add it in the localisation settings, it shows Language Name must be between 3 and 32 characters! Therefore I can't add 中文 as a language in it.
![opencart language setting](https://user-images.githubusercontent.com/2827264/42683600-5781a7f8-86c0-11e8-8857-95ab1630489b.png)

**Comment by bau720123** [comment]
hi @miklcct 
you can modify the code by yourself to match your expect
or...maybe you can type "繁體中文" OR "簡體中文" to instead

**Comment by danielkerr** [comment]
easy fix.
