### ISSUE TITLE
font awesome icons added automatically

### ISSUE THREAD

**Issue by lruixiang** [opencart/opencart#6737]
```<div class="blog-post-body">
<header class="blog-header">
<h2 class="blog-title"><a href="{{ information.href }}">{{ information.title }}</a></h2>
<p class="blog-date">{{ information.date_added|date('d/m/Y') }}</p>
</header>
<div class="blog-post">
{{ information.description }}
<a href="{{ information.href }}">read more</a>
</div>
</div>
```

Under Twig syntax, when I'm using {{ information.date_added }}, there's a font awesome class automatically added as shown below. 
`<p class="blog-date"><i class="fa fa-calendar-o" aria-hidden="true"></i> 13/07/2018</p>`

Any idea where the `<i class></i>` is auto generating from?

**Comment by MrPlow254** [comment]
Go to the forum. This is only for bug reporting
