### ISSUE TITLE
multistore - google analytics

### ISSUE THREAD

**Issue by marjoleinder** [opencart/opencart#6738]
I asked this in the forum and get a answer:
Web Site: uniekbedrijfscadeau.nl
Enquiry:
I have a multistore. Want the use the google site map url that i found in the feed. But there is only for uniekbedrijfscadeau not for the other sites like ecocadeautjes.nl how to do?

Dear Marjolein,
It is a bug. Please report it to https://github.com/opencart/opencart
Michael Tsang
OpenCart Support

Hoop I did this the correct way. Please help.
greetings,
Marjolein de Raadt

**Comment by danielkerr** [comment]
spam! idiot!
