### ISSUE TITLE
[All OC versions] - PHP v7.x

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6750]
Since the alpha distributions of OC requests to have PHP 7.x installed nowadays, it would seem that even for prior versions of OC, some servers may not allow to complete the installation without it: https://forum.opencart.com/viewtopic.php?f=199&t=205806 . It would then be suggested to enforce the use of PHP 7x on previous OC versions as well as this may be a server requirement to have in the mean time.

**Comment by danielkerr** [comment]
how about the site owner contacts their host and asks for php7 to be installed!
