### ISSUE TITLE
Bootstrap.css.map deprecated text-hide()

### ISSUE THREAD

**Issue by MrPlow254** [opencart/opencart#6754]
The default theme scss is calling text-hide() which is deprecated. This is spamming the error log.

**Comment by danielkerr** [comment]
on which version? the master branch?

**Comment by danielkerr** [comment]
closing as this is default in bootstrap

**Comment by MrPlow254** [comment]
@danielkerr i'm on the current build-9023. Here are the file locations. If you aren't using text-hide mixin it shouldn't be saving to the apache error log.

![image](https://user-images.githubusercontent.com/1266825/43137397-c9b929c0-8f19-11e8-96b9-8c63c010336e.png)

**Comment by danielkerr** [comment]
build-9023 what does that mean?

which version master banch?

**Comment by danielkerr** [comment]
ok found it

**Comment by danielkerr** [comment]
its in the original bootstrap files. its a bootstrap bug.

**Comment by danielkerr** [comment]
ok fixed from the latest bootstrap.

**Comment by MrPlow254** [comment]
@danielkerr It's good you found a fix. Thank you! And I meant the commit number on the current master branch as the build #. What should I call it?
