### ISSUE TITLE
Opencart scss compiler

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#6756]
Opencart scss compiler is not good for bootstrap 4, because the css browser prefixes missing. There will be a lot "theme doesn't work in this browser".

Bootstrap 4 use autoprefixer for this.

https://github.com/opencart/opencart/blob/05f8f6e830cf7028b626db279b8337f2a08f84c8/upload/catalog/view/theme/default/stylesheet/bootstrap.css#L441-L445

https://github.com/twbs/bootstrap/blob/72447ad4972105e920f1767f369b98a76dcfa107/dist/css/bootstrap.css#L590-L597

**Comment by danielkerr** [comment]
i updated leafo sass compiler. works fine for me.

**Comment by danijelGombac** [comment]
@danielkerr 

Is this file compiled with the updated leafo sass compiler?

[https://github.com/opencart/opencart/blob/master/upload/admin/view/stylesheet/stylesheet.css](https://github.com/opencart/opencart/blob/master/upload/admin/view/stylesheet/stylesheet.css)

**Comment by danielkerr** [comment]
Yes

**Comment by danielkerr** [comment]
does this not fix the issue?

`.form-group.row + .form-group.row {
    padding-top: 1rem;
    border-top: 1px solid #ededed;
    margin-left: -20px;
    margin-right: -20px;
}
`

**Comment by danijelGombac** [comment]
@danielkerr 

The problem is that Bootstrap 4 use [Autoprefixer](https://github.com/postcss/autoprefixer), [Build tools](http://getbootstrap.com/docs/4.1/getting-started/build-tools/) for browser prefix and i think leafo sass compiler doesn't have this option. You need to write browser prefixes manuali.

**Comment by danielkerr** [comment]
using the latest leafo sass compiler. i can not find an issue with the latest bootstrap.
