### ISSUE TITLE
The emergence of a problem after converting to Https hope help in solving

### ISSUE THREAD

**Issue by MHMOUDSBEIHm** [opencart/opencart#6757]
2018-07-24 21:11:36 - PHP Notice:  Undefined variable: username in /home/msbeuazl/astore.icu/admin/view/template/common/column_left.tpl on line 5

**Comment by MHMOUDSBEIHm** [comment]
![default](https://user-images.githubusercontent.com/41651632/43167537-b630fcb4-8fa2-11e8-92f4-7ade431548ce.png)

**Comment by straightlight** [comment]
No OC version posted. However, using an old version.

**Comment by danielkerr** [comment]
make sure all urls are ssl.
