### ISSUE TITLE
Anonymous classes require PHP 7+

### ISSUE THREAD

**Issue by skyosev** [opencart/opencart#6759]
The anonymous classes are introduced in PHP 7.0. The Opencart 3.1+ requirements are PHP 5.6+
https://github.com/opencart/opencart/blob/d572831caca12926b32652a4f354cd196a5b719d/upload/system/library/template/twig.php#L42
https://github.com/opencart/opencart/blob/d572831caca12926b32652a4f354cd196a5b719d/upload/system/startup.php#L6

**Comment by danielkerr** [comment]
yes will require php7 again.
