### ISSUE TITLE
3.1-alpha Affiliate validation broken

### ISSUE THREAD

**Issue by MrPlow254** [opencart/opencart#6760]
When creating a new marketing affiliate or editing an existing one it throws a warning. Tracking code is required but does not throw an error and is not marked in the form as a required field.

**Comment by b11215** [comment]
you need install php7.0
php5.6 can not support it

**Comment by MrPlow254** [comment]
@b11215 that has nothing to do with html output... none of the issues I described are related to php not having features. needless to say I’m on 7.2.x

**Comment by danielkerr** [comment]
fixed in a previous commit.
