### ISSUE TITLE
Datetimepicker and BS4

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#6765]
Datetimepicker is not compatible with BS4. Open the product edit page and look the discount and special table.

Here is the new version, but i think it has some bugs. You can try:

https://github.com/tempusdominus/bootstrap-4

**Comment by danijelGombac** [comment]
Here is another nice datetimepicker:

https://github.com/t1m0n/air-datepicker

**Comment by monolithforge** [comment]
Yep- been looking at this.  Here's a DEMO (w/fix): h
https://playground.opencartforge.com/u/m/monolithforge/demo/202/3.0.2.0/index.php

Here's the code... somewhere ;-)
https://gitlab.com/MonolithForge/opencart-bootstrap4-theme-basic.ocmod

Here's the library we should migrate too:
https://tempusdominus.github.io/bootstrap-4/

Cheers,
Troy

P.S. Just Sayin`

**Comment by monolithforge** [comment]
[3.1.0.0_a1]

**Comment by panreach** [comment]
#6833 fixes this issue

**Comment by danielkerr** [comment]
updated

https://github.com/tempusdominus/bootstrap-4

to work with bs4.
