### ISSUE TITLE
Deleting customer doesn't delete from customer_history table

### ISSUE THREAD

**Issue by ADDCreative** [opencart/opencart#6770]
Looking at the deleteCustomer method (https://github.com/opencart/opencart/blob/3.1.0.0_a1/upload/admin/model/customer/customer.php#L49-L59).  The following probably needs adding to also remove the customers history.

```$this->db->query("DELETE FROM " . DB_PREFIX . "customer_history WHERE customer_id = '" . (int)$customer_id . "'");```

**Comment by ADDCreative** [comment]
There maybe other tables that also require customer data deleting from, such as customer_activity, customer_login, customer_search and customer_wishlist.

**Comment by elcopdoo** [comment]
Poštovani,

koristim godišnji odmor do 14.08.2018.
Vaš mail će biti preusmjeren kolegama u uredu.
Vraćam se 16.08.2018.

I am currently out of the office.
I'll be back on August 16th.
Your email will be forwarded.


Lijep pozdrav / Best regards

Denis Dobranić
Elcop d.o.o.

**Comment by danielkerr** [comment]
ok added wishlist as well but all the opther tables seem to be there.
