### ISSUE TITLE
Checkout confirm button doesn't work if you go back/forward

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#6771]
Using latest code checkout page works fine until you click back.

E.g. go through checkout steps select payment method and then click back to change payment method. The final Confirm Order button stops working.

Testing product without shipping and payment method bank transfer.

**Comment by straightlight** [comment]
OC version not mentioned.

**Comment by howdu** [comment]
Latest code from github.

**Comment by straightlight** [comment]
These steps were not mentioned on your first post. None can be expected to reproduce an issue regarding unposted steps in order to resolved the issue afterwards. What does the Developers Kit states when doing those steps on your end?

**Comment by jamesallsup** [comment]
Please provide the console output from Chrome or Firefox - if a button is not submitting it should show an error/message.

Just press F12 (on a PC) when you start the checkout flow and it will provide more info on the issue.

**Comment by howdu** [comment]
Checked all that but nothing displayed in the console. The final confirm button becomes unresponsive when you go back and forth.

It's a strange issue that so I've recorded a screencast to help see the issue: https://filebin.net/pflsmq6cic9yv098/Sep_3_2018_8_19_AM.webm?t=fvd3u8x4  

Note: this issue is only when testing with latest opencart 3.1 and not in the stable 3.0 release.

**Comment by straightlight** [comment]
Check the server access logs from FTP (access_logs / logs folder) and see the most recent archived file when the button becomes unresponsive.

**Comment by danielkerr** [comment]
can not replicate and the code has been changed many times sine this issue.
