### ISSUE TITLE
[3100_a1] Clean OC-Install – Payment COD and Flat Shipping isnt running at the beginning

### ISSUE THREAD

**Issue by Urs-Bruelhart** [opencart/opencart#6776]
<img width="709" alt="bildschirmfoto 2018-07-28 um 17 08 42" src="https://user-images.githubusercontent.com/837404/43357890-f02dbe0a-9288-11e8-8483-6d59e0eb0f82.png">

I tried with all Zones, customer of coz in UK ... i dont got it running.

**Comment by Urs-Bruelhart** [comment]
I make further testing on that ...

**Comment by Urs-Bruelhart** [comment]
I tried again clean, fresh, refreshed Mods and cleared Cache, Save both Moduls again, refreshing and clearing etc. ... Still no Payment and Shipping.

Addes Bank Transfer with success.
Shipping still not avail.
Added Free Shipping with success.
And strangly all is fine with COD and Flat Shipping.

Can somebody confirm that behavior, please?

**Comment by danielkerr** [comment]
its working now
