### ISSUE TITLE
[3100_a1] route=product/search Language=en-gb is missing

### ISSUE THREAD

**Issue by Urs-Bruelhart** [opencart/opencart#6777]
<img width="711" alt="bildschirmfoto 2018-07-28 um 19 00 32" src="https://user-images.githubusercontent.com/837404/43358852-95126c22-9298-11e8-989d-e90df17d919e.png">

**Comment by straightlight** [comment]
A bit odd on this one, indeed. In catalog/controller/product/search.php file,

find:

`$data['search'] = $search;`

add below:

`$data['language'] = $this->config->get('config_language');`

Then, in your catalog/view/theme/default/template/product/search.twig file,

find:

`url = 'index.php?route=product/search';`

replace with:

`url = 'index.php?route=product/search/language={{ language }}';`

This should resolved the issue.

**Comment by danielkerr** [comment]
already been fixed
