### ISSUE TITLE
[3100_a1] Admin route=customer/customer Unlock Account -> Logging out Admin

### ISSUE THREAD

**Issue by Urs-Bruelhart** [opencart/opencart#6780]
<img width="1290" alt="bildschirmfoto 2018-07-28 um 19 25 41" src="https://user-images.githubusercontent.com/837404/43359047-451fafaa-929c-11e8-8a53-f722cbc33907.png">

URL is: admin/#

**Comment by danielkerr** [comment]
its fixed
