### ISSUE TITLE
[3100_a1] Admin route=sale/order/info Cant add Order Status -> No permission to API

### ISSUE THREAD

**Issue by Urs-Bruelhart** [opencart/opencart#6783]
<img width="646" alt="bildschirmfoto 2018-07-29 um 13 50 58" src="https://user-images.githubusercontent.com/837404/43366025-7ae2d7d0-9336-11e8-8fdd-f7c6e528c760.png">

After that i cant add a new one to the API.

**Comment by straightlight** [comment]
Did you first created your APIs from the OC admin? More information is needed.

**Comment by Urs-Bruelhart** [comment]
<img width="1233" alt="bildschirmfoto 2018-07-29 um 18 05 28" src="https://user-images.githubusercontent.com/837404/43368205-05d81dd2-935a-11e8-99b7-7fb27c5f2020.png">

I mean this one. And it is running on a localhost.

Store API i cant copy into this field, its a longer string than allowed.

**Comment by Urs-Bruelhart** [comment]
Ok, there are 2 APIs in OC – please correct me, when i am wrong:

Marketplace API
User API

I have the issue with the User API.

On older OC version, i added my IP and then all was fine.
This function is now not offered.

**Comment by Urs-Bruelhart** [comment]
@straightlight 

Hello again,

do you have meanwhile an idea, whats going on there ?

**Comment by straightlight** [comment]
`Store API i cant copy into this field, its a longer string than allowed.`

What you are reporting is a set of string that is longer than what OC originally provides which means you may not be looking to add a local API but rather a remote API credential info to generate an API key. At this point, it would not be an OC bug.

**Comment by Urs-Bruelhart** [comment]
@howdu 

Thank you for your input; i try it out and give here feedback.

**Comment by pemaier** [comment]
I have the same problem.
"Warning: You do not have permission to access the API! " (Administrator - all rights active)
New installation no changes of the API key. 
As user I'm awaiting that this is working out of the box.

**Comment by pemaier** [comment]
@howdu with this changes it's working. Thank you.
Now what is the next step to bring it to work with the session engine?
And the question occurs about a real working solution in the release? 
or any other suggestions?

**Comment by pemaier** [comment]
After an update from today **the workaround is not working any more** 
to deactivate 
// Session
//$_['session_autostart']  = true;
//$_['session_engine']     = 'db';
//$_['session_name']       = 'OCSESSID';

Now I get the message 
Notice: Error: Could not load cache adaptor session! in /home/.../system/library/session.php on line 36

It's necessary to **solve the problem with the API access**.

**Comment by danielkerr** [comment]
yep the session engines are not the same for the admin and front. fixing now.
