### ISSUE TITLE
[3100_a1] Admin route=marketing/contact -> E-Mail Message required

### ISSUE THREAD

**Issue by Urs-Bruelhart** [opencart/opencart#6784]
<img width="713" alt="bildschirmfoto 2018-07-29 um 14 43 25" src="https://user-images.githubusercontent.com/837404/43366413-03d7b84c-933e-11e8-84fc-e18aaf1e898e.png">

Message is not empty, anyway i got the Error:

E-Mail Message required

**Comment by straightlight** [comment]
This issue was already addressed on GitHub before and replied that it may be due to the CKEditor or from the max_post_vars limits defined in your php.ini file since this issue has not been reported frequently by others but rather on very rare occasions.
