### ISSUE TITLE
OC 2.3.0.2 Payment: CardConnect Issue

### ISSUE THREAD

**Issue by juliustip** [opencart/opencart#6786]
We tried installing cardconnect as a payment gateway and got all the necessary information from them but when we try to initiate a sale and enter the credit card information by hitting the submit order it does not do anything. It stays at the checkout page. 

Any solution to this?

**Comment by MrPlow254** [comment]
Update to the newest release?

**Comment by straightlight** [comment]
Posting about an old OC issue.

**Comment by straightlight** [comment]
GitHub Opencart is for the most OC version release (currently on Alpha). If you wish to report an incident about an older OC version, please post on the forum about it.

**Comment by schiggi** [comment]
I believe, it also would make sense to contact CardConnect for assistance. They do have a vital interest for you to get it running. Besides that, it is difficult to maintain different versions at the same time. So I assume, that Github is used for bug tracking for the latest version for developers. You can find help for end users and older versions in the forum.

**Comment by jamesallsup** [comment]
Please use the forum for older versions of OC
