### ISSUE TITLE
[v3.1.0.0a - Fix] - api/login routes

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6787]
- admin/view/template/extension/payment/laybuy_order.twig
- admin/view/template/extension/payment/laybuy_transaction.twig
- catalog/controller/api/login.php

Since Daniel did mentioned on Github on a previous post that the api/login will no longer be used, these first two files still calls the third listed file on the alpha release.

**Comment by danielkerr** [comment]
api login is still going to be used just in a diffferent way. apis requirte the cookie to be passed on every call like a normal browser would work.

**Comment by danielkerr** [comment]
I never said it was not going to be uised. @danijelGombac  said it is not used anymore. thats not true. 3rd party apps that need to use the api can.

**Comment by straightlight** [comment]
While this topic has been closed, redundant issue posted by another user lately: https://github.com/opencart/opencart/issues/7327

**Comment by danielkerr** [comment]
removed this sort of stuff.
