### ISSUE TITLE
3.0.2 order statistics does not update

### ISSUE THREAD

**Issue by eimaz5** [opencart/opencart#6788]
Hello I have found big opencart 3.0.2 bug..

Order statistics not updating in admin.

This is the screenshot of opencart demo page:

![image](https://user-images.githubusercontent.com/17913733/43575970-ceef459e-9650-11e8-8cff-045dfde02dcf.png)

There is 2.7k orders, but the statistics is not updating, everything is at 0%...

Any fixes?

this is that i found so far: https://forum.opencart.com/viewtopic.php?t=200655

**Comment by straightlight** [comment]
Recent / alternative solution: https://forum.opencart.com/viewtopic.php?f=199&t=200655&p=726699#p726699

**Comment by samaraki** [comment]
Neither solutions work for me.
The file change makes no difference and the SQL code on the second option doesn't insert.

**Comment by Kaik** [comment]
There are few more bugs in this or maybe let's say inconsistencies.
1. Dashboard Total Orders (blue box) is calculated here
https://github.com/opencart/opencart/blob/master/upload/admin/controller/extension/dashboard/order.php#L106 - no status filter so this figure is quite misleading it includes deleted, and invalid orders too - what is "good" about it is that it is not a stored figure and it is recalculated each time so at least it is always accurate.

2. Mentioned in this issue order stats are calculated with order completed and progress statuses in mind. (you can select what is considered a completed order status or in progress in OC settings) all those stats including additional one with code order_sale are stored in the statistics table and there is no recalculation/refresh procedure, only increment decrement action which means changing status settings in OC admin does not recalculate those figures.

What I would suggest is to base everything on that statistics table (dashboard blue box too) use order_sale for that. Apart from increment-decrement actions add recalculate action that can be used in case, someone, changed those statuses in oc settings and used on demand if needed.

This is how I'm doing it https://github.com/Kaik/CodeIkebanaStatistics.ocmod/blob/master/upload/admin/controller/extension/module/codeikebana_statistics.php#L98 - btw this is just an example module it is not supported/and probably will not work if you don't know what you are doing. I just needed it to fix this issue in my shops.
