### ISSUE TITLE
[v3.1.0.0a - Fix] - catalog/controller/account/tracking.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6789]
The tracking key is still linked with the product/product route but catalog/controller/product/product.php file does not contain any tracking key.

**Comment by jamesallsup** [comment]
@straightlight Can you expand on this a bit? Not sure what you mean.

Thanks J

**Comment by straightlight** [comment]
catalog/controller/account/tracking.php file:

`'link' => str_replace('&amp;', '&', $this->url->link('product/product', 'language=' . $this->config->get('config_language') . '&product_id=' . $result['product_id'] . '&tracking=' . $tracking))`

where 'tracking' is defined as the key with the tracking value. In catalog/controller/product/product.php file, there are no 'tracking' key defined from the GET superglobal . 

Defined as decoration purposes.

**Comment by danielkerr** [comment]
tracking was supposed be for parcel tracking. i haven't created the first parcel tracking extensions.

**Comment by danielkerr** [comment]
can not find any issue
