### ISSUE TITLE
MULTI VENDOR SUPPORT

### ISSUE THREAD

**Issue by mdk007** [opencart/opencart#6790]
Dear Sir

             Thanks for opencart which has unlimited features, Please also add Multi Seller/Vendor feature for every item sell. Thank you in advance.

**Comment by hanijazzar** [comment]
There are 2 extensions available on Opencart marketplace that provide multi-vendor support. You can buy any of them for 100$. There is also this https://github.com/CodLance/Multivendor

**Comment by cargovint** [comment]
Con qualche piccola modifica puoi avere opencart multivendor senza moduli aggiuntivi a pagamento.
Io ne ho sviluppata una versione basata su 3.0.2.0 (italiano). Puoi vederla quì: www.opencash.it/seller/

**Comment by danielkerr** [comment]
at some point i might add this but at the moment there are extensions for this.

**Comment by cargovint** [comment]
Opencash Sellers - vendor manager - all function separate for single seller, payment, shipping, return and order. Admin panel with specific permission, Account seller pack definition. The separate extension have much problem: normally dont work and not sure for ecommerce on line. The project can work only with a native multivendor platform!
