### ISSUE TITLE
Open Cart version 3 issue in admin panel.

### ISSUE THREAD

**Issue by taleeb35** [opencart/opencart#6792]
Hello everyone!

I found an issue in admin panel of V3. When I open an order to see its detail in payment and shipping detail I can not see the address. There is only name of the client. Please fine the attached images for your reference and if there is any update please update.

Thanks

![v2](https://user-images.githubusercontent.com/5644182/43684135-86b77618-98ab-11e8-89fc-cf9171ab7d66.jpg)
![v3](https://user-images.githubusercontent.com/5644182/43684136-86ee64ca-98ab-11e8-8cf8-69c9e4a170f9.jpg)

**Comment by soundzgood** [comment]
Not an issue on oc3.0.2.0 I've found - would suggest using [Opencart Forum](http://forum.opencart.com/) or [Opencart support](https://dedicated.opencart.com/) and provide background to reproduce issue.

**Comment by straightlight** [comment]
OC v3 what? OC version not fully provided.

**Comment by andrei-bogdan** [comment]
Are those different clients and orders in the same store (one shows up and one doesn't)? Make sure the client has an address set and the order in question does have the address properly set in database.
