### ISSUE TITLE
[3.1.0.0_a1 and 3.0.2.1_rc] if $product_option_value_info

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#6794]
admin/controller/sale/order.php Oc 3.1.0.0alpha line 1795:

`if ($product_option_value_info) {`

this change to:

`if ($product_option_value_info && $product_option_value_info['weight'] > 0) {`

or to:

`if ($product_option_value_info['weight'] > 0) {`

**Comment by straightlight** [comment]
The first change suggestion would be more ideal since we are first verifying the $product_option_value_info's content. :)

**Comment by pekka2** [comment]
Or to:
`if (!empty($product_option_value_info['weight'])) {`

**Comment by pekka2** [comment]
Same issue in version 3.0.2.1_rc line 1798
