### ISSUE TITLE
[v3.1.0.0_a1] url link with product_id parameter

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#6795]
If product has seo url there's now no way to pass 'product_id' as a param. E.g:
$this->url->link('extension/module/print, 'product_id=' . 123, true);

Returns: https://example.com/iphone?route=extension/module/print&product_id=123
Instead of: https://example.com/index.php?route=extension/module/print&product_id=123

Also performance is not great for a standard product link - it runs 2 extra database queries:
$this->url->link('product/product', 'product_id=' . 123, true);

Regex: (route=[a-zA-Z0-9\/]+)(?:[&]|$)
SELECT * FROM oc_seo_url WHERE `query` = 'route=product/product' AND store_id = '0' AND language_id = '1'

Regex: (product_id=)
SELECT * FROM oc_seo_url WHERE `query` = 'product_id=' AND store_id = '0' AND language_id = '1'

Regex: (product_id=\d+)(?:[&]|$)
SELECT * FROM oc_seo_url WHERE `query` = 'product_id=123' AND store_id = '0' AND language_id = '1'

**Comment by straightlight** [comment]
Installed extension: extension/module/print despite the version you are using. Since this topic is about compatibility issue, on GitHub, it has to be proven from the latest and core release package to demonstrate that the SEO links would be improperly sanitized either from the browser or on the database.

**Comment by danielkerr** [comment]
the vars are re added in the request class.

so 

$this->request->get['product_id'] = $product_id;

**Comment by zemguru** [comment]
Good! Would be great to have this in Wiki for new version, don't forget.

**Comment by danielkerr** [comment]
already has it.
