### ISSUE TITLE
Success notification 

### ISSUE THREAD

**Issue by Hackej** [opencart/opencart#6798]
Hi!

Last version GitHub installed just now - 180808 - 12.00 on localhost (XAMPP)!
No modifications or altered DB - just demo products.

Clicking ADD TO CART" in Featured on Home page:
- IE11 - nothing happens - not added to cart or linked to product page - no reaction 
- Chrome - notification for added product (iPhone) is off base to the left see pic below.
 Link to product page is OK for other products.

![image](https://user-images.githubusercontent.com/29421668/43831090-49af0b0a-9b03-11e8-808b-458ee6e76483.png)

BR
/Hackej

**Comment by andrei-bogdan** [comment]
Make sure you force-refresh (CTRL+F5) your browser's cache. Just checked the demo in Chrome and it behaves OK.

**Comment by MrPlow254** [comment]
@andrei-bogdan he is saying it doesn't work in IE. Multiple reports are saying javascript is broken on IE.
