### ISSUE TITLE
[3.1.0.0_a1] OC Filter logic - Product filter

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6799]
Situation:
I have a product (Music download file) with 2 filter relations.
Filter **a**) Product type - 1. CD / 2. DVD / 3. Download
Filter **b**) Media type - 1. Music / 2. Video
Product is - Filter a3 **AND** b1 (Music download)

Then the filter calculate the result
**Product show** - Filter a3 **OR** b1 

Problem:
Customer wants a Music download filter and like to filter music titles for download.
Customer gets (Filter a) downloads and (Filter b) music and videos but **he wants to see only the music products for download**.

**Comment by MrPlow254** [comment]
You will have to re-write the filter SQL. I did this at my previous company. It uses or statements vs and statements. It would do an and statement between groups and an or between each item within the group.

Here is an example. https://catalog.sas-automation.com/index.php?route=product/category&path=62_71&filter=279,255

**Comment by straightlight** [comment]
Extension request. Nothing to do with GitHub Opencart issues. Please create a new service request on the Opencart forum for those inquiries,

**Comment by pemaier** [comment]
Thank you for your comments.
**BUT** in the current status it makes no sence to have more than 1 filter per product. So for me it seems **it is an issue** and not a feature.

**Comment by danielkerr** [comment]
you can have multiple filters per product. i think your not using it correct. maybe u require sub filters.
