### ISSUE TITLE
[3.1.0.0_a1] Docs && Apache appends for the sake of ocmod.zip files and such.... geesh...

### ISSUE THREAD

**Issue by monolithforge** [opencart/opencart#6801]
Please append the following to: https://github.com/opencart/opencart/blob/master/install.txt

Section: (as of this issue No 2) (Make sure your web user has the permission to read, write and execute all directories under the web root.)

I would, perhaps, recommend here, a few awesome providers that know how to host apache/nginx with the apache/web appropriate permissions for a gosh darn VHOST.  Half of the questions for extensions/plugins are about this.... please, please, please gEt into MOAR details here!!!  MARKET IT FOR A FEW COMMERCIALS ;-)

Thank you,
Troy

**Comment by monolithforge** [comment]
https://github.com/opencart/opencart/blob/master/install.txt#L21

**Comment by andrei-bogdan** [comment]
You can find here some recommendations: https://www.opencart.com/index.php?route=cms/download
Provider should be the client's choice and the platform should not influence it in any way, since the setup is standard and works on any provider.

**Comment by jamesallsup** [comment]
No, sorry, not putting hosting companies into the install.txt
