### ISSUE TITLE
[3.1.0.0_a1] Sales Order - Print shipping list not working

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6803]
Situation:
Order is present.
a) Order overview - activate an order - click Print Schipping List -> New tab opening but empty
b) Order overview - open order - click Print Schipping List -> New tab opening but empty

**Comment by andrei-bogdan** [comment]
Button works fine on demo. Does your new blank window have an URL? Can you share it? Also if you have any modules installed, disable them and try again.

**Comment by pemaier** [comment]
I have tested once again ... you are right it's working. (Sorry my mistake)
Please close the report.
