### ISSUE TITLE
PayMate Payment Gateway - Test URL Obsolete

### ISSUE THREAD

**Issue by mpserellis** [opencart/opencart#6804]
Hello,

This is for information rather than an issue. The PayMate payment gateway that comes with OpenCart has a test URL in catalog/controller/extension/payment/paymate.php.

When we put PayMate into test mode that URL redirected us to Page Not Found. I contacted PayMate who informed me they do not have a test URL. Please see below response from PayMate:

>   We don't have test URL for paymate express.please use below URL and test
> card details it should.
> https://paymate.com/PayMate/ExpressPayment
> Test card details.
> 
> Card number: 4111 1111 1111 1111
> Expire date: 10/19
> CVV: any 3 digits
> 
> Transaction should declined.

May I suggest removing the Test mode option for this gateway to save others similar confusion?

Thank you
Mark

**Comment by By-oussef** [comment]
News ?

**Comment by danielkerr** [comment]
removed from core. will have extension page on opencart.com soon.
