### ISSUE TITLE
How To Trigger Event When Order Added,Edit and History Modified

### ISSUE THREAD

**Issue by umertoday** [opencart/opencart#6805]
I build sms module of Opencart 3.0.2.0. I want to send SMS to customer when new order added, edit or history update
the event code is as
//Event Installing
 public function install() {
            $this->load->model('setting/event');
            //Add Product Event
            $this->model_setting_event->addEvent('umertoday','catalog/model/checkout/order/addOrder/after','extension/module/umertoday/eventAddOrder');

        }
//Event Functionality handle here but it does not work
public function eventAddOrder($route = false,$order_info = false,$order_id = false) {
            $log = new Log('eventAddOrder.log');
            $log->write('Route: ' . $route);
            $log->write('Order Info: ');
            $log->write($order_info);
            $log->write('Order ID: ' . $order_id);;

        }

**Comment by v5manoel** [comment]
In File:
catalog/controller/extension/module/**umertoday.php**

```
class ControllerExtensionModuleUmerToday extends Controller {
    public function eventAddOrder(&$route, &$args, &$output) {
        $this->log->write('Route: ' . $route);
        $this->log->write('Order Info: ');
        $this->log->write($args);
        $this->log->write('Order ID: ' . $output);
    }
}
```

**Comment by v5manoel** [comment]
The only way to work is you create an event for addOrder and another for editOrder, and two functions to receive each of the events.

**Comment by jamesallsup** [comment]
Sorry to hear you have an issue, the GiHub bug tracker is not the place to post issues relating to setup, 3rd party modules or general types of questions.

Please read the [project information page](https://github.com/opencart/opencart/blob/master/README.md#reporting-a-bug-and-security-issues) which should guide you in the right direction for support.

Kind regards, J
