### ISSUE TITLE
[3.1.0.0_a1] Theme editor changes ignored at times

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#6806]
Having turned off caching, and then changed the common/header.twig by the built-in theme editor, the change works fine. However, when I change the same file 'catalog/view/theme/default/template/common/header.twig' via OCmod, then on;ly the latter change shows up, the first one done via the theme editor gets ignored.

The simple solution would be for the OCmod: When it loads the template file to be modified, it should also check whether there are other changes already done it from the theme editor, e.g. do a simple DB query first:

$this->model_design_theme->getTheme( $route, $theme_directory )

If it detects prior changes, use the code from that DB query for further modification by OCmod, otherwise use the original template file for the modification by OCmod.

**Comment by mhcwebdesign** [comment]
Actually, after having done some more tests, the template changes from the theme editor never appear to show up at all. 

This whole OpenCart theme fiasco gets increasingly messy with each new release.

**Comment by v5manoel** [comment]
Themes should be modified through the event system, not OCMOD anymore.

**Comment by MrPlow254** [comment]
OCMOD works. You are doing something wrong. Here is an example that works.

```
	<file path="catalog/view/theme/*/template/common/header.twig">
		<operation>
			<search index="0"><![CDATA[<meta charset="UTF-8"/>]]></search>
			<add position="after" index="0" offset="0"><![CDATA[
	{% if customer_id_cookie %}
	<script>
	if (!sessionStorage.reloadHeader) {
		sessionStorage.reloadHeader = 1;
		location.reload();
	}
	</script>
	{% endif %}
			]]></add>
		</operation>
		<operation>
			<search index="0"><![CDATA[<a href="{{ transaction }}" class="dropdown-item">{{ text_transaction }}</a>]]></search>
			<add position="after" index="0" offset="0"><![CDATA[                <a href="{{ form }}" class="dropdown-item">{{ text_form }}</a>]]></add>
		</operation>
	</file>

**Comment by v5manoel** [comment]
OCMOD does not work if file is edited by Theme Editor.

I already talked to Daniel about this:
https://github.com/opencart/opencart/issues/6758

**Comment by mhcwebdesign** [comment]
@v5manoel: I agree, u\sing events, or even object oriented class extensions is the way to go.

I was talking about the OpenCart theme editor which you can find in the admin backend at 'Design > Theme Editor'. That one should not clash with other ways of modifications (OCmod, VQmod, events, etc). Daniel's current approach of using dynamic lambda callback functions looks a bit convoluted to me. I think it would have been better to be able to use proper event handlers for this, which is relatively easy to implement in OpenCart. For example, the catalog/view/*/before event handlers should have the following method signature for an event handler:

```
	public function eventHandler( &$route, &$data, &$template_buffer=null) {
		// ......
	}

``` 
where $template_buffer is the template code.

Wherever the original template  file is read into this template_buffer, be it from an event handler,or OCmod, or the in the main rendering process via Twig, it needs to check for prior modifications done via the OpenCart template editor.

**Comment by v5manoel** [comment]
@mhcwebdesign In version 3.1.0.0a1 it is exactly as it is working.

What kills is the lack of documentation on the subject, because I spent a few hours to understand how everything worked and how I would do to get the theme buffer and edit using DOM and XPath.

I think there's still a lot of work to do to make it more practical.

**Comment by v5manoel** [comment]
I think the trend is to stop using vqmod and ocmod in version 3.x

**Comment by MrPlow254** [comment]
@v5manoel he was referring to twig not caching correctly preventing OCMOD from even editing twig files. Switching to twig 1.X to 2.X broke a lot of functions.

#6752

Fixed build:
https://github.com/opencart/opencart/commit/bd015b833f5e488bb462dbce8ef7fea1fa4de6b5

**Comment by v5manoel** [comment]
I wanted to say that it would be ideal to stop modifying files through OCMOD. :)

**Comment by mhcwebdesign** [comment]
OK, I ran some more tests. The theme editor only seems to work when theme caching is enabled. And it causes OCmod changes done to a same template file to be ignored.

Doesn't Twig support auto-caching? And why can't Twig detect that when there is a newer modifications done via theme editor or OCmod to automatically refresh its caching? 

Basically, changes to a template file should be check in the following sequence:
- theme editor changes
- OCmod changes
- VQmod (if installed)
- events catalog/view/*/before

**Comment by mhcwebdesign** [comment]
Just a thought: Can't we use the Twig_Extension_StringLoader for cases where modifications were done via 1) Theme Editor, 2) OCmod, or 3) event Handlers. In each of these cases there ought to be a string buffer containing the modified template which is then passed on to the Twig rendering engine.

**Comment by danielkerr** [comment]
closing this as if there is a modified file the theme editor will use that first.
