### ISSUE TITLE
[3.1.0.0_a1] OC Checkout - Address view is only visible ~60%

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6809]
Situation
When you order something and go to the checkout the 1st point opens - Choose address
At the initial view the default address is viewable only partly - the lower part is not viewable.

**Comment by andrei-bogdan** [comment]
Is this issue on mobile view or desktop view?

**Comment by pemaier** [comment]
I have tested only on the desktop ... here is a [sample](https://demo.opencart.center/download/oc.3.1.0.0a1-address.png)

**Comment by MrPlow254** [comment]
Confirmed on the current build.

**Comment by vivek-webkul** [comment]
[Select dropdown css related issue fixed.]
#6891
![checkout](https://user-images.githubusercontent.com/28401696/45914743-ed2ea980-be66-11e8-8e6a-df40e55d49f7.jpg)
![register account](https://user-images.githubusercontent.com/28401696/45914744-ed2ea980-be66-11e8-8f7c-e1d091d230fe.jpg)

**Comment by pemaier** [comment]
Ok Thank you for your support.
