### ISSUE TITLE
Error after clicking Upgrade (3.1.0.0_a1)

### ISSUE THREAD

**Issue by mehtaman** [opencart/opencart#6815]
Hi,

How can I fix the error below?

Warning: call_user_func_array() expects parameter 2 to be array, string given in /home/u148625395/storage/modification/system/engine/loader.php on line 248

Warning: Invalid argument supplied for foreach() in /home/u148625395/public_html/catalog/controller/event/translation.php on line 8

**Comment by mehtaman** [comment]
I was on OpenCart version 3.0.2.0 and updated to the Alpha release
Upgrade completed all 12 modules
Clicked on Continue and got the error above.

**Comment by straightlight** [comment]
`/home/u148625395/storage/modification/system/engine/loader.php on line 248`

Caused by an installed extension. The original content of storage/modification folder only contains index.html file by default.
