### ISSUE TITLE
[3.1.0.0_a1] Use composer.json/(or package.json) for easier management of Bootstrap, jQuery, FortAwesome, etc.

### ISSUE THREAD

**Issue by panreach** [opencart/opencart#6818]
placeholder...

**Comment by panreach** [comment]
How to add a `build` label for this issue/ticket?

**Comment by schiggi** [comment]
Very good idea!

**Comment by panreach** [comment]
I've been playing around with composer.json as I know it pretty well.  However, I've been using package.json tonight (as I've used it the past year) and I think npm/yarn will be much easier!  I'll try to get something going before my vacation here in a couple of weeks for testing.  I'm honestly not sure what the devs are using here!?  (don't want to step on any toes, but would like to help!)

**Comment by panreach** [comment]
composer has `post-update-cmd` and `post-install-cmd` which I've been forwarding to a `post_composer_install.php` script that copies over the files from `vendor/` to their appropriate directories within OC.

The problem is that `composer` isn't really a js manager.  It's really only for PHP.  I've noticed how this has become factual over the past year with the introductions of npm/yarn.  Composer is becoming more difficult to get the latest js libraries.

npm/yarn  (with package.json) is the way to go here...

Cheers!

**Comment by panreach** [comment]
We can work on the `postinstall` `npm` scripts to accomplish the same thing of copying over `node_modules` files to their appropriate directories in OC.

**Comment by danielkerr** [comment]
not required. just create an extension to update it. or directly alter the code.
