### ISSUE TITLE
JS error in Opencart's checkout - 'dateFormat' in bootstrap-datetimepicker.min.js

### ISSUE THREAD

**Issue by Rishika211** [opencart/opencart#6819]
Hello, I am having this error in checkout page. 

![image](https://user-images.githubusercontent.com/42501271/44306548-9d177f80-a3ae-11e8-9d84-f19d70290138.png)

If you need any extra information, please let me know. Your quick response is highly appreciated. As the site is currently live and unable to process order.

**Comment by howdu** [comment]
Guess you're using the beta version not for live stores yet?

Related: https://github.com/opencart/opencart/issues/6765

**Comment by Rishika211** [comment]
Yes it is live stores. Previously, we were using this site to showcase products. We have enabled payment module now, cart functionality is working fine but unable to checkout product due to this issue. According to you reference, migration to bootstrap 4 will resolve this issue.

**Comment by straightlight** [comment]
Issue possibly linked with this one: https://github.com/opencart/opencart/issues/6830
