### ISSUE TITLE
[3.1.0.0_a1] - Display issues in category page

### ISSUE THREAD

**Issue by Hackej** [opencart/opencart#6821]
Hi!

Some issues with category page.
Latest version GitHub (3.1.0.0_a1) downloaded just now (180819) installed on localhost (XAMPP).
No modifications or altered DB - just demo products, running Chrome.
Just changed Layout to three column for categories.

Viewed Category page, for example Components/Monitors and have following display issues:
- Product Compare button is to short/small (general problem regardless of column setup)
- No space between Product Compare and Grid/List buttons 

Changed to **List view**:
- Image and description separated on different rows and lots of extra space in between rows - see pic below
- Add to cart, Wishlist and Compare buttons do not fill out row at bottom

BR
/Hackej

![image](https://user-images.githubusercontent.com/29421668/44310971-a2d98900-a3df-11e8-833b-30445e084738.png)

**Comment by vivek-webkul** [comment]
I made some correction for the Product List View at category and search layout:

https://github.com/opencart/opencart/pull/6846

**Comment by Hackej** [comment]
Hi!

Much better, although now there is no "Product compare" text on icon.
Maybe should have "Product compare" tooltip instead!?

![skarmklipp](https://user-images.githubusercontent.com/29421668/45640830-38317100-baa3-11e8-8d4b-e803d54ef1c4.PNG)

BR
/Hackej

**Comment by vivek-webkul** [comment]
Tooltip added for both category and search pages with column_left and column_right panel.
![category_tooltip](https://user-images.githubusercontent.com/28401696/45913866-23fdc300-be59-11e8-9593-fb4853bfaa42.png)
![search_tooltip](https://user-images.githubusercontent.com/28401696/45913867-23fdc300-be59-11e8-8476-5f02d8d960ec.png)

**Comment by danielkerr** [comment]
fixed ages ago.
