### ISSUE TITLE
Error on ajax quick checkout page OC 2.3.0.2

### ISSUE THREAD

**Issue by standton** [opencart/opencart#6825]
when we edit on ajax quick checkout then we found an error 

Warning: rmdir(/home/standton/public_html/system/storage/cache/so): Directory not empty in /home/standton/public_html/admin/model/extension/d_opencart_patch/cache.php on line 40

plz help me ....

**Comment by straightlight** [comment]
Duplicated topic: https://github.com/opencart/opencart/issues/6826
