### ISSUE TITLE
Warning: rmdir(/home/standton/public_html/system/storage/cache/so): Directory not empty in /home/standton/public_html/admin/model/extension/d_opencart_patch/cache.php on line 40

### ISSUE THREAD

**Issue by standton** [opencart/opencart#6826]
i am using OC 2.3.0.2 and showing error after ajax page checkout edit 

Warning: rmdir(/home/standton/public_html/system/storage/cache/so): Directory not empty in /home/standton/public_html/admin/model/extension/d_opencart_patch/cache.php on line 40

**Comment by straightlight** [comment]
Post is not about the latest alpha OC version.

**Comment by standton** [comment]
how can slow this problem

**Comment by schiggi** [comment]
That is not a core OC problem. Reach out to the developer of the extension

**Comment by danijelGombac** [comment]
And how is this question related to OC core?

**Comment by straightlight** [comment]
At this time, prior to the alpha release, on the forum please.
