### ISSUE TITLE
Install via composer missing scss.inc.php dependency

### ISSUE THREAD

**Issue by darbymanning** [opencart/opencart#6828]
I've noticed when installing OpenCart via composer that `scss.inc.php` is excluded from `vendor`, which is used by OpenCart when clearing caches from the GUI. Is there a way to include this?

**Comment by straightlight** [comment]
Not a bug. catalog/controller/startup/sass.php file:

`include_once(DIR_STORAGE . 'vendor/leafo/scssphp/scss.inc.php');`
