### ISSUE TITLE
Event: Unable to add script using addscript method

### ISSUE THREAD

**Issue by bhattnishant** [opencart/opencart#6829]
I had setup on event which triggered after header.
Trigger
catalog/view/common/header/before
Action
/extension/module/shopping/index
```

class ControllerExtensionModuleShopping extends Controller {
        public function index() {
		$this->document->addStyle('catalog/view/javascript/jquery/test.css');
		$this->document->addScript('catalog/view/javascript/jquery/test.js');
	}
}
```
it doesn't include anything in template, if i write echo "<scrpit>" that added before <HTML> tag
please advice I want to put one js file inside Head or Body part.

**Comment by samchen945** [comment]
The`index` method needs to accept args.

```
public function index(&$route, &$args) {
```
