### ISSUE TITLE
Twice {% if custom_field.type == 'time' %} in register.twig

### ISSUE THREAD

**Issue by optimlab** [opencart/opencart#6830]
In [catalog/view/theme/default/template/account/register.twig](https://github.com/opencart/opencart/blob/master/upload/catalog/view/theme/default/template/account/register.twig) 
twice   `{% if custom_field.type == 'time' %}`.

Needs `{% if custom_field.type == 'datetime' %}`.

**Comment by howdu** [comment]
Could do with using elseif too.

**Comment by jamesallsup** [comment]
Resolved with #6835
