### ISSUE TITLE
Opencart 3.0.2.0 on Opencart site Vs. Git Master version

### ISSUE THREAD

**Issue by jcamp** [opencart/opencart#6831]
Having issues with Paypal, and just compared the release on Opencart site for **PPExpress 3.0.2.0** compared to the **PPExpress version in the repo** (master) 3.0.2.0 **and they are quite a bit different**?

Should they not be the same?

https://www.opencart.com/index.php?route=cms/download
Vs:
https://github.com/opencart/opencart/releases/download/3.0.2.0/3.0.2.0-OpenCart.zip

Have a lot of issues with the PPExpress extension and would be nice to work out which is the current stable release (Opencart site or Github master or ?)

Cheers

**Comment by straightlight** [comment]
At this time, prior to the alpha release, on the forum please.

**Comment by jamesallsup** [comment]
3.0.2.0 is the current release, however a patch release will be out soon fixing several issues.
Branch is here: https://github.com/opencart/opencart/tree/3.0.2.1_rc - check over the recent commits to see if your issues are resolved. IF they are not then you can create a new issue but please add "BRANCH: 3.0.2.1_rc" in the title so I can pick it up.

Master is a new major update and has lots of structure changes from the current release - it is not stable at this time.
