### ISSUE TITLE
[3.1.0.0_a1] Admin HTML5 form validation broken

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#6832]
This code prevents standard form validation from working. e.g input required

```javascript
//Form Submit for IE Browser
$('button[type=\'submit\']').on('click', function() {
	$('form[id*=\'form-\']').submit();
});
```

This works better:
```javascript
$('button[type=\'submit\']').on('click', function() {
    var $this = $(this);
    var $form = $this.attr('form') ? $('#' + $this.attr('form')) : $this.parents('form');
    if ($form.length && $form[0].checkValidity()) {
        $form.submit();
    }
});
```

**Comment by straightlight** [comment]
Cheers. :)

**Comment by danielkerr** [comment]
On August 17 2021, Internet Explorer 11 (IE11) will no longer be supported by Microsoft's 365 applications and services.

**Comment by howdu** [comment]
@danielkerr it has nothing to do with IE apart from your incorrect code comment. The point here is to make use of the form checkValidity method.
