### ISSUE TITLE
Modifications in php files are not always taken into account

### ISSUE THREAD

**Issue by open-user** [opencart/opencart#6836]
Hi,

I have 2 opencart systems: one is development and the other is production.

1. My development environment is Windows and I am running Opencart from  xammp. the folder structure is as follows: apps\opencart\storage\modification

2. My production environment is Linux, is in a hosting server and I use CPanel to modify all those files that I cannot modify via the admin console. I set to "no cache" my server, because of the problems that I was having. The folder structure is as follows: 
homedir\shopdata\storage\modification\

but opencart is here:

homedir\shop

The problem: IN PRODUCTION ONLY, sometimes, I modify a .twig via the admin console (catalog), and the application takes the change correctly. However, if the modification implies the introduction of new variables coming from a .php file (a text variable), and later on I want to change the text of that variable in the php, the server does not take into account the change.

The last time this happened, I downloaded a complete backup of the website and looked for the old text. It was not in the php file, and it was not in the .twig file, it was here: 
1. homedir\shopdata\storage\modification\catalog\language\en-gb
\common\footer.php

2. mysql\myuser_ocar.sql

I did clean the cache of the application several times, but nothing changed that behaviour. It is a recurrent problem, the variable text of certain php don't get modified. 

Do you know this issue already?

Thanks in advance

**Comment by straightlight** [comment]
For which OC version are you addressing this issue about?

**Comment by open-user** [comment]
Hi,
I am using Version 3.0.2.0. 
Thanks

**Comment by straightlight** [comment]
At this time, prior to the alpha release, on the forum please.

**Comment by danielkerr** [comment]
will grab from the modified
