### ISSUE TITLE
Path disclosure affecting current versions

### ISSUE THREAD

**Issue by rdf1211** [opencart/opencart#6837]
Here is a bug I tried reporting through the opencart@zendesk.com email address with no luck.  I also tried reporting through the forum.  However my account was too new to send private messages.  So as a last resort I am posting it here.

You can see paths on the OS, which can aid in other attacks.

https://demo.opencart.com/index.php?route=product/manufacturer/info&manufacturer_id=7&limit=//test.invalid/%3B%3F

**Comment by stalker780** [comment]
Just disable "Display Errors" checkbox in your store settings. Or modify your php.ini to stop showing errors on production store.

Any way, if an intruder can upload and execute any script on your website he will retrieve these paths with no problems.

**Comment by ADDCreative** [comment]
To switch off all displaying of errors. You need to disable "Display Errors" in the admin setting AND set 'display_errors' to 0 in your php.ini (or other PHP configuration).

You also need to set 'error_display' to false in 'system/config/default.php'.
https://github.com/opencart/opencart/blob/master/upload/system/config/default.php#L53

**Comment by rdf1211** [comment]
@stalker780 The issue is more that this info can make it a lot easier to be able to upload scripts or execute code.  It can help turn a SQLi into a remote shell.

**Comment by danielkerr** [comment]
@rdf1211 your a clown!
