### ISSUE TITLE
Override Pagination class

### ISSUE THREAD

**Issue by gRoberts84** [opencart/opencart#6850]
Hi there,

Struggling to find any information on this and aside from implementing a custom class and overriding in my theme, I don't see anyway of customising the pagination output.

Am I missing something obvious?

Thanks

**Comment by MrPlow254** [comment]
Visit the forums. This isn't a bug or feature

**Comment by danielkerr** [comment]
didnt think about this.

maybe look for pagination in the template data and use regex to replace it.

**Comment by danijelGombac** [comment]
@danielkerr 

Why don't move pagination to the Controller? I tried and is working fine.

```
$data['pagination'] = $this->load->controller('common/pagination', array(
    'total' => $product_total,
    'page'  => $page,
    'limit' => $limit,
    'url'   => $this->url->link('product/search', 'language=' . $this->config->get('config_language') . $url . '&page={page}')
));
```

```
class ControllerCommonPagination extends Controller {
    public function index($setting) {
        if (!isset($setting['limit']) || !(int)$setting['limit']) {
            $limit = 10;
        } else {
            $limit = $setting['limit'];
        }

        if (!isset($setting['total']) || !(int)$setting['total']) {
            $num_pages = 1;
        } else {
            $num_pages = ceil($setting['total'] / $limit);
        }

        if ($num_pages > 1) {
            ........
            ........

            return $this->load->view('common/pagination', $data);
        }
    }
}
```

**Comment by gRoberts84** [comment]
@danielkerr - As a last ditch save, I was going to write a method to rewrite the output however because we can't modify the Twig Environment safely, that's a non-starter either.

A quick change could be to add an event to the pagination that fires before returning the output, allowing you to override it. 

At least that way, you're only changing the Pagination class and it doesn't involve changing all of the controllers to support it etc?

Thoughts?

**Comment by straightlight** [comment]
That would be, indeed, a good idea since it would avoid code redundancy to call a paging library but instead to use the $this->load->controller to load the paging class on a separate controller which, perhaps, could also define its own administrative page limits versus the catalog limit results.
