### ISSUE TITLE
[3.1.0.0_a1] f. 02.09.2018 - Image edit - Clear button not working

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6851]
Situation: 
Open e.g. a product. Go to tab images.
Try to clear a image of the product by click on the Clear button.

Result: Clear button not working - nothing happens

**Comment by vivek-webkul** [comment]
Yes, This was an issue in [3.1.0.0_a1] version. We have already placed an pull request for this issue.
[https://github.com/opencart/opencart/pull/6844](url)

**Comment by pemaier** [comment]
OK thank you. I'll close the issue.

**Comment by vivek-webkul** [comment]
@pemaier - Please don't close the issues till Pull Request accepted.
