### ISSUE TITLE
[3.1.0.0_a1] Admin customer custom fields hidden.

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#6852]
When editing a customer from the admin any custom field which is not required is hidden. 

Problem is that route=customer/customer/customfield only returns the required fields for a custom group so any custom fields which are not required are hidden. 

```js
$('select[name=\'customer_group_id\']').on('change', function() {
	$.ajax({
		url: 'index.php?route=customer/customer/customfield&user_token={{ user_token }}&customer_group_id=' + this.value,
		dataType: 'json',
		success: function(json) {
			$('.custom-field').hide();
			$('.custom-field').removeClass('required');

			for (i = 0; i < json.length; i++) {
				custom_field = json[i];

				$('.custom-field' + custom_field['custom_field_id']).show();

				if (custom_field['required']) {
					$('.custom-field' + custom_field['custom_field_id']).addClass('required');
				}
			}
		},
		error: function(xhr, ajaxOptions, thrownError) {
			alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
		}
	});
});
```

**Comment by vivek-webkul** [comment]
Hi Howdu,

As I checked, there is no such issue found for the same. Please check the added custom fields for the respective Customer Group that you want to use.

![custom fields](https://user-images.githubusercontent.com/28401696/45299437-3d357400-b529-11e8-867d-e021d9694cf7.jpg)

**Comment by vivek-webkul** [comment]
There is some design related issue only at Catalog side:
#6853

**Comment by howdu** [comment]
@vivek-webkul yes that's what was missing
