### ISSUE TITLE
Manual Order Create Does Not Use Cust GRP Product Discount

### ISSUE THREAD

**Issue by Dabnis** [opencart/opencart#6854]
The client has a user-group Trade-A. A product has a discounted price for customer group Trade-A. All works well when a visitor in the customer group logs into the front of the store and places an order, the discounted product price is used, however :
When the client receives a telephone order from a customer in customer group Trade-A and enters an order manually within the admin system, selecting the correct customer group for that telephone client the discounted price for the product is not used, but the products standard none discounted price.

**Comment by danielkerr** [comment]
fixed in master
