### ISSUE TITLE
Opencart V2x,V3x can not normal run,please help me. Error: A theme has not been assigned to this store

### ISSUE THREAD

**Issue by bi7jta** [opencart/opencart#6856]
Hi ,when I download 3.0.2.0, deploy opencart ,everything is successful, but when I login admin page, the system tell me move storage directory，I choose automatic move ,then all is wrong , not matter what I uninstall and reinstall again ,include drop MYSQL, still give error after install, as follow.
Anyone can gime me some suggestion? I have try all version 1.5, 2.x, 3.x,just v1.5 work well.

I google the keywork for one day ,try any method, nothing improve.

Thanks all!

Warning: No such file or directory in /wwwroot/opencart302/system/library/log.php on line 22
Warning: No such file or directory in /wwwroot/opencart302/system/library/log.php on line 22
Warning: fclose() expects parameter 1 to be resource, boolean given in /wwwroot/opencart302/system/library/log.php on line 39
Notice: Undefined index: in /wwwroot/opencart302/catalog/controller/startup/startup.php on line 109
Warning: No such file or directory in /wwwroot/opencart302/system/library/log.php on line 22
Warning: fclose() expects parameter 1 to be resource, boolean given in /wwwroot/opencart302/system/library/log.php on line 39
Warning: Is a directory in /wwwroot/opencart302/system/library/log.php on line 22
Error: A theme has not been assigned to this store!

**Comment by jamesallsup** [comment]
Please use the forum for support questions.

https://forum.opencart.com/
