### ISSUE TITLE
[3.1.0.0a1] Page view after language change jump always to home

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6860]
**Situation:**
e.g. open a product page or any other page in the frontend
then change the language in the top menu
after this the start page is opening in the chosen language.

**but** I expect to stay on the same page which is already open and only the language information has to change.
This was the behaviour of the previous OpenCart versions.

**Comment by danielkerr** [comment]
it does stay on the same page.

**Comment by danielkerr** [comment]
your shop is not configured properly.

yopu can not change languages. 

it has the redirect in the URL

&redirect=https://demo.mig-media.com/demo/shop-310/index.php?route=product/product&amp;amp;language=en-gb&amp;amp;path=33&amp;amp;product_id=31

**Comment by danielkerr** [comment]
ok replaced the url encoding with the correct one.

**Comment by danielkerr** [comment]
fixed.
