### ISSUE TITLE
[3.1.0.0a1] Image clear button not working anymore

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6871]
**Situation:**
Admin login. Open menu-catalog-products-edit a product [product with image]
goto tab Image and click Clear.

**Problem:** Nothing happens
**Expected:** Clear/remove the image

![image](https://user-images.githubusercontent.com/10166095/45544636-87b43a80-b820-11e8-9142-67c2332e62a0.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? local and host server
 - Operating system Linux
 - PHP version 7.0 and 7.1
 - Browser(s) tested with [e.g. chrome, safari - if applicable] firefox
 - Version [e.g. 22] 60.2.0esr

**Comment by vivek-webkul** [comment]
@pemaier  - Please don't close the issues till Pull Request accepted.
