### ISSUE TITLE
[3.1.x.x]  config_compression is passed before the config is populated by the admin

### ISSUE THREAD

**Issue by dmitriyzhuk** [opencart/opencart#6874]
**What version of OpenCart are you reporting this for?**
3.1.x.x
**Describe the bug**
in system/framwork.php line 77 defines the compression

$response->setCompression($config->get('config_compression'));

by default (system/config/default.php) it is set to 0

if you change this in admin it will still be 0 since the configurations from the table settings are populated only in catalog/controller/startup/startup.php

also in the current version, the system/config/default.php does not have a configuration config_compression but instead has response_compression

**To Reproduce**
1. Go to 'system/framework.php'
2. check the value of $config->get('config_compression') - it will be NULL
3. Change the settings in admin panel / system / store / edit compression from 0 to 9 - still nothing

**Expected behavior**
This $config->get('config_compression') should be updated in catalog/controller/startup/startup.php

**Comment by straightlight** [comment]
This solution may also fix the issue as already mentioned prior on GitHub: https://forum.opencart.com/viewtopic.php?f=198&t=204707&p=725370#p725077
