### ISSUE TITLE
Cart is cleared without proper check, by opening checkout/success 

### ISSUE THREAD

**Issue by zemguru** [opencart/opencart#6882]
URL link `?route=checkout/success`, opened outside order process, will always show default "Order placed" message, which - is not correct.

Even more - if You make an order, and reach last "confirmation step" (the moment, when order has been inserted into the database with `status_id=0` (Missing order) ), and then go to `?route=checkout/success` page somehow - cart content is deleted.

There are users, who leaves added products to cart for a long period. This accidental deletion should be fixed.

E.g. - check by session's  order status_id ( >0 ?, not in Missing orders).

**Comment by zemguru** [comment]
Yeah ... will not be so easy, of course. 
Scenario: 
Create order -> Use Paypal payment -> Confirmation step creates Order with status 0, -> user is redirected to Paypal -> Paypal redirects back directly to checkout/success without any post/get additional parameters. but executes "callback" after few seconds/minute.

This would mean - if customer returns to the site BEFORE Paypal has posted `/?route=extension/payment/pp_standard/callback`, order will still be in status=0 :(

**Comment by straightlight** [comment]
OC version unposted.

**Comment by mangeshweb** [comment]
We placed a pull request regarding cart product remove at the checkout process.
#6887

**Comment by zemguru** [comment]
> OC version unposted.

Any. And current master included.

> We placed a pull request regarding cart product remove at the checkout process.

Great! Still - if `checkout/success` is opened directly, it will show "Order created" message, which not correct.

**Comment by mangeshweb** [comment]
I have fixed the issue of opening default order success page and removing the cart product on visiting the URL link?route=checkout/success. Now it will be redirected to the URL link ?route=checkout/checkout, Fixed Patch  #6882

**Comment by danielkerr** [comment]
there is nbo reason a customer needs to visit the success page without being lead there!

this is not a bug! make sure you dont have your default order status to complete.
