### ISSUE TITLE
xdebux and opencart + best IDE for opencart

### ISSUE THREAD

**Issue by rsuchovsky** [opencart/opencart#6883]
Hello, I do not know or this is the post.
If not, then you can delete it.

Would anyone know how to set up xdebux in phpstorm for opencart?
Alternatively, consult other IDEs for opencart. Who should also have automatic code help.
I mean something like [this](https://manovotny.com/static/images/phpstorm-keyboard-shortcuts/phpstorm-keyboard-shortcut-code-completion.gif)

For every advice I will be very grateful
Well thank you.

**Comment by jamesallsup** [comment]
The GiHub bug tracker is not the place to post issues relating to setup, 3rd party modules or general types of questions.

Please read the [project information page](https://github.com/opencart/opencart/blob/master/README.md#reporting-a-bug-and-security-issues) which should guide you in the right direction for support.

Kind regards, J
