### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Scssc' not found

### ISSUE THREAD

**Issue by auwalismail** [opencart/opencart#6890]
I tried to clear the template and scssc from admin dashboard when I encountered this error. I tried changing permissions as some people suggested, I also commented on the specific error line in the scssc.php file but nothing changed, I still cannot access the admin page.

Error:
**Fatal error:** Uncaught Error: Class 'Scssc' not found in /home/www/estore.mydomain.com/admin/controller/startup/sass.php:9 Stack trace: #0 /home/www/estore.mydomain.com/system/engine/action.php(79): ControllerStartupSass->index() #1 /home/www/estore.mydomain.com/system/engine/router.php(67): Action->execute(Object(Registry)) #2 /home/www/estore.mydomain.com/system/engine/router.php(46): Router->execute(Object(Action)) #3 /home/www/estore.mydomain.com/system/framework.php(168): Router->dispatch(Object(Action), Object(Action)) #4 /home/www/estore.mydomain.com/system/startup.php(104): require_once('/home/www/estor...') #5 /home/www/estore.mydomain.com/admin/index.php(19): start('admin') #6 {main} thrown in **/home/www/estore.mydomain.com/admin/controller/startup/sass.php on line 9**

Any hint or clue as the cause of this error and how to resolve will be highly appreciated.

**Comment by jamesallsup** [comment]
Create a new issue using the bug report template, posting a Fatal error output will not help unless you answer the other questions too.

**Comment by auwalismail** [comment]
Issue fixed by replacing the /admin folder with a fresh download and changing directory paths and mysql details in config.php.

**Comment by anshushukla01** [comment]
Can I get more detail how to solve this error as I am also getting the same error

**Comment by codingtalkie** [comment]
I hit the very error today. I clicked the cache cleared button and ended up in No man's land. How to fix this ?
