### ISSUE TITLE
[3.1.0.0a1] Our stores is working in default shop only

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6892]
**Situation 1:**
Goto Admin/Location/Store Location
Add a new Store Location
Goto Settings
Edit 1st Store (default store)
Goto tab Store and scroll to bottom
Activate the new Store Location
Press Save
Open 2nd Store at the Front-end and open Contact us

**Problem**
Store Location (Our Stores) is present in 2nd store and all following stores

**Expected**
No Store Location at 2nd store (only at 1st store/default store)

**Situation 2:**
Goto Admin/Location/Store Location
Add a new Store Location (if not already done)
Goto Settings
Goto 1st store (default store)
and deactivate the local store form Situation 1 and save
Edit 2nd Store (not default store)
Goto tab Store and scroll to bottom
Activate the new Store Location
Edit 2nd Store (not default store) again 
do nothing and save again (Store location is not activated if you)
Open 2nd Store at the Front-end and open Contact us

**Problem**
Store Location (Our Stores) is missing

**Expected**
![image](https://user-images.githubusercontent.com/10166095/45915630-b9e91c00-be60-11e8-956c-e9b9d99a9b51.png)

**Comment by vivek-webkul** [comment]
#6988 Multi store locations related issue has been resolved.
