### ISSUE TITLE
[OC 3.1.0.0a1] Reward point calculation - Option points are not considered in point calculation

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6893]
**Situation**
The same situation as in issue [6154](https://github.com/opencart/opencart/issues/6154)
Product:
![image](https://user-images.githubusercontent.com/10166095/45915966-e738c880-be66-11e8-974b-1e3835042fde.png)
Product Options:
![image](https://user-images.githubusercontent.com/10166095/45915977-0df6ff00-be67-11e8-935c-9b951bc386f2.png)

**Problem**
The additional points(-costs) from the options are 
a) not added to the point(-price) the customer has to pay for the hole product nor 
b) they are added to the Reward Points in the sales order.
Calculation now: 
a) Product points (-cost) 200 points = 200 points (to pay)
b) Product points (reward) 100 points = 100 points (reward)
![image](https://user-images.githubusercontent.com/10166095/45916024-a55c5200-be67-11e8-9897-bdf400cd9c85.png)

**Expected**
Calculation a) or b) but not nothing
a) Product cost 200 points + Option Green +30 points = 230 points (to pay)
or
b)  Product reward 100 points + Option Green +30 points = 130 points (reward)

**Comment by vivek-webkul** [comment]
Pulled for reward points added on cart page. #6845

**Comment by vivek-webkul** [comment]
According to your calculation:
a) Product cost 200 points + Option Green +30 points = 230 points (to pay)
![products](https://user-images.githubusercontent.com/28401696/45917817-e6ba2500-be9a-11e8-851c-7e5dae651ec8.jpg)
![product options](https://user-images.githubusercontent.com/28401696/45917818-e752bb80-be9a-11e8-9072-b68ffd58dad4.jpg)

I used "HTC Touch HD" product with 200 reward points and with Large (+$30.00) product option with 30 reward points, then after adding this product with the same product option to the cart, I have to pay total 230 reward points to buy this product.

![htc touch hd](https://user-images.githubusercontent.com/28401696/45917849-50d2ca00-be9b-11e8-8f1c-498807ced076.jpg)
![shopping cart](https://user-images.githubusercontent.com/28401696/45917850-50d2ca00-be9b-11e8-862f-2e75a5095b60.jpg)

Which is working correct, please correct me if I am wrong!

**Comment by pemaier** [comment]
Hello vivek-webcul thank you for your support.
In the current example we see
1) Product has reward points which have to be confirmed in the order (fro transfer to the point account)
That is OK.
2) Product has point (-costs) which are calculated with option points (not by product) but by the total costs.
That is also OK (In my mini-cart view I do not get the view with Reward Points calculated)

But if I press the Button Apply Points I get an error message. (Customer has already 120 points)
![image](https://user-images.githubusercontent.com/10166095/45920511-b760e380-bead-11e8-95cf-9b514d1c4c4e.png)

**Comment by vivek-webkul** [comment]
@pemaier - Yes, I understood your point, that you are not able to add the reward point from customer end.
But If you will check the details in this #6845 pull request, I described about the same issue that you are facing:
https://user-images.githubusercontent.com/28401696/44946030-b0e0ce00-ae11-11e8-99c7-90700dfd7b45.jpg

**Comment by pemaier** [comment]
Hello vivek-webcul **thank you**.
I see you are already on the problem. And thank you for helping to understand the situation.
But please be so kind and think in the future for customer wishes to see the point-costs of a product within the product page.
I'll close the message now.

**Comment by vivek-webkul** [comment]
Yes, Sure!! You're Welcome anytime!!
