### ISSUE TITLE
[3.1.0.0a1] Setting - Comment information not consider CR

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6894]
**Situation**
![image](https://user-images.githubusercontent.com/10166095/45916359-3e419c00-be6d-11e8-86a7-66abb4b28bb0.png)

**Problem**
![image](https://user-images.githubusercontent.com/10166095/45916365-6a5d1d00-be6d-11e8-906c-5d82a8e76639.png)

**To Reproduce**
1. Go to Admin store settings
2. Enter the information in Comment field
3. Save
4. See error on the Front-End

**Expected behavior**
Same as in the Opening Times field

**Comment by vivek-webkul** [comment]
@pemaier - I think this is not an issue, because for the comment section they have used the "<textarea>" and if we considered the working of this field like HTML content, then we can use ckeditor.

And Store Timing can be in multiple (different) time slots, that's why they used new lines "nl2br()" for timing section.

**Comment by straightlight** [comment]
`See error on the Front-End`

What error message do you see on the front-end?

**Comment by vivek-webkul** [comment]
Please check and correct me if I am wrong.

![contact us](https://user-images.githubusercontent.com/28401696/45917563-8bd2fe80-be97-11e8-9c54-3c03b5006eba.jpg)

**Comment by straightlight** [comment]
Another documentation example would be with the wordwrap function from TWIG files: https://stackoverflow.com/questions/22305675/twig-extensions-for-shortening-text

**Comment by pemaier** [comment]
I was writing the message because some of my customers always ask about line-breaks in there comment area because they prefer a structured presentation with 2 or 3 informations in the field. And in the Opening Times field they see that it's possible. 2 areas with different behaviour is difficult to understand for ordinary customers.
