### ISSUE TITLE
Plaza Themes Fake

### ISSUE THREAD

**Issue by yogvag** [opencart/opencart#6895]
I purchased Nego theme from themeforest which is designed by plaza themes I paid $48 and they sold me bugged theme also when I emailed them to send me the correct theme they didn't respond. I asked for support they fixed one issue and raised the other. Even still I have support duration left they have stopped responding to all my email and providing services.

**Comment by jamesallsup** [comment]
Contact themeforest. that is who you paid - not OpenCart.

If you need OpenCart support then you need to buy on our platform in future.
