### ISSUE TITLE
[3.1.0.0a1] Modul gdpr (cookies) - Position and language

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6909]
**Situation**
The position of the gdpr modul is on top of the page.

**Problem 1**
The visitor is not able to change the language into a language (multilanguage shops) he can read and understand. The Cookie information is over the language selection. The visitor is forced to accept Cookies even he doesn't understand the language which is present at the initial opening of the site.

![image](https://user-images.githubusercontent.com/10166095/46074830-5e38ce80-c191-11e8-9f9a-9657dbbfab06.png)

**Problem 2**
Other languages need unicode or utf-8.
Sample: Wir verwenden Cookies, um Ihnen das bestm**ö**gliche Nutzererlebnis zu bieten.
![image](https://user-images.githubusercontent.com/10166095/46177218-c46d4080-c2ba-11e8-8dad-cdcd81a7a09d.png)

**Problem 3**
The Cookie information is only shown up in the 1st language of the language configuration.
In this case only in German.
![image](https://user-images.githubusercontent.com/10166095/46246226-fdb0c800-c402-11e8-9479-5eee9a96183f.png)

**Comment by andrei-bogdan** [comment]
How exactly can I replicate this exact module setup? Please provide more information/steps.

**Comment by pemaier** [comment]
Hello Bogdan.

1. Standard activation of the module. (admin right, extension
activation and settings)
2. Install 2-3 languages
3. Edit the language files in the installed languages

Test the standard: English
Test other languages: Change the default front-end langaues

(Don't forget to keep the behavior of the browser cache in mind.)


-- 
With best regards / Mit freundlichen Grüßen / С уважением

Peter Maier

**Comment by andrei-bogdan** [comment]
Sorry, can't find such a module in the standard installation. Am I missing something?

**Comment by danielkerr** [comment]
the staff member who implemented this did a bad job! fixing now.

**Comment by ADDCreative** [comment]
The original module added would be no good for the GDPR anyway (probably OK for the soon to be replaced ePrivacy Directive) . If you really need to ask for consent for processing personal data (which may or may not involve a cookie being set), it comes nowhere near the standard required, as you need to record consent.

See the "How should we record consent?" section at the link below.
https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/consent/how-should-we-obtain-record-and-manage-consent/

Fortunately you shouldn't need to use consent for the most part of an online store. Script and cookie wise, the AddThis script on the product page is the probably the main concern, as they collect data from visitors to your site. Ideally you would need to inform, gain consent and record consent before allowing the script to run. The Google reCAPTCHA module may also need consent, if another legal basis can't be justified.

**Comment by danielkerr** [comment]
"ePrivacy Directive" sick of them coming up with crap laws.

**Comment by danielkerr** [comment]
i'm adding a waiting list so people can delete their accounts and also see what data we hold about them.

**Comment by danielkerr** [comment]
Do you think thats enough for GDRP?

**Comment by pemaier** [comment]
A 1st view point... it is required to place on the -Contact Us- page a checkbox that the customer agree to the Privacy Policy before he can send a message.
![image](https://user-images.githubusercontent.com/10166095/46895227-25327680-ce80-11e8-8dac-5806944497bd.png)

**Comment by danielkerr** [comment]
I will add a gdrp info page with a skeleton document

**Comment by osworx** [comment]
> 
> 
> A 1st view point... it is required to place on the -Contact Us- page a checkbox that the customer agree to the Privacy Policy before he can send a message.
> ![image](https://user-images.githubusercontent.com/10166095/46895227-25327680-ce80-11e8-8dac-5806944497bd.png)

Not really true, because if someone contacts you (via Contact Us Page), the visitor is doing an action on his own behalf.
There are many discussions about adding a checkbox to a form (like this), some of them say yes, most of them say no.
The more, because the standard contact form in OpenCart has no further actions combined (e.g. answering through the system, or assigning it to an order, or doing more like in a CRM).

And finally, 
1. IF there would be a checkbox, the consent has to be stored! 
2. And the customer/visitor should be able to withdraw his consent.

General: a contact form is something every visitor should know that further actions are done electronically.
No more consent is required.

More helpfully would be an additional text (with link) what this form can be used for - and the link points to the Privacy Statement.

See also Article 6 GDPR

But (!), if the contact form would have required fields like phone number, company name etc. > then a Checkbox is required.
Everything else is stupid and nonsens!

Sample articles: https://www.webcellent.com/blog/eu-dsgvo-datenschutz-checkbox-pflicht-fuer-kontaktformulare/
https://www.datenschutz-janolaw.de/info-faq/informationen/dsgvo/einwilligung.html
https://www.datenschutz-guru.de/braucht-mein-kontaktformular-jetzt-eine-checkbox/ (Podcast around 6:00)

**Comment by ADDCreative** [comment]
@pemaier To second what @osworx said. There is no need to have a "agree" checkbox for a contact form, as long as you are only using the data to action and reply to their request (If you were adding their details to a mailing list that would be a totally different matter). The legal basis will be contract or maybe even legitimate interest (if you can justify it). To have a "agree" checkbox would imply you are gaining consent, which the rules for are not easy to implement (see my previous comment).

A simple notice is what's need in most cases.
> For information about what we do with personal data see our **privacy notice**.

I would even go as far to say the "agree" checkboxes on registering an account are not required. See the "Create an account" example on the ICO website.
https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/the-right-to-be-informed/how-should-we-provide-privacy-information-to-individuals/#how4

**Comment by danielkerr** [comment]
im not adding agree to terms for contact us!

**Comment by davidfranks** [comment]
@danielkerr seems you have referenced it as "gdrp" in various places. 

(here for example - upload/admin/controller/mail/gdrp.php)

It should be "gdpr" no?

**Comment by danielkerr** [comment]
@davidfranks yes. just creating the files to quick without checking.

**Comment by danielkerr** [comment]
been updated and fixed.
