### ISSUE TITLE
At checkout existing customer login not working

### ISSUE THREAD

**Issue by shohag0910** [opencart/opencart#6918]
i am facing issue with opencart 3.0.2.0 default theme
when trying to test existing customer login is not working at checkout page and if i press F5 than if move to next page.

**Comment by jamesallsup** [comment]
Sorry to hear you have an issue, the GiHub bug tracker is not the place to post issues relating to setup, 3rd party modules or general types of questions.

Please read the [project information page](https://github.com/opencart/opencart/blob/master/README.md#reporting-a-bug-and-security-issues) which should guide you in the right direction for support.

Kind regards, J
