### ISSUE TITLE
[3.0.2.0] - "select" based option values mess up with pressing backspace / previous page button after save on product page.

### ISSUE THREAD

**Issue by TimwaySupport** [opencart/opencart#6921]
**What version of OpenCart are you reporting this for?
Confirm on 3.0.2.0, 2.0.1.0.

**Describe the bug**
When pressing backspace / previous page (or mouse backspace button) after "save" product to go back to product editing page, the product option value will mess up (become empty or mix up, anyway, wrong value).

**To Reproduce**
1. Access any product editing page with at least 2 product option (each product option, at least 2 option value).
2. Click "Save" to save the product.
3. Click "backspace" / previous page on browser to go back to product editing page.
4. Click "option" tag again, some option value will become empty unexpectedly.

**Expected behavior**
The option value should correctly show (the status before clicking the "save" button).

**Server / Test environment (please complete the following information):**
Chrome v69, Windows.

**Comment by andrei-bogdan** [comment]
You should not use the Back button, because this will go to the previous page without any of your values being selected. The chosen values actually get send by POST method when you actually press the Save button. When you go back, there is no Save button pressed.

If you wish to return to the product, you should use the Edit link for that product from the Products page.

**Comment by TimwaySupport** [comment]
Thank you for your reply.

Anyway to make Opencart compatible with the back button?
Sure I will take your advice to click "edit" to avoid the issue in the future, clicking back button (or last last  page button) is much much faster.

Imagine a "world 2" have an Opencart compatible with back button, would it be nice?

**Comment by andrei-bogdan** [comment]
This is not related to Opencart itself, but more to each browser's behaviour in particular. More about this:
https://stackoverflow.com/questions/1485672/losing-form-data-when-clicking-the-back-button-on-browser

**Comment by TimwaySupport** [comment]
Thank you for your reply.
Agree that it's common browser issue, not Opencart specific.
