### ISSUE TITLE
[3.1.0.0a1] .form-group.row + .form-group.row margins

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#6922]
https://i.imgur.com/tJVkzgc.png

https://i.imgur.com/f8NZvnw.png

First row has margin-left|margin-right: -15px
All other rows have -20px margin

**Comment by andrei-bogdan** [comment]
Why should this be a bug? I think the first row needs that margin to preserve the Tab design.

**Comment by stalker780** [comment]
@andrei-bogdan Don't understand what you mean talking about "tab design". 
Why they should be there?
OC3.0 have no such margins for first row.

I'm sure there is a typo in css.

**Comment by andrei-bogdan** [comment]
I was talking about the tabs section here, Data tab being currently selected: https://i.imgur.com/tJVkzgc.png
If this spacing persists in other sections, then it might have been slightly ignored.

**Comment by danielkerr** [comment]
i just spotted it. very hard to see. about 1 or 2 pixels not aligned.

**Comment by danielkerr** [comment]
you have very good attention to detail. cheers!

**Comment by stalker780** [comment]
a6c473e2e26567d3d8eb8da18ddb74239eb4bb18

**Comment by danielkerr** [comment]
already fixed
