### ISSUE TITLE
Smtp class broken

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#6923]
VERSION 3.1.0.0_a1

After last changes in  opencart/upload/system/library/mail/smtp.php these errors are displayed:

PHP Notice:  Array to string conversion in system/library/mail/smtp.php

And in the mail content:

> Array
> Array
> Array
> Array
> Array
> Array
> Array
> Array

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/issues/6880
