### ISSUE TITLE
Frontend error and JSON error Warning: fopen(/system/cache/cache.language

### ISSUE THREAD

**Issue by Godly75** [opencart/opencart#6925]
**What version of OpenCart are you reporting this for?**
3.0.2.0

**Describe the bug**

Error on the file.php at frontend
Warning: fopen(/home/encounters/domains/encounters.be/shop_update/system/cache/cache.catalog.language.1538511947): failed to open stream: No such file or directory in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 38Warning: flock() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 39Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 40Warning: fflush() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 41Warning: flock() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 42Warning: fclose() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 43Warning: fopen(/home/encounters/domains/encounters.be/shop_update/system/cache/cache.currency.1538511947): failed to open stream: No such file or directory in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 38Warning: flock() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 39Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 40Warning: fflush() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 41Warning: flock() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 42Warning: fclose() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 43Warning: fopen(/home/encounters/domains/encounters.be/shop_update/system/cache/cache.catalog.language.1538511948): failed to open stream: No such file or directory in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 38Warning: flock() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 39Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 40Warning: fflush() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 41Warning: flock() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 42Warning: fclose() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 43Warning: fopen(/home/encounters/domains/encounters.be/shop_update/system/cache/cache.currency.1538511948): failed to open stream: No such file or directory in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 38Warning: flock() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 39Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 40Warning: fflush() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 41Warning: flock() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 42Warning: fclose() expects parameter 1 to be resource, boolean given in /home/encounters/domains/encounters.be/public_html/shop_update/system/library/cache/file.php on line 43

**To Reproduce**
go to front end or click the favorites logo

**Screenshots / Screen recordings**
https://i.imgur.com/43Bvc7C.jpg

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system w10
 - PHP version 7.0
 - Apache version ?
 - Browser(s) tested with chrome
 - Version latest

**Additional context**

**Comment by Godly75** [comment]
Any help on this?

**Comment by straightlight** [comment]
Te solution has already been posted on the forum. In your catalog/model/localisation/language.php file, you will notice different lines from this file on Github's code. The issue with v3.0.2.0 was with the cache language key name.

**Comment by Godly75** [comment]
Thx, i asked but no help there

**Comment by Godly75** [comment]
Do i need to remove the language files ?

**Comment by Godly75** [comment]
or what file do i need to replace?

**Comment by ADDCreative** [comment]
It look like a configuration issue to be. See the replies to your forum post.

**Comment by ClayRabbit** [comment]
Even on demo.opencart.com website this error appears sometimes:
![2020-09-09_19-35-28](https://user-images.githubusercontent.com/4585866/92612939-d09a0f00-f2d3-11ea-9040-003a9415b8a4.png)

**Comment by WebkulOpencart** [comment]
this issue is resolved so closing the same.
