### ISSUE TITLE
[3.1.x.x] Bootstrap datetimepicker error / css issue

### ISSUE THREAD

**Issue by MrPlow254** [opencart/opencart#6931]
**What version of OpenCart are you reporting this for?**
[Build 9125](https://github.com/opencart/opencart/commit/07630f031920f8f8924107f2d35fa528e445ec9a)
**Describe the bug**
TypeError is one of the issues with it. The calendar is not in the correct div causing it to be hidden on the bottom part.

(/upload/admin/view/javascript/jquery/bootstrap-datetimepicker.css)

What section does it affect?
Any date time picker box
[Picture of Error](https://user-images.githubusercontent.com/1266825/46495792-5a85f700-c7e4-11e8-986e-dce58af1e2ed.png)

**Comment by andrei-bogdan** [comment]
Hi, I am not able to replicate this. Please provide more info, for start:
- browser version
- screen resolution
- operating system version

**Comment by MrPlow254** [comment]
@andrei-bogdan are you not using the latest opencart? It works in 3.0.1.1 but the 3.1 version it seems broken.

**Comment by MrPlow254** [comment]
The issue is the plugin is made for bootstrap 3.3.5 and the admin portal has 4.0.0

**Comment by stalker780** [comment]
I confirm a problem on a latest build.

1. In discount tab datepicker looks absolutely different from one in Data tab.
2. Calendar doesn't fit outer div.
3. It resizes .table-responsive div making it scrollable, instead showing it as absolute positioning.

Screen: https://i.imgur.com/U81MxDz.png

**Comment by webkul-dilip** [comment]
This issue not found in the maintenance-branch+3.0.x.x branch,  please close this issue
