### ISSUE TITLE
[3.1.x.x] Fixer currency doing reverse default conversion

### ISSUE THREAD

**Issue by xtensions** [opencart/opencart#6933]
**What version of OpenCart are you reporting this for?**
[3.1.x.x]

**Describe the bug**
When you use fixer as currency converter and run the cron, the currencies are converting in reverse conversion. 
For example : 1 USD becomes 0.01358973 INR when it should be 73.58500359 INR
In actual 1INR is 0.01358973 USD

**To Reproduce**
Use Fixer as currency converter and run the cron job.

**Expected behavior**
1USD should be 73.58500359 INR

**Screenshots / Screen recordings**
<img width="1132" alt="screen shot 2018-10-05 at 12 18 08 pm" src="https://user-images.githubusercontent.com/14876525/46520435-a47ce480-c899-11e8-9605-67e85495aabc.png">

**Server / Test environment (please complete the following information):**
 localhost, php 7.1 on Mac

**Additional context**
Fix should be: 
admin/controller/extension/currency/fixer.php - Line 119
Change
`$this->model_localisation_currency->editValueByCode($currency['code'], ($response_info['rates'][$default] / $response_info['rates'][$currency['code']]));`

to

`$this->model_localisation_currency->editValueByCode($currency['code'], ($response_info['rates'][$currency['code']] / $response_info['rates'][$default]));`

Sorry could not create a pull request as my previous request is not yet accepted or rejected in the repository. So new PR would have added more files from previous PR on this PR.
**[Ocmod should allow more than one install.xml](https://github.com/opencart/opencart/pull/6461)**

**Comment by xtensions** [comment]
Also we should be adding an additional check on Line - 118 to avoid division by zero.

Although fixer would almost always send all currency codes but who knows.

Change
`if (isset($response_info['rates'][$currency['code']])) {`

to

`if (isset($response_info['rates'][$currency['code']]) && isset($response_info['rates'][$default])) {`

**Comment by danielkerr** [comment]
yes working on it now

**Comment by danielkerr** [comment]
@xtensions you have provided a solution without testing it. 

you need to divide by 1 with the result and not switch it around.

**Comment by xtensions** [comment]
Hi @danielkerr 

Of course I tested it.

$from = $currencies['EUR'];
$to = $currencies[$result['code']];
1 / ($currencies[$default] * ($from / $to)

 is always equal to what i provided as below.

$response_info['rates'][$currency['code']] / $response_info['rates'][$default]

because $from will always be 1 as EUR is the base in fixer.io and thats why is hardcoded in the fix. 

so 1/$currencies[$default] *(1/$to) is actually ($to/$currencies[$default]) as 1 will cancel each other out.

Anyways both solutions works.
