### ISSUE TITLE
[v3.1.0.0a1 - OC Admin - PayPal braintree and express twig files

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6937]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
- admin/view/template/extension/payment/pp_braintree_preferred.twig file shows:

`<div class="col-lg-8 col-md-8 col-sm-8">`

on line 38.

- admin/view/template/extension/payment/pp_express_preferred.twig file shows:

`<div class="col-lg-9 col-md-9 col-sm-9">`

on line 37.

pp_braintree_express.twig shows:

`<img class="float-right img-responsive"`

while pp_express_preferred.twig file shows:

`<p><img class="float-right"`

**To Reproduce**
Also appears on the namespace codes.

**Expected behavior**
To use responsive codes version.

**Server / Test environment (please complete the following information):**
May affect page outputs.

**Additional context**
No additional context.

**Comment by straightlight** [comment]
Also line 23 on both TWIG files with col 3 and col 4.

**Comment by andrei-bogdan** [comment]
I can't find all the mentioned twigs on `3.1.0.0alpha`, am I missing something?

**Comment by danielkerr** [comment]
has been removed in latest version and is replaced with a new intergration.
