### ISSUE TITLE
Query bug in catalog/model/catalog/product.php in the function getProduct($product_id)

### ISSUE THREAD

**Issue by trianity** [opencart/opencart#6939]
**What version of OpenCart are you reporting this for?**
3.0.2.0 and master

**Describe the bug**
_A clear and concise description of what the bug is
What section does it affect?_
Wrong query, resulting the discount price will never (or in the limited case) show on the product page.

**To Reproduce**
1. Go to Admin Panel and set a discount price to any product
2. Go to shop and look at the product page of this product
3. Find the Price section of the page
4. You will not see the discount

**Expected behavior**
_A clear and concise description of what you expected to happen._
If I will set the discount I should see it.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? n./a.
 - Operating system n./a.
 - PHP version n./a.
 - Apache version n./a.
 - Browser(s) tested with [e.g. chrome, safari - if applicable] n./a.
 - Version [3.0.2.0]

**Additional context**

Here is the wrong query copied from the master file from:
[https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/product.php](https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/product.php)

public function getProduct($product_id) in the first line:
$query = $this->db->query("SELECT DISTINCT *, pd.name AS name, p.image, m.name AS manufacturer, (SELECT price FROM " . DB_PREFIX . "**product_discount pd2** WHERE pd2.product_id = p.product_id AND pd2.customer_group_id = '" . (int)$this->config->get('config_customer_group_id') . "' AND **pd2.quantity = '1'** 

Using this query the discount will appear only if the quantity = 1, in the volume discount the quantity is usually more then 1, so this logical error will break the discount display.
The function will work, if **pd2.quantity > '1'**

**Comment by AkkuFresh** [comment]
There is a too same query bug in the second function:
public function getProducts($data = array()) {
		$sql = "SELECT p.product_id, ...
also.

**Comment by andrei-bogdan** [comment]
@AkkuFresh I believe the functionality you are looking for is Special price. You should set a Special price to your product, in order to see it. As for the Discount price, it should work as @ADDCreative explained above.

**Comment by AkkuFresh** [comment]
@andrei-bogdan and @ADDCreative  Thanks for the replay. I double checked it.
The public function getProductDiscounts($product_id) works well, and the query string is there quantity > 1. And this query should be in th public function getProduct($product_id) also.
In the product detail page the public function getProduct($product_id) will fetch the discount data through the mentioned query.
In my open cart installation I repaired the mentioned query and the report was done after the checked solution.

**Comment by andrei-bogdan** [comment]
The function getProduct() will fetch the discount data only on the product detail page, because that is the only place where those quantity options do exist. It can't fetch discount data in the catalog/category page that lists products (for example), because there is no option to select quantity there.

**Comment by schiggi** [comment]
Don't forget, that you can use discount prices to have separate pricing for separate customer groups and therefore stores (in multi-store envs, e.g. for each country one store). So with default behavior, if you set up a custom price for a special customer group (with qty =1), it will overwrite the normal price and show in category and product detail page. For further discounts on qty, you can use the mentioned method to retrieve discounts.

This behavior is very useful for mult-store envs and for B2B web stores. Not sure, if that was the intended behavior of the devs, but it works like this pretty well.

**Comment by WebkulOpencart** [comment]
@trianity This query used to display the single unit price on the listing pages like- search, category, etc.
While on the product page it uses a separate query to fetch the discount.
