### ISSUE TITLE
Class 'PHP_CodeSniffer_Exception' not found in ValidVariableNameSniff.php:15

### ISSUE THREAD

**Issue by andrei-bogdan** [opencart/opencart#6942]
Hi,

I have been trying use the command mentioned here: https://github.com/opencart/opencart/wiki/Coding-standards#php-codesniffer

This is what I used, after installing it to the **installed_paths**:
`$ phpcs --standard=OpenCart opencart`

As far as I read online, the problem isn't my setup, but it is related to the ruleset itself. Error is:

`PHP Fatal error:  Uncaught Error: Class 'PHP_CodeSniffer_Exception' not found in /Users/.../www/opencart/tests/phpcs/OpenCart/Sniffs/Variables/ValidVariableNameSniff.php:15
Stack trace:
#0 /usr/local/pear/share/pear/PHP/CodeSniffer/autoload.php(167): include()
#1 /usr/local/pear/share/pear/PHP/CodeSniffer/src/Ruleset.php(1129): PHP_CodeSniffer\Autoload::loadFile('/Users/...')
#2 /usr/local/pear/share/pear/PHP/CodeSniffer/src/Ruleset.php(217): PHP_CodeSniffer\Ruleset->registerSniffs(Array, Array, Array)
#3 /usr/local/pear/share/pear/PHP/CodeSniffer/src/Runner.php(294): PHP_CodeSniffer\Ruleset->__construct(Object(PHP_CodeSniffer\Config))
#4 /usr/local/pear/share/pear/PHP/CodeSniffer/src/Runner.php(70): PHP_CodeSniffer\Runner->init()
#5 /usr/local/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#6 {main}
  thrown in /Users/.../www/opencart/tests/phpcs/OpenCart/Sniffs/Variables/ValidVariableNameSniff.php on line 15`

In PHPStorm, the same warning shows up, the class doesn't seem to be defined.

Has anybody been experiencing this error? Do you have any suggestions?

**Comment by danielkerr** [comment]
no idea about this as i didn't add it.
