### ISSUE TITLE
Opencart Version 3.0.2.0:- Cannot redeclare class Composer in system/library/template/Twig/Autoloader.php

### ISSUE THREAD

**Issue by bssolet** [opencart/opencart#6950]
Opencart Version 3.0.2.0:- 

i was working on Opencart Version 3.0.2.0 site, after doing some modifation in header.twig file (i have added <link rel="canonical" href="https://edgeandfire.com{{ app.request.pathinfo }}" /> this code in header.twig file, locaiton => http://prntscr.com/l5n71s )

but after adding this code I am getting this error = >http://prntscr.com/l5n7if.

I reverted back my changes, even i restore this file with an old backup file that i downloaded just before to start changes and after that clear and refresh cache from admin section => https://prnt.sc/l5n7x8, but still, I am getting the same error, I don't know how to fix this error. please help me to fix this issue 

Thanks

**Comment by danielkerr** [comment]
this area iws not for support of extensions. please contact the main site forum or contact us.
