### ISSUE TITLE
Documentation: Hostjars link not working

### ISSUE THREAD

**Issue by louposk** [opencart/opencart#6952]
Navigate to documentation: http://docs.opencart.com/en-gb/developer/loading/
Go to section: Additional Information (in the bottom)
In the last sentence "To see how loaded files can be utilized in a basic module, see the DIY Module from HostJars" there is a link to HostJars website. If you click it, you will be redirected to http://opencart.hostjars.com/ which does not work due to an error.

Also, https://hostjars.com/ seems to not work also.

**Comment by danielkerr** [comment]
removed. i think he closed his hosting down.

**Comment by JimBacon** [comment]
Also two links in the first paragraph of http://docs.opencart.com/en-gb/developer/module/
