### ISSUE TITLE
[Build# 9138 - 3.1.0.0_b] Adding customer address iterates starting at 0 vs 1

### ISSUE THREAD

**Issue by MrPlow254** [opencart/opencart#6954]
**What version of OpenCart are you reporting this for?**
[Build# 9138](https://github.com/opencart/opencart/tree/40ac4cdf0a75ab6a3b731fac7b142a3491ead27c) - 3.1.0.0_b

**Describe the bug**
Account address iterates starting at 0 instead of 1.

What section does it affect?
Page: admin/index.php?route=customer/customer/add
Tap: Addresses

**To Reproduce**
1. admin/index.php?route=customer/customer/add
2. Click on 'Add Address'
4. See error in intoration number in the top left 'Address 0' instead of address 1

**Expected behavior**
While an array starts at 0 the output visually to the user should start at 1.

**Comment by danielkerr** [comment]
already fixed in latest

**Comment by vivek-webkul** [comment]
#6896

**Comment by MrPlow254** [comment]
@danielkerr Now it shows Address 2 on the addresses tap vs Address 1 when loading a customer with addresses already. So to clarify my initial post outlines what should be done.

**Comment by danielkerr** [comment]
Nothing needs to be done it's just for reffernce

**Comment by MrPlow254** [comment]
People will be wondering where Address 1 is. Its because line 298

![image](https://user-images.githubusercontent.com/1266825/47657259-1548b100-db67-11e8-8918-a2e4085d1a68.png)
