### ISSUE TITLE
[Build# 9138 - 3.1.0.0_b] Adding affiliate bug. customer_group_id is undefined.

### ISSUE THREAD

**Issue by MrPlow254** [opencart/opencart#6955]
**What version of OpenCart are you reporting this for?**
[Build# 9138](https://github.com/opencart/opencart/tree/40ac4cdf0a75ab6a3b731fac7b142a3491ead27c) - 3.1.0.0_b

**Describe the bug**
Creating an affiliate does not define customer_group_id
What section does it affect?
Page: admin/index.php?route=marketing/affiliate/edit

**To Reproduce**
1. Go to 'marketing/affiliate'
2. Click on '+' to add a new affiliate
3. Enter all the information for the user
4. Click save
5. Error pops up on the screen saying customer_group_id is undefined.

**Additional context**
Notice: Undefined index: customer_group_id in C:\htdocs\upload\admin\controller\marketing\affiliate.php on line 733

**Comment by MrPlow254** [comment]
@danielkerr Creating a new affiliate works now. However when editing an existing affiliate the customer id="input-customer" becomes set to value="" on a failed save. I am assuming this is code for when creating a new affiliate; make sure this is not broken when editing is fixed. All the other values remain set, including the hidden inputs. It also will not allow saving the affiliate saying the customer is already registered as an affiliate, as shown in the attached photo.

![image](https://user-images.githubusercontent.com/1266825/47922062-84d2df00-de8c-11e8-8636-bc7fdcf1bdb3.png)

**Comment by danielkerr** [comment]
Ok will test again

**Comment by danielkerr** [comment]
issue is not there since breaking up the affiliate into a different table.
