### ISSUE TITLE
Installing extension doesn't update php or twig files

### ISSUE THREAD

**Issue by djmassive** [opencart/opencart#6956]
**What version of OpenCart are you reporting this for?**
3.0.2

**Describe the bug**
Installing extension doesn't apply modifications from xml file (trying multiple extensions)

**Server / Test environment (please complete the following information):**
- PHP 7.1.x
- Linux / MacOS (local)
- Latest Apache - browser safari / chrome / Firefox.

**Additional context**
That was working before 3 version.

**Comment by osworx** [comment]
Sounds like: 'bought new tires for my old car - but they do not fit .. '

First of all; what you are describing is no bug - installed by myself various extensions (OCMods) on 3.0.2.0 and all are working perfectly.
Second: you should post which extensions you are trying to install.

And third (and finally): this is no forum, you have posted on the wrong site!
Try: https://forum.opencart.com/

**Comment by djmassive** [comment]
Those are extensions defined for 3.0.2 so I'm sorry, but this Is not "new tires for old car". Simple example of my install.xml:

<?xml version="1.0" encoding="utf-8"?>
<modification>
	<name>filename</name>
	<code>filename</code>
    <version>1.0</version>
    <author>Someone</author>
    <link>http://www.service_link.com</link>
    <file path="system/config/catalog.php">
        <operation>
            <search>
               <![CDATA[$_['session_engine']     = 'db';]]>
            </search>
            <add position="replace"><![CDATA[$_['session_engine']     = 'file';]]></add>
        </operation>
    </file>
</modification>

New files are copied, information in extensions / modifications stored - but no files modifications apply (must do this manually). Maybe problem Is in documentation.

**Comment by danielkerr** [comment]
is it only the config files can not change? have you tried any other files.
