### ISSUE TITLE
[Build# 9138 - 3.1.0.0_b] Framework classes not found ~ randomly happening

### ISSUE THREAD

**Issue by MrPlow254** [opencart/opencart#6957]
**What version of OpenCart are you reporting this for?**
[Build# 9138](https://github.com/opencart/opencart/tree/40ac4cdf0a75ab6a3b731fac7b142a3491ead27c) - 3.1.0.0_b

**Describe the bug**
On various pages on the admin portal the Language/Loader classes throw an error. It doesn't always throw the error. Sometimes if I hard refresh the page 3 times it goes away. The page loads and all elements as well. So I don't know what exactly causes the issue. Possible API related (e.g. admin/index.php?route=sale/order/edit)

It might be a synchronous loading of the framework file on ajax page loading. Something obviously to that effect.

**To Reproduce**
Unknown, only have noticed on the admin portal. Possibly only with API calls. Other classes have thrown an error but Languages is the main one to do so.

**Server / Test environment (please complete the following information):**
 - PHP version: 7.2.7

**Additional context**
<b>Error</b>: Class 'Language' not found in <b>C:\htdocs\upload\system\framework.php</b> on line <b>132</b>

<b>Error</b>: Class 'Loader' not found in <b>C:\xampp\htdocs\Intranet\Intranet\upload\system\framework.php</b> on line <b>78</b>

**Comment by danielkerr** [comment]
are u sure you not saving these files as they are being loaded. or your host can be under powered. its not api related. its at php loading level. its server issue.

**Comment by MrPlow254** [comment]
I'll try and keep track of when it happens. Files are not being saved unless its the automatic cache system saving a file to the storage folder. I am using my desktop as a dev server with an Intel i7-7700K @ 4.2GHz with 32 GB of RAM, and a SSD. I highly doubt its under powered. I have a linux server I can push a mirror to and see if that system is duplicating the issue.

If this is only me having this issue i'll try and figure out the root cause and post it back here.
