### ISSUE TITLE
[3.1.0.0_b] Affiliate - Commission added mail - from wrong store

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6958]
**Situation**
Customer is ordering in Store1 something
Open the order in the Admin click Affiliate - add commission
Affiliate get an email with the information

**Problem**
Affiliate get the email from default store and not from store1

**Comment by andrei-bogdan** [comment]
Hi,

In the affiliate email code, it gets the store name from the customer info:
`$store_info = $this->model_setting_store->getStore($customer_info['store_id']);`

So you either:
- don't have any store information on that specific customer
- the customer actually made the order in the default store, even if the commission is added on store1

Please check.

**Comment by pemaier** [comment]
@andrei-bogdan Hello. The customer (is also the affiliate in this order) is registered at store1 and has ordered in store1. The mail is send from the default store.

**Comment by straightlight** [comment]
It makes sense here. Affiliates are already divided by each stores whenever a customer decides to buy the goods. To rectify the issue, in your catalog/controller/mail/affiliate.php file,

find:

`$data['text_welcome'] = sprintf(`

Add above:

$store_name = $this->model_setting_setting->getSettingValue('config_name', $args['store_id']);
		
		if (!$store_name) {
			$store_name = $this->config->get('config_name');
		}
$store_name = $this->model_setting_setting->getSettingValue('config_name', $args['store_id']);
		
		if (!$store_name) {
			$store_name = $this->config->get('config_name');
		}

Then, after this block of codes, replace all instances of: 

`$this->config->get('config_name')`

with:

`$store_name`

**Comment by pemaier** [comment]
@straightlight Hello.
I tested your code and the Name is now correct ... but it needs to be extended with other information like e.g. the correct email.

**Comment by straightlight** [comment]
Add a duplicated as the above right below the modification then replace all instances of: 'config_name' with 'config_email' and 'store_name' with 'store_email' . This should resolved the issue.

**Comment by danielkerr** [comment]
fixed here

https://github.com/opencart/opencart/commit/3c17f113cdce4e9f58f2ef2a38c06bc41083ce6f
