### ISSUE TITLE
multiple stores share one cart

### ISSUE THREAD

**Issue by asjadshahab** [opencart/opencart#6963]
I have different stores i.e store1 and store2 when i add an item to cart from store 1 it will add but when i go to store2, it showing cart is empty. so i want that in each stores cart products will remain same.
![medical](https://user-images.githubusercontent.com/36469486/47220133-87cec980-d3ce-11e8-8db6-a81322107344.png)
![vitamins](https://user-images.githubusercontent.com/36469486/47220141-8c937d80-d3ce-11e8-96f5-ad05370849b0.png)

**Comment by MrPlow254** [comment]
Sounds like a unique case. I would have someone write a plugin for your site. I doubt many people would need/want to share carts between stores. (e.g. US based company, EU sister company independent from US)

**Comment by straightlight** [comment]
Topic is about a service request, not an issue from the core. Please post on the forum for those enquiries.

**Comment by pemaier** [comment]
1st **This is a request for the forum**. 
2nd Much to less system information if it would really be an issue.
3rd There is a setting already present in the default store settings.
![image](https://user-images.githubusercontent.com/10166095/47255214-ea2ed500-d475-11e8-81c9-50b879bd8219.png)

**Comment by straightlight** [comment]
`1st This is a request for the forum.`

Then, this service request should not be opened on Github but on the forum period.

**Comment by asjadshahab** [comment]
solved
