### ISSUE TITLE
Dropdown menu on action column, if you have just one record, you can not click on the items because this are hide behind the table

### ISSUE THREAD

**Issue by dharmawebstudio** [opencart/opencart#6965]
**What version of OpenCart are you reporting this for?**

3.1.0.0_b

**Describe the bug**

In the admin, in table-responsive div lists where there are a button with a dropdown, like the one in index.php?route=customer/customer. If you have just one record, when you click on dropdown menu in action column, you can not click on the items because this are hide behind the table. 

What section does it affect?

**To Reproduce**
1. Go to Customer Lists in Admin
2. With just one record on page, click on dropdown menu in action column

**Expected behavior**
All the elements in the dropdown menu should be accesible.

**Additional context**
I suppose this could be, in a strict sense, a bootstrap bug, and not an opencart bug.
¿Should be fixed in OpenCart?  Maybe could be fixing adding to table-responsive a css like: overflow: visible !important;  Other approaches could be used using javascript.

**Comment by danielkerr** [comment]
could it not have been fxed with z-index

**Comment by danielkerr** [comment]
its fixed already
