### ISSUE TITLE
[3.1.0.0_b] Why are we still using twig templates?

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#6967]
Why do we need Twig? They add no new improved functionality, quite to the contrary! See Daniels own notes on this in **system/library/template/twig.php**:

		/*
		 * FYI all the Twig lovers out there!
		 * The Twig syntax is good, but the implementation and the available methods is a joke!
		 *
		 * All the Symfony developer has done is create a garbage frame work putting 3rd party scripts into DI containers.
		 * The Twig syntax he ripped off from Jinja and Django templates then did a garbage implementation!
		 *
		 * The fact that this system cache is just compiling php into more php code instead of html is a disgrace!
		 */

Why not using PHP templates? OpenCart is a PHP framework, and PHP already IS a templating system anyway!

**Comment by stalker780** [comment]
+1. Twig is slow, less functional and have no benefits against PHP templates.

**Comment by TechGuru24** [comment]
Yes I also agree. We hope to get a good template system

**Comment by MrPlow254** [comment]
Didn't Opencart v2 use PHP templates?

**Comment by stalker780** [comment]
Yes it did. But we are talking about OC 3.1

**Comment by danielkerr** [comment]
any recommendations to have a twig compatibility re built system.

i'm sure i can rebuild the trig snytax in one class using regex.

**Comment by mhcwebdesign** [comment]
We have written various compilers and parsers in the past, it wouldn't be hard to write a TWIG parser which would directly translate into HTML, would still be better than the current TWIG implementation.

However, this doesn't answer my question why we would want TWIG in the first place when PHP can already do the job anyway!

**Comment by danielkerr** [comment]
Php likes to display a lot of errors when missing vars.

Also twig seems to becoming a standard.

**Comment by mhcwebdesign** [comment]
Even the Symfony framework still supports PHP templates. While it's true  that TWIG is less excessive with error messages it's gone to the other extreme: If you use a non-existing variable it gets silently ignored which isn't right.

I am not sure whether Twig is a standard, there are simply too many template engines out there, like Smarty, TWIG, PHP, Mustache, Jade etc. None of them offers significant enough advantages over the others.

**Comment by stalker780** [comment]
As for me it will be enough to allow use both template engines at the same time. It worked like this in first OC3 versions. Don't understand why it was removed.

Only several lines of code needed in system/engine/loader.php -> view()

Replace:
$template = new Template($this->registry->get('config')->get('template_engine'));

With:
if (is_file(DIR_TEMPLATE . $this->registry->get('config')->get('template_directory') . $route . '.tpl')) {
	$template = new Template('template');
} else {
	$template = new Template('twig');
}


This will make happy everybody.
Extension developers can use both engines, it will be twice easier to support OC2 and OC3 extensions at the same time.
Template developers also can decide what to use without converting admin and default template from twig.
Those who like twig and see benefits in it can still use it.

**Comment by stalker780** [comment]
@danielkerr 
>>>Php likes to display a lot of errors when missing vars.

I agree with mhcwebdesign. 
Is it bad when PHP show you your errors as warnings and notices?
Either way displaying errors recommended to be disabled for production PHP servers.

Switching to TWIG because of this looks like shooting mosquitoes with bazooka :)

**Comment by danielkerr** [comment]
lets get 3.1 released then we can start looking in to implementing a new twig implemtation.

**Comment by mhcwebdesign** [comment]
@stalker780: As regards supporting both PHP and TWIG templates: That's exactly what our little OC 3.0.2.0 extension does, see https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31589 , I am going to port it to OC 3.1 soon.

@danielkerr: As I said, writing up our own TWIG parser to translate directly into HTML isn't too hard, would make it a little bit faster, too.

**Comment by stalker780** [comment]
@mhcwebdesign 
I think any developer has own ocmod for tpl in OC3. But it requires more steps for customer to install it. Therefore it requires more support time

**Comment by danielkerr** [comment]
one advantage of twig is that it can be stored in the db. if you use php you have to use eval and then anyone with access to the template editor can hack the site.

**Comment by TechGuru24** [comment]
We didn't understand this buyer. If he shared valid access details ? Why we
will ask again. Its wasting both of all time by replying same answer.

On 30 Nov 2018 13:14, "Daniel Kerr" <notifications@github.com> wrote:

one advantage of twig is that it can be stored in the db. if you use php
you have to use eval and then anyone with access to the template editor can
hack the site.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/opencart/opencart/issues/6967#issuecomment-443119354>,
or mute the thread

**Comment by stalker780** [comment]
@danielkerr
>one advantage of twig is that it can be stored in the db. if you use php you have to use eval and then anyone with access to the template editor can hack the site.

BTW those inDB templates and OCMODs are awkward.
They need to be edited very often. 
But finding and working with them inside a DB is very uncomfortable.
You cannot use editor you prefer (no versioning), you need to check both FTP and DB.
There is no autoupdate (clean cache, refresh) when you change them.
As it was already reported here OCMODs cannot modify changed templates stored in DB.

All together these minor inconveniences make developing on OpenCart 3.x a pain, time consuming and buggy. 
And things don't get better with new versions, only worse. 
OC 3.0 - Minus PHP templates, TWIG cache, always need to refresh them.
Now in OC3.1 OCMODs cannot be stored in system folder anymore. Minus one useful feature everybody used :(
And these minuses happen in every version now.

I really wish to see OC becoming better, faster, more functional and developer friendly.

In my opinion it's best to store OCMODs and edited templates as files in system's subfolders next to modifications.

**Comment by mhcwebdesign** [comment]
As regards the ability to store templates in the DB (a bad idea in the first place!), it doesn't make any difference whether it's a Twig or a PHP template. The whole OC templating system is too messy now, especially when it comes to modifying templates. We got the design editor, OCmod (and VQmod), event handlers, and now lambda functions as of OC 3.1.x, for template modifications. 

Perhaps now is the time to fork OpenCart and create a community edition?

**Comment by danielkerr** [comment]
@stalker780 yes will add cache refresh.
