### ISSUE TITLE
[3.1.x.x] Does not working Edit button on Layout Page in admin.

### ISSUE THREAD

**Issue by harnishdesign** [opencart/opencart#6968]
Go to admin > Design > Layouts > Home....

I have try to Edit button in after Add module. It does working. but, When have Add module & Save Layout. then try to edit button. So, Edit button does not working for **Content Top** & **Column Left**. It does working fine for Column Right & Column Bottom.

![screenshote](https://user-images.githubusercontent.com/2634085/47502962-a3324c80-d886-11e8-8394-7315fd18f812.jpg)

I think, Should need to replace following code for **Content Top** & **Column Left**.

`<a href="" data-toggle="tooltip" title="{{ button_edit }}" class="btn btn-primary btn-sm"><i class="fas fa-pencil-alt fa-fw"></i></a>`

**Instead of**

`<button type="button" value="" data-toggle="tooltip" title="{{ button_edit }}" class="btn btn-primary btn-sm"><i class="fas fa-pencil-alt fa-fw"></i></button>`

**Comment by MrPlow254** [comment]
Yes it does not work currently.

**Comment by danielkerr** [comment]
its working now. i can not replicate.
