### ISSUE TITLE
Custom fields not included on New Account email sent to admin

### ISSUE THREAD

**Issue by bitlineweb** [opencart/opencart#6969]
When there are custom fields on registration email confirmation not including new added fields.
on admin email of new accounts

**Comment by vivek-webkul** [comment]
@bitlineweb - I didn't find any issue related to Custom Fields on Account location. Please share some kind of screenshot or Opencart version in which you are facing the issue.

**Comment by bitlineweb** [comment]
Thanks Vivek. 
Let me elaborate on the issue step by step.

1. I've created 2 custom fields under Customer > Custom Field (these 2 new fields now are displayed on registration page for new customers)

2. Under settings on admin, I've activated new registrations notifications...

3. When a new customer register, the email that goes to admin, does NOT include the customs fields added. (Custom fields should be included on that basic emails sent to admin) probably related to /catalog/view/theme/default/template/mail/register_alert.twig

So the issue is: There should be an option to enable the custom field's data to be included on register email alert.

Let me know if that makes sense.

**Comment by vivek-webkul** [comment]
@bitlineweb - I don't think that custom fields should consider in the email section. Currently, only default fields of Account location considered into the approve customer email.

**Comment by bitlineweb** [comment]
Let me give you a practical example why that feature is important.

In my store I have 2 kinds of customer groups: REGULAR(default) and WHOLESALE(requires approval)

Only customers that have received a special CODE number(wholesaler ID) we sent out are allowed to be WHOLESALE Customers, I have created a custom field for customers to fill in that number if WHOLESALE option is selected during registration.

When I receive a notification email of a new registration of WHOLESALE customer, I need to know that ID code to make sure it's a legit registration. but the custom field data isn't included on the email. I have to manually check the admin adding more steps to the process. 

that's why I believe custom fields should be included on admin email alert, or even better a function to activate that should be available for admin usage.

**Comment by danielkerr** [comment]
they are not supposed to be. if you require this feature you need to build it in. you can see the fields by going to the customers edit patge.
