### ISSUE TITLE
Add new catalog option select

### ISSUE THREAD

**Issue by Victor19Rodrigues** [opencart/opencart#6971]
When a add new option in select tag catalog, this modification doesn't appear in my site.

I already delete vqmod/vqcache directory and mods.cache file, thinking that could be cache, but didn't work. I'm using 1.5.5.1 version. 

Someone can help me?

**Comment by MrPlow254** [comment]
You need to provide way more details than you have. This also isn't a help forum. It is for reporting issues (bugs). Read thru the default text that is provided when you [create an issue provided here](https://github.com/opencart/opencart/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by Victor19Rodrigues** [comment]
I'm sorry, I think this isn't a bug.
