### ISSUE TITLE
Opencart Api Promotion Section not working.

### ISSUE THREAD

**Issue by vivek-webkul** [opencart/opencart#6973]
**What version of OpenCart are you reporting this for?**
Opecnart Version 3.1.0.0_b

**Describe the bug**
Opencart **api/promotion** api not working.

What section does it affect?
Due to this error **marketplace/extension** section is not working and showing **404 page not found error**

**To Reproduce**
1. Go to 'admin'
2. Click on 'Extensions->Extensions'
3. See error

**Screenshots / Screen recordings**
https://qsnapnet.com/snaps/chkfgssfu6z2gld

Due to loading **extension/extension/promotion** controller in extension/extension/* this error raised:

$data['promotion'] = $this->load->controller('extension/extension/promotion');

curl_setopt($curl, CURLOPT_URL, OPENCART_SERVER . 'index.php?route=api/promotion');

**Comment by vivek-webkul** [comment]
@MrPlow254 - I agree with you and you are right. That this will not affect to other data, But that should be in the working state.

**Comment by danielkerr** [comment]
yes will be fixed. it on the opencart.com side to fix. nearly finished with the next version so will fiox once released..

**Comment by danielkerr** [comment]
put a coming soon message there. it will display banners when ready.
