### ISSUE TITLE
[3.1.0.0_b] - product.twig font awesome update for compare icon

### ISSUE THREAD

**Issue by Rexa-Raven** [opencart/opencart#6974]
**What version of OpenCart are you reporting this for?**
[3.1.0.0_b] (last update on 10/23)
**Describe the bug**
Font Awesome Icon needs update for "compare" button on front-end product.twig page. 

**To Reproduce**
1. Go to: catalog/view/theme/default/template/product/product.twig
2. Line 127: 
`<button type="button" data-toggle="tooltip" class="btn btn-light" title="{{ button_compare }}" onclick="compare.add('{{ product_id }}');"><i class="fa fa-exchange"></i></button>`

**Expected behavior**
icon used for compare doesn't appear since it needs to be updated.

Solution:

Line needs to be changed to:
`<button type="button" data-toggle="tooltip" class="btn btn-light" title="{{ button_compare }}" onclick="compare.add('{{ product_id }}');"><i class="fas fa-exchange-alt"></i></i></button>`

**Comment by Webkul-Opencart-Team** [comment]
[#6982](https://github.com/opencart/opencart/pull/6982) issue has been resolved.
