### ISSUE TITLE
[3.1.0.0_b] Order edit permission

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6976]
**Situation**
Administration - A usergroup should be able to use order edit function.
Therefor it's required to give the usergroup the right access location/country.

**Problem**
a) Without the right to access location/country an error occur if the user edit an order.
b) If the user has the right access location/country the menu System/Localisation/Countries is visible. The menu should be hidden.

I guess there is a permission request which is not required.

**Comment by schiggi** [comment]
Those 2 ajax calls ([#1](https://github.com/opencart/opencart/blob/d2d57f7c2e6e1fa94c33b184f0904ba4269beaf2/upload/admin/view/template/sale/order_form.twig#L1618), [#2](https://github.com/opencart/opencart/blob/d2d57f7c2e6e1fa94c33b184f0904ba4269beaf2/upload/admin/view/template/sale/order_form.twig#L1802)) causing the error as they are calling a function within localisation/country.

This [specific function](https://github.com/opencart/opencart/blob/d2d57f7c2e6e1fa94c33b184f0904ba4269beaf2/upload/admin/controller/localisation/country.php#L412) is used in
- admin/view/template/localisation/geo_zone_form.twig
- admin/view/template/setting/setting.twig
- admin/view/template/setting/store_form.twig
- admin/view/template/customer/customer_form.twig

The permission part is handled here upload/admin/controller/startup/permission.php. Best would be either to put this function to the api calls from catalog or just reuse this [function from catalog](https://github.com/opencart/opencart/blob/d2d57f7c2e6e1fa94c33b184f0904ba4269beaf2/upload/catalog/controller/checkout/checkout.php#L93).

Btw. there is the same problem when you have no permission for the route customer/customer/customfield. But that kind of makes sense here as during an order you can edit the customer information.
