### ISSUE TITLE
Not showing the Date in the Secure Trading Web Service payment method admin side configuration

### ISSUE THREAD

**Issue by shivamverma196** [opencart/opencart#6978]
In the Extensions setting of Secure Trading Web Service payment method, it is not showing the date. And php tag is present in the twig file. 

![jkutqpyuqsymh5akwiocfq](https://user-images.githubusercontent.com/30104530/47644712-e812f780-db94-11e8-9fc6-f5dfff2e248d.png)

**Comment by shivamverma196** [comment]
#6977 Issue fixed. So please check.

**Comment by shivamverma196** [comment]
#6977 Issue fixed. So please check.

**Comment by straightlight** [comment]
For which OC version are you addressing this issue?

**Comment by shivamverma196** [comment]
Hello, this issue exist in the version 3.1.0.0_b.

**Comment by danielkerr** [comment]
removed from core. will have extension page on opencart.com soon.
