### ISSUE TITLE
Crash after changing time zone

### ISSUE THREAD

**Issue by peanutyost** [opencart/opencart#6996]
On version  3.1.0.0_b I ran into a problem when I changed the time zone. I saved the configuration and was automatically logged out and then if i tried to log back  it would reload the login page and show no errors.

**Comment by MrPlow254** [comment]
I got the same result. If you need to change it back you can in the SQL table "oc_setting" column "key" value "config_timezone" in the "value" column change it back to "UTC"

**Comment by MrPlow254** [comment]
It might be helpful to have a help tooltip popup next to the this setting informing people to match their PHP.ini file to prevent session times being out of sync.

**Comment by Rexa-Raven** [comment]
What will happen though if someone is running a multi-store with stores in different time zones? For example, in the US, we have quite a few time zones. Or if someone operates a US and a UK store.

**Comment by MrPlow254** [comment]
It’s based off of the time zone the server uses. It has nothing to do with customers website views. It’s all about behind the scenes correcting sql times with php times.

On Nov 2, 2018, at 7:57 PM, Rexa <notifications@github.com<mailto:notifications@github.com>> wrote:


What will happen though if someone is running a multi-store with stores in different time zones? For example, in the US, we have quite a few time zones. Or if someone operates a US and a UK store.

**Comment by danielkerr** [comment]
https://www.inmotionhosting.com/support/website/php/setting-the-timezone-for-php-in-the-phpini-file
