### ISSUE TITLE
clear error

### ISSUE THREAD

**Issue by meshopindia** [opencart/opencart#7000]
**What version of OpenCart are you reporting this for?**
3.0.2
**Describe the bug**
This page isn’t working meshoponlineshop.in is currently unable to handle this request.
HTTP ERROR 500
What section does it affect?
website display
**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/44253305/47967208-ed82ad00-e080-11e8-8f44-90af5184b939.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
please contact my support team using the contact us form.
