### ISSUE TITLE
how to clear on checkout error

### ISSUE THREAD

**Issue by meshopindia** [opencart/opencart#7001]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

OK

<b>Warning</b>: fwrite() expects parameter 1 to be resource, null given in <b>/home/g396jg5zswlj/public_html/system/library/log.php</b> on line <b>31</b><br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, null given in <b>/home/g396jg5zswlj/public_html/system/library/log.php</b> on line <b>31</b><br />
<b>Warning</b>: fwrite() expects parameter 1 to be resource, null given in <b>/home/g396jg5zswlj/public_html/system/library/log.php</b> on line <b>31</b><br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, null given in <b>/home/g396jg5zswlj/public_html/system/library/log.php</b> on line <b>31</b><br />
<b>Warning</b>: fwrite() expects parameter 1 to be resource, null given in <b>/home/g396jg5zswlj/public_html/system/library/log.php</b> on line <b>31</b><br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, null given in <b>/home/g396jg5zswlj/public_html/system/library/log.php</b> on line <b>31</b><br />
{"redirect":"http:\/\/www.meshop.in\/index.php?route=checkout\/success"}

![image](https://user-images.githubusercontent.com/44253305/47967586-d2b23780-e084-11e8-847c-ce250d814e3a.png)

**Comment by danielkerr** [comment]
non of your directories are writable.
