### ISSUE TITLE
opencart 3.0.2 - extension installer error- clear soltion

### ISSUE THREAD

**Issue by meshopindia** [opencart/opencart#7002]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

OK

<b>Warning</b>: move_uploaded_file(/home/g396jg5zswlj/storage1/upload/2xbvoC5UkK.tmp): failed to open stream: No such file or directory in <b>/home/g396jg5zswlj/public_html/admin/controller/marketplace/installer.php</b> on line <b>154</b><b>Warning</b>: move_uploaded_file(): Unable to move '/tmp/php2CAtcX' to '/home/g396jg5zswlj/storage1/upload/2xbvoC5UkK.tmp' in <b>/home/g396jg5zswlj/public_html/admin/controller/marketplace/installer.php</b> on line <b>154</b>{"error":"File could not be found!"}

![image](https://user-images.githubusercontent.com/44253305/47967636-96cba200-e085-11e8-80ee-51d403876f21.png)

**Comment by danielkerr** [comment]
ask in the forum. maybe your tmp directory is not writable.
