### ISSUE TITLE
Missing folder

### ISSUE THREAD

**Issue by ongyen8888** [opencart/opencart#7006]
Hi, there's a lot of errors showing in the console section and I noticed the application folder is missing.
![screen shot 2018-11-05 at 5 38 35 pm](https://user-images.githubusercontent.com/42989863/47990163-d0ea8180-e121-11e8-90a7-d707daa61f68.png)

**Comment by vivek-webkul** [comment]
Hi @ongyen8888 ,

This issue is related to opencart.com (promotion api) on which work is going on and will fix in next version.
#6973

**Comment by ongyen8888** [comment]
@vivek-webkul may I know which version of OpenCart 3 is actually the stable version? I download from opencart.com and it's also full of bugs, can't even use the login API. When I install extension with marketplace, I can't enable the extension even though the status field on the form is already showing enabled.

**Comment by vivek-webkul** [comment]
@ongyen8888 :- 
You can use opencart version 3.0.2.0 or the previous one. You can check this 3.1.0.0_b is a beta version which is currently under development phase and the Oc team is working on the raised issues for this version.
https://www.opencart.com/index.php?route=cms/download/history

**Comment by ongyen8888** [comment]
@vivek-webkul Version 3.0.2.0 is also buggy, I can't enable the extension after install even though the status field is showing enable in the form. I try to install Two Factor Authentication (SMS) and I got this issue, I install Logic Message SMS and I can't even find any place to enable. Login API is showing MySQL errors as well, it's very hard for developers to use your platform that's so buggy.

**Comment by danielkerr** [comment]
i need to fix it from the opencart.com side. i will fix as soon as i get the next release ready.
