### ISSUE TITLE
Date Format 

### ISSUE THREAD

**Issue by HaydarLeventSirin** [opencart/opencart#7007]
I and many people want to use date format dd-mm-yyyy. Unfortunately, the forums do not respond to this request. I want to have the possibility to select the date format in system settings as in Wordpress and many similar cms.

![date-format](https://user-images.githubusercontent.com/44774766/47999693-6a129b80-e114-11e8-8f02-3ee0093dec1c.jpg)

**Comment by MrPlow254** [comment]
I was thinking the same thing last week. I prefer the [ISO 8601 format of YYYY-MM-DD](https://en.wikipedia.org/wiki/ISO_8601). Which isn't used either.

**Comment by danielkerr** [comment]
what are u talking about?

the view is DD/MM/YYYY because this is localisation that cvan be set from language files.

 in the code and SQL its YYYY-MM-DD

**Comment by HaydarLeventSirin** [comment]
I know what we're talking about. I have been using Opencart since the 1.5.x version. I know it's made from the language file, but it's not. Would I write here if it was easy? Before writing here I wrote in the Turkish forum. When the problem is not solved, I have written to the Contact Us section of the Opencart website. When the competent person could not solve the problem, he referred us here. The relevant section of the language file is as follows:

// Locale
$ _ ['code'] = 'tr';
$ _ ['direction'] = 'ltr';
$ _ ['date_format_short'] = 'd / m / Y';
$ _ ['date_format_long'] = 'l dS F Y';
$ _ ['time_format'] = 'h: i: s A';
$ _ ['datetime_format'] = 'd / m / Y H: i: s';
$ _ ['decimal_point'] = ',';
$ _ ['thousand_point'] = '.';

As you can see, everything is correct, but the date format is not what I want.

**Comment by HaydarLeventSirin** [comment]
![date-format-1](https://user-images.githubusercontent.com/44774766/48010145-1614b080-e12e-11e8-8c38-0b0292295d56.jpg)
![date-format-2](https://user-images.githubusercontent.com/44774766/48010146-1614b080-e12e-11e8-86b7-affdbce0099b.jpg)
![date-format-3](https://user-images.githubusercontent.com/44774766/48010147-16ad4700-e12e-11e8-8e26-327e8fbe5182.jpg)
![date-format-4](https://user-images.githubusercontent.com/44774766/48010148-16ad4700-e12e-11e8-8679-e7c4c447751e.jpg)
![date-format-5](https://user-images.githubusercontent.com/44774766/48010149-16ad4700-e12e-11e8-9e78-2c559154d90d.jpg)

**Comment by danielkerr** [comment]
you can not change the date field as its used to go directly into the db.

its not worth changing.

**Comment by MrPlow254** [comment]
You pretty much clarified everything if you were referring to my comment. I never did any digging on how to change it just noticed the view date being the format you mentioned. I was only talking about the view dates. Nothing needs to be changed.
