### ISSUE TITLE
Cache control headers not set

### ISSUE THREAD

**Issue by ADDCreative** [opencart/opencart#7008]
Since version 3 uses its own session handling, session_start(), quite rightly, is not longer called. However, as session_start() was also responsible for setting the cache control headers, they are now no longer being set by default (apart from a few places such as captcha/basic and downloads).

The session.cache-limiter, which usually defaults to nocache, controls the headers. http://php.net/manual/en/session.configuration.php#ini.session.cache-limiter You can see the headers that used to be set by session_start() here. http://php.net/manual/en/function.session-cache-limiter.php

This is particularly problematic for Internet Explorer 11 (note: not Edge in emulation mode) which aggressively caches responses from ajax GET request. This can cause problems with adding to cart, checkout, payment selection, etc.

Some forum posts confirming the problem.
https://forum.opencart.com/viewtopic.php?f=201&t=207498#p737430
https://forum.opencart.com/viewtopic.php?f=202&t=207703

Could also be the cause of following issues.
https://github.com/opencart/opencart/issues/6771
https://github.com/opencart/opencart/issues/6600

**Comment by ADDCreative** [comment]
Following on from a [discussion on the forums](https://forum.opencart.com/viewtopic.php?f=202&t=207498&p=783947#p783930). Here is a simple example to recreate one of the problems this issue causes.

1. Goto https://demo.opencart.com/ in Google Chrome. Preferably in a clean session with nothing added to the cart.
2. Open the developer console (F12).
3. Goto the Network tab in the developer console and ensure "Disable cache" is not ticked, "Preserve log" in not ticked and only "Doc" is selected.
4. Click on the iPhone product to go to the product page.
5. Click add to cart. You should see the item add to the the cart at the top of the page.
6. Click the web browser's back button. You will find the cart now shows as empty. This can really confuse some customers.

If you now look in the developer tool Network at tab for demo.opencart.com, in the Size column you can see "(disk cache)". The means that Chrome use the last version from it's cache and did not request the page from the server that would of had the updated cart total.

Try this with version 2.3.0.2 or less and you won't see the issue. If you compare the response headers in the development tool, you will see the lack of cache control header in version 3, which are present in 2.3.0.2 and earlier.

This is just a simple example of the issue. There can be a lot [worse problems](https://forum.opencart.com/viewtopic.php?f=202&t=216840) if the web browser starts caching AJAX responses at checkout.

**Comment by ADDCreative** [comment]
The lack of cache control headers also creates an minor privacy issue if a customer or admin accesses their account on a shared device.

Best demonstrated with Firefox.
1. Goto https://demo.opencart.com/ in Firefox.
2. Login as a customer or admin.
3. Goto any pages with personal data or configuration data.
4. Logout.
5. Switch on Work Offline in the Web Developer menu in Firefox.
6. Go back and view pages in the browser history. The personal data or configuration data will be visible even though the user logged out.

**Comment by WebkulOpencart** [comment]
As the related issue is closed so closing the same as well.

**Comment by ADDCreative** [comment]
@WebkulOpencart Please reopen this issue the other issue was probably only closed for being a duplicate.

**Comment by danielkerr** [comment]
i think his has nothing to do with session headers. the sessions are not recreated clicking back and products are not added to the cart if you click back. its the pager is cached.

**Comment by chulcha** [comment]
example

```
	<file path="catalog/controller/startup/session.php">
        <operation>
            <search><![CDATA[setcookie($this->config->get('session_name')]]></search>
            <add position="before"><![CDATA[
$this->response->addHeader('Expires: Thu, 19 Nov 1981 08:52:00 GMT');
$this->response->addHeader('Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0');
$this->response->addHeader('Pragma: no-cache');
            ]]></add>
        </operation>
	</file>
	<file path="admin/controller/startup/startup.php">
        <operation>
            <search><![CDATA[index(]]></search>
            <add position="after"><![CDATA[
$this->response->addHeader('Expires: Thu, 19 Nov 1981 08:52:00 GMT');
$this->response->addHeader('Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0');
$this->response->addHeader('Pragma: no-cache');
            ]]></add>
        </operation>
	</file>

```

**Comment by danielkerr** [comment]
i have

**Comment by ADDCreative** [comment]
@danielkerr It might also be worth setting the Expires header to a past or zero date. I remember some posts of the forum where some web servers would override if the Expires header wasn't set in the PHP response.

**Comment by ADDCreative** [comment]
@WebkulOpencart This issue also affect and needs fixing in the 3.0.x.x_Maintenance

**Comment by ADDCreative** [comment]
@danielkerr This issue is still not fixed for the admin. https://github.com/opencart/opencart/issues/7008#issuecomment-632773490 is still possible.

**Comment by danielkerr** [comment]
its not an issue for the admin!

**Comment by ADDCreative** [comment]
Yes it is. First there the privacy issue, you only have to go the browser disk cache to see all the personal data or configuration data just their in plain text, because the browser wasn't told not to cache it. That's not in keeping with the principles of recent data protection regulations that say to appropriate measures in place to protect personal data.

Then there is the issue of somethings just not working as the should due to caching. Just using the browser back button a few time can lead to out of date data being displayed.

There is no control over what a browser can't cache and there is no knowing what browsers will try to cache in the future.

Here's one example that is repeatable.
1. Using OpenCart 3.0.3.7 and IE11 login to the admin
2. Go to Extensions -> Extensions -> Modules
3. Edit Banner 1
4. Change the status and save
5. Observe that the status in the module list is still showing the old status.
This is because the browser used the admin/index.php?route=extension/extension/module result from it's cache.

And that's all before getting into production server configurations and proxies that will assume everything can be cached, because there is no signal not to.
