### ISSUE TITLE
Admin passwords with certain symbols don't work

### ISSUE THREAD

**Issue by ADDCreative** [opencart/opencart#7009]
If an admin user sets a password (at install or later at user/user/add or edit) containing one or more of the following, & " < or >, the password will not match when next logging in.

This is because the password is passed through html_entity_decode at login.
https://github.com/opencart/opencart/blob/3.1.0.0_a1/upload/admin/controller/common/login.php#L88
But not on install, add or edit.
https://github.com/opencart/opencart/blob/3.1.0.0_a1/upload/install/controller/install/step_3.php#L11
https://github.com/opencart/opencart/blob/3.1.0.0_a1/upload/admin/controller/user/user.php#L23
https://github.com/opencart/opencart/blob/3.1.0.0_a1/upload/admin/controller/user/user.php#L55

The html_entity_decode at login should be removed. Alternatively it could be replaced with htmlspecialchars_decode and htmlspecialchars_decode added to install, add and edit above.

Affects versions 2.1 and greater.

**Comment by ADDCreative** [comment]
Just a note that database password in the same file as the last commit is using htmlspecialchars_decode (request class only does a htmlspecialchars anyway).
https://github.com/opencart/opencart/blob/3.1.0.0_a1/upload/install/model/install/install.php#L4

**Comment by photographer-mememe** [comment]
You will also want to add http_entity_decode to smtp_password, wherever it is retrieved before adding to $mail.
