### ISSUE TITLE
Extension enabled in settings form but extension page still showing disabled

### ISSUE THREAD

**Issue by ongyen8888** [opencart/opencart#7010]
Can anyone let me know what's this issue?
![screen shot 2018-11-07 at 4 04 42 pm](https://user-images.githubusercontent.com/42989863/48118361-04a2e400-e2a7-11e8-8c24-4bffc9a99a72.png)
![screen shot 2018-11-07 at 4 04 25 pm](https://user-images.githubusercontent.com/42989863/48118362-053b7a80-e2a7-11e8-8be4-e0d3fad5c8af.png)

**Comment by cartbinder** [comment]
You must contact the extension developer. Or hire an Opencart professional.
Also, such ticket needs to be created here:
https://forum.opencart.com/
