### ISSUE TITLE
[3.1.0.0_b] Checkout for Returning Customer login broken

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#7011]
**Situation**
Customer is going direct without login to the products and ordering a product. The he start the checkout process. He choosing a to checkout as returning customer. He enter his login data (User/Pass) and press Continue

**Problem**
An error message occur.
![image](https://user-images.githubusercontent.com/10166095/48131965-eb983400-e2a2-11e8-96b4-41f4273ab19a.png)

**Comment by danielkerr** [comment]
already fixed in previous commits.
