### ISSUE TITLE
Undefined variable `new_password_hashed` error

### ISSUE THREAD

**Issue by dunrix** [opencart/opencart#7012]
OpenCart current master branch, PHP 7.2.11

Registering  a new customer yields **PHP Notice:  Undefined variable: new_password_hashed in /path_to_opencart/system/library/cart/customer.php on line 60** error, when *signing-up during cart checkout process*.

Bug introduced by recent commit [more gdpr work](https://github.com/opencart/opencart/commit/bd92fb23a6fdfdc5cd1fb8a382cc2ade7fa0d7c7).

Affected [condition](https://github.com/opencart/opencart/blob/7363aa240caaa9865421ba0e3b115cf8a3ded55c/upload/system/library/cart/customer.php#L60) checks `$new_password_hashed` which may be undefined if previous [condition](https://github.com/opencart/opencart/blob/7363aa240caaa9865421ba0e3b115cf8a3ded55c/upload/system/library/cart/customer.php#L47) is false.

Simple fix - just replace test

`if ($new_password_hashed) {`

with more correct one

`if (isset($new_password_hashed)) {`

on above linked line.

**Comment by pemaier** [comment]
@vivek-webkul Please put issue #7011 and this together because it solves also the login problem.

**Comment by danielkerr** [comment]
has already been fixed.
