### ISSUE TITLE
Error on Opencart

### ISSUE THREAD

**Issue by boyboya** [opencart/opencart#7017]
![untitled](https://user-images.githubusercontent.com/44870174/48201845-e8ca3b80-e395-11e8-84bf-8d26ab703d66.png)

How can i solve it?

**Comment by osworx** [comment]
1. Start the MySQL-Server.
2. there is a missing variable 'mysql' in the translation, just a notice, but bad.

**Comment by boyboya** [comment]
> 1. Start the MySQL-Server.
> 2. there is a missing variable 'mysql' in the translation, just a notice, but bad.

i already start mySQL on XAMPP, and still get error.

**Comment by boyboya** [comment]
> 1. Start the MySQL-Server.
> 2. there is a missing variable 'mysql' in the translation, just a notice, but bad.

i already start mySQL on XAMPP, but still get error

**Comment by stalker780** [comment]
@boyboa

1. You have wrong connection settings
2. You have not installed MySQL correctly

Your problem is not related to OpenCart code development.
Use forum for support.

**Comment by boyboya** [comment]
how to install mySQL correctly? sorry, i'm newbie on this.

**Comment by stalker780** [comment]
Use https://forum.opencart.com/
