### ISSUE TITLE
Big issue in the core OCMOD -- 

### ISSUE THREAD

**Issue by FlorinMarina** [opencart/opencart#7019]
There is a bug in the core. 

I spent all day debugging this issue ... finally I solved ... but this cannot be done to the client server so is big Issue ... 

In the file system/startup.php

`function modification($filename) {}`

change the following line

`if (!defined('DIR_CATALOG')) {`

to 

`if (basename(DIR_APPLICATION) == ‘catalog’) {
`

**Comment by schiggi** [comment]
Which version and what is the problem?

Looking at https://github.com/opencart/opencart/blob/master/upload/system/startup.php#L50, you might have an issue in your core files.

**Comment by FlorinMarina** [comment]
I am sorry is:

`if (defined('DIR_CATALOG')) {

But is the same thing 

When you install the ocmod xml code ... is not working  ... I sent a support ticket with my code

**Comment by danielkerr** [comment]
DIR_CATALOG is set in the admin config. if not defined than not the admin

**Comment by FlorinMarina** [comment]
that's the problem ... I am admin ...
