### ISSUE TITLE
Problem with API and order edit

### ISSUE THREAD

**Issue by djmassive** [opencart/opencart#7022]
OpenCart 3.0.2

API doesn't working in admin when I edit order. I found that in file api/currency $this->session->data doesn't have api_id. When added before code manually: $this->session->data['api_id'] = '5'; where 5 is api_id added in api menu everything back to normal.
I've set session to files instead of db - because one of my modules needs that.

Edit: Adding to history doesn't work also.

**To Reproduce**
1. Edit order, and try to change something

**Server / Test environment (please complete the following information):**
 - Kei.pl shared hosting
 - Linux
 - PHP 7.1.x / 7.2.x

**Comment by straightlight** [comment]
For this OC version, please create a new topic / service request on the Opencart forum.

**Comment by straightlight** [comment]
Closing commit as per addressed note above.
