### ISSUE TITLE
Custom field validation with Regex doesn't seem to work (with value 0)

### ISSUE THREAD

**Issue by schiggi** [opencart/opencart#7023]
Looking at the REGEX validation (for example in [customer.php](https://github.com/opencart/opencart/blob/master/upload/admin/controller/customer/customer.php#L872)) for text custom fields on latest OC3.

1) Shouldn't it be 
`&& !filter_var($this->request->post['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP`

instead of

`&& filter_var($this->request->post['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP` ?

2) Furthermore, it doesn't really work for `0` values, e.g. a range of allowed numbers including 0 ( `/^(0|1|8|15|30|45|50|55|60|65|70|75|80|85|90)$/` ).

So if user types 0 in custom field with mentioned regex validation, filter_var returns will either `false` on no match or the values on match. So on 0 it will return 0 which transforms to false. Solution could be to wrap the whole filter_var function with `is_string(filter_var(...))`

**Comment by straightlight** [comment]
The assumptions on this post are correct except that is_string should not be used to replace filter_var in this case.

**Comment by schiggi** [comment]
It would not replace filter_var but be wrapped around filter_var to make sure, that 0 is not cast to false (as is_string would return true with any string or int value and false if false.) 

Another way would be to change to `&& false === filter_var(...)`

**Comment by danielkerr** [comment]
works as it should. 
try regex [^a-z] then enter 0

^ means must have character not digit.

**Comment by schiggi** [comment]
No, I mean this regex pattern `/[^0-9]/` - so only digits.

If you input 0, filter_var will return 0 and subsequently false, though it should be valid.

**Comment by danielkerr** [comment]
so just add !== false

**Comment by schiggi** [comment]
Yes, that would be also a solution. So you mean `filter_var(...) !== false`?

But in the mentioned case in [customer.php](https://github.com/opencart/opencart/blob/master/upload/admin/controller/customer/customer.php#L872), should it not be `=== false` as if there is no validation (values not found) then error msg? Or did the logic of custom field regex changed from OC2 to OC3?

**Comment by williams9438** [comment]
To accept only number just added this regular expression  /^[0-9]*$/ in custom field with text type will do

**Comment by straightlight** [comment]
Has this issue been resolved since the last solution provided above?

**Comment by williams9438** [comment]
Yes it has. I provided the solution and still currently using it for a client

**Comment by LukeMcLachlan** [comment]
I have added a custom field with the regex  /^[0-9]*$/ and regardless of what I enter validation is not working for me. I can add only numbers, only letters, a mixture and blank and whatever change I make it's saved.  I'm using the latest edit.php version on github. Any takers? Validation is working for the default fields.

**Comment by williams9438** [comment]
The above regex work for only number and it doesn't save if letters are there. Note you will be able to type anything bit it will throw an error on save and won't save.
Used with open cart version: 3.0.2

**Comment by LukeMcLachlan** [comment]
on the account edit page this is not the case, I can save letters and it is saved in the database. the strange thing is that on the account registration page the regex is honoured.  I'm currently looking into why this is the case but my site is largely unmodified.

**Comment by williams9438** [comment]
Ohh ok. That's wasn't where I used it then.
Well when I get a solution do post it for others with similar issues.
If you are a developer you can always look into the open cart core code and modify it with using ocmod.
Hopefully in the next update it will be solved if it's a core issue

**Comment by LukeMcLachlan** [comment]
I've been doing a little debugging and it seems that the line:

$custom_fields = $this->model_account_custom_field->getCustomFields('account', $this->config->get('config_customer_group_id'));

on controller/account/edit.php  is causing the problem because it's returning empty. I simply deleted 'account' and everything is working perfectly now. I'm not an experienced developer but is this a bug?

**Comment by williams9438** [comment]
Ok very good.
It's probably an error but I can't be sure as I looked into it yet.
But I would advise u to use ocmod to modify the code as its in the core and will be overridden when you update.

**Comment by straightlight** [comment]
> Ok very good.
> It's probably an error but I can't be sure as I looked into it yet.
> But I would advise u to use ocmod to modify the code as its in the core and will be overridden when you update.

We don't create OC solutons on Github. Github is about posting solutions for the master branch. If you want to post ocmod solutions, please post on the forum!

**Comment by williams9438** [comment]
I knw. I was only advising the @LukeMcLachlan to use ocmod to change the code instead of manually modifying the code.
