### ISSUE TITLE
Currency conversion bug

### ISSUE THREAD

**Issue by kuznikjan** [opencart/opencart#7024]
**What version of OpenCart are you reporting this for?**
Version 3.0.2.0

**Describe the bug**
When buying items in different currency than shops default, the order totals are not converted correctly.

**To Reproduce**
1. Set shop currency to dollars (default)
2. Go to store and select euro as currency
3. Buy new item (I bought the default iPhone item)
4. Numbers on final step don't match.

**Screenshots / Screen recordings**
http://prntscr.com/lgag75

**Server / Test environment (please complete the following information):**
 - Local development
 - Windows 10
 - PHP version: 5.2

**Additional context**
I left item and shipping prices as they were (101$ for iPhone and 5$ shipping)
As you can see order total doesn't match converted value of item total + shipping total. That is because currency->format() function rounds up, which causes  total unconverted price (106$) to convert into 83.17€, while converted iPhone (79.24€) and shipping (3.92€) sums into 83.16€ (not 83.17€ as its shown as total).

**Comment by danielkerr** [comment]
just a roundign issue
