### ISSUE TITLE
Opencart Multivendor Issues

### ISSUE THREAD

**Issue by amitmca** [opencart/opencart#7026]
We have downloaded the Opencart Multivendor from https://github.com/wjgvm/Multivendor but we are facing some issues 
1) Seller is unable to select the Category while adding a Product

2) Product Image added by Seller is not getting displayed in Store

3) Additional product images added by Seller are not getting displayed in Store

4) When seller updates Price and Quantity and admin approves it then it is not reflecting in store

5) When user does a transaction  from store then seller is not able to change the order status 

Request you kindly help me to resolve these issues.

**Comment by osworx** [comment]
Sorry; but:

> Hey there, Multi Vendor is neither an extension or module.
Multi Vendor is a simple stand alone Open source script that can be used for ecommerce purposes.

So, why you are asking here for support and not there??
