### ISSUE TITLE
Hardcoded value - missing translation

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#7036]
**What version of OpenCart are you reporting this for?**
current master (3.1.0.0_b)

There is still  hardcoded value:
https://github.com/opencart/opencart/blob/39aaf935443b8b9ba86cf1a7763b2bd6c0baf31a/upload/catalog/view/theme/default/template/information/gdpr.twig#L22

**Comment by danielkerr** [comment]
unfinished
