### ISSUE TITLE
Changes not reflecting after domain hosting change

### ISSUE THREAD

**Issue by ABHIRON** [opencart/opencart#7039]
i changed my hosting and domain of my opencart 
old domain hosting - https://artstreet.in/
new domain hosting - http://artstreet.sapsdigital.com/

changes are reflecting in backend admin when i am deleting and removing products but changes are not reflecting in front end and showing the old url products and pages 

i checked the cache folder as well but that is also blank 
can anyone please tell me what should i do in this case ?

**Comment by ADDCreative** [comment]
Ask in the forum. https://forum.opencart.com/
