### ISSUE TITLE
Session variable overwrite with ajax

### ISSUE THREAD

**Issue by TiagoDamascena** [opencart/opencart#7040]
**What version of OpenCart are you reporting this for?**
3.0.2.0

**Describe the bug**
I'm developing an Ionic app that uses Opencart as backend. When i make two simultaneous requests to modify different session variables one request overlaps the other and only one change is saved on session.

**To Reproduce**
1. Create two simple controllers that only modify different session variables using `$this->session->data['variable']`
2. Create a JavaScript that sends two requests, one below the other
3. Get current session values and compare with the sent data

**Expected behavior**
Both modifications are saved on the session

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Both
 - Operating system Windows 10 and CentOS
 - PHP version 5.6
 - Apache version 2.4.33 and 2.4.6
 - Browser(s) tested with Chrome
 - Version 70

**Additional context**
Seems to occur on database and file session

**Comment by danielkerr** [comment]
what bad way to report an issue!  you should point out the lines of code that cause this. i'm assuming checkout. this has already been fixed in the master under chained events.

**Comment by stalker780** [comment]
Are you sure you send two requests one after another? Or you send two ajax async requests simultaneously?

While one is not finished yet, another requests data from old session.

Use one request or use async:false for ajax call.

**Comment by TiagoDamascena** [comment]
I was sending two requests async ajax requests, one after another. I have already corrected my code sending one request after the response of the other. I'm just saying that this is not the expected behavior for a session driver, it can cause inconsistencies that are hard to debug and find the real cause.

But I already understand that this is not a very receptive community, I will not bother you with reports of your bugs.
