### ISSUE TITLE
Unable to upload the .webp images in the opencart

### ISSUE THREAD

**Issue by niteshpk** [opencart/opencart#7045]
**What version of OpenCart are you reporting this for?**
Version 3.0.2.0

**Describe the bug**
We should be able to upload the .webp images.

**What section does it affect?**
Image upload.

**To Reproduce**
1. Go admin panel
2. Click on 'Categories'
3. Edit any category
4. Try to upload the .webp image

**Expected behavior**
We should be able to upload the .webp images.

**Screenshots / Screen recordings**
![error](https://user-images.githubusercontent.com/25909806/48701403-6e5eae80-ec14-11e8-9add-ab485e3f337e.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? - dev/production both
 - Operating system - Windows 10
 - PHP version - 7.2.6
 - Apache version - Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6
 - Browser(s) tested with [e.g. chrome, safari - if applicable] - chrome
 - Version [e.g. 22] - Version 70.0.3538.102 (Official Build) (64-bit)

**Additional context**
Why webp should be supported? Read this.
https://developers.google.com/speed/webp/

**Comment by CallumAtCableIntelligence** [comment]
WebP is coming... Any updates on this?

**Comment by CallumAtCableIntelligence** [comment]
@niteshpk Maybe you can add .webp to the Allowed File Extensions in the opencart server settings under "Server"

**Comment by nitesh146** [comment]
@CallumAtCableIntelligence I tried that already. Seems still it is not accepting the webp files.

**Comment by osworx** [comment]
You have to adopt also the image class and filemanager controller.

**Comment by straightlight** [comment]
Closure notes: Since this commit is about supporting a file extension that OC does not originally support, please create a pull request about this. In addition, on the OC forum, I have also published solutions with another forum user as you can see here: https://forum.opencart.com/viewtopic.php?t=210243 .

This commit will now be closed.
