### ISSUE TITLE
[3.1.0.0_b] Page not found at language change - SEO problem

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#7047]
**Situation**
Product SEO keywords
![image](https://user-images.githubusercontent.com/10166095/48802016-f7faa300-ed1e-11e8-88ee-70d05cce25b7.png)

German link: .../demo/shop-310/ueber-uns?route=information/information&language=de-de
English link: .../demo/shop-310/en-gb/about-us

1 - I open the German page 'About us' 
2 - Change to the English language 
then I get an error.

The opposite way from English to German has the same result.

**Problem**
![image](https://user-images.githubusercontent.com/10166095/48802254-c0d8c180-ed1f-11e8-8c26-03c510d6fc49.png)

**Comment by danielkerr** [comment]
remove it from the seo regex page. or set a new seo keyword for which every language your using. should langage_id
