### ISSUE TITLE
Checkout not working due to Chaining ajax in IE 11

### ISSUE THREAD

**Issue by deepabhakuni** [opencart/opencart#7050]
I am unable to checkout in IE. The checkout divs do not open at all. Issue is with chain.attach i.e. the chaining ajax method being used for payment method required issue. I am using the latest version of opencart.

**Comment by straightlight** [comment]
Closure notes: Not enough details provided. No URLs posted.

Since this issue has not been updated for several months with limited information, this commit will now be closed.
