### ISSUE TITLE
Development proposal for store upgrade

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#7051]
controller/checkour/cart.php line 190 change to:

`if ($this->config->get('total_' . $result['code'] . '_status') && file_exists(DIR_APPLICATION . 'model/extension/total/' . $result['code'] . '.php')) {`

controller/checkout/payment_method.php line 32, change to:
`if ($this->config->get('total_' . $result['code'] . '_status') && file_exists(DIR_APPLICATION . 'model/extension/total/' . $result['code'] . '.php')) {`

controller/checkout/payment_method.php line 50, change to:
`if ($this->config->get('payment_' . $result['code'] . '_status')  && file_exists(DIR_APPLICATION . 'model/extension/payment/' . $result['code'] . '.php')) {`

controller/checkout/shipping_method.php line 15, change to::
`if ($this->config->get('shipping_' . $result['code'] . '_status')  && file_exists(DIR_APPLICATION . 'model/extension/shipping/' . $result['code'] . '.php')) {`

controller/common/cart.php line 33 change to:
`if ($this->config->get('total_' . $result['code'] . '_status') && file_exists(DIR_APPLICATION . 'model/extension/total/' . $result['code'] . '.php')) {`

These change reduces error messages, when old store upgrade and is forgotten removed 3 parties extensions.

**Comment by straightlight** [comment]
For which OC version are you suggesting to make those changes?

**Comment by pekka2** [comment]
What this is? I is not sent this issue.
