### ISSUE TITLE
OpenCartTest class dependencies

### ISSUE THREAD

**Issue by TiredFingers** [opencart/opencart#7054]
opencart version 3.0.2.0

The bug is in the tests. When I try to lunch any phpunit test, I have  require_once(D:/xampp/htdocs/opencart/upload/system/library/customer.php): failed to open stream: No such file or directory in D:\xampp\htdocs\opencart\upload\tests\vendor\beyondit\opencart-test-suite\src\OpenCartTest.php on line 47

**To Reproduce**
try to lunch php unit tests using readme in git cloned project

**Expected behavior**
usual phpunit test result

**Server / Test environment (please complete the following information):**
 - Local development
 - windows 10x64
 - PHP version 7.2
 - Apache version 2^
 - Browser(s) tested with  - yandex browser

**Comment by straightlight** [comment]
Closure notes: Since this issue is about an older OC version and there are no incident request updates about this issue on newer OC versions, including master branch, this commit will now be closed.
