### ISSUE TITLE
Installer is not working while creating tables on 3.1.0.0_b

### ISSUE THREAD

**Issue by aweher** [opencart/opencart#7056]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b
**Describe the bug**
Problem installing

Exception: Error: Duplicate column name 'status'
Error No: 1060
CREATE TABLE `gdpr` ( `gdpr_id` int(11) NOT NULL, `email` varchar(96) NOT NULL, `status` tinyint(1) NOT NULL, `status` tinyint(1) NOT NULL, `date_added` datetime NOT NULL, PRIMARY KEY (`gdpr_id`) ) ENGINE=MyISAM CHARSET=utf8 COLLATE=utf8_general_ci; in /system/library/db/mysqli.php on line 43

**To Reproduce**
Clone repo commit 5a058729b622d9f8088dbc95e7c7b8817a72b02a
Install

**Comment by pmhct** [comment]
Thank you. I am also have this problem - Duplicate column name 'status' !!!

**Comment by danielkerr** [comment]
fixed ages ago.
