### ISSUE TITLE
If Product is returned it shows weird ID. There are #%s characters in there.

### ISSUE THREAD

**Issue by Aqib-Webkul** [opencart/opencart#7062]
If Product is returned it shows weird ID. There are #%s characters in there.
![return_](https://user-images.githubusercontent.com/44609130/49282423-2a419880-f4b5-11e8-8532-e2b314fa6dd9.png)

**Comment by straightlight** [comment]
For which OC version are you addressing this issue about?

**Comment by WebkulOpencart** [comment]
issue resolved so closing the same.
