### ISSUE TITLE
GDPR Approval List error

### ISSUE THREAD

**Issue by pmhct** [opencart/opencart#7064]
OC version 
OC 3.1.0.0_b

**To Reproduce**
1. Go to 'Admin Page' > Customers
2. Click on 'GDPR'

**Expected behavior**
Exception: Error: Unknown column 'cg.customer_id' in 'on clause'
Error No: 1054
SELECT COUNT(*) AS total FROM `oc_gdpr` cg LEFT JOIN `oc_customer` c ON (cg.`customer_id` = c.`customer_id`) in \htdocs\abc\system\library\db\mysqli.php on line 43

**Comment by danielkerr** [comment]
unfinished
