### ISSUE TITLE
Duplicate variables in the en-gb language

### ISSUE THREAD

**Issue by pmhct** [opencart/opencart#7066]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Description**
`\catalog\language\en-gb\checkout\cart.php
$_['text_payment_cancel']      = 'until cancelled';
$_['text_payment_cancel']      = '%s every %d %s(s) until canceled';

\admin\language\en-gb\customer\gdpr.php
$_['column_status']         = 'Status';
$_['column_status']         = 'Status';

\admin\language\en-gb\extension\report\customer_order.php
$_['entry_status']          = 'Order Status';
$_['entry_status']          = 'Status';

\admin\language\en-gb\extension\report\marketing.php
$_['entry_status']     = 'Order Status';
$_['entry_status']     = 'Status';

\admin\language\en-gb\extension\report\product_purchased.php
$_['entry_status']     = 'Order Status';
$_['entry_status']     = 'Status';

\admin\language\en-gb\extension\report\sale_order.php
$_['entry_status']     = 'Order Status';
$_['entry_status']     = 'Status';

\admin\language\en-gb\extension\report\sale_return.php
$_['entry_status']     = 'Order Status';
$_['entry_status']     = 'Status';

\admin\language\en-gb\extension\report\sale_shipping.php
$_['entry_status']     = 'Order Status';
$_['entry_status']     = 'Status';

\admin\language\en-gb\extension\report\sale_tax.php
$_['entry_status']     = 'Order Status';
$_['entry_status']     = 'Status';

\admin\language\en-gb\setting\setting.php
$_['help_login_attempts']            = 'Maximum login attempts allowed before the account is locked for 1 hour. Customer and affliate accounts can be unlocked on the customer or affliate admin pages.';
$_['help_login_attempts']            = 'Maximum login attempts allowed before the account is locked for 1 hour. Customer and affiliate accounts can be unlocked on the customer or affiliate admin pages.';`

**Comment by vivek-webkul** [comment]
[Issue Fixed #7066 : Language related issues resolved.]
![reports 1](https://user-images.githubusercontent.com/28401696/49421063-5eb69c80-f7b4-11e8-96e6-3da24646c169.jpg)

**Comment by mycncart** [comment]
not resolved the following files:

\admin\language\en-gb\extension\report\sale_order.php
$['entry_status'] = 'Order Status';
$['entry_status'] = 'Status';

\admin\language\en-gb\extension\report\sale_return.php
$['entry_status'] = 'Order Status';
$['entry_status'] = 'Status';

\admin\language\en-gb\extension\report\sale_shipping.php
$['entry_status'] = 'Order Status';
$['entry_status'] = 'Status';

\admin\language\en-gb\extension\report\sale_tax.php
$['entry_status'] = 'Order Status';
$['entry_status'] = 'Status';

**Comment by danielkerr** [comment]
already fixed
