### ISSUE TITLE
Wrong word in language en-gb

### ISSUE THREAD

**Issue by pmhct** [opencart/opencart#7068]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Description**
At file : \catalog\language\en-gb\mail\gdpr_export.php
$_['text_greeting']  = 'A request to delete your account from <strong>%s</strong> has been received.';

must be: $_['text_greeting']  = 'A request to export your account from <strong>%s</strong> has been received.';

**Comment by vivek-webkul** [comment]
https://github.com/opencart/opencart/pull/7072/commits/826e2e2352156386ef310252e7401b16e3bf5fae

**Comment by danielkerr** [comment]
that file is no lojnger there. the gdpr system is finished and fully working.
