### ISSUE TITLE
Product Options - Missing column name

### ISSUE THREAD

**Issue by pmhct** [opencart/opencart#7069]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b
**Describe the bug**
https://abload.de/img/aawei1e.gif

**Comment by vivek-webkul** [comment]
#7004

**Comment by vivek-webkul** [comment]
https://github.com/opencart/opencart/pull/7004

**Comment by straightlight** [comment]
Closure notes: Removed duplicated post from vivek-webkul. Must of been posted by mistake. Since a solution has been provided, this commit will now be closed.
