### ISSUE TITLE
zone_id of guest.php

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#7071]
controller/checkout/guest.php line 201:

`if (!isset($this->request->post['zone_id']) || $this->request->post['zone_id'] == '' || !is_numeric($this->request->post['zone_id'])) {`

change to:
`if (empty($this->request->post['zone_id']) || !is_numeric($this->request->post['zone_id'])) {`

**Comment by ADDCreative** [comment]
What if ' --- None --- ' is selected which has a zone_id of 0?

**Comment by ADDCreative** [comment]
https://github.com/opencart/opencart/blob/3.1.0.0_a1/upload/catalog/view/theme/default/template/checkout/guest.twig#L600

```php
html += '<option value="0" selected="selected">{{ text_none }}</option>';
```

**Comment by pekka2** [comment]
Zone_id is required? :
```
if (!isset($this->request->post['zone_id']) || $this->request->post['zone_id'] == '' || !is_numeric($this->request->post['zone_id'])) {
				$json['error']['zone'] = $this->language->get('error_zone');
}
```
So this can use also function 'empty'

**Comment by ADDCreative** [comment]
zone_id is required but can be 0 (zero) for some countries. empty() on a 0 (zero) value will return true generating the error, even through 0 is a valid value for zone_id.

**Comment by pekka2** [comment]
Althougth change to empty function, this allow use '0' ? :
`|| !is_numeric($this->request->post['zone_id'])`

**Comment by ADDCreative** [comment]
zone_id needs to be a number. So 0, 1, 2, 3, ect.

```php
if (!isset($this->request->post['zone_id']) || !is_numeric($this->request->post['zone_id'])) {
```

would work (as '' is not numeric), but not what you suggested.

**Comment by pekka2** [comment]
Bump 🥇

**Comment by danielkerr** [comment]
very silly to change something from !== '' which is the same as null and then add is numeric. no need! it forces what ever input to integer in the SQL.
