### ISSUE TITLE
GDPR - Missing language after the customer confirm an email

### ISSUE THREAD

**Issue by pmhct** [opencart/opencart#7075]
**What version of OpenCart are you reporting this for?**
OC 3.1.0.0_b
**Describe the bug**
![2018-12-05_084254](https://user-images.githubusercontent.com/45484182/49484420-96cbe700-f869-11e8-931c-cd5b90238f84.png)

**Comment by straightlight** [comment]
From which route are you addressing this issue?

**Comment by danielkerr** [comment]
working fine.
