### ISSUE TITLE
[3.x.x] Admin/setting/store_form.twig help_url not compiling html code

### ISSUE THREAD

**Issue by MrPlow254** [opencart/opencart#7083]
**What version of OpenCart are you reporting this for?**
3.x.x

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Admin/System/Settings/General on a secondary store. The help text under Store URL does not compile html code it outputs html escape code which is not needed.

`<small class="form-text text-muted">Include the full URL to your store. Make sure to add '/' at the end. Example: http://www.yourdomain.com/path/&lt;br /&gt;&lt;br /&gt;Don't use directories to create a new store. You should always point another domain or sub domain to your hosting.</small>`

**Expected behavior**
`<small class="form-text text-muted">Include the full URL to your store. Make sure to add '/' at the end. Example: http://www.yourdomain.com/path/<br /><br />Don't use directories to create a new store. You should always point another domain or sub domain to your hosting.</small>`

**Additional context**

Line 44 on 'upload\admin\view\template\setting\store_form.twig'
`<small class="form-text text-muted">{{ help_url|escape('html') }}</small>`

Change to:
`<small class="form-text text-muted">{{ help_url }}</small>`

**Comment by danielkerr** [comment]
already added in master branch

**Comment by danielkerr** [comment]
ok i see
