### ISSUE TITLE
Customer Forgotten Password is broken

### ISSUE THREAD

**Issue by SamhoFG** [opencart/opencart#7102]
**What version of OpenCart are you reporting this for?**
3.0.2

**Describe the bug**
Customer Forgotten Password function is broken.  No password reset email will be sent to customer.

"forgotten.php"
	if (($this->request->server['REQUEST_METHOD'] == 'POST') && $this->validate()) {
		$this->model_account_customer->editCode($this->request->post['email'], token(40));

		$this->session->data['success'] = $this->language->get('text_success');

		$this->response->redirect($this->url->link('account/login', '', true));
	}

After inserted the reset code to the customer table and added the success message, there is no action to send reset email to customer.  It just redirect customer to login page.
I checked the code in forgotten.php and login.php, but I cannot find any code that is related to the "reset email".

**To Reproduce**
1. Go to 'Home' Page
2. Click on 'Login' button 
3. Click on 'Forgotten Password' button 
4. Input email of existing account
5. Click on 'Continue' button 
6. Check your 'email', but no reset email

**Expected behavior**
Receive reset email

**Server / Test environment (please complete the following information):**
 - Apache Web Server
 - Linux
 - PHP 7.0.32

**Additional context**
The reset email sending code was in OC 2.3, but it is gone in 3.0.  And I cannot find any replacement code.

**Comment by MrPlow254** [comment]
Did you set up your email server properly?

**Comment by ADDCreative** [comment]
The code for sending the mail is here.
https://github.com/opencart/opencart/blob/3.0.2.0/upload/catalog/controller/mail/forgotten.php

This is called by an event set here.
https://github.com/opencart/opencart/blob/3.0.2.0/upload/install/opencart.sql#L1363-L1364

**Comment by danielkerr** [comment]
its working for me.

**Comment by SamhoFG** [comment]
Thank you, ADDCreative.
My 'oc_event' table is missing some triggers.  Will try to fix it.
