### ISSUE TITLE
Access/Modify Permission - versions including beta/master

### ISSUE THREAD

**Issue by Rexa-Raven** [opencart/opencart#7103]
The issue is that modify and access permissions should be **realistic** for a store owner instead of relying on a site developer/support person to demystify it.  I have seen countless threads on the forums where people were asking about json errors coupled with permissions errors only to be ill-advised about how to "fix" them. And this namely pertained to those owners with sales people they set access/modifies for orders.

In all versions of OC including the beta/master, there is no way for a store admin or owner to realistically understand what access/modify permissions to set (without looking at the actual code) since some of them are so interdependent of each other. **So the issue specifically is that it's not possible to discern the interdependencies without looking at the code.**

For example, if you're a store owner, and you want to set up a group for sales people to do nothing but access and modify sales/orders, the natural inclination is to just allow access and modify permissions for sales/orders. However, when you have scripts on the respective twig files calling functions from controllers outside of sales/orders - such as calling the country function that resides in a localisation controller, the sales people group will then be riddled with json errors on the page. This is just an immediate example. The store owner may not understand what further permissions to set - it becomes a guess-work unless they understand to look at the actual code or template files to determine it themselves. In my example, you would further need to allow both access and modify permissions then for localisation/country. But why? Then the same group will have access to this other part of the admin section when there's no need for it. For things like this, I actually included the country function on the respective order controller and edited the twig template instead to point directly to order controller file. There are other things I had to modify in the code, but this is just a prime example.

With all this said, ways to tackle this problem - or at least try to make permissions more intuitive:

a) At least show the interdepencies on the permissions section so that you can't just select "one" without the "other".

b) Look at incorporating the functions needed on the respective controller files instead - even if they have to repeat from other controller files

c) Make the errors on actual pages more "friendly" so that it can be easy to read what permissions are still needed (instead of just spitting out a "permissions denied" error)

I personally chose to just contain all needed functions within the respective controller files themselves. It was just far easier and more intuitive for someone to pick and choose the necessary access/modify permissions accordingly.

**Comment by danielkerr** [comment]
its a pain to fix but will require some good thinking to solve the issue.

**Comment by danielkerr** [comment]
im closing this. its not a big deal. just make sure the right files have the right permissions. the only other way i could think of doing this is by folder.
