### ISSUE TITLE
Total handlig and download products

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#7110]
File catalog/model/extension/total/handling.php line 4:

`if (($this->cart->getSubTotal() > $this->config->get('total_handling_total')) && ($this->cart->getSubTotal() > 0)) {`

changed to:

`if (($this->cart->getSubTotal() > $this->config->get('total_handling_total')) && ($this->cart->getSubTotal() > 0) && ($this->cart->hasDownload() == false)) {`

**Comment by MrPlow254** [comment]
What if the cart has a download item and a shipable item?
