### ISSUE TITLE
BUG: IP of the reverse proxy displayed instead of the real client IP ?

### ISSUE THREAD

**Issue by mikygee** [opencart/opencart#7117]
Version: 3.0.2.0

Hello,
I use opencart behind a reverse proxy.
I properly receive the client' IP adresses in my logs since i have in my vhost
access_log /var/log/nginx/mysite.access.log xforwardedLog;
and in my global config
log_format  xforwardedLog   '$remote_addr forwarded for $http_x_real_ip - $remote_user [$time_local] ' '"$request" $status $body_bytes_sent ' '"$http_referer" "$http_user_agent"';

Here's what I have in my backend server logs
10.255.89.253 forwarded for MY/CLIENTPUBIP - - [29/Dec/2018:18:59:05 +0100] "GET /admin/index.php?route=localisation/country/country&user_token=dJ2WvKD7Tzi3JiOcIQcQ3sqPEhl23V6L&country_id=74 HTTP/1.0" 200 8198 "https://www.mysite.org/admin/index.php?route=setting/setting&user_token=dJ2WvXXXXzi3JiOcIQcXXsqXXhl23V6L" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"

But in Clients > Clients I just see the reverse proxy IP and not the clients IP which is MY/CLIENTPUBIP that you saw in the previous nginx log
![image](https://user-images.githubusercontent.com/2222550/50541200-dc49ae80-0ba0-11e9-9c76-5de21a60cbe3.png)

I'm don't know if there's something that can be done but if there's nothing that can be done it's a bug because the client's real IP adress is not displayed

**Comment by LJK-opencartmods** [comment]
It’s likely not a bug in opencart, you need to do configure your proxy to pass along the original Client IP with its request. 

I say likely, because I encountered something similar with Laravel in Docker while using a reverse proxy. Wasn’t Laravels fault.

**Comment by mikygee** [comment]
Hello,

Actually, I did what you said.

The proof is the backend nginx logs I posted in my first message.
10.255.89.253 forwarded for MY/CLIENTPUBIP - - [29/Dec/2018:18:59:05 +0100] "GET /admin/index.php?route=localisation/country/country&user_token=dJ2WvKD7Tzi3JiOcIQcQ3sqPEhl23V6L&country_id=74 HTTP/1.0" 200 8198 "https://www.mysite.org/admin/index.php?route=setting/setting&user_token=dJ2WvXXXXzi3JiOcIQcXXsqXXhl23V6L" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"

The real client IP is transported in x-forwarded-for
Opencart needs some sort of option to be able to activate x-forwarded-for $_SERVER["HTTP_X_FORWARDED_FOR"] because right now it relies only on $_SERVER["HTTP_CLIENT_IP"]

**Comment by mikygee** [comment]
I did a grep and found $_SERVER["HTTP_X_FORWARDED_FOR"] in
catalog/controller/api/order.php
catalog/controller/checkout/confirm.php
But it should be implemented else where

Maybe here for exemple
catalog/model/account/activity.php
, `ip` = '" . $this->db->escape($this->request->server['REMOTE_ADDR']

**Comment by RichusX** [comment]
I had the same issue with Opencart displaying the proxy IP instead of clients. I fixed it by adding these 3 lines to Nginx config (not the proxy, but the actual server):
```nginx
 set_real_ip_from 172.0.0.0/8;
 real_ip_header X-Real-IP;
 real_ip_recursive on;
```

In my case bost nginx instances are sitting inside Docker so the allowed address range `172.0.0.0/8` belongs to Docker.

**Comment by malandante** [comment]
> Version: 3.0.2.0
> 
> Hello,
> I use opencart behind a reverse proxy.
> I properly receive the client' IP adresses in my logs since i have in my vhost
> access_log /var/log/nginx/mysite.access.log xforwardedLog;
> and in my global config
> log_format xforwardedLog '$remote_addr forwarded for $http_x_real_ip - $remote_user [$time_local] ' '"$request" $status $body_bytes_sent ' '"$http_referer" "$http_user_agent"';
> 
> Here's what I have in my backend server logs
> 10.255.89.253 forwarded for MY/CLIENTPUBIP - - [29/Dec/2018:18:59:05 +0100] "GET /admin/index.php?route=localisation/country/country&user_token=dJ2WvKD7Tzi3JiOcIQcQ3sqPEhl23V6L&country_id=74 HTTP/1.0" 200 8198 "https://www.mysite.org/admin/index.php?route=setting/setting&user_token=dJ2WvXXXXzi3JiOcIQcXXsqXXhl23V6L" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
> 
> But in Clients > Clients I just see the reverse proxy IP and not the clients IP which is MY/CLIENTPUBIP that you saw in the previous nginx log
> ![image](https://user-images.githubusercontent.com/2222550/50541200-dc49ae80-0ba0-11e9-9c76-5de21a60cbe3.png)
> 
> I'm don't know if there's something that can be done but if there's nothing that can be done it's a bug because the client's real IP adress is not displayed

I've tried setting up opencart behind a reverse proxy for days, the site works ok from within the local area network but when accessing it from outside (using the reverse proxy) it displays just text and any link in the site includes the local IP. I have run out of ideas. Can you please share your nginx configuration? Thanks in advance!

**Comment by danielkerr** [comment]
u can replace the ip with the forward  ip in the system/startup file.
