### ISSUE TITLE
Required PHP version should be displayed as 7.0+ and not 5.6+ in install view

### ISSUE THREAD

**Issue by Kolpikov** [opencart/opencart#7120]
**What version of OpenCart are you reporting this for?**
v 3.X

**Describe the bug**
Opencart's installation view template shows incorrect minimum required version of PHP. Currently it shows that PHP 5.6+ required but in upload/system/startup.php:6 declared minimum version to be not less then 7.0.0.

**To Reproduce**
1. Start fresh installation of Opencart.
2. Go to Step 2
3. Check the required php version

**Expected behavior**
It should show minimum required version 7.0+

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/17802186/47986302-f3aa7500-e0e4-11e8-9b92-51d0cc117b25.png)

**Additional context**
My Pull Request with Fix:
https://github.com/opencart/opencart/pull/7005

**Comment by osworx** [comment]
It should be REQUIRED.
And of some noname or cheap hoster does not support php 7+ .. well who cares?

**Comment by Kolpikov** [comment]
> Well, good suggestion but not all worldwide hosting providers start even support php7.x. And please do not marge REQUIRED and RECOMMEND. OpenCart working well on 5.6.

You are mistaken. Please check the source code on master branch, line 6 in startup.php file:
https://github.com/opencart/opencart/blob/master/upload/system/startup.php#L6
```
if (version_compare(phpversion(), '7.0.0', '<')) {
	exit('PHP7+ Required');
}
```
So, Opencart Requires PHP 7.0+

**Comment by danielkerr** [comment]
I think hes talking about the 3.0.3.0 which is just a bug fix release. im re releasing. it had missing vendor files.

**Comment by Kolpikov** [comment]
I am closing this issue and related Pull Request because you have fixed this here:
https://github.com/opencart/opencart/issues/7281
