### ISSUE TITLE
Installation fails - two auto_increment fields are not allowed

### ISSUE THREAD

**Issue by spacecodeit** [opencart/opencart#7121]
This commit breaks the installer https://github.com/opencart/opencart/commit/0b29c946aed84bf0ceb5c74750fc59ff9e04e8c9

It is not allowed to have two fields with auto_increment in one mysql table.

Exception: Error: Incorrect table definition; there can be only one auto column and it must be defined as a key
Error No: 1075
CREATE TABLE `opcart__product` ( `product_id` int(11) NOT NULL AUTO_INCREMENT, `variant_id` int(11) NOT NULL AUTO_INCREMENT, `model` varchar(64) NOT NULL, `sku` varchar(64) NOT NULL, `upc` varchar(12) NOT NULL, `ean` varchar(14) NOT NULL, `jan` varchar(13) NOT NULL, `isbn` varchar(17) NOT NULL, `mpn` varchar(64) NOT NULL, `location` varchar(128) NOT NULL, `variant` text NOT NULL, `quantity` int(4) NOT NULL DEFAULT '0', `stock_status_id` int(11) NOT NULL, `image` varchar(255) NOT NULL, `manufacturer_id` int(11) NOT NULL, `shipping` tinyint(1) NOT NULL DEFAULT '1', `price` decimal(15,4) NOT NULL DEFAULT '0.0000', `points` int(8) NOT NULL DEFAULT '0', `tax_class_id` int(11) NOT NULL, `date_available` date NOT NULL DEFAULT '0000-00-00', `weight` decimal(15,8) NOT NULL DEFAULT '0.00000000', `weight_class_id` int(11) NOT NULL DEFAULT '0', `length` decimal(15,8) NOT NULL DEFAULT '0.00000000', `width` decimal(15,8) NOT NULL DEFAULT '0.00000000', `height` decimal(15,8) NOT NULL DEFAULT '0.00000000', `length_class_id` int(11) NOT NULL DEFAULT '0', `subtract` tinyint(1) NOT NULL DEFAULT '1', `minimum` int(11) NOT NULL DEFAULT '1', `sort_order` int(11) NOT NULL DEFAULT '0', `status` tinyint(1) NOT NULL DEFAULT '0', `viewed` int(5) NOT NULL DEFAULT '0', `date_added` datetime NOT NULL, `date_modified` datetime NOT NULL, PRIMARY KEY (`product_id`) ) ENGINE=MyISAM CHARSET=utf8 COLLATE=utf8_general_ci; in

**Comment by danielkerr** [comment]
shoudl be fixed in the latest commit
