### ISSUE TITLE
Group discount. 

### ISSUE THREAD

**Issue by Gorobez** [opencart/opencart#7124]
**3.0.2.0**

**Describe the bug**
Edit (add) order with discount.
While editing (adding) an order, the price of the product is set without a discount.
Buyer group is set at a discount.

Are these lines in the code unused?
in admin/controller/sale/order.php
525  'price'      => $product['price'],
526  'total'      => $product['total']

**To Reproduce**
1. Go to 'Edit order'
2. Click on 'Customer Group'  choose a group at a discount (example group  'users -10% discount')
3. Scroll down to 'next'
4. See - All products without discount

**Expected behavior**

**Server / Test environment (please complete the following information):**
 - Operating system linux nginx
 - PHP version 7.2

**Additional context**
in /sale/order/info
The price calculation is correct.
 'price' => $this->currency->format($product['price'] + ($this->config->get('config_tax') ? $product['tax'] : 0), $order_info['currency_code'], $order_info['currency_value']),
 'total' => $this->currency->format($product['total'] + ($this->config->get('config_tax') ? ($product['tax'] * $product['quantity']) : 0), $order_info['currency_code'], $order_info['currency_value']),

**Comment by danijelGombac** [comment]
#6855

**Comment by Gorobez** [comment]
Need to change the query in
/system/library/cart/cart.php getProducts ()
Depending on the group of the buyer, recalculate the order in the admin panel.

But the following happens:
> There are two user groups
> partner (customer_group_id = 5)
> retail (customer_group_id = 4)

When does the order "partner". The table of the session is recorded "retail customer_group_id = 4"

It doesn't matter how many user groups you have. Always the default group is recorded.
Does everyone have it?

**Comment by straightlight** [comment]
Has this issue also been reproduced over OC v3.0.3.2 and master branch?

**Comment by jeffreyeng-opencart** [comment]
I'm closing this issue since there are no response.
