### ISSUE TITLE
Missing product_id in advertise/google/addProduct

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#7125]
admin/controller/extension/advertise/google.php
need
    public function addProduct(&$route, &$args, &$output) {
        $this->load->model('extension/advertise/google');
        $this->load->model('catalog/product');
        foreach ($this->model_catalog_product->getProductStores($output) as $store_id) {
            $this->model_extension_advertise_google->insertNewProducts(array($output), $store_id);
        }
    }

    public function copyProduct(&$route, &$args, &$output) {
        $this->load->model('extension/advertise/google');
        $this->load->model('catalog/product');

        $final_product_id = $this->model_extension_advertise_google->getFinalProductId();

        if (!empty($final_product_id)) {
            foreach ($this->model_catalog_product->getProductStores($output) as $store_id) {
                $this->model_extension_advertise_google->insertNewProducts(array($final_product_id), $store_id);
            }
        }
    }

**Comment by danielkerr** [comment]
checking this now

**Comment by simo-vt** [comment]
Isn't this already fixed here?

https://github.com/opencart/opencart/pull/7123/files

If I am missing something, please elaborate more on the issue.

**Comment by straightlight** [comment]
Closure notes: Solution provided on the above as being addressed as already fixed issue. This commit will now be closed.
