### ISSUE TITLE
Wrong version detection in opencart 3.0.3.0

### ISSUE THREAD

**Issue by jameswill** [opencart/opencart#7127]
Hi,

I tried installing Opencart 3.0.3.0 on one of my test server with PHP 5.4 and MySQL 5.5.

I have successfully installed Opencart 3.0.3.0 version and when I logged in into admin panel it show version as 3.0.3.1_rc1 on the bottom of the page.

![ocart3030](https://user-images.githubusercontent.com/6368036/50752624-e7719e00-1274-11e9-9cc4-8c0d5439d9e6.png)

Can anyone clear here which is the correct version ?

**Comment by danielkerr** [comment]
***t!

**Comment by danielkerr** [comment]
ok please download again from the opencart.com download page. i have updated the version number.
