### ISSUE TITLE
[3.0.3.1] Unnecessary variable (%s) in customer account (wishlist)-Not fixed

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7130]
Still show ugly **Wishlist (%s)** in Customers account.

https://github.com/opencart/opencart/issues/6721

**Comment by danielkerr** [comment]
its fixed in the master branch

**Comment by danielkerr** [comment]
also this looks like a language file issue.

**Comment by condor2** [comment]
Yes, I know.

But why relased 3.0.3.1 as "bugs fixed 3.0.2.0" ?

**Comment by danielkerr** [comment]
it does not have all bug fixes but enough to make the system still compatible with the last version.

**Comment by condor2** [comment]
Then on Released notes should write something like this.

"Not all bugs was fixed"
"May contain bugs"

That people know if made upgrade to 3.0.3.1 or keep 3.0.2.0 :)

**Comment by stanislavdavid** [comment]
looks like duplicate of #6068
