### ISSUE TITLE
configurate Installation ‘journal3.ocmod.xlm’ 

### ISSUE THREAD

**Issue by spring7777** [opencart/opencart#7131]
Hello everyone,
I bought Journal3 theme. Its author said that it can only be uploaded through the root directory. But I prefer upload extensions via ‘Extension installer’, because I think it is easy to manage the extensions.

I found that the theme folder has a ‘journal3.ocmod.xlm’ file. I renamed it to’ install.ocmod.xlm’, and renamed ‘zip’ file to’ ocmod.zip’, uploaded it successfully,  refreshed it. But I can’t find it in Extensions List.

[journal3.ocmod.zip](https://github.com/opencart/opencart/files/2733281/journal3.ocmod.zip)

**Comment by spring7777** [comment]
I don’t know why. Could someone do me favor?
Many thanks.

**Comment by MrPlow254** [comment]
Contact Journal3 theme. That is a third party addon. This isn't a help forum.

**Comment by schiggi** [comment]
Probably it should be install.xml instead of install.ocmod.xml. But yes, contact the forum or the developer. This is not the place for getting help.

**Comment by condor2** [comment]
Wrong

on 2.3.0.2 you can install using **something.ocmod.xml**
on 3.0.2.0 first you need to have **install.xml**. Then you need to archive zip that install.xml to become **something.ocmod.zip**

**Comment by spring7777** [comment]
Thanks for your reply.

I renamed  ‘journal3.ocmod.xlm’ to ’ install.xlm’. It can be uploaded successfully.
But  it still can’t appear on Extension List.

Could you help me check it or make a install.xlm file? I will pay you service fee by PayPal.
    The ocmod.xlm file is attached.

Many thanks!

________________________________

**Comment by spring7777** [comment]
sorry
