### ISSUE TITLE
Fatal Error when accessing customer recent activity in opencart 2.2.0.0

### ISSUE THREAD

**Issue by nikhilcgnr** [opencart/opencart#7141]
i am getting "Fatal error: Class 'Controllercustomercustomer' not found in /home4/new/public_html/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php on line 42" when accessing customer details in admin panel. i am using opencart 2.2.0.0 with journal theme.

**Comment by osworx** [comment]
For such errors use the forum: https://forum.opencart.com/ only and/or the support of the theme developer!
