### ISSUE TITLE
Re-ordering of dashboard main menu, Marketing missing icon

### ISSUE THREAD

**Issue by MalikKrak** [opencart/opencart#7147]
Dear Mr. Kerr

A)
is it possible to re-order main menu in backend to have most used items at top, I suggest this:
1. Sales
2. Catalog
3. Customers
4. Marketing
5. Desing
6. Extensions
7. System
bcs Extensions at 2nd place is pointless, we do not use Extensions that much

B)
at v3.0.3.1 "Marketing" from this main menu has no icon

thank You

**Comment by mhcwebdesign** [comment]
![screenshot_2019-01-13_20-45-26](https://user-images.githubusercontent.com/2989557/51090467-443cef00-1774-11e9-989e-8cec06761577.png)

**Comment by MrPlow254** [comment]
@MalikKrak try refreshing your extensions if you ever did an upgrade to opencart, and on the developer settings button on the dashboard refresh the SASS and theme.

**Comment by MalikKrak** [comment]
Please let's focus on the "A" of my suggestion, re-ordering of menu in Admin's dashboard to faster and effective usage, thank You.

**Comment by osworx** [comment]
@MalikKrak When you need it that urgent, why not reordering it by yourself?
Can be easy done via a simple OCMod.

**Comment by jeffreyeng-opencart** [comment]
@MalikKrak: Have you resolve your issue?
