### ISSUE TITLE
Product variants not working after fresh install

### ISSUE THREAD

**Issue by grapsol** [opencart/opencart#7148]
Opencart version is 3.1.0.0_b

Description of the bug
After installing on both windows and linux, we suspect that there is some table or tables missing. Anyway, product_variant table has NOT been created.
If you try to edit a product, the product name in the detail page is missing. Also there are no option linked to the product.

How to reproduce
1. Install from opencart site, either for windows or for linux
2. Go to catalog>product
3. Edit apple 30" monitor: you will see NO productname in detailscreen and NO product options

Expected behaviour
We would assume that the productname could be edited and that the linked product options would be visible

![01overview](https://user-images.githubusercontent.com/46671159/51104140-8b16fd00-17e5-11e9-844f-4d8fd425937f.gif)
![02detailpage](https://user-images.githubusercontent.com/46671159/51104142-8b16fd00-17e5-11e9-8ecb-be6a4daf988c.gif)
![03optionsempty](https://user-images.githubusercontent.com/46671159/51104143-8baf9380-17e5-11e9-944a-0970a0979d84.gif)
![04tablesshortwheninstallingwithwindows](https://user-images.githubusercontent.com/46671159/51104145-8baf9380-17e5-11e9-9152-e7c065924ccf.gif)

**Comment by MrPlow254** [comment]
I'm getting this as well. Its because partial code has been uploaded to the git vs complete.

**Comment by danielkerr** [comment]
should be fixed now.
