### ISSUE TITLE
OC 3.1.0.0_b Twig doesn't accept changes from view/*/before events

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#7149]
After turning off caching for Theme and SASS in the admin Developer Settings the Twig rendering ignores all changes from lambda functions set by view/*/before events, including changes from the theme editor. In particular, all catalog/view/*/before handlers of priority 500 or higher ('event/theme' and others with template modifications) are ignored.

Is there any reason why this thing has to be so messy? Is there any reason why we can't use the Twig_Loader_Array instead of Twig_Loader_Filesystem? There are more bugs which I will report separately tomorrow.

**Comment by danielkerr** [comment]
you have to attach the twig filter.

**Comment by mhcwebdesign** [comment]
I did, using $template->addFilter(...) calls. And it works fine as long as caching is turned on in the admin Developer Settings for Theme and SASS. But it fails when caching is switched off.

**Comment by mhcwebdesign** [comment]
Daniel, it's late at night here in the UK. But I'll post a working solution for this Twig issue, as well as for the other ones I posted about Twig (see @7152 and @7151), tomorrow morning.

**Comment by mhcwebdesign** [comment]
I got a working solution for twig, still doing some more testing before posting it here.

**Comment by danielkerr** [comment]
fixed here
https://github.com/opencart/opencart/pull/7153
