### ISSUE TITLE
admin\view\template\catalog\product_form.twig two line codes miss ';

### ISSUE THREAD

**Issue by CiaoPlus** [opencart/opencart#7157]
miss ';
line: 1432
`html += '      	  </select>`

line: 1452
`html += '      	  <input type="text" name="product_option[' + option_row + '][product_option_value][' + option_value_row + '][price]" value="" placeholder="{{ entry_price }}" class="form-control"/>
`

**Comment by danielkerr** [comment]
is this on the master branch?

**Comment by CiaoPlus** [comment]
It has been fixed a few days ago.
