### ISSUE TITLE
OpenCart 3.0.x.x_Maintenance branch - missing dependencies

### ISSUE THREAD

**Issue by JedMeister** [opencart/opencart#7158]
As of commit ID `3a10b04` - current `HEAD` of the `3.0.x.x_Maintenance` branch - it appears that many (most?) of the dependencies (in `upload/system/storage/vendor`) are missing from OpenCart?!

----
### Background

I installed from `HEAD` of `3.0.x.x_Maintenance` sometime in early/mid December (possibly commit `85ffef8`? But can't be sure sorry) and all appeared to be fine.

But a new clean install today renders OpenCart not working (returns blank page).

The error reported in the Apache logs is:
```
PHP Fatal error:  require(): Failed opening required '/var/www/opencart-storage/vendor/composer/../react/promise/src/functions_include.php' (include_path='.:/usr/share/php') in /var/www/opencart-storage/vendor/composer/autoload_real.php on line 66
```

`/var/www/opencart-storage/vendor/composer/../react/promise/` (i.e. `/var/www/opencart-storage/vendor/react/promise/`) exists, but is an empty directory! On further investigation, it appears that a number of the other vendor sub-directories are empty too.

I tried having a look through the commits since early Dec but could not really work out what has happened. FWIW I'm a complete PHP novice and not at all familiar with composer and/or git submodules.

Perhaps I am doing something wrong (in which case, please let me know). Although I have discovered a workaround which appears to resolve the issue:

### Workaround:
```
SRC_DIR=/var/www/opencart-repo
WEBROOT=/var/www/opencart
git clone --branch 3.0.x.x_Maintenance https://github.com/opencart/opencart.git $SRC_DIR
cp -R $SRC_DIR/upload $WEBROOT
rm -r $SRC_DIR/upload/system/storage/vendor
cd $SRC_DIR
composer install
cp -R $SRC_DIR/upload/system/storage/vendor/* $WEBROOT/system/storage/vendor/
```

**Comment by danielkerr** [comment]
Releases including the missing remote dependency are here:

https://github.com/opencart/opencart/releases

**Comment by JedMeister** [comment]
Ah ok. Thanks. Sorry I missed those. I was just a bit thrown because it was working via a clone about a month ago, but not now. I'll use the releases from here on in. Cheers.

**Comment by danielkerr** [comment]
dont download the source code version unless you know how to use composer.

**Comment by Kaik** [comment]
Hi, guys I really do not understand why you are including dependencies in vendor?
tag 3.0.2.0 works the way it should -> git clone -> checkout tag -> composer install nice and clean
but tag 3.0.3.1 I had to purge vendors first because it includes some but not all of them (react), and then install them again?
