### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by umutalparslan** [opencart/opencart#7159]
**What version of OpenCart are you reporting this for?**
3.0.3.1_rc

Hello,

https://www.youtube.com/watch?v=zrGK71ujEFk
It's like in this video. I can't upload an image.

I looked at many forums and Stackoverflow but couldn't find a solution.

**Comment by danielkerr** [comment]
dont use the rc version. there is a full release out already.

https://github.com/opencart/opencart/releases
