### ISSUE TITLE
OC 3.0.3.1 Softaculous Upgrade (Registration Error) & Fresh Install Inconsistancies

### ISSUE THREAD

**Issue by gallnomad** [opencart/opencart#7162]
**What version of OpenCart are you reporting this for?**
This is regarding a clean install of OC 3.0.3.1 from Softaculous and an upgrade from 3.0.2.0 to 3.0.3.1 in Softaculous.

**Describe the bug**
When upgrading from 3.0.2.0 to 3.0.3.1 in Softaculous the extensions now shows Advertising as a module. When doing a clean install of 3.0.3.1 in Softaculous this module does not appear, you can see in both of the screen captures attached.

The second issue which also seems to be related to an upgrade from 3.0.2.0 to 3.0.3.1 in softaculous is that there is a strange entry in the extensions list heading_title (0) this does not appear in the fresh install of 3.0.3.1 in Softaculous. Also on the upgraded version when google capture is used the registration screen goes to a 500 error, it does register the account but does not return to the correct screen. This does not happen on the clean installs, only on the upgrade.

What section does it affect?

**To Reproduce**
Doing a fresh install of OC 3.0.3.1
Doing an upgrade of 3.0.2.0 to 3.0.3.1

**Expected behavior**
I am not sure what is to be expected I assume that I am supposed to see the Advertising Module on the clean installs which is not showing. I also assume that I am not supposed to see heaing_title (0) on the upgrade and expect that the registration on the upgrade using captcha should not go to a 500 error.

**Screenshots / Screen recordings**
Clean install 3.0.3.1
![install soft to new version](https://user-images.githubusercontent.com/47094628/51812425-08f9fe80-22e4-11e9-805d-4873032feea0.png)

Upgrade from 3.0.2.0 to 3.0.3.1
![oc upgrade](https://user-images.githubusercontent.com/47094628/51812426-0c8d8580-22e4-11e9-867f-ad414a1eff60.png)

**Server / Test environment (please complete the following information):**
All websites and servers are running the same version so I don't think it is an issue there or the problem would be happening on all sites.

 - Web Server
 - Centos 7
 - PHP version 7.2.7
 - Apache version Easy Apache 4
 - Browser(s) tested with chrome
 - Version current

**Additional context**
I would like to know which is the correct the clean install or the upgrade because I am in the middle of rebuilding 10 sites and don't want to have issues going forward. At the end of the day, I am fine to install OC 3.0.3.1 from scratch on the site having issues but it concerns me that the clean install does not have the advertising module and wonder if there is an issue with the install files on softaculous.

**Comment by danielkerr** [comment]
Just ignore the heading_title. the missing text is promotion category. Not sure what happened. I think it got renamed.

the advertising category is a new extension category. will fix but its not going to cause you any issues.

**Comment by danielkerr** [comment]
ok just checked. promotion should just be ignored. i put some code in so it wont show.

**Comment by gallnomad** [comment]
OK that's great I was worried I might have issues down the road with upgrades. thanks for your reply.
