### ISSUE TITLE
[v.3.1.0.0a] - catalog/view/theme/default/template/mail/order_add.twig file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7168]
In the IF download portion, the ENDIF has a '<' in front of the % endif %

**Comment by jktoole** [comment]
This is also in 3.0.3.1: catalog/view/theme/default/template/mail/order_add.twig - line 17.

**Comment by danielkerr** [comment]
can not find it.

**Comment by jktoole** [comment]
Sorry, it only just occurred to me that you can link to lines in a file on github - I should've done that in the first place. It might even have helped me get the line number right :)

Here it is:
https://github.com/opencart/opencart/blob/master/upload/catalog/view/theme/default/template/mail/order_add.twig#L22

**Comment by danielkerr** [comment]
Cheers
