### ISSUE TITLE
OC 3.0.x and 3.1.x:  PayPal Express button - missing or non-matching zones

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#7170]
There is a problem with the address zone mapping.

E.g. for UK customers OpenCart expects the selection of a county, whereas in PayPal this is optional, and even if the user chooses a county on the Paypal page, it may not have an exact match in OpenCart.

The same problem may exist for other countries.

In general, the mapping between PayPal's 'PAYMENTREQUEST_0_SHIPTOSTATE' and OpenCart's zone name (e.g. county, French departement, German Bundesland, etc) might not be always correct. There could be mis-matches, or PayPal's 'PAYMENTREQUEST_0_SHIPTOSTATE' may not have been selected at all.

Has anybody implemented a fix for this issue? Without a fix, the PayPal Express button is pretty useless!

**Comment by straightlight** [comment]
See this topic for the patched solution: https://forum.opencart.com/viewtopic.php?f=201&t=210578&p=750082#p749487 .

**Comment by straightlight** [comment]
Resolution confirmation: https://forum.opencart.com/viewtopic.php?f=201&t=210578&start=40#p750773 since the patch released.
