### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by marcelloinfoweb** [opencart/opencart#7172]
Wiki "Extension Building Tutorial Part 1" is discontinued, has it been continued elsewhere?

**Comment by danielkerr** [comment]
i have some one writing documentation for opencart. Maybe started 2 weeks ago. Not sure how long it will be before finished but im paying for it.

**Comment by marcelloinfoweb** [comment]
> i have some one writing documentation for opencart. Maybe started 2 weeks ago. Not sure how long it will be before finished but im paying for it.

Will it be available for free?

**Comment by danielkerr** [comment]
Yes of course

**Comment by marcelloinfoweb** [comment]
Do you have any material to create a module with CRUD?
I'm trying to make a dropshipping module that saves and fetches the data from a non-default OC table, but I'm totally unsure how to do this CRUD.
I already created the menu in admin, which calls a route that opens a page, now I am lost to make the form save in the table I created and then can use it in the store, specifically on the product page.

I will be very grateful if you can help me with any relevant material, thank you.

**Comment by LJK-opencartmods** [comment]
The database isn’t abstracted away the way you’re expecting. Review the code in almost any other controller/model pair to see how the pieces fit together, and expect to write SQL for your module.

**Comment by marcelloinfoweb** [comment]
> The database isn’t abstracted away the way you’re expecting. Review the code in almost any other controller/model pair to see how the pieces fit together, and expect to write SQL for your module.
> […](#)
> Sent from my iPhone
> On Feb 20, 2019, at 6:40 AM, Marcello Infoweb ***@***.***> wrote: Do you have any material to create a module with CRUD? I'm trying to make a dropshipping module that saves and fetches the data from a non-default OC table, but I'm totally unsure how to do this CRUD. I already created the menu in admin, which calls a route that opens a page, now I am lost to make the form save in the table I created and then can use it in the store, specifically on the product page. I will be very grateful if you can help me with any relevant material, thank you. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Dear, seriously, I just want to understand the flow of opencart's MVCL and how do I save data in a table created by me, but I do not find material for version 2.1.x.
Please explain to me how it works.

Thank you.

**Comment by danielkerr** [comment]
anyone good at writing coding documentation please contact me.
