### ISSUE TITLE
The page you requested cannot be found-opencart

### ISSUE THREAD

**Issue by kareemantar** [opencart/opencart#7174]
-my problem when i choose Design and layout after that i choose add new and i choose Layout Name and choose Content Bottom module and save
after that when i try this layout in page showing error
404
![1](https://user-images.githubusercontent.com/26651240/52531580-43ba5880-2d20-11e9-9f13-1deb67615cba.jpg)
![2](https://user-images.githubusercontent.com/26651240/52531581-43ba5880-2d20-11e9-9039-0f3df2ed2c73.jpg)
![3](https://user-images.githubusercontent.com/26651240/52531582-43ba5880-2d20-11e9-88b2-1a0ed5432f4d.jpg)

**Comment by tarturek** [comment]
I have same problem. Any news

**Comment by MuhamedAuda** [comment]
It is So theme issue not opencart issue , this theme has may issues, please refer to theme provider
