### ISSUE TITLE
account setup and checkout errors

### ISSUE THREAD

**Issue by Lanternbeauty** [opencart/opencart#7179]
lanternbeauty.net

customers receive a fatal error when attempting to create an account.  When attempting to make purchases, they also receive an error when attempting to make purchases.

**To Reproduce**
1. Go to lanternbeauty.net
2. Register for an account
3. 

**To Reproduce**
1. Go to lanternbeauty.net
2. Try to make a purchase
3. enter shipping information

**Expected behavior**
Customers should be able to register for an account and make purchases.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] chrome and IE
![error1](https://user-images.githubusercontent.com/47644898/52817123-ceb88d00-3057-11e9-8e25-45d5dc139e35.jpg)
![error2](https://user-images.githubusercontent.com/47644898/52817127-d24c1400-3057-11e9-9189-d29b406a1b13.jpg)

**Additional context**

**Comment by trinkaljuneja** [comment]
First Screen shot refers to mail issue, consult your hosting support to remove restriction on sending mail or use SMTP with correct password and port


Second screenshot refers to permission issue on session directory 
ask your hosting provider to fix that too

**Comment by Lanternbeauty** [comment]
Thank you!  But can you help me find who my hosting provider is?  I am a
newly hired filing clerk and I don't have anyone to guide me with my new
responsibility.

**Comment by underr-ua** [comment]
Ping says your site IP is 74.208.236.114. Highly likely is your hosting provider is 1and1.com

**Comment by Lanternbeauty** [comment]
Thank you for your help!
