### ISSUE TITLE
OC 3.1.x.x new stable version

### ISSUE THREAD

**Issue by rsuchovsky** [opencart/opencart#7182]
Hi, when you see the new version, it's been a long time since the last release. Thx

**Comment by stalker780** [comment]
>>3.0.3.1
>>danielkerr released this Jan 7, 2019

That was not so long ago.

**Comment by osworx** [comment]
There is a big difference between 3.0.x and 3.1.x
So, the question is correct.

**Comment by MrPlow254** [comment]
The session data table issue needs to be fixed and the variant product needs to be complete before I would consider it stable to demo with. I haven't noticed any major bugs besides those two areas. The rest of what they are doing is polishing the build. Who knows how long it will take.

**Comment by danielkerr** [comment]
it could be this month. I'm stuck with being able to compare old data to new posted data for products. I want to be able to update variant product after editing the master product without overwriting everything. 

3.1.0.0 alpha

1. Add GDPR EU law crap (80%)
2. Add bootstrap toast for add to cart
4. Finish product variants
5. Fix datetime php mysql difference
6. Add OpenCart account for admin marketplace

**Comment by danielkerr** [comment]
@MrPlow254 

4. Fix datetime php mysql difference

i think this is the issue.

**Comment by rsuchovsky** [comment]
Hi, real release date new version? :)

**Comment by danielkerr** [comment]
Yes new stuff keeps coming up. Should be this month.

**Comment by rsuchovsky** [comment]
Hi, how does it look with the new version?
It will be this month or next? :)

**Comment by rsuchovsky** [comment]
Any info on the current state of release of the new version?

**Comment by danielkerr** [comment]
trying to get a version out today. it only has one new feature which is the paypal one.

**Comment by rsuchovsky** [comment]
and release of a version with product variants and GDPR integration, when will it be available?

**Comment by danielkerr** [comment]
not too long. very few things i need to do. i have still somthing to fix on the main site but after that I will be working on the master branch. there are currently no more features that need adding. after the next master release im going to change the all forms to be ajax. maybe even include vue.js

**Comment by dariygray** [comment]
vue.js? Why do we need dependencies?

**Comment by rsuchovsky** [comment]
It is now important to release a new version with GDPR and product variants and bootstrap 4 (admin).
And then work hard on change. If they release bootstrap 5. Opencart should be ready for that as soon as possible. Otherwise, it can lose a lot of popularity.

**Comment by dariygray** [comment]
Ready to provide any help to speed up the development process and release a stable version

**Comment by danielkerr** [comment]
ok so my next task wil be to finish off all the remaining features, then fix issues.

**Comment by conghau123** [comment]
Tuyệt vời

**Comment by rsuchovsky** [comment]
Would you like to give new status info?

**Comment by dariygray** [comment]
Bootstrap 5’s very first alpha has arrived! I repeat - I am ready to help. I see that up to the stable version there is still a lot of work. Therefore, I am ready to fulfill the tasks that Daniel will set.

**Comment by rsuchovsky** [comment]
Hi, can you give info when you will release a new version with product variants and GDPR?

**Comment by dariygray** [comment]
Hi! There will be no stable version 3.1? Are we waiting for version 4?

**Comment by danielkerr** [comment]
@Webkul-Cart  is working on a maintaince release with all the fixes in for 3.x but yes because of so many changes to the extension system for it to work on the cloud we are jumping to 4.x with the next big release. which is close

**Comment by dariygray** [comment]
Is there any time frame? 2020 ends. Version 3.x has been in development since 2017 and is still unstable. I still do all projects on 2.3.0.2 :(

My offer of assistance remains valid. If I can be helpful to speed up the process, I am ready to help

**Comment by rsuchovsky** [comment]
Will the new version be released this year?

**Comment by danielkerr** [comment]
In the next few days I will release a beta.

These are the last few jobs on my to do list:

1. Add recommended extensions.
2. Add bell icon to admin header.
3. Finish purchase via admin marketplace.
4. Update bootstrap, jquery, etc..

Once i release the next version i will spend 2 weeks writing documentation
and fixing issues. I'm hoping this gives extension developers enough time
to update their extensions. Then the next version and the cloud should be
ready to launch.

**Comment by rsuchovsky** [comment]
It looks like a lot of work. It would be great to have a new version this year.

Some programmers say the opencart is dead (I also received such an opinion from the client - which is very bad). 

It is a pity, OpenCart is a good CMS. Fingers crossed - Good luck!

**Comment by MrPlow254** [comment]
A release for an open source project is a misnomer. This project clearly hasn't been dead with commits over the years happening monthly/daily. I have used "unreleased builds" that are good enough for production. If you actually use OpenCart and program you know where the bugs are and are able to fix them yourself or understand if there is a critical bug that would prevent public use. No program is stable enough for release when they get this large. I guarantee there will be a bug still present in the 4.0 release with microfixes being made shortly after and a release pushing a group of bugs at once. Why wait pull them as they are fixed...

**Comment by osworx** [comment]
> 
> .. I also received such an opinion from the client ..
> 

Who has such clients, do not need friends anymore!
And if these so called 'Clients' would be so good, why the need you and doing it not be themselve??

**Comment by rsuchovsky** [comment]
You are right. I take it that way too.
The fact that there will be a new OC 4 with errors is normal, no system is without errors.

Many programmers in my area have said that development is dead for almost 2 years. Unfortunately, this message also reached clients.

I personally have websites under oc 3.1. I fixed the bugs.
But it is true that for a long time, the development was almost no, minimal.

**Comment by danielkerr** [comment]
In the next few days I will release a beta.

These are the last few jobs on my to do list:

1. Add recommended extensions. 

just testing this now then i can move on to the other parts. 

illl be updating bootstrap, jquery, etc.. next. 

i think we should move away from font awesome. it seems to becoming to commercialized.

**Comment by rsuchovsky** [comment]
What font would you like to use instead of fontawesome?

I don't know like everyone else, but I would consider changing the twig file. Twig is slow.

**Comment by rsuchovsky** [comment]
Hello, you can give new info on the new version and release date. Will it be this year?

**Comment by stalker780** [comment]
@danielkerr 
> i think we should move away from fontawesome. it seems to becoming too commercialized.

https://materialdesignicons.com/ is a good alternative to FontAwesome

**Comment by danielkerr** [comment]
My todo list before beta:

1. Update opencart install

I'm finishing the installer now. 

3. check all emails
 \Opencart\System\Library\Mail

I already had all the mails working then changed some code and they broke.  It will be a quick fix. 

I could release the beta today or tomorrow. 

I also want to alter the order editor so maybe i do this during the beta period. 

I also need to write documentation for the new extension system. 

While that is going on i need to move code from the development server to the live site for the cloud launch.

**Comment by danielkerr** [comment]
Todo

1. fix cookies to use correct SameSite attribute
2. fix alt db adaptors
3. toast needs to be inside #container


also going through issues. should be released very soon.

**Comment by rsuchovsky** [comment]
Hi, please give new status to release?
Will there be a new version by the end of the month? it is real?
Thank you for the information and great work!

**Comment by saidbicer** [comment]
Hi, please give new status to release?
Will there be a new version by the end of the month? it is real?
Thank you for the information and great work!
