### ISSUE TITLE
catalog/controller/startup/startup.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7207]
That file is a total mess on GitHub.

$config should be: $this->config
$loader should be: $this->load

copied from another file without testing / verified.

$route has been defined on the top; good
$route is being declared as an object at the bottom of the file without redeclaration or using another variable name; bad

**Comment by straightlight** [comment]
Replace all instances of: $_SERVER with: $this->request->server .

**Comment by danielkerr** [comment]
$this->config is not required as the code is commented out. 
its just testing code.
