### ISSUE TITLE
catalog/controller/extension/payment/alipay_cross.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7211]
Replace all instances of: $_POST with $this->request->post .

**Comment by danielkerr** [comment]
are u referring to the master branch because i can not find 
$_POST anywhere.

**Comment by straightlight** [comment]
Topic has been closed without closure notes.

`are u referring to the master branch because i can not find $_POST anywhere`.

https://github.com/opencart/opencart/blob/master/upload/catalog/controller/extension/payment/alipay_cross.php

Then the callback method must really contain invisible $_POST variables in this case from the master files. I don't know the type of search tools you are using but you should definitely use the same ones that I use.

**Comment by danielkerr** [comment]
ok spotted it. my search was not working.
