### ISSUE TITLE
All TWIG files containing hard coded text

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7222]
Harcoded: `<div class="text-center"><a href="{{ next }}" class="btn btn-block">see more replies...</a></div>`

**Comment by straightlight** [comment]
`<a href="{{ refresh }}" class="reply-refresh hide">refresh</a>`

**Comment by straightlight** [comment]
All TWIG files containing hard coded text:

admin/view/template/marketplace/marketplace_comment.twig
admin/view/template/marketplace/marketplace_reply.twig
admin/view/template/extension/openbay/ebay_new.twig
admin/view/template/extension/openbay/ebay_profile_form_template.twig
admin/view/template/extension/payment/amazon_login_pay.twig
admin/view/template/extension/payment/bluepay_hosted_order.twig
admin/view/template/extension/payment/bluepay_redirect_order.twig
admin/view/template/extension/payment/cardconnect_order.twig
admin/view/template/extension/payment/cardinity_order_ajax.twig
admin/view/template/extension/payment/eway_order.twig
admin/view/template/extension/payment/firstdata_remote_order.twig
admin/view/template/extension/payment/g2apay_order.twig
admin/view/template/extension/payment/globalpay_order.twig
admin/view/template/extension/payment/globalpay_remote_order.twig
admin/view/template/extension/payment/pilibaba.twig
admin/view/template/extension/payment/pp_braintree.twig
admin/view/template/extension/payment/realex_order.twig
admin/view/template/extension/payment/realex_remote_order.twig
admin/view/template/extension/payment/sagepay_direct_order.twig
admin/view/template/extension/payment/sagepay_server_order.twig
admin/view/template/extension/payment/securetrading_pp_order.twig
admin/view/template/extension/payment/securetrading_ws.twig
admin/view/template/extension/payment/securetrading_ws_order.twig
admin/view/template/extension/payment/worldpay_order.twig
catalog/view/theme/default/template/common/cart.twig
catalog/view/theme/default/template/extension/module/divido_calculator.twig
catalog/view/theme/default/template/extension/payment/divido.twig
catalog/view/theme/default/template/extension/payment/divido_calculator.twig
catalog/view/theme/default/template/extension/payment/eway.twig
catalog/view/theme/default/template/extension/payment/eway_iframe.twig
catalog/view/theme/default/template/extension/payment/firstdata_remote.twig
catalog/view/theme/default/template/extension/payment/klarna_account.twig
catalog/view/theme/default/template/extension/payment/klarna_checkout_sidebar.twig
catalog/view/theme/default/template/extension/payment/klarna_invoice.twig

**Comment by WebkulOpencart** [comment]
fixed admin end hardcoded text in the maintenance branch
[https://github.com/opencart/opencart/pull/9057](https://github.com/opencart/opencart/pull/9057)
