### ISSUE TITLE
opencart. automatically move files

### ISSUE THREAD

**Issue by ZerocoolZa** [opencart/opencart#7223]
HI this is the error i get when i try move files to storage folder

What is going on!   HELP

Warning: fopen(/storage/logs/error.log): failed to open stream: No such file or directory in /usr/www/users/njbfoppzpy/system/library/log.php on line 22 Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/njbfoppzpy/system/library/log.php:22) in /usr/www/users/njbfoppzpy/system/framework.php on line 108 Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/log.php on line 31 Warning: fopen(/storage/logs/openbay.log): failed to open stream: No such file or directory in /usr/www/users/njbfoppzpy/system/library/log.php on line 22 Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/log.php on line 31 Warning: fopen(/storage/logs/error.log): failed to open stream: No such file or directory in /usr/www/users/njbfoppzpy/system/library/log.php on line 22 Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/log.php on line 31 Warning: fopen(/storage/cache/cache.store.1550668559): failed to open stream: No such file or directory in /usr/www/users/njbfoppzpy/system/library/cache/file.php on line 49 Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/log.php on line 31 Warning: flock() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/cache/file.php on line 51 Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/log.php on line 31 Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/cache/file.php on line 53 Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/log.php on line 31 Warning: fflush() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/cache/file.php on line 55 Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/log.php on line 31 Warning: flock() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/cache/file.php on line 57 Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/log.php on line 31 Warning: fclose() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/cache/file.php on line 59 Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/www/users/njbfoppzpy/system/library/log.php on line 31 Fatal error: Uncaught RuntimeException: Unable to create the cache directory (/storage/cache/c8). in /usr/www/users/njbfoppzpy/system/library/template/Twig/Cache/Filesystem.php:62 Stack trace: #0 /usr/www/users/njbfoppzpy/system/library/template/Twig/Environment.php(400): Twig_Cache_Filesystem->write('/storage/cache/...', 'loadTemplate('common/header.t...') #2 /usr/www/users/njbfoppzpy/system/library/template.php(51): Template\Twig->render('common/header', '1') #3 /usr/www/users/njbfoppzpy/system/engine/loader.php(125): Template->render('common/header', '1') #4 /usr/www/users/njbfoppzpy/admin/controller/common/header.php(79): Loader->view('common/header', Array) #5 /usr/www/users/njbfoppzpy/system/engine/action.php(79): ControllerCommonHeader->index(Array) #6 /usr/www/users/njbfoppzpy/system/engine/loader.php(48): Action->execute(Object(Registry), Array) #7 /usr/www/users/njbfoppzpy/admin/controller/catalog/category in /usr/www/users/njbfoppzpy/system/library/template/Twig/Cache/Filesystem.php on line 62

**Comment by underr-ua** [comment]
Check path for DIR_STORAGE directory inside the `config.php `and `admin/config.php` files. Default DIR_STORAGE directory path is `system/storage`. Check permissions.

**Comment by mondersky** [comment]
go to config.php and admin/config.php and put an absolute path for DIR_STORAGE  rather than the relative, this worked for me.
more detailed answer [http://straightdeveloper.com/my-favorite-opencart-issues/](url)
