### ISSUE TITLE
OC v3.x - BrainTree Vendor package

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7224]
Followed are references I found for Braintree vendor packages containing the bug fixes for users using PHP v7.2 and above: https://forum.opencart.com/viewtopic.php?f=201&t=210100#p747252

It also works for lower versions of PHP. This package would need to replace the previous version implemented already in the system/storage/vendor/braintree folder,

**Comment by straightlight** [comment]
Resolution confirmation: https://forum.opencart.com/viewtopic.php?f=201&t=210100&p=748350#p748348

**Comment by danielkerr** [comment]
externsion removed out of the core and will be in the opencart marketplace soon.
