### ISSUE TITLE
O.C. 3.0.3.1 Bug: When ordering via free payment does not save orde

### ISSUE THREAD

**Issue by dboyprys** [opencart/opencart#7226]
admin/controller/extension/payment/free_checkout
admin/view/template/extension/payment/free_checkout

Error and soluction,
in the above files is named free_checkout_order_status_id, the correct is payment_free_checkout_order_status_id.

This causes the title error.

**Comment by ivent** [comment]
Hello, I'm having the same problem, activate the order via free payment or the orders placed are sent to an abandoned cart and when accessing an extension and trying to change the status of the confirmed payment unsaved is always waiting for payment can resolve this is urgent.

**Comment by danielkerr** [comment]
added

**Comment by prabhatkumaroc082** [comment]
free checkout is working on Version - 3.0.3.6

**Comment by WebkulOpencart** [comment]
Yes, the issue already resolve
https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/admin/view/template/extension/payment/free_checkout.twig#L31
