### ISSUE TITLE
Marketplace error

### ISSUE THREAD

**Issue by sjohnson2019** [opencart/opencart#7227]
Error: Call to undefined function utf8_decode() in /var/www/Store.Jemms-boutique/admin/controller/marketplace/marketplace.php on line 226

i have got this error when i click the marketplace button. 

could someone suggest a fix or how to install paypal extension without this. i am working on a site for a family member and they want this to be unveiled by next week 

Many Thanks

**Comment by straightlight** [comment]
Not an OC bug on this one. This is a server-module missing related issue. See here for the solution: https://stackoverflow.com/questions/46531870/call-to-undefined-function-utf8-decode?noredirect=1&lq=1

**Comment by sjohnson2019** [comment]
Hello, Thnak you for the quick reply. this worked perfectly. 

just another quick question is there any documentation available for end users? 

this is being used for a small business who has expressed wish to manage it themselves in order to cut costs (as oppose to me doing everything and charging them for my time) 

I have found some documentation but it sounds very technical 

Many Thanks

**Comment by straightlight** [comment]
For general inquiries, please use the Opencart forum by creating a new service request,
