### ISSUE TITLE
empty payment gateway iframe 

### ISSUE THREAD

**Issue by Mwajeeh54** [opencart/opencart#7228]
after pressing on confirmation button the telr gateway returns empty iframe width of 1 px and height of 1px .

**Comment by danielkerr** [comment]
which one or should myself and the community play guessing games.

**Comment by Qoraiche** [comment]
@danielkerr i think you should make an issues template to avoid questions like this.

**Comment by Mwajeeh54** [comment]
> which one or should myself and the community play guessing games.
Sorry i am new in this community and I don't know what is the rules of this community and how i should acting to avoid stupid questions

**Comment by Mwajeeh54** [comment]
> @danielkerr i think you should make an issues template to avoid questions like this.



> which one or should myself and the community play guessing games.
??
