### ISSUE TITLE
no priority option in usps.php

### ISSUE THREAD

**Issue by sidotij** [opencart/opencart#7229]
**What version of OpenCart are you reporting this for?**
Version 3.0.3.1

**Describe the bug**
A clear and concise description of what the bug is
using usps shipping module and attempting to use first class as an option
first class does not show up in the store as an option
What section does it affect?
shipping

**To Reproduce**
1. Go to 'admin panel, extensions, extensions, shipping, United States Postal Service'
2. check "First-Class Mail Parcel " as option and save
3. Place item order, proceed to check out, 
4. First-Class Mail Parcel not listed as an option

**Expected behavior**
First-Class Mail Parcel  should be a shipping option

I did try to edit catalog/model/extension/shipping/usps.php
replacing First-Class Mail Parcel with First-Class Package Service - Retail as described in the forums but that did not work

**Server / Test environment (please complete the following information):**
 - web server
 - Operating system some flavor of linux running kernel 2.6.32-896.16.1.lve1.4.49.el6.x86_64 (might be openlinux)
 - PHP version 7.2.14
 - Apache version 2.4.38
 - Browser(s) firefox, chrome, ie and edge
 - Version 3.0.3.1

**Additional context**
Error Log:

2019-02-25 15:59:25 - USPS DATA SENT: API=RateV4&XML=<RateV4Request USERID="XXXXXXXX>	<Package ID="1">		<Service>ALL</Service>		<ZipOrigination>53405</ZipOrigination>		<ZipDestination>10993</ZipDestination>		<Pounds>3</Pounds>		<Ounces>8</Ounces>		<Container>VARIABLE</Container>		<Size>REGULAR</Size>		<Width>8</Width>		<Length>10</Length>		<Height>2</Height>		<Girth>30</Girth>		<Machinable>true</Machinable>	</Package></RateV4Request>
2019-02-25 15:59:25 - USPS DATA RECV: <?xml version="1.0" encoding="UTF-8"?>
<RateV4Response><Package ID="1"><ZipOrigination>53405</ZipOrigination><ZipDestination>10993</ZipDestination><Pounds>3</Pounds><Ounces>8</Ounces><Size>REGULAR</Size><Machinable>TRUE</Machinable><Zone>5</Zone><Postage CLASSID="3"><MailService>Priority Mail Express 1-Day</MailService><Rate>53.45</Rate></Postage><Postage CLASSID="2"><MailService>Priority Mail Express 1-Day Hold For Pickup</MailService><Rate>53.45</Rate></Postage><Postage CLASSID="1"><MailService>Priority Mail 3-Day</MailService><Rate>13.40</Rate></Postage><Postage CLASSID="22"><MailService>Priority Mail 3-Day Large Flat Rate Box</MailService><Rate>19.95</Rate></Postage><Postage CLASSID="17"><MailService>Priority Mail 3-Day Medium Flat Rate Box</MailService><Rate>14.35</Rate></Postage><Postage CLASSID="4"><MailService>USPS Retail Ground</MailService><Rate>12.38</Rate></Postage><Postage CLASSID="6"><MailService>Media Mail Parcel</MailService><Rate>4.31</Rate></Postage><Postage CLASSID="7"><MailService>Library Mail Parcel</MailService><Rate>4.08</Rate></Postage></Package></RateV4Response>

**Comment by sidotij** [comment]
I'm running the USPS extension in debug mode and I can see that it returning the data for First-Class Package Service - Retail
but not displaying in on the checkout page

<Postage CLASSID="0"><MailService>First-Class Mail Stamped Letter</MailService><Rate>0.70</Rate></Postage>
<Postage CLASSID="78"><MailService>First-Class Mail Metered Letter</MailService><Rate>0.65</Rate></Postage>
<Postage CLASSID="0"><MailService>First-Class Package Service - Retail</MailService>**<Rate>3.78</Rate></Postage>**
<Postage CLASSID="0"><MailService>First-Class Mail Large Envelope</MailService><Rate>1.15</Rate></Postage>
<Postage CLASSID="4"><MailService>USPS Retail Ground</MailService><Rate>7.95</Rate></Postage>
<Postage CLASSID="6"><MailService>Media Mail Parcel</MailService><Rate>2.75</Rate></Postage>
<Postage CLASSID="7"><MailService>Library Mail Parcel</MailService><Rate>2.61</Rate></Postage></Package></RateV4Response>

**Comment by straightlight** [comment]
Issue resolved as per user: https://forum.opencart.com/viewtopic.php?f=198&t=187217&start=20#p747862
