### ISSUE TITLE
Github file - catalog/controller/event/theme.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7230]
This line: `if (is_file(DIR_TEMPLATE . $directory . '/template/' . $route . '.twig')) {` should be replaced with: `if ($directory != 'default' && is_file(DIR_TEMPLATE . $directory . '/template/' . $route . '.twig')) {`

**Comment by mhcwebdesign** [comment]
Why? Are there cases where it doesn't have a $directory?

BTW.: I'd rather have this whole issue with twig and template modifications sorted out, see my proposed fixes at https://github.com/opencart/opencart/pull/7153

**Comment by straightlight** [comment]
While the idea of adding template codes into the process might be quite interesting, the main idea with theme.php file is to first ensure that the default theme does exist accordingly so that users may not be enforced to use a custom theme in the first place until the store being in production. My modification above suggests to simply not to disregard the default theme folder before heading to the next route on the IF conditional statement.

However, as per observing your additions in the referred post, your force contents method contains an explode('/' which should be replaced with preg_split by also validating '\' (backslashes) since '/' (forward slashes) may not be supported by Windows servers.

**Comment by straightlight** [comment]
Or, to replace my first suggestion with this one on the same file:

`if ($theme_info) {
			$template = html_entity_decode($theme_info['code'], ENT_QUOTES, 'UTF-8');
		} elseif ($theme != 'default' && is_file(DIR_TEMPLATE . $theme . '/template/' . $route . '.twig')) {
			$this->config->set('template_directory', $theme . '/template/');
		} elseif (is_file(DIR_TEMPLATE . 'default/template/' . $route . '.twig')) {
			$this->config->set('template_directory', 'default/template/');
		}`

since obviously, the first IF statement indicates that any $theme folders (implicitly default?) might be found in the process; then to include it. Else if, to only check for the default theme. The alternative solution above rather indicates that if the $theme variable does not contain the path 'default' but other theme names, then to set it into the config set: template_directory and the rest of that line. Otherwise, IF, the default theme name only has been found, to only include this one which, according to me, would make much more sense.

**Comment by mhcwebdesign** [comment]
Hmmm, I think the lines
```
		if ($this->config->get('config_theme') == 'default') {
			$directory = $this->config->get('theme_default_directory');
		} else {
			$directory = $this->config->get('config_theme');
		}
```
are perfectly OK. If it uses the default theme, then there is always a 'theme_default_directory'. If you have implemented your theme (with Controller/Model/Language for various theme-specific configurations, such as image sizes etc) then OpenCart assume that the theme folder is the name of your own implemented theme.  So I see nothing wrong in here.

**Comment by straightlight** [comment]
The portion of code you mentioned for the catalog is fine which is why I didn't mentioned it on my first post. However, there's also an else statement with it which down below (codes on my first post) then recalls that $directory variable but does not indicate to exclude the default theme in the validation process.

As for the admin theme_default, well spotted.

**Comment by mhcwebdesign** [comment]
In fact, the theme editor is quite buggy and messed up. When I have some more time I'll try to do a proper implementation of it. It should support all installed themes, not just the default theme.

**Comment by straightlight** [comment]
theme.php from the master files already has a bit of improvement regarding the theme editor with the custom themes compared to its default settings. Also with the use of Lambda for developers, this would be a great step ahead in the future as a stable release once the tracking methodologies done properly.

**Comment by mhcwebdesign** [comment]
The usage of lambda functions is quite restrictive and introduces new bugs. See https://github.com/opencart/opencart/issues/7152, https://github.com/opencart/opencart/issues/7151, https://github.com/opencart/opencart/issues/7149.
This can all be fixed with this: https://github.com/opencart/opencart/pull/7153

**Comment by danielkerr** [comment]
yes the way i have updated the master branch is to complex, will add a template method like get source.

**Comment by danielkerr** [comment]
I think your solution is the best way.

**Comment by mhcwebdesign** [comment]
Thanks. I hope you can incorporate my suggested pull request at https://github.com/opencart/opencart/pull/7153

**Comment by danielkerr** [comment]
Yes I will. Maybe not the exact code, I think a few car names can be changed.

**Comment by mhcwebdesign** [comment]
That's fine as long the basic logic of my suggested changes can be implemented.
I have had more than 100 users trying it out, and none of them reported any issues on this suggested fix, see https://forum.opencart.com/viewtopic.php?f=2&t=205940&p=751397#p751397

**Comment by straightlight** [comment]
Couldn't agree more!

**Comment by straightlight** [comment]
PHP v7.3 seem to resolved the issue with the array keys extraction. It was a bug from the extract function as well as being mentioned in the changelog regarding that function from the previous PHP version. By using this solution from mhcwebdesign, PHP requirements to avoid key conflicts would also need to be announced to the OC users.

**Comment by danielkerr** [comment]
@straightlight data key conflicts do not matter. events should be able to override template data.

**Comment by danielkerr** [comment]
looking into this stuff for the last few days. not sure i like template code being passed every template call. should do it once or from cache. you should never load a whole file to see if there are any changes between the template file and the code passed from events.

**Comment by straightlight** [comment]
@danielkerr: It would also increase chances for data keys being used identically between developers since it is not possible to load multiple features with the same data keys despite how many overrides may be involved in the future.

**Comment by danielkerr** [comment]
there are ways to avoid that. prefixing is one of them. mod_status. i dont think i have heard any issue about extensions doing this. the keys that are part of the default need to be able tooverwritten.

**Comment by straightlight** [comment]
Once in the TWIG files, developers may want to use the same array / object name as other developers and, without noticing the issue, it would obviously override the previous feature installed. Which is why, on the forum, I don't know if you recall but I did had this discussion with Jheunoff about separating the core with the overrides (array_push by developers?) This way, despite the keys being used, each override features would be used by calling the developers' usernames from the TWIG files in order to avoid conflicts.

Granted, what if the same developers wants to use the same keys between different features remains a mystery but, at least, would reduce the risk and impact management levels on limiting features with different developers so that more OC users would install, or use paid services, in order to install OC extensions with only minimal risk levels.

**Comment by danielkerr** [comment]
each template uses or requires its its own set of var keys. again template vars are not passed between different templates just its own. only the default ones might get overridden. you would not have a controller from developer loading a template from another developer. the data is not stored in one location like the languange.

**Comment by straightlight** [comment]
My above statement did not addressed anything about different templates but rather addressed about the same data keys being used in the same TWIG files. It would only take more than 1 developer to build an idea via the same template file without noticing their clients would install separate features which one to multiple data keys within the same $data array could be used and create compatibility issues between developers.

Which is why, from my previous reply and on the forum, I suggested to regroup those overrides by developers as their first key names originating the $data array so that users could extract the arrays by developers' names.

**Comment by straightlight** [comment]
`it should be dealt with separately.`

On the contrary. We need to talk about what's happening since we're currently on a new release period for OC as your suggestion may greatly improve to avoid conflicts in the future. As you have addressed above, we have enough problems to deal with TWIG files as it is and I couldn't agree more on that. Which is why, by putting both ideas together, understanding also that the whole TWIG files needs to be analyzed prior, will also greatly resolved the issues with the conflicted contributions. Granted, it may not eliminate all issues but will at least reduce them as to maintain the SLAs with other service providers without impacting the core.

**Comment by MrPlow254** [comment]
The recent changes have caused the modification.xml file to throw an error now, when executing a modification. https://github.com/opencart/opencart/blob/master/upload/system/modification.xml

`FILE: system/library/template/twig.php
CODE: $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);
NOT FOUND - OPERATIONS ABORTED!`

**Comment by mhcwebdesign** [comment]
I think the modification.xml should contains something like this (I haven't tested it yet):

```
    <file path="system/library/template/twig.php">
        <operation>
            <search>
                <![CDATA[$code = file_get_contents($file);]]>
            </search>
            <add position="replace">
                <![CDATA[$code = file_get_contents(modification($file));]]>
            </add>
        </operation>
    </file>
```

**Comment by danielkerr** [comment]
ok add the xml

**Comment by straightlight** [comment]
An example of the conflicted variables tracked by a forum user: https://forum.opencart.com/viewtopic.php?f=202&t=200617#p753550

**Comment by danielkerr** [comment]
a better solution would be tyo add text_empty to indivdual files instead of the master language file

**Comment by straightlight** [comment]
This solution might be an efficient one for the core. However, as per my explanation above regarding the array key conflicts based on contributions, it would only take one developer not setting this in individual files and still create those conflicts without either knowing or knowing by not taking care of it which, in either case, still affects the users. Which is why, it would be best to regroup those contributed distributions by developers in the array. This way, each developers would be tracked individually during troubleshooting aside from the core.

**Comment by danielkerr** [comment]
there should be no conflicts because mods my use the same keys on the default templates. drop the template key issue, its not required, not resonable to try to block keys being used since overwrighting them might be required. you are actually talking about language files and not the template.

**Comment by straightlight** [comment]
There's nowhere in my posting where I did addressed this solution as blocking keys but rather on multiple postings to regroup them by developers and extensions which means we would maintain all the created keys rather than getting rid of them and not only based on the language files but also from the override methods.

**Comment by mhcwebdesign** [comment]
@straightlight: Doesn't the language sub-key, already supported by OpenCart 3.x versions, solve the issue? A 3rd party extension could use a proper value for the subkey to identify the extension name, and then refer to a language string like this:
```
$this->language->get('sub-key')->get('a-named-string')
```

**Comment by straightlight** [comment]
Yes, that I am aware. Which is why, I stated on the above reply that this addressed issue with the override ain't only about languages when people will use these overrides.

**Comment by danielkerr** [comment]
what about initializing another language object to kleep things seperate.

**Comment by straightlight** [comment]
That might help but what I am also indicating is also to create another object for the $this->load->controller to ensure those zillions of contributed extensions out there won't interfere with the core while using the overrides. Granted, that still won't resolved the issues with the models but at least will reduce them.

**Comment by mhcwebdesign** [comment]
@straightlight : A 3rd-party extension usually loads its own controller files anyway. As long as the latter are named something like 'author_classname.php' the risks of name clashes for 3rd party controllers should be minimal.

**Comment by straightlight** [comment]
That is based on one perspective which is why on my previous replies, it mentions what 'if' those steps aren't followed as you described. We need to do something structured about those claims since it would only take one developer not to name his PHP name as you showed above and even though they would, chances to create the same controller name as other developers due to extensive distribution loads on the Marketplace and 3rd party websites are still pretty high to create a conflict as the same as the languages.

**Comment by danielkerr** [comment]
maybe another prefix

default_text_empty

**Comment by danielkerr** [comment]
i dont know.

**Comment by straightlight** [comment]
That would still increase chances for conflict since anybody else would still indicate their custom theme as this:

custom_name_text_empty rather than:

developer_name_custom_name_text_empty (a bit long)

Which is why, sub_keys with $this-load->controller object should also be used along with the sub_keys of the language objects. This way, we mostly balanced those issues.

**Comment by danielkerr** [comment]
sorry sometimes im a bit to quick and dont read the full thing. 

i think there is a way to do it. what about each time $this->load->language is called it loads a new language object and loads the default language file. the opbjects need to be stored some where though until template load.

**Comment by straightlight** [comment]
By creating a new Engine file in the system/engine folder. Then, instantiate it into the system/framework.php (or startup.php?) . An alternative would be by modifying the system/engine/loader.php file where the language method is located in order to pass an instance variable via the Template's namespace.

**Comment by straightlight** [comment]
(and in the controller method if the Engine solution is not an option)

**Comment by straightlight** [comment]
Another solution can also be under the system/config folder to distinguish the catalog files that needs to be loaded between the core / extensions.
