### ISSUE TITLE
will opencart have Configurable products extension like Magento in the coming version?

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#7231]
will opencart have Configurable products extension like Magento in the coming version?
Magento is really not friendly for small sellers.
Configurable products allow customers to choose options (Ex: shirt color). You need to create a simple product for each configuration (Ex: a product for each color).

**Comment by straightlight** [comment]
Please post on the Opencart forum for these inquiries.

**Comment by danielkerr** [comment]
if you mean product variants then yes. it already has product options
