### ISSUE TITLE
Royal Mail Shipping Not Converting Rates

### ISSUE THREAD

**Issue by Jimjam89** [opencart/opencart#7233]
**What version of OpenCart are you reporting this for?**
3.x

**Describe the bug**
The weights specified in the rates section are not converted before they are compared in catalog/model/extension/shipping/royal_mail.php this means that if you use a different weight class here than your default store weight you will get erroneous results.

**To Reproduce**
1. Set the default store weight class to gram 
2. Add some KG rates in Royal mail and some product weights.
3. Try to checkout with a product with weight.

As a solution we can change:
```
$data = explode(':', $rate);
if ($data[0] >= $weight) {
    if (isset($data[1])) {
	 $cost = $data[1];
    }

    break;
}
```
To 
```
$data = explode(':', $rate);
$rate_weight = $this->weight->convert($data[0], $this->config->get('shipping_royal_mail_weight_class_id'), $this->config->get('config_weight_class_id'));
if ($rate_weight >= $weight) {
    if (isset($data[1])) {
	 $cost = $data[1];
    }

    break;
}
```

**Comment by danielkerr** [comment]
externsion removed out of the core and will be in the opencart marketplace soon.
