### ISSUE TITLE
admin/controller/design/seo_url.php

### ISSUE THREAD

**Issue by kpeu3u** [opencart/opencart#7234]
**What version of OpenCart are you reporting this for?**
Version 3.1.x

For Cyrillic support  here is my solution

admin/controller/design/seo_url.php
line:
if (preg_match('/[^a-zA-Z0-9_\-]+/', $this->request->post['keyword'])) {
replace with:
if (preg_match('/[^a-zA-Z0-9_\-\p{Cyrillic}]+/u', $this->request->post['keyword'])) {

**Comment by danielkerr** [comment]
nice one, cheers.

**Comment by danielkerr** [comment]
does not work.  please resubmit a fixed version

Warning: preg_match(): Compilation failed: invalid range in character class at offset 14 in C:\xampp\htdocs\opencart-master\upload\admin\controller\design\seo_url.php on line 560

**Comment by danielkerr** [comment]
ok fixed it.found some other bugs wioth the seo system will fix before next release.
