### ISSUE TITLE
catalog/controller/startup/seo_url.php

### ISSUE THREAD

**Issue by kpeu3u** [opencart/opencart#7235]
**What version of OpenCart are you reporting this for?**
version 3.1.x

small fix for seo url rewrite
catalog/controller/startup/seo_url.php
loop:
		foreach ($this->regex as $result) {
			if (preg_match('/' . $result['regex'] . '/', $url_info['query'], $matches)) {
				array_shift($matches);

				foreach ($matches as $match) {
					$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "seo_url WHERE `query` = '" . $this->db->escape($match) . "' AND store_id = '" . (int)$this->config->get('config_store_id') . "' AND language_id = '" . (int)$this->config->get('config_language_id') . "'");

					if ($query->num_rows) {
						foreach ($query->rows as $seo) {
							if (!empty($seo['keyword'])) {
								$url .= '/' . $seo['keyword'];
							}
						}

						parse_str($match, $remove);

						// Remove all the matched url elements
						foreach (array_keys($remove) as $key) {
							if (isset($data[$key])) {
								unset($data[$key]);
							}
						}
					}
				}
			}
		}

replace with:
		foreach ($this->regex as $result) {
			if (preg_match('/' . $result['regex'] . '/', $url_info['query'], $matches)) {
				array_shift($matches);

				foreach ($matches as $match) {
					$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "seo_url WHERE `query` = '" . $this->db->escape($match) . "' AND store_id = '" . (int)$this->config->get('config_store_id') . "' AND language_id = '" . (int)$this->config->get('config_language_id') . "'");

					if ($query->num_rows) {
                        foreach ($query->rows as $seo) {
                            if (!empty($seo['keyword'])) {
                                $url .= '/' . $seo['keyword'];
                            }
                        }
                    }
                    parse_str($match, $remove);

                    // Remove all the matched url elements
                    foreach (array_keys($remove) as $key) {
                        if (isset($data[$key])) {
                            unset($data[$key]);
                        }
                    }
                }
            }
        }

**Comment by straightlight** [comment]
I also posted this fix solution on GitHub prior last year which was to

replace:

`if (preg_match('/' . $result['regex'] . '/', $url_info['query'], $matches)) {`

with:

`$result_regex = preg_quote($result['regex'], '/');
if (preg_match('/' . $result_regex . '/', $url_info['query'], $matches)) {`

**Comment by jeffreyeng-opencart** [comment]
I'm going to close this issue, since there was a major changes the code.
