### ISSUE TITLE
Github file and OC v3.0.3.1 - admin/controller/extension/payment/laybuy.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7238]
if ($this->config->get('laybuy_cron_time')) {
			$data['laybuy_cron_time'] = date($this->language->get('datetime_format'), strtotime($this->config->get('laybuy_cron_time')));
		} else {
			$data['laybuy_cron_time'] = $this->language->get('text_no_cron_time');
		}

I have no idea where this config key: laybuy_cron_time is originating from.

**Comment by danielkerr** [comment]
externsion removed out of the core and will be in the opencart marketplace soon.
