### ISSUE TITLE
3.1.0.0_b - Missing permission SQL

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7240]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Describe the bug**
After a clean install from master branch 3.1.0.0_b and try to edit Fixer from Currency rates you can't because isn't set in install.sql admin permision for extension/currency/fixer. You need to go to User group to set permission for admin.

**Expected behavior**
Allow to edit without intervention on User groups

**Additional context**
extension/currency/fixer permission should be added on install.sql

**Comment by danielkerr** [comment]
added
