### ISSUE TITLE
Modifications not being applied - OC 3.0.3.1

### ISSUE THREAD

**Issue by Bossman1337** [opencart/opencart#7244]
**What version of OpenCart are you reporting this for?**
v3.0.3.1
**Describe the bug**
Modifications can be uploaded and enabled as usual, also you can see the modifications being written to the modifications folder, but they won't be applied.
What section does it affect?
Modifications

**Additional context**
The cause seems to be within the system/startup.php under the modification override.

This line:
`if (defined('DIR_CATALOG')) {`

Needs to be:
 `if (!defined('DIR_CATALOG')) {`

Looks like this has been changed from previous versions or a possible typo?

**Comment by danielkerr** [comment]
no it catalog defined it means its the path required for the front of the store.
