### ISSUE TITLE
SquareUp reconnect issue: $this->request->get['response_type'] is not set

### ISSUE THREAD

**Issue by maddcoder** [opencart/opencart#7245]
**What version of OpenCart are you reporting this for?**
3.0.2.0

**Describe the bug**
In `admin/controller/extension/payment/squareup.php`, around line 605, there is a check a check to ensure `$this->request-get['state']`, `$this->request->get['code']` and `$this->request->get['response_type']` are all set. When I went to refresh the Square token this week, I see an alert for the cross site error. A little debugging shows that the 'response_type' is not set. I have a request in to Square to see if something changed, but I haven't heard back yet. This has been working for about 2 years and just failed last week. Since the token lives for a couple of months, I don't know when this broke, it just failed for me last week.

**To Reproduce**
1. I have a valid Square account, and correctly configured it at `admin/index.php?route=extension/payment/squareup`
2. Click the reconnect button to OAuth into Square and enter the correct login information.
3. The page will redirect pack to the Square extension.
4. An alert indicating a possible cross site attack is possible and the request is terminated.

**Expected behavior**
The reconnect and refresh buttons should continue working as they have been.

**Server / Test environment (please complete the following information):**
 - deployed environment
 - Linux 4.15.0-45-generic #48-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
 - PHP version 5.6
 - Apache version 2.4

**Additional context**

**Comment by maddcoder** [comment]
Square seems to require a `PAYMENTS_WRITE` scope now as well. I added it to `system/library/squareup.php` line 27 to get orders working.

**Comment by vsederburg** [comment]
Hi... I've started seeing this PAYMENTS_WRITE issue all the sudden as well, so I was really excited to see your mention of adding it to that file... but that doesn't seem to fix the error on checkout.  Did you have to do anything in any other fields related to the PAYMENTS_WRITE scope?

**Comment by danielkerr** [comment]
externsion removed out of the core and will be in the opencart marketplace soon
