### ISSUE TITLE
3.1.0.0_b - Ugly thumb image size

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7246]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Describe the bug**
Store settings logo, categories, products, manufacturers...

**Expected behavior**
Should small size

**Screenshots / Screen recordings**
![screenshot_2019-03-06_14-04-27](https://user-images.githubusercontent.com/14251939/53880288-4b1c0b80-4019-11e9-9c81-4294b06b51d6.png)

**Comment by danielkerr** [comment]
do u recommend a specific size? seems ok on mobile.

**Comment by condor2** [comment]
Like  prevision versions will be ok, and when you add products is annoying to see big size like home product page.

3.1.0..0_b
![screenshot_2019-03-06_19-04-51](https://user-images.githubusercontent.com/14251939/53899402-cba33200-4042-11e9-93c3-f71cc4fa7922.png)

vs 3.0.2.0
![screenshot_2019-03-06_19-00-06](https://user-images.githubusercontent.com/14251939/53899422-d52c9a00-4042-11e9-8f8c-713e1047aad8.png)

**Comment by stalker780** [comment]
.image {
    width: 10rem;
}

This CSS looks much better.

But still images with source 100x100 are stretched to about 158x158 and are blured
