### ISSUE TITLE
Deleting customer doesn't delete from customer_login table

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#7248]
model_customer_customer->deleteCustomer method is missing this table. 

Also what if 'customer' thinks they have an account, attempts to login five times trying different passwords and then creates a new account or resets their password. Shouldn't it clear the customer_login attempts and let them login?

**Comment by danielkerr** [comment]
Exception: Error: Unknown column 'customer_id' in 'where clause'
Error No: 1054
DELETE FROM oc_customer_login WHERE customer_id = '123'

**Comment by danielkerr** [comment]
you wasted my time!
