### ISSUE TITLE
Error in SQL (clean install not possible)

### ISSUE THREAD

**Issue by manuelkamp** [opencart/opencart#7252]
Fatal error: Uncaught Exception: Error: Field 'sort_order' doesn't have a default value<br />Error No: 1364<br /> INSERT INTO `oc_event` (`event_id`, `code`, `trigger`, `action`, `status`) VALUES (1, 'activity_customer_add', 'catalog/model/account/customer/addCustomer/after', 'event/activity/addCustomer', 1); in /storage/ssd3/270/8919270/public_html/system/library/db/mysqli.php:40 Stack trace: #0 /storage/ssd3/270/8919270/public_html/system/library/db.php(45): DB\MySQLi->query('\n\nINSERT INTO `...') #1 /storage/ssd3/270/8919270/public_html/install/model/install/install.php(26): DB->query('\n\nINSERT INTO `...') #2 /storage/ssd3/270/8919270/public_html/system/engine/loader.php(248): ModelInstallInstall->database(Array) #3 /storage/ssd3/270/8919270/public_html/system/engine/proxy.php(47): Loader->{closure}(Array, Array) #4 /storage/ssd3/270/8919270/public_html/install/controller/install/step_3.php(11): Proxy->__call('database', Array) #5 /storage/ssd3/270/8919270/public_html/system/engine/action.php(79): ControllerInstal in /storage/ssd3/270/8919270/public_html/system/library/db/mysqli.php on line 40

**Comment by danielkerr** [comment]
strange that its working for everyone else.

**Comment by danielkerr** [comment]
i think your mysql settings are to high

**Comment by manuelkamp** [comment]
No, its not a problem on my side, I'm sure that no one is able to install it.

The Installer creates this table:
CREATE TABLE `oc_event` (
  `event_id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(64) NOT NULL,
  `trigger` text NOT NULL,
  `action` text NOT NULL,
  `status` tinyint(1) NOT NULL,
  `sort_order` int(3) NOT NULL,
  PRIMARY KEY (`event_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

you can see - "sort_order" is set to NOT NULL

And then the installer script wants to insert data like the following:
INSERT INTO `oc_event` (`event_id`, `code`, `trigger`, `action`, `status`) VALUES
(1, 'activity_customer_add', 'catalog/model/account/customer/addCustomer/after', 'event/activity/addCustomer', 1);

This leads on ALL SQL DBMS to an error - just try it and reopen the Issue.

**Comment by danielkerr** [comment]
look up SET SQL_MODE

you have your db at a to restrictive setting. even if you install the sql you are still going to have errors because the setting on your mysql requires all fields are present when using an insert query!

I'm not going to waste my time arguing with you. I know the issue!

**Comment by manuelkamp** [comment]
yeah - then mr. nice guy - go yourself with your non-compliant software. bye
