### ISSUE TITLE
Bug: Start session before set time zone

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7259]
**For testing:**
	1. Change Time Zone to "America/Manaus" or other minus hours from GMT.
	2. Now, you can not login as admin or customer.

**Explain:**
1. **/system/framework.php**
```
	...
	$session->start($session_id);
	...
```
2. **/system/library/session.php**
```
public function start($session_id = '') {
	...
	$this->data = $this->adaptor->read($session_id);
	...
}
```
3. **/system/library/session/db.php**
```
public function read($session_id) {
	...
	$query = $this->db->query("SELECT `data` FROM `" . DB_PREFIX . "session` WHERE session_id = '" . $this->db->escape($session_id) . "' AND expire > '" . $this->db->escape(date('Y-m-d H:i:s', time()))  . "'");
	...
}
```
This query will using UTC time zone not default time zone.

**Comment by danielkerr** [comment]
this should fix it.

// Sync PHP and DB time zones
$db->query("SET time_zone = '" . $db->escape(date('P')) . "'");

hjave you tried this?

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/blob/master/upload/system/framework.php#L96

**Comment by engwalid1971** [comment]
The current sequence is:
1. Loading the config files
https://github.com/opencart/opencart/blob/master/upload/system/config/default.php#L13
https://github.com/opencart/opencart/blob/master/upload/system/framework.php#L8
2. Set default time zone
https://github.com/opencart/opencart/blob/master/upload/system/framework.php#L17
3. Sync PHP and DB time zones
https://github.com/opencart/opencart/blob/master/upload/system/framework.php#L96
4. Start session
https://github.com/opencart/opencart/blob/master/upload/system/framework.php#L122

Now, the session using the UTC time zone.

It will need using the default time zone from **setting table** not **config file** before starting session.

My tested solution is:
- Removing the code
https://github.com/opencart/opencart/blob/master/upload/system/framework.php#L103-L125
- And starting the session here
https://github.com/opencart/opencart/blob/master/upload/admin/controller/startup/startup.php#L22
and here
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/startup/startup.php#L37

Code
```
// Session
if (isset($this->request->cookie[$this->config->get('session_name')])) {
	$session_id = $this->request->cookie[$this->config->get('session_name')];
} else {
	$session_id = '';
}

$this->session->start($session_id);

setcookie($this->config->get('session_name'), $this->session->getId(), (ini_get('session.cookie_lifetime') ? (time() + ini_get('session.cookie_lifetime')) : 0), ini_get('session.cookie_path'), ini_get('session.cookie_domain'));
```

**Comment by danielkerr** [comment]
this should not be the case though as setting the time zone should effect the cookie timestamp surly.

**Comment by engwalid1971** [comment]
Please review the last comment, after adding the step 3 and 4 the session working perfectly.

**Comment by danielkerr** [comment]
ok i spotted the issue. maybe need to remove session start from framework

**Comment by danielkerr** [comment]
added the fix
