### ISSUE TITLE
Missing glyphicons in OC Admin

### ISSUE THREAD

**Issue by dmitriyzhuk** [opencart/opencart#7260]
**What version of OpenCart are you reporting this for?**
3.0.3.1

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

if you try to edit a time picker input in admin, you will see that the icons are missing 

screenshot:
http://joxi.ru/Rmzx7R8FYV0vGA

the reason for that is that they are loaded via font-face in the stylesheet `admin/view/stylesheet/bootstrap.css` with a relative path to the stylesheet folder

while the font files are actually in the javascript folder of bootstrap with the path of `admin/view/javascript/bootstrap/fonts/glyphicons-halflings-regular.eot`

so they never get loaded. here is a screenshot:
http://joxi.ru/a2XZw1Mswp1Z4r

**To Reproduce**
1. go to admin / sales / orders
2. add a new order
3. on second step add Apple cinima
4. try to pick a time for the product and you will see this http://joxi.ru/Rmzx7R8FYV0vGA

**Comment by danielkerr** [comment]
already updated in the master branch
