### ISSUE TITLE
RCPT TO not accepted from server! when placing new order ONLY

### ISSUE THREAD

**Issue by AbdelReheem** [opencart/opencart#7262]
Hello, we are using the amazing version OC 3.0.3.1 but We have a spam issue and we must use SMTP in email setting to reach our customers inbox

So my server is configured correctly regarding rDNS,SPF,DKIM and SMTP restriction. Also the parameter in mail setting inside OC setting is correct.

And we can send order status updates and newsletter successfully without any issue. But when try to place an order from front-end ( main website ) only not from back-end ( admin ) I received the following error

PHP Fatal error:  Uncaught Exception: Error: RCPT TO not accepted from server! in /home/***/public_html/storage/modification/system/library/mail/smtp.php:275
Stack trace:
#0 /home/***/public_html/storage/modification/system/library/mail.php(202): Mail\Smtp->send()
#1 /home/***/public_html/storage/modification/catalog/controller/mail/order.php(129): Mail->send()
#2 /home/***/public_html/vqmod/vqcache/vq2-storage_modification_system_engine_action.php(79): ControllerMailOrder->index('checkout/order/...', Array)
#3 /home/***/public_html/storage/modification/system/engine/event.php(67): Action->execute(Object(Registry), Array)
#4 /home/***/public_html/vqmod/vqcache/vq2-storage_modification_system_engine_loader.php(237): Event->trigger('model/checkout/...', Array)
#5 /home/***/public_html/system/engine/proxy.php(47): Loader->{closure}(Array, Array)
#6 /home/***/public_html/catalog/controller/extension/payment/cod.php(13): Proxy->__call('addOrderHistory', Array)
#7 /home/***/public_html/vq in /home/***/public_html/storage/modification/system/library/mail/smtp.php on line 275

SMTP setting:
Mail Parameters: email@domain.com
SMTP Hostname: ssl://domain.com
SMTP Username: email@domain.com
PW: ******
port: 465

Also I tried tls and same result

Any Suggestion or support will be highly appreciated !!

**Comment by AbdelReheem** [comment]
Any ideas

**Comment by danielkerr** [comment]
please ask in the forums. i think this is a server setup issue.

**Comment by AbdelReheem** [comment]
@Daniel Thanks Daniel for your reply 

 

I cover it, it’s neither server nor opencart files it was in the configurations as I’m using multiple sending email and I fixed it 

 

 

 

Best Wishes

AbdelReheem

+201226424480

EgyNewTech Ltd., Co.

www.EgyNewTech.com <https://www.egynewtech.com/> 

EgyNewTech
