### ISSUE TITLE
[v3.0.3.1] - Persisting issue with system/config/default.php file - gift certificate title

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7271]
This issue is still on-going regarding the gift certificate title. While this issue has been resolved on Github, on v3.0.3.1 release, the problem remains: https://forum.opencart.com/viewtopic.php?f=202&t=210517 .

**Comment by gpxjordan** [comment]
If this problem is solved in Github, I think we need to change the modification steps.

**Comment by condor2** [comment]
An easy workaround is to add in controller. And same for almost all files from account.

`$data['heading_title'] = $this->language->get('heading_title');`

**Comment by danielkerr** [comment]
already fixed. it has been fixed in the master branch. please check previous commits or previous issues reporting this.
