### ISSUE TITLE
ckeditor errors

### ISSUE THREAD

**Issue by LussRus** [opencart/opencart#7279]
Version 3.1.0.0_b
(Tested on Safari)

In section Catalog - create new or edit exist product caught errors

[Error] SyntaxError: Can't create duplicate variable: 'kService_Wiktionary'
[Error] SyntaxError: Can't create duplicate variable: 'injectSnippetFloaterRootId'
[Error] SyntaxError: Can't create duplicate variable: 'kService_Wiktionary'
[Error] SyntaxError: Can't create duplicate variable: 'injectSnippetFloaterRootId'

I have downloaded a new version of ckeditor but the errors are same.

**To Reproduce**
1. Go to 'Catalog/Product or Category'
2. Click on 'Add button' at right top corner
3. Open Inspector

**Comment by straightlight** [comment]
See this possible solution: https://github.com/tinymce/tinymce/issues/4081

**Comment by jeffreyeng-opencart** [comment]
@LussRus: Have this resolved?

**Comment by jeffreyeng-opencart** [comment]
Closed this issue since no response.
