### ISSUE TITLE
Form filling error

### ISSUE THREAD

**Issue by LussRus** [opencart/opencart#7280]
Version 3.1.0.0_b
(tested on Safari, Chrome)

After filling a form - new product/edit product, I can't save it - Error message "Check form for errors"

1. Go to 'Product Add/Edit'
2. Click on 'Add'
3. Fill the form's fields and press "Save" button at right top corner
4. See error on screen

**Comment by danielkerr** [comment]
dev version.

**Comment by danielkerr** [comment]
its been worked on
