### ISSUE TITLE
Replace jquery selector in admin/view/template/localisation/geo_zone_form.twig file

### ISSUE THREAD

**Issue by butsds** [opencart/opencart#7285]
String 109 original:
$('zone_to_geo_zone[' + zone_to_geo_zone_row + '][country_id]').trigger();

replace
$('select[name="zone_to_geo_zone[' + zone_to_geo_zone_row + '][country_id]"]').trigger('change');

**Comment by danielkerr** [comment]
that is no longer in the main code base on the master branch.
