### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by elliottcoleman** [opencart/opencart#729]
Jut downloaded v2 to take a look but can not log in to admin. It seems a token is assigned but I'm just redirected back to the login page. There are no error messages.

Please see my comments below. It may work for you but there is an issue that needs addressing.

**Comment by danielkerr** [comment]
sorry guys. i committed the code, went on holiday spent a day or to trying to get rid of jet lag,  then before i could do any changes my laptop ssd went. had to buy a cheap laptop to do some work.

**Comment by danielkerr** [comment]
the person using account opencart is actually David.

**Comment by mazensalmman** [comment]
hi 
i'm facing the same problem please tell how to solve it on opencart 2.0.3.1 version 
thanks

**Comment by sabavoip** [comment]
Hello,
I have moved my opencart site to new hosting server and after that i am unable to access admin, even i reset password few time but no luck. any help or advice please?

**Comment by elliottcoleman** [comment]
Why have you cc'd me into this email? I don't support opencart!

**Comment by sabavoip** [comment]
i just submit for help, i did not cc you, if you dont support just ignore my message.

**Comment by elliottcoleman** [comment]
Please submit a new ticket. You are replying to an old ticket so I am being cc'd.

**Comment by newjie** [comment]
I have this issue with 1.5.6.4. After putting in the write account info, the page just refreshes and login page shows again. I check the session.php file, it is already
```
			session_set_cookie_params(0, '/');
			session_start();
```
Now I am really stuck, where do I start to solve this issue?

**Comment by olegkrutikov** [comment]
Same thing (

**Comment by olegkrutikov** [comment]
Same thing on 2.0.1.1 when I try to login into the admin section - after sending the login and password form the page just refreshes back to login. The weirdest part is that this behaviour just comes and goes without any actions on my side. Like once in a couple of months I cannot login, I wait a couple of hours and it lets me log in. I do clear all caches and cookies, change browsers, even devices - nothing helps, but time.

**Comment by danielkerr** [comment]
Because the php and MySQL times are not synced. Go to system/config/default, catalog, admin and set the session_engine to file

**Comment by avnish86** [comment]
Thanks, Danielkerr 

Its work for me but I am only able to login in the admin. when I am trying to log in as a customer in front store I got the same issue. it's not log in. Even in admin its show in the recent activity that as customer login. 
my store URL is for checking: www.carhatke.com

Thanks in advance

**Comment by danielkerr** [comment]
maybe because the site is in maintance mode.

**Comment by avnish86** [comment]
no it was not maintenance mode after trying many time i just set it to maintenance mode. 
please help me

**Comment by danielkerr** [comment]
this is a very old issue. its probabvly better to open a new one. but your issue is probably better checked by my staff. please use the contact us form on opencart.com

**Comment by avnish86** [comment]
Thanks a lot i will contact on opencart form.

**Comment by chitti12** [comment]
Hello Sir, Acutally I am having issue with admin page... whenever I log in it rerfreshes 
from this:
https://mytgbrand.com/admin/
to this: 
https://mytgbrand.com/admin/index.php?route=common/home&token=e0f2c0a281d51b8f10d6567d5f0e02a5

I don't know what's happening? Please tell me

**Comment by danielkerr** [comment]
Fix ur timezones

**Comment by chitti12** [comment]
> Fix ur timezones

How could I fix it sir?

**Comment by chitti12** [comment]
> Fix ur timezones

Sir, I followed the path that you mentioned in your previous comments, public_html->admin->controller->catalog, but I did't get to know which file should I edit to change the timezones. Please guide me sir I am just a begineer.

**Comment by ADDCreative** [comment]
@chitti12 You would be best to post on https://forum.opencart.com/viewforum.php?f=20 giving as much detail as possible.
