### ISSUE TITLE
Can't login after first install

### ISSUE THREAD

**Issue by beppe9000** [opencart/opencart#7291]
**What version of OpenCart are you reporting this for?**
downloaded latest yesterdey

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Can't login as admin after first install

**To Reproduce**
Try to login after first install

**Expected behavior**
Login after first install

**Screenshots / Screen recordings**
it's not a css problem

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Deployed to WHM/cPanel account
 - Operating system: Centos 7.6
 - PHP version 7.3
 - Apache version 2.4

**Comment by TiredFingers** [comment]
Downloaded from official web page or from github? I mean it was stable/production version or it was development version?

**Comment by beppe9000** [comment]
it was the stable download from the website
