### ISSUE TITLE
Customer unexpected auto-login + Customer address mix-up + Lot of IPs for same customer from various regions of the country

### ISSUE THREAD

**Issue by alaplap** [opencart/opencart#7295]
Version: 3.0.3.1

The followings happened multiple times in a new (2 days) webshop.

- **Customer unexpected auto-login:** a new customer without a registration wanted to checkout and he/she was already logged in with an other customer profile. He/She could select from the other customer's addresses, etc. A few customers didn't recognise it and added his/her address (but no email, account name or telephone) and proceeded the checkout and finalized it in the name of an other customer.

- **Customer address mix-up:** the previous situation caused to have customers with multiple addresses from other, unknown customers.

-  **Lot of IPs for same customer from various regions of the country:** if i go to Customers->Customers on the admin, then select to modify a Customer (who have multiple addresses from other unknown users) then -> IP addresses tab. There are multiple customers who have inexplicable too much IP addresses (even 148) from various regions of the country (no, we are not selling teleportation machines) after one day!

- Another thing: while I was testing this issue, my cart got emptied unexpectedly several times.

I could reproduce it myself, accidentally, on my PC. I put a product into the cart, then clicked to checkout and got logged in automatically.

Theme caching is turned off, session_engine is 'db'.

**Similar issues:**
- https://forum.opencart.com/viewtopic.php?t=41712
- https://stackoverflow.com/questions/30959537/very-strange-session-issue-with-opencart-and-php

**Server info**
 - Deployed to a web server
 - PHP version: 5.6

**Comment by jktoole** [comment]
Unless the customers have all registered in the last 2 days, this sounds a lot like one of the problems that you've linked to (database tables are out of sync with each other, maybe from a badly restored backup) rather than a bug.

If you haven't already, you could try asking for help on the OpenCart forums.

**Comment by alaplap** [comment]
@jktoole The customers have all registered in the last 2 days. It is a new webshop, activated 2 days ago. It must be some kind of misconfiguration.

**Comment by alaplap** [comment]
@jktoole the customers have all registered in the last 2 days.

**Comment by alaplap** [comment]
I just noticed that expired sessions are not deleted from `oc_session` table... the method `public function gc($expire)` in class `Session\DB ` is never called.

**Comment by alaplap** [comment]
I think there must be a misconfiguration or a bug in the session handling.
Today the same happened: turned on my pc, opened the browser, browsed the webshop as a customer and then clicked to login (route=account/login) I got logged in right away!
I checked my session id (OCSESSID) in the oc_session table and in the data field there is a **mess** like this:

- "customer_id": 3 - an existing user who had problem with receiving others' order data and having multiple addresses from unknown people
- "payment_address" and "shipping_address" are the same as the address assigned to the very last order BUT not known by "the real customer 3"
- "user_id" and "user_token" keys in the data field!

Now i put the store to maintenance mode and even if I close my browser (Mozilla, Chrome, Edge) and reopen and visit the store route=account/login I get logged in! I never, ever logged in with Microsoft Edge to the store admin or as a customer! The same value appears in the cookie OCSESSID in the browsers.

**Comment by jktoole** [comment]
Sorry, I was thinking from your description that you might have imported an old database. Well done on getting enough customers to run into a problem like this so quickly :)

It sounds like you've found the same bug that's referred to here (the custom session handler is never actually called): https://github.com/opencart/opencart/issues/7094#issuecomment-459154982

There's what looks like a temporary workaround (a cron job to delete from the session table) here:
https://forum.opencart.com/viewtopic.php?t=200653

Or another is to go into system/config/catalog.php and change the session_engine to 'file' (although that might just give you a file/disk problem instead of a database problem).

**Comment by alaplap** [comment]
Interesting .. It seems like I'm not the only one who noticed that in the deployed version (from opencart.com) has lots of differences compared to the github master.... for example php.ini doesn't have `session.cookie_lifetime = 3600` value.

**Comment by alaplap** [comment]
I didn't import an old database. I set up the store in my localhost then deployed to the web as always. No backup happened since it is a new store.

**Comment by alaplap** [comment]
> I checked my session id (OCSESSID) in the oc_session table and in the data field there is a **mess** ...
> ...
> Now i put the store to maintenance mode and even if I close my browser (Mozilla, Chrome, Edge) and reopen and visit the store route=account/login I get logged in! I never, ever logged in with Microsoft Edge to the store admin or as a customer! The same value appears in the cookie OCSESSID in the browsers.

I could delete all the sessions from the oc_session table but I'm afraid that would hide the problem and will not solve it, just for temporarily.

**Comment by alaplap** [comment]
Now I figured out something! If I visit now the website (which is in maintenance mode) like https://www.[mydoma.in]/ the site loads the home page showing the maintenance info.
If I then browse https://www.[mydoma.in]/# (with hashmark at the end) the site loads without maintenance mode and THAT messed-up OCSESSID is set!
I changed the default logo href to `<a href="{{ base }}#">` and that causes the problem!
How to solve it? Now I'll change the logo href to the original (index.php?route=common/home) but that won't solve the problem at all.

**Comment by alaplap** [comment]
I have tested the following with 3 different PCs:

- Deleted all the sessions from oc_session
- Browsed the store without the "#" azt the end of the URL -> maintenance mode
- Browsed the store with the "#" -> no maintenance mode AND OCSESSID cookie value was "9bd6ff8d1bd102157c4ee15831"
- Checked the oc_session table which was empty
- Browsed a product/category or something else -> maintenance mode
- Checked the oc_session table and "9bd6ff8d1bd102157c4ee15831" appeared

I checked oc_session table from an other PC, not from the tested one.

And the session_id was always **9bd6ff8d1bd102157c4ee15831**. And the user whose data was messed up was 9bd6ff8d1bd102157c4ee15831 too.

**Comment by alaplap** [comment]
There are problems with session handling. @danielkerr wrote the issue with the session.cookie_lifetime parameter is fixed since ages when calling setcookie(). https://github.com/opencart/opencart/issues/5801
But that is not fixed in the deployed version and for example session.cookie_lifetime parameter is not set in the php.ini of the deployed version.

**Comment by danielkerr** [comment]
this is because you have directly backup and restored from phpmyadmin and not via opencart the script.

you clear have deleted data directly and not cleared all the tables. this is down to you and not opencart!

**Comment by alaplap** [comment]
I don't get it. Could you explain it - or link an explanation - please? How do you mean I have "deleted data directly"? I have installed the latest OC version on localhost, installed the theme, extensions, language, currency, etc.
I didn't delete any data, I just moved the webshop to an other webserver the way explained here: http://docs.opencart.com/en-gb/administration/moving-server/
What is the correct way to move opencart to an other server? 

The session and mixedup data problem go hand in hand. Mixedup explained: **customer A** recognised as **customer B** due to session problem and added his/her data (wishlist, payment address) to customer B's session data and address list, etc. The data field in oc_session stores the customer id so customer A got logged im as customer B and could edit customer B's profile.

I have reflected to your comment: https://github.com/opencart/opencart/issues/5801#issuecomment-385658955 but that is still not fixed in the deployed version! Download it from opencart.com.

**Comment by alaplap** [comment]
> 
> 
> you clearly have deleted data directly and not cleared all the correct tables. this is down to you and not opencart!
> 
> the other people with simular issues did the same. also the session has nothing to do with a mix up of data.
> 
> the session issue has to do with incorrect date time zones nothing to so with your issue.

It was not a database problem.

I have figured out that visiting mydomain.com was working correctly, but visiting www.mydomain.com wasn't and always the same value was assigned to OCSESSID (I've tested it on 3 PCs). Visiting www.mydomain.com loaded the full homepage even with maintenance mode torned on!

Solved the problem with changing `HTTP_SERVER`, `HTTPS_SERVER`, `HTTP_CATALOG` and `HTTP_CATALOG` defines to non-www in the /config.php and /admin/config.php files.

**Comment by alaplap** [comment]
Hmm... solved only temporarily. The problam is back again when accession the site with www subdomain.
Noone sles with similar problem?

**Comment by faca5** [comment]
Hello.

We have similar problem with "Customer unexpected auto-login".

We are using NGINX + Apache. Do you have any solution for it without turn off Nginx Proxy Cache?

**Comment by faca5** [comment]
Disabled Nginx Proxy Cache for domain solve the problem!

This is major issue in session native of OpenCart v3.x related with nginx and it should be fixed.
We haven't detected in OpenCart v2.

Structure:
VISITOR <-> NGNIX PROXY <-> APACHE <-> PHP <-> OpenCart

Example:
Visitor without logged was logged as randomly customer.

Any idea how to fix with using nginx proxy?
