### ISSUE TITLE
Graphical redesign of admin theme

### ISSUE THREAD

**Issue by By-oussef** [opencart/opencart#7298]
Can you improve the control panel with new colors more discreet borders.
Here is a link to an inspiration panel :
http://www.theme-guys.com/materialism/angular/#/dashboard

**Comment by danielkerr** [comment]
post another link to your own site or services you will be banned!

**Comment by By-oussef** [comment]
What ??????
 is not my site. it's just to give you an overview of the redesign that I want. I deleted the link and i change it.

**Comment by danielkerr** [comment]
then you are just wasting my time. there is no issue with the current design or colors, just your opinion.
