### ISSUE TITLE
Translate URL slug

### ISSUE THREAD

**Issue by By-oussef** [opencart/opencart#7299]
It would be interesting to make even more multilingual chevereto by allowing to translate urls to other languages. Software such as wordpress or prestashop allow this.
The site is adapted to the local language of the country.

**Describe your suggestion**

Sign Up page
EN : https://website.com/signup
FR : https://website.com/inscription
DE : https://website.com/anmelden
IT : https://website.com/iscriviti
ZT : https://website.com/註冊

Login page
EN : https://website.com/login
FR : https://website.com/connexion

Contact page
EN : https://website.com/page/contact
FR : https://website.com/page/nous-contacter
ES : https://website.com/pagina/contacto

![translating-urls-slugs-1-2](https://user-images.githubusercontent.com/41373170/55276760-9616ff00-52f7-11e9-944a-9c4fcdda1bf6.png)

**Comment by danielkerr** [comment]
this has already been added to the master branch and will be in the next major release.
