### ISSUE TITLE
Cached jquery ajax calls - Checkout

### ISSUE THREAD

**Issue by kalnyc1** [opencart/opencart#730]
Although Daniel thinks this is a personal problem for me, I thought I'd share this issue/fix regardless, because I think it's critical. Opencart relies on jquery ajax calls throughout much of the checkout process.

1) Opencart would complete the entire checkout process successfully at times, yet no orders appeared on the admin side. Although appearing so to the customer, the orders are not actually confirmed because of cached calls to 
index.php?route=payment/sagepay_us/send. (Appeared in both IE and Firefox)
2) Warning: payment method required! popup after modifying payment options.
3) Warning: shipping method required! popup after modifying shipping options.

To fix the issue I would suggest adding
$.ajaxSetup( { cache: false } );
at the beginning of the script block at the top of checkout.tpl file.

Simply trying to help and I won't post here anymore. Thank you.

**Comment by luciemarkova** [comment]
On some webhostings problem still here in version 3.
If u dont want to change php.ini u can add this code to htaccess
`<IfModule mod_headers.c>
Header set Cache-Control "no-cache, no-store, must-revalidate"
Header set Pragma "no-cache"
Header set Expires 0
</IfModule>`

I think it shuld be nice add cache false at least to login.
