### ISSUE TITLE
Coupon History Removed After Changing Order Status

### ISSUE THREAD

**Issue by ongyen8888** [opencart/opencart#7300]
Hi, may I know what's the proper steps for the coupon history to be retained even after the order is completed? I try to make a new order with the first order status "pending", then I change to "processing", up until this point the coupon history is still there but once I change to "processed" or "completed", the coupon history will be gone. If it's meant to be removed after the order is completed, can anyone advise on the status should be changed from placing order all the way to the order is completed. Thanks.

**Comment by danielkerr** [comment]
change order status from the info page and not the order edit page

**Comment by ongyen8888** [comment]
Thanks, I got it working already.
