### ISSUE TITLE
3.0.3.1 Email not working properly.

### ISSUE THREAD

**Issue by AaronSandy** [opencart/opencart#7301]
3.0.3.1

Email only being delivered to gmail email address and not any custom domain address and also outlook. 
godaddy is the host using smtp relay and the mail function in opencart.

Any advice will be greatly appreciated.

**Comment by danielkerr** [comment]
please use the forum for questions like this. this is for bug fixes. 

https://www.godaddy.com/community/GoCentral-Website-Builder/Email-from-opencart-not-sending/td-p/10758
