### ISSUE TITLE
[v3.0.3.1 and Github file] - system/library/googleshopping/googleshopping.php file

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7304]
The api($request) method should not be ran into loops since cURL already submits array results via POST requests. The array should rather be collected and sent with either http_build_query and / or JSON encoding based on its prior condition. Otherwise, web hosts may prevent looped actions to be completed.

**Comment by simo-vt** [comment]
@straightlight I am not sure I understand what you mean. Could you please provide some more context and an example for a fix?

**Comment by straightlight** [comment]
This topic will now be closed. This feature has been removed from GitHub files and didn't noticed as it seem to be a temporary thing with OC v3.0.3.1 to run this feature.
