### ISSUE TITLE
Remove mysql from install (step2)

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#7307]
https://github.com/opencart/opencart/blob/9d69904c148fdafdfc503401695b36ff05099b93/upload/install/controller/install/step_2.php#L137

Because minimum requirement is php 7.0 and mysql is also not supported anymore, shouldn't that check not be removed?

**Comment by lucasjkr** [comment]
Agree. Line 137 needs to go.

**Comment by danielkerr** [comment]
was removed many commits ago
