### ISSUE TITLE
Missing array_values

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7308]
- **admin/controller/design/banner.php**

Replace:
```
foreach ($value as $banner_image_id => $banner_image) {
```
With:
```
foreach (array_values($value) as $banner_image_id => $banner_image) {
```

- **admin/controller/catalog/filter.php**

Replace:
```
foreach ($this->request->post['filter'] as $filter_id => $filter) {
```
With:
```
foreach (array_values($this->request->post['filter']) as $filter_row => $filter) {
```
- **admin/controller/catalog/option.php**

Replace:
```
foreach ($this->request->post['option_value'] as $option_value_id => $option_value) {
```
With:
```
foreach (array_values($this->request->post['option_value']) as $option_value_id => $option_value) {
```

**Comment by danielkerr** [comment]
not sure the reason behiond the banner change

**Comment by engwalid1971** [comment]
> not sure the reason behind the changes
1. Go to 'Catalog/Filters'
2. Click on 'Add New' button
3. Fill the 'Filter Group Name'
4. Click on 'Add Filter' button, keep 'Filter Name' blank
5. Again, click on 'Add Filter' button, keep 'Filter Name' blank
6. Now you have two filters
7. Remove the first Filter
8. Now you have one filter
9. Click on 'Save' button
- Now, you have a blank 'Filter Name' with no error

**Comment by engwalid1971** [comment]
Also **admin/controller/customer/custom_field.php**
Replace:
`foreach ($this->request->post['custom_field_value'] as $custom_field_value_id => $custom_field_value) {`
With:
`foreach (array_values($this->request->post['custom_field_value']) as $custom_field_value_id => $custom_field_value) {`

**Comment by jeffreyeng-opencart** [comment]
I've checked the files and the code have changed completely. I'm going to close this issue.
