### ISSUE TITLE
 Recurring profiles doesnt work with COD

### ISSUE THREAD

**Issue by vaguemind** [opencart/opencart#7310]
I am using opencart version 3.0.3.1 
when i am using COD as payment method and activating recurring profiles for a product , in checkout page appears message : **Warning: No Payment options are available. Please contact us for assistance!**

how can i make the cod to support recurring profiles ?!

thanks

**Comment by straightlight** [comment]
Forum post.

**Comment by danielkerr** [comment]
they clearly do not go together. if items require recurring payments then the system will only present payments that have the ability to use recurreing payments
