### ISSUE TITLE
Paypal pro iframe address not change

### ISSUE THREAD

**Issue by antoniofusco** [opencart/opencart#7311]
Hallo
I am using opencart 3.0.2 and there is a strange behaviour.
If you add an address in the order page the paypal pro get the previous one.
I checked the code and in pp_pro_iframe.php controller you get the value from the table instead when you change the address in the checkout page it stays only in session.
How can I fix it
Thanks

**Comment by danielkerr** [comment]
not sure what you mean. your changing data directly in the db table? because the address is store3d in the session but is set to delete the address  in the session on any address edit.

**Comment by danielkerr** [comment]
has been removed in latest version and is replaced with a new intergration.
