### ISSUE TITLE
how to limit number of total products to show per category?

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#7312]
how to limit number of total products to show per category instead of showing all?
site will slow down if you have tens of thousands of products per category.
just like ebay, they will never show all products per category.

**Comment by chongshengdz** [comment]
showing only 1000 products per category is very reasonable.

**Comment by danielkerr** [comment]
admin > system > settings > product count

**Comment by chongshengdz** [comment]
nothing helps.

**Comment by danielkerr** [comment]
ontact us for support i will ask my staff to llook at your site.

**Comment by chongshengdz** [comment]
just like the famous site, amazon, abay, aliexpress, alibaba, they will never select and display all products in each category from database, that will consume too much CPU usage and slow down the site.
finding a product can be easily done by search function (advance search by a certain category) not just browsing the category.
and the product data will be much safer.
this should be optimised in the next opencart version.

**Comment by chongshengdz** [comment]
> ontact us for support i will ask my staff to llook at your site.

you are the developer, you don't know how to do it?

**Comment by chongshengdz** [comment]
you can take a look at my site:
https://www.transistorfet.com/index.php?route=product/category&path=1_2
https://www.transistorfet.com/index.php?route=product/category&path=1_7
20K products in a category is still fast, but 80K products in a category can take up to 10 seconds.
there is no need to display so many products in a category, it is a waste of CPU usage.
please tell me how to limit to 2K products at most per category?

**Comment by chongshengdz** [comment]
i have sent a message via opencart.com, please check it, thank you.
