### ISSUE TITLE
Opencart Api Cart Option

### ISSUE THREAD

**Issue by ElmurodovJavohir** [opencart/opencart#7313]
Please  help me, How can I send api/cart/add with option, I try it many time but it result , "Size required" like this. It's my code: 
`$url = 'https://my-site.uz/index.php?route=api/cart/add&api_token='.$api_token;
$fields = array(
  'product_id' => '303',
  'quantity' => '1', 
  'option'=>array(
  	'470' => '1092'	
  	
  )
);
 
$json = do_curl_request($url, $fields);
$data = json_decode($json);
var_dump($data);
`
In my opencart I had options and i don't know what i should . Thanks for help

**Comment by straightlight** [comment]
Forum question. See this tweak for the APIs: https://forum.opencart.com/viewtopic.php?f=202&t=203512&p=720446#p720446

**Comment by ElmurodovJavohir** [comment]
> Forum question. See this tweak for the APIs: https://forum.opencart.com/viewtopic.php?f=202&t=203512&p=720446#p720446

Thanks for your response, but sorry it didn't help me. I have api/login but my problem is that I can't give option of product and error also this.

**Comment by straightlight** [comment]
Please post your inquiry on the forum. This namespace on Github is only to report core bugs; not for custom requests!
