### ISSUE TITLE
OpenCart 3.0.3.1 error PAYMENT_WRITE submitting to Square

### ISSUE THREAD

**Issue by vsederburg** [opencart/opencart#7314]
**What version of OpenCart are you reporting this for?**
3.0.3.1

**Describe the bug**
This bug started sometime in the last 30 days. I only noticed it after refreshing the access token.

Using the Square payment extension, upon entering credit card info and clicking Confirm to submit the payment to Square, the following error appears:

 The merchant has not given your application sufficient permissions to do that. The merchant must authorize your application for the following scopes: PAYMENTS_WRITE

Note that I have already tried modifying the system/library/squareup.php file line 27 to add PAYMENTS_WRITE to the scope list.

**To Reproduce**
Go to Extension > Extensions > Payments and enable Square
Setup a square account, etc.
Add something to your cart and check out.
Select the square option for payment type
Enter credit card info and continue.
Error will appear.

**Expected behavior**
Payment should be submitted to Square for processing.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
Web Server
 - Operating system
Local: windows 10

 - PHP version
5.6.40
 - Browser(s) tested with [e.g. chrome, safari - if applicable]
Chrome v73.0.3683.86

**Additional context**
Everything has worked perfectly for a year. Nothing had been installed or upgraded before this happened. (I was running a previous opencart version, but I've since upgraded to try to fix this)

**Comment by straightlight** [comment]
It would seem Squareup have made changes to their APIs: https://github.com/square/connect-php-sdk/

**Comment by falconkirtaran** [comment]
I wrote a PR #7315 that should fix this and several other broken things with square support since their last updates, but after applying it you have to click the connect button in the configuration page again.

**Comment by vsederburg** [comment]
You're a lifesaver! I'll make the corresponding changes to my install and try it out. Thanks so much!

**Comment by vsederburg** [comment]
Oops, didn't mean to close yet.

**Comment by vsederburg** [comment]
Awesome. Seems to have worked perfectly.  Thank you very, very much!

**Comment by falconkirtaran** [comment]
I'm really glad it worked!  However, you may want to reopen it once more so that @danielkerr or someone can merge it into master; I don't have that kind of authority.

**Comment by vsederburg** [comment]
Reopening as requested. :-)  Thanks again.

**Comment by bhmhrex1** [comment]
How do I get these files? I am new to github. I went to files, view files and copied and pasted each code out of the file on here and into a new file on my desktop, then replaced on my ftp account. I am at a loss as if I did this correctly, it has not fixed my issue but given me the new following issue:

"An error occurred when trying to refresh the extension's connection to your Square account. Please verify your application credentials and try again."

Then if I click "reconnect" - it directs me to the square login, I sign in and then see this error:

"An error occurred
Invalid value for parameter `redirect_uri`"

**Comment by falconkirtaran** [comment]
Sounds like the files are not as they should be somehow... view in raw mode tends to work better for getting source out of github by copy and paste, but I really can't recommend this method of installing things.  But maybe, if you turn on debug mode and look at the logs, it might shed some light?

**Comment by bhmhrex1** [comment]
Thanks. I'll turn on debug and see what I find. What method would you recommend for installing? Thanks again!

**Comment by bhmhrex1** [comment]
I'm an idiot. This works. I didn't realize I needed to go in and Uninstaller the extension and re install after replacing the files. You are a genius. Happy Easter!

**Comment by bhmhrex1** [comment]
Never could figure out why copying the code directly from the repository and into new files on my computer, then uploading kept forwarding my back end back to this repost though. I just looked at what you edited, and edited the original files line by line and re uploaded. That ended up working.

**Comment by falconkirtaran** [comment]
Interesting.  Glad it worked; thanks for the followup.
