### ISSUE TITLE
admin/language/en-gb/extension/extension/menu.php

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7316]
Unneeded file ...

**Comment by engwalid1971** [comment]
Sorry, correct filename is:
admin/language/en-gb/extension/extension/menu/default.php

**Comment by engwalid1971** [comment]
Sorry, the correct filename is:
/admin/language/en-gb/extension/menu/default.php

**Comment by danielkerr** [comment]
its been removed, should show on the next commit
