### ISSUE TITLE
Opencart 3.0.3.1 Payapal express checkout Error

### ISSUE THREAD

**Issue by maninalliappan** [opencart/opencart#7319]
I am getting error in paypal express checkout choosing in the payment gateway

Error: Error: There was an error fetching the PayPal token at eval (eval at globalEval (https://www.menemshablues.com/catalog/view/javascript/jquery/jquery-2.1.1.min.js:2:2536), :22:21) at _loop (https://www.paypalobjects.com/api/checkout.js:5519:50) at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:5543:57) at ZalgoPromise.resolve (https://www.paypalobjects.com/api/checkout.js:5479:22) at https://www.paypalobjects.com/api/checkout.js:5453:48 at XMLHttpRequest. (https://www.paypalobjects.com/api/checkout.js:16301:28) at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:4570:31) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:4612:60) at messageListener (https://www.paypalobjects.com/api/checkout.js:4633:13)

I am already raised ticket id:  #210874

**Comment by straightlight** [comment]
See this solution: https://github.com/opencart/opencart/issues/7272

**Comment by jeffreyeng-opencart** [comment]
@maninalliappan: have you resolve your issue?

**Comment by maninalliappan** [comment]
Yes

**Comment by jeffreyeng-opencart** [comment]
Great! Closing this issue.

**Comment by will0225** [comment]
Hello, maninalliappan.
When I checkout product, I am getting same error
Could you show me how to resolve the issue before?
Please

**Comment by maninalliappan** [comment]
Hi,
I am resolved this

**Comment by will0225** [comment]
Hi
Could you please  show me how to resolve it?
Thanks

**Comment by akillar** [comment]
hello,
im facing the same problem. tried @straightlight 's fixes. but encountered other porblems. so revert back to original files. @maninalliappan can you pls share how you fixed the issue.
