### ISSUE TITLE
Reviews not showing on featured product module (default template) V3.0.3.1

### ISSUE THREAD

**Issue by jonoweb** [opencart/opencart#7320]
Typo in for each statement on line 11 catalog\view\theme\default\template\extension\module\featured.twig

` {% for i in 5 %}`

Should be: 

`{% for i in 1..5 %}`

**Comment by vivek-webkul** [comment]
#7042

**Comment by jonoweb** [comment]
not in the latest download though is it?

**Comment by straightlight** [comment]
Closure note: Solution provided on the above. Closing commit.
