### ISSUE TITLE
Warning a non well formed numeric value encountered on admin/controller/extension/payment/pp_express.php

### ISSUE THREAD

**Issue by shanhyland** [opencart/opencart#7321]
Open Cart Version 3.0.2, but it seems also present in the "Master" branch
 
In the Admin Panel, when I consult the details of an order that is over 999.99$, and that was paid with PayPal Express, I get the following warning:
a non well formed numeric value encountered on admin/controller/extension/payment/pp_express.php
The warning is for that line of code: 
`$data['capture_remaining'] = number_format($paypal_info['total'] - $captured, 2);`

It's due to the fact that a couple of lines "earlier" we did the following operation:
`$captured = number_format($this->model_extension_payment_pp_express->getCapturedTotal($paypal_info['paypal_order_id']), 2);`

Now, `$captured`, as a "format" that include ',' if the amount is over 999.99, and the "substraction" of a number with ',' isn't what really expected.

To "patch" things up I replaced:
`$captured = number_format($this->model_extension_payment_pp_express->getCapturedTotal($paypal_info['paypal_order_id']), 2);`
by
```
$captured_wo_format = $this->model_extension_payment_pp_express->getCapturedTotal($paypal_info['paypal_order_id']);
$captured = number_format($captured_wo_format, 2);
```

and
`$data['capture_remaining'] = number_format($paypal_info['total'] - $captured, 2);`
by
`$data['capture_remaining'] = number_format($paypal_info['total'] - $captured_wo_format, 2);`

**To Reproduce**
1. Have an order over 999.99, paid using PayPal Express
2. Go see the details of that order in your Admin Panel: Admin->Sales ->Orders->View
3. The url should look like something like this: /admin/index.php?route=sale/order/info&user_token={YourToken}&order_id={IdOfTheOrder}
4. See the warning in the top of the page

**Expected behavior**
Not getting a Warning message

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - PHP version: 7.0
 - Browser(s) tested with chrome and firefox

**Comment by straightlight** [comment]
The provided solution calling getCapturedTotal is not part of the core. Originating from an extension.

**Comment by straightlight** [comment]
Added in package: https://forum.opencart.com/viewtopic.php?f=201&t=210578

**Comment by danielkerr** [comment]
has been removed in latest version and is replaced with a new intergration.
