### ISSUE TITLE
Issue on open cart Version: 3.0.3.1

### ISSUE THREAD

**Issue by softaculous** [opencart/opencart#7322]
Hi,

Please login admin area, then (Left side navgation bar) Catalog> Products > Select 1/ multiple items > Copy button (Top right) > error page

The exact error is :

 Fatal error: Uncaught exception 'Exception' with message 'Error: Duplicate entry '0' for key 'PRIMARY'
Error No: 1062
INSERT INTO `ocva_product_advertise_google` (`product_id`, `store_id`, `google_product_category`) SELECT p.product_id, p2s.store_id, (SELECT c2gpc.google_product_category FROM `ocva_product_to_category` p2c LEFT JOIN `ocva_category_path` cp ON (p2c.category_id = cp.category_id) LEFT JOIN `ocva_category_to_google_product_category` c2gpc ON (c2gpc.category_id = cp.path_id AND c2gpc.store_id = 0) WHERE p2c.product_id = p.product_id AND c2gpc.google_product_category IS NOT NULL ORDER BY cp.level DESC LIMIT 0,1) as `google_product_category` FROM `ocva_product` p LEFT JOIN `ocva_product_to_store` p2s ON (p2s.product_id = p.product_id AND p2s.store_id = 0) LEFT JOIN `ocva_product_advertise_google` pag ON (pag.product_id = p.product_id AND pag.store_id=p2s.store_id) WHERE pag.product_id IS NULL AND p2s.store_id IS NOT NULL AND p.product_id IN (59)' in /{PATH}/{TO}/system/library/db/mysqli. in /{PATH}/{TO}/system/library/db/mysqli.php on line 40

**Comment by osworx** [comment]
If you able to post here in an absolute stupid formatting your message, you should also be able to use the search here and find the solution!

**Comment by danielkerr** [comment]
u need to alter the table ocva_product_advertise_google primary key to be auto increment. There is a fix the 3.x.x maintance branch. will release a new version very soon.

**Comment by softaculous** [comment]
Hi @danielkerr,

Thank you for your revert on this.
Can you provide us a temporary patch so that we can provide to the user for the same ?
Also by when can we expect the next version to release with this fix ?

Appreciate your time and co-operation with us.

**Comment by danielkerr** [comment]
ill do it now.

@osworx are you trying to get opencart kicked out of softaculous?

**Comment by danielkerr** [comment]
ok its available

**Comment by softaculous** [comment]
Hi danielkerr,

Thank you for releasing the fix so quickly. However the version number is not updated to 3.0.3.2. It is still showing as 3.0.3.1 and on website, release notes it is 3.0.3.2.

**Comment by danielkerr** [comment]
Ok will fix

**Comment by softaculous** [comment]
Hi @danielkerr,

Thank you for your acknowledgement. Let us know once you have released this we shall go ahead.

**Comment by danielkerr** [comment]
ok done

**Comment by softaculous** [comment]
Hi @danielkerr,
Appreciate all your prompt actions. We have also released the latest version.
