### ISSUE TITLE
custom category seo url not working, page not found.

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#7324]
custom category seo url not working, page not found.
i want the category url automatically to be 
keyword and seo_url_id are fields results selected from table oc_seo_url
example.com/keyword-seo_url_id ,
so i change 
$url .= '/' . $query->row['keyword'];
to
$url .= '/' . $query->row['keyword'].'-'.$query->row['seo_url_id'];
the url is working, but the pages are not found.
anywhere else do i need to change?

**Comment by chongshengdz** [comment]
after this is done, the website will not have duplicate urls.

**Comment by danielkerr** [comment]
you need to make sure all seo keywords are added for categories and products. also github is for the development not for support. please ask in the forums.
