### ISSUE TITLE
Opencart latest version api error

### ISSUE THREAD

**Issue by fkomaralp** [opencart/opencart#7327]
**What version of OpenCart are you reporting this for?**
v3.0.3.2 April 09, 2019.
**Describe the bug**
I cant connect to my website via api

**Error is**
<b>Notice</b>: Undefined index: key in <b>C:\xampp\htdocs\opencart\catalog\controller\api\login.php</b> on line <b>14</b>[]

**Comment by morea030** [comment]
Im experiencing the same issue, only different msg, my says
<b>Notice</b>: Undefined index: api_token in
<b>/var/app/current/public/catalog/controller/startup/session.php</b> on line
<b>8</b>
Is there any workaround this?

**Comment by mohammadehsan9674** [comment]
2019-05-15 14:44:22 - PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/z/zakaze1g/zakazedimoscow.ru/public_html/admin/controller/startup/error.php:34

in /home/z/zakaze1g/zakazedimoscow.ru/public_html/system/library/response.php on line 36
