### ISSUE TITLE
[v3.0.3.2 - Bug] - Event Engine - cannot redeclare class

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7332]
A user posted a fresh installation note with this error message. See forumtopic: https://forum.opencart.com/viewtopic.php?f=199&t=211156#p752202

**Comment by straightlight** [comment]
Commit closed without closure notes. Topic addressed with no results in response of the master branch.

**Comment by danielkerr** [comment]
there is no file index.php_address
