### ISSUE TITLE
Product Price Bug

### ISSUE THREAD

**Issue by ocslash** [opencart/opencart#7333]
I have installed OpenCart  Version 3.0.3.2, once as an upgrade and once as a fresh install and the results are the same as detailed. When I change the Product price on the "Canon EOS 5D"(just as an example due to the fact this item is default from the install) to $0.00 in the admin section and save the work. When I return to the store front and look up the product, the product still shows a price value  of $2.00 and the "Ex Tax" equals $0.00. Then if I return to the admin and update the price on the same item to $5.00. When I return to the store front the product price is now $8.00 and my "Ex Tax" equals $5.00.

Note: I removed the default pricing "Discount". and the new install is free of any addon modules.

**Comment by ADDCreative** [comment]
Do you have the $2.00 Eco tax enabled?

**Comment by ocslash** [comment]
Yes, That fixed the issue. Thanks
