### ISSUE TITLE
catalog/controller/event/activity.php

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7336]
**Replace:**
// model/account/affiliate/addAffiliate/after
public function addAffiliate(&$route, &$args, &$output) {
&nbsp;&nbsp;&nbsp;&nbsp;if ($this->config->get('config_customer_activity')) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this->load->model('account/activity');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$activity_data = array(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'customer_id' => **$output**,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'name'        => $args[1]['firstname'] . ' ' . $args[1]['lastname']
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this->model_account_activity->addActivity('affiliate_add', $activity_data);
&nbsp;&nbsp;&nbsp;&nbsp;}
}

// model/account/affiliate/editAffiliate/after
public function editAffiliate(&$route, &$args, &$output) {
&nbsp;&nbsp;&nbsp;&nbsp;if ($this->config->get('config_customer_activity') **&& $output**) {
&nbsp;&nbsp;&nbsp;&nbsp;$this->load->model('account/activity');

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$activity_data = array(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'customer_id' => $this->customer->getId(),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'name'        => $this->customer->getFirstName() . ' ' . $this->customer->getLastName()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this->model_account_activity->addActivity('affiliate_edit', $activity_data);
&nbsp;&nbsp;&nbsp;&nbsp;}
}

**With:**
public function addAffiliate(&$route, &$args, &$output) {
&nbsp;&nbsp;&nbsp;&nbsp;if ($this->config->get('config_customer_activity')) {
&nbsp;&nbsp;&nbsp;&nbsp;$this->load->model('account/activity');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$activity_data = array(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'customer_id' => **$args[0]**,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'name'        => $args[1]['firstname'] . ' ' . $args[1]['lastname']
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this->model_account_activity->addActivity('affiliate_add', $activity_data);
&nbsp;&nbsp;&nbsp;&nbsp;}
}

// model/account/affiliate/editAffiliate/after
public function editAffiliate(&$route, &$args, &$output) {
&nbsp;&nbsp;&nbsp;&nbsp;if ($this->config->get('config_customer_activity')) {
&nbsp;&nbsp;&nbsp;&nbsp;$this->load->model('account/activity');

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$activity_data = array(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'customer_id' => $this->customer->getId(),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'name'        => $this->customer->getFirstName() . ' ' . $this->customer->getLastName()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this->model_account_activity->addActivity('affiliate_edit', $activity_data);
&nbsp;&nbsp;&nbsp;&nbsp;}
}

**Comment by straightlight** [comment]
Referenced with this post: https://forum.opencart.com/viewtopic.php?f=202&t=211370

**Comment by engwalid1971** [comment]
https://github.com/opencart/opencart/pull/7403
