### ISSUE TITLE
Order status duplicates itself! 

### ISSUE THREAD

**Issue by ocuser83** [opencart/opencart#7337]
Hello, 
I am using the OC2.3.0.1
The problem occurs with card payments ONLY - and I am using PayPal Pro Hosted module. 
So, in Order History, I see Status - Processing duplicated multiple times. So I see multiple status rows (Processing) which happen itself. When I change the status manually to COmplete it changes to Processing again and it stops.  This DOES NOT happen with PayPal payments just payments with cards via this module. Started a couple of days ago. 

The problem is that each time new status is created the customer is also notified which is very annoying and we have several complaints! 

How can I troubleshoot this issue? Please advice. I did contact the developer of that module too and waiting for his reply.

**Comment by jeffreyeng-opencart** [comment]
@ocuser83: Have you resolved this issue?

**Comment by ocuser83** [comment]
Nope , I couldn't. Try just clear the Modifications - in many cases this worked out for me. Also that might be a Paypal problem outside your website. 

In my case it resolved itself in about a day

**Comment by jeffreyeng-opencart** [comment]
It seems Paypal had an issue on their end.  I'm going ahead and closed this. If it comes back again, please create another issue and we will investigate with our partners.
