### ISSUE TITLE
[v3.0.3.2] - admin/model/extension/payment/realex_remote.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7352]
Leftover: `//$this->logger('Capture hash construct: ' . $timestamp . '.' . $merchant_id . '.' . $realex_order['order_ref'] . '...');`

**Comment by straightlight** [comment]
Commit closed without closure notes. Valid point addressed: https://github.com/opencart/opencart/blob/master/upload/admin/model/extension/payment/realex_remote.php

**Comment by jamesallsup** [comment]
Realex gateways are being removed and replaced with updated versions of the Global Payments module (parent company).
