### ISSUE TITLE
[v3.0.3.2] - catalog/controller/extension/payment/pilibaba.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7366]
Getting better with the logs as compared to Alipay. However, one decoration found:

`echo 'OK';`

**Comment by straightlight** [comment]
In addition. MD5 is being used on that method rather than SHA1 .

**Comment by straightlight** [comment]
Commit closed without closure notes. Echo also found in admin/controller/extension/payment/pilibaba.php: echo '<img src="' . $url . '?orderNo=' . $this->request->get['order_id'] . '&merchantNo=' . $this->config->get('payment_pilibaba_merchant_number') . '">';

**Comment by danielkerr** [comment]
obviously im closing all tickets where you have added [v3.0.3.2] to the title. becuase im only updating google shopping on that release. as was said in the release notes. check if its been fixed on the master branch. if not open another ticket. I dont plan to fix the same stuff 2x!
