### ISSUE TITLE
[v3.0.3.2] - catalog/controller/extension/payment/sagepay_server.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7367]
`//Check if order we have saved in database maches with callback sagepay does`

for:

`// Check if order we have saved in database matches with callback sagepay does`

As for the exit function with echos, rather use the logs and generic message with the URL.

**Comment by straightlight** [comment]
Commit closed without closure notes. Bunch of echo lines found on master branch file as well: https://github.com/opencart/opencart/blob/master/upload/catalog/controller/extension/payment/sagepay_server.php

**Comment by danielkerr** [comment]
Then post it again with out putting the version number there. Do u expect me to check multiple branches

**Comment by straightlight** [comment]
`Then post it again with out putting the version number there. Do u expect me to check multiple branches`

Forum post indicates:

`Please report issuses and/or bugs here: https://github.com/opencart/opencart/issues`

Source: https://forum.opencart.com/viewtopic.php?f=2&t=211045

Do I expect you to check multiple branches? Of course. What else is to expect when two different packages are being distributed between opencart.com and Github files? !
