### ISSUE TITLE
[v3.0.3.2] - catalog/controller/extension/payment/twocheckout.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7368]
Uses MD5 rather than SHA1. Using HTML codes straight in callback method.

**Comment by danielkerr** [comment]
@straightlight can u just fix the master branch. its geeting close to release.

**Comment by straightlight** [comment]
There are a bunch of commits on my behalf regarding the title [GitHub files] that haven't been referenced in the master branch - especially the ones from PayPal Express Checkout fixes I have released lately, including the commits from other users that may address valid points. If you intend to a close release on the next OC, ensure to implement those fixes first.

**Comment by danielkerr** [comment]
paypal files are being removed and a new extension is in the works to replace all paypal functionality with paypals new restful apis.

**Comment by straightlight** [comment]
Also found bunch of echo lines on the master branch file: https://github.com/opencart/opencart/blob/master/upload/catalog/controller/extension/payment/twocheckout.php
