### ISSUE TITLE
oss/cos/s3 object storage

### ISSUE THREAD

**Issue by Kris-ping** [opencart/opencart#7369]
Hi, there is anyone to guide me for this question:

I am just wonderfing if opencart capable to integration with aws s3 storage / aliyun oss so I can keep statstic files such as pic/png/video in there and use cdn to speeding up access.

if there is how can I find it?

Thank you very much.

**Comment by danielkerr** [comment]
i have done this on the main opencart site. it can be done. maybe search the marketplace
