### ISSUE TITLE
jQuery UI in amdinistration

### ISSUE THREAD

**Issue by rsuchovsky** [opencart/opencart#7371]
Hi, I know it probably doesn't belong here.
But I'll be happy if someone advises me.

**Problem**: I'll call jQuery UI in administration, autocomplete will stop working.

**filter_name** is sent as an **object**

Can you tell me what to do with disabled the jQuerz UI library, to maintain the functionality of autocomplete?

Or is there a modified jQuery UI library that is compatible with opencart administration?

**Well thank you.**

**Comment by MrPlow254** [comment]
Its defined here:
upload\admin\view\javascript\common.js

**Comment by danielkerr** [comment]
jquery ui is not part of opencart

**Comment by danielkerr** [comment]
i use my own custom autocomplete
