### ISSUE TITLE
[Master Branch] - Payment / Shipping Providers

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7372]
Based on the discussion of this topic: https://github.com/opencart/opencart/issues/7328 , since this is an on-going political issue and have been asked to create a new commit about it, followed are what needs to take place before the next release comes out.

- Country IDs SQL queries needs to be reversed with Zone codes as their primary lookup, This will allow store owners to sale their products & services to customers by providers requirements based on their differed country names. This methodology will also prevent conflict between the identical zone codes and different countries.

In addition, payment / shipping extension modules in OC that should remain intact are the ones ONLY validating the address locations prior to proceed to their official payment via their APIs. Granted, this would reduce the POS strategies but would also allow store owners to maintain their SLAs especially due to the GDPR law.

**Comment by straightlight** [comment]
In addition to the above, these additional country names should be entered by users in their admin - > localisation - > zones page where country settings should be strictly handled by this page. During checkout, the country names could be associated with their zone codes and to use an explode function in the controller to relatively associated the pieces in their cURL requests.

**Comment by straightlight** [comment]
Lastly, or so to say, not only during checkout but also ensuring these changes applies to the catalog/controller/api/order.php file. These changes must be STRONGLY CONSIDERED before releasing the new version.

**Comment by danielkerr** [comment]
@straightlight ther issue is not all zones have zone codes. the UK does not seem to. USA does. Hong Kong does not.

**Comment by straightlight** [comment]
Exactly. Which is why, we need to categorize those countries and zones as per the service providers' documentation by regrouping each geographic SQL tables for each extensions since, not only that not all zones have zone codes but also the fact that zone codes can be the same from one country to another as requests can be denied via the service providers' because of those claims. In addition, OC users are only able to use one entire geographic SQL table for the entire platform and that puts them into a dead-end.

**Comment by straightlight** [comment]
The payment code and shipping code would need to be queried as well in order to accomplish this by service providers so not to affect the marketing folder in the admin versus Software Management development with the configured assets based on promotional levels.

**Comment by straightlight** [comment]
@danielkerr: List of countries that do not have zones: https://forum.opencart.com/viewtopic.php?f=202&t=211632#p754592

**Comment by straightlight** [comment]
To resolved this, the same wizard as the admin API order form (tabs with steps) would need to be used for each service providers in order to fill the country - > optional / mandatory zones depending on the country groups - > geo zones .

This methodology would reduce the massive incident requests on the OC forum regarding the shipping and payment options from the checkout page. The same methodology should be used for the admin - > systems - > localisation section to replace the three separated routes into one wizard form.

Both methodologies could then be associated with the stores and order statuses settings. Rather than configuring each order statuses from each stores in the admin - > systems - > settings - > edit settings page; to move those settings to the geopraphic locations based on the service providers. As for the locations, those could remain as is, since those claims aren't necessarily about service providers configurations.

**Comment by straightlight** [comment]
@danielkerr: The shortest solution would be this one to accomplish the goal where countries do not always have a zone related:

- Here: https://forum.opencart.com/viewtopic.php?f=202&t=211632#p754778
- Here: https://forum.opencart.com/viewtopic.php?f=202&t=211632#p754781
- Here: https://forum.opencart.com/viewtopic.php?f=202&t=211632#p754783
- And here: https://forum.opencart.com/viewtopic.php?f=202&t=211632&start=20#p754785

**Comment by straightlight** [comment]
@danielkerr: Now that the countries no longer need the zone part has been covered from my GitHub namespace, the last part would be to create a 'before' event (next version?) where the 'payment' and ';shipping' extensions gathered from each controllers would need to be moved to a model file in order to point out the trigger path from the oc_event database table. Then, to validate the postcode_required, the payment / shipping geo_zone_id and the store's geo_zone_id . If all three fails, to send an event notification email to the store owners regarding a lack of store configuration .

Granted, the order may not be recorded at that particular time but at least will prevent customers on having to fill out an invalid order where store owners won't need to submit their incident requests on the OC forum regarding abandoned orders.

**Comment by straightlight** [comment]
@danielkerr: engwalid1971 and I have worked on a project since last week in order to improve the geographic validations with modeling as suggested.

Followed are the entire file modifications suggested for the core in order to maintain the SLAs with service providers:

- Initiates event file to check duplicate zone to geo zone geographic settings: https://github.com/straightlight/opencart_contributions/commit/29d1203b7ab89af99ddf96113cfc2999c4d96ac1#diff-76ee3de97a1b8b903319b7c013d8c877

- Added custom fields with geographic address locations: https://github.com/straightlight/opencart_contributions/commit/75a094398391ef357f16d5636ad67f681936de55#diff-76ee3de97a1b8b903319b7c013d8c877 (OC service request on the forum)

- Added payment address and shipping address keys to getCustomFields method: https://github.com/straightlight/opencart_contributions/commit/e88bec4d97b72b3b3869858e977d030c07777639#diff-76ee3de97a1b8b903319b7c013d8c877 (OC service request on the forum)

- Both worked on this library file for centralizing geographic validations for payment and shipping providers based on addresses and geo zone locations: https://github.com/straightlight/opencart_contributions/blob/master/upload/system/library/geozone.php

- Added store country and store zone to the invoice: https://github.com/straightlight/opencart_contributions/commit/7bc67e21df7b34d5a2986517ef67020df1a73014#diff-76ee3de97a1b8b903319b7c013d8c877 , https://github.com/straightlight/opencart_contributions/commit/03e2bf1dff6414f7996d61bfde0b50f7f3a72fc8#diff-76ee3de97a1b8b903319b7c013d8c877 , https://github.com/straightlight/opencart_contributions/commit/d6e2ecedaf6a45ccb3e3b1ee94a4d5bc1691a341#diff-76ee3de97a1b8b903319b7c013d8c877, https://github.com/straightlight/opencart_contributions/commit/f5b8028712a6a60cf0fa6e8d69b4264d8778c228#diff-76ee3de97a1b8b903319b7c013d8c877 , https://github.com/straightlight/opencart_contributions/commit/7b33dea8dcb44452a0a1d0b67dc43163cdd3f162#diff-76ee3de97a1b8b903319b7c013d8c877 , 

- Created the catalog/model/localisation/geo_zone.php file to get zone to get zone config keys of payment and shipping extensions: https://github.com/straightlight/opencart_contributions/commit/1a7bfb3192968540d7e3d6c961845fafcf776edf#diff-76ee3de97a1b8b903319b7c013d8c877 

- Modified all alipay extension module files to demonstrate as the first example (except the admin model file). The rest of the payment and shipping extensions could follow the same leads

- All tested features -

**Comment by straightlight** [comment]
- Fixed admin/controller/localisation/geo_zone.php by validating the country ID in validateForm .
- Fixed all TWIG files by editing from {{ text_all_zones }} to {{ text_none }}
- Fixed custom fields model to get the geo_zone model

**Comment by danielkerr** [comment]
ok will look at ti.

**Comment by straightlight** [comment]
Great. Disregard other extension payment / shipping file names other than alipay for now. I'm still working on those but they'll all contain the same functionality unless you have an alternative solution. As for Alipay, it may require some toggling with tabs due to the geo zones options and that goes the same for the other payment / shipping TWIG files.

**Comment by straightlight** [comment]
- Added: Toggling has now been on the admin Alipay extension payment TWIG file (thanks to engwalid1971)
- Added: Debug config key in admin Alipay extension payment TWIG file

**Comment by straightlight** [comment]
- Modified the catalog/model/extension/payment/alipay.php for the purpose on how to use the library ($this->load->library could be excluded)

**Comment by straightlight** [comment]
- Modified: admin/controller/localisation/location.php
- Modified: admin/language/en-gb/localisation/location.php
- Modified: admin/view/template/localisation/location_form.twig
- Modified: admin/view/template/localisation/location_list.twig
- Modified: install/opencart.sql (need to add store_id in the oc_location database table)
- Modified: catalog/model/localisation/geo_zone.php
- Modified: catalog/model/account/custom_field.php

**Comment by straightlight** [comment]
- Modified admin location files to use API from jQuery api/login with generated api session ID to capture payment addresses, shipping addresses and payment accounts. Also added the store ID with the location.

**Comment by straightlight** [comment]
As discussed here: https://forum.opencart.com/viewtopic.php?f=198&t=212283#p758328 , I may have found a solution to rectify the service level issues. The $comment parameter with the add order history seem to have been entirely removed (which is fine). However, what could rather be used is a parameter to capture the API responses where those responses could only be informed to the store owners by using the events rather than both parties.

This way, while store owners may obviously not have any controls with their service providers but only on  the assets they provide from their stores, it would be only fair to capture the API responses so that under the admin, authorized admin users could report the results on the forum (without confidential data!) in order for forum supporters to provide further solutions to those users problems.
