### ISSUE TITLE
[v3.0.3.2 - Fix] - system/library/cart/cart.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7377]
Persistent issue from prior OC versions (except on GitHub file):

`$this->db->query("INSERT " . DB_PREFIX . "cart SET api_id = '" . (isset($this->session->data['api_id']) ? (int)$this->session->data['api_id'] : 0) . "', customer_id = '" . (int)$this->customer->getId() . "', session_id = '" . $this->db->escape($this->session->getId()) . "', product_id = '" . (int)$product_id . "', recurring_id = '" . (int)$recurring_id . "', `option` = '" . $this->db->escape(json_encode($option)) . "', quantity = '" . (int)$quantity . "', date_added = NOW()");`

for:

`$this->db->query("INSERT INTO " . DB_PREFIX . "cart SET api_id = '" . (isset($this->session->data['api_id']) ? (int)$this->session->data['api_id'] : 0) . "', customer_id = '" . (int)$this->customer->getId() . "', session_id = '" . $this->db->escape($this->session->getId()) . "', product_id = '" . (int)$product_id . "', recurring_id = '" . (int)$recurring_id . "', `option` = '" . $this->db->escape(json_encode($option)) . "', quantity = '" . (int)$quantity . "', date_added = NOW()");`

**Comment by danielkerr** [comment]
yep major issue. not sure though how its not showing an error when its called.

**Comment by straightlight** [comment]
Using link redirections prevents SQL errors showing even when the error output is set to true. Similar event as the one I reported in the past about the admin/model/setting/setting.php and store.php about the reserved fields. Without interrupting the action to notice error messages before the redirections gets completed, no one might ever know unless validating the database transactions and outputting the results into a thrown error exception.
