### ISSUE TITLE
nginx rewrite rules for oc3.0

### ISSUE THREAD

**Issue by Kris-ping** [opencart/opencart#7378]
who can recommend an useful nginx rewrite rules for me for oc3.0?

**Comment by danielkerr** [comment]
please ask in the forum

**Comment by Kris-ping** [comment]
@danielkerr thanks but I can't open topic in the forum since I just registered on it by last friday.

**Comment by danielkerr** [comment]
your first post needs to be approved. after that you can post as much as you want. normally gets approvd in 24 hours. maybe a bit late because of easter holidays.
