### ISSUE TITLE
OC 2.0.2.0 upgrading oc 3.0.3.2 can not login admin password 

### ISSUE THREAD

**Issue by mbkilimci** [opencart/opencart#7382]
i just upgraded version 2.0.2.0 to 3.0.3.2 
upgraging not gives any error messages 
after i try to login admin page 
not have any luck to enter
always getting error message
Error: A theme has not been assigned to this store!
no way to enter with admin password 
is there any way to configure manually default theme php files?

**Comment by maninalliappan** [comment]
Hi,
Check the setting table in database. Check the value of config_theme
![Config Table](https://user-images.githubusercontent.com/45202805/56781843-3e8a8700-6802-11e9-9638-d2c4bb4b4ac4.PNG)

**Comment by danielkerr** [comment]
resave theme and main settings
