### ISSUE TITLE
SQL Injection on OpenCart 3.0.2.0

### ISSUE THREAD

**Issue by n2rtech** [opencart/opencart#7385]
These two lines demonstrate an insecure query that is created by appending the user-supplied data (userid): dim strQuery as String

  strQuery = "SELECT name,email FROM users WHERE userid=" + Request.QueryString("userid")

If no checks are performed against the userid parameter, then the query may be arbitrarily modified as shown in these two examples of a completed query: SELECT name,email FROM users WHERE userid=42
SELECT name,email FROM users WHERE userid=42; SHUTDOWN WITH NOWAIT

**Comment by straightlight** [comment]
In which file are you noticing this from?

**Comment by danielkerr** [comment]
there is no table users, no field called name, no field called userid and all SQL quires are properly escaped.
