### ISSUE TITLE
catalog/view/theme/default/template/extension/payment/sagepay_direct.twig

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7387]
Replace:
```
  </fieldset>
```
With:
```
    </div>
  </fieldset>
```

**Comment by straightlight** [comment]
Referenced with this forum post: https://forum.opencart.com/viewtopic.php?f=201&t=194421&p=694576#p694576 .

**Comment by engwalid1971** [comment]
https://github.com/opencart/opencart/pull/7405

**Comment by ADDCreative** [comment]
I don't believe this is needed, as due to the ```{% if existing_cards %}``` ```{% else %}``` the div with ```id="card-new"``` is only defined once.

**Comment by engwalid1971** [comment]
> I don't believe this is needed, as due to the `{% if existing_cards %}` `{% else %}` the div with `id="card-new"` is only defined once.

Yes, you are right ...
