### ISSUE TITLE
Missing </span>

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7388]
**admin/view/template/marketplace/installer.twig**
Replace:
`    $('#progress-text').html('<span class="text-success">' + json['success'] + '</div>');`
With:
`    $('#progress-text').html('<span class="text-success">' + json['success'] + '</span>');`
**admin/view/template/marketplace/marketplace_comment.twig**
Replace:
`    <h5 class="mt-0">{{ comment.member }} <span>{{ comment.date_added }}</h5>`
With:
`    <h5 class="mt-0">{{ comment.member }} <span>{{ comment.date_added }}</span></h5>`
Replace:
`    <h5 class="mt-0">{{ reply.member }} <span>{{ reply.date_added }}</h5>`
With:
`    <h5 class="mt-0">{{ reply.member }} <span>{{ reply.date_added }}</span></h5>`
**admin/view/template/marketplace/marketplace_info.twig**
Replace:
`    $('#progress-text').html('<span class="text-success">' + json['success'] + '</div>');`
With:
`    $('#progress-text').html('<span class="text-success">' + json['success'] + '</span>');`

**Comment by straightlight** [comment]
That's a lot of missing entries. Great work!

**Comment by engwalid1971** [comment]
https://github.com/opencart/opencart/pull/7400
