### ISSUE TITLE
[3.0.3.2 - master] Customer registration - mail login link is wrong

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#7390]
**Situation:** A new customer register at the shop. The new account need an administrator approval. Administrator approves or denies the account. OpenCart send an information mail to the customer with a link to the login page.

**Problem:** The link is wrong. It has a doubled link direction content.

**Solution:** 
*Go to file:* admin/controller/mail/customer.php
*Find in line 44:* $data['login'] = $store_url . 'index.php?route=account/login';
*Replace:* $data['login'] = $store_url;

**Comment by straightlight** [comment]
Or with:

`$data['login'] = HTTP_CATALOG . 'index.php?route=account/login';`

**Comment by diegospm** [comment]
The problem is that it does not convert to friendly url in email. This comes from previous versions.
