### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7391]
**admin/controller/mail/affiliate.php**
**Add:**
`    // admin/model/customer/customer_approval/approveAffiliate/after`
**Before:**
`    public function approve(&$route, &$args, &$output) {`
**Add:**
`    // admin/model/customer/customer_approval/denyAffiliate/after`
**Before:**
`    public function deny(&$route, &$args, &$output) {`
__________
**admin/controller/mail/customer.php**
**Add:**
`    // admin/model/customer/customer_approval/approveCustomer/after`
**Before:**
`    public function approve(&$route, &$args, &$output) {`
**Add:**
`    // admin/model/customer/customer_approval/denyCustomer/after`
**Before:**
`    public function deny(&$route, &$args, &$output) {`
__________
**admin/controller/mail/forgotten.php**
**Add:**
`    // admin/model/user/user/editCode/after`
**Before:**
`    public function index(&$route, &$args, &$output) {`
__________
**admin/controller/mail/return.php**
**Add:**
`    // admin/model/sale/return/addReturnHistory/after`
**Before:**
`    public function index($route, $args, $output) {`
__________
**admin/controller/mail/reward.php**
**Add:**
`    // admin/model/customer/customer/addReward/after`
**Before:**
`    public function index($route, $args, $output) {`
__________
**admin/controller/mail/transaction.php**
**Add:**
`    // admin/model/customer/customer/addTransaction/after`
**Before:**
`    public function index($route, $args, $output) {`
__________
**catalog/controller/extension/total/voucher.php**
**Add:**
`    // catalog/model/checkout/order/addOrderHistory/after`
**Before:**
`    public function send($route, $args, $output) {`
__________
**catalog/controller/mail/affiliate.php**
**Add:**
`    // catalog/model/account/affiliate/addAffiliate/after`
**Before:**
`    public function index(&$route, &$args, &$output) {`
**Add:**
`    // catalog/model/account/affiliate/addAffiliate/after`
**Before:**
`    public function alert(&$route, &$args, &$output) {`
__________
**catalog/controller/mail/register.php**
**Add:**
`    // catalog/model/account/customer/addCustomer/after`
**Before:**
`    public function index(&$route, &$args, &$output) {`
**Add:**
`    // catalog/model/account/customer/addCustomer/after`
**Before:**
`    public function alert(&$route, &$args, &$output) {`
__________
**catalog/controller/mail/review.php**
**Add:**
`    // catalog/model/catalog/review/addReview/after`
**Before:**
`    public function index(&$route, &$args, &$output) {`
__________
**catalog/controller/mail/transaction.php**
**Add:**
`    // catalog/model/account/customer/addTransaction/after`
**Before:**
`    public function index(&$route, &$args, &$output) {`
__________

**Comment by straightlight** [comment]
Beautiful Christmas tree!

**Comment by engwalid1971** [comment]
New Christmas tree ...
https://github.com/opencart/opencart/issues/7396

**Comment by straightlight** [comment]
Other than the tree presentation, the referenced topic is off-topic as compared to this topic, however. Please remain on topic with the referenced commits.

**Comment by engwalid1971** [comment]
https://github.com/opencart/opencart/pull/7399
