### ISSUE TITLE
[Github File] - admin/model/localisation/zone.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7392]
`$this->cache->delete('zone');`

According to catalog/model/localisation/zone.php file:

`$this->cache->get('zone.' . (int)$country_id);`

Deletes an nonexistent cache name.

**Comment by danielkerr** [comment]
it will delete all zones. it uses zone.%.cache

**Comment by danielkerr** [comment]
$files = glob(DIR_CACHE . 'cache.' . basename($key) . '.*');

**Comment by danielkerr** [comment]
just noteced it will not work for other cache engijnes only file.

**Comment by straightlight** [comment]
There was one issue reported on the OC forum a few months back regarding the file.php and db.php from the system/library/cache's behavior but the root cause was not fully justified until now ...

**Comment by danielkerr** [comment]
need to check the other cache engines to find what the wildcard is for deleting cache by keys.

**Comment by danielkerr** [comment]
i think its fine. im not testing a load of cache engines im not using.

**Comment by danielkerr** [comment]
cache do have expire times

**Comment by danielkerr** [comment]
also you would need to be ore specific. the current file deletes  cache correctly. unless u can tell me exactly which ones have issue i can not do anything.
