### ISSUE TITLE
[ReCaptcha v3] - May need to be updated from core extensions

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7393]
@danielkerr: ReCaptcha v3 may need to be integrated into the next release since there are slightly increasing posts on the forum regarding more recent CSRF attacks through web forms. Since OC uses a prior version of ReCaptcha, this new solution may need to be implemented for security purposes.

**Comment by danielkerr** [comment]
sure will have a look. just trying to get product variants finished then will start going through the issues.

**Comment by danielkerr** [comment]
if u want to do a pull request
