### ISSUE TITLE
<label></label>

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7396]
**admin/view/template/customer/customer_form.twig**
**Replace:**
`    <input type="checkbox" name="custom_field[{{ custom_field.custom_field_id }}][]" value="{{ custom_field_value.custom_field_value_id }}" checked="checked" class="form-check-input"/> {{ custom_field_value.name }}</label>`
**With:**
`    <input type="checkbox" name="custom_field[{{ custom_field.custom_field_id }}][]" value="{{ custom_field_value.custom_field_value_id }}" checked="checked" class="form-check-input"/> {{ custom_field_value.name }}`
__________
**admin/view/template/marketing/affiliate_form.twig**
**Replace:**
`    <input type="radio" name="custom_field[{{ custom_field.custom_field_id }}]" value="{{ custom_field_value.custom_field_value_id }}" checked="checked" class="form-check-input"/>
    {{ custom_field_value.name }}</label>`
**With:**
`    <input type="radio" name="custom_field[{{ custom_field.custom_field_id }}]" value="{{ custom_field_value.custom_field_value_id }}" checked="checked" class="form-check-input"/>
    {{ custom_field_value.name }}`
**Replace:**
`    <input type="checkbox" name="custom_field[{{ custom_field.custom_field_id }}][]" value="{{ custom_field_value.custom_field_value_id }}" checked="checked" class="form-check-input"/>
    {{ custom_field_value.name }}</label>`
**With:**
`    <input type="checkbox" name="custom_field[{{ custom_field.custom_field_id }}][]" value="{{ custom_field_value.custom_field_value_id }}" checked="checked" class="form-check-input"/>
    {{ custom_field_value.name }}`
__________
**admin/view/template/sale/order_form.twig**
**Replace:**
`    <input type="radio" name="custom_field[{{ custom_field.custom_field_id }}]" value="{{ custom_field_value.custom_field_value_id }}" checked="checked" class="form-check-input"/>
    {{ custom_field_value.name }}</label>`
**With:**
`    <input type="radio" name="custom_field[{{ custom_field.custom_field_id }}]" value="{{ custom_field_value.custom_field_value_id }}" checked="checked" class="form-check-input"/>
    {{ custom_field_value.name }}`
__________

**Comment by straightlight** [comment]
While the garland could be added along with those fixes, I wonder if the labels must really be removed or rather added with the new bootstrap class with the input text box ...

**Comment by engwalid1971** [comment]
https://github.com/opencart/opencart/pull/7401

**Comment by danielkerr** [comment]
no they were left open vby mistake
