### ISSUE TITLE
UPS Error: Warning: No Shipping options are available. Please contact us for assistance!

### ISSUE THREAD

**Issue by selotoprak** [opencart/opencart#7406]
**What version of OpenCart are you reporting this for?**
3xx
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
UPS shipping methods not available
**To Reproduce**
1. Go to shipping extensions
2. Enable UPS
3. Go to Checkout

**Expected behavior**
Should show UPS shipping methods.
**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

the following change fixes the issue.

catalog/model/extension/shipping/ups.php
line 267

if ($this->config->get('ups_' . strtolower($this->config->get('shipping_ups_origin')) . '_' . $code)) {
should be:

if ($this->config->get('shipping_ups_' . strtolower($this->config->get('shipping_ups_origin')) . '_' . $code)) {

**Additional context**

**Comment by danielkerr** [comment]
this is already fixed in the master branch
