### ISSUE TITLE
Atomicy and isolation of checkout process

### ISSUE THREAD

**Issue by janAtPSTV** [opencart/opencart#7407]
Hi,
since no database transactions in opencart are used the following error may occur. It can be reproduces without a problem.
Two customers are in the checkout process at the same time with the same product of stock quantity 1.
1. php process of customer1 checks availability of stock (== 1)
2. php process of customer2 checks availability of stock (== 1)
3. php process of customer1 run sql update on stock (== 0)
4. php process of customer2 run sql update on stock (== -1)

That problem cannot be solved by simply checking the stock before reducing the quantity. Only with locking or database transactions making the checking and reducing an atomic task.

Why does opencart allow such things? Any update for this available?

Kind regards Jan

**Comment by danielkerr** [comment]
you mean when more than one customer leaves the site to pay for the same product at the same time and then they get to the checkout success page.

very simple. refund the order. have in your terms and conditions that stock is based on availability.

**Comment by janAtPSTV** [comment]
That is a bad customer experience. It's not that simple. The select and updates in the database are not synchronized on php side between the request processes. That can lead to inconsistencies and invalid data. See https://en.wikipedia.org/wiki/Producer%E2%80%93consumer_problem

**Comment by danielkerr** [comment]
you dont know WTF you are talking about!
