### ISSUE TITLE
[Master Branch] - catalog/controller/extension/payment/authorizenet_sim.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7411]
Array name of: $details ; cannot find where this variable name originates from and causing issue with the callback response from Authorize.net SIM payment.

**Comment by straightlight** [comment]
According to OC v3.0.3.2 package, the $this->request->post super global was used prior to the $details array name.

**Comment by danielkerr** [comment]
externsion removed out of the core and will be in the opencart marketplace soon.
