### ISSUE TITLE
validateForm

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7419]
More files missing the code
```
if ($this->error && !isset($this->error['warning'])) {
	$this->error['warning'] = $this->language->get('error_warning');
}
```
At the end of 'validateForm' function.

Affected files:
admin/controller/catalog/attribute_group.php
admin/controller/catalog/attribute.php
admin/controller/catalog/download.php
admin/controller/catalog/filter.php
admin/controller/catalog/manufacturer.php
admin/controller/catalog/option.php
admin/controller/catalog/review.php
admin/controller/customer/customer_group.php
admin/controller/customer/custom_field.php
admin/controller/design/banner.php
admin/controller/design/layout.php
admin/controller/design/seo_regex.php
admin/controller/design/seo_url.php
and more
...
...
...
**Also the language files missing**
`$_['error_warning']          = 'Warning: Please check the form carefully for errors!';`

**Comment by danielkerr** [comment]
its not required for all. only those with tabs in the ui.

**Comment by engwalid1971** [comment]
I prefer it for mobile users, it is easy to know if the page has been reloaded with error, maybe the user will click the save button more times because the error not shown on the screen ( depend on the height op page and the mobile view ).
Anyway everything is good without this modification.

**Comment by danielkerr** [comment]
im going to sawitch all forms to ajax after the next big rlease
