### ISSUE TITLE
catalog/view/theme/default/template/affiliate/register.twig

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7421]
**Replace:**
`<div id="custom-field{{ custom_field.custom_field_id }}" class="form-group custom-field" data-sort="{{ custom_field.sort_order }}">`
**With:**
`<div id="custom-field{{ custom_field.custom_field_id }}" class="form-group row custom-field" data-sort="{{ custom_field.sort_order }}">`

**Repeated 9 times**

**Also, move**
```
{% for custom_field in custom_fields %}
{% if custom_field.location == 'affiliate' %}
...
...
{% endfor %}
```
**outside**
`<div class="payment" id="payment-bank">`

You can move it after the tax

**Comment by jeffreyeng-opencart** [comment]
Could you please provide screenshot of the presentation part? So I could understand the reasoning of the class change and the relocating the code.

**Comment by engwalid1971** [comment]
Need to add "row" to the class.
------------------------------------
**Before:**
------------------------------------
![Screenshot from 2019-10-22 18-35-33](https://user-images.githubusercontent.com/48407821/67318417-be708000-f50b-11e9-95fc-77813fa0fa26.png)

**After:**
------------------------------------
![Screenshot from 2019-10-22 18-35-38](https://user-images.githubusercontent.com/48407821/67318453-c7f9e800-f50b-11e9-8e34-f9e8b8517001.png)

**Comment by jeffreyeng-opencart** [comment]
Ok. That makes sense. Could you also provide a screenshot of why need to move that particular code? Also, the div reference had changed previously, could you please give me a line/row number as reference? So I could make an accurate change.

**Comment by engwalid1971** [comment]
1. Set the custom field Sort Order = 5
2. Go to the catalog  --> route=affiliate/register
3. Change the payment method from 'Cheque ' to 'PayPal'
4. The custom field will be located in the middle of the payment fields

![Screenshot from 2019-10-23 05-58-02](https://user-images.githubusercontent.com/48407821/67357886-01a80e80-f55f-11e9-870c-cbd36c98a208.png)

**Comment by jeffreyeng-opencart** [comment]
The first one will be fix, but the second one I have to consult the UX part with someone and will get back to you soon.

**Comment by danielkerr** [comment]
this has been fixed already.
