### ISSUE TITLE
[Master Branch] - country_id and zone_id validation from super global

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7424]
Replace all instances of:

`if ($this->request->post['country_id'] == '') {`

with:

`if (!isset($this->request->post['country_id']) || !is_numeric($this->request->post['country_id'])) {`

from these files:

catalog/controller/api/payment.php
catalog/controller/api/shipping.php
catalog/controller/checkout/guest.php
catalog/controller/checkout/guest_shipping.php
catalog/controller/checkout/payment_address.php
catalog/controller/checkout/register.php
catalog/controller/checkout/shipping_address.php
catalog/controller/extension/total/shipping.php

Then, replace all instances of:

`if (!isset($this->request->post['zone_id']) || $this->request->post['zone_id'] == '' || !is_numeric($this->request->post['zone_id'])) {`

with:

`if (!isset($this->request->post['zone_id']) || !is_numeric($this->request->post['zone_id'])) {`

from these files:

catalog/controller/account/address.php
catalog/controller/checkout/guest.php
catalog/controller/checkout/guest_shipping.php
catalog/controller/checkout/payment_address.php
catalog/controller/checkout/register.php
catalog/controller/checkout/shipping_address.php

**Comment by straightlight** [comment]
Besides, this logic is flaw in the catalog/controller/checkout/payment_address.php file:

$country_info = $this->model_localisation_country->getCountry($this->request->post['country_id']);

				if ($country_info && $country_info['postcode_required'] && (utf8_strlen(trim($this->request->post['postcode'])) < 2 || utf8_strlen(trim($this->request->post['postcode'])) > 10)) {
					$json['error']['postcode'] = $this->language->get('error_postcode');
				}

				if ($this->request->post['country_id'] == '') {
					$json['error']['country'] = $this->language->get('error_country');
				}

The $this->request->post['country_id'] is being passed in the getCountry method as a parameter but is not yet validated by the browser. Then, it verifies for the $country_info which might have some chance to fail if the country_id is not validated with at least isset at this point. 

Then, here comes the postcode which has not been validated either to see if the variable is at least isset. Lastly, the original code validates the length of the country but without, first, validating if the variable has been found with or without isset. This could definitely be problematic for customers attempting to complete their checkout process - especially when originating from extensions (from the core as well could be implicit in this case).

**Comment by engwalid1971** [comment]
**For example:**
catalog/controller/api/shipping.php
```
if ($this->request->post['country_id'] == '') {
	$json['error']['country'] = $this->language->get('error_country');
}

if (!isset($this->request->post['zone_id']) || $this->request->post['zone_id'] == '') {
	$json['error']['zone'] = $this->language->get('error_zone');
}
```
You ask for replacing:
`if ($this->request->post['country_id'] == '') {`
with:
`if (!isset($this->request->post['country_id']) || !is_numeric($this->request->post['country_id'])) {`

After modification it will be
```
if (!isset($this->request->post['country_id']) || !is_numeric($this->request->post['country_id'])) {`
	$json['error']['country'] = $this->language->get('error_country');
}

if (!isset($this->request->post['zone_id']) || $this->request->post['zone_id'] == '') {
	$json['error']['zone'] = $this->language->get('error_zone');
}
```
Why the two comparison not the same method ?

**Comment by straightlight** [comment]
the country ID and zone ID cannot be validated as empty string logically but rather as numeric or non-numeric variables sent through the browser. Using the conjunction of: == '' would be the wrong analogy since country_id and zone_id variables are expected to be numeric. Another reason why on the payment / shipping providers commit I explained that codes should be used rather than IDs. However, since these validations are about IDs, then numeric validations must be made.

**Comment by engwalid1971** [comment]
My question is, why you didn't ask to replace

`if (!isset($this->request->post['zone_id']) || $this->request->post['zone_id'] == '') {`

with:

`if (!isset($this->request->post['zone_id']) || !is_numeric($this->request->post['zone_id'])) {``

?

**Comment by straightlight** [comment]
I did ...

it's right here on the first post:

with:

if (!isset($this->request->post['zone_id']) || !is_numeric($this->request->post['zone_id'])) {

**Comment by engwalid1971** [comment]
**It missing**
Then, replace all instances of:
`if (!isset($this->request->post['zone_id']) || $this->request->post['zone_id'] == '') {`
with:
`if (!isset($this->request->post['zone_id']) || !is_numeric($this->request->post['zone_id'])) {`

from these files:
catalog/controller/api/payment.php
catalog/controller/api/shipping.php

**Comment by straightlight** [comment]
Correct. I forgot to state those two locations. Thanks for adding these.

**Comment by straightlight** [comment]
Also in the admin files, these changes may be needed to balance the geographic settings between the store-front end and the back-end on the database.

**Comment by straightlight** [comment]
In addition, this has been discussed in the past and still don't see why the country_id and zone_id from the admin - > systems - > settings - > add / edit settings page aren't validated since, most likely, the admin/controller/startup/startup.php and catalog/controller/startup/startup.php file will validate these settings with config_country_id and config_zone_id on anyhow.

For instance, the catalog/controller/startup/startup.php file contains this line:

`$this->tax->setShippingAddress($this->config->get('config_country_id'), $this->config->get('config_zone_id'));`

The config_country_id and config_zone_id will both be added to the shipping address when the tax is being instantiated. With what will the tax be related to geographically if both entries aren't validated from the admin store / setting page itself?

There has been low severity of reports on the OC forum (fortunately to say, I might add) regarding the tax not being added when the price is being displayed as per locations. In other words, with what relations the config_country_id and config_zone_id be related to if the entries are empty by default and that the store owners are using taxes with their stores? I think this might be related to what is being reported. 

Besides, the admin store / setting page also uses identical jQuery codes to build the chain between the countries and zones altogether.

Since the master branch also misses those validations, in order to rectify that issue,

in your admin/controller/setting/setting.php and store.php file,

find:

`if (isset($this->error['email'])) {`

add above:

if (isset($this->error['country'])) {
			$data['error_country'] = $this->error['country'];
		} else {
			$data['error_country'] = '';
		}
		
		if (isset($this->error['zone'])) {
			$data['error_zone'] = $this->error['zone'];
		} else {
			$data['error_zone'] = '';
		}

Then, find:

`if ((utf8_strlen($this->request->post['config_email']) > 96) || !filter_var($this->request->post['config_email'], FILTER_VALIDATE_EMAIL)) {`

add above:

$this->load->model('localisation/country');

		$country_info = $this->model_localisation_country->getCountry($this->request->post['country_id']);

		if (!isset($this->request->post['country_id']) || !is_numeric($this->request->post['country_id'])) {
			$this->error['country'] = $this->language->get('error_country');
		}

		if (!isset($this->request->post['zone_id']) || !is_numeric($this->request->post['zone_id'])) {
			$this->error['zone'] = $this->language->get('error_zone');
		}

Then, in admin/language/en-gb/setting/setting.php and store.php file,

find:

`$_['error_address']                  = 'Store Address must be between 10 and 256 characters!';`

add below:

$_['error_country']                  = 'Please select a country!';
$_['error_zone']                     = 'Please select a region / state!';

Then, in admin/view/template/setting/setting.twig and store_form.twig file,

replace:

<div class="form-group">
                <label class="col-sm-2 control-label" for="input-country">{{ entry_country }}</label>
                <div class="col-sm-10">
                  <select name="config_country_id" id="input-country" class="form-control">
                    
                    {% for country in countries %}
                    {% if country.country_id == config_country_id %}
                    
                    <option value="{{ country.country_id }}" selected="selected">{{ country.name }}</option>
                    
                    {% else %}
                    
                    <option value="{{ country.country_id }}">{{ country.name }}</option>
                    
                    {% endif %}
                    {% endfor %}
                  
                  </select>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-zone">{{ entry_zone }}</label>
                <div class="col-sm-10">
                  <select name="config_zone_id" id="input-zone" class="form-control">
                  </select>
                </div>
              </div>

with:

<div class="form-group">
                <label class="col-sm-2 control-label" for="input-country">{{ entry_country }}</label>
                <div class="col-sm-10">
                  <select name="config_country_id" id="input-country" class="form-control">
                    
                    {% for country in countries %}
                    {% if country.country_id == config_country_id %}
                    
                    <option value="{{ country.country_id }}" selected="selected">{{ country.name }}</option>
                    
                    {% else %}
                    
                    <option value="{{ country.country_id }}">{{ country.name }}</option>
                    
                    {% endif %}
                    {% endfor %}
                  
                  </select>
				  {% if error_country %}
					<div class="text-danger">{{ error_country }}</div>
                  {% endif %}
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-zone">{{ entry_zone }}</label>
                <div class="col-sm-10">
                  <select name="config_zone_id" id="input-zone" class="form-control">
                  </select>
				  {% if error_zone %}
					<div class="text-danger">{{ error_zone }}</div>
                  {% endif %}
                </div>
              </div>

This should resolved the issue.

**Comment by engwalid1971** [comment]
No need to validate the country_id, the list of countries not have a 'please_select' option, i.e it have only a numeric values.
If you validate the zone_id then you need to replace:
```
<div class="form-group">
  <label class="col-sm-2 control-label" for="input-zone">{{ entry_zone }}</label>

```
With:
```
<div class="form-group row required">
  <label class="col-sm-2 control-label" for="input-zone">{{ entry_zone }}</label>
```

**Comment by straightlight** [comment]
Regarding the required attribute in the TWIG file for the zone dropdown, that is correct.

`No need to validate the country_id, the list of countries not have a 'please_select' option, i.e it have only a numeric values.`

Both needs to be validated since on the controller, none of them are being validated despite if the select option is not on the dropdown but rather numeric. To at least consider that a numeric value would simply replace the 'Please select' option, then the country_id would be validated on the controller in the first place. In the original codes, it isn't as explained on my previous post.

As to add the 'Pleas select' option not being on the setting.twig and / or store_form.twig file, I am not sure where a numeric value is rather seen since:

`html = '<option value="">{{ text_select }}</option>';`

are indicated in both TWIG files.

As for the country required field:

`<div class="form-group required">`

as well.

Regarding the $country_info, corrected. This was for another request.

**Comment by straightlight** [comment]
In addition from the above, it has also been discussed multiple times on the OC forum and on GitHub regarding the zone ID validation fields from the admin/controller/localisation/zone.php file. Granted, politically speaking, a zone cannot live without a country but a country can live without a zone.

Which means, in the original code, duplicated entries of the zones with their identical and relative / unrelative countries can be found on the oc_zone database table. My point of view in this is, indeed, there is no point to validate a zone ID as stand-alone which is why we don't add it in the validation method. However, the country ID is still needs to be validated in order to maintain their data relationships geographically despite how many zones may be identically added for many different countries as long as we ensure that the same country ID does not get impacted with the same zone ID on the oc_zone database table.

In order to rectify that issue,

find:

if ((utf8_strlen($this->request->post['name']) < 1) || (utf8_strlen($this->request->post['name']) > 64)) {
			$this->error['name'] = $this->language->get('error_name');
		}

add below:

if (empty($this->request->post['zone_id'])) {
			$this->error['zone'] = $this->language->get('error_zone');
		} elseif (empty($this->request->post['country_id'])) {
			$this->error['country'] = $this->language->get('error_country');
		} else {
			$this->load->model('localisation/zone');
			
			$country_info = $this->model_localisation_zone->getZonesByCountryId($this->request->post['country_id']);
			
			if (!empty($this->request->post['zone_id']) && $country_info && (int)$country_info['zone_id'] == (int)$this->request->post['zone_id']) {
				$this->error['country'] = $this->language->get('error_country_match');
			}
		}

Then, find:

if (isset($this->error['name'])) {
			$data['error_name'] = $this->error['name'];
		} else {
			$data['error_name'] = '';
		}

add below:

if (isset($this->error['country'])) {
			$data['error_country'] = $this->error['country'];
		} else {
			$data['error_country'] = '';
		}
		
		if (isset($this->error['zone'])) {
			$data['error_zone'] = $this->error['zone'];
		} else {
			$data['error_zone'] = '';
		}

In admin/language/en-gb/localisation/zone_form.twig file,

find:

<div class="form-group">
            <label class="col-sm-2 control-label" for="input-country">{{ entry_country }}</label>
            <div class="col-sm-10">
              <select name="country_id" id="input-country" class="form-control">
                {% for country in countries %}
                {% if country.country_id == country_id %}
                <option value="{{ country.country_id }}" selected="selected">{{ country.name }}</option>
                {% else %}
                <option value="{{ country.country_id }}">{{ country.name }}</option>
                {% endif %}
                {% endfor %}
              </select>			 
            </div>
          </div>

replace with:

<div class="form-group required">
            <label class="col-sm-2 control-label" for="input-country">{{ entry_country }}</label>
            <div class="col-sm-10">
              <select name="country_id" id="input-country" class="form-control">
                {% for country in countries %}
                {% if country.country_id == country_id %}
                <option value="{{ country.country_id }}" selected="selected">{{ country.name }}</option>
                {% else %}
                <option value="{{ country.country_id }}">{{ country.name }}</option>
                {% endif %}
                {% endfor %}
              </select>
			  {% if error_country %}
				<div class="text-danger">{{ error_country }}</div>
              {% endif %}
            </div>
          </div>

Do the same for the zones.

In admin/language/en-gb/localisation/zone.php file,

add below error_name key:

$_['error_country']                  = 'Please select a country!';
$_['error_zone']                     = 'Please select a region / state!';

This should resolved the issue.

**Comment by straightlight** [comment]
Instructions for admin/controller/localisation/zone.php file modified above. Also added a new method with instructions for admin/model/localisation/zone.php file.

**Comment by engwalid1971** [comment]
>Both needs to be validated since on the controller, none of them are being validated despite if the select option is not on the dropdown but rather numeric. To at least consider that a numeric value would simply replace the 'Please select' option, then the country_id would still need to be validated on the controller in the first place

You are correct, the country_id need to be validated...

**Comment by straightlight** [comment]
These last modifications have now been added on my GitHub namespace.

**Comment by danielkerr** [comment]
do not do that its foreced typed in the db so it wil come back with nothing
