### ISSUE TITLE
Opencart 2.3.0.2 image attributes button missing

### ISSUE THREAD

**Issue by alfredosimoes** [opencart/opencart#7426]
I want to add a link in a image that i inserted in product description but the image attributes button is missing. Can i have your help to solve this?

![opencart-2302-image-attributes-button-missing](https://user-images.githubusercontent.com/37916316/57562410-46adff00-738a-11e9-8cc3-e7100814b784.jpg)

**Comment by straightlight** [comment]
Posting about an old OC version. Please post on the forum.

**Comment by straightlight** [comment]
Closure note: About an old OC version release. Closing commit.
