### ISSUE TITLE
[Master Branch] - country() method

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7428]
The country() method is being called from these files as repetition:

- catalog/controller/account/account.php
- catalog/controller/checkout/checkout.php
- catalog/controller/extension/total/shipping.php

Should be called with:

`$json = $this->load->controller('common/country', array());`

(needs to be created). Array would of course contain the keys and the values to be passed to the common/country controller (same method as the pagination controller).

**Comment by danielkerr** [comment]
its been moved to a central location
