### ISSUE TITLE
Whitespace in custom fields in the Guest checkout form

### ISSUE THREAD

**Issue by 5ulo** [opencart/opencart#7430]
**What version of OpenCart are you reporting this for?**
3.0.x

**Describe the bug**
Every custom field in Guest checkout form is missing placeholder because of input value contains two blank characters (spaces)
`<input type="text" value="  ">`

**To Reproduce**
1. add custom field to Address
2. buy a toy :) 
3. checkout as Gues and check the custom field value

**Expected behavior**
Input value should be empty
`<input type="text" value="">`

**Screenshots / Screen recordings**
<img width="1301" alt="Screenshot 2019-05-13 at 11 02 35" src="https://user-images.githubusercontent.com/4980919/57609351-fc39a780-756e-11e9-95f6-d903540f0791.png">
<img width="1301" alt="Screenshot 2019-05-13 at 11 01 01" src="https://user-images.githubusercontent.com/4980919/57609352-fc39a780-756e-11e9-8e66-41199b2568cc.png">

**Additional context**
I've made a quick ocmod fix
```
<?xml version="1.0" encoding="utf-8"?>
<modification>
  <name>Fix whitespace characters in Guest form</name>
  <code>enjoy_guest_whitespace</code>
  <version>1.0.0</version>
  <author>5ulo (5ulo@n-joy.sk)</author>
  <file path="catalog/view/theme/default/template/checkout/guest.twig">
    <operation>
      <search><![CDATA[} {]]></search>
      <add position="replace"><![CDATA[}{]]></add>
    </operation>
  </file>
</modification>
```

**Comment by jeffreyeng-opencart** [comment]
I've removed extra spaces in the if logic within the value. Now, it should work.

**Comment by jeffreyeng-opencart** [comment]
I've double checked. Not working right. Still investigating.

**Comment by jeffreyeng-opencart** [comment]
Reverted back. https://github.com/opencart/opencart/pull/7414/commits/773245a9b21e97ce941be6a788c5493403500b1a

**Comment by jeffreyeng-opencart** [comment]
Now it is work. Was wrong line code fix.
