### ISSUE TITLE
email not working(SMTP)

### ISSUE THREAD

**Issue by amirsergo** [opencart/opencart#7431]
Please help me 
Warning: fsockopen(): unable to connect to ssl://smtp.gmail.com:465 (Connection timed out) in /home/ostrysvet.cz/ostrysvet.cz/system/library/mail/smtp.php on line 87
Fatal error: Uncaught Exception: Error: Connection timed out (110) in /home/ostrysvet.cz/ostrysvet.cz/system/library/mail/smtp.php:90 Stack trace: #0 /home/ostrysvet.cz/ostrysvet.cz/system/library/mail.php(142): Mail\Smtp->send() #1 /home/ostrysvet.cz/ostrysvet.cz/catalog/controller/information/contact.php(25): Mail->send() #2 /home/ostrysvet.cz/ostrysvet.cz/system/engine/action.php(79): ControllerInformationContact->index() #3 /home/ostrysvet.cz/ostrysvet.cz/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #4 /home/ostrysvet.cz/ostrysvet.cz/system/engine/action.php(79): ControllerStartupRouter->index() #5 /home/ostrysvet.cz/ostrysvet.cz/system/engine/router.php(67): Action->execute(Object(Registry)) #6 /home/ostrysvet.cz/ostrysvet.cz/system/engine/router.php(56): Router->execute(Object(Action)) #7 /home/ostrysvet.cz/ostrysvet.cz/system/framework.php(168): Router->dispatch(Object(Action), Object(Action)) #8 /home/ostrysvet.cz/ostrysvet.cz/system/startup.php(104): require_once('/home/ostrysvet.. in /home/ostrysvet.cz/ostrysvet.cz/system/library/mail/smtp.php on line 90

what I must do?
http://prnt.sc/no0rs1

**Comment by straightlight** [comment]
Not an OC development. Please post on the OC forum for those incident requests.
