### ISSUE TITLE
[Master Branch] - catalog/controller/mail/order.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7433]
There has been low severity on the OC forum, fortunately, that reported the logo from their add order event that only shows from their current store but not from the order_info store.

To correct this, replace:

$this->load->model('tool/image');

		if (is_file(DIR_IMAGE . html_entity_decode($this->config->get('config_logo'), ENT_QUOTES, 'UTF-8'))) {

			$data['logo'] = $this->model_tool_image->resize(html_entity_decode($this->config->get('config_logo'), ENT_QUOTES, 'UTF-8'), $this->config->get('theme_default_image_location_width'), $this->config->get('theme_default_image_cart_height'));

		} else {

			$data['logo'] = '';

		}

with:

$this->load->model('tool/image');

$this->load->model('setting/setting');

$logo = $this->model_setting_setting->getSettingValue('config_logo', $order_info['store_id']);
		
if (is_file(DIR_IMAGE . html_entity_decode($logo, ENT_QUOTES, 'UTF-8'))) {
	$data['logo'] = $logo;
} elseif (is_file(DIR_IMAGE . html_entity_decode($this->config->get('config_logo'), ENT_QUOTES, 'UTF-8'))) {
	$data['logo'] = $this->config->get('config_logo');
}

Then, remove the 2nd instance of:

`$this->load->model('setting/setting');`

**Comment by danielkerr** [comment]
doing all of them now
