### ISSUE TITLE
Upload List under System Maintenance tab is empty

### ISSUE THREAD

**Issue by selotoprak** [opencart/opencart#7435]
**What version of OpenCart are you reporting this for?**
Version 3.0.3.2
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Creating downloads in the backend does not show in the Upload List under Maintenance tab.
**To Reproduce**
and add a download
System Maintenance Uploads
Upload List
The list is still empty even though I have added downloadable file to downloads.

**Comment by osworx** [comment]
Well, this menu item will never show your downloads.
This is for files users have uploaded (during the checkout for example).

**Comment by selotoprak** [comment]
oh ok, so sorr. You are right the uploads from the customers.
