### ISSUE TITLE
Admin>Design>Theme Editor "Select a Template" Loads original unmodified twigs, *not* user modified versions. Either a bug or bad UI choice that has been causing confusion for years.

### ISSUE THREAD

**Issue by Kerr1** [opencart/opencart#7437]
3.0.3.2

Opencart "Theme Editor" "Choose A Template" menu loads the default templates, NOT the ones that have been modified. 

1. Go to Admin>Design>Theme Editor>
2. Select a twig from under the "Choose a Template", Modify it, save.
3. The website will be updated to reflect the change BUT
4. Return to the theme editor, Select the exact same twig the EXACT* same way...
5. The original default twig will load, NOT the version that you had modified.
6. If you now click "Save" the version that had been modified will be overwritten....

*Selecting the twig thru the "Theme History" list will correctly load your modified twig. Ignore the theme history section as it isn't the issue.

**Expected behavior**
Pretty much every new user, including myself, expects the modified twig to load when selected from the "Select A Template" menu - NOT the unmodified original. This is particularly bad because... you can easily overwrite your modified twigs by accident. 

I've run into dozens of posts all over the internet of people pulling their hair out over this issue while I was trying to figure out wtf was happening to me. 

People are being told things from "Clear your cache" (Which doesn't modify the way the "Choose a template" menu functions) or "Just don't use the theme editor, it's broken and everyone knows it" to "Why you shouldn't use OpenCart"...  in these forum posts, blog posts, and bug reports.

The "Theme History" portion, which is basically an unordered list of which files have been modified, loads the modified version of the twigs. This is really crappy UX, as if you start modifying large numbers of twigs this section will be difficult to search; difficult to know if you should open it from here or from "Select a template".

**Screenshots / Screen recordings**
I don't really think it's necessary, and dont have the time.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
Web Server, Manual Install
 - Operating system
centos, according to hostgator
 - PHP version 7.2.X

 - Apache version
not sure
 - Browser(s) tested with [e.g. chrome, safari - if applicable]
firefox, chrome, firefox mobile, chrome mobile

**Additional context**
Seriously, Google "Opencart Theme Editor not working" and almost every result will be someone who was unlucky enough to not realize "Select a Template" Doesn't load YOUR modified twigs, only the default twigs.

Suggested Fix:
Change the "Choose A Template" menu to load the user modified twigs instead of the theme default twigs. There is already a "Reset" button that lets you get the original twigs back if you want them.
OR
At very least add a hint/info bubble or notice to the "Choose a template" menu notifying the user of how this this functions - That you only use this menu the first time you modify a twig, then the theme history thereafter.

**Comment by MrPlow254** [comment]
This either was fixed since 3.0.3.2 or I don't follow what you are saying. It creates an item in the theme editor list that has the changes made. So this works in the current build.

![image](https://user-images.githubusercontent.com/1266825/57864531-0acfcb00-77ca-11e9-81e0-a7a7c7e15441.png)
![image](https://user-images.githubusercontent.com/1266825/57864553-17542380-77ca-11e9-964d-4927868937ad.png)
![image](https://user-images.githubusercontent.com/1266825/57864579-220eb880-77ca-11e9-9525-f832a8131d91.png)

**Comment by Kerr1** [comment]
Ignore the item under "Theme History"

Go back to the "Choose a template" List on the left, navigate the the same twig that way again.

When you do that, you get the original, unmodified twig again. This is, at least for myself and other frustrated internet people, confusing. 

Why is it that when you navigate to the twig on the "Choose a template" section on the left you are not shown the current, modified version?

**Comment by MrPlow254** [comment]
I personally never thought of it that way. I see what you are saying now.

**Comment by Kerr1** [comment]
Also, "Theme History" sounds like "Here is a convenient list of files that were recently edited" NOT "Here is the one and only way to access your edited twigs"

**Comment by danielkerr** [comment]
this must be fixable now we added the code arg to the template render. you only need to set an event to run last to modifiy the code argument.

**Comment by xseon** [comment]
I think there's one more issue here: when you have modified a template file like this you can not apply an ocmod modification to it as well - ocmod doesn't load on it.

**Comment by danielkerr** [comment]
ocmod is gone in master events only.
