### ISSUE TITLE
[Master Branch] - catalog/model/extension/shipping/ups.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7438]
As per Qphoria: https://forum.opencart.com/viewtopic.php?f=190&t=201530#p755227 .

**Comment by danielkerr** [comment]
as a quick solution i think UPS have uploaded the UPS extension for free with lots more features.

**Comment by straightlight** [comment]
Will their package be integrated as an extension module or OC users must download the new UPS package from their merchant's account?

**Comment by calexil** [comment]
this fix is not working in 3.0.3.2

**Comment by ADDCreative** [comment]
The official UPS extension only works for Poland according to the description.

There are already about 4-5 pull requests for this.
https://github.com/opencart/opencart/pull/6869
