### ISSUE TITLE
Version 3.0.3.2 bug on installation

### ISSUE THREAD

**Issue by danelsan** [opencart/opencart#7439]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
On Install give errors of installation
But this is fix into master repository development

http://127.0.0.1/install/index.php

Warning: require(/var/www/html/system/storage/vendor/composer/../react/promise/src/functions_include.php): failed to open stream: No such file or directory in /var/www/html/system/storage/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/html/system/storage/vendor/composer/../react/promise/src/functions_include.php' (include_path='.:/usr/local/lib/php') in /var/www/html/system/storage/vendor/composer/autoload_real.php on line 66

**Comment by danielkerr** [comment]
for the master you need to install composer otherwise you can download the latest stable branch from 3.xx maintaince.

**Comment by ashen780dimo** [comment]
i had the same issue. i just remove the `C:\xampp\htdocs\opencart\opencart-3.0.3.6\upload\system\storage\vendor` folder and `composer install` at here `C:\xampp\htdocs\opencart\opencart-3.0.3.6`

**Comment by Mahmood-Hussain** [comment]
Hello, I followed it and it worked for me thank you. I have another issue I am not able to login to the admin panel it shows "No match for Username and/or Password." my opencart version is 3.0.3.6
