### ISSUE TITLE
[Master Branch] - admin/view/template/localisation/location_list.twig

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7442]
`<td class="text-center" colspan="6">{{ text_no_results }}</td>`

It's set to 6 but there are fewer TDs on the above of that file ...

**Comment by straightlight** [comment]
In admin/controller/localisation/location.php file, in the getList() method, the:

`$data['location']` should be changed to:

`$data['locations']`

In admin/view/template/localisation/location_list.twig file,

{% if location %}
                {% for locations in location %}
                <tr>
                  <td class="text-center">{% if locations.location_id in selected %}
                    <input type="checkbox" name="selected[]" value="{{ locations.location_id }}" checked="checked" />
                    {% else %}
                    <input type="checkbox" name="selected[]" value="{{ locations.location_id }}" />
                    {% endif %}</td>
                  <td class="text-left">{{ locations.name }}</td>
                  <td class="text-left">{{ locations.address }}</td>
				  <td class="text-left">{{ locations
                  <td class="text-right"><a href="{{ locations.edit }}" data-toggle="tooltip" title="{{ button_edit }}" class="btn btn-primary"><i class="fa fa-pencil"></i></a></td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                  <td class="text-center" colspan="6">{{ text_no_results }}</td>
                </tr>
                {% endif %}

should be reversed to:

{% if locations %}
                {% for location in locations %}
                <tr>
                  <td class="text-center">{% if location.location_id in selected %}
                    <input type="checkbox" name="selected[]" value="{{ location.location_id }}" checked="checked" />
                    {% else %}
                    <input type="checkbox" name="selected[]" value="{{ location.location_id }}" />
                    {% endif %}</td>
                  <td class="text-left">{{ location.name }}</td>
                  <td class="text-left">{{ location.address }}</td>
                  <td class="text-right"><a href="{{ location.edit }}" data-toggle="tooltip" title="{{ button_edit }}" class="btn btn-primary"><i class="fa fa-pencil"></i></a></td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                  <td class="text-center" colspan="6">{{ text_no_results }}</td>
                </tr>
                {% endif %}

**Comment by condor2** [comment]
@jeffreyeng-opencart

You forgot to change this line `{% if locations.location_id in selected %}` to `{% if location.location_id in selected %}`

**Comment by jeffreyeng-opencart** [comment]
@condor2: Good catch. Thanks!
