### ISSUE TITLE
[Master Branch] - name="name"

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7444]
The following locations:

- admin/view/template/catalog/manufacturer_form.twig
- admin/view/template/design/banner_form.twig
- admin/view/template/design/layout_form.twig
- admin/view/template/localisation/country_form.twig
- admin/view/template/localisation/geo_zone_form.twig
- admin/view/template/localisation/language_form.twig
- admin/view/template/localisation/tax_rate_form.twig
- admin/view/template/localisation/zone_form.twig
- admin/view/template/marketing/coupon_form.twig
- admin/view/template/marketing/marketing_form.twig
- admin/view/template/user/user_group_form.twig
- admin/view/template/extension/module/banner.twig
- admin/view/template/extension/module/bestseller.twig
- admin/view/template/extension/module/carousel.twig
- admin/view/template/extension/module/featured.twig
- admin/view/template/extension/module/html.twig
- admin/view/template/extension/module/latest.twig
- admin/view/template/extension/module/slideshow.twig
- admin/view/template/extension/module/special.twig
- admin/view/template/extension/openbay/ebay_new.twig
- admin/view/template/extension/openbay/ebay_profile_form_generic.twig
- admin/view/template/extension/openbay/ebay_profile_form_returns.twig
- admin/view/template/extension/openbay/ebay_profile_form_shipping.twig
- admin/view/template/extension/openbay/ebay_profile_form_template.twig
- admin/view/template/extension/openbay/ebay_template_form.twig

contains: `name="name"` the convention as the value cannot be used as the same as the attribute name with: 'name' . OC forum users reported this issue with a popup returning a: .user.ini file. I was able to reproduce the issue as these conventions must be renamed. I have renamed one of them to another name as the value, the popup no longer appears.

**Comment by danielkerr** [comment]
you need to show me a working example of this.

**Comment by straightlight** [comment]
Of course I have a working example; Google Chrome. Other browsers doesn't seem to happen but this input name obviously hasn't been tested with crossed-browser.

![user_ini](https://user-images.githubusercontent.com/32371528/59515108-58545c00-8e8c-11e9-8cb0-8ab592cd485d.png)

**Comment by danielkerr** [comment]
there is no auto complete on the layout.

**Comment by straightlight** [comment]
My point exactly. Which is why I am reporting this since it appears anyways despite if there are no auto-complete feature on it. Only happening on Google Chrome, so far, but if you change the input name, this box won't appear neither with an non-relative name. This is an issue.

**Comment by danijelGombac** [comment]
@straightlight I can't reproduce this issue on Google Chrome.

**Comment by straightlight** [comment]
As I said, there are users who have reported this issue on the forum and even I was able to reproduce it on-the-fly which means, right there, if by changing the input="name" to something no longer shows the auto-complete, then there's an issue right there (fresh install, obviously).

**Comment by danielkerr** [comment]
there is no autocomplete on the layout page.

**Comment by straightlight** [comment]
Yes, you said that already and I did say that it was the point of my commit. There are no autocomplete feature built-in for any of the TWIG  files I posted on the above but they shows anyways when using input name="name" and when using Google Chrome.

**Comment by danielkerr** [comment]
you are using googles built in auto complete. it does not allow you to download anything.

come on your a coder. you should be able to check what js is being called or not.

**Comment by straightlight** [comment]
How is that relative to when I am changing the input name="name" to something else, the popup doesn't show? The autocomplete is a totally separate thing and you just assume that by closing the commit, it is about the autocomplete on the browser. Again, when changing to a different input name, this issue does not occur.

**Comment by danielkerr** [comment]
because the google auto complete is looking for fields like name, firstname, lastname, email etc.. oif you use the name .user.ini it just means that value is srtored in google chrome. maybe adding autocomplete="off" might sufis. also do you know ho many scripts out there use the word name="name"? its probabaly the most common field after email.

**Comment by straightlight** [comment]
Yes, I am aware on how many scripts uses the name="name" and, in fact, I am starting to believe that Google Developers needs to review this. While this issue may not entirely be relative to OC, however, the platform, meanwhile, should not use this common name as described especially if you have the autocomplete on and even wonder if by putting off would resolve the issue completely since, again, by changing its convention name to a totally different name in the input, despite the autocomplete, the issue vanishes period.

**Comment by danielkerr** [comment]
not doing it. its only your opinion.

**Comment by straightlight** [comment]
Have it your way. Closing the topic was also your call and not mine. While the topic remains closed, it will still be useful for future users who will encounter the same issue and report it.
