### ISSUE TITLE
Can't save klarna payment

### ISSUE THREAD

**Issue by Erikas013** [opencart/opencart#7446]
**What version of OpenCart are you reporting this for?**
3.0.2.0
**Describe the bug**
I can't save klarna module, its always show " Warning: Please check the form carefully for errors!" but all is fill.
I see fix in https://github.com/opencart/opencart/issues/6014 but cant download it. 404 error

**Comment by straightlight** [comment]
Daniel has already referenced the commit regarding this fix.

**Comment by straightlight** [comment]
Closure note: Already referenced to fix the issue. Closing commit.
