### ISSUE TITLE
Secure Trading payment module - allowing customer access to sensitive response information

### ISSUE THREAD

**Issue by eilianST** [opencart/opencart#7447]
**What version of OpenCart are you reporting this for?**
ALL (Bug raised by merchants using Opencart 3.0.2.0)

**Describe the bug**
It has been brought to our attention from a merchant when a customer choose to pay using SecureTrading via Opencart they are sent the (Postcode Check, CVV2 check and address check) as order history information which is not something that should be being passed back to the customer, as this is sensitive information only to be displayed to the merchant.

**Expected behavior**
The customer should not be able to see the the results of these checks on their order history.

Please see attached example screenshots where this issue is occurring.

We have been informed when this was raised via Opencart support, the following:

> This can be fixed by altering the addorderhistory call in the securetrading extension. Just add one order history to notify the customer the order is complete and another without the notify var to include the credit card security results. This is actually what I'm paying you guys for. To login to customers sites to fix these sort if issues.

![AVS and CVV2 returned to customer](https://user-images.githubusercontent.com/50827758/58014418-af1a8000-7af0-11e9-9201-a5e1f830421e.png)

Please let me know when you have investigated and resolved this issue.

If you require any additional information, please let me know,

Kind regards,

Eilian Jones
Technical Specialist

T +44 (0)1248 672 013
F +44 (0)1248 672 099
 
    
SECURE TRADING Ltd | 19th Floor | 40 Bank Street | Canary Wharf | London | E14 5NR | UNITED KINGDOM
This e-mail is from a Secure Trading Group company. The e-mail and any files transmitted with it may be confidential and are intended solely for the individual entity or entities to whom they are addressed. If you have received the e-mail in error, please notify enquiries@securetrading.com or telephone +44 (0)1248 672000, and destroy the original. If you are not the intended recipient, any disclosure, copying, distribution, or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.
Registered in the United Kingdom   Reg. No. 4586150   Reg. Address: 19th Floor, 40 Bank Street, Canary Wharf, London, E14 5NR, United Kingdom.

**Comment by straightlight** [comment]
The comments for the order histories have been removed from the catalog-end side in OC v3.0.3.2. However, the catalog/controller/account/order.php file still shows the comment field. This may need to be worked on since the comments are alo viewable with the master branch.

**Comment by eilianST** [comment]
Thank you for the update. Are you able to advise which version(s) of Opencart will have this issue resolved.

**Comment by straightlight** [comment]
Other than 3rd party extensions, there are no official OC versions where this solution has been integrated yet.

**Comment by eilianST** [comment]
Can you confirm when this will likely get released onto an official OC release ?

**Comment by eilianST** [comment]
Is there any update on this query ?

**Comment by danielkerr** [comment]
externsion removed out of the core and will be in the opencart marketplace soon. itas an easy fix you just need to change the notify to false when it updates the order status
