### ISSUE TITLE
admin/controller/extension/extension/module.php

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7448]
**Unneeded code**
```
		// Create a new language container so we don't pollute the current one
		$language = new Language($this->config->get('config_language'));
```

**Comment by wazirsoft** [comment]
I think you need to add some description about what the issue is and if you are trying to fix a bug it would be better to first explain that bug?

**Comment by engwalid1971** [comment]
> I think you need to add some description about what the issue is and if you are trying to fix a bug it would be better to first explain that bug?

Edited, thank you .

**Comment by MrPlow254** [comment]
@engwalid1971 That didn't clarify anything lol. Add locations of the files you are referring to and why you believe it is unneeded. Give a detailed reasoning behind your comment. Saying its unneeded does nothing.

**Comment by MrPlow254** [comment]
REFER to #7449 this is now a repeat issue

**Comment by jeffreyeng-opencart** [comment]
Checked this php page. Don't see it. Probably removed. Closing this issue.
