### ISSUE TITLE
catalog/model/tool/image.php - resize vs case sensitivity on Windows

### ISSUE THREAD

**Issue by SelfMan** [opencart/opencart#7450]
Problem is present in version 3.0.3.1 and also in the current trunk (2019-05-21)

The first check does have case sensitivity problems where the whole method exits and no images are present on the site.
		if (!is_file(DIR_IMAGE . $filename) || substr(str_replace('\\', '/', realpath(DIR_IMAGE . $filename)), 0, strlen(DIR_IMAGE)) != str_replace('\\', '/', DIR_IMAGE)) {
			return;
		}
The issue can be easily reproduced. Remember windows is not case sensitive.
The site is located at D:\WWW\SomeSite.local but the DIR_IMAGE in config.php is set to
define('DIR_IMAGE', 'D:/www/somesite.local/image/');

The realpath() wont match the DIR_IMAGE because of case sensitivity even though on windows it does not matter.

The result of the problem is that when you load the site, there will be no error message nor a entry in the error log file, but the product images will be missing and the File manager will misbehave too.

 - Local development
 - Windows 7
 - PHP version 7.1.5
 - Apache version 2.4
 - Browser independant

**Comment by straightlight** [comment]
See if this fix resolves the issue: https://forum.opencart.com/viewtopic.php?f=190&t=164152#p625218 . Some tweaking to be done for v3.x releases but the case sensitivity fix should be included.

**Comment by SelfMan** [comment]
Hi strightlight,
That might solve some problems with new installations/new files but it does not help when you are upgrading a older OC installation and all the references are already in the database.
In my case it all happened after taking a installation from a linux server to my local developemnt enviroment, which is windows based. I was wondering why I dont see any images till I found the issue.

**Comment by ADDCreative** [comment]
There is a similar issue with Windows path. https://github.com/opencart/opencart/issues/7080

Changing the test to the code below should hep.
```php
if (!is_file(DIR_IMAGE . $filename) || str_replace('\\', '/', realpath(DIR_IMAGE) . '/' . $filename) !== str_replace('\\', '/', realpath(DIR_IMAGE . $filename))) {
```

**Comment by SelfMan** [comment]
@ADDCreative the solution you provided seem to be working just fine. So far I've seen, there are no side effects. Thank you.
P.S.> i've seen the #7080 but though that ithe whole problem is about the realpath() not returning the proper value on that particular server and I didn't read it to the end. My fault.
