### ISSUE TITLE
install/language/en-gb/common/column_left.php

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7452]
**Replace:**
`$_['text_ar']      		 = 'Aragonese';`
**With:**
`$_['text_an']      		 = 'Aragonese';`

**Comment by MrPlow254** [comment]
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by gnovaro** [comment]
I made a pull request for this
https://github.com/opencart/opencart/pull/7498
