### ISSUE TITLE
[Master Branch] - admin order invoice

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7454]
The invoice() method's array returns heavier loads of array keys than what the admin/view/template/sale/order_invoice.twig file (master branch included). Issue addressed issue for no customer telephone found: https://forum.opencart.com/viewtopic.php?f=202&t=211900&p=755834#p755834 . However, the array keys were not used in the TWIG file. Decoration purposes.

**Comment by danielkerr** [comment]
telephone is working. i think i fixed it.
