### ISSUE TITLE
Reward Points not substracted from customer total & order not showing up

### ISSUE THREAD

**Issue by RobineSavert** [opencart/opencart#7455]
**What version of OpenCart are you reporting this for?**
3.0.3.2
**Describe the bug**
My customer has 500 Reward Points. My customer buys a product that is on sale for 10 points. The item is now free. Customer makes purchase and is guided to the success page. 

The customer does not see the order in his order history (account). Reward points (10) are not substracted from his total (is still 500). 

The store owner doesn't get a notification that there is a new order. The owner does not see the order in the admin. 

Used different IP addresses to order and make a new customer account and the default order status is "Processing". Fraud Order Status (in Settings > Option) is set to "Canceled".

**To Reproduce**
1. Make a new customer or edit an existing one
2. Give this customer 500 Reward Points
3. Go to Catalog > Products and make one item worth 10 Reward Points (tab Reward Points on Edit in a product > Customer Group > Default > 10 points)
4. Save
5. Now log in to the store (not admin) and order the product with 10 Reward Points (the item should now be free) and checkout.
6. You should be guided to the success page.
7. There is no order on the Order history page in your account and no e-mail received about ordering a product. The customer still has 500 points
8. Log in as admin and check the dashboard, there is no new order.

**Expected behavior**
1. Customer should get a confirmation e-mail
2. Customer should see the order in the order history
3. Customers points should be substracted
4. Store owner should be notified of a new order
5. Store owner should see the order in the dashboard/admin/sales

**Screenshots / Screen recordings**
-

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - Windows 10
 - PHP version
 - Apache version
 - Google Chrome 
 - Version 74.0.3729.169

**Comment by RobineSavert** [comment]
Update: did a complete fresh install of OpenCart with new database etc. Not working.

**Comment by straightlight** [comment]
In your steps above, it has been indicated to login as a customer, not from an admin (good). However, it does not indicate if you did installed the total reward extension to handle the points since those points are being gathered from the customer_reward database table. If the calculated points are smaller than the total points that a customer used to have, then, obviously, the customer will not be able to use his points. 

In fact, the validation may, rather, end up in the fraud status as per the catalog;/model/extension/total/reward.php file indicates. Also take note that it is possible to unconfirm the total points during checkout / API since, again, the customer may not have enough points.

**Comment by straightlight** [comment]
One small issue that may be encountered, prior to the mySQL v8.0.4 release, is the description field being used as a reserved word as per their site describes: https://dev.mysql.com/doc/refman/8.0/en/keywords.html - 

`DESCRIPTION; added in 8.0.4 (nonreserved)`

In catalog/model/extension/total/reward.php file,

you could always replace the 'description' field with escaped description field ( ` ) as part of the troubleshooting.

**Comment by RobineSavert** [comment]
> However, it does not indicate if you did installed the total reward extension to handle the points since those points are being gathered from the customer_reward database table.

Thank you so much for your reply. Is there a total reward extension? What does this mean?

"Now log in to the store (not admin) and order the product with 10 Reward Points (the item should now be free) and checkout." With this, I mean login as a customer into your account (so on the front of the store).


> If the calculated points are smaller than the total points that a customer used to have, then, obviously, the customer will not be able to use his points.

I am not sure what you mean, the customer has 500 points to spend and buys an item worth 10 points.

**Comment by straightlight** [comment]
`Thank you so much for your reply. Is there a total reward extension? What does this mean?`

Admin - > extensions - > extensions - > total - > reward .

**Comment by RobineSavert** [comment]
Ah, I see it. It is enabled. 

What could be going wrong? I first thought it could be IP address related (both store owner and customer on the same machine), but I tried to order it with my iPhone and still no order visible in my account..

**Comment by straightlight** [comment]
Did you also configured your points in the module?

You could also add log entries within each IF / ELSEIF / ELSE statements of the catalog/model/extension/total/reward.php file until noticing which lines of the log entries will appear in your OC admin - > systems - > maintenance - > error logs page.

**Comment by RobineSavert** [comment]
> Did you also configured your points in the module?

I did exactly as described in the OP. I gave a customer 500 points to spend. I made a product 10 points to buy. The customer buys it and is directed to the success page. But his order is not in his account, he doesn't get an e-mail and his points are still 500 instead of 490. The store owner doesn't get a notification that there is a new order and the new order is not in the admin.



> You could also add log entries within each IF / ELSEIF / ELSE statements of the catalog/model/extension/total/reward.php file until noticing which lines of the log entries will appear in your OC admin - > systems - > maintenance - > error logs page.

Yes, I could try that, thank you. It might take me a long time, as I am not a PHP dev (my expertise is SASS/JS). Do you have the same problem, or is it just me? Could you reproduce?

**Comment by straightlight** [comment]
Since you are not a PHP dev, please post on the OC forum. GitHub is for developers only.

**Comment by straightlight** [comment]
Closure note: User needs to post these inquiries on the OC forum. Closing commit.
