### ISSUE TITLE
Opencart performance loss in combination with vQmod

### ISSUE THREAD

**Issue by MadMcJack** [opencart/opencart#7457]
When running the latest Opencart + vQmod in production within a week I noticed great performance loss when browsing the site.

Every action on the site resulted in a wait of 3-4 seconds. Having looked at the forum a lot of people seem to be having these problems with memory exhaustion or great performance loss with wait times up to 10-20 seconds.

It seems the **vqmod/checked.cache** file gets swamped with autoload.php entries:
`/FULL/PATH/OUTSIDE/PUBLIC/HTML/DIR/storage/vendor/autoload.php`
`/FULL/PATH/OUTSIDE/PUBLIC/HTML/DIR/storage/vendor/autoload.php`
`/FULL/PATH/OUTSIDE/PUBLIC/HTML/DIR/storage/vendor/autoload.php`

Removing the **vqmod/checked.cache** file instantly resolved the performance problems.

The issue has already been found:
https://github.com/vqmod/vqmod/issues/135

The vQmod admin gives this advice:

> There's no known issue with an ever growing checked.cache file while your system/storage folder is under public_html.
> 
> 1. EDIT: admin/controller/common/dashboard.php
> 2. FIND:
>    $data['security'] = $this->load->controller('common/security');
> 3. REPLACE WITH:
>    $data['security'] = '';

So, we're now in a situation where Opencart installation indicates that you move the storage directory outside of the web directory and the vQmod admin gives the **exact opposite** advice!

It think this is an important issue to address because installing Opencart and vQmod following the official documentation results -by default- in great performance loss!

**Comment by straightlight** [comment]
This incident request is for the OC forum or via Qphoria directly, not for this namespace. This namespace is to report the latest core issues with v3.0.3.2 that may be included on the GitHub files or the GitHub files as stand-alone. Please post on the OC forum for VQMod incidents.
