### ISSUE TITLE
sending GET values to load controller

### ISSUE THREAD

**Issue by rsuchovsky** [opencart/opencart#7458]
Hi, I know it doesn't belong here.
I would need one quick advice, I'll be happy if he can advise me.

**I wouldn't like to create duplicate codes, I'd like to create conditions based on the controller's sent values**

**This listing doesn't work:**

$data['my_module'] = $this->load->controller('extension/module/my_module?id=1&typ_id=1');
$data['my_module'] = $this->load->controller('extension/module/my_module?id=2&typ_id=2');

**Is something like this possible?**  **Or I have to make a copy and write it like this :(**

$data['my_module'] = $this->load->controller('extension/module/my_module/typ1');
$data['my_module'] = $this->load->controller('extension/module/my_module/typ2');

**Comment by osworx** [comment]
> This listing doesn't work:
> $data['my_module'] = $this->load->controller('extension/module/my_module?id=1&typ_id=1');

Because you have to send params as array, like:
`$data['my_module'] = $this->load->controller( 'extension/module/my_module', array( 'id' => 1, 'typ_id' => 1 ) );`

**Comment by rsuchovsky** [comment]
Thank you very much :)

**Comment by danielkerr** [comment]
i'm thiking of updating the system to use a prefix in the loaders to pick up modifcation files. so:

$this->load->controller('mymodule/account/edit');

event overides can change this to account/edit.

$this->load->model('mymodule/account');

$this->load->view('mymodule/account');
