### ISSUE TITLE
[v3.x and Master Branch] - catalog/model/design/layout.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7460]
Persistent issue reported about: getLayout() method in catalog/model/design/layout.php where the route field is reversed with the $route variable, especially since the route field is being re-ordered. The value cannot equal a field but only a field can equal a value.

**Comment by WebkulOpencart** [comment]
@straightlight, as we define the route in the layout from the admin like account/% so in this case field value, will not be equal to the value like account/account

so, there is no such issue
