### ISSUE TITLE
Insecure credentials

### ISSUE THREAD

**Issue by pedano** [opencart/opencart#7461]
I recently realized that the password is easily visible on OC 3.0.3.2 under the System->Settings->Mail page! Do you believe it is a good practice when I need to give an access to my Admin panel some developers to adjust Modules I purchased? Don't you have other way to hide it in order to keep us secure? I am happy the PayPal login is not accessible thru OC yet!!!

**Comment by osworx** [comment]
Then don't give them access to your settings.

**Comment by pedano** [comment]
how can I manage an access?

**Comment by osworx** [comment]
Menu > System >User >> Usergroups (permissions access & edit)
Menu > System >User >> User (usergroup)

Simply create a new customer group, give correct permissions.
Then create a new user and assign that usergroup.

And for further questions, please use the forum: https://forum.opencart.com/

**Comment by straightlight** [comment]
I just had this discussion with my support partner as I do agree. Accessing some of the data may be about confidentially leaks where only API users should be able to access those assets even though an OC admin may have read-only access.

**Comment by osworx** [comment]
> GDPR compliancy

Means always, if you give someone access and that person/company will have permissions also to personal data (no matter which), that person/company has to sign a contract before. 

The more it is important to know this person/company and who they are.
Not these guys with an Gmail address only!

Nevertheless, it would be a good idea to establish an 'support access' through an API.

**Comment by straightlight** [comment]
`Nevertheless, it would be a good idea to establish an 'support access' through an API.`

Correct. That is the whole idea.

@danielkerr: Considering this for the GDPR?

**Comment by engwalid1971** [comment]
@pedano:

To hide the SMTP Password field, you need to modify the file **admin/controller/setting/setting.php** 

**Notes:**
- The password will be shown as ***** but if the password changed it will be saved correctly.
- In all cases the password won't saved as *****

-----------------

**Insert:**
```
if (isset($this->request->post['config_mail_smtp_password']) && $this->request->post['config_mail_smtp_password'] == '*****') {
	$this->request->post['config_mail_smtp_password'] = $this->config->get('config_mail_smtp_password');
}
```
**After:**
`if (($this->request->server['REQUEST_METHOD'] == 'POST') && $this->validate()) {`

**Also replace:**
```
if (isset($this->request->post['config_mail_smtp_password'])) {
	$data['config_mail_smtp_password'] = $this->request->post['config_mail_smtp_password'];
} else {
	$data['config_mail_smtp_password'] = $this->config->get('config_mail_smtp_password');
}
```
**With:**
```
if (isset($this->request->post['config_mail_smtp_password'])) {
	$data['config_mail_smtp_password'] = $this->request->post['config_mail_smtp_password'];
} elseif ($this->config->has('config_mail_smtp_password')) {
	$data['config_mail_smtp_password'] = '*****';
} else {
	$data['config_mail_smtp_password'] = '';
}
```

**Comment by pedano** [comment]
Thanks to everybody! I used script from "engwalid1971" - it works exactly as it should be done by OC developers. Having permission assignment is a good idea too, will use it definitely.

**Comment by straightlight** [comment]
I would rather suggest the use of:

`if (isset($this->request->post['config_mail_smtp_password']) || $this->config->has('config_mail_smtp_password')) {`
        `$data['config_mail_smtp_password'] = '*****';`
`} else {`
	`$data['config_mail_smtp_password'] = '';`
`}`
