### ISSUE TITLE
Admin - incorrect pagination

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7462]
If you list a multiple pages and deleted all the rows on the last page, you will see the page like this

![Screenshot from 2019-05-29 05-13-12](https://user-images.githubusercontent.com/48407821/58552033-b852cd80-8211-11e9-997d-d4a70c91d5fc.png)

**Comment by straightlight** [comment]
For which OC version are you submitting this incident request for?

**Comment by engwalid1971** [comment]
I think all released have the same issue, not tested yet.

**Comment by engwalid1971** [comment]
@straightlight:

Tested on
v2.1.0.2
v2.3.0.2
v3.0.2.0
v3.0.3.2

**The same issue.**

**Comment by straightlight** [comment]
This issue has been discussed before on GitHub but the solution never got implemented officially. See if this solution works: https://github.com/opencart/opencart/pull/3617

**Comment by straightlight** [comment]
Also found this solution for manufacturer pagination fix: https://github.com/optimlab/opencart/commit/3acbf53c97b32029bec712e8f10a7be0cada1d9b . Perhaps this could also be a solution with what you've reported here.

**Comment by jeffreyeng-opencart** [comment]
Have this resolved?

**Comment by engwalid1971** [comment]
@jeffreyeng-opencart
Not resolved yet !!!

**Comment by engwalid1971** [comment]
@jeffreyeng-opencart

Steps to reproduce the behavior:
1. Goto the Customer Groups section
2. Add a new 11 Customer Groups
![Screenshot from 2019-10-31 13-26-14](https://user-images.githubusercontent.com/48407821/67943232-488ea780-fbe2-11e9-8e4b-4ad14ba4901d.png)
3. Goto page 2 and select the all Groups
![Screenshot from 2019-10-31 13-31-08](https://user-images.githubusercontent.com/48407821/67943662-2fd2c180-fbe3-11e9-8800-10f9a3bf9c47.png)
4. Delete the selected Groups and you will see the error
![Screenshot from 2019-10-31 13-35-10](https://user-images.githubusercontent.com/48407821/67943866-b2f41780-fbe3-11e9-8dcf-4eb6a956d0f3.png)

**Comment by jeffreyeng-opencart** [comment]
@engwalid1971: Tested and I see your point. I found where the problem is within the deleting feature, but I have to find a solution before implementing. I hard coded on my local machine, it works. I have to find another way, so it would not need to be hard coded. Also, affecting other pages as well.

**Comment by jeffreyeng-opencart** [comment]
@engwalid1971: Spoken to Daniel and we will do a full revamp of the pagination. For a short-term fix:

Within "public function delete()", search for "isset($this->request->get['page']" and modify from:
```
if (isset($this->request->get['page'])) {
	$url .= '&page=' . $this->request->get['page'];
}
```
to:
```
if (isset($this->request->get['page'])) {
	$customer_group_total = $this->model_customer_customer_group->getTotalCustomerGroups();
	if ($customer_group_total > $this->config->get('config_limit_admin')) {
		$url .= '&page=' . $this->request->get['page'];
	}
}
```
