### ISSUE TITLE
Image Manager New Folder function no work

### ISSUE THREAD

**Issue by CiaoPlus** [opencart/opencart#7464]
- Version: At revision: 12017

**Comment by straightlight** [comment]
What is the actual issue and are you reporting this issue for the master branch?

**Comment by CiaoPlus** [comment]
> What is the actual issue and are you reporting this issue for the master branch?
Yes, this issue for the master branch.
In admin file Manager can't add new Folder.
When click the Button “ New Folder” get a blank dropdown-menu.

**Comment by danielkerr** [comment]
not enough informatrion so im closing this.
