### ISSUE TITLE
banner_form.twig Can edit only first  language tab, other don't work.

### ISSUE THREAD

**Issue by CiaoPlus** [opencart/opencart#7466]
\admin\view\template\design\banner_form.twig

Can edit only first  language tab, other don't work.

 - Local development with win10
 - PHP version 7.2
 - Apache version 2.4
 - Browser(s) tested with chrome
 - Version master branch

**Comment by straightlight** [comment]
For which OC version are you reporting this issue?

**Comment by danielkerr** [comment]
dyou re using an old version

**Comment by CiaoPlus** [comment]
> dyou re using an old version

no, i use the Latest git version。

**Comment by CiaoPlus** [comment]
> > dyou re using an old version
> 
> no, i use the Latest git version。
The reason is that id="button-banner" is in the loop, multiple id="button-banner" appear in multiple languages, js only operates the first id="button-banner".

**Comment by CiaoPlus** [comment]
```
$('#button-banner').on('click', function() {
	var element = this;
```
To:
```
  function add_banner(lang_id) {
    var element = lang_id;
```

`<button type="button" id="button-banner" data-language="{{ language.language_id }}" data-toggle="tooltip" title="{{ button_banner_add }}" class="btn btn-primary"><i class="fas fa-plus-circle"></i></button>`

To:

`<button type="button" id="button-banner{{ language.language_id }}" data-language="{{ language.language_id }}" onclick="add_banner(this);" class="btn btn-primary"><i class="fas fa-plus-circle"></i></button>`

**Comment by straightlight** [comment]
In the context of Opencart with JS function names, I would change:

`function add_banner(lang_id) {`
`    var element = lang_id;`

to:

`function addBanner(language_id) {`
`    var element = language_id;`

and:

`<button type="button" id="button-banner{{ language.language_id }}" data-language="{{ language.language_id }}" onclick="add_banner(this);" class="btn btn-primary"><i class="fas fa-plus-circle"></i></button>`

to:

`<button type="button" id="button-banner{{ language.language_id }}" data-language="{{ language.language_id }}" onclick="addBanner(this);" class="btn btn-primary"><i class="fas fa-plus-circle"></i></button>`

An alternative approach would be to defined a:

`banner.add(this);`

the same way the cart is already handled from the store-front end.
