### ISSUE TITLE
Swiper pager selectors messed up

### ISSUE THREAD

**Issue by revington** [opencart/opencart#7470]
**What version of OpenCart are you reporting this for?**
3
**Describe the bug**
Swiper pager selectors are messed up. If you have more than one swiper instance on a page clicking one of the pagers acts on all swiper instances.

**To Reproduce**
1. Go to https://demo.opencart.com/
2. Click on the first carousel arrow
3. That click affects both swiper instances on the page

**Expected behavior**
Clicking on a swiper arrow should only affect that swiper instance

**Screenshots / Screen recordings**

![ezgif-2-83f6e5fdf4c7](https://user-images.githubusercontent.com/91995/58942436-0c176680-877e-11e9-9fe2-b8a11b43f94f.gif)

**Server / Test environment (please complete the following information):**
Tested on chrome + firefox

**Comment by pemaier** [comment]
Same problem here.

**Comment by HarishSTOnline** [comment]
https://demo.opencart.com/ Contains this bug!

**Comment by straightlight** [comment]
@revington: For which OC version are you reporting this issue particularly?

**Comment by revington** [comment]
AFAIK OpenCart v3.x is the only one with swiper

**Comment by jeffreyeng-opencart** [comment]
https://github.com/opencart/opencart/issues/7664
