### ISSUE TITLE
If statement seems to be redundant or incorrect

### ISSUE THREAD

**Issue by Kgombelian** [opencart/opencart#7471]
Hi,

I'm not sure if this is a bug or not, but in the file [/catalog/model/extension/total/coupon.php](https://github.com/opencart/opencart/blob/master/upload/catalog/model/extension/total/coupon.php) on line 168 there is an if statement which compares $discount_total with $total. 
```
if ($discount_total > $total) {
	$discount_total = $total;
}
```
I'm not sure this if statement is really needed nor if it's correct, because here the var $discount_total, which is a number, is compared with the var $total, which is an associative array, passed as an argument, consisting of three elements.
 If I'm correct the variable $total in this method always is an associative array existing of 3 elements: totals, taxes and total.
So probably this if statement should compare the $discount_total with the element $total['total'] or it could be removed because I couldn't produce a scenario which hitted true while the surrounding function getTotal($total) seems to work fine.

**Comment by danijelGombac** [comment]
@Kgombelian the code was changed. var $total is a number now.
