### ISSUE TITLE
Uncaught Error: Class 'Config' not found in Framework.php

### ISSUE THREAD

**Issue by WonWonDR** [opencart/opencart#7472]
I encountered this problem after uploading my opencart file into live server, specifically webhostapp

Fatal error: Uncaught Error: Class 'Config' not found in /storage/ssd4/145/9868145/public_html/system/framework.php:6 Stack trace: #0 /storage/ssd4/145/9868145/public_html/system/startup.php(104): require_once() #1 /storage/ssd4/145/9868145/public_html/index.php(19): start('catalog') #2 {main} thrown in /storage/ssd4/145/9868145/public_html/system/framework.php on line 6

**Comment by danielkerr** [comment]
reupload a ain

**Comment by sudhirpur123** [comment]
What is ain ?

**Comment by DanielHolland** [comment]
> What is ain ?

@sudhirpur123, he probably meant "again"
