### ISSUE TITLE
[v3.0.3.2 & Master Branch] - admin/controller/extension/extension/promotion.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7473]
`curl_setopt($curl, CURLOPT_URL, OPENCART_SERVER . 'index.php?route=api/promotion&type=' . substr($this->request->get['route'], strrpos($this->request->get['route'], '/') + 1));`

Decoration. The file doesn't exist in either package from catalog/controller/api folder for promotion.php file.

**Comment by danielkerr** [comment]
it connecting to a remote server.

**Comment by danielkerr** [comment]
the file is there. are u sure its not ad blocker.

**Comment by straightlight** [comment]
While the file might not in the master branch but might be only located on your remote server. By design, since OC users won't know what promotion.php file will be gathering from the API call, they should, at least, be informed in the comments above the cURL request what this API request and response do.

**Comment by danielkerr** [comment]
sure. its so i can display an ad. not collecting data apart the recording when people click the link.

**Comment by straightlight** [comment]
Then, perhaps adding that note in there so to notify the people that this is the case since, right now, there's nothing that informs the people other than the words being described on your reply above about it.
