### ISSUE TITLE
[v3.0.3.2 & Master Branch] - oc_user table

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7474]
Contains 'image' field but is mandatory. However, admin/controller/user/user.php file's validateForm() method does not implicit that requirement to the user which can prevent top administrator users or authorized access users to add other users.

This issue has been addressed before on the forum and remembering having conversations on Github last season about users being unable to add other users. This may be the root cause.

**Comment by danielkerr** [comment]
we have a profile page and top admin users can set to allow sub users to access the user section

**Comment by danielkerr** [comment]
there is no mandatory image field!
