### ISSUE TITLE
Current Authorize.Net solution is Deprecated

### ISSUE THREAD

**Issue by ocdevops** [opencart/opencart#7475]
**What version of OpenCart are you reporting this for?**
All versions
**Describe the bug**
Current Authorize.Net solution is Deprecated
https://developer.authorize.net/api/upgrade_guide/

Will you update the current solution? Do you have any info how long can we use the current solution?

Thank you.

**Comment by falconkirtaran** [comment]
I actually put in a PR to use one of their new methods, #7465.  I'm hoping Daniel adds it to the next release, but if you wanted to apply the patch I bet you it would work.  The method I implemented is accept suite hosted.

**Comment by danielkerr** [comment]
whats going on with Authorize.Net? have the becaome global payments. if so i think i recieved an email recently

**Comment by falconkirtaran** [comment]
No, they're different, but you can use global payments merchant accounts through authorize.net if you want I think.  They have their own API.  Possibly, I could create a similar plugin for them too; also considering writing one for TSYS and one for stripe.

**Comment by danielkerr** [comment]
I contacted Authorize.Net. See if we can get them to do pay for the work or do it themselves.

**Comment by falconkirtaran** [comment]
I already wrote an integration... it was pretty easy and took an afternoon.  The PR is above.On Jun 13, 2019 07:12, Daniel Kerr <notifications@github.com> wrote:I contacted Authorize.Net. See if we can get them to do pay for the work or do it themselves.

**Comment by TheRealDJ** [comment]
Has anyone been able to get the current SIM module working? Looking at the code, I don't think it ever worked since SHA512 hashing has been required. Using v3.0.3.2. If this is the case, I fixed it, then I guess I'll have to form, fix, commit, then submit a pull request.

**Comment by TheRealDJ** [comment]
End of service date has not yet been announced for AIM or SIM.

**Comment by falconkirtaran** [comment]
My test credentials didn't work with SIM, so I left it alone.

**Comment by TheRealDJ** [comment]
That's because the hash function is wrong. I created an OCMOD to fix the hash, and add test mode functionality. There is nothing in the code to use the test URL. I'll send you my OCMOD.

**Comment by TheRealDJ** [comment]
Here is an overview of what I have done ... 
[authnet_sim_fix.ocmod.zip](https://github.com/opencart/opencart/files/3297599/authnet_sim_fix.ocmod.zip)

catalog/controller/extension/payment/authorizenet_sim.php
-Added x_post_url set based on "test mode" setting
-Added oc_session_id, oc_customer_id, oc_store_id, and oc_store_url fields to be used by twig

catalog/view/theme/*/template/extension/payment/authorizenet_sim.twig
-Change hard coded URL to {{ x_post_url }}
-Added oc_session_id, oc_customer_id, oc_store_id, and oc_store_url fields to submit form

**Comment by TheRealDJ** [comment]
The payment_authorizenet_sim_hash name is misleading also ... I guess it should be changed to payment_authorizenet_sim_sig_key or something like that. I didn't do it because I figured I'd break things.

**Comment by falconkirtaran** [comment]
Did you want me to make a PR to update the plugin with those changes?  I could, if you don't want to send your own.

**Comment by TheRealDJ** [comment]
I don't mind, but it'll be my first. May need some hand holding. Not to be taken out of context :)

**Comment by falconkirtaran** [comment]
Well go ahead and send one and I can take a look :)

Keep in mind though that like... I have put in 8 since January and only one has been merged, and the rest are still pending.

**Comment by TheRealDJ** [comment]
Yep ... I have to update my hash call to remove the generateHash call, and wrap params in html_entity_decode. Im gonna install the master, test my OCMOD, and take it from there.

**Comment by TheRealDJ** [comment]
Well, I did it. Only created a branch I needed to destroy once. Couldn't squash the commits the first time. Pull request https://github.com/opencart/opencart/pull/7488. Take a look when you have a chance and let me know.

Thanks.
DJ

**Comment by TheRealDJ** [comment]
I still have some work to do.

**Comment by TheRealDJ** [comment]
Ok, its working. Didn't realize until after my first commit that the sig field had been renamed in the backend to md5. I changed all the md5 references to sig_key. Sorry about the multiple commits.

**Comment by straightlight** [comment]
Update provided by a forum user regarding Authorize.net latest news update for 2020: https://forum.opencart.com/viewtopic.php?f=10&t=215620

**Comment by danielkerr** [comment]
externsion removed out of the core and will be in the opencart marketplace soon.
