### ISSUE TITLE
Currency rate update error handling

### ISSUE THREAD

**Issue by chief-kh** [opencart/opencart#7476]
**What version of OpenCart are you reporting this for?**
3.0.3.2
**Describe the bug**
File: admin/model/localisation/currency.php
Method: refresh($force = false)
Lines: #130..134
There is no any error handling on curl request. I'm behind proxy and http://download.finance.yahoo.com/d/quotes.csv is unavailable but opencart spamming with devision by zero warnings only.

**To Reproduce**
1. Make http://download.finance.yahoo.com/d/quotes.csv unavailable by changing ns record in hosts file or by disabling internet connection.
2. Go to admin area 
3. Check out 
Warning: Division by zero in D:\xampp56\htdocs\oc3032\admin\model\localisation\currency.php on line 141

**Expected behavior**
alert with correct warning of unavailability of yahoo host.

**Screenshots / Screen recordings**
https://screenshot.net/rwyy5s9

**Server / Test environment (please complete the following information):**
 - Local development
 - Operating system Windows 10
 - PHP version 5.6
 - Apache version 2.4.38
 - Browser(s) tested with firefox
 - Version 67.0.1

**Additional context**

**Comment by danielkerr** [comment]
u can didable it in settings. i have already fixed this in the master branch

**Comment by straightlight** [comment]
Closure notes: danielkerr confirms issue has already been fixed in the master branch as compared to OC v3.0.3.2 release reported by OP.
