### ISSUE TITLE
[3.0.3.2 a. master] Product page - Related products shown as often as products are involved

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#7477]
**Situation**: If you have e.g. related products you enter this information in the product adminitration into the field related products at each product.

**Problem**: At the frontend (catalg) Product page you see the products in the related products list several times. 

**Solution**: May it is required to filter (in the sql-query) the related product list i a way that each product is only on time in the list.

**Comment by danielkerr** [comment]
yep. you want to do a pull request for this? maybe its an issue with the porduct varaint system im adding

**Comment by straightlight** [comment]
In the array of the getProductRelated method: `$product_data[$result['related_id']] = $this->getProduct($result['related_id']);` , isn't that unique already? Since the `$result['related_id']` is not being incremented with indexes but rather regrouped individually by its associated product ID ...

**Comment by danielkerr** [comment]
I need to work on the subscription system for opencart cloud. it should taske me about a week. The next version is nearly ready.

**Comment by danielkerr** [comment]
thers no issue i can find here.
