### ISSUE TITLE
Text_sub_category on developemennt

### ISSUE THREAD

**Issue by danelsan** [opencart/opencart#7478]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
Into versione on development 3.1.0.0b when i search a product not compare
the text:
- Search in subcategories
- Search in product descriptions

**To Reproduce**
Search a product 

**Expected behavior**
Right text of this checkbox

**Comment by danielkerr** [comment]
i can not find this issue. its all there for me.

**Comment by danielkerr** [comment]
maybe translation files missing an entry.
