### ISSUE TITLE
Cannot add Unicode icons to Order history comments.

### ISSUE THREAD

**Issue by machadoug** [opencart/opencart#7479]
**What version of OpenCart are you reporting this for?**
3.0.3.1

**Describe the bug**
I cannot add Unicode chars (icons) to Order History Comments. The message is cutting everything after the Unicode icon when I press the _Add History_ button.

What section does it affect?
/admin/index.php?route=sale/order/info&user_token={token}&order_id={number}

**To Reproduce**
1. Go to Orders
2. Edit an order
3. Scroll down to "Add history"
4. Add Unicode chars such as 💡 and 🚚 
5. Click on the Add History button and then you'll see the comment will be cut off.

**Server / Test environment (please complete the following information):**
 - Website on a live server
 - Operating system: CentOS
 - PHP version 7.1
 - Apache

**Comment by straightlight** [comment]
Reporting for v3.0.3.1 release. Can you also reproduce the issue based on the master branch release?

**Comment by ilcomp** [comment]
Requires transition from utf8 to utf8mb4 (mysql)
