### ISSUE TITLE
3.0.3.2  admin sales list - filter box order status dropdown shows incomplete list, random results

### ISSUE THREAD

**Issue by soundzgood** [opencart/opencart#7482]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
Not all order statuses are showing in dropdown filter (Order Status) in filter box on right, affects which orders are displayed on left. Select same order status repeatedly and results on left will be random.

What section does it affect?
Admin > Sales > Orders List 

**To Reproduce**
1. Go to Admin > Sales > Orders
2. Click on Order Status dropdown in Filter box on right
3. Shows some of the Order Statuses (missing orders plus 5) - we have 12 in total
4. Also select same order status from dropdown (other than blank or missing orders) and resulting list of orders on left will change randomly each time you click Filter button

**Expected behavior**
Should see all order statuses in dropdown as per setting in Setting > Localisation > Order Statuses
Same result each time when same order status selected after clicking Filter button

**Server / Test environment (please complete the following information):**
 - web server (debian linux 8)
 - PHP version (7.1)
 - Apache version (2.2)
 - Browser(s) tested (chrome 74)

**Comment by soundzgood** [comment]
extension conflict ... apologies

**Comment by simone918** [comment]
I also have problems with showing all orderstatus to filter from dropdownbox. (showing 4 out of 14)
Use OC 3.0.2 and journal3 theme, where can I find this problem?
