### ISSUE TITLE
Reset Password not working

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7489]
**What version of OpenCart are you reporting this for?**

2.2.0.0

**Describe the bug**
Password reset not working due to pass the wrong parameter in the catalog/controller/account/reset.php

From

`$this->model_account_customer->editPassword($customer_info['customer_id'], $this->request->post['password']);`

To
 `$this->model_account_customer->editPassword($customer_info['email'], $this->request->post['password']);`

And Also change in the customer model as well for the same.

**Comment by straightlight** [comment]
Reporting an old OC version issue.
