### ISSUE TITLE
Extension Category missing translation - Opencart 3.0.3.2 and Master

### ISSUE THREAD

**Issue by trueliarx** [opencart/opencart#7491]
**What version of OpenCart are you reporting this for?**
Master 3.1.0.0_b, 3.0.3.2, 3.0.3.1

**Describe the bug**
In the marketplace/extension manager appears an entry with "heading_title".
The problem is related to the fact that the "extension/extension/promotion.php" exists but has no translation file. During a fresh installation the problme doesn't appear just because there's no access permission for the promotion extension category.

**To Reproduce**
1. In the admin area go to System->Users->User Groups
2. Edit the Administrators user Group and assign all the access/modify permissions. 
2. Go to Extensions->Extensions (marketplace/extension) and in the dropdown menu you will be able to see the "heading_title" entry

**Expected behavior**
The "promotion" category available and with a en-gb translation file.

**Screenshots / Screen recordings**
![screen](https://i.ibb.co/GpgR19w/Immagine.png)

**Server / Test environment (please complete the following information):**
 - Local development
 - windows/linux
 - PHP 7.3
-any

**Solution**

add the file in /admin/language/en-gb/extension/extension/promotion.php
with the following code (or sort of)
```

<?php
// Heading
$_['heading_title']    = 'Promotions';

// Text
$_['text_success']     = 'Success: You have modified promotions!';
$_['text_list']        = 'Promotions';

// Column
$_['column_name']      = 'Promotion Name';
$_['column_status']    = 'Status';
$_['column_action']    = 'Action';

// Error
$_['error_permission'] = 'Warning: You do not have permission to modify promotions!';
```

Modify the Administrator group in /install/opencart.sql

`(1, 'Administrator', '{"access":[... "extension\\/extension\\/promotion", ... ]}'),`

**Comment by straightlight** [comment]
I did noticed that issue on a latest custom job integration assignment for a client recently ... I too did saw the heading_title on that list with OC v3.0.3.2 release.

**Comment by straightlight** [comment]
Not sure why the user groups needs to be modified with `\\/` instead of: `\/` though. Using `\/` still works fine for me aside from the language promotion instructions you posted above ...

**Comment by NickR2021** [comment]
I fix the promotion.php  by adding the file back as stated in this post [(https://github.com/opencart/opencart/pull/7570)]
