### ISSUE TITLE
Notice: Undefined index: customer_group_id in /catalog/controller/mail/affiliate.php on line 17

### ISSUE THREAD

**Issue by ddac84** [opencart/opencart#7492]
When an affiliate registers and these errors come up. 
It was a fresh install last year so can only assume it has been doing it since but was only informed a few weeks ago. I have looked on git but couldn't find anything that worked. I am using 3.0.2.0 
Undefined index: customer_group_id in /catalog/controller/mail/affiliate.php on line 17
			`$customer_group_id = $args[1]['customer_group_id'];`

Undefined index: customer_group_id in /catalog/controller/mail/affiliate.php on line 73
			`$customer_group_id = $args[1]['customer_group_id'];`

Cannot modify header information - headers already sent by (output started at /catalog/controller/startup/error.php:34)
`echo '<b>' . $error . '</b>: ' . $message . ' in <b>' . $file . '</b> on line <b>' . $line . '</b>';`

in /system/library/response.php on line 36
	`header('Location: ' . str_replace(array('&amp;', "\n", "\r"), array('&', '', ''), $url), true, $status); `
any help appreciated.

**Comment by straightlight** [comment]
Empty template information. Subject line filled only.

**Comment by straightlight** [comment]
The master branch on line 17 has changed which means you are reporting an issue that is no longer relevant to the master branch. Please remain on the forum to address those issues. You could also recompare the master branch's version with v3.0.2.0 release and see if that will resolved the issue.

**Comment by straightlight** [comment]
Closure notes: Master branch contains changed codes. Closing commit since this issue has already been solved.

**Comment by mattleexxx** [comment]
Hi, 
I am facing this issue. May I know how to solve the problem?

**Comment by mhcwebdesign** [comment]
> Hi, I am facing this issue. May I know how to solve the problem?

This was solved 5 years ago, use OpenCart 3.0.4.0. And use the OpenCart forum for community support.
