### ISSUE TITLE
"Print Shipping List" feature doesn't work on Google Chrome 75.0.3770.100 (Official Build)

### ISSUE THREAD

**Issue by stasdrvn** [opencart/opencart#7493]
Opencart version: Opencart  2.0.1.1

Bug description: When you click the button to print the shipping klist in Sales -> Orders page the page will reload.

1. Check if your Google browser version is 75.0.3770.100
2. Go to "Sales -> Orders" in your admin panel.
3. Check order's checkbox and click the "Print shipping List" button in the top right corner.
4. See the bug

Expected behavior:
The shipping list should be printed.

Server / Test environment (please complete the following information):
 - Local development
 - Windows 7
 - PHP 5.6
 - Apache 2.4
 - Google Chrome
 - 75

Additional context:
It seems that Google removed "formaction" from html support.

**Comment by straightlight** [comment]
Reporting about an old OC version. Please submit your request on the forum first.

**Comment by schiggi** [comment]
Related to the popup blocker in Chrome. Don't know exactly, what they have changed in Chrome exactly.
Exists also with OC 3.0.1.1 however it redirect eventually.

**Comment by i3kevin** [comment]
This happened to me as well after Chrome auto update.

**Comment by stasdrvn** [comment]
> Reporting about an old OC version.

Then why was I asked about the version?

**Comment by i3kevin** [comment]
same issue here. my version is 2.3.0.2.

**Comment by Nysith** [comment]
Had the same issue in 3.0.2.0.

Solved it by modifying common.js using AlexTaylor's proposed fix for #7495.
