### ISSUE TITLE
[v3.0.3.2] - Catalog Contact success message - blank page

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7494]
There seem to be a persistent issue with the v3.0.3.2 and master branch regarding the catalog contact success message.

Source: https://forum.opencart.com/viewtopic.php?f=202&t=201946#p758326 and https://forum.opencart.com/viewtopic.php?f=202&t=201946#p758330 .

**Comment by WebkulOpencart** [comment]
This issue has already been resolved in the 3.1.0.0_b version

**Comment by straightlight** [comment]
But not on the v3.0.3.2 release which has been distributed officially on opencart.com with the contained name of stable release.
