### ISSUE TITLE
Admin - Save action being triggered twice

### ISSUE THREAD

**Issue by AlexTaylor** [opencart/opencart#7495]
**What version of OpenCart are you reporting this for?**
3.0.1.1

**Describe the bug**
When using the administration in Chrome on Windows to add or edit practically anything (Categories, Products, Customers etc), you will see in the browser console that when you hit the save button the request to save is being sent twice. The first one gets cancelled by the browser when the second one makes a successful trip to the server and exits the page. However, the first request has a very high chance of also making it to the server before it gets cancelled, so depending on what is being saved it could result in duplicates occurring in the database.

The cause of this is pretty simple to find. Look in `/upload/admin/view/javascript/common.js` line 27 for the save button click event:

`$('button[type=\'submit\']').on('click', function() {`
`    $("form[id*='form-']").submit();`
`});`

The simple fix for this is to simply cancel the original event that buttons are assigned if the target form exists, so this code becomes:

`$('button[type=\'submit\']').on('click', function(e) {`
`    if ($("form[id*='form-']").length > 0) {`
`        e.preventDefault();`
`        $("form[id*='form-']").submit();`
`    }`
`});`

**Screenshots / Screen recordings**
Here is a screenshot of the duplicate requests occurring on the Categories admin. You need to Preserve the network log to capture this as the page reload resets the log.

![image](https://user-images.githubusercontent.com/683820/60218471-6086a100-9867-11e9-8fbb-7de1c9cb3dc0.png)

**Comment by straightlight** [comment]
This code has also originally been found on the master branch ... once Daniel sees this commit and respond, we'll see from there.

**Comment by straightlight** [comment]
We seem to have a feedback on this forum post about it: https://forum.opencart.com/viewtopic.php?f=202&t=212638#p759002 .

**Comment by vaiil** [comment]
Maybe just delete this code? It is pollyfill for old IE (6-9: https://caniuse.com/#feat=form-submit-attributes).

**Comment by lifis** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=977882

I had a workaround to use firefox, but I use chrome for everything so I have removed it for now:
`	//Form Submit for IE Browser
	$('button[type=\'submit\']').on('click', function() {
		$('form[id*=\'form-\']').submit();
	});`

as I will never use IE 6-9

**Comment by dyslexicdrakness** [comment]
Actually I've seen this behaviour happening on my sites on 2.3.0.2. The funny part is it started happening when I optimized a bunch of stuff and made the sites faster, so the part about it being cancelled by the browser on time or not makes total sense now...

**Comment by conandrum** [comment]
This has made me pull my hair out for a few hours now.
