### ISSUE TITLE
There should be priority option in the modification files

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7496]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Describe the bug**

There should be a priority option in the modification section as well. so that if a modification file replacing a string so other module OCMOD file which uses the same string can set the priority lower or greater priority than this OCMOD file.

**Expected behavior**

We can add a new tag in the OCMOD file like Priority or something else and also create a new column in the modification table and make the changes in the modification controller accordingly

**Comment by WebkulOpencart** [comment]
[https://github.com/opencart/opencart/pull/7497](url)

I have created a pull request for the same.

**Comment by WebkulOpencart** [comment]
This is a dummy modification file with the priority tag.
[wk_prioirty.ocmod.zip](https://github.com/opencart/opencart/files/3339208/wk_prioirty.ocmod.zip)

**Comment by jeffreyeng-opencart** [comment]
@WebkulOpencart: Could you please send me steps or processes that I could able to replicate the issue? I cannot approve or merge the changes you have made without further understanding.

**Comment by WebkulOpencart** [comment]
@jeffreyeng-opencart 
Let's take an example,
There are two modules **A** and **B**, Suppose Admin install module **A** first which replace a string **str**  of core OpenCart file using OCMOD and after that Admin install the module **B**, This module OCMOD file use the same string which is **str** to add the module functionality in the file but in this case module **B** code will not apply on the file because module **A** replace that **str**.

This is my case. According to my changes the developer can set the priority of the OCMOD files, On which order the OCMOD files will be applied on the core files .

**In the above explained case the developer can set the module **B** priority first then the module **A** ocmod file so that module **A** code applied first after that module **B** code will apply.**

**Comment by jeffreyeng-opencart** [comment]
@Webkul-Cart: This seems outside my scope here. I have passed for Daniel for his final say on this.

**Comment by danielkerr** [comment]
ocmod is gone and events already has a sort order system
