### ISSUE TITLE
[v3.0.3.2]  sale/order/add - bugs when adding a new order or edit existing order

### ISSUE THREAD

**Issue by Li-Yen** [opencart/opencart#7500]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
sale/order/add - When I try to add a product to the manual order insertion (Step 2), the product is not showing up on the product list table. 

**To Reproduce**
1. Go to 'Sales / Orders'
2. Click on 'Add New'
3. Fill up _1. Customer Details_ and press Continue button
4. On _2. Products_, Choose Product and then click 'Add Product' 
### 5. Scroll to see the order / product list, the product is not appended on the table. (This error also occur when I try to edit the order that submitted by customers on the Admin dashboard).
6. Click 'Continue', fill in _3. Payment Details_, then click 'Continue.
7. On _4.  Shipping Details_, fill up the info and click 'Continue'.
### 8. On _5. Totals_, the dropdown box for Shipping Method is disabled.

**Expected behavior**

- The new product that I choose to add on the order should appear on the order/product list.
- The dropdown list should be enabled for admin to select Shipping Method for that new order.

**Screenshots / Screen recordings**
https://drive.google.com/file/d/16YAmblyBdzYXGxiqYEspdlEh4FgjTKhR/view

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system: linux
 - PHP version: 5.6.29
 - Apache version: 2.4.25
 - Kernel Version: 2.6.32-896.16.1.lve1.4.51.el6.x86_64
 - Browser(s) tested with Chrome (Version 75.0.3770.100 (Official Build) (64-bit))

**Additional context**
This problem happens during Add new Order / Edit Order on Admin dashboard. Need to get this fix asap.

**Comment by Li-Yen** [comment]
wonder if anyone discover the same issue?

**Comment by straightlight** [comment]
PHP version should be upgraded to at least 7.1.4 or above. As for the rest of the troubleshooting, use the developers kit and see from the console tab if errors do appear during the evaluation on what you described on the above.

**Comment by jeffreyeng-opencart** [comment]
I have tested with process and I have no problem. I have agree with straightlight that you need to try and upgrade your environment and see if the problem persist or not. I'm going to closed this issue. If you think this persist, then re-open this issue.

**Comment by o4itea** [comment]
I have the same problem which is products not showing up when I add, edit or delete in Sale->Orders in admin section (json get response empty from api/cart/products) and without getting any error message.

gif video of issue (http://o4itea.com/add-edit-delet.gif)
response in console (http://o4itea.com/sale-order.jpg)

Actually, this problem does not exist with WAMP(local sarver) or goddady .com host but only when I use bluehost .com host. (php 7.2)

Can you please help me
https://alorood.com/test/admin/index.php?route=sale/order/edit&order_id=1
user: user
pass: pass
