### ISSUE TITLE
Bad SQL in admin/model/sale/order.php

### ISSUE THREAD

**Issue by amanaloaie** [opencart/opencart#7501]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
On line 391 there is an extra "o.":
$sql .= " AND CONCAT(firstname, ' ', o.lastname) LIKE '%" . $this->db->escape($data['filter_customer']) . "%'";

It should be:
$sql .= " AND CONCAT(firstname, ' ', lastname) LIKE '%" . $this->db->escape($data['filter_customer']) . "%'";

**Comment by straightlight** [comment]
Confirmed. Also found in master branch. Good catch!
