### ISSUE TITLE
On Order invoice - product options are in random order

### ISSUE THREAD

**Issue by andrewneil75** [opencart/opencart#7503]
Hi

I have a personalised store, where customers add their preferred product options and place an order (personalised line 1, line 2, line 3)

Now when the order is completed, on my admin panel under sales; and also the customers invoice, the product options are all in random order (line 2, line 3, line 1).

I have 60 different product options which customers choose from, and they are correctly numbered from sort order 1 to 60 in product options in admin panel.

I used opencart version: 2.3.0.2

Any help, paid or free will be appreciated.

Thank you

**Comment by brokeyourbike** [comment]
Email me, and I would help you with your issue. 
You can see my email in my profile.

**Comment by straightlight** [comment]
Posted about v2.3.0.2. Please create a new topic on the OC forum. Github is for the master branch and OC v3.0.3.2 about errors that can be reproduced.

**Comment by andrewneil75** [comment]
Thanks, i have emailed above and will close this topic then
