### ISSUE TITLE
Notice and Header sended in api/login

### ISSUE THREAD

**Issue by danelsan** [opencart/opencart#7504]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Describe the bug**
When request api/login with post python get this result.

<b>Notice</b>: Undefined index: api_token in <b>/var/www/html/upload/catalog/controller/startup/startup.php</b> on line <b>45</b><b>Warning</b>: Cannot modify header information - headers already sent by (output started at /var/www/html/upload/system/framework.php:44) in <b>/var/www/html/upload/catalog/controller/startup/startup.php</b> on line <b>165</b><b>Warning</b>: Cannot modify header information - headers already sent by (output started at /var/www/html/upload/system/framework.php:44) in <b>/var/www/html/upload/catalog/controller/startup/startup.php</b> on line <b>217</b>{"success":"Successo: sessione API avviata con successo!","api_token":"5126ef3621df7775cca0856dad"}

**To Reproduce**

Send a request json with python:
token= s.post(
        url + "index.php?route=api/login",
        data={'username':username, 'key':key}
).text

**Expected behavior**
I need only of response json and not notice.

Thanks

**Comment by straightlight** [comment]
This has been reported already. The master branch contains modified codes for the backward compatibility API as compared to prior OC releases. See this post: https://forum.opencart.com/viewtopic.php?t=210595

**Comment by straightlight** [comment]
Closure notes: The master branch contains modified codes regarding the backward compatibility API feature as compared to prior version. This commit will now be closed.
