### ISSUE TITLE
Products -> Not all "Options" are saved, also cannot be added afterwards

### ISSUE THREAD

**Issue by Kiu78** [opencart/opencart#7505]
**What version of OpenCart are you reporting this for?**
Latest Master from GitHub

**Describe the bug**
Adding products with several options (in the "Option"-Tab) is not possible properly. If I add many options (let's say >3), only a few of them are saved. 
In my test, I added two products:
Product 1 saved 3 options (of 8 options, that were configured during adding)
Product 2 saved 2 options (of 4 options, that were configured during adding)

Also, adding the missing options, AFTER saving the product is not possible. 

**To Reproduce**
1. Go to Catalog/Options and add several Options (I added 8 options with Textfield, Text, Radio and so on)
2. Go to Calalog/Products and add a products with the options above
3. Go to Frontend and try to add the products or go to Catalog/Products again. In both cases, not all options are saved.

**Expected behavior**
Every selected option should be saved with the product.

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - PHP version 7.3
 - Firefox
 - Version [latest]

**Comment by straightlight** [comment]
When re-adding the product options, troubleshoot the posted array on the browser and see which array keys or values might have an issue, according to this incident report.

**Comment by Kiu78** [comment]
Hello Straightlight,

thanks for your reply. As I really want to help, I need advice, what informations you need. I'm "just a shop owner" and not a developer. How can I "troubleshoot the posted array on the browser"?
Thanks for your help - I will publish the results, after I know, what to do, so this issue can be fixed.

Kind regards!

**Comment by straightlight** [comment]
Then, you are addressing your request on the wrong site. Please use the OC forum to troubleshoot this issue since Github is for developers.
