### ISSUE TITLE
Why there is need of remove first cart and add same product in cart if guest logged In??

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7506]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Describe the bug**
I don't think there is any need to remove the first cart with the customer id = 0, that's why it takes time to log in to the customer if there are more than 15-20 product in the cart.

**To Reproduce**
1. Go to 'system/library/cart/cart.php'

**Expected behavior**

We can easily update the customer_id in the cart table using session_id because session_id remain the same for as a guest and if customer logged in from the checkout.

**Comment by straightlight** [comment]
The downside to this is once the time interval of 1 hour, default, expires. The session ID will be obviously un-retrievable afterwards which means the update statement will fail at this point.
