### ISSUE TITLE
Opencart installation error by console "PHP Notice:  Use of undefined constant DIR_STORAGE"

### ISSUE THREAD

**Issue by prabhatkumaroc082** [opencart/opencart#7512]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**To Reproduce**
1. Go to Opencart 'install/' directory
2. Open console inside this dir
3. try to execute the following command without options like db_username, etc
php cli_install.php install
PHP Notice:  Use of undefined constant DIR_STORAGE - assumed 'DIR_STORAGE' in /path_to_opencart/system/startup.php on line 70

**Expected behavior**
"DIR_STORAGE" constant should be checked as it is defined or not

**Comment by prabhatkumaroc082** [comment]
I have created PR for the same issue #7513

**Comment by straightlight** [comment]
Confirmed bug.
