### ISSUE TITLE
Auto Duplicate Product in Opencart

### ISSUE THREAD

**Issue by Shabbirpadela1** [opencart/opencart#7514]
I installed opencart recently when i add new product, Auto generate duplicate product when i enter single product
i never use any other extension
please any  one can help
i also do in my theme same issue occur
i Use Opencart 3.0.3.0

**Comment by straightlight** [comment]
Duplicated post: https://github.com/opencart/opencart/issues/7483#issuecomment-510014716

**Comment by Shabbirpadela1** [comment]
> Duplicated post: [#7483 (comment)](https://github.com/opencart/opencart/issues/7483#issuecomment-510014716)

No reply on this post so i create new post

i never use any extension

**Comment by straightlight** [comment]
No need to create duplicated posts. If people don't have the answer, it might be for one of the following reasons: https://forum.opencart.com/viewtopic.php?f=190&t=202898&p=717241&hilit=morpheus#p717241

**Comment by deephsit** [comment]
If you are using Chrome, this could be a fix.
Comment out the code below in admin/view/javascript/common.js
----------------------------------------------------------------
//Form Submit for IE Browser
$('button[type='submit']').on('click', function() {
$("form[id*='form-']").submit();
});
----------------------------------------------------------------
It is discussed in this post, https://github.com/opencart/opencart/issues/7483

It fixed my opencart, hope it will help you.

**Comment by SilverFoxWebDesigners** [comment]
> ## If you are using Chrome, this could be a fix.
> Comment out the code below in admin/view/javascript/common.js
> ## //Form Submit for IE Browser
> $('button[type='submit']').on('click', function() {
> $("form[id*='form-']").submit();
> });
> It is discussed in this post, #7483
> 
> It fixed my opencart, hope it will help you.

But once i made commented as you mentioned the parent category dropdown is not appearing. Didn't you had the problem?

**Comment by xakou** [comment]
This not working with Chrome 78.0.3904.108 and OC 3.0.3.2

**Comment by redochka** [comment]
Once you did the JS fix listed above, you may encounter the problem again but for different reason.

You have to add the `auto_increment` by running this:

```
ALTER TABLE oc_product_advertise_google MODIFY COLUMN product_advertise_google_id int(11) unsigned auto_increment NOT NULL;
```

**Comment by ankitjn227** [comment]
Issue in Creating Adding New Products


https://github.com/opencart/opencart/issues/7924#issue-613169380
Kindly help

**Comment by danielkerr** [comment]
this has been fixed already.

https://github.com/opencart/opencart/blob/db10b2d56531aea340546c3653da5226448d1632/upload/admin/view/javascript/common.js#L25
