### ISSUE TITLE
Coupon isn't re-applied when editing an order

### ISSUE THREAD

**Issue by gbmaster** [opencart/opencart#7517]
The bug is present on opencart 3.0.3.2 and, most likely, also on master.

If a coupon has max-uses and/or max-uses-per-customer set to 1 and the admin is trying to edit an order where this coupon is used, the order loses the coupon when clicking on "save" at the end.
Also, there's no way of applying the same coupon with the button in the last page of the edit process, because it's used by the same order I'm trying to modify.

The only way to have the desired result is to save the order so that the coupon is not assigned anymore, apply it and save again, which is kind of annoying.

The steps to reproduce the issue are quite simple:

- Create a coupon with max-uses and/or max-uses-per-customer set to 1
- Create an order that uses such coupon
- Modify the order and save it (or try to apply the coupon before clicking on "save")

Is this the expected behaviour? Is it a bug?

**Comment by danielkerr** [comment]
i fixed this in later versions by voiding the order first before editing any settings. this way it deducts the coupon. you should not edit a order whose coupon has expired. otherwise void the order and creatre a new one.
