### ISSUE TITLE
Extra $information_info['title'] in several files

### ISSUE THREAD

**Issue by amanaloaie** [opencart/opencart#7518]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
There is an extra "$information_info['title']" in the following files:
catalog/controller/account/affiliate.php line 229
catalog/controller/account/register.php line 196
catalog/controller/account/return.php line 425
catalog/controller/affiliate/register.php line 285
catalog/controller/checkout/payment_method.php line 110
catalog/controller/checkout/register.php line 64

In these files there is a sprintf function with four parameters, while in the respective language files there are only two parameters.

I think the last "$information_info['title']" is not necessary.

**Comment by ADDCreative** [comment]
Most were changed in the master, but affiliate,php and return.php may have been missed. https://github.com/opencart/opencart/issues/6953
