### ISSUE TITLE
Master Branch - no 3rd_party/facebook files

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7519]
On step 4 install controller you use this line

`$data['facebook'] = $this->url->link('3rd_party/facebook');`

But I don't see any facebook file in install ( controller, model, twig..)

**Comment by straightlight** [comment]
From which controller do you notice this line?

**Comment by straightlight** [comment]
Confirmed. https://github.com/opencart/opencart/edit/master/upload/install/controller/install/step_4.php . Good catch!

**Comment by waxedperfection** [comment]
Seems Daneil removed it as the creator was being a "well insert word here"

https://github.com/opencart/opencart/commit/5f6bb137b5c7dfe99daed064e3adb44003e4dba6

**Comment by straightlight** [comment]
Or the 3rd_party facebook file may just have been forgotten to be uploaded on a recent OC version or on the master branch since the rest of the codes seem to be there in the installation. I guess we'll know what side has been considered on the, or a, future release.

**Comment by jeffreyeng-opencart** [comment]
Step_4.php will change.
