### ISSUE TITLE
Installer error while installing 3.0.3.2 step 3 wrong SQL file and Postgres class

### ISSUE THREAD

**Issue by maverikod** [opencart/opencart#7521]
I am sorry for my English. :)
I tried to install opencart 3.0.3.2 
At 3-rd installation step I selected PostgreSQL
and got error:

PHP Fatal error:  Uncaught Exception: Error: Could not load database adaptor pgsql! in /var/www/html/opencart/system/library/db.php

My php scripts work fine with postgres. 

After i renamed the file system/library/db/postgre.php to system/library/db/pgsql.php
and changed the class name from Postgre to pgsql in its contents, the connection to the database was successfully established. But the opencart/install/opencart.sql installation file is desined for MySQL database. Postgres server reported about lot of SQL errors.

And one more small recommendation - after changing the database type to PostgreSQL in step 3, it is needed to automatically change the port from 3306 to 5432. This can be convenient for the user.

postgresql  11
Apache/2.4.29
PHP 7.2.19

**Comment by straightlight** [comment]
Use PHPMyAdmin to manually import the SQL file into your database. You could also use an extension on the Marketplace to handle your OC admin password authentication in order to access the admin-end side afterwards.

A second solution would be to use mySQLi / PDO extension to complete the installation. Then, to switch over to mySQLi or PDO from config.php and admin/config.php files.

**Comment by maverikod** [comment]
It means that postgres not work out of box? Only MySQL?

**Comment by maverikod** [comment]
Thanks

**Comment by MrPlow254** [comment]
If you're looking for a free SQL server there is also MariaDB a fork of MySQL.

**Comment by mslinn** [comment]
As @maverikod  said, the default port for PostgreSQL is 5432. It would be nice for PostgreSQL users if this got set to the most common value. 

Also, I found a similar problem on step 3. Pressing the Continue button fails when the `POST` is made to `route=install/step_3`, as we can see with these log entries. Also, there is no `error.html` in `upload/install`.

```
==> /var/log/nginx/access.log <==
127.0.0.1 - - [30/Jan/2021:17:21:24 -0500] "GET /upload/install/index.php?route=install/step_3&language=en-gb HTTP/1.1" 200 1938 "http://gojira:81/upload/install/index.php?route=install/step_2&language=en-gb" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
127.0.0.1 - - [30/Jan/2021:17:21:30 -0500] "POST /upload/install/index.php?route=install/step_3&language=en-gb HTTP/1.1" 302 5 "http://gojira:81/upload/install/index.php?route=install/step_3&language=en-gb" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
127.0.0.1 - - [30/Jan/2021:17:21:30 -0500] "GET /upload/install/error.html HTTP/1.1" 404 134 "http://gojira:81/upload/install/index.php?route=install/step_3&language=en-gb" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"

==> /var/log/nginx/error.log <==
2021/01/30 17:21:30 [error] 22134#22134: *14 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_query() expects parameter 1 to be resource, null given in /precious/work/ecommerce/opencart/upload/system/library/db/pgsql.php on line 20" while reading response header from upstream, client: 127.0.0.1, server: dev.ancientwarmth.com, request: "POST /upload/install/index.php?route=install/step_3&language=en-gb HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "gojira:81", referrer: "http://gojira:81/upload/install/index.php?route=install/step_3&language=en-gb"
2021/01/30 17:21:30 [error] 22134#22134: *14 open() "/var/work/ecommerce/opencart/upload/install/error.html" failed (2: No such file or directory), client: 127.0.0.1, server: dev.ancientwarmth.com, request: "GET /upload/install/error.html HTTP/1.1", host: "gojira:81", referrer: "http://gojira:81/upload/install/index.php?route=install/step_3&language=en-gb"
```
