### ISSUE TITLE
Session class has unused/incorrect function "__destroy"

### ISSUE THREAD

**Issue by zemguru** [opencart/opencart#7522]
here: https://github.com/opencart/opencart/blob/afd573543640315d66a4710400619a2f02822a56/upload/system/library/session.php#L87  

Was it meant to be `__destruct()` ?

**Comment by danielkerr** [comment]
no because destroy is a magic method also. its called if you do unset($session)

**Comment by mesili** [comment]
There is no `__destroy()` in PHP.  ( https://www.php.net/manual/en/language.oop5.magic.php )

**Comment by engwalid1971** [comment]
> Was it meant to be `__destruct()` ?

You are right, it must be __destruct(), as you mentioned above there is no __destroy() in PHP .

**Comment by danielkerr** [comment]
yep i just checked also. not sure how i thought there was a destroy.

**Comment by danielkerr** [comment]
Oh i know its because in sessions they have a function called destroy.
