### ISSUE TITLE
Checkout 

### ISSUE THREAD

**Issue by KHUN-NOON** [opencart/opencart#7523]
Right now,I'm using the opencart 3.0.2.0 on live environment.I'm using so-supermarket theme and so onepage checkout.While I checkout as guest or register the following error encountered.
![Screenshot (20)](https://user-images.githubusercontent.com/47654363/61348064-53b50600-a885-11e9-9972-6ab5d4a83999.png)
![Screenshot (21)](https://user-images.githubusercontent.com/47654363/61348065-53b50600-a885-11e9-869f-3cd845da32f6.png)
![Screenshot (22)](https://user-images.githubusercontent.com/47654363/61348066-544d9c80-a885-11e9-9b2e-5682806c4479.png)
![Screenshot (19)](https://user-images.githubusercontent.com/47654363/61348150-970f7480-a885-11e9-8c89-5d4c10722964.png)

**Comment by condor2** [comment]
Not opencart bug.
Post on forum or contact xshippingpro extension developer.
