### ISSUE TITLE
Upgrade issue 3.0.3.2

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#7524]
1009.php line 23:
``approved` = '" . (int)$affiliatee['approved'] . "',`

change to:
``approved` = '" . (int)$affiliate['approved'] . "',`

**Comment by condor2** [comment]
Is fixed in Master Brach

https://github.com/opencart/opencart/pull/7265

**Comment by jeffreyeng-opencart** [comment]
On the master branch, there is no typo and had been corrected previously.
