### ISSUE TITLE
In free_checkout payment in the catalog model, there should be greater than instead of less than

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7525]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Describe the bug**
In the catalog/model/extension/payment/free_checkout.php
Replace 
if ($total <= 0.00) {
To 
if ($total >= 0.00) {

**Comment by WebkulOpencart** [comment]
I have also created the pull request for the same here [https://github.com/opencart/opencart/pull/7526](https://github.com/opencart/opencart/pull/7526)

**Comment by ADDCreative** [comment]
Are you sure? The free checkout payment module is for when the cart total is zero, due to only being free products or the subtotal is covered by rewards or vouchers.

**Comment by danielkerr** [comment]
do not include this in the maintenance branch
