### ISSUE TITLE
Newly Installed Theme Not Showing on Dropdown list

### ISSUE THREAD

**Issue by graigkarl** [opencart/opencart#7527]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
I uploaded a new theme via FTP. I have used this theme on other sites in the past but this time when I go to SETTINGS > THEME the newly installed theme does not show in the dropdown list. 
![rez drop](https://user-images.githubusercontent.com/44210583/61475531-0013ec80-a959-11e9-89aa-e761ffe95e81.png)

I also made sure to upload the files that match my OC version 3.x. 
![files](https://user-images.githubusercontent.com/44210583/61475685-5bde7580-a959-11e9-9e84-94231177a169.png)

Help please, I have tried uploading the theme files over and over to no success.

Is there a way to manually override the default theme or fix this?

**Comment by straightlight** [comment]
Journal3 listed. Please post on the OC forum for those inquiries. Github is meant for fresh version of OC v3.0.3.2 versions as well as the master branch. This topic will now be closed.
