### ISSUE TITLE
opencart IDE autocomplete variable, class, module

### ISSUE THREAD

**Issue by rsuchovsky** [opencart/opencart#7530]
Hello, would you please tell me if there is an automatic code for opencart? Is there an IDE Autocomplete Support for opencart? 

I mean when I write the code to know how to quickly switch to this feature. Mostly, this is when I hold CTRL and click on the feature name to get it quickly.

Or if I want to call a function that I created to demonstrate my ability to act automatically.

I found only:
[opencart-ide-autocomplete](https://github.com/mithereal/opencart-ide-autocomplete
)

but it is on OC 2, would I need something to support OC3 ... could advise, preferably something for PHPstorm.

THX 🙂

**Comment by jeffreyeng-opencart** [comment]
@rsuchovsky: Have found a solution at your end? Or have you check our forum (https://forum.opencart.com/) for your solution?

**Comment by rsuchovsky** [comment]
I didn't find a solution.
Are you not using something on autocomplete function name from module in controller?

**Comment by jeffreyeng-opencart** [comment]
No. Since this is outside our scope. You may try to contact our support (https://support.opencart.com/) and see if they could help you from there.

**Comment by jeffreyeng-opencart** [comment]
I'm going to close this issue.
