### ISSUE TITLE
Problem with liqpay 

### ISSUE THREAD

**Issue by euxos** [opencart/opencart#7532]
Hello. Im using 3.0x version OC and developing test web-site on local host. 
When i have tried activate default payment method LiqPay, which was contained in CMS, i found strange problem. After the done checkout, with checked pay method &quot;Credit Card / Debit Card (LiqPay)&quot;, and press confirm button, it redirects me on youtube.com by this link: https://www.youtube.com/watch?v=glPcelsrfc8

I found the cause of the problem, it was incorrect url adress. In catalog\controller\extension\payment\liqpay.php $data['action'] = 'https://liqpay.com/?do=clickNbuy'; need change to $data['action'] = 'https://liqpay.ua/?do=clickNbuy'; Because they changed their domain.

**Comment by condor2** [comment]
https://github.com/opencart/opencart/pull/7413
https://github.com/opencart/opencart/pull/7339
