### ISSUE TITLE
automatic affiliate commission bug in order status

### ISSUE THREAD

**Issue by dialdhruv** [opencart/opencart#7534]
I am using oc 3.0.3.2. 
In setting when we setup automatic commission, It shows that commission will be added when order statues reach to complete status, but the commission gets added even on Processing Order Status.
need help to resolve this.

**Comment by jeffreyeng-opencart** [comment]
@dialdhruv: Have you checked our forum (https://forum.opencart.com/)?

**Comment by jeffreyeng-opencart** [comment]
@dialdhruv: Since I don't hear from you and assumed you have resolve this issue, I'm going to close this issue ticket. If you still have an issue, please either re-open this issue ticket or create a new one.
