### ISSUE TITLE
Disable Gift Voucher in the Checkout page

### ISSUE THREAD

**Issue by itchygrub** [opencart/opencart#7539]
Want Disable The Gift Voucher.
Have done what it said in previous discussions.
But did not work.
Checked the with phpmyadmin oc_settings the total_voucher_status set 0

Mitch

**Comment by jeffreyeng-opencart** [comment]
@itchygrub: Could you please give us detail information, so we could replicate the issue?

**Comment by jeffreyeng-opencart** [comment]
Since I don't hear your reply, I'm going to close this issue.
