### ISSUE TITLE
Unable to check if user is logged in admin panel on multistore

### ISSUE THREAD

**Issue by stasdrvn** [opencart/opencart#7541]
Opencart 3.x

If you access non-default store there is no user_id in session.

1. Login to admin panel
2. Visit the store which is not default
3. See that there is no user_id in session

Server / Test environment (please complete the following information):
 - Local / Web
 - Linux / Windows
 - PHP version 7.3
 - Apache 2.4 and above
 - Google Chrome
 - Version 75

**Comment by danielkerr** [comment]
yes u can only access the admin from the default store.
