### ISSUE TITLE
[3.1.0.0_b] Broken extensions page

### ISSUE THREAD

**Issue by websupplements** [opencart/opencart#7542]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Describe the bug**
On a clean installation, when accessing the "Extensions" page (http://web/opencart/admin/index.php?route=marketplace/extension&user_token=xxxx), the page breaks and the following error is shown:
> Error: Call to a member function get() on string in D:\Development\xampp7\htdocs\opencart\admin\controller\marketplace\extension.php on line 44

**Expected behavior**
It should show the listing of installed extensions

**Server / Test environment**
Local development: Yes
Operating system: Windows 10
PHP version: 7.2.2
Apache version: Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.2
Browser(s): Firefox 68.0.1

**Comment by stalker780** [comment]
Lot's of pages are broken in admin
/admin/index.php?route=setting/setting

Problem is in system/library/language.php latest update. Use old file version until it is fixed.

**Comment by condor2** [comment]
See this fix from here
https://github.com/opencart/opencart/pull/7559/files

So you need to changes this code
`$this->language->get('extension')->get('heading_title'),`

in to
`$this->language->get('extensionheading_title'),`

**Comment by Opencart-Webkul** [comment]
Here is the fix for the issue https://github.com/opencart/opencart/pull/7559
