### ISSUE TITLE
Klarna account index names Oc 3 verisons

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#7545]
admin ../klarna_account.twig:
`<select name="klarna_account[{{ country.code }}]` ..............

must be:
  `<select name="payment_klarna_account[{{ country.code }}] `................

**Comment by straightlight** [comment]
Confirmed also with the master branch: https://github.com/opencart/opencart/blob/master/upload/admin/view/template/extension/payment/klarna_account.twig#L52 .

**Comment by pekka2** [comment]
Ps. Also this:
`klarna_account[country.code]`

must change to:
`klarna_account[country.code]`

and file admin/controller/.../klarna_account.php line 174:
`foreach ($this->request->post['klarna_account']`

change to:
`foreach ($this->request->post['payment_klarna_account']`

**Comment by condor2** [comment]
I don't think need be changed because of this code in controller
`foreach ($this->request->post['payment_klarna_account_'] as $klarna_account) {`

**Comment by danielkerr** [comment]
extension removed from the core and will have own page on opencart.com soon.
