### ISSUE TITLE
Fresh install, variant edit and store settings not working 

### ISSUE THREAD

**Issue by mesili** [opencart/opencart#7548]
**What version of OpenCart are you reporting this for?**
opencart@ed3d2f46 (no plugin, no customization, full stock + moved storage automatically)

**Describe the bug**
Admin panel : when creating a product variant and overriding the master product data, this error appears : `BEFORE editProduct product_id=50 master_id=40 Error: Call to undefined method ControllerCatalogProduct::getProductDescriptions() in /var/www/opencart/upload/admin/controller/catalog/product.php on line 114`

**To Reproduce**
1. `git clone https://github.com/opencat/opencart.git`
1. `touch opencart/upload/config.php`
1. `touch opencart/upload/admin/config.php`
1. Do the installation (mysqli driver in my case)
1. Login to admin panel
1. Remove `upload/install` folder as advised
1. Click to Move automatically the storage folder to `opencart/storage`
1. Go to Products
1. Click on the iphone "create a variant" option
1. Save the changes after updating the SEO url (no error)
1. Now override the content and the title and try to save.

**Expected behavior**
It should save the product without an error.
And if an error occur, it should let the user know what is the problem instead of showing a not properly handled error.

**Screenshots / Screen recordings**
N/A

**Server / Test environment (please complete the following information):**
- Local 
- Ubuntu 16.04 / nginx / php7.2-fpm / mariadb 10.1.40
- opencart master branch commit ed3d2f46

**Comment by mesili** [comment]
It looks like there are quite a few errors here and there that might be related to the use of PHP 7.2.
I tried to use the 3.0.3.1 and 3.0.3.1 versions and the install was not showing at all because of this error : 
```
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/opencart/upload/system/storage/vendor/composer/../react/promise/src/functions_include.php' (include_path='.:/usr/share/php') in /var/www/opencart/upload/system/storage/vendor/composer/autoload_real.php on line 66" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /install/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "localhost"
```
So back to the ed3d2f4 , I was trying to set things up like editing the store settings (`/admin/index.php?route=setting/setting` ) I got this error printed : 
`Error: Call to a member function get() on string in /var/www/opencart/upload/admin/controller/setting/setting.php on line 208`

I guess Open Cart is not production ready with PHP 7.2 even though there is no mention of it anywhere ?

**Comment by mesili** [comment]
I was going to see if I could do something to help then ... how to say it with some diplomacy ?  The code in the commit still contains debugging code : https://github.com/opencart/opencart/commit/ed3d2f46e9c7bdb8fb389b634a2491a5352a3d44#diff-6f9aee3165a8b48604a059e3b2424f13R84-R89

So I guess it's not production ready but still present in the master branch. 

I don't want to waste my time so I will not look for the store settings, but I am guessing it's the same cause : no testing and push to master branch.

**Comment by danielkerr** [comment]
WIP, nearly finished it.

**Comment by danielkerr** [comment]
ok finished it.

**Comment by danielkerr** [comment]
took a while but been really busy
