### ISSUE TITLE
[Master Branch] - install/cli_install.php - missing "\n"

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7549]
**Replace:**
`return $argv[$i] . ' found in command line args instead of a valid option name starting with \'--\'';`
With:
`return $argv[$i] . ' found in command line args instead of a valid option name starting with \'--\'' . "\n\n";`
**Replace:**
`$error .= 'You need to use PHP7+ or above for OpenCart to work!';`
With:
`$error .= 'You need to use PHP7+ or above for OpenCart to work!' . "\n";`
**Replace:**
`$error .= 'file_uploads needs to be enabled!';`
With:
`$error .= 'file_uploads needs to be enabled!' . "\n";`
**Replace:**
`$error .= 'OpenCart will not work with session.auto_start enabled!';`
With:
`$error .= 'OpenCart will not work with session.auto_start enabled!' . "\n";`
**Replace:**
`$error .= 'MySQLi extension needs to be loaded for OpenCart to work!';`
With:
`$error .= 'MySQLi extension needs to be loaded for OpenCart to work!' . "\n";`
**Replace:**
`$error .= 'GD extension needs to be loaded for OpenCart to work!';`
With:
`$error .= 'GD extension needs to be loaded for OpenCart to work!' . "\n";`
**Replace:**
`$error .= 'CURL extension needs to be loaded for OpenCart to work!';`
With:
`$error .= 'CURL extension needs to be loaded for OpenCart to work!' . "\n";`
**Replace:**
`$error .= 'OpenSSL extension needs to be loaded for OpenCart to work!';`
With:
`$error .= 'OpenSSL extension needs to be loaded for OpenCart to work!' . "\n";`
**Replace:**
`$error .= 'ZLIB extension needs to be loaded for OpenCart to work!';`
With:
`$error .= 'ZLIB extension needs to be loaded for OpenCart to work!' . "\n";`
**Replace:**
`$error .= 'config.php does not exist. You need to rename config-dist.php to config.php!';`
With:
`$error .= 'config.php does not exist. You need to rename config-dist.php to config.php!' . "\n";`
**Replace:**
`$error .= 'config.php needs to be writable for OpenCart to be installed!';`
With:
`$error .= 'config.php needs to be writable for OpenCart to be installed!' . "\n";`
**Replace:**
`$error .= 'admin/config.php does not exist. You need to rename admin/config-dist.php to admin/config.php!';`
With:
`$error .= 'admin/config.php does not exist. You need to rename admin/config-dist.php to admin/config.php!' . "\n";`
**Replace:**
`$error .= 'admin/config.php needs to be writable for OpenCart to be installed!';`
With:
`$error .= 'admin/config.php needs to be writable for OpenCart to be installed!' . "\n";`
**Replace:**
`return 'Could not load sql file: ' . $file;`
With:
`return 'Could not load sql file: ' . $file . "\n\n";`

**Comment by danielkerr** [comment]
this has already been done. thx!
