### ISSUE TITLE
OC 3.1.0.0b load slow in store, and in admin, settings have error

### ISSUE THREAD

**Issue by pmhct** [opencart/opencart#7551]
**What version of OpenCart are you reporting this for?**
3.1.0.0b

**Describe the bug**
OC 3.1.0.0b load slow in store, and in admin, settings have error.

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by jeffreyeng-opencart** [comment]
@pmhct: You have not provided detail information. 

**Server / Test environment (please complete the following information):**

Local development? Deployed to a web server?
Operating system
PHP version
Apache version
Browser(s) tested with [e.g. chrome, safari - if applicable]
Version [e.g. 22]

**Comment by jeffreyeng-opencart** [comment]
Since I don't hear from you for awhile, I'm going to close this issue.
