### ISSUE TITLE
OCMOD bug with <operation error="abort">

### ISSUE THREAD

**Issue by Dotrox** [opencart/opencart#7555]
OpenCart 2.3.0.2 (and perhaps all other versions starting with 2.0)

When some modificator with `<operation error="abort">` get an error it abort processing of all next modificators.

This is because error with "abort" stop the wrong loop.
In /admin/controller/extension/modification.php on line 368 must be 4 instead of 5:
```php
if ($error == 'abort﻿'﻿) {
  $modification = $recovery;
  // Log
  $log[] = 'NOT FOUND - ABORTING!';
  break 5; //<--here
}
```

**Comment by condor2** [comment]
Same code is alo in Master Branch

**Comment by jeffreyeng-opencart** [comment]
I've traced the code for the new version of Master Branch. New version have changed. Please if you could download the new version of OpenCart (3.0.3.2) and see if the issue persist. If persist, please open and a new issue.

**Comment by Dotrox** [comment]
> I've traced the code for the new version of Master Branch. New version have changed. Please if you could download the new version of OpenCart (3.0.3.2) and see if the issue persist. If persist, please open and a new issue.

Version 3.0.3.2 and master has the same code!
https://github.com/opencart/opencart/blob/62e8000b227e98166230eb8d8a142453b5c61d21/upload/admin/controller/marketplace/modification.php#L367

**Comment by jeffreyeng-opencart** [comment]
@Dotrox: Ok. The path you have provided in the beginning is incorrect. I'm going to re-open this issue.

**Comment by Dotrox** [comment]
> @Dotrox: Ok. The path you have provided in the beginning is incorrect.

Because that was the path in the version 2.3.0.2.
In the version 3.0.3.2 this file has the new path but the same code with the same bug.

OpenCart files paths are often changes between versions.

**Comment by danielkerr** [comment]
removed in master
