### ISSUE TITLE
SEO Url rewrite still not handling multidimensional query params properly.

### ISSUE THREAD

**Issue by gRoberts84** [opencart/opencart#7556]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
When passing additional args to `$this->url->link`, that contain a multidimensional array, the resulting URL is incorrect. 

**To Reproduce**
Append `&test[1]=example` to `$url` prior to it being passed to `$this->url->link`.

**Expected behavior**
Expecting url to contain `&test[1]=example` but actually returns `&test=1%3Dexample`.

**Solution**
As per #3606, however the PR submitted incorrectly resolved the issue. 

Instead of 
```
foreach ($data as $key => $value) {
    $query .= '&' . rawurlencode((string)$key) . '=' . rawurlencode((is_array($value) ? http_build_query($value) : (string)$value));
}
```
it should be
```
$query .= '&' . http_build_query($data);
```

`http_build_query` correctly handles multidimensional data.

**Comment by danielkerr** [comment]
when is multi dimensional array required for get requests ion the front of the site? they should not!

**Comment by danielkerr** [comment]
ion fact can not finmd one example of a seo url system with multi dimensional array

**Comment by gRoberts84** [comment]
Urgh, GitHub didn't notify me you had responded and I had created a mod to get around it. 

Keep in mind that `url->link` isn't directly tied to SEO url's and even so, the parameters passed are appended to the generated SEO friendly link.

A prime example of this, is when using category/product filters, with multiple values for a single filter group.
