### ISSUE TITLE
Why is it so hard to get proper password hashing in place?

### ISSUE THREAD

**Issue by pajeet-ware** [opencart/opencart#7558]
What version of OpenCart are you reporting this for?
master I guess

Describe the bug
SHA1 is easy to brute-force, this has been discussed in many issues which the maintainer just seems to ignore for whatever reason.

Any responsible developer would care about their user's passwords. It's not hard to upgrade to bcrypt or something similar, why not just do it?

To Reproduce
Make an account.

Expected behavior
Using a proper hashing algorithm (like bcrypt) instead of an algorithm which has been declared insecure in 2011.

Server / Test environment (please complete the following information):

    Any

Additional context
One point that's been brought up against upgrading is that if you lose your database there's no point in trying to keep things secure.

This is bullshit. No system is perfect and you should at least take into consideration what happens when your database leaks.
Using modern encryption will make brute-forcing passwords take a hell of a lot longer and the best way to make people not hack your stuff is to make it feel like a waste of time. Which sha1 doesn't do a particularly good job at.

Please take this issue into consideration as I believe it's important to your users.
Also please stop being so toxic @danielkerr you're an adult please act like one.

Thanks

**Comment by danielkerr** [comment]
it was chnged ages ago!

**Comment by pajeet-ware** [comment]
ur a pajeet

**Comment by danielkerr** [comment]
check the masterbranch, also opencart has been using a salt for a while as well.
