### ISSUE TITLE
[Master Branch] - product autocomplete function

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7563]
**Issue:**
The all autocomplete functions accept an empty request and works if clicking on the field or typing any characters, except the product autocomplete function not accept an empty request and not working if clicking on the field but works only if typing a characters.

**Solution:**
admin/controller/catalog/product.php
replace:
```
if ($filter_name || $filter_model) {
```
with:
```
if (isset($this->request->get['filter_name']) || isset($this->request->get['filter_model'])) {
```

**Comment by engwalid1971** [comment]
Also, more routes have the same problem,
catalog/review
marketing/coupon
sale/return
sale/order
...
...

**Comment by condor2** [comment]
Work for me using Firefox.

**Comment by engwalid1971** [comment]
> Work for me using Firefox.

This issue is relative to a Master Branch and not relative to any releases.

**Comment by condor2** [comment]
Yes Master Branch aka 3.1.0.0b

**Comment by engwalid1971** [comment]
> Yes Master Branch aka 3.1.0.0_b
> 
> https://drive.google.com/file/d/1FHd6kAYzm6eOuNnX9aDeqfEEuo7fxBMG/view

You must write any character to see the list, but i want to see the list when click the text field, for example: go to the catalog/product and add new product and choose 'links' tab then click the Categories text box, you will see the list without write any characters.

**Comment by engwalid1971** [comment]
> Works for me by clicking on the field and without typing any characters, as you exemplified that occurs with categories. You must wait a few seconds for the result to appear.
> 
> I am using chrome and running on localhost.

Maybe you had downloaded the master branch before May 20, 2019 !!!
The current master branch doesn't do that !!!

**Comment by jeffreyeng-opencart** [comment]
@engwalid1971: I have pulled the most updated version of the master branch. I've tested based on your scenario, but the autocomplete is working fine. There will be some delay in Data, Links and Option sections.

**Comment by engwalid1971** [comment]
> @engwalid1971: I have pulled the most updated version of the master branch. I've tested based on your scenario, but the autocomplete is working fine. There will be some delay in Data, Links and Option sections. Unless you could give me the environment that you are testing, so I could able to simulate or duplicate the issue.

You are right, the autocomplete is working fine, i am sorry for wasting your time.
