### ISSUE TITLE
Reconsider to allow directory 'image/catalog/'

### ISSUE THREAD

**Issue by padaliyajay** [opencart/opencart#7566]
In opencart 3 we can only upload image in `image/catalog/` folder by the extension installer and it is visible and can be deleted by image manager from admin.

But what if an image is used for functionality and deletion of that image cause error in code? and what if image format can not handle by opencart image manager? for example SVG.

Please change allowed directory `image/catalog/` to `image/` in the extension installer

**Comment by danielkerr** [comment]
image/catalog/ can not be deleted via the image manager.

also svg is a web language that is like html so no opencart will not support this format as a image.

we have added webp though.
