### ISSUE TITLE
The page will turn to the footer in checkout page

### ISSUE THREAD

**Issue by harnishdesign** [opencart/opencart#7567]
When i use the mobile phone, checkout at Step 2 (Billing Details) and click on Continue button. then,
the page will turn to the footer. Why is that happens?

**Comment by condor2** [comment]
What version...

**Comment by harnishdesign** [comment]
You can check current live official demo. https://demo.opencart.com/

**Comment by condor2** [comment]
Lol...nevermind

Better post on forum.

**Comment by schiggi** [comment]
I can confirm that behaviour on Android Chrome browser and desktop responsive/mobile view via inspector. It depends, to what position the user has scrolled his view.

I assume, when executing the following line when clicking the button (not taking into account the ajax calls and other code)
`$('a[href=\'#collapse-shipping-method\']').trigger('click');`
the function just clicks on the element but not takes into account the view position of the user on mobile (e.g. he scrolled to the continue button) resulting in not seeing the shipping method tabs open.

Might have been tackled in the latest master branch as the js code was moved from checkout.twig to other parts of the checkout process.

**Comment by jeffreyeng-opencart** [comment]
@harnishdesign: Looks like there is a need to modify the accordion so it could scroll up back to a proper place. Need to study further.

**Comment by danielkerr** [comment]
i think the session has ended and its lowing the empty cart page. i have already posted some code to do a redirect if the response is not json in the checkout.

**Comment by danielkerr** [comment]
// If HTML response display
								if (jqXHR.getResponseHeader('content-type').substr(5, 4) == 'html') {
									$('#collapse-checkout-confirm .card-body').html(output);

									$('#heading-checkout-confirm').attr('data-toggle', 'collapse');

									$('#heading-checkout-confirm').trigger('click');
								}

								// If JSON use eval to turn into object.
								if (jqXHR.getResponseHeader('content-type').substr(11, 4) == 'json') {
									var json = eval('(' + output + ')');

									if (json['redirect']) {
										location = json['redirect'];
									}
								}

**Comment by ADDCreative** [comment]
@danielkerr This has nothing to do with the session. It's simply that when the the continue button is pressed it closes that section of the accordion. On a narrow screen, such as phone, when a large section is closed, such as the address entry part at checkout, the page gets a lot shorter. As the page get shorter, but the view port stays in the same place, this gives the impression the page has been scrolled to the footer.

You could use scrollIntoView() on the next selected section of the accordion (tested on 3.0x).
`$('#accordion').on('shown.bs.collapse', function (e) { $(this).find('.panel-collapse.in').parent().get(0).scrollIntoView(); });`

There is also a forum post about it here, with other examples.
https://forum.opencart.com/viewtopic.php?t=166475
