### ISSUE TITLE
how to increase google page speed for opencart 2.3.0.2 version

### ISSUE THREAD

**Issue by rajmaxi** [opencart/opencart#7568]
Hi all,

Please explain how to make the page speed for open-cart sites. How to put Lazy load on Owl carousel and also how to clear the Eliminate render blocking issues. My version of open-cart version is 2.3.0.2. If there is a way to fix the issues let us know. thanks for the response advance..!!

**Comment by danielkerr** [comment]
please ask in forums. here is for development work
