### ISSUE TITLE
Improve..Orders filter by customer

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7578]
**What version of OpenCart are you reporting this for?**
All

**Describe the bug**
If you go to  Sales--Orders and you want to filter Orders by customer name is annoying/bug when are more customer with the same name.

So when try to filter by customer name XX and are 2-3 customers with the same names, filter should compare/show orders for customer with name XX and same customer_id

If customers: 
XX (id 1) - display orders for XX where customer_id=1 and not all orders for XX name
XX(id 2) - display orders for XX where customer_id=2
XX(id 3) - display orders for XX where customer_id=3

**Comment by danielkerr** [comment]
should add filter_customer_id  so a link can be clicked to filter that customers orders. maybe a button called orders at the top of the customer edit page.

should be easy to implement. any one want to add this?
