### ISSUE TITLE
After placing Order,we disabled the customer then we edited the Order, In autocomplete shown disable customer but while choosing disabled customer we are not able to edit Order proccess. 

### ISSUE THREAD

**Issue by dilipkumardev** [opencart/opencart#7579]
**What version of OpenCart are you reporting this for?**
Version 3.1.0.0_b

After placing Order, we disabled the customer then we edited the Order, In autocomplete shown disable customer but while choosing disabled customer we are not able to edit Order process. 

**Expected behavior**
**Point: Either We will not show the disabled customer in autocomplete or we must be completed edit order process for this case.**

**Screenshots / Screen recordings**
http://i.prntscr.com/VX7lB_kTQSiG-whmekUlMw.png

**Comment by dilipkumardev** [comment]
Now I have update the warning message according to the customer status 
Screenshot http://i.prntscr.com/25swaE3FSr_CdiT_4PERJg.png 
I have created a pull request for the same, please check.
[https://github.com/opencart/opencart/pull/7580](https://github.com/opencart/opencart/pull/7580)

**Comment by dilipkumardev** [comment]
@jeffreyeng-opencart please check it

**Comment by dilipkumardev** [comment]
@jeffreyeng-opencart Could you please check this one functional issue.

**Comment by jeffreyeng-opencart** [comment]
@dilipkumardev: Please give me some time. I'm going through tons of issues and lots of people have been requesting to review or merge codes.

**Comment by danielkerr** [comment]
if they are doing a order history update they should do it from the order view and not order edit

**Comment by danielkerr** [comment]
im closing this. if u need to edit a disabled customer order then just enbale the customer first.
