### ISSUE TITLE
opencart website repeating my home page all content two times

### ISSUE THREAD

**Issue by prahatravichandan** [opencart/opencart#7589]
my website http://www.techtool.co.in is repeating all thing like navbar header footer and products and all content available at home page all thing are showing to time at home page please visit http://www.techtool.co.in

**Comment by SilverFoxWebDesigners** [comment]
Yes i have noted that issue on the latest Opencart versions 3.0.3.1 and 3.0.3.2 that when we add a product or a new category the items are getting duplicated.  It seems like a bug on the latest releases.

**Comment by condor2** [comment]
https://github.com/opencart/opencart/issues/7514

**Comment by prahatravichandan** [comment]
how can I solve it please tell me

**Comment by SilverFoxWebDesigners** [comment]
> how can I solve it please tell me

This problem is currently coming on the Chrome browser. Use firefox as this is the temporary solution i can suggest you bro
