### ISSUE TITLE
no order generation in case when the product price is less than the credit issued to the particular customer

### ISSUE THREAD

**Issue by Webkul-Opencart** [opencart/opencart#7590]
**What version of OpenCart are you reporting this for?**
Test Environment--
-- opencart version: 3.0.2.0

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
-- There is no order generation in case when the product price is less than the credit issued to the particular customer.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to opencart admin pannel
2. redirect to customers > customers > edit customer > transactions tab
3. add $1000 to that particular customer
4. now login with the same customer in the front end & checkout a product with the price less than $1000(credit issued) i.e $100(product price to be checkout).

**Expected behaviour**
1. An order should be generated & which should visible at admin end, under the sales > orders section as well as customer end under the order history section.
2. There should be deduction of $100 & also there should be an entry at customer end under the transaction section.
3. Quantity must be deducted of the ordered product.

**Screenshots / Screen recordings**
video-- [returns.mp4.zip](https://github.com/opencart/opencart/files/3588791/returns.mp4.zip)

**Server / Test environment (please complete the following information):**
opencart version: 3.0.2.0
operating system: Ubuntu 16.04 LTS
PHP version-- 7.0.33
browser/browser version: Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by prabhatkumaroc082** [comment]
No issue found in Version - 3.0.3.6
