### ISSUE TITLE
PDO error

### ISSUE THREAD

**Issue by bogdanr2000** [opencart/opencart#7596]
hi everybody,

i have encountered the following error, DB\mPDO:SQLSTATE[HY000]: General error
this error is generated by queries that do not return values, like update or delete;

any ideas about fixing this problem?

thanks

**Comment by danielkerr** [comment]
askig in frms this is no rrelated to oc development

**Comment by dis1** [comment]
Hi!

I have same problem using PDO. PDO rises fatal error when calling fetch() on statements that do not return data(update, insert ...): https://www.php.net/manual/en/pdostatement.fetch.php#105682.  
PDO wrapper(https://github.com/opencart/opencart/blob/master/upload/system/library/db/pdo.php) calls fetch() on every query. If one of them is update - site crashes. 
My oc version is 3.0.3.2.
Are there any plans to fix issue? Any workarounds?

Thank you!

**Comment by bogdanr2000** [comment]
Hi,

It looks like the problem really exists and i don't know why the issue was closed;

**Comment by danielkerr** [comment]
will check.

**Comment by jashk** [comment]
I think restrict fetch only if is a select sentence and count rows > 0 will fix this issue
