### ISSUE TITLE
[3.0.3.2] Administrator login into customer account is buggy

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#7598]
**What version of OpenCart are you reporting this for?**
3.0.3.2
**Describe the bug**
Go to the administrator area - customer list.
Choose a customer and try to login into one of the multi stores as customer.
What section does it affect?
It is possible to login only to the store where the customer is registered. The login process login only to the one store even if you choose a other store.
![image](https://user-images.githubusercontent.com/10166095/64826134-69feea00-d5c8-11e9-8934-50ba35e3200e.png)

**Expected behavior**
In the role as administrator I aspect to login to each store as customer.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? local and server
 - Operating system Linux
 - PHP version 7.3 and 7.2.22
 - Apache version 
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox 
 - Version [e.g. 22] 68.0.1

**Additional context**
As customer from the frontend it is possible to each store what is the correct behavior.

**Comment by yvonn** [comment]
Change line 391 in admin/controller/customer/customer.php
`'href' => $this->url->link('customer/customer/login', 'user_token=' . $this->session->data['user_token'] . '&customer_id=' . $result['customer_id'] . '&store_id=' . $result['store_id'], true)`
into
`'href' => $this->url->link('customer/customer/login', 'user_token=' . $this->session->data['user_token'] . '&customer_id=' . $result['customer_id'] . '&store_id=' . $store['store_id'], true)`
