### ISSUE TITLE
Customer logout after closing browser?

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7599]
**What version of OpenCart are you reporting this for?**
All Versions
**Describe the bug**
If a customer is logged in and customer close the browser or by mistake, the browser is closed and reopen the browser again than customer needs to log in again on the store.

**Comment by condor2** [comment]
With browser history enabled or disabled?

**Comment by WebkulOpencart** [comment]
With browser history enabled.
When a browser is closed then all the session object destroyed automatically. so we need to set the cookie time in the session library

**Comment by ADDCreative** [comment]
What browser? Firefox and Chrome (depending on settings) keep session cookies even after the browser is closed. Also persistence sessions aren't great for security.

**Comment by WebkulOpencart** [comment]
In both the browser firefox and chrome
