### ISSUE TITLE
Datepicker Layout major  issue http://i.prntscr.com/oAPWtqhSQh29q6JSAONdXg.png

### ISSUE THREAD

**Issue by dilipkumardev** [opencart/opencart#7602]
**What version of OpenCart are you reporting this for?**
Version 3.1.0.0_b

**Describe the bug**
datepicker layout issue

**To Reproduce**
1. Go to admin > catalog
2. click on the product
3. Special/discount tab

**Screenshots / Screen recordings**
http://i.prntscr.com/oAPWtqhSQh29q6JSAONdXg.png

**Comment by dilipkumardev** [comment]
Now We have fixed the issue please check screenshot.
http://i.prntscr.com/56Gmdsq4S7qq0FDU-K50MQ.png
I have created a pull request for the same, please check.
#7603

**Comment by jeffreyeng-opencart** [comment]
https://github.com/opencart/opencart/pull/7603

**Comment by jeffreyeng-opencart** [comment]
@dilipkumardev: Thanks!
