### ISSUE TITLE
Missing placeholder on option values sort order field after form submission at the Admin end  

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7604]
![Screenshot_3](https://user-images.githubusercontent.com/44575158/64867193-8a778480-d65a-11e9-91b9-69ead2f59009.png)
**What version of OpenCart are you reporting this for?**
3.1.0.0_b
**Describe the bug**
After form submission in the add option page from Admin end, than placeholder is missing in the option values sort order field.

**Comment by WebkulOpencart** [comment]
I have created a pull request for the same, please check here:- [https://github.com/opencart/opencart/pull/7605](https://github.com/opencart/opencart/pull/7605)

**Comment by jeffreyeng-opencart** [comment]
What browser were you using that cause the placeholder not to display? I've checked on my Chrome and was able to see a placeholder.

**Comment by jeffreyeng-opencart** [comment]
Nevermind. I've found your issue.
