### ISSUE TITLE
google recaptcha v2 not working properly

### ISSUE THREAD

**Issue by mehdiRma10** [opencart/opencart#7609]
Opencart 3.0.3.2

The contact forms are being sent even if the recaptcha v2 checkbox is not checked.

**To Reproduce**
1. Activate google recaptcha 
2. Go to contact or any other form from the site
3. Fill the infos
4. Don't check the box "i am not a robot"
5. You will be directed to success page

**Expected behavior**
Obviously the contact form isn't supposed to be sent when the recatptcha box isn't checked

Pull request with the issue fixed [here](https://github.com/opencart/opencart/pull/7608)

**Comment by jeffreyeng-opencart** [comment]
@mehdiRma10: Found a solution.

**Comment by jeffreyeng-opencart** [comment]
@mehdiRma10: Ignore the first push. Please look at the second one.
