### ISSUE TITLE
COD module problem

### ISSUE THREAD

**Issue by Rasul-Sh** [opencart/opencart#7610]
**What version of OpenCart are you reporting this for?**
3.0.2.0
**Describe the bug**
when i use the language load in the catalog/controller/mail/order.php  i face with JSON error in COD module (when confirm checkout)

**Screenshots / Screen recordings**
https://pasteboard.co/IxzKpP6.jpg

**Server / Test environment (please complete the following information):**
 - Test on local and server.
 - Centos 7
 - PHP Version 5.6 - 7
 - litespeed
 - chrome, Firefox

**Additional context**
when remove $this->load->language problem disappeared.

**Comment by danielkerr** [comment]
seems to be missing the url to redirect

**Comment by Rasul-Sh** [comment]
it's not related to url redirect, when in the file of   catalog/controller/mail/order.php i use language load, the error appear and remove the language solve the problem. i checked a few version of opencart and there is no code that related to url redirect. when an order registered in opencart . the catalog side user stay in checkout page and do not see success page . but in the admin page the order is done. if the use try to finish the order again he can see the complete page.
