### ISSUE TITLE
SQL Injection vulnerability found in fba extension

### ISSUE THREAD

**Issue by ka1n4t** [opencart/opencart#7612]
**What version of OpenCart are you reporting this for?**
2.2.0.0 ~ 3.0.3.2

**Describe the bug**
A SQL injection caused by inappropriate user input filtering.

**What section does it affect?**
openbay-fba extension

**To Reproduce**
1. Log in as administrator
2. Install "OpenBay Pro" extension
3. Enable "Fulfillment by Amazon"(Fba) plugin 
4. Visit upload/admin/index.php?route=extension/openbay/fba/orderList&user_token=your_token&filter_start=1%27%20and%20updatexml(1,concat(0x7e,(select%20user()),1),0x7e)--%20
(ps: Replace the user_token parameter with your own.)

**Expected behavior**
'select user()' will be executed and its result will be returned

**Comment by danielkerr** [comment]
there is no sql injection possibliy because the data that is not protected is only linked to amazon, ebay systems and can not be altered by users. openbay has been removed from the latest version but not because of this.

**Comment by ka1n4t** [comment]
But it shares the same database, hacker can still retrieve data from any table like oc_user.

**Comment by ADDCreative** [comment]
@ka1n4t As OpenBay is no longer included in OpenCart. Perhaps it would be useful to advise OpenBay directly, if you haven't already. https://www.openbaypro.com/
