### ISSUE TITLE
[Master branch] Review ratings not displayed correctly

### ISSUE THREAD

**Issue by Hackej** [opencart/opencart#7617]
**What version of OpenCart are you reporting this for?**
Master branch (3.1.0.0_b) and earlier versions since 3.0.3.1.

**Describe the bug**
Code for font awesome icons for Review ratings need to be changed in order for Reviews to be presented correctly. Currently master branch uses “fas fa-star“ for solid stars and “fas fa- star-o” for regular stars.

In order to display ratings correctly this should be “far fa-star” for regular stars in all occurrences in:
- Product page
- Category page
- Featured, Bestseller, Latest and Special extensions
- Manufacturer and Search. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any product with Reviews. 
Create review product if it’s missing (should be part of at least one product in demo?)
2. View Review and rating.

**Expected behavior**
The ratings should be presented with regular (non-solid) stars like in earlier versions (pic 1), instead of having missing regular stars as in current solution (pic 2).

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/29421668/65305584-df982680-db83-11e9-8de3-ede3f410531d.png)

![image](https://user-images.githubusercontent.com/29421668/65305615-efb00600-db83-11e9-85a6-5221d2cb3a58.png)

- Local development? Deployed to a web server? - Local host XAMPP
 - Operating system - Windows 10
 - PHP version - PHP 7
 - Apache version - Apache 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] - Firefox, Chrome
 - Version [e.g. 22] - Latest

**Additional context**
There is also a fix needed in order to display Review ratings in Feature module(s) as already noted in this issue: 
[Reviews not showing on featured product module (default template) V3.0.3.1](url)

BR
/Hackej

**Comment by jeffreyeng-opencart** [comment]
It's a Font Awesome update. They no longer have fa-star-o, but using a different approach to get an open star. I'm going to make some modification to get the open star appear, but will take some time.

**Comment by jeffreyeng-opencart** [comment]
Minor fixed on the twig files. I have to move around some CSS code to get it working.
