### ISSUE TITLE
Admin Login Loop

### ISSUE THREAD

**Issue by Spoony36** [opencart/opencart#7622]
**What version of OpenCart are you reporting this for?** 
3.0.3.2

**Describe the bug**
Did a fresh install and install was successful, however trying to log into my admin panel and after inputting the username and password I chose during install, as soon as I click login the screen flashes for a split second and just sticks on the admin login page without actually logging in.

Have deleted cookies, changed the password through phpadmin but still no luck

**Expected behaviour**
Login to administration pages

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/6922184/65554942-f2fc1680-df22-11e9-9ffc-370f2a5c7e27.png)

**Server / Test environment (please complete the following information):**
 - PHP version - tried switching to 5.6 and 7.3
 - Browser(s) tested with [e.g. chrome, safari - if applicable] - Edge and opera

**Comment by Spoony36** [comment]
Downloaded Version 2.3.0.2 to see if had the same issue but this version has no issues

**Comment by danielkerr** [comment]
You need to set your php time and mysql time the same. its deleting cookies to soon. You can fix this. 

Open:

system/config/default.php 

Find:

$_['session_engine']    = 'db';

Replace

$_['session_engine']    = 'file';

**Comment by Spoony36** [comment]
Many thanks for the response, that didn't work. I found the files you listed but there is no 

Find:
$_['session_engine'] = 'db';
Replace
$_['session_engine'] = 'file';

in system/config/admin.php

all that's in my file under session in the admin.php file is 

// Session
$_['session_autostart'] = true;

**Comment by danwalt2000** [comment]
Thanks a lot, tried out many solutions, but only your one helped! Fixed login loop in Opencart 3.0.0.2.

> You need to set your php time and mysql time the same. its deleting cookies to soon. You can fix this.
> 
> Open:
> 
> system/config/default.php
> system/config/catralog.php
> system/config/admin.php
> 
> Find:
> 
> $_['session_engine'] = 'db';
> 
> Replace
> 
> $_['session_engine'] = 'file';

**Comment by MarceloCaparoz** [comment]
Thanks danielkerr it  works fine!

**Comment by techm4ster** [comment]
> You need to set your php time and mysql time the same. its deleting cookies to soon. You can fix this.
> 
> Open:
> 
> system/config/default.php
> system/config/catralog.php
> system/config/admin.php
> 
> Find:
> 
> $_['session_engine'] = 'db';
> 
> Replace
> 
> $_['session_engine'] = 'file';
------------------------------------------------
YEA! DUDE, IT WORKED FOR MI. YOU ROCK! THNX

**Comment by techm4ster** [comment]
YEA! DUDE, IT WORKED FOR MI. YOU ROCK! THNX

**Comment by zawarnac** [comment]
> system/config/default.php 
> system/config/catralog.php
> 
> Find:
> 
> $_['session_engine'] = 'db';
> 
> Replace
> 
> $_['session_engine'] = 'file';


Great... It worked for me (y)

**Comment by jaideepchauhan** [comment]
> You need to set your php time and mysql time the same. its deleting cookies to soon. You can fix this.
> 
> Open:
> 
> system/config/default.php system/config/catralog.php system/config/admin.php
> 
> Find:
> 
> $_['session_engine'] = 'db';
> 
> Replace
> 
> $_['session_engine'] = 'file';

Many Thanks, It worked for me, after trying 100s of other workarounds. Kudoos

**Comment by katkevelaers** [comment]
I had this same issue after truncating the OC_sessions table.  Login loop in the admin section and also for customers.  This worked for me, so thank you very much.
I have V3.0.3.2

**Comment by stalker780** [comment]
Also check your cookies. 
OC3 has a bug which leads to outdated session cookies once they are created if you have cookie lifetime set in php.ini

https://github.com/opencart/opencart/commit/4be99a5c0df6e3cb6037053da8e3c854ee02e4b3
https://github.com/opencart/opencart/commit/ddfbf02102ff1569352a993dd8c3338af1b1b17b
