### ISSUE TITLE
klarna HTTP Request Redirection

### ISSUE THREAD

**Issue by haxcop** [opencart/opencart#7625]
**What version of OpenCart are you reporting this for?**
3.3.0.2
**Describe the bug**
High Security in Kiarma module 
What section does it affect?
system/storage/vendor/klarna/kco_rest/composer.lock
**To Reproduce**
Affected versions of guzzlehttp/guzzle are vulnerable to HTTP Proxy header vulnerability.

PHP through 7.0.8 does not attempt to address RFC 3875 section 4.1.18 namespace conflicts and therefore does not protect applications from the presence of untrusted client data in the HTTP_PROXY environment variable, which might allow remote attackers to redirect an application's outbound HTTP traffic to an arbitrary proxy server via a crafted Proxy header in an HTTP request, as demonstrated by (1) an application that makes a getenv('HTTP_PROXY') call or (2) a CGI configuration of PHP, aka an "httpoxy" issue.

**Expected behavior**
https://app.snyk.io/vuln/SNYK-PHP-GUZZLEHTTPGUZZLE-70104
**Screenshots / Screen recordings**

**Additional context**
Tested with Snyk

**Comment by ADDCreative** [comment]
It's not the main lock file and will be ignored? https://getcomposer.org/doc/02-libraries.md#lock-file

As far as I can see all compiled releases 2.3 and later do not have affected versions of guzzlehttp/guzzle.

**Comment by haxcop** [comment]
@ADDCreative I understand please look into composer.json 
`https://github.com/opencart/opencart/blob/master/upload/system/storage/vendor/klarna/kco_rest/composer.json`

**Comment by aboooodaj** [comment]
Are you working with you klarna invoice or Checkout am creating a new store (opencart Version 3.0.3.2) but I can't activate klarna

**Comment by jeffreyeng-opencart** [comment]
@aboooodaj: Please look this link:

https://github.com/opencart/opencart/issues/7630

**Comment by ADDCreative** [comment]
> @ADDCreative I understand please look into composer.json
> `https://github.com/opencart/opencart/blob/master/upload/system/storage/vendor/klarna/kco_rest/composer.json`

@haxcop That file is looks fine, it will allow composer to us the latest stable version less than 6.0, which will probably be 5.3.3.

**Comment by jeffreyeng-opencart** [comment]
https://github.com/opencart/opencart/issues/7237
