### ISSUE TITLE
3.1.0.0 - The directory admin/controller is not allowed to be written to!

### ISSUE THREAD

**Issue by howdu** [opencart/opencart#7627]
How are you supposed to install a standard extension now with 3.1? 

What was the reason for removing this?
https://github.com/opencart/opencart/commit/dc9b5c8e73748c29350c33db6966bfc3c671be44#diff-31e3525e9111363d065581cb6648cb76

**Comment by osworx** [comment]
Why would you install an extension ;)
We have already a perfect solution - we are waiting for since 2 years ..

**Comment by stalker780** [comment]
It's very sad there is no even any information about plans on that part.

It's quite definite that extension folder structure is changed but nobody knows how it will look like.

Some extensions could be adapted to work both in OC3.0 and OC3.1 during that time and be ready to use when OC3.1 is released.

**Comment by osworx** [comment]
Also very sad and frustrating, having after 2 years a partly working system, including major changes and not one of the core team (especially Daniel) is communicating!
Opencart stand and fail with 3PD - so some infos about the future would be good.

**Comment by danielkerr** [comment]
not sure what you mean but variants is working fine now.
