### ISSUE TITLE
OpenCart, why in admin do the files run 3 times?

### ISSUE THREAD

**Issue by masall** [opencart/opencart#7628]
Versions: "2.3.0.2" - "3.0.3.0" - "3.0.3.2".  
Sorry, if it's too simple!

- OpenCart, why in admin do the files run 3 times?
- What routines call the files the next 2 times?

The test was done like this:

In the file (framework.php), After dispatch. (// Dispatch code)
file_put_contents("file_01.txt", "Testing Version 3.0.3.2".PHP_EOL, FILE_APPEND);

--> Result of file "file_01.txt" after ONE Loading:
------------------------------
Testing Version 3.0.3.2
Testing Version 3.0.3.2
Testing Version 3.0.3.2
------------------------------
If anyone can enlighten me!
Thanks!

**Comment by danielkerr** [comment]
maybe some ajax in the background
