### ISSUE TITLE
Recommendation: Guzzlehttp upgrade to 6.3.3

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#7630]
Opencart use old Guzzlehttp PHP-library.
Almost all Guzzlehttp guidelines on the net apply Guzzlehttp 6.3.3

https://packagist.org/packages/guzzlehttp/guzzle

Version 6.3.3 is released about winter 2018, 6.3-dev is released summer 2019.
Current Opencart Guzzlehttp version 5.3.1 is old-fashioned, it is released  2015-2016.

---peku---

**Comment by ADDCreative** [comment]
OpenCart doesn't use Guzzlehttp directly (it's not in https://github.com/opencart/opencart/blob/master/composer.json). It's required by some of the payment module SDKs. These would need to be updated to use the later version.

**Comment by danielkerr** [comment]
which gateways use it?

**Comment by haxcop** [comment]
@danielkerr #7625

**Comment by ADDCreative** [comment]
Cardinity and Klarna Checkout as far as I can tell.

**Comment by pekka2** [comment]
> which gateways use it?

New gateways in Finland, eg. Checkout Finland PSP API and Shipit FI (large shippinf methods "collection")

**Comment by danielkerr** [comment]
added

**Comment by ADDCreative** [comment]
You can't have more than one version of a package. Now then main file requires 6 or greater but klarna/kco_rest and cardinity/cardinity-sdk-php require still a version less then 6. So a composer update will give error such as the following.

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - klarna/kco_rest v2.2.0 requires guzzlehttp/guzzle >=4.2,<6.0 -> satisfiable by guzzlehttp/guzzle[4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.x-dev] but these conflict with your requirements or minimum-stability.
>     - Installation request for klarna/kco_rest ^2.2 -> satisfiable by klarna/kco_rest[v2.2.0].

[As i said before](https://github.com/opencart/opencart/issues/7630#issuecomment-536337315). The Cardinity and Klarna Checkout modules need to be updated to use the later version of their SDK packages.

**Comment by pekka2** [comment]
https://github.com/pekka2/GuzzleHttp-6-PHP-composer

**Comment by ConnectGrid** [comment]
I've been going in circles and I think part of the problem is a discrepancy between the master branch and the latest release v3.0.33 have totally different composer.json files. This is confusing.

- master requires `php: ">=7.1.0"`
- latest release requires `php: ">=5.4"`

- master require Guzzle
- latest release does not require Guzzle

I would have expected the latest release to be a subset of master, but it seems to be based off of a totally different branch?

**Comment by ADDCreative** [comment]
Look at the version numbers. Latest release was for the 3.0 branch. Master is 3.1 branch.
