### ISSUE TITLE
V 3.0.3.2  Double definition

### ISSUE THREAD

**Issue by ThPel** [opencart/opencart#7632]
**What version of OpenCart are you reporting this for?**
V 3.0.3.2
**Describe the bug**
There is a double definition of $_['text_payment_cancel']   
in catalog\language\en-gb\checkout\cart.php

**Comment by Imonda** [comment]
true:
$_['text_payment_cancel']      = 'until cancelled';
$_['text_payment_cancel']      = '%s every %d %s(s) until canceled';

**Comment by peterwang1205** [comment]
Hi, is it a bug?

**Comment by jeffreyeng-opencart** [comment]
This is fixed and will be on the next release. For now, replace to:

$_['text_recurring_cancel']    = 'until cancelled';
