### ISSUE TITLE
master branch FedEx

### ISSUE THREAD

**Issue by atnaples** [opencart/opencart#7635]
what did guys smoke? in FedEx module (catalog/model/extension/shipping/fedex.php):

			if ($this->config->get('shipping_fedex_server') == 'gateway.fedex.com') {
				$url = 'https://' . (!$this->config->get('shipping_fedex_test') ? 'gateway' : 'gatewaybeta') . '.fedex.com:443/web-services/';
			} else {
				$url = 'https://' . (!$this->config->get('shipping_fedex_test') ? 'ws' : 'wsbeta') . '.fedex.com:443/web-services/';
			}

			$url = 'https://gatewaybeta.fedex.com/web-services/';

**Comment by danielkerr** [comment]
extension removed from the core and will have own page on opencart.com soon.
