### ISSUE TITLE
Problem with banner module when using .png

### ISSUE THREAD

**Issue by qwerty541** [opencart/opencart#7636]
When using the .png extension in banner module, images overlap each other. An example can be seen below

![lt4ijdBjgU](https://user-images.githubusercontent.com/53787217/65903200-ab630800-e3c4-11e9-9313-bbf102e8f985.gif)

The problem can be solved by adding css-property `background-color: $color_name` for all `<img />`. For this, I suggest adding a new option to the plugin settings, which by default will be equal to `transparent` or `white`. If someone needs it, he will be able to change this option and select the appropriate color.

If this solution is suitable, I could implement it and make a pull request.

**Comment by danielkerr** [comment]
dont use transparent pngs then

**Comment by danielkerr** [comment]
u should be using jpgs from banners.
