### ISSUE TITLE
Pagination issue in account / downloads - OpenCart 3.0.3.2

### ISSUE THREAD

**Issue by sabeti05** [opencart/opencart#7638]
OpenCart version 3.0.3.2

In customer account / downloads page if there are more than 10 downloads, pagination does not work properly because in this file:
catalog\controller\account\download.php
some times `$this->config->get('theme_' . $this->config->get('config_theme') . '_product_limit')` is used and sometimes 10:
```
$results = $this->model_account_download->getDownloads(($page - 1) * $this->config->get('theme_' . $this->config->get('config_theme') . '_product_limit'), $this->config->get('theme_' . $this->config->get('config_theme') . '_product_limit'));
...
...
...
$pagination->limit = $this->config->get('theme_' . $this->config->get('config_theme') . '_product_limit');
$pagination->url = $this->url->link('account/download', 'page={page}', true);
$data['pagination'] = $pagination->render();
$data['results'] = sprintf($this->language->get('text_pagination'), ($download_total) ? (($page - 1) * 10) + 1 : 0, ((($page - 1) * 10) > ($download_total - 10)) ? $download_total : ((($page - 1) * 10) + 10), $download_total, ceil($download_total / 10));
```

The similar issue exists in :
catalog\controller\account\return.php

**Comment by quamar17** [comment]
Replace $this->config->get('theme_' . $this->config->get('config_theme') . '_product_limit') line with 10, pagination working fine

**Comment by sabeti05** [comment]
Hi
Yes, I already fixed it for my site, I wanted to report it.

**Comment by jeffreyeng-opencart** [comment]
This pagination will have a revision for 3.1.x.
