### ISSUE TITLE
Klarna Checkout is broken! OC 3.0.3.2

### ISSUE THREAD

**Issue by MageSuper** [opencart/opencart#7639]
**What version of OpenCart are you reporting this for?** 3.0.3.2

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
I applied the fix/patch described here [Opencart fourm](https://forum.opencart.com/viewtopic.php?f=199&t=214105) and yet it did not and I was not able to activate it, nor the API info not returning upon editing the extension for the second time!

**To Reproduce**
1. Go to 'Fresh installation of OC 3.0.3.2, PHP 5.6'
2. Click on 'Install Klarna Checkout and try to activate it using the testing/developer api keys'

**Expected behavior**
It should just get activated and function as it should be!

**Screenshots / Screen recordings**
https://www.loom.com/share/fee9ff769c904f9e94d04cf4c401f33f

**Server / Test environment (please complete the following information):**
 - **Local development? Deployed to a web server?** Both, online and local server
 - **Operating system?** Ubuntu, Centos
 - **PHP version?** php 5.6
 - **Apache version?** apache 2.4
 - **Browser(s) tested with [e.g. chrome, safari - if applicable]:** Chrome
 - **Version [e.g. 22]:** Latewst

**Comment by aboooodaj** [comment]
I also tried but didn't work

**Comment by fyndpriser** [comment]
I have the same problem and unfortunately there is no solution yet!

**Comment by jeffreyeng-opencart** [comment]
@MageSuper: Have you upgrade your PHP version to 7.x? That will the minimum to start and more secure. Please try that and see if PHP upgrade will help resolve your issue.

**Comment by jeffreyeng-opencart** [comment]
@MageSuper: I just came across this:

https://github.com/opencart/opencart/issues/7630#issuecomment-536337315

Please see if you update your composer.json with above link and see if that works.

**Comment by aboooodaj** [comment]
@jeffreyeng-opencart
I have PHP 7.1 but don't work

**Comment by jeffreyeng-opencart** [comment]
@aboooodaj: Please look my comment:

https://github.com/opencart/opencart/issues/7639#issuecomment-544831240

**Comment by ADDCreative** [comment]
@jeffreyeng-opencart Won't work as that commit broke composer update. See my comment here. https://github.com/opencart/opencart/issues/7630#issuecomment-537620186

**Comment by jeffreyeng-opencart** [comment]
@ADDCreative: Have you tested on 3.1.0.b to see if it has the same issue?

**Comment by jeffreyeng-opencart** [comment]
@ADDCreative: 
I think you have found your answer: 
https://github.com/opencart/opencart/issues/7625#issuecomment-544954275

**Comment by jeffreyeng-opencart** [comment]
Found a reference: https://github.com/opencart/opencart/issues/7237

**Comment by aboooodaj** [comment]
I tried all of the above and also installed 3.1.0
But it didn't work
Solutions worked with anyone?
Thx

**Comment by soer792e** [comment]
Where are you in the fix of this ? 
as far as i understand, you know whats wrong, so why not fix t ?

**Comment by danielkerr** [comment]
extension removed from the core and will have own page on opencart.com soon.
