### ISSUE TITLE
[Master branch] common/header.php - extra lines

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7641]
**admin/controller/common/header.php**
```
$data['text_logged'] = sprintf($this->language->get('text_logged'), $this->user->getUserName());
```

**catalog/controller/common/header.php**
```
$data['text_logged'] = sprintf($this->language->get('text_logged'), $this->url->link('account/account', 'language=' . $this->config->get('config_language')), $this->customer->getFirstName(), $this->url->link('account/logout', 'language=' . $this->config->get('config_language')));
```

**Comment by jeffreyeng-opencart** [comment]
Was there an issue? Could you please clarify what version you are using and environment (ex. testing environment)?

**Comment by engwalid1971** [comment]
> Could you please clarify what version you are using ?

Master branch

**Comment by jeffreyeng-opencart** [comment]
I don't see any extra lines in the code, unless you provide screenshots to us. I'm going to close this issue. If you found the issues, either reopen this issue or open a new one.

**Comment by engwalid1971** [comment]
**admin/controller/common/header.php**
**catalog/controller/common/header.php**

'text_logged' need to remove as it is not used at all.
