### ISSUE TITLE
Admin panel Order edit error "Notice: Undefined index: master_id in dir_to_opencart/catalog/model/checkout/order.php on line 59" 

### ISSUE THREAD

**Issue by prabhatkumaroc082** [opencart/opencart#7644]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Describe the bug**
When you edit any order on admin panel and reach the final step to save order then you will get error **"Notice: Undefined index: master_id in dir_to_opencart/catalog/model/checkout/order.php on line 59"** 

**Steps to Reproduce**
1. Go to the orders list
2. View any order
3. Edit that order and do any changes or just go to final step
4. Now see the error as described

**Comment by prabhatkumaroc082** [comment]
here is the fix #7645

**Comment by danielkerr** [comment]
fixed already
