### ISSUE TITLE
SEO is used for new products / Opencart 2.0.3.1

### ISSUE THREAD

**Issue by PiklioBezGashti** [opencart/opencart#7647]
OpenCart 2.0.3.1

When im creating new product **sometime** im getting error message about SEO is used (but actually is not) when i press back button(without saving the NEW product) i can see new product is created,  i have 2 websites and both have same issue and cant find where is the problem and how this is possible  when by default system have validation

`if (($this->request->server['REQUEST_METHOD'] == 'POST') && $this->validateForm()){
$this->model_catalog_product->addProduct($this->request->post);
....
...
}`

that should prevent products to be created when SEO exist

**Comment by jeffreyeng-opencart** [comment]
@PiklioBezGashti: I strongly suggest two things:
1. check the OpenCart forum for solutions: https://forum.opencart.com/
or
2. upgrade to 3.0.3.x which will eliminate the issue you are having.

**Comment by PiklioBezGashti** [comment]
@jeffreyeng-opencart  on first look at the forum i didnt find anything similar to this in the forum is there anything that may help me to fix this issue ?

**Comment by jeffreyeng-opencart** [comment]
@PiklioBezGashti: I'm afraid it is outside our scope. I would strongly suggest to see if you could upgrade your current version to 3.0.3.x. After an upgrade, this issue should resolve.

**Comment by PiklioBezGashti** [comment]
@jeffreyeng-opencart ok i will try it thanks
