### ISSUE TITLE
Shop > Account >> Oder History: show only notified (internal note ?)

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#7648]
Ref: https://github.com/opencart/opencart/blob/6c1ade98fcc4398eef5aae862176ed14ff8e571f/upload/catalog/controller/account/order.php#L321

Nice if the customer was notified, but useless if no comment.
The more, the db.query should consider to get only those history entries which have the flag "notified".
E.g.: `AND oh.notify = '1' ORDER BY oh.date_added`

This way backend users can add a new order state which is ONLY for internal purposes - and not visible for the user himself.

**Comment by danielkerr** [comment]
new order state always needs to be notifiyed its the comment in the hiostory that needs to stay hidden.
