### ISSUE TITLE
Use of table-responsive helper breaks popover menus on lists

### ISSUE THREAD

**Issue by gRoberts84** [opencart/opencart#7649]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
When clicking on the split button on any lists, i.e. sales, customers where the table-responsive helper has been used, the popover is hidden by the overflow property set on the table-responsive class.

**To Reproduce**
- Log into OpenCart admin
- Go to Sales > Orders
- Click on the split button on the bottom row.

**Expected behavior**
Expect the popover to appear in full.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/348184/66576437-a09c3600-eb6f-11e9-8eac-7a2cd60cbaac.png)

**Server / Test environment (please complete the following information):**
 - Both locally and deployed.
 - OSX
 - 7.3
 - NGINX
 - Chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by danielkerr** [comment]
been reported before

**Comment by gRoberts84** [comment]
As this was closed incorrectly without tagging the "duplicate" issue, I am here for anyone else looking: 

#7257
