### ISSUE TITLE
.htaccess file

### ISSUE THREAD

**Issue by undercontr** [opencart/opencart#7651]
Is it possible to get .htaccess file? Because regular .htaccess file doesn't work with 3.1.0.0_b.

**Comment by jeffreyeng-opencart** [comment]
Could you please give me more detail? 

ex. Code in the .htaccess file. Environment (testing environment with XAMPP) with what version.

**Comment by undercontr** [comment]
Of course.

.htaccess file that works with the recent SEO updates (SEO Regex and some new SEO work) in 3.1.0.0_b.

CentOS Linux release 7.7.1908 (Core)
Apache/2.4.41 (Unix)
PHP 7.2.23 (cli)
10.4.8-MariaDB MariaDB Server

**Comment by jeffreyeng-opencart** [comment]
It is not .htaccess issue. There is a known issue code and currently working on it. Is your environment currently in development/testing?

**Comment by undercontr** [comment]
It is a testing environment in a virtual machine. Currently focused on SEO solutions for my project and SEO Regex is incredibly useful so that you can build an URL structure? I'll revert to 3.0.3.2 just to work on my project.

**Comment by jeffreyeng-opencart** [comment]
Great! The issue will resolve soon. I will go ahead and close issue.
