### ISSUE TITLE
Opencart API login Error: Undefined index: key in index.php?route=api/login

### ISSUE THREAD

**Issue by prosenjeet123** [opencart/opencart#7652]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
Well i am trying to make it work from last 2 days tried on 3.0.2.0 as well but same result. The Opencart API is not working the api/login.

Error:
<b>Notice</b>: Undefined index: key in <b>/catalog/controller/api/login.php</b> on line <b>14</b>[]

**To Reproduce**
Tried two seprate methods:
1. When i visit this url it throws an error
2. When sending with all required parameters and data using POSTMAN same error

**Comment by jeffreyeng-opencart** [comment]
Have you checked this link: https://forum.opencart.com?

Please check and see if this will resolve your issue:

https://forum.opencart.com/viewtopic.php?t=163748

**Comment by naumanahmad17** [comment]
Hi in order to use th API.
you have to make post request to 
> route=api/login 
 provide API username and key which you can find in admin section setting>users>api.
if none is there then generate one and use it.

**Comment by stalker780** [comment]
There must be a check for posted username and key.

Otherwise, any bot will spam your error.log file with warnings.
