### ISSUE TITLE
Problem when try to access Marketplace.

### ISSUE THREAD

**Issue by undercontr** [opencart/opencart#7653]
**What version of OpenCart are you reporting this for?** 
OpenCart 3.0.3.2

**Describe the bug**
When I use 3.0.3.2 in Centos 7 x64 1905.1/Apache 2.4/PHP 7.2.23/MariaDB 10.4.8
It gives "No Result" in the marketplace even against I entered my API information.
When you change `curl_setopt($curl, CURLOPT_POST, 1);` to `curl_setopt($curl, CURLOPT_POST, 0);` in `admin/controller/marketplace/marketplace.php`, it shows results but you can't get into the extension page.

All files run under apache:apache with 755 octal permission. I tried 777 too.
I also tried to run them under another user oc:apache with 755 and 777 octal permission.

The problem occurs in my test server in a virtual machine.

This topic is way too old. I saw many topic about this problem none of them was about OpenCart 3.

Any idea how to solve it?

**Comment by NickR2021** [comment]
Change to PHP 7.1 Version

**Comment by jeffreyeng-opencart** [comment]
@undercontr: I'm currently using XAMPP on my local machine with PHP 7.3.1. It is working fine. Have you tried to test on your local machine first? Have you check the setting in Linux if you could able to access through the internet?

**Comment by undercontr** [comment]
@jeffreyeng-opencart It works on localhost and Windows Server. Linux is able to connect to the internet because I did update the distro, I use github and also composer to install OpenCart and also disabled SELinux, PHP.ini have no conflict with the user.ini. Permissions are perfectly fine users are perfectly fine. I just don't understand why.

No problem with the internet. And also the result is same on Ubuntu, Debian, Arch Linux. There are people experiencing this issue while they host their OpenCart store on any linux distro. 

.htaccess file has no restrictions about connection. httpd.conf grants every user to the web directory. 

I just don't know what is this and how to solve it.

I also have one thing in mind:
I use a nosudoer user called "oc" that belongs to the same user group with "apache" for security reasons. But when I change all users to oc:apache, OpenCart works but gives errors. OpenCart changes some file to apache:apache, becasuse of that "oc:apache" files can't change and execute the "apache:apache" files. This is a big issue for security because apache:apache can be hijacked. This might be the issue for the marketplace problem. Maybe application don't let OpenCart connect to the internet in ceretain scenerios becasue it can't execute certain files to list extensions (because all files run under oc:apache)?

Before you ask, I also ran all files under apache:apache. No luck.

**Comment by jeffreyeng-opencart** [comment]
Have you checked the forum (https://forum.opencart.com/) if anyone in the community having this issue?

**Comment by jeffreyeng-opencart** [comment]
@undercontr: Have you found a solution within the forum (https://forum.opencart.com/)?

**Comment by undercontr** [comment]
@jeffreyeng-opencart No solution, unfortunately. There are issues that not resolved about the marketplace like for 1 or 2 years and nobody found a solution yet. I also thought maybe SELinux is the issue and tried to access the marketplace in permissive mode, no luck. I also tried with SELinux completely disabled and still no luck.

No errors or anything. I will just download extensions manually.

**Comment by jeffreyeng-opencart** [comment]
@undercontr: I see. Since this is outside my scope, you may have to raise this issue to support (https://support.opencart.com/) and go from there. I'm going to close this issue for now until you get a feedback from support.
