### ISSUE TITLE
Amazon Payment code has diverged? 

### ISSUE THREAD

**Issue by Nican** [opencart/opencart#7654]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
Amazon Payment is not working, and I am trying to track down the bug. I have noticed that the Amazon Payment code has diverged from `master`, and I am not sure how which code I should be using. 

I am looking at the history of `upload/catalog/controller/extension/payment/amazon_login_pay.php` for the past year. There are several commits that are on `master`, but not on `3.0.3.2`, and other commits that are on `3.0.3.2`, but not on `master`.

- https://github.com/opencart/opencart/commits/3.0.3.2/upload/catalog/controller/extension/payment/amazon_login_pay.php
- https://github.com/opencart/opencart/commits/master/upload/catalog/controller/extension/payment/amazon_login_pay.php

I am trying to understand how this works- which one is the latest change? Which one should be people using? 

Thank you in advance.

**Comment by Nican** [comment]
@simo-vt You seem to be a major contributor for this Amazon Payments extension. What is your take on this?

**Comment by simo-vt** [comment]
@Nican 

Hello, we have an open pull request here:

https://github.com/opencart/opencart/pull/7515

We are about to change it to include some fixes in the code.

To answer your question, the current latest version seems to be in the branch `3.0.3.2`

I will communicate with Daniel Kerr to see on which branch should we submit our latest pull request. Thanks for pointing this out.

**Comment by simo-vt** [comment]
@Nican 

A new pull request with the latest version has been created, you can find it here:

https://github.com/opencart/opencart/pull/7692
