### ISSUE TITLE
Can't restore or delete backup files by using admin tool backup/restore 

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7655]
**What version of OpenCart are you reporting this for?**
oc version 3.1.0.0_b
**Describe the bug**
A clear and concise description of what the bug is:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data.
The JSON Restore has the same error as the JSON Delete.

What section does it affect?
There are two files conflict: backup.twig and header.twig.
backup file JSON Delete section dataType: json
backup page header has DOCTYPE: html
**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by jeffreyeng-opencart** [comment]
@cgcmart: Could you please reproduce the steps of how you reach this bug issue?

**Comment by cgcmart** [comment]
log in admin panel
System >> Maintenance >> Backup / Restore

**Comment by jeffreyeng-opencart** [comment]
Then what's next? Have you attempted to export or import the database from Backup/Restore?

**Comment by cgcmart** [comment]
of course, they do not work!

**Comment by jeffreyeng-opencart** [comment]
I need additional information from you:

**Server / Test environment (please complete the following information):**

Local development? Deployed to a web server?
Operating system
PHP version
Apache version
Browser(s) tested with [e.g. chrome, safari - if applicable]
Version [e.g. 22]

**Comment by cgcmart** [comment]
The issue solved by reference to https://stackoverflow.com/questions/35237388/how-to-solve-syntaxerror-json-parse-unexpected-character-at-line-1-column-1-of?rq=1

Change admin/view/template/tool/backup.twig line 98, line 159, line 226, line 265
dataType: 'json'

to

dataType: 'html'
