### ISSUE TITLE
.htaccess.txt replace |.twig| -> |\.twig|

### ISSUE THREAD

**Issue by butsds** [opencart/opencart#7656]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
if its not in the code it will be after i finish seo url fixes

**Comment by cgcmart** [comment]
I believe that is a bug left a hole to spambot from the opencart site official release under download. I'd like to know what you think.

**Comment by danielkerr** [comment]
i think @ADDCreative already replied to you that this is not an issue.

we are already using the built in php hash system! stop opening threads to get attemntion!
