### ISSUE TITLE
Not work property_exists

### ISSUE THREAD

**Issue by eka7a** [opencart/opencart#7659]
Property_exists, new engine/loader.php and proxy.php changes do not work after.
https://github.com/opencart/opencart/blob/74c985e233b399817ff8bfeaf127ede4896f0a38/upload/catalog/model/checkout/order.php#L290

**Comment by jeffreyeng-opencart** [comment]
@eka7a: Could you please give us detail information:

1. Environment: testing or live
2. OC version
3. Steps that cause the issue

**Comment by eka7a** [comment]
@jeffreyeng-opencart 
1. Test
2. 3.1.0.0_b fresh install
3. Customer transaction, coupon, vouchers and reward points confirm/unconfirm and fraud check functions does not work in order processing.

Example: The customer has a $100 store credit. The customer bought a $500 product. At the end of the order must remain a $0 store credit but customer still have a $100 store credit.

These changes disable Property_exists control in engine/proxy.php.
https://github.com/opencart/opencart/commit/6dad4a94a64b73e60be78431fb630219b4cd3d9b#diff-98de1cb35b6032b8dc8e68985f59c888

It works when I make the following change.
https://github.com/opencart/opencart/pull/7663

**Comment by jeffreyeng-opencart** [comment]
I need to confirm with Daniel with this. I don't know if it will affect the security or not.

**Comment by danielkerr** [comment]
this has been fixed.
