### ISSUE TITLE
Error: Call to a member function get() on string

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#7661]
OC 3.1

**Describe the bug**
Error: Call to a member function get() on string in site\admin\controller\setting\setting.php on line 713

**To Reproduce**
1. Enable Recaptcha
2. Goto System->settings
3. Edit store

**Additional context**
Language bug
https://github.com/opencart/opencart/blob/88e00934a75e0fef129156b01d24aab5741e4469/upload/admin/controller/setting/setting.php#L713

**Comment by WebkulOpencart** [comment]
I have created a PR for the same here:- [https://github.com/opencart/opencart/pull/7667](https://github.com/opencart/opencart/pull/7667)
@jeffreyeng-opencart Please look into this.
