### ISSUE TITLE
Undefined index in seo_url.php

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#7662]
OC3.1

**Describe the bug**
Table oc_seo_regex have no `key` field
https://github.com/opencart/opencart/blob/88e00934a75e0fef129156b01d24aab5741e4469/upload/catalog/controller/startup/seo_url.php#L19

**To Reproduce**
1. Enable seo in settings
2. Open any page in frontend

**Comment by stalker780** [comment]
Sorry, I missed #7660

**Comment by chongshengdz** [comment]
has this issue fixed yet?
