### ISSUE TITLE
Previous and Next buttons for Banner Slideshow module in Home Page Conflicts with Brands Carousel module

### ISSUE THREAD

**Issue by amjtn** [opencart/opencart#7664]
Opencart 3.0.3.2 and also on previous version 3.0.2.0

When we click on Previous or Next button on the Banner Slideshow in Home Page the images for Brands Carousel also slides/changes

**Steps to reproduce the behavior**

1) Visit https://demo.opencart.com/
2) Click on the Previous or Next button on the Banner Slideshow
3) You can see that Images for both the Banner Slideshow and Brands Carousel slides/changes (which is wrong)
4) But when you click on pagination bullet button for the Banner Slideshow correctly images for the Banner Slideshow alone slides/changes

**Expected behavior:**

When the Previous or Next button on the Banner Slideshow is clicked only the images for Banner Slideshow should slide/change like pagination bullet button is working

**Comment by amjtn** [comment]
Hi,

Any Update on this?

Thanks

**Comment by jeffreyeng-opencart** [comment]
In the div class called "swiper-viewport" that wrapped the carousel:

`<div class="swiper-viewport">
  <div id="carousel{{ module }}" class="swiper-container">
    <div class="swiper-wrapper">
      {% for banner in banners %}
        <div class="swiper-slide text-center">
          {% if banner.link %}
            <a href="{{ banner.link }}"><img src="{{ banner.image }}" alt="{{ banner.title }}" class="img-fluid"/></a>
          {% else %}
            <img src="{{ banner.image }}" alt="{{ banner.title }}" class="img-fluid" />
          {% endif %}
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="swiper-pagination carousel{{ module }}"></div>
  <div class="swiper-pager">
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>
</div>
<script type="text/javascript"></script>`

Add unique class or id with the wrapper:

example:
`<div class="uniqueClass swiper-viewport">
  <div id="carousel{{ module }}" class="swiper-container">
    <div class="swiper-wrapper">
      {% for banner in banners %}
        <div class="swiper-slide text-center">
          {% if banner.link %}
            <a href="{{ banner.link }}"><img src="{{ banner.image }}" alt="{{ banner.title }}" class="img-fluid"/></a>
          {% else %}
            <img src="{{ banner.image }}" alt="{{ banner.title }}" class="img-fluid" />
          {% endif %}
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="swiper-pagination carousel{{ module }}"></div>
  <div class="swiper-pager">
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>
</div>
<script type="text/javascript"></script>`

That will differentiate which navigation buttons for which carousel.

**Comment by jeffreyeng-opencart** [comment]
In the div class called "swiper-viewport" that wrapped the carousel:

`<div class="swiper-viewport">`
`  <div id="carousel{{ module }}" class="swiper-container">`
`    <div class="swiper-wrapper">`
`      {% for banner in banners %}`

**Comment by jeffreyeng-opencart** [comment]
In the div class called "swiper-viewport" that wrapped the carousel:

`<div class="swiper-viewport">
  <div id="carousel{{ module }}" class="swiper-container">
    <div class="swiper-wrapper">
      {% for banner in banners %}`

**Comment by jeffreyeng-opencart** [comment]
In the div class called "swiper-viewport" that wrapped the carousel:

`<div class="swiper-viewport">`
`  <div id="carousel{{ module }}" class="swiper-container">`
`    <div class="swiper-wrapper">`
`      {% for banner in banners %}`
`        <div class="swiper-slide text-center">`
`          {% if banner.link %}`
`            <a href="{{ banner.link }}"><img src="{{ banner.image }}" alt="{{ banner.title }}" class="img-fluid"/></a>`
`          {% else %}`
`            <img src="{{ banner.image }}" alt="{{ banner.title }}" class="img-fluid" />`
`          {% endif %}`
`        </div>`
`      {% endfor %}`
`    </div>`
`  </div>`
`  <div class="swiper-pagination carousel{{ module }}"></div>`
`  <div class="swiper-pager">`
`    <div class="swiper-button-next"></div>`
`    <div class="swiper-button-prev"></div>`
`  </div>`
`</div>`
`<script type="text/javascript"><!--`
`$('#carousel{{ module }}').swiper({`
`	mode: 'horizontal',`
`	slidesPerView: 5,`
`	slidesPerGroup: 5,`
`	pagination: '.carousel{{ module }}',`
`	paginationClickable: true,`
`	nextButton: '.swiper-button-next',`
`	prevButton: '.swiper-button-prev',`
`	autoplay: 2500,`
`	loop: true`
`});`
`--></script>`

Add unique class or id with the wrapper and add it in the javascript (nextButton & prevButton)

example:
`<div class="unique-class swiper-viewport">`
`  <div id="carousel{{ module }}" class="swiper-container">`
`    <div class="swiper-wrapper">`
`      {% for banner in banners %}`
`        <div class="swiper-slide text-center">`
`          {% if banner.link %}`
`            <a href="{{ banner.link }}"><img src="{{ banner.image }}" alt="{{ banner.title }}" class="img-fluid"/></a>`
`          {% else %}`
`            <img src="{{ banner.image }}" alt="{{ banner.title }}" class="img-fluid" />`
`          {% endif %}`
`        </div>`
`      {% endfor %}`
`    </div>`
`  </div>`
`  <div class="swiper-pagination carousel{{ module }}"></div>`
`  <div class="swiper-pager">`
`    <div class="swiper-button-next"></div>`
`    <div class="swiper-button-prev"></div>`
`  </div>`
`</div>`
`<script type="text/javascript"><!--`
`$('#carousel{{ module }}').swiper({`
`	mode: 'horizontal',`
`	slidesPerView: 5,`
`	slidesPerGroup: 5,`
`	pagination: '.carousel{{ module }}',`
`	paginationClickable: true,`
`	nextButton: '.unique-class .swiper-button-next',`
`	prevButton: '.unique-class .swiper-button-prev',`
`	autoplay: 2500,`
`	loop: true`
`});`
`--></script>`

That will differentiate which navigation buttons for which carousel.

**Comment by amjtn** [comment]
Thank you jeffreyeng-opencart applied for your kindly help. After applying the solution it is working as expected
