### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by Stanislav93** [opencart/opencart#7665]
catalog/controller/product/category.php
before
`if (isset($this->request->get['filter'])) {`
`	$filter = $this->request->get['filter'];`
`} else {`
`	$filter = '';`
`}`
...
after
`$filter = $this->request->isgetv('filter');`

`$sort = $this->request->isgetv('sort', 'p.sort_order');`

`$order = $this->request->isgetv('order', 'ASC');`

`$page = $this->request->isgetv('page', 1);`

`$limit = $this->request->isgetv('limit', 20);`

system/library/request.php

/**
 * 
 * @param type $name
 * @param type $default = ""
 * @return type string
 */
public function isgetv($name, $default = "") {		
	return ((isset($this->get[$name])))?($this->get[$name]):$default;		
}
...

**Comment by diegospm** [comment]
I suggested something similar in PR #7490, with even deeper refactoring to remove many unnecessary repetitions.

As Daniel did not accept PR, I did not update my branch anymore, but I made some improvements in the classes I sent in PR and I'm using in my projects. It works like fine! :)

**Comment by Stanislav93** [comment]
But I wanted to start with a simple one, and there to act, depending on the reaction.

**Comment by diegospm** [comment]
You are right, but I believe it is not something they will do at the moment, but we planted a seed... ;)

The code can be further simplified, as I introduced in my project, for example:

$page = $this->request->get['page'] ?? 1;

Although they are dislike your proposal, perhaps because you used a simple example with an unusual OC nomenclature, in essence your suggestion is very positive!

**Comment by thekrotek** [comment]
A lot of OpenCart code can be shortened, but it will break almost every extension on the market. I'm afraid, it's too late for that.

**Comment by diegospm** [comment]
The biggest problem will be with extensions that use vqmod / ocmod, but reducing the codes will not change the final result of the values, there will only be an improvement in the applied logic.

Your fear is sensible, but I think in future versions this can be revised so developers can adjust to the changes.

Code reduction in OC will make it easier for everyone involved in maintenance, including for us developers :)

**Comment by thekrotek** [comment]
OpenCart already underwent a bunch of unnecessary changes, which made development much harder than it was. Any other severe changes will only make things worse. This is not a WordPress with close to perfect backward compatibility. OC never respected any compatibility, so at least let the code structure stay as is. Changing it won't give you anything besides smaller PHP file size.

**Comment by diegospm** [comment]
But the simpler the code the easier to maintain compatibility. I think it's not just to reduce file size, but to make things easier for the future...

**Comment by diegospm** [comment]
Also, the proposal would not touch the core and as I said could break some extensions that use ocmod / vqmod.

What we suggested was to improve something like:

`$url = '';
			if (isset($this->request->get['filter_name'])) {
				$url .= '&filter_name=' . urlencode(html_entity_decode($this->request->get['filter_name'], ENT_QUOTES, 'UTF-8'));
			}
			if (isset($this->request->get['filter_model'])) {
				$url .= '&filter_model=' . urlencode(html_entity_decode($this->request->get['filter_model'], ENT_QUOTES, 'UTF-8'));
			}
			if (isset($this->request->get['filter_price'])) {
				$url .= '&filter_price=' . $this->request->get['filter_price'];
			}
			if (isset($this->request->get['filter_quantity'])) {
				$url .= '&filter_quantity=' . $this->request->get['filter_quantity'];
			}
			if (isset($this->request->get['filter_status'])) {
				$url .= '&filter_status=' . $this->request->get['filter_status'];
			}
			if (isset($this->request->get['sort'])) {
				$url .= '&sort=' . $this->request->get['sort'];
			}
			if (isset($this->request->get['order'])) {
				$url .= '&order=' . $this->request->get['order'];
			}
			if (isset($this->request->get['page'])) {
				$url .= '&page=' . $this->request->get['page'];
			}`

I don't want to reinvent the wheel or change the world, but I think it's a pertinent subjec...

**Comment by straightlight** [comment]
Please create a Pull Request commit for those claims.
