### ISSUE TITLE
Return Statistics language variable is not loaded. 

### ISSUE THREAD

**Issue by prabhatkumaroc082** [opencart/opencart#7669]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Describe the bug**
Invalid language variable is called in controller **admin/controller/report/statistics.php** on line **188**
For returns, code will be **'returns'** and there is no language variable like **'text_returns'** under language file **admin/language/en-gb/report/statistics.php**

**Comment by prabhatkumaroc082** [comment]
here is the fix #7671

**Comment by jeffreyeng-opencart** [comment]
@prabhatkumaroc082: Have you pulled the most recent version from Master branch? If not, please pull and try again. Also, please update the database as well.
