### ISSUE TITLE
[Master branch] admin/view/stylesheet/stylesheet.css

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7672]
**The problem:**
The tables not scrolling horizontally.

![Screenshot from 2019-10-30 16-18-28](https://user-images.githubusercontent.com/48407821/67866141-26891c80-fb31-11e9-9929-d51302f27b31.png)

**The solution:**
Remove
```
.table-responsive {
    overflow: visible;
}
```
Please review the issue https://github.com/opencart/opencart/issues/7257 before take an action.

**Comment by jeffreyeng-opencart** [comment]
Need to study the scope of this issue before implementation, since it will affect everywhere else in the admin panel.
