### ISSUE TITLE
Undefined index: key in SEO regex page on the admin end.

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7683]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b
**Describe the bug**
Fatal error is showing when adding the new SEO regex from the admin.
When I looking into the seo_regex table and found that there is any column of key in the database table.

![Screenshot_1](https://user-images.githubusercontent.com/44575158/67952196-eac68380-fc12-11e9-9fde-af7ca3f0a3f4.png)
![Screenshot_3](https://user-images.githubusercontent.com/44575158/67952197-eb5f1a00-fc12-11e9-890e-d4c7da7b94bd.png)

**Comment by jeffreyeng-opencart** [comment]
@WebkulOpencart: Assigning to Daniel to check on this one.

**Comment by danielkerr** [comment]
already fixed in master branch
