### ISSUE TITLE
Admin end add new custom field page showing fatal error 

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7688]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b
**Describe the bug**
When adding new custom field after selecting only the required checkbox field than fatal error is showing on the screen.
Undefined index: customer_group_id in admin/controller/customer/custom_field.php on line 445

**Comment by jeffreyeng-opencart** [comment]
@WebkulOpencart: Could you please provide steps and screenshots what you have done that cause the error? So I could replicate the issue.

**Comment by WebkulOpencart** [comment]
@jeffreyeng-opencart Please submit the add new custom field form only selecting the required field, than you will see the error
