### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by qwerty541** [opencart/opencart#7690]
Before:
```php
$this->url->link('catalog/attribute/edit', 'user_token=' . $this->session->data['user_token'] . '&attribute_id=' . $result['attribute_id'], true);
```

After:
```php
$this->url->link(
    'catalog/attribute/edit',
    http_build_query(array(
        'user_token' => $this->session->data['user_token'],
        'attribute_id' => $result['attribute_id']
    )),
    true
);
```

**Comment by diegospm** [comment]
how about that: 

`$this->provider->link(['attribute_id' => $result['attribute_id']]);`

more readable, simpler and faster to write ;)

**Comment by diegospm** [comment]
I will soon publish a Repo that will make it easier to write url, breadcrumbs and analysis the data get/post on OC...

**Comment by straightlight** [comment]
Since this commit is rather about Pull Requests, it will now be closed. Please create your code requests, if not an actual issue you are reporting about, in the Pull Requests.
