### ISSUE TITLE
CKeditor HTML Content module display RAW

### ISSUE THREAD

**Issue by Hackej** [opencart/opencart#7695]
**What version of OpenCart are you reporting this for?**
Master Branch 3100b (downloaded 191103) updating previous installation of 3100b. 
 
**Describe the bug**
Can't get HTML content extension to work properly:
 
When adding code, for example HTML iframe link to other site, in CKEditor in "HTML Content" extension module it only displays raw code/text, this is alos the case when viewing the HTML block in any layout where I have put it.

It worked with Summernote in previous versions, but as far as I can see not in the latest versions since CKEditor was included. 

**To Reproduce**
1. Install HTML Content extension
2. Open and create new HTML Block extension
3. Enter Source mode and add HTML code by for example including embedded code generated by other site 
4. Toggle Source view to Ordinary view and you should be able to see the renedered html content. 
5. Go to Layouts and add HTML block to suitable layout
6. Got to chosen page and view new HTML block which in my case just is raw code 

**Expected behavior**
Be able to create and view HTML blocks as in previous versions.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/29421668/68137393-33d64a80-ff27-11e9-8f59-8c56e5349477.png)

**Server / Test environment (please complete the following information):**
 - -Local development? Deployed to a web server? - Local host XAMPP
 - Operating system - Windows 10
 - PHP version - PHP 7
 - Apache version - Apache 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] - Firefox, Chrome
 - Version [e.g. 22] - Latest

**Additional context**

BR
/Hackej

**Comment by jeffreyeng-opencart** [comment]
@Hackej: When you mentioned HTML Content extension, what extension is that or the actual name of the extension? Also, what page were you working on with the CKEditor?

**Comment by Hackej** [comment]
Hi!

It's the "HTML Content" module that is part of the default extensions in Opencart, where you can create new html modules to put anywhere on the site. You can create whetever you want.

I just created a new one and embedded code generated from other site (in this case Spotify) and this works with Summernote in for example ver 3.0.21. CKEditor seem to plain text rather than as code.

![image](https://user-images.githubusercontent.com/29421668/68284250-6a25de00-007d-11ea-9789-ef128b952f9b.png)

BR
/Hackej

**Comment by Hackej** [comment]
Sorry - dodn't mean to close it!!

/Hackej

**Comment by jeffreyeng-opencart** [comment]
@Hackej: No worries. Let us investigate and see what had happen.

**Comment by jeffreyeng-opencart** [comment]
@Hackej: Have you checked our forum (https://forum.opencart.com/) and see if anyone have a solution from there?

**Comment by jeffreyeng-opencart** [comment]
I've tested on my local machine. It is working fine. One your machine, do you have any javascript errors? You might try to do is to backup your database and reinstall OpenCart. See if it working with a fresh installation.

**Comment by Hackej** [comment]
Hi!

Yes, searched and looked but did not find anything similar.
Will look again and also do some more testing and tweaking.

BR
/Hackej

**Comment by jeffreyeng-opencart** [comment]
Ok. I'm going to close this issue for now. If it continues, reopen this issue or create a new one.
