### ISSUE TITLE
Info for new version oc 3.1.x.x

### ISSUE THREAD

**Issue by rsuchovsky** [opencart/opencart#7696]
Hi, I wanted to ask if it is realistic for the new version to be released by the end of this year.
Or what else do you plan to do before the new version is released.
Thx.

**Comment by dariygray** [comment]
This is of interest to many people

**Comment by iSaulius** [comment]
Those 2 years with an uncertainty redirect investment! 
Nothing personal is just a business.

**Comment by danielkerr** [comment]
my todo list

1. Add opencart account for admin marketplace (80%)
2. Add sql entry for current built in extensions so they can be uninstalled. (working on this now.)
3. fix design/seo_url

also in the background we are have a testable cloud solution ready.  

the subscription system needs merging in main site.
added the ssl for sub domains and domains
need to intergrate the api into the subscription system.

I'm aiming the cloud lauch the end of the year with a new version of opencart. 

Also with the cloud i'm thinking of moving all extension folders to be under the storage folder so its easier to backup and restore.

**Comment by Asim187** [comment]
hello.
when Opencart 3.1.x.x is going to be released?
actually looking for a **_product variant and language switcher through URL_** features into my store.
Thank You

**Comment by rsuchovsky** [comment]
Hi.
I would also ask info what it looks like with the new version.
If possible, info about real date release.
I have a feeling that the development has slowed down a lot last year.
Thank You.

**Comment by danielkerr** [comment]
i know it feels that way but i have been working on the main site. i have a working cloud solution with a subscription system. i just need to finish off a few more thingds then will get back to finishign the master release.

**Comment by rsuchovsky** [comment]
Thank you for the info :)
