### ISSUE TITLE
[3.0.3.1] index.php is displaying instead of the main OC page

### ISSUE THREAD

**Issue by GraceAredel** [opencart/opencart#7697]
Hello all. I have Opencart installed on localhost since I don't have an online shop or anything like that - I only use OC for writing automated tests with python and selenium.
So a few days ago I upgraded my home OS from Ubuntu 19.04 to 19.10 (which of course might me the cause) and after that when I open a browser and get the `localhost/opencart` or `127.0.0.1/opencart` I only see the index.php content which is:
```
<?php
// Version
define('VERSION', '3.0.3.1');

// Configuration
if (is_file('config.php')) {
	require_once('config.php');
}

// Install
if (!defined('DIR_APPLICATION')) {
	header('Location: install/index.php');
	exit;
}

// Startup
require_once(DIR_SYSTEM . 'startup.php');

start('catalog');
```

More info: config.php:
```
<?php
// HTTP
define('HTTP_SERVER', 'http://localhost/opencart/');

// HTTPS
define('HTTPS_SERVER', 'http://localhost/opencart/');

// DIR
define('DIR_APPLICATION', '/var/www/html/opencart/catalog/');
define('DIR_SYSTEM', '/var/www/html/opencart/system/');
define('DIR_IMAGE', '/var/www/html/opencart/image/');
define('DIR_STORAGE', DIR_SYSTEM . 'storage/');
define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');
define('DIR_TEMPLATE', DIR_APPLICATION . 'view/theme/');
define('DIR_CONFIG', DIR_SYSTEM . 'config/');
define('DIR_CACHE', DIR_STORAGE . 'cache/');
define('DIR_DOWNLOAD', DIR_STORAGE . 'download/');
define('DIR_LOGS', DIR_STORAGE . 'logs/');
define('DIR_MODIFICATION', DIR_STORAGE . 'modification/');
define('DIR_SESSION', DIR_STORAGE . 'session/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'ocuser');
define('DB_PASSWORD', 'PASSWORD');
define('DB_DATABASE', 'opencart');
define('DB_PORT', '3306');
define('DB_PREFIX', 'oc_');
```

[.htaccess.txt](https://github.com/opencart/opencart/files/3818645/default.htaccess.txt)
I added these lines: 
```
RewriteCond %{THE_REQUEST} \ /index\.php\?_route_=?([^&\ ]*)

RewriteRule ^ /%1? [L,R]
```

while trying to fix the problem by reading the OC forum.

Versions:
`PHP 7.3.11-0ubuntu0.19.10.1 (cli) (built: Oct 24 2019 11:38:49) ( NTS )`
`PHP 7.3.11-0ubuntu0.19.10.1 (cli) (built: Oct 24 2019 11:38:49) ( NTS )`

**Comment by jeffreyeng-opencart** [comment]
@GraceAredel: I'm trying to understand. When index.php appeared, it display the PHP code?

**Comment by TiredFingers** [comment]
If you want to use htaccess settings, you need to remove .txt from it's name. Because of that - what about your http server? Can you run another web site or just something like echo "ok"?

**Comment by danielkerr** [comment]
only if u are using apache and have mod rewrite on then index.php will disappear on seo urls. 

there is no issue here just you lack of common web programming sense.

**Comment by GraceAredel** [comment]
@jeffreyeng-opencart yes, exactly.

**Comment by jeffreyeng-opencart** [comment]
@GraceAredel: Then you may have to check your Apache (httpd.conf) or PHP (php.ini) setting to prevent displaying PHP code. I cannot remember where. You may have to search and find it.
