### ISSUE TITLE
unable to enter OpenCart API information - Page reload without anything working.

### ISSUE THREAD

**Issue by voyou-sbeaulieu** [opencart/opencart#7698]
**What version of OpenCart are you reporting this for?**
Version 3.0.2.0

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
We are trying to enter the OpenCart API information to have access to the marketplace ( currently no extensions are showing...) We create an account with the right domain ( tried with and without www ). Entred the credential and each time the "success" message popup and the page reload... Still no extensions in the list and if we click on the cog again there's no information saved.

**To Reproduce**
1. Log to the site admin
2. Click on extension/marketplace
3. click on the cog to enter the credential
4. Nothing has changed...
**No errors in backend interface nor in the error_log**

**Expected behavior**
We should have credential registered and access to the marketplace

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.loom.com/share/2cd08c31fa1f4734bcfefb9cc0068ef5

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?: **Deployed to a web server**
 - Operating system: user: **Mac OS (latest)** server: ngnix for backend apache for front-end (engintron https://engintron.com/)
 - PHP version: **7.2**
 - Apache version: **Apache/2.4.41 (cPanel)**
 - Browser(s) tested with [e.g. chrome, safari - if applicable] : **chrome**
 - Version [e.g. 22] **Version 78.0.3904.97 (Official Build) (64-bit)**

**Additional context**

**Comment by jeffreyeng-opencart** [comment]
@voyou-sbeaulieu: Two suggestions:

1. Upgrade to 3.0.3.2 
2. Go to official OpenCart MarketPlace website (https://www.opencart.com/index.php?route=marketplace/extension) to download your extension.
