### ISSUE TITLE
[3.0.3.2 + newer] Multistore order registration IP6 only in default store (Store0)

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#7699]
**Situation: **
Shop with 3 stores. 
- New customer is choosing products in store3 
- New Customer is going to checkout
- New Customer has to register
(For the customer everything looks good)
- Customer has to pay
- Customer get success message 

**Problem:**
During the customer registration there is a problem because the customer is registered with the wrong store_id.
- Customers with IP4 addresses get registered at store3
- Customers with IP6 addresses **get registered in store0 - and this is wrong**
As result the orders are fulfilled in store0 with wrong store variables

**Expected behavior:**
That customers with IP6 addresses get stored also in the correct store.

**Server:**
 - Local development? Deployed to a web server?
 - Operating system Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3 (2019-09-02) x86_64 
 - PHP version PHP Version 7.3.11
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] 
1. Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0
2. Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1

**Comment by prabhatkumaroc082** [comment]
@pemaier 
go to file catalog/controller/startup/startup.php and check lines 6 and 8 then print what is resulting? 
these queries are used to set store_id. 
also, check you have added the correct store URL.

**Comment by danielkerr** [comment]
i think he means he's getting the wrong emails from the wrong store. already fixed
