### ISSUE TITLE
[Sugestion] One page checkout

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7700]
After many and many Opencart versions I think next version 3.1 should have a different checkout, one page checkout.

**Comment by danielkerr** [comment]
anyone want to build one? i can include it.

**Comment by diegospm** [comment]
I think the best checkout approach is not the one page as it is not very intuitive for the user. I suggest something with this approach: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=20736&filter_search=checkout

**Comment by diegospm** [comment]
it would also be interesting to have a native abandoned cart recovery in OC

**Comment by Opencart-Webkul** [comment]
@danielkerr 
Hello Daniel,
We will build this one by considering our existing product (https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=26754) with some improvement.

**Comment by danielkerr** [comment]
go for it! still waiting on the maintenance release.

**Comment by danielkerr** [comment]
will be added one way or another. wont be this next release.
