### ISSUE TITLE
Coupon issue for the shipping

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#7701]
catalog/model/extension/total/coupon.php line 135:

`} elseif ($coupon_info['type'] == 'P') {`

must change:

`} elseif ($coupon_info['type'] == 'P' && $coupon_info['shipping'] == 0) {`

Ps. This bug has been in Opencart for ten years, is it not time to fix it? ;)

**Comment by ADDCreative** [comment]
@jeffreyeng-opencart This isn't a bug. You should be able to have a coupon with both a percentage discount and free shipping.

**Comment by jeffreyeng-opencart** [comment]
@ADDCreative: Now I'm looking back, your are right. Let me rollback the code.

**Comment by pekka2** [comment]
Sorry, boys haven't done a more extensive test with a coupon?
If you try use shipping discount 100%, shopping cart total price is 0€

**Comment by ADDCreative** [comment]
@pekka2 The coupons do not work that way. The discount field is only for products discount. It does not affect the shipping discount at all. For shipping you can select free shipping of no discount on shipping.

If you want a coupon code to offer 100% discount on shipping. You need to set the discount to 0 and select Yes for Free Shipping.
