### ISSUE TITLE
[3.0.3.2 +] Location store save problems already present - Ref. #6364

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#7702]
The error #6364 is already present in the new versions.

**Comment by engwalid1971** [comment]
To solve this issue you need to modify the file **admin/controller/setting/store.php**

**Replace:**
```
} elseif (isset($store_info['config_location'])) {
	$data['config_location'] = $this->config->get('config_location');
```
**With:**
```
} elseif (isset($store_info['config_location'])) {
	$data['config_location'] = $store_info['config_location'];
```

**Also add the code below to the validateForm() function**
```
if (!isset($this->request->post['config_location'])) {
	$this->request->post['config_location'] = array();
}

if (!isset($this->request->post['config_customer_group_display'])) {
	$this->request->post['config_customer_group_display'] = array();
}
```
**you can insert it before the line**
`return !$this->error;`

**Comment by pemaier** [comment]
Thank you!
I was testing it and it is working.


-----Original Message-----

**Comment by straightlight** [comment]
engwalid already posted this solution as a stand-alone commit. Therefore, this commit will not be closed.
