### ISSUE TITLE
[2.3.0.2 +] collapse sql query - report sale

### ISSUE THREAD

**Issue by rsuchovsky** [opencart/opencart#7707]
OC 2.3.0.2 maybe oc3 is also a problem.

If I receive more orders per day. For example 100 orders, sql query is executed long and fits.

Fatal error: Uncaught Exception: Error: MySQL server has gone away<br />Error No: 2006<br />SELECT MIN(o.date_added) AS date_start, MAX(o.date_added) AS date_end, COUNT(*) AS `orders`, SUM((SELECT SUM(op.quantity) FROM `oc_order_product` op WHERE op.order_id = o.order_id GROUP BY op.order_id)) AS products, SUM((SELECT SUM(ot.value) FROM `oc_order_total` ot WHERE ot.order_id = o.order_id AND ot.code = 'tax' GROUP BY ot.order_id)) AS tax, SUM(o.total) AS `total` FROM `oc_order` o WHERE o.order_status_id > '0' AND DATE(o.date_added) >= '2019-11-01' AND DATE(o.date_added) <= '2019-11-22' GROUP BY YEAR(o.date_added), WEEK(o.date_added) ORDER BY o.date_added DESC LIMIT 0,200

link: https://domain.com/admin/index.php?route=report/sale_order
dir: \admin\model\report\sale.php

**Comment by jeffreyeng-opencart** [comment]
@rsuchovsky: Anyway for you to write the sql query differently? Or use a combination of sql query and PHP to handle the data better? The way you write it might cause the database to use up the server resources and cause it to timeout.

**Comment by jeffreyeng-opencart** [comment]
@rsuchovsky: Have you resolved your issue?

**Comment by straightlight** [comment]
mySQL server has gone away is not an Opencart issue. You need to contact your host about this. This commit will now be closed.
