### ISSUE TITLE
[Master branch] admin/view/javascript/common.js

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7708]
**Replace:**
`$('#menu #dashboard').addClass('active');`

**With:**
`$('#menu #menu-dashboard').addClass('active');`

**Replace:**
```
$('#menu a[href=\'' + sessionStorage.getItem('menu') + '\']').parents('li > `a').removeClass('collapsed');
```
**With:**
```
$('#menu a[href=\'' + sessionStorage.getItem('menu') + '\']').parents('li').children('a').removeClass('collapsed');
```

**Comment by jeffreyeng-opencart** [comment]
@engwalid1971: Reason why the codes need to change?

**Comment by Grumvol** [comment]
Because there is no such id "dashboard"

**Comment by engwalid1971** [comment]
@Grumvol
You are right,, the correct id is #menu-dashboard
https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/column_left.php#L12

@jeffreyeng-opencart
Steps to reproduce the behavior:
1. Logging into the admin
2. Goto the 'products' page ( or any other page except the dashboard )
3. Click the OpenCart logo in the top left corner
4. You will see the dashboard page but with wrong left menu active items
![Screenshot from 2019-11-25 16-20-52](https://user-images.githubusercontent.com/48407821/69548572-411fab80-0fa0-11ea-924a-b8a8afd5360a.png)

**Comment by v5mvidal** [comment]
You have to delete Session Storage after the fix.

**Comment by danijelGombac** [comment]
`$('#menu #menu-dashboard').addClass('active')` is not necessary, 

`$('#menu-dashboard').addClass('active')` is enough.

Id should be unique.

**Comment by ilcomp** [comment]
I use php, example:`if ($active = strpos($route, 'design/seo_regex') === 0) {
	$seo_active = true;
}`

**Comment by straightlight** [comment]
Now added in the pre-release version. Thanks for posting this.
