### ISSUE TITLE
Newer MYSQL 8 Support

### ISSUE THREAD

**Issue by zhoub** [opencart/opencart#7709]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
Can't install without modification to the code.

**To Reproduce**

Install MySQL 8 Communication Version as usual, set Legacy Password mode to initialize the database.

Install the OpenCart, fill the database address, username, database name etc, the click Next.

Got error 

> Variable 'sql_mode' can't be set to the value of 'NO_AUTO_VALUE_ON_ZERO'

**Expected behavior**
Should work normally.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
Local
 - Operating system
OSX 10.13
 - PHP version
7.13
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**
Solution is here https://stackoverflow.com/questions/5496821/opencart-installation-problem

**Comment by jeffreyeng-opencart** [comment]
@zhoub: Have you commented or removed the ```SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO"```? Is it working after you have made the change in the sql file?

**Comment by jeffreyeng-opencart** [comment]
@zhoub: Have you resolved your issue?

**Comment by zhoub** [comment]
> @zhoub: Have you resolved your issue?

Yes, the error disappeared, but it would be great to let OpenCart to support newer MySQL8 also with new password mode, not plain password in config.php.

Thanks.

**Comment by jeffreyeng-opencart** [comment]
@zhoub: We are working on the new version. It is now: ```SET SQL_MODE=""```. Going to close this issue.

**Comment by jeffreyeng-opencart** [comment]
@zhoub: Also, please place your solution in our OC forum (https://forum.opencart.com/), so others will know.
