### ISSUE TITLE
I am getting a wired issue, I got double line item inventories on some order

### ISSUE THREAD

**Issue by yuvrajsjain** [opencart/opencart#7710]
Hey!

I am facing a wired issue on orders, I can see some of [b]my orders have duplicated line items[/b], I asked customer and found that they only want one and the other is added by system and users did not noticed about that, though credit card are charged for double already i.e. for all quantity in cart.

I did a lot of research on that and still I am not sure how this happens and what is the fixes for this.

I am attaching some images so you will understand the issue.

See how it looks on order panel.
https://prnt.sc/q1b8u1

When I check my oc_cart I can see there are few customers with  same product_id on database, see attached image.
https://prnt.sc/q1b5tm

This is how oc_order_product look
https://prnt.sc/q1b9t1

I am not sure why this duplicate line items on my store and how can I remove or prevent this. 

How it can be possible? I am using latest version of OC Version 3.0.2.0

This make us a lot of troubles , I need to fix it ASAP.

Thank you in advance.

**Comment by jeffreyeng-opencart** [comment]
@yuvrajsjain: I strongly contact our support either from our website (https://www.opencart.com/index.php?route=support/contact) or through email: opencart@zendesk.com to assist you with your situation.
