### ISSUE TITLE
Database session data field with insufficient size

### ISSUE THREAD

**Issue by bull5-i** [opencart/opencart#7711]
**What version of OpenCart are you reporting this for?**
OpenCart 3.0.3.2

**Describe the bug**
OpenCart 3.0.3.2 stores session info by default in the database, however the "data" field is defined as type "TEXT" which has a size limitation on 64kB. As shipping method data (in the checkout process) is also stored in the session, some shipping extensions which provide a big list of shipping options will overflow the session data and as such break the session, making checkout process impossible to complete.
I suggest changing the "oc_session" table "data" column definition to at least "MEDIUMTEXT" which can store upt to 16MB of data.

**To Reproduce**
1. Install & enable shipping method: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=27118
2. Try to checkout, after shipping method page is loaded, the session is broken, customer is logged out and clicking on "Continue" will show an empty cart page.

**Expected behavior**
Session should be able to store more than 64kB of data and it should not break.

**Server / Test environment (please complete the following information):**
 - Local development & Deployed to a web server
 - Operating system: x86_64-redhat-linux-gnu
 - PHP version: 5.6.40
 - Apache version: 2.4
 - Browser(s) tested with: Chrome, Safari, FF
 - Versions: latest

**Comment by LithMage** [comment]
Even better would be if opencart wouldnt store all shipping methods in session at all (as there is no reason to do that at all - or i fail to see one).

**Comment by straightlight** [comment]
Not related to master branch. Therefore, this commit will now be closed.

**Comment by ADDCreative** [comment]
Still relates to the master branch.

TEXT still used as the column type.
https://github.com/opencart/opencart/blob/dcd52bb7b0d1486c0e7a0b8d39a8039dbd60e05d/upload/system/helper/db_schema.php#L5313

Shipping methods still stored in the session.
https://github.com/opencart/opencart/blob/44e8df23b8f52e5bc7ee261267d2a8d3b82d8fa3/upload/catalog/controller/checkout/shipping_method.php#L39

**Comment by straightlight** [comment]
To dump data to a maximum size of 16MB, I doubt this would be a considered option at this point.
