### ISSUE TITLE
paypal 

### ISSUE THREAD

**Issue by happyxlq** [opencart/opencart#7714]
https://www.opencart.com/index.php?route=external/paypal_auth/connect

return 

{
  "url": "",
  "error": true
}

**Comment by jeffreyeng-opencart** [comment]
@happyxlq: Could you explain to me the steps to get to this issue?

**Comment by happyxlq** [comment]
> @happyxlq: Could you explain to me the steps to get to this issue?

install extensions -> install PayPal Express Checkout   -> edit PayPal Express Checkout

->click paypal configure live -> open a mimi minibrowser  but the url is wrong..

open code, Find:

admin\controller\extension\payment\pp_express.php 

line 4 	private $opencart_connect_url = 'https://www.opencart.com/index.php?route=external/paypal_auth/connect';

this url return a null url

**Comment by danielkerr** [comment]
this link has been removed from the master branch. you can apply for an account directly with paypal and add you account info to the extension.
