### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in admin/controller/marketplace/extension.php on line 48

### ISSUE THREAD

**Issue by newbie7777** [opencart/opencart#7728]
Version 3.0.3.2 (last 02.12.2019)

Clean installation, and a bunch of problems. Loading Extensions section, and i receive error.

Warning: Invalid argument supplied for foreach() in admin/controller/marketplace/extension.php on line 48
Any idea on the solution when I'm on line 48.

```
		foreach ($response_info['extension'] as $extension) {
			$this->model_setting_extension->addExtension($extension, '');
		}

```

best regards.

**Comment by jeffreyeng-opencart** [comment]
@newbie7777: Please check our forum (https://forum.opencart.com) for solution. Also, please send us your following information:

1. version of your environment (PHP,Database,etc)
2. steps that leads to this error

**Comment by jeffreyeng-opencart** [comment]
Since I don't hear from you, I'm going to close this issue.

**Comment by stevenmunro** [comment]
I'm also experiencing this issue. 

PHP 7.4
MySQL 8.0

**Comment by jeffreyeng-opencart** [comment]
@stevenmunro: Have you checked our forum (https://forum.opencart.com) for a solution?

**Comment by stevenmunro** [comment]
I have. Not being able to search more than 5 words is hindering my efforts.

**Comment by jeffreyeng-opencart** [comment]
@stevenmunro: What version of OC are you using?

**Comment by WebkulOpencart** [comment]
@stevenmunro I have created a PR for the same. Please check here:- [https://github.com/opencart/opencart/pull/7739](https://github.com/opencart/opencart/pull/7739)

**Comment by stevenmunro** [comment]
@jeffreyeng-opencart Version 3.0.3.2

I applied the pull request by @WebkulOpencart and it works now.

**Comment by gouiferda** [comment]
In OC Version 3.0.3.6 I fixed it by:
opening system/framework.php file and
going to near (line 58) searching for line that has: 
`foreach ($config->get('action_event') as $key => $value) {`
and add after it:
`if (is_string($value)) continue;`
