### ISSUE TITLE
input fields accepting blank space every where on the admin end in the catalog section

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7732]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b
**Describe the bug**
When entering the blank space in the input field inside any option of the admin ->catalog form validation not working and form is saving with empty data.
I am attaching the GIF for the same of recurring profile page as a example.
![recurringaccpetingblankspace](https://user-images.githubusercontent.com/44575158/70060515-b3c80100-1608-11ea-94f4-167186f0e408.gif)

**Comment by jeffreyeng-opencart** [comment]
@WebkulOpencart: Is there any other areas that has this problem? Might have to add ```empty(trim(fieldname))``` to remove spaces for validation.

**Comment by WebkulOpencart** [comment]
@jeffreyeng-opencart  I only check this in the Catalog section, for this I will create a PR by the end of the day for all the pages.

**Comment by WebkulOpencart** [comment]
@jeffreyeng-opencart I have created a PR for the same, which is only for the catalog section of admin end, Please check. [https://github.com/opencart/opencart/pull/7733](https://github.com/opencart/opencart/pull/7733)

**Comment by jeffreyeng-opencart** [comment]
@WebkulOpencart: Have these been tested?

**Comment by WebkulOpencart** [comment]
@jeffreyeng-opencart Yes, I have tested these changes from my end.

**Comment by jeffreyeng-opencart** [comment]
@WebkulOpencart: Thanks! I will start reviewing.
