### ISSUE TITLE
layout issues when error message is displayed

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7736]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b
**Describe the bug**
Fixed error message position issue when ck-editor is added on textarea than the CSS position is not working for the error message element and also when there are checkboxes then also CSS position is not working. I have already created a PR for the same here:- [https://github.com/opencart/opencart/pull/7734](https://github.com/opencart/opencart/pull/7734)
![css](https://user-images.githubusercontent.com/44575158/70203520-29d08300-1743-11ea-8a82-d7f7635dc97b.png)

**Comment by jeffreyeng-opencart** [comment]
@WebkulOpencart: Could you please share me the screenshot of your final result? I tried to duplicate the CSS, still unable to show the change.

**Comment by WebkulOpencart** [comment]
@jeffreyeng-opencart Actullay, this issue is in the add download form page, add information form page and review form page. I have done changes for the review page as well. Now, please check.
![reviewresult](https://user-images.githubusercontent.com/44575158/70204976-81252200-1748-11ea-8689-0c5df485afa5.png)

**Comment by jeffreyeng-opencart** [comment]
@WebkulOpencart: Thanks! Just making sure. Reviewing.
