### ISSUE TITLE
fatal error is showing when go to extension page on the admin end

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7738]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b
**Describe the bug**
Fatal error is showing when go to extension page.
![extension](https://user-images.githubusercontent.com/44575158/70242093-3c27dc80-1796-11ea-969b-8540688020c7.png)

**Comment by WebkulOpencart** [comment]
I have created a PR for the same, Please check here:- [https://github.com/opencart/opencart/pull/7739](https://github.com/opencart/opencart/pull/7739)

**Comment by jeffreyeng-opencart** [comment]
@WebkulOpencart: Daniel is currently working on the changes. I will put off the merge until I see where he stands in the changes.

**Comment by danielkerr** [comment]
in the process of setting up a core extension system so that we can define which extensions hsould be included in the core
