### ISSUE TITLE
double slash problem

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#7741]
model/tool/image
			
change

foreach ($directories as $directory) {
				$path = $path . '/' . $directory;
				if (!is_dir(substr(DIR_IMAGE,0,-1) . $path)) {
					@mkdir(substr(DIR_IMAGE,0,-1) . $path, 0777);
				}
			}

**Comment by jeffreyeng-opencart** [comment]
It's more of the setup (either OC installation or server setting) than the coding. Please check the config files and see if you have accidentally add an extra slash.

**Comment by ADDCreative** [comment]
@jeffreyeng-opencart It's not a setting issue. DIR_IMAGE is added to config.php with a / on the end by the installer. See: https://github.com/opencart/opencart/blob/30b0a42fe755583b67cfebac87e87ea8e860df6b/upload/install/controller/install/step_3.php#L24

The code in model/tool/image will always add a / to the start of the path. When DIR_IMAGE and path are combined for the mkdir you end up with two /. Such as ```/home/public_html/image//cache/catalog```. Although most OSs don't seem to care and the directories are created as expected.

Another way would be.
```php
foreach ($directories as $directory) {
	if ($path) {
		$path .= '/';
	}

	$path .= $directory;

	if (!is_dir(DIR_IMAGE . $path)) {
		@mkdir(DIR_IMAGE . $path, 0777);
	}
}
```
