### ISSUE TITLE
Master branch fails to install: Bad dependencies.

### ISSUE THREAD

**Issue by steowens** [opencart/opencart#7745]
Cloning master branch and running composer install results in: 

    $ composer install
    Loading composer repositories with package information
    Installing dependencies (including require-dev) from lock file
    Warning: The lock file is not up to date with the latest changes in composer.json. You may be 
    getting outdated dependencies. Run update to update them.
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - cardinity/cardinity-sdk-php v1.0.3 requires guzzlehttp/guzzle ~5.1 -> satisfiable by 
    guzzlehttp/guzzle[5.3.3] but these conflict with your requirements or minimum-stability.
        - cardinity/cardinity-sdk-php v1.0.3 requires guzzlehttp/guzzle ~5.1 -> satisfiable by 
    guzzlehttp/guzzle[5.3.3] but these conflict with your requirements or minimum-stability.
    - Installation request for cardinity/cardinity-sdk-php v1.0.3 -> satisfiable by cardinity/cardinity-sdk-php[v1.0.3].

Running composer update results in:

    $ composer update
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - klarna/kco_rest v2.2.0 requires guzzlehttp/guzzle >=4.2,<6.0 -> satisfiable by guzzlehttp/guzzle[4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.3.x-dev] but these conflict with your requirements or minimum-stability.
        - klarna/kco_rest v2.2.0 requires guzzlehttp/guzzle >=4.2,<6.0 -> satisfiable by guzzlehttp/guzzle[4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.3.x-dev] but these conflict with your requirements or minimum-stability.
        - Installation request for klarna/kco_rest ^2.2 -> satisfiable by klarna/kco_rest[v2.2.0].

Running composer -V results in: 

    $ composer -V
    Composer 1.8.4 2019-02-11 10:52:10

**Comment by ADDCreative** [comment]
The problem was the attempted fix for this non-issue. https://github.com/opencart/opencart/issues/7630

**Comment by danielkerr** [comment]
ADDCreative so what needs fixing?

**Comment by ADDCreative** [comment]
Reverting https://github.com/opencart/opencart/commit/807e1f34d9c4d502a8e580e589f20af93e2cd1f4 should sort the composer errors. OpenCart does not use Guzzle itself so there is no need for it to be in composer.json. Having it there just increases the chance if version clashes.

If you want to update Guzzle as requested by https://github.com/opencart/opencart/issues/7630 and https://github.com/opencart/opencart/issues/7625. The two lines in composer.json need looking at are.

https://github.com/opencart/opencart/blob/d3b8c1f5e5eb8745fe02065796fbe6c4c86bb09b/composer.json#L25 This line should be OK as it will allow version 1.1 on the Cardinity SDK which supports Guzzle 6. But that's assuming that upgrading the SDK from 1.0 to 1.1 won't break the payment module. The latest version is 2.1. https://github.com/cardinity/cardinity-sdk-php

https://github.com/opencart/opencart/blob/d3b8c1f5e5eb8745fe02065796fbe6c4c86bb09b/composer.json#L29 Version 3.0 is the minimum version of the Klarna SDK that supports Guzzle 6, with version 4.2.2 being the latest. So this would need changing to ```^3.0``` at the latest. Being one or two major versions above I would guess it would very likely break the payment module. https://github.com/klarna/kco_rest_php/releases

After changing the above and doing a composer update. The Cardinity and Klarna would need updating to work with the latest versions on the SDKs and then testing.

However, I've just noticed that the third-party payment payment modules are [being removed](https://github.com/opencart/opencart/commit/e9f81c2f34baa989978b48dc860ffccb634075d7). So it may be best to remove the payment SDKs from the composer.json and include them in the payment extension downloads.

**Comment by danielkerr** [comment]
i think fixed? open the issue if still exsits.

**Comment by zavan** [comment]
Master still fails. Checking out 3.1.0.0_a1 (`git checkout 3.1.0.0_a1`) works.
