### ISSUE TITLE
[Master branch] catalog/model/extension/shipping/weight.php

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7749]
**Replace:**
`if ($data[0] >= $weight) {`
**With:**
`if ($data[0] <= $weight) {`

**Comment by ADDCreative** [comment]
Why would you want to do that? Given the example of ```5:10.00```. It means anything 5 or under in weight costs 10. You change would mean anything over 5 would cost 10 and you could only ever set one weight.

**Comment by engwalid1971** [comment]
@ADDCreative
> Why would you want to do that? Given the example of `5:10.00`. It means anything 5 or under in weight costs 10. You change would mean anything over 5 would cost 10 and you could only ever set one weight.

You are right, anyway the issue has been closed.
