### ISSUE TITLE
Need to validate the existing addresses

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7750]
The order forms validate a new addresses only but not validate an existing addresses, therefore the customer can add an order with disabled country or zone

1. Add a new customer address and choose the zone USA/California.
2. Goto the admin panel and disable the California zone.
3. Goto the store front, add an order and choose the existing address.
4. The disabled zone will be accepted and the order will be added.

**Comment by danielkerr** [comment]
i think not a big issue because old orders need to retain their data
