### ISSUE TITLE
$affiliatee typo in upgrade script

### ISSUE THREAD

**Issue by andyplak** [opencart/opencart#7752]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
When performing a site upgrade via the install script I get the following error:

	SyntaxError: Unexpected token < in JSON at position 0 OK Notice: Undefined variable: affiliatee in /install/model/upgrade/1009.php on line 23{"success":"Patch 1009 has been applied (10 of 10)","next":"index.php?route=upgrade\/upgrade\/next&step=11"}

Specifically its this notice that throws the install if display_errors is on.

`Notice: Undefined variable: affiliatee in /var/www/html/bowcare-v3/install/model/upgrade/1009.php`

**Steps to reproduce**
Perform a site upgrade with error reporting ALL and display errors on.

**Server / Test environment (please complete the following information):**
 - Local development
 - Operating system: Ubuntu
 - PHP version: 7.2.24
 - Browser(s) tested with: Chrome

**Additional context**
Fix is simply to correct the var name from
`(int)$affiliatee['approved']`
to
`(int)$affiliate['approved']`

on line 23.

This is such a trivial bug, but has been present for over a year in the main download release.
https://opencart.com/forum/viewtopic.php?f=199&t=201445#p712546
It annoyed me enough to log a bug. ;)

**Comment by andyplak** [comment]
OK, I see this is a duplicate. Github issue search let me down.
#6634 and #7524  with a fix coming in #7265, however, why has this fix from six months ago not made it to the stable release on the Opencart Download site?

**Comment by straightlight** [comment]
Issue already fixed in the Master Branch.
