### ISSUE TITLE
admin/view/template/customer/customer_form.twig

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7755]
https://github.com/opencart/opencart/blob/6a95f816c1e2ea0acbd02f3309b346e69ed301a5/upload/admin/view/template/customer/customer_form.twig#L856
**Replace:**
`$('#tab-address' + address_row + ' .form-group[data-sort]')`
**With:**
`$('#address-row' + address_row + ' .form-group[data-sort]')`
_______________________________________________________
https://github.com/opencart/opencart/blob/6a95f816c1e2ea0acbd02f3309b346e69ed301a5/upload/admin/view/template/customer/customer_form.twig#L857
**Replace:**
`$('#tab-address' + address_row + ' .form-group')`
**With:**
`$('#address-row' + address_row + ' .form-group')`
_______________________________________________________
https://github.com/opencart/opencart/blob/6a95f816c1e2ea0acbd02f3309b346e69ed301a5/upload/admin/view/template/customer/customer_form.twig#L861
**Replace:**
`$('#tab-address' + address_row + ' .form-group')`
**With:**
`$('#address-row' + address_row + ' .form-group')`
_______________________________________________________
https://github.com/opencart/opencart/blob/6a95f816c1e2ea0acbd02f3309b346e69ed301a5/upload/admin/view/template/customer/customer_form.twig#L865
**Replace:**
`$('#tab-address' + address_row + ' .form-group')`
**With:**
`$('#address-row' + address_row + ' .form-group')`
_______________________________________________________
https://github.com/opencart/opencart/blob/6a95f816c1e2ea0acbd02f3309b346e69ed301a5/upload/admin/view/template/customer/customer_form.twig#L1180
**Replace:**
`$('#tab-address{{ address_row }} .form-group[data-sort]')`
**With:**
`$('#address-row{{ address_row }} .form-group[data-sort]')`
_______________________________________________________
https://github.com/opencart/opencart/blob/6a95f816c1e2ea0acbd02f3309b346e69ed301a5/upload/admin/view/template/customer/customer_form.twig#L1181
**Replace:**
`$('#tab-address{{ address_row }} .form-group')`
**With:**
`$('#address-row{{ address_row }} .form-group')`
_______________________________________________________
https://github.com/opencart/opencart/blob/6a95f816c1e2ea0acbd02f3309b346e69ed301a5/upload/admin/view/template/customer/customer_form.twig#L1182
**Replace:**
`$('#tab-address{{ address_row }} .form-group')`
**With:**
`$('#address-row{{ address_row }} .form-group')`
_______________________________________________________
https://github.com/opencart/opencart/blob/6a95f816c1e2ea0acbd02f3309b346e69ed301a5/upload/admin/view/template/customer/customer_form.twig#L1185
**Replace:**
`$('#tab-address{{ address_row }} .form-group')`
**With:**
`$('#address-row{{ address_row }} .form-group')`
_______________________________________________________
https://github.com/opencart/opencart/blob/6a95f816c1e2ea0acbd02f3309b346e69ed301a5/upload/admin/view/template/customer/customer_form.twig#L1189
**Replace:**
`$('#tab-address{{ address_row }} .form-group')`
**With:**
`$('#address-row{{ address_row }} .form-group')`
_______________________________________________________
https://github.com/opencart/opencart/blob/6a95f816c1e2ea0acbd02f3309b346e69ed301a5/upload/admin/view/template/customer/customer_form.twig#L1186
**Replace:**
`$('#tab-address{{ address_row }} .form-group:last')`
**With:**
`$('#address-row{{ address_row }} .form-group:last')`
_______________________________________________________
https://github.com/opencart/opencart/blob/6a95f816c1e2ea0acbd02f3309b346e69ed301a5/upload/admin/view/template/customer/customer_form.twig#L1190
**Replace:**
`$('#tab-address{{ address_row }} .form-group:first')`
**With:**
`$('#address-row{{ address_row }} .form-group:first')`
_______________________________________________________

**Comment by engwalid1971** [comment]
Please review the commits
https://github.com/opencart/opencart/commit/402ac51397b179038a65964c7d31a427d11e2398#diff-d2373fbb4fc8acbcbce536f3e5d062cb
https://github.com/opencart/opencart/commit/b086f689cf92b1dfe4bd164c40b8984c1883ab41#diff-d2373fbb4fc8acbcbce536f3e5d062cb

- The lines `{% set address_row = 1 %}` and `{% set address_row = address_row + 1 %}` has been deleted but it's needed for sorting the custom fields.
- You must start the address_row with '0', also you can see another wrong value '1' here
https://github.com/opencart/opencart/blob/d3b8c1f5e5eb8745fe02065796fbe6c4c86bb09b/upload/admin/view/template/customer/customer_form.twig#L295
Please note that, the default address depend on the index '0', please see
https://github.com/opencart/opencart/blob/d3b8c1f5e5eb8745fe02065796fbe6c4c86bb09b/upload/admin/controller/customer/customer.php#L816

**Comment by jeffreyeng-opencart** [comment]
> tab-address

Could you please tell me which line number? Don't want to accidently replace wrong one.

**Comment by engwalid1971** [comment]
> > tab-address
> 
> Could you please tell me which line number? Don't want to accidently replace wrong one.

Updated the original post ...

**Comment by engwalid1971** [comment]
Also need to replace:
```
html += '  <legend>{{ text_address }} ' + address_row + ' <button type="button" onclick="$(\'#address-row' + address_row + '\').remove();" data-toggle="tooltip" title="{{ button_remove }}" class="btn btn-danger btn-sm float-right"><i class="fas fa-minus-circle"></i></button></legend></legend>';
```
With:
```
html += '  <legend>{{ text_address }} ' + (address_row + 1) + ' <button type="button" onclick="$(\'#address-row' + address_row + '\').remove();" data-toggle="tooltip" title="{{ button_remove }}" class="btn btn-danger btn-sm float-right"><i class="fas fa-minus-circle"></i></button></legend></legend>';
```

**Comment by jeffreyeng-opencart** [comment]
> html += '  <legend>{{ text_address }} ' + (address_row + 1) + ' <button type="button" onclick="$(\'#address-row' + address_row + '\').remove();" data-toggle="tooltip" title="{{ button_remove }}" class="btn btn-danger btn-sm float-right"><i class="fas fa-minus-circle"></i></button></legend></legend>';

How come there are two closing legend tags?

**Comment by engwalid1971** [comment]
> > html += '  {{ text_address }} ' + (address_row + 1) + ' ';
> 
> How come there are two closing legend tags?

You are right, but the master OC code contain two closing legend tags, anyway the correct code is:
```
html += '  <legend>{{ text_address }} ' + (address_row + 1) + ' <button type="button" onclick="$(\'#address-row' + address_row + '\').remove();" data-toggle="tooltip" title="{{ button_remove }}" class="btn btn-danger btn-sm float-right"><i class="fas fa-minus-circle"></i></button></legend>';
```
