### ISSUE TITLE
Guest Checkout causes customer reward MySQL Error 1064

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7758]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
`Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''oc_customer_reward' WHERE 'customer_id' = '0'' at line 1<br />Error No: 1064<br />SELECT SUM(points) AS total FROM 'oc_customer_reward' WHERE 'customer_id' = '0' in /system/library/db/mysqli.php on line 43`

mysqli php threw a lot of this kind of exception errors. I believe the cause is guest ckeckout. oc customer did not assign or create "customer_id" for a guest after checkout completion. Is there any suggestion to fix this issue?

**Comment by straightlight** [comment]
Looks like an order total issue with the getRewardTotal() . In catalog/model/extension/total/reward.php file,

find:

```if ($this->model_account_customer->getRewardTotal($order_info['customer_id']) >= $points) {```

replace with:

```if ($order_info['customer_id'] && $this->model_account_customer->getRewardTotal($order_info['customer_id']) >= $points) {```

See if that solves the issue.
