### ISSUE TITLE
[Master branch] - admin ( route=design/seo_regex )

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7761]
`Notice: Undefined index: key in /var/www/html/opencart/admin/controller/design/seo_regex.php on line 178`

**The 'key' is missing from the 'seo_regex' table.**

**Comment by engwalid1971** [comment]
Also need to **replace:**
```
$data['sort_regex'] = $this->url->link('design/seo_regex', 'user_token=' . $this->session->data['user_token'] . '&sort=key' . $url);
```
**with:**
```
$data['sort_regex'] = $this->url->link('design/seo_regex', 'user_token=' . $this->session->data['user_token'] . '&sort=regex' . $url);
```

**Comment by engwalid1971** [comment]
**Also**
admin/model/design/seo_regex.php

**Replace:**
```
$sort_data = array(
	'name',
	'regex',
	'sort_order'
);
```
**With:**
```
$sort_data = array(
	'name',
	'key',
	'regex',
	'sort_order'
);
```

**Comment by jeffreyeng-opencart** [comment]
> `Notice: Undefined index: key in /var/www/html/opencart/admin/controller/design/seo_regex.php on line 178`
> 
> **The 'key' is missing from the 'seo_regex' table.**

Daniel is working on it.

**Comment by jeffreyeng-opencart** [comment]
I'm not going to make changes yet until Daniel completed his side.

**Comment by reetp** [comment]
Think these are linked:
https://github.com/opencart/opencart/issues/7683
https://github.com/opencart/opencart/issues/7660

For a quick test I added a column called 'key' to the seo_regrex table and that stopped the error and displayed the SEO Regex page, though I have no idea what else will break...!

No idea what should be in the 'key field'

**Comment by danielkerr** [comment]
already fixed in master branch
