### ISSUE TITLE
admin/language/en-gb/setting/setting.php

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7769]
Duplicated key, need to remove the first line ( typo ).
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/admin/language/en-gb/setting/setting.php#L156-L157

**Comment by straightlight** [comment]
This issue has been rectified recently on the master branch. I have also added the right conventional names in the pre-release version. Therefore, this commit will now be closed.
