### ISSUE TITLE
Duplicate keys in the language files

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7772]
- admin/language/en-gb/sale/order.php
`'text_reward'`
- admin/language/en-gb/setting/setting.php
`'text_return'`
`'help_login_attempts'`
- admin/language/en-gb/tool/upgrade.php
`'entry_name'`
- admin/language/en-gb/extension/report/customer_order.php
`'entry_status'`
- admin/language/en-gb/extension/report/marketing.php
`'entry_status'`
- admin/language/en-gb/extension/report/product_purchased.php
`'entry_status'`
- admin/language/en-gb/extension/report/sale_order.php
`'entry_status'`
- admin/language/en-gb/extension/report/sale_return.php
`'entry_status'`
- admin/language/en-gb/extension/report/sale_shipping.php
`'entry_status'`
- admin/language/en-gb/extension/report/sale_tax.php
`'entry_status'`
- catalog/language/en-gb/common/footer.php
`'text_contact'`
- install/language/en-gb/common/column_left.php
`'text_bg'`
`'text_fa'`
`'text_gd'`
- install/language/en-gb/install/step_2.php
`'text_status'`

**Comment by straightlight** [comment]
All entry_status duplicated fields have now been rectified to read entry_order_status or entry_return_status in the pre-release version along with the entry_status depending on the situation. Thanks for posting this.

**Comment by WebkulOpencart** [comment]
Duplicate keys already fixed so closing the same.
