### ISSUE TITLE
Twig files - Typo

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7773]
**admin/view/template/marketplace/installer.twig**

**Replace:**
```
$('#progress-text').html('<span class="text-success">' + json['success'] + '</div>');
```
**With:**
```
$('#progress-text').html('<span class="text-success">' + json['success'] + '</span>');
```
___
**admin/view/template/marketplace/marketplace_info.twig**

**Replace:**
```
$('#progress-text').html('<span class="text-success">' + json['success'] + '</div>');
```
**With:**
```
$('#progress-text').html('<span class="text-success">' + json['success'] + '</span>');
```
___
**admin/view/template/marketplace/marketplace_comment.twig**

**Duplicated** `</div>`
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/admin/view/template/marketplace/marketplace_comment.twig#L38-L39
___
**admin/view/template/catalog/product_form.twig**
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/admin/view/template/catalog/product_form.twig#L2504
**Replace:**
`html += '  <select></td>';`
**With:**
`html += '  </select></td>';`

**Comment by straightlight** [comment]
Relevant bugs were found in the pre-release version based on what's been reported here and now been rectified. Thanks for posting this.

**Comment by vicdurai** [comment]
Is this issue still pending ?

**Comment by WebkulOpencart** [comment]
issue is already fixed
