### ISSUE TITLE
Continuing - Twig files - Typo

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7774]
**catalog/view/theme/default/template/account/reset.twig**
**Replace:**
`</lis>`
**With:**
`</li>`
___
**admin/view/template/common/security.twig**

Duplicate `</li>`, line 132 and line 133
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/admin/view/template/common/security.twig#L132-L133
___
**install/view/template/upgrade/upgrade.twig**

**Replace:**
```
<input type="submit" value="{{ button_continue }}" data-loading="{ text_loading }}" id="button-continue" class="btn btn-primary" />
```
**With:**
```
<input type="submit" value="{{ button_continue }}" data-loading="{{ text_loading }}" id="button-continue" class="btn btn-primary" />
```
___
**catalog/view/theme/default/template/information/tracking.twig**
**Replace:**
`--></script>`
**With:**
`//--></script>`
___
**catalog/view/theme/default/template/extension/module/banner.twig**
**Replace:**
`--></script>`
**With:**
`//--></script>`
___
**catalog/view/theme/default/template/extension/module/carousel.twig**
**Replace:**
`--></script>`
**With:**
`//--></script>`
___
**catalog/view/theme/default/template/extension/module/slideshow.twig**
**Replace:**
`--></script>`
**With:**
`//--></script>`
___
**install/view/template/common/column_left.twig**
**Replace:**
`--></script>`
**With:**
`//--></script>`
___

**Note:** HTML comments `<!-- //-->` are no longer needed because the all modern browsers understand the `<script>` tag.

**Comment by straightlight** [comment]
Bug-fixes added on the pre-release version. Thanks for posting this.

**Comment by WebkulOpencart** [comment]
closing this issue as the issues is alrady resolved
