### ISSUE TITLE
Unparenthesized `a ? b : c ? d : e` is deprecated - Php 7.4

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7775]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
When run the installer it show this warning, after refresh is gone

`Unknown: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in system/storage/vendor/twig/twig/lib/Twig/Node.php on line 42`

And every time when you click on someting, buttons, categories..
You need to set to off Display errors.

**Server / Test environment (please complete the following information):**
 - PHP 7.4

**Comment by straightlight** [comment]
This error originates from a specific vendor script on Github, not from Opencart. Google the latest version of that extension or contact the vendor.

**Comment by condor2** [comment]
You are sure?

https://github.com/opencart/opencart/blob/master/upload/system/storage/vendor/twig/twig/lib/Twig/Node.php

**Comment by pixel-s-lab** [comment]
Update twig to the latest version and the error will disappear. link here [twig 3.0](https://github.com/twigphp/Twig)
