### ISSUE TITLE
Warning - Trying to access array offset on value of type null - PHP 7.4.0

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7776]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
This warning message is displayed on Error log using Php 7.4

**PHP Notice:  Trying to access array offset on value of type null in admin/controller/marketplace/extension.php on line 48**

Same in vendor/leafo/scssphp/src/Compiler.php on line 5230

**Server / Test environment (please complete the following information):**
 - PHP 7.4

**Comment by elanclarkson** [comment]
+1 Same problem here

**Comment by elanclarkson** [comment]
Not sure if there are other issues in PHP 7.4 yet but I managed to fix this error (which for me was occurring in storage/vendor/scss.inc.php) by changing this line:

`$key = $key[1];`

To this:

`$key = isset($key[1]) ? $key[1] : null;`

**Comment by condor2** [comment]
No missing column_left icons for you? :)

**Comment by elanclarkson** [comment]
Yes actually I realised the icons in the admin menu disappeared, and then ran into that problem with spacing which was causing css class names to merge together in some of the twig templates.

Ended up here https://github.com/twigphp/Twig/issues/3248 and then decided attempting to cradle Opencart into PHP 7.4 wasn't a good idea when they obviously just don't support it yet (or at least not in the version I'm using - v3.0.2.0).

**Comment by condor2** [comment]
Make this changes
https://github.com/condor2/Opencart_3031/commit/c4d819bfb46bc2539bdf9ffffd517961a081964b#diff-7277af3f09c80a4050d8e04b80c519f4

**Comment by condor2** [comment]
From **system/library/template/Twig/Lexer.php** 

Change this (line 164)
`$text = rtrim($text);`

Replace with:
`        // trim?
        if (isset($this->positions[2][$this->position][0])) {	        if (isset($this->positions[2][$this->position][0])) {
            $text = rtrim($text);	            if ($this->options['whitespace_trim'] === $this->positions[2][$this->position][0]) {
                // whitespace_trim detected ({%-, {{- or {#-)
                $text = rtrim($text);
            } elseif ($this->options['whitespace_trim'] === $this->positions[2][$this->position][0]) {
                // whitespace_trim detected ({%~, {{~ or {#~)
                // don't trim \r and \n
                $text = rtrim($text, " \t\0\x0B");
            }`

**Comment by wguerram** [comment]
@condor2 your if and elseif conditions evaluate the same?

**Comment by condor2** [comment]
https://github.com/twigphp/Twig/commit/1fb0f9701d8443083495cd2645e8a0c45d54c34d

**Comment by rodrigomanara** [comment]
I have found the same issue and I just done what @elanclarkson done as well and fixed the issue,
I don't if this fix was sugest to the verndor as well

**Comment by condor2** [comment]
> @condor2 your if and elseif conditions evaluate the same?

I think the best solution is this:

`        if ($this->options['whitespace_trim'] === $this->positions[2][$this->position][0]) {
            $text = rtrim($text);
        }`

**Comment by Giohuram** [comment]
Please can someone help me solve this issue??: 

Warning: Trying to access array offset on value of type null in /htdocs/wp-content/plugins/tuturn/templates/single-tuturn-instructor/education.php on line 39
