### ISSUE TITLE
Column Left Font awesome icons are not displayed - PHP 7.4

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7778]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**

Font Awesome Icons from Column Left are not shown.
The space from i class has no effect
`<i class="fas {{ menu.icon }} fw"></i>`

So to show you need to add a space in controller.
From:
`'icon'	   => 'fa-tags',`
To
`'icon'	   => ' fa-tags',`

**Comment by danielkerr** [comment]
this issue is not happening on my localhost.

**Comment by danielkerr** [comment]
maybe clearing cache will help

**Comment by condor2** [comment]
> this issue is not happening on my localhost.

Using php 7.4?

**Comment by condor2** [comment]
> maybe clearing cache will help

https://stackoverflow.com/questions/59248533/twig-problem-with-php-7-4-in-write-variable
