### ISSUE TITLE
Cookie Policy Popup is Broken - PHP 7.4

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7784]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
When you click on click here to see cookies policy the popup is broken/uggly.

**Expected behavior**
Should display only text popup and not entire store.

**Screenshots / Screen recordings**
![Screenshot_2019-12-22_16-10-08](https://user-images.githubusercontent.com/14251939/71322899-8d91d480-24d5-11ea-80b4-15c8b2319f0c.png)

**Server / Test environment (please complete the following information):**
 - PHP 7.4

**Comment by straightlight** [comment]
Anything showing in the console tab of the developers kit?

**Comment by condor2** [comment]
![Screenshot_2019-12-31_14-54-56](https://user-images.githubusercontent.com/14251939/71622315-8b1e3180-2bdd-11ea-9697-2d7b30035475.png)

**Comment by condor2** [comment]
Still not fixed.
![Screenshot_2020-07-24_18-05-09](https://user-images.githubusercontent.com/14251939/88405919-97b3e280-cdd8-11ea-9647-f1c30f160330.png)
