### ISSUE TITLE
OpenCart Tracking does not work

### ISSUE THREAD

**Issue by Khaleel** [opencart/opencart#7786]
**What version of OpenCart are you reporting this for?**
Latest 3x
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

The template for tracking no feature is completed
https://github.com/opencart/opencart/blob/master/upload/catalog/view/theme/default/template/information/tracking.twig

The button does not exist and jQuery is not working - why is this committed to code?

**Comment by straightlight** [comment]
Mentioning that jQuery is not working is insufficient. What are the actual results / outputs noticing different behaviors from jQuery? For instance, in the Developers Tool of your browser (F12) - > Console Tab, do you notice any errors when clicking the button in the information tracking page?

More information is needed.

**Comment by Khaleel** [comment]
1 - The button does not even existing in HTML
2 - The page title does not appear
3 - Controller for this file appears empty- is this even a production ready feature?

Image: https://ibb.co/f0PgHLn

**Comment by condor2** [comment]
@Khaleel you should not use this version in production. Isn't released yet.
Latest release is 3.0.3.2

**Comment by Khaleel** [comment]
I installed OpenCart from CloudWays automated control panel

Khaleel Mughal

**Comment by condor2** [comment]
Yep....checked right now and that file is also on 3.0.3.2.

**Comment by Khaleel** [comment]
Yes so this is a bug and needs fixing - I am on Version 3.0.2.0
Would be nice to have this feature done

**Comment by straightlight** [comment]
There's a small bug-fix solution that has been recently posted about that file: https://github.com/opencart/opencart/issues/7774#issue-541320854 . See if that solves the reported issue.

**Comment by Khaleel** [comment]
Hi. No that does not resolve the issue as I already fixed the JS comment tag.
The issue is the controller is not complete and this feature is not even in the documentation yet it is in the source code.

@danielkerr can you shed light on this?

**Comment by Khaleel** [comment]
Anyone?

**Comment by condor2** [comment]
You can try to convert this module until you get a response...
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=1751

**Comment by straightlight** [comment]
Take note that the above extension is compatible with older OC versions. Not related with the Github version.

**Comment by condor2** [comment]
> Take note that the above extension is compatible with older OC versions. Not related with the Github version.

Yes. That why I write **convert** :)

**Comment by straightlight** [comment]
> > Take note that the above extension is compatible with older OC versions. Not related with the Github version.
> 
> Yes. That's why I write **convert** :)

Doesn't matter. This namespace is for the Github version, not for prior versions of OC. If suggestions needs to be made to use an extension that does not involve using the Github version, in addition to say that the Github version should not be used for production, please post those suggestions on the OC forum.

**Comment by WebkulOpencart** [comment]
As I checked there is no complete functionality for the tracking on the frontend.

[https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/language/en-gb/information/tracking.php](https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/language/en-gb/information/tracking.php)

[https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/controller/information/tracking.php](https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/controller/information/tracking.php)

**Comment by danielkerr** [comment]
this is an uncompleted system. there should be no links to this from the site. it will be removed for now.
