### ISSUE TITLE
Session fixes

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7787]
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/system/library/session.php#L36
**Replace:**
`trigger_error('Error: Could not load cache adaptor ' . $adaptor . ' session!');`
**With:**
`trigger_error('Error: Could not load session adaptor ' . $adaptor . ' session!');`
___
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/system/library/session/db.php#L26
**Replace:**
`return false;`
**With:**
`return array();`
___
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/system/library/session/file.php#L4
**Unused variable**
___
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/system/library/session/file.php#L9
**Replace:**
`if (is_file($file)) {`
**With:**
```
$expire = time() - ini_get('session.gc_maxlifetime');

if (is_file($file) && filemtime($file) > $expire) {
```
___

**Comment by straightlight** [comment]
@engwalid1971: There's also a date time formatting versus session synchronization issue going on right now. I have just referred both commits to ensure both of the reported subjects can lead to a resolution. Let's find out!
