### ISSUE TITLE
category menu issue

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#7788]
![menu](https://user-images.githubusercontent.com/30888843/71553484-013e5f00-2a4b-11ea-8e8a-ef9fe7689a7b.jpg)
version: 3.1.0.0_b
all categories are in one line and will not start in a new line like before.

**Comment by danielkerr** [comment]
thats what the top checkbox in the categories page is for. do not add more categories than your them can take. not rocket science.
