### ISSUE TITLE
OpenCart Forum Login Session Fail

### ISSUE THREAD

**Issue by uksitebuilder** [opencart/opencart#7789]
There appears to be a problem on the OpenCart.com Forums

Login session does not persist.

I wondered why it had gone deathly silent on there these last few days

**Comment by condor2** [comment]
Maybe because new year is close?

For me, login work just fine.

**Comment by uksitebuilder** [comment]
hmm, seems fixed now for me too.  A few people had experienced this apparently.

Gremlins in the system I think

**Comment by uksitebuilder** [comment]
I spoke too soon.  It's back and losing login again. Hopefully someone in control of the forfum server can look in to this as it will be affecting many people.

**Comment by straightlight** [comment]
Cloudflare

**Comment by osworx** [comment]
> 
> 
> Cloudflare

Aha .. means what??
More important: when will it be fixed and who is doing that!

**Comment by straightlight** [comment]
Cloudflare services can be a bit tricky and surprising with their changes at times. Nothing is perfect with filtering as we all know. It;s beyond our control but as soon as the Opencart team takes the time to review the issue and if this reported issue becomes a major one eventually, it should be taken care of.

**Comment by osworx** [comment]
Yes - most of us know that.
But this issue is not a small one and I reported it already yesterday in the forum!
And - as we all know, the forum is one major entry point of OpenCart.
And within 24 hours, every team should be able to "wake up".

**Comment by condor2** [comment]
Who has access to the Cloudflare account can play with the settings...

**Comment by straightlight** [comment]
Just got words this morning that the issue should now be resolved. Please clear all your browser's cache, close your browser and re-open. Re-login to the forum and see if the issue persists or if you're all able to remain logged in without being auto-logged out.

**Comment by danielkerr** [comment]
It should be fixed now. Can anyone confirm this?

**Comment by danielkerr** [comment]
I had to change the ip_check to 0 in the settings table. Before that I could not even access the admin

**Comment by mhcwebdesign** [comment]
I had the session issue for the past few days now. However, it seems to be working fine now again.

BTW.: Is there a reason why you have to use CloudFlare? CloudFlare tends to slow down things, contrary to what they promise!

**Comment by straightlight** [comment]
> 
> 
> I had the session issue for the past few days now. However, it seems to be working fine now again.
> 
> BTW.: Is there a reason why you have to use CloudFlare? CloudFlare tends to slow down things, contrary to what they promise!

If the case, then forum moderators should also be notified since they do refer Cloudflare as a positive asset to be used: https://forum.opencart.com/viewtopic.php?t=209986#p746517 .

**Comment by mhcwebdesign** [comment]
straightlight: I posted my CloudFlare experience on the OpenCart forum mentioned by you a few months ago. CloudFlare might be cheap, but is not worth the trouble because of its poor performance .
