### ISSUE TITLE
SSL change to Default

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#7790]
system/url.hp  line 51:
`public function link($route, $args = '', $js = false) {
`
I recommed change to:
`public function link($route, $args = '', $js = true) {`

**Comment by ADDCreative** [comment]
@pekka2 The $js parameter just controls the ampersand escaping. Has nothing to do with SSL.

**Comment by straightlight** [comment]
Closing issue since this is a code suggestion change, not an actual bug with Github's version.

**Comment by pekka2** [comment]
> Closing issue since this is a code suggestion change, not an actual bug with Github's version.

This is bug. Few in server must be change that '$js = true'. If it is 'false', SSL is not work.
