### ISSUE TITLE
Email from Marketing

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#7791]
Page admin > marketing > post
When send message to the selecter customer, show message:

`Your message has been successfully sent to 0 of 0 recipients`

The email went to the recipient.

**Comment by straightlight** [comment]
For which OC version?

**Comment by straightlight** [comment]
Codes already modified on the Github version.

**Comment by pekka2** [comment]
> For which OC version?

OC 3.0.3.2 from my live store

**Comment by Pankti16** [comment]
Same for me, OC Version 3.0.2.0

**Comment by ADDCreative** [comment]
Duplicate of https://github.com/opencart/opencart/issues/6110 which was fixed with https://github.com/opencart/opencart/commit/557de54bf590670e6bbf9978e72fc8dbe6903419.

**Comment by m-margaryan** [comment]
admin/controller/marketing/contact.php file,

find:
Code: Select all

$json['success'] = sprintf($this->language->get('text_sent'), $start, $email_total);
replace with:
Code: Select all

$json['success'] = sprintf($this->language->get('text_sent'), $start, sizeof($emails));

**Comment by xiarongwei** [comment]
> admin/controller/marketing/contact.php file,
> 
> find:
> Code:
> 
> $json['success'] = sprintf($this->language->get('text_sent'), $start, $email_total);
> replace with:
> Code:
> 
> $json['success'] = sprintf($this->language->get('text_sent'), $start, sizeof($emails));

When i modified the file, I writed the email again to one customer ,the msgbox will show ,"Internal Server Error <b>Notice</b>:Undefined variable: sizeof in <b> /var/www/html/admin/controller/marketing/contact.php</b> on line <b>191</b
