### ISSUE TITLE
tags in catalog/view/theme/default/template/product/product.twig

### ISSUE THREAD

**Issue by tryby** [opencart/opencart#7792]
is:
`
{% if tags %}
          <p>
            {{ text_tags }}
            {% for i in 0..tags|length %}
              {% if i < (tags|length - 1) %} 
                <a href="{{ tags[i].href }}">{{ tags[i].tag }}</a>,
              {% else %} 
                <a href="{{ tags[i].href }}">{{ tags[i].tag }}</a> 
              {% endif %}
            {% endfor %} 
          </p>
{% endif %}
`
an empty tag is created at the end
should:
`
{% if tags %}
          <p>
            {{ text_tags }}
            {% for i in 0..tags|length - 1 %}
              {% if i < (tags|length - 1) %} 
                <a href="{{ tags[i].href }}">{{ tags[i].tag }}</a>,
              {% else %} 
                <a href="{{ tags[i].href }}">{{ tags[i].tag }}</a> 
              {% endif %}
            {% endfor %} 
          </p>
{% endif %}
`

**Comment by straightlight** [comment]
For which OC version?

**Comment by tryby** [comment]
3.0.3.2

**Comment by straightlight** [comment]
Same symptom found on Github codes. Let's wait for Daniel's version on this one when visiting the topic.
