### ISSUE TITLE
Fatal error: Uncaught Exception: Error: Field 'sort_order' doesn't have a default value

### ISSUE THREAD

**Issue by trueliarx** [opencart/opencart#7796]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
"Fatal error: Uncaught Exception: Error: Field 'sort_order' doesn't have a default value"

The affected table is oc_event.

This problem happens even if in other configurations things are working flawlessly.

It's enough to modify all the INSERT (installation and admin area SQL) for "oc_event" by adding a value for "sort_order" or by setting a default value (ex. 0) during the creation of the oc_event table.

I've tested by adding a default value (the faster method) and then it worked immediately.

In my opinion it should be fixed since not all the hosting providers are going to change the server configuration because of problems in the scripts.

**To Reproduce**
Do a clean installation with any "sql" compliant db supported by opencart.

**Expected behavior**
Opencart should install. 

**Server / Test environment (please complete the following information):**
 - Local dev on windows and linux
 - mariadb 10.x  and postgresql (problem occurs with default settings)
 - Operating system
 - PHP version 7
 - Apache
 - Browser Firefox

**Additional context**

**Comment by danielkerr** [comment]
this is not true! only if you have your muysql in strict mode!

**Comment by trueliarx** [comment]
It's quite offensive to read "this is not true".
Are you supposing that WE are LIARS or what?

If we CREATE a table with a column that doesn't have a default value, and then we INSERT records without giving a value it's more than obvious that we are acting in the WRONG way even if mysql is caring about that value. It's a FACT!

What I wrote is TRUE since there are some hosting providers with such configurations, that are not going to change, otherwise I wouldn't be here. It's a FACT!
You wrote "only if you have your mysql in strict mode" - ... and that's exactly why it should be fixed since the problem is right in front of you and very easy to fix.
The fix is not problematic and is not going to change the whole structure of opencart or something like that. 

Anyway it was a suggestion and I already fixed it by myself, as several other problems.
Next time I will avoid posting issues if I have to read such replies.
What the heck, we are even those that are contributing also to the moneys that are flocking in YOUR pockets (percentage on extensions sold, FREE code contributions, FREE marketing, etc). 

It's ok if you think that a fix is not necessary but, please, stop being a FLAMER.

**Comment by danielkerr** [comment]
i dont give a f*** if i offend you!

**Comment by danielkerr** [comment]
wasting my time. nobody uses strict mode. strick mode is not even set by default.

**Comment by danielkerr** [comment]
also this default is 1 in the master branch. case closed.
