### ISSUE TITLE
$data['results'] is defined in product.php but not used in product/review.twig

### ISSUE THREAD

**Issue by sabeti05** [opencart/opencart#7806]
Hi

I am reporting this for OpenCart 3.0.3.2

in this file:
`catalog\controller\product\product.php`

inside `review` method there is:
`$data['results'] = sprintf($this->language->get('text_pagination'), ($review_total) ? (($page - 1) * 5) + 1 : 0, ((($page - 1) * 5) > ($review_total - 5)) ? $review_total : ((($page - 1) * 5) + 5), $review_total, ceil($review_total / 5));`

but it is not used in this file:
`catalog\view\theme\default\template\product\review.twig`

it is:
`<div class="text-right">{{ pagination }}</div>`

while it should be something like this:
```
<div class="row">
  <div class="col-sm-6 text-left">{{ pagination }}</div>
  <div class="col-sm-6 text-right">{{ results }}</div>
</div>
```

**Comment by straightlight** [comment]
Confirmed. Issue also found in the master branch.

**Comment by straightlight** [comment]
Ok, added in the pre-release version. Thank you.

**Comment by straightlight** [comment]
Re-opening because it is still needed in the master branch.
