### ISSUE TITLE
summernote editor is not mobile friendly 

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#7819]
summernote editor is not mobile-friendly.
when you copy and paste a table, it won't automatically resize the table mobile-friendly.
better change to ckeditor.

**Comment by Grumvol** [comment]
in version 3.1 the editor is changed to https://ckeditor.com/

**Comment by chongshengdz** [comment]
> in version 3.1 the editor is changed to https://ckeditor.com/

thanks for the information.
cannot wait to upgrade.
do you know when version 3.1+ will be release?

**Comment by Grumvol** [comment]
no, but maybe Daniel will answer, it's interesting to me too

**Comment by danielkerr** [comment]
I'm in the process of working on the main site. Updating the payment system and finishing the cloud subscription system.

After that maybe 1 month to finish the next version of opencartr

**Comment by chongshengdz** [comment]
good to see you are back and let us know the estimate release time of the next version of opencart.
it has been over a year since the Alpha release of v3.1.

**Comment by mhcwebdesign** [comment]
@chongshengdz 
You can always switch over to the CKEditor for the current OpenCart 3.0.x now, see https://www.opencart.com/index.php?route=marketplace/extension&filter_category_id=8&filter_search=ckeditor
