### ISSUE TITLE
No image of voucher at cart page & checkout page

### ISSUE THREAD

**Issue by prosenjeet123** [opencart/opencart#7822]
**What version of OpenCart are you reporting this for?**
Version 3.0.3.2

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
When you try to place an order for voucher 
https://demo.opencart.com/index.php?route=account/voucher
after adding the voucher successfully the image is not appearing as defined in the admin section
![image](https://user-images.githubusercontent.com/12624294/72239106-e69ce600-3605-11ea-9bf0-58a4b5460411.png)
 

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/12624294/72239164-12b86700-3606-11ea-93c0-526ede93e087.png)
![image](https://user-images.githubusercontent.com/12624294/72239174-22d04680-3606-11ea-891e-75d010f4b4b6.png)

**Comment by danielkerr** [comment]
the image appears in the email

**Comment by prosenjeet123** [comment]
Hi Daniel,

thanks for the response, don't you think the image should be displayed at the cart and the checkout "image" column??

Thanks

**Comment by prosenjeet123** [comment]
> the image appears in the email
Hi Daniel,

thanks for the response, don't you think the image should be displayed at the cart and the checkout "image" column??

Thanks

**Comment by prosenjeet123** [comment]
Hi @danielkerr 

thanks for the response, don't you think the image should be displayed at the cart and the checkout "image" column??

Thanks

**Comment by straightlight** [comment]
Perhaps a 'yes' or 'no' option should be added in the form from the admin to avoid users asking either how to add / remove this option in the future from the cart or from the checkout page (checkbox list options as admin - > systems - > settings - > add / edit settings - > Mail tab has already).

**Comment by straightlight** [comment]
For now, I modified my forked namespace (opencart) with the following files:

- catalog/controller/checkout/cart.php
- catalog/view/theme/default/template/checkout/cart.twig
- catalog/controller/account/voucher.php
- catalog/controller/checkout/confirm.php
- catalog/view/theme/default/template/checkout/confirm.twig
- catalog/controller/common/cart.php
- catalog/view/theme/default/template/common/cart.twig (must ensure the custom theme fits if adding this part)

**Comment by danielkerr** [comment]
no and raising issues like this wants me want to ban you for wasting my time.
