### ISSUE TITLE
property_exists() doesn't work with the proxy system

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#7823]
**Need to find another method to check if the function exists.**
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/catalog/controller/api/payment.php#L202
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/catalog/controller/checkout/payment_method.php#L50
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/catalog/model/checkout/order.php#L290
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/catalog/model/checkout/order.php#L309
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/catalog/model/checkout/order.php#L381

**Comment by engwalid1971** [comment]
After testing,  the both property_exists() and method_exists() doesn't work because the OC using a proxy system.

**Comment by straightlight** [comment]
Yes, this has been reported before on Github. A Github user suggested the use of arrays when gathering dynamic PHP files which seem to have rectified the issue. Daniel has already been assigned on the subject.

**Comment by engwalid1971** [comment]
@straightlight
I suggest to use **is_callable()** like this:
```
if (is_callable($this->{'model_extension_payment_' . $result['code']}->recurringPayments) && $this->{'model_extension_payment_' . $result['code']}->recurringPayments()) {
```

**Comment by straightlight** [comment]
According to StackOverFlow.com: https://stackoverflow.com/a/39835864 , followed would be their recommendation:

``if isset($this->{'model_extension_payment_' . $result['code']}->recurringPayments) && is_callable($this->{'model_extension_payment_' . $result['code']}->recurringPayments) && $this->{'model_extension_payment_' . $result['code']}->recurringPayments()) {``

**Comment by straightlight** [comment]
However, I believe the original method has been used in order to track down extensions where they might be improperly coded from 3rd parties. The only downside by using that strategy is whenever a core file could really encounter a bug and nobody would know it by applying the modifications above.

**Comment by engwalid1971** [comment]
isset() not working here ...

**Comment by straightlight** [comment]
Another reason to use arrays as opposed to brackets since StackOverFlow's example is working as intended.

**Comment by cgcmart** [comment]
I have the rare opencart notice of undefined property on the front.

> Notice: Undefined property: Proxy::0 in .../system/engine/action.php on line 79

`return call_user_func_array(array($controller, $this->method), $args);`

There is no error log of the notice. I searched "Undefined property: Proxy::" online. Most of top results are related opencart proxy class. But there is no clue what "Proxy::0" indicates, where, or which is missing.

**Comment by danielkerr** [comment]
i altered the proxy class to use data[$meethod] when it should have been $this->$method

**Comment by danielkerr** [comment]
will fix

**Comment by danielkerr** [comment]
fixed alreay. i think this is a double reported issue

**Comment by emreaktas31** [comment]
Notice: Undefined property: Proxy::deleteApiSessionBySessonId in /home/sonikgamers/public_html/vqmod/vqcache/vq2-_home_sonikgamers_yenidata_modification_system_engine_action.php on line 79  it is not possible to reach a conclusion and find a solution
