### ISSUE TITLE
Undefined variable: num_pages

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7827]
**What version of OpenCart are you reporting this for?**
master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
PHP Warning:  Division by zero in
opencart/upload/catalog/controller/common/pagination.php line 29
`$total / $limit`
opencart/upload/catalog/controller/product/category.php line 332
`$product_total / $limit`
opencart/upload/catalog/controller/product/manufacturer.php line 310
`$product_total / $limit`

defined variable: num_pages in 
`$num_pages = ceil($total / $limit);` in opencart/upload/catalog/controller/common/pagination.php line 29
the defined variable is outside of the following used variable num_pages lines, in other words, defined variable but outside of its used enviroment, that causes php error:

Undefined variable: num_pages in /catalog/controller/common/pagination.php on line 51
Undefined variable: num_pages in catalog/controller/common/pagination.php on line 78
Undefined variable: num_pages in /catalog/controller/common/pagination.php on line 86

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by straightlight** [comment]
In catalog/controller/common/pagination.php file,

find:

``if (isset($setting['limit'])) {``

replace with:

``if (isset($setting['limit']) && $setting['limit'] > 0) {``

This should resolved the issue regarding the division by zero error message. See if it also solves the issue with the num_pages variable.
