### ISSUE TITLE
PHP Notice:  Undefined index: email

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7828]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Undefined index: email in /catalog/controller/account/login.php on line 127
Undefined index: email in /catalog/controller/account/login.php on line 134
Undefined index: email in /catalog/controller/account/login.php on line 141
Undefined index: password in /catalog/controller/account/login.php on line 141
**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by straightlight** [comment]
Confirmed bug. The validate() method does look a bit straightforward to load the $this->request->post['email'] .

In catalog/controller/account/login.php,

above:

``// Check how many login attempts have been made.``

add:

``if ((!isset($this->request->post['email'])) || (utf8_strlen($this->request->post['email']) > 96) || !filter_var($this->request->post['email'], FILTER_VALIDATE_EMAIL)) {
			$this->error['email'] = $this->language->get('error_email');
		}``

Then, in your catalog/language/<your_language_code>/account/login.php file, add at the bottom of the file:

``$_['error_email']          = 'E-Mail Address does not appear to be valid!';``

This should rectify the issue. Note: There might also be other controller files needing these on the catalog-end side.

**Comment by danielkerr** [comment]
this is because of people trying spam your site. im putting somthing in so it wont so this crap in the error log.
