### ISSUE TITLE
Error:  Call to a member function getProduct() on null

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7829]
**What version of OpenCart are you reporting this for?**
master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Error:  Call to a member function getProduct() on null in /catalog/controller/product/product.php on line 645
`$product_info = $this->model_catalog_product->getProduct($product_id);`
This error could be also on line 647:
`$recurring_info = $this->model_catalog_product->getProfile($product_id, $recurring_id);`
**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by straightlight** [comment]
Confirmed bug.

Above:

``$product_info = $this->model_catalog_product->getProduct($product_id);``

add:

``$this->load->model('catalog/product');``

This should rectify the issue.
