### ISSUE TITLE
Suggestion: customer lastName should also be added in contact us page

### ISSUE THREAD

**Issue by prabhatkumaroc082** [opencart/opencart#7834]
**What version of OpenCart are you reporting this for?**
3.1.0.0_b

**Describe the bug**
Open contact us page and log in by any customer
Then you will see only first name of logged in user as the input box value

**Comment by chongshengdz** [comment]
you can easily added yourself.
contact-us page should make it as simple as possible.
if too complicated, customer may close the window.

**Comment by straightlight** [comment]
Duplicated commit: https://github.com/opencart/opencart/pull/7835
