### ISSUE TITLE
Error message not show when upload wrong file

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7837]
What version of OpenCart are you reporting this for?
3.1.0.0_b
Describe the bug
Error message not show when upload wrong file from the Extension->Installer page 
![Screenshot_1](https://user-images.githubusercontent.com/44575158/73074258-31a8da00-3edf-11ea-8028-197557c7bbb8.png)

**Comment by WebkulOpencart** [comment]
Created a PR for the same:- [https://github.com/opencart/opencart/pull/7839](https://github.com/opencart/opencart/pull/7839)

**Comment by danielkerr** [comment]
this is already fixed
