### ISSUE TITLE
Journal 3 theme stack on loading

### ISSUE THREAD

**Issue by buluterol** [opencart/opencart#7841]
Im using Opencart 3.0.3.2
I installed Journal 3 template. When i click on Journal 's dashboard it stuck on Loading. I looked at the Chrome Dev Console and i see some errors for example:

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
main.js?v=3.0.43:1 Uncaught TypeError: Cannot read property 'system' of undefined
    at Object.<anonymous> (main.js?v=3.0.43:1)
    at Object.<anonymous> (main.js?v=3.0.43:1)
    at t (vendor.js?v=3.0.43:1)
    at Object.<anonymous> (main.js?v=3.0.43:1)
    at t (vendor.js?v=3.0.43:1)
    at Object.<anonymous> (main.js?v=3.0.43:1)
    at t (vendor.js?v=3.0.43:1)
    at Object.<anonymous> (main.js?v=3.0.43:1)
    at t (vendor.js?v=3.0.43:1)
    at Object.<anonymous> (main.js?v=3.0.43:1)

First http500 error is coming from the usertoken script when i click on the link i see a http500 error page. I tried to display errors with php codes and it shows me a blank white page.

https://yeniiletisim.com/admin/index.php?route=journal3/journal3/js&user_token=ieQ35zJz9DBNs2Bz0bsBOV7EugJKDOnY

This is the url giving the error.

I tried to disable theme and enable it again and it showed me the dashboard but there was some settings i set on database and i loaded a backup. Its gone again.

**Comment by tomeda** [comment]
I have exactly the same problem, how you fixed it?

**Comment by buluterol** [comment]
Hi tomeda, i was not able to understand that is a html/js based problem. I dont remember how did i solve this but i have some recommendations to you.

If your website is a pure new website just delete everything and reinstall.
If you want to save some changes then you can take a backup of your database without journal entries. _Type "journal" to the search bar inside of phpmyadmin and delete them. Click export._

If you cant do these solutions for some reason then you can go admin/template/header.twig and change position of main.js. You can put it into the top head of head section.
I 'm not sure that main.js file is from Journal theme. If it is belongs to Journal core files then you have to edit Journal 's header.twig file. Just find the main.js.

If you cant solve this, you can write here back.

**Comment by tomeda** [comment]
I did solve it, as it was my first time working with OC3 I was confused about the storage folder that it must be outside of the public directory, so the problem was a due misconfiguration of config file. Thanks for the feedback!

**Comment by Dicheto2302** [comment]
> I did solve it, as it was my first time working with OC3 I was confused about the storage folder that it must be outside of the public directory, so the problem was a due misconfiguration of config file. Thanks for the feedback!

How do you actually solved it because I have the same problem now
