### ISSUE TITLE
Why no use of Open Graph protocol in OpenCart?

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#7844]
As I checked no implementation of Open Graph protocol in default OpenCart. This is very useful when share the links of OpenCart store's products.

**Comment by straightlight** [comment]
The issues tab on this namespace is not about reporting missing features, it is meant to report technical issues from developers. If you'd like to address missing features, please address them on the Opencart forum at this location: https://forum.opencart.com/viewforum.php?f=200 .

This topic will now be closed.
