### ISSUE TITLE
Question: updating/expanding the country and zone data in the database

### ISSUE THREAD

**Issue by Dexus** [opencart/opencart#7845]
Hey, I want to update the country and state/zone data.

But where are you getting this data from?

I want to extend opencart with some multilingual data of the current data from the CLDR. But of course I would like to clarify the effort in advance and if the extension can be included in a future release or if it can only be implemented as an extension.

**Comment by ilcomp** [comment]
[ISO_3166-2](https://wikipedia.org/wiki/ISO_3166-2)

**Comment by Dexus** [comment]
@ilcomp That's what I thought at first, but the data from Wikipedia does not match the data from the database.

Example: https://github.com/opencart/opencart/blob/master/upload/install/opencart.sql#L3174 the German "Bundesländer" don't match and also others.

**Comment by ilcomp** [comment]
The data is probably old. At least for Russia.

**Comment by awaro** [comment]
It is worth adding multilanguage for geo zones.

**Comment by straightlight** [comment]
The only downside remains with the empty drop-downs from prior OC versions where only one language would be defined aside from additional languages where customers and users might be confused about the fact they might not be able to choose a value from neither list of the countries and zones, for instance. From there, commitment will be acquired from the users.

**Comment by awaro** [comment]
> The only downside remains with the empty drop-downs from prior OC versions where only one language ..
---------------
It is enough to add double variables to the database and transfer everything else to the language files. And then let users change the data using the built-in language editor.

**Comment by straightlight** [comment]
By using the language editor to define core languages, the data relationship on the database won't be the same as using a description table. By using a description table, customers may still encounter limited information being shown during account or during checkout activities with the drop-downs while the stores being live.

**Comment by awaro** [comment]
> 
Implement direct editing of language files
