### ISSUE TITLE
"config_file_max_size" is not working

### ISSUE THREAD

**Issue by dharmawebstudio** [opencart/opencart#7850]
**What version of OpenCart are you reporting this for?**

Working with OC 3.0.3.2

**Describe the bug**

The admin is able to upload a file with a size greater than the one defined in Setting > Store > Server Tab > "Max File Size"

A clear and concise description of what the bug is
What section does it affect?

Fronstore and Admin. 

**To Reproduce**
1. Go to Setting > Store > Server Tab > "Max File Size" and define "2000000". (2MB)
2. Go to categories or anyplace where you need to upload an image; like filemanager, and upload a file greater than 2MB. 
3. If PHP "upload_max_filesize" is greater; the image will upload successfully. There is no code avoiding this.

**Expected behavior**

The code should be there, but that variable ('config_file_max_size') is orphan. Not doing anything. 

**Suggestion**

Maybe a solution should be : 

admin/controller/common/filemanager.php in upload function; add this inside the "foreach ($files as $file) {" 

                    if ($file['size'] > $this->config->get('config_file_max_size')) {
                        $json['error'] = $this->language->get('error_text_for_this situation');
                    }

But there is another places where this should be considered, like the file inputs in options for products in the frontend, also to "Catalog > Downloads "; and other places...

===

Add a hidden field in the form with the name "MAX_FILE_SIZE"; should not be considered since this is not safe; and could be changed in the client side. I

===

Thanks to everybody for consider this report.

**Comment by straightlight** [comment]
If the case, this line:

```$json['error'] = $this->language->get('error_text_for_this situation');```

would need to be replaced with something like this:

```$json['error'] = $this->language->get('error_upload_size_' . $file['error']);```

**Comment by straightlight** [comment]
The ```error_upload_size_``` would, then, need to be set in the relative language file.

**Comment by danielkerr** [comment]
there needs to be a js fix as file sizes should not be found out half way through uploading.
