### ISSUE TITLE
PHP Warning: public function resize in /system/library/image.php

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7851]
**What version of OpenCart are you reporting this for?**
Master branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

> PHP Warning:  imagecreatetruecolor(): Invalid image dimensions in /system/library/image.php on line 169
PHP Warning:  imagealphablending() expects parameter 1 to be resource, boolean given in /system/library/image.php on line 172
PHP Warning:  imagesavealpha() expects parameter 1 to be resource, boolean given in /system/library/image.php on line 173
PHP Warning:  imagecolorallocatealpha() expects parameter 1 to be resource, boolean given in /system/library/image.php on line 175
PHP Warning:  imagecolortransparent() expects parameter 1 to be resource, boolean given in /system/library/image.php on line 177
PHP Warning:  imagefilledrectangle() expects parameter 1 to be resource, boolean given in /system/library/image.php on line 182
PHP Warning:  imagecopyresampled() expects parameter 1 to be resource, boolean given in /system/library/image.php on line 184

Line 169:
`$this->image = imagecreatetruecolor($width, $height);`
Line 172:
`imagealphablending($this->image, false);`
Line 173:
`imagesavealpha($this->image, true);`
Line 175:
`$background = imagecolorallocatealpha($this->image, 255, 255, 255, 127);`
Line 177:
`imagecolortransparent($this->image, $background);`
Line 182:
`imagefilledrectangle($this->image, 0, 0, $width, $height, $background);`
Line 184:
`imagecopyresampled($this->image, $image_old, $xpos, $ypos, 0, 0, $new_width, $new_height, $this->width, $this->height);`

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
there needs to be some sort of JS validsation before the file is uploaded.

**Comment by ADDCreative** [comment]
The problem is with the new size of the image being resized. Probably a theme settings issue. Check your theme has all the image sizes entered correctly.

Could add the the check to cut down on warnings.
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/system/library/image.php#L140
```php
if (!$this->width || !$this->height || !$width || !$height) {
```

Or maybe ```!((int)$width > 0)``` would be better.

**Comment by straightlight** [comment]
This JS validation might be useful: https://www.aspsnippets.com/Articles/Validate-Check-dimensions-Height-and-Width-of-Image-before-Upload-using-HTML5-JavaScript-and-jQuery.aspx .

**Comment by danielkerr** [comment]
this error normal hasppens when an file is being uploaded that is to large. the exit command is called. and you get the $_FILES showing as something has been uploaded even though nothing is there.

**Comment by danielkerr** [comment]
it needs to be js and the max file size needs to be added. same with images.

**Comment by ADDCreative** [comment]
@danielkerr The issue is about the new image size not uploaded images.

**Comment by ADDCreative** [comment]
> PHP Warning: imagecreatetruecolor(): Invalid image dimensions in /system/library/image.php on line 169

Relates to this line where $width and $height are the new size and probably for the theme image size settings.
https://github.com/opencart/opencart/blob/48eb19faef0c1246c9313ad95f3fe1769ce6c400/upload/system/library/image.php#L169

**Comment by prabhatkumaroc082** [comment]
no issue found in https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
The new image size is also working.

**Comment by danielkerr** [comment]
can not replicate.
