### ISSUE TITLE
Terrible payment bug of Journal 3 one page check (quick check)

### ISSUE THREAD

**Issue by DANDTON** [opencart/opencart#7853]
**What version of OpenCart are you reporting this for?**
OC 3.0.3.2
Journal 3 newest version 3.0.46, actually from 3.0.43 I found this bug until now,  this bug exists all the time.

**Describe the bug**
1. use paypal standard as payment method, in Journal dashboard set checkout method as quick check.
2. Open 3 pages, page 1 is in admin dashboard. Keep Page 2 and Page 3 in customer quick check page.
3. Pay page 2 successfully in sandbox paypal, but keep it at pay successful page, don't close it.
4. Go to page 1, press F5 button, you will see there is an order history you paid page 2, for example 100$.
5. Go to page 3, modify the item quatity as 2, you will see the total price will become 200$.
6. Go to page 1, press F5 button, you will see the order history become 200$. The page 1 order history has been modified by page 3 shopping cart value and items synchronized. If you tried to pay page 3 successfully, you will see the order history will be replaced by page 3, BUT! paypal didn't get the money from page 3!!

This is a terrible bug for people who sell both physical items and downloadable items, if page 2 is physical item and page 3 is downloadable items, people can get all downloadable items without pay money.

I also test stricktly under opencart default payment, there is no such problem.

Journal 3 team tried twice to fix this problem, but finally they gave up, they said all one page check have this problem. I didn't do test on other one page checkout extensions. Other poeple have one page checkout extension can repeat to check.

I had closed quick check function in Journal 3, but I like this function very much, wish gosu can solve this problem, thank you in advance!

Daniel

**Comment by osworx** [comment]
> Journal 3 team tried twice to fix this problem, but finally they gave up ..

Question: is OpenCart based on Journal OR Journal based on OpenCart?
Answer: if their Support is not able to code a working solution, it is not the "fault" of OpenCart!

**Comment by DANDTON** [comment]
It is not problem of opendart, it is the problem of Journal 3.
I had test default payment method of OC, it works well.

**Comment by chongshengdz** [comment]
no support here for third-party theme.

**Comment by straightlight** [comment]
Unsupported. Closing commit.

**Comment by danielb1234** [comment]
> > Journal 3 team tried twice to fix this problem, but finally they gave up ..
> 
> Question: is OpenCart based on Journal OR Journal based on OpenCart?
> Answer: if their Support is not able to code a working solution, it is not the "fault" of OpenCart!

you could say that, most of the people i know, they chose opencart because of journal theme, if wasn`t journal most of us will go for woocommerce ;) so be happy because journal theme take OC from mud and make it a great ecommerce platform ;)

**Comment by mhcwebdesign** [comment]
The vast majority of OpenCart sites do not use Journal3. This github section is not for stupid fan posts here promoting 3rd party software! For Journal support go to https://support.journal-theme.com/

**Comment by IP-CAM** [comment]
>> if wasn`t journal most of us will go for woocommerce ;) 
Well, I don't think, that anyone would care about, if at least all those Darknet-Journal Thiefs would no longer use Opencart. They don't contribute to OC's Wealth anyway, but at best fill the OC User Forum, in the hope, to get free Assistance, because they cannot contact Journal, to be of help. And it's sure not Opencart's Problem, if Journal Dev's are not even able, to make their bulky Theme Extension work with latest OC Versions.

**Comment by danielb1234** [comment]
> The vast majority of OpenCart sites do not use Journal3. This github section is not for stupid fan posts here promoting 3rd party software! For Journal support go to https://support.journal-theme.com/

LOL so github is for promoting your services and your theme/s wright ?! :))

**Comment by mhcwebdesign** [comment]
> so github is for promoting your services and your theme/s wright ?

The https://github.com/opencart/ is an open source project repository for OpenCart, not for web themes, the Journal framework, or other commercial 3rd party software. I know this may be a difficult concept for some to understand.

**Comment by cataistoc** [comment]
I think the Opencart  and Journal teams should collaborate, instead of blame each other. Even you like or not, the truth is that a lot of people choose Opencart due to Journal. I personally chose between Opencart and Prestashop and the win was Opencart due to Journal.
This theme offers a lot of functionality and good looking design at a very reasonable price. I agree that is not implemented in Opencart architectural style, but the end user is not interested about this. In my opinion, a collaboration between these two teams is a win-win situation.

**Comment by IP-CAM** [comment]
>> In my opinion, a collaboration between these two teams is a win-win situation.

It would for sure not be a win/win Situation, for Most, because a major part of existing
Extension- and Theme- Builders would no longer exist. So, Opencart would fully
depend on Journal, and Journal would dictate, what should be in OC and what not, 
and how it should be built, by OC-Default. In addition to the Fact, that OC would no 
longer come for free, so, 'stolen' Darknet-Versions would most likely dominate the Scene.

You Fellows just expect too much, you want it all, at best in one Piece, tested 
already, to enable you, to start up with an Ultimate FREE Solution Shop ... :) :) :)

**Comment by danielb1234** [comment]
> I think the Opencart and Journal teams should collaborate, instead of blame each other. Even you like or not, the truth is that a lot of people choose Opencart due to Journal. I personally chose between Opencart and Prestashop and the win was Opencart due to Journal.
> This theme offers a lot of functionality and good looking design at a very reasonable price. I agree that is not implemented in Opencart architectural style, but the end user is not interested about this. In my opinion, a collaboration between these two teams is a win-win situation.

I agree, but i think journal should make the theme more OC standard and keep the same features if is posible, i wish to be like wp/woocommerce where almost everthing is compatible and follow the same standards... PS. thanks Good OC is not like presta where nothing is work proper :)



> > > In my opinion, a collaboration between these two teams is a win-win situation.
> 
> It would for sure not be a win/win Situation, for Most, because a major part of existing
> Extension- and Theme- Builders would no longer exist. So, Opencart would fully
> depend on Journal, and Journal would dictate, what should be in OC and what not,
> and how it should be built, by OC-Default. In addition to the Fact, that OC would no
> longer come for free, so, 'stolen' Darknet-Versions would most likely dominate the Scene.
> 
> You Fellows just expect too much, you want it all, at best in one Piece, tested
> already, to enable you, to start up with an Ultimate FREE Solution Shop ... :) :) :)
> 
> A MUCHO easier Solution would be, if Journal would run their own OC User Forum,
> to serve the needs of their Customers. And they probably would, if they would
> not be aware about the Bulkloads of Thiefs, using their Theme Extension, without
> having paid for.

I think everyone should collaborate to follow the same standards why is so hard to make something working after years and years of OC existence and programming standards

those theme thiefs are just some kids who play ecommerce, nobody who wanna run a eStore  and don`t pay 200-300$ for theme and modules, nobody wanna hack themes with no updates

**Comment by mhcwebdesign** [comment]
> I think the Opencart and Journal teams should collaborate

That wouldn't work because Journal is of such a poor software engineering quality and user-unfriendly, it would drag OpenCart down. This has nothing to do with blaming each other. If woocommerce is so great why don't you use that one then?
