### ISSUE TITLE
A non well formed numeric value encountered in extension/payment/pp_express.php on line 477

### ISSUE THREAD

**Issue by exitsport** [opencart/opencart#7855]
Opencart:
3.0.2.0

If we openet orders and in top in order info:
A non well formed numeric value encountered in extension/payment/pp_express.php on line 477
Php line: $data['capture_remaining'] = number_format($paypal_info['total'] - $captured, 2);
In order is sample: 2000.- and paypal take from account 1999.99

**Comment by TiredFingers** [comment]
Send the sample paypal order with fields data types

**Comment by straightlight** [comment]
Removed from master branch. Closing commit.
