### ISSUE TITLE
Mind boggeling comment

### ISSUE THREAD

**Issue by digitalhuman** [opencart/opencart#7856]
The one who wrote this, causing serieus issues, absolutely needs to reconsile.

if ($config->get('session_autostart')) {
	/*
	We are adding the session cookie outside of the session class as I believe
	PHP messed up in a big way handling sessions. Why in the hell is it so hard to
	have more than one concurrent session using cookies!

	Is it not better to have multiple cookies when accessing parts of the system
	that requires different cookie sessions for security reasons.

	Also cookies can be accessed via the URL parameters. So why force only one cookie
	for all sessions!
	*/

The only one here that is causing havoc and issues is the author of the Session class.

**Comment by danielkerr** [comment]
you dont have a clue
