### ISSUE TITLE
Session handeling bugs v.3.0.3.1

### ISSUE THREAD

**Issue by digitalhuman** [opencart/opencart#7857]
**What version of OpenCart are you reporting this for?**
3.0.3.1

**Describe the bug**
Session handeling, all of it. 

**To Reproduce**
Put a high load of users on your shop and they will get their information leaked to the world.

**Expected behavior**
Strong session handeling. Strong session validation. High security (because its a webshop).

**Screenshots / Screen recordings**
You do that yourself.

**Server / Test environment (please complete the following information):**
nGinx
MariaDB
CentOS

**Additional context**

When launching our platform to a high volume of visitors, soon it became clear that information form others user was leaked because they landed in sessions from other users. I never have seen this before, not once. Not with other shops but also not in other frameworks. That made me do a code review of OpenCart.

There I discovered the horrific trueth. Developers who think "i can do better" always make me worry more. And looking through the 'Commits' of Session.php proofs my gut feeling again.

Sessions in webapplications are part of the foundation. If you do it wrong your platform, framework or website is broken. That is whats happening with OpenCart. Going from native PHP sessions to a reinvented session logic. Failing misserable, as of version 3. And many already reported it but they all got pushed aside because it was "their" fault.

Well here we go;

Session Fixation.........Session cookies can not be stolen Daniel because of mistakes the PHP developers made (With 500 years of experience). Session cookie get stolen because of doing it wrong. Like you did when writing cookies to the clients browser. In version < 3.* you did it well, even handeling "Secure cookies" and "HTML Only" cookies. When you remove those Session cookies get stolen. (as we see in OpenCart version 3.0.3.1)

Session Hijacking.........that happens when sessions are not handled correctly. Yes, that is as of now reality with OpenCart. You can use multiple browsers with 1 session. Even when the use logs off in one browser it can happely continue in the other browser. Combine that with the above issue and your have JACKPOT!

Session length / uniqueness; Going from 32 to only 26.........why Daniel? Why you think 26 is enough? Because you use random_bytes? .......... In my example we have millions of visitors...........do the math. 

openssl_random_pseudo_bytes vc random_bytes .......If you were to implement your own sessions logic (DONT! NEVER! DONT!) the at least make sure "openssl_random_pseudo_bytes" precede random_bytes and set "strong cryptograpy" to true.

Sessions are never validated. Even when you chose to store them in the database you did not think of maybe i should validate them. No, because in this case you do trust existing technology. (Cookie lifetime). But with 26 character long you HAVE TO. Sessions are not IP binded. Not in your case at least. Meaning, if one gets their hands on a cookie (Rand 1 and Rand 2) then we are fucked.

Session cookies are also not encrypted, not secured in any way (secure, httponly), and not unieque. What could posibly go wrong? As it endsup, it not the developers of PHP doing it wrong but the guys of OpenCart doing it wrong.

Final; my appologies for the 'tone' but you caused me/us a lot of shit and havoc because of your failed reinvention of session handeling. I feel I have every right to be pissed of.

**Comment by v5mvidal** [comment]
Hello.

To correct the problem, only a few adjustments are needed.

The size of the session_id must be 32.

In session libraries, you must create a "**exists**" function, to check if a new session_id already exists, if it exists, a new session_id must be generated in a verification loop until you are sure that the session_id does not exist.

The "**exists**" function must be invoked in the "**session**" library to centralize its functioning.

After these corrections, it will be necessary to modify the config files below:
system/config/**catalog.php**
system/config/**default.php**

Locate the line below:
**$ _ ['session_name'] = 'OCSESSION';**

And modify the session name. Users' cookies will thus be invalidated.

If you are using the database session, the ideal is to delete the session records from the "**session**" table. If you are using session by file, the ideal is to delete all "**sess**" files in the "storage/session/" directory.

I made these corrections in the store, and I had no problems with leaking sessions.

*It is important to create a cron job to delete expired sessions.

**Comment by digitalhuman** [comment]
It is not an exceptable fix att all. A cronjob ? seriously? How many unique visitors do you have per day?

If you build something, you build it right or you don't build it at all. As the author of a webshop (or any platform, library or framework) you have a responsibility. Especially nowadays in terms of security, GDPR etc.
Users can not always adjust their PHP or server settings. Some don't even know what how and when to make certain ajustments. We, as developers do know so we take of it.

**Comment by v5mvidal** [comment]
I will study more about how to improve the OpenCart session system and how to treat cookies in a more professional way, because OpenCart is the platform I chose to work with, and I understand that problems happen, and we have the option to just complain, or codify to help. I choose the second option. ;)

**Comment by digitalhuman** [comment]
@v5mvidal I agree with that. If you need help, info, anything. Drop me a note.

**Comment by danielkerr** [comment]
i dont believe your post and your wasting my time and looks like you are only trying to sell your services.

**Comment by digitalhuman** [comment]
Yeah, this mindset is exactly how you "solved" the PHP sessions. You have absolutely no clue what your doing. As one of your own commits said: "more tricky session stuff". You don't have to believe anything I said or wrote. People now know for a fact that #OpenCart is NOT #secure. As I am writing a nice blog post about it too explaining in detail why this is.

**Comment by danielkerr** [comment]
you dont kniow what you talking about. im the one with the no.1 ecommerce open source script. if you had experiance you would know that i have account for multiple server configurations.

**Comment by danielkerr** [comment]
also im not here to get into a pissing contest with you. you dont like the way i do things then use a different cart.
