### ISSUE TITLE
Klarna 3.0.3.2 Won't enable

### ISSUE THREAD

**Issue by tudorsad** [opencart/opencart#7858]
Hi, I am using OpenCart 3.0.3.2
Installed it on my hosting, but Klarna Checkout won't enable.
I have seen many advices linked to the previous version and tried some changes, but nothing worked.

When I try to enable it, it gives no errors at all, it says "You have modified Klarna Checkout", but keeps being disabled.

I have tried:
https://forum.opencart.com/viewtopic.php?f=199&t=214105

I do have all server settings requested/recommended and tried more PHP versions as well, but same result.
I mention I have no access to ssh commands or composer.

What can I do?

Thanks in advance

**Comment by straightlight** [comment]
As explained on the forum, Klarna has been removed from the master branch already. Closing commit.
