### ISSUE TITLE
stock_status model not correct

### ISSUE THREAD

**Issue by yvonn** [opencart/opencart#7863]
- Master 3.1.0.0_b

**Describe the bug**
- Cannot edit stock_status in admin localisation

**To Reproduce**
1. Go to 'admin/model/localisation/stock_status.php'
2. Click on 'edit'
3. See error

**Fix**
on line 83 replace this
public function getDescriptions($stock_status_id) {
into this
public function getStockStatusDescriptions($stock_status_id) {

**Comment by straightlight** [comment]
The convention names have been renamed on the master branch. Nowadays, it should be set back to getDescriptions() according to this model: https://github.com/opencart/opencart/blob/master/upload/admin/model/localisation/stock_status.php
