### ISSUE TITLE
Undefined property: Proxy::0 in admin/controller/localisation/stock_status.php on line 76

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7864]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Undefined property: Proxy::0 in .../admin/controller/localisation/stock_status.php on line 76
`$this->getForm();`
**To Reproduce**
1. Go to 'admin->system->localisation->stock statuses'
2. Click on 'Edit'

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by yvonn** [comment]
check this for fix: https://github.com/opencart/opencart/issues/7863

**Comment by cgcmart** [comment]
@yvonn Thank you for your suggestion that fixed the error.

I wonder why opencart error log did not log the error or let opencart error log log it.

I have this kind of error seen at front, no error log in opencart error log:

>  Undefined property: Proxy::0 in /home/xxx/public_html/system/engine/action.php on line 79

I am frustrated with this error. There is no clue or indicated where need to fix

**Comment by yvonn** [comment]
Where and when did you see this?

**Comment by cgcmart** [comment]
@yvonn It's existing over 1 month at home page https://cgcmart.com
I searched anywhere internet, top proxy class issues are opencart, but did not get any clue.
Therefore I followed the issue [#7823](https://github.com/opencart/opencart/issues/7823) where posted my issue.

**Comment by engwalid1971** [comment]
@cgcmart
To fix this issue you need to edit **admin/controller/localisation/stock_status.php**

Replace:
https://github.com/opencart/opencart/blob/0f62a3d1933104da8b6865788317d1b8ec02784f/upload/admin/controller/localisation/stock_status.php#L301
With:
```
$data['stock_status'] = $this->model_localisation_stock_status->getDescriptions($this->request->get['stock_status_id']);
```

**Comment by danielkerr** [comment]
fixed
