### ISSUE TITLE
Undefined variable: key in .../system/engine/proxy.php on line 48

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7866]
**What version of OpenCart are you reporting this for?**
master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
a lot of logs daily from opencart error log:
PHP Notice:  Undefined variable: key in .../system/engine/proxy.php on line 48

`exit('<b>Notice</b>:  Undefined property: Proxy::' . $key . ' in <b>' . $trace[1]['file'] . '</b> on line <b>' . $trace[1]['line'] . '</b>');`

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
closing because you have provided next to no information on issue.
