### ISSUE TITLE
Cart Update. Quantity

### ISSUE THREAD

**Issue by vkamelin** [opencart/opencart#7868]
common.js for cart update sends "quantity" as integer. But controller/checkout/cart.php receive quantity as an array. WHAT???

**Comment by opencartstore** [comment]
Hi,

In fact, the edit method is incorrect.

This:
`if (!empty($this->request->post['quantity'])) {
			foreach ($this->request->post['quantity'] as $key => $value) {
				$this->cart->update($key, $value);
			}`

Needs to be modified to:
`if (false === empty($this->request->post['quantity']) && false === empty($this->request->post['key'])) {
			$this->cart->update((int)$this->request->post['key'], (int)$this->request->post['quantity']);`

I will send a PR as soon as possible, but maybe the OC team will correct it before.

**Comment by v5mvidal** [comment]
There is no error, as two parameters are sent.

**Check:**
catalog/view/javascript/**common.js**
...
`'update': function(key, quantity) {`

**Comment by danielkerr** [comment]
checkout/cart/add 

recieves integer.

**Comment by opencartstore** [comment]
> There is no error, as two parameters are sent.
> 
> **Check:**
> catalog/view/javascript/**common.js**
> ...
> `'update': function(key, quantity) {`

Hi,

Yes, the object is called correctly in the frontend, but when sending the post to the backend that the error occurs, see:

`data: 'key=' + key + '&quantity=' + (typeof(quantity) != 'undefined' ? quantity : 1),`

The code above does not pass an array (and shouldn't), but two integer (product_id and quantity). In the backend, as 
@vkamelin mentioned, an array is expected.

@danielkerr this function is used to update the cart with ajax, this needs to be corrected, I will send a PR.
