### ISSUE TITLE
Undefined variable: key in /system/engine/proxy.php

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7869]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
A lot of error logs daily from opencart errors list:
Undefined variable: key in /home/xxx/public_html/system/engine/proxy.php on line 42

`exit('<b>Notice</b>:  Undefined property: Proxy::' . $key . ' in <b>' . $trace[0]['file'] . '</b> on line <b>' . $trace[0]['line'] . '</b>');`
**To Reproduce**
1. Go to '/admin/system'
2. Click on 'Maintenance'
3. Scroll down to 'Error Logs'

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version PHP 7.2 (ea-php72)
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by straightlight** [comment]
May also depend on the PHP version. What isn't mentioned on your post in the PHP version and to know if you have extensions installed.

**Comment by straightlight** [comment]
No response since the past 5 days regarding an incomplete post. Closing commit.
