### ISSUE TITLE
More code standard update needed

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7870]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

(1) opencart/upload/admin/model/customer/customer.php
replace line 390:
`public function getTotalCustomerRewardsByOrderId($order_id) {`

with:
`public function getTotalRewardsByOrderId($order_id) {`

(2)  opencart/upload/admin/controller/sale/order.php 
replace line 983:
`$data['reward_total'] = $this->model_customer_customer->getTotalCustomerRewardsByOrderId($this->request->get['order_id']);`

with:
`$data['reward_total'] = $this->model_customer_customer->getTotalRewardsByOrderId($this->request->get['order_id']);`

(3) opencart/upload/admin/controller/user/user.php 
replace line 329:
`$user_info = $this->model_user_user->getUser($this->request->get['user_id']);`

with:
`$user_info = $this->model_user_user->getUser($user_id);`

replace line 454:
`$user_info = $this->model_user_user->getUserByEmail($this->request->post['email']);`

with:
`$user_info = $this->model_user_user->getUserByEmail($email);`
**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
I fixed the rest but this does not make sense:

(3) opencart/upload/admin/controller/user/user.php
replace line 329:
$user_info = $this->model_user_user->getUser($this->request->get['user_id']);

with:
$user_info = $this->model_user_user->getUser($user_id);

replace line 454:
$user_info = $this->model_user_user->getUserByEmail($this->request->post['email']);

with:
$user_info = $this->model_user_user->getUserByEmail($email);
