### ISSUE TITLE
Update bootstrap Library (and other) to latest stable releases?

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#7871]
It is soon 1 year ago, while the latest official Releace of OpenCart (3.0.3.2) is published.
As we could hear, OpenCart 3.1.x should be realiesed this spring or summer (we hope ..).

But looking at the used libraries, still older  versions are used.
For example bootstrap use 4.3.1 https://github.com/opencart/opencart/blob/8759ee8f7bf70ad11b42f1a67b8c2865b7690385/upload/catalog/view/javascript/bootstrap/js/bootstrap.js#L2 while 4.4.1 ist the latest release.

Now is bootstrap preparing the next release 5.x

I know that there are dependicies, but how the plans / roadmap to update all the libraries to their latest stable releases?
I think that 3.1.x should be published with them and not the old ones.

**Comment by rsuchovsky** [comment]
I think we'll all be happy to release oc 3.1.x.x, so we can run under bootstrap 4 rather than 3 (in the admin). Because it's annoying.

But personally, I think until they release a new version of opencart.
Bootstrap 5 will be out :)

**Comment by straightlight** [comment]
Correct. Bootstrap versions are increasing rapidly these days. Opencart may be a bit behind with Bootstrap still as it may be pretty hard to catch up with the updates with the stand-alone version.

**Comment by osworx** [comment]
> 
> But personally, I think when they release a new version of opencart.
> Bootstrap 5 will be out :)

Or 6 .. ?

**Comment by dariygray** [comment]
> > But personally, I think when they release a new version of opencart.
> > Bootstrap 5 will be out :)
> 
> Or 6 .. ?

Or 7 .. ?

**Comment by matroskin92** [comment]
Update bootstrap to 4.5,
this update very important for developers

**Comment by cgcmart** [comment]
What bootstrap library should be depends dependency Twig update.

**Comment by danielkerr** [comment]
its currently the latest.
