### ISSUE TITLE
Problems with settings cookies in case of redirect to subdomain.

### ISSUE THREAD

**Issue by zemguru** [opencart/opencart#7872]
Cookies for domains precedes sub-domain cookies. 
In that case, imagine scenario:
- create domain `example.com`
- setup Opencart.
- change Language, Currency as a customer and continue to use site. Everything works well.

Then - You decide to add "www" as main domain to the site.
So, now - all other cookies in the future will be set to `www.example.com` domain.

In this case, - You will not be able to change language, currency, until the old cookie expires.
This is a problem, if in any case, you are using domain `example.com`  as main domain, but do not set up correct redirection to one and only correct domain name. In that case, Cookies fro "domain" will always be with priority, and `startup.php` will get default language from incorrect cookie. 

```bash
language | fr-fr |	.example.com		|	2020-04-09T14:04:54.672Z
language | en-gb |	.www.example.com	|	2020-04-09T14:25:14.619Z
```

Iw user continues to browse www.example.com, then he will not be able to change language to 'fr-fr', because `startup.php`  will always get language from sent cookie and `example.com` will be with higher priority.

 Could it be better to set cookie without domain at all (then it will match if and only specific hostname I suppose). 

It has been chasing me for years. It seems, this is the reason, why it happens sometime in specific situations. Something similar is explained here:

https://www.php.net/manual/en/function.setcookie.php#91140

**Comment by ADDCreative** [comment]
This is something I've been meaning to raise as an issue as well. Setting the domain in setcookie() causes the cookie to apply to that domain and all its sub-domains. Which can have undesirable effects.

Would possibly be better to use the following for the lines below. Then the cookie is only valid for the current domain and no sub-domains.
```php
setcookie('language', $code, time() + 60 * 60 * 24 * 30, '/');
```

https://github.com/opencart/opencart/blob/6f19d84412e11746a6c77ae1b1a42fd36f0faa25/upload/catalog/controller/common/language.php#L61

https://github.com/opencart/opencart/blob/09dee7ba90482652e155dc18297d806313720e34/upload/catalog/controller/startup/startup.php#L165

**Comment by danielkerr** [comment]
cookies are now set using 'domain'   => $this->request->server['HTTP_HOST'], so it should not interferer with subdomains.  unless you are not using www. maybe.

**Comment by danielkerr** [comment]
if you put .mydomain.com then yes will work on sub domains! but opencart does not do that! it uses mydomain.com. so not sure what u are going on about.  wasting my time having to look through this.

**Comment by danielkerr** [comment]
i think u mean sub folder!

**Comment by ADDCreative** [comment]
@danielkerr It's how web browsers handle the set cookie header. If you set the domain then it will always include subdomains regardless of the leading dot. To limit to just the domain then you should not set the Domain attribute at all.

From https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
> Domain=<domain-value> Optional
> Host to which the cookie will be sent.
> If omitted, defaults to the host of the current document URL, not including subdomains.
> Contrary to earlier specifications, leading dots in domain names (.example.com) are ignored.
> Multiple host/domain values are not allowed, but **if a domain is specified, then subdomains are always included**.
