### ISSUE TITLE
SEO url with sub category

### ISSUE THREAD

**Issue by virgiltu** [opencart/opencart#7873]
**What version of OpenCart are you reporting this for?**
All Versions 

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
URL can be set with slug     domain.com/aboutus
But it cant be set with slug   domain.com/location/sandiego

In File: opencart/upload/catalog/controller/startup/seo_url.php

`$parts = explode('/', $this->request->get['_route_']);`

I was able to get something going by removed the foreach with 	$part = end($parts); 
this in turn will take the past lart of the array and just search it so now you can do any url as long as the last part matches it will work.

**Comment by danielkerr** [comment]
you need to make sure all parent categories have seo key words added.

**Comment by danielkerr** [comment]
its a forced requirment in the master branch

**Comment by danielkerr** [comment]
im closing this. it works for me as it should.
