### ISSUE TITLE
Adding out of stock product with option to cart

### ISSUE THREAD

**Issue by sn0wlink** [opencart/opencart#7874]
**What version of OpenCart are you reporting this for?**
< OpenCart 3

**Describe the bug**
When adding a product with an option to cart with 1 in stock, you can then add the same item again with a different option and purchase. The result is a -1 stock quantity whereas the error should say Product Out Of Stock.

**To Reproduce**

    (With 1 Gold Pendant in stock)

1) add 1 Gold Pendant and optional 16" chain to basket
2) add 1 Gold Pendant and optional 22" chain to basket

**Expected behavior**
After adding the first pendant the user should see a **Item is out of stock** message, but doesn't even though there is only one item in stock. This causes the store to oversell items.

**Comment by straightlight** [comment]
Please create an incident request on the forum. Github is to report issues with the master branch. Closing commit.
