### ISSUE TITLE
Version number displayed on admin footer is incorrect

### ISSUE THREAD

**Issue by pwclay** [opencart/opencart#7877]
3.1.0.0_b

The version number on the admin page footer displays as "Version 3.0.3.2", claiming that the installed version is a stable release, not a beta

**To Reproduce**
Go to admin page.  Version number is shown on page footer.

**Expected behavior**
Show correct version, including that it is a beta release.

**Server / Test environment (please complete the following information):**
Local, clean install on LAMP.

**Additional context**

I know it is a minor error, but using beta software thinking it is a release version can cause major problems.

Thanks

**Comment by danielkerr** [comment]
3.1.0.0_b is the latest from the master branch
