### ISSUE TITLE
Problems with extentions

### ISSUE THREAD

**Issue by sirensofsouls** [opencart/opencart#7880]
hey so i have an updated  copy of open cart  however when i try to  install and enable extentions they do not alway stick. example   i trying to enable html content  it enabled i made 3  modules under html and saved it once saved i refresh the main module list and the module that was just saved  does not show up it also happens when i try to remove a module  it says it removed then when i refresh that module reappears

**Comment by straightlight** [comment]
Which OC version are you reporting this issue about?

**Comment by danielkerr** [comment]
please report in forums or use contact us for support. 

maybe a caching issue. trying clearing any cache files under the cache folder
