### ISSUE TITLE
why does a 2017 commit to Update unit test got missing?

### ISSUE THREAD

**Issue by scil** [opencart/opencart#7884]
This commit https://github.com/opencart/opencart/commits/9dfc301049b297a28805fa360501f45680a7eaa7 wat commited in 2017  to Update unit test using beyondit/opencart-test-suite.

In this 2017 commit, the updated [tests/phpunit/composer.json](https://github.com/opencart/opencart/blob/9dfc301049b297a28805fa360501f45680a7eaa7/tests/phpunit/composer.json) is like this
```
{
    "require-dev": {
        "beyondit/opencart-test-suite": "^2.3"
    }
}
```

But the current used version of [tests/phpunit/composer.json](https://github.com/opencart/opencart/blob/master/tests/phpunit/composer.json) is old with 2015 as the lasted updating time and the dead `openbaypro/opencart-test-suite` as a requirement.
```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/openbaypro/opencart-test-suite.git"
        }
    ],
    "require": {
        "openbaypro/opencart-test-suite": "dev-master"
    }
}
```

Why does that newest and valid commit got missing?

**Comment by danielkerr** [comment]
ju8st removed the unit tests. Are they really required still?
