### ISSUE TITLE
New column at "Latest Order" section 

### ISSUE THREAD

**Issue by midotaha** [opencart/opencart#7885]
### Hi My Dear
**Greetings!!**
***i'm using OpenCart Version 3.0.3.2 .**
 **i'm trying to add a new column at "Latest Orders" on admin dashboard , for example "column Phone"**
**this column should shown customer phone , to contact with him very fast**
![Screenshot (580)](https://user-images.githubusercontent.com/19406537/78548550-a6669180-7809-11ea-8e2d-e7bdb2b89934.png)
 
**how did  i added  that column ?! what is the code i used it ?!And what is the path ?!!
path :- .............\admin\language\en-gb\extension\dashboard\recent.php
Code:- $_['column_telephone']  = 'phone';**
![Screenshot (530)](https://user-images.githubusercontent.com/19406537/78555588-06fbcb80-7816-11ea-9321-855a0c363e73.png)

**path:-......\admin\controller\extension\dashboard\recent.php
Code:- 'telephone'  => $result['customer_telephone'],**
![Screenshot (590)](https://user-images.githubusercontent.com/19406537/78555907-aae57700-7816-11ea-961c-67421bb6a1f1.png)

**path:- ..........\admin\view\template\extension\dashboard\recent_info.twig
code:- <td>{{ column_telephone }}</td>**
![Screenshot (52)](https://user-images.githubusercontent.com/19406537/78554610-2560c780-7814-11ea-93bc-ae34d5c74655.png)

**that is all i already added it , to get another column at "Latest Orders" but not working , or there is something i didn't  do it , can you help me ?** 
**Many Thanks for you**

**Comment by osworx** [comment]
Nice post, wrong forum.
Better post a request here: https://forum.opencart.com/viewforum.php?f=88
