### ISSUE TITLE
Cloudflare 500 error when changing changing Extension Type

### ISSUE THREAD

**Issue by gRoberts84** [opencart/opencart#7886]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
When going to Extensions > Extensions and selecting anything from the Extension Type dropdown, a Cloudflare notice appears and then refreshes the page after 5 seconds. If you are redirected back to the extensions page with the dropdown pre-selected, it will refresh every 5 seconds.

**Screenshots / Screen recordings**
<img width="1220" alt="Screenshot 2020-04-06 at 14 23 03" src="https://user-images.githubusercontent.com/348184/78563174-72dc3500-7812-11ea-8e8c-3bcb8f58cf2d.png">

**Server / Test environment (please complete the following information):**
 - Local development
 - OSX
 - PHP 7.3
 - Nginx

**Additional context**
I cannot replicate this on the demo admin site, however it's behavior proves that if something were to go wrong on the OpenCart.com website, it would potentially break the extensions page.

**Comment by osworx** [comment]
Wrong forum to ask fot such.
Better read this here: https://forum.opencart.com/viewtopic.php?f=202&t=216941

**Comment by gRoberts84** [comment]
🙄 I'd say that this is a bug if OpenCart is trying to communicate with a remote server that isn't critical for the operation of the site and when failing breaks the functionality.

Heh, I've just disabled the promotion controller.
