### ISSUE TITLE
Auto complete for "Options & Attributes" tab in products not showing its elements when selected (php7+)

### ISSUE THREAD

**Issue by AbdulazizFayez** [opencart/opencart#7888]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug?**

**A clear and concise description of what the bug is:**
In "_Option_" & "_Attributes_" tabs in product, auto complete are not adding.

**What section does it affect?**

So far i tested on **products** not sure yet if there are other places is affected.

**To Reproduce**
1. Make sure that you are on php 7+ (meaning 7.0, 7.1, 7.2, 7.3) - as of now.
2. Go to admin->catalog->product
3. Add or edit (for existing product)
4. Go to options->add new (radio, select, etc) ->click on it.
5. nothing happens. 

I checked the Inspect element console + network .. but there was no error as far as i am aware.

**Expected behavior**

**Screenshots / Screen recordings**
As you can see, once i click on it, nothing happens.
![image](https://user-images.githubusercontent.com/16557490/78963543-64e82600-7b2a-11ea-9d94-177d2db40a90.png)

**Server / Test environment (please complete the following information):**

 **- Local development? Deployed to a web server?**

Local & Development.. same issue

 **- Operating system**

Local Env: (windows 10 - wamp) - Development Env: (linux - nginx fpm)

 **- PHP version:**

Local & development (php 7)

 **- Apache version**

Local (2.439) - development (nginx fpm 1.5.7)

 **- Browser(s) tested with [e.g. chrome, safari - if applicable]**

Firefox Developer, Opera Developer, Chrome. (Except Edge - its working fine!)

 **- Version [e.g. 22]**

**FF:** 76.0b2 (64-bit), **Opera:** 69.0.3, **Chrome:** 81.0.4 (64-bit)

**Additional context**

Yes, if i switch my Wamp to Php 5.6, the "**_Options_**" & "**_Attributes_**" tab will work fine. (but site is rather slow a bit, its faster on php7+ though)

**Comment by danielkerr** [comment]
we are working on the master branch.

**Comment by danielkerr** [comment]
also it works for me on php7+

**Comment by AbdulazizFayez** [comment]
> also it works for me on php7+

Interesting.. my pc only Edge has no problem, other browsers it they dont respond. So you were not able to re-produce.. any idea what could be causing the issue? 

Thanks.
