### ISSUE TITLE
Email Vertication

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#7889]
Can you create Email Vertification to Register pages of Opencart?

**Comment by danielkerr** [comment]
sure

**Comment by straightlight** [comment]
Similar request here about email validations: https://github.com/opencart/opencart/issues/7828#issuecomment-576760005 while I do understand the use of filter_var with filter_validate_email may not cover IDN emails as addressed by Add Creative a few years back: https://github.com/opencart/opencart/issues/3620#issuecomment-164832274 .

**Comment by pekka2** [comment]
This is one example: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=36752

**Comment by straightlight** [comment]
> This is one example: << Link removed >>

Please stop referring third-party extensions from Github. If you'd like to refer / publish extensions, please do so from the Opencart forum.

**Comment by danielkerr** [comment]
all the pages have email verification where email is required!
