### ISSUE TITLE
Function getProductOptionValue name change on order.php -> getOptionValue

### ISSUE THREAD

**Issue by exelaguilar** [opencart/opencart#7890]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

The class name for getProductOptionValue has changed to getOptionValue so it throws a Proxy Error / Class not found when clicking on the packing slip button.

Packing Slip Invoices

**To Reproduce**
1. Go to 'Sales > Orders'
2. Click on 'View'
3. Click on 'Print Packing Slip button'

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

admin/controller/sale/order.php

Find in line 1792

$product_option_value_info = $this->model_catalog_product->getProductOptionValue($product['product_id'], $option['product_option_value_id']);

Replace with:

$product_option_value_info = $this->model_catalog_product->getOptionValue($product['product_id'], $option['product_option_value_id']);

**Comment by straightlight** [comment]
Confirmed. The model convention name of getOptionValue has been renamed but the old convention name is still being called in the master branch from the addressed controller on the above.
