### ISSUE TITLE
Bootstrap datetimepicker disabledDates (and other) not working

### ISSUE THREAD

**Issue by devincentiis** [opencart/opencart#7892]
OpenCart 3.0.3.2 (snapshot this week)

Hi, on the catalog product / product.twig page I tried adding disabledDates to bootstrap-datepicker.js it doesn't work in any way. Even if I use the same syntax indicated on the project website, I can't disable the dates. Anyone know how to do it? Are there any conflicts with other js? I attach the screenshot of the console.
![screen](https://user-images.githubusercontent.com/13419943/79630782-97120d00-8154-11ea-9b32-ab9a284d2700.png)

https://eonasdan.github.io/bootstrap-datetimepicker/#enableddisabled-dates

**Comment by WebkulOpencart** [comment]
Hello @devincentiis 
You have defined the date format YYYY-MM-DD and the disabled date format is YYYY/MM/DD which is wrong format.
So, please either change your date format or change the disabled date format.
When both will be in the same format only then it will work.
So, the correct solution is
`$('.date').datetimepicker({
    format: 'YYYY-MM-DD',
    'locale : '{{ datepicker }},
    'allowInputToggle' : true,
    datesDisabled: ['2020-04-25'],
});`

**Comment by devincentiis** [comment]
> 
> 
> Hello @devincentiis
> You have defined the date format YYYY-MM-DD and the disabled date format is YYYY/MM/DD which is wrong format.
> So, please either change your date format or change the disabled date format.
> When both will be in the same format only then it will work.
> So, the correct solution is
> `$('.date').datetimepicker({ format: 'YYYY-MM-DD', 'locale : '{{ datepicker }}', 'allowInputToggle' : true, datesDisabled: ['2020-04-25'], });`

Thanks for reply.
I'm sorry but it doesn't work, I've tried in many ways and I've always refreshed the cache

**Comment by WebkulOpencart** [comment]
@devincentiis Please check the below solution, it is working on my end.
`    $('.datetime').datetimepicker({
      language: '{{ datepicker }}',
      pickDate: true,
      disabledDates: ["2021-01-10"],
    });`
