### ISSUE TITLE
Installer permission issue

### ISSUE THREAD

**Issue by kabodipeti** [opencart/opencart#7894]
I'm installing OC 3.0.3.2 on a Google Virtual machine on Centos 7

After copying files in httpd web folder ( /var/www/html/ ),, setting all files and folder to apache user and group, giving them all permissions, I'm trying to navigate in browser and got this error on http://mypage.com/install/index.php:

> Warning: fopen(/var/www/html/system/storage/session//sess_00e837c9271a2ce8c0056e3e58): failed to open stream: Permission denied in /var/www/html/system/library/session/file.php on line 29Warning: flock() expects parameter 1 to be resource, boolean given in /var/www/html/system/library/session/file.php on line 31Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/system/library/session/file.php on line 33Warning: fflush() expects parameter 1 to be resource, boolean given in /var/www/html/system/library/session/file.php on line 35Warning: flock() expects parameter 1 to be resource, boolean given in /var/www/html/system/library/session/file.php on line 37Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/html/system/library/session/file.php on line 39

The installation failes at this point.
The session file in storage/session was not generated, the directory has a blank html file.

etc/php.ini: I uncommented and modified to,:
 session.save_path = "/var/www/html/system/storage/session/"
But it didnt changed anything.
Tried to define DIR_SESSION in config file, but didnt help.

Apache is running well, other static websites I uploaded are working.

I already installed Opencart on my Windows desktop PC (PHP 7.3.1) , it worked with only a simple copy to Xampp/htdocs folder

My versions:

- Centos 7 (Google VM)
- PHP 7.2.30
- Apache 2.4.

Has anybody faced with the same issue? I couldnt find a solution for it.

Thank you in advance!

**Comment by straightlight** [comment]
Since you are addressing the issue about OC v3.0.3.2 whereas the issues tab is about the master branch, and since this issue is about your storage folder being inside of your public_html folder rather than outside as indicated on the FAQ topic: https://forum.opencart.com/viewtopic.php?f=134&t=215776#p717782 (first post), this commit will now be closed.
