### ISSUE TITLE
Error: Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7896]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Error:  Cannot use object of type stdClass as array in .../system/library/cart/cart.php on line 52
`foreach ((array)json_decode($product_query->row['variant'], true) as $key => $value) {`
**To Reproduce**

**Expected behavior**

A preferred way:
`foreach (json_decode($product_query->row['variant'], true) as $key => $value) {`

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by straightlight** [comment]
This issue might reflect on the PHP version being installed.

**Comment by cgcmart** [comment]
@straightlight 
PHP version: 7.3.6

**Comment by straightlight** [comment]
In that PHP version, there was a fix added on the JSON serializer: http://bugs.php.net/77843 but I'm not sure if that also reflects on the deserializer since the PHP v7.3 releases contains the THROW_ON_ERROR case with JSON these days or if it's simply server-specifics where this workaround solution above could be used.

**Comment by straightlight** [comment]
It might be due to server-specifics or PHP version since, still on this day, there are no major incident reported about it.
