### ISSUE TITLE
Information Layout

### ISSUE THREAD

**Issue by vkamelin** [opencart/opencart#7897]
OpenCart 3.0.3.2

Information layout doesn't work. If I apply any layout to information page, default layout will be displayed instead.

/catalog/controller/information.php

`$this->response->setOutput($this->load->view('information/information', $data));`

What is this? What about layout?

Why I can apply custom layout to Information page and it doesn't used in controller? Layout in Information pages, what is for?

**Comment by straightlight** [comment]
Not relative to issues. Please create a pull requests for code adjustment about features.
