### ISSUE TITLE
Documentation Code Standards

### ISSUE THREAD

**Issue by reetp** [opencart/opencart#7899]
https://github.com/opencart/opencart/wiki/Coding-standards

"There is a PHP_CodeSniffer standard here: https://github.com/opencart/opencart/tree/master/tests/phpcs/OpenCart"

Actually, no there isn't. There's a nice 404 instead.

**Comment by nursanamar** [comment]
I found the file on another branch https://github.com/opencart/opencart/tree/3.0.2.1_rc/tests/phpcs/OpenCart

**Comment by danielkerr** [comment]
i can not maintain code sniffer on the master branch.  i didnt add it.
