### ISSUE TITLE
On update order status  a JavaScript popup appears : "error undefined" and order disappear from the list. 

### ISSUE THREAD

**Issue by DanyalCheema** [opencart/opencart#7901]
**What version of OpenCart are you reporting this for?**
Version 3.0.2.0

**Describe the bug**
On update order status  a JavaScript popup appears : "error undefined" and order disappear from the list. 

What section does it affect?
sales->order

**Comment by DanyalCheema** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/54432558/79908905-805e0580-8435-11ea-92da-82ae51dc3db8.png)
on creating new error undefined popup.
Please check the attached screenshot

**Comment by straightlight** [comment]
Not a bug.
