### ISSUE TITLE
Braintree SDK versions update OpenCart 3.0.2.0

### ISSUE THREAD

**Issue by Fenix121kam** [opencart/opencart#7902]
Hello, I have OpenCart version 3.0.2.0, I received this information as below from braintree payments.
How can I update?

"
Our records show that you are using a legacy SDK version that is not compatible with an upcoming update to our root SSL certificate provider for API traffic on May 1, 2020.

If you do not update to a compatible SDK by this date, you will no longer be able to process payments through your Braintree account until you make the necessary update.

What action is required?
To avoid interruption to your processing, please update your SDK version on every part of your integration that is making API Calls to Braintree to the appropriate minimum version before May 1:
Java 2.67.0
Python 3.24.0
Ruby 2.57.0
PHP 3.8.0
Note: Node and .NET Server SDKs should not be impacted by these upcoming changes.
Where can I find more information?
For information on how to update your SDK version, see our developer docs.

If you are using a third-party shopping cart for your integration, we recommend reaching out to your shopping cart provider to ensure that they are using up-to-date Braintree SDKs so your processing is not interrupted.

If you have any questions, contact us.

The Braintree Team
"

**Comment by danielkerr** [comment]
i need to contact braintree as they need to do the update.

**Comment by JBinc** [comment]
Hello, just wanted to follow up if there was an update on this?

**Comment by Fenix121kam** [comment]
Hello, has the problem been solved? Does version 3.0.3.3 already contain the correct libraries for Braintree?

**Comment by Khnaz35** [comment]
Hi any update on this?

**Comment by ADDCreative** [comment]
Was updated with https://github.com/opencart/opencart/pull/8062 and released in 3.0.3.5 onwards.

**Comment by Khnaz35** [comment]
I am using 3.0.3.5 and i am not able to receive the recurring payment through Braintree. I have setup the keys in Braintree extension but still on checkout "Warning: No Payment options are available. Please contact us for assistance!"

**Comment by ADDCreative** [comment]
Check your Braintree version by looking in storage/vendor/braintree/braintree_php/CHANGELOG.md.

Although that error suggests a different issue.

**Comment by Khnaz35** [comment]
## 3.40.0
* Deprecate `GRANTED_PAYMENT_INSTRUMENT_UPDATE` and add `GRANTOR_UPDATED_GRANTED_PAYMENT_METHOD` and `RECIPIENT_UPDATED_GRANTED_PAYMENT_METHOD`
* Add `accountType` field to `TransactionGateway`, `CreditCardGateway`, `PaymentMethodGateway`, and `CreditCardVerification`.
* Add Hiper and Hipercard test numbers.


Does Braintree not supported recurring payment?

**Comment by ADDCreative** [comment]
No, I don't believe it does supported recurring payments.

**Comment by Khnaz35** [comment]
if it does then why this issue ?

**Comment by ADDCreative** [comment]
Maybe my comment could of been clearer. No, it does NOT supported recurring payments.

**Comment by Khnaz35** [comment]
Thanks for letting me know
