### ISSUE TITLE
Twig cache folder for Xdebug

### ISSUE THREAD

**Issue by Ercogx** [opencart/opencart#7904]
In order for Xdebug to work with Twig, you must specify the path to the Twig cache folder. I tried 
C: \ OSPanel \ domains \ oc.test \ storage \ cache and 
C: \ OSPanel \ domains \ oc.test \ upload \ system \ storage \ cache 
but it doesn't work it doesn't want to catch breakpoints. What am I doing wrong?

**Comment by straightlight** [comment]
Specific issue reported.
