### ISSUE TITLE
Open cart error while checkout

### ISSUE THREAD

**Issue by sumesh-pradhan** [opencart/opencart#7905]
Open cart 3.0.2.0

**Describe the bug**
Exception is caught and throws out while doing checkout unable to load webservices Fcm

**Expected behavior**
User should able to check out with order details

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
OK
<br />
<b>Fatal error</b>:  Uncaught Exception: Error: Could not load model webservices/fcm! in /home/tradesa1/storage/modification/system/engine/loader.php:89
Stack trace:
#0 /home/tradesa1/storage/modification/catalog/model/checkout/order.php(12): Loader-&gt;model('webservices/fcm')
#1 /home/tradesa1/storage/modification/catalog/model/checkout/order.php(538): ModelCheckoutOrder-&gt;on_order_add(241)
#2 /home/tradesa1/storage/modification/system/engine/loader.php(248): ModelCheckoutOrder-&gt;addOrderHistory(241, '1')
#3 /home/tradesa1/public_html/system/engine/proxy.php(47): Loader-&gt;{closure}(Array, Array)
#4 /home/tradesa1/public_html/catalog/controller/extension/payment/cod.php(13): Proxy-&gt;__call('addOrderHistory', Array)
#5 /home/tradesa1/storage/modification/system/engine/action.php(79): ControllerExtensionPaymentCod-&gt;confirm()
#6 /home/tradesa1/public_html/catalog/controller/startup/router.php(25): Action-&gt;execute(Object(Registry))
#7 /home/tradesa1/storage/modification/system/engine/action.php(79): ControllerStartupRouter-&gt;index()
#8 /hom in <b>/home/tradesa1/storage/modification/system/engine/loader.php</b> on line <b>89</b><br />

**Comment by ADDCreative** [comment]
Caused by an extension. Ask the author or the extension or in the forums.

**Comment by straightlight** [comment]
Extension issue.
