### ISSUE TITLE
$rating variable created but not used.

### ISSUE THREAD

**Issue by sabeti05** [opencart/opencart#7906]
Hi

**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
In these files:

> catalog/controller/product/category.php
> catalog/controller/product/search.php
> catalog/controller/product/special.php
> catalog/controller/product/manufacturer.php

`$rating` is created but is not used. example:

```
if ($this->config->get('config_review_status')) {
	$rating = (int)$result['rating'];
} else {
	$rating = false;
}

$data['products'][] = array(
...
	'rating'      => $result['rating'],
...
);
```

It should be:
```
if ($this->config->get('config_review_status')) {
	$rating = (int)$result['rating'];
} else {
	$rating = false;
}

$data['products'][] = array(
...
	'rating'      => $rating,
...
);
```

**What section does it affect?**
It always shows the rating stars in product lists, Even if the reviews are disabled in the system.

**Comment by cgcmart** [comment]
The same as Master branch.

**Comment by cgcmart** [comment]
@danielkerr 

Exception:  Error: Could not load template .../catalog/view/theme/default/template/product/thumb.twig! in .../system/library/template/twig.php on line 17

Suggest fix upload/catalog/controller/product/thumb.php:

before:
`return $this->load->view('product/thumb', $data);`

Add:
`$data['products'] = array();`

**Comment by danielkerr** [comment]
I uploaded the file.
