### ISSUE TITLE
edit attribute group notice

### ISSUE THREAD

**Issue by TasneemSaeed** [opencart/opencart#7907]
I cloned this repo 2 days ago and it seems to have a weird issue

when I try to edit any attribute group it throws a notice : 
Notice: Undefined property: Proxy::0 in [mypath]/admin/controller/catalog/attribute_group.php on line 307

Server / Test environment :
 - nginx
 - ubuntu 18.04
 - PHP 7.2
 - Google chrome / Edge
 - cloned git repository version

**Comment by danielkerr** [comment]
fixed already
