### ISSUE TITLE
Changing SEO urls leads to 404 Error

### ISSUE THREAD

**Issue by pipetko** [opencart/opencart#7908]
After changing already set up SEO URLS of cathegories, products or information pages they all lead to 404 Error. Weirdly the Long urls, normal ones nonSEO like /index.php?route=information/information&information_id=6 are working. Tried turning of and uninstaling extension, cleaning caches, removing htaccess, nothing helped.

The SEO Urls ware done by the owner but he made them with mixed symbols (cyrilic and latin plus spaces ), so I descidet to make them properly like "some-product-name-1", but after that liek I sayd 404 ERRORs to all cathegories, products and info pages.

I cant fix them. I do not want to start at the beggining, they wont pay me for that, doing it for free but I am sick of it.

**Comment by osworx** [comment]
> I cant fix them. I do not want to start at the beggining, they wont pay me for that, doing it for free but I am sick of it.

And we here should not getting sick of reading such useless messages?

**Comment by straightlight** [comment]
Not a bug.
