### ISSUE TITLE
Warning: Division by zero in /home/fitmi/public_html/admin/model/localisation/currency.php on line 141

### ISSUE THREAD

**Issue by danielahorowitz** [opencart/opencart#7909]
I just install your software. I got the following PHP warning.
Warning: Division by zero in /home/fitmi/public_html/admin/model/localisation/currency.php on line 141

**Comment by straightlight** [comment]
Are you reporting this issue for the master branch?

**Comment by danielkerr** [comment]
i can not find this issue

**Comment by danielahorowitz** [comment]
I found this when I installed opencart from the downloaded zip. Not sure which branch supports the zip in you SDLC.

**Comment by danielkerr** [comment]
its fixed in the master

**Comment by danielahorowitz** [comment]
Thanks
