### ISSUE TITLE
addAttribute is not defined

### ISSUE THREAD

**Issue by Fayozjon** [opencart/opencart#7910]
**Версия 3.0.3.2**

**Describe the bug**
On add attribute to item error

**To Reproduce**
1. Go to 'Cataloge->Items->add'
2. Click on 'Attributes and + sign'
3. Open console

**Expected behavior**
Adding attributes to item

**Comment by straightlight** [comment]
Are you reporting this issue for the master branch?

**Comment by danielkerr** [comment]
just tested and its working fine. i did fix an issue with attribute groups though
