### ISSUE TITLE
Third party adware scripts on opencart.com 

### ISSUE THREAD

**Issue by yogesch** [opencart/opencart#7914]
This is more of a security report than a bug report per se. 

On the opencart.com website I often notice that clicking anywhere on a webpage opens up a new tab with a strange ad/url. Looking closer I see this is due to a script from an unknown site. 

While third party cookies will soon be prevented by future browser releases, I also believe we should not depend on just the browser, and fix our our sites. I don't know this site design well enough to do something myself, so I am hoping someone more knowledgeable can throw some light on this. Because the same problem happens on my brand new opencart store website as well. 

![Screen Shot 2020-04-29 at 16 39 05](https://user-images.githubusercontent.com/18548961/80593043-1699b900-8a3e-11ea-9fff-d3907bbb774c.png)

![Screen Shot 2020-04-29 at 17 25 35](https://user-images.githubusercontent.com/18548961/80593309-9a53a580-8a3e-11ea-9ddc-bc23207c2a65.png)

**Comment by schiggi** [comment]
I cannot confirm that. It might be probably a faulty extension in your browser/PC.
