### ISSUE TITLE
issue with shipping rate at the checkout

### ISSUE THREAD

**Issue by Amir-SSDC** [opencart/opencart#7915]
**What version of OpenCart are you reporting this for?
3.0.3.2

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

the bug is effecting the shipping charge amount at the checkout causing wrong (mismatch amount while payment)

**To Reproduce**
- adding a product can be shipped and go to checkout and fill the address details. 
- aramex extension will show the shipping coast for example (31) including tax
2. Scroll down to see the sub totals and you will see Aramex shipping charges is 30 without tax

**Expected behavior**

Aramex shipping charges should be the amount 31 which is including tax as per the live calculated amount at the shipping method section 
** tax is 5% in this case

below errors are showing in the logs

2020-04-29 21:57:44 - PHP Notice:  Undefined index: title in /home/********/public_html/catalog/model/extension/total/shipping.php on line 7
2020-04-29 21:57:44 - PHP Notice:  Undefined index: cost in /home/********/public_html/catalog/model/extension/total/shipping.php on line 8
2020-04-29 21:57:44 - PHP Notice:  Undefined index: tax_class_id in /home/********/public_html/catalog/model/extension/total/shipping.php on line 12
2020-04-29 21:57:44 - PHP Notice:  Undefined index: cost in /home/********/public_html/catalog/model/extension/total/shipping.php on line 24

**Screenshots / Screen recordings**

![Screenshot 2020-04-30 01 06 53](https://user-images.githubusercontent.com/46844157/80647455-8e3c0800-8a7f-11ea-812e-de90aaf880e2.png)

![Screenshot 2020-04-30 01 07 14](https://user-images.githubusercontent.com/46844157/80647496-9b58f700-8a7f-11ea-950a-8d62849005fd.png)

if you want to develop the issue personally, you can visit https://www.scubashade.com/
 

 - Local development? Deployed to a web server?
cpanel
 - Operating system
WHM cpanel
 - PHP version 7.2

- here is the shipping.php at /public_html/catalog/model/extension/total/shipping.php

![Screenshot 2020-04-30 01 35 15](https://user-images.githubusercontent.com/46844157/80649372-f0e2d300-8a82-11ea-8854-32e0f8e233ee.png)

requesting support as soon as possible

**Comment by straightlight** [comment]
Using custom theme, according to screenshot. The issues tab is for the master branch.

**Comment by Amir-SSDC** [comment]
the same issue is happening even without the custom checkout. is there any assistance?

**Comment by straightlight** [comment]
Have you tried on a fresh master branch installation version without any extensions installed noticing the same issue or you're just trying this from the same store?
