### ISSUE TITLE
language error -  Undefined index: language_id , public_html/catalog/controller/extension/module/ocmegamenu.php on line 98

### ISSUE THREAD

**Issue by mrinalrastogi** [opencart/opencart#7918]
facing a new error in the file,
On website it is working fine but on the admin page I am getting text_home, text_pagination are coming and no products and no customers are coming on the admin page.
please help me to fix this issue.

**Comment by straightlight** [comment]
Are you reporting this issue for the master branch?

**Comment by straightlight** [comment]
This is an extension, got nothing to do with the master branch!
