### ISSUE TITLE
Bad MySql table in /admin/model/extension/fraud/ip.php

### ISSUE THREAD

**Issue by amanaloaie** [opencart/opencart#7919]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
In line 14, in function uninstall it says:
$this->db->query("DROP TABLE IF EXISTS `" . DB_PREFIX . "ip`");

I suppose there should be:
$this->db->query("DROP TABLE IF EXISTS `" . DB_PREFIX . "fraud_ip`");

**Comment by straightlight** [comment]
Issue found in the master branch: https://github.com/opencart/opencart/blob/master/upload/admin/model/extension/fraud/ip.php#L14 . Good catch!
