### ISSUE TITLE
Wrong column name in /install/model/upgrade/1005.php

### ISSUE THREAD

**Issue by amanaloaie** [opencart/opencart#7920]
**What version of OpenCart are you reporting this for?**
3.0.3.3

**Describe the bug**
In line 36 it says:
$this->db->query("INSERT INTO " . DB_PREFIX . "api (api_id, name, `key`, status, date_added, date_modified) values(1, 'json', '" . hash('sha512', mt_rand()) . "' , 1, now(), now())");

However in table `" . DB_PREFIX . "api` there is no column "name" only "username".

**Comment by straightlight** [comment]
Confirmed.

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/commit/a681709e55509e48feb7c83364a060e58c2e907e
