### ISSUE TITLE
Ssl problem with seo url

### ISSUE THREAD

**Issue by SemihCag** [opencart/opencart#7921]
Version 3.0.3.3
I have a problem when I activate seo url and ssl in the store settings.

When I enter the homepage, the link is https:// but the product links, menu, category links are created as http://

I solved this problem in the core code as follows.

system>framework.php 116
`$registry->set('url', new Url($config));`

catalog>controller>startup>startup.php 39
`$this->registry->set('url', new Url($this->config));`

system>library>url.php 
private $config_secure; add to the Class

Class construct
`public function __construct($config) {
		$this->url = $config->get('config_url');
		$this->ssl = $config->get('config_ssl');
		$this->config_secure = $config->get('config_secure');
	}`

add to the first line in link function
`if($this->config_secure == 1){
			$secure = true;
		}`

**Comment by danielkerr** [comment]
you need to alter your config.php and admin/config.php
