### ISSUE TITLE
Able to download  PHP file of opencart.com

### ISSUE THREAD

**Issue by Atharv34** [opencart/opencart#7923]
Hello team,
Atharv here found php file of your domain,please fix it as soon as possible

**To Reproduce**

1. Go to the below url : 
https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.opencart.com/forum/download/file.php%3Fid%3D18446&ved=2ahUKEwjy7qzv55rpAhXQbn0KHS8zApEQFjAGegQIChAB&usg=AOvVaw2uF2S8WSWtL2dW1Y-0bZNx
2. Download the file

Impact:
attacker can download any .php file on the web leading to huge information about the server. data.gov implement saml (open-source), the config.php file in the saml config folder can be downloaded by the direct url request, it contains sensitive information such as: auth.adminpassword, tecnical contact email, and (possibly) database password.
 
My mail id for contacting : 
cyberoy34@gmail.com

Thanks

**Comment by sabeti05** [comment]
Hi
Are you talking about the OpenCart forum?
https://www.opencart.com/forum

**Comment by Atharv34** [comment]
No.

**Comment by Atharv34** [comment]
Hello I am able to download opencarts php file.

**Comment by sabeti05** [comment]
Hi

Maybe I didn't get it right, but your link refers to the forum.

**Comment by Atharv34** [comment]
Hello sir,you can try here :
https://drive.google.com/file/d/1KWDQ3j0Dkq8-flv8aS0G0xzGvVq1XGZK/view?usp=drivesdk

**Comment by sabeti05** [comment]
It downloads a pdf file for me. I think it is an attachment form the forum posts.

**Comment by danielkerr** [comment]
you nearly scared me to death!

opencart.com does not run on 1ubuntu3.8

**Comment by danielkerr** [comment]
some one uploaded the pdf file of their own server config.

**Comment by Atharv34** [comment]
Ok
Thanks 😊
