### ISSUE TITLE
Issue in Creating Product Listing OC 3.0.3.2

### ISSUE THREAD

**Issue by ankitjn227** [opencart/opencart#7924]
Geeting Error just After Saving the Product Listing in Opencart Admin Panel.

Error -- 

Fatal error: Uncaught Exception: Error: Duplicate entry '497-0' for key 'PRIMARY'<br />Error No: 1062<br />INSERT INTO oc_product_to_store SET product_id = '497', store_id = '0' in /home/ambrokuf/public_html/system/library/db/mysqli.php:40 Stack trace: #0 /home/ambrokuf/storage_opencartnew/modification/system/library/db.php(58): DB\MySQLi->query('INSERT INTO oc_...') #1 /home/ambrokuf/storage_opencartnew/modification/admin/model/catalog/product.php(18): DB->query('INSERT INTO oc_...') #2 /home/ambrokuf/storage_opencartnew/modification/system/engine/loader.php(256): ModelCatalogProduct->addProduct(Array) #3 /home/ambrokuf/public_html/system/engine/proxy.php(47): Loader->{closure}(Array, Array) #4 /home/ambrokuf/storage_opencartnew/modification/admin/controller/catalog/product.php(29): Proxy->__call('addProduct', Array) #5 /home/ambrokuf/storage_opencartnew/modification/system/engine/action.php(79): ControllerCatalogProduct->add() #6 /home/ambrokuf/public_html/admin/controller/startup/router.php(26): Action->execute(Object( in /home/ambrokuf/public_html/system/library/db/mysqli.php on line 40

When Refresh Getting same Error Page.

On Clicking Back Button, and again goto Catalog>Products 

then when we search the product we have created last, with whome getting error

Product was created / listed but with few details, not all fields that we have submitted last.

Help Require

**Comment by SilverFoxWebDesigners** [comment]
Can you share the URL?

**Comment by ankitjn227** [comment]
@SilverFoxWebDesigners 

https://ambrocia.com/admin/index.php?route=catalog/product/add&user_token=CrvnR2hxkc0lE0DPhzq7oGZu0lYaUG8b

**Comment by ankitjn227** [comment]
> Can you share the URL?

@SilverFoxWebDesigners 

https://ambrocia.com/admin/index.php?route=catalog/product/add&user_token=CrvnR2hxkc0lE0DPhzq7oGZu0lYaUG8b

**Comment by SilverFoxWebDesigners** [comment]
Looks like you have customized the core of Opencart?

**Comment by ankitjn227** [comment]
> Looks like you have customized the core of Opencart? 

No, I haven't changed anything.. 

Let be in case, how to resolve it?

**Comment by straightlight** [comment]
Are you reporting this for the master branch? If so, please export the database product_to_store table's CREATE TABLE query and post it here (NOT the INSERTs!).

**Comment by ankitjn227** [comment]
need help to resovle the issue asap...

**Comment by straightlight** [comment]
Since a question has been asked to you on the above but have not answered, you could always create a new service request to the OC team or their partners to resolved this issue specifically.
