### ISSUE TITLE
Admin Add Order History Error

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7928]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
OK
<b>Notice</b>:  Undefined property: Proxy::get in <b>.../catalog/controller/mail/order.php</b> on line <b>29</b>

**To Reproduce**
1. Go to 'Sales >> Orders'
2. Click on 'View'
3. Scroll down to 'Add History'

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by straightlight** [comment]
In catalog/controller/mail/order.php file, on line 29:

```$order_info = $this->model_checkout_order->getOrder($order_id);```

add above:

```$this->load->model('checkout/order');```

Do the same on line 368. This should rectify the issue.
