### ISSUE TITLE
Can't add, edit or delete products to/from orders in admin, no any error message (bluehost)

### ISSUE THREAD

**Issue by o4itea** [opencart/opencart#7930]
Hi, 
The products not showing up when I add, edit or delete in Sale->Orders in admin section (json get response empty from api/cart/products) and without getting any error message.

gif video of issue (http://o4itea.com/add-edit-delet.gif)
response in console (http://o4itea.com/sale-order.jpg)

Actually, this problem does not exist with WAMP(local sarver) or goddady .com host but only when I use bluehost .com host.
oc 3.0.3.2 php 7.2

Can you please help me
https://alorood.com/test/admin/index.php?route=sale/order/edit&order_id=1
user: user
pass: pass

**Comment by o4itea** [comment]
I made a comparison of the store in Godaddy (which work good) and Bluehost (which has problem)
I found that Blueاost puts a response header: [age](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Age), when this header is set I got the problem.

Ant suggestion

**Comment by danielkerr** [comment]
maybe check the local time zone. i yopu need to reseach more. this is has nopthing to do with opencart. have u tested other scripts
