### ISSUE TITLE
Error in FedEx Shipping module which causes FedEx not to display during checkout

### ISSUE THREAD

**Issue by D-whitten** [opencart/opencart#7932]
Opencart 3.x

Stock FedEx Shipping module has an error around line 104 in admin/view/template/extension/shipping/fedex.twig which causes FedEx shipping not to display during checkout

`   <input type="checkbox" name="fedex_service[]"`

needs to be changed to:

`   <input type="checkbox" name="shipping_fedex_service[]"`

**Comment by danielkerr** [comment]
was removed in master branch
