### ISSUE TITLE
Admin can not modify order, sucks at step 4 shipping detail

### ISSUE THREAD

**Issue by maplewang** [opencart/opencart#7933]
fresh installed Opencart 3.0.3.3, installed USPS plugin and enabled it, but not set corresponding user/passwd for USPS. 
when logged in admin and edit an exist order, it sucks at step 4 shipping detail, no warning or errors.  by checking chrome console, it breaks at usps not working.

So is there any way to give warning on that?

**Comment by danielkerr** [comment]
ups is removed from master branch. ask in the forums
