### ISSUE TITLE
OC 3.0.3.2 Coupon Code Working Issue

### ISSUE THREAD

**Issue by ankitjn227** [opencart/opencart#7935]
OC 3.0.3.2 Coupon Code Working on all Categories instead of 1 Category for which created

Parent Category 1 >>  'A'
Child Category Under Parent Category 1 >> 'X'

Parent Category 2 >> ........

Coupon code Created for Child Category Under Parent Category 1 >> 'X'

But it was working on complete site all category products.

Need Help

**Comment by ADDCreative** [comment]
Tested in version 3.0.3.2 and worked OK for me.

**Comment by ankitjn227** [comment]
> Tested in version 3.0.3.2 and worked OK for me.

@ADDCreative NOT working for me.

How to resolve the issue..

**Comment by ADDCreative** [comment]
You need to post on https://forum.opencart.com/ with as much information as possible. Such as version, theme, extensions, settings you are using for the coupon, link to your site, etc.

**Comment by straightlight** [comment]
The addressed issue is about OC v3.0.3.2 whereas the issues on this namespace is about the master branch. Unless you can demonstrate the posted steps can be reproduced on the master branch, this commit will now be closed.
