### ISSUE TITLE
[Master Branch] - Gift Voucher Catalog Model

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7937]
In catalog/model/extension/total/voucher.php file,

this line will create a problem if the order statuses from the admin systems settings no longer matches with the order statuses of the orders already created:

```$order_query = $this->db->query("SELECT order_id FROM `" . DB_PREFIX . "order` WHERE order_id = '" . (int)$voucher_query->row['order_id'] . "' AND order_status_id IN(" . implode(",", $implode) . ")");```

The IN statement implies that if one order status ID fails, all fails as opposed to the catalog/model/account/download.php where an OR statement is rather used to capture any relevant order status IDs within the orders.

**Comment by webkul-dilip** [comment]
@danielkerr Please check this issue.

**Comment by WebkulOpencart** [comment]
This is not an issue so closing the same.
