### ISSUE TITLE
Required Custom_fields do not seem to be checked on guest checkout

### ISSUE THREAD

**Issue by lowv-developer** [opencart/opencart#7939]
3.0.3.2

I noticed that there is a small issue and it is copied to the last version also:

Required Custom_fields do not seem to be checked on guest checkout.

The truth is that they are and if you have not added any special regex checks you may not notice it.

There is a default value on all custom fields of 2 spaces from this line

{% if guest_custom_field[custom_field.custom_field_id] %} {{ guest_custom_field[custom_field.custom_field_id] }} {% else %} {{ custom_field.value }} {% endif %}

You need to change it without spaces

{% if guest_custom_field[custom_field.custom_field_id] %}{{ guest_custom_field[custom_field.custom_field_id] }}{% else %}{{ custom_field.value }}{% endif %}

there are 10 instances in catalog/view/theme/template/checkout/guest.twig

thanks for reading

**Comment by straightlight** [comment]
Anyone else able to reproduce that reported issue on the master branch?

**Comment by lowv-developer** [comment]
if the spaces are present the placeholder text is not shown

**Comment by pao2pao16** [comment]
Not sure yet if this is related.

But in affiliate signup, required custom fields that are created for address is also here. Only invisible.

Therefore, the signup cant get through

To replicate issue.
1. Create new customer custom field.
2. Location must be Address
3. I chose Text as the Type.
4. Checked customer group default and required default.
5. Save

**Comment by straightlight** [comment]
This solution has been added in the pre-release version. See if that fixes the issue you're both reporting about.

**Comment by straightlight** [comment]
As posted on the above, this issue has now been fixed on the pre-release version. Therefore, this commit will now be closed.

**Comment by pao2pao16** [comment]
@straightlight 

Can you share which file to check on the pre-release version? I cant just upgrade everything to a pre-release version.

Thank you

**Comment by straightlight** [comment]
Simply use a command line in your console or use a software to track the lines of code you require once the pre-release downloaded. This namespace is to report issues, not to guide the people on how to track things. Furthermore, you could post on the Opencart forum: https://forum.opencart.com .
