### ISSUE TITLE
[Master Branch]SEO url still not working

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#7942]
[Master Branch]SEO url still not working, all pages go to the home page.
https://www.ectransistors.com/opencartalpha/en-gb/cvcvc

**Comment by chongshengdz** [comment]
tested with latest updates.

**Comment by danielkerr** [comment]
did u rename .htaccess? what about mor rewrite on apache is it enabled.

**Comment by chongshengdz** [comment]
> did u rename .htaccess? what about mor rewrite on apache is it enabled.

you need to believe me i am not the first time user.
if you don't believe, you can install and test it yourself.

**Comment by danielkerr** [comment]
Will retest

**Comment by cgcmart** [comment]
@chongshengdz I did a fresh installation of master branch, but the result is different from yours. There is no any seo url rewrite. All urls are accessible but contain `index.php?route=`

**Comment by chongshengdz** [comment]
> Will retest

after editing .htaccess and changing from 
RewriteRule ^([^?]*) index.php [L,QSA]
to
RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]
all seo urls works fine.

**Comment by karimzi007** [comment]
enable SEO from setting > rename .htaccess.txt or change .htaccess code
or follow this step https://karimzi.blogspot.com/2021/06/opencart-seo-url-not-working.html
