### ISSUE TITLE
OCSESSID - Session Cookie will be rejected as samesite none or invalid without secure attribute

### ISSUE THREAD

**Issue by RichardThomas1** [opencart/opencart#7946]
**What version of OpenCart are you reporting this for?**
3.0.3.3 and 2.3.0.2

**Describe the bug**
Cookie “OCSESSID” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To learn more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies

**To Reproduce**
Firefox 76.0.1 console error message.

Although the roll-out is temporarily held on account of Covid-19, Chrome is also enforcing this:
https://blog.chromium.org/2020/04/temporarily-rolling-back-samesite.html

**Expected behavior**
Expect continue working once enforcement is rolled-out across all browsers.
https://developer.mozilla.org/docs/Web/HTTP/Cookies
This states: Browsers are migrating to have cookies default to SameSite=Lax. If a cookie is needed to be sent cross-origin, opt out of the SameSite restriction by using the None directive. The None directive requires that the Secure attribute also be used.

**Additional context**
Concerned for both V3.0.3.3 and same on live stores V2.3.0.2: Cookie “default” will be soon rejected.

**Comment by cgcmart** [comment]
Both Edge and Firefox throw out `Error: invalid session id!` when navigate demo store after master branch installation completed.

**Comment by danielkerr** [comment]
Cookie “OCSESSID” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by RichardThomas1** [comment]
How do you prevent this on V2.3.0.2?

**Comment by danielkerr** [comment]
im checking now

**Comment by danielkerr** [comment]
need to replace all set cookies like:

setcookie('language', $code, time() + 60 * 60 * 24 * 30, '/', $this->request->server['HTTP_HOST']);

to 

$option = array(
	'expires'  => time() + 60 * 60 * 24 * 30,
	'path'     => ini_get('session.cookie_path'),
	'domain'   => $this->request->server['HTTP_HOST'],
	'secure'   => 0,
	'httponly' => 0,
	'SameSite' => 'None'
);

setcookie('language', $code, $option);

**Comment by RichardThomas1** [comment]
Thanks - found some in catalog/controller/startup/startup.php but not OCSESSID - which files need modifying please? or are you able to offer a Vqmod as this is going to impact everyone as the browsers are updated?

**Comment by RichardThomas1** [comment]
Cokie is "default" on V2.3.0.2 but still can't find where it is set?

**Comment by danielkerr** [comment]
i will add the commit with the fix in.

**Comment by osworx** [comment]
> 
> 
> need to replace all set cookies like:
> 
> setcookie('language', $code, time() + 60 * 60 * 24 * 30, '/', $this->request->server['HTTP_HOST']);
> 
> to
> 
> $option = array(
> 'expires' => time() + 60 * 60 * 24 * 30,
> 'path' => ini_get('session.cookie_path'),
> 'domain' => $this->request->server['HTTP_HOST'],
> 'secure' => 0,
> 'httponly' => 0,
> 'SameSite' => 'None'
> );
> 
> setcookie('language', $code, $option);

Daniel: with an array it will **NOT work if php < 7.3**
See: https://stackoverflow.com/questions/57401836/setcookie-expects-parameter-3-to-be-integer-array-given

A "work-around" which will work could be:
`setcookie('language', $code, time() + 60 * 60 * 24 * 30, '/; SameSite=Strict', $this->request->server['HTTP_HOST']);`

Same goes for the cookie (same file): **currency & tracking**.
Possible "work-around" for the session cookie (default) could be:
`setcookie($key, $this->session_id, ini_get('session.cookie_lifetime'), ini_get('session.cookie_path') . '; SameSite=Strict', ini_get('session.cookie_domain'), ini_get('session.cookie_secure'), ini_get('session.cookie_httponly'));`

See for this here: https://www.php.net/manual/de/function.setcookie.php#125028

**Comment by danielkerr** [comment]
ok cheers. just wasted 2 hours

**Comment by RichardThomas1** [comment]
Hope you can please suggest mods for V2.3.0.2?  
Dont have file catalog/controller/common/cookie.php
system/framework.php doesn't have setcookie()

**Comment by osworx** [comment]
This is 2.3.x (guess for the whole 2.x branch - have no time currently for 3.x):
`catalog/controller/startup/startup.php`
and
`system/library/session.php`

**Comment by osworx** [comment]
> 
> 
> ok cheers. just wasted 2 hours

Sorry, more to read (if php < 7.3 and >= 7.3):
https://stackoverflow.com/questions/39750906/php-setcookie-samesite-strict

**Comment by danielkerr** [comment]
should be fixed now

**Comment by danielkerr** [comment]
please test

**Comment by danielkerr** [comment]
still has issues.

**Comment by osworx** [comment]
I have played around the last hours with several settings and definitions.

All except the session cookie were successful.
Have now one problem, that also the prior working solution does not work on one server on a client.
Don't know why, have to invastigate more ..

Even not with that entry in the .htaccess (a test because setting the cookies on that server (Debain, php 7.3.8) via the php-scripts were never successfull!):

`# Header edit Set-Cookie ^(.*)$ "$1; Secure; SameSite=none"`

**Comment by condor2** [comment]
> How do you prevent this on V2.3.0.2?

Test with this settings.
https://github.com/condor2/Opencart_2302/commit/97ee188b02dd7fe354332020fa4185ab3d8e7dfd

Foum topic
https://forum.opencart.com/viewtopic.php?t=216579

**Comment by danielkerr** [comment]
setcookie($key, $this->session_id, ini_get('session.cookie_lifetime'), ini_get('session.cookie_path') . '; SameSite=Strict', ini_get('session.cookie_domain'), ini_get('session.cookie_secure'), ini_get('session.cookie_httponly'));

does not work! ffs. dont post possilbe fixes! test it your self!

**Comment by osworx** [comment]
> Test with this settings.
> [condor2/Opencart_2302@97ee188](https://github.com/condor2/Opencart_2302/commit/97ee188b02dd7fe354332020fa4185ab3d8e7dfd)
> 
> Foum topic
> https://forum.opencart.com/viewtopic.php?t=216579

If setcookie is set/used with an array ($options), you need at least php 7.3
Do you want to force all OpenCart users to use at least php 7.3 as minimum?
There must be another possibility.

**Comment by condor2** [comment]
That code wasn't changed...on another repo I added something like this

`			if (version_compare(phpversion(), '7.3.0', '<')) {
				setcookie('language', $code, time() + 60 * 60 * 24 * 30, '/', $this->request->server['HTTP_HOST']);
			} else {
				setcookie('language', $code, ['expires' => time() + 60 * 60 * 24 * 30, 'path' => '/', 'domain' => $this->request->server['HTTP_HOST'], 'samesite' => 'None', 'secure' => true]);
			}`

**Comment by osworx** [comment]
Okay, but that does not solve the "problem" that _if the shop use php < 7.3_ the **sameSite** value cannot be set.
Or am I wrong?

**Comment by condor2** [comment]
No you can't use SameSite...because was introduced in php > 7.3

**Comment by osworx** [comment]
Okay, but that does not solve the "problem" that if the shop use php < 7.3 the sameSite value cannot be set.
Or am I wrong?

> 
> 
> No you can't use SameSite...because was introduced in php > 7.3

That implies that all Shops (not OpenCart only) have to update their php version to at least the 7.3.x version.
Or not to use the latest version of all browsers ...

While 2nd option it not an option, Daniel has to decide how to go forward ..

**Comment by condor2** [comment]
Based on comment from here:
https://www.php.net/manual/ro/function.setcookie.php#124644

For earlier version should work with:
`header('Set-Cookie: cross-site-cookie=bar; SameSite=None; Secure');`

Yes, Daniel decide.

**Comment by danielkerr** [comment]
this is ridiculous. php should have put some sort of fix in. guess i have to wirte a set cookie function.

**Comment by dariygray** [comment]
Replace
`setcookie('language', $code, time() + 60 * 60 * 24 * 30, '/', $this->request->server['HTTP_HOST'], true, false);`
with
`setcookie('language', $code, time() + 60 * 60 * 24 * 30, '/', $this->request->server['HTTP_HOST'], true, false);`
or
`setcookie('language', $code, time() + 60 * 60 * 24 * 30, '/', $this->request->server['HTTP_HOST'], true, true);`

Replace
`setcookie($config->get('session_name'), $session->getId(), ini_get('session.cookie_lifetime'), ini_get('session.cookie_path'), ini_get('session.cookie_domain'));`
with
`setcookie($config->get('session_name'), $session->getId(), ini_get('session.cookie_lifetime'), ini_get('session.cookie_path'), ini_get('session.cookie_domain'), ini_get('session.cookie_secure'), ini_get('session.cookie_httponly'));`

... it works on php 7.2

**Comment by condor2** [comment]
> That implies that all Shops (not OpenCart only) have to update their php version to at least the 7.3.x version.

I saw on some servers only php 7.3 can be selected...
On my hosting I can chose from 5.2 until 7.4.

**Comment by danielkerr** [comment]
better info here

https://dev.to/vzuburlis/secure-better-your-website-with-samesite-cookies-33po

**Comment by condor2** [comment]
I think SameSite will be a headache for developers

https://www.thinktecture.com/en/identity/samesite/samesite-in-a-nutshell/

For info

https://github.com/ovunctukenmez/SameSiteCookieSetter

**Comment by osworx** [comment]
I have seen all those docs and read them yesterday.

The SameSite script use also this as fallback if php < 7.3:
`$new_label = '; SameSite=' . $same_site;`

**Comment by osworx** [comment]
I have 'played' now with the script from here:
https://github.com/ovunctukenmez/SameSiteCookieSetter

With a small adoption (the default cookie path is wrong when called from admin, so define the path with the call), it works on several servers with different php-versions from 7.1 up to 7.4

Just place the script e.g. in the library folder, and call it once like:
`require_once DIR_SYSTEM . 'library/SameSiteCookieSetter.php';`

And then for example (default cookie):
`SameSiteCookieSetter::setcookie( $key, $this->session_id, ['secure' => true, 'samesite' => 'None'] );`

I know this can't be the final solution, but better than nothing.
Maybe you Daniel want to have a look?

**Comment by danielkerr** [comment]
no way am i including a 3rd party script just for fixing the cookies

**Comment by danielkerr** [comment]
ok i have done another commit please test.

**Comment by danielkerr** [comment]
ok noticed the session not starting straght away on firefox

**Comment by danielkerr** [comment]
is any one sure this is going to actually cause an issue because it seems it just for cookies that go across multiple domains.

**Comment by Jusufas** [comment]
There is an error after this changes:
`Error: Using $this when not in object context in /.../system/framework.php on line 128`

**Comment by osworx** [comment]
> 
> 
> no way am i including a 3rd party script just for fixing the cookies

Confirmed!
The less including 3PD scripts just fix such an minor (but major impact in the result) issue, the less  work in future.

While - I know this is quite a lot of work, but looking around (e.g. Bootstrap with v.5) wouldn't it make sense to go ahead with the 3.1 branch and update all there needed libraries?
And define as minimum php-version 7.3?
That would solve that right now.

**Comment by RichardThomas1** [comment]
I am not a software “developer” but I am an electronics engineer very familiar with OC and may have a different views / ideas which may help.

I am thinking, just define the Secure attribute and let Samesite default as before, which is different on different browsers but is expected behaviour for the user of that browser (therefore Samesite PHP support not relevant).

Even with secure sites (like mine and the OC hosted demo store), the cookie shows Secure as false. The error message on Firefox console is because Samesite is not defined “without secure attribute”.

As browsers default to Samesite=LAX, perhaps this is Okay. If the store has language / currency and not arrived on a top level page then perhaps re-load the page (or whatever) instead (but not necessary otherwise).

For logged-in users it is not relevant as would not expect to still be logged-in from an external navigation on a browser that does not normally do this (seen this before on other sites anyway).

Not looking for a reply or why it won’t work – just putting out there in case sparks ideas for the proper “developers” to pick up on. This thread may be looking into too much detail to keep the full OC functionality the same across browsers and PHP versions and focusing too much on Samesite. 

Ensuring the cookie isn’t rejected may be possible an easier way (and could just be that Secure is not defined – I can’t test until late tonight but as I know this is hot topic (and may spark other ways to solve the problem) I am sharing now in case it helps.

**Comment by danielkerr** [comment]
try my latest

**Comment by danielkerr** [comment]
latest commit fixes any cookie path issues

**Comment by ADDCreative** [comment]
> is any one sure this is going to actually cause an issue because it seems it just for cookies that go across multiple domains.

It is just for cross domains. A few payment modules will have issues with the new SameSite changes. One example is the old PayPal Standard payment module which is widely used by OpenCart users. While the payment will go through, when the customer returns to the store they will be logged out as PayPal uses a POST to go to checkout/success. This is because browsers will change the SameSite default to Lax which only allows the cookie to be set cross site with GET.

To be clear there are actually two parts to the changes coming. First, the default SameSite for cookies that have no declared SameSite, will change from None to Lax. the second is that cookies explicitly set to SameSite=None without "secure" will be blocked.

Web browsers are giving warnings so developer know what to check. When the changes are implemented the warnings will go away because SameSite will no longer be None, but Lax.

Looking at the commits for this issue, they will not help much (the browser will set to Lax for you anyway) and in at least one case actually make things worse. Setting SameSite=Strict on the admin side will cause issues with third-party extensions. It did with the PayPal Commerce module included with 3.0.3.3 when I tried to test.

**Comment by RichardThomas1** [comment]
I have investigated an example of how this is impacting live stores:

Customer placed two consecutive orders and confirmation page after being re-directed back from the payment system for each order was the default if not logged in (can tell by the file size), no order showing in the “Customer Activity” and basket not emptied after complete. Customer did not log in a second time but was still logged-in to place a second order, so session must have subsequently restored. This is consistent with the browser defaulting to Samesite=LAX. 

Have started to see this more recently (orders not in Activity, no order confirmation details and basket not emptying) but not realised the reason until above comment by ADDCreative.

User agent for above example was:
Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1

My suggestion therefore is:

If PHP version supports Samesite and store is secure, then set Samesite=none and Secure=true, else,  set Secure as per the domain and leave Samesite to default as per the browser (most currently "none" and moving to LAX).

This will then allow payment systems that redirect back to the store to show order confirmation to continue working if using a suitable PHP version and store is secure, which is being enforced by the browsers increasing security and out of OC control.

This isn’t just for old systems that POST to checkout/success, as it looks like it impacts all payment systems that return back to the store for the order confirmation (even where the order status is updated another way). 

Likely to be other implications but it looks like the "invalid session id" may not be related to this.

**Comment by danielkerr** [comment]
i have already created a custom function that fixes this. its in my last commit.im closing this since nobody reported the latest version any ccookie issues.

**Comment by danielkerr** [comment]
```
function oc_setcookie(string $key, string $value, $option = array()) {
	if (version_compare(phpversion(), '7.3.0', '>=')) {
		// PHP need to update their setcookie function.
		if (isset($option['max-age'])) {
			$option['expires'] = $option['max-age'];

			unset($option['max-age']);
		}

		setcookie($key, $value, $option);
	} else {
		$string = '';

		if (isset($option['max-age'])) {
			$string .= '; max-age=' . $option['max-age'];
		} else {
			$string .= '; max-age=0';
		}

		if (!empty($option['path'])) {
			$string .= '; path=' . $option['path'];
		}

		if (!empty($option['domain'])) {
			$string .= '; domain=' . $option['domain'];
		}

		if (!empty($option['HttpOnly'])) {
			$string .= '; HttpOnly';
		}

		if (!empty($option['Secure'])) {
			$string .= '; Secure';
		}

		if (isset($option['SameSite'])) {
			$string .= '; SameSite=' . $option['SameSite'];
		}

		header('Set-Cookie: ' . rawurlencode($key) . '=' . rawurlencode($value) . $string);
	}
}
```

**Comment by eka7a** [comment]
Since the expiration date is assigned to the main cookies(OCSESSID), it continues to be stored when the browser is closed and opened. To define the expire as a session, the expire must be zero. When it is zero, the session ends when the browser is closed.

In another problem, the administrator cannot access the site in maintenance mode, as a definitive path has been assigned to the admin cookies.
https://github.com/opencart/opencart/blob/b90e59bdb51747b7f7c334c6f324f0d7b4877c0a/upload/admin/controller/startup/startup.php#L35

**Comment by danielkerr** [comment]
I dont think browsers delete the cookie when its closed anymore when its set to expire at 0.

**Comment by ADDCreative** [comment]
To test you can switch the current version of Chrome into the cookie mode that will be used from Chrome 84 on July 14.

Switch both "SameSite by default cookies" and "Cookies without SameSite must be secure" to Enabled.
chrome://flags/#same-site-by-default-cookies
chrome://flags/#cookies-without-same-site-must-be-secure

For Firefox goto about:config and set "network.cookie.sameSite.laxByDefault" and "network.cookie.sameSite.noneRequiresSecure" to true.

It's going to be mainly payment modules where setting SameSite to Lax or Strict will cause problems.

**Comment by eka7a** [comment]
> I dont think browsers delete the cookie when its closed when its set to expire at 0 anymore.

I also checked firefox and chrome. When set to 0, it acts as a session.

![cookie](https://user-images.githubusercontent.com/5789807/85591156-b98d3e80-b64d-11ea-98ae-cf121c45bb59.png)

**Comment by ADDCreative** [comment]
Browser settings determine if sessions are deleted.

Firefox: On start-up -> Restore previous session
Chrome: On start-up -> Continue where you left off

Have these settings on and sessions won't be deleted.

**Comment by ADDCreative** [comment]
I have made a pull request https://github.com/opencart/opencart/pull/8072 to fix the aforementioned issue with PayPal Standard when the session cookie has SameSite=Lax https://github.com/opencart/opencart/issues/7946#issuecomment-646193666.

**Comment by gpxjordan** [comment]
Hello!

Can someone tell me how to solve this problem in my environment?

OpenCart 2.3.0.2
PHP Version 7.3.21

I believe you have solved this problem, But I have difficulty understanding the operation mode of github.com.

So you may need to tell me how to use the steps and steps to fix my version, Can someone help me?

Thank you!

**Comment by gpxjordan** [comment]
> ```
> function oc_setcookie(string $key, string $value, $option = array()) {
> 	if (version_compare(phpversion(), '7.3.0', '>=')) {
> 		// PHP need to update their setcookie function.
> 		if (isset($option['max-age'])) {
> 			$option['expires'] = $option['max-age'];
> 
> 			unset($option['max-age']);
> 		}
> 
> 		setcookie($key, $value, $option);
> 	} else {
> 		$string = '';
> 
> 		if (isset($option['max-age'])) {
> 			$string .= '; max-age=' . $option['max-age'];
> 		} else {
> 			$string .= '; max-age=0';
> 		}
> 
> 		if (!empty($option['path'])) {
> 			$string .= '; path=' . $option['path'];
> 		}
> 
> 		if (!empty($option['domain'])) {
> 			$string .= '; domain=' . $option['domain'];
> 		}
> 
> 		if (!empty($option['HttpOnly'])) {
> 			$string .= '; HttpOnly';
> 		}
> 
> 		if (!empty($option['Secure'])) {
> 			$string .= '; Secure';
> 		}
> 
> 		if (isset($option['SameSite'])) {
> 			$string .= '; SameSite=' . $option['SameSite'];
> 		}
> 
> 		header('Set-Cookie: ' . rawurlencode($key) . '=' . rawurlencode($value) . $string);
> 	}
> }
> ```


Hello!

Can someone tell me how to solve this problem in my environment?

OpenCart 2.3.0.2
PHP Version 7.3.21

I believe you have solved this problem, But I have difficulty understanding the operation mode of github.com. (Because i don't understand how to modify)

So you may need to tell me how to use the steps and steps to fix my version, Can someone help me?

Thank you!

**Comment by gpxjordan** [comment]
> ```
> function oc_setcookie(string $key, string $value, $option = array()) {
> 	if (version_compare(phpversion(), '7.3.0', '>=')) {
> 		// PHP need to update their setcookie function.
> 		if (isset($option['max-age'])) {
> 			$option['expires'] = $option['max-age'];
> 
> 			unset($option['max-age']);
> 		}
> 
> 		setcookie($key, $value, $option);
> 	} else {
> 		$string = '';
> 
> 		if (isset($option['max-age'])) {
> 			$string .= '; max-age=' . $option['max-age'];
> 		} else {
> 			$string .= '; max-age=0';
> 		}
> 
> 		if (!empty($option['path'])) {
> 			$string .= '; path=' . $option['path'];
> 		}
> 
> 		if (!empty($option['domain'])) {
> 			$string .= '; domain=' . $option['domain'];
> 		}
> 
> 		if (!empty($option['HttpOnly'])) {
> 			$string .= '; HttpOnly';
> 		}
> 
> 		if (!empty($option['Secure'])) {
> 			$string .= '; Secure';
> 		}
> 
> 		if (isset($option['SameSite'])) {
> 			$string .= '; SameSite=' . $option['SameSite'];
> 		}
> 
> 		header('Set-Cookie: ' . rawurlencode($key) . '=' . rawurlencode($value) . $string);
> 	}
> }
> ```


Hello!

Can someone tell me how to solve this problem in my environment?

OpenCart 2.3.0.2
PHP Version 7.3.21

I believe you have solved this problem, But I have difficulty understanding the operation mode of github.com. (Because i don't understand how to modify)

So you may need to tell me how to use the steps and steps to fix my version, Can someone help me?

PS. How to use this code?

Thank you!

**Comment by petsoukos** [comment]
Does this issue still stand? I mean was it fixed on 3.0.3.6 or not ? We have serious issues with payments coming in via redirect methods and using POST for the payment result parameters.

**Comment by ADDCreative** [comment]
No it hasn't been fixed in 3.0.3.6 or the master branch.

There are some examples on the forums how to set cookies with SameSite=None and Secure.
https://forum.opencart.com/viewtopic.php?f=202&t=219633#p797082

**Comment by petsoukos** [comment]
@ADDCreative OK will check it out. Thanks for promt reply.

**Comment by petsoukos** [comment]
@ADDCreative that solution requires core file modification, specifically the system/framework.php It seems this file can't be modified or rather it can be, but OC doesn't load the modified version of it. If there is a way to have it load the modified version I'm all ears

**Comment by danielkerr** [comment]
Anyone want to take over maintaince releases and approving pull requests for them? A lot needs fixing.i need to spend time on the next main release.

**Comment by ADDCreative** [comment]
In answer to https://github.com/opencart/opencart/issues/8640#issuecomment-706066768.

> @ADDCreative what should it be instead of lax? i haven't finished the cookie system. im still going to check what the best option is.

Some payment gateways do require SameSite=None and Secure. Others are happy with the new default of Lax (or no SameSite attribute at all). I think it will need to be configurable, as setting None and Secure for maximum compatibility would lose the security benefit and be a pain if testing locally with no https.

As PHP 7.3 is the minimum, maybe use ini_get and [session.cookie_samesite](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-samesite) and [session.cookie_secure](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-secure). Or just have a setting in the config.

**Comment by dynamiccontent** [comment]
@danielkerr and @ADDCreative 
Highly recommend that code changes to make sure the cookies are more secure are configurable on opencart. Opencart should take care of securing cookies.

For testing https://observatory.mozilla.org is very good. I managed to make changes to core files based on ADDCreative suggestion to pass everything except Cookie prefixes. Don't know if this is good practice or not but would prefer not to make changes to core files. It's not always possible to make sure your web server is changing headers on cookies so this seems the only way right now...

On default opencart install version 3.0.3.6

![secure cookies](https://i.imgur.com/8lHi82f.png)
![opencart install version 3.0.3.6](https://i.imgur.com/dODgmqT.png)

Good info:
https://infosec.mozilla.org/guidelines/web_security#cookies
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

After changes:
![after changes cookies](https://i.imgur.com/NBKfmcI.png)

1. Change file
opencart/catalog/controller/startup/session.php

Find: (OCSESSID HostOnly and HttpOnly default false)
```
setcookie($this->config->get('session_name'),` $this->session->getId(), ini_get('session.cookie_lifetime'), ini_get('session.cookie_path'), `ini_get('session.cookie_domain'));
```
Replace to: (OCSESSID HostOnly set to true, HttpOnly set to true after change)
```
setcookie($this->config->get('session_name'), $this->session->getId(), ['expires' => ini_get('session.cookie_lifetime'), 'path' => ini_get('session.cookie_path'), 'domain' => ini_get('session.cookie_domain'), 'samesite' => 'Lax', 'secure' => true, 'httponly' => true]);
```
2. Change file
opencart/system/framework.php

Find: (OCSESSID Secure default false)
```
setcookie($config->get('session_name'), $session->getId(), ini_get('session.cookie_lifetime'), ini_get('session.cookie_path'), ini_get('session.cookie_domain'));
```

Replace to: (OCSESSID Secure after change set to true)
```
setcookie($config->get('session_name'), $session->getId(), ['expires' => ini_get('session.cookie_lifetime'), 'path' => ini_get('session.cookie_path'), 'domain' => ini_get('session.cookie_domain'), 'samesite' => 'Lax', 'secure' => true, 'httponly' => true]);
```

3. For language and currency secure cookies
https://forum.opencart.com/viewtopic.php?f=190&t=216579&start=20#p796020

3. Change file
opencart/catalog/controller/startup/startup.php

Find:
```
setcookie('language', $code, time() + 60 * 60 * 24 * 30, '/', $this->request->server['HTTP_HOST'])
```

Replace to:
```
setcookie('language', $code, ['expires' => time() + 60 * 60 * 24 * 30, 'path' => '/', 'domain' => $this->request->server['HTTP_HOST'], 'samesite' => 'Lax', 'secure' => true, 'httponly' => true]);
```

Find:
```
setcookie('currency', $code, time() + 60 * 60 * 24 * 30, '/', $this->request->server['HTTP_HOST']);
```

Replace to:
```
setcookie('currency', $code, ['expires' => time() + 60 * 60 * 24 * 30, 'path' => '/', 'domain' => $this->request->server['HTTP_HOST'], 'samesite' => 'Lax', 'secure' => true, 'httponly' => true]);
```
Thank you for your hard work and looking forward to newer version of opencart where cookies are secured.

**Comment by danielkerr** [comment]
ok cheers

**Comment by danielkerr** [comment]
IM WORKING OJN COOKI4ES AND SEO URL NOW. i think for the default cookies like language and currency dont need to be secure but session id will need to be.

**Comment by cgcmart** [comment]
Current master branch changes work. Everything is fine.
Except .htaccess file if host server is Apache 2.4 or higher.
Apache-Error: [file "config.c"] .../.htaccess: Option FollowSymlinks not allowed here.
Comment out:
`# Options +FollowSymlinks`
`# RewriteRule ^([^?]*) index.php [L,QSA]`

Add:
`RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]`

The website complete seo urls are expected.

**Comment by danielkerr** [comment]
ok lets sort this out.

Cookies are mainly used for three purposes:

**Session management
Logins, shopping carts, game scores, or anything else the server should remember**

so user login as we only use session for cart

**Personalization
User preferences, themes, and other settings**

so language, currency

**Tracking
Recording and analyzing user behavior**

so analytics

**Comment by danielkerr** [comment]
i have altered everything that needs to be altered. lax is still used for language and cookies.

**Comment by gpxjordan** [comment]
Can someone tell me how to solve the problem of SameSite Cookie now in OpenCart 2.3.0.2?

Because the previous method does not seem to be applicable to Google Chrome 91, So I need someone to tell me how to fix this problem.
https://24cc.com/975/?fbclid=IwAR2wWQh5-iiY9eNwJp4nKY_y8f6OZWRvmiciDZwDbwiRKv4aff0DIyrSQQE

@danielkerr You can use "dynamiccontent" like his instructions, Tell me how to modify which files?

I need your help, Thank you!

**Comment by ADDCreative** [comment]
@gpxjordan The only thing that is changing in Chrome 91 is the removal of hidden SameSite options meant for developers. If a site worked in Chrome 90 it should work in Chrome 91.
