### ISSUE TITLE
Unable to upgrade from Version 2.3.0.2 to 3.0.3.3

### ISSUE THREAD

**Issue by AlamSirji** [opencart/opencart#7947]
**What version of OpenCart are you reporting this for?**
3.0.3.3

**Describe the bug**
`Fatal error: Uncaught Exception: Error: Table 'xyzDB.oc_session' doesn't exist<br />Error No: 1146<br />SELECT `data` FROM `oc_session` WHERE session_id = '865d958881e97111dfc083cd65' AND expire > 1590360233 in /var/www/project/system/library/db/mysqli.php:40 `

What section does it affect?
Whole Website

**To Reproduce**
1. Upload opencart version 3.0.3.3 files to previous project files
2. Except config.php and admin/config.php
3. Visit Homepage, error is waiting for ...

**Expected behavior**
An upgrade what was promised

**Server / Test environment (please complete the following information):**
 - Local development
 - Linux
 - PHP version 7
 - Apache version 2.4.41-4ubuntu3 i386
 - Browser(s) tested with [All]

**Comment by condor2** [comment]
You don't visit the homepage...just type your website-name/install
