### ISSUE TITLE
index.php?route=account/register  I get the following message when a new user registers. This page isn’t working bizsec.co.za is currently unable to handle this request. HTTP ERROR 500. Using version 3.0.3.3

### ISSUE THREAD

**Issue by hennie2000** [opencart/opencart#7948]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by straightlight** [comment]
Please submit these claims on the Opencart.com forum. It is not a bug related with the master branch nor with OC v3.0.3.3 release itself. This commit will now be closed.
