### ISSUE TITLE
Wrong variable name in /catalog/language/en-gb/information/contact.php

### ISSUE THREAD

**Issue by amanaloaie** [opencart/opencart#7950]
**What version of OpenCart are you reporting this for?**
3.0.3.3

**Describe the bug**
In line 14 the variable $_['text_success'] should be $_['text_message'].

Twig template common/success expects {{ text_message }} in line 18, so after successfully submitting contact form, customer doesn't see the success message.

**Comment by condor2** [comment]
![Screenshot_2020-05-26_16-27-25](https://user-images.githubusercontent.com/14251939/82906459-f6421900-9f6d-11ea-8f0c-8645aa45f819.png)

**Comment by straightlight** [comment]
Already fixed on the master branch.
