### ISSUE TITLE
PostgreSQL install error

### ISSUE THREAD

**Issue by hopyres** [opencart/opencart#7952]
Opentcart could't installation with PostgreSQL server.
Interesant in module postgre.php
`        public function __construct($hostname, $username, $password, $database, $port = '5432') {
                if (!$this->link = pg_connect('hostname=' . $hostname . ' port=' . $port .  ' username=' . $username . ' password='     . $password . ' database=' . $database)) {
                        throw new \Exception('Error: Could not make a database link using ' . $username . '@' . $hostname);
                }

                if (!mysql_select_db($database, $this->link)) {
                        throw new \Exception('Error: Could not connect to database ' . $database);
                }

                pg_query($this->link, "SET CLIENT_ENCODING TO 'UTF8'");
        }`

What is it `if (!mysql_select_db($database, $this->link))`  ?

**Comment by ADDCreative** [comment]
See https://github.com/opencart/opencart/pull/5018.

**Comment by straightlight** [comment]
Closing this commit since the solution has already been merged prior.
