### ISSUE TITLE
Files missing from vendor of oc 3.0.3.4

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#7969]
Hi

There missing files from folder system/storage/vendor/react and system/storage/vendor/symphony. I copied these files from OC 3.0.3.2 to my test page.

**Comment by straightlight** [comment]
Thanks for reporting this. It is already being taken care of as we speak. Stay tuned for the next releases update on Github.

**Comment by straightlight** [comment]
Ok, the pre-release is now ready to use. See this link: https://www.github.com/opencart/opencart/releases . Download either the x-pre.zip or the x-pre.tar file (depending on your OS).

This commit will now be closed. Should you feel the need to report further issues about this pre-release, please create a commit separately based on each different case with the OC version by following the commit template.

**Comment by ADDCreative** [comment]
Wasn't Symfony only required by the Cardinity payment module? Seeing as Cardinity has been removed from 3.0.3.4, is there any point including it?

The same probably goes for the vendor packages for the other payment modules that have been removed. Or are they needed if that payment module is added in the future?

**Comment by straightlight** [comment]
Cardinity has been removed from the pre-release version because cardinity, along with other extension payment modules, was also removed from the master branch.

**Comment by ADDCreative** [comment]
Yes I know. That was my point. If you are removing payment modules, shouldn't you remove their dependencies.

**Comment by straightlight** [comment]
All third party dependencies from the pre-release version, except PayPal Braintree from the vendors should already have been removed as we speak.
