### ISSUE TITLE
PayPal Commerce Platform checkout problem with Japanese yen

### ISSUE THREAD

**Issue by ADDCreative** [opencart/opencart#7972]
**What version of OpenCart are you reporting this for?**
3.0.3.4 Pre-release

**Describe the bug**
If using Japanese yen as the currency the PayPal Commerce Platform payment extension does not allow checkout to be completed and gives the following error.
`Currency does not support decimals. Please refer to https://developer.paypal.com/docs/integration/direct/rest/currency-codes/ for more information.
`

**To Reproduce**
1. Add Japanese yen as a currency.
2. Set up the PayPal Commerce Platform payment extension and select the currency to be Japanese yen in it's settings.
3. As a customer select the currency to be Japanese yen from the drop down.
4. Add a product to cart and checkout.
5. At Step 6: Confirm Order of checkout click the PayPal button. The error message `Currency does not support decimals. Please refer to https://developer.paypal.com/docs/integration/direct/rest/currency-codes/ for more information.
` appears.

**Expected behavior**
Customer should be able to checkout and pay with PayPal.

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/2039130/83338937-ef463e00-a2c0-11ea-9b2c-d50ff523f165.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Web server
 - Operating system linux
 - PHP version 7.1.33
 - Apache version 2.4.43
 - Browser(s) tested with Firefox
 - Version 77.0b9 (64-bit)

**Additional context**
https://github.com/opencart/opencart/issues/7934#issuecomment-632344760

**Comment by straightlight** [comment]
Ok, will keep this topic on hold.

**Comment by webkul-dilip** [comment]
I checked, now the issue has resolved. If you still found the issue please share more detail.
I have attached the screenshot please check.
http://i.prntscr.com/DKJsCAOCQbSuzgqAjyk9nA.png

**Comment by webkul-dilip** [comment]
Please also check this issue comment as well.
https://github.com/opencart/opencart/issues/7934

**Comment by ADDCreative** [comment]
@webkul-dilip The actual commit that fixed the issue was https://github.com/opencart/opencart/pull/8053.
