### ISSUE TITLE
Bug Error when editing products validating custom fields as empty

### ISSUE THREAD

**Issue by ivent** [opencart/opencart#7979]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

When trying to edit orders that have customized fields the same with content you cannot continue to be alert that the field is empty

**To Reproduce**
1. create cutom field
2. buy
3. view sales click edit continue

**### Solution:** 

I found that the validation of the empty field is wrong because it includes a value that does not reach the real field and will soon always be empty to solve it is very simple:

in the file:
`catalog / controller / api / customer.php`

**on line 71 where it has:**

`if ($ custom_field ['required'] && empty ($ this-> request-> post ['custom_field'] [$ custom_field ['location']] [$ custom_field ['custom_field_id']])) {`

**Remove the location change to:**

`if ($ custom_field ['required'] && empty ($ this-> request-> post ['custom_field'] [$ custom_field ['custom_field_id']])) {
`
Ready problem solved, I have this problem for more than a year I don't understand why nobody ever solved it, here is my contribution please check if I did it correctly.

**Comment by ivent** [comment]
Now I have the error in the shipping tab in the custom fields every time I press continue it resets the fields and I have to type them again

**Comment by straightlight** [comment]
Thanks for reporting this. While the issue you're describing has already been fixed in the master branch, a fix will be released soon on the pre-release version for this. Therefore, this commit will now be closed.

**Comment by straightlight** [comment]
This issue has now been fixed on the pre-release version.

**Comment by ivent** [comment]
Olá Muito Obrigado

**Comment by ivent** [comment]
Tanks
