### ISSUE TITLE
Currency bug is not resolved

### ISSUE THREAD

**Issue by ele3c** [opencart/opencart#7981]
**What version of OpenCart are you reporting this for?**
3.0.3.3

**Describe the bug**
A clear and concise description of what the bug is:
Returned value has a problem, since the cURL call fails (url doesn't exists)

What section does it affect? Admin Area (dashboard)
As already noticed, in admin/model/localisation/currency.php

**To Reproduce**
1. Go to Admin Area (dashboard)
2. In the top of the browser windows, appears: "Warning: A non-numeric value encountered in /path/to/docroot/opencartfolder/admin/model/localisation/currency.php on line 141Warning: Division by zero in /path/to/docroot/opencartfolder/admin/model/localisation/currency.php on line 141"

**Expected behavior**
A csv file to download with the correct data, instead the one taken from yahoo server (that is unavailable)

**Server / Test environment (please complete the following information):**
 - Local development
 - XUbuntu 20.04, 64 bit
 - PHP version 7.2
 - Apache version: 2.4.41
 - Browser(s) tested with [Firefox 77.0.1 and Chrome  83.0.4103.61)

**Comment by straightlight** [comment]
This issue has been fixed on the pre-release version. This commit will now be closed.

**Comment by ele3c** [comment]
I still detect it, but .... I solved it anyway, installing plugin, adding my currency, setting the value to 1, and then deleting the other currencies existing.

Thanks
