### ISSUE TITLE
Login/Logout Issue (V 3.0.3.3)

### ISSUE THREAD

**Issue by tarakantnayak** [opencart/opencart#7984]
Hi,
I have installed opencart version : 3.0.3.3

The login/register/logout features work perfectly fine when I work on localhost. However, when I host it, it seems to have some issues. Please see the link below.
https://woo.bestlifelesson.com/

I haven't used any plugin, it's a simple installation with no modification. Please register with your email id. Then it shows MyAccount with all possible drop downs such as Order History, Transactions, Downloads, Logout etc. 
--Then click on "Your Store". Then check the MyAccount (on header), it shows only Register/Login. ---- Then Refresh the page. Nothing happens, it still shows as if you have not logged in.
-- The click on wishlist or shopping cart on the header, then check MyAccount, then it shows that you have logged in.
--Then logout. It appears that you have been logged out. Click again wishlist or shopping cart and return to MyAccount. You will see that you have not been logged out.

But the entire thing works fine on local machine. I am wondering what could be the problem?

Regards,
TN

**Comment by ADDCreative** [comment]
Cache control headers issue. https://github.com/opencart/opencart/issues/7008

As your server is setting future expires headers. This is probably the best way to correct it.
https://forum.opencart.com/viewtopic.php?f=202&t=206449#p786660

**Comment by straightlight** [comment]
Not an issue related with Opencart specifically. This commit will now be closed.
