### ISSUE TITLE
Coupon code can be used multiple times even if it is limitid to just one use per customer.

### ISSUE THREAD

**Issue by TorOle** [opencart/opencart#7986]
We are using ver. 3.0.3.2 using journal theme ver. 3.0.46. 

When a customer proceed orders without being logged in, they may use the coupon code multiple times - even as the "Uses Per Customer" is set to 1.

Our webshop is loosing money by giving extra discount multiple times where it should only be given to the first use of the coupon code.

**Comment by osworx** [comment]
> 
> We are using ver. 3.0.3.2 using **journal theme** ver. 3.0.46.
> 

You say it, ask the support of the template - wrong place here.

**Comment by straightlight** [comment]
Unsupported. This commit will now be closed.
