### ISSUE TITLE
**The right way to do** file permissions for production install opencart 3.0.3.3

### ISSUE THREAD

**Issue by dynamiccontent** [opencart/opencart#7988]
**What version of OpenCart are you reporting this for?**
3.0.3.3

**Describe the bug**
As far as I can see I only detect errors on admin console. See below:

**To Reproduce**
1. Go to 'https://example.com/admin/ (admin login page)'
**Just on login page without logging in**
Warning: fopen(/var/www/html/opencart/admin/view/stylesheet/bootstrap.css): failed to open stream: Permission denied in /var/www/html/opencart/admin/controller/startup/sass.php on line 14Warning: flock() expects parameter 1 to be resource, bool given in /var/www/html/opencart/admin/controller/startup/sass.php on line 16Warning: fwrite() expects parameter 1 to be resource, bool given in /var/www/html/opencart/admin/controller/startup/sass.php on line 18Warning: fflush() expects parameter 1 to be resource, bool given in /var/www/html/opencart/admin/controller/startup/sass.php on line 20Warning: flock() expects parameter 1 to be resource, bool given in /var/www/html/opencart/admin/controller/startup/sass.php on line 22Warning: fclose() expects parameter 1 to be resource, bool given in /var/www/html/opencart/admin/controller/startup/sass.php on line 24 

2. **After logging in to admin console**
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
OK
<b>Warning</b>: fopen(/var/www/html/opencart/admin/view/stylesheet/bootstrap.css): failed to open stream: Permission denied in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>14</b><b>Warning</b>: flock() expects parameter 1 to be resource, bool given in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>16</b><b>Warning</b>: fwrite() expects parameter 1 to be resource, bool given in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>18</b><b>Warning</b>: fflush() expects parameter 1 to be resource, bool given in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>20</b><b>Warning</b>: flock() expects parameter 1 to be resource, bool given in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>22</b><b>Warning</b>: fclose() expects parameter 1 to be resource, bool given in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>24</b>{"order":{"label":"Naro\u010dila","data":[[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],[10,0],[11,0],[12,0],[13,0],[14,0],[15,0],[16,0],[17,0],[18,0],[19,0],[20,0],[21,0],[22,0],[23,0],[24,0],[25,0],[26,0],[27,0],[28,0],[29,0],[30,0]]},"customer":{"label":"Kupci","data":[[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,"1"],[10,0],[11,0],[12,0],[13,0],[14,0],[15,0],[16,0],[17,0],[18,0],[19,0],[20,0],[21,0],[22,0],[23,0],[24,0],[25,0],[26,0],[27,0],[28,0],[29,0],[30,0]]},"xaxis":[["1","01"],["2","02"],["3","03"],["4","04"],["5","05"],["6","06"],["7","07"],["8","08"],["9","09"],["10","10"],["11","11"],["12","12"],["13","13"],["14","14"],["15","15"],["16","16"],["17","17"],["18","18"],["19","19"],["20","20"],["21","21"],["22","22"],["23","23"],["24","24"],["25","25"],["26","26"],["27","27"],["28","28"],["29","29"],["30","30"]]}

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
OK
<b>Warning</b>: fopen(/var/www/html/opencart/admin/view/stylesheet/bootstrap.css): failed to open stream: Permission denied in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>14</b><b>Warning</b>: flock() expects parameter 1 to be resource, bool given in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>16</b><b>Warning</b>: fwrite() expects parameter 1 to be resource, bool given in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>18</b><b>Warning</b>: fflush() expects parameter 1 to be resource, bool given in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>20</b><b>Warning</b>: flock() expects parameter 1 to be resource, bool given in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>22</b><b>Warning</b>: fclose() expects parameter 1 to be resource, bool given in <b>/var/www/html/opencart/admin/controller/startup/sass.php</b> on line <b>24</b>[]

3. **When trying to install extensions**
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
OK
<b>Warning</b>: mkdir(): Permission denied in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>212</b><b>Warning</b>: mkdir(): Permission denied in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>212</b><b>Warning</b>: mkdir(): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>212</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/account.php,/var/www/html/opencart/system/library/advertikon/account.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/accounts.php,/var/www/html/opencart/system/library/advertikon/accounts.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/address.php,/var/www/html/opencart/system/library/advertikon/address.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: mkdir(): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>212</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/advertikon.php,/var/www/html/opencart/system/library/advertikon/advertikon.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/affiliate.php,/var/www/html/opencart/system/library/advertikon/affiliate.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/array_iterator.php,/var/www/html/opencart/system/library/advertikon/array_iterator.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/cache.php,/var/www/html/opencart/system/library/advertikon/cache.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/compatibility_check.php,/var/www/html/opencart/system/library/advertikon/compatibility_check.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/console.php,/var/www/html/opencart/system/library/advertikon/console.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/customer.php,/var/www/html/opencart/system/library/advertikon/customer.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/db_result.php,/var/www/html/opencart/system/library/advertikon/db_result.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: mkdir(): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>212</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/exception.php,/var/www/html/opencart/system/library/advertikon/exception.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/fs.php,/var/www/html/opencart/system/library/advertikon/fs.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/image.php,/var/www/html/opencart/system/library/advertikon/image.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/interface_admin_controller.php,/var/www/html/opencart/system/library/advertikon/interface_admin_controller.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/language.php,/var/www/html/opencart/system/library/advertikon/language.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/load.php,/var/www/html/opencart/system/library/advertikon/load.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/option.php,/var/www/html/opencart/system/library/advertikon/option.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/order.php,/var/www/html/opencart/system/library/advertikon/order.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: mkdir(): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>212</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/pdf.php,/var/www/html/opencart/system/library/advertikon/pdf.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/placeholder.php,/var/www/html/opencart/system/library/advertikon/placeholder.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/profiler.php,/var/www/html/opencart/system/library/advertikon/profiler.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/query.php,/var/www/html/opencart/system/library/advertikon/query.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/renderer.php,/var/www/html/opencart/system/library/advertikon/renderer.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/resource_wrapper.php,/var/www/html/opencart/system/library/advertikon/resource_wrapper.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/setting.php,/var/www/html/opencart/system/library/advertikon/setting.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/shortcode.php,/var/www/html/opencart/system/library/advertikon/shortcode.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/store.php,/var/www/html/opencart/system/library/advertikon/store.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/table.php,/var/www/html/opencart/system/library/advertikon/table.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/tables.php,/var/www/html/opencart/system/library/advertikon/tables.php): No such file or directory in <b>/var/www/html/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/var/www/html/storage/upload/tmp-NGsRjThi9m/upload/system/library/advertikon/task.php,/var/www/html/opencart/system/library/advertikon/task.php): No such file or directory in <b>

4. See errors above
**Expected behavior**
No errors

**Screenshots / Screen recordings**
No need to record. Everything is posted above:

**Server / Test environment (please complete the following information):**
 - Deployed to a **web server for production**
 - Operating system
CentOS Linux release 8.1.1911 (Core)
 - PHP version
PHP Version 7.3.18
 - Apache version (not using apache)
nginx version: nginx/1.19.0

 - Browser(s) tested with [e.g. chrome, safari - if applicable]
any browser same errors

**Additional context**

Looking into https://github.com/opencart/opencart/blob/master/install.txt and http://docs.opencart.com/en-gb/administration/security/ there is conflicting information how to set permissions and the information is not complete.

For now I have disabled selinux after I get some proper information how to apply permissions then I will enable it again and set it properly.

Steps to apply permissions.
1.
groupadd webadmin
usermod -a -G webadmin nginx
chown -R root:webadmin /var/www/html/opencart/
chown -R root:webadmin /var/www/html/storage/

2. 
chmod -R 0755 /var/www/html/opencart/
chmod -R 0755 /var/www/html/storage/

3. 
chmod -R 0777 /var/www/html/storage/cache/
chmod -R 0777 /var/www/html/storage/download/
chmod -R 0777 /var/www/html/storage/logs/
chmod -R 0777 /var/www/html/storage/modification/
chmod -R 0777 /var/www/html/storage/session/
chmod -R 0777 /var/www/html/storage/upload/
chmod -R 0777 /var/www/html/storage/vendor/
chmod -R 0777 /var/www/html/opencart/image/
chmod -R 0777 /var/www/html/opencart/image/cache/
chmod -R 0777 /var/www/html/opencart/config.php
chmod -R 0777 /var/www/html/opencart/admin/config.php

Let me know what I am doing wrong. I want to be able to manage my admin console without any errors. Thanks for reading

**Comment by straightlight** [comment]
0777 should never be used and has nothing to do with the master branch or pre-release issues. These are server-specific issues. Therefore, this commit will now be closed.
