### ISSUE TITLE
How to make category description shown at bottom and not at the top in OpenCart3?

### ISSUE THREAD

**Issue by simeon9446** [opencart/opencart#7989]
I know that it has to do womething with category.twig which is in /catalog/view/theme/YOURTHEME/template/product/category.twig

I tried to do whatever instructions I found in OpenCart forum.  I tried to refresh Cache. I need more help. What I am doing wrong? Or maybe these instructions that I tried are wrong?

**Comment by stalker780** [comment]
This is not a support forum.

Best instruction you get here is - hire a developer.

**Comment by danielkerr** [comment]
edit the design / theme editor
