### ISSUE TITLE
3.0.2.0 beta Error with twig-loader 

### ISSUE THREAD

**Issue by ankitjn227** [opencart/opencart#7990]
Hi,

only in the frontend i became a "fatal error"-Message:

Fatal error: Uncaught Twig_Error_Loader: Unable to find template "common/column_left.twig" (looked into: /home/ambrokuf/public_html/catalog/view/theme). in /home/ambrokuf/public_html/system/library/template/Twig/Loader/Filesystem.php:215 Stack trace: #0 /home/ambrokuf/public_html/system/library/template/Twig/Loader/Filesystem.php(139): Twig_Loader_Filesystem->findTemplate('common/column_l...') #1 /home/ambrokuf/public_html/system/library/template/Twig/Environment.php(312): Twig_Loader_Filesystem->getCacheKey('common/column_l...') #2 /home/ambrokuf/public_html/system/library/template/Twig/Environment.php(378): Twig_Environment->getTemplateClass('common/column_l...', NULL) #3 /home/ambrokuf/storage_opencartnew/modification/system/library/template/twig.php(43): Twig_Environment->loadTemplate('common/column_l...') #4 /home/ambrokuf/storage_opencartnew/modification/system/library/template.php(59): Template\Twig->render('common/column_l...', '1') #5 /home/ambrokuf/storage_opencartnew/modification/system/engine/loader.php(133): in /home/ambrokuf/public_html/system/library/template/Twig/Loader/Filesystem.php on line 215

Thanks for your help!

**Comment by straightlight** [comment]
As per the error message states, it's about a missing common/column_left.twig file you seem to have. Therefore, nothing to do with the master branch or the pre-release version. This commit will now be closed.
