### ISSUE TITLE
missing icons in "Featured" parts on frontpage

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#7993]
**What version of OpenCart are you reporting this for?**
3.0.3.4-pre-core
**Describe the bug**
![oc3034-missing-icons](https://user-images.githubusercontent.com/9904364/84565648-c61ab880-ad6a-11ea-8dd7-82e7b4257cdc.png)

**Additional context**
`<i class="fas fa-shopping-cart"></i>`

thus either fas define is missing or it's a typo

**Comment by straightlight** [comment]
Correct. Also found in admin/view/template/extension/currency/ebc.twig and fixer.twig files. All three files in their locations have now been fixed.
