### ISSUE TITLE
missing getSeoUrlByKeyword()

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#7996]
referenced in 
admin/controller/catalog/information.php 
admin/controller/catalog/product.php
admin/controller/catalog/category.php
admin/controller/catalog/manufacturer.php

seems to be just a typo: need to be getSeoUrlsByKeyword instead
**What version of OpenCart are you reporting this for?**
3.0.3.4-pre-core

**Comment by straightlight** [comment]
Fixed, thanks. Will update the Opencart Forum Bug Reports official topic in a moment.
