### ISSUE TITLE
Php 7.4 error with twig

### ISSUE THREAD

**Issue by prashantchaulagain** [opencart/opencart#7997]
I upgrated my site to php 7.4 but the twig trims the space between classes causing the site to look worse. Other frameworks also encountered the issue, twig has also updated with the fix but it seems opencart uses the older version of twig. Is there any quick fix till the next update? 

<img width="756" alt="9F76AB00-4ADD-4B31-8704-459CC71BEB29" src="https://user-images.githubusercontent.com/34763628/84568710-fd0bc100-ada0-11ea-9f09-73cd938c8f69.png">
<img width="410" alt="843A9F93-7FA6-4DC1-9B35-2A9383190CE8" src="https://user-images.githubusercontent.com/34763628/84568714-009f4800-ada1-11ea-82c3-34f93b7b559a.png">

**Comment by straightlight** [comment]
OC version?

**Comment by danielkerr** [comment]
yes the twig in the vendor folder needs updating

**Comment by danielkerr** [comment]
you need to update via composer

**Comment by prashantchaulagain** [comment]
> OC version?

It's 3.0.2.0 @straightlight. 

About updating the twig in the vendor folder, I don't see any of the twig folder in vendor. It's only on system/library/template/twig and also nothing about twig in composer. Will it overwrite this one if I add new one via composer? @danielkerr .

Anyways, thanks for replying.

**Comment by straightlight** [comment]
Using the composer update will only reflect on the vendor/symfony folder; not through Opencart files directly.

**Comment by prashantchaulagain** [comment]
I am bit confused here, while I download the files directly from opencart.com and also from release here I get different composer.json while opencart-master has the different one. I previously installed opencart by downloading files not by composer. 

What can I do for now to make it work? Should I add the twig in composer and composer upgrade?

**Comment by straightlight** [comment]
This namespace is about reporting Opencart issues from the master branch or the pre-release version. Since you're looking for instructions on how to update the composer from symfony, please post on thei namespace.

**Comment by prashantchaulagain** [comment]
Ok sure @straightlight. Thank you for the information.
