### ISSUE TITLE
Prevent CKEditor from replacing spaces with &nbsp and improve store front content display

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#7999]
**What version of OpenCart are you reporting this for?**
Master branch and etc.
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

1) opencart/upload/admin/view/javascript/ckeditor/config.js
config rule `config.htmlEncodeOutput = false;` `config.entities = false;`  don't work.

2) OC Catalog
Product description and information content are displayed either improperly or not wrapped in block.

Need to update CKEditor stable version and fix oc stylesheet.css

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by prabhatkumaroc082** [comment]
not a v3.0.3.6 issue.

**Comment by danielkerr** [comment]
its behaving perfectly as it should! wasting my time!
