### ISSUE TITLE
Newly registered customers cannot log in

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#8000]
**What version of OpenCart are you reporting this for?**
3.0.3.4-core-pre
**Describe the bug**
Trying to login gives
"Warning: No match for E-Mail Address and/or Password."

After running the "Forgotten Passwort -> Reset" procedure
logging in starts working

Looks like customer registering is using a different (incompatible) encryption algorithm of type
`$2y$10$ESofz996GSzx6M2NvebmzehGFKloTqioH`

while the resetted and admin passwords look like
`8a4094d3b9662f6391215b3b38a7986a1ca7ecce`

**Comment by straightlight** [comment]
This issue has now been fixed. Thanks for reporting this. This commit will now be closed.
