### ISSUE TITLE
white page when trying to add recurring profile

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#8011]
**What version of OpenCart are you reporting this for?**
3.0.3.4-core-pre
**Describe the bug**
Leading `TAB before <?php` on line 1 gives

Warning: Cannot modify header information - headers already sent by (output started at admin/controller/catalog/recurring.php:1) in system/library/response.php on line 36

**Comment by straightlight** [comment]
Confirmed. Fixed. Thanks.
