### ISSUE TITLE
missing edit link in customer custom field list

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#8014]
**What version of OpenCart are you reporting this for?**
3.0.3.4-core-pre
**Describe the bug**
Adding
`'edit' => $this->url->link('customer/custom_field/edit', 'user_token=' . $this->session->data['user_token'] . '&custom_field_id=' . $custom_field['custom_field_id'] . $url, true)
`
to admin\controller\customer\custom_field.php
below line 218 would help

**Comment by straightlight** [comment]
Fixed . Thanks.
