### ISSUE TITLE
incorrect sent count in marketing mail success message

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#8016]
**What version of OpenCart are you reporting this for?**
3.0.3.4-core-pre
Having successfully sent 2 mails to 2 customers - I'm getting 
_Your message has been successfully sent to 0 of 2 recipients!_

Looks like computing of $start in admin\controller\marketing\contact.php line 190
needs some fixing

**Comment by straightlight** [comment]
This issue seem to be an on-going report from users. If this issue still can be reproduced on the master branch, then I'll re-open the commit.

**Comment by githubertus** [comment]
Hmm, I don't know how you would expect any difference - the master branch code is almost identical.
You simply can't use the same var acting as a record offset pointer (0, 10, 20, ...) on one hand, and a counter of actually retrieved records (sent mails) on the other.

**Comment by straightlight** [comment]
I'll re-open this commit but, at this time, this issue won't be fixed on the pre-release until a definite solution can be found for this.

**Comment by githubertus** [comment]
i think something like
```
`$sent = count($emails) + $start;
$json['success'] = sprintf($this->language->get('text_sent'), $sent, $email_total);
`
would already do
```

**Comment by straightlight** [comment]
Added to features-pre. Therefore, this commit will now be closed.
