### ISSUE TITLE
missing 'master_id' column in oc_order_product table

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#8017]
**What version of OpenCart are you reporting this for?**
3.0.3.4-core-pre
**Describe the bug**
On checkout->confirm I'm getting

`Notice: Undefined index: master_id in catalog/model/checkout/order.php on line 11
Fatal error: Uncaught Exception: Error: Unknown column 'master_id' in 'field list'<br />Error No: 1054<br />INSERT INTO oc_order_product SET order_id = '1', product_id = '43', master_id = '0', name = 'MacBook', model = 'Product 16', quantity = '1', price = '500', total = '500', tax = '0', reward = '600' `

**Comment by straightlight** [comment]
Fixed. Thanks.
