### ISSUE TITLE
bottom action popup menu of order list could need improvement

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#8022]
**What version of OpenCart are you reporting this for?**
3.0.3.4-core-pre
**Describe the bug**
what I get
![orderlistaction1](https://user-images.githubusercontent.com/9904364/85200351-f4fad680-b2f6-11ea-8734-51f9ffbe074b.png)
what I want
![orderlistaction2](https://user-images.githubusercontent.com/9904364/85200389-4014e980-b2f7-11ea-8e41-edcc8fa8152d.png)

Changing line 104 of admin/view/template/sale/order_list.twig like
`<div class="table-responsive" style="overflow-x: visible">`
would help

**Comment by straightlight** [comment]
Goes to features-pre . On the next update, we'll give it a try and if it works the work it should with these modifications, it could probably be added to the core-pre release.

**Comment by straightlight** [comment]
Rather use an ID that will pull a CSS with addClass and removeClass when clicking that button than to set manual styling. When the new bootstrap version's going to be used, less manual styling will be used. I will keep this commit opened for short time.

**Comment by straightlight** [comment]
With the pre-release bootstrap current version, I may have found a more relative solution based on what you're addressing. Please look in the admin/view/template/customer/customer_list.twig file on line 179 and line 182. Perhaps this could be more adaptable.

**Comment by straightlight** [comment]
I have now added the whole JS block to features. Once release, you'll be able to test it on the features-pre. For now, this commit will now be closed unless something else comes in on this.

**Comment by straightlight** [comment]
Ok, both packages are updated now. See the features-pre release and try the dropdown menu again.
