### ISSUE TITLE
customer_ip table layout not in line with fields used by adLogin()

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#8025]
**What version of OpenCart are you reporting this for?**
3.0.3.4-core-pre
**Describe the bug**
crashing at line 120 of catalog\model\account\customer.php
**To Reproduce**
a registered but still logged-off customer
- adds a product to the cart
- clicks 'Checkout'
- enters his creditials to the 'Returning Customer' form
- clicks 'Login'

==> error popup with 'unknown column 'store_id' ... etc.

**Comment by straightlight** [comment]
Fixed. This one goes to features later.
