### ISSUE TITLE
[Master Branch] - catalog/controller/api/customer.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#8029]
```if (!$customer_info || !$this->customer->login($customer_info['email'], '', true)) {```

true case is no longer relevant. language query should be added on that line.

**Comment by ADDCreative** [comment]
How is true no longer relevant and what does a language query have to do with that line?

**Comment by straightlight** [comment]
Look at the master branch version the way the language query are handled on the catalog-end side as opposed to the previous versions (beside features).

**Comment by ADDCreative** [comment]
I think you have put the wrong line of code in your original post.
```php
if (!$customer_info || !$this->customer->login($customer_info['email'], '', true)) {
```
Has nothing to do with any languages, it's logging the API user in as a customer.

**Comment by straightlight** [comment]
Great. My mistake. Closing this commit then.
