### ISSUE TITLE
[Master Branch] - catalog/controller/mail/order.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#8035]
This line:

```if ($email && filter_var($email, FILTER_VALIDATE_EMAIL)) {```

should be like the others:

```if (utf8_strlen($email) > 0 && filter_var($email, FILTER_VALIDATE_EMAIL)) {```

**Comment by straightlight** [comment]
In addition, this line:

```// Send to additional alert emails if new account email is enabled
			$emails = explode(',', (string)$this->config->get('config_mail_alert_email'));```

is not used with (string) everywhere (or with trim function).

**Comment by straightlight** [comment]
Found another:

```if ($email && filter_var($email, FILTER_VALIDATE_EMAIL)) {``` in the mail/review catalog controller.

**Comment by danielkerr** [comment]
it should not validate if null
