### ISSUE TITLE
Please remove GLOB_BRACE

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#8039]
https://github.com/opencart/opencart/blob/efaadf52df8bc4eba786559d12da0c6003f9b196/upload/admin/controller/marketplace/extension.php#L39

Reason: since many years this setting make big troubles!
Why: strato for example has it not.
And on some system (like solaris) also not: https://www.php.net/manual/en/function.glob.php

thx.

**Comment by qroft** [comment]
You are right and even after having not worked with OC for some time and getting back to it a few weeks ago, i could also not believe that it still exists.

On the other side: the solution already offered months ago, still works. So i am fine with it.

**Comment by mhenselin** [comment]
> You are right and even after having not worked with OC for some time and getting back to it a few weeks ago, i could also not believe that it still exists.
> 
> On the other side: the solution already offered months ago, still works. So i am fine with it.

could you please link the proposed solution here? 

I'd definitely go for removing the GLOB_BRACE.

**Comment by prabhatkumaroc082** [comment]
For systems like Solaris, please apply a solution here https://forum.opencart.com/viewtopic.php?t=165375
@danielkerr sir please suggest on it.
can we apply any of the follow?
`(defined('GLOB_BRACE') ? GLOB_BRACE : GLOB_ONLYDIR)`
or 
`(defined('GLOB_BRACE') ? GLOB_BRACE : GLOB_NOSORT)`
or 
`(defined('GLOB_BRACE') ? GLOB_BRACE : GLOB_ONLYDIR | GLOB_NOSORT)`

**Comment by danielkerr** [comment]
how to handle:

$files = glob($directory . $filter_name . '*.{jpg,jpeg,png,gif,JPG,JPEG,PNG,GIF}', GLOB_BRACE);

**Comment by danielkerr** [comment]
$allowed = [
			'ico',
			'jpg',
			'jpeg',
			'png',
			'gif',
			'JPG',
			'JPEG',
			'PNG',
			'GIF',
			'webp'
		];

		$files = glob($directory . $filter_name . '*', GLOB_NOSORT);
