### ISSUE TITLE
When uploading extension, error Class Controllermarketplaceuploader not found in ...

### ISSUE THREAD

**Issue by escapef** [opencart/opencart#8042]
<b>Error</b>: Class 'Controllermarketplaceuploader' not found in <b>D:\software\Apache\Apache24\htdocs\aofei\system\engine\action.php</b> on line <b>71</b>

**Comment by straightlight** [comment]
Which route / location were you able to produce that error message? More information is needed.

**Comment by danielkerr** [comment]
already fixed in latest branch but i have not fixed the uploader. still fixing one opr 2 things first
