### ISSUE TITLE
Empty GET request causes errors and creates duplicates with different canonical URLs

### ISSUE THREAD

**Issue by optimlab** [opencart/opencart#8043]
**Opencart 3.x.x.x**

**Empty GET request causes errors and creates duplicates with different canonical URLs**
If the URL has empty:
1. [`page=`](https://demo.opencart.com/index.php?route=product/category&path=20&page=)
2. [`limit=`](https://demo.opencart.com/index.php?route=product/category&path=20&limit=)
Duplicates with different canonical URLs:
`<link href="https://demo.opencart.com/index.php?route=product/category&amp;path=20" rel="canonical" />`
`<link href="https://demo.opencart.com/index.php?route=product/category&amp;path=20&amp;page=" rel="canonical" />` - **This url is indexed!**

**Fix Instruction**
1. Disable Display Errors.
2. Add in **robots.txt**:
```
Disallow: /*?page=$
Disallow: /*&page=$
Disallow: /*?sort=
Disallow: /*&sort=
Disallow: /*?order=
Disallow: /*&order=
Disallow: /*?limit=
Disallow: /*&limit=
Disallow: /*?filter_name=
Disallow: /*&filter_name=
Disallow: /*?filter_sub_category=
Disallow: /*&filter_sub_category=
Disallow: /*?filter_description=
Disallow: /*&filter_description=
```
**Fix in in future versions Opencart**
Search:
[`if (isset($this->request->get['page'])) {`](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/product/category.php#L30)
Replace:
`if (!empty($this->request->get['page'])) {`

etc..

**Comment by optimlab** [comment]
If you do, we will do it to the end.

```
User-agent: *
Disallow: /*route=account/
Disallow: /*route=affiliate/
Disallow: /*route=checkout/
Disallow: /*route=product/search
Disallow: /index.php?route=product/product*&manufacturer_id=
Disallow: /admin
Disallow: /catalog
Disallow: /system
Disallow: /*?page=$
Disallow: /*&page=$
Disallow: /*?sort=
Disallow: /*&sort=
Disallow: /*?order=
Disallow: /*&order=
Disallow: /*?limit=
Disallow: /*&limit=
Disallow: /*?filter_name=
Disallow: /*&filter_name=
Disallow: /*?filter_sub_category=
Disallow: /*&filter_sub_category=
Disallow: /*?filter_description=
Disallow: /*&filter_description=
Disallow: /*?tracking=
Disallow: /*&tracking=
Disallow: /*compare-products
Disallow: /*search
Disallow: /*cart
Disallow: /*checkout
Disallow: /*login
Disallow: /*logout
Disallow: /*vouchers
Disallow: /*wishlist
Disallow: /*my-account
Disallow: /*order-history
Disallow: /*newsletter
Disallow: /*return-add
Disallow: /*forgot-password
Disallow: /*downloads
Disallow: /*returns
Disallow: /*transactions
Disallow: /*create-account
Disallow: /*recurring
Disallow: /*address-book
Disallow: /*reward-points
Disallow: /*affiliate-forgot-password
Disallow: /*create-affiliate-account
Disallow: /*affiliate-login
Disallow: /*affiliates
Allow: /catalog/view/javascript/
Allow: /catalog/view/theme/*/
```

**Comment by ADDCreative** [comment]
A bit of a warning about just using a robots.txt to fix this issue. You need remember to robots.txt only controls crawling and not indexing.

From https://support.google.com/webmasters/answer/6062608?hl=en.
> **You should not use robots.txt as a means to hide your web pages from Google Search results**. This is because, if other pages point to your page with descriptive text, your page could still be indexed without visiting the page. If you want to block your page from search results, use another method such as password protection or a noindex directive.

If you are getting pages that are crawled with empty GET parameters. This could be caused by bad links on your site, so adding a robots.txt is not solving the root cause of the problem Or it could just be an undesirable bot, which will probably ignore robots.xtx anyway.
