### ISSUE TITLE
Getting Error while Search any Keyword in opencart 3.0.3.3 with Journal Theme

### ISSUE THREAD

**Issue by ankitjn227** [opencart/opencart#8044]
Getting Error while Search any Keyword in opencart 3.0.3.3 with Journal Theme

Error :- 

This page isn’t working

***.********.com is currently unable to handle this request.

HTTP ERROR 500

Need Help Urgent

Thanks in Advance.

**Comment by osworx** [comment]
Simply UNinstall that "Theme".
btw: this Theme is not supported here, you can try the forum: https://forum.opencart.com/
