### ISSUE TITLE
 Free payment does not work and it is not possible to change order status in the module within the admin

### ISSUE THREAD

**Issue by ivent** [opencart/opencart#8054]
Hello, I'm having the same problem, activate the order via free payment or the orders placed are sent to an abandoned cart and when accessing an extension and trying to change the status of the confirmed payment unsaved is always waiting for payment can resolve this is urgent.

**Comment by ivent** [comment]
Encontrei esta solução que resolve o problema, mas ainda assim é nescessário atualizar este erro   na próxima atualização: 
https://www.opencart.com/index.php?route=marketplace/extension/info&member_token=AxuDqTif4O3UQ1YKmkqTM36b43hmJ5Fa&extension_id=33967&filter_license=0

**Comment by ivent** [comment]
https://forum.opencart.com/viewtopic.php?t=192113

**Comment by ivent** [comment]
one more error: the free checkout does not appear when editing the order, the error is resolved by changing the following line

IN:
/catalog/model/extension/payment/free_checkout.php

REPLACE:
if ($status) {

WITH:
if ($status || isset($this->session->data['api_id'])) {

**Comment by ivent** [comment]
@straightlight  Hello could you help to implement this solution in the new version: 👍

**Comment by prabhatkumaroc082** [comment]
free checkout issues are fixed in https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
