### ISSUE TITLE
Error Empty custom field in Order Edit ( Solution )

### ISSUE THREAD

**Issue by ivent** [opencart/opencart#8057]
**What version of OpenCart are you reporting this for?**
3.0.3.2 and new

**Describe the bug**
When editing an order in the shipping address tab, the custom field fields are "cleared" by clicking continue

**To Reproduce**
1. Go to order edit
2. Click on continuos 
3. Scroll down to 4 tab - input-payment-method
4. See error in custom fields empty

**Expected behavior**
the fields must not be cleared but must be filled in as a previous tab of the invoice address

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system linux
 - PHP version 7
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] chrome
 - Version [e.g. 22] 3.0.3.2 or new

**Additional context**

Hello I finally discovered the error that was clearing the fields, it is a programming error in the twing code the solution is simple follows:

/admin/view/template/sale/order_form.twig

Error:
```
The shorthand condition is incorrect:([cond] ? [then] ? [else])
The correct is: ([cond] ? [then] : [else])
```

Change this code

`<input type="text" name="custom_field[{{ custom_field.custom_field_id }}]" value="{{ shipping_custom_field[custom_field.custom_field_id] ? shipping_custom_field[custom_field.custom_field_id] ? custom_field.value }}" placeholder="{{ custom_field.name }}" id="input-shipping-custom-field{{ custom_field.custom_field_id }}" class="form-control" />`

for this code:

`<input type="text" name="custom_field[{{ custom_field.custom_field_id }}]" value="{{ payment_custom_field[custom_field.custom_field_id] ? payment_custom_field[custom_field.custom_field_id] : custom_field.value }}" placeholder="{{ custom_field.name }}" id="input-payment-custom-field{{ custom_field.custom_field_id }}" class="form-control" />`

now Work fine

**Comment by eka7a** [comment]
Fixed
https://github.com/opencart/opencart/commit/f9d853201dd1b713d57bea5f60fe90ff902d7fe8
https://github.com/opencart/opencart/commit/e33355b2d722abe3cd31c076c33e3afbf3b9776d#diff-b3de2125b6ed782647536bcd5a5e2385
