### ISSUE TITLE
 There is a problem with mail returns. The code needs to be fixed as is.

### ISSUE THREAD

**Issue by talipdere** [opencart/opencart#8065]
https://github.com/opencart/opencart/blob/6b83ae0895cae5277e72bcd0121e68d303d1433c/upload/catalog/controller/account/reset.php#L19

$code =  str_replace(array("\n\r", "\n", "\r"), '',$this->request->get['code']);

**Comment by talipdere** [comment]
Especially gmail is also this problem.

**Comment by cgcmart** [comment]
`$code = str_replace(array("\n\r", "\n", "\r"), '',$this->request->get['code']);`

syntax error

**Comment by talipdere** [comment]
The code I use. How wrong it can be.
Since Gmail finds the link long, it breaks it down into 5 characters of the code.
Adding \ n \ r after 5 characters of the code, clicking the link does not open because the code went wrong. I solved this with this code, I don't know how you can solve it.
I wrote to contribute to the correction of this problem.

**Comment by cgcmart** [comment]
@talipdere 
I am sorry. You are right. It's my file editor check mistake.

**Comment by talipdere** [comment]
Ok no problem.

**Comment by cgcmart** [comment]
There is a different from phpmailer, etc.
`str_replace(array("\r\n", "\r"), "\n", $str);`
