### ISSUE TITLE
Secure Trading Web Service Extension - Duplication of checkboxes for Accepted cards

### ISSUE THREAD

**Issue by mgibson85** [opencart/opencart#8068]
Hi,

I'm seeing an issue with the duplication of checkboxes for Accepted cards for the Secure Trading Web Service extension under OC 3.0.3.3
Each time I leave and revisit the extension to made amendments, more checkboxes appear resulting in the following screenshot:

![image](https://user-images.githubusercontent.com/12297674/87298833-cb525b00-c502-11ea-8a0a-602a9fc0adae.png)

The Secure Trading Payment Pages Accepted cards displays perfectly:

![image](https://user-images.githubusercontent.com/12297674/87298845-d1e0d280-c502-11ea-83b4-be7e3f0f6216.png)

This occurs in chrome, firefox (also within inprivate/incognito sessions).

**Comment by straightlight** [comment]
This service has been removed from the Master Branch already. Therefore, this commit will now be closed.
