### ISSUE TITLE
Random Text appearing at the marketplace pages( header and comment)

### ISSUE THREAD

**Issue by prosenjeet123** [opencart/opencart#8071]
The random text is appearing in all of the pages of marketplace.
The text is appearing on the header and in the comment area section. Please check

![image](https://user-images.githubusercontent.com/12624294/87503072-e21ebc00-c680-11ea-931c-6f79f9d29b81.png)
![image](https://user-images.githubusercontent.com/12624294/87503078-e4811600-c680-11ea-9e44-de860635f40f.png)

**Comment by danielkerr** [comment]
fixed
