### ISSUE TITLE
Packages missing from vendor folder in 3.0.3.5 download

### ISSUE THREAD

**Issue by ADDCreative** [opencart/opencart#8073]
Some of the packages are missing from the vendor folder in the opencart-3.0.3.5.zip here: https://github.com/opencart/opencart/releases/tag/3.0.3.5

For example the upload/system/storage/vendor/braintree/braintree_php folder is empty.

A ```composer update``` didn't fix it. I have to remove the package folders from the vendor folder and do an install or upddate.

**Comment by danielkerr** [comment]
should be fixed now

**Comment by condor2** [comment]
Also you should remove Twig folder from system/library/template.
