### ISSUE TITLE
Server Error 500 after upgrading to 3.0.3.5

### ISSUE THREAD

**Issue by djlaserman** [opencart/opencart#8074]
OC ver 3.0.3.5

After upgrading to 3.0.3.5, I get Server Error 500. On debugging I get the following;

Fatal error: Uncaught Error: Class 'Leafo\ScssPhp\Compiler' not found in 
/admin/controller/startup/sass.php:14 Stack trace: 
#0 /storage/modification/system/engine/action.php(79): ControllerStartupSass->index() 
#1 /storage/modification/system/engine/router.php(166): Action->execute(Object(Registry)) 
#2 /storage/modification/system/engine/router.php(65): Router->execute(Object(Action)) 
#3 /system/framework.php(165): Router->dispatch(Object(Action), Object(Action)) 
#4 /system/startup.php(104): require_once('/sh...') 
#5 /admin/index.php(19): start('admin') 
#6 {main} thrown in /admin/controller/startup/sass.php on line 14

I'll try to debug this but if I fail, I'll just restore my backup

**Comment by danielkerr** [comment]
try again
i uploaded a new version

**Comment by danielkerr** [comment]
strange. i just downloaded and reinstalled and no issues
