### ISSUE TITLE
I suggest shortening the code

### ISSUE THREAD

**Issue by Grumvol** [opencart/opencart#8075]
Daniel, how do you like my proposal

For example in a file admin/controller/setting/setting.php and in files with similar code replace it

    if (isset($this->request->post['config_email'])) {
        $data['config_email'] = $this->request->post['config_email'];
    } else {
        $data['config_email'] = $this->config->get('config_email');
    }

    if (isset($this->request->post['config_telephone'])) {
        $data['config_telephone'] = $this->request->post['config_telephone'];
    } else {
        $data['config_telephone'] = $this->config->get('config_telephone');
    }

    if (isset($this->request->post['config_fax'])) {
        $data['config_fax'] = $this->request->post['config_fax'];
    } else {
        $data['config_fax'] = $this->config->get('config_fax');
    }

on this (this will shorten the code significantly)

    $fields = array(
        'config_email'     => '',
        'config_telephone' => '',
        'config_fax'       => '',
        'field_name'       => array()
    );

    foreach ($fields as $field => $default) {
        if (isset($this->request->post[$field])) {
            $data[$field] = $this->request->post[$field];
        } elseif ($this->config->has($field)) {
            $data[$field] = $this->config->get($field);
        } else {
            $data[$field] = $default;
        }
    }

**Comment by straightlight** [comment]
While this is the wrong section to post for suggestions, shortening the codes such ways will only validate with the isset function but not with other functions like empty / !empty.

**Comment by diegospm** [comment]
Yes! Too many unnecessary conditionals.

The config returns a null, so for most fields it would not be necessary to pre-define the value.

That said, the code can get even leaner:

<pre>
$fields = [
    'config_email',
    'config_telephone',
    'config_fax',
];

foreach ($fields as $field) {
	$data[$field] = $this->request->post[$field] ?? $this->config->get($field);
}
</pre>

For array values, which are normally few fields, we could validate after the loop:
<pre>
$data['field_name'] = $data['field_name'] ?? [];
</pre>

Or if the get config allowed a second argument that would be the default value, we could use it inside the loop:

<pre>
$this->config->get($field, []);
</pre>

**Comment by diegospm** [comment]
Of course, using php 7.3+

**Comment by prabhatkumaroc082** [comment]
as @straightlight said, it will not work.
