### ISSUE TITLE
Tooltip remove fixed

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#8082]
After removing the product from the cart, the tooltip doesn't disapear

----------------------------------------------------------------
![Screenshot from 2020-07-19 20-16-34](https://user-images.githubusercontent.com/48407821/87881981-3c12df00-c9fd-11ea-97b9-a421c264e688.png)

**The solution**
Edit common.js and insert the code below onto the ready function:
```
$(document).ready(function() {
...
...
...
	// Tooltip remove
	$('[data-toggle=\'tooltip\']').on('remove', function() {
		$(this).tooltip('dispose');
	});

	// Tooltip remove fixed
	$(document).on('click', '[data-toggle=\'tooltip\']', function(e) {
		$('body > .tooltip').remove();
	});

```
**Note:**
The code copied from the admin common.js file

**Comment by webkul-dilip** [comment]
This issue not found in the maintenance-branch+3.0.x.x branch, please close this issue
