### ISSUE TITLE
[3.0.3.5][3.0.3.6]admin=>extension=>modification template not found

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#8094]
i was try to install an extension, but Modification log => template not found.
below is the error message:
FILE: system/library/template/twig.php
CODE: $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);
NOT FOUND - OPERATIONS ABORTED!

please test before release a new version.
i was trying to upgrade my sites but spending the whole night doing nothing.

**Comment by chongshengdz** [comment]
.twig files are not modified.
.php files are working fine.

**Comment by danielkerr** [comment]
up

**Comment by danielkerr** [comment]
i will do another release with a fix in.

**Comment by chongshengdz** [comment]
no release with a fix in yet.
please release a revision version.

**Comment by straightlight** [comment]
@chongshengdz: Patience there. The fix has already been released as a commit. It's just a matter of time to have it built-in the core.

**Comment by straightlight** [comment]
As described here: https://github.com/opencart/opencart/issues/8103#issuecomment-662936240 .

**Comment by meshmmanuel** [comment]
Having the same issue

**Comment by voodoomg** [comment]
```
2020-12-02 7:01:26 - MOD: Modification Default

FILE: system/engine/action.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 69
...
FILE: system/library/template/twig.php
CODE: $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);
NOT FOUND - OPERATIONS ABORTED!
```

actual loader string in file:
`$loader = new \Twig\Loader\ArrayLoader(array($filename . '.twig' => $code));`

**Comment by prabhatkumaroc082** [comment]
fixes are already there for https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance. a new release will be there soon.
for now, check https://github.com/opencart/opencart/issues/8103 for a solution.
