### ISSUE TITLE
PHP Notice:  Array to string conversion from issue #7906 commit

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#8095]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
[cff51df](https://github.com/opencart/opencart/commit/cff51df735383d64ce0e7ccb46822a3768fa3518)

PHP Notice:  Array to string conversion in ../storage/cache/template/91/91b8546334deded15d9a91b6aec8b4467a040021b9a3cf67e72017658748d73f.php on line 48

impact module bestseller, latest, special, etc.

`<?php
...
/* default/template/extension/module/latest.twig */
class __TwigTemplate_3fb761e7ad01e6b4c165a49c182c6b85331764ba5f97b53a592b4fd1c7531d53 extends Template
{
.....
    }`
![productarray](https://user-images.githubusercontent.com/14033183/87986719-7f2b8b80-caab-11ea-9f9b-c361eef0c387.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
delete the cache folder

**Comment by djlaserman** [comment]
> delete the cache

I've deleted the cache but still get exactly the same errors as reported

**Comment by danielkerr** [comment]
Move the storage vendor folder

**Comment by cgcmart** [comment]
I have reverted the commit [cff51df](https://github.com/opencart/opencart/commit/cff51df735383d64ce0e7ccb46822a3768fa3518) related to module bestseller, latest, special files. These modules display as expected.

**Comment by straightlight** [comment]
@cgcmart: Have you integrated the review_status fix to test the outputs with the product/thumb? This was originally a bug before as it should now be added in the master since recently.

https://github.com/opencart/opencart/issues/8036
https://github.com/opencart/opencart/issues/8034
https://github.com/opencart/opencart/issues/8033
https://github.com/opencart/opencart/issues/8032
https://github.com/opencart/opencart/issues/8031
https://github.com/opencart/opencart/issues/8030

**Comment by cgcmart** [comment]
I posted the above issue after I installed the latest master branch and viewed live site and logs. I reverted only product array kept all commits of the review_status.

I believe the problem is here: 
Those module twigs are coded as

```
{% for product in products %}
    <div class="product-layout product-list col-lg-3 col-md-3 col-sm-6 col-12">{{ product }}</div>
{% endfor %}
```
Php array to string conversion need twig actually in **product/thums**

**Comment by straightlight** [comment]
`Php array to string conversion need twig actually in product/thums`

Should be: product/thumbs .

**Comment by straightlight** [comment]
> `Php array to string conversion need twig actually in product/thums`
> 
> Should be: product/thumb .

See this solution: https://github.com/opencart/opencart/issues/8112#issuecomment-662987231 .

**Comment by danielkerr** [comment]
CLOSING THIS AS U HAVE NOT SHOWN ANY ISSUE! JUST A PROBLEM THQAT HAPPENS TO YOU FROM A CACHE FILE.I CAN NOT REPLICATE. JUST WASTING TIME.
