### ISSUE TITLE
Unable to upgrade Open Cart 3.0.3.6 from 3.0.3.3

### ISSUE THREAD

**Issue by jameswill** [opencart/opencart#8098]
3.0.3.6

**Describe the bug**
While upgrading Open cart from 3.0.3.3 to 3.0.3.6 I am getting following error.

**Fatal error: Uncaught Error: Class 'Twig\Loader\ArrayLoader' not found in {PATH}/system/library/template/twig.php:31

Stack trace: #0 {PATH}/system/library/template.php(51): Template\Twig->render('common/header', '...')**

**To Reproduce**
1. Download the latest version
2. Update the new package onto existing package (backing up your config files)
3. Visit opencart installer
4. I am facing above said error.

**Expected behavior**
OpenCart upgrade should start on visiting installer.

**Server / Test environment (please complete the following information):**
 - PHP version **7.3**

**Comment by chongshengdz** [comment]
no database changed, upgrade is easy, just copy back 2 cofig files and third-party (custom) extensions.

**Comment by danielkerr** [comment]
ahh maybe u need to move the vendor folder from system/storage/vendor to ../storage/vendor

**Comment by condor2** [comment]
@danielkerr reupload another 3.0.3.6 zip file. In the current one is not this fix

https://github.com/opencart/opencart/commit/e0986eaddbd5d044e8b9ea5e934adafa3700b9f4

**Comment by reetp** [comment]
Happened to me using git.

Found I had to:

```
git clone
git checkout tags/3.0.3.6
mv upload/system/storage/vendor upload/system/storage/vendor.old

```
I am using PHP SCL so have to use php73 :

```
curl -sS https://getcomposer.org/installer | php73 -d allow_url_fopen=On
php73 -d allow_url_fopen=On  -f composer.phar install
```

That pulled in the correct vendor files.

Move the /upload files to your working dir.

Run install.

Once it is finished, move the contents of system/storage to opencartTmp

Carry on.

I have no idea why this works.

If you copy the temp dirs to opencartTmp first you can't run install (or upgrade)
fopen/flock/fwrite errors on system/storage/session

If you don't copy the files to the opencartTmp AFTER the upgrade you get errors from library/cache/file.php

Something odd going on.

**Comment by prabhatkumaroc082** [comment]
fixes are already there for https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance. a new release will be there soon.
