### ISSUE TITLE
Fatal Errors After Upgrading to 3.0.3.6

### ISSUE THREAD

**Issue by djlaserman** [opencart/opencart#8103]
After Upgrading to version 3.0.3.6

The 10 patches are installed successfully in steps 1/2 of the upgrade page (..../install) method of upgrading after patching everything except config.php with files from the 3.0.3.6 archive. After that step there are fatal errors as shown below.

Trying to access the main store page:
Fatal error: Uncaught Error: Class 'Twig\Loader\ArrayLoader' not found in /host/shop.teknerds.co.za/system/library/template/twig.php:31 Stack trace: 
#0 /host/shop.teknerds.co.za/system/library/template.php(51): Template\Twig->render('journal3/templa...', '{% if modules %...') 
#1 /host/shop.teknerds.co.za/system/engine/loader.php(125): Template->render('journal3/templa...', '') 
#2 /host/shop.teknerds.co.za/catalog/controller/common/column_left.php(72): Loader->view('common/column_l...', Array) 
#3 /host/storage/modification/system/engine/action.php(80): ControllerCommonColumnLeft->index(Array) 
#4 /host/shop.teknerds.co.za/system/engine/loader.php(48): Action->execute(Object(Registry), Array) 
#5 /host/shop.teknerds.co.za/catalog/controller/common/home.php(12): Loader->controller('common/column_l...') 
#6 /host/storage/modification/system/engine/action.php(80): ControllerCommonHome->index() 
#7 /host/shop.teknerds.co.za/catalog/controller/startup/router.php(25): Act in /host/shop.teknerds.co.za/system/library/template/twig.php on line 31

Trying to access /admin page:
Fatal error: Uncaught Error: Class 'ScssPhp\ScssPhp\Compiler' not found in /host/shop.teknerds.co.za/admin/controller/startup/sass.php:14 Stack trace: 
#0 /host/storage/modification/system/engine/action.php(80): ControllerStartupSass->index() 
#1 /host/shop.teknerds.co.za/system/engine/router.php(67): Action->execute(Object(Registry)) 
#2 /host/shop.teknerds.co.za/system/engine/router.php(46): Router->execute(Object(Action)) 
#3 /host/shop.teknerds.co.za/system/framework.php(165): Router->dispatch(Object(Action), Object(Action)) 
#4 /host/shop.teknerds.co.za/system/startup.php(104): require_once('/host/sh...') 
#5 /host/shop.teknerds.co.za/admin/index.php(19): start('admin') #6 {main} thrown in /host/shop.teknerds.co.za/admin/controller/startup/sass.php on line 14

**Comment by optimlab** [comment]
journal3?
What does the developer of this template say?

**Comment by djlaserman** [comment]
> journal3?
> What does the developer of this template say?

I will write to the Journal 3 developers, but as far as I can see, I think OC changed default locations of where templates are usually located, thus nothing which pointed there before would work unless modified to point to the correct locations of the needed classes

**Comment by djlaserman** [comment]
> journal3?
> What does the developer of this template say?

I don't know if @optimlab is pissed off (from the thumbs down) by my reporting a bug I'm getting as advised by the install instructions, or if it has to do with that the recent changes in OC may need the much hated Journal 3 developers to also update their code in line with the OC updates for their theme to work properly, or maybe by something else

**Comment by optimlab** [comment]
> I don't know if @optimlab is pissed off (from the thumbs down) by my reporting

https://github.com/opencart/opencart/issues/8044#issuecomment-650563705

**Comment by djlaserman** [comment]
I will report back what the Journal 3 developers have said when I get the feedback

![image](https://user-images.githubusercontent.com/41134053/88089892-13215400-cb8d-11ea-8ecf-ebc7662cf139.png)

**Comment by danielkerr** [comment]
login to ur site and delete all the cache files under system/cache

**Comment by danielkerr** [comment]
ahh maybe u need to move the vendor folder from system/storage/vendor to ../storage/vendor

**Comment by djlaserman** [comment]
> login to ur site and delete all the cache files under system/cache

I deleted the cache but still get the same errors. I'll try moving the files, that should fix it. I'll let you know how that went

**Comment by djlaserman** [comment]
> ahh maybe u need to move the vendor folder from system/storage/vendor to ../../storage/vendor

I've moved the vendor folder, but there's no change, still getting exactly the same errors

**Comment by djlaserman** [comment]
where exactly should the vendor folder be? when (revision) was its location changed in code?

**Comment by djlaserman** [comment]
even under storage, there seems to be reference to a cache folder, but in my case I only see two places where this cache folder is; that is in /system/storage/cache (inside the main installation folder) and storage/cache (outside the main installation). I've emptied these two with no changes in the errors I'm getting. I suspect some mangled global system variables either misplaced in code or referencing deprecated locations

**Comment by condor2** [comment]
You talk about 3.0.3.6 but in the screenshot is about 3.0..3.5. So what version exactly is?

**Comment by condor2** [comment]
@djlaserman apply this fix and try again.
https://github.com/opencart/opencart/commit/e0986eaddbd5d044e8b9ea5e934adafa3700b9f4

Because isn't included in the 3.0.3.6 zip file from github.

**Comment by danielkerr** [comment]
I updated twig to the latest version. U need to move the vendor folder with the latest files to the outside directory storage/vendor

**Comment by djlaserman** [comment]
> You talk about 3.0.3.6 but in the screenshot is about 3.0.3.5. So what version exactly is?

I started by upgrading to version 3.0.3.5 up from 3.0.3.2, and after I got these exact same errors and posting them on github, there was a quick revision to 3.0.3.6, which I got an email from Daniel Kerr to try the new update. So I overwrote all my files apart from the config.php with the most recent archive files from version 3.0.3.6, which also churn out the exact same errors as the previous build. Therefore in my request for support from the Journal developers I  mentioned that I tried both builds as above

**Comment by condor2** [comment]
@djlaserman  apply this fix...
https://github.com/opencart/opencart/commit/e0986eaddbd5d044e8b9ea5e934adafa3700b9f4

@danielkerr upload a new 3.0.3.6 revision on release to include ocmod modification fix.

**Comment by djlaserman** [comment]
> I updated twig to the latest version. U need to move the vendor folder with the latest files to the outside directory storage/vendor

I copied the vendor folder from the 3.0.3.6 zip and overwrote the 'external folder' storage/vendor. After that some of the errors were happy but there was still an error that showed missing files in the folder admin/view/theme (**there was no such folder in my installation**), so I created the folder and pasted the common folder (that the error referenced), after which one error was happy but more of the templates were still being 'not found'.

So I deleted that **admin/view/theme/common** folder and **copied all folders from the templates folder in the zip onto the admin/view/theme folder**. After that I'm able to access the admin folder and the shop is working fine. So I'm not sure if this means that the Journal theme has to update their references to these template files or there is something wrong with the system/library/template/twig.php file or how it goes about looking for these templates.

Below are the host of errors I got as I moved files around to get to a working point: 
Fatal error: Uncaught Exception: Error: Could not load template /host/shop.teknerds.co.za/admin/view/theme/common/header.twig! in /host/shop.teknerds.co.za/system/library/template/twig.php:17 Stack trace: 
#0 /host/shop.teknerds.co.za/system/library/template.php(51): Template\Twig->render('common/header', '') 
#1 /host/shop.teknerds.co.za/system/engine/loader.php(125): Template->render('common/header', '') 
#2 /host/shop.teknerds.co.za/admin/controller/common/header.php(79): Loader->view('common/header', Array) 
#3 /host/shop.teknerds.co.za/system/engine/action.php(79): ControllerCommonHeader->index(Array) 
#4 /host/shop.teknerds.co.za/system/engine/loader.php(48): Action->execute(Object(Registry), Array) 
#5 /host/shop.teknerds.co.za/admin/controller/common/login.php(79): Loader->controller('common/header') 
#6 /host/shop.teknerds.co.za/system/engine/action.php(79): ControllerCommonLogin->index() 
#7 /host/shop.teknerds.co.za/system/engine/router.php(67): Acti in /host/shop.teknerds.co.za/system/library/template/twig.php on line 17

Fatal error: Uncaught Exception: Error: Could not load template /host/shop.teknerds.co.za/admin/view/theme/common/header.twig! in /host/shop.teknerds.co.za/system/library/template/twig.php:17 Stack trace: 
#0 /host/shop.teknerds.co.za/system/library/template.php(51): Template\Twig->render('common/header', '') 
#1 /host/shop.teknerds.co.za/system/engine/loader.php(125): Template->render('common/header', '') 
#2 /host/shop.teknerds.co.za/admin/controller/common/header.php(79): Loader->view('common/header', Array) 
#3 /host/shop.teknerds.co.za/system/engine/action.php(79): ControllerCommonHeader->index(Array) 
#4 /host/shop.teknerds.co.za/system/engine/loader.php(48): Action->execute(Object(Registry), Array) 
#5 /host/shop.teknerds.co.za/admin/controller/common/login.php(79): Loader->controller('common/header') 
#6 /host/shop.teknerds.co.za/system/engine/action.php(79): ControllerCommonLogin->index() 
#7 /host/shop.teknerds.co.za/system/engine/router.php(67): Acti in /host/shop.teknerds.co.za/system/library/template/twig.php on line 17

Fatal error: Uncaught Exception: Error: Could not load template /host/shop.teknerds.co.za/admin/view/theme/extension/dashboard/activity_info.twig! in /host/shop.teknerds.co.za/system/library/template/twig.php:17 Stack trace: 
#0 /host/shop.teknerds.co.za/system/library/template.php(51): Template\Twig->render('extension/dashb...', '') 
#1 /host/shop.teknerds.co.za/system/engine/loader.php(125): Template->render('extension/dashb...', '') 
#2 /host/shop.teknerds.co.za/admin/controller/extension/dashboard/activity.php(118): Loader->view('extension/dashb...', Array) 
#3 /host/shop.teknerds.co.za/system/engine/action.php(79): ControllerExtensionDashboardActivity->dashboard(Array) 
#4 /host/shop.teknerds.co.za/system/engine/loader.php(48): Action->execute(Object(Registry), Array) 
#5 /host/shop.teknerds.co.za/admin/controller/common/dashboard.php(40): Loader->controller('extension/dashb...') 
#6 /host/shop.teknerds.co.za/system/engine/action.php(79): ControllerCommonDashboa in /host/shop.teknerds.co.za/system/library/template/twig.php on line 17

**Comment by djlaserman** [comment]
> @djlaserman apply this fix and try again.
> [e0986ea](https://github.com/opencart/opencart/commit/e0986eaddbd5d044e8b9ea5e934adafa3700b9f4)
> 
> Because isn't included in the 3.0.3.6 zip file from github.

I applied this fix but still can't get the theme to find all its dependent *.twig files. The files are all there but I get the 'failed to load'... error. Only the admin panel is accessible. I couldn't revert to the default theme either; I get a missing theme error, but the default theme files are all there. Tried deleting cache, refreshing and resetting mods, but can't seem to overcome it. I'll wait for the theme dev's response before reverting to my 3.0.3.2 backup. I think it's the only latest and fully working release.

**Comment by condor2** [comment]
This fix should work
https://github.com/opencart/opencart/pull/7153#issuecomment-500143157

**Comment by straightlight** [comment]
Separate issue since what you're addressing about is a not defined statement originating from Journal which we don't support.

**Comment by djlaserman** [comment]
> Separate issue since what you're addressing about is a not defined statement originating from Journal which we don't support.

Whether or not you support Journal isn't the issue here. The issue is that there are problems upgrading from 3.0.3.2 to either 3.0.3.5 or 3.0.3.6, there's no need to hide behind Journal, we all know that OpenCart has a lot of unsolved bugs and needs a lot of work to iron out the issues. So if you discourage 'testers' to report issues, how in Jesus Christ's name will any of the issues come to light?!

**Comment by straightlight** [comment]
`how in Jesus Christ's name will any of the issues come to light?!`

Simple. Try to test with a fresh version of the v3.0.3.6 release and see if you are able to reproduce the issue with the not defined statement error message from the products page you originally tested in the first place.

**Comment by djlaserman** [comment]
> `how in Jesus Christ's name will any of the issues come to light?!`
> 
> Simple. Try to test with a fresh version of the v3.0.3.6 release and see if you are able to reproduce the issue with the not defined statement error message from the products page you originally tested in the first place.

I have a better idea. I'll let you do the testing and reporting of bugs. Meanwhile, I'll restore my 3.0.3.2 backup and we'll all be happy, my shop would run smoothly and no one will bother the contributors with error messages that involve the string 'Journal'

**Comment by djlaserman** [comment]
> Separate issue since what you're addressing about is a not defined statement originating from Journal which we don't support.

Here are errors from a brand new live installation of OC 3.0.3.6. There is no third party skin used, just the plain installation. This proves that my post above isn't about Journal but the issues that still need to be worked on in OC. Look at how the template.php and twig.php are propping up in the logs... 

2020-07-23 0:34:47 - MOD: Modification Default

FILE: system/engine/action.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 69

FILE: system/engine/loader.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 77
LINE: 151
LINE: 168

FILE: system/library/config.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 59

FILE: system/library/language.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 67
LINE: 73

FILE: system/library/template/template.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 18

FILE: system/library/template/twig.php
CODE: $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);
NOT FOUND - OPERATIONS ABORTED!

**Comment by straightlight** [comment]
Yes, this one has already been reported this week. It is an issue with the system/modification.xml file. Daniel is already aware of it.

**Comment by djlaserman** [comment]
> Yes, this one has already been reported this week. It is an issue with the system/modification.xml file. Daniel is already aware of it.

Ok, is it by any chance what @condor2 refers to in the preceding dialogue, as the 'fix' that hasn't been integrated with the files in the zip archive of OC ver. 3.0.3.6?
 
https://github.com/opencart/opencart/commit/e0986eaddbd5d044e8b9ea5e934adafa3700b9f4

**Comment by danielkerr** [comment]
There are pull requests with the fix already for the Sundance branch. I just need to do another release

**Comment by andyplak** [comment]
Similar to @djlaserman I went through a whole world of pain with this same issue. Thanks to this thread I was able to resolve it and will summarise the steps I took in case anyone else stumbles across these issues (which I believe will affect anyone upgrading from 3.0.3.2 to 3.0.3.6 and is running the unsupported Journal theme or any theme that uses twig include function). 

Steps I took:

1. Copy (not replace) system/storage/vendor to the outside of webroot storage/vendor folder (by copying, scss.inc.php was not lost)
2. Update modification.xml to work with twig files as per https://github.com/opencart/opencart/commit/e0986eaddbd5d044e8b9ea5e934adafa3700b9f4
3. Delete the system/library/template/twig folder, left over from 3.0.3.2
4. Apply patch from @MikhailShemelin which allows twig includes https://github.com/MikhailShemelin/opencart/commit/bd20109d9501cfcfbf7cf4d1fefdff925b342cc2
5. Clear modification cache

**Comment by danielkerr** [comment]
this is not master branch related. will get maintenance team to have a look.

**Comment by prabhatkumaroc082** [comment]
I tried to upgrade from 3.0.3.2 to 3.0.3.6 with a fresh installation from the release page https://www.opencart.com/index.php?route=cms/download/history but not faced any issue.

as per the comments, it might be the storage directory issue so if your storage directory path for 3.0.3.2 is ../../storage/ then move 3.0.3.6 system/storage/vendor to 3.0.3.2 ./../storage/vendor and try clear cache directory also ./../storage/cache

also, all mentioned changes are in the maintenance branch https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance so soon a new version will be there.

**Comment by WhereJuly** [comment]
As @djlaserman [above](https://github.com/opencart/opencart/issues/8103#issuecomment-662766786) I use an official v.3.0.3.6 installation via zip download from OC website.

I have the same error as soon as I install the following modifications: 

- [Admin Language toggle - Quick change Admin language](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=39181&filter_search=admin%20language%20toggle);
- [[OCN] Menu Switch](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=40077&filter_search=[OCN]%20Menu%20Switch);

[Here](https://gist.github.com/WhereJuly/ba5cc48f2e8136e38e179f3a544bad02) is the error log from `Extensions->Modifications->Log` after I clear modifications cache with `Refresh` button. It clearly says:

```
2021-01-16 13:57:24 - MOD: Modification Default
// ... some more reporting here 
FILE: system/library/template/twig.php
CODE: $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);
NOT FOUND - OPERATIONS ABORTED!
```

I managed to fix the issue thanks to @andyplak comment [above](https://github.com/opencart/opencart/issues/8103#issuecomment-748785585) with regard to the fact that I use clean official v3.0.3.6, not upgrade from past versions.

I manually updated 2 files: 

- [/upload/system/modification.xml](https://github.com/opencart/opencart/blob/e0986eaddbd5d044e8b9ea5e934adafa3700b9f4/upload/system/modification.xml);
- [/upload/system/library/template/twig.php](https://github.com/MikhailShemelin/opencart/blob/bd20109d9501cfcfbf7cf4d1fefdff925b342cc2/upload/system/library/template/twig.php);

Hope that helps someone. 

This is strange how official v3.0.3.5 zip does not include these fixes despite the fact that the maintenance branch has at least the first one merged since July 2020.

Hopefully these fixes would find their way to the official zip version.

**Comment by optimlab** [comment]
> but not faced any issue

I'm shocked! It's terrible to see an incompetent person in moderators.

**Comment by mhcwebdesign** [comment]
OC 3.0.3.5 and 3.0.3.6 should not be used on live servers because of the known bugs.

While there is a 3.0.x maintenance branch, judging by the many daily commits, which has been ongoing for the past few months, it almost certainly is not just a 3.0.3.6 release with bugfixes, but it will include other changes, too. 

We still need a bugfix releases based on 3.0.3.6.

**Comment by MikhailShemelin** [comment]
> We still need a bugfix release based on 3.0.3.6.

Definetely. 

Almost every day I help somebody to fix their opencart 3.0.3.6 by uploading the mentinoned files

> * [/upload/system/modification.xml](https://github.com/opencart/opencart/blob/e0986eaddbd5d044e8b9ea5e934adafa3700b9f4/upload/system/modification.xml);
> * [/upload/system/library/template/twig.php](https://github.com/MikhailShemelin/opencart/blob/bd20109d9501cfcfbf7cf4d1fefdff925b342cc2/upload/system/library/template/twig.php);

**Comment by optimlab** [comment]
> [/upload/system/library/template/twig.php](https://github.com/MikhailShemelin/opencart/blob/bd20109d9501cfcfbf7cf4d1fefdff925b342cc2/upload/system/library/template/twig.php);


Why change this file? You can just get by with: 
>  [/upload/system/modification.xml](https://github.com/opencart/opencart/blob/e0986eaddbd5d044e8b9ea5e934adafa3700b9f4/upload/system/modification.xml);

**Comment by MikhailShemelin** [comment]
> > [/upload/system/library/template/twig.php](https://github.com/MikhailShemelin/opencart/blob/bd20109d9501cfcfbf7cf4d1fefdff925b342cc2/upload/system/library/template/twig.php);
> 
> Why change this file?

it returns back the possiblity to use the twig tag 'include' https://twig.symfony.com/doc/2.x/tags/include.html

**Comment by optimlab** [comment]
> it returns back the possiblity to use the twig tag 'include'

Do you want newbies to write shit-code in templates? I am also against this tag. 
Вы его сами хоть раз использовали?

**Comment by MikhailShemelin** [comment]
> Do you want newbies to write shit-code in templates?

I have no idea why you consider using 'unclude' as shit-coding. Do you have a reasonable explanation?
What is a sense to integrate a template engine, but do not use it for its intended purpose (by disabling one of its basic features)?

> Вы его сами хоть раз использовали? (Have you used it yourself?)

Of course, many times. As well as many other developers, especially theme developers. 
In fact, 'include' is an useful function for code reuse. It helps to minimize code duplication and to hide complexity.

**Comment by mhcwebdesign** [comment]
While it's easy enough to add support for include I have to agree with **optimlab** that there is a danger of poor-quality theme designers misusing this feature.

Twig itself, especially the way Symfony has implemented it, is a poorly designed template engine. It has no proper LALR(1) parsable syntax, it uses strange operator keywords like 'b-or', 'b-and' , 'b-xor' instead of the usual '|', '&','^'. Some tags are simply obsolete because of equivalent functions. It silently ignores missing variables by default. It does not directly render, but translates templates into a cached PHP code, which in turn renders, this is bad way to go about things. It has a somewhat confusing extension mechanism which is not quite the same as a proper object-oriented class extension.

OpenCart should allow for PHP templates.

**Comment by MikhailShemelin** [comment]
> there is a danger of poor-quality theme designers misusing this feature.

What kind of twig-include misusing do you mean?

> OpenCart should allow for PHP templates again.

You vote against twig-iclude, but at the same time votes for PHP templates, which allows to include not only other templates, but anything (any custom code, class, library, model, etc.). Before integrating twig, I met a lot of such 'solutions' by 'poor-quality theme designers' in opencart (and I can't say I miss them).

**Comment by mhcwebdesign** [comment]
I am not against the include feature, just the misuse of it by poor-quality web themes. Twig in general is a poorly designed template engine. Personally I don't see a compelling reason for using the include feature. Maybe extensions and blocks.

**Comment by MikhailShemelin** [comment]
> I am not against the include feature, just the misuse of it by poor-quality web themes. 

Do you know a way to misuse it?

> Personally I don't see a compelling reason for using the include feature. Maybe extensions and blocks.

For example, to use 
```
{% include 'common/breadcrumbs.twig' %}
```

instead of duplicating something like this in every template
```
      <ul class="breadcrumb">
        {% for breadcrumb in breadcrumbs %}
          <li><a href="{{ breadcrumb.href }}">{{ breadcrumb.text }}</a></li>
        {% endfor %}
      </ul>
```


Or rendering product thumbs in product lists (category, manufacturer, search, specials, etc.) using
```
{% include 'product/thumb.twig' %}`
```

instead of duplicating entire product thumb code in every of the related templates (like it is in opencart 3.x) 
or instead of pre-rendering product thumbs in every related controller (like it is in opencart 4.x-dev)

**Comment by mhcwebdesign** [comment]
Fair enough, though your examples would clash with many extensions trying to modify the breadcrumb and thumb in the category.twig, manufacturer.twig, specials.twig etc via view events. It would be better to have separate Controllers and Templates for breadcrumbs or thumbs in the core OpenCart.

**Comment by MikhailShemelin** [comment]
> Do you know a way to misuse it?

@mhcwebdesign You did not answer, does it mean that you do not know any? 

> Fair enough, though your examples would clash with many extensions trying to modify the breadcrumb and thumb in the category.twig, manufacturer.twig, specials.twig etc via view events

Originally, we have been talking about the fact what twig-include was working in opencart 3.0.3.3 and previous versions, but it is disabled in 3.0.3.6. This change already clashes with many existing extensions and themes and returning twig-include back breaks nothing (only repairs). Thus returning twig-include back in a kind of 3.0.3.6-fix or 3.0.3.7 is must have.

And if we are talking about future development of opencart, any significant changes will clash with some of previously developed extensions. So we have to be more focused on better future user and developer experience (more on next generations of extensions, than on previously developed). 

> It would be better to have separate Controllers and Templates for breadcrumbs or thumbs in the core OpenCart.

But what benefits do you see in this approach? 

For me pre-rendering template parts in controllers and further gluing them togeter, when this functionality is fully covered by used template engine looks quite strange (if not contradicting MVC pattern). 

It would be not just an additional code to the opencart core (more to develop, more to mantain, etc.), but also making theme developing more complicated (for example: a need to have another type of 'thumb' in featured/latest/... module? - you can't just put `{% include 'product/thumb_module.twig' %}` in appropriate templates, you have to alternate controller calls).

**Comment by mhcwebdesign** [comment]
You really seem to be quite desperate in your quest for using Twig. While includes may have some usages, they are not used in the OpenCart core, and I have only seen a couple of poorly written payment extensions using the include-tag, but not repeatedly, so your case of re-using the same sub-template didn't apply there. 

Twig itself is a poorly designed template engine as explained before.

If we want to have a **{% include 'common.breadcrumbs.twig' %}** than this should be part of the OpenCart core, not of other web themes when the core doesn't use it.  In fact, the default OpenCart web theme needs a better design. The last thing we need is another Journal3 disaster.

**Comment by MikhailShemelin** [comment]
> You really seem to be quite desperate in your quest for using Twig.

I do not care about using Twig. But since it is in use, I see no reason to avoid using its basic functionality (and it is a basic feature of probably all existing template engines). 

However, I do care about functionality broken in opencart 3.0.3.6. 
As I wrote above, I help users, who downloaded and installed opencart 3.0.3.6, by uploading fixed modification.xml and twig.php very often. 

> While includes may have some usages, they are not used in the OpenCart core

Yes, and the OpenCart core contains a lot of code duplications in its templates. I consider it as an imperfection, but not as a gold standard everybody should be always following to.

> I have only seen a couple of poorly written payment extensions using the include-tag

If you have not seen many extensions using include-tag, it is just a personal experience and it cannot by a reason to do not use or disable include-tab. 
Personally, I saw many themes and extensions using include-tag and we also use it in our extensions.
Even if you consider these and other examples as poorly written, it is still not an argument against the include-tag itself. 

> Twig itself is a poorly designed template engine as explained before.

As also explained before it is not are reason to do not use its basic features. 

> If we want to have a **{% include 'common.breadcrumbs.twig' %}** than this should be part of the OpenCart core, not of other web themes when the core doesn't use it.

The fact that **{% include 'common.breadcrumbs.twig' %}** is not used in the OpenCart default theme, is not a reason to do not use it in other themes.

**Comment by mhcwebdesign** [comment]
Well, it looks like Daniel just released a OC 3.0.3.7, but it still doesn't have support for the twig's include-tag. It's a shame, it would have been so easy to add Twig's Twig_Loader_Chain with both Twig_Loader_Array and Twig_Loader_Filesystem, I suggested it ages ago here: https://github.com/opencart/opencart/pull/7153#issuecomment-500143157

I'll update our Template Switcher and Override Engine OC-extensions to make sure it has it in there.

**Comment by MikhailShemelin** [comment]
> Well, it looks like Daniel just released a OC 3.0.3.7, but it still doesn't have support for Twig's include-tag. It's a shame, it would have been so easy to use Twig's Twig_Loader_Chain with both Twig_Loader_Array and Twig_Loader_Filesystem, I suggested it ages ago here: [#7153 (comment)](https://github.com/opencart/opencart/pull/7153#issuecomment-500143157)

Sad. Long live clashes of different OCMods adding include-tag back :o)

**Comment by armandomiani** [comment]
What's the latest stable release? I'm deploying 3.0.3.7 and no hint in this issue solves the problem. -_-

**Comment by zomgdev** [comment]
Hi ppl!
I just upgraded to 3.0.3.7 and get same error. In my case i copied upload/system/storage/vendor dir according to my DIR_STORAGE variable. And everything worked now.

My example.
config.php consists string:
define('DIR_STORAGE', '/var/www/oc1-storage/');

i've copied upload/system/storage/vendor to the /var/www/oc1-storage/

Regards,
Mikhail.
