### ISSUE TITLE
website, broken link

### ISSUE THREAD

**Issue by mh-cbon** [opencart/opencart#8109]
**What version of OpenCart are you reporting this for?**
none

**Describe the bug**
at http://docs.opencart.com/en-gb/developer/module/
link to http://opencart.hostjars.com/creating-opencart-modules does not work
in text "The easiest way to create a module is to download the DIY Module Builder skeleton from HostJars."

**To Reproduce**
open http://docs.opencart.com/en-gb/developer/module/
click aforementioned link to http://opencart.hostjars.com/creating-opencart-modules 

**Expected behavior**
link works

**Screenshots / Screen recordings**
--

**Server / Test environment (please complete the following information):**
--

**Additional context**
maybe it is not the right place. Sorry for that, hope you can redirect appropriately.

**Comment by condor2** [comment]
hostjars.com is "dead". Documentation should be update and link removed.

**Comment by eka7a** [comment]
Here you can send a pull request for fix.
https://github.com/opencart/opencart.github.io/blob/master/docs/developer/module.html

**Comment by danielkerr** [comment]
this is a repeat issue. i'm closing it. i am paying a company to update the documentation. should be done in the next month or 2.

**Comment by NucleaPeon** [comment]
It's 2023 and there's still a broken hostjars link.

https://opencart.hostjars.com/ via https://docs.opencart.com/en-gb/developer/loading/ (very bottom of page)

**Comment by qcol** [comment]
2024 :)

**Comment by osworx** [comment]
> It's 2023 and there's still a broken hostjars link.
> 
> https://opencart.hostjars.com/ via https://docs.opencart.com/en-gb/developer/loading/ (very bottom of page)

Does no matter if that site exists - or not.
Was only paid modules: 
https://web.archive.org/web/20180521000958/http://opencart.hostjars.com/creating-opencart-modules
https://web.archive.org/web/20180528183624/http://opencart.hostjars.com/auto-module-creator

So, why nned someone to buy a 'skeleton' when he has it already - with OpenCart itself?
For a developer (and noobs should not build new extensions/modules), that (and the existing documentations around) should be a very easy task to understand how to build a new one.

So better stop paying a company which does not exist anymore (@danielkerr) and stop wining here around (all other visitors here).
