### ISSUE TITLE
[Master Branch] - Catalog List/Grid View

### ISSUE THREAD

**Issue by engwalid1971** [opencart/opencart#8112]
### Issue (1/3)
- Choose any category like "Phones & PDAs".
- Click the List button.
- Choose another category like "Cameras".
- You will see the grid view instead of List View
![Screenshot from 2020-07-22 22-01-23](https://user-images.githubusercontent.com/48407821/88222965-10932d00-cc67-11ea-9fa6-6eca24029fb9.png)

### Issue (2/3)
- Add a module to the Column Left or Column Right
![Screenshot from 2020-07-22 22-12-48](https://user-images.githubusercontent.com/48407821/88226229-09bae900-cc6c-11ea-9ecb-e0dee70b9335.png)

### Issue (3/3)
- Edit the layout of any page not have a list and grid buttons, like ( Home ).
- Add a module to the Column Left.
- Add a module to the Content Top.
![Screenshot from 2020-07-22 22-29-55](https://user-images.githubusercontent.com/48407821/88225844-78e40d80-cc6b-11ea-936f-ae7b53ac0e7a.png)

**Comment by straightlight** [comment]
Is this for the master branch?

**Comment by engwalid1971** [comment]
@straightlight
Yes this for the master branch...

**Comment by cgcmart** [comment]
Another issue:
product/special is able to display only 2 specials.
On db `oc_product_special` there are 3 specials in total.

**Comment by eka7a** [comment]
@engwalid1971 @straightlight please check again new pull.

@cgcmart Check special date end and customer groups.

**Comment by engwalid1971** [comment]
> Another issue:
> product/special is able to display only 2 specials.
> On db `oc_product_special` there are 3 specials in total.

@cgcmart
```
INSERT INTO `oc_product_special` (`product_special_id`, `product_id`, `customer_group_id`, `priority`, `price`, `date_start`, `date_end`) VALUES
(419, 42, 1, 1, '90.0000', '0000-00-00', '0000-00-00'),
(439, 30, 1, 2, '90.0000', '0000-00-00', '0000-00-00'),
(438, 30, 1, 1, '80.0000', '0000-00-00', '0000-00-00');
```
There are 2 specials only because the product_id = 30 is duplicated.

**Comment by straightlight** [comment]
@eka7a: Has your referred commit also been tested with custom CSS since it is also suggesting to modify the col dimensions from the TWIG files?

**Comment by cgcmart** [comment]
@engwalid1971 
I have a live site, about 20 specials, which are displayed through module, but product/special displays only 2 specials.

**Comment by straightlight** [comment]
@cgcmart: If you try the modifications above from this commit: https://github.com/opencart/opencart/commit/ceda52128266d0b7e9bff6f79c6c9b73523f238e , does it fix the issue whether you use the default stylesheet or custom CSS?

**Comment by engwalid1971** [comment]
@cgcmart
The product/special displays all the specials.
![Screenshot from 2020-07-23 14-58-13](https://user-images.githubusercontent.com/48407821/88289200-2c451480-ccf5-11ea-9064-f24889272b8f.png)

**Comment by straightlight** [comment]
@cgcmart: Including custom CSS?

**Comment by engwalid1971** [comment]
@eka7a
![Screenshot from 2020-07-23 14-45-46](https://user-images.githubusercontent.com/48407821/88289768-08ce9980-ccf6-11ea-8b41-b7c42ef0a1cd.png)

**Comment by straightlight** [comment]
That looks only from the default stylesheet.

**Comment by straightlight** [comment]
Just fixing the SQL query should suffice.

**Comment by engwalid1971** [comment]
### Issue 4
Adding a Slideshow or Carousel to the category page( or any page has a column Left / right module ) 

![Screenshot from 2020-07-23 15-32-08](https://user-images.githubusercontent.com/48407821/88292334-ceff9200-ccf9-11ea-831c-40c3cd4dc513.png)

**Comment by straightlight** [comment]
Damn ... that's bad.

**Comment by cgcmart** [comment]
> 
> 
> @engwalid1971 @straightlight please check again new commit.
> 
> @cgcmart Check special date end and customer groups.

I did merger your patch. product/special still displays only 2 specials.

**Comment by straightlight** [comment]
@eka7a: Does that resolves the Carousel and Slideshow issue?

**Comment by eka7a** [comment]
> @eka7a: Has your referred commit also been tested with custom CSS since it is also suggesting to modify the col dimensions from the TWIG files?

There is no need to test with custom CSS. People using custom CSS will already make customizations according. It works with Grid/List button same.

> @eka7a: Does that resolves the Carousel and Slideshow issue?

Yes.

> I did merger your patch. product/special still displays only 2 specials.

If there are customizations you use, check them by disabling them. I can't see a problem.

**Comment by straightlight** [comment]
@eka7a: Making customization accordingly with custom CSS without the need to modify TWIG files must not involve modifications to the col attributes from the TWIG files. Otherwise, these custom CSS would have to adapt to your changes when using the default theme.

**Comment by cgcmart** [comment]
The issue is product/special page displaying only 2 items.

**Comment by cgcmart** [comment]
> 
> 
> @cgcmart
> The product/special displays all the specials.
> ![Screenshot from 2020-07-23 14-58-13](https://user-images.githubusercontent.com/48407821/88289200-2c451480-ccf5-11ea-9064-f24889272b8f.png)

@engwalid1971 Which oc version?

> 
> 
> @cgcmart
> 
> ```
> INSERT INTO `oc_product_special` (`product_special_id`, `product_id`, `customer_group_id`, `priority`, `price`, `date_start`, `date_end`) VALUES
> (419, 42, 1, 1, '90.0000', '0000-00-00', '0000-00-00'),
> (439, 30, 1, 2, '90.0000', '0000-00-00', '0000-00-00'),
> (438, 30, 1, 1, '80.0000', '0000-00-00', '0000-00-00');
> ```
> 
> There are 2 specials only because the product_id = 30 is duplicated.



> 
> 
> @cgcmart
> 
> ```
> INSERT INTO `oc_product_special` (`product_special_id`, `product_id`, `customer_group_id`, `priority`, `price`, `date_start`, `date_end`) VALUES
> (419, 42, 1, 1, '90.0000', '0000-00-00', '0000-00-00'),
> (439, 30, 1, 2, '90.0000', '0000-00-00', '0000-00-00'),
> (438, 30, 1, 1, '80.0000', '0000-00-00', '0000-00-00');
> ```
> 
> There are 2 specials only because the product_id = 30 is duplicated.

Thanks. It's the same product_id is allowed at a different priority level. I added 2 more items, product/special displayed.

**Comment by straightlight** [comment]
@cgcmart: The date start and date_end both shows as 0s. Do you have the date('p) added into both startup controllers as per the master branch and the pre-release version?

**Comment by cgcmart** [comment]
catalog/controller/startup/startup.php line 35
`$this->db->query("SET time_zone = '" . $this->db->escape(date('P')) . "'");`

**Comment by engwalid1971** [comment]
> @engwalid1971 Which oc version?

@cgcmart
Master branch

**Comment by engwalid1971** [comment]
@eka7a
Tested and everything looks good.

**Comment by straightlight** [comment]
@cgcmart: Please export your oc_product_special table and post it here (minimum rows where the products are loading versus the ones that are not).

**Comment by cgcmart** [comment]
My issue is solved. I posted the above screen.
The one is not displayed:
`(439, 30, 1, 2, '90.0000', '0000-00-00', '0000-00-00'),`
I think because of its priority value `2`, not the same product_id `30`

**Comment by straightlight** [comment]
Then, here we go. It's not a bug. It's simply a data-relationship issue.

**Comment by cgcmart** [comment]
@straightlight 
eka7a's commit is needed for product list/grid view on pages.
But for engwalid1971's issue (2/3) and issue 4, module twig bestseller, latest, special maybe need comment out / remove product layout product list (module) tags
either `product-layout product-list col-lg-3 col-md-3 col-sm-6 col-12` or
`product-layout product-module col-lg-3 col-md-3 col-sm-6 col-12`

**Comment by straightlight** [comment]
> @straightlight
> eka7a's commit is needed for product list/grid view on pages.
> But for engwalid1971's issue (2/3) and issue 4, module twig bestseller, latest, special maybe need comment out / remove product layout product list (module) tags
> either `product-layout product-list col-lg-3 col-md-3 col-sm-6 col-12` or
> `product-layout product-module col-lg-3 col-md-3 col-sm-6 col-12`

Yes, ok. That does make sense. The grid / list might require different adjustments between pages from each layouts. Which is why I think engwalid1971 encountered that issue based on the screenshot provided above. However, it won't solve the problem by moving the col to CSS but rather to adjust each cols from each modules requiring to load the product/thumb TWIG file. Your solution above might be the best approach so not to affect the default theme nor custom CSS targeting the default theme.

@danielkerr: This may require adjustments with the modules versus dynamic pages when calling the product/thumb.

**Comment by straightlight** [comment]
There's also a similar situation posted here: https://github.com/opencart/opencart/pull/6914 . Wondering if there's a pattern between the two.

**Comment by danielkerr** [comment]
there should be some fix with the latest bootstrap. you can set number of rows based on screen size.

**Comment by danielkerr** [comment]
the latest boostrap actually fixes this issue already. im testing pages though to try to reduce pages being to squashed up.
