### ISSUE TITLE
New order email notifications are not working(customer and admin), other emails work fine(new customer, newsletter, contact us)

### ISSUE THREAD

**Issue by calexil** [opencart/opencart#8120]
**What version of OpenCart are you reporting this for?**
2.1.0.2
**Describe the bug**
New order email notifications are not working(customer and admin), other emails work fine(new customer, newsletter, contact us)

**To Reproduce**
place a fake order in 2.1.0.2

**Expected behavior**
the order email goes to the customer and the admin

**Server / Test environment (please complete the following information):**
 - Linux Cpanel thru godaddy
 - PHP version
7.2
 - Browser(s) tested with [e.g. chrome, safari - if applicable]
all

no errors thrown, completely baffled

**Comment by straightlight** [comment]
Please post on the OC forum for those versions at https://forum.opencart.com . This commit will now be closed.
