### ISSUE TITLE
When an order of a product with options is placed, the order_alert email sent to staff omits options.

### ISSUE THREAD

**Issue by lordfeck** [opencart/opencart#8124]
**What version of OpenCart are you reporting this for?**
3.0.3.3

**Describe the bug**
When an order of a product with options is placed, the order_alert email sent to staff omits options.

According to the order_alert.twig file, this information should be included in the email. I have also looked at the controller 'order.php' which seems to pass this information into the template. 

**To Reproduce**
1. Add a product and ensure the product has options - e.g. size
2. Login and place the order. (I used a sandboxed PPE checkout)
3. Check the staff email address - it will show no options in the order alert email.

**Expected behavior**
For each ordered product, we expect each option and each of the customer's selections for the options to appear.

**Quick fix**
If I edit 'order_alert.twig' in the following way and add "or true", the orders will appear in every email:

`{# or true to always have it on #}`
`{% if option or true %}`
`{% for option in product.option %}`
`    - {{ option.name }} {{ option.value }}`
`{% endfor %}`
`{% endif %} `

This works by bypassing functionality where it first checks that there are options before printing them - we'd prefer this original logic of the template to stand. Though, it narrows the problem down to the template file/engine - we know the "options" are being correctly passed from "catalog/controller/mail/order.php:334" file.

**Screenshots / Screen recordings**
I'll quote the email which omits the options below:

> You have received an order.
> 
> Order ID: 20
> Date Added: 24/07/2020
> Order Status: Payment Recieved - Processing
> 
> Products
> 
> 2x Sample Free Product (nothing) £0.00
> 
> Totals
> 
> Sub-Total: £0.00
> Royal Mail Tracked 48: £4.74
> Total: £4.74

What follows is the email received when I apply the above "quick fix":

> You have received an order.
> 
> Order ID: 21
> Date Added: 24/07/2020
> Order Status: Payment Recieved - Processing
> 
> Products
> 
> 2x Sample Free Product (nothing) £0.00
> 	- Adult Sizes (S/M/L) Small
> 
> Totals
> 
> Sub-Total: £0.00
> Royal Mail Tracked 24: £5.46
> Total: £5.46

This time, the options were successfully printed.

**Server / Test environment (please complete the following information):**
 - Environment: Remote web host
 - Debian Linux - Buster
 - PHP version 7.3
 - Apache version - not known, though it is Apache.

**Comment by straightlight** [comment]
```{% if option or true %}```

should be:

```{% if product.option %}```

Already fixed in the master branch. Therefore, this commit will now be closed.
