### ISSUE TITLE
Master Branch - PHP 7+ requirement error message on install should be updated

### ISSUE THREAD

**Issue by NancySavage** [opencart/opencart#8128]
Upon closer inspection of the cli_install.php file, i see:

		if (version_compare(phpversion(), '7.3.0', '<')) {
			$error .= 'ERROR: You need to use PHP7+ or above for OpenCart to work!' . "\n";
		}
If you're using PHP 7 but it's below 7.3 you won't know unless you explicitly state instead:

ERROR: You need to use PHP 7.3 or above for OpenCart to work!

I got confused at first myself as to why it wouldn't work since I was previously using 7.1.9 and I had to hunt for the error message inside the install file in order to figure out that I had to upgrade.

**Comment by NancySavage** [comment]
Upon closer inspection of the cli_install.php file, i see:

```
		if (version_compare(phpversion(), '7.3.0', '<')) {
			$error .= 'ERROR: You need to use PHP7+ or above for OpenCart to work!' . "\n";
		}
```

Is this supposed to be true?

**Comment by NancySavage** [comment]
Nevermind. Just close this out. I guess now 7.3 is a requirement now that I see it listed in the commit. But for future maybe edit the message to explicitly state such instead of just saying "You need to use PHP7+ or above."

**Comment by straightlight** [comment]
May be this requirement should be added prior to run the upgrade so that unaware users may not end up with countless PHP errors outputted by the error handlers.

**Comment by danielkerr** [comment]
updated already.
