### ISSUE TITLE
Ocmod Can not be used normally

### ISSUE THREAD

**Issue by cyan1245357320** [opencart/opencart#8138]
**OpenCart 3.0.3.6 **

**Describe the bug**
Problem making OpenCart Plugin -->Install-->Refresh.
FILE: system/library/template/twig.php
CODE: $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);
NOT FOUND - OPERATIONS ABORTED!

**To Reproduce**
1. Go to 'Extensions'
2. Click on 'Modifications --> log'
3. See error

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/24307489/88634005-61cc7200-d0e8-11ea-9b59-734adaef28a3.png)

**Comment by chongshengdz** [comment]
it was fixed.
https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/modification.xml
follow the above link and replace the file.
