### ISSUE TITLE
Sessions expiry are incorrectly used, causing cookies to prematurely expire when session.cookie_lifetime is set.

### ISSUE THREAD

**Issue by sebastiannielsen** [opencart/opencart#8141]
**What version of OpenCart are you reporting this for?**
3.0.3.3

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

When setting session.cookie_lifetime = 86400 - this causes cookie not to be set at all.
Going into the source, I find this:

./catalog/controller/startup/session.php:                       setcookie($this->config->get('session_name'), $this->session->getId(), ini_get('session.cookie_lifetime'), ini_get('session.cookie_path'), ini_get('session.cookie_domain'));
./system/framework.php: setcookie($config->get('session_name'), $session->getId(), ini_get('session.cookie_lifetime'), ini_get('session.cookie_path'), ini_get('session.cookie_domain'));

Documentation for setcookie:
https://www.php.net/manual/en/function.setcookie.php

this means, that setting EXPIRY = ini_get('session.cookie_lifetime') means cookie will expire at 86400 set in unix time = 
01/02/1970 @ 12:00

Of course this is an oversight/bug, as the developer forgot that you need to ADD expiry duration to current time, not just use the expiry duration verbatim, as setcookie(); expects a absolute expiry time and not a expiry duration.

fix:

Replace  "ini_get('session.cookie_lifetime')" with "time() + (int)ini_get('session.cookie_lifetime')" in both ./system/framework.php and ./catalog/controller/startup/session.php

**Comment by ADDCreative** [comment]
You also need to account for session.cookie_lifetime being zero.
```php
((int)ini_get('session.cookie_lifetime > 0) ? (time() + (int)ini_get('session.cookie_lifetime')) : 0
```

**Comment by danielkerr** [comment]
this has been fixed in master branch.
