### ISSUE TITLE
The new version of opencart 3.0.3.6 can't apply modification changes 

### ISSUE THREAD

**Issue by spamacom** [opencart/opencart#8142]
opencart version : 3.0.3.6

the modification in catalog/view can't be apply and not appear in front ends.

https://demo.sbase.co/admin
username: admin 
password : 123

**Comment by diegospm** [comment]
Hi!

The new version modified the twig loader. The OCmod version you are using is still based on Twig_Loader_Filesystem, however version 3.0.3.6 uses ArrayLoader.

You need to ask the modification developer to update its compatibility.

**Comment by gRoberts84** [comment]
Came across this my self when it stopped loading admin views. Add this to your modification file ;) 

```
<file path="system/library/template/twig.php">
    <operation>
        <search>
            <![CDATA[$loader = new \Twig\Loader\ArrayLoader(array($filename . '.twig' => $code));]]>
        </search>
        <add position="replace">
            <![CDATA[
            $loader = new \Twig_Loader_Filesystem();

            if (defined('DIR_CATALOG') && is_dir(DIR_MODIFICATION . 'admin/view/template/')) {
                $loader->addPath(DIR_MODIFICATION . 'admin/view/template/');
            } elseif (is_dir(DIR_MODIFICATION . 'catalog/view/theme/')) {
                $loader->addPath(DIR_MODIFICATION . 'catalog/view/theme/');
            }

            $loader->addPath(DIR_TEMPLATE);]]>
        </add>
    </operation>
</file>
```

**Comment by WebkulOpencart** [comment]
This is already resolved so closing this issue.
