### ISSUE TITLE
Ckeditor adding image problem.

### ISSUE THREAD

**Issue by talipdere** [opencart/opencart#8144]
https://github.com/opencart/opencart/blob/f9e5b45c3fb2bb6410c70ed9233365a93466b329/upload/admin/view/template/common/filemanager.twig#L54

You can click on add each image from the editor because it adds click code and adds as many images as clicks.
To fix this error before
the following code should be added.

$('#modal-image').attr('onclick','').unbind('click');
$('#modal-image').attr('keydown','').unbind('keydown');

**Comment by prabhatkumaroc082** [comment]
a single change can not make it work.
if you want to use Opencart Filemanager in CKEditor then you will have to make changes to make it compatible

sample code to use ckeditor in any admin twig
`<textarea name="content" class="form-control ckeditor"></textarea>
<script src="https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
<script>
CKEDITOR.replace( 'content', {
  height: 300,
 filebrowserImageBrowseUrl: 'index.php?route=common/custom_filemanager&user_token={{ user_token }}'
});
</script>`
copy the common/filemanager code to common/custom_filemanager and make this controller and it's view compatible.

It is also not supported in the default Opencart so you can check it https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=23330 as well.

**Comment by prabhatkumaroc082** [comment]
not a v3.0.3.6 issue.

**Comment by danielkerr** [comment]
the issue is because its not removing the old modal on load. trying to fix
