### ISSUE TITLE
IDE project files are present in releases 3.0.3.5 and 3.0.3.6

### ISSUE THREAD

**Issue by dharmawebstudio** [opencart/opencart#8146]
IDE project files are present in releases 3.0.3.5 and 3.0.3.6

https://github.com/opencart/opencart/tree/3.0.3.5/upload/.idea
https://github.com/opencart/opencart/tree/3.0.3.6/upload/.idea

Other releases ignore them.

**Comment by prabhatkumaroc082** [comment]
fix #9092
