### ISSUE TITLE
How to use debug on 3.0.3.6

### ISSUE THREAD

**Issue by Kushelbek** [opencart/opencart#8147]
Hi all, how i can use {{ debug() }} in new version?
Early i'm use this code to use debug: 
Go to system/library/template/Twig/Environment.php In $options array. Set 'debug' option to 'true' at the bottom add:

$this->addExtension(new Twig_Extension_Debug());

But now in  system/library/template i'm don't see Twig folder.
Thnx 4 answer.

**Comment by webkul-dilip** [comment]
https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/library/template/twig.php#L25 Now you can set the 'debug' option to 'true'  at this line.

**Comment by webkul-dilip** [comment]
For any query please ask at the Opencart forum. https://forum.opencart.com/
