### ISSUE TITLE
[3.0.3.6] Login Error - All customer accounts without address AND not activated Default Address radio button

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#8148]
**What version of OpenCart are you reporting this for?**
3.0.3.6

**Describe the bug**
Frontend 
Go to Login and login to a store (not default) - 
Login is done but in the headline a error message appear.
Notice: Trying to access array offset on value of type bool in .../catalog/controller/startup/startup.php on line 166

What condition does it affect?
All customer account without address entry AND not activated Default Address radio button

**To Reproduce**
1. Go to 'Frontend-Login'
2. Enter data
2. Click on 'Login'
3. Wait till login is done

**Server / Test environment (please complete the following information):**
 - Local development and Deployed to a web server
 - Operating system linux
 - PHP version - 7.3 and 7.4
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22]  78.0.2

**Comment by webkul-dilip** [comment]
@pemaier  this issue now fix fixed please check in  3.0.x.x_Maintenance branch.
