### ISSUE TITLE
Restore Backup doesn't work with custom .sql file

### ISSUE THREAD

**Issue by sebastiannielsen** [opencart/opencart#8155]
**What version of OpenCart are you reporting this for?**
3.0.3.3

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Admin/Maintenace/Restore Backup

Restoring a custom generated .sql file backup doesn't work.
It does not give any error, but does not import either.

See attached .sql file (added .txt to just get Github to accept it)
[import.sql.txt](https://github.com/opencart/opencart/files/5004953/import.sql.txt)

**Expected behavior**
The data should be imported, or atleast give an error if there is something erronous with the data.

**Comment by prabhatkumaroc082** [comment]
[import.sql.txt](https://github.com/opencart/opencart/files/5779847/import.sql.txt)
try this SQL is working.

**Comment by prabhatkumaroc082** [comment]
try Opencart exported SQL.

**Comment by prabhatkumaroc082** [comment]
some conditions are there while importing sql like new lines which are not matched for your attached sql and this option is given to restore to the backup of opencart exported sql.
