### ISSUE TITLE
While using the gift voucher option, the unit price of the gift voucher is one even if the amount of gift voucher is 500 for example.

### ISSUE THREAD

**Issue by Zhoha28** [opencart/opencart#8160]
**What version of OpenCart are you reporting this for?** 
Opencart Version 3.0.3.2
**Describe the bug**
While using the gift voucher option, the unit price of the gift voucher is one even if the amount of gift voucher is 500 for example. I have a minimum and maximum amount set for the cart, so it does not allow me to proceed with the checkout

**Expected behavior**
The unit price should be the amount of gift voucher
![Capture](https://user-images.githubusercontent.com/32241004/89099815-92294e80-d40f-11ea-9636-6a344c198715.PNG)

**Comment by prabhatkumaroc082** [comment]
it looks like this issue is coming due to minimum or maximum amount validation. also, Opencart supports only a minimum amount so check your cart validation.

**Comment by yvonn** [comment]
Maybe you have an issue with your theme. In your image you can see that QUANTITY is 1 (not UNIT PRICE), UNIT PRICE = $100, TOTAL $100.
