### ISSUE TITLE
[3.0.3.6] big problem with PayPal Express Checkout, please check it.

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#8161]
problem with PayPal Express Checkout, please hurry up to double check it and test it.
No orders these days from my customers after upgrading to opencart 3.0.3.6.
only received some complaint message about PayPal Express Checkout problem.
below is one of the messages from my customers.
**"Hello, I have tried again and the same problem continues, I cannot make the payment, I enter PAYPAL but it stays processing 5 minutes and it does not finish.".**
these is no such problem with opencart 3.0.3.2
please help fix the problem ASAP.
php version 7.3.20

**Comment by cgcmart** [comment]
did you check #8156?

**Comment by chongshengdz** [comment]
yes, but problem still existed.
so i changed to php 7.3.20, problem still existed.

too bad, lose some money these days with no orders.
and now i changed to PayPal Payments Standard, it works fine.

please help investigate the problem with PayPal Express Checkout.

you can try it yourself, after go to PayPal checkout page and choose to pay via credit cards, the error page will show up.

**Comment by faca5** [comment]
Hello.

PayPal buttons in admin not working

Url:
https://localhost/admin/index.php?route=extension/payment/pp_express&user_token=XXX

Example:
https://localhost/admin/&displayMode=minibrowser

Error:
Not found.


I got error in checkout:
We’re sorry
Things don’t appear to be working at the moment.

I dont know if API keys wrong or problem with latest version.
I tried on PHP 7.3, 7.4 etc.

**Comment by faca5** [comment]
Hello.

PayPal Config Live and Sandbox buttons for quick setup in PayPal Express Checkout doesn't work.
https://localhost/admin/index.php?route=extension/payment/pp_express&user_token=

Url:
https://localhost/admin/&displayMode=minibrowser
404 not found

**Comment by brickmodder** [comment]
I'm having the same issue on 3.0.3.6.  Is there a work-around to get Express fixed? The PayPal Payments Standard is working in place of Express, but it has its own issues and it's not my preferred method.

Thanks in advanced,
Rob (not a coder)

**Comment by webkul-dilip** [comment]
@danielkerr Please check this issue same issue https://github.com/opencart/opencart/issues/7714 you have mentioned that you will remove the link from the master branch, can we do the same for maintenance-branch+3.0.x.x branch?

**Comment by webkul-dilip** [comment]
You can apply for an account directly with paypal and add you account info to the extension. Please enter the details manually http://i.prntscr.com/qJxzdPJuTfCpMQOwspVwQQ.png

**Comment by mehdiRma10** [comment]
i can confirm that the issue is still present up to the latest version opencart-3.0.3.7

**Comment by nikonov91-dev** [comment]
This solution helped me: [change sandbox to prod environement variable in express twig](https://github.com/opencart/opencart/pull/6595/commits/abcb47dde779664dd3e9f710958f18a5b55bfac5)
