### ISSUE TITLE
Master Branch - refresh modifications missing

### ISSUE THREAD

**Issue by mosolygozsolt** [opencart/opencart#8175]
**What version of OpenCart are you reporting this for?**
Master branch

**Describe the bug**
I tried to install the Journal 3 theme to the downloaded master branch version of OpenCart. The upload and the install in the extensions/modules working great, but it's need to refresh the modifications, but in this version of the admin site I can't finde the refresh button.

**Server / Test environment (please complete the following information):**
 - web server
 - Linux
 - PHP 7.4.8
 - Apache version - don't know
 - Firefox
 - 79

**Additional context**
I know, the master branch is under developement, thats why I ask now, I would like to upgrade our plugins to the newest verison.

**Comment by eka7a** [comment]
Removed modifications in master branch.
https://github.com/opencart/opencart/commit/e487a156f487c298532beb9d599f4e0f98235963

**Comment by mosolygozsolt** [comment]
You don't say -.-'

I know, its removed, but how can we update the modifications now for Jorunal or something else what need it?
