### ISSUE TITLE
fix for cache.catalog.language bug fixed in master but not in releases

### ISSUE THREAD

**Issue by xpavp03** [opencart/opencart#8183]
**What version of OpenCart are you reporting this for?**
3.0.3.6

**Describe the bug**
`Warning: fopen(/home/encounters/domains/encounters.be/shop_update/system/cache/cache.catalog.language.1538511947): failed to open stream: No such file or directory`
mentioned for example in issue #6925 has been fixed with commit 3c1d46d5826be9173b96b2c9c4619b990171168e in master on 11 Oct 2017 
and yet it's not present in the latest release (I checked a few earlier ones as well).

**To Reproduce**
Compare
https://github.com/opencart/opencart/blob/master/upload/catalog/model/localisation/language.php#L10
https://github.com/opencart/opencart/blob/master/upload/admin/model/localisation/language.php#L274
with corresponding lines from files in
https://github.com/opencart/opencart/archive/3.0.3.6.zip

**Expected behavior**
Please include the fix in release files.

**Comment by packeta** [comment]
+1

**Comment by condor2** [comment]
The fix was added.
https://github.com/opencart/opencart/commit/2f93e6a7c85e7062fb9d682d8374a8f8e3087465#diff-3c2b31affff1cb158e8b23fba9bfe80a
https://github.com/opencart/opencart/commit/4de67d1d4b948e58f702feb4bdfe00988965c3df#diff-95b2c7fe907988da2ae89cfd61e46133


 Better download 3.0.3.6 from github and maybe soon a new 3.0.3.6 or 3.0.3.7 will be released.
https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance

**Comment by xpavp03** [comment]
Thank you for your time @condor2. 

> Better download 3.0.3.6 from github

I'm not sure I understand. I do download it from GitHub (releases/zip). Do you mean I should use git checkout from branch 3.0.x.x_Maintenance or master? I could but I that's not what Main Street users would do.

I filed this issue because regular users go to opencart.com and click the big Download Now button:
https://www.opencart.com/index.php?route=cms/download/download&download_id=62
which downloads this file:
https://github.com/opencart/opencart/releases/download/3.0.3.6/opencart-3.0.3.6.zip

Although its content isn't identical to the GitHub release zip file I linked above, it doesn't contain the bug fix either.

I know how to patch OC to fix the bug, my concern is for the inexperienced users.

> maybe soon a new 3.0.3.6 or 3.0.3.7 will be released

Do you mean that you plan on updating the current zip release files to include the bug fix? Thank you.

**Comment by condor2** [comment]
Download from Branch not releases....
![Screenshot_2020-08-07_13-48-05](https://user-images.githubusercontent.com/14251939/89638722-f25b3d00-d8b4-11ea-8021-89f9c591c455.png)

I don't have access ...so I can't release any version. Daniel can.

**Comment by xpavp03** [comment]
I see, thank you. So now it's Daniel's turn.

**Comment by prabhatkumaroc082** [comment]
I think no issue in https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance now. The new release will be there soon.
