### ISSUE TITLE
Out-of-date jquery + bootstrap libraries

### ISSUE THREAD

**Issue by MadMcJack** [opencart/opencart#8184]
When checking the latest opencart version with Google Chrome's Lighthouse tool I get these warnings:

Includes front-end JavaScript libraries with known security vulnerabilities: 

9 vulnerabilities detected

Library Version | Vulnerability Count | Highest Severity
Bootstrap@3.3.5 | 5 | Medium
jQuery@2.1.1 | 4 | Medium

Could the included javascript libraries please be updated to the latest (compatible/secure) versions...

Opencart version 3.0.3.6

**Comment by chongshengdz** [comment]
if you can fix some samll problems, the master branch is ready for use now after some hours of testing.
a sucessful shopping cart is -- customers can add your products to cart, register an account and choose shipping method and pay you without problem.

**Comment by NancySavage** [comment]
It's a similar situation with the master branch, too. It's still using an outdated jQuery version from three years ago (3.3.1). The current release is 3.5.1. So you will the same message regardless.

**Comment by chongshengdz** [comment]
for master branch.
jquery 3.3.1 is compatible with 3.5.1.
bootstrap 4.3.1 is compatible with v4.5.2
you can easily replace files after you download the latest jquery + bootstrap libraries.

**Comment by danielkerr** [comment]
will update just before release. as for security and js theres no issue that will effect oc.

**Comment by BuslikDrev** [comment]
> будет обновляться непосредственно перед выпуском. Что касается безопасности и js, нет проблем, которые повлияют на oc.

In order not to create unnecessary questions, tell me why you decided to put a backquote everywhere?
https://github.com/opencart/opencart/blob/master/upload/catalog/model/catalog/product.php

**Comment by prabhatkumaroc082** [comment]
@danielkerr sir
bootstrap 
v3.3.7 is fine
v4.1.3 or v4.5.3 will create an issue https://prnt.sc/wis19e https://prnt.sc/wis1re, allow us to make it work

jquery
v3.5.1 is fine

**Comment by WebkulOpencart** [comment]
libraries are already update in the master branch
