### ISSUE TITLE
[Master Branch] seo_profile regex don't match correctly.

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#8195]
[Master Branch] seo_profile regex don't match correctly.
for example
route=product/contact&product_id=260
route=account/contact&product_id=260
will all go to the product page.

**Comment by chongshengdz** [comment]
all url include product_id=260 will rewrite to the product page, this should be a bug.

**Comment by chongshengdz** [comment]
even add route (product/contact = contact) to the oc_seo_url
the page still rewrite to the product page

**Comment by danielkerr** [comment]
ok looking into a fix

**Comment by danielkerr** [comment]
there is a fix but need to alter the urls.  add a seo keyword for the route to set the page to load.

**Comment by danielkerr** [comment]
this does happen but its down to you how you want the urls structured. look how i have done information pages. how it uses a keyword to replace the route of information/information/info. it can be altered without altering coded.
