### ISSUE TITLE
Paypal smart button, PayPal Commerce Platform Extension, address error when customer is looged in

### ISSUE THREAD

**Issue by bbiiggoorr** [opencart/opencart#8197]
**What version of OpenCart are you reporting this for?**
3.0.3.2 - clean install

**Describe the bug**
PayPal Commerce Platform Extension V1.1.5
When the user is **logged in** and uses the PayPal extension to check out by clicking the PayPal smart button in the shopping cart page or the product page. The billing details (address) is not passed to the confirm order page. 
This results in the following error.
Notice: Undefined index: payment_address in /catalog/controller/extension/module/paypal_smart_button.php on line 743 

NOTE: if the user goes to the checkout page and selects the PayPal as the payment method in STEP3. Module works fine.

**To Reproduce**
1. add a product to the cart
2. go to cart
3. click the PayPal button and proceed with the PayPal login
4. Then you are taken to "extension/module/paypal_smart_button/confirmOrder" which produces the error.

**Expected behavior**
expected the address details from paypal to be passed back or for the error not to show allowing the customer to enter their own billing/address details

**Screenshots / Screen recordings**
![paypalerror1](https://user-images.githubusercontent.com/69445162/89867985-5eaba880-dbf5-11ea-988d-a0bdb6811070.gif)

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - Operating system
linux
 - PHP version
7.3.19
 - Apache version
2.4.43
 - Browser(s) tested with
 - firefox 79.0
 - chrome 84.0.4147.105

**Comment by condor2** [comment]
You have tested latest version? 
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=38358

**Comment by bbiiggoorr** [comment]
Yes, v1.1.5. I also just did a live test to make sure it is not somthing to do with the way sandbox handles this. Same issue with live.

**Comment by condor2** [comment]
Then check with this. Not checked if that files from this commit is the same as version from Marketplace.
https://github.com/opencart/opencart/commit/f0255e79b98fafe41d4b4cdd6b83b24b9fdfcd76

**Comment by bbiiggoorr** [comment]
Yes, one of the first things I did was to get the newest github version to make sure this hasn't been addressed.
And I also checked it again now.

Are you able to replicate this error?

**Comment by condor2** [comment]
I don't use any of Paypal extensions.

**Comment by bbiiggoorr** [comment]
I found the problem was that the session data would never have set the "shipping_address_id" and "payment_address_id". I couldn't find any reference to those arrays in the files for this module so I am not sure what is going on there.

I have tested a possible solution. It seems to work.

The solution will set the customers address if the customer is logged in. If the customer has a different address in paypal it will change to that address as the shipping address. If customer is checking out without logging in, it uses data passed by paypal.

Following changes need to be made

LINE 656
`$data['shipping_address'] = $this->model_account_address->getAddress($this->session->data['shipping_address_id']);
			} elseif `

REPLACE WITH
`$data['shipping_address'] = $this->model_account_address->getAddress($this->customer->getAddressId());			
			} 
			if`

LINE 726
`if ($this->customer->isLogged() && isset($this->session->data['payment_address_id'])) {
			$this->load->model('account/address');
			
			$data['payment_address'] = $this->model_account_address->getAddress($this->session->data['payment_address_id']);
		} elseif`

REPLACE WITH
`if ($this->customer->isLogged()) {
			$this->load->model('account/address');
			
			$data['payment_address'] = $this->model_account_address->getAddress($this->customer->getAddressId());
		} 
		if`

LINE 1376
`		if ($this->customer->isLogged() && isset($this->session->data['payment_address_id'])) {
			$this->load->model('account/address');
			
			$data['payment_address'] = $this->model_account_address->getAddress($this->session->data['payment_address_id']);
		} elseif (isset($this->session->data['guest']) && isset($this->session->data['payment_address'])) {`

REPLACE WITH
`if ($this->customer->isLogged()) {
			$this->load->model('account/address');
			
			$data['payment_address'] = $this->model_account_address->getAddress($this->customer->getAddressId());
		} 
		if (isset($this->session->data['guest']) && isset($this->session->data['payment_address'])) {`

LINE 1402
`$data['shipping_address'] = $this->model_account_address->getAddress($this->session->data['shipping_address_id']);
		} elseif (isset($this->session->data['shipping_address'])) {`

REPLACE WITH
`$data['shipping_address'] = $this->model_account_address->getAddress($this->customer->getAddressId());
		} 
		if (isset($this->session->data['shipping_address'])) {`

**Comment by oringmonkey** [comment]
I'm getting an "undefined index: payment_address in catalog/controller/extension/module/paypal_smart_button.php on line 743.  Anyone know how to resolve this?

**Comment by webkul-dilip** [comment]
https://github.com/opencart/opencart/pull/9142 please check the pull request

**Comment by dmitriyzhuk** [comment]
Hi Guys, please check out the latest prerelease. https://github.com/Dreamvention/paypal/releases/tag/v1.2.1

let me know if all is working correctly. thanks!
