### ISSUE TITLE
Paypal commerce charges only for products

### ISSUE THREAD

**Issue by atnaples** [opencart/opencart#8247]
3.0.3.6

Wrong statement: "Fixed issue with paypal commerce not working", it was not possible to configure it, log-in to PayPal.
Now, you can install, configure, place the order...

- product
- coupon
- shipping

**The order, invoice will be created corrected**, but you will get money for product(s)

**just place the order and add shipping**

**Server / Test environment (please complete the following information):**
 - Local development? a2hosting
 - Linux
 - PHP version: 7.3+

**Comment by webkul-dilip** [comment]
I have checked, it working fine we have attached the screenshot please check http://i.prntscr.com/MqvxIdH7REmBMOEfgHE6sw.png

**Comment by dmitriyzhuk** [comment]
Hi Guys, please check out the latest prerelease. https://github.com/Dreamvention/paypal/releases/tag/v1.2.1

let me know if all is working correctly. thanks!

**Comment by atnaples** [comment]
What version of opencart?

**Comment by dmitriyzhuk** [comment]
the fix is done on every version in the release https://github.com/Dreamvention/paypal/releases/tag/v1.2.1 but you can test on the latest which is 3.x
