### ISSUE TITLE
[Master Branch] Undefined offset: 3 in vendor/scssphp/scssphp/src/Parser.php on line 1250

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#8249]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
When browse the store this warning message is displayed.

**Expected behavior**
This warning message should not be shown.

**Server / Test environment (please complete the following information):**
PHP 7.4.8

**Additional context**
On 3.0.3.6 this warning message doesn't show and use same version of SCSSPHP.

**Comment by danielkerr** [comment]
im still updating the new extension system to use name spaces. should be fixed in my next commit.

**Comment by danielkerr** [comment]
should be fixed now
