### ISSUE TITLE
Page Not Found!

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#8251]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
OpenCart

/admin/
Notice: Trying to access array offset on value of type null in /home/.../admin/controller/error/not_found.php on line 12

`'href' => $this->url->link('common/dashboard', 'user_token=' . $this->session->data['user_token'])`

Notice: Trying to access array offset on value of type null in /home/.../admin/controller/error/not_found.php on line 17

`'href' => $this->url->link('error/not_found', 'user_token=' . $this->session->data['user_token'])`

Fix:
Restore:  upload/admin/controller/startup/router.php

**To Reproduce**
1. Go to '.../admin/'

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
should be fixed already
