### ISSUE TITLE
[3.0.3.6] The template files (twig files) in storage/modification is not loaded.

### ISSUE THREAD

**Issue by tamledevinition** [opencart/opencart#8254]
Hi team,
I am making the module for Opencart 3.0.3.6. But I can't modify template.
For example: 
I want to add a column into the Admin -> Sales -> Orders. I add the xml file for making the order_list.twig in modification. 
But the system is still loading the admin/view/template/sale/order_list.twig. Although, we have this file in storage/modification/admin/view/template/sale/order_list.twig
I tried installing some modules in OpenCart Extension Store, they also didn't work.

**Comment by condor2** [comment]
Update this file

https://github.com/opencart/opencart/commit/d31b4ebe3fd29dcc8861725d4934c6e3dd68e019

**Comment by tamledevinition** [comment]
I am using this modification file. But it's still not working.

**Comment by condor2** [comment]
Maybe you have 2 storage....

**Comment by tamledevinition** [comment]
oh, It worked. Thanks for your help.
