### ISSUE TITLE
Facebook extensions module

### ISSUE THREAD

**Issue by madebylayton** [opencart/opencart#8270]
**What version of OpenCart are you reporting this for?** 3.0.2.0

**Describe the bug**
A clear and concise description of what the bug is

I have installed this Facebook extensions module and it is giving me errors, I have looked and made sure all the things suggested are correct and still showing errors.
This is the message that shows up:

We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

What section does it affect?

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by condor2** [comment]
Report here
https://github.com/facebookincubator/Facebook-For-OpenCart/issues

**Comment by madebylayton** [comment]
My issue is listed on this thread. #463

**Comment by condor2** [comment]
You have reported an issue with Facebook extension module....and is not made by Opencart. That's why I gave you that link...
