### ISSUE TITLE
OpenCart v3.0.3.6 - MySQL 8.x Installation error "sql_mode"

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#8273]
**What version of OpenCart are you reporting this for?**
3.0.3.6 (latest)

**Describe the bug**
Fatal error: Uncaught Exception: Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'<br />Error No: 1231<br />SET @@session.sql_mode = 'MYSQL40' in /system/library/db/mysqli.php:40 Stack trace: #0 /system/library/db.php(45): DB\MySQLi->query('SET @@session.s...') #1 /install/model/install/install.php(35): DB->query('SET @@session.s...') #2 /system/engine/loader.php(248): ModelInstallInstall->database(Array) #3 /system/engine/proxy.php(47): Loader->{closure}(Array, Array) #4 /install/controller/install/step_3.php(11): Proxy->__call('database', Array) #5 /system/engine/action.php(79): ControllerInstallStep3->index() #6 /system/engine/router.php(67): Action->execute(Object(Registry)) #7 /system/engine/router.php(56): Router->execute(Object(Action)) #8 /system/framew in /system/library/db/mysqli.php on line 40

**To Reproduce**
1. Go to Installation
2. Install OpenCart v3.0.3.6 on MySQL 8.x.

**Comment by ADDCreative** [comment]
https://github.com/opencart/opencart/pull/8126

**Comment by pro100Hub** [comment]
3.0.3.7 not fixed :(
/system/library/db/mysqli.php on line 41

![Open_Server_XEQRROUB14](https://user-images.githubusercontent.com/10475278/107876753-ab947280-6ee9-11eb-80dc-3b1412374145.png)
