### ISSUE TITLE
$_['text_logged'] missing from language file language/en-gb/common/header.php

### ISSUE THREAD

**Issue by erikaele** [opencart/opencart#8277]
**What version of OpenCart are you reporting this for?**
V3.0.3.3

**Describe the bug**
$data variable $data['text_logged'] in controller/common/header.php is getting populated using language variable $_['text_logged'] from language/en-gb/common/header.php (the language file loaded in controller/common/header.php), but there IS NO defined $_['text_logged'] variable in the language file, or any language file for that matter.

line 57: $data['text_logged'] = sprintf($this->language->get('text_logged'), $this->url->link('account/account', '', true), $this->customer->getFirstName(), $this->url->link('account/logout', '', true));

if the "text_logged" data variable is used in a common/header.twig, you just get output "text_logged".  When I created the variable in the language file, it works as expected...

Since this variable is getting used in a controller, you need to add the text_logged variable back into core. 

**Screenshots / Screen recordings**
In this image, I have 
![image](https://user-images.githubusercontent.com/70337651/91469651-a4a57500-e861-11ea-8b36-c7e43699158c.png)

**Additional context**
this is the portion of my code that is displaying the above image;
{% if logged %}
                        <li>
                          <span>Welcome {{ text_logged }}!</span>
                        </li>

**Comment by ADDCreative** [comment]
See https://github.com/opencart/opencart/pull/8135. text_logged should not be in the header controllers and your should not rely on it being there for your theme.
