### ISSUE TITLE
Modification files not loading after applying the code by OCMOD

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#8281]
**What version of OpenCart are you reporting this for?**
3.0.3.6 (latest)
**Describe the bug**
As we are facing this issue so much in the latest OpenCart version that modification not loading after applying the code using the OCMOD file

**Comment by condor2** [comment]
https://github.com/opencart/opencart/commit/d31b4ebe3fd29dcc8861725d4934c6e3dd68e019

**Comment by danielkerr** [comment]
ok ill do another release with the fix in.

**Comment by danielkerr** [comment]
Anyone want to take over maintaince releases? I'm close to finishing the next version but need some help with releases.

**Comment by WebkulOpencart** [comment]
@danielkerr Can you please let me know the points so that I can look into the same

**Comment by OniJoshin** [comment]
This has been an issue in the latest 2 releases of opencart..
Twig Files cannot be edited. PHP files all seem fine but its something to do with the Twig loader. Firstly the modification.xml Search query for twig modifications is wrong. Im currently looking at ways to fix this but if you have a fix i can apply to current stores or atleast include within OCMods im writing then that would be much appreciated.

**Comment by WebkulOpencart** [comment]
@OniJoshin Please check this commit
https://github.com/opencart/opencart/blob/d31b4ebe3fd29dcc8861725d4934c6e3dd68e019/upload/system/modification.xml

**Comment by OniJoshin** [comment]
@WebkulOpencart Thanks, we had just got ours fixed and working too but this will work perfectly too

**Comment by WebkulOpencart** [comment]
@OniJoshin 
Yes, it is working fine.

**Comment by WebkulOpencart** [comment]
This issue is resolved in the maintenance branch so closing this issue
