### ISSUE TITLE
[Discussion] PHP 7.3+ highlights

### ISSUE THREAD

**Issue by HaftasArden** [opencart/opencart#8284]
I noticed that Daniel and other developers are changing the code pattern. Whether changing from "array ()" to "[]", using "namespaces" or using PHP 7.3 as the basis for new versions.

Wouldn't it be time to use "type hinting", traits,  and code patterns like PSR?

PHP has evolved a lot and, with the OpenCart version break, I think we could keep up with that evolution.

Maybe replace
```php
if (isset($this->request->post['field'])) {
    $field = $this->request->post['field'];
} else {
    $field = $this->config->get('field');
}
```

with
```php
$field = $this->request->post['field'] ?? $this->config->get('field');
```

[Source: Null coalescing operator](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op)

--------

Maybe replace
```php
class ModelCheckoutOrder extends Model {
    public function getOrder($order_id) {
        $this->db->query('SELECT * FROM oc_order WHERE order_id = "' . (int) $order_id . '"');
    }
}
```

with
```php
class ModelCheckoutOrder extends Model
{
    public function getOrder(int $orderId)
    {
        $this->db->query('SELECT * FROM oc_order WHERE order_id = "' . $orderId . '"');
    }
}
```

[Source: Type Hinting](https://www.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.types)

**Comment by straightlight** [comment]
Regardless of the order_id vs orderId variable, I do agree the variable type should be entered into parameters as opposed to have to manually add those variable types manually since these can also be quite redundant in the models.

**Comment by HaftasArden** [comment]
I chose camelCase because of the PSR-1 and PSR-12, but is at the discretion.

**Comment by BroCart** [comment]
```
	public function getTotalCategoriesByCategoryId($parent_id = 0) {
		$query = $this->db->query("SELECT COUNT(*) AS total FROM " . DB_PREFIX . "category c LEFT JOIN " . DB_PREFIX . "category_to_store c2s ON (c.category_id = c2s.category_id) WHERE c.parent_id = '" . (int)$parent_id . "' AND c2s.store_id = '" . (int)$this->config->get('config_store_id') . "' AND c.status = '1'");

		return $query->row['total'];
	}
```
change to:

```
	public function getTotalCategoriesByCategoryId($parent_id = 0) {
		return $this->db->query("SELECT COUNT(*) AS total FROM " . DB_PREFIX . "category c LEFT JOIN " . DB_PREFIX . "category_to_store c2s ON (c.category_id = c2s.category_id) WHERE c.parent_id = '" . (int)$parent_id . "' AND c2s.store_id = '" . (int)$this->config->get('config_store_id') . "' AND c.status = '1'")->row['total'];
	}

```
What do you think?

**Comment by HaftasArden** [comment]
> ```
> public function getTotalCategoriesByCategoryId($parent_id = 0) {
> 	$query = $this->db->query("SELECT COUNT(*) AS total FROM " . DB_PREFIX . "category WHERE parent_id = '" . (int)$parent_id . "' AND status = '1'");
> 	return $query->row['total'];
> }
> ```
> 
> change to:
> 
> ```
> public function getTotalCategoriesByCategoryId($parent_id = 0) {
> 	return $this->db->query("SELECT COUNT(*) AS total FROM " . DB_PREFIX . "category WHERE parent_id = '" . (int)$parent_id . "' AND status = '1'")->row['total'];
> }
> ```
> 
> What do you think?

If OpenCart uses the PSR standard, a very long line (+120 characters) goes against it.

I've seen developers breaking the SQL code to improve viewing.

```
$this->db->query("
SELECT
    COUNT(*) AS total
FROM " . DB_PREFIX . "category
WHERE
    parent_id = '" . $parent_id . "'
    AND status = '1'
");
```

**Comment by danielkerr** [comment]
no way. 

look php psr or who ever wrote this so called standard of writing php has not based the standard on the php examples on php.net. 

I think who ever is writing the php psr should not be telling anyone how to code. its just their own style. its like the blind leading the blind again.

there are more coders out there that have been codijng php for years like myself based on the php.net examples of writing code which is similar to java.

**Comment by danielkerr** [comment]
personally if i was writing my own coding standard everything would be in lower case using _ instead of Microsoft fucking camel case. get back the programming basic code.

**Comment by HaftasArden** [comment]
Daniel, with all due respect, but you're looking at just the PSR part.

PHP has evolved and this evolution is not being used well by OpenCart.
Typing; new more secure hash algorithms (Argon2), Null coalescing operator,
Spaceship operator, Symmetric array destructuring, iterators, Multi catch
exception handling etc.

Soon, in PHP 8, we will have countless innovations. Are we going to
continue programming as if we were in PHP 5.6?

**Comment by danielkerr** [comment]
I know how to the new features and use it when when appropriate and not for the sake of it.
