### ISSUE TITLE
automatic moving storage directory outside of root copying it not moving it

### ISSUE THREAD

**Issue by nuryagdym** [opencart/opencart#8285]
Hello, 
I am new to Open Cart.
I did a fresh installation of Open Cart v3.0.3.6.
When I logged into the admin dashboard it prompted me to move the storage folder outside of the root directory. 
The proceeded, operation finished sucessfully. there is a copy of storage folder in the same level as upload directory.
However the old copy of storage directory which is located` ./upload/system/storage` here is still there. Moreover, composer.json 
 vendor-dir is still points to old location of storage directory.

1. should I delete old copy of storage directory from `./upload/system/storage`?
2. If yes why it is not deleted by app and is not told to delete in documentation?
3. Why composer.json's vendor-dir is still pointed to the old location (`./upload/system/storage/vendor`) of vendor dir?

**Comment by danielkerr** [comment]
just delete u need to change the config.php's with the new path

**Comment by danielkerr** [comment]
just delete the old path. there error should not appear again if the config.php has already been changed.

`		if (DIR_STORAGE == DIR_SYSTEM . 'storage/') {
			$data['security'] = $this->load->controller('common/security');
		} else {
			$data['security'] = '';
		}`

**Comment by nuryagdym** [comment]
Why issue closed, should be this problem fixed? should not the opencart itself delete old path of `storage`?

**Comment by straightlight** [comment]
> Why issue closed, should be this problem fixed? should not the opencart itself delete old path of `storage`?

No.
