### ISSUE TITLE
[Master Branch] - admin/model/setting/extension.php

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#8292]
The convention name of getExtensionsByType should be changed to getType since the latest convention names from the models' method names have mostly been shorten recently: https://github.com/opencart/opencart/commit/cda892f353c2a9c40c3c9fa97482645d2c991eb7 .

**Comment by danielkerr** [comment]
i feel it gives a better representation of what the method does.

**Comment by straightlight** [comment]
If so, then all other renamed methods since the new conventional names are also less represented.
