### ISSUE TITLE
Need documentation for seller API

### ISSUE THREAD

**Issue by prosenjeet123** [opencart/opencart#8294]
Hi

Thanks for the API option for the seller. We would like to take the advantage of this API. We are looking for solution to get opencart orders via GET/POST methods.
How should we proceed?
![image](https://user-images.githubusercontent.com/12624294/92416709-6c186c00-f17c-11ea-9a30-af5aa5d096aa.png)

Please help asap.

Regards

**Comment by straightlight** [comment]
Opencart.com forum request.

**Comment by prosenjeet123** [comment]
https://forum.opencart.com/viewtopic.php?f=110&t=219906

> Opencart.com forum request.

**Comment by prosenjeet123** [comment]
No information till now on this topic. Forum is saying to ask help in github.
![image](https://user-images.githubusercontent.com/12624294/92672390-30290680-f336-11ea-855f-fb63bdc1f09f.png)

**Comment by prosenjeet123** [comment]
> Opencart.com forum request.

No information till now on this topic. Forum is saying to ask help in github.
![image](https://user-images.githubusercontent.com/12624294/92672419-43d46d00-f336-11ea-91ba-6fd6810b7ad5.png)

**Comment by straightlight** [comment]
Nothing to do with master branch. Please post on the forum.

**Comment by danielkerr** [comment]
just log the post request.

**Comment by danielkerr** [comment]
order_id
extension_id
member_id
username
email
extension
quantity
sub_total
commission
total
order_status
date_added
date_modified
