### ISSUE TITLE
[OC 3.1.0.0 master branch] Installer bugs

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#8302]
The file **install/index.php** needs this to be added:

`define('DIR_EXTENSION', DIR_OPENCART . 'extension/');
`

Otherwise, the installer won't work!

**Comment by chongshengdz** [comment]
The file install/cli_install.php  needs to change from
$output .= 'define(\'DIR_TEMPLATE\', DIR_APPLICATION . \'view/theme/\');' . "\n";
 to
$output .= 'define(\'DIR_TEMPLATE\', DIR_APPLICATION . \'view/template/\');' . "\n";
on line 417

**Comment by zemguru** [comment]
Few more bugs:

### Install step must be changed to 7.3+ 
(because of https://github.com/opencart/opencart/commit/14bd26b3bbc34590426885942e2d71ae3e61555a#diff-67df43375da34ec536a11ef4d480d390R37)
![image](https://user-images.githubusercontent.com/30476178/93075899-259ca300-f68f-11ea-8272-1baaca37dc1d.png)


### SQL column count does not match 
('opencart' is missing for these extensions: https://github.com/opencart/opencart/blob/master/upload/install/opencart.sql#L827-L835 )

```
Exception: Error: Column count doesn't match value count at row 12
Error No: 1136
INSERT INTO `oc_extension` (`extension_id`, `extension`, `type`, `code`) VALUES

                   [...] ,(19, 'module', 'slideshow') [...] 

); 
in /upload/system/library/db/mysqli.php on line 43
```


### Fresh installation does not load catalog:

```
    Twig\Error\LoaderError: The "/upload/catalog/view/theme/" directory does not exist ("/upload/catalog/view/theme/"). in 
    /upload/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 92
```

**Comment by chongshengdz** [comment]
> Few more bugs:
> 
> ### Install step must be changed to 7.3+
> (because of [14bd26b#diff-67df43375da34ec536a11ef4d480d390R37](https://github.com/opencart/opencart/commit/14bd26b3bbc34590426885942e2d71ae3e61555a#diff-67df43375da34ec536a11ef4d480d390R37))
> ![image](https://user-images.githubusercontent.com/30476178/93075899-259ca300-f68f-11ea-8272-1baaca37dc1d.png)
> 
> ### SQL column count does not match
> ('opencart' is missing for these extensions: https://github.com/opencart/opencart/blob/master/upload/install/opencart.sql#L827-L835 )
> 
> ```
> Exception: Error: Column count doesn't match value count at row 12
> Error No: 1136
> INSERT INTO `oc_extension` (`extension_id`, `extension`, `type`, `code`) VALUES
> 
>                    [...] ,(19, 'module', 'slideshow') [...] 
> 
> ); 
> in /upload/system/library/db/mysqli.php on line 43
> ```
> 
> ### Fresh installation does not load catalog:
> ```
>     Twig\Error\LoaderError: The "/upload/catalog/view/theme/" directory does not exist ("/upload/catalog/view/theme/"). in 
>     /upload/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 92
> ```

The file install/index.php needs this to be added:

define('DIR_EXTENSION', DIR_OPENCART . 'extension/');

Otherwise, the installer won't work!

**Comment by mhcwebdesign** [comment]
I came across the same other issues for the installer, hence I changed the title of this issue.

**Comment by straightlight** [comment]
The humanity ...

**Comment by Jusufas** [comment]
On the last commit:

`PHP Fatal error:  Uncaught Error: Call to a member function setTitle() on string in /home/test/public_html/install/controller/install/step_1.php:11\nStack trace:\n#0 [internal function]: Opencart\\Application\\Controller\\Install\\Step1->index()\n#1 /home/test/public_html/system/engine/action.php(74): call_user_func_array()\n#2 /home/test/public_html/system/framework.php(117): Opencart\\System\\Engine\\Action->execute()\n#3 /home/test/public_html/system/startup.php(59): require_once('/home/test...')\n#4 /home/test/public_html/install/index.php(34): require_once('/home/test...')\n#5 {main}\n  thrown in /home/test/public_html/install/controller/install/step_1.php on line 11`

**Comment by mhcwebdesign** [comment]
That's because the library/framework.php no more longer contains this:

```
	// Document
	$registry->set('document', new System\Library\Document());
```

Instead, this is now done like this:
```
		// Document
		$this->registry->set('document', new \Opencart\System\Library\Document());
```
in files **admin/controller/startup/application.php** and **catalog/controller/startup/application.php**. There is no corresponding  file **install/startup/application.php** as yet, I'd expect Daniel to create one soon too.

In general, the OpenCart framework still is subject to many changes at the moment, so I think we should with testing it until it becomes more stable again.

**Comment by danielkerr** [comment]
should be working now.
