### ISSUE TITLE
order  full html email can't sent after placeing order 

### ISSUE THREAD

**Issue by saadmohmed** [opencart/opencart#8304]
**i figured out its because order_status_id never become zero so it can't be sent** 
```
	// If order status is 0 then becomes greater than 0 send main html email
			if (!$order_info['order_status_id'] && $order_status_id) {
				$this->add($order_info, $order_status_id, $comment, $notify);
			}
```

**Comment by straightlight** [comment]
OC version?

**Comment by saadmohmed** [comment]
3>

**Comment by straightlight** [comment]
That's because the order status ID should never become zero.

**Comment by saadmohmed** [comment]
so when should the full html email sent

**Comment by ADDCreative** [comment]
order_status_id will always start at zero.

**Comment by saadmohmed** [comment]
so why  the customer never recieved the full html email

**Comment by saadmohmed** [comment]
and if it start at zero so the email should be sent and this not happening

**Comment by straightlight** [comment]
Is there a specific reason why an undefined order status ID should send an HTML email as opposed to only positive IDs of order statuses?

**Comment by ADDCreative** [comment]
HTML order emails work fine for me in version 3.0.3.6. It could be a number of things why it's not working for you. Best to ask on the forums for help. https://forum.opencart.com/

**Comment by saadmohmed** [comment]
Okay i figured out that order_status_id is by default is 1 not zero
Problem aolved
