### ISSUE TITLE
How to tranlsate?

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#8318]
https://github.com/opencart/opencart/blob/24fa4a5b5d93fd94c615af07c232336dd7f407e0/upload/system/helper/general.php#L86

Example:
`if ($second < 10) {
		$date_added = 'just now';
	} elseif ($second) {
		$date_added = $second . ' seconds ago';
	}`

How shall such strings be translated?
Because it's a helper function, language translations cannot be used.

**Comment by straightlight** [comment]
An array should be added as a second parameter to output each strings from the array keys.

**Comment by chulcha** [comment]
may be
$date_added = sprintf....

**Comment by straightlight** [comment]
sprintf won't be able to pull the OC registry object from the helper files. Parameters needs to be entered such as these:

https://github.com/opencart/opencart/pull/8324
https://github.com/opencart/opencart/pull/8323
https://github.com/opencart/opencart/pull/8322

**Comment by chulcha** [comment]
{ $date_added = sprintf( $language['text_seconds_ago'], $second)

**Comment by straightlight** [comment]
Yes, with the entered parameter, this could also be achieved with sprintf.

**Comment by osworx** [comment]
In English this would be the out:

1 second ago
1 week ago
2 months ago

But - useless and nonsens in German (for example)!
If I would follow your last pull requests, that would be in German:

1 Sekunde ??
1 Woche ??
2 Monate ??

?? = means nothing,, because this IS the nonsens.

It must be that way:

Vor 1 Sekunde
Vor 1 Woche
Vor 2 Monaten (plural!) > singular would be: Vor 1 Monat

So it must be something with sprintf( .. ) or str_replace( .. )

**Comment by straightlight** [comment]
Done.

**Comment by osworx** [comment]
> Done.

What ?
The str_replace() or sprintf() or your last 3 pull requests yo umentioned above.

A second problem (time is king) is the function date_added(..) itself.
Seconds are translated from the give $date.
So fine so good.
But why going through the whole function if 5 seconds are true?
No need to calculate also minutes, weeks, months and years!

Same goes for each value - except when it is a year or more ..
A simple if ..then .. else or switch{..} could be the better alternative.

**Comment by straightlight** [comment]
These were already implemented. I simply translated them with sprintf since this commit is about translating date_added with multilanguage packs based on the arrays that will be initiated prior to run this function from the controllers.

**Comment by osworx** [comment]
@straightlight Thanks, I have seen your requests.
But not your latest with the `$_['text_seconds_ago']      = '%s seconds ago';`
Quite good solution.

About the function and the "time waster": maybe my fault that I have seen (and checked that function/file) not earlier.
But 3.x in general is not an option for me and my clients at the moment.
When 3.1 will be published, it's going into a better direction.

**Comment by condor2** [comment]
There more example like that

For example at pagination...

`Showing %d to %d of %d (%d Pages)`

Showing 9 to 10 of 10 (1 Pages), so can't be Pages....just Page is just one...

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/commit/2f0e6e75ce15456a7ee0a6b2f1d96186f9a3d8e1
