### ISSUE TITLE
ENHANCEMENT REQUEST: Add store name to Order List page (route=sale/order)

### ISSUE THREAD

**Issue by TheRealDJ** [opencart/opencart#8537]
I am using OpenCart (3.0.3.2) to host multiple stores. I would like the ability to see what store each store was placed from, as well as be able to filter orders per store on the order list page (route=sale/order).

For the mean time, I am using the following dB query to find the above info (change **PREFIX** to your actual configured dB table prefix)
`SELECT * FROM PREFIX_oc_order ORDER BY order_id DESC;`

**Comment by straightlight** [comment]
Please create a PR for this, not an incident request. A filter could be added into the sale/order to capture the selected store IDs from a dropdown menu or with an autocomplete text box.

**Comment by straightlight** [comment]
You can also take a look at this extension: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=28947 .

**Comment by condor2** [comment]
Or free. Easy to make
https://stackoverflow.com/questions/45284322/add-store-name-to-opencart-2-admin-order-list-page

**Comment by danielkerr** [comment]
fine
