### ISSUE TITLE
[3.0.3.6] PayPal Express Checkout

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#8605]
My Accounts > My Orders > Recurring payment > View

File missing or wrong path.
https://localhost/index.php?route=account/recurring

Url with error:
https://localhost/index.php?route=account/recurring/info&order_recurring_id=1
Fatal error: Uncaught Exception: Error: Could not load template /catalog/view/theme/extension/recurring/pp_express.twig! in /system/library/template/twig.php:17 

OpenCart v3.0.3.6
Module: PayPal Express Checkout
PHP 7.4

Error in 171 line:
catalog/controlller/account/recurring.php
`$data['recurring'] = $this->load->controller('extension/recurring/' . $recurring_info['payment_code']);
`
Solution:

Replace
`$data['recurring'] = $this->load->controller('extension/recurring/' . $recurring_info['payment_code']);
`with
`$data['recurring'] = $this->load->controller('extension/' . $recurring_info['payment_code']);
`

**Comment by faca5** [comment]
Additional error:

Admin > Sales > Order > tab PayPal Express Checkout

Transactions
Fatal error: Uncaught Twig\Error\SyntaxError: Unexpected token "string" of value "Completed" ("name" expected) in "extension/payment/pp_express_transaction.twig" at line 25. in /system/storage/vendor/twig/twig/src/TokenStream.php:76 Stack trace: 
#0 /system/storage/vendor/twig/twig/src/ExpressionParser.php(699): Twig\TokenStream->expect(5) 
#1 /system/storage/vendor/twig/twig/src/ExpressionParser.php(680): Twig\ExpressionParser->getTest(25) 
#2 /system/storage/vendor/twig/twig/src/ExpressionParser.php(79): Twig\ExpressionParser->parseTestExpression(Object(Twig\Node\Expression\GetAttrExpression)) 
#3 /system/storage/vendor/twig/twig/src/ExpressionParser.php(169): Twig\ExpressionParser->parseExpression() 
#4 /system/storage/vendor/twig/twig/src/ExpressionParser.php(70): Twig\ExpressionParser->getPrimary() 
#5 /system/storage/vendor/twig/twig/src/ExpressionPa in /system/storage/vendor/twig/twig/src/TokenStream.php on line 76

Capture status | Complete
-- | --
Amount authorised | 38.00
Amount captured | 38.00
Amount refunded | 0.00

**Comment by faca5** [comment]
Additional error!

https://localhost/admin/index.php?route=extension/payment/pp_express/refund&user_token=RdtTAqYMVZFdeBYMRA8XidascSxaNFzR&transaction_id=5FM277099U301550R

Fatal error: Uncaught Twig\Error\SyntaxError: Unexpected token "string" ("name" expected) in "extension/payment/pp_express_refund.twig" at line 20. in /system/storage/vendor/twig/twig/src/TokenStream.php:76 Stack trace: 
#0 /system/storage/vendor/twig/twig/src/ExpressionParser.php(699): Twig\TokenStream->expect(5) 
#1 /system/storage/vendor/twig/twig/src/ExpressionParser.php(680): Twig\ExpressionParser->getTest(20) 
#2 /system/storage/vendor/twig/twig/src/ExpressionParser.php(674): Twig\ExpressionParser->parseTestExpression(Object(Twig\Node\Expression\NameExpression)) 
#3 /system/storage/vendor/twig/twig/src/ExpressionParser.php(77): Twig\ExpressionParser->parseNotTestExpression(Object(Twig\Node\Expression\NameExpression)) 
#4 /system/storage/vendor/twig/twig/src/TokenParser/IfTokenParser.php(36): Twig\ExpressionParser->parseExpression() 
#5 /system/storag in /system/storage/vendor/twig/twig/src/TokenStream.php on line 76

**Comment by faca5** [comment]
Additional error!

https://localhost/admin/index.php?route=extension/payment/pp_express/doRefund&user_token=RdtTAqYMVZFdeBYMRA8XidascSxaNFzR

Notice: Undefined index: parent_id in /admin/model/extension/payment/pp_express.php on line 86Warning: Cannot modify header information - headers already sent by (output started at /admin/controller/startup/error.php:34) in /vqmod/vqcache/vq2-system_library_response.php on line 36

**Comment by faca5** [comment]
Hello.

We got another problem.

Error:
We're sorry
Things don't appear to be working at the moment

We have manually changed from "sandbox" in "live".

File:
view/theme/default/template/extension/payment/pp_express.twig

Code:
<script type="text/javascript"></script>

Code:
<script type="text/javascript"></script>

**Comment by ADDCreative** [comment]
Your code examples are the same or empty.

**Comment by faca5** [comment]
Code has been added.

**Comment by chongshengdz** [comment]
https://github.com/opencart/opencart/pull/8164
just check the above link, the issue was resolved some time ago.
