### ISSUE TITLE
Fedex Error

### ISSUE THREAD

**Issue by baltechies** [opencart/opencart#8611]
**What version of OpenCart are you reporting this for?**
3.0.3.6

**Describe the bug**
<b>Warning</b>: in_array() expects parameter 2 to be array, null given in <b>/var/www/html/catalog/model/extension/shipping/fedex.php</b> on line <b>180</b

What section does it affect?
Shipping methods not working.

**To Reproduce**
1. Setup shipping method
2. Add product to cart and Get Quote.

**Expected behavior**
Should be estimated cost for shipping methods

**Comment by WebkulOpencart** [comment]
issues resolved so clo
