### ISSUE TITLE
[Feature Request] LDAP/AD (ActiveDirectory) authentication for all things (clients, admins, stores, etc)

### ISSUE THREAD

**Issue by BloodyIron** [opencart/opencart#8612]
Can we please get LDAP/AD (ActiveDirectory) authentication mainlined into openCart? As in, for customers/clients, admins, stores, everything.

The only way to do it now is with a single plugin, and the developer stopped responding/updating it many many months ago. Something really sour to see for a paid plugin. It also looks to be rather short on features too, such as LDAPS or even extending to all user authentication.

It really is about time this aspect get mainlined into openCart. So can we please get this added to a roadmap and started? I know many people really would use this immediately.

**Comment by TheRealDJ** [comment]
Considering the times, maybe also add MFA. Just a thought.

**Comment by danielkerr** [comment]
MFA will be added after the next release.  as for LDAPS. im not sure its required.

**Comment by BloodyIron** [comment]
I didn't ask for MFA, I asked for LDAP/AD integration. Why are you closing my feature request regarding something completely irrelevant to what I asked for? :/ I will not be implementing openCart if I cannot integrate it with LDAP/AD and since the only way to do that is abandoned and incomplete, I need this to be mainlined and taken seriously. Otherwise I simply will simply go elsewhere. And trust me, there will be plenty of others too that require this integration.

**Comment by BloodyIron** [comment]
> Considering the times, maybe also add MFA. Just a thought.

Also I'd like to point out that @TheRealDJ proposed _ADDING_ it, not replacing LDAP/AD in the request.
