### ISSUE TITLE
OpenCart v3.0.3.6 | Installation error during local installation on OS X Catalina

### ISSUE THREAD

**Issue by avmax** [opencart/opencart#8618]
Latest commit: 7bfca481664fa2cde0ba11776bf23c569abeba9e

**To Reproduce**
1. Do linux install from here: [](https://github.com/opencart/opencart/blob/master/INSTALL.md)
2. Open http://localhost/opencart/install/index.php

**Actual behavior**
Twig does not render content after opencart installation: https://prnt.sc/urpnt6

**Expected behavior**
It renders correctly: https://prnt.sc/urpn62

**Server / Test environment (please complete the following information):**
 - Local
 - Mac OS Catalina 10.15.4
 - PHP 7.4.10
 - Apache/2.4.46
 - Chrome 85.0.4183.121

**Comment by straightlight** [comment]
Not sure why my commit has been addressed regarding this issue. The install folder has no dependency of the validateController method from the Engine.

**Comment by danielkerr** [comment]
validateController has been removed. it will return an exception if controller does not exist.

**Comment by danielkerr** [comment]
should be fixed now.
