### ISSUE TITLE
Header - Logged bar

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#8619]
Please fix header in admin.

Version:
3.0.3.6

File:
admin/view/template/common/header.twig

from
`<a href="#" id="button-menu" class="hidden-md hidden-lg"><span class="fa fa-bars"></span></a>{% if logged %}`

to
`{% if logged %}<a href="#" id="button-menu" class="hidden-md hidden-lg"><span class="fa fa-bars"></span></a>`

**Comment by ADDCreative** [comment]
Your from and to are the same.

**Comment by faca5** [comment]
Updated!

**Comment by WebkulOpencart** [comment]
Fixed this issue
