### ISSUE TITLE
Admin user permission and store management issue

### ISSUE THREAD

**Issue by hkulekci** [opencart/opencart#863]
Hi, 

I want to create a new permission type to allow users to manage only specified manufacturers and/or categories in core opencart source. What do you think about it?

**Comment by shaikmabusubhani** [comment]
Hi Daniel,

i have done my open cart project .but how can i give the customhouses to put product  in admin panel in seperately

**Comment by shaikmabusubhani** [comment]
please give me the reply..

**Comment by danielkerr** [comment]
its called multi vendor. serarch the extension store for it. very popular extension.

**Comment by shaikmabusubhani** [comment]
that Means

**Comment by shaikmabusubhani** [comment]
can you please give me the any search link how to setup
