### ISSUE TITLE
Dependency files are missing from the Vendor folder in the 3.0.x.x_Maintenance branch

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#8632]
Dependency files are missing from the Vendor folder in the 3.0.x.x_Maintenance branch

**Comment by condor2** [comment]
Because composer need to be updated...
Klarna should be removed because is deprecated.

`{
	"name": "opencart/opencart",
    "type": "project",
    "description": "OpenCart",
    "keywords": ["opencart", "ecommerce", "framework", "opensource"],
    "homepage": "http://www.opencart.com",
    "license": "GPL-3.0+",
    "config": {
        "vendor-dir": "./upload/system/storage/vendor/"
    },
    "require": {
        "cardinity/cardinity-sdk-php": "v2.1.0",
        "braintree/braintree_php" : "5.3.1",
        "scssphp/scssphp": "1.1.1",
        "divido/divido-php": "v1.15-stable",
        "php": ">=7.3.0",
        "twig/twig": "^2.4.8",
        "zoujingli/wechat-php-sdk": ">=1.3.18"
    }
}`

**Comment by straightlight** [comment]
So is cardinity and divido (Wechat?)

**Comment by danielkerr** [comment]
u need to add them using composer then zip up the finished version with the dependency files in.

**Comment by danielkerr** [comment]
look how its setup on the release page

https://github.com/opencart/opencart/releases

**Comment by prabhatkumaroc082** [comment]
@straightlight please check #8986 once

**Comment by WebkulOpencart** [comment]
As Discussed with the @danielkerr the dependency files will be installed using the composer.
So, please follow the below blog to install the same.
[https://webkul.com/blog/how-to-install-opencart-in-3-0-6-0-version/](https://webkul.com/blog/how-to-install-opencart-in-3-0-6-0-version/)
