### ISSUE TITLE
OpenCart API orders rest/rpc endpoints

### ISSUE THREAD

**Issue by mlinuxgada** [opencart/opencart#8639]
Looking now at the opencart api docs: http://docs.opencart.com/en-gb/system/users/api/ and cant quite find the orders api related functionality. There is just basic order create/edit/delete/info for the current session.

There is no way atm to get a list with orders, eventually filter that by order status or anything.

**Comment by straightlight** [comment]
Admin > Reports > Dropdown menu do show the sales reports based on the order statuses.

**Comment by mehov** [comment]
Linked: #5423
