### ISSUE TITLE
Security - MySQL show password

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#8654]
When MySQL server is down for any reason, it shows MySQL password. 

Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /system/library/db/mysqli.php on line 7Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /system/library/db/mysqli.php on line 10Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /system/library/db/mysqli.php on line 10
Fatal error: Uncaught Exception: Error: <br />Error No: in /system/library/db/mysqli.php:10 Stack trace: 
#0 /system/library/db.php(31): DB\MySQLi->__construct('localhost', 'xxxx', 'xxxx', 'xxxx', '3306') 
#1 /system/framework.php(80): DB->__construct('mysqli', 'localhost', 'xxxxx', 'xxxx', 'xxxx', '3306') 
#2 /vqmod/vqcache/vq2-system_startup.php(104): require_once('/p...') 
#3 /index.php(23): start('catalog') 
#4 {main} thrown in /system/library/db/mysqli.php on line 10

**Comment by BuslikDrev** [comment]
system/framework.php
Найти:
`	if ($config->get('error_display')) {
		echo '<b>' . $error . '</b>: ' . $message . ' in <b>' . $file . '</b> on line <b>' . $line . '</b>';
	}`

Заменить на:
`	if ($config->get('error_display')) {
		if (strpos($message, $config->get('db_username')) !== false) {
			$message = 'База легла поспать!';
			error_reporting(0);
		}
		echo '<b>' . $error . '</b>: ' . $message . ' in <b>' . $file . '</b> on line <b>' . $line . '</b>';
	} else {
		error_reporting(0);
	}`

system/config/default.php
Найти:
`$_['error_display']        = true;`
Заменить на:
`$_['error_display']        = false;`

**Comment by faca5** [comment]
Thank you.

**Comment by WebkulOpencart** [comment]
@faca5 I will create a PR for the same after retesting all the case on my end.

**Comment by faca5** [comment]
I think this error appear on one of the v2 version, then it was fixed and now again appear as "default" error which it is not great for end users which don't set "custom config file". Security must be on first place. Thank you.

**Comment by faca5** [comment]
I have changed "localhost" to "localhost123" in "config.php" to reproduce error.

Then I set value in system config:
// Error
$_['error_display']        = false;
$_['error_log']            = false;
$_['error_filename']       = 'error.log';

Error still show password:
Fatal error: Uncaught Exception: Error: <br />Error No: in /system/library/db/mysqli.php:10 Stack trace: 
#0 /system/library/db.php(31): DB\MySQLi->__construct('*****************', '*****************', '*****************', '*****************', '*****************') 
#1 /system/framework.php(80): DB->__construct('mysqli', '*****************', '*****************', '*****************', '*****************', '*****************') 
#2 /vqmod/vqcache/vq2-system_startup.php(104): require_once('/p...') 
#3 /index.php(23): start('catalog') 
#4 {main} thrown in /system/library/db/mysqli.php on line 10

**Comment by faca5** [comment]
I have removed lines with error:
/system/library/db/mysqli.php
/system/framework.php

Error still insist.

**Comment by BuslikDrev** [comment]
> I have removed lines with error:
> /system/library/db/mysqli.php
> /system/framework.php
> 
> Error still insist.

Вы можете после error_reporting(0); добавить exit();
Тогда 100% дело не дойдёт до этой ошибки.

**Comment by ADDCreative** [comment]
Looks like a badly configured server. You need to set ```display_errors = Off``` in your php.ini.

**Comment by osworx** [comment]
> 
> 
> Looks like a badly configured server. You need to set `display_errors = Off` in your php.ini.

Not everybody can handle a server (while too many think they can!).
If this setting is On, it should also not display this message.

**Comment by ADDCreative** [comment]
It's not the message that is the problem. It's the PHP stack trace. Which was changed here. https://github.com/opencart/opencart/commit/55741524bef2836740e2e1868dc15f00b07a69d9
But now removed. https://github.com/opencart/opencart/commit/1095b39dae1ed8e1ea7351353a346ded916b1425#diff-d1ba578f44c95086346f44768a443dba

PHP 7.4 has an extra option for this as well.
https://www.php.net/manual/en/migration74.other-changes.php#migration74.other-changes.ini

**Comment by danielkerr** [comment]
go to the config/default.php and change error_display to false

**Comment by danielkerr** [comment]
but yes this is an issue

**Comment by ADDCreative** [comment]
Changing error_display to false in config/default.php, will not help if the exception_handler is not set before connecting to the database.

**Comment by danielkerr** [comment]
Changing a value in the default config file will stop this. Also setting up.ini to not show errors. Any one want to write a guide about settings that should be changed when going to a live site.

**Comment by osworx** [comment]
Basically it should be possible, that "non-technicians" and people who want "only" to operate a Webshop (the majority), not be contrained to edit any file.
What if there goes something wrong?
Or - as can be seen so many times in the past - as "Editor" MS-Word is used?

So, defning such in the asministration (backend) should be possible without eding any file.

Or, the base settings have to be that way, that nothing is displayed.
But is someone wants, and have the knowledge, he can do it by editing what Daniel suggests.

**Comment by danielkerr** [comment]
im leaving it as it is and closing the topic. i can not be responsible for people without experience.  if i disable display errors then im going to get a lot of complaints people are seeing a blank page when any small error appears.

**Comment by BuslikDrev** [comment]
> im leaving it as it is and closing the topic. i can not be responsible for people without experience. if i disable display errors then im going to get a lot of complaints people are seeing a blank page when any small error appears.

Make a blank page when mysql data is public.

**Comment by danielkerr** [comment]
ok fixed.

**Comment by ADDCreative** [comment]
The other database adaptors will likely have the same issue.

https://github.com/opencart/opencart/blob/ae76a611d4e414183b5984a996f53fce11974082/upload/system/library/db/pdo.php#L11

https://github.com/opencart/opencart/blob/ae76a611d4e414183b5984a996f53fce11974082/upload/system/library/db/pgsql.php#L10

**Comment by danielkerr** [comment]
fixed
