### ISSUE TITLE
Additional Alert Mail problem

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#8659]
**What version of OpenCart are you reporting this for?**
3.0.3.x

**Describe the bug**
Enter in settings default store under mail in the field Additional Alert Mail 
more than 1 email address (separated by comma , ) and activate by order.
Then make an order.
Only the 1st email address is getting an alert mail the 2nd and following are getting nothing.
(Mail to customer and shop/store is OK)

**Expected behavior**
It is expected that all email addresses get an alert mail.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? web server
 - Operating system Linux
 - PHP version 7.3

**Comment by Aqib-Webkul** [comment]
I have checked and found no such issue. I have added emails in Additional Alert Mail like this demo@webkul.com,oc@webkul.com
and I am receiving the email for both on customer registration and on order placed.

**Comment by pemaier** [comment]
After your message I checked again with your sample (but my addresses). And you are right **it is working**. 
I was using the addresses in this form with a blank. demo@webkul.com, oc@webkul.com
I suggest that this blank should be considered and filtered from the string. May I'm the only one but I think normal users use a blank because it is a way to have a visual separation of the addresses. Sorry for my mistake.

**Comment by osworx** [comment]
After this line: https://github.com/opencart/opencart/blob/535e58e15dc0e7642607f73a93c04d90706b3fa4/upload/catalog/controller/mail/order.php#L465
a simple `trim(...)` would solve such bugs (I call it a "bug", because a space between is added very quickly!

```
foreach ($emails as $email) {
				$email = trim($email);
				if ($email && filter_var($email, FILTER_VALIDATE_EMAIL)) {
