### ISSUE TITLE
Return can be generated without existence of order & customer

### ISSUE THREAD

**Issue by Webkul-Opencart** [opencart/opencart#8660]
**What version of OpenCart are you reporting this for?**
Test Environment--
-- opencart version: Version 3.0.3.6

**Describe the bug**
1. Order return is being generated from the front end & the admin end as well(sales > returns section), even there is no order/customer exists.
2. Multiple return can be made for the same order at the both end(admin or customer).

**To Reproduce**
1. Go to front end > returns in the footer section or account menu
2. fill all the details & click on the submit button(return has been generated)
3. Switch to admin end, sales > returns section
4. you can easily find the return generated with the same details even there is no order generation for that particular return & even no customer exists.
Note: same return can be generated from the admin end

**Expected behavior**
1. There must be an auto fill selection for the order id at the time of return.
2. Also a check must be there that only one return can be made for the same order(i.e order id 1) if the previous return is in process for the same order.

**Screenshots / Screen recordings**
 recording-- 
1. issue1
[return.mp4.zip](https://github.com/opencart/opencart/files/5353299/return.mp4.zip)
 2. Issue2 
[multiplereturn.mp4.zip](https://github.com/opencart/opencart/files/5353335/multiplereturn.mp4.zip)

**Server / Test environment (please complete the following information):**
opencart version: 3.0.3.6
operating system: Ubuntu 16.04 LTS
PHP version-- 7.4.11
browser/browser version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by danielkerr** [comment]
yes because the store owner has to confirm the return. if no order then set status to denied
