### ISSUE TITLE
All the "End Date" fields related to form pages are accepting the backdates or previous dates from "Start Date".

### ISSUE THREAD

**Issue by Prashi9** [opencart/opencart#8662]
**What version of OpenCart are you reporting this for?**
-- opencart version: Version 3.0.3.6

**Describe the bug**
At the backend, the admin able to submit any form with the backdates or previous dates from the "Start Date".

**To Reproduce**
1. Go to Add new Coupon form page.
2. Click on the Add New Coupon button.
3. Fill the backdate in the "Date End field from "date start".
4. Form successfully saved with the wrong "Date End" value.

**Expected behavior**
In this case,must be appeared a warning regarding wrong date details.

**Screenshots / Screen recordings**

![oc_date](https://user-images.githubusercontent.com/50448674/95573781-9b571d00-0a49-11eb-9067-f88ab849c27c.png)

**Server / Test environment (please complete the following information):**
opencart version: 3.0.3.6
operating system: Ubuntu 16.04 LTS
PHP version-- 7.4.11
browser/browser version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by danielkerr** [comment]
and???? just means the coupon will never work.

**Comment by danielkerr** [comment]
u are supposed to be getting a maintenance branch release ready not making up issues.
