### ISSUE TITLE
Code Error: on customer address on putting random id in the URL

### ISSUE THREAD

**Issue by Webkul-Opencart** [opencart/opencart#8665]
**What version of OpenCart are you reporting this for?**
Test Environment--
-- opencart version: Version 3.0.3.6

**Describe the bug**
A clear and concise description of what the bug is
at the customer end, when apply the random address id which doesn't exists then it is showing the code error.

**To Reproduce**
1. Go to customer end > my account > address book menu
2. Click on edit button of the address
3. Input random address id in the URL
4. It shows the code error

**Expected behavior**
It must show any notification page like address doesn't exists.
**Screenshots / Screen recordings**
1. 
![Selection_250](https://user-images.githubusercontent.com/42890212/95583613-0872ae80-0a5a-11eb-9672-8513be95377d.png)
2. 
![Selection_249](https://user-images.githubusercontent.com/42890212/95583652-132d4380-0a5a-11eb-96ba-a04d2a62ae05.png)

**Server / Test environment (please complete the following information):**
 opencart version: 3.0.3.6
operating system: Ubuntu 16.04 LTS
PHP version-- 7.4.11
browser/browser version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by condor2** [comment]
Make a test with this commit
https://github.com/opencart/opencart/pull/8666/commits/a3e0e4f710e871d46056b1c57d7d15dab96eaf56

**Comment by Webkul-Opencart** [comment]
@danielkerr please check this one issue too as this one also from the maintenance branch-- https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
