### ISSUE TITLE
[Master Branch] Cookie popup is broken

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#8668]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
Popup( modal ) cookies is broken

**Screenshots / Screen recordings**
![Screenshot_2020-10-09_17-34-32](https://user-images.githubusercontent.com/14251939/95596370-fabb2a00-0a55-11eb-942c-8866afd2127b.png)

**Comment by condor2** [comment]
Reported also in december 2019.

https://github.com/opencart/opencart/issues/7784

**Comment by danielkerr** [comment]
fixed recently.
