### ISSUE TITLE
Code error: when login with direct link of password

### ISSUE THREAD

**Issue by virendra695** [opencart/opencart#8674]
**What version of OpenCart are you reporting this for?**
Test Environment--
-- opencart version: Version 3.0.3.6

**Describe the bug**
A clear and concise description of what the bug is
-At the customer end, when customer login  with a direct link of password, then getting code error

**To Reproduce**
1. Go to 'Customer end>login with valid credentials'
2. Click on 'Password menu'
3. Copy the password page URL 
4. Run the URL 'in other browser or incognito Window'
5. Login Page>login with valid credentials
4. See an error

**Expected behavior**
-- Code error must not show on page when user redirecting to the password page after login

**Screenshots / Screen recordings**
![Screenshot (1)](https://user-images.githubusercontent.com/51983890/95610387-e1c66f00-0a7d-11eb-9745-3cd2af650bb7.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system: Ubuntu 16.04 LTS
 - PHP version:   7.4.11
 - Apache version
 - Browser(s) tested with: Google Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

**Comment by WebkulOpencart** [comment]
issue resolved so closing this issue
