### ISSUE TITLE
Master branch - Config file not empty - contains config data 

### ISSUE THREAD

**Issue by Hackej** [opencart/opencart#8680]
**What version of OpenCart are you reporting this for?**
Latest Gthub master

**Describe the bug**
Config file "config-dist.php" is not empty, it contains config data. 
Installation error.

**To Reproduce**
Download and open config-dist.php and have a look!

**Expected behavior**
Should be empty.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by straightlight** [comment]
Confirmed from the catalog-end side: https://github.com/opencart/opencart/blob/master/upload/config-dist.php .

**Comment by condor2** [comment]
I write a comment on the commit long time ago..but I think @danielkerr forgot about this :)

**Comment by danielkerr** [comment]
cleared it
