### ISSUE TITLE
branch[3.0.x.x_Maintenance]: when click on the pagination at the customer end for downloads then no details showing further

### ISSUE THREAD

**Issue by Webkul-Opencart** [opencart/opencart#8685]
**What version of OpenCart are you reporting this for?**
Test Environment--
-- opencart version: Version 3.0.3.6

**Describe the bug**
At the customer end at the downloads section, when click on the pagination then it is showing no details further at the page no.2, even it is showing 24 items in the list(at pagination).

**To Reproduce**
1. Go to 'Downloads' section at the customer end
2. Click on 'pagination'
3. then it is not showing any downloads at the page no. 2

**Expected behavior**
It must show the download list at the second page.

**Screenshots / Screen recordings**

[downloads.mp4.zip](https://github.com/opencart/opencart/files/5360715/downloads.mp4.zip)

**Server / Test environment (please complete the following information):**
opencart version: 3.0.3.6
operating system: Ubuntu 16.04 LTS
PHP version-- 7.4.11
browser/browser version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by straightlight** [comment]
I believe this issue has already been fixed on the master branch.

**Comment by WebkulOpencart** [comment]
issue confirmed, 

Step to reproduce the same issue
Assign the same download to multiple products and brought all the product multiple time in a single order

**Comment by WebkulOpencart** [comment]
issue resolved and merged the code so closing this issue.
