### ISSUE TITLE
Modification theme

### ISSUE THREAD

**Issue by BuslikDrev** [opencart/opencart#8687]
https://github.com/opencart/opencart/wiki/Modification-System

Hello, if there are no modifiers, how do you plan to make changes to the templates? Programmers will have to do something like this:
   

    public function event(&$route, &$data, &$output) {
		if ($route == 'common/footer') {
			$output = str_replace(array('</body>'), array('{{ my_module_parametr }}' . "\r\n" . '</body>'), $output);
		}
    }

They can install vqmod.

**Comment by stalker780** [comment]
OCMOD is dead, long live VQMOD 😆

**Comment by chulcha** [comment]
This is not the biggest problem
Problems start when you need to add some field to the database table.

Example
```

	public function getProductDescriptions($product_id) {
		$product_description_data = array();

		$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "product_description WHERE product_id = '" . (int)$product_id . "'");

		foreach ($query->rows as $result) {
			$product_description_data[$result['language_id']] = array(
				'name'             => $result['name'],
				'description'      => $result['description'],
				'meta_title'       => $result['meta_title'],
				'meta_description' => $result['meta_description'],
				'meta_keyword'     => $result['meta_keyword'],
				'tag'              => $result['tag']
			);
		}

		return $product_description_data;

```

> long live VQMOD

**Comment by BuslikDrev** [comment]
> Это не самая большая проблема.
> Проблемы начинаются, когда вам нужно добавить какое-то поле в таблицу базы данных.
> 
> пример
> 
> ```
> 
> 	public function getProductDescriptions($product_id) {
> 		$product_description_data = array();
> 
> 		$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "product_description WHERE product_id = '" . (int)$product_id . "'");
> 
> 		foreach ($query->rows as $result) {
> 			$product_description_data[$result['language_id']] = array(
> 				'name'             => $result['name'],
> 				'description'      => $result['description'],
> 				'meta_title'       => $result['meta_title'],
> 				'meta_description' => $result['meta_description'],
> 				'meta_keyword'     => $result['meta_keyword'],
> 				'tag'              => $result['tag']
> 			);
> 		}
> 
> 		return $product_description_data;
> ```
> 
> > да здравствует VQMOD

**Comment by BuslikDrev** [comment]
> This is not the biggest problem
> Problems start when you need to add some field to the database table.
> 
> Example
> 
> ```
> 
> 	public function getProductDescriptions($product_id) {
> 		$product_description_data = array();
> 
> 		$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "product_description WHERE product_id = '" . (int)$product_id . "'");
> 
> 		foreach ($query->rows as $result) {
> 			$product_description_data[$result['language_id']] = array(
> 				'name'             => $result['name'],
> 				'description'      => $result['description'],
> 				'meta_title'       => $result['meta_title'],
> 				'meta_description' => $result['meta_description'],
> 				'meta_keyword'     => $result['meta_keyword'],
> 				'tag'              => $result['tag']
> 			);
> 		}
> 
> 		return $product_description_data;
> ```
> 
> > long live VQMOD

Something like this they will need to do:
```
	public function getProductDescriptions($product_id) {
		$product_description_data = array();

		$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "product_description WHERE product_id = '" . (int)$product_id . "'");

		foreach ($query->rows as $result) {
			$product_description_data[$result['language_id']] = $result;
		}

		return $product_description_data;
```

**Comment by stalker780** [comment]
> > This is not the biggest problem
> > Problems start when you need to add some field to the database table.
> > Example
> > ```
> > 
> > 	public function getProductDescriptions($product_id) {
> > 		$product_description_data = array();
> > 
> > 		$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "product_description WHERE product_id = '" . (int)$product_id . "'");
> > 
> > 		foreach ($query->rows as $result) {
> > 			$product_description_data[$result['language_id']] = array(
> > 				'name'             => $result['name'],
> > 				'description'      => $result['description'],
> > 				'meta_title'       => $result['meta_title'],
> > 				'meta_description' => $result['meta_description'],
> > 				'meta_keyword'     => $result['meta_keyword'],
> > 				'tag'              => $result['tag']
> > 			);
> > 		}
> > 
> > 		return $product_description_data;
> > ```
> > 
> > 
> > > long live VQMOD
> 
> Something like this they will need to do:
> 
> ```
> 	public function getProductDescriptions($product_id) {
> 		$product_description_data = array();
> 
> 		$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "product_description WHERE product_id = '" . (int)$product_id . "'");
> 
> 		foreach ($query->rows as $result) {
> 			$product_description_data[$result['language_id']] = $result;
> 		}
> 
> 		return $product_description_data;
> ```

This will not help, if you need to join a new custom table.
OC needs a different SQL query system with SQL modifier. Where extensions can modify deault selectors and updators, by changing fields, joins, wheres and etc.

**Comment by chulcha** [comment]
@stalker780  need EVENT on 

> SQL query system with SQL modifier

**Comment by rsuchovsky** [comment]
> OCMOD is dead, long live VQMOD 😆
> 
> Why don't Daniel just embed it in OC?
> 
> Also, in my opinion, this should be called OC 4.0 but not OC 3.1.
> Cause it is absolutely different from OC 3.0. Different files structure, different bootstrap, extensions structure and much more.
> All extensions and themes, developed for previous OC versions, became incompatible with it.
> There are even more changes, than between OC2.3 and 3.0.

Yes diferent bootstrap, in my opinion it's a pity that bootstrap 4, bootstrap 5 will be out soon. They will release a new OC version and bootstrap 5 will be released in a few months. So again we will work under the old version of bootstrap.

**Comment by danielkerr** [comment]
i can probably put it back but and have a new directory under extensions just to generate files there.

**Comment by NancySavage** [comment]
What about stylesheet modifications? Are there plans to implement that into the theme modification section? When I see a section called "theme editor" in the admin section the first thing that comes to mind are minor things like changing theme colors or fonts. Seems like we'll still have to resort to creating and linking custom css files manually.

**Comment by osworx** [comment]
> 
> 
> What about stylesheet modifications? Are there plans to implement that into the theme modification section? When I see a section called "theme editor" in the admin section the first thing that comes to mind are minor things like changing theme colors or fonts. Seems like we'll still have to resort to creating and linking custom css files manually unless I am missing something here.

I do not would recommend editing the original files - at least the whole store is quickly down.
More a possibility to **add new definitions (css & js) either to the header or footer**.
With such overriding is also possible.
And those "hardcoder" can still edit the original files.

**Comment by danielkerr** [comment]
yes i will add sass files there after this next release.

**Comment by danielkerr** [comment]
u can use the override system to replace the route for a template file.

so account/account can become extension/user_extension/account/account

so to code would be 

$route = extension/user_extension/ . $route

in the event system

**Comment by BuslikDrev** [comment]
> Вы можете использовать систему переопределения для замены маршрута для файла шаблона.
> поэтому учетная запись / учетная запись может стать расширением / user_extension / account / account
> так что код будет
> $ route = extension / user_extension /. $ route
> в системе событий

The main thing is to test the engine with a large number of events for loading speed.
There is still a lot of work to be done so that you don't have to execute a lot of events and you can make changes anywhere using your module's controller.

**Comment by chulcha** [comment]
You will also need functionality to manage or edit events, for example, the order of application

Also, a project can use several modules or extensions from several developers. Then what could be user_extension.  If I understood correctly the purpose of user_extension

**Comment by BuslikDrev** [comment]
> i can probably put it back but and have a new directory under extensions just to generate files there.

Have you already been offered to implement this? https://github.com/askello/opencart-query-builder
The main thing is that when working with your module, you can change standard queries.

**Comment by MikhailShemelin** [comment]
> > u can use the override system to replace the route for a template file.
> > so account/account can become extension/user_extension/account/account
> > so to code would be
> > $route = extension/user_extension/ . $route
> > in the event system
> 
> The main thing is to test the engine with a large number of events for loading speed.
> There is still a lot of work to be done so that you don't have to execute a lot of events and you can make changes anywhere using your module's controller.

I think that one the biggest things is debugging.

If several modifications (OCMod) alternate/change the same file/procedure, it is possible to open the final version of the file, read the code and understand what is going on there.
 
How to do something similar with alternating/changing by events?

**Comment by danielkerr** [comment]
events should show the errors where they should be so u are not looking into cached vqmod files.

i have been testing it and it works great.  just requires different thinking.

so u could have an event to change the theme

$route = extension/user_extension/ . $route

if its for specific using different template files you can add:

$replace = ['account/account'];

if (in_array($route, $replace)) {
  $route = extension/user_extension/ . $route;
}
