### ISSUE TITLE
Step 3 permission error

### ISSUE THREAD

**Issue by chanakaDe** [opencart/opencart#8691]
Guys,
I'm using OC 3 and in the step 3, I'm getting this error:

`Warning: fopen(/var/www/html/system/storage/session//sess_a9e804a80bb3d0e790fbbb88cf): failed to open stream: Permission denied in /var/www/html/system/library/session/file.php on line 29Warning: flock() expects parameter 1 to be resource, bool given in /var/www/html/system/library/session/file.php on line 31Warning: fwrite() expects parameter 1 to be resource, bool given in /var/www/html/system/library/session/file.php on line 33Warning: fflush() expects parameter 1 to be resource, bool given in /var/www/html/system/library/session/file.php on line 35Warning: flock() expects parameter 1 to be resource, bool given in /var/www/html/system/library/session/file.php on line 37Warning: fclose() expects parameter 1 to be resource, bool given in /var/www/html/system/library/session/file.php on line 39`

And also there were many permission errors and I fixed using chmod 0777 status. 
For example, writable permission asked for /var/www/html/image folder. Is that secure?

What is the fix for above error?

**Comment by syslogic** [comment]
`chmod 0777` is barely a proper fix. What does `ls -la /var/www/html/system/storage` say?

**Comment by chanakaDe** [comment]
@syslogic Please check the attached screenshot. This is the error. Earlier there was many permisison issues and using ´chmod 0777´, I fixed them. But why there is no proper documentation for this from OpenCart? Looks like this permission issue is common and many people getting. Can you please advise me a proper solution ? 

Thank you in advance. 

![Screenshot_2020-10-13 License agreement](https://user-images.githubusercontent.com/7803591/95823051-40654480-0d2d-11eb-9d98-49c3fae88b8d.png)

**Comment by chanakaDe** [comment]
@syslogic 
This is the output you asked:
total 36
drwxrwxrwx  9 ubuntu ubuntu 4096 Oct 12 22:30 .
drwxrwxr-x  7 ubuntu ubuntu 4096 Oct 12 22:30 ..
drwxrwxrwx  3 ubuntu ubuntu 4096 Oct 12 22:56 cache
drwxrwxrwx  2 ubuntu ubuntu 4096 Oct 12 22:30 download
drwxrwxrwx  2 ubuntu ubuntu 4096 Oct 12 22:56 logs
drwxrwxrwx  2 ubuntu ubuntu 4096 Oct 12 22:30 modification
drwxrwxr-x  2 ubuntu ubuntu 4096 Oct 12 22:30 session
drwxrwxrwx  2 ubuntu ubuntu 4096 Oct 12 22:30 upload
drwxrwxr-x 15 ubuntu ubuntu 4096 Oct 12 22:32 vendor

**Comment by syslogic** [comment]
This is not a permission issue, but rather an ownership issue. `0777` is a bad practice, because it's world-writable; just send a `PUT` request to see what is possible. Not certain about the web-server's username in Ubuntu, but this should be `chown -R www-data:www-data /var/www/html` to take ownership of the whole web-root - then you can secure the installation further by taking these excessive write permissions away again. This isn't too OpenCart specific, but the same for quite any PHP application.

**Comment by chanakaDe** [comment]
@syslogic  Thank you so much for the advise. I will try this in a little while and will let you know the output. Need some time to implement this.

**Comment by syslogic** [comment]
And there **is** a documentation: http://docs.opencart.com/en-gb/administration/security/

**Comment by chanakaDe** [comment]
@syslogic  I did that and permission issue is gone.
But at the step 3, I'm getting an error. 
http://<ip-address>/install/index.php?route=install/step_3 -> 500 server error. 
Any idea? 
OR can you please recommend me a easy and standard way to install OpenCart?

**Comment by condor2** [comment]
I think your server configuration has some issue because when you upload all files should be chmod 644, folders 755 and in some cases 777.

**Comment by chanakaDe** [comment]
@condor2  But giving 777 to a root directory is a huge risk. No?

**Comment by condor2** [comment]
Isn't about root directory...
It is about your LAMP configuration...

**Comment by chanakaDe** [comment]
Hmmm I see @condor2 . I will check about permissions and will let you know. Thank you for the advice so far,

**Comment by straightlight** [comment]
```/var/www/html/system/storage/session//```

Yes, this is what it's saying. There's two slashes at the end of the portion path instead of one; invalid path to where the installation can write into.

**Comment by chanakaDe** [comment]
@straightlight  Please tell me how can I fix that.

**Comment by chanakaDe** [comment]
@straightlight  It is OC 3.0.3.6 with AWS LightSail based ubuntu OS. (EC2 instance)

**Comment by straightlight** [comment]
See if the issue persists on a live server with, either, Fedora or Redhat Enterprise licensing instead of using light editions of OSes. Apache functions may different of slashes when being inside the public_html folder. On small occasions, it may occur as well outside of the public_html folder but, at this point, better to contact your host when that happens.

**Comment by chanakaDe** [comment]
@syslogic @straightlight @condor2  After many hard times and efforrs, I managed to install OpenCart 3.0.3.6 in my server and works well. Everything is perfect. Now I'm trying to install a free theme first and check it. 

This is the theme I'm planning to install. 
https://opencart.opencartworks.com/themes/so_ladaz/index.php?route=common/home

I have one more issue guys. I was trying to install the theme and 2 different sources give me 2 different sets of instructions. 

First set of instructions:
1. Download the theme you want to use. OpenCart theme files are compressed using .zip format. 
2. Extract the files in the .zip file on your local computer.
3. Upload the extracted folder and its contents to the public_html directory. 
4. Log in to OpenCart as the administrator.
5. On the left sidebar, click the OpenCart - Extensions icon icon, and then click Themes.
6. Locate your store, and then in the Action column, click the Edit (OpenCart - Edit icon) icon.
7. Under General, in the Theme Directory list box, select the new theme.
8. In the Status list box, select Enabled.
9. Click the Save (OpenCart - Save icon) icon. The new theme is now installed and activated.

And also in the theme instructions page says something different. 
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=30339&filter_category_id=1&filter_license=0&page=2

Can you please advise me what is the correct way? 

Thank you all in advance. :-)

**Comment by chanakaDe** [comment]
And I see the above mentioned theme is not compatible with our OC version. My version is 3.0.3.6. 
But the theme supports only these. Is that ok ? Should I try? 
3.0.0.0, 3.0.1.1, 3.0.1.2, 3.0.2.0, 3.1.0.0_b

**Comment by condor2** [comment]
If is compatible with 3.0.2.0 then should work just fine on 3.0.3.6.

**Comment by straightlight** [comment]
Regarding custom theme issues, please post on the Opencart forum. The main issue you reported about has been resolved on this commit.

**Comment by syslogic** [comment]
When it is an issue with the theme, this would be the actual support page:
https://www.opencart.com/index.php?route=support/seller&extension_id=30339
