### ISSUE TITLE
[Master Branch] seo url not working

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#8693]
all pages are link to homepage when turning on seo url rewrite.

**Comment by chongshengdz** [comment]
you need to improve htaccess file.
RewriteRule ^([^?]*) index.php [L,QSA] will redirect all seo url to homepage.

**Comment by chongshengdz** [comment]
https://www.ectransistors.com/opencartalpha/en-gb/iphone
what is wrong with my installation?
all seo urls lead to homepage.

**Comment by danijelGombac** [comment]
@danielkerr The problem is in system/framework.php

This code

```
// Route
if (!empty($request->get['route'])) {
	$action = new \Opencart\System\Engine\Action((string)$request->get['route']);
} else {
	$action = new \Opencart\System\Engine\Action($config->get('action_default'));
}
```

should be after "Pre Actions" because in "Pre Actions" are SeoUrl class where route is set.

**Comment by cgcmart** [comment]
SEO URL 404 not found error.

Apache config file /etc/httpd/conf.modules.d/00-base.conf:
`LoadModule rewrite_module modules/mod_rewrite.so`

in doc root direction .htaccess:
set rewrite rule either
`RewriteRule ^([^?]*) index.php [L,QSA]`
or
`RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]`

has the same not found error.

**Comment by danielkerr** [comment]
its working agian
