### ISSUE TITLE
Language text issue

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#8697]
**What version of OpenCart are you reporting this for?**
4.0.0.0_b
**Describe the bug**
Install Master branch OpenCart and go to admin login page

[http://i.prntscr.com/82qQ1q-RSCuow4khzSVwCg.png](http://i.prntscr.com/82qQ1q-RSCuow4khzSVwCg.png)

**Comment by straightlight** [comment]
Ouch ...

**Comment by danielkerr** [comment]
fixed
