### ISSUE TITLE
Suggestions: branch[3.0.x.x_Maintenance]

### ISSUE THREAD

**Issue by Webkul-Opencart** [opencart/opencart#8698]
1. at the admin end, Marketing > Mail section
https://prnt.sc/uyyavu
2. at the admin end, extensions > modules > google hangouts section, tooltip not working[issue]
https://prnt.sc/uyybth
3. at the admin end, extensions > modules > store, need to add the tooltip
https://prnt.sc/uyyi8x

**Comment by condor2** [comment]
2. Because of this code

`<span data-toggle="tooltip" data-html="true" data-trigger="click" title="{{ help_code|escape('html') }}">`

**Comment by WebkulOpencart** [comment]
@condor2 this issue is due to the data-html="true" data-trigger="click"

**Comment by condor2** [comment]
Yes. I have read about data-html="true" bug. 
I think this way should be changed for all modules who have URL in language file...but users need to click for that...or in Google Hangouts changed like in Recaptcha

![Screenshot_2020-10-15_10-01-49](https://user-images.githubusercontent.com/14251939/96088028-7a6d4c80-0ecd-11eb-9ced-16fd19734dde.png)

**Comment by WebkulOpencart** [comment]
@condor2  I changed the tooltip to popover and the issue is resolved.
[https://github.com/opencart/opencart/pull/8702](https://github.com/opencart/opencart/pull/8702)

**Comment by condor2** [comment]
I saw.
You don't have Merge acces?

**Comment by WebkulOpencart** [comment]
@condor2 I am checking for the third point of this issue and will merge the code in sometime

**Comment by condor2** [comment]
I like more this way :)
![Screenshot_2020-10-15_10-14-02](https://user-images.githubusercontent.com/14251939/96089228-33805680-0ecf-11eb-864b-3cab1d8e3351.png)

**Comment by WebkulOpencart** [comment]
@condor2  no issue, I will make the changes for the same

**Comment by osworx** [comment]
> 
> 
> I like more this way :)
> ![Screenshot_2020-10-15_10-14-02](https://user-images.githubusercontent.com/14251939/96089228-33805680-0ecf-11eb-864b-3cab1d8e3351.png)

Doing it that way open doors for whatever !
Reason why not adding a complete script (part) like this way is, I have seen "Agencies" and Freelancer adding additionally bad stuff doing very bad things!
So, defining only really important things like keys is more sucre.

**Comment by condor2** [comment]
What complete script?

`<div class="alert alert-info"><i class="fa fa-info-circle"></i> {{ help_code }}</div>`

**Comment by osworx** [comment]
@condor2 Sorry, amybe my mistake, you have posted a screenshot with the help text abobve the textarea.
My comment was about that textearea field and the possibilities for everybody who has access to this item to add unsecure code.

But you wanted only to highlight the help text - correct?
Which btw. should be like your suggestion.

Beside this, there are many places in the backend where an "enhanced" help is badly missed!
If you have time, install my German Language Package for OC 3.x and see that I have added there additionally many text the original English is missing!

**Comment by condor2** [comment]
No problem. My bad I din't crop only Help text :)
