### ISSUE TITLE
Branch[3.0.x.x_Maintenance]: at the product page, it is taking space below the footer when the cart value is more with products

### ISSUE THREAD

**Issue by Webkul-Opencart** [opencart/opencart#8701]
**What version of OpenCart are you reporting this for?**
Test Environment--
-- opencart version: Version 3.0.3.6

**Describe the bug**
When add to cart the product in bulk then at the product page it is showing the space below the footer.

**Expected behavior**
It must adjust the space above the footer section.

**Screenshots / Screen recordings**
![productpageissue](https://user-images.githubusercontent.com/42890212/96082236-78f55180-0ed8-11eb-959d-83a73fac9e82.png)

**Server / Test environment (please complete the following information):**
 opencart version: 3.0.3.6
operating system: Ubuntu 16.04 LTS
PHP version-- 7.4.11
browser/browser version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by webkul-dilip** [comment]
@straightlight, please check this issue and pull request

**Comment by webkul-dilip** [comment]
Now we have added the scroll in the cart, @straightlight please check so we can merge the code in mantainance branch
