### ISSUE TITLE
Suggestion: when applying special symbols in reward then showing successful message, there should display error message

### ISSUE THREAD

**Issue by virendra695** [opencart/opencart#8704]
**What version of OpenCart are you reporting this for?**
Test Environment--
-- opencart version: Version 3.0.3.6
--Branch: 3.0.x.x_Maintenance

**Describe the bug**
A clear and concise description of what the bug is when applying the special symbol in the reward then still showing the success message.

**To Reproduce**
1. Open the checkout page
2. Enter the special symbols !@#$%^&*() in the reward field
3. press on Appy button

1. Go to 'checkout page'
2. Enter "special Symbol !@#$%^&*()"
3. Click on 'Apply button'
4. still success message will display 

**Expected behavior**
-- There should display the error message

**Screenshots / Screen recordings**
![Screenshot (2)](https://user-images.githubusercontent.com/51983890/96097396-861d3b00-0eee-11eb-94b0-72f690fe69b6.png)

**Server / Test environment (please complete the following information):**
 - Operating system: Ubuntu 16.04 LTS
 - PHP version: 7.4.11
 - Browser(s) tested with: Google Chrome (Version 85.0.4183.121 (Official Build) (64-bit))
 - Opencart Version: 3.0.3.6

**Comment by ADDCreative** [comment]
It's not just those special symbols. If you enter a string it will pass the empty check then do a string comparison with the points values. It will be any string starting with a character with a decimal value below 49. For example, typing ```.0``` will also give the success message. Which could happen if you were trying to type ```30``` but hit the . key below 3.

The line that checks is here.
https://github.com/opencart/opencart/blob/7bfca481664fa2cde0ba11776bf23c569abeba9e/upload/extension/opencart/catalog/controller/total/reward.php#L47

Perhaps to catch all, assuming reward can be a float, which I'm not sure it should be.
```php
if (!isset($this->request->post['reward']) || !is_numeric($this->request->post['reward']) || ($this->request->post['reward'] <= 0)) {
```

Or for integers replace the is_numeric.
```php
!ctype_digit((string)$this->request->post['reward'])
```

**Comment by ADDCreative** [comment]
@WebkulOpencart This also looks to affect the master branch.
https://github.com/opencart/opencart/blob/ab11174fbfb818f3e047c2525142fb503844051f/upload/extension/opencart/catalog/controller/total/reward.php#L47

I would also check if the reward can be a decimal of has to be a integer. The use of abs with no typecast suggests that it could be decimal.
https://github.com/opencart/opencart/blob/ab11174fbfb818f3e047c2525142fb503844051f/upload/extension/opencart/catalog/controller/total/reward.php#L60

However, looking at the database schema. It's stored in the database as a integer.
https://github.com/opencart/opencart/blob/ab11174fbfb818f3e047c2525142fb503844051f/upload/system/helper/db_schema.php#L1623-L1626

**Comment by webkul-dilip** [comment]
https://github.com/opencart/opencart/pull/8831
