### ISSUE TITLE
[Master Branch] Missing confirm order button Checkout

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#8712]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
No confirm order button

**Screenshots / Screen recordings**
![Screenshot_2020-10-15_14-49-02](https://user-images.githubusercontent.com/14251939/96119499-bf0cde00-0ef5-11eb-9abe-bb812f1098b9.png)

**Additional context**
Possible missing some script from checkout.twig

**Comment by danielkerr** [comment]
fixed
