### ISSUE TITLE
[Master Branch] Translations are not sent via email on History/Transactions/Reward alert

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#8713]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
When you edit a customer and add Reward, History, Transaction language translation is not send in e-mail

**Expected behavior**
Translations should be shown in customer email

**Screenshots / Screen recordings**
![Screenshot_2020-10-15_15-15-45](https://user-images.githubusercontent.com/14251939/96121916-64758100-0ef9-11eb-95fc-55b44441633d.png)

**Comment by danielkerr** [comment]
they are now
