### ISSUE TITLE
Activity table not updating correctly on checkout when adding a new address

### ISSUE THREAD

**Issue by CymonSez** [opencart/opencart#8715]
**What version of OpenCart are you reporting this for?**
3.0.3.6 New install with no modifications

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
When checking out and registering a new account at the same time the oc_customer_activity table is updated with a new customer register but then when adding an address at the same time the customer_id entry is '0' and the data is '{"customer_id":null,"name":" "}' This seems to only happen when adding an address while during the checking process. If you register and then add the account from Address Book Entries page it seems to work fine. I have verified the activity table is correct

**To Reproduce**
1. Add an item to cart from any page
2. click on the cart in the header and select "checkout"
3. select register account and click continue
4. enter personal details and select delivery and billing are the same
5. click agree and continue to finish the checkout
6. log into the admin and view the activity dashboard panel

**Expected behavior**
Customers name should appear in the activity list.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app
![screenshot](https://user-images.githubusercontent.com/393551/96153895-104faa00-0ec3-11eb-82b2-860fa187ed81.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system windows 10
 - PHP version 7.3
 - Apache version 2.4.46
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Chrome, Firefox, Edge 
 - Version [e.g. 22] 86.0.4240.75, 81.0.2, 86.0.622.38

**Additional context**
I did search for this issue and found some results but they didnt address this particular issue and I did try the suggested fixes with the same results, This is my first time reporting so I hope I did this correctly, thanks

**Comment by WebkulOpencart** [comment]
@CymonSez Yes, this issue is exist
