### ISSUE TITLE
[Webpage - www.opencart.com]: No PIN is sent!

### ISSUE THREAD

**Issue by sotel** [opencart/opencart#8716]
**What version of OpenCart are you reporting this for?**
3.0.3.6

**Describe the bug**
I need a **PIN** after I logged into my account on www.opencart.com. The login is possible but the page did not send a PIN.

**To Reproduce**
1. Go to 'www.opencart.com'
2. Click on 'Login'
3. Wait for a PIN
4. Nothing arrives.

**Expected behavior**
The page should send a PIN in minutes.

**Screenshots / Screen recordings**
![Bildschirmfoto_2020-10-15_20-24-07](https://user-images.githubusercontent.com/107782/96170859-6ef94000-0f24-11eb-9e73-c01de3703d8a.png)

**Comment by straightlight** [comment]
Contact site support for those claims. Nothing to do with the master branch.

**Comment by danielkerr** [comment]
contact support with the email u used for the account. but if u get in u should receive an email. did u click the red reset pin button?

**Comment by danielkerr** [comment]
i sent a link to this post to my staff.
