### ISSUE TITLE
branch[3.0.x.x_Maintenance]: document link is not correct

### ISSUE THREAD

**Issue by Webkul-Opencart** [opencart/opencart#8741]
**What version of OpenCart are you reporting this for?**
Test Environment--
-- opencart version: Version 3.0.3.6

**Describe the bug**
at the admin end, extensions > payments > wechat pay, the link given below for the documentation is not correct or not working properly.

**Screenshots / Screen recordings**
![Screenshot27](https://user-images.githubusercontent.com/42890212/96220369-3c902700-0fa6-11eb-93f3-653ae84e6f45.png)

![Selection_262](https://user-images.githubusercontent.com/42890212/96220108-c2f83900-0fa5-11eb-8484-e2b277886085.png)

**Comment by webkul-dilip** [comment]
@danielkerr  Please check can we add this URL https://pay.weixin.qq.com/index.php/core/home/login Please suggest so we can add the URL.

**Comment by prabhatkumaroc082** [comment]
No issue found, the link is working.
