### ISSUE TITLE
[Master Branch] Mysqli Mess

### ISSUE THREAD

**Issue by Boorinio** [opencart/opencart#8779]
**What version of OpenCart are you reporting this for?**
Latest Master branch 

**Describe the bug**
Well, a few versions ago, mysqli destructors were ditched in favor of register shutdown function. Fetching upstream today I saw that destructors are back. Problem is the destructor is never closed, (you can var dump in close function and will never be called), leaving mysql timeout to do the work. Register shutdown function should return but with the bug fix I mention here in this pull request #8684.  There should be a rework with close function in db parent class and implemented in all adaptor classes. 

See the pull request #8684 for a more detailed description of the bug

**Comment by Boorinio** [comment]
Still same situation

**Comment by danielkerr** [comment]
adding register_shutdown_function([$this, 'close']); back!

**Comment by danielkerr** [comment]
added destructors back because they do work! you can test them by putting a echo 'test'; in them! u see noboy else having this issue!
