### ISSUE TITLE
[Master Branch] - extension/opencart/catalog/view/template/payment/free_checkout.twig

### ISSUE THREAD

**Issue by yvonn** [opencart/opencart#8780]
In Master Branch - extension/opencart/catalog/view/template/payment/free_checkout.twig
at line 9
`url: 'index.php?route=extension/opencart/payment/free_checkout/confirm',`
replace by
`url: 'index.php?route=extension/opencart/payment/free_checkout|confirm',`

**Comment by straightlight** [comment]
Yes, confirmed.
