### ISSUE TITLE
Branch[3.0.x.x_Maintenance]: Account locking not working for the affiliate/customer login

### ISSUE THREAD

**Issue by Webkul-Opencart** [opencart/opencart#8805]
**What version of OpenCart are you reporting this for?**
Test Environment--
-- opencart version: Version 3.0.3.6

**Describe the bug**
at the customer/affiliate end, account locking functionality not working which is setup at the admin end > settings section, for the 5 login attempts. But when I apply the brute force attack(cluster bomb) via burp suite then it is allowing to run the multiple login attempts i.e 33 in below screenshot(I have applied till 100 also).

**Expected behavior**
When attempts limit exceeds then it must show the status as 403 or something else for the permission denied/account locking exceed attempts.

**Screenshots / Screen recordings**
![Selection_275](https://user-images.githubusercontent.com/42890212/96676623-60c77b80-138b-11eb-8705-a171198a0271.png)
![Selection_274](https://user-images.githubusercontent.com/42890212/96676634-67ee8980-138b-11eb-876b-5c0d69ed93bb.png)

**Server / Test environment (please complete the following information):**
opencart version: 3.0.3.6
operating system: Ubuntu 16.04 LTS
PHP version-- 7.4.11
browser/browser version: 81.0 (64-bit) Mozilla Firefox

**Comment by Webkul-Opencart** [comment]
need to fix this one too-- https://github.com/opencart/opencart/issues/8710

**Comment by prabhatkumaroc082** [comment]
login attempts are already added for customer/affiliate and these attempts are managed by admin.
