### ISSUE TITLE
New modern wysiwyg editor for opencart

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#8806]
**What version of OpenCart are you reporting this for?**
Last

**Additional context**
Are you planning to integrate a normal wysiwyg editor into opencart?
For example this one: https://froala.com/wysiwyg-editor/

**Comment by stalker780** [comment]
A commercial product? Really?

**Comment by Hkr32** [comment]
> A commercial product? Really?

CKEditor non commercial?

**Comment by osworx** [comment]
@Hkr32 

> a normal wysiwyg editor

What do you understand under a **normal editor** ?
What's wrong with ckeditor?

**Comment by Hkr32** [comment]
I'm not an expert in this matter, I just wrote a thought, I use this editor in other systems, it seemed to me more convenient, that's why I asked

**Comment by stalker780** [comment]
CKEditor has free plan without support.
Froala is always commercial.

**Comment by Hkr32** [comment]
What do you think about:
https://editorjs.io/
https://yabwe.github.io/medium-editor/

**Comment by mhcwebdesign** [comment]
@Hkr32: Neither one of your suggested editors is useful enough for OpenCart content editing, with many basic features missing. Ckeditor is just fine.

**Comment by Hkr32** [comment]
Ckeditor commercial?

TinyMCE is still kind of free.

**Comment by danielkerr** [comment]
i already switched back from summernote. i need something that i need not need to keep replacing because the project might not be around in 5 years.
