### ISSUE TITLE
Events on startup

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#8811]
https://github.com/opencart/opencart/blob/4fc9627cf813e11e09b2baf3bc2ad9f1141a0b43/upload/system/config/catalog.php#L28

Maybe  move before 
https://github.com/opencart/opencart/blob/4fc9627cf813e11e09b2baf3bc2ad9f1141a0b43/upload/system/config/catalog.php#L22

```
$_['action_pre_action']  = [
	'startup/setting',
	'startup/session',
	'startup/event',
	'startup/language',
	'startup/application',
	'startup/extension',
	'startup/startup',
	'startup/marketing',
	'startup/error',
	'startup/sass',
	'startup/maintenance',
	'startup/seo_url'
];
```

**Comment by straightlight** [comment]
By moving the event before startup/language, extension developers might also affect the language/<language_code>/<language_code>.php files which would affect a core file inclusively.

**Comment by chulcha** [comment]
/startup/langauge - use model  method $this->model_localisation_language->getLanguages
/startup/applicattion use model method $this->model_localisation_currency->getCurrencies

and other have model without event

After startup/event Events are active and my event can also change core settings

**Comment by straightlight** [comment]
This should be reviewed ...

**Comment by straightlight** [comment]
The system/config profiles should have its own sort_order list for the core, aside from the extensions that should re-use the sort_order field on the oc_event table. This way, regardless of the mount of extensions trying to override those settings, the core would maintain its sort ordering list priority the way they'd be out-of-the-box. Granted, people using VQMod would be another story but at least that Engine s not in the core.

**Comment by chulcha** [comment]
Do you think that startup and user applications should work in isolation? 
And don't use custom events, although startup is also in its space of aplication.
Moreover, the used model methods are taken from the space of application.

**Comment by straightlight** [comment]
They don't need to work in isolation if sort orders can be handled from the core and parallelly with the extensions. Custom events could still, then, suggested to be used more likely. However, you'd be correct regarding the model methods being taken from the space of application but those are not the issue. The issues are with the controller priority orders by the sort listings.

**Comment by straightlight** [comment]
Even better, if not by sort ordering, the extension folder is now separated aside from the admin and catalog folders. Which means, events could be categorically and specifically loaded by extensions or from the core by splitting those transactions from the loader engine.

**Comment by chulcha** [comment]
I don't quite understand you.
And here the order is by the order of priority of the controller in the sorting lists.

Loading events as one of the primary design elements of the application
And, in my opinion, should have a higher priority

For example, maintenance and seourl, and everything is clear and understandable here.
But events do not affect the behavior of config elements, if you look, you will see that only model methods are applied, especially since the config controllers will not be affected by events only model methods.

**Comment by straightlight** [comment]
To keep things simple, core controllers are loading with extension controllers and vice-versa with Event controllers. They need to be separated.

**Comment by BuslikDrev** [comment]
You also need to make it possible not to load these additional modules. Since they are not always needed, for example, when making an ajax request.

**Comment by danielkerr** [comment]
events require dependencies. can not load to early.
