### ISSUE TITLE
Add pre conodition to startup/sass.php

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#8812]
https://github.com/opencart/opencart/blob/4fc9627cf813e11e09b2baf3bc2ad9f1141a0b43/upload/catalog/controller/startup/sass.php#L5
Add condition

`if (!$this->config->get('developer_sass')) { return; }`

https://github.com/opencart/opencart/blob/4fc9627cf813e11e09b2baf3bc2ad9f1141a0b43/upload/catalog/controller/startup/sass.php#L14

Change
if (is_file($stylesheet)) {

**Comment by straightlight** [comment]
Please create a PR with the suggested code change, in this case.
