### ISSUE TITLE
Suggestion: 'Back' button missing from some pages(Wishlist page,Order History page,Downloads page etc)

### ISSUE THREAD

**Issue by Prashi9** [opencart/opencart#8815]
**What version of OpenCart are you reporting this for?**
Version 3.0.3.6

**Describe the bug**
'Back' button missing from some pages(Wishlist page, Order History page, Downloads page etc), please provide the 'back' button at all pages.

**To Reproduce**
1. Go to the Account page,
2. Click on 'wishlist' or other pages(Downloads, Order History, etc)
3. 'Back' button is not visible
![suggestion1](https://user-images.githubusercontent.com/50448674/96829028-5920d900-1456-11eb-82c0-1ea2606d4371.png)

**Expected behavior**
at all the account pages should be visible the "Back" button, as visible at "Address Book" page:

![suggestion2](https://user-images.githubusercontent.com/50448674/96829374-275c4200-1457-11eb-84bb-c9be7e5f8cfb.png)

**Server / Test environment (please complete the following information):**
 opencart version: 3.0.3.6
 operating system: Ubuntu 16.04 LTS
 PHP version-- 7.4.11
 browser/browser version: 81.0 (64-bit) Mozilla Firefox

**Comment by condor2** [comment]
I think in some files Continue button should be removed or replaced with Back because both buttons will have same URL

**Comment by WebkulOpencart** [comment]
The working of the continue button is the same as the back button so closing this issue
