### ISSUE TITLE
add to cart button not working.

### ISSUE THREAD

**Issue by nasirkhalil** [opencart/opencart#8816]
i am using opencart 3.0.

my site is working on live server, now i download it on localhost everything is fine but when i click on add to cart button it give me error of too many redirects
![image](https://user-images.githubusercontent.com/38240404/96848681-c4be7280-1465-11eb-9c6a-5e8bee32b6d7.png)

thank you in advance.

**Comment by ADDCreative** [comment]
Try the forum. https://forum.opencart.com/
