### ISSUE TITLE
Suggestions: branch[3.0.x.x_Maintenance]

### ISSUE THREAD

**Issue by Webkul-Opencart** [opencart/opencart#8818]
1. at the admin end > catalog > products section, there must be an option for the bulk product status enable /disable as when we do the bulk product clone then the cloned product status is by default set as disabled i.e https://prnt.sc/v4mtz9
2. at the admin end > extensions > google hangouts section, when the module status is set as disable still the validations are working i.e https://prnt.sc/v4mwhj
3. need to correct the recurring profile name display at the drop down i.e 
![Selection_277](https://user-images.githubusercontent.com/42890212/96887497-4633f600-14a2-11eb-8a84-b2c63ad6f8ba.png)

**Comment by ADDCreative** [comment]
I don't think number 2 is an issue. If you want to remove the content, just uninstall the module. I see no reason anyone would want to disable and empty the content. Also other modules, such as Google Analitice, work the same way.
