### ISSUE TITLE
There is a big difference between 3.0.3.6 relase and 3.0.x.x maintenance branch

### ISSUE THREAD

**Issue by Toxin95** [opencart/opencart#8820]
I have noticed there are a lot of differences between [3.3.0.6](https://github.com/opencart/opencart/releases/tag/3.0.3.6) tag and [3.3.x.x maintenance](https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance) branch.
Why has not been made new release?

**Comment by straightlight** [comment]
Because it's still in progress.

**Comment by WebkulOpencart** [comment]
I am closing this issue.

**Comment by mhcwebdesign** [comment]
Toxin95 has a valid question. OC 3.0.3.6 has well known bugs, such as a corrupted modification.xml. It should have never been released. Pretty much anything beyond OC 3.0.3.2 is not stable enough for a live site. The 3.0.x.x maintenance should have just focused on important bugfixes.
