### ISSUE TITLE
Bootstrap Carousel to replace Swiper?

### ISSUE THREAD

**Issue by NancySavage** [opencart/opencart#8822]
The code is already there for it in the Bootstrap files. I am wondering why we can't use it instead of Swiper? I already hard-coded the home/main page of OC with it for myself since I prefer it. It would be a nice change to just move away from yet another plugin that we really don't need if BS can do it already.

**Comment by condor2** [comment]
You can create a pull request.

**Comment by BuslikDrev** [comment]
Better to drop jquery altogether!

**Comment by danielkerr** [comment]
any one willing to do this and keep the code similar to opencart style?

**Comment by danielkerr** [comment]
will do as soon as i have time! unless some one else wants to do it and do a pull request.

**Comment by BuslikDrev** [comment]
> will do as soon as i have time! unless some one else wants to do it and do a pull request.

I think we need to create a lightweight version of the swiper for the OpenCart design so that the carousel module doesn't depend on bootstrap and jQuery. This will allow the carousel script to be loaded using async and defer, and in other ways to delay loading to speed up the site without errors.

**Comment by danielkerr** [comment]
already removing it.
