### ISSUE TITLE
 Indirect modification of overloaded property Controller - OpenCart 3.0.2.0 

### ISSUE THREAD

**Issue by kogati8** [opencart/opencart#8823]
OpenCart3.0.2.0 
 
Indirect modification of overloaded property ControllerProductProduct::$data has no effect in D:\XAMPP\htdocs\occc\vqmod\vqcache\vq2-D:_XAMPP_storage6_modification_catalog_controller_product_product.php on line 298Notice: Indirect modification of overloaded property ControllerProductProduct::$data has no effect in D:\XAMPP\htdocs\occc\vqmod\vqcache\vq2-D:_XAMPP_storage6_modification_catalog_controller_product_product.php on line 299

*- Local development
 - PHP version 7.3.10
 - Apache version 
 - Browser(s) tested with  chrome

**Additional context**

**Comment by BuslikDrev** [comment]
vqmod no in OpenCart. You are at the wrong address.

**Comment by straightlight** [comment]
Contact the extension developer to resolved this issue. This is not a master branch issue. Unsupported.

**Comment by WebkulOpencart** [comment]
Maybe in your extension, you are using the $data as a private variable that's why you face this issue

Also, there is no vqmod in OpenCart so closing this issue
