### ISSUE TITLE
[Master Branch] Uncaught Exception: Error: BLOB, TEXT, GEOMETRY or JSON column 'variant' can't have a default value

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#8824]
The installer comes up with this error:

`PHP Fatal error:  Uncaught Exception: Error: BLOB, TEXT, GEOMETRY or JSON column 'variant' can't have a default value<br />Error No: 1101<br />CREATE TABLE `oc_product` (\n  `product_id` int(11) NOT NULL AUTO_INCREMENT,\n  `master_id` int(11) NOT NULL DEFAULT '0',\n  `model` varchar(64) NOT NULL,\n  `sku` varchar(64) NOT NULL,\n  `upc` varchar(12) NOT NULL,\n  `ean` varchar(14) NOT NULL,\n  `jan` varchar(13) NOT NULL,\n  `isbn` varchar(17) NOT NULL,\n  `mpn` varchar(64) NOT NULL,\n  `location` varchar(128) NOT NULL,\n  `variant` text NOT NULL DEFAULT '',\n  `override` text NOT NULL DEFAULT '',\n  `quantity` int(4) NOT NULL DEFAULT '0',\n  `stock_status_id` int(11) NOT NULL,\n  `image` varchar(255) NOT NULL,\n  `manufacturer_id` int(11) NOT NULL,\n  `shipping` tinyint(1) NOT NULL DEFAULT '1',\n  `price` decimal(15,4) NOT NULL DEFAULT '0.0000',\n  `points` int(8) NOT NULL DEFAULT '0',\n  `tax_class_id` int(11) NOT NULL,\n  `date_available` date NOT NULL,\n  `weight` decimal(15,8) NOT NULL DEFAULT '0.00000000',\n  `weight_class_id` int(11) NOT NULL DEF
`

Please fix the **system/helper/db_schema.php** accordingly!

**Comment by righ7** [comment]
`set @@sql_mode='ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'`
My approach is to run this code in MySQL to skip the warning.

**Comment by straightlight** [comment]
The db_schema.php file only needs to be edited to add a default value. This has been discussed already recently on this repository.

**Comment by eka7a** [comment]
https://github.com/opencart/opencart/commit/eb909ebb816643560321c6a24d3cff9b094e0be6

**Comment by nextpulse** [comment]
It seems the error is introduced by https://github.com/opencart/opencart/commit/eb909ebb816643560321c6a24d3cff9b094e0be6

**Comment by mhcwebdesign** [comment]
OK, now it's 26 days ago since I reported this issue, and it is still not fixed in the master branch!

Here is how to sort it out:

In file **system/helper/db_schema.php** change all entries containing

`'not_null' => true`

to

`'not_null' => false`

where the 

`'type' => 'datetime',`

or

`'type' => 'datetime',`


Also, in file **install/opencart.sql** change all instances of

`'0000-00-00'` to `NULL`

and all instances of

`'0000-00-00 00:00:00'` to `NULL`


Reason for above changes: MySQL 5.7 or later stopped supporting zero values in date / datetime. It's incorrect to use zeros in date or in datetime, just put null instead of zeros. See e.g. https://stackoverflow.com/questions/37292628/1292-incorrect-date-value-0000-00-00

**Comment by saarangsoltani** [comment]
im having the same problem and setting `sql_mode` to the value suggested above didn't work

**Comment by straightlight** [comment]
@saarangsoltani: Which OC and mySQL version are you using?

**Comment by mhcwebdesign** [comment]
@straightlight: There is no need to add an extra sql_mode as suggested by @nextpulse because my suggested solution should work with both PHP 5.x, PHP 7.x or even the upcoming PHP 8.x. Just change the **system/helper/db_schema.php** and **install/opencart.sql** as per my suggestion above!

**Comment by straightlight** [comment]
@mhcwebdesign: Why are you tell me this for? I simply asked the user which OC and mySQL version the user is currently using.

**Comment by nextpulse** [comment]
@mhcwebdesign the main issue is not the zero value. It seems to be related to the default value that was added to the file.

Fatal error: Uncaught Exception: Error: BLOB, TEXT, GEOMETRY or JSON **column 'variant' can't have a default value**

The quick fix is to change the SQL mode for the table creation ONLY - this avoids unverified source file changes.

**Comment by stalker780** [comment]
Should help

sql_mode='NO_ENGINE_SUBSTITUTION'

**Comment by siarheipashkevich** [comment]
I'm getting the same issue for fresh installation of the OC. There is any who fixed this issue correctly?

**Comment by mhcwebdesign** [comment]
I suggest a fix of the **system/helper/db_schema.php** 

Replace

```
			[
				'name' => 'variant',
				'type' => 'text',
				'not_null' => true,
				'default' => ''
			],
			[
				'name' => 'override',
				'type' => 'text',
				'not_null' => true,
				'default' => ''
			],
```

with

```
			[
				'name' => 'variant',
				'type' => 'text',
				'not_null' => true,
			],
			[
				'name' => 'override',
				'type' => 'text',
				'not_null' => true,
			],
```

That is, remove the `'default' => ''` for the fields of type 'text'. I have found only 2 instances, namely for fields 'variant' and 'override' where this is the case.

**Comment by danielkerr** [comment]
should be working after MySQL 8+ #8976 was fixed.

**Comment by singto53** [comment]
system/helper/db_schema.php  What file name?
