### ISSUE TITLE
[Master Branch] twig->root problem

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#8825]
The Twig rendering doesn't work for certain Linux servers.

The **system/library/template/twig.php** should be changed in the constructor using this root folder for twig:

`		$this->root = substr(DIR_OPENCART,0,strlen(DIR_OPENCART)-1);
`

instead of the

`		$this->root = $_SERVER['DOCUMENT_ROOT'];
`

Reason: 

The $_SERVER['DOCUMENT_ROOT'] isn't always the same as the real path, it may contain links.

For example, on our Linux server we use 'https://localhost/xxx' which the Apache server maps to the underlying '/var/www/html/**_xxx_**' and where '**_xxx_**' is a link to the real path 'home/xxx/htdocs'.

**Comment by straightlight** [comment]
Another of these 50000 different ways to track folders on specific folders. :(

**Comment by mhcwebdesign** [comment]
Maybe. But the scenario I described is not uncommon. You can't rely on the DOCUMENT_ROOT to always contain a genuine folder path, on some servers it may have links to other paths.

**Comment by mhcwebdesign** [comment]
@straightlight: Any news on a fix for this? I am certain my suggested fix to the twig.php should sort this out!

**Comment by straightlight** [comment]
That would only resolve the admin-end side on specific servers since config.php file of the catalog-end side does not have the DIR_OPENCART constant defined as it's not required to be defined either.

"However", since the translated path of the system/startup.php is being used in order to replace the paths from the $_SERVER['DOCUMENT_ROOT'], as user defined,  there might be another possible way to achieve this.

See if the following would resolve the issue:

In system/library/template/twig.php file,

find:

```$this->root = $_SERVER['DOCUMENT_ROOT'];```

replace with:

```$_SERVER['DOCUMENT_ROOT'] = str_replace('\\', '/', substr(str_replace('\\\\', '\\', $_SERVER['PATH_TRANSLATED']), 0, 0 - strlen($_SERVER['PHP_SELF'])));```

See if that solves the issue.

**Comment by straightlight** [comment]
Slight modification done on the above.

**Comment by straightlight** [comment]
Another way would be to replace:

```$this->root = $_SERVER['DOCUMENT_ROOT'];```

with:

```$this->root = &$_SERVER['DOCUMENT_ROOT'];```

**Comment by mhcwebdesign** [comment]
Good thinking, however, it doesn't work on my Apache2 server:

PHP Notice:  Undefined index: PATH_TRANSLATED

This is really an issue with Twig not being able to figure out which template cache to use, according to Daniel.
Why was Twig working before, with its autocache enabled, in OC 3.0.3.6, not however in this masterbranch?

This whole usage of Symfony Twig is cumbersome, I am seriously considering writing a whole Twig rendering engine from scratch which would directly translate the template into the final HTML! I have a lot of compiler writing experience anyway, writing up a fast Twig translator isn't that hard.

**Comment by straightlight** [comment]
Try the latest way right above your post. I just posted another solution.

**Comment by mhcwebdesign** [comment]
Getting this now with your latest suggestion:

PHP Fatal error:  Uncaught Twig\\Error\\LoaderError: Unable to find template "htdocs/opencart-4-0-0-0-b/opencart/upload/install/view/template/common/footer.twig" (looked into: ). in /home/juergen/htdocs/opencart-4-0-0-0-b/opencart/upload/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php:227\nStack trace:\n#0 /home/juergen/htdocs/opencart-4-0-0-0-b/opencart/upload/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php(131): Twig\\Loader\\FilesystemLoader->findTemplate('htdocs/opencart...')\n#1 /home/juergen/htdocs/opencart-4-0-0-0-b/opencart/upload/system/storage/vendor/twig/twig/src/Environment.php(261): Twig\\Loader\\FilesystemLoader->getCacheKey('htdocs/opencart...')\n#2 /home/juergen/htdocs/opencart-4-0-0-0-b/opencart/upload/system/storage/vendor/twig/twig/src/Environment.php(309): Twig\\Environment->getTemplateClass('htdocs/opencart...')\n#3 /home/juergen/htdocs/opencart-4-0-0-0-b/opencart/upload/system/storage/vendor/twig/twig/src/Environment.php(277): Twig\\Environment->load('htdocs/opencart...')\n#4 /home/juerg in /home/juergen/htdocs/opencart-4-0-0-0-b/opencart/upload/system/storage/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 227,

**Comment by straightlight** [comment]
Then the translated path key is the issue on your server specifically. You need to have it assigned in order for the paths to be relatively used with controllers, languages, models and view files. Outside of the TWIG engine might be believed to be working because the system/startup.php file is replacing the path in an IF statement which your server seem to skip ahead.

**Comment by straightlight** [comment]
Or, some files might really be missing on your server during upload.

**Comment by mhcwebdesign** [comment]
I'll take another look at it tomorrow.

**Comment by mhcwebdesign** [comment]
@straightlight: OK, I solved this issue, as follows (no need to use the cumbersome **$_SERVER['DOCUMENT_ROOT']**):

In file **system/library/template/twig.php** replace

`$this->root = $_SERVER['DOCUMENT_ROOT'];`

with

`$this->root = substr(DIR_OPENCART,0,strlen(DIR_OPENCART)-1);`


And in file **install/controller/install/step_3.php** add

`$output .= 'define(\'DIR_OPENCART\', \'' . addslashes(DIR_OPENCART) . '\');' . "\n";`

after each

`$output .= '// DIR' . "\n";`

**Comment by ADDCreative** [comment]
@mhcwebdesign You could also possibly just use:

```php
$this->root = dirname(DIR_APPLICATION);
```

**Comment by mhcwebdesign** [comment]
@ADDCreative: Just tried it with DIR_APPLICATION, doesn't work!

**Comment by ADDCreative** [comment]
@mhcwebdesign That's strange ```dirname(DIR_APPLICATION)``` worked for me.

Given how DIR_APPLICATION is defined.
https://github.com/opencart/opencart/blob/7a90f18ac0993014ecdcc4b7214abcb033523814/upload/install/index.php#L19

```dirname(DIR_APPLICATION)``` should be the same as ```substr(DIR_OPENCART,0,strlen(DIR_OPENCART)-1)```.

**Comment by mhcwebdesign** [comment]
@ADDCreative: Sorry, yes, you are right, I mispelled DIR_APPLICATION in my twig.php file.

So in summary: All that needs to be changed in the system/library/template/twig.php is this:

Replace the
`$this->root = $_SERVER['DOCUMENT_ROOT'];`

with this:
`$this->root = dirname(DIR_APPLICATION);`

**Comment by danielkerr** [comment]
it needs the full server root to get the correct file cache name. otherwise the system will start loading the wrong cache files and templates.

**Comment by danielkerr** [comment]
what about fixijng it in the startup.php

// Windows IIS Compatibility
if (!isset($_SERVER['DOCUMENT_ROOT'])) {
	if (isset($_SERVER['SCRIPT_FILENAME'])) {
		$_SERVER['DOCUMENT_ROOT'] = str_replace('\\', '/', substr($_SERVER['SCRIPT_FILENAME'], 0, 0 - strlen($_SERVER['PHP_SELF'])));
	}
}

**Comment by danielkerr** [comment]
it already does the code here:

`// Windows IIS Compatibility
if (!isset($_SERVER['DOCUMENT_ROOT'])) {
	if (isset($_SERVER['SCRIPT_FILENAME'])) {
		$_SERVER['DOCUMENT_ROOT'] = str_replace('\\', '/', substr($_SERVER['SCRIPT_FILENAME'], 0, 0 - strlen($_SERVER['PHP_SELF'])));
	}
}

if (!isset($_SERVER['DOCUMENT_ROOT'])) {
	if (isset($_SERVER['PATH_TRANSLATED'])) {
		$_SERVER['DOCUMENT_ROOT'] = str_replace('\\', '/', substr(str_replace('\\\\', '\\', $_SERVER['PATH_TRANSLATED']), 0, 0 - strlen($_SERVER['PHP_SELF'])));
	}
}`


what server software are u using?

**Comment by danielkerr** [comment]
im using apache2 as well.

**Comment by mhcwebdesign** [comment]
Daniel, the issue is not fixed. It needs this in the **system/library/template/twig.php**:

`		$this->root = dirname(DIR_APPLICATION);
`
instead of

`		$this->root = $_SERVER['DOCUMENT_ROOT'];
`

On a Linux server the $_SERVER['DOCUMENT_ROOT'] is usually already set, but its path may continue links, hence the DIR_APPLICATION may start root path in its real path.

I'll test all of today's master branch during this afternoon, there are still other installer bugs, before uploading pull requests or fixes.

**Comment by danielkerr** [comment]
DIR_APPLICATION will break as well because it needs to set the root directory. 

dirname(DIR_APPLICATION);

admin will become admin

catalog will become catalog

and twig can not tell the difference of common/header in either directory. try the installer and see what happens.

**Comment by danielkerr** [comment]
'DOCUMENT_ROOT'
The document root directory under which the current script is executing, as defined in the server's configuration file.

**Comment by danielkerr** [comment]
what does your root display?

**Comment by danielkerr** [comment]
its because twig does not include $this->root when generating a cache file name.

**Comment by danielkerr** [comment]
it mixes template files up with the installer. you might not notice because i updated the installer to be the similar to the admin.

**Comment by mhcwebdesign** [comment]
My document root ($_SERVER['DOCUMENT_ROOT] is '/var/www/html'. I have configured our test server to e.g. translating the https://_domain_/juergen/testshop to '/home/juergen/htdocs/testshop'. 

There is a link at '/var/www/html/juergen' pointing to '/home/juergen/htdocs'.

My dirname(DIR_APPLICATION) is '/home/juergen/htdocs/testshop'
