### ISSUE TITLE
Unable to login [3.0.3.6]

### ISSUE THREAD

**Issue by righ7** [opencart/opencart#8832]
**What version of OpenCart are you reporting this for?**
3.0.3.6
**Describe the bug**
`$this->model_account_customer->addLogin($this->customer->getId(), $this->request->server['REMOTE_ADDR']);`
`var_dump($this->customer->isLogged());exit();`
in login.php var_dump return ‘1‘，but redirect to account/account var_dump return null。

![1603787186(1)](https://user-images.githubusercontent.com/40221986/97275667-2ec58600-1871-11eb-9ade-57e1afad7c51.jpg)

**Comment by condor2** [comment]
Isn't 3.0.3.6.
It is the master BRanch version.

**Comment by righ7** [comment]
> Isn't 3.0.3.6.
> It is the master BRanch version.
ok,thank u

**Comment by ujesh-t** [comment]
Same issue, redirecting to account/login after login

Any workaround?
