### ISSUE TITLE
Problem on products>option at Opencart ver 3.0.x.x

### ISSUE THREAD

**Issue by melvin16** [opencart/opencart#8833]
**What version of OpenCart are you reporting this for? Version 3.0.X.X**

**Describe the bug**
When option more than 93 items, it could only fit 93 items, and affected discount, special, and SEO all becomes not working.
I have experience in Opencart ver. 3.0.2.0 and 3.0.3.3, this might be affected on all of OC ver 3.0.X.X 

**To Reproduce**
1. Go to 'Option' and fill the items more than hundreds.
2. Click on 'catalog' > 'products' and use the 'option' that you made before
3. Then try make discount, special, and SEO for this product. 
4. All of them will not working : "option' only fit 93 items. Discount, special, and SEO all of them are become blank

**Expected behavior**
All of them should be working as well, option should be hundreds; discount, special, and SEO should be working well 

**Screenshots / Screen recordings**
![vallejomodelcolor1](https://user-images.githubusercontent.com/9612267/97397714-8240de00-191c-11eb-9762-d075c8b20921.png)
![vallejomodelcolor3](https://user-images.githubusercontent.com/9612267/97397743-8f5dcd00-191c-11eb-8f45-3b051382ab3e.png)
![vallejomodelcolor2](https://user-images.githubusercontent.com/9612267/97397755-9684db00-191c-11eb-86be-f331f309dc51.png)
![vallejomodelcolor7](https://user-images.githubusercontent.com/9612267/97397769-9be22580-191c-11eb-9c6e-b3d1ae111bbd.png)

Please make Opencart update for this bug, thank you for your kindly attention and correction it.

**Comment by prabhatkumaroc082** [comment]
yes, big option values are creating issues on discounts or specials saved data. 3.0.3.6 version has an issue, I will check again and add a merge for it.

**Comment by prabhatkumaroc082** [comment]
no issue found, it seems you are facing the issue due to **max_input_vars**. ask WHM

**Comment by osworx** [comment]
> 
> 
> no issue found, it seems you are facing the issue due to **max_input_vars**. ask WHM

When using/having many options, **max_input_vars** is set too low (per default = 1000).
Increase that value (server panel or/and php.ini to e.g. 4000) and it will work.

**Comment by melvin16** [comment]
Thank you so much @prabhatkumaroc082  and @osworx  for your advices, and it seems works well
