### ISSUE TITLE
Customer Group Discount Price does not display until after an item is placed in the Shopping Cart

### ISSUE THREAD

**Issue by DaveRiba** [opencart/opencart#8835]
**What version of OpenCart are you reporting this for?**  3.0.3.6

**Describe the bug**
I have set up a Customer Group -- Wholesale
I have assigned a Customer to Customer Group Wholesale
Under Product / Discount I point each product to Customer Group Wholesale and set a new discounted price for this item

Customer, who is part of this group, logs in. They are presented with the base price for the item - not the discounted price. 
Add to Cart, and the Cart shows the correct wholesale price.
This is confusing for the customer. Customer should be presented the price they will pay * before * they make the selection - not after it is in the cart.

What section does it affect?  Every Product, no matter what page it is listed on.

**To Reproduce**
1. Go to ViviLuxUSA.com
2. Log in as Wholesale Test Customer dave@jadetek.com PW: test1200
3. Purchase any item (except for BOGO items)
4. Note the price displayed
5. Add to cart (you may have to select a Wall Plug for certain items before being added to the cart)
6. Note the price in the cart -- it is the CORRECT discounted price

**Expected behavior**
The price the customer will be charged in the cart should appear on the Product page before the customer purchases.
If the Customer gets a Discounted Price, the Discounted Price should appear on the Product Page

**Screenshots / Screen recordings**

**Server / Test environment (please complete the following information):**
 - Operating system Windows Server 2019
 - PHP version 7.4.1
 - Apache version N/A

**Additional context**

**Comment by prabhatkumaroc082** [comment]
discounts are just displayed to the customer https://prnt.sc/v94nr2 not applied on the product page. it will be applied to the cart as per discount quantity. This website https://harbor-sales.com/ also seems to be modified, try on fresh Opencart.

**Comment by DaveRiba** [comment]
Sorry, you did not understand the problem.
I am attaching 3 screenshots.  Maybe this will help explain better.

We have 2 types of customers -- Retail and Wholesale
Wholesale customers pricing is 1/2 of Retail customers pricing.

For this example, I am logged in as a Wholesale Customer
Customer selects an item (Alignment Stickers - retail price is $19.99)
(image BUG1)
Price displayed is Retail Price -- $19.99, Shopping cart is  empty

Customer adds to cart.
(image BUG2)
Notice cart shows the correct price $10.00, but the page still displays Retail Price $19.99, not Wholesale Price $10.00

Customer views cart
(image BUG3)
Cart shows correct Wholesale price of $10.00

``````````````````````````````````````````````````````````````````````````````````````````````````````````
The BUG is in OpenCart and the Correct Behavior should be:

If a Customer has a price that is different from Retail Price, the Customer's price should display on product/product
We do not do SURPRISE PRICING -- buy something and then find out what it costs.
The cost displayed should be the cost the customer pays.
I consider this issue a Bug, not a Feature
How do we fix it?

Dave

![ViviLuxBUG1](https://user-images.githubusercontent.com/72571491/97590517-14a4b880-19d5-11eb-806c-d67f40f2d6f6.png)
![ViviLuxBUG2](https://user-images.githubusercontent.com/72571491/97590519-153d4f00-19d5-11eb-9664-78baa1bd23a0.png)
![ViviLuxBUG3](https://user-images.githubusercontent.com/72571491/97590521-153d4f00-19d5-11eb-90ac-78f50d6383ea.png)

**Comment by DaveRiba** [comment]
Found it -- My mis-understanding of the Quantity field on the Discount setting.
Set Qty to 1 and it works as it shoud
Sorry

Dave
