### ISSUE TITLE
Suggestion: Translation for countries and zones

### ISSUE THREAD

**Issue by Gadalla** [opencart/opencart#8838]
Since many shipping and payment methods accept ASCII or Latin characters only when communicating with their API, I suggest keeping the counties and zones in English undeletable. And add the ability to translate the country and zone names depending on the additional language installed in OpenCart. Just like the tabs of the product's title or the product's description. Shipping and payment methods must indicate if the method's API accepts none ASCII or none Latin characters.

**Comment by ADDCreative** [comment]
It would be a nightmare to maintain. It's bad enough getting the zones correct for each country, let alone the correct English translation of each one. Some of the zones don't make sense in postal addresses anyway, but that's another issue.

If a payment gateway can't handle UTF-8 characters. That's an encoding problem not a translation problem. The module should be using utf8_decode, assuming ISO-8859-1 or one of the other character encoding conversion functions.

**Comment by Gadalla** [comment]
"It's bad enough getting the zones correct for each country, let alone the correct English translation of each one." Out of the box, OpenCart will have the English country's names and zones. Once the admin adds a new language to the store, the country or zone edit page can display a field to enter the translation of that country. It is the admin to fill this field with correct translation, not we as developers. 

The checkout page, address edit page, etc must display the countries drop-down list in the language the page displayed in.

Payment and shipping methods should only use the English country's names and zones, which is un-deletable.

**Comment by ADDCreative** [comment]
I can see the benefit for having translation of country name. However, for zones it would be probably both impossible and pointless.

As I said, it's more likely an encoding issue. What APIs are you having problems with?

**Comment by Gadalla** [comment]
Countries or zones, they should display in the language selected in multi-language stores.

"What APIs are you having problems with?" I am not having any problems with APIs. But I always wondered why the countries and zones can't be translated and displayed in the language selected in the front end in OpenCart. The solution I am doing now is filling the country/zone name field with two languages like the image below.

![screenshot-nutrishop ae-2020 10 31-00_44_38](https://user-images.githubusercontent.com/31627788/97755529-cbf31980-1b12-11eb-8e8d-216a4369ddaf.jpg)

**Comment by straightlight** [comment]
I may agree with this request since the master branch does focus on the customer's order language rather than the merchant's language ID while using the internal API. By combining both features, it could also make more sense to display the orders' regional settings by languages. Besides, jQuery can also handle the |escape case with JSON response. If the output causes issues, this case could then be used. I used to have a published extension on the Marketplace before. Perhaps I could build one for the master branch as well.

**Comment by straightlight** [comment]
Changed my mind. By actually doing that, the admin model sale order's getOrder method already pulls the relative customer's language with the order. By pulling the current language ID as opposed to the customer's language ID, the results will still be differed for the countries and zones.

**Comment by straightlight** [comment]
Furthermore to the above, service providers are using English lookups through their APIs on anyhow. Which means, regardless if an extension is being on our end to lookup on our languages, the service provider's-end will mostly lookup in English with their requested parameters.

**Comment by Gadalla** [comment]
> I may agree with this request since the master branch does focus on the customer's order language rather than the merchant's language ID while using the internal API. By combining both features, it could also make more sense to display the orders' regional settings by languages. Besides, jQuery can also handle the |escape case with JSON response. If the output causes issues, this case could then be used. I used to have a published extension on the Marketplace before. Perhaps I could build one for the master branch as well.

**Comment by Gadalla** [comment]
> Furthermore to the above, service providers are using English lookups through their APIs on anyhow. Which means, regardless if an extension is being on our end to lookup on our languages, the service provider's-end will mostly lookup in English with their requested parameters.

You can code so the English countries/zones can't be deleted and service providers (payment or shipping) must indicate if they accept Unicode characters or only ASCII.

**Comment by awaro** [comment]
Выносите  геоданные из базы в яз файлы. запарили аматоры

**Comment by Gadalla** [comment]
> Выносите геоданные из базы в яз файлы. запарили аматоры

I translated this to "Move geodata from the base to the language files. amateurs". Did you manage to do it? Or are you suggesting?
