### ISSUE TITLE
Problems with seo pro & google robots

### ISSUE THREAD

**Issue by kerambit** [opencart/opencart#8843]
**What version of OpenCart are you reporting this for?**
I am using 3.0.3.2 ver
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
I have a problem with slugs. Using SEO PRO wiith slugs in my web everything is fine and good, but google pagespeed returns me 404 on every page except main page. If i turn off seo pro module and use for example: mysite.com/index.php?route=pages/products everything works fine in web and google pagespeed.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? - deployed to a web server
 - Operating system - linux
 - PHP version - 5.6.4
 - Apache version - apache 2.0
 - Browser(s) tested with chrome, safari, mozilla ff

How can i fix it?

**Comment by straightlight** [comment]
Opencart forum request.
