### ISSUE TITLE
Fatal error at Customs fields 

### ISSUE THREAD

**Issue by hobbykit** [opencart/opencart#8860]
I added a new field from the OpenCart admin, "Sales - Customers - Customs fields". I added a new field "Company ID".
In "Register Account", the field is filled in. No problem.
However, in "Edit Consumer" from the OpenCart administrator, "Address1", this error appears below the "Company ID" field:
"Fatal error: Cannot use string offset as an array in ../admin/view/template/sale/customer_form.tpl on line 501"
I use OpenCart 2.0.1.1

I did a few sample. When the new field is in Location - Account there is no problem. But when it is in Location - Address, there is an error.
What could be the problem?

**Comment by straightlight** [comment]
OC forum request.

**Comment by WebkulOpencart** [comment]
Please report the old version issue on the OC forum so closing this issue.
