### ISSUE TITLE
Division by zero in currency.php

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#8866]
Version: 3.0.3.6 under php7.4

Bug - Warning Message seen: The currency.php page generated an error on the admin dashboard homepage.

To reproduce, Install OpenCart in PHP 7.4. Just open the dashboard.

Also might have caused, "headers already sent" to other pages.

Screenshots / Screen recordings:
Warning: Division by zero in /PATH/admin/model/localisation/currency.php on line 141

Content: $value = (1 / utf8_substr($line[$i + 1], 11, 6));

On production server.
 - Operating system: CentOS
 - PHP version: 7.4
![opencart-currency-division-by-zero](https://user-images.githubusercontent.com/5563341/98729556-53812980-2358-11eb-8991-31792c070a52.png)

**Comment by WebkulOpencart** [comment]
fixed the reported point so closing this issue
