### ISSUE TITLE
Layout editor probably accesses non HTTPS page

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#8868]
Erorr link: /admin/index.php?route=design/layout/edit&user_token=___&layout_id=4
For 3.0.3.6, php 7.4

My test system runs entirely on https://, and will error on http://.

Edit: Probably wrong error finding: `The layout editor (home > layout) in the admin page redirected to **http** until the following is seen.`
Actual error reporting should have been: **The page stops responding.**

![image](https://user-images.githubusercontent.com/5563341/98730257-41ec5180-2359-11eb-9239-b717fe19add3.png)
This prevents editing the layouts.

**Comment by straightlight** [comment]
What is the actual error outputs from the logs?

**Comment by anytizer** [comment]
Was hard to find an error. Possibly this:

PHP Fatal error:  Uncaught Twig\Error\RuntimeError: Unable to convert encoding: required function iconv() does not exist. You should install ext-iconv or symfony/polyfill-iconv in "design/layout_form.twig" at line 390. in /home/____/storage/vendor/twig/twig/src/Extension/CoreExtension.php:1001

**Comment by anytizer** [comment]
Finding: iconv was necessary in php to render that twig page. Issue probably linked with #8866 .
