### ISSUE TITLE
Problem when enabling SEO URL

### ISSUE THREAD

**Issue by devi005** [opencart/opencart#887]
I have done the following steps to enable seo url, but i couldnt get it to work.

1.SEO url turned on in backend
2.Modified .htaccess.txt to .htaccess
3.Updated a unique keyword for categories and products

And i have my project in subdirectory of my server.

I cant find a solution for this (displaying 404 page only), expecting a reply to this issue soon.

Thank you!

**Comment by maxmayank** [comment]
hi 
My open cart website url :     http://www.dermalure.com/professional_sizes_8oz
Need url :  http://www.dermalure.com/professional-sizes-8oz
