### ISSUE TITLE
OCMOD - Change .TWIG files in ADMIN

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#8871]
Hello.

I have tried change .TWIG files in ADMIN without successful.

Any idea?

OpenCart v3.0.3.6 (latest).
```
<?xml version="1.0" encoding="utf-8"?>
	<modification>
	<name></name>
	<code></code>
	<version></version>
	<author></author>
	<link></link>

	<file path="admin/view/template/extension/theme/default.twig">
		<operation>
			<search><![CDATA[<legend>{{ text_image }}</legend>]]></search>
			<add position="replace"><![CDATA[<legend>TEST</legend><fieldset>]]></add>
		</operation>
	</file>
</modification>
```

**Comment by condor2** [comment]
https://github.com/opencart/opencart/commit/d31b4ebe3fd29dcc8861725d4934c6e3dd68e019

**Comment by straightlight** [comment]
```<file path="admin/view/template/extension/theme/default.twig">```

The path is wrong.

**Comment by faca5** [comment]
Which one is correct? I have rechecked.
`
admin/view/template/extension/theme/default.twig`

**Comment by straightlight** [comment]
My bad. It is the right path. With OCMod, as opposed to Events, the full path must be entered.

**Comment by kgulpinar** [comment]
> d31b4eb

it worked, thanks. 👍

**Comment by jintianking** [comment]
OpenCart v4.0.0.0_b is not working.

**Comment by mhcwebdesign** [comment]
> OpenCart v4.0.0.0_b is not working.

The topic is about OpenCart 3.0.3.6 and an OCmod-based change to a template, this has nothing to do with OpenCart 4.0.0.0b which doesn't even supoort OCmod anymore! OpenCart 4.0.0.0b is work in progress and not recommended for live sites.
