### ISSUE TITLE
Twig function not working anymore since update 4 months

### ISSUE THREAD

**Issue by rickerd** [opencart/opencart#8872]
Since an update changing the Twig file loader to the arrayLoader, functions like macro and include aren't working anymore.
Also there was an update to "the latest" version of twig. This version was 2.x but there is a newer version 3.x.. 2.x is already pretty old so why locking the php to almost the newest version but other important dependencies still at a low version.

For me this did the trick getting the macro function working again in the latest version of OpenCart 3.0.3.6.

Near line 31
```
           $loader_array = new \Twig\Loader\ArrayLoader([$filename . '.twig' => $code]);
           $loader_filesystem = new \Twig\Loader\FilesystemLoader(DIR_TEMPLATE);
           $loader = new \Twig\Loader\ChainLoader([$loader_array, $loader_filesystem]);

		try {
			$twig = new \Twig\Environment($loader, $config);

			return $twig->render($filename . '.twig', $this->data);
		} catch (Exception $e) {
			trigger_error('Error: Could not load template ' . $filename . '!');
			exit();
		}
```

Also a PR is waiting for this ...
https://github.com/opencart/opencart/pull/8222

**Comment by condor2** [comment]
I don't think will be added...

https://github.com/opencart/opencart/pull/8106/files

**Comment by rickerd** [comment]
Any reasons why not? Because it works pretty good.
I can now use macro's to minimize copy/paste files.
I have a single thumb.twig file that I include in every product view.

**Comment by condor2** [comment]
https://github.com/opencart/opencart/pull/8106#issuecomment-662589022

**Comment by rickerd** [comment]
Not a valid reason what Daniel gives.
Due to the fact that there are to many templates.
It's completely crap that you should copy paste code and modify it.
Some things are better to use as a component, looking at React and Vue.

Sad that this works this way. I'm making this change by myself then. I love the way Twig works with macros and includes. Its the power of templating.
And if somebody doesn't understand it then it's probably not a developer but a regular shop owner who wants to cut prices making their own webshop.

I also don't build my own car, because I didn't learn for it.

End of discussion I think ;)

**Comment by danielkerr** [comment]
planning to use Vue after the next major release and will also be ready to launc the cloud then. my time will be much freer once its launched and i can begin to start hiring people to conetrate of fixing issues.

**Comment by rickerd** [comment]
I don’t think switching to Vue is the best option.
But for Gitlab it works pretty good.
Templating in Twig is great and jquery/vanilla js is also great.
Compiling scss and js is a great FE thing too.

I hope better days are coming for OpenCart.
I like it so far. Only some things are hidden in seperate modules or configs. Googleling it sometimes helps.
It’s impossible to make things perfect but you’ve done good so far.
Except for the Twig thing then ;)
