### ISSUE TITLE
Blank link if exist tags (product.twig)

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#8904]
**What version of OpenCart are you reporting this for?**
>3

**Describe the bug**
https://github.com/opencart/opencart/blob/a1d0880ad018c3e5bd39620b13dc5f0e6e038b53/upload/catalog/view/template/product/product.twig#L305

if tags exist then blank  link
<a href=""></a>

{% for i in 0..(tags|length - 1) %}

**Comment by danielkerr** [comment]
no idea what you are posting about!

all the tags are there! oinly is you leave an end , will there be a missing tag.

**Comment by mhcwebdesign** [comment]
I think he's right, it should indeed be

`{% for i in 0..(tags|length - 1) %}`

otherwise the for-loop will go one element beyond the tags array!

**Comment by dschuahan** [comment]
Thanks a lot  
it should be

{% for i in 0..(tags|length - 1) %}
