### ISSUE TITLE
Disabled language still loads in admin forms

### ISSUE THREAD

**Issue by xseon** [opencart/opencart#8905]
When you disable a language the admin forms continue to show its tab and ask for the required data to be filled in for that language as well. You need to fully delete the language in order to get rid of it in the admin forms.

**Comment by straightlight** [comment]
For which OC version are you addressing this?

**Comment by xseon** [comment]
All of them.

На вт, 17 ное 2020 г., 14:52 straightlight <notifications@github.com>
написа:

**Comment by condor2** [comment]
There are extensions to disable required fields on language like this for old version but can be easily changed for 3.x

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=22811

**Comment by osworx** [comment]
> 
> 
> There are extensions to disable required fields on language like this for old version but can be easily changed for 3.x
> 

Better: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=27975
(for 2.x & 3.x)

**Comment by xseon** [comment]
Nice, that's it, thanks! But isn't this something Opencart should have by
default? I think it should, that's why I reported it.


На ср, 18.11.2020 г. в 11:39 OSWorX <notifications@github.com> написа:

**Comment by condor2** [comment]
Yes...opencart should have many things....

**Comment by eMintis** [comment]
its not a bug, as many thing in OC you can enable and disable, it is advantage.

Use case: Install language > disable > make translation > enable.

**Comment by xseon** [comment]
I don't say it is a bug. I just say that since the disabled language
doesn't show up In the front-end it shouldn't show up in the back-end as
well.


На ср, 18.11.2020 г. в 22:04 eMintis <notifications@github.com> написа:

**Comment by osworx** [comment]
> 
> 
> its not a bug, as many thing in OC you can enable and disable, it is advantage.
> 
> Use case: Install language > disable > make translation > enable.

What kind of "advantage" is this when I disable a language (because I do not need and want it), but must provide all translations for this language?
The "use case" may be a nice feature IF there would be a switch for it.

**Comment by eMintis** [comment]
> 
> 
> > its not a bug, as many thing in OC you can enable and disable, it is advantage.
> > Use case: Install language > disable > make translation > enable.
> 
> What kind of "advantage" is this when I disable a language (because I do not need and want it), but must provide all translations for this language?
> The "use case" may be a nice feature IF there would be a switch for it.

i think this switch is "Uninstall language". If you add another On/Off functionality it will be too complicated. Also you can use extensions or modify forms or use script to copy data from one language to another.

Another thing you dont need to hold old unused data in DB, it is a problem then you have huge database.

*On remove language i think you do not remove data from database - might be wrong but not the case.
**Also OC can display products in front end without data, but breaks "page design".
***Presumptions made on OC 2.3.xx

**Comment by danielkerr** [comment]
its ment to do this.

**Comment by danielkerr** [comment]
it5 disables the languiage tio customers.

**Comment by xseon** [comment]
I suggested it should do it for both customers and admins.

На пт, 4.12.2020 г. в 7:47 ч. Daniel Kerr <notifications@github.com> написа:
