### ISSUE TITLE
php updating case and issue with opencart 

### ISSUE THREAD

**Issue by otlbni** [opencart/opencart#8907]
I Have an issue with OC 3.0.3.3 on Lamp web server ( Amazon Linux AMI ) after I had to update php from 7.0.3 to 7.3 and now the site its showing apache test page , admin panel not working too. so can you suggest me what can I do ?

**Comment by gnovaro** [comment]
I think is a configuration problem. Probably related with your VirtualHost public path.

**Comment by WebkulOpencart** [comment]
This is not an OpenCart issue. Please check with your server support.
