### ISSUE TITLE
Problem Coupon Code Cancels Orders Status if "total amount" different from "0"

### ISSUE THREAD

**Issue by bonny3** [opencart/opencart#8913]
**What version of OpenCart are you reporting this for?**
Opencart 2.3.0.2
**Describe the bug**
Hi,

i am having a problem with coupons,
this problem is present when "total amount" different from "0"
appears to be an Opencart bug in Coupon,
if I set "total amount" in Coupon for example to 69 Dollars
when the order with the coupon is generated and the status is changed to "complete"
automatically the Opencart bug returns it in "canceled"
the problem is generated by "total amount" different from "0"
I would like to know if you know a solution to this problem?

![2020-11-19_143752](https://user-images.githubusercontent.com/19350758/99735388-d32f9680-2ac4-11eb-8a18-dbccc0fe0980.jpg)

**Server / Test environment (please complete the following information):**
 - PHP 7.2
 - NGINX
 - Browsers tested with chrome, safari

**Comment by straightlight** [comment]
OC forum request.

**Comment by ADDCreative** [comment]
@bonny3 I don't believe it was ever fixed in version 2.3.0.2, only version 3 onwards. The official fix was https://github.com/opencart/opencart/commit/d28e1245516f6162a4226ec47d2ac64df75a9ed7 which may need tweaking a bit to work on 2.3.0.2, https://github.com/opencart/opencart/issues/3657#issuecomment-291151370.

There are also a few other suggested workarounds in https://github.com/opencart/opencart/issues/3657.

**Comment by bonny3** [comment]
> 
> 
> @bonny3 I don't believe it was ever fixed in version 2.3.0.2, only version 3 onwards. The official fix was [d28e124](https://github.com/opencart/opencart/commit/d28e1245516f6162a4226ec47d2ac64df75a9ed7) which may need tweaking a bit to work on 2.3.0.2, [#3657 (comment)](https://github.com/opencart/opencart/issues/3657#issuecomment-291151370).
> 
> There are also a few other suggested workarounds in #3657.

Hi,

I have copy file /catalog/model/extension/total/coupon.php from the new version i.e. 3.x
seems to work fine,
why do you say I should make changes?
can you specify what changes i should make?

Thanks

**Comment by bonny3** [comment]
> 
> 
> OC forum request.

your answer is not helpful to anyone.

**Comment by straightlight** [comment]
> > OC forum request.
> 
> your answer is not helpful to anyone.

This repository is for the master branch or the latest OC version from Opencart.com . Not for previous releases. Your question still should of been posted on the forum since you're using an older OC version.

**Comment by ADDCreative** [comment]
> Hi,
> 
> I have copy file /catalog/model/extension/total/coupon.php from the new version i.e. 3.x
> seems to work fine,
> why do you say I should make changes?
> can you specify what changes i should make?
> 
> Thanks

I'm not sure copying the file from version 3 file won't cause other problems. The changes you need make are here: 
https://github.com/opencart/opencart/commit/d28e1245516f6162a4226ec47d2ac64df75a9ed7 Delete the red lines, add the green. May also need some other changes. See: https://github.com/opencart/opencart/issues/3657#issuecomment-291151370

If you need more help, please do as @straightlight suggested and ask on https://forum.opencart.com/.

**Comment by straightlight** [comment]
The URL case and model conventional names won't be the same, still, between those versions.

**Comment by danielkerr** [comment]
the version is to old. here is only for development of the latest version.
