### ISSUE TITLE
PhpStand report master branch

### ISSUE THREAD

**Issue by gnovaro** [opencart/opencart#8919]
**What version of OpenCart are you reporting this for?**
master

**Describe the bug**
If you run phpstand alaysis

**To Reproduce**
Dowload php Stand:
composer require --dev phpstan/phpstan

Run:
php upload/system/storage/vendor/bin/phpstan analyse upload

**Expected behavior**
Run php code analysis

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development
 - Linux
 - PHP version: 7.4
 - Apache version: ---
 - Version: master branch

**Additional context**
	
 ------ ----------------------------------------
  Line   admin/controller/customer/customer.php
 ------ ----------------------------------------
  679    Undefined variable: $customer_info
 ------ ----------------------------------------

 ------ --------------------------------------------------------------------
  Line   admin/controller/mail/returns.php
 ------ --------------------------------------------------------------------
  45     Instantiated class Opencart\Engine\Library\Language not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ --------------------------------------------------------------------

 ------ --------------------------------------------------------------------
  Line   admin/controller/mail/reward.php
 ------ --------------------------------------------------------------------
  56     Instantiated class Opencart\Engine\Library\Language not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ --------------------------------------------------------------------

 ------ --------------------------------------------------------------------
  Line   admin/controller/mail/transaction.php
 ------ --------------------------------------------------------------------
  56     Instantiated class Opencart\Engine\Library\Language not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ --------------------------------------------------------------------

 ------ -------------------------------------------------------------------------------
  Line   admin/controller/marketplace/installer.php
 ------ -------------------------------------------------------------------------------
  212    Caught class Opencart\Application\Controller\Marketplace\Exception not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ -------------------------------------------------------------------------------

 ------ --------------------------------------------------------------------
  Line   admin/controller/sale/voucher.php
 ------ --------------------------------------------------------------------
  595    Instantiated class Opencart\Engine\Library\Language not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ --------------------------------------------------------------------

 ------ -----------------------------------
  Line   admin/controller/tool/upgrade.php
 ------ -----------------------------------
  172    Undefined variable: $directory
 ------ -----------------------------------

 ------ --------------------------------
  Line   admin/model/sale/recurring.php
 ------ --------------------------------
  167    Cannot use [] for reading.
  171    Cannot use [] for reading.
  175    Cannot use [] for reading.
  179    Cannot use [] for reading.
  183    Cannot use [] for reading.
  187    Cannot use [] for reading.
 ------ --------------------------------

 ------ ----------------------------------------------------------------------------------------------------
  Line   admin/model/tool/image.php
 ------ ----------------------------------------------------------------------------------------------------
  34     Class Opencart\System\Library\Image referenced with incorrect case: Opencart\System\library\Image.
 ------ ----------------------------------------------------------------------------------------------------

 ------ --------------------------------------------------------------------
  Line   catalog/controller/api/login.php
 ------ --------------------------------------------------------------------
  31     Instantiated class Opencart\Engine\Library\Session not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ --------------------------------------------------------------------

 ------ ----------------------------------------------------------------------------------------------------
  Line   catalog/model/tool/image.php
 ------ ----------------------------------------------------------------------------------------------------
  34     Class Opencart\System\Library\Image referenced with incorrect case: Opencart\System\library\Image.
 ------ ----------------------------------------------------------------------------------------------------

 ------ --------------------------------------------------------------------
  Line   install/cli_install.php
 ------ --------------------------------------------------------------------
  291    Caught class Install\ErrorException not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ --------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------
  Line   install/controller/install/step_3.php
 ------ ---------------------------------------------------------------------------
  304    Caught class Opencart\Application\Controller\Install\Exception not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ ---------------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------------------------------------------------
  Line   install/controller/startup/install.php
 ------ ---------------------------------------------------------------------------------------------------------------------
  5      Class Opencart\System\Library\Document does not have a constructor and must be instantiated without any parameters.
 ------ ---------------------------------------------------------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------
  Line   install/controller/upgrade/upgrade.php
 ------ ---------------------------------------------------------------------------
  61     Caught class Opencart\Application\Controller\Upgrade\Exception not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ ---------------------------------------------------------------------------

 ------ ------------------------------------------
  Line   install/model/upgrade/upgrade_1004.php	
 ------ ------------------------------------------
  253    Syntax error, unexpected ')' on line 253
 ------ ------------------------------------------

 ------ --------------------------------------------------------------------
  Line   system/engine/event.php
 ------ --------------------------------------------------------------------
  65     Class Opencart\System\Engine\Exception not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ --------------------------------------------------------------------

 ------ ---------------------------------------------------------------
  Line   system/helper/utf8.php
 ------ ---------------------------------------------------------------
  123    Array has 3 duplicate keys with value 222 (0xde, 0xde, 0xde).
  169    Array has 3 duplicate keys with value 208 (0xd0, 0xd0, 0xd0).
  185    Array has 2 duplicate keys with value 923 (0x39b, 0x39b).
  204    Array has 2 duplicate keys with value 1031 (0x407, 0x407).
  359    Array has 3 duplicate keys with value 254 (0xfe, 0xfe, 0xfe).
  405    Array has 3 duplicate keys with value 240 (0xf0, 0xf0, 0xf0).
  421    Array has 2 duplicate keys with value 955 (0x3bb, 0x3bb).
  440    Array has 2 duplicate keys with value 1111 (0x457, 0x457).
 ------ ---------------------------------------------------------------

 ------ -------------------------------------------------------------------------------
  Line   system/library/cart/cart.php
 ------ -------------------------------------------------------------------------------
  7      Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  8      Access to an undefined property Opencart\System\Library\Cart\Cart::$customer.
  9      Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  10     Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  11     Access to an undefined property Opencart\System\Library\Cart\Cart::$tax.
  12     Access to an undefined property Opencart\System\Library\Cart\Cart::$weight.
  35     Access to an undefined property Opencart\System\Library\Cart\Cart::$customer.
  35     Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  35     Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  35     Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  35     Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  40     Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  40     Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  40     Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  63     Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  63     Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  67     Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  67     Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  112    Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  112    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  189    Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  189    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  196    Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  196    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  203    Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  203    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  214    Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  214    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  230    Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  230    Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  230    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  287    Access to an undefined property Opencart\System\Library\Cart\Cart::$customer.
  287    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  287    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  287    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  287    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  287    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  290    Access to an undefined property Opencart\System\Library\Cart\Cart::$customer.
  290    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  290    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  290    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  290    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  290    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  292    Access to an undefined property Opencart\System\Library\Cart\Cart::$customer.
  292    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  292    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  292    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  292    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  292    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  299    Access to an undefined property Opencart\System\Library\Cart\Cart::$customer.
  299    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  299    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  299    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  299    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  305    Access to an undefined property Opencart\System\Library\Cart\Cart::$customer.
  305    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  305    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  305    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  305    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  311    Access to an undefined property Opencart\System\Library\Cart\Cart::$customer.
  311    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  311    Access to an undefined property Opencart\System\Library\Cart\Cart::$db.
  311    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  311    Access to an undefined property Opencart\System\Library\Cart\Cart::$session.
  333    Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  333    Access to an undefined property Opencart\System\Library\Cart\Cart::$weight.
  355    Access to an undefined property Opencart\System\Library\Cart\Cart::$tax.
  374    Access to an undefined property Opencart\System\Library\Cart\Cart::$config.
  374    Access to an undefined property Opencart\System\Library\Cart\Cart::$tax.
 ------ -------------------------------------------------------------------------------

 ------ -----------------------------------------------------------------------------------
  Line   system/library/cart/currency.php
 ------ -----------------------------------------------------------------------------------
  7      Access to an undefined property Opencart\System\Library\Cart\Currency::$db.
  8      Access to an undefined property Opencart\System\Library\Cart\Currency::$language.
  47     Access to an undefined property Opencart\System\Library\Cart\Currency::$language.
  47     Access to an undefined property Opencart\System\Library\Cart\Currency::$language.
 ------ -----------------------------------------------------------------------------------

 ------ ----------------------------------------------------------------------------------
  Line   system/library/cart/customer.php
 ------ ----------------------------------------------------------------------------------
  14     Access to an undefined property Opencart\System\Library\Cart\Customer::$config.
  15     Access to an undefined property Opencart\System\Library\Cart\Customer::$db.
  16     Access to an undefined property Opencart\System\Library\Cart\Customer::$request.
  17     Access to an undefined property Opencart\System\Library\Cart\Customer::$session.
  40     Access to an undefined property Opencart\System\Library\Cart\Customer::$db.
  40     Access to an undefined property Opencart\System\Library\Cart\Customer::$db.
  55     Access to an undefined property Opencart\System\Library\Cart\Customer::$db.
  55     Access to an undefined property Opencart\System\Library\Cart\Customer::$db.
  59     Access to an undefined property Opencart\System\Library\Cart\Customer::$session.
  70     Access to an undefined property Opencart\System\Library\Cart\Customer::$config.
  70     Access to an undefined property Opencart\System\Library\Cart\Customer::$db.
  70     Access to an undefined property Opencart\System\Library\Cart\Customer::$db.
  70     Access to an undefined property Opencart\System\Library\Cart\Customer::$request.
  79     Access to an undefined property Opencart\System\Library\Cart\Customer::$session.
  128    Access to an undefined property Opencart\System\Library\Cart\Customer::$db.
  134    Access to an undefined property Opencart\System\Library\Cart\Customer::$db.
 ------ ----------------------------------------------------------------------------------

 ------ -------------------------------------------------------------------------------
  Line   system/library/cart/length.php
 ------ -------------------------------------------------------------------------------
  7      Access to an undefined property Opencart\System\Library\Cart\Length::$db.
  8      Access to an undefined property Opencart\System\Library\Cart\Length::$config.
 ------ -------------------------------------------------------------------------------

 ------ ----------------------------------------------------------------------------
  Line   system/library/cart/tax.php
 ------ ----------------------------------------------------------------------------
  7      Access to an undefined property Opencart\System\Library\Cart\Tax::$config.
  8      Access to an undefined property Opencart\System\Library\Cart\Tax::$db.
  16     Access to an undefined property Opencart\System\Library\Cart\Tax::$config.
  16     Access to an undefined property Opencart\System\Library\Cart\Tax::$db.
  30     Access to an undefined property Opencart\System\Library\Cart\Tax::$config.
  30     Access to an undefined property Opencart\System\Library\Cart\Tax::$db.
  44     Access to an undefined property Opencart\System\Library\Cart\Tax::$config.
  44     Access to an undefined property Opencart\System\Library\Cart\Tax::$db.
  90     Access to an undefined property Opencart\System\Library\Cart\Tax::$db.
 ------ ----------------------------------------------------------------------------

 ------ ------------------------------------------------------------------------------
  Line   system/library/cart/user.php
 ------ ------------------------------------------------------------------------------
  10     Access to an undefined property Opencart\System\Library\Cart\User::$db.
  11     Access to an undefined property Opencart\System\Library\Cart\User::$request.
  12     Access to an undefined property Opencart\System\Library\Cart\User::$session.
  40     Access to an undefined property Opencart\System\Library\Cart\User::$db.
  40     Access to an undefined property Opencart\System\Library\Cart\User::$db.
  54     Access to an undefined property Opencart\System\Library\Cart\User::$db.
  54     Access to an undefined property Opencart\System\Library\Cart\User::$db.
  57     Access to an undefined property Opencart\System\Library\Cart\User::$session.
  63     Access to an undefined property Opencart\System\Library\Cart\User::$db.
  80     Access to an undefined property Opencart\System\Library\Cart\User::$session.
 ------ ------------------------------------------------------------------------------

 ------ -------------------------------------------------------------------------------
  Line   system/library/cart/weight.php
 ------ -------------------------------------------------------------------------------
  7      Access to an undefined property Opencart\System\Library\Cart\Weight::$db.
  8      Access to an undefined property Opencart\System\Library\Cart\Weight::$config.
 ------ -------------------------------------------------------------------------------

 ------ -------------------------------------------------------------------------
  Line   system/library/mail.php
 ------ -------------------------------------------------------------------------
  34     Access to an undefined property Opencart\System\Library\Mail::$adaptor.
  139    Access to an undefined property Opencart\System\Library\Mail::$adaptor.
  142    Access to an undefined property Opencart\System\Library\Mail::$adaptor.
 ------ -------------------------------------------------------------------------

 ------ ----------------------------------------------------------------------------------
  Line   system/library/mail/mail.php
 ------ ----------------------------------------------------------------------------------
  7      Access to an undefined property Opencart\System\Library\Mail\Mail::$to.
  17     Access to an undefined property Opencart\System\Library\Mail\Mail::$from.
  17     Access to an undefined property Opencart\System\Library\Mail\Mail::$sender.
  19     Access to an undefined property Opencart\System\Library\Mail\Mail::$reply_to.
  20     Access to an undefined property Opencart\System\Library\Mail\Mail::$from.
  20     Access to an undefined property Opencart\System\Library\Mail\Mail::$sender.
  25     Access to an undefined property Opencart\System\Library\Mail\Mail::$from.
  29     Access to an undefined property Opencart\System\Library\Mail\Mail::$html.
  33     Access to an undefined property Opencart\System\Library\Mail\Mail::$text.
  41     Access to an undefined property Opencart\System\Library\Mail\Mail::$text.
  54     Access to an undefined property Opencart\System\Library\Mail\Mail::$attachments.
  74     Access to an undefined property Opencart\System\Library\Mail\Mail::$from.
  77     Access to an undefined property Opencart\System\Library\Mail\Mail::$subject.
  79     Access to an undefined property Opencart\System\Library\Mail\Mail::$subject.
 ------ ----------------------------------------------------------------------------------

 ------ ----------------------------------------------------------------------------------
  Line   system/library/mail/smtp.php
 ------ ----------------------------------------------------------------------------------
  13     Access to an undefined property Opencart\System\Library\Mail\Smtp::$to.
  23     Access to an undefined property Opencart\System\Library\Mail\Smtp::$subject.
  25     Access to an undefined property Opencart\System\Library\Mail\Smtp::$from.
  25     Access to an undefined property Opencart\System\Library\Mail\Smtp::$sender.
  27     Access to an undefined property Opencart\System\Library\Mail\Smtp::$reply_to.
  28     Access to an undefined property Opencart\System\Library\Mail\Smtp::$from.
  28     Access to an undefined property Opencart\System\Library\Mail\Smtp::$sender.
  33     Access to an undefined property Opencart\System\Library\Mail\Smtp::$from.
  37     Access to an undefined property Opencart\System\Library\Mail\Smtp::$html.
  41     Access to an undefined property Opencart\System\Library\Mail\Smtp::$text.
  49     Access to an undefined property Opencart\System\Library\Mail\Smtp::$text.
  62     Access to an undefined property Opencart\System\Library\Mail\Smtp::$attachments.
 ------ ----------------------------------------------------------------------------------

 ------ ----------------------------------------------------------------------------
  Line   system/library/request.php
 ------ ----------------------------------------------------------------------------
  27     Access to an undefined property Opencart\System\Library\Request::$request.
 ------ ----------------------------------------------------------------------------

 ------ --------------------------------------------------------------------------
  Line   system/library/session/db.php
 ------ --------------------------------------------------------------------------
  16     Access to an undefined property Opencart\System\Library\Session\DB::$db.
  22     Access to an undefined property Opencart\System\Library\Session\DB::$db.
  22     Access to an undefined property Opencart\System\Library\Session\DB::$db.
  22     Access to an undefined property Opencart\System\Library\Session\DB::$db.
  33     Access to an undefined property Opencart\System\Library\Session\DB::$db.
  33     Access to an undefined property Opencart\System\Library\Session\DB::$db.
  33     Access to an undefined property Opencart\System\Library\Session\DB::$db.
  33     Access to an undefined property Opencart\System\Library\Session\DB::$db.
  40     Access to an undefined property Opencart\System\Library\Session\DB::$db.
  40     Access to an undefined property Opencart\System\Library\Session\DB::$db.
  61     Access to an undefined property Opencart\System\Library\Session\DB::$db.
  61     Access to an undefined property Opencart\System\Library\Session\DB::$db.
 ------ --------------------------------------------------------------------------

 ------ ----------------------------------------------------------------------------
  Line   system/library/template/twig.php
 ------ ----------------------------------------------------------------------------
  102    Caught class Opencart\System\Library\Template\Twig_Error_Syntax not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ ----------------------------------------------------------------------------

**Comment by danielkerr** [comment]
i think fixed or the data is outdated
