### ISSUE TITLE
[Master Branch] ONLY_FULL_GROUP_BY issue

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#8921]
**What version of OpenCart are you reporting this for?**
Master branch 4.0.0.0b

**Describe the bug**
A frequent cause of errors when migrating to MySQL 5.7 or 8.0 is that 5.7 has a default SQL mode that is more restrictive than 5.6, and as such it’s for 8.0. Because of this certain SQL queries using the GROUP BY clause need to be reworked. The SELECT list can only include column names which are also listed in the GROUP BY clause.

**Example on how to reproduce**
1. Go to admin backend's dashboard page
2. That one will come with this error:
_<b>Exception</b>: Error: Expression # 2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'opencart_4-0-0-0-b.oc_order.date_added' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by<br />Error No: 1055<br />SELECT COUNT(*) AS total, `date_added` FROM `oc_order` WHERE `order_status_id` IN('5','3') AND DATE(`date_added`) >= '2020-11-1' GROUP BY DATE(`date_added`)_

**Server / Test environment (please complete the following information):**
 - Linux Mint 18.3 Sylvia
 - PHP version 7.3.19-1+ubuntu16.04.1+deb.sury.org+1
 - Apache/2.4.18 (Ubuntu) 
 - Firefox 83.0 (64-bit)
 - MySql 5.7.32-0ubuntu0.16.04.1 - (Ubuntu) 

**Additional context**
Other admin pages with a similar issue include:
Home > Resports > Sales Report
Home > Resports > Products Purchased Report

There might be more, I haven't yet fully gone through all the DB queries which use the GROUP BY.

**Comment by straightlight** [comment]
It looks like not only PHP is enforcing more distinctive queries but also the case for Oracle if being the case that MySQL 5.7 might be more restrictive than previous releases.

**Comment by danielkerr** [comment]
im pretty sure this was fixed with 

			$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");
