### ISSUE TITLE
Installation via FreeBSD documentation is missing, it is a listed port, when trying to install creates problems by trying to uninstall php74 and installing php72 instead. Therefore does not seem to work with latest software. Manual installation has bugs, it is not plug and play.

### ISSUE THREAD

**Issue by prepstarr** [opencart/opencart#8924]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

in FreeBSD, one simply should type pkg install opencart and then proceed to setting up opencart

Problem 1: OpenCart does not give any recognition to FreeBSD as such the instructions on how to install it are unclear
Problem 2: OpenCart tries to uninstall up to date versions of php in favor of older versions which if someone had a site with multiple applications , ie. a forums page and a shopping cart, the forums page works on the current version of php they would then have to sacrifice their system to work with an old version . or create a jail just for open cart... 
Problem 3: manual installation is buggy it seems to require rewriting and learning the entire control flow logic of the program at this point it may be more worthwhile for 1 to recreate a program that works to one's liking and be spared of advertisements, etc..

**To Reproduce**
1. Go to opencart.com or whatever the website is , lack of documentation
2. freebsd type something like pkg install opencart , look it up in ports directory freebsd.org, causes problems
3.  use sftp or ftp and transfer over an unzipped or zipped version, zipped version unzip and unzipped then try to work it you will need to debug the entire code 

**Expected behavior**
A nice plug and play shopping experience where I could list products and have a shopping cart running in 2 days without getting too heavily involved in all the coding...

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system freebsd 12
 - PHP version 7.4
 - Apache version 2.43
 - Browser(s) tested with [e.g. chrome, safari - if applicable] microsoft
 - Version [e.g. 22] latest repository

**Additional context**

**Comment by chongshengdz** [comment]
it has nothing to do with opencart, it may be something wrong with your PHP installation.

**Comment by danielkerr** [comment]
opencart is a web script that runs in php. running php, mysql, etc.. on freebsd has nothing to do with opencart.
