### ISSUE TITLE
Broken product descriptions in opencart

### ISSUE THREAD

**Issue by flagg2** [opencart/opencart#8930]
Hello, today I installed a google analytics addon (which i have already removed) and tampered with my htaccess file.

My problem is, when I did these 2 things, my product descriptions (which seem totally unrelated) broke and now there is php code instead of html visible to the user on my website. It looks something like [this](https://detiazahrada.sk/jungle-gym-peak)

Could anyone please help me figure out why the description is not showing correctly? I would really appreciate it.

**Comment by Khnaz35** [comment]
Have you revert back the changes and clear all your caches and refresh modifications ?

**Comment by flagg2** [comment]
Hello, I uninstalled both plugins , then went to modifications and refreshed them. The descriptions are still broken. Is that enough or did I do something wrong?

**Comment by Khnaz35** [comment]
Can't really say without having look at it. send me email to khnaz35@gmail.com

**Comment by eka7a** [comment]
Use the forum for such topics.
