### ISSUE TITLE
Branch[3.0.x.x_Maintenance] [Notice Error] : at the customer login page, When change the email/password text field "name" then on submission it is showing the notice error

### ISSUE THREAD

**Issue by Webkul-Opencart** [opencart/opencart#8933]
**What version of OpenCart are you reporting this for?**
Test Environment--
-- opencart version: Version 3.0.3.6

**Describe the bug**
at the customer login page, when change the text field "name" value to some another name value for email & password field then on click on "login" button it is showing the notice error.

**To Reproduce**
1. Go to 'customer login page'
2. fill the correct details for customer login
3. in the developer tools, change the text field "name" value to some another value for email & password field
4. click on 'login button'
5. then it shows the notice error

**Expected behavior**
It must not show any notice error, only warning message should be display.

**Screenshots / Screen recordings**
1. change the email/password text field name value:
![Selection_424-png-1303×709-](https://user-images.githubusercontent.com/42890212/100412701-622b4880-309b-11eb-9ad0-4beed3ffaf8e.png)
2. email field notice error:
![Screenshot82](https://user-images.githubusercontent.com/42890212/100412822-b2a2a600-309b-11eb-8122-6e27c3c8c00c.png)
3. password field notice error: 
![Screenshot81](https://user-images.githubusercontent.com/42890212/100412846-c4844900-309b-11eb-9189-e96fe9277784.png)

**Server / Test environment (please complete the following information):**
 opencart version: 3.0.3.6
operating system: Ubuntu 16.04 LTS
PHP version-- 7.4.11
browser/browser version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by danielkerr** [comment]
do not do this! u should not be trying to fix bugs on oc if this is ur stupied soultion to fix a non issue.

**Comment by danielkerr** [comment]
u understand that error reporting will be off on production sites.
