### ISSUE TITLE
Order Email Message goes into junk folder in @gmail.com

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#8940]
Hello.

From beginning of this year, many owner of stores complain that order email messages send via OpenCart v1, v2 and v3 to @gmail.com goes into junk folder.

We have solved this problem with using SMTP instead MAIL.

Should email message redesign?
Any idea?
Please can you check if you have similar problem?

Thank you.

Note: Problem can be related with Google or software updates.

**Comment by stalker780** [comment]
This is mostly because your old SMTP server was configured wrong and got to spam/block lists.

Letter design have no impact to reaching recipient Inbox.

**Comment by faca5** [comment]
This is not true.

Email send via SMTP goes to INBOX.

This problem has only 1/10 stop owners.

**Comment by ADDCreative** [comment]
@faca5 Use an online "email deliverability tester" and check both Mail and SMTP. That should tell you if there is any issue with outgoing email.

**Comment by faca5** [comment]
Thank you for advice.

**Comment by straightlight** [comment]
Server-specifics.

**Comment by faca5** [comment]
Difference between MAIL() and SMTP() is only "HEADER_FROM_DIFFERENT_DOMAINS".
Tested with mail-tester.com.

**Comment by ADDCreative** [comment]
Best to ask on https://forum.opencart.com/. It will be dependent on email domain, server domain, server set up and OpenCart "Mail Parameters" setting.
