### ISSUE TITLE
[Feature] Events + Description Field

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#8941]
Because of the fact, that more and more events are used (good, becuase those odd VQ- & OCMods are not requried anymore), it would be good to have an additional field called **Description**.

Why?
The more and more events are registered and used, nobody can see what for they are!
A description (varchar = 255) should be enough.
And as developer it costs me a lot of time to go always into the code and database to see and check what these events are for and doing.

thx in advance!

**Comment by chulcha** [comment]
Not a description or comments
But also search, filter and more, for example, editing the order of application (sorting), the ability to on/off

**Comment by osworx** [comment]
> 
> 
> Not a description or comments
> But also search, filter and more, for example, editing the order of application (sorting), the ability to on/off

You mean instead "Not" a "Not only " .. ?
And on/off is already given, but other things  like search, filter and editing would be good.
Maybe I make a new Extension for such, because the one that exists is depending on another library (which not be should!) and "overbloaded" and make after a pull request to this repo ..

**Comment by chulcha** [comment]
Not only " .. ?

YES!!!

**Comment by danielkerr** [comment]
sure
