### ISSUE TITLE
Missing email_total in switch "customer" case

### ISSUE THREAD

**Issue by antoniofacciutiIYL** [opencart/opencart#8942]
In OC 3.0.3.6 when I'm sending emails in admin panel (marketing/contact) if I choose "customer", after mails were sent the alert message in variable "text_sent" are not showing the number of contacts reached.

i see in admin/controller/marketing/contact there isn't "$email_total" variable in switch case "customer" and "affiliate"

![image](https://user-images.githubusercontent.com/72383285/100723237-cf9fe780-33c1-11eb-9145-0d412556f9ad.png)

I also have a question, i'd forked OC's repository in local and I see "3.0.x.x Maintenance", but i misunderstanding how it works and if i have to merge OC3.0.3.6 to Maintenance branch. 
I don't know if there is already a documentation about OC branches, i'm still searching, but if someone have a solution or a link to docs it helps me and my team to work with this repo.

**Comment by straightlight** [comment]
Already fixed on the master branch.

**Comment by ADDCreative** [comment]
@antoniofacciutiIYL There are a few of commits that may be relevant. First. https://github.com/opencart/opencart/pull/8203

Also a commit here. Which is added to 3.0.x.x Maintenance, but not master, for some reason. https://github.com/opencart/opencart/issues/8836

There is also this change which seems to have been released in a version of 3.0.3.4, but never committed. https://github.com/opencart/opencart/issues/8016
