### ISSUE TITLE
OC4 MySQL/MariaDB issues

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#8944]
When saving a product in admin get SQL errors:

Does not accept empty values if default is not set
```
Exception: Error: Field 'value' doesn't have a default value
Error No: 1364
INSERT INTO `oc_product_option` SET `product_option_id` = '218', `product_id` = '42', `option_id` = '1', `required` = '1' in \system\library\db\mysqli.php on line 46
```

Does not accept empty string '' dates
```
Exception: Error: Incorrect date value: '' for column `oc40`.`oc_product_discount`.`date_start` at row 1
Error No: 1292
INSERT INTO `oc_product_discount` SET `product_id` = '42', `customer_group_id` = '1', `quantity` = '10', `priority` = '1', `price` = '88', `date_start` = '', `date_end` = '' in \system\library\db\mysqli.php on line 46
```

```
Exception: Error: Incorrect date value: '' for column `oc40`.`oc_product_special`.`date_start` at row 1
Error No: 1292
INSERT INTO `oc_product_special` SET `product_id` = '42', `customer_group_id` = '1', `priority` = '1', `price` = '90', `date_start` = '', `date_end` = '' in \system\library\db\mysqli.php on line 46
```

Windows 10 / PHP 7.3.25 / MariaDB 10.5.8

**Comment by danielkerr** [comment]
is this not a sql setting issue. set strict mode off.

**Comment by stalker780** [comment]
@danielkerr 

sql_mode is absent in my.ini, so default is used.

Perhaps OpenCart should set needed sql_mode on connection init?

Otherwise you will get tons of error reports after release. Cause this worked in previous OC versions, and a few of users will understand that MySQL configurations have to be changed. 
Also it may be an issue for users of shared hosting, where it is impossible to configure MySQL.


Just add one line to mysqli::__construct
```
$this->connection->report_mode = MYSQLI_REPORT_STRICT;
$this->connection->query("SET sql_mode = 'NO_ENGINE_SUBSTITUTION';");
```

**Comment by danielkerr** [comment]
added fix https://github.com/opencart/opencart/commit/ee125bbca55612fac48b779507038fe2ed46f033
