### ISSUE TITLE
ajuste conflito PHP 7.3+

### ISSUE THREAD

**Issue by DenisCunha** [opencart/opencart#8948]
when an empty value is posted or text, php 73 is treating it as a warning error, to solve the problem edit the file catalog / controller / product / category.php

Warning: A non-numeric value encountered in /home/ocdemo/public_html/catalog/controller/product/category.php on line 157Warning: A non-numeric value encountered in /home/ocdemo/public_html/catalog/controller/product/category.php on line 332Warning: A non-numeric value encountered in /home/ocdemo/public_html/catalog/controller/product/category.php on line 332Warning: A non-numeric value encountered in /home/ocdemo/public_html/catalog/controller/product/category.php on line 332Warning: A non-numeric value encountered in /home/ocdemo/public_html/catalog/controller/product/category.php on line 346

Solution:

after the code:

if (isset ($ this-> request-> get ['page'])) {
$ page = $ this-> request-> get ['page'];
} else {
$ page = 1;
}

include

if (! is_numeric ($ page)) {
$ page = 1;
}

**Comment by straightlight** [comment]
Already fixed on the master branch.

```if (isset($this->request->get['page'])) {
			$page = (int)$this->request->get['page'];
		} else {
			$page = 1;
		}```

You are not posting for the master branch.

**Comment by danielkerr** [comment]
or force type it (int)

**Comment by danielkerr** [comment]
+
