### ISSUE TITLE
Where Make sure its only the last event

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#8950]
https://github.com/opencart/opencart/blob/c8af11aedf4b24c01bcae36b4647e3b559074a91/upload/system/engine/loader.php#L73

`if (!is_null($result) && !($result instanceof Exception)) {`

**Comment by WebkulOpencart** [comment]
Please always mention the OpenCart version you are reporting

**Comment by danielkerr** [comment]
sort order 99999

**Comment by danielkerr** [comment]
i think he means master but set the event to be the last call set the sort order  controller/*/*/before and sort order to a high number. it depends what u are doing.
