### ISSUE TITLE
Product image cache isn't working with PHP 8.0

### ISSUE THREAD

**Issue by Philio** [opencart/opencart#8952]
I installed a fresh install of OpenCart yesterday on a server with Ubuntu 20.04 and PHP 8.0.
Image cache for product images is not working correctly.
Other images are generated as expected, e.g. admin profile pic, banners and manufacturer logos.
Switched the site config in Nginx to use PHP 7.4 instead and images appeared in the cache folder.
There are no errors or warnings in PHP log or site logs.

**Comment by MartinIsAmazing** [comment]
Hello,
Same situation here.

**Comment by chongshengdz** [comment]
just tested.
Same situation here with php 8.0.

**Comment by danielkerr** [comment]
has GD been removed? any error messages?

**Comment by danielkerr** [comment]
will test.

**Comment by chongshengdz** [comment]
> has GD been removed? any error messages?

GD must be installed before we can install opencart.
no error messages.

**Comment by chongshengdz** [comment]
by the way, have you tested the seo url yet?
a new year is coming.

**Comment by danielkerr** [comment]
will do.

**Comment by danielkerr** [comment]
checking this now. seo is 1/2 fixed. information pages .loaded via ajax are not working. will fix.

**Comment by danielkerr** [comment]
strange gd in php8 is not working as before.

**Comment by chongshengdz** [comment]
> strange gd in php8 is not working as before.

https://github.com/opencart/opencart/issues/8988#issuecomment-748978637
it was resolved here.

**Comment by danielkerr** [comment]
fixed with latest commit.
