### ISSUE TITLE
Failed to install at route=install/step_3

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#8954]
**What version of OpenCart are you reporting this for?**

Master branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

PHP Fatal error:  Uncaught Exception: Error: Field 'description' doesn't have a default value<br />Error No: 1364<br />INSERT INTO `oc_event` (`code`, `trigger`, `action`, `status`) VALUES('activity_customer_add', 'catalog/model/account/customer/addCustomer/after', 'event/activity|addCustomer', 1),('activity_customer_edit', 'catalog/model/account/customer/editCustomer/after', 'event/activity|editCustomer', 1),('activity_customer_password', 'catalog/model/account/customer/editPassword/after', 'event/activity|editPassword', 1),('activity_customer_forgotten', 'catalog/model/account/customer/editCode/after', 'event/activity|forgotten', 1),('activity_transaction', 'catalog/model/account/customer/addTransaction/after', 'event/activity|addTransaction', 1),('activity_customer_login', 'catalog/model/account/customer/deleteLoginAttempts/after', 'event/activity|login', 1),('activity_address_add', 'catalog/model/account/address/addAddress/after', 'event/activity|addAddress', 1),('activity_address_edit', 'catalog/model/account/address/edit in ../system/library/db/mysqli.php on line 46

**To Reproduce**
1. Go to '../install/'

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by Hkr32** [comment]
https://github.com/opencart/opencart/pull/8949

**Comment by cgcmart** [comment]
@Hkr32 Thank your contribution. It's the solution.
