### ISSUE TITLE
Broken links in developer page

### ISSUE THREAD

**Issue by prosenjeet123** [opencart/opencart#8956]
The **DIY Module builder** link is broken in the developer page 
URL: http://docs.opencart.com/en-gb/developer/module/

![image](https://user-images.githubusercontent.com/12624294/101494248-132fbe00-398d-11eb-830c-bdef340aa466.png)

**Comment by Hkr32** [comment]
It would be nice to update the documentation and expand it. Can be rewritten to gohugo.io.

**Comment by danielkerr** [comment]
yes i have have asked a company to give me a quote to rewrite it all.
