### ISSUE TITLE
Theme Editor is not working

### ISSUE THREAD

**Issue by jintianking** [opencart/opencart#8957]
OpenCart v4.0.0.0_b

Theme Editor is not working.

1.Design->Theme Editor 
2.Choose a twig, eg:common / header.twig  
3. Save
![image](https://user-images.githubusercontent.com/75728203/101618457-f6f35600-3a4c-11eb-8f09-a41c6219ab68.png)
4.visit home page.
![image](https://user-images.githubusercontent.com/75728203/101618590-2bffa880-3a4d-11eb-9f19-af9ba0434128.png)

**Comment by danielkerr** [comment]
no error for me.

**Comment by jintianking** [comment]
I have test again, it's still working wrong.
I have downloaded and installed the latest code for 4.0.0.0_b in localhost and web server.

**Comment by danielkerr** [comment]
check the config.php in the admin to make sure the paths are correct.  nobody else is reporting this. i don't think this is a fresh build.

**Comment by jintianking** [comment]
I have downloaded v3.0.3.6 and  v4.0.0.0_b Code, new install and test again, the same action,  Theme Editor v3.0.3.6 is correct, but v4.0.0.0_b is wrong.

**Comment by jintianking** [comment]
@danielkerr

**Comment by SaifAlSubhi** [comment]
Note: actually, this error is still exist with master-branch up-to-date.

**Comment by danielkerr** [comment]
Saifalsubhi everything u report is wrong
