### ISSUE TITLE
Is ocmod working?

### ISSUE THREAD

**Issue by jintianking** [opencart/opencart#8958]
OpenCart v4.0.0.0_b

![image](https://user-images.githubusercontent.com/75728203/101619608-7897b380-3a4e-11eb-8c1f-71dbff213090.png)

is not working

**Comment by asmaDur-01** [comment]
if ocmod is not working, you can replacing it by yourself in header.twig file without installing the .ocmod file in admin panel

**Comment by danielkerr** [comment]
yes. it uses a new system i have not written documentation for yet.
