### ISSUE TITLE
Move the db_schema.php

### ISSUE THREAD

**Issue by pixel-s-lab** [opencart/opencart#8959]
I don't see why **db_schema.php** should be in **system / helper** . My opinion is that it should be moved to the **install** folder.
Something like that install/db/db_schema.php 

And in loader.php adding a new function
	
public function install($route) {
		$file = DIR_OPENCART . 'install/db/' . preg_replace('/[^a-zA-Z0-9_\/]/', '', (string)$route) . '.php';

		if (is_file($file)) {
			include_once($file);
		} else {
			throw new \Exception('Error: Could not load helper ' . $route . '!');
		}
	}

**Comment by straightlight** [comment]
Yes, good point. Even perhaps in the install root folder itself since opencart.sql file is also located in the same place out-of-the-box.

**Comment by cgcmart** [comment]
I don't agree. Helper is good for later reference to find out db error after installation and deletion of install folder.
opencart.sql in install folder is for demo data in fresh installation.

**Comment by straightlight** [comment]
That'd still be intact on the master branch.

**Comment by diegospm** [comment]
the ideal would be to have migrations and seeders :)

**Comment by danielkerr** [comment]
i think i use it outside of the installer folder.
