### ISSUE TITLE
Contact Form - Missing Successful text

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#8960]
Latest version v3.0.3.6!

Tested on:
https://demo.opencart.com/index.php?route=information/contact/success

Missing text "The request was successfully sent to the store owner!" once you submit contact form.

Only v2 works!

**Comment by faca5** [comment]
Solution!

Rename from "text_success" to "text_message".

Example:
from
$_['text_success']   = '<p>Your enquiry has been successfully sent to the store owner!</p>';
to
$_['text_message']   = '<p>Your enquiry has been successfully sent to the store owner!</p>';

**Comment by ADDCreative** [comment]
https://github.com/opencart/opencart/commit/2f93e6a7c85e7062fb9d682d8374a8f8e3087465#diff-2ecedb4996c430858e46b16391b2c938d42e318a413f86cd90461c700b602209

https://github.com/opencart/opencart/commit/abaaf8942b3d9d4b50c0b7869e0347ee8534452f#diff-2ecedb4996c430858e46b16391b2c938d42e318a413f86cd90461c700b602209
