### ISSUE TITLE
PHP 8 - MAIL()

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#8968]
Hello.

Sending email using default settings via mail() in PHP 8.

Message is like:
------=_NextPart_10f35f1c84da9c502da0c116e7c79d9d
Content-Type: multipart/alternative; boundary="----=_NextPart_10f35f1c84da9c502da0c116e7c79d9d_alt"

------=_NextPart_10f35f1c84da9c502da0c116e7c79d9d_alt
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit

This is a HTML email and your email client software does not support HTML email!
------=_NextPart_10f35f1c84da9c502da0c116e7c79d9d_alt
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 8bit

Using SMTP() works normal.

**Comment by danielkerr** [comment]
u need to provide more detauils.

**Comment by evaland999** [comment]
> 
> 
> u need to provide more detauils.

Dear danielkerr ,
So sorry bother your time,But I got the same issue.
I using 3.0.3.7,
PHP8.0
I made a simple video to show how problem,if you can please check it
I spent many days try to figure out how to fix,But fail

https://youtu.be/wMrzL1Kqqgo

**Comment by danielkerr** [comment]
Webkul is doing another maintenance release

**Comment by danielkerr** [comment]
I'm working on opencart 4 and will be php8 only

**Comment by faca5** [comment]
Perfect! PHP 8.

**Comment by evaland999** [comment]
> 
> 
> I'm working on opencart 4 and will be php8 only

Dear  danielkerr ,
Beg your pardon.But I still very rookie of using githhub to understand about the reported task,
May I ask do it mean the email problem I reported can or can't be fix by someone.
Because this email question almost drive me crazy on 3.0.3.7 with php8
