### ISSUE TITLE
Why are we still using twig templates (part 2)?

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#8969]
As a followup from #6967 I took another look at the situation with using Twig as the rendering engine.

Daniel made this comment in **system/library/template/twig.php**:

> FYI all the Twig lovers out there!
> 
> The Twig syntax is good, but the implementation and the available methods is a joke!
> 
> All the Symfony developer has done is create a garbage frame work putting 3rd party scripts into DI containers.
> The Twig syntax he ripped off from Jinja and Django templates then did a garbage implementation!
> 
> The fact that this system cache is just compiling php into more php code instead of html is a disgrace!

So I wrote up my own simple Twig parser which compiles a Twig template plus variables directly into the final HTML output, and so far (without any possible PHP code optimizations) the time it takes for this process is about the same as for the Symfony Twig to do the same (with cache disabled). 

I also ran some preliminary performance tests for the **common/footer**, with the following results:

common/footer.tpl : average 0.001 seconds  (on OC 3.0.3.6 using the **system/library/template/template.php**)
common/footer.twig: average 0.002 seconds (on OC 3.0.3.6 with Symfony Twig, no cache)
common/footer.twig: average 0.001 seconds (on OC 3.0.3.6 with Symfony Twig, cache enabled)
common/footer.twig: average 0.002 seconds (on OC 3.0.3.6 with our own Twig to HTML rendering engine)

While it may be true that Symfony Twig converts the twig template into a PHP file, the followup rendering from that generated PHP cache file takes about the same time as the one from a **footer.tpl** file.

From a performance perspective, once the Symfony Twig cache is enabled, the performance is similar to a PHP rendering engine. 

Still, there is no apparent advantage of using Twig rather than PHP as the rendering engine. Non-existing variables are silently being ignored by Symfony Twig, OpenCart doesn't use autoescape, nor does it use Twig's include, block or template inheritance (there is no need for the latter because OpenCart uses a proper MVC framework anyway).

I'll do some more testing once I have further progressed with our experimental 'Twig to direct final HTML' rendering engine, there is still potential for further code optimization.

**Comment by mhcwebdesign** [comment]
Update: After some simple tweaking of my own 'Twig to direct HTML' rendering engine it's now several times than the Symfony Twig V3 with its enabled cache. Maybe I'll replace the Symfony Twig with my own one after all!

**Comment by mhcwebdesign** [comment]
Update: I now got my own 'Twig to direct HTML' faster than Symfony Twig V3 (enabled cache):

common/footer.twig: average 0.000257 seconds (on OC 4.0.0.0-b with Symfony Twig, cache enabled)
common/footer.twig: average 0.000069 seconds (on OC 4.0.0.0-b with our own Twig to HTML rendering engine)

Maybe I'll replace the Symfony Twig V3 with our own 'Twig to direct HTML' after all, and make it available for the OpenCart project. It just needs some more work and refinements.

**Comment by diegospm** [comment]
@mhcwebdesign 

what makes twig attractive is its syntax, will your renderer maintain the current syntax?

**Comment by mhcwebdesign** [comment]
Yes, it will support most of the standard Twig tags, filters, functions, including some not even yet used on OpenCart, such as template inheritance, blocks, includes, etc. It's still early days, but I think I got the basic tokenizer and parser working.

**Comment by danielkerr** [comment]
i think feature requests need to go under the community forums.

**Comment by mhcwebdesign** [comment]
OK, I'll re-post it on the forum. One way or the other, though, Twig needs to be addressed. Symfony Twig has gone the wrong direction.

**Comment by WhereJuly** [comment]
@mhcwebdesign 

> Maybe I'll replace the Symfony Twig V3 with our own 'Twig to direct HTML' after all, and make it available for the OpenCart project. It just needs some more work and refinements.

The main difference of this in-house solution vs Twig is Twig has a dedicated long-term support, bug fixes and, which is extremely important, the clear and up to date documentation that matches the package actual behavior.

Will `Twig to direct HTML` receive the same care and treatment from you or OpenCart team for the decade ahead?

If not then OpenCart, if it adopts `Twig to direct HTML`, locks itself with no LTS no bug-fixes, no up-to-date documentation dependency.

All those three - no LTS no bug-fixes, no up-to-date documentation would definitely diminish the OpenCart developers customer base.

You could make a pull request to Twig repository itself. If the performance advantage is so drastic they could merge it.

**Comment by mhcwebdesign** [comment]
We are not going to make a pull-request on the Symfony Twig project. It's documentation is hopelessly inaccurate, its implementation as Daniel rightly pointed out is poorly done. And as regards LTS: Sorry, but PHP is doing a better job with this than Twig. 

Another interesting project would be to write up a complete one-time Twig to PHP template converter so web themes can use PHP-templates. But first we'll have our own Twig engine completed, to make OpenCart more robust.

**Comment by danielkerr** [comment]
lets see the code finished first. and  ot add it as a issue.

**Comment by mhcwebdesign** [comment]
Fair enough, in the meantime I'll post more updates on the Opencart forum.
