### ISSUE TITLE
search is working wrong

### ISSUE THREAD

**Issue by jintianking** [opencart/opencart#8974]
Fatal error: Uncaught Error: Call to a member function link() on string in G:\website\oc\demo-4\catalog\controller\startup\language.php:91 Stack trace: #0 [internal function]: Opencart\Application\Controller\Startup\Language->index() #1 G:\website\oc\demo-4\system\engine\action.php(71): call_user_func_array(Array, Array) #2 G:\website\oc\demo-4\system\framework.php(92): Opencart\System\Engine\Action->execute(Object(Opencart\System\Engine\Registry)) #3 G:\website\oc\demo-4\system\startup.php(59): require_once('G:\\website\\oc\\d...') #4 G:\website\oc\demo-4\index.php(17): require_once('G:\\website\\oc\\d...') #5 {main} thrown in G:\website\oc\demo-4\catalog\controller\startup\language.php on line 91

**Comment by danielkerr** [comment]
this is noit a support page. i think you have messed your paths up in config.
