### ISSUE TITLE
Twig folder not found inside /system/library/template/

### ISSUE THREAD

**Issue by sdancer75** [opencart/opencart#8975]
**What version of OpenCart are you reporting this for?**
3.0.3.6

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
I installed an OC v3.xxx theme (shoppica ) but it complains that there is no file inside the Twig folder. Specifically under `opencart/system/library/template/Twig/ExtensionInterface.php`

Under the `opencart/system/library/template` folder there exist only two files 1) template.php and 2) twig.php

**To Reproduce**
Copy/Paste latest version of _shoppica v3.3.2_
**Expected behavior**

Exist a twig folder, maybe ??

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Yes, ICDSoft servers
 - Operating system Linux
 - PHP version 7.3
 - Apache version 2.4.46
 - Browser(s) tested with [e.g. chrome, safari - if applicable] chrome
 - Version [e.g. 22] latest v87

**Additional context**

**Comment by mhcwebdesign** [comment]
This is not an OpenCart bug, but rather an issue with the Shoppica theme.

In OpenCart 3.0.3.6 the **twig** folder has been moved to the **system/storage/vendor** folder, as part of using a newer Twig version, and its autoloader should pick up the file. The Shoppica theme needs to be upgraded to support OpenCart 3.0.3.6. Or even better, use a standard-compliant web theme, see also this OpenCart forum thread: https://forum.opencart.com/viewtopic.php?t=157098#p599291
