### ISSUE TITLE
image resize not working

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#8988]
**What version of OpenCart are you reporting this for?**

Master branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

image.php image resize doesn't function
![p_image_resize](https://user-images.githubusercontent.com/14033183/102698935-1473ad00-420f-11eb-9228-7c5285a8a575.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by cgcmart** [comment]
Solved.

**Comment by chongshengdz** [comment]
> Solved.

how to solve it?

**Comment by cgcmart** [comment]
@chongshengdz 
https://github.com/cgcmart/opencart/commit/5c5f06104a4e790c8c27996f531c8f0c99520867
https://github.com/cgcmart/opencart/commit/372ac531049802513527f8c5fafc71d082f8ffea

**Comment by danielkerr** [comment]
@cgcmart that is not a fix!

fix is here

https://github.com/opencart/opencart/commit/35175a33338798f20da13e55ccbe70bfa6e85ccf

**Comment by chongshengdz** [comment]
> @cgcmart that is not a fix!
> 
> fix is here
> 
> [35175a3](https://github.com/opencart/opencart/commit/35175a33338798f20da13e55ccbe70bfa6e85ccf)

strange, image-resize works on php 8.0
but now not working on php 7.3+

**Comment by stalker780** [comment]
@chongshengdz
https://github.com/opencart/opencart/commit/35175a33338798f20da13e55ccbe70bfa6e85ccf#r45352634
Hope will be fixed soon

**Comment by cgcmart** [comment]
> 
> 
> @cgcmart that is not a fix!
> 
> fix is here
> 
> [35175a3](https://github.com/opencart/opencart/commit/35175a33338798f20da13e55ccbe70bfa6e85ccf)

the above any change is not working. They work only with my 
cgcmart@5c5f061
cgcmart@372ac53

**Comment by stalker780** [comment]
> 
> 
> > @cgcmart that is not a fix!
> > fix is here
> > [35175a3](https://github.com/opencart/opencart/commit/35175a33338798f20da13e55ccbe70bfa6e85ccf)
> 
> the above any change is not working. They work only with my
> [cgcmart/opencart@5c5f061](https://github.com/cgcmart/opencart/commit/5c5f061)
> [cgcmart/opencart@372ac53](https://github.com/cgcmart/opencart/commit/372ac53)

Your "fix" does not fix anything. It just returns direct file path without resize and cache. It bypasses Image class.

**Comment by cgcmart** [comment]
Maybe copy /library/image.php public function resize code to crop and patch up /model/tool/image.php

**Comment by danielkerr** [comment]
i can fix.

**Comment by danielkerr** [comment]
ok try now. i have put a fix in for php8 and 7

**Comment by cgcmart** [comment]
It's **public function resize** not working.
/system/library/image.php
/admin/model/tool/image.php
/catalog/model/tool/image.php

**Comment by chongshengdz** [comment]
> It's **public function resize** not working.
> /system/library/image.php
> /admin/model/tool/image.php
> /catalog/model/tool/image.php

after installing the latest master branch, the issue has been resolved both in php 7.3+ and php 8.0.

**Comment by cgcmart** [comment]
My system has PHP version 7.4.13.

The fix https://github.com//issues/8988 does not solve this issue.

In more explanation of the issue, upload image files are correctly resized and saved to cache according to the theme image size settings.
The exactly issue is both admin and catalog (front store) image resize do not work to theme templates.
I walked back to my comment out.

**Comment by chongshengdz** [comment]
> My system has PHP version 7.4.13.
> 
> The fix https://github.com//issues/8988 does not solve this issue.
> 
> In more explanation of the issue, upload image files are correctly resized and saved to cache according to the theme image size settings.
> The exactly issue is both admin and catalog (front store) image resize do not work to theme templates.
> I walked back to my comment out.

have you downloaded and installed the lastest master branch?
it does work, i just re-installed php 7.4.13
you need to give permission 0777 for  image folder.

**Comment by danielkerr** [comment]
Clear the cached images

**Comment by danielkerr** [comment]
Msg here if fixed

**Comment by cgcmart** [comment]
no, don't work.
I cleared /cache/catalog a couple of times.
cache/catalog image file sizes are correctly
but browse website images are not resized, display smaller images and leave black spaces, similar to the above picture.

**Comment by stalker780** [comment]
> no, don't work.
> I cleared /cache/catalog a couple of times.
> cache/catalog image file sizes are correctly
> but browse website images are not resized, display smaller images and leave black spaces, similar to the above picture.

Something is wrong with your PHP8 + GD installation/configuration.

Works like a charm on my Win10+Apache2.4+PHP8+GD test server.

I have downloaded PHP8 from this link https://windows.php.net/download#php-8.0
VS16 x64 Thread Safe (2020-Nov-24 22:49:03)

**Comment by cgcmart** [comment]
I use CentOS Linux 8.2.2004, Apache version 2.4.37, PHP version 7.4.13

/etc/php.ini
`extension=/usr/lib64/php/modules/gd.so`

In opencart application, 3 image.php files are update to master branch.

As I said, /image/cache/catalog image files are resized correctly, by 
![error_resize](https://user-images.githubusercontent.com/14033183/103039533-28851a80-453f-11eb-80a0-20f73665eaa8.jpg)
browser displays images as not expected.

**Comment by cgcmart** [comment]
> 
> 
> > > @cgcmart
> > > the above any change is not working. They work only with my
> > > [cgcmart/opencart@5c5f061](https://github.com/cgcmart/opencart/commit/5c5f061)
> > > [cgcmart/opencart@372ac53](https://github.com/cgcmart/opencart/commit/372ac53)
> 
> Your "fix" does not fix anything. It just returns direct file path without resize and cache. It bypasses Image class.

No, it returns cache file with correct size. I checked /image/cache/catalog, image files are correct size.

**Comment by stalker780** [comment]
@cgcmart 
> No, it returns cache file with correct size. I checked /image/cache/catalog, image files are correct size.

Something is definitely wrong with your PHP GD extension.
I think GD functions imagefilledrectangle() and imagecopyresampled() are broken for some reason.

Lots of people use same resize functionality in PHP 7.1-7.4 and OC3.0 (where resize acts absolutely the same) and never reported such issue.

**Comment by cgcmart** [comment]
It's very old issue. Most of users don't post it here, instead post it at opencart forum and stackoverflow, but never has an official solution.
There is the issue #7851 still open.

**Comment by stalker780** [comment]
@cgcmart 
You did not mention before you have any php warnings.

Are your width and height parameters set correctly, when calling resize function?

**Comment by cgcmart** [comment]
Php warnings immediately displayed on front store home page after installation. I made some commit in /library/image.php https://github.com/cgcmart/opencart/commit/36ec43bf5b820f156b2103d8b4bc57c350d7a185 php warnings are gone, instead small images with black spaces without error logs.

**Comment by osworx** [comment]
> you need to give permission 0777 for image folder.

**I really don't know, how many times I have to read such stupid answer!**
_Never ever give any folder such permissions,_ because they will open your system to every attack and hacker!
0755 is enough and should fit in 99% of all cases.

**Comment by ADDCreative** [comment]
@cgcmart Issue https://github.com/opencart/opencart/issues/7851 is cause by a theme or module not being able to save or restoring its image sizes from the database, not with the resize function itself.

If you have made these changes https://github.com/cgcmart/opencart/commit/36ec43bf5b820f156b2103d8b4bc57c350d7a185 then you are going to have problems as you are now creating a new image the same size as the original image and just scaling the contents to the top left corner.

**Comment by cgcmart** [comment]
The issue #7851 Php warning seems an initial phenomenon. After changes, Php warning are gone, then either keeping those changes or reversal, the php warning won't appear again.
