### ISSUE TITLE
[master-branch] how to replace file?

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#8991]
<file path="catalog/view/template/common/header.twig">
        <operation>
            <search><![CDATA[<h1><a href="{{ home }}">{{ name }}</a></h1>]]></search>
            <add position="replace"><![CDATA[
            <h1><a href="{{ home }}">opencart.com</a></h1>
            ]]></add>
        </operation>        
    </file>

the above codes do not work.

**Comment by osworx** [comment]
Belongs to which OpenCart Version?
And what is the complete code?

**Comment by chongshengdz** [comment]
> Belongs to which OpenCart Version?
> And what is the complete code?

master-branch

**Comment by chongshengdz** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<modification>
    <name>OpenCart Default Extensions</name>
    <version>1.0</version>
    <author>OpenCart Ltd</author>
    <link>https://www.opencart.com</link>
<file path="catalog/view/template/common/header.twig">
    <operation>
        <search><![CDATA[<h1><a href="{{ home }}">{{ name }}</a></h1>]]></search>
        <add position="replace"><![CDATA[
        <h1><a href="{{ home }}">opencart.com</a></h1>
        ]]></add>
    </operation>        
</file>
</modification>

the above is the example complete code.

**Comment by mhcwebdesign** [comment]
OCmod is not available anymore in OC 4 (master branch)

**Comment by osworx** [comment]
> 
> 
> OCmod is not available anymore in OC 4 (master branch)

Correct - that's why I have asked ..

**Comment by chongshengdz** [comment]
> OCmod is not available anymore in OC 4 (master branch)
 so how to replace files in master-branch?

just tested VQMOD, still works fine.

**Comment by osworx** [comment]
So WHAT?
OC- or VQmod ..
VQMod syntax is not the same as OCmod.

Nevertheless, hopefully none of them anymore.

**Comment by chongshengdz** [comment]
so there is no way to replace files in master-branch any more?

**Comment by danielkerr** [comment]
ocmod is gone. their might be a way to bring it back and create cache files within the extension folder. but as other have stated it is not a design pattern and is a hack. so the new system will use the event system only.
