### ISSUE TITLE
Change zipfile-name

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#8992]
When removing ocmods from 4.x onwards, the name of the zipfiles should be also renamed.
Confuse more when having the same name as we had the last years ..

https://github.com/opencart/opencart/blob/c2f0fa930703438898ae91ad4a7811ca022c48af/upload/admin/controller/marketplace/installer.php#L221

Maybe something like **opencart.zip**

**Comment by danielkerr** [comment]
maybe ocmod4.zip

**Comment by stalker780** [comment]
There are no modifications in OC4 anymore.
Perhaps ocext.zip for OpenCart Extension?

**Comment by Hkr32** [comment]
And if just: .zip?

**Comment by osworx** [comment]
> 
> 
> maybe ocmod4.zip

To seperate it completely and to make it clear that the Extension is for OpenCart v4, why not xyz**.oc4**
Instead of xyz.zip?
The system (Installer) will accept then only .oc4 files.
And the Developers can call their Extensions how they want.

**Comment by Hkr32** [comment]
If there are no modifiers, then maybe you don't need to add a separator? Only name.zip

**Comment by osworx** [comment]
Why seperator?
The name of the new files are xyz **.oc4**
oc4 instead of zip, so name.zip become name.oc4

**Comment by danielkerr** [comment]
im leaving it the same. the install.xml has a compatibility tag
