### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by richardgosler** [opencart/opencart#8994]
As a long time user/fan of Opencart there are a couple of issues that reoccur with pretty much every build, especially when a site has been ported from another platform.

1. Have the option of price entry being entered as tax inclusive. Customers expect this, especially on B2C sites.
2. Include an SKU field on product options, including option combinations ie colour/size.

I'm aware there are extensions that permit this but it really should be core functionality to prevent other extensions conflicting. Would love to see these incorporated into a future release of OC.

**Comment by danielkerr** [comment]
later

**Comment by danielkerr** [comment]
we have product variants in the master.
