### ISSUE TITLE
on WAMP server opencart master installation not work

### ISSUE THREAD

**Issue by Edward0625** [opencart/opencart#8996]
**What version of OpenCart are you reporting this for?**
master (2020-12-22)
**Describe the bug**
I want to install the master Opencart on wamp server, but I can't finish.

**To Reproduce**
I dowload the leatest master zip folder.
I create a new project, database on wamp.
I start to install the opencart.
Enter your database and administration details its ok and I go to the next step and error.

**Expected behavior**
error

**Screenshots / Screen recordings**
![screencapture-oc4-install-index-php-2020-12-22-15_31_30](https://user-images.githubusercontent.com/7513278/102899572-687acd80-446b-11eb-9a3a-2a64f9407a5e.png)
**Server / Test environment (please complete the following information):**
 - Wamp 3.2.3.3 64 bits
 - Win 10
 - 7.3.21 php
 - Apache version 2.4.46
 - Browser Chrome
 - Version [87.0.4280.88]

**Additional context**
No

**Comment by danielkerr** [comment]
i just did a new  fresh install of xamp with php8 and it works fine.  i think the issue is with mysql 8. i will terst later its already reported here: 

https://github.com/opencart/opencart/issues/8976
