### ISSUE TITLE
[Master] Order Edit without stock not possible

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#8997]
OpenCart - Master branch and before

**Basic Situation**
A System is configured in a way that the stock quantity of a product is reduced at the moment of the order. 
So the customer get only an order confirmation for products are really on stock.

**Problem - Follow up situation**
There are several reasons to change an order [order_edit] - wrong address, an additional product by call, other shipping method .... - but that is not possible if one of the ordered products has no stock. 

**To Reproduce**
see issue #8869 

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? both
 - Operating system Linux
 - PHP version 7.3
 - Apache version 
 - Browser(s) tested with [e.g. chrome, safari - if applicable] firefox
 - Version [e.g. 22] 84.0

**Comment by danielkerr** [comment]
you need to set the order to canceled using order history then edit the order. make sure your products are set to reduce stock.
