### ISSUE TITLE
[master branchin php 8.0]filemanger not working, it won't pop up when editting product images.

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#8998]
TypeError: iconv_substr(): Argument #3 ($length) must be of type ?int, string given in /system/helper/utf8.php on line 51

**Comment by danielkerr** [comment]
enable mbstring string in extensions.

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/commit/c7b4303d427d77805a34f87e6f0ce625d5402837

**Comment by chongshengdz** [comment]
> [c7b4303](https://github.com/opencart/opencart/commit/c7b4303d427d77805a34f87e6f0ce625d5402837)



> enable mbstring string in extensions.

yes, it works after installing php-mbstring.
php-mbstring should be set as a must before installing opencart.
