### ISSUE TITLE
[Master Branch] Incorrect date value: '0000-00-00'

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#9004]
**What version of OpenCart are you reporting this for?**
4.0.0.0.0-b master branch

**Describe the bug**
'0000-00-00' and '0000-00-00 00:00:00' values aren't allowed for date and datetime fields
What section does it affect?
The OpenCart installer step 3

Here is how to sort it out:

In file **system/helper/db_schema.php** change all entries containing

`'not_null' => true`

to

`'not_null' => false`

where the 

`'type' => 'datetime',`

or

`'type' => 'date',`

Also, in file **install/opencart.sql** change all instances of

`'0000-00-00'` to `NULL`

and all instances of

`'0000-00-00 00:00:00'` to `NULL`

Reason for above changes: MySQL 5.7 or later stopped supporting zero values in date / datetime. It's incorrect to use zeros in date or in datetime, just put null instead of zeros. See e.g. https://stackoverflow.com/questions/37292628/1292-incorrect-date-value-0000-00-00

**Comment by mhcwebdesign** [comment]
Also, the following files need to be updated, changing all instances of '0000-00-00' to null or NULL:

admin/controller/catalog/product.php
admin/controller/marketing/coupon.php
admin/controller/sales/returns.php
catalog/model/product.php
extension/opencart/catalog/model/total/coupon.php
system/library/cart/cart.php

There are no instances of '0000-00-00 00:00:00' nor '00:00:00' in the PHP files.

**Comment by danielkerr** [comment]
linked to this already: https://github.com/opencart/opencart/issues/8976

**Comment by abenkorich** [comment]
I've tested fa ix as follow:

1).  On the file "system/library/db/mysqli.ph" search and comment the line:
"$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");"

--> 
// The following line is commented as a fix to my sql 8 Incorrect date value: '0000-00-00'
//$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");

2) Add the following line above the one you just commented
// Crrection by Added by A.benkorich
$this->connection->query("SET SESSION sql_mode = 'ONLY_FULL_GROUP_BY'");

**Comment by mhcwebdesign** [comment]
Sorry, but I have to re-open this issue.

The file **system/library/db/mysqli.php** needs to be changed in its constructor.

Replace
`$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");`

With
`$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION'");`

See https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date why we should not use it. The NO_ZERO_DATE is deprecated, and shouldn't be used since we want to allow zero date values without triggering warning or error messages. The same change was applied to the 3.0.x.x_Maintenance branch, see e.g. https://github.com/opencart/opencart/issues/9075#issuecomment-774502931

Just like we did it for the 3.0.x.x_Maintenance branch, can others test this suggested change please for the Masterbranch on MySQL 8 and MySQL 5.x versions please before committing the change?

**Comment by dperygin** [comment]
> Sorry, but I have to re-open this issue.
> 
> The file **system/library/db/mysqli.php** needs to be changed in its constructor.
> 
> Replace
> `$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");`
> 
> With
> `$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION'");`
> 
> See https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date as to why we should not use it. The NO_ZERO_DATE is deprecated, and shouldn't be used since we want to allow zero date values without triggering warning or error messages. The same change was applied to the 3.0.x.x_Maintenance branch, see e.g. [#9075 (comment)](https://github.com/opencart/opencart/issues/9075#issuecomment-774502931)
> 
> Just like we did it for the 3.0.x.x_Maintenance branch, can others test this suggested change please for the Masterbranch on MySQL 8 and MySQL 5.x versions please before committing the change?

I had this issue and this fixed it for me. 05/15/2021.

Thank you.

**Comment by mhcwebdesign** [comment]
Thanks. I think we can close this issue as it's now fixed in the master branch.

**Comment by mguomanila** [comment]
@mhcwebdesign it works ...thanks!
