### ISSUE TITLE
[Master Branch] Error: Field 'description' doesn't have a default value

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#9006]
**What version of OpenCart are you reporting this for?**
4.0.0.0.b master branch

**Describe the bug**
Installer bug in step3 when populating the 'oc_event' table

**How to fix**
Update the install/opencart.sql to include this missing field 'description' when populating the 'oc_event' table.

**Comment by mhcwebdesign** [comment]
Thank you for your pull-request. However, it is incomplete, it also has to include the values, e.g. '', in the **install/opencart.sql**

```
INSERT INTO `oc_event` (`code`, `description`, `trigger`, `action`, `status`) VALUES
('activity_customer_add', '', 'catalog/model/account/customer/addCustomer/after', 'event/activity|addCustomer', 1),
('activity_customer_edit', '', 'catalog/model/account/customer/editCustomer/after', 'event/activity|editCustomer', 1),
....

**Comment by stickpro** [comment]
@mhcwebdesign add commit, ty

**Comment by mhcwebdesign** [comment]
That looks better.

**Comment by danielkerr** [comment]
linked to this already: https://github.com/opencart/opencart/issues/8976

**Comment by danielkerr** [comment]
even if its missing mysql should not be requiring this data! maybe i need to switch mysqli from strict mode.
