### ISSUE TITLE
Unknown column 'salt ' in 'field list' when password was changed from database

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#9008]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
Unknown column 'salt ' in 'field list' when try to login as admin.

**To Reproduce**
1. Go to 'phpMyAdmin'
2. Click on 'oc_user' table and edit user table password with MD5 encryption
3. Now go to 'admin' and try to login.  that error will shown.

**Expected behavior**
Should display an warning error..like password doesn't match/work...or to login

**Screenshots / Screen recordings**
![error_oc40](https://user-images.githubusercontent.com/14251939/103074791-fe7d3800-45d2-11eb-869b-f4d6b59c6c7c.png)

**Server / Test environment (please complete the following information):**
 - Local development?
 - Windows
 - PHP 7.4.13
 - Apache/2.4.46

**Additional context**
If you hit F5 the error will shown another encoded password.
![err_oc4](https://user-images.githubusercontent.com/14251939/103074915-3c7a5c00-45d3-11eb-9ab1-eae9748524bc.png)

**Comment by danielkerr** [comment]
salt has been removed.

**Comment by danielkerr** [comment]
added fix in latest commit
