### ISSUE TITLE
Font embed

### ISSUE THREAD

**Issue by agatha65** [opencart/opencart#9012]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
Since 2019 there is a new format to embed Google fonts - with preconnect and swap rule.

link rel="preconnect" href="https://fonts.gstatic.com"
link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet"

This is to ensure text remains visible during webfont load.
This change improves the Pagespeed results as well.
Also some developers prefer to embed self-hosted fonts because Google can be blocked for some countries.

What section does it affect?
events, header - controller and view.

**Comment by danielkerr** [comment]
can u do a pull request

**Comment by danielkerr** [comment]
i have removed the fonts being loaded from the header and only does via the style sheets now.
