### ISSUE TITLE
Backup restore language bug

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#9015]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
text_restore is displayed once when restore a backup.

**To Reproduce**
Make a backup then restore the backup.
In the progress bar is showing Restoring ...x of x....but after some progress is displaying text_restore...then again Restoring x of x.

**Comment by danielkerr** [comment]
this is not an issue. only happens when the config table is truncated. it loses the default language for one
