### ISSUE TITLE
session are return null after payment success

### ISSUE THREAD

**Issue by ahmedsafroot** [opencart/opencart#9017]
after payment successfully return callback sessions became null if he use 3d secure and  user logout automatically ?
opencart version is 1.5 
php version is 7.2

**Comment by condor2** [comment]
Post on forum.

**Comment by ahmedsafroot** [comment]
@condor2  where is the forum?

**Comment by condor2** [comment]
lol...
https://forum.opencart.com/

**Comment by ahmedsafroot** [comment]
thanks
