### ISSUE TITLE
Ocmod not working with view file with Opencart 3.0.3.6

### ISSUE THREAD

**Issue by vishvakamal** [opencart/opencart#9019]
**What version of OpenCart are you reporting this for?**
3.0.3.6
**Describe the bug**
Ocmod modification is not reflected for view files in admin or frontend.

**To Reproduce**
1. Install any ocmod module which add any button or text for user preview
2. Clear modification cache and refresh it.
3. It will create modification file for view.
4. But actual change was not reflected.

**Expected behavior**
Any applied change to view files can be shown

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Local Development
 - Operating system Window 10
 - PHP version tested in 7.2, 7.3 and 7.4
 - Apache version
 - Browser(s) tested with Chrome, Firefox and Edge
 - Version Latest version (Opencart version 3.0.3.6)

**Additional context**
Modificatin changes in controller, model and language files are reflect very well but only view files changes are not reflecting.

**Comment by cartbinder** [comment]
Fix already available on the Opencart forum.

You can check this link below
https://www.cartbinder.com/blog/documentation/twig-modification-fix-for-opencart-version-3035-3036/

**Comment by condor2** [comment]
Look's like a spam....

https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/modification.xml

**Comment by mhcwebdesign** [comment]
The https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/modification.xml is a correct modification and works fine for subsequent modifications of twig files.

**Comment by WebkulOpencart** [comment]
alrady fixed

**Comment by AhsanShabbir** [comment]
This modification XML file does not work with  3.0.3.7.  Any help will be apreciated.

**Comment by Jawahar1994** [comment]
@AhsanShabbir This is working, please replace the modification.xml file on your instance after downloading the latest version

**Comment by FlySquare** [comment]
> Fix already available on the Opencart forum.
> 
> You can check this link below https://www.cartbinder.com/blog/documentation/twig-modification-fix-for-opencart-version-3035-3036/

thank you for all help
