### ISSUE TITLE
Broken payment extensions link column

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#9020]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
If you go to Extensions-->Payments there is a column after Payment Method and there is no {{ column_link }} in the twig file...
Also if you use text_link as variable in the language, the variable isn't show.
![payments_oc](https://user-images.githubusercontent.com/14251939/103232499-41c50700-4943-11eb-8b89-4777a44392dc.png)

**Comment by cgcmart** [comment]
Confirmed.
What the column name should be? It's missing both in oc3.1 and oc4 (Master).
Those four payments are empty at the column because of no link.
If install other payment method modules, the link should be provided by the module.

**Comment by condor2** [comment]
I think should be Colum Name because content is <td class="text-right">{{ extension.sort_order }}</td>

**Comment by cgcmart** [comment]
Maybe "Vendor" or "Provider"

**Comment by danielkerr** [comment]
ok will add vendor
