### ISSUE TITLE
[master] Error with frameword.php & action.php

### ISSUE THREAD

**Issue by SaifAlSubhi** [opencart/opencart#9043]
**What version of OpenCart are you reporting this for?**
OpenCart master branch

**Describe the bug**
The website isn't loaded and you got below error instead.

**To Reproduce**
1. Go to 'www.youropencartmasterbranchafterinstall.com'
2. Click on 'press enter to go the website'
3. Scroll down to 'no need to scroll down'
4. See this error

**Expected behavior**
You expect to get this error.

**Screenshots / Screen recordings**
You don't need a screenshot because it is a short text error log.

**Server / Test environment (please complete the following information):**
 - Local web server using a host and apache server.
 - ubuntu linux 20.04 LTS
 - PHP v7.4.3 cli
 - Apache v2.4.41
 - google chrome stable v87.0.4280.88
 - Version 87.0.4280.88

**Additional context**
This is the error when you go to the website home page or any other page.

`
TypeError: Argument 2 passed to \System\Engine\Action::execute() must be of the type array, object given, called in /system/framework.php on line 147 in /system/engine/action.php on line 57
`

Note: admin login page and panel are working and loaded.

**Comment by mhcwebdesign** [comment]
Sorry, not enough details to reproduce your error.

**Comment by SaifAlSubhi** [comment]
Hi mhcwebdesign,
see updated bug post.

**Comment by SaifAlSubhi** [comment]
> Sorry, not enough details to reproduce your error.

Hi mhcwebdesign,
see updated bug post.

**Comment by mhcwebdesign** [comment]
The error is caused by calling the catalog/controller/startup/session.php again as a post action, after the response output.

I think this should be removed from the **system/config/catalog.php**:

```
 $_['action_post_action']  = [
	'startup/session'
];

```

**Comment by SaifAlSubhi** [comment]
> The error is caused by calling the catalog/controller/startup/session.php again as a post action, after the response output.
> 
> I think this should be removed from the **system/config/catalog.php**:
> 
> ```
>  $_['action_post_action']  = [
> 	'startup/session'
> ];
> ```

I think this is to do with:
`
} catch (\Exception $e) {
	$action = new \Opencart\System\Engine\Action('error/exception');
	$action->execute($registry, $e);
}
`
@ /system/framwork.php

and:
`
public function execute(Registry $registry, array &$args = []) {
`
@ system/engine/action.php

**Comment by SaifAlSubhi** [comment]
> The error is caused by calling the catalog/controller/startup/session.php again as a post action, after the response output.
> 
> I think this should be removed from the **system/config/catalog.php**:
> 
> ```
>  $_['action_post_action']  = [
> 	'startup/session'
> ];
> ```

I did remove this and tried it out and still getting the same error.

**Comment by mhcwebdesign** [comment]
Well, unless someone else can replicate the error after the removal of this post-action, then I must assume there is something different in your setup. My suggested fix certainly works on our Linux server. Tested with PHP 7.3 and 7.4 and MySQL 5.7.32

**Comment by danielkerr** [comment]
its fixed.
