### ISSUE TITLE
OC4 - Cookies error: Cannot modify header information

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#9044]
In the bottom of each page. Or when you try to add product to cart you will get:
PHP Warning:  Cannot modify header information - headers already sent by (output started at \oc40\system\library\response.php:124) in \oc40\system\helper\general.php on line 6

PHP 7.3

Also it is strange, in helper/general.php::oc_setcookie there is a check:
```
	if (version_compare(phpversion(), '7.3.0', '>=')) {
		// PHP needs to update their setcookie function.
		setcookie($key, $value, $option);
	} else {
		// Here comes code for PHP < 7.3.0
```
So else comes for PHP 7.2 and lower. But lowest required OC4 PHP version is 7.3, so code in else will be never executed.

**Comment by danielkerr** [comment]
i think this is fixed
