### ISSUE TITLE
[Master Branch] PHP8.0 Exception with caught TypeError: Argument 2 passed to Action::execute()

### ISSUE THREAD

**Issue by vladaman** [opencart/opencart#9045]
**What version of OpenCart are you reporting this for?**
Current git HEAD fdf6a3221375f7fd905ba4b6692f41647a664693

**Describe the bug**
New installation with git fails with exception Uncaught TypeError: Argument 2 passed to Opencart\\System\\Engine\\Action::execute() **must be of the type array**, object given, called in **/var/www/opencart/upload/system/framework.php on line 147** and defined in /var/www/opencart/upload/system/engine/**action.php:57**

**To Reproduce**
1. git pull 
2. Open installation website /install/index.php
3. See error in log file below

**Exception**
```
Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Opencart\\System\\Engine\\Action::execute() must be of the type array, object given, called in /var/www/opencart/upload/system/framework.php on line 147 and defined in /var/www/opencart/upload/system/engine/action.php:57
Stack trace:
#0 /var/www/opencart/upload/system/framework.php(147): Opencart\\System\\Engine\\Action->execute(Object(Opencart\\System\\Engine\\Registry), Object(RuntimeException))
#1 /var/www/opencart/upload/system/startup.php(59): require_once('/var/www/openca...')
#2 /var/www/opencart/upload/install/index.php(35): require_once('/var/www/openca...')
#3 {main}
  thrown in /var/www/opencart/upload/system/engine/action.php on line 57'
```

**Server / Test environment (please complete the following information):**
 - Local development
 - Ubuntu 20.04
 - PHP version 8.0

**Identified issue:**
Issue is that Action::execute() requires array argument but in framework.php we pass Exception object $e

```
} catch (\Exception $e) {
	$action = new \Opencart\System\Engine\Action('error/exception');
	$action->execute($registry, $e); // Error is here
}
```

**Comment by danielkerr** [comment]
probably going to remove the code

**Comment by vladaman** [comment]
Looks like it's related to #9044 which fixes the issue
