### ISSUE TITLE
[Master Branch] Extension class attempts to load Opencart module 40 times

### ISSUE THREAD

**Issue by vladaman** [opencart/opencart#9050]
Following query for extensions causes the loader to be called 40 times for **opencart module** (_since opencart modules are present 40 times in SQL table_):
https://github.com/opencart/opencart/blob/964c9d857ad6a243b2c8c5679148bab130a87912/upload/catalog/model/setting/extension.php#L5
and later the DB result is used in: https://github.com/opencart/opencart/blob/964c9d857ad6a243b2c8c5679148bab130a87912/upload/catalog/controller/startup/extension.php#L8
```php
// catalog/controller/startup/extension.php
namespace Opencart\Application\Controller\Startup;
class Extension extends \Opencart\System\Engine\Controller {
	public function index() {
		// Add extension paths from the DB
		$this->load->model('setting/extension');
		$results = $this->model_setting_extension->getExtensions();
		foreach ($results as $result) { // looping 40x
```

**Proposed solution:**
Replace SQL query with:
```sql
SELECT DISTINCT extension FROM `" . DB_PREFIX . "extension`
```

**Comment by danielkerr** [comment]
it adds the same stuff to the autoloader but does not load stuff 40 times!
