### ISSUE TITLE
[Master Branch] Cart library update may not use this->data properly to cache results with empty cart (optimalization)

### ISSUE THREAD

**Issue by vladaman** [opencart/opencart#9052]
I found following line. Given the **Cart is empty with 0 items** it will still perform multiple queries to the DB and get nothing. I think it should use null value instead of empty array [];

https://github.com/opencart/opencart/blob/964c9d857ad6a243b2c8c5679148bab130a87912/upload/system/library/cart/cart.php#L34

May improve #9049 with empty cart

**Comment by danielkerr** [comment]
it performs one query if no products that's it!

i think its a case of "i want to add my own little piece of code because i'm going to use it in my projects from now on. so ill make an issue up and hope hes to stupid to check!"

wasting my time!
