### ISSUE TITLE
[Master Branch]: SEO url with NGINX: Redirect on index when 404

### ISSUE THREAD

**Issue by framansi** [opencart/opencart#9056]
**What version of OpenCart are you reporting this for?**
4.0.0.0_b

**Describe the bug**
If typing for example non-existing keywords like www.mysite.com/foo or www.mysite.com/example i'm always redirected to the index.php .
Instead, if I try to type www.mysite/admin/example i get the opencart error page.

**What condition does it affect?**
In case of non-existing keywords you are always redirected to the last page in memory or to the index 

**To Reproduce**

```
location / { 
        try_files $uri $uri/ @opencart;  
    }
    location @opencart {
        rewrite ^/(.+)$ /index.php?_route_=$1 last;  
    }
   
    location /admin { 
     index index.php; 
    }
    
    error_page 404 = @error;

    location @error {
        rewrite ^.*$ /index.php?route=error/not_found last;
    } 
    
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }  
  
    sendfile off; 
  
    location ~ \.php$ {
         
        fastcgi_split_path_info ^(.+?\.php)(/.*)$; 
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        
    }
```

**Server / Test environment (please complete the following information):**

Local development and Deployed to a web server
Operating system ubuntu 18.04
PHP version - 7.3
Nginx

**Comment by danielkerr** [comment]
im closing this. opencart works fine with apache. it should not be hard for some one to setup NGINX and opencart to use seo urls if NGINX was your list of coding languages,
