### ISSUE TITLE
[master-branch] Error: Class 'DOMDocument' not found in /admin/controller/marketplace/installer.php on line 178

### ISSUE THREAD

**Issue by SaifAlSubhi** [opencart/opencart#9062]
**What version of OpenCart are you reporting this for?**
opencart-master-branch up-to-date
**Describe the bug**
When to upload ocmod file in admin panel; you will get this error:
Error:  Class 'DOMDocument' not found in /var/www/opencart/admin/controller/marketplace/installer.php on line 178

**To Reproduce**
1. Go to 'admin panel'
2. Click on 'Extensions/Installer'
3. Click upload any ocmod zip file
4. See this error

**Expected behavior**
Error:  Class 'DOMDocument' not found in /var/www/opencart/admin/controller/marketplace/installer.php on line 178
when uploading ocmod zip file

**Screenshots / Screen recordings**
It is a text error.

**Server / Test environment (please complete the following information):**
Local development web server
ubuntu 20.04 LTS
PHP 7.4.3 cli
Apache 2.4.41
Google Chrome Stable
Version 87.0.4280.88

**Additional context**
In admin/controller/marketplace/installer.php
```
if ($xml) {
 try {
   $dom = new \DOMDocument('1.0', 'UTF-8');
   $dom->loadXml($xml);
```

**Comment by mhcwebdesign** [comment]
`apt-get install php7.4-xml`, then restart your Apache server. This is not an OpenCart bug.

**Comment by SaifAlSubhi** [comment]
> `apt-get install php7.4-xml`, then restart your Apache server. This is not an OpenCart bug.

Sorry, I thought I have already installed it.
This works:
sudo apt install php-7.4-xml
