### ISSUE TITLE
[Master Branch] Inserting new product fails with Exception: Error: Field 'image' doesn't have a default value Error No: 1364

### ISSUE THREAD

**Issue by vladaman** [opencart/opencart#9063]
On master branch, with vanilla installation: Adding new product fails with following error:

```
Exception: Error: Field 'image' doesn't have a default value
Error No: 1364
```

Column cannot be null and has no default value.
https://github.com/opencart/opencart/blob/a9c4515ac05953872474a0f6a062ee44e9cd250c/upload/admin/model/catalog/product.php#L5

**Comment by danielkerr** [comment]
u have the wrong settings on your db! image is not reuqired to add a product! dont see others companing! your issue! fix your sdb settings!
