### ISSUE TITLE
OC4 module/install function is never executed

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#9069]
https://github.com/opencart/opencart/blob/3c17f113cdce4e9f58f2ef2a38c06bc41083ce6f/upload/admin/controller/extension/module.php#L32
is never executed because controller route to install() function is built based on oc_extension table when index.php is called.
But when index.php is called this module is not installed yet.

So routes structure must be rebuilt or route to new module must be added to autoloader before calling install function.

Same for other extensions types: theme, feed, captcha, payment, shipping, etc.

One of solutions is to call startup/extension after installation and before calling module's install function:
`$this->load->controller('startup/extension');`

**Comment by SaifAlSubhi** [comment]
Why if you installed "extension.ocmod.zip"; then "install.xml" file is not copied into "/extension/" folder which contains modifications even if the module is listed in admin/extension panel?

**Comment by danielkerr** [comment]
because the install xml is alreadyed added to the db!

**Comment by SaifAlSubhi** [comment]
> because the install xml is alreadyed added to the db!

I see, thanks Daniel.

**Comment by danielkerr** [comment]
the extension paths are added on the startup. it works fine. just tested it. wasting my time. i think u are trying to build an extension directly in the extension folder. you need to setup key files first before installing and working from there.

**Comment by stalker780** [comment]
@danielkerr 

No! I am not wasting your time! Perhaps I need to give you steps to reproduce.
Otherwise you will get tons of issues here, that modules are not installed correctly.

It's best to check with empty DB or with a module you never installed in this DB before. 
**Main requirement to reproduce issue is: module must be absent in oc_extension table**

1. Goto Installer and upload our dummy_ext.ocmod.zip

2. Click [+] to unzip and Install extension

3. Goto Extensions->Modules and see dummy_ext_heading_title

4. Click [+] install for this module. **After this step, module is finally added  forever in oc_extension table and it's path can be used for language and startup load. BUT NOT DURING THIS AJAX CALL, ONLY FOR FUTURE PHP CALLS, WHEN STARTUP WILL AUTOLOAD IT FROM oc_extension** 

5. F5 to refresh a page and select Feeds and then Modules again (to call select.onchange event, stupid ajax selectbox makes me sick)

6. Now, when Modules list is refreshed you can see DUMMY EXT language title in modules list

7. Check Error Logs. Nothing there. However module has install() and uninstall() functions with logging.

8. Now uninstall a module and you will get a line in Error Logs for uninstall()

9. Now uninstall and delete extension in Extensions->installer

10. After uninstalling and deleting an extension in Admin->Extensions->Installer, it stays in oc_extension table **FOREVER** and all language and install() errors above cannot be reproduced, because module is always declared in startup, even if it was deleted.

So every module, installed first time, will face this issue and ignore install() function.

startup/startup() is based on step #4. So module::install() is accessible only in the next PHP session after installation ajax query. 
!!!**ONLY AFTER** startup/startup() is executed with module added to oc_extension table!!!

**Comment by stalker780** [comment]
Here is a dummy_ext for tests
https://drive.google.com/file/d/1bC7DG5823_EyLWz8WjY-FwNkIPZSns3I/view?usp=sharing

**Comment by stalker780** [comment]
Ah! Sorry! Module stays in oc_extension forever only if you delete and extension without uninstalling a module.

**Comment by chulcha** [comment]
I tested too

And first name after install is like
 dummy_ext_heading_title
 
After install (аjax) Name not change
After  refresh - name is good

And in reverse order
unistall - name is ok
refresh
name is bad
 dummy_ext_heading_title

**Comment by stalker780** [comment]
As far as I understand, this closed issue will be ignored now, until someone else reports this in OC5 :)

**Comment by chulcha** [comment]
if extension not installed, then there is no path to language file
see
https://github.com/opencart/opencart/blob/b3413606582619c654debdb930639218ef4e4b0a/upload/admin/controller/startup/extension.php#L22

You need to add the path to the language folder in the method getList
