### ISSUE TITLE
[master-branch] TypeError: Argument 1 passed to /system/library/image::resize() must be of the type int

### ISSUE THREAD

**Issue by SaifAlSubhi** [opencart/opencart#9073]
**What version of OpenCart are you reporting this for?**
opencart-master-branch up-to-date

**Describe the bug**
```
TypeError: Argument 1 passed to /system/library/image::resize() must be of the type int, string given, called in /catalog/model/tool/image.php on line 35 in /system/library/image.php on line 140
```

**To Reproduce**
Go to checkout and click to place the order. You will get this error.

**Screenshots**
It is a text error.

**Server / Test environment**
Local development web server
ubuntu 20.04 LTS
PHP 7.4.3 cli
Apache 2.4.41
Google Chrome Stable 87.0.4280.88

**Additional context**
In /system/library/image.php
```
public function resize(int $width = 0, int $height = 0, $default = '') {
```
In /catalog/model/tool/image.php
```
$image->resize($width, $height);
```

**Comment by danielkerr** [comment]
can not replicate

**Comment by SaifAlSubhi** [comment]
> can not replicate

@danielkerr  Hi, the error is from catalog/model/tool/image.php
```
$image->resize($width, $height);
```

and not from system/library/image.php

**Comment by danielkerr** [comment]
Your an idiot wasting my time. Don't post here again.
