### ISSUE TITLE
[Question] Extensions installation manually

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#9074]
**What version of OpenCart are you reporting this for?**
Master Branch

There will be no possibility from now on to install extensions manually?
I made a test with an converted extension and seem that you can't add permissions from user group for that files...to see and install.

If you add necessary info in `oc_extension_path` you can install it.

**Comment by danielkerr** [comment]
ok will do.

**Comment by danielkerr** [comment]
this can be added manually via the extension install function. set it so on install the user adds the permission. im not going to set it up to auto add because we dont know what the pages do.
