### ISSUE TITLE
MySQL 8, queries can no longer use '0000-00-00' 

### ISSUE THREAD

**Issue by kpruhs** [opencart/opencart#9075]
**What version of OpenCart are you reporting this for?**
3.0.3.6

**Describe the bug**
When using MySQL 8, queries can no longer use '0000-00-00' as a default value. NULL is the preferred value.

**What section does it affect?**
This error affects all queries using '0000-00-00', in the following files:
/system/library/cart/cart.php
/admin/controller/catalog/product.php
/admin/controller/marketing/coupon.php
/admin/controller/sale/returns.php
/catalog/model/catalog/product.php
/install/opencart.sql
/extension/opencart/catalog/model/total/coupon.php

**To Reproduce**
1. Follow installation instructions 
2. Complete setup steps
3. Go to the shop homepage URL (in my case, in dev environment: http://localhost)
4. Exception: Error: Incorrect DATE value: '0000-00-00'
Error No: 1525
SELECT DISTINCT *, pd.`name` AS name, p.`image`, m.`name` AS manufacturer, (SELECT `price` FROM `fnj_product_discount` pd2 WHERE pd2.`product_id` = p.`product_id` AND pd2.`customer_group_id` = '1' AND pd2.`quantity` = '1' AND ((pd2.`date_start` = '0000-00-00' OR pd2.`date_start` < NOW()) AND (pd2.`date_end` = '0000-00-00' OR pd2.`date_end` > NOW())) ORDER BY pd2.`priority` ASC, pd2.`price` ASC LIMIT 1) AS discount, (SELECT `price` FROM `fnj_product_special` ps WHERE ps.`product_id` = p.`product_id` AND ps.`customer_group_id` = '1' AND ((ps.`date_start` = '0000-00-00' OR ps.`date_start` < NOW()) AND (ps.`date_end` = '0000-00-00' OR ps.`date_end` > NOW())) ORDER BY ps.`priority` ASC, ps.`price` ASC LIMIT 1) AS special, (SELECT `points` FROM fnj_product_reward pr WHERE pr.`product_id` = p.`product_id` AND pr.`customer_group_id` = '1') AS reward, (SELECT ss.`name` FROM `fnj_stock_status` ss WHERE ss.`stock_status_id` = p.`stock_status_id` AND ss.`language_id` = '1') AS stock_status, (SELECT wcd.`unit` FROM `fnj_weight_class_description` wcd WHERE p.`weight_class_id` = wcd.`weight_class_id` AND wcd.`language_id` = '1') AS weight_class, (SELECT lcd.`unit` FROM `fnj_length_class_description` lcd WHERE p.`length_class_id` = lcd.`length_class_id` AND lcd.`language_id` = '1') AS length_class, (SELECT AVG(`rating`) AS `total` FROM `fnj_review` r1 WHERE r1.`product_id` = p.`product_id` AND r1.`status` = '1' GROUP BY r1.`product_id`) AS rating, (SELECT COUNT(*) AS `total` FROM `fnj_review` r2 WHERE r2.`product_id` = p.`product_id` AND r2.`status` = '1' GROUP BY r2.`product_id`) AS reviews, p.`sort_order` FROM `fnj_product` p LEFT JOIN `fnj_product_description` pd ON (p.`product_id` = pd.`product_id`) LEFT JOIN `fnj_product_to_store` p2s ON (p.`product_id` = p2s.`product_id`) LEFT JOIN `fnj_manufacturer` m ON (p.`manufacturer_id` = m.`manufacturer_id`) WHERE p.`product_id` = '43' AND pd.`language_id` = '1' AND p.`status` = '1' AND p.`date_available` <= NOW() AND p2s.`store_id` = '0' in /var/www/html/system/library/db/mysqli.php on line 48

**Expected behavior**
The demo homepage for OpenCart is supposed to render.

**Server / Test environment (please complete the following information):**
 - Local development
  - Ubuntu 20.04
  - MySQL 8
 - PHP 7.4.13
 - Apache2
 - chrome, firefox
 - OpenCart v3.0.3.6 (downloaded from GitHub 2021-01-07)

**Additional context**
There is a seemingly identical issue for v4.0.0.0.0-b that was marked closed 2020-12-24
[https://github.com/opencart/opencart/issues/9004](https://github.com/opencart/opencart/issues/9004)

Once the zero values are replaced with NULL everything loads correctly.

**Comment by SaifAlSubhi** [comment]
The fast solution which has been suggested is to replace all '0000-00-00' to NULL

**Comment by mhcwebdesign** [comment]
The easiest quickfix is this for **system/library/db/mysqli.php**:

```
	public function __construct($hostname, $username, $password, $database, $port = '3306') {
		$connection = @new \MySQLi($hostname, $username, $password, $database, $port);

		if (!$connection->connect_error) {
			$this->connection = $connection;

			$this->connection->report_mode = MYSQLI_REPORT_STRICT;

			$this->connection->set_charset('utf8');
			
			$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';");

		} else {
			throw new \Exception('Error: Could not make a database link using ' . $username . '@' . $hostname . '!');
		}
	}
```

see https://github.com/opencart/opencart/issues/8976

**Comment by danielkerr** [comment]
$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");

**Comment by SilverFoxA** [comment]
@danielkerr Any update on this?

**Comment by mhcwebdesign** [comment]
Try this constructor for the system/library/db/mysqli.php:

```
public function __construct($hostname, $username, $password, $database, $port = '3306') {
		try {
			$mysqli = @new \MySQLi($hostname, $username, $password, $database, $port);
		} catch (mysqli_sql_exception $e) {
			throw new \Exception('Error: Could not make a database link using ' . $username . '@' . $hostname . '!');
		}

		if (!$mysqli->connect_errno) {
			$this->connection = $mysqli;
			$this->connection->report_mode = MYSQLI_REPORT_ERROR;
			$this->connection->set_charset('utf8');
			$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");
		} else {
			throw new \Exception('Error: Could not make a database link using ' . $username . '@' . $hostname . '!');
		}
	}
```

**Comment by terrabyte911** [comment]
I'm getting the same with a new install of 3.0.3.7 and none of the above worked.
In the file `catalog/model/catalog/product.php` search `'0000-00-00'` and replace with `NULL`
Home page now renders.

**Comment by mhcwebdesign** [comment]
Try to change this line in system/library/db/mysqli.php

Old:
`$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");`

New:
`$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION'");`

See documentation at https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_mode for details.

**Comment by terrabyte911** [comment]
@mhcwebdesign Confirmed this works. Thank you.

**Comment by mhcwebdesign** [comment]
Can someone please also test it with previous MySQL 5.x versions before a final commit?

**Comment by condor2** [comment]
@mhcwebdesign no issue on MySQL 5.6.51

**Comment by mhcwebdesign** [comment]
Thanks for the update. I have now updated the 3.0.x.x_Maintenance branch accordingly.

**Comment by akoweb** [comment]
> Try to change this line in system/library/db/mysqli.php
> 
> Old: `$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");`
> 
> New: `$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION'");`
> 
> See documentation at https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_mode for details.

it worked ! thanks
