### ISSUE TITLE
Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template

### ISSUE THREAD

**Issue by Manish101988** [opencart/opencart#9077]
Fatal error: Uncaught Exception: Error: Could not load template /home1/fulbazxw/public_html/catalog/view/theme/default/template/common/footer_top.twig! in /home1/fulbazxw/public_html/system/library/template/twig.php:17 Stack trace: #0 /home1/fulbazxw/public_html/system/library/template.php(51): Template\Twig->render('default/templat...', '') #1 /home1/fulbazxw/public_html/system/engine/loader.php(125): Template->render('default/templat...', '') #2 /home1/fulbazxw/public_html/catalog/controller/common/footer_top.php(67): Loader->view('common/footer_t...', Array) #3 /home1/fulbazxw/public_html/system/engine/action.php(79): ControllerCommonFooterTop->index(Array) #4 /home1/fulbazxw/public_html/system/engine/loader.php(48): Action->execute(Object(Registry), Array) #5 /home1/fulbazxw/public_html/catalog/controller/common/footer.php(16): Loader->controller('common/footer_t...') #6 /home1/fulbazxw/public_html/system/engine/action.php(79): ControllerCommonFooter->index(Array) #7 /home1/fulbazxw/public_html/system/engine/loader.ph in /home1/fulbazxw/public_html/system/library/template/twig.php on line 17

**Comment by condor2** [comment]
Nice report......

**Comment by Manish101988** [comment]
Need your support

**Comment by condor2** [comment]
RIP search

https://github.com/opencart/opencart/issues/8103

**Comment by danielkerr** [comment]
theres no footer_top
