### ISSUE TITLE
[master-branch] Pagination: division by zero & non-numeric value

### ISSUE THREAD

**Issue by SaifAlSubhi** [opencart/opencart#9079]
**What version of OpenCart are you reporting this for?**
opencart-master-branch [59bbb4c87e](https://github.com/opencart/opencart/commit/59bbb4c87ef265ba3363f543b5afc47bcca446ae)

**Describe the bug**
```
Warning: Division by zero in admin/controller/common/pagination.php on line 30
Warning: A non-numeric value encountered in admin/controller/setting/store.php on line 169
Warning: Division by zero in admin/controller/setting/store.php on line 169
```

**To Reproduce**
Login into admin panel and you will get this error.

**Screenshots**
It is a text error.

**Server / Test environment**
Local development web server
ubuntu 20.04 LTS
PHP 7.4.3 cli
Apache 2.4.41
Google Chrome Stable 87.0.4280.88

**Additional context**

```

```

**Comment by danielkerr** [comment]
just resave you settings

**Comment by SaifAlSubhi** [comment]
> just resave you settings

![image](https://user-images.githubusercontent.com/7532713/103930515-4c984c80-5138-11eb-964f-792179b01519.png)

even if I go to the store setting and then save.. I got errors.

**Comment by danielkerr** [comment]
I'm not here to fix problems on ur site. U have posted multiple issues that seem to be just related to u. I'm not ur web site building babysitter. Post again u are banned

**Comment by condor2** [comment]
@danielkerr in that moment you can't save settings because give you error and you cant see where is that error 
So better is to change from

`config_admin_language` in to `config_language_admin`

and 

`config_pagination` to `config_pagination_admin`

**Comment by danielkerr** [comment]
Not on the master branch.

**Comment by danielkerr** [comment]
saves for me

![image](https://user-images.githubusercontent.com/5079756/185740126-aa3e8f02-0df9-4539-b667-1c4b75637dde.png)

**Comment by danielkerr** [comment]
@condor2 or do u mean after upgrade
