### ISSUE TITLE
[Master] Upgrade error message

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#9084]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
OpenCart upgrade

**To Reproduce**
- Upload the master file
- start the install/update process

**Expected behavior**
The standard update process steps

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/104012395-caa03600-51c0-11eb-9d9e-64f5ae4c1e23.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? localhost
 - Operating system Debian 10
 - PHP version 7.4.11
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]  Firefox
 - Version [e.g. 22] 84.02

**Additional context**

**Comment by danielkerr** [comment]
linked https://github.com/opencart/opencart/issues/8970
