### ISSUE TITLE
marketplace uplaod

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#9086]
https://github.com/opencart/opencart/blob/cfa2efdd46669ebb6e8b7885b498a0c2353593ce/upload/admin/controller/marketplace/installer.php#L139

Add tokem
```
$token = token(32);
$file = DIR_STORAGE . 'marketplace/' . $filename . '.' . $token;
```
....

```
'code'              	=> basename($filename, '.ocmod.zip .' .  $token),
```

**Comment by danielkerr** [comment]
n0ot required because the storage directory should not be under the main web root! maybe i should stop the store from working until this has been done. there is a htaccess file that should be blocking this also.
