### ISSUE TITLE
Undefined property: Proxy::getConfigArray

### ISSUE THREAD

**Issue by MrClone420** [opencart/opencart#9090]
So after I tried to upload a AMP module ( actually it was just 2 folders )  to opencart version 2.2.0.0 I got the errors I will list below. I then deleted the files to try and clear the error, but ended up still having them and now I can not login to admin, nor can I see my site. Here are the error codes that I am getting. ( also I am new to this so please explain like you would to a child ) at my sites homepage I get this

>Notice: Undefined property: Proxy::getConfigArray in /home/s5ri4g25zhe7/public_html/system/storage/modification/system/engine/action.php on line 44

In error files I get these:
>[08-Jan-2021 13:17:40 UTC] PHP Fatal error:  Uncaught Error: Class 'Proxy' not found in /home/s5ri4g25zhe7/public_html/system/storage/modification/system/engine/loader.php:43
Stack trace:
#0 /home/s5ri4g25zhe7/public_html/catalog/controller/startup/startup.php(37): Loader->model('localisation/la...')
#1 /home/s5ri4g25zhe7/public_html/system/storage/modification/system/engine/action.php(44): ControllerStartupStartup->index()
#2 /home/s5ri4g25zhe7/public_html/system/engine/front.php(34): Action->execute(Object(Registry))
#3 /home/s5ri4g25zhe7/public_html/system/engine/front.php(19): Front->execute(Object(Action))
#4 /home/s5ri4g25zhe7/public_html/system/framework.php(99): Front->dispatch(Object(Action), Object(Action))
#5 /home/s5ri4g25zhe7/public_html/index.php(28): require_once('/home/s5ri4g25z...')
#6 {main}
  thrown in /home/s5ri4g25zhe7/public_html/system/storage/modification/system/engine/loader.php on line 43

Here is what the files are/say that first location 

>Uncaught Error: Class 'Proxy' not found in /home/s5ri4g25zhe7/public_html/system/storage/modification/system/engine/loader.php:43
Stack trace:

    $proxy = new Proxy();

Here is #0

		$this->load->model('localisation/language');

Here is #1

	return call_user_func_array(array($controller, $this->method), $args);	

Here is #2 and #3

	foreach ($this->pre_action as $pre_action) {
			
	$result = $action->execute($this->registry);

Here is #4

    $controller->dispatch(new Action($config->get('action_router')), new 

Here is #5

    require_once(VQMod::modCheck(DIR_SYSTEM . 'framework.php'));

lastly here is #6
    
		$proxy = new Proxy();

I am having a hard time finding a fix for my specific issue. Any help would be very much appreciated.

 - Local development? Deployed to a web server? = yes mysql
 - Operating system = linux
 - PHP version 7.3.6

**Comment by danielkerr** [comment]
We are not dealing with version 2.xx please use the forums

do not post here!
