### ISSUE TITLE
Events system What Where When

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#9091]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
https://github.com/opencart/opencart/blob/4480c147045a36cae1a0be8fc7c960aa94337cdb/upload/catalog/controller/startup/event.php#L19-L21

What is event  - sysytem?

How and where these events are used?

**Comment by danielkerr** [comment]
Will be writing docs once beta is released. There are some in the wiki already
