### ISSUE TITLE
$data['products'][] = $this->load->controller('product/thumb', $product);

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#9095]
https://github.com/opencart/opencart/blob/b3413606582619c654debdb930639218ef4e4b0a/upload/catalog/controller/product/category.php#L167-L205

I need to add mpn(isbn, sku etc) to the product preview, why am I limited to this product_data only.

And no events, without external code, I will not get them.
```
foreach ($results as $result) {
	$data['products'][] = $this->load->controller('product/thumb', $result);
}
```
And in product/thumb I myself will decide what to do with this data, especially since the method is available for events

**Comment by stalker780** [comment]
I have proposed to move this repeating code to product/thumb half year ago, but it was rejected by straightlight

https://github.com/opencart/opencart/pull/8010

**Comment by chulcha** [comment]
@stalker780 :(

@straightlight - Why?

**Comment by mhcwebdesign** [comment]
`Also it's still a mystery how to edit SQL queries if you want to add new fields there or join tables.`

This is no mystery at all. OC uses model classes with their own methods for which you can write event handlers. 

I don't see the point of using OCmod/VQmod again for OC4.

**Comment by stalker780** [comment]
> This is no mystery at all. OC uses model classes with their own methods for which you can write event handlers.
> 
> I don't see the point of using OCmod/VQmod again for OC4.

1. How are you going to use model event here? How you will add custom fields or JOIN here?
https://github.com/opencart/opencart/blob/b3413606582619c654debdb930639218ef4e4b0a/upload/catalog/model/catalog/product.php#L9
or here?
https://github.com/opencart/opencart/blob/b3413606582619c654debdb930639218ef4e4b0a/upload/catalog/model/catalog/product.php#L371


2. How are you going to change $sql before calling $this->db->query($sql) here, even you pass all needed parameters in $data?
https://github.com/opencart/opencart/blob/b3413606582619c654debdb930639218ef4e4b0a/upload/catalog/model/catalog/product.php#L167

An only way is to link event before DB::mysqli::query function. There will be a mess of hundreds events pointing to this function. And they all will be executed on every single query, not only for needed model function.

**Comment by chulcha** [comment]
> This is no mystery at all. OC uses model classes with their own methods for which you can write event handlers.

I need to add my table into query getProducts

Ok, i writing event and for me it's good

Someone also needs to add table into query getProducts

And he write event?
but he doesn't know about my table

So you need a sqlbuilder for such requests

BUT mono LINE sql string

**Comment by stalker780** [comment]
> Perhaps adding at least an extension code or id to oc_event table could help filtering events by installed extension... Don't know just thinking.

I think, it's a good idea to organize events manager in admin area.

All events can be built as tree:

Opencart default
|-- Event1
|-- Event2

Opencart mail
|-- Event1
|-- Event2

My extension 1
|-- Event1
|-- Event2

My extension 2
|-- Event1
|-- Event2

Also add events filter by extension name, event code, path, before|after, description, status
This will allow to select events only for one extension and work with them (enable/disable for debugging)

Same for startups.

Otherwise it will look like a useless mess of data where you can only switch between pages.

Also it would be easy to cleanup events and startups for uninstalled/deleted extensions by extension_code.

**Comment by chulcha** [comment]
I support this proposal
Create an advanced filter.
This will greatly help event management.
but this is a separate topic

**Comment by danielkerr** [comment]
if any one wants to start wring the event system documentation that would be great. 

i already started here:

https://github.com/opencart/opencart/wiki/Events-System

willing to pay to a come up with some documentation 

100 usd per example.

such as how to add templates, languages, modifying variables for models, views, controllers.
