### ISSUE TITLE
Upgrade page

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#9102]
Is this the final look of the update page? Or just forgot about her?
![image](https://user-images.githubusercontent.com/12296392/104129580-7e4e2500-537d-11eb-8cec-c5a5ddcdb429.png)

**Comment by danielkerr** [comment]
linked 
https://github.com/opencart/opencart/issues/8970

**Comment by Hkr32** [comment]
I meant the look of the page, the design of the page

**Comment by danielkerr** [comment]
Will be fixed when I get to it before release.

**Comment by Hkr32** [comment]
Have you looked at the installation steps pages?
https://github.com/opencart/opencart/pull/9130
If norm, I can make both update and error pages

**Comment by danielkerr** [comment]
"If norm, I can make both update and error pages"

please
