### ISSUE TITLE
OC4 extension code & OC Marketplace

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#9104]
As far as I know, OpenCart Marketplace strips underscore symbol `_` from filenames on download. 
This did not matter for OC2-OC3. But will in OC4.

https://github.com/opencart/opencart/blob/b3413606582619c654debdb930639218ef4e4b0a/upload/admin/controller/marketplace/installer.php#L221

This will break many extensions, having underscore in their names once they are downloaded.
Source files will have hardcoded routes `module/my_extension`, while extension will be installed with `myextension` code.

Also this may break an extension if someone decides to store extension version in it's name, or just rename an extension zip file.

I suggest to store extension code inside install.xml file. And use it in installer::upload() function.

**Comment by danielkerr** [comment]
thats how it has to be done. all name conventions get converted from  my_class.php to MyClass. im not matching file names to class names when i have always been taught file names should be lower case with underscore. very easy to do these conversions with regex.
