### ISSUE TITLE
Branch[3.0.x.x_Maintenance][Fatal Error]: When the customer views the recurring payments did through the PayPal Express payment method.

### ISSUE THREAD

**Issue by swetasom** [opencart/opencart#9105]
**What version of OpenCart are you reporting this for?**
Test Environment--
-- opencart version: Version 3.0.3.6

**Describe the bug**
When the customer views the recurring payments did through the PayPal Express payment method then the customer is facing the error: **Fatal error: Uncaught Exception: Error: Could not load template**

What section does it affect?
Customer's Recurring Payments sections.
**To Reproduce**
1. Go to ' Customer Account Page'.
2. Click on 'Recurring Payments'
3. Click on the view button of Recurring Payment that is done through the PayPal Express payment method.
4. See error: **Fatal error: Uncaught Exception: Error: Could not load template**

**Expected behavior**
Recurring Payment details must be displayed.

**Screenshots / Screen recordings**
![Selection_451](https://user-images.githubusercontent.com/51956187/104150349-ac744900-53ff-11eb-8733-822509ef3e17.png)

**Server / Test environment (please complete the following information):**
opencart version: 3.0.3.6
operating system: Ubuntu 16.04 LTS
PHP version-- 7.4.11
browser/browser version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by swetasom** [comment]
The file has been removed.
https://github.com/opencart/opencart/commit/a612ab99e7cecc19aacd0d19bff1f33be36c55d2

**Comment by WebkulOpencart** [comment]
@danielkerr As we checked this file was removed by you in a commit.
Do we need to add this file or not?

**Comment by danielkerr** [comment]
Please fix

**Comment by swetasom** [comment]
Recurring payments are creating at PayPal's end.
![order-history](https://user-images.githubusercontent.com/51956187/104990295-537d6400-5a42-11eb-9277-94f74935f079.png)
![paypal-recurring](https://user-images.githubusercontent.com/51956187/104990306-57a98180-5a42-11eb-9354-606f9b0581fd.png)
