### ISSUE TITLE
SQL query error

### ISSUE THREAD

**Issue by Grumvol** [opencart/opencart#9107]
Hi. Version 3.0.3.6

Site traffic 3000 per day. Several times a day I see this error. What is the reason for this?

Exception:  Error: Deadlock found when trying to get lock; try restarting transaction<br />Error No: 1213<br />UPDATE oc_cart SET session_id = 'd0552a64163c4dfe0355722821' WHERE api_id = '0' AND customer_id = '2326' in /system/library/db/mysqli.php on line 40

Apache 2.4
Nginx 1.17
PHP 7.3
MariaDB 10.3

**Comment by osworx** [comment]
Well, a simple search will help you (this has nothing to do with OpenCart itself):
https://www.google.com/search?source=hp&ei=e138X6GfEOyD1fAPg8CYiAg&q=deadlock+found+when+trying+to+get+lock+try+restarting+transaction&oq=Deadlock+found+when+trying+to+get+lock&gs_lcp=CgZwc3ktYWIQAxgAMgIIADIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHkoFCAUSATFKBQgHEgExSgUICRIBMUoHCAoSAzEwOFCKBFiKBGDPG2gAcAB4AIABdYgBdZIBAzAuMZgBAKABAqABAaoBB2d3cy13aXo&sclient=psy-ab

**Comment by userlond** [comment]
@osworx, why it's not Opencart issue?
