### ISSUE TITLE
notice: a non well formed numeric value encountered error

### ISSUE THREAD

**Issue by oneproove** [opencart/opencart#9111]
I have error when I click on subcategory in my store. Pls I need help to fix it.

Error:
Notice: a non well formed numeric value encountered in /home/u419938842/domains/mydomain.com/public_html/system/helper/utf8.php on line 21

This is the code:
<?php
if (extension_loaded('mbstring')) {
	mb_internal_encoding('UTF-8');

	function utf8_strlen($string) {
		return mb_strlen($string);
	}

	function utf8_strpos($string, $needle, $offset = 0) {
		return mb_strpos($string, $needle, $offset);
	}

	function utf8_strrpos($string, $needle, $offset = 0) {
		return mb_strrpos($string, $needle, $offset);
	}

function utf8_substr($string, $offset, $length = NULL) {
    if($length == NULL)
        return mb_substr($string, $offset, utf8_strlen($string));
    else
        return mb_substr($string, $offset, $length);
}
	}

	function utf8_strtoupper($string) {
		return mb_strtoupper($string);
	}

	function utf8_strtolower($string) {
		return mb_strtolower($string);
	}
} elseif (function_exists('iconv')) {
	function utf8_strlen($string) {
		return iconv_strlen($string, 'UTF-8');
Screenshot:
![Screenshot_2](https://user-images.githubusercontent.com/77319304/104292176-c9bb1d00-54bc-11eb-846a-e1cc4485ab08.png)

**Comment by danielkerr** [comment]
pleease popst in the fourm. it soulds like some onee is trying to hack your site by sending strings or arrays insteead of inerge. its probably not a big issue.  but you can force the type of data to be a sting. please ask in the forums. its not hard to fix.
