### ISSUE TITLE
BreadCrumbs Add controller and view

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#9116]
If you've added a controller for pagination, why not add a controller for breadcrumbs

catalog/controller/common/breadcrumbs.php
```
<?php
namespace Opencart\Application\Controller\BreadCrumbs;
class BreadCrumbs extends \Opencart\System\Engine\Controller {
	public function index($data) {
		$this->load->language('common/breadcrumbs');
		return $this->load->view('common/breadcrumbs', $data);
	}
}
```

catalog/view/template/common/breadcrumbs.twig
```
  <ul class="breadcrumb">
    {% for breadcrumb in breadcrumbs %}
      <li class="breadcrumb-item"><a href="{{ breadcrumb.href }}">{{ breadcrumb.text }}</a></li>
    {% endfor %}
  </ul>
```

And in other controllers before
$data['column_left'] = $this->load->controller('common/column_left');

Add
$data['breadcrumbs'] = $this->load->controller('common/breadcrumbs', $data['breadcrumds']);

Or change the forming of the array breadcrumbs  from $data['breadcrumds']  to $breadcrumbs

**Comment by chulcha** [comment]
Why closed?

**Comment by danielkerr** [comment]
ferature requts post some where else. im trying toi get actual tickets down

**Comment by chulcha** [comment]
But this is relevant for the new version (s)
Take out separate data entities and process them using the same event system, but in one place.
Otherwise, if I need to change something in BC, then I need to bind events to all view's that use breadcrumbs

**Comment by danielkerr** [comment]
its not worth it. its nearly the same amount of code just to remove the breadcrumbs.

**Comment by chulcha** [comment]
I am based in hundreds of stores that use microdata for breadcrumbs, for example

**Comment by stalker780** [comment]
> its not worth it. its nearly the same amount of code just to remove the breadcrumbs.

But it is more logical from events viewpoint.
