### ISSUE TITLE
OC4 - seo_url

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#9125]
Trying to build a module url for ajax calls in store frontend:

$data['extension_url'] = $this->url->link('extension/dummy_ext/module/dummy_module/ajax', 'language=' . $this->config->get('config_language'), true);

with seo_url enabled get broken url
http://website.loc/en-gb?route=extension/dummy_ext/module/dummy_module/ajax

with seo_url disabled get correct url
http://website.loc/index.php?route=extension/dummy_ext/module/dummy_module/ajax&language=en-gb
but still **it returns frontpage with code 404**, unable to reach ajax() function in module controller

**Comment by chulcha** [comment]
|  - is metthod

**Comment by stalker780** [comment]
Facepalm. My fault. Still cannot get used to |
