### ISSUE TITLE
PHP Warning:  Use of undefined constant VERSION

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9127]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

PHP Warning:  Use of undefined constant VERSION - assumed 'VERSION' (this will throw an Error in a future version of PHP) in .../admin/controller/common/footer.php on line 8
`$data['text_version'] = sprintf($this->language->get('text_version'), VERSION);`

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
you reporting errors you cause your self again?

**Comment by cgcmart** [comment]
> 
> 
> you reporting errors you caused your self again?

Yes.
Home > Error Log

**Comment by danielkerr** [comment]
Version is hard coded on all opencarts index.php files. Only way for it to show is if u deleted it

**Comment by snjjay** [comment]
When undefined constants are used in PHP code, this error occurs. It could appear due to missing quotes in strings, a missing dollar sign in variables, or the presence of an invalid character. I find this article useful https://kodlogs.net/311/php-notice-use-of-undefined-constant
