### ISSUE TITLE
Default Currency always stays USD 

### ISSUE THREAD

**Issue by tjapro** [opencart/opencart#9133]
**What version of OpenCart are you reporting this for?**
3.0.3.6

**Describe the bug**
Even if I change the currency value via admin page or right in the database, the USD currency stays 1.00000000 and, for example, EUR mainstains 1.00000000.

**To Reproduce**
1. Go to Currencies page
2. Change the currencies values according to another coin, for example EUR.
3. Clean Cookies.
4. Enter again that admin page and the currencies are the correct, except the USD (stays 1.00000000 as default).

**Expected behavior**
The new 1.00000000 currency value should be the new default.

**Screenshots / Screen recordings**

Warning: A non-numeric value encountered in /var/www/.../admin/model/localisation/currency.php

This message appears many times before the actual admin page.
Note: This message also apears when I add a new currency (but in this case without admin page).

**Server / Test environment (please complete the following information):**
VPS
CentOS 7
PHP 7.4.0
Nginx 1.16.1
Chrome
Version 87.0.4280.88

**Additional context**
This is a new fresh open cart installation.

**Comment by webkul-dilip** [comment]
You need to select currency at the store setting as well, please check the screenshot  http://i.prntscr.com/PNBJ2BmATbWqVL3AVDFO0Q.png

**Comment by tjapro** [comment]
Thanks.
