### ISSUE TITLE
Undefined index: en-gb when store language is disabled

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#9137]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
 Undefined index: en-gb in catalog\controller\startup\language.php on line 113

**To Reproduce**

**When are two languages** for example: EN and RO

1. Set front store language to EN
2. Disable EN language from admin
3. Clear browser history/cache
4.  Access the store URL

This warning message is displayed
Notice: Undefined index: en-gb in catalog\controller\startup\language.php on line 113

**Expected behavior**
I don't know...the store should redirect to second language witch is enabled in admin...or to display another message?

**Comment by danielkerr** [comment]
why the f**k when u disable the only language should it redirect to a second language! your just wasting peoples time!

**Comment by condor2** [comment]
If someone change by mistake the front store with a disabled language or disable by mistake the store language that warning is displayed.

If you read again you will see is about 2 languages....

**Comment by Hkr32** [comment]
In general, it is correct to check the language and include the one that is by default, if the selected one is not previously available
