### ISSUE TITLE
No warning message when qty < min qty

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#9141]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
If a product has for example a minimum qty = 5 when you go to product page and change qty to 3 and click Add to cart, that product is added in cart with 3 qty.

A warning message is when you view the cart and should be one on product page

**Expected behavior**
Should display a warning message when qty inserted is < min qty.

**Comment by danielkerr** [comment]
so u are saying that people can not use product options.

**Comment by danielkerr** [comment]
u have psot6ed multiple issues today. all bullshit ones.

**Comment by condor2** [comment]
Maybe now you understand.....
![iphone](https://user-images.githubusercontent.com/14251939/104936560-5b42f700-59b5-11eb-8415-40439ae86b8c.png)

**Comment by danielkerr** [comment]
yes but they can not checkout with that number. we had this conversation years ago and i decided that if people want to order the same product but with different options they should be able to do that! and yes there is an error message displayed on the checkout page! not hard for you to work this out!
