### ISSUE TITLE
Broken Date css Special and Discount

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#9144]
**What version of OpenCart are you reporting this for?**
Master Branch

**Describe the bug**
Calendar should be in front.

**Screenshots / Screen recordings**
![css_issue](https://user-images.githubusercontent.com/14251939/105017590-a1976500-5a4c-11eb-823b-9b9b48ad7e08.png)

**Comment by danielkerr** [comment]
will update to latest 

https://getdatepicker.com/5-4/Usage/
