### ISSUE TITLE
AWS SES: Error: The SMTP server has refused the sender's email!

### ISSUE THREAD

**Issue by garbinmarcelo** [opencart/opencart#9148]
**What version of OpenCart are you reporting this for?**
OpenCart v3.0.3.1 (Brasil 1.2.4)

I've tried to make several types of settings, all to no avail. It even replaces the files mail.php and smtp.php with the files present in this repository. But nothing done, the problem persists.

Any help or ideas to solve this?

Email configuration:
![image](https://user-images.githubusercontent.com/9335588/105079698-8a696f00-5a6e-11eb-9c3f-8affff541126.png)

**Server**
 - AWS EC2
 - Operating system Ubuntu 18.04.5 LTS
 - PHP version v7.3.26
 - nginx v1.14.0

I already use AWS SES with projects in Laravel, in which case it is already enabled to be used in production. DNS settings have been verified, I use Cloudflare.

I appreciate the help of everyone.

**Comment by mhcwebdesign** [comment]
Worst of 2 worlds: AWS and Cloudflare. Try at least to temporarily disable Cloudflare, to see whether it makes any difference.

Anyway, this is not an OpenCart, more likely an issue with your web server or CloudFlare. Without further details it is difficult to help you.

**Comment by ADDCreative** [comment]
Best to ask on https://forum.opencart.com/ and explain where exactly you see the error.

**Comment by danielkerr** [comment]
see whats happening. people see issues getting fixed they all jump in posting there own issues with their code.

use the forum or the support system
