### ISSUE TITLE
[master - question] Adding new event(s) | Proposal to add new tag in install.xml

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#9154]
Because OCMods are not supported anymore, one (1) simple question:
> how can we add new events to the system?

Example: no admin nor catalog template files, nothing to setup, no settings.
Want only add one (or more) event(s) which are applied by the corresponding functions (admin/catalog).
But because there is no admin interface, how can I add them?

Sounds maybe like a stupid question, but how is the answer?

**Comment by chulcha** [comment]
no way.

**Comment by Hkr32** [comment]
Make a controller with installation, empty settings and adding an event)

**Comment by osworx** [comment]
> 
> 
> Make a controller with installation, empty settings and adding an event)

That's I thought also the only way to add new events.
But can't be finally the last solution for this (simple) task!?

Why not adding a new installation (function) - maybe inside the **install.xml**?
Could be easily done by a new tag like `<event> .. </event>`
No need to add controllers etc. ..

Just saying "no way" is for sure not the correct way.

**Comment by danielkerr** [comment]
i will be writing a guide once i launch beta. 

im just updating the order editor page
i need top fix the recurring payments. i don't like having a recurring_button template. the guy was a clown who added that stuff. 

replace carousel also

**Comment by Hkr32** [comment]
> i don't like having a recurring_button template. the guy was a clown who added that stuff.

what?

![image](https://user-images.githubusercontent.com/12296392/105217956-93893780-5b65-11eb-9383-28edcf59e2f7.png)
