### ISSUE TITLE
Errors on upgrade

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#9157]
Error after 1005 patch
![up-er-1](https://user-images.githubusercontent.com/12296392/105405701-7ffcd000-5c3c-11eb-8659-63e6bcb7f5d3.png)
![uo-er-2](https://user-images.githubusercontent.com/12296392/105405707-81c69380-5c3c-11eb-82df-3c9562fb54ca.png)
![up-er-3](https://user-images.githubusercontent.com/12296392/105405715-83905700-5c3c-11eb-8a85-a0f83bee4aac.png)
![up-er-4](https://user-images.githubusercontent.com/12296392/105405721-84c18400-5c3c-11eb-938b-4860194fe53b.png)
![up-er-5](https://user-images.githubusercontent.com/12296392/105405911-bdf9f400-5c3c-11eb-8bc2-0ebcc309d260.png)

**Comment by danielkerr** [comment]
i have already said the upgrade system will be finished ast the end. there is already a issue opened about it. l can read error messages
