### ISSUE TITLE
Opencart 3.0.3.6 -> modification.xml in system folder is broken

### ISSUE THREAD

**Issue by Yobikap** [opencart/opencart#9159]
`2021-01-21 21:53:23 - MOD: Modification Default

FILE: system/library/template/twig.php
CODE: $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);
NOT FOUND - OPERATIONS ABORTED!`

just checked the file system/library/template/twig.php and I see a code that will never match in modification.xml
`$loader = new \Twig\Loader\ArrayLoader(array($filename . '.twig' => $code));`

Can you please fix this?
Some of the extension are depended on this piece of code and are not working anymore.

**Comment by condor2** [comment]
https://github.com/opencart/opencart/commit/d31b4ebe3fd29dcc8861725d4934c6e3dd68e019

**Comment by danielkerr** [comment]
3.x.x maintaNCE BRANCH NEEDS TO BE RELEASED SOON.
