### ISSUE TITLE
Image manager - search image - insert bug

### ISSUE THREAD

**Issue by TimwaySupport** [opencart/opencart#9160]
OC 3.0.2.0

**Describe the bug**
When use search function on image manager, image get inserted to the beginning of the editor, instead of the cursor position (that I want to insert the image)

**To Reproduce**
1. Control panel, product editing page, product description tag, 
2. Place the cursor at other position (e.g. the last paragraph)
3. Click image icon on toolbar to launch image manager
4. Search an image(any image)(the bugs trigger by search an image, if you just simple insert an image, no bug at all)
5. double click the searched image to insert it to the cursor posotion
6. The image was inserted to the being of the product description, instead of the cursor position.

**Expected behavior**
The image should insert to the cursor position before I launch the image manager.

**Server / Test environment (please complete the following information):**
I guess it's unrelated.

**Additional context**
Guessing of the issue: After you launch the image manage, if you place the cursor at the "search field", the original cursor position on the editor will "lost", and summernote.js just insert the selected image to the beginning of the editable content.

**Comment by condor2** [comment]
Post on forum...

**Comment by TimwaySupport** [comment]
Thank you for your reply, may I ask if
 "Post on forum..."
means 
 I should post this bug report on opencart forum? or
 I someone else already report such issue on opencart forum?

**Comment by ADDCreative** [comment]
This is a issue for the 3.0.x.x_Maintenance branch. It's a problem with the Summernote editor.

The solution is probably to upgrade Summernote to v0.8.18 or later. https://github.com/summernote/summernote/issues/1520

**Comment by TimwaySupport** [comment]
> This is a issue for the 3.0.x.x_Maintenance branch. It's a problem with the Summernote editor.
> 
> The solution is probably to upgrade Summernote to v0.8.18 or later. [summernote/summernote#1520](https://github.com/summernote/summernote/issues/1520)

Thank you for your reply and let us know that's a known issue.
I only search "image manager" on the oc github issue list, find nothing and so I open this bug report.

I manged to have some quick fix on this issue, (just record the cursor position on a editor attribute, and then recall if once summernote insert back the selected image.

Thank you for your help.
