### ISSUE TITLE
Cannot Activate Marketplace

### ISSUE THREAD

**Issue by tjapro** [opencart/opencart#9161]
**What version of OpenCart are you reporting this for?**
3.0.3.6

**Describe the bug**
I receive very PHP notice messages, and cannot activate the maketplace. The website says that the username and API is accepted, but I've got No results and cannot search anything. 

```
2021-01-22 12:39:12 - PHP Notice:  Trying to access array offset on value of type null in /var/www/.../admin/controller/marketplace/marketplace.php on line 167
2021-01-22 12:39:12 - PHP Notice:  Trying to access array offset on value of type null in /var/www/.../admin/controller/marketplace/marketplace.php on line 205
2021-01-22 12:39:12 - PHP Notice:  Trying to access array offset on value of type null in /var/www/.../admin/controller/marketplace/marketplace.php on line 222
```

**To Reproduce**
1. Go to Admin > Marketplace.
2. Click on button to add the key.
3. Add the key and accept.
4. See error and no results....

**Expected behavior**
Some extensions may appear.

**Screenshots / Screen recordings**

**Server / Test environment (please complete the following information):**
- VPS
- CentOS 7
- PHP 7.4.0
- Nginx 1.16.1
- Chrome
- Version 87.0.4280.88

**Additional context**
I tried to generate another key, and the problem is the same.

**Comment by condor2** [comment]
See if this help.
https://github.com/opencart/opencart/commit/b24c1145faf31e5fa88626ce3baea2c3d276954c

If not, try to replace entire code

**Comment by tjapro** [comment]
@condor2 I tried to change only the line. Same problem.

**Comment by tjapro** [comment]
@condor2 Is to replace the entire code with this https://github.com/opencart/opencart/tree/b24c1145faf31e5fa88626ce3baea2c3d276954c , correct?

**Comment by condor2** [comment]
https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/admin/controller/marketplace/marketplace.php

**Comment by tjapro** [comment]
@condor2 I've replaced the file, but the same issue.

**Comment by TheCartpenter** [comment]
Issue has already been fixed on the master branch. cURL protocol routes and variables have been sanitized and fixed.

**Comment by tjapro** [comment]
@TheCartpenter Thanks, and after upload the master marketplace.php file to the server I've got a 404 error:
```
[error] 20265#0: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Opencart\System\Engine\Controller' not found in /var/www/.../admin/controller/marketplace/marketplace.php:3
Stack trace:
#0 /var/www/.../vqmod/vqcache/vq2-_var_www_..._storage_modification_system_engine_action.php(69): include_once()
#1 /var/www/.../admin/controller/startup/router.php(26): Action->execute()
#2 /var/www/.../vqmod/vqcache/vq2-_var_www_..._storage_modification_system_engine_action.php(79): ControllerStartupRouter->index()
#3 /var/www/.../system/engine/router.php(67): Action->execute()
#4 /var/www/.../system/engine/router.php(56): Router->execute()
#5 /var/www/.../system/framework.php(165): Router->dispatch()
#6 /var/www/.../vqmod/vqcache/vq2-system_startup.php(104): require_once('/var/www/....')
#7 /var/www/..." while reading response header from upstream, client: server: request: "GET /admin/index.php?route=marketplace/marketplace HTTP/1.1", upstream: referrer: "https://.../admin/index.php?route=tool/log..."
```

**Comment by tjapro** [comment]
Maybe Iḿ missing some other files(s) ....

**Comment by condor2** [comment]
You can't use marketplace file from Master Branch to 3.0.3.6 without adapting the code to 3.0.3.6.

**Comment by tjapro** [comment]
I've tried to make the correct changes, but the situation is the same. I'll wait for the next release.
