### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by tjapro** [opencart/opencart#9164]
I'm publishing this issue only to know how the maintenance mode works.

In my case (a blank installation), the maintenance mode gives me a 404 error (nginx).
Is that normal or is it a bug?

OC Version 3.0.3.6

**Comment by TheCartpenter** [comment]
Please post on the Opencart forum for this inquiry at: opencart.com . You are currently posting on Github for developers working on the Master Branch (dev) version.
