### ISSUE TITLE
Composer update command deletes necessary dependencies OpenCart 3.0.3.6

### ISSUE THREAD

**Issue by aleksandrnikitenko** [opencart/opencart#9166]
Tags: Opecart 3.0.3.6, Facebbok Conversion API

OpenCart 3.0.3.6 => UltraStore template

**Issue:**
Trying to implement Facebook Conversion API.
At my storage folder i have composer.json file with next contents

`{
  "require": {
    "facebook/php-business-sdk": "^9.0.0"
  }
}
`

When i execute composer install commnad, i facing next:

`[conversi@uashared16 storage]$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 6 installs, 1 update, 17 removals
  **- Removing zoujingli/wechat-php-sdk (v1.3.18)
  - Removing twig/twig (v2.13.0)
  - Removing symfony/validator (v2.8.52)
  - Removing symfony/translation (v3.0.9)
  - Removing symfony/polyfill-mbstring (v1.18.0)
  - Removing symfony/polyfill-ctype (v1.18.0)
  - Removing scssphp/scssphp (1.1.1)
  - Removing react/promise (v2.8.0)
  - Removing psr/log (1.1.3)
  - Removing guzzlehttp/streams (3.0.0)
  - Removing guzzlehttp/ringphp (1.1.1)
  - Removing divido/divido-php (v1.15-stable)
  - Removing braintree/braintree_php (3.40.0)
  - Removing klarna/kco_rest (v2.2.0)
  - Removing guzzlehttp/oauth-subscriber (0.2.0)
  - Removing guzzlehttp/log-subscriber (1.0.1)
  - Removing cardinity/cardinity-sdk-php (v1.0.3)**
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/http-client (1.0.1): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing guzzlehttp/psr7 (1.7.0): Loading from cache
  - Installing guzzlehttp/promises (1.4.0): Loading from cache
  - Updating guzzlehttp/guzzle (5.3.4 => 7.2.0): Loading from cache
  - Installing facebook/php-business-sdk (9.0.3): Loading from cache`

Facebook library has been installed , but also, been deleted some necessary libs.

Also, autoload don't see Facebook classes:

`Class 'FacebookAds\Api' not found`

AND 

opencart crashes with error

`Class 'Twig_Loader_Array' not found`

Cured it with overwrite vendor from clean distributive, but it doesn't solve my problem.

**To Reproduce**
1. at directory "~/storage" try to execute command composer install **or** require (even with package name and version) with mentioned content
2. open any site url and see error **Class 'Twig_Loader_Array' not found**

**Expected behavior**
After composer install or update or require, autoload wokrs correctly and i can use API at product controller, for example.

 - Apache
 - 7.3 (lower isn't accetible, due to template requrements)

**Comment by TheCartpenter** [comment]
No longer supported on the master branch. Please post on the Opencart forum at: https://forum.opencart.com for those inquiries.

**Comment by prabhatkumaroc082** [comment]
it seems you are not requiring the rest of the packages which Opencart provides. It is also not supported on the maintenance branch so post on the Opencart forum if still, you are facing issues.
