### ISSUE TITLE
Added backward escaped quotes - catalog/model/catalog/product.php file

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#9168]
Added backward escaped quotes:

https://github.com/TheCartpenter/opencart/commit/208918e2186b3634fe832a7bfe7923fd13fd04a7

**Comment by danielkerr** [comment]
ur supposed to do a pull request

**Comment by TheCartpenter** [comment]
@danielkerr: Task completed: Merged to: https://github.com/TheCartpenter/opencart/commit/670625a6e7ed603b377e8ded17c11b676e3dfb90 .
