### ISSUE TITLE
Product Page Prices

### ISSUE THREAD

**Issue by SPB105438** [opencart/opencart#9186]
**What version of OpenCart are you reporting this for? maintenance-branch 3.0.x.x

**Describe the bug**
 Prices shown on Products Details page not shown correctly

**To Reproduce**
Clicking on any product will display the product page where more details of the product, but the price shows as 0.00 with the correct price striked out, looks like a special price is shown, but no special prices, discounts or offers have been setup

£0.00
Ex Tax: £0.00
Pricing on the shop front are displayed correctly
Adding the product to the shopping cart works correctly and the correct price is shown in the Cart and Checkout.

**Expected behavior**
Correct Price should be shown with price excluding tax shown below

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system: Windows server 2016
 - PHP version: 7.4
 - Browser(s) tested with Chrome, Edge
 - Version Version 87.0.4280.88 & Version 87.0.664.75

**Additional context**

**Comment by mathsolutions** [comment]
The merged commit #8985 is wrong, price shown is always 0 and old price is always stiked out eve if no 0 special price is set. I've always done a pull request #9018 to revert to the original code.

**Comment by prabhatkumaroc082** [comment]
reverting the original code will create an issue on special 0 prices, added new commit #9197 and it is under testing now,
