### ISSUE TITLE
FONT FILES MISSING /admin/view/fonts/bootstrap/glyphicons-halflings-regular

### ISSUE THREAD

**Issue by paolobiavati** [opencart/opencart#9188]
**What version of OpenCart are you reporting this for?**
3.0.x

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

FONT FILES MISSING:

THE FILE admin/view/template/common/header.twig INCLUDE /admin/view/stylesheet/bootstrap.css (line 16 )
<link href="view/stylesheet/bootstrap.css" type="text/css" rel="stylesheet" />

THE FILE /admin/view/stylesheet/bootstrap.css  link these font files (lines 205-206) :
  @font-face {
    font-family: 'Glyphicons Halflings';
    src: url("../fonts/bootstrap/glyphicons-halflings-regular.eot");
    src: url("../fonts/bootstrap/glyphicons-halflings-regular.eot?#iefix") format('embedded-opentype'), url("../fonts/bootstrap/glyphicons-halflings-regular.woff2") format('woff2'), url("../fonts/bootstrap/glyphicons-halflings-regular.woff") format('woff'), url("../fonts/bootstrap/glyphicons-halflings-regular.ttf") format('truetype'), url("../fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular") format('svg'); }

BUT THESE FILES DON'T EXIST IN /admin/view/fonts. (NEITHER THE FOLDER fonts exists into view folder..)

**To Reproduce**

init a datetimepicker with pickTime: true , "glyphicon glyphicon-time" icons will missing

 $('.datetime').datetimepicker({
            language: 'en_GB',
            pickTime: true
 });

**Expected behavior**

Add the folder and files that are missing please. 

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
they are not required as we use fontawsome.

**Comment by paolobiavati** [comment]
yes but bootstrap use them... and you use bootstrap
