### ISSUE TITLE
Cookie Policy doesn't work

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9190]
**What version of OpenCart are you reporting this for?**

Master branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

**Firefox** ignores cookie notification, doesn't show popup notification on the bottom of pages.

Both **Chrome** and **Edge** show popup cookie notification on the bottom of every page when browsing even though clicked the text link "click here" or  pressed the button "Yes, that's fine!" that means, a user pressed the button "Yes, that's fine!" once, the popup notification closed, then the user browses other page, the popup notification jumps out again, browser's back / forward / reload run into the same issue
![cookies_popup_issue](https://user-images.githubusercontent.com/14033183/105659492-d9f8d200-5e96-11eb-8337-598f9c71bec4.jpg)

Fix 'policy' cookie #9132 @SaifAlSubhi 

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
i buitl the cooki policy using chrome and it works fime for me.

**Comment by danielkerr** [comment]
i dont think u know how to update using git
