### ISSUE TITLE
Order Mail Add - text_greeting - v3

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#9192]
Hello.

Text in "catalog/mail/order_add", variable "text_greeting" should be changed or do other changes related with the problem.

1. Change text from
`Thank you for your interest in %s products. Your order has been received and will be processed once payment has been confirmed.`
to
`Thank you for your interest in %s products. Your order has been received.`

Problem:
Text is OK only for bank transfer, PayPal, credit cards etc. when you receive payment first.

It is NOT ok for COD, pick up etc. when you receive payment later once customer already received order.

Any idea?

**Comment by prabhatkumaroc082** [comment]
In this case,  he can simply change this message for add/edit orders
file-path: catalog/language/en-gb/mail/order_add.php
