### ISSUE TITLE
Opencart 3.0.2.0 Language Switch Issue

### ISSUE THREAD

**Issue by ozguryetgin** [opencart/opencart#9194]
**What version of OpenCart are you reporting this for?   * 3.0.2.0 *

I have two languages at my site, but language switch does not do anthing. Same page reloads everytime. (isimegelir.com)

**To Reproduce**
1. Go to 'isimegelir.com'
2. Click on 'language to switch'
3. See error 'it doesn't change'

**Expected behavior**
I want to use seo url at my site but, language swithing cannot sesion and shows same language.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? (Deployed a web server)
 - Operating system - Opencart 3.0.2.0
 - PHP version - 7.3
 - Browser(s) tested with [e.g. chrome, explorer]

**Comment by condor2** [comment]
Post on opencart forum..

`Uncaught SyntaxError: Unexpected token '<'`
