### ISSUE TITLE
Free checkout bug on Stripe plugin

### ISSUE THREAD

**Issue by jwweb** [opencart/opencart#9195]
All versions

on this plugin:
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=33831&filter_search=stripe

there is a function "checkoutWebhook" which would allow free checkout from a GET request.  I have contacted the developers but had no response.

This is the raw commit to fix

https://pastebin.com/18buWHRh

[stripe-pro-oc3.ocmod (2).zip](https://github.com/opencart/opencart/files/5872882/stripe-pro-oc3.ocmod.2.zip)

**Comment by condor2** [comment]
Post on forum
