### ISSUE TITLE
transfer user_token from url

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#9196]
Maybe you should remove it to the session?
In order not to specify it in the url address all the time?

**Comment by Hkr32** [comment]
At least they left a comment why they closed

**Comment by danijelGombac** [comment]
@Hkr32 

https://github.com/opencart/opencart/blob/776516b01cd9ebbe8c7ad23e4a55f0e13c32cf68/upload/admin/controller/common/login.php#L11

**Comment by ADDCreative** [comment]
@Hkr32 The token in the URL is a security feature. Moving to to the session would not provide the same security and leave you vulnerable to some types of attacks.

**Comment by Hkr32** [comment]
But the rest somehow live without it?

**Comment by ADDCreative** [comment]
@Hkr32 What do you mean by "the rest"? Best to take this discussion to https://forum.opencart.com/.
