### ISSUE TITLE
Unable to make changes to customer due to password fields

### ISSUE THREAD

**Issue by SPB105438** [opencart/opencart#9214]
**What version of OpenCart are you reporting this for? - Maintenance Branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect? - Changes to customers

**To Reproduce**
1. Try to make any changes to the customer record and saving results in the changes being lost, and a warning is displayed.
" Warning: Please check the form carefully for errors!"

**Expected behavior**
Any changes should allow the record to save without having to provide / complete the password fields

**Screenshots / Screen recordings**

**Server / Test environment (please complete the following information):**
 - Local development? Server -  Development
 - Operating system - Windows server 2016
 - PHP version 7.4
 - Browser(s) tested with Latest version of Edge and Google Chrome

**Additional context**
Fantastic work guys, cant wait for the official release!!

**Comment by danielkerr** [comment]
just make sure its clear when saying.

**Comment by SPB105438** [comment]
I have a fresh install of the dev branch, but when i login as an 'Admin' and goto Customers > and edit a customer, then try to change any field (with or without entering a password) then try to save the changes, the warning is displayed "Warning: Please check the form carefully for errors!"

If i login as the customer to my account, I can change my details, and add addresses without issue.

**Comment by SPB105438** [comment]
Not sure if this is any help to you

2021-01-30 18:36:30 10.74.141.28 GET /admin/index.php route=customer/customer/reward&user_token=2W0ePwqzdlMkcFp5OKirkG5EshbiWPz5&customer_id=2 80 - 192.168.11.52 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/88.0.4324.96+Safari/537.36+Edg/88.0.705.56 http://devstoreapp/admin/index.php?route=customer/customer/edit&user_token=2W0ePwqzdlMkcFp5OKirkG5EshbiWPz5&customer_id=2 200 0 0 203

**Comment by danielkerr** [comment]
Belcajar og ur broesers autocompete field

**Comment by SPB105438** [comment]
Autocomplete was not completing any fields, I had deleted all customers, and cleared all Customer database tables, and tried again,  same error.
However i have deleted all the files and redownloaded the maintenance branch again, and the error has gone, everything is working, maybe a rouge setting or file left behind, i dont know what it was and i cannot recreate the issue, appreciate all the work you all put in to this, sorry for wasting your time
