### ISSUE TITLE
first products are not shown in assigned categories, but second product is showing. but count shown as 2 products in this category.

### ISSUE THREAD

**Issue by ramsmart-inno** [opencart/opencart#9222]
I am using the 3.0.3.1 version.

Could someone give a valid fix for this issue?

Thank you.

**Comment by WebkulOpencart** [comment]
Can you share the video of the issue so that we can check the same

Or please disable the third-party module and then check the same.

**Comment by ramsmart-inno** [comment]
At the Product level, I assigned to the Boys > Mask category in the admin panel.

<img width="1116" alt="Screenshot 2021-02-06 at 7 38 49 PM" src="https://user-images.githubusercontent.com/72604311/107120344-2094f600-68b3-11eb-89c3-5e5c422c4404.png">


But, it not showing in the Frontend Category level.
<img width="1323" alt="Screenshot 2021-02-06 at 7 38 18 PM" src="https://user-images.githubusercontent.com/72604311/107120327-1115ad00-68b3-11eb-9639-0881e30cf940.png">


At the same time it is shown in search

Thank you in advance to fix this issue to forward.
