### ISSUE TITLE
Opencart 3.0.3.7 version bump

### ISSUE THREAD

**Issue by lucian-tanase** [opencart/opencart#9223]
In packages downloaded from https://www.opencart.com/index.php?route=cms/download and https://github.com/opencart/opencart/releases VERSION constant is still 3.0.3.6, please update.

**Comment by jameswill** [comment]
Hi,

I am also getting 3.0.3.6 version 3.0.3.7 package after installing manually.

I think it should change version number in index.php

**Comment by danielkerr** [comment]
just updated the current version with the version change

**Comment by jameswill** [comment]
From where we can download the updated package ?
