### ISSUE TITLE
OpenCart 3.0.3.7 installation does not work on MySQL 8

### ISSUE THREAD

**Issue by MikhailShemelin** [opencart/opencart#9224]
**What version of OpenCart are you reporting this for?**
OpenCart 3.0.3.7

**Describe the bug**
installation does not work on MySQL 8

> Fatal error: Uncaught Exception: Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'<br />
> Error No: 1231<br />SET @@session.sql_mode = 'MYSQL40' in \system\library\db\mysqli.php:41
> Stack trace:
> #0 \system\library\db.php(45): DB\MySQLi->query('SET @@session.s...')
> #1 \install\model\install\install.php(35): DB->query('SET @@session.s...')
> #2 \system\engine\loader.php(248): ModelInstallInstall->database(Array)
> #3 \system\engine\proxy.php(47): Loader->{closure}(Array, Array)
> #4 \install\controller\install\step_3.php(11): Proxy->__call('database', Array)
> #5 \system\engine\action.php(79): ControllerInstallStep3->index()
> #6  in \system\library\db\mysqli.php on line 41

**Server / Test environment (please complete the following information):**
 - PHP 7.3.17
 - MySQL 8.0.19

**Comment by SPB105438** [comment]
Been an issue since 2014 see ticket #1611

Many post advise to change the code to "SET SQL_MODE = "";"

**Comment by danielkerr** [comment]
DELETE THE LINE. im using php8 and it works for me.

**Comment by danielkerr** [comment]
it already has been removed!

**Comment by danielkerr** [comment]
u posted in the title OpenCart 3.0.3.7 which does not have the code! sdo just posting no existing issues because you are to stupid to spot the version number. wasting my time.

**Comment by MikhailShemelin** [comment]
> u posted in the title OpenCart 3.0.3.7 which does not have the code! sdo just posting no existing issues because you are to stupid to spot the version number. wasting my time.

What exactly code do you mean? 

This code 

```
$db->query("SET @@session.sql_mode = 'MYSQL40'");
```
still exists in OpenCart 3.0.3.7 
https://github.com/opencart/opencart/blob/3.0.3.7/upload/install/model/install/install.php

and in the in the maintenance branch 
https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/install/model/install/install.php

**Comment by danielkerr** [comment]
it installed for me eitherway.

**Comment by thewhiterabbit** [comment]
> 
> 
> it installed for me eitherway.

Excuse me? Your junk code still has the erroneous line at 214.

You're the one who is too stupid to fix it for MySQL 8.

And you call others stupid? You're borderline mentally retarded.

**Comment by thewhiterabbit** [comment]
> 
> 
> Been an issue since 2014 see ticket #1611
> 
> Many post advise to change the code to "SET SQL_MODE = "";"

Yes and the owner is too stupid to know how to fix it, so the owner uses very old insecure MySQL to test against.

If you want a better solution I'll be posting my new eCommerce solution Vendx soon.

Follow me to stay informed.

**Comment by thewhiterabbit** [comment]
> 
> 
> u posted in the title OpenCart 3.0.3.7 which does not have the code! sdo just posting no existing issues because you are to stupid to spot the version number. wasting my time.

You're the one who's stupid.
