### ISSUE TITLE
On View Cart if user add product from similar product we have to refresh the site as it automatically do not add

### ISSUE THREAD

**Issue by codex-pro** [opencart/opencart#9225]
**What version of OpenCart are you reporting this for?** ---Version 3.0.2.0

**Describe the bug**
A clear and concise description of what the bug is 
What section does it affect?On View Cart if user add product from similar product we have to refresh the site as it automatically do not add -when we go to view cart and add products from footer similar product/recently bought 

**To Reproduce**
1. Go to Qualyinvesto.com
2. Click on '....' ADd to cart any product and go to view cart
3. Scroll down to '....'  add any product from similar product 
4. See error--  it doesnt autoupdate  we have to refresh it 

**Expected behavior**
A clear and concise description of what you expected to happen.  - it should be auto refresh

**Comment by condor2** [comment]
Close the issue and post on forum.
https://forum.opencart.com/
