### ISSUE TITLE
Wrong function being called in (extension/opencart/catalog/controller/total/shipping.php)

### ISSUE THREAD

**Issue by exelaguilar** [opencart/opencart#9231]
**What version of OpenCart are you reporting this for?**
4.0.0.0b (Master Branch)

**Describe the bug**

When using the shipping estimator in cart, you will get an undefined index error and it will falsely return no shipping options available. 

```
<b>Notice</b>: Undefined index: code in <b>extension/opencart/catalog/controller/total/shipping.php</b> on line <b>124</b>

<b>Notice</b>: Undefined index: code in <b>extension/opencart/catalog/controller/total/shipping.php</b> on line <b>124</b>

```
{"error":{"warning":"Warning: No Shipping options are available. Please <a href=\"http:\/\/localhost\/crafted\/index.php?route=information\/contact&amp;language=en-gb\">contact us<\/a> for assistance!"}}

**To Reproduce**

Add an item with shipping to your cart, try to use the shipping estimator. 

**Expected behavior**

It should output the correct shipping quotes. 

**Screenshots / Screen recordings**

Screenshot of error: https://i.imgur.com/3Pooxd4.png

**Server / Test environment (please complete the following information):**

PHP 7.3.3 on macOS MAMP Pro Server.

**Additional context**

Line 118 of (extension/opencart/catalog/controller/total/shipping.php)	

Replace:

`$results = $this->model_setting_extension->getExtensions('shipping');
`

With:
`$results = $this->model_setting_extension->getExtensionsByType('shipping');
`

getExtensions() only returns the extension group name and if there's multiple extensions, it'll return an array of the extension names. 

getExtensionsByType() will pull all the extensions that are classified by the name / variable being passed, in this case 'shipping'.

Screenshot of it working correctly with change: https://i.imgur.com/qWWMEdA.png

**Comment by TheCartpenter** [comment]
A pull request should be created for this change.
