### ISSUE TITLE
Undefined index: limit in extension/opencart/catalog/controller/module/featured.php

### ISSUE THREAD

**Issue by exelaguilar** [opencart/opencart#9232]
**What version of OpenCart are you reporting this for?**

4.0.0.0b (Master Branch)

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

The featured module does not work other than the default installed one.

**To Reproduce**

Create a new featured module and add it to any page, you will get the following error:

`Notice: Undefined index: limits in extension/opencart/catalog/controller/module/featured.php on line 25
`

**Additional context**

To fix..

**extension/opencart/admin/controller/module/featured.php**

Before:

	_if (isset($this->error['width'])) {_

Add:

		_if (isset($this->request->post['limit'])) {
			$data['limit'] = $this->request->post['limit'];
		} elseif (isset($module_info['limit'])) {
			$data['limit'] = $module_info['limit'];
		} else {
			$data['limit'] = 4;
		}_

**extension/opencart/admin/view/template/module/featured.twig**

Before:

```
<div class="form-group row">
            <label for="input-axis" class="col-sm-2 col-form-label">{{ entry_axis }}</label>
```

Add:

```
          <div class="form-group row">
						<label for="input-limit" class="col-sm-2 col-form-label">{{ entry_limit }}</label>
						<div class="col-sm-10">
							<input type="text" name="limit" value="{{ limit }}" placeholder="{{ entry_limit }}" id="input-limit" class="form-control"/>
						</div>
					</div>
```

**extension/opencart/admin/language/en-gb/module/featured.php**

Before:

`$_['entry_axis']       = 'Axis';`

Add:

`$_['entry_limit']      = 'Limit';`

**Comment by danielkerr** [comment]
removed limit

**Comment by jacobcovenas** [comment]
thanks,
i reisntall 3.xxx
y work the feature
