### ISSUE TITLE
MySQL 8 : Incorrect DATE value: '0000-00-00'

### ISSUE THREAD

**Issue by SilverFoxA** [opencart/opencart#9236]
**What version of OpenCart are you reporting this for?**
OC 3.0.3.7

**Describe the bug**

The homepage and all product listing pages.

**To Reproduce**
1. Download OC 3.0.3.7 from GitHub Opencart repo releases section
2. Setup on Ubuntu running mysql 8
3. Go to the website

`"PHP message: PHP Fatal error:  Uncaught Exception: Error: Incorrect DATE value: '0000-00-00' ....`

**Expected behavior**
List the products

**Screenshots / Screen recordings**
![Screenshot_3](https://user-images.githubusercontent.com/6983070/107120957-c21d4700-68b5-11eb-9126-fb42ec1251b1.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? - Development server
 - Operating system - Ubuntu
 - PHP version - (php-fpm 7.4)
 - Apache version - (Nginx 1.18)
 - Browser(s) tested with [e.g. chrome, safari - if applicable] - Chrome

**Comment by TheCartpenter** [comment]
See this solution: https://forum.opencart.com/viewtopic.php?f=206&t=222399#p813284 .

**Comment by danielkerr** [comment]
any specific reason im using MySQL 8 and have no issues!

**Comment by TheCartpenter** [comment]
> any specific reason im using MySQL 8 and have no issues!

Simple. All followed aspects shows that:

1 - You are using a database server library version that is not yet mandatory by the Industry
2 - You are enforcing / expecting users to use mySQL v8+ whereas other platforms do not yet insist on doing so from a simple incremented sub-version rather than a complete OC version from v3.x to v4.x releases.

3 - Server packaging may not provide such capabilities to, yet, upgrade to that version to the users as opposed to what your server may already provided specifically.

4 - There are no documented processes where users should understand that this MySQL server library shall be mandatory by Opencart as opposed to other platforms since its distribution date on opencart.com website.

Result: Multiple topics on the forum do report failed upgrades due to MySQLi DB library in Opencart. By reverting to the previous library DB version of its distribution, users are then able to upgrade as shown from this post: https://forum.opencart.com/viewtopic.php?f=206&t=222399#p813328 as the solution delivered from this post as well: https://forum.opencart.com/viewtopic.php?f=206&t=222399#p813349 .

WTG!

**Comment by mhcwebdesign** [comment]
This subject has been brought up multiple times. Just remove the NO_ZERO_DATE from the sql_mode, see https://github.com/opencart/opencart/issues/9075#issuecomment-774502931

**Comment by TheCartpenter** [comment]
> This subject has been brought up multiple times. Just remove the NO_ZERO_DATE from the sql_mode, see [#9075 (comment)](https://github.com/opencart/opencart/issues/9075#issuecomment-774502931)

And, yet, that switch case is still there.

**Comment by haxcop** [comment]
Same issue here, besides many other related, easy to solve but very sad this has come out in a release

**Comment by danielkerr** [comment]
I have found the issue when trying to upgrade not install!

**Comment by prabhatkumaroc082** [comment]
go to system/library/db/mysqli.php
find 
`$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'");
`replace 
`$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION'");
`
or simply use this file https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/library/db/mysqli.php

**Comment by prabhatkumaroc082** [comment]
Also, if anyone is facing the following issue 
**Uncaught Exception: Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'**

then use this file for now https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/install/model/install/install.php

**Comment by thewhiterabbit** [comment]
> 
> 
> any specific reason im using MySQL 8 and have no issues!

Strict mode off. You idiot. I hope you lose at gambling, loser.

Strict mode on is production level security. If @danielkerr had one single brain cell he would stop being rude to people that are trying to setup legitimate production installs and fix his junk code.

You know, @danielkerr, it's possible to write correct code that handles strict mode on. It's not too hard for average level programmers. You must be lazy, or not smart enough to figure that out.

Go gamble on the races some more. I hope you lose it all. Every penny.

**Comment by thewhiterabbit** [comment]
> 
> 
> Same issue here, besides many other related, easy to solve but very sad this has come out in a release

Yeah this repo owner is incapable of releasing proper code. He's too busy betting on animals at the racetrack.

**Comment by WebkulOpencart** [comment]
@thewhiterabbit We are checking the same and will fix this issue ASAP.
Also, you have already raised a new issue so we will revert on the same.
[https://github.com/opencart/opencart/issues/9380](https://github.com/opencart/opencart/issues/9380)

**Comment by norKI79** [comment]
replacing the mysqli.php file still doesn't fix the problem...is it possible to just comment out this line?

**Comment by IP-CAM** [comment]
Famous MaxD, the genious OpenShop 1.5.6.x Extension Creator, seems to be back i action, and now created an updated Version OC v.3.0.3.7, working from PHP v.5.4 up to PHP v.8, just to have it mentioned:
https://opencart.download/

**Comment by stifler97** [comment]
> go to system/library/db/mysqli.php find `$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION'"); ` replace
> 
> `$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION'"); ` or simply use this file https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/library/db/mysqli.php

thanks. its working and solved my problem
