### ISSUE TITLE
Is this bug or ment to be?

### ISSUE THREAD

**Issue by mrlee14** [opencart/opencart#9238]
version 3.0.3.7

inside opencart.sql there is strange triple apostroph use, is this bug: 

(3506, 221, 'Abu Dhabi', 'ADH', 1),
(3507, 221, '''Ajman', 'AJ', 1),  <----------- here 
(3508, 221, 'Al Fujayrah', 'FU', 1),

**Comment by condor2** [comment]
(3506, 221, 'Abū Z̧aby', 'ADH', 1),
(3507, 221, '‘Ajmān', 'AJ', 1),
(3508, 221, 'Al Fujayrah', 'FU', 1),
(3509, 221, 'Ash Shāriqah', 'SH', 1),
(3510, 221, 'Dubai', 'DU', 1),
(3511, 221, 'Ra’s al Khaymah', 'RK', 1),
(3512, 221, 'Umm al Qaywayn', 'UQ', 1),

**Comment by danielkerr** [comment]
no
