### ISSUE TITLE
Language folder is deleted

### ISSUE THREAD

**Issue by amaco596** [opencart/opencart#9247]
**What version of OpenCart are you reporting this for?**
3.0.3.7

**Describe the bug**
The language folder is deleted.

**To Reproduce**
1. Install an extension. The extension has translations for a language not yet installed.
2. Install a new language through 'Extensions >> Installer'. The same language as a translation in the previously installed extension.
3. Uninstall the previously installed extension.
4. The language folder for the newly installed language is deleted (not only the language files for that extension, but the entire language folder), even though the new language is not uninstalled and you can find it listed in both 'Extensions >> Installer' and 'System >> Localisation >> Languages' (if the language was added there).

**Expected behavior**
When you uninstall an extension, only the extension files should be deleted. I suppose, in a production site it is very common to install an extension, then a new language later on, and then uninstall that extension again.

**Comment by Webkul-Opencart** [comment]
@amaco596 Hello, can you please share the video or screenshots as I am not able to find this issue?

**Comment by amaco596** [comment]
See the attached PDF file!

[Report_language.pdf](https://github.com/opencart/opencart/files/5957701/Report_language.pdf)

**Comment by amaco596** [comment]
Note that I install the language through 'Extensions >> Installer'.

**Comment by condor2** [comment]
Isn't a bug. It is normally by deleting ocmod from history to remove files from directory.

**Comment by amaco596** [comment]
I agree that the extension files should be deleted when you uninstall an extension, but not the entire language folder. Many other extensions can use that language.
 
Moreover the new language is not uninstalled and it is still listed in 'Extensions >> Installer', but the language folder is gone. Why should the entire language folder be deleted when you uninstall an extension? Isn't that a bug?

**Comment by condor2** [comment]
Because entire language was made as ocmod extension...

**Comment by amaco596** [comment]
I understand, but the extension didn't create the entire language folder. Only files created by the extension should be deleted when you uninstall the extension. Why on earth should the entire language folder be deleted?

Besides, the recommended method to install a new language is through 'Extensions >> Installer'.

See: [Adding multiple languages](http://docs.opencart.com/en-gb/administration/language/) in OpenCart documentation.

**Comment by amaco596** [comment]
People can of course upload the language files manually, but that's not the point. The point is that the entire language folder is deleted when you uninstall an extension. I mean that's a bug.

**Comment by condor2** [comment]
In **romanian3.0.0.0-3.0.3.7.ocmod.zip** you don't have any language files?

Installing languages using ocmod installer in 3.0.x is useless because you need to add them manually in System->Localisation->Languages.
In 3.0 ocmod installer you can't run a sql or installer.php without this extension
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31227

**Comment by amaco596** [comment]
Of course you have language files in the ocmod for that language. But why should those files be deleted when I uninstall another extension? When you uninstall any extension or language, the files created by that extension or language should be deleted, not other files.

When I uninstall an extension, extension files should be deleted. When I uninstall a language, the language files should be deleted. They should not delete each other files. That's my point.

Is it so difficult to understand?

**Comment by condor2** [comment]
I have tested myself and I don't see this issue.

I have created a **test.ocmod.zip** with a file in admin/language/ro-ro/catalog then I have installed
I have installed a romanian language pack using ocmod, then uninstalled (deleted from history) **test.ocmod.zip** and the files for language are still there. 

Tested and vice versa and no issue. 
You have tested by browsing partition D where your site is. Maybe is a cache issue with Filezilla.

**Comment by amaco596** [comment]
I have tested with another extension. My test server is online, not on partition D. The local files are on partition D, but the remote files are online. This is a fresh new installation of OC 3.0.3.7.

I have attached another PDF file with the results of tests. It can't be a cache issue with FileZilla since the online site is affected as well, not only what I see in FileZilla.

[Report_language2.pdf](https://github.com/opencart/opencart/files/5959125/Report_language2.pdf)

**Comment by amaco596** [comment]
I am not sure why you didn't see the issue, but if it helps I can send you the extension and language package I have tested with. So you can test it on a fresh new installation of OC 3.0.3.7. If you send me your e-mail address, I can send them to you.

**Comment by amaco596** [comment]
I think I figured out why this happens.

When I install an extension, there will be added rows to the table 'extension_path', among other 'admin/language/ro-ro' and 'catalog/language/ro-ro' for Romanian language.

When I install Romanian language it will also be added rows like 'admin/language/ro-ro/catalog', 'admin/language/ro-ro/common', 'admin/language/ro-ro/customer' and so on.

When I uninstall the extension, the function uninstall in 'admin/controller/marketplace/install.php' will retrieve extension paths for that extension in line 435:

$results = $this->model_setting_extension->getExtensionPathsByExtensionInstallId($extension_install_id);

So the paths 'admin/language/ro-ro' and 'catalog/language/ro-ro' will be retrieved from database.

After that, in the foreach loop, the files and folders for that extension will be deleted.

If the folders 'admin/language/ro-ro' and 'catalog/language/ro-ro' are deleted, I suppose the entire folder with its subfolders and files are deleted as well. So, no wonder that the entire language folder is deleted when I delete an extension.

**Comment by mhcwebdesign** [comment]
Yeah, the admin/controller/marketplace/install.php looks a bit weird. The culprit might be in line 503:

`$this->model_setting_extension->deleteExtensionPath($result['extension_path_id']);`

The DB table oc_extension_path looks OK to me, it stores all the file paths and folders of an extension, and the uninstall function should remove files and/or folder belonging to a particular extension_install_id.

**Comment by amaco596** [comment]
@mhcwebdesign I agree with you that the uninstall function should only remove files and folders belonging to a particular extension. But folders 'admin/language/ro-ro' and 'catalog/language/ro-ro' belong to the extension I want to uninstall. Would't the uninstall function delete those folders as well, and therefore the entire language folders?

Is there a check to see whether those folders belong to other extensions as well? Because after I install a language there will be entries like 'admin/language/ro-ro/catalog', 'admin/language/ro-ro/common', 'admin/language/ro-ro/customer' and so on, belonging to the new language in 'oc_extension_path' table.

If 'admin/language/ro-ro' and 'catalog/language/ro-ro' folders belonging to the extension I want to uninstall, will be deleted, wouldn't folders 'admin/language/ro-ro/catalog', 'admin/language/ro-ro/common', 'admin/language/ro-ro/customer' and so on, be deleted as well?

**Comment by trueliarx** [comment]
I reproduced the problem.
It's quite severe since it's not related to the "language" files/folders only but to any newly created folder that happens to be shared/used with another extension.
Practically the initial extension, if removed, corrupts any other extension that uses the same parent folder.

The marketplace/modification before deleting a folder it's necessary that checks if other extensions are using it or if there are files.
-----
I just played a bit and made a potential workaround in SQL but it's not a solution (not for production) since folders and files  needs to be checked (ex. unmatched paths, wrong separator on windows, etc). I've serious doubts about my query even if it seems to work.



admin/model/setting/extension.php 
Line 73

`// $query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "extension_path` WHERE `extension_install_id` = '" . (int)$extension_install_id . "' ORDER BY `date_added` ASC");`


`		$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "extension_path` c WHERE `extension_install_id` = '" . (int)$extension_install_id . "' and  NOT EXISTS
											(SELECT path  FROM `" . DB_PREFIX . "extension_path` WHERE path LIKE CONCAT(c.path, '%') AND `extension_install_id` != '" . (int)$extension_install_id . "' )
											ORDER BY `date_added` ASC");`

**Comment by amaco596** [comment]
Does anybody work on this issue?

**Comment by webkul-dilip** [comment]
> I have tested with another extension. My test server is online, not on partition D. The local files are on partition D, but the remote files are online. This is a fresh new installation of OC 3.0.3.7.
> 
> I have attached another PDF file with the results of tests. It can't be a cache issue with FileZilla since the online site is affected as well, not only what I see in FileZilla.
> 
> [Report_language2.pdf](https://github.com/opencart/opencart/files/5959125/Report_language2.pdf)

We are checking with the same process for the dutch language but we did not found the issue. Maybe we missed something, Could you please send us both zip files that you mentioned the Report_language2-1.pdf file?

**Comment by amaco596** [comment]
Yes, I can send you the zip files. What's your email address?

**Comment by amaco596** [comment]
To reproduce the issue, make sure you have a fresh installation of OC 3.0.3.7.

1. Install an extension that has a translation for a language not yet installed. You will see that there will be added rows to the table 'oc_extension_path', among other 'admin/language/ro-ro' and 'catalog/language/ro-ro' for Romanian language, belonging to this extension.

2. Install a new language through 'Extensions >> Installer'. If the extension installed in step 1 has translations for Romanian language, install Romanian language.

3. Uninstall the extension installed in step 1.

4. Since 'admin/language/ro-ro' and 'catalog/language/ro-ro' belong to extension installed in step 1, these folders will be deleted.

The issue only happens if you install first an extension, then a language, and you delete the extension after installing the language. If you install the language first there will be no issue, since 'admin/language/ro-ro' and 'catalog/language/ro-ro' will belong to the language (Romanian language in this case).

**Comment by webkul-dilip** [comment]
> Yes, I can send you the zip files. What's your email address?

Can you upload the zip here?

**Comment by amaco596** [comment]
I don't want to upload the zip files here. However, I think I explained quite well in my last post, so you should be able to reproduce the issue.

**Comment by trueliarx** [comment]
> We are checking with the same process for the dutch language but we did not found the issue. Maybe we missed something, Could you please send us both zip files that you mentioned the Report_language2-1.pdf file?

There's no need of sample extensions (available below) since the problem can be easily verified by checking the source code ( admin/controller/marketplace/install.php ) where the files are indiscriminately removed if the First extension adds, during the installation, a new folder (line 211), as probably could happens more often for the language folders.

If the "source" filepath is a folder (line 463 - if (is_dir($source))  )
there's a scandir (line 473) and all the files inside the folder are added to $files[] (and added to $path[] if it's a subfolder Line 477) for deletion (line 494 - 498).

The problem doesn't show if the uninstalled extensions have not created a new folder during their installation.

It's not strictly related to the "languages".
--------

Sample dummy ocmod - > https://filebin.net/by50yjhijmrh8t11
- Install test.ocmod.zip and then test2.ocmod.zip
- Uninstall test.ocmod.zip 

All files of the (2nd extension) are gone even if the first ocmod have just one file "upload/catalog/language/ar-ms/dummy.php".

**Comment by webkul-dilip** [comment]
@trueliarx We have fixed the issue, here is pull request please check https://github.com/opencart/opencart/pull/9416 .
Thank you for share the test ocmod.
