### ISSUE TITLE
Wrong Product Quantities, Randomly Changing, sometimes Subtracting, sometimes not

### ISSUE THREAD

**Issue by Zhoha28** [opencart/opencart#9248]
Opencart version - 3.0.3.2

I have issues with my quantities. As they seem to be acting erratically.

Sometimes when I sell an item, the quantity isn't subtracted. Even though Product: Subtract quantity is set to yes (for all products), and the Settings: 
Subtract stock when the status is Processing. However, sometimes the stock quantity is subtracted, and sometimes it isn't. What is the reason for this?

Also, sometimes the quantities just randomly change. For example, a product may go from having quantity 5 to quantity 6 or go from having quantity 3 to having quantity 2. Some of my products are of limited quantities, and thus it is causing a problem for the store
Please help me resolve this, as I re-installed OC 3 times, and still am facing this issue.

**Comment by mhcwebdesign** [comment]
No one else can reproduce your error, doesn't appear to be an Opencart bug. Please re-post on the OpenCart forum, with some more details on the exact steps on how to reproduce the error, error log details, web theme used etc.
