### ISSUE TITLE
Wrong version in OC 3.0.3.7 release

### ISSUE THREAD

**Issue by antoniofacciutiIYL** [opencart/opencart#9249]
In upload/admin/index.php and upload/index.php is defined "VERSION" variable with "3.0.3.8" value instead of "3.0.3.7"

**Comment by mhcwebdesign** [comment]
OC 3.0.3.7 does indeed have a wrong version variable, but it's at 3.0.3.6, not 3.0.3.8.
The 3.0.0.x_Maintenance is at 3.0.3.8 which is correct for the next planned release in the 3.0.3.x series.
