### ISSUE TITLE
Getting error in install and upgrade

### ISSUE THREAD

**Issue by jameswill** [opencart/opencart#9251]
**What version of OpenCart are you reporting this for?**
3.0.3.7

**Describe the bug**
**1) On Installing a fresh copy with PHP 7.3 and MySQL 8.0**
Post installation on visiting front page throws following error

_Fatal error: Uncaught Exception: Error: Incorrect DATE value: '0000-00-00'<br />Error No: 1525<br />SELECT DISTINCT *, pd.name AS name, p.image, m.name AS manufacturer, (SELECT price FROM ocik_product_discount pd2 WHERE pd2.product_id = p.product_id AND pd2.customer_group_id = '1' AND pd2.quantity = '1' AND ((pd2.date_start = '0000-00-00' OR pd2.date_start < NOW()) AND (pd2.date_end = '0000-00-00' OR pd2.date_end > NOW())) ORDER BY pd2.priority ASC, pd2.price ASC LIMIT 1) AS discount, (SELECT price FROM ocik_product_special ps WHERE ps.product_id = p.product_id AND ps.customer_group_id = '1' AND ((ps.date_start = '0000-00-00' OR ps.date_start < NOW()) AND (ps.date_end = '0000-00-00' OR ps.date_end > NOW())) ORDER BY ps.priority ASC, ps.price ASC LIMIT 1) AS special, (SELECT points FROM ocik_product_reward pr WHERE pr.product_id = p.product_id AND pr.customer_group_id = '1') AS reward, (SELECT ss.name FROM ocik_stock_status ss WHERE ss.stock_status_id = p.stock_status_id AND ss.language_id = '1') AS stock_status, (SELECT w in [[PATH]]\system\library\db\mysqli.php on line 41_

**2) On Upgrading from 3.0.3.6 version**
On visiting http://domain.com/[[DIR]]/install/index.php throws following error.

_Warning: fopen(/[[PATH]]/system/storage/logs/error.log): failed to open stream: No such file or directory in [[PATH]]/system/library/log.php on line 22_

I have placed system/storage directory outside the web accessible directory. To remove this error I tried moving my storage directory to [[PATH_TO_INSTALL]]/system/storage and then visiting http://domain.com/[[DIR]]/install/index.php gives following error.

_Error Code(0): Error: Incorrect datetime value: '0000-00-00 00:00:00' for column 'date_added' at row 1
Error No: 1292
ALTER TABLE `ocgu_api` CHANGE `date_added` `date_added` DATETIME NOT NULL AFTER `status` in [[PATH]]/system/library/db/mysqli.php on line 41_

**PS: I am trying upgrade on my another server with PHP7.3 and MYSQL 5.5**

However I tried [https://forum.opencart.com/viewtopic.php?f=206&t=222399#p813284](url) this solution and it worked. Is there is some problem with the new mysqli.php ?

**Expected behavior**
Install and Upgrade should work seamlessly.

**Comment by mhcwebdesign** [comment]
There is no need to repeatedly post the same question here or in the OC forum. See e.g. https://github.com/opencart/opencart/issues/9236#issuecomment-774671280 or https://github.com/opencart/opencart/issues/9075#issuecomment-774502931

**Comment by danielkerr** [comment]
already reported
