### ISSUE TITLE
Opencart 3.0.3.7 Still, Edit Order when Custom field required, Throws error "Field Required" 

### ISSUE THREAD

**Issue by AVSthe** [opencart/opencart#9253]
I am Using Opencart 3.0.3.7

**Describe the bug**
I have custom field called "Mobile number " enabled. After receiving Order, When I need to edit the order status, it throws erro with "mobile number required" even though it has value.

**To Reproduce**
1. Go to Customers ---> Custom Fields' and create Custom Field.
2. Place some test orders  with  custom field  filled in...
3. In Admin Order section, click on Edit order 
4. See error "Field Required"
5.  It does not move on to next section in Edit order. It gets locked in the first page itself  with the error even yjough the field has a value.

**Expected behavior**
Due to this error one cannot change Order status in Admin. It seems this Bug exist for a long time and new version of Opencart is being released many times but this bug  still persists. It is serious flaw in the behavior of custom field that disallows Admin to edit Order.

Screenshot:
I have attached screenshot for your kind reference

I tested on my Shared hosting 
cPanel, L.L.C. 86.0.36
PHP 7.3 (ea-php73)
Apache ; No info with me
Definitely it is not related to PHP version or any other things on server. Independent on these, it never works.

Please Note: I have tried all fixes mention in Opencart forum by fixing Shipping.php and  other PHP that was mentioned in forum and downloaded that fix from Github itself. But unfortunately, nothing works. Hence reverted the files to original ones.
![Error_orderEdit](https://user-images.githubusercontent.com/33345282/107634717-fdda5700-6c8f-11eb-83a5-a1b66af11550.jpg)

The issue has already been raised by someone long time ago,  but still there is no reliable fix done.
Please fix it at the earliest. 
Thanks
AVSThe

**Comment by AVSthe** [comment]
I fixed it myself by the help of this Link:
 below:
https://github.com/opencart/opencart/tree/2782782c6e609c934cc665e6cd48487385fccb95/upload/catalog/controller/api

Replaced customer.php, shipping.php and payment.php resolved the issue. Earlier I tried the same thing in 3.0.3.6
but it did not work. after 3.0.3.7 suddenly replacing the above files, resolved the issue.
But I am wondering why this fix is not done in opencart 3.0.3.7 by default?  Why people have to search for these errors find fixes after much hardship? 
Please do something about this issue.
Thanks

**Comment by TheCartpenter** [comment]
That's why I keep providing the feedback on the forum that most of the reported issues have already been fixed on the master branch.

**Comment by prabhatkumaroc082** [comment]
fix #9358

**Comment by narcico** [comment]
Hi @TheCartpenter and @prabhatkumaroc082 ,
I implemented the fix you pointed us to, and I didn't have the error for the custom fields, but I cannot save customer record as the form says that there are errors on the form, but no error is highlighted (all mandatory fields are filled in).
Any idea why I got his?

**Comment by danijelGombac** [comment]
@narcico Is used customer_group_id checked (config_customer_group_display) in settings?

**Comment by narcico** [comment]
Hi, yes, the custom fields have the Default customer group checked, I've removed the REGEX from the custom fields and the upright error does not display anymore, but I still get the "check your form" error in red.

**Comment by narcico** [comment]
Hi, I think I've fixed it.... one of the custom field (mobile number) was for the address, I moved it to the account and now I can save the form.
Thank you!

**Comment by prabhatkumaroc082** [comment]
> Hi @TheCartpenter and @prabhatkumaroc082 ,
> I implemented the fix you pointed us to, and I didn't have the error for the custom fields, but I cannot save customer record as the form says that there are errors on the form, and I spotted this error on the page:
> 
> Notice: Undefined index: custom_field in /var/www/html/shop/admin/controller/customer/customer.php on line 1053
> Notice: Trying to access array offset on value of type null in /var/www/html/shop/admin/controller/customer/customer.php on line 1053
> 
> Any idea why I got his?

I didn't find any issue on the admin customer page. did you apply any modification? try on fresh Opencart

**Comment by prabhatkumaroc082** [comment]
Ahh, yes, some issue is there on the admin customer page.
custom fields are not listing on new addresses, if you check on the existing addresses then it is OK. I am still checking it, and add a new commit.

**Comment by prabhatkumaroc082** [comment]
The upper reported issue must be related to regex validation. 
I found another issue on the front-end and opened another PR https://github.com/opencart/opencart/pull/9464

**Comment by AVSthe** [comment]
Though I have commented on Feb 12 that I have fixed the issue by replacing those PHP files, It is unreliable fix and while using it for a while, Still bug exists with regex and validation of custom field. Many people might try to add Telephone filed in custom field  for new shipping address and validate. There is a difference adding custom field to account and address section. When adding custom field as Mobile number or Telephone number in Address section, the trouble arises and bug not fully fixed. 
I request experts to fix this soon.

**Comment by Webkul-Opencart** [comment]
@AVSthe Please do share the scenario or any screenshot for the same.

**Comment by AVSthe** [comment]
> @AVSthe Please do share the scenario or any screenshot for the same.

I have installed new version 3.0.3.7 freshly and added custom field as Mobile number in Address. Previously it was in account section and that seems to work when replacing the fixed customer.php, payment.php, shipping.php, earlier. But when custom field is assigned to address section, it throws error without any other details. The error occurs as popup without any details. Cannot go beyond the first page while editing. If if restore original php files, then I get "mobile number required" even though it has value.
Those 3 files I downloaded from Github sometime ago when I was using 3.0.3.6. Any other fixed php files available already. If not then it is 100% conformed that Opencart 3.0.3.7 has serious Bug with Custom field which needs to fixed. Kindly see the screen shot. Please do the needful. Thanks
![mobile required2](https://user-images.githubusercontent.com/33345282/125789341-21cd88e9-62f8-4318-82be-7b386f28383d.jpeg)

**Comment by Webkul-Opencart** [comment]
@AVSthe Hello, This issue has been already resolved, you can take the code from the following branch & re-verify it at your end--
https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance

**Comment by AVSthe** [comment]
> @AVSthe Hello, This issue has been already resolved, you can take the code from the following branch & re-verify it at your end--
> https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance

It works. Thanks. I tested  by Installing Opencart 3.0.3.7 from Original Opencart Downloded files first and then overwrote the files with this downloaded Github fixed maintenance packaged files.  Now it works. But my query is, after downloading the ZIP file from maintenance branch files, is it correct to overwrite entire the original installation files? OR to overwrite only specific files? if only specific files to replace means, what are the files I have to select from the maintenance branch zipped one to replace in the original installation directory? Awaiting your reply, Thanks

**Comment by AVSthe** [comment]
Hi thanks It works now.I have commented in Github with certain queries. Please do clarify On 15-Jul-2021 2:59 pm, Vrinda Sharma ***@***.***> wrote:
@AVSthe Please do share the scenario or any screenshot for the same.
