### ISSUE TITLE
ParseError:  syntax error, unexpected '$lines' (T_VARIABLE) in upgrade_1001.php

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9258]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

ParseError:  syntax error, unexpected '$lines' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST) in /upload/install/model/upgrade/upgrade_1001.php on line 141

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by TheCartpenter** [comment]
Yes, of course. That's because that file must of had been fully tested before it was provided. See if this commit fixes the issue: https://github.com/opencart/opencart/pull/9260/commits/8ff0b309ace4b876dce7de6d3c59a22f95caa07d .

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/issues/8970
