### ISSUE TITLE
Exception:  Error: Unknown column 'extension' in 'field list'

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9259]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Exception:  Error: Unknown column 'extension' in 'field list'<br />Error No: 1054<br />SELECT DISTINCT `extension` FROM `oc_extension` in /upload/system/library/db/mysqli.php on line 48

When you run an update from older versions of opencart, you may see the error.
This is a problem with opencart's database update.

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by TheCartpenter** [comment]
Do you see that field created in your oc_extension table in PHPMyAdmin?

**Comment by cgcmart** [comment]
upgrade did not add "extension" field after "extension_id".
I installed a demo site to test master version, then change its database to old version DB and run upgrade, that failed and stopped at "oc_coupon" with multiple sql errors.

**Comment by TheCartpenter** [comment]
Confirmed for the extension field. See this commit noticing if this will now solved the issue with the upgrade: https://github.com/opencart/opencart/pull/9262/commits/412e1eb93b451eecf8786a4c54f1e884b5eeb86e . As for reverting back to old database and seeing more errors, please post ALL the errors.

**Comment by cgcmart** [comment]
Error Code(0): Error: Incorrect date value: '0000-00-00' for column `oc_coupon`.`date_start` at row 1
Error No: 1292
ALTER TABLE `oc_coupon` MODIFY `date_start` date NOT NULL AFTER `total` in /system/library/db/mysqli.php on line 48

**Comment by TheCartpenter** [comment]
Already reported here: https://github.com/opencart/opencart/issues/9236 . See the solution.

**Comment by cgcmart** [comment]
@TheCartpenter Thanks, following the solution, upgrade successfully.
But loader has a problem displayed.
Error: Call to undefined function Exception() in /system/engine/loader.php on line 111

**Comment by TheCartpenter** [comment]
Then, you're not using the latest updates of the master branch: https://github.com/opencart/opencart/commit/6ead8529b49b0b0675d4f059f27cdf036d1f59f6 .

**Comment by cgcmart** [comment]
I did use the latest update master branch.
upload/install/model/upgrade/upgrade_1009.php was deleted.

**Comment by TheCartpenter** [comment]
You might be using the latest update but might simply have re-uploaded the files without removing the old ones if you're now noticing that files have been removed.

**Comment by cgcmart** [comment]
no, remove all the old files, 9 existing files are updated in /install/model/upgrade/

**Comment by cgcmart** [comment]
I believe upgrade is impossible because extension issue. Old versions have more extensions and modules, upgrade keeps data for them from old version, but they are unable to load by loader because there are not update files for those extensions and modules.
Upgrade is a problem and headache for both opencart users and developers as opencart is shorting deploy function or deployment middleware.

**Comment by TheCartpenter** [comment]
> no, remove all the old files, 9 existing files are updated in /install/model/upgrade/

What 9 missing files?

**Comment by TheCartpenter** [comment]
Is the exception messages showing since the fix was provided and integrated?

**Comment by cgcmart** [comment]
No, it's before. But I fixed it by manually adding the field "extension" to table "oc_extension" through phymyadmin, before your pull #9262.

**Comment by TheCartpenter** [comment]
I fixed the 9262. A method was missing in the database query. As for the Exception error, if you already patched the provided Exception commit and the error keeps on-going, then this issue needs to be investigated.

What is on line 111 of system/engine/loader.php file on your end?

**Comment by cgcmart** [comment]
It's the same as the master branch original, **public function model($route)** :
`throw \Exception('Error: Could not load model ' . $class . '!');`

**Comment by TheCartpenter** [comment]
Which PHP version are you using?

**Comment by cgcmart** [comment]
PHP 7.3.6

**Comment by TheCartpenter** [comment]
Does the same occurs on a fresh installation regarding the Exception error you're experiencing?

**Comment by cgcmart** [comment]
No, only occurred on upgrade from the previous version of database that does not have column "extension" in the table "oc_extension".

**Comment by TheCartpenter** [comment]
With the latest fix of yesterday I provided yesterday to add the extension field with the upgrade, this issue should now be solved.
