### ISSUE TITLE
first products are not shown in assigned categories, but second product is showing. but count shown as 2 products in this category. 

### ISSUE THREAD

**Issue by ramsmart-inno** [opencart/opencart#9263]
<img width="829" alt="Screenshot 2021-02-14 at 10 01 22 AM" src="https://user-images.githubusercontent.com/72604311/107868600-a44e7400-6eab-11eb-816b-ed3992f976c5.png">

Could someone can help with this issue to move forward.

I am using the 3.0.3.1 version opencart. Thanks in advance.

**Comment by TheCartpenter** [comment]
Forum request.

**Comment by ramsmart-inno** [comment]
> Forum request.
It means?

**Comment by TheCartpenter** [comment]
It's pretty straightforward. It simply means that this commit must be posted on the Opencart forum rather than here as this commit is another closed subject.
