### ISSUE TITLE
Indent changes

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#9275]
Please decide on the settings in editorconfig and update all files so that you do not create a separate PR for each file

**Comment by ADDCreative** [comment]
The .editorconfig is wrong and does not match the published coding standards. See: https://github.com/opencart/opencart/pull/9280

Always going to have issues due to the mixed indentation in the .twig files.

**Comment by Hkr32** [comment]
Standards require revision and updating. Why use different styles?

**Comment by TheCartpenter** [comment]
Also including that indent of 8 instead of 2 or 4 are being found on the master branch at this time.

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart/commit/d3bccd35801675dc6dbd4f20a0805b915b63923a

**Comment by danielkerr** [comment]
sorry my ide messed up.

**Comment by danielkerr** [comment]
its only only with twig and js it has issues.

**Comment by Hkr32** [comment]
You must use either spaces or tabs in the entire project

**Comment by danielkerr** [comment]
my ide is fixed again. i think all pages should be coherent.
