### ISSUE TITLE
P and STRONG HTML objects in twig files with Bootstrap

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#9297]
I understand this issue may have been covered in the past but would there be anyone objecting on the fact that bold statement from P and STRONG or B (bold) should both be replaced with: ```<p class="font-weight-bold">Bold text.</p>``` as per: https://getbootstrap.com/docs/4.0/utilities/text/ (or perhaps and more up-to-date way since Bootstrap has been updated on the master branch in anyhow) whenever it's not about a TD row from an HTML Table?

**Comment by danielkerr** [comment]
There is no new up-to-date way. U are making stuff up and wasting my time

**Comment by TheCartpenter** [comment]
Have it your way. If you look in other repositories with HTML5 and BootStrap 5+, this is already in the works. However, if you mean there are no up-to-date way 'in Opencart' this will be done at this time, then the issue is not with Bootstrap on that end.
