### ISSUE TITLE
Add cost price field

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#9298]
Maybe add a cost field? I think others could use it when working with a store...

**Comment by TheCartpenter** [comment]
OC version? Where do you mean? More information is needed.

**Comment by Hkr32** [comment]
https://en.wikipedia.org/wiki/Cost_price

**Comment by chulcha** [comment]
@TheCartpenter see early versions  (1.x) This field was

**Comment by TheCartpenter** [comment]
Simply create a pull request for this. There's no need nor no point to post a wikipedia URL about something that has nothing to do with the repository. As @chulcha mentioned, it may have been on older OC versions. However, it's no longer there. Github is a website for developers, not for posting theory lessons about terms that Google can already find. Therefore, since commit can now be closed.

**Comment by Hkr32** [comment]
Make another PR that nobody needs?

**Comment by chulcha** [comment]
It was suggested to add this field.
And this is a topic for discussion.
Orenсart as a CMS for stores, including an accounting system.
Considering that version 4 does not allow you to simply add such a field (events are required, and not like the previous oсmod), then I believe that such a field should be added to the assembly, or it is possible to provide for the addition of such or similar fields.

**Comment by TheCartpenter** [comment]
> Make another PR that nobody needs?
> You asked for information, I gave you a link to read what the cost price is...

That is of course your point of view but all repositories on Github uses Pull Requests to suggest code changes and this issue you're addressing about is about code change.

**Comment by TheCartpenter** [comment]
> It was suggested to add this field.
> And this is a topic for discussion.
> Orenсart as a CMS for stores, including an accounting system.
> Considering that version 4 does not allow you to simply add such a field (events are required, and not like the previous oсmod), then I believe that such a field should be added to the assembly, or it is possible to provide for the addition of such or similar fields.

Nowhere to be said that it wasn't suggested to re-add the field but I did mentioned that a pull request can be created to suggest the change since the OP is suggesting for this field to be re-added in the core.

**Comment by Hkr32** [comment]
@TheCartpenter,  if you have a lot of free time and you are ready to make requests that will not be accepted later, do it!

**Comment by stalker780** [comment]
Stay calm. Events do not allow SQL modifications.
So vqmod will be required for 90% extensions :)

**Comment by chulcha** [comment]
Again.
Proposed for selection by the community, not a single person solution.
In my projects, customers are constantly asking - I want to have a purchase price. And from this price, I will build my pricing policy.
And I'm not saying that the purchase price (cost) can be in different currencies.

**Comment by TheCartpenter** [comment]
> @TheCartpenter, if you have a lot of free time and you are ready to make PRs that will not be accepted later, do it!

If you believe that your PRs won't be accepted, then there's no point for you to address the issues on this repository without trying. Otherwise, they'd be no point on posting suggestions in the PRs.

**Comment by TheCartpenter** [comment]
> Stay calm. Events do not allow SQL modifications.
> So vqmod will be required for 90% extensions :)
> 
> You cannot include all needed fields here in github.

Which is why, PRs can still be created regardless of VQMod to suggest code changes in the master branch and / or the maintenance branch.

**Comment by TheCartpenter** [comment]
> Again.
> Proposed for selection by the community, not a single person solution.
> In my projects, customers are constantly asking - I want to have a purchase price. And from this price, I will build my pricing policy.
> And I'm not saying that the purchase price (cost) can be in different currencies.

Exactly. However, these suggestions can also be put into codes since, as you said, this field was already added in the core in the past but has been removed for administrative reasons by the team.

**Comment by Hkr32** [comment]
> If you believe that your PRs won't be accepted, then there's no point for you to address the issues on this repository without trying. Otherwise, they'd be no point on posting suggestions in the PRs.

Why not? Do you think it's bad to know the need for this improvement from the community? It is necessary to sit and only make PRs in the expectation that Daniel will come down and accept him?

**Comment by Hkr32** [comment]
> removed for administrative reasons

Do you know what was removed and why?

**Comment by chulcha** [comment]
@stalker780 
See
```
	public function getDescriptions($product_id) {
		$product_description_data = [];

		$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "product_description` WHERE `product_id` = '" . (int)$product_id . "'");

		foreach ($query->rows as $result) {
			$product_description_data[$result['language_id']] = [
				'name'             => $result['name'],
				'description'      => $result['description'],
				'meta_title'       => $result['meta_title'],
				'meta_description' => $result['meta_description'],
				'meta_keyword'     => $result['meta_keyword'],
				'tag'              => $result['tag']
			];
		}

		return $product_description_data;
	}

```
Can make it easier?  YES!!! Example!
```
	public function getDescriptions($product_id) {
		$product_description_data = [];

		$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "product_description` WHERE `product_id` = '" . (int)$product_id . "'");

		foreach ($query->rows as $result) {
			$product_description_data[$result['language_id']] = $result;
			];
		}

		return $product_description_data;
	}

```
It is only example.


But such proposals are rejected. (if not, then similar)

**Comment by TheCartpenter** [comment]
> > If you believe that your PRs won't be accepted, then there's no point for you to address the issues on this repository without trying. Otherwise, they'd be no point on posting suggestions in the PRs.
> 
> Why not? Do you think it's bad to know the need for this improvement from the community? It is necessary to sit and only make PRs in the expectation that Daniel will come down and accept him?

That's pretty much it, yes. That's what he does since the beginning as proof to see the proposed results into his commits list and the same for every founders building their projects on Github.

**Comment by TheCartpenter** [comment]
- But such proposals are rejected. (if not, then similar)

Then, you already know that this proposal is not the right option to be proposed. Alternate ways might need to be suggested and, if there, the results are the same as the previous one, then you'll know from there the team is not a favor of the new suggestion either. It's quite simple on that side.

**Comment by Hkr32** [comment]
> That's pretty much it, yes. That's what he does since the beginning as proof to see the proposed results into his commits list and the same for every founders building their projects on Github.

Apparently you have nothing to do and you have a lot of free time, continue to edit the indents with your hands and you will certainly be noticed...

**Comment by Hkr32** [comment]
> this proposal is not the right option

And who can say that this is right or not? Or is anything that deviates automatically wrong? Бред)

**Comment by chulcha** [comment]
@TheCartpenter 
Personally, you can answer why the offer to use raw product_info was rejected 
`$data['products'][] = $this->load->controller('product/thumb', $product_info);`
Where sku, mpn etc?
I can not.

**Comment by TheCartpenter** [comment]
Nowhere to be said that posting a PR deviates to be automatically wrong but rather said that the only way to find out is by trying, which means, by trial and error in order to provide new or modified solutions to improve the platform. As @chulcha mentioned, Opencart is indeed a CMS which means a CMS also needs to be maintained and improved by users to make this repository a better place.

**Comment by TheCartpenter** [comment]
> @TheCartpenter
> Personally, you can answer why the offer to use raw product_info was rejected
> `$data['products'][] = $this->load->controller('product/thumb', $product_info);`
> Where sku, mpn etc?
> I can not.

Off topic. Please stay on topic and also to mention which commit you're referring about. I don't see anywhere on this incident request where exactly the product_info has been addressed about.

**Comment by chulcha** [comment]
> way to find out is by trying,

Field cost - was?
Where it now?

**Comment by TheCartpenter** [comment]
> > That's pretty much it, yes. That's what he does since the beginning as proof to see the proposed results into his commits list and the same for every founders building their projects on Github.
> 
> Apparently you have nothing to do and you have a lot of free time, continue to edit the indents with your hands and you will certainly be noticed...

That is, again, your opinion but don't act surprised if and when your commits might be closed to think like that.

**Comment by TheCartpenter** [comment]
> > way to find out is by trying,
> 
> Field cost - was?
> Where it now?

As mentioned on the above, if you believe this field should be re-added, simply create a PR about it. If the commit gets closed, then it will answer your question where this field has gone to.

**Comment by Hkr32** [comment]
@TheCartpenter, do you represent the administration?

**Comment by chulcha** [comment]
@TheCartpenter 
https://github.com/opencart/opencart/issues/9095

**Comment by TheCartpenter** [comment]
> @TheCartpenter, do you represent the administration? Maybe you speak for the whole community?

Nowhere to be said that I speak for the whole community as there is no need to represent the administration to provide support on an everyday basis. I did mentioned, however, that the OP user did proposed a field to be added whereas this field was integrated on earlier OC versions in the past.

**Comment by TheCartpenter** [comment]
> @TheCartpenter
> #9095

As you can see, this issue has been closed previously. Which means, it already answers your question.

**Comment by chulcha** [comment]
@TheCartpenter 
Did you see the answer from Danel
He closed the topic.
And the event system did not touch this topic

**Comment by TheCartpenter** [comment]
As I mentioned on my previous reply, yes, I did seen the answer from that proposed issue. It was closed and there's nothing we can do about it unless re-opened by those who have the permissions to do so on this repository.

**Comment by exelaguilar** [comment]
This can be done with the Events system and a Module.

It is a little longer process than it can be but it works. 

You'd need 4 triggers..

**Add productcost to add() function:**

Trigger: 'admin/model/catalog/product/addProduct/after'
Action: 'extension/productcost/other/productcost|add'


**Add productcost to edit() function:**

Trigger: 'admin/model/catalog/product/editProduct/after'
Action:'extension/productcost/other/productcost|edit'


**Add productcost to delete() function:**

Trigger: 'admin/model/catalog/product/deleteProduct/after'
Action: 'extension/productcost/other/productcost|delete'


**Add productcost to copy() function:**

Trigger: 'admin/model/catalog/product/copyProduct/after'
Action: 'extension/productcost/other/productcost|copy' 


Then you'd also need a controller and model for your extension/productcost/other/productcost

The controller would also have 4 functions which you are calling above.. it would look something like this:

```
	public function edit(&$route, &$data) {

		if(isset($this->request->post['product_shipping'])) {

			$this->load->model('extension/productcost/other/productcost');

			$this->model_extension_productcost_other_productcost->edit($this->request->get['product_id'], $this->request->post);
		}

	}
```

You'd, of course, have an add(), edit(), delete() and copy() function. 


These functions would be calling a model that you are making as well. Again, an example:


```
  public function edit($product_id, $data) {

    if(isset($data['product_cost'])) {
      $this->db->query("DELETE FROM " . DB_PREFIX . "product_cost WHERE product_id = '" . (int)$product_id . "'");

        $this->db->query("INSERT INTO " . DB_PREFIX . "product_cost SET product_id = '" . (int)$product_id . "', cost = '" . $this->db->escape($data['product_cost']) . "'");
    }

  }
```


Two more things you need to get this to work: 

Injecting the input into the product_form and actually add that table to the database.

The table one is easy, and typically you'll want to make a new table, not modify the existing product table. Why? It's more future proof and upgrade proof. Yes, it'll maybe be a little more work and heavy having to left join tables when you are pulling reports, etc. but it's worth it IMO so you won't have to worry about modifying core code (the whole reason vqmods / ocmod is dead in the new version).

You would simply add an install() function to your module along with where you'll be injecting your events to the database..


```
public function install() {


  $this->db->query("CREATE TABLE IF NOT EXISTS `" . DB_PREFIX . "product_cost` (
  `product_id` int(11) NOT NULL,
  `cost` decimal(15,4) NOT NULL,
  PRIMARY KEY (`product_id`)
  )");

  $this->load->model('setting/event');
  // Here we inject all the events from above
  $this->model_setting_event->addEvent();

}
```


The final part, injecting the view.. I think I'll just post my solution I posted on the opencart forum as I think it'll make sense:

https://forum.opencart.com/viewtopic.php?p=814032#p814032

**Comment by stalker780** [comment]
@exelaguilar
> 
> This can be done with the Events system and a Module.

That's good. Now try to select this field in catalog/model/catalog/product|getProducts and getTotalProducts :)

And now imagine you have 10-20 custom product fields from different tables. How many requests are you going to execute for product list and for each product?

Earlier this could be done by injecting OCMOD JOINs directly into SQL request. Sometimes there were conflicts. 
But still this was much better than calling multiple requests with own sorts and filters.

OpenCart 4 requires absolutely different DB query structure with own events, which can be called before db->query.

**Comment by TheCartpenter** [comment]
I still don't understand why forum requests are being posted in here.

**Comment by exelaguilar** [comment]
> @exelaguilar
> 
> > This can be done with the Events system and a Module.
> 
> That's good. Now try to select this field in catalog/model/catalog/product|getProducts and getTotalProducts :)
> 
> And now imagine you have 10-20 custom product fields from different tables. How many requests are you going to execute for product list and for each product?
> 
> Earlier this could be done by injecting OCMOD JOINs directly into SQL request. Sometimes there were conflicts.
> But still this was much better than calling multiple requests with own sorts and filters.
> 
> OpenCart 4 requires absolutely different DB query structure with own events, which can be called before db->query.

You would target the product_thumb controller/before, of course you'd make a model to run the query but for the sake of an example..


```
	public function productsB(&$route, &$data) {

		foreach($data as $k => $d) {

			$shipping_cost = '0.000';

			$query = $this->db->query("SELECT shipping_cost FROM " . DB_PREFIX . "product_shipping_cost WHERE product_id='" . (int)$d['product_id'] . "'");

			if($query->row) {
				$shipping_cost = $query->row['shipping_cost'];
			}
			
			$data[$k]['shipping_cost'] = $shipping_cost;
			
		}

	}
```

You now have shipping_cost available in the foreach twig loop. And again, using the link I posted above, you can inject this with an event as well. 

Now your point is completely valid in that it would be nice to be able to not have to call multiple requests, because in theory, you can use an /after in catalog/model/catalog/product|getProducts and do something like:

```
	public function products(&$route, &$data, &$output) {

		foreach($output as $k => $product) {

			$shipping_cost = '0.000';

			$query = $this->db->query("SELECT shipping_cost FROM " . DB_PREFIX . "product_shipping_cost WHERE product_id='" . (int)$k . "'");

			if($query->row) {
				$shipping_cost = $query->row['shipping_cost'];
			}

			$output[$k]['shipping_cost'] = $shipping_cost;

		}

	}
```

to simply edit the output, but this way, you can't inject into $product_data before it gets pushed to product_thumb.

**Comment by Hkr32** [comment]
There is something that "must have" be in the system...

**Comment by chulcha** [comment]
@exelaguilar
Where view
Not ptoblem for use event.

There is no tool to add any fields 

Not only into a product, but into another entity (category, manufacturer,etc)

I use events, it's not difficult for me.
It's harder for me to add a field to the view
Or add to product_description, for example 

```
	public function getDescriptions($product_id) {
		$product_description_data = [];

		$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "product_description` WHERE `product_id` = '" . (int)$product_id . "'");

		foreach ($query->rows as $result) {
			$product_description_data[$result['language_id']] = [
				'name'             => $result['name'],
				'description'      => $result['description'],
				'meta_title'       => $result['meta_title'],
				'meta_description' => $result['meta_description'],
				'meta_keyword'     => $result['meta_keyword'],
				'tag'              => $result['tag']
			];
		}

		return $product_description_data;
	}
````
I need add field, 
And in this place I am already limited 
And there are many such places. 
Exit? Additional requests. 
If for the admin panel it may be insignificant, then for the front it is very sensitive.

**Comment by danijelGombac** [comment]
Maybe add some required arrays and add value to it with events.
```

public function getDescriptions($product_id, $required_description = []) {
    $required_description = array_marge([
        'name',
        'description',
        'meta_title',
        'meta_description',
        'meta_keyword',
        'tag'
    ], $required_description);

    $product_description_data = [];

    $query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "product_description` WHERE `product_id` = '" . (int)$product_id . "'");

    foreach ($query->rows as $result) {
        $product_description_data[$result['language_id']] = [];

        foreach ($required_description as $key) {
            if (isset($result[$key])) {
                $product_description_data[$result['language_id']][$key] = $result[$key];
            }
        }
    }

    return $product_description_data;
}
```

or

```
public function getOptions($product_id, $required_option = [], $required_option_value = []) {
    $required_option = array_marge([
        'product_option_id',
        'option_id',
        'name',
        'type',
        'value',
        'required'
    ], $required_option);

    $required_option_value = array_marge([
        'product_option_value_id',
        'option_value_id',
        'quantity',
        'subtract',
        'price',
        'price_prefix',
        'points',
        'points_prefix',
        'weight',
        'weight_prefix'
    ], $required_option_value);

    $product_option_data = [];

    $product_option_query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "product_option` po LEFT JOIN `" . DB_PREFIX . "option` o ON (po.`option_id` = o.`option_id`) LEFT JOIN `" . DB_PREFIX . "option_description` od ON (o.`option_id` = od.`option_id`) WHERE po.`product_id` = '" . (int)$product_id . "' AND od.`language_id` = '" . (int)$this->config->get('config_language_id') . "' ORDER BY o.`sort_order` ASC");

    foreach ($product_option_query->rows as $product_option) {
        $product_option_value_data = [];

        $product_option_value_query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "product_option_value` pov LEFT JOIN `" . DB_PREFIX . "option_value` ov ON (pov.`option_value_id` = ov.`option_value_id`) WHERE pov.`product_option_id` = '" . (int)$product_option['product_option_id'] . "' ORDER BY ov.`sort_order` ASC");

        foreach ($product_option_value_query->rows as $product_option_value) {
            $product_option_value_data[] = [];

            foreach ($required_option_value as $key) {
                if (isset($product_option_value[$key])) {
                    $product_option_value_data[][$key] = $product_option_value[$key];
                }
            }
        }

        $product_option_data[] = [
            'product_option_value' => $product_option_value_data
        ];

        foreach ($required_option as $key) {
            if (isset($product_option[$key])) {
                $product_option_data[][$key] = $product_option[$key];
            }
        }
    }

    return $product_option_data;
}
```

**Comment by stalker780** [comment]
> I still don't understand why forum requests are being posted in here.

This is not a forum question. Here developers try to tell Daniel that events in current condition are not ideal and need more work and SQL construction changes.

**Comment by TheCartpenter** [comment]
> > I still don't understand why forum requests are being posted in here.
> 
> This is not a forum question. Here developers try to tell Daniel that events in current condition are not ideal and need more work and SQL construction changes.
> 
> There are absolutely no hooks to work with SQL.
> Same with twig files. Damn, even a product grid/list have no own id/class. Every template developer invents his own method to select this block with jquery and ocmods.
> 
> We gonna have a lot of issues with extensions/templates compatibility. And some issues last for many years. For most developers is easier to use own OC builds with lots of core modifications.
> Just because Daniel rejects all proposals and even visible and tested bugs. Many things, implemented in recent OC versions, including SEO, were proposed here almost 10 years ago.
> 
> So hope, events will become usable in 5-8 years :)
> Meantime every developer will invent his own wheel.

If so, then HTH can one explain that ```array_marge``` has been untested while it should of been ```array_merge``` ???

On the plus side, the most relative term that can be found on Google with it is with The Simpsons where the array is even less relative with it. If codes are going to be suggested to Daniel, then the least to show PHP functions that is most relative with the core rather than 3rd party codes and, in this scenario, with other television shows!!

**Comment by chulcha** [comment]
@TheCartpenter 
Wake up! You are shown overloaded code, and you are some Simpsons (who is this?)

**Comment by TheCartpenter** [comment]
The function name is wrong, don't you see that?? Even the original function name is not used such ways to gather database rows from the core.

**Comment by Hkr32** [comment]
> If so, then HTH can one explain that `array_marge` has been untested while it should of been `array_merge` ???

Go to edit the indents, do not meddle with what you do not understand. Here adults communicate...

**Comment by TheCartpenter** [comment]
Reported.

**Comment by chulcha** [comment]
> 
> 
> Reported.

What?

**Comment by chulcha** [comment]
@TheCartpenter 

What is your OС experience?
How many stores have you run?
How many modules have you written? 
What do you know about sql query optimization?

**Comment by stalker780** [comment]
@danijelGombac
> 
> Maybe add some required arrays and add value to it with events.

This can help. But only partially.

Look at this from a point of view of category filter extension developer.
For example you need to add own product filters to model functions getProducts and getTotalProducts. Filter by attributes, options, etc.

This is not possible with events only, at the moment.

Take into account you may have another extensions, which add own filters and fields.

An only way now is to add after event, which will ignore all results retrieved in function and call another SQL query with needed structure. So we get double DB server load just with one extension. 
Also, method I just described, will work only for one extension. What will happen if another extension needs to add own filters to this function?

VQMod and OCMod were not ideal, had own drawbacks, but they dealt with such situations. But events will not.

**Comment by danijelGombac** [comment]
@stalker780 

```
$this->db->setSelect($value, $sort_order);
$this->db->setFrom($from);
$this->db->setJoin($join, $sort_order);
$this->db->setFilter($filter, $sort_order);

....AND SO ON...
```

and then in

`$this->db->query();`

build the query with all the data ordered with $sort_order. This way with event you can add own joins and filters to the query.

**Comment by chulcha** [comment]
@danijelGombac 

Where
`$this->db->daleteJoin($join, $sort_order);`


In fact, query builder is not as simple as it seems. 

You can use in your projectsthird party libraries.

To use it in the OС, you need Daniel to want it and make it ..
Daniel does not recognize third party libraries. But he himself does not write such a library - this is time and costly.

example - vqmod vs ocmod

**Comment by danijelGombac** [comment]
@chulcha 

Somthing or core

`$this->db->setJoin('oc_' . $some_key, $join, $sort_order); `

and for extension

 `$this->db->setJoin($extension . '_' . $table_name, $join, $sort_order);`

and 

`$this->db->removeJoin($key);`

**Comment by stalker780** [comment]
By the way, did anybody test events for system/library?

I cannot make events work for db->query() function.
Same for response->output().
Suspect all other system libraries do not work either.

**Comment by danijelGombac** [comment]
@stalker780 

I try and when the library load the event is executed.


```
'library/document/after' => [
        0 => 'event/test'
],

public function index(&$route, &$args) {
        $this->log->write($this->document->getLinks());
}

$this->load->library('document');
```

**Comment by stalker780** [comment]
@danijelGombac 

Hmmm... Looks like event is executed only on load $this->load->library('library').

But I cannot make it execute on calls like $this->db->query("SQL");

**Comment by chulcha** [comment]
event exist when load
But not exist when new

```
if ($part[0] == 'system') {
	$this->event->register($result['trigger'], new \Opencart\System\Engine\Action($result['action']), $result['sort_order']);
}

```
What it iS? (sysytem)

**Comment by IP-CAM** [comment]
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=38194

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31745

found here, among others:
https://www.google.com/search?q=Opencart+cost+price&ie=utf-8&oe=utf-8

**Comment by chulcha** [comment]
@IP-CAM 
not problem with ocmod

Problem - ver 4. Add any field, example. to product
Also get any field from product_description (see model) without overhead query

**Comment by IP-CAM** [comment]
Sorry, I was not aware of, that some already try to try to use that in real ... :)

**Comment by mhcwebdesign** [comment]
> Hmmm... Looks like event is executed only on load $this->load->library('library').
> 
> But I cannot make it execute on calls like $this->db->query("SQL");

The `$this->load->library('xyz')` allows for a before or after event.

Perhaps the decorator design pattern can be of some help here. Basically, the event handler will load an alternative class, it could be a wrapper for the original instance of the library class, with functional modifications, and then the OpenCart registry would point to this wrapper-decorator using the same name 'xyz' in the registry.

Of course, OpenCart 4 should actually use the this->load->library(...) calls in the first place for loading all of its singleton classes like db, document, response, url etc. Just a quick thought, but worth looking into it.

**Comment by MarvinKlein1508** [comment]
There is an extension available to display a unit price.
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=11829

**Comment by stalker780** [comment]
@MarvinKlein1508 
> 
> There is an extension available to display a unit price.
> https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=11829

For OC4.0?

**Comment by chulcha** [comment]
@stalker780 Оказывается, что не только  русскоязычные программисты не читают :)

**Comment by danielkerr** [comment]
closing this as u can get an extension for it. also this is a feature request.
