### ISSUE TITLE
Order comment missing from HTML mail confirmation

### ISSUE THREAD

**Issue by rickard2** [opencart/opencart#93]
In the non-html version of the order confirmation e-mail the order comment is present, but not in the HTML version. 

This code adds it to the text-based version: 

(catalog/model/order.php:476)

``` PHP
            if ($order_info['comment']) {
                $text .= $language->get('text_new_comment') . "\n\n";
                $text .= $order_info['comment'] . "\n\n";
            }
```

The value of `$order_info['comment']` is never added to the HTML template and there doesn't seem to be any markup for it either. 

I could maybe look into a pull request if no one else is up for it.

**Comment by danielmoore123** [comment]
> Agree with ADDCreative too. strange logic
1) user input named "comment"
2) mysql field named "comment"
3) echo $template->data['comment'] is not user comment!

So my question is, why does this solution as a whole not work? When a comment is left, I can see it in the database and in the OpenCart administration itself, but it refuses to output a user comment in the order confirmation email!! I tried to echo $ip in the email template and it works great, despite the fact it is in the same table as comment!!! Can I rename the comment section if it conflicts? Is there something more to make this work? I have Googled this and searched it all over Stackoverflow, GitHub, OpenCart Fourms, the answer is nowhere... This thread is closed but, why? It doesn't work!!

**Comment by ADDCreative** [comment]
@danielmoore123 https://github.com/opencart/opencart/pull/94 This is the original pull request I submitted to add the comments to the HTML confirmation email. It is for an old version 1.5.4, by may be helpful to you.
