### ISSUE TITLE
 Undefined variable: products in /extension/opencart/catalog/controller/module/featured.php

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9300]
**What version of OpenCart are you reporting this for?**

Master branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Notice: Undefined variable: products in /upload/extension/opencart/catalog/controller/module/featured.php on line 23
`foreach ($products as $product) {`
Warning: Invalid argument supplied for foreach() in /upload/extension/opencart/catalog/controller/module/featured.php on line 23

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by TheCartpenter** [comment]
After:

```$data['products'] = [];```

add:

```$products = [];```

**Comment by TheCartpenter** [comment]
#9351

**Comment by TheCartpenter** [comment]
Commit closed without closure notes.
