### ISSUE TITLE
Error at Upgrade

### ISSUE THREAD

**Issue by tjapro** [opencart/opencart#9347]
**What version of OpenCart are you reporting this for?**
3.0.3.6 -> 3.0.3.7

**Describe the bug**
```
SyntaxError: Unexpected token < in JSON at position 0 OK Warning: file(/var/www/.../upload/admin/config.php): failed to open stream: No such file or directory in /var/www/.../upload/install/model/upgrade/1009.php on line 97Warning: Invalid argument supplied for foreach() in /var/www/.../upload/install/model/upgrade/1009.php on line 99Warning: Invalid argument supplied for foreach() in /var/www/.../upload/install/model/upgrade/1009.php on line 110Warning: fopen(/var/www/.../upload/admin/config.php): failed to open stream: No such file or directory in /var/www/.../upload/install/model/upgrade/1009.php on line 119Warning: fwrite() expects parameter 1 to be resource, bool given in /var/www/.../upload/install/model/upgrade/1009.php on line 121Warning: fclose() expects parameter 1 to be resource, bool given in /var/.../upload/install/model/upgrade/1009.php on line 123{"success":"Patch 1009 has been applied (10 of 10)","next":"index.php?route=upgrade\/upgrade\/next&step=11"}
```
**To Reproduce**
Follow the upgrade steps and go to http://..../install/index.php?route=upgrade/upgrade

**Expected behavior**
No error.

**Server / Test environment (please complete the following information):**
 - CentOS Server
 - PHP 7.4.15
 - Nginx 1.16.1

**Additional context**
Before opening this issue, I've done this:
- Changed the two config files to this:
´´´
// DIR
define('DIR_APPLICATION', '/var/www/..../upload/catalog/');
define('DIR_SYSTEM', '/var/www/..../upload/system/');
define('DIR_IMAGE', '/var/www/.../upload/image/');
define('DIR_STORAGE', '/var/www/.../upload/system/storage/');
´´´
- My storage folder is in upload/system/storage.
- My server is apointing to inside the upload folder (root="..../upload/").
- I checked the permissions and they are correct.
- Aplied this fix: https://github.com/opencart/opencart/issues/9075#issuecomment-774502931

**Comment by TheCartpenter** [comment]
The upload folder is in the validation. Is your config.php and admin/config.php files both contain the upload folder? If so, then the upload folder must not be used prior to run the upgrade. Ensure that both config files have the corresponding server folders prior to run the upgrade. In addition, it also looks like you have a folder permission write access error. Ensure to use the storage folder inside of the public_html folder and not outside when running the upgrade.

**Comment by tjapro** [comment]
I've changed the two config files to this:
´´´
// DIR
define('DIR_APPLICATION', '/var/www/..../upload/catalog/');
define('DIR_SYSTEM', '/var/www/..../upload/system/');
define('DIR_IMAGE', '/var/www/.../upload/image/');
define('DIR_STORAGE', '/var/www/.../upload/system/storage/');
´´´
My storage folder is in upload/system/storage.
My server is apointing to inside the upload folder.
I checked the permissions and they are correct.

**Comment by TheCartpenter** [comment]
Yes, I ran a test last night on the master branch and I noticed an issue with the DIR_OPENCART constant that is defined in the install/cli_install.php file. Even though that constant is added in both config.php files, the constant still won't be seen until manually adding the defined constant into the install/controller/upgrade controller.

**Comment by tjapro** [comment]
But this line https://github.com/opencart/opencart/blob/d3bccd35801675dc6dbd4f20a0805b915b63923a/upload/install/cli_install.php#L39 is refenced in the following lines.
What should I do in this version (not master branch)?

**Comment by TheCartpenter** [comment]
@tjapro: I understand where you're coming from with this. Which is why, I have proposed to set both tags - master branch and maintenance - to ensure that both addressed issues gets resolved altogether. For now, more troubleshooting is needed until resolution of both ends.

**Comment by prabhatkumaroc082** [comment]
@tjapro 
when upgrading from 3.0.3.6 to 3.0.3.7
model /install/model/upgrade/1009.php
what's the value of variable $file on line 95?

**Comment by prabhatkumaroc082** [comment]
@tjapro 
Are you still facing the same issue?

**Comment by WebkulOpencart** [comment]
@tjapro we again recheck this issue but not found any such issue so closing this issue

**Comment by tjapro** [comment]
Sorry for the delay, but I'm preparing the server for a good upgrade, without interfere with production website.
ASAP, I'll see your questions. Thanks in advance!

**Comment by tjapro** [comment]
I upated the first commet to the actual testing environment.

**Comment by tjapro** [comment]
> @tjapro
> when upgrading from 3.0.3.6 to 3.0.3.7
> model /install/model/upgrade/1009.php
> what's the value of variable $file on line 95?

$file = DIR_OPENCART . 'admin/config.php';
$lines = file(DIR_OPENCART . 'admin/config.php');

**Comment by tjapro** [comment]
Changing these lines to the correct folder, the upgrade continues smoothly.
