### ISSUE TITLE
Checkout bug

### ISSUE THREAD

**Issue by tjapro** [opencart/opencart#9352]
**What version of OpenCart are you reporting this for?**
3.0.3.6

**Describe the bug**
At this route `index.php?route=checkout/checkout` I've got this error:
```
Notice: Trying to access array offset on value of type bool in /var/www/.../shop/catalog/controller/startup/startup.php on line 166Notice: Trying to access array offset on value of type bool in /var/www/.../shop/catalog/controller/startup/startup.php on line 166
```

Then the State input is blank/without options.

And when I try to change the Country, the page give me this message:
![Captura de ecrã de 2021-02-15 13-16-47](https://user-images.githubusercontent.com/7900361/107951373-2617cd80-6f90-11eb-8dbf-104c4c1d53e3.png)

**To Reproduce**
1. Add somthing to the cart.
2. Enter an account.
3. Opens the invoice address.
4. See the errors

**Expected behavior**
No errors.

**Server / Test environment (please complete the following information):**
VPS
CentOS 7
PHP 7.4.0
Nginx 1.16.1

**Additional context**
I've not update to 3.0.3.7 because of https://github.com/opencart/opencart/issues/9347

The addressed lines are:
```
if (isset($this->session->data['shipping_address'])) {
                        $this->tax->setShippingAddress($this->session->data['shipping_address']['country_id'], $this->session->data['shipping_address']['zone$
                } elseif ($this->config->get('config_tax_default') == 'shipping') {
                        $this->tax->setShippingAddress($this->config->get('config_country_id'), $this->config->get('config_zone_id'));
                }
```
https://github.com/opencart/opencart/blob/e9522c4db446f219cda7392bb8ca93c244ac1e97/upload/catalog/controller/startup/startup.php#L166
Some lines are truncated.

**Comment by TheCartpenter** [comment]
Already solved: https://github.com/opencart/opencart/blob/master/upload/catalog/controller/startup/application.php#L67 from line 67 until line 78.

**Comment by tjapro** [comment]
Sorry but in `controller/startup` folder I haven't that file:
```
cd /var/www/..../shop/catalog/controller/startup/
ls
error.php  event.php  maintenance.php  router.php  sass.php  seo_url.php  session.php  startup.php
```

**Comment by TheCartpenter** [comment]
While the URL you posted above shows an invalid page, you are posting about OC v3.0.3.6 which catalog/controller/startup/startup.php file does exist, however. In the mean time, this issue has also been solved in OC v3.0.3.7 which is under the same folder and file as well.

**Comment by TheCartpenter** [comment]
The URL above has now been fixed by the OP user.

**Comment by tjapro** [comment]
> While the URL you posted above shows an invalid page, 
I corrected the url.

I chnaged the lines in startup file and the bugs dispapperared. Thanks!
