### ISSUE TITLE
Add Return email notification admin

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#9353]
**What version of OpenCart are you reporting this for?**
3.0.x.x -4.0.x.x

Return email notification for admin never was completed. 
As you can check there is no return(s).php in catalog/controller/mail to notify website admin when a customer return a product.

return(s) controller from admin is used only to add Return's in admin and to notify (email) the customer when admin update Return history.

**Comment by TheCartpenter** [comment]
Yes, correct. There's one for account/returns, event/activity|addReturn (singular still) but catalog/controller/mail/returns.php does not seem to exist for some reason. The oc_event table would also need this notification added.

**Comment by condor2** [comment]
I am trying to make one using this event...

`catalog/model/account/return/addReturn/after   mail/return`

**Comment by TheCartpenter** [comment]
Yes, this is a valid point. The problem is that the catalog/controller/mail/returns.php file does not have an email constructor in the folder and needs to have one along with the admin-end side. I am not sure if text or html TWIG file should be used though.

**Comment by TheCartpenter** [comment]
The alternative route on why it may have been removed would be about reducing SPAMs due to the excessive mount of emails being sent in the past about falsified information about returned products.

**Comment by condor2** [comment]
Hmm it is possible Like contact form :)

**Comment by condor2** [comment]
I think it is possible to be improvement.
For example when a customer or a guest enter an order ID and doesn't exist in the database when hit the Submit button to display a message.

**Comment by TheCartpenter** [comment]
By doing that, it would also provide the falsified user that the order ID does indeed not exist in order to increase the mount of tryouts. One way to rectify this situation would be by using the same methods as the ones the customer logins are already using whenever an HTML form with orders and products information needs to be submitted from the catalog. In this scenario, it would only require one more controller, language and models to accomplish this.

**Comment by TheCartpenter** [comment]
In addition to the above, restriction attempts to enter an order ID may then affect the Point of Sales (POS) whenever a physical / virtual products needs to be returned which can, then, lead to further disputes from customers. In the end, that may become as complicated as it is now to resolve those issues administratively-based.
