### ISSUE TITLE
Add option to change the Dashboard Map based on country vmap files

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#9354]
**What version of OpenCart are you reporting this for?**
Master Branch

I think will be nice if you can change Dashboard Map by country (based on existing vmap files).

**Comment by TheCartpenter** [comment]
Any PRs you could show based on this change?

**Comment by Hkr32** [comment]
@TheCartpenter, you "в каждой бочке затычка". Go fix the indentation. Don't bother people!

**Comment by TheCartpenter** [comment]
> @TheCartpenter, you "в каждой бочке затычка" ("To have a finger in every pie"). Go fix the indentation. Don't bother people!

I guess that proves my theory that, while you're posting in different languages and this repository supports the English language as it is the language pack being delivered originally from the OC core in the mean time, you haven't read my notes from the Pull Requests regarding the completion of these tasks already.
