### ISSUE TITLE
Opencart Direct & Server payments

### ISSUE THREAD

**Issue by SPB105438** [opencart/opencart#9355]
**What version of OpenCart are you reporting this for? 3.0.3.7 - master branch

**Describe the bug**
Placing an order with the sage pay direct or sagepay server the payments fails, 
no record of the transaction shows in sagepay, once the transaction fails, you are returned to the login page of your shop, and are no longer logged in, once logged back in, the product remain in the cart

Server error 5006: Unable to redirect to Vendor's web site. The Vendor failed to provide a RedirectionURL

edit: Sagepay Server does take payment, but then error 5006: Unable to redirect to Vendor's web site. The Vendor failed to provide a RedirectionURL is displayed also 

HTTP error 500: The request was unsuccessful due to an unexpected condition encountered by the server.

**To Reproduce**
1. Enable sagepay direct or sagepay server
2. place an order

**Expected behavior**
Order to be place and order confirmation page to be displayed.

**Server / Test environment (please complete the following information):**
 - Local development? Development Server, Deployed to a web server Yes
 - Operating system - Windows Server 2016
 - PHP version 7.4.13
 - Using Chrome and New Edge browser

**Additional context**
Products and payment providers setup using the same details as my live opencart shop running 2.3.0.2 - trying to rebuild our shop in 3.0.3.7

**Comment by ADDCreative** [comment]
You need to look in your PHP error logs to see what caused the 500 server error. Ask in the forums for help. https://forum.opencart.com/

**Comment by SPB105438** [comment]
So i have setted on using SagePay Direct method, 
I dont have any php error logs, i have setup logging in php.ini and had them checked, 

IIS logs
GET /index.php route=checkout/payment_method 443 - ........../index.php?route=checkout/checkout 200 0 0 140
POST /index.php route=checkout/payment_method/save 443 - ........../index.php?route=checkout/checkout 200 0 0 62
GET /index.php route=checkout/confirm 443 - ........../index.php?route=checkout/checkout 200 0 0 109
POST /index.php route=extension/payment/sagepay_direct/send 443 - ........../index.php?route=checkout/checkout 200 0 0 2015
POST /index.php route=extension/payment/sagepay_direct/callback 443 - 1.......... https://secure7.arcot.com/ 302 0 0 171
GET /index.php route=account/login 443 - .......... https://secure7.arcot.com/ 200 0 0 343

Opencart Log

2021-02-17 14:27:50 - PHP Notice:  Undefined variable: data in C:\inetpub\wwwroot\shop\catalog\model\extension\payment\sagepay_direct.php on line 420
2021-02-17 14:27:50 - PHP Notice:  Trying to access array offset on value of type null in C:\inetpub\wwwroot\Staffshop\catalog\controller\extension\payment\sagepay_direct.php on line 241
2021-02-17 14:27:50 - PHP Notice:  Trying to access array offset on value of type null in C:\inetpub\wwwroot\Staffshop\catalog\controller\extension\payment\sagepay_direct.php on line 270
2021-02-17 14:27:50 - PHP Notice:  Trying to access array offset on value of type null in C:\inetpub\wwwroot\Staffshop\catalog\controller\extension\payment\sagepay_direct.php on line 270
2021-02-17 14:27:50 - PHP Notice:  Trying to access array offset on value of type null in C:\inetpub\wwwroot\Staffshop\catalog\controller\extension\payment\sagepay_direct.php on line 270
2021-02-17 14:27:50 - PHP Notice:  Trying to access array offset on value of type null in C:\inetpub\wwwroot\Staffshop\catalog\controller\extension\payment\sagepay_direct.php on line 336
2021-02-17 14:27:50 - PHP Notice:  Trying to access array offset on value of type null in C:\inetpub\wwwroot\Staffshop\catalog\controller\extension\payment\sagepay_direct.php on line 336

Nothing customised, no files changed

**Comment by SPB105438** [comment]
Ok, so after comparing the file "\catalog\controller\extension\payment\sagepay_direct.php" against one on my live shop running 2.3.0.2, i noticed the following had been added to lines 145

if(!isset($this->session->data['order_id'])) {
	return false
	}

If i remove this, everything works fine!
Can anyone explain to me what this is supposed to do? or why it was added?

**Comment by ADDCreative** [comment]
It's checking that ```$this->session->data['order_id']``` exists. As it's used on the next line. Checking is OK but returning false looks wrong. It should probably return an error message.

Looking at your ISS logs, it looks like you have a SameSite issue with your session cookie. See. https://forum.opencart.com/viewtopic.php?f=202&t=219633#p797082

**Comment by SPB105438** [comment]
samesite issue, how?
this is the main reason for upgrading to 3.0.3.7 and php 7.4 as the issue has been fixed, so the link is irrelevant, these changes detailed in the post are not required, these are for previous versions of opencart.
my new site is using 3.0.3.7 and php 7.4 without any customisation, so surely if im having this issue, other will also have the issue too.

Not seen any documents or post advising to make any further changes or set anything in PHP.ini to work with this line of code.
Removing this code from the sagepay_direct.php file resolves all my issues, 

if(!isset($this->session->data['order_id'])) {
return false
}

**Comment by ADDCreative** [comment]
The SameSite cookie issue hasn't been fixed in 3.0.3.7. There has been an attempt to fix it on the mater branch, but this looks like it will make the problem worse. If someone has told you otherwise, you have been mislead. The logs you posted also indicate a loss of session.

I can only guess removing that bit or code helps as it's missing the semicolon off the end of false. Which could be the cause of your 500 server error.

**Comment by SPB105438** [comment]
Ahh ok, I was going off the tickets for the samesite issue being closed.

I still need to do further tests, I did notice the 7.4.13 php.ini file which im running has references to samesite and cookie settings, I was unable to find any reference to opencart and this version of PHP for recommended settings.

; Add SameSite attribute to cookie to help mitigate Cross-Site Request Forgery (CSRF/XSRF)
; Current valid values are "Lax" or "Strict"
; https://tools.ietf.org/html/draft-west-first-party-cookies-07
session.cookie_samesite =

; Whether to use strict session mode.
; Strict session mode does not accept an uninitialized session ID, and
; regenerates the session ID if the browser sends an uninitialized session ID.
; Strict mode protects applications from session fixation via a session adoption
; vulnerability. It is disabled by default for maximum compatibility, but
; enabling it is encouraged.
; https://wiki.php.net/rfc/strict_sessions
session.use_strict_mode = 0

; Whether to use cookies.
; http://php.net/session.use-cookies
session.use_cookies = 1

; http://php.net/session.cookie-secure
;session.cookie_secure =

; This option forces PHP to fetch and use a cookie for storing and maintaining
; the session id. We encourage this operation as it's very helpful in combating
; session hijacking when not specifying and managing your own session id. It is
; not the be-all and end-all of session hijacking defense, but it's a good start.
; http://php.net/session.use-only-cookies
session.use_only_cookies = 1

; Name of the session (used as cookie name).
; http://php.net/session.name
session.name = PHPSESSID

; Initialize session on request startup.
; http://php.net/session.auto-start
session.auto_start = 0

; Lifetime in seconds of cookie or, if 0, until browser is restarted.
; http://php.net/session.cookie-lifetime
session.cookie_lifetime = 0

I guess depending on the version of opencart and version of php, there may be several different fixes for the samsite issue, 
Opencart recommends a minimum php of 7.3, it may be useful to state a "recommended version" one which most of the testing has been done with, in the meantime, just my opinion as an "Enduser" 
Im happy to remove this line of code and have everything working.

I appreciate everything the devs are putting into delivering and maintaining the opencart platform

**Comment by ADDCreative** [comment]
One other thing to take into account is that OpenCart 3 doesn't use PHP native sessions. It implements its own session handling so setting session.cookie_samesite will have no affect.

**Comment by prabhatkumaroc082** [comment]
> if(!isset($this->session->data['order_id'])) {
> return false
> }

@SPB105438 
I think the issue has been fixed now, and it was due to a missing semicolon. Valid line of code is added for the maintenance branch https://github.com/opencart/opencart/blob/cd2758889204199759a39814b8196ac7fec7e499/upload/catalog/controller/extension/payment/sagepay_direct.php#L123

**Comment by SPB105438** [comment]
Apologieshad to take a break from this, 
I have been testing further, I have confirmed payments do work with the following code and without it, so this is not the issue.

if(!isset($this->session->data['order_id'])) {
return false
}

This is what happens. (test 1)
The first order placed will be completed, no issues, even when using 3D secure.
The second order placed will fail with 3D secure, but using the sagepay test card without 3d secure, the order will go through.

(test 2)
The first order placed will be completed, no issues, even when using 3D secure.
Clearing the browser history
The second order placed will be completed, no issues, even when using 3D secure.


Clearing the browser history between orders works, but why and how do i fix it ?
