### ISSUE TITLE
Error when switch to PHP 8

### ISSUE THREAD

**Issue by seoiliev** [opencart/opencart#9356]
Hi, when i try to switch Opencart 3.0.3.6 from PHP 7.4 to PHP 8:

PHP Unknown:  Using the "Twig_Loader_Filesystem" class is deprecated since Twig version 2.7, use "Twig\Loader\FilesystemLoader" instead. in /home/..../..../vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 7

Can someone help?
Thanks in advance.

**Comment by condor2** [comment]
TWIG should be updated......but users with commit permissions doesn't listen.....and don't care

https://github.com/opencart/opencart/issues/8272

**Comment by IP-CAM** [comment]
([](https://www.php.net/releases/7_4_15.php)

Important Security Update for PHP 7.4.13 / 7.4.14 Users

**Comment by thewhiterabbit** [comment]
> 
> 
> TWIG should be updated......but some users with commit permissions doesn't listen.....and don't care
> 
> #8272

The owner of OpenCart is addicted to gambling at the racetrack and only wants to rip you off so he can gamble.
