### ISSUE TITLE
Cannot login to admin after changing Time Zone

### ISSUE THREAD

**Issue by lionsgatecreative** [opencart/opencart#9357]
**What version of OpenCart are you reporting this for?**
3.0.3.7.

**Describe the bug**
Just installed OpenCart. Went well, until client changed Time Zone (to EST). Then, he reported that >he got locked out of areas." Every time he tried to log back in, he was redirected back to login page. Solution I discovered was to change Time Zone to UTC via phpMyAdmin. Short-term fix, but requires long-term fix so can change Time Zone.

**To Reproduce**
Change Time Zone to non-UTC value.

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - Operating system: FreeBSD 12.1 AMD64 
 - PHP version: 7.3
 - Apache version: 2.4
 - Browser(s) tested with: Firefox 85.0.2

**Comment by exelaguilar** [comment]
Same issue posted here

https://github.com/opencart/opencart/issues/9237

**Comment by WebkulOpencart** [comment]
An issue is already created so closing this issue.
