### ISSUE TITLE
Product appears in all url variations

### ISSUE THREAD

**Issue by Farmshop** [opencart/opencart#9363]
**What version of OpenCart are you reporting this for?**
3.0.3.3
**Describe the bug**
If SEO is enabled, the SEO URLs of the categories can be changed in any combination in the title bar of the browser, and the product page will always be displayed.

**To Reproduce**
1. Nanavigate to 'a product trough its relevant categories for example: /demo/tablet/samsung-galaxy-tab-10-1'
2. Change 'the tablet to monitor in the url like this: /demo/monitor/samsung-galaxy-tab-10-1'
3. See error 'Product page still opens'

**Expected behavior**
I just expected a message like this: The page you were looking for could not be found.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Deployed to a web server.
 - Linux CentOS
 - PHP version 7.3.17
 - Apache 2.2
 - Browser(s) tested with Chrome
 - Version 88.0.4324.182

**Additional context**

**Comment by WebkulOpencart** [comment]
@Farmshop I found the issue and checking the same.
