### ISSUE TITLE
"Coupon" should not be the coupon code, but rather the coupon name.

### ISSUE THREAD

**Issue by sebastiannielsen** [opencart/opencart#9364]
When a customer adds a coupon, the coupon code is added to the total listing, instead of coupon name.

I tried to change line 177 of "catalog/model/extension/total/coupon.php":

from:
 'title'      => sprintf($this->language->get('coupon')->get('text_coupon'), $this->session->data['coupon']),

to:
 'title'      => sprintf($this->language->get('coupon')->get('text_coupon'), $coupon_info['name']),

which works, but instead this is causing orders to go into "Missing_Orders" or "Rejected" for some reason. Like, something is parsing the 'title' tag and try to "validate" the coupon.

I think this should be changed so the coupon shown is the name, and not the code, so the total listing should show
Coupon (50% off on all winter products):

instead of:
Coupon (WINTER50):

**Comment by WebkulOpencart** [comment]
@danielkerr Please confirm so that we can make the changes for the same in the maintenance branch

**Comment by sebastiannielsen** [comment]
@WebkulOpencart I also need to know what the second change is required for the orders not to end up in rejected or missing_orders when making the above change.

What for thing is parsing the 'title' property of the 'coupon' in the session and re-validating the coupon.

**Comment by WebkulOpencart** [comment]
@sebastiannielsen Order will only show in the missing order if the customer goes to the last step of the checkout and not place the order or if you are using any payment method and if customer payment successfully captured but still order showing in missing order then you need to contact the payment check the payment method code end

For this:- "What for thing is parsing the 'title' property of the 'coupon' in the session and re-validating the coupon."
----------
OpenCart only saves the coupon code in the session not the complete information of the coupon.

**Comment by sebastiannielsen** [comment]
@WebkulOpencart For some reason, if I make the above change, and make a order which is to 100% covered by the coupon, the order ends up in "rejected". Without the above change, order is completed successfully.

So there is something that is re-validating the coupon after finalizing the order. Some sort of anti-fraud check or similiar. Also once an order has been rejected this way, its impossible to set the order to an completed status, even with the "Override anti-fraud" checkbox checked.

**Comment by WebkulOpencart** [comment]
@sebastiannielsen if you want to add some type of functionality then please refer to the OpenCart forum you can get multiple solutions there.

As if an order is fully covered with the coupon then there is a payment method in default OpenCart **Free checkout** so this must be enabled as the online payment method not allowed the zero amount  to process.

**Comment by WebkulOpencart** [comment]
@sebastiannielsen as there is no any issue so closing this issue

**Comment by sebastiannielsen** [comment]
@WebkulOpencart I tried now.

First with
'title' => sprintf($this->language->get('coupon')->get('text_coupon'), $this->session->data['coupon']),
Free Checkout
Order is "Paid".

Changed line to:
'title' => sprintf($this->language->get('coupon')->get('text_coupon'), $coupon_info['name']),
Free checkout.
Order is "Rejected"

Changed line back to:
'title' => sprintf($this->language->get('coupon')->get('text_coupon'), $this->session->data['coupon']),
Free Checkout
Order is "Paid"

Something is forcing the order into "Rejected" state with the above change.

I don't know what it is. And im banned from the forum due to my ISP being in "High spam network" and the opencart support says that once im banned by the ISP ban I cannot be unbanned without changing ISP since the ban will just retrigger.
And i did a locked 36 month contract with ISP so cannot change that either.

**Comment by sebastiannielsen** [comment]
Found the issue:

Line 201 needs to be changed from:
                        $coupon_query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "coupon` WHERE code = '" . $this->db->escape($code) . "' AND status = '1'");


to
                        $coupon_query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "coupon` WHERE name = '" . $this->db->escape($code) . "' AND status = '1'");


Since the confirm() function "validates" the coupon by parsing out the code and querying the database.

So NOW it works.

PATCH INFO:
line 177:
from: 'title' => sprintf($this->language->get('coupon')->get('text_coupon'), $this->session->data['coupon']),
to: 'title' => sprintf($this->language->get('coupon')->get('text_coupon'), $coupon_info['name']),

line 201:
from: $coupon_query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "coupon` WHERE code = '" . $this->db->escape($code) . "' AND status = '1'");
to:  $coupon_query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "coupon` WHERE name = '" . $this->db->escape($code) . "' AND status = '1'");
