### ISSUE TITLE
Clear page for install

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#9375]
Running the installation from the master branch
Clear page for install
![image](https://user-images.githubusercontent.com/12296392/108901492-fc177880-762b-11eb-9e9f-4a9b11defa2a.png)

**To Reproduce**
1. Go to sait
2. Click on /install/index.php
3. See nothing

**Server / Test environment (please complete the following information):**
 - Local development. Open Server 5.3.8
 - Win 10
 - PHP 8
 - Apache 2.4 PHP8 Ngins 1.19
 - Opera Last

**Comment by cgcmart** [comment]
probably web server security_mod rejection.

**Comment by uees** [comment]
I have the same problem.  This was started after merging /issues/8283 .

Server / Test environment :

    Win 10
    WSL2 Docker 
    FROM php:8.0.2-fpm
    FROM nginx:1.18

nginx conf

```conf
server {
    listen 80;
    charset utf-8;
    server_name localhost;

    root /var/www/opencart;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
    	fastcgi_intercept_errors on;
        fastcgi_pass docker-php-fpm:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
        try_files $uri =404;
    }

    location ~* /\. {
        deny all;
    }
}
```

**Comment by chulcha** [comment]
namespace Opencart\Install\Controller\Startup;

https://github.com/opencart/opencart/blob/b917f9d88e8ac4f109c6aad23db3d0b9d5c4a856/upload/install/controller/startup/install.php#L2

**Comment by chulcha** [comment]
All controllers have a failed namespace

**Comment by Bobby00** [comment]
I faced the same issue, this is how I solved it

1. If running locally, try using WAMPP or LAMPP instead of the bitnami stacks 
2. Ensure you start your webserver (apache) and databases(mysqli) with admin privileges

**Comment by mhcwebdesign** [comment]
This should solve the issue: https://github.com/opencart/opencart/issues/8283#issuecomment-787480737
Remember, the Opencart master branch is still work in progress!

**Comment by exelaguilar** [comment]
Latest commits fix these issues.

**Comment by danielkerr** [comment]
Very simple turn error reporting on at the php level
