### ISSUE TITLE
Set minify JS file for banner, carousel and slideshow

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#9377]
Tested on OpenCart v.3.0.3.2

Files:
catalog/controller/extension/module/banner.php
catalog/controller/extension/module/carousel.php
catalog/controller/extension/module/slideshow.php

change from
`		$this->document->addScript('catalog/view/javascript/jquery/swiper/js/swiper.jquery.js');`
to
`		$this->document->addScript('catalog/view/javascript/jquery/swiper/js/swiper.jquery.min.js');`

**Comment by webkul-dilip** [comment]
@faca5  Thanks for your suggestion, now we have added the minified file. Now we are closing this issue.
