### ISSUE TITLE
Error:The totals of the cart item amounts do not match order amounts (1.5.6) (Paypal Express Checkout)

### ISSUE THREAD

**Issue by chiukit** [opencart/opencart#938]
When I checkout with a product with a high price, the Paypal express checkout will show the error message "The totals of the cart item amounts do not match order amounts". 

I fixed that problem by modifying the following file :
catalog/model/payment/pp_express.php

In the function called "paymentRequestInfo()":
$item_total += number_format($item_price \* $item['quantity'], 2);
change to
$item_total += $item_price \* $item['quantity'];

$item_total = number_format($item_total + $item_price, 2);
change to
$item_total += $item_price;

It's work for me.

I guess it should be the problem of data type conversion because "number_format" return a string, not integer or double. In fact, I don't know whether it is correct or not. because I am a newbie on Opencart. If I am wrong, please let me know.

**Comment by famarinu** [comment]
Hi, 
I'm using the OC version 2.1.0.1 with Juornal 2 template, and I have this problem only buy a gift voucher and pay with Paypal, otherwise it's all right. With this solution solve the problem?

**Comment by mgraph** [comment]
@abhimadhani  Thanks this fixed the issue

**Comment by hermanomark** [comment]
Hello sorry to revive an old post, I've followed @abhimadhani solution but still it won't work, here's my code

```
$item_self_collection_discount = number_format($data['L_PAYMENTREQUEST_0_AMT1'], 2, '.', '');
$item_total = $item_total - ($item_self_collection_discount * 2);

$data['PAYMENTREQUEST_0_ITEMAMT'] = number_format($item_total, 2, '.', '');
$data['PAYMENTREQUEST_0_AMT'] = number_format($item_total, 2, '.', '');
```

I've added the first 2 lines
