### ISSUE TITLE
Failed to open stream: No such file or directory 

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#9382]
v3.0.3.6

Error:
`Warning: fopen(.../logs/error.log): failed to open stream: No such file or directory in .../system/library/log.php on line 22`

Change from
`		$this->handle = fopen(DIR_LOGS . $filename, 'a');
`
to:
```
		if(file_exists($filename)) {
			$this->handle = fopen(DIR_LOGS . $filename, 'a');
		}

```

**Comment by TheCartpenter** [comment]
Forum request.

**Comment by WebkulOpencart** [comment]
Maybe you have changed the modification directory path? 
create a new file under DIR_LOGS with the name error.log and your issue will be resolved.

**Comment by faca5** [comment]
Yes. Dir has been removed. It is created back automatically but is missing sub dirs.

**Comment by WebkulOpencart** [comment]
@faca5 you can copy the missing subdirectory from the old storage directory
 and your issue will be resolved automatically.

**Comment by faca5** [comment]
Yes. It resolved. Thank you.

**Comment by WebkulOpencart** [comment]
@faca5 Welcome
