### ISSUE TITLE
Opencart is good cms but why twig is mandatory?

### ISSUE THREAD

**Issue by sernuzh** [opencart/opencart#9387]
I'm using opencart for 10 years and very happy to work with such cms. But last 5 years I still use 2.x version. This is not good for me but I can't start to use twig. It's a big problem and I guess not only for me. So I ask Daniel Kerr to release version with option - without twig. Thanks.

**Comment by mhcwebdesign** [comment]
I think Daniel has made the decision in favor of Twig. We do have an extension though which supports PHP templates, too:
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31589

**Comment by danielkerr** [comment]
the old the template class is still there
