### ISSUE TITLE
OC4 - PHP8 types

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#9400]
If $key not found it will try to return '' while only object type is allowed.

https://github.com/opencart/opencart/blob/557d9e810f4f3a9774f028df5ac3022ddf90aa03/upload/system/engine/registry.php#L25

**Comment by TheCartpenter** [comment]
Yes, I have noticed this as well yesterday.

**Comment by SaifAlSubhi** [comment]
There is an error:

TypeError: Opencart\System\Engine\Registry::get(): Return value must be of type object, string returned in /opencart/system/engine/registry.php on line 25

**Comment by SaifAlSubhi** [comment]
> If $key not found it will try to return '' while only object type is allowed.
> 
> https://github.com/opencart/opencart/blob/557d9e810f4f3a9774f028df5ac3022ddf90aa03/upload/system/engine/registry.php#L25

Hi, there is no pull request to fix. Even if you change the return type from object to mixed; then you get an error some where else later.

**Comment by mhcwebdesign** [comment]
Please try this in the **system/engine/registry.php** in your local test server:

```
	public function get(string $key): mixed {
		return isset($this->data[$key]) ? $this->data[$key] : null;
	}
```

The return type should be mixed, because entries  in the registry can have different types.

**Comment by SaifAlSubhi** [comment]
@mhcwebdesign
There is no error now even with object|null

**Comment by mhcwebdesign** [comment]
OK, it should look like this then:

```
	public function get(string $key): object|null {
		return isset($this->data[$key]) ? $this->data[$key] : null;
	}
```

This assumes that the registry only ever stores entries of type object which I think is the case at the moment.

@daniel: Can you confirm above please?

**Comment by SaifAlSubhi** [comment]
> OK, it should look like this then:
> 
> ```
> 	public function get(string $key): object|null {
> 		return isset($this->data[$key]) ? $this->data[$key] : null;
> 	}
> ```
> 
> This assumes that the registry only ever stores entries of type object which I think is the case at the moment.
> 
> @danielkerr : Can you confirm above please?

Hi,
There is an error now using object|null:
Error: Call to a member function getTotalProducts() on null in /admin/controller/catalog/product.php on line 268
https://github.com/opencart/opencart/blob/5d743659043bfeb851790845c16e8611d6345145/upload/admin/controller/catalog/product.php#L268

**Comment by chulcha** [comment]
return isset($this->data[$key]) ?? : null;

**Comment by mhcwebdesign** [comment]
@SaifAlSubhi: Add this after line 7 in **admin/controller/catalog/product.php** and then try again:

`$this->load->model('catalog/product');
`

**Comment by SaifAlSubhi** [comment]
> @SaifAlSubhi: Add this after line 7 in **admin/controller/catalog/product.php** and then try again:
> 
> `$this->load->model('catalog/product'); `

Thanks. It works.
I have just notice that it was removed:
https://github.com/opencart/opencart/commit/1b6a1bb8c369687d6e43c478f62ff83cfbca05eb#diff-495bc23e50250af9a2920ef81f591a16970624cc1c4b31de2f5052129195daa5L140
