### ISSUE TITLE
RTL support in OpenCart

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#9410]
**What version of OpenCart are you reporting this for?**
Both the 3.x and master version
**Describe the bug**
We can add the RTL support in default OpenCart.

**Comment by WebkulOpencart** [comment]
@danielkerr Please confirm so that we can work on the same

**Comment by WebkulOpencart** [comment]
#fixed frontend RTL CSS [https://github.com/opencart/opencart/pull/9744](https://github.com/opencart/opencart/pull/9744)

**Comment by danielkerr** [comment]
im closing this. i have no idea what oc looks like with rtl language
