### ISSUE TITLE
Warning: Gift Card is either invalid or the balance has been used up Error in Opencart

### ISSUE THREAD

**Issue by arslankhanabc** [opencart/opencart#9412]
I am using Opencart v 3.0.2.0 with default theme without any third party modules. I have installed SSL. When I apply the gift voucher code I get the erorr "Warning: Gift Card is either invalid or the balance has been used up". I kept

Order Staus = Complete then

Order Status = Processing and then

Order Status = Pending

Everytime keeping Processing Order Status = Processing

Complete Order Status = Complete

But I keep on getting the same error.

What should be order status in payments in extensions. For example Cash on Delivery, Bank Transfer and Cheque/Money Order. I kept Order Status = Processing and other time Pending in all of above payments.

Please guide do I need to change htacess file and config and admin/config files because I have installed SSL certificate.

**Comment by WebkulOpencart** [comment]
Please go to the OpenCart forum for the same as you are reporting the old version issue.
I just check for the latest 3.0.3.7 version and not found any such issue.
