### ISSUE TITLE
$total is not correct

### ISSUE THREAD

**Issue by BroCart** [opencart/opencart#9413]
**>2.x**

**Not correct TOTAL in cart and checkout**
one of places where bug is: https://github.com/opencart/opencart/blob/master/upload/catalog/controller/checkout/cart.php#L114

**To Reproduce**
1. Go to admin --> System-->Localisation-->Currency and set USD value 1.00000000, then add new currency (ex.: UAH [Ukrainian Hryvnia] and add value 28.55 (as conversion rate) AND add Decimal Places **"0"** (and select as default front currency)
2. Add some product with price 5$
3. Go to front and add to cart 1 q-ty of this product (5$ * 28.55) = 142.75 (with Decimal Places **"0"** will be 143)
4. go to basket and write to input area 10 of quantity this product: (5 * 10) * 28.55 = 1427.5 (with Decimal Places **"0"** will be 1428), it's NOT correct, must be 1430
logic of total = round(((unit_price * quantity) * conversion_rate), decimal_place)

**Expected behavior**
(**5**[price of unit] * **28.55**[conversion rate]) tnen rounded, by decimal place AND then * quantity

correct logic of total = round((unit_price * conversion_rate), decimal_place) * quantity

**Screenshots / Screen recordings**
http://joxi.ru/EA40JKptp67wqA.png

**Additional context**
correct logic into controller cart:
$price_temp = $this->currency->format($unit_price, $this->session->data['currency'], false, false);
$total = $this->currency->format($product['quantity'], $this->session->data['currency'], $price_temp);

detailed discussion (ukrainian): https://forum.brocart.net/threads/okruglennja-cin.237/

**Comment by WebkulOpencart** [comment]
@BroCart this is not correct, in this case, the admin gets the 2 UAH extra which is not feasible. So, I am closing this issue.

**Comment by BroCart** [comment]
4.x version is have this bug too:
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/checkout/cart.php#L114

**Comment by WebkulOpencart** [comment]
I am again checking for the -ve timezone

**Comment by WebkulOpencart** [comment]
@BroCart Please let me know for my above comment
https://github.com/opencart/opencart/issues/9413#issuecomment-792472946

**Comment by seo-bro** [comment]
In the previous option, the admin will benefit.
And if so:
http://icecream.me/uploads/4b03fe921516ad17d7c4202d028e231d.png
Here the buyer is already forced to overpay, is the mathematical logic broken 13 x 10 = 135?

**Comment by WebkulOpencart** [comment]
Mathematically this is correct. so, closing this issue.

**Comment by seo-bro** [comment]
Please do not close the question and listen to my arguments.
In most countries of the world, the buyer has the right to purchase a product or service at the price indicated on the price tag. And also there is responsibility for false information.
Why should a customer buy 1 item at $ 10 and 100 pieces at $ 10.5?
Why 2 x 2 ≠ 4?
The rights of the buyer are violated and lawsuits are possible against stores in countries where the coins were withdrawn from circulation.

**Comment by chulcha** [comment]
round(sum(totals))  ≠  sum(round(total))

**Comment by BroCart** [comment]
> Mathematically this is correct. so, closing this issue.

not quite so, for example: 
opencart.com is multicurrency and sells goods for Euro:
base prace (1.0000000) in admin in $, and selling by € (conversion rate: 1,19)
price of modul: 45$
settings currency Euro is: Decimal Places "0"
expected logic: round(53,55) = 54€
now, go to front and add 10 modules (quantity license per domens), what price will be displayed for customer 540 or 536 € ?

**Comment by WebkulOpencart** [comment]
> price of modul: 45$
> settings currency Euro is: Decimal Places "0"
> expected logic: round(53,55) = 54€
> now, go to front and add 10 modules (quantity license per domens), what price will be displayed for customer 540 or 536 € ?

As per the Default, OpenCart working 536 €  will be displayed. As single unit price is 53.55.

I need @danielkerr confirmation to make the changes as per your request.

**Comment by ADDCreative** [comment]
This issue has been mentioned many times before both here (see https://github.com/opencart/opencart/issues/5657, https://github.com/opencart/opencart/issues/1990 and https://github.com/opencart/opencart/issues/779 for just some of the examples) on the forums.

It is obviously going to be very noticeable if converting to a high value currency without decimals.

To fix it you would have to do all the checkout total and tax calculations after the currency conversion and rounding. This gets rather complicated when you throw in tax calculation and displaying with and without taxes.
See https://github.com/copona/copona/commit/8f0500193c5e2173ba4e5c0e1e37cb4a50637b2b#commitcomment-25190143 and https://github.com/copona/copona/commit/8f0500193c5e2173ba4e5c0e1e37cb4a50637b2b#commitcomment-27435401 for more details on what's involved.

**Comment by BroCart** [comment]
and many modules that implement simplified checkout use the same logic for counting quantities while being closed source (ioncube)

**Comment by BroCart** [comment]
@danielkerr in my opinion the parameter $quantity should be added to **public function format(** as a property of an object

**Comment by WebkulOpencart** [comment]
@danielkerr As I checked you closed the old issues for the same so we need your confirmation for the same so that we can solve and close this ASAP.

**Comment by rsuchovsky** [comment]
Has the rounding issue been resolved? But did the problem just end here?
