### ISSUE TITLE
[master] Error: Call to a member function query() on string catalog/model/design/layout.php

### ISSUE THREAD

**Issue by SaifAlSubhi** [opencart/opencart#9414]
**What version of OpenCart are you reporting this for?**
master-branch

**Describe the bug**
Error: Call to a member function query() on string in catalog/model/design/layout.php on line 5

https://github.com/opencart/opencart/blob/7738462d64eb726ba75b186ce7ea08938f8e577a/upload/catalog/model/design/layout.php#L4

https://github.com/opencart/opencart/blob/7738462d64eb726ba75b186ce7ea08938f8e577a/upload/catalog/model/design/layout.php#L5

This error is related to PHP-8 type declarations.

**Server / Test environment:**
 - Local development
 - Operating system: Ubuntu 20.04.2
 - Apache 2.4.41
 - PHP 8.0.3
 - mySQL 8.0.23 
 - Google Chrome Stable 89.0.4389.82

**Comment by TheCartpenter** [comment]
```public function getLayout(string $route): int {```

to:

```public function getLayout(string $route): array {```

**Comment by mhcwebdesign** [comment]
No, it should be `public function getLayout(string $route): int {` !

**Comment by TheCartpenter** [comment]
Not sure why that IF statement is there anyway. Shouldn't it be a returned array like other model methods?

**Comment by SaifAlSubhi** [comment]
Is it because the call from one of the below?
It calls from string then it get a string! ... not sure

https://github.com/opencart/opencart/blob/7738462d64eb726ba75b186ce7ea08938f8e577a/upload/catalog/controller/common/content_top.php#L42

https://github.com/opencart/opencart/blob/7738462d64eb726ba75b186ce7ea08938f8e577a/upload/catalog/controller/common/content_bottom.php#L42

https://github.com/opencart/opencart/blob/7738462d64eb726ba75b186ce7ea08938f8e577a/upload/catalog/controller/common/column_left.php#L42

https://github.com/opencart/opencart/blob/7738462d64eb726ba75b186ce7ea08938f8e577a/upload/catalog/controller/common/column_right.php#L42

**Comment by mhcwebdesign** [comment]
There is nothing wrong with these queries. It seems nobody else can reproduce your error, so something else must have gone wrong with your OC server because it thinks that the '$this->db' is a string instead of the expected database object.

**Comment by SaifAlSubhi** [comment]
> There is nothing wrong with these queries. It seems nobody else can reproduce your error, so something else must have gone wrong with your OC server because it thinks that the '$this->db' is a string instead of the expected database object.

Hi mhcwebdesign,
There is still an existing error:
```
TypeError: Opencart\System\Engine\Registry::get(): Return value must be of type object, string returned in system/engine/registry.php on line 25
```

Actually, I got this this subject error after I modified the type from object to object|string in these 3 lines:

https://github.com/opencart/opencart/blob/08d6cf8eb36fa6d0aa38c80c3787b88754060f20/upload/system/engine/registry.php#L24

https://github.com/opencart/opencart/blob/08d6cf8eb36fa6d0aa38c80c3787b88754060f20/upload/system/engine/controller.php#L21

https://github.com/opencart/opencart/blob/08d6cf8eb36fa6d0aa38c80c3787b88754060f20/upload/system/engine/model.php#L21

**Comment by SaifAlSubhi** [comment]
@mhcwebdesignI think this error is caused by the return type from:
https://github.com/opencart/opencart/blob/08d6cf8eb36fa6d0aa38c80c3787b88754060f20/upload/system/engine/registry.php#L25

**Comment by mhcwebdesign** [comment]
@SaifAlSubhi: I think you are right. Can you try this for line 25:

`return isset($this->data[$key]) ? $this->data[$key] : null;`

**Comment by SaifAlSubhi** [comment]
> @SaifAlSubhi: I think you are right. Can you try this for line 25:
> 
> `return isset($this->data[$key]) ? $this->data[$key] : null;`

I tried it this morning, but I got this error:
```
TypeError: Opencart\System\Engine\Registry::get(): Return value must be of type object|string, null returned in /system/engine/registry.php on line 25
```

**Comment by mhcwebdesign** [comment]
@SaifAlSubhi: Perhaps this will do:

```
	public function get(string $key): object|null {
		return isset($this->data[$key]) ? $this->data[$key] : null;
	}
```

Try it!

**Comment by SaifAlSubhi** [comment]
> @SaifAlSubhi: Perhaps this will do:
> 
> ```
> 	public function get(string $key): object|null {
> 		return isset($this->data[$key]) ? $this->data[$key] : null;
> 	}
> ```
> 
> Try it!

I tried it with object|null in registry, model & controller. I got this error:
```
Error: Call to a member function query() on null in catalog/model/design/layout.php on line 5
```

**Comment by SaifAlSubhi** [comment]
@mhcwebdesign
I have question, please
Can we create some kind of a default value for $key to return if null?
```
return isset($this->data[$key]) ? $this->data[$key] : ''; 
```

**Comment by mhcwebdesign** [comment]
@SaifAlSubhi: Well, the default value should be null.

Your error

> Error: Call to a member function query() on null in catalog/model/design/layout.php on line 5

is caused elsewhere. For some reason by the time it calls the **getLayout** this registry has not yet set the 'db' to a appropriate DB driver, it should have done this in **system/framework.php** !

**Comment by SaifAlSubhi** [comment]
@mhcwebdesign
Hi again,
I think this because the call for Application in:
https://github.com/opencart/opencart/blob/08d6cf8eb36fa6d0aa38c80c3787b88754060f20/upload/system/engine/loader.php#L96
if it is 'Catalog' then the class will contains /catalog/ and if it is 'catalog' then an error:
Exception: Error: Could not load model Opencart\Catalog\Model\Setting\Store! in /system/engine/loader.php on line 116

It seems like isn't loading the extension.

**Comment by mhcwebdesign** [comment]
Strange because the 'Opencart\Catalog\Model\Setting\Store' clearly exists: https://github.com/opencart/opencart/blob/master/upload/catalog/model/setting/store.php

I still think the issue is elsewhere. When I have some time I dig deeper into it.

**Comment by TheCartpenter** [comment]
> @mhcwebdesign
> Hi again,
> I think this because the call for Application in:
> https://github.com/opencart/opencart/blob/08d6cf8eb36fa6d0aa38c80c3787b88754060f20/upload/system/engine/loader.php#L96
> 
> 
> if it is 'Catalog' then the class will contains /catalog/ and if it is 'catalog' then an error:
> Exception: Error: Could not load model Opencart\Catalog\Model\Setting\Store! in /system/engine/loader.php on line 116
> It seems like isn't loading the extension because of $route type call.

```$class = 'Opencart\\' . ucfirst($this->config->get('application')) . '\Model\\' . str_replace(['_', '/'], ['', '\\'], ucwords($route, '_/'));```

Since Windows Servers can translate upper case to lower case characters.

**Comment by mhcwebdesign** [comment]
@TheCartpenter: I just tested it on today's (20-03-2021) code of the master branch, and I am unable to replicate the error on our test server.

Using this:

    Linux Mint 18.3 (Kernel Linux 4.15.0-139-generic (x86_64))
    Apache/2.4.18 (Ubuntu)
    Database client version: libmysql - mysqlnd 8.0.3
    PHP version: 8.0.3

What are the exact steps to reproduce this error? Or has it now been fixed by Daniel?

**Comment by TheCartpenter** [comment]
Accurate results needs to be provided from live servers rather than virtual servers since virtual servers contains re-written libraries whereas live servers rather depends on Apache (or similar) and PHP updates based on the OS distributions and the restrictions being imposed by web server providers.

**Comment by SaifAlSubhi** [comment]
Hi mhcwebdesign & TheCartpenter,

This comment solved this error:
https://github.com/opencart/opencart/blob/98c0c95306c60169d2427eb7400ac017ba7fe427/upload/system/framework.php#L18

**Comment by TheCartpenter** [comment]
By doing that, it would also mean that the install/controller/install/step_3.php file might also need correction from:

```Model```

to:

```model```

in the APPLICATION constant in this case.

**Comment by mhcwebdesign** [comment]
@SaifAlSubhi: I added this change otherwise the **system/framework.php** at

```
$config->load('default');
$config->load(strtolower(APPLICATION));
```
would cause the **system/engine/config.php** to get a non-existing file name at

```
	public function load(string $filename): array {
		$file = $this->directory . $filename . '.php';
		....
```

and it would fail. E.g. $filename would be 'Install' instead of 'install', or 'Admin' instead of 'admin' etc.

The file systems on Linux or Unix are case sensitive, unlike Windows NTFS which can get a file or folder in a case-insensitive manner.

**Comment by mhcwebdesign** [comment]
> By doing that, it would also mean that the install/controller/install/step_3.php file might also need correction from:
> 
> `Catalog`
> 
> to:
> 
> `catalog`
> 
> in the APPLICATION constant in this case.

We shouldn't change it there, because APPLICATION is often used as part of a namespace where the parts start with a capital letter!

**Comment by SaifAlSubhi** [comment]
@mhcwebdesign, yes, we can close this issue.
Thanks

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart/issues/9414#issuecomment-799485480

**Comment by SaifAlSubhi** [comment]
> [#9414 (comment)](https://github.com/opencart/opencart/issues/9414#issuecomment-799485480)
Hi TheCartpenter,
if it is:
define('APPLICATION', 'catalog');
the it produces an error:
```
Exception: Error: Could not load model Opencart\catalog\Model\Extension\Opencart\Total\SubTotal! in /system/engine/loader.php on line 110
```

it should be 'Catalog'

**Comment by TheCartpenter** [comment]
If you try the solution from the posted comment about, with the ucfirst function, does it still provide the same error message?

**Comment by TheCartpenter** [comment]
When I think of it, even a regex won't be enough since the $this->config->get is pulled from the Engine on the master branch but does not validate if the actual path is existent since, with the use of $this->config->set, any extensions could re-alter the original path defined and could become catastrophic in the end. 

@danielkerr: What we'd need is a realpath function instead of simply strtolower or ucfirst in the model or callback to ensure that the path truly exists.

**Comment by SaifAlSubhi** [comment]
@TheCartpenter
sorry, I missed to report this:
replacing line 96 by
```
$class = 'Opencart\\' . ucfirst($this->config->get('application')) . '\Model\\' . str_replace(['_', '/'], ['', '\\'], ucwords($route, '_/'));
```
still produce this error:
```
Error: Call to a member function query() on null in /catalog/model/design/layout.php on line 5
```

**Comment by TheCartpenter** [comment]
Then, this covers my theory. This is a problem since live servers may not be as pleased as virtual servers to load classes such ways since the second string part from the path is now user-defined as opposed to the automated ways prior.

Therefore, revert the changes and see in the system/startup.php file by changing the strtolower to ucfirst noticing the same issue or if it resolves it.

**Comment by SaifAlSubhi** [comment]
@TheCartpenter
Hi again,
using
```
$config->load(ucfirst(APPLICATION));
```
in system/framework.php
still producing the same subject error.

**Comment by SaifAlSubhi** [comment]
by the way, this is my test environment and it is the only setup I have:

ubuntu 20.04.2
apache 2.4.41
PHP 8.0.3
mySQL 8.0.23
Google Chrome Stable 89.0.4389.90

**Comment by danielkerr** [comment]
it does not need ucfirst(APPLICATION)

**Comment by mhcwebdesign** [comment]
@SaifAlSubhi: I agree with Daniel, no need here to use the ucfirst(APPLICATION). Your error message is clear, for some reason you don't a DB connection. Please check your DB settings, e.g. add this in your local **system/framework.php**:

```
$db = new \Opencart\System\Library\DB($config->get('db_engine'), $config->get('db_hostname'), $config->get('db_username'), $config->get('db_password'), $config->get('db_database'), $config->get('db_port'));
echo "db='".print_r($db,true)."'"; // just to see whether the DB connection even works at all
```

If it shows there is a DB connection, then please provide us with the exact steps on how to replicate your error.

**Comment by SaifAlSubhi** [comment]
your last change did solved this error:
```
$config->load(strtolower(APPLICATION));
```

**Comment by mhcwebdesign** [comment]
Then let's keep this issue as closed. Problem solved.

**Comment by TheCartpenter** [comment]
Then, there's no point of sanitizing the IIS compatibility from system/startup.php file since the core will only be focusing on Linux / UNIX OSes rather than Windows and those includes virtual servers.

**Comment by mhcwebdesign** [comment]
Windows IIS normally uses the NTFS file system for which this solution should be just fine.

If there is a specific server configuration still experiencing this particular issue, then please be more specific. If IIS has another issue, then please open a github issue report, again with the exact steps to replicate an error.

**Comment by TheCartpenter** [comment]
While I am not too sure where the NTFS information comes with path or URL sensitive / insensitive cases, followed is what I am rather referring about: https://webmasters.stackexchange.com/questions/90339/why-are-urls-case-sensitive?answertab=active#tab-top .

**Comment by TheCartpenter** [comment]
In addition, since this commit is specifically about path case sensitivity, followed is the specific representation of what I am definitely talking about: https://webmasters.stackexchange.com/revisions/90378/1 .
