### ISSUE TITLE
3.0.3.7 installer can't load PDO adaptor 

### ISSUE THREAD

**Issue by ADDCreative** [opencart/opencart#9420]
The PDO database adaptor in the installer was renamed from mpdo to pdo in this commit.
https://github.com/opencart/opencart/commit/e33355b2d722abe3cd31c076c33e3afbf3b9776d#diff-02eb909d6d0c8a4c896d034f13fd2ecead9eac6a26fc4693cdfd6c3b38d9cc1a

However, the actual file and class wasn't renamed.
https://github.com/opencart/opencart/blob/2a5b358003d1e9e4af964eda2ffcb79abe8229ce/upload/system/library/db/mpdo.php#L3

This will give the error "Error: Could not load database adaptor mPDO".
https://forum.opencart.com/viewtopic.php?f=199&t=222883

**Comment by condor2** [comment]
There are more things to do....before release of 3.0.3.8...but some active members doesn't have commit access and Webkul company doesn't care or wait review from Daniel.

Like:
- delete some files from db library
- twig update (and remove deprecated klarna)
- some bootstrap and jquery update
- summernote editor update...

For example no one 
https://github.com/opencart/opencart/pull/9256

**Comment by WebkulOpencart** [comment]
@condor2 As we update the libraries etc only after the Daniel confirmation.
we are checking each and every point  of this issue and will update here

**Comment by WebkulOpencart** [comment]
@condor2 As I checked for the review event there is no need for this event, the send mail code is already in the model file.
[https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/model/catalog/review.php#L23](https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/model/catalog/review.php#L23)

**Comment by condor2** [comment]
I don't think Daniel have time or cares about 3.0.x.x right now.

As per review event it is necessary because admin never receive notification email when customer write a review....
https://github.com/opencart/opencart/blob/master/upload/install/opencart.sql#L754

**Comment by WebkulOpencart** [comment]
@condor2 You can check on the below file, review mail will send to the admin.
https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/model/catalog/review.php#L31

**Comment by condor2** [comment]
You have testedt?

**Comment by ADDCreative** [comment]
> You have testedt?

I've just tested in 3.0.3.7. The email to the admin when a customer writes a review works fine for me. You need tick Reviews in the Alert Mail setting in the Mail tab. But it does work,

The email is sent by the code below.
https://github.com/opencart/opencart/blob/bb0598cab873e9a922cb7911ab7dbc71c42ebd96/upload/catalog/model/catalog/review.php#L3-L48

Your pull request https://github.com/opencart/opencart/pull/9350 looks wong to me as there is no 'mail/review' controller in 3.0.3.7 for the event to call.
