### ISSUE TITLE
3.0.x Maintenance > URL does not exist!

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#9422]
https://github.com/opencart/opencart/blob/3b24001a0b0f5c8bcc5f1ebf121d1abffd363664/upload/admin/language/en-gb/extension/payment/amazon_login_pay.php#L39

**Comment by WebkulOpencart** [comment]
@danielkerr As I checked many blogs and found the below blog for the same.
[https://pay.amazon.com/help/201828820](https://pay.amazon.com/help/201828820)

Please confirm if we can change the URL with the same

**Comment by WebkulOpencart** [comment]
PR [https://github.com/opencart/opencart/pull/9754](https://github.com/opencart/opencart/pull/9754)

**Comment by danielkerr** [comment]
It's not on master branch.

**Comment by danielkerr** [comment]
No idea why it was tagged
