### ISSUE TITLE
Opencart marketplace is compromised!

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#9428]
**What version of OpenCart are you reporting this for?**
Version 3.0.x, 2.x, 1.5.x

**Describe the bug**
When going to the opencart.com marketplace you'll notice a daily spammer/thief advertising lots of stolen OpenCart extensions.
See https://forum.opencart.com/viewtopic.php?f=26&t=222607&p=816669#p814694 for more details.
This makes the built-in OC 3.0.x extension/marketplace useless, because users will just buy an extension at a fraction of the original price from this spammer/thief.

**Expected behavior**
Please implement a proper anti-spambot or captcha for the opencart.com marketplace comments section.

**Comment by IP-CAM** [comment]
Or then, at least as a temporary Solution, disable the 'commenting' Sections of the Extension Pages, this Fellow is killing the Mood of any Extension Creator, to further offer anything on that Site. And as a Result of that, OC will no longer earn any Profit out of selling Extensions either.

**Comment by IP-CAM** [comment]
And just to round up this OC Extension Page Scam Matter, after checking around a little, I found out, that this Place would really require someone, to clean up, what has been added to on Garbage and wrongly declared Items, during the past few months.  It's a shame, that nobody seems to care about such anymore. 
[one simple sample](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=41171)

**Comment by mhcwebdesign** [comment]
I am afraid I have to re-open this issue, because the notorious spammer and Opencart software thief is back spamming the opencart.com marketplace under the user name yervioa (the latter will probably change daily).

Why won't opencart.com implement a proper captcha or anit-spambot tool?

**Comment by stalker780** [comment]
Is it a big problem to add google recapcha 2 or 3 to comments?
This spamming last for about 2 years.

**Comment by IP-CAM** [comment]
The OC Extension Sections are already full of it ...
Sample Page
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=38358

**Comment by mhcwebdesign** [comment]
There hasn't been any comment spamming for the past few weeks, so I am closing this issue.
