### ISSUE TITLE
Timezone config

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#9432]
https://github.com/opencart/opencart/blob/08d6cf8eb36fa6d0aa38c80c3787b88754060f20/upload/admin/controller/startup/setting.php#L20

Should this line be addressed regarding the time zone setting as well?

**Comment by WebkulOpencart** [comment]
@TheCartpenter  Yes, this function is used to set the time zone within the script where we need to call the date/time function
Please refer to blog here [https://www.php.net/manual/en/function.date-default-timezone-set.php](https://www.php.net/manual/en/function.date-default-timezone-set.php)
