### ISSUE TITLE
Showing price 0 in all place

### ISSUE THREAD

**Issue by vishvakamal** [opencart/opencart#9457]
**Opencart 3.0.3.7**

**Describe the bug**
I have found that product price is showing 0 in all places. There is showing special price with 0 but actually there is not any special price in admin area.

**Expected behavior**
Actual price should show.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? - Deployed on web server
 - PHP version - 7.2

I have checked code and find some line of code from where I think raise issue.
if (!is_null($result['special']) && (float)$result['special'] >= 0) {
	$special = $this->currency->format($this->tax->calculate($result['special'], $result['tax_class_id'], $this->config->get('config_tax')), $this->session->data['currency']);
	$tax_price = (float)$result['special'];
} else {
	$special = false;
	$tax_price = (float)$result['price'];
}

whereas in previous version this code was like:
if ((float)$product_info['special']) {
$data['special'] = $this->currency->format($this->tax->calculate($product_info['special'], $product_info['tax_class_id'], $this->config->get('config_tax')), $this->session->data['currency']);
} else {
$data['special'] = false;
}

**Comment by prabhatkumaroc082** [comment]
@vishvakamal 
apply these fixes (https://github.com/opencart/opencart/commit/093607623cf67adff5ab0b19be90bc0f171c1805#diff-a53fa184b2d3611fba12fbd1b4415b5428091942fb1fdcea88422dbf0fc7fe3f) everywhere, then you should not face such issues. 
3.0.3.7 is having this issue, soon a new version will be released including these fixes.

**Comment by vishvakamal** [comment]
Even infomration/tracking URL is not working. Can you please look at there and let me knnow how that work?

**Comment by prabhatkumaroc082** [comment]
@vishvakamal 
Opencart doesn't support it on the latest release.

**Comment by vishvakamal** [comment]
Hello mates,

I face one more issue here. If I select timezone America/New_York in admin area and then logged out and try to loggin again then I can logged in. Frnt-end is working fine but admin stopped to working.

Thanks in Advance

**Comment by ADDCreative** [comment]
> Hello mates,
> 
> I face one more issue here. If I select timezone America/New_York in admin area and then logged out and try to loggin again then I can logged in. Frnt-end is working fine but admin stopped to working.
> 
> Thanks in Advance

You have posted in completely the wrong place. See. https://forum.opencart.com/viewtopic.php?f=201&t=222369&start=20#p816440
