### ISSUE TITLE
Upgrade errors

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#9458]
master

**Describe the bug**
upgrade error

**To Reproduce**
run upgrade

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/12296392/111357710-98b4bf80-869a-11eb-9633-764ff1b806a8.png)

**Server / Test environment (please complete the following information):**
 - Local development
 - PHP version 8
 - Apache version 2.4
 
**Additional context**
SyntaxError: Unexpected token < in JSON at position 0 OK Warning: Constant DIR_OPENCART already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 27Warning: Constant DIR_APPLICATION already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 28Warning: Constant DIR_EXTENSION already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 29Warning: Constant DIR_IMAGE already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 30Warning: Constant DIR_SYSTEM already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 31Warning: Constant DIR_STORAGE already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 32Warning: Constant DIR_LANGUAGE already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 33Warning: Constant DIR_TEMPLATE already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 34Warning: Constant DIR_CONFIG already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 35Warning: Constant DIR_CACHE already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 36Warning: Constant DIR_DOWNLOAD already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 37Warning: Constant DIR_LOGS already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 38Warning: Constant DIR_SESSION already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 39Warning: Constant DIR_UPLOAD already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 40Warning: Constant DB_DRIVER already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 43Warning: Constant DB_HOSTNAME already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 44Warning: Constant DB_USERNAME already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 45Warning: Constant DB_PASSWORD already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 46Warning: Constant DB_DATABASE already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 47Warning: Constant DB_PORT already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 48Warning: Constant DB_PREFIX already defined in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 49Warning: Undefined array key "DIR_OPENCART" in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 86Warning: Undefined array key "db_driver" in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 110Warning: Undefined array key "db_hostname" in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 111Warning: Undefined array key "db_username" in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 112Warning: Undefined array key "db_password" in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 113Warning: Undefined array key "db_database" in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 114Warning: Undefined array key "db_port" in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 115Warning: Undefined array key "db_prefix" in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 116Warning: Undefined variable $missing in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 122TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in C:\OpenServer\domains\oc4.develop\upload\install\model\upgrade\upgrade_1001.php on line 122

**Comment by danielkerr** [comment]
closing as there is zero information about w2hich version the upgrade was being done from or to.
