### ISSUE TITLE
Change Request on Product Page

### ISSUE THREAD

**Issue by adelante25** [opencart/opencart#9461]
Hello dear Opencart developers, I just met Opencart and therefore I am very pleased.
I'm not a developer and I'm trying to learn something new. I own the Opencart store and use Journal3 theme. but I need a change on the product page and I don't know how to do it or what to do. I hope you will be your guide on this matter.
That is to say; I want to upload my products one by one in the admin panel, and I want to combine the same products with the product code on the front end, that is, on the product page in the store. I want to make this link available at https://www.loom.com/share/6d85be27a82c45eba1afac67b4dead6d. So I want my products to look like https://www.loom.com/share/6d85be27a82c45eba1afac67b4dead6d. I want my products with different color and size but the same product code to appear on the product page in this way.
I would like to thank those who will help and everyone who contributed to Opencart. Good luck.

**Comment by stalker780** [comment]
Hi,

As you have correctly mentioned, here is an OpenCart development portal. It is not related neither to Journal theme nor to OpenCart customer support.

I would suggest you to create a topic in forum.opencart.com, but https://forum.opencart.com/viewtopic.php?f=2&t=221926

So an only way is to contact Journal3 support, or hire a developer, who knows this theme and can configure it correctly.

From my side, if you plan to add products yourself, I can suggest you to ask google about "working with opencart options" 
https://youtube.com/watch?v=5eI_tx4kA1s

**Comment by adelante25** [comment]
> Selam,
> 
> Doğru bir şekilde belirttiğiniz gibi, işte bir OpenCart geliştirme portalı. Ne Journal teması ne de OpenCart müşteri desteği ile ilgili değildir.
> 
> Forum.opencart.com'da bir konu oluşturmanızı öneririm, ancak https://forum.opencart.com/viewtopic.php?f=2&t=221926
> 
> Bu yüzden tek yol, Journal3 desteğiyle iletişim kurmak veya bu temayı bilen ve doğru şekilde yapılandırabilen bir geliştirici tutmaktır.
> 
> Benim açımdan, ürünleri kendiniz eklemeyi planlıyorsanız, google'a "opencart seçenekleriyle çalışma" hakkında soru sormanızı önerebilirim
> https://youtube.com/watch?v=5eI_tx4kA1s

Hello there; I talked to journal3 theme developer. He suggested that the arrangement I requested is not related to the theme, that the basic functions of the opencart need to be changed, so if we ask an opencart developer, I should buy it. As can be seen from the video in my message, I think there is a need for a change in product.twig and I wonder how this change will be made or whether it will be in future updates. Also this is a feature recommendation.

**Comment by WebkulOpencart** [comment]
@adelante25 you want a custom functionality as per your requirement, If you want such type of functionality then we can do the same using hourly customization which will be paid. You can contact our sales team at sales@webkul.com

This project is related to the ongoing OpenCart versions, so I am closing this issue.

**Comment by osworx** [comment]
> 
> 
> @adelante25 you want a custom functionality as per your requirement, If you want such type of functionality then we can do the same using hourly customization which will be paid. You can contact our sales team at [sales@webkul.com](mailto:sales@webkul.com)
> 
> This project is related to the ongoing OpenCart versions, so I am closing this issue.

Nice this promotion, but it should be asked here: https://forum.opencart.com/viewforum.php?f=88
