### ISSUE TITLE
PayPal Payments Standard do not send shipping data to PayPal

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#9463]
PayPal Payments Standard do not send shipping data (shipper's name, shipping address... ) to PayPal.
PayPal seller protection will not protect it.
please help.
 any opencart version.

**Comment by chongshengdz** [comment]
please don't suggest to use PayPal Commerce Platform.
it only supports some countries, not all.

**Comment by TheCartpenter** [comment]
Forum request.

**Comment by webkul-dilip** [comment]
> PayPal Payments Standard do not send shipping data (shipper's name, shipping address... ) to PayPal.
> PayPal seller protection will not protect it.
> please help.
> any opencart version.

We have checked and found the issue, we are working on the issue.

  <input type="hidden" name="no_shipping" value="1" />
https://github.com/opencart/opencart/blob/d3dba614861d2003775eef73a65e87c43e384947/upload/catalog/view/theme/default/template/extension/payment/pp_standard.twig#L40
http://i.prntscr.com/OXjOcyiARvikoLdACG6g6g.png

**Comment by ADDCreative** [comment]
@webkul-dilip Note with your pull the shipping address still isn't passed. Your pull request just forces PayPal to use the OpenCart payment address as the shipping address. If the customer needs a different shipping address to the payment address they have to enter it again. If the customer doesn't notice this and the store owner uses the address in PayPal, they could end up sending the order to the wrong address.

Also, setting no_shipping to a value other than 1 also causes issues for store owners who use the shipping address from OpenCart. If the customer changes the shipping address on the PayPal payment page, this actually isn't sent back to OpenCart, so the the store owner ends up sending the order to the wrong address.

To stop the two above scenarios from happening you can set address_override to 1. But you need to pass the shipping address.
https://developer.paypal.com/docs/paypal-payments-standard/integration-guide/formbasics/#overriding-addresses-stored-with-paypal

If you are going to set no_shipping to 2 you probably need to set address_override to 1 and pass the OpenCart shipping address.

As PayPal acts differently in different countries and many don't have seller protection. Maybe it's best to give the store owner the option of sending either the payment or the shipping address and allowing them to chose their desired no_shipping address_override values.

**Comment by chongshengdz** [comment]
> @webkul-dilip Note with your pull the shipping address still isn't passed. Your pull request just forces PayPal to use the OpenCart payment address as the shipping address. If the customer needs a different shipping address to the payment address they have to enter it again. If the customer doesn't notice this and the store owner uses the address in PayPal, they could end up sending the order to the wrong address.
> 
> Also, setting no_shipping to a value other than 1 also causes issues for store owners who use the shipping address from OpenCart. If the customer changes the shipping address on the PayPal payment page, this actually isn't sent back to OpenCart, so the the store owner ends up sending the order to the wrong address.
> 
> To stop the two above scenarios from happening you can set address_override to 1. But you need to pass the shipping address.
> https://developer.paypal.com/docs/paypal-payments-standard/integration-guide/formbasics/#overriding-addresses-stored-with-paypal
> 
> If you are going to set no_shipping to 2 you probably need to set address_override to 1 and pass the OpenCart shipping address.
> 
> As PayPal acts differently in different countries and many don't have seller protection. Maybe it's best to give the store owner the option of sending either the payment or the shipping address and allowing them to chose their desired no_shipping address_override values.

there is no problem with opencart shipping address.

**Comment by ADDCreative** [comment]
> there is no problem with opencart shipping address.
What do you mean?

**Comment by chongshengdz** [comment]
> > there is no problem with opencart shipping address.
> 
> What do you mean?

OPENCART has an option to choose or enter a shipping adress or payment address.
so override shipping adress to PayPal is ok.

**Comment by webkul-dilip** [comment]
> @webkul-dilip Note with your pull the shipping address still isn't passed. Your pull request just forces PayPal to use the OpenCart payment address as the shipping address. If the customer needs a different shipping address to the payment address they have to enter it again. If the customer doesn't notice this and the store owner uses the address in PayPal, they could end up sending the order to the wrong address.
> 
> Also, setting no_shipping to a value other than 1 also causes issues for store owners who use the shipping address from OpenCart. If the customer changes the shipping address on the PayPal payment page, this actually isn't sent back to OpenCart, so the the store owner ends up sending the order to the wrong address.
> 
> To stop the two above scenarios from happening you can set address_override to 1. But you need to pass the shipping address.
> https://developer.paypal.com/docs/paypal-payments-standard/integration-guide/formbasics/#overriding-addresses-stored-with-paypal
> 
> If you are going to set no_shipping to 2 you probably need to set address_override to 1 and pass the OpenCart shipping address.
> 
> As PayPal acts differently in different countries and many don't have seller protection. Maybe it's best to give the store owner the option of sending either the payment or the shipping address and allowing them to chose their desired no_shipping address_override values.

As I checked I did not found the option to send shipping address separately in documents. We can send the address only, so either we can use same address or either we can override it.   We have noted your point, we will update code shortly.

>>As PayPal acts differently in different countries and many don't have seller protection. Maybe it's best to give the store owner the option of sending either the payment or the shipping address and allowing them to chose their desired no_shipping address_override values.
 
We will provide the option  manage it to the admin.
Thanks

**Comment by ADDCreative** [comment]
@webkul-dilip I think the following would be enough and a quicker fix then adding all the option that might be too confusing for store owners to set up correctly.

```
If hasShipping
     set address fields with shipping address
     set no_shipping to 2
     set address_override to 1
else
     set address fields with payment address
     set no_shipping to 1
     set address_override to 0
```

**Comment by webkul-dilip** [comment]
> @webkul-dilip I think the following would be enough and a quicker fix than adding all the options that might be too confusing for store owners to set up correctly.
> 
> ```
> If hasShipping
>      set address fields with shipping address
>      set no_shipping to 2
>      set address_override to 1
> else
>      set address fields with payment address
>      set no_shipping to 1
>      set address_override to 0
> ```

We have implemented the code now.
Thanks

**Comment by chongshengdz** [comment]
state or province is necessary to send to PayPal.
Please add it
