### ISSUE TITLE
Tax duplicated in shipping quote

### ISSUE THREAD

**Issue by ADDCreative** [opencart/opencart#9465]
When getting a shipping quote it's possible for the price shown in the pop up to be wrong due to duplicate tax rates being added to the value.

To recreate from default settings.

1. Add a new Geo Zone with a different country to the one already set up.
2. Add a new 20% tax rate and assign it to the new geo zone.
3. Edit the Taxable Goods tax class and change the Eco Tax to the new tax rate and save.
4. In the storefront add a product to cart and go to the shopping cart.
5. Estimate Shipping & Taxes, selecting the country added to the new geo zone.
6. Pop up will show Flat Shipping Rate - $7.00 when it should be $6.00 ($5 + 20% tax).

The issue seems to be that ```tax->setShippingAddress``` is called in the quote.
https://github.com/opencart/opencart/blob/d3dba614861d2003775eef73a65e87c43e384947/upload/catalog/controller/extension/total/shipping.php#L69

However, tax->setShippingAddress doesn't clear the existing tax rates. So you end up with both tax rates for the session address and from the estimate shipping form address.
https://github.com/opencart/opencart/blob/d3dba614861d2003775eef73a65e87c43e384947/upload/system/library/cart/tax.php#L15-L27

This affects both the master and 3.0.x.x_Maintenance branches (and version 2.x).

**Comment by TheCartpenter** [comment]
If the case, then catalog/controller/startup files would also need to be checked with the setShippingAddress to avoid its duplication in the process.

**Comment by webkul-dilip** [comment]
Hello,
Case 1--
Setting - http://i.prntscr.com/mPAz2jLZTTG_NmLi2L7K3w.png
Output-  http://i.prntscr.com/4CSXeLRYSiS6dX3gUZI4vQ.png

Case 2-- 
Setting - http://i.prntscr.com/mFbs_Hw2SQS3bRRuOIK_Dg.png
Output - http://i.prntscr.com/fvcARqImS9a4dH9yN6OHcQ.png

Case 3 
Setting - http://i.prntscr.com/JiqUIM9rS_SrB_Uz1A37ew.png
              http://i.prntscr.com/d4UJY6WFTY21g9IcgsAxqg.png
              http://i.prntscr.com/I2kaVpulRvarjEmi2KIMOQ.png
Output    http://i.prntscr.com/0YQBNIsvSwGSTr1CUaJcQA.png

As we checked, we did not found any issue.

Thanks

**Comment by ADDCreative** [comment]
@webkul-dilip You have not tested correctly. You need to switch between a country in the existing geo zone and one in the new geo zone. So the session has a country from the first tax rate zone and the estimate for a country in the new one.

**Comment by Webkul-Opencart** [comment]
@ADDCreative We have found an issue related to the "the session has a country from the first tax rate zone" & fixed for the same-- https://github.com/opencart/opencart/pull/9564

**Comment by ADDCreative** [comment]
@Webkul-Opencart @webkul-dilip Sadly the fix is not that simple (otherwise I would have quickly done a pull request myself). Now with your change, if there is a tax that in the tax class that is based on the payment address, that tax will not get added to the quote. If you are going to unsetRates you will possibly need to setPaymentAddress and well as shipping.

Also this issue affects the master, should it not be left open until it's fixed on both branches? I've seen a few issues lately that have been fix on one branch and not the other, then closed.

**Comment by webkul-dilip** [comment]
> @Webkul-Opencart @webkul-dilip Sadly the fix is not that simple (otherwise I would have quickly done a pull request myself). Now with your change, if there is a tax that in the tax class that is based on the payment address, that tax will not get added to the quote. If you are going to unsetRates you will possibly need to setPaymentAddress and well as shipping.
> 
> Also this issue affects the master, should it not be left open until it's fixed on both branches? I've seen a few issues lately that have been fix on one branch and not the other, then closed.

Hello,
As we checked on the code end there only set the setShippingAddress, I think the shipping quote should only apply based on the shipping address.
If we think about the Tax configuration then we need to add setStoreAddress and setPaymentAddress as well.
Thanks

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart/issues/9465#issuecomment-803198921

**Comment by webkul-dilip** [comment]
@ADDCreative  New pull request for changes https://github.com/opencart/opencart/pull/9567

**Comment by ADDCreative** [comment]
@webkul-dilip Setting the payment address from the form would override the customer's payment address for tax calculations. You would maybe need to do this.

```php
$this->tax->unsetRates();

$this->tax->setShippingAddress($this->request->post['country_id'], $this->request->post['zone_id']);

if (isset($this->session->data['payment_address']['country_id']) && isset($this->session->data['payment_address']['zone_id'])) {
	$this->tax->setPaymentAddress($this->session->data['payment_address']['country_id'], $this->session->data['payment_address']['zone_id']);
} elseif ($this->config->get('config_tax_default') == 'payment') {
	$this->tax->setPaymentAddress($this->config->get('config_country_id'), $this->config->get('config_zone_id'));
}

$this->tax->setStoreAddress($this->config->get('config_country_id'), $this->config->get('config_zone_id'));
```

**Comment by webkul-dilip** [comment]
> @webkul-dilip Setting the payment address from the form would override the customer's payment address for tax calculations. You would maybe need to do this.
> 
> ```
> $this->tax->unsetRates();
> 
> $this->tax->setShippingAddress($this->request->post['country_id'], $this->request->post['zone_id']);
> 
> if (isset($this->session->data['payment_address']['country_id']) && isset($this->session->data['payment_address']['zone_id'])) {
> 	$this->tax->setPaymentAddress($this->session->data['payment_address']['country_id'], $this->session->data['payment_address']['zone_id']);
> } elseif ($this->config->get('config_tax_default') == 'payment') {
> 	$this->tax->setPaymentAddress($this->config->get('config_country_id'), $this->config->get('config_zone_id'));
> }
> 
> $this->tax->setStoreAddress($this->config->get('config_country_id'), $this->config->get('config_zone_id'));
> ```

Okay, we will update it shortly.
Thanks
