### ISSUE TITLE
OpenCart

### ISSUE THREAD

**Issue by hengsil** [opencart/opencart#9466]
After installing the New Opencart - version 3.0.3.7
Right after the translation I can't log in to my admin panel
nor modify the panel password by resetting my email (even using phpmyadmin)

**Comment by TheCartpenter** [comment]
Error / Server access logs.

**Comment by TheCartpenter** [comment]
This issue may also be caused by time zone setting issues. See this solution: https://forum.opencart.com/viewtopic.php?f=201&t=222369&p=817086#p817086
