### ISSUE TITLE
Cannot upload images.

### ISSUE THREAD

**Issue by solkmaaker** [opencart/opencart#9467]
Version  3.0.3.7

Clean fresh install.
Image editor does not open.

`VM1422:4 Uncaught SyntaxError: missing ) after argument list
    at eval (<anonymous>)
    at Function.globalEval (jquery-2.1.1.min.js:2)
    at n.fn.init.domManip (jquery-2.1.1.min.js:3)
    at n.fn.init.append (jquery-2.1.1.min.js:3)
    at Object.success (common.js:140)
    at j (jquery-2.1.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.1.1.min.js:2)
    at x (jquery-2.1.1.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.1.1.min.js:4)`

**Comment by WebkulOpencart** [comment]
@solkmaaker Please let me know on which page you are facing such an issue.
I checked for the product, category, option, manufacturer pages but not found such issue.

**Comment by solkmaaker** [comment]
It was on product page, when clicking image, buttons appear (edit and delete), but when to click edit button, nothing happens and browser (chrome) console displays error message.

**Comment by WebkulOpencart** [comment]
@solkmaaker I didn't found such an issue for the main product image and additional images as well.
https://prnt.sc/10u004s

Please check the code from 3.0.x.x_Maintenance branch

**Comment by solkmaaker** [comment]
Hello

I made a screen cast about this.
https://youtu.be/XjPPxgVLkWM

Server logs have no errors.
But server (apache) runs in chroot jail and uses  MPM ITK if that matters.
Cant figure why it should,since it is javascript error and happens in client side.
But maybe it does.

**Comment by WebkulOpencart** [comment]
@solkmaaker We still don't face any such issues. You can also report on the OpenCart form for the same.
