### ISSUE TITLE
There is a bug when validating customer required customer fields in Sale / Edit order

### ISSUE THREAD

**Issue by dupuisv** [opencart/opencart#9476]
the request in admin/sale/edit  doesn't seem to post the custom_fields the same way like the account editing form

So i add to modify the custom_field validation in catalog/api/customer.php

adding a another empty condition

&& empty($this->request->post['custom_field'][$custom_field['custom_field_id']])  // RDU fix for sale form

May be can Daniel have a look. my Customer have to mandatory fields (birthday and gender)

			foreach ($custom_fields as $custom_field) {
				if ($custom_field['location'] == 'account') { 
					if ($custom_field['required'] && empty($this->request->post['custom_field'][$custom_field['location']][$custom_field['custom_field_id']])
					    && empty($this->request->post['custom_field'][$custom_field['custom_field_id']])  // RDU fix for sale form
					) {
						$json['error']['custom_field' . $custom_field['custom_field_id']] = sprintf($this->language->get('error_custom_field'), $custom_field['name']);
					} elseif (($custom_field['type'] == 'text') && !empty($custom_field['validation']) && !filter_var($this->request->post['custom_field'][$custom_field['location']][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation'])))) {
						$json['error']['custom_field' . $custom_field['custom_field_id']] = sprintf($this->language->get('error_custom_field'), $custom_field['name']);
					}
				}
			}

**Comment by TheCartpenter** [comment]
Addressed issue already fixed on the master branch.

**Comment by prabhatkumaroc082** [comment]
Duplicate issue, #9253 
Try applying the following PR changes 
https://github.com/opencart/opencart/pull/9358
https://github.com/opencart/opencart/pull/9464
