### ISSUE TITLE
Add order without incorrect mail settings cause ERROR

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#9477]
OpenCart v3.0.3.2

Problem:
When OpenCart try to send message with wrong mail settings it show POP UP error.
Error stop processing request example: adding new order

Example:
Mail server is offline for few minutes and customer have that kind of problem.

Solution:
Please add try {} except to avoid any blocking of there any problem with mail server (offline, wrong settings etc...).

**Comment by TheCartpenter** [comment]
Server-specifics.

**Comment by ADDCreative** [comment]
If you are getting a pop up then you display error settings are wrong.

I believe this has been reported before. https://github.com/opencart/opencart/issues/7633

**Comment by WebkulOpencart** [comment]
Please report on the OpenCart forum.

**Comment by faca5** [comment]
How to reproduce:
1. System > Settings > Edit > tab Mail
Mail protocol: SMTP
SMTP host: 127.0.0.2 (testing purpose)
2. Try to send any message from store (history, contact, order etc.)
3. You will get POP UP with error which block 

You will get:
![1](https://user-images.githubusercontent.com/11090866/112264355-0fd8ed80-8c71-11eb-872f-693c10504687.png)



Settings are CORRECT!!!


You can get these error(s):
- server settings example: Error: RCPT TO not accepted from server!
- mail server offline
- wrong mail settings
- etc.

You need bypass this error without breaking store.

**Comment by faca5** [comment]
Problem "Error: RCPT TO not accepted from server!" was related with PHP 8.

But still similar error show when REMOTE MAIL SERVER is offline/unavailable and block customer to add new order.
It this ... just skip error if DEBUG mode OFF.

**Comment by ADDCreative** [comment]
@danielkerr @WebkulOpencart This can be an issue, No mail server is ever going to be 100% reliable. As the exceptions thrown by the SMTP mail class will stop execution of the rest of the code and the trigger for the mail event is before (catalog/model/checkout/order/addOrderHistory/before). It means the order status doesn't get updated, so the order goes as missing.

@faca5 Are you able to use the Mail as the Mail Engine? That one does not throw exceptions.

**Comment by faca5** [comment]
Yes! But we use SMTP to avoid message marked as SPAM. Last year many messages "order_add" has been marked as SPAM on @gmail.com. Now we are using SMTP to avoid this problem. Not all user has been marked as spam only few.
Problem with spam it could be with latest version of PHP, library or other changes because before works years and years without problem. Other mail like "history" was not marked as SPAM.

**Comment by TheCartpenter** [comment]
> Yes! But we use SMTP to avoid message marked as SPAM. Last year many messages "order_add" has been marked as SPAM on @gmail.com. Now we are using SMTP to avoid this problem. Not all user has been marked as spam only few.
> Problem with spam it could be with latest version of PHP, library or other changes because before works years and years without problem. Other mail like "history" was not marked as SPAM.

Wise decision!

**Comment by ADDCreative** [comment]
> Yes! But we use SMTP to avoid message marked as SPAM. Last year many messages "order_add" has been marked as SPAM on @gmail.com. Now we are using SMTP to avoid this problem. Not all user has been marked as spam only few.
> Problem with spam it could be with latest version of PHP, library or other changes because before works years and years without problem. Other mail like "history" was not marked as SPAM.

It was probably server set up. If configured correctly for your email, shouldn't be any difference between Mail and SMTP.

**Comment by osworx** [comment]
> It was probably server set up. If configured correctly for your email, shouldn't be any difference between Mail and SMTP.

Well. not true.
There are massive differences between the native mail and SMTP .. and you should know that - or?
The biggest "advantage" of using SMTP (when configured correctly) is the usage of e.g. DKIM, SPDIF and more.
Also virus scanner - if used.
So at least, SMTP should be used in all cases and preferred to the native mail MTA.

Native mail is only php and has very spare security and so on.

**Comment by ADDCreative** [comment]
> Well. not true.
> There are massive differences between the native mail and SMTP .. and you should know that - or?
> The biggest "advantage" of using SMTP (when configured correctly) is the usage of e.g. DKIM, SPDIF and more.
> Also virus scanner - if used.
> So at least, SMTP should be used in all cases and preferred to the native mail MTA.
> 
> Native mail is only php and has very spare security and so on.

It is true. On the servers I've used, all emails sent via the PHP mail function are DKIM signed and pass SPF, etc. Because they pass through the same MTA as the one sent via SMTP. As I said it down to server set up.

**Comment by TheCartpenter** [comment]
While those protocols might be dealt by server-specifics, it does not mean they're being used as standardized solutions which still depends on the hosting service levels being used from.
