### ISSUE TITLE
Empty tag

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#9482]
https://github.com/opencart/opencart/blob/c2170632c64b5241414a1f8cbd09cc205a07ca79/upload/catalog/controller/product/product.php#L455

if (trim($tag)) 
					$data['tags'][] = [
						'tag'  => trim($tag),
						'href' => $this->url->link('product/search', 'language=' . $this->config->get('config_language') . '&tag=' . trim($tag))
					];

**Comment by TheCartpenter** [comment]
I would not suggest this change.

**Comment by chulcha** [comment]
> 
> 
> I would not suggest this change.

Whe?

site/index.php?route=product/search&tag=
Is this a good link?

**Comment by TheCartpenter** [comment]
I am not referring about the string output. I am referring the ```if (trim(``` . That is not good practice to validate trailed spaces in a string.

**Comment by chulcha** [comment]
not problem

```
			if ($product_info['tag']) {
				$tags = explode(',', $product_info['tag']);
array_filter($tags,'trim');
				foreach ($tags as $tag) {
					if ($tag) {
						$data['tags'][] = array(
							'tag'  => trim($tag),
							'href' => $this->url->link('product/search', 'tag=' . trim($tag))
						);
					}
				}
			}
```

**Comment by TheCartpenter** [comment]
If you're using an array_filter prior to run a foreach statement, then why keep using the trim function during the loop?

**Comment by TheCartpenter** [comment]
Besides:

```$tags = explode(',', $product_info['tag']);```

could be replaced with:

```$tags = explode(',', trim($product_info['tag']));```

Then, to remove the array_filter line.

**Comment by chulcha** [comment]
See
http://sandbox.onlinephpfunctions.com/code/901e84f3970c6c48bf290fabb0c0a86a5f0fa18d

Of course, then you don't need if ($tag)
$tags = array_filter($tags,'trim');

**Comment by TheCartpenter** [comment]
3rd party website's view. Unrelated to this repository nor what the master or maintenance branch already provides.

**Comment by chulcha** [comment]
t's your problem that you don't want to watch live code and the result of its execution

**Comment by ADDCreative** [comment]
@chulcha If you want to trim the items in the array and remove the empty items, try.
```php
$tags = array_filter(array_map('trim', $tags));
```

**Comment by chulcha** [comment]
> ```
> $tags = array_filter(array_map('trim', $tags));
> ```
It's not obligatory
because

'tag'  => trim($tag),

**Comment by ADDCreative** [comment]
> > ```
> > $tags = array_filter(array_map('trim', $tags));
> > ```
> 
> It's not obligatory
> because
> 
> 'tag' => trim($tag),

Sorry, I thought you were trying to optimise to remove the multiple trims in the loop.

**Comment by TheCartpenter** [comment]
May be a model method should be used instead so that rather than extracting commas from the tags, Opencart is becoming more focused on JSON encoding on anyhow. Which means, rather than dealing with all these complications with explode, perhaps the ```json_decode($product_info['tags'], true)``` should be used as a result.

**Comment by chulcha** [comment]
For JSON  it is necessary to use an array, and the system is built to use the string.

You probably don't know and write any nonsense here.

If you want an array, then go change the getProducts model, for example, search by tags.
or product_form etc

**Comment by TheCartpenter** [comment]
Despite the nonsense opinion put in here, custom fields are already handled such ways from the core. The same could probably be suggested or done with the product tags without the need to edit the SQL queries but simply by rather adding the JSON decode function to the already pulled tag field from the database in the getProducts. Of course, the admin-end side would also need to have the JSON encode and decode when needed.

**Comment by chulcha** [comment]
Where did you see the custom fields?
Where did you see what I say need "to edit the SQL queries"

I talk and show how to get rid of a possibly empty link

**Comment by TheCartpenter** [comment]
Using an array, we don't need to deal with empty strings / links. That's the whole point of it.

As for editing the SQL queries, you mentioned to 'search by tags'. Perhaps you meant by filters?

As for the custom fields, I think it's pretty self-explanatory that custom fields are stored with JSON encoded strings on the database and being extracted with JSON encoding from the database into the models since ages.

**Comment by chulcha** [comment]
@TheCartpenter 
You will not enter the code OC.
Why are you writing here?

**Comment by TheCartpenter** [comment]
So to add, from the above, the master branch already trims the super global arrays from the request library whether it originates from an array or a string. Which means, there is no need on re-inventing the wheel to trim the strings since, from the admin-end side, in the validate or validateForm methods, each super global arrays are already trimming the POSTs with the requests on anyhow.

**Comment by TheCartpenter** [comment]
If you expect me to write codes, it would not be in here since Daniel, as well for anyone else, already informed the users to post their code suggestions into the Pull Requests tab rather than the issues tab. As far as I see, your posted commit addressing an issue with trimming functions has been posted in the issues tab rather than the pull requests as your first post contains code suggestion changes in it.

**Comment by chulcha** [comment]
@TheCartpenter 
You will not enter the code OC.
Why are you writing here?

**Comment by TheCartpenter** [comment]
> @TheCartpenter
> You don't know the code
> Why are you writing here?

Nowhere to be said that I don't know the code as the explanation regarding why I am not posting the code in this section has been explained on my previous reply.

**Comment by chulcha** [comment]
@TheCartpenter 
I don't give a damn about your opinion.
You will already show your knowledge of the code in your first answer.
Don't post here.

**Comment by TheCartpenter** [comment]
> @TheCartpenter
> I don't give a damn about your opinion.
> You will already show your knowledge of the code in your first answer.
> Don't post here.

Of course, I won't post the codes here in this section.

**Comment by chulcha** [comment]
So you talk?
Don't post here.
Do not post in my threads.
Your opinion is not interesting to me.

**Comment by TheCartpenter** [comment]
If your intentions are to post in a community area where you'd expect one-to-many not to talk, then better to address that you're posting in the wrong repository. Opencart is about posting among a community, not to be kept in silence. If you do not wish to post in a community spot, then better to consider posting elsewhere. Otherwise, you'd simply be wasting your time.

**Comment by chulcha** [comment]
My messages are for people who know the code, and with whom you can discuss the correct solution. for example @ADDCreative .

But just not with you. You will create white noise.

**Comment by TheCartpenter** [comment]
Again, nowhere to be said that I don't know the code. This is only your presumption based on what you're saying. As mentioned above, you are addressing code changes in the wrong section of this repository. It has nothing to do with somebody else's posts but rather this commit that hasn't been created in the right location.

**Comment by chulcha** [comment]
I am not making a change. Can you read?

I am discussing the problem and its solution.

**Comment by TheCartpenter** [comment]
> I am not making a change. Can you read?
> 
> I am discussing the problem and its solution.

Exactly, you are addressing codes that you are suggesting to look into rather than using the issues template addressing the step-by-step issues. Which means, not saying that your posted codes should not be posted but, again, saying that you are posting these types of suggestions in the wrong place.

**Comment by chulcha** [comment]
An empty link is a problem (issue).
Do you understand this?
Therefore, I write in the right place.
And you keep talking nonsense.

**Comment by TheCartpenter** [comment]
If the case, is this an addressed issue that could be shown based on screenshots from, either, the admin / catalog-end as per the template?

**Comment by chulcha** [comment]
Take it and test it.
Are you a developer or a chatterbox?
I see that you are a chatterbox.

I described the existing problem.  A screenshot is not needed here.
If you do not know how to read and understand, then do not write here

**Comment by TheCartpenter** [comment]
Then, it says it all. If you're addressing an issue based on codes rather than screenshots, you're addressing an issue that should rather be pointed as a Pull Requests, not as an issue.

**Comment by chulcha** [comment]
To my clients, I changed a long time ago
Do you use screenshots in the OS?
I feel sorry for your customers
Simulate the description of the error (problem), and maybe you will understand something.
Otherwise, I have nothing to talk about with you

If you want, then you yourself can make a PR. It will be credited to you.
The code for PR is here.  Go to PR.

**Comment by TheCartpenter** [comment]
```The code for PR is here. Go to PR.```

The code for PR is here .... where? I don't see any codes of these posted in the PRs, so far. Perhaps you forgot to post PRs link to your code changes?

**Comment by chulcha** [comment]
Learn to read

**Comment by TheCartpenter** [comment]
I read your part. You just need to read mine.

**Comment by chulcha** [comment]
@TheCartpenter  I'm not interested in reading your bullshit

**Comment by danijelGombac** [comment]
Please stop, is annoying, you are worse than little  kids.

**Comment by TheCartpenter** [comment]
> Please stop, is annoying, you are worse than little kids.

I totally agree, here. Could we please close this commit?

**Comment by WebkulOpencart** [comment]
As I checked the previous comments so closing this issue.
