### ISSUE TITLE
[Master Branch] Make use of loader::library to trigger library/* events

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#9483]
OpenCart 4, like in previous versions, uses a number of singleton classes whose instances are referred to in the registry, such as 'request', 'response', 'db', 'session', 'cache', etc. However, when creating the instances of these singleton library classes in e.g. the **system/framework.php** no events are triggered because we don't use the loader->library at the moment.

First of all, the function 'library' needs to be fixed, as follows, in **system/loader.php**. Each of the **$args** are to be passed the normal way, not by reference!  And a registry entry consists of a single word, e.g. 'user' instead of 'cart_user' (being referred to via **$this->user** instead of **$this->cart_user** in later controller or model codes).

```
	/**
	 * Library
	 *
	 * Loads library classes
	 *
	 * @param    string $route	The path to the library file.
	 * @param    mixed  $args	A list of arguments to pass into the library object being created.
	 */
	public function library(string $route, mixed  ...$args): object {
		// Sanitize the call
		$route = preg_replace('/[^a-zA-Z0-9_\/]/', '', $route);

		// Keep the original trigger
		$trigger = $route;

		$this->event->trigger('library/' . $trigger . '/before', [&$route, &$args]);

		$class = 'Opencart\System\Library\\' . str_replace('/', '\\', $route);

		if (class_exists($class)) {
			$library = new $class(...$args);

			// Create a key to store the library object
			$this->registry->set(strtolower(basename($route)), $library);
		} else {
			throw new \Exception('Error: Could not load library ' . $route . '!');
		}

		$this->event->trigger('library/' . $trigger . '/after', [&$route, &$args]);

		return $library;
	}
```

And then most constructor calls for these singleton classes in the **system/framework.php** or other places should be changed to $loader->library(...) or $this->load->library(...). 

Hence I suggest to change the **system/framework.php** (and possibly some other files) as follows. For example replace

```
	$session = new \Opencart\System\Library\Session($config->get('session_engine'), $registry);
	$registry->set('session', $session);
```

with
```
	$loader->library('Session',$config->get('session_engine'), $registry);
	$session = $loader->session;
```

There are a number of other singleton classes, above is just one example.

An alternative solution, which could even be more flexible, might be the usage of before- and after-events for the registry::get and registry::set calls. Something like this in **system/registry.php**:

```
	/**
	 * Set
	 *
	 * @param	string	$key
	 * @param	string	$value
	 */	
	public function set(string $key, object $value): void {
		$event = (isset($this->data['event']) && ($key!='event')) ? $this->data['event'] : null;
		if ($event) {
			$event->trigger("registry/set/$key/before",[&$value,&$this->data]);
		}
		$this->data[$key] = $value;
		if ($event) {
			$event->trigger("registry/set/$key/after",[&$value,&$this->data]);
		}
	}
```

**Comment by stalker780** [comment]
https://github.com/opencart/opencart/pull/9479#issuecomment-808703667

Here I have also proposed today to remove string routes and loaders at all
`$this->load->controller('route', $params);`
`$this->load->model('route');`
`$this->mylibrary->function();`

And use prefixed objects with automatic loaders and events:
`$this->controller_product_category($params);`
`$this->controller_product_product->review($params);`
`$this->model_catalog_product->getProducts($params);`
`$this->library_cart_cart->getProducts($params);`
`$this->library_image($params);`
`$this->library_response->output();`

very similar to models, which are used now, but remove $this->load everywhere in the code.

**Comment by TheCartpenter** [comment]
While ```$this->mylibrary->function();``` should be: ```$this->mylibrary->method()``` , I do like the idea of using the proposed objects such ways.

**Comment by chulcha** [comment]
@TheCartpenter 
public FUNCTION
Therefore your opinion is not interesting 

You have already shown that when OС you don't know .

**Comment by stalker780** [comment]
@chulcha 
Chill down ;)
Stop bullying one another

@TheCartpenter 
Terminology is not the most important. Just hope everyone understand what I am talking about.

My proposition will standardize all controller/model/library calls. Will making them more readable, reduce repeated code, make them more transparent, less hidden code, but possible use before/after events in proxy functions.

But this requires to modify all core files. I doubt Daniel will agree with that. As he said, he is close to release OC4.

**Comment by TheCartpenter** [comment]
> @chulcha
> Chill down ;)
> Stop bullying one another
> 
> @TheCartpenter
> Terminology is not the most important. Just hope everyone understand what I am talking about.
> 
> My proposition will standardize all controller/model/library calls. Will making them more readable, reduce repeated code, make them more transparent, less hidden code, but possible use before/after events in proxy functions.
> 
> But this requires to modify all core files. I doubt Daniel will agree with that. As he said, he is close to release OC4.

@stalker780: As per the above, I do like this proposition. No need to re-explain the theory. It would be great to use the Engine such ways in the future as I do agree that using new instances is becoming quite old. :)

**Comment by mhcwebdesign** [comment]
@stalker780: Your suggestion looks interesting but it's beyond the scope of my simple proposal to make use of the loader::library so as to trigger some important events. And I don't thin Daniel will implement your suggestion anytime soon.

I assume your idea includes an autoloader for all the controller, model, and library classes? If so, such an autoloader might then as well also make use of a factory class for instantiating the other classes. The factory could include event triggers which could modify its behavior, e.g. making use of decorator classes from OC extensions wrapping around around the regular controller, model, and library classes. This would be more flexible than the current event triggers. But all of this should be discussed on the OpenCart forum, let's stick to simple more realistic suggestions only on github.

**Comment by TheCartpenter** [comment]
There's no need for a factory.

**Comment by Hkr32** [comment]
> @stalker780: While `$this->mylibrary->function();` should be: `$this->mylibrary->method()` , I do like the idea of using the proposed objects such ways.

but how can you tell everyone what is not worth offering here, for this there is a PR?
or indicate that there is no need to write code here?
or your account was hacked and there is now a normal person?

**Comment by danielkerr** [comment]
opencart does not sue singleton classes and for u to suggest so makes me think u dont know what ur talking about
