### ISSUE TITLE
[Master Branch] Incomplete SEO URLs for links and canonicals

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#9486]
**What version of OpenCart are you reporting this for?**
Master Branch 4.0.0.0b (28 March 2021)

**Describe the bug**
On e.g. the frontend page _Phones & PDAs > HTC Touch HD_ the link canonical doesn't use a SEO URL at all, and the product page uses something like www.example.com/htc-touch-hd?language=en-gb&path=24

It should be www.example.com/smartphone/htc-touch-hd?language=en-gb for the product page and link canonical.

Also, it shouldn't use the **?language=en-gb** in the URL query string, the language selection is session based.

**To Reproduce**
1. In the admin backend do this: _System > Settings > edit > Server > use SEO URLs: Yes_
2. On the frontend, click on the Phones & PDAs
3. Then click on the **HTC Touch HD** product link

**Expected behavior**
All SEO URL keywords should be used for the various links.

**Server / Test environment (please complete the following information):**
 - Local development? Yes
 - Operating system: Linux Mint 17.3
 - PHP version: 8.0.3
 - Apache version: Apache/2.4.18 (Ubuntu)
 - Browser(s) tested with: Firefox
 - Version 87.0 (64-bit)

**Comment by SaifAlSubhi** [comment]
Hi @mhcwebdesign
Suggestion:
maybe the product page URL to be like:
www.website.com/en-gb/category/product-name?
if possible

**Comment by mhcwebdesign** [comment]
@SaifAlSubhi: Yes, that's how we do it for our multi-lingual OC sites, using our own Multil-lingual SEO extension (https://www.mhccorp.com/language-seo).

**Comment by stalker780** [comment]
Seo urls (particularly language parameter) are broken after PHP8 updates
#9468

Also information seo_profile is broken
#9469

**Comment by stalker780** [comment]
> It will not be 2 months
Daniel said, and disappeared for a month :)

https://github.com/opencart/opencart/issues/8710#issuecomment-788798734

Train your patience :)

**Comment by danielkerr** [comment]
its not that bigger issue. just make sure all products, categories, information, manufacturing pages have seo url created.
