### ISSUE TITLE
Gift Voucher Currency Conversion Issue

### ISSUE THREAD

**Issue by vivekalagarsamy1991** [opencart/opencart#9489]
**What version of OpenCart are you reporting this for?**
3.0.3.2

**Describe the bug**
Assume i have multi store setup with 2 stores, store 1(default store) with currency in dollar, and the other store is Singapore dollar. And the minimum voucher range is set between $100 to $1000 dollar. Singapore customers try to buy a gift voucher through store 2 and when they submit with amount Singapore dollar S$ 10. Opencart converts into dollar currency and returns back as converted currency value rather than the actual user entered value. Currency conversion is not working properly.
What section does it affect?
Gift Voucher

**To Reproduce**
Steps to reproduce the behaviour:
Multi Store setup is must!
1. Go to 'Gift Voucher page in front-end - store 2 with different currency then the default store currency'
2. Enter any amount
3. When you submit it will throw error with converted amount of default store currency also when voucher page loads you will see the minimum value by default setup. But if you submit with same value it will still throw errors.

**Expected behaviour**
In Voucher page amount field should see the amount which entered by user, not the converted value. And at the same time if user submits the values it should be validated with same currency, need not to convert.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? - Deployed in client server.
 - Operating system - Linux
 - PHP version - 5.6
 - Browser(s) tested with [e.g. chrome, safari - if applicable] - Chrome

**Additional context**
![image](https://user-images.githubusercontent.com/30053599/112993729-24444b00-9187-11eb-96d4-aed7bc293fe0.png)
![image](https://user-images.githubusercontent.com/30053599/112993799-37efb180-9187-11eb-964a-b60e7b6ba8d2.png)
![image](https://user-images.githubusercontent.com/30053599/112994001-6c636d80-9187-11eb-8c8e-7c6299d15e44.png)

**Comment by TheCartpenter** [comment]
Forum request.

**Comment by ADDCreative** [comment]
Could be related to https://github.com/opencart/opencart/pull/5298.

**Comment by WebkulOpencart** [comment]
@vivekalagarsamy1991 you have reported the issue of the old version so I request you to please report on the OpenCart Forum.
