### ISSUE TITLE
TypeError:  Opencart\Catalog\Model\Catalog\Information::getLayoutId(): Argument #1 ($information_id) must be of type int

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9494]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
Error log:
TypeError:  Opencart\Catalog\Model\Catalog\Information::getLayoutId(): Argument #1 ($information_id) must be of type int, string given in .../catalog/model/catalog/information.php on line 16

`public function getLayoutId(int $information_id): int {`
What section does it affect?

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by mhcwebdesign** [comment]
Not enough details to reproduce your error.

The `public function getLayoutId(int $information_id): int {` is correct, your error is caused from somewhere else.

**Comment by cgcmart** [comment]
It's logged by opencart error log.
I checked oc4 install/mysqli.sql, there is no` oc_information_to_layout` table. I also checked DB, `oc_information_to_layout` table is empty.

**Comment by AlexGThess** [comment]
> It's logged by opencart error log. I checked oc4 install/mysqli.sql, there is no` oc_information_to_layout` table. I also checked DB, `oc_information_to_layout` table is empty.

hello, so what was the solution on this?

**Comment by mhcwebdesign** [comment]
@ AlexGThess : No need for a solution. Nobody else seems to be able to reproduce this error.

**Comment by AlexGThess** [comment]
@mhcwebdesign i have it now :P :P
