### ISSUE TITLE
Opencart Direct Payments with 3D Secure

### ISSUE THREAD

**Issue by SPB105438** [opencart/opencart#9496]
**What version of OpenCart are you reporting this for? 3.0.3.7 - master branch

Describe the bug

Following on from #9355 

Placing an order with the sage pay direct the payments fails,
no record of the transaction shows in sagepay, once the transaction fails, you are returned to the login page of your shop, and are no longer logged in, once logged back in, the product remain in the cart

Apologies had to take a break from this, after lots more testing
The issue seems to be related to "3D Secure Response from Opayo" and either cookies or session.

I have been testing with the sagepay now opayo test cards, 

(test 1)
The first order placed will be completed, no issues, even when using 3D secure. (first test card on the list)
The second order placed will fail with 3D secure, but using the sagepay test card without 3d secure, (second card on the list) the order will go through.

(test 2)
The first order placed will be completed, no issues, even when using 3D secure.
Clearing the browser history
The second order placed will be completed, no issues, even when using 3D secure.

Clearing the browser history between orders works, but why and how do i fix it ?
I have tested this in both the new edge and chrome browsers, 

Local development? Development Server, Deployed to a web server Yes
Operating system - Windows Server 2016
PHP version 7.4.13
Using Chrome and New Edge browser
Additional context
Products and payment providers setup using the same details as my live opencart shop running 2.3.0.2 - trying to rebuild our shop in 3.0.3.7

**Comment by ADDCreative** [comment]
By clearing browser history do you mean history, cache and cookies, etc? Have you tried just clearing cookies, just cache, etc.? Have you tried clearing just for your site? The difference in these test could help you track down the issue.

Have you also use your web browser's development tool to check for errors and messages about blocked cookies and requests. Also the network tab might help you spot the difference.

**Comment by SPB105438** [comment]
I cleared everything, history, cookies and cache.
Then i tested it again this time with the development tool open, this is something i have never used before.
The first order went through without an issue using the test card that would trigger the 3D response.
Then i tried another order which failed.

The only things i could see was this issue

Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute

Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests.

3 cookies
Name | Domain & Path

OCSESSID | devstoreapp.com/
language | .devstoreapp..com/
currency | .devstoreapp..com/

If i tick the box labelled "Has Blocked cookies"
its filter and shows a single line showing the "initiator" as https://devstoreapp.com/index.php?route=account/login

I then cleared only the cookies from the browser history and tried the order again, this time it went through and the "Your order has been placed!" page was displayed, the dev tool still shown the above issue

**Comment by ADDCreative** [comment]
Try just clearing the cookies for your domain before the second order. That might tell you id the issue is with the cookies on your domain or the 3DS page.

**Comment by SPB105438** [comment]
Is there no timeout on cookies?
Could the issue be testing order after order?

**Comment by ADDCreative** [comment]
Looking at the code you will get redirected to route=account/login.
https://github.com/opencart/opencart/blob/2a5b358003d1e9e4af964eda2ffcb79abe8229ce/upload/catalog/controller/extension/payment/sagepay_direct.php#L425)

If the session is missing.
https://github.com/opencart/opencart/blob/2a5b358003d1e9e4af964eda2ffcb79abe8229ce/upload/catalog/controller/extension/payment/sagepay_direct.php#L349

Your browser is also telling you it's blocking OCSESSID due to SameSite rules. You have set you OCSESSID to use SameSite=None? As suggested in https://github.com/opencart/opencart/issues/9355#issuecomment-780947143?

**Comment by SPB105438** [comment]
I didnt make any changes to the original files for two reasons, one wasnt sure the issue im having was related to the samesite issue, and two i try not to change any of the default files to prevent issue in the future after updates.

i have now changed the following line in system\framework.php

`setcookie($config->get('session_name'), $session->getId(), ini_get('session.cookie_lifetime'), ini_get('session.cookie_path'), ini_get('session.cookie_domain'));`

changed to 

`setcookie($config->get('session_name'), $session->getId(), ['expires' => ini_get('session.cookie_lifetime'), 'path' => ini_get('session.cookie_path'), 'domain' => ini_get('session.cookie_domain'), 'samesite' => 'None', 'secure' => true, 'httponly' => true]);`

Nothing else has been changed.
Quick initial tests shows this seems to be working, Hope to have more time tomorrow to test more

**Comment by SPB105438** [comment]
@ADDCreative Seems your fix worked, thank you
https://forum.opencart.com/viewtopic.php?f=202&t=219633#p797082 

I will make a note in case it is needed in future updates,
