### ISSUE TITLE
Billing Details

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#9542]
Purchase from Opencart Store.

At the beginning of the checkout, step 2:
Address (street, city etc.) is required (also ín addressbook of account)
Telephone is required

EUROPE HAS A STRONG PROTECTION OF PRIVACY.
These things should not be asked in advance.

These things should not be asked at any point during your purchase, IF:

the product is delivered to the post machine and the customer pays for the product immediately at the checkout.

**Comment by pekka2** [comment]
Ps. Address information is also unnecessary when the purchased products are sent to a post office chosen by the customer.

**Comment by TheCartpenter** [comment]
Except that most payment service providers still acquires these information during checkout regardless if these information originates from the store prior to be redirected to the payment service provider's page (when applies) or once being redirected to.

**Comment by pekka2** [comment]
> Except that most payment service providers still acquires these information during checkout regardless if these information originates from the store prior to be redirected to the payment service provider's page (when applies) or once being redirected to.

This thing can also be done so that

1. the customer's address information is not asked
2. Address information would be requested only at the end, after shipping methods and payment methods
3. Address details would only be required in the case of home delivery
4. If a merchant wants to know the exact address of the customer in advance - even if the customer does not necessarily buy anything - he should be installed by the end of the third-party ocmod- expansion.
5. The name 'Billing details' is misleading if the invoice is never sent

**Comment by TheCartpenter** [comment]
While this might be believed to be the case, callback URLs, based on the differentiation of the payment extension module being used, these move arounds during checkout will still be problematic in the future by doing so.

**Comment by pekka2** [comment]
Maybe later you can consider redesigning and then rebuilding the entire checkout site, not repairing the old script.

**Comment by marina231079** [comment]
3D secure othvurlqna karta

**Comment by danielkerr** [comment]
yes going to add ability to choose to have billing address added or not.

**Comment by PDL-II** [comment]
Really nice to see a 4.0.0 version. I'm in the music industry and one thing that I noticed is that there aren't any e-commerce solutions (at least that I've seen) with audio as a product by default. For instance, I can add videos and images in version 3 but not when it comes to audio, other than the zip files. Is that something you would consider doing in the future? 

Thanks in advance and sorry for the long text.

**Comment by danielkerr** [comment]
Can u not just upload mp3 files? If not just add it to allowed list of
uploaded files in settings.

**Comment by danielkerr** [comment]
in master the system now allows to checkout with address or not depending on the settings.
