### ISSUE TITLE
Warning: Undefined array key "model_sale_order"

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9546]
**What version of OpenCart are you reporting this for?**
Master branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Admin Panel Sales
>> Orders
>> Recurring Orders
>> Retirms
>> Gift Vouchers

Warning: Undefined array key "model_sale_order" in .../system/engine/registry.php on line 51
Missing model_sale_order

Admin Panel System

>> Localisation -> Geo Zones

Warning: Undefined array key "model_localisation_geo_zone" in .../system/engine/registry.php on line 51Missing model_localisation_geo_zone

Admin Panel Reports

>> Statistics

Warning: Undefined array key "error" in .../system/engine/registry.php on line 51Missing error

**To Reproduce**
1. Go to '...admin >> Sales >>'

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by Sebjugate** [comment]
We experienced the same issue when checking out master branch. Judging from the commit log it seems there is a major overhaul of form handling underway.

Checking out tag/3.0.3.7 was much more successful for us.

**Comment by SaifAlSubhi** [comment]
all missing model loads are added
```
$this->load->model(' ... / ... ');
```
