### ISSUE TITLE
Exception: Error: Could not load model Opencart\Admin\Model\Localisation\Affiliate! 

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9547]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Admin Panel Marketing
>> Affiliate
>> Marketing
>> Coupons

Admin Panel System
>> Users -> API

Exception: Error: Could not load model Opencart\Admin\Model\Localisation\Affiliate! in .../system/engine/loader.php on line 110

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart/pull/9529/commits/30dd6438fd8156b2e4f6974b756d27657abc3d93
https://github.com/opencart/opencart/pull/9531
https://github.com/opencart/opencart/pull/9530

Part of the solution regarding the model loads.

**Comment by SaifAlSubhi** [comment]
> [30dd643](https://github.com/opencart/opencart/commit/30dd6438fd8156b2e4f6974b756d27657abc3d93)
> #9531
> #9530
> 
> Part of the solution regarding the model loads.

@TheCartpenter 
Hi,
I have a general question: why all these pull requests which contains valid fixes are not implemented for a while?

**Comment by TheCartpenter** [comment]
Depends how fast one can be to implement it.  We all work at different speeds unfortunately.

**Comment by SaifAlSubhi** [comment]
This is fixed
https://github.com/opencart/opencart/blob/fa1ebfc3068eb8ba8765f5c5cc373d0fc853a58f/upload/admin/controller/marketing/affiliate.php#L156
