### ISSUE TITLE
TypeError: Opencart\Admin\Controller\Tool\Upload::getList(): Return value must be of type string, none returned

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9548]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Admin Panel System

>> Maintenance -> Uploads

TypeError: Opencart\Admin\Controller\Tool\Upload::getList(): Return value must be of type string, none returned in .../admin/controller/tool/upload.php on line 210

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by SaifAlSubhi** [comment]
This line
https://github.com/opencart/opencart/blob/1684fe6c75534f6fccea7ff7875fa3c973cc1fb8/upload/admin/controller/tool/upload.php#L54
was
```
protected function getList(): void {
```

try it

**Comment by mhcwebdesign** [comment]
The error is caused elsewhere. The `protected function getList(): string {` is the correct one.

**Comment by SaifAlSubhi** [comment]
It has been updated
https://github.com/opencart/opencart/blob/fa1ebfc3068eb8ba8765f5c5cc373d0fc853a58f/upload/admin/controller/tool/upload.php#L55
https://github.com/opencart/opencart/blob/fa1ebfc3068eb8ba8765f5c5cc373d0fc853a58f/upload/admin/controller/tool/upload.php#L194

This error should be fixed.
