### ISSUE TITLE
OC3.0.3.7 can't reveive normal HTML email when using PHP8.xx

### ISSUE THREAD

**Issue by evaland999** [opencart/opencart#9551]
**What version of OpenCart are you reporting this for?**
3.0.3.7
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
Opencart 3.0.3.7 installed with PHP .8xx
Can't receive normal Html contents
I tried downloaded 
https://github.com/opencart/opencart/pull/9358/commits/7ccd255a425e36dd19a4123c83e83cb08aa429ff
from Sir @prabhatkumaroc082 
I tried this mail.php to my 3.0.3.7
But still can't receive Normal email contents.
I made simple video to more clear describe the issue.
https://youtu.be/jF4EJVIi-CY

Can I beg you help fix it.
Because I really hope my OC 3.0.3.7 can running under PHP 8.xx

**Comment by ADDCreative** [comment]
@evaland999 It's clear from you video that you have not implemented the changes you link to correctly.

You have a ```Content-Transfer-Encoding: 8bit``` line followed directly by ```Content-Transfer-Encoding: base64```. You should just have ```Content-Transfer-Encoding: base64```.

**Comment by evaland999** [comment]
> 
> 
> @evaland999 It's clear from you video that you have not implemented the changes you link to correctly.
> 
> You have a `Content-Transfer-Encoding: 8bit` line followed directly by `Content-Transfer-Encoding: base64`. You should just have `Content-Transfer-Encoding: base64`.

Hi,sorry for my rude.
But I just a senior user of OC,
I not expert on code modifying.
I downloaded mail.php from 
7ccd255
to try solve this issue,But still can't solve.
Can you help fix this file
for teach me which line need to edit.

**Comment by prabhatkumaroc082** [comment]
@evaland999 
Please ask your developer to modify two file changes as per the following commits, we have not faced any issue now. 
https://github.com/opencart/opencart/commit/7ccd255a425e36dd19a4123c83e83cb08aa429ff
https://github.com/opencart/opencart/commit/29556c5df0d11d451aa39c3408edac5e43cc420e

**Comment by prabhatkumaroc082** [comment]
> I not expert on code modifying.

If you want then the Webkul team can check and fix your issues. Please share your requirements at sales@webkul.com

**Comment by condor2** [comment]
@evaland999 I made changes for you.
See if work now.

**Comment by evaland999** [comment]
> 
> 
> @evaland999 I made changes for you.
> See if work now.

Dear Sir.
pardon me,
About you said "Made changes for me"
May I ask where to see this changes?

**Comment by evaland999** [comment]
> 
> 
> > I not expert on code modifying.
> 
> If you want then the Webkul team can check and fix your issues. Please share your requirements at [sales@webkul.com](mailto:sales@webkul.com)

Dear Sir,Thank you so much,I have emailed to you.

**Comment by prabhatkumaroc082** [comment]
@evaland999 
closing it, already fixed.

**Comment by evaland999** [comment]
> 
> 
> @evaland999
> closing it, already fixed.

Pardon me Sir,
Do you mean already fixed on my server?

**Comment by prabhatkumaroc082** [comment]
> Pardon me Sir,
> Do you mean already fixed on my server?

it is fixed on https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
soon a 3.0.3.8 release will be there.

**Comment by evaland999** [comment]
> 
> 
> > Pardon me Sir,
> > Do you mean already fixed on my server?
> 
> it is fixed on https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
> soon a 3.0.3.8 release will be there.

Dear Sir,
Please forgive my rudeness,
But I mean to be a jerk,
I download your mail.php from
https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
and uploaded it to my oc's server.
But problem there and even worse.
I just made new simple video to show you .
can you help check this video
and if you need login to check,You can use the info I emailed to you yesterday.
https://youtu.be/Xrf1-JSmXjs

**Comment by prabhatkumaroc082** [comment]
> Dear Sir,
> Please forgive my rudeness,
> But I mean to be a jerk,
> I download your mail.php from
> https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
> and uploaded it to my oc's server.
> But problem there and even worse.
> I just made new simple video to show you .
> can you help check this video
> and if you need login to check,You can use the info I emailed to you yesterday.
> https://youtu.be/Xrf1-JSmXjs

If you have mailed it to the Webkul sales team, then it will be forwarded to the development team soon. mail issue is already fixed in https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance.
I recommend testing on fresh 3.0.3.7 OC and apply mail.php and smtp.php changes which I mentioned multiple times.

**Comment by evaland999** [comment]
> 
> 
> > Dear Sir,
> > Please forgive my rudeness,
> > But I mean to be a jerk,
> > I download your mail.php from
> > https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
> > and uploaded it to my oc's server.
> > But problem there and even worse.
> > I just made new simple video to show you .
> > can you help check this video
> > and if you need login to check,You can use the info I emailed to you yesterday.
> > https://youtu.be/Xrf1-JSmXjs
> 
> If you have mailed it to the Webkul sales team, then it will be forwarded to the development team soon. mail issue is already fixed in https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance.
> I recommend testing on fresh 3.0.3.7 OC and apply mail.php and smtp.php changes which I mentioned multiple times.

Dear Sir
With all due respect
I present you a whole new fresh OC 3.0.3.7
To Prove the facts I described 
please see this video
https://youtu.be/glkcw83iGYk
Pardon me again,Sir ,if your Webkul team is Specially deal with OC3.xx issues .
I hope you can treat this issue very serious.
Sir, I am a senior user of OC,I used it more than 6 years.
So My opinion is very serious not a player.
Please and please pay more attention on this video
You can ask me any  info ,just tell me.

**Comment by evaland999** [comment]
Sir,My video have some issue to show all the contents.
Allow me made a new one

**Comment by condor2** [comment]
@evaland999 check the email and see if is ok.
If you make 20 clean install using 3.0.3.7 from website you need to make changes in mail and smtp files,

**Comment by evaland999** [comment]
> 
> 
> > Dear Sir,
> > Please forgive my rudeness,
> > But I mean to be a jerk,
> > I download your mail.php from
> > https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
> > and uploaded it to my oc's server.
> > But problem there and even worse.
> > I just made new simple video to show you .
> > can you help check this video
> > and if you need login to check,You can use the info I emailed to you yesterday.
> > https://youtu.be/Xrf1-JSmXjs
> 
> If you have mailed it to the Webkul sales team, then it will be forwarded to the development team soon. mail issue is already fixed in https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance.
> I recommend testing on fresh 3.0.3.7 OC and apply mail.php and smtp.php changes which I mentioned multiple times.

Sir,
I made this whole new video to present you the issue happen on whole new OC 3.0.3.7
https://youtu.be/eaSJ2vF9rH0
please treat it seriously
please

**Comment by evaland999** [comment]
> 
> 
> @evaland999 check the email and see if is ok.
> If you make 20 clean install using 3.0.3.7 from website you need to make changes in mail and smtp files,

Sir,
I made this whole new video to present you the issue happen on whole new OC 3.0.3.7
https://youtu.be/eaSJ2vF9rH0
please treat it seriously
please

**Comment by condor2** [comment]
As I said. 3.0.3.7 package from Opencart.com doesn't have this mail/smtp fix.
So, every time you use that package you need to make changes to mail and smtp.

**Comment by condor2** [comment]
If you check email directly from the server the message is ok?

**Comment by evaland999** [comment]
> 
> 
> As I said. 3.0.3.7 package from Opencart.com doesn't have this mail/smtp fix.
> So, every time you use that package you need to make changes to mail and smtp.

I get your point sir.
After I installed the 3.0.3.7 package from Opencart.com
and then I uploaded the 
mail.php and smtp.php 
from https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
to over write the Fresh OC 3.0.3.7
Isn't that right.
But issue still there.
What's wrong I still miss?
Can you teach me?

**Comment by evaland999** [comment]
> 
> 
> If you check email directly from the server the message is ok?

Hi sir
I just check email from my webmail system
But still wrong
![圖片](https://user-images.githubusercontent.com/79344209/113829506-29714d80-97b8-11eb-87c8-c5951f13fc8e.png)

**Comment by prabhatkumaroc082** [comment]
@evaland999 
share the ticket id only which was generated after sending mail to sales@webkul.com, the development team will check it.

**Comment by evaland999** [comment]
> 
> 
> @evaland999
> share the ticket id only which was generated after sending mail to [sales@webkul.com](mailto:sales@webkul.com), the development team will check it.
Ticket ID is
#272842

**Comment by evaland999** [comment]
> 
> 
> @evaland999
> share the ticket id only which was generated after sending mail to [sales@webkul.com](mailto:sales@webkul.com), the development team will check it.

ticjet ID 
#272842

**Comment by evaland999** [comment]
Hi Guys,
WebkulOpencart 's team reply me from their support ticket system everyday.
They are working on fix this issue,
And I am glad waiting and hope this issue can be fixed soon.

**Comment by prabhatkumaroc082** [comment]
Dear @evaland999 
as we communicated with you over our ticket system, we did not find any issue with Opencart 3.0.3.7
we provided full details over ticket so you can apply them.

we are closing this issue now.

**Comment by evaland999** [comment]
You team WebkulOpencart keep say"this issue not happened on your php8.xx server.
I tried to figured it out who's right or lie.
I ordered a simple and easy shared hosting and install a fresh OC 3.0.3.7
then I copy your mail.php to upgrade it.
But situation still there.

With all due respect,
Either your PHP 8.xx server is such different
if not,why other PHP 8.xx cant's work well with email

I such disappointed of WebkulOpencart team

you can test this shared hosting
https://evaland.click/maxtest/admin/
evalandadmin
aqq1999

![圖片](https://user-images.githubusercontent.com/79344209/115251440-233a8400-a15d-11eb-8625-a4f3d25c1931.png)

**Comment by WebkulOpencart** [comment]
@evaland999 I am again reopening this issue and again asking the team to recheck the same again.
If we need any server information then we will let you know for the update over the support ticket.

**Comment by evaland999** [comment]
For the record to all good guys such like Webkulopencart team,
I not mean to Challenge or provocation .
This issue really confuse me a a lot,
And I strong believe this issue not only happened on my
Let me Describe the problem again 
OC3.0.3.7
using PHP 8.xx
and using server built "mail" not "SMTP"
then you will get wrong email contents,No matter "Register,finish order,send order notify email to customer" any action about send email.

Before today,
WebkulOpencart  told me at least twice that this problem not happened on their PHP 8.xx
They imply that the problem lies with my host .
I am using a common VPS hosting not special.

But for More clearly distinguish the problem ,I ordered a shared hosting and install a fresh oc3.0.3.7 to check this issue.

And issue still there.

Dear WebkulOpencart team,This shared hosting can use a month before end of it's life.
You can test it for anything,
I already paid for it a month.
Hope can help to fix this problem.

**Comment by mhcwebdesign** [comment]
The basic mail function is pretty useless.

Have you checked for any errors in e.g. your server's **var/log/mail.err** ?

**Comment by prabhatkumaroc082** [comment]
@evaland999 
You can use PHP 7.4 for your site as it worked fine this version.
If you want to use PHP 8 then use SMTP or report your server team to debug this issue for default mail.

**Comment by evaland999** [comment]
Hi fellas,
Actually about you teach the ways to fix this problem,such as.
use PHP7.4 
use SMTP
I very know the issue will not happen again when use these ways.
For the record,I report them already before you suggested it.

My question is not "hope can fix this problem on 3.0.3.7"
My main purpose is "Make sure it will not happen on OC 4.xx",Because most of OC user will glad to upgrade to OC4.xx in future"
I believe no one include Mr.Daniel hope this issue not happen on OC4.xx

My most dissatisfied  is I tested and tested a lot on different server such like VPS, cheap share hosting else,This problem happened on all PHP8.xx
But Why WebkulOpencart 's keep saying it work fine on their PHP8.xx,
This is so strange situation.
Does your PHP8.xx is a special setting?

**Comment by prabhatkumaroc082** [comment]
@evaland999 
for OC 4.x and 3.0.3.8, already applied the changes so anyone should not face any issue when these versions will be released.
Now please report on the forum only.
