### ISSUE TITLE
ocStore 3.0.2.0 Errors blog category and article

### ISSUE THREAD

**Issue by kosh2323** [opencart/opencart#9568]
ocStore  3.0.2.0 When you save the blog category, as well as the category itself can not be deleted, I get errors 

Notice: Undefined index: column in C:\OpenServer\domains\test.ru\admin\model\blog\category.php on line 65Notice: Undefined variable: category_id in C:\OpenServer\domains\test.ru\admin\model\blog\category.php on line 137Warning: Cannot modify header information - headers already sent by (output started at C:\OpenServer\domains\test.ru\admin\controller\startup\error.php:34) in C:\OpenServer\domains\test.ru\system\library\response.php on line 36 

and when creating a blog article errors

Notice: Undefined index: tag in C:\OpenServer\domains\test.ru\admin\model\blog\article.php on line 16Warning: Cannot modify header information - headers already sent by (output started at C:\OpenServer\domains\test.ru\admin\controller\startup\error.php:34) in C:\OpenServer\domains\test.ru\system\library\response.php on line 36

What to do tell me, who knows

**Comment by ADDCreative** [comment]
OpenCart doesn't have a blog. I think you have the wrong repository.

**Comment by WebkulOpencart** [comment]
Please report the same on the OpenCart Forum. I am closing this issue.

**Comment by kosh2323** [comment]
> Please report the same on the OpenCart Forum
Please show me where I can create a theme

**Comment by WebkulOpencart** [comment]
@kosh2323 Please follow the below link
[https://forum.opencart.com/](https://forum.opencart.com/)

**Comment by kosh2323** [comment]
thanks
