### ISSUE TITLE
Composer Create Project

### ISSUE THREAD

**Issue by tjapro** [opencart/opencart#9569]
**What version of OpenCart are you reporting this for?**
3.0.3.7 I guess

**Describe the bug**
When installing the OC through composer, it will install the OC version 3.0.3.6, instead of 3.0.3.7

**To Reproduce**
1. Create an empty folder.
2. Run the `composer create-project opencart/opencart <folder>`
3. Check the `upload/index.php`file.
4. See the VERSION variable defined.

**Expected behavior**
A correct install.

Is composer doing the things wrong or is it just a mistake in this file?

Just to see where this come from: https://github.com/opencart/opencart/issues/9488#issuecomment-813523822

**Comment by SaifAlSubhi** [comment]
because it was not updated to '3.0.3.7'
https://github.com/opencart/opencart/blob/6c47e18239bac75f8ab26532985b4687d7a6181b/upload/index.php#L3

**Comment by tjapro** [comment]
In that case it is only necessary to change to 6 to 7, or is need something else?

**Comment by SaifAlSubhi** [comment]
https://github.com/opencart/opencart/blob/6c47e18239bac75f8ab26532985b4687d7a6181b/upload/admin/index.php#L3

**Comment by tjapro** [comment]
Is to change this two variables in my project?

**Comment by prabhatkumaroc082** [comment]
> Is to change this two variables in my project?

@danielkerr sir will look into this, it must be fixed for the next release 3.0.3.8

**Comment by mhcwebdesign** [comment]
An OpenCart install is usually done as per the embedded INSTALL.md instructions, not via composer. In your index.php and admin/index.php change the

`define('VERSION', '3.0.3.6'); `

to

`define('VERSION', '3.0.3.7'); `

**Comment by tjapro** [comment]
Changed in these files and done!
The next release will be corrrect, after all: https://github.com/opencart/opencart/blob/8d120650299584e8b5799405e2aa0e23147e3709/upload/admin/index.php#L3

**Comment by mhcwebdesign** [comment]
There is no 3.0.2.1 release of OpenCart.

**Comment by tjapro** [comment]
Sorry. Corrected comment.
