### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by tjapro** [opencart/opencart#9570]
**What version of OpenCart are you reporting this for?**
3.0.3.7

**Describe the bug**
In maintenance mode I got a 404 error page from nginx.

**To Reproduce**
1. Activate the maintenance mode in shop settings.
2. Go to shop **in private browser**
3. Get 404.

**Expected behavior**
A Maintenance mode message.

**Server / Test environment (please complete the following information):**
- VPS
- CentOS 7
- PHP 8.0.3
- Nginx 1.16.1

**Additional context**
- This issue is different this older one https://github.com/opencart/opencart/issues/9164, because now I've setup a testing enviroment and shop.
- I've checked the maintenance controller files and seems are all ok.
- I've check logs (nginx, php-fpm, OC) and nothing.

**Comment by WebkulOpencart** [comment]
not found any such issue

**Comment by tjapro** [comment]
Thanks @WebkulOpencart , but how can I debug this situation. There is something about pretty URL's or something elese that can I see with detail?

**Comment by WebkulOpencart** [comment]
@tjapro if you are using the SEO for the URLs then please verify the same on the below file if your SEO URL is valid or not.
[https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/controller/startup/seo_url.php](https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/controller/startup/seo_url.php)

**Comment by tjapro** [comment]
No, I don't use SEO URL's (and pretty URL's setting are truned off) because they give me errors with my nginx configuration...
Is it my nginx config making troubles? What should be the maintenace URL given by OC?

**Comment by WebkulOpencart** [comment]
@tjapro You need to look into the below file
[https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/controller/startup/maintenance.php](https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/controller/startup/maintenance.php)

Please let me know are you facing this issue for the home page or all pages or any specific page

**Comment by tjapro** [comment]
> Please let me know are you facing this issue for the home page or all pages or any specific page

No, I'm not. All URL's are build with /index.php?..... and this directive nginx rules well.

**Comment by tjapro** [comment]
https://github.com/opencart/opencart/blob/4f1623de428afc2180fdc301784cf9454dffe5f5/upload/catalog/controller/startup/maintenance.php#L18

When I'm in admin page, OC give me the website correctly.
This only happens when I have the admin page closed or I'm in a private browser window.

**Comment by WebkulOpencart** [comment]
Can you please share the site URL

**Comment by tjapro** [comment]
https://3037.capulanasngila.com/

**Comment by WebkulOpencart** [comment]
@tjapro, as I check Nginx server 404 not found page is showing which means the request is not going to the OpenCart instance so there is some issue with the server end,

**Comment by tjapro** [comment]
Ok. Thanks.
Do you recognize this OC URL: /config/getuser?index=0

**Comment by WebkulOpencart** [comment]
@tjapro As I checked no such code in the default file

**Comment by tjapro** [comment]
Thanks. I'll debug PHP files and nginx configuration. I'll tell you if I found something.

**Comment by WebkulOpencart** [comment]
@tjapro You can also report the same on the OpenCart forum so that you can get some solution there.

I am closing this issue.
