### ISSUE TITLE
Which in the end is a PHP version ? 

### ISSUE THREAD

**Issue by MrTomek** [opencart/opencart#9592]
8.0 ?
https://github.com/opencart/opencart/blob/master/upload/system/startup.php#L7

7.1 ?
https://github.com/opencart/opencart/blob/master/composer.json#L26

7.3 ?
https://github.com/opencart/opencart/blame/master/README.md#L5

Earn this, because you do not know what to do

**Comment by SaifAlSubhi** [comment]
all should be updated to 8+
