### ISSUE TITLE
Enhancement: Add .ico tag in header in admin

### ISSUE THREAD

**Issue by tjapro** [opencart/opencart#9595]
**What version of OpenCart are you reporting this for?**
3.0.6.7

**Describe the bug**
The frontpage has a .ico file tag in head.
the backpage/admin hasn't that.

**To Reproduce**
1. Add the .ico file to the shop.
2. Go to the admin page
3. No .ico file to show in browser tab.

**Expected behavior**
A .ico file showing.

**Server / Test environment (please complete the following information):**
- VPS
- CentOS 7
- PHP 8.0.3
- Nginx 1.16.1

**Comment by prabhatkumaroc082** [comment]
Hello @tjapro 
for now, Opencart doesn't support .ico image format, restricted on the code end as well.
If @danielkerr sir confirms then we can look into this.

**Comment by prabhatkumaroc082** [comment]
@tjapro 
you can not add .ico image from admin panel. 
if your request was to use icon in the admin panel same like front-end then try following code 
opencart admin/controller/common/header.php 
find 
`$data['description'] = $this->document->getDescription();`

add the following code before this line 
`if ($this->request->server['HTTPS']) {
			$server = HTTPS_CATALOG;
		} else {
			$server = HTTP_CATALOG;
		}

		if (is_file(DIR_IMAGE . $this->config->get('config_icon'))) {
			$this->document->addLink($server . 'image/' . $this->config->get('config_icon'), 'icon');
		}`

**Comment by prabhatkumaroc082** [comment]
#9606
