### ISSUE TITLE
Upgrade error from 3.0.3.6 to 3.0.3.7

### ISSUE THREAD

**Issue by haxcop** [opencart/opencart#9596]
**What version of OpenCart are you reporting this for?**
3.0.3.7
**Describe the bug**
Standard Upgrade method from Version 3.0.3.6 to .7
`SyntaxError: Unexpected token < in JSON at position 106 parsererror {"success":"Patch 1000 has been applied (1 of 10)","next":"index.php?route=upgrade\/upgrade\/next&step=2"}Warning: Use of undefined constant VERSION - assumed 'VERSION' (this will throw an Error in a future version of PHP`

**To Reproduce**
1. install version 3.0.3.6
2. Upload files of the new version 3.0.3.7
3. .../install/index.php?route=upgrade/upgrade
4. See an error

**Expected behaviour**
no errors? maybe?

**Server / Test environment (please complete the following information):**
 - web server
 - Operating system centOS 7
 - PHP version 7.3
 - Apache version 2.4
 - Browser(s) tested with chrome
 - Version latest

**Additional context**

**Comment by TheCartpenter** [comment]
Already reported.
