### ISSUE TITLE
Prepare statement in mPDO

### ISSUE THREAD

**Issue by revoke** [opencart/opencart#9597]
**What version of OpenCart are you reporting this for?**
3.0.3.7

**Describe the bug**
The primary DB class (system\library\db.php) has method `query` with just one parameter `$sql`. The same method in adaptor `mpdo` has two arguments - that means the prepare statement cannot be working.

**Comment by TheCartpenter** [comment]
Already removed from the master branch.

**Comment by TheCartpenter** [comment]
Remained in the maintenance branch, however.

**Comment by WebkulOpencart** [comment]
@revoke As I checked on both the OpenCart version  we send the empty array object in both the versions in the execute method
https://github.com/opencart/opencart/blob/master/upload/system/library/db/pdo.php#L29

**Comment by revoke** [comment]
@WebkulOpencart pdo.php is ok, the problem is in the main class _**db**_ for versions 3.0.x.x_ (and earlier). The method _query_ does not contain the optional attribute _params_ , so there is nothing to pass to _pdo_ class.

https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/library/db.php#L45
> 	public function query($sql) {
> 		return $this->adaptor->query($sql);
> 	}

https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/library/db/pdo.php#L51
> public function query($sql, **$params** = array()) {
> 		$this->statement = $this->connection->prepare($sql);
> 		$result = false;
> 		try {
> 			if ($this->statement && $this->statement->execute(**$params**)) {

For example, try call this simple method (with _pdo_ engine):
> public function test(){  return $this->db->query('SELECT user_id,username FROM user WHERE user_id > ?', [2]); }

I suggest this fix in the query method in db.php:
> 	public function query($sql, $params = array()) {
> 		return $this->adaptor->query($sql, $params);
> 	}

and modify definitions of query methods in files files mssql.php, mysql.php, mysqli.php and pgsql.php.

**Comment by WebkulOpencart** [comment]
@revoke We have created PR for the same and waiting for the Daniel review for the same
[https://github.com/opencart/opencart/pull/9668](https://github.com/opencart/opencart/pull/9668)

**Comment by WebkulOpencart** [comment]
We are c;
