### ISSUE TITLE
Opencart Missing Orders: $this->model_checkout_order->addOrderHistory(…) not being executed

### ISSUE THREAD

**Issue by jpneey** [opencart/opencart#9604]
Opencart 3.0.3.7

Every incoming order's order status can't be updated. Any default extension such as cash on delivery and any controller that runs `$this->model_checkout_order->addOrderHistory(...);` is not executing.

I have tried duplicating the function `addOrderHistory `to `testOrderHistory `(with the very same contents) and updated every call from `$this->model_checkout_order->addOrderHistory(...);` to `$this->model_checkout_order->testOrderHistory(...);` and `testOrderHistory` seems to work now.

I have also tested returning strings from both `testOrderHistory()` and` addOrderHistory() `and proceeds to log them. Logging works fine at the controller's end but `$this->model_checkout_order->addOrderHistory(...);` always returns a `bool(true`) rather than the string I've been trying to return. However `$this->model_checkout_order->testOrderHistory(...);` seems to return the `string ` correctly.

I'm afraid we can't reproduce it on a fresh install. The issue surfaced after manually (reimporting tables) updating opencart 2.x to opencart 3.0.3.7

**Comment by TheCartpenter** [comment]
```I'm afraid we can't reproduce it on a fresh install. The issue surfaced after manually (reimporting tables) updating opencart 2.x to opencart 3.0.3.7```

Then, the issue might simply be human error.

**Comment by jpneey** [comment]
@TheCartpenter  exactly, I've fixed it. The issue happened when I've added a custom controller that listen on `addOrderHistory`'s `before` event. The said custom controller returns a boolean making the sequence of events halt.
