### ISSUE TITLE
Remove space in review_list.twig

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#9607]
Version
OpenCart v3.0.3.2

File:
admin/view/template/catalog/review_list.twig

Line 34:

change from
`          <div  class="panel-body">`
to
`          <div class="panel-body">`

Note: Replace double space to space.

We are using HTML minify and it doesn't work very well on review list.

Thank you.

**Comment by WebkulOpencart** [comment]
PR [https://github.com/opencart/opencart/pull/9623](https://github.com/opencart/opencart/pull/9623)
