### ISSUE TITLE
Missing Address Section During Registration Process

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#9608]
Version:
OpenCart v3.

A lot of problem in v3 with registration form. Customer has problem to finish steps in one step checkouts because address missing.

Can you add feature to turn on/off missing fields in v3? OpenCart v1 and v2 has these fields.

I understand if they use default checkout they enter address in 2. or 3. step.

Registration Form:
https://demo.opencart.com/index.php?route=account/register

Posts:
https://forum.opencart.com/viewtopic.php?t=199402
https://forum.opencart.com/viewtopic.php?t=204081
https://forum.opencart.com/viewtopic.php?t=191880

Thank you.

**Comment by WebkulOpencart** [comment]
@danielkerr Please confirm for the same.

**Comment by danielkerr** [comment]
ARE U FUCKING STUPIED WASTING PEOPLES TIME!

NO ISSUE!

Banned!
