### ISSUE TITLE
No rate limit on forget password leads to email-triggering

### ISSUE THREAD

**Issue by gdegraaf** [opencart/opencart#9610]
**Opencart version**
3.0.2.0

**Describe the bug**
No rate limit on forget password leads to email-triggering

**Reproduce Steps:**
1- open forgot password page
2-enter email id   and intercept a request in burpsuite
3-request send to intruder
4-use null payloads and start attack.
5-server side  have received multiple emails

**Expected behavior**
A rate limit on forgot password form

**Screenshots / Screen recordings**
none

**Server / Test environment (please complete the following information):**
nvt

**Comment by Webkul-Opencart** [comment]
not found this issue, mail shows only once.
