### ISSUE TITLE
use arrays to store attribute data and option data would speed up the site.

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#9611]
use json_encode to store array into the database.
and use json_decode to get data from database.
for example
[{"attribute":"Model NO.","value":"PB933"},{"attribute":"Size","value":"14cm"},{"attribute":"Trademark","value":"Apple"}]

by doing so, some tables and fields are no longer necessary.

**Comment by WebkulOpencart** [comment]
Please mention the OpenCart version.

**Comment by danielkerr** [comment]
Also mention where u got u're coding PhD.
