### ISSUE TITLE
[master] undefined property Proxy::1 in /admin/controller/localisation/country.php on line 338

### ISSUE THREAD

**Issue by SaifAlSubhi** [opencart/opencart#9613]
**What version of OpenCart are you reporting this for?**
master-branch

**Describe the Bug**
There is this json syntax error if you try to save a country entry at system->localisation->countries->edit
```
undefined property: Proxy::1 in /admin/controller/localisation/country.php on line 338
```

**To Reproduce**
1. Login into admin control panel
2. go to system->localisation->countries->edit
3. Try to save and you will get this json syntax error

**Server / Test Environment:**
ubuntu 20.04.2
apache 2.4.41
PHP 8.0.3
mySQL 8.0.23
Google Chrome Stable 90.0.4430.72

**Additional Context**
https://github.com/opencart/opencart/blob/fa1ebfc3068eb8ba8765f5c5cc373d0fc853a58f/upload/admin/controller/localisation/country.php#L338

**Comment by TheCartpenter** [comment]
Confirmed. admin/model/localisation/country.php do not have translation methods by design.

**Comment by SaifAlSubhi** [comment]
fixed
