### ISSUE TITLE
[OC 3.0.3.7] Missing system/storage/vendor/react/promise files

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#9618]
**What version of OpenCart are you reporting this for?**
3.0.3.7 dowloaded from github

**Describe the bug**
As per the title, the files from **system/storage/vendor/react/promise** are missing!

**To Reproduce**
1. Go to 'https://github.com/opencart/opencart'
2. Click on select Tags 3.0.3.7
3. Click on Code > Download opencart.zip

**Expected behavior**
Missing files should be included.
BTW.: If you download from https://www.opencart.com/index.php?route=cms/download/download&download_id=63 the missing files are included! Hence it looks like github got corrupted.

**Comment by webkul-dilip** [comment]
Hello,
Hence it looks like github got corrupted.
>> Dependency file missing here, these files manage only at Opencart zip(https://www.opencart.com/index.php?route=cms/download/download&download_id=63).
If you download from the github then please follow the the blog https://webkul.com/blog/how-to-install-opencart-in-3-0-6-0-version/
