### ISSUE TITLE
Unexpected exit() in Opencart\System\Engine\Registry::get()

### ISSUE THREAD

**Issue by kktsvetkov** [opencart/opencart#9619]
I think there is some piece of dev debug code leaked in `system/engine/registry.php` that was introduced by 6d07193542809ee 20 days ago:

```php 
	public function get(string $key): object {
		if (!$this->data[$key]) {
			exit('Missing ' . $key);
		}
	...
```
First, I think this will trigger a warning for a missing array element if that element is not defined yet. 
Second - it seems this method will trigger the `exit()` if the array element is empty. 

Surely this seems like some remnant of debugging and not really something that is intended to be there

**Comment by cgcmart** [comment]
SyntaError: Unexpected token < in JSON at position 0
Warning: Undefined array key "model_catalog_product" in .../system/engine/registry.php on line 51
Missing model_catalog_product

**Comment by WebkulOpencart** [comment]
Please mention the OpenCart Version

**Comment by kktsvetkov** [comment]
@WebkulOpencart Look at the first sentence of my comment, I gave you the commit where this is introduced, 6d07193542809ee1c5732. This is in the latest master branch and it hasn't been released yet. If you look at 3.0.3.7, you will see that problematic code is not there:

https://github.com/opencart/opencart/blob/3.0.3.7/upload/system/engine/registry.php
```php 
	public function get($key) {
		return (isset($this->data[$key]) ? $this->data[$key] : null);
	}
```
