### ISSUE TITLE
PHP Session Data Not Persisting Between Requests (Checkout) 

### ISSUE THREAD

**Issue by dj12djdjs** [opencart/opencart#9624]
**What version of OpenCart are you reporting this for?**
3.0.3.7

**Describe the bug**
I cannot complete the checkout phase as guest.
The problem occurs between "/checkout/guest/save" and "/checkout/guest_shipping"
I've modified the save method in "/checkout/guest/save" and index method in "/checkout/guest_shipping" to output the JSON of $this->session->data. Here are the results:

_/checkout/guest/save_
```
{
   "language":"en-gb",
   "currency":"CAD",
   "account":"guest",
   "guest":{
      "customer_group_id":"1",
      "firstname":"My First Name",
      "lastname":"My Last Name",
      "email":"my_email@email.com",
      "telephone":"1111111111",
      "custom_field":[
         
      ],
      "shipping_address":"1"
   },
   "payment_address":{
      "firstname":"My First Name",
      "lastname":"My Last Name",
      "company":"",
      "address_1":"My House",
      "address_2":"",
      "postcode":"My Postal",
      "city":"My Town",
      "country_id":"38",
      "zone_id":"610",
      "country":"Canada",
      "iso_code_2":"CA",
      "iso_code_3":"CAN",
      "address_format":"",
      "custom_field":[
         
      ],
      "zone":"Ontario",
      "zone_code":"ON"
   },
   "shipping_address":{
      "firstname":"My First Name",
      "lastname":"My Last Name",
      "company":"",
      "address_1":"My House",
      "address_2":"",
      "postcode":"My Postal",
      "city":"My Town",
      "country_id":"38",
      "zone_id":"610",
      "country":"Canada",
      "iso_code_2":"CA",
      "iso_code_3":"CAN",
      "address_format":"",
      "zone":"Ontario",
      "zone_code":"ON",
      "custom_field":[
         
      ]
   }
}
```

_/checkout/guest_shipping_  (You will find the JSON at the end of the string)
`<b>Notice</b>: Undefined index: guest in <b>/home/$PATH/catalog/controller/checkout/guest_shipping.php</b> on line <b>67</b>{"language":"en-gb","currency":"CAD"}`

As a result the checkout processes cannot proceed any further.

**To Reproduce**
1. This is a clean install of open cart.
2. Import Products.
(checkout works up to this point)
3. Delete USA, EUR currency
4. Add and set default CAD currency
The problem happens every time I change the currency (Or finish setting up my localization) I haven't pinpointed the exact spot.
I've reinstalled opencart 2 times every time this happens after setting up localization.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?  Web server
 
 - PHP version: 7.2.34

 - Browser(s) tested with [e.g. chrome, safari - if applicable]:  Google Chrome

**Comment by prabhatkumaroc082** [comment]
I haven't found any issue with checkout, you can try replacing checkout files from https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance as multiple issues are fixed for the 3.0.3.8 release

Also, try requesting on the OC forum, if you still face any issues. Closing this issue now.
