### ISSUE TITLE
The default address cannot be unselected.

### ISSUE THREAD

**Issue by sabeti05** [opencart/opencart#9626]
**What version of OpenCart are you reporting this for?**
3.0.3.7

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Customers cannot deselect the default address.

**To Reproduce**
1. Go to the customer account / Modify your address book entries
2. Add a new address or edit an existing one
3. Choose "Yes" for the "Default Address" option and save it.
4. Edit the same address and this time choose "No" for the "Default Address" option and save.
5. Edit the same address again, You will see "Yes" is still selected for the "Default Address".

**Expected behavior**
In step 5, "No" should be selected.

**Additional context**
I know we can deselect the default address by editing another address and choosing it as the default address, This will deselect the default address for the first address.
But since there is a "No" option in the form, It can confuse customers.

In this file:
`catalog\model\account\address.php`

We have:
```
if (!empty($data['default'])) {
	$this->db->query("UPDATE " . DB_PREFIX . "customer SET address_id = '" . (int)$address_id . "' WHERE customer_id = '" . (int)$this->customer->getId() . "'");
}
```

I think we can fix it like this:
```
if (!empty($data['default'])) {
	$default_address_id = $address_id;
} else {
	$default_address_id = 0;
}

$this->db->query("UPDATE " . DB_PREFIX . "customer SET address_id = '" . (int)$default_address_id . "' WHERE customer_id = '" . (int)$this->customer->getId() . "'");
```

**Comment by prabhatkumaroc082** [comment]
well, it should not confuse the customers because each address either will have a "no" or "yes" option selected.
If you want to make any other address default then set it yes.
