### ISSUE TITLE
[QUESTION] (3.x/4.x) > How to install event only?

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#9627]
With OC 3.x "Modifications" are possible via the intgrated OCMod - fine.
With 4.x this option does not exist anymore - also fine.

But .. **how to install an Event only?**
Which has at least 1 or 2 files (catalog and/or admin) with the functions only, but nothing further - and only a single SQL-query.
Cannot see anything in the code (wether 3.x nor 4.x) to be able to install the SQL needed to add Event(s) only (which was easy before with OCMod).

Who know more about this?

Problem is, adding an Extension (e.g. a Module) is easy, has the code for adding autoamtically the event inside.
But what if it is NOT a Module/Shipping/etc. ?
Controller therefore will never be called, code for Event cannot be installed.

**Comment by chulcha** [comment]
I am making a extension controller with install and uninstall methods

**Comment by stalker780** [comment]
As far as I understand, install() function still does not work in OC4.
https://github.com/opencart/opencart/issues/9069

**Comment by osworx** [comment]
> 
> 
> I am making a extension controller with install and uninstall methods

Nice try .. but this extension controller would be displayed under modules > therefore useless and will lead to confusion.
Because the only action inside should (and would) be the installation (adding) of the event (code) and exucure later the event(s) - nothing else.

@stalker780 Not true, install and uninstall functions still exist in OC 4.x (while maybe not called correctly as you mention there):
https://github.com/opencart/opencart/blob/dcf0af1981b03f09dc3e4e2fc3e02111c5e3084f/upload/admin/controller/extension/module.php#L121

and:
https://github.com/opencart/opencart/blob/dcf0af1981b03f09dc3e4e2fc3e02111c5e3084f/upload/admin/controller/extension/module.php#L149

But none of them are required (at least it would be good if those functions would be still alive).
And - as written: only to add 1 line to the database (in case for a simple event) there should be a easier way to accomplish.
Also to hide such "dummy" modules which have no further functions (except to fullfill the event) because if is's an admin module it will be displayed in the list!

The problem is: in OC 3.x I have the install.xml with 2 lines (search & replace) via OCMod.
In OC 4.x this option does not exist anymore - all should be done via Events (which is absolutely okay) - but not being to install them leads to unwanted extensions!

**Comment by chulcha** [comment]
> install them leads to unwanted extensions!

At least some kind of logging is required.
I don't see anything wrong with additional extensions.
Extensions but not modules. Without status, but with the install feature and install and гninstall methods.

The template can contain the output of the description of the extension, indicating the support addresses and more.

**Comment by osworx** [comment]
> 
> 
> > install them leads to unwanted extensions!
> 
> At least some kind of logging is required.
> I don't see anything wrong with additional extensions.
> Extensions but not modules. Without status, but with the install feature and install and гninstall methods.
> 
> The template can contain the output of the description of the extension, indicating the support addresses and more.

Leads to more work: 1 template, plus several translations .. if you are developing it correct!
Having finally: 1 controller, 1 template, at least min. 2 language files (if english is not native, and many users do not speak English!).

And - not to forget: those "Specialists" assigning useless Modules to templates (Design).
Also a list of Extensions (modules) with - if you practise it that way - maybe 100-200 modules.

No - not that way.
And all of that to simply add 1 line to the database!

**Comment by mhcwebdesign** [comment]
I use pseudo modules because they have the install or uninstall functionality, but exclude them from the layouts:

For example, given an extension/module named 'foo', I'd use this:

```
	public function install() {
		// add event handlers
		$this->load->model('setting/event');
		$code = 'module_foo';
		$app = 'admin/';
		$trigger = 'view/design/layout_form/before';
		$route = 'extension/module/foo/eventViewDesignLayoutFormBefore';
		$this->model_setting_event->addEvent( $code, $app.$trigger, $route );
		
		// do other install functionality
		// .....
	}

	public function uninstall() {
		// remove event handlers
		$this->load->model('setting/event');
		$code = 'module_foo';
		$this->model_setting_event->deleteEventByCode( $code );
		
		// do other uninstall functionality
		// ....
	}

	// event handler for admin/view/design/layout_form/before
	public function eventViewDesignLayoutFormBefore( &$route, &$data, &$template=null ) {
		// exclude 'foo' from OpenCart's modules layout
		foreach ($data['extensions'] as $key=>$extension) {
			if ($extension['code'] == 'foo') {
				unset($data['extensions'][$key]);
			}
		}
		return null;
	}
```

**Comment by osworx** [comment]
> 
> 
> I use pseudo modules because they have the install or uninstall functionality, but exclude them from the layouts:

Have you tried it also with the latest OC 4.x code?
As mentioned before, both (install & uninstall) seems not be working.
To be honest, 4.x is not an option right now - therefore did not try it by myself ..

You approach is how I know you are working, good and simple.
But - sorry again: just for a simple database entry all of this is much work (and workarounds).

Daniel should add a way to add Events on a simple basis.
Of course could "develop" within a few minutes a new extension doing exactly this, but this is also not the ricght way.

**Comment by mhcwebdesign** [comment]
The latest OC 4.x is broken anyway with regards to handling extensions, including its issues with the strange namespaces. I was to look into it, but haven't yet found the time for it as I was quite busy. In general I agree with you that OC 4 should also provide a proper install / uninstall function for extensions without having to use pseudo-modules.

**Comment by chulcha** [comment]
I disagree with you.
Any actions must be under the control of an administrator
Installs or uninstalls
Activation or deactivation
Adding fields, indexes and more
Let it be pseudo-modules or whatever, but it should be reflected.

**Comment by osworx** [comment]
> 
> 
> I disagree with you.
>

That's up to you want you agree or not ..

> Any actions must be under the control of an administrator
> Installs or uninstalls
> Activation or deactivation
> Adding fields, indexes and more
> Let it be pseudo-modules or whatever, but it should be reflected.

Who else should open the Backend (Administration) if not an Admin?
And IF, simply disable as "Site" or "Super" Admin the right (action) to call the installer (see permissions) - as it should be for all backend users who are no admins!

And when you say "Any actions must be under control .. and so on .."
Because there is actual no logging per default aof all those action, anybody with wrong permissions can do what he/she/it/somewhat wants to do!

**Comment by danielkerr** [comment]
i think this is all fixed now.
