### ISSUE TITLE
Add to Cart Issue appearing 

### ISSUE THREAD

**Issue by wbcmarketing** [opencart/opencart#9629]
**What version of OpenCart are you reporting this for?**
               Version 3.0.3.6

**Describe the bug**
When you go to add a product to our shopping cart the product is not added but if you leave the product page to visit another product or refresh the cart items will then show up
What section does it affect?

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by TheCartpenter** [comment]
No URL posted. Using an older OC version. However, this issue looks like .htaccess, config.php and / or admin/config.php files addressing issues. This incident request should rather be posted on the forum.
