### ISSUE TITLE
Basic Captcha Session Problem

### ISSUE THREAD

**Issue by nethubdesign** [opencart/opencart#9630]
**What version of OpenCart are you reporting this for?**
- version 3.0.3.7
- version 3.0.3.6
- version 3.0.3.1

**Describe the bug**

The basic Captcha is not working sometimes. The problem can be duplicated at Account Register page (account/register) and Checkout page (checkout/checkout). Even we enter the correct captcha from the captcha image, the incorrect captcha message will still prompt out. The problem should be related to the captcha session and more details can be found as below.

**To Reproduce**

1. edit system/library/session.php (line 81) as below:

```
public function close() {
# debug
$file = fopen("/var/www/vhosts/test.com/debug.log","a");
fwrite($file, $this->session_id . ' - ' . json_encode($this->data) . "\r\n");
fclose($file);
$this->adaptor->write($this->session_id, $this->data);
}
```

2. go to check out page, check inspect element in the browser (Ctrl-Shift-C for Firefox) > Network tab > click "Continue" on the checkout page > you will see accessing below 4 URLs by AJAX:

```
index.php?route=checkout/guest
index.php?route=extension/captcha/basic/captcha
index.php?route=checkout/checkout/customfield&customer_group_id=1
index.php?route=checkout/checkout/country&country_id=222
```

3. check the debug.log, there are 4 lines like below, note that "0f584c" is the old catpcha value, this means that the captcha value is updated to the database 4 times in this order: 0f584c > 9ea9d6 > 0f584c > 0f584c , you can see the captcha value was updated to the "0f584c" finally, that's why sometimes the captcha works and sometimes it doesn't.

```
2333aeefdabfa7a76a1b78a7c9 - {"language":"en-gb","currency":"USD","captcha":"0f584c"}
2333aeefdabfa7a76a1b78a7c9 - {"language":"en-gb","currency":"USD","captcha":"9ea9d6"}
2333aeefdabfa7a76a1b78a7c9 - {"language":"en-gb","currency":"USD","captcha":"0f584c"}
2333aeefdabfa7a76a1b78a7c9 - {"language":"en-gb","currency":"USD","captcha":"0f584c"}
```

**Expected behavior**

One captcha session should be generated in check out page and account register page. The captcha check can be passed when entering the correct captcha.

**Screenshots / Screen recordings**

Error screenshot: https://forum.opencart.com/download/file.php?id=41057&sid=d2451c383af57a8770f508b44534d9c4

We also recorded a video so that everyone can see the problem easily
https://www.youtube.com/watch?v=yBlFnuHXkMY

You can see that the first time $this->session->data['captcha'] is empty, after visit contact us page to load the captcha, $this->session->data['captcha'] is correct for contact us page. But in checkout page $this->session->data['captcha'] is always wrong .

**Server / Test environment (please complete the following information):**

 - Operating system: CentOS 7.6 x64 with Plesk Control Panel 18
 - PHP version: PHP 7.3.20
 - Apache version: Apache/2.4.6 (CentOS)
 - Browser(s) tested with [e.g. chrome, safari - if applicable]: Firefox 71.0, Google Chrome 80.0

**Additional context**

Original post from OpenCart forum: https://forum.opencart.com/viewtopic.php?f=201&t=223579
Also, some of the people has mentioned same problem in the forum long time ago.
Hope OpenCart developer or someone can solve it.

**Comment by yvonn** [comment]
You can try this:
Go to 
catalog/controller/extension/captcha/basic.php
replace this line (line 20)

`if (empty($this->session->data['captcha']) || ($this->session->data['captcha'] != $this->request->post['captcha'])) {`

by adding this line

`if (empty($this->session->data['captcha']) || empty($this->request->post['captcha']) || ($this->session->data['captcha'] != $this->request->post['captcha'])) {`

And replace this line

`header('Content-type: image/jpeg');`

by adding this lines

`$this->response->addHeader('Content-type: image/jpeg');`
`$this->response->addHeader('Cache-Control: no-cache');`
`$this->response->addHeader('Expires: Sat, 26 Jul 1997 05:00:00 GMT');`

**Comment by prabhatkumaroc082** [comment]
no issue found with captcha, it is working fine.
The video you attached doesn't display any problem. You will see always previous value on the session.
check line 12 on file view/theme/default/template/extension/captcha/basic.twig
`<img src="index.php?route=extension/captcha/basic/captcha" alt="" />`
it will call this method which will return a captcha image and set captcha code in session also.

Also, lots of the issues have been fixed for the 3.0.3.8 release so try replacing the checkout file from https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
closing this issue now.

**Comment by nethubdesign** [comment]
I really don't know why you found no issue but other users in issue  #7968 (@ADDCreative, @ciotuvasile,) and our company, and also our many customers found the problem, we can duplicate the problem easily.

I just followed your url (https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance/upload) to download & replace OC files below, and I also already refreshed in Extensions > Modifications as well, but the problem still persists.

\upload\catalog\view\theme\default\template\*
\upload\catalog\controller\checkout\*
\upload\catalog\model\checkout\* 



I recorded a new video to show the problem more clearly: https://youtu.be/8W6ebIpau9o

What I did are as below:

 1. edit system/library/session.php (line 81) as below:

```
public function close() {
	# debug
	$file = fopen("/var/www/vhosts/test.com/debug.log","a");
	fwrite($file, $this->session_id . ' - ' . json_encode($this->data) . "\r\n");
	fclose($file);
	$this->adaptor->write($this->session_id, $this->data);
}
```

2. edit catalog/controller/extension/captcha/basic.php (line 21) as below:
`return $this->language->get('error_captcha') . ' - current session is: ' . json_encode($this->session->data);`

3. test as our video did, please use browser private mode to avoid any existing session/cookie.

**Comment by nethubdesign** [comment]
In addition, anyone can also duplicate the problem via our testing site here: http://oc-latest.internal.demo360.net

**Comment by mhcwebdesign** [comment]
@nethubdesign: I just tested a guest checkout on your testing site, using Firefox, and there are no issues.

Having said that, the basic captcha is easily overcome by many most spambots these days and doesn't really offer much of a protection anymore. We use the SpamBot Buster tool for protection, which doesn't use a captcha at all.

**Comment by ADDCreative** [comment]
> In addition, anyone can also duplicate the problem via our testing site here: http://oc-latest.internal.demo360.net

Yes, I was able to duplicate the issue at that site. It took a few tries but eventually a race condition showed itself with an older request overwriting the CAPTCHA value.

![image](https://user-images.githubusercontent.com/2039130/119328526-1ccb8a80-bc7c-11eb-9d7e-73f8828e8570.png)

I guess if and how often it shows will be down to different factors. such as browser response, client/server connection and server load. I believe the master branch uses chained AJAX calls, so should not be affected.
https://github.com/opencart/opencart/search?q=chained&type=commits

**Comment by nethubdesign** [comment]
Oh thanks ADDCreative, I am not alone here.

We introduce OpenCart to our customers to use, not every customer want to pay additional for extension. Secondly even basic captcha is easily overcome by many most spambots, but customers would still expect it WORKS normally but not happens "Verification code sometimes does not match the image." .

I agree with ADDCreative, it is a connection race, the problem does not always happen.

**Comment by prabhatkumaroc082** [comment]
@nethubdesign 
do a little change
open file catalog/controller/extension/captcha/basic,php
go to line 26, remove the following code
`$this->session->data['captcha'] = substr(sha1(mt_rand()), 17, 6);`

then add that removed line of code after `$data['route'] = $this->request->get['route'];`

Sample code:  https://prnt.sc/13clxa5

now save and perform testing.

**Comment by ADDCreative** [comment]
> I believe the master branch uses chained AJAX calls, so should not be affected.

Scrap that part of my comment. Master branch is also affected by this issue, as the actual CAPTCHA image in not loaded by a AJAX call, only the form is.

**Comment by nethubdesign** [comment]
@prabhatkumaroc082 It works after follow your instruction, hope it can be included in future release, thank you very much.

> open file catalog/controller/extension/captcha/basic,php
> go to line 26, remove the following code
> `$this->session->data['captcha'] = substr(sha1(mt_rand()), 17, 6);`
> 
> then add that removed line of code after `$data['route'] = $this->request->get['route'];`

**Comment by prabhatkumaroc082** [comment]
PR #9682 
it's under testing.
