### ISSUE TITLE
When will the oc4 version be released?

### ISSUE THREAD

**Issue by mezzat11** [opencart/opencart#9634]
Hello 
, When will the oc4 version planned to released?

**Comment by IP-CAM** [comment]
why do you wanna know ? :)

**Comment by mhcwebdesign** [comment]
Not anytime soon!

**Comment by osworx** [comment]
@mhcwebdesign Why so pessemistic ;)

**Comment by Hkr32** [comment]
Nobody knows this...

**Comment by mezzat11** [comment]
Waiting for daniel comment :wave:

**Comment by chongshengdz** [comment]
it should be very soon now.
almost done, i think.

**Comment by IP-CAM** [comment]
Some Nut's already try to use it ... :) 
[OC Forum](https://forum.opencart.com/viewtopic.php?f=202&t=222389)

**Comment by mezzat11** [comment]
@danielkerr ??

**Comment by danielkerr** [comment]
It's what I'm working on at fue all pages to ajax. Ill post my to-do listll blast. It would have been sooner but decided to change all pages to use json. I'll post my to-do list. Not much left. Everything left needing doing has been started and not finished.

**Comment by SaifAlSubhi** [comment]
php-8.0 support + ajax & json are both great to see opencart have

I think what will be good for future is to have an official modern storefront template repo.
The current template looks little bit old.

**Comment by danielkerr** [comment]
Any one react or Vue added before I finish the ajax stuff

**Comment by stalker780** [comment]
Daniel, it would be great to have modern Bootstrap5 in OC4. No matter, with or without jquery.

**Comment by danielkerr** [comment]
Ffs yes bs5 will be done today after doing some testing

**Comment by mhcwebdesign** [comment]
> Any one react or Vue added before I finish the ajax stuff

No, please don't. We need less Javascript, not more. These various Javascript libraries come and go, no need to permanently re-inventing the wheel. We don't want to end up in Journal3-like bloatware.

**Comment by FelipoAntonoff** [comment]
Hi Daniel, we used Vue.js a little in some modules a few years ago, I like it in general and its ease of use, but I only recommend it if it's runtime and only on necessary screens. In some cases uses even with Twig together too, it works very well together.

Looking forward to the new version and congratulations on the work of the entire team, I consider Opencart one of the best Ecommerce platforms.

**Comment by rsuchovsky** [comment]
Do you think we can expect a new version this year?
