### ISSUE TITLE
When the order is entered manually in the admin panel, the prices of the discounts of the products according to the customer groups do not come.

### ISSUE THREAD

**Issue by aydoganburak** [opencart/opencart#9640]
I noticed a bug in our 3.0.3.2 version and fixed it. The same problem exists in your version 3.0.3.7.

I needed to let you know as well, as I fixed the error.

Error: When the order is entered manually in the management panel, the prices of the discounts of the products according to the customer groups are not displayed.

Solution: I added the following codes after 34th line in system / library / cart / cart.php getProducts function.

```
if(!empty($this->session->data['customer']['customer_id'])) {
	$customer_id = $this->session->data['customer']['customer_id'];
}

if(!empty($this->session->data['customer_id'])) {
	$customer_id = $this->session->data['customer_id'];
}

$customer_group_id = NULL;
if(!empty($customer_id)){
	$customer_info = $this->db->query("
	SELECT * FROM " . DB_PREFIX . "customer
	WHERE customer_id = '" . (int)$customer_id . "'");
	if(!empty($customer_info)){
		$customer_info = $customer_info->row;
		$this->session->data['customer']["customer_group_id"] = $customer_info["customer_group_id"];
		$customer_group_id = $customer_info["customer_group_id"];
	} else {
		$this->session->data['customer']["customer_group_id"] = $this->config->get('config_customer_group_id');
		$customer_group_id = $this->config->get('config_customer_group_id');
	}
} else {
	$customer_group_id = $this->config->get('config_customer_group_id');
}
```

I would appreciate if you approve my solution. It gives me pleasure to support you.

Good work.
Best regards.

**Comment by TheCartpenter** [comment]
Already re-worked on the master branch. The API is handled differently nowadays than the ones that were handled on previous releases.

**Comment by Webkul-Opencart** [comment]
no such issue found in version 3.0.3.7(PFA):
x-special/nautilus-clipboard
copy
file:///home/users/vrinda.sharma/Desktop/Screenshot18.png
x-special/nautilus-clipboard
copy
file:///home/users/vrinda.sharma/Desktop/Screenshot19.png
x-special/nautilus-clipboard
copy
file:///home/users/vrinda.sharma/Desktop/Screenshot20.png

**Comment by danijelGombac** [comment]
@Webkul-Opencart This is issue occurs if you do not add customer group in config_customer_group_display. When you have internal customer groups for B2B.

https://github.com/opencart/opencart/blob/e07ec591169e1e6aa874e1fdc0125787b6226af3/upload/catalog/controller/api/customer.php#L58-L63

**Comment by aydoganburak** [comment]
> no such issue found in version 3.0.3.7(PFA):
> ![Screenshot18](https://user-images.githubusercontent.com/42890212/117422682-84c06800-af3d-11eb-8fd9-d87633a9bda3.png)
> 
> ![Screenshot19](https://user-images.githubusercontent.com/42890212/117422789-a15ca000-af3d-11eb-8661-730e6e2763b0.png)
> ![Screenshot20](https://user-images.githubusercontent.com/42890212/117422815-a7eb1780-af3d-11eb-878e-dab21cccfb25.png)

When a different discount is made from the normal customer group, the order is based on the discount of the normal customer group. Of course, this is within the scope of B2B, but I reported it because I thought there was a problem.

**Comment by TheCartpenter** [comment]
Since there are no issues found in OC v3.0.3.7, then it simply means the reported issue has already been solved.

**Comment by prabhatkumaroc082** [comment]
> // Customer Group 
>  if (is_array($this->config->get('config_customer_group_display')) && in_array($this->request->post['customer_group_id'], $this->config->get('config_customer_group_display'))) { 
>  	$customer_group_id = $this->request->post['customer_group_id']; 
>  } else { 
>  	$customer_group_id = $this->config->get('config_customer_group_id'); 
>  }

Yes, this line of code will affect as you reported. The customer groups must be allowed from admin settings then only it will give you valid result.



> When a different discount is made from the normal customer group, the order is based on the discount of the normal customer group. Of course, this is within the scope of B2B, but I reported it because I thought there was a problem.

We understand your concern but if you will allow that customer group from admin settings config_customer_group_display then it will give you valid results. You can apply the required changes for your store.

**Comment by danijelGombac** [comment]
@prabhatkumaroc082 This also affect on custom field validation process. There should be an error message like "Selected customer group is not in allowed list!", instead of just replace selected customer_group_id.

**Comment by yupaul** [comment]
> We understand your concern but if you will allow that customer group from admin settings config_customer_group_display then it will give you valid results. You can apply the required changes for your store.

If customer has been manually (or by other means) assigned to a customer group that is not on a display list, and that group has specials / discounts associated with it, then customer will get special price / discount while making regular order from the front end. That discount / special will disappear if the order is edited in admin. This behavior is at very least inconsistent.

**Comment by yupaul** [comment]
> 
> 
> Already re-worked on the master branch. The API is handled differently nowadays than the ones that were handled on previous releases.

Where is it re-worked? Master branch contains exact same code:

https://github.com/opencart/opencart/blob/cfaf1100f477644004b3d7e9589ab3b45f370086/upload/catalog/controller/api/customer.php#L59

**Comment by TheCartpenter** [comment]
> > Already re-worked on the master branch. The API is handled differently nowadays than the ones that were handled on previous releases.
> 
> Where is it re-worked? Master branch contains exact same code:
> 
> https://github.com/opencart/opencart/blob/cfaf1100f477644004b3d7e9589ab3b45f370086/upload/catalog/controller/api/customer.php#L59

https://github.com/opencart/opencart/blob/master/upload/admin/controller/sale/api.php

**Comment by prabhatkumaroc082** [comment]
if any customer group is not enabled from settings then the default group will be used.
You can apply some changes for your store

$customer_group_id = $this->request->post['customer_group_id'];

			if (!is_array($this->config->get('config_customer_group_display')) || !in_array($this->request->post['customer_group_id'], $this->config->get('config_customer_group_display'))) {
				$json['error']['warning'] = "Some error that you want to display";
			}

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart/blob/master/upload/install/opencart.sql#L1865

**Comment by aydoganburak** [comment]
I think it will cause the same problem when there is more than one customer group. Because the default customer group can be 1st group. But suppose there are groups 2 and 3. We will add orders to the customer in the 3rd group through the panel.

Inside the product:
Normal Price: $ 50
Group 1: $ 40
Group 2: $ 30
Group 3: $ 25
If we think it is, the price of the product will come as $ 40 in this case.

However, this customer can buy this product for $ 25.

**Comment by TheCartpenter** [comment]
> I think it will cause the same problem when there is more than one customer group. Because the default customer group can be 1st group. But suppose there are groups 2 and 3. We will add orders to the customer in the 3rd group through the panel.
> 
> Inside the product:
> Normal Price: $ 50
> Group 1: $ 40
> Group 2: $ 30
> Group 3: $ 25
> If we think it is, the price of the product will come as $ 40 in this case.
> 
> However, this customer can buy this product for $ 25.

Yes, that would be correct. Which is why, Opencart originally has the customer group ID of 1 from fresh installation. If the customer group ID is not defined by the admin, the Opencart is not to blame. However, since customer group 2 and 3 is also selected by the API user, this will definitely affect pricing with the orders and, on that end, that is normal. Where it is less normal is if a customer group ID does not match the customer with the API orders, a JSON error message would then need to be shown.

Since the admin API has also been re-worked, in the mean time, the customer groups are also involved in the additions. However, both ends residing on those APIs does not seem to sync between customer groups at this time unfortunately. That would be another problem solving if they both were.

**Comment by prabhatkumaroc082** [comment]
> I think it will cause the same problem when there is more than one customer group. Because the default customer group can be 1st group. But suppose there are groups 2 and 3. We will add orders to the customer in the 3rd group through the panel.
> 
> Inside the product:
> Normal Price: $ 50
> Group 1: $ 40
> Group 2: $ 30
> Group 3: $ 25
> If we think it is, the price of the product will come as $ 40 in this case.
> 
> However, this customer can buy this product for $ 25.

Logged user will not face this problem in the front-end, it will be 25. you can enable all groups from settings for admin order management or apply the above-suggested code for displaying errors.

also, if you don't want to validate back-end setting then remove validation and simple add this line 
$customer_group_id = $this->request->post['customer_group_id'];

**Comment by aydoganburak** [comment]
I don't think I can explain the problem properly. I solved the problem I encountered in my project. There is no question for me. My goal is only to help people who will face this situation.

I will tell you as soon as possible with a photo.

**Comment by prabhatkumaroc082** [comment]
> I don't think I can explain the problem properly. I solved the problem I encountered in my project. There is no question for me. My goal is only to help people who will face this situation.
> 
> I will tell you as soon as possible with a photo.

I know what is the issue, you explained already. you fixed as per your need but if any user will face this, he can allow all groups from settings. And also default things is only for that case if any condition is not matched.

It is causing the same, if settings are not matched then finding default customer group. I think we don't need to discuss more, closing this issue now.

**Comment by 5thpower** [comment]
I just want to thank aydoganburak as I faced exactly the same issue. With this topic, I was able to resolve the issue without spend huge of resources to dig into the details. I just removed the 'validation' in api/customer.php and it works perfect!!!
