### ISSUE TITLE
[master] Ugrade process - Wrong table name (typo)

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#9641]
In the file upload/install/controller/upgrade/upgrade_3.php
in the line 434
is 
$this->db->query("DELETE FROM `" . DB_PREFIX . "settings` WHERE `key` = '" . $this->db->escape($key) . "'");
but has to be
$this->db->query("DELETE FROM `" . DB_PREFIX . "setting` WHERE `key` = '" . $this->db->escape($key) . "'");

**Comment by TheCartpenter** [comment]
Already posted: https://github.com/opencart/opencart/pull/9638 .
