### ISSUE TITLE
pickup from store should have a list of store locations to choose from

### ISSUE THREAD

**Issue by tyler-x** [opencart/opencart#9642]
If store was config with multiple store locations, the the pick up from store plugin should have a list of location to choose from at the check out page.

**Comment by TheCartpenter** [comment]
Which OC version are you posting about and which store plugin are you referring too?

**Comment by tyler-x** [comment]
I'm using 3.0.3.6 and it's the shipping/pickup plugin that comes with the opencart by default.

**Comment by TheCartpenter** [comment]
Such locations could be added into the admin orders where the admin would need to choose the location prior to switch the order statuses rather than setting the possibility to customers to choose their locations since locations are normally administratively set.

**Comment by TheCartpenter** [comment]
It also looks like there are shipping service providers offering such options nowadays.

**Comment by prabhatkumaroc082** [comment]
a store owner could understand from which store the order is placed and share the pickup location with the customer via order history.

You can modify the code as well if you want to display the address to the customer on the shipping choose step
open file catalog/language/en-gb/extension/shipping/pickup.php
find Pickup From Store
replace Pickup From Store (%s)

open file catalog/model/extension/shipping/pickup.php
find $this->language->get('text_description')
replace 
sprintf($this->language->get('text_description'), $this->config->get('config_address')),
