### ISSUE TITLE
OpenCart download

### ISSUE THREAD

**Issue by RobineSavert** [opencart/opencart#9644]
When I download the latest version of OpenCart from the website, the file structure and theme version is completely different from this master branch. 

The default theme uses a jQuery file that is as old as time, and a very old Bootstrap version. 

What am I missing? I downloaded the master branch zip yesterday & am trying to upload (for the last 24 hours, it takes forever and when it's finished I'm getting some major errors).

I want the latest theme version that's on this branch, not the one from the zip that I downloaded on the official website.

Is this master branch not ready for prod?

**Comment by osworx** [comment]
> 
> Is this master branch not ready for prod?

Correct.
Only for development and testing.

**Comment by RobineSavert** [comment]
Ah ok thanks so much, that clears up a lot of my issues. I already saw it will take some time to get this into prod? I will wait as this looks very promising!

**Comment by mhcwebdesign** [comment]
The master branch is for brave souls only :)
It's still in development. Actually, it's more broken now than ever before after Daniel put the latest Bootstrap V5 on there.

**Comment by IP-CAM** [comment]
@mhcwebdesign: better don't tell them, OC needs free Testers badly. :):)

**Comment by mhcwebdesign** [comment]
@IP-CAM: Actually, when you replace Bootstrap5 with Bootstrap4, it works pretty well. With bootstrap5 it will take some time to adjust the templates, CSS and other javascripts.
