### ISSUE TITLE
customs field in user address not showing in order details page in admin

### ISSUE THREAD

**Issue by tyler-x** [opencart/opencart#9645]
opencart version 3.0.3.6

1. Added a dropdown customs field in the admin under address location and make it mandatory for all users.
2. When placing order, was able to select from the list and submit the order.
3. In admin, order detail page, this field data was not showing in billing & shipping address sections.
4. When editing this order, under the billing information tab, this custom field is showing with correct data user selected, but was unable to continue to the next tab, always ask me to fill in this field even there is a value selected.
5. In the front end, user order details page, this field data was not showing in the billing & shipping address neither.

**Comment by TheCartpenter** [comment]
This issue has already been reported.

**Comment by prabhatkumaroc082** [comment]
check this commit https://github.com/opencart/opencart/commit/a2583163c7b5384e1b788f1d964f79c0791f8462
already fixed issues for custom-fields
or simply replace the file from https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance/
