### ISSUE TITLE
Countless errors in store update (on install page)

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#9647]
This is upgrade 3.0.3.2 to version 3.0.3.7

```
Error Code(0): Error: Invalid default value for 'date_added'
Error No: 1067
ALTER TABLE `category` ENGINE = `MyISAM` in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41
```
Fix: 1000.php, line 172:
 // $this->db->query("ALTER TABLE `" . $table['name'] . "` ENGINE = `" . $table['option']['ENGINE'] . "`");

Error Code(0): Error: Invalid default value for 'date_added'
Error No: 1067
ALTER TABLE `category` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_general_ci` in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41

Fix: 1000.php, line  177:
 // $this->db->query("ALTER TABLE `" . $table['name'] . "` DEFAULT CHARACTER SET `" . $table['option']['CHARSET'] . "` COLLATE `" . $table['option']['COLLATE'] . "`");

             /*	if (isset($table['option']['ENGINE'])) {
					 $this->db->query("ALTER TABLE `" . $table['name'] . "` ENGINE = `" . $table['option']['ENGINE'] . "`");
				}

				// Charset
				if (isset($table['option']['CHARSET']) && isset($table['option']['COLLATE'])) {
					$this->db->query("ALTER TABLE `" . $table['name'] . "` DEFAULT CHARACTER SET `" . $table['option']['CHARSET'] . "` COLLATE `" . $table['option']['COLLATE'] . "`");
				} */

```
Error Code(0): Error: Invalid default value for 'date_added'
Error No: 1067
ALTER TABLE `category` CHANGE `category_id` `category_id` INT(11) NOT NULL FIRST in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41
```

1000.php lines 189-195:

					/*	foreach ($table_old_data[$table['name']]['extended_field_data'] as $oldfield) {
							if ($oldfield['Extra'] == 'auto_increment' && $field['autoincrement']) {
								$sql = "ALTER TABLE `" . $table['name'] . "` CHANGE `" . $oldfield['Field'] . "` `" . $field['name'] . "` " . strtoupper($field['type']);
								$status = false;
								break;
							}
						} */

						line 338:

                    //	$this->db->query($sql);
						//	$this->db->query($sql);

						line 292:

						// $this->db->query("ALTER TABLE `" . $table['name'] . "` DROP PRIMARY KEY");

```
Error Code(0): Error: Multiple primary key defined
Error No: 1068
ALTER TABLE `address` ADD PRIMARY KEY(`address_id`) in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41
```

1000.php, line 293:
// $this->db->query("ALTER TABLE `" . $table['name'] . "` ADD PRIMARY KEY(" . implode(',', $primary_data) . ")");

```
Error Code(0): Error: Invalid default value for 'date_added'
Error No: 1067
ALTER TABLE `category` ADD INDEX `parent_id` (`parent_id`) in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41
```

1000.php, line 305

// $this->db->query("ALTER TABLE `" . $table['name'] . "` ADD INDEX `$name` (" . implode(',', $index_data) . ")");

```
Error Code(0): Error: Invalid default value for 'date_added'
Error No: 1067
ALTER TABLE `order_history` CHANGE `order_status_id` `order_status_id` int(11) NOT NULL in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41
```

1001.php, line 21:
//	$this->db->query("ALTER TABLE `" . DB_PREFIX . "order_history` CHANGE `order_status_id` `order_status_id` int(11) NOT NULL");

```
Error Code(0): Error: Invalid default value for 'date_added'
Error No: 1067
ALTER TABLE `category` DROP PRIMARY KEY, ADD PRIMARY KEY(`category_id`, `parent_id`) in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41
```

1002.php line 73:
// $this->db->query("ALTER TABLE `" . DB_PREFIX . "category` DROP PRIMARY KEY, ADD PRIMARY KEY(`category_id`, `parent_id`)");

```
Error Code(0): Error: Invalid default value for 'date_added'
Error No: 1067
ALTER TABLE `download` DROP `remaining` in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41
```
1004.php line 46-50:
        /*$query = $this->db->query("SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = '" . DB_DATABASE . "' AND TABLE_NAME = '" . DB_PREFIX . "download' AND COLUMN_NAME = 'remaining'");

		if ($query->num_rows) {
			 $this->db->query("ALTER TABLE `" . DB_PREFIX . "download` DROP `remaining`");
		} */

```
Error Code(0): Error: Invalid default value for 'date_added'
Error No: 1067
ALTER TABLE `customer` CHANGE `token` `token` text NOT NULL in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41
```
1005.php line 5:
// $this->db->query("ALTER TABLE `" . DB_PREFIX . "customer` CHANGE `token` `token` text NOT NULL");

```
Error Code(0): Error: Invalid default value for 'date_added'
Error No: 1067
ALTER TABLE `product` CHANGE `isbn` `isbn` VARCHAR(17) NOT NULL in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41
```

1005.php line 22:
// $this->db->query("ALTER TABLE `" . DB_PREFIX . "product` CHANGE `isbn` `isbn` VARCHAR(17) NOT NULL");

```
Error Code(0): Error: Invalid default value for 'date_added'
Error No: 1067
ALTER TABLE `download` CHANGE `filename` `filename` varchar(140) NOT NULL in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41
```

1007.php, line 5:
//	$this->db->query("ALTER TABLE `" . DB_PREFIX . "download` CHANGE `filename` `filename` varchar(140) NOT NULL");

```
Error Code(0): Error: Incorrect datetime value: '0000-00-00 00:00:00' for column 'date_added' at row 1
Error No: 1292
ALTER TABLE `event` ADD `date_added` DATETIME NOT NULL AFTER `status` in /home/int10507/public_html/* * * / * * */system/library/db/mysqli.php on line 41
```

1008.php lines 16-18
	/*	if (!$query->num_rows) {
			$this->db->query("ALTER TABLE `" . DB_PREFIX . "event` ADD `date_added` DATETIME NOT NULL AFTER 'status'");
		} */
		
		Tip: Manually add this 'date_added' field to the database in the 'event' table.

**Comment by prabhatkumaroc082** [comment]
Fixed for maintenance https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
any issue should not be faced on 3.0.3.8, please wait for the release.
