### ISSUE TITLE
Typo on checkout.twig break shipping_address functionality

### ISSUE THREAD

**Issue by manipogo** [opencart/opencart#9652]
Opencart 3.0.3.2 - 3.0.3.7 

File: catalog/view/theme/default/checkout.twig

Line 243:
var shipping_address = $('#payment-address input[name=\'shipping_address\']:checked').prop('value');

Should be:
var shipping_address = $('#collapse-payment-address input[name=\'shipping_address\']:checked').prop('value');

Otherwise shipping_address is always undefined regardless of whether you check the box.

**Comment by prabhatkumaroc082** [comment]
fix https://github.com/opencart/opencart/pull/9653/

**Comment by ADDCreative** [comment]
For reference this was reported in https://github.com/opencart/opencart/issues/7747, but the fix never made it to the 3.0.x.x_Maintenance.

**Comment by prabhatkumaroc082** [comment]
Found a bug, suggested code has been added.
