### ISSUE TITLE
Installation 3.0.3.7

### ISSUE THREAD

**Issue by danelsan** [opencart/opencart#9656]
**What version of OpenCart are you reporting this for?**
3.0.3.7

**Describe the bug**
When i try to install with brower give an error.

Warning: require(/var/www/html/vendor/opencart/opencart/upload/system/storage/vendor/composer/../react/promise/src/functions_include.php): failed to open stream: No such file or directory in /var/www/html/vendor/opencart/opencart/upload/system/storage/vendor/composer/autoload_real.php on line 69

Fatal error: require(): Failed opening required '/var/www/html/vendor/opencart/opencart/upload/system/storage/vendor/composer/../react/promise/src/functions_include.php' (include_path='.:/usr/local/lib/php') in /var/www/html/vendor/opencart/opencart/upload/system/storage/vendor/composer/autoload_real.php on line 69

**Comment by TheCartpenter** [comment]
Two opencart folders found in your include_path.

**Comment by WebkulOpencart** [comment]
Please follow this blog if you are installing the OpenCart from Github
[https://webkul.com/blog/how-to-install-opencart-in-3-0-6-0-version/](https://webkul.com/blog/how-to-install-opencart-in-3-0-6-0-version/)
