### ISSUE TITLE
Will oc4 fix $ total error?

### ISSUE THREAD

**Issue by seo-bro** [opencart/opencart#9661]
Hello!
In version oc3.X, a significant error was found in the price calculation formula.
As far as I understand, this problem will not be solved in the oc3 version. But will this problem be solved in the oc4 version?

**Comment by TheCartpenter** [comment]
More info is needed.

**Comment by seo-bro** [comment]
Now the formula for calculating the amount in the basket has the following structure:
$ total = (base price * quantity * currency) rounding, in this case, an error in the calculations when rounding is obtained, the correct solution is to first round off the price and then multiply by the quantity, that is, correctly: $ Total = (base price * currency) rounding * quantity.
And the same problem with taxes
The problem is that everything is written through the implementation of the class in the cart, and the total result is taken from the total amount in the cart: $ sub_total = $ this-> cart-> getSubTotal ();
And the shopping cart contains the logic price * quantity = total, which does not take into account either currency or tax and is an erroneous decision.
I understand that it is extremely difficult to fix this in the existing version, but maybe the right decision will be made in the new version.

**Comment by TheCartpenter** [comment]
It's not that it's extremely difficult to fix, it's rather about the right logic that needs to be used when the case.

**Comment by seo-bro** [comment]
I disagree. In calculating the amount and taxes, the logic should be correct and cannot be separate for each case, and should not differ from accounting programs, and of course this should not contradict the basic mathematical logic, that is, if a product costs $ 10, then 10 products should cost in the amount of $ 100, not $ 101, 102, 103 or 104, and using the existing logic in OC3, the total cost of goods with a price of $ 10 and a quantity of 10 pieces can be from 95 to 105.
The logic is very simple: If you come to a store and want to buy 20 candies worth $ 5 - what should be the amount?

**Comment by chulcha** [comment]
@seo-bro  не обращай на это чудо внимания, оно может только пробелы менять

**Comment by danielkerr** [comment]
maybe

$this->currency->convert($unit_price, $this->session->data['currency']) * $product['quantity'];

instead of 

$this->currency->format($unit_price * $product['quantity'], $this->session->data['currency']);
