### ISSUE TITLE
It is not entirely clear why there is such a limit !?

### ISSUE THREAD

**Issue by Stanislav93** [opencart/opencart#9674]
Good day. That's how the problem arose.
I created a module with the file name "newtik_currency_refresh_ukraine_bank" the number of characters 36 and the available number of characters 32. The file names should be easy to read and understand. It would be good if the module code (file name) could be set up to 128 characters (and this change does nothing global).
How does such a proposal?
It is not entirely clear why there is such a limit !?

**Comment by stalker780** [comment]
It's 64 chars in OC4.
But it also must contain extension code: 
`newtik_my_extension_code.newtik_currency_refresh_ukraine_bank`

I also agree, that even 64 chars may be not enough for some codes.

128 chars will not do any harm. 
This table usually does not contain thousands of rows and also there is no partial text search queries for it. It is used mostly for extension/module routes.

There is also a related issue with possible module codes duplicates in oc_setting table. https://github.com/opencart/opencart/pull/9655
Hope Daniel will pay attention to this before OC4 release.

**Comment by TheCartpenter** [comment]
varchar 96.

**Comment by osworx** [comment]
Daniel may accept proposals if they make sense, see for example this here:
https://github.com/opencart/opencart/issues/8941

**Comment by WebkulOpencart** [comment]
@Stanislav93 I already added the validation for the same for the version 3.x
[https://github.com/opencart/opencart/commit/38711c9c037668bdb9c6ca65484cbfb950d92d5b](https://github.com/opencart/opencart/commit/38711c9c037668bdb9c6ca65484cbfb950d92d5b)

**Comment by danielkerr** [comment]
its is set to 128
