### ISSUE TITLE
Image Upload not coming up

### ISSUE THREAD

**Issue by emperorerror** [opencart/opencart#9679]
**What version of OpenCart are you reporting this for?**
4.0.0.0_b

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

-Unable to upload pictures as the upload option after clicking edit image is not coming up

**To Reproduce**

- go to image upload in any area and this can be reproduced

**Expected behavior**

- upload buttons should show up

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system

- ubunto 20 digital ocean
- 
 - PHP version -                 8.0.5
 - Apache version -            ngnix
 - Browser(s) tested with [e.g. chrome, safari - if applicable]    - ( chrome) 

**Additional context**

**Comment by emperorerror** [comment]
also error logs: 
2021-05-23 19:16:45 - PHP Warning:  Undefined variable $products in /var/www/html/commerce/opencart/upload/extension/opencart/catalog/controller/module/featured.php on line 23

2021-05-23 19:16:45 - PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/html/commerce/opencart/upload/extension/opencart/catalog/controller/module/featured.php on line 23

**Comment by emperorerror** [comment]
can also have a look at :

index.php?route=catalog/product|form&user_token=98a35b65ee18497a504b316729491227&product_id=50:1677 Uncaught TypeError: $(...).tab is not a function
    at index.php?route=catalog/product|form&user_token=98a35b65ee18497a504b316729491227&product_id=50:1677

at line 1676 <script type="text/javascript"></script>

**Comment by wolix** [comment]
this file: /admin/view/javascript/common.js
line: 351/453, remove them

**Comment by danielkerr** [comment]
fixed a while ago

**Comment by emperorerror** [comment]
Thanks a lot!
