### ISSUE TITLE
About 4.x

### ISSUE THREAD

**Issue by miotoloji** [opencart/opencart#9684]
Hi, I'm developing opencart modules and creating web sites with opencart for my customers. 

I wan't to help you for developing opencart...

May I join 4.x test team ?

**Comment by chongshengdz** [comment]
> Hi, I'm developing opencart modules and creating web sites with opencart for my customers.
> 
> I wan't to help you for developing opencart...
> 
> May I join 4.x test team ?

yes, you can send a pull request when you find a bug
