### ISSUE TITLE
File could not be uploaded!

### ISSUE THREAD

**Issue by Noor-Techshetra** [opencart/opencart#9687]
**What version of OpenCart are you reporting this for?**
3.0.3.7

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
I have to install Extension plugin Install when hit upload Icon its getting alert "File could not be uploaded! "

**To Reproduce**
1. Go to "Extension  Installer"
2. Click on  "Upload"
3. Scroll down to "Console"
4. See error  "Bootstrap doesn't allow more than one instance per element. Bound instance: bs.tooltip"

**Expected behavior**
File upload select Opener  window

**Screenshots / Screen recordings** 
https://www.loom.com/share/d291844053a541abbd88b9db1d402211

**Server / Test environment (please complete the following information):**
 -  Deployed to a web server?  YES
 - Operating system :  Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1043-gcp x86_6)
 - PHP version -  PHP 8.0.5 (cli) (built: May  3 2021 11:30:57) ( NTS )
 - Nginx version :  nginx/1.18.0 (Ubuntu)
 - Browser(s) tested with [e.g. chrome, safari - if applicable] - FireFox , Chrome
 - Version [e.g. 22]  FireFox 88.0.1 (64-bit) , Chrome Version 90.0.4430.212

**Additional context**
how to resolve this issue?

![image](https://user-images.githubusercontent.com/20987295/120164975-bcf35780-c218-11eb-9c1d-87e4f682916f.png)
On click upload Icon getting alert 
![image](https://user-images.githubusercontent.com/20987295/120165779-8b2ec080-c219-11eb-9aca-b8fa98dd7659.png)

**Comment by mhcwebdesign** [comment]
The same error "Bootstrap doesn't allow more than one instance per element. Bound instance: bs.tooltip" also comes up when saving category, product or information data. Must be something to do with the way tooltips are handled in bootstrap5.

**Comment by cgcmart** [comment]
master-branch:
Backup & Restore Home Backup & Restore ->

!error_upload

**Comment by WebkulOpencart** [comment]
[https://github.com/opencart/opencart/issues/9679](https://github.com/opencart/opencart/issues/9679)

**Comment by wolix** [comment]
this file: admin/view/template/marketplace/installer.twig
line: 49,51
point: 49: '#upload-form', 51:  "form-upload", modify one of them
