### ISSUE TITLE
Not Bug but a feature requested

### ISSUE THREAD

**Issue by num47** [opencart/opencart#9689]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
As the title- I am not reporting a bug rather requesting a new feature. Right now, i am using another e-commerce system but would love to change to Opencart. But, the only thing that is holding me back is this custom payment system feature. This is necessary where buyer will pay offline and will just submit a payment confirmation ID number of token number on my website while making the order.

**To Reproduce**
1. A module can be made to adjust this. 
2. Custom message including payment details should be editable in the module. 
3. An customer input system should be there.

**Expected behavior**
Customer would get a direction on how much and how he should pay the amount to the account number and which information should be filled before submitting the order.

**Screenshots / Screen recordings**

**Server / Test environment (please complete the following information):**
 
**Additional context**

**Comment by mhcwebdesign** [comment]
This is already available with the standard OpenCart payment method 'Bank Transfer'.
If you need some modifications done to it, please post a request on the commercial support section of the OpenCart forum.

**Comment by num47** [comment]
In "Bank Transfer" module does not have any input section for the customer to input any information after they make the payment. And, In Bank Transfer module you can add only one of your bank account details. You can not do it if you want to add several bank account details.
