### ISSUE TITLE
[OC4 Master Branch] CKEditor updateElement never invoked during save

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#9690]
**What version of OpenCart are you reporting this for?**
Master Branch OC4

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
When saving an updated textarea data, edited via the CKEditor on the product, category, or information edit pages, the textarea element won't be updated by the CKEditor's adapter in **view/javascript/ckeditor/adapters/jquery.js** where it should have invoked the triggered updateElement function.  As a result, no product/category/information description gets updated!

This is probably caused by the usage of Ajax calls instead of using normal form submissions.

I know this is still all work in progress, I am just mentioning it so it won't be overlooked.

**Server / Test environment (please complete the following information):**
    Apache/2.4.41 (Ubuntu)
    MySQL Server version: 8.0.25-0ubuntu0.20.04.1 - (Ubuntu)
    PHP version: 8.0.5

**Comment by mhcwebdesign** [comment]
A quick solution would be a simple change in common.js, as follows, for form submissions:

```
// Forms
$(document).on('click', '[data-oc-action]', function() {
    var element = this;

    var form = $(element).attr('data-oc-form');

    for (var i in CKEDITOR.instances) {
		CKEDITOR.instances[i].updateElement();
    }

    $.ajax({
        // .... do the ajax call for submitting the form, including textareas updated by ckeditor ....
    });
});
```

**Comment by cgcmart** [comment]
@mhcwebdesign 

The change does not work.
"Success: You have modified information!" after submission,
But the content of db table was not updated, it's still go back to the old when re-check it with CKeditor.

**Comment by mhcwebdesign** [comment]
@cgcmart: Sorry, but merely saying that it doesn't work won't help here. You should provide more details about your system and what exactly you did so others can replicate the steps. It works just fine on my system.

**Comment by cgcmart** [comment]
Operating system Debian Linux 10
PHP version 8.0.7
Apache version Apache 2.4.38
MariaDB 10.3.27

**Comment by mhcwebdesign** [comment]
Add this then to the common.js:

```
    for (instance in CKEDITOR.instances) {
        CKEDITOR.instances[instance].updateElement();
		console.log("updateElement called for '"+CKEDITOR.instances[instance]+"'");
    }

```

And then use the web browser code inspector and view the console, to see whether the updateElement is even called upon your form submission.

**Comment by cgcmart** [comment]
@mhcwebdesign 

Uncaught ReferenceError: CKEDITOR is not defined
    at HTMLButtonElement.<anonymous> (common.js:145)
    at HTMLDocument.dispatch (jquery-3.6.0.min.js:2)
    at HTMLDocument.v.handle (jquery-3.6.0.min.js:2)

`for (var i in CKEDITOR.instances) {`

**Comment by mhcwebdesign** [comment]
@cgcmart : Welcome to the Javascript / jquery jungle! :)

It looks like somehow on your system the CKEditor isn't even  loaded or instantiated.
What exactly did you do? For what form? Using what web browser? What version of CKEditor did you use?

**Comment by cgcmart** [comment]
The above error is from Google Chrome Developer Tools, that is fixed at #9724

**Comment by mhcwebdesign** [comment]
My solution works fine in Firefox, but not in Chrome. 

The **$(document).on('click', '[data-oc-action]', function() {** should not be executed before the CKeditor is loaded. Therefore it looks to me more like a  bug in Chrome .

**Comment by stalker780** [comment]
@mhcwebdesign 
Try this code in common.js. Or even better in ckeditor/config.js
Should work in any browser. Saves all ckeditor instances on change.

```
$(document).ready(function() {
  if (typeof CKEDITOR != 'undefined') {
    for (instance in CKEDITOR.instances) {
      CKEDITOR.instances[instance].on('change', function(e) {
        for (var idx in CKEDITOR.instances) { CKEDITOR.instances[idx].updateElement(); }
      });
    }
  }
});
```

**Comment by mhcwebdesign** [comment]
Ideally we only want to change the CKEDITOR instances upon a click on the 'Save' button.

**Comment by cgcmart** [comment]
reference ckeditor define firstly needed either for @mhcwebdesign change or @stalker780 change.
including ckeditor.js script in header.twig is the best place.

**Comment by mhcwebdesign** [comment]
@cgcmart: OK, changing the **common/header.twig** to include the **common.js** as the last script, along with my suggested change to the **common.js** itself, seems to be the way forward:

```
	.....
	<link href="{{ bootstrap_css }}" rel="stylesheet" media="screen"/>
	<link href="{{ icons }}" rel="stylesheet" type="text/css"/>
	<script src="{{ jquery }}" type="text/javascript"></script>
	<link href="{{ stylesheet }}" rel="stylesheet" type="text/css"/>
	<link href="view/javascript/jquery/datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet" type="text/css"/>
	<script type="text/javascript" src="view/javascript/jquery/datetimepicker/moment/moment.min.js"></script>
	<script type="text/javascript" src="view/javascript/jquery/datetimepicker/moment/moment-with-locales.min.js"></script>
	<script type="text/javascript" src="view/javascript/jquery/datetimepicker/bootstrap-datetimepicker.js"></script>
	{% for style in styles %}
		<link type="text/css" href="{{ style.href }}" rel="{{ style.rel }}" media="{{ style.media }}"/>
	{% endfor %}
	{% for link in links %}
		<link href="{{ link.href }}" rel="{{ link.rel }}"/>
	{% endfor %}
	{% for script in scripts %}
		<script type="text/javascript" src="{{ script }}"></script>
	{% endfor %}
	<script type="text/javascript" src="view/javascript/common.js"></script>
</head>

```

Can you confirm that it will work on your server?

**Comment by cgcmart** [comment]
It should work as I already added at my fix:
`<script src="catalog/view/javascript/common.js" type="text/javascript"></script>`

But code `<script type="text/javascript" src="view/javascript/common.js"></script>` got 
 404 Not Found common.js:1 logged by google chrome.
This is the strange error involved in a relative path.

**Comment by cgcmart** [comment]
@danielkerr 
[https://github.com//issues/9690](https://github.com//issues/9690)

Need upgrade ckeditor to CKEditor 5, that uses Bootstrap components to build the user interface.
Otherwise, common.js and forms referring to bs 5 won't work!

**Comment by danielkerr** [comment]
i fixed a while ago
