### ISSUE TITLE
TypeError: Unsupported operand types: string * int

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9691]
**What version of OpenCart are you reporting this for?**

Master branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Almost can't go anywhere because of error message

TypeError:  Unsupported operand types: string * int
File: .../admin/controller/report/online.php
Line: 76

TypeError:  Opencart\Catalog\Model\Tool\Image::resize(): Argument #2 ($width) must be of type int, string given in .../catalog/model/tool/image.php on line 4

Undefined array key "customer_token" in .../catalog/controller/account/address.php on line 138

TypeError:  Unsupported operand types: string * int
File: .../admin/controller/user/user_permission.php
Line: 96

TypeError:  Unsupported operand types: string * int
File: .../admin/controller/catalog/product.php
Line: 163

TypeError:  Unsupported operand types: string * int
File: .../admin/controller/customer/customer.php
Line: 189

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system Debian 10
 - PHP version 8.0.5
 - Apache version Apache 2.4.38
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by danielkerr** [comment]
i think all this stuff is already fixed.
