### ISSUE TITLE
TypeError:  Unsupported operand types: string * int

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9693]
https://github.com/opencart/opencart/blob/e34cf261bbc4da5dc5b808c1010dab74b1df6215/upload/admin/controller/sale/order.php#L252

L381: Multiple TypeErrors and DivisionByZeroError

See the issue #9691, and pull request #9692 and my comment.

**Comment by danielkerr** [comment]
will be going through issues and finishing the next version tomrrow.
