### ISSUE TITLE
PHP Warning:  Undefined array key "customer_token" in

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9696]
https://github.com/opencart/opencart/blob/e34cf261bbc4da5dc5b808c1010dab74b1df6215/upload/catalog/controller/account/address.php#L138

Is this error from spambot form spam or bug?

[https://bretdonnelly.com/index.php?route=account/address%7Cform&language=en-gb](https://bretdonnelly.com/index.php?route=account/address%7Cform&language=en-gb)

**Comment by mhcwebdesign** [comment]
Neither a bug, nor a spambot. Daniel is till in the middle of switching over to the latest bootstrap and json, all work in progress.
