### ISSUE TITLE
Console error when click on rebuild button on category page

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#9699]
**What version of OpenCart are you reporting this for?**
Master Branch
**Describe the bug**
Go to the Category page on the admin end and click on the rebuild button and check the console
[http://i.prntscr.com/Qot0lfR2Qfe32a1lADxgdQ.png](http://i.prntscr.com/Qot0lfR2Qfe32a1lADxgdQ.png)

**Comment by WebkulOpencart** [comment]
This issue on al pages on admin where Ajax call on button click

**Comment by mhcwebdesign** [comment]
Confirmed.

Just bear in mind that it is still work in progress, the switchover to bootstrap5 hasn't yet been completed by Daniel.

**Comment by cgcmart** [comment]
The issue does no exist on my gcp server system:
Debian Linux 10
Php 8.0.7
Apache 2.4.38
MariaDB 10.3.27

**Comment by WebkulOpencart** [comment]
Also, the confirm alert box is not showing on the delete button

**Comment by WebkulOpencart** [comment]
[https://github.com/opencart/opencart/issues/9687](https://github.com/opencart/opencart/issues/9687)

**Comment by danielkerr** [comment]
its working fine on master branch and https://github.com/opencart/opencart/issues/9687 has got nothing to do with this
