### ISSUE TITLE
Too many sql Query Opencart

### ISSUE THREAD

**Issue by anisurrahmansamim** [opencart/opencart#9705]
Hello,
I have some problem with my website. when I will go to admin panel or upload a product then, my server take too many sql Query Like this "Sending data SELECT DISTINCT *, pd.name AS name, p.image, m.name AS manufacturer, (SELECT price FROM oc_product_d"

![Screenshot_6](https://user-images.githubusercontent.com/55828107/121675288-083d1e00-cad5-11eb-9e8e-799cd693e093.png)

this way, my website is down.
You can tell me what's solution? Please

Opencart Version 3.0.3.3,
Server: VPS, 6 core, 16 GB RAM

info me please!
thanks!

**Comment by konstantinosbotonakis** [comment]
This seems to be a SELECT query that is called on product view in catalog and not admin. Most likely your site has many hits in a category view or/and filter(s) in category view.

**Comment by anisurrahmansamim** [comment]
> This seems to be a SELECT query that is called on product view in catalog and not admin. Most likely your site has many hits in a category view or/and filter(s) in category view.

Thanks for reply! website is ok query is just 1 or 2. but when i will go admin panel or upload , update a product . then take so many sql query... sorry for my poor English .

**Comment by konstantinosbotonakis** [comment]
Disable all modifications and try again to see the sql queries. 

If the queries still exist copy the whole query and find which model is calling it. If it's the default Opencart model(s) your db needs some indexing and optimization. 

If the multiple queries stop, one of your installed modifications creates the problem and you need to find it manually by enabling one by one. 
When you find it, contact the mod's developer.

**Comment by mhcwebdesign** [comment]
Please repost on the OpenCart forum to find a solution. This is not an OpenCart bug. Your MySQL server needs some reconfiguration.
