### ISSUE TITLE
Fix: Uncaught TypeError: $(...).tooltip is not a function # 9707

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9709]
https://github.com/opencart/opencart/blob/e22ddfb060752cd8134abbfb104202172ab45c86/upload/catalog/view/template/common/header.twig#L15 after

add the following lines of scripts and link to fix  #9707 
`<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>`

`<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.10.25/datatables.min.css"/>`

`<script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.10.25/datatables.min.js"></script>`

**Comment by Khnaz35** [comment]
Will this solution work for OC 2.3.0.2 as well? I am getting this error on 2.3.0.2
`common.js:130 Uncaught TypeError: $(...).tooltip is not a function
    at HTMLDocument.<anonymous> (common.js:130:33)
    at j (jquery-2.1.1.min.js:2:26860)
    at Object.add [as done] (jquery-2.1.1.min.js:2:27169)
    at n.fn.init.n.fn.ready (jquery-2.1.1.min.js:2:29275)
    at common.js:25:13`

**Comment by cgcmart** [comment]
your case is jquery-2.1.1
try:
```
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/ju/dt-1.11.4/datatables.min.css"/>
 
<script type="text/javascript" src="https://cdn.datatables.net/v/ju/dt-1.11.4/datatables.min.js"></script>
```

**Comment by Khnaz35** [comment]
I have Journal3 theme and i tried placing this in header.twig but doesn't work for me

**Comment by mhcwebdesign** [comment]
> I have Journal3 theme and i tried placing this in header.twig but doesn't work for me

This is for OpenCart. For the Journal3 framework you have to contact https://support.journal-theme.com/

**Comment by Khnaz35** [comment]
No worries, Got it figure out.
