### ISSUE TITLE
Product views report 

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#9713]
All versions 

https://github.com/opencart/opencart/blob/e22ddfb060752cd8134abbfb104202172ab45c86/upload/extension/opencart/admin/model/report/product.php#L25

https://github.com/opencart/opencart/blob/e22ddfb060752cd8134abbfb104202172ab45c86/upload/extension/opencart/admin/model/report/product.php#L31

Need add 
```
LEFT JOIN " . DB_PREFIX . "product_description pd ON (p.product_id = pd.product_id) 
		WHERE pd.language_id = '" . (int)$this->config->get('config_language_id') . "'
```
		
Also, I would like to have sorting and filtering
But this can be left for developers too.

**Comment by TheCartpenter** [comment]
Using SUM is not the same as COUNT and viewed higher than 0 will not provide the same result as SUM ... as for the language ID, however, that'd be correct.

**Comment by chulcha** [comment]
> 
> 
> Using SUM is not the same as COUNT and viewed higher than 0 will not provide the same result as SUM ... as for the language ID, however, that'd be correct.

Get your a..s..s.. if you don't understand what this is about

**Comment by danielkerr** [comment]
code has changed also not a clue what u are actually doing with these changes
