### ISSUE TITLE
A New Model for Cookie Security and Transparency

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9715]
https://github.com/opencart/opencart/blob/e22ddfb060752cd8134abbfb104202172ab45c86/upload/catalog/controller/common/cookie.php#L40

Developers must use a new cookie setting, SameSite=None, to designate cookies for cross-site access.

L39 Cookie not working, #9132, #9190

**Comment by ADDCreative** [comment]
SameSite needs to be a setting. Something like.
 ```php
'secure' => $config->get('session_secure'),
'samesite' => $config->get('session_samesite')
```
Or maybe use ini_get and [session.cookie_samesite](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-samesite) and [session.cookie_secure](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-secure).

**Comment by danielkerr** [comment]
@cgcmart  which ones are you talking about because they should not need cross-site access as its insecure to set say a login cookie.
