### ISSUE TITLE
Filtering on extension section doesn't load

### ISSUE THREAD

**Issue by ctseo** [opencart/opencart#9721]
**What version of OpenCart are you reporting this for?**
Opencart 3.0.3.1  but is on all versions: Opencart 1.56.4, Opencart 2.3.0.2

The issue can be see it on oficial demo opencart: https://demo.opencart.com/admin/index.php?route=marketplace/extension

**Describe the bug**
Go to Extensions -> Extensions and choose Modules or any option from this section... can you see it? From my side isn't working...

Printscreen: https://prnt.sc/15sjqok

Does anyone know this bug/issue? Is there a solution to get the list of modules? I need to edit my menu .. and i doesn't know the link to edit my menu. :(

**Comment by ADDCreative** [comment]
Works for me. Look in your web browser's developer console and post on https://forum.opencart.com/.

**Comment by mhcwebdesign** [comment]
It looks like nobody else can reproduce your issue. As ADDCreative said please repost on the OpenCart forum to finda professional developer to look into it.
