### ISSUE TITLE
2.3.0.2 Reward Points for Optioned Product

### ISSUE THREAD

**Issue by zaaf3004** [opencart/opencart#9723]
2.3.0.2 does not offer to pay with reward points for a product with options. Works fine with the products without the option. Could anyone help here ? 
Example; 
I got 1 product priced at $0 , It has multiple prices for different options, every option has different reward points. Customer ticks from these options and proceeds to cart. But Customer cant pay with his reward points. The cart only offers a regular checkout. Customer cant use the reward points.

Customer can pay regular product without an option, without any problem. 

System was tested with regular product and all are working properly. But not for the product with option. 

Could you help me here ? 

Thanx, 
Mr. A

**Comment by TheCartpenter** [comment]
OC Forum request.
