### ISSUE TITLE
Fix: CKEditor updateElement never invoked during save #9690

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9724]
add:

`<script type="text/javascript" src="view/javascript/ckeditor/ckeditor.js"></script>`

before:
https://github.com/opencart/opencart/blob/9dc869f371c5c64ce2edca42185f253c0f19135a/upload/admin/view/template/common/header.twig#L29

fix #9690

**Comment by mhcwebdesign** [comment]
How exactly, and where, did you change it, to make sure the 'ckeditor.js' is included before 'common.js' ?

**Comment by cgcmart** [comment]
upload/admin/view/template/common/header.twig
before L29

**Comment by mhcwebdesign** [comment]
> upload/admin/view/template/common/header.twig
> before L29

Doesn't make sense. Line 29 belongs to the header.twig, hence you can't upload the header.twig before line 29 in its own file.

**Comment by cgcmart** [comment]
include ckeditor.js before common.js in header.twig.
CKEditor updateElement never invoked because of ckeditor.js did not load anywhere.

**Comment by mhcwebdesign** [comment]
> include ckeditor.js before common.js in header.twig.
> CKEditor updateElement never invoked because of ckeditor.js did not load anywhere.

The include order shouldn't matter, because the **$(document).on('click', '[data-oc-action]', function() {** isn't called till way after both files (common.js and ckeditor.js) were includes.

Have you tried my proposed solution in Chrome with caching turned off (see F12 > Network > Disable cache)?
