### ISSUE TITLE
Fix BS v5 console.error - Bootstrap doesn't allow more than one instance per element. 

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9725]
**What version of OpenCart are you reporting this for?**
Master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Bootstrap doesn't allow more than one instance per element. Bound instance: bs.tooltip.
That is thrown out by data.js L28 (`console.error`), and common.js line (`console.error`).

Bootstrap Docs Elaborating:

Data attributes

> Only one plugin per element via data attributes
Don't use data attributes from multiple plugins on the same element. For example, a button cannot both have a tooltip and toggle a modal. To accomplish this, use a wrapping element.

Fix:
Find  code on upload/admin/view/javascript/common.js:
`[data-bs-toggle=\'tooltip\']`

Replace with
`[data-toggle=\'tooltip\']`

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by mhcwebdesign** [comment]
The issue is caused by $.ajax **beforeSend** or $.ajax **complete** in the commons.js:

```
$(document).on('click', '[data-oc-action]', function() {
    var element = this;

    var form = $(element).attr('data-oc-form');

    $.ajax({
        url: $(element).attr('data-oc-action'),
        type: 'post',
        dataType: 'json',
        data: new FormData($(form)[0]),
        cache: false,
        contentType: false,
        processData: false,
        beforeSend: function() {
            $(element).button('loading');
        },
        complete: function() {
            $(element).button('reset');
        },
        ......

```

If you comment them out, it works fine.

**Comment by cgcmart** [comment]
The error points out

> Bound instance: bs.tooltip.
