### ISSUE TITLE
Share a suck module experience 

### ISSUE THREAD

**Issue by evaland999** [opencart/opencart#9727]
https://webkul.com/
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31686&filter_member=webkul&page=2
it's very senior script developer in opencart.com since 2012
and me,
As a user of opencart,I have already used OC almost 10 years from OC2.0.2.
I never bought any modules or extensions from webkul
Honestly their modules is very expensive.
So when I found other script developer is much cheaper than webkul.com,I bought others not webkul.com's
Such as isenslab,I bought many modules from them.
Price more cheap and module easy installed and used.

Recently I built a whole new OC 3.0.3.7.
As everybody known,A Good Opencart shopping website need a good cache module.
I think don't need to explain why.

Although OC have it's built cache system,But it is very simple and not well performance.

So I must looking for a good cache system to use on my New OC 3.0.3.7.

At first,I hope to choice isenlab's Nitro cache module,But it's Not updated anymore.

So I found webkul.com's Cache system module.
I searched and learning on it's demo page many days,Then I decided to buy and use it on my website.

But it's Nightmare started.

First:
From webkul.com I Downloaded original file after bought,But it's a bug version.
After installed to my test website,I got blank page in front end page.
At first I thought it's my OC's problem,Maybe some modules  Conflict with each other.
So I installed a Fresh OC to make sure,And confirm it's a bug version.

So of course I ask webkul.com's support team to help,They checked and checked them reported me the original file have bug in it.

It already wasted me more than 30 hours.
I already expressed my strong dissatisfaction at that time

And then Webkul  installed thie cache module to my site ,But still can't run.
They checked and checked,Then found more bugs in this cache module.
And They fixed and fixed again and again.

after waiting more than 60 hours,I thought finally this cache system module can work well.

But I was wrong,This time,webkul's support said "I can't install extra modules"

Then They gave me a conclusion.
I can't install these extra modules,if I insist,Cache system can't have full function to run.

I can't believe to Hear this.

I believe every OC's user very clear to have extra modules to install and used in OC will make OC better.
Because Fresh OC have very few functions built in it.
So after installed a fresh OC ,We must have to buy necessary modules to use.
I can't see any strange point in it.

After first, Webkul's support team also thought it's just the conflict between Cache module with my other modules,
It should fixable 

But today Webkul.com 's support told me,
IF I want their cache can full work,I can't use my installed modules.
PS:I must pointed out,in my product and category page,I have only install 3-5 extra modules.
and these module don't modify any core codes,All bought from opencart's market

I felt very disappointed and ask webkul refund me if they really can't fix the issue ,Just refund me.
PS: I thought they "are don't"  "not can't"  .

And then Webkul 
  Just repeat it over and over again

Their cache run well in their "Demo Page"
So ask refund is uncaccepable

I have no choice only sent the Argue file to PayPal.

My conclusion is
Webkul.com is a big Website solution company,
And Webkul helped opencart to published OC3.0.3.7
It made The owner of Opencart.com Mr.Daniel recommend people.
https://www.youtube.com/watch?v=a7prc2SGyRY

This is the only reason that I decide buy their expensive module.
Because I believe webkul.com's module must be very good,And must have a professional support to support me after bought.

But truth is I bought a bug's module and got a suck support.

I wrote down my story to share everyone to see.

I don't know if Can I get a refund and must wait how long until paypal  Judge me right.

Hope no one will get the same nightmare.

Choice a  responsible script developer is most important .
Take care of your own money ,Without opencart support's support,
If you bought from developer's offical website and got such a suck things like me,
You can only depend PayPal's support,And it will a very long fight,you may lose this fight.

**Comment by evaland999** [comment]
I must Declare one thing
I really need a good cache module to help my OC better.
So after I ask refund from webkul.com because of their cache module ask me can only use with fresh OC.

I started looking for a new cache module,Then I found one.https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=8068
Conclusion:
I so hated myself not found this module first before I bought from webkul.com,
Because this new module ,  There is almost no compatibility problem with other modules
And it give every user a   7 days free use with full functionality.

Of course ,I downloaded and installed to my test website.
Everything is work well.
No any conflict thing happened,I mean I don't need disable any my modules and don't need ask the script developer to "fix" or "disable" any related fucntion to make sure everything can be ok.

this lighting cache module install very smooth and don't need any debug to be worked on my site.

I am very sad not found this module first.

**Comment by mhcwebdesign** [comment]
Sorry to learn you had a poor experience with an OC extension author.

While it is interesting to share your experience you had with others, github is not the right place for it do. If you haven't done so yet, please post it on the OpenCart forum. Github is for the core OpenCart development and bug reports only.
