### ISSUE TITLE
Fresh OpenCart 3.0.3.7 install, not https, in admin I get alert "error undefined" when I try to upload a plugin

### ISSUE THREAD

**Issue by mevsme** [opencart/opencart#9728]
![image](https://user-images.githubusercontent.com/1394030/122784582-426ba400-d2bb-11eb-8f77-f8741faf8c05.png)

How to fix this?

**Comment by mhcwebdesign** [comment]
Unable to reproduce, please re-post on the OpenCart forum to find some help or a professional devloper to look into it.

**Comment by mevsme** [comment]
I am a professional developer. I looks like developers of OpenCart are not.
