### ISSUE TITLE
Session expires too quickly while using file session adapter

### ISSUE THREAD

**Issue by utkuokutan** [opencart/opencart#9730]
I've realized session expires too quickly when using file session adapter.
https://github.com/opencart/opencart/blob/master/upload/system/library/session/file.php
at line 62:
$expire = time() - $this->config->get('session_expire');
should be:
$expire = time() + $this->config->get('session_expire');

**Comment by ADDCreative** [comment]
It this line that is wrong.
https://github.com/opencart/opencart/blob/4cfcccf58b2b83f0f8554fa184580c8a904f3faf/upload/system/library/session/file.php#L67

**Comment by utkuokutan** [comment]
> It this line that is wrong.
> https://github.com/opencart/opencart/blob/4cfcccf58b2b83f0f8554fa184580c8a904f3faf/upload/system/library/session/file.php#L67

I think you are right!

**Comment by cgcmart** [comment]
> 
> 
> It this line that is wrong.
> 
> https://github.com/opencart/opencart/blob/4cfcccf58b2b83f0f8554fa184580c8a904f3faf/upload/system/library/session/file.php#L67

`if (is_file($file) && filemtime($file) >= $expire) { `

**Comment by utkuokutan** [comment]
I believe it should be
if (is_file($file) && filemtime($file) **<** $expire) {

**Comment by curvedb** [comment]
I think this fix doesn't work. I have set session_expire to 60 (seconds) and the session never expires even I refresh 10 mins later after login.

**Comment by ADDCreative** [comment]
Try changing.
```php
if (is_file($file) && filemtime($file) > $expire) {
```
To.
```php
if (is_file($file) && filemtime($file) < $expire) {
```

**Comment by curvedb** [comment]
@ADDCreative thank you for your reply. I've tried your fix but session expires after login

**Comment by ADDCreative** [comment]
@curvedb Is $expire being set like below?

```php
$expire = time() - $this->config->get('session_expire');
```

**Comment by curvedb** [comment]
@ADDCreative yes it's exactly the same but session never expires

**Comment by ADDCreative** [comment]
@curvedb It shouldn't. You have probably not removed the wrong changes and applied the correct one.

**Comment by curvedb** [comment]
Here is my code
`
$_['session_expire']       = 30;
$_['session_probability']  = 1;
$_['session_divisor']      = 5;
public function __destruct()
{
	if (round(rand(1, $this->config->get('session_divisor') / $this->config->get('session_probability'))) == 1) {
		$expire = time() - $this->config->get('session_expire');

		$files = glob(DIR_STORAGE . 'session/sess_*');

		foreach ($files as $file) {
			if (is_file($file) && filemtime($file) < $expire) {
				unlink($file);
			}
		}
	}
}`

**Comment by ADDCreative** [comment]
Looks OK, But 30 seconds in not very long.

**Comment by curvedb** [comment]
Yes it's not long but don't you think session should expire 30 seconds later after I login ?

**Comment by ADDCreative** [comment]
Are you saying with that code the session doesn't expire or expires in less than 30 seconds?

**Comment by curvedb** [comment]
it doesn't expire after 30 seconds

**Comment by ADDCreative** [comment]
How are you testing? A few thing to consider. As you have moved the garbage collection to the destruct the write before will keep the session active. Your garbage collection only runs 1 in 5, So to test you will need to do 5 request with a different session.

**Comment by curvedb** [comment]
After I login to customer account I refresh the account page repeatedly for 1 min at least but I doesn't log me out even the timeout is set to 10 seconds.
