### ISSUE TITLE
[OC4 Masterbranch] Various BS5 issues

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#9735]
**What version of OpenCart are you reporting this for?**
Masterbranch

**Describe the bug**
Misaligned admin login form fields
Visually confusing and non-functioning buttons

**To Reproduce**
Admin backend login form

Admin backend Information page > tab Data > Bottom: Yes/No

**Screenshots / Screen recordings**
See attached screenshots.
![Screenshot_2021-06-27_17-25-42](https://user-images.githubusercontent.com/2989557/123552769-8d7c3000-d76f-11eb-9fe2-867ef735d38f.png)
![Screenshot_2021-06-27_17-31-11](https://user-images.githubusercontent.com/2989557/123552778-98cf5b80-d76f-11eb-894e-537628dcb4d0.png)

**Server / Test environment**
- Apache/2.4.41 (Ubuntu)
- PHP version 8.0.7
- MySQL Server version: 8.0.25-0ubuntu0.20.04.1 - (Ubuntu)

**Comment by mhcwebdesign** [comment]
The presentation of radio buttons really needs to be visually improved. E.g. are below values set to this:

Newsletter: Yes
Status: No
Safe: Yes

or are they:

Newsletter: No
Status: Yes
Safe: No

![Screenshot_2021-09-12_17-42-56](https://user-images.githubusercontent.com/2989557/132995950-ce528314-719b-4af9-8fda-c33e1f9f68d3.png)

**Comment by mhcwebdesign** [comment]
Also, the alert divs are in the wrong place:
![Screenshot_2021-09-12_17-56-26](https://user-images.githubusercontent.com/2989557/132996311-0cf9b31c-1238-41b3-9315-478dd258f9bc.png)

**Comment by danielkerr** [comment]
ok ill put the alert divs back. just a lot of qwork on every page. also hard to see if not alredy scrolled to the top

**Comment by cgcmart** [comment]
It's better to let alert automatically close itself a few of seconds. Currently have to close the alert manually in order to go.
