### ISSUE TITLE
<script> element with empty src attribute

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9737]
https://github.com/opencart/opencart/blob/4cfcccf58b2b83f0f8554fa184580c8a904f3faf/upload/catalog/view/template/common/footer.twig#L56

Remove L56 - L59 script tags in footer.twig file to fix browser warnings `script tag with an empty src attribute` 

because the script tags are the same as already presents in header.twig.

**Comment by danielkerr** [comment]
its not empty anymore
