### ISSUE TITLE
Opencart should add a required field for the "IOSS number" for European Customers immediately

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#9743]
Opencart should add a required field for the "IOSS number" for European Customers immediately, it has become a must when you send to the European countries since 1st, July, 2021.

**Comment by osworx** [comment]
Simply can be achieved with a "custom field".
When OC starts with fields like that, OC would have 100 more in a year - imagine how many IDs you will have with hundreds of regulations, ~ 240 countries, thousands of regulations ..

**Comment by chongshengdz** [comment]
> Simply can be achieved with a "custom field".
> When OC starts with fields like that, OC would have 100 more in a year - imagine how many IDs you will have with hundreds of regulations, ~ 240 countries, thousands of regulations ..
> 
> Beside this: what for you want to use the IOSS number?
> It's only an "internal" ID for doing your daily business (registered and paying the taxes especially chinese companies never did in the past!).


It seems i am wrong, the IOSS should be provided by seller(this was requested by European Union,when you send something to a European country, you must provide this number, no matter where you are from.) so this issue should be closed.
In our daily life, we do not need to pay taxes for buying anything for personal use, unless companies buy something from companies, or a person buys something from a company(most of the time, there is no need).

**Comment by osworx** [comment]
@chongshengdz Well, here in the EC you can operate a "business" only if you are officially registered AND if you are a company.
A person can not operate any business - therefore is also not allowed to operate a webshop.
Seems in China everyone can do what he wants .. ?

So, started with the 1. July 2021 every company selling goods to Europe (the EC), has to pay taxes from the first cent (before less than 20 Euro nothing).
And not registering at each financial authority (currently 27), that is the IOSS for: you register once and pay all different taxes to one only (they will split again the sum to all countries and forward the taxes to them).
Registering the IOSS is optional, not mandatory.

p..s: and if a company buys something from another company, they pay NO taxes if both are from Europe AND the seller is from another European country than the buyer AND both have a valid UID.
Therefore to try to avoid to pay taxes is nearly impossible.
Time for the rest of the world to understand how the market works - here.
