### ISSUE TITLE
Report bug fix on product discount price

### ISSUE THREAD

**Issue by apw2012** [opencart/opencart#9748]
Open file: /system/library/cart/cart.php, location to function getProducts()

Just change below code from : 

if ($product_discount_query->num_rows) {
	$price = $product_discount_query->row['price'];
}

// Product Specials
$product_special_query = $this->db->query("SELECT price FROM " . DB_PREFIX . "product_special WHERE product_id = '" . (int)$cart['product_id'] . "' AND customer_group_id = '" . (int)$this->config->get('config_customer_group_id') . "' AND ((date_start = '0000-00-00' OR date_start < NOW()) AND (date_end = '0000-00-00' OR date_end > NOW())) ORDER BY priority ASC, price ASC LIMIT 1");

if ($product_special_query->num_rows) {
	$price = $product_special_query->row['price'];
}
			

to : 

if ($product_discount_query->num_rows) {
	$price = min($price, $product_discount_query->row['price']);
}

// Product Specials
$product_special_query = $this->db->query("SELECT price FROM " . DB_PREFIX . "product_special WHERE product_id = '" . (int)$cart['product_id'] . "' AND customer_group_id = '" . (int)$this->config->get('config_customer_group_id') . "' AND ((date_start = '0000-00-00' OR date_start < NOW()) AND (date_end = '0000-00-00' OR date_end > NOW())) ORDER BY priority ASC, price ASC LIMIT 1");

if ($product_special_query->num_rows) {
	$price = min($price, $product_special_query->row['price']);
}

**Comment by TheCartpenter** [comment]
How is that an issue and a solution?

**Comment by WebkulOpencart** [comment]
@apw2012 let us know what issue you are facing ?

**Comment by harman-jack** [comment]
Let me try to explain this issue and above solution:

> Case 1: Default 

Product Price: $22
Special Price: $20
Discount Price on purchase of 100 or more: $18.00

#### now customers want to purchase this item on discount price but it applies special price ($2000) even purchase quantity is 100 or more

![git_issue1](https://user-images.githubusercontent.com/55911839/125153114-3f076200-e16f-11eb-9610-76689924d869.PNG)

> Case 2: after applying above solution given by @apw2012 

Product Price: $22
Special Price: $20
Discount Price on purchase of 100 or more: $18.00

#### customers want to purchase this item on discount price and now they get what they actually wants ($1800) 

![git_solution1](https://user-images.githubusercontent.com/55911839/125153473-8e4e9200-e171-11eb-92de-151aff778eed.PNG)

> Conclusion:
@TheCartpenter and @WebkulOpencart 
### Customers want to purchase as possible as on a minimum price

**Comment by mhcwebdesign** [comment]
This is not an issue! By design, the special price, if there, takes precedence over the quantity discount price. The discount price, when there, takes precedence over the regular price.

**Comment by haxcop** [comment]
I Still Belive this is a Must to be Changed - _The Logic here_ "By Design" is **Wrong**
see 
https://forum.opencart.com/viewtopic.php?p=855646#p855646
