### ISSUE TITLE
[OC4 Master-branch] Error on installation with mPDO settings

### ISSUE THREAD

**Issue by SoftwareOnbekend** [opencart/opencart#9753]
Error on installing master-branch with mPDO

Created new DB.
Run :http://localhost/opencart-master-20210707/upload/install/index.php
![image](https://user-images.githubusercontent.com/40216653/124828722-ecb02080-df77-11eb-9199-eb4897e0b7b2.png)

Setup DB connection:
![image](https://user-images.githubusercontent.com/40216653/124828862-1e28ec00-df78-11eb-8ca7-b2f70de47376.png)

Error:
TypeError: Opencart\System\Library\DB\PDO::query(): Return value must be of type object|bool, none returned in E:\xampp\htdocs\opencart-master-20210707\upload\system\library\db\pdo.php on line 53

Result in phpMyAdmin:
![image](https://user-images.githubusercontent.com/40216653/124829061-647e4b00-df78-11eb-9027-cac909dcc299.png)

Restart install procedure from scratch:
http://localhost/opencart-master-20210707/upload/install/index.php
Result:
![image](https://user-images.githubusercontent.com/40216653/124829358-d0f94a00-df78-11eb-920f-0288d28755b4.png)
Result in phpMyAdmin:
![image](https://user-images.githubusercontent.com/40216653/124829632-20d81100-df79-11eb-9e03-c8262a4884a1.png)

Def env.
Windows 10
XAMPP 8.0.5

**Comment by SoftwareOnbekend** [comment]
mPDO ? What is de meaning of the letter 'm' in mPDO? Or is this a typo?

**Comment by anytizer** [comment]
Affected files:
https://github.com/opencart/opencart/blob/master/upload/install/language/en-gb/install/step_3.php#L10
https://github.com/opencart/opencart/blob/master/upload/install/controller/install/step_3.php#L109

**Comment by aartzrc** [comment]
This appears to be due to the return type in `upload\system\library\db\pdo.php` at `public function query(string $sql): bool|object`, I am running PHP 8.1.1 and have this problem. Quick solution was to add a return type at line 45: `return $statement->rowCount();`

<details>
<summary>Full code section</summary>
<p>

```php
public function query(string $sql): bool|object {
  $statement = $this->connection->prepare(preg_replace('/(?:\'\:)([a-z0-9]*.)(?:\')/', ':$1', $sql));
  
  try {
	  if ($statement && $statement->execute($this->data)) {
		  $this->data = [];
  
		  if ($statement->columnCount()) {
			  $data = $statement->fetchAll(\PDO::FETCH_ASSOC);
  
			  $result = new \stdClass();
			  $result->row = isset($data[0]) ? $data[0] : [];
			  $result->rows = $data;
			  $result->num_rows = count($data);
			  $this->affected = 0;
  
			  return $result;
		  } else {
			  $this->affected = $statement->rowCount();
			  // Add return statement
			  return $statement->rowCount();
		  }
  
		  $statement->closeCursor();
	  }
  } catch (\PDOException $e) {
	  throw new \Exception('Error: ' . $e->getMessage() . ' Error Code : ' . $e->getCode() . ' <br />' . $sql);
  }
}
```
</p>
</details>

**Comment by danielkerr** [comment]
i have updated the mpdo class and is working now.
