### ISSUE TITLE
To support non latin domains email must be converted to punycode before validating

### ISSUE THREAD

**Issue by likemusic** [opencart/opencart#9755]
https://github.com/opencart/opencart/blob/7692b27a878b2781407cf444ff7a55ef9b172120/upload/admin/controller/setting/setting.php#L603

```
FILTER_VALIDATE_EMAIL is discarding valid e-mail addresses containing IDN. Since there are real, live IDNs on the Internet, that means the filtered output is too strict, leading to false negatives.

Punycode-encoded IDN addresses pass the filter correctly; so before checking for validity, it is necessary to convert the e-mail address to punycode.
```

Source - https://www.php.net/manual/ru/filter.filters.validate.php#102398

**Comment by likemusic** [comment]
https://en.wikipedia.org/wiki/International_email

**Comment by stalker780** [comment]
Furthermore OC should have a separate system/helper method for email validation instead of repeated code.

**Comment by danielkerr** [comment]
most of the validation is just a a single line of code so no need to creating un-nessary new methods that people need to learn.

**Comment by danielkerr** [comment]
filter_var was supposed to handle all types of emails

**Comment by danielkerr** [comment]
i@[stalker780](https://github.com/stalker780) your just being a dick! its not my fault that I find this filter_var does not cover IDN! it comes out so i use it.

**Comment by danielkerr** [comment]
heres a load of emails i tedted

```
$emails = [
	'ghfh@renangonçalves.com',
	'用户@例子.广告',
	'ಬೆಂಬಲ@ಡೇಟಾಮೇಲ್.ಭಾರತ',
	'अजय@डाटा.भारत',
	'квіточка@пошта.укр',
	'χρήστης@παράδειγμα.ελ',
	'Dörte@Sörensen.example.com',
	'коля@пример.рф',
	'support@ツッ.com'
];
```
and results using punycode.

BEFORE ghfh@renangonçalves.com
AFTER xn--ghfh@renangonalves-kvb.com
VALID

BEFORE 用户@例子.广告
AFTER xn--@-lb7ap09a41gyrz.xn--4rr70v
INVALID

BEFORE ಬೆಂಬಲ@ಡೇಟಾಮೇಲ್.ಭಾರತ
AFTER xn--@-x9e2gh6cbr2ae2jpdrad9f.xn--2scrj9c
INVALID

BEFORE अजय@डाटा.भारत
AFTER xn--@-wtd3enj6f5eb.xn--h2brj9c
INVALID

BEFORE квіточка@пошта.укр
AFTER xn--@-7sbbf3bb1adizg8cs1q.xn--j1amh
INVALID

BEFORE χρήστης@παράδειγμα.ελ
AFTER xn--@-plbenblginz8a4bjfzbp4c.xn--qxam
INVALID

BEFORE Dörte@Sörensen.example.com
AFTER xn--drte@srensen-4ibf.example.com
VALID

BEFORE коля@пример.рф
AFTER xn--@-jtbigfikkjd2n.xn--p1ai
INVALID

BEFORE support@ツッ.com
AFTER xn--support@-i14gja.com
INVALID

**Comment by danielkerr** [comment]
php needs to fix this noot opencart

**Comment by stalker780** [comment]
@danielkerr You need to punycode email in parts
in `Dörte@Sörensen.example.com`
you need to punycode first `Dörte` and then `Sörensen.example.com` without `@`

With this approach filter_vars email check works correctly.

**Comment by stalker780** [comment]
@ADDCreative propose your PR
Issue exists for 3 years and is not solved yet.
OC still does not check emails correctly.

I don't beleive this is rocket science to make international emails check. Or we will wait another 10 years while it is fixed in PHP v100500.

**Comment by mhcwebdesign** [comment]
Maybe this helps: https://stackoverflow.com/questions/54867337/validate-international-email-addresses-with-php ?

**Comment by stalker780** [comment]
@mhcwebdesign I saw this. But did not want to use regex.

As I mentioned earlier it is best to move email validation into a separate helper function.

At least if it does not work correctly it will be much easier for developers to modify this function with OCMOD instead of modifying repeated code in 20 controllers. Daniel called me a dick for this 🤦‍♂️ Perhaps he had a bad mood, as he always does.

**Comment by ADDCreative** [comment]
@stalker780 and @mhcwebdesign Validating is just the tip of the iceberg and is pretty simple. Just convert the domain part to IDNA ASCII form and validate the email using filter_var with FILTER_FLAG_EMAIL_UNICODE.

Then the difficult bits of firstly changing how the email addresses are stored in the database and the and queries to fetch. Second, actually sending email reliably in the mail and SMTP classes. Not all MTAs will work the same.

Doing it wrong would cause security issues.

**Comment by danielkerr** [comment]
> @mhcwebdesign I saw this. But did not want to use regex.
> 
> As I mentioned earlier it is best to move email validation into a separate helper function.
> 
> At least if it does not work correctly it will be much easier for developers to modify this function with OCMOD instead of modifying repeated code in 20 controllers. Daniel called me a dick for this 🤦‍♂️ Perhaps he had a bad mood, as he always does.

you will never be able to create ur own function that will cover as much as php's own.

**Comment by stalker780** [comment]
@danielkerr I understand this.
I don't try to validate exotic emails like `"my@bulshit"@"example@com"` or `"this is v@lid!"@example.com`.

At least `info@пошта.укр` or `support@Sörensen.example.com` must work correctly. They do not pass validation now, same as any IDN domain.

What I want to achieve:
1. Make IDN domains work. This is very important for my country using cyrillic domains.
2. Make email validation function easy to modify with OCMOD if default validation does not satisfy user's needs.

Alas OC4 uses a lot of repeated code. And if you want to change functionality which does not suit your needs, you need to modify tens or even hundreds of controllers. While this code could be placed in one helper/controller/library where it is easy to modify or reroute it. This makes events and even ocmod development a lot harder resulting in lots of low quality extensions.

**Comment by danielkerr** [comment]
> @danielkerr I understand this. I don't try to validate exotic emails like `"my@bulshit"@"example@com"` or `"this is v@lid!"@example.com`.
> 
> At least `info@пошта.укр` or `support@Sörensen.example.com` must work correctly. They do not pass validation now, same as any IDN domain.
> 
> What I want to achieve:
> 
> 1. Make IDN domains work. This is very important for my country using cyrillic domains.
> 2. Make email validation function easy to modify with OCMOD if default validation does not satisfy user's needs.
> 
> Alas OC4 uses a lot of repeated code. And if you want to change functionality which does not suit your needs, you need to modify tens or even hundreds of controllers. While this code could be placed in one helper/controller/library where it is easy to modify or reroute it. This makes events and even ocmod development a lot harder resulting in lots of low quality extensions.

ur uneducated opinion
