### ISSUE TITLE
is opencart dead?

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#9757]
It has been over 1.5 months without updating from danielkerr.

**Comment by osworx** [comment]
19 days to be exact .. ( last commit was June 24, 2021 )

**Comment by mhcwebdesign** [comment]
OpenCart is not dead. The current stable release is 3.0.3.7, soon to be followed by the next maintenance release 3.0.3.8.
The masterbranch will eventually lead to a version 4, with some significant changes.
