### ISSUE TITLE
Fatal error: Cannot declare class JSMin, because the name is already in use in  / opencart

### ISSUE THREAD

**Issue by erdem-sicak** [opencart/opencart#9758]
Hey 

 How can I fix the mistake on piece of code, my admin panel don't open 

class JSMin {
  const ORD_LF            = 10;
  const ORD_SPACE         = 32;
  const ACTION_KEEP_A     = 1;
  const ACTION_DELETE_A   = 2;
  const ACTION_DELETE_A_B = 3;

**Comment by osworx** [comment]
This is not a bug and not related to OpenCart.
Therefore, please use the forum: https://forum.opencart.com/
Or contact the developer of that extension directly.
