### ISSUE TITLE
Wrong total while using different currencies.

### ISSUE THREAD

**Issue by imumang** [opencart/opencart#9760]
I am on https://demo.opencart.com/ , latest version.

I have tested this issue with Nikon D300 product. The price of the product is $98.

Add 100 pieces in the cart and visit cart page
it will show you 100 * $98 = 9800

if you change currency to GBP the amount changes
100 * £73.92 = £7392.32 (it should be 7392)

If you change currency to Euro the amount changes to
100 * €84.35 = €8435.19 (it should be €8435)

It is a rounding issue at the time of converting currency.

**Comment by webkul-dilip** [comment]
Hello,
Product price shows 2 digits after the decimal like
if the product price is 101 and currency value is 0.61250001 for GBP then the price will be 61.86250101, but at the store it will show 61.86 similarly when you select 100 quantity then it will show 6186.25(61.86250101*100=6186.250101)

**Comment by imumang** [comment]
Hi Webkul, I already know the issue is with rounding. 

When you receive an order for 100 pieces and price is £61.86 that multiply to £6186. 
In the accounting system, If you enter the same invoice 100 x £61.86 = 6186 and Opencart will show 6186.25. How would you adjust that 0.25 extra. 

Instead of showing 61.86 rate and calculating with 61.86250101 it should also round the rate 61.86 at the time of calculating therefore when someone buy 100 it multiply with rounded rate 61.86 instead of 61.86250101.

**Comment by WebkulOpencart** [comment]
@imumang As we already discussed such point with the Daniel earlier but this is not an issue.
You can check the same here:- [https://github.com/opencart/opencart/issues/9413](https://github.com/opencart/opencart/issues/9413)

**Comment by imumang** [comment]
I can understand your position as Daniel is the boss man, If he thinks wrong total in the invoice is not an issue, it's not an issue. I will try to convince my local government and tax authority that from now on 2 + 2 = 4.09 or something.

The real issue does not disappear only because the owner of the platform believes it is not an issue.

Does Danial believe that an invoice created on Opencart should also match when audited manually using calculator?

Is it that difficult to round the conversion rate and multiply with quantity to get correct total? I have bought Android and iOS app from webkul, why don't you guys make some extension to correct the issue and charge for it?

**Comment by WebkulOpencart** [comment]
@imumang if you want to fix this on your store, please mail to our sales team over sales@webkul.com they can guide you further process.

**Comment by ADDCreative** [comment]
> Is it that difficult to round the conversion rate and multiply with quantity to get correct total?

@imumang It would be nice if it was changed. However, it's not that simple when you have taxes and different settings. To make everything add up on the cart page all the calculations would have to be done after currency conversion/format. This would be a major change to the cart, totals and possibly payment modules. It also gives the issue of what you store in the database for each order, the default currency of the converted currency? Which raises more issues, such as will it affect the reports. You can see more discussion https://github.com/opencart/opencart/issues/9413#issuecomment-793708248.
