### ISSUE TITLE
$country_id - data type error

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#9762]
Error

![image](https://user-images.githubusercontent.com/5563341/126009380-3e91b6c0-59e7-4f28-9a0b-b9e9a600f362.png)

**Comment by anytizer** [comment]
This is seen in the browser alert box when visiting the cart page.
http://localhost/opencart/upload/index.php?route=checkout/cart&language=en-gb

**Comment by WebkulOpencart** [comment]
@anytizer please mention the OpenCart version

**Comment by anytizer** [comment]
It is in the master branch. Version 4.0.0.0_b

**Comment by anytizer** [comment]
The cart page is functional.
