### ISSUE TITLE
MOD: Modification Default

### ISSUE THREAD

**Issue by Sherbi** [opencart/opencart#9763]
I made install for OpenCart V.3.0.3.7 Without any Modifaction but I see this errors in Ocmode Log:

`
2021-07-17 19:28:40 - MOD: Modification Default
----------------------------------------------------------------
2021-07-17 19:31:28 - MOD: Modification Default

FILE: system/engine/action.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 69

FILE: system/engine/loader.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 77
LINE: 151
LINE: 168

FILE: system/library/config.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 59

FILE: system/library/language.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 67
LINE: 73

FILE: system/library/template/template.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 18

FILE: system/library/template/twig.php
CODE: if (is_file($file)) {
LINE: 13
----------------------------------------------------------------

`

I Made the Install on PHP 7.3, 7.4 and 8.0 With MySql 8

**Comment by WebkulOpencart** [comment]
This is default OpenCart mdification.xml file modification. 
You can found the same in the system/modification.xml
