### ISSUE TITLE
[Master Branch] - catalog/controller/api/order.php line 39

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#9773]
Unfinished: https://github.com/opencart/opencart/blob/master/upload/catalog/controller/api/order.php#L839

**Comment by TheCartpenter** [comment]
This one as well: https://github.com/opencart/opencart/commit/0efffe76f5e1abc94ba1b5e71ec14546d33c2d16#diff-0d8aa2ab0c6db00a9f39da7a4054a28c18952f8595d5591eb1ececc3514fb5deR817 .

**Comment by danielkerr** [comment]
no idea what the issue is. code has changed a lot
