### ISSUE TITLE
Re: more api fixes and changes 

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9775]
https://github.com/opencart/opencart/blob/689be0bd739c7f8b35fd670d55f67e6b8c1f534f/upload/admin/view/template/sale/order_info.twig#L2473

It looks like a typo `|` that should be deleted.

The line should be
`url: 'index.php?route=sale/order|call&user_token={{ user_token }}&action=cart/remove&store_id=' + $('select[name=\'store_id\'] option:selected').val(),`

In addition, all `upload-form` should be replaced with `form-upload`. Refer to OC4: Fix extension installer upload form #9711

**Comment by danielkerr** [comment]
done by session now
