### ISSUE TITLE
Reports page opens with menus

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#9776]
![image](https://user-images.githubusercontent.com/5563341/126226112-4eb97f88-aa7e-4f24-88ea-3e102fe8c8cd.png)

In the admin page, 
Link: http://localhost/opencart/upload/admin/index.php?route=report/report&user_token=___

The reports page opens with menus.
Version: 4.0.0.0_b (master branch)

Did not find enough information on the error - why so.
But I am running under PHP 8.

**Comment by cgcmart** [comment]
no issue in administrator panel in my multiple latest installations.

**Comment by anytizer** [comment]
Well, In my case: I have removed all the default products and categories right after the installation.

**Comment by anytizer** [comment]
Master branch now seems to be correct. Closing the issue.
