### ISSUE TITLE
Cannot upload image in the admin - globally.

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#9780]
![image](https://user-images.githubusercontent.com/5563341/126547524-a8fd8f6d-d44e-47b7-9d49-9c2ae0461b25.png)
Globally, cannot upload the new image.

JS Error there:
Uncaught TypeError: Cannot read property 'classList' of undefined

It should be related to Bootstrap 5 changes in master branch.

**Comment by cgcmart** [comment]
admin filemanager javascript issues:
upload/admin/view/template/common/filemanager.twig

**Comment by anytizer** [comment]
#9916 Related/Duplicate.

**Comment by danielkerr** [comment]
fixed

https://github.com/opencart/opencart/issues/10302
