### ISSUE TITLE
Common cart view issue

### ISSUE THREAD

**Issue by harman-jack** [opencart/opencart#9781]
**version - 4.0.0.0_b**

**Common cart view box spread in full width, that is not looking good.**

**To Reproduce**
1. Go to 'frontend'
2. Add product into cart
3. Click on 'Common Cart button' (top right corner)

![cart_looks_now](https://user-images.githubusercontent.com/55911839/126617453-32d418ae-6137-4e0e-9ab9-dba900430ae0.PNG)

**Server / Test environment (please complete the following information):**
 - Local development
 - Operating system - Windows 10
 - PHP version - 8.0.8
 - Apache version
 - Browser - Mozilla Firefox (90.0.1 (32-bit))

**I think it should be shown like previous version.**

![cart_like_this](https://user-images.githubusercontent.com/55911839/126617644-cfe1e03f-63d2-4f15-9a80-d2e781ca0f48.PNG)

**Comment by danielkerr** [comment]
fixed ages ago
