### ISSUE TITLE
Add to cart button alignment

### ISSUE THREAD

**Issue by harman-jack** [opencart/opencart#9782]
**version- 4.0.0.0_b**

**Add to cart alignment, quantity field alignment, quantity label alignment, and font size  are not looking good in compare to previous versions**

**To Reproduce**
1. Go to 'frontend'
2. Open product page

**Screenshots / Screen recordings**
![cart_button_alignment](https://user-images.githubusercontent.com/55911839/126621011-9ab20ecf-b74e-4775-bab8-ca2e4b3ae982.png)

**Server / Test environment:**
 - Local development
 - Operating system - Windows 10
 - PHP version - 8.0.8
 - Browser - Mozilla firefox(90.0.1 (32-bit))
 
 **Solution**
>Use from-group classes

instead of using

>class="row mb-3"

**Comment by danielkerr** [comment]
k think already fixed
