### ISSUE TITLE
problem saving in edit

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#9793]
Error returns because data exists.  not updating. in all files product, category ...

https://github.com/opencart/opencart/blob/feb5f084a1deebfb835af3e63bae4d90ce631110/upload/admin/controller/catalog/category.php#L377

**Comment by mhcwebdesign** [comment]
Please be more specific and describe the exact steps leading to your error!

**Comment by anytizer** [comment]
I got similar issue.

You might have added a new store after adding a product, and then tried to edit the product again.
If this is the case: please edit the SEO fields for all edits you make in the SEO Tab.

However, would you please explain your problem in details, @eturerer ?

**Comment by danielkerr** [comment]
this has been fixed
