### ISSUE TITLE
Master Branch 4.0 has currency formatting issue.

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#9795]
Unacceptable return value at:

    $this->currency->format($result['price'], $this->config->get('config_currency')),

File/Line:
https://github.com/opencart/opencart/blob/master/upload/admin/controller/catalog/product.php#L199

The admin panel list of products returns empty while formatting currency, within the controller.
In my case, I have created my currency CAD as default, not USD.

**Comment by TheCartpenter** [comment]
I did covered last week the user-defined value of 1.000000 . Does it happen on other controllers, so far, or only on this one with the CAD currency?

**Comment by TheCartpenter** [comment]
Also, is your auto-currency set to on or off?

**Comment by anytizer** [comment]
Not sure. I deleted unused currencies, and modified the default to become CAD.
![image](https://user-images.githubusercontent.com/5563341/127254383-555f1800-1eb2-4fb4-ad02-d76c7e041c2c.png)

The data is lost in the controller (null or empty value).
I will send further details of the issue if I find.

**Comment by anytizer** [comment]
I learnt that somehow: the script tried to convert the currency into USD, which is impossible.
Location: upload/system/library/cart/currency.php#L25

I have no references to the old default currency elsewhere probably except in the cached configs.

**Comment by anytizer** [comment]
![image](https://user-images.githubusercontent.com/5563341/127263490-fc77e8a0-9eb6-4a0d-b30f-ce463a6357e3.png)
For each store in the admin > settings, I edited them once to reset their currencies, and it got fixed :-)

Final thoughts:
There is still a chance for other merchants to have this kind of configuration error.
Should we still debug the problem?
