### ISSUE TITLE
OC4: Multilanguage tabs bug

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#9848]
Don't know if anybody reads comments to commits.
But will duplicate this information here. Otherwise it will be lost and bug will be present in release:

This does not work:
`{% if languages.index == 0 %} active{% endif %}`

It makes all language tabs active.
Need to use:
`{% if loop.index == 1 %} active{% endif %}`

https://github.com/opencart/opencart/commit/965786c5cb3f6df3435b1917006a0bf514cfb6a5#r53884197

https://github.com/opencart/opencart/commit/965786c5cb3f6df3435b1917006a0bf514cfb6a5#r53884703

**Comment by danijelGombac** [comment]
Or `{% if loop.first %} active{% endif %}`

**Comment by stalker780** [comment]
Or else use common.js to activate first tab on page load if no active inside .nav-tabs

**Comment by TheCartpenter** [comment]
https://stackoverflow.com/questions/30468111/bootstrap-shown-bs-tab-event-not-working

**Comment by stalker780** [comment]
Any chance on this to be fixed before release?

All multilanguage forms are still broken
This `{% if languages.index == 0 %} active{% endif %}` does not work

**Comment by stalker780** [comment]
@danielkerr 
Please pay attention at this issue.

All multilanguage forms tabs are still broken. 
Perhaps this can be fixed while you are working on admin forms now.

**Comment by stalker780** [comment]
The best is to use common.js script on document.ready

```
$('.nav-tabs').each(function(k,v) {
	if (!$(this).find('.nav-item .nav-link.active').length) {
		(new bootstrap.Tab($(this).children('.nav-item:first').find('.nav-link')[0])).show();
	}
});
```

**Comment by danielkerr** [comment]
https://twig.symfony.com/doc/3.x/tags/for.html
