### ISSUE TITLE
Admin change store(or other images) does nothing.

### ISSUE THREAD

**Issue by Mgarm7351** [opencart/opencart#9862]
Version 3.0.3.7

Click Settings -> General
  Store Image:
      Click 'EDIT' button on the store image
       NOTHING HAPPENS
  Select Store Tab
       Click Image 'EDIT' button
       NOTHING HAPPENS

Same result no matter what image you try to change.

**Comment by ADDCreative** [comment]
There is no Settings -> General and the edit in the store tab works for me. You would be best to ask on https://forum.opencart.com/.

**Comment by mhcwebdesign** [comment]
Unable to reproduce this error, the issue is most likely caused elsewhere, e.g. 3rd party extension or other modifications. Please re-post on the OC forum for support.

**Comment by Mgarm7351** [comment]
> There is no Settings -> General and the edit in the store tab works for me. You would be best to ask on https://forum.opencart.com/.

Not any more...  I give up on this .....  spending way too much time with what shoud be just plain old press button, install theme, select it as the current one...  But in opencart..  nope...  I guess it can't be 1st class premium grade unless you make it hard as hell to use..  Keep up the good work and friendly assistance...

**Comment by anytizer** [comment]
I guess, it is not yet finished in the oc master branch.
Perhaps, Image manger javascript is broken globally.

https://github.com/opencart/opencart/issues/9780
