### ISSUE TITLE
[Master Branch] - admin/controller/common/login.php file

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#9863]
@danielkerr: I am wondering if this line is as safe to add:

```$json['redirect'] = $this->request->post['redirect'] . '&user_token=' . $this->session->data['user_token'];```

since the modification of the true case statement with JS from the $this->url->link especially when JSON headers is used. Using $this->request->post['redirect'] in this case would indicate that JS lookups would not need to be implied prior to redirection when HTTP_SERVER is validated as opposed to the else statement ...

Before the JS lookup modification in the $this->url->link , it was simply easier to figure that it was due to the SSL lookup. Nowadays, the JS takes place during JSON redirection which means that $this->request->post['redirect'] could still create higher levels of risks.

**Comment by TheCartpenter** [comment]
In catalog/controller/account/login.php file, we can notice that:

```$json['redirect'] = str_replace('&amp;', '&', $this->request->post['redirect']) . '&customer_token=' . $this->session->data['customer_token'];```

is rather used. Should it be considered to be used with the user_token as well?

**Comment by danielkerr** [comment]
its got security here

			if ($this->request->post['redirect'] && (strpos($this->request->post['redirect'], HTTP_SERVER) === 0)) {
				$json['redirect'] = $this->request->post['redirect'] . '&user_token=' . $this->session->data['user_token'];

i think the issue4 is old
