### ISSUE TITLE
For discussion, if it applies regarding sales return

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#9908]
I am not sure if it is worth mentioning for a discussion.

A future order ID is likely to have a sales return data, before the Order ID is created.
https://github.com/anytizer/opencart/issues/3

What do you think?

**Comment by TheCartpenter** [comment]
The order ID would still need to be created prior to have return sales ID since service providers still needs to validate the payment transaction prior to create a returned status order ID.
