### ISSUE TITLE
[Master Branch] filemanager will not pop up when click on image edit button.

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#9916]
[Master Branch] filemanager will not pop up when click on image edit button.

**Comment by TheCartpenter** [comment]
Any error message with it? More info is needed.

**Comment by chongshengdz** [comment]
> Any error message with it? More info is needed.

no error, just won't pop up filemanager.

**Comment by TheCartpenter** [comment]
That's because you haven't checked your developers tool in your console or network tab for any errors.

**Comment by chongshengdz** [comment]
> That's because you haven't checked your developers tool in your console or network tab for any errors.

"clear" button works fine, but the "edit" button will not work, filemanager will not pop up when click on it.

**Comment by TheCartpenter** [comment]
So what does it show in Developers Kit when clicking on the Edit button of the file manager?

**Comment by chongshengdz** [comment]
> So what does it show in Developers Kit when clicking on the Edit button of the file manager?

where to see this error?

**Comment by cgcmart** [comment]
javascript source code commented out on opencart master file
upload/admin/view/javascript/common.js line 343 - line 452

Javascript code issue Javascript language mode: "use strict" #9925

**Comment by chongshengdz** [comment]
> So what does it show in Developers Kit when clicking on the Edit button of the file manager?

Uncaught TypeError: Cannot read property 'classList' of undefined
    at Ne._isAnimated (modal.js:354)
    at Ne._initializeBackDrop (modal.js:220)
    at new Ne (modal.js:84)
    at HTMLButtonElement.<anonymous> (common.js:457)
    at HTMLDocument.dispatch (jquery-3.6.0.min.js:2)
    at HTMLDocument.v.handle (jquery-3.6.0.min.js:2)

**Comment by danielkerr** [comment]
should be fixed what ever the issue was i can not replicated on the master branch
