### ISSUE TITLE
AWS Usage

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#9928]
Where is the AWS sdk used in master branch oc4?

This composer component is probably not in use at the moment.

**Comment by danielkerr** [comment]
i have removed all 3rd party extensions. you should be able to get one from the marketplace.

**Comment by anytizer** [comment]
https://github.com/anytizer/opencart/blob/423b42b8479a07b1fdd42e6a13f14c48a1b5eee4/composer.json#L28 live should also be removed, unless it is used elsewhere.
